### ISSUE TITLE
[BUG] Minecolonies crash attempting to load NBT data

### ISSUE THREAD

**Issue by iamnoobplzhelp** [ldtteam/minecolonies#10009]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.20.1-1.1.601-BETA

### Structurize Version

1.20.1-1.0.738-BETA

### Related Mods and their Versions

1. Forge Version: 47.2.20
2. domum_ornamentum-1.20.1-1.0.187-BETA-universal
3. blockui-1.20.1-1.0.156-RELEASE
4. multipiston-1.20-1.2.43-RELEASE

### Current Behavior

Was playing on a personal ATM9 server with Minecolonies when the server crashed due to this error.
Manually updated the ATM9 version to the latest (0.2.61), did not fix the issue
Manually updated Minecolonies, Structurize, and Domum Oranmentum to the latest versions, did not fix the issue

### Expected Behavior

The server to start and Minecolonies is playable

### Reproduction Steps

1. Attempt to start the server, server crashes

### Logs

https://gist.github.com/iamnoobplzhelp/6c0ea057b311b7bfd4d6079028eb5328

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
I believe there was another server crash before which resulted in file corruption. Try going into the minecolonies folder in your world and replacing the current backup with a previous one.

**Comment by iamnoobplzhelp** [comment]
> I believe there was another server crash before which resulted in file corruption. Try going into the minecolonies folder in your world and replacing the current backup with a previous one.

You're absolutely right. I honestly didn't even know Minecolonies took their own backups until now. I used one of the previous Minecolonies backups and it started right up. Thank you! Please consider this resolved
