### ISSUE TITLE
[BUG] Buiders doesn't teleport after invalid pathfinding / stay stuck

### ISSUE THREAD

**Issue by TheRocket81** [ldtteam/minecolonies#10003]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.20.1-1.1.597

### Structurize Version

1.20.1-1.0.737

### Current Behavior

Builders aren't teleporting when stuck. Sample scenarios: 
1- Builder builds a wall of fences around him, 
2- Builder locks himself in a room, 
3- Builder have feet in an air block, head is in a upper closed birch trapdoor, no path to escape. 

You create a path to escape, it won't move. While other workers (crusher worker) escape immediately.

![2024-06-24_23 49 42](https://github.com/ldtteam/minecolonies/assets/109647859/2dfd46b4-0fd9-4c8b-b31d-dd4a79bb4e72)

The builder won't teleport, waited at least ~27 minutes IRL.

### Expected Behavior

Builder should try to path-find again after a few seconds?
Builder should teleport to a valid 2 high-air-block-solid-block-underneath nearby when no path is found for x times?
Builder could interact with player saying "I need help at building X" after too many invalid pathfinds?
At least, builder should teleport to bed at night as a fail safe. Builder says "Sleeping" but still stands at the jobsite.

### Reproduction Steps

With Medieval birch:
A- Create a mine from a flat surface. builder will dig, start placing cobble ring at the bottom, place himself in the center of the ring, and place fence post around him. He is stuck. Won't teleport out.
B- Upgrade a sifter from level 1 to level 2. Builder locks himself in the little room on the first floor. Won't teleport at night.
C- Upgrade a crusher from level 2 to level 3. Builder get stuck underneath trap doors near crusher.
D- Builder and other workers uses rails of said crusher to move around. disembark the rails under the trapdoors of the crusher. Builder won't teleport out. Builder won't pathfind out, even if we create a 2 high path underneath

### Logs

https://pastebin.com/AwG9c4wp

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by mateuspina69** [comment]
Not only they are not teleporting, but they seem to struggle to pathfind after i upgraded my world from 1.19.2 to 1.20.1 (latest). I had some buildings in a cave underground (around -40) and they were able to reach them by the mines. Now they can't.

**Comment by Raycoms** [comment]
solved

**Comment by Vwhbj2003** [comment]
How was this solved? I'm having the same issue.

**Comment by schealex** [comment]
same here @Raycoms

**Comment by Shadizar** [comment]
Plus 1
1.20 787, folks almost never teleport and get stuck constantly

**Comment by Raycoms** [comment]
The issue underlying this was solved. The rest is https://github.com/ldtteam/minecolonies/issues/10522
