### ISSUE TITLE
[BUG] Null pointer exception in client upon joining server

### ISSUE THREAD

**Issue by evhub** [ldtteam/minecolonies#10011]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.20.1

### MineColonies Version

1.1.601-BETA

### Structurize Version

1.0.737-BETA

### Related Mods and their Versions

See <https://bytebin.lucko.me/rdHg1A56qI>.

### Reproduction Steps

Client was initially able to join fine, then due to unknown cause now cannot join and instead gets this null pointer exception: <https://bytebin.lucko.me/rdHg1A56qI>

### Logs

https://bytebin.lucko.me/rdHg1A56qI

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by cyberNinja6143** [comment]
I looked into it and submitted a pull request that fixes the issue.
