### ISSUE TITLE
[BUG] 1.1.601 excessive "I will come along and do pickup shortly" messages using stash

### ISSUE THREAD

**Issue by EurypteriD192** [ldtteam/minecolonies#10010]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [X] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.1.601

### Structurize Version

1.0.738

### Related Mods and their Versions

Forge 47.2.0

### Current Behavior

When adding 4 items to stash you instantly get 4 messages for the items. But you also get them when someone is comming to pick up. 

https://cdn.discordapp.com/attachments/1003402487417548801/1257039000351543399/image.png?ex=6682f44c&is=6681a2cc&hm=7a5bb6efd9a5b1f5e5d66cefceea7356a0f9dc2bf989dc54a97a36fda9516b6d&

https://cdn.discordapp.com/attachments/1003402487417548801/1257039000724574328/image.png?ex=6682f44c&is=6681a2cc&hm=4a0f9bbf0bb5134dcdcb876d3b9381d40d3abe33723151a30ac8453833e4bbe3&

### Expected Behavior

Before on 596 it was correct, where they only said it when they was on the way to pick up. 

### Reproduction Steps

Build stash.
build warte house
add couriers
add items to stash take note of items and keep eye on chat

### Logs

https://paste.ee/p/obsoT

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by cyberNinja6143** [comment]
I was unable to replicate this issue even when I put 4 items separately into the stash. Are you using the latest version?

**Comment by EurypteriD192** [comment]
I’m on the build mentioned in the report.

And my world reproduces all the time like 20 min ago I put 10 stacks In got
10 messages and the one message for each pick up.

If there’s a newer version I can try to update tomorrow.

**Comment by someaddons** [comment]
![image](https://github.com/ldtteam/minecolonies/assets/38401808/7949c310-ae49-4bea-8a15-639ebfd1d92e)
I can reproduce it just fine 🤷 
make sure you're using version/main branch

**Comment by cyberNinja6143** [comment]
> ![image](https://private-user-images.githubusercontent.com/38401808/346222944-7949c310-ae49-4bea-8a15-639ebfd1d92e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyNTIxODMsIm5iZiI6MTcyMDI1MTg4MywicGF0aCI6Ii8zODQwMTgwOC8zNDYyMjI5NDQtNzk0OWMzMTAtYWU0OS00YmVhLThhMTUtNjM5ZWJmZDFkOTJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA2VDA3NDQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiMTg4YmFmMWFiMzBiYTU2YzFmMjgyMTQ3ZjE5ZjgyMzBjNjA4MGMwZDIzZGE3ZGQyOWQ4OGY1ODkxNTYxZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IpeCHb_SyP_W47ZI7FcbWgxlx38fu5OHr797sSxhOSY) I can reproduce it just fine 🤷 make sure you're using version/main branch

You're right, I didn't put more than one stack in. I tried looking into what's causing it and unfortunately I don't understand the codebase well enough to fix it. Is anyone currently working on a fix?

**Comment by EurypteriD192** [comment]
I am using main. Currently updating to 602
:)

**Comment by EurypteriD192** [comment]
It even reproduces on 602, and its everytime an item enters like if you use
right click to add 1 piece of something and each click it pops up.

**Comment by EurypteriD192** [comment]
I am stepping away from helping the mod, community after guidance from moderators.
