### ISSUE TITLE
UI improvements

### ISSUE THREAD

**Issue by kaiytech** [ldtteam/minecolonies#10021]
side note: Thodor12 suggested on Discord to post this here instead of the minecolonies-features repo.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.20.1

### Structurize Version

1.20.1-1.1.581-BETA

## Is your feature request related to a problem?
The warehouse UI requires some changes, there's a lot of free screen space that could be used to fix the UI.

## Enhancement or Change description

# Warehouse UI
![image](https://github.com/ldtteam/minecolonies/assets/5287083/5e7efb6c-6cf8-4edb-9b42-de586bc0426c)
- Expand the scroll viewer, move the buttons to the bottom of the page

![image](https://github.com/ldtteam/minecolonies/assets/5287083/8c42d790-9c5e-4190-ac92-7dd8220103f1)
- Don't show -1 if on max level (sounds like a bug? both "-1" and "0/1" should be hidden)

![image](https://github.com/ldtteam/minecolonies/assets/5287083/7cad11ae-206c-4e62-b767-f219fda2fd9e)
- move the scroll veiwer to be closer to the 'minimum stock' label
- expand the scroll viewer so it reaches the bottom
- change the add button to be a "+" and move it to upper-right corner to be more aligned with ui principles 

# Builder's hut UI
![Untitled](https://github.com/ldtteam/minecolonies/assets/5287083/37d614de-4184-467c-8f3b-d05c37f0a603)
(the above is a suggested redesign of the recipes list! not the actual screenshot from the game)
- move 'List of recipes' to the upper-left corner
- move the 'teach recipe' button to the upper-right corner and make it a simple "+"
- add a search box between the top label and the scroll viewer
- extend the scroll viewer so it's larger
- move the 'x of x' label to the bottom
- (not shown on the pic) make the custom recipe items smaller, because they are not 3x3 and don't need to be so tall
I'd also suggest adding a custom 2-page formatted page for the builder's hut, so the left stays the same (or similar) but the right represnts the required resources and current building task

# Generic
- add a 'requests' button to the 'crafting recipes' option for huts, just like it works in 'custom recipes'
- add 'stats' to all huts, not just miners, etc..
- remove 'inventory' from huts that don't interact with the inventory at all, like houses or courier's hut 
![Untitled](https://github.com/ldtteam/minecolonies/assets/5287083/8ce066aa-95cb-4449-85cb-cd283c75dc40)

- center the 'or' in the research tab

### Notes or related things
n/a

---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### Expected Behavior

n/a

### Reproduction Steps

n/a

### Logs

n/a

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
The inventory of residences and courier's huts can still be used by players, e.g. as temporary storage space, or in case of a courier's hut, as a sort of manual, larger stash (if the courier's hut has racks as well). You can order a pickup from there to have those items be sent to the warehouse
