### ISSUE TITLE
[BUG] JEI errors with new chef 

### ISSUE THREAD

**Issue by Talyda** [ldtteam/minecolonies#10036]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

.606

### Structurize Version

.742

### Current Behavior

![image](https://github.com/user-attachments/assets/e62c09a0-4962-4235-a995-adedc9bf2647)

JEI is showing only the chef as worker to make stuff that the cook should be doing as well (regular smelting recipes) 

Also not sure if this is a translation key thing (name of the worker in this screenshot)

### Expected Behavior

cook still showing up

### Reproduction Steps

search JEI

### Logs

can grab them later if you need them

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
> JEI is showing only the chef as worker to make stuff that the cook should be doing as well (regular smelting recipes)

The chef is also the one who can cook steak, mutton, etc. on request, so JEI is right about that.
The cook can't make that on request, which is why they don't have a JEI tab

**Comment by Talyda** [comment]
Oh, that makes sense! Cheers Train!
