### ISSUE TITLE
Missing Textures. All the textures!

### ISSUE THREAD

**Issue by Galindorf** [ldtteam/minecolonies#1003]
### Minecolonies version
minecolonies-universal-1.11.2-1.4.9.4
Mods: 
Forge 1.11.2-13.20.0.2228
Texture Pack: Chroma Hills 128x1.10-v1
![screen shot 2017-05-15 at 3 47 52 pm](https://cloud.githubusercontent.com/assets/17105217/26078763/2e645cb8-3986-11e7-8d23-443d9e669026.png)

### Expected behavior
Open world, be able to view world

### Actual behaviour
Missing Textures, but only when Minecolony is loaded.
![screen shot 2017-05-15 at 3 42 25 pm](https://cloud.githubusercontent.com/assets/17105217/26078867/75bbaef4-3986-11e7-86cd-bc54bcf55c8b.png)

Particles were viewable, and select item icons would show, see screenshot. Any ideas?

### Steps to reproduce the problem

1. Install Minecolonies by dragging into Mods Folder
2. Open a Minecraft World
3. ...
4. Profit

**Comment by Raycoms** [comment]
Please post your startup log.

It seems like you're using a texturePack.

**Comment by Galindorf** [comment]
Wow, thanks for the fast response! 

Actually, upon further investigation, and testing, it appears to be incompatible with OptiFine. I am using a texture pack, "Chroma Hills 128x1.10-v1." 

It works just fine with all the other things I have installed; it's just really choppy without the Optifine.

**Comment by Raycoms** [comment]
Yeah minecolonies is not compatible with optfine because of the rendering
our build-tool does.

2017-05-15 18:48 GMT-03:00 TheeLadyG <notifications@github.com>:

**Comment by Galindorf** [comment]
Do you have any other suggestions? A couple of my mods really function 100x better with OptiFine on. (particularly Better Foliage)

**Comment by Raycoms** [comment]
I think there are some other mods like better fps etc which should also
improve things but without the optifine problems.

2017-05-15 20:22 GMT-03:00 TheeLadyG <notifications@github.com>:

**Comment by marvin-bitterlich** [comment]
@Galindorf you can try asking on the discord, some players use optifine like mods with success. 

It is just that we can't support it properly for all the changes it does

**Comment by SulpherStaer** [comment]
I successfully use optifine - and am on the 1.10.2 version that's given with the curse launcher. (I've added several other mods myself)

So, with the actual package offered, optifine works. So it must be a conflict between something you have yourself.

Try optifine and minecolonies on its own, and then slowly add in other mods.

**Comment by Galindorf** [comment]
Oh that's good to know! I actually did try Minecolony  on its own with 
OptiFine and got the error. I'm using Forge and 1.11.2... but this gives me 
hope that it may get worked out at some point. Thanks, mate!

**Comment by Raycoms** [comment]
Did you try it without a texturepack?

2017-05-16 14:47 GMT-03:00 TheeLadyG <notifications@github.com>:

> Oh that's good to know! I actually did try Minecolony on its own with
> OptiFine and got the error. I'm using Forge and 1.11.2... but this gives
> me
> hope that it may get worked out at some point. Thanks, mate!
>
>

**Comment by Galindorf** [comment]
By Jove, it DOES work if I take off the Chroma Hills texture pack. I wonder why that is? 

So basically it's only the addition of the Chroma Hills texture pack with OptiFine that causes the error. hmmm...

Edit: I tried updating to a newer version of the TexturePack designed for 1.11, but I had the same result. Do you think it may be because the texturepack is at 128?

**Comment by AndrewTru** [comment]
@Galindorf from what I can tell looking it over when you use OptiFine and that pack the Minecolonies mod adds stuff that the pack can't account for so Minecraft sees them as missing and most item systems do this or the broken texture as a byproduct. @Raycoms do you think this can be fix with the API? Once you get that working that is.

**Comment by Raycoms** [comment]
In this case I assume there is nothing we can do, I suppose if someone
makes a stylepack compatible with minecolonies things should work.

2017-05-22 9:38 GMT-03:00 AndrewTru <notifications@github.com>:

**Comment by AndrewTru** [comment]
@Raycoms good point, I am still getting use to the back office side of minecraft mods.

**Comment by Galindorf** [comment]
Thanks guys, I've been doing a revamp of our usual game with updates and 
interesting new mods, and found yours is not the only one I have this issue 
with. It is also an issue with Animania and Chisels & Bits. Interestingly, 
I got Chisels & Bits to work with Chroma Hills + OptiFine on my Surface 
Book Pro laptop. This leads me to suspect it may be a graphics card problem 
with my desktop, which is a 2011 iMac. hmmmmm.... more testing to do

**Comment by Galindorf** [comment]
I've got both computers open and can confirm: Minecolonies + Optifine + Chroma Hills works just fine on the Surface Book. I think what I'll do is leave Optifine off of my desktop for now. 

Also, I can highly recommend the Chroma Hills texture pack. I've played with a lot of them and this is what I always come back to. ;)

**Comment by Raycoms** [comment]
I think I can close this here then.
