### ISSUE TITLE
[BUG] Translation missing for some of the food items

### ISSUE THREAD

**Issue by MotionlessTrain** [ldtteam/minecolonies#10033]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

version/main (DEV environment)

### Structurize Version

1.20.1-1.0.740-BETA

### Current Behavior

When I look for a food item to give to a citizen in JEI, I see the name `item.minecolonies.muffin` and item description `com.minecolonies.core.item.food.tooltip.baker`, where I would have expected something like "Muffin" and "This item can be crafted at the bakery" (or something like that)
(Using the default English (US) language)

There are more items with missing translations, the Chef's JEI window doesn't have text, and a lot of the food items

### Expected Behavior

The food items and JEI window should show the english name/description/text

### Reproduction Steps

1. Look up "food" in JEI
2. Press "r" whilst hovering over item.minecolonies.pasta_tomato
3. The com.minecolonies.job.chef tab doesn't seem to give a lot of useful information

### Logs

I found this whilst debugging something else, so my log is cluttered with debug messages from that, and I don't believe missing translations yield log warnings

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
![2024-07-14_14 31 34](https://github.com/user-attachments/assets/ce0f4b05-f9ee-4974-9cef-ff8df5e79ee0)

They show fine for me

**Comment by MotionlessTrain** [comment]
This seems to be something that went wrong when running the dev environment. Rerunning minecraft within the dev environment fixed it

**Comment by Talyda** [comment]
![image](https://github.com/user-attachments/assets/6bf10bdb-70df-4016-96a7-00eab7ee1c10)
I know you closed this, but is this the same thing (translation key?)  Didn't want to open a new issue if it isn't =p

Oh, I might have to start a new issue - all the thins are showing that the chef is the crafter for them now, like cooked mutton, which should be regular old cook, is showing in JEI as the new chef.

So ignore all this and I will start a new issue LOL
