### ISSUE TITLE
[BUG] Removing recipes that are Built-In on a hut might either crash or reset the whole list

### ISSUE THREAD

**Issue by AylanJ123** [ldtteam/minecolonies#10047]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.1.601-BETA

### Structurize Version

1.0.738-BETA

### Related Mods and their Versions

Forge 47.2.23

### Current Behavior

When removing recipes in a quick succesion (which are built in like the copper state recipes on the Mechanic) might crash the client  with an OutOfBounds exception or might clean the whole recipe list. 

### Expected Behavior

Removing recipes that are built in should:

- Not be allowed (Grey button)
- Not work (Just doesn't get removed)
- Keep the current behaviour of coming back after a couple seconds but shouldn't crash or reset when doing it

### Reproduction Steps

1. Make a multiplayer world (Couldn't get it to happen on single player maybe because the laptop is faster than the server on Single Player.
2. Add some recipes along with the default ones (Easier to test on a lvl 1 Mechanic).
3. Remove them quickly and there is a chance for any of both situations to happen.

### Logs

https://mclo.gs/ZwgeCOb

### Anything else?

Couldn't get it to happen on a clean install, maybe because I tested on Single Player.

**Comment by AylanJ123** [comment]
Both bugs happen on BlockUI, might be related to https://github.com/ldtteam/BlockUI/issues/93

**Comment by Raycoms** [comment]
same issue as ldtteam/BlockUI#93 closing in favor of that one
