### ISSUE TITLE
[BUG] Farmers cannot farm tomatoes and rice

### ISSUE THREAD

**Issue by kaiytech** [ldtteam/minecolonies#10055]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.20.1-1.1.581-BETA

### Structurize Version

n/a

### Related Mods and their Versions

n/a

### Current Behavior

Fields have a select option for seeds. Tomatoes and rice are listed as crops they can farm (from Farmer's Delight).
Farmers do not want to farm them, for some reason - maybe they are coded differently, i don't know.

### Expected Behavior

Best to fix this is issue would be by either:
- removing incompatible seeds from the Field selection
- adding support for currently incompatible seeds

### Reproduction Steps

1. click on the Field block
2. pick tomato or rice
3. farmer won't do anything (but the courier will supply the needs)

### Logs

n/a

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
That would be mod compat ye. https://github.com/ldtteam/minecolonies-features for this

**Comment by Thodor12** [comment]
The actual reported issue is that we should be de-listing modded seeds from the field (as they can't be cultivated)

**Comment by kaiytech** [comment]
thank you for reopening, sorry if i didn't make this clear. it shouldnt list incompatible seeds in the Field block (also the official modpack ships with Farmer's Delight which makes it double confusing), cheers

**Comment by Raycoms** [comment]
We cannot easily automatically detect which modded crops work and which don't. We should not just auto remove all modded ones.

**Comment by Thodor12** [comment]
Can't we solve this via a tag `minecolonies:seeds`, let datapacks decide which ones are allowed and which ones aren't?

**Comment by Raycoms** [comment]
Yes, we can. That's why this is a feature request for modded compat and not a "bug". 99% modpacks won't set that properly though.

**Comment by kaiytech** [comment]
thank you for your replies.
could you please consider mentioning on the wiki that not necessairly all listed seeds from other mods will work?

**Comment by Thodor12** [comment]
Generally we don't include implementation details on the wiki

**Comment by Shadizar** [comment]
But isn't that last comment a player facing one?
It does get asked very often

**Comment by Raycoms** [comment]
I think it's fine to include in the wiki some "Note, not all modded seeds will work"

**Comment by Don-Vega** [comment]
so the farmers delight not work with minecolonies or builders paradise 2?  just asked cause i downloadet the latest version with include minecolonies and the assistend cook cannot even use the cutting board witch is needet to make the patty for the cook to create the learned buger recepie all they do is create the vanilla recepies like steak and on
