### ISSUE TITLE
Missing coremod.gui

### ISSUE THREAD

**Issue by DarkStone269** [ldtteam/minecolonies#1005]
Minecolonies version

version 1.11.2-0.7.811

### Expected behavior

- XXX

### Actual behaviour

- YYY

### Steps to reproduce the problem

1. XYZ
2. ZYX
3. ...
4. Profit

This is what i'm seeing when i click on any of the podiums
![image](https://cloud.githubusercontent.com/assets/28727490/26098677/20582740-39ee-11e7-8a98-7e6432e4a44d.png)

**Comment by SulpherStaer** [comment]
That's a localisation issue. Update to the latest version, as things have changed.
