### ISSUE TITLE
[BUG] <Restaurant cooking disabled food without limit>

### ISSUE THREAD

**Issue by SnowySakura1** [ldtteam/minecolonies#10050]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

Tropical Colonies 1.8 

### Structurize Version

1.20.1-1.0.742

### Current Behavior

![7c543ec1-479c-42d6-b6d8-ae4667b0e36f](https://github.com/user-attachments/assets/b554e578-3d69-4d36-95c9-c12df9bb6376)

### Expected Behavior

Once u add a fuel type, the restaurant starts cooking cod, salmon and potatoes despite not being listed anymore. 

### Reproduction Steps

1. select the fuel type 
2.  the cook will start cooking previously mentioned food 

### Logs

https://gist.github.com/SnowySakura1/c36e604a7a3c54cee3ea82bac6b4309b

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
There was already an issue too Ray:
https://github.com/ldtteam/minecolonies/issues/9944

**Comment by Raycoms** [comment]
referred to both in my PR then
