### ISSUE TITLE
create mod / mincolonies

### ISSUE THREAD

**Issue by Arpello** [ldtteam/minecolonies#10063]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.20.1-1.1.593

### Structurize Version

1.20.1-1.0.737

### Current Behavior

I'm using the fantasy style the builder wants an brass encased shaft, i can make it but i can not pick it up without it going to its original pieces.  how do you give the builder the encased shaft.

### Expected Behavior

i expected to be able to pick it up once made so i can give to builder

### Reproduction Steps

1. put shaft down hit it with a brass casing
2.  get brass encased casing
3.  try to pick it up
4.  check inventory and see its back in the individual pieces. { shaft, and brass casing } 

### Logs

do not have log

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
You need to report it to the style designer on discord
They have a thread for it here: https://discord.com/channels/139070364159311872/1145401819535777883 (though I think they may already have been informed of that one)
