### ISSUE TITLE
[BUG] <Game Freezes and Crashes When Accessing Colony with New Account>

### ISSUE THREAD

**Issue by LemCsZ** [ldtteam/minecolonies#10078]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

minecolonies-1.20.1-1.1.601-BETA

### Structurize Version

structurize-1.20.1-1.0.742-RELEASE.jar

### Related Mods and their Versions

Forge version:47.3.5
blockui-1.20.1-1.0.156-RELEASE.jar
domum_ornamentum-1.20.1-1.0.188-BETA-universal.jar

### Current Behavior

Crash Video:https://github.com/user-attachments/assets/2f8ddabb-4acd-4e27-9f55-62a4330967e4
Crash report:[crash-2024-07-28_14.30.33-server.txt](https://github.com/user-attachments/files/16403097/crash-2024-07-28_14.30.33-server.txt)
All crash reports used to come as server.txt. I saw this while looking through the files, it might still be useful, it's a crash report caused by MineColonies:[crash-2024-07-27_22.54.20-fml.txt](https://github.com/user-attachments/files/16403098/crash-2024-07-27_22.54.20-fml.txt)

I had used this save with a different account before, and there was no issue. Now I have lost access to my old account, or I should say I can't access it anymore. I logged in from a new account and didn't experience any issues while being away from the colony, but as soon as I got close to the colony, and as soon as the message 'you have entered the colony' appeared, the game freezes and doesn't close unless I close it manually. When I went to my previous save and tried changing the colony manager, the game crashed. I changed the manager in the config files, but the server said 'invalid player' and didn't let me into the game. This is my problem."

Let me know if you need anything else!

### Expected Behavior

I would be very grateful if you could help me. I have played on that save for nearly 100 hours, and it’s probably even more.

### Reproduction Steps

I entered the existing colony with another account, and the modpack used is the Industrial Village modpack from CurseForge.

### Logs

https://gist.github.com/LemCsZ/d51b4a4371305d678b6f7d9172c5006e

**Comment by Raycoms** [comment]
You're missing dependencies:

	Failure message: Mod minecolonies requires structurize 1.20.1-1.0.740-BETA or above
		Currently, structurize is 1.20.1-1.0.738-BETA

**Comment by LemCsZ** [comment]
> You're missing dependencies:
> 
> ```
> Failure message: Mod minecolonies requires structurize 1.20.1-1.0.740-BETA or above
> 	Currently, structurize is 1.20.1-1.0.738-BETA
> ```
I was sure that all the mods were updated to the latest versions, but I just sent the old crash report. I'll try again immediately.

**Comment by LemCsZ** [comment]
[crash-2024-07-28_15.08.13-server.txt](https://github.com/user-attachments/files/16403177/crash-2024-07-28_15.08.13-server.txt)
The same issue continues; nothing has changed, and it was already on the latest version. Anyway, I’ve left the crash report here.

**Comment by Raycoms** [comment]
MineColonies_Tweaks-1.20.1-2.26.jar               |Tweaks addon for MineColonies |minecolonies_tweaks           |2.26                |DONE      |Manifest: NOSIGNATURE
		MineColonies_Compatibility-1.20.1-2.27.jar        |Compatibility addon for MineCo|minecolonies_compatibility    |2.27                |DONE      |Manifest: NOSIGNATURE
		
		Remove

**Comment by LemCsZ** [comment]
> ```
> 	MineColonies_Tweaks-1.20.1-2.26.jar               |Tweaks addon for MineColonies |minecolonies_tweaks           |2.26                |DONE      |Manifest: NOSIGNATURE
> 	MineColonies_Compatibility-1.20.1-2.27.jar        |Compatibility addon for MineCo|minecolonies_compatibility    |2.27                |DONE      |Manifest: NOSIGNATURE
> 	
> 	Remove
> ```

he problem wasn't resolved, but there is some progress. This time, the game closed itself without me doing anything. Oh well.
[crash-2024-07-28_15.24.54-server.txt](https://github.com/user-attachments/files/16403258/crash-2024-07-28_15.24.54-server.txt)
https://gist.github.com/LemCsZ/03d1c6e181f4d66b981d90534aca85dd

Actually, as soon as I opened the game, the 'you have entered the colony' message appeared a few seconds later. Just as I was starting to feel like something had changed, the game crashed.

**Comment by Thodor12** [comment]
Looks like you have a crash in the request system, that Minecolonies Tweaks mod modifies something in the request system code. Now that you have removed it, it's probable that is now missing and cannot be parsed again, which is causing the crash you are seeing.

If you are able, try and run `/mc colony requestsystem-reset-all`, if you can't do that in time, you have to find a way to teleport yourself out of the colony and then run that command.

Alternatively, it might be that faulty entry is now gone entirely already, and you may be able to just reboot the game without any problems.

**Comment by LemCsZ** [comment]
> Looks like you have a crash in the request system, that Minecolonies Tweaks mod modifies something in the request system code. Now that you have removed it, it's probable that is now missing and cannot be parsed again, which is causing the crash you are seeing.
> 
> If you are able, try and run `/mc colony requestsystem-reset-all`, if you can't do that in time, you have to find a way to teleport yourself out of the colony and then run that command.
> 
> Alternatively, it might be that faulty entry is now gone entirely already, and you may be able to just reboot the game without any problems.

I'm going to try it now, but I don't have enough time to do it. I'll try it and get back to you as soon as possible.

**Comment by LemCsZ** [comment]
> /mc colony requestsystem-reset-all

Wow, it’s been resolved. Thanks a lot. Actually, as soon as I entered the game, I teleported myself somewhere else within the first 3-4 seconds, but I normally didn’t have that much time. Anyway, after that, I entered the code you mentioned. Do you know exactly what the code restarted that made it work? I’m curious. Thanks again, by the way.

**Comment by LemCsZ** [comment]
> Looks like you have a crash in the request system, that Minecolonies Tweaks mod modifies something in the request system code. Now that you have removed it, it's probable that is now missing and cannot be parsed again, which is causing the crash you are seeing.
> 
> If you are able, try and run `/mc colony requestsystem-reset-all`, if you can't do that in time, you have to find a way to teleport yourself out of the colony and then run that command.
> 
> Alternatively, it might be that faulty entry is now gone entirely already, and you may be able to just reboot the game without any problems.

Wow, it’s been resolved. Thanks a lot. Actually, as soon as I entered the game, I teleported myself somewhere else within the first 3-4 seconds, but I normally didn’t have that much time. Anyway, after that, I entered the code you mentioned. Do you know exactly what the code restarted that made it work? I’m curious. Thanks again, by the way.

**Comment by Thodor12** [comment]
The tweaks addon injects a custom request type class into the request system, you removed tweaks so that caused that code to become unavailable.
It then tried to parse an existing request from NBT data but couldn't do it because that code from Tweaks was now gone, causing the output to be null, that caused the crash.

The reset command wipes all current request data, which will also remove the currently unloadable data.

**Comment by LemCsZ** [comment]
> MineColonies_Compatibility

I just re-downloaded MineColonies_Tweaks and MineColonies_Compatibility that I had deleted earlier. Before deleting them, I had changed the colony manager in my saved game. Now, when I loaded the game with the two mods I deleted, everything works fine. Sometimes Minecraft can be extremely frustrating.

**Comment by Thodor12** [comment]
You should not install them. They break our code in several ways, causing all kinds of weird bugs.
They're not even compatible with our newer versions after the food update because we completely revised our code.

**Comment by LemCsZ** [comment]
> You should not install them. They break our code in several ways, causing all kinds of weird bugs. They're not even compatible with our newer versions after the food update because we completely revised our code.

Hmm, there were a lot of mistakes with the builder starting and continuing the work, and by saying that, I think I've found the scapegoat.
