### ISSUE TITLE
[BUG] Farmer does not farm anymore

### ISSUE THREAD

**Issue by killkillsito** [ldtteam/minecolonies#10083]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.20.1-1.1.622-BETA

### Structurize Version

1.20.1-1.0.742-RELEASE

### Related Mods and their Versions

1. Forge Version: 1.20.1 forge-47.2.32
2. BlockUI: 1.20.1-1.0.156-RELEASE
3. Domum Ornamentum: 1.20.1-1.0.189-BETA-universal

### Current Behavior

Farmer does not farm, i tried to updating to the last version of the mod and dependencies and still giving the same AI error. I tried to hire a new farmer and the same bug appears. Resetting farmer does not solve the bug
![aibug](https://github.com/user-attachments/assets/8ce08bb0-b7d6-45c9-b2ac-431262ffa6bb)

### Expected Behavior

Farmer should be farming

### Reproduction Steps

1. Create a Farm
2. Hire a Farmer
3. Upgrade Farm
4. Give all the requested items and crops

### Logs

https://gist.github.com/killkillsito/50055955aa0b878a72cfac04a723ac55

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Report to: Endlessbiomes
