### ISSUE TITLE
Persistent Builder NPC Issues in MineColonies: Builder NPC's AI Seems to Be Broken

### ISSUE THREAD

**Issue by LemCsZ** [ldtteam/minecolonies#10082]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

minecolonies-1.20.1-1.1.601-BETA

### Structurize Version

structurize-1.20.1-1.0.742-RELEASE.jar

### Related Mods and their Versions

blockui-1.20.1-1.0.156-RELEASE.jar
domum_ornamentum-1.20.1-1.0.188-BETA-universal.jar

There are also Compatibility addon for MineColonies and Tweaks addon for MineColonies mods, but I played for a long time after removing them and nothing changed

### Current Behavior

![Ekran görüntüsü 2024-07-30 170055](https://github.com/user-attachments/assets/ec339e9d-8cf8-4c8f-997c-721a5e751470)
Here’s the situation: My builder was broken. When I first started with MineColonies, there was no issue. Over time, whenever I made specific requests for the builder, it would say it started in the chat, but it would just stand in front of the builder's hut. I tried using commands to reload and reloaded the colony, but nothing changed. I assigned a different job to the NPC, but it didn’t work either, so I killed it and assigned a new NPC. The new one worked perfectly at first, but over time, it started malfunctioning as if it had a virus. It only starts working if I repeatedly fire and rehire it, and even then, it eventually goes back to standing in front of the builder's hut and does nothing. I received a message like this, so I finally decided to ask for help.

### Expected Behavior

Reliable, insured construction workers.

### Reproduction Steps

I just continued playing.

### Logs

https://gist.github.com/LemCsZ/b376d62b2883385d5921c4851b39c59e

### Anything else?

I’ll say it again: I removed the Compatibility addon for MineColonies and the Tweaks addon for MineColonies mods and played for about 5-6 hours. I also used the /mc colony requestsystem-reset-all command after removing the mods, but the builder NPC’s behavior didn’t change.

**Comment by Raycoms** [comment]
Yes, most likely the tweak mods messed with colony internal data which prevents the builder to function properly.
Cancel the current build request, fire and rehire the builder please and see if it works then.

**Comment by LemCsZ** [comment]
> Yes, most likely the tweak mods messed with colony internal data which prevents the builder to function properly. Cancel the current build request, fire and rehire the builder please and see if it works then.

So every time I start a job, I’m doing as you said, but it seems you’re right. Even when the builder starts, they don’t continue, and I end up removing them again. It’s a strange cycle.But even though I deleted the mods, it seems I can’t fix whatever they messed up. It’s really frustrating.

**Comment by Raycoms** [comment]
Have you tried: A) Fire builder and set to manual B) Clean up workorder queue in the townhall and c) rehire builder
