### ISSUE TITLE
[BUG] If citizens can't find a path, they will permanently stop generating new path points and they don't react to taking damage.

### ISSUE THREAD

**Issue by fulmoonless** [ldtteam/minecolonies#10092]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.20.1-1.1.623

### Structurize Version

1.20.1-1.0.742

### Related Mods and their Versions

Forge - 47.3.0

### Current Behavior

If a citizen can't reach their target location, they will walk in a seemingly random direction once, then get stuck forever (I AFK'd for 6 hours) not fleeing, guards not fighting back, and doing nothing.

### Expected Behavior

Don't get stuck.

### Reproduction Steps

1. Trap them
2. Wait for them to walk a bit
3. They get stuck forever
https://youtu.be/2ySZoCuc9p8

### Logs

https://gist.github.com/fulmoonless/69a817b363cf48880d8ae377afd9e723

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Can I have the modlist please

**Comment by fulmoonless** [comment]
blockui-1.20.1-1.0.156-RELEASE
domum_ornamentum-1.20.1-1.0.186-RELEASE-universal
minecolonies-1.20.1-1.1.624-BETA
multipiston-1.20-1.2.43-RELEASE
structurize-1.20.1-1.0.742-RELEASE
towntalk-1.20.1-1.1.0
(Basically, it's what you need to download when getting the latest version of Minecolonies from Forge.)
Additionally, I reproduced the issue from https://github.com/ldtteam/minecolonies/issues/9999 using these mods as well (I uploaded a video there), so I don't think it's just an issue with the Industrial Village modpack.
My guards also drowned in the official modpack.

**Comment by fulmoonless** [comment]
This bug started from the minecolonies-1.20.1-1.1.519-BETA version. It seems that version made citizens wander around when they couldn't find a path.
Additionally, it seems they still react to taking damage (guards tried to attack me), but once they enter the 'wander around' mode, the pathing system doesn't generate paths for fleeing or attacking.

**Comment by fulmoonless** [comment]
https://youtu.be/H_NvOKxMHG4

**Comment by Thodor12** [comment]
That video is unavailable

**Comment by fulmoonless** [comment]
https://youtu.be/6aZKxYUs8Js
Guards and other citizens without tasks triggered teleportation after being stuck for about 30 minutes (the guard was about 170 blocks away from his guard tower), while citizens who had work tasks (about 135 blocks away from their workplace) remained permanently stuck. Additionally, once they enter the 'wander around' mode, they don't flee even if they aren't stuck yet.

**Comment by fulmoonless** [comment]
So it should be divided into two issues:

1. The teleportation trigger time is too long when they are stuck at a greater distance.(But it's actually not that long, especially for builders.)
2. Citizens in 'wander around' mode do not engage in pursuit or fleeing.

**Comment by someaddons** [comment]
this should be fixed in the newer versions, if not plesae make open a new issue
