### ISSUE TITLE
Miner cannot handle vanilla ore variants from Underground Biomes Constructs

### ISSUE THREAD

**Issue by Rory-Lambert** [ldtteam/minecolonies#1009]
### Minecolonies version

version 1.10.2-0.6.112

### Expected behavior

- Mine worker mines the UBC skinned ore block

### Actual behaviour

-Mine worker stands staring at the block until a player removes it for them. He will not move on to any other blocks. If recalled, he will not leave the mine chest until the ore block is removed.

### Steps to reproduce the problem

1. Have minecolonies and underground biomes constructs (0.9beta16) installed
2. Set up a miner and wait until he encounters a 'vanilla' ore block with UBC stone
3. Observe as he lollygags about!
4. Profit

**Comment by Raycoms** [comment]
Can you show us the console log?

2017-05-16 20:23 GMT-03:00 Lookbehindyoo <notifications@github.com>:

**Comment by Raycoms** [comment]
It's usually because the UBC mod did not implement the "pickaxe" to be an
efficient tool. Or at least not correctly.

2017-05-16 20:25 GMT-03:00 Ray Neiheiser <ray.neiheiser@gmail.com>:

**Comment by Rory-Lambert** [comment]
Here are the most recent logs. 

[2017-05-16-1.txt](https://github.com/Minecolonies/minecolonies/files/1007465/2017-05-16-1.txt)
[2017-05-15-2.txt](https://github.com/Minecolonies/minecolonies/files/1007464/2017-05-15-2.txt)

I see that I am a few version behind on UBC, so let me update it and get back to you. Perhaps this is already fixed on their end.

**Comment by Raycoms** [comment]
Couldn't find anything minecolonies related in there, but I bet the problem
is that the block doesn't implement the right methods.

2017-05-17 8:15 GMT-03:00 Lookbehindyoo <notifications@github.com>:

**Comment by Rory-Lambert** [comment]
I updated UBC and added UBCoreregistrar. The problem persisted. I had the idea to try with a vanilla pickaxe instead of tinkers tools, and this appears to be a suitable workaround. I guess you can consider this closed!

**Comment by Raycoms** [comment]
If vanilla works but itnkers not the problem must be on their side =)

2017-05-17 20:16 GMT-03:00 Lookbehindyoo <notifications@github.com>:
