### ISSUE TITLE
[BUG] chunks of colony dont load, lets players time out and crash the server after creating a colony

### ISSUE THREAD

**Issue by moritxius-matsuda** [ldtteam/minecolonies#10108]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [ ] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

6.10-BETA

### Structurize Version

1.0.742-RELEASE

### Related Mods and their Versions

FORGE: 47.2.20
MODPACK: All The Mods 9

### Current Behavior

Another Player created a colony, placed a city hall, destroyed the city hall. I wanted to teleport myself to him per waystone to his colony. As soon as i got there i started levitating with the message. You cannot enter this colony. After teleporting myself back to my home, we both timed out and the server crashed. Just trying to load the chunks of the colony outside of the colony brings the server to time out and crash. Deleting the colony, updating and removing the mod wont solve the issue.

### Expected Behavior

To delete the colony and let the chunks load without getting timed out nor crashing the server.

### Reproduction Steps

1. Create a colony
2. Teleport to that colony by waystone
3. Teleport back to your home
4. Try to load the chunks of the colony outside of the colony.

### Logs

Server Log: https://pastebin.com/FWGKvgti

### Anything else?

PROCESSOR: i7-6700
RAM: 64GB DDR4
OS: Debian 12

**Comment by Raycoms** [comment]
can we have the crash log?

**Comment by moritxius-matsuda** [comment]
unfortunately i dont have the crash log of it anymore it somehow got deleted from the original crash. but here is the crashlog 2 hours after that: https://pastebin.com/NavtE0vw

side note: minecolonies must have done something to the world. In singleplayer it loads, but in multiplayer with a fresh server installation it doesn't load at all.
![image](https://github.com/user-attachments/assets/b397a9b8-3ee7-43dc-997d-263d98e89e84)

**Comment by Raycoms** [comment]
That seems just like the classic worldgen crashes

**Comment by Raycoms** [comment]
And especially as you stated that removing the mod doesn't solve this either, it doesn't seem to be a minecolonies issue. Just in general some chunks that are not generating. What is your server settings timeout value?

**Comment by someaddons** [comment]
colonies are not stored within chunks, nor laoded alongside them, you got some other mod affecting the chunks data most likely

**Comment by moritxius-matsuda** [comment]
im now trying to load. i had a few server-side performance mods installed, including one that had rewritten the lighting engine. so i'll give it a try if it loads now. i will edit the post if it works.

```
max-tick-time=180000
player-idle-timeout=0
```

**Comment by moritxius-matsuda** [comment]
it works now. starlight seemed to be the problem. thanks a lot
