### ISSUE TITLE
[BUG] <Citizens walking on underwater blocks leading to drowning.>

### ISSUE THREAD

**Issue by fulmoonless** [ldtteam/minecolonies#10114]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.20.1-1.1.629

### Structurize Version

1.20.1-1.0.742

### Related Mods and their Versions

Minecolonies Offical WinterColonies-1.11(Some tests were done without installing this modpack.)
Forge - 47.2.0
blockui-1.20.1-1.0.156-RELEASE
domum_ornamentum-1.20.1-1.0.186-RELEASE-universal
multipiston-1.20-1.2.43-RELEASE
structurize-1.20.1-1.0.742-RELEASE
towntalk-1.20.1-1.1.0

### Current Behavior

Citizens walking on underwater blocks leading to drowning.
https://youtu.be/n9WvWgjgT98

### Expected Behavior

Stop drowning.

### Reproduction Steps

https://www.youtube.com/watch?v=cBawO2dVo7Q

### Logs

No crash

### Anything else?

I think there are two main causes for this issue:

1. Citizens prefer walking on blocks over swimming, so they choose to walk on blocks at the bottom of the water.
2. In what seems to be a recent update, the pathfinding system is triggered once when a citizen is submerged in water.

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Estyria** [comment]
We’ve sent this lovely person here from the discord as we’ve now had at least half a dozen people describe colonists walking on the bottom of a body of water and water deaths appear to be at an all time high once again. Lots of complaints of drowning. More than usual colonist derpiness.

**Comment by fulmoonless** [comment]
After testing a lot of versions, I found that the issue likely started with the update in minecolonies-1.20.1-1.1.566-BETA.jar. There was a change related to pathfinding
Underwater escape pathing Fix float bumping Fix shingle cost not applying Improve general pathfinding

**Comment by fulmoonless** [comment]
I found that the issue likely started with the update in minecolonies-1.20.1-1.1.566-BETA.jar. There was a change related to pathfinding
Pathfinding fixes (#9930)
Underwater escape pathing Fix float bumping Fix shingle cost not applying Improve general pathfinding

(I tested it, and from that version onwards, citizens started walking underwater.)
