### ISSUE TITLE
Builder fails to identify Item Frames

### ISSUE THREAD

**Issue by TheQuadShot** [ldtteam/minecolonies#1011]
When upgrading Fishing Hut to lvl 4 the builder requests 4 item frames, but will not "see" them in my inventory via the UI, or if I put them directly into the inventory.

Minecraft 1.10.2
minecolonies-universal-1.10.1-0.7.848
Forge-12.18.3.228

ModList
https://pastebin.com/QpQ9ff3x

latest log file
https://pastebin.com/X6gQg3g2

**Comment by Raycoms** [comment]
You mean the builder does not accept them?
Or you mean you put them in his inventory and they vanish right away?

2017-05-16 21:22 GMT-03:00 James <notifications@github.com>:

**Comment by TheQuadShot** [comment]
He does not accept them and continues to ask for them, I tried via the UI, putting them in the builders "block" inventory and directly into his inventory.

**Comment by Raycoms** [comment]
Are you sure you're giving him 100% vanilla item frames and not the modded
ones like tinkers ones?

2017-05-16 21:48 GMT-03:00 James <notifications@github.com>:

**Comment by TheQuadShot** [comment]
Yes, (sticks around a cow hide) crafted or creative ones

**Comment by TheQuadShot** [comment]
oops, forgot to mention that this only happens on the fishing hut, I've got a lvl 4 warehouse and other build requests that asked for them and they worked just fine.

**Comment by Raycoms** [comment]
Okay that's very strange. Thanks we will test it.

2017-05-16 21:53 GMT-03:00 James <notifications@github.com>:

**Comment by TheQuadShot** [comment]
His AI appears to be "stuck/hung" now. I cancel the upgrade and create build order to repair a bldg and he does nothing until I bounce the game/server, when game relaunches he picks up the build order and starts his repair.

**Comment by Raycoms** [comment]
Okay it seems like something in general with the fisherman 4 fails him,
I'll have to test that tomorrow.

2017-05-16 22:39 GMT-03:00 James <notifications@github.com>:

**Comment by cltnschlosser** [comment]
@Raycoms Update on this?

**Comment by Raycoms** [comment]
Didn't get to test this yet.

2017-05-22 0:39 GMT-03:00 Colton Schlosser <notifications@github.com>:

**Comment by WORMSS** [comment]
I am experiencing the same thing (Fisher hut upgrade to level 4). This is the first building that is requesting item frames.

The strange thing is, the builder is holding a stair case. Usually the builder holds what they are requesting.. but this time it's stairs.. Looks like oak.

I tried given the builder stairs of all types + item frames (crafted and cheated in). 
Also tried putting them into block inventory and builder inventory as @TheQuadShot had.
Also to note on this, the ^ arrow that transfers items from your inventory into the builders hut inventory doesn't accept the item frame as a valid transfer.

minecolonies: 1.10.2-0.8.1772
minecraft: 1.10.2
forge: 12.18.3.2297

JEI: 1.10.2-3.14.7.419
FastLeafDecay: 11
JourneyMap: 1.10.2-5.4.6
TreeGrowingSimulator: 2016-0.0.4

**Comment by rsmalec** [comment]
Same issue.

**Comment by buleoer** [comment]
Same issue.
My builder is building the town hall lvl 3. He requests an item frame but he is holding a stair case. When I give him an item frame, it disappears immediately from his inventory.
minecolonies 1.10.2-0.8.3056

**Comment by Raycoms** [comment]
He places them directly in the townhall.

2017-09-04 19:22 GMT+01:00 Eric Buléon <notifications@github.com>:

**Comment by Zucichan** [comment]
I had the same issue with Items frames on town halls and warehouse upgrades. At first you think you are loosing the Frames, or they are deleting, they are not.

 They are magically placing them. 

I tested it by committing to tossing the builder 3 stacks of frames. I thought for sure they couldn't need that many, and I was right.  She ran off and finished the building, and I counted the frames after the fact. All accounted for. So if this happens, craft the total amount you need :)

**Comment by Raycoms** [comment]
The newest versions still don't tell you the exact amount? In which
versions does this happen?

2017-09-07 3:16 GMT+01:00 Zucichan <notifications@github.com>:
