### ISSUE TITLE
[BUG] The latest release's version not matching previous version's structure

### ISSUE THREAD

**Issue by zyxkad** [ldtteam/minecolonies#10138]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.1.636

### Structurize Version

1.1.636-1.20.1-BETA

### Current Behavior

Previously the version structure is `<minecraft_version>-<minecolonies_version>`,
but now the versions swapped, it become `<minecolonies_version>-<minecraft_version>`

Is this on purpose? Since it breaks our mod dependencies.

```toml
[[dependencies.${mod_id}]]
modId = "minecolonies"
mandatory = false
versionRange = "[1.20.1-1.1.472-BETA,)"
ordering = "NONE"
side = "BOTH"
```

![image](https://github.com/user-attachments/assets/286400a8-8a8e-439d-ae9f-ac6572f36bc4)

### Expected Behavior

Mod (both older version and the latest version) should load correctly without error.

### Reproduction Steps

1. Define dependencies with older version
2. Try load with the latest version
3. Load failed

### Logs

N/A

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
We're aware, this is being fixed with https://github.com/ldtteam/OperaPublicaCreator/pull/13

**Comment by Yzen90** [comment]
The file `minecolonies-1.1.638-1.20.1-beta.jar` at CurseForge still has this issue. I edited the mods.toml in the jar and that seemed to work.

**Comment by zyxkad** [comment]
Maybe minecolonies can temperatory remove the release until fixed.

**Comment by Thodor12** [comment]
We're currently checking what we want to do to resolve this, we recommend not upgrading past 1.1.629 for now
