### ISSUE TITLE
[BUG] Raycoms Minecolonies Official 1.20.1 Exception Access violation

### ISSUE THREAD

**Issue by Geminiasp** [ldtteam/minecolonies#10131]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.20.1-1.1.609-BETA

### Structurize Version

1.20.1-1.0.742-RELEASE

### Current Behavior

I was trying to start up the Minecolonies Official ModPack by Raycoms 1.20.1 
I want to play on singleplayer.
I keep receiving the EXCEPTION_ACCESS_VIOLATION preventing me from getting into the game with this modpack.
I double checked and all my drivers are completely updated. Java is completely updated. Curseforge is completely updated.

### Expected Behavior

I expect be able to use this modpack with no problems since I downloaded it from curseforge and it is the Official Modpack. And everything is updated on my computer.

### Reproduction Steps

1. Go to Curseforge
2. Download Official Minecolonies modpack from Raycoms (1.20.1 forge version)
3. Click play

### Logs

https://gist.github.com/Geminiasp/c50d144111ea0cb106836ba4474379ce

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Please join our discord for pack support. This is just for mod support.
discord.minecolonies.com

For now, delete pack and reinstall might fix it.
