### ISSUE TITLE
[BUG] <Numbers blend with the background and can barely be visible in multiple instances>

### ISSUE THREAD

**Issue by Shazway** [ldtteam/minecolonies#10144]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [X] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.1.598 BETA

### Structurize Version

1.0.737 BETA

### Related Mods and their Versions

Craft to exile 2 modpack

### Current Behavior

Text indicating number of items, blend with background and is barely visible
![image](https://github.com/user-attachments/assets/088225ab-cb4f-4c15-bf8b-0f155ff4d0b6)
![image](https://github.com/user-attachments/assets/e6b4400b-0e51-4a36-813b-bc0269a49e2d)
![image](https://github.com/user-attachments/assets/7be8e0bd-afeb-4724-be93-c3588c1a938f)

### Expected Behavior

Visible numbers

### Reproduction Steps

Talk to a visitor
Open crafting recipes of any crafter
Open researches for university

### Logs

.

**Comment by Moobien** [comment]
I thought Ray already fixed that for the visitor recruiting buttons.

**Comment by Raycoms** [comment]
No, we can't alter this stack color atm , I added to the visitor a more verbose text with the info

-------- Original Message --------

**Comment by Shazway** [comment]
How about modifying the bg color to unmatch from the white number would that be a thing
