### ISSUE TITLE
[BUG] Builder's Hut UI opens to Quick Guide interface every time

### ISSUE THREAD

**Issue by kezmodius** [ldtteam/minecolonies#10159]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

minecolonies-1.20.1-1.1.644-BETA

### Structurize Version

structurize-1.20.1-1.0.742-BETA

### Related Mods and their Versions

Forge 47.2.23
Block UI 1.20.1-1.0.156-Release
Modpack: Wolf Craft - A modpack by Certi https://www.curseforge.com/minecraft/modpacks/certi-wolf-craft

### Current Behavior

After today's server update to 644 (previous version was 622) every time I open a Builder Hut UI it goes first to the Quick Guide interface. Shindria asked me to report here as there have been a few mentions of this in the discord lately.

### Expected Behavior

To only open the Quick Guide the first time you open the Builder's Hut UI

### Reproduction Steps

Be on version 1.1.644 (or maybe earlier, post version 1.1.622)
Open Builder Hut UI
See Quick Guide interface
Click Understood
Close UI
Open UI
See Quick Guide again
It does it with every Builder Hut 

### Logs

https://gist.github.com/kezmodius/9e12705840617a3f6283a5fecc6e2334

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
This is an old vanilla bug where vanilla somehow has broken achievements, relogging should fix this.

**Comment by kezmodius** [comment]
Our server updated to 647 and it stopped happening thereafter, so I can't say if it was the version or what you said. I'll close the issue.
