### ISSUE TITLE
[BUG] My AI has run into an issue

### ISSUE THREAD

**Issue by Cklarkus** [ldtteam/minecolonies#10179]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [x] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.20.1

### MineColonies Version

minecolonies-1.20.1-1.1.647-BETA

### Structurize Version

structurize-1.20.1-1.0.742-RELEASE

### Related Mods and their Versions

Forge 47.3.6
Blockui-1.20.1-1.0.156-RELEASE
domum_ornamentum-1.20.1-1.0.186-RELEASE-universal
multipiston-1.20-1.2.43-RELEASE

### Reproduction Steps

my builder is broken, it says “My AI has run into an issue” I changed people, builders. I wrote the command mc colony requestsystem-reset, but none of this helped. It puts 2-3 blocks, then freezes, after the night again 2-3 blocks and freezes.

### Logs

https://mclo.gs/aHTAvXa

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by someaddons** [comment]
has been fixed, you need to update to the latest version or remove the sounds mod

**Comment by Cklarkus** [comment]
> has been fixed, you need to update to the latest version or remove the sounds mod

I now have the 647 beta, but nothing has changed.

**Comment by Cklarkus** [comment]
> has been fixed, you need to update to the latest version or remove the sounds mod

New log uploaded

Sound mod, is that town talk?

**Comment by Thodor12** [comment]
There's a separate mod called "Sounds" which causes this error, nothing we can do about it.

**Comment by Cklarkus** [comment]
> has been fixed, you need to update to the latest version or remove the sounds mod



> There's a separate mod called "Sounds" which causes this error, nothing we can do about it.

Ok, I'll try deleting it now, very strange, I've had this mod for a long time, but the error appeared now

**Comment by Cklarkus** [comment]
> There's a separate mod called "Sounds" which causes this error, nothing we can do about it.

Thanks, everything is working now, will wait for the patch for the sounds mod

**Comment by someaddons** [comment]
ye its a certain sound being played that crashes, interesting though, seems the check I added did not catch the issue
