### ISSUE TITLE
[BUG] texture loading crash Non [a-z0-9/._-] character in path

### ISSUE THREAD

**Issue by JurkoDev** [ldtteam/minecolonies#10181]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.20.1

### MineColonies Version

1.20.1-1.1.644

### Structurize Version

1.20.1-1.0.752

### Related Mods and their Versions

its also listing Entity Model Features (2.2) as it has a mixin there

### Reproduction Steps

i start the game
i join the server and it crashes right when it starts rendering i am near a minecolonies village

### Logs

https://gist.github.com/JurkoDev/1c2f4b6b06407df9193607abe6aeed02

### Anything else?

i had issues with optimisation mods just wrecking it i think theres probably something still based on the log spam

idk what this loading issue is also the sound loading issues in the console log

also am not on latest minecolonies as i couldnt be as the server is just rejecting me (also cant test sp as it will just eat all my ram (32gb) and cpu and then crash while trying to load a sp world huh)

**Comment by someaddons** [comment]
did you use some custom texture pack called minecolonies:builder by chance?

**Comment by JurkoDev** [comment]
I don't use any custom texture packs I only notable one is a kubejs autogen Datapack that disables some origins stuff
