### ISSUE TITLE
[BUG] Server crashes when a MineColonies "citizen" entity takes damage

### ISSUE THREAD

**Issue by Amidz99** [ldtteam/minecolonies#10195]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19.2

### MineColonies Version

1.19.2-1.1.433-BETA

### Structurize Version

1.19.2-1.0.682-RELEASE

### Related Mods and their Versions

1. Apotheosis (apotheosis), Version: 6.4.1
2. Silent Compat (silentcompat), Version: 1.3.4
3. MineColonies (minecolonies), Version: 1.19.2-1.1.433-BETA

### Reproduction Steps

The server is crashing when a Mine Colonies "Citizen" entity takes damage. Something is trying to treat it as a player, which is causing a crash.

### Logs

https://pste.ch/wobokolisi.pl

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Report to Silent Compat
