### ISSUE TITLE
IA fail to recognised additional chest

### ISSUE THREAD

**Issue by xavierh** [ldtteam/minecolonies#1019]
### Minecolonies version

Version/1.11

### Expected behavior

- IA should use the chest part of the building

### Actual behaviour

- they don't know they are there

### Steps to reproduce the problem

1. Build a warehouse
2. Remove the main chest
3. put the chest back at the exact position and let the builder do his job
4. The delivery man will not use the chests

Probably because the chest are added to the building when the builder put them down.

It can be fix by removing the additinnal chests and ask the builder to repair.

I suppose that the problem will show with any buildings with additional chest where the IA use them

**Comment by Raycoms** [comment]
we could fix that by looking in the "isSchematicEqualWorldBlock" if its a
chest and then check if it has been added already.

2017-05-18 16:29 GMT-03:00 xavierh <notifications@github.com>:

**Comment by marvin-bitterlich** [comment]
We are currently not scanning for extra chests and that is somewhat intentional (cpu cycles and such)

**Comment by Raycoms** [comment]
Yeah but we don't need to scan if we simply make the scan during the
execution of a repair.

2017-05-18 17:43 GMT-03:00 Marvin Hofmann <notifications@github.com>:

**Comment by xavierh** [comment]
We will have to pay attention to this when doing issue #788
