### ISSUE TITLE
[BUG] Warehouse cannot handle minimum stock.

### ISSUE THREAD

**Issue by fulmoonless** [ldtteam/minecolonies#10207]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20

### MineColonies Version

1.20.1-1.1.658

### Structurize Version

1.20.1-1.0.742

### Related Mods and their Versions

WinterColonies-1.11

### Current Behavior

Warehouse cannot handle minimum stock (maybe it's related to having two warehouses).
![image](https://github.com/user-attachments/assets/742e5e19-0442-4dd7-91f3-c4f12388b6c4)

### Expected Behavior

Make warehouse handle minimum stock.

### Reproduction Steps

Make a minimum stock.

### Logs

No crash

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
wdym?

**Comment by Raycoms** [comment]
Ah, warehouse doesn't answer it?

**Comment by Estyria** [comment]
To clarify, you've set minimum stock at those various huts, and yet the delivery system is marking you as the resolver even though the materials/items are available in the warehouse, correct? That's my understanding from our discord discussion.

Also, reset request system didn't work.

**Comment by Raycoms** [comment]
hotfix pushed

**Comment by fulmoonless** [comment]
Ah, sorry about that. I was almost falling asleep at that time, so it ended up being a bit unclear.

**Comment by Estyria** [comment]
I got your back, no worries xD
