### ISSUE TITLE
[BUG] Statemachine for state INVENTORY_FULL 

### ISSUE THREAD

**Issue by Eiriksb** [ldtteam/minecolonies#10200]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.21

### MineColonies Version

1.21.1-1.1.677

### Structurize Version

1.21.1-1.0.751

### Related Mods and their Versions

NeoForge 1.21.1-21.1.35 BlockUI 1.21.1-1.0.188 snapshot domum_ornamentum-1.0.203-1.21.1-snapshot

### Current Behavior

Spaces between the first item slot in a inventory and other items, either in a citizen or in a chest of a building they work at, will make the AI crash and pause, try again pause try again pause etc. In a loop. 

### Expected Behavior

That the citizen regardless of spaces in their inventory will work and not crash.

### Reproduction Steps

1. Have a builders hut
2. Make the builder build something and give him the resources he requires to build it.
3. Watch him build it for a bit until he has to get some new block from the builders hut
4. AI Crash message

### Logs

https://gist.github.com/Eiriksb/f606110c6144d0c55753805a2b6604ad

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Please try the newest posted on discord. And 1.21 bugs can also be directed reported there.
