### ISSUE TITLE
Trying to figure out which mod is conflicting with Mine Colonies

### ISSUE THREAD

**Issue by DreezyMoto** [ldtteam/minecolonies#10204]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20

### MineColonies Version

1.1.647-BETA

### Structurize Version

1.0.755-BETA

### Current Behavior

Main issue im having is the builder and sometimes other workers freeze up and say that their AI is bugged. Paste-binned the logs that spit out and am hoping someone who knows how to read them can assist in pin pointing which mod is causing the error.

### Expected Behavior

For the MineColonies AI to work

### Reproduction Steps

-Have a giant modlist
-Be too lazy to go through and disable one mod at a time
-Attempt to make a Colony
-Smash keyboard on head when giant modlists dont always work well with eachother

### Logs

https://pastebin.com/YJwF2Cj6

### Anything else?

Simply just needed someone who knows how to read through java errors to help me pin point which mod is causing this error.

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
You need to include the whole log, not just a snippet. (then we can see the actual modlist also)
And discord is a better place to go for support

**Comment by DreezyMoto** [comment]
sorry, will post the whole log. I may have, out of pure luck, just discovered the incompatibility. Has anyone else had issues with MineColonies and the mod "sounds"?

**Comment by Talyda** [comment]
Yup. Was waiting for modlist to check it =P
Search github for it - or discord. Really, please use discord for support!

**Comment by DreezyMoto** [comment]
Sounds good I will. And my  entire log is too big to put into pastebin, hit the 512kb limit; Ill put the mod list pastebin below. But looks like it was the Sounds mod, which is a shame. I like the sounds that mod adds. Should I make a compatibility request for it?

https://pastebin.com/w98HqxER

**Comment by Talyda** [comment]
Nope - search the previous issues =)

**Comment by DreezyMoto** [comment]
Sounds good, well thank you for the help and info!
