### ISSUE TITLE
Configliststudyitems issue.

### ISSUE THREAD

**Issue by fulmoonless** [ldtteam/minecolonies#10210]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [x] Single Player
- [ ] Multi Player

### Minecraft Version

1.20

### MineColonies Version

1.20.1-1.1.660

### Structurize Version

1.20.1-1.0.742

### Related Mods and their Versions

Minecolonies Offical WinterColonies-1.11

### Current Behavior

Library Students will only request the item at the top of configliststudyitems, and even if other items are placed to enable their study, they will still request the item at the top of configliststudyitems.
https://youtu.be/L8e8EjCLMd0

(To test, I changed the first item in configliststudyitems to a dragon egg.)
	#Items consumed by citizens in the Library. 
	configliststudyitems = ["minecraft:dragon_egg;600;10", "minecraft:book;600;10"]

### Expected Behavior

Request all items in configliststudyitems at the same time, and don’t request them again if they are already available.

### Reproduction Steps

1. Build a library. 
2. Place books in the library. 
3. Recruit workers.

### Logs

No crash

### Anything else?

Curious, how many people are unaware that they can actually give them books to study, which are about 1,000,000 times better than paper?

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
> Curious, how many people are unaware that they can actually give them books to study, which are about 1,000,000 times better than paper?

Library students actually have requested books every once in a while
They may have done so after consuming the paper, though, so those items may be requested and used after each other rather than at the same time
