### ISSUE TITLE
AI log upload

### ISSUE THREAD

**Issue by IAM-png** [ldtteam/minecolonies#10212]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.20

### MineColonies Version

1.20.1-1.1.171-RELASE.jar

### Structurize Version

1.20.1-1.0.6333-BETA.jar

### Related Mods and their Versions

![grafik](https://github.com/user-attachments/assets/2f1a49da-057d-4823-9ab5-5a32ddb2ac67)
![WhatsApp Bild 2024-09-11 um 11 07 58_4d0e1209](https://github.com/user-attachments/assets/8f8c0759-1e67-4419-b42b-5fbde8e8e11a)
![2024-09-11_11 09 45](https://github.com/user-attachments/assets/b46c0615-ec93-4f4e-ac76-b79a58d85bb7)

### Logs

https://pastebin.com/a0Eu60ny

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
Your version of minecolonies is approximately a year old.

**Comment by Raycoms** [comment]
Please test with a new one and reopen if it occurs again
