### ISSUE TITLE
All couriers standing in warehouse, not delivering or picking up

### ISSUE THREAD

**Issue by vincentreynolds** [ldtteam/minecolonies#10214]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20

### MineColonies Version

1.1.661-snapshot

### Structurize Version

1.0.755-BETA

### Related Mods and their Versions

1. Forge: 47.3.3
2. Domum Ornamentum: 1.0.203-BETA

### Current Behavior

All couriers are standing around the warehouse hut block. They are not picking up, they are not delivering. They go home and go to bed, then come back and stand at the warehouse. Couriers are fully fed. Colony has two level 5 warehouses.

### Expected Behavior

Couriers pick up and deliver.

### Reproduction Steps

Current problems involve two worlds that have been growing for almost a year, so isolating the steps needed to reproduce the problem is difficult. Minimally, I would expect the problem to show if you:

1. Create a colony and advance to the point where there is a warehouse and at least one courier.
2. Set tasks that require the courier to make deliveries.

### Logs

https://gist.github.com/vincentreynolds/0de3f6ed7dea17c4acb0f71852d0dc36

### Anything else?

Resetting the request system seems to work around the problem.

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Estyria** [comment]
Not the first occurrence we’ve seen in the discord. In several others, resetting the request is not working and the couriers remain unresponsive.

**Comment by oatmealmanFG** [comment]
2 years later and still an issue

**Comment by Talyda** [comment]
> 2 years later and still an issue

No. It's not. You may have run into a new issue, in which case ask for help in discord, or open a new issue. Replying on a 2 year old issue just to complain, while giving absolutely no information at all, is totally pointless.
