### ISSUE TITLE
Destroying the WH hut chest should be acknowledge by the dman

### ISSUE THREAD

**Issue by xavierh** [ldtteam/minecolonies#1021]
### Minecolonies version

version/1.11

### Expected behavior

- destroying the warehouse chest, the dman should stop using the chests

### Actual behaviour

- the dman keep working as normal

### Steps to reproduce the problem

1. destroy the warehouse hut chest
2. The dman carry on as usual

**Comment by Raycoms** [comment]
He just continues working for a while?
Its possible that he just finishes his last task because he has the
reference to the last chest. then he should stop working.

2017-05-19 7:09 GMT-03:00 xavierh <notifications@github.com>:

**Comment by xavierh** [comment]
No. it did at least to gathering after that

**Comment by Raycoms** [comment]
Still happening?

**Comment by Raycoms** [comment]
Fixed
