### ISSUE TITLE
Improvement: Enhanced Builder Inventory Management

### ISSUE THREAD

**Issue by Rhodizzle** [ldtteam/minecolonies#1022]
Hey guys,

Great mod you have here. I have a suggestion for builder inventory that may help keep some of the messiness and inventory management for them more cleanly.

In short: Add a second chest to the builder hut for a dumping ground. Have the builder scan their inventory on each pass back to the hut and dump all materials not related to the current building's materials in that secondary chest so that they're only using the builder's hut inventory for materials that they build with. The deliveryman would have to be modified as well to understand to pull materials only from this second chest to go back to the warehouse and fulfill delivery requests only to the builder's chest.

**Comment by xavierh** [comment]
The delivery man is already picking up item not used by the builder.

Also you get additional chest when you upgrade the Builder's hut (level 3 or 4).

**Comment by Rhodizzle** [comment]
Ah ok, I'll close this then.

**Comment by Rhodizzle** [comment]
I suppose I should fully progress my buildings before getting all uppity and submitting change requests, lol.

**Comment by xavierh** [comment]
no problem :)
