### ISSUE TITLE
Build stage lost

### ISSUE THREAD

**Issue by chriskeena** [ldtteam/minecolonies#10223]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.21

### MineColonies Version

1.1.693

### Structurize Version

1.0.751

### Related Mods and their Versions

Neoforge 21.1.54

### Current Behavior

Deconstructed builders hut.
Placed builders hut in new location.
Hired same NPC as builder
Saw only option to build the hut as if new.

### Expected Behavior

Expected to see option to Upgrade hut after placing in new location.

### Reproduction Steps

Deconstruct builders hut.
Place builders hut in new location.
Hire same NPC as builder.
Not see option to Upgrade hut.

### Logs

https://mclo.gs/sEiUNk8

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by someaddons** [comment]
its not lost, you need to rebuild the building before you can upgrade to the next level, works as intended

**Comment by chriskeena** [comment]
> its not lost, you need to rebuild the building before you can upgrade to the next level, works as intended

Then this is new behaviour. In 1.20.1 and previous versions, relocating a building allows it to be rebuilt as an upgrade.
