### ISSUE TITLE
My AI has run into a problem - JobDeliveryman.finishRequest - Cannot invoke com.minecolonies.api.colony.requestsystem.request.IRequest.childStateUpdated 

### ISSUE THREAD

**Issue by TheRocket81** [ldtteam/minecolonies#10222]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.20

### MineColonies Version

1.20.1-1.1.669-snapshot-universal

### Structurize Version

1.20.1-1.0.742-RELEASE

### Reproduction Steps

Just upgraded from minecolonies-1.20.1-1.1.624-BETA to 1.20.1-1.1.669-snapshot-universal

Have a Courrier complete a delivery. I have 3 warehouses in world, about 18 courriers fullfilling tasks. No major issues prior to update. First ~15 minutes of playing with the new version, this error comes up.

### Logs

https://gist.github.com/TheRocket81/2f33ff3eaab410cab58f290af330320c#file-log-txt-L3702

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
This will fix itself over time or through a request system reset.
Also recommended to update to version 670 as soon as it's available.
