### ISSUE TITLE
Builder just stops!

### ISSUE THREAD

**Issue by mistresskahlan** [ldtteam/minecolonies#1023]
### Minecolonies version
curse 1.10.2-0.8.1331

### Expected behavior
- builds all the buildings I tell him to!

### Actual behaviour
- stops working after a while with no reason, no text info.

### Steps to reproduce the problem
1. Build builders hut,
2. build other buildings
3. keep going until he gives up.

I can't fire him, re-hire him, the button does nothing. I can recall him, but he just stands anywhere and does nothing. I killed him, but new builder just stands around doing nothing. I killed everyone, no new people reappear. I've checked items, but the item list is blank, the jobs list is full, he has tools etc but does nothing.
![2017-05-19_11 35 47](https://cloud.githubusercontent.com/assets/2369033/26256894/6d21f75c-3cb6-11e7-8a35-e00085129d3b.png)
![2017-05-19_11 35 51](https://cloud.githubusercontent.com/assets/2369033/26256893/6d21d8a8-3cb6-11e7-9139-c8ed1041a460.png)
![2017-05-19_11 35 59](https://cloud.githubusercontent.com/assets/2369033/26256891/6d21122e-3cb6-11e7-98eb-3afcced4dac6.png)
![2017-05-19_11 36 02](https://cloud.githubusercontent.com/assets/2369033/26256895/6d2b46ae-3cb6-11e7-9594-8188cd691dbc.png)
![2017-05-19_11 36 05](https://cloud.githubusercontent.com/assets/2369033/26256890/6d1f4ade-3cb6-11e7-9bf7-660e9181847c.png)
![2017-05-19_11 36 10](https://cloud.githubusercontent.com/assets/2369033/26256892/6d21273c-3cb6-11e7-8fef-a64fffc8e5a5.png)

**Comment by Raycoms** [comment]
Do you have the logs as well?

2017-05-19 13:13 GMT-03:00 Larkin <notifications@github.com>:

**Comment by xavierh** [comment]
For Hire/Fire, you need to set the hiring mode to manual in the Town Hall first

**Comment by mistresskahlan** [comment]
[2017-05-19-2.log.gz](https://github.com/Minecolonies/minecolonies/files/1015007/2017-05-19-2.log.gz)
Heres the log

**Comment by mistresskahlan** [comment]
While I'm here, why don't they builders take more than just a handful of materials?

**Comment by Raycoms** [comment]
Because they can't, its a future feature =)

2017-05-19 17:26 GMT-03:00 Larkin <notifications@github.com>:

**Comment by mistresskahlan** [comment]
that's a shame, things would be so much faster if they did.

**Comment by Raycoms** [comment]
We would have to slow him down then, would be a bit too op if the builder
builds that much faster than any player, don't you think?

2017-05-19 17:29 GMT-03:00 Larkin <notifications@github.com>:

**Comment by WheresMyMtnDew** [comment]
I am also having this issue. So is a friend of mine who is playing on a lan with me. Our builders just stopped and now have no inventory and are completely unresponsive. (inventory is still there and can access it but they are empty). Also the builder's hut is not reading that there is a build request because it is not asking for any items. (our towns are in other areas of the world and are no where near one another)

**Comment by SkullCrusher548** [comment]
I am having the same issue..The biuld just stands in his hut .No messages,has everything he needs to build.Ive tried firing him,rehiring him and another citizen,cleaning his inventory and chest and still does nothing but stand there

**Comment by Raycoms** [comment]
If happens again, please reopen.

**Comment by Nayzal** [comment]
This is happening with my builder in 1.15.2.
