### ISSUE TITLE
Warehouse Hut not accesible via hoppers (or other mod pipes)

### ISSUE THREAD

**Issue by maashrafh** [ldtteam/minecolonies#10246]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [X] Multi Player

### Minecraft Version

1.21

### MineColonies Version

1.1.705-1.21.1-snapshot

### Structurize Version

1.0.751-1.21.1-snapshot

### Related Mods and their Versions

appliedenergistics2-19.0.23-beta

### Current Behavior

The warehouse hut block is currently not able be to have items retrieved or to receive any items from any block sides via a vanilla hopper (or mod pipes). Tested using vanilla hoppers and AE2 storage bus.

Other hut blocks seem unaffected, and interacts normally with hoppers and the storage bus.

### Expected Behavior

Warehouse hut block should be able to have items retrieved and receive items on any block side via hoppers.

### Reproduction Steps

1. Build warehouse with build tool.
2. Attach hopper to warehouse hut block.
3. Add items to hopper. Observe no items moved from hopper to warehouse hut block or surrounding racks. 

### Logs

n/a

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
duplicate

**Comment by maashrafh** [comment]
which issue does this duplicate? i looked for a similar issue before making this issue, and couldnt find any.

**Comment by Raycoms** [comment]
weird, the other one was closed it seems, so I'll reopen this one

**Comment by Raycoms** [comment]
fixed
