### ISSUE TITLE
NPC's halt on spot on/in fishing hut

### ISSUE THREAD

**Issue by TheQuadShot** [ldtteam/minecolonies#1024]
The Builder and the Deliveryman will stop on that spot and just stand there. If I recall them and they path next to that spot they will repeat. If they path to the other side of the building they don't

ScreenShot
http://imgur.com/bMkOPdq

Minecraft 1.10.2
minecolonies-universal-1.10.1-0.7.848
Forge-12.18.3.228

ModList
https://pastebin.com/QpQ9ff3x

**Comment by Raycoms** [comment]
Yeah, unfortunately, minecraft locomotion doesn't know what to do there, we're planning to make it work later on, there must be an issue for that already somewhere.
