### ISSUE TITLE
Apiary not saving assigned hives

### ISSUE THREAD

**Issue by Mikec78660** [ldtteam/minecolonies#10250]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.21

### MineColonies Version

1.1.705-1.21.1-snapshot

### Structurize Version

1.0.751-1.21.1-snapshot

### Related Mods and their Versions

1. Neoforge 21.1.57
2.  domum_ornamentum-1.0.203-1.21.1-snapshot
3.  Jade-1.21.1-NeoForge-15.4.1
4.  jadecolonies-1.21.1-1.6.0
5.  jei-1.21.1-neoforge-19.18.8.212
6. midnightcontrols-neoforge-1.10.0-beta.1
7. multipiston-1.2.50-1.21.1-snapshot
8. supermartijn642configlib-1.1.8-neoforge-mc1.21
9.  supermartijn642corelib-1.1.17i-neoforge-mc1.21
10. towntalk-1.2.0

### Current Behavior

Get the assign tool from the apiary block. Mark the hives. colonist starts gathering honey and honey comb. Colonist will keep working collecting honey and honey comb until you log out and log back in then no hives are assigned to the block. If you move away from the colony until the colony unloads and move back in the hives stay assigned to the block. It is only when you close the game and restart it the hives become unassigned.

### Expected Behavior

Assign the hives to the hut block block. Exit the game and when you restart it the hives are still assigned to the block.

### Reproduction Steps

build an apiary, assign a hive to the hut block block. Exit the game. Load the work again and grab the assign tool from the hut block and see the hut block will be outlined in red but the hives are not outlined in yellow. Or click on the colonist who will tell you that no hives are assigned to his hut.

### Logs

https://gist.github.com/Mikec78660/e7436d4bc44fd4e88bbc11a41d05eb6e

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
fixed
