### ISSUE TITLE
Permissions do not save

### ISSUE THREAD

**Issue by RickieGamer** [ldtteam/minecolonies#10253]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.21

### MineColonies Version

1.1.705-1.21.1

### Structurize Version

1.0.751.1.21.1

### Current Behavior

Changing Permissions in my town hall hut block do not save
Adding another player as friend, they still aren't able to interact with anything
after a while it swaps the perms back to Neutral 

### Expected Behavior

Expect the perms to save

### Reproduction Steps

Open TH Hut
Add player as friend/officer
Watch them be denied perms

### Logs

https://mclo.gs/XKLkbBY

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
fixed
