### ISSUE TITLE
Tool requests are broken if a previous tool has been consumed [1.21.1]

### ISSUE THREAD

**Issue by IchHabeHunger54** [ldtteam/minecolonies#10258]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.21

### MineColonies Version

1.1.702-1.21.1-snapshot

### Structurize Version

1.0.751-1.21.1-snapshot

### Related Mods and their Versions

NeoForge 21.1.54
Others should not be relevant, can provide if needed.

### Current Behavior

I noticed this first with builders, but it has since extended to also foresters as soon as I built one, so I'm assuming this is a general problem.

Basically, when a builder or forester or other tool-using profession uses up a tool, they will request a tool and set themselves into the `needs_item` job state (confirmed via `/minecolonies citizen`), as would be expected. However, the tool request never makes it into the request system, causing the builder to idle in their hut.

Things to note:
- The request is never actually broadcast to the system, nothing is visible in the clipboard and the couriers do not deliver anything.
- There is also nothing in the builder's requests tab.
- Giving them the item directly or into the hut inventory does NOT resolve the issue. My current workaround is to give them the item, then fire and rehire, as this resets the internal state. This is obviously a bad and unintuitive solution.

### Expected Behavior

Tool requests to properly propagate to the request system.

### Reproduction Steps

Note: The reproduction steps are not 100% clear because sometimes, it magically works; though more often than not, it is broken.

1. Place down a builder's hut and hire a builder, ideally in a place where they need to dig out a bit.
2. Start construction of the building. They will request a tool to dig out some ground.
3. The issue may already arise here. If it does not, fulfill their request and wait until they use up the tool.
4. The issue has (should have) been replicated.

### Logs

N/A

### Anything else?

I'm running a modpack of ~90-100 mods, so it is unlikely but possible that this is a bad mod interaction. If you cannot reproduce, please let me know, and I will provide the mod list.

This issue was also touched upon in #10255, which reported another bug I also encountered.

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
Thanks for figuring out the details what causes this, had several reports but couldn't find a reproduction.
Will try tomorrow.

**Comment by Talyda** [comment]
Oh, I mentioned it in passing in my forester zone tool not working report too. I had to give the forester all the tools, but they were still asking for an item in citizen info command, and then had to do a request system reset for them to actually start moving. Freshly hired, so there had been no tool breaking. Glad you worked it out!

**Comment by IchHabeHunger54** [comment]
Important note: This appears to be a multiplayer-exclusive issue. I tried and failed to reproduce this bug in singleplayer.

**Comment by Thodor12** [comment]
Couldn't reproduce this, confirmed it seems to be working in the newest version.
