### ISSUE TITLE
Bakery gives missing respective block error

### ISSUE THREAD

**Issue by sendelp** [ldtteam/minecolonies#10252]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20

### MineColonies Version

minecolonies-1.20.1-1.1.673-snapshot-universal.jar

### Structurize Version

structurize-1.20.1-1.0.742-RELEASE.ja

### Related Mods and their Versions

1. Forge - 47.3.0 
2. BlockUI - blockui-1.20.1-1.0.156-RELEASE.jar 
3. Domum - domum_ornamentum-1.20.1-1.0.186-RELEASE-universal.jar
4. Multi-piston - multipiston-1.20-1.2.43-RELEASE.jar
5. Modpack: ColonyState 6 https://www.curseforge.com/minecraft/modpacks/colonystate-6

### Current Behavior

The bakery hut block is giving me the error of "This block is missing its respective building, try restarting or loading a backup!". This is not fixed by waiting, restarting the game/server, or any other things that normally fix this issue. It is only happening to me on the server, other people can access the bakery fine, and it is not happening to me in single player.

### Expected Behavior

The bakery hut allows me to access its GUI, whether immediately, or after letting the hut load for a while the error should disappear

### Reproduction Steps

Please note that, for whatever reason, this is only happening in multi player for me, and the bakery hut works perfectly fine in singleplayer, so I am not sure how reproducible this will be, but I was told to create a github issue on the discord.
1. Use the above modpack (ColonyState 6) in multiplayer (I am specifically on TimeLordVampire's server the ColonyState 6 pack was created for)
2. Use spruce medieval style (Though this is happening for all styles for me)
3. Place down bakery hut (doesnt matter if its with the wand or by hand)
4. It gives the missing respective block error, and does not allow access to its GUI

### Logs

https://gist.github.com/sendelp/83b27e6e915201ce7cdd99afa7dd87a9

### Anything else?

This was previously happening to me with the Cookery hut, and that was fixed when the server updated Minecolonies, but now it is happening with the bakery instead. Another person was having this issue with both the cookery and bakery, but updating fixed it fully for them. Other people on the server are also experiencing this issue, one person with both the cookery and bakery still, and other people have no issues at all.
Things I have tried to fix the issue:
Reset my game
Waited for the server to restart
Broke and replaced the hut block
Made a new hut block
Tried in a different style
Tried placing it using both the building tool and placing the hut by hand, both have the same result
The hut block is not within any other mod's claimed chunks (FTB chunks, etc)

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by sendelp** [comment]
Please let me know if the gist github link is the right log, for me it shows an older log when I click it even though I submitted the latest one, but Shindria on the discord could see the correct one, so I'm not sure.

**Comment by Raycoms** [comment]
[12:07:45] [modloading-worker-0/WARN]: |======================================================================================================================================|
[12:07:45] [modloading-worker-0/WARN]: |                                                                                                                                      |
[12:07:45] [modloading-worker-0/WARN]: | Minecolonies has detected an addon mod that alters Minecolonies core code recklessly: 'Tweaks/Compatibility addon for Minecolonies'. |
[12:07:45] [modloading-worker-0/WARN]: |          Please report any bugs or issues you find directly to the authors of this addon, as the Official Minecolonies Team          |
[12:07:45] [modloading-worker-0/WARN]: |               will not be able to provide you any support with potential issues that will arise when using this addon.               |
[12:07:45] [modloading-worker-0/WARN]: |                                                                                                                                      |
[12:07:45] [modloading-worker-0/WARN]: |======================================================================================================================================|


That is most likely the problem

**Comment by Talyda** [comment]
...I legitimately did not see that! Sorry! I was focused on the end of the log
