### ISSUE TITLE
Cannot rebuild town hall after picking it up. Message "Error on placement! You are too close to an existing colony!" appears.

### ISSUE THREAD

**Issue by Goldenheart176** [ldtteam/minecolonies#10266]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.21

### MineColonies Version

minecolonies-1.1.700-1.21.1-snapshot.jar

### Structurize Version

1.0.751-1.21.1-snapshot.jar

### Related Mods and their Versions

Direwolf20 Season 14 Modpack on Curseforge

### Current Behavior

I picked up the town hall block from the build menu and attempted to move it (had not built the town hall yet and wanted to reposition). I tried both the build tool and by hand, and got the message "Error on placement! You are too close to an existing colony!" Citizens also are completely missing aside from one visitor in the tavern. Some huts still show who was living there/working there.
Relogging or reloading the client does not fix issue. Sent from the discord server. One other person was experiencing the same issue. 

### Expected Behavior

Expected behavior:
Have a town hall block. Town hall is not built yet, and town is functioning properly.
Pick up the town hall block.
Use the build tool to maneuver and place the town hall again.
Block should appear, construction tape should reappear.

### Reproduction Steps

1. Have medieval oak town. 
2. Have unbuilt town hall. 
3. Pick up town hall through the build menu.
4. Attempt to rebuild town hall with the build tool. Citizens disappear and error message "Error on placement! You are too close to an existing colony!" appears.

### Logs

https://mclo.gs/lCbrlJF

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
Just to add to this, I asked them to stand in the chunk where their town hall used to be, and run the "/mc whereami" command, and it told them they weren't in a colony, so I think it is related to https://github.com/ldtteam/minecolonies/issues/10261 and using the pickup option unclaimed the chunks
