### ISSUE TITLE
Buildings with no racks undeliverable to

### ISSUE THREAD

**Issue by Moobien** [ldtteam/minecolonies#10262]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [X] Multi Player

### Minecraft Version

1.20

### MineColonies Version

1.1.673

### Structurize Version

1.0.755

### Related Mods and their Versions

n/a

### Current Behavior

Buildings that don't have a rack cannot be delivered to by a courier. up until now, this has never been a problem

https://discord.com/channels/139070364159311872/1125094832143077456/1287688470021799987

### Expected Behavior

all huts are deliverable to whether they have a rack or not. this has NEVER been an issue in the past, as an example the pagoda herders have worked fine for years but now they suddenly are not deliverable to.

### Reproduction Steps

n/a

### Logs

n/a

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.
n/a

**Comment by Raycoms** [comment]
Can't reproduce, let user create issue with log if it still happens.
