### ISSUE TITLE
Chunks getting Unclaimed after picking up a hut in the menu.

### ISSUE THREAD

**Issue by FinalLavos** [ldtteam/minecolonies#10261]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.21

### MineColonies Version

1.1.707

### Structurize Version

1.0.751

### Related Mods and their Versions

NeoForge 21.1.54  Domum Ornamentum 1.0.203

### Current Behavior

When I go to pick up a hut in the menu it will unclaim chunks for my colony in the initial area that gets claimed. This happens with any hut and style.
![2024-09-22_23 29 42](https://github.com/user-attachments/assets/8ae95c43-a2b6-487a-a6cc-edf50d118f85)

### Expected Behavior

Pick up the hut without any of the initial area getting un-claimed

### Reproduction Steps

1. Place down a hut in the initial area. 2. Go into the hut menu and pick up the hut block.

### Logs

<script src="https://gist.github.com/FinalLavos/8c16c74f707bb363b59abb80c5465ad2.js"></script>

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
Just adding confirmation on this one, I tested it as well.
Don't need to build the hut or anything, just place it, then pickup from build menu
