### ISSUE TITLE
Incan style uses default mineshafts because the style misplaced their own mineshafts

### ISSUE THREAD

**Issue by Shadizar** [ldtteam/minecolonies#10272]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.21

### MineColonies Version

1.1.703

### Structurize Version

1.0.751

### Current Behavior

![image](https://github.com/user-attachments/assets/98b3be26-b8f5-4061-bd07-ce99ea4d790a)
![image](https://github.com/user-attachments/assets/c3059d1f-99ba-48bb-8bd5-99df53cf7461)

As can be seen, the Incan mineshafts are in a nonstandard folder, and the built mineshaft is not Incan style

### Expected Behavior

![image](https://github.com/user-attachments/assets/a8836558-7ab3-48ea-b4bb-7d4d75b5ce56)

Expected Incan style mineshafts, since they exist

### Reproduction Steps

Build mine
Let the miner do their mining thing
Observe incorrect shafts

### Logs

n/a

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
This should have been closed when the PR was merged. Apparently it did not pick that up
