### ISSUE TITLE
Schematic Analyzer crashes game when hovering over it

### ISSUE THREAD

**Issue by Neronya11** [ldtteam/minecolonies#10276]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [X] Multi Player

### Minecraft Version

1.21

### MineColonies Version

1.1.708-1.21.1-snapshot

### Structurize Version

1.0.751-1.21.1-snapshot

### Related Mods and their Versions

Neoforge 21.1.61
domum_ornamentum-1.0.203-1.21.1-snapshot
multipiston-1.2.50-1.21.1-snapshot
blockui-1.0.190-1.21.1-snapshot

### Current Behavior

Whenever I hover over the Schematic Analyzer either in EMI or my own inventory, the game crashes. (Holding it in my hand does not crash, only if I hover over it)

### Expected Behavior

The game to not crash.

### Reproduction Steps

1. Simply hover over it in EMI or in your inventory

### Logs

https://mclo.gs/zKvzPek

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Satherov** [comment]
This issue is currently happening to everyone playing AllTheMods10

**Comment by someaddons** [comment]
fixed in newest
