### ISSUE TITLE
Builders have stop working!!!!!

### ISSUE THREAD

**Issue by SkullCrusher548** [ldtteam/minecolonies#1028]
### Minecolonies version

version minecolonies-universal-1.11.2-0.8.1258

I have tried everything from ,firing,rehiring him and other citizen,clearing inventory and chest and still all both do is stand at the chest Please help
![screenshot 101](https://cloud.githubusercontent.com/assets/25522161/26283397/c0f96758-3df5-11e7-8bb1-3db85365f017.png)

**Comment by xavierh** [comment]
You can set the development option on in the config file. It will give you
more information.
I suspect they either need food or a particular tool

**Comment by Raycoms** [comment]
with /mc citizens citizenInfo name

You can get even more info on them.

2017-05-21 8:58 GMT-03:00 xavierh <notifications@github.com>:

> You can set the development option on in the config file. It will give you
> more information.
> I suspect they either need food or a particular tool
>

**Comment by Raycoms** [comment]
If it happens again, please reopen
