### ISSUE TITLE
crash when breaking plantation field block

### ISSUE THREAD

**Issue by Talyda** [ldtteam/minecolonies#10285]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.21

### MineColonies Version

1.1.711

### Structurize Version

1.0.752

### Current Behavior

Try to break plantation field block, game crashes

### Expected Behavior

Game doesn't crash

### Reproduction Steps

Place plantation field block
Try to break plantation field block
Crash

### Logs

https://gist.github.com/Talyda/4c8dabeee7d11d26ae2283c5bb0229fc

### Anything else?

crash log too: https://gist.github.com/Talyda/3f10e272a393407cc8065ceb1dda5eb5

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
fixed
