### ISSUE TITLE
Vanilla recipes are not offered in the builder's settings -> "fill block" menu

### ISSUE THREAD

**Issue by ncottrill** [ldtteam/minecolonies#10280]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.21

### MineColonies Version

1.1.707

### Structurize Version

1.0.751

### Related Mods and their Versions

ATM 10 modpack

### Current Behavior

I need to change the builder's fill block to vanilla "sand" block.
There are hundreds of sand types in the list, but not vanilla sand.

### Expected Behavior

I expect vanilla recipes to always be at the top of any Minecolonies "select block" option in the GUI.
There are modpacks that add 100s of items to the "select block" option in the GUI. Vanilla items should be listed first.

### Reproduction Steps

Play ATM 10 modpack
Make a "Desert Style" build
Try to change the builder's fill block to sand.

### Logs

This is not going to be a logged error 

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
There is no sand block in there because falling blocks are not considered solid. Other sands might weirdly bypass this.
