### ISSUE TITLE
AI log upload

### ISSUE THREAD

**Issue by Stevethreeb** [ldtteam/minecolonies#10303]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.21

### MineColonies Version

1.1.719-1.21.1

### Structurize Version

1.0.752-1.21.1

### Reproduction Steps

Builders Hut at level 4 and 5. The builders, which happened in 4 different cases stopped performing building tasks. 
They all had the message that there was an issue with their AI and to submit the logs. 

Tried to break the builders hut block and reinstall it, but they wont build the new builders blocks either. 

One unrelated thing that happened is that there were a couple occurrences where citizens would glitch from location to another really fast, without resolving their path. 

### Logs

https://gist.github.com/Stevethreeb/4510fae1c55ec93db0605c530eb3a6d0

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Stevethreeb** [comment]
So i tried from the ground up again. It appears to only start happening once the builders hut is being upgraded from Builders Hut 4 to 5
I'm using the medival spruce style

**Comment by Talyda** [comment]
Which one of the builders huts BTW? The one that is like three little buildings, or the single building one?

**Comment by Stevethreeb** [comment]
> Which one of the builders huts BTW? The one that is like three little buildings, or the single building one?

The singular building. One of the members in the discord suggested that it was potentially due to the claim / force load chunks mods, but even disabled the issue is occurring

**Comment by Stevethreeb** [comment]
Also for more context, this is in the ATM10 modpack

**Comment by Talyda** [comment]
In case it helps, I recreated it in a mostly clean instance too. Same level 4-5 medieval spruce builder. Log below

https://gist.github.com/Talyda/348ee40d22e3023329f74d9234d0ae09

**Comment by iangifford** [comment]
Same as https://github.com/ldtteam/minecolonies/issues/10264

**Comment by Raycoms** [comment]
fixed
