### ISSUE TITLE
GL Error in Build tool window

### ISSUE THREAD

**Issue by cltnschlosser** [ldtteam/minecolonies#1030]
### Minecolonies version

version 1.11.2

### Steps to reproduce the problem

1. Open build tool window
2. Click on one of the buttons to open the "drop down" menu. (See attached screenshot)
3. Log is spammed with:
```
[11:33:55] [Client thread/ERROR]: ########## GL ERROR ##########
[11:33:55] [Client thread/ERROR]: @ Post render
[11:33:55] [Client thread/ERROR]: 1281: Invalid value
```

![2017-05-21_11 33 44](https://cloud.githubusercontent.com/assets/1498529/26285781/d951b776-3e1b-11e7-9c0a-f6546b57fd72.png)

**Comment by xavierh** [comment]
Yes I need to look into that

**Comment by cltnschlosser** [comment]
Generally you shouldn't close issues until after they are merged. If you use the right Closes #... phrases they will be auto closed on merge.
