### ISSUE TITLE
Nordic spruce style mine getting stuck.

### ISSUE THREAD

**Issue by starfall18** [ldtteam/minecolonies#10300]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20

### MineColonies Version

1.1.681-snapshot

### Structurize Version

1.0.755-beta

### Related Mods and their Versions

1. Forge version : 47.3.7
2. BlockUI version: 1.0.186-beta
3. Domum Ornamentum version: 1.0.203-beta
other mods from ATM9 modpack version: 0.3.2

### Current Behavior

Miner sometimes ends up building a tunnel that is not connected to the main tunnel system and gets stuck doing so. Probably cause he cant reach to finish the tunnel. I have to physically take down the wall that is connecting it to the main tunnel for the miner to continue their work. The wall i have to break down is not touched by the miner in any way, no blocks have been filled and no blocks have been broken.

### Expected Behavior

Miner being able to dig tunnels without any interference from me.

### Reproduction Steps

1. Place a mine (Nordic spruce, if that matters)
2. let him start digging tunnels
3. sometimes he gets stuck cause he cant reach a tunnel he built because it is isolated from the rest of the tunnel system.

### Logs

https://gist.github.com/starfall18/f6a727542b523c79c5996cbe1bcfe8cb

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
#5006 and @kedamono maybe some of the shaft here are also wrongly rotated like it was in the desert style
