### ISSUE TITLE
Citizens not showing 

### ISSUE THREAD

**Issue by emilyxwardx** [ldtteam/minecolonies#10301]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest Structurize Version?

- [X] I am running the latest **beta/release** version of Structurize for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/).

### Minecraft Version

1.21

### Structurize Version

1.1.707-snapshot

### Problem description

Citizens having AI issues, theyre stuck in place, no name and unable to do anything

![2024-10-02_15 13 56](https://github.com/user-attachments/assets/68d4de3f-499e-4ae3-82f9-4d4804f36bac)

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
log please

**Comment by emilyxwardx** [comment]
[2024-10-01-1.log.gz](https://github.com/user-attachments/files/17232784/2024-10-01-1.log.gz)

**Comment by Raycoms** [comment]
Can you upload it as a gist please?

**Comment by emilyxwardx** [comment]
https://gist.github.com/emilyxwardx/ba7bd5e1674b167710f6d07ca990b425.js

**Comment by emilyxwardx** [comment]
https://gist.github.com/emilyxwardx/ba7bd5e1674b167710f6d07ca990b425#file-gistfile1-txt

i think ive done it right? lol

**Comment by Raycoms** [comment]
Yes, but unfortunately it doesn't contain anything useful, can you send the latest.log for a moment where this issue persists?

**Comment by emilyxwardx** [comment]
https://gist.github.com/emilyxwardx/f91a62ac83c9203f698f12628582ff7c#file-gistfile1-txt

this was the LATEST one

**Comment by Raycoms** [comment]
@uecasm maybe sth interesting for you in there?

**Comment by Loose-Morals** [comment]
I am also having this same issue. i posted on the discord about it, but figured it couldn't do any harm to post here too. here is the gist I made yesterday.
https://gist.github.com/Loose-Morals/371071dc27995f12392bba6a88b64599

And today when I logged in, the issue has spread to another citizen, so its getting worse.
Here is todays Gist. just in case it has something for you to see.
https://gist.github.com/Loose-Morals/316aa06dbea19d66561cd148bf39afc4

**Comment by Raycoms** [comment]
When was the last server restart?

**Comment by emilyxwardx** [comment]
It's been restarted multiple times, so it's not a restart issue

**Comment by Estyria** [comment]
This bug has persisted a long time, devs. We’ve had people report it across multiple versions now, and while restarts may temporarily fix the colonists, it always comes back.

**Comment by someaddons** [comment]
we'll need the serverside logs for this bug, this is nearly always a case of server not syncing data

**Comment by Raycoms** [comment]
It's a long time bug, we don't know how to solve yet, yes

**Comment by jennLumm** [comment]
can anyone share your behavior right before this bug happened?

i was completing upgrading residence,
turn off the town's new citizens spawning option, 
recruit a new citizen and hire them to university,
proceed night-owl research,
upgrading library, deconstructing guard tower
(and im using Pagoda theme on my colony)

please let me know if there's anything similar part with me

**Comment by Raycoms** [comment]
Do these broken citizens persist through restart?

**Comment by emilyxwardx** [comment]
They fix temporarily with a restart and then it will do it again

**Comment by jennLumm** [comment]
yes..and after the restart, random citizen takes over the glitch, as if it were contagious

**Comment by Zarlios** [comment]
Since this was never mentioned I thought I would provide some insight.  Every time this happens, the people are outside of my "loading range".  I can see them on my map, but they are very far away from me for long periods of time.  Could this be related?

**Comment by Raycoms** [comment]
Potentially yes. can you test if this stll happens with the newest?

**Comment by Zarlios** [comment]
I am using ATM9 so I can't change the version of minecolonies.  I am on the 0.3.2 version of ATM9
