### ISSUE TITLE
Minecolonies in ATM 10 modpack is being blamed for server not starting - conflict parsing loot table of productive bees mod

### ISSUE THREAD

**Issue by ncottrill** [ldtteam/minecolonies#10318]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.21

### MineColonies Version

1.1.719

### Structurize Version

1.0.752

### Related Mods and their Versions

Modpack ATM 10 v 10-0.61

### Current Behavior

Sometimes the server doesn't start at all. The last errors in the logs involve Minecolonies and Productive Bees. Players in the AllTheMods/ATM10 Github issues keep reporting that Minecolonies is preventing their server from starting at all. I use Sam's Performant mod, which corrects many errors/conflicts so it could be why our server works at all. The other ATM 10 players don't have this Performant mod.

Anyway, here is the start up log

https://mclo.gs/uzJRUBs

### Expected Behavior

The server should start consistently on reboot.

### Reproduction Steps

Install ATM 10 10-0.61
Build a Minecolonies colony
Start working with Productive Bees (we have about 50 bees in simulators - not running free but locked in a hive)
Test rebooting server observe startup log

### Logs

https://mclo.gs/uzJRUBs

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Yeah, that's just a spammy log from loottable analysis, we toned that down in the latest. But this doesn't prevent any starting

**Comment by ncottrill** [comment]
Ok. I think because it is (was?) the last thing that server owners see before the "server failed to start" in the logs, Minecolonies being blamed in ATM 10 issues list for preventing the server from starting at all.

**Comment by Raycoms** [comment]
Yeah, people don't know how to read logs and just blame whatever mod that printed the last thing

**Comment by ncottrill** [comment]
PS. Did this spam also get removed? This is a continuous (doesn't stop) output in the console

[06:43:25] [Server thread/WARN] [minecolonies/]: Calculated rotation doesn't match recorded: x:0 z:0
[06:43:26] [Server thread/WARN] [minecolonies/]: Calculated rotation doesn't match recorded: x:0 z:0
[06:43:27] [Server thread/WARN] [minecolonies/]: Calculated rotation doesn't match recorded: x:0 z:0

**Comment by ncottrill** [comment]
![image](https://github.com/user-attachments/assets/6443e829-a0b8-4daa-bb2c-5af065b523da)

Still have some spam and no x y z given for me to discern source :(

**Comment by Raycoms** [comment]
This is the miner

**Comment by ncottrill** [comment]
We updated server to minecolonies-1.1.723-1.21.1-snapshot.jar and still having the (above image) miner text spamming server.

**Comment by Raycoms** [comment]
I tried repro, but couldn't yet, did you mirror your miner?

**Comment by ncottrill** [comment]
I didn't but there are 7 other players ... If I had coords in that message, I could go check it out.

**Comment by ncottrill** [comment]
Maybe ... relegate this message to a dev debug comment vs. server console output?

**Comment by Raycoms** [comment]
It's not coords, it's the relative coords from the mine
