### ISSUE TITLE
Invalid seed in field: Wheat

### ISSUE THREAD

**Issue by Almandor** [ldtteam/minecolonies#10314]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.21

### MineColonies Version

minecolonies-1.1.719-1.21.1-snapshot

### Structurize Version

structurize-1.0.752-1.21.1-snapshot

### Related Mods and their Versions

Neoforge 21.1.61
blockui-1.0.192-1.21.1-snapshot

### Current Behavior

The farm allows to select Wheat as seed. This makes the farmer running all around the field, trying unsuccessful to plant the wheat. 

### Expected Behavior

Since the correct seed is "Wheat seed" Wheat should not be in the list.

### Reproduction Steps

Place farm, open scarecrow menu, select "pick seeds", observe Wheat in the menu

### Logs

-

### Anything else?

![image](https://github.com/user-attachments/assets/f0a1f325-347f-47df-a17b-1cb21ac89c70)

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Estyria** [comment]
^ This seems like a small oversight, so they were sent to report it.

**Comment by Thodor12** [comment]
I am unable to reproduce this bug, probably have a weird datapack that lists wheat as if it were a seed, nothing we can do to fix that.

**Comment by Raycoms** [comment]
Did you try in 1.21?

**Comment by Thodor12** [comment]
Yeah
