### ISSUE TITLE
Colonists unusable

### ISSUE THREAD

**Issue by Estyria** [ldtteam/minecolonies#10327]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20

### MineColonies Version

1.20.1-1.1.685

### Structurize Version

1.20.1-1.1.760

### Current Behavior

Colonists become unresponsive. No trigger known. 

https://github.com/user-attachments/assets/e35054ac-fea7-41c6-b52b-448b4e0374ac

![image](https://github.com/user-attachments/assets/d0c6c98d-45fc-45a2-81e9-1b04437722f3)

### Expected Behavior

Colonists should work and not bug out

### Reproduction Steps

1. Start a colony on multiplayer (patreon raid server in this case)
2. Develop colony
3. Witness eventual bugginess

### Logs

https://gist.github.com/Estyria/0f4432bdb2e289abc25fe5c07f47863e

### Anything else?

"Wait until server restart" is really, really not what I hope to hear from you guys on a competition server where every colonist and every minute counts. Can we please get this sorted? It's been a big problem for all of 1.20.1 now, but has never been *this* bad in previous versions. So something darn well changed.

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
Just wanna add on here, I feel like we have seen increased reports of this on public discord just recently too. And pretty sure server restart isn't actually fixing it for everyone

Here's one report on discord: https://discord.com/channels/139070364159311872/1003402487417548801/1291402590550097982
(for some reason I remembered that one)

**Comment by Raycoms** [comment]
fixed
