### ISSUE TITLE
New Citizens spawning with all 1 in stats (including happiness)

### ISSUE THREAD

**Issue by Talyda** [ldtteam/minecolonies#10320]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20

### MineColonies Version

minecolonies-1.20.1-1.1.684-snapshot

### Structurize Version

structurize-1.20.1-1.0.760-snapshot

### Current Behavior

Start colony, wait for citizens to spawn. The first one spawns in with assorted stats, the next three citizens all spawn in with 1's across the board.
I loaded up an old version of the mod to double check I wasn't misremembering how it worked, and in older versions all four initial citizens start with random stats

### Expected Behavior

All four citizens get random stats

### Reproduction Steps

Start colony, wait for citizens to spawn, see stats

### Logs

https://gist.github.com/Talyda/8fbd2c2f261491ecd3c5a3257287cb75

### Anything else?

Log's from old version when it did work as expected, I can grab a new one if you think it will show anything relevant

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
I suddenly realised that they are probably spawning with 1 in all stats cos the very first citizen spawns in with 1 happiness? They used to spawn in with happiness of 5

**Comment by Axl-Lvy** [comment]
Hi everyone, I was able to reproduce the issue using the very last version (local build on main). The very first citizen starts with random stats but happiness of 1, then the other ones start with every stat at 1.
