### ISSUE TITLE
Minecolonies food in bowls disappear after eating 

### ISSUE THREAD

**Issue by SteefVanOranje** [ldtteam/minecolonies#10321]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20

### MineColonies Version

1.20.1-1.1.684

### Structurize Version

1.20.1-1.0742

### Current Behavior

I have a stack of minecolonies food in a bowl (tomato pasta for example). If I eat one item of this food. The whole stack disappears and I am left with only one empty bowl.

### Expected Behavior

After eating a minecolonies food in a bowl. One food item of the food which you have eaten should disappear. If I have 64 tomato pasta and eat one, I should have 63 tomato pasta and 1 empty bowl in my inventory.

### Reproduction Steps

Get a stack of tomato pasta, plain pasta or pottage.
Eat the food
The whole stack will disappear and you will be left with only 1 empty bowl

### Logs

https://gist.github.com/SteefVanOranje/0e3750ce0487543510f751ce09e767d9

### Anything else?

Shindria has tested with various minecolonies bowl food and confimed the issue. I have made this github issue on her request.

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Urkaz** [comment]
They now keep the bowl in their inventories, hoarding as if they were their most valuable treasure
