### ISSUE TITLE
Residents choose to drown rather than walk longer

### ISSUE THREAD

**Issue by Gerpuss** [ldtteam/minecolonies#10326]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20

### MineColonies Version

1.20.1-1.1.686

### Structurize Version

1.20.1-1.1.686

### Related Mods and their Versions

The latest versions of the required mods for MineColonies

### Current Behavior

My builder, instead of going 20 blocks more and going around the river on the bridge, chooses to swim across the river

### Expected Behavior

The builder will choose to walk over the bridge (if there is one) to get to your destination

### Reproduction Steps

1.Start building a building across the river (but to have a bridge or crossing)

### Logs

https://drive.google.com/drive/folders/1qEcXqNdFC24CcTMTgMmRjwA_0RPOYK4h?usp=sharing

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
It's the limitations of pathfinding, there is not a lot we can do. Make the bridge out of path blocks
