### ISSUE TITLE
Guards do not rally under active rallying banner

### ISSUE THREAD

**Issue by Corbi84** [ldtteam/minecolonies#10337]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.21

### MineColonies Version

1.1.724

### Structurize Version

1.0.752

### Related Mods and their Versions

1. NeoForge 21.1.66
2. BlockUI 1.0.192
3. DO 1.0.204

### Current Behavior

When activating the Rallying Banner the textbox confirms that x (currently 18 in my case) guards are supposed to be rallying near it. The guards instead ignore the rallying and keep patrolling the colony, even when standing right next to a guard tower/barracks to avoid range issues.

Everything else (tower selection, marking of hut blocks, text confirmations of rallying and returning to duty) works fine, the guards just don't react to it.

### Expected Behavior

Guards to come towards the player carrying the active rallying banner.

### Reproduction Steps

- Make rallying banner.
- Add one or more towers with guards in it.
- activate banner either with shift-click or via right-click and interface-button in the banner.
- wait

### Logs

relevant in this case?

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ZerasT** [comment]
Same problem. 
 
 Tested Ver. 
Minecraft : 1.21.1 
NeoForge : 21.1.65 & 21.1.71 
Launcher : Prism Launcher 8.4 
OS : Win 11 (Some apps trouble with win 11 so I mentioned) 

MineColonies : 1.1.688 & 1.1.700 & 1.1.726 
I tested several versions because I thought it might work on other versions. But in the end it didn't work. 

Structurie : 1.0.752
blockUI : 1.0.192
Domun : 1.0.204
Multipiston : 1.2.51
towntalk : 1.2.0

Used mod only MineColonies and its dependency

**Comment by Mikec78660** [comment]
I have has this as well. Once it did seem to actually work after not working for a long time. Guards suddenly started coming out of the woodwork at me. I had forgotten I had even rallied them at that point. But it hasn't worked since.

**Comment by Aeternelle** [comment]
I want to comment I also have the same issue, playing the Direwolf 1.21.1 Feed The Beast Modpack (v. 1.3.0) which contains the following Minecolonies Mod amongst other things. It seems to be the same version as the above commenters, just in the context of a modpack.

- Domum ornamentum 1.0.204-1.21.1-snapshot
- MineColonies 1.1.726-1.21.1-snapshot
- Towntalk 1.2.0
- Structurize 1.0.752-1.21.1-snapshot

**Comment by Akjosch** [comment]
What just worked for me is activating the banner, then shutting down the game and restarting. All of the sudden ... Guards!

- Minecraft 1.21.1, NeoForge 21.1.73
- Domum Ornamentum 1.0.24-1.21.1-snapshot
- Minecolonies 1.1.751-1.21.1-snapshot
- Structurize 1.0.754-1.21.1-snapshot

**Comment by TelliusNi** [comment]
I just tested Akjosch's method, and same outcome. Activated the banner, nothing happens. Shutdown and restart game, guards get their outline and rallied. Same snapshots and versions, including neoforge.

**Comment by Raycoms** [comment]
fix pushed
