### ISSUE TITLE
Lost Mesa City Tavern 3 is broken

### ISSUE THREAD

**Issue by puggan** [ldtteam/minecolonies#10336]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [ ] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20

### MineColonies Version

1.20.1-1.1.647-beta

### Structurize Version

1.20.1-1.0.742-RELEASE

### Current Behavior

After the building is finished, it complains that the top most roff block is missing, so can't upgrade it to the next level.
![image](https://github.com/user-attachments/assets/3ab26b32-fd97-4301-afd6-a73d8d78df9f)

### Expected Behavior

Roofblock to be counted as part of the building, so it no longer asks for repairs of a blocks that exists

### Reproduction Steps

1. build a Lost Mesa City Tavern 3
2. Try to upgrade it to level 4

### Logs

N/A

### Anything else?

My guess is that the roof-block is sticking out outside of the building frame, so it fails to count it.

Simular issue #7194

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
There is no next level, taverns only go to level 3 (as an aside, you should update minecolonies too - you're quite  a bit out of date!)

**Comment by Raycoms** [comment]
Also #5006 for schematic issues please
