### ISSUE TITLE
AI log upload

### ISSUE THREAD

**Issue by CurseMaster97** [ldtteam/minecolonies#10344]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.21

### MineColonies Version

1.1.707-1.121.1-snapshot

### Structurize Version

1.0.751-1.21.1-snapshot

### Logs

https://gist.github.com/b0370b133924db919d85e73b9349cb27.git

### Anything else?

My builder told me to upload my latest log and sent it to the aurthors

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
First best step would be to update minecolonies as it has probably been fixed =)
