### ISSUE TITLE
Food missing Foods tag

### ISSUE THREAD

**Issue by TheBedrockMaster** [ldtteam/minecolonies#10354]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player

### Minecraft Version

1.21

### MineColonies Version

1.1.727

### Structurize Version

1.0.752

### Current Behavior

Food items from the mod don't have the `c:foods` item tag.

### Expected Behavior

Food items from the mod should have the `c:foods` item tag.

### Reproduction Steps

Check the tags on food items from the mod.

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
What even is the `c:foods` tag? We add vanilla and forge representative tags where needed. If another mod adds some tag you will have to make a datapack to add our food in.

**Comment by TheBedrockMaster** [comment]
Sorry, this is for Neoforge which uses c: for tags

**Comment by Thodor12** [comment]
Alright, sounds good, I was unaware neoforge was using `c` as the namespace

**Comment by Raycoms** [comment]
c is the new common namespace
