### ISSUE TITLE
Guards not going to hospital when sick

### ISSUE THREAD

**Issue by cammy1o** [ldtteam/minecolonies#10358]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20

### MineColonies Version

1.20.1-.1.1.696

### Structurize Version

1.20.1-1.0.760

### Current Behavior

Guards will not go to the hospital, Specifically barracks guards.
![image](https://github.com/user-attachments/assets/6bbfc2e6-c67d-4c6c-b61e-1876f7172bd2)

They will not move from that spot, It's not just that spot tho, it happens with the other hut's too. When it first happened, I showed the same issue to Thodor who then broke the barrack's hut and slapped them a few times which then caused them to go straight to the hospital. However, 6 hours later, the same issue arose so i've created a bug ticket. I'm still in the server if anyone wants to come check it out :P

Another thing I would like to mention is that when they are given the cure to their illness, That they don't use it at all. 

Another thing I would like to mention is that the doctor doesn't come to any of the sick guards.

### Expected Behavior

Run to the hospital to get healed.

### Reproduction Steps

Join the multiplayer event server and teleport to me. Otherwise get the fortress style, or some other style, i'm not sure if it's just with the fortress style, But once you've got the fortress barracks, get a few guards that are sick and follow them around until they go to a barrack's hut and get stuck 🤔

### Logs

Why is this a requirement? Not everyone crashes..

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Corbi84** [comment]
One of the classic bugs, been around for a long time. Likely hard to reproduce, since sometimes they do go to the hospital. Sometimes they "go in increments", meaning leaving the squad and walk towards the hospital, turn back around to rejoin their barracks squad, leave the squad again to go a little closer to the hospital, rince and repeat. They might eventually reach the hospital.

For me giving them the cure manually has always worked (after a while).

Personally I have only seen this behaviour with barracks guards.

Edit: typo
