### ISSUE TITLE
Builders Hut

### ISSUE THREAD

**Issue by Senseless26** [ldtteam/minecolonies#10362]
## Description

The Builder doesnt take the Framed Wood. He gets it but he doesnt use ist for building. He´s stuck in the request and keeps requesting ist

**Comment by MotionlessTrain** [comment]
This is the issue page for minecolonies' wiki, not for the mod

**Comment by Thodor12** [comment]
Either you used the wrong materials and the output item doesn't match what he wants, or you were affected by #10404
