### ISSUE TITLE
how to turn off the halloween style

### ISSUE THREAD

**Issue by Emiliano122844** [ldtteam/minecolonies#10387]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [X] Multi Player

### Minecraft Version

1.20

### MineColonies Version

1.20.1-1.1.609-BETA

### Structurize Version

structurize-1.20.1-1.0.742-RELEASE

### Related Mods and their Versions

how to turn off the halloween style of the underworld skins from residents

### Current Behavior

how to turn off the halloween style of the underworld skins from residents

### Expected Behavior

how to turn off the halloween style of the underworld skins from residents

### Reproduction Steps

how to turn off the halloween style of the underworld skins from residents

### Logs

how to turn off the halloween style of the underworld skins from residents

### Anything else?

how to turn off the halloween style

### Footer

how to turn off the halloween style

**Comment by someaddons** [comment]
👻
