### ISSUE TITLE
TRANSLATION - START OF THE COLONY and tutorial

### ISSUE THREAD

**Issue by sukispring** [ldtteam/minecolonies#10381]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20

### MineColonies Version

1.20.1-1.1.697-snapshot

### Structurize Version

1.20.1-1.1.697-snapshot

### Related Mods and their Versions

-

### Current Behavior

I asked on discord why it wasn't translated into Spanish when you found an abandoned colony and where I could help to translate, since I understand English perfectly. I checked the wiki and saw that the translation to Spanish was at 100%. Then on discord they told me that it wasn't set to translate and that I should create an incident and that's what I do.

As I've been playing, I've realized that the tutorial that the settler gives you to play or when you set up your settlement isn't translated either.
![Captura de pantalla 2024-10-29 113004](https://github.com/user-attachments/assets/337d5364-cb7f-4f5d-90c0-b6a77d39ce06)
![Captura de pantalla 2024-10-29 113256](https://github.com/user-attachments/assets/11fdd66f-993a-4c9f-bca6-7c6c9a08dd08)
![Captura de pantalla 2024-10-29 113519](https://github.com/user-attachments/assets/4487143e-8c57-412c-bf6b-febbf736af85)
![Captura de pantalla 2024-10-29 115554](https://github.com/user-attachments/assets/99b7caa5-cf94-44f6-93c2-9de61d24172f)
![Captura de pantalla 2024-10-29 120835](https://github.com/user-attachments/assets/15e200f2-ee25-467d-8139-a85a05a563b7)
![image](https://github.com/user-attachments/assets/27966076-8502-49e9-9a30-5cbfe2403317)

### Expected Behavior

-

### Reproduction Steps

I would like the stories, the tutorial and the campsite to be content that we could translate. 
I would be happy to do it in Spanish. 

Thank you in advance.

### Logs

-

### Anything else?

--

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
The quests should be translatable though @uecasm  and maybe @Thodor12 for the wrong lang file being uploaded (pre merger)

**Comment by uecasm** [comment]
Quests, yes.  Stories, not yet 😛

**Comment by Thodor12** [comment]
Stories are fixed content, we should make them datagen an array of strings for translation purposes

**Comment by Raycoms** [comment]
No need to datagen them, they are already data driven. But I'm talking about quests not being translatable on crowdin apparently?

-------- Original Message --------

**Comment by Thodor12** [comment]
I guess the crowdin upload task has no dependency on mergeTranslations. Locally the file is filled properly with all quests.

**Comment by Thodor12** [comment]
Oh, we're not calling the upload at all :)

**Comment by Thodor12** [comment]
Some quests are uploaded, but it doesn't look like any of the tutorial ones are there.

![2024-10-31 13_04_59-en_us json - Minecolonies - Crowdin translation](https://github.com/user-attachments/assets/3d3aa247-4fbd-4ce2-9f60-59c1ce6174fc)

Edit: Nevermind, there are 7 full pages, the tutorial quests are translated as well. So it's more likely an issue in the code if they're not getting translated.

**Comment by Raycoms** [comment]
Probably the early ones when upload was still working

-------- Original Message --------

**Comment by Thodor12** [comment]
The upload is semi up-to-date, it's only ever since GH actions it's not uploading, which is an easy fix, but still the majority of translations should work.

**Comment by Thodor12** [comment]
@Raycoms The generated quests file do not use the translation values, instead they just use the raw values:
Quest file:
```json
{
  "name": "A roof over the head",
   "objectives": [
    {
      "type": "minecolonies:dialogue",
      "target": 0,
      "text": "Hi there! Your builder is looking neat! How about we let them build a Tavern so that your citizens don't have to sleep outside and are safe at night?",
}
```

Quest translations:
```json
  "minecolonies.quests.tutorial.tavern": "A roof over the head",
  "minecolonies.quests.tutorial.tavern.obj0": "Hi there! Your builder is looking neat! How about we let them build a Tavern so that your citizens don't have to sleep outside and are safe at night?",
```

**Comment by Raycoms** [comment]
Is that from the main resources or from the generated resources?

**Comment by Thodor12** [comment]
Main, the quests themselves are hardcoded and then generate translations for them, but those translations are never persisted back into the actual quest file.

We're probably going to have to make the quest templates come from datagen themselves if we want to fill the translation string + actual translation

**Comment by Raycoms** [comment]
It doesn't override the actual quest site, it's generated into the datagen folder quest files.

**Comment by Thodor12** [comment]
Hmm, they do look good in datagen, is it possible that main is taking precedence over datagen?

**Comment by Raycoms** [comment]
Shouldn't, are these strings all uploaded to crowdin?

**Comment by Thodor12** [comment]
File in the jar:
![2024-10-31 13_59_51-builder json - ts - Visual Studio Code](https://github.com/user-attachments/assets/a8e95778-4c86-49be-a0a8-1945380d9634)

Translation on Crowdin:
![2024-10-31 14_00_35-en_us json - Minecolonies - Crowdin translation](https://github.com/user-attachments/assets/06c964c5-7bdf-46f1-9520-5216d185abc4)

**Comment by Thodor12** [comment]
Could be possible what I stated on Discord, because crowdin was never rebuilding the translation files and using cached data it might've never actually generated?

**Comment by Thodor12** [comment]
@sukispring All translations (not just Spanish) are fixed in version 704. So at least the quests should start being translated now.

**Comment by Thodor12** [comment]
@sukispring You may also look on crowdin to translate any additional strings that have been newly uploaded.
Also Ray noticed there are faulty texts in other content, if you want/have time you may also look over any existing content to see if it's correct.

**Comment by Raycoms** [comment]
I'll close this and refer you to the feature request repo for the translation requests

**Comment by sukispring** [comment]
Lets goo! Thank you so much
