### ISSUE TITLE
жители поменяли скины на скины адских мобов

### ISSUE THREAD

**Issue by Emiliano122844** [ldtteam/minecolonies#10386]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20

### MineColonies Version

1.20.1-1.1.609-BETA

### Structurize Version

structurize-1.20.1-1.0.742-RELEASE

### Current Behavior

![2024-10-31_21 45 21](https://github.com/user-attachments/assets/675a70b3-3bfe-431c-8fbc-0dfb21b7a95d)
![2024-10-31_21 45 28](https://github.com/user-attachments/assets/282cf0ea-5ec7-425a-b81c-1c52eeadcf9d)

### Expected Behavior

жители поменяли скины на скины адских мобов, играал до этого все было нормально

### Reproduction Steps

к

### Logs

е

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
Please make bug reports in English.

**Comment by Thodor12** [comment]
For halloween every year it's intended that the skins change for a couple of days. Either wait or turn off holiday features.

**Comment by Emiliano122844** [comment]
how to disable them
