### ISSUE TITLE
AI log upload: A large number of 'Missing sound for event: minecolonies .child' messages are causing the game to freeze.

### ISSUE THREAD

**Issue by FireHeart1203** [ldtteam/minecolonies#10393]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.20

### MineColonies Version

1.20.1-1.1.708-snapshot

### Structurize Version

1.20.1-1.1.708-snapshot

### Logs

https://gist.github.com/FireHeart1203/c4c340613ce74a44008d31a6be46dfb8

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
That log definitely does not make anything freeze, you have something else freezing the world, not those couple of missing sounds.
