### ISSUE TITLE
Couriers are not working

### ISSUE THREAD

**Issue by Gerpuss** [ldtteam/minecolonies#10394]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20

### MineColonies Version

1.20.1-1.1.709

### Structurize Version

1.20.1-1.1.709

### Current Behavior

Hi, I was playing minecolonies version 1.1.709 this morning and probably ran into some kind of bug. I upgraded my only warehouse to level 4 (exactly like a MineColonies-style warehouse, with two storage floors and underground rooms for couriers), and shortly after that I used the sort button in the warehouse. After a few minutes, I noticed that all my 4 couriers were not working. Most of the time they stand in one place in the warehouse, only from time to time they leave the building, look around and return to their favorite place. I tried to move all the goods back to the lower floor, since some of them moved upstairs during sorting, I restarted the game and reloaded the save (several times), tried to suspend/cancel the work of the workers, fire and re-hire them. I have no other ideas what to try.
![2024-11-03_16 45 52](https://github.com/user-attachments/assets/9662cb66-7bc7-4496-9ae9-16e7516f8143)
![2024-11-03_16 47 08](https://github.com/user-attachments/assets/0e87553f-d7ec-46d4-8162-84aa0fad7c7c)

### Expected Behavior

Couriers should work, not stand still

### Reproduction Steps

Build A Warehouse > Build A Courier Booth > Hire A Courier

### Logs

https://drive.google.com/drive/folders/1qEcXqNdFC24CcTMTgMmRjwA_0RPOYK4h?usp=sharing

### Anything else?

I'm not sure, but it may affect the fact that I have 90 residents

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Gerpuss** [comment]
I want to add that for some reason the bug only works when building a warehouse in the style of "Minecolonias"

**Comment by Raycoms** [comment]
should be solved in latest
