### ISSUE TITLE
minecolonies-universal-1.10.2-0.8.1342 lumber jack ignores saplings

### ISSUE THREAD

**Issue by jasonsaffle13** [ldtteam/minecolonies#1039]
### Minecolonies version

minecolonies-universal-1.10.2-0.8.1342

### Expected behavior

lumber jack to replant saplings

### Actual behaviour

lumber jack ignores saplings most times worse with oak.

### Steps to reproduce the problem

build saw mill and upgrade to level2 or higher

**Comment by Raycoms** [comment]
How does he ignore them?
Where does he ignore them?

2017-05-21 21:21 GMT-03:00 jasonsaffle13 <notifications@github.com>:

**Comment by jasonsaffle13** [comment]
He leaves them on the ground around his saw mill, though he will most times replant spruce. If we put them into his inventory he will then replant them instead of ignoring them till the despawn.
[2017-05-21-4.log.gz](https://github.com/Minecolonies/minecolonies/files/1017486/2017-05-21-4.log.gz)

[fml-server-latest.txt](https://github.com/Minecolonies/minecolonies/files/1017489/fml-server-latest.txt)

the .gzz is from the time he was acting up. We added in Ender IO to have a way to charge the Gendustry scooperator, Tested it was running fine and then I logged off so the log.tx may not be much use

**Comment by Amadeus99** [comment]
I was using v1.10.2-0.8.1009 then updated to v1.10.2-0.8.1386 and now I'm having the same issue with the Lumberjack not picking up oak or spruce saplings.  The Lumberjack doesn't appear to pick up anything at all.  I only have oak and spruce trees planted, though.  Then I destroyed the Sawmill and tried a level 1 Sawmill, just in case, and still had the same problem.  I play on SMP.  I reverted to v1009 and the Lumberjack picks up saplings and apples and so on again.

**Comment by jasonsaffle13** [comment]
![2017-05-22_05 30 33](https://cloud.githubusercontent.com/assets/4934838/26301877/7d73feb0-3eb0-11e7-9223-78e9c1db6ec6.png)
![2017-05-22_05 30 51](https://cloud.githubusercontent.com/assets/4934838/26301880/7fcc8e3e-3eb0-11e7-961d-2300c2d6cac9.png)
![2017-05-22_05 31 07](https://cloud.githubusercontent.com/assets/4934838/26301885/83208fd6-3eb0-11e7-942e-6137b69acac2.png)

 We are using minecolonies-universal-1.10.2-0.8.1429 now and same issue.

**Comment by jasonsaffle13** [comment]
![2017-05-22_19 42 17](https://cloud.githubusercontent.com/assets/4934838/26332748/ea645f6c-3f26-11e7-869a-a456525d2cbb.png)

minecolonies-universal-1.10.2-0.8.1470 behavior unchanged.

**Comment by jasonsaffle13** [comment]
minecolonies-universal-1.10.2-0.8.1536
![2017-05-23_20 13 02](https://cloud.githubusercontent.com/assets/4934838/26383070/b0431124-3ffe-11e7-826d-2ae701aeb7e6.png)
 He's back to work!! Though some times he is invisible. Happens when he is hungry but working, You hit recall and seems like nothing happens then you  hear some one walking the door opens and closes I walked outside and a oak tree was being chopped by no one. Then he came zipping across the town to his saw mill walked out side and started chopping. Not a huge deal cause he is still working when i can not see him. Thanks for all the hard work!!

**Comment by jasonsaffle13** [comment]
On my phone and it will not let me edit last comment. I am using optifine and a large 256 texture pack. I am so used to visual glitches from that combo it may just be that. Not going to take time to look i to it unless it helps you amd your team.

**Comment by Boyownik** [comment]
I have the same problem, Lumberjack just afk near saplings and wait until they disappear (like he have order to pick them up, but he can't) and then he can cointinue his work.

**Comment by Raycoms** [comment]
Shouldn't happen anymore.
