### ISSUE TITLE
Citizen will clump by the residence block and stay there, in "Looking for Bed" mode.

### ISSUE THREAD

**Issue by Knaxia** [ldtteam/minecolonies#10405]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.21

### MineColonies Version

minecolonies-1.1.772-1.21.1-snapshot

### Structurize Version

structurize-1.0.754-1.21.1-snapshot

### Related Mods and their Versions

Neoforge 21.1.72
blockui-1.0.192-1.21.1-snapshot
domum_ornamentum-1.0.204-1.21.1-snapshot
jei-1.21.1-neoforge-19.21.0.247
journeymap-neoforge-1.21.1-6.0.0-beta.29
multipiston-1.2.51-1.21.1-snapshot
towntalk-1.2.0

### Current Behavior

At night, all citizen will head to their residence, but instead of going to bed, they will clump up to their residence block and stay there. Their state will be stuck at "FIND_BED" and there will also be no message that they are all tucked into bed. 

On the other hand, they do no seem to complain about the lack of sleep even after multiple days so it doesn't seem to affect their actual sleep.

### Expected Behavior

They will all go sleep in their bed after getting inside their home, and the tucked message will appear once they are all sleeping.

### Reproduction Steps

Have a colony with houses and residents assigned and wait for night. Doesn't matter if it's a normal residence or tavern, doesn't matter which house level or style either.

### Logs

None required.

### Anything else?

-The problem wasn't present using the November 1st version 1.1.759-1.21.1. The issue only happened after updating today.
-The schematic / style version doesn't matter (I use medieval oak, medieval spruce both variant and medieval dark oak), nor does the building level, also affects tavern.
-Removing bed and replacing them didn't work
-Restarting minecraft didn't work
-De-assigning and reassigning homes didn't work
-It has been reported by multiple people over discord after updating today

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by jhadred** [comment]
Also present in minecolonies-1.20.1-1.1.718-snapshot
Was not present in minecolonies-1.20.1-1.1.709-snapshot

Also saw colonists standing outside at night but didn't get a debug state to add

blockui-1.20.1-1.0.186-beta
domum_ornamentum-1.20.1-1.0.282-snapshot-universal
multipiston-1.20-1.2.43-RELEASE
structurize-1.20.1-1.0.760-snapshot
stylecolonies-1.10-1.20.1

**Comment by Raycoms** [comment]
Can you tell me with which style residences this is happening?

**Comment by Talyda** [comment]
Colonial, medieval dark oak, medieval oak, and alt oak too, medieval spruce
(I think we had four people all report it)

**Comment by Talyda** [comment]
Oh, affects the tavern too  (oops, Knaxia said that in the report already, sorry!)

**Comment by Raycoms** [comment]
fixed
