### ISSUE TITLE
Vanishing Flag Patterns for Editing Town Flag

### ISSUE THREAD

**Issue by Mijithemidge** [ldtteam/minecolonies#10401]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20

### MineColonies Version

1.1.760-1.21.1

### Structurize Version

1.0.754-1.21.1

### Related Mods and their Versions

Latest ATM10 version as of 11/3/2024, Neoforge 21.1.73

### Current Behavior

While creating a flag for my colony, scrolling down only leads to blank space. Scrolling back up shows that all the patterns that could be seen have also vanished. Only leaving the flag editing screen and reopening it could show the first page of patterns again. This also occurred on a clean version of Minecolonies with dependencies.

### Expected Behavior

Scrolling down to find more patterns, and scrolling up to see previous patterns, without having to close the editing window.

### Reproduction Steps

1. Go to a town hall (this problem was seen with my level 1)
2. Click Edit flag
3. Use whatever color for a background
4. Go to patterns (even the first works fine)
5. Scroll down to reveal no patterns, and that the patterns you scrolled past have vanished.

### Logs

Not sure how, it wasn't a crash.

### Anything else?

![image](https://github.com/user-attachments/assets/a2b76789-8c4d-4011-808a-7d161060a64e)
(Don't worry about the missing textures, that's Actually Addition's problem)
![image](https://github.com/user-attachments/assets/11da2d0e-c5f1-4442-9ad9-f65c88fd20a8)
![image](https://github.com/user-attachments/assets/85875389-da02-4c8a-b0b3-73bb5de49c27)

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Mijithemidge** [comment]
I typo'd! It is version 1.21 of minecraft!

**Comment by Talyda** [comment]
More examples here on patreon discord too:
https://discord.com/channels/472875599422291968/1300483967962710106

I tested with just Minecol etc, and some QoL mods (very minimal instance)

**Comment by Raycoms** [comment]
fixed
