### ISSUE TITLE
No Dialogue or Interaction Windows for NPCs

### ISSUE THREAD

**Issue by OracleMask** [ldtteam/minecolonies#10419]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20

### MineColonies Version

1.20.1-1.1.723 snapshot

### Structurize Version

1.20.1-1.0.742-release

### Current Behavior

Upon founding my colony and first citizen spawning in, discovered that I am not able to interact with them.  Right-clicking with empty hand triggered correct audio line, but no dialogue window ever appeared.  Shift-right-clicking does not bring up inventory window.  The npc has the quest indicator for the tutorial floating over his head and I cannot talk to him about it.

However, I placed the first builder hut down and he automatically took the job as normal.  He has no issues with block breaking or block placement.  However even when the red cogwheel appeared to show he needed an item I was unable to ask what the item was or check his requests.  I had to guess based on past experience with the mod when he wanted replacement tools or needed building materials.  Builder successfully constructed his hut, the tavern, a guard tower, and began work on a mine before I left the session.

All other initial citizens spawned in with the same issue - unable to trigger dialogue window or access npc inventory.  After the tavern was completed the visitors spawned in but no dialogue windows appeared for them either.  I cannot see their stats or hire them for my colony.  I also had one child spawn in and I cannot interact with them either.

### Expected Behavior

I expect to be able to interact with the npcs generated by the mod.

### Reproduction Steps

1. Generate a single-player world in a version slightly before 1.1.723 (i do not remember the exact number, somewhere between 720 and 722)
2. Update to version 1.1.723
3. Start a colony.

### Logs

https://gist.github.com/OracleMask/24579a42579651182abb72c8a8545b2b

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by OracleMask** [comment]
Have since discovered that removing Critters and Companions mod from modpack has corrected this.  Said mod got updated to its version 2.2.0 a few days ago and previous versions did not cause issue with Minecolonies.

**Comment by Raycoms** [comment]
Please report there.
