### ISSUE TITLE
Colonist Stuck, spinning on Flooded Field blocks

### ISSUE THREAD

**Issue by timbrown81** [ldtteam/minecolonies#10414]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20

### MineColonies Version

1.1.718 snapshot

### Structurize Version

1.0.760 snapshot

### Related Mods and their Versions

Official Event Modpack (Raid server)

### Current Behavior

After most recent patch I noticed colonists becoming stuck and spinning on flooded fields (MC rice crop fields).  They remain stuck until recalled.

### Expected Behavior

Not get stuck

### Reproduction Steps

Just wait until citizen paths through rice field.

### Logs

na

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
should be fixed in latest it seems
