### ISSUE TITLE
When hiring mercenaries crash

### ISSUE THREAD

**Issue by Player-Frisk** [ldtteam/minecolonies#10412]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.20

### MineColonies Version

minecolonies-1.20.1-1.1.719-snapshot

### Structurize Version

structurize-1.20.1-1.0.742-RELEASE

### Related Mods and their Versions

multipiston-1.20-1.2.43-RELEASE
domum_ornamentum-1.20.1-1.0.186-RELEASE-universal
blockui-1.20.1-1.0.156-RELEASE
towntalk-1.20.1-1.1.0

### Reproduction Steps

Hire mercenaries

### Logs

https://mclo.gs/J7LG6fu

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
fix pushed
