### ISSUE TITLE
Town hall crash

### ISSUE THREAD

**Issue by Gaz492** [ldtteam/minecolonies#10417]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.21

### MineColonies Version

1.1.774

### Structurize Version

1.0.754

### Current Behavior

If you reinstate a settlement then click on sign and found colony the game will crash.

### Expected Behavior

The game not to crash after clicking Sign and found colony

### Reproduction Steps

1. Find abandoned settlement
2. Open the town hall
3. Click on Reinstate button
4. Click on sign and found colony button
5. Crash

### Logs

https://pste.me/@jHN5B_i3TDY & https://pste.me/@5PcytE9Oib8

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.
[](https://github.com/FTBTeam/FTB-Modpack-Issues/issues/6109)

**Comment by Nightenom** [comment]
Report to or remove moonrise, in their code it looks like intentional change
https://github.com/Tuinity/Moonrise/blob/mc/1.21.1/src/main/java/ca/spottedleaf/moonrise/mixin/chunk_system/ChunkHolderMixin.java#L185

**Comment by someaddons** [comment]
not a mineoclonies bug
