### ISSUE TITLE
upgrade wall 

### ISSUE THREAD

**Issue by unicon04** [ldtteam/minecolonies#10426]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [X] Multi Player

### Minecraft Version

1.20

### MineColonies Version

1.20.1-1.1.708

### Structurize Version

1.20.1 - 1.0.742

### Current Behavior

hey 
i build a few wall, tower, and one gate lvl 1 and i can't lvl up the decoration 
the problem comes from the decoration controller
when we finished putting it at lvl 1 it does not display either upgrade or repair

### Expected Behavior

want to upgrade decorations

### Reproduction Steps

lean on the decoration controller so that it considers the wall as a structure like other buildings

### Logs

idk

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
This has been fixed in 1.1.724

You need to break the decoration controllers after updating, and place the decoration back at the same place. The builder should be done very quickly with building it, as almost everything is already at the correct place. The decoration controller the builder placed back should allow for upgrading it
