### ISSUE TITLE
In 1.21.1, plate armor is invisible on armor stands

### ISSUE THREAD

**Issue by Shadizar** [ldtteam/minecolonies#10428]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [X] Multi Player

### Minecraft Version

1.21

### MineColonies Version

1.1.776

### Structurize Version

1.0.754

### Current Behavior

Plate armor is invisible on armor stands (even in wide open spaces unlike the screenshot). All other armors from vanilla/mods show fine.
![image](https://github.com/user-attachments/assets/69eea138-cf0f-4234-b055-b3e5866dbac7)

### Expected Behavior

non invis

### Reproduction Steps

Put it on the stand
look at it

### Logs

na

### Anything else?

It's just minecol and Ars/BoP (for our schematic server)
No visual or armor or armor stand mods present.

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by someaddons** [comment]
plot armor for citizens?!

**Comment by Shadizar** [comment]
The Emperor's New Armor
It's there, just trust us

**Comment by Raycoms** [comment]
fixed
