### ISSUE TITLE
Ticking entity

### ISSUE THREAD

**Issue by ncottrill** [ldtteam/minecolonies#10421]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.21

### MineColonies Version

1.1.760-1.21.1-snapshot

### Structurize Version

structurize-1.0.754-1.21.1-snapshot

### Related Mods and their Versions

NeoForge *.73
Domum 1.0.204
Blockui 1.0.192
Multipiston

### Current Behavior

Citizen ticking - see log https://mclo.gs/VrWSLBW starting line 4647
Associated colony unable to load some schematics.

![image](https://github.com/user-attachments/assets/c85035cb-2e04-42a6-99a9-7f2b88406642)

### Expected Behavior

I expect Minecolonies to not have a ticking entity.
And, load schematics when requested.

### Reproduction Steps

Start multiplayer ATM 10 server.
Have an existing colony load. Sometimes on load an entity will tick.
Sometimes a server reboot fixes the problem.

### Logs

Link provided above

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
This has been fixed already in version 1.1.776
You need to update to the latest version, break the decoration controller, and place the decoration back on exactly the same spot (such that the builder can place a new decoration controller back). Then it is upgradable again

**Comment by ncottrill** [comment]
> This has been fixed already in version 1.1.776 You need to update to the latest version, break the decoration controller, and place the decoration back on exactly the same spot (such that the builder can place a new decoration controller back). Then it is upgradable again

The primary bug is/was a ticking entity. Is this fixed?

**Comment by MotionlessTrain** [comment]
It is really confusing when you are reporting two unrelated bugs in one report

The AI issue seems to indicate that the hut block of the nether miner is missing its block entity for some reason

You also probably want to have ticking entities in minecolonies (as you seem to be expecting no ticking entities for some reason)
A ticking entity is an entity that can do things, like mobs, citizens, villagers, players, etc. The only entities not ticking are certain block entities (if they are actual entities), and item frames, armour stands and paintings (as they are simply holding items)

**Comment by ncottrill** [comment]
I sent this link to Sam earlier (prior to posting here) and he said report it here on Github because it was a coding fix that needs to happen.

**Comment by ncottrill** [comment]
Sorry for posting two things at once. I won't in the future.

**Comment by uecasm** [comment]
> You also probably want to have ticking entities in minecolonies (as you seem to be expecting no ticking entities for some reason)
A ticking entity is an entity that can do things, like mobs, citizens, villagers, players, etc. The only entities not ticking are certain block entities (if they are actual entities), and item frames, armour stands and paintings (as they are simply holding items)

Since English is super confusing about it, in this particular usage of "ticking entity" in the error message, "ticking" is acting as a verb and not an adjective.  i.e. it's saying "when ticking this particular entity, an error occurred", and is not saying that a entity that ticks is inherently a bad thing.

**Comment by ncottrill** [comment]
In this case, a Minecolonies ai's tickratestate was erroring out. I should have been more explicit, I guess. I mentioned the error output line (or the start of them) in the ticket. 

I'm fine with the discussion, btw. I was being fast and loose with my words and being lazy. I figured the error log would tell Ray / whomever looked into this far more than my English gibberish :)
