### ISSUE TITLE
Banners do not hold their patterns upon being placed and broken

### ISSUE THREAD

**Issue by cocoa005** [ldtteam/minecolonies#10420]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [X] Multi Player

### Minecraft Version

1.21

### MineColonies Version

1.1.774

### Structurize Version

1.0.754

### Current Behavior

Banners, even vanilla banners, with any sort of patterns on them do not hold those patterns upon being placed and then broken. Tested on an instance with just Minecolonies and its dependencies.

![Screenshot 1](https://github.com/user-attachments/assets/ae7e3c98-9132-4ca0-96c7-a5a0916149bb)
![Screenshot 2](https://github.com/user-attachments/assets/668a79d0-079b-499c-be45-d7c226a0c751)
![Screenshot 3](https://github.com/user-attachments/assets/6824678f-19ca-4422-a188-6a77b53f1aad)
![Screenshot 4](https://github.com/user-attachments/assets/8d104cad-756d-4267-89b2-b2ae8d12ea6f)
![Screenshot 5](https://github.com/user-attachments/assets/07b38bd5-3f91-4908-b730-12356cb413af)

### Expected Behavior

The banners should hold their patterns even after being broken.

### Reproduction Steps

1. Get a banner with any sort of patterns on it
2. Place the banner
3. Break the banner
4. Be dismayed at the loss of all the patterns from the banner

### Logs

https://mclo.gs/DuhsE4l

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
We don't change anything with vanilla banners, are you sure you also checked without minecolonies if that's not a neo or so bug?

**Comment by cocoa005** [comment]
Thank you for your response. Yes, I have tried with Minecolonies disabled and the issue simply does not happen then on the NeoForge instance. It only happens when Minecolonies is enabled.
