### ISSUE TITLE
Citizens being added/removed from teams causes server disconnect.

### ISSUE THREAD

**Issue by CloWnicide** [ldtteam/minecolonies#10425]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.21

### MineColonies Version

1.1.776

### Structurize Version

1.0.754

### Related Mods and their Versions

Neoforge: 21.1.74
BlockUI: 1.0.192
Domum: 1.0.204

### Current Behavior

Just playing the game and will be disconnected at random times with no actual indication as to why.

### Expected Behavior

Not to crash to server list

### Reproduction Steps

Play the game for any amount of time and wait for d/c

### Logs

https://gist.github.com/CloWnicide/9f7d623c25f68133b2c2bc938f73f7b8

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Could we get the server log too?

**Comment by CloWnicide** [comment]
https://gist.github.com/CloWnicide/a615980215b26381ab9d77c9aa5eb169

**Comment by Raycoms** [comment]
Hmm, but this one has no disconnect

**Comment by pietro-lopes** [comment]
Lots of people on ATM 10 server having this problem too.

**Comment by Mijithemidge** [comment]
https://gist.github.com/Mijithemidge/bd3e640f84a1f6ad999b92e27d942c2d I did send this crash report to ATM10's team, and they said it is on MineColony's end. However, I am playing in a single player world, not multiplayer, and it *still* crashes me to the server selection. It seems to happen a lot more when I am trying to find good placement for new buildings. A programmer friend told me it seems to have something to do with a scoreboard.

**Comment by Mijithemidge** [comment]
Okay, so unexpected update: I went and loaded right back into my single player world, and got right back to what I was doing; finding placement for the composter's hut. Except the moment I swung the wand, BAM, the whole thing crashed.
https://gist.github.com/Mijithemidge/c5cab990fb88c1d1c6a7c001be3cd043

**Comment by Raycoms** [comment]
Would you be able to binary search to find out which mod interaction could be causing this?

**Comment by Mijithemidge** [comment]
I'm not sure. It only really started happening to me when I got to mid-tier minecolonies, all level 2 and some 3 buildings, and that took days to get to. I am not the best at Minecraft bug testing, I'm afraid.

**Comment by CloWnicide** [comment]
Seems an update to ATM10 pack using Minecolonies ver. 1.1.787 has fixed the disconnect issue, although running into another issue were citizens have become lobotomized and don't move at all.

**Comment by Talyda** [comment]
> Seems an update to ATM10 pack using Minecolonies ver. 1.1.787 has fixed the disconnect issue, although running into another issue were citizens have become lobotomized and don't move at all.

Update minecolonies more
