### ISSUE TITLE
Ladder dancies

### ISSUE THREAD

**Issue by Estyria** [ldtteam/minecolonies#10435]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20

### MineColonies Version

1.20.1-1.1.723

### Structurize Version

1.20.1-1.1.760

### Related Mods and their Versions

Raid comp server

### Current Behavior

Look I get that "Spin me right round" is a fantastic song, but ALL the colonists trying to recreate the music video on the ladders is a bit much. 

More seriously, lol, the colonists get stuck on ladders dancing and bobbing and spinning in place. It's been an issue across all workers and guards. While they may eventually finish ascending or descending, it can take the entire minecraft day (or longer) and cause critical tasks to go undone.

### Expected Behavior

Path properly up and down ladders without trying to groove to the music

### Reproduction Steps

Just have ladders in high traffic areas. You'll see.

### Logs

https://gist.github.com/Estyria/f35e0ebb182e9a28f08ee61294381753

### Anything else?

Ray told me to

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
O removed all the ladders in my barracks, cos guards were just spinning on the ladders, instead of going to hospital to get cured

**Comment by OracleMask** [comment]
Visitors also get stuck on ladders!  I tried replacing ladders with scaffolding and all NPCs were bouncing on those as well.  The only thing that they didn't get stuck on was vines.

Not sure if related but I think it is since it started happening at the same time: colonists also keep trying to jump through doors.

Because doors are not 3 blocks tall they can't get through, and then get stuck in front of or next to a door and jumping uselessly.

**Comment by Estyria** [comment]
^ Have encountered ALL of those as well.

**Comment by zen-crab** [comment]
This happens a lot in the fortress pack. The ladders are often missing the last rung, which causes citizens to get stuck. Citizens also have a tendency to move laterally on ladders and fall off if their destination isn't directly above them.
