### ISSUE TITLE
builder wont build when there are path blocks in his hut

### ISSUE THREAD

**Issue by krjencik** [ldtteam/minecolonies#10432]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.21

### MineColonies Version

minecolonies-1.1.780-1.21.1-snapshot

### Structurize Version

structurize-1.0.754-1.21.1-snapshot

### Related Mods and their Versions

not sure... 
neo forge version: 21.1.77 for minecraft 1.21.1
towntalk-1.2.0 , multipiston-1.2.51-1.21.1-snapshot , blockui-1.0.192-1.21.1-snapshot , 
domum_ornamentum-1.0.204-1.21.1-snapshot

### Current Behavior

When there are path blocks in the hut, builder wont build. If the path blocks are manually replaced with regular dirt, issue is solved.

### Expected Behavior

The builder works even when the path blocks are in.

### Reproduction Steps

1.run the game (enter a world) 2. build builders hut. 3. try to build something else.

### Logs

https://gist.github.com/krjencik/689ed93e24cb2c9da0d2d93029160ff3

### Anything else?

hope the log isnt too long... 

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
Just gonna add, this is not an isolated report, there was quite a few people over the past couple of days. If the ground in front of the builder hutblock is a dirt/grass path, the builder seemingly can not reach? maybe? their hutblock to start work.

**Comment by MotionlessTrain** [comment]
This has also be found in a sawmill, in one of the styles. The carpenter would not craft anything because the hut block has path blocks on all sides

**Comment by Talyda** [comment]
I was trying to get confirmation for racks too, (in warehouse maybe?) if there was path blocks around them - have you seen anything about that Train? I'm not sure why I thought it might be related.

**Comment by MotionlessTrain** [comment]
I have not, but that may explain some of the courier problems if there is a warehouse with path blocks

**Comment by NepyNepy** [comment]
Found a new pathing issue regarding Dark Oak Medieval Builder's hut being leveled up from 1 -> 2. There is a dark oak stair directly to the left of the "builders hut" block that the builder will get stuck on. It can be fixed by removing this block, but the builder placed a new stair block down and got blocked again. - Posting comment to issue by advice of @Shindria on MineColonies discord Repro of issue for me at least is 2/2
![mcpathing](https://github.com/user-attachments/assets/067799da-1ce7-42fc-9c69-5448e89110d1)
