### ISSUE TITLE
Game Crash when opening Restaurant Menu

### ISSUE THREAD

**Issue by LittleTealeaf** [ldtteam/minecolonies#10443]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.21

### MineColonies Version

1.1.789-1.21.1-snapshot.jar

### Structurize Version

1.0.754-1.21.1-snapshot.jar

### Related Mods and their Versions

blockui-1.0.192-1.21.1.snapshot.jar (This appears to be what's causing the crash in the logs)

### Current Behavior

Logged into my world after new update. Needed to set the restaurant menu since it became opt-in. Every time I try to open it, the game completely crashes

### Expected Behavior

I expect the game to not crash so my citizens can be well fed :)

### Reproduction Steps

Open world
Create restaurant (Level 5)
Try clicking on food tab

### Logs

https://gist.github.com/LittleTealeaf/abf009b9d91f18ffaf75d4d95bf0b1b8

### Anything else?

Snipped from logs that appears to be the issue:

> [13Nov2024 08:35:11.413] [Render thread/ERROR][com.ldtteam.blockui.mod.Log/]: There is no factory method for label
> [13Nov2024 08:35:11.413] [Render thread/ERROR][com.ldtteam.blockui.mod.Log/]: There is no factory method for label
> [13Nov2024 08:35:11.436] [Render thread/ERROR][com.ldtteam.blockui.mod.Log/]: There is no factory method for label
> [13Nov2024 08:35:11.436] [Render thread/ERROR][com.ldtteam.blockui.mod.Log/]: There is no factory method for buttonimage
> [13Nov2024 08:35:11.549] [Render thread/ERROR][net.minecraft.client.Minecraft/FATAL]: Reported exception thrown!

Related to blockui, but seems to be something with whatever changed with the food tab

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
fixed
