### ISSUE TITLE
unable to access certain huts

### ISSUE THREAD

**Issue by LokisArmy2011** [ldtteam/minecolonies#10446]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20

### MineColonies Version

1.20.1-1.1.730

### Structurize Version

1.20.1-1.0.760

### Related Mods and their Versions

1. Forge Version: 47.3.0
2. BlockUI: 1.20.1-1.0.186
3. Domum Ornamentum: 1.20.1-1.0.282
4. Multi Piston: 1.20-1.2.43-RELEASE
5. Better with Minecolonies: 1.20-1.19.19
6. Tweaks addon for Minecolonies: 1.20.1-2.37
7. Compatibility addon for Minecolonies: 1.20.1-2.44
8. Minecolonies Curios Compat: 1.0.0
9. Let's Do addon for Minecolonies: 1.20.1-1.6

### Current Behavior

When placing the Apiary Hut, Bakery Hut, Composter's Hut, Cookery Hut, Dyer's Hut, Flower Shop Hut, Forester's Hut, Glassblower's Hut, Restaurant Hut, Smeltery Hut, and Stone Smeltery Hut then trying to interact with said hut it says, "This block is missing its respective building, try restarting or loading a backup!" I try restarting and reloading the world and it does not help.

### Expected Behavior

When placing the Apiary Hut, Bakery Hut, Composter's Hut, Cookery Hut, Dyer's Hut, Flower Shop Hut, Forester's Hut, Glassblower's Hut, Restaurant Hut, Smeltery Hut, and Stone Smeltery Hut then trying to interact with said hut. It should open the huts GUI.

### Reproduction Steps

1. Update Minecolonies to latest version
2. load world
3. get a build tool and place a Apiary Hut, Bakery Hut, Composter's Hut, Cookery Hut, Dyer's Hut, Flower Shop Hut, Forester's Hut, Glassblower's Hut, Restaurant Hut, Smeltery Hut, or Stone Smeltery Hut.
4. then try to access the huts GUI

### Logs

https://pastebin.com/XEkwcigN

### Anything else?

I do play the Minecolonies mod with a long list of other mods but I had no problem with the other mods before I updated Minecolonies. I also tried a world with only Minecolonies and it still does the same thing.

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
[23:35:54] [modloading-worker-0/WARN]: | Minecolonies has detected an addon mod that alters Minecolonies core code recklessly: 'Tweaks/Compatibility addon for Minecolonies'. |
[23:35:54] [modloading-worker-0/WARN]: |          Please report any bugs or issues you find directly to the authors of this addon, as the Official Minecolonies Team          |
[23:35:54] [modloading-worker-0/WARN]: |               will not be able to provide you any support with potential issues that will arise when using this addon.               |
[23:35:54] [modloading-worker-0/WARN]: |                                                                                                                                      |
[23:35:54] [modloading-worker-0/WARN]:

**Comment by Thodor12** [comment]
Meaning: Uninstall tweaks/compatibility addon for Minecolonies for support.
