### ISSUE TITLE
citizen request system issue

### ISSUE THREAD

**Issue by memeclone** [ldtteam/minecolonies#10442]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20

### MineColonies Version

1.20.1-1.1.723

### Structurize Version

1.20.1-1.0.760

### Related Mods and their Versions

1. forge: 47.3.11
2. using official minecolonies special events pack version 1.8

### Current Behavior

video shows what happened
https://github.com/user-attachments/assets/a4396614-7986-4fc1-bf35-d7b7cc5defcc

looks like a request system issue
Before the 4th raid competition week take place at 11/10, everything work properly
after 4th raid competition week while kept developing the colony normally, the request system start become shattered
citizen would normally placed there request, but the open requests page would shows a pure blank, and while open the clipboard, it crash, while trying to request item from postbox, nothing happened.

### Expected Behavior

it shall be normally processing since there's more colony that is well developed (200+ citizen with full constructed) without having this issue

### Reproduction Steps

X

### Logs

https://pastebin.com/uq5DZyua

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
I did a request system reset in your colony, seems you had a corrupted request somewhere in there. Please re-open when it appears again.

**Comment by memeclone** [comment]
sorry it happened again

**Comment by memeclone** [comment]
sorry, it happened again
