### ISSUE TITLE
Netherminer AI statemachine error

### ISSUE THREAD

**Issue by ncottrill** [ldtteam/minecolonies#10458]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.21

### MineColonies Version

1.1.792

### Structurize Version

1.0.754

### Related Mods and their Versions

Neoforge 21.1.77

### Current Behavior

Netherminer is being paused over and over due to AI state machine error.
[netherminer issues.txt](https://github.com/user-attachments/files/17789629/netherminer.issues.txt)

### Expected Behavior

Netherminer should function.

### Reproduction Steps

Just have a netherminer try to go to work. This one is level 3 Oasis style (lava boat) netherminer.

### Logs

Provided above

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ncottrill** [comment]
I updated the nether miner to Oasis Style level 4 and it still bugs out and the NPC doesn't work.

**Comment by Morcalvin** [comment]
I'm having the same problem with a fairytale level 2 nether mine on Minecraft 1.20.1

Logs https://gist.github.com/Morcalvin/9921a67a88c0c9e5c1c99b206214cc3b
