### ISSUE TITLE
Cook is ordering all foods over and over again

### ISSUE THREAD

**Issue by kezmodius** [ldtteam/minecolonies#10455]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20

### MineColonies Version

minecolonies-1.20.1-1.1.733-snapshot

### Structurize Version

structurize-1.20.1-1.0.742-RELEASE

### Related Mods and their Versions

Forge 47.3.0

### Current Behavior

![2024-11-16_18 53 48](https://github.com/user-attachments/assets/9a3ac474-5d1a-4a03-9d56-e35439a3db55)
![2024-11-16_18 54 13](https://github.com/user-attachments/assets/43c67673-5533-4791-a1b7-23f6b6e27115)
Cook is constantly ordering all the foods on the menu list until the racks are overflowing.
Colony only has 60 population.
Earlier (in this group colony) players had set too many foods.
![2024-11-16_15 03 01](https://github.com/user-attachments/assets/11a8acb0-796f-4c94-891e-d9ac5db92ce8)
I didn't take a screenshot but the cook was asking player for every meal there selected, even though there were multiple stacks of all the foods already in the racks. I reduced the food choice to the first s/shot above. The couriers picked up all the food no longer on the menu. Cook then wanted to fill the rack with these choices.

### Expected Behavior

Cook maintains a small stock for a small population.

### Reproduction Steps

Level 3 restaurant
60 pop

### Logs

Don't have one

### Anything else?

Can give more screenshots, logs, details if required

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
A level 3 restaurant wants to keep 6 stacks of each food in the menu on hand.  Since iirc food stacks to 64, you're still a long way below that.  But for 4 menu items that should easily fit in a single rack, and a level 3 restaurant should have more than enough space.

**Comment by Shadizar** [comment]
Should that be reduced now that there's a multi dish menu? 6 stacks per dish seems like far, far too much food, no?

**Comment by LittleTealeaf** [comment]
I've also noticed (I can double check / watch for verification) that every so often he'll request a pickup, which removes half of them and keeps the couriers in an endless loop of taking things to and from the restaurant

**Comment by noobielord** [comment]
I just checked if my requests would stop at 6 stacks, but he keeps requesting. Testing it with just baked potatoes and he's up to 4k in storage and still asking for more. With just baked potatoes on the menu and 1 min stock. Tested with other foods including some minecolonies with similar results.

**Comment by Raycoms** [comment]
64 min stock is 64 stacks.
Menu shouldn't be picked up though by couriers. And it's building level x2 min stock stacks.

-------- Original Message --------

**Comment by noobielord** [comment]
Misspoke have it set at 1 min stack not 64.

**Comment by Talyda** [comment]
> Should that be reduced now that there's a multi dish menu? 6 stacks per dish seems like far, far too much food, no?

Have to agree with that! 6 stacks of each food for a level 3 restaurant seems way too much food if we now need to keep a variety of foods to keep them happy with the new diversity stuff. 6 stacks **total** maybe, but not per dish. Or maybe 1 stack per dish per building level? (though that honestly sounds like too much too!)

**Comment by kezmodius** [comment]
It's not a full rack issue, the restaurant has enough space for the minimal menu I set. When there were 11 items on the menu though? That would have been close to overflow. 
I was troubleshooting the food issue originally because 1000s of baked potatoes had appeared in the warehouse and no-one knew why. I had assumed a newish player had set a min stock of potatoes at the restaurant, but I now think it was just having baked potatoes on the menu.

**Comment by kezmodius** [comment]
Oh, oops, I also wanted to comment that the stats showed 12 meals served in the last week, so really didn't need 6 stacks per dish. Maybe a balance is needed between restaurant level and actual population?
