### ISSUE TITLE
Come foods unable to be made by chef and baker

### ISSUE THREAD

**Issue by sirStroam** [ldtteam/minecolonies#10450]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [X] Multi Player

### Minecraft Version

1.20

### MineColonies Version

1.1.691-snapshot

### Structurize Version

1.0.742-RELEASE

### Current Behavior

Some foods such as cheesecake and pizza can't be made by the chef and baker

### Expected Behavior

At least one or the other to be able to make it

### Reproduction Steps

Try adding the recipe to either

### Logs

NA

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
Some recipes are only available at the cookery level 4 or 5

JEI should show that, if that is the case

**Comment by Liam-Selleslagh** [comment]
Minecolonies version 1.20.1 -1.1.733 snapshot
Structurize version 1.20.1 - 1.0.742 Release

Plain cheesecake can be crafted by players but not by colonists
the recepe cannot be taught to any colonist either
