### ISSUE TITLE
Food update Part 2 Couriers stealing food from restaurant and shenanigans

### ISSUE THREAD

**Issue by Estyria** [ldtteam/minecolonies#10464]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20

### MineColonies Version

Raid comp

### Structurize Version

Raid comp

### Related Mods and their Versions

Raid comp

### Current Behavior

Ok, I have some minimum stocks set in the restaurant from before the food update, but only for 2 stacks. Imagine my surprise when I found the cookery hoarding 14 stacks of stuffed pita and not delivering it to the restaurant. For only working on request, seems weird, right? So I took the stuffed pita and put it in the restaurant racks. 

I discovered a couple hours later that the couriers had absconded to the warehouse with almost all the stuffed pita again. Along with most everything else the restaurant *should* have had in stock. Couriers are not supposed to take food OUT of the warehouse, right?

I've seen this behavior with non-food items as well. A request is made, the item is made, but it is never delivered. The request is not fulfilled... so the crafter just makes more, and more, and more! Until next thing you know you've got about a thousand stuffed pita, or nearly 500 iron gates... Either in the hut of the crafter that made them, or sitting in the warehouse.

### Expected Behavior

Things get delivered to their destination and then stay there.

### Reproduction Steps

Just pay very close attention to your cookery and it should become apparent they are not working as intended. Hopefully you catch it *before* you have nearly a thousand of one food item....

### Logs

Raidcomp

### Anything else?

Also being reported on 1.21 that couriers are stealing food from the restaurant. Will try to get that individual to comment as well with their experience.

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Mijithemidge** [comment]
I have been having the same problem on my ATM10 single player world. My cookery is level 1, and restaurant and courier/warehouse are level 2. I was wondering how my small colony was burning through so many baked potatoes until I found a whole stash of them in the warehouse! I even crossed paths with the courier while trying to redeliver food after dropping some off, only to find that that courier had the food I had just dropped off!

**Comment by kezmodius** [comment]
From my observation, it seems like the cook requests a bunch of food, a quarter stack at a time. Once the food is in the restaurant the cook then asks for a pick up and it all goes back to the warehouse. They then order more food, which maybe is made by the chef, maybe comes from the WH, then the cycle repeats. The couriers are all caught up doing these tasks instead of delivering to builders.

**Comment by ncottrill** [comment]
The restaurant - whether it has minimums or not - just keeps ordering whatever food is on the menu. Then, their stacks get full and the couriers put it in the warehouse. The food is never got back out of the warehouse.

I have this same problem in Minecraft v.1.21.1 version of Minecolonies v. 1.1.802

**Comment by ncottrill** [comment]
Kezmodius and Mijithemidge - put your thumbs up on the original github issue (above) so this can get some visible attention from devs. That's what they ask for anyway, in the github issue. :D thank you! We want this fixed, eh?
