### ISSUE TITLE
Translation Key Typo

### ISSUE THREAD

**Issue by momo-i2** [ldtteam/minecolonies#10460]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.21

### MineColonies Version

1.1.797

### Structurize Version

1.0.754

### Current Behavior

![image](https://github.com/user-attachments/assets/3d90a31b-7cd6-40fb-880f-9ec87c4dddee)

### Expected Behavior

Translated strings are displayed.

### Reproduction Steps

Talking to Citizens

### Logs

no logs

### Anything else?

Not Typo, but please do something about the fact that no matter how many times I translate the following 5 keys, they always revert to being untranslated at some point.
1. com.minecolonies.alchemyquestpotion.lore
2. com.minecolonies.alchemyquestpotion.name
3. com.minecolonies.coremod.research.tags.other
4. com.minecolonies.coremod.research.limit.cost
5. com.minecolonies.coremod.gui.workerhuts.recipe.domum

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
fixed
