### ISSUE TITLE
minecolonies this block is missing its respective building

### ISSUE THREAD

**Issue by mass764** [ldtteam/minecolonies#10467]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20

### MineColonies Version

1.1.628beta.jar

### Structurize Version

1.0.689-RELEASE

### Related Mods and their Versions

forge- 43.3.5

### Current Behavior

im port forwarding a server and when i close the server and start it back up it makes all the buildings break and gives me this message "minecolonies this block is missing its respective building"

### Expected Behavior

i feel like its not meant to give this message cause in single player i've never had this issue.

### Reproduction Steps

first delete existing buildings and remake the colony next replace the buildings where they were and turn off the server once restarted they should break again

### Logs

idk how ;-;

### Anything else?

ive seen others with similar issues but no fixes

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Estyria** [comment]
First and foremost, that's an old version of the mod, and you should definitely update, as we are not having this issue on latest. Second, make sure you do NOT have either tweaks or compatibility for minecolonies installed as they can do exactly this. Third, it can take a couple of minutes for hut blocks to load in if there are lag issues, but no more than five.

**Comment by mass764** [comment]
im on minecraft 1.19.2 tho will the newer version even work if i use it?

**Comment by Raycoms** [comment]
This is sth that can happen when servers crash at some moment and some server data is lost etc. Only thing that can be done is remove the hut block if it doesn't load in 1-2 minutes and replacing it unfortunately.

**Comment by mass764** [comment]
ah i see so it just kinda doesnt work for the older version also
![image_2024-11-19_134013743](https://github.com/user-attachments/assets/644b304e-02ca-47ae-9d2d-20514816dec2)

![image_2024-11-19_134031973](https://github.com/user-attachments/assets/2e021a00-4cb3-42a7-8b41-fd7d048b5656)
 are these mods the issue?

**Comment by Estyria** [comment]
Final point.... don't say you're on 1.20 if you're not on 1.20. 1.19.2 is no longer supported.

**Comment by mass764** [comment]
idk it wasn't supported anymore my bad i just didnt see an option and couldnt find any info on this anywhere

**Comment by mass764** [comment]
well if nothing can be done guess im out of luck thank you for lookin at least
