### ISSUE TITLE
Cookery crashes client when opening crafting recipes menu

### ISSUE THREAD

**Issue by Droseran** [ldtteam/minecolonies#10461]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.21

### MineColonies Version

1.1.801

### Structurize Version

1.0.754

### Related Mods and their Versions

NeoForge 21.1.79
BlockUI 1.0.192
Domum Ornamentum 1.0.204

### Current Behavior

Open Cookery menu by right clicking Cookery block
Click on Crafting Recipes tab
Client crashes

### Expected Behavior

Open Cookery menu by right clicking Cookery block
Click on Crafting Recipes tab
Cooking recipes show up

### Reproduction Steps

Open Cookery menu by right clicking Cookery block
Click on Crafting Recipes tab

### Logs

https://gist.github.com/Droseran/08eb964724a6de6cea5787d3dc166122

### Anything else?

I added the recipes for soy sauce and raw noodles to this tab while playing on version 1.1.792 as they did not appear in any of the menus and I wanted to ensure the dishes were made.

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
fixed
