### ISSUE TITLE
Custom_payload error if player doesnt have style pack installed

### ISSUE THREAD

**Issue by TheWez** [ldtteam/minecolonies#10466]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.21

### MineColonies Version

minecolonies-1.1.802-1.21.1-snapshot

### Structurize Version

structurize-1.0.754-1.21.1-snapshot

### Related Mods and their Versions

1. NeoForge 21.1.79
Modpack: All The Mods 10 - v1.22

### Current Behavior

If the server has a style pack added to the blueprints folder, it fails to push it to players who do not yet have it upon joining and disconnects them with the error:
_"Client disconnected with reason: Internal Exception: io.netty.handler.codec.EncoderException: Failed to encode packet 'clientbound/minecraft:custom_payload'"_

If player already has the folder they connect successfully.

### Expected Behavior

To encode and successfully push the blueprint folder/style pack to players so they can use them in-game

### Reproduction Steps

1. add style pack to */blueprints folder on the server only (i'm using Littleton style pack here as an example)
2. connect client without the pack installed
3. connection fails while trying to push the pack to client

### Logs
client:
https://gist.github.com/TheWez/d0a27ad77ba8041343a0d35000da0338#file-gistfile1-txt
server:
https://gist.github.com/TheWez/a9f3ce62a522ff8badb187c368f31a22#file-gistfile1-txt

### Anything else?

The short-fix is getting all players to manually adding the individual style packs to their blueprints folder but this is beyond the scope of some of my players who are only used to one-click modpack installers

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by TheWez** [comment]
the more I look into it, this could be a Structurize bug?

**Comment by MotionlessTrain** [comment]
It is, and should be fixed already:
https://github.com/ldtteam/Structurize/pull/710
(It didn't seem to be properly linked to this issue)
