### ISSUE TITLE
Civs can not path down stairs if there is a door or gate at the bottom of the stairs

### ISSUE THREAD

**Issue by Jinotad** [ldtteam/minecolonies#10463]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [X] Multi Player

### Minecraft Version

1.20

### MineColonies Version

minecolonies-1.20.1-1.1.740-snapshot

### Structurize Version

structurize-1.20.1-1.0.760-snapshot

### Current Behavior

Civs can open the door at the bottom of stairs, and go up the stairs. Once they are upstairs, they then can not path down the stairs, becoming stuck. This has happened with both fence gates and doors. It doesn't matter if the gate or door is open.

Once the gate or door is broken, they are able to come down just fine.

![2024-11-18_19 14 28](https://github.com/user-attachments/assets/64601e22-9eb7-455c-946a-1a5108aeba33)
![2024-11-18_19 14 33](https://github.com/user-attachments/assets/52636233-80c6-4a20-bd10-5dc28771d160)
![2024-11-18_19 13 33](https://github.com/user-attachments/assets/2d44a32d-2663-4646-a39f-f74f49ae1522)
![2024-11-18_19 13 43](https://github.com/user-attachments/assets/5557e61d-58ce-4d89-aa9b-98e57fcb485b)

### Expected Behavior

Pathing through the open door/gate. If needed, open the door/gate themselves so they can path through.

### Reproduction Steps

Construct a Medival Dark Oak Fletcher level 5.
Teach the Fletcher a recipe, and put ingredients for the recipe in their racks upstairs.
Request the item in a postbox.

### Logs

none

### Anything else?

none

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by LadyShatana** [comment]
Possibly related - if ladders are placed side by side (for aesthetic purposes) they will path UP one side, but not back down.

**Comment by thaylar** [comment]
![2024-11-22_18 24 36](https://github.com/user-attachments/assets/314e8912-0ac1-47a5-ad27-5757434faa3b)

Opening the gate doesn't seem to work.  Removing the gate and the NPC seems to path freely that way.  As stated, going up is not a problem.

**Comment by LadyShatana** [comment]
Again, not sure if it is related: the Jungle Crusher has a gate 1 block away from the hut block. This actually prevented the worker from accessing the block and working (I have now permanently removed said gate from the schematic)
