### ISSUE TITLE
Ladder Dancies Part II

### ISSUE THREAD

**Issue by Estyria** [ldtteam/minecolonies#10462]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20

### MineColonies Version

Raid comp

### Structurize Version

Raid comp

### Related Mods and their Versions

Raid comp

### Current Behavior

Guards are still getting stuck at the top of the barracks ladders. It seems one will try to go up, get stuck, and then the whole barrack group will get jammed and they're just having a grand time in the mosh pit. I stood watching a good five minutes or so, left and came back a couple of times after that. Still there! I'm re-reporting as I promised I would Ray. Best of luck. As an aside, I even had a raid at this barracks and these guards, despite being closest, failed to respond to the injuries of their fellows. So it IS affecting gameplay significantly.

### Expected Behavior

Go up and down ladders like, you know, a normal human being. Ha!

### Reproduction Steps

Have Fortress barracks and a wall for them to patrol. That is all you need to recreate the epic ladder dance parties!

![2024-11-18_16 59 27](https://github.com/user-attachments/assets/7f53487d-5b75-48cf-9325-d083d9c83bd6)

### Logs

raidcomp

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by LadyShatana** [comment]
I also get Visitors bouncing on ladders. But I do at this very moment have an entire Barracks stuck on a ladder.

**Comment by patapon888** [comment]
it is not only guards, pepoles get stuck on every single ladder
