### ISSUE TITLE
villager not detecting guards tower and barracks

### ISSUE THREAD

**Issue by patapon888** [ldtteam/minecolonies#10465]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.21

### MineColonies Version

1.1.802-1.21.1

### Structurize Version

1.0.754-1.21.1

### Related Mods and their Versions

neoforge 21.1.74, Block Ui 1.0.192-1.21.1, Domum ornamentum 1.0.204-1.21.1

### Current Behavior

villager do not detect when there is guards tower and/or Barracks and there is impossiblequest and not saying that they not in security and they are angry.

### Expected Behavior

villager detecting when there is guards tower and Barracks and finishing there quest and not saying that they not in security

### Reproduction Steps

just play it normaly util a villager ask you to build a guard tower 

### Logs

https://gist.github.com/patapon888/9dd17350ac08173049a84a34ed0626ef

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
This is not a quest, this is about having guardtowers/barracks close to their living/working places. They feel unsave if there is no security hubs close to their living/working locations. This is not about having them "in general in the colony"
