### ISSUE TITLE
Aquatica miner isn't working right

### ISSUE THREAD

**Issue by Talyda** [ldtteam/minecolonies#10476]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20

### MineColonies Version

.740

### Structurize Version

.760

### Current Behavior

Building Aquatica colony. I have a level 1 miner, which I don't actually expect to do any actual mining yet, but I did expect them to create a shaft of some kind down to sea floor.

They have built 1 level of cobble platform, but are now stuck just constantly mining/placing one piece of cobblestone in front of the ladder, rather than continuing to fill in the space
![image](https://github.com/user-attachments/assets/dbbb41c5-1803-4f86-9a2c-6d8546727325)

Also, I had to manually give them a few stacks of cobble to even get them started - or they just stood waggling their arm around, and not requesting anything

### Expected Behavior

Was expecting them to fill in the space, or something like that! 
If they find an open gap when making their mineshaft in a "normal" world area, they continue to place the ladders down, and fill in big areas

### Reproduction Steps

Build aquatica mine
Watch them

### Logs

https://gist.github.com/Talyda/e3625fa96b70da6df60a808cf5838696

### Anything else?

Gonna test doing some stuff, like just make them a 1 block tunnel going down to sea bed - but wanted to report this as it is while I remembered 

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
I put a 3x3 of cobble directly under the bottom ladder, so she would have something else to dig at, but she keeps just breaking and placing that same one block

**Comment by Talyda** [comment]
I got her working, for now at least, by making a cobblestone pole where the ladder would go against all the way down to seabed. Then I made a gravel pole each other cardinal direction, and then filled in the middle so there was no water in the ladder area

**Comment by Raycoms** [comment]
#5006

**Comment by MotionlessTrain** [comment]
The issue seems to be that the miner can’t clear the water out, so it looks to be an AI issue rather than a schematic issue

**Comment by Talyda** [comment]
Yeah, did seem like the water was the problem. I *think* it is because she places the ladder, which then becomes waterlogged, and she can't clear that water?
I honestly have no idea how to check that.
