### ISSUE TITLE
Kids are not growing

### ISSUE THREAD

**Issue by NikeskA094** [ldtteam/minecolonies#10481]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.21

### MineColonies Version

1.16.5-1.0.978

### Structurize Version

1.16.5- 1.0.418

### Current Behavior

Well all my kids are not growing. It has been days

### Expected Behavior

them to grow

### Reproduction Steps

Can you tell me whats wrong?

### Logs

https://gist.github.com/NikeskA094/7e4410c6a090b8ceeb43443800a259d3#file-gistfile1-txt

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by kezmodius** [comment]
You are better off going to the Minecolonies discord for support like this. You are on 1.16.5, which has been unsupported for some time. There is a unsupported-version-talk channel in the discord for questions like yours.

**Comment by Raycoms** [comment]
ohhh, 1.16.5
