### ISSUE TITLE
Citizens should lay down in their beds at night [$5]

### ISSUE THREAD

**Issue by Raycoms** [ldtteam/minecolonies#1049]
Just let them search for an empty bed within their citizenHut and render them in and out at the right moment.

**Comment by xavierh** [comment]
We should also fix the number of beds per huts/level

**Comment by kedamono** [comment]
In my citizen huts that I build, I make sure to have 1 bed per level.

**Comment by Raycoms** [comment]
@OrionDevelopment did that aready
