### ISSUE TITLE
Nether Miner remains idle even after all supplies were fulfilled. Continues to request food over and over but doesn't work

### ISSUE THREAD

**Issue by Toxarcher** [ldtteam/minecolonies#10490]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20

### MineColonies Version

1.20.1-1.1.759-snapshot

### Structurize Version

1.20.1-1.0.760-snapshot

### Related Mods and their Versions

1. Forge Version: 47.3.7
![modlist](https://github.com/user-attachments/assets/fcc5681b-f199-427d-a0f2-0ca75db389b9)

### Current Behavior

![idle worker](https://github.com/user-attachments/assets/fcbb0b3c-ba53-46e0-9978-49bae97fd5e7)
![miner](https://github.com/user-attachments/assets/aaf7870b-1c6e-4671-b495-10b63618a470)

i created a level one nether miner, and fulfilled all the supplies they requested, but they have been idle at their workstation even after all the supplies was given to them. They also keep requesting food from the menu over and over, but they never go work.

### Expected Behavior

after all the supplies gets fulfilled to the worker, they will either immediately go work or go after a few minutes

### Reproduction Steps

1. use the byzantine style for your colony
2. create a nether mine
3. fulfill supplies to nether miner

### Logs

https://gist.github.com/Toxarcher/61c482568a762765a5972180f9c8c8f5

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
I ran up a quick test game too, pasted in two level 5 nether miners (incidentally, really love the look of the Ancient Athens level 5 =D) the first miner I gave her more than a stack of hand pies in her racks, she totally ignored them, so I used the fulfil button on her request for 16. She asked again, so I cancelled request she asked again, so I clicked fulfil, repeated again, she had 48 then she went off and did a trip. Second time around, she keeps asking and asking for 16 -  I have given her more than 10 stacks of food in her inventory, she is not going anywhere.
Second nether miner I put 48 in his racks, he totally ignored them. Moved 48 to his personal inventory, and he went off for a trip. Cam back and just kept asking and asking for 16 over and over, and same, more than 10 stacks of food, and he is still asking for 16

**Comment by Raycoms** [comment]
On a newer version we fixed the cosntant asking,t hey should ask up to 64

**Comment by Talyda** [comment]
Was testing on newest Ray - .759

**Comment by Raycoms** [comment]
So, netherminer should request up to 1 stack in inv + 1 stack in building at most. (In increments of 16, but non blocking)

**Comment by Talyda** [comment]
Yeah, they weren't going on the trips, even with many stacks

**Comment by Talyda** [comment]
I can probably test more tomorrow BTW - just couldn't handle minecraft today, so did a real quick test with pasting 2 in

**Comment by Talyda** [comment]
![image](https://github.com/user-attachments/assets/6884c6af-0664-4e4d-81f8-e39476f4dfa8)
![image](https://github.com/user-attachments/assets/30e4b13e-4485-40b5-ad1f-85d4b7b1e35c)
This is contents of her inventory, and her hut inventory. Every time I click on her, she gives me the "I'm waiting for something/where's that courier" voice line, but she has no requests (last time that happened was a month or so back, when their requests weren't showing at all) and her /mc citizeninfo says "gathering resources"
![image](https://github.com/user-attachments/assets/58c92912-da0d-445e-beab-5b7f97ecc92b)


Second one was acting exactly the same, so I threw more food in his inventory, 
![image](https://github.com/user-attachments/assets/b3387ac1-d634-4ab6-a188-c6abfa6a1ce7)
he's no longer giving me those voicelines, and his status is "idle" now
![image](https://github.com/user-attachments/assets/122e903c-5d53-475e-bc8c-180125e531da)

When I first logged in to the game, they both went off and did a trip. Been 5 in game days since they got back, (might have been 4 actually) and they were both acting the same as the first one since they got back (until I threw extra food into the second one)
Gonna keep game open until a few more in game days have passed to see if anything changes

**Comment by Talyda** [comment]
OK second one just went to the nether, with all that food in their inventory, first one is still giving me "I need something" voicelines

**Comment by Talyda** [comment]
Second guy came back from the nether, and has dumped all the extra food in the racks, and is now giving me the "need something" voicelines.  know one day isn't long enough to say he is stuck, but it does seem to be the exact same thing.
it's like they can't see the food in their racks?

First one just gave me this message
![image](https://github.com/user-attachments/assets/4cbe1307-4d8e-410a-8c6e-13b91f0750ce)
But her request tab is empty, and her mc citizeninfo still says gathering materials

**Comment by Talyda** [comment]
Alright, more fuddling around, and more nether mines and miners, it looks like until they have 32 of a food in their inventory they will not go. It doesn't matter how many is in their hut inventory, it has to be 32 in their personal inventory, but they won't pick any more up from the hut inventory. First nether miner I gave her 32, she went off, did a trip, never came back, (well, it had been 3 in game days =P) so I recalled her, she went and closed the portal, has put all but 16 of the food in the racks, and is now giving me the "I need something" voicelines again.
And that's all from me =P I don't know what else to do to test it, and it's late LOL

**Comment by Raycoms** [comment]
Ah, nice thanks. So they have a multi day timeout in-between where they might get the wrong sound lines, but the waiting for food stuff is weird, will have to test that

Sent from Proton Mail Android

-------- Original Message --------

**Comment by Talyda** [comment]
I don't think it is just the wrong sound lines. They are not going to go work, as if they are waiting for something - and a couple of them brought up the dialogue box about missing items last night - it just doesn't show anything on their request tab, even with that dialogue box.
And I waited 8 or more in game days for that first one to go, and she never did.

**Comment by 99dreada** [comment]
found a bit of a fix add a minimum quantity of

- 4x Cobblestone
- 4x Ladders
- 1x Torch
- 1x food

after that she put on her goggles and headed into the depths of the nether. didn't return with anything useful but its a temp fix at least.

**Comment by Talyda** [comment]
Did she go back a second time?
(asking cos I could get mine to go once, then not a second time)

**Comment by 99dreada** [comment]
awaiting that answer now will update tomorrow (getting late here)

**Comment by 99dreada** [comment]
so after 5 in game days she has got everything needed but not starting another mission

**Comment by 99dreada** [comment]
correction once i forced her to have more than 16 food and the above list in her inventory aswell as building block she set off again but there is defo a bug that she isnt picking it up by default.

**Comment by mafamaul** [comment]
I was told in discord to post here because I'm running on 1.1.816-1.21.1
My nether miner is stuck on gathering required materials until I give him a stack of food. He just keeps running to a rack and then walks away. As soon as I manually give him a stack of food his status changes to idle and he goes back to the rack and picks up the rest of the needed resources.

**Comment by 99dreada** [comment]
@Raycoms thank you very much dont understand the code enough to have fixed myself Its been bugging me for days.

Trying to passive build a colony and stuck needing nether resources having the manual fix every 5 mins kinda breaks the passive part of my build
