### ISSUE TITLE
Out of memory crashes - 1.20.1 760/761

### ISSUE THREAD

**Issue by AnyankaT** [ldtteam/minecolonies#10498]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20

### MineColonies Version

1.20.1-1.1.761

### Structurize Version

1.20.1-1.0.760-snapshot

### Related Mods and their Versions

So. Many. Mods.

### Current Behavior

I'm in the process of updating our server modpack, and it appears that Minecolonies 1.20.1-1.1.760 and 761 have both caused out of memory crashes. 
In the latest, I started the world, then added a couple foods to the restaurant menu. Within a minute or so everyone stopped moving and the world crashed.
I'd updated from pre-Food 2.0 to the latest version (760) yesterday, then tried the 761 update today.
Latest.log and both crash reports are in the gist.

### Expected Behavior

In previous versions the world did not freeze up. I'm also running another server with 759, which is operating as expected.

### Reproduction Steps

1. update to 760 or 761 from pre-Food2.0 versions
2. add items to restaurant menu
3. wait - everyone stops moving, then server times out

### Logs

https://gist.github.com/AnyankaT/35d462b12c93b9af85393de471083ab4

### Anything else?

I have two restaurants. In the second restaurant, Hand Pie was already in the menu, which was unexpected as I'd updated from a pre-Food 2.0 version. When I went to the second restaurant to add items to the menu, it was already there.

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
hotfix pushed
