### ISSUE TITLE
Sudden crash

### ISSUE THREAD

**Issue by Gerpus** [ldtteam/minecolonies#10493]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20

### MineColonies Version

1.20.1-1.1.759

### Structurize Version

1.20,1-1.0.760

### Related Mods and their Versions

1.Forge 47.3.0
2. domum_ornamentum-1.20.1-1.0.186-RELEASE-universal
3. multipiston-1.20-1.2.43-RELEASE
4. towntalk-1.20.1-1.1.0

### Current Behavior

Suddenly the server shut down

### Expected Behavior

The server should not shut down itself

### Reproduction Steps

It happened on its own

### Logs

https://drive.google.com/drive/folders/1XcQDmMyIcT9CtftTor7QwaCsyu6tTc_N?usp=sharing

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
Try without optifine. Optifine doesn't work with Forge. You need Embeddium and Oculus. Closing this issue, comment if persists.

**Comment by Gerpus** [comment]
The problem is that it wasn't my minecraft that crashed, but the server crashed

**Comment by Raycoms** [comment]
Please upload the server crashlog as a gist then

**Comment by Gerpus** [comment]
I didn't really understand you, should I just send you the crashlog of the server?

**Comment by Thodor12** [comment]
We require any server instance to be ran in online mode for bug reports to be valid. Your server is running in offline mode, so support ends here.

**Comment by Gerpus** [comment]
Thanks
