### ISSUE TITLE
[Performance] Memory Leak of Chunks

### ISSUE THREAD

**Issue by pietro-lopes** [ldtteam/minecolonies#10492]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.21

### MineColonies Version

1.1.806

### Structurize Version

1.0.755

### Related Mods and their Versions

NeoForge 21.1.81

### Current Behavior

This here is leaking some already unloaded chunks

https://github.com/ldtteam/minecolonies/blob/8a5def598e0de79445c6cd318ef535cbf88ab790/src/main/java/com/minecolonies/core/entity/pathfinding/world/ChunkCache.java#L46

![image](https://github.com/user-attachments/assets/b867cd9d-3377-4e7f-ba25-757b9ae2140b)

### Expected Behavior

No leaks

### Reproduction Steps

This was taken from a heap dump of a server

### Logs

NA

### Anything else?

From ATM10 Modpack

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
This is not a memory leak if we temporary hold onto them for a bit after they were unloaded. This will get removed once the raid is over.
