### ISSUE TITLE
[Performance] Memory Leak of ServerPlayers

### ISSUE THREAD

**Issue by pietro-lopes** [ldtteam/minecolonies#10491]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.21

### MineColonies Version

1.1.806

### Structurize Version

1.0.755

### Related Mods and their Versions

Neoforge 21.1.81

### Current Behavior

Those are leaking players as we checked our heapdump.
ServerPlayers removed from Level were still there (with removalReason `UNLOADED_WTIH_PLAYER`).

https://github.com/ldtteam/minecolonies/blob/8a5def598e0de79445c6cd318ef535cbf88ab790/src/main/java/com/minecolonies/core/colony/Colony.java#L255

https://github.com/ldtteam/minecolonies/blob/8a5def598e0de79445c6cd318ef535cbf88ab790/src/main/java/com/minecolonies/core/colony/Colony.java#L260

![image](https://github.com/user-attachments/assets/92c5aab0-a4fb-4484-b6e0-8158a33f4f16)

### Expected Behavior

No leak

### Reproduction Steps

This was checked from a heap dump of our dedicated servers

### Logs

NA

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
```
    /**
     * Updates the pvping playeres.
     */
    public void updateAttackingPlayers()
    {
        final List<Player> visitors = new ArrayList<>(visitingPlayers);

        //Clean up visiting player.
        for (final Player player : visitors)
        {
            if (!packageManager.getCloseSubscribers().contains(player))
            {
                visitingPlayers.remove(player);
                attackingPlayers.remove(new AttackingPlayer(player));
            }
        }
```

We actually clean those out regularily. It just might take a minute after the player logs out in a colony.
So this is also fine.
