### ISSUE TITLE
Cant remove recipe from stonemason

### ISSUE THREAD

**Issue by ArynRama** [ldtteam/minecolonies#10503]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.21

### MineColonies Version

1.1.817-1.12.1

### Structurize Version

1.0.755-1.21.1

### Related Mods and their Versions

NeoForge: 21.1.83
Modpack: All The Mods 10 version 1.26 (https://www.curseforge.com/minecraft/modpacks/all-the-mods-10/files/5961041/additional-files)

### Current Behavior

When trying to remove a recipe from the stonemason the recipes dissapear from the ui and then reapear. allong with a console mesage "Failure to remove recipe, please tell the mod authors about this"

### Expected Behavior

The recipe gets removed

### Reproduction Steps

1. Open stonemason ui
2. go to recipes
3. press remove
4. after a bit reopen ui

### Logs

https://gist.github.com/ArynRama/e10ca554f5d2e599f6127fc316de198f

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
Are the recipes you are trying to remove the ones that the hut automatically knows? You can't remove those, they will always come back

**Comment by ArynRama** [comment]
ahh yeah i see. tyy
