### ISSUE TITLE
Quarry Issue 1.21.1

### ISSUE THREAD

**Issue by brandonyy4u** [ldtteam/minecolonies#10501]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.21

### MineColonies Version

minecolonies-1.1.787-1.21.1-snapshot

### Structurize Version

structurize-1.0.754-1.21.1-snapshot

### Related Mods and their Versions

None to my knowledge. 

### Current Behavior

You are able to create quarries but within the Minecolonies GUI to doesn't have a location to select quarry to be built. You can hire a quarrier within the mine, but are unable to build any of the quarries.

https://github.com/user-attachments/assets/a05efaa5-61db-4940-af31-41c462255b9a

### Expected Behavior

While opening the Minecolonies GUI was expecting to find "Quarry" in one of the corresponding sections of the Minecolonies groups. Allowing the player to be able to move and relocate the quarry with the movement / rotating arrows as it is with all other Minecolony builds.

### Reproduction Steps

1. Craft a Quarry
2. Right Click the Quarry on the location that you want it to build
3. Use the Build Tool to look for the location of the quarry.
4. After failing to find the location of the quarry within the Minecolonies GUI
5. Open CurseForge and submit a bug report about Quarries not being within the GUI.

### Logs

https://gist.github.com/brandonyy4u/cf78ef4bc7f17d31c0475c027ddb5030

### Anything else?

https://github.com/user-attachments/assets/8e683658-018e-451c-94c4-2888972331c6

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
Not all styles have a quarry. Right click in the air with the quarry hutblock, and wait for the list to populate which will shows you which styles have one, and where in the build tool to look for it.

**Comment by brandonyy4u** [comment]
> Not all styles have a quarry. Right click in the air with the quarry hutblock, and wait for the list to populate which will shows you which styles have one, and where in the build tool to look for it.

Just did it and the quarry block seems to be very limited in styles that it works with. Just happened that my partner and I happened to both pick a style that doesn't support a quarry. I'll load up another single player and see if I find it in one of the listed styles.

https://github.com/user-attachments/assets/cb2a7543-fc4f-46a2-85c8-f91ed2e247e8

**Comment by Shadizar** [comment]
You can build from any style though, so you can simply make your quarry another style
