### ISSUE TITLE
Christmas server scrolls de-register their waypoints after a time

### ISSUE THREAD

**Issue by ncottrill** [ldtteam/minecolonies#10504]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20

### MineColonies Version

1.1.759

### Structurize Version

1.0.760

### Related Mods and their Versions

The Patreon Christmas server with  MColonies1.1.759

### Current Behavior

A teleport scroll made by the Enchanter is registered to a townhall. The scroll shows the name of the townhall. After some time and going to another colony or through the nether (not all instances of deregistering are because the scroll went through the nether), the scroll doesn't show the name of its registered townhall. Sometimes, if we're lucky, we can use the scroll and be sent to the registered townhall, sometimes it doesn't work at all, but sometimes we're teleported to some random place. Anastasia mentioned she was teleported off of a cliff with no buildings around.

### Expected Behavior

After registering a scroll to a townhall and after any length of time from the time of registration, I expect that the scroll will take me back to the townhall from any place and any dimension.

### Reproduction Steps

Log onto the Christmas server
Register a scroll with the townhall there.
Go to someone else's colony.
Review what happens to the scroll.
Do the same after some period of time has passed.
Do the same after running through the nether with the scroll in your inventory.

### Logs

No log available

### Anything else?

See references in Discord to players sharing their experiences with the teleportation scrolls.

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by kezmodius** [comment]
That happens when the colony is unloaded usually. They should still work to tp you there though. Did you try and use them?
