### ISSUE TITLE
AI log upload

### ISSUE THREAD

**Issue by Assaideas0419** [ldtteam/minecolonies#10524]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.20

### MineColonies Version

1.20.1-1.1.603-RELEASE

### Structurize Version

1.20.1-1.0.742-RELEASE

### Related Mods and their Versions

1.Forge version:47.3.0

### Reproduction Steps

1.I just put the builders hut then hire a guy to build it.
2.Gave her some material to build.
3.She didn't build the build hut.
4.When I went to check,she told me to give the latest.log to the developer.

### Logs

https://gist.github.com/Assaideas0419/ec659c183a94f742f48ea924ae344e36

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
Please remove the "Sounds" mod, it's a known incompatibility
