### ISSUE TITLE
AI log upload

### ISSUE THREAD

**Issue by madsbuvi** [ldtteam/minecolonies#10537]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.20

### MineColonies Version

1.1.776

### Structurize Version

1.0.763

### Related Mods and their Versions

TownTalk - 1.1.0

### Reproduction Steps

If i log into my world with minecolonies 1.1.776 this happens with no further steps.

### Logs

https://pastebin.com/AUFyCwQS

### Anything else?

Log is continuously spammed by the same exception. Teacher is the only one i noticed get paused from it.

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
fix pushed
