### ISSUE TITLE
Citizens should walk faster on paths, and locomotion should stick to the path

### ISSUE THREAD

**Issue by cltnschlosser** [ldtteam/minecolonies#1054]
Current behavior:
![gravel_pathing](https://cloud.githubusercontent.com/assets/1498529/26330914/e0373612-3f13-11e7-8479-f931fdf81a81.gif)

**Comment by SulpherStaer** [comment]
As long as grass path, cobblestone, gravel, and stone bricks are amongst the type of walking surface, I am okay with this.

**Comment by cltnschlosser** [comment]
@sylcai I think we should make it a config option, currently its hardcoded to gravel, stonebrick, and grass path

**Comment by AndrewTru** [comment]
I was thinking about this as well, I use the grass paths a lot and this will help on a void world due to the lack of ground from point A to point B.

**Comment by cltnschlosser** [comment]
@AndrewTru They shouldn't run off the edge into the void, is that happening now?

**Comment by Wissi** [comment]
This should be merged with issue #626?

**Comment by marvin-bitterlich** [comment]
i'd say they are different. This is for staying on a path, the other one is for adding an new path block

**Comment by AndrewTru** [comment]
@cltnschlosser , so far
Idle yes
Pathing somewhat interaction with chisel N bits
      To extend the info on the above one, pathing says block but when your town paths they fall off the platform and seem to like finding the fastest path first and not the applied path.

**Comment by Raycoms** [comment]
That's fixed now, fortunately
