### ISSUE TITLE
Compatibility issues with the Plantations and Forgified Fabric API

### ISSUE THREAD

**Issue by libertyboy1** [ldtteam/minecolonies#10547]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.21

### MineColonies Version

1.1.823-1.21.1-snapshot

### Structurize Version

1.0.758-1.21.1

### Related Mods and their Versions

Newforge：21.1.90
BlackUI：1.0.192-1.21.1-snapshot
Domum Ornamentum：1.0.204-1.21.1-snapshot
Multi Piston：1.2.51-1.21.1-snapshot
Town Talk：1.2.0

### Current Behavior

mod：Forgified Fabric Api 0.107.0 2.0.22 + Sinytra Connector 2.0.0-beta.4

Plantations cannot identify other crops, such as kelp, cocoa, etc

![1734933909915](https://github.com/user-attachments/assets/4dc35be2-caae-42c2-9498-fa7c224ba9b3)
![1734933913234](https://github.com/user-attachments/assets/17522aea-c9c4-4976-9d4a-37ba6c79f109)
![1734934436390](https://github.com/user-attachments/assets/44c4df89-4ba3-4455-9a36-e736612e866f)

### Expected Behavior

Plantations can identify other crops

### Reproduction Steps

1、build Plantations
2、build kelp field

### Logs

none

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
We do not support using the forgified fabric api, you must remove it.
