### ISSUE TITLE
Crafts don't work

### ISSUE THREAD

**Issue by Gerpus** [ldtteam/minecolonies#10550]
![Screenshot_261](https://github.com/user-attachments/assets/ba32b0c2-230c-4a4f-b536-c6261ff4e05f)
![Screenshot_262](https://github.com/user-attachments/assets/24791c4d-a56f-4737-8e5f-b5dc2b190d5e)
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20

### MineColonies Version

1.20.1-1.1.778

### Structurize Version

1.20,1-1.0.763

### Related Mods and their Versions

OpenLoader-Forge-1.20.1-19.0.4
KubeJS Forge 2001.6.5-build.16

### Current Behavior

I'm creating my build using the Mineclonies mod and wanted to add crafting items that only colonists can create. To do this, I use the "Open Loader" mod, and to remove crafting, I use the "KubeJS" mod. And I ran into the problem that crafting can't be properly added to many items (photos #1 and #2). I also tried to insert the code into the mod itself or add various tags to the items, but it didn't help (Crafting is added to some items, for example, to all armor).

### Expected Behavior

Crafting must be added correctly to all items.

### Reproduction Steps

1.Download all mods 2.Write a code to remove crafting items 3.Write a code to add recipes

### Logs

https://drive.google.com/drive/folders/10KeS-1ZAKMUzncoYp1Lrjotog9zC9l41?usp=sharing

### Anything else?

Файлы загружаю по пути src/datagen/generated/minecolonies/data/minecolonies/crafterrecipes/ (The code path from GitHub)

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Gerpus** [comment]
I will add: There is no such problem on version 1.21.1.

**Comment by uecasm** [comment]
You don't have the correct syntax in your json files.  The syntax is very different between 1.20 and 1.21 due to changes in Minecraft.  Look at some existing 1.20 datapacks or the recipes included in the mod for reference.

And as you've already been told in Discord, it is not possible to use tags in crafterrecipes; you must use specific items.  If you're claiming that this does work in 1.21, then that would be a bug.

If you want further help with your data packs, then ask in the correct channel in Discord.
