### ISSUE TITLE
Citizen sleeping issue still not fixed

### ISSUE THREAD

**Issue by Mattijs-VH** [ldtteam/minecolonies#10566]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.21

### MineColonies Version

1.1.843-1.21.1

### Structurize Version

1.0.758-1.21.1

### Current Behavior

Citizens aren't able to get into their beds if there's a block next to it. Wich is very frustrating since a lot of styles were designed to have this. 
![2024-12-29_12 27 10](https://github.com/user-attachments/assets/128cbdb2-bda2-43e9-9d4d-e92d1e242578)
this picture is from a lvl 3 Ancient athens residence (estate).
Breaking the blocks immediatly lets them sleep
![2024-12-29_12 27 19](https://github.com/user-attachments/assets/acf884dc-cab7-4eaa-a499-ea0a1d0e38e4)

### Expected Behavior

I'd expect them to sleep as long as they can access the bed from a way. doesn't matter if it's head or feet part. this was the case previously

### Reproduction Steps

have a residence with beds with blocks next to it

see that citizens don't sleep

### Logs

/

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by addlp** [comment]
Same problem in cavern style, they just stand there without sleeping next to the hut, the worst thing is that when they besiege the village, they are easier for the villagers to kill because they are close to the door of the house.

**Comment by Shadizar** [comment]
1.20 has it happen a lot too; so far, Archwood collective style (haven't checked many others)

**Comment by Talyda** [comment]
> 1.20 has it happen a lot too; so far, Archwood collective style (haven't checked many others)

In the latest version of 1.20 Shadizar? Should have been fixed in the one ending in .786
Only people I have seen complaining in the past day or so, are people in 1.21, with the version mentioned in original post here (which made me think maybe it hasn't been fixed in 1.21 yet for some reason)

**Comment by Shadizar** [comment]
Ah; no, we haven't got to that build yet, will have to check after we update in a few weeks

**Comment by Raycoms** [comment]
ported to 1.21 now too
