### ISSUE TITLE
Game closes when you click past the posts in the architects table 

### ISSUE THREAD

**Issue by GTSKing21** [ldtteam/minecolonies#10568]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20

### MineColonies Version

1.20.1-1.1.786

### Structurize Version

1.20.1-1.0.763

### Current Behavior

When you open the architects table, and click past the poles variation, and close the table and try to reopen it the game close
https://cdn.discordapp.com/attachments/1125094832143077456/1323090187458449458/image.png?ex=67733f42&is=6771edc2&hm=84f0cc92626e0107c80a2e8b2bcdaba8551edc12875eab83ecb4500f894a0cee&s

### Expected Behavior

The table just reopens

### Reproduction Steps

1. Open the architects table,
2. Scroll down the variations tab to the post
3. Click on the blank space to the right of the post
4. Close the table
5. Reopen the architects table 
6. Game crash
7. https://cdn.discordapp.com/attachments/1125094832143077456/1323090424604266618/image.png?ex=67733f7b&is=6771edfb&hm=fcf69119f9c5ef95675201032c96c42d174670a33f503f03c628dfc46e76b7f1&

### Logs

https://gist.github.com/GTSKing21/46f334649ef0ac9f03d0e61360d22bf3

### Anything else?

No

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
I replicated this while we were trying to work out what the problem was, and crashed the same
Log here in case it helps: https://gist.github.com/Talyda/bb9ac9853d5fc99d3f7dceb8daa091d3

**Comment by Raycoms** [comment]
fixed
