### ISSUE TITLE
Minecraft crash when opening require ressources in builder's hut at the same time as completing the building process

### ISSUE THREAD

**Issue by CCC7012** [ldtteam/minecolonies#10567]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20

### MineColonies Version

1.20.1-1.1.603-RELEASE

### Structurize Version

1.20.1-1.0.742-RELEASE

### Related Mods and their Versions

Forge: 47.3.0
BlockUi: 1.0.156
Domum Ornamentum: 1.0.186
TownTalk: 1.1.0
Optifine: 1.20.1_HD_U_16

### Current Behavior

I started a upgrade of a warehouse. I tried, after opening the builder's hut GUI, to open the "required ressources" tab. At the same time I eared the fireworks that appear when a building is finished. Then my game freezed, whitout showing me the ressources tab, and a few seconds after, it crashed.

### Expected Behavior

I extpected the game to show me the ressources tab, with the inscription "there is no buid in progress" (or something like that).

### Reproduction Steps

1. Start an upgrade
1. Just before the end of the upgrade, open the "requires ressources" tab of the builder (at the same time that earing the fire works or just before)
1. At that time my game freezed and crashed

### Logs

https://pastebin.com/8Sq8naK7

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
Update the mod, you are on an outdated version
