### ISSUE TITLE
Quarks & Opening door permission

### ISSUE THREAD

**Issue by xavierh** [ldtteam/minecolonies#1072]
### Minecolonies version

version/1.11

### Expected behavior

- Should not be able to open door if the permission is not granted

### Actual behaviour

- Warn that I do not have the permission but the door open anyway

Quarks allow to open double door automatically when you open one which probably mess the permission.

Additionnaly the only one door is open when colonist open a double door

**Comment by Raycoms** [comment]
Should be fixed with newer quark versions:
https://github.com/Vazkii/Quark/issues/386
