### ISSUE TITLE
Builder should break entities when upgrading.

### ISSUE THREAD

**Issue by H3roDude** [ldtteam/minecolonies#1075]
Hey, my Builder dont want to break Item Frames when upgrading a Hut
Hes done with lvl 5 and now there are 2 item frames on the wall who arent in the schematic from the lvl 5 hut

**Comment by Raycoms** [comment]
Yeah we need to fix this.
We only clean up blocks and not entities after a build.

2017-05-24 15:01 GMT-03:00 H3roDude <notifications@github.com>:

**Comment by H3roDude** [comment]
also he should get the items in his inventory, like when hes breaking item frames or armor stand's
