### ISSUE TITLE
java.lang.NoClassDefFoundError: com/minecolonies/api/colony/permissions/Rank (1.11.2)

### ISSUE THREAD

**Issue by SDUBZ** [ldtteam/minecolonies#1077]
### Minecolonies version

version X.X.XXXX or curse X.X.XX
minecolonies-universal-1.11.2-0.8.1633
Forge:1.11.2-2304
### Expected behavior
to load up fine after updating

### Actual behaviour
crashed

### Steps to reproduce the problem

1. update to minecolonies-universal-1.11.2-0.8.1633
2. load up and get crash

3. ...
4. Profit

crash:
[crash-2017-05-25_05.57.03-client.txt](https://github.com/Minecolonies/minecolonies/files/1027115/crash-2017-05-25_05.57.03-client.txt)

**Comment by Raycoms** [comment]
copy of #1074.
