### ISSUE TITLE
Miner doesn't ask for cobblestone/stops mining out of nothing

### ISSUE THREAD

**Issue by nekatu** [ldtteam/minecolonies#1078]
### Minecolonies version

version 0.8.1540 (but seems to have been there for the last few weeks over versions)

### Expected behavior

Miner asks for cobblestone like all other resources

### Actual behaviour

Mine stands around waiting for something but never asks for cobblestone

### Steps to reproduce the problem

1. Leave miner to do his thang
2. Notice he's not doing a lot of, you know, mining...
3. Give him everything you can think of until he gets cobblestone and then runs off happy
4. Profit

The Deliveryman seems just as confused as I am as to what the Miner is waiting around for, happily bringing him everything else he asks for (ladders, torches, etc) but no one seems to know he needs cobblestone, and he seems strangely shy about it. ;-)

**Comment by cltnschlosser** [comment]
I believe this should be fixed in the next version. But I also think that build is probably broken right now, so I'm going to leave this open until my next debugging session with the deliveryman.

**Comment by Wissi** [comment]
I think this issue has been fixed?
Should this be closed @Raycoms ?

**Comment by Raycoms** [comment]
Yes please

2018-05-03 21:16 GMT+01:00 Wissi <notifications@github.com>:
