### ISSUE TITLE
Refined Storage Constructor and Destructor does not work anymore when minecolonies is installed

### ISSUE THREAD

**Issue by Ioandar** [ldtteam/minecolonies#1086]
Block place and Block remove with Refined Storage is not possible when minecolonies is installed

### Minecolonies version

tested versions: 1.10.2-0.8.1429 or 1.11.2-0.8.1440

here:
- Minecraft: 1.10.2
- Forge: 1.10.2 - 12.18.3.2185 (recommended version)
- Refined Storage: 1.2.25 (latest version for 1.10.2, no change if using others down to 1.2.5)
- minecolonies 1.10.2-0.8.1429 from curseforge.com/projects/minecolonies
  same crossmod conflict when using 1.11.2 and 1.11.2-0.8.1440. Block Event conflict?

### Expected behavior

- Refined Storage constructor places block

### Actual behaviour

- Refined Storage Constructor does not place blocks when minecolonies is installed. Removing minecolonies makes refined storage works again. placing blocks and removing blocks (constructor/destructor).

### Steps to reproduce the problem

1. Use minecraft 1.10.2 with refined storage abd minecolonies mod
2. setup a minimal Refined Storage system and try using the constructor to place a block
3. 
4. Profit

http://github.com/raoulvdberge/refinedstorage/issues/1236

**Comment by Raycoms** [comment]
It seems like refinedStorage uses fakePlayers.

There are two chances:

1) Disable colony protection in the config.
2) As we spoke with the forge team, fakePlayers should inherit the players UUID, I guess refinedStorage does that wrong
