### ISSUE TITLE
Recipes need fixing

### ISSUE THREAD

**Issue by TheRealM18** [ldtteam/minecolonies#1090]
0.8.1784

### Expected behavior
recipe for town hall

lang needs to say the recipe for multiple structures

### Actual behaviour

recipe for town hall does not excissed

lang for town hall teir 3 says 1 item frame needed

lang for fishery does not except the 4 item frames

### Steps to reproduce the problem

do creative mode with single player from the start aka check an exciting jar
those two building are the ones that i have notice recipe problems so far

**Comment by Raycoms** [comment]
Should be fixed in the newest versions.

**Comment by EX3MP** [comment]
We have the same problem with the Townhall and Warehouse on the upgrade to Tier 3

MC Version: 1.10.2
Minecolonies: 0.8.2661

When we give them the item frame it disappears.

**Comment by EX3MP** [comment]
Nevermind, the text for call for item frames is a bit confusing. It just say's he need 1 but he needs a lot more.

**Comment by Raycoms** [comment]
Should be fixed now
