### ISSUE TITLE
Farmer and Field interaction could use an overhaul

### ISSUE THREAD

**Issue by cltnschlosser** [ldtteam/minecolonies#1093]
Things I noticed:
- Fields use the citizens names, instead of UUID's
- Field update packets are sent way too often
- Farmer/Field serialization could be improved
- Farmer error checking is seriously lacking, which is why we need to call "sync" methods to detect missing fields.

**Comment by AndrewTru** [comment]
Seems to me that the clock speed of the Farmers and the fields are not keeping sync, what if the two systems use the same clock and you link it by the Unit ID?

**Comment by cltnschlosser** [comment]
@AndrewTru I'm guessing you have an electronics background?

**Comment by AndrewTru** [comment]
Computer A+, RAM/CPU have the same idea.

**Comment by Raycoms** [comment]
Fields use the citizens names, instead of UUID's
Names are coded to be unique in minecolonies atm.

**Comment by AndrewTru** [comment]
@Raycoms good point, This seems to be a lot harder than it looks.
Overhauling the system will sadly brake the mod in the case of the farmer.
If you can rework the farmer and the fields so they work together a overhaul of the system can be done. One line of code off and you crash the whole food system wide open. Sadly this is where my assistance with this issue ends, I have little to no clue how to rework the system as this time. this issue will have to be placed on an idea back burner for now.
