### ISSUE TITLE
Bakery not a building?

### ISSUE THREAD

**Issue by mistresskahlan** [ldtteam/minecolonies#1094]
### Minecolonies version
curse 1.10.2-0.8.1331

### Expected behavior
building shows me boundaries

### Actual behaviour
building point goes down and nothing shows up to show me where it will be. Also, doesn't show up on builders tool.

### Steps to reproduce the problem
1. build a barkery
2. put it down (or use builders tool)
![2017-05-26_11 20 21](https://cloud.githubusercontent.com/assets/2369033/26491104/1a104f78-4206-11e7-8a69-a482f368c233.png)

**Comment by marvin-bitterlich** [comment]
look at #1073 not merged so not implemented yet

**Comment by marvin-bitterlich** [comment]
@mistresselara If you click on the pr and on watch there you get an email when it is done
