### ISSUE TITLE
Miner requests 1 item at a time

### ISSUE THREAD

**Issue by cltnschlosser** [ldtteam/minecolonies#1096]
It takes a long time to build a level if you request every slab 1  at a time, and have to wait for the deliveryman.

This also hurts the verbal request, because he is repeating the same things often, so it gets filtered by the chat spam filter.

**Comment by xavierh** [comment]
He get delivered 1 stack of slabs, does he not?

**Comment by Raycoms** [comment]
Actually we can have them request a stack as well, The request system is
designed that even if he only receives a subvalue he should return to work.

2017-05-29 13:39 GMT-03:00 xavierh <notifications@github.com>:

**Comment by ghost** [comment]
I have the same issue (#1730).

Sometimes, my builder and miner don’t even tell me what they need, so they just stand there, waiting helplessly.
