### ISSUE TITLE
World freeze and crash when looking up/down on ladder in miner's shaft.

### ISSUE THREAD

**Issue by Boyownik** [ldtteam/minecolonies#1100]
### Minecolonies version

version 0.8.1715

### Actual behaviour

- Minecraft freeze for a moment and then fatal error with button "back to the server list" when i look up/down standing on ladder in Miner's shaft. No crash logs. 
Latest logs: https://pastebin.com/seWg1zca

**Comment by cltnschlosser** [comment]
I don't know if this is even related to minecolonies.

**Comment by AndrewTru** [comment]
I just looked at the log, it has over 1k lines and I can't find when in the log the program crashed.

**Comment by SulpherStaer** [comment]
I had a similar problem, when I had an older version of Fancy Block Particles.

This is not a problem with Minecolonies. Do a test, by turning the half of your mods off / on, and find the one that causes the crash.

It is NOT minecolonies.

**Comment by cltnschlosser** [comment]
Closing unless @Boyownik returns with more information proving this is minecolonies.
