### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by Drakoflame** [ldtteam/minecolonies#1105]
I got a crash on Minecolonies version: 1.11.2-0.8.1784 Forge 13.20.0.2282

Crash log: https://pastebin.com/pa5iRs4t

it says something to do with the block render? 9/10 whenever I use a mod it always says it has issues with block renders/finding a specific file. Its gotten to the point that if I get this error I dump the mod and walk away and come back a few versions later, but this time I felt like submitting the error, even on the off chance I'm that one in a million crashes that crashed because of a bug so obscure only one other person has ever had it and no-one can re-create it.

Hope this helps and you guys can tell me what I did wrong! I'm going to use an older version for now, hopefully that works.

**Comment by marvin-bitterlich** [comment]
[ooks like a crash of BetterGrass to me

**Comment by Drakoflame** [comment]
I was just coming to say that even after removing Minecolonies, I got the crash... Don't know why its happening, BetterGrass is a modual of Quark... going to test one thing, just updated Tinkers to the newest versions, and I"m wondering if thats causing the issue?

**Comment by marvin-bitterlich** [comment]
Alright, thanks fer the update!

If you have any problems with minecolonies, we fix them quickly :)

**Comment by Drakoflame** [comment]
Looks like I found the issue... maybe? Anyway... you know how when you update a mod, they tell you to delete the old versions because it'll read as two of the same mod and Forge doesn't like that... well... when you have two versions of a mod, it can cause quite a few issues... I updated my minimap/worldmap mod, and forgot to delete the old ones... deleted the old files and everything works now XD

Don't know how the heck that happened... yea, thanks for the help (on a mod that doesn't even remotely have anything to do with yours)
