### ISSUE TITLE
Schematic issue with guard 5

### ISSUE THREAD

**Issue by wilsondgonzales** [ldtteam/minecolonies#1109]
When you're previewing a guard tower lv5 and joining it to a wall, the builder will destroy a block section of the wall the tower is to be connected to. there should be placeholder blocks since the initial lv to be built is lv1

**Comment by marvin-bitterlich** [comment]
What Style did this happen with?

**Comment by wilsondgonzales** [comment]
it should be from lv1. basically the preview of a lv5 tower looks perfectly connected to a wall section. after you click the checkmark and build, the builder will cut of a 1 block full section of the wall the tower is being connected to

**Comment by marvin-bitterlich** [comment]
wood, stone or sandstone?

**Comment by marvin-bitterlich** [comment]
style ≠ level

**Comment by wilsondgonzales** [comment]
my bad. wood

**Comment by xavierh** [comment]
@marvin I have rescanned the guard tower to take this into account. I have
4 version, with or without water and straight or corner. Any interests?

**Comment by Raycoms** [comment]
I thought you had added them to the game already =D

2017-05-30 16:00 GMT-03:00 xavierh <notifications@github.com>:

> @marvin I have rescanned the guard tower to take this into account. I have
> 4 version, with or without water and straight or corner. Any interests?
>

**Comment by xavierh** [comment]
No. I have been selfish and been using them for my own pleasure :D

**Comment by wilsondgonzales** [comment]
are there new schematics for the newest version? just wondering

**Comment by xavierh** [comment]
No. Still the same. Will send you mine today if you wish. Are you using the wooden walls?

**Comment by wilsondgonzales** [comment]
@xavierh no i'm using stone. it's alright i can wait for the next release :)

**Comment by xavierh** [comment]
[GuardTower.zip](https://github.com/Minecolonies/minecolonies/files/1052765/GuardTower.zip)
As promised, 4 styles of guard tower, 2 corners 2 straight both with or without moat
They are meant to go with decoration walls, but I also modified them see in walls.zip
[Walls.zip](https://github.com/Minecolonies/minecolonies/files/1052768/Walls.zip)
