### ISSUE TITLE
Colonists not spawning?

### ISSUE THREAD

**Issue by omega025** [ldtteam/minecolonies#1110]
### Minecolonies version

version 0.8.1917

### Expected behavior

- A limited number of colonists spawn automatically after the placement of the Town Hall block (podium with book).

### Actual behaviour

- After Town Hall block is placed, the "Found a colony" achievement is triggered and the construction tape cordon appears, but no colonists spawn.  Right-clicking on Town Hall shows menu with the Information tab indicating that the colony has 0/4 colonists.

### Steps to reproduce the problem

1. Create new world.
2. Build supply camp.
3. Use Town Hall block or building wand provided to place a new Town Hall.
4. Town Hall block placed, achievement triggered, no colonists.

**Comment by marvin-bitterlich** [comment]
please wait a Minute, they will appear. Place the builders hut while you wait

**Comment by omega025** [comment]
In previous builds the first colonist would appear almost immediately - has a delay been added?  If so, about how long should I be waiting?

**Comment by marvin-bitterlich** [comment]
The config determines the spawn time. I think 1-3 minutes per colonist

**Comment by omega025** [comment]
If it's the CitizenRespawnInterval config setting, that appears to be set to the default 30 seconds (I haven't adjusted my configs at all), though after waiting 15 minutes still no colonists have appeared.

Should I be deleting a config file after updating minecolonies versions?

**Comment by omega025** [comment]
False alarm - after making a new save several times it seems to be working again. How bizarre.
