### ISSUE TITLE
Can't Interact with Villagers or any Building Blocks

### ISSUE THREAD

**Issue by zoou** [ldtteam/minecolonies#1112]
[crash-2017-05-30_21.42.43-client.txt](https://github.com/Minecolonies/minecolonies/files/1040328/crash-2017-05-30_21.42.43-client.txt)
### Minecolonies version

version 0.8.1772

### Expected behavior

- Interface opens when interacting with a villager or building block (town hall, builders hut, etc)

### Actual behaviour

- Nothing happens when I right click a villager or building block.

### Steps to reproduce the problem

Not too sure how to reproduce this. Everything worked fine for a number of days. I got a town hall setup and some buildings. Suddenly when I loaded the world none of the interfaces opened, and when trying to interact with a villager, I got the attached crash. The villagers are still following their commands as usual.

Edit: Booted up this morning, and it's working again. Was going to try using /mc colony refresh.

**Comment by zoou** [comment]
The issue has returned. /mc colony refresh doesn't work. The village functions perfectly fine, except no GUIs appear.

**Comment by Raycoms** [comment]
Tried to restart?

2017-06-04 19:53 GMT-03:00 zoou <notifications@github.com>:

**Comment by zoou** [comment]
Restarting did fix it. Thank you. Just had to quit to menu and load the world again.

**Comment by Raycoms** [comment]
Good to know
