### ISSUE TITLE
[bug/feature] any version when buttons required and coupled with Better With Mods

### ISSUE THREAD

**Issue by kreezxil** [ldtteam/minecolonies#1113]
When Minecolonies is used with Better with Mods and BWM is set to HCSteelRecipes=true, making a stone button requires killing the Ender Dragon.

My suggestion is that builder should be allowed to use any button and not require the stone button.

See: https://github.com/BeetoGuy/BetterWithMods/issues/386

**Comment by marvin-bitterlich** [comment]
why does it do that??? That is so broken xD

Just rescan the building btw ;)

**Comment by kreezxil** [comment]
I created a new mod today that solves that issue of the button with bwm's
harder steel recipe enabled. It adds a much easier top make some button.
It'll be public shortly and is called Better With Harder Steel Recipe.
