### ISSUE TITLE
Scan Tool doesn't prompt "Point one/two saved" message when used on fence block

### ISSUE THREAD

**Issue by omega025** [ldtteam/minecolonies#1114]
### Minecolonies version

version 0.8.1917

### Expected behavior

- Right-clicking on fence block with Scan Tool should prompt "Point one saved" or "Point two saved" chat message.

### Actual behaviour

- Right-clicking on fence block with Scan Tool appears to register (see below), but no chat message is displayed.
- Right-clicking on another block with the Scan Tool after right-clicking on a fence block prompts a "Point two saved, right click again to save the schematic" chat message.

or

- Right-clicking on a regular block while holding the Scan Tool prompts the "Point one saved" chat message.
- Right-clicking on an oak fence block while holding the Scan Tool prompts no chat message, but right-clicking again prompts the message indicating that the "scan [was] successfully saved".

### Steps to reproduce the problem

1. Build something with an oak fence block in a lower front corner.
2. Equip Scan Tool.
3. Right-click oak fence block while holding Scan Tool.
4. Right-click another block while still holding Scan Tool.

or

1. Build something with an oak fence block in an upper rear corner and a regular block in a lower front corner.
2. Equip Scan Tool.
3. Right-click regular block in lower front corner while holding Scan Tool.
4. Right-click fence block in upper rear corner while still holding Scan Tool.
5. Right-click again to receive notification of successfully saved scan.

**Comment by omega025** [comment]
This also appears to happen with right-clicking on a fence block for point two - no chat message, though right-clicking again prompts a chat message saying that the scan was successfully saved.

**Comment by cltnschlosser** [comment]
Can you confirm that the scan was in fact saved?

**Comment by cltnschlosser** [comment]
Actually was this on a server or single player version of the game?

**Comment by cltnschlosser** [comment]
Its likely that some mod (could but minecolonies, unsure) is cancelling the right click event for fences on the client side (in "remote" worlds). So the following code is never called:
```
            if (worldIn.isRemote)
            {
                LanguageHandler.sendPlayerMessage(playerIn, "item.scepterSteel.point");
            }
```

We should be able to change this to just `if (!worldIn.isRemote)` and be good, since deciding whether to actually send the packet, or add a message to chat is handled by minecraft's code anyway.

**Comment by omega025** [comment]
Can confirm - scans were indeed saved to the minecolonies/scans/new folder.  This was in single-player.

**Comment by Raycoms** [comment]
Okay I checked it, that's not our issue, without any mods this works well for me.
