### ISSUE TITLE
feature request Dman Actually delivers

### ISSUE THREAD

**Issue by abdullamu** [ldtteam/minecolonies#1115]
Since you are working on Dman 2.0 maybe you can add this feature.
you can ask the Dman to deliver certain resources specified by the player using the wand or order item to anywhere the player asks chest or machines, and keep pick certain amount of items from this chest.

this will be useful why, because we can create complex system or auto run colonies .
Example: Dman deliver wood to specific chest or machine or crafter to make axes or pickaxe and Dman can take from the output chest to deliver when its needed. of course you will answer we have the smither planed to do this.
but this is example we can use him for more complex stuff like feeding wood into RF gen to keep it going or coal from miner or take Ores instead of storing them which is useless than player have to open each chest manually find ores go double them, Dman can directly send them off to chest or smeltary if Tconstract integration exist
plus this will allow us to sort items if we ask him to keep only ores in this chest food in other store in other and so on.
thank you for your hard work.

**Comment by AndrewTru** [comment]
@abdullamu This idea is doable to an extent, the team is working on the internal market/request calls and right now the Dman and the new Baker unit are bugging in that the Dman is not keeping the needed items in play for the baker, this may help with that but at the same time we have to pick and deploy what we can,
@Kostronor 
What's your take on this idea, I myself am keeping it on the back burner till we fix more game breaking bugs like the Dman baker interactions.

**Comment by Raycoms** [comment]
Been worked on. Closed in favor of other issue.
