### ISSUE TITLE
Guards attack friendlies

### ISSUE THREAD

**Issue by Diggygoglol** [ldtteam/minecolonies#1119]
### Minecolonies version

Curse version: 0.7.4.2.1

### Expected behavior

- Attack mobs

### Actual behaviour

- attacks mobs and friendly players (Even as officer in town hall)

### Steps to reproduce the problem

1. Build tower
2. hire guard
3. insert friendly
4. Profit

This is a private "LAN" server that this happens on.

**Comment by Raycoms** [comment]
I'm sure you set the guard attack level in the permission to friendly or
even officer...

2017-06-01 20:00 GMT-03:00 Diggygoglol <notifications@github.com>:

**Comment by marvin-bitterlich** [comment]
Everyone with the guard_attack permission will be attacked. Also if you hit a guard he will get revenge for a short time

**Comment by ThomasRunting** [comment]
iam getting the same thing on my server.
where is this guard_attack permission set?

**Comment by Raycoms** [comment]
In each permission tab in each colony there is a "guard attack" config

2017-06-13 10:38 GMT-03:00 Thomas Runting <notifications@github.com>:

**Comment by ThomasRunting** [comment]
Is it this permission?
![image](https://user-images.githubusercontent.com/2153950/27085603-1f27be4c-5093-11e7-917b-f84e23942031.png)

**Comment by Raycoms** [comment]
Yes exactly.

2017-06-13 10:51 GMT-03:00 Thomas Runting <notifications@github.com>:

**Comment by ThomasRunting** [comment]
And that should be off then?

**Comment by Raycoms** [comment]
Exactly.
If you want that your guards don't attack your officers that should be off.

2017-06-13 10:53 GMT-03:00 Thomas Runting <notifications@github.com>:

**Comment by ThomasRunting** [comment]
odd i have it off right now and the guard still attacks.
the game is in peaceful mode if thats affecting it

**Comment by Raycoms** [comment]
Shouldn't affect it, are you the colony owner? (only the owner can
effectively change it)

2017-06-13 10:58 GMT-03:00 Thomas Runting <notifications@github.com>:

**Comment by ThomasRunting** [comment]
i got the owner to change it and it still happens

**Comment by Raycoms** [comment]
You set that option to off for all ranks?

2017-06-13 11:08 GMT-03:00 Thomas Runting <notifications@github.com>:

**Comment by ThomasRunting** [comment]
its off for officer, friend, netural and on for hostile

**Comment by Raycoms** [comment]
that should fix it. Even though the guards will need a bit to lose focus on
you after he turned it off.

2017-06-13 11:17 GMT-03:00 Thomas Runting <notifications@github.com>:

**Comment by ThomasRunting** [comment]
Ah yes it did after a server reload

**Comment by okegima** [comment]
am having the same issue. even after a day, i don't loose the friendly attack. i don't find any setting about owner no attack.

**Comment by Raycoms** [comment]
Are you on the newest version?

2017-08-28 13:34 GMT+01:00 syal <notifications@github.com>:

**Comment by okegima** [comment]
version 1.12.1 - 0.8.3530, forge 14.21.1.2387. I have officier, friend, neutral, hostile : fight guard off. but when am kicking it one, he fight me back, and no way to loos agro exceped to kill or being killed.

**Comment by Raycoms** [comment]
uhm, even if you stay away from him (far enough so that he can't see you)
for around a minute?

2017-08-28 13:38 GMT+01:00 syal <notifications@github.com>:

**Comment by okegima** [comment]
moved away from 215 and wait a full day, once back to the camp, the npc still come to me to fight.

**Comment by Raycoms** [comment]
Uhm, if you move too far away he won't continue ticking to start forgetting
you, try attacking and then moving away 20 blocks waiting a minute and
returning.

2017-08-28 15:09 GMT+01:00 syal <notifications@github.com>:
