### ISSUE TITLE
Deliveryman does not deliver

### ISSUE THREAD

**Issue by wilsondgonzales** [ldtteam/minecolonies#1123]
### Minecolonies version

version 0.8.2020 

### Expected behavior

- Have requests delivered

### Actual behaviour

- Lumberjack requests for an axe.
- Dman does his rounds and 'gathers' warehouse items
- Then does a few gathering rounds and puts the item back in the warehouse
- The dman even indicates he holds the axe but left turns into the warehouse to put it back. He never shows a 'delivering' state'. He only shows gathering and dumping states

### Steps to reproduce the problem

1. take teh axe from the lumberjack so he requests for one

**Comment by Asherslab** [comment]
yeah, that's all part of the upcoming DMan 2.0 (https://github.com/Minecolonies/minecolonies/pull/1001) , which OrionDevelopment is working on. Hopefully it will be ready soon.

**Comment by marchermans** [comment]
Actually this not something i did.
No part of the DMan it self is in.
@xavierh @cltnschlosser did any of you guys not update the dman lately to make him more efficient?

**Comment by Asherslab** [comment]
My bad, sorry.

**Comment by marchermans** [comment]
No Problem. The DMan 2.0 Is currently just a finished API, which is being integrated into the new Minecolonies API. Once the Integration is done, release of the actuall implementation should go quickly

**Comment by Raycoms** [comment]
Colton did it, but for 1.11 only, he has to port it still.

2017-06-04 4:13 GMT-03:00 Marc Hermans <notifications@github.com>:

**Comment by Raycoms** [comment]
This should work, please if this still occurs with the latest 1.10 and 1.11 reopen.
