### ISSUE TITLE
1.11.2 builder not building but uses the resources

### ISSUE THREAD

**Issue by Jay9519** [ldtteam/minecolonies#1125]
### Minecolonies version

minecolonies-universal-1.11.2-0.8.1784
Forge-1.11.2-13.20.0.2310-universal

### Expected behavior

Start a building project, a builders hut

### Actual behaviour

when I start the project and add all the required materials into the hut's inventory
The builder collects the items and starts working on the build.
but no blocks are breaking for the ground and no blocks are being placed by the builder but the resources are being used up.
the builder says the build is complete and restarts it all over again and uses more resources

### Steps to reproduce the problem

start building a builder's hut

**Comment by Raycoms** [comment]
Are you using any additional mods?

**Comment by H3roDude** [comment]
i remember that this was a bug in 1.10 too and already fixed some time ago
like 1-2 month

**Comment by Raycoms** [comment]
Should be fixed if you add "EntityCitizen" as allowed griefer in the config
