### ISSUE TITLE
The builders aren't changing blocks.

### ISSUE THREAD

**Issue by PerksPrisoner** [ldtteam/minecolonies#1126]
1.11.2-0.8.1784 Minecolonies version

version 1.11.2

### Expected behavior
That the NPC would alter blocks, add blocks.

### Actual behaviour

 The NPC seem to be doing just that, however they don't physically change the block, the particles show them breaking blocks, they hold the tools, blocks, and show they are using them. But nothing changes in the world. Please help. The owner and I are stumped.

### Steps to reproduce the problem

1. Place the City Hall
2. Place "Builders Hut"
3. Click "Build Building"
4. Supply with tools
5. Supply Items
6. Blocks don't change

![2017-06-03_10 34 30](https://cloud.githubusercontent.com/assets/22648457/26755712/5b1ea6e8-4848-11e7-8f00-6c2735a5d03b.png)
![2017-06-03_10 34 35](https://cloud.githubusercontent.com/assets/22648457/26755713/5b1f90e4-4848-11e7-9361-f9292938f371.png)
![2017-06-03_10 34 42](https://cloud.githubusercontent.com/assets/22648457/26755714/5b213fac-4848-11e7-87ba-011da1614aa7.png)
![2017-06-03_10 35 33](https://cloud.githubusercontent.com/assets/22648457/26755716/6585bdd8-4848-11e7-9421-0b1a28c6b559.png)

**Comment by Raycoms** [comment]
What kind of additional mods are you using? Are on a server or in single
player?

2017-06-03 14:30 GMT-03:00 PerksPrisoner <notifications@github.com>:

**Comment by PerksPrisoner** [comment]
This is a sponge server that has "Sky Block", "Dropper", "Vanilla Survival" and "Vanilla PvP"  I have included a snapshot of the complete mods list.

Also if you need to try them out for yourself on a server.... As solo works fine. I assume you have a test server here is the direct link to our modpack collection so you may download it as the server has, as well as the other players.

[http://ozservermc.com.au/showthread.php?tid=151](url)

![capture](https://cloud.githubusercontent.com/assets/22648457/26757470/f1144a54-4870-11e7-9899-26723295ec55.PNG)

**Comment by Jay9519** [comment]
same server as Issue #1125 
I noticed this showing up in the console


[minecolonies]: ForgeHook not in sync with EfficientTool for Block{minecraft:tallgrass} and 32xtile.dirt@0
Please Report to MineColonies with this text to add support!

**Comment by Jay9519** [comment]
no acknowledgement that you've seen our replies? would be nice that you have seen it at least :(

**Comment by Raycoms** [comment]
Sorry, have been working on other issues. Can you confirm that this also
happens without any other mods?

2017-06-04 16:25 GMT-03:00 Jay9519 <notifications@github.com>:

**Comment by xavierh** [comment]
And log file too from the server side.

**Comment by PerksPrisoner** [comment]
@Jay9519 Would have to confirm server side, but I can tell you that it is only happening in the server. Solo works fine, private servers, it is only live servers apparently. But I don't know the full details.

**Comment by Raycoms** [comment]
do you have some kind of anti griefing protection?

2017-06-04 23:22 GMT-03:00 PerksPrisoner <notifications@github.com>:

**Comment by PerksPrisoner** [comment]
Just the FTB Lib, FTB Utilities... But once again it doesn't stop it in any other situation, that was our assumption at the start as well.

**Comment by Raycoms** [comment]
They are able to remove but not to place?

2017-06-04 23:33 GMT-03:00 PerksPrisoner <notifications@github.com>:

**Comment by PerksPrisoner** [comment]
They aren't able to do either.

**Comment by Raycoms** [comment]
Then I believe it is the anti griefing protection. Can you try it without
ftb utilities?

2017-06-04 23:37 GMT-03:00 PerksPrisoner <notifications@github.com>:

**Comment by PerksPrisoner** [comment]
I'll see what we can do with this and check back with you with an update.

**Comment by Raycoms** [comment]
Great =)

2017-06-04 23:40 GMT-03:00 PerksPrisoner <notifications@github.com>:

**Comment by PerksPrisoner** [comment]
That hasn't effected the outcome... They still are unable to break/place

**Comment by Raycoms** [comment]
Nothing great, can you post in the complete latest.log and
fml-server-latest.log ?

2017-06-04 23:48 GMT-03:00 PerksPrisoner <notifications@github.com>:

**Comment by PerksPrisoner** [comment]
While I wait to see if the owner can get it uploaded, I took a couple screen shots the help you see what the issue is physically. To add context. If you build the building. The workers take up the jobs and will perform them. But they are simply unable to break/place. I don't know if they will help. But meh, something besides words to look at.

![2017-06-04_19 49 40](https://cloud.githubusercontent.com/assets/22648457/26768807/3ece8766-495f-11e7-9e4c-c760385f22a0.png)
![2017-06-04_19 49 57](https://cloud.githubusercontent.com/assets/22648457/26768806/3eb89bae-495f-11e7-808a-6220e1054818.png)

**Comment by Jay9519** [comment]
latest.log file   -   https://pastebin.com/UcpbnDxN

fml-server-latest.log Part1  -  https://pastebin.com/KbEAjweX

fml-server-latest Part2  -  https://pastebin.com/VezqzVn8

sorry the file was too large and i'm not a pro user of pastebin

**Comment by PerksPrisoner** [comment]
Also, there are few players mentioning some placement issues with placing the supply camp, it requires 1 block above ground such as a Grass block but not on dirt covered with grass. (i.e Grass, Tall Grass) also them not placing with nothing around them.

**Comment by Amadeus99** [comment]
I don't know the code so I don't know if this matters, but you are not trying to build in the spawn area, are you?  The spawn area is usually protected unless changed in server.properties.

**Comment by Jay9519** [comment]
It is over 1000 blocks from spawn and in multiple locations from every player

**Comment by Amadeus99** [comment]
FYI, I installed the mod pack via the Twitch(Curse) client, made a Forge server out of it (not a sponge server) and then logged in and the builder was able to break and place blocks just fine.  I've never used sponge so I don't know what is different.

**Comment by Jay9519** [comment]
The wiki says it works with sponge
http://wiki.minecolonies.com/wiki/18/server

**Comment by Raycoms** [comment]
It works for us with sponge, are you using red-protect?

2017-06-05 7:16 GMT-03:00 Jay9519 <notifications@github.com>:

**Comment by Jay9519** [comment]
No im not using red-protect

**Comment by Jay9519** [comment]
Same issue as #1031

Was that one solved?

**Comment by Raycoms** [comment]
#1031 <https://github.com/Minecolonies/minecolonies/issues/1031> doesn't
cause this kind of a problem. Its really only spam in 90% of the cases.

@Kostronor do you have any idea?

2017-06-05 10:07 GMT-03:00 Jay9519 <notifications@github.com>:

**Comment by Asherslab** [comment]
Can i ask what all the plugins are that you're using?

**Comment by Jay9519** [comment]
They are all listed at the start of this conversation

**Comment by Raycoms** [comment]
Should be fixed if you add "EntityCitizen" as allowed griefer in the config
