### ISSUE TITLE
Support colonies in other Dimensions

### ISSUE THREAD

**Issue by Neoletum** [ldtteam/minecolonies#1127]
### Minecolonies version

version 1.11-0.6.3360

### Expected behavior

- Interacting with Town Hall to start a Colonie on Mars in Galacticraft Vers. 1.11.2-4.0.0.101

### Actual behaviour

- Town Hall is locked, can't interact with it, only sends: 
   "You don't have persmissions to interact with this...." 
   MineColonie Version 1.11-0.6.3360

Hello everyone,
I started Minecraft with Minecolonie and Galacticraft and everything works well on "Earth" but when I
landed on Mars i could place a town hall but everytime I tried to interact with it it just said
"You don't have the permission to do that..."

Does anyone here have an idea how to solve this problem?

I hope someone could help me and sorry for my bad english ^^

**Comment by Raycoms** [comment]
Minecolonies only works in the overworld dimension. I bet it will run into
problem on mars and similar

2017-06-03 17:05 GMT-03:00 Neoletum <notifications@github.com>:

**Comment by Neoletum** [comment]
But there was a User who allready created a colony in an older version:

http://www.minecolonies.com/publicforum/m/18051739/viewthread/12333334-minecolonies-in-space/post/66945813#p66945813

Greets

**Comment by Raycoms** [comment]
That's interesting, you could try to execute /mc colony refresh
yourcolonyId -> which you can get from /mc colonies list -> which might
solve your problem

2017-06-03 17:30 GMT-03:00 Neoletum <notifications@github.com>:

**Comment by Neoletum** [comment]
https://cloud.githubusercontent.com/assets/29167228/26757031/527c0b58-48b0-11e7-9d5e-02d3f079fecb.png

Doesn't work for me, it doesnt identify me as a player
But thank you for your idea =)

**Comment by Raycoms** [comment]
try to delete it with /mc colony delete 1 and /mc colony delete 2 and then
try to place a new townhall. Did you place it with or without the build
tool?

2017-06-03 18:02 GMT-03:00 Neoletum <notifications@github.com>:

**Comment by Neoletum** [comment]
Tried it again, first time with the build tool and second time I just placed it and deleted the ID's but it wont work - a pity... I hoped i could create a colony on the moon but there is a conflict with the dimension and the player ID I think

**Comment by Raycoms** [comment]
Can you change this title to "Minecolonies support other dimensions"
because we don't really support the placing in other worlds yet.

**Comment by ghost** [comment]
Good thing I checked before trying to colonize the End.

**Comment by Auriel1** [comment]
Previously used version : minecolonies-universal-1.10.2-0.8.1772.jar
Actual used version :       minecolonies-universal-1.12.1-0.8.4075.jar

Now I understand why my workers won't spawn after I place a new town hall..

In my previous server modpack, I had created a creative map in the "Simple void world" dimension (43).  In it, I was able to build every building of every style, it remained in me only a part of the stones buildings..

New server and modpack in 1.12.1, and I thus took back this map, but surprised, after having placed the townhall, nobody appeared...


So yes in older versions, nothing prevented us from making a colony in another dimension. Moreover, at no time we were told in the wiki that it was impossible, becauseit was totally feasible.

**Comment by Raycoms** [comment]
The problem is, that in SMP this crashes the server completely so we built
a killswitch for not overworld dimensions. Nevertheless, in one of the next
updates this will change already.

2017-10-11 18:16 GMT+01:00 Auriel1 <notifications@github.com>:

**Comment by Raycoms** [comment]
Done
