### ISSUE TITLE
[feature request] config option for villagers to ignore bad weather

### ISSUE THREAD

**Issue by Zygus42** [ldtteam/minecolonies#1134]
The villagers don't work on days when it's raining, and while this is not a major issue usually, we're currently playing with a mod that has long seasons of rain and snow, and it makes this mod essentially impossible.  Would be nice to have an option in the config to have them ignore bad weather conditions.

**Comment by Thomasdavid097** [comment]
upgrade the huts to level 5, they ignore the rain.

**Comment by SulpherStaer** [comment]
A toggle option in the config file would be nice though.

**Comment by Zygus42** [comment]
Yes, know about the huts, but it would take months of playing to get to that point because of the rain and snow.

**Comment by Zygus42** [comment]
I have suggested in the past that you could maybe give them some item that would let them work in the rain - a raincoat or umbrella or somesuch.
