### ISSUE TITLE
cras hwhen upgrading bakery

### ISSUE THREAD

**Issue by H3roDude** [ldtteam/minecolonies#1135]
it seems that the baker dont like when his furnace is breaked from the builder while used.
The server crashed when the builder is upgrading the bakery hut

[crash-2017-06-06_19.24.45-server.txt](https://github.com/Minecolonies/minecolonies/files/1055937/crash-2017-06-06_19.24.45-server.txt)

**Comment by xavierh** [comment]
Why did you close it?
