### ISSUE TITLE
Request: Allow multiple workers per building

### ISSUE THREAD

**Issue by Galindorf** [ldtteam/minecolonies#1140]
It would be great if we could assign more than 1 person per building, like having 3 builders working or two farmers farming from the same hut. Building is pretty slow going sometimes, and it would be very useful to take someone off say, fishing, and put them  up to helping build!

**Comment by Raycoms** [comment]
Just place more of the buildings and built them.
Assigning several to one building would be just the lazy, less gameplay way to go.
(Warehouse has multiple workers assigned to it btw)

**Comment by Shrooblord** [comment]
What is your stance on this now? Do you still feel the same? I find it weird that you can assign multiple farms to one farmhouse, but not have multiple farmers working at one farmhouse, for example. Thoughts?

**Comment by Shrooblord** [comment]
What is your stance on this now? Do you still feel the same? I find it weird that you can assign multiple farms to one farmhouse, but not have multiple farmers working at one farmhouse, for example. Thoughts?
@Raycoms

**Comment by MokahTGS** [comment]
I would like to see this implemented as an option myself.  Seems odd that you can't have multiple employees of a building.  Really this should go for all building types.

**Comment by Nightenom** [comment]
Not sure about Raycoms's opinion now, but it probably did not change and I agree with that unless the building allows it by purpose (like a library)

**Comment by Raycoms** [comment]
Yeah, if we have this then we have it on purpose as library or barracks. We won't enable this for all buildings since it can cause a lot of weird issues and quite often only cost computation power without giving you more return.

**Comment by MokahTGS** [comment]
OK, thanks for the answer on this.  Totally understandable with CPU drag as an issue.
