### ISSUE TITLE
Colonist don't build with a permissions mod installed

### ISSUE THREAD

**Issue by Jay9519** [ldtteam/minecolonies#1141]
### Minecolonies version

minecolonist-universal-1.11.2-0.8.1784

### Expected behavior

The builder build the townhall

### Actual behaviour

The builder collects items from the builders hut and walks over to the town hall.
he does the actions of building but no blocks are removed/placed
he does use the items however

### Steps to reproduce the problem

install minecolonies mod 1784
install nucleus mod 29.4
install luckperms mod 3.2.7

**Comment by Raycoms** [comment]
Normally you should not need a permission mod with minecolonies since
minecolonies has his own anti griefing systems already.

2017-06-08 0:33 GMT-03:00 Jay9519 <notifications@github.com>:

**Comment by Jay9519** [comment]
I agree, I even have the minecolonies protection turned off.
I will try a different essentials mod when I get home and see if I get the same result

**Comment by Jay9519** [comment]
so I deleted the nucleus essentials mod and installed a different one
and now they are building, no idea how or why but it's working so it's all good :)

**Comment by Raycoms** [comment]
Great!
Unfortunately, we're not able to do much there, those anti-griefing mods have to allow us.
Nevertheless, that's why we added our own anti-griefing system.

**Comment by Jay9519** [comment]
Out of curiosity, how many lols can you upgrade the buildings like the town hall for example? I've only seen on forums up to lvl4 but that was a few years ago it was posted

**Comment by Raycoms** [comment]
All buildings up to level 5.


I think we can close this here.

**Comment by Jay9519** [comment]
Levels not lols omg haha
