### ISSUE TITLE
Colonists warn they need to eat even when food is available.

### ISSUE THREAD

**Issue by harleypig** [ldtteam/minecolonies#1146]
### Minecolonies version
minecolonies-universal-1.11.2-0.8.1784

### Expected behavior
A colonist warns they are about to starve when there is no food available. If there is food available then they don't say anything.

### Actual behaviour
Colonist warns they are saturated, but will soon have to eat again. Even if there is food in the warehouse.

### Steps to reproduce the problem

1. Build the appropriate buildings.
2. Put food in the warehouse.
3. Wait.
4. Listen to colonists warn you.

**Comment by Asherslab** [comment]
Do you have a Deliveryman? and is he putting the food in the citizen's chests?

**Comment by jzburda** [comment]
@Asherslab I have a deliveryman, he might be way behind on work but the citizens will still complain about being saturated.

**Comment by harleypig** [comment]
Yes, I have two actually. They do deliver food. But if they fall behind, and at this level this happens frequently, the colonists will complain.

**Comment by Raycoms** [comment]
I think this is quite okay.
its still only some chat you know you can ignore if you have deliveryman,
but if they talk you know that you can get them more efficient if you
deliver it at night yourself.

2017-06-14 14:08 GMT-03:00 Alan Young <notifications@github.com>:

**Comment by harleypig** [comment]
Fair enough. I'll close this issue then.
