### ISSUE TITLE
[New Workers] Enchanter

### ISSUE THREAD

**Issue by pmardle** [ldtteam/minecolonies#115]
Enchanter

So the concept of the enchanter is to provide enchants that the player can use, or use on tools for the workers.

The way the Enchanter will work is.

1) "Ancient Tome" will be a new Item that will be a rare drop from all mobs in game, and a uncommon drop from Barbarians (Higher drop rate from the chief please) - Think 1 in 100 from regular mobs, 1 in 20 from a barbarian, and 1 in 5 from the chief.

![ancienttome](https://cloud.githubusercontent.com/assets/21060710/18343974/683b61ae-75ad-11e6-8445-7c5caf2d4682.png)

The Ancient Tomes go to the enchanter, who will "Cook" them in a restyled furnace - This will be designed as an enchantment table, but made to look like a research bench (we can use the enchantment table model and re-texture - the floating book should stay)

So the ancient tome goes in and a re-agent is added (coal) - This can be 1 of the following.

1) Block of Coal (Needs Enchanter Level 1 Building)
2) Block of Lapis (Needs Enchanter Level 2 Building)
3) Block of Diamond (Needs Enchanter Level 3 Building)
4) Block of Emerald (Needs Enchanter Level 4 Building)

The Ancient Tome is cooked using one of these reagents (1 book cooked per block of reagent over 30-60 seconds)

The output is an enchanted book, which has a completely random enchant form all available in game.

The level of that enchant will depend on the reagent used and the skill of the enchanter

Coal = Rnd (1-2) + ((0.5 \* Enchanter Level)/10) = 0.05 to 5 (i.e. Level 1 to 5 enchants)
Lapis = Rnd (2-3) + ((0.5 \* Enchanter Level)/10) = 2.05 to 5.5 (i.e. Level 2 to 5 enchants)
Diamond = Rnd (2-5) + ((0.5 \* Enchanter Level)/10) = 3.05 to 7.5 (i.e. level 2 to 7 enchants)
Emerald = Rnd (2-7) + ((0.5 \* Enchanter Level)/10) = 3.05 to 9.5 (i.e. level 2 to 9 enchants)

This therefore creates an Enchanted book anywhere from level 1 to 9 depending on RND and Hut and enchanter level.

I'm keen this doesn't become too OP, so I think the player should still have to pay levels to apply these enchants via an Anvil in the usual manner.

Being able to give all your guards Sharpness 9, Fire Aspect 9, Unbreaking 9 swords, plus protection 9 armour will be OP enough ;)

We can of course tone this down to only give 1-5 enchants if people think this is still OP :D

**Comment by Raycoms** [comment]
How I will do this:
- [x] Config of enchantments with hut levels 1-5
- [x] Which one is actually applied to the tome and transforms it into a book is actually random.
- [x] Enchanter doesn't gain experience, he burns it.
- [x] Level 1 enchantments cost 1 level, level 2 costs 2, level 5 costs 5
- [x] Player can choose in a list of which workers the enchanter is allowed to suck experience and how much (1 level per day, 2 levels per day, 3, etc)
- [x] So enchanter goes to one of these worker huts, wait there some time until the worker shows up (max time of x, if doesn't show up he tries next)
- [x] When he sees the worker he sucks out the level (some nice particle effect between the two)
- [x] Goes back to hut and requires a certain time to produce tome to enchantment book
- [x] He always guarantees to have buildingLevel levels on him to produce a book of possibly the highest level.

**Comment by Nightenom** [comment]
Regarding transformation I would go with:
hut level 1-3 will produce results as the enchanting table with 1-3 lapis
hut level 4-5 will produce stronger things than the enchanting table can
- level 4 - allows up to 4 enchantments at somewhat random but higher levels
- level 5 - 5 enchantments at max vanilla level

Maybe create some kind of different anvil which can consume our books so the price for combining will only be based on what enchantments from the book are used? Idk if vanilla already does that or if there is some kind of event for this

**Comment by Raycoms** [comment]
We can just remove the book from the inventory the moment we add the new enchantment book.
I thought about going the vanilla way, but I don't like this particularly because our enchanter will use essentially less experience levels, so there should only be 1 enchantment per level.

I can check if vanilla gives me a nice way of ordered enchantments so I can cut them into building levels. Else, I really like to allow the player to configure the maximum of the things.

So making the default config based on vanilla allows modpack makers to extend on top of that.

**Comment by Raycoms** [comment]
- [x] Randomly enchants workers tools when sucking XP (higher building level higher chance)

Building adjustment:
- [x] we can allow level 1 enchants besides mending at any level, and mending only level 3+, and then everything above level 1, adds 1 level

**Comment by Asherslab** [comment]
I dunno why, but I kinda want the model for the enchanted to include two (one on left and right) glass “jars” on his back like a backpack, and when he sucks up experience those fill up with experience “juice”.

Also maybe ghost busters style vacuum  cleaner for grabbing experience from workers. Lol

**Comment by ravenbuilder934** [comment]
Can we change the texture for the enchanter to have the glass jars like @Asherslab said? That would be so cool (and funny)! Plus, right now they just look like the library students, so they need their own texture. :)
