### ISSUE TITLE
Miner problem - I need a hut level Stone to handle stronger pickaxes.

### ISSUE THREAD

**Issue by DestinyPlayer** [ldtteam/minecolonies#1161]
### Minecolonies version

version 0.8.1784

### Expected behavior

- Miner should mine if I tell them to mine on a certain level.

### Actual behaviour

- The miner returns to their Miner block, and constantly spouts "I need a hut level Stone to handle stronger pickaxes" even though they have a stone pickaxe on a level 2 hut.

### Steps to reproduce the problem

1. Build a Miner hut
2. Let the miner dig down a few levels
3. Tell them to mine on a specific level
4. Look at them be confused

**Comment by Raycoms** [comment]
Probably he needs an iron pickaxe or diamond pickaxe.
@Xavier this message seems slightly bugged

2017-06-12 12:26 GMT-03:00 DestinyPlayer <notifications@github.com>:

**Comment by xavierh** [comment]
Will have a look.

**Comment by DestinyPlayer** [comment]
Didn't work. I gave the miner a stronger pickaxe, they're still standing there spouting the same exact phrase.

**Comment by Raycoms** [comment]
Yeah the pickaxe they need is too weak for the hut level. You have to
upgrade the hut.

2017-06-12 12:31 GMT-03:00 DestinyPlayer <notifications@github.com>:

**Comment by DestinyPlayer** [comment]
Upgraded the hut. Now they're spouting "I need a hut level Iron to handle stronger pickaxes" even though I gave them an iron pickaxe.
And no, there don't appear to be any blocks that are unbreakable by an iron pickaxe in the way.

**Comment by Raycoms** [comment]
try to upgrade once more please. the message seems confusing though.

2017-06-12 12:34 GMT-03:00 DestinyPlayer <notifications@github.com>:

**Comment by xavierh** [comment]
My bad will fix this asap, is it 1.10 or 1.11 (probably both)

**Comment by DestinyPlayer** [comment]
Okay. I upgraded it to the maximum level. The miner requested a diamond pickaxe. I gave it to them, and now they're just standing in front of the block, doing nothing. I fired and re-hired them, I recalled them a bunch of times. I still need to wait for the night, but they're standing still for now, now silent.

**Comment by xavierh** [comment]
Which version is it ? 1.10 or 1.11

**Comment by xavierh** [comment]
And is it a release version or testing ?

**Comment by DestinyPlayer** [comment]
1.11.2
The latest one on Curse, 0.8.1784
Also, waited for the night and then morning. The miner just kept standing in the townhall even though it was day already. Didn't start working even after recall.

**Comment by xavierh** [comment]
AFAIK the problem is fix but did not reach curse yet

**Comment by DestinyPlayer** [comment]
OK. If I may ask, what was the problem? Pure curiosity.

**Comment by xavierh** [comment]
more than on things: for a start it should ask say "I need a hut level 2 to handle stronger pickaxes"

**Comment by xavierh** [comment]
worker may ask for tool that they can not use too. I reworked all of those to be consistent between workers too. now the farmer can not use diamond hoe without the correct hut level and enchantment are taken into account too now for instance at level 2, the worker can use:

- wood pickaxe with efficiency 2
or
- stone pickaxe with efficiency 1
or
- iron pickaxe with no enchantment

Also the dman should be able to deliver the correct tools i.e. he will no longer deliver a diamond pickaxe if the worker can use up to iron pickaxe

**Comment by xavierh** [comment]
As for your worker not working even with the diamond pickaxe, does he need feeding too ?

**Comment by DestinyPlayer** [comment]
Nope, I fed them, and even then they were doing that even before they started saying "I'm quite saturated, but I'll have to eat soon again".

**Comment by xavierh** [comment]
Cobblestone?

**Comment by DestinyPlayer** [comment]
Cobblestone, stone, granite in a few places.
Or, if you meant the hut itself, yes, built of cobblestone.

**Comment by xavierh** [comment]
I mean does he have cobblestone in his inventory.  It use to fail to ask
for it

**Comment by DestinyPlayer** [comment]
Okay. They did not, and the moment I gave it to them they started mining. Weird. Thank you for your help.

**Comment by xavierh** [comment]
The cobblestone problem already have been fixed, it will come in the next version
