### ISSUE TITLE
Builder won't place furnace for T2 Town Hall

### ISSUE THREAD

**Issue by jzburda** [ldtteam/minecolonies#1166]
### Minecolonies version

version 0.8.2292 or curse X.X.XX

### Expected behavior

- Builder should place furnace and continue building town hall T2

### Actual behaviour

- Builder sits in a corner with the Furnace placed in his hand doing nothing

### Steps to reproduce the problem

1. Build Town Hall tier 2
2. Wait for Builder to get a furnace
3. Watch him lazily walk to a corner of the build site
4. ...
5. Profit

**Comment by FiveEYZ** [comment]
same thing happen for me, but i also have a NPE spamming in console while its happening

https://gist.github.com/FiveEYZ/b8a3aad14b4936688c37c805bddc8c53

**Comment by jzburda** [comment]
I don't have a console, so I couldn't see that
thanks for the feedback though.

**Comment by Raycoms** [comment]
Will try to reproduce this.

2017-06-12 20:58 GMT-03:00 Henric Backman <notifications@github.com>:

**Comment by FiveEYZ** [comment]
i would upload the `fml-server-latest.log` if it wasn't 30 MB already, so i only included that error :P

the NPE will spam in console until the item they are supposed to place, are removed from their inventory (they then need to go check the builder's hut for said item and request it),
or the work order is canceled.

**Comment by FiveEYZ** [comment]
will this fix https://github.com/Minecolonies/minecolonies/issues/1167 to?

**Comment by xavierh** [comment]
Yes. It does
