### ISSUE TITLE
Above Standard definition textures break UI

### ISSUE THREAD

**Issue by RyderOfNitor** [ldtteam/minecolonies#1169]
### Minecolonies version

version 0.8.2368 or curse X.X.XX

### Expected behavior

- colonist GUI show food, hunger and exp bar:
![image](https://user-images.githubusercontent.com/13579373/27070868-158bafc2-505e-11e7-88cf-6235be6fbcaf.png)

### Actual behaviour

- foo, hunger and exp display badly:
![image](https://user-images.githubusercontent.com/13579373/27070944-5b0eb850-505e-11e7-9f67-9104132d0e74.png)

### Steps to reproduce the problem

1. Install texturepack with definition of x128
2. launch minecraft
3. Interact with colonist
4. Profit

**Comment by Raycoms** [comment]
We take those textures directly from the minecraft textures, so if the texture pack does something fuzzy with those standard textures and does not replace it at the exact same spot with something good, we unfortunately can't do anything to support this.
