### ISSUE TITLE
[Feature] Outposts

### ISSUE THREAD

**Issue by kreezxil** [ldtteam/minecolonies#1175]
I have an idea: outpost block, gives you 20 block radius protection, can't be placed within 1000 blocks of any townhall. You can build w/e you want it. Probably has it's own cadre of npcs as you wouldn't want the main town npcs traveling 1000's of blocks.
[2:22 PM] H3roDude: like a second small townhall?
[2:23 PM] Kreezxil: yeah but call it an outpost
[2:24 PM] H3roDude: outpost is for me only gaurds lol
[2:24 PM] Kreezxil: maybe it has limits, like 1 citizen hut, 2 guard towers, and one of either a miner or lumberjack

**Comment by Asherslab** [comment]
Sounds like a great idea, ESP for like a little Lumberjack outpost in the middle of a forest, while your colony is way further out. Maybe also a specialized "Trader" like the D-Man except he only goes between the Main Colony and the Outpost getting tools and bringing back resources and such.

**Comment by purestone9** [comment]
It would also be nice if they were able to interact with something like a mine cart.
They could use it to transport materials between colony and outpost.

**Comment by Raycoms** [comment]
When we add that, I think we would make it that you would have a building
which transfers it slowly to a building in your colony

2017-06-16 14:57 GMT-03:00 purestone9 <notifications@github.com>:

**Comment by purestone9** [comment]
Maybe a higher level warehouse?

**Comment by Raycoms** [comment]
Closed in favor of joint issue.
