### ISSUE TITLE
Builder not affecting the world

### ISSUE THREAD

**Issue by WindRider739** [ldtteam/minecolonies#1178]
### Minecolonies version

version 1.10.2 - 0.8.1917

### Expected behavior

Builder should be able to place the blocks that he asks for, and then have them appear in the world.

### Actual behaviour

Builder removes the blocks from the builder's table, carries them to location, places them which removes them from his inventory, but they do not appear. Additionally, builder will break blocks that are in the way when building, the blocks will appear in his inventory, but the blocks are not removed from the world. However, in both cases, the builder believes he has completed his task.

### Steps to reproduce the problem

I have enabled the following line in Nucleus - a forge essentials replacement. When this value is changed to false, builder may then work as intended.

        **# If true, mob griefing will be disabled except for the entities listed in the whitelist (which should be done by mob ID).
        enable-protection=true
        whitelist=[]**

Mods like Minecraft Comes Alive and Minions are not affected by this, and can edit the world as intended almost as though they have some sort of override for this. Whether this is intentional or not, I do not know.

Upon doing about 30 minutes of intense googling and backreading through various forums, I've found no one with the same issue, and no listed mob id to enter into the whitelist. Have I missed something? I would just leave the variable as false, but it's necessary to prevent other mobs from messing with the world, now.

**Comment by Raycoms** [comment]
Try to add EntityCitizen to this white list.

**Comment by WindRider739** [comment]
This worked perfectly, thank you.

**Comment by Asherslab** [comment]
Close the issue?
