### ISSUE TITLE
 Crafting bug in version 1.11.2 (only happens in SMP,SNP is no problem)

### ISSUE THREAD

**Issue by qaz84904** [ldtteam/minecolonies#1181]
### Minecolonies version

version 1.11.2

### Expected behavior

Get supply chest, and it can be used

### Actual behaviour

Supply chest is not be crafted

### Steps to reproduce the problem

1. Put crafting items into a crafting table
2.  Supply chest appears, and clicks it into our bag.
3. Suddenly, 5 wooden boats appears, and they don't become the supply chest.
4. Bug Youtube video link
https://www.youtube.com/watch?v=2Lwnw_l_7rQ&feature=youtu.be

**Comment by Raycoms** [comment]
Can you give us a list of mods you have installed?

2017-06-14 11:20 GMT-03:00 qaz84904 <notifications@github.com>:

**Comment by qaz84904** [comment]
I only install this mod.

**Comment by Raycoms** [comment]
can you send us your minecolonies server config?

2017-06-14 11:31 GMT-03:00 qaz84904 <notifications@github.com>:

**Comment by qaz84904** [comment]
ok.
I found the problem.
I want supply chest to use more than once, so I change allowInfiniteSupplyChests=true.
I should not change the config, thank you for reminding me of config.
