### ISSUE TITLE
Lost all items in warehouse (newest beta)0.8.2488

### ISSUE THREAD

**Issue by lunadragnstar** [ldtteam/minecolonies#1185]
Minecolonies version 1.11.2-0.8.2488

### Expected behavior

- I expected that all the items that I traded with the deliveryman would be in the warehouse

### Actual behavior

- All of the chests were empty

### Steps to reproduce the problem

1. Give items to deliveryman while they are running around
2. Check the werehouse chests

**Comment by Raycoms** [comment]
Should be fixed in the newest version, sorry for that
