### ISSUE TITLE
[Feature] Buildable town border

### ISSUE THREAD

**Issue by kreezxil** [ldtteam/minecolonies#1188]
I see that something similar was discussed #888. My idea is that when you start your builder for the first time there is an option to have him build the town border.

It could be like this for tiers.

1. Builds 3 block high pillars of a block type every 10 blocks on the perimeter except in water. The pillars would have 4 torches each on the top block.
1. Adds fences of a type along the perimeter between the pillars, leaving gaps midway on each segment to allow passage of entities. Every so many fences a torch is placed on top.
1. Finishes filling in the fences. Adds gates in the four cardinal faces. Again with torches as needed.
1. Replaces everything with a grand wall, 3 blocks tall, with a walking platform all the way around. Gates are replaced with double doors. And torches placed at least every 7 blocks on top of the wall.
1. Final tier, wall expanded to have places to hide behind for protection while firing arrows. Stairs are added so guards can get on top of the wall.

**Comment by Raycoms** [comment]
I like that idea

**Comment by Asherslab** [comment]
my question is where does the GUI for upgrading from tier to tier go, do we put it in the Town Hall (That seems smart by me, since there can only be one TH)

**Comment by lunadragnstar** [comment]
I just hope I don't try this since I changed the size of my city.

**Comment by WORMSS** [comment]
Town hall does mean the most sense, especially since this is what the village is centred on.

**Comment by Wissi** [comment]
Nice idea of a Perimeter wall. 
Many will want to choose the blocks to be used as well as the design.

Solution for blocks to be used:
There could be an option for the builder to ask for the block to use (f.e. Cobble, stone, modded blocks, etc) upon request to build the perimeter wall.
I think that would have a broader acceptance for all players in general.

And for the design aspect, same approach so it can have diff blocks in design as they level it up.
It can be higher or thicker wall w/diff materials per Level (if player decides to use a diff block type for next level "layer"?)

**Comment by MineShadow7** [comment]
Possibly can be combined with issue #332

**Comment by Raycoms** [comment]
Closed because this doesn't make a lot of sense with dynamic borders anymore. I got this border block issue open which is probably the better solution for this.
