### ISSUE TITLE
[1.11.2-0.8.2488] Builder won't specify what kind of button he wants

### ISSUE THREAD

**Issue by jzburda** [ldtteam/minecolonies#1190]
### Minecolonies version

version 0.8.2488

### Expected behavior

- Miner should specify what kind of button he wants

### Actual behaviour

- Miner specifies they just want "X BUTTON"

### Steps to reproduce the problem

1. Build Guard post Tier 2
2. Wait for Builder to get to button
3. ...
4. Profit

**Comment by Raycoms** [comment]
The next update will have an icon in the gui of the builder

**Comment by jzburda** [comment]
Oh alright
