### ISSUE TITLE
[1.11.2-0.8.2488] Deliveryman hangs if there is more than one stone pickaxe in warehouse

### ISSUE THREAD

**Issue by jzburda** [ldtteam/minecolonies#1191]
### Minecolonies version

version 0.8.24888

### Expected behavior

- Deliveryman should bring pickaxe to miner

### Actual behaviour

- Deliveryman sits in the warehouse all day and night if there's more than one in the warehouse.

### Steps to reproduce the problem

1. Build miner hut
2. Wait for miner to ask for a stone pickaxe
3. Have more than one stone pickaxe in the warehouse
4. ...
5. Profit

**Comment by Raycoms** [comment]
Does this still happen with the newest version?
If yes please reopen
