### ISSUE TITLE
[1.11.2-0.8.2488] Builder committed suicide building warehouse

### ISSUE THREAD

**Issue by jzburda** [ldtteam/minecolonies#1192]
### Minecolonies version

version 0.8.2488

### Expected behavior

- Builder should build warehouse without jumping off and taking fall damage

### Actual behaviour

- Builder jumps off the warehouse and takes fall damage, eventually killing themselves.

### Steps to reproduce the problem

1. Build tier 2 warehouse
2. Have builder build roof
3. ...
4. Profit

**Comment by jzburda** [comment]
Just couldn't handle being called Gay ;(

**Comment by Raycoms** [comment]
Yeah we have to rework the builder positioning a little bit again, he seems to find a really nice position on top of those roofs.

**Comment by Raycoms** [comment]
Closed in favor of new issue soon.
