### ISSUE TITLE
[enhancement] be able to control the permissions/protections

### ISSUE THREAD

**Issue by kreezxil** [ldtteam/minecolonies#1193]
I would like to be able to control all of the things manually that the townhall block manipulates with its protection powers.

I have noticed that hostile mobs don't spawn inside the protected area, they'll come in to it, but they won't spawn into it. Even with no torches. If you need to kill them, you have to travel to the edge of the zone of protection and there they are all clumped together. Apparently, they hide the beer and cigarettes when you show up.

This is also true of the passive mobs.

The only cases where it is not true is when a mod adds mobs that don't inherit from the vanilla mobs, those mobs will spawn inside the town borders easily and often. For instance, the roots mods, which adds baby deer (bambi), has no issue spawning inside the town border. Animania however apparently inherits the vanilla mobs as its mobs like the ones mentioned above congregate or rather aggregate at the town border.

Additionally, when people are traveling through your town and they become hungry, they can not eat because of the protection. They also can't attack hostile mobs that are hunting them down for their human skins to make demonic drums from.

So a full permission system either in a config or accessible via the townhall block that allows us to toggle each of the things that the protection covers.

Back to mob spawn, I built a dark tower in my town, also known as a mob dropper, it never drops mobs and very extremely rarely spawns mobs. When they do spawn they never enter the chute but despawn instead. I think it has something to do with the permissions/protection.

This might be a bug report, but I see it more of as a chance to make enhancements that solve it.

**Comment by purestone9** [comment]
It would be nice if it there was a config file so that we were able to control the colony protections. Being unable to eat in another persons colony is extremely annoying.

**Comment by Raycoms** [comment]
Hey there,

1) There is a config file to allow a certain degree
2) Not eating and not defending against hostiles is a bug, which should've
been fixed (maybe only fixed on 1.10).
3) You can configure all of these things in the GUI
4) That's strange mobs spawn quite a lot in my colony and if you take a
look at Peters videos (on youtube) the spare quite a lot in his 1.11 colony
as well.

2017-06-16 15:05 GMT-03:00 purestone9 <notifications@github.com>:

**Comment by kreezxil** [comment]
Huh, so I can change most of this in townhall gui for 1.11.2 now?

**Comment by Raycoms** [comment]
Yeah you should take a look there are a huge amount of configurations in
the townhall gui, should also be in 1.11

2017-06-16 15:24 GMT-03:00 kreezxil <notifications@github.com>:

**Comment by Raycoms** [comment]
Should be fixed in the newest 1.10 alpha and in the upcoming 1.11 alpha
