### ISSUE TITLE
[1.11.2-0.8.2551] Deliveryman destroying items v 2440 through 2551

### ISSUE THREAD

**Issue by Krougal** [ldtteam/minecolonies#1195]
### Minecolonies version

version1.11.2-0.8.2440 , 2488 and 2551

### Expected behavior

- Deliveryman picks up items (or takes items you put in his inventory) and puts them in chests in warehouse. This works fine up to v 2431.

### Actual behaviour

- Deliveryman goes to warehouse, items are removed from his inventory. Nothing goes into warehouse.

### Steps to reproduce the problem

1. Build a warehouse
2. Build deliveryman to level 2 (level 1 seems to only pickup tools, which IIRC is intended behavior?)
3. Wait for deliveryman to pickup some items, or just put items in his inventory. Follow him.
4. Profit

**Comment by Asherslab** [comment]
Hi, yes sorry, Xavier made a patch for this very recently (I made the same discovery about 3 days ago) so it should be in the mod very soon, I'm sorry for any headaches caused by this. 
#1187

**Comment by Krougal** [comment]
Verified fixed in 2573
