### ISSUE TITLE
1.11.2 - D-man ignores repaired chests?

### ISSUE THREAD

**Issue by MoonCutter2B** [ldtteam/minecolonies#1196]
### Minecolonies version

minecolonies-universal-1.11.2-0.8.2488

### Expected behavior

If I have to repair the warehouse for some reason including missing/destroyed chests I expect the d-man to sooner or later start using the "new" chests. 

### Actual behaviour

- Looks like the D-man ignores the "new" chests (at least so far). He keeps on adding stuff, even new types of stuff, to the "old" chests. 

### Steps to reproduce the problem

1. Build warehouse
2. Remove some of the chests
3. Repair the house (builder)
4. Wait and let the D-man do his/her work for some time
5. Check for items added to the repaired chests.
4. Profit

**Comment by Asherslab** [comment]
Have you tried firing the D-Man and then re-hiring him?

**Comment by MoonCutter2B** [comment]
Yes, I have now. and I even have a new D-man but so far nothing.
But on the other hand that bug with items beeing destroyd by the D-man might be a reason why I cannot see if it helped or not.

**Comment by marchermans** [comment]
Sadly only chests placed by the builder work.
You will have to tell him to repair the Building to make the chests function again.

**Comment by Asherslab** [comment]
Sorry @OrionDevelopment he said that the builder Did make the chests, that his warehouse burnt down (or something similar where his chests were removed) and his builder Repaired it.

**Comment by marchermans** [comment]
Ah okey, sorry missed that
Will reopen.

**Comment by MoonCutter2B** [comment]
oh, but that is what I did.
what happened was that one of the earlier versions of minecoloneis had a bug that crashed the game. I removed the mod and then a few versions later I added it again and tried to rebuild my village house by house by placing the same building on the same spot. Most of it worked very nicely except the warehouse/d-man.

**Comment by Asherslab** [comment]
Okay, well then can you please destroy the chests you placed, and press the Repai button in are house GUI?

**Comment by MoonCutter2B** [comment]
done that also
two hours playing since then - still no items in the repaired chests

**Comment by MoonCutter2B** [comment]
but as I said - that could be the other D-man bug (1195)
I can wait for that update and check what happens  - I'm not in a hurry

**Comment by Raycoms** [comment]
Still happening?

**Comment by MoonCutter2B** [comment]
It looks like this issue has been solved. After a playing a 10 minutes there was items in most of the repaired chests.
Thanks mates!
