### ISSUE TITLE
Stone Brick Monster Eggs and Stone Mine Level 5

### ISSUE THREAD

**Issue by wyattzastrow** [ldtteam/minecolonies#1199]
### Minecolonies version

version 1.10.2-08.1917

### Expected behavior

- Stone Mine Level 5 Requires Stone Brick Monster Eggs which don't have a crafting recipe, maybe they exist in the world, but they have to be pretty rare, I could get stone monster eggs, but stone brick would be nearly impossible without a crafting recipe.

**Comment by Asherslab** [comment]
Oh crap, really? that was an accident (they're impossible to get outside of creative) @xavierh ?

**Comment by Raycoms** [comment]
I am not sure if that is fixed already in the newest versions @xavierh did you port your fix to 1.10?

**Comment by xavierh** [comment]
I don't recall

**Comment by Raycoms** [comment]
Is this still so?
Please report if still an issue.
