### ISSUE TITLE
[1.10.2] [Server] Builder getting stuck trying to build any building with error in console

### ISSUE THREAD

**Issue by xXJamieXx** [ldtteam/minecolonies#1201]
### Minecolonies version

Version: 0.8.2487

### Expected behavior

- When selecting "build building", the builder should start building it.

### Actual behaviour

- It says "Build Request Created"
- Builder does nothing
- Server Console gets spammed with error:

> [Server thread/ERROR] [minecolonies]: Pausing Entity Miles T. Hale (com.minecolonies.coremod.job.Builder) at BlockPos{x=-181, y=78, z=-737} for 0 Seconds because of error:
> [Server thread/INFO] [STDERR]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:202]: java.lang.NullPointerException

### Steps to reproduce the problem

1. Run a server with MineColonies instaled
2. Place down a town hall
3. Place down builder
4. Build builder hut
5. Place down mine
6. Request build
7. Fail

**Comment by Raycoms** [comment]
Can you tell me exactly which building, which upgrade he is trying to
build, and, if he is building already or still clearing?

2017-06-17 15:17 GMT-03:00 xXJamieXx <notifications@github.com>:

**Comment by xXJamieXx** [comment]
He is trying to build the mine in wood from the beginning. He hasn't cleared anything or built anything.

**Comment by xXJamieXx** [comment]
UPDATE:
This is happening for any building I try to build from this point onwards!

**Comment by Raycoms** [comment]
Can you fire/rehire him and check if that solves it?

2017-06-17 16:08 GMT-03:00 xXJamieXx <notifications@github.com>:

**Comment by xXJamieXx** [comment]
None of the button are doing anything except for recall and inventory.

**Comment by xXJamieXx** [comment]
I broke and replaced the builders hut block and yet it still will not build.

**Comment by Raycoms** [comment]
You have to enable firing in the townhall GUI.

Could you please update to the latest alpha?

2017-06-17 16:28 GMT-03:00 xXJamieXx <notifications@github.com>:

**Comment by xXJamieXx** [comment]
Im on the latest alpha, I can't destroy my builders hut anymore.

**Comment by xXJamieXx** [comment]
I break the block, I don't get it back, I try to place a block where it used to be, and the hut comes back.
This is the case for survival and creative.

**Comment by Raycoms** [comment]
Yeah it seems like that one block has been corrupted, you can try to place
a block with the buildTool over it. But its possible that only world edit
is able to remove it or nbt editor.

2017-06-17 17:18 GMT-03:00 xXJamieXx <notifications@github.com>:

**Comment by xXJamieXx** [comment]
The BuildTool fixed it for me. It looks like its working now (touch wood). I'm not sure whether it was due to the update or the builders hut but whichever one, im happy now I can get on lol. Thanks for help, will be sure to submit a new issue if I find anything else!
