### ISSUE TITLE
[enhancement] adding custom inventories to warehouse

### ISSUE THREAD

**Issue by kreezxil** [ldtteam/minecolonies#1203]
When you add entities that have inventories to the warehouse manually, the deliveryman needs to know they are there. Because we don't want waste cpu cycles constantly scanning for these inventories, have a button in the warehouse block, that when pressed will scan the warehouse for the inventories.

Possible scan cycle would be:

1. remove current data array of inventory locations
2. search entire current schematic area for new inventory entities. that means a colossal chest would qualify.
3. save these inventory locations into the data array
4. now the d-man would be insane with happiness!

**Comment by dsipp138** [comment]
I've been trying to customize the warehouse5.nbt to have more chests for a while with no luck. I've had the builder build the standard wharehouse5 and added 2 additional chests. 1 stacked on top of another chest and one added to the side of the wood column. Each time after i scan in the warehouse using the scan tool, and try to repair the warehouse, (so it includes the new chests) either the builder doesn't build or it builds a partial warehouse in a different location.

I've also tried this from scratch building a completely new warehouse but modifying warehouse2.nbt to have more chests. The same thing happens.

Wondering if this is a bug for the built in schematics?

**Comment by xavierh** [comment]
If you want to use your custom schematics you need to move them in the
appropriate location.
See https://wiki.minecolonies.com/wiki/22/schematics for more informations

**Comment by dsipp138** [comment]
Great idea and appreciate the reply but that's not my problem.  All my SCH
files are in the correct place.  I wouldn't be able to overwrite the
default schematic if it wasn't.

**Comment by xavierh** [comment]
You seems so sure they are at the right location but yet it does not work :)

May I have the full path including the filename of your custom warehouse 5
please

**Comment by dsipp138** [comment]
/Library/Application
Support/minecraft/minecolonies/schematics/wooden/WareHouse5.nbt

My other custom schematics work fine in the same folder and if includes a a
citizen or fisherman chest, works perfectly.  (I've only tried with those
two) It's only when the customized house has the same name as one of the
default schematics.

For example.  The builder builds the fisherman's hut to level 3 using.  I
then go and change a wall, add a chest, etc...  I then scan in the new
changed hut to the scans folder.  I rename it using the build tool. and
move it to the schematics folder.
Now I go and have the builder build a new fisherman's hut to level 1.   I
upgrade the hut to level 3.  Each time the builder try to upgrade the hut
to level 3, it either won't build or builds a partial version in a
different location, typically behind or to the side of the hut.

In this scenario, i've only modified the fisherman3.nbt and i only have a
fisherman3.nbt file in the schematics folder.

If you've had luck adding more chests to the warehouse at any level please
tell me what steps you did and i'll do the same on my world.  This is
probably a bit easier than troubleshooting.

**Comment by dsipp138** [comment]
Any updates?

**Comment by Raycoms** [comment]
The thing is that we want to avoid infinite storage, mainly for performance
purposes as well.

**Comment by Raycoms** [comment]
We will eventually add upgradeable storage in the warehouse but with racks out of performance issues.
Closed in favor of new issue soon.
