### ISSUE TITLE
Hope more materials choices for building town hall

### ISSUE THREAD

**Issue by qaz84904** [ldtteam/minecolonies#1204]
### Minecolonies version

version 1.11.2-0.8.2488

### Expected behavior

More materials choices for building town hall, such as spruce tree, birch tree, jungle tree, acacia tree, dark oak tree.

Now town hall has only three choices of building it. They are wooden( mainly requires oak tree a lot. I remember it is needed more than 150 oak tree wood. However, it doesn't need other tree at 1 level. ), mesa, and sand.

Due to limitation of materials of building town hall and huge requirement of material of building, we can only find oak tree forest, desert, and mesa to build our colony first. 

However, sometimes we don't spawn at these regions first. We maybe spawn at jungle, dark oak forest, spruce forest, and savanna. It is sometimes not convenient for players to find a proper region starting their colonies.

**Comment by Raycoms** [comment]
Additional stylepacks are definitively planned, but we also need you, the community to propose stylepacks we might officially add
