### ISSUE TITLE
Farmland placed above water causes villager pathing to break.

### ISSUE THREAD

**Issue by dreadwraith** [ldtteam/minecolonies#1205]
I noticed that farmers were getting stuck in the fields I built on top of a lake. I did some testing and realized that because the farmland blocks are directly above water blocks, it's causing some kind of error in their pathfinding, making them stand still until I physically push them on top of a full block. Adding a solid block layer beneath the farmland fixed the problem, and serves as a decent bypass for the issue for now. Suggest adding a dirt/cobblestone layer beneath the farm layer of the built in field blueprint to prevent this from occurring.

**Comment by Raycoms** [comment]
Closed in favor of new issue soon.
