### ISSUE TITLE
[Suggestion] Allow for changing design of camp/ship

### ISSUE THREAD

**Issue by SwordShaman** [ldtteam/minecolonies#1207]
As I understand it, you can change the design of all "huts" but the initial base camp.  I'm putting together a survival themed game and would love to adjust the camp to be much more simplistic in design.  Would this be possible?

**Comment by Raycoms** [comment]
You can switch our the baseCamp and supplyship from inside the jar =)

2017-06-18 13:46 GMT-03:00 SwordShaman <notifications@github.com>:

**Comment by xavierh** [comment]
No you should be able to replace the supply camp using the schematic folder

**Comment by xavierh** [comment]
FYI the schematics name for them are SupplyShip.nbt and SupplyCamp.nbt .
The need to be placed at the Base of the schematic folder
