### ISSUE TITLE
Baker complains that there is no furnaces

### ISSUE THREAD

**Issue by Jay9519** [ldtteam/minecolonies#1211]
### Minecolonies version

minecolonies-universal-1.11.2-0.8.2611
forge-1.11.2-13.20.0.2315

### Expected behavior

- The baker to make food

### Actual behaviour

- The baker just stands at the bakery block and says:
'My building doesn't have any furnaces, please repair it'
there is 2 furnaces in his location on the lvl2 building

### Steps to reproduce the problem

1. build the bakery
2. hire a baker
3. upgrade to lvl 2 building (not sure if this happened during lvl1 as I upgraded the building straight away)

https://www.dropbox.com/s/mt6kkyjb805s448/2017-06-20_00.22.52.png?dl=1

**Comment by Raycoms** [comment]
Yes, this is quite strange, will have to debug that when I get to it.
Meanwhile, just destroy the furnaces and ask the builder to repair the building

**Comment by Raycoms** [comment]
Finally fixed
