### ISSUE TITLE
Miner control

### ISSUE THREAD

**Issue by Mailleweaver** [ldtteam/minecolonies#1215]
### Minecolonies version

version 0.8.2611

### Expected behavior
- When the miner hut is upgraded he stops mining the level he's assigned to and digs the shaft deeper so new levels become available for assignment.

### Actual behaviour
- When the miner hut is upgraded he continues mining the level he's already assigned to, never digs the shaft deeper, and can't be assigned to deeper levels since they haven't been dug and so aren't available for assignment in the hut GUI.  

### Steps to reproduce the problem

- Build a miner hut, hire a miner, give him all necessary materials/tools, assign him to mine an upper level once the shaft to it is dug, upgrade miner hut, and there's no way to get him to dig the shaft deeper since he's already been assigned to a level.

### Suggestion to fix the problem
- Please give an option to unassign them, make levels available for assignment if the miner hut is upgraded enough even if the shaft hasn't been dug that deep, or give digging the vertical shaft priority over the manual level assignment.

**Comment by Raycoms** [comment]
This is quite interesting, normally (in code) the miner will just finish the current node he is working on and then start working on digging the shaft deeper (if he isn't at the max depth yet (like a few blocks from bedrock away) He reaches max depth at level 3

**Comment by Mailleweaver** [comment]
Apparently I was just impatient with this one. He did dig deeper after finishing the node he was on. I just expected him to stop mining immediately and go to digging. It makes sense that he'd finish his current node, though.
