### ISSUE TITLE
Wood Cutter died in his own tree

### ISSUE THREAD

**Issue by purestone9** [ldtteam/minecolonies#1221]
### Minecolonies version

curse 0.8.2689

The wood cutter will die in their own trees that they plant.

would it be possible to have the colonists path find around saplings?

**Comment by Raycoms** [comment]
The lumberjack is optimized to avoid standing on them, pathing around them would be possible but he would still optimize and possibly walk over them. Fortunately its quite rare nowadays so I'd close this and call it "sometimes people die working on hard labour jobs".
