### ISSUE TITLE
[1.11.2] Version 0.8.2594: Builder doesn't do anything

### ISSUE THREAD

**Issue by ghost** [ldtteam/minecolonies#1223]
### Minecolonies version

version 1.11.2 or curse 0.8.2594

### Steps to reproduce the problem

1. Start a new village
2. Place the builder
3. Let him build 1 Building
4. Then, after that, he does nothing, even hiring don't change anything and new build requests don't work (In chat comes "new build request", but then nothing), in the console is no error or sth.
5. Profit

**Comment by Raycoms** [comment]
I think we found a solution on discord for that. =)
