### ISSUE TITLE
[bug] farmer asks for axe ...

### ISSUE THREAD

**Issue by kreezxil** [ldtteam/minecolonies#1224]
1.11.2-0.8.2797

Farmer asks for stone axe, dman never delivers it. When farmer gets the axe, the farmer doesn't use and instead goes back to planting.

![image](https://user-images.githubusercontent.com/3880072/27408980-d34e4d84-56a4-11e7-938b-45e47f5fa503.png)

![image](https://user-images.githubusercontent.com/3880072/27409035-044aaacc-56a5-11e7-8de1-e3c2e8f1f069.png)

![image](https://user-images.githubusercontent.com/3880072/27409058-1f181ab0-56a5-11e7-9299-7c2619d1ff92.png)

and then as I was about to post this, the dman took the axe, but then the day ended. so I set the start of the day again, and the dman put stone axe back in the warehouse.

the dman is going back and forth between the farmer and the warehouse with a stone axe, the farmer keeps asking for it.

do i need to turn on developer options to get you a better log? cause right now the log has nothing in it.

**Comment by Raycoms** [comment]
That will be fixed with the next update. The farmer needs the axe for
melons and pumpkins.
In th enext update the dman will stop stealing it.

2017-06-21 19:18 GMT-03:00 kreezxil <notifications@github.com>:

**Comment by kreezxil** [comment]
ok cool
