### ISSUE TITLE
Game Crashing on Entering Citize'ns Hut Menu

### ISSUE THREAD

**Issue by Warrof** [ldtteam/minecolonies#1226]
### Minecolonies version

Minecolonies-universal-1.10.2-0.8.28.17

### Expected behavior

Bringing up the Citizen's hut menu normally

### Actual behaviour

Right clicking on the hut chest to bring up the menu causes and instant crash to desktop.

below are the crash reports.
[crash-2017-06-22_12.36.51-client.txt](https://github.com/Minecolonies/minecolonies/files/1095967/crash-2017-06-22_12.36.51-client.txt)
[crash-2017-06-22_12.38.13-client.txt](https://github.com/Minecolonies/minecolonies/files/1095968/crash-2017-06-22_12.38.13-client.txt)
[crash-2017-06-22_12.36.09-client.txt](https://github.com/Minecolonies/minecolonies/files/1095969/crash-2017-06-22_12.36.09-client.txt)

**Comment by Raycoms** [comment]
Kk working on a fix

2017-06-22 16:41 GMT-03:00 Warrof <notifications@github.com>:

**Comment by Raycoms** [comment]
@Warrof does this happen here as well: https://s3.eu-central-1.amazonaws.com/minecolonies/Minecolonies/Minecolonies_Branches/2823/minecolonies-universal-1.10.2-0.8.2823.jar
??

**Comment by Warrof** [comment]
I'll check when I get home.

**Comment by Warrof** [comment]
Works fine with that update.
