### ISSUE TITLE
[Enhancement] Colony Protection Expiration Date

### ISSUE THREAD

**Issue by SulpherStaer** [ldtteam/minecolonies#1230]
### Minecolonies version

Any future release

### Expected behavior

When a colony hasn't been used / the owner hasn't logged in for X amount of time, the protection range slowly decreases until it's just the center block, or even completely removed.

The colony protection radius is 200 - I recommend, that this radius slowly decreases by 1 block per 1 day (or 1728000 ticks) after 7 days of not having the owner or an officer of the colony be online and INSIDE the colony radius.

This isn't much reduction, but it is a solution. It means that a colony will only be 'without protection', after 
half a year. (200/30=6.6) For more drastic measures, other block reduction per X amount of time, after Y amount of no owner or officer can be used.

### Alternative behaviour

When a colony hasn't been used / owner hasn't logged in for X amount of time, the colony falls in decay. Buildings are replaced by lower level / decayed style buildings, and chunks within the radius, but not having a colony block on them, will regenerate.

Colony protection also turns off completely, and colony blocks dissapear, unclaiming the land, and 'deleting' the colony.

### Actual behaviour

Colonies are abandoned, and people have difficulty finding a spot for their colony. The colonies take up space, but are never used. And it's very difficult to see which ones are not used for admins and mods, to clean up some space.

**Comment by Asherslab** [comment]
As of most recently (not certain about in the past) the /mc colony info <ID> will show a correct amount of time that an owner has been away, also there is the /mc colony delete <ID> command. i will look at auto deleting after a config timing (0 being automatic and disabling it)

**Comment by Asherslab** [comment]
Also possibly a way to mark a colony as "do-not-delete"

**Comment by kreezxil** [comment]
can these /mc commands be used in a command block?

**Comment by Raycoms** [comment]
They should work

2017-08-13 13:46 GMT+01:00 kreezxil <notifications@github.com>:

**Comment by kreezxil** [comment]
Now the question is, how would I pull the away time out for use by the command blocks. I believe it can be done with the scoreboard in someway. I am not that experienced with advanced command block scripting however, so not sure how to do it. Perhaps by entertaining the thought here, someone will provide us a sequence of commands to be used in command blocks to do it.

Granted having the capability available within your mod seems more ideal, however a command block way will eliminate code bloat.

**Comment by Raycoms** [comment]
We have a pr running which will add a command which will remove colonies by
date.

2017-08-13 13:58 GMT+01:00 kreezxil <notifications@github.com>:

**Comment by kreezxil** [comment]
So, I just logged onto my production server and there was colony sitting right at spawn. It was 184 hours old, so I thought list /mc delete it and it did, but the protection remained.

**Comment by Raycoms** [comment]
Yeah, the protection only gets removed on the next restart.

2017-08-13 14:08 GMT+01:00 kreezxil <notifications@github.com>:

**Comment by Raycoms** [comment]
This has been merged already.
