### ISSUE TITLE
[1.11.2] Miner stops mining after a certain point (Reopen)

### ISSUE THREAD

**Issue by jzburda** [ldtteam/minecolonies#1232]
### Minecolonies version

version 0.8.2797

### Expected behavior

- Miner should be mining

### Actual behaviour

- Miner sits in the tunnel doing nothing

### Steps to reproduce the problem

1. Build Mining hut
2. Have miner dig tunnel
3. ...
4. Profit

P.S Unofficial solutions have already been made in issue https://github.com/Minecolonies/minecolonies/issues/1183

**Comment by Natrukei** [comment]
which level is the miner hut?
Each level is able to mine only a specific number of blocks down.
Maybe try to upgrade the building

**Comment by jzburda** [comment]
Miner level 4, and he stops when digging tunnels

**Comment by Raycoms** [comment]
Closed in favor of new issue soon.
