### ISSUE TITLE
minecolonies 1.11.2-0.8.2797 Corner tape texture error

### ISSUE THREAD

**Issue by teutates1989** [ldtteam/minecolonies#1234]
### Minecolonies version

minecolonies-universal-1.11.2-0.8.2797 

### Expected behavior

construction corner uses the correct tape texture

### Actual behaviour

construction corner doesn't use the correct texture
![2017-06-24_21 33 39](https://user-images.githubusercontent.com/11924154/27511474-72ca7bd0-5925-11e7-890a-2c8c39539de5.png)

### Steps to reproduce the problem

1. place a building and look at the construction tape in the corner for the block "corner tape"

**Comment by xavierh** [comment]
Pretty sure there is already an issue created for that

**Comment by teutates1989** [comment]
it seems you are correct [https://github.com/Minecolonies/minecolonies/issues/831](#831l)
I used the search function instead of scrolling the pages.
But indeed this issue is redundant then sorry for the inconvenience

**Comment by xavierh** [comment]
No problem
