### ISSUE TITLE
Allow player to request items from warehouse

### ISSUE THREAD

**Issue by BrianEdmonds** [ldtteam/minecolonies#1239]
I'd like to be able to share my personal crafting storage with my colony by just sharing the warehouse, but it's such a pain to look through all the chests. Having the item frames helps a bit, if I fill them in, but there are many chests with multiple unrelated things in them, and even without that it's a pain wandering around looking for the right chest. I'd love to be able to ask for what I need, like the colonists do, and have a deliveryman show up with it some (short :) time later.

**Comment by Raycoms** [comment]
Yes that's what we have planned already

2017-06-28 23:12 GMT-03:00 BrianEdmonds <notifications@github.com>:

**Comment by BrianEdmonds** [comment]
Very nice. I looked through issues and projects but didn't spot it. Is there somewhere you have planning notes for this sort of thing?

**Comment by marchermans** [comment]
The system that should male that possible is called the request system. It is currently a wip, we started pulling in the first official components now, but it will take some time until it is complete.
