### ISSUE TITLE
Town Protection limit blocks only visible by owner.

### ISSUE THREAD

**Issue by Wissi** [ldtteam/minecolonies#1240]
When placing a new hut by officer, the "diamond" town protection delimiter blocks are not visible to player.
only visible to "Owner" when Owner places a hut block.

Can we have "Officer" status in TH to also View the diamond delimiter blocks?
As well as the "Edit permissions" to actually work for Officer as well?

**Comment by Raycoms** [comment]
I asked the guys on the server and I think you did something wrong.
When you're inside someone else's colony and use the build tool you should be able to see it without a problem.
I also think you shouldn't need a permission for that. People should be able to find a fast way out of someones colony.
