### ISSUE TITLE
[1.11.2]pathfinding on bridges

### ISSUE THREAD

**Issue by teutates1989** [ldtteam/minecolonies#1241]
### Minecolonies version

minecolonies-universal-1.11.2-0.8.2797

### Expected behavior

Colonists cross over the bridge and return over the bridge

### Actual behaviour

Colonists cross over the bridge and try to return crossing under the bridge/ in the water.
A part of those that cross the water get stuck and even when you build land under them stop working until you recall them.
### Steps to reproduce the problem

1. build a oakbridgespan/ oakbridgestairs over water
2. let a colonist cross it.
3. See him getting stuck / cross water when he wants to return.
![2017-06-30_09 53 30](https://user-images.githubusercontent.com/11924154/27726402-a9935b38-5d7a-11e7-8761-6395249ecd47.png)

I tried building a fence near the bridge as quick-fix but they decide to bypass it to hangout in the water.

**Comment by Raycoms** [comment]
It seems like some of the waypoints are under the bridge. try to remove those and set them on top of the bridge.

**Comment by teutates1989** [comment]
yes it seems to work. just removing them seem to fix the problem. 
and replacing them after and it will continue to work as intended.
The bridge is standard minecolonie bridge though so their is something wrong with the schematic then ?

**Comment by Raycoms** [comment]
No, unfortunately, its very hard how to correctly detect where the
waypoints should be placed. We currently automatically in the center of the
schematic. But the bridge schematic center, unfortunately, is under them
and not above. We might want to include an invisible block which defines
the waypoint location in schematics. Therefore, I'd like to keep this here
open.

2017-06-30 16:18 GMT-03:00 teutates1989 <notifications@github.com>:

**Comment by BrianEdmonds** [comment]
Or introduce a real waypoint block which they can walk over? Then
placing waypoints would be as simpleas crafting such blocks and placing
them wherever desired.

**Comment by Raycoms** [comment]
Will be fixed with: #1263
