### ISSUE TITLE
underground colonies?

### ISSUE THREAD

**Issue by BrianEdmonds** [ldtteam/minecolonies#1244]
Has anyone tried creating an underground colony? I'm playing with the 1.11.2-0.8.1784 release on a server, and for the life of me cannot get the supply camp placed. I cleared a 16x17x5 cavern and attempted to place it with no luck. I've gradually dug that out to 18x19x9 and it still won't place. (Yes, I've clicked a few blocks around where the chest should place, on all four sides just for grins, and the entire space is flat and nothing but air.) I've poked through the code, and the only possible blocking check I could see is if the camp is taller than nine blocks, which would be surprising, since the times I've built it, it fit easily into nine blocks high. I looked at SupplyCamp.nbt, but couldn't find any tools to dig into it with, so couldn't find how tall it thinks it is. I understand NBT is a Minecraft native format, so I figure that's why it's being used, but it would be nice if schematics were in a format that could be manipulated with regular editors and shell tools.

**Comment by Wissi** [comment]
Try placing Dirt as the floor. I think it has to be Dirt as floor. 17 x 17
When U click on the block to place it make sure you're on the edge of the area.

**Comment by BrianEdmonds** [comment]
I can't see in the code where dirt is required, but I'm a newbie with Minecraft modding. That did occur to me, so I did try spreading dirt across at 18x19x5, but that may be too short for the camp. Anyone know how tall the thing wants to be? I'm kinda tired of digging. :)

**Comment by Asherslab** [comment]
Btw it does depend on N/S/E/W directions os it won't specifically place in the direction you're facing

**Comment by BrianEdmonds** [comment]
I lowered the dirt floor to 18x19x8, and still cannot place the camp on any side. Just the usual 16x17 requirement message. Can anyone tell me how tall the camp thinks it is, before I go digging down to bedrock? (Well, one above bedrock, since the code does appear to restrict building it directly on bedrock...)

**Comment by Wissi** [comment]
Try a couple more, shouldn't be more than 10 high. And make sure the floor is dirt(?)

**Comment by BrianEdmonds** [comment]
Next time I should just cheat in an RFTools builder and void the whole thing. :)

**Comment by BrianEdmonds** [comment]
And thats what I did, to build down a few more blocks. I didn't narrow down the exact height, but part of the issue was definitely at least height, as far enough down it placed as expected. I did place it on dirt, but as I said, I didn't see anything in the source that mandates that, just solid blocks.

**Comment by Wissi** [comment]
kk.. so it placed now? The issue (in your case) was the height restriction (not being announced)?

**Comment by BrianEdmonds** [comment]
@Wissi Yeah, the main problem I had was that it was taller than I
expected, and I had no visibility into what the required height was. I
doubt it was important that it was placed on dirt (unless someone more
familiar with the code says otherwise). It's now placed, and I'm on to
considering how to approach the digging project for the rest of the
colony...

**Comment by Wissi** [comment]
@Kostronor @Raycoms I guess this one can be closed now?
Was solved by making more space horizontally.

**Comment by Raycoms** [comment]
Yay =)

**Comment by BrianEdmonds** [comment]
More space vertically, that is. But yeah, placing the supply camp works
when there's enough vertical space. An improvement would be to make it
more clear what vertical space is the problem. It could happen
overground too with an overhanging tree or such.
