### ISSUE TITLE
Citizens stop moving

### ISSUE THREAD

**Issue by WindRider739** [ldtteam/minecolonies#1246]
### Minecolonies version

1.10.2 - 0.8.1917

### Expected behavior

Citizens continue to function as long as chunk is loaded.

### Actual behaviour

Citizens stop moving unless a player is within about 32 blocks of them.

### Steps to reproduce the problem

1. Install Sponge
2. Edit activation range to 256
3. ...
4. Frustration

**Comment by Raycoms** [comment]
I pet you're using sponge, you have to increase the neutral entity range to
make that activation range 256.

2017-07-02 9:46 GMT-03:00 WindRider739 <notifications@github.com>:

**Comment by WindRider739** [comment]
I've done that. This is what reads in the following files.

global.conf
worlds/minecraft/real_name_dim_2200/dimension.conf
worlds/minecraft/real_name_dim_2200/DIM2200/world.conf (this is essentially a second overworld)

    entity-activation-range {
        # If enabled, newly discovered entities will be added to this config with a default value.
        auto-populate=true
        # Default activation ranges used for all entities unless overidden.
        defaults {
            ambient=256
            aquatic=256
            creature=256
            misc=256
            monster=256

**Comment by Raycoms** [comment]
Should be fixed, its a sponge problem.
