### ISSUE TITLE
Miner and Deliveryman: Dirt Problem

### ISSUE THREAD

**Issue by Nezraddin** [ldtteam/minecolonies#1247]
### Minecolonies version

version 0.8.2797

### Expected behavior

- Deliveryman brings dirt to the miner's hut when the miner needs it.

### Actual behaviour

- The deliveryman actually brings the dirt to the miner's hut, puts it into the inventory, but immediately afterwards he takes it out again before the miner can grab it. 
(probably needs a command to ignore one stack of dirt in the inventory, like with torches and cobblestone)

### Steps to reproduce the problem

1. Stalking the deliveryman when he brings dirt to the miner's hut.

**Comment by zekermarco** [comment]
This happens with the Builder too, in version 0.8.2890

**Comment by Raycoms** [comment]
Ah I think that should be ready as well.
