### ISSUE TITLE
HAD COLONY error

### ISSUE THREAD

**Issue by WindRider739** [ldtteam/minecolonies#1248]
Minecolonies version

1.10.2 - 0.8.1917

Expected behavior

Business as usual

Actual behaviour

Something has happened to one of my server alpha tester's colonies. She logged out in her colony and everything was fine. She logged in about an hour later and crashes to title screen every time she logs in, getting the fatal exception error. Looking in console provides this message about three dozen times...

[13:48:19] [Server thread/WARN] [minecolonies]: TileEntityColonyBuilding at DedcraftHeroes4:[-2092,64,-501] had colony.

Steps to reproduce the problem

Unknown

**Comment by Asherslab** [comment]
could you get a crash-log from the player herself please?

**Comment by Raycoms** [comment]
Seems to me that somehow the colony got rollbacked and the building is
still there but the tileEntity lost its colony.
I think we should try to fix that in the "had colony" check.
Like: Where we print had colony we should try to recover the colony (check
if tileEntity is inside colony) else we delete the block and tileEntity
itself.

2017-07-10 5:19 GMT-03:00 Asherslab <notifications@github.com>:

**Comment by WindRider739** [comment]
The crash log no longer exists. I rolled the world back and did some tweaking.

**Comment by Asherslab** [comment]
okay well it seems this is done now? i'm going to close this
