### ISSUE TITLE
underground colonists path poorly

### ISSUE THREAD

**Issue by BrianEdmonds** [ldtteam/minecolonies#1250]
Continuing to play with an underground colony, I've gotten the builder's hut done, and up to level two, the lumberjack done, and chopping away at a little copse of trees, and the miner done, and upgrading to level two. The miner is refusing to mine without being upgraded, since she's down at level 32, but I figure that's working as intended. My problem is that the colonists are having major issues pathing. There's only one tunnel for them to walk down, so it shouldn't be very difficult. The tunnel slopes up on one end, and the builder's hut is up around level 50. She picks up stuff, then goes to stand at the edge of her hut on the side of the miner and does nothing until nightfall. The next morning, on the way by the miner's hut, she'll finish working with whatever she's carrying, then go back to her hut to get more and stand at the wall again.

**Comment by Raycoms** [comment]
Closed in favor of new issue soon.
