### ISSUE TITLE
[1.12] When you throw out an item in a colony not your own, it deletes.

### ISSUE THREAD

**Issue by ProsperCraft** [ldtteam/minecolonies#1251]
### Minecolonies version

minecolonies-universal-1.12-0.8.2971

### Expected behavior

- Drop anything in a colony you don't have perms in, and the item drops on the ground, but you can't pick it up.

### Actual behaviour

- The block deletes.

**Comment by Raycoms** [comment]
The reason for this is that players don't grief others by filling up the inventories of their workers.
Way:
Go to the builder, drop him 20 stacks of 1 unique items, he will fill up and stop working completely.
