### ISSUE TITLE
Miner has stopped working

### ISSUE THREAD

**Issue by kedamono** [ldtteam/minecolonies#1253]
### Minecolonies version

version 0.8.2994

### Expected behavior

- Miner mines and guards guard.

### Actual behaviour

- The miner just stands there and does nothing. Either in the Mine hut or in their citizen's hut. Firing and hiring only results in them walking to the Mine block and just standing there. Current mine hut is level 2.

The guards ignore the mine hut even though it's well within their range. They don't go in and treat it as non-colony building.

### Steps to reproduce the problem

Install version 0.8.2994 and play for a while.

**Comment by Goten87** [comment]
same problem builded a miner got to work he got 2 iron ore and he did noting anymore for like 6 ingame days now

also are u peeps still working on the project ?

**Comment by BrianEdmonds** [comment]
In my experience, most of the time when my people are standing around
not working, it's because there's a hostile mob in the neighborhood.
Particularly the miner, there may be something lurking in one of the
shafts that's scaring the poor blighter out of his wits.  Feature idea:
could guards patrol mines?

**Comment by Goten87** [comment]
there is no mob sins i play on peacefull right now to learn the mod
and he just keeps chilling out in or near the town hall

also i use version Alpha 8.2797

**Comment by kedamono** [comment]
It turned out that my miner just wanted some cobblestone. So, to get them to work, give them a stack of cobble and a stack of dirt. 

Closing as no fix needed.
