### ISSUE TITLE
Builders get stuck

### ISSUE THREAD

**Issue by lunadragnstar** [ldtteam/minecolonies#1258]
### 0.8.2797

version 1.11.2 or curse X.X.XX

### Expected behavior

- I expect that when I ask a builder to build something they do it.

### Actual behaviour

- Some of the requests seem to get stuck in the queue. I'm building a huge city and when I set up a lot of build requests some of them get stuck. They can get stuck on any build object. Don't know if this is because I am putting in a ton of requests at once or not, but once a build becomes stuck, more items on the list get stuck too. I have to go to the Townhall and delete all requests and start over.

### Steps to reproduce the problem

1. Put in a lot of build requests
2. wait
3. ...
4. Profit

**Comment by lunadragnstar** [comment]
I did some more testing and it seems they like to get stuck at 422 from the center of the colony.

**Comment by Raycoms** [comment]
Yeah that's kind of far away from the colony center. I bet the colony gets
into trouble because parts of it aren't loaded. can you try to increase
your render distance to see if that increases the distance they get stuck?

2017-07-09 21:39 GMT-03:00 lunadragnstar <notifications@github.com>:

**Comment by lunadragnstar** [comment]
It does it even if I follow the builder. Sometimes they eventually continue but other times I have to wait days for it to finally be built and others I have to cancel and restart the build.

**Comment by Raycoms** [comment]
Yeah, I think the problem is the distance.
The colony runs into problems if huge parts are not loaded.
Often the builder might be waiting for the dman to come but he is far away and in an unloaded chunk.
We will have an issue discussing that.
