### ISSUE TITLE
[1.12] MC RTP does not check for world border and kills players.

### ISSUE THREAD

**Issue by ProsperCraft** [ldtteam/minecolonies#1259]
### Minecolonies version

version X.X.XXXX or curse X.X.XX

### Expected behavior

- RTP checks against world border before sending player beyond it.

### Actual behaviour

- RTP drops people beyond the world border leading to instant death.

### Steps to reproduce the problem

1. Set world border to smaller then the rtp range.
2. Player uses rtp
3. Profit

**Comment by Raycoms** [comment]
Yeah that's definitively something we should add.
@Asherslab are you up to adding that to your pr?

**Comment by Asherslab** [comment]
hahahah i actually just did that yesterday (i'll check to make sure i didn't remove it tho) =D

**Comment by Raycoms** [comment]
Add a "Closes #1259" to your pr then =D ontop

**Comment by Asherslab** [comment]
yep =D

**Comment by Raycoms** [comment]
Fixed in that pr.
