### ISSUE TITLE
Create waypoint placeholder block

### ISSUE THREAD

**Issue by Raycoms** [ldtteam/minecolonies#1263]
This is a placerholder block like the solid one (texture this time blue).

The difference is that it lets the player create a waypoint on building it.

Advantages:

If we add them in all our worker buildings we can remove the waypoint of the building chests.
(This time workers don't enter the buildings).

This way also the bridges etc can have the waypoint in a central pos.

**Comment by Goten87** [comment]
And how will that work with roads then de we place the waypoint under the road or do we have a other block in your road where the waypoint comes
I stil think a waypoint want will be better for making waypoints

**Comment by Raycoms** [comment]
The waypoint will be an option in the building wand, no need for an extra
wand

2017-07-10 20:31 GMT-03:00 Remko de Bruin <notifications@github.com>:
