### ISSUE TITLE
Waypoints not going away

### ISSUE THREAD

**Issue by lunadragnstar** [ldtteam/minecolonies#1264]
### Minecolonies version

version 0.8.2797 or curse X.X.XX

### Expected behavior

- was told that if you removed the block beneath the waypoint that it will remove the waypoint after a few minutes

### Actual behaviour

- removed several blocks beneath the waypoint and waited several minecraft days (and a couple RL days) and the waypoints are still there.
![2017-07-06_22 43 12](https://user-images.githubusercontent.com/29446488/27941114-f3f8db36-629c-11e7-9fe0-c65d2ffa29cc.png)

### Steps to reproduce the problem

1. XYZ
2. ZYX
3. ...
4. Profit

**Comment by Raycoms** [comment]
just place a block over them, wait 20 seconds and they'll vanish.
You need to replace or change the block inside and not under them.

**Comment by lunadragnstar** [comment]
Thanks, this is slowly working, taking longer than 20 seconds though.

**Comment by Araxidis** [comment]
I know this is closed but this post helped me so I figure it's still relevant. My problem was the deliveryman would get stuck on a waypoint on the corner of the well. I didn't need the waypoints at the well so I deleted them. Each one just took a couple seconds to disappear and it fixed the problem.

**Comment by NilsMoller** [comment]
This does not work anymore... What do I need to do to destroy the waypoints?

**Comment by Raycoms** [comment]
Place a block over it, ways a few minutes, then take it away. This is not "ticked" regularly to avoid lag.

**Comment by NilsMoller** [comment]
Got it, thanks. I tried 1:30 minutes but i guess that's not enough. Might wanna mention it on the wiki too

**Comment by Raycoms** [comment]
If it's not gone in 5 minutes we'll take a look at it again. 
@someaddons are we ticking it so rarely atm?

**Comment by NilsMoller** [comment]
I waited a little over five minutes and they are indeed gone. Thanks for the info
