### ISSUE TITLE
How to fix miner nodes.

### ISSUE THREAD

**Issue by Guardian9978** [ldtteam/minecolonies#1266]
### Minecolonies version

version 0.8.2797 or curse X.X.XX

### Expected behavior

- when removing the miner block, rotating it, and placing back down on the same spot the miner should not use the old mineshaft.

### Actual behaviour

- when removing the miner block, rotating it, and placing back down on the same spot the miner uses the new mineshaft entrance but tries to use the old mineshaft the rest of the way.

### Steps to reproduce the problem

1. build a miner building and have a miner mine a few nodes worth.
2. break the miner block and rotate building on the same spot and rebuild the building
3. have the miner mine again (the miner may get stuck on the new ladder)

I've also noticed that if you mine down to the first wooden slab layer in the new mineshaft the miner will use the new mineshaft entrance but use the old mineshaft ladders the rest of the way if the miner can reach it else the miner gets stuck. also have noticed that the miner block marks the bottom most layer of the old mineshaft as node 0

**Comment by Raycoms** [comment]
Remove the ladder of the old shaft and it works great

Am Freitag, 7. Juli 2017 schrieb Guardian9978 :
