### ISSUE TITLE
Miner not using pickaxe on some stones/ores

### ISSUE THREAD

**Issue by Goten87** [ldtteam/minecolonies#1267]
### Minecolonies version

version 1.11.2-0.8.2797

### Expected behavior

- miner to use a pickaxe on marble from the mod Quark

### Actual behaviour

- uses a block of dirt to mine the marble

### Steps to reproduce the problem

1. put miner on a marble deposit and see the magic happen
2. Profit

**Comment by Raycoms** [comment]
I think we have to report this to quark, he has to implement efficient tool
on this block

Am Freitag, 7. Juli 2017 schrieb Remko de Bruin :
