### ISSUE TITLE
much needed permission for staff members

### ISSUE THREAD

**Issue by Jay9519** [ldtteam/minecolonies#1268]
minecolonies-universal-1.11.2-0.8.2786
spongeforge-1.11.2-2315-6.1.0-BETA-2438

Need a permission for staff to access colony protected areas, if players make lag machines in their base, then staff can't access the area to remove it

**Comment by Raycoms** [comment]
Staff can execute /mc colony addOfficer to get access.

2017-07-08 7:36 GMT-03:00 Jay9519 <notifications@github.com>:

**Comment by Jay9519** [comment]
thanks for the fast reply
would that remove the staff member from their own colony when they add themselves to the players colony?

**Comment by Raycoms** [comment]
No its only as officer.

2017-07-08 9:44 GMT-03:00 Jay9519 <notifications@github.com>:

**Comment by Jay9519** [comment]
that works good, is there a command for the staff member to remove himself from the colony?

**Comment by Raycoms** [comment]
Not yet, we will add that soon. For now you have to remove yourself in the
GUI or ask the owner.

2017-07-09 21:10 GMT-03:00 Jay9519 <notifications@github.com>:
