### ISSUE TITLE
Cannot Place SupplyCamp

### ISSUE THREAD

**Issue by QuantumBreed** [ldtteam/minecolonies#1269]
### Minecolonies version

version 0.8.2971

### Expected behavior

Supplycamp chest places when clicking on ground in a completely flat area of at lease 16 x 17.

### Actual behaviour

Went into creative mode and made a 32 x 32 flat platform of grass. no matter where i click and in what orientation it only tells me that i need a flat area of at least 16 x 17. I know the placing can be fickle as with the Supply ship but the conditions for the supply camp should be easier to get especially on a superflat creative world.

**Comment by BrianEdmonds** [comment]
Screenshot?

**Comment by QuantumBreed** [comment]
![2017-07-08_11 34 46](https://user-images.githubusercontent.com/30003932/27986777-7b985cda-63d1-11e7-8e27-9d33633896ff.png)

**Comment by Raycoms** [comment]
Since you're on a superflat world its possible that the y position is too
low (under the limit) try it 1-2 blocks higher

2017-07-08 12:35 GMT-03:00 QuantumBreed <notifications@github.com>:

**Comment by QuantumBreed** [comment]
That is the area i'm trying to place the SupplyCamp in my creative world. nothing is blocking the creation in any way. I also raised the platform by 2 from the normal super flat but will raise the level to normal minecraft height about 60.

**Comment by QuantumBreed** [comment]
Tested it again and it still did not work i have my F3 open to show my Y value.

![2017-07-08_11 41 35](https://user-images.githubusercontent.com/30003932/27986823-844575ce-63d2-11e7-8f92-b5cf7442e94e.png)

**Comment by Raycoms** [comment]
the area is 16*17? (Area must be 16*17 but the supplychest would be in the
2nd row around central left =P

2017-07-08 12:42 GMT-03:00 QuantumBreed <notifications@github.com>:

**Comment by QuantumBreed** [comment]
The diamond block is where i stood to place the camp with the emerald block being the spot i tried placing it. still did not work.

![2017-07-08_11 49 37](https://user-images.githubusercontent.com/30003932/27986882-95d348b0-63d3-11e7-87f7-33d024d9271a.png)

**Comment by Raycoms** [comment]
Can you show me the log?

2017-07-08 12:50 GMT-03:00 QuantumBreed <notifications@github.com>:

**Comment by QuantumBreed** [comment]
where can i find that so i can show it

**Comment by Raycoms** [comment]
in the minecraft root folder, in the logs folder.

2017-07-08 12:52 GMT-03:00 QuantumBreed <notifications@github.com>:

**Comment by QuantumBreed** [comment]
Alright i found the issue. it seems that I had to click on a layer above where i was trying to place it will provide a picture.

**Comment by QuantumBreed** [comment]
so it seems that for whatever reason something is blocking it from spawning on totally flat ground unless i put a block  down and click on that block.


my accidental placing of the camp.
![2017-07-08_11 58 36](https://user-images.githubusercontent.com/30003932/27986987-0c1478e0-63d5-11e7-83c8-21ec2bc61b92.png)


new planned spot
![2017-07-08_11 58 49](https://user-images.githubusercontent.com/30003932/27986996-1212d124-63d5-11e7-9f34-b64e2e23ad7a.png)

after clicking on emerald block notice emerald block underneath.
![2017-07-08_11 58 55](https://user-images.githubusercontent.com/30003932/27987003-2524984c-63d5-11e7-9889-802280e58e01.png)
![2017-07-08_11 59 00](https://user-images.githubusercontent.com/30003932/27987004-287c94f4-63d5-11e7-95a1-e421b3154a67.png)

**Comment by QuantumBreed** [comment]
should it not be able to replace the ground with dirt? which is what seems to be the issue now.

**Comment by QuantumBreed** [comment]
Made a 16 long line of blocks and am clicking on it to see where this hang up is coming from.
![2017-07-08_12 05 10](https://user-images.githubusercontent.com/30003932/27987039-b5c0b4bc-63d5-11e7-9254-587eeb162c75.png)

**Comment by QuantumBreed** [comment]
in a 16 x 17 area one or more blocks seems to be blocking the creation of the structure as proven by making a 16 x 17 platform of diamond and emerald blocks and being unable to spawn the camp on it but i am able to spawn the camp on a line of emerald from my position all the way to the end of the 17 blocks. minus the two at the end.
![2017-07-08_12 05 10](https://user-images.githubusercontent.com/30003932/27987130-19635d8e-63d7-11e7-8cc1-70a0a33258e1.png)
![2017-07-08_12 15 52](https://user-images.githubusercontent.com/30003932/27987136-3ab20bb6-63d7-11e7-86e1-654d19232faa.png)
![2017-07-08_12 16 01](https://user-images.githubusercontent.com/30003932/27987137-3c7e1f7a-63d7-11e7-9ee3-31847e078591.png)

**Comment by Asherslab** [comment]
does it work if the 16 x 17 area is all Grass not Dirt?

**Comment by Raycoms** [comment]
It shouldn't make a difference

2017-07-12 3:34 GMT-03:00 Asherslab <notifications@github.com>:

**Comment by QuantumBreed** [comment]
No it doesn't matter the material. But if I dig a 16 x 17 pit with one block not dug out where I am clicking the supply camp on it works fine.
