### ISSUE TITLE
Cant Expand Village?

### ISSUE THREAD

**Issue by LegoCollecter14** [ldtteam/minecolonies#1271]
Release for 1.12 With Beta Features On

1.12 with newest forge

well i have 6 houses + town hall so that sure be what? 4+2+2+2=10? Its still at 4. i originally thought that, oh hey maybe i need to make 2 houses for the first 4, but no still at 4 after 3 houses
![image](https://user-images.githubusercontent.com/19707996/27990269-13219dda-641f-11e7-9563-c6d50e8eef9f.png)
![image](https://user-images.githubusercontent.com/19707996/27990270-180bf444-641f-11e7-9596-de62e3fb63c8.png)

So Uh Let Me Know If This Is Actually A Glitch Or Me Being A Noob

**Comment by Asherslab** [comment]
One house only allows one occupant per building level, thus 5 level 1 houses only allows 5 citizens total (the TownHall does not house anyone).

**Comment by LegoCollecter14** [comment]
Ah so I was being a noob thanks for the help

**Comment by Asherslab** [comment]
no problemo =D

**Comment by Asherslab** [comment]
tell me when it works (so we can be sure, as 1.12 is still kinda WIP)

**Comment by LegoCollecter14** [comment]
Works fine now, but you may want to go over your wiki

**Comment by Asherslab** [comment]
yep @Wissi ^^^^^^

**Comment by Wissi** [comment]
The WIKI is very clear and specific about that, unless you're viewing another NON official WIKI.
Official WIKI:
https://wiki.minecolonies.com/wiki/15/citizen-hut
