### ISSUE TITLE
Builders Get Killed Making Building

### ISSUE THREAD

**Issue by LegoCollecter14** [ldtteam/minecolonies#1272]
Newest

1.12

Builder Not Dying 

Builder Died

### Steps to reproduce the problem
![image](https://user-images.githubusercontent.com/19707996/27993646-d910bf38-647b-11e7-9a2e-7f7768f1d10e.png)

**Comment by LegoCollecter14** [comment]
He built himself into the back wall, please fix this

**Comment by lunadragnstar** [comment]
I have builders dying while building the fishermans huts, they get stuck under it and drown.

**Comment by LegoCollecter14** [comment]
Your supposed too keep it on land they walk to water 5 blocks away

**Comment by lunadragnstar** [comment]
Even when I put it in the water, I get the message that the hut is too far away from the water.

**Comment by Raycoms** [comment]
You have to put it on the same y level.

2017-07-09 18:13 GMT-03:00 lunadragnstar <notifications@github.com>:

**Comment by lunadragnstar** [comment]
It is, and it has at least 7 water around 3 sides.

**Comment by Raycoms** [comment]
Will open a separate issue for that soon.
