### ISSUE TITLE
Stuck on Granite Walls

### ISSUE THREAD

**Issue by rsmalec** [ldtteam/minecolonies#1273]
### Minecolonies version

version 1.11.2

### Expected behavior

- path AROUND granite walls (ftb direwolf20)

### Actual behaviour

- I believe they are being detected as 1 block high, and the colonists are trying to jump over them.  But they are 1.5 blocks (like stone fences).  Not sure if vanilla stone fences have the same issue.

### Steps to reproduce the problem

1. Have a colonist path next to existing stone wall (e.g. Around the pit of the Mining Hut).
2. Replace stone walls with granite walls.
3. Villagers get stuck and keep jumping.
4. This happens too when I tried to surround my colonists' homes to keep mobs out of the village.

**Comment by Raycoms** [comment]
I bet minecraft mobs do behave the same way, no?

2017-07-09 11:25 GMT-03:00 rsmalec <notifications@github.com>:

**Comment by Raycoms** [comment]
Will open a separate issue for that soon.
