### ISSUE TITLE
MineColonies stops Mechanical Miner [Extra Utilties 2] from breaking blocks

### ISSUE THREAD

**Issue by Chaechew** [ldtteam/minecolonies#1274]
### Minecolonies version
minecolonies-universal-1.10.2-0.8.3056

### Expected behavior
extrautils2-1.10.2-1.4.4  : Mechanical Miner Breaks blocks

### Actual behaviour
extrautils2-1.10.2-1.4.4  : Mechanical Miner will not break blocks

### Steps to reproduce the problem
Removed minecolonies-universal-1.10.2-0.8.3056.
extrautils2-1.10.2-1.4.4  : Mechanical Miner Breaks blocks
Installed minecolonies-universal-1.10.2-0.8.3056
extrautils2-1.10.2-1.4.4  :  Mechanical Miner will not break blocks
4. Profit

**Comment by Raycoms** [comment]
This doesn't work inside the colony borders only I bet.
You can deactivate the anti-griefing mechanism in the config.
Else please report this to extrautils because they have to make their miner the placers UUID
