### ISSUE TITLE
Large Fern Warehouse level 4 (sandstone)

### ISSUE THREAD

**Issue by roulito** [ldtteam/minecolonies#1275]
### Minecolonies version

1.11.2-0.8.2786

Impossible upgrade Warehouse level 4 (sandstone) because large ferns are impossible to pick up. When we break we get 2 fern and not 1 large fern.

**Comment by Raycoms** [comment]
Did you try to get them with shears?

2017-07-09 17:04 GMT-03:00 roulito <notifications@github.com>:

**Comment by roulito** [comment]
Yes, I try shear, shear silk touch and other tools.

**Comment by Raycoms** [comment]
What you can do is placing the fern in the location where the builder wants
to place it, he would then a bit later on night/day detect that. (Place
single fern and use bonemeal).
I remember there was a way to get it but I don't recall how.

2017-07-09 17:30 GMT-03:00 roulito <notifications@github.com>:

**Comment by Asherslab** [comment]
yeah this has been noted before, do we want to make it so that two fern items can be used to place one big fern?

**Comment by Asherslab** [comment]
we fixed this =D
