### ISSUE TITLE
Question about pathing and assignment of citizen huts

### ISSUE THREAD

**Issue by ZephyrWindSpirit** [ldtteam/minecolonies#1276]
### Minecolonies version

version 1.12

Been playing All The Mods 3, and I've noticed that my miner whose hut is across the colony, never goes home. He appears to get stuck pathing someplace and ends up starving. 

I noticed the 1.12 version of Minecolonies has no 'assign citizen to hut'. So how do we assign the colonists to a hut closer to their workplace instead of building a hut right next door?

**Comment by Raycoms** [comment]
Hey there, I am currently porting exactly that update to 1.11 so expect it to 1.12 soon as well.
Additionally, help him out with waypoints to help him find home.
