### ISSUE TITLE
Quary&forge have no recipies

### ISSUE THREAD

**Issue by Goten87** [ldtteam/minecolonies#1280]
### Minecolonies version

version 1.11.2-0.8.3061

### Expected behavior

- recepies for the Quary and forge

### Actual behaviour

- No crafting recepies for both buildings

### Steps to reproduce the problem

just click for the show recepie in the item list

so how do i unlock them is it a beta test or is it juist not in there yet?

**Comment by Raycoms** [comment]
No recipes needed, they'r enot implemented yet.
