### ISSUE TITLE
separated config files for worlds

### ISSUE THREAD

**Issue by Goten87** [ldtteam/minecolonies#1282]
### Minecolonies version

- Upcoming

### Expected behavior

- new way the settings work/load in the config folder will be the main config file that will always be copied to the new game
then when i start a new world it will go in there so that we have separated config files for the worlds we make
that way when i want a test/build world for schematics i can just edit the file to have the builder always have resources without switching back when i go to my normal world

that way it will be nicer to play the mod and not switching 100 times between worlds and settings

also a addition for configs is the fact of food/happiness to turn it on/off

**Comment by xavierh** [comment]
Excellent idea :D 
https://github.com/Minecolonies/minecolonies/issues/659

**Comment by Raycoms** [comment]
We discussed that a few times already.
Until forge cleans up a way for that this won't be happening since we would have to code our own config system.
