### ISSUE TITLE
Better Waypoint System

### ISSUE THREAD

**Issue by Goten87** [ldtteam/minecolonies#1283]
### Minecolonies version

version 1.11.2-8.3123

### Expected behavior

- way to see where i place a Decorations->Waypoints->Waypoint

### Actual behaviour

- Cant see anything where i will build it only when i place it
- Also a way to delete waypoints will be nice maby a new tool to place waypoints on a block where we are clicking with left mouse and delete a waypoint with right mouse click

### Steps to reproduce the problem

1. get your self a building tool
2. set it to waypoint
3. click somewhere and u see nothing xD

**Comment by Raycoms** [comment]
I made an issue already for that.
We will create a waypoint block for that.
