### ISSUE TITLE
Rename/Delete button glich

### ISSUE THREAD

**Issue by Goten87** [ldtteam/minecolonies#1284]
### Minecolonies version

version 1.11.2-8.3123

### Expected behavior

- good vieuw of the UI

### Actual behaviour

- the most right dropdown bar going over Rename/Delete butten 
can u chance the posision to somthing else for exemple under the confirm butten

**Comment by Goten87** [comment]
i made a chance my self test it and pull request it if u want i like the buttens like this
`<button id="rename" size="114 15" pos="83 215" label="Rename" visible="false"/> 
    <button id="delete" size="114 15" pos="217 215" label="Delete" visible="false"/>`

**Comment by xavierh** [comment]
a screen shot would be nice

**Comment by Goten87** [comment]
a screenshot of what the bug or the new pos?

**Comment by Raycoms** [comment]
Of the bug

Am Montag, 17. Juli 2017 schrieb Remko de Bruin :

**Comment by Goten87** [comment]
Here is a screenshot i dont thing its nice looking at all
if u put the buttens under the green V and just above the toolbar it looks a lot nicers
![2017-07-17_15 36 51](https://user-images.githubusercontent.com/1938598/28270453-d3de4f40-6b05-11e7-8328-19be341a466a.png)

**Comment by xavierh** [comment]
I don't see any problem with that.

**Comment by Goten87** [comment]
well if u have a list its not nice looking at all

**Comment by xavierh** [comment]
It's only when the third drop down menu is open

**Comment by Goten87** [comment]
true

**Comment by Raycoms** [comment]
If still an issue please reopen.
