### ISSUE TITLE
Colonists Duplicating

### ISSUE THREAD

**Issue by judicius** [ldtteam/minecolonies#1290]
### Minecolonies version

0.8.2890

### Expected behavior

Workers Request tool and wait at chest

### Actual behavior

Workers duplicating with every request

### Steps to reproduce the problem

Firing and rehiring do not seem to effect, nor does recalling worker. Currently running the mod in the Sprout pack on a server where I am experiencing this behavior. Killing the "extra" workers has no effect unless the "prime" worker is killed in which case a new colonist arrives. Any of the duplicate workers that weren't killed still exist. Messages/Requests generate for every duplicate. [ie I have 12 miners and all 12 gather at the chest and I get 12 messages that the miner needs a pick. Each duplicate will pick a pick from the chest but they will keep requesting till the prime miner gets one.

**Comment by judicius** [comment]
![2017-07-12_02 03 53](https://user-images.githubusercontent.com/30104638/28103930-73e6e268-66a6-11e7-8b71-66496367ec94.png)

**Comment by Raycoms** [comment]
Yeah that happens due to minecrafts entitiy management, unfortunately we didn't find out yet about that.
You just have to kill both unfortunately
