### ISSUE TITLE
Guards picking up items

### ISSUE THREAD

**Issue by pmardle** [ldtteam/minecolonies#1291]
### Minecolonies version 

All

### Enhancement

Guard currently pick up items/mob drops etc, but never seem to deposit them into their guard tower chests..  Can we make the guards visit their chests occasionally (one a day?) and deposit any non weapons/armour into their chests (for the D-Man to pick up at his leisure :)

Thanks,

**Comment by Raycoms** [comment]
Will open a separate issue for that soon.
