### ISSUE TITLE
Builder stop building on none plain floor

### ISSUE THREAD

**Issue by trzebiaf** [ldtteam/minecolonies#1293]
### Minecolonies version

version 1.11.2-0.8.2786

### Expected behavior

- worker terraform floor or continue building

### Actual behaviour

- builder stop terraform and building

### Steps to reproduce the problem

1. choose an none flat place to build 
2. place a building on none flat final floor (with some natural hole or water). 
3. worker start to work
4. at a moment, worker just stop building or terraforming. fire/hire him, recall or past the night doesn't unlock the worker
5. manually add block to have flaty floor will make worker finish the building

**Comment by Asherslab** [comment]
"none plain" what do you mean by that?

**Comment by trzebiaf** [comment]
Ok bad english --'.

i talk about flat ground.

I edit the message

**Comment by Raycoms** [comment]
If you have a ground where the builder is unable to move he can't build the building unfortunately.
In this case you have to help him out.
