### ISSUE TITLE
Miner won't mine

### ISSUE THREAD

**Issue by fireclaw20** [ldtteam/minecolonies#1295]
### Minecolonies version

version X.X.XXXX or curse 0.8.3056

### Expected behavior

- Mining

### Actual behaviour

- Just standing there doing absolutely nothing

### Steps to reproduce the problem

1. Hire
2. Give him/her the tools
3. He/she goes in mine
4. Just stand there
5. Profit

I made a video to make it easier: https://youtu.be/FK2hgCwr6p0

**Comment by Raycoms** [comment]
Did you try giving him cobble or dirt?

2017-07-13 15:48 GMT-03:00 fireclaw20 <notifications@github.com>:

**Comment by fireclaw20** [comment]
Yes I did, after a restart, so I dont know what fixed it, the restart or giving him dirt

**Comment by Raycoms** [comment]
We have some issues with the miner not requesting completely.
