### ISSUE TITLE
Warehouse worker

### ISSUE THREAD

**Issue by Goten87** [ldtteam/minecolonies#1296]
### Minecolonies version

Future

### Expected behavior

- Worker in warehouse that will sort items
- Worker in warehouse will get items for u

### How it will work

- New Job: Sorter

- You will hire a worker to the warehouse.
When its day and there are items in the warehouse inventory the hired npc will sort the items in the right chest/shelf.
When the Worker is done doing that a massage will showup `Im done sorting the items`

- The inventory of the warehouse can be extended to request items.
When u request a item the NPC hired in the warehouse will pickup the item and bring it to the inventory for u to pickup (a massage can be played if the worker did bring the item: `I have bough the item u asked for`
or `i have bough the items u asked for`

**Comment by Asherslab** [comment]
okay, i understand the idea, any chance you could clean it up a bit? bullet points etc =D

**Comment by Goten87** [comment]
Hope this looks a little nicer @Asherslab

**Comment by Asherslab** [comment]
Yes, thank you very much =D

**Comment by Goten87** [comment]
made a little extra addition as well to the system :P

**Comment by Raycoms** [comment]
Will add separate issue for that (was planned anyway)
