### ISSUE TITLE
EMPTY WAREHOUSE SAYING ITS FULL

### ISSUE THREAD

**Issue by taluseve** [ldtteam/minecolonies#1297]
### Minecolonies version

minecolonies-universal-1.10.2-0.8.3171

### Expected behavior

Delivery man being able to use the new shelves

### Actual behaviour

When delivery man enters warehouse : he says its full or needs to be upgraded

### Steps to reproduce the problem

1. Build Warehouse and delivery man
2. Upgrade warehouse and delivery man to level 5
3. Delivery man will not use new shelve system in warehouse
4. I can put things on the shelf by hand by opening the GUI

I've attached my server startup log

[Serverstartup.txt](https://github.com/Minecolonies/minecolonies/files/1151139/Serverstartup.txt)

THIS IS A SCREENSHOT OF A SINGLE PLAYER WORLD WITH ONLY MINECOLONIES INSTALLED
![screenshot](https://user-images.githubusercontent.com/18486779/28249402-e7d78efa-6a22-11e7-9424-a0c94550c1bc.png)

**Comment by matkapi** [comment]
same here (minecolonies-universal-1.10.2-0.8.3120 in MineColonies TestPack)
warehouse lv 1 / delivery man lv 1

**Comment by Raycoms** [comment]
Have you tried restarting it and have you tried repairing the warehouse
already?

2017-07-16 18:43 GMT-03:00 matkapi <notifications@github.com>:

**Comment by taluseve** [comment]
yes I have tried the repair option

**Comment by Raycoms** [comment]
That is quite strange. Never had that problem. We have to debug that.

2017-07-16 20:20 GMT-03:00 taluseve <notifications@github.com>:

**Comment by taluseve** [comment]
what version of forge are you guys using for testing ....we use forge-1.10.2-12.18.3.2316-universal  on our server

**Comment by Raycoms** [comment]
we're probably quite behind with 12.18.2.2115

2017-07-16 20:57 GMT-03:00 taluseve <notifications@github.com>:

**Comment by taluseve** [comment]
Ill try that version see if I can get it to recreate Forge 2185 Bugs out the Miners they wont dig down Ill test with 2115 see if that works

**Comment by taluseve** [comment]
You guys need to update your forge version.    With a version that far behind none of the other mods will load.

**Comment by taluseve** [comment]
Ok I Rolled back my forge to 2115 and did a fresh start with default configs with NO other mods but mine colonies . it is the same issue. warehouse is full.    I also broke all of the shelves and then had a lvl 5 builder repair the ware house to no avail.    Not sure how else i can put this ........this feature is broken

**Comment by Asherslab** [comment]
mhmmm, fun. i'm gonna debug this

**Comment by Asherslab** [comment]
hey, could you send me your world? (in a .zip) i can't seem to reproduce it myself =D

**Comment by taluseve** [comment]
[New World.zip](https://github.com/Minecolonies/minecolonies/files/1156533/New.World.zip)

this is the singleplayer world

**Comment by taluseve** [comment]
If it helps I Deleted all minecraft files from my PC and rebuilt the game from scratch . I only installed your version of forge and the newest version of minecolonies .  I still have the issue.      Could it be a Java 8 issue?

**Comment by Bigrod9696** [comment]
Any information on this im getting the same thing?

**Comment by taluseve** [comment]
I haven't heard anything back I rolled back to a version before the new shelves...gonna test it with my mods folder

**Comment by Asherslab** [comment]
No, it's not java8 I'm gonna debug this today, (once my internet stops being absolute crap) it has to do with the warehouse / D-Man recognising the shelves

**Comment by taluseve** [comment]
sweet . I look foreward to trying it out

**Comment by Asherslab** [comment]
Should be fixed soonish once it's merged =D you'll need to repair your warehouse

**Comment by marchermans** [comment]
Closed by #1303

**Comment by matkapi** [comment]
Thanks a lot guys
