### ISSUE TITLE
Ressource pack compatibility

### ISSUE THREAD

**Issue by steevmau** [ldtteam/minecolonies#1298]
### Minecolonies version

version 0.8.3167 or curse X.X.XX

### Expected behavior

- Using 32*32 ressrouce pack, in villager gui window to look at his stats.
 (icons.png is 512*512)

### Actual behaviour

- only half is displayed like if it was icons.png with a size of 256*256

### Steps to reproduce the problem

1. install a higher resolution (in my case a 32*32)
2. open dialog GUI with a villager
![2017-07-16_20 10 10](https://user-images.githubusercontent.com/30216966/28250167-e1a5964a-6a62-11e7-97a5-bb66a962c05a.png)

**Comment by Raycoms** [comment]
I think in this case the resourcepack should be compatible with us.

2017-07-16 15:11 GMT-03:00 steevmau <notifications@github.com>:

**Comment by magneticflux-** [comment]
@Raycoms I'm experiencing the same issue, and I believe it stems from the fact that the icons change their pixel coordinates based on the size of the texturepack and Minecolonies doesn't use the correct coordinates or sizes.

I'm using 1.12-0.8.3167.

**Comment by Raycoms** [comment]
We're using the minecraft pixel coordinates and it works, I guess the
resource style somehow changes them?

2017-07-19 0:25 GMT+01:00 Mitchell Skaggs <notifications@github.com>:

**Comment by magneticflux-** [comment]
@Raycoms I think you have to use relative coordinates when you're getting images [here](https://github.com/Minecolonies/minecolonies/blob/67bffca2981eca310aaf6fac6be8357b1a8a78c4/src/main/java/com/minecolonies/coremod/client/gui/WindowCitizen.java#L315). Maybe make a util class that finds the ratio between the resourcepack and vanilla and adjusts positions by that ratio?

**Comment by marchermans** [comment]
@Raycoms you ware using direct Rendering
You Need to check how MC renders this!, it has textures for all of this!

**Comment by Raycoms** [comment]
Back then when I coded this, I copied most of the display code directly
from MC itself. Might be because it was 1.8.9?

2017-07-19 16:06 GMT+01:00 Marc Hermans <notifications@github.com>:

**Comment by marchermans** [comment]
Might be i made mine in 1.8 and later so yeah possible for sure.

**Comment by Raycoms** [comment]
@OrionDevelopment 

```
for (int i = 0; i < citizen.getMaxHealth() / 2; i++)
        {
            @NotNull final Image heart = new Image();
            heart.setImage(Gui.ICONS, EMPTY_HEART_ICON_ROW_POS, HEART_ICON_COLUMN, HEART_ICON_HEIGHT_WIDTH, HEART_ICON_HEIGHT_WIDTH);
            heart.setPosition(i * HEART_ICON_POS_X + HEART_ICON_OFFSET_X, HEART_ICON_POS_Y);
            findPaneOfTypeByID(WINDOW_ID_HEALTHBAR, View.class).addChild(heart);
        }
```

I mean if the other resource pack overwrites Gui.ICONS and puts everything at the same location there shouldn't be a problem at all.

I also took a look in the minecraft code, it seems to make it the same static way.
It just doesn't select "Gui.ICONS" it seems.

**Comment by marchermans** [comment]
Is the size static in pixels?
