### ISSUE TITLE
Multiple Colonies in SSP

### ISSUE THREAD

**Issue by pmardle** [ldtteam/minecolonies#1299]
Had a few requests about adding the ability in SSP for allowing multiple colonies in the same world.

Is there a technical reason we can't do this, or a massive amount of work involved in adding this in as a config option?

Thanks,

**Comment by xavierh** [comment]
Or in SMP

**Comment by xavierh** [comment]
On option maxNumberColoniesPerPlayer default to 1 would be nice.
I suspect the reason why we only allow 1 colony per player is for performance reason.
But in SSP or in server with a low number of player, this could be adjusted.
At the moment a lot of the code assume we only have one colony, I don't think changing that would be trivial.

Also multiple worlds support would be nice too

**Comment by Goten87** [comment]
yeah more colonys will be nice same as other world support
i have a mining world in my SSP and it will be nice if i can add a colony in there with the mining specialty later on xD

**Comment by Wissi** [comment]
Agree, also multiple world/dimensions also. 
For those other mods that add dimension and "space" mods (that was an old request somewhere already).

**Comment by marchermans** [comment]
Yeah ColonyManager has currently Problems handling this Kind of stuff.

**Comment by pmardle** [comment]
Thought that would be the case..

**Comment by marchermans** [comment]
I have a new version for the colonymanager sitting ready to go which takes care of this. But i need people who help me clean up individual prs, i just do not have the time and willpower to the clean up done. See my open pr for the initial request system stuff.

**Comment by Goten87** [comment]
@OrionDevelopment if i know how I can do that but I have No eperience with Java or git :o

**Comment by marchermans** [comment]
@Goten87 you need some experience with both to help. The code is relatively complex to make this kind of stuff possible.

However if you want to learn you can take a look at #1305 and see what @Asherslab is doing there.
