### ISSUE TITLE
InvTweaks Error

### ISSUE THREAD

**Issue by Wervern** [ldtteam/minecolonies#1300]
Attempting to sort Diamond or Glass chests returns error:

[ERROR] [3] Failed to sort container: null (l101 in HandlerSorting.java)

Clearing the chest does not fix the issue, empty chests return same error.

Error does not occur with Wood, Iron, or Gold chests.

### Minecolonies version

version 0.8.8.3

### Expected behavior

- Inventory sort.

### Actual behaviour

- Error message.

### Steps to reproduce the problem

1. Attempt to sort Diamond/Glass chest.
2. No sort, returns error.

**Comment by Goten87** [comment]
i think that is or inventorytweak mod or ironchest mod that is doing that note minecolony

**Comment by Wervern** [comment]
I don't know if it's a conflict with Minecolony or just an issue with InvTweak.

**Comment by Goten87** [comment]
well then backup your world and disable minecolony

**Comment by Wervern** [comment]
That's not really my call, as the issue is coming from the MineColonies Official Test Server.

**Comment by Asherslab** [comment]
Not us thanks =D that's an inventory tweaks class failing, if you really want us to check you'll have to supply a full crash log
