### ISSUE TITLE
[SUGGESTION] Builder chunk loader

### ISSUE THREAD

**Issue by Thanaen** [ldtteam/minecolonies#1301]
Hey there,

I've been playing a long time in the official Minecolonies' server, and now I'm facing an annoying thing:
When I ask my builder to work on something, I have to follow him, as when he goes away, he just fades out with the chunk being unloaded.

A cool thing would be to make the builder generating the chunk he walks in, so he's always able to build stuff even if the player isn't right next to him!

In order to avoid a server full of useless but active builders, it might be clever to allow this "chunk loader" only when the owner of the colony is online!
It would help a lot when the cities are starting to get really big, and when there aren't many human players around!

Hope you'll be interested in this!

**Comment by Raycoms** [comment]
We discussed this quite a lot already.
Unfortunately, we decided to let this depend on the player.
If you want chunkloaders just put them around the colonies.
Sinc 99% of the servers would turn off that feature anyway and the rest can still use any other chunkloading mod.
This way we won't interfere with the actual worker code which is more secure for us.

**Comment by Thanaen** [comment]
Well, I didn't know chunk loaders were in the game, so I'll try to use them!
Thanks 👍
