### ISSUE TITLE
I don't have permission to do anything in my colony

### ISSUE THREAD

**Issue by JakeT3hSnake** [ldtteam/minecolonies#1307]
### Minecolonies version

0.8.8.3
### Expected behavior

- Hop onto the server and have fun building and doing other things in your own personal colony
### Actual behavior

- "You have no permission to do this in this colony!" Also, I'm the owner of the colony so I know I wasn't removed from the list.

### Steps to reproduce the problem

1. Get on the server
2. Try to break a block or open a chest in your colony
3. Realize that you don't have permissions for some reason
4. Cry

**Comment by Raycoms** [comment]
Can you ask your admin to execute /mc colony refresh <yourname> ?

**Comment by JakeT3hSnake** [comment]
Ok, I'll try that. Thanks
