### ISSUE TITLE
Warehouse full message despite being empty.

### ISSUE THREAD

**Issue by Swannicus** [ldtteam/minecolonies#1308]
### Minecolonies version

1.10.2-0.8.3120
https://minecraft.curseforge.com/projects/minecolonies-testpack?gameCategorySlug=modpacks&projectID=250424

### Expected behavior

- Deliverman takes items to/from the warehouse

### Actual behaviour

- Deliveryman complains that the warehouse is full, despite it being empty.

### Steps to reproduce the problem

1. Install the minecolonies pack above
2. Build a warehouse and deliveryman hut.
3. Watch him fail to deliver items and repeatedly send the message "The Warehouse is full, please upgrade or make space."
4. Profit
I have attempted to replace a couple of the selves with chests, and I have also tried hitting the repair button.  Neither seem to work.
![image](https://user-images.githubusercontent.com/7967475/28482593-0640fe5e-6e37-11e7-8eca-401b50f9bb08.png)
![image](https://user-images.githubusercontent.com/7967475/28482607-183dae4a-6e37-11e7-8f0e-628e1ddb544d.png)
![image](https://user-images.githubusercontent.com/7967475/28482617-29128d08-6e37-11e7-9e41-ff7c1fd3feaa.png)
![image](https://user-images.githubusercontent.com/7967475/28482651-54b0a1b6-6e37-11e7-8e26-3c34c091ca9f.png)

**Comment by Raycoms** [comment]
please use the newest beta where this should be solved.

2017-07-21 22:10 GMT+01:00 Swannicus <notifications@github.com>:

**Comment by Asherslab** [comment]
you'll need to repair your warehouse when you do^^

**Comment by Swannicus** [comment]
Thank you, I guess the pack on curse wasn't updated as I just downloaded it last night.
Edit: Actually it looks like you guys just fixed this, nice turn around time!

**Comment by Asherslab** [comment]
haha, it was a simple issues =D
