### ISSUE TITLE
Can not build the supply ship

### ISSUE THREAD

**Issue by h3llobob** [ldtteam/minecolonies#1310]
### Minecolonies version

version: 0.8.2971

### Expected behavior

- The ability to be able to craft the supply ship with 5 oak wood boats

### Actual behavior

- When putting five boats together the nothing was able to be crafted/nothing occurred in the "product" box.

### Steps to reproduce the problem

1. Start a New World with the mods just enough items, optifine, The one probe, and minecolonies.
2. After having five oak boats, put into the bottom row and the left and right in the middle row.

*Note* The version of minecraft is 1.12 and I am using forge.

**Comment by Raycoms** [comment]
Still occurring, if yes please reopen.
