### ISSUE TITLE
Builder does not use correct tool for wooden stairs

### ISSUE THREAD

**Issue by magneticflux-** [ldtteam/minecolonies#1313]
### Minecolonies version

- Version 0.8.3167, MC 1.12, Forge 14.21.1.2423

### Expected behavior

- The builder should switch to his iron axe to mine wooden stairs

### Actual behaviour

- The builder uses his pickaxe, which is much slower. This exacerbates the time it takes to demolish a building roof, for instance, when rotating a building.

### Steps to reproduce the problem

1. Build a building with wooden steps in it
2. Break the hut block and replace it, but rotated
3. Give the builder a pickaxe and regular axe
4. Observe the speed difference between breaking wooden planks and wooden stairs

**Comment by Raycoms** [comment]
Will open a separate issue for that soon.
