### ISSUE TITLE
Builder Still requesting an item

### ISSUE THREAD

**Issue by jc4me** [ldtteam/minecolonies#1316]
### Minecolonies version

version X.X.XXXX or curse X.X.XX

### Expected behavior

I cancel an upgrade because I do not have the material or is too hard to get at the moment. Thus I expect to cancel the upgrade and the builder will pick a new hut to build. 

### Actual behaviour

Just stands there asking for the item when I already canceled the project. 

### Steps to reproduce the problem

1. Upgrade building 
2. Don't give material when requested
3. Cancel the upgrade
4. Currently just stands there waiting for the object

**Comment by MineShadow7** [comment]
Try to relog or rehire. Should help

**Comment by jc4me** [comment]
Thanks yea, relogging reset it!
