### ISSUE TITLE
Viewing the TH Boundary in the build tool

### ISSUE THREAD

**Issue by pmardle** [ldtteam/minecolonies#1317]
Not sure if this is intentional but when building walls, the TH boundary does not show up ?

Surely it should show up whenever in the Build Tool, regardless of what building/decoration/waypoint type you are trying to construct?

(Reported to me by through YouTube, haven't validated this myself)

**Comment by Raycoms** [comment]
Yes, only when building buildings.
Can easily be changed

Am Dienstag, 25. Juli 2017 schrieb pmardle :

**Comment by pmardle** [comment]
Yes please... For walls especially many people build them at the boundary :)
