### ISSUE TITLE
Builder Stop build, Workorders Do not assign Builder

### ISSUE THREAD

**Issue by Spyro1502** [ldtteam/minecolonies#1320]
### Minecolonies version

version 1.11.2-0.8.3184

### Expected behavior

- Builder work correctly

### Actual behaviour

- The Builder stopped build, when looking in the townhall, in workorders, it's said that the building are on waitlist but no workers are selected for

### Steps to reproduce the problem
(i don't really know)_, here is a historic of what I did_

>- I built the buider hut
>- I built the townhall
>- I upgraded the townhall
>- I built the mine
>- I tried to build a fisherman hut but from this moment the bug happen and no any build is available, I tried to break and rebuild the worker hut but it did nothing

**Comment by Raycoms** [comment]
that's really strange. If this is still an issue please reopen.
