### ISSUE TITLE
Items deleted

### ISSUE THREAD

**Issue by RoyalRedKing** [ldtteam/minecolonies#1322]
### Minecolonies version

version 0.8.3120 v2 or curse X.X.XX

### Expected behavior

- Put Stuff in another rack if full. racks dont count as  double chest only single so stuff gets place as if were single chest

### Actual behaviour

- tries to put stuff in full rack. items get deleted since its full

### Steps to reproduce the problem

1. put 1 stone in dman
2. locate rack they put it in
3. give them a double chest of stone 
4. only 1 single chest of stone will be safe
5. if not being replicated contact me on the server RedRebelKing and ill show u in my warehouse

**Comment by Asherslab** [comment]
@Raycoms I'll try take a look at this when I can, any thoughts?

**Comment by Raycoms** [comment]
I think th transfer method with shift click has a bug

**Comment by Asherslab** [comment]
I thought he was talking about when the D-Man puts items in?

**Comment by Raycoms** [comment]
Ahh I misunderstood yes, strange

**Comment by Raycoms** [comment]
Still happening with the newest version @RoyalRedKing ?

**Comment by Raycoms** [comment]
I will close it, please reopen if reaccuring
