### ISSUE TITLE
Shop Bug

### ISSUE THREAD

**Issue by RoyalRedKing** [ldtteam/minecolonies#1323]
### Minecolonies version

version 8.3129 v2
### Expected behavior

- (not a Minecolonies bug) stop when you dont have enough inv space

### Actual behaviour

- when removing items from your shop with a full inv items get deleted. for instence 2 inv worth of cobble u only get 1 inv of cobble rest is deleted

### Steps to reproduce the problem

1. put 2 inv worth of cobble in shop
2. take the 2 inv of cobble out
3. only get 1 inv and no more cobble in shop or floor
4. Profit

**Comment by Raycoms** [comment]
Please report not minecolonies related bugs to the discord or forums
