### ISSUE TITLE
Farm Automatic Field Selection 

### ISSUE THREAD

**Issue by Electrocutor** [ldtteam/minecolonies#1325]
### Minecolonies version

version 0.8.3210v2

### Expected behavior

- Farm will auto-select a valid Field when one is available

### Actual behaviour

- Farm auto-selects a Field that doesn't have a seed specified even though there are many that already do.

### Steps to reproduce the problem

1. Build 2+ Fields
2. Build level 1 Farm
3. Place seed in only 1 of the fields (I think the farthest from the farm, but am not certain on the auto-select criteria for choosing)

**Comment by Electrocutor** [comment]
### Addendum
It appears that the code dealing with field assignment between multiple farms and multiple fields in an area is extremely buggy. To the point that it gets into a state whether set to Manual or Automatic where the farmers simply do not do anything and the fields seem to be locked with multiple farmers being assigned to a single field and showing the hired farmers that are working for other huts in different ones.

For example, my level 1 farm had a worker that was somehow auto-assigned to 8 fields, but he would not harvest any of them and no matter how much I tried to unset them, they would always revert back after some time.

**Comment by Raycoms** [comment]
Will open a separate issue for that soon.
