### ISSUE TITLE
HarvestCraft Bakery Compatibility

### ISSUE THREAD

**Issue by Electrocutor** [ldtteam/minecolonies#1327]
[Enhancement Request][Mod Support]

### Minecolonies version

version 0.8.3210v2

### Expected behavior

- The Bakery should support creating any custom food items with bakery-like words in their names and recipes that can be accomplished with just a crafting table and furnace. For example, carrot cake.

### Actual behaviour

- The bakery only supports vanilla minecraft's bread, cake, and cookies.

### Addendum
The baker should also be able to produce any requisite food items needed in the recipe (recursive), but request that non-food items be provided. For example, in HarvestCraft many recipes require containers such as pots, which are needed for the recipes.

**Comment by Raycoms** [comment]
I don't agree, baker is baker. 
This automatic recipe stuff is planned for the cook later. 

_Sent from my Oneplus A0001 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Electrocutor** [comment]
Then what would be the point of the Baker after the Cook is done? I had thought the Baker made baked food and the Cook was going to make cooked food (like steak, chicken, etc)?

**Comment by Asherslab** [comment]
Medievalness

**Comment by Asherslab** [comment]
@Raycoms are we closing this

**Comment by Raycoms** [comment]
Yes please

**Comment by kedamono** [comment]
It's a 4 step process to make bread with Pam's Harvestcraft:

1. Using a mortal a pestle, grind a grain into flour.
2. Using a pot, turn water into salt.
3. Using a mixing bowl, combine flour, salt, and water into dough.
4. Bake the dough into bread.

The benefit of this process is that you get 1 bread per 1 wheat, not 1 per 3.

**Comment by YoutuberNL300** [comment]
yes
