### ISSUE TITLE
Build Tool Building Flipping

### ISSUE THREAD

**Issue by Electrocutor** [ldtteam/minecolonies#1330]
[Enhancement Request]

Add the ability to flip a building horizontally. The building itself would need some kind of 'flipped' tag so that the builder would know to switch left with right during build/upgrade/repair.

**Comment by Raycoms** [comment]
You mean, mirroring?
That's implemented already

**Comment by Electrocutor** [comment]
It is? I only see rotate, four cardinal directions, and up/down on the tool?

[Edit]
I found it. Now I feel stupid... Please, remove this enhancement request.

**Comment by Raycoms** [comment]
Just click in the middle
