### ISSUE TITLE
Error in Clicking Building Request Blocks

### ISSUE THREAD

**Issue by redtonM** [ldtteam/minecolonies#1331]
### Minecolonies version
It does it on Direwolf 20 1.10.2 pack and Infinity Pack 1.10.2
-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_141, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2433479432 bytes (2320 MB) / 4026531840 bytes (3840 MB) up to 4026531840 bytes 
	FML: MCP 9.32 Powered by Forge 12.18.3.2316 93 mods loaded, 93 mods active
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2316-universal.jar) 
	UCHIJAAAA	Forge{12.18.3.2316} [Minecraft Forge] (forge-1.10.2-12.18.3.2316-universal.jar) 

### Expected behavior

- Trying to open the main creation blocks of various buildings: (Warehouse in this instance, but also happens on other buildings) suppose to open it's inventory  & display other options.  

Sidenote: Thanks for changing those chests to rack reduces lag.  Might want to create them different than chests just increase the capacity after upgrading warehouse.  They could just be in one block position just double capacity save a lot of problems with checking.

### Actual behavior
Either one of two things happens.

- Ignores your clicking on block - Until you log off and back on.
  or 
- Shuts the server down 

### Steps to reproduce the problem
Unknown it's a matter of timing .. I think the permission is getting lost for ownership of colony

[crash-2017-07-30_11.53.31-client.txt](https://github.com/Minecolonies/minecolonies/files/1185854/crash-2017-07-30_11.53.31-client.txt)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.minecolonies.coremod.colony.permissions.Permissions$View.hasPermission(Permissions.java:950)
	at com.minecolonies.coremod.colony.permissions.Permissions$View.hasPermission(Permissions.java:1057)
	at com.minecolonies.coremod.blocks.AbstractBlockHut.func_180639_a(AbstractBlockHut.java:206)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:410)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1518)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2184)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1961)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['RedTon'/566, l='MpServer', x=-243.38, y=63.00, z=309.82]]
	Chunk stats: MultiplayerChunkCache: 625, 625
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-232,64,256), Chunk: (at 8,4,0 in -15,16; contains blocks -240,0,256 to -225,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 1290693 game time, 97486 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 134 total; [EntityItem['item.item.rottenFlesh'/41728, l='MpServer', x=-191.03, y=63.00, z=265.40], EntityItem['item.item.egg'/39685, l='MpServer', x=-200.51, y=63.00, z=361.35], EntityPig['Pig'/261, l='MpServer', x=-219.30, y=66.00, z=252.50], EntityHorse['Horse'/262, l='MpServer', x=-223.75, y=67.00, z=243.60], EntityPig['Pig'/263, l='MpServer', x=-212.43, y=65.00, z=250.69], EntitySpider['Spider'/41224, l='MpServer', x=-179.33, y=63.00, z=329.24], EntityBat['Bat'/41745, l='MpServer', x=-289.86, y=38.51, z=322.33], EntityZombie['Zombie'/41239, l='MpServer', x=-205.50, y=52.00, z=236.50], EntityCreeper['Creeper'/41496, l='MpServer', x=-239.54, y=40.00, z=232.21], EntityBat['Bat'/35358, l='MpServer', x=-241.83, y=40.10, z=335.40], EntityPig['Pig'/288, l='MpServer', x=-198.52, y=64.00, z=247.18], EntityPig['Pig'/295, l='MpServer', x=-195.73, y=63.00, z=280.01], EntitySquid['Squid'/40999, l='MpServer', x=-277.60, y=56.00, z=347.60], EntityPig['Pig'/297, l='MpServer', x=-187.94, y=63.00, z=321.98], EntityPig['Pig'/298, l='MpServer', x=-186.81, y=63.00, z=322.83], EntityChicken['Chicken'/300, l='MpServer', x=-199.83, y=63.00, z=364.17], EntityChicken['Chicken'/301, l='MpServer', x=-200.70, y=63.00, z=361.00], EntityCow['Cow'/302, l='MpServer', x=-201.54, y=63.00, z=360.40], EntityCow['Cow'/303, l='MpServer', x=-203.93, y=63.00, z=365.92], EntityCow['Cow'/304, l='MpServer', x=-205.18, y=63.00, z=363.52], EntityCow['Cow'/305, l='MpServer', x=-200.10, y=63.00, z=360.31], EntityCow['Cow'/306, l='MpServer', x=-204.98, y=63.00, z=360.45], EntitySkeleton['Skeleton'/42290, l='MpServer', x=-248.50, y=36.00, z=344.50], EntityCow['Cow'/307, l='MpServer', x=-203.00, y=63.00, z=365.39], EntityCow['Cow'/308, l='MpServer', x=-202.45, y=63.00, z=364.39], EntitySheep['Sheep'/309, l='MpServer', x=-200.27, y=63.00, z=370.17], EntityCreeper['Creeper'/35385, l='MpServer', x=-256.30, y=45.00, z=333.70], EntityCreeper['Creeper'/42297, l='MpServer', x=-317.50, y=30.00, z=383.50], EntityChicken['Chicken'/314, l='MpServer', x=-200.54, y=63.00, z=367.97], EntityBlitz['Blitz'/35386, l='MpServer', x=-257.50, y=45.00, z=333.24], EntityCreeper['Creeper'/42298, l='MpServer', x=-316.50, y=30.00, z=377.50], EntitySheep['Sheep'/315, l='MpServer', x=-200.55, y=63.00, z=367.24], EntityCreeper['Creeper'/42299, l='MpServer', x=-316.50, y=30.00, z=380.50], EntitySkeleton['Skeleton'/41788, l='MpServer', x=-289.50, y=37.00, z=297.50], EntityZombie['Zombie'/42300, l='MpServer', x=-314.75, y=30.00, z=381.54], EntityCreeper['Creeper'/41278, l='MpServer', x=-170.50, y=29.00, z=254.50], EntityCreeper['Creeper'/42302, l='MpServer', x=-169.50, y=51.00, z=382.50], EntitySkeleton['Skeleton'/41535, l='MpServer', x=-208.50, y=26.00, z=357.50], EntityCreeper['Creeper'/42303, l='MpServer', x=-170.50, y=51.00, z=387.50], EntityZombie['Zombie'/42304, l='MpServer', x=-170.50, y=51.00, z=382.50], EntitySkeleton['Skeleton'/42309, l='MpServer', x=-317.50, y=33.00, z=365.50], EntitySkeleton['Skeleton'/42310, l='MpServer', x=-317.50, y=33.00, z=365.50], EntitySkeleton['Skeleton'/42311, l='MpServer', x=-318.50, y=33.00, z=362.50], EntityPig['Pig'/330, l='MpServer', x=-186.52, y=63.00, z=282.28], EntitySpider['Spider'/41802, l='MpServer', x=-216.50, y=24.00, z=367.50], EntitySheep['Sheep'/335, l='MpServer', x=-187.61, y=63.00, z=295.79], EntityPig['Pig'/336, l='MpServer', x=-173.68, y=63.00, z=288.44], EntityPig['Pig'/337, l='MpServer', x=-195.76, y=63.00, z=297.81], EntityCreeper['Creeper'/41815, l='MpServer', x=-321.50, y=56.00, z=261.50], EntityWitch['Witch'/41560, l='MpServer', x=-254.27, y=39.00, z=338.50], EntityWitch['Witch'/41561, l='MpServer', x=-255.50, y=38.00, z=339.50], EntityBat['Bat'/41824, l='MpServer', x=-247.49, y=35.04, z=342.75], EntitySheep['Sheep'/353, l='MpServer', x=-184.57, y=62.09, z=322.03], EntityBat['Bat'/42337, l='MpServer', x=-210.62, y=41.08, z=310.94], EntityCreeper['Creeper'/42083, l='MpServer', x=-298.50, y=31.00, z=301.50], EntityBat['Bat'/25191, l='MpServer', x=-256.25, y=48.10, z=335.75], EntityCreeper['Creeper'/41065, l='MpServer', x=-186.50, y=21.00, z=241.50], EntityFlicker['entity.arsmagica2.Flicker.name'/42346, l='MpServer', x=-276.74, y=44.88, z=364.72], EntityItem['item.item.egg'/39534, l='MpServer', x=-199.75, y=63.00, z=363.76], EntityCreeper['Creeper'/36722, l='MpServer', x=-253.20, y=51.00, z=337.53], EntityCartChest['Chest Cart'/3955, l='MpServer', x=-339.50, y=31.06, z=465.50], EntityRabbit['Rabbit'/374, l='MpServer', x=-174.62, y=67.00, z=357.51], EntityPig['Pig'/375, l='MpServer', x=-164.76, y=69.00, z=366.57], EntityFlicker['entity.arsmagica2.Flicker.name'/42108, l='MpServer', x=-225.25, y=42.50, z=256.25], EntityCreeper['Creeper'/41598, l='MpServer', x=-289.50, y=20.00, z=368.50], EntityBat['Bat'/42112, l='MpServer', x=-211.25, y=27.10, z=351.75], EntityZombie['Zombie'/41861, l='MpServer', x=-265.50, y=32.00, z=288.50], EntitySkeleton['Skeleton'/24973, l='MpServer', x=-241.77, y=38.00, z=334.50], EntityFallingBlock['Falling Block'/398, l='MpServer', x=-121.50, y=29.50, z=295.50], EntitySkeleton['Skeleton'/24974, l='MpServer', x=-253.51, y=39.00, z=323.30], EntityFallingBlock['Falling Block'/399, l='MpServer', x=-121.50, y=29.50, z=295.50], EntitySquid['Squid'/41871, l='MpServer', x=-180.67, y=56.00, z=329.23], EntityCartChest['Chest Cart'/403, l='MpServer', x=-123.50, y=33.06, z=330.50], EntityZombie['Zombie'/41878, l='MpServer', x=-175.50, y=26.00, z=245.50], EntityCartChest['Chest Cart'/156, l='MpServer', x=-334.50, y=28.06, z=458.50], EntityBat['Bat'/42142, l='MpServer', x=-300.53, y=31.41, z=357.19], EntityBat['Bat'/42143, l='MpServer', x=-263.08, y=41.17, z=239.25], EntityPig['Pig'/160, l='MpServer', x=-314.36, y=71.00, z=269.46], EntityBat['Bat'/42144, l='MpServer', x=-257.21, y=43.23, z=243.36], EntityCartChest['Chest Cart'/417, l='MpServer', x=-110.50, y=26.06, z=345.50], EntityPig['Pig'/161, l='MpServer', x=-315.68, y=71.00, z=266.54], EntityCartChest['Chest Cart'/420, l='MpServer', x=-103.50, y=26.06, z=352.50], EntityPig['Pig'/166, l='MpServer', x=-291.44, y=70.00, z=238.70], EntityPig['Pig'/167, l='MpServer', x=-296.77, y=71.00, z=250.69], EntityPig['Pig'/168, l='MpServer', x=-293.23, y=71.00, z=251.71], EntityCreeper['Creeper'/28329, l='MpServer', x=-256.89, y=45.00, z=332.99], EntityAshen['Ashen'/42153, l='MpServer', x=-167.50, y=19.00, z=338.50], EntityPig['Pig'/170, l='MpServer', x=-300.37, y=71.00, z=258.77], EntityRabbit['Rabbit'/171, l='MpServer', x=-301.34, y=70.00, z=277.20], EntitySheep['Sheep'/172, l='MpServer', x=-301.18, y=66.00, z=293.56], EntityVillager['Villager'/173, l='MpServer', x=-263.24, y=62.56, z=279.28], EntityVillager['Villager'/174, l='MpServer', x=-291.70, y=64.00, z=296.55], EntityCartChest['Chest Cart'/430, l='MpServer', x=-83.50, y=28.06, z=338.50], EntityCartChest['Chest Cart'/431, l='MpServer', x=-87.50, y=26.06, z=350.50], EntityZombie['Zombie'/42162, l='MpServer', x=-316.71, y=40.00, z=389.50], EntityCartChest['Chest Cart'/179, l='MpServer', x=-289.50, y=33.50, z=409.50], EntityCartChest['Chest Cart'/440, l='MpServer', x=-77.50, y=25.06, z=290.50], EntitySkeleton['Skeleton'/41145, l='MpServer', x=-276.50, y=40.00, z=375.50], EntitySheep['Sheep'/186, l='MpServer', x=-286.15, y=72.00, z=257.83], EntityCartChest['Chest Cart'/443, l='MpServer', x=-77.50, y=27.06, z=321.50], EntityRabbit['Rabbit'/187, l='MpServer', x=-284.02, y=71.00, z=255.57], EntitySkeleton['Skeleton'/10428, l='MpServer', x=-256.34, y=50.00, z=351.49], EntitySpider['Spider'/42174, l='MpServer', x=-222.50, y=44.00, z=233.50], EntitySheep['Sheep'/192, l='MpServer', x=-282.40, y=63.00, z=376.72], EntitySheep['Sheep'/195, l='MpServer', x=-274.56, y=64.00, z=387.00], EntityCreeper['Creeper'/41927, l='MpServer', x=-266.50, y=28.00, z=390.50], EntityPlayerSP['RedTon'/566, l='MpServer', x=-243.38, y=63.00, z=309.82], EntityPig['Pig'/204, l='MpServer', x=-265.80, y=70.00, z=255.50], EntityCitizen['Riley S. Harris'/205, l='MpServer', x=-257.82, y=66.94, z=298.40], EntityCitizen['Natasha H. Ginter'/207, l='MpServer', x=-265.50, y=63.00, z=323.54], EntitySkeleton['Skeleton'/41679, l='MpServer', x=-213.50, y=25.00, z=366.50], EntityCreeper['Creeper'/41681, l='MpServer', x=-285.50, y=30.00, z=372.50], EntitySkeleton['Skeleton'/32727, l='MpServer', x=-251.70, y=50.00, z=339.86], EntitySkeleton['Skeleton'/32728, l='MpServer', x=-252.80, y=50.00, z=336.44], EntityBat['Bat'/41435, l='MpServer', x=-298.39, y=33.10, z=385.61], EntityPig['Pig'/220, l='MpServer', x=-249.45, y=67.00, z=239.06], EntityHorse['Horse'/221, l='MpServer', x=-251.85, y=68.00, z=241.13], EntitySheep['Sheep'/222, l='MpServer', x=-255.27, y=68.00, z=240.42], EntitySheep['Sheep'/223, l='MpServer', x=-255.76, y=69.00, z=266.50], EntityCitizen['Rose U. Goring'/225, l='MpServer', x=-246.50, y=63.00, z=330.69], EntityCitizen['Adeline D. Audlington'/229, l='MpServer', x=-216.42, y=64.00, z=280.50], EntitySkeleton['Skeleton'/41189, l='MpServer', x=-165.22, y=62.55, z=319.50], EntitySquid['Squid'/41959, l='MpServer', x=-193.48, y=61.48, z=336.95], EntitySquid['Squid'/41960, l='MpServer', x=-195.09, y=61.85, z=334.96], EntityZombie['Zombie'/42227, l='MpServer', x=-285.50, y=20.00, z=383.50], EntityZombie['Zombie'/42228, l='MpServer', x=-285.50, y=20.00, z=380.50], EntityPig['Pig'/245, l='MpServer', x=-234.72, y=67.00, z=236.64], EntityHorse['Horse'/246, l='MpServer', x=-218.10, y=66.00, z=234.79], EntityPig['Pig'/247, l='MpServer', x=-240.16, y=68.00, z=262.58], EntityBat['Bat'/25848, l='MpServer', x=-256.44, y=48.10, z=335.75], EntityZombie['Zombie'/42232, l='MpServer', x=-267.50, y=29.00, z=389.50], EntityCitizen['Charity O. Battle'/249, l='MpServer', x=-234.52, y=63.00, z=364.27], EntitySkeleton['Skeleton'/42233, l='MpServer', x=-247.50, y=29.00, z=383.50], EntityCitizen['Elizabeth U. Clifford'/254, l='MpServer', x=-235.24, y=63.00, z=375.70]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:400)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Raycoms** [comment]
Doe this happen regularly?
And does this happen with any of the town chests?
Are you the owner of the colony?

**Comment by Raycoms** [comment]
I will close this, I think it has been resolved. At least a refresh of the colony should resolve it

**Comment by redtonM** [comment]
Doe this happen regularly?about every 12 hrs of play avg or so it could be two days then happen two times in same hour.

And does this happen with any of the town chests?Yeah happens on other chests as well but because of it randomly happens  it happens on ones you use most often

Are you the owner of the colony?Yes I am the only creator and owner I am playing by myself on that flavor of Minecraft.

 

    On Monday, August 28, 2017 7:53 AM, Raycoms <notifications@github.com> wrote:
 

 I will close this, I think it has been resolved. At least a refresh of the colony should resolve it—

**Comment by Raycoms** [comment]
Does /mc colony refresh or restarting solve it?
