### ISSUE TITLE
Issue in SMP

### ISSUE THREAD

**Issue by Exowolfas** [ldtteam/minecolonies#1332]
### Minecolonies version

minecolonies-universal-1.11.2-0.8.1784
forge-1.11.2-13.20.1.2425-universal

### Expected behavior

Must craft and put chests on recipes

### Actual behaviour

After crafting any recipe and putting it on a fast panel, it disappears, and the characters drop out the ingredients

### Steps to reproduce the problem

1. This issue exist only in SMP, in SSP mode working how it must. 
2. I created a new world with only one mod: minecolonies.

**Comment by Raycoms** [comment]
I don't understand, fast panel?

**Comment by Exowolfas** [comment]
quick bar* or inventory, crafted item just disappear and character drop out the ingredients

**Comment by Raycoms** [comment]
Can you make a video of this?

2017-07-30 21:15 GMT+01:00 Exowolfas <notifications@github.com>:

**Comment by Exowolfas** [comment]
Sure
https://youtu.be/y2DHN5GNxNI

**Comment by Exowolfas** [comment]
ok, i find the way out, forge was not working) sry, ty for help, close thread
