### ISSUE TITLE
More Realistic/Smarter D-Man System

### ISSUE THREAD

**Issue by ghost** [ldtteam/minecolonies#1337]
I had an idea that would him be more like a real mailman. 

- Start at the warehouse
- Pick up as many things as he can that need to be delivered. The earliest ordered things would take priority.
- Go around to every house/worker hut (probably going from one to the next closest that he hasn't visited yet)
- Check the "mailbox" for things to take to the warehouse, while also dropping off his deliveries.
- If his inventory is filled, he should stop at the warehouse, empty it, and continue where he left off. 
- When he finishes a round he could either wait around until he is needed, or just do it again.
- Also there should be a way to set which houses he visits on a round (like guard patrols)

The main difference is that he doesn't stop at the warehouse after checking a house if he doesn't need to, and all the houses are checked in order instead of randomly.

**Comment by MineShadow7** [comment]
Isn't that system slower?

**Comment by Asherslab** [comment]
This kind of stuff should probably be thought about and done after the DMan 2.0 is done

**Comment by ghost** [comment]
The things would be dropped of into the warehouse a little slower, but in general it would be faster because there would be much less walking to and from houses, and it would not be random. Large deliveries from the warehouse like the materials of a house would probably be slower.

**Comment by owghard** [comment]
sugestion: in warehouse only one chest for other items to dump.And new item "Wand memorestore" to memore storable items inside oter chests.

**Comment by Asherslab** [comment]
memore?

**Comment by Raycoms** [comment]
I will close this.
Please note that we're working on a complete request system. I will also create some issues in favor of that.
