### ISSUE TITLE
Exception caught during firing event when closing server

### ISSUE THREAD

**Issue by FiveEYZ** [ldtteam/minecolonies#1338]
### Minecolonies version

minecolonies-universal-1.12-0.8.3238
forge-1.12-14.21.1.2428-universal

### Expected behavior

no error when stopping server

### Actual behaviour

Sometimes when I shutdown the server after a couple of hours uptime,
I see this error in console:

https://gist.github.com/FiveEYZ/f4cbaadd08cb7eaab3aaf553013d7ebd

### Steps to reproduce the problem

1. XYZ
2. ZYX
3. ...
4. Profit

**Comment by Raycoms** [comment]
Please report that to sponge, I can't see anything minecolonies related
there

**Comment by FiveEYZ** [comment]
sorry wrong gist, here is the right one:
https://gist.github.com/FiveEYZ/260ba61c70d4613d885de400beb1cdee

the gist link is from line 276 in this log;
http://paste.ubuntu.com/25216218/

**Comment by Raycoms** [comment]
@Asherslab look, I bet that causes the colony owner going missing!

**Comment by Asherslab** [comment]
Hey, @FiveEYZ this is only Sometimes? or always?
