### ISSUE TITLE
Hemp seed dont colect.

### ISSUE THREAD

**Issue by owghard** [ldtteam/minecolonies#1341]
### Minecolonies version

version 1.11.2-0.8.3293

Farmer dont colect hemp seed from immersive enginering

**Comment by Raycoms** [comment]
I don't understand.
Please reopen if still relevant.

**Comment by owghard** [comment]
Farmer does not collect seeds from immersive enginering.
Your farmer only work with potatos carrots and wheat seed.

Does not collect seeds cotton from Natura or hemp seeds from Immersive enginering. I dont test other mods

**Comment by Raycoms** [comment]
What do you want to say with "he does not collect them". If you put them in
the scarecrow and give him seeds he should farm it.

2017-08-29 15:33 GMT+01:00 owghard <notifications@github.com>:

**Comment by owghard** [comment]
I know. It work perfect with carrots, pottatos and wheat. But it dont work with other seeds

**Comment by Raycoms** [comment]
It works well with all Pams harvestcraft seed. it Should work with those as
well. Will have to test it.

2017-08-29 15:38 GMT+01:00 owghard <notifications@github.com>:

**Comment by owghard** [comment]
You need prof? I must meke move to you be know?

**Comment by Raycoms** [comment]
Sure, if I can see a video I can see whats wrong.
Could you additionally provide your client logs?

2017-08-29 15:39 GMT+01:00 owghard <notifications@github.com>:

**Comment by owghard** [comment]
move: https://1drv.ms/u/s!AiF3dn5FfcZ0nkTKGhlOdINmV-fm
log: https://1drv.ms/u/s!AiF3dn5FfcZ0nkWrgJPUteBzePGa

**Comment by Raycoms** [comment]
Okay, this seems to be related to some "item pick up" bugs. I will take a
look at this later.

2017-08-29 16:49 GMT+01:00 owghard <notifications@github.com>:

**Comment by gazpachoking** [comment]
Is the farmer meant to work with immersive engineering hemp now (still doesn't seem to work on latest version)? Hemp works a bit different than other plants, it's more like sugar cane, where it grows 2 blocks tall, and you cut off the top block to harvest.
