### ISSUE TITLE
Miners Stop Mining

### ISSUE THREAD

**Issue by Electrocutor** [ldtteam/minecolonies#1343]
### Minecolonies version
1.10.2-0.8.3210

### Expected behavior
Miner Mines

### Actual behaviour
Miner Doesn't Mine

### Steps to reproduce the problem
This has happened on all my miners at all levels at some point in time. Sometimes it is many days before it occurs, sometimes it is a few minutes after hiring.

### Addendum - Clarifications
The miner's inventory contains:
- 1 stack x64 dirt
- 1 stack x64 cobble
- 1 stack x64 oak plank
- 1 stack x64 oak slab
- 1 stack x64 oak fence
- 1 stack x64 torch
- 1 undamaged stone pickaxe
- 1 undamaged stone shovel

Upon night-time, miner will return home. When morning comes, it will return to exactly the same spot and do nothing.

Upon recall worker, miner will teleport then run back to exactly the same spot and do nothing.

If you remove every single item from its inventory, it will not say anything, nor will it attempt to even get a pickaxe, it will just run right back to the exact same spot and do nothing. This happens regardless of night-day cycle-reset or recall worker.

If you fire and re-hire, then the miner will abandon that spot and once again work properly for an undetermined amount of time, but shortly after will once again get stuck in a new spot and simply do nothing.

This has happened on 100% of my miners, but the time each took to reach this state varied widely and I am unable to determine any kind of pattern of what causes it. Having to fire and rehire miners sometimes 10 to 20 times in a single play session is very annoying.

This has all happened on the official server. I've not had this occur on my single player games yet, but have far fewer hours into them as well.

**Comment by Raycoms** [comment]
Is it possible it reaches a material it can't mine, does the game log say
anything in those moments?

**Comment by Electrocutor** [comment]
No, it even happens at depth level 1. Where should I look for a local log that would have anything useful while playing on the server?

**Comment by Raycoms** [comment]
The local log doesn't help, we would need the server log.
Does it also happen while mining vertically?

**Comment by Electrocutor** [comment]
Not that I've seen, only when actually mining, and not when digging depth levels.

**Comment by Raycoms** [comment]
Are you using any additional mods like railcraft or any mod that adds other
underground blocks and ores?

**Comment by Electrocutor** [comment]
Of course; like I said this is on the official server; so I am using the server's modpack.

**Comment by Tezorian** [comment]
I have also seen this behavior. Turns out it needed something, but wasn't asking for it. Not even after a recall. After a recall it would just go to the same spot and idle. After emptying their entire inventory, it would instantly say "I need cobblestone" or something similar.

**Comment by Electrocutor** [comment]
This is different from that as I had both given everything it could possible need as well as removed everything from its inventory.

The issue where NPCs do not ask for what they need nor try to go get it is something that affects all the workers. This issue affects the miner alone as far as I have ever seen and behaves differently.

**Comment by Raycoms** [comment]
Will open a separate issue for that soon.
