### ISSUE TITLE
[Feature] Colony.dat purging

### ISSUE THREAD

**Issue by Raycoms** [ldtteam/minecolonies#1354]
Currently, we store like unlimited save copies of the colonies.dat

We should limit that, either by amount or by date.

**Comment by Asherslab** [comment]
To put this in Perspective: the "minecolonies" save folder on the official server is 3.5gig large. But the latest colonies.dat is only 7MB. Obviously this needs some trimming down. =D

**Comment by Raycoms** [comment]
On a note to that, could you remove like all but the latest 25 maybe, or even like 10 but from different moments in the past from our server 

_Sent from my Oneplus A0001 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Raycoms** [comment]
Closed in favor of joint issue.
