### ISSUE TITLE
Workers need locomotion improvement

### ISSUE THREAD

**Issue by Raycoms** [ldtteam/minecolonies#1358]
Workers really need locomotion improvement (walls, trapdoors, underground, farmland, doors)

**Comment by postal291** [comment]
Yea even navigating between path blocks and grass blocks causes pathing issues, I just upgraded my colony to brownstone paths and 100% recommend it!

**Comment by Zoidey** [comment]
I've had a few npc get stuck trying to walk thru buildings, like the builder that gets stuck on the other side of the building where the door would be if it was rotated (I always think they must be drunk lol).

I didn't know about brownstone paths, I so have to give that a go, thanks!
