### ISSUE TITLE
[Feature] Warehouse Sorting

### ISSUE THREAD

**Issue by Raycoms** [ldtteam/minecolonies#1360]
Warehouse level x+ might have its own worker which will sort the warehouse accordingly.

**Comment by Wissi** [comment]
Wouldn't that add a bit more workload on the server. 

Instead a "virtual" storage system with a searchable feature (like some have suggested using the AE2 -or similar- open GNU) and have a limited storage space, upgradable with the warehouse building level and as you suggested past level 5 being upgraded with some special type of block or expensive recipe?

Just an idea.

**Comment by Raycoms** [comment]
That worker wouldn't work that fast, he would do it pretty much as the
inventoryTweaker mod probably. But chest by chest. This way it doesn't put
any load on the server.

2017-08-31 0:53 GMT+01:00 Wissi <notifications@github.com>:

**Comment by Asherslab** [comment]
I'm going to close this issue, as i believe we've already implemented a sorting feature.

**Comment by Bucketsmith** [comment]
> I'm going to close this issue, as i believe we've already implemented a sorting feature.

Did this feature ever get into the latest version for MC 1.14?
There seems to be absolutely no sorting going on in our warehouse.

**Comment by RyTechro** [comment]
Haven't tested it myself but if you upgrade your warehouse above level 3 a sort button reveals

**Comment by Bucketsmith** [comment]
Ah, ours is level 3. So we couldn't have seen that yet. I wonder why it's only available at level 4? I mean, the small the storage space you have available, the more important sorting is.

**Comment by Raycoms** [comment]
It should be visible on page 2 of the warehouse on level 3 already.

**Comment by Bucketsmith** [comment]
Found the button. Clicked it, but then all the inventories for the racks disappeared. All of our stuff, gone.
Is it being held in a virtual storage to be sorted, or something? Does it take time?
Or is this a bug and is all of our stuff now gone?

**Comment by Asherslab** [comment]
@Bucketsmith check all the racks, they’re in there somewhere. It doesn’t update the model though

**Comment by Bucketsmith** [comment]
No, apparently, there's a bug.
https://pastebin.com/SVw65SME
I am no coder, only dabbled a little bit with it in some education and hobby projects.
Might this be because we manually picked items out of racks a few times? That the sorting function tries to pick up items it is expecting, but they're not actually there?

Quite a catastrophic error to just remove ALL items in the entire warehouse... So much progress lost..

**Comment by Asherslab** [comment]
@Bucketsmith please make an issue then
