### ISSUE TITLE
Improve Build tool rendering.

### ISSUE THREAD

**Issue by Raycoms** [ldtteam/minecolonies#1362]
Some things don't render in there:
Entities, walls, closed fences etc.

**Comment by Raycoms** [comment]
@JoseluGames do you have any idea, time?

**Comment by JoseluGames** [comment]
I have almost no time but I can have a look, whats broken? If I remember correctly when I made it almost everything rendered

**Comment by Raycoms** [comment]
The problem is that entities and things like walls and fences often don't
render correctly. Good testing example would be the stone baker level 5.

**Comment by JoseluGames** [comment]
I will have a look on tuesday, that is my free day and I can give more time to it. I will tell you what I found out!

**Comment by Raycoms** [comment]
Sounds great, thanks.

2017-08-13 12:35 GMT+01:00 José Luis <notifications@github.com>:

**Comment by JoseluGames** [comment]
For the time I've got free I'm not able to have a deep look into it, everything seems to be ok on the code and I'm not able to play and see what's wrong. What do you mean with things not rendering correctly? Rotations?

**Comment by Asherslab** [comment]
no, it's literally not there. Fences/ basically anything with a none solid block shape.

**Comment by JoseluGames** [comment]
That's weird because what the code does is, it gets the baked model for the block and then renders it. Maybe it's not able to get the baked model or it doesn't find a layer to render it to.

**Comment by Raycoms** [comment]
Fences are rendered but without connections between them, walls and
entities are just not rendered at all

**Comment by JoseluGames** [comment]
Ok, so that are 2 if not 3 things broken, the only one I can have a clue of what's about are the fences, they are not getting the correct blockstate (That is used to get the baked model). Later today I will try to make a kind of "Flow chart" of what the structure renderer does and where maybe the conflicting points.

**Comment by JoseluGames** [comment]
Ok, so today I managed to do this: https://goo.gl/r6meoq
I will be working on it so we can have a "visual" reference of what it does, and it will be easier to point out where the bugs may happend. So far I can tell that the thing about blocks is probably going to be about IBlockState. For the entities I still have no clue.

**Comment by Raycoms** [comment]
Okay @JoseluGames I fixed the tileEntityRendering I guess, I removed the "prepare" call which made them appear.
Still, walls etc don't work well yet.
I guess we need a better way to get the state.

**Comment by JoseluGames** [comment]
I knew I was forgotting something. The problem about fixing blockstates is that we get it from many places and many times, we should use com.minecolonies.structure.lib.ModelHolder more often, it's a class made to store that kind of info so we don't need to call so many places to get the state

**Comment by Raycoms** [comment]
Yeah probably, do you think you're able to improve this?

2017-08-22 22:31 GMT+01:00 José Luis <notifications@github.com>:

**Comment by JoseluGames** [comment]
Yes, or at least clean it and comment it so it's easier to understand what it does, but I can't put my full attention until september, although I can start making little but some progress if you create a branch for me to work upon

**Comment by Raycoms** [comment]
made a branch called fix/buildtoolrendering

2017-08-22 22:47 GMT+01:00 José Luis <notifications@github.com>:

**Comment by JoseluGames** [comment]
Ok, tomorrow morning I'm going to at least get the workspace up and running, I'm going to also try to use IntelliJ for the first time 😁

**Comment by Raycoms** [comment]
I investigates this problem and all the blocks have only the default blockState and not the info they need. Might be happening when we store this info.

**Comment by Raycoms** [comment]
Fixed it, will make a pr with it later.
Will improve the performance as well
