### ISSUE TITLE
[Feature] Hardcore Mode

### ISSUE THREAD

**Issue by kreezxil** [ldtteam/minecolonies#1365]
# Description
The player logs on and they are in **Adventure** mode. They have a _Supply Camp_ by default, it can be converted easily to __Supply Ship__ with the personal crafting grid and vice-versa. No matter what mods are installed to the pack, the player stays in **Adventure** mode. Therefore they are in total reliance on the colony to obtain resources.

## Default Equipment
The player is given a tool that will dismantle their __Supply Camp__ or __Supply Ship__. 

## Additional Consideration

- Since the player is dependent on the **Colony** for all of their equipment and resource needs, the player should be prevented from build the next tier of anything else until all possible building types have been erected to 1 each.
- Because the player won't be able to craft to aid the colony, they should be given build start blocks after placing each one. 
For instance, 
-- when they place the town hall block, they should be given the builder block. 
-- Then given the lumberjack block.
-- Then given the craftsmith (does this exist yet?)
-- Then given the miner block.
-- Then a house blocks.
-- Then a farmer and some scarecrows (fields)
-- Then a baker
-- Then a guard tower.
-- After the guard tower is built and all the other builds are built and at least 1 guard. The colony becomes tier 2. This time they start with the town hall and upgrade it, and subsequently all of the other buildings. Upgrading the town hall will give them another guard tower block.
- I understand this might not be possible until more of the mod is deployed.
- I further understand there may be other logistical issues to deal with and that his might not be possible in whole or in part.
- If this is achievable with command blocks I'd like to see it. :)

## Why did you post this idea?
To get it out there ofcourse, to give those concerned a spock moment. Maybe something can come of this. I could easily see special interface block that would allow the feeding of recipes from other mods so the craftsman can fabricate those blocks for the player.

**Comment by Glockshna** [comment]
That's essentially how I'm playing right now. Turned up the speed of the colonist actions in the config and just running around managing projects and letting them do it all. Apart from basic decorating, of course. +1 for some official version of this.

**Comment by Raycoms** [comment]
Closed in favor of joint issue.
