### ISSUE TITLE
[Feature] World Spawn Protection

### ISSUE THREAD

**Issue by kreezxil** [ldtteam/minecolonies#1368]
Using Minecolonies build 3302

All the distance setting values for controlling how far away from spawn a supply ship/camp be placed is being ignored. This goes for the townhall too.

In 1.11.2 this value is respected. My server forces the player to travel 8000 blocks before they can place a townhall or supply chest.

My minecolonies.cfg just in case I've got something arsed up in it. https://gist.github.com/410b2a44444d2e45d3df6f22e3fbda27

**Comment by Raycoms** [comment]
Uhm I think that value is for the /mc rtp command and not for
supplyship/camp placement.
Did that really work in 1.11.2?
Might that be another mod doing that?

2017-08-13 14:50 GMT+01:00 kreezxil <notifications@github.com>:

**Comment by kreezxil** [comment]
yep it did work there

**Comment by kreezxil** [comment]
if it wasn't ever meant to do that, it would be a nice feature to have.

**Comment by Raycoms** [comment]
I'm quite sure it was your 1.11.2 spawn protection or anything similar
which did that.
If you want it as a feature request please edit the description and title
and add an "enhancement" label.

2017-08-13 15:00 GMT+01:00 kreezxil <notifications@github.com>:

**Comment by kreezxil** [comment]
ok, i'll do that, but btw, you know use pleebs can't actually add lables, we can put stuff in brackets tho. :)

**Comment by Raycoms** [comment]
Thanks

**Comment by kreezxil** [comment]
Because of this and my not realizing that in 1.8 Mojang made the spawnprotect value self-disabling if no op is present at world creation. I created the following which is now available on Curse. https://minecraft.curseforge.com/projects/no-op-spawn-protection

**Comment by kreezxil** [comment]
I would still like to have the feature that this **Enhancement** requests however.

**Comment by Raycoms** [comment]
I will change this to "Offer spawn protection".
Our whole anti-griefing can simply be adapted to turn it on as an anti-griefing protection within the spawn area.

**Comment by Raycoms** [comment]
Closed in favor of joint issue.
