### ISSUE TITLE
[feature request] Modern building style

### ISSUE THREAD

**Issue by Zygus42** [ldtteam/minecolonies#1371]
1.12

I would love to see a Modern building style to fit a more modern minecraft setting instead of the standard Medieval one that is currently available in wood or stone.

**Comment by Raycoms** [comment]
Hey there @Zygus42.
We would like to see that modern building style as well.
So if you like you can build it and send us the world so we can scan it in.
If you want to know about rules on how to build a style contact us.

**Comment by Zygus42** [comment]
This is from your wiki:

The scans MUST have the same footprint for the same style/Hut's type;
The scans must contain the hut's chest i.e. builder's chest for the builder's hut, Citizen's chest for the Citizen's hut and so on.
The hut chest need to be exactly at the same place and have the same rotation for each level;

Does this apply to styles added this way as well, and if so, how do I find out the footprint and chest location & rotation of each level of each building ?  Is there a world save with all the existing buildings that I could use as a template ?

**Comment by Raycoms** [comment]
The styles don't have to have the same footprint and position as our style.
But inside your style, each worker hut (i.e the builders hut) must have a coherent design, footprint and position within that hut.
