### ISSUE TITLE
Hiding Citizen's Names

### ISSUE THREAD

**Issue by Oraiz** [ldtteam/minecolonies#1375]
### Minecolonies version

version 1.10.2-0.8.3227

### Expected behavior

Setting "Always render Citizen's name tag?" to "false" will hide Citizen's names.

### Actual behaviour

Does not hide names

### Note
I'm using Vazkii's "Neat", so would like to have the option to hide the nametags from Minecolonies, or be able to disable them in Neat, either would work (so I don't have double names displayed).

**Comment by Raycoms** [comment]
Always render name tags should render them always, if that's on false it
will only show them if you hover over them afaik.

2017-08-16 13:10 GMT+01:00 Oraiz <notifications@github.com>:

**Comment by Oraiz** [comment]
Thanks for the quick reply. I have the option set to false, so would expect to not see the names, but they're still showing (whether I'm looking at the citizen or not).

**Comment by Raycoms** [comment]
Okay this is strange.

this.setAlwaysRenderNameTag(Configurations.alwaysRenderNameTag);

We add that as direct input to the minecraft method.
So the bug is probably not on our side with this.

Did you restart the game after changing the option?


2017-08-16 13:14 GMT+01:00 Oraiz <notifications@github.com>:

**Comment by Oraiz** [comment]
Yes I've restarted the game.

**Comment by Oraiz** [comment]
So since this, I've built two more citizens huts, and the new citizens' names are hidden... the original four that spawn when you place the town hall are still showing.

**Comment by Raycoms** [comment]
Even on complete game restart? (Turn off and on minecraft completely) They
should reconstruct themselves normally and then get their name removed as
well.

2017-08-16 13:29 GMT+01:00 Oraiz <notifications@github.com>:

**Comment by Oraiz** [comment]
Even after complete PC restart :)

I suppose I could try killing the original citizens?

**Comment by Raycoms** [comment]
Will have a look at this tomorrow.

2017-08-16 13:45 GMT+01:00 Oraiz <notifications@github.com>:

**Comment by Raycoms** [comment]
Can you try the recall all in the townhall, if that fixes it?

2017-08-16 13:45 GMT+01:00 Ray Neiheiser <ray.neiheiser@gmail.com>:

**Comment by Oraiz** [comment]
Didn't work.
