### ISSUE TITLE
Crashing server

### ISSUE THREAD

**Issue by fusionmc-evilscoop** [ldtteam/minecolonies#1376]
### Minecolonies version
0.8.3433 for 1.10.2
version X.X.XXXX or curse X.X.XX

Using building wand to build town hall (wooden lvl 1)

https://gist.github.com/OrionDevelopment/2f2e0afa0d7e511a3db22dcb4766ba18

Restarting the server, soon as I connect, server crashes

Server is spongeforge-1.10.2-2281-5.2.0-BETA-2558

Guess core of this is the "java.lang.NoClassDefFoundError: net/minecraft/client/multiplayer/WorldClient "
Which means something is using a client side method in the server side rather than passing back to client...i believe

**Comment by fusionmc-evilscoop** [comment]
Client side log -
[20:26:23] [Client thread/INFO] [minecolonies]: isCorrectMD5: md5:BDA21FCF138D6CC56DA9D70699493F60 other:BDA21FCF138D6CC56DA9D70699493F60
[B#349]  [20:26:48] [Client thread/INFO] [minecolonies]: isCorrectMD5: md5:437BEEAE6FE4D83EDDF0744C42C90297 other:437BEEAE6FE4D83EDDF0744C42C90297
[B#349]  [20:26:50] [Client thread/INFO] [minecolonies]: isCorrectMD5: md5:E009E37A576775A81C0A9883FFB7EBB9 other:E009E37A576775A81C0A9883FFB7EBB9
[B#349]  [20:26:51] [Client thread/INFO]: [CHAT] [DIM-343800852][g][Founder]Kmartinator: Gotta run!  later folks.
[B#349]  [20:26:54] [Client thread/INFO] [minecolonies]: isCorrectMD5: md5:8EE3AEE2CF11A8C75736E5A94BDFF13F other:8EE3AEE2CF11A8C75736E5A94BDFF13F
[B#349]  [20:26:55] [Client thread/INFO] [minecolonies]: isCorrectMD5: md5:437BEEAE6FE4D83EDDF0744C42C90297 other:437BEEAE6FE4D83EDDF0744C42C90297
[B#349]  [20:26:57] [Client thread/INFO]: [CHAT] [test][g][Founder]Bladewind187: cya
[B#349]  [20:26:58] [Netty Client IO #1/INFO] [EnderCore]: Reset configs to client values for com.enderio.core.common.config.ConfigHandler
[B#349]  [20:26:58] [Client thread/INFO] [STDOUT]: [com.lordmau5.ffs.FancyFluidStorage:onWorldUnload:135]: Unloading dimension 3
[B#349]  [20:26:58] [Client thread/INFO] [journeymap]: Mapping halted in D:\technic\technic\modpacks\evilmc-10\journeymap\data\mp\Evilscoop~Games\DIM3
[B#349]  [20:26:58] [Client thread/INFO] [FML]: Applying holder lookups
[B#349]  [20:26:58] [Client thread/INFO] [FML]: Holder lookups applied
[B#349]  [20:27:03] [Client thread/INFO] [Mekanism]: VoiceServer: Stopping client connection...

**Comment by Asherslab** [comment]
could you put this in a Gist please? it's currently quite unreadable
:smile:

**Comment by marchermans** [comment]
Updated the issue with a gist.

**Comment by marchermans** [comment]
Raycoms said this is something with the request System?

**Comment by fusionmc-evilscoop** [comment]
srs....you want me to do your job for you.....you want it in gist you paste it in
server log is now gone and mod disabled.....what i have was posted, use it...read my comment at the bottom of first post...tbh you shouldn't evan need the rest of the crap

**Comment by fusionmc-evilscoop** [comment]
Other factors to this 
There was a tree in the space for the town hall (and i didnt remove it when confirming the build), nothing in the docs said i needed to, and the building wand let me confirm the placement

Part of the town hall would have overlapped a grief prevention claim (basic one), not sure this makes a diff as the supply crate building also overlaps and spawned perfectly

**Comment by Raycoms** [comment]
This should be fixed in the newest versions on curse.

**Comment by fusionmc-evilscoop** [comment]
there is not a 1.10 version on curse
1.10 version last updated 21 July

**Comment by Asherslab** [comment]
yeah sorry, it's coming, it hasn't been merged yet sorry

**Comment by fusionmc-evilscoop** [comment]
np i found it on curseforge.... so removed my comment

**Comment by Asherslab** [comment]
ah, okie dokie =D

**Comment by fusionmc-evilscoop** [comment]
just wanted to say works a treat......
my server users thank you :D

**Comment by Asherslab** [comment]
great, glad to hear
