### ISSUE TITLE
Barbarians don't spawn.

### ISSUE THREAD

**Issue by sayamath** [ldtteam/minecolonies#1381]
### Minecolonies version

minecolonies-universal-1.11.2-0.8.3487

### Expected behavior

-Barbarians should spawn after the message "Buckle up cowboy! There's some darn raiders commin' for you Tonight!"

### Actual behaviour

- Barbarians don't actually spawn after the message even though I waited the whole night,

### Steps to reproduce the problem

1. use this command : /mcolonies raid-tonight
2. use "time set night" or without the command
3. Waiting the whole night but nothing happened
4. Asking for your help! I beg you T_T

**Comment by Asherslab** [comment]
Yep, there's a fix coming soon (you can see in Pull requests)

**Comment by sayamath** [comment]
Oh sorry i didn't see it. thx for your fast reply and your hard work !!
