### ISSUE TITLE
If "builderInfiniteResources=true" breaks building/and access to block UI

### ISSUE THREAD

**Issue by TheQuadShot** [ldtteam/minecolonies#1385]
Minecraft 1.10.2
Forge 12.18.3.2422
minecolonies-universal-1.10.2-0.8.3486.jar

FullModList:
https://pastebin.com/D2V2BsuM

LatestLog:
https://pastebin.com/LWTpQkyC

I set down a builder hut, the builder goes to the hut and stands there, and I can't open the block UI (to place build order/cancel/inventory).
Log file shows "[Netty Local Client IO #0/ERROR]: Colony view does not exist for ID #1"

**Comment by Raycoms** [comment]
Ahm I think those two things are not related, it seems to me that your colony broke after a restart, might have had an exception on load or unload which destroyed the loading process.
Please try to insert one of the backup minecolonies.dat which should make it work.

**Comment by TheQuadShot** [comment]
Ok, sorry. I made the edit and it went weird, so I changed it back and it started working again. I also confirmed that it is working correctly.
