### ISSUE TITLE
Rangers (archer guards) should not charge into barbarians

### ISSUE THREAD

**Issue by Rosomah** [ldtteam/minecolonies#1388]
### Minecolonies version

minecolonies-universal-1.10.2-0.8.3513

### Expected behavior

- Archers should keep their distance from the raiding barbarians and other mobs.

### Actual behaviour

- They just rush in, firing their arrows into them, but since the enemies are all stacked together, they kill my rangers pretty fast.

### Steps to reproduce the problem

1. Hire some rangers and wait for the raid.
2. ZYX
3. ...
4. Profit? No profit since all your rangers are dead. :)

This isn't the current version's problem since it was happening before this one, but I hope there's an easy way to fix this.

**Comment by Raycoms** [comment]
Closed in favor of #1356
