### ISSUE TITLE
[Enhancement] wild warehouse ideas

### ISSUE THREAD

**Issue by hron84** [ldtteam/minecolonies#1390]
- Warehouses should contain any inventory blocks, including modded ones (not neccessarily at build time, but delivery men should look for any inventory in the warehouse. Probably can be filtered
 - Builders should take care to TileEntities at repairing / upgrading warehouse and try to just skip that block from the blueprint (to not remove modded inventories).
 - A request / support block should be good for providing / requesting items to/from delivery men. A slotted thing, like AE Interface blocks would be enough, delivery men try to keep one stack from the requested items. The very important thing is this should be just a block, and delivery villager could use them only from say level 3 (but it could be configurable also).

**Comment by Asherslab** [comment]
Most of these have been suggested in other issues. should we close this in favour of those? @Raycoms

**Comment by Raycoms** [comment]
Yeah, agreed
