### ISSUE TITLE
[Bug] Colonists does not show up on JourneyMap

### ISSUE THREAD

**Issue by hron84** [ldtteam/minecolonies#1391]
### Minecolonies version

version 1.11.2 / 0.8.3184 

### Expected behavior

- JourneyMap should display colonists anyhow, pets, or villagers, it does not matter.

### Actual behaviour

- All colonies seems empty on the map

**Comment by Asherslab** [comment]
you need to update to the newest versions of JourneyMap and Minecolonies, we literally just added that yesterday (Sorry not meaning that in a rude way, came out wrong)

**Comment by hron84** [comment]
@Asherslab I will definitely do then! Thank you! I am very glad seeing a mod being actively developed and being more and more compatible with other mods.

**Comment by marchermans** [comment]
No this is still in the PR queue which i am pulling now
Should be released in a couple of hours, when no conflicts arise.

**Comment by Asherslab** [comment]
huh, was on the official server lol

**Comment by hron84** [comment]
@OrionDevelopment could you poke me when release is available for us?

**Comment by Asherslab** [comment]
it's already merged, so build system has uploaded it (Thus it should already be on curse)

**Comment by Asherslab** [comment]
Version with Journey Map: https://minecraft.curseforge.com/projects/minecolonies/files/2468837
Newest (Adds waypoint block): https://minecraft.curseforge.com/projects/minecolonies/files/2468840
@hron84

**Comment by Asherslab** [comment]
btw, highly suggest joining us on discord if you haven't already. https://discord.gg/NMMKU9g

**Comment by Raycoms** [comment]
Should be merged already (If you switch to icons you can even see the worker heads)

**Comment by Rosomah** [comment]
Is this available for the 1.10.2 as well?

**Comment by Raycoms** [comment]
Will be made available soon. Will port it this weekend.

2017-08-25 14:43 GMT+01:00 Rosomah <notifications@github.com>:

**Comment by Rosomah** [comment]
👍

**Comment by marchermans** [comment]
Hmm sorry i was busy merging stuff and with TeamCity. It is up now as the others said.

**Comment by hron84** [comment]
And it's installed to my private instance, thanks.
