### ISSUE TITLE
[Worker improvement] Worker should try to escape from suffocating

### ISSUE THREAD

**Issue by hron84** [ldtteam/minecolonies#1392]
### Minecolonies version

version 1.11.2 / 0.8.3184 or curse X.X.XX

### Actual behaviour

- Workers, especially wood workers suffocates in accidental events, like tree grown.

### Expected behavior

 - Workers should try to escape from suffocating if it is possible. The very basic way is remembering to latest portion of their path and move back on that until they do not take suffocation damage. It could help miners and woodworkers to escape from suffocating. Freezing is definitely not a good reaction.

**Comment by Raycoms** [comment]
They try to suffocate, but if they're already closed in, there is no way out.
The lumberjack rarely dies, we even have some extra functionality that he doesn't stand on top of a sapling. If it still happens it was simply bad luck and takes part. (Even has an achievement)

**Comment by Rosomah** [comment]
If it's possible, you should make the builder stand behind the construction tape, cause in my experience, he starts climbing on the walls he already built and that's usually when he places a block over himself and dies.

**Comment by Raycoms** [comment]
That should've been fixed in the latest versions.

2017-08-25 14:48 GMT+01:00 Rosomah <notifications@github.com>:
