### ISSUE TITLE
[Enhancement] NPC GUI

### ISSUE THREAD

**Issue by Electrocutor** [ldtteam/minecolonies#1397]
Add a text section to the NPC GUI window that tells what they are currently trying to do. This will help alleviate a great deal of the headaches associated with trying to make them work while you guys continue to work on their AI.

Examples:
"I am trying to use an axe."
"I am trying to get an axe from my work hut."
"I am waiting for the deliveryman to deliver an axe to my work hut."
"I am trying to get to location (x,y,z)"
"I am trying to find a furnace in my hut"
"I am wandering around because I'm hungry."
etc

**Comment by Raycoms** [comment]
In the works, there is an issue for this already
