### ISSUE TITLE
[Request] Warehouse Rack support Bibliocraft Stockroom Catalog

### ISSUE THREAD

**Issue by scottosx** [ldtteam/minecolonies#1400]
### Minecolonies version

version 1.10.2

### Expected behavior

- The Stockroom Catalog from Bibliocraft lists all items in selected inventories in a sortable book. It would be perfect as a manifest for the warehouse. Sneak right clicking on any inventory should add that to the catalog.

### Actual behaviour

- Racks are not recognized as valid inventories by the Bibliocraft Stockroom Catalog. They cannot be assigned.

### Steps to reproduce the problem

1. Craft Stockroom Catalog.
2. Sneak right click on warehouse rack.
3. Be disappointed.
4. Add functionality.

**Comment by scottosx** [comment]
In general the storage racks seem to not extend vanilla storage in a conventional way? For instance, the Quark command 'Merge to nearby chests' doesn't work either. That would be a good way to quickly store items in the warehouse while keeping the NPCs storage scheme intact. (not sure how much that matters but surely it stops constant reindexing)

However the RF Tools Storage Scanner sees the contents fine, which is nice.

**Comment by Asherslab** [comment]
Yeah, our racks work completely differently to vanilla storage, we do this because it reduces around 90% of Mincolonies caused lag on servers.

**Comment by Raycoms** [comment]
I believe that those mods might require too tight coding.
I think they probably scan for the block being a container and not, like it should be, checking if the block has itemHandler capabilities. Could you report that to the regarding mods as well to see what they have to say to that?

**Comment by marchermans** [comment]
I was about to say that we have IItemHandler Caps on them. So interaction with them is possible.

**Comment by Raycoms** [comment]
I believe that Bibliocraft used a lazy(outdated) implementation, relying on
"BlockContainer" or even "BlockChest"

2017-08-30 14:24 GMT+01:00 Marc Hermans <notifications@github.com>:

**Comment by Raycoms** [comment]
I'll close this here because there is not much we can do from our side.
