### ISSUE TITLE
[Minocolony Testpack Patreon in Single player] miner stopps mining, requesting nothing

### ISSUE THREAD

**Issue by DietmarKrause** [ldtteam/minecolonies#1403]
### Minecolonies version

Minecolony Testpack 1.11 (Patreon) in SP downloaded 3 Days ago (around 25th August)

### Expected behavior

miner hud level 2 . Miner should ask for materials,  
### Actual behaviour
miner stopps mining requesting nothing. I fired her and hired another different who startes mining again. The "old" miner (now without profession) keeps holding the pickaxe in her hand even after i hired her as a guard. No pickaxe in inventory though. After restart of the game the pickaxe was gone and replaced by a bow out of the inventory. Now she serves as a guard without problem. The new miner mines 5 shafts  in the deep without asking for materials and stopps . No branching etc. No asking for materials after that.  I cannot get him to work again no matter what i do. There is no delivery man in my colony until now.
Before that he only asked for one item at a time (requesting exactly one torch or one oak wood slap etc. I give him 10-12 each time but this time i cannot see what he is asking for). It would help if there is a list of thing he needed to give it to him in advance. 

### Steps to reproduce the problem
 see above

**Comment by Raycoms** [comment]
Yes this happens with the Miner, there is already an issue for that. When that happens provide him with everything he might possibly need and he will continue working

**Comment by DietmarKrause** [comment]
Solution found: There is a workaround: The miner continues working, if you take some materials *out* of his *personal* inventory (not the chest). He instandly takes fresh materials out of the chest and restarts working. You have to do that often, but it works !

**Comment by DietmarKrause** [comment]
https://github.com/Minecolonies/minecolonies/issues/1343
