### ISSUE TITLE
[question] How do the Barabarians spawn? 

### ISSUE THREAD

**Issue by DietmarKrause** [ldtteam/minecolonies#1405]
I am playing Testpack patreon (1.11.2) in SSP and my colony is attacked several times by barbarians. I want to avoid that in future, so the question: Are there some spawner cages around i can find and destroy? I havent found anything like that though? Or is there a config option ? What is the best defense if one cannot avoid the barbarians?

**Comment by Asherslab** [comment]
Few things. 
1. no there are no spawners, your colony itself spawns them.
2. Yes there is a config option "DoBarbarianSpawns" (or something similar)
3. Best defence is Rangers (I find) rangers now level up for killing mobs, so yay!

also, Barbarians start spawning after you have more that 5 citizens (thus, after your first additional citizen)

also, i'm happy to hear they are spawning. that's good!

**Comment by DietmarKrause** [comment]
i was confused for there a (older?) videos that a showing spawners, so i looked for them and didnt find them. in fact they spawn two nights in advance and killed NPCs and stole blocks out of the buildings. At first i didnt know anything about the barabarians and was overun. Now i have 3 rangers and tend to kill them for myself. They seem to spawn in a group of 10-12 100 blocks away in the water they swim there and attack my starter ship as far as as i can see. .... then run / swim to the colony, but it can very well be that they spawn at different points. I havent found that out.

**Comment by Asherslab** [comment]
they spawn at random points.. should, unless they're using the fall-back point =/ 

And those would be Really really old videos lol
