### ISSUE TITLE
Can't interact with own village

### ISSUE THREAD

**Issue by Spyro1502** [ldtteam/minecolonies#1408]
### Minecolonies version

minecolonies-universal-1.10.2-0.8.3227

### Expected behavior

- Be able to interact with my own village

### Actual behaviour

- can't do anything

### I play with my friend by LAN
i saved and quit
when return in the game, we can't breack blocks or place blocks like if we weren't the owner, but when looking i the town (we can open it, modify it, interact with villager inventory) i'm still the owner
ps:this is a lan game saved as a solo map
edit: by adding each other as officer in our village we can re-interact with

**Comment by marchermans** [comment]
Try the refresh command. It should reload the data.

**Comment by Spyro1502** [comment]
refresh command ?

**Comment by Raycoms** [comment]
/mc colony refresh colonyid

2017-08-30 16:20 GMT+01:00 Spyro1502 <notifications@github.com>:

**Comment by Spyro1502** [comment]
it do nothing...

**Comment by Wissi** [comment]
U did get your Colony ID first right, using:
/mc colony info <player>

Then using your Colony ID did: 
/mc colony refresh <colony ID#>

All the commands are in the WIKI, server section:
https://wiki.minecolonies.com/wiki/18/server

**Comment by Raycoms** [comment]
I think that should'Ve resolved it.
