### ISSUE TITLE
Builder's hut crafting (0.8.3530)

### ISSUE THREAD

**Issue by Hiomir** [ldtteam/minecolonies#1410]
version 0.8.3530 - minecraft 1.12.1

Hello
When I try to craft the builder's hut, the craft doesn't work. I'm placing the different items, but it doesn't give me the builder's hut chest. I already crafted a SupplyShip chest and placed it, and also placed my townhall. As you can see in the screenshot, at the left, the SupplyShip chest is shown, so the mod is totaly installed.
![2017-08-30_23 37 25](https://user-images.githubusercontent.com/31491206/29896534-aa9158c6-8ddd-11e7-8fc4-ba73e362be88.png)
 When I play in creative, i can place the builder's hut without problems. I've already seen this problem in the internet for the 1.12.1 version of minecraft with minecolonies.
Hoping you'll fix it
Hiomir

**Comment by Wissi** [comment]
The recipe for all the huts is a "Building tool" in the top middle.

You can check the updated WIKI:
https://wiki.minecolonies.com/wiki/1

You can check the recipes in JEI or NEI (if you have either installed) as well.
