### ISSUE TITLE
Shaped Recipe conflict w/ Builders Wand

### ISSUE THREAD

**Issue by TheQuadShot** [ldtteam/minecolonies#1414]
Minecraft 1.10.2
Forge 12.18.3.2422
BetterBuildersWands-1.10.2-0.11.1.220
minecolonies-universal-1.10.2-0.8.3690

Building Tool and Scan Tool conflict with builder wands. Maybe flip the recipe 180° (flip it up-side-down)
ModList:
https://pastebin.com/XZWj3KEF

Current recipes:
recipes.addShaped(<minecolonies:scepterSteel>, [[null, null, <minecraft:iron_ingot>], [null, <ore:stickWood>, null], [<ore:stickWood>, null, null]]);
recipes.addShaped(<minecolonies:scepterGold>, [[null, null, <ore:cobblestone>], [null, <ore:stickWood>, null], [<ore:stickWood>, null, null]]);

Proposed change:

recipes.addShaped(<minecolonies:scepterSteel>, [[null, null, <ore:stickWood>], [null, <ore:stickWood>, null], [<minecraft:iron_ingot>, null, null]]);
recipes.addShaped(<minecolonies:scepterGold>, [[null, null, <ore:stickWood>], [null, <ore:stickWood>, null], [<ore:cobblestone>, null, null]]);

Source Change(I think, I can make a pull request if you wish):

minecolonies/src/main/java/com/minecolonies/coremod/util/RecipeHandler.java

       //Register Scepters
        GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(ModItems.scanTool, 1), "  S", " S ", "I  ", 'I', Items.IRON_INGOT, 'S', WOODEN_STICK));
        GameRegistry.addRecipe(new ShapedOreRecipe(new ItemStack(ModItems.buildTool, 1), "  S", " S ", "C  ", 'C', "cobblestone", 'S', WOODEN_STICK));

**Comment by DietmarKrause** [comment]
As far as i can see you have forestry in your modlist. It should be possible to switch betwenn the recipes in the forestry worktable.

**Comment by TheQuadShot** [comment]
True, I also have MineTweaker.  However I'm thinking of other people that don't know how to use minetweaker and/or don't have Forestry and Better Builder's Wands has become very popular.

**Comment by Raycoms** [comment]
Yeah I thought for a while we probably should change that, will think of something good.

**Comment by Raycoms** [comment]
It a quite common recipe however you turn it.
I think the best idea would be making a button in the townhall to get it for free
