### ISSUE TITLE
[Enhancement] Use oredict for building materials

### ISSUE THREAD

**Issue by rosareven** [ldtteam/minecolonies#1422]
Suggested by this comment https://minecraft.curseforge.com/projects/minecolonies?comment=528

Some biomes have different dominant wood type other than oak. I think it makes sense to use oredict wood instead of strictly one type of wood, or instead of having separate schematics for different wood type.

**Comment by Asherslab** [comment]
as discussed in the following issue:
https://github.com/Minecolonies/minecolonies/issues/1345

We are not planning on adding anything like this.
@Raycoms Correct?

**Comment by Pablo-DS** [comment]
Sorry, to necro this but since this was closed as #completed and not #not planned was this completed? I think having the ability to swap stone/wood types would be a great adition.

**Comment by MotionlessTrain** [comment]
Closed as not planned didn’t exist back then
