### ISSUE TITLE
Farmer appears to go to newest field not closest field.

### ISSUE THREAD

**Issue by TheQuadShot** [ldtteam/minecolonies#1426]
Minecraft 1.10.2
Forge 2422
MincColonies Build: 3780

I set up some farms about 50 blocks apart, The farmer went to the one across town to a farm that hasn't been built yet, not the one at the hut. I also place hoe and seeds in farm hut and define fields when I lay them out, so they can start as soon as the builder is done.

**Comment by Asherslab** [comment]
Last I checked Builders don't build fields? @Raycoms

**Comment by TheQuadShot** [comment]
He doesn't, he builds the farm/barn/building, I define the field location and what crop I want. The inventory for the building and the crop marker are available as soon as I place the block, so I can "stock" it up before I put in a build order.

**Comment by Raycoms** [comment]
You can choose the field in his gui.
He will search the first scarecrow which registered with the colony and is
free, but you can assign him manually as well

**Comment by TheQuadShot** [comment]
That's kind of what I thought(he would find the closest field), but that didn't happen. I had a crop (scarecrow) set up with a crop, (wheat in this case) right in front of the "door" of the farm/barn (about 10 blocks). But he went to the one I built on the other side of town, over 50 blocks away from what should have been his closest field.
I think I see what happened but I'm not sure. I see this msg in the log:
Client thread/WARN]: core (Initialized) Bad configField entry during updateFrom(): optionsManagerViewed=null


Here's the complete log file for ya:
https://pastebin.com/103xPg1N

**Comment by Raycoms** [comment]
even though it says field it has nothing to do.
Still just switch the field in his GUI.

2017-09-05 4:02 GMT+01:00 James <notifications@github.com>:

**Comment by TheQuadShot** [comment]
Ok, I don't see anywhere to assign field. Do I have to set job assignment to manual to see it?

**Comment by Raycoms** [comment]
On the second page of the farmer hut gui
