### ISSUE TITLE
Crash when placing the Mesa Farming Block

### ISSUE THREAD

**Issue by kedamono** [ldtteam/minecolonies#1430]
### Minecolonies version

version 1.10.2-0.8.3801

### Expected behavior

- Place the farming block and use it normally

### Actual behaviour

- Crashes Minecraft and corrupts the world file. Cannot reenter the world after the crash.

### Steps to reproduce the problem

1. Create a new vanilla world with the correct version of forge and MC 1.10.2-0.8.3801
2. Build the Barracks block and Barracks Towers
3. Build a citizens hut and upgrade it to level 2.
4. Set the citizens hut to be upgraded to level 3.
5. Before work starts on the citizens hut, place the Farming block and set it to Mesa.
6. Click the green arrow to accept.

Result: Game crashes. Try to reenter world, game crashes

Attached all the log files around the crash
[Crash.zip](https://github.com/Minecolonies/minecolonies/files/1285751/Crash.zip)
[CrashReenter.zip](https://github.com/Minecolonies/minecolonies/files/1285752/CrashReenter.zip)

**Comment by Asherslab** [comment]
@Raycoms slightly curious why this was closed. Did we fix this?

**Comment by Raycoms** [comment]
Only part of my testing version I sent to the people and yes I fixed it
