### ISSUE TITLE
Signs attached to colonists

### ISSUE THREAD

**Issue by Rosomah** [ldtteam/minecolonies#1438]
### Minecolonies version

minecolonies-universal-1.10.2-0.8.3880

### Behaviour

- Not sure if it's intended or if it's a bug, but there are signs attached to the colonists, on which it says what the colonists want or what they are doing.

**Comment by Asherslab** [comment]
Yep, part of the mod

**Comment by Raycoms** [comment]
Only appear when you bump into them.
