### ISSUE TITLE
Miner Level4 miner building//miner not using (unbreakable) Tinkers Construct pickaxe

### ISSUE THREAD

**Issue by daantimmer** [ldtteam/minecolonies#1439]
### Minecolonies version

version 0.12.1-0.8.3804

### Expected behavior

- Miner using Tinkers Construct pickaxe
- ![2017-09-09_20 05 40](https://user-images.githubusercontent.com/8293597/30242652-9c401662-959a-11e7-90fa-9accd606c47f.png)

### Actual behaviour

- Miner not using Tinkers Construct pickaxe
- Miner keeps asking for a pickaxe of diamond quality or better
- Miner using diamond pickaxe instead

### Steps to reproduce the problem

1. Make unbreakable pickaxe
2. ..
3. ...
4. No Profit

**Comment by Raycoms** [comment]
What's the mining level of this pickaxe?
Its possible that that high pickaxe can only be used from level 5 on.

2017-09-09 19:09 GMT+01:00 daantimmer <notifications@github.com>:

**Comment by daantimmer** [comment]
![2017-09-09_20 13 03](https://user-images.githubusercontent.com/8293597/30242689-5e14975e-959b-11e7-85c1-04eb981cad19.png)
It is obsidian and it is asking for
![2017-09-09_20 17 03](https://user-images.githubusercontent.com/8293597/30242717-e9a1e34e-959b-11e7-86dd-d08aa1516e99.png)

And as far as I know the mining levels go like:
Diamond
Obsidian
Cobalt

So "Better than Diamond" should be Obsidian

**Comment by Raycoms** [comment]
Sent it to the dev you developed a part of this to see what the problem is.

**Comment by scottosx** [comment]
My level 3 miner won't use this unbreakable pick from Tinker's either. It is only Diamond level. I do notice that both of the reported pickaxes have XP on them from the mod Tinker's Tool Levelling. I used that  to get the extra modifiers to make it unbreakable. Maybe that has something to do with it?

![2017-09-12_10 40 58](https://user-images.githubusercontent.com/5866215/30335313-98b0f214-97a7-11e7-953c-ade31073a12e.png)
![2017-09-12_10 41 06](https://user-images.githubusercontent.com/5866215/30335314-98b87976-97a7-11e7-96dc-025ec5be8b83.png)

**Comment by Raycoms** [comment]
Can you try to give them the tool without any extra modifiers(Without
fortune and without xp).
And can you check if level 5 accepts them.

2017-09-12 16:54 GMT+01:00 Scott Hendrickson <notifications@github.com>:

**Comment by scottosx** [comment]
Will check. I seem to remember that using a plain all iron pickaxe before modification worked fine (but has no advantages besides possibly repairability)

Looking quickly at the API code maybe only weapons are being checked for use by guards?

https://github.com/Minecolonies/minecolonies/tree/version/1.11/src/api/java/com/minecolonies/api/compatibility/tinkers

**Comment by scottosx** [comment]
Ok, in first tests the Level 3 miner will use an all iron pickaxe from Tinkers, even with Haste, Luck and at least one Reinforced modifier. I will continue to test to see where it breaks but I suspect maybe extended modifiers or XP might not be handled by the Tinkers ToolHelper API.

![2017-09-12_12 34 56](https://user-images.githubusercontent.com/5866215/30340295-aa846f7e-97b7-11e7-87c7-e03f11cf6914.png)
![2017-09-12_12 35 03](https://user-images.githubusercontent.com/5866215/30340297-ab6660aa-97b7-11e7-9892-4a2464e3e507.png)

**Comment by scottosx** [comment]
After more testing, the Level 3 miner will use an unbreakable Tinker's Tool which has XP and extended modifiers. Suspecting now that Fortune II is the issue.

![2017-09-12_13 22 25](https://user-images.githubusercontent.com/5866215/30342106-2831ac7e-97be-11e7-9688-e4124e480d2d.png)
![2017-09-12_13 25 11](https://user-images.githubusercontent.com/5866215/30342107-283253a4-97be-11e7-84f7-979c3a5e3842.png)

**Comment by scottosx** [comment]
Upgraded Miner to Level 4 and now he is using a Fortune II/ Luck II pickaxe fine. Still Diamond level but I will test beyond that.

Question: would the modifiers like Haste and Lightweight make any difference in the miner's speed? Hard to tell with a lot of observation.. Or is it just worth focusing on level, durability and fortune tool modifiers?

**Comment by Raycoms** [comment]
Okay, Yes it should be the combination of high level + enchantments which is only allowed at level 5
