### ISSUE TITLE
/mc home

### ISSUE THREAD

**Issue by Swf01** [ldtteam/minecolonies#1444]
### Minecolonies version

version 1.102-0.8.3780

### Expected behavior

- Teleport to Town Hall block

### Actual behaviour

- 1: "We got places to go, kid!" 2: "Hold onto your pants kid, we're going Inter-Dimensional!" 3: "Error occured while executing command: null" 4: No teleportation 5: Suffocation in an invisible wall 6: Spawn at 8,8 in the nether and is invincible until relog

### Steps to reproduce the problem

1. Go to Nether
2. Do /mc home
3. ...
4. Profit?

**Comment by Raycoms** [comment]
We tested it today, working in all newer versions.
