### ISSUE TITLE
Deliveryman broken

### ISSUE THREAD

**Issue by Rosomah** [ldtteam/minecolonies#1446]
### Minecolonies version

Version: 1.10.2-0.8.3896

### Actual behaviour

- I've got 3 deliverymen and I see them carrying seeds to the farmer one after another, even though the farmer already has a stack and a half of seeds in his chest. Meanwhile, the lumberjack has an almost full chest and none of the deliverymen go check out his chest.

### Expected behavior

- They should stop being silly.

**Comment by Raycoms** [comment]
Yeah our future update will improve this, we already have some issues for that.
