### ISSUE TITLE
Warehouse does not exist

### ISSUE THREAD

**Issue by Irizase** [ldtteam/minecolonies#1448]
### Minecolonies version

version 1.12.1  file 0.8.3530 from curse 
Single player
### Expected behavior

- Put in the updated recipe to get warehouse.

### Actual behaviour

- No recipe exists but suggests there should be a recipe. It worked in the previous versions but doesn't now.

### Steps to reproduce the problem (missing recipe)

I tried all kinds of formulas, I even restarted the game a few times. It just gives me a blank space on the crafting bar.

**Comment by Asherslab** [comment]
Chest in the centre, oak planks In a U shape around chest, build tool on top.

**Comment by Irizase** [comment]
Done that already doesn't work.

**Comment by Raycoms** [comment]
You tried it with and without the buildtool?
@MineShadow7

**Comment by Irizase** [comment]
I tried with both. I tried everything I could think of to make it happen.
With wand, without wand, different woods including oak, and more it is not
showing up.

**Comment by MineShadow7** [comment]
I checked out latest version 1.12.1 branch and it works fine with every type of wood.
![2017-09-14_15 03 25](https://user-images.githubusercontent.com/28764927/30428853-d576a42a-995d-11e7-9ed8-f6a1b56fa71f.png)

**Comment by MineShadow7** [comment]
There should be gold ingot in centre, not chest.

**Comment by MineShadow7** [comment]
I'll change it to chest right now.

**Comment by Raycoms** [comment]
isn't chest dman hut?

2017-09-14 13:06 GMT+01:00 MineShadow7 <notifications@github.com>:

**Comment by MineShadow7** [comment]
Dman hut use leather boots to craft.

**Comment by Raycoms** [comment]
Ahkk, then make it even a rack

2017-09-14 13:08 GMT+01:00 MineShadow7 <notifications@github.com>:

**Comment by Irizase** [comment]
That was the key! Thank you so much! I'm so tired of responding to every
citizen! they get demanding after awhile.

**Comment by Irizase** [comment]
The wiki still has it as a chest! =) Might want to update it.

**Comment by MineShadow7** [comment]
I think this can be closed for now.
