### ISSUE TITLE
Cannot build warehouse

### ISSUE THREAD

**Issue by markusvisse** [ldtteam/minecolonies#1449]
### Minecolonies version
In Invasion modpack.
0.8.3056

### Expected behavior

Build a Warehouse

### Actual behaviour

Cannot build a warehouse, it says it is limited to one per town, despite the fact I do not have any yet.

### Steps to reproduce the problem

1. Try to build a warehouse
2. Fail
3. ...
4. Profit

**Comment by Asherslab** [comment]
are you the owner of the colony? Or an officer?

**Comment by markusvisse** [comment]
Wow, fast reply!
I ma an officer, the only priviliges that I don't have is to fight guards or edit priviliges.

**Comment by Asherslab** [comment]
Yeah, apologies currently only the owner of a colony may place a Warehouse. @Raycoms weren't you going to fix this?

**Comment by Raycoms** [comment]
I think it should be fixed in the version including the barracks.

**Comment by markusvisse** [comment]
Wow, even faster replies! Thanks so much!
Can I somehow change the ownership? My friend that put the town hall is not playing at the moment, if he would log in can he pass it to me?

**Comment by Raycoms** [comment]
Any admin can change this for you. If you're admins of the world its /mc
colony ownerchange colonyId yourname

2017-09-13 23:38 GMT+01:00 markusvisse <notifications@github.com>:

**Comment by markusvisse** [comment]
Thank you very much!
