### ISSUE TITLE
[Feature] Architect's Office

### ISSUE THREAD

**Issue by ghost** [ldtteam/minecolonies#1452]
I'd like to suggest an architect's office where the player could perform basic customization of buildings.
1. Shift-right click a map on a building's "block" to get a blueprint.
2. Take the blueprint to the architect.
3. Specify which blocks should be replaced with which blocks when building. (i.e, oak wood to brick, torches to IE lanterns, etc.) I was thinking that there could be an exchange list in the architect's GUI. The architect would then go to the site to do her elevations (i.e, burn time).
   3a. Bonus points if functional blocks can be replaced with blocks that have the same function (vanilla crafting for tinker's crafting or an AE crafting terminal.
   3b. Double bonus points if the architect can mark some materials "ignore" so that builders will skip blocks containing lights, cables, decorations, railcraft tracks, etc. rather than break them. (Maybe have a chest in the architect's hut that contains materials to ignore.)
4. Order the structure to be built or repaired.
5. Create pretty steampunk/fantasy/high-tech/etc. town.

**Comment by Wissi** [comment]
I agree it is an awesome idea.
Problem is that it's a very complicated concept to code and implement.
Not enough coders atm helping out atm.
But I agree it's a great idea.

**Comment by ghost** [comment]
Not to necro ;), but couldn't it just copy the original structure with a find and replace?

**Comment by Nightenom** [comment]
As mentioned back in #2872, this one is about changing the price of blocks you need to get to build a certain level - so you need to pay for this somehow, so the level costs the same or more

**Comment by ghost** [comment]
To be clear, based on discussion in #2872, the intended use of the Architect's Office is a) making aesthetic changes that would fit better with modpacks and probably increase the cost over basic wood and stone and b) allowing some substitution to take advantage of the great diversity of functional blocks available in mod packs (double furnaces, electric lights, etc.).

If maintaining a cost per building level issue is in question,  building construction kits or schematics might be in order. Something along the lines of the initial ship/campsite but using more expensive items and/or compressed items (like in Prefab). Alternatively, the architect (who does nothing when not being used) may be slow and charge a fee (drafting supplies are expensive apparently).

**Comment by Raycoms** [comment]
Closed in favor of joint issue.
