### ISSUE TITLE
[Feature Request] config for middle names

### ISSUE THREAD

**Issue by jcamden** [ldtteam/minecolonies#1453]
In 0.8.3804, there is no config option to disable the middle initial of colonists' names.

I am a giant nerd, obviously, and I've imported a custom list of names which I compiled from the Hebrew Bible. If, for example, the first name is "Gershom" and the last name is "of Midian," I end up with a colonist named "Gershom B. of Midian." I wouldn't want to show that to my friends! I wouldn't want to show any part of this to my friends, but especially not with that awkward middle initial. Would be cool if I could disable. Thanks for your time!

**Comment by Raycoms** [comment]
That's quite interesting, have you tried to make the middlename list empty in the config like only containing " " the empty string.

**Comment by jcamden** [comment]
Well, there doesn't appear to be a middlename list in the config. I only have femaleFirstNames, lastNames, and maleFirstNames, in that order. I just assumed Minecolonies generates a random letter + "." for the middle name. 

By the way (further highlighting my surpassing dorktasticity), ooo, cool to chat with a Minecolonies dev! Years ago, I totally used to daydream about a project just like this; and I'm always most amused by the somewhat hapless Mincecolonies Team vids. Great stuff. Thanks again!

**Comment by Asherslab** [comment]
Hahaha. yeah the vids can be kinda sparatic 😛

**Comment by zyxifrash** [comment]
Confirmed as described, colonist middle name is literally assigned as "getRandomLetter(rand)".

Will have this config option implemented shortly.

**Comment by Wissi** [comment]
@zyxifrash Was this implemented already? 
Can we close this now?

**Comment by SulpherStaer** [comment]
This is indeed implemented and functioning properly, thus should be closed.
![2018-05-09](https://user-images.githubusercontent.com/5037244/39829881-2007801e-53c0-11e8-995a-ac396feb9c38.png)

**Comment by mkienenb** [comment]
Pr #2541 finally contains a fix for citizen names up to 10 words long.
