### ISSUE TITLE
 Simple problem in button text to dismiss colonist

### ISSUE THREAD

**Issue by scriptsengineer** [ldtteam/minecolonies#1460]
### Minecolonies version

version 1.12.1-0.8.4000

### Expected behavior

- We wait for the text "Fire"

### Actual behaviour

- When being in the contracted state, the blocks from where the employment is contracted, does not change the text to "Fire" and continues "Hire"

### Steps to reproduce the problem

1. Hire colonist
2. View text button "Hire" continue

**Comment by Asherslab** [comment]
That is because you are able to hire multiple Colonists (AFAIK)

**Comment by scriptsengineer** [comment]
Sorry, did not know the implementation of the same, but anyway, strangely does not appear who is hired up.
