### ISSUE TITLE
miner wont work in mine

### ISSUE THREAD

**Issue by 404notfound91** [ldtteam/minecolonies#1466]
### 1.12.1

version 0.8.3530 

### go mining in mine

- XXX

### AFK at the start of a mine tunnel

- YYY

### 1-create a mine
        2-miner starts dig tunnel in mine
        3-go afk in tunnal
here is a pic
![2017-09-20_14 05 25](https://user-images.githubusercontent.com/32132214/30645193-d2d24dce-9e0c-11e7-90e8-6be884a9c269.png)

**Comment by 404notfound91** [comment]
i kill the last guy who did that but this guy is still doing this idk why

**Comment by Raycoms** [comment]
Can you show us the log?

2017-09-20 14:07 GMT+01:00 404notfound91 <notifications@github.com>:

**Comment by 404notfound91** [comment]
what is a log??(I'm a noob btw)

**Comment by Raycoms** [comment]
there is a "log" folder in minecraft which writes down events of the game.
Its in the root minecraft folder.

2017-09-20 17:46 GMT+01:00 404notfound91 <notifications@github.com>:

**Comment by Justen-N** [comment]
Hey, quick workaround for your issue, recall the worker and grab and replace everything in his inventory. Hopefully, this should return him to the behavior he is missing. At least until we can fix the problem.

**Comment by Raycoms** [comment]
we have an issue for that already
