### ISSUE TITLE
Crash when placing schematics

### ISSUE THREAD

**Issue by carlansor** [ldtteam/minecolonies#1468]
### Minecolonies version

minecolonies-universal-1.12.1-0.8.4026

### Problem

After scanning some buildings with the scan tool, the game crashes when i want to place them with the build tool, it never gets to be rendered.

### Steps to reproduce the problem

1. Scan a building, like warehouse.
2. Try to select it on the building schematics menu
3. Crashes
4. 

Here's the crash log:
https://pastebin.com/SJLwXugQ

**Comment by Asherslab** [comment]
Yep, there's a fix for this (Not sure if it's merged yet. but should be soon!)

**Comment by carlansor** [comment]
no worries then, thanks!

**Comment by Raycoms** [comment]
SHould be merged now.
