### ISSUE TITLE
Weapons.cfg

### ISSUE THREAD

**Issue by georgio3333** [ldtteam/minecolonies#1471]
### Minecolonies
version 1.10.2 0.84015

### Forge
Version 1.10.2 12.18.3.2477

### Cavern 
version 1.10.2 1.8.3

### Ender IO
version 1.10.2 3.1.183

### Expected behavior

- The guards wear armor and a weapon and use them.

### Actual behaviour

- Some guards lose their armor after putting it on.
the armor is not deposited in their chest and is not brought back by the deliveryman to the warehouse.
The armor simply disappears.
I did the test with vanilla armor, ender io (dark armor) and armor of Cavern mod.

- As I have tested different arc of several Mods (cavern for example) and the rangers take them well but does not use them.

I would like to know if it is possible to add a cfg file that would add the weapons ID that the guards can use.

all them don't have enchant.

### Steps to reproduce the problem

I don't know because i have 3 guards tower with ranger and 2 of them only lose their armor.
For info
The level of guards who lose stuff is 16 and 2
The level of other guard is 23

**Comment by Raycoms** [comment]
Hi there, can you test this losing problem with the most recent 1.10 version?

**Comment by Wissi** [comment]
Also please try only with Minecolonies. It seems like some other mods is causing the dissapearing issue.
