### ISSUE TITLE
Warn's on console that can't find resource table for barbarians

### ISSUE THREAD

**Issue by Foxgreat** [ldtteam/minecolonies#1473]
### Minecolonies version
version 0.8.4000

### Expected behavior

- No console warns

### Actual behaviour

- Have warns that sends in console by launch 7 times
[Server thread/WARN]: Couldn't find resource table minecolonies:entityarcherbarbariandrops
[Server thread/WARN]: Couldn't find resource table minecolonies:entitychiefbarbariandrops
[Server thread/WARN]: Couldn't find resource table minecolonies:entitybarbariandrops

**Comment by Raycoms** [comment]
Should be fixed with the next update.
