### ISSUE TITLE
The waypoint block is not being scanned into the .nbt file

### ISSUE THREAD

**Issue by kedamono** [ldtteam/minecolonies#1478]
### Minecolonies version

version 1.10.2-0.8.4038

### Expected behavior

- When you scan a structure or path that has waypoint, the waypoint is included in the resulting .nbt file.

### Actual behaviour

- Created several paths and scanned them in. None of them have the waypoint block included in the .nbt file.

### Steps to reproduce the problem

1. Place a Waypoint block on the ground.
2. Scan the ground and the waypoint.
3. Have the builder build the resulting .nbt file.
4. Using the builders wand, select Waypoints.

When you do, you do not see the waypoint marker floating in the desired location.

**Comment by Raycoms** [comment]
Oh damn I forgot to put that fix in, let me extract it from the cook branch

2017-09-26 7:00 GMT+01:00 kedamono <notifications@github.com>:

**Comment by Raycoms** [comment]
Fixed in the newest.
