### ISSUE TITLE
crash while exploring on server(1.12.1-2485)

### ISSUE THREAD

**Issue by SDUBZ** [ldtteam/minecolonies#1481]
### Minecolonies version

minecolonies-universal-1.12.1-0.8.4026
### Expected behavior

-go exploring and not crash

### Actual behaviour

crashed me back to desktop

### Steps to reproduce the problem

1. have version listed above with forge 1.12.1-2485
2. go explore on server 
3. crash back to desktop
4. Profit

crash report: http://puu.sh/xJFRP/ad9b15dacd.txt

**Comment by Raycoms** [comment]
That looks bed, will take a soon at it asap.

2017-09-26 23:20 GMT+01:00 SDUBZ <notifications@github.com>:

**Comment by Raycoms** [comment]
fixed
