### ISSUE TITLE
Lost Colonists after going to new Alpha

### ISSUE THREAD

**Issue by Howman** [ldtteam/minecolonies#1484]
### Minecolonies version

minecolonies-universal-1.12.2-0.8.4118

### Expected behavior

- To work as expected 

### Actual behaviour

- Well after going to this version Colonist Disappeared and none of the chest can be accessed  

### Steps to reproduce the problem

1. Start game
2. ZYX
3. ...
4. Profit

Is there away to get it back or do i have to start over

**Comment by Howman** [comment]
Is there any to get Colonists back If i replace the town hall chest will that restore the colonists

**Comment by Raycoms** [comment]
you can try recall all in the townhall, or rolling back the colonies.dat file.

**Comment by Howman** [comment]
Well I can't even access any chest click on any chest and nothing happens. How would i go about rolling back data

**Comment by Raycoms** [comment]
In the world folder there is a minecolonies folder with several colonies
dat backlogs, replace the current colonies.dat with one where it still
worked.

2017-09-29 17:07 GMT+01:00 Howman <notifications@github.com>:

**Comment by Howman** [comment]
Thank you replaced dat went to townhall recall and got Colonists back but the barracks chest and barracks tower chests are gone and some of my buildings went back to level 0

**Comment by Justen-N** [comment]
Howman, you'll have to rebuild, you've just restored a backup. Those building did not exist/were not upgraded when the backup you used was saved.

**Comment by Raycoms** [comment]
problems similar to that should be fixed with the newest alphas.
