### ISSUE TITLE
crash upon loading in onto server

### ISSUE THREAD

**Issue by SDUBZ** [ldtteam/minecolonies#1485]
### Minecolonies version

minecolonies-universal-1.12.1-0.8.4026

### Expected behavior

- not to crash have dont all the info because was handed to me by one of my users

### Actual behaviour

- load into server and crash on load

### Steps to reproduce the problem

unsure was handed by one of my users

crash report:
http://puu.sh/xKHdq/116b7496e6.txt

**Comment by Raycoms** [comment]
merged
