### ISSUE TITLE
workers/citizens getting stuck in doors

### ISSUE THREAD

**Issue by cronix91** [ldtteam/minecolonies#1488]
### Minecolonies version

minecolonies-universal-1.10.2-0.8.4072.jar

### Expected behavior

Go through the doors

### Actual behaviour

Getting stuck in the doors when more workers/citizens try to get out of the same door

### Steps to reproduce the problem

1. I sleep during night
2. They trying to get out but getting stuck.

**Comment by Raycoms** [comment]
that's one of the "improve locomotion issues" we already have a big one for that.
Unfortunately vanilla pathfinding has that issue so we have to work on top of that.
