### ISSUE TITLE
Barbarians spawning only in last village on SMP server

### ISSUE THREAD

**Issue by XerorBattler** [ldtteam/minecolonies#1489]
### Minecolonies version

1.12.2-0.8.4118 on forge-1.12.2-14.23.0.2491

### Expected behavior

Barbarians attacks all villages on SMP server

### Actual behaviour

I noticed one more issue with barbarians not spawning. We have 3 villages on SMP server (1.12.2 4128 version) and barbarians attacks only the last one. Notices are coming both on first and second (third is unloaded at the time), but real attack is only at third (there is some weird "death.attack.entity.Barbarian.name" spam to world chat).

### Steps to reproduce the problem

Build more then one village on SMP server

(I'm not sure if it's related to #1350 which was fixed by @Raycoms few moments ago)

**Comment by Raycoms** [comment]
Okay a few things:
How big are those colonies?
How long did you test?

**Comment by XerorBattler** [comment]
First one has 12 people in, second one has 4, third has 3.

A lot of barbarians (80+) attacks only the third one, we are testing this for 2 days (from release of version with barbarian spawn fix). We are testing it on our modpack https://minecraft.curseforge.com/projects/tech-magic-colonies.

If you can merge #1350 to 1.12.2 branch on curseforge then I will test if it has same issue.

**Comment by Raycoms** [comment]
Ah that explains it, they spawn only for colonies with more than 4 citizens.

**Comment by XerorBattler** [comment]
Does it? They attack only the colony with 3 people in. It doesn't look as explain to me.

**Comment by Raycoms** [comment]
Oh, the attack the one with 3 citizen only? Know I understood.
That is quite strange, never happened to me

**Comment by XerorBattler** [comment]
Yea I tried it just now with forced barbarian attack. 
I run "/mc colony raid 1" and then waited, nothing happened in first colony. But after I warped to third colony there was a raid. So I killed whole raid and rerun "/mc colony raid 1" while I was in third one. No attack happened in third one. But after I warped to first one and back there was a new attack again in third one.
It seems there is some sort of issue with chunk loading.

**Comment by Raycoms** [comment]
Are you the owner of the first colony where the raids are happening?

2017-09-29 22:39 GMT+01:00 VaclavHaramule <notifications@github.com>:

**Comment by XerorBattler** [comment]
Nope I don't own any colony yet.

**Comment by Raycoms** [comment]
Okay, this is strange, they should spawn inside the colony with > 5 and if
it's not loaded they shouldn't spawn anywhere.
The Id of the colony with >= 12 citizen is 1, the id of the colony where
the raids are happening is "3" ?

2017-09-29 22:42 GMT+01:00 VaclavHaramule <notifications@github.com>:

**Comment by XerorBattler** [comment]
Yep, there are only three colonies. ID 1 have 12 citizens, ID 2 has 4 and ID 3 has 3.

**Comment by Raycoms** [comment]
I will try to debug this on our server and try to find what is happening
here...

2017-09-29 22:45 GMT+01:00 VaclavHaramule <notifications@github.com>:

**Comment by XerorBattler** [comment]
If you need, you can join my test server (it has hard copy of live server world save), in that case just tell me and I'll op you there.

**Comment by Raycoms** [comment]
Okay, #1 problem is that this command doesn't work for a specific colony, it will work for all, not we have to find out why it spawns them in the wrong colony.
