### ISSUE TITLE
Item Frames missing from Builder's List of Materials for Warehouse 3,

### ISSUE THREAD

**Issue by mfmiller** [ldtteam/minecolonies#1490]
### Minecolonies version

version 1.10.2-0.8.3880 and 0.8.3227

### Expected behavior

When building Warehouse 3 (wood), the total number of item frames needed should be on the builder's material list. The builder should ask for the full amount of item frames needed in chat and hold the item frame object in their hand. 

### Actual behaviour

The item frames don't show up on the builder's material list. When it is time to put in the item frames, the builder asks for 1 item frame at a time, and holds an non-item-frame object. Spruce slab, for me. (Not sure if the spruce slab is replicable, may just be the last item  the builder held.) I think this behavior also holds true for Warehouse 4 and  maybe 5, if more item frames are needed, but not sure.

### Steps to reproduce the problem

1. Build warehouse 3
2. Look at builder's material list and builder, look  for announcements about item frames in chat.

**Comment by nuindil** [comment]
I am having the same problem as described above by mfmiller with Minecolonies version 1.10.2-0.8.4063.

**Comment by daddy77gaming** [comment]
Sandstone warehouse build to level 5 is also missing the item frames in the requested items by builder, just give them yourself will help.. otherwise the Dman will only bring 1 itemframe each trip.

**Comment by Raycoms** [comment]
Did you try the newest versions available? (alpha)

2017-10-16 22:02 GMT+01:00 daddy77gaming <notifications@github.com>:

**Comment by Raycoms** [comment]
I guess its fixed
