### ISSUE TITLE
minecraft 1.11.2 forge and quarry no recipes and farmes stops working

### ISSUE THREAD

**Issue by zezreli** [ldtteam/minecolonies#1491]
### Minecolonies version

version 0.8.4057 or curse X.X.XX

### Expected behavior
farmer does farming like harvest and replant 
- XXX
recipes for forge and guarry
### Actual behaviour
farmer sometimes just stop working he just stands  by the field and stands there and to get him to plant or harvest you need to recall him a few times before he/she starts to work again
- YYY

### Steps to reproduce the problem

1. XYZ
2. ZYX
3. ...
4. Profit

**Comment by Raycoms** [comment]
Hi, Forge and Quarry are not yet implemented.
About the farmer I bet he is getting stuck on some water, we have an issue for improving the moving already.
