### ISSUE TITLE
Unable to reassign colonists to a new house (1.10.2)

### ISSUE THREAD

**Issue by PoroUsedSnax** [ldtteam/minecolonies#1492]
### Minecolonies version

version 1.10.2-0.8.4113 or curse 0.8.9

### Expected behavior

- When removing a colonist from their current home, they remain in the list of colonists so you can assign them to another house.

### Actual behaviour

- When removing a colonist from their current home, they seemingly disappear from the list of colonists within the house assignment UI, therefore you are unable to add that colonist to any houses, leaving them homeless. It's also been mentioned by others on the server that any colonists you remove from a house actually return to the house they should have been removed from.

### Steps to reproduce the problem

1. Remove a colonist from a house they are currently assigned to.
2. Search for that colonist within the house assignment UI.
3. ...
4. Profit

**Comment by Raycoms** [comment]
Will debug this after dinner for sure.

2017-09-30 23:47 GMT+01:00 El-Poro <notifications@github.com>:

**Comment by Raycoms** [comment]
fixed and uploaded
