### ISSUE TITLE
Server Crash with the new version  1.10.2-0.8.4160

### ISSUE THREAD

**Issue by cronix91** [ldtteam/minecolonies#1496]
### Minecolonies version

minecolonies-universal-1.10.2-0.8.4160

### Expected behavior

Server and client startup

### Actual behaviour

Downloaded the new version. Tried to start up server with the new version but crashing. 
Crash report: https://pastebin.com/vHkAQYS8

### Steps to reproduce the problem

1. Download new version
2. Put it in mod Folder
3. Start up Server
4. Crashing

**Comment by Raycoms** [comment]
Hi, sorry for the inconvenience, I'm currently working on fixing this.

Will push out a build with around 3-4 urgent bug fixes. (Including some
quite old ones).

2017-10-01 23:43 GMT+01:00 cronix91 <notifications@github.com>:

**Comment by cronix91** [comment]
Sounds great! Love the mod so keep up the good work!

**Comment by Raycoms** [comment]
Newest fix uploaded, check it out
