### ISSUE TITLE
Colonists don't follow waypoints if they are up a block

### ISSUE THREAD

**Issue by pckuijper** [ldtteam/minecolonies#1503]
Colonists seem to only follow waypoints at the same level or possibly 1 lower. But never up causing them to avoid certain paths even if stone path.

https://imgur.com/a/2pm6v

The red/blue arrows show the path the colonists take

**Comment by Raycoms** [comment]
They always try to optimize their paths a bit, they will try to pass closely to the waypoints and close to the stonebricks but sometimes they optimize a bit too much. What you could try:

Leave the first waypoint, leave the one in front of the building and add one where the last dman is, that might force them to walk on the path.
