### ISSUE TITLE
2 miners

### ISSUE THREAD

**Issue by polikarpov5** [ldtteam/minecolonies#1506]
### Minecolonies version

version 1.12.1-0.0.4077

### Expected behavior

- have 2 miners

### Actual behaviour

- 1 work only

### Steps to reproduce the problem

Hello,
If I have 2 miners, only one works, the other is in "waiting for".
 I dismiss him then resume him, he works 
but it is the other miner who is stopped.

**Comment by Raycoms** [comment]
I think this doesn't depend on having two miners, give the other miner (the one who isn't working) some cobblestone and dirt
