### ISSUE TITLE
Scan tool copying.

### ISSUE THREAD

**Issue by Moobien** [ldtteam/minecolonies#1508]
### Minecolonies version
1.11.2-0.8.4057
version X.X.XXXX or curse X.X.XX

### Expected behavior

- XXX

### Actual behaviour
I copied the wooden tier 5 warehouse and when i started building it the builder is wanting the contents of the chests as part of the build. My plan was to copy the building, modify it to house my mekanism storage etc and then copy it again so i can use it in future games. Should the scan tool be copying the contents of the chests?
- YYY

### Steps to reproduce the problem

1. XYZ
2. ZYX
3. ...
4. Profit

**Comment by Raycoms** [comment]
Hi there,

Yes the scan tool copies 100% of the schematic including chest contents, entities, tileEntities etc since that's what the builder will need to reconstruct it 100%.

If you don't want that, for now, you'll have to empty the chests first.
