### ISSUE TITLE
Pam's Harvestcraft issue in single player mode

### ISSUE THREAD

**Issue by ladyannie68** [ldtteam/minecolonies#1509]
### Minecolonies version

curse 8.8.0

### Expected behavior

when breaking harvestcraft gardens crops are obtained.
### Actual behaviour

currently only working with windy gardens all others break with no outcome. Not occurring on server.

### Steps to reproduce the problem

after update retested single player game and also loaded a fresh world with this still being the issue

**Comment by Justen-N** [comment]
Pam's was having an issue with this. Is your log file showing a Minecolonies issue? I believe MatrexsVigil pushed out an update that should have fixed this.

**Comment by Raycoms** [comment]
Forgot to close this, @Wissi can we update the config of the minecolonies modpack of pams harvestcraft or something?
