### ISSUE TITLE
Have buildings emit light

### ISSUE THREAD

**Issue by Raycoms** [ldtteam/minecolonies#1510]
What would be interesting is having buildings emit light, like level 1 only a bit, level 2 a bit more... level 5 a lot.
So higher level buildings would also avoid mob spawns in a certain radius.

**Comment by cronix91** [comment]
Really good idea. Some light decoration would be really awsome as well. like, street lamps,  lanterns or something like that.

**Comment by MineShadow7** [comment]
Shouldn't torches do that job?

**Comment by Raycoms** [comment]
The effect should be bigger like 20 blocks on a level 5 buildings. (We can
discuss the range).

2017-10-07 19:40 GMT+01:00 MineShadow7 <notifications@github.com>:

**Comment by MineShadow7** [comment]
Then what guards should defend (except barbarians raids) if colony have lights everywhere?

**Comment by Raycoms** [comment]
Mostly things at the colony borders and not in the middle of the colony
(but barbarians)

2017-10-07 19:47 GMT+01:00 MineShadow7 <notifications@github.com>:
