### ISSUE TITLE
Upgrading townhall doesnt work

### ISSUE THREAD

**Issue by Maetzl** [ldtteam/minecolonies#1511]
### Minecolonies version

version 0.8.4234 or curse 0.8.11

### Expected behavior

-

### Actual behaviour

-

### Steps to reproduce the problem

The Builder is upgrading any other building but if i want to upgrade my town hall (mesa LV. 2). The builder is building but he is only holding a block what he doesnt need. Sometime he is walking back and over his head is standing : Waiting for. After this he walkes back and over his head stands building. I Fired and rehired him doesnt work. I recalled him 100 times also doesnt work.

sry for my bad english.

**Comment by Raycoms** [comment]
Hi there, the mesa building has a huge underground part so he might be
filling in holes there and will need quite a while until he reaches the
party of the surface

2017-10-08 0:29 GMT+01:00 TLN00B <notifications@github.com>:
