### ISSUE TITLE
[1.12.2] NPE Client Crash

### ISSUE THREAD

**Issue by Morpheus1101** [ldtteam/minecolonies#1512]
minecolonies v1.12.2-0.8.4191
Forge *.2503

Mod Pack: ATM3

Crash Report @ https://puu.sh/xSAJF/99d1176844.txt

Unknown on exactly how to reproduce this

**Comment by Raycoms** [comment]
Have produced a fix for 1.10 already, will port it soon

2017-10-08 1:07 GMT+01:00 Morpheus1101 <notifications@github.com>:

**Comment by Morpheus1101** [comment]
okies thanks.

**Comment by Raycoms** [comment]
Currently testing if it really resolves the problem, I think by monday I
will have a port

2017-10-08 1:09 GMT+01:00 Morpheus1101 <notifications@github.com>:

**Comment by Raycoms** [comment]
Does this still happen with the newest minecolonies 1.12 on curse 4221?

**Comment by Saintares97** [comment]
Yep, it still happens on 4221.

**Comment by Raycoms** [comment]
Can you show me a log of it happening in 4221? I think it might crash at a slightly different place now.

**Comment by Morpheus1101** [comment]
The simplest way i was able to re-create it in the prev version was to attempt to interact with a machine i didnt have permission to use and it triggered the crash, idk if the same can be said for the newer vers

**Comment by Raycoms** [comment]
This was guaranteed to happen?

**Comment by Raycoms** [comment]
Okay I just tested it in 1.12 at least for me on a dedicated server it didn't happen.

**Comment by Saintares97** [comment]
Log https://pastebin.com/D8sy0Ngd

It is odd and difficult to replicate, at one point I crashed and I was simply typing in chat while standing at someone's colony, I am the server admin. It is quite random, one of my players hasn't even had the crash.

**Comment by Raycoms** [comment]
Okay I'll take a look at it right now

2017-10-09 0:42 GMT+01:00 Saintares97 <notifications@github.com>:

**Comment by Raycoms** [comment]
Please try this:
https://minecraft.curseforge.com/projects/minecolonies/files/2488871

2017-10-09 1:17 GMT+01:00 Ray Neiheiser <ray.neiheiser@gmail.com>:

**Comment by Saintares97** [comment]
Will do, thank you. You guys are fast!
