### ISSUE TITLE
Colonists don't go into their homes.

### ISSUE THREAD

**Issue by Rosomah** [ldtteam/minecolonies#1521]
### Minecolonies version

minecolonies-universal-1.10.2-0.8.4279

### Expected behavior

- All colonists go into their homes after dark.
### Actual behaviour

- Some of them do enter their homes, but a few just stand outside of their house, which makes them easy targets for barbarians and other hostiles.

This occured in some previous versions as well, but I can't remember when.

**Comment by Raycoms** [comment]
Should be fixed
