### ISSUE TITLE
Barbarians spawn in the middle of my colony

### ISSUE THREAD

**Issue by Rosomah** [ldtteam/minecolonies#1522]
### Minecolonies version

minecolonies-universal-1.10.2-0.8.4279

### Expected behavior

- They should spawn somewhere on the colony's boundaries.

### Actual behaviour

- It's a real pain, since they spawn immediately at night time and my workers haven't yet returned to their homes which sometimes leads to their demise (muahahaha).

**Comment by marchermans** [comment]
That depends, they spawn on the Point that is the furthest away from the Colony Center (your townhall) and is still loaded.

Meaning that if it determines that the Barbarians spawn in the Northeast this night, and your colony Center is the furthest North east Point that is loaded then they will spawn there.

**Comment by Rosomah** [comment]
But.. I was standing somewhere 20 blocks from the town hall, and they spawned almost on top of me, I almost shit myself.. And I have a chunkloader which is set to a radius of 7 I think, which means they should spawn at least 7 chunks from the town hall right?

**Comment by Raycoms** [comment]
do you have any buildings in that direction? The thing is we search the
farthest out building or decoration into a direction which is still loaded,
then we go around 20 more blocks if they are loaded and then we spawn them,
we might want to increase that extra buffer a bit.

2017-10-11 13:19 GMT+01:00 Rosomah <notifications@github.com>:

**Comment by Rosomah** [comment]
Yeah, I have buildings at least 2 chunks in every direction away from the townhall, yet that one time, they spawned almost on top of me, since I saw the message that they're coming and 2 seconds from then, someone slaps me from behind.

**Comment by Raycoms** [comment]
Will have to debug this then a bit more.

**Comment by bob0bob** [comment]
I've had 2 nights that barbarians spawn and they spawn in the middle of the town both times.  Guards are not doing much, they walk right by them and the barbarians do not attack either.   Te barbarians are just wondering around doing nothing.   Every once in a while a ranger attacks but it is random.   I've not seen the barbarian attack anyone or me either time.  they just wonder around.

I'm using default config.

**Comment by bob0bob** [comment]
OK.  Every barbarian raid spawns only about 20 blocks from town hall.   They don't attack anyone.  They just wondering around.  They don't attack the guard or me.

**Comment by Raycoms** [comment]
Yeah I made an issue for that on 1.12 then.

**Comment by Raycoms** [comment]
I think most of the spawning issues should be resolved now.
