### ISSUE TITLE
Observations ans suggestions.

### ISSUE THREAD

**Issue by Moobien** [ldtteam/minecolonies#1524]
Hey guys  in the last few days of playing with your mod I have to say its awesome.  Have some observations and suggestions.  Running latest version for 1.11.2 and playing with the unlimited resources option on. Some of these things have probably already been mentioned and suggested but I thought I would give my input.

1: had 6 fancy fields built (4 wheat, 1 carrot 1 potato). Had 2 farmers, 2 of the wheat fields were full and ready for harvesting, had no potatos. The farmers ignored the wheat fields and instead sat there demanding potatoes. After an hour i got sick of them whinging and gave them potatoes. During this time not one wheat field was tended to.

2: Suggestion - farmers able to use bonemeal and other fertilizers.

3: Observation - at level 5 the builders huts, with exception to the mesa one, are cluttered and cramped as hell. Perhaps update each schematic to tidy them up like the mesa one does.

4: Observation - villagers seem to get stuck in doorways, my guess is when one is entering as another is leaving. Had one DMan hut with 3 guards stuck in the doorway, removing the door seemed to unstick them.

5: Suggestion - A player drop off hut that the DMan can retrieve from would be useful. Saves time when you have villagers asking for crafted items as you can make them and drop them off at a central location. An upgrade to this could be a resource request option (villager wants oak slabs, you request oak wood and the DMan gets you however much you ask for IF its in the warehouse)

6: I found it amusing when my miner said he needed a pickaxe of greater level than diamond.

7: if possible remove the trapdoors from all wood buildings. Sure they look nice but ONLY after you have gone and manually flipped every one of them (sans bakery) You could change the bakery sails to wool instead of trapdoors.

8: Chunk loading..... even with a heap of IC2 chunk loaders in place construction stopped once I was too far away. Had 1 chunk loader next to a major construction and it still stopped and didnt resume until i was in range again.

9: whatever you do, DONT scan in major structures lol. Frame rate takes a dive when you then try to position the copy in the world. I modified the lvl 5 wood warehouse to suit my needs as a factory building and its not pleasant to position for construction.

**Comment by cronix91** [comment]
8: I use chicken chunk and  it work great for me. they still whining about things when im off the server, Haha.  Chunkloaded Colonies would be great and it can maybe be activated in the config?

**Comment by Moobien** [comment]
Gave chicken chunks a go and makes no noticeable difference

**Comment by Asherslab** [comment]
Sorry, for number 8 we are not, and never will, do chunk loading. it's a major hassle code-wise and it would absolutely KILL any machine, we have enough problems with performance already lol
😄

**Comment by Enverex** [comment]
The issue with villagers happens even when they're both going the same way. Every day all of my villagers get stuck trying to leave their rooms (as they appear to have gone 2 to a room rather than going into their own second room of the building). Basically they're pushing each other out of the way of the door, so neither of them get through. Examples below.

![2017-11-26_20 37 59](https://user-images.githubusercontent.com/958670/33244169-6c230772-d2ea-11e7-8829-7f4f3aa8dfdb.png)
![2017-11-26_16 17 20](https://user-images.githubusercontent.com/958670/33244170-6c3ca95c-d2ea-11e7-9f6b-5c2573e5050d.png)

**Comment by Raycoms** [comment]
have you tried using the newest builds?

2017-11-26 20:44 GMT+00:00 Benjamin Hodgetts <notifications@github.com>:

**Comment by Enverex** [comment]
I didn't realise you were moving that fast. I'm using a version from a few days ago. I'll update and report back.

**Comment by Raycoms** [comment]
Not so fast, I will send you a better one to test. just a minute.

**Comment by Raycoms** [comment]
Try this one:
https://s3.eu-central-1.amazonaws.com/minecolonies/Minecolonies/Minecolonies_Branches/5257/minecolonies-universal-1.12.2-0.8.5257.jar

I think I fixed it (They might get stuck up to 10 seconds).

2017-11-26 22:54 GMT+00:00 Ray Neiheiser <ray.neiheiser@gmail.com>:

> Not so fast, I will send you a better one to test. just a minute.
>

**Comment by Enverex** [comment]
Roger. I'll have to test tomorrow afternoon, I'll report back then.

**Comment by Enverex** [comment]
Not seen it happen again with that new version. I'll post back here if it does.
