### ISSUE TITLE
Lumberjack only tracking birch-trees

### ISSUE THREAD

**Issue by tomorrow4268** [ldtteam/minecolonies#1525]
### Minecolonies version

latest and earlier versions 1.11.2

### Expected behavior

- lumberjack should track down all trees when not changing setup or if defined only the tree-type of choice

### Actual behaviour

The first time, the lumberjack was hitting leaves of 2x2 spruce trees and after i changed the settings to only cut down birch, since those are less difficult, he never stopped cutting those.
- After changing tracking-settings, lumberjack is only cutting down birch trees. activating spruce and oak and deactivating the tracking of birch will result in an inactive lumberjack even if there are plenty of trees around. Reactivating birch will immediately activate tracking of birch.

### Steps to reproduce the problem

1. changing tracking settings of the lumberjack-building
2. even after restart, same problem
3. modpack with tinkers construct and botania

**Comment by tomorrow4268** [comment]
Modpack
![screen shot 2017-10-12 at 15 50 43](https://user-images.githubusercontent.com/23143040/31499472-2ad7cf94-af65-11e7-92af-e19f17b480b1.png)

**Comment by tomorrow4268** [comment]
if i set a oak sapling on his first inventory-slot with "track only oak trees" he will be searching for trees and not find it (this tree is ~20 blocks away from the building (level 3))
![2017-10-12_15 56 44](https://user-images.githubusercontent.com/23143040/31499827-2c4ce598-af66-11e7-9d65-9a4442edc153.png)

**Comment by Raycoms** [comment]
Is there a way to reproduce this 100% ?

2017-10-12 14:58 GMT+01:00 tomorrow4268 <notifications@github.com>:

**Comment by tomorrow4268** [comment]
it was reproduced by deactivating all trackings and restarting the session(save&quit). After redefining the trackings, the lumberjack didn't recognize oak, spruce,.... still birch was recognized

**Comment by Raycoms** [comment]
I can't reproduce it, does this happen in single or multi player?

**Comment by Raycoms** [comment]
Can you send me your logs?
