### ISSUE TITLE
[Suggestion] clearing out volume/ flattening surfaces

### ISSUE THREAD

**Issue by tomorrow4268** [ldtteam/minecolonies#1526]
Adding several schematics with different dimensions filled with "air" (0)-Blocks with maybe fence-corners in order to see the borders when placing them to the Builders schematic-list.
This will allow the possibility of doing terraforming or flattening locations and be able to build  cities more easily.

**Comment by Raycoms** [comment]
Just create them, upload them on the forums we will review them and can add
them =)

2017-10-12 15:04 GMT+01:00 tomorrow4268 <notifications@github.com>:

**Comment by tomorrow4268** [comment]
it was reproduced by deactivating all trackings and restarting the session. After redefining the trackings, the lumberjack didn't recognize oak, spruce,.... still birch was recognized

**Comment by Raycoms** [comment]
I will take a look at it at the weekend.

2017-10-12 15:21 GMT+01:00 tomorrow4268 <notifications@github.com>:

**Comment by tomorrow4268** [comment]
thx , have a nice weekend ;)

**Comment by Raycoms** [comment]
Yeah Like I said, I think the easier would be if people scan those in like they'd want them and upload them on the forums =)
