### ISSUE TITLE
[bug] wrong interaction with furniture

### ISSUE THREAD

**Issue by tomorrow4268** [ldtteam/minecolonies#1527]
### Minecolonies version

latest

### Expected behavior

- citizen shouldn't use chairs or be able to stand up again

### Actual behaviour

- some citizen start to sit on furniture (like bibliocraft) but will never stand up again. Behave like all AI-Entities

### Steps to reproduce the problem

- mod implementation like bibliocraft

### Improvement

- maybe if they stay inactive for a certain amount of time on a tile they will automatically stand up or improve block-evasion of non-vanilla blocks.

**Comment by marchermans** [comment]
Their is no code from our side that performs this interaction.
It might be that Bibliocraft picks up on the fact that they behave like villagers and sits them down, and does not tick the entity, making it become stuck. A recall to the townhall should fix your problem.

In any case their is not much we can do. @Raycoms am i correct here?

**Comment by Raycoms** [comment]
Yeah like putting them in boats, that's something boats or chairs to on their own, we can do nothing do prevent that afaik.

Recalling fixes it.
