### ISSUE TITLE
the miner

### ISSUE THREAD

**Issue by wobbles222** [ldtteam/minecolonies#1532]
### Minecolonies version
0.8.11
version X.X.XXXX or curse X.X.XX
Minecolonies test pack 
### Expected behavior
- To mine, has the right tools

### Actual behaviour
- Despite having the right tools the miner does not mine

### Steps to reproduce the problem

1. Create block, miner appears in game associated with the block
2. Create his tools - shovel and pickaxe - and put in his inventory
3. He is supposed to use the tools to mine - but he is not doing that, he is just standing there
4. When the day ends he walks back to the Town Hall, when the day begins he just stands out the front of the Town Hall and doesn't come back to the plot
.... so despite everything being there for him, he is not mining

**Comment by Asherslab** [comment]
There are many more items needed than just tools:
(For level 1) Wooden Pick, Wooden Shovel, Oak Planks, Oak Fence, Oak Slab, Cobble (i can't think of anything else)

**Comment by Justen-N** [comment]
Miner can be a little tempermental. His pathing is fairly  complex and
sometimes he just  doesn't  want to tell you what he needs. Recall him,
pull an item from his inventory, and hopefully  he'll  get more
comfortable with expressing  himself.

**Comment by marchermans** [comment]
We are working on this.
The request system (Coming soon™) needs a way for the player to complete a request. This will get a proper GUI, so you can actually see what a citizen is waiting on and how it is being resolved.
