### ISSUE TITLE
builders die building a fancy field

### ISSUE THREAD

**Issue by daddy77gaming** [ldtteam/minecolonies#1535]
### Minecolonies version

version 0.8.4063

### Expected behavior

- building a fancy field

 ### Actual behaviour

- builders die placing redstone lamp in the 3 deep hole in the middle

### Steps to reproduce the problem

- i had 2 builders die back to back to this.. then finished it myself, dont like to kill more builders building this :)

can clear out the area to have room under it or as the structure diagram is put into the world to avoid this however i reckon most players will put the dirt level at ground level when starting this.

**Comment by Raycoms** [comment]
Thats strange, how does he die? Building the field inside him?
