### ISSUE TITLE
Crashing randomly. Permissions.Java

### ISSUE THREAD

**Issue by cronix91** [ldtteam/minecolonies#1539]
### Minecolonies version

minecolonies-universal-1.10.2-0.8.4279 and earlier version. 

### Expected behavior

Not crashing

### Actual behavior

Crashing.  The game freeze in like 4 sec, dc from server then crash. 
tried to do a server reset 2 times but still crashing randomly. 

https://pastebin.com/44REBrBi

### Steps to reproduce the problem

1. install it on server and client
2. Get random crashes
3. ...
4. Profit

**Comment by Raycoms** [comment]
Yes please use the newest alpha which should fix this.
