### ISSUE TITLE
Supply Ship did not spawn chest

### ISSUE THREAD

**Issue by steemypete** [ldtteam/minecolonies#1541]
### Minecolonies version

1.12.2-0.8.4288

### Expected behavior

Ship spawn with Chest

### Actual behaviour

Ship spawned without chest

### Steps to reproduce the problem

Dropped Ship in swamp on edge of land.
Chest did not spawn.
Can see in our Let's Play here: https://youtu.be/RZxvwlkhiXw?t=16m32s
It should start at 16m 32s a moment before we dropped the ship.

**Comment by Justen-N** [comment]
the chest should be outside the ship a few blocks away from the ladder.  maybe try placing the ship again in a different spot ( i've had this issue myself)

**Comment by steemypete** [comment]
My son placed it by accident, we did it again in a new world and it worked fine.  It was suggested I report it.

**Comment by Justen-N** [comment]
AH, I actually know what happened here. The ship had jsut enough space to make itself work, but when it placed, it removed the chest from where it was located. This issue will be resolved at a later date when placement method is changed. Thanks!.
