### ISSUE TITLE
cant place the supply camp

### ISSUE THREAD

**Issue by zezreli** [ldtteam/minecolonies#1544]
### Minecolonies version

version 0.8.4280 or curse X.X.XX

### Expected behavior

- place the camp?

### Actual behaviour

- does not place the camp even though i have a larger then 16 x 17 flat area 

### Steps to reproduce the problem

1. XYZ
2. ZYX
3. ...
4. Profit

**Comment by Justen-N** [comment]
Is there any grass  or other obstacles in the way?

**Comment by zezreli** [comment]
nope there is not want me to send a picture of the place where i want to place the supply camp?

**Comment by Justen-N** [comment]
Odd. We are planning on changing how that works in future, but I'm  unsure
of what's happening here. Do you mind posting your log of when you try to
place it?

**Comment by zezreli** [comment]
sure give me a sec

**Comment by zezreli** [comment]
[latest.log](https://github.com/Minecolonies/minecolonies/files/1404993/latest.log)

**Comment by zezreli** [comment]
there you have my log file

**Comment by Justen-N** [comment]
Alright. Are you in the overworld? Go ahead and post the picture if you would.

**Comment by zezreli** [comment]
![2017-10-22_16 58 42](https://user-images.githubusercontent.com/27296782/31863176-2b35e736-b74a-11e7-8f3a-5128a5bf5b68.png)

**Comment by zezreli** [comment]
yes im in the overworld :D there is the flat area where i want to have it 
i want the entrance of the camp faced the road
aka the cobblestone

**Comment by Justen-N** [comment]
Maybe expand the dimensions past the 16 * 17.  What's odd to me is your log shows that it should have place when you tried it at 4:20.

**Comment by zezreli** [comment]
its larger then 16*17 now, yea it should have

**Comment by zezreli** [comment]
there is water under the blocks can that be the problem?

**Comment by Justen-N** [comment]
@Raycoms, this one has got me stumped. I'm going to try to reproduce. I don't think the water is the issue.

**Comment by zezreli** [comment]
its minecraft 1.12

**Comment by zezreli** [comment]
would it be possible to somehow let the building tool to place down the supply camp block?

**Comment by zezreli** [comment]
cuz then you could rotate it in which direction you want :D

**Comment by Justen-N** [comment]
That is in the pipeline

**Comment by zezreli** [comment]
the pipeline?

**Comment by Justen-N** [comment]
We are working on it, in other words.

**Comment by zezreli** [comment]
ah okey :)

**Comment by zezreli** [comment]
so any progress on how i can place the supply camp`?

**Comment by Justen-N** [comment]
Not at the moment. I would consider downgrading to the most recent release until we have a better idea what went wrong.

**Comment by zezreli** [comment]
i cant downgrade i can upgrade to the alpha version 0.8.4369 
im using the beta version 0.8.4280

**Comment by Raycoms** [comment]
It seems like players sometimes run into this kind of problem, we weren't
able to reproduce it yet. try this: Make sure that both levels are solid
(the dirt level you'Re building at and the one under it that seemed to have
fixed it in some cases

2017-10-22 17:13 GMT+01:00 zezreli <notifications@github.com>:

**Comment by zezreli** [comment]
ah okey thanks will try :)

**Comment by zezreli** [comment]
that worked thanks @Raycoms

**Comment by YoshiWalsh** [comment]
I was encountering this issue and this thread is the top result in Google. The reason that it wasn't working for me is because some of the ground was grass blocks and some of it was dirt blocks. I think if I'd waited for all the grass to spread it would've worked, but I managed to destroy all the grass and replace it with dirt, which also worked.

Frustratingly, the message in chat doesn't help with this. It picked one of the dirt blocks and said it expected it to be air.
