### ISSUE TITLE
Farmer doesn´t do anything

### ISSUE THREAD

**Issue by shiosakun** [ldtteam/minecolonies#1546]
### Minecolonies version

version 0.8.4369 minecraft 1.12.2

### Expected behavior

- Farmer take crops, and replant.

### Actual behaviour

- Anything, it stay´s stand.

### Steps to reproduce the problem

1. Build the Farm 
2. Asign the farmer
3. I need to uste the Recall Worker button several times to make him plant crops, but then it stays when the farm is all planted and doesn´t pick them when are already mature.
4. It stays forever, and I tried to refresh the colony (with the "/mc colony refresh") and even killed the farmer and nothing.

**Comment by Flabort** [comment]
Did you build a field, too? A farmer can support up to [Level] Fields, which are centered around Field Blocks, which look like scarecrows. Without any Fields, he will not work.

**Comment by shiosakun** [comment]
Yes, I did, there´s the scarecrow in the middle but nothing... how can I share a caption from my world?

**Comment by Degenerecy** [comment]
Pack: The Simple Life 2  V: 1.3.6
Mod Version:  8.4063

I have the same issue with The Simple Life 2 pack.  Farmer will start to till the ground then stops randomly.  Recalling them will get them to continue for a bit, but then they stop again.   Current farm stopped tilling but won't plant anything I give em, including putting that seed into the Scarecrow(unsure if its what its their for).

**Comment by Raycoms** [comment]
Can you send us the log?

2017-10-24 0:08 GMT+01:00 Degenerecy <notifications@github.com>:

**Comment by Degenerecy** [comment]
[latest.log](https://github.com/Minecolonies/minecolonies/files/1412991/latest.log)
[2017-10-22-2.log.gz](https://github.com/Minecolonies/minecolonies/files/1412994/2017-10-22-2.log.gz)
These are the last 2 in my list of logs.

**Comment by Raycoms** [comment]
Can you link me a dropbox download of the pack so I might debug it?

**Comment by masternetra** [comment]
@shiosakun - Did you put a seed of what you want the farmer to grow IN the scarecrow? Doing this tells the farmer what to plant and what have you.

But yea I frequently experience the farmer ceasing to do anything as well.

**Comment by masternetra** [comment]
@Raycoms - Dropped back from lastest alpha to stable, I think the AI is unable to handle multiple fields. With just one field the AI goes about just fine for me (in the stable release at least), but introduce additional fields and it doesn't seem to be able to handle it very well. Might be better to have 1 field per NPC and allow for additional farmers as you upgrade to match the number of fields that can be attended.

**Comment by th3wyatt** [comment]
I've run into the same issue.  I'm not sure if it is local to Simple Life 2.  The farmer will harvest in spurts with VERY long idle times.

**Comment by Raycoms** [comment]
Yeah, I think I have to tweak the random decision of the field a bit.

2017-11-03 0:10 GMT+00:00 th3wyatt <notifications@github.com>:
