### ISSUE TITLE
Some Bugs I encounteret on the test server

### ISSUE THREAD

**Issue by Caer1324** [ldtteam/minecolonies#1549]
### Minecolony Testserver Singleplayer

Hello,
some Bugs I encounteret

As soon as I upgradet the wooden Bakery to lvl 3 my baker started to run back und forth between the oven and his chest. I recalled him like a dozen time, restarted the game, recalled all to the citizen hall and fired him und reemployed him. nothin changed, I employed some different all stat 1 npc, and it did not work. after I got an better stat npc he finally startet to work^^

Nearly same Problem with my Fisherman, he worket fine but as soon as the Building (wooden= hit lvl 3 he startet to bug, the original npc decidet to run back und forth to the shore and his chest, the fishing line still hanging in the water. now the next hire ( a good stats one) is just standing at the shore und claim to be working but doing nothing at all.

 my woodcutter also (wooden lvl3) bugget a bit in the beginning after some rehiring he finally startet to work again, before he just run through his forest, back to his hut and to the forest.

You see i had some problems with workers on lvl 3 buildings^^

The houses are looking great! i love the alternative ones very much. my npc are just not able to go in or out becaouse they are stuck in the door, bc two workers try to leave at the same time. This problem i encounteret with every house and as soon as i get 2 workers in a house. Not every morning but pretty often. 

Normally easy resolvable (recall the worker) but in the evening when the raiders attack THIS is annoying when they do not get in the houses. worst case the npc stand in open doors and do not get in or they stand before the door and look at it and bam they are killded (rip my favourite builder he did such a good job :( )

Maybe a bit more time after the raider annoucement would make this easier? ( to shove the villagers in their houses z.b) and i would appricate a message when you killed them all so you can relax :D 

finally i would love an easier explanation of waypoints or even a video since as an not native english speaker i understand the words on the wiki but kind of not the meaning >.<

I hope you understood my text xD and thank you for this great Mod. I have a lot of fun with it.

Lg Dolorosus

**Comment by Raycoms** [comment]
This is very strange can you ping me on discord when it happens again so I might come and take a look at it?

**Comment by Moobien** [comment]
I get the door blocking issue a LOT also. Only on single doorways though.

**Comment by Raycoms** [comment]
This should be fixed with the newest alpha

On Nov 3, 2017 2:10 PM, "Moobien" <notifications@github.com> wrote:

I get the door blocking issue a LOT also. Only on single doorways though.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/Minecolonies/minecolonies/issues/1549#issuecomment-341749991>,
or mute the thread

**Comment by Moobien** [comment]
Cool.
