### ISSUE TITLE
Hard crash.

### ISSUE THREAD

**Issue by LordSkittles** [ldtteam/minecolonies#1550]
### Minecolonies version

version 0.8.4279 or curse X.X.XX

### Expected behavior

- Not crashing.

### Actual behaviour

- Crashing.

### Steps to reproduce the problem

Not really sure how it happened, I was playing the default raid settings and then I changed it to a longer delay between raids (mind you I was in the middle of a raid) and then suddenly I can't go near my colony as the game keeps crashing.

[crash-2017-10-25_11.28.14-client.txt](https://github.com/Minecolonies/minecolonies/files/1412890/crash-2017-10-25_11.28.14-client.txt)

**Comment by LordSkittles** [comment]
Additional note. Changing back to the original setting of 3 fixes the issue. Could be that the entities are not notified of the config change.

**Comment by Asherslab** [comment]
Nah, that wouldn't be the error, it's in PermissionsView.hasPermission (I.E. nothing to do with barbarians, but a little confusing....)

just as a side note for future reference most devs don't like downloading files and would instead prefer you put the crash in a gist or pastebin (https://gist.github.com)

**Comment by marchermans** [comment]
@Raycoms I thought you fixed this?

**Comment by Raycoms** [comment]
I thought as well, is this the newest version?

**Comment by LordSkittles** [comment]
Yes, this is the latest version on Curse

**Comment by Raycoms** [comment]
Latest alpha? Which Minecraft version?

**Comment by LordSkittles** [comment]
Latest 1.10 version

**Comment by Raycoms** [comment]
Wow that's getting really strange now...

**Comment by LordSkittles** [comment]
I do have Better FPS installed. Would you like a full mod list? potential conflict causing the issue?

**Comment by LordSkittles** [comment]
Strangely enough, I can't seem to reproduce the issue

**Comment by LordSkittles** [comment]
Also @Asherslab Maybe it's just mod devs as I am a game developer and we prefer the actual log straight up :P

**Comment by Asherslab** [comment]
i guess so, i've always gotten backlash from any dev when giving them a .txt instead of a gist/pastebin/etc but i mostly interact with mod/sponge devs, so that could be the case 😛

**Comment by LordSkittles** [comment]
The issue happened again and I don't know why haha

**Comment by Asherslab** [comment]
it seems to be permissions again. not sure why either @Raycoms is/will be working on it 😄

**Comment by Raycoms** [comment]
Can you please test it with this version: https://minecraft.curseforge.com/projects/minecolonies/files/2493137

And see if you can reproduce it?
