### ISSUE TITLE
Citizen dont spawn

### ISSUE THREAD

**Issue by Sonsia** [ldtteam/minecolonies#1551]
### Minecolonies version

version 1.12.1-08.4075

### Expected behavior

spawn citizens

### Actual behaviour

no citizens when i start a colony

### Steps to reproduce the problem

i started a colony citizen spawned. i wanted to start over killed the citizen destroyed the building and deleted my colony with the command delete. i started over with a town hall but no citizen spawned,

**Comment by Raycoms** [comment]
Uhm, how much time did you wait? Sometimes they need a bit, and sometimes if there are too many blocks around the townhall they don't have space to spawn

**Comment by Sonsia** [comment]
I deleted the townhall completely to restart so the blocks shouldn't be a
problem. I'll see tonight if they respawned if the time is the problem.

**Comment by Raycoms** [comment]
Great =D

2017-10-26 17:33 GMT+01:00 Sonsia <notifications@github.com>:

> I deleted the townhall completely to restart so the blocks shouldn't be a
> problem. I'll see tonight if they respawned if the time is the problem.
>

**Comment by Sonsia** [comment]
Thank you i found the problem. someone had stopped the time on the server.

**Comment by Raycoms** [comment]
Oh that's bad =)

**Comment by Sonsia** [comment]
It's ok...i made sure he won't be able to ever do that again...and they
will never find the body neither 😂
