### ISSUE TITLE
[suggestion] Crafters huts / or guys can craft what they need if the have raw materials

### ISSUE THREAD

**Issue by winsrp** [ldtteam/minecolonies#1557]
So how about a building and a colonist that crafts requested items from raw materials.

Most of the time there is a builder asking for stairs and slabs, when it has all the raw materials and even a crafting bench right next to him, so... can't he just craft them?, how about an axe or a pickaxe that gets requested every single time.. ?

On the first idea, if the colonist needs something, the delivery guy will get all the recipe components from the storage, if the component is not on the warehouse, but that component has a recipe, it will get those items too, to the crafter, then item gets crafted, and it gets delivered to the colonist needing the item.

On the second idea, the hut needs to be at level 2, and if the intelligence of the colonist is 1, he just request the item, if intelligence is 2, then it will request either the item or the components to the recipe, if intelligence is level 3 it will request up to 2 levels below on the recipe, for example if he needs a shovel, he will request as option 1... the shovel, option 2, sticks and cobble, or option 3, planks, and cobble (so he will also craft sticks, and then use them for the shovel), if intelligence is 4 it goes 4 levels back into the recipe... and you get the idea.

This will ease up on the automation part of the colony, where most raw materials will be enough for the most basic stuffs once you have your colonist workflow up and going.

**Comment by Nachtflame** [comment]
They have plans for this. If you check over on 'Pull Requests' up top, you can see some of what's being worked on. This is listed there. :-)

**Comment by winsrp** [comment]
uhhh cool.

**Comment by Raycoms** [comment]
Yep we have quite some issues for that =)
