### ISSUE TITLE
Please help me. Builder need tape?! HOW craft the tape? Thanks

### ISSUE THREAD

**Issue by Kniga47** [ldtteam/minecolonies#1559]
![2017-10-29_00 30 44](https://user-images.githubusercontent.com/33187571/32139263-fe0fcb56-bc43-11e7-8c3c-23c269aa501b.png)
### Expected behavior

Finished citizen hut level 2

### Actual behaviour
Stay and wait for tape?!

### Steps to reproduce the problem

1. Fire Builder
2. Cancel upgrade citizen hut

**Comment by Raycoms** [comment]
Yes that's unfortunately in the schematic, just craft the tape and give it
to him.

2017-10-28 23:57 GMT+01:00 Kniga47 <notifications@github.com>:

**Comment by Kniga47** [comment]
Craft tape? how?!

**Comment by Kniga47** [comment]
None recipe on web minecolonies :(

**Comment by Raycoms** [comment]
I think it was 2 sticks on each side and yellow wool in the middle

2017-10-29 0:04 GMT+01:00 Kniga47 <notifications@github.com>:

**Comment by Kniga47** [comment]
No :( I test all combination with stick (two, four, six) and wool (yellow, white, one, three)... not working for me :(

**Comment by Asherslab** [comment]
if you get JEI (Just Enough Items) and you search for Tape and click on the item it will give you a recipe for it.

**Comment by Kniga47** [comment]
ok.. I will get JEI :(
