### ISSUE TITLE
New Supplyship recipe

### ISSUE THREAD

**Issue by bob0bob** [ldtteam/minecolonies#1560]
Could you allow someone to make a supply ship out of any wood.  Not force them to oak.

**Comment by Raycoms** [comment]
That should be the case at least on 1.12

2017-10-29 1:16 GMT+01:00 bob0bob <notifications@github.com>:

**Comment by bob0bob** [comment]
I"m using 1.12.2 minecraft
mine colonies minecolonies-universal-1.12.2-0.8.4422.jar

**Comment by aylacullen** [comment]
On 1.12 as well, tried making it out of dark oak, no go.  Tried again with regular oak, worked fine.
