### ISSUE TITLE
wood issue

### ISSUE THREAD

**Issue by bob0bob** [ldtteam/minecolonies#1561]
add recipes to support alternate wood crafting for everything.   I'm in a birch forest, and basically you can't use mine colonies.  Everything has to be oak.  Builders.  Though of the wood planks not being oak, but the door has to be oak.   

I don't have oak by where I wanted to build.  

Please allow for recipes to use any kind of wood items and not limit it to oak.

Thank you.

**Comment by Raycoms** [comment]
We discussed this quite a few times already, our plan is to have 1 building style for each possible biome. But we're actually requiring the help of the colony for that one. WOuld just be too ugly if the builder would use any type of wood.
