### ISSUE TITLE
[Compatibility] Tinker bow / mattock support

### ISSUE THREAD

**Issue by Thyriel** [ldtteam/minecolonies#1562]
Hi,

would it be possible to implement support for Tinker construct mattocks (hoe) and bows/arrows (for guards)  ?

**Comment by marchermans** [comment]
@Asherslab I though we added Support for Tinker Tools in General.
If this is not the case, would you be able to take a look at this and make this more General, maybe even after the new RequestSystem is in with the Tool class.

**Comment by Raycoms** [comment]
@OrionDevelopment we didn't implement tinker bows yet because we would have to implement arrow handling for the guards (guards using up arrows). Additionally, I'm not sure if we should allow the use of those for the guards, our archers are already extremely powerful, if we'd let them use tinkers bows and arrows things might get out of hand.
The mattock support as a hoe makes sense though for the farmer (he needs hoe and ax) so we would need to write some compatibility code here.

**Comment by marchermans** [comment]
@Raycoms, personally I would add a balancing factor here, the higher Level the tool, the longer it takes for the guard to use it.

**Comment by Thyriel** [comment]
Maybe add an option (default disabled) to allow tinker bows then if it's too powerfull in normal environments ?
For example i use mods that make mobs much more powerfull (mutated mobs, zombie awareness, scaling health = mobs have levels and boss variants, boosts your hordes too but not guards) and under that environment the bow guards are definitly underpowered with vanilla bows.
But i would understand if it's too much work for special cases like that ^^

Mattock support would be really great. I deactivated / removed all vanilla tools in my modpack, but had to reimplement hoes now again just for the farmer so he can work.

**Comment by SeriousCreeper** [comment]
Just commenting that i'd also really love the mattock support! I have most vanilla items (and other hoes/axes) disabled and focus on the tinkers tools, so right now the farmer can't be used in my current pack.

**Comment by Haaxor1689** [comment]
Hi there, just dropping a comment here to ask if I should expect any progress with mattock being usable as hoe. It would be even nicer if mattock could be accepted as an axe and shovel as well. Thanks

**Comment by NachtRaveVL** [comment]
Can I throw in my support for this? Can I put in a bounty on this one?

Tinker Forge arrows don't work and that just makes having guards use regular bows completely outclassed by the ones who use tinker forge swords.

Also note, at least in minecolonies-1.12.2-0.9.127-ALPHA-universal.jar (part of current All The Mods 3), that tinker forge swords will equip but won't let the guard respond to orders to move unless they have a vanilla sword in their inventory.

**Comment by someaddons** [comment]
I just did an overhaul on the guards (does not include tinkers bows) but gave them more levelscalings/enchants working and configurability for dmg/hp, might want to check that out first.

**Comment by Raycoms** [comment]
I will check at the compatibility for the swords.

Am Fr., 26. Okt. 2018 um 09:29 Uhr schrieb someaddons <
notifications@github.com>:

**Comment by Raycoms** [comment]
Just tried, they work for me with tinker swords, just not tinker bows
(mainly because they're op)

Am Fr., 26. Okt. 2018 um 09:29 Uhr schrieb Ray Neiheiser <
ray.neiheiser@gmail.com>:

**Comment by someaddons** [comment]
ye if one added tinkers bows we'd scale their damage down to intended levels anyways :D use the new Health/damage config modifiers to adjust for modded mobs

**Comment by InterruptingOctopus** [comment]
im currently having problems with mattocks myself as im using tinker's hegemony which removes vanilla options so im in quite a pickle

**Comment by Raycoms** [comment]
Will be added to a new joint mod compat issue.

**Comment by Treya7** [comment]
Just want to add a little something to this even if it's closed but was wondering if there was ever a problem with colonists suddenly not able to use tinkers tools? I'm currently running into that problem now and wanted to know if someone else reported it as a bug.

**Comment by uecasm** [comment]
@Treya7 Please don't post to closed issues that are 6 or more years old.  Whatever it is you're experiencing is something different.  Ask about it on Discord first.
