### ISSUE TITLE
Miner did some weird things and then stopped doing anything

### ISSUE THREAD

**Issue by Thyriel** [ldtteam/minecolonies#1566]
### Minecolonies version

minecolonies-universal-1.12.2-0.8.4483
Forge 14.23.0.2512

### Actual behaviour

I think the script that controls my lvl2 miner did some weird things. At some point he started to build the mineshaft upwards, removed the ladder at the entrance and closed it with a cobblestone block.
See screenshot: https://imgur.com/wG6nedO

He then just stood at the blocked entrance and i was not able get him do anything (removed all items from his inventory, bumped him, etc.)

I fired him then and took another colonist as miner. This one started doing something, but all he did was mining the cobblestone that blocked the entrance and instantly replaced it with a new cobblestone (looped)

Finally i got it fixed by destroying the weird mineshaft he built on the surface, let the builder repair the building and then hiring another new colonist.

**Comment by Raycoms** [comment]
Yes this seems to happen when a creeper or anything similar destroys the miners ladder.
The miner depends on his ladder, if it gets destroyed, removed of anything he will have no reference and build upward.
