### ISSUE TITLE
[issue] Workers just going back and forth to their work huts and to the hall

### ISSUE THREAD

**Issue by winsrp** [ldtteam/minecolonies#1567]
### Minecolonies version

minecolonies-universal-1.12.2-0.8.4505.jar

### Expected behavior

- guys do work

### Actual behaviour

- miner gets to the entrance of the mine, and goes to the hall, and back again, same with lumberjack goes to a tree and back to the hall, they have tools and items, not missing anything... 

### Steps to reproduce the problem

1. build a colony to level 2 with the previews 1.12 version
2. upgrade to this new version
3. Profit (not really as they no longer do work)

**Comment by Raycoms** [comment]
Are there any hostile mobs around?

2017-10-30 18:44 GMT+00:00 winsrp <notifications@github.com>:

**Comment by winsrp** [comment]
nope... full daylight, no mobs

**Comment by winsrp** [comment]
the message on the lumberjack says chopping, but still going back and forth... same with the miner... ??

**Comment by Raycoms** [comment]
I will debug this later probably.
That's strange, I think my avoidance code is causing this and detecting
that the worker is stuck when he isn't.

2017-10-30 19:08 GMT+00:00 winsrp <notifications@github.com>:

**Comment by winsrp** [comment]
I also took everything from the miner to test it out, and he still goes back and forth, and says he is missing something, firing and hiring the same guy does nothing as well.

**Comment by Raycoms** [comment]
I think I know what the issues is.

2017-10-30 19:21 GMT+00:00 winsrp <notifications@github.com>:

**Comment by winsrp** [comment]
cool

**Comment by Raycoms** [comment]
Should be fixed now =)

**Comment by winsrp** [comment]
I'll give it a try

**Comment by winsrp** [comment]
seems to be working fine, thanks!
