### ISSUE TITLE
Level 2 citizen hut not working for 2 citizens

### ISSUE THREAD

**Issue by bob0bob** [ldtteam/minecolonies#1581]
### Expected behavior

I have a level 2 citizen hut.  I assign to 2 people to that hut. I did a wood hut.   after upgrade to level 2, there are 2 huts.  At night the citizens should go into the hut

### Actual behaviour

- at night the first citizen there goes into the hut that was built when it was level 1.   Then when the 2nd citizen shows up, they stand outside the door to the original hut.   They never go into the 2nd hut.  They just stand outside at night.  Until mobs show up and then run away.

### Steps to reproduce the problem
I've tried unassinging the citizen and reassigning them and they do the same thing.  They never go into the second hut that was built for level 2 wood hut.

**Comment by Raycoms** [comment]
This should be fixed in the newest alpha.
