### ISSUE TITLE
Incomplete Mesa Warehouse.

### ISSUE THREAD

**Issue by Moobien** [ldtteam/minecolonies#1586]
Flooring missing in Mesa warehouse blueprint.

Reference: https://github.com/Minecolonies/minecolonies/issues/1585

**Comment by Raycoms** [comment]
All building levels or only a certain one?

**Comment by Moobien** [comment]
Level 1 has no flooring.  I think level 2 and 3 has flooring. but 4 and 5 (when the entryway gets expanded) has no flooring in the extension.

**Comment by Raycoms** [comment]
Level 1 flooring is on purpose, but level 2+ should have, I will take a
look in my schematic world tomorrow.

2017-11-04 0:55 GMT+00:00 Moobien <notifications@github.com>:

**Comment by Moobien** [comment]
thats cool. I am loving the mod and I am happy to report any bugs I
encounter.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
