### ISSUE TITLE
Guard

### ISSUE THREAD

**Issue by bob0bob** [ldtteam/minecolonies#1591]
I've noticed that when a guard is guard based on a manual path.  That manual path gets obstructed by a tree or something.  The guard will just stand there and do nothing forever..  I'm mean EVER,   even to the point he dies.   I saw a spider come up on him and kill him.  He didn't fight back,  it appears he was more worried about not being able to get to his path spot.

It appears something in the code, that the path finding option has a higher priority then being attacked and fighting back.

**Comment by Raycoms** [comment]
That's part of this issue: https://github.com/Minecolonies/minecolonies/issues/1358

They shouldn't get stuck at all.
