### ISSUE TITLE
Bug Minecolonies Worker:Baker don't see furnances

### ISSUE THREAD

**Issue by Foxgreat** [ldtteam/minecolonies#1593]
Here's my walkthrough
MC 1.12.2
Forge 14.23.0.2503
Minecolonies 0.8.4565

I tried to baker see furnances in bakers house but he didn't see them.
Also i tried to recall him\replace furnances\repair house but it not worked.
https://youtu.be/9Eg0HWyXyZE

**Comment by Foxgreat** [comment]
![2](https://user-images.githubusercontent.com/29230185/32407747-915d40f0-c1b7-11e7-887c-1f2028c1109d.png)
![1](https://user-images.githubusercontent.com/29230185/32407748-91854e24-c1b7-11e7-9e00-0838b1f5457f.png)

**Comment by Raycoms** [comment]
Did you let the builder repair the hut yet?

**Comment by Foxgreat** [comment]
Updated to last one
got it, sorry. he repairs hut and it goes to work.

Furnances when you paste from gamemode and when it built by builder are different.

Also some minor bug - baker don't care where he works, i think its not normal)
![1](https://user-images.githubusercontent.com/29230185/32412656-938a0e14-c228-11e7-848d-c3f440dc7d76.png)

**Comment by Foxgreat** [comment]
Also after restart baker come insane and just walk around with bread in hand
![4](https://user-images.githubusercontent.com/29230185/32414892-2ca2a38c-c25a-11e7-9883-a41410cb0695.png)
