### ISSUE TITLE
Bug Minecolonies Worker:Postman can't see space on Bank

### ISSUE THREAD

**Issue by Foxgreat** [ldtteam/minecolonies#1594]
Here's my walkthrough
MC 1.12.2
Forge 14.23.0.2503
Minecolonies 0.8.4565

After i hired postman he always triyng to deliver things on bank but he sais that in bank no slots. Even if i configure places where he need to place.
https://youtu.be/uMGLWeN6_I4

**Comment by Foxgreat** [comment]
![2](https://user-images.githubusercontent.com/29230185/32407755-9b05c5a0-c1b7-11e7-985e-b7a28d0b89ce.png)
![1](https://user-images.githubusercontent.com/29230185/32407756-9b2e1762-c1b7-11e7-9f43-646395776411.png)

**Comment by Raycoms** [comment]
Can you please update to the newest minecolonies version and "repair" your warehouse?

**Comment by Asherslab** [comment]
sorry, what's this Bank thing?

**Comment by Raycoms** [comment]
He means the warehouse

**Comment by Foxgreat** [comment]
got updated Minecolonies

From creative paste it pastes chests.
After repair it replaces chests to Rack. In survival it goes normal.
About "Upgrade" feature, is it working on warehouse?

**Comment by Asherslab** [comment]
yes, you must have emerald/emerald block (Sorry forgot which)

**Comment by Foxgreat** [comment]
Here's come some trouble because i used Emerald block and it wont be upgraded on 1 or 5 tier.

I put emeralds on store\inventory\into storage itself and it wont give me to upgrade

![1](https://user-images.githubusercontent.com/29230185/32414811-11d83d56-c259-11e7-8af7-93347f0b4c72.png)
![2](https://user-images.githubusercontent.com/29230185/32414812-1205449a-c259-11e7-9b6d-5ecc0e06b18b.png)
![3](https://user-images.githubusercontent.com/29230185/32414813-122b320e-c259-11e7-9855-3ec345a21ac9.png)
