### ISSUE TITLE
Suggestion: Chance Mining Option [$25]

### ISSUE THREAD

**Issue by masternetra** [ldtteam/minecolonies#1595]
Currently as it stands the miner is useless in worlds lacking ores (such as sky islands/void worlds and the like) and personally I notice once the miner gets into tunnel making he/she eventually stops being very productive, running from side of the tunnel network to the other (wasting a lot of time) making him not as useful in the long term. So I purpose adding a chance mining thing (like in the millenaire mod) as a option, which could be enabled in config.

When enabled, the miner instead of breaking blocks could just stand at the ladder entrance or around the mining pit (top side) and perform his/her mining animation and randomly obtain materials, who's chances and availability would of course be based on the mining hut's level. 

Additionally, another config area could be added for ores and materials from other mods where you could either directly define the miner hut level chances/availability and/or define the chances/availability by tying it to a existing vanilla material/ore.

**Comment by Raycoms** [comment]
That's definitely possible, but, unfortunately, due to limited manpower we have to put that quite far behind in the "TODO-List"

**Comment by Wissi** [comment]
I agree as it's a GREAT "option" we've discussed in the past. 
I really hope it will eventually get coded from the "TODO-List". So if more coders w/experience lend their time and expertise we can get all this done faster.
It is a great way to save world resources as well as other gameplay types like: space/void/sky, etc etc.

Placing a "Bounty" on it will most likely make it get coded much faster  ;-)

<a href="https://www.bountysource.com/issues/51166378-suggestion-chance-mining-option?utm_source=51166378&utm_medium=shield&utm_campaign=ISSUE_BADGE"><img src="https://api.bountysource.com/badge/issue?issue_id=51166378" /></a>

**Comment by Raycoms** [comment]
Done
