### ISSUE TITLE
Yet more bugs/suggestions (sorry guys)

### ISSUE THREAD

**Issue by Moobien** [ldtteam/minecolonies#1596]
### Minecolonies version

version 0.8.4564 - MC 1.11.2 

More possible bugs/suggestions.

1) With this version I am noticing I have to rehire my guards at my barracks almost daily. 

2) With regards to the colonist death update, something to further help players is to know WHAT job they had, that way if say your dman dies you don't have to check every building to see what job that killed colonist was doing.

3) Speaking of the Dman, how feasable would it be to make a priorities list for the dman.  i.e. say have 1 dman set to prioritize delivering requested resources, another collecting from production buildings, one delivering food to the homes.  Obviously I don't mean that its set so the dman ONLY does that job, moreso that that job takes priority.

4) I am noticing the dman is taking food I put into my towers for my guards so they are left with none. This includes the barracks towers.

5) I made you guys an armory, took me a few hours of construction to do 5 levels and it looks pretty crap. I was thinking that you could have it so the guards/dman checks the armory for appropriate level gear for the guards to use when requested. the 2 zip files I am linking are for the .nbt scans I made and the actual world so you can have a look, have a play and tell me I suck at building.  If you do like what I have made and decide to use it or adapt it, please feel free to do so.

The armory has 8 double chests initially, with the idea that each chest holds 1 type of gear. 1 for helmets, 1 for chestplates.  The gold blocks I used as placeholders for scan points and the building block. couple of nice little surprises for the lvl 4 and 5 upgrades.

NBT Zip: https://www.dropbox.com/s/cux9gxcpkpiqeum/mc-armory.zip?dl=0
World Zip: https://www.dropbox.com/s/wm5ncqvlja20a81/New%20World.zip?dl=0

**Comment by Moobien** [comment]
6) colonists spawned by the barracks towers shouldnt appear in hire list for non barracks buildings. (I keep hiring guards for normal jobs and they then complain they are hungry because they have no 'home' to get food from)

7) all of a sudden today I can access the farm gui.

**Comment by Moobien** [comment]
To further 7, my farmers seem to now just stay home instead of going to work

**Comment by Raycoms** [comment]
3-5 will be fixed soon, do you have logs for1+7?

**Comment by Moobien** [comment]
1 seems to have sorted itself out. How do i get logs for 7 for you?

**Comment by Asherslab** [comment]
in your Minecraft dir find the fml-latest.log plz
and put the text inside a gist (http://gist.github.com/)

**Comment by Moobien** [comment]
ok. done.  I went to all 3 of the farmer's blocks in my world and tried to activate them and then quit the game.

https://gist.github.com/Moobien/daaaf3d9504f99c2128dba4b4d415682

**Comment by Moobien** [comment]
no idea why it closed when I commented....

**Comment by Moobien** [comment]
I just tried something. Had a new farm built and was able to interact with the farm block with no issues. So its the 3 i had built BEFORE the update that stopped existing as farms

**Comment by Moobien** [comment]
Update. New farm broke at/during the lvl 3 upgrade

**Comment by Moobien** [comment]
Farmer seems to still be planting/harvesting though...

**Comment by Moobien** [comment]
Ok I think bug 1 may have resurfaced but in an odd manner.

I fired all guards from the barracks. set game time to midnight to send all colonists home.
I then reassigned any that did not have a home to the barracks (4 of them)
I upgraded a citizens hut.
When the new colonist spawned one of the guards at the barracks seemed to have been fired AND the new housing slot assigned to one of the barracks guards instead of the newly spawned colonist.

I rebuilt all my farms on top of the old ones and they all seem to be functioning.
Here is the latest fml-client-latest log for you guys.

https://gist.github.com/Moobien/6b6b1f3a394547b085ed54bdfe183940

**Comment by Moobien** [comment]
hmmmmmm after fully exiting minecraft yesterday and shutting my pc down, today all my farms are uninteractable again.

**Comment by bob0bob** [comment]
Here is my log also where I'm trying to access the farm gui and it is not working.  Also, like Moobien said,  the farm people are not working anymore.   Half the time they just stay in their huts.

This version of minecolonies, has a HUGE bug with farm gui.  They stop working after a day or two in minecraft.


[latest.log](https://github.com/Minecolonies/minecolonies/files/1459972/latest.log)

**Comment by bob0bob** [comment]
I got it., farm not working on right click.    At least in my world, this is what I do.    I build a farm..    Then build a field.  Assign a citizen to the farm and assign them a field.  Once they start working for a bit.  "Quit" (normal shutdown), and then reload it.  The right click stops after the save and quit.  When it reloads it is not functional anymore.

**Comment by marchermans** [comment]
Hmm seems like an error while saving the field data

**Comment by marchermans** [comment]
So I checked this, and this is a bug between Colony and Entity, they have different instances, after a reload, of the Field, while one is making changes (say update the state) the other does not see those, causing a miss sync.

We might be able to fix those by moving the loading and saving calls around? @Raycoms
