### ISSUE TITLE
Console "sound does not exist" warns from minecolonies

### ISSUE THREAD

**Issue by Foxgreat** [ldtteam/minecolonies#1597]
MC couldn load some sounds in loading can you check them?

Logs
[main/WARN]: File minecolonies:sounds/mob/deliveryman/female/inhaleexhale1.ogg does not exist, cannot add it to event minecolonies:mob.deliveryman.female.noise
[main/WARN]: File minecolonies:sounds/mob/builder/female/whatisit.ogg does not exist, cannot add it to event minecolonies:mob.builder.female.interaction
[main/WARN]: Missing sound for event: minecolonies:mob.guard.archer.female.badhousing
[main/INFO]: SoundSystem shutting down...

**Comment by Raycoms** [comment]
Which minecolonies version?

**Comment by Foxgreat** [comment]
@Raycoms minecolonies-universal-1.12.2-0.8.4596.jar

**Comment by PhoenixRiver** [comment]
Still got one warning with minecolonies-universal-1.12.2-0.8.4932

[main/WARN]: File minecolonies:sounds/mob/deliveryman/female/inhaleexhale1.ogg does not exist, cannot add it to event minecolonies:mob.deliveryman.female.noise
