### ISSUE TITLE
lumberjack stuck doing nothing.

### ISSUE THREAD

**Issue by bob0bob** [ldtteam/minecolonies#1600]
minecolonies-universal-1.12.2-0.8.4596.jar

sometime the lumberjack will get stuck standing there.  not meaning blocked.   He wants a sapling.  He has none and he will stand there until night.  Problem. there might not be any but he is standing around 20+ trees that are on his list to chop down.  For example, I have him chopping oak but he has not oat sapling and he will not chop tree even though there might be 20+ around him.   
There should be something to skip that step

**Comment by Raycoms** [comment]
That's strange, is there a way to reproduce this in a new world?

**Comment by Foxgreat** [comment]
@Raycoms i had same problem, it goes unstucked at some time went. It askes for supplings that he dont have and some times have.

**Comment by Kzorith** [comment]
I have a similar problem with my lumberjack in "The Simple Life 2" modpack (MineColonies 1.10.2-0.8.4063) where my lumberjack will cut down Tinker's Construct slime trees, and ignore the rest of the forest I have growing around them.  All the trees in that area are in the work list, but for some reason, the lumberjack is not inclined to chop any of them down.  At times, the lumberjack will stand at their station and not do anything until night comes.  At other times, the lumberjack doesn't even leave the Citizen Hut they live in.

**Comment by Raycoms** [comment]
I think I have to play 1.12.2 a bit to find those things out.

**Comment by bob0bob** [comment]
I've kind of figured out that you have to make the changes to what they can do and then recall him.  That appeared to work for me.  Because when I started, I told him to do oak only.  then I went in an added other woods but he kept just doing oat.  I even went in and turned everything off and he still did oak.   Once I did recall worker, it started working again.

I've noticed that in this mods, citizens are stuck doing what is in these task and nothing can break that.  It appears that they do not get an event update on changes.

**Comment by Wissi** [comment]
yeah, when that happens, to kind of "reset" them on stuck processes or after a change, just "Fire/Hire" them and that will usually do the trick.

**Comment by PhoenixRiver** [comment]
I have tried resetting the builder once after the build order changed but never again - crash bug. Now I just get her to finish what she is currently doing and then she moves onto the new order.

**Comment by scraw-darkblade** [comment]
minecolonies-1.12.2-0.10.68

Encountered a problem where lumberjack just standing and not doing anything.

Equipped with stone axe
Work level 1 @ lumberjack hut level 1 

A way to reproduce the problem is to at least plant oak wood one space apart (oak)(space)(oak)

I think it's about pathing . I manage to make him work again by chopping all tree that are compressed noticed that LJ is after other tree.
