### ISSUE TITLE
Website popup "Pvp Event thing" keeps popping up EVERYWHERE.

### ISSUE THREAD

**Issue by masternetra** [ldtteam/minecolonies#1601]
Sorry, didn't know where else to put this, The popup on the website talking about some PVP event thing keeps popping up everytime I go to a different page on the site. It's annoying as hell, please don't do those, I mostly avoid the website because of it.

**Comment by Raycoms** [comment]
@OrionDevelopment  can you take a look at that?

**Comment by masternetra** [comment]
Here is a screenshot of it; if it helps anything: https://postimg.org/image/4tju4ea4vv/
Really should do announcements as a small banner at/near the top of the page if it's that important to warrant a sitewide announcement. Popup's are just annoying.

**Comment by marchermans** [comment]
No actually I can not, I have no acces to the website servers.

**Comment by Raycoms** [comment]
@masternetra do you have an idea where I can turn that off within enjin?

**Comment by Raycoms** [comment]
Fixed it!
