### ISSUE TITLE
Cancelling builds

### ISSUE THREAD

**Issue by bob0bob** [ldtteam/minecolonies#1605]
minecolonies-universal-1.12.2-0.8.4596.jar

If you have a request to build or upgrade something and then you delete it because you want to to do something else.  They are stuck and will not do that.  I have two pictures that show what the builder is requesting and second picture shows the work order.

When you delete a work order,  it appears that the builder doesn't get updated until they are completed.  Once you start a build, you have to complete it no matter what.

![2017-11-08_23 37 31](https://user-images.githubusercontent.com/30982580/32590112-3b31b1c8-c4de-11e7-9713-39b47dc80379.png)
![2017-11-08_23 37 47](https://user-images.githubusercontent.com/30982580/32590113-3b43defc-c4de-11e7-9355-9af49ed6048d.png)

**Comment by Wissi** [comment]
Yeah, that's been a kind of a bug that we know of and will get fixed.
For now the solution is to "fire/hire" the builder to kind of "reset" him and current deleted W/O will be removed from his queue.

**Comment by Raycoms** [comment]
this will be fixed with the newest request system. so I'll close this for now.

**Comment by bob0bob** [comment]
Actually,  when I slept.  The next day it cleared itself.   i did nothing about fire/hire.  The system must redo on the new day what they are suppose to do and saw it was nothing.
