### ISSUE TITLE
farmer level 2 building

### ISSUE THREAD

**Issue by bob0bob** [ldtteam/minecolonies#1606]
minecolonies-universal-1.12.2-0.8.4596.jar\

When I started up my colony today, I couldn't right click on the farmers chest.  Nothing happened.  No matter what I did.   I had to destroy it and start over from level 1.

**Comment by bob0bob** [comment]
I deleted the farm box but I forgot to fire the worker.   So now I have a worker that thinks they are a farmer and assigned to a farm that doesn't exist.  Is there a way to reassign this person?   I can't remove his job as the box is gone.

Thanks,

**Comment by bob0bob** [comment]
Ok. It built the farm over and it started doing it again.  Right click on it and nothing happens.  the farm appears to be really broken.  It worked for a bit when I rebuilted it but then it stopped.

![2017-11-09_00 39 26](https://user-images.githubusercontent.com/30982580/32591795-825d3920-c4e6-11e7-9a90-eeaee84b8f5c.png)

**Comment by bob0bob** [comment]
now I have 2 farmers that I can't access.  as this chest is not "right clickable" and the previous is gone but I still show 2 farmers for the town but one is assigned to a farm that is gone.  There is no code in the system to remove the farmer from that assignment when the block is destroyed.  Hoping there is a solution for the right click, so I don't have to destroy it and start over again.

Thanks.

**Comment by Wissi** [comment]
I assume you're playing in SSP not on a server? What version are you using (1.10, 1.11 or 1.12) and is it the latest?
If so then give yourself  /op   
And then run:
/mc colony info     ( to get ur Colony ID: ? )(has to be ID:1   in SSP)
then:
/mc colony refresh <colony ID#>      ( to see if that fixes the issue of not recognizing the farmer Hut GUI)
/as for the Citizen that is employed under a non existent farm, fire your current farmer and see if you can "hire" the previous one, if not you might have to "kill" him. either w/sword, or with command in game:
/mc citizens kill <colony ID#><citzen ID#>
(to get Citizen ID do:  /mc citizens list <colony ID#> )

**Comment by bob0bob** [comment]
No, I'm playing on a server.  minecraft and minecolony version number is above but here it is again.
Mine craft 1.12.2
Mine colonies 0.8.4596

I will try the refresh colony tonight.   and see if the current farm that is not working, starts working.  
I ended up killing the old citizen from the old farm from the command line.

But there should be something in the code when the work block a citizen is assigned to is destroyed, it should clear their assignment.  We shouldn't have to kill them to clear it.

I will update tonight after do these things with the results.  

Keep up the good work.

**Comment by bob0bob** [comment]
I tried the colony commands  info and refresh and no change on the farm.  


![2017-11-09_20 04 32](https://user-images.githubusercontent.com/30982580/32639389-5722f148-c589-11e7-82fb-06ff045985c9.png)

**Comment by bob0bob** [comment]
a picture of me doing a right click 
![2017-11-09_20 06 02_2](https://user-images.githubusercontent.com/30982580/32639421-7f8b5350-c589-11e7-985c-b7d43a9323da.png)

**Comment by bob0bob** [comment]
[latest.log](https://github.com/Minecolonies/minecolonies/files/1459974/latest.log)


Here is by log when I logged on and tried to right click the farm gui and also did the /mc command to try and refresh.  It is related to the version,  that is about the time it started.

**Comment by Wissi** [comment]
Well the log had no helpful info. 
On the server are there mods/plugins that might be interfering?
Try in SSP to see if it is a Server side issue, please.
If so, then we might be able to help you troubleshooting your server?

**Comment by bob0bob** [comment]
I created a SSP game and them copied over the world data and loaded it up.  But still no difference.  I tried the commands, but now it says I don't have permission.

**Comment by bob0bob** [comment]
I installed minecolonies ,  I had to destroy the farm and kill the citizen because the right click stopped.  Then a built a new farm.
minecraft 1.12.2
mine colonies 0.8.4701

And after the second day,  the right click stopped working again.

**Comment by bob0bob** [comment]
I got it.     At least in my world, this is what I do.    I build a farm..    Then build a field.  Assign a citizen to the farm and assign them a field.  Once they start working for a bit.  "Quit" (normal shutdown), and then reload it.  The right click stops after the save and quit.  When it reloads it is not functional anymore.

**Comment by polikarpov5** [comment]
me too, 
I installed minecolonies-universal-1.12.2-0.8.4701.jar and update to minecolonies-universal-1.12.2-0.8.4701.jar, the farm is sandstone
46/5000
the farmer says: 

_let me sleep_

 even during the day

**Comment by Schadrach** [comment]
I'm having a similar problem.  Running All the Mods 3 pack.

The farm block in a farm occasionally becomes inaccessible, farmer eventually gets full and complains about not having room to deliver into.  Can't seem to fix it but to break the farm block and rebuild the farm, then break and replace all the fields.

Only farms seem to do this.  Another user having the same problem, mine is stone hers is wood.

**Comment by bob0bob** [comment]
From what I found it is related to the Save/Load procedures.  Not sure which one is the issue but either the save or the load is messing up the farm.

**Comment by Raycoms** [comment]
We have a fix ready just needs to be merged to 1.12 and 1.10

**Comment by bob0bob** [comment]
Thanks.

**Comment by polikarpov5** [comment]
I updated to 1.12.2-0.0.2832, I still have the same problem.

**Comment by Raycoms** [comment]
With new farmers?

**Comment by Raycoms** [comment]
And new fields?

**Comment by bob0bob** [comment]
Farm box is working for me.  but there are still issues with farming altogether.   Not all fields show up.  I have 5 fields,  it usually only shows 4 fields.  The 5 field it doesn't show is not the furthest away.   The farming is set to manual and I assign him to 2 farms.  if you right click on the field, it shows assigned to "NO ONE",  and some do not even show anything at the top like it is not seen.

I've destroyed all the fields and redid them but it is the same.   But Don't know if you break the field, the NBT data is still related to that and  I've not tried making new fields and placing those yet.
