### ISSUE TITLE
Guard inventories fill with barbarian weapons until they can't eat!

### ISSUE THREAD

**Issue by MattBeard** [ldtteam/minecolonies#1607]
### Minecolonies version

version 1.12.2-0.8.4596 or curse 7.5.6515.471

### Expected behavior

- Excess weapons picked up by a guard are dumped in tower chest and taken by deliveryman to warehouse. Perhaps allow a guard to carry a maximum of 4 swords and 4 bows at a time, also for perhaps 4 of each to be in the tower chest without being collected by deliveryman.

### Actual behaviour

- Guard inventory fills up with swords from barbarian battles and when the guard is hungry they can not eat as a free slot is required to take food from the chest. Result is that they wait by the chest with max hunger even when the chest contains food

### Steps to reproduce the problem

1. Make a guard
2. Wait for lots of barbarians
3. Wait for guard to stand by chest
4. Check guard inventory and see it is full of swords (and/or bows)
5. Remove a weapon and watch the guard eat then return to duty

**Comment by Raycoms** [comment]
Fixed
