### ISSUE TITLE
[Feature Request] Multi-packet buildings to expand max building size

### ISSUE THREAD

**Issue by Flabort** [ldtteam/minecolonies#1610]
In discord it was said that the maximum building size is set by the maximum size of a packet you can send through forge. Would it be possible to detect if a scanned building was larger than the maximum packet size, and if so, divide the scan automatically into smaller sections, then piece them together automatically when you build the schematic? Send them one after the other so the preview of the schematic loads in pieces?

Of course, this is a very low priority suggestion AFAIK,

**Comment by Asherslab** [comment]
It's certainly doable in some sort of way. But as said this would be quite a time in the future. I put it up for discussion, i'm interested as to what the other guys might have to say about it. 

@Raycoms @OrionDevelopment @Kostronor What're you're thought? Possible, Hard, Easy, Best way to do it?

**Comment by marchermans** [comment]
This is actually relatively simple :D Implementing this would take something like 30 minutes or so XD
Let me check our code.

**Comment by Asherslab** [comment]
Awesome! I was expecting it to be a lot more difficult, i really should look into the forge / other network packaging we do, lol

**Comment by Raycoms** [comment]
Actually as I remember it, the problem was that there is a multi package
functionality which simply has a bug in 1.10 forge.

**Comment by marchermans** [comment]
No idea
But is simple to fix from our side.

**Comment by Raycoms** [comment]
OKay, nice

2017-11-11 11:07 GMT+00:00 Marc Hermans <notifications@github.com>:
