### ISSUE TITLE
Crashing upon placing town hall chest

### ISSUE THREAD

**Issue by Anostraca** [ldtteam/minecolonies#1615]
Minecolonies ver. universal-1.12.2-0.8.4701
MC ver. 1.12.2
Forge ver. 1.12.2 - 14.23.0.2540

Whenever I place townhall chest client crashes, server looks OK. First try with various mods, crash log from plain forge + mcolonies. Same for singleplayer.
Tried even stable version of mcolonies same crash.

https://pastebin.com/cvtpAgnk

**Comment by Raycoms** [comment]
Please try with forge: 14.23.0.2493

Until we fixed this.

**Comment by Anostraca** [comment]
Didn't expect so fast respond, anyway I'll wait for fix, because most of the most i try to play with need 2507+ so keep doing the great work and I'm looking forward to next build :)

**Comment by Raycoms** [comment]
try this one please: https://s3.eu-central-1.amazonaws.com/minecolonies/Minecolonies/Minecolonies_Branches/4847/minecolonies-universal-1.12.2-0.8.4847.jar

**Comment by Anostraca** [comment]
Tested with single, multiplayer and with other mods. Looks like it works like a charm :)

**Comment by mvdhoning** [comment]
can this be reopened for:
minecolonies-universal-1.12.2-0.8.4932
MC ver. 1.12.2
Forge ver. 1.12.2 - 14.23.1.2555

Updated to a newer forge for forestry and binnies and the same situaties as here occurs

**Comment by HashBrownOO7** [comment]
Where do you get that jar file @Raycoms

**Comment by NorAnnie** [comment]
Hey, i have the same problem, but i don't know what version is 14.23.0.2493. I tried opening minecraft and going to launch options, and change there, but it only shows version 1.0 above 14.23.0.2493... what do i do?   the link above didn't work :(

**Comment by TheWolf320** [comment]
@NorAnnie go to this and wait about 5 second up the right a skip button will appear and it will download forge 14.23.0.2493 and install it and go to your launch options and set the version to 14.23.0.2493 hope it helps http://adfoc.us/serve/?id=27122865519691
