### ISSUE TITLE
Bakery dont work / Forge cant plant

### ISSUE THREAD

**Issue by Haraldson85** [ldtteam/minecolonies#1617]
### Minecolonies version

minecolonies-universal-1.12.1-0.8.4075

### Expected behavior

Build a Bakery, give the Baker Wheat and he´s making Bred.

Build a Forge and there is a Smith with making Tools/Weapons

### Actual behaviour

When i build a Bakery and place a Worker there, he wont start to work. He´s running between Crafting Table and Furnace without doing something. When i give him Wheat he wont start to work. When i place Wheat in the Crafting Table nothing happend.

Cant build a Forge, just can place the Block but when i rightklich at him nothing happens.
### Steps to reproduce the problem

1. Build a Bakery and test the Bug with Lvl 1-5
2. Try to build a Forge

**Comment by Justen-N** [comment]
Forge has not been reimplemented in anticipation  of crafting changes.

TRY having the builder repair the bakers hut.

**Comment by Raycoms** [comment]
Can you reproduce this somehow?

2017-11-13 23:40 GMT+00:00 Justen Neeley <notifications@github.com>:

> Forge has not been reimplemented in anticipation of crafting changes.
>
> TRY having the builder repair the bakers hut.
>

**Comment by Haraldson85** [comment]
Yeah i try to repair but this wont help. I also try to upgrade from Level 1 - 5 and test every Stage but this Bug is in every Level. Sometimes the Baker also stands on the Chest and punch the Chest. I thinking he stucks in the Script. Maybe ther is a incompatibility with a other mod like Pams Harvestcraft because it changes the recipe of bread?

**Comment by Justen-N** [comment]
Pam's shouldn't do it. Maybe send a mod list and

**Comment by Justen-N** [comment]
Sorry, one year old pressed enter. Is the area beneath your bakery solid? at least one layer deep?

**Comment by Raycoms** [comment]
@Haraldson85 he doesn't actually craft, he just takes the items and makes bread of it. In 1.10 it works well even with Pams.

Can you reproduce this from a clean world somehow?

**Comment by Haraldson85** [comment]
Is the area beneath your bakery solid? at least one layer deep? Yes it is, testet it with Dirt and cobblestone 4 Layers down

Can you reproduce this from a clean world somehow? Yes i testet it in Singleplayer with a new World. I build following: Builders Hut Lvl 1, Townhall Lvl 1, Bakery Lvl 1

Here a Video (New World) to showing the Bug: https://www.youtube.com/watch?v=PqGbrNupdaY&feature=youtu.be

I play on Minecraft 1.12.2 with Forge 14.23.0.2512

So here a Modlist:

AdvancedRocketry-1.12.2-1.2.3
AppleCore-mc1.12.2-2.2.2
Aroma1997Core-1.12.2-1.3.0.2
Aroma1997s-Dimensional-World-1.12.2-2.0.0.2.b61
backpacks 1.12.2 - 3.4.0
bdlib-1.14.3.10-mc1.12.2
BetterFps-1.4.8
BetterTitleScreen-1.12.2-1.4b
ChickenChunks-1.12-2.4.0.70-universal
CodeChickenLib-1.12-3.1.3.313-universal
CoFHCore-1.12-4.3.6.14-universal
CoFHWorld-1.12-1.0.1.8-universal
CompactSolars-1.12.2-5.0.17.340-universal
CraftTweaker2-1.12-4.0.9
Decocraft-2.5.2_1.12.2
FarmingForBlockheads_1.12-3.1.5
FastLeafDecay-v14
fencejumper-1.12-1.0.1
forestry_1.12.2-5.7.0.210
FullscreenWindowed-1.12-1.6.0
generators-0.9.20.9-mc1.12.2
Hwyla-1.8.22-B37_1.12
industrialcraft-2-2.8.16-ex112
InventoryTweaks-1.63
IronBackpacks-1.12.2-3.0.0
ironchest-1.12.2-7.0.34.820
jehc-1.12-1.3.1
jei_1.12.2-4.8.0.111
jeibees-0.9.0.5-mc1.12.2
journeymap-1.12.2-5.5.2
justenoughbuttons-1.12-1.2.1
JustEnoughResources-1.12.2-0.8.5.27
LibVulpes-1.12.2-0.2.6-universal
minecolonies-universal-1.12.2-0.8.4775
Morpheus-1.12-3.3.2
MTLib-3.0.1
NotEnoughItems-1.12-2.4.0.231-universal
NuclearCraft-2.5a--1.12.2
Ore Tweaker-1.0.2-1.12.0
Pam's HarvestCraft 1.12.2a
RedstoneFlux-1.12-2.0.1.2-universal
RoguelikeDungeons-1.12.2-1.8.0
TreeChopper-1.12.2-1.2.4
WailaHarvestability-mc1.12-1.1.12
Wawla-1.12.2-2.5.246
WorldEdit CUI Forge Edition 2-2.1.2-mf-1.12.2-14.23.0.2487
worldedit-forge-mc1.12-6.1.8-dist

**Comment by Haraldson85** [comment]
Ps: Maybe you can implement a funktion so i can there wheres the entress of the Building so i can plan a nice city(make all Entress at the same side). Or something like a Preshow of the Building when i try to place it?

**Comment by Raycoms** [comment]
Does the log show anything strange?

2017-11-15 11:08 GMT+00:00 Haraldson85 <notifications@github.com>:

**Comment by Haraldson85** [comment]
here the latest Log:

https://pastebin.com/f17NCBpg

**Comment by Justen-N** [comment]
The build tool has the functionality you suggested. As to your other issue,
I am uncertain what is going on.

**Comment by Haraldson85** [comment]
I am uncertain what is going on. Okay :-)

Maybe you find the issue . . . have testet it in a existing world, a new world, with lvl 1-5 bakery and so i can reproduce the issue. Maybe there is some mod incompatible. Have you seen the video?

**Comment by Haraldson85** [comment]
Sry had the wrong Settings on Video, now you should seen it: https://www.youtube.com/edit?o=U&feature=vm&video_id=PqGbrNupdaY

**Comment by Raycoms** [comment]
That one links me to my own videos.

2017-11-15 15:52 GMT+00:00 Haraldson85 <notifications@github.com>:

**Comment by Haraldson85** [comment]
Try this one: https://www.youtube.com/watch?v=PqGbrNupdaY

**Comment by Raycoms** [comment]
No I'm really confused because this means he is working correctly, he hits his chest with the wheat until he got flour, then he puts the dough in the furnace and waits a bit to retrieve it.
At initial levels he needs a bit of hitting until he is ready.

**Comment by Haraldson85** [comment]
Strange now iam confused. Let him work for 10min . . . you got right it takes a little bit BUT he´s only making 3 Breads after this he´s running between forge and chest and nothing happend. Maybe i can make a video later when iam coming home. So now the Problem is he stops after making 3 Breads . . .

**Comment by Raycoms** [comment]
At the start he is slow, but after a while he will get going more fast

2017-11-15 16:31 GMT+00:00 Haraldson85 <notifications@github.com>:

**Comment by Enverex** [comment]
The baker used to work fine for me, but now I'm seeing the same issue with the baker as was originally reported here. Originally the baker worked fine, he'd smack the chest for a while, go bake and then end up with bread.

He's level 4 now and the bakery is level 3, but all he's doing is running between the chest and the furnace, not actually accompanying anything. Inventory wise, there's 17 wheat in his inventory and 41 wheat in the chest. Nothing else.

**Comment by Raycoms** [comment]
Did you try fire/rehire and repair?

2017-11-30 22:06 GMT+00:00 Benjamin Hodgetts <notifications@github.com>:

**Comment by Enverex** [comment]
Repair completed without appearing to have done anything. Fire then rehiring hasn't helped. Baker is still just running back and forth without doing anything.

**Comment by Raycoms** [comment]
Is there a way to reproduce this to get them to this stage?

2017-12-01 1:15 GMT+00:00 Benjamin Hodgetts <notifications@github.com>:

**Comment by Enverex** [comment]
Not sure really. I'm using the All the Mods 3 pack and the baker was originally fine. It only started happening some time after the baker building was upgraded the second time.

**Comment by Enverex** [comment]
Restarted the server and it seems to be ok now. I have a feeling the baker had some phantom dough in their inventory or something.

**Comment by rnlewis** [comment]
I know this is from a couple months ago, but I just had the same problem tonight and I broke and replaced the furnace they kept running to which fixed the running back and forth problem.  They went back to hitting the Bakery block to make bread.

**Comment by mkienenb** [comment]
I had this problem a couple of days ago as well, and it was on my list to investigate.  I hadn't realized there was an issue covering it.   Interesting that breaking the furnace fixed it.   I didn't try that.  Next time it happens try using `/mc citizen info <colony number> <citizen id or full name>` to see what more information you can provide.
