### ISSUE TITLE
Mine Colonies not allowing Refined Storage Constructor/Deconstructor's to place/break blocks.

### ISSUE THREAD

**Issue by SystemCollapse** [ldtteam/minecolonies#1618]
### Minecolonies version

version 1.10.2 

### Expected behavior

- Setting Construct to place a blocks and the Deconstructor to break said a block.

### Actual behaviour

- It does nothing.

### Steps to reproduce the problem

Not to add other then,

ran /ftb team config ftbu.fake_players true
Tried adding fakeplayer to the permissions
Tried adding refinedstorage:constructor and refinedstorage:deconstructor to the permissions did not seem to work. Also tried setting block interaction to the target blocks and did not help either.

**Comment by Raycoms** [comment]
Yeah that's because their fakeplayer doesn't have the player uuid.

2017-11-13 22:52 GMT+00:00 SystemCollapse <notifications@github.com>:

**Comment by SystemCollapse** [comment]
I just disabled Protection from Mine colonies. But that won't fix it for anyone on servers. It is a feature that should not be on by default anyway as the majority of players don't play on servers. Also it cannot be disabled in the in game config so it takes a manual edit. Which I find odd since people setting up servers tend to have more understanding of such things then people just downloading and playing a pack off of curse.

I will let all my viewers know how to disable it.
