### ISSUE TITLE
Farmer is broken

### ISSUE THREAD

**Issue by CactussJack** [ldtteam/minecolonies#1626]
Minecolonies ver: universal-1.12.2-0.8.4422.jar
Minecraft version: 1.12.2
Forge version: forge-14.23.0.2515

I have built a basic field with the builder, the farmer has started working and after a while I noticed that the farmer were stuck in a corner. He sat there and didn't do anything (the wheat was fully grown near him)
So i used the recall button. He started working again, he went back to that corner and got stuck again. 
I hired a new worker. She started to work as well but she got stuck in the same corner.
"What about a new field?" That sounded like a great idea, but no, still the same problem.
Some screenshots: 
The 2 corners: 
![corners](https://user-images.githubusercontent.com/33664121/32791667-db6df016-c961-11e7-8559-bb1f7cc7a468.png)

And at night: 
![2017-11-14_16 41 02](https://user-images.githubusercontent.com/33664121/32791676-dedb726e-c961-11e7-89e5-cd4762db5f01.png)

I have tried my best to explain it.

**Comment by CactussJack** [comment]
Umm, and i'm using the official Minecolonies Modpack

**Comment by Raycoms** [comment]
Can you tell me if the blocks under the field are solid?

2017-11-14 16:36 GMT+00:00 CactussJack <notifications@github.com>:

**Comment by CactussJack** [comment]
Oh... i think there's a little lake :D

**Comment by Raycoms** [comment]
Yeah there is a problem with our pathfinding (we already have an issue for
that) that makes the worker unable to path if there is no block under a
field block.

2017-11-14 16:39 GMT+00:00 CactussJack <notifications@github.com>:

**Comment by CactussJack** [comment]
Thank you for the help :)
