### ISSUE TITLE
Pathing Error - Pacing very slowly back and forth

### ISSUE THREAD

**Issue by jakedecourcey** [ldtteam/minecolonies#1627]
### Minecolonies version

version 1.10.2-0.8.4063

### Expected behavior

- Worker path from current location to required location

### Actual behaviour

- Various workers will seem to path normally then stop and begin to "pace" very slowly backwards along the route for about 5 blocks, then they run forwards at normal speed to the same spot, then back to pacing, and so on. This occurs in certain locations unrelated to the worker's identity.

### Steps to reproduce the problem

1. First it was just the delivery person in a certain location, so I walled off that troublesome spot.
2. Then, the delivery person got stuck in a different place along with the miner.
3. I've tried placing waypoints, removing waypoints, converting grass path to dirt, firing and rehiring
4. As I type, 2 builders and the Dman are pacing back and forth in front of me, each taking the exact same route. When I recall them, they path normally until they reach that area and then revert to pacing.

**Comment by Raycoms** [comment]
are those places farmland?

2017-11-14 20:45 GMT+00:00 jakedecourcey <notifications@github.com>:

**Comment by jakedecourcey** [comment]
No, at first I thought it was the grass path, but it doesn't seem to be any particular material. It's also occurred in several different locations. 5, so far, maybe. And there's no water or even empty space, either. It's dirt at least 2 blocks deep below.

**Comment by Raycoms** [comment]
Is there a way to reproduce this?

**Comment by jakedecourcey** [comment]
Eh, not really. I can get it to happen in different areas of my colony, but I can't discern any particular pattern.

**Comment by jakedecourcey** [comment]
I've tried creating colonies in other worlds and the issue hasn't come up again - can't do much about it at this point.
