### ISSUE TITLE
Add parameter to colony deletion to keep structures

### ISSUE THREAD

**Issue by descention** [ldtteam/minecolonies#1632]
I'd like to be able to keep the structures I've built with Mine Colonies, even when my colony gets corrupted and I need to delete it. I'd be able to continue to live out of those buildings. I could then place the schematics over top and start my colony right back where I was once issues are resolved.

### Minecolonies version

version Any

### Expected behavior

- Optionally, colony buildings aren't removed when colony is deleted

### Actual behaviour

- Colony buildings are removed when colony is deleted

### Steps to reproduce the problem

1. Create town hall
2. Delete colony
3. ...
4. Profit

**Comment by Asherslab** [comment]
We have a lovely fellow already working on this!

**Comment by Moobien** [comment]
Another thing that could be useful similar to this is is if you are in creative mode and accidentally destroy your worker block, being able to restore it to the level it was at before you broke it would be useful.  The other day I  accidentally broke the block on my lvl 5 builder and ended up having to go through the whole build process again.

**Comment by Raycoms** [comment]
In creative you can just paste it over it.

**Comment by Moobien** [comment]
Paste over it?

**Comment by Raycoms** [comment]
Yeah there is a "paste" button in creative mode.

2017-11-27 11:17 GMT+00:00 Moobien <notifications@github.com>:

**Comment by Moobien** [comment]
Oh cool.
