### ISSUE TITLE
Dup and construction bug

### ISSUE THREAD

**Issue by ouroborus** [ldtteam/minecolonies#1633]
While trying to upgrade a bakery to stone tier 5, the builder generates infinite torches rather than placing them. This seems like an issue with the tier 4 bakery display frames, that are supposed to be above the door, being two blocks over in the wrong spot, in the same space a torch is. Moving the display frame manually stops the builder generating torches and lets the building complete.

MineColonies 1.12.2-0.8.4596

**Comment by marchermans** [comment]
@Raycoms ^^ ^^^^
@ouroborus What style?

**Comment by ouroborus** [comment]
The style is stone.

**Comment by Raycoms** [comment]
Can you try it with the newest alpha if it still happens?

**Comment by Raycoms** [comment]
Can't reproduce it with the newest version

**Comment by Raycoms** [comment]
Guess it's fixed then, closing
