### ISSUE TITLE
[Feature] [$10] Waste disposal unit [$10]

### ISSUE THREAD

**Issue by MattBeard** [ldtteam/minecolonies#1635]
Mature colonies with one or more active lumberjacks and one or more active miners often end up with chests overflowing with certain items such as cobblestone.

The idea is to have a new item that can be added to the warehouse (or perhaps somewhere else - maybe even part of a special building?) that will dispose of "excess" items.

The mechanism would be that there are a few chest-like slots in the unit and you place in these examples of the items you want disposed of. The deliveryman will then check this unit FIRST when taking items to the warehouse and put them here instead. Those items will then instantly (or slowly) be disposed of.

It could work a little like a furnace in that when a stack of 64 cobblestone is placed in the unit it goes down by maybe 1 per second until gone. There could be a flame effect on the texture like the furnace perhaps too.

It would be good if this item was rather hard to construct - perhaps the recipe uses 5 buckets of lava in a "boat" type pattern?

If this were implemented as a new building, the first level could have either one disposal unit (with only one slot for setting items to dispose of) and level 2 has two disposers (or one disposer with 2 selection slots). This may increase to 4 for level 3 and 8 for level 4.

I would be interested in comments.

**Comment by LazerusKI** [comment]
Just wanted to suggest the same but as a tab in the warehouse instead.

Basically an inventory just like the Builders where you can put in items, which are then "filtered" from being put into racks and instead simply vanish.

My main problem is with Seeds, my racks overflow with them and i have to manually sort them out every few hours

a "Waste disposal" building could be interesting too where you filter those things and the delivery guy brings them there to get destroyed.

**Comment by Zoidey** [comment]
The extra tab idea is not bad. I'd like to improve it but having an option that you add an item for it to keep a max number of that item and void the rest. Using your seed example you would tell it to only store 64 (a full stack) and void the rest or have a building that makes compost or fertilizer from the excess seed, dirt and plants or crops. Then you use that compost or fertilizer with your farms so the farmer has an extra job or something.

**Comment by Raycoms** [comment]
Closed in favor of joint issue.

**Comment by ravenbuilder934** [comment]
> Just wanted to suggest the same but as a tab in the warehouse instead.
> 
> Basically an inventory just like the Builders where you can put in items, which are then "filtered" from being put into racks and instead simply vanish.
> 
> My main problem is with Seeds, my racks overflow with them and i have to manually sort them out every few hours
> 
> a "Waste disposal" building could be interesting too where you filter those things and the delivery guy brings them there to get destroyed.

Do you have a chicken herder? Since they use seeds to breed chickens, they take care of all the seeds in my colony.

**Comment by Asherslab** [comment]
@ravenbuilder934 please don't necro closed issues. use the issue this got mentioned in

**Comment by ravenbuilder934** [comment]
@Asherslab It wasn't really about the waste disposal unit, just giving advice to LazerusKI. I will do that in the future though.

**Comment by Asherslab** [comment]
@ravenbuilder934 yes, but this post is from **2017**

**Comment by ravenbuilder934** [comment]
@Asherslab Oops, I hadn't noticed. Sorry!
