### ISSUE TITLE
Mouse-over not working in shelving-chest

### ISSUE THREAD

**Issue by MattBeard** [ldtteam/minecolonies#1636]
### Minecolonies version

version 1.12.2-0.8.4802 or curse 7.5.6522.42411

### Expected behavior

When the mouse points at an item in the shelving unit or your inventory while the shelf is open, the name of the item you are pointing at should pop up like in the normal chests.

### Actual behaviour

You point - nothing pops up. You then have to guess whether that is dark oak or spruce etc.

### Steps to reproduce the problem

1. Make a warehouse with shelves
2. Drop in some objects
3. Hover the mouse over them and wait for the description, give up
4. Compare with a normal chest

**Comment by marchermans** [comment]
![image](https://user-images.githubusercontent.com/5585406/32891219-0b356c40-cad2-11e7-89e0-eb27a73bdb4e.png)
This works for me.

**Comment by MattBeard** [comment]
And this is what I get:
![mc-shelf](https://user-images.githubusercontent.com/835593/32891825-01300c74-cacc-11e7-92ab-7e1157344fb3.jpg)

**Comment by Raycoms** [comment]
Do you have any other mods installed which could cause this?

2017-11-16 12:45 GMT+00:00 MattBeard <notifications@github.com>:

**Comment by MattBeard** [comment]
The only other mod I have is JourneyMap - I am trying again without

**Comment by Raycoms** [comment]
Yeah JourneyMap can't cause this. Let me test it here myself.

2017-11-16 12:52 GMT+00:00 MattBeard <notifications@github.com>:

**Comment by MattBeard** [comment]
New world with JorneyMap off:
![mc-shelf2](https://user-images.githubusercontent.com/835593/32894923-3d180cb4-cad6-11e7-9a2d-187ed026f1d8.jpg)

**Comment by descention** [comment]
Please note @OrionDevelopment was on 1.11.2 and @MattBeard is on 1.12.2

**Comment by marchermans** [comment]
Correct however, in this case it does not matter since the Code is the same. I checked.

**Comment by Raycoms** [comment]
fixed it, will merge pr soon
