### ISSUE TITLE
Food...

### ISSUE THREAD

**Issue by PhoenixRiver** [ldtteam/minecolonies#1638]
### Minecolonies version

version minecolonies-universal-1.12.1-0.8.4075

### Expected behavior

- They get deliveries of bread and eat it

### Actual behaviour

- no deliveries and I can only get them to eat bread by putting it in their inventory - the delivery guy takes it from their chests and puts in back in the warehouse. It might be because either Pam Harvest or Natura means that to make bread you have to use barley so maybe bread is a different ID? you can make bread with wheat but you have to mill the wheat to make flour.

### Steps to reproduce the problem

1. see above
2. if I get time I will try a setup with only mine colonies and see if I have the same problem, but I don't have much time at present.

P.S. They won't eat many types of food either so... that's an issue mainly associated with Natura and Pam's Harvestcraft though.

**Comment by MineShadow7** [comment]
Dman should deliver all kinds of items which contains "fooditem". I've actually noticed that they deliver all the food but citizens have to visit their homes at night first.

**Comment by Raycoms** [comment]
Will be fixed when we add the cook and delivery system

**Comment by PhoenixRiver** [comment]
> Dman should deliver all kinds of items which contains "fooditem". I've
> actually noticed that they deliver all the food but citizens have to visit
> their homes at night first.

Then maybe the problem is that only one has a home so far, the rest
only have a work chest and one has no chest at all - so maybe they
don't need food or get it from the warehouse?

Thank you for the update though, good to know this is in active
development :) - I might even be able to contribute but it'll be at
least a couple of weeks before I have to time to look at it :)

River

**Comment by Raycoms** [comment]
With the cook, we'll make that workers go to the restaurant to get food.

2017-11-17 1:13 GMT+00:00 PhoenixRiver <notifications@github.com>:

**Comment by PhoenixRiver** [comment]
> With the cook, we'll make that workers go to the restaurant to get food.

Excellent idea :) - then players at least know what to build, when -
I'm still trying to work out a good ordering for things (one of my
homeless citizens without a job complains every night about lack of
food!

River :)
