### ISSUE TITLE
[Feature] Better scarecrow GUI, and Options

### ISSUE THREAD

**Issue by bob0bob** [ldtteam/minecolonies#1644]
It would be great in the scarecrow gui to be able to select the field size.  Sometime you don't need a 5x5 farm field.  Having smaller ones available would be great.   Seems weird but a selection os a 2x2, 3x3, 4x4.  Would be great.  When using pams harvest, there are items you don't need a bunch of 

Just a thought.

**Comment by Zoidey** [comment]
Not a bad idea, another idea to add to it is maybe allow up to 4 or 9 crops. 

if you had a 4x4 farm you could have wheat, carrots, potatoes and melon in a corner each or something. I guess kinda like you can set whats in the NW, NE, SW and SE sections in the Forestry Multifarms.

**Comment by Wissi** [comment]
I agree on the second idea. 
Having a farmer "manage" up to 4 crops per field would be awesome due to the great varieties of mods like Pam's harvest. 
Maybe 4 slots in scarecrow to divide the plot in 4 sections w/4 diff. crops.

**Comment by Raycoms** [comment]
The field size I agree on, multiple crops I don't agree on, the reason we have fields and not one big field is that there is exactly one crop per field. If the player wants different types he has to add more farmer levels and or fields, else this is just tooo easy =D

**Comment by winex** [comment]
well, with harvestcraft this is insane, yeah.
maybe just give guys 2x2 grid in the scarecrow and half/triple(don't)/quad the field. wouldn't be hard to implement i think, well, even if AI checks this every time (i think there is no list of field-blocks). and Scarecrow probably already has some range check.

or just from NW to SE and to use all field you need to place 4 seeds.
i like this!

**Comment by Raycoms** [comment]
Closed in favor of joint issue.
