### ISSUE TITLE
[Feature] Guard Improvements

### ISSUE THREAD

**Issue by bob0bob** [ldtteam/minecolonies#1645]
It would be really neat and a better realistic improvement. Ok, I know I'm talking about minecraft when it comes realistic.  I get it.  But a guard working 24hr/ until he dies.

But this is my thought.

Be able to assign 2 guards to a guard tower.  This way you have have a daytime guard and a nighttime guard.  You hire one for day time and hire one for night time.

Ok,  if you only hire 1 guard, that guard will work 24/hr until he/she dies.  (slave duty).   So in the beginning you can put just one.  
Second thought,  if you only have one guard,  it would be great after say (7 days, or sometime) of on duty, start adjusting the colony happiness.   Basically the guard is getting tired of working 24/hr.  He needs relieve.   Also, start posting in chat about needing to be relieve from duty to rest.

**Comment by Wissi** [comment]
Barracks takes care of this already. Tho individual guard Towers still remain w/1 guard per Tower.
Can the Tower code for the barracks be copied over to the regular Tower to achieve this as is in the barracks?

**Comment by Raycoms** [comment]
Closed in favor of joint issue.
