### ISSUE TITLE
Farm - Issue

### ISSUE THREAD

**Issue by bob0bob** [ldtteam/minecolonies#1647]
minecolonies-universal-1
minecraft .12.2-
minecolony 0.8.4802

Not all fields are showing up.  Only 4 of the 5 show up.   The one not showing up is not even the furthest away.
It is a level 1 farm,  weird thing,  is the farmer is farming 2 fields.   the 2nd field is the field that is not showing up in the gui of the farm block.
![2017-11-16_21 23 03](https://user-images.githubusercontent.com/30982580/32927861-a7030cf8-cb14-11e7-838c-fdf1ef5baac0.png)

**Comment by bob0bob** [comment]
Also,  it could be related to my colony did experience the issue where the farm block was not working.  I had a farmer that was a lvl 8 before it broken.  The fields where already created,  I did break them and place them down again.   It then showed no farmer but after a period of time that farmer was assigned to it even though the farm was level 1 and on manual.

**Comment by bob0bob** [comment]
Farm still has issues seeing all farms.   I ahve 5 and sometime the GUI only shows 4.

**Comment by wilsondgonzales** [comment]
@bob0bob try rebuilding the field?

**Comment by bob0bob** [comment]
With latest version,  farming is working now.
