### ISSUE TITLE
Citizens - Enhacnements

### ISSUE THREAD

**Issue by bob0bob** [ldtteam/minecolonies#1653]
Would be nice to easily find information about a citizen.  Maybe in the town hall, instead of just listing a citizen you could get information about the citizen.   Like their job, place of living level and such.

Sometime your running around everywhere trying to locate where a citizen lives,  or which mine they are mining at.   The skin of the citizen is the only indication of their job.   It gets harder and harder to remember everyone as the colony grows.

Just info in the town hall about each citizen would be great.

**Comment by Zoidey** [comment]
Oh maybe have the information on each citizen stored at the library that you can build, might be a way to give the library a use other than just a decoration.

**Comment by bob0bob** [comment]
Sounds cool.  Giving function to other building is always better.  Just makes the mod a FULL overall experience  when there is more.

**Comment by Raycoms** [comment]
Added it to the townhall already
