### ISSUE TITLE
Builder - Enhancement  Manual assignment

### ISSUE THREAD

**Issue by bob0bob** [ldtteam/minecolonies#1656]
A good feature would be able to set building assignments to "MANUAL" or "automatic".  When you need up with Multiple builders, it gets to the point there is no much time waster because of the assignment.

Exmpl:
Builder A  is located on the west edge of town.
Builder B is located on the east edge of town.
On average each building is 85 blocks from center of town.

I define an upgrade to Builder A 's hut.
I define an farm upgrade on the East edge of town.

System assigned Bldr A to  Farm upgrade on the east of town.,   Bldr B gets assign to upgrade Bldr A's hut.

90% of the time to build is them just walking back an forth from their hut to get supplies to the building they are building.

If we had the ability to manually assign builders to certain build request.  We could cut the time by more than half.

If you have it on manual build assignment.  Then when bldr is done, inside the chat window, post that the builder is done and needs a new assignment.
Also, allow us to go back to change assignment back to auto like the farm.

**Comment by Raycoms** [comment]
this has been done
