### ISSUE TITLE
Miner not working, "Com.minecolonies.c"

### ISSUE THREAD

**Issue by beorma** [ldtteam/minecolonies#1658]
### Minecolonies version

version X.X.XXXX or curse X.X.XX
minecolonies-universal-1.12.1-0.8.4075
### Expected behavior

- Miner working

### Actual behaviour

- Came to Miner chest and idling with message "com.minecolonies.c" overhead

### Steps to reproduce the problem
Unsure if related but
 Asked for slabs twice, fences, then torches then came back to box again and broke

**Comment by Raycoms** [comment]
Give him cobblestone

2017-11-19 16:06 GMT+00:00 beorma <notifications@github.com>:

**Comment by Raycoms** [comment]
We have an issue for that already, closing in favor of it.
