### ISSUE TITLE
MAJOR: Latest release breaks previous worlds!

### ISSUE THREAD

**Issue by MattBeard** [ldtteam/minecolonies#1661]
### Minecolonies version

version 1.12.2-0.8.4905 or curse 7.5.6529.932

### Expected behavior

- Upgrading to the latest release should be painless and error free

### Actual behaviour

- Loading my world up I get "There are 47 missing entries in this save"
![mc-err47](https://user-images.githubusercontent.com/835593/32995691-41a1858e-cd70-11e7-85cf-54b7abc1e4a2.JPG)

### Steps to reproduce the problem

1. Install minecolonies with an older version (say 1.12.2-0.8.4832) and make a world
2. Upgrade to 1.12.2-0.8.4905
3. Load the old save
4. Panic!

**Comment by Raycoms** [comment]
Hello, yes. Our release system works the following way:
We have alpha versions which are cutting edge, please never go from alpha to beta or from beta to release even if the version number is higher.

As soon as a beta version is successful for a while it will automatically become a release. That means that it can still be older than most versions.
As soon as we convert the beta to a release we will convert the latest alpha to beta.

**Comment by MattBeard** [comment]
OK, I'm confused... so if I am on 1.12.2-0.8.4832, which version should the next one I install be?

And... having loaded that version can I get those sounds back, or do I need to revert to a backup and lose recent progress?

**Comment by Raycoms** [comment]
When you're on 1.12.2-0.8.4832 that means that's the newest 1.12 version
there is (The alpha is always newer than beta or release).
In the next days there will probably be a new beta.

2017-11-19 21:59 GMT+00:00 MattBeard <notifications@github.com>:

**Comment by MattBeard** [comment]
Returning to 1.12.2-0.8.4832 seems to have had no ill effects. The workers are speaking again!

**Comment by marchermans** [comment]
@MattBeard see that 48xx version number? That number indicates time. The higher the number the newer the build. Generally speaking you can only upgrade, so with the flow of that number (regardless if it is an Alpha, Beta or Release) never down. So once you go from a 47xx Release, to a 48xx Alpha there is no way back.

However if you are on a 47xx Alpha you can simply go to a 48xx Release no problem.
