### ISSUE TITLE
Town Hall bug - (First upgrade with bookshelves)

### ISSUE THREAD

**Issue by Deckerz** [ldtteam/minecolonies#1662]
### Minecolonies version

version1.10.2-0.8.4908

### Expected behavior

- Build town hall upgrade with bookshelves

### Actual behaviour

- Gets stuck asking for item frame

### Steps to reproduce the problem

1. Upgrade to town hall with bookshelves
2. gets stuck with item frame (eats the frame but doesnt do anything)
3. ...
4. Profit

**Comment by Raycoms** [comment]
He actually places them from his hut , that's why it seems he isn't. Just give him enough.

**Comment by Deckerz** [comment]
Ah okay i see, i thought it was bugged cause he asks for one not how many he actually needs.

**Comment by Raycoms** [comment]
This should be fixed in the newest alphas.
