### ISSUE TITLE
Builder does not finish the Farmers Hut

### ISSUE THREAD

**Issue by Ralf2745** [ldtteam/minecolonies#1663]
### Minecolonies version

version 1.12.2-0.8.4832

### Expected behavior

- Builder should finish the Farmers Hut

### Actual behaviour

- Builder is missing Water Block.
- Cant get Water Block

### Steps to reproduce the problem

1. Setting up Building
2. Starts Building
3. Missing Block

**Comment by Raycoms** [comment]
Please remove the Creative+ mod, it messes with the water and the builder is unable to get it.
