### ISSUE TITLE
Farmer not harvesting barley

### ISSUE THREAD

**Issue by PhoenixRiver** [ldtteam/minecolonies#1666]
### Minecolonies version

version minecolonies-universal-1.12.1-0.8.4075
version natura-1.12-4.3.0.23
(version Pam's HarvestCraft 1.12.2a - I think it is Natura though)

### Expected behavior

- for the farmer to harvest barley

### Actual behaviour

- the farmer doesn't harvest barley

### Steps to reproduce the problem

1. create farm
2. create field
3. plant field entirely with barley and put barley seeds into the scarecrow
4. farmer sits there with no experience not harvesting barley

**Comment by Raycoms** [comment]
Do you have a log of this?

2017-11-20 17:08 GMT+00:00 PhoenixRiver <notifications@github.com>:

**Comment by PhoenixRiver** [comment]
How do I create a log? or where do I find them? I can see a dat file
but nothing else other than one of my scans. If you meant he mincraft
log file there is nothing related to minecolonies at all other than no
problems at all! (Impressive given lots of the other mods seems to be
causing things here and there!)

River *<:@)

**Comment by Raycoms** [comment]
Will have to test that then

2017-11-21 15:41 GMT+00:00 PhoenixRiver <notifications@github.com>:

> How do I create a log? or where do I find them? I can see a dat file
> but nothing else other than one of my scans. If you meant he mincraft
> log file there is nothing related to minecolonies at all other than no
> problems at all! (Impressive given lots of the other mods seems to be
> causing things here and there!)
>
> River *<:@)
>

**Comment by PhoenixRiver** [comment]
Forgot to mention that the farmer seems happy with there being something in the field too - she doesn't complain there is nothing in the scarecrow. I should not it is planted on siltydirt but does have water source blocks  (I have a second field with exactly the same setup with a separate farmer which has wheat instead and which works... just in case that's relevant).

**Comment by Raycoms** [comment]
Can you switch he other field, which works to barley and tell me if that
works?

2017-11-21 15:44 GMT+00:00 PhoenixRiver <notifications@github.com>:

**Comment by PhoenixRiver** [comment]
Have switched the wheat and barley fields and the barley still doesn't
work but the wheat continues to work (despite having changed between
farmers), have planted a second barley field with the other one and it
doesn't work either but a new bamboo shoot field is working with the
farmer that originally couldn't do the barley field - I also noticed
that she had not used her hoes at all but the new farmer did ask for
seeds for the barley field and then does nothing with them.

If you have any other tests you want me to try I can have a go (though
it might be difficult to built something not on siltydirt - apparently
my town is right in the middle of that biome and mostly surrounded by
water... (the water I knew about the lack of many other biomes not so
much *sigh* (and it seems I will have to go hunting since I can't find
one of the two plants to make black dye for the third level builders
hut (since apparently one of my mods (essentially Biomes O' Plenty,
Natura, Forestry and Pam's Harvestcraft) has removed the squid ink
recipe?!?)

**Comment by Wissi** [comment]
I think this issue has been resolved when the compatibility w/Pam's was done.
Close issue @Raycoms ?
