### ISSUE TITLE
Farmer doesn't work unless the field has water source blocks...

### ISSUE THREAD

**Issue by PhoenixRiver** [ldtteam/minecolonies#1667]
### Minecolonies version

version minecolonies-universal-1.12.1-0.8.4075
version natura-1.12-4.3.0.23

### Expected behavior

- for the farmer to work with a field if the crops are growing

### Actual behaviour

- the farmer doesn't work if there are no water source blocks supplying water despite the fact the crops grow in siltydirt without the need for the water (I believe this may ap[ply to more than just siltydirt)

### Steps to reproduce the problem

1. create farm
2. create field
3. plant field entirely with crop and put seed crop into scarecrow
4. farmer sits there with no experience not working

**Comment by Raycoms** [comment]
The problem is not the water, the problem is that the farmer requires a dirt block.

**Comment by PhoenixRiver** [comment]
Erm... then none of my farms should be working because none of them
have "dirt" blocks, only "silty dirt" blocks... and they only started
working when those were made wet from a water source block...
