### ISSUE TITLE
Deliveryman carries sword, not bow!

### ISSUE THREAD

**Issue by MattBeard** [ldtteam/minecolonies#1670]
### Minecolonies version

version 1.12.2-0.8.4943 or curse 7.5.6529.932

### Expected behavior

- When delivering a bow to a guard, I expect to see the deliveryman carrying a bow

### Actual behaviour

- They actually go to the bow chest, take out a bow, walk with a visible **sword** to the guard tower, give the bow to the guard, who then is seen to be carrying a bow.

### Steps to reproduce the problem

1. Get a guard that is expecting a bow
2. Follow deliveryman as they get a bow
3. See them appear to be carrying a sword!

**Comment by Raycoms** [comment]
Please reopen if reaccurring.
