### ISSUE TITLE
MOAR issues :P

### ISSUE THREAD

**Issue by Moobien** [ldtteam/minecolonies#1671]
Hey guys Found an issue for you :P I bet you devs hate me by now lol.

Upgraded to 1.12.2 finally, REALLY loving the Taiga and Birch buildings!  Did you like the armory I made? you can be honest and tell me how bad it sucked lol.

ok so the issue.  I have been making some highways, if you like them you can adapt them if you like.  the highways are fenced, I got REALLY sick of the peasants taking shortcuts over grass when I have had them make nice paths to run faster on, and in the middle is 2 rail tracks.  as you can see in the screenshots the rails look/build correct in 3 of the 4 possible orientations.  Is this a bug or have I done something wrong?

Please ignore 3 of the screenshots as I had to raise an issue with the mekanism guys.  https://imgur.com/a/oMusZ

**Comment by Moobien** [comment]
SPECIAL bonus screenies!

my new track scan underground coming off of the lvl 5 taiga dman building

https://imgur.com/a/P6RZS

**Comment by Raycoms** [comment]
I'd say this is an issue on how tracks work in general, I mean even in vanilla I have a hard time placing them

**Comment by Moobien** [comment]
Thats cool :) thanks @Raycoms
