### ISSUE TITLE
Minecolonies vs Mekanism Digital Miner

### ISSUE THREAD

**Issue by Moobien** [ldtteam/minecolonies#1674]
Just a heads up guys, the minecolonies colony protection prevents the Mekanism Digital Miner from working. Disabling protection allows it to work properly.

https://github.com/aidancbrady/Mekanism/issues/4820#issuecomment-346278850

@raycoms is there a way to keep protection on AND let the dminer work?

**Comment by marchermans** [comment]
@Moobien this is a Problem on Mekanisms side due to a broken FakeUser implementation I think, EnderIO has the same Problem. Will keep the discussion there for now.
