### ISSUE TITLE
1.12 placing town hall crashes minecraft

### ISSUE THREAD

**Issue by Sammy004** [ldtteam/minecolonies#1676]
### Minecolonies version

version 1.12.2-0.8.4932

### Expected behavior

Place town hall.  Town hall placed... game continues

### Actual behaviour

When placing town hall game crashes and world becomes unplayable.  Attempts to reload the game cause instant crash

### Steps to reproduce the problem

1. Create new world.  Place supply camp
2. Open chest take out wand and town hall.
3. Move distance away and place town hall.
4. Game crashes.

This can be reproduced each time.

**Comment by Raycoms** [comment]
Please use the newest alpha in 1.12.2 for the fix for this or use an older
forge version.

2017-11-22 11:55 GMT+00:00 Sammy004 <notifications@github.com>:

**Comment by PhoenixRiver** [comment]
I have rarely had crashes from trying to place other buildings too but they don't break the map... I just reload and it's all fine but there is no new building and trying again doesn't necessarily trigger the problem; it seems to be more of an issue if I place the building then press esc and move around and then go back to finish placing the building... the more I do that the more likely a problem. When I then try and press the tick mark it sometimes works straight away, sometimes takes a while, sometimes I have to press a few dozen times and it finally works  and occasionally it just crashes (so it's something to do with the tick mark maybe? Or something in the way when you try and press it?)

**Comment by Raycoms** [comment]
Yeah forge did update some of their message code in the newer forge
versions, we fixed this bug already but it's currently only in the alpha
versions.

2017-11-22 16:47 GMT+00:00 PhoenixRiver <notifications@github.com>:

**Comment by PhoenixRiver** [comment]
Cool :)
