### ISSUE TITLE
scan tool oddity...

### ISSUE THREAD

**Issue by PhoenixRiver** [ldtteam/minecolonies#1678]
### Minecolonies version

version minecolonies-universal-1.12.2-0.8.4932
version BiomesOPlenty-1.12.2-7.0.1.2309-universal

### Expected behavior

- use the scan tool to scan a 16x16x3 block of siltydirt to create a schematic that makes the builder mine the ground out to a depth of three and infill with siltydirt

### Actual behaviour

- use the scan tool to scan a 16x16x3 block of siltydirt to create a schematic that makes the builder mine the ground out to a depth of three and infill with Silty Dirt EXCEPT schematic contains one (1) block of Loamy Grass (since I personally laid every block it was definitely all Silty Dirt because I have no biome nearby that provides Loamy Grass and once you did it up it turns into Dirt rather than Grass anyway - also the biome is all Silty Dirt so if there was a missing block then it should be replaced with Silty Dirt, not Loamy Grass (also said Loamy Grass appears to be underground when placed by the builder - I used creative to give her some).

### Steps to reproduce the problem

1. dig a 16x16x4 (four) hole
2. fill with siltydirt
3. scan block (infilling as necessary before the final right click and leave for time in case grass grew)
4. get builder to use schematic
5. curse because it's the third time I tried this (the first time had lots of silty grass blocks on top because I didn't use a layer of dirt on top to stop the grass problem which the builder couldn't place I don't have silk touch to gice her the necessary blocks, the second time had two (2) Loamy grass blocks once I had a fourth layer of siltydirt on top to stop the grass growing, third time I still had one Loamy grass... give up and use creative to get those blocks for my builder.)

**Comment by Wissi** [comment]
Well the issue here are the modded blocks and how they are coded by their devs. 
Minecolonies works with the block code designation from Minecraft.
Try using regular "vanilla" dirt or any other normal minecraft block instead of modded blocks. 
If issue persists w/regular minecraft blocks then let us know, if not so that we can close this issue?

**Comment by PhoenixRiver** [comment]
Hello :)

> Well the issue here are the modded blocks and how they are coded by their
> devs.
> Minecolonies works with the block code designation from Minecraft.
> Try using regular "vanilla" dirt or any other normal minecraft block instead
> of modded blocks.
> If issue persists w/regular minecraft blocks then let us know, if not so
> that we can close this issue?

I understand that this is a problem with modded blocks but I might
also suggest that Biomes O' Plenty (which is where this particular
block comes from, never mind any of the other mods that add dirt
types) is a very popular mod that a lot of people like to use and that
it might be nice to work out what the problem is... though I'm willing
to file a bug report with them too I don't expect I will get any
better response from them... so the bug just stays despite these being
two otherwise entirely compatible mods that are both very popular...
(though, if I had to pick, I'm afraid I'd have to pick Biomes due to
the inflexibility and difficulty of creating buildings in Colonies -
that the builder insists on particular flowers and particular types of
wood makes things incredibly difficult as soon as any non-vanilla
biomes are introduced... getting the diamonds for the top level
building items is really easy compared to finding those damn blue
orchids in a vanilla swamp biome!!!)

Yes, this is a punt because, no, I don't have the concentration time
to hunt this down myself (the joys of having a child) so I'm just
hoping... maybe I should just build my town in a desert... at least
that way my single warehouse wouldn't be bursting to the gills with
food and nothing else useful *sigh*

**Comment by PoroUsedSnax** [comment]
There have been a few updates to the scan tool since this was made, as such it's possible something changed there and this will be fixed. If this could be retested to see and then we know if this can be closed or should stay open.

**Comment by Raycoms** [comment]
Please reopen if still an issue
