### ISSUE TITLE
Construction Sign removal after an upgrade...

### ISSUE THREAD

**Issue by PhoenixRiver** [ldtteam/minecolonies#1679]
### Minecolonies version

version minecolonies-universal-1.12.2-0.8.4932

### Expected behavior

- Construction Signs get removed after an upgrade

### Actual behaviour

- Construction Signs not entirely removed after an upgrade

### Steps to reproduce the problem

1. build town hall
2. build builder behind town hall
3. upgrade town hall and discover that it gets bigger and it removes part of the builders hut and has construction signs running over it
4. discover that once the upgrade is finished the construction signs that run over the builders hut are not removed (this does not happen if the overlapped building no longer has a chest (i.e. doesn't exist) only if the building still has a chest?!)

**Comment by Raycoms** [comment]
Yeah we have an issue for the townhall scan size, we have to fix that definitely.
