### ISSUE TITLE
Suggestions (quickie)

### ISSUE THREAD

**Issue by PhoenixRiver** [ldtteam/minecolonies#1680]
Make the player able to request items from the delivery man (since otherwise I have to go to the warehouse every time to do things that people request of me and there is no crafting station in the warehouse (certainly at low levels and none at all in any level one buildings I think?)

Have stone versions of every building - wouldn't use it on the current map but if I were in a mountain or hill biome they'd be much better than wooden structure (especially the warehouse and town hall given their size and number of needed resources).

**Comment by marchermans** [comment]
This is currently planned. However this is on hold untill the request system is completely implemented.
