### ISSUE TITLE
Builder going for a wander...

### ISSUE THREAD

**Issue by PhoenixRiver** [ldtteam/minecolonies#1681]
### Minecolonies version

version minecolonies-universal-1.12.2-0.8.4932

### Expected behaviour

- builder stays by the building she is building and keeps working

### Actual behaviour

- builder walks to the opposite corner of the new building but gets lost and stops working on building to finally return and do a little more before leaving again and getting lost again...

### Steps to reproduce the problem

I_think_ this _night_ be the problem but I'm not sure...

1. build building
2. build building where the construction signs are on top of the first building - even if only the one space they are further than the edge of the new building
3. make it worse? by having the builder dig a huge foundation forcing them to not cut the corner to the opposite corner and having them go around the side
4. the builder seems to want to get to one block beyond the opposite corner of the build area (similar to the block they stand on when they start building), however if that block is inaccessible then they keep moving away from the original corner trying to get there but eventually time out and return to the original corner. However the builder only seems to place or remove blocks when they are in the first corner's quarter of the building (they work on the whole building but only work when they are inside that first quarter's area)... my builder can make it across town before giving up getting to the opposite corner and coming back.

I understand that this is unusual because I'm trying to build things right up against each other but it makes it easier for me to do most of the work than let my builder do it - it which case why Mine Colonies! :D I'm also confused why the builder moves at all because she doesn't if she has all the resources she needs in any other case. (Yes, I checked, it's not due to resources or tools - proved because she doesn't even collect anything when she goes and gets lost!)

**Comment by Raycoms** [comment]
the builder searches a side where he is able to have a safe stand, this might not seem very good at times. But it's the most secure solution.
