### ISSUE TITLE
Lumberjack can't find trees

### ISSUE THREAD

**Issue by ouroborus** [ldtteam/minecolonies#1683]
Mine Colonies 1.12.2-0.8.4832

The screenshot shows how I have my trees arranged. The lumberjack building is right behind me.

I did this because the lumberjack and the nearby guard have a tendency to either get stuck in the leaves when a tree grows near them or climb the trees and then get stuck on the canopy, unable to get down.

With this arrangement, they no longer get stuck, but the lumberjack can no longer find the trees.

![2017-11-22_21 03 46](https://user-images.githubusercontent.com/392047/33159604-45609a7e-cfc9-11e7-880e-effb1efe1811.png)

**Comment by Justen-N** [comment]
We will eventually  rework the pathfinding system. Currently, your lumber
jack can't  "see" the trees because his "look for trees" looks at the level
he is standing on, not above or below it.

**Comment by ouroborus** [comment]
I think it might be a bit more complex than that. He seems to find trees on rolling terrain just fine. It's just this specific instance when there are no blocks around the block the tree sits on.

Anyway, I understand the team is working on it.

**Comment by Raycoms** [comment]
The lumberjack can't find trees which are on dirt like that
