### ISSUE TITLE
Miner using Tinkers silk touch pick as if it was normal

### ISSUE THREAD

**Issue by Deuxis** [ldtteam/minecolonies#1687]
### Minecolonies version

version 1.10.2-0.8.4908

### Expected behavior

The Miner should acquire silk touched blocks (stone, redstone ore, etc).

### Actual behaviour

The Miner mines as if he had normal pickaxe (cobblestone, redstone dust, etc).

### Steps to reproduce the problem

1. Make a pickaxe with Squishy modifier (e.g. sponge tool rod)
2. Watch its plainly written "Silk Touch" be completely ignored.
3. ...
4. Profit

**Comment by marchermans** [comment]
Yeah they just hold the pick and damage it.
It is low on the priority list to make them actually use the tool. But that will take some time.

**Comment by Raycoms** [comment]
Problem is that those tools require fakePlayers and not just an entity. closed for now
