### ISSUE TITLE
Minecolonies Patreon advantages.

### ISSUE THREAD

**Issue by Raycoms** [ldtteam/minecolonies#1692]
Several things could be implemented like:

Custom Stylepack (Someone has to build that).
Custom villager skins (Someone has to design those).

**Comment by Asherslab** [comment]
The last one with "Might have to think that through completely" is mainly in reference to Minecraft's EULA, which states that we/us/you can't give players any advantage within game for money (which in turn includes patronage)

**Comment by Wissi** [comment]
Implementing it in the JAR does NOT mean that you are violating the EULA. 
How the server will implement it is the issue in reality.  If a certain "feature' is ONLY made avail to "patreons" f.e. that would be a violation, but making it accessible to any player (at an extremely high cost of playtime/money earned/etc etc) as well complies w/EULA.
The code for implementing it and turning it on/off in config as a "feature" is awesome and does NOT violate the EULA.
It is a great feature that will bring more attention to servers that host this mod.

**Comment by blacksythe** [comment]
Simplest solution is expand the current config file option into something that intergrates into shop and server management plugins. Leaving the config option in place where patreons can be added/removed manually and/or automatically and updated when the mod updates. (short term) Later you would want a system that has patreon intergration that automatically requests that information keeping the config file as a backup (if possible)
