### ISSUE TITLE
Still confused about Barracks!

### ISSUE THREAD

**Issue by MattBeard** [ldtteam/minecolonies#1701]
### Minecolonies version

version 1.12.2-0.8.5203 or curse 7.5.6529.932

### Expected behavior

- It seems I should be able to build barracks and barracks towers

### Actual behaviour

- I have no idea how to craft a barracks chest in survival - is it really for creative only???

### Steps to reproduce the problem

1. Be new to Minecolonies
2. See that some people are using Barracks
3. See that you can build them in creative
4. Read the Wiki, the forums, all the other pages available...
5. Go mad trying every single combination of objects in a crafting table!!!

**Comment by Raycoms** [comment]
It's an iron block in the middle, build tool on the top, and planks around it.
