### ISSUE TITLE
Extract Static variables

### ISSUE THREAD

**Issue by Raycoms** [ldtteam/minecolonies#1702]
Our static variables should be extracted out of our entity/building etc classes in a few global constant classes.

This will remove a lot of duplicated code and allows us to change constants at a more central place.

**Comment by Asherslab** [comment]
Love that idea. i'd be cool with working on that at some point if someone else hasn't already done it. Although the way i did it personally (with my plugin) might be different than what you're thinking

**Comment by Raycoms** [comment]
Kostronor has been assigned for this task, it's his baby =D

2017-11-27 8:09 GMT+00:00 Asherslab <notifications@github.com>:

**Comment by Raycoms** [comment]
Done in a lot of the most important classes already.
