### ISSUE TITLE
PLEASE CLOSE

### ISSUE THREAD

**Issue by bob0bob** [ldtteam/minecolonies#1704]
Yesterday you released  Alpha version  
minecolonies-universal-1.12.2-0.8.5203

today the alpha version is saying
minecolonies-universal-1.12.2-0.8.5066

But the beta version is saying 
minecolonies-universal-1.12.2-0.8.5081

I'm asking if the versioning a mistake?

Yesterday alpha was .5203  and today it says 5066.   This would indicate the alpha went backwards.  Now it appears that the beta version is ahead of the alpha.

Am I missing something.

**Comment by bob0bob** [comment]
Got my answer on discord

**Comment by ghost** [comment]
You can close your own issues.
