### ISSUE TITLE
Citizen - Food consumption - Suggestion

### ISSUE THREAD

**Issue by bob0bob** [ldtteam/minecolonies#1709]
It would be nice to have something in the config to adjust the food consumption.   I have a colony of 16 people with lvl 3  farm/fishing.    There is SO MUCH food,  it is insane.   The citizens do not even close to that amount the farm/fisherman is producing.   If would be nice to set it to how many pieces per day (just saying).  To make it a bit more realistic.  Mine craft is crazy for food.  You can go days without the need to eat.   
At this rate one farm and one fisherman could feed 50+ people at this rate.   Would be cool if we could adjust it to be a bit more real and have the need to create second huts for larger colonies.

Just a thought.

**Comment by bob0bob** [comment]
How about this as a change.

Currently food is eaten at night.  based on SATURATION_DECREASE_FACTOR (.2) * (2 * pow of builders level)

An idea for change?  I don't know if this is the rate place or not.

Right now the function getDesiredActivity handles the decrease of saturation.  The function onLivingUpdate handles TryToEat if saturation is below a certain level.

So Change this based on several factors.
in the onLivingUpdate function.  Every 500 ticks (1/2 hour mc).  Reduce the saturation level (instead once a day).  but base it on the activity of the citizen at the time.   So if they are "SLEEP, IDLE" the saturation level falls at one rate.  if it is something else "WORKING" then they fall at a higher level.  Then have in the config file an adjustable amount that can be done for saturation.  This will allow people to choice the level of food consumption.   You can change it so that people eat daily or more times a day depending.  

Right now, the higher the building level the more consumption that takes place.  So at a level of 5.  would be 1 point per day.   The level of 7 required to eat.  Means 3 mc days before each person can eat or longer.
Level 1 worker works out to .2 reduction per day and they have to get below 7 from 10 to eat.

It will force people to build more than one farmer/fisherman.   I see youtube video after youtube video that starts a fisherman or farmer and then stops it and rehires them to do something else.  because after about mc week.  you have enough fish/food  to make people live or years without anymore.    Until they get higher but it is still not a issue.   Check out youtube video like Java Vampire where he is stopping farming for long stretching because he has so much food in the colony it is insane.

**Comment by Raycoms** [comment]
Seems like an interesting idea

**Comment by Raycoms** [comment]
Adapted it to food per action already
