### ISSUE TITLE
The 1.12.2 version Builders wand Mirror Image function not working in Single Player

### ISSUE THREAD

**Issue by kedamono** [ldtteam/minecolonies#1710]
### Minecolonies version

version 1.12.2-0.8.5203

### Expected behavior

Use the Builders wand to place a preview either a scanned building or built-in decoration, like the Birch animal herder decoration in Single Player world. Use the Mirror Image function to flip the preview of the schematic.

### Actual behavior

Neither scanned in objects or built-in decorations will mirror image.
On the 1.12.2 Official server, the same decoration flips when I use the builders wand.

### Steps to reproduce the problem

1. Create a new creative single player world.
2. Use the builders wand to place a preview the Birch Animal Herder decoration.
3. Click the mirror image function on the GUI for the Builders wand.

Expected: The decoration flips.

Actual: It does not flip.

**Comment by kedamono** [comment]
And the latest build has fixed this issue. Thanks!

**Comment by Raycoms** [comment]
Np, thanks for closing this issue =D

2017-12-04 16:35 GMT+00:00 kedamono <notifications@github.com>:
