### ISSUE TITLE
Wood Barracks has scan dirt block in the air!

### ISSUE THREAD

**Issue by MattBeard** [ldtteam/minecolonies#1711]
### Minecolonies version

version 1.12.2-0.8.5066

### Expected behavior

- Building the level 1 wooden barracks should be a viable building

### Actual behaviour

- The builder puts a dirt block in the air when building!
- This is almost certainly the block used to mark the top corner when the design was scanned

### Steps to reproduce the problem

1. Build a level 1 wood barracks
2. Look up

**Comment by bob0bob** [comment]
I noticed that also.
