### ISSUE TITLE
Guards on auto-patrol end up on top of trees!

### ISSUE THREAD

**Issue by MattBeard** [ldtteam/minecolonies#1712]
### Minecolonies version

version 1.12.2-0.8.5066

### Expected behavior

- Guards should not end up getting in places where they are "stuck"

### Actual behaviour

- When on automatic patrol, guards often somehow get themselves on top of trees and are unable to get down

### Steps to reproduce the problem

1. Build guard towers or barracks, near some trees
2. Set guards to patrol, on automatic
3. Wait a few days
4. Look at the nearby trees and you will probably see guards stuck on top!

**Comment by Raycoms** [comment]
they don't tp down eventually?

2017-11-27 21:55 GMT+00:00 MattBeard <notifications@github.com>:

**Comment by MattBeard** [comment]
How long should it take? I get fed up waiting and build stairs down for them!

**Comment by Raycoms** [comment]
I think the max is 2 minutes it should take.

2017-11-27 22:02 GMT+00:00 MattBeard <notifications@github.com>:

**Comment by bob0bob** [comment]
I've seen not just guards but citizens also.  usually happens somewhere around dusk.  It has happened to me several times, it has all been citizens for me.    They just get TP up on the roof of the hut for me where the citizen is suppose to be sleeping.

Quick solution, is hit "recall" at their work or post.

**Comment by ouroborus** [comment]
They don't seen to TP back down. They just try to repath every once in a while and end up idling somewhere else on the tree canopy.
