### ISSUE TITLE
lumberjack - all trees not showing trees on old lumberjack huts

### ISSUE THREAD

**Issue by bob0bob** [ldtteam/minecolonies#1715]
minecolonies-universal-
minecraft 1.12.2-
mine colonies 0.8.5203

I see you added a complete tree list for lumberjack huts.   But if it is an already existing lumber jack, it doesn't show the entire list but new huts since the fix shows them all.

Is there a way to update existing lumberjacks gui to reflect all the trees.  Seems like it is only done when the hut is placed.

**Comment by Raycoms** [comment]
Yeah only on hut placement
