### ISSUE TITLE
Raiders Spawn in Town

### ISSUE THREAD

**Issue by Deckerz** [ldtteam/minecolonies#1718]
### Minecolonies version

version 1.10.2

### Expected behavior

- Raiders spawn outside of town and move in

### Actual behaviour

- Raiders spawn pretty much on top of the town hall killing colonists before you even have a chance to react

### Steps to reproduce the problem

1. get town big enough for raids
2. night time
3. ...
4. Profit

**Comment by Asherslab** [comment]
Closed in favour of #1657
