### ISSUE TITLE
Crash when placing town hall

### ISSUE THREAD

**Issue by OfficiallyBrown** [ldtteam/minecolonies#1721]
### Minecolonies version

version 0.8.4075

### Expected behavior

- Ability to place town hall without crashing

### Actual behaviour

- After placing the town hall with the build tool, the game crashes and any attempt to re-load the world will also crash

### Steps to reproduce the problem

1. Placing town hall. It has done it every time for 5 or 6 times

[crash-2017-11-28_19.45.45-client.txt](https://github.com/Minecolonies/minecolonies/files/1512225/crash-2017-11-28_19.45.45-client.txt)

**Comment by Raycoms** [comment]
Please use the alpha or beta or use an older forge version
