### ISSUE TITLE
Display Mine Shaft Y Levels - Enhancement

### ISSUE THREAD

**Issue by descention** [ldtteam/minecolonies#1725]
I'd like to propose an enhancement to the Miner's Hut. On the interface where you can select a specific platform for the miner to dig, display the Y level of the platform. This would assist in gathering materials from certain Y level ranges without going down into the mine shaft. Displaying the depth of the level beside the Node count would be useful.

**Comment by Wissi** [comment]
I agree if we can have the "Y" level of the node being displayed next to the node would be very helpful.
