### ISSUE TITLE
Crash when placing Town Hall

### ISSUE THREAD

**Issue by RoboCyclone** [ldtteam/minecolonies#1727]
### Minecolonies version

Curse 1.4.8

### Expected behavior

- Placing a Town Hall will create a new colony

### Actual behaviour

- Instantly disconnected from server with "A fatal error has occured, this connection has been terminated."

### Steps to reproduce the problem

This occurs in a custom made modpack for me and a few friends.
1. Friend crafts town hall, tries to place it, and gets kicked from the server.
2. As soon as anyone else tries to load the chunk the town hall was in, they are kicked as well. Seems as though some sort of UI is supposed to appear and it's not allowed to for some reason from what I can figure from the crash log. 

Relevant part of log (not a crashlog, as the client doesn't crash): https://pastebin.com/FF9D9mNd
Modlist: https://pastebin.com/G5xCmS6W
Full log (if it helps... relevant part taken from the bottom.): https://pastebin.com/ZUVppzwf

**Comment by RoboCyclone** [comment]
Should also note that deleting the colony with /mc colony delete fixes the issue, however no one is allowed to build anymore in the area the colony was supposed to occupy despite the colony supposedly being deleted.

**Comment by Asherslab** [comment]
Sorry. what's your Minecolonies version? and can you please update to the latest AFAIK we fixed that issue

**Comment by RoboCyclone** [comment]
Wow! Total brainfart, sorry. I was on version 0.8.4932 and just updated to 0.8.5290. Seems to have completely fixed the issue. Sorry for wasting your time!
