### ISSUE TITLE
Guard tower achievement lacks localization

### ISSUE THREAD

**Issue by ghost** [ldtteam/minecolonies#1729]
![minecolonies achievement localization issue](https://user-images.githubusercontent.com/25916106/33453615-99377c1e-d616-11e7-82d3-b96cd5192649.png)

**Modpack**: [The Simple Life 2](https://minecraft.curseforge.com/projects/the-simple-life-2-hqm), version 1.4 toast
**Minecraft version**: 1.10.2
**Forge version**: 12.18.3.2511
**Minecolonies version**: 0.8.4063

**Comment by Raycoms** [comment]
Will be fixed in the next updates. I think the newest alpha should have it already, thanks =)

**Comment by PapiDimmi** [comment]
Okay.

**Comment by ghost** [comment]
Okay. That was quick.
