### ISSUE TITLE
Miners don’t accurately tell you what they need

### ISSUE THREAD

**Issue by ghost** [ldtteam/minecolonies#1730]
My miner tells me that he needs one torch, one oak slab, one oak fence, etc., even though he needs more than just one.

**Modpack**: [The Simple Life 2](https://minecraft.curseforge.com/projects/the-simple-life-2-hqm), version 1.4 toast
**Minecraft version**: 1.10.2
**Forge version**: 12.18.3.2511
**Minecolonies version**: 0.8.4063

**Comment by Raycoms** [comment]
Duplicate: https://github.com/Minecolonies/minecolonies/issues/1096
