### ISSUE TITLE
ComputerCraft compatability issue

### ISSUE THREAD

**Issue by RoboCyclone** [ldtteam/minecolonies#1734]
### Minecolonies version

Version 0.8.5290

### Expected behavior

- ComputerCraft turtles will be able to mine/place blocks inside of my colony (or I will be able to add them as a trusted mod)

### Actual behaviour

- Attempting to use turtle.dig() or turtle.place() is returned with an error saying that it's not allowed to perform that action in this area.

### Steps to reproduce the problem

1. Create a colony
2. Place a turtle inside of it
3. Attempt to have the turtle perform actions (excavate, place, dig, etc.)

It would be nice to be able to add computercraft to my colony somehow in a similar vein to the way I can add players to my colony. I looked for an option like this in the config (for both ComputerCraft and MineColonies) and couldn't seem to find one (besides turning off protection entirely; which isn't a particularly good solution for the problem at hand in the long term).

**Comment by Asherslab** [comment]
The problem is that ComputerCraft turtles do not implement fake players correctly. that must be taken up with the Authors
