### ISSUE TITLE
Nearest town info not showing up on the debug screen

### ISSUE THREAD

**Issue by ghost** [ldtteam/minecolonies#1735]
![minecolonies f3](https://user-images.githubusercontent.com/25916106/33474685-f5e8063a-d67b-11e7-916b-09a3dc20cfe2.png)

**Modpack**: [The Simple Life 2](https://minecraft.curseforge.com/projects/the-simple-life-2-hqm), version 1.4 toast
**Minecraft version**: 1.10.2
**Forge version**: 12.18.3.2511
**Minecolonies version**: 0.8.4063

**Comment by Raycoms** [comment]
Duplicate

**Comment by ghost** [comment]
@Raycoms Of what?

**Comment by Raycoms** [comment]
Sorry, didn't have the time to search it, but there is already an issue about the f3 screen. We made a workaround with the /mc whereami command.
