### ISSUE TITLE
[Feature] Better lang files

### ISSUE THREAD

**Issue by marvin-bitterlich** [ldtteam/minecolonies#1736]
Our source strings in `default.lang` are of low quality.

Punctuation is inconsistent:
![image](https://user-images.githubusercontent.com/644950/33477169-fa40ecd4-d684-11e7-90ca-b990c08efcba.png)

Usage of parameters and : is inconsistent and hard to understand for translators:
![image](https://user-images.githubusercontent.com/644950/33477315-89746b10-d685-11e7-8712-90b9d7836915.png)

Some are really messed up:
![image](https://user-images.githubusercontent.com/644950/33477247-4bb520d0-d685-11e7-9e02-d0ce7d93d433.png)

What needs to be done here:

1. We need to define guidelines on how we address the players and what punctuation we use. 
2. We need to document these guidelines so new source strings have a guideline.
3. We need to clean up the source file to ensure all strings are consistent.

I will post this as an utopian task request with the category Translation, but this will require a pull request to the `translation` branch of this repo with a markdown file documenting the guidelines and a fix for our source strings,

I suggest you add a new folder [here](https://github.com/Minecolonies/minecolonies/tree/translation/documentation) and add a link to the document [here](https://github.com/Minecolonies/minecolonies/blob/translation/.github/CONTRIBUTING)

I offer one 100% vote (roughly $20) and a resteem for this completed task as an utopian contribution.

**Comment by Raycoms** [comment]
I'll close this because this would mess up crowdin completely
