### ISSUE TITLE
Problem with town hall

### ISSUE THREAD

**Issue by jona8a1** [ldtteam/minecolonies#1739]
### Minecolonies version

version 1.12.2-0.8.4932

### Expected behavior

- Create City Hall

### Actual behavior

- Sorry for the bad dramatics, I'm talking to the google translator
I have only installed this mod, none more. The problem is that when I put the city council out of the map and I loose an error: "a fatal error has occurred this connection is terminated"
From there he sends me to the initial menu and when I open the map again he hangs up and can only be closed with the task manager.
The mod worked a few days ago when I tested, and now that I wanted to play seriously it does not let me play without the bug.
### Steps to reproduce the problem

1. crear un mundo nuevo
2. colocar un ayuntamiento
3. Te saca del servidor interno (singleplayer)

**Comment by Asherslab** [comment]
Please update to the latest version, we fixed this :smile:

**Comment by jona8a1** [comment]
the version that I have is the last one that gives me in minecolonies.com

**Comment by Asherslab** [comment]
please refer to Curseforge for our latest builds instead, we're currently working on the downloads section on the website
