### ISSUE TITLE
Workers don’t retrieve food from the working station

### ISSUE THREAD

**Issue by ghost** [ldtteam/minecolonies#1740]
1. Put some food in a working station (sawmill, town hall, mine, etc.).
2. Wait for the worker to get hungry.
3. Watch the worker starve and yell at you, not picking up the food from the working station (or whatever they’re called).

**Modpack**: [The Simple Life 2](https://minecraft.curseforge.com/projects/the-simple-life-2-hqm), version 1.4 toast
**Minecraft version**: 1.10.2
**Forge version**: 12.18.3.2511
**Minecolonies version**: 0.8.4063

**Comment by Raycoms** [comment]
Yes this will only come in the game with the cook (Soon to be released)

**Comment by ghost** [comment]
Why? Wouldn’t it make sense for workers to get food from their own hut when they are hungry?

**Comment by Raycoms** [comment]
That's why the cook update will fix this.

**Comment by PapiDimmi** [comment]
I thought you meant you needed a new worker to do this.

**Comment by ghost** [comment]
I thought you meant you’d need a new worker to do this.

**Comment by Raycoms** [comment]
We will rework the food system almost completely to handle how workers get food. It will require a worker, to have it function completely (if you don't want to deliver them food manually to their worker chests)

**Comment by PapiDimmi** [comment]
Okay. That sounds pretty good.

**Comment by ghost** [comment]
Okay. That sounds pretty good. Will the 1.10.2 version be updated too?

**Comment by Raycoms** [comment]
Yes, we will support the 1.10 for a bit still.

2017-12-03 1:18 GMT+00:00 PapiDimmi <notifications@github.com>:

**Comment by ghost** [comment]
You’re the only mod dev who does this. Thanks!

**Comment by Raycoms** [comment]
I know, unfortunately

2017-12-03 1:20 GMT+00:00 PapiDimmi <notifications@github.com>:
