### ISSUE TITLE
[Suggestion] Guards should require arrows (unless they have a bow with Infinity)

### ISSUE THREAD

**Issue by ghost** [ldtteam/minecolonies#1741]

**Comment by tomtenberge** [comment]
seeing the hit/miss ratio of guards... i wouldn't say so, durability of the bow will be a pain enough.

**Comment by Asherslab** [comment]
I don't believe they should, they can fire over a stack in about 10 seconds. but only about 8 of those arrows will hit. (This would be a very high level archer). in reality we've balanced it for the purpose of not requiring arrows
