### ISSUE TITLE
Miners sometime stop mining; resolved by exiting and re-entering world

### ISSUE THREAD

**Issue by ghost** [ldtteam/minecolonies#1747]
I am playing a LAN server.

**Modpack**: [The Simple Life 2](https://minecraft.curseforge.com/projects/the-simple-life-2-hqm), version 1.4 toast
**Minecraft version**: 1.10.2
**Forge version**: 12.18.3.2511
**Minecolonies version**: 0.8.4063

**Comment by Raycoms** [comment]
Already have an issue for the miner as well

**Comment by ghost** [comment]
Link?
