### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by wilsondgonzales** [ldtteam/minecolonies#1748]
### Minecolonies version

1.12.2-0.8.5743
forge 14.23.1.2555
tried with old or new map

Still getting a crash upon worker assignment. https://paste.ee/p/07nHb

Steps

1. Drop town hall
2. Drop a builder
3. moment a worker gets hired, causes a crash

**Comment by wilsondgonzales** [comment]
no comment on this? :(

**Comment by wilsondgonzales** [comment]
with a bit more testing, i deleted the minecolonies folder in the save and deleted the config to start fresh and was able to work like normal. after turning on 'developer features' however, it caused a crash and the save was unable to load even with having a fresh config

**Comment by marchermans** [comment]
Yeah. There is an issue with forges networking changes. @Raycoms.

**Comment by Raycoms** [comment]
It should be fixed now =)
