### ISSUE TITLE
[Feature] [RS] Request simulation

### ISSUE THREAD

**Issue by marchermans** [ldtteam/minecolonies#1749]
As of writing the RS is not capable of handling simulations.
When we want playerrequesting to be a thing this is going to be a required feature.
On top of this, other assignment strategies might require some form of simulation to determine which Resolver gets the request assigned.

To achieve this certain components and elements have to be created or moved_
- [ ] Move the assigning hook into enum for assignmentstrategies.
- [ ] Remove the map access from the Handlers. Use methods on IStandardRequestManager instead.
- [ ] Create a SimulationRequestManager, which wraps two IStandardRequestManagers. The first holds the data up to this point. The second will collect all data produced by the simulation (to be seen as the simulation result). This simulation Manager will expose the data of both, however the data of the first is immutable.

This issue is made to keep track of progress and to collect and store ideas on this topic. Feel free to comment.

**Comment by Raycoms** [comment]
Closed in favor of joint issue.
