### ISSUE TITLE
Deliveryman Hut Level 3 instantly clears blocks above structure post-clearing step

### ISSUE THREAD

**Issue by descention** [ldtteam/minecolonies#1750]
### Minecolonies version

version 1.12.2-0.8.4832

### Expected behavior

- leave blocks above structure alone

### Actual behaviour

- post clearing phase, pre-torch placement, builder wiped out blocks above structure instantly
![cleared](https://user-images.githubusercontent.com/125809/33527813-162a9f0c-d825-11e7-888a-4a5fe72328e6.png)

### Steps to reproduce the problem

1. Build a level 1 or 2 birch deliveryman hut into a hill.
2. upgrade deliveryman hut to lvl 3
3. ...
4. Profit

**Comment by Justen-N** [comment]
this appears to be an issue with the scan, as it has included the air blocks above the building. This appears to be a custom hut, so it may be necessary to rescan the building without the air above. If it isn't custom, we will take a look at what's going on.

**Comment by Raycoms** [comment]
Yeah this is normal when the one who scanned the building didn't scan in
the upper part accordingly

**Comment by descention** [comment]
Would it make sense to programatically fix this by checking from top-most layer to bottom for an all air block level and removing it from the builder's work? Hitting any non-air block in the blueprint would stop the process. 

If this were done, then buildings built into the sides of hills would be able to be more progressive rather than clearing a huge hole into the hill for a small hut.

**Comment by Raycoms** [comment]
The problem with this is that we'd need to detect if nothing follows this air level anymore. (Might be stuff hovering around for example.

Not much we can do about it since we didn't plan on building the buildings inside walls.
When we rescan them eventually we will scan them more exactly in height.
