### ISSUE TITLE
[1.12.2] Crash in Construction Site

### ISSUE THREAD

**Issue by NielsPilgaard** [ldtteam/minecolonies#1751]
### Minecolonies version
minecolonies-universal-1.12.2-0.8.4832
version X.X.XXXX or curse X.X.XX

### Expected behavior
Cutting down a tree in an active construction site, results in items dropping and leaves despawning after all logs have been cleared.
### Actual behaviour
Hardcrash
https://pastebin.com/xLVjB84P

### Steps to reproduce the problem

1. Make a construction site
2. Chop down a tree inside said construction site
3. ...
4. Profit/crash

This issue is relayed from https://github.com/NillerMedDild/Enigmatica2/issues/1

**Comment by Raycoms** [comment]
Can you reproduce this error?

**Comment by Raycoms** [comment]
Fixed in the upcoming version (should only need a few minutes)

**Comment by NielsPilgaard** [comment]
Thank you!
Sorry I didn't answer whether I could reproduce the error, I was waiting for the original issue author to reply.
