### ISSUE TITLE
Suggestion - Snow - config to throw away

### ISSUE THREAD

**Issue by bob0bob** [ldtteam/minecolonies#1752]
Would be great have the option in the config file for the citizen to not collect snow.   If you are in an area where it snows a lot.   This is my experience.

I'm doing a very LARGE foot print tavern/inn.  Having the builder make it.  But it snows in this area.  So what ends up happening.  In the beginning of the day,  he goes out and collects the snow.   It fills up his inventory,  knowing he already has inventory for building the building.  So he goes back to his hut to unload the snow w/o laying anything down.   His hut chest doesn't have a ton of room, because it has items that is needed to build the building.   

He gets stuck waiting for room in the hut chest to unload the snow. only 16 perstack and he ends up with around 20 stacks (large area).   

Then goes backs to get more snow, because clearing is required before he can place one piece of material.   He ends up laying about 2 - 3 blocks per day.  Because at night,  it snows again.

Rinse and repeat.   I ended up with 3 - 4 chests in the warehouse just full of snow.

Would be great to have an option in the config file to not collect snow, or throw it away once collected.   It prevents the builder when building anything at all.    Its been 5 minecraft days and the builder has about 20 blocks laid down.

**Comment by Raycoms** [comment]
I think that would fit for this:
https://github.com/Minecolonies/minecolonies/issues/1635

Will close it in favor of that.
