### ISSUE TITLE
Lumberjacks won't chop oak logs

### ISSUE THREAD

**Issue by Imaninja32** [ldtteam/minecolonies#1753]
1.12 Minecolonies version

version X.X.XXXX or curse X.X.XX

### Expected behavior

- Chop oak

### Actual behaviour

- Don't chop oak

### Steps to reproduce the problem

1. Placed sawmill in middle of forest
2. Set to only chop oak
3. Don't chop any trees
4. Change setting to any tree but oak
5. Chop all other trees

**Comment by JoshHawley** [comment]
I'm seeing the same behavior. Running on a forge server though. Let me know if/which logs you want me to post, or if there is a debug mode or something else you want.

**Comment by blacksythe** [comment]
Had a similar likely related issue with birch set everything to off but birch, wont chop anything down

**Comment by Raycoms** [comment]
Yeah will have to analyze BOP saplings

2017-12-19 2:08 GMT+00:00 blacksythe <notifications@github.com>:
