### ISSUE TITLE
Exception in server tick loop - NoClassDefFoundError: net/minecraft/client/multiplayer/WorldClient

### ISSUE THREAD

**Issue by rckymtnrfc** [ldtteam/minecolonies#1756]
### Minecolonies version

minecolonies-universal-1.12.2-0.8.5805

### Expected behavior

- Not crashing server  (I didn't test on the client once it crashed the server on startup)

### Actual behaviour

- Crashing Server

### Steps to reproduce the problem

1. Install minecolonies-universal-1.12.2-0.8.5805
2. Launch Server
3. ...
4. Crash

https://pastebin.com/EeQjUuDE

**Comment by rckymtnrfc** [comment]
I should have mentioned I don't have this issue when I roll back to minecolonies-universal-1.12.2-0.8.5290.  I'm also on forge-1.12.2-14.23.1.2554-universal.

**Comment by Raycoms** [comment]
Will take a look at it, thanks for reporting it.

2017-12-04 20:11 GMT+00:00 rckymtnrfc <notifications@github.com>:

**Comment by Raycoms** [comment]
Fixed in the newest version
