### ISSUE TITLE
Crashing with minecolonies-universal-1.12.2-0.8.5805.jar

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [ldtteam/minecolonies#1757]
### Minecolonies version

minecolonies-universal-1.12.2-0.8.5805.jar

### Expected behavior

Not to crash?

### Actual behaviour

https://hastebin.com/owizodupog.cs

### Steps to reproduce the problem
No idea

**Comment by Raycoms** [comment]
Fixed in the newest version
