### ISSUE TITLE
Error. Internal server shuts down upon placing town hall.

### ISSUE THREAD

**Issue by jrowel20** [ldtteam/minecolonies#1759]
### Minecolonies version

version X.X.XXXX or curse X.X.XX

### Expected behavior

- XXX

### Server error. Internal server shuts down

- YYY

### Creative mode. Placing wooden town hall with build tool. click check mark and the game crashes.

Sidenote: best mod ever! My dream would be your team and MCA mod team coming together to create the best of both worlds. Any hope there could be a way to start a colony in survival without a ship? I never thought it was possible but thanks for making Minecraft more fun and interesting.

1. XYZ
2. ZYX
3. ...
4. Profit

**Comment by Eggonomicon** [comment]
Forge Version: 14.23.1.2555

Minecolonies version: 1.12.2-0.8.4932

When placing the town hall either directly or via wand you get kicked from the server and can not log back in.

This is repeatable every time.

**Comment by Raycoms** [comment]
Please use the newest minecolonies version or an older forge version (2529)
