### ISSUE TITLE
[1.12.2] Miner is not function correct

### ISSUE THREAD

**Issue by ghost** [ldtteam/minecolonies#1760]
### Minecolonies version
Forge-14.23.1.2559

minecolonies-universal-1.12.2-0.8.5805+

### Expected behavior

Miner should dig and mining as normal

### Actual behaviour

Miner went frozen at put cobblestone on ladder. however cobblestone is already in its inventory

### Steps to reproduce the problem

1. gives all items that miner needs.
2. watch he doing.
3. he went frozen (or doing nothing.)

Plus: Inside his inventory which has torches, cobblestone, wooden shovel, tinker's pickaxe, and ladder.

Logs Link
[fml-client-latest.log](https://github.com/Minecolonies/minecolonies/files/1529669/fml-client-latest.log)
[latest.log](https://github.com/Minecolonies/minecolonies/files/1529670/latest.log)

**Comment by Raycoms** [comment]
any log?

2017-12-05 1:39 GMT+00:00 Sagez <notifications@github.com>:

**Comment by ghost** [comment]
Updated: added my log but i seen some errors for other mods however it didnt crash my game.

**Comment by Raycoms** [comment]
does the request system tab show anything?

**Comment by ghost** [comment]
Nope just blank.
Edit: however i just go stick with minecolonies-universal-1.12.2-0.8.5743.jar for now.
I believe new inventory system breaks my game. Well, good luck to find the issue.

**Comment by ghost** [comment]
@Raycoms I tested with 5900 version with only vanilla minecraft of 1.12.2 this miner stalled at try plant cobblestone to make a ladder.

**Comment by Raycoms** [comment]
Yeah I created a fix, will merge it as soon as possible

2017-12-08 18:03 GMT+00:00 Sagez <notifications@github.com>:

**Comment by ghost** [comment]
thanks man..
