### ISSUE TITLE
Delivery guys - Stuck

### ISSUE THREAD

**Issue by bob0bob** [ldtteam/minecolonies#1762]
minecolonies-universal-
minecraft 1.12.2-
mine colonies 0.8.5810

All my delivery guys just stand there doing nothing.   Can't get them to move.   Most citizen appear to be doing their job,  Except all guards assigned to Barracks,  they are stuck in place also.

Tried recalling them to their hut.  Nothing changed.   Tried /mc colony refresh and no change.

**Comment by Raycoms** [comment]
can you provide a log?

**Comment by bob0bob** [comment]
Sure, when I get home I'll attach them.

**Comment by Raycoms** [comment]
Did you get the logs?

**Comment by bob0bob** [comment]
When I upgrade to 5875.  from upgrading from 5290,  it worked just fine.  Everyone is working like they should.

**Comment by bob0bob** [comment]
Spoke to soon,  Builders and d-man are stuck.  Its the middle of the night and they are still not moving.

My 2-dman are stuck in the warehouse.

https://github.com/Minecolonies/minecolonies/issues?q=is%3Aissue+author%3Abob0bob

**Comment by bob0bob** [comment]
Ok.   To unlock them for me.  This worked. 

I just did the command to respawn the citizen.   They started moving and working at that point.  I''ll let you know if it happens again.  Could be just the old status compare to the new status (assuming) of the new request system causing an issue.

**Comment by bob0bob** [comment]
They worked until dark.  Then froze.  already anyone went back to their citizen hut.  They just stood there all night.
![2017-12-05_19 33 55](https://user-images.githubusercontent.com/30982580/33640587-05c72008-d9f7-11e7-9418-ba56e55e7d3e.png)

**Comment by bob0bob** [comment]
Okay.  They work during the day and they definitely get stuck at night.  They just stand there and do not go back to through assigned citizen hut.  I do have a couple workers that do.  Can't tell why a few vs. most not.  I have 20 citizen. 8 guard and rest are citizens.  I can find 3 in huts only at night.

**Comment by Raycoms** [comment]
Fixed in the upcoming version (should only need a few minutes)
