### ISSUE TITLE
Lots of crashing on 1.12.2-0.8.5810

### ISSUE THREAD

**Issue by MattBeard** [ldtteam/minecolonies#1765]
### Minecolonies version

version 1.12.2-0.8.5810

### Expected behavior

- Should be stable

### Actual behaviour

- Frequent crashing (about every 15 or 20 minutes)

### Steps to reproduce the problem

1. Install version 1.12.2-0.8.5810
2. Build up a reasonable sized colony
3. Ply for a while
4. Bang!

[crash-2017-12-05_16.10.43-server.txt](https://github.com/Minecolonies/minecolonies/files/1531945/crash-2017-12-05_16.10.43-server.txt)

**Comment by bob0bob** [comment]
Yep.  Don't think the alpha 5810 is really playable.   Have my guards just stand there asking for something.  My 2 d-man just stand and never move.
Half the guards, miners/lumber jack all those their weapons/axes (pickaxe/axe).   You can't give it to them either.
The new gui based on the Youtube window,  should have a  "Cancel" and a "Fulfill" button when you look at the request window to fulfill it.  Doesn't appear.  if you put those items in their inventory.  Nothing happens and the request is never filled.

Do we need to delete our config file and allow it to create a new one?   On the youtube video for the request talks about a new option in the config that is related to this new request system.   Would that have something to do with it?

**Comment by Raycoms** [comment]
Fixed it, will be merged in a bit.

**Comment by MattBeard** [comment]
Cool - I don't see all the same issues, but my guards (from my barracks at least) are only going one or two stops along the patrol route, then stopping and getting confused a bit before returning!

**Comment by Raycoms** [comment]
Yeah the latest version has a ton of new stuff and we have to balance it out completely first, reporting those bugs makes it way faster

**Comment by Raycoms** [comment]
@bob0bob can you re-report those errors, since this error here has been fixed.

**Comment by bob0bob** [comment]
sure no problem.
