### ISSUE TITLE
Crash when right clicking builder

### ISSUE THREAD

**Issue by jasmine2785** [ldtteam/minecolonies#1769]
### Minecolonies version

version 1.12.2-0.8.5875

### Expected behavior

- Opens builder GUI/inventory

### Actual behaviour

- client side crash, but server does not crash

### Steps to reproduce the problem

Right click on builder

Note = i am using direwolf 1.12 from curse and just added minecolonies to it.

crash report 
https://pastebin.com/Jj9RMUpz

**Comment by Raycoms** [comment]
will take a look at it right after dinner

**Comment by Raycoms** [comment]
Fixed in the upcoming version (should only need a few minutes)
