### ISSUE TITLE
Guards won't follow patrol points correctly

### ISSUE THREAD

**Issue by MattBeard** [ldtteam/minecolonies#1770]
### Minecolonies version

version 1.12.2-0.8.5875

### Expected behavior

- Guards should follow set patrol points

### Actual behaviour

- Guards from a tower or barracks will follow some patrol points, but stop when they take them further away - not matching beyond the range that you can set points, and not matching the town border (though seems perhaps related)

### Steps to reproduce the problem

1. Build tower and/or barracks
2. Set manual patrol points all over the town
3. Watch which ones they obey

**Comment by Raycoms** [comment]
Might it be too far from the building, depending on its level?

2017-12-05 22:02 GMT+00:00 MattBeard <notifications@github.com>:

**Comment by MattBeard** [comment]
No, firstly the patrol points are set rather than rejected, and secondly the invisible border seems to be the same for different towers!

**Comment by Raycoms** [comment]
They don't pass the colony border, might that be it?

**Comment by MattBeard** [comment]
The border shown with the build tool does not match where they won't go

**Comment by Raycoms** [comment]
did you change the config of the town range since you created the colony?

2017-12-05 22:25 GMT+00:00 MattBeard <notifications@github.com>:

**Comment by MattBeard** [comment]
Nope

**Comment by Raycoms** [comment]
Is there a way to reproduce this? Or can you send us the world and exactly
what happens

2017-12-05 22:27 GMT+00:00 MattBeard <notifications@github.com>:

**Comment by MattBeard** [comment]
The world is about 50Mb - Can that be uploaded here?

**Comment by Raycoms** [comment]
can you just delete the other regions?

2017-12-05 22:30 GMT+00:00 MattBeard <notifications@github.com>:

**Comment by MattBeard** [comment]
The data is here: https://www.dropbox.com/s/4ske70wpj2t1o4z/Second%20Colony.zip?dl=0

It is a sprawling mess as it is basically a whole load of experiments!

The best thing to try is to get guards from the barracks in the north to go through the tunnel to the North. They stop way before the border.

Also, it's a pain the guards can't go a little way beyond the border!

**Comment by Raycoms** [comment]
They're not going through the tunnel you mean?

(And yes, we're planning on extending them outside of the border).

2017-12-05 22:53 GMT+00:00 MattBeard <notifications@github.com>:

**Comment by MattBeard** [comment]
They go about 4 or 5 blocks along it, then stand there looking confused.

The border is about one block to the north of the other end of the tunnel

**Comment by Raycoms** [comment]
Couldn't reproduce this. Is this still an issue?
