### ISSUE TITLE
Suggestion - New request system.  Faster filling.

### ISSUE THREAD

**Issue by bob0bob** [ldtteam/minecolonies#1772]
minecraft 1.12
mine colonies 0.8.5875

If you notice the builder standing their doing nothing.  You click on him and see he has a request.  Lets say 64 oak slabs.   YOu have the GREAT NEW FEATURE "fulfill".  You click on that.

Here is teh suggestion.

Instead of when you click on 'Fulfill",  it doesn't put the slabs in the builder's hut.  Since you are standing their.  Why not just hand it to the builder.  The function puts it in the builder's hut and he has to go back the hut to get it even though you click on him to fulfill the request.

If it will not be easy, completely understand.  Sometimes you can't do what seems simple.

Would save time.

**Comment by Raycoms** [comment]
Fixed in the upcoming version (should only need a few minutes)
