### ISSUE TITLE
Right click on - clipboard - crash

### ISSUE THREAD

**Issue by bob0bob** [ldtteam/minecolonies#1773]
minecraft 1.12.2
mine colonies 0.8.5875

Not sure how to duplicate this.   I had been using the clipboard for about 20 mins,  and one time I right click on it to see who needed the bow I was bringing and it crashed.
[crash-2017-12-05_19.58.09-client.txt](https://github.com/Minecolonies/minecolonies/files/1533599/crash-2017-12-05_19.58.09-client.txt)

**Comment by Raycoms** [comment]
Fixed in the upcoming version (should only need a few minutes)

**Comment by Nattehine** [comment]
I just experienced this issue on a LAN server, mod version 0.8.8026. We're using a modpack called World of Dragons if that matters at all.
Here's the crash log:
https://pastebin.com/czhDWxhx
