### ISSUE TITLE
Food Delivery 1.12 - only partial port

### ISSUE THREAD

**Issue by bob0bob** [ldtteam/minecolonies#1774]
mine craft 1.12.2
mine colonies 0.8.5875

It appears that part of the new food delivery got ported over to 1.12.2 but not all of it.   D-man are not delivering food anymore.   The citizen are requiring food or a restaurant.  But the restaurant is not implemented fully.  The block appears to be in it, no recipe.  Doesn't appear to be schematics either.

**Comment by wilsondgonzales** [comment]
i saw a restaurant under 'decorations/birch' schematics

**Comment by Raycoms** [comment]
I forgot the 1.12 recipe, my bad

**Comment by Raycoms** [comment]
Fixed in the upcoming version (should only need a few minutes)
