### ISSUE TITLE
Any hints on how the new request system works?

### ISSUE THREAD

**Issue by MattBeard** [ldtteam/minecolonies#1775]
### Minecolonies version

version 1.12.2-0.8.5875

### Expected behavior

- No idea!

### Actual behaviour

- Deliverymen are now standing at the warehouse chest in state "Dumping" and various other citizens are stuck waiting for items

### Steps to reproduce the problem

n/a

So, I have no idea how this is supposed to work. I have seen mention of "clipboard" and I see details about delivery priority and I also see details of any items citizens require, but I have no idea how to make any of it work!

Can someone write one or two paragraphs just explaining what is supposed to be going on?

**Comment by Raycoms** [comment]
Can you show us the log to this?

**Comment by MattBeard** [comment]
? I'm confused.
Is it supposed to be behaving differently?
What log files do you need?
Do you want me to try anything specific before collecting the logs (like firing and re-hiring the deliverymen)?

**Comment by Raycoms** [comment]
The dman isn't supposed to be stuck there. I need the logs of what happens while he is "dumping" there.

**Comment by MattBeard** [comment]
[latest.log](https://github.com/Minecolonies/minecolonies/files/1535381/latest.log)
This looks significant - there are lots of errors in the deliveryman handling it seems

**Comment by Raycoms** [comment]
Is there a way to send us your world?

2017-12-06 13:59 GMT+00:00 MattBeard <notifications@github.com>:

**Comment by MattBeard** [comment]
Same world I uploaded yesterday for the guard issue

**Comment by Raycoms** [comment]
ok, we will analyze it

2017-12-06 14:01 GMT+00:00 MattBeard <notifications@github.com>:

**Comment by Raycoms** [comment]
Do you have a "backup" before you updated to 5875?

2017-12-06 14:04 GMT+00:00 Ray Neiheiser <ray.neiheiser@gmail.com>:

**Comment by MattBeard** [comment]
I have a few backups over the past few days, but I have done quite a bit on 5875 so it would be sad to revert

**Comment by Raycoms** [comment]
No, we don't want you to revert, it, could we have the "newest" backup so
we can test it with the 5875 from "scratch" to see what happens when
converting the world to the requet-system.

2017-12-06 14:16 GMT+00:00 MattBeard <notifications@github.com>:

**Comment by MattBeard** [comment]
Would 5743 be fine?

https://www.dropbox.com/s/8nlo5t64fuklw3f/Second%20Colony-5743.zip?dl=0

(Uploaded now)

**Comment by Raycoms** [comment]
before the request system, not sure when we started that =D before things
started to go wrong

2017-12-06 14:32 GMT+00:00 MattBeard <notifications@github.com>:

**Comment by Raycoms** [comment]
Fixed in the upcoming version (should only need a few minutes)

**Comment by MattBeard** [comment]
(Happy-Dance)
