### ISSUE TITLE
birch schematics

### ISSUE THREAD

**Issue by wilsondgonzales** [ldtteam/minecolonies#1776]
### Minecolonies version

minecolonies-universal-1.12.2-0.8.5875.jar

the birch stairs and wall is actually the opposite of one another.

**Comment by Raycoms** [comment]
what?

**Comment by wilsondgonzales** [comment]
schematics for birch-wall is loading up the schematic for what would be birch-stairs
schematics for birch-stairs is loading up the schematic for what would be birch-wall 

i come to this conclusion because the schematic for birch-wall shows stairs leading up to the top of the structure while the stairs schematic has no stairs
