### ISSUE TITLE
Right click on Baker - Crash

### ISSUE THREAD

**Issue by Discomanco** [ldtteam/minecolonies#1778]
### Minecolonies version

version 0.8.5875

### Expected behavior

- Open GUI

### Actual behaviour

- Crashing client

### Steps to reproduce the problem

1. Right click your Baker
2. "huh I froze?"
3. ...
4. Profit

https://pastebin.com/9rSt9wx9

**Comment by Raycoms** [comment]
We're working on this, it's same bug for each worker =)
No need to report them for each one.

**Comment by Discomanco** [comment]
Well what do I know :P I just saw the bug for the guards and builder.
And the builder is working fine for me, so there's that

**Comment by Raycoms** [comment]
Yeah it's just bad luck, I have the fix ready, just needs to be merged =)

2017-12-06 11:18 GMT+00:00 Icebear <notifications@github.com>:

**Comment by Discomanco** [comment]
Sweet!
