### ISSUE TITLE
[Suggestion] Rack and Inventory Tweaks

### ISSUE THREAD

**Issue by Discomanco** [ldtteam/minecolonies#1780]
Currently you can not sort Racks with Inventory Tweaks.
Suggesting support!

also JEI overlaps with the Double Racks
https://i.gyazo.com/b373b16f4b05fc016e7ee61118e8d4cb.png

**Comment by Raycoms** [comment]
About the overlap we can't do much there atm since we need the size and implementing it scrollable would be too much work atm.

That racks don't get sorted with inventory tweaks should be fixed on their site since we implement a normal itemHandler, it should work well.

**Comment by Discomanco** [comment]
Alright, I will report it to InvTweaks then

As for the overlap, there are ways to bend JEI around the UI, although I don't know how. But Thermal does it. https://i.gyazo.com/1172a36a0ff1d816aa9ac581b5159093.png
