### ISSUE TITLE
Build Not Working

### ISSUE THREAD

**Issue by Ph4i1ur3** [ldtteam/minecolonies#1782]
I'm pulling from the version/1.12 branch

I'm following the Readme on compiling it (headless Ubuntu)

The file(s) that get built all have this file name:
minecolonies-universal-1.12.2-0.8.null.jar
(Notice the null)

I'm not sure what I'm doing wrong
The JDK is up to date, as is Gradle (from the Ubuntu repos)

The jar file loads into Minecraft fine, but the supply ship doesn't make a box.

(I would upload any log files if I knew where they were, if you can tell me I'll gladly upload them)

**Comment by Raycoms** [comment]
Hi there, this seems right to me, the name only gets inserted when it's
built on our teamCity build servers.
What do you mean with the supplyship doesn't make a box? You have to be in
gamemode 0 for it to place the chest, and it will be placed on the ship now.

2017-12-06 21:24 GMT+00:00 Ph4i1ur3 <notifications@github.com>:

**Comment by Ph4i1ur3** [comment]
Ah, Okay. Thank you. Due to the changes correct information can be hard to find!

**Comment by Raycoms** [comment]
Yeah no worries, we're working on a new Wiki right at the moment.

2017-12-06 21:56 GMT+00:00 Ph4i1ur3 <notifications@github.com>:
