### ISSUE TITLE
Deliverymen still getting stuck in 5900

### ISSUE THREAD

**Issue by MattBeard** [ldtteam/minecolonies#1783]
### Minecolonies version

version 1.12.2-0.8.5900

### Expected behavior

- Deliverymen should work more-or-less continually

### Actual behaviour

- Get stuck in the warehouse in state "dumping" but sometimes move again

### Steps to reproduce the problem

1. Warehouse with 1 or more DMan
2. Get them busy
3. Watch them fail ;-(

[latest.log](https://github.com/Minecolonies/minecolonies/files/1537147/latest.log)

**Comment by Raycoms** [comment]
I will work on this tomorrow morning first thing =D

2017-12-06 22:52 GMT+00:00 MattBeard <notifications@github.com>:

**Comment by polikarpov5** [comment]
Me too, i have a SMP

**Comment by Raycoms** [comment]
@MattBeard can you please test it with:
https://s3.eu-central-1.amazonaws.com/minecolonies/Minecolonies/Minecolonies_Branches/5915/minecolonies-universal-1.12.2-0.8.5915.jar

And send us your log?

**Comment by Raycoms** [comment]
This will "allow the dman to move" but it should throw a lot of stuff in the log we will need to fix this for real

**Comment by MattBeard** [comment]
Just the same I'm afraid!

[latest.log](https://github.com/Minecolonies/minecolonies/files/1539418/latest.log)

**Comment by MattBeard** [comment]
Both deliverymen (women in this case) started by doing a little work, but within a minute Margaret stopped, then a little later Lena. Margaret said she was starving (a new sound file!) so I gave her some apples, which took her health up to full. Not sure why she didn't use the restaurant!

**Comment by Raycoms** [comment]
Hi, can you turn the request system logging in the minecolonies
configuration file and create another log with that?

2017-12-07 14:27 GMT+00:00 MattBeard <notifications@github.com>:

**Comment by MattBeard** [comment]
Big log, so I zipped it

[latest.zip](https://github.com/Minecolonies/minecolonies/files/1539766/latest.zip)

**Comment by Raycoms** [comment]
https://s3.eu-central-1.amazonaws.com/minecolonies/Minecolonies/Minecolonies_Branches/5922/minecolonies-universal-1.12.2-0.8.5922.jar

**Comment by Raycoms** [comment]
And this?

**Comment by bob0bob** [comment]
I'm using the 5922.   The d-man are working just fine.   They can appear to be stuck and just standing there.  But figured out it is food related.   If no restuarant they just stand there.  there is not chat message.  If restuarant they will go there and stand.

**Comment by marchermans** [comment]
@MattBeard I have been Debugging this for you last night.
I took your world and loaded it My debug System. And now i Need some Information. When did you create this world? For which Version? Did you load a test Version of the RS before the original release of the RS into it?

**Comment by MattBeard** [comment]
I have run with 5922 for a MC day or so with RS logging on. The deliverymen are working better, but they do not seem to be working right. One interesting thing was that a couple of times I got a message from my fisherman asking for a rod. I no longer have a fisherman - she was retasked as a guard a few days back!!
[latest-5922-log.zip](https://github.com/Minecolonies/minecolonies/files/1542481/latest-5922-log.zip)

**Comment by MattBeard** [comment]
The world was created 17th November I think, with the most up-to-date alpha at that time. I have kept the mod reasonably high on the alpha head.

**Comment by Raycoms** [comment]
Should be fixed in the newest version, should be on curse in a few minutes
