### ISSUE TITLE
Crashes Client on Server when placing TH

### ISSUE THREAD

**Issue by iInjection** [ldtteam/minecolonies#1791]
### Minecolonies version

curse 0.8.4932

### Expected behavior

- Spawning The Townhall Borders with the Colonists

### Actual behaviour

- while spawning the TH with the Building Rod, every PLayer in Rendering Range gets kicked and cannot rejoin until minecolonies and the playerdata is removed from the worlds directory.

### Steps to reproduce the problem

1. Spawning the TH Ship
2. Configuring the TH with the Wand, (wood, t1)
3. Client Crashes immediatly.

Modpack: https://www.curseforge.com/minecraft/modpacks/colonial-builders-reloaded

**Comment by Raycoms** [comment]
You have to use the newest minecolonies version or forge 2529- to avoid
this. (Latest minecolonies versions have a fix for this)

2017-12-07 20:47 GMT+00:00 iInjection <notifications@github.com>:

**Comment by iInjection** [comment]
so either forge 2529 or new Minecolonies-Version... My Problem is that I cant use the "newer" versions since it is not uploaded on Twitch... Can you do me a favor and put it on twitch-curse? I would be so grateful... (project starts @6pm GMT+1...)

**Comment by Raycoms** [comment]
There are a ton of alphas on twitch, maybe even the newest beta fixes it
