### ISSUE TITLE
Clipboard -  doesn't work

### ISSUE THREAD

**Issue by bob0bob** [ldtteam/minecolonies#1793]
minecraft1.12.2
mine colonies 0.8.5900 or 8.5922

No recipe in .5900
recipe in .5922  but when you right click with the clipboard nothing happens.  It says to right click on colony to register it.  When you hold shift and right click nothing happens.  I've tried every where in the colony?  Where are you suppose to right click

**Comment by bob0bob** [comment]
Screen shot of the right click.   If I hold the shift down in the town hall build nothing.  Tried right click with shift on the town hall block.  nothing.

![2017-12-07_22 25 08](https://user-images.githubusercontent.com/30982580/33751027-87ceeef8-db9d-11e7-9eeb-f1b2f802a373.png)

**Comment by marchermans** [comment]
Shift right click on any colony building.

**Comment by bob0bob** [comment]
Ok.  sneak+right click worked for me.
