### ISSUE TITLE
Citizen - food

### ISSUE THREAD

**Issue by bob0bob** [ldtteam/minecolonies#1795]
minecraft 1.12.2
mine colonies. 8.5900  8.5922

I'm seeing many citizen just standing around,  also wondering.    I was thinking it was this new request.

But now, I'm thinking it is the new food delivery/request system.

I put down a restuarant.  Now I'm seeing citizens standing at the restuarant block.  I don't have a restaurant build.  its in the queue.

ISSUE:    There is no display in the chat anymore that a citizen is starving and needs food.  We need to log in the chat to see that.   It took me a while to figure that out.  Because the citizen standing at the restaurant block was a builder.  He was assigned to building the restuarant.  So it never dawn on me.  THe other citizen that was standing their was d-man.  Thought it was something related to the builder.

**Comment by marchermans** [comment]
We want to give you as much Information as possible.
But this is not the RS that is causing the issue, but the new Food System.

You NEED a Restaurant or provide the FOOD yourself.
The RS is never used to get food. Every hungry citizen goes to the Restaurant to get it. If you do not have it build. Give the builder, and the DMan some food yourself
Which should solve the issue.

**Comment by Raycoms** [comment]
I will work at that today though

2017-12-08 9:37 GMT+00:00 Marc Hermans <notifications@github.com>:

**Comment by bob0bob** [comment]
OrionDevelopment -   the comment was until you have a restuarant that you do not know if citizen needs food.  There is no more comments in the chat window.   Only option is to check it all the time,  or notice someone standing around or i guess die(is that an option). 

I understand no need for chat window since they are suppose to go to the cook.  But until you have a cook!   the player has no clue.    I doubt many people in the start will build a cook to feed people.  
Maybe display chat until you detect a restaurant?

**Comment by Raycoms** [comment]
Fixed this.

2017-12-08 17:51 GMT+00:00 bob0bob <notifications@github.com>:
