### ISSUE TITLE
Deliverymen and worker behavior

### ISSUE THREAD

**Issue by wilsondgonzales** [ldtteam/minecolonies#1798]
### Minecolonies version

1.12.2-0.8.5922

- Baker
needs to double check their chests. Had a baker requesting wheat that was delivered to his chest but kept on requesting it. Started working after i personally took it out of the chest and placed it in their inventory

- Cook
Says he's 'start working' but does nothing. after a night, he stays by the citizen's hut in that state

- Delivery men
Seems to only do 1 round of work then gets stuck in a 'dumping' state by the warehouse. Naturally all requests get ignored. Good thing is it seems to refresh their state after a night.

- Minor bug. It caused a crash when i clicked the list icon beside any request entry for the workers

**Comment by Raycoms** [comment]
Will release a bugfix pr later today for a lot of those issues.
The cook only works if he gets food and fuel (but he should request those).

2017-12-08 12:23 GMT+00:00 Wilson Gonzales <notifications@github.com>:

**Comment by wilsondgonzales** [comment]
Update on 5930 @Raycoms 

- Baker
Gets stuck on a 'preparing' phase

- Cook
Seems to get stuck on his 'start working' phase but does nothing

- delivery men (i have 2)
Does quite a bit of 'gathering phases', no deliveries, and eventually gets into a 'dumping' phase. I've noticed that it's usually 4pm in-game that they get into this 'dumping' phase

- Lumberjack
Same with baker, gets stuck on a 'preparing' phase. Also he gets into trouble and searches for trees while he's in the citizen's hut. if possible, he should check for trees once he goes back to his hut as the hut will be mostly situated closer to the trees

- minor bugs
* right click crash on clipboard (i don't know what it's for tho)
* schematics for birch walls and birch stairs still needs to be switched

**Comment by Raycoms** [comment]
To the baker, Cook and Lumberjack do they have all what they need? Or don't
they request correctly?

2017-12-08 20:13 GMT+00:00 Wilson Gonzales <notifications@github.com>:

**Comment by wilsondgonzales** [comment]
they don't have requests. nor do they show 'needs item' on their name via developer feature option

**Comment by Raycoms** [comment]
Please try: https://s3.eu-central-1.amazonaws.com/minecolonies/Minecolonies/Minecolonies_Branches/5941/minecolonies-universal-1.12.2-0.8.5941.jar

**Comment by wilsondgonzales** [comment]
@Raycoms for 5941

- Baker
Gets stuck in a preparing state, no requests pending. After a couple of night cycles, starts the day with the 'kneading' state but eventually gets stuck

- Farmer
gets stuck requesting 1 seed when other tasks could be done (he is managing more than 1 crop). when all requests are fulfilled, goes into a very fast alternating 'preparing-harvesting' loop but he actually doesn't even move

- Lumberjack
this guy is working perfectly

- Cook
Started working and serving food but eventually gets stuck in a 'start working' state

- Delivery guys
sigh....these guys don't deliver, gather a bit. gets stuck in a 'dumping' state still

**Comment by marchermans** [comment]
Fixed most of the errored behaviour in an upcoming PR

**Comment by wilsondgonzales** [comment]
looking forward then. 👍
