### ISSUE TITLE
clicking on builder's request system. = crash

### ISSUE THREAD

**Issue by bob0bob** [ldtteam/minecolonies#1799]
minecraft 1.12.2
minecolonies 8.5900

I went to the the builder he was standing at his hut like he needed something.   I right clicked on him and then clicked on "request".   It showed  "sprice fence" required.    The clipboard didn't show this.
Then I clicked on the button to show details on the "spruce fence" to see if it was coming from the warehouse.

Crashed when I clicked that.
The clipboard only showed "rack" as a request.
[crash-2017-12-08_11.43.07-client.txt](https://github.com/Minecolonies/minecolonies/files/1543442/crash-2017-12-08_11.43.07-client.txt)

**Comment by Raycoms** [comment]
It only shows it in the clipboard if the player should solve it. I will
take a look at it

2017-12-08 17:46 GMT+00:00 bob0bob <notifications@github.com>:

**Comment by Raycoms** [comment]
Please try: https://s3.eu-central-1.amazonaws.com/minecolonies/Minecolonies/Minecolonies_Branches/5941/minecolonies-universal-1.12.2-0.8.5941.jar

**Comment by bob0bob** [comment]
Ok thanks.   That did it for me.  I got everyone working again.  Guard/miners/lumberjack/fisherman  all working again. D-Man are working delivering stuff. Great job.......  Dedication is amazing.   Everyday you guys get  something out the door even though it is Alpha version and we all know  that means buggy.
