### ISSUE TITLE
That darned construction tape

### ISSUE THREAD

**Issue by MattBeard** [ldtteam/minecolonies#1800]
### Minecolonies version

version 1.12.2-0.8.5922

### Expected behavior

- When a build is finished it should all be removed

### Actual behaviour

- Much of it stays behind, especially if you have cleared any blocks yourself. This is especially a problem when you need to clear soil or trees away from the front of a building while it is being built to allow it to be used when built.

### Steps to reproduce the problem

1. Start building a building on uneven land
2. While this is going on clear blocks under the tape
3. When the building is done, see all the remaining tape
4. Spend ages clearing it by hand!

The clearing tape phase really needs to check all the space around the edge for tape, not just at ground level. Minor I know, but can be a real pain for uneven or very forested areas!

**Comment by TheOrionsun** [comment]
I have seen this too, however it has always been my fault. I tried to do the same as you describe and remove blocks that are under or around the tape and it ends up there when the build is done. Once I started prepping the town area and get a level area to build on it goes away. One time though I was removing blocks and kinda helping the builder, I just cleared the tape. Tape does not seam to be required for the build to work.

I do see there is an option in the mod settings (ingame) where you can set "builderPlaceConstructionTape" true (default). I changed it to false and tested with a building I needed upgraded and no Tape!

Hope this helps...

**Comment by Raycoms** [comment]
The issue is else we would have to scan too big of an area. it assumes it is as it was before and only the builder worked around it. Else only a bit stays behind you can easily remove by clicking on it =)

**Comment by ArodSnaux** [comment]
UPDATE: you can easily remove construction tape using the FILL command:

/fill ~-30 ~-2 ~-30 ~30 ~5 ~30 air 0 replace minecolonies:blockconstructiontape

...for example, will replace all builder tape in a 30-yard radius (ok, block)  of where you are standing. Cheats must be enabled of course in that world.
