### ISSUE TITLE
Right-clicking builder and fisherman

### ISSUE THREAD

**Issue by KToader** [ldtteam/minecolonies#1803]
### Minecolonies version
All The Mods3 Pack
minecolonies-universal-1.12.2-0.8.5875

### Expected behavior

Right-click builder or fisherman
Enter into menu for character

### Actual behaviour

Right-click builder or fisherman
Game Crashes, Server does not

### Steps to reproduce the problem

1. Right click builder or fisherman-anything or nothing in hand
2. Game crashes and closes
[crash-2017-12-08_16.56.00-client.txt](https://github.com/Minecolonies/minecolonies/files/1543937/crash-2017-12-08_16.56.00-client.txt)

**Comment by Raycoms** [comment]
Can you try the newest minecolonies?

2017-12-08 22:08 GMT+00:00 KToader <notifications@github.com>:

**Comment by Raycoms** [comment]
Please try: https://s3.eu-central-1.amazonaws.com/minecolonies/Minecolonies/Minecolonies_Branches/5941/minecolonies-universal-1.12.2-0.8.5941.jar
