### ISSUE TITLE
Guard just standing around.

### ISSUE THREAD

**Issue by bob0bob** [ldtteam/minecolonies#1804]
Mine Craft 1.12.2
Mine Colonies 0.8.5930

When I upgraded from 8.5922 the guard are just standing there doing nothing.   They appear in the state "Guard_Search_target".   All my guards are doing this,  some are set to "patrol auto", "patrol manual".
I even tried changing some to guard, follow and nothing changed.

Here is a short clip, showing that, and I tried to respawn the guards and nothing changed.

https://youtu.be/H7Q2sB_GzTA

**Comment by Raycoms** [comment]
I will debug this tomorrow morning already.

2017-12-08 23:08 GMT+00:00 bob0bob <notifications@github.com>:

**Comment by bob0bob** [comment]
Sorry,  did I put this in twice.  Very sorry.

**Comment by Raycoms** [comment]
Please try: https://s3.eu-central-1.amazonaws.com/minecolonies/Minecolonies/Minecolonies_Branches/5941/minecolonies-universal-1.12.2-0.8.5941.jar

**Comment by bob0bob** [comment]
Ok thanks.   That did it for me.  I got everyone working again.  Guard/miners/lumberjack/fisherman  all working again. D-Man are working delivering stuff. Great job.......  Dedication is amazing.   Everyday you guys get  something out the door even though it is Alpha version and we all know  that means buggy.
--
