### ISSUE TITLE
Request from a miner.  _ appears in a loop

### ISSUE THREAD

**Issue by bob0bob** [ldtteam/minecolonies#1805]
minecraft 1.12.2
minecolonies 0.8.5930

I have a miner that is stuck in "needs item".  If you click on his request gui this is what shows.

![2017-12-08_17 43 42](https://user-images.githubusercontent.com/30982580/33789644-c15d79e4-dc3f-11e7-8ea3-33700f6bea1d.png)

**Comment by bob0bob** [comment]
Also,  When you right click on the miner, the system because SO SLOW.  it takes if about 1 or more to display the request window when you click on it.

**Comment by Raycoms** [comment]
Please try: https://s3.eu-central-1.amazonaws.com/minecolonies/Minecolonies/Minecolonies_Branches/5941/minecolonies-universal-1.12.2-0.8.5941.jar

**Comment by bob0bob** [comment]
Ok thanks.   That did it for me.  I got everyone working again.  Guard/miners/lumberjack/fisherman  all working again.
D-Man are working delivering stuff.
Great job.......  Dedication is amazing.   Everyday you guys get something out the door even though it is Alpha version and we all know that means buggy.
