### ISSUE TITLE
[1.12.2-0.8.5930] multi-issue

### ISSUE THREAD

**Issue by ghost** [ldtteam/minecolonies#1806]
### Minecolonies version

minecolonies-universal-1.12.2-0.8.5930

WoodCutter = Pickup Axe then do nothing
https://puu.sh/yCrMJ/5d250002da.png

Builder = stalled at try pick up shovel for upgrade building (miner stone version 5) with item frame which is not on wall yet.

Farmer = Stalled as Prepare and Planting loop (No Request) (wooden Hoe 64 x Seeds)

Fisherman = Pickup Fish rod then doing nothing and voice goes crazy?.

Water Source (I am not sure this is good enough for Fisherman)
https://puu.sh/yCrL1/c3e7741b70.png

Guard = Request is broken. I tried give him wooden sword but nothing.
https://puu.sh/yCrLi/8ca176dc45.png

Logs
fml-client-latest.log
https://puu.sh/yCrX4/c9808d9989.log
Latest.log
https://puu.sh/yCsj6/e17e3c45cb.log

**Comment by tomtenberge** [comment]
i have the same problem with the fisherman, also same minecraft version
the fisherman says he needs a fishing rod, while it has 3, tried rehiring and everything

**Comment by Raycoms** [comment]
Please try: https://s3.eu-central-1.amazonaws.com/minecolonies/Minecolonies/Minecolonies_Branches/5941/minecolonies-universal-1.12.2-0.8.5941.jar

**Comment by Raycoms** [comment]
Should be fixed in the newest version, should be on curse in a few minutes
