### ISSUE TITLE
Huge FPS drops on Raiders announcement

### ISSUE THREAD

**Issue by Discomanco** [ldtteam/minecolonies#1808]
So I have a small colony, mostly level 5 buildings. I don't have Lumberjack, Fisher, Barracks or Guardtowers (using IE turrets to defend the colony).
Now I was working a bit away from the colony, when I got the chat message "Buckle up cowboy! There's some darn raiders commin' for you Tonight!", and suddenly my frames immediately dropped to around 2.
This was the 2nd time that happened, so I teleported myself out and started to mark where the "corrupt" area was (for data purposes). Approximately 130x130 blocks, not centered on me.
The issue disappeared after around 8-10mins
https://i.gyazo.com/c833d72caec51ac0ad4543fc8a41ceb2.png
The colony starts in the upper right corner of the picture.

Note: The triggered area is at y200, with the colony at y75

### Minecolonies version

version 0.8.5900, so may have been fixed

**Comment by Raycoms** [comment]
Does this still happen? If yes please reopen
