### ISSUE TITLE
Citizens not Sleeping

### ISSUE THREAD

**Issue by LazerusKI** [ldtteam/minecolonies#1809]
### Minecolonies version

version 1.12.2-0.8.5900

### Expected behavior

- NPC Sleeping at Night

### Actual behaviour

- NPC Walks to his house and just stands there

### Steps to reproduce the problem

Im using the Taiga houses. My builder constantly shows the "let me sleep" bubbly when i look at him, so i investigated him for a while.
Sometimes he walks around randomly, sometimes he finds his way to his house where he then opens the door...and thats it. 
Not to mention that usually the nights are skipped by players, so my citizens never actually get to sleep.

Would there be a way to disable the need for sleep in the config somehow?

**Comment by Raycoms** [comment]
Please try: https://s3.eu-central-1.amazonaws.com/minecolonies/Minecolonies/Minecolonies_Branches/5941/minecolonies-universal-1.12.2-0.8.5941.jar

**Comment by Raycoms** [comment]
Sorry, wrong comment, yeah, we actually plan on letting them sleep for real in the bed, but it involves some rendering things which get us a lot of work.

**Comment by LazerusKI** [comment]
is there a way to disable npc sleeping on a server completely then? maybe thats why they constatly show that they want to sleep

**Comment by Raycoms** [comment]
Actually they also show that they sleep if they have nothing to do since
they woke up.

**Comment by Raycoms** [comment]
Should be fixed in the newest version, should be on curse in a few minutes
