### ISSUE TITLE
Fisherman Bugged Talk

### ISSUE THREAD

**Issue by Largeboy31** [ldtteam/minecolonies#1810]
### Minecolonies version

minecolonies-universal-1.12.2-0.8.5930

### Expected behavior

Fisherman You have to keep talking

### Actual behaviour

Fisherman He keeps talking

**Comment by tomtenberge** [comment]
is the same issue as mentioned in issue #1806

**Comment by Raycoms** [comment]
Please try: https://s3.eu-central-1.amazonaws.com/minecolonies/Minecolonies/Minecolonies_Branches/5941/minecolonies-universal-1.12.2-0.8.5941.jar
