### ISSUE TITLE
Guard Bugged No Patrol

### ISSUE THREAD

**Issue by Largeboy31** [ldtteam/minecolonies#1811]
### Minecolonies version

minecolonies-universal-1.12.2-0.8.5930

### Expected behavior

Walking and patrolling

### Actual behaviour

Patrol is disabled

**Comment by Raycoms** [comment]
Please try: https://s3.eu-central-1.amazonaws.com/minecolonies/Minecolonies/Minecolonies_Branches/5941/minecolonies-universal-1.12.2-0.8.5941.jar

**Comment by yotthani** [comment]
fyi: having the same problem in minecolonies-universal-1.10.2-0.9.5938.jar
