### ISSUE TITLE
Fisherman Not Work And non-stop Talk

### ISSUE THREAD

**Issue by Largeboy31** [ldtteam/minecolonies#1812]
### Minecolonies version

minecolonies-universal-1.12.2-0.8.5930

### Expected behavior

Stop Talk

### Actual behaviour

Retard Talk non-stop

**Comment by Raycoms** [comment]
Please try: https://s3.eu-central-1.amazonaws.com/minecolonies/Minecolonies/Minecolonies_Branches/5941/minecolonies-universal-1.12.2-0.8.5941.jar

**Comment by Largeboy31** [comment]
thanks
