### ISSUE TITLE
Colonist Kill... Crashhhh

### ISSUE THREAD

**Issue by Largeboy31** [ldtteam/minecolonies#1813]
### Minecolonies version

minecolonies-universal-1.12.2-0.8.5930

### Expected behavior

Colonist killed in no crash wtf 

### Actual behaviour

a colonist killed

**Comment by Raycoms** [comment]
Please give us your log

**Comment by Largeboy31** [comment]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Quark-r1.3-117.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  HammerCoreCore (HammerCore-1.12.2-1.9.5.7.jar)
  SFRCore (SolarFluxReborn_1.12.2-3.42r.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  MovingWorldCore (movingworld-1.12-6.342-full.jar)
Contact their authors BEFORE contacting forge

// Sorry :(

Time: 12/9/17 8:55 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at com.minecolonies.coremod.colony.buildings.AbstractBuilding.lambda$cancelAllRequestsOfCitizen$18(AbstractBuilding.java:1509)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:408)
	at com.minecolonies.coremod.colony.buildings.AbstractBuilding.cancelAllRequestsOfCitizen(AbstractBuilding.java:1505)
	at com.minecolonies.coremod.colony.Colony.removeCitizen(Colony.java:1950)
	at com.minecolonies.coremod.entity.EntityCitizen.func_70645_a(EntityCitizen.java:746)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:1014)
	at com.minecolonies.coremod.entity.EntityCitizen.func_70097_a(EntityCitizen.java:692)
	at com.minecolonies.coremod.entity.ai.mobs.barbarians.EntityAIBarbarianAttackMelee.attack(EntityAIBarbarianAttackMelee.java:89)
	at com.minecolonies.coremod.entity.ai.mobs.barbarians.EntityAIBarbarianAttackMelee.func_75253_b(EntityAIBarbarianAttackMelee.java:56)
	at net.minecraft.entity.ai.EntityAITasks.func_75773_a(SourceFile:136)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:83)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:894)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2347)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:689)
	at net.minecraft.entity.monster.EntityMob.func_70636_d(EntityMob.java:45)
	at com.minecolonies.coremod.entity.ai.mobs.barbarians.AbstractEntityBarbarian.func_70636_d(AbstractEntityBarbarian.java:209)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2167)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:388)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:50)
	at net.minecraft.world.World.func_72866_a(World.java:1986)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:831)
	at net.minecraft.world.World.func_72870_g(World.java:1948)
	at net.minecraft.world.World.func_72939_s(World.java:1755)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:239)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.minecolonies.coremod.colony.buildings.AbstractBuilding.lambda$cancelAllRequestsOfCitizen$18(AbstractBuilding.java:1509)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:408)
	at com.minecolonies.coremod.colony.buildings.AbstractBuilding.cancelAllRequestsOfCitizen(AbstractBuilding.java:1505)
	at com.minecolonies.coremod.colony.Colony.removeCitizen(Colony.java:1950)
	at com.minecolonies.coremod.entity.EntityCitizen.func_70645_a(EntityCitizen.java:746)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:1014)
	at com.minecolonies.coremod.entity.EntityCitizen.func_70097_a(EntityCitizen.java:692)
	at com.minecolonies.coremod.entity.ai.mobs.barbarians.EntityAIBarbarianAttackMelee.attack(EntityAIBarbarianAttackMelee.java:89)
	at com.minecolonies.coremod.entity.ai.mobs.barbarians.EntityAIBarbarianAttackMelee.func_75253_b(EntityAIBarbarianAttackMelee.java:56)
	at net.minecraft.entity.ai.EntityAITasks.func_75773_a(SourceFile:136)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:83)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:894)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2347)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:689)
	at net.minecraft.entity.monster.EntityMob.func_70636_d(EntityMob.java:45)
	at com.minecolonies.coremod.entity.ai.mobs.barbarians.AbstractEntityBarbarian.func_70636_d(AbstractEntityBarbarian.java:209)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2167)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:388)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:50)
	at net.minecraft.world.World.func_72866_a(World.java:1986)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:831)
	at net.minecraft.world.World.func_72870_g(World.java:1948)

-- Entity being ticked --
Details:
	Entity Type: minecolonies:barbarian (com.minecolonies.coremod.entity.ai.mobs.barbarians.EntityBarbarian)
	Entity ID: 147597
	Entity Name: entity.Barbarian.name
	Entity's Exact location: 444.36, 63.00, 231.59
	Entity's Block location: World: (444,63,231), Chunk: (at 12,3,7 in 27,14; contains blocks 432,0,224 to 447,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.05, -0.08, -0.01
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1755)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)

-- Affected level --
Details:
	Level name: Kabileler
	All players: 1 total; [EntityPlayerMP['kral120'/498, l='Kabileler', x=458.21, y=62.94, z=258.34]]
	Chunk stats: ServerChunkCache: 759 Drop: 0
	Level seed: -1551809439795622503
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: {"diamondSize":8,"lapisCenterHeight":16,"lavaLakeChance":80,"redstoneMaxHeight":16,"diamondMaxHeight":16,"coalMaxHeight":128,"coalMinHeight":0,"seaLevel":63,"graniteCount":10,"riverSize":4,"gravelMinHeight":0,"graniteSize":33,"redstoneSize":8,"fixedBiome":-1,"waterLakeChance":4,"dioriteMinHeight":0,"andesiteCount":10,"graniteMaxHeight":80,"redstoneMinHeight":0,"lapisSize":7,"dirtCount":10,"ironMinHeight":0,"dioriteMaxHeight":80,"coalCount":20,"gravelCount":8,"coalSize":17,"gravelSize":33,"ironMaxHeight":64,"lapisSpread":16,"dioriteCount":10,"andesiteSize":33,"biomeSize":4,"graniteMinHeight":0,"goldCount":2,"diamondCount":1,"dirtSize":33,"gravelMaxHeight":256,"goldSize":9,"ironCount":20,"diamondMinHeight":0,"ironSize":9,"redstoneCount":8,"andesiteMinHeight":0,"dioriteSize":33,"goldMaxHeight":32,"dungeonChance":8,"andesiteMaxHeight":80,"dirtMinHeight":0,"lapisCount":1,"goldMinHeight":0,"dirtMaxHeight":256,"lowerLimitScale":512.0,"biomeDepthOffset":0.0,"upperLimitScale":512.0,"heightScale":684.412,"biomeScaleWeight":1.0,"biomeDepthWeight":1.0,"mainNoiseScaleZ":80.0,"mainNoiseScaleY":160.0,"depthNoiseScaleX":200.0,"mainNoiseScaleX":80.0,"baseSize":8.5,"depthNoiseScaleZ":200.0,"stretchY":12.0,"depthNoiseScaleExponent":0.5,"biomeScaleOffset":0.0,"coordinateScale":684.412,"useStrongholds":true,"useMineShafts":true,"useTemples":true,"useLavaOceans":false,"useCaves":true,"useWaterLakes":true,"useLavaLakes":true,"useMonuments":true,"useRavines":true,"useDungeons":true,"useVillages":true}
	Level spawn location: World: (188,64,224), Chunk: (at 12,4,0 in 11,14; contains blocks 176,0,224 to 191,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 372831 game time, 194142 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 22522 (now: false), thunder time: 80746 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:239)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_151, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1079030888 bytes (1029 MB) / 2562273280 bytes (2443 MB) up to 6429081600 bytes (6131 MB)
	JVM Flags: 5 total; -Xmx6144M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.1.2555 Optifine OptiFine_1.12.2_HD_U_C6 62 mods loaded, 61 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                                           | Version                  | Source                                          | Signature                                |
	|:--------- |:-------------------------------------------- |:------------------------ |:----------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft                                    | 1.12.2                   | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | mcp                                          | 9.42                     | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | FML                                          | 8.0.99.99                | forge-1.12.2-14.23.1.2555.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                                        | 14.23.1.2555             | forge-1.12.2-14.23.1.2555.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | ivtoolkit                                    | 1.3.3-1.12               | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | com.elytradev.movingworld.common.asm.coremod |                          | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | quark                                        | r1.3-117                 | Quark-r1.3-117.jar                              | None                                     |
	| UCHIJAAAA | autoreglib                                   | 1.3-15                   | AutoRegLib-1.3-15.jar                           | None                                     |
	| UCHIJAAAA | bibliocraft                                  | 2.4.3                    | BiblioCraft[v2.4.3][MC1.12.0].jar               | None                                     |
	| UCHIJAAAA | buildcraftlib                                | 7.99.12                  | buildcraft-7.99.12.jar                          | None                                     |
	| UCHIJAAAA | buildcraftcore                               | 7.99.12                  | buildcraft-7.99.12.jar                          | None                                     |
	| UCHIJAAAA | buildcraftbuilders                           | 7.99.12                  | buildcraft-7.99.12.jar                          | None                                     |
	| UCHIJAAAA | buildcraftenergy                             | 7.99.12                  | buildcraft-7.99.12.jar                          | None                                     |
	| UCHIJAAAA | buildcraftfactory                            | 7.99.12                  | buildcraft-7.99.12.jar                          | None                                     |
	| UCHIJAAAA | buildcraftrobotics                           | 7.99.12                  | buildcraft-7.99.12.jar                          | None                                     |
	| UCHIJAAAA | buildcraftsilicon                            | 7.99.12                  | buildcraft-7.99.12.jar                          | None                                     |
	| UCHIJAAAA | buildcrafttransport                          | 7.99.12                  | buildcraft-7.99.12.jar                          | None                                     |
	| UCHIJAAAA | redstoneflux                                 | 2.0.1                    | RedstoneFlux-1.12-2.0.1.2-universal.jar         | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCHIJAAAA | car                                          | 1.2.10                   | car-1.2.10.jar                                  | None                                     |
	| UCHIJAAAA | chameleon                                    | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                        | None                                     |
	| UCHIJAAAA | codechickenlib                               | 3.1.3.313                | CodeChickenLib-1.12-3.1.3.313-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | cofhcore                                     | 4.3.7                    | CoFHCore-1.12.2-4.3.7.24-universal.jar          | None                                     |
	| UCHIJAAAA | cofhworld                                    | 1.0.2                    | CoFHWorld-1.12.2-1.0.2.10-universal.jar         | None                                     |
	| UCHIJAAAA | movingworld                                  | 1.12-6.342               | movingworld-1.12-6.342-full.jar                 | None                                     |
	| UCHIJAAAA | davincisvessels                              | @DVESSELSVER@            | davincisvessels-1.12-6.340-full.jar             | None                                     |
	| UCHIJAAAA | energyconverters                             | 1.0.1.2                  | energyconverters_1.12.1-1.0.1.2.jar             | None                                     |
	| UCHIJAAAA | fastleafdecay                                | v14                      | FastLeafDecay-v14.jar                           | None                                     |
	| UCHIJAAAA | grapplemod                                   | 1.12-v10                 | grapplemod-1.12-v10.jar                         | None                                     |
	| UCHIJAAAA | hammercore                                   | 1.9.5.7                  | HammerCore-1.12.2-1.9.5.7.jar                   | None                                     |
	| UCHIJAAAA | waila                                        | 1.8.22                   | Hwyla-1.8.22-B37_1.12.jar                       | None                                     |
	| UCHIJAAAA | improvedbackpacks                            | 1.12-1.1.2.0             | ImprovedBackpacks-1.12-1.1.2.0.jar              | None                                     |
	| UCHIJAAAA | ic2                                          | 2.8.16-ex112             | industrialcraft-2-2.8.16-ex112.jar              | de041f9f6187debbc77034a344134053277aa3b0 |
	| UCHIJAAAA | lunatriuscore                                | 1.2.0.42                 | LunatriusCore-1.12.2-1.2.0.42-universal.jar     | None                                     |
	| UCHIJAAAA | ingameinfoxml                                | 2.8.2.94                 | InGameInfoXML-1.12.2-2.8.2.94-universal.jar     | None                                     |
	| UCHIJAAAA | inventorytweaks                              | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                        | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJAAAA | jei                                          | 4.8.0.114                | jei_1.12.2-4.8.0.114.jar                        | None                                     |
	| UCHIJAAAA | journeymap                                   | 1.12.2-5.5.2             | journeymap-1.12.2-5.5.2.jar                     | None                                     |
	| UCHIJAAAA | jeresources                                  | 0.8.5.27                 | JustEnoughResources-1.12.2-0.8.5.27.jar         | None                                     |
	| UCHIJAAAA | levelup2                                     | ${version}               | Level Up! 2-1.1.12-1.12.jar                     | None                                     |
	| UCHIJAAAA | mantle                                       | 1.12-1.3.1.21            | Mantle-1.12-1.3.1.21.jar                        | None                                     |
	| UCHIJAAAA | minecolonies                                 | 1.12.2-0.8.5930          | minecolonies-universal-1.12.2-0.8.5930.jar      | None                                     |
	| UCHIJAAAA | harvestcraft                                 | 1.12.2a                  | Pam's HarvestCraft 1.12.2a.jar                  | None                                     |
	| UCHIJAAAA | reccomplex                                   | 1.4.6                    | RecurrentComplex-1.4.6.jar                      | None                                     |
	| UCHIJAAAA | solarfluxreborn                              | 3.42r                    | SolarFluxReborn_1.12.2-3.42r.jar                | None                                     |
	| UCHIJAAAA | storagedrawers                               | 1.12-5.2.5               | StorageDrawers-1.12.1-5.3.3.jar                 | None                                     |
	| UCHIJAAAA | tconstruct                                   | 1.12-2.7.4.34            | TConstruct-1.12-2.7.4.34.jar                    | None                                     |
	| UCHIJAAAA | thermalfoundation                            | 2.3.7                    | ThermalFoundation-1.12.2-2.3.7.18-universal.jar | None                                     |
	| UCHIJAAAA | thermaldynamics                              | 2.3.7                    | ThermalDynamics-1.12.2-2.3.7.14-universal.jar   | None                                     |
	| UCHIJAAAA | thermalexpansion                             | 5.3.7                    | ThermalExpansion-1.12.2-5.3.7.27-universal.jar  | None                                     |
	| UCHIJAAAA | thutcore                                     | 5.12.2                   | thutcore-5.12.2.jar                             | None                                     |
	| UCHIJAAAA | thutcore_compat                              | 1.0                      | thutcore-5.12.2.jar                             | None                                     |
	| UCHIJAAAA | thuttech                                     | 6.0.8                    | thuttech-6.0.8.3.jar                            | None                                     |
	| UCHIJAAAA | tinkertoolleveling                           | 1.12-1.0.2b.DEV.1a79301  | TinkerToolLeveling-1.12-1.0.2b.jar              | None                                     |
	| UCHIJAAAA | twilightforest                               | 3.5.263                  | twilightforest-1.12.2-3.5.263-universal.jar     | None                                     |
	| UCHIJAAAA | veinminer                                    | 0.38.1                   | VeinMiner-1.12-0.38.1.639+134fb1e.jar           | None                                     |
	| UCHIJAAAA | veinminermodsupport                          | 0.38.1                   | VeinMiner-1.12-0.38.1.639+134fb1e.jar           | None                                     |
	| UCHIJAAAA | wailaharvestability                          | 1.1.12                   | WailaHarvestability-mc1.12-1.1.12.jar           | None                                     |
	| UCHIJAAAA | wanionlib                                    | 1.12.2-1.3               | WanionLib-1.12.2-1.3.jar                        | None                                     |
	| UCHIJAAAA | wawla                                        | 2.5.246                  | Wawla-1.12.2-2.5.246.jar                        | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | waystones                                    | 4.0.17                   | Waystones_1.12.1-4.0.17.jar                     | None                                     |
	| UCHIJAAAA | unidict                                      | 1.12.2-1.4               | UniDict-1.12.2-1.4.jar                          | None                                     |
	| UD        | solarfluxreborncore                          | 3.42r                    | minecraft.jar                                   | None                                     |

	Loaded coremods (and transformers): 
LoadingPlugin (Quark-r1.3-117.jar)
  vazkii.quark.base.asm.ClassTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
HammerCoreCore (HammerCore-1.12.2-1.9.5.7.jar)
  com.pengu.hammercore.asm.HammerCoreTransformer
SFRCore (SolarFluxReborn_1.12.2-3.42r.jar)
  com.pengu.solarfluxreborn.core.SFRSerializedTransformer
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
MovingWorldCore (movingworld-1.12-6.342-full.jar)
  
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- wailaIntegration (Enabled/Not Forced)

	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['kral120'/498, l='Kabileler', x=458.21, y=62.94, z=258.34]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_C6
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 388.59
	OpenGlRenderer: GeForce GTX 980M/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by marchermans** [comment]
Already fixed in an upcoming PR.

**Comment by Largeboy31** [comment]
thanks
