### ISSUE TITLE
Farmer Not Working

### ISSUE THREAD

**Issue by Largeboy31** [ldtteam/minecolonies#1814]
### Minecolonies version

minecolonies-universal-1.12.2-0.8.5930

### Expected behavior

Farmer not work?

### Actual behaviour

he does not go to the field and do not plant fields

**Comment by yotthani** [comment]
fyi: having the same problem in minecolonies-universal-1.10.2-0.9.5938.jar

**Comment by Raycoms** [comment]
Did you try: https://s3.eu-central-1.amazonaws.com/minecolonies/Minecolonies/Minecolonies_Branches/5941/minecolonies-universal-1.12.2-0.8.5941.jar 
?

**Comment by Moobien** [comment]
@Raycoms I just gave that version a go and now I can't even get into my world, even after rolling back to the version I was using.

**Comment by Largeboy31** [comment]
okey

**Comment by bob0bob** [comment]
Should not the function AbstractEntityAIBasic.checkForToolOrWeapon() return true if the tool is in inventory. Below::: But the check "if (checkForNeededTool(toolType, minimalLevel)) " in the function returns false (meaning the tool is in inventory). so the default return for the function says "FALSE". meaning you don't have the tool.... Seems like it just needs to switch around the two return types. It lets the farmer start working in my build.

The comments say

boolean com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic.checkForToolOrWeapon(@NotNull IToolType toolType)

Ensures that we have a appropriate tool available. Will set needsTool accordingly.
Parameters:toolType type of tool we check for.
Returns:true if we have the tool

**Comment by marchermans** [comment]
That is a javadoc error

**Comment by bob0bob** [comment]
Ok.  Yeah if that is a mistake then the functions calling this is messed up.   Because the function returns false   as saying citizen has a tool.  While calling function is counting on a true to indicate they have a tool.   So Based on what I read through the code. 


Based on the code.  The fisher many prepareForFishing()   it checks if the return is false then assumes the tool is missing.
Lumberjack is the same check if false then tool is not found.   

-So the comments of return true if we have tool appears to be correct.

**Comment by bob0bob** [comment]
Also,   prepareForFarming()  function is checking the states of the fields to see what is next to do.

there is a check

            else if (currentField.getFieldStage() == Field.FieldStage.HOED && !checkForToolOrWeapon(ToolType.HOE)) 

to tell it to go plant.   This check says if the player doesn't have a hoe then plant.  They will never plant a seed.

**Comment by marchermans** [comment]
Let me check

**Comment by marchermans** [comment]
I noticed. That check is in the wrong place isn't.

`if (currentField.getFieldStage() == Field.FieldStage.PLANTED && checkIfShouldExecute(currentField, this::shouldHarvest))
            {
                return FARMER_HARVEST;
            }
            else if (currentField.getFieldStage() == Field.FieldStage.HOED)
            {
                return canGoPlanting(currentField, building, true);
            }
            else if (currentField.getFieldStage() == Field.FieldStage.EMPTY && checkIfShouldExecute(currentField, this::shouldHoe))
            {
                return FARMER_HOE;
            }`

This should work.
The check for the HOE is in the workAtField method so it can be removed anyway.

**Comment by Largeboy31** [comment]
thanks guys

**Comment by bob0bob** [comment]
Should this issue not be closed?

**Comment by Raycoms** [comment]
Should be fixed in the newest version, should be on curse in a few minutes
