### ISSUE TITLE
Miner stuck - Requesting samething over and over

### ISSUE THREAD

**Issue by bob0bob** [ldtteam/minecolonies#1815]
mine craft 1.12.2
mine colonies 8.5941

Ok,  after about an hour of playing one of the miner is stuck requesting oak fence over and over.  Must be thousands of request for this.   The request gui for them took 3+mins to open.  The clipboard took 3+mins also.

![2017-12-09_13 23 51_2](https://user-images.githubusercontent.com/30982580/33798776-5dffaa0c-dce4-11e7-9a67-4a1b04b187fd.png)

**Comment by bob0bob** [comment]
It cleared up by itself and the miner started working just fine.  I don't think I did anything.

**Comment by marchermans** [comment]
Yeah. The RS has healing mechanic that will track those kinds of things down. But the latest patch round by @Raycoms made this a lot worse.

**Comment by Raycoms** [comment]
Should be fixed in the newest version, should be on curse in a few minutes
