### ISSUE TITLE
clipboard - cosmetic issue

### ISSUE THREAD

**Issue by bob0bob** [ldtteam/minecolonies#1816]
minecraft 1.12.2
mine colonies 8.5941

If you have to many request to show up on the page.  The scroll box, cancel button is to low.  

Basically, appears to be by one row.

![2017-12-09_13 23 51_2](https://user-images.githubusercontent.com/30982580/33798786-8169ff60-dce4-11e7-9cce-33517fc30b98.png)

**Comment by Raycoms** [comment]
Should be fixed in the newest version, should be on curse in a few minutes
