### ISSUE TITLE
[1.12.2-0.8.5941] issue

### ISSUE THREAD

**Issue by ghost** [ldtteam/minecolonies#1817]
Tested with:
minecolonies-universal-1.12.2-0.8.5941

Builder = stalled at request shovel as try build mine level 5 stone version. (its pretty much same as one from 5930)
https://puu.sh/yCPL0/598356adce.png
https://puu.sh/yCPKf/cc1f23e3f4.png

Farmer = Stalled in Prepare and farm plant loop (No Request) (wooden Hoe 64 x Seeds)
https://puu.sh/yCPSf/630e20384f.png
https://puu.sh/yCPSS/12fa7e6bea.png
Its Inventory and request:
https://puu.sh/yCPUx/ed97e31796.png
https://puu.sh/yCPVK/3820652775.png
EDIT: I might try trace it down and it seem that it try find the fields but it show no field in the list.
https://puu.sh/yCSDK/7e72381833.png
https://puu.sh/yCSE9/19277c94d3.png

fml-client-latest.log
https://hastebin.com/cikomajaqi.scala
latest.log
https://hastebin.com/teyameziwe.sql

**Comment by bob0bob** [comment]
Same.  Farmer: Just loops between {Preparing} and {farmer_harvest}

**Comment by marchermans** [comment]
We are going to need logs.
Screen shots are nice and all. But they do not help us with reproducing anything.

**Comment by Moobien** [comment]
Here are my logs, I am having similar issues to the ones being reported here and in other threads.

https://gist.github.com/Moobien/d239d498e0a29c125fa52a2e4d831920

**Comment by bob0bob** [comment]
Should not the function AbstractEntityAIBasic.checkForToolOrWeapon()  return true if the tool is in inventory.  Below:::    But the check "if (checkForNeededTool(toolType, minimalLevel)) " in the function returns false (meaning the tool is in inventory).   so the default return for the function says "FALSE".  meaning you don't have the tool....   Seems like it just needs to switch around the two return types.   It lets the farmer start working in my build.

The comments say

boolean com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic.checkForToolOrWeapon(@NotNull IToolType toolType)


Ensures that we have a appropriate tool available. Will set needsTool accordingly.
Parameters:toolType type of tool we check for.
Returns:true if we have the tool

**Comment by marchermans** [comment]
Fixed in a upcoming PR.

**Comment by Raycoms** [comment]
Should be fixed in the newest version, should be on curse in a few minutes
