### ISSUE TITLE
[1.10.2] Server Lag and Log Spam

### ISSUE THREAD

**Issue by yotthani** [ldtteam/minecolonies#1818]
### Minecolonies version
version minecolonies-universal-1.10.2-0.9.5938.jar

### Actual behaviour

- After some time running server gets huge lag spikes from the Colonists placing requests
can be forced by calling them all to the town hall
- also with diabled DEBUG output Server log gets spammed with hundreds of lines like these

"[20:41:19] [Server thread/DEBUG] [minecolonies/]: Found input factory with matching super OUTPUT type. Search complete with: com.minecolonies.coremod.colony.requestsystem.requests.StandardRequestFactories$FoodRequestFactory@3617f0aa
[20:41:19] [Server thread/DEBUG] [minecolonies/]: Attempting to find a Factory with Primary: com.minecolonies.api.colony.requestsystem.requestable.Food -> com.minecolonies.coremod.colony.requestsystem.requests.StandardRequests$FoodRequest
[20:41:19] [Server thread/DEBUG] [minecolonies/]: Found matching Factory for Primary input type."

**Comment by marchermans** [comment]
How are you starting your server?
These log entries are debug only and under normal operations they should not appear at all.

**Comment by yotthani** [comment]
iam starting it from a self written windows service with following config:
`<configuration>
  <appSettings>
    <add key="Path" value="C:\\Program Files\\Java\\jre1.8.0_151\\bin\\"/>
    <add key="FileName" value="java.exe"/>
    <add key="Arguments" value=" -server -Xms4G -Xmx15G -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSIncrementalPacing -XX:ParallelGCThreads=2 -XX:+AggressiveOpts -Dfml.queryResult=confirm -jar forge-1.10.2-12.18.3.2511-universal.jar nogui"/>`

**Comment by marchermans** [comment]
Weird.
Seems like you set the log level wrong.

**Comment by yotthani** [comment]
chekced it twice .. everything was on default except that i disabled babarians

**Comment by yotthani** [comment]
update: tried version minecolonies-universal-1.10.2-0.9.5961.jar

* Log Spam is less but still there
* Lag seems to appear if there are more than one Colony is loaded (in different Chunks) at the same time from player running around in it

**Comment by Raycoms** [comment]
Should be fixed in the newest version, should be on curse in a few minutes
