### ISSUE TITLE
Builder constantly requests 2  Diamond Swords

### ISSUE THREAD

**Issue by Guardian9978** [ldtteam/minecolonies#1820]
### Minecolonies version

version 1.12.2-0.8.5930

### Expected behavior

- When placing 2 Diamond swords into the Builder's Hut the builder should stop requesting them and build/request something else.

### Actual behaviour

- Placing 2 Diamond Swords in the Builder's Hut ends up with one in the builders inventory and the other stays in the builders hut.

### Steps to reproduce the problem

1. Request a builder to build "schematics/Taiga/TownHall4".
2. Feed the builder resources including Diamond Swords.
3. See if both swords are taken and the builder starts building/requesting other things.

**Comment by Moobien** [comment]
I am having this same issue but not with swords.  
"Builder <UNKNOWN> is in need of 1 {Armor Stand} at Dim: 0"

Nothing being built even needs an armor stand, this started when I pasted a lvl 5 Wood Town hall and clicked on "repair building"

**Comment by Raycoms** [comment]
Should be fixed in the newest version, should be on curse in a few minutes

**Comment by Guardian9978** [comment]
Problem still exists with version 1.12.2-0.8.6037
