### ISSUE TITLE
Request gui - clicking on "fulfill"

### ISSUE THREAD

**Issue by bob0bob** [ldtteam/minecolonies#1823]
mine craft 1.12.2
mine colonies 8.5941

Lets say. builder.

Builder is requesting an item Say a Bed.   You have 4 beds in your inventory.  You right click on builder and then click on request.  You then see he wants 1 bed.  you click on "FULFILL".   IT removed EVERY BED from your inventory and give it to him.   It doesn't just give what he asks for which is 1.

**Comment by bob0bob** [comment]
A quick look at the code WindowCitizen.fulfill()
It looks like it is using the wrong variables for the count when sending it over to the server.

MineColonies.getNetwork().sendToServer(new TransferItemsToCitizenRequestMessage(citizen, itemStack, isCreative ? amount : count, citizen.getColonyId()));

var amount = request amount
var count = amount in players inventory.

so based on the if statement isCreative  means in creative mode send over requested amount in survival send over the players entire inventory.

I would think this should be reversed.

**Comment by marchermans** [comment]
Yep you are right
Pushing a fix to our fixes branch now :D

**Comment by bob0bob** [comment]
check out #1814, 1817.  I put the fix for that issue also.  Both are the same issue.

**Comment by marchermans** [comment]
Seen thank you. I am working on those directly after dinner

**Comment by Raycoms** [comment]
Should be fixed in the newest version, should be on curse in a few minutes
