### ISSUE TITLE
Baker - Gui enhancement

### ISSUE THREAD

**Issue by bob0bob** [ldtteam/minecolonies#1826]
Add a new interface to the bake gui like the farmer.  To select which of the 3 recipes to make.  right now the player has to supply the ingredients for the cookie or cake.  Because if they do not have any items it request the recipe for bread.

The gui to select would be great.

Even better.   Remove the recipe from being hard coded and add it to the config.  That way a player can add in the recipes they want.  This way they can make stuff from other mods like pam's harvest.  

Should be doable and would be great.

**Comment by Justen-N** [comment]
Crafting update is waiting on RS bugs before moving forward. Recipe Config is planned.
