### ISSUE TITLE
“Requiring a builder of level 3 in order to build or upgrade this building”

### ISSUE THREAD

**Issue by Dimentive** [ldtteam/minecolonies#1827]
The game is telling me that I need a builder of level 3 to upgrade a building, but my builder is level 5. I think it means the **builder’s hut**.

**Version**: 1.10.2-0.8.4063

I’m not sure if this has been fixed in a future version.

**Comment by Justen-N** [comment]
Absolutely requesting the hut, not the builder himself. Probably a translation error on our part. I'll take a look later.
