### ISSUE TITLE
Minecolonies

### ISSUE THREAD

**Issue by Optimistos** [ldtteam/minecolonies#1829]
Hellow all, i have some troubles with my "Colonists". 
My Worker works FINE, but my farmer and lumber jack doesn't do anything it says "waiting to end rain" and always stuck on his chest. 

Minecolonies-universal-1.12.2-0.8.5930
My mc Version is 1.12.2 Forge. I read all internet abbout this problems and seems not only me have it, but dont finde how repair. Please help, TEACH ME AND TELL ME what need to do) 

[fml-server-3.log](https://github.com/Minecolonies/minecolonies/files/1548770/fml-server-3.log)
[fml-server-latest.log](https://github.com/Minecolonies/minecolonies/files/1548771/fml-server-latest.log)
[2017-12-11-3.log.gz](https://github.com/Minecolonies/minecolonies/files/1548768/2017-12-11-3.log.gz)

**Comment by Raycoms** [comment]
Should be fixed in the newest version, should be on curse in a few minutes
