### ISSUE TITLE
Issues for 0.8.5950

### ISSUE THREAD

**Issue by wilsondgonzales** [ldtteam/minecolonies#1833]
### Minecolonies version

0.8.5950

- Baker
Gets stuck in 'preparing' state. However I strongly believe that it's because he gets left with 2 wheat when he needs 3. Maybe a check needs to be added to him

- Dmen
still getting stuck on 'dumping' state

- Fisher
stuck on 'searching for water'
Also had a moment when he was 'inventory full' when his chest or personal inventory is nowhere near full. Also was a boat added? he was stuck in a 'searching for water' state when riding the boat. He works when i took it out

- cook
not working even though he is in a 'start working' state, he's chillin in the citizen hut
- Guards
shows 'working' state even though right-clicking them shows they are requesting. not sure how important that is

**Comment by Raycoms** [comment]
Should be fixed in the newest version, should be on curse in a few minutes
