### ISSUE TITLE
farmer stuck - At night

### ISSUE THREAD

**Issue by bob0bob** [ldtteam/minecolonies#1834]
minecraft 1.12.2
mine colonies 8.5950

When night falls, the farm does not go to sleep.  stands in the fields {farmer_hoe} state.

**Comment by bob0bob** [comment]
![2017-12-11_21 32 49](https://user-images.githubusercontent.com/30982580/33866902-d5b4da28-debe-11e7-8f59-6c66ccbb35ae.png)

**Comment by bob0bob** [comment]
If night comes at he is at the farmer hut, he goes to sleep.  Has something to do when he is in the field

**Comment by Raycoms** [comment]
Should be fixed in the newest version, should be on curse in a few minutes
