### ISSUE TITLE
1.12.2-0.8.4932 fatal error

### ISSUE THREAD

**Issue by lJasonl** [ldtteam/minecolonies#1837]
Minecolonies version

version 1.12.2-0.8.4932 or curse X.X.XX

### Actual behaviour

Game crashes in single player with a "fatal error" as soon as the Town Hall is placed. Game returns to multiplayer game menu.

### Steps to reproduce the problem

1. Attempt to place Town Hall

**Comment by Optimistos** [comment]
well ya that happens some times with lot of players) try new version
https://minecraft.curseforge.com/projects/minecolonies/files/2508692

**Comment by lJasonl** [comment]
Thank you, that seems to have fixed it.

-JaY
