### ISSUE TITLE
Lumberjack issue

### ISSUE THREAD

**Issue by Endalion** [ldtteam/minecolonies#1838]
### Minecolonies version

version 0.9.5961

### Expected behavior

- Lumberjack collects wood.

### Actual behaviour

- At the start of the day, Lumberjack collects some wood, returns to the sawmill chest, then sits there doing nothing other than spamming logs.
- Rehiring simply repeats the above.
- Recalling does nothing.

### Steps to reproduce the problem

1. Hire a lumberjack
2. Observe behaviour and logs
3. ...
4. Profit

[LJLog.txt](https://github.com/Minecolonies/minecolonies/files/1554020/LJLog.txt)

**Comment by Raycoms** [comment]
Should be fixed in the newest version, should be on curse in a few minutes
