### ISSUE TITLE
Deliveryman Issue

### ISSUE THREAD

**Issue by Endalion** [ldtteam/minecolonies#1839]
### Minecolonies version

version 0.9.5961

### Expected behavior

- Deliveryman does deliveries

### Actual behaviour

- Deliveryman goes to warehouse, then to a citizen hut (with no food in it), back to the warehouse, then sits there doing nothing other than spamming logs.
[DMLog.txt](https://github.com/Minecolonies/minecolonies/files/1554030/DMLog.txt)
- Rehiring repeats the above.
- Recalling causes the deliveryman to return to the warehouse. 
Message shown is "Dumping"

### Steps to reproduce the problem

1. Hire a deliveryman
2. Observe behaviour
3. ...
4. Profit

**Comment by marchermans** [comment]
I know the error. I released a fix to not haveit happen again, but if your world already has that Problem then it might return. I will release a fix this Weekend that will clean up the lingering data that was around. Alternatively you can downgrade to 0.8.5929 and run it untill a bunch of log spam turns up in your log and then reupgrade. It contains a cleaning mechanism for this error.

**Comment by wilsondgonzales** [comment]
@OrionDevelopment where is 5929?

**Comment by marchermans** [comment]
Sorry 0.8.5930. 5929 is the PR variant.

**Comment by Raycoms** [comment]
Should be fixed in the newest version, should be on curse in a few minutes
