### ISSUE TITLE
Ticking player while other players stay fine

### ISSUE THREAD

**Issue by Wyrrrd** [ldtteam/minecolonies#1840]
### Minecolonies version

version 1.12.2-0.8.5950

### Expected behavior

- no disconnect by a fatal error for a player

### Actual behaviour

- disconnect by a fatal error for one player while others are fine

### Steps to reproduce the problem

1. Have a "All the Mods 3"-server for 4 or 5 consecutive versions
2. Have a player wear specific baubles. Or just have citizens. Maybe.
3. ...
4. Have no clue at all... Sorry. Might be Vazkii's fault, I see a name in the file :)

### Attachments
[disconnect_message.txt](https://gist.github.com/Wyrrrd/f5697b2750faf3271d8436390c63d083)

**Comment by Wyrrrd** [comment]
#### Update:
The problem seems to be Botania's "The Spectator" (ItemItemFinder).
It takes the ItemStack in the (later ticking) player's hand, then is trying to read the citizens's inventories to display its fancy rising bubbles if the ItemStack is contained in them.
This reading fails.

Problem here may be the citizens returning a `hasCapability = true`, but then returning `getCapability = null`.

**Comment by Raycoms** [comment]
Should be fixed in the newest version, should be on curse in a few minutes

**Comment by Wyrrrd** [comment]
Thank you!
