### ISSUE TITLE
Newer Minecolonies Versions not working (Forge crash during minecraft startup) 

### ISSUE THREAD

**Issue by johnnye152** [ldtteam/minecolonies#1845]
I'd like to update to the newer Alpha versions but when I use them it crashes halfway through  the Forge loading screen showing:  

Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from MineColonies (minecolonies)

That's using Forge 1.12.2-14.23.0.2491 and Minecolonies Alpha 5981
 It'll work fine with Minecolonies Beta 0.8.5081 though. Is there something I need to do?

I've tried to attach the crash report for the issue below. The same issue (type of crash) occurs on all versions of minecolonies except for the 5081 version which is a Beta.

[crash-2017-11-13_15.26.36-client.txt](https://github.com/Minecolonies/minecolonies/files/1562576/crash-2017-11-13_15.26.36-client.txt)

**Comment by Raycoms** [comment]
This is weird, @OrionDevelopment do you have any idea?
And @johnnye152 can you try a newer forge version (2529+) ?

**Comment by marchermans** [comment]
No idea

**Comment by johnnye152** [comment]
I'll try a newer forge

**Comment by johnnye152** [comment]
I've just tried forge 2555 which is the latest recommended version and same crash seems to happen:
[crash-2017-12-15_12.57.59-client.txt](https://github.com/Minecolonies/minecolonies/files/1562703/crash-2017-12-15_12.57.59-client.txt)

**Comment by johnnye152** [comment]
Reverted to Minecolonies 5081 but still using newer forge 2555 and that works, just not the newer versions of minecolonies still...

**Comment by Optimistos** [comment]
i have those problem bu just instaled forge-1.12.2-14.23.1.2562-universal and all was oke

**Comment by marchermans** [comment]
Okey
So seems to be a Forge issue with there API mechanics.
@johnnye152 Does @Optimistos fix work for you?

**Comment by johnnye152** [comment]
I'll give 2562 a go. Thank you Optimistos. I'll update after

**Comment by johnnye152** [comment]
Still seems to be the same problem. I installed Forge 2562 using the Windows installer. I'm not sure how to use the 'universal' file which can also be downloaded, it seems just to be a JAR file. Forgive my ignorance but what do you do to get that JAR file to work as opposed to using the Forge windows installer? I cannot find the JAR file on the 'launch options' tab on minecraft launcher, but I can see the 2562 which appeared from the Windows installer and is selectable in the 'versions' drop down box. The universal JAR file isn't.

**Comment by Optimistos** [comment]
The problem with Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from MineColonies (minecolonies) Was gone for me after update new FORGE and launch game with that forge.

**Comment by johnnye152** [comment]
Updated to latest version 2566 and problem remains. There must be something I am doing differently?? Weird how Minecolonies 5081 works though.

I download Forge installer for windows, run, select 'install client' and then select that version of forge from the list of version options from the minecraft launcher options. That's all straightforward enough, weird how it doesn't work for me.

**Comment by johnnye152** [comment]
Thanks for the help though

**Comment by Optimistos** [comment]
Do you play in single player? or your server? I have server and i play with  my wife. When i havend that problem i instal that new forge in game directory withous INSTAL. Because its for server. And other FORGE for singleplayer should be instaled Like some Exe files but "open with JAVA". After that he instaled for me in %appdata% needed forge for My launcher after that i launch server forge  and problem is gone.. MAYBE what i say is look strange and wierd but for me WORKS fine)))

**Comment by marchermans** [comment]
I will test it myself i think this Weekend. But if I can not find the issue. I will need more information. Like installed mods, java version, forge version, mc version etc.

**Comment by Raycoms** [comment]
Did you try re-download it?

**Comment by johnnye152** [comment]
I did retry downloading both forge and minecolonies. 

Just picked up kids from school but will write later this evening (chaos in my house at the mo!)

**Comment by johnnye152** [comment]
From the crash report, here is my system details with Java version etc (full crash report attached at bottom of comment):

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 154568640 bytes (147 MB) / 436207616 bytes (416 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.1.2566 10 mods loaded, 10 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized '

[crash-2017-12-15_13.52.05-client.txt](https://github.com/Minecolonies/minecolonies/files/1563541/crash-2017-12-15_13.52.05-client.txt)

**Comment by Optimistos** [comment]
Do you play on your server or in singleplayer

**Comment by Optimistos** [comment]
Also helps me. If you play on MP server.
I removed the File minecolonies from world folder. After that starting the game and its loaded fine. After that you can put it back but server will make there another one and STRANGE but i dont lose nothing. But better COPY that minecolonies file in some other place for SURE) in case if no help to put it back

**Comment by johnnye152** [comment]
usually single player, I'll give your suggestion a go. Thanks.

**Comment by johnnye152** [comment]
Couldn't find 'world' folder, I assume that is a MP folder? Thanks for suggestion though.

**Comment by Optimistos** [comment]
Whoot 0_o in %appdata% should be Saves and in saves should be the map with world name. in my case is "saves=>word123" also in%appdata% there should be the "minecolonies" folder.  try CUT them both. And enter in World. if doest help Put it back. If you wont come play with us but you need hamachi and official minecraft ^_^

**Comment by Raycoms** [comment]
Should be fixed in the newest version, should be on curse in a few minutes

**Comment by johnnye152** [comment]
Thank you. Works a treat. :)
