### ISSUE TITLE
Minecolonies guide not found

### ISSUE THREAD

**Issue by johnnye152** [ldtteam/minecolonies#1846]
5081 Minecolonies 

I cannot get the Minecolonies guidebook to work, though I have put the 'guidebook' 1.12 Mod on. When trying to open the guidebook from supply building chest it says 'minecoloniesfilenotfound'**

Screen capture below:

![image](https://user-images.githubusercontent.com/34572954/34041467-03393466-e190-11e7-9ee3-7db6a906376b.png)

Hope it's not me missing something obvious, couldn't find the minecolonies.xml on forge or anywhere.

**Comment by Raycoms** [comment]
I'll test that out.

**Comment by Raycoms** [comment]
Okay, will be fixed with the next pr from me =)
