### ISSUE TITLE
All found problems.

### ISSUE THREAD

**Issue by Optimistos** [ldtteam/minecolonies#1847]
### Minecolonies version

forge-1.12.2-14.23.1.2562-universal

1. Builder have some troubles when he need some stuff he start SPAM in his MENU loot of times and provoke lags when you try to look at his needs or his inventory. 
When i upgrade the DEFENS tower he ask 1 white bed. i give it to him and HE placed RED bed 0_o without some error BUT when i try upgrade the citizen house at lvl 3 he ask for 2 white beds and HE says always "i need 2 beds" and just walks around to building to chest, to building to chest.

2 Farmer doest wana do nothing. He says only Hoening or planting and walking around on Farm field but not make some field or some planting. Nothing.

Also Similar problem with "NEED STUFF" happens wiht all colonists. When they want some food or fences or etc.. they start SPAM IN his NEED menu over and over 300+ times and provoke lags. But when u place in Chest it goes down from 300- after 10 minutes stats working 0_o.

And sometimes when colonist die or dunnow ITS gone IT spam in chat over and over "Colonie name <UNKNOW> is need of Food ad Dim.... " or not food but some other stuff.. EVEN i dont have any colonists 0_o

**Comment by Raycoms** [comment]
What is the minecolonies version?

2017-12-15 13:02 GMT+00:00 Optimistos <notifications@github.com>:

**Comment by Optimistos** [comment]
The latest sir. But those problem WAS from latest 2 Updates 5981 and earlier one

**Comment by Optimistos** [comment]
Better to make some video to show but dunnow how xD ^_^

**Comment by marchermans** [comment]
@Raycoms @Optimistos I have a fix for the Spam stuff. The bed is something i am still researching. @Raycoms we might need to update all our Scans that have beds.

**Comment by Optimistos** [comment]
il make some Video with all founded bugs, maybe will help ya, me english not so good, im from Moldova

**Comment by Optimistos** [comment]
Dunnow if help Ya
You will see and SPAM NEED stufs. and unworked Worked Farmer xD etc..etc.)
https://youtu.be/BcCZdtUxeNA
https://youtu.be/4CEgZN8CqMU
https://youtu.be/8fWdENhGs20

**Comment by Optimistos** [comment]
So? do you see my problems? know how resolve it? HOPE you know)) my wife play like a Builder and designer in other corner and i play in left corner with those colonist and some mecanism..so i really want to they work(((

**Comment by marchermans** [comment]
1) Is fixed in a test version, ready for internal testing, not yet released however.
2) Ah they do not stack! That is the issue. He is looking for a stack with 2 beds. Not for two stacks with each one bed! (Good to know.)
3) The same as 1).

Thanks for the vidoes that actually helped. I hope to have some time this evening to fix. But definitely this weekend.

**Comment by Optimistos** [comment]
THANK YOU for working its really a nice project and its give us lots of experience and fun!

**Comment by Optimistos** [comment]
aah and sometimes when Rain stops they walking around and says "Waiting to stop rain" or Let me sleep 0_o

**Comment by Raycoms** [comment]
Yeah that's normal since they didn't switch their task to start_working
yet, because they didn't get anything to do.

2017-12-15 20:07 GMT+00:00 Optimistos <notifications@github.com>:

**Comment by Optimistos** [comment]
Oke) thankyou Sir ^_^

**Comment by Raycoms** [comment]
Should be fixed in the newest version, should be on curse in a few minutes
