### ISSUE TITLE
Birch Town Hall Level 1 not being built

### ISSUE THREAD

**Issue by Kerzahd** [ldtteam/minecolonies#1849]
### Minecolonies version

version 0.8.5981 and 0.8.5950

### Expected behavior

- Builder uses the requested beds in the building process of the birch town hall

### Actual behaviour

- Builder requests 2 white beds over and over again. No beds can be found in the blueprint either (preview via building tool doesn't show any)

### Steps to reproduce the problem

1. Place birch town hall via building tool
2. Let builder do the first layer
3. Beds are requested but never placed

**Comment by marchermans** [comment]
Yeah we now
It has something to do with stacking? Do the beds stack or not?

**Comment by Optimistos** [comment]
op they dont stack. they are 1 by one separatly

**Comment by Kerzahd** [comment]
I know that they are separte but I investigated the blueprint for the birch town hall level 1 and there are no beds? Is it a common issue or is there something missing in the pack then? Because the builder also goes to the zone with both beds and just returns to the builder's hut and repeats that until I kill him. Something might be broken there.

Also only the speech bubble says he wants 2 beds, chat and request menu are clear and don't even sho the beds if there are already some in the inventory of the builder

**Comment by Raycoms** [comment]
Yes, we will resolve this this weekend.

2017-12-15 16:00 GMT+00:00 Kerzahd <notifications@github.com>:

**Comment by marchermans** [comment]
Found the bug! Will be fixed.

**Comment by Raycoms** [comment]
Should be fixed in the newest version, should be on curse in a few minutes
