### ISSUE TITLE
My warehouse needs... air???

### ISSUE THREAD

**Issue by MattBeard** [ldtteam/minecolonies#1850]
### Minecolonies version

version 1.12.2-0.8.5981

### Expected behavior

- Sanity?

### Actual behaviour

- The warehouse is requesting a delivery of air

### Steps to reproduce the problem

I have no idea... but I don't yet have a deliveryman in this colony and the builder is constructing the post office.

![2017-12-15_15 14 56](https://user-images.githubusercontent.com/835593/34048300-1af43978-e1ab-11e7-8d34-7e536f0f77e7.png)

**Comment by Optimistos** [comment]
well ) you building on the moon? so where is your oxygen maker station? )) if seriosly iits WIERD )))

**Comment by marchermans** [comment]
That us a delivery request. Bug in its processing thanks for the report.

**Comment by Raycoms** [comment]
Should be fixed in the newest version, should be on curse in a few minutes

**Comment by CplPibald** [comment]
I just got this exact same message today in version 1.12.2-0.8.6682
