### ISSUE TITLE
[build 5989] crash when viewing npc tool requests

### ISSUE THREAD

**Issue by kreezxil** [ldtteam/minecolonies#1851]
### Minecolonies version

1.12.2-0.8.5989

### Expected behavior

client to not crash when looking at npc to see what tool they need and clicking the npc's 3 line icon that is below the tool they are requesting.

client crash report: https://pastebin.com/PLyyXQGu

![unknown](https://user-images.githubusercontent.com/3880072/34062096-8ef77c5e-e1b0-11e7-9884-89c5730db4d6.png)

**Comment by Rumpelstiltskinny** [comment]
confirmed...minecolonies-universal-1.12.2-0.8.5950 on 1.12.2-forge1.12.2-14.23.1.2554

**Comment by Optimistos** [comment]
Confirmed all versions played

**Comment by kreezxil** [comment]
more specifically this crash happens when you are connected to a dedicated server, the server doesn't crash but the client does.

In single player mode, the crash does not happen.

**Comment by Raycoms** [comment]
This should be fixed with the version we should be releasing in the next 3
days

2017-12-16 17:32 GMT+00:00 kreezxil <notifications@github.com>:

**Comment by kreezxil** [comment]
cool

**Comment by Raycoms** [comment]
Should be fixed in the newest version, should be on curse in a few minutes
