### ISSUE TITLE
Request System - Delivery man

### ISSUE THREAD

**Issue by bob0bob** [ldtteam/minecolonies#1854]
minecraft 1.12.2
minecolonies 8.5989

If you get a request for 1 furnace.  The warehouse have a stack (Important stack) of 23 furnaces.   The DMan comes and grabs the ENTIRE stack even though the request is 1 furnace.   He goes to the builder and delivers ALL 23 furnaces to the builder  not just 1 as requested.

**Comment by Raycoms** [comment]
Should be fixed in the newest version, should be on curse in a few minutes
