### ISSUE TITLE
Scarecrow Trashcan

### ISSUE THREAD

**Issue by kreezxil** [ldtteam/minecolonies#1856]
### Minecolonies version

1.12.2-0.8.5989

### Expected behavior

- expected scarecrow to take seeds from the hopper

### Actual behaviour

- scarecrow deletes the seeds

### Steps to reproduce the problem

1. place a scarecrow
2. put a hopper to the scarecrow's pants
3. put anything in the hopper
4. watch the stuff vanish into oblivion

**Comment by Asherslab** [comment]
You shouldn't be putting more than one seed item in a scarecrow anyway. it is not used as storage
