### ISSUE TITLE
MineColonies keeps crashing!!!

### ISSUE THREAD

**Issue by BlancFou** [ldtteam/minecolonies#1858]
### Minecolonies version

version 1.12.2

### Expected behavior

- works like shown

### Actual behaviour

- crashes once placed down and I cant go onto the world anymore

**Comment by Raycoms** [comment]
can't you define the forge and minecolonies version?

2017-12-16 20:35 GMT+00:00 BlancFou <notifications@github.com>:

**Comment by Raycoms** [comment]
Should be fixed in the newest version, should be on curse in a few minutes
