### ISSUE TITLE
[Enhancement] Scarecrow Gui

### ISSUE THREAD

**Issue by kreezxil** [ldtteam/minecolonies#1859]
### Minecolonies version

1.12.2-0.8.5989

Currently if a scarecrow is placed outside the town border limit you can not access the gui and you get the feeling that it is broken.

Idea:
Allow the gui to come up and have a red X in the seed slot. And a note saying one of "must have rights" or "must be in border". Something to that affect.

Why:
Had a player place his scarecrow at 105 blocks from towncenter. Complained that the scarecrow was broken. I tested and was able to access my own. Discovered that Scarecrow had to be inside town border. Thought it would've been nice to have this information on the scarecrow.

**Comment by Raycoms** [comment]
Yeah probably should even notice the player before placing like "Can't
place here, must be inside your town"

2017-12-16 23:04 GMT+00:00 kreezxil <notifications@github.com>:
