### ISSUE TITLE
Perpetual need for Beetroot

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [ldtteam/minecolonies#1861]
### Minecolonies version

minecolonies-universal-1.12.2-0.8.5989.jar

### Expected behavior

- To finish Cook5

### Actual behaviour

- Perpetual need for beetroot https://i.imgur.com/Skiw3Vc.jpg (I gave the builder like 5 stacks of beetroot)

### Steps to reproduce the problem

Upgrade Cook4 to Cook5 (stone)

**Comment by marchermans** [comment]
Yeah known. Their is a Problem with stack detection right now.

**Comment by Raycoms** [comment]
Should be fixed in the newest version, should be on curse in a few minutes
