### ISSUE TITLE
Builder Request not being fulfilled

### ISSUE THREAD

**Issue by blacksythe** [ldtteam/minecolonies#1862]
### Minecolonies version

version 1.12.2-0.8.4932 
Sponge Forge (The latest version compatable with nucleus) Unsure of version number
All The mods 3 5.5
### Expected behavior

- Builder collects/requests minecart with a chest and uses it for upgrading the deliveryman
- Request is fulfilled in creative mode via player interaction in gui/throwing the item at him/putting it in his chest
- Request is fulfilled in survival mode via player interaction in gui/throwing the item at him/putting it in his chest

### Actual behaviour
- Builder requests minecart with a chest and is delivered by the deliveryman but does not collect it from his hut
- Request is fulfilled in creative mode via player interaction in gui/throwing the item at him/putting it in his chest but does nothing with it "keeps requesting it"
- Request is fulfilled in survival mode via player interaction in gui/throwing the item at him/putting it in his chest but does nothing with it "keeps requesting it"

### Steps to reproduce the problem

See above
4. Profit

**Comment by marchermans** [comment]
Known bug already fixed in internal testing version. Waiting for other relevant and connected bugs to be fixed.

**Comment by Raycoms** [comment]
Should be fixed in the newest version, should be on curse in a few minutes
