### ISSUE TITLE
Inaccessable Inventories

### ISSUE THREAD

**Issue by Moobien** [ldtteam/minecolonies#1866]
Hey guys, updated to minecolonies-universal-1.12.2-0.8.6037 and none of the MC added inventories are accessible.  Have tried the building blocks and the racks.

**Comment by Moobien** [comment]
Please disregard the previous issue. I made a new world and they worked fine, but the previous world no longer loads.

That being said the armor stand issue still is there. Builder has 20 of them in his hand and still stops to demand an armor stand.

**Comment by bob0bob** [comment]
My experience is it is related to 6037.   I'm seeing part of MC just freezes.  I don't get a crash but ALL inventory chest do not work after a certain point.   Request windows do.  I even notice the citizen freeze.  I have to leave and come back and after a bit it does it again.  It just started with 6037.  It is also a old map.   If i used an old version, the map works just fine.  it is related to changes.  
That is what I'm seeing.

**Comment by TheOrionsun** [comment]
Found that installing preview_OptiFine_1.12.2_HD_U_C8_pre.jar fixed chest not opening problem. Game locked up after first new loaded game, but restarted second time and all was ok now.

**Comment by Raycoms** [comment]
Try this jar:
https://s3.eu-central-1.amazonaws.com/minecolonies/Minecolonies/Minecolonies_Branches/6050/minecolonies-universal-1.12.2-0.8.6050.jar

2017-12-19 0:44 GMT+00:00 danielconrad2011 <notifications@github.com>:

**Comment by TheOrionsun** [comment]
Tested 6050.jar and no issues with chests or worker inventories.

**Comment by TheOrionsun** [comment]
This issue looks to have been fixed using the preview of OptiFine and latest Alpha release 6093, at least for me it has...
