### ISSUE TITLE
java.lang.NullPointerException: Ticking entity (1.12.2)

### ISSUE THREAD

**Issue by SDUBZ** [ldtteam/minecolonies#1869]
### Minecolonies version
minecolonies-universal-1.12.2-0.8.6037

### Expected behavior

to visit a users base and not crash from barbarians

### Actual behaviour

-visited a users base and crashed from barbarians

### Steps to reproduce the problem

1.have minecolonies on server and forge-1.12.2-2575
2. goto a base with a built up colony when barbarians are attacking
3. get crash
4. Profit
[crash-2017-12-18_17.07.54-server.txt](https://github.com/Minecolonies/minecolonies/files/1566803/crash-2017-12-18_17.07.54-server.txt)

**Comment by Raycoms** [comment]
Will be taken care of

**Comment by Raycoms** [comment]
Should be fixed in the newest version
