### ISSUE TITLE
Implement Cactus Plank Type

### ISSUE THREAD

**Issue by Raycoms** [ldtteam/minecolonies#1871]
We have several models made by D3miurge for the Cactus Plank Type.

What needs to be done:

- Create Cactus Plank Block
- Create Cactus Plank BlockState
- Add Variants for Stairs, Slabs, Door, Trapdoor (Textures and models are already available)
- Create recipe

**Comment by MineShadow7** [comment]
But... Why? Is that usable in any structures/buildings?

**Comment by Raycoms** [comment]
Yes, it will be for the dessert style

**Comment by connoisseur-demiurgo** [comment]
![cactus_wood_1 13_preview_400___360](https://user-images.githubusercontent.com/17484186/35065798-76d11a26-fbb5-11e7-90da-d8108f9e9ccd.png)

**Comment by IamAlathe** [comment]
So, will the lumberjack ( or perhaps someone else) plant/harvest cacti?

**Comment by MineShadow7** [comment]
Maybe farmer can do this job.

**Comment by IamAlathe** [comment]
That also makes sense.  My first thought was lumberjack because plank/wood.  But can farmers work outside of fields?  I've never tried, and with some of the vanilla cactus mechanics (on sand, nothing next to it, causes damage) that might not work well.

**Comment by Raycoms** [comment]
@MineShadow7 progress?

**Comment by Cazsius** [comment]
https://github.com/ldtteam/minecolonies/pull/2546

Didn't Mean to Close until accepted, opened again.

**Comment by MineShadow7** [comment]
Since cactus planks were released, can we close this?

**Comment by PoroUsedSnax** [comment]
Would have figured referencing it in the PR would close it, as it's implemented with #2546 I'll close this
