### ISSUE TITLE
Implement new Shingle variation

### ISSUE THREAD

**Issue by Raycoms** [ldtteam/minecolonies#1873]
Until now we have only the oak shingle variation.
What we need:

Implement all shingle variations with the models and textures we have.

What needs to be done:
- Create block and blockStates as well as recipe for those blocks.

**Comment by Moobien** [comment]
Shingle recipe could be as simple as

X  X  os
X  os ow
os ow ow

Os oak slab. Ow oak wood

**Comment by bob0bob** [comment]
X - clay?

If I read this right.
x (clay)  3
os (oak slab) 3
ow (oak wood) 3

This would be all 9 blocks filled?  This is the plan?

This is for just a Shingle? or 3 shingle pieces? 

I don't get it.   I was wondering about this.   From the code, it references clay shingle?  

from the models,  everything is a clay roof.    Is there any other plans to make a wood shingle instead of clay.  For different looks?

**Comment by Moobien** [comment]
X for nothing lol. No clay. As for how much it makes i would suggest at least 2

**Comment by Moobien** [comment]
You would replace the wood and slabs with other materials for other types of shingle

**Comment by bob0bob** [comment]
Ok.  That seems weird,  the roof tile is clay.  they have all the same look.  Only difference is the support beam.   Which will not been seen unless you don't have a flat roof. (drop down ceiling).   Otherwise it will be covered up.  Or did I miss something.

**Comment by Moobien** [comment]
Depends on the rooftile. @rqycoms specifically mentioned oak wood so i suggested a recipe based on that.

**Comment by Raycoms** [comment]
since there will be different variations our idea of the recipe was the following:

B
BB
SPS

S= stick
P = plank
B = Brick Item

**Comment by Moobien** [comment]
That could work dude

**Comment by bob0bob** [comment]
Looking at these shingle models.   I wanted to ask.   there appears to be no point in having any other wood types.   All of them appear to be clay shingles.  The only thing that changes is the support beams.     When you have a finished house  oak,spruce, dark wood  will all look the same unless you have see the bottom of the block.

Of course every item has clay in it.  my thoughts is having only one clay shingle and the shingles change to wood shingles and have them different wood types and looks.  I don't get only thing that changes is something that is not noticeable at the end.  it seems like work that will never be worth the effort.
