### ISSUE TITLE
NPC are not walking properly

### ISSUE THREAD

**Issue by MnkyArts** [ldtteam/minecolonies#1874]
### Minecolonies version

version 1.12-0.8.3238

### Expected behavior

- The Builder (or any mc-npc) should walk normal even if i am away from him.

### Actual behaviour

- So i found a weird bug on my Server where is MineColonies Installed, if i create a Builder (or any mc-npc) & let him Build something and go some blocks away he starts to move like 1milimeter as like 1 Block
here is an Video of the Problem: https://streamable.com/skj0d

(the Problem just appears on Servers)

Also: Can i do that the Builder build even if i am like 500 blocks away? I tried it with an Chunk Loader to keep the Chunks Loaded but it won't work.

### Steps to reproduce the problem

1. Make a Server with the Mods
2. Add a Builder and let him Build something
3. go some blocks away from him

**Comment by Raycoms** [comment]
Do you use sponge by chance?

2017-12-18 19:11 GMT+00:00 Liam R. <notifications@github.com>:

**Comment by MnkyArts** [comment]
wow what an fast answer, yes i use sponge

**Comment by Raycoms** [comment]
There is a sponge setting which makes it slow.

mods { minecolonies { defaults { misc=512 } # Set to false if you want mod
to ignore entity activation rules and always tick. enabled=false entities {
citizen=512 } } }
You need to add this, it's in one of the sponge configs.

2017-12-18 19:14 GMT+00:00 Liam R. <notifications@github.com>:

**Comment by MnkyArts** [comment]
do i need to add it like this: https://i.imgur.com/6ecutbc.png

i am new to this whole Spongeforge thing, the Config is a bit weird

**Comment by Raycoms** [comment]
That should do it.

2017-12-18 19:21 GMT+00:00 Liam R. <notifications@github.com>:

**Comment by MnkyArts** [comment]
alright, i will try it. thanks for the help an fast answer, greate support! :)

**Comment by MnkyArts** [comment]
i also found a little bug (i think) i don't want to open a new Issue so i write it here:

It seems like the warehouse don't work properly it does not add a worker and even manuell i cant add one

**Comment by Raycoms** [comment]
You need a deliveryman building additionally and he will automatically
start working at it.

2017-12-18 20:04 GMT+00:00 Liam R. <notifications@github.com>:

**Comment by MnkyArts** [comment]
ahh, yea i have an deliveryman, but i didnt know they dow work also in the warehouse. thank you for your help! :)
