### ISSUE TITLE
Barracks guards not patrolling

### ISSUE THREAD

**Issue by nick-johnson** [ldtteam/minecolonies#1875]
### Minecolonies version

version 1.12.2-0.8.5081 Beta

### Expected behavior

- Barracks guards set to automatic Patrol mode will patrol all village blocks/waypoints similar to guard tower guards

### Actual behaviour

- Barracks guards patrol all waypoints within the barracks, but do not go farther

**Comment by Raycoms** [comment]
What is their tower level?

2017-12-18 19:12 GMT+00:00 nick-johnson <notifications@github.com>:

**Comment by nick-johnson** [comment]
Level 3 barracks and towers, with other buildings within 40-60 blocks

**Comment by Raycoms** [comment]
It always worked for me, I have to test that out.

2017-12-18 19:39 GMT+00:00 nick-johnson <notifications@github.com>:

**Comment by nick-johnson** [comment]
It's the Taiga style barracks, and they tend to walk around the building and up on top of the walls. I'll try increasing the barracks/tower level and see if they go any farther.

**Comment by bob0bob** [comment]
Issue  #1804   had this reported also.  I don't remember what version it started in, but it was resolved 8.5941 and as far back as 8.5810  for many people. Just FYI.

**Comment by Raycoms** [comment]
Should be working now
