### ISSUE TITLE
Minecolonies 6067 not workig stufs

### ISSUE THREAD

**Issue by Optimistos** [ldtteam/minecolonies#1882]
1) Farmer still walking around and just telling stufs like hoeing and planting but nothing happens.
2) When try upgrade Curier house at lvl 4 Builder almost on the end of buildings Stops and SAYS "Spawning entities" and doesnt move.
3) The miner request now only Stone pickaxe...at lvl 7 )
REST works **JUST PERFECT!**

if i repeat some problems Sorry

**Comment by Raycoms** [comment]
2) Yeah fixed this just with the DMAN, will come tomorrow.
3) The miner requests depending on the hut level not on the worker level.
and 1) I have to test still.

2017-12-19 23:07 GMT+00:00 Optimistos <notifications@github.com>:

**Comment by Optimistos** [comment]
After build a defense tower builder says GATHERING i hope this is oke)
BUT NOW WORKER works LIKE a PRo ) and FAST. 

Thankyou again for work

**Comment by Raycoms** [comment]
Yeah the builder gathers dropped items.

2017-12-19 23:17 GMT+00:00 Optimistos <notifications@github.com>:

**Comment by Raycoms** [comment]
Should be working now
