### ISSUE TITLE
Github clones outdated version. Cant run outdated version.

### ISSUE THREAD

**Issue by Samcity** [ldtteam/minecolonies#1885]
### Minecolonies version

version 1.11.2-08/version 1.12.2

### Expected behavior

- Get 1.12.2

### Actual behaviour

- Get 1.11.2-08
- Game complains about not being able to run it

### Steps to reproduce the problem

1. Relocate to minecolonies github
2. Ensure branch is 1.12.2
3. Redo compiling
4. Repeat x3
4.1. Cant delete previous version as stuff still runs in background.

**Comment by Raycoms** [comment]
You're trying to compile our sources? Can you contact us on discord,
that'll be easier to resolve these kind of problems?

2017-12-20 18:16 GMT+00:00 Samcity <notifications@github.com>:

**Comment by Samcity** [comment]
Just joined. Same name. Where am I going to contact you?
