### ISSUE TITLE
Builder building from location pathing issues

### ISSUE THREAD

**Issue by TheOrionsun** [ldtteam/minecolonies#1888]
### Minecolonies version; 1.12.2

version or curse 0.8.6093 and all older versions

### Expected behavior

- Builder build-from-location close to building they need to build.

### Actual behaviour

- If another building or environment is not pathed to easily they keep moving up until a location can be found to build from. This is sometimes too far away from building area. See screen shot of builder having moved up on Barracks until they could find a location to build from. I had to place blocks out from one tower so builder could get into position.

### Steps to reproduce the problem

1. Just start a Barracks 
2. Build just two towers opposent from each other to lvl 4-5
3. Start third tower and see where builder wants to stand
4. Profit
![2017-12-21_05 02 54](https://user-images.githubusercontent.com/34198967/34253673-39993e7a-e60e-11e7-96b3-3a7ac7b70f2b.png)

**Comment by Philos89** [comment]
I also have this problem. The builder will climb trees near the build site. I try cutting down the trees around the build site but he will look for trees to climb even further out then stand on top doing nothing.

**Comment by marchermans** [comment]
Yeah I was looking into that. We might give him a scaffolding block which he can make (or creatively spawn) which allows him to build better. But for now that is just the way his pathing works.
