### ISSUE TITLE
Builder will not pull items from builder's hut chest

### ISSUE THREAD

**Issue by TheOrionsun** [ldtteam/minecolonies#1892]
### Minecolonies version; 1.12.2

version X.X.XXXX or curse; 0.8.6137

### Normal behavior

- When I put items into builder's chest (lvl 5) the builder is able to get items as they need them.

### Actual behavior

- Builder just stands there waiting for item they show in their hand and in their open requests. When I fulfill the requests they leave and go build. Clears fulfill need if you just put items in their inventory, but that may not allow them to go build, only works 100% of the time when fulfilling need.

I do see some items are waiting for a deliveryman to Resolve their need, but does not give the builder the item when they show up.

### Steps to reproduce the problem

1. Start to build something (observed on building lvl 5, lvl 4 Guard Tower and Citizen 3.)
2. Put needed items into builders chest
3. See if builder takes items from chest or waits for them from deliveryman.
4. Profit

**Comment by TheOrionsun** [comment]
This looks to be working correctly now with update v 6147. Both the pull from the chest and deliveryman...

**Comment by Raycoms** [comment]
great
