### ISSUE TITLE
Crashing upon placing townhall (again)

### ISSUE THREAD

**Issue by mvdhoning** [ldtteam/minecolonies#1894]
minecolonies-universal-1.12.2-0.8.4932
MC ver. 1.12.2
Forge ver. 1.12.2 - 14.23.1.2555

Updated to a newer forge for forestry and binnies and the same situaties as here occurs
https://github.com/Minecolonies/minecolonies/issues/1615

**Comment by Raycoms** [comment]
Yeah you'll have to update minecolonies to a newer version to avoid this.

**Comment by Raycoms** [comment]
At least to a beta.
