### ISSUE TITLE
[Feature] Citizens thank you for food

### ISSUE THREAD

**Issue by mfmiller** [ldtteam/minecolonies#1898]
### Minecolonies version

all versions

### Expected behavior

When I feed my colonists an especially delicious, nutritious, or fancy meal, like a Pam's Harvestcraft Beef Wellington or a Delighted Meal, or a Cheeseburger with Fries and a Strawberry Shake, they don't appreciate it. It would be nice if they worked a little faster for a day, or at least said "Thank you that was a delicious meal."

### Actual behaviour

- They don't care. They only complain when they are hungry.

### Steps to reproduce the problem

1. Make your colonists a delicious Pam's meal.
2. Wait for thanks, or any kind of a reaction.
3. Keep waiting.

**Comment by Nightenom** [comment]
@bob0bob what about that any food will restore a bit of lost happiness?

**Comment by bob0bob** [comment]
@Nightenom The new happiness system has a range of a modifier that depends on the saturation level of the citizen.  As for expecting a citizen to thank you for feeding them, personally find it strange.  it is something that is expected for a person to work.

**Comment by Raycoms** [comment]
Closed in favor of joint issue.
