### ISSUE TITLE
colony data lost/broken during server upgrades.

### ISSUE THREAD

**Issue by ouroborus** [ldtteam/minecolonies#1903]
Minecolonies 1.12.2-0.8.5989

Whenever the server is updated:

* Colonies always lose track of their owners
  * Colony info claims the correct player as an owner, but player can't access anything they normally would otherwise.
  * `/mc colony refresh` usually fixes this but shouldn't be necessary
* Colonies forget their officers, etc.
  * There's no fix for this aside from having the owner re-add the other players.
* Colonies disassociate from their buildings.
  * No fix for this outside of breaking the building control blocks then using the wand to re-start construction from scratch.
  * This doesn't always happen. Seems to happen to colonies that aren't in the overworld. For me, the colony that this happens to is in an RFTools dimension. The colony in the overworld doesn't have this problem.

There needs to be some way to resurrect a colony that's been broken like this. I propose recording each building's info (type is recorded, level isn't, other data may be needed for reconstruction of the colony data) in the building's control block NBT and making it so that `/mc colony refresh` also scans the area inside the colony perimeter and re-adds disassociated buildings.

I also propose adding an admin-only command for instantly constructing/upgrading a building, creative style.

**Comment by Raycoms** [comment]
Hi, we currently offer no support for colonies outside of the overwold, we
are still working on this

**Comment by ouroborus** [comment]
@Raycoms I understand. That still leaves colonies losing track of their owners during a server update. This happens to all colonies with each colony needing its own `/mc colony refresh` to fix.

**Comment by Raycoms** [comment]
@ouroborus Yeah, I hope the newest alpha resolves this.
We're trying to track this down, but it seems a minecraft error.
