### ISSUE TITLE
Lumberjack having to rebuild

### ISSUE THREAD

**Issue by Lordbaane** [ldtteam/minecolonies#1905]
### Minecolonies version

version 08.5085 or curse X.X.XX

### Expected behavior

- Once built , lumberjack hut stays active
### Actual behaviour

- due to some issue of trees being too close it causes the hut to become inactive and you have to reconstruct it. ONce updated to level two, it happens again and you have to start at level one again.

### Steps to reproduce the problem

1. XYZ
2. ZYX
3. ...
4. Profit

**Comment by Raycoms** [comment]
does this problem persist in newer versions?

2017-12-24 21:26 GMT+00:00 Lordbaane <notifications@github.com>:
