### ISSUE TITLE
Level 5 builders hut not creating requests

### ISSUE THREAD

**Issue by WalnutWhip** [ldtteam/minecolonies#1906]
### Minecolonies version

minecolonies-universal-1.12.2-0.8.6204.jar

### Expected behavior

Builders in a builders hut create requests for things to be built for either player attention or deliveryman attention

### Actual behaviour

no requests are made and the builder stands there even if there is materials in the warehouse and deliveryman available. The builders will also not remove materials out of their assigned builders hut chest. The builder will only work if you manually place all items into their inventory at once. Sometimes the materials are fetched but the level 5 builder will not retrieve them from the builders hut.

### Steps to reproduce the problem

1. Go from level 4 builders hut to level 5
2. The request behaviour breaks
3. ...
4. Profit

**Comment by Raycoms** [comment]
a) does this problem persist in 6211?
b) is there a log?

2017-12-24 23:39 GMT+00:00 WalnutWhip <notifications@github.com>:

**Comment by WalnutWhip** [comment]
Sorry i dont think i have access to a log, but ive recommended the server owner to update it again and the behavior seems to be fixed in minecolonies-universal-1.12.2-0.8.6215.jar
