### ISSUE TITLE
Can't Build a builder huts

### ISSUE THREAD

**Issue by webcrafter-fr** [ldtteam/minecolonies#1913]
### Minecolonies version

version 1.12.2-0.8.6291

### Expected behavior

- Get the builder hut

### Actual behaviour

- When I try to craft a builder hut I get nothing. Others craft are working.

**Comment by Raycoms** [comment]
door in the middle and build tool on top with planks around the rest?

2017-12-26 22:05 GMT+00:00 Aurélien Leclerc <notifications@github.com>:

**Comment by webcrafter-fr** [comment]
Yep.

**Comment by Raycoms** [comment]
Working perfectly for me, are you using an oak door?

2017-12-26 22:20 GMT+00:00 Aurélien Leclerc <notifications@github.com>:

**Comment by webcrafter-fr** [comment]
I tried oak, and acacia, it's the same :/ It must work for every type of doors ?

**Comment by Raycoms** [comment]
have you any mod installed which changes doors?

2017-12-26 22:52 GMT+00:00 Aurélien Leclerc <notifications@github.com>:

**Comment by webcrafter-fr** [comment]
Hmm I don't think so. I got thoses mods : 

- ClockHUD
- CraftSaddles
- HearthstoneMod
- InventoryTweaks
- Prefab
- Signpost
- WearablesBackpacks

**Comment by Raycoms** [comment]
That's strange, the recipe works perfectly for me, did you try
redownloading the jar already?

2017-12-26 22:56 GMT+00:00 Aurélien Leclerc <notifications@github.com>:

**Comment by webcrafter-fr** [comment]
Ok, my bad. I haven't tried Oak Door, it was an Spruce Door. It works fine with an Oak Door.

I don't understand... Why it's working with an oak door only ? The wiki show the recipe with an Acacia Door btw. 

Anyway, thanks for your help :)

**Comment by Raycoms** [comment]
I guess our dev which made the recipe in 1.12 did something wrong, will
contact him.

2017-12-26 23:14 GMT+00:00 Aurélien Leclerc <notifications@github.com>:

**Comment by webcrafter-fr** [comment]
Thanks a lot !
