### ISSUE TITLE
1.12.2 Minecolonies Pack

### ISSUE THREAD

**Issue by janagyjr** [ldtteam/minecolonies#1925]
### Minecolonies version

Minecolonies 4.7 for MC 1.12.2

### Expected behavior

- Server to launch

### Actual behaviour

- Server Crashes

### Steps to reproduce the problem

1. Download modpack
2. Copy mods and configs over to server (removing CustomMainMenu, ResourceLoader, and Betterfps, obvious client-side only mods)
3. ...
4. Crash

FML Server Latest:
https://gist.github.com/janagyjr/d325ad882acd06842089917b0a1dd940

Crash Report:
https://gist.github.com/janagyjr/fc7cf3baaa06fed8eada6d45195fb3ae

**Comment by Raycoms** [comment]
Seems to be a problem with GuideBook and CraftTweaker:

at
gigaherz.guidebook.guidebook.client.BookRegistry.<clinit>(BookRegistry.java:178)
at
gigaherz.guidebook.guidebook.ItemGuidebook.func_150895_a(ItemGuidebook.java:71)
at crafttweaker.mc1120.item.MCItemUtils.createItemList(MCItemUtils.java:38)
at
crafttweaker.mc1120.brackets.BracketHandlerItem.rebuildItemRegistry(BracketHandlerItem.java:63)
at
crafttweaker.mc1120.events.CommonEventHandler.registerRecipes(CommonEventHandler.java:39)

2017-12-27 22:26 GMT+00:00 TheCrappyGamer <notifications@github.com>:

**Comment by janagyjr** [comment]
I guess?

**Comment by Raycoms** [comment]
Did you try to start it without guidebook on the server side?

2017-12-27 22:26 GMT+00:00 TheCrappyGamer <notifications@github.com>:

**Comment by janagyjr** [comment]
No as it seems to be kind of one of those things that should be on the server. I guess it wouldn't hurt to try it w/o the guidebook.

**Comment by janagyjr** [comment]
That seemed to do it. Server prepared spawn w/o the guidebook. Is the Guidebook client-side only?
