### ISSUE TITLE
Npc and Building Issue 

### ISSUE THREAD

**Issue by Airisii** [ldtteam/minecolonies#1926]
### Minecolonies version

version 0.9.6314

### Expected behavior

- Npcs to run smoothly
- Restaurant to be built to level 5
- Have all the items asked for in request slot

### Actual behaviour

- Npcs stopping and not moving
- Restaurant build level 4/5 not wanting to build
- Npcs asking for item that are not shown in the request slot

### Steps to reproduce the problem

1. Npc fix
2. Restaurant build fix

**Comment by Raycoms** [comment]
please try the newest version.

2017-12-27 23:32 GMT+00:00 LegendaryCrystalFox <notifications@github.com>:

**Comment by Raycoms** [comment]
Sorry it's still under review. It should have fixes for those issues.

**Comment by Raycoms** [comment]
4 hours now, twitch is really happy today.

**Comment by Airisii** [comment]
Im not sure if I understand. I have the newest version of minecolonies unless you're meaning for a later release?

**Comment by Raycoms** [comment]
![image](https://user-images.githubusercontent.com/6438347/34396191-b26ce850-eb5f-11e7-9398-63c8cd501610.png)

**Comment by Airisii** [comment]
How do I find where the Under Review is?

**Comment by Raycoms** [comment]
Or wait until twitch approves it, or directly here:
https://s3.eu-central-1.amazonaws.com/minecolonies/Minecolonies/Minecolonies_Alpha/6341/minecolonies-universal-1.12.2-0.8.6341.jar

**Comment by Airisii** [comment]
I need 1.10.2

**Comment by Airisii** [comment]
Thank you so much for your help!
