### ISSUE TITLE
game crashes when trying to build townhall

### ISSUE THREAD

**Issue by forReason** [ldtteam/minecolonies#1927]
### Minecolonies version

version 1.12.2-0.8.4191

### Expected behavior

- when using the building tool after the correct position is found the townhall chest is placed by clicking on the arrow sign

### Actual behaviour

- as soon as I press the green tickbox the map crashes and I receive the message "fatal error, internal server has been shut down"

### Steps to reproduce the problem

1. build the startership
2. obtain building tool and th chest
3. search for a nice location and press the green build button
4. game crashes

**Comment by Raycoms** [comment]
That should be fixed in one of the 2000 last versions =) We'll release soon a new beta =)

**Comment by forReason** [comment]
where can I get those versions?

**Comment by Raycoms** [comment]
https://minecraft.curseforge.com/projects/minecolonies

2017-12-28 0:11 GMT+00:00 Julian B. <notifications@github.com>:

**Comment by forReason** [comment]
so I should use the latest alpha? Problem occurs with the latest release

**Comment by Raycoms** [comment]
Yes, latest alpha should be decent. (But take care, after going alpha there
is no way back to release or beta)

2017-12-28 0:14 GMT+00:00 Julian B. <notifications@github.com>:

**Comment by forReason** [comment]
thank you, latest alpha works
