### ISSUE TITLE
Lumberjack fired when I disconnect

### ISSUE THREAD

**Issue by webcrafter-fr** [ldtteam/minecolonies#1929]
### Minecolonies version

version 1.12.2-0.8.62.91

### Actual behaviour

Ok so, my lumberjack do his work properly but when I quit the game and I reconnect he's no more assigned to his hut. All his EXP is loosed and now I can build his hut again but my builder do nothing.

I tried to destroy and rebuild the hut but it's still not working, I don't know what to do. 

### Steps to reproduce the problem

- Built Lumberjack hut
- Assign a npc
- Disconnect
- Reconnect
- The npc isn't assigned anymore and loose his EXP.
- Click the "build" button
- The builder is comming
- The hut is created
- I can assign the NPC

Thanks for your help <3

**Comment by Raycoms** [comment]
Can you send us the log? (Shutdown and restart log)

2017-12-28 20:32 GMT+00:00 Aurélien Leclerc <notifications@github.com>:

**Comment by webcrafter-fr** [comment]
Yep.

[latest.log](https://github.com/Minecolonies/minecolonies/files/1592092/latest.log)

Edit : I tried with the last version btw (minecolonies-universal-1.12.2-0.8.6341) but it still not working
Edit : I also tried to repair the building

**Comment by Raycoms** [comment]
can you try the newest 1.12 version?

2017-12-28 20:58 GMT+00:00 Aurélien Leclerc <notifications@github.com>:

**Comment by webcrafter-fr** [comment]
I have already tried the minecolonies-universal-1.12.2-0.8.6341 version :(

**Comment by Raycoms** [comment]
Oh ugly, found it. Will be fixed soon.

2017-12-28 21:02 GMT+00:00 Aurélien Leclerc <notifications@github.com>:

**Comment by Raycoms** [comment]
Should be uploading soon.

2017-12-28 21:12 GMT+00:00 Ray Neiheiser <ray.neiheiser@gmail.com>:

**Comment by webcrafter-fr** [comment]
Thank you ! :)

**Comment by webcrafter-fr** [comment]
Wow I have huge lags since I installed the 1.12.2-0.8.6341 version O_o

**Comment by Raycoms** [comment]
any exceptions running through the console?

2017-12-28 21:18 GMT+00:00 Aurélien Leclerc <notifications@github.com>:

**Comment by webcrafter-fr** [comment]
If I open the console in game with "/" it show nothing but I have many problems in the logs : 

[latest.log](https://github.com/Minecolonies/minecolonies/files/1592144/latest.log)

**Comment by Raycoms** [comment]
Hmm strange, doesn't say anything about minecolonies though =/ can you find
out  which worker causes it?

2017-12-28 21:25 GMT+00:00 Aurélien Leclerc <notifications@github.com>:

**Comment by webcrafter-fr** [comment]
How ?

**Comment by Raycoms** [comment]
just fire all of a certain type and check if it still lags.

2017-12-28 21:28 GMT+00:00 Aurélien Leclerc <notifications@github.com>:

**Comment by webcrafter-fr** [comment]
If I fire them they will loose their EXP ?

**Comment by Raycoms** [comment]
not if you rehire them to the exact same job

2017-12-28 21:36 GMT+00:00 Aurélien Leclerc <notifications@github.com>:

**Comment by webcrafter-fr** [comment]
It seems to be the builder. I'm not sure. When I fired him I have no more lags, I hired him and still no lags. But when I give to him the items he needs to continue his building, the lags appears. 

I have some errors in the logs : 

[latest.log](https://github.com/Minecolonies/minecolonies/files/1592183/latest.log)

Edit : The builder has finished his job, no more lags.
Edit 2 : Nevermind, I still have lags :/

**Comment by Raycoms** [comment]
Yeah but those are mostly not minecolonies related problems.
Will have to debug the builder then.

2017-12-28 21:45 GMT+00:00 Aurélien Leclerc <notifications@github.com>:

**Comment by webcrafter-fr** [comment]
I tried the last version (1.12.2-0.8.6357). It works fine. The lumberjack problem is gone.

I returned on the 1.12.2-0.8.6291 version and the lags are still there. But the lumberjack problem is gone too... I don't understand :D I will restart my computer and test again the last version.

Thoses warnings are normal ? : 

`[23:00:57] [main/WARN]: File minecolonies:sounds/mob/deliveryman/female/inhaleexhale1.ogg does not exist, cannot add it to event minecolonies:mob.deliveryman.female.noise`

`[23:00:57] [main/WARN]: File minecolonies:sounds/mob/builder/female/whatisit.ogg does not exist, cannot add it to event minecolonies:mob.builder.female.interaction`

`[23:00:57] [main/WARN]: Missing sound for event: minecolonies:mob.guard.archer.female.badhousing`

`[23:01:01] [main/WARN]: Texture minecolonies:textures/blocks/info/info_poster_wax.png with size 12x12 will have visual artifacts at mip level 4, it can only support level 2. Please report to the mod author that the texture should be some multiple of 16x16.`

`[23:01:07] [main/WARN]: Skipping bad option: lastServer:`

**Comment by Justen-N** [comment]
Yeah, there are still some sound issues, but those errors are not
performance related.

**Comment by webcrafter-fr** [comment]
Ok so I tried a lot of different things but my game is totally broken... 

No matter wich version I'm using, the lumberjack is fixed but I got lags. I just can't play anymore...

If I uninstall the mod the lag disapear.

**Comment by Raycoms** [comment]
This is strange, can you send me your world?

2017-12-28 23:35 GMT+00:00 Aurélien Leclerc <notifications@github.com>:

**Comment by webcrafter-fr** [comment]
oh-my-god.

my world has gone from 38 MB to 631 MB. In my world there is a "minecolonies" folder 547 MB.

I think the problem is here. I got many files from 3ko to 46 MB. Maybe it's because I tried multiple times to rebuild my lumberjack ? I don't know. Should I delete thoses files ? I don't want to loose all my progress :(

**Comment by Raycoms** [comment]
Okay wow inside the minecolonies folder there is a colonies.dat, how big is
it?

**Comment by webcrafter-fr** [comment]
46 MB

https://i.imgur.com/o8ISkHK.jpg

**Comment by Raycoms** [comment]
You can delete all the other. Data there, can you send me the 46 MB one?

**Comment by webcrafter-fr** [comment]
Yep

[colonies.zip](https://github.com/Minecolonies/minecolonies/files/1593016/colonies.zip)

**Comment by Raycoms** [comment]
That was helpful, I found the issue =).
You have 100.000 saplings and ores registered with our system which the
workers have to search through.  I messed something up there, will have to
check before adding.
You can try to open the dat with an nbt editor and remove the saplings and
ores in the colonymanager.

2017-12-29 11:22 GMT+00:00 Aurélien Leclerc <notifications@github.com>:

**Comment by webcrafter-fr** [comment]
Why I have so many saplings and ores ? My miner don't bring me so much stuff :p 

I got many errors when I open the colonies.dat with notepad, I'm maybe wrong. 

I don't know how to do this. Can you clean my colonies.dat and send me the file ? 

If I install again minecolonies (latest version), will I have the same bug ? Or it's ok now ? Should I wait the next update ?

**Comment by Raycoms** [comment]
I think you should wait until the next update, I'm currently working on a
code which should clean up that mess.

2017-12-29 12:09 GMT+00:00 Aurélien Leclerc <notifications@github.com>:

**Comment by webcrafter-fr** [comment]
Ok, I'm waiting the next version :) Thank you for your work, this mod is really cool 👍

**Comment by webcrafter-fr** [comment]
Is the 1.12.2-0.8.6368.jar ok ? 

How can I install this version properly ?

**Comment by Raycoms** [comment]
Like the others, it automatically fixes your issue.

**Comment by webcrafter-fr** [comment]
I'll try this ! Thanks !
