### ISSUE TITLE
LJ gets fired when building upgrades

### ISSUE THREAD

**Issue by Lordbaane** [ldtteam/minecolonies#1930]
### Minecolonies version

version1.11.2-0.8.6298 or curse X.X.XX

### Expected behavior

- When you upgrade LJ all is good

### Actual behaviour

- After you upgrade LJ the building resets to level 0

### Steps to reproduce the problem

1. Three different worlds, each time it is upgraded is goes back to level 0
2. Tried different systems, happened twice, checked to see if foreign blocks are affecting the LJ building
3. Has happened even if trees are farther away.
4. Need to check code to see if some object is causing it to reset. Builder deconstructs LJ back to level 1.

https://paste.ubuntu.com/26274687/

**Comment by Lordbaane** [comment]
I did post a previous issue about this, but with the latest update I figured it was fixed. I also see some similar issues with LJ as well, so maybe a bigger issue. It only happens with the LJ.

**Comment by Raycoms** [comment]
try 6357

2017-12-28 23:11 GMT+00:00 Lordbaane <notifications@github.com>:

**Comment by Lordbaane** [comment]
Okay, just a side note, the builder is now upgrading to lvl 3
