### ISSUE TITLE
[Enhancement] Add option to tell the miner to strip mine.

### ISSUE THREAD

**Issue by harleypig** [ldtteam/minecolonies#1931]
### Minecolonies version

any

### Expected behavior

An option (either config file or tab in the miner's chest) to strip mine or random (as it currently does).

### Actual behavior

No way currently to tell miner to strip mine.

### Steps to reproduce the problem

None

**Comment by Raycoms** [comment]
Yeah we actually have it on purpose that he goes as deep as possible first, also considering that this is also as efficient as going sidewards.

**Comment by harleypig** [comment]
I'm sorry ... I wasn't referring to depth. There is already an option to stop mining down and start mining sideways.

I'm asking for an option to have the miner strip mine sideways instead of randomly. Basically, tunnels two blocks wide, with occasional two block wide cross tunnels.
