### ISSUE TITLE
Don't appear new citizens

### ISSUE THREAD

**Issue by caiiiok107** [ldtteam/minecolonies#1932]
### Minecolonies version

version 0.8.6257

### Expected behavior

- After building the house, new citizens had to start spawning, i think

### Actual behaviour

- When the townhall was built, four residents appeared, all of them women. New residents do not start showing up, at the 2 level townhall and 2 level home

**Comment by Raycoms** [comment]
You need at least 5 building levels of the citizen Hut for new citizens to appear
