### ISSUE TITLE
Mc closed when pleacing Town Hall

### ISSUE THREAD

**Issue by TheErpuk** [ldtteam/minecolonies#1934]
### Minecolonies version

minecolonies-universal-1.12.2-0.8.4932

### Expected behavior

- I exepted a table where you are able to start du creat your own colonie

### Actual behaviour

- The Map was closed and the alert "shutting down internal server / Connection Lost / A fatal error has occurred, this connection is terminated / Back to server list" appiert!

### Steps to reproduce the problem

1. I play this Mod in Single Player
2. Every thing is working
3. Pleaced the Town Hall Item which I get from the supplied camp.
4. The Map was closed and the alert "shutting down internal server / Connection Lost / A fatal error has occurred, this connection is terminated / Back to server list" appiert!
5. Now I can´t play on this Map.
6. The error comes again

I Hope you can fix it 
I like this Mod

LG

**Comment by Raycoms** [comment]
Please use a newer version or an older forge version.

2017-12-29 19:58 GMT+00:00 TheErpuk <notifications@github.com>:

**Comment by TheErpuk** [comment]
It works!
Thanks alot
