### ISSUE TITLE
My NPCs don't eat

### ISSUE THREAD

**Issue by webcrafter-fr** [ldtteam/minecolonies#1937]
### Minecolonies version

Latest

### Expected behavior

- The NPC eat the food in his inventory

### Actual behaviour

The NPC is hungry but eat nothing. The builder is the only one who is eating (steak). I tried different foods but I got the same problem. Maybe I miss something ?

More questions : 

- Is it normal to have only npcs with 1 point for each skill  ?
- I killed many pnj to try to have a good skilled one but it don't work. We need to have a good happiness to have hight skilled NPC ? How can I grow up their happiness ? Feed them only ?
- I have a guard. I get attacked but he did nothing. Is it normal ?

Thanks

**Comment by Raycoms** [comment]
Is the npcs hunger at 0? Doesn't eat anything when you put it in his inv? they always do it for me.
Yes, the skills depend on the happiness of the colony, and when you kill them it drops to 0.
And yes, the guard does try to detect mobs and not attacks.

**Comment by webcrafter-fr** [comment]
Their hunger isn't at 0. And yes, they doesn't eat anything when I put food in their inventory. Only the builder ate the steak I gave him but he stopped doing it... Why closing the topic so fast ? Am I doing it wrong ?

**Comment by Raycoms** [comment]
I guessed, they only eat if hunger falls under 7 as well, that might be it.

2017-12-30 1:25 GMT+00:00 Aurélien Leclerc <notifications@github.com>:

**Comment by webcrafter-fr** [comment]
Oh ok, good to know :) The wiki need a little rework :P Thanks.
