### ISSUE TITLE
The lumberjack don't take enchanted axes

### ISSUE THREAD

**Issue by webcrafter-fr** [ldtteam/minecolonies#1938]
### Minecolonies version

Latest

### Expected behavior

- The lumberjack take and use enchanted axes

### Actual behaviour

The lumberjack don't take enchanted axes

**Comment by Raycoms** [comment]
What's his hut level?

**Comment by webcrafter-fr** [comment]
Hut lvl 2 
Worker lvl 1

**Comment by Raycoms** [comment]
Yeah he starts using them only on level 4 upwards.

**Comment by webcrafter-fr** [comment]
Ok thanks :)
