### ISSUE TITLE
Unknown NPC

### ISSUE THREAD

**Issue by webcrafter-fr** [ldtteam/minecolonies#1939]
### Minecolonies version

Latest

### Expected behavior

- In the tchat : "<NPC NAME> Is in need of shovel ...

### Actual behaviour

- In the tchat : "<UNKNOWN> is in need of shovel ...

### Steps to reproduce the problem

I don't know... And "Unknown" doesn't even exist. I don't see him :/

**Comment by webcrafter-fr** [comment]
Any idea ?

**Comment by Raycoms** [comment]
the clipboard has no information?

2018-01-03 22:01 GMT+00:00 Aurélien Leclerc <notifications@github.com>:

**Comment by webcrafter-fr** [comment]
What's the clipboard ?

**Comment by Raycoms** [comment]
an item, crafted with leather in the middle sticks around and buildtool on
top

2018-01-03 22:14 GMT+00:00 Aurélien Leclerc <notifications@github.com>:

**Comment by webcrafter-fr** [comment]
https://i.imgur.com/ixyi9ta.jpg

I canceled the request, we'll see what's next :) Thanks.

Why the wiki is not up to date ? :( This plugin is amazing, he deserves a better one ! ❤️

**Comment by Raycoms** [comment]
Oh we're working on it =)

2018-01-03 23:13 GMT+00:00 Aurélien Leclerc <notifications@github.com>:

**Comment by webcrafter-fr** [comment]
Nice 😄
