### ISSUE TITLE
Mis-spelled method, maybe?

### ISSUE THREAD

**Issue by Kira076** [ldtteam/minecolonies#1947]
### Minecolonies version

version 1.11.2-0.8.6369

### Expected behavior

- The game loads and doesn't crash

### Actual behaviour

- The game crashes. Crash log: https://pastebin.com/TgTiGKvi

### Additionally:
This seems to have only started happening after I added Mantle, Tinkers' Construct, Embers, and Reliquary to the pack. Before I did that, it was loading in fine, but after that it crashed. As far as I can tell, "CompatabilityManager" is a mis-spelling somewhere.

### Update:
I just tried re-testing my pack, adding the new mods one at a time until it crashed... But it never did. I'm not entirely sure what caused it to crash that time.

### Update Two:
It appears to crash when starting the server with a world already generated... So if it has to generate a world, it works fine. If there's already a world folder, it crashes.

### Update Three:
Found it. I must have changed the Sponge jar, or possibly I had forgotten to include it previously... It seems it's what's triggering the whole thing.

**Comment by Raycoms** [comment]
Just pushed the fix
