### ISSUE TITLE
[Enhancement] Guards use barracks chest for armour supply

### ISSUE THREAD

**Issue by MattBeard** [ldtteam/minecolonies#1948]
### Minecolonies version

version 1.12.2-0.8.6403

### Expected behavior

- Guards should protect themselves better

### Actual behaviour

- I have to hand out armour manually

### Suggestion

- Every now and then (perhaps every 10 to 30 seconds depending on what routine they are running) each guard compares items of armour in the barracks chest with corresponding armour they are wearing and if they find a better item they swap so they are wearing the better one and the worse one is in the barracks chest.
- Comparisons should not consider wear level, only strength/durability (otherwise they will constantly keep swapping out worn armour for slightly less worn, it wears out a little, they swap it again etc.)
- Better yet, they should first look in their own tower chest, and then in the barracks chest. Items they take off should always be returned to the barracks chest so they can be used by guards from other towers in the same barracks.
- When a guard is set to patrol, the resetting of the patrol list to the top would be a great time to do the check.
- You could chose for the guard to always physically go to the chest (or close to it ) to check, or perhaps only go to it if and when a swap occurs (that would be my choice).
- Could the same routine work for guard towers and their chest?

**Comment by Justen-N** [comment]
Yeah, this one is my fault.  Currently in progress.

**Comment by Raycoms** [comment]
Yeah we have an issue for that already.

Thanks for the report =)
