### ISSUE TITLE
Cooks ?

### ISSUE THREAD

**Issue by webcrafter-fr** [ldtteam/minecolonies#1949]
In the Townhall GUI we can see in the jobs list "cooks" but he's not in the wiki. Is it implemented ?

Thanks :)

**Comment by Raycoms** [comment]
It is, wiki missing still @Wissi

**Comment by webcrafter-fr** [comment]
How can I craft him ? :)

**Comment by Raycoms** [comment]
apple in the middle =D

2018-01-01 15:08 GMT+00:00 Aurélien Leclerc <notifications@github.com>:

**Comment by webcrafter-fr** [comment]
Thanks :)
