### ISSUE TITLE
Large fern impossible to get in survival (TownHall3, Birtch)

### ISSUE THREAD

**Issue by Azuxul** [ldtteam/minecolonies#1953]
### Minecolonies version

version 1.12.2-0.8.5081

### Steps to reproduce the problem

1. Upgrade TownHall to lvl 3
2. See requiments list

![2018-01-02_00 49 36](https://user-images.githubusercontent.com/11092555/34471985-d89ba804-ef56-11e7-8279-8dbacb59e751.png)

### More informations

In survival is impossible to get large fern as item so is imposible to give to the builder.

See #1275

**Comment by Raycoms** [comment]
There should be a recipe with two small ferns over each other.

2018-01-01 23:50 GMT+00:00 Lancelot H. <notifications@github.com>:

**Comment by Azuxul** [comment]
But there are no recipe, NBT do not show recipe too and when i try is not working.

See : 

![2018-01-02_01 12 34](https://user-images.githubusercontent.com/11092555/34472109-44c56ea4-ef5a-11e7-8fdb-519d0f8b5636.png)

**Comment by Raycoms** [comment]
@MineShadow7 can you add that recipe please?

**Comment by Echo51** [comment]
Please add the recipe to the recipe-list in the wiki ( https://wiki.minecolonies.com/source/misc/recipes )
