### ISSUE TITLE
Builder Crash when given shovel

### ISSUE THREAD

**Issue by teagan75** [ldtteam/minecolonies#1954]
### Minecolonies version

minecolonies-universal-1.10.2-0.9.6457.jar

### Expected behavior

Should be able to give a wooden shovel to builder.

### Actual behaviour

Crashes to desktop. Doesn't happen each time. Both female builders crashed and one male builder did not.

https://pastebin.com/ajGgZX8R

**Comment by Raycoms** [comment]
Sorry, for the delay, we're working on it.
