### ISSUE TITLE
Cannot place the townhall

### ISSUE THREAD

**Issue by Jaimartuan** [ldtteam/minecolonies#1955]
### Minecolonies version

version 0.8.4932

### Expected behavior

- Place the town hall without closing the game

### Actual behaviour

- When the town hall is placed, minecraft closes

### Steps to reproduce the problem

1. I have looked at the files of the mod and on the internet some solutions but I can not find the reason why the game closes when I put the town hall. I can only place the supply camp/ship and after that I cannot do anything else.

**Comment by Raycoms** [comment]
can you try a newer version of minecolonies, this is a forge bug.

2018-01-02 17:21 GMT+00:00 Jaimartuan <notifications@github.com>:

**Comment by Jaimartuan** [comment]
Okay, I'll try, thanks

**Comment by Jaimartuan** [comment]
Yeah, now it works!!!!! thanks
