### ISSUE TITLE
No townhall block when place camp/ship and structures are phantom (I can pass them)

### ISSUE THREAD

**Issue by jonabrv1965** [ldtteam/minecolonies#1956]
### Minecolonies version : minecolonies-universal-1.12.2-0.8.6479

MC 1.12.2 - Forge version : forge-1.12.2-14.23.1.2582

### Expected behavior

- To obtain the townhall block. 

### Actual behaviour

- The structures generated are phantom, I can pass thru them walking, cannot harvest them, theoneprobe does not detect any block, are ethereal, not solid... and I do not get the townhall block. It happens with the camp and ship.

### Steps to reproduce the problem

0. Backup world
1. Install the latest version of everything
2. load MC and the world.
3. create the camp /ship item 
4. right click with the item in the appropriate environment
5. the structure appear right there where you are standing. NO townhall block anywhere
6. the structure is ethereal (not solid) one cannot harvest it, and can walk thru it
7. close MC, restore backup, rinse and repeat... :-)

**Comment by jonabrv1965** [comment]
Uhm.. i found that you have to click again with the camp/ship item, and click in the ok button (the green one) and it materialize the camp/ship and within you get the townhall block. This mechanic should be better explained in the wiki IMHO...

**Comment by Raycoms** [comment]
Yes, will go to the wiki soon.
