### ISSUE TITLE
Farmer do nothing

### ISSUE THREAD

**Issue by webcrafter-fr** [ldtteam/minecolonies#1957]
### Minecolonies version

1.12.2-0.8.6368

### Expected behavior

- The farmer plant and recolt wheat

### Actual behaviour

- The farmer go on his farm, hit some wheat, and stop. He stays on his farm, and do nothing. During the night he's not going to sleep. 

### Steps to reproduce the problem

Simply construct a farm, a farm plot, put some seeds, watch him doing nothing :D

**Comment by Raycoms** [comment]
Hmm this is strange, I wasn't able to reproduce this, does fire/rehire help?

**Comment by webcrafter-fr** [comment]
No :( But if I "recall" him he'll works for a while, and stop again.

**Comment by Raycoms** [comment]
Is there water under the field?

2018-01-04 0:13 GMT+00:00 Aurélien Leclerc <notifications@github.com>:

**Comment by FK187** [comment]
I am having the same issue and I have a level 3 that wont handle more than one plot even though they are assigned.

**Comment by webcrafter-fr** [comment]
![Good](https://media.giphy.com/media/RgfGmnVvt8Pfy/giphy.gif)

Yeah, there was water underneath. I filled it all up and now it looks like it's working. However, I don't know if it's normal, but the worker is really slow..... Sometimes he goes around his field over and over again, but does nothing in the next field when there is work to be done.
