### ISSUE TITLE
Proposed Smelter Enhancement

### ISSUE THREAD

**Issue by pmardle** [ldtteam/minecolonies#1963]
Proposed enhancement for the Smelter Worker :)

When deconstructing enchanted weapons/tools/armour - give him a chance to salvage the enchant as an enchanted book, based on his hut level.

Hut Level 0/1 = NO chance
Hut Level 2 = 10%
Hut Level 3 = 25%
Hut Level 4 = 40%
Hut Level 5 = 60%

**Comment by MineShadow7** [comment]
Enchant books will be used by enchanter to enchant tools and items on exactly what enchantment book says. 
Ancient tome will give random enchantment.

**Comment by marchermans** [comment]
If we do this, we should multiply the chance with the durability on item. Item low durability -> lower chance to get the enchant.

**Comment by pmardle** [comment]
Sure

**Comment by webcrafter-fr** [comment]
Wait, there is a smelter worker ?

(omg the new wiki <3)

**Comment by Asherslab** [comment]
Yes webcrafter, there is, also 4 new herder workers =D

**Comment by MattBeard** [comment]
In 1.12.2-0.8.6705 the smelter hut is not being crafted when the wiki recipe is used.

**Comment by marchermans** [comment]
Yep recipe is coming in an update.
