### ISSUE TITLE
My colonist disappear and cannot open any inventory (builder, 

### ISSUE THREAD

**Issue by jonabrv1965** [ldtteam/minecolonies#1964]
### Minecolonies version 

version minecolonies-universal-1.12.2-0.8.6523 

### Expected behavior

- XXX

### Actual behaviour

- No colonist around...

### Steps to reproduce the problem

1. Colonist not shown (I had courier, builder and lumberjack)
2. Cannot open  the town hall chest nor any other chest in the town..
3. ...
4. Profit

**Comment by Raycoms** [comment]
Seems like your colony broke, try to rollback the colonies.dat in the
minecolonies folder in your world to a previous point and then recall all
your workers.

2018-01-04 17:28 GMT+00:00 jonabrv1965 <notifications@github.com>:

**Comment by jonabrv1965** [comment]
Hi Ray, yes, that did the trick. But I have to rollback four .dat files (almost a day)

Nonetheless I have to order the builder to "build" again several already existent structures. Fortunately do not ask for materials/items...

Hopefully this do not happen again...

**Comment by Schiemel** [comment]
Hi,
I have the same issue. Every time I start my world all citizens dissappear and I can't open any blocks.
Ho do I rollback the file?

Thank you

**Comment by Raycoms** [comment]
when it's a new version you can try /mc colony loadbackup
