### ISSUE TITLE
Town hall placement crashes game

### ISSUE THREAD

**Issue by TheGreatCow** [ldtteam/minecolonies#1967]
## Minecolonies version
minecolonies-universal-1.12.2-0.8.4932.jar

  ### Expected behavior

- I should be able to place the town hall without crashing

### Actual behaviour

- Exits single player whilst saying "Shutting down internal server" and then once it has disconnected it says "A fatal error has occurred, this connection is terminated"

**Comment by Raycoms** [comment]
Please use a newer version of minecolonies or an older one of forge
