### ISSUE TITLE
Client crash: Nullpointerexception - Updating screen events

### ISSUE THREAD

**Issue by xorinzor** [ldtteam/minecolonies#1969]
### Minecolonies version

version 1.12.2-0.8.6147 (as part of the All the Mods 3 modpack)

### Expected behavior

- Pressing the details button should open a screen with information

### Actual behaviour

- It crashes the client

### Steps to reproduce the problem

1. Login
2. Click the button (in the screenshot, the button underneath the shovel)
3. ...
4. Crash!
5. Profit?

![2018-01-05_17 05 38](https://user-images.githubusercontent.com/4212335/34617215-f37551de-f23a-11e7-8c8a-e5ae659b1eb4.png)

Crash log: https://pastebin.com/qubLnHKF

**Comment by marchermans** [comment]
This is fixed in a newer version. Please update.

**Comment by xorinzor** [comment]
Thanks for the quick reply, I'll pass that on!

**Comment by marchermans** [comment]
I fixed at least the same crash myself. And the line it is stating is empty in the current version. So it should be fixed. If it persist in the newer versions open this ticket back up again with a newer crash log. That should make sure that i get notified and will take a look 👍
