### ISSUE TITLE
[Feature] One blueprint items

### ISSUE THREAD

**Issue by mvdhoning** [ldtteam/minecolonies#1971]
It would be nice to have a template item that via nbt or config files can be assigned a template.
And when used like the builders wand would place only the preselected template to be build by a builder.

The builderswand feels overpowered/overwhelming due to the lots of templates to choose from.

So a special house blueprint item could via other mod be assigned as dungeon loot or have a special crafting recipe via craftweaker.

**Comment by Raycoms** [comment]
Can you explain this a bit better?

**Comment by mvdhoning** [comment]
With the 'building tool' you get to choose what you want the builder to build and where 
e.g. you could choose: decorations birch birchwall or something else.

What i would like to have is a(nother) 'building tool' that may look like a 'blueprint' that does not allow you to choose what you want to build but instead has decoration birch birchwall embedded in for example nbt data (or via config file). So if you accuire a 'building tool'/'blueprint' with nbt data (via dungeon loot or questing system or otherwise) you can use that 'building tool'/'blueprint' only to tell the builder to build the decoration birch birchwall somewhere but not something else. (with craftweaker one could add the nbt data to the 'building tool'/'blueprint')

hope this makes clearer what i want.

**Comment by Asherslab** [comment]
Okay i see what you mean, basically:
A build tool item, except the item spawns with a specific preset (locked) schematic to use, thus allowing for "gifting" schematics (Maybe even synch over server to share with over players???) also the ability for "loot" schematics and etc

**Comment by marchermans** [comment]
Yes this would be something very cool. Especially if we would lift the builder level requirements for that building. Seeing it as a guide for the builder.
So say you get a barracks level 4 (extreme rare) but still have a builder level 1 he should be able to build this building exactly once (by using the schematic)

**Comment by mvdhoning** [comment]
**Yes i want a build tool item that is locked to a specific preset schematic that looks like a blueprint.**

It would be nice to be able to set the preset locked schematic via nbt as that is configurable via craftweaker. Will be great for modpack makers.

With [craftweaker](https://minecraft.curseforge.com/projects/crafttweaker) one can 'make' those build tools with nbt and assign them to loot etc. so there is no need for minecolonies to provide features that can be done with craftweaker. But if you can do this easily from minecolonies go ahead :-)

Also these build tool items with a specifig preset (locked) schematic could be given as reward from [better questing](https://minecraft.curseforge.com/projects/better-questing) (or other quest mods).

I dont see advantages letting a builder of level 1 being able to build a blueprint of level 4. Getting a blueprint of level 4 via loot will encourage you to wanting to upgrade the builder faster to level 4.

**Comment by Nightenom** [comment]
I think we have that now, not sure which command does it

**Comment by Raycoms** [comment]
Not yet

**Comment by Nightenom** [comment]
I thought the thing we used in the event?

**Comment by someaddons** [comment]
to me this sounds like what the craftable building blocks do already, I guess one could make some more rare buildings that cannot be crafted and are obtained in a different way

**Comment by Raycoms** [comment]
Closed in favor of joint issue.

**Comment by marchermans** [comment]
@Raycoms This is already implemented. See the Commands we have for this. We used this feature in the PvP event.
