### ISSUE TITLE
Buggy Farmer

### ISSUE THREAD

**Issue by YutaTakano** [ldtteam/minecolonies#1972]
### Minecolonies version

minecolonies-universal-1.12.2-0.8.6564.jar

### Expected behavior

- Walking around field, checking crops, harvesting as they mature

### Actual behaviour

- Stands around doing nothing. Most of the time, goes home at night, comes back at dawn. Not always.

### Steps to reproduce the problem

1. Assign worker to farm, assign field, etc (standard field steps)

### Additional notes

- This is the second farmer I've tried (in the same location).
- Getting the farmer to make/till/seed the farm was also buggy - a lot of the time I had to hit him/her to get the farmer to start moving again.

**Comment by Raycoms** [comment]
is there water under the farm?

2018-01-07 0:04 GMT+00:00 Yuta <notifications@github.com>:

**Comment by YutaTakano** [comment]
@Raycoms yes, it's built over a river.

**Comment by Raycoms** [comment]
Please build one more row of dirt, the pathfinding gets crazy if the block
under a field block is water. (We have an issue for that already, but it's
very complicated).

2018-01-07 1:07 GMT+00:00 Yuta <notifications@github.com>:

**Comment by YutaTakano** [comment]
Thank you!
