### ISSUE TITLE
[BUG] The cook get stuck with restaurant

### ISSUE THREAD

**Issue by AlexandrePavy** [ldtteam/minecolonies#1985]
### Minecolonies version

1.12.2-0.8.6291 -  and i checked with 1.12.2-0.8.6623 too.

### Expected behavior

- The cook fed the citizens without paused (I am a bad boss!)

### Actual behaviour

- The cook stops work, the other citizens come to the restaurant and wait for food.
- Exception in console and cook take pause (100-200 seconds).

It seems that the rack is involved.

[Error-console-with-restaurant.txt](https://github.com/Minecolonies/minecolonies/files/1612494/Error-console-with-restaurant.txt)

### Steps to reproduce the problem

1. Build colony with restaurant
2. Put somes stuff on chest + rack (like coal and delicius potatoes)
3. The cook cooks a few items and then take a break by the server
4. Profit

Thanks.

**Comment by Raycoms** [comment]
Looking at it now

**Comment by Raycoms** [comment]
Should be fixed now.

**Comment by AlexandrePavy** [comment]
Hello, i update to 1.12.2-0.8.6990 and my cook crash again (it doesn't freeze anymore)

[cook-crash-console.txt](https://github.com/Minecolonies/minecolonies/files/1648110/cook-crash-console.txt)

i have also my Delivery man crash

[delivery-man-crash-console.txt](https://github.com/Minecolonies/minecolonies/files/1648114/delivery-man-crash-console.txt)

Thanks !

**Comment by Raycoms** [comment]
The dman will be fixed soon, the cook I'll fix =)

2018-01-19 22:53 GMT+00:00 Alexandre PAVY <notifications@github.com>:
