### ISSUE TITLE
[BUG] FPS drop on client with clipboard

### ISSUE THREAD

**Issue by AlexandrePavy** [ldtteam/minecolonies#1986]
### Minecolonies version

1.12.2-0.8.6731

### Expected behavior

- fluid game with clipboard 

### Actual behaviour

- When i use clipboard my FPS decrease :

Without clipboard i run with 130 fps (I have max framerate to 130) 
![drop-fps-1](https://user-images.githubusercontent.com/6603411/34684802-a0ed7784-f4a6-11e7-95a1-8f6eed9e975a.png)

When i open clipboard i got less 10 fps
![drop-fps-2](https://user-images.githubusercontent.com/6603411/34684804-a11100d2-f4a6-11e7-8b9d-ffcc7b97ac00.png)

On item show my FPS are back 
![drop-fps-3](https://user-images.githubusercontent.com/6603411/34684805-a131531e-f4a6-11e7-9385-1ff516c4449b.png)

### Steps to reproduce the problem

1. Set up a clipboard with your colony 
2. Wait one or more Request
3. See your FPS decrease
4. Profit

Thanks !

**Comment by AlexandrePavy** [comment]
I just tried without optifine, I have the same fall of fps.

**Comment by marchermans** [comment]
I will need to debug this. I coded this, and i did not have this.

**Comment by nick-johnson** [comment]
Hate to bump the issue, but I am continuing to see this drop in FPS in the current version as well.

Forge 14.23.4.2708
Minecolonies 1.12.2-0.8.9540
Occurs with or without Optifine 1.12.2 HD U D2

**Comment by Raycoms** [comment]
We're currently still reworking the RequestSystem for crafting workers,
that's why we're needing a bit longer =)

2018-06-18 13:51 GMT-03:00 nick-johnson <notifications@github.com>:

**Comment by Raycoms** [comment]
This should be better in the newest builds. But it will be completelt fixed with the next blockout
