### ISSUE TITLE
[Enhancement] Animal babies escape Herders hut

### ISSUE THREAD

**Issue by AlexandrePavy** [ldtteam/minecolonies#1987]
Firstly thanks a lot, this mod is awesome, You add some cool features ! 👍 

### Minecolonies version

1.12.2-0.8.6731

### Expected behavior

- The Herders do not lose animals, otherwise the wolves eat them!

### Actual behaviour

- There are some smart little animals that escape from the pen (look pictures)

They jump on the wheat block.

![farmer-hut-1](https://user-images.githubusercontent.com/6603411/34686776-fbe26b12-f4ac-11e7-8ae6-ffce3b6f003e.png)

![farmer-hut-2](https://user-images.githubusercontent.com/6603411/34686777-fc0e0d08-f4ac-11e7-8e18-b4d355d0bb56.png)

### Steps to reproduce the problem

1. Build herders (Level 4 or 5) (below there is not the problem)
2. Watch the chickens (and pigs) escape from your meal
3. Profit

Thanks !

**Comment by Asherslab** [comment]
Ahhh apologies, we'll definitely have a look at the schematics for the herder buildings at some point, sadly i'm a horrible builder so i had to get some others to build them for me, if you'd like you could help me get those fixed quick?
BTW, our discord: https://discord.gg/zjA75K8

**Comment by Monarch-of-Gold** [comment]
I'd be willing to do some buildings for you. I've got schematica installed so turning them into schematics isn't a problem
