### ISSUE TITLE
[Suggestion] Show cause of unhappiness in the townhall

### ISSUE THREAD

**Issue by Aynjul** [ldtteam/minecolonies#1990]
### Minecolonies version
1.12.2-0.8.6705

I can't figure out what is causing my happiness not to rise in my colony. It would be nice if I could go to the town hall to find out why my colonists aren't happy. The colonists could report every day what they are not liking. Thank you.

**Comment by Wissi** [comment]
I agree that would be a great enhancement as well.
Maybe show all of the factors involved in the happiness system and then show a "value" next to each one (maybe in green/orange/red colors) to let us see what needs more attention/improvement to reach the highest happiness level possible.

**Comment by Aynjul** [comment]
That would be amazing!
