### ISSUE TITLE
Chunks loading problem and other.

### ISSUE THREAD

**Issue by attilavv** [ldtteam/minecolonies#1992]
version 
minecolonies-universal-1.12.2-0.8.5081
upgraded to
minecolonies-universal-1.11.2-0.8.6745

And other mods.

Forge version : 14.23.1.2565 
1 - Chunks loading problem
![chunks](https://user-images.githubusercontent.com/35277791/34747449-98859386-f598-11e7-889e-1a1502bd80ab.jpg)
Some time many chunks is loaded from one to another city ( probably from a bad town hall to ?? )
In top right it is my village and bottom left is it the village from my friend.

Problem is alway present with minecolonies-universal-1.11.2-0.8.6745

2 - PNJ duplacation.

![double pnj](https://user-images.githubusercontent.com/35277791/34747618-567bcf54-f599-11e7-86e1-c5e080a752c3.jpg)

This time my server need reboot but max memory is back. After reboot a PNJ is duplicated.
Not see at this time with minecolonies-universal-1.11.2-0.8.6745

3 - Tested on local and server same time all tread - 1 is at 100% usage of CPU. On my good server TPS is over 19/20. It is possible you are out the schulduler from Minecraft/forge. In local on Windows 10 PC it is sheduler from windows that cut your loop. Probably is windows cup your loop it is a problem and no memory free command and server it need more and more CPU/Memory. 

And my server on Verygames, it is Linux and schuduler can limite to a core. Same speed for 2 logicals cores.

----------

Add a command on town hall for stop new pnj and  for kill / free all pnj or for disable city. But at this time soluce for testing is waiting for construct many and many building. With a option for place city in pause it is a good method for testing.

Add a command in town hall or on config file for difficulty same minecraft : peacefull / easy / hard. For stop barbarians. In multiplayer without player many barbarians spawn and wheen you come back it is no soluce. It is possible source of problem. Place a city in pause if player is not present. 

Sorry for my poor english but French.

**Comment by AlexandrePavy** [comment]
Hi, are you using `minecolonies-universal-1.11.2-0.8.6745` with `1.12.2` server ? maybe try with `1.12.2-0.8.6731`

**Comment by Asherslab** [comment]
Sorry not sure what a PNJ is. for issue 1 we do not load any chunks what-so-ever in our code, anything that is happening is either another mod, your server, players, or forge itself

**Comment by attilavv** [comment]
Hi,

For 1, all mob like cow, chicken and other can move and when it change chunk it is a loading process that start. It is for this raison you can see some loaded chunk it the path when you move and use command "/chunkloaders" from ChickenChunks. Problem is all time it is between two village and some time between a player position and a not loader zone. 

At this time, without Obis or other test mods it is hard to find real problem. 
I find this issue : Issues Inherent with Chunk Loading and Unloading #1351
[https://github.com/Minecolonies/minecolonies/issues/1351](url)

Same problem ?

But after waiting many time, take picture capture, save it, wait again .. no chunks is free. No unloading chunks. And for my it is not from schelduler from minecraft ... it come from ? ? ? anther way ... a way out scheduler. And at this time you are the one mod that i use that works out minecraft /forge schelduler.

For 2 :  PNJ = NPC = Villager. All provider use mutualised computer and cut or resart server if no body is connected and high CPU usage. If server can stop or take moor time it cut directly the task. In Minecraft it is not a problem, it is possible you save a list, order or other that can duplicate some register or other if server is cut and not stoper properly. 

For 3 : Lag , CPU usage. You say in #1351 it is for good IA. Thaumcraft have a very very good IA, without lag and in scheduler from minecraft / forge. And your IA is not very good but if I run towards a soldier with a zombie last me, both can end up on the same box without any action.

**Comment by marchermans** [comment]
We do not chunk load anything. This is not caused by minecolonies.
