### ISSUE TITLE
Fix for #1994 has killed my colony!

### ISSUE THREAD

**Issue by MattBeard** [ldtteam/minecolonies#1995]
Raycoms helped me earlier with issue #1994 and edited my colonies.dat file.

Unfortunately, even though this did fix the crashing issue, and did not appear to have any side-effects, it has broken my colony.

The deliverymen now gather, but never deliver anything. I have tried firing/rehiring, fulfilling a few requests manually etc. but they just gather, gather, gather! Interestingly at least one guard is also stuck in "gather" mode, which seems odd!

Help?

I have attached the current colonies.dat file in case it can be edited.

[colonies-broken-again.zip](https://github.com/Minecolonies/minecolonies/files/1619929/colonies-broken-again.zip)

**Comment by Raycoms** [comment]
Hey, guards gather mode has nothing to do with the dman gather mode,
(guards often gather randomly the drops).

The dman shouldn't be affected with this, it might've broken your warehouse
though, try to replace it please and tell us if that fixed it.

2018-01-10 18:06 GMT+00:00 MattBeard <notifications@github.com>:

**Comment by MattBeard** [comment]
Replace the warehouse!!!!! That took about a week to build and stock ;-(

Will make a copy and try in that.

**Comment by Asherslab** [comment]
Wait wait

**Comment by Asherslab** [comment]
You should try "Repair" your warehouse first, that'll check all the inventories within and such and re-register them if needed, try that first then try other =D

**Comment by MattBeard** [comment]
Ah I have just removed the warehouse chest and rebuilt back as level 1 (was level 3) and that has fixed it (but left me loads of my own double chests full of all the stuff I salvaged when the racks and frames were destroyed!)

Will try backing up this, then restoring the pre-demolish backup and use repair. Thanks for the tip Asherlab.

**Comment by MattBeard** [comment]
... well, I wasted a couple of hours!

It looks like Asherlab was right that repair was all that was needed. Have a cookie!
