### ISSUE TITLE
Can't place supply camp or supply ship (MC 1.10.2]

### ISSUE THREAD

**Issue by lebanni** [ldtteam/minecolonies#1997]
### Minecolonies version

minecolonies-universal-1.10.2-0.9.6734.jar

### Expected behavior

- Place supply camp on cleared area.

### Actual behaviour

- Nothing happen, with no message. I got the usal message when I try to place the camp on an uncleared area.
However I got errors in the log files. I suspect an incompatibility with a mod, but can't identify which one is responsible.

https://gist.github.com/lebanni/7d7d3ab6e5dd34e1d301dc4b844edbad
https://gist.github.com/lebanni/5bfbef4fde04153be03e70b451edc832

List of mods :
http://modlister.com/server/Industrial%20Science

### Steps to reproduce the problem

1. Collect some wood.
2. Craft a supply camp.
3. Clear area.
4. Try to place supply camp.

Edit : the issue does not happen in singleplayer.

**Comment by Nukerxz** [comment]
Exactly the same problem here. Can't do it in my server but i can do it in solo. 

Minecolonies version : minecolonies-universal-1.10.2-0.9.6847.jar

Edit : I make it worked in multiplayer by doing it in Creative mode. So i think it's an command or permissions problem. Any ideas ?

**Comment by Raycoms** [comment]
Both should be fixed
