### ISSUE TITLE
Cook not asking for food

### ISSUE THREAD

**Issue by YutaTakano** [ldtteam/minecolonies#1998]
### Minecolonies version

minecolonies-universal-1.12.2-0.8.6564.jar

### Expected behavior

- Cook requests uncooked food (fish, raw beef, etc)
- dman then delivers this food
- cook requests fuel and then starts cooking after receipt

### Actual behaviour

- cook stands around doing nothing, sometimes just hangs around in the town hall
- once I put raw food in the restaurant chest, he asked for fuel which dman brought
  -- but does nothing without raw food already in there

NB - a ton of raw fish exists in warehouse from my fisherman - not an issue of not having the food to cook

### Steps to reproduce the problem

1. Place+build restaurant, hire cook
2. Wait...

 - tried fire-rehire, no fix

**Comment by RyanToor** [comment]
**Minecolonies Version**

minecolonies-universal-1.12.2-0.8.6731

**Comments**

I am having the same problem on this version but it also occurs with the Bakery not requesting all wheat.  Instead, the dman will deliver one at a time, only when the bakery is out of wheat.

I tried the same steps, even going as far as to kill/re-hire, no luck.

In addition I have noticed that re-logging sometimes seems to cancel all build projects and stops the deliveryman from delivering to other huts until you deliver manually yourself.  E.G. Smelter will not request ore/burnables until i manually stock it with some sort of ore/burnable myself..

Not sure if it is relevant but I did notice that prior to me delivering manually, the dman did go with ore to the smeltery but failed to deliver properly.  He deposited ore and a little andesite, then picked them up again and left, looping until i successfully delivered ore myself.

These problems seemed similar, so thought they might be relevant, apologies if formatting is wrong or I'm in the wrong place (first post).

**Comment by Raycoms** [comment]
Hit here, yeah we will need to implement that the dman leaves things at
those places.

2018-01-11 13:19 GMT+00:00 da2mole <notifications@github.com>:

**Comment by RyanToor** [comment]
Ah, OK, was worried it might be deliberate to keep you checking up on your colony, the way it is at the moment it's a little tedius.

Great work btw, it's been a long time since I've found a mod which both fits in with and changes the base game so completely with such great care in its implementation.

Thankyou :)

**Comment by YutaTakano** [comment]
Ah if implementation is forthcoming then that's all I need to know :) I was just worried something was broken.
Also ditto on smelter - my smelter constantly requests ore but never gets any delivered.

^and yea, amazing job!! And I so appreciate you being super on top of everything.
