### ISSUE TITLE
Miner requests single slabs and fences

### ISSUE THREAD

**Issue by Devostar** [ldtteam/minecolonies#2001]
### Minecolonies version

Latest minecolonies alpha release

### Expected behavior

- Miner requests a stack of slabs/fences so he can build

### Actual behaviour

- Miner requests a single slab/fence, builds a single block and waits for dman again

### Steps to reproduce the problem

1. Build new mine
2. Wait for miner to start building
3. ...
4. Profit

**Comment by Raycoms** [comment]
We have an issue for that already.

thanks for reporting.

2018-01-11 16:55 GMT+00:00 Devostar <notifications@github.com>:
