### ISSUE TITLE
Miner Not Mining

### ISSUE THREAD

**Issue by YutaTakano** [ldtteam/minecolonies#2003]
### Minecolonies version

minecolonies-universal-1.12.2-0.8.6564.jar

### Expected behavior

- after building a new mine, hiring miner, giving equipment and resources, miner starts mining 

### Actual behaviour

- Miner initially requested a higher hut level to dig deeper.
- When i obliged, miner now walks over to a nearby natural cavern in a cliffside and walks allllllll the way down it and then mines a little bit, totally ignoring the mine

### Steps to reproduce the problem

1. made a second mine on outskirts of town (after extending colony protected area) near a cliff
2. hire and give items to a miner
3. ...

NB 
- ladder is intact. 
- tried fire/rehire even with different colonists, same result
- BUT my first mine works fine?

**Comment by Raycoms** [comment]
@YutaTakano two possibilities:

a) He found another ladder too close to his hut (will bork him)
b) His hut is too deep (y value) for his building level so you need to upgrade him.

Please reopen of neither fixes it.
