### ISSUE TITLE
Minecolonies takes up 4GB in my worldsave folder. I've never used the mod.

### ISSUE THREAD

**Issue by AMartinie** [ldtteam/minecolonies#2004]
### Minecolonies version

minecolonies-universal-1.12.2-0.8.6147

### Expected behavior

- Not to take up memory if it isn't being used...

### Actual behaviour

- Take up a massive ass amount of fuckin data..?

### Steps to reproduce the problem

1. Put mod in modpack
2. Don't use mod or even touch a single item in the mod
3. ...
4. crash your damn hard drive :+1:

**Comment by Raycoms** [comment]
Is it the colonies.dat which takes as much? you can remove those. We had a problem with a bug a while ago which caused that. You probably got it from then still.

**Comment by AMartinie** [comment]
I believe it recreated the same file repeatedly, while maintaining previous data in the clone AND leaving the old file there. I'd have to check later to find the exact cause.

**Comment by Raycoms** [comment]
Yes we have an issue for discarding after a while already. But making it as
big only happened because of the issue we had a while ago.

2018-01-12 12:01 GMT+00:00 Austin <notifications@github.com>:

**Comment by AMartinie** [comment]
Thanks for the quick support, I appreciate it. This can be closed
