### ISSUE TITLE
Villagers still working after colony deletion

### ISSUE THREAD

**Issue by ghost** [ldtteam/minecolonies#2008]
### Minecolonies version

version X.X.XXXX or curse X.X.XX

### Expected behavior

- i had deleted the colony and expected the colonists to die or dissapper

### Actual behaviour

- kept working

### Steps to reproduce the problem

1. XYZ
2. ZYX
3. ...
4. Profit

**Comment by Raycoms** [comment]
Which version? Are you sure you deleted it correctly?

**Comment by Wissi** [comment]
Seems a bit strange, that has never happened. 
What version of Minecolonies are you using? (f.e. 1.10, 1.11or 1.12 and file ver.)
Version of Forge and list of other mods?
As well as how did you delete the Colony, did you just "break/remove" the TH block or use the in-game command?

**Comment by ghost** [comment]
1.12.2 but i dont know ver number beacuse im currently at school.

**Comment by ghost** [comment]
Also it could be i pressed delete after using mcedit but i removed a block from another mod

**Comment by ghost** [comment]
Oh also i had some trouble with custom npc's and your mod not rendering textures while together

**Comment by Wissi** [comment]
Well "removing"  block will not remove the Town from the World.
There is a command you have to run to permanently delete the information of the Town from the world.
You must be OP to run the command: ` /mc colony delete <colonyID>`

**Comment by ghost** [comment]
I had pressed delete in the town hall.

On Jan 12, 2018 3:45 PM, "Wissi" <notifications@github.com> wrote:

Well "removing" block will not remove the Town from the World.
There is a command you have to run to permanently delete the information of
the Town from the world.
You must be OP to run the command: /mc colony delete <colonyID>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Minecolonies/minecolonies/issues/2008#issuecomment-357342778>,
or mute the thread

**Comment by Raycoms** [comment]
in the townhall there is a delete button? =O

2018-01-14 19:01 GMT+00:00 LegendaryGeek <notifications@github.com>:

> I had pressed delete in the town hall.
>

**Comment by ghost** [comment]
Yes in the version i have there is.

**Comment by ghost** [comment]
I also ran the command too. Before removing the block

**Comment by Raycoms** [comment]
can you send me a screenshot?

2018-01-14 19:12 GMT+00:00 LegendaryGeek <notifications@github.com>:

> Yes in the version i have there is.
>

**Comment by ghost** [comment]
I can try but it will have to be in a couple of days beacuse i have an FPS
issue right now. My game keeps dropping to 1 FPS

**Comment by Raycoms** [comment]
np

2018-01-14 19:18 GMT+00:00 LegendaryGeek <notifications@github.com>:

> I can try but it will have to be in a couple of days beacuse i have an FPS
> issue right now. My game keeps dropping to 1 FPS
>

**Comment by ghost** [comment]
I have 2 pics. I couldn't get the picture of the button but i have a pic of
them still working and a pic of all my versions i have downloaded. I am
sending this through my email so let me know if you can see them or not.

**Comment by Raycoms** [comment]
Tested it out several times, works perfectly for me.
