### ISSUE TITLE
Can an emerald block upgrade warehouse yet?

### ISSUE THREAD

**Issue by MattBeard** [ldtteam/minecolonies#2015]
I have seen that for ages that the warehouse chest had an option for using emerald blocks to upgrade, but this didn't work. I assumed this was not yet implemented. I am now on 1.12.2-0.8.6851 - has this feature been activated yet, or am I going to waste my time if I try collecting emeralds again?

**Comment by Raycoms** [comment]
It should work as soon as your warehouse is leve 5.

2018-01-13 13:28 GMT+00:00 MattBeard <notifications@github.com>:

**Comment by MattBeard** [comment]
Level 5... so I need to defeat the Ender Dragon to upgrade my warehouse!!!!!!

**Comment by Raycoms** [comment]
=)
