### ISSUE TITLE
<UNKNOWN> is in need of Shovel at Dim: ...

### ISSUE THREAD

**Issue by Mortenkein** [ldtteam/minecolonies#2016]
### Minecolonies version

1.12.2-0.8.6851

### Expected behavior

Only existing NPCs can request something.

### Actual behaviour

An unknown NPC is in need of a shovel. He can’t be found since he doesn’t exist.

### Steps to reproduce the problem

I do not know.

I crafted a clipboard to cancel this strange request.

**Comment by Raycoms** [comment]
We're currently fixing this with an all in one PR, should be out soonish =)
