### ISSUE TITLE
Builder Birch wood/slabs mixed up.

### ISSUE THREAD

**Issue by warpdragon** [ldtteam/minecolonies#2017]
### Minecolonies version

version 0.8.6705

### Expected behavior

- Builder asks for X Birch Wood so he should be holding Birch Wood

### Actual behaviour

- Builder is actually holding Birch Slabs. You have to give him Birch Slabs even though he's asking for Birch Wood.

### Steps to reproduce the problem

1. Request the Builder to build something out of Birch such as the Warehouse
2. Wait for him to need Birch Slabs
3. Observe he asks instead for Birch Wood, even though he's holding Birch Slabs
4. Profit

**Comment by Raycoms** [comment]
I was unable to reproduce this.
