### ISSUE TITLE
My colony is borked!!

### ISSUE THREAD

**Issue by MattBeard** [ldtteam/minecolonies#2019]
### Minecolonies version

version 1.12.2-0.8.6851

### Expected behavior

- Live in the colony progresses a normal

### Actual behaviour

- Major borkage!
- Many citizens are suddenly unemployed
- Many hut chests are not responding to right-click
- HELP!

### Steps to reproduce the problem

1. Erm... 

I can upload a ~180Mb zip to Dropbox if it helps!

Log file attached:
[latest.log](https://github.com/Minecolonies/minecolonies/files/1629446/latest.log)

**Comment by Raycoms** [comment]
Is the colony dat huge?

**Comment by MattBeard** [comment]
Hmm... it looks like a recent update has split it into colonies.dat and colony1.dat. Maybe the issue is linked to that.

This is both of them:
[minecolonies.zip](https://github.com/Minecolonies/minecolonies/files/1629638/minecolonies.zip)

**Comment by Raycoms** [comment]
No, this is supposed to be like it, we have it on the server with 200
colonies where it split all colonies accordingly without any problems.

2018-01-14 18:28 GMT+00:00 MattBeard <notifications@github.com>:

**Comment by Landstryder** [comment]
We had the same issue after server I playing on updated to the latest version. Many of of the hut blocks became inoperable. Everyone was unemployed and apon replacing them by the OP many of the former guards took up new profession and still had there armor on. Also the miner will not get back to work even after having his hut replaced by the OP and after that still not working after replacing the block and rebuilding it from tier 1, he just stands there and says upgrade my hut to dig deeper even tho it is tier 5 again. And yet another problem at arose from the shuffle was that the warehouse deleted more than 50% of the items on the shelves when attempting to fix it creatively spitting mass quantities of the remaining 50% of stuff on the ground then once it was replace and sort of working again trying to upgrade the inventories resulted in some of them upgrading but other stop expanding at different levels so some racks are default size, some seem to have one upgrade and some 2 or max and it will not let me use any more emerald blocks to get the low one up to the proper level nor will running a repair on the building have any effect.
