### ISSUE TITLE
[Suggestion] Trade Station

### ISSUE THREAD

**Issue by freshnici** [ldtteam/minecolonies#2020]
I thought it would be cool to have a trainstation or something else like a marketplace to trade with other colonies. Or just to share the inventory of the warehouse. 

My idea looks like that:

1. You build a trainstation or marketplace
2. You hire a worker
3. You choose a other colony to trade with or share your inventory or maybe "trade" citizen (of course it needs the building too with worker)
4. You need an item that your colony doesnt have but the other colony has 
5. The Trainstation or Marketplace worker from the other colony takes the item from the warehouse and brings it to your colony. -> maybe he gets money for that or other items or nothing, i dont know your choise :)

if you trade citizen it could look like this:

1. you build a jobhouse but you dont have a citizen to hire 
2. the other colony has a free citizen
3. you can hire that one -> maybe for money ?
4. every morning he comes late for work becouse of the way he has to travel between the colonies and in the evening he goes home earlier -> so its better to have your own citizen

Markedplace:

the traveling between 2 markedplaces would be on foot or maybe they ride on a pig or horse ?
but who builds the way between ?

maybe at first you dont have one but the builders from the colonies could build one 
(problems are maybe the waypoints ??)

Trainstation:

the traveling between 2 trainstations would be minecards 🚋 so first you need to build rails between the stations (or the builders ?) and the next step would be powered rails ?

So i dont know how hard it is to programming this :D but maybe you like the idea. I hope i can get a response how you like it and whats your view on this :)

sorry for bad english

**Comment by Raycoms** [comment]
Definitely! https://github.com/Minecolonies/minecolonies/issues/81

=D
