### ISSUE TITLE
Same-footprints for all upgrades of a given Building

### ISSUE THREAD

**Issue by warpdragon** [ldtteam/minecolonies#2024]
### Suggestion: Enforce same-footprints for all upgrades of a given building

To allow for precise site planning, upgrade(s) should not have a different footprint than the original building (# of blocks wide x # of blocks long). Players shouldn't have to redesign their whole layout simply because they need to upgrade a single building. The level 1 footprint should be used as the base. Schematics exceeding this footprint could be handled in a number of ways:
- They could be considered invalid. An error would print on save, and the save cancels. This would be an ideal solution.
- They could simply be chopped off. This would be a lazy solution.

**Comment by Raycoms** [comment]
Totally agree the only schematics not responding to this are old ones and will receive a rescan soon
