### ISSUE TITLE
Villagers will not leave town hall

### ISSUE THREAD

**Issue by xonear** [ldtteam/minecolonies#2025]
minecolonies-universal-1.10.2-0.8.4063

### Expected Behavior

- Villagers leaving the town hall/working

### Actual behaviour

- Villagers reach the block outside of the front door of the town hall and run back inside saying help danger yet there are no hostile mobs in any direction.

Have respawned every villager. Have refreshed the colony.

### Steps to reproduce the problem

1. Recall villagers to town hall
2. Watch them run around

**Comment by Raycoms** [comment]
There is probably some type of mob out there you need to kill for them or hire a guard to do that

**Comment by xonear** [comment]
I have journeymap installed and like I said above, there are no hostile mobs in any of the surrounding chunks
