### ISSUE TITLE
Supply ship/camp chests empty

### ISSUE THREAD

**Issue by ryansherring** [ldtteam/minecolonies#2026]
###4.10.1 Minecolonies version (twitch/curse)

###Expected behavior

- chests would appear full in supply chest or supply camp

###Actual behaviour

- supply chests appear empty

### Steps to reproduce the problem
Tried different games and different game modes. In all of them the supply chests consistently spawn empty.

**Comment by ryansherring** [comment]
Sorry about the formatting

**Comment by Asherslab** [comment]
sorry, that minecolonies version doesn't even exist? 
what Minecraft version are you on?

**Comment by ryansherring** [comment]
I apologize im new to this. I just downloaded the official package from the twitch client ythat was updated last saturday and my minecraft version is 1.12

**Comment by Asherslab** [comment]
Ahh are you talking about the Mincolonies Official modpack?

**Comment by ryansherring** [comment]
Yep thats right!

**Comment by Raycoms** [comment]
This happends when you're in gamemode1, in gamemode 0 it should work well.
I just tested it out.
