### ISSUE TITLE
Some recipes only work with oak

### ISSUE THREAD

**Issue by MattBeard** [ldtteam/minecolonies#2030]
### Minecolonies version

version 1.12.2-0.8.6851

### Expected behavior

- Should be able to build most minecolonies items with any wood

### Actual behaviour

- Several recipes require oak

### Steps to reproduce the problem

1. Try various minecolonies recipes with different wood items
2. Find a number fail

For example it seems that a colony ship requires oak boats and won't work with spruce ones.

**Comment by Raycoms** [comment]
Besides the boat recipe is there any else?
@MineShadow7 can you create 1 recipe each woodtype for the boats?

**Comment by MattBeard** [comment]
I have found a few others, but I can't remember them all. I have a feeling the builders hut may not work with a spruce door though.

**Comment by MineShadow7** [comment]
@Raycoms I've already said that forgeoredict don't have boats in it. Or they've updated that already?

**Comment by Raycoms** [comment]
I mean, 1 recipe each boat.
And the builder hut, are doors in it?

2018-01-17 13:41 GMT+00:00 MineShadow7 <notifications@github.com>:
