### ISSUE TITLE
the town hall, crashed the internal server

### ISSUE THREAD

**Issue by Merancau** [ldtteam/minecolonies#2031]
### Minecolonies version

version 0.8.4932 or curse 

### Expected behavior

- XXX

### Actual behaviour

- YYY

### Steps to reproduce the problem

1. XYZ
2. ZYX
3. ...
4. Profit

**Comment by Merancau** [comment]
When i put the town hall the internal server get close. if you don't understand my english srry

**Comment by Merancau** [comment]
can you help me?

**Comment by Raycoms** [comment]
Which minecraft version do you use?

2018-01-15 16:18 GMT+00:00 Merancau <notifications@github.com>:

**Comment by Merancau** [comment]
version 1.12.2

**Comment by Merancau** [comment]
i am playing in mac

**Comment by Merancau** [comment]
hello? some one there?

**Comment by Merancau** [comment]
hello?!?!
I need some help! pls!
