### ISSUE TITLE
Possible conflict with Minecraft Comes Alive

### ISSUE THREAD

**Issue by DrConnor** [ldtteam/minecolonies#2033]
### Minecolonies version 1.12.2

Forge #2555

I believe that there is a conflict with MCA. I can place the ship, but when I try to place the town hall, the game crashes me out to my server screen, when I am in single player. I tried moving the colony out of range of the village, and checking my permissions to no success. Nothing in the log file stood out, so I'm going to have to assume that it has something to do we the villagers and colonists creating the issue. Honestly not sure if anything can be done, this is more of a psa for anyone else who gets this. I'll post my log file later.

**Comment by Raycoms** [comment]
Which minecolonies version are you using?

2018-01-15 17:05 GMT+00:00 DrConnor <notifications@github.com>:

**Comment by DrConnor** [comment]
Okay I just noticed that you dropped an update. I'm not at my PC right now, but it was the version before this one. I'll try the new version and see if it fixes the problem.

**Comment by Raycoms** [comment]
Can you drop me a log if it doesn't resolve it?

2018-01-15 19:19 GMT+00:00 DrConnor <notifications@github.com>:

**Comment by Wissi** [comment]
I guess since no further "update" was given by DrConner we can close this as issue resolved.
