### ISSUE TITLE
Better Barbarian Announcements

### ISSUE THREAD

**Issue by warpdragon** [ldtteam/minecolonies#2034]
### Suggestion: Better Barbarian Announcements

Implement multiple announcement strings for the barbarian attack system which reflects more accurately the intensity of the incoming attack.

Since early game attacks are often quite weak or non-existence, their announcement string should merely introduce the players to the possibility of needing protection:
- "Mysterious warriors have been spotted near the encampment"
- "Citizens report rumors of raiders nearby"

Reason:
- New players are underwhelmed and often think the attack system is "broken" at low levels because they often experience no attacks even after a serious-sounding announcement.

Other ideas:
- A sound effect similar to "war drums" which signal the onset of only the most severe attacks.
- Highly visible campfire smoke particle system which spawns on the ground at the center of attack parties of a certain size, giving players an idea of the approximate direction of incoming attacks.

**Comment by MattBeard** [comment]
Brilliant - I like these ideas!
