### ISSUE TITLE
Minecolonies Crashes When Town Hall Is Placed

### ISSUE THREAD

**Issue by HashBrownOO7** [ldtteam/minecolonies#2035]
Minecolonies Universal 1.12.2-0.8.419

forge-1.12.2-14.23.1.2555

MC ver. 1.12.2

Expected behaviour: get your build tool and town hall from the supply camp, use build tool to place town hall, game continues.

Actual behaviour: get your build tool and town hall from the supply camp, use build tool to place town hall, when town all is placed game crashes and sometimes corrupts my world.

Steps to reproduce the problem-
1. Build Supply camp
2.Take town . hall and building tool out of chest
3. Place town hall

**Comment by Raycoms** [comment]
Please use a newer minecolonies version.
