### ISSUE TITLE
Player passes through supply ship. Can't interact with blocks

### ISSUE THREAD

**Issue by robstouf3** [ldtteam/minecolonies#2041]
Minecolonies version 0.8.6147
Minecraft version 1.12.2
Most recent Yogbox 2 Version

After placing the supply ship, I then attempt to climb the boarding ladder but phase through the ship, as if the blocks don't exist. I can see the ship, but can't interact with any of the blocks.

1. Place Supply ship with bottom layers submerged in water up to the bottom of the ladder
2. Swim to ship
3. Pass through everything
4. Consider whether or not the player actually exists in the plane of existence
5. Profit...by becoming a very good poltergeist.

**Comment by robstouf3** [comment]
This just in...I found the ACTUAL block you are meant to use. Was using a crafted building wand and trying to build a supply ship that way. Spoilers...it doesn't work.

**Comment by Raycoms** [comment]
haha great you figured

2018-01-17 0:22 GMT+00:00 robstouf3 <notifications@github.com>:
