### ISSUE TITLE
Problem with the builders wand

### ISSUE THREAD

**Issue by Tyffyfee** [ldtteam/minecolonies#2042]
### Minecolonies for minecraft version 1.12.2 (any)

version X.X.XXXX or curse X.X.XX

### In my version of the game after setting a supply ship or camp, the builders wand does´work anymore. It wants me to place down the town hall in water or when I´ve used the camp, it says it needs an area of 16x17 and when I have cleared it, the game still does not want to set the town hall chest.

I had this problem with every version of the 1.12 mod and it is still there with the newest version.

**Comment by marchermans** [comment]
Close the UI with esc once you placed the where you want it. Walk a couple of blogs and reopen the UI with a right click of the Building wand into the air.
Now keep pressing the checkmark.

It takes the server a couple of tries sometimes before it registers a click and is done validating,
