### ISSUE TITLE
Baker "issue"

### ISSUE THREAD

**Issue by webcrafter-fr** [ldtteam/minecolonies#2045]
### Minecolonies version

minecolonies-universal-1.12.2-0.8.6731

### Expected behavior

- My farmer give wheat to my baker
- My baker make bread
- And now two options : 
1. Breads are placed in the restaurant
2. Breads are placed in the warehouse

### Actual behaviour

- My farmer produce wheat
- The wheat is placed in the warehouse by the deleverymens
- My baker never get a huge amount of wheat
- I don't have many breads

I think all my wheat should be placed in the baker's hut no ? What about the produced breads ? Should they be placed in the warehouse or the restaurant ?

I don't think that the deleveryman bring wheat to the baker hut :/

**Comment by Raycoms** [comment]
Your baker doesn't get any wheat at all, or only a bit?
