### ISSUE TITLE
[Suggestion] Modifiable Raider Messages

### ISSUE THREAD

**Issue by copperwarrior** [ldtteam/minecolonies#2048]
While the addition of different raider messages corresponding to the various difficulty level is nice, a config option to change the raider announcements would be even better. I'm playing a Minecolonies game with more of a "medieval" setting, and it's rather peculiar whenever we get the "western" style message from the raider announcement. (specifically the "Buckle up, cowboy," announcement.) Alternatively, selectable styles for the various announcements (as well as potentially for the building names, e.g. "Cowboy" to "Cowman", "Rancher", "Cattle Herder") would suffice as well.

**Comment by marchermans** [comment]
All lang files are editable by using minecrafts resource pack mechanics. Simply target minecolonies as a domain instead of Minecraft.
