### ISSUE TITLE
Suggested Feature

### ISSUE THREAD

**Issue by mgwerner** [ldtteam/minecolonies#2052]
1. Craftable clipboard which will clone resources needed list from builder
2. carry clipboard so that you can craft things needed
3. ...prevents running back and forth to see what is needed, saving time with especially large build
4. Profit

**Comment by marchermans** [comment]
Sorry no. I have thought about this when i designed the clipboard. You can already see what the entire colony needs from you and directly fullfill its requests from it, regardless from where you are.

Giving the player the ability to craft would be very op.

We are however working on making the builder request all resources at once.

**Comment by Asherslab** [comment]
@OrionDevelopment i think he meant that it would show only the stuff of the specific worker you want to `which will clone resources needed list from builder` and then He can know what to craft, not that the thing itself crafts the items

**Comment by mgwerner** [comment]
Indeed, I am simply looking to be able to see what is needed without the back and forth, not to make supplying the materials easier.  I understand what you mean, I think, in that the clipboard would be op if able to fulfill requests from it, no matter the player location, and I agree completely.  Thanks

**Comment by marchermans** [comment]
I understood very clearly what he wanted. And even though i am having somewhat of a bad day. It does not change what i mean. Especially with the crafting update Coming out. The clipboard was designed as a last resort for the rs to drop requests. It even allows you to see them coming 3 minutes ahead of time. 

I have planned to make it more sophisticated in the future. But I do not think restricting to a single building or citizen would make sense here. The clipboard already shows requests that are or could be finally assigned to you. Including the citizens name. I have tested it myself when building 5 level town hall. I agree that we need to make the builder request everything at once. So we can immediately see what is needed (or at least have him request in batches), but that does not mean that we have to make it as easy as 1,2,3. 

I already had a bad feeling when I allow led a player a resolve through the ui. It takes the interaction away. And even though with crafting update that will become even less. That is a natural change, it is something that comes natural. Having the ability to see exactly what any citizen needs at any time and full fill it without thinking, without any interaction is simply a step too far for mr.

**Comment by mgwerner** [comment]
I was not aware of that purpose of the clipboard, since, as it stands now, I am getting no requests through it.  What you have described fulfills my suggestion, and then some.  I can see your point that the clipboard passing all requests is even more useful to the player, and I had not thought about requests other than the Builder.
Thanks for the explanation, the quick responses, and above all, for a mod that I am enjoying very much.

**Comment by marchermans** [comment]
Try shift right clicking it on any building. It will show all requests that might eventually end up in your chat box or already have.

**Comment by Asherslab** [comment]
okay apologies, i was not sure if you understood :smile:

**Comment by mgwerner** [comment]
I was having trouble getting the clipboard to register.  Kept sneak right clicking the book in the Town Hall to no effect.  Tried several other buildings, got it to work with a Citizen Hut.  First request is listed now.  Thanks again, this is part of what I was asking.

**Comment by marchermans** [comment]
No Problems. The UI will improve over time. But right now, there are so few requests made simultaniously that you can see them in one go anyway. We are working on the builder making say 5 requests at once. But that is still a bit in the future.
