### ISSUE TITLE
Newer Minecolonies versions crashing on launch (again)

### ISSUE THREAD

**Issue by johnnye152** [ldtteam/minecolonies#2055]
Hello again,

Previously I raised an issue with minecolonies crashing on forge loadup (See: Newer Minecolonies Versions not working (Forge crash during minecraft startup) #1845)

This issue was closed when version 6037 worked. Unfortunately the same issue arrises with using newer than v6037 of minecolonies. I've tried updating to latest forge and also the latest minecolonies (v6990). I've tried the latest Beta version and still the same crash. Log and information below:

![image](https://user-images.githubusercontent.com/34572954/35167865-e0136148-fd4e-11e7-91b2-b655625820e6.png)

Message said: The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from MineColonies (minecolonies)

[crash-2018-01-19_19.22.33-client.txt](https://github.com/Minecolonies/minecolonies/files/1647673/crash-2018-01-19_19.22.33-client.txt)

Last time it was fixed by Raycoms who said
"Should be fixed in the newest version, should be on curse in a few minutes" on 17 Dec

Sorry to be a pain, hope it can be fixed, I can't wait to see some of these new things i see in the changelogs since 6037.

Thanks as always.

**Comment by Raycoms** [comment]
This occurs with which forge version? Did you try several?

2018-01-19 19:32 GMT+00:00 johnnye152 <notifications@github.com>:

**Comment by johnnye152** [comment]
I did try several:
Versions: 2555
               2562
               2584

I'll try the latest now.

**Comment by johnnye152** [comment]
Just tried 2599 and same problem occurred.

**Comment by Raycoms** [comment]
Where did you download it? On curse?

2018-01-19 20:37 GMT+00:00 johnnye152 <notifications@github.com>:

**Comment by marchermans** [comment]
You are using the deobf jar. It is for development only.
