### ISSUE TITLE
Nether with No Fortress

### ISSUE THREAD

**Issue by mgwerner** [ldtteam/minecolonies#2056]
### Minecolonies version

minecolonies-universal-1.11.2-0.8.6843

### Expected behavior

-Normal nether with large open areas, fortresses, etc.

### Actual behaviour

- Portal opens at height 6 in a small cavern.  Digging up gets me to an open almost like normal nether, but no structures, and a low ceiling.  Digging up through this finds the ceiling at about height 150, flat with recesses with structures from the ruins mod.  Mobs walking about.  Flying up I can get to 186 or so, but the jetpack will not allow me higher.

Thorough exploration found no fortress.

### Steps to reproduce the problem

1. Delete DIM-1
2. Go to nether
3. Cavern same, open area same, no fortress
4. Profit

**Comment by Raycoms** [comment]
We don't mess at all with the nether, must be another mod.

**Comment by mgwerner** [comment]
OK, thanks
