### ISSUE TITLE
TOWNHALL ISSUES

### ISSUE THREAD

**Issue by shxlbyt** [ldtteam/minecolonies#2057]
The townhall disconnected from the game right when I placed it and I used the universal one. I spent so much time in that world and now I can't open and play it cause it doesn't work because of the town hall.

**Comment by marchermans** [comment]
Log and version numbers please.

**Comment by shxlbyt** [comment]
minecolonies-universal-1.12.2-0.8.4932.jar
and I don't know what log is

**Comment by Raycoms** [comment]
Please update to the latest version
