### ISSUE TITLE
Server crash on load com.minecolonies.api.compatibility.CompatabilityManager.readFromNBT

### ISSUE THREAD

**Issue by ProsperCraft** [ldtteam/minecolonies#2058]
### Minecolonies version

minecolonies-universal-1.12.2-0.8.6990

### Actual behaviour

- https://gist.github.com/ProsperCraft/9de565ac153ed5265e2b5d116a75a398

**Comment by ProsperCraft** [comment]
I quit trying to load the server, then loaded it again, and now my colony is deleted.

**Comment by marchermans** [comment]
Did you remove a mod or something?

**Comment by ProsperCraft** [comment]
No

**Comment by Raycoms** [comment]
It seems it has been fixed by the mod owners.
