### ISSUE TITLE
Guards attacking Owner

### ISSUE THREAD

**Issue by Deathcofi** [ldtteam/minecolonies#2060]
### Minecolonies version

version 0.8.4908

### Expected behavior

- Guards ignore Owners

### Actual behaviour

- Guards follow and attack Owners without losing focus

### Steps to reproduce the problem

1. Hire a Guard, any type (fresh or old colony, doesn't matter)
2. Attack Guard in any way (Punch, Arrow, THORNS enchantment - reason I have created this thread)

The Guard will proceed to attack you.
To stop them you have to fire them then hire them back. But still, doing this too fast will still result in the Guard attacking you but with a slower attack speed - very strange indeed, I think this has to do with the Job Level being reset.

*Ok, I found out that stealing their weapon and giving it back to them also solves it but I'll still keep the text above in this post

This also happens in Creative Mode!

**Comment by Raycoms** [comment]
Running away for a minute should fix that as well.
