### ISSUE TITLE
Schematic to NBT transformer

### ISSUE THREAD

**Issue by Raycoms** [ldtteam/minecolonies#2064]
Would be nice to have some sort of tool to transform .schematics to .nbt easily.
Would be handy to have since there are a lot of .schematics out there.

**Comment by winsrp** [comment]
still waiting for this, kind of hard to find .nbt files, but really easy to find .schematic files ='(

**Comment by winsrp** [comment]
also .schematic being binary files are much smaller, making them better for things like sharing *wink* like when sharing an item with a linked schematic to another user =D

**Comment by Nightenom** [comment]
Closing since blueprints were introduced

**Comment by Nightenom** [comment]
Wait, I just remember that schematics are from some kind of world edit app?

**Comment by spacewolfcub** [comment]
Schematica is not dependent on WorldEdit, afaik. 
[https://minecraft.curseforge.com/projects/schematica](url)

**Comment by Nightenom** [comment]
This mod is definitely younger than .schematic file

**Comment by spacewolfcub** [comment]
Do not be fooled by it only having moved to curseforge recently. It has been around a long time.

> The .schematic file format was created by the community to store sections of a Minecraft world for use with third-party programs (including MCEdit, Minecraft Note Block Studio, Redstone Simulator, WorldEdit, and Schematica). Schematics are in NBT format and are loosely based on the Indev level format. 
[https://minecraft.gamepedia.com/Schematic_file_format](url)

**Comment by Nightenom** [comment]
MCEdit (and WorldEdit in-game) is ten years old or more, it was there in beta times where mods were put into minecraft.jar. I still think Schematica is not the origin of .schematic
Whatever it's still community format so regardless things around I'm not sure if we want a tool between .schematic .blueprint
