### ISSUE TITLE
Builder not acknowledging build requests

### ISSUE THREAD

**Issue by RetsnomKcor** [ldtteam/minecolonies#2065]
### Minecolonies version

Happens in at least Minecolonies versions 0.8.6471 and up for 1.12, as well as 0.8.6960 for 1.11.2 ( I didn't check earlier versions than those, so more versions might be affected as well). 

### Expected behavior

- Builder builds buildings

### Actual behaviour

- After finishing the builders' hut and the town hall, the builder just stands around and ignores any further build requests. 
- Placing another builders' hut and hiring a second builder has similar results - the new builder will build their own builders hut and one more building before ignoring further requests. 
- Firing/killing the builder and hiring a new one does not affect anything, the new one will continue to ignore all build requests
- The build requests appear in the work order list in the town hall, but no existing builder is assigned to them
- Cancelling build requests and adding new ones does nothing
- Builder appears able to make decorations prior to the second building, but not after (i.e. the builder can make a builders hut, several fancy paths, and then a town hall - but once the town hall is built no more decorations can be made)

### Steps to reproduce the problem

1. Start a new colony 
2. Build two buildings
3. Builder forgets how to build
4. Profit

I'm not sure how useful it is, but [here's a log](https://pastebin.com/YzJADL2g).

**Comment by Raycoms** [comment]
Can you give us a mod and plugin list?

2018-01-21 0:42 GMT+00:00 RetsnomKcor <notifications@github.com>:

**Comment by RetsnomKcor** [comment]
Only mods installed aside from Minecolonies are 
- Journeymap 5.5.2
- JEI 4.8.5.138
- The One Probe 1.4.19  

Using Forge version 14.23.1.2583.

**Comment by Raycoms** [comment]
can you send us the world?

2018-01-21 1:11 GMT+00:00 RetsnomKcor <notifications@github.com>:

**Comment by RetsnomKcor** [comment]
[This](https://github.com/Minecolonies/minecolonies/files/1649444/Test.53.zip) is the first world I encountered it in.

**Comment by Raycoms** [comment]
Will check it out tomorrow morning =) thanks

2018-01-21 1:30 GMT+00:00 RetsnomKcor <notifications@github.com>:
