### ISSUE TITLE
Miner confused after update

### ISSUE THREAD

**Issue by Landstryder** [ldtteam/minecolonies#2066]
### Minecolonies version

minecolonies-universal-1.12.2-0.8.6934
in the Colonial Engineers pack on the public server

### Expected behavior

- Get back to mining after version Upgrade
- Keep node data if hut block is broken and replace to exact same spot

### Actual behaviour

- Block becomes non interactable and miner is now unemployed (this was the case with nearly every hut block in my city but not for every person on the server, so effected some not)
- Building replace to tier 5 by OP , but after running a repair on it and hiring a new miner the miner just repeat "Please upgrade my hut to dig deeper" (shaft already goes to bedrock and much of the lowest level had been mined, 192 nodes on the very bottom and 100+ on the next to the lowests before the update)
- Break and replaced the miners hut block with the wand normal mode and proceed to have the builder upgrade it to tier 5 again but the whole time the miner just keeps saying that same thing "Please upgrade my hut to dig deeper"
- Completed rebuilding the tier 5 hut and fired the current miner and tried a new citizen but get the same response "Please upgrade my hut to dig deeper"
- Smacked miner around with a raw fish but also didn't help

### Steps to reproduce the problem

1. have a large city with tier 5 everything
2. update to the latest version
3. break and replace non-interactable blocks (survival or creative)
4. Profit

**Comment by Raycoms** [comment]
Is it possible that you use techreborn? That caused an issue which made colonies not load, just update to their newest version.
About th eminer, yes that's perfectly normal, if you remove the block it will lose its levels and its shaft you have to place th eminer building at a new location. We can't store all past building data if we can't say wether a player destroyed a building by accident or not.

**Comment by Raycoms** [comment]
Fix will come soon with the crafting update for that issue =)

2018-01-22 17:16 GMT+00:00 pyscho974 <notifications@github.com>:
