### ISSUE TITLE
server crash on client connection

### ISSUE THREAD

**Issue by lebanni** [ldtteam/minecolonies#2069]
### Minecolonies version

updating from 0.8.6996 to 0.8.7011 (MC 1.12.2)

[https://gist.github.com/lebanni/2196710bc60516a9ba33ef300caa4540](url)

[https://gist.github.com/lebanni/9f04e02c3985a5f02df04a84258d06e5](url)

**Comment by Raycoms** [comment]
Added a hotfix in my current PR
