### ISSUE TITLE
Builder Generating infinite slabs trying to upgrade to builder hut 2

### ISSUE THREAD

**Issue by Frosted-Buns** [ldtteam/minecolonies#2070]
### Minecolonies version

version 0.8.4908 or curse X.X.XX

### Expected behavior

- Builder upgrading hut to tier 2

### Actual behaviour

- Builder standing still with slab in hand even when it's no longer need and quickly generating infinite slabs https://i.imgur.com/3eqKfwU.gif

### Steps to reproduce the problem

1. Assign anyone to builder
2. set builder hut to upgrade to tier 2
3. builder gets to slab step
4. no work and infinite slabs

**Comment by Frosted-Buns** [comment]
I'd also like to note that I've tried switching builders, turning upgrade on and off again, and even killing the builder and making a new one

**Comment by Raycoms** [comment]
Please update to the newest alpha or beta.

**Comment by Frosted-Buns** [comment]
Ah, that worked, thanks.
