### ISSUE TITLE
Can't interact with buildings

### ISSUE THREAD

**Issue by wilsondgonzales** [ldtteam/minecolonies#2071]
### Minecolonies version

minecolonies-universal-1.12.2-0.8.7011.jar

### Expected behavior

access to building chests

### Actual behaviour

can't rclick townhall, farmer, delivery hut. Builder works. Haven't played in a while so i'm seeking advice on how to proceed. /mc colonies list still shows my colony. and i still see workers working etc.

**Comment by Raycoms** [comment]
Do /mc colony refresh

**Comment by Doudle666** [comment]
I have the same issue, and there is no more citizen in my town. I am not able to do /mc refresh, says i am not allowed to do that command. (i am on Hardcore, dont know if can change something)

**Comment by Raycoms** [comment]
Hey, what does f3 say? Is there a close colony?

>

**Comment by Doudle666** [comment]
ill try it right now, (can we reopen it ?) Thanks a lot

**Comment by Raycoms** [comment]
Actually, the issue is probably that something happened through saving or loading and the colony didn't load validly. F3 should tell you if its a permission issue (so it will say, xx colony is close) or a loading issue in which case it would say no close colony. If no close colony you can simply load a backup colony.nbt

**Comment by Doudle666** [comment]
Not sure where i have to check to see if its still open
![untitled](https://user-images.githubusercontent.com/42633751/44606060-c3c42480-a7b9-11e8-8f5b-3a4643c0d7ea.png)

**Comment by Raycoms** [comment]
Hmm, darn, Botania and Astral Sorcery seems to be pushing it out. 
can you nbt edit the colonies.dat and check if the colony count is 1, if not set it 1 and reload the world.
Then recall all citizens.

**Comment by Doudle666** [comment]
Thanks buddy, i just took a colonies.dat older and it now works.
