### ISSUE TITLE
Client Crash - When using scroll bar.

### ISSUE THREAD

**Issue by ProsperCraft** [ldtteam/minecolonies#2072]
### Minecolonies version

- minecolonies-universal-1.12.2-0.8.6996

### Actual behaviour

- https://gist.github.com/ProsperCraft/f129b7c4c282c06ba42002eaa3dfbbe3

### Steps to reproduce the problem

1. I was scrolling down to see what the builder needed.

**Comment by Raycoms** [comment]
Pushed a hotfix
