### ISSUE TITLE
pickaxe

### ISSUE THREAD

**Issue by pyscho974** [ldtteam/minecolonies#2076]
### Minecolonies version  minecolonies-universal-1.12.2-0.8.6934

version X.X.XXXX or curse X.X.XX

### Expected behavior miner would continue mining

- XXX

### Actual behaviour miner stuck requesting diamond pickaxe

acts like does not recognize diamond pickaxe in inventory
- YYY

### Steps to reproduce the problem build mine and hire employee

1. XYZ
2. ZYX
3. ...
4. Profit

**Comment by Raycoms** [comment]
The worker only recognizes it if the building level is high enough.
