### ISSUE TITLE
Builder in loop asking for diamond level pick

### ISSUE THREAD

**Issue by ProfIPFreely** [ldtteam/minecolonies#2079]
### Minecolonies version

version 1.12.2-0.8.6983

### Expected behavior

- building the town hall

### Actual behaviour

1. asking for diamond level pick
2. going to work space for town hall
3. returning to builders hut
4. goto1
There is nothing that should require a diamond level pick to break, which makes it more annoying.
### Steps to reproduce the problem

1. Assigned new builder
2. Fired both builders
3. Tried two new builders
4. Posted here

**Comment by ProfIPFreely** [comment]
problem persists in 1.12.2-0.8.7080, same pattern and bug

**Comment by Asherslab** [comment]
and there are no obsidian or etc blocks in the area (do remember that it may be under the ground or not visible) that require a diamond pick to mine? also does it work if you do give him a diamond pick? does he work without a diamond pick? (iron or etc)

**Comment by ProfIPFreely** [comment]
There is nothing that should require a diamond pick. I cleared out the area to check. Cleared out ground level, and the one below. APperently is was thinking rutile ore was diamond level? It's iron, but they're working now.

**Comment by Raycoms** [comment]
It is possible that rutile ore has implemented it somehow wrongly and that's why we detect it as diamond level.
