### ISSUE TITLE
Oh come ON!!! Yet again my DMan is broken!!!

### ISSUE THREAD

**Issue by MattBeard** [ldtteam/minecolonies#2084]
### Minecolonies version

version 1.12.2-0.8.7133

### Expected behaviour

- The game is playable!

### Actual behaviour

- Yet again my deliveryman has stopped working.

### Steps to reproduce the problem

1. Install Minecolonies
2. Regularly contribute on Patreon
3. Get fed up with all my colonies getting fatally broken
4. I may stop playing ;-(

Yes, OK, I am upset and not necessarily being rational, but my colonies keep ending up either totally broken or with a delivery man who will no longer work.

In this case I has built a Taiga warehouse (which is not anything like as good as the wooden one in usability in my opinion, even though it looks nice). I upgraded the warehouse to level 3 and had 2 builders busy in the colony serviced by a single deliveryman. Then the dman stopped working with the warehouse. I tried firing/re-employing, employing a different colonist, getting a builder to repair the warehouse, manually breaking some racks then using the builder to repair again (so new racks). Still no good. So, I demolished the warehouse and got the builder to build a new one (wood this time). And the deliveryman is still stick "dumping".

I have attached the colonies.dat and colony1.dat files in case someone knows how to de-kaput them!!

[colonies.dat.zip](https://github.com/Minecolonies/minecolonies/files/1659903/colonies.dat.zip)

**Comment by Raycoms** [comment]
Does he throw something in the log?

2018-01-24 13:04 GMT+00:00 MattBeard <notifications@github.com>:

**Comment by MattBeard** [comment]
Here is the latest log...
[latest.log](https://github.com/Minecolonies/minecolonies/files/1660049/latest.log)

**Comment by MattBeard** [comment]
The previous log is more interesting... all the "warehouse full" messages are caused by the replacement warehouse being built while the delivery man is wanting to try and use it.
[2018-01-24-4.log](https://github.com/Minecolonies/minecolonies/files/1660062/2018-01-24-4.log)

**Comment by Raycoms** [comment]
can you check if /mc colony rs reset yourcolonyId fixed it?

2018-01-24 13:57 GMT+00:00 MattBeard <notifications@github.com>:

**Comment by MattBeard** [comment]
I guess I execute this inside the game (in a chat window) - just need to figure out my colony id - where is the best place to find that?

**Comment by Raycoms** [comment]
do /mc colonies list

2018-01-24 14:02 GMT+00:00 MattBeard <notifications@github.com>:

**Comment by MattBeard** [comment]
"You do not have permission to use this command"

/me weeps!!!

**Comment by Raycoms** [comment]
open the world to be a lan world and allow commands, this will allow you
temporarily to execute this.

2018-01-24 14:08 GMT+00:00 MattBeard <notifications@github.com>:

**Comment by MattBeard** [comment]
Half worked...

Opening the world to the LAN allowed me to execute the commands (nice trick, thanks)

However... still stuck dumping ;-(

**Comment by MattBeard** [comment]
***STOP PRESS***
It is now working!

**Comment by MattBeard** [comment]
Initially I did the reset and my builders restarted their jobs, and the dman was gathering only (not delivering as far as I could tell)

I then went to a miner who was stuck waiting for a pickaxe and cancelled his request to try and get it re-added to the queue. This cause a Java Crash.

I then restarted and watched and saw the dman stuck in "dumping"

This may have been re-triggered by the miner (or that colonist may have been the source of the issue). I re-ran the reset and it now seems to be working.

@Raycoms you are now my hero :-)

**Comment by MattBeard** [comment]
Here is the log with the crash - in case that helps
[2018-01-24-6.log](https://github.com/Minecolonies/minecolonies/files/1660169/2018-01-24-6.log)

**Comment by Raycoms** [comment]
We have constructed a fix for the corruption of a few requests which we'll
push with some other fixes in the next days.

2018-01-24 14:39 GMT+00:00 MattBeard <notifications@github.com>:

**Comment by MattBeard** [comment]
OK - I am now getting a lot of citizens with open requests and the "resolver" is marked as "Player"

This does not go away when I to an "rs reset" - sometimes after I fulfil a few for a worker they start using the warehouse again, then they go back to expecting me to resolve. Is this something the new fixes solve?

**Comment by MattBeard** [comment]
Ah... note to self:
Do not open the game to LAN (to get commands working) then after a while press escape to pause, then go off and have lunch. You will come back to a "you died" screen as LAN games don't pause!!

**Comment by marchermans** [comment]
Player resolving means that it requires something from you

**Comment by marchermans** [comment]
Check the clipboard.

**Comment by MattBeard** [comment]
After being seriously killed (see above) my colony seems to be behaving itself better. I will post details about the clipboard if/when it gets confused again.

Re: "Player resolving means that it requires something from you" - yes, I understand that, but why is a builder (or miner etc.) asking me for things that are in the warehouse and the deliveryman should resolve?

**Comment by marchermans** [comment]
Because right now, the priority based resolved resolvers are broken.
So it is a bit of a gamble what gets the job. You will need to cancel it until your luck is better, or do it yourself. A fix for it is already on the way to the testers.

**Comment by MattBeard** [comment]
It got confused again...

My builder wants me to supply a block of coal, however there are two blocks in the warehouse. The clipboard does not show this request.
<img width="966" alt="screen shot 2018-01-25 at 16 33 02" src="https://user-images.githubusercontent.com/835593/35400004-965a1346-01ed-11e8-8fa4-497e002d77e0.png">
<img width="966" alt="screen shot 2018-01-25 at 16 30 22" src="https://user-images.githubusercontent.com/835593/35400010-9c68aefa-01ed-11e8-8407-74ca06398642.png">
<img width="966" alt="screen shot 2018-01-25 at 16 31 42" src="https://user-images.githubusercontent.com/835593/35400026-a393a6a8-01ed-11e8-80e9-ba23df1cf41b.png">

**Comment by marchermans** [comment]
Hmm
Wait what.....

**Comment by marchermans** [comment]
Show me a screenshot from his request ui

**Comment by MattBeard** [comment]
This?
<img width="966" alt="screen shot 2018-01-25 at 16 31 17" src="https://user-images.githubusercontent.com/835593/35400593-1a0be682-01ef-11e8-807b-bc9282ec1532.png">

**Comment by Raycoms** [comment]
You can check this jar:

https://s3.eu-central-1.amazonaws.com/minecolonies/Minecolonies/Minecolonies_Branches/7176/minecolonies-universal-1.12.2-0.8.7176.jar

if it improves things.

2018-01-25 16:45 GMT+00:00 MattBeard <notifications@github.com>:

**Comment by marchermans** [comment]
Okey yeah you ran into the bug that is on the way to be fixed

**Comment by marchermans** [comment]
Give me some time to run it by our testers

**Comment by MattBeard** [comment]
7176 installed and it did not immediately fix, but I assumed the duff data was stuck, so I cancelled the request and after going to the building being upgraded and staring for ages, she returned to her hut and asked the warehouse for the block of coal. I will keep running this version and let you know if it happens again.

Thanks!

**Comment by MattBeard** [comment]
Update on 7176 performance... still getting requests allocated to the player (and NOT appearing on the clipboard) but cancelling them seems to get them reallocated and the warehouse tends to pick them up. Hmmm.....

Oh... and the clipboard is forever causing Java crashes!!

**Comment by Raycoms** [comment]
Logs for the java crashes please

2018-01-25 17:36 GMT+00:00 MattBeard <notifications@github.com>:

**Comment by Raycoms** [comment]
I will close this here in favor of the pull request. If the dman problem and the crashes continue to occur please open a new issue with a log.

Please also do /mc colonies rsResetAll after upgrading to the next version.

**Comment by Raycoms** [comment]
https://github.com/Minecolonies/minecolonies/pull/2089
