### ISSUE TITLE
Builder Breaking

### ISSUE THREAD

**Issue by ninjadcb** [ldtteam/minecolonies#2087]
1.11.2-0.8.4904

Upgrading my Builder's Hut

Saying "I'm waiting for the rain to stop" when there was no rain.
1. Have some rain appear
2. do /weather clear to clear the weather
3. sometimes the builder will forever say "I'm waiting for the rain to stop
4. Killing them spawns a new person, but they will forever be looking for a job.

**Comment by Justen-N** [comment]
attempt to fire/rehire, or do /mc colony refresh. The request system still
isn't 100%

**Comment by marchermans** [comment]
This has nothing to do with the RS. There is only one state the RS is active for and that is waiting for X Item.
I have not seen it doing this.

He can try to run: /mc colony rs reset <ColonyId>
