### ISSUE TITLE
Aquatic Barbarians!!

### ISSUE THREAD

**Issue by MattBeard** [ldtteam/minecolonies#2088]
### Minecolonies version

version: anything recent, in this case 7176

### Expected behaviour

- Barbarians spawn somewhere sensible

### Actual behaviour

- Barbarians seem to love spawning well out to sea!!

### Steps to reproduce the problem

1. Build a colony on an island, peninsular, or in fact anywhere near the ocean
2. Wait for barbarians to spawn
3. Wonder why they almost always seem to spawn all the way out to sea!!

<img width="966" alt="screen shot 2018-01-25 at 17 56 32" src="https://user-images.githubusercontent.com/835593/35404041-83622f4c-01f9-11e8-8cc4-90d2d0c34fe1.png">

**Comment by Raycoms** [comment]
Yeah we plan on making them pirates in this case =)
For now that's okay if they spawn there.

**Comment by MattBeard** [comment]
Just for context... here is the border (they had been swimming for quite a while when I spotted them, so they may have started even further out)
<img width="966" alt="screen shot 2018-01-25 at 18 01 39" src="https://user-images.githubusercontent.com/835593/35404177-f3e84440-01f9-11e8-9883-dc811ba1f34d.png">

Oh... and the big problem is that they tend to arrive well after all the workers are back working and they get killed rather than just fighting with the guards.

**Comment by Raycoms** [comment]
Yeah we try to spawn them as far out as possible atm to give the player time to react =)
