### ISSUE TITLE
Miner Duplication

### ISSUE THREAD

**Issue by mgwerner** [ldtteam/minecolonies#2090]
### Minecolonies version

minecolonies-universal-1.11.2-0.8.6843 (and several versions prior)
industrialcraft-2-2.7.81-ex111

### Expected behavior

- Clicking Fulfill transfer one pick from player inventory to Miner inventory

### Actual behaviour

- Clicking Fulfill transfers IC2 drill to Miner inventory, doubling (or increasing by 1, not sure) the number of IC2 drills.  
Ex. if player inventory has 7 iron pickaxes, and a diamond IC2 drill, clicking Fulfill moves 7 or 8 IC2 drills to Miner inventory, leaving the 7 iron pickaxes in Player inventory.  No IC2 drills remain in player inventory.

### Steps to reproduce the problem

1. make iron pickaxes
2. Fulfill Miner request with IC2 drill in Player inventory
3. Have multiple IC2 drills appear in Miner inventory
4. Profit (massively!)

**Comment by Raycoms** [comment]
Should be fixed
