### ISSUE TITLE
Sheep pine for neighbours in AlternativeWood pens

### ISSUE THREAD

**Issue by MattBeard** [ldtteam/minecolonies#2092]
### Minecolonies version

version 1.12.2-0.8.7200 (and earlier)

### Expected behaviour

- Shepherd should breed animals is a sensible way

### Actual behaviour

- In the AlternativeWood shepherd's hut (may happen with others) at level 2 upwards there are two pens
- The shepherd will often give wheat to one sheep in each pen, and they cannot reach each other to breed
- Lost wheat, and sad sheet

### Steps to reproduce the problem

1. Build and AlternativeWood sheperd's hut, upgrade to level 2
2. Employ a shepherd, give 4 sheep and lots of wheat
3. Watch the sad sight of pining sheep that can see each other but can't rumpy-pumpy

**Comment by Raycoms** [comment]
We can't unfortunately detect that. The hut design must be changed for that.
