### ISSUE TITLE
Baker ain't baking

### ISSUE THREAD

**Issue by Lordbaane** [ldtteam/minecolonies#2095]
### Minecolonies version

-1.12.2-0.8.7210.jar 
### Expected behavior

- Baker requests wheat, or even just shows up for work

### Actual behaviour

- Stands around

### Steps to reproduce the problem

1. Reset the game
2. recalled the town
3. nothing happens, has been around for the last several updates.
4. Profit

**Comment by Lordbaane** [comment]
He goes to the bakery, but just stands around. He should request wheat but nothing is on his list.
It did work before, just something got lost lately.

**Comment by marchermans** [comment]
The RS is currently broken. We are working hard to fix this. But it is proving a very hard issue to fix.
Please bare with us.

**Comment by Lordbaane** [comment]
Hey, no problem guys, I just want to help test it out to make it better! I wouldn't be a backer otherwise. ;-)
