### ISSUE TITLE
Stone Restaurant lev4 to lev5

### ISSUE THREAD

**Issue by attilavv** [ldtteam/minecolonies#2096]
### Minecolonies version

constated : minecolonies-universal-1.12.2-0.8.6905 
Actual : minecolonies-universal-1.12.2-0.8.7200

### Expected behavior

Build to the end.

### Actual behaviour

Stone Restaurant level 4  to level 5 bug.

Builder need 3 music disc. Tested with 3 types of disc and same as picture : Green disc : C418 - cat but stop building. It move with a chest in hand. Go to building wait a moment and go back to the builder hut and need again a music disc.

### Steps to reproduce the problem

Just play in survival mod. Place it, upgrade it again and again.

**Comment by nosfiratys** [comment]
Have the same problem with 
minecolonies-universal-1.10.2-0.9.7375 and earlier versions

**Comment by Asherslab** [comment]
Is this fixed now?

**Comment by Raycoms** [comment]
Should be fixed

**Comment by BonaireDreams** [comment]
Not sure if this broke again but we're on .8618 and the builder keeps going back and forth asking for a disc  when trying to upgrade the stone restaurant from Tier 4 to Tier 5.
