### ISSUE TITLE
Wooden smeltery need a "spawn"

### ISSUE THREAD

**Issue by attilavv** [ldtteam/minecolonies#2097]
### Minecolonies version

constated : minecolonies-universal-1.12.2-0.8.6905
Actual : minecolonies-universal-1.12.2-0.8.7200

### Expected behavior

Build to the end.

### Actual behaviour

Wooden smeltery level 3 to level 4 need a Spawn. 
In design with the building tool you can see a cow on a fence.
The builder stop build.

Tested with creative spawn egg ( cow and other passive mob but same problem )
same problem.

### Steps to reproduce the problem

Just play in survival mod. Place it, upgrade it again and again.

**Comment by Asherslab** [comment]
Is this fixed now?

**Comment by Raycoms** [comment]
Should be fixed
