### ISSUE TITLE
cook does not cook

### ISSUE THREAD

**Issue by DjTylerD** [ldtteam/minecolonies#2099]
**Minecolonies Version**

minecolonies-universal-1.12.2-0.8.7210
Forge1.12.2-14.23.1.2555
no other mod

**Info**

maptest: creative flat solo (3; minecraft: rock mother, 20 * minecraft: earth, minecraft: grass; 1; village)
/ mc colonies rsResetAll after new version alfa

**Expected behaviour**

cooked raw food, distributed cooked food.

**Real behavior**

level 1: directly charge the four, do not ask for fuel and do not charge him gives manual, distributes raw food
level 5: load the four after the fifth pile of food, do not ask for fuel oil, distribute raw food

**Steps to follow to reproduce the problem**

created new world
townall, builer, warehouse, delivery man, all in level 5
1 restaurant level 1, 1 restaurant level 5
20 stack of raw pork in the warehouse
watch the 2 cuicsinier

**suggestion**

- correct demand fuel, limit 1 stack buffer to feed village, ask nouriture that if 1 empty
- if possible: created a priority request food to cook minimum 32 article, and if there is no reserve give: apple, watermelon, carrot, etc ...
- note: clown fish, puffer fish, spidereye are considered as food, not logical as in vanilla

_sorry i'm french and i use google translation_

**Comment by Raycoms** [comment]
The newest version should resolve this now.

**Comment by DjTylerD** [comment]
**starting:**
- update minecolonies-universal-1.12.2-0.8.7273
- / time set night
- emptying: inventory cook, chest and furnace restaurant
- / mc colonies rsResetAll
- / time set day

**observation cook level 1:**
- it loads the furnace to the 2nd stack received by the deliveryman
- he does not request fuel
- if you give him 64 planks in his inventory he does nothing, except if you unload the raw food from the oven, he loads the entire furnace

thank you for all the work you do on this mod

**Comment by Raycoms** [comment]
Will take a look at this later.

2018-01-30 20:09 GMT+00:00 DjTylerD <notifications@github.com>:

**Comment by DjTylerD** [comment]
thank you excellent work minecolonies-universal-1.12.2-0.8.7307 
ok all works level 1 and 5.
remains to learn from the cook so that he becomes like Gordon Ramsey XD

**Comment by Ashley047** [comment]
I HAVE THE SOLUTION FOR THE BASIK PROBLEM IN MINECOLONIES 
JUST FOLLOW THE STEPS AS SHOWN IN THE PICTURE
--------------FIRST------------------
![2020-04-18_01 07 42](https://user-images.githubusercontent.com/63372171/79606147-f818f100-8112-11ea-9f5b-0323f17af607.png)
-------------SECOND-----------------
![2020-04-18_01 10 00](https://user-images.githubusercontent.com/63372171/79606214-10890b80-8113-11ea-8edb-a5b2ac730461.png)
-------------THIRD---------------------
![2020-04-18_01 13 41](https://user-images.githubusercontent.com/63372171/79606240-1b43a080-8113-11ea-8eac-8849ace32a48.png)

FOLLOW ALL THE STEPS TO SOLVE OR FIX THE PROBLEM

**Comment by ghost** [comment]
https://github.com/ldtteam/minecolonies/issues/4668
