### ISSUE TITLE
Builder

### ISSUE THREAD

**Issue by Vealikaso** [ldtteam/minecolonies#2101]
### Minecolonies version

version 0.8.7210

### Expected behavior

- Builder picks up cobblestone and goes buildind

### Actual behaviour

- Still asking for materials, even if they are at Builder's chest

### Steps to reproduce the problem

1. Build Builder's Hut
2. Ask to build something.
3. Wait untill builder ask for materials
4. Deposit material in their chest
![2018-01-28_00 51 52](https://user-images.githubusercontent.com/35880693/35477565-e42af066-03c5-11e8-87f7-0616b8691279.png)
![2018-01-28_00 52 01](https://user-images.githubusercontent.com/35880693/35477567-e8b4f492-03c5-11e8-99cc-64a9cc2fd493.png)

**Comment by marchermans** [comment]
Yes it is a known bug of the RS. It does not respect priority right now. And just picks a resolver at random.
We are running an internal test build that should fix this.
