### ISSUE TITLE
Crash on open TownHall Statistics

### ISSUE THREAD

**Issue by vagner1000** [ldtteam/minecolonies#2102]
[crash-2018-01-28_02.01.52-client.txt](https://github.com/Minecolonies/minecolonies/files/1670799/crash-2018-01-28_02.01.52-client.txt)
### Minecolonies version

version minecolonies-universal-1.10.2-0.9.7220

**Comment by SanAndreaP** [comment]
same issue: https://gist.github.com/SanAndreasP/cc0669b1c02855ef2514b70fb7f83e13

For me it happens when I try to build my first town hall, it shows me the material costs and after clicking "build", it crashes

**Comment by Raycoms** [comment]
Added a fix to the next pr for it

**Comment by vagner1000** [comment]
Thanks

**Comment by vagner1000** [comment]
Hi, the same problem on version: minecolonies-universal-1.10.2-0.9.7232.jar
I removed all mods to test. Thanks.

[crash-2018-01-29_20.36.23-client.txt](https://github.com/Minecolonies/minecolonies/files/1675672/crash-2018-01-29_20.36.23-client.txt)

**Comment by Raycoms** [comment]
The newest version should resolve this now.
