### ISSUE TITLE
Builders copying them selves 

### ISSUE THREAD

**Issue by Howman** [ldtteam/minecolonies#2103]
### Minecolonies version

minecolonies-universal-1.12.2-0.8.7210

### Expected behavior

- One Builder

### Actual behaviour

- Copys of the same builder

### Steps to reproduce the problem

1. Not really sure it been happening a lot but not this this extent.

[Minecraft 1.12.2 1_28_2018 1_25_51 AM.M2TS.mp4.zip](https://github.com/Minecolonies/minecolonies/files/1670846/Minecraft.1.12.2.1_28_2018.1_25_51.AM.M2TS.mp4.zip)
5 sec video clip
 
2. ZYX
3. ...
4. Profit

**Comment by Raycoms** [comment]
Yeah this happens occasionally unfortunately, it seems to be minecraft which causes this. Please restart to fix it.
