### ISSUE TITLE
Client crash - com.minecolonies.coremod.colony.buildings.views.AbstractBuildingView.getOpenRequests

### ISSUE THREAD

**Issue by ProsperCraft** [ldtteam/minecolonies#2104]
### Minecolonies version

- minecolonies-universal-1.12.2-0.8.7210

### Actual behaviour

- https://gist.github.com/ProsperCraft/cd55139ba1eb9501571b4cf2b39e24c0

**Comment by Raycoms** [comment]
Fortunately, I was able to fix this in the last build. Will go live
tomorrow or Tuesday. =)

2018-01-28 18:27 GMT+00:00 ProsperCraft <notifications@github.com>:
