### ISSUE TITLE
1.12.2 - Builder will not pull things from his buidlers hut chest.

### ISSUE THREAD

**Issue by ProsperCraft** [ldtteam/minecolonies#2105]
### Minecolonies version

- minecolonies-universal-1.12.2-0.8.7210

### Expected behavior

- Builder takes the items he needs from the builders hut.

### Actual behaviour

I have to take things out of his hut and hand it to him.
The following stacktrace is in the server console - 
- https://gist.github.com/ProsperCraft/d9ddc48d8084907654440aaadb7cc8a2

**Comment by Raycoms** [comment]
Also already fixed in the debug branch, will also go live at max tuesday =)

2018-01-28 18:54 GMT+00:00 ProsperCraft <notifications@github.com>:
