### ISSUE TITLE
Villagers speaking - same thing twice in a row.

### ISSUE THREAD

**Issue by ProsperCraft** [ldtteam/minecolonies#2106]
### Minecolonies version

- minecolonies-universal-1.12.2-0.8.7210

### Expected behavior

- Villagers cycle through a long list of babble

### Actual behaviour

- Villagers only say a couple things, and often they say the same thing twice in a row withing seconds of eachother.

**Comment by alpan1** [comment]
lol my builder and delivery both keep on complaining about their husbands telling them that they eat to much. It gets tiresome for sure.

**Comment by Raycoms** [comment]
That's a minecraft problem. We only define it by XML. The probability calc is by minecraft itself.
