### ISSUE TITLE
1.12.2 - Upgrade to stone lumbar hut from wood, and you get half a wood building.

### ISSUE THREAD

**Issue by ProsperCraft** [ldtteam/minecolonies#2107]
### Minecolonies version

- minecolonies-universal-1.12.2-0.8.7210

### Expected behavior

- They tear down the entire old building.

### Actual behaviour

![2018-01-28_23 47 43](https://user-images.githubusercontent.com/4427684/35497058-ca33b07e-0485-11e8-8382-aba7d169df1d.png)

### Steps to reproduce the problem

1. Build a taiga lumbar hut,
2. upgrade it to level 3
3. upgrade To lumbarjack 4 stone
4. View the awesomeness.

**Comment by marchermans** [comment]
@Raycoms we need to take a look at structure downgrading.

**Comment by Raycoms** [comment]
For now switching is like that, else we would have to create a lot if additional tasks to let the builder deconstruct first. But currently at the moment of building we only have the info of the current level and not of the last one to compare them

**Comment by marchermans** [comment]
We could technically once the RS is stable switch the builder from the workmanager to the RS.
It would allow us to combine build requests together. Just a note for the future.

**Comment by Raycoms** [comment]
I think that's not that big of a problem atm. the bigger problem is that we have to code the "deconstruct" task extra. Shouldn't be that hard, we can include that with the "chest relocation" feature.

**Comment by marchermans** [comment]
Hmm okey
