### ISSUE TITLE
[BUG] The food disappears with the restaurant on a citizen with full inventory

### ISSUE THREAD

**Issue by AlexandrePavy** [ldtteam/minecolonies#2119]
### Minecolonies version

version 1.12.2-0.8.6996

### Expected behavior
The food should not go in void when the cook feed a villager with full inventory. 

But what is the good behavior ? 
- Cook is waiting for an empty slot? But the citizen will also wait for food and wait forever

### Actual behaviour

When citizen are fully inventory (like deliveryman) and he go to the restaurant, he consume all food (food disappear one by one)

### Steps to reproduce the problem

1. Build restaurant
2. fulfill inventory of a hungry Citizen
3. Watch the cook's inventory emptying
4. Profit

Thanks !

**Comment by AlexandrePavy** [comment]
Good job, what is behavior now ? cook don't give food to citizen ? Citizen gonna wait food ?

Best regards.

**Comment by Raycoms** [comment]
Cook will complain to the player that he is unable to feed him.
