### ISSUE TITLE
Tomb many graves bugging out

### ISSUE THREAD

**Issue by gaminggirl** [ldtteam/minecolonies#2120]
### Minecolonies version

version 14.23.1.2587

### Expected behavior

- When I die I get a grave, when I sneak over it it opens and I get my stuff

### Actual behaviour

- When I die I get a grave, when I sneak over it nothing happens

### Steps to reproduce the problem

1. Die
2. Return to grave
3. Sneak over it
4. Profit

**Comment by Raycoms** [comment]
Sorry, this github is only for minecolonies related issue, for tomb issues you have to go to their github, or search support on our discord if its on the official server.
