### ISSUE TITLE
[Discord Suggestion] Guards Carry Torches

### ISSUE THREAD

**Issue by Imrielle** [ldtteam/minecolonies#2122]
Hey, would it be possible to have that guards walk around at night holding torches that light up the path as they walk? IE Optifine's Dynamic Lights and it be compatible with shaders? would look nice

From: Cain Seldon#4999

**Comment by Raycoms** [comment]
I'd say we can close this because of three things:

a) We would need other mods to make that make sense
b) It then creates quite some lag (at least for my laptop)
c) We want them to wear shields.
