### ISSUE TITLE
[Discord Suggestion] Additional Employment

### ISSUE THREAD

**Issue by Imrielle** [ldtteam/minecolonies#2123]
What if....at Lvl 5 some buildings could employ additional citizens? Like say at Lvl 5 the restuarant has the Cook and a Bartender

From: LadyShatana#8683

**Comment by chriskeena** [comment]
Perhaps the ranking worker could take on an apprentice? Automaticlly getting promoted on worker death.

**Comment by Raycoms** [comment]
I will close this for now, since it's rather unspecific. We can employ additional people.
A bartender is for example planned for the Inn later on.
