### ISSUE TITLE
[Discord Suggestion] Cold Biomes Heating Logic/Happiness

### ISSUE THREAD

**Issue by Imrielle** [ldtteam/minecolonies#2125]
Hey maybe if the colony is in a cold biome they would use a furnace in the citizen huts and consume a log per night for warmth and if they cant do that it would lower the happiness a small bit

From: TheSwedishPilot#2690

**Comment by Theamericanpilot** [comment]
👍

**Comment by Raycoms** [comment]
Closed in favor of joint issue.
