### ISSUE TITLE
Miner's constantly request diamonds picks, even if they have them already

### ISSUE THREAD

**Issue by DuskFalls** [ldtteam/minecolonies#2127]
### Minecolonies version

version 0.0.6983

### Expected behavior

- Go and mine stuff with the diamond pickaxes theyre already holding

### Actual behaviour

- Stand around asking for another one

### Steps to reproduce the problem

1. Have a miner who's dug the first two layers
2. Miner asks for diamond pickaxe
3. Give him one, but then he asks for a second one
4. Give him a second one but then he asks for a third?
5. Not Profit

**Comment by Raycoms** [comment]
What is your miners building level, at the moment the miner will request a diamond pick if he found a resource he can't mine, but if his hut level is not high enough he won't recognize that.

**Comment by DuskFalls** [comment]
It's 3 at the moment
I'll upgrade it just in case, and I did check if there was anything he couldnt mine down in the shaft but there wasnt anything

**Comment by Raycoms** [comment]
Some random modded block seem to have a certain hardness implemented which
get displayed for our miner as "diamond level".

2018-01-31 18:57 GMT+00:00 Jamie Horncastle <notifications@github.com>:

**Comment by DuskFalls** [comment]
Is the highest tier the miners can request diamond picks then?

I just checked all the blocks that he'd look at, theyre all either stone variants of slate (from rustic), which he's already mined with lower tier pickaxes

**Comment by Raycoms** [comment]
level 4 they should work, level 5 if enchanted.

2018-01-31 19:03 GMT+00:00 Jamie Horncastle <notifications@github.com>:

**Comment by DuskFalls** [comment]
I'll get the miner to that and then see if it's fine, thanks for the advice

**Comment by DuskFalls** [comment]
I got the miner to level 4, fired and rehired and then finally he started working again

I had previously fired and rehired him so i'm guessing theres a problem with miners under level 3 OR its not clear that the building needs to be 4 or 5 before they'll continue

**Comment by Aynjul** [comment]
I had to go further back in the walls than what the Miner would actually see. In my modpack Rutile ore was the problem.

**Comment by mkienenb** [comment]
Probably will be resolved once issue #2219 is resolved.
