### ISSUE TITLE
Workers should not eat requested items

### ISSUE THREAD

**Issue by nick-johnson** [ldtteam/minecolonies#2129]
When a worker requests a food item for a job (builder requests fish to build fisherman's hut, swineherder requests carrots) and are also hungry, they will eat it instead. This can be very painful if the worker eats something rare like a clown fish. Workers should not eat anything that they are currently requesting/using for a job.

**Comment by marchermans** [comment]
I am sorry but that is sadly not possible. To save on memory the system deletes the request data after it has arrived at the citizen and the stack turns back into a normal stack like everything else.

Keeping track of that is simply impossible. I wish it was different too. But there is not much i can do.

**Comment by Raycoms** [comment]
We can check in the builder if the food item is in the required items

**Comment by marchermans** [comment]
We could do that.
But that would probably fix it only for the builder. Altough i guess it would solve the issue more or less.
