### ISSUE TITLE
No chest full of important stuff with camp or supply ship

### ISSUE THREAD

**Issue by Rovinion** [ldtteam/minecolonies#2133]
### Minecolonies version

1.12.2-0.8.7312

### Expected behavior

- I place a SupplyCamp chest or SupplyShip chest, and get a chest containing a town hall and build tool where I placed the chest

### Actual behaviour

- The camp/ship spawn, but there is no chest containing the town hall or build tool-only chests that spawn are empty

### Steps to reproduce the problem

1. Find nice clear area/large body of water for camp/ship chest
2. Place ship/camp chest
3. Spawn ship/camp but no chest

**Comment by Raycoms** [comment]
Did you spawn it in creative mode?

2018-02-02 0:31 GMT+00:00 Rovinion <notifications@github.com>:

**Comment by Rovinion** [comment]
Yes, and now that you mention it, the supply ship does work in survival mode. Is it supposed to not spawn anything in creative?

**Comment by Raycoms** [comment]
Exactly.

2018-02-02 0:44 GMT+00:00 Rovinion <notifications@github.com>:

**Comment by Raycoms** [comment]
In creative you can place an infinite amount but they don't give you the items since you can get them in creative anyway =P

**Comment by Rovinion** [comment]
OK thanks
