### ISSUE TITLE
[suggestion] miner builds bridges

### ISSUE THREAD

**Issue by DjTylerD** [ldtteam/minecolonies#2135]
the minor is one of the first citizen, can you bridge the gaps and the big caverns
right now here is what he builds (not very pretty)
![2018-02-02_00 59 44](https://user-images.githubusercontent.com/35812264/35713243-9cf0b5f0-07c6-11e8-879e-7b3b7f3b5755.png)

here is an example in fault:
![2018-02-02_01 19 03](https://user-images.githubusercontent.com/35812264/35713270-bca9826e-07c6-11e8-9b81-f0cb69f858b8.png)

another in the cave:
![2018-02-02_02 32 26](https://user-images.githubusercontent.com/35812264/35713287-d3bfb2ac-07c6-11e8-98f3-924e632baf39.png)

**inconveniant:**
1: can this kill by monsters (but it adds gameplay)
2: the bridge can burn through the lava and prevent it from continuing on this path so will work on another (bridge can be made of stone)

**technical if possible in java minecraft** (_because I know that the java website_)

before building
{if: (test 4 block after, an area of 5x5 = air)
     {build the bridge;}
else: {normally builds minerX2Top or minerX2Right ect ...}}

example for test area (red glasse)
![2018-02-02_01 59 34](https://user-images.githubusercontent.com/35812264/35713340-1b10871c-07c7-11e8-8203-a53213ea4aff.png)

I'm sorry I'm french, I translate with google translate

**Comment by marchermans** [comment]
@Raycoms who worked on the original miner Building logic?

**Comment by chriskeena** [comment]
I'd like to see the miner only fill the floors unless preventing flooding.

**Comment by Raycoms** [comment]
That was me

**Comment by DjTylerD** [comment]
this is the first time I have a colony next to a fail
the nineur starts at a height according to his level, instead of the bridge it was a bend in dirt (as in the picture deeper)
![2018-02-05_12 42 35](https://user-images.githubusercontent.com/35812264/35803635-c802f298-0a74-11e8-8b96-8e4d77fe4d01.png)

for its that I thought about building a bridge for empty space.
@chriskeena the miner works remotely on the chematic before, so no problem
On the risk is the lava or the water that blocks the way, but he works on several tunelat the same time.
after if the air test area changes (ex: 5x5x2) to detect lava and water, he creates a tunnel

Edit: another possible bridge to solve the problem of water
![2018-02-05_14 09 01](https://user-images.githubusercontent.com/35812264/35806051-706e07d4-0a7e-11e8-9376-a32b3563ed78.png)

**Comment by kreezxil** [comment]
I like this idea.

**Comment by Raycoms** [comment]
The main problem I see with this is that its a bunch of wood which can take
fire and close the miner in.
Any solution ideas for that?
Searching for all lava blocks in a certain range evertime we detect a
"hole" would be quite some work.

2018-03-15 14:53 GMT-03:00 kreezxil <notifications@github.com>:

**Comment by chriskeena** [comment]
Build the bridge sections from cobble. The miner should be producing their own supply as needed. Cobble fences may require an outside source or teaching the miner the recipe.

**Comment by Raycoms** [comment]
Closed in favor of joint issue.
