### ISSUE TITLE
Duplication of villager

### ISSUE THREAD

**Issue by attilavv** [ldtteam/minecolonies#2136]
### Minecolonies version

Forge 2604 ( in modpack )
version ; minecolonies-universal-1.12.2-0.8.7273
- Barbarian is disabled in config file

### Expected behavior

- No duplication

### Actual behaviour

- Trace of duplication.

1 - In fml-junk-earlystartup.log ( extract )
[fml-junk-earlystartup.log](https://github.com/Minecolonies/minecolonies/files/1688417/fml-junk-earlystartup.log)

2 - In player console.
![villager](https://user-images.githubusercontent.com/35277791/35720992-63c0dc4a-07f0-11e8-9669-5bec94780484.jpg)

3 - Old picture in old post.

### Steps to reproduce the problem

Not found a process for reproduct at this time.

**Comment by marchermans** [comment]
We really need to work on entity deduplication. I will take a look today to start using WeakReferences and Optionals.
@Raycoms Ping me in Slack.

**Comment by attilavv** [comment]
Hi,

Server upgraded : minecolonies-universal-1.12.2-0.8.7312

Now : I have 2 deliveryman from same house. And one group of 4 of soldiers have duplication for 3 soldiers.

For me it is "always" (99%) on upgrade and "some time" in "start up" (1%). 
YES i make many and many upgrade for found some bug. Like a big memory leak ( 2GB to 6GB in 2/3 hours ). Removing some mods again and again.
And YES for me you have resolved this big memory leak. 
But at this time i update only Minecolonies mod. Same time other for minor change like some recipes.

![mem](https://user-images.githubusercontent.com/35277791/35737725-ce838e10-082c-11e8-9879-64b89ac0a41f.jpg)

**Comment by marchermans** [comment]
So is the mem leak fixed or not?

**Comment by attilavv** [comment]
Not sure for me ...
Before the big washing of debug i can say memory used = disk space.

Are you open a windows console in start up ?
A console Java not in the cycle of Forge. Only a little debug console and when you add a message it is output on Forge fml-junk-earlystartup.log. A console in a separated tread ? But i have a high CPU usage. And CPU usage change when i change version of Minecolonies. A console that wait the Forge tread and take CPU ressource for nothink. A console is same problem when you run a JAR, you can have all history and it is bad.

In fact all CPU ressource is "for me" doubled.

With this version ( 7312 ) i use 60% CPU ( indice is Verygame CPU usage )
with 7273 ... 90% ( the beging of remove debugging message )
with 7200 ... 120% or more. Verygames stop server after 3 reboots in 2 hours for High CPU usage. 
Before ... it is better ... 60% ...

Read my other issue for chunks loading.
For me, all is linked. Memory leak or usage, High CPU usage, Chunk loading, some fonction out the tread of Forge and duplication but it is a sign that some register, byte or other is not full controled.

If i have time, tomorrow i open a issue for proposion. For exemple, stop add news villager but make a price for recrute on town hall. That stop all kill by "lava bucket" for bad stat and possible to clean all villager for debugging. Add redstone control for "place in pause" a building if bug, for testing or debugging and for game play too ... stop farmer, stop wood ... 

xD

**Comment by attilavv** [comment]
![2018-02-03_01 11 53](https://user-images.githubusercontent.com/35277791/35760269-7e293f2a-087f-11e8-94e7-915ba8bc7d5a.png)

Server is .. OK ( 2x 60% ) .. 
Client is very out.1 FPM = Frame Per Minute !
I don't know how many villager is present but it is many and many.
Server is "open" from 8 hours without reboot ( 40/60% it is acceptable for Verygames )
Memory 3250MB to 3850MB ( for 8 Hours without connection, no player have make connection )

![2018-02-03_01 21 22](https://user-images.githubusercontent.com/35277791/35760510-e968f8ba-0880-11e8-8215-dc417bc72d15.png)

E = 259 entity in render for a total of 5765 ! ! !


Add a config entry for reset all villager.
ResetAtNextReset = True / False.
After reset is set to True place it to False.

Add a command for "disable", or fire like a job for village all or some villager.
At this time it is a Alpha / Beta this command is needed.
After for a Release version remove it if you want.

On Wiki add a description for Config and all command and how it work.
But for a problem like this the best way is the Wiki and found a command or a soluce.

**Comment by attilavv** [comment]
After thsi a decide to launch it in local without reboot my client.
And it is not possible, i have wait more 5 mins.

For me some data are not clear after disconned.
No entry found in fml-junk-earlystartup.log
No entry in fml-client-3.log ( i have rerun it, now it is 3 )
