### ISSUE TITLE
Birch Town Center Bug Bed

### ISSUE THREAD

**Issue by Largeboy31** [ldtteam/minecolonies#2137]
### Minecolonies version

minecolonies-universal-1.12.2-0.8.7312

### Expected behavior

It continues to work normally.

### Actual behaviour

The moment he gets up, he's stuck on a wall and he's dead.

Note:because of bug, men are dying and everything is reset.

**Comment by marchermans** [comment]
Well damn that fix does not work then......

**Comment by marchermans** [comment]
There is another bugfix round for that incoming as soon as @Raycoms is back.
We will need to see if that fixes is. Else i have to find a different solution.

**Comment by Largeboy31** [comment]
I wonder because of my modsim may be Quark

**Comment by marchermans** [comment]
No ideaI actually explicitely search for Air or a flower with a two high gap. So I have no idea why it is broken.
Now if they spawned under the bedrock and fell into the void (which some are doing), now that i know :D

**Comment by Largeboy31** [comment]
:D
