### ISSUE TITLE
Chunk loading come back ...

### ISSUE THREAD

**Issue by attilavv** [ldtteam/minecolonies#2138]
### Minecolonies version

version ;
Forge 2604
minecolonies-universal-1.12.2-0.8.7312
For take fonction /chunkloader
ChickenChunks-1.12.2-2.4.1.71-universal
CodeChickenLib-1.12.2-3.1.5.331-universal

### Expected behavior

Unload chunk is no body is present.
On server ;  after deconnect of player unloading chunks.

### Actual behaviour

Chunks is loading and never released.

### Steps to reproduce the problem

Install Forge / Minecolonies / ChickenChunks and CodeChickenLib.
Build a news world flat in creative.
Build a villager with two active villager. For me it is only 2 builder with 2 builder hut.
Use /chunkloaders to view ... move away ... come back ... move ...

--------------------------------------
Result for this LITTLE test !
I have make many news maps, probably 4 to 10.

1- Have found a problem from another issue.
For this test, on new map, after place the town hall, two builder i go away ... go away ... locking chunks load and unload ... and i see this message.
![nouvelle image bitmap 2](https://user-images.githubusercontent.com/35277791/35742284-49d0a23a-083a-11e8-8c0b-8ad7c2121f31.jpg)

2- Another time, possible another map but not sure.
Crash with error  -1073740771 ; [https://bugs.mojang.com/browse/MC-38384](url)
Another time this crash error in local ( it is the local server crash report )
[crash-2018-02-02_16.25.07-server.txt](https://github.com/Minecolonies/minecolonies/files/1689938/crash-2018-02-02_16.25.07-server.txt)

For another : YES minecolonies make loading chunks ! ! !
On this picture from night all is ok or not ...
Me is ok with 21x21 chunks. A mob are moving and have claming a new chunks accepted by Minecraft. And Minecolonies villager is sleeping with a 16x16 chunks ! ! ! 
![nouvelle image bitmap 4](https://user-images.githubusercontent.com/35277791/35742943-5e40f3f8-083c-11e8-9b4e-e91be05dad9a.jpg)

Yes 16x16 chunks is loader by villager. A bigger Quarry from Builcraft is 64x64 or 4x4 chunks. In fact 5x5 chunks is not centered. 256 chunks VS 25 chunks. Many FTB server accept only one Quarry or / and one chunks loader from railcraft ( a 3x3 chunkloader ). 

Now it is day ;
The array is 20x21 NOT 21x21 same a player. It not a 16x16 too.
![nouvelle image bitmap 5](https://user-images.githubusercontent.com/35277791/35744045-94add764-083f-11e8-986c-3cfe18766abd.jpg)

or 

This time the array is 21x22 better all of exist in Minecraft, better that a 21x21 from player.
And centered by ? ? ? a ghost ? ? ?
![nouvelle image bitmap 6](https://user-images.githubusercontent.com/35277791/35744059-a12097e8-083f-11e8-8839-d96e1a8c2a82.jpg)

It come not smooth. It come like a spawn of mob.
I have placed the blue line. it is not centered at me or yes for X pos but not for Z pos.
For this test i don't move, i have stopped to move and wait many minecraft day.
Always same chunks loading ... 16 x 16 = 256 chunks loaded.

In server, it is same thinks. Same problem but after a villager is loaded or "full loader" it never unload the chunks. All villager load some chunks and another villager. If a player from a village is not on the village, this village is not "full" loader.

I use "full loaded" but all existant village have always some chunks loaded. 2 to 10 and chunks is some time unloaded. For this no player need go in village.

**Comment by Asherslab** [comment]
Hi mate, our mod literally doesn't load any chunks, we have NO chunk loading code at all, one of the reasons for that is because It causes lots of lag. We Do Not Chunk Load. If what you are saying is correct, then this is Vanilla behaviour with our entities, nothing we can do.

**Comment by Justen-N** [comment]
This mod inherits entity behaviour from Forge.  None of the code deals in
any way with chunkloading. If the mod is chunkloading, then it stands to
reason that this behavior is inherited from Forge or from Minecraft itself.
Maybe, if we crawled through the Forge api, we might find a method to
change this behaviour. I don't  know.

**Comment by marchermans** [comment]
I checked. We do not chunk load period.

**Comment by attilavv** [comment]
Move method from Forge or Minecraft ?
A method for found a path ?
Declaration by default as some chunks distance and can be set to another value ?

Add a visitor spawnable by a stick without many code. Only for test. A stick that can't craft, only by give for admin. Usable for many test for all new version.

Yes it is probably a Vanilla / Minecraft or Forge component. Problem is many mod add mob passif, neutral or hostile and it is the first time i see this problem. This village have 4 villagers finaly. 2 builder and 2 without jobs that move very slow.

In my flat map built at 250 ( special option in start up ) i have some Vanilla villager and you can see villager move and change chunks ( max is 10 chunks total loaded ). With many time it is ONE chunks and full unloading. It is the normal method for Vanilla Villager. 

Another mystery is what is the array that come like a flash centered by nothing.
It is not a villager that have move but only in my direction. I have take picture on one direction but my test is from some hours. this array of loading chunks come like a flash and chunks are unloading, some time it come back before all chunks is unloaded, some time no.

And for the night ? Why nothing ? why no chunks is loaded ?


Have all of the team have make the test or only read this and say "No i want that it is NO" ?

**Comment by Raycoms** [comment]
Sorry it is very difficult to understand your description, minecolonies
doesn't load any chunks bit as all passive mods if their chunk is loaded
and they go to 1 neighboring chunk the pathfinding will load it and there
is nothing we can do, we already restricted that they at max path into that
1 chunk and not load a couple for pathfinding

**Comment by marchermans** [comment]
Yep. There is not much we can do here. Since this is simple vanilla behaviour.
I am going to close this issue unless the problem gets better described in at least readable English. If you do not speak English natively that is no problem. But keep your problem description then to a minimum, so we can figure out what is your problem for you.

State what is wrong in 1 or 2 lines aka:
_"Minecolonies is loading chunks when it should not."_

Then we know what you want and we can answer correctly.
