### ISSUE TITLE
[1.10.2]Crash when updating a world to a version newer than 0.8.5086 with TC6 installed

### ISSUE THREAD

**Issue by thephoenixlodge** [ldtteam/minecolonies#2143]
### Relevant mod versions

Minecolonies: 1.10.2 version 0.9.XXXX (any newer than 0.8.5086)
Forge 12.18.3.2511
Thaumcraft 6.0 Beta3

### Expected behavior

World to load

### Actual behaviour

Trying to open a world that was made previously on any version newer than 0.8.5086 while also having TC6 installed results in a soft crash (hanging with server state set to ERRORED but not actually closing out) with this crash log : https://pastebin.com/gXrRci3D

### Steps to reproduce the problem

See above, not 100% sure that this is exactly what's triggering it, but if a world encounters this soft crash, it will happen consistently.

**Comment by marchermans** [comment]
@Raycoms Another one.
@thephoenixlodge This is a problem of Thaumcraft / FoamFix. They do not behave properly when their blockstate gets written and read from NBT. Properly better to report it to them
