### ISSUE TITLE
Save size increasing every load/save

### ISSUE THREAD

**Issue by waynestir** [ldtteam/minecolonies#2145]
minecolonies-universal-1.12.2-0.8.6147

version 0.8.6147 or curse 14.23.1.2568  (client only.. no server used)

### Expected behavior
sit and wait for me to initiate
not grow into a life of your own unexpectedly 

### Actual behaviour
unknown.  never actually used mod yet
file size became too large to process in client
i.e. wouldn't load after only few hours a day few days a week of creative world building.

### Steps to reproduce the problem
Load client (not playing on server).. work on build for a few.  Then save & exit.

Hi,
New to minecraft …  started in version 1.12.2

exploring a lot of the new mods …  added AllTheMods3 which included a version of minecolonies.

     I never actually explored the mod to date only content from other mods in my week old creative build.  Load times were becoming a real problem after a few days.  In exploring the problem I noticed every time I exit the game the save dir would be 500MB larger than previous load time.  

    The culprit turned out to be minecolonies directory growing every game session without having even moved out of a 20 chunk radius from first spawn point in world creation.  I've since dumb-ed down my mod loads to eliminate the problem for now.  

     These issues are client load only.  Not playing on a server or loading one.

**Comment by Raycoms** [comment]
Please update minecolonies to the newest version to fix this issue.

2018-02-03 16:42 GMT+00:00 waynestir <notifications@github.com>:
