### ISSUE TITLE
Disable manually placing Town Hall, Builder's Hut, etc, and require Builder's Tool?

### ISSUE THREAD

**Issue by mkienenb** [ldtteam/minecolonies#2152]
As I played through my first Minecolonies game, I made the mistake of placing my Town Hall block and my Builder's Hut block manually without using the Building Tool, which caused me some confusion, such as thinking the Town Hall should be placed in the center of my supply camp.

Is there a valid reason to allow these blocks to be manually placed?   Or would we be better off disabling the manual placement and requiring the building tool?

Also, should we consider disabling the decorations menu until after the Town Hall is placed?   Having Decoration as the default menu when you first use the Building Tool is also confusing for a new player.  Since the building tool is already context-sensitive to your inventory contents, it would make the most sense to show a schematic for an schematic block in your inventory by default.

**Comment by marchermans** [comment]
No there is no valid reason.
Take a look at the `BlockTorch` class from vanilla MC. It allows placement only on solid sides of blocks. If you adapt that logic to not place at all. You should be good to go.

**Comment by Raycoms** [comment]
I think we should make them manually place able since there are a few
players which can't use the build tool since their computer is too bad.

**Comment by mkienenb** [comment]
From Zyx on discord yesterday

> Not the TH for sure, that's the best way to guarantee the exact center of your colony
But I think it may be suitable to add a note suggesting to place teh TH block to get colony position, then break it and use the wand
For the other blocks - that might not be a bad idea
The last time I checked, there was a comment somewhere that it was possible to break the TH block and replace it - but I'm not sure whether that was in the getting started tutorial

**Comment by mkienenb** [comment]
> I think we should make them manually place able since there are a few
players which can't use the build tool since their computer is too bad.

I will do some investigation on older computers.  All of my computers are old, and my one son's computer has a graphics chip with 8Mb of memory (it'll run vanilla MC and Attack of the B-Team but not much else)

But even if it has problems on older equipment, we should look at what can be done to make the build tool perform better.

**Comment by Raycoms** [comment]
When you're good with rendering there is something we can do else we have
to wait for orion to do it, we would need to adapt our build tool rendering
to work like the real world rendering.

2018-02-04 21:00 GMT+00:00 Mike Kienenberger <notifications@github.com>:

**Comment by mkienenb** [comment]
I think the way to address both the older computers and more-precise-placement issues is to have a simple mode on the building tool which only shows the placed schematic block (town hall, builder's hut) plus some simple indicators (outline of area or tinted shading for existing blocks rather than rendering the schematic) and uses the activation location as the location of the placed schematic block.

We can add it as a client-side mod configuration option, and also put a control to toggle between the two display types once the schematic is activated.

Along with this, we should consider showing the schematic blocks as 2d plans rather than 3d blocks to make the difference between schematics (patterns for the building tool) and normal blocks more obvious.

I did some timing yesterday before I got logging working and almost all of the time was spent in renderGhost.

**Comment by marchermans** [comment]
It is a known that the Schematic rendering takes a lot of time.
I have been working on this. But sadly it will take a Huge amount of time.

It has to wait until BlockOut is complete before we can make this work.

**Comment by mkienenb** [comment]
I try not to open enhancement issues that require someone else to do the work :-)

I think I may be able make a simple mode renderer by modifying the existing render that could perform better without a lot of changes.   I wanted to make sure that this was a goal that we wanted to pursue before I started.   It sounds like it is.

**Comment by Raycoms** [comment]
I will close this for now, the new blockout is faster but I still rather not force people to use the tools. We have to hint them to it, but sometimes people just want it the fast way.
