### ISSUE TITLE
Town Hall Bug

### ISSUE THREAD

**Issue by CoporalKritz** [ldtteam/minecolonies#2154]
4.15 Minecolonies version

version 14.23.2.2611

Expected behavior
For the town hall to function 

Actual behavior
As soon as I place a town hall block, it immediately shuts down the server and every time I 
try to re-log into the server, it shuts down again. 

The only way to reproduce the problem is simply place the town hall block, but I don't think that
would be helpful as it seems to work for most. I don't receive crash reports or logs from it either as it doesn't crash the game. Something else to note is that when it shuts down the server, it says "connection lost" and sends me to the multiplayer menu

**Comment by mkienenb** [comment]
I can't promise if I'll get a chance to look at it, but if you make a copy of your world available somewhere, I'll try to take a look today.

**Comment by Raycoms** [comment]
Might be related to this being 1.11.

We pushed a fix for 1.12, maybe forge changed this for 1.10 and 1.11 as well and we need to port the fix over.
