### ISSUE TITLE
Colonists keep dying in walls or 'out of world'.

### ISSUE THREAD

**Issue by Midge57** [ldtteam/minecolonies#2157]
### Minecolonies version

MineColonies Official 1.12-ver 4.17

### Expected behavior

- Colonists should not die from wall suffocation or falling out of the world, considering there is nowhere for them to actually do this in my colony.

### Actual behaviour

- Every single morning at least one colonist will die from being in a wall or falling out of the world. As a result, my happiness is forever at 1 and my colonists never level up, as they just die anyway.

### Steps to reproduce the problem

1. Have a colony.
2. Exist.

**Comment by figtito** [comment]
I'm still having this issue as well. I reported this in 2132 as well as some other people but for some reason that issue was closed even though it's still happening. I tried 7373 and the problem is still here.

**Comment by Lordbaane** [comment]
Maybe this part should be removed for the time being, suspended, until is can be sorted out.

**Comment by chriskeena** [comment]
It seems to be tied to teh new mechanic of colonists using beds. My character was pushed into a wall one morning after sharing a bed for the night with a colonist. And yes most mornings a colonist is sufocated.
The short term solution seems to be only assigning one colonist per house. I did also see death by falling out of the world and crushed to death by crowding.

**Comment by Justen-N** [comment]
We close issues when a commit should have fixed them if the commit did not
fix the error, please resubmit the issue. @oriondevelopment is endeavoring
to fix what is going on here. This should only be on the alpha/beta builds,
so the only options we can give you is keep being our awesome test
community or downgrade to the latest release build.

**Comment by AlexandrePavy** [comment]
Bug still with 0.8.7415, should add config to temporary disable this. 

Best regards.

**Comment by marchermans** [comment]
I figured it out. It was so stupid of me not to think of that.
