### ISSUE TITLE
Delivery man not delivering things and empty clipboard.

### ISSUE THREAD

**Issue by Boyownik** [ldtteam/minecolonies#2158]
### Minecolonies version
minecolonies-universal-1.12.2-0.8.7363

### Expected behavior

- Delivery man deliver materials to builder/miner.
- Clipboard shows requests.

### Actual behaviour

- Deliver man is running around the village with empty inventory, i've placed materials in Warehouse and he act like there is no of them.
- Clipboard is empty, i think that's the reason delivery man isn't deliver things (he can't see any requests).

### Steps to reproduce the problem

1. Build a village
2. Build delivery man, warehouse, builder, miner.
3. Profit

Edit1: How does Delivery priority works? Can i customize it? Like set builder to highest priority, next sawmill etc.
Also, often when builder has request, i fill materials in his hut  and he still can't get them. I have to give materials to his inventory, after that he starts his job again and works fine untill i re-enter my world.

Edit2: It looks like it happens only when i close my save/whole game when for example builder is waiting for materials/in mid of his job. When i "restarted" builder, messages with requests appears normally and delivery man works fine.
Edit3: Oooops, my mistake. Requests are disappearing in the morning when colonists wake up.

**Comment by grugsy** [comment]
having similar issue. deliverymen go to all buildings, but pick nothing up/deliver nothing with the exception of milk and eggs. they randomly dump 5-6 buckets of milk into mine/fisher/sawmill/builder chests. do nothing else. noticed this after adding animal buildings. (playing on latest alpha, first noticed several builds back when my villagers were suddenly starving)

**Comment by Raycoms** [comment]
should be fixed
