### ISSUE TITLE
Builder needs to indicate why work stopped if build-hut chest is full and builder wants to put something in it.

### ISSUE THREAD

**Issue by mkienenb** [ldtteam/minecolonies#2169]
### Minecolonies version

snapshot from 2018-02-05: version/1.12 6118e4f2da3088f3cff52982237bc2d6525e2b08

### Expected behavior

- Some indication of why builder is standing next to hut chest

### Actual behaviour

- Builder stands with "Clearing" message displayed.

**Comment by Raycoms** [comment]
Should be fixed
