### ISSUE TITLE
Feature Request - wipe stone swords from barbarians on drop?

### ISSUE THREAD

**Issue by ProsperCraft** [ldtteam/minecolonies#2172]
The stone swords constantly stack up in hut chests, can you remove them on drop? 

Or do I need to add a filter and barrel for stone swords to all huts?

**Comment by ProsperCraft** [comment]
Or remove it from the drop table?

**Comment by PoroUsedSnax** [comment]
The smelter should be able to deal with these stone swords, just drop them in their inventory and they should work away.
