### ISSUE TITLE
[observation] miner ignores cobblestone construction

### ISSUE THREAD

**Issue by DjTylerD** [ldtteam/minecolonies#2173]
**Minecolonies version**
minecolonies-universal-1.12.2-0.8.7415
forge1.12.2-14.23.1.2555
OptiFine_1.12.2_HD_U_C8
no other mod

**info**: 
map test creative solo
/ mc colonies rsResetAll at every update

**Expected behavior**
     hollow tunel, harvesting ore, mouth holes, climbing structure

**Actual behavior**
  the miner recorks the holes and builds only with dirt (see do fail)
![2018-02-05_12 42 35](https://user-images.githubusercontent.com/35812264/35860946-4b63fb2e-0b46-11e8-914b-7338376c94c9.png)
  before on my server under construction (stop in July waiting for maj 1.13, very modified), he used the cobblestone (version: minecolonies-universal-1.11.2-0.8.2689)
  now he claims only dirt and ignores the cobblestone (2 double chest cobblestone in warehouse)

**Steps to reproduce the problem**
remove dirt in warehouse and miner inventory

**Comment by DjTylerD** [comment]
**retest:**
I just made a new map with miner level 5.
during the descent I help the miner and empty his inventory in dirt.
no problem cobblestone used for schematic "minerMainshaft"
then first schematic "minerx2top" tunel height 7 of the world

I observed in gamemode 3:
1- fill the air with cobblestone
2- dig and harvest ore
3- barrier application and dirt request to plug the holes
4- finished by laying board and torch

continuing with the other schematics, it is similar

**conclusion:**
  before the construction it recorks air with cobblestone,
but not during it needs dirt

**Comment by GanthorPrime** [comment]
Can confirm this this too. I notice to much cobblestone in the warehouse, and the miners always waiting for dirt from the dmans

**Comment by Raycoms** [comment]
should be fixed now
