### ISSUE TITLE
[Suggestion] Racks should be sortable like other modded inventories

### ISSUE THREAD

**Issue by nick-johnson** [ldtteam/minecolonies#2174]
Expected: Inventory sorting mods like Inventory Tweaks should work on the Rack inventories, similar to vanilla inventories/chests and modded inventories like the Actually Additions storage crate.

Actual: The rack inventory cannot be sorted with mods like Inventory tweaks.

**Comment by marchermans** [comment]
That is correct. Those mods look specifically for chests or anything implementing the vanilla interface.
However we tested this our Racks are compatible and can be added to the InventoryTweaks config file by the user. Sadly we can not do this from our side.

**Comment by mistysmilesalot** [comment]
What did your InvTweaksCompatibility.xml file look like?
