### ISSUE TITLE
[Suggestion] Allow patreons to add custom quotes to NPCs

### ISSUE THREAD

**Issue by Eufranio** [ldtteam/minecolonies#2175]
Patreons could be allowed to send their own voices speaking some message to some review/approvation system, or even on Discord. So, we would send message that would be quoted by NPCs for approvation somewhere along with the written message, and if it is approved, it gets included in the original collection of songs of Minecolonies.

*I'd like to send my own and friend's quotes for the mod :P*

**Comment by Raycoms** [comment]
Actually this is possible via datapacks nowadays. You can add a datapack with sounds with similar sounds categories as in the mod. These should be picked up by the workers then as well.
So this only has to be put in the modpack or similar then
