### ISSUE TITLE
Builder stuck in INVENTORY_FULL AiState because chest is full but inventory is not

### ISSUE THREAD

**Issue by mkienenb** [ldtteam/minecolonies#2179]
### Minecolonies version

2018-02-06 snapshot

- When builder tries to dump extra blocks due to inventoryNeedsDump(), it goes into INVENTORY_FULL state.   This can happen for reasons other than the inventory being full:
```
        return (worker.isInventoryFull()
                  || actionsDone >= getActionsDoneUntilDumping()
                  || wantInventoryDumped())
                 && !(job instanceof JobDeliveryman);

```
However, the INVENTORY_FULL state only handles the case when the chest is full and the inventory is full.  It does not handle the case when the chest is full but the inventory is not.

### Steps to reproduce the problem

1. Fill the builder's chest.
2. Have the builder dig out a lot of dirt.
3. Wait until the builder tries to get rid of the dirt due to ACTIONS_UNTIL_DUMP counts down from 32.

**Comment by grugsy** [comment]
playing on latest alpha, having same issue. noticed several partial stacks of stackable items, sometimes empty slots but builder stuck asking for something that is in the chest. combining them or even moving an item makes the builder function again. (partial stack issue with other chests as well, related or should I open a new issue?)

**Comment by Nightenom** [comment]
@mkienenb is this solved?
