### ISSUE TITLE
Add subtitles for sounds

### ISSUE THREAD

**Issue by mkienenb** [ldtteam/minecolonies#2180]
We need to define subtitles in the src/main/resources/assets/minecolonies/sounds.json file.
Each sound should have an appropriate translation string key and each translation key should be added to src/main/resources/assets/minecolonies/lang/en_us.lang.

For example:
(changes in **_bold-italic_**)

### sounds.json

`  "mob.builder.female.complete": {`
`    "category": "neutral",`
`   "sounds": [`
`     {`
`        "name": "minecolonies:mob/builder/female/projectcomplete",`
         **_subtitle": "com.minecolonies.coremod.sound.builder.female.projectComplete",_**
`       "stream": false`
`      }`
`  },`

### en_us.lang
**_`com.minecolonies.coremod.sound.builder.female.projectComplete=Builder says, "Project complete."`_**

**Comment by Raycoms** [comment]
Closed in favor of joint issue.
