### ISSUE TITLE
[forgets & sugestion] builder asks variant timberframe, and craft facility

### ISSUE THREAD

**Issue by DjTylerD** [ldtteam/minecolonies#2184]
before all super improvement that adds design to the hut, congratulation because not easy to take care of all

**Minecolonies version:**
minecolonies-universal-1.12.2-0.8.7450
forge1.12.2-14.23.1.2555
OptiFine_1.12.2_HD_U_C8
no other mod

**info:**
 map test creative solo
/ mc colonies rsResetAll at every update

**Expected behavior:**
    request in the timberframe chat, built when given

**Actual behavior:**
1. do not ask in chat
2. in request or clipboard, always ask for the timberframe total with the same icon (no amount of variation)
3. To know the variation look at his hand
![2018-02-07_13 44 57](https://user-images.githubusercontent.com/35812264/35919210-b43cc382-0c14-11e8-85a8-621045334748.png)

**Steps to reproduce the problem:**
fix hut and observe the builder

**suggetion craft**
_currently:_
 1 craft timberframe + 9 variation
- timberframe 4147/0 = 2 board + building tool (normal)
- timberframe 4147/1 = timberframe 4147/0 slot 0 in crafttable
- timberframe 4147/2 = timberframe 4147/1 slot 0
 ect ...

_possibility:_
use that timberframe 4147/0 and have the variant according to the example slot
- timberframe 4147/1 = timberframe 4147/0 slot 0 in crafttable
- timberframe 4147/2 = timberframe 4147/0 slot 1
- timberframe 4147/3 = timberframe 4147/0 slot 2
 ect ...
unless you've planned for the builder to self-craft later

**Comment by Raycoms** [comment]
Fixed already

**Comment by DjTylerD** [comment]
Hello sorry for my absence in the test, family problem.
I see that you have considered my topic, thank you for listening;
I notice in minecolonies-universal-1.12.2-0.8.7719.
on the craft table, every slot gives that doublecrossed, but not the other variant

**Comment by Raycoms** [comment]
yeah, they are in a row. First gives double crossed, put double crossed in, gets other, and so on.
