### ISSUE TITLE
[Discord Suggestion] Include warehouse contents in build hut required items list

### ISSUE THREAD

**Issue by mkienenb** [ldtteam/minecolonies#2186]
From: @Zyx#6333 

I've been wishing for the warehouse contents to be included in the build hut required items list so you aren't making more of what you already have.

We've been asking for a way to have the builder look ahead and request more than just the current block he needs -- we have the current option to add items from our inventory to the hut using a button on the required list, and the item turns green if we have the item in our inventory. We could add something where it turns blue if the items are in the warehouse, and the button instead adds the items to the delivery request queue.

**Comment by Raycoms** [comment]
Closed in favor of joint issue.
