### ISSUE TITLE
[suggestion] Command for scanning

### ISSUE THREAD

**Issue by carlansor** [ldtteam/minecolonies#2191]
It would make things easier for style pack creators to have a scan command, maybe with the next format:

/mc scan (point1 x y z) (point2 x y z) nameofscan.

 With that command stylepack creators can scan all buildings with some sort of command macro, or another mod that excecutes command automatically, reducing scan tedious time.

**Comment by Asherslab** [comment]
This has been made as of recently if i'm correct?
