### ISSUE TITLE
Server crash when blowing up mine colony

### ISSUE THREAD

**Issue by Kowantify** [ldtteam/minecolonies#2192]
https://pastebin.com/uwZMtE4S

Not to sure as to what mod is the issue, it's either ICBM or Minecolonies, I can't really tell, but yeah i lit off a bomb near the colony and boom! it crashed the server side, not client

### Minecolonies version
1.12.2-0.8.7455

### Expected behavior
Lit off bomb near entities/mine colony
- XXX

### Actual behaviour
game crashed
- YYY

### Steps to reproduce the problem
get anti matter bomb, light off near colonies, causes crash
1. XYZ
2. ZYX
3. ...
4. Profit

**Comment by Misunderstood-Wookiee** [comment]
It's Minecolonies, causing `java.lang.NullPointerException: Ticking entity`

**Comment by copperwarrior** [comment]
It's actually both, caused apparently by an antimatter bomb going off near a citizen. I recommend not blowing up antimatter bombs near colonies.

**Comment by Raycoms** [comment]
I think the mod messes with something when it explodes.
