### ISSUE TITLE
Concurrent thread exception when supplying builder

### ISSUE THREAD

**Issue by Misunderstood-Wookiee** [ldtteam/minecolonies#2193]
### Minecolonies version

version 1.12.2-0.8.7455 or curse v14.23.1.2587

### Expected behaviour

- Chunk Load without issue

### Actual behaviour

- Concurrent thread crash when loading colony chunks near builders chest
https://pastebin.com/LJ6C2ayZ

### Steps to reproduce the problem

1. Creative Mode 
2. Open Builder Chest, & Click the ^ arrow to creatively fill supply demand.
3. ...
4. Profit

**Comment by Misunderstood-Wookiee** [comment]
Hmm appears loading the same world in SSP works, but join my local server and it crashes not sure if it was this mod I have three server-side mods running on the server. Just strange that this happens right after I was giving builder supplies in creative.

**Comment by marchermans** [comment]
@Misunderstood-Wookiee Can you please format the exception log so that it is humanly readable?
Maybe by uploading it to gist or pastebin.

**Comment by Misunderstood-Wookiee** [comment]
Done, however, it's a concurrent exception halt with nothing to read anyway Forge throws it for any concurrent exception nothing in the log relates to this mod specifically. It was just odd that it crashed while I was spam clicking the builder chest's needs in creative mode.  However, as I said moving the world over to Single-Player as I have my own modpack for the server and it appears the world loads without this crash. 

So a server-side mod is likely at fault. I also tried updating Forge too the latest stable _2611_ caused the same issue but at least I know the pack is working alright so far on this version as well

Things I did try - fresh player data, empty colony data, enabling Forge errored entity removal values (in-case it was a bad entity) moving the world into single-player and behold that worked fine. 


**UPDATE**
**This error only affects SMP**, (Open-Lan, or Internet) anyone joining a server gets kicked with this error, loading the whole world via SP and there is no issue, however, open the world to LAN and the joining player is kicked on chunk gen where my colony is, there is a floating construction tape in one of my colony chunks which cannot be removed and states an invalid name which may have been created by the update to the tape which was reverted in a subsequent update.  This reeks of chunk corruption which oddly is only effecting SMP client joins.

**Comment by Raycoms** [comment]
This doesn't seem to be us, I can't find anything minecolonies related in this log.

**Comment by Misunderstood-Wookiee** [comment]
That's alright, I could not see anything related to this mod either but it did crash only whilst inside of the colony chunks, spawning outside the colony far enough before the chunks are loaded by server/client the game is stable. Crash as soon as colony chunk loaded and it only effects those clients who joined and have not hosted or the actual server PID. Which was so strange.  

The only thing I could think of after testing more was that it was right after the tape update and I had a leftover tape model floating in the air which could not be interacted with and had an invalid name registered.
