### ISSUE TITLE
Moving items from rack in warehouse bug

### ISSUE THREAD

**Issue by Boyownik** [ldtteam/minecolonies#2194]
### Minecolonies version
minecolonies-universal-1.12.2-0.8.7455

### Expected behavior

- Move items from rack in warehouse to player inventory by shift+left click

### Actual behaviour

- Items, for example full stack of cobble is moved to player inventory and weird things happens, first, one part of armor is taken off (by clicking shift + left click on items in rack, it looks like armor is still in right player's slots but armor above health decrase) next when i sort my inventory by other mod, "moved" items from rack disappears . Re-enter world causes items go back to rack, not player inventory

### Steps to reproduce the problem

1. Pull out items from rack in warehouse by shift + left click (player have full armor on himself).
2. Profit
Edit1. Also i can't place anything in warehouse too D: 
I've checked twice, it still happens and i can't pull out cobblestone from warehouse :D

**Comment by DjTylerD** [comment]
if it helps
I confirm, the problem is on all rack
I tested in the restaurant:
- put 64 blocks in the rack
- left click to take 1 block in the rack
it removes the rack stack

minecolonies-universal-1.12.2-0.8.7450
forge1.12.2-14.23.1.2555
OptiFine_1.12.2_HD_U_C8
no other mod
