### ISSUE TITLE
Lumberjacks want to collect dropped items from Conveyor Belts

### ISSUE THREAD

**Issue by Eufranio** [ldtteam/minecolonies#2196]
I jave a lumberjack that has trees to cut, but near the farm I have a Conveyor Belt system (from Immersive Engineering). The items on conveyor belts keep moving as usual, but the NPC always want to collect the items from the conveyors, and don't cut any tree, as he's on a loop trying to get into the conveyor belts.

NPC info:
```
> [17:07:24] [Server thread/INFO]: ID: 7 Name: Oliver Y. Ashcombe
> [17:07:24] [Server thread/INFO]: Citizen position: x=-22336 y=63 z=8757
> [17:07:24] [Server thread/INFO]: Home position: x=-22372 y=71 z=8777
> [17:07:24] [Server thread/INFO]: Work position: x=-22332 y=63 z=8757
> [17:07:24] [Server thread/INFO]: Health: 20.0 Max Health: 20.0
> [17:07:24] [Server thread/INFO]: Level: 0 Age: 0 Experience: 0
> [17:07:24] [Server thread/INFO]: Charisma: 6 Dexterity: 2 Endurance: 7
Intelligence: 2 Strength: 3
> [17:07:24] [Server thread/INFO]: Job: Lumberjack
> [17:07:24] [Server thread/INFO]: Desired activity: WORK Current Activity: LUMBERJACK_GATHERING
```

EDIT: I think this is going to need a hardcoded check. Immersive Engineering spawn and moves the items on a vanilla way (spawning the EntityItem and changing it's motion), so there's no clean way to detect if an item is being carried by a conveyor belt. An *ugly* fix that I can think of is blacklisting NPCS from picking up items that are in the same position as a TileEntity (aka inside the TE, if the TE holds an item I don't think you're supposed to pick it up), or add an hardcoded check to see if there's a Conveyor Belt near the item.

**Comment by Sandriell** [comment]
Immersive Engineering puts an NBT flag on items while they are on conveyor belts- "PreventRemoteMovement". It is designed to prevents magnets from interacting with the items, but could easily be used in this case as well.
