### ISSUE TITLE
Recalling the NPC while he's sleeping won't wake him up

### ISSUE THREAD

**Issue by Eufranio** [ldtteam/minecolonies#2197]
If you recall an NPC while he's sleeping, he won't wake up, see:

![img](https://image.prntscr.com/image/e1bPZzvkTBiCAHq4uYUafg.png)

Note: lmao

**Comment by marchermans** [comment]
Well................ @Raycoms did you not want to fix that.

**Comment by DjTylerD** [comment]
Humor: Minecolony has become so realistic that there are also homeless people

**Comment by Raycoms** [comment]
@Eufranio can you reproduce this with the newest version?

**Comment by Raycoms** [comment]
Should be fixed in the newest version.
