### ISSUE TITLE
Lumberjack continuously stop cutting trees

### ISSUE THREAD

**Issue by lebanni** [ldtteam/minecolonies#2198]
### Minecolonies version
Minecraft 1.12.2
version 0.8.7466 but happened on all previous versions

### Expected behavior

- Lumberjack cut trees one after another.

### Actual behaviour

- Stop cutting tree, move around a tree.

Video of the issue :
https://youtu.be/MTz5WrzHga8

**Comment by DjTylerD** [comment]
he waits for the drop sapling if he has not in his inventory or hut.
often he will fetch it on the tree cut before
I admit that there are none on the ground, too bad it blocks if stack in warehouse

**Comment by lebanni** [comment]
Actually, he has saplings in his inventory : 

https://imgur.com/HGfBIrm

**Comment by kkbearxo** [comment]
I'm having the same issue with the lumberjack just standing there searching for trees.
Mine is smack in the middle of a forest within colony limits. Mine doesn't even move.
The saplings are enabled in her block and she has an axe, saplings, and food.. everything she needs.
Mine has been like this for at least 10 updates, I've been waiting and hoping that one of these updates would just fix it but no luck yet.

**Comment by Raycoms** [comment]
Does she have all saplings enabled?

2018-03-02 15:51 GMT+00:00 kkbearxo <notifications@github.com>:

**Comment by kkbearxo** [comment]
Yes she has all saplings enabled.
I've tried disabling them, getting out of her lumbermill block, then enabling them again.
I've tried hiring and rehiring.
I've tried upgrading lumbermill

**Comment by Raycoms** [comment]
Should be fixed nwi as well
