### ISSUE TITLE
Miner doesn't make mineshafts

### ISSUE THREAD

**Issue by Vealikaso** [ldtteam/minecolonies#2201]
### Minecolonies version

Minecraft 1.12.2

### Expected behavior

- Miner mines mineshafts on selected level

### Actual behaviour

- Miner stil mines downwards

### Steps to reproduce the problem

1. Hire miner
2. Wait until firts mineable level pops up in second window
3. Select it

**Comment by Raycoms** [comment]
That's intended, the miner is supposed to go down until he can't anymore and then only mine sidewards.
This is this way to avoid several issues.
