### ISSUE TITLE
Builder doesn't like the new medieval oak style

### ISSUE THREAD

**Issue by copperwarrior** [ldtteam/minecolonies#2203]
### Minecolonies version

version 0.8.7484

### Expected behavior

- Builder upgrades his level 4 birch builder's hut to a level 5 medieval oak builder's hut

### Actual behaviour

- Builder freezes on the corner of the building, never places or removes a block

### Steps to reproduce the problem

1. Build up a builder to level 4 with the birch style
2. Upgrade the builder to level 5 with medieval oak style
3. ...
4. Profit

**Comment by nick-johnson** [comment]
Having a similar problem with any of the level 4 wooden herders. When a building requires more than one type of timber frame style in the same wood type, the builder "Required Resources" only shows a single type, and the builder is unable to resolve what it actually needs.
