### ISSUE TITLE
Concurrent Exception with  .getRecipes

### ISSUE THREAD

**Issue by Misunderstood-Wookiee** [ldtteam/minecolonies#2206]
### Version Info

- Minecolonies: `1.12.2-0.8.7494`
- Forge: `14.23.2.2611`

### Expected behavior
- I guess not crash??

### Actual behaviour
- Client Force Closed
https://pastebin.com/GUe31FJh

### Steps to reproduce the problem
I have no idea, one of the builders was building a fancy T-Intersect Path.

**Comment by marchermans** [comment]
@Raycoms We seriously need to make it so that all messages that come in are directed to there proper thread.

**Comment by Raycoms** [comment]
Aren't all messages yet?
I thought we had rewritten it so all do "message on server thread".

**Comment by Raycoms** [comment]
Ahh I remember, we'd have to schedule the message results so they get
inserted in the thread.

**Comment by Raycoms** [comment]
Should be fixed now.
