### ISSUE TITLE
[Enhancement] Configurable Raids

### ISSUE THREAD

**Issue by Misunderstood-Wookiee** [ldtteam/minecolonies#2208]
Allow Raids to be configured with stages via JSON or another language.

Reason:
It would be cool too make custom raids with modded mobs or add held items & armour to raiders. The original idea was for me to add a chance of a dragon attack using Ice and Fire Mod's dragon mobs. I could code this for myself as an addon though and have colony people run inside like they do at night time.

**Comment by Misunderstood-Wookiee** [comment]
Speaking of Mob tho, not all modded explosion are caught by colony protection, however, may be intentional.

**Comment by Raycoms** [comment]
If they're not, then you have to report it to that mod, since they're doing
something wrong and are not considering someone canceling the explosion.

2018-02-10 14:37 GMT+00:00 Misunderstood-Wookiee <notifications@github.com>:

**Comment by Misunderstood-Wookiee** [comment]
**I have had some time to flesh this concept out a bit and in order of most valuable, I list them below.**

- [ ] **Raider Group** - Holds the values Min-Max group size based on colony days passed & Entity Types. Easier to think of this as a stage which holds all possible entity data for the possible wave during that time period.

- [ ] **Raider Entity Type** - entity names with NBT data, used in the "Raider Group/Wave as a value or a string"
_e.g._ 
`"minecraft:husk", "minecolonies:barbarian", "iceandfire:firedragon_lvl3"`
or `"minecraft:skeleton:{Riding:{id:"EntityHorse",Type:4,Tame:1}}, "minecolonies:barbarian"`

- [ ] **Raider Main Hand & Offhand & Armor Worn** -  either as values or a string value & weighted chance, is assigned to any entity which can wear or hold items in the raid wave. 
_e.g._  
`"minecraft:iron_boots", "minecraft:iron_chest", "minecraft:iron_sword" 0.15` - (15% chance per raider spawn with these items equipped)

- [ ] **Summon Aid** - a weighted string to determine an entity to be possibly summoned to aid by the attacking raider group.  This could be a single entity or a group of entity's and has a chance value.

- [ ] **Random Even**t - This is a weighted value after X colony days have passed which might trigger something  e.g. Mini-boss or modded entity is summoned and announced to chat, bonus if there is a true/false value for if this entity spawns in the sky, useful for summoning periodic flying mobs.

- [ ] **Waves** - How many waves in the raid period such as two waves of Group A & B or three waves of Group A & C. (unsure on how plausible it would be to bother with this but having the chance for a second strike if you will and which Raider Group to use could get interesting.

- [ ] **Destruction Override** - `true/false` value assigned to the global configuration of Raids and toggles if a raid can cause world destruction (self-explanatory it just allows raiders to do block damage separate to that of the colony global config, this could be whitelist string or simple true or false value.

- [ ] **Raid Leader** - This entity is summoned in by each raid and has unique loot drop and gives buffs to fellow non-monster type entity's in the attack. They should have a unique skin or wear a cape.

**Comment by marchermans** [comment]
@Misunderstood-Wookiee We are currently working on this. We understand that you want to configure this relatively flexibly. And we understand why you would want it. But in its currently designed form we are not going this far.

We will give you the option to define how a raid looks like (what entities, how many, what they are wearing, and what their effect are). But that is what we are limiting it too.

@Tim020 Is currently looking into it. As such we have to wait for his result and see what he comes up with.

**Comment by Misunderstood-Wookiee** [comment]
@OrionDevelopment  
That's perfectly alright, anything is better than nothing I was just throwing some ideas into the mix, I understand there is an API for this mod? In which case it really should not be too much trouble even for me to get something going as an extension by importing the appropriate classes. The current scope looks to be sufficient but will wait for final word before going off on a coding extravaganza ;) 

For World mobs outside of mine colonies control, I use [InControl](https://minecraft.curseforge.com/projects/in-control), Maybe bits of that can help with coding this for you guys if you are looking for ways to get functions to work effectively.  I was also wondering if in a future update that Guards could possibly acquire custom loadout I understand how they work currently in saying the player chooses ranged or melee I am just not sure as I have never use a Melee Guard yet if they will use the weapons in their inventory or not I know they don't use the weapons I place in their inventory right now as I tried to throw a staff there once or a modded bow. It may be intentional but I don't think it would be overly time-consuming for a future update to also make use of any weapon in their inventory, could tie this functionality into higher tier guard towers or guard levels for RP aspect. 

Thanks for the responses thus far on these requests and tracked issues :) I was originally going to with factions but I saw this and my eyes lit up haha. Outstanding mod, really digging the ability to scan and build your own structures in a balanced way easily the best towny mod I have tried.

**Comment by Raycoms** [comment]
They use anything which is marked as weapon + tinker weapons, but they
don't use modded bows yet, mostly because that would make them op

**Comment by Misunderstood-Wookiee** [comment]
@Raycoms 
Oh okay :), in-regards to the bows I would think that this would be the server owners choice but not my mod so not much to say on that other than I don't have any modded OP bows in my pack I use VarriedCommodites and was hoping to get them to use the crossbow which I think is only a couple dmg points above a normal bow and crossbows require bolts, not arrows and don't have any bolts with any effects on them the crossbow is basically just a quick-fire not requiring a pullback. 

I suppose adding a global option to the config for allowing modded items as a global rule would give server hosts the choice but still default be balanced. I am not asking it be changed just a few cents on that. 

Was curious and only suggesting on the basis that they will use modded melee and armour which some mods have some crazy OP melee and armour which goes well above diamond stats and still accepts enchantments making it even more OP so having an OP guard bow or no bow is possible with that in mind.  I am fine with it how it is as I said not asking to change anything which is beyond a scope you guys don't wish to make possible.

**Comment by mkienenb** [comment]
> I was just throwing some ideas into the mix, I understand there is an API for this mod? In which case it really should not be too much trouble even for me to get something going as an extension by importing the appropriate classes. The current scope looks to be sufficient but will wait for final word before going off on a coding extravaganza ;)
[..]
> I am fine with it how it is as I said not asking to change anything which is beyond a scope you guys don't wish to make possible.

MineColonies accepts PRs.   :-)   If you are willing to do the work, and your code is maintainable and not at cross-purposes to what the project goals, that's the fastest way to get your ideas implemented.   You could check with @Tim020 and see if this is something he's started, or you could wait and improve upon what he provides if it doesn't go far enough.  It doesn't sound like it's being limited because we don't want to do it so much as no one has yet committed to doing everything you've requested..

**Comment by Raycoms** [comment]
Closed in favor of joint issue.
