### ISSUE TITLE
Crash when building Medieval Birch Townhall

### ISSUE THREAD

**Issue by lunadragnstar** [ldtteam/minecolonies#2210]
### Minecolonies version

minecolonies-universal-1.12.2-0.8.7437

### Expected behavior

- For the building to be built

### Actual behaviour

- The game crashed whilst rendering block entity
The game crashed whilst rendering block entity
Error: java.lang.IllegalArgumentException: Cannot set property PropertyEnum{name=half, clazz=class net.minecraft.block.BlockDoor$EnumDoorHalf, values=[upper, lower]} as it does not exist in BlockStateContainer{block=minecraft:bookshelf, properties=[]}

### Steps to reproduce the problem

1. Creative
2. Build Medieval Birch Townhall
3. Upgrade to lvl 3 or 4

**Comment by copperwarrior** [comment]
Can you provide a crash report?

**Comment by lunadragnstar** [comment]
The message is all I have, it crashed and I would have to start all over again to get it to do it, I'll have to do it later.

**Comment by copperwarrior** [comment]
Was there not a report generated in the crash-reports folder? Can't really help much without it.

**Comment by lunadragnstar** [comment]
[crash-2018-02-10_11.35.17-server.txt](https://github.com/Minecolonies/minecolonies/files/1714030/crash-2018-02-10_11.35.17-server.txt)
[crash-2018-02-10_15.20.39-client.txt](https://github.com/Minecolonies/minecolonies/files/1714031/crash-2018-02-10_15.20.39-client.txt)
[crash-2018-02-10_22.22.36-client.txt](https://github.com/Minecolonies/minecolonies/files/1714032/crash-2018-02-10_22.22.36-client.txt)
[crash-2018-02-10_11.35.17-client.txt](https://github.com/Minecolonies/minecolonies/files/1714033/crash-2018-02-10_11.35.17-client.txt)

**Comment by lunadragnstar** [comment]
Those are the crash reports from tonight, after trying several times. The last time was a Medieval Oak, but when I went back in, I didn't have to start over.

**Comment by lunadragnstar** [comment]
And the last time, it just froze, I had to end the task.

**Comment by lunadragnstar** [comment]
[crash-2018-02-11_14.14.15-client.txt](https://github.com/Minecolonies/minecolonies/files/1715035/crash-2018-02-11_14.14.15-client.txt)
[crash-2018-02-11_19.35.08-client.txt](https://github.com/Minecolonies/minecolonies/files/1715036/crash-2018-02-11_19.35.08-client.txt)
[crash-2018-02-11_19.42.52-client.txt](https://github.com/Minecolonies/minecolonies/files/1715037/crash-2018-02-11_19.42.52-client.txt)
[crash-2018-02-11_00.22.16-client.txt](https://github.com/Minecolonies/minecolonies/files/1715038/crash-2018-02-11_00.22.16-client.txt)
[crash-2018-02-11_02.54.06-client.txt](https://github.com/Minecolonies/minecolonies/files/1715039/crash-2018-02-11_02.54.06-client.txt)
[crash-2018-02-11_02.54.07-server.txt](https://github.com/Minecolonies/minecolonies/files/1715040/crash-2018-02-11_02.54.07-server.txt)


These are all using Medieval Oak

**Comment by Raycoms** [comment]
@lunadragnstar all this is the townhall?

**Comment by lunadragnstar** [comment]
No, it varies, I've had it happen with the houses, sawmill, and mine. A lot of time I could get back in and get it to work.

**Comment by Raycoms** [comment]
Should be fixed in the newest alpha
