### ISSUE TITLE
Fix citizens dying after getting up

### ISSUE THREAD

**Issue by Raycoms** [ldtteam/minecolonies#2212]
It seems like citizens still die when they get up.

My idea: Let them move around kind of "noclip" for 3 seconds (there should be a way for this) and protect them from damage during that.

**Comment by MineShadow7** [comment]
Shouldn't they disable their AI when the suffocate in a block? (default minecraft behavior)

**Comment by MineShadow7** [comment]
And I don't seem to have any problems with that on the latest version...

**Comment by DjTylerD** [comment]
minecolonies-universal-1.12.2-0.8.7508
I do not have a death problem in townhall, but a problem of reconnection (solo games)
if I disconnect at night, the citizens are standing without tic of damage (as in the picture)
![2018-02-11_13 24 32](https://user-images.githubusercontent.com/35812264/36073417-68547c52-0f30-11e8-8f2e-19b2bf5b41df.png)

2 solution to unlock them: break the block or go to the hut "recall worker"
on a server 24/24, its should not be a problem

**Comment by marchermans** [comment]
I might have a fix for the single player stuff
But @Raycoms If they are dying somebody needs to tell me. Building, Orientation of said building, Level of said building, which bed etc.

**Comment by marchermans** [comment]
@MineShadow7 Yes that is what is happening. Their AI actually teleports out of a block. But since their head is in one, they suffocate.

**Comment by grugsy** [comment]
can confirm both the death as well as stuck in block bug. any bed in any building with any stair/block 1 block above it will do this. it's/was? a [vanilla bug](https://bugs.mojang.com/browse/MC-99909?jql=project%20in%20(MC%2C%20MCPE%2C%20MCCE)%20and%20(resolution%20is%20empty%20or%20resolution%20in%20(2%2C%206))%20and%20(summary%20~%20"Bed")%20order%20by%20resolution%20desc).

**Comment by marchermans** [comment]
@grugsy Version number please. We confirmed with the original issuer (not raycoms) that he was behind update schedule. This is most definetly fixed in the newest version.

**Comment by grugsy** [comment]
apologies. the issue was on every alpha for about the last week (74**). I have updated to the latest version available on curse client (7508) but have not spent much time in it. I got distracted by the new textures I needed to make for the timber frames. lol

**Comment by Raycoms** [comment]
Please reopen if still an issue
