### ISSUE TITLE
Citizens lives in townhall

### ISSUE THREAD

**Issue by MineShadow7** [ldtteam/minecolonies#2216]
### Minecolonies version

version minecolonies-universal-1.12.2-0.8.7508

### Expected behavior

- They do not live in townhall.

### Actual behaviour

- Citizens live in townhall. It's looks like they are homeless or something. That actually increases colony population like the normal citizen hut would do.

### Steps to reproduce the problem

1. Build townhall.
2. Upgrade it to more levels.
3. Have some other huts to see the difference.
4. At nights some citizens will go sleeping to townhall because it's their Citizen hut.
5. Actual profit because there is more people in my colony lol

**Comment by Raycoms** [comment]
Yeah that's on purpose. They even have beds there, why shouldn't they live there.

**Comment by jelaw21** [comment]
I would like to re-open this. I have a citizen living in town hall, who I want to re-assign to a closer citizens hut, but there is no option in the town hall for re-assignment like in the citizens hut.

**Comment by Raycoms** [comment]
Yeah, we are currently reworking our GUI system. As soon as this is ready
we will add a complete reassignment GUI which allows you to reassign all
citizens between houses

Am Mi., 19. Sep. 2018 um 22:07 Uhr schrieb Joshua Law <
notifications@github.com>:

**Comment by NachtRaveVL** [comment]
This is actually one of my major complaints against this mod. Once you have a citizen living in townhall, their house modifier goes red, reducing their happiness level.

I have more than enough houses, but cannot reassign them to an actual house.
