### ISSUE TITLE
[1.12.2] Lumberjack cuts down structures with logs in them.

### ISSUE THREAD

**Issue by Misunderstood-Wookiee** [ldtteam/minecolonies#2217]
### Version Info

Minecolonies: 1.12.2 - 08.7508
Forge:  14.23.2.2611

### Expected behavior

- Lumberjack ignores structures with huts/ structures in general.

### Actual behaviour

- Lumberjack chops log blocks of town structures near the sawmill.

### Steps to reproduce the problem

Unsure really, I just was wondering why one of the town structures was repaired yet broken, and also whilst being qued for repair the lumberjack jack in the town ran up to the structure and started cutting down all the logs and planting saplings as it usually would for trees, the structure was probably around 30 or fewer blocks away from the sawmill and it was the closest thing near the sawmill with logs in it.

May have been a glitch it has not done this again yet since the structure was repaired and I planted some extra trees for the little guy to go too instead of the structures.

**Comment by Raycoms** [comment]
We could detect just if a block is too close to a building and not cut it.

**Comment by Misunderstood-Wookiee** [comment]
@Raycoms Should work, may wish to add the same check for leaves as I noticed it only happened to the building which had some leaf blocks placed around it for aesthetical purposes which may have been the trigger and not the logs themselves. 

![2018-02-12_12 42 27](https://user-images.githubusercontent.com/22002023/36081388-4ba85ab6-0ff2-11e8-88ee-71107b8a466f.png)

This is the building from the OP, it's a Medieval Oak Deliveryman structure, too the right you can see the upgraded lumberjack structure. The building from the OP used to have leaf blocks around one side of it however they are removed and this pic is post lumberjack issue.
