### ISSUE TITLE
Bug upgrading building

### ISSUE THREAD

**Issue by lebanni** [ldtteam/minecolonies#2218]
### Minecolonies version

minecolonies-universal-1.12.2-0.8.7508.jar

When upgrading warehouse medieval spruce to lvl 2, the lvl 1 building is sliced and apparently replace with a schematic that doesn't fit.

https://imgur.com/y8muMIJ
https://imgur.com/VCva1DS
https://imgur.com/fqYb1zj

**Comment by Raycoms** [comment]
@lebanni the newest build replaced the warehouse of the medieval versions, this will be fixed from now on.
