### ISSUE TITLE
Minecolonies Crashes..

### ISSUE THREAD

**Issue by JustVito** [ldtteam/minecolonies#2220]
### Minecolonies Version

Version 1.12.2

### The Problem

My game just crashes whenever i place down the town hall..

This is the crash report.. \/ \/ \/

[crash-2018-02-13_17.12.51-client.txt](https://github.com/Minecolonies/minecolonies/files/1720878/crash-2018-02-13_17.12.51-client.txt)

**Comment by Justen-N** [comment]
This should have been fixed in the latest alpha. If you are not using the
alpha, please upgrade or wait until the fix comes to the beta or release.
Also, please provide your Minecolonies version, not the Minecraft version.

**Comment by Raycoms** [comment]
Yeah please upgrade
