### ISSUE TITLE
[proposition] Some storage and hapiness info

### ISSUE THREAD

**Issue by Boyownik** [ldtteam/minecolonies#2222]
I wish it could be some info in warehouse which tells about amount of items inside and also some more info about happiness in town hall, like it's getting low because of low security level or something. That info especially in warehouse would be very useful, because i fill warehouse with building materials and carefully sort it to have easy sight of their amount but deliveryman is a messy boi and shuffling all items in racks :/

Aaaand still clipboard not showing requests properly or even showing nothing, when ranchers or builder wants something.

**Comment by Misunderstood-Wookiee** [comment]
I second this, I have to go around manually using the inventory sort function from another mod in the builders inventory and hut chest just to make space a lot of the time and prevent them bitching about no room to move items between the hut chest and the worker and sometimes it is as simple as just merging two stacks into one stack making room. 

This could be automated better, I am not sure if such a function exists where workers can use racks manually placed into the huts if that was possible then builders could offload into a rack that is in the workers hut and the delivery dude could go about gathering as usual but at least there would a bit of extra storage for the workers to avoid small overflow.

**Comment by Raycoms** [comment]
Closed in favor of: https://github.com/Minecolonies/minecolonies/issues/1990
