### ISSUE TITLE
Build tool GUI crashes on Forge version 2615

### ISSUE THREAD

**Issue by copperwarrior** [ldtteam/minecolonies#2224]
### Minecolonies version

version 0.8.7508

### Expected behavior

- The build tool gui works

### Actual behaviour

- It doesn't, causing a crash when using both the build tool, supply ship and supply camp tools.

### Steps to reproduce the problem

1. Download forge latest, version 2615
2. Realize the latest forge version has a changelog of "Clean up some GUI code and change magic numbers to GL constants"
3. Look at the log here: https://pastebin.com/0FuvW9r7 and the crash report here: https://pastebin.com/qHiATG7T
4. Find that the number changes in the latest forge version causes the array in the build tool GUI to attempt to subtract a number from a nil value

**Comment by Raycoms** [comment]
Can't reproduce this. Weirldy

**Comment by copperwarrior** [comment]
Didn't test it myself, so can't say. I can try and reproduce it when I get home.
