### ISSUE TITLE
[1.12.2] EntityCitizen (AiSleep) Bug

### ISSUE THREAD

**Issue by Misunderstood-Wookiee** [ldtteam/minecolonies#2228]
### Version Info
Forge: `14.23.2.2611`
Minecolonies: `1.12.2-0.8.7551`

### Expected behaviour
The client does not force close.

### Actual behaviour
[Crashes](https://gist.github.com/Misunderstood-Wookiee/fe3eb4ca431355dd54286d0b851f88cb)
`java.lang.IllegalArgumentException: Cannot get property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}`

### Steps to reproduce the problem
Unsure, I believe this is caused by the simple fact that I broke the bed the citizen was sleeping in at night. Then come daylight `EntityAITasks` didn't know how to handle the missing `BlockStateContainer`  I think this bug is quite an easy fix just need to catch the exception instead of expecting the property to exist and going unhandled when it is not present.

**Comment by Raycoms** [comment]
Please report if it hppens again.
