### ISSUE TITLE
Extremely slow

### ISSUE THREAD

**Issue by Senderoth** [ldtteam/minecolonies#2229]
### Minecolonies version

version 1.12.2-0.8.7508

### Expected behavior

- Build things.

### Actual behaviour

- Takes literal 2 hours to build just the town hall. First off, they only accept wood or gold tools. Second off, their speed at breaking blocks is as if they're underwater. For some reason, they recognized one other pickaxe, from my corruption mod, which has a OP pickaxe stronger than diamond. But even using that, they were mining at the speed of maybe a stone pickaxe on a player. BUT EVEN THEN, they requested a stone pick specifically, for some odd reason, and couldn't register that I gave it to them, and just stopped working.

All in all, could have built 2 or 3 town halls in the time it took this builder to hallow out the basement for 1. It's horribly inefficient and not even remotely afk-able. ( At the very least, I should be able to go do other things while waiting for stuff to be built. ) I don't know if this is an issue, or how the mod is built. Either way, needs fixing.

P.S. Notifications don't show up in chat, I have to go find the builder at their hut.

**Comment by Raycoms** [comment]
Hey there, first build the builder hut up to level 1 and then build the townhall, he will then also accept better tools. The builder gets faster during the time. But on hut level 0 he stays weak, better upgrade him to get him faster.
