### ISSUE TITLE
Minecolonies, Description: Exception ticking world

### ISSUE THREAD

**Issue by VampBloodknight** [ldtteam/minecolonies#2230]
xxx Minecolonies version

version 0.8.6471 or curse X.X.XX
Server is 1.12.1 byt twitch is loading either 6471 or 4075 
### Expected behavior

- Players join my server and build their cities

### Actual behaviour

- Server crashes either as soon as some one joins it, or with in a couple minutes. Has been happening for last 2 days, no changes to any mods i run for last 4 weeks. 

### Steps to reproduce the problem

1. tried a server back up from 3 days to a week ago. same error crashes in seconds.
2. tried removing all mods and just running 6471 on its own, still crashes.
3. Tried going back to 4075 and killed Minecolonies, chests for every building no longer work and all citizens are gone and no more spawn. ( able to log in and make changes. reading the crash report, might be scarecrowentity so thought to destroy those but can not in a working minecolonies as it crashes.})
 restored from back up and replaced all mods... no go...
restored from back up and deleted all and loaded fresh 6471... still crashes.
4. Profit

Mods i run: All for server 1.12.1( though 6471 shows 1.12.2) no other options in twitch
Carbonado 1.4.2(stock)
Customized Dungeon Loot 1.0.1( increased drop rate)
Custom Mob spawner 3.11.3 (stock)
DrZharks Mp Creatures 12.0.3 (stock)
Fancy Battleaxes 1.1.4 (stock)
JourneyMap 5.5.2 9Stock)
Just Enough Items 4.7.8.95 (stock) 
Just Enough Resources 0.8.4.24 (stock)
Mantle 1.3.1.21 (stock)
Minecolonies 0.8.6471(stock)
Runic Blink 1.6.0 (stock)
Tinkers Construct 7.4.34(stock)

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 17/02/18 9:09 PM
Description: Exception ticking world

java.lang.NullPointerException: Exception ticking world
	at com.minecolonies.coremod.tileentities.ScarecrowTileEntity.func_189518_D_(ScarecrowTileEntity.java:452)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187273_a(PlayerChunkMapEntry.java:287)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187280_d(PlayerChunkMapEntry.java:249)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:115)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:226)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:754)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.minecolonies.coremod.tileentities.ScarecrowTileEntity.func_189518_D_(ScarecrowTileEntity.java:452)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187273_a(PlayerChunkMapEntry.java:287)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187280_d(PlayerChunkMapEntry.java:249)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:115)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:226)

-- Affected level --
Details:
	Level name: Server MineColonies GOOD
	All players: 1 total; [EntityPlayerMP['VampBloodknight'/388, l='Server MineColonies GOOD', x=24.80, y=64.00, z=-10.45]]
	Chunk stats: ServerChunkCache: 943 Drop: 0
	Level seed: -2607141240769591740
	Level generator: ID 04 - customized, ver 0. Features enabled: true
	Level generator options: {"coordinateScale":684.412,"heightScale":684.412,"lowerLimitScale":512.0,"upperLimitScale":512.0,"depthNoiseScaleX":200.0,"depthNoiseScaleZ":200.0,"depthNoiseScaleExponent":0.5,"mainNoiseScaleX":80.0,"mainNoiseScaleY":160.0,"mainNoiseScaleZ":80.0,"baseSize":8.5,"stretchY":12.0,"biomeDepthWeight":1.0,"biomeDepthOffset":0.0,"biomeScaleWeight":1.0,"biomeScaleOffset":0.0,"seaLevel":63,"useCaves":true,"useDungeons":true,"dungeonChance":46,"useStrongholds":true,"useVillages":true,"useMineShafts":true,"useTemples":true,"useMonuments":true,"useMansions":true,"useRavines":false,"useWaterLakes":true,"waterLakeChance":4,"useLavaLakes":true,"lavaLakeChance":80,"useLavaOceans":false,"fixedBiome":-1,"biomeSize":2,"riverSize":3,"dirtSize":33,"dirtCount":10,"dirtMinHeight":0,"dirtMaxHeight":256,"gravelSize":33,"gravelCount":8,"gravelMinHeight":0,"gravelMaxHeight":256,"graniteSize":33,"graniteCount":10,"graniteMinHeight":0,"graniteMaxHeight":80,"dioriteSize":33,"dioriteCount":10,"dioriteMinHeight":0,"dioriteMaxHeight":80,"andesiteSize":33,"andesiteCount":10,"andesiteMinHeight":0,"andesiteMaxHeight":80,"coalSize":17,"coalCount":20,"coalMinHeight":0,"coalMaxHeight":128,"ironSize":12,"ironCount":20,"ironMinHeight":0,"ironMaxHeight":64,"goldSize":12,"goldCount":5,"goldMinHeight":0,"goldMaxHeight":32,"redstoneSize":8,"redstoneCount":8,"redstoneMinHeight":0,"redstoneMaxHeight":16,"diamondSize":11,"diamondCount":5,"diamondMinHeight":0,"diamondMaxHeight":16,"lapisSize":7,"lapisCount":2,"lapisCenterHeight":16,"lapisSpread":16}
	Level spawn location: World: (19,64,189), Chunk: (at 3,4,13 in 1,11; contains blocks 16,0,176 to 31,255,191), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 215309485 game time, 217950436 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 27556 (now: false), thunder time: 15246 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:754)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.1
	Operating System: Windows Server 2012 R2 (amd64) version 6.3
	Java Version: 1.8.0_60, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2274698376 bytes (2169 MB) / 3113877504 bytes (2969 MB) up to 3113877504 bytes (2969 MB)
	JVM Flags: 3 total; -XX:MaxPermSize=256M -Xmx3072M -Xms3072M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 88
	FML: MCP 9.41 Powered by Forge 14.22.1.2478 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID           | Version         | Source                                     | Signature                                |
	|:--------- |:------------ |:--------------- |:------------------------------------------ |:---------------------------------------- |
	| UCHIJAAAA | minecraft    | 1.12.1          | minecraft.jar                              | None                                     |
	| UCHIJAAAA | mcp          | 9.19            | minecraft.jar                              | None                                     |
	| UCHIJAAAA | FML          | 8.0.99.99       | forge-1.12.1-14.22.1.2478-universal.jar    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge        | 14.22.1.2478    | forge-1.12.1-14.22.1.2478-universal.jar    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | minecolonies | 1.12.2-0.8.6471 | minecolonies-universal-1.12.2-0.8.6471.jar | None                                     |

	Loaded coremods (and transformers): 
	Profiler Position: N/A (disabled)
	Player Count: 1 / 15; [EntityPlayerMP['VampBloodknight'/388, l='Server MineColonies GOOD', x=24.80, y=64.00, z=-10.45]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by Raycoms** [comment]
Even when you run it with 6471

**Comment by VampBloodknight** [comment]
Wrote the above report and forgot about it as my servers provider started assisting me in finding the problem.

After 3 hours of his excellent help and testing, 

We found the problem.

Old fields (scarecrows) somehow bugged and when someone went near them the game crashed,

He assisted me in moving my spawn and taking all gear off me and i ran back to the towns in game and removed and destroyed all scarecrows and fired the farmers.
Restored my profile and gear and now is working fine.
Have planted 3 new fields with new farmer and is working happily again.

So for now this is a info error, so maybe an idea to look at the fields that were placed on previous versions to see if there is a conflict with newer versions. 

Thanks and loving the mod.

Leaving open so you see it and close when ever you like :)
Stefan

**Comment by VampBloodknight** [comment]
Yes even restoring to 6471 everything was broken, buildings were still there but was a ghost town. 
I planted the fields months ago, and only just upgraded from 3rd level to 5th this week.
May have something to do with it.

**Comment by Raycoms** [comment]
Yeah, the current release is quite outdated at the moment.

2018-02-17 11:21 GMT+00:00 VampBloodknight <notifications@github.com>:

**Comment by VampBloodknight** [comment]
Will there be support for 1.12.1 ongoing or is it all 1.12.2 now? 
Wonder if the server will survive a version upgrade,, forge, minecraft 1.12.2 and mods... scary

**Comment by Raycoms** [comment]
Actually the versions should work all on 1.12.1 as well

2018-02-17 11:37 GMT+00:00 VampBloodknight <notifications@github.com>:
