### ISSUE TITLE
Villagers disappearing. 

### ISSUE THREAD

**Issue by alcheya** [ldtteam/minecolonies#2233]
### Minecolonies version

version 0.8.7551

### Expected behavior

- Villagers always visible

### Actual behaviour

- Villagers are invisible

### Steps to reproduce the problem

1. Go into Twilight Forest (or Aroma Mining Dimension) portal
2. Come out of Twilight Forest (or other Mod dimension) portal.
3. Most of the Colony is invisible.
4. Accidentally kill a citizen because you're shooting shurikens randomly and you don't see the invisible lady you've had since the beginning losing a level 27+ deliverywoman resulting in 1 colony happiness from 10 and a dead deliverywoman.  :(

**Comment by copperwarrior** [comment]
You might be able to fix this by recalling all citizens in the town hall

**Comment by alcheya** [comment]
I go into the nether portal and come back out. It works again then and that's what I've been doing, but the one time I forgot I nuked my deliverywoman.

**Comment by Lordbaane** [comment]
Sometimes when I hire a villager, I recall them, and they are invisible for the short term but reappear shortly thereafter. Logging out and in fixes it. Recalling them works too. Not sure what can be done (not a programmer), but hopefully something can be.

**Comment by Raycoms** [comment]
Should be fixed in the newest version. If it happens please recall them in the townhall
