### ISSUE TITLE
[Enhancement] Rally Troops

### ISSUE THREAD

**Issue by MattBeard** [ldtteam/minecolonies#2234]
It would be great to be able to craft an item that could be used a little like the green-wand used for selecting the location to be guarded (or patrol points) for guards. But, this wand would cause all guards to rally to the selected point and look for enemies in that area. 

The guards would return to their previous action after a while (perhaps 3 minutes).

It would be nice if the wand was used up each time you rallied the troops, so you would have to take a little care with using it. Personally I would make it NOT stackable, and made from something not hugely abundant - perhaps like the building tool, but stick+stick+red-wool. This would give a wand that looks like the green wand, but in red.

An enhancement on this (but not required initially) would be to have a checkbox or switch in each guard chest that says "answers rallies" and defaults to on. This means that you could leave some guards patrolling or guarding even during a rally.

**Comment by Raycoms** [comment]
Closed in favor of joint issue.
