### ISSUE TITLE
Crashes when town hall is placed and unable to open world

### ISSUE THREAD

**Issue by mackenziemay** [ldtteam/minecolonies#2238]
Using newest version of Minecraft 1.12.2
using the newest version of minecolonies

once town hall is placed game crashes then, I am unable to open the world

I was really looking forward to using this mod and if there is a fix. i would love to use this mod.

**Comment by Raycoms** [comment]
That's the one you're using? https://minecraft.curseforge.com/projects/minecolonies/files/2532902

**Comment by Justen-N** [comment]
Ray is asking because the alpha build, and I believe the beta should
contain a fix for this.

**Comment by Raycoms** [comment]
And I just pushed the latest betas to release as well to avoid this issue from happening.

**Comment by mackenziemay** [comment]
I'm not sure if its the beta, I just said it was for version 1.12.2

**Comment by Justen-N** [comment]
We need the number from the file you downloaded, not your minecraft
version. Each release of the mod can have different fixes, and before we
work on your problem, we need to know exactly what version of the mod you
have.

**Comment by mackenziemay** [comment]
this is what is on it says
minecolonies-universal-1.12.2-0.8.7551.jar

**Comment by Justen-N** [comment]
Yep, this should be fixed in the newest release, went live an hour ago! please report back after you download it, even if it fixes your error.

**Comment by mackenziemay** [comment]
where do I find the newest download?

**Comment by Raycoms** [comment]
https://minecraft.curseforge.com/projects/minecolonies/files/2532902

**Comment by Justen-N** [comment]
The curseforge site has one lablled r, as well as the link Ray posted  on
this issue.

**Comment by mackenziemay** [comment]
thank you

**Comment by Justen-N** [comment]
Have Fun!
