### ISSUE TITLE
Just a Thought...

### ISSUE THREAD

**Issue by Lordbaane** [ldtteam/minecolonies#2239]
So, I saw several recommendations for improvements, and I know that some of them are already in the works, especially with your creating the ability for villagers to manufacture items by being taught.
So I have a thought that you add a _Blacksmith/armorer_, who can create arms and equipment on demand. 
The other thought was adding an _Apothecary_ who can create basic potions that can help the colony.
Future thoughts were maybe a laborer who can build simple things like walls and roads which could give the villagers bonuses on movement.
A last thought was to somehow allow villagers to gain improvements as they level. Increased speed for deliverymen, more damage for guards.
As I said, just a thought.

**Comment by Justen-N** [comment]
Actually, a lot of what you've  mentioned either already exists or is
planned. The only one I don't  think we have is a specific transport
worker. Maybe flesh that idea out and submit it as it's own issue?
Blacksmith and apothecary have their own issues submitted, and the level of
each worker does affect how well they work.

**Comment by Lordbaane** [comment]
Yah, I know the villagers get better with levels, I was thinking more of equipment enhancements. 
I was just looking at medieval times and saw that a general laborer was on the list. I also figured the other jobs were prolly in the works already, but it would be nice to have a guy who could build a simple wall with fences at first, then be upgraded to proper walls, maybe building a trench on the outside of the wall filled with water. You may even add the option of simple traps like dispenser with arrows made by the blacksmith.

**Comment by Lordbaane** [comment]
Though I'm not sure how to add labels, I was looking for that when you replied.

**Comment by Lordbaane** [comment]
If there was a way to integrate with some of the other mods that added animals, plants and ores would be cool, but I'd think that would be a separate mod.
