### ISSUE TITLE
Lumberjack chopped down the warehouse

### ISSUE THREAD

**Issue by alcheya** [ldtteam/minecolonies#2240]
### Minecolonies version

0.8.7551

### Expected behavior

- Lumberjack knows a building from a tree

### Actual behaviour

- I don't think there was a tree too close to the warehouse, but the lumberjack slowly navigated toward it.  Went hunting, colony chunks were loaded.. came back to all the oak wood (not planks) from the warehouse chopped down.
https://i.imgur.com/IkS4FsK.png
https://i.imgur.com/DtFZi1G.png (inside)

### Steps to reproduce the problem

1. Grow a tree near the warehouse
2. Leave the lumberjack near there
3. Give it some time
4. Lumberjack decides the warehouse is a tree and chops it down as your builder desperately attempts to repair it (When told to repair because I thought it was a bug, until I realized the lumberjack was chopping it down on the other side.)

**Comment by Raycoms** [comment]
Should be fixed in the newest alpha
