### ISSUE TITLE
[Enchancement] General Laborer

### ISSUE THREAD

**Issue by Lordbaane** [ldtteam/minecolonies#2241]
Yesterday one of the thoughts I had was adding a General Laborer job for the mod.
The guy would start with a simple fenced hut where he'd wait for you to show up and show him a task. The hut can be expanded from level 2-5 with beds.
Possible tasks could be:
-Leveling an area, you use the builders wand to indicate four points for them to flatten
-Digging a trench for defense
-Digging a pit for a trap
-Building a wall out of wood at first, fences, etc.
-Can be ordered to plant trees to start a new forest, or to clear and area
When building a wall, you can have them grab the materials from the hut or go and get them directly from the stone pit (future) or logger and have a basic template for them to make their own fences/walls.
Using the wand, you can select a prebuilt 10 spaced wall section, each one that is unlocked as the building levels up. Another small pieces could be corners, gate, etc.
Another option is to have them build basic items for themselves, such as torches, fences, polished stones, bricks. 
Maybe you can even have them dig out clay for bricks.
In some sense, you can take some basic programming from the Builder, and that they just do the odd jobs needed around the colony.
There can be other things they can do, as it is more heavily Player directed.

**Comment by Raycoms** [comment]
YOu can do all that with the builder tbh.
