### ISSUE TITLE
Rope fences

### ISSUE THREAD

**Issue by KienanBlue** [ldtteam/minecolonies#2242]
![2018-02-20_14 13 49](https://user-images.githubusercontent.com/24659505/36431629-59894764-1658-11e8-8121-e2bffe01a698.png)
[rope fence assets.zip](https://github.com/Minecolonies/minecolonies/files/1740573/rope.fence.assets.zip)
@Raycoms @OrionDevelopment

**Comment by Asherslab** [comment]
Sooo, can i close this now?
