### ISSUE TITLE
Barracks put towers in wrong order

### ISSUE THREAD

**Issue by carlansor** [ldtteam/minecolonies#2243]
### Minecolonies version

version 1.12.2-0.8.7608

### Expected behavior

- Barracks with medieval style put towers in a X shape when upgrading it (viewing from above, first left top, then bottom right, then top right and last bottom left)

### Actual behaviour

- Barracks with medieval style put towers in different order (first top left then bottom left and so on)

### Steps to reproduce the problem

1. Make the builder build Medieval Barracks
2. Upgrade it to 2nd level
3. Watch until is finished
4. Profit

Should be like this:
![2018-02-20_20 24 21](https://user-images.githubusercontent.com/5648523/36458687-854ad056-1686-11e8-8354-ecba714466c0.png)
But its like this:
![2018-02-20_20 24 42](https://user-images.githubusercontent.com/5648523/36458689-87295104-1686-11e8-821b-067e26ce8e68.png)

**Comment by Raycoms** [comment]
duplicated issue.
