### ISSUE TITLE
[FEATURE REQUEST] Let the first SupplyCamp built with Building tool

### ISSUE THREAD

**Issue by hron84** [ldtteam/minecolonies#2244]
### Minecolonies version

version 1.12.2-0.8.7582

### Expected behavior

- For more precise placement, I want use Building tool for place my SupplyyCamp with the more advanced guide than the item itself has (e.g. the tool remembers the last configuration (position/facing) of the schematic, while if you try to place the item it automatically resets.

### Actual behaviour

- I can select the placement with the tool, but when I try to accept the schematic, nothing happens.

### Steps to reproduce the problem

1. Craft a SupplyCamp and a Building tool
2. Try to place SupplyCamp with Building Tool
3. ...
4. Profit

Both 1.10 and 1.12 versions affected.

**Comment by Raycoms** [comment]
You don't need the build tool, the supplycamp already opens the GUI now.

**Comment by hron84** [comment]
@Raycoms maybe I did not described correctly my issue.

Supply Camp item opens the GUI, but there is a little difference, how it works. If you place a building with a building tool, you can exit the GUI, check the placement (Supply camp is a little bit big structure with strict requirements, so I usually want to double-check it) and return to the GUI to confirm the building. If you try to place  a Supply Camp with the item itself, every time you right click with the Supply Camp item, it resets the placement, so if I want to place it, I do right click, the "shadow" of the future structure appears, I exit the GUI, check the placement, and return to the GUI, but the placement resets if I do not right click on exactly same block as I clicked before.

Sometimes the way this works is OK, but sometimes I would like to use the building tool functionality, especially if I have to clear/build the place where I want to drop down the Supply camp as I prefer to not get "this structure requires XxY clear area" message on the chat. I am not that expert builder who can place the camp at first sight.
