### ISSUE TITLE
Miner reporting wrong ore at the location that can't be mined.

### ISSUE THREAD

**Issue by Aynjul** [ldtteam/minecolonies#2246]
### Minecolonies version

Minecolonies 1.12.2

### Expected behavior
Report correct ore that is at the location of the coordinates

### Actual behaviour
On several occasions the miner reports an ore that can't be mined at certain coordinates. What he is listing isn't the ore at that location but a different ore that can not be mined. This was only a problem because I was trying to tell a player what the ore looked like so she could mine it so the miner could carry on but she couldn't find it. I went to take a look and even though it was reporting galena ore it was dilithium. I did find galena ore 2 levels down on the other side though. It has been reporting the right ore about 50% of the time in my tests.

### Steps to reproduce the problem

1. Put a few different ores that can't be mined at different locations 
2. Cover the ore back up
3. Check ore reported versus the one that is there.

**Comment by Too-DAMN-Much** [comment]
yeah, been having this same problem, they report dilithium, but it was actually apatite i believe.

**Comment by Nightenom** [comment]
@Raycoms the miner doesn't skip ores which he can't mine?
