### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by lebanni** [ldtteam/minecolonies#2247]
### Minecolonies version

minecolonies-universal-1.12.2-0.8.7608.jar
forge-1.12.2-14.23.2.2618-universal.jar

[crash-2018-02-21_11.36.54-server.txt](https://github.com/Minecolonies/minecolonies/files/1743665/crash-2018-02-21_11.36.54-server.txt)

Another one, first lines changed quite a bit.
[crash-2018-02-23_12.14.56-server.txt](https://github.com/Minecolonies/minecolonies/files/1751433/crash-2018-02-23_12.14.56-server.txt)

minecolonies-universal-1.12.2-0.8.7688.jar, still happening
[crash-2018-03-03_16.36.14-server.txt](https://github.com/Minecolonies/minecolonies/files/1777607/crash-2018-03-03_16.36.14-server.txt)

**Comment by Raycoms** [comment]
Should be fixed
