### ISSUE TITLE
1.12.2 you need to be close to your town hall

### ISSUE THREAD

**Issue by Faenum** [ldtteam/minecolonies#2249]
### Minecolonies version

version 0.8.7608

### Expected behavior

To be able to build a builders hut right next to the town hall

### Actual behaviour

You need to be closer to your town hall message, i cant build a town hall without a builder, but i cant build a builder because of this.

### Steps to reproduce the issue

Place town hall, try to place builders hut

**Comment by Raycoms** [comment]
Working on that right now.
Can you send us your log in a gist?

2018-02-21 16:36 GMT+00:00 Faenum <notifications@github.com>:

**Comment by Faenum** [comment]
I'm not familiar with how to send it as a gist, never done it before.

**Comment by Raycoms** [comment]
Just copy it in here: https://gist.github.com/

**Comment by Faenum** [comment]
here you go
https://gist.github.com/Faenum/4826a1e9902b7091e4ab9f37591b04f7

**Comment by Raycoms** [comment]
That doesn't help me a lot, it only has the startup data. Do you have
anything else?
you should be getting this here in the log:
chunk has colonies: [0] if no colony and chunk has colonies: [1] if colony


2018-02-21 17:22 GMT+00:00 Faenum <notifications@github.com>:

**Comment by Faenum** [comment]
ive found this if its helpful#
[17:43:22] [Server thread/INFO]: chunk has colonies: []
[17:43:33] [Server thread/INFO]: chunk has colonies: []
[17:43:35] [Server thread/INFO]: chunk has colonies: []
[17:44:05] [Server thread/INFO]: chunk has colonies: []
[17:44:08] [Server thread/INFO]: chunk has colonies: []
[17:44:13] [Server thread/INFO]: chunk has colonies: []
[17:44:14] [Server thread/INFO]: chunk has colonies: []
[17:44:18] [Server thread/INFO]: chunk has colonies: []
[17:44:18] [Server thread/INFO]: chunk has colonies: []

**Comment by DjTylerD** [comment]
hello Faenum was faster than me, the time to retest on a new solo map.
all huts can be built on the chunk of the block townhall.
i try to change the new townHallPaddingChunk configuration, but it changes nothing.
return to minecolonies-universal-1.12.2-0.8.7594 the bug disappeared

**Minecolonies version:**
minecolonies-universal-1.12.2-0.8.7608
forge1.12.2-14.23.1.2555
OptiFine_1.12.2_HD_U_C8
no other mod

map test creative solo
/ mc colonies rsResetAll at every update

**Comment by Raycoms** [comment]
Can you check in the world - minecolonies - chunkinfo folder?

2018-02-21 17:48 GMT+00:00 Faenum <notifications@github.com>:

**Comment by Faenum** [comment]
this is a new map im trying to use it on, in single player, ive tried putting down a couple of buildings right next to the town hall and its giving me that error.
there are several files in my chunkinfo folder

**Comment by Raycoms** [comment]
Can you make a screenshot of those files, and, are you using windows?

2018-02-21 17:55 GMT+00:00 Faenum <notifications@github.com>:

**Comment by Raycoms** [comment]
Found the issue, pushing a fix

2018-02-21 17:57 GMT+00:00 Ray Neiheiser <ray.neiheiser@gmail.com>:

**Comment by Faenum** [comment]
yep, windows 10.

**Comment by Faenum** [comment]
sweet thanks

**Comment by DjTylerD** [comment]
minecolonies-universal-1.12.2-0.8.7611.jar
always the same problem
in save / test mine / minecolonies / chunkInfo
I have 35 files from -0 to -27 all empty and without extension (.txt or .dat, ect ...)

**Comment by Faenum** [comment]
What version number will that be please?

**Comment by Raycoms** [comment]
7611

2018-02-21 18:29 GMT+00:00 Faenum <notifications@github.com>:

**Comment by Faenum** [comment]
Ive updated and still getting the same issue, do i need to start a new world for it to work?

**Comment by Faenum** [comment]
Tried it on a new map, still got the same problem

**Comment by Raycoms** [comment]
Yeah try *7613*

2018-02-21 19:00 GMT+00:00 Faenum <notifications@github.com>:

**Comment by Faenum** [comment]
Ok thanks

**Comment by Faenum** [comment]
Still not working, getting same issue.

**Comment by Raycoms** [comment]
Even in a new world?

**Comment by DjTylerD** [comment]
note 7613
still same problem, but on a new map it works thanks to the name change of chunk-0 to chunk-0_0_0 folder

on my game map i try / mc colonies rsResetAll or clear the files i games not trying to rewrite files

**Comment by Raycoms** [comment]
you can try to rename those files to _ _ _ of the right chunk locations to
fix old worlds.

2018-02-21 19:18 GMT+00:00 DjTylerD <notifications@github.com>:

**Comment by Faenum** [comment]
Ok its working in a new world.

**Comment by DjTylerD** [comment]
@Raycoms 
the problem has become chunk file, on the new map, there is chunk-0_1_0, chunk-1_0_0 ect ....
just to load map, ask townhall and try hut builder
I have 1089 files (I miss it)

**Comment by Raycoms** [comment]
what you can do is: run /mc backup then /mc colony delete 1, then wait a
bit, log off, log on, walk until each side of the border.
Then place the townhall at exact the same spot.
Then log off, and replace the backed up colonyX.dat with the new one.

**Comment by DjTylerD** [comment]
@Raycoms I will test
but good for me it's not serious what are the test maps
to help you because I'm thinking about the other player
(I have my server in stanbye since minecraft 1.11.2, following all the modif commandblock 1.12 and soon 1.13)

**Comment by Raycoms** [comment]
Fortunately, this is the alpha version so bugs are to be expected if you
always download the latest.
If you want a stable one check if the last one introduced any fundamental
changes and don't get it if it does.

2018-02-21 19:41 GMT+00:00 DjTylerD <notifications@github.com>:

**Comment by DjTylerD** [comment]
lol, I did not know the news
/ mc colony delete 1 destroyed all buildings

**Comment by Raycoms** [comment]
Oh shoot, it would be /mc colony delete 1 false to not destroy them.

2018-02-21 19:49 GMT+00:00 DjTylerD <notifications@github.com>:

**Comment by DjTylerD** [comment]
good test finished, my last save map date 19-02
so without going through the day's bug
with my save no bug and I have no file in chunkinfo
