### ISSUE TITLE
 Can't do any thing

### ISSUE THREAD

**Issue by CashMaster** [ldtteam/minecolonies#2250]
### Minecolonies version

0.8.7613

### Expected behavior

Placing supply ship and building chests/huts

### Actual behaviour

Whenever I try to place the supply ship it says it must be in a fitting pool of water (When it is) and when I try to place a supply camp it says I can't make it near an existing colony (When I don't have any). I also can't craft any thing like builders huts, citizen huts etc. (I can craft the building wand)

**Comment by Raycoms** [comment]
@mkienenb

**Comment by mkienenb** [comment]
@Raycoms  Looks like you found the reason (wasn't me!) the colony error was showing up and already fixed it.
My changes only affected the supply camp and not the supply ship so not sure what's going on with that either.

**Comment by Raycoms** [comment]
yeah fixed it =D

**Comment by mkienenb** [comment]
If the changes I made to supply-camp were applied to supply-ship, that would probably have revealed that the supply ship error was also the same colony error and not a water block issue.
