### ISSUE TITLE
1.12.2 crash when clicking upgrade building on citizen hut level 4

### ISSUE THREAD

**Issue by Faenum** [ldtteam/minecolonies#2251]
### Minecolonies version

version 0.8.7613

### Expected behavior

not to crash when upgrading building

### Actual behavior

client crashes when clicking upgrade on citizen hut 4

crash report: https://gist.github.com/Faenum/d21b2a5163d2483206d0f098b38ceb2a

**Comment by Faenum** [comment]
Tested on a second hut, same problem, upgraded to level 4 then crashes on next upgrade

**Comment by PoroUsedSnax** [comment]
Would this happen to be related to the Medieval Oak level 4 -> level 5? If so, we recently had a fix for it from the creator and should have it in the mod soon.

**Comment by Faenum** [comment]
Yes, thats the one. Brill, thanks.

**Comment by carlansor** [comment]
Yeah fix is ready, will be included in next alpha
