### ISSUE TITLE
[1.12.2] [0.8.7620] Console/Log Spam: [minecolonies]: chunk has colonies

### ISSUE THREAD

**Issue by Sandriell** [ldtteam/minecolonies#2254]
### Minecolonies version

minecolonies-universal-1.12.2-0.8.7620

### Expected behavior

Not spamming the log

### Actual behaviour

Getting the following spammed in the log (I assume as chucks are loaded):

`6:54:24 PM CONSOLE: thread/INFO] [minecolonies]: chunk has colonies: [1]`
`6:54:26 PM CONSOLE: thread/INFO] [minecolonies]: chunk has colonies: [1]`
`6:54:35 PM CONSOLE: thread/INFO] [minecolonies]: chunk has colonies: [1]`
`6:54:45 PM CONSOLE: thread/INFO] [minecolonies]: chunk has colonies: [1]`
`6:54:47 PM CONSOLE: thread/INFO] [minecolonies]: chunk has colonies: [1]`
`6:54:48 PM CONSOLE: thread/INFO] [minecolonies]: chunk has colonies: [1]`
`6:54:48 PM CONSOLE: thread/INFO] [minecolonies]: chunk has colonies: [1]`
`6:54:48 PM CONSOLE: thread/INFO] [minecolonies]: chunk has colonies: [1]`
`6:54:48 PM CONSOLE: thread/INFO] [minecolonies]: chunk has colonies: [1]`
`6:54:48 PM CONSOLE: thread/INFO] [minecolonies]: chunk has colonies: [1]`
`6:54:49 PM CONSOLE: thread/INFO] [minecolonies]: chunk has colonies: [1]`
`6:54:49 PM CONSOLE: thread/INFO] [minecolonies]: chunk has colonies: [1]`
`6:56:04 PM CONSOLE: thread/INFO] [minecolonies]: chunk has colonies: [1]`
`6:56:08 PM CONSOLE: thread/INFO] [minecolonies]: chunk has colonies: []`
`6:56:10 PM CONSOLE: thread/INFO] [minecolonies]: chunk has colonies: []`
`6:56:15 PM CONSOLE: thread/INFO] [minecolonies]: chunk has colonies: []`
`6:56:17 PM CONSOLE: thread/INFO] [minecolonies]: chunk has colonies: []`
`6:56:19 PM CONSOLE: thread/INFO] [minecolonies]: chunk has colonies: []`
`6:56:25 PM CONSOLE: thread/INFO] [minecolonies]: chunk has colonies: []`
`6:57:20 PM CONSOLE: thread/INFO] [minecolonies]: chunk has colonies: []`
`6:57:20 PM CONSOLE: thread/INFO] [minecolonies]: chunk has colonies: []`
`6:57:22 PM CONSOLE: thread/INFO] [minecolonies]: chunk has colonies: []`
`6:57:32 PM CONSOLE: thread/INFO] [minecolonies]: chunk has colonies: []`
`6:57:50 PM CONSOLE: thread/INFO] [minecolonies]: chunk has colonies: [1]`

### Steps to reproduce the problem

Happens constantly.

**Comment by Raycoms** [comment]
Currently added to debug the new feature, will be removed soon.

2018-02-23 0:15 GMT+00:00 Sandriell <notifications@github.com>:

**Comment by Raycoms** [comment]
Fixed in latest alpha
