### ISSUE TITLE
cant place builder hut even when im still close to the town hall

### ISSUE THREAD

**Issue by MaiyrCordeth** [ldtteam/minecolonies#2255]
### Minecolonies version

version 1.12.2-0.8.7620

### Expected behavior

placing builder hut should let me place it

### Actual behaviour

says i am too far from my town hall even though I'm only 6-10 blocks away

### Steps to reproduce the problem

1. place builder hut
2. ZYX
3. ...
4. Profit

I changed 

        # Colony size (radius in chunks around central colony chunk)
        I:workingRangeTownHallChunks=15
to     

        # Colony size (radius in chunks around central colony chunk)
        I:workingRangeTownHallChunks=40

to fix it

**Comment by Raycoms** [comment]
Just walk around a bit or relog.
