### ISSUE TITLE
[enhancement] Deliveryman does simple crafting

### ISSUE THREAD

**Issue by MattBeard** [ldtteam/minecolonies#2256]
If you teach the deliveryman crafting recipes he doesn't seem to use them, however it would be ideal to be able to use this as a simple way to handle common simple recipes. For example oak wood to oak planks. Then any worker that wants planks can just ask for a delivery and the deliveryman will collect wood from the warehouse and deliver planks.

**Comment by Raycoms** [comment]
Yeah, we will have special workers for this, it doesn't make a lot of sense to have a deliveryman craft things.
