### ISSUE TITLE
Minecraft crashes when I place a Town Hall Block, help pls

### ISSUE THREAD

**Issue by Lakstar** [ldtteam/minecolonies#2257]
Minecolonies version

version 1.12.2-0.8.4191 or forge 14.23.2.2619

Expected behavior

- Town Hall block is placed and game keeps running

Actual behaviour

- Game Crashes

Steps to reproduce the problem

1. Start Minecraft
2. Start World
3. Create Supplyboat and get town hall block / go to creative and get town hall block
4. Place it and game crashes
5. Profit

**Comment by Raycoms** [comment]
Please update your version, you're 3000 builds behind =)
