### ISSUE TITLE
[1.12.2] [0.8.7620] Builder only takes single item after request being fufilled

### ISSUE THREAD

**Issue by Sandriell** [ldtteam/minecolonies#2258]
### Minecolonies version

0.8.7620

### Expected behavior

After requesting a stack(s) of items the builder will pick up the entire stack(s).

### Actual behaviour

When the builder request something and it is fulfilled by a delivery person, the builder will only take a single item, walk all the way out to the job site, place the single item, then go back and pick the rest of the items. This happens for every item that is requested/auto-fulfilled doubling the amount of time needed to build.

### Steps to reproduce the problem

Queue up a build and have the needed items in the warehouse so that they are fulfilled by the npcs.
Observe the behavior.

**Comment by marchermans** [comment]
Yes it is a known bug and being worked on.
