### ISSUE TITLE
Colony deleted without reason and crash when placing TownHall

### ISSUE THREAD

**Issue by carlansor** [ldtteam/minecolonies#2259]
Minecolonies version

version 1.12.2-0.8.7620 and forge 1.12.2 - 14.23.2.2619

I log into a world with just one colony, but it seems that the colony doesnt exist anymore. Relogging doesnt help. Looking for it with /mc colonies list doesnt show anything. Also, when placing other townhall the game crashed. Here is the crash log:
[crash-2018-02-24_13.05.54-server.txt](https://github.com/Minecolonies/minecolonies/files/1754707/crash-2018-02-24_13.05.54-server.txt)

**Comment by Raycoms** [comment]
Wow this is weird, it seems like you removed a mod which messed up the
colonies (probably adds ores/saplings)

2018-02-24 17:42 GMT+00:00 carlansor <notifications@github.com>:

**Comment by carlansor** [comment]
I didnt have any mods that add trees or ores. Worldedit, worldedit cui, dynamic sorroundings and worldsutil. I didnt change anything in the save folder either

**Comment by Raycoms** [comment]
Weird, then a crash or something else must've corrupted the world, the
problem is that the colonies.dat seems to have invalid data caused by some
strange event.

2018-02-24 19:42 GMT+00:00 carlansor <notifications@github.com>:

**Comment by alcheya** [comment]
Same thing happened to me a bit ago. You can restore your colony from a backup. (colony#.dat) Happened when I updated the mod.

**Comment by carlansor** [comment]
The world was fine until i tried to put a townhall. Well time to ditch another test world

**Comment by Raycoms** [comment]
Please reopen if still occurring
