### ISSUE TITLE
Crashing constantly.

### ISSUE THREAD

**Issue by alcheya** [ldtteam/minecolonies#2262]
### Minecolonies version

version 0.8.7620

### Expected behavior

- Not to crash

### Actual behaviour

- Constantly crashing with Minecolonies spam in the crash-report

### Steps to reproduce the problem

1. Turn on the game
2. Crash
3. The end
-----------------------------

Should note, I notice OpenMods also in the log, so if it's that one, please let me know so I can post it there or update that. Thanks.

I was crashing non-stop and the crash report was showing Minecolonies over and over, so I updated. First my colony was deleted (restored from backup) and now it's still crashing every now and then.
This is the latest crash:
[crash-2018-02-24_14.53.32-server.txt](https://github.com/Minecolonies/minecolonies/files/1755179/crash-2018-02-24_14.53.32-server.txt)

This is from before the update:
[crash-2018-02-23_23.52.29-server.txt](https://github.com/Minecolonies/minecolonies/files/1755180/crash-2018-02-23_23.52.29-server.txt)

This is from days ago, still the same thing:
[crash-2018-02-19_17.25.42-server.txt](https://github.com/Minecolonies/minecolonies/files/1755182/crash-2018-02-19_17.25.42-server.txt)

**Comment by alcheya** [comment]
The nonstop crashes broke my world. I ended up losing a couple chunks (specifically with my mob grinder in it) and restored them with MC edit.. It was fine, but still crashing.. Now I logged back in and the entire area where my house (and colony was) is regenerated, erasing all my progress from the last 2 weeks.

**Comment by Wissi** [comment]
Try removing/changing Foamfix to see if it helps?
```Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (FoamFix-1.12.2-0.8.4-Anarchy.jar)```

**Comment by Wissi** [comment]
For the Colony you can restore it from a backup. 
1.- Stop serer, go to world folder on server and inside there is "minecolonies" folder.
     ``` /world/minecolonies/```
2.- Rename/remove colonies.dat and replace with a backup version. backups are timestamped, so whichever you decide jsut rename it to colonies.dat
3.- Start server.

**Comment by alcheya** [comment]
Yea, I rolled back to a previous save. Colony disappeared again, so I replaced colony1.dat with an older backup and it worked. I'll remove Foamfix on my next crash, should be soon.

**Comment by alcheya** [comment]
Don't want to jinx it, but it definitely feels much better. No lag spikes/jitters like I was getting and hasn't shut down yet. Foamfix might have been the issue.

**Comment by Wissi** [comment]
If no further comment, then it was Foamfix and we close this issue now.

**Comment by alcheya** [comment]
It just crashed again. It was the longest it's lasted though. 

[crash-2018-02-24_20.34.07-server.txt](https://github.com/Minecolonies/minecolonies/files/1755533/crash-2018-02-24_20.34.07-server.txt)

**Comment by Raycoms** [comment]
It's weird, we just got another report as well, I will check this again
tomorrow, are you running the latest alpha?

2018-02-25 1:35 GMT+00:00 Alcheya <notifications@github.com>:

**Comment by alcheya** [comment]
Yes, but the earlier 2 crashes I believe were both earlier versions.

**Comment by marchermans** [comment]
Is this on a dedicated server or on singleplayer?

**Comment by alcheya** [comment]
Singleplayer, ATM3 pack

**Comment by marchermans** [comment]
Okey Thanks.

**Comment by marchermans** [comment]
Okey that explains a bit.
@Raycoms you will need to rewrite the your recipe manager implementation to NOT use a freaking static recipe map.

Of course that throws an CME, when the client tries to modify it due to syncing.

**Comment by alcheya** [comment]
This was marked as fixed. Was it supposed to be fixed with the latest alpha or is this a new crash?
[crash-2018-02-26_00.23.54-server.txt](https://github.com/Minecolonies/minecolonies/files/1757326/crash-2018-02-26_00.23.54-server.txt)
[crash-2018-02-26_00.30.40-server.txt](https://github.com/Minecolonies/minecolonies/files/1757327/crash-2018-02-26_00.30.40-server.txt)

**Comment by Justen-N** [comment]
It should have been fixed, however, it looks like it wasn't. @Raycoms, I've reopened this issue.

**Comment by Justen-N** [comment]
Also, @alcheya, we don't say a closed issue is fixed, it simply means we have addressed it. If the error persists, please reopen the issue. Pretty much what you did, but with an extra step.

**Comment by alcheya** [comment]
Thanks, sorry.

**Comment by Raycoms** [comment]
Please reopen if still happening.
