### ISSUE TITLE
Crash getting worse

### ISSUE THREAD

**Issue by DylanSkokan** [ldtteam/minecolonies#2263]
### Minecolonies version

minecolonies-universal-1.12.2-0.8.7508 or curse X.X.XX

### Expected behavior

- Game runs

### Actual behaviour

- Game crashes with this crash log. I used to be able to play on this world fine but the time I could play got shorter and shorter until it crashes about a second into loading the world.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  LoadingPlugin (Quark-r1.4-121.jar)
  LoadingPlugin (HardcoreDarkness-MC1.12.2-2.0.jar)
Contact their authors BEFORE contacting forge

// On the bright side, I bought you a teddy bear!

Time: 2/24/18 7:14 PM
Description: Exception in server tick loop

java.util.ConcurrentModificationException
	at com.google.common.collect.HashBiMap$Itr.hasNext(HashBiMap.java:401)
	at java.util.AbstractCollection.toArray(Unknown Source)
	at com.google.common.collect.Iterables.toArray(Iterables.java:295)
	at com.google.common.collect.ImmutableMap.copyOf(ImmutableMap.java:406)
	at com.google.common.collect.ImmutableMap.copyOf(ImmutableMap.java:391)
	at com.minecolonies.coremod.colony.requestsystem.management.manager.StandardRecipeManager.getRecipes(StandardRecipeManager.java:34)
	at com.minecolonies.coremod.colony.buildings.AbstractBuildingWorker.serializeToView(AbstractBuildingWorker.java:502)
	at com.minecolonies.coremod.colony.buildings.BuildingBuilder.serializeToView(BuildingBuilder.java:228)
	at com.minecolonies.coremod.network.messages.ColonyViewBuildingViewMessage.<init>(ColonyViewBuildingViewMessage.java:42)
	at com.minecolonies.coremod.colony.managers.BuildingManager.lambda$sendBuildingPackets$1(BuildingManager.java:444)
	at com.minecolonies.coremod.colony.managers.BuildingManager$$Lambda$1206/1111216842.accept(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.util.HashMap$KeySpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at com.minecolonies.coremod.colony.managers.BuildingManager.sendBuildingPackets(BuildingManager.java:444)
	at com.minecolonies.coremod.colony.managers.BuildingManager.sendPackets(BuildingManager.java:148)
	at com.minecolonies.coremod.colony.managers.ColonyPackageManager.updateSubscribers(ColonyPackageManager.java:168)
	at com.minecolonies.coremod.colony.Colony.onServerTick(Colony.java:509)
	at com.minecolonies.coremod.colony.ColonyManager.onServerTick(ColonyManager.java:618)
	at com.minecolonies.coremod.event.FMLEventHandler.onServerTick(FMLEventHandler.java:35)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_45_FMLEventHandler_onServerTick_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:264)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:710)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1005147016 bytes (958 MB) / 3216506880 bytes (3067 MB) up to 4772593664 bytes (4551 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx5120m
	IntCache: cache: 0, tcache: 0, allocated: 20, tallocated: 86
	FML: MCP 9.42 Powered by Forge 14.23.1.2590 42 mods loaded, 42 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                  | Version                  | Source                                          | Signature                                |
	|:--------- |:------------------- |:------------------------ |:----------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft           | 1.12.2                   | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | mcp                 | 9.42                     | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | FML                 | 8.0.99.99                | forge-1.12.2-14.23.1.2590-universal.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge               | 14.23.1.2590             | forge-1.12.2-14.23.1.2590-universal.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | fenceoverhaul       | 1.3.2                    | [1.12]FenceOverhaul-1.3.2.jar                   | None                                     |
	| UCHIJAAAA | quark               | r1.4-121                 | Quark-r1.4-121.jar                              | None                                     |
	| UCHIJAAAA | autoreglib          | 1.3-15                   | AutoRegLib-1.3-15.jar                           | None                                     |
	| UCHIJAAAA | codechickenlib      | 3.1.5.331                | CodeChickenLib-1.12.2-3.1.5.331-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | avaritia            | 3.2.0                    | Avaritia-1.12-3.2.0.13-universal.jar            | None                                     |
	| UCHIJAAAA | betterbuilderswands | 0.11.1                   | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar | None                                     |
	| UCHIJAAAA | chesttransporter    | 2.8.7                    | ChestTransporter-1.12-2.8.7.jar                 | None                                     |
	| UCHIJAAAA | chickenchunks       | 2.4.1.71                 | ChickenChunks-1.12.2-2.4.1.71-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | ctm                 | MC1.12-0.2.3.12          | CTM-MC1.12-0.2.3.12.jar                         | None                                     |
	| UCHIJAAAA | chisel              | MC1.12-0.1.1.28          | Chisel-MC1.12-0.1.1.28.jar                      | None                                     |
	| UCHIJAAAA | clienttweaks        | 3.1.2                    | ClientTweaks_1.12-3.1.2.jar                     | None                                     |
	| UCHIJAAAA | endercompass        | 1.2.6.1                  | EnderCompass-1.12-1.2.6.1.jar                   | None                                     |
	| UCHIJAAAA | fastleafdecay       | v14                      | FastLeafDecay-v14.jar                           | None                                     |
	| UCHIJAAAA | flatbedrockx        | 1.4.0                    | FlatBedrock-1.4.0_1.12.jar                      | None                                     |
	| UCHIJAAAA | hardcoredarkness    | 2.0                      | HardcoreDarkness-MC1.12.2-2.0.jar               | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| UCHIJAAAA | harvest             | 1.12-1.2.6-18            | Harvest-1.12-1.2.6-18.jar                       | None                                     |
	| UCHIJAAAA | ichunutil           | 7.1.4                    | iChunUtil-1.12.2-7.1.4.jar                      | None                                     |
	| UCHIJAAAA | inventorytweaks     | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                        | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJAAAA | ironbackpacks       | 1.12.2-3.0.4             | IronBackpacks-1.12.2-3.0.4.jar                  | None                                     |
	| UCHIJAAAA | ironchest           | 1.12.2-7.0.34.820        | ironchest-1.12.2-7.0.34.820.jar                 | None                                     |
	| UCHIJAAAA | jei                 | 4.8.5.138                | jei_1.12.2-4.8.5.138.jar                        | None                                     |
	| UCHIJAAAA | mantle              | 1.12-1.3.1.21            | Mantle-1.12-1.3.1.21.jar                        | None                                     |
	| UCHIJAAAA | minecolonies        | 1.12.2-0.8.7508          | minecolonies-universal-1.12.2-0.8.7508.jar      | None                                     |
	| UCHIJAAAA | mobdismemberment    | 7.0.0                    | MobDismemberment-1.12.2-7.0.0.jar               | None                                     |
	| UCHIJAAAA | mousetweaks         | 2.8                      | MouseTweaks-2.8-mc1.12.1 (1).jar                | None                                     |
	| UCHIJAAAA | naturescompass      | 1.5.1                    | NaturesCompass-1.12.2-1.5.1.jar                 | None                                     |
	| UCHIJAAAA | openglider          | @VERSION@                | OpenGlider-1.12.1-1.1.0.jar                     | None                                     |
	| UCHIJAAAA | portalgun           | 7.0.0                    | PortalGun-1.12.2-7.0.1.jar                      | None                                     |
	| UCHIJAAAA | silentlib           | 2.2.16                   | SilentLib-1.12-2.2.16-97.jar                    | None                                     |
	| UCHIJAAAA | tconstruct          | 1.12.2-2.9.1.65          | TConstruct-1.12.2-2.9.1.65.jar                  | None                                     |
	| UCHIJAAAA | silentgems          | 2.6.7                    | SilentsGems-1.12-2.6.7-258.jar                  | None                                     |
	| UCHIJAAAA | sgextraparts        | 1.4.1                    | SGExtraParts-1.12-1.4.1-34.jar                  | None                                     |
	| UCHIJAAAA | storagenetwork      | 1.12.2-1.2.2             | SimpleStorageNetwork-1.12.2-1.2.2.jar           | None                                     |
	| UCHIJAAAA | stg                 | 1.12.2-1.2.3             | stg-1.12.2-1.2.3.jar                            | None                                     |
	| UCHIJAAAA | tinkersaddons       | 1.0.7                    | Tinkers'+Addons-1.12.1-1.0.7.jar                | None                                     |
	| UCHIJAAAA | tinkertoolleveling  | 1.12-1.0.3.DEV.56fac4f   | TinkerToolLeveling-1.12-1.0.3.jar               | None                                     |
	| UCHIJAAAA | twilightforest      | 3.5.263                  | twilightforest-1.12.2-3.5.263-universal.jar     | None                                     |
	| UCHIJAAAA | vc                  | 5.6.1                    | ViesCraft-1.12.2-5.6.1.jar                      | None                                     |

	Loaded coremods (and transformers): 
CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  team.chisel.ctm.client.asm.CTMTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
LoadingPlugin (Quark-r1.4-121.jar)
  vazkii.quark.base.asm.ClassTransformer
LoadingPlugin (HardcoreDarkness-MC1.12.2-2.0.jar)
  lumien.hardcoredarkness.asm.ClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)

	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['furbiedad'/435, l='New World', x=199.26, y=61.00, z=189.30]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

### Steps to reproduce the problem

1. Load world
2. Do nothing but stand there
3. ...
4. Profit

**Comment by marchermans** [comment]
Is this a dedicated server? or Singleplayer / LAN World?

**Comment by DylanSkokan** [comment]
@OrionDevelopment This is a singleplayer world. I thought singleplayer worlds were run kind of like a server now anyways?

**Comment by Justen-N** [comment]
All video games run on a server/client model. However, how something works
in multiplayer may be completely different from single player.
