### ISSUE TITLE
Builders get stuck building barrack towers

### ISSUE THREAD

**Issue by lunadragnstar** [ldtteam/minecolonies#2265]
### Minecolonies version

minecolonies-universal-1.12.2-0.8.7582 (Twitch Minecolonies Official)

### Expected behavior

- Builders should return to the hut after finishing build/upgrade

### Actual behaviour

- Builders get stuck on catwalk and can't seem to get down. 

### Steps to reproduce the problem

1. Build the barracks
2. Build to barrack towers
3. When the builders finish all 4 towers, they can't seem to get down from the catwalk
4. Have to go to the builder hut and recall builder

**Comment by Raycoms** [comment]
Still happening?

**Comment by lunadragnstar** [comment]
Not sure, this happened building a specific type (I think wooden) but I haven't tried it again

Just to let you know, a lot of the crashes that I was having stopped when I switched to a lightly modded version. The version on twitch with the several dozen other mods kept crashing, now I have like 6 mods working with Minecolonies and it hasn't crashed.

**Comment by Raycoms** [comment]
Should be fixed
