### ISSUE TITLE
Can't build builder hut in any of the medieval or dark oak style.

### ISSUE THREAD

**Issue by lunadragnstar** [ldtteam/minecolonies#2266]
### Minecolonies version

minecolonies-universal-1.12.2-0.8.7582

### Expected behavior

- Builder builds hut

### Actual behaviour

- Builder removes blocks but then just stands there and doesn't build.

### Steps to reproduce the problem

1. Place builder hut
2. Click build building

**Comment by lunadragnstar** [comment]
I was able to get the Dark Oak to work using 7620

**Comment by Raycoms** [comment]
We updated a few of the structure in the last update, all still not working?

2018-02-25 22:59 GMT+00:00 lunadragnstar <notifications@github.com>:

**Comment by lunadragnstar** [comment]
I just downloaded the newest alpha, I'll test it out.

**Comment by lunadragnstar** [comment]
I'm an idiot, I figured out why it wasn't working. I was trying to build on the superflat world and there are basements to these buildings so the builders didn't know how to proceed.
