### ISSUE TITLE
Builder stutter when constructing town hall, player distance required.

### ISSUE THREAD

**Issue by MrSkittlesROTR** [ldtteam/minecolonies#2267]
### Minecolonies version

version minecolonies-universal-1.12.2-0.8.7620

### Expected behavior

- builder pathfinding when constructing town hall

### Actual behaviour

- builder slows down in movement, block place and block break. stuttering to move if outside of 10 blocks distance from a player when constructing the town hall.
- issue didnt happen with construction of builders hut.

### Steps to reproduce the problem

1. replaced the town hall construction still persists
2. replaced builder still persists

can record a video of the issue if needed.

**Comment by Raycoms** [comment]
Are you on a sponge server?

**Comment by MrSkittlesROTR** [comment]
yes
[https://www.youtube.com/watch?v=gGDr1LFb3h8](url)
sry quality's shocking but this is the problem.

**Comment by Raycoms** [comment]
You need to update the entity activation range there, that's why they
stutter

2018-02-25 19:41 GMT+00:00 MrSkittlesROTR <notifications@github.com>:

**Comment by MrSkittlesROTR** [comment]
that worked thank you, sorry for the hassle.
