### ISSUE TITLE
Game crashes when upgrading builder from lvl 3 to 4

### ISSUE THREAD

**Issue by lunadragnstar** [ldtteam/minecolonies#2268]
### Minecolonies version

7637 (alpha)

### Expected behavior

- Upgrade

### Actual behaviour

- crash
[crash-2018-02-26_00.45.03-client.txt](https://github.com/Minecolonies/minecolonies/files/1757349/crash-2018-02-26_00.45.03-client.txt)
[crash-2018-02-26_00.13.30-client.txt](https://github.com/Minecolonies/minecolonies/files/1757350/crash-2018-02-26_00.13.30-client.txt)

### Steps to reproduce the problem

1. Place Town Hall
2. Place builder hut
3. Upgrade, upgrade, upgrade, upgrade

**Comment by Justen-N** [comment]
This looks like a compatibility issue with Malisis doors/core

**Comment by Raycoms** [comment]
I reported it to Malisis, I think he will build a fix for this.
