### ISSUE TITLE
Townhall Placement Issue in 1.12.2

### ISSUE THREAD

**Issue by CorruptShade** [ldtteam/minecolonies#2269]
Minecolonies version : minecolonies-universal-1.12.2-0.8.7637.jar

Expected behavior
When you place down a town hall, construction tape is usually placed down as well. Also able to right click it to make a build request.

Actual behavior
After placing townhall, minecraft stops. All entities(like sheep or cows) stop moving; unable to right-click the townhall; pressing ESC to save and exit crashes the game. 

Other points to note
This issue is isolated to 1.12.2(it works fine on 1.11.2)
The first time I used this mod, it worked fine(in the 1.12.2 version), but I deleted that world.

**Comment by Raycoms** [comment]
What is the colony size in chunks in your config file? Does minecraft run on an ssd?

**Comment by CorruptShade** [comment]
I have the colony size set to 2000. Minecraft doesn't run on an SSD.

**Comment by Raycoms** [comment]
That's the issue, 2000 blocks is a huge range, and it currently has to
write all the files to disk so he is unable to do it, try to restrict the
chunk range to 20, that's still huge and should fit your needs easily.

2018-02-26 14:29 GMT+00:00 CorruptShade <notifications@github.com>:

**Comment by CorruptShade** [comment]
okay thx man

**Comment by CorruptShade** [comment]
this issue still persists

**Comment by CorruptShade** [comment]
[minecolonies.zip](https://github.com/Minecolonies/minecolonies/files/1759143/minecolonies.zip)
 Here's my config file. If any changes are required, please make them and send it back to me

**Comment by Raycoms** [comment]
# Colony size (radius in chunks around central colony chunk)
        I:workingRangeTownHallChunks=20

I don't know exactly how it behaves on a normal HD, you might have to play with this value until you reach the moment it only has a bad lag but works.

We're currently working on improving the performance for non SSD

**Comment by CorruptShade** [comment]
okay thanks
will check it out at 15 chunks

**Comment by CorruptShade** [comment]
It may be interesting for you to note, that even if I set the initial colony size to 5 chunks, I change it later to whatever I like
