### ISSUE TITLE
Question : is it possible to have guards use modded swords ?

### ISSUE THREAD

**Issue by lebanni** [ldtteam/minecolonies#2270]
Citizens can use modded tools (Mekanism, Industrial Craft, Thermal Foundation, etc). Why can't the guards use modded swords ?

**Comment by Raycoms** [comment]
Actually citizens can use modded tools if those implement the minecraft "weapon class" or they are tinker weapons.

**Comment by Wissi** [comment]
Closed cause it's not an Issue that requires to be fixed nor a specific mod request.
Cleaning up issues.

**Comment by lebanni** [comment]
I reported the issue to Mekanism dev, that's what he answered :
https://github.com/aidancbrady/Mekanism/issues/5188

**Comment by Raycoms** [comment]
Then they should be using it =D
Did you try it on a level 5 building?

Am Mo., 12. Nov. 2018 um 21:47 Uhr schrieb lebanni <notifications@github.com
