### ISSUE TITLE
Cant go threw some doors.

### ISSUE THREAD

**Issue by MrSkittlesROTR** [ldtteam/minecolonies#2272]
### Minecolonies version

version minecolonies-universal-1.12.2-0.8.7620

### Expected behavior

- open and enter a door.

### Actual behaviour

- player gets stuck on door can only enter or exit if npc shuts the door on them while they are trying to pass threw, on breaking problem door it displays as half a door.
Problem is on builder hut level 2 main door and one of the doors inside the level 2 townhall.

### Steps to reproduce the problem

1. tried upgrading builder hut no luck.
2. tried breaking the door and repairing no luck

**Comment by Raycoms** [comment]
That's because you're opening a door you are not allowed to open because of colony protection.
So the door opens on client but not on the server. just relog to check.

**Comment by MrSkittlesROTR** [comment]
reloged several times, its been doing it for past 2 days, other players have the same issue.

**Comment by Raycoms** [comment]
That should only happen in other peoples colonies where you don't have the perms to open them.

**Comment by MrSkittlesROTR** [comment]
im the colony owner, other player is set to officer in the town hall.
its only 2 of the doors doing it out of 6 in the colony so far.

**Comment by Raycoms** [comment]
Hmm, I'd say that this is not related to minecolonies then.

2018-02-26 20:15 GMT+00:00 MrSkittlesROTR <notifications@github.com>:

**Comment by Raycoms** [comment]
Do you have any door mods installed which could cause this?
We don'T do anything with doors besides blocking access if it is not your
colony.

2018-02-26 20:20 GMT+00:00 MrSkittlesROTR <notifications@github.com>:

**Comment by MrSkittlesROTR** [comment]
buildcraft + modules
lukyperms
thut essentials
worldedit
generators
irontank
just enough items
journymap
reptilemod
tinkerers construct
minecolonies
gravestones

sponge, bungiecord(waterfall)

none of them effect doors.

**Comment by Raycoms** [comment]
weird, minecolonies shouldn't interfere either. it seems like a cleint
server disconnect

2018-02-26 20:27 GMT+00:00 MrSkittlesROTR <notifications@github.com>:

**Comment by MrSkittlesROTR** [comment]
could it be an issue with useing bungiecord?

**Comment by Raycoms** [comment]
Shouldn't be. Not sure, thur essentials might be causing it as well.

**Comment by MrSkittlesROTR** [comment]
update: fixed it
Buildings hight was 1 block lower down than the surrounding terrain.
removeing a cupple of rows of blocks around the edges of the buildings so the surrounding terrain was the same hight as the building itself fixed the door passage error.
