### ISSUE TITLE
Wooden smeltery lvl 4 despawn builders

### ISSUE THREAD

**Issue by TheCaliban** [ldtteam/minecolonies#2273]
### Minecolonies version

minecolonies-universal-1.11.2-0.8.7585

### Expected behavior

- Build the level 4 of Wooden Smeltery

### Actual behaviour

- Despawn all builders and when the build resquest is created
- Need tu use the command /mc citizens respawn
- Don't start the upgrade

### Steps to reproduce the problem

1. Have 1 or more builder
2. Have a level 3 wooden smeltery
3. Start the level 4 upgrade
4. Wait for confirmation starting building
5. Check the list of citizens with /mc citizens list

**Comment by Raycoms** [comment]
Can you send us the log?

2018-02-27 14:54 GMT+00:00 TheCaliban <notifications@github.com>:

**Comment by TheCaliban** [comment]
I have selected the part of the log that I think is interesting.
[crash_minecolonies.txt](https://github.com/Minecolonies/minecolonies/files/1763696/crash_minecolonies.txt)

**Comment by Raycoms** [comment]
Should be fixed
