### ISSUE TITLE
[1.12.2] [0.8.7637] Cook requests/receives random fuel; should prioritize coal/charcoal.

### ISSUE THREAD

**Issue by Sandriell** [ldtteam/minecolonies#2274]
### Minecolonies version

0.8.7637

### Expected behavior

The the cook would prioritize requesting coal and charcoal first before anything else.

As I am writing this I am thinking this might actually be a dman problem instead?

### Actual behaviour

While having both coal and charcoal in my warehouse the cook requests/receives everything but that, consuming everything within the warehouse that is burnable.

### Steps to reproduce the problem

1. Create a restaurant/cook
2. Give him raw food or what till he requests something to cook.
3. Observe what he requests/receives.

**Comment by Raycoms** [comment]
For now this is intended behavior because in the current request system we can't check if the warehouse can resolve something, as soon as this is added we can add priorities as for recipes or fuel.
This is solved with another issue with "request system simulation"
