### ISSUE TITLE
[Enhancement] Config option for circular or square Colony Protection.

### ISSUE THREAD

**Issue by Wissi** [ldtteam/minecolonies#2276]
Have an option in config file to keep using the existing circular town protection or use the square protection.
For existing servers currently using the circular and heavily populated.

```
# Should the colony protection be circular?
B:enableCircularColonyProtection=true

**Comment by marchermans** [comment]
Sadly we will not be able to implement this feature.
The square colony radius and protection comes from the fact that it now depends on chunks to speed up calculation and detection of colonies.
