### ISSUE TITLE
Cannot confirm actions from server console

### ISSUE THREAD

**Issue by ouroborus** [ldtteam/minecolonies#2277]
MineColonies 1.12.2-0.8.7551

Can't confirm commands using the server console. Confirmation appears to require the ability to click a provided link but server console doesn't render links, just text.

**Comment by marchermans** [comment]
Sadly that is a limit of how mc's command system works.

There is not much we can do. We need contextual data for the confirmation to work properly and the only way to pass that between two command instance (delete request -> delete confirmation) is to use these links.

However these links execute commands as well. So when you execute for example your delete command in the console you can then run: `/mc colony delete <colonyId> <destroyBuildings> true` to confirm.
