### ISSUE TITLE
[Suggestion] Inventory Tweaks support for Racks

### ISSUE THREAD

**Issue by Sandriell** [ldtteam/minecolonies#2278]
I originally requested this from the Inventory Tweaks dev but it seems this is something that has to be supported on your end. I really like the racks and have used them outside of the hut builds for my own uses but the lack of Inventory Tweaks support is frustrating.

**Comment by marchermans** [comment]
Join our Discord and ask for the Minecolonies InvTweaks xml-file.
We sadly can not add this support directly from our code.
