### ISSUE TITLE
town hall crash on latest version

### ISSUE THREAD

**Issue by Zygus42** [ldtteam/minecolonies#2281]
minecolonies-universal-1.12.2-0.8.7686

Rightclick on town hall block = crash to desktop.

[crash-2018-03-02_12.54.49-client.txt](https://github.com/Minecolonies/minecolonies/files/1773765/crash-2018-03-02_12.54.49-client.txt)

**Comment by matthijsthoolen** [comment]
Confirmed, same error here

**Comment by Raycoms** [comment]
Fix pushed.
