### ISSUE TITLE
Enhancement Suggestion: Allow for different blocks for designs, or a way to replace blocks after built

### ISSUE THREAD

**Issue by lunadragnstar** [ldtteam/minecolonies#2282]
### Minecolonies version

any

I would love to see a way to make all the designs, with different blocks. IE. Change the sandstone to regular stone, or wood or obsidian. (during or after build. I like some of the designs, but want them in different blocks.

**Comment by Raycoms** [comment]
Thanks for the suggestion, we're planning on that when we introduce our new GUI framework.
