### ISSUE TITLE
MC 7686 crashes on upgrading Town Hall, regress to 7637 and it proceeded (same world)

### ISSUE THREAD

**Issue by robbcrg** [ldtteam/minecolonies#2283]
### Minecolonies version

version X.X.XXXX or curse X.X.XX
minecolonies-universal-1.12.2-0.8.7686

### Expected behavior

- Does NOT crash when upgrading town Tall L2 to L3. Birch Medieval.

### Actual behavior

- Crashes

Thread: Client thread
Java.lang.NullPointerException: Unexpected error
	at com.minecolonies.coremod.client.gui.WindowTownHall$8.updateElement(WindowTownHall.java:850)

### Steps to reproduce the problem

1. Town Hall at L2
2. Upgrade to L3
3. Crashes hard - to desktop
4. Reload client (server is OK
5. Click Town Hall book
67. Instant Crash

#### Other details

* Archiving the world and preserved a few 15 minute snapshots
* Note keeping work that crashed above and just regressing to my prior MC
* Shut down server and restored prior MC : minecolonies-universal-1.12.2-0.8.7637 to client and server
* Started server, launched client connected
* Clicked Town hall book -- all OK
* Town hall was marked as being upgraded
* Builder started to process
[fml-client-2.log](https://github.com/Minecolonies/minecolonies/files/1776587/fml-client-2.log)

**Comment by copperwarrior** [comment]
Please update to the latest alpha, there has been a hotfix pushed to fix this error.

**Comment by robbcrg** [comment]
Confirmed: As a test I restored my prior world that crashed, updated the MC to (minecolonies-universal-1.12.2-0.8.7688) and everything worked.

Thank you
