### ISSUE TITLE
Builders stop building/freeze

### ISSUE THREAD

**Issue by mackenziemay** [ldtteam/minecolonies#2284]
### Minecolonies version

version 1.12.2-08.7582

### Expected behavior

- build anything thing

### Actual behaviour

- frozen in one spot not moving or asking for anything

**Comment by copperwarrior** [comment]
Please update to the latest alpha and see if the issue persists

**Comment by mackenziemay** [comment]
where do I find that?

**Comment by copperwarrior** [comment]
https://minecraft.curseforge.com/projects/minecolonies

**Comment by mackenziemay** [comment]
thank you!

**Comment by CringeCakes** [comment]
The problem is still happening in the latest version (1.12.2-0.8.7809)

**Comment by Kisonu** [comment]
issue happening with 0.8.8390 version as well.

**Comment by Raycoms** [comment]
Should be fixed
