### ISSUE TITLE
[Feature Request] Herders breed Animania Animals

### ISSUE THREAD

**Issue by merdinarchfire** [ldtteam/minecolonies#2285]
### Minecolonies version

version 1.2.12

### Expected behavior

- Breeding Animania Cows check for male female.

### Actual behaviour

- Kills off Cows to only have 2 cows. 

### Config Request

- I haven't seen an option for this, but it would be great if there was a config to change how many animals the herders keep alive. Or have them check for Male and Female when using Animania. 
- The issue is that my cowboy killed off the female adult then once the baby grew up it was a Bull, so I was stuck with 2 Bulls and no longer can get more cows.

**Comment by Asherslab** [comment]
Sadly i cannot add support for Animania without some serious changes, This does seem to be something i'd like to do in the future when i have the time though.

**Comment by Terpo** [comment]
Would iit be possible to check for named animals and don't kill these? This would allow to name two cows/pigs/whatever without breaking everything.

**Comment by marchermans** [comment]
That would be an option. @Asherslab would that work?

**Comment by Wissi** [comment]
@Asherslab To fix the compatibility issue w/animania animals (and any other type). Can a config option be added (to the hut GUI or the config file) so that players can manually add modded animals?
Animals placed here would be treated in vanilla manner: bred like a vanilla mob type and killed. (for now).
If they require special breeding then player would have to do it or even automate it, but at least they would have the kills and drops, herders would be workable for now?

**Comment by merdinarchfire** [comment]
I found that when upgrading the Cowboy to a higher level it wasn't as big a
problem, but would still lose the female cows. It looks like the higher
level cowboy keeps more cows so, this made it less likely for it to break
and have no more breeding. I haven't tested beyond a level 2 Cowboy.

**Comment by capnkirok** [comment]
https://github.com/capnkirok/animania/issues/600
Hey guys. Had a request on the Animania side for just this and wanted to add my name here. Let me know what you might need to proceed. One way to do this currently is to pull the EntityNames from all the animals to determine gender. Of course, each species is using the colloquial gender name (e.g. Doe & Buck for Rabbits), so it's tedious. But it would work. Let me know how I could further support. 

Purp

**Comment by marchermans** [comment]
It is not that we are not looking in to this. It is just that we are slowing introducing new workers since this is a complete rebuild from scratch. And we have other priorities. It should however be relatively easy to do. Is there a way in code to detect if I have a female and male, in a list of entities?

**Comment by marchermans** [comment]
Also do you have a maven repo we can use in development?

**Comment by capnkirok** [comment]
No maven (yet), but source code is here: https://github.com/capnkirok/animaniamod

As I mentioned, there is a way of telling if male or female, based on Entity Name. If you check for instanceof EntityCow, you can check the entity name string for the occurence of "animania:bull_" or "animania:cow_" or "animania:calf_"

The same goes for all animals.. but you will need to know the colloquial names currently. Easy to see this list from the lang file.

**Comment by Raycoms** [comment]
Yeah but if you'd get it to maven somewhere we could just do instance of
AnimaniaAnimal and isFemale, which would be a lot cleaner when we get to it.

2018-04-08 22:26 GMT+01:00 Purplicious_Cow <notifications@github.com>:

**Comment by capnkirok** [comment]
Yes, agree. Seems like a good reason to get a maven :)

**Comment by marchermans** [comment]
If you want you can use our buildsystem. It has an integrated maven/ivy repo.

**Comment by Asherslab** [comment]
Wow i forgot i turned off github notifications ages ago, sorry about that. 
@capnkirok that'd be awesome if you could get a maven, OR just use our buildsystem (we use docker and a few other things which makes our system work amazingly well)

@Wissi sadly it wouldn't be that simple, but the abov emention idea *should work

**Comment by MokahTGS** [comment]
Hopefully this will get support.  Currently my cowboy just feeds the cows endlessly until he's out of wheat.

**Comment by hron84** [comment]
@capnkirok maybe could you make an API call that can return male/female info based on names?

**Comment by marchermans** [comment]
@capnkirok Do you still need a BuildSystem / Repository?

**Comment by caerulea1324** [comment]
i also would love a compatibility, since i think this two mods would suit each other :D

**Comment by Xorbah** [comment]
Did anything ever happen with this?

**Comment by Justen-N** [comment]
Not as of yet.  There are two ways to do this, but the way that's best in
the long run isn't supported by Animania.

**Comment by 0dinson** [comment]
So is there any workaround to this right now? I really want to use the herders but Animania is an important mod for me so id rather not uninstall it. Im not sure if it would work to use spawn eggs to get vanilla cows just for the herder maybe?

**Comment by Justen-N** [comment]
Using vanilla cows is currently  recommended.  We are working with
Purpalicious_Cow but he is extremely busy with his actual job.

**Comment by 0dinson** [comment]
Thanks for the quick response, using vanilla cows seems like the best option for now. My issue is though that using a vanilla spawn egg for cows it just spawns nothing after using it, something seems to completely deactive normal cows.

**Comment by Justen-N** [comment]
You may be able to change that via animania's configs, if I remember
correctly.

**Comment by 0dinson** [comment]
Alright thanks i will check why they won't spawn and look in the animania and familiar flora configs. I hope there will be a patch someday in the future when Purpalicious got more time :)

**Comment by ErdbeerbaerLP** [comment]
Also the animals need water, that should be implemented too

**Comment by hron84** [comment]
@ErdbeerbaerLP since Animania animals can drink from an infinite pool of water and water through, herders not necessarily have to take care about it, it could be automated in so many ways.

**Comment by ErdbeerbaerLP** [comment]
Yeah, but the builder should. Level 1 for example does not have any water (i think i used wooden)

**Comment by Raycoms** [comment]
Would be more on the responsibility of the style author.

Am Fr., 23. Aug. 2019 um 18:50 Uhr schrieb ErdbeerbaerLP <
notifications@github.com>:

**Comment by Raycoms** [comment]
Will be added to a new joint mod compat issue.
