### ISSUE TITLE
[SUGGESTION] New NPC Crafter

### ISSUE THREAD

**Issue by Fireruner** [ldtteam/minecolonies#2289]
Crafter

A new type of NPC that recieves the requirements of constructors or any other NPC, and then asks for prime materials to craft the ones that needs crafting. Then, the delivery man attends the requirements of prime materials so he can craft, and let them to the delivery man to get them where they are needed.

Also, he should calculate the precrafts needed. For example, for an axe, you need sticks, and for sticks you need planks, so he asks for sticks, and if they are not delivered, planks, and if they are not delivered, then wood. If not prime material is supplied, then he waits for it.

Hope is not too complicated and is clear. Also, sorry if I made any mistake in spelling or formating, this is my first time creating an Issue here.

P.S I´m a Java dev and I´ll love to help if there is need of it. Maybe, I can try to implement this if it is not too complicated

**Comment by marchermans** [comment]
This is in the works and on holt until I am done with exams at the end of the week.

**Comment by Raycoms** [comment]
There is an issue for that already as well.

@Fireruner We'd be glad to have you in hour team, we have a bunch of tasks open to be solved =)

**Comment by Raycoms** [comment]
If you send me your email I can invite you to our dev chat

**Comment by Fireruner** [comment]
Nice! It would be a pleasure! Where can I send it to you safelly? :D

**Comment by Raycoms** [comment]
You can contact me on discord: https://discord.gg/gA7T6ma (My name is
raycoms)

2018-03-05 15:58 GMT+00:00 Daniel Fuego <notifications@github.com>:
