### ISSUE TITLE
cannot bulid Bakery Medieval DarkOak Level 5 because of wrong type of stonebrick in the schematic

### ISSUE THREAD

**Issue by collwee** [ldtteam/minecolonies#2291]
### Minecolonies version

version 0.8.7688

### Actual behaviour

- in the schematic Bakery Medieval DarkOak Level 5 some of (Stone Brick) block are (Stone Brick Monster Egg) and because of that you cannot build it

### Steps to reproduce the problem

- try to upgrade level 4 darkoak bakery and it ask (Stone Brick Monster Egg)
- or spawn the level 5 darkoak bakery in creative and look at the stone brick allot of them are (Stone Brick Monster Egg)

**Comment by carlansor** [comment]
thanks for submitting the issue, i will look into it and fix it.

**Comment by Raycoms** [comment]
should be fixed
