### ISSUE TITLE
Level 3 Wooden style Herder buildings are offset from the level 1,2,4, and 5 buildings.

### ISSUE THREAD

**Issue by GrokDuckFarmer** [ldtteam/minecolonies#2292]
### Minecolonies version

minecolonies-universal-1.12.2-0.8.7572.jar

### Expected behavior

Wooden style Level 3 herder huts line up with Level 2 structures

### Actual behaviour

All four herder huts (sheep, cow, pig, chicken) are offset from the rest of the huts with the Level 3 building.  They are back 5 blocks, to the left 5 blocks, and up 1 block.

### Steps to reproduce the problem

1. Have the Building Tool and any of the four animal herder hut blocks in your inventory
2. Right-click the Building Tool on the ground
3. Select the wooden style and level 2 hut.  Note its placement on the ground with a block in the corners.
4. Select the level 3 herder's hut.  Note that it has shifted over, back, and up.

The misalignment of the level 3 building will make the builder break any overlapped blocks.  Note the attached image showing the hut overlapping the level 2 chicken pens in the back.

![overlap](https://user-images.githubusercontent.com/22861790/37052328-d3c08166-212d-11e8-8638-f3e67c1021a5.jpg)

**Comment by Raycoms** [comment]
Should be fixed
