### ISSUE TITLE
"Commin'" is misspelled

### ISSUE THREAD

**Issue by GrokDuckFarmer** [ldtteam/minecolonies#2293]
### Minecolonies version

minecolonies-universal-1.12.2-0.8.7572.jar

### Expected behavior

Barbarian horde warnings are spelled correctly.

### Actual behaviour

"commin'" is misspelled with an extra m in the word.  Should be "comin'" to be correct.

### Steps to reproduce the problem

1. Build your colony.
2. Wait for the warning that barbarians are coming.
3. Shake your head at the misspelling.

**Comment by Wissi** [comment]
Well in that case it's also misspelled as `comin`
It would either be: `coming` or `comin'`
But I guess it's kinda intentional   xP
