### ISSUE TITLE
[1.10.2]Server Crash

### ISSUE THREAD

**Issue by ErdbeerbaerLP** [ldtteam/minecolonies#2295]
### Minecolonies version

version 0.9.7587

### Expected behavior

- Non crashing

### Actual behaviour

- Crashing  
already 5 times in an hour
[crash-2018-03-08_14.57.37-server.txt](https://github.com/Minecolonies/minecolonies/files/1793405/crash-2018-03-08_14.57.37-server.txt)

**Comment by marchermans** [comment]
You seem to have creative resolving enabled in 1.10. Please disable it. It is not supported in 1.10 Since minecraft does not provide a way to get the subitems on the server side only.
