### ISSUE TITLE
Town hall ui crashes game to desktop

### ISSUE THREAD

**Issue by fabbe50** [ldtteam/minecolonies#2296]
### Minecolonies version

version 0.8.7686

### Expected behavior

- Open the town hall UI

### Actual behaviour

- Crashes to desktop
[crash-2018-03-09_03.30.24-client.txt](https://github.com/Minecolonies/minecolonies/files/1795473/crash-2018-03-09_03.30.24-client.txt)

### Steps to reproduce the problem

1. Log into Minecraft
2. Click on the town hall block
3. ...
4. Profit (Crash)

**Comment by Raycoms** [comment]
Fixed in the newest version.
