### ISSUE TITLE
Creepers are exploding within the colony

### ISSUE THREAD

**Issue by lebanni** [ldtteam/minecolonies#2300]
minecolonies-universal-1.12.2-0.8.7719.jar
forge-1.12.2-14.23.2.2624-universal.jar

![2018-03-10_03 22 49](https://user-images.githubusercontent.com/2799575/37237573-2dc03f8c-2415-11e8-9276-8819538225a7.png)
![2018-03-10_03 35 09](https://user-images.githubusercontent.com/2799575/37237574-2ddfd900-2415-11e8-9556-8aa5ceaaf93a.png)

**Comment by Raycoms** [comment]
Can you check if those areas show your colony in f3?
Is this in SMP?
Is this close to the SMP spawn?

**Comment by lebanni** [comment]
The closest blowing was at 82 blocks from the center (the one you see on the 2nd picture), which apparently is considered outside the colony. The visualization line is at 143 blocks from the center in the shortest way. And yes it's in SMP.

**Comment by Wissi** [comment]
@lebanni Could you please update to the latest Alpha and verify if this is still happening to you.
Else this issue will be closed as resolved.
Thank you.

**Comment by lebanni** [comment]
It's seems to work fine now. But I had to start a new world. I'll see when I have guards again. In the meantime I think you can close the issue.
