### ISSUE TITLE
Builder - Oak framed timber frame

### ISSUE THREAD

**Issue by woodytt** [ldtteam/minecolonies#2303]
### Minecolonies version

version 1.12.2-0.8.7719

### Expected behavior

- Request items, add into inventory then go off and build. 

### Actual behaviour

- I currently having a builder build cowboy lvl 3 and needs oak framed timber frame. The request isnt fulfilled by the deliverymen so I have manually placed in his inventory but he is still not registering it. I have tried cancelling request, restarting server etc to no avail. 

![mc issue](https://user-images.githubusercontent.com/37252031/37246632-fab58b66-24a4-11e8-8f76-bcb3501165b6.png)
![mc issue1](https://user-images.githubusercontent.com/37252031/37246633-fc477a8e-24a4-11e8-8689-836b75580a96.png)

**Comment by Raycoms** [comment]
You have to give him exactly the type he wants in the photo of the request.

**Comment by woodytt** [comment]
I have done, he has 2 stacks on him

**Comment by Raycoms** [comment]
Look closely, the two stacks you gave him are slightly different

2018-03-10 21:09 GMT+00:00 woodytt <notifications@github.com>:
