### ISSUE TITLE
[Feature Request] Builder Item Management

### ISSUE THREAD

**Issue by leion247** [ldtteam/minecolonies#2308]
### Minecolonies version being used

version 0.8.7737

### Current behavior

-After items are put into the builders building storage for construction, he only takes the one item he plans to use immediately and doesn't dump unnecessary resources from his personal inventory. Causing him to need to go back and forth from the construction site and his base for more resources.

-The builder typically have items that could be stacked together, but aren't, taking up more space then they should be.

### Requested behaviour

-Once a construction is requested, The builder should dump unnecessary resources for the construction into his base inventory, and pull all resources he needs for the construction, although leaving a line empty for any resources he picks up during upgrade processes, before he starts building. Tools like the shovel, pickaxe, and axe would still always be on him.

-When he need more resources, he goes back to take the rest of the needed items and again dumps unnecessary resources. Then should stack items that aren't all together during this time. Again with a one row of empty space.

-During clearing, he should hold nothing but the tools he will need, with plenty of empty space.

-Maybe even a small importance system were the builder, as in which items he should take into his inventory first when he starts the build. Such as stairs, fences, wood planks and oak, cobble and stone bricks, and doors. With items like shingles, wool, or item frames as least important. That would make sure he takes the right items the first time he leaves his base for construction.
-Another method would be to have him take all the resources he needs for a set of layers from the bottom to the top until his inventory is full, minus the one row.

### Expected results

-The builder will build much quicker and make less trips to his hut for resources, as he'll have what he needs on him.
-Less wasted space in his inventory, as he'll only carry what he needs.

**Comment by Raycoms** [comment]
Closed in favor of similar old issue (Builder has to prefetch)
