### ISSUE TITLE
recipies lacking info

### ISSUE THREAD

**Issue by SulpherStaer** [ldtteam/minecolonies#2310]
### Minecolonies version

version 1.12.2-0.8.7737

### Expected behavior

- a suggested recipe list somewhere, that is teachable to the baker / cook / smelter.

### Actual behaviour

- Not able to teach the baker to make bread, or able to teach the cook how to cook fish. No idea which recipies are available or not.

### Steps to reproduce the problem

1. have baker / cook available
2. attempt to teach recipe (3 wheat, 4 wheat, 2 wheat)

**Comment by Raycoms** [comment]
Neither cook nor baker are able to fulfill recipes automatically.

**Comment by SulpherStaer** [comment]
That doesn't help me.

How does it work? I found the recipies in the git - but I can't teach them. Closing the issue doesn't make it go away. It's not explained in the wiki, or in the patchnotes.

**Comment by Sandriell** [comment]
The baker just needs wheat (3) in their inventory and they will "bake" bread at the bakery. They don't need to be taught a recipe. They will hit the bakery hut block for a bit, then go over to the furnace to pretend to bake it.

**Comment by PoroUsedSnax** [comment]
@sylcai As mentioned, they will not fulfil recipes that **you** teach them currently, only the builder really makes use of that feature as he **requires** the stuff you tell him to craft, the baker will craft bread with wheat (3 per 1) and also cakes, but they will not request mats for the cake, you must provide them manually if you want them.

The cook will cook/provide whatever they have at hand, so if you want them to cook fish you need to make sure they have fish and coal (Or other fuel sources) and they should cook it.
