### ISSUE TITLE
Citizens not requesting food at night.

### ISSUE THREAD

**Issue by nldreyer** [ldtteam/minecolonies#2311]
### Minecolonies version

version 0.8.7719

### Expected behavior

- Citizens request food at night when hungry.

### Actual behaviour

- Citizens return to their houses at night hungry and do not request food.

### Steps to reproduce the problem (THIS IS SMP, I have access to all server files if requested)

1. Create colony
2. Make builder hut
3. Have builder make Deliveryman building
3. Have builder make houses
4. Assign people jobs to lose saturation (Any job, I have a miner, baker, chickenherder, farmer, deliveryman, and builder)
5. During night time wait for them to return to their houses and request food
6. Witness there are no food requests

**Comment by Justen-N** [comment]
Do you  have a cook?

**Comment by marchermans** [comment]
Citizens are sleeping at night. So yes they do not request food at night, seems very logical to me. The better question would be: Why are they not getting food during the day? Do you have a restaurant?

**Comment by Sandriell** [comment]
To be fair, the wiki does say they request food at night.

**Comment by marchermans** [comment]
But they do not. That is a bug in the Wiki. It was previously like that when their AI was still running during the night. But since they started sleeping in their beds their AI is disabled. TBH having them request food while they are sleeping seems a bit off to me.

**Comment by Raycoms** [comment]
@PoroUsedSnax can you take care of that?

**Comment by PoroUsedSnax** [comment]
Yes, I'll see what I can do with that, it would be in the new wiki anyways but I'll make a note of it in the old one.

**Comment by nldreyer** [comment]
@PoroUsedSnax Is this new wiki reachable to anyone, on the wiki.minecolonies.com domain, or is it something that will be released in the future? I'm not sure if I just don't have enough deliverymen but even after building the restaurant they still aren't getting food. I have a colony of 15 with 3 deliverymen. Should I be able to see food requests from the clipboard? Are the citizens supposed to go into the restaurant during the day?

**Comment by PoroUsedSnax** [comment]
The new wiki isn't currently reachable for the general public, just editors, your deliveryman should be delivering food to the restaurant for the cook to be cooking/distributing, if not then yes, you should see a request for food from the cook
