### ISSUE TITLE
Dark Oak Mine miner getting stuck in mine.

### ISSUE THREAD

**Issue by nldreyer** [ldtteam/minecolonies#2312]
### Minecolonies version

version 0.8.7719

### Expected behavior

- Miner does not fall into inescapable areas.

### Actual behaviour

- Miner starts placing oak slabs and falls into center of mine.

### Steps to reproduce the problem (THIS IS SMP, I have access to all server files if requested)

1. Create Dark Oak Mine
2. Assign miner and wait for them to mine down
3. When placing oak slabs to separate into different layers miner falls into center area

**Comment by Raycoms** [comment]
I this dark oak medieval or dark oak normal?

**Comment by Raycoms** [comment]
I fixed that, will upload it with the next schematic upload scan.

**Comment by MineShadow7** [comment]
Should we close this if the problem was fixed?

**Comment by Nightenom** [comment]
We should

**Comment by Nightenom** [comment]
@Raycoms is it already done?

**Comment by Raycoms** [comment]
Should be fixed
