### ISSUE TITLE
Second Guard Tower Destroyed When Upgrading to Wooden Barracks 3

### ISSUE THREAD

**Issue by nldreyer** [ldtteam/minecolonies#2313]
### Minecolonies version

version 0.8.7719

### Expected behavior

- Guard tower to remain just like the first guard tower does.

### Actual behaviour

- Guard Tower level 1 destroyed when upgrading wooden barracks 2 to level 3.

### Steps to reproduce the problem

1. Build Wooden Barracks
2. Build first Guard Tower
3. Upgrade Barracks to level 2
4. Build second Guard Tower
5. Upgrade Barracks to level 3

**Comment by WPaul15** [comment]
I encountered this as well with version 0.8.7996 using the Taiga schematics. This may or may not be intended; I can't be sure. However, the tower block itself isn't destroyed, so you can still have the guards.

**Comment by marchermans** [comment]
@Asherslab will something like this be fixed in the new Guard System you are working on, or would the builder Need to be changed for that?

**Comment by Asherslab** [comment]
@OrionDevelopment Yessss, completely new Guard Tower placement system in the new Guards rework

**Comment by Raycoms** [comment]
Should be fixed, else duplicate, we will rework the placement of the chests completely.
