### ISSUE TITLE
Barbarians attacking other colony

### ISSUE THREAD

**Issue by randomlypickedname** [ldtteam/minecolonies#2314]
### Minecolonies version

version 0.8.7582

### Expected behavior

- When raider message appears, I expect raiders to appear in one of their spawn spots outside the village.

### Actual behaviour

- When raider message appears, raiders attack a fellow player's colony. They spawn in the middle of the village and start ransacking everything before the player has time to react, and haven't even been set up long enough to deal with the raiders they're getting.

### Steps to reproduce the problem

(This is only a guess, I can't confirm this is actually what happened)
1. Player adds other /op'd player (me) as officer to troubleshoot (Optionally: Removed myself after, still happens. I receive raider messages and scan all floors of my town and find no barbarians, when I go check the other player's town they're all over.)
2. Player randomly experiences raids without seeing raid message; I get raider messages without getting raiders.
3. ...
4. Profit

I learned about /mc colony addOfficer <ID> after, but regardless, the player has barely started and has citizens dying left and right to them (with a non-working death message), and they spawn there even with the player offline.

**Comment by Raycoms** [comment]
Is it possible that the raid message appeared quite some time before that and then after a few nights they actually started appearing?

**Comment by randomlypickedname** [comment]
It would occur right after I received the message. I'm thinking it might involve having to replace their town hall for them at one point to fix an issue, but I haven't tested more since I've reported it.

**Comment by Wissi** [comment]
@randomlypickedname can you please upgrade to the latest alpha version and report back if that actually happens again and if you have tested it further?
Else it will be closed as has not been reported elsewhere.
thanks.

**Comment by Raycoms** [comment]
Should be fixed already.
