### ISSUE TITLE
Loading chunk console spam

### ISSUE THREAD

**Issue by MrSkittlesROTR** [ldtteam/minecolonies#2322]
### Minecolonies version

minecolonies-universal-1.12.2-0.8.7809.jar

### Expected behavior

- clear console

### Actual behaviour

- see screen shot.
https://puu.sh/zK7qX/ac4f9d18bf.png

### Steps to reproduce the problem

1.install latest

**Comment by Raycoms** [comment]
Should be removed in the newest one.
