### ISSUE TITLE
[1.12.2] Citizens are invisible 

### ISSUE THREAD

**Issue by YaibaToKen** [ldtteam/minecolonies#2328]
### Minecolonies version

version 0.8.7582

### Expected behavior

- Citizens spawn, be visible and hopefully do stuff

### Actual behaviour

- Can't see or interact with citizens

### Steps to reproduce the problem

1. Create a world
2. Create a colony
3. Create a supply camp
4. Create a town hall
5. Create a builder
6. Profit

![image](https://user-images.githubusercontent.com/9133736/37676663-6e455c0a-2c70-11e8-8326-a6394a2dfb6d.png)

As you can see in the picture, I'm at the coords shown by the /mc citizens list command, yet none of the citizens are there/visible/interactable

**Comment by Raycoms** [comment]
Shoild be fixed now.
