### ISSUE TITLE
Custom hut upgrade crashes client to desktop

### ISSUE THREAD

**Issue by BonaireDreams** [ldtteam/minecolonies#2330]
### Minecolonies version

version 1.12.2-0.8.7855 also 0.8.7737

### Expected behavior

- Upgrade custom citizen hut to LVL 2

### Actual behaviour

- Client crashes to desktop, server is fine.

### Steps to reproduce the problem

1. Dedicated Server running Colonial Engineers
2. Mod pack has some custom building schematics
3. Built a T1 custom citizen hut, all 5 tiers are available to preview before placing
4. When trying to upgrade to T2, client crashes to desktop after clicking Upgrade, right before the materials list is displayed.
5. Minecolonies huts upgrade fine so I'm pretty sure its the custom hut but looking for some direction what could  be causing it and how I can fix it. Would it be an invalid block in the schematic?

[crash-2018-03-20_22.14.13-client.txt](https://github.com/Minecolonies/minecolonies/files/1834044/crash-2018-03-20_22.14.13-client.txt)

**Comment by mkienenb** [comment]
Note, this is the first time I've looked at this part of the code....

According to the java code for the stack trace, the template for the structure is null (missing).
Did you see something in the logs along the lines of "Failed to load template %s"?

Hope this helps.

**Comment by BonaireDreams** [comment]
Dug through the startup logs. Couldn't find any error, only confirmation that it loaded the extra schematics.
[04:11:36] [Server thread/INFO] [minecolonies]: Load huts or decorations from jar
[04:11:38] [Server thread/INFO] [minecolonies]: Load additionnal huts or decorations from ./Bonaire/minecolonies/schematics
[04:11:38] [Server thread/INFO] [minecolonies]: Load cached schematic from ./Bonaire/minecolonies/cache
[04:11:38] [Server thread/INFO] [minecolonies]: Finished discovering saplings
[04:11:38] [Server thread/INFO] [minecolonies]: Finished discovering ores

**Comment by BonaireDreams** [comment]
No longer happens as of 0.8.8068
