### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by CharCharthemonkey** [ldtteam/minecolonies#2331]
### Minecolonies version
1.12.2 0.8.7737
version X.X.XXXX or curse X.X.XX

### Expected behavior
to pick up items 
- XXX

### Actual behaviour
ignores like half the items dropped was told by wissi to add this so pretty plz consider?
- YYY

### Steps to reproduce the problem

1. XYZ
2. ZYX
3. ...
4. Profit

**Comment by Asherslab** [comment]
This is too non-descript. create a new, more descriptive issue
