### ISSUE TITLE
NBT agian ...: Tried to read NBT tag that was too big; tried to allocate: 2097153bytes where max allowed: 2097152

### ISSUE THREAD

**Issue by robbcrg** [ldtteam/minecolonies#2333]
### Minecolonies version

version minecolonies-universal-1.12.2-0.8.7875

### Expected behavior

- The client log does not fill with the error with a coresponding jump in CPU to 100+%

Error executing task
[B#355]  java.util.concurrent.ExecutionException: java.lang.RuntimeException: Tried to read NBT tag that was too big; tried to allocate: 2097153bytes where max allowed: 2097152

### Actual behavior

- Game lags and log fills with NBT errors
- This happens even when out of chunk range (tested to out of about 200) and no chunk loading active

### Steps to reproduce the problem

1. Just happens after a few minutes of playing
2.  Town is modestly size, 40 citizens

See also:
#2188 

I placed the colony dat file on my public DropBox. There are two colonies but the second is very very small. I tried to tweak the request system NBT data but I goofed and broke all requests. The file attached is the original. 

https://www.dropbox.com/s/d63fn7idnkzhcty/colony2.dat?dl=0

**Comment by Raycoms** [comment]
Please upgrade to a new version and run /mc colony rs reset
