### ISSUE TITLE
03/26/2018 Game Breaking Bug

### ISSUE THREAD

**Issue by mjrekich** [ldtteam/minecolonies#2347]
### Minecolonies version

version: minecolonies-universal-1.12.2-0.8.4191

### Expected behavior

- Put down town hall, town hall erects :)

### Actual behaviour

- Game goes poop

### Steps to reproduce the problem

1. Put down town hall
2. Hail satan
3. ...
4. Eternal bliss

Seriously though, it is a game breaking bug for 1.12.2. Seems to work on other versions but not this one. Unless there is a new update coming out soon, I would highly recommend fixing this. Great mod by the way. I loved Millenaire and I think this is a better rendition of how a village works. Keep up the excellent work :)

**Comment by Justen-N** [comment]
The release is about 3000 builds behind. Update to the alpha and this issue
is fixed.

**Comment by mjrekich** [comment]
What do you mean the alpha? Like the game version, forge or minecolonies?

**Comment by Justen-N** [comment]
Minecolonies alpha build.  It is available on the curseforge page.

**Comment by mjrekich** [comment]
Bless your soul, you wonderful man
