### ISSUE TITLE
Miner does not replace broken Tinker's Construct pickaxe

### ISSUE THREAD

**Issue by Oraxian** [ldtteam/minecolonies#2348]
### Minecolonies version

version 1.12.2-0.8.7949 (issue has existed since at least 1.12.2-0.8.5081)

### Expected behavior

When a Tinker's Construct pickaxe becomes "broken" (no durability,) the miner should request a new pickaxe

### Actual behaviour

Sometimes (about 25%-50% of the time?) the miner continues to work with the broken tool, instead of requesting a new one.  He's not just waiting forever at his building, like if the request was bugged - he goes down into the mine and works.

See attached picture
![2018-03-27_08 14 22](https://user-images.githubusercontent.com/37782499/37970617-89d75b70-3199-11e8-8d13-899680f09844.png)

### Steps to reproduce the problem

I have been unable to find a single trigger for this issue, and it's intermittent.  This is what I do know:

* The issue does not happen with vanilla pickaxes
* The lumberjack and builders do not have this issue with their Tinker's tools that I have observered
* The miner has not had this issue with a Tinker's shovel or axe, although they go through less of those
* If the broken pickaxe is taken from the miner's inventory, he correctly issues a request for a new pickaxe
* I've observed this behavior on at least 6 different miners, so I don't think this is due to a bugged citizen

**Comment by Wissi** [comment]
Yes unfortunately Tinker's tools don't dissapear or stop working when they go to "broken" status.
Part of the compatibility w/Tinker's tools should make the Broken state be treated as no tool/new tool required?

**Comment by Raycoms** [comment]
this shouldn't be an issue anymore
