### ISSUE TITLE
[1.12.2] [0.8.7902] Pathfinding issues with Quark Walls

### ISSUE THREAD

**Issue by Sandriell** [ldtteam/minecolonies#2349]
### Minecolonies version

0.8.7902

### Expected behavior

Not constantly jumping trying to get on top of walls.

### Actual behaviour

Constantly jumping trying to get on top of walls.

### Steps to reproduce the problem

1. Have Quark
2. Place wall
3. ...
4. Profit

This is due to Quark not extending BlockWall and instead using its own class BlockQuarkWall for all its walls. Based on my own limited knowledge I would think adding a check for that in AbstractPathJob.java like below is what it needed, but I doubt it is as simple as that. lol

```
protected SurfaceType isWalkableSurface(@NotNull final IBlockState blockState)
    {
        final Block block = blockState.getBlock();
        if (block instanceof BlockFence
              || block instanceof BlockFenceGate
              || block instanceof BlockWall
              || block instanceof BlockQuarkWall
              || block instanceof BlockHutField)
        {
            return SurfaceType.NOT_PASSABLE;
        }

```

**Comment by Raycoms** [comment]
fixed
