### ISSUE TITLE
[1.12.2] Builder sometimes fails to use basement Chests

### ISSUE THREAD

**Issue by Skip21** [ldtteam/minecolonies#2350]
### Minecolonies version

version 0.8.7934

### Expected behavior

- Place Items in Basement Chests when Upper one is full

### Actual behaviour

- Keep on asking for a player to empty his upper chest even when Basement ones are empty

### Steps to reproduce the problem

Since it doesn't happen every time - got 2 Builders : one using them and the other not - i will try my best to reproduce

1. Get a Builder's Hut level 2 or More
2. Fill its upper chest and the Builder inventory with random stuff
3. Wait for him to try to empty its inventory

**Comment by Raycoms** [comment]
Please reopen if still an issue, shouldn't be anymore.
