### ISSUE TITLE
Citizens spawning on top of their bed, getting stuck (Noticed in medieval citizens hut level 2)

### ISSUE THREAD

**Issue by PoroUsedSnax** [ldtteam/minecolonies#2351]
### Minecolonies version

version 0.8.7934

### Expected behavior

- Citizens wake up in places where they are able to continue their work

### Actual behaviour

- In the medieval citizens huts (level 2 at least) when the citizens wake up they spawn on top of the bed, meaning they get stuck there in the roof, I'm presuming this is more of a general issue as to where they spawn than a problem with medieval, but I may be wrong.

![2018-03-29_04 29 26](https://user-images.githubusercontent.com/19329455/38068746-b45318f4-330a-11e8-95c2-e852b94d9521.png)

### Steps to reproduce the problem

1. Build medieval citizens hut (Level 2)
2. Wait for the citizens to sleep and wake up
3. ...
4. Profit

**Comment by marchermans** [comment]
I was sure this was fixed....

**Comment by carlansor** [comment]
i can change stairs for slabs, if that works

**Comment by PoroUsedSnax** [comment]
I think it's worth the issue being solved over changing the design. But it's a decent quick fix if it works, not sure if it's them getting stuck because of the lower section of stair, or the block in general.

**Comment by marchermans** [comment]
So I checked. I use the MC bed code to wake up citizens, so unless you can sleep in that bed without getting your head stuck and being teleported out this issue is a design flaw in the building and not something I can solve.

**Comment by carlansor** [comment]
dont worry then, i will modify the design in a moment.

**Comment by PoroUsedSnax** [comment]
In that case, I believe the town hall could also do with modifications, as the beds upstairs (Level 3 at least) The citizens wake up inside some stairs which lead up to a tower, so it isn't as simple to fix from a user stand point.

**Comment by spacewolfcub** [comment]
Medieval CitizenHut levels 2 and 4: flaw still exists. 
Issue reported just now by Charlie, screenshots taken by me of the problem areas.

[https://cdn.discordapp.com/attachments/372217492547829762/542932723019284510/unknown.png](url)
[https://cdn.discordapp.com/attachments/372217492547829762/542934146843148303/unknown.png](url)

**Comment by carlansor** [comment]
will look into it :)
