### ISSUE TITLE
Multiblock needs localization.

### ISSUE THREAD

**Issue by Wissi** [ldtteam/minecolonies#2355]
![multiblock](https://user-images.githubusercontent.com/23312242/38166776-168efae8-34ef-11e8-9df6-3cbfd074f8c5.png)

**Comment by Sandriell** [comment]
Kind of tough to think of a good name for it.

**Comment by Wissi** [comment]
Gate/Door Block ?

**Comment by Sandriell** [comment]
It's also a drawbridge.

**Comment by MineShadow7** [comment]
Something like piston engine 'cause it moves blocks (I guess).

**Comment by carlansor** [comment]
what about contraptor? (not really know what is a contraptor, just like the word)

**Comment by Asherslab** [comment]
Isn't this fixed now?
