### ISSUE TITLE
PigFarmer not listed / No Scrollbar Jobs list

### ISSUE THREAD

**Issue by SulpherStaer** [ldtteam/minecolonies#2359]
### Minecolonies version

version 1.12.2-0.8.7996

### Expected behavior

- All working citizens are listed.

### Actual behaviour

- List is truncated when it exceeds the panel height

### Steps to reproduce the problem

1. Have a colony that has at least 1 of every working job offering building
2. observe the list in the town hall and notice not all jobs are listed
![2018-04-03](https://user-images.githubusercontent.com/5037244/38256518-cc45e42a-375e-11e8-828e-f968db0a4a3a.png)

**Comment by Wissi** [comment]
When there are more workers than can be shown on the TH GUI Information tab page. 
1. Maybe add a scrollbar or 
2. Change information from pg. 1 and 2 and add a pg. 3 to continue showing the rest of the Workers.
Will be necessary as more Worker types are implemented.

**Comment by Nightenom** [comment]
Closed in #2527
