### ISSUE TITLE
Spawn egg required for building upgrade

### ISSUE THREAD

**Issue by snoopydude48** [ldtteam/minecolonies#2360]
minecolonies-universal-1.12.2-0.8.7855

The upgrade from level 1 to 2 includes a pig spawn egg
![2018-04-04_12 55 42](https://user-images.githubusercontent.com/8415887/38322320-0cec550a-3808-11e8-8b1c-c51de908179a.png)

It some how used the egg in the upgrade.

**Comment by carlansor** [comment]
will fix that asap.

**Comment by Asherslab** [comment]
Is this fixed now?

**Comment by Arystina** [comment]
Doesn't seem like it. I was just about to report the same issue and I am playing the latest version of Minecolonies. My Smeltery guy wants a cow egg for some reason at the lvl 4 upgrade. At this time I guess if you are playing singleplayer, just grab the spawn egg in creative mode.

**Comment by carlansor** [comment]
i just gave the fixed schem to Raycoms. The fix will be included in latest alpha. @Arystina what style are you using with the smeltery? if its one the medievals, wich one?

**Comment by Arystina** [comment]
Taiga.

**Comment by Arystina** [comment]
Sorry. It's the 'wooden' one.

**Comment by Raycoms** [comment]
Should be fixed by now
