### ISSUE TITLE
[Question] Saveing biger schematics

### ISSUE THREAD

**Issue by EnnekPL** [ldtteam/minecolonies#2362]
### Minecolonies version

version 1.10.2
It's possibile to make biger schematics than maximum allowed? now is 32763 bytes.
I want to make f.e. schematic scan of big castle.

**Comment by Justen-N** [comment]
At the moment, no. However, this feature is available on the 1.12.2.
version, it just isn't backported.

**Comment by EnnekPL** [comment]
ok ty for reply :)

**Comment by EnnekPL** [comment]
btw. I backported this feature  to 1.10.2 on my owne

**Comment by Sandriell** [comment]
Should do a pull request then.
