### ISSUE TITLE
Guards Attack the Player [1.12.2]

### ISSUE THREAD

**Issue by WPaul15** [ldtteam/minecolonies#2365]
### Minecolonies Version
- 1.12.2-0.8.8008

### Forge Version
- 14.23.2.651

### Issue
Oftentimes, during a Barbarian raid, I will set several Guards to "Follow" so that I can pull them over to face the oncoming horde. Naturally, once combat ensues, I may be forced to use my sword to attack. The problem is that my Guards do the same. They rush up to attack the Barbarians, and as I'm frantically trying to not die, I may accidentally hit a Guard when I sweep with my sword (which is the default attack as of Minecraft 1.9). This makes the Guard stop attacking Barbarians and start attacking me! I've probably been killed by my own Guards as often as I have been killed by Barbarians, which, during a Barbarian raid, is very annoying. The Barbarians are tough enough; I shouldn't have to worry about my Guards also turning on me.

### Similar Issues Logged
I know that this issue has been addressed before, but despite that, I haven't found a solution.
- #2060 @Raycoms responded to the post with, "Running away for a minute should fix that as well," and closed the issue. This is somewhat true. I tested this by punching a Guard in the daytime. She chased me, but after I got far enough away, she went back to her post. But when I came close again, she started running towards me. Exiting to the main menu and reopening the world reset the behavior, but essentially, I would assume that I would have to stay away from her until I reloaded the world or until she started fighting something else. During a Barbarian raid, however, this is very inconvenient.
- #1828 This is more related to servers; I'm on single-player.
- #1119 The chat in this issue talks about a "Fight Guards" permission. However, a picture posted in the chat shows the old Town Hall GUI. I can't find this permission anywhere in the new Town Hall GUI (see below), it's not a config option, and I don't know if there's a specific file for saved permissions where I could edit a value outside the game. In other words, I don't know if this is still available. If it is, let me know how I can change it and you can close this issue.

![2018-04-07_12 06 43](https://user-images.githubusercontent.com/16868897/38453820-17a4f6d6-3a5c-11e8-96c1-05a57acec750.png)

### Proposed Change
- Disable or prevent Guard aggression towards players, or at least towards the colony owner. (I'm assuming Guards are set to attack anything that attacks them. I could be wrong.)

### Steps to Reproduce the Issue
1. Hit a Guard

### Note
This is not a game-breaking issue. It may even be the case that this is an intended feature to make gameplay more difficult. If this is the case, then let me know and close the issue.

**Comment by BonaireDreams** [comment]
I hate this as well. You're in the midst of fighting a bunch of barbarians, accidentally hit a guard and then they switch to you. They never forgive you either. If you run away they do stop chasing you, but as soon as you are in range again they attack you. Only option left is to kill them which reduces happiness.

**Comment by Raycoms** [comment]
@Asherslab is working on the guards atm, he can code them to be a bit more forgiving =P

**Comment by Asherslab** [comment]
@Raycoms i can and i will =P
how forgiving would you like? 
On a scale of Canadian to North Korea

**Comment by Raycoms** [comment]
Just one hit back is okay

**Comment by Kisonu** [comment]
to anyone having this issue, i have noticed that removing and replacing the attacking guards weapon also resets this behavior. Might help to prevent you from having to flee your colony for an extended time or close your world to reset it.

**Comment by desagas** [comment]
At least in the mean time, on a server play, logging out and back in seemed to fix the problem. But, it has only been 15 minutes since the accidental attack happened.

**Comment by Wissi** [comment]
@Asherslab have you made them more "foregiving" can we close this Issue as resolved?

**Comment by Raycoms** [comment]
Fixed that recently, running away for a bit will let them rethink

**Comment by kualajimbo** [comment]
I found a temporary fix for this. After facing this issue, I escaped into the Nether, and when I returned my guard no longer attacked me.

**Comment by pwaksman973** [comment]
Have to say, it still a pain as is until today, anything attacking the village if you go near to "help" and your swing hits the guards, they instantly turn to you. Can't we have like a friendly fire settings so we could just turn off

**Comment by MotionlessTrain** [comment]
There is a permission setting whether a user role can damage citizens nowadays.

**Comment by pwaksman973** [comment]
O yah it does work, thans for the tip.
But it is misleading as hell. Fight Guards is off, but you have to turn off "Attack citizens", then there is also hurt citizens and other that just make it even hard to know what is what.

Now need to find where to disable the "warning message" "you do not have permission to do this in this colony"... hope there is a config for it
