### ISSUE TITLE
Client crash while placing supply ship on or near water

### ISSUE THREAD

**Issue by kreezxil** [ldtteam/minecolonies#2367]
### Minecolonies version

1.12.2-0.8.8021

### Expected behavior

- Place supply ship and receive ingame message about not being able to place it or have it actually place

### Actual behaviour

- client crash

### Steps to reproduce the problem

1. place supply ship on water block itself

https://pastebin.com/BPRZGWyi

In this next one, the player built a pier out into the body of water and placed the supply ship on the last block of the pier.

https://pastebin.com/7Dwv86dx

same steps

### Screenshot of area where this was being done
![screenshot](https://cdn.discordapp.com/attachments/396850544678797323/432631305625272330/2018-04-08_22.01.30.png)

**Comment by marchermans** [comment]
Update your client. Hotfix was pushed this afternoon. Hope you have a nice evening 🙂
