### ISSUE TITLE
Building tool is non functional on smp

### ISSUE THREAD

**Issue by Relgub** [ldtteam/minecolonies#2368]
### Minecolonies version

version 1.10.2-0.9.7587

### Expected behavior

- preview and placement of building schematics

### Actual behaviour

- Nothing... the menu pops up but their are no selectable options and the preview does not paste. I do see the movement arrows and blank text blocks. I have tried with every building in hand but it's all the same in creative and survival. Everything works properly in ssp.  I am playing with a larger number of mods (Candyland Survival in curse), but it worked fine in previous versions and as I said before it does work in ssp.

### Steps to reproduce the problem

1. join server
2. place building and building tool in inventory bar
3. click ground with building tool
4. ...

**Comment by marchermans** [comment]
Please update to the newest version of minecolonies.

**Comment by Relgub** [comment]
I'm on the most current version for mc1.10.2 in curse.  Unless you mean to update to mc1.12?

**Comment by marchermans** [comment]
Oh @Raycoms in that case 😅

**Comment by Raycoms** [comment]
Yeah we need to re-port the 1.12 version to 1.11 and 1.10. But for now we don't really have time for that
