### ISSUE TITLE
Save & Load times and Save File size.

### ISSUE THREAD

**Issue by WonderDog** [ldtteam/minecolonies#2376]
### Minecolonies version

MineColonies - 1.12.2-0.8.8053 
in Modpack ATM3 - 5.8, 5.9.1 & 5.9.2

In Single Player

### Expected behavior

Game Loading time & File Size to be stable.

### Actual behaviour

Loading time and size of the minecolonies save folder increase dependent on the number of times the world is loaded.

See [Save / Load Times in Single Player from Minecolonies (and Save Bloat)](https://github.com/AllTheMods/ATM-3/issues/485) for further info.

### Steps to reproduce the problem

Using NBT Explorer I notice that the problem is in **Compatibility Manager** / **Tag Saplings** which  grows geometrically

In Quick test game where I have 3 backups I have the number of **TagSapling** entries : 0 (On World Creation), 339, 603, 1395.  Compare to **TagOre** 0, 84, 84, 84 and **TagSapLeaves** with 0, 0, 0, 0

I just downloaded another instance of ATM3 v 5.9.3 without optifine and made no changes to any settings / config. 

I created a new default world and exited after a minute and checked _colonies.dat_ in NBT explorer.  Did that three times and the number of entries of **TagSapling** 339, 867, 1923

My original save under 5.9.2 from last week has 65099 entries and takes about 45 seconds to open in NBT explorer from a SSD and the game takes longer to load / save than to start All the Mods 3 from the twitch launcher.

**Comment by Raycoms** [comment]
Hey, can you tell me which mods you have which add trees?

**Comment by Raycoms** [comment]
And can you send us one of these files?

**Comment by WonderDog** [comment]
Here is the Mincolonies folder from an older game as it has a good history showing the behaviour.
[minecolonies.zip](https://github.com/Minecolonies/minecolonies/files/1911442/minecolonies.zip)

I seem to deleted the test game from yesterday.  I can run it again as it only takes a few minutes if you want. New game and load/save a few times.

I think the mods adding trees are Biome's o Plenty, Natura, Terraqueous, Binnies, Forestery & Traverse
[Mod List.txt](https://github.com/Minecolonies/minecolonies/files/1911443/Mod.List.txt)

**Comment by WonderDog** [comment]
I created a new instance of ATM3 5v9.3 and made no changes.  [CT Mod List.txt](https://github.com/Minecolonies/minecolonies/files/1911496/Mod.List.txt)

Created a new creative game Flat World, Overword preset.  Flat World, default preset does not cause the error.  [Minecolonies Tester.zip](https://github.com/Minecolonies/minecolonies/files/1911497/minecolonies.Tester.zip)

Notice how each backup zip is nearly double in size.

Here is a list of all the saplings that are in the CraftTweaker oredict list.  [CT Oredict Sapling.txt](https://github.com/Minecolonies/minecolonies/files/1911499/Oredict.Sapling.txt)

Is it safe to delete the archive zips from the saves as in my last play through, I had pages of zip files in my saves/minecolony folder.

**Comment by Raycoms** [comment]
I'm looking over the data atm, and I'm noticing that forestry has some amazingly complicated saplings with chromosomes etc, might there exist an almost infinite amount of saplings for forestry?

**Comment by Justen-N** [comment]
Well, kind of. You have to breed for each set of chromosomes, so that
shouldn't  be affecting the save file. I think the is in the sapling
registry code. It should run once on startup, overriding the current file,
and that's it.

**Comment by Justen-N** [comment]
Honestly, yeah, I think we aren't overwriting the file, it just reregisters
every startup.

**Comment by WonderDog** [comment]
Its probably not noticeable on a server as you rarely shut it down but in single player I probably load the game between 5 - 20 times a week.

**Comment by Raycoms** [comment]
https://s3.eu-central-1.amazonaws.com/minecolonies/Minecolonies/Minecolonies_Branches/8096/minecolonies-universal-1.12.2-0.8.8096.jar

Can you check if this jar fixes it?

**Comment by WonderDog** [comment]
Great looks to be fixed.  76 entries over multiple reloads.

[atm3 testing](https://user-images.githubusercontent.com/8510324/38774081-831d06d2-40a2-11e8-8606-0f23857c70eb.JPG)
