### ISSUE TITLE
Minecolony Keeps Crashing as soon as I place the town hall

### ISSUE THREAD

**Issue by DeadDJButterflies** [ldtteam/minecolonies#2380]
Minecolonies version

version 1.12.2

Expected behavior

- To run smoothly without error or complication when placing blocks

Actual behaviour

- After placing the town hall block, the game crashes and wont open again

Steps to reproduce the problem

1. Open new game (in whatever setting)
2. Open inventory or craft a town hall
3. Place town hall on any block

**Comment by Justen-N** [comment]
This is fixed in the alpha build on curse.  Please upgrade to it. Also,
please submit the Minecolonies version, not the Minecraft  version.
