### ISSUE TITLE
No Build Preview When Using Shaders

### ISSUE THREAD

**Issue by NuL1F3** [ldtteam/minecolonies#2381]
### Minecolonies version

version 1.12.2-0.8.8095

### Expected behavior

-Should show build preview when placing build huts with the building tool

### Actual behaviour

- No build preview

### Steps to reproduce the problem

I am using the latest Sildur's shader and since a recent mod update I can no longer see build previews whilst using it.

**Comment by marchermans** [comment]
Yep, certain shaders do not respect Minecrafts default block format. Sorry there is nothing we can do.

**Comment by NuL1F3** [comment]
I have used these shaders since the start and have never had a problem. It was only since one of the latest minecolonies updates that it stopped working. So how is that not a minecolonies issue?
