### ISSUE TITLE
No Build Preview When Using Shaders.

### ISSUE THREAD

**Issue by NuL1F3** [ldtteam/minecolonies#2382]
### Minecolonies version

version 1.12.2-0.8.8095

### Expected behavior

- Should show build preview when placing build huts with the building tool.

### Actual behaviour

- No build preview.

### Steps to reproduce the problem

I am using shaders and since a recent mod update, I can no longer see build previews whilst using it. I have gone back to version 1.12.2-0.8.8008 and previews are working perfectly with shaders.

Previous created issue closed for reason of blaming the shaders themselves but clearly if I revert to an earlier minecolonies version and build preview is visible again, then the issue is not with the shader.

The version update after 8008 (8021) in it's changelog mentions using VBO to render structures and since build previews with shaders fail with this and further versions I am guessing that is the cause of the issue.

Please don't just close this issue until it has been properly looked into.

**Comment by Raycoms** [comment]
We rewrote the system using vbos like Minecraft does for its world
rendering, so the bug for the rendering is on the shaders side probably

**Comment by NuL1F3** [comment]
That is unfortunate.

**Comment by marchermans** [comment]
Yeah a lot of shaders (optifine is a good example) do not respect MCs default vertex ordering and data, they pick what they need and be done with it.
