### ISSUE TITLE
Bug: custom schematics not build

### ISSUE THREAD

**Issue by matthijsthoolen** [ldtteam/minecolonies#2383]
### Minecolonies version

version 1.12.2-0.8.8095

### Expected behavior

- Build the custom schematic

### Actual behaviour

- The building tape is placed. But builders won't start building

### Steps to reproduce the problem

1. Upgrade to version 8095 (7972 just works fine)
2. Build a custom schematic somewhere within the city limits
3. I did not get the message 'Succesfully send' but a friend did.
4. Multitple free (and even lvl 5 builders) are availble
5. Nothing happens. Upgrading or building a normal building does work. 
6. Downgrade to 7972, builders will instantly start building the custom schematic. 

Thanks!

**Comment by Raycoms** [comment]
Should be fixed
