### ISSUE TITLE
[Bug?] [Suggestion] Barbarians receive speed buff.

### ISSUE THREAD

**Issue by BonaireDreams** [ldtteam/minecolonies#2384]
Minecolonies version

version 0.8.8068

Expected behavior

Barbarians don't receive SPEED Buff

Actual behaviour

Barbarians do receive Speed Buff and they are crazy fast. Not sure if caused by Minecraft grass pathways, and Totemic Horse Totemes (Speed) (from Totemic Mod, gives a 13x13 area speed boost)

Steps to reproduce the problem

1. Have Large Village
2. Add grass pathways and Totemic Speed Totems to get around town quicker.
3. Wait for Horde
4. Try to catch up to the barbarians as their speed buff seems to be faster than yours even if you double tap to run.

Would be nice if barbarians are not subject to the speed buffs. Normal citizens do not receive them so the horde can chase down and kill everyone before you have a chance to catch them. If intended, perhaps lower the amount they receive to a more manageable level.

**Comment by Raycoms** [comment]
Actually, hordes usually have a 30-60 second speed buff shortly after
spawning to allow them to get to town quicker.
Since Barbarians are mobs and citizen passive npcs, they react differently
to the speed buffs. Although it's strange citizens do not get a speed buff
from the Totems.

2018-04-15 19:49 GMT+01:00 Gerald <notifications@github.com>:

**Comment by BonaireDreams** [comment]
Interesting, I'll monitor the barbarians more closely to see if they are actually receiving the buff or if this was residual speed buff left over spawn. It seems this horde spawned maybe 20 blocks away from my townhall and not outside the town boundaries. I received the "Buckle your seatbelts" warning and within 20 seconds, 3 of my citizens were already dead and the horde was in the center of town. So perhaps they just spawned closer than normal and still had their initial buffs. It was too much of a crazy panic killing them to try and figure out why they were moving so fast. LOL Will keep my eye on the next few hordes and report back.
