### ISSUE TITLE
Herders don't get any experience

### ISSUE THREAD

**Issue by osechet** [ldtteam/minecolonies#2386]
### Minecolonies version

version 1.12.2 or curse X.X.XX

### Expected behavior

- Herders should get experience working with their animals.

### Actual behaviour

- Herders experience stays at 0.

### Steps to reproduce the problem

1. Build any of the herders hut (tested with chicken, sheep and cow)
2. Give the proper tools and food
3. Bring some animals inside the fences
4. Let the herder works
5. Check the experience after a while. It remains at 0.

**Comment by MokahTGS** [comment]
It's not just herders.  My builder doesn't seem to be gaining exp either.

**Comment by GregPatience** [comment]
Note also that it makes no difference what level the building is or if the worker has an intelligence stat higher than 1 (I thought that might affect it).  I have a level 5 dairy farm with the same issue as described above.

**Comment by bob0bob** [comment]
None of the new herders get experience.

They left out the line 

worker.getCitizenExperienceHandler().setSkillModifier(2 * worker.getCitizenData().getEndurance() + worker.getCitizenData().getCharisma());


in the herder code.  Of course it would change based on the primary skill/secondary skill for skill Modifier.  Right now it is set to 0.   Not experience for any of them.

Just need to add the line of code in AbstractEntityAIHerder or each class of the herders and it will start working.   2 second fix.

**Comment by bob0bob** [comment]
I've submitted a fix for this issue.
