### ISSUE TITLE
Weirdness after crashing

### ISSUE THREAD

**Issue by MaddysinLeigh** [ldtteam/minecolonies#2387]
Three times after my game crashed and I went back in my colonists have disappeared and the building chests no longer work. All the buildings and construction is still there but I have to delete the chests and start all over, which wouldn't be a problem for me if I hadn't already upgraded most of buildings to the third or fourth tier.

Another time when my game crashed all of my colonists were relocated to an unknown place in the world and all my buildings had disappeared. I simply placed a new town hall and recalled them, however after leaving the game returning later all of my new buildings were gone replaced with the old ones which again did not work similar to the other time (with the exception that my colonists were still present). 

I didn't fill out the outline thing because I'm not a very tech savvy person but it's the most recent version of the mod and if need be I can provide a list of my other mods.

**Comment by Asherslab** [comment]
This happens because the colony NBT got corrupted when the game crashed. you can load a backup of you colony in the Minecraft/saves/{world-folder}/minecolonies

**Comment by MaddysinLeigh** [comment]
Okay thanks!

**Comment by Wissi** [comment]
Closing due to crash related issue not mod related issue.
No fix required by developers.
