### ISSUE TITLE
Building templates not visible with shaders on?

### ISSUE THREAD

**Issue by ThePlanetMan** [ldtteam/minecolonies#2388]
### Minecolonies version

version 0.8.8117

### Expected behavior

- Use building tool to see block template in the world (so it can be moved before confirming)

### Actual behaviour

- No block templates are visible (tested multiple buildings)

### Steps to reproduce the problem

1. Mod is installed as part of Towncraft modpack
2. Using Optifine 1.12.2_HD_U_D1, with either of KUDA-Shaders v6.5.56 or SEUS-v11.0 enabled
3. Obtain building tool from creative menu, as well as any building (town hall, supply chest, etc.)
4. Right click build tool on open ground and no template shows up (even after changing selected building.)

A. I've gone into the shader profile and turned off just about every selectable option and issue recurs, but as soon as I switch shaders to "Off" the building templates are visible again as expected.
B. I've tried looking for any compatibility notes regarding shaders, so maybe you just don't plan to support them, but hopefully that's something that can come in a future update!

**Comment by marchermans** [comment]
Yes. Since a month we are using VBOs to render templates. Almost all shaders do not respect this even though they simply should if they were used right. I am looking into this, but I am not having much hope.

**Comment by xtended2l** [comment]
It took me a while to figure out what causing the issue, as I have a lot of mods installed. Dear Developers, I hope you will look into this. Thanks for the great mod!

**Comment by Raycoms** [comment]
Yeah, we will be looking into this, but for now it's not a priority since we got a bit stack in front of us already =)

**Comment by Justen-N** [comment]
This is a known issue but is currently low priority.
