### ISSUE TITLE
Chiselled Variants not being requested correctly by Builder - Follow up from Discord

### ISSUE THREAD

**Issue by 99Blocks** [ldtteam/minecolonies#2389]
### Minecolonies version

version Universal-1.12.2-0.8.7582.jar (Forge 14.23.2657)

### Expected behavior

- Being able to distinguish between chiselled variants in the Builder Request menu/inventory

### Actual behaviour

- I'll post my original question from the discord here:

"I'm currently working on a new modpack and want to include some custom buildings that players can style their colonies around. My build team are wanting to use Chisel block variants and after some testing, I'm having an issue with how the blocks show up in the build requests.
As it is, the requests window for my builder shows only the first variant but the block they are holding reflects the variant they need.
In my test I have place five variants of Diorite in a row and scanned it to then place a build request.
- The builder asks for 5 diorite and the block image in the requests shows only the first variant in my five.
- The block she is holding is the correct variant that she needs but I was hoping there was a way for the build request window to reflect that.
- I know chisel uses meta to create its different variants but also that the variants aren't shown in the block name."

### Steps to reproduce the problem

1. Install Minecolonies
2. Install Chisel (Version 1.12.2-0.2.0.31.jar)
3. Make a request from the builder that uses chiselled variants of blocks

Thanks for taking the time to investigate this!

**Comment by Raycoms** [comment]
I tested this, please use the newest minecolonies version
