### ISSUE TITLE
SkyColonies Crash when upgrade a Custom made Hut (Custom stylepack)

### ISSUE THREAD

**Issue by H3roDude** [ldtteam/minecolonies#2390]
### minecolonies-universal-1.12.2-0.8.8095

SkyColonies 2.0 V2.1

### Expected behavior

- Custom Schematics and roads can be build by builder without crashing or any other issues

### Actual behaviour

- On Huts, First level works fine... on second level, your game will crash (crashlog:https://pastebin.com/L6hFnQSK)
- Roads are saved in the Townhall when placing via b. tool but Builder wont start building them

### Steps to reproduce the problem

1. Install the SkyColonies modpack
2. Join the Server
3. Upgrade your Hut
4. Crash
This Crash only works on Multiplayer! tested on Singleplayer and everythink works fine

**Comment by thecatcore** [comment]
On client modpack the path to the schematics is "SkyColonies" but when the game crash for this issue in the console the game say "Skycolonies" this is a Problem ?

**Comment by H3roDude** [comment]
im not really understanding what youre saying

**Comment by thecatcore** [comment]
In the modpack files, the path to the schematics of style "Skycolonies" is ./minecolonies/schematics/SkyColonies/ . But when they have the issue in the log of client the game say he didn't find the schematics on path ./minecolonies/schematics/Skycolonies/ (on the server) is this a problem ? (sorry for my possible bad english)

**Comment by Raycoms** [comment]
H3ro, the server folder is Skycolonies or SkyColonies?

2018-04-18 13:52 GMT+01:00 arthurbambou <notifications@github.com>:

**Comment by H3roDude** [comment]
Skycolonies

**Comment by Raycoms** [comment]
and in the modpack the folder is SkyColonies?

2018-04-18 16:22 GMT+01:00 H3roDude <notifications@github.com>:

**Comment by H3roDude** [comment]
could be, let me look.. but why is that important? i mean, why does it have to be the same names? Isnt that serverside?

**Comment by H3roDude** [comment]
yeah client is SkyColonies

**Comment by Raycoms** [comment]
server and client side names should match.

2018-04-18 16:26 GMT+01:00 H3roDude <notifications@github.com>:

**Comment by H3roDude** [comment]
ugh since when? :o

**Comment by Raycoms** [comment]
Or you don't put the client side files at all. or you put them with the
same names. Else case differences can cause issues depending on the OS.

2018-04-18 16:27 GMT+01:00 H3roDude <notifications@github.com>:

**Comment by H3roDude** [comment]
gotcha.. thank you Ray
