### ISSUE TITLE
broken permissions

### ISSUE THREAD

**Issue by CharCharthemonkey** [ldtteam/minecolonies#2391]
### Minecolonies version
1.12.2-0.8.8117
version X.X.XXXX or curse X.X.XX

### Expected behavior
to work correctly
- XXX

### Actual behaviour
doesnt work rigth
- YYY

### Steps to reproduce the problem
set any fake player in permissions in the townhall to officer log out then back in and it is reset
1. XYZ
2. ZYX
3. ...
4. Profit

**Comment by Asherslab** [comment]
umm. we're going to need a tonne more information than that thanks

**Comment by CharCharthemonkey** [comment]
basically anytime i load in my SP world i have to re add ancientwarfare2 fake players to be allowed to do anything in my colony same for most cyclic machines too

**Comment by BonaireDreams** [comment]
I've had this in every version of minecolonies that I've used over the past 3 months. Assumed it was just normal. Running on a server. I can log on and off and the Fake players retain their permissions. But my servers shuts down every night and performs a full offsite backup. Then starts up again. The next day everyone has to re-add any fakeplayers and give them officer permissions so the machines can place/break blocks within the colony.
