### ISSUE TITLE
Dark Oak Barracks crashing when attempting Lvl 2 upgrade.

### ISSUE THREAD

**Issue by guitarguy0124** [ldtteam/minecolonies#2393]
### Minecolonies version

version 0.8.8053 or curse X.X.XX

### Expected behavior

- When clicking upgrade button on lvl 2 dark oak barracks, construction tape will appear and upgrade build request will be added to build queue.

### Actual behaviour

- Minecraft crashes, but server is allowed to shutdown (not typically the case with MC caused crashes).

### Steps to reproduce the problem

1. Start Colony.
2. Build dark oak barracks.
3. Upgrade dark oak barracks to lvl 1.
4. Attempt to upgrade dark oak barracks to lvl 2.

[crash-2018-04-19_00.11.02-client.txt](https://github.com/Minecolonies/minecolonies/files/1926710/crash-2018-04-19_00.11.02-client.txt)

**Comment by guitarguy0124** [comment]
I just attempted a different route, by building a wood barracks all the way up to level 5, and then changing the design. Minecraft crashed the moment I clicked the 'right' button and it attempted to toggle from birch to dark oak.

**Comment by marchermans** [comment]
Are you on SkyColonies or running custom schematics?

**Comment by guitarguy0124** [comment]
No, and no.

**Comment by marchermans** [comment]
@Raycoms

**Comment by guitarguy0124** [comment]
UPDATE: I tried copying the .NBT (for level 5) out of the .JAR into my scans, and building it that way. Still no dice.

**Comment by guitarguy0124** [comment]
I just updated and tried again. Still broken. Here's the crash report.
[crash-2018-05-06_01.36.34-client.txt](https://github.com/Minecolonies/minecolonies/files/1977403/crash-2018-05-06_01.36.34-client.txt)

**Comment by nebukadnet** [comment]
Same, also having this issue! On version 1.12.2 - 0.8.8213
