### ISSUE TITLE
Building switch style Client Crash

### ISSUE THREAD

**Issue by Asherslab** [ldtteam/minecolonies#2396]
### Minecolonies version

minecolonies-universal-1.12.2-0.8.7972.jar

### Expected behavior

- When switching a Building style with a custom style, it doesn't crash

### Actual behaviour

- When switching a building style with a custom style (on a server) the client crashes with the following log: https://gist.github.com/Asherslab/25e4252f4670eeb25b60ab792f742b43
As far as we are aware, the custom style pack works perfectly using the Build Tool.
Also, we tried both with and without the stylepack installed on the client. both had the same crash.

### Steps to reproduce the problem

1. Install a custom style pack under `{server}/{world}/minecolonies/schematics`
2. boot up and try to switch an existing building's style to the new custom pack.
3. client crashes.

**Comment by marchermans** [comment]
This happens when you name stuff wrong see hero error from this week.

**Comment by Asherslab** [comment]
@OrionDevelopment the pack isn't installed on the client side, as was stated to not do in: #2390

**Comment by marchermans** [comment]
This is your sync to server code if I am not mistaken. I have no idea.

**Comment by Starshak3r** [comment]
This also happens when I attempt to upgrade said custom building from Level1 to Level2, but **does not** happen on my personal server with the same exact stylepack.

I also did not change the folder name from Uppercase to Lowercase in my server, if that matters

**Comment by marchermans** [comment]
Again for @Asherslab , make sure capitalization is correct! Even if it is not on the client. If it works for @Starshak3r it is not Minecolonies. Make sure the directories are properly named.

**Comment by Starshak3r** [comment]
I also solved this error I think, by simply adding a local copy of the schematic into the minecolonies.jar on my machine.
When I clicked the upgrade from Builder 1 to Builder 2, no crash. Accepted the queue position for the upgrade, and as soon as the other building is finished I will be able to verify 100% that it is working

*edit* 
Mr. Diego is happily upgrading his hut from level 1 to level 2

**Comment by marchermans** [comment]
Yeah but you should not need to. There is code in place for this.
