### ISSUE TITLE
Builder not work 

### ISSUE THREAD

**Issue by miosaurio** [ldtteam/minecolonies#2398]
### Minecolonies version

version 0.8.8127 or curse X.X.XX

### Expected behavior

- build the whole town medieval style

### Actual behaviour

- the builder does not build his own hut when you put medieval oak, 

### Steps to reproduce the problem

1. Start Colony.
2. try to build the construstructo cottage of the medieval style oak
3.dig the ground
4. Stands with a solid-placeholderblock in his hand

**Comment by miosaurio** [comment]
sorry for my bad English (made with google translator (I'm too lazy to get my dictionary in English))

**Comment by Asherslab** [comment]
Hey there, when you click on the builder, and look at his "requests" does it have anything in there?
