### ISSUE TITLE
Farm Fields Need to handle more than one seed type at a time.

### ISSUE THREAD

**Issue by MokahTGS** [ldtteam/minecolonies#2400]
1.12.2

Field GUI should allow the player to put seeds into it's inventory which define what is cultivated.  With modded crops (or even vanilla) you simple have too many crops to farm and it could all be done with one or two fields instead of 50+

**Comment by MokahTGS** [comment]
My thought on this is that the GUI for the farm field could be changed to a 5x5 square grid representing each of the farm plots for that field.  The player could then define exactly the crop grown in each plot by placing seeds in each square.  This would make the farm 300% more useful in a modded environment.

**Comment by marchermans** [comment]
This is currently on hold. Blockout (what we are using to construct gui's does not support inventories directly, it is being worked upon however)

**Comment by MokahTGS** [comment]
As it turns out, the farmer does farm custom crops.  You just have to plant them yourself.  The farmer will harvest anything in the field that is planted and growing.  Doesn't even break and replace...just harvests.  I'll close this for now.
