### ISSUE TITLE
Loading a savegame may last "forever" depending on size of colonies.dat

### ISSUE THREAD

**Issue by courseofra** [ldtteam/minecolonies#2401]
Hi dear team,

### Minecolonies version

minecolonies-universal-1.12.2-0.8.8008
(Not testet with newer versions since I found no information belonging to this in the changelogs)

### Expected behavior

- Load fast

### Actual behaviour

- Loading a savegame lasts up to 45 Minutes, depending on filesize of ...\.minecraft\saves\[NAME]\minecolonies\colonies.dat which is seeming to depend on how much of the map was discovered

### Steps to reproduce the problem

I could send you my savegames, but before, it might be useful to check the logs I attached. Please search for "minecolonies/cache".
In one File, for example, you will see:

"[12:04:34] [Server thread/INFO] [minecolonies]: Load cached schematic from C:\Users\Christian\AppData\Roaming\.minecraft\saves\A Place to be\minecolonies/cache
[12:25:12] [Server thread/INFO] [minecolonies]: Finished discovering saplings"

[2018-04-02-3.log.gz](https://github.com/Minecolonies/minecolonies/files/1934203/2018-04-02-3.log.gz)
[2018-04-07-1.log.gz](https://github.com/Minecolonies/minecolonies/files/1934204/2018-04-07-1.log.gz)

Best regards
Christian

**Comment by Raycoms** [comment]
This issue should've been solved already, the colony dat shouldn't grow as big anymore.

**Comment by Vickaizer** [comment]
I have this problem too. My survival world takes 50minutes-1 and half an hour to finally load. I'm using version 1.12.2-0.9.30-ALPHA

**Comment by Raycoms** [comment]
Please upgrade the version and do %
/mc es resetAll
