### ISSUE TITLE
broken GUI on buildings when trying to build them

### ISSUE THREAD

**Issue by CharCharthemonkey** [ldtteam/minecolonies#2403]
Minecolonies version

version 1.12.2.0.8.8117

### Expected behavior

- not crash when trying to open the GUI

### Actual behaviour

- repeatedly crashes on opening the GUI

### Steps to reproduce the problem

1. place down building (this time was caused by the lumberjack)
2. right click with and without biulder wand tool
3. crash
4. Profit
https://pastebin.com/iCRAWNv2

**Comment by CharCharthemonkey** [comment]
after testing on the latest update for minecolonies it still crashes on the lumberjack but not the rest of the buildings 
https://pastebin.com/3bZZH3nx

**Comment by Justen-N** [comment]
Are you playing with other mods that add large numbers of trees? Because
there  is a known issue logged for lumberjack gui.

**Comment by CharCharthemonkey** [comment]
nope its vanilla trees and tinkers no dynamic trees or BOP trees or anything like that
