### ISSUE TITLE
[build 8133] no /help available

### ISSUE THREAD

**Issue by kreezxil** [ldtteam/minecolonies#2405]
### Minecolonies version

build 8133

### Expected behavior

- as non-creative player and non-op player expect /help to show the minecolonies entries

### Actual behaviour

- all improperty mod coded help terminated

### Steps to reproduce the problem

1.install this mod version and nothing else, be amazed that it has no help

### Notes
Using **Forge** build 2673
This was reported to me a few version ago in my pack, World of Dragons
Will try builds backward until the help comes back.
I'll attach the results here.
**Apparently you can still access /mc commands if you know them**

**Comment by kreezxil** [comment]
The following builds also have no help

- 8127
- 8117
- 8113
- 8095
- 8068
- 8053
- 8026
- 8021
- 8008
- 7996
- 7972
- 7965
- 7953
- 7949
- 7934
- 7913
- 7902
- 7883
- 7875
- 7869
- 7866
- 7855
- 7847

# maybe it's Forge related. At this point I'm going to fork the project and fix help and submit a PR.

**Comment by Wissi** [comment]
@Raycoms Close issue?

**Comment by kreezxil** [comment]
I've not had any more issues with it once we realized that the one config
setting that convinces the mod that everyone is op was set. although I
think that is a bug. because normies should have access to normie parts of
the command.
