### ISSUE TITLE
Scan Tool Crashes in SSP

### ISSUE THREAD

**Issue by kreezxil** [ldtteam/minecolonies#2406]
### Minecolonies version

1.12.2-0.8.8133

### Expected behavior

- scan tool to not crash

### Actual behaviour

- scan tool causes crash

### Steps to reproduce the problem

[8:57 AM] Sandra: Created a scan of the library that I finished building (I do this more for testing than actually using it via the builders tool) and trying to use the scan with the builders tool then crashes the game. Other scans seem to work fine

https://pastebin.com/DhQY2V8W

**Comment by kreezxil** [comment]
![pic](https://cdn.discordapp.com/attachments/237795556687216641/438321841325473803/unknown.png)
![pic](https://cdn.discordapp.com/attachments/237795556687216641/438321431550361600/unknown.png)
![pic](https://cdn.discordapp.com/attachments/237795556687216641/438320959976374272/unknown.png)
![pic](https://cdn.discordapp.com/attachments/237795556687216641/438316595866107905/unknown.png)
![pic](https://cdn.discordapp.com/attachments/237795556687216641/438305776629710857/unknown.png)

**Comment by Raycoms** [comment]
This is a buildtool rendering issue then @oriononline

**Comment by marchermans** [comment]
Hmm something with bibliocraft. We had the same issue with our Racks. It might be that schedule needs to be rescanned to update the data somehow.

@kreezxil The schematic would be nice.

**Comment by kreezxil** [comment]
I'm checking to see if the player made one or not and if not hoping she can
make it.

**Comment by Silviax88** [comment]
@OrionDevelopment 
Here's a zip file that contains the schematic for the library that causes the crashes
[https://drive.google.com/open?id=1D8isgCaATrXJUZkTzwInp1Jl331QOOJ9](url)

(I'm the user who experienced the issues btw xP)

**Comment by marchermans** [comment]
Is it a custom schematic?

**Comment by Silviax88** [comment]
@OrionDevelopment Yeah, I built it in creative mode singleplayer and used the scan tool to make the schematic, then trying to place it with the builder's tool is what crashed the game

**Comment by marchermans** [comment]
Yeah there are some blocks which behave a bit wrongly

**Comment by marchermans** [comment]
Are you using any blocks from Bibliocraft?

**Comment by marchermans** [comment]
Cause if so they might be accessing the world which is simply not supported. I will try to find a away to exclude them.

**Comment by Raycoms** [comment]
@OrionDevelopment progress?

**Comment by marchermans** [comment]
Some yes.

**Comment by marchermans** [comment]
I could add an exclusion for them but I do not fancy doing so.

**Comment by Raycoms** [comment]
I'd close this, if blocks access the world in methods they should clearly not, we can't do much, most mods solved their issues related to this though
