### ISSUE TITLE
Colony Automatically Placing Random Mineshafts Everywhere [1.12.2]

### ISSUE THREAD

**Issue by WPaul15** [ldtteam/minecolonies#2408]
### Minecolonies Version

- 1.12.2-0.8.8133

### Forge Version

- 14.23.3.2674

### Issue

After updating to the latest version of MineColonies (0.8.8133), I got on to play. At one point, I noticed that there was a random area surrounded by Construction Tape (See image below). I went to the Town Hall to look, and I noticed that `schematics/miner/mine...` was in the Work Orders list (The name is too long to fit, but after a bit of testing, I'm assuming that it's trying to build `schematics/miner/minerMainShaft`, though it might be some other schematic under that folder). The thing is, I didn't do anything!

![2018-04-27_10 20 03](https://user-images.githubusercontent.com/16868897/39352804-24257746-4a06-11e8-8c0a-764ac0e9d695.png)

What's more, these mineshafts continue to be placed. If I go clear the Work Orders, a new one will pop up after some time, even if there's already one in the queue. The image below shows a Work Order list full of them.

![2018-04-27_10 05 20](https://user-images.githubusercontent.com/16868897/39352789-106b2728-4a06-11e8-86d7-eec43cf33b5d.png)

Additionally, whatever algorithm is placing these has no regard for preexisting buildings. I've had it try to put one right on top of an existing Mine, I've had one generate in the middle of the wall of my Town Hall... The list goes on. What's also annoying is that if the Builder starts building one of these, I don't get a message notifying me that they're beginning to build like I normally would. They just start building, and if I weren't constantly paying attention, this would wreak havoc on my colony.

### Expected Behavior

- Presumably nothing. This was never an issue before.

### Actual Behavior

- Attempted mineshafts everywhere!

### Steps to Reproduce the Problem

1. Load the game.
2. Wait,.

**Comment by marchermans** [comment]
@Raycoms

**Comment by Raycoms** [comment]
Can you test if this one works:

https://s3.eu-central-1.amazonaws.com/minecolonies/Minecolonies/Minecolonies_Branches/8143/minecolonies-universal-1.12.2-0.8.8143.jar

2018-04-27 14:01 GMT+01:00 Marc Hermans <notifications@github.com>:

**Comment by WPaul15** [comment]
That seems to do the trick! Thank you!
