### ISSUE TITLE
[Enhancement] MineColonies Texture Consistency

### ISSUE THREAD

**Issue by Electrocutor** [ldtteam/minecolonies#2409]
Please, adjust the block models that come with minecolonies to use the normal minecraft textures where at all possible. This will allow minecolonies to look right regardless of what texture pack you may be using without the need for that texture pack to make special textures just for minecolonies.

Example:
The rack is merely oak wood and iron, but instead of just using blocks/planks_oak and blocks/iron_trapdoor, it uses its own textures that achieve the exact same look, but will not update when a texture pack is installed.

I am willing to help with this if desired, but have only just started to learn minecraft modding, so things like which facing is which and what orientation the 3d grid axes have are things I am not familiar with yet.

**Comment by Electrocutor** [comment]
Here's some examples:
https://forum.minecolonies.com/showthread.php?tid=331

**Comment by Raycoms** [comment]
We're actually quite busy, but feel free to PR these changes =)

**Comment by SulpherStaer** [comment]
May I suggest you use White Concrete Powder as the washing for the wattle and daub blocks (timber frames) instead of white wool? Wool does not have an excelent texture (in most texture packs) that matches what the material actually is.

**Comment by Raycoms** [comment]
@Electrocutor up for PRing this yourself? =)
