### ISSUE TITLE
Colony data + colonists vanishing on server stop.

### ISSUE THREAD

**Issue by shiney103** [ldtteam/minecolonies#2411]
### Minecolonies version

version 0.8.8133 (Included in ATM3 v5.9.4)

### Expected behavior

- The colonists should remain, and the building blocks should be able to be interacted with. The colony should persist after a restart.

### Actual behaviour

-Sometimes when restarting, or more reliably when stopping a server, and starting it fresh, existing colonies will lose their information, and colonists. This results in colony blocks such as the builder, town hall, and such becoming non-interactable, while the buildings remain. The colonists vanish as well, requiring a complete restart of building your colony.
Reverting the minecolony data has only worked once out of a few attempts, but ran into the same problem immediately on the next server stop.

### Steps to reproduce the problem

1. have a functional colony consisting of at least town hall, builder's hut, and citizens.
2. either restart, or more likely stop-and-start a server at least once, may take a few tries.

**Comment by Asherslab** [comment]
this happens because of the way that Minecraft stops servers and saves NBT data. 
In basic there's nothing we can do right now, we are wanting to overhaul the system to allow for saving directly to the world in the future though, which would (hopefully) fix the issue

**Comment by Hadexander** [comment]
So nothing can be done to prevent this? 
Or to manually save the colonies data?

**Comment by JonnaJudin** [comment]
I just experienced the same issue. Rebooted the server and whole colony stopped existing. blocks are still there but not interactable. Is there anything I can do to save the colony before shutting the server? I restored the colony.dat from backup in the world/minecolonies, but the colony was still unresponsive.

**Comment by Raycoms** [comment]
Did you load the colonyX.dat (x is the right colonyid) + the colonies.dat and then restarted the server?

**Comment by JonnaJudin** [comment]
Ok thanks!, did not realize I need both of those. I only had backup of the colonies.dat. I did check colony1.dat in nbt reader and noticed it was missing the ownerid tag, I added it in, but it still did not work. I'll try to keep both files backupped as workaround until more permanent solution appears.
