### ISSUE TITLE
Some Colonist Inventories Won't Open [1.12.2]

### ISSUE THREAD

**Issue by WPaul15** [ldtteam/minecolonies#2412]
### Minecolonies Version

- 1.12.2-0.8.8147

### Forge Version

- 14.23.3.2674

### Issue

This only happens with some colonists, but if I try to open their inventories, nothing happens. Their requests open just fine, however. I'm not sure why it only happens with some and not the others, though.

Here's a list of my colonists affected:
- 1/2 Farmers
- 1/1 Cowboys
- 3/7 Guards (2 are Barracks Guards, 1 is a Tower Guard)
- 1/4 Unemployed Colonists

All other colonists are fine.

**Comment by Raycoms** [comment]
Reopen with more info

**Comment by WPaul15** [comment]
@Raycoms, what other info should I provide?

**Comment by marchermans** [comment]
We have an issue template fill it in.
