### ISSUE TITLE
mine colonies custom main menu pngs and config names need to be lowercase

### ISSUE THREAD

**Issue by Bfk98** [ldtteam/minecolonies#2413]
MineColonies Official v 4.25 on minecraft.curseforge.com/
using multimc 6
the custom main menu config and pngs need to be all lower case for linux clients otherwise the mod does not recognise them and you get the standard purple and black title  screen

**Comment by mkienenb** [comment]
@Wissi Weren't you already working on this?

**Comment by Wissi** [comment]
Fixed already. Should be up on next version update.
