### ISSUE TITLE
Some Colonists' Inventories Won't Open

### ISSUE THREAD

**Issue by WPaul15** [ldtteam/minecolonies#2414]
### MineColonies Version

- 1.12.2-0.8.8147

### Forge Version

- 14.23.3.2674

### Expected Behavior

The colonist's inventory should appear when I click on "Inventory" in their menu.

### Actual Behavior

The colonist's inventory does not appear when I click on "Inventory" in their menu.
This is not the case for all colonists, however; some work just fine. After closing and reloading the game, it seems that the individual colonists this bug affects _may_ change, i.e. their inventory may open during one play session and not the next. I could be wrong.

### Steps to Reproduce the Problem

1. Load the game with MineColonies 1.12.2-0.8.8147.
2. Find a colonist.
3. Try to open the selected colonist's inventory.
4. If the inventory opens as usual, repeat steps 2 and 3 with another colonist. If nothing happens when you click "Inventory", continue to step 5.
5. You have encountered the problem.

### Note

I really don't know of anything else that would be helpful to solving this issue because I don't know what would be causing the issue. I know I was told to reopen the issue with more information, but there really isn't much else I can give you. I would include a video clip of me trying to open colonists' inventories, but I can't seem to get that working at the moment.

All I can say is that sometimes, the colonists' inventories won't open when I click the "Inventory" button, and that didn't start happening until I installed MineColonies 0.8.8147. I'll revert back to a previous version for now, and if I somehow encounter the issue again, I'll let you know.

Also, if any other players are also encountering this problem, please comment or upvote this issue!

**Comment by WPaul15** [comment]
I hope this suffices. If not, please give me _specific_ data you'd like to have. Otherwise, I'll just be reporting the same thing in different words.

**Comment by Raycoms** [comment]
Can you attach your world?

**Comment by WPaul15** [comment]
Absolutely! [MineColonies-WPaul15.zip](https://github.com/Minecolonies/minecolonies/files/1966336/MineColonies-WPaul15.zip)
Hopefully, everything will be there. I only included the region files that contain the colony, because otherwise, the file would have been too large to upload. If you don't spawn in the colony, going to (540, 69, 672) will put you there.

I am using some other mods alongside MineColonies, but I don't think not having them will change the issue here. But just in case, here's a list of the mods I'm using (I would just include a ZIP with all the JARs, but that would be far too large):

- [Animaina](https://minecraft.curseforge.com/projects/animania/files/2553952)
- [AppleCore](https://minecraft.curseforge.com/projects/applecore/files/2530884)
- [AppleSkin](https://minecraft.curseforge.com/projects/appleskin/files/2496585)
- [AutoRegLib](https://minecraft.curseforge.com/projects/autoreglib/files/2544276)
- [Chameleon](https://minecraft.curseforge.com/projects/chameleon/files/2450900)
- [Cooking For Blockheads](https://minecraft.curseforge.com/projects/cooking-for-blockheads/files/2543356)
- [CraftStudio API](https://minecraft.curseforge.com/projects/craftstudio-api/files/2480954)
- [Dynamic Surroundings](https://minecraft.curseforge.com/projects/dynamic-surroundings/files/2556333)
- [Fast Leaf Decay](https://minecraft.curseforge.com/projects/fast-leaf-decay/files/2463272)
- [Gravestone](https://minecraft.curseforge.com/projects/gravestone-mod/files/2524880)
- [Hwyla](https://minecraft.curseforge.com/projects/hwyla/files/2545475)
- [Inventory Tweaks](https://minecraft.curseforge.com/projects/inventory-tweaks/files/2514356)
- [JEI](https://minecraft.curseforge.com/projects/jei/files/2556235)
- [JourneyMap](https://minecraft.curseforge.com/projects/journeymap/files/2498312)
- MineColonies
- [Mouse Tweaks](https://minecraft.curseforge.com/projects/mouse-tweaks/files/2462627)
- [OptiFine](https://optifine.net/adloadx?f=OptiFine_1.12.2_HD_U_D1.jar)
- [Pam's HarvestCraft](https://minecraft.curseforge.com/projects/pams-harvestcraft/files/2545718)
- [Quark](https://minecraft.curseforge.com/projects/quark/files/2544279)
- [Spice of Life](https://minecraft.curseforge.com/projects/the-spice-of-life/files/2486848)
- [Storage Drawers](https://minecraft.curseforge.com/projects/storage-drawers/files/2545495)
- [VeinMiner](https://minecraft.curseforge.com/projects/veinminer/files/2528295)
- [Wawla](https://minecraft.curseforge.com/projects/wawla-what-are-we-looking-at/files/2552608)

Let me know if you need anything else!

**Comment by BonaireDreams** [comment]
Can confirm we've had this same issue for the past 3 months with every version of MC's we've used. We first had a Colonial Engineers server which had this issue, currently we are playing a Sevtech: Ages server with Minecolonies added.  It seems to happen much less on the current version we are running (.8068) than previous ones. I think I've only had it happen maybe once in the past week. But then I find I'm not interacting with my colonists as much, at least not checking their inventories.
