### ISSUE TITLE
Repositioning preview 

### ISSUE THREAD

**Issue by MaddysinLeigh** [ldtteam/minecolonies#2417]
I tried to reposition a building and now the unplaced building won't disappear. I even started a new game and it's in the new game.

**Comment by marchermans** [comment]
Please. Fill in the Template. More information Is required.

**Comment by Raycoms** [comment]
Close the preview with the X in the gui

**Comment by MaddysinLeigh** [comment]
there is no X, and I can't destroy any of the blocks

**Comment by Raycoms** [comment]
you have to open the relocate GUI again

2018-05-01 16:47 GMT+01:00 MaddysinLeigh <notifications@github.com>:

**Comment by MaddysinLeigh** [comment]
I tried and it won't come up
