### ISSUE TITLE
Crash on loading screen 

### ISSUE THREAD

**Issue by coldsthetic** [ldtteam/minecolonies#2418]
### Minecolonies version
colonies version
1.12.2-0.8.8008
version X.X.XXXX or curse X.X.XX

### Expected behavior
to work on loading screen and not crash

### Actual behaviour
Minecraft on loading screen when added Minecolonies 
### Steps to reproduce the problem

1. XYZ
2. ZYX
3. ...
4. Profit

**Comment by marchermans** [comment]
More Details please. Logs worlds modpacks .
