### ISSUE TITLE
Bug with Town Hall

### ISSUE THREAD

**Issue by ninjadcb** [ldtteam/minecolonies#2419]
1.11.2-0.8.1784

1.11.2

Being able to place a Town Hall

Saying "You already placed a Town Hall"

Steps to reproduce the problem:

1. Place a Town Hall
2. Break the Town hall (Break it quickly after placing it)
3. Try to place another Town Hall
4. Profit

**Comment by Raycoms** [comment]
Cannot reproduce, did you try relogging?
