### ISSUE TITLE
Problem with OptiFine

### ISSUE THREAD

**Issue by Kocytos** [ldtteam/minecolonies#2420]
Minecolonies version: minecolonies-universal-1.12.2-0.8.8140
Optifine version: OptiFine_1.12.2_HD_U_D2

Problem: 
![2018-05-03_17 38 35](https://user-images.githubusercontent.com/28514610/39587102-fc0450c8-4ef8-11e8-8652-8596fb0a32a5.png)

this is a Supplychest shematic lol

**Comment by Justen-N** [comment]
Please see #2388.

**Comment by Justen-N** [comment]
Kocytos, the issue is dealing with how optifine handles VBOs. I would try modifying your optifine settings,  to see if that would help, but this doesn't  look like a problem we can fix on our own.

**Comment by marchermans** [comment]
Actually we can. It is just on the lower priority end of the task list.

**Comment by Justen-N** [comment]
Oh, did you find something? Last I saw you weren't  very hopeful.

**Comment by Raycoms** [comment]
We asked the Optifine devs and they linked us into a direction

**Comment by Justen-N** [comment]
Got it.

**Comment by Raycoms** [comment]
Closed inf avor of: https://github.com/Minecolonies/minecolonies/issues/2399
