### ISSUE TITLE
The miner does something strange. Minecolonies 1.12.2-0.8.8160 

### ISSUE THREAD

**Issue by ZzylinN** [ldtteam/minecolonies#2423]
Hello! I'm using version 1.12.2-0.8.8160 
Java 1.8.0_121 (x64)
Forge 14.23.3.2672
The miner does something strange. I started the mine, and the miner broke the mine and began to build a box of earth and stone.
The height at which the mine begins (in the picture is visible): 68
Mine level: 4 (wood)
Picture attached: https://hostingkartinok.com/show-image.php?id=a620c203101b7ac0ad36695d51642088

inside the shaft: https://hostingkartinok.com/show-image.php?id=ecd32a71c2bf72584f6914cf1b0b5f5c
As the miner began to make a descent on the other side (the nearest wall to the main block of the mine.) When the mine was being built, the descent was on the left side of the main block of the mine. Maybe this information will help

**Comment by Raycoms** [comment]
I just checked on that, is it possible that something went wrong with the ladder of the mine?

**Comment by ZzylinN** [comment]
I tried to restore the mine and re-run the miner into it, but the miner again broke the top of the shaft and built a box of earth and stone

**Comment by Raycoms** [comment]
please download the newest version, I fixed it.

**Comment by ZzylinN** [comment]
https://hostingkartinok.com/show-image.php?id=c53a1fac9381790476473f534eda0c71

https://hostingkartinok.com/show-image.php?id=280183e7ab2c0b255d6abe622df72f1f

Downloaded the latest version. But the miner is still beginning to disassemble the upper part of the mine. The picture shows that the miner with an ax (requested ax from the warehouse) breaks the wooden fence (the one that is above the block redstone)

**Comment by Raycoms** [comment]
you'll need to fix the ladder so he starts working well again.

2018-05-06 3:47 GMT+01:00 Sasha <notifications@github.com>:

**Comment by ZzylinN** [comment]
need to click on the mine to repair?

**Comment by ZzylinN** [comment]
Thank you! like the miner began to work normally

**Comment by ZzylinN** [comment]
https://hostingkartinok.com/show-image.php?id=3591c1d1d8a07bda4712bb03ff5b4e22
The bottom left is written: "missing ..." is this an option not completed?

And whether it is possible to make for those who are settlers in the building there is a workbench (builder, etc.) to write down the creation of objects as on a workbench !?
