### ISSUE TITLE
Achievements not showing in 1.12.2

### ISSUE THREAD

**Issue by rangerunnown** [ldtteam/minecolonies#2426]
I am currently playing The Official Minecolonies modpack on twitch. i have a town hall and builder hits, but i am not gaining any achievements. I am playing on creative. Thanks
![2018-05-05_16 23 03](https://user-images.githubusercontent.com/39012268/39666254-a5cded26-5098-11e8-9e2c-92f4ffc4efd8.png)

**Comment by Raycoms** [comment]
Yeah, we had to remove them because the achievement system in 1.12 is the worst, and we're waiting to see how its going to be in 1.13 to decide how we will add it back in the future.

**Comment by ghost** [comment]
I know this is old, but it isn't going to change, the new system is better. The best options are to either work with it or implement your own system within the mod itself.

As an add-on request, adding something to detect colony size for use in questing would be nice.

**Comment by spacewolfcub** [comment]
Oh, yeah... Someone mentioned in passing they wanted me to make them some icons to use in setting up achievements. 

I see Ray wanted to wait for 1.13

Well, 1.13 is coming soon! So one way or another, we'll find out what ray plans to make then. 
In the meantime, bump this thread in a week to see if I have more time for other projects to focus on the icons, ok?

**Comment by ghost** [comment]
> 
> 
> Oh, yeah... Someone mentioned in passing they wanted me to make them some icons to use in setting up achievements.
> 
> I see Ray wanted to wait for 1.13
> 
> Well, 1.13 is coming soon! So one way or another, we'll find out what ray plans to make then.
> In the meantime, bump this thread in a week to see if I have more time for other projects to focus on the icons, ok?

The icons for the task are actually there, the problem is that there's nothing to trigger them. For now I just have them as checkbox tasks, placed right about at the point where you would probably have that many citizens anyway.

**Comment by Nightenom** [comment]
This is almost done, that means the code is ready from our side, textures are up to visuals, but we (or at least me) are missing a Forge util which I'm not sure if I'm able to create it properly

**Comment by Nightenom** [comment]
And I don't know why Ray hates this system?

**Comment by ghost** [comment]
> 
> 
> This is almost done, that means the code is ready from our side, textures are up to visuals, but we (or at least me) are missing a Forge util which I'm not sure if I'm able to create it properly

You could always do what I do: look at how someone else did it and copy them.

**Comment by Nightenom** [comment]
I just don't want to create 100 proxy items, especially with flattening

**Comment by ghost** [comment]
I don't blame you there.

I'm not a coder, so take this with a lump of salt, but I don't believe you need them anymore. Outside of this mod I haven't seen items specific to achievements, usually it's just re-using a texture or includes another texture (and nothing more) for it.

**Comment by Nightenom** [comment]
The problem is our community decided to have new textures for this, and the way Mojang created is terrible to use

**Comment by spacewolfcub** [comment]
I just hate they tried to make up a new word for Achievements. 
Other than SevTech, I've never even looked at Achievements, so I don't actually care intensely.

**Comment by Nightenom** [comment]
meh, advancements are completely different system than achievements, it's not about hunting for numbers now - which is good from my pov
