### ISSUE TITLE
A usable version for 1.7.10?

### ISSUE THREAD

**Issue by RickArcee** [ldtteam/minecolonies#2430]
### Minecolonies version

version 1.7.10

### Expected behavior

- Build the builder's hut

### Actual behaviour

- Starts to dig and stops before putting any bloc. Won't ask for any materials

### Steps to reproduce the problem

1.Create the townhall and found the colony
2. Put the "builder's hut" bloc
3. Ask to build the builder's hut

This version doesn't seem to be working, the town hall's GUI buttons won't react when the arrow is on them, and the builder won't build any building (i'm on creative in order to test the game).
Is there a 1.7.10 Minecolonies version that works? :/ I'm about to make a modded server and it will be very sad without minecolonies.... Is there a 1.7.10 version of the mod that works? I saw official reviews of the mod made by the Minecolonies team that runned in this version.

Thanks for your help

**Comment by Raycoms** [comment]
Yeah there is no good version for 1.7.10.

2018-05-06 11:34 GMT+01:00 RickArcee <notifications@github.com>:
