### ISSUE TITLE
Barbarians are unkillable

### ISSUE THREAD

**Issue by lebanni** [ldtteam/minecolonies#2431]
### Minecolonies version

minecolonies-universal-1.12.2-0.8.8208.jar
forge-1.12.2-14.23.3.2678-universal.jar

### Expected behavior

- Barbarians should die when killing them.

### Actual behaviour

Barbarians spawn invisible at start and can hit player or citizens. They become visible after a while. When hitting them, they lose hitpoints but stay with armor at 1 and don't die.

https://imgur.com/a/aMPcl59

**Comment by Raycoms** [comment]
Should be fixed now.
