### ISSUE TITLE
Ideas for the development of minecolonies

### ISSUE THREAD

**Issue by ZzylinN** [ldtteam/minecolonies#2432]
Hello! :)
My suggestions:

1. Create money (which will be used in the settlement) and when enemies attack (when killing a settler), money will be taken away by enemies (with complete killing of enemies money is returned or even added more than it was).

2. Create a settler engineer who can create items on the workbench such as doors, steps, stairs, beds and other (making it in 3x3).

3. Create a settler of the magician (enchanter) who could enchant weapons and armor both to settlers and the player (to enchant players for money).

4. Create a settler of the potions

5. To teach the settlers that raw eggs are not food (they bring all the settlers raw eggs and settlers start to starve).

6. Make it possible to access the entire warehouse from one block (very useful for different mods).

7. So that the settlers would issue some quests (for the execution of quests issued a cash reward).

8. So that the enemies had a leader who was stronger and carried prey - a bag (the bag contains money, valuable resources).

9. For all of the above, the settlers make buildings.

10. Create a settler repairman armor and weapons (repairs for residents and for the player for money).

11. Guards include swords and bows to the repairman..

12. In the game of a wandering merchant who comes once a couple of days to the colony (if the market is built, then he goes to the market and then he has much more goods!). Sells this trader both for money and for gold, diamonds or emeralds.

**Comment by Raycoms** [comment]
Most of these are around already and planned already. Thanks for sending us these though =)
