### ISSUE TITLE
Colony Crashes

### ISSUE THREAD

**Issue by ravenclaw1987** [ldtteam/minecolonies#2433]
### Minecolonies version

version 4.25

### Expected behavior

- Game To work

### Actual behaviour

- Starts fine, playing single player world, then game crashes upon relaunch all coloniests gone and interactive blocks just say chest and can not access.

### Steps to reproduce the problem

1. Started another colony further away on same world 
2. Started another world.
3. Same results, only change is time to crash.
4. Profit

**Comment by Raycoms** [comment]
version 4.2.5?

2018-05-07 15:57 GMT+01:00 ravenclaw1987 <notifications@github.com>:

**Comment by PoroUsedSnax** [comment]
I'm guessing pack version 4.25, so 0.8.8147

**Comment by ravenclaw1987** [comment]
I downloaded from the Twitch Launcher if that helps. Not sure were to find the version.

**Comment by ravenclaw1987** [comment]
Is there anything I can do to restore my colony once it crashes? I ask because I am really into this mod, but I don't want to waste another day of work trying to build something that's gonna break at any time..

**Comment by PoroUsedSnax** [comment]
There should be zip backups of your colonies.dat saved at [worldname]/minecolonies, which should hopefully bring things back.

**Comment by Raycoms** [comment]
Should be fixed.
