### ISSUE TITLE
Jobless Citizens Starving / Full hunger don't visit Restaurant

### ISSUE THREAD

**Issue by SulpherStaer** [ldtteam/minecolonies#2434]
### Minecolonies version

version 1.12.2-0.8.8147

### Expected behavior

- Citizens that are hungry stop doing what ever they were doing, visit the restaurant, and eat.

### Actual behaviour

- Citizens are starving, only the cook of the restaurant and the baker are eating.

### Steps to reproduce the problem

1. Build a mature colony on an island.
2. Observe general behaviour
3. I don't know the steps that reproduce the problem, because I only noticed it now.

**Comment by SulpherStaer** [comment]
Nevermind - it seems the restaurant was out of food, despite having cowboy, sheepherder, farmer, ect... The cook of the restaurant isn't requesting the raw ingredients for cooking, so the delivery people aren't offering anything to him.

**Comment by SulpherStaer** [comment]
Again nevermind, he just requested raw beef, and it got delivered, but only because I was standing in the restaurant.
This is very confusing...

**Comment by Raycoms** [comment]
The chunk might not be loaded otherwise
