### ISSUE TITLE
mc colony delete deletes all colonies on restart.

### ISSUE THREAD

**Issue by Hadexander** [ldtteam/minecolonies#2436]
### Minecolonies version

curse 1.12.2-0.8.7582

### Expected behavior

- To use /mc colony delete and detele my own colony

### Actual behaviour

- It deletes my colony, but if the server restarts, all colonies get deleted

### Steps to reproduce the problem

1. Use, in-game, on your account, /mc colony delete
2. Get your colony deleted.
3. Restart Server.
4. All colonies are gone, not even in the /mc colonies list. All the buildings are still there tho.

**Comment by Raycoms** [comment]
Should be fixed in the newest versions.
