### ISSUE TITLE
distance check is borked

### ISSUE THREAD

**Issue by PhanaticD** [ldtteam/minecolonies#2437]
### Minecolonies version

minecolonies-universal-1.12.2-0.8.8208

https://gyazo.com/aeb9e1985bac0e77a415816d732871d0

**Comment by PhanaticD** [comment]
probably would be fixed by not casting to a int for the distance, as square root of int's max value is only a little over 46k, so anyone further than that far out will have problems

**Comment by PoroUsedSnax** [comment]
I believe this should be fixed with #2458, please test with the newest version available and comment back if there are any issues.
