### ISSUE TITLE
NPC's duplicate when you leave the area then come back

### ISSUE THREAD

**Issue by PhanaticD** [ldtteam/minecolonies#2438]
minecolonies-universal-1.12.2-0.8.8208

i made a builder hut and whenever I leave the area so the chunks unload then come back there is one standing where it last was and a new one duplicated. it can keep happening so there can be infinite amounts of one guy till you re-call it individually

**Comment by Raycoms** [comment]
Does this happen in smp only or in ssp as well?

2018-05-09 15:46 GMT+01:00 Josh <notifications@github.com>:

**Comment by PhanaticD** [comment]
its on a server

**Comment by PhanaticD** [comment]
one standing here and one stuck in the floor under him: https://gyazo.com/8c88ba57c0e430f2842e722237632b86
and one standing outside: https://gyazo.com/85f1b13c206877ce17f0a438b01eebe1

**Comment by PhanaticD** [comment]
https://gyazo.com/800b0ee9dab9239e1e494577a0b44eb2

this mod is pretty much unplayable its a shame looked like fun

**Comment by Raycoms** [comment]
Wow, let's calm down a bit, we have a server running for ages and have
barely problems with this, it happens occasionally but nothing that breaks
gameplay at all.
But offering problems and complaining is always better than offering 100%
reproduces and solutions.

2018-05-10 3:00 GMT+01:00 Josh <notifications@github.com>:

**Comment by Sandriell** [comment]
This isn't even a Minecolonies issue, this is a Minecraft issue.

See: https://bugs.mojang.com/browse/MC-119971 or https://bugs.mojang.com/browse/MC-22147

**Comment by PhanaticD** [comment]
what seems to be working for me as a fix is i just killed them all, restarted server, then set the chunks for the village to always stay loaded with ftbutils

**Comment by Sandriell** [comment]
Chunk loading the area will definitely help. Basically the issue crops up when something moves from a loaded to an unloaded chunk.
