### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ZoniThePothead** [ldtteam/minecolonies#2439]
### Minecolonies version

minecolonies-universal-1.12.2-0.8.8133.jar
--

### Expected behavior

- Game to work

### Actual behaviour

- Game crashes upon placing a townhall chest
-Not letting me play anymore on this world unless i delete "minecolony" folder from my world

### Steps to reproduce the problem

1. Started new world
2. Placed the chest
3. Not suprised, game crashed
4. Profit

**Comment by Raycoms** [comment]
Can you post the log please?

**Comment by ZoniThePothead** [comment]
Hey thanks for trying to help but i downloaded the latest version of minecolonies and it works correctly but there is another problem with the townhall range, ima just make new ticket for it ye
