### ISSUE TITLE
Waypoints aren't rendered

### ISSUE THREAD

**Issue by SulpherStaer** [ldtteam/minecolonies#2440]
### Minecolonies version

version 1.12.2-0.8.8208

### Expected behavior

- When placing just a waypoint with the build wand, other waypoints are visible (to prevent to close overlap)

### Actual behaviour

- When placing a waypoint, there is no way to know where the other waypoints are placed. This was possible in the past.

### Steps to reproduce the problem

1. Place several waypoints in the build queue and wait for them to finish.
2. Place more waypoints, and observe that already built waypoints are not rendered / made visible.

**Comment by marchermans** [comment]
That is currently a side effect of the new vbo based rendering. I am working on that but is currently on the 4 or 5 position in the queue. So it might takes some time or be even pushed down further.

**Comment by SulpherStaer** [comment]
How far do I roll back to get the waypoints again? Because I really don't like not seeing them.

**Comment by marchermans** [comment]
Oh that is going to be at least a couple of months. I am currently not at my pc and would not be able to tell you right now.

**Comment by marchermans** [comment]
You have to rollback to a version from before April 7. 2018.

**Comment by Raycoms** [comment]
Now they render
