### ISSUE TITLE
Townhall range

### ISSUE THREAD

**Issue by ZoniThePothead** [ldtteam/minecolonies#2442]
###minecolonies-universal-1.12.2-0.8.8208

### Expected behavior

- I build townhall and i have about 100(?) blocks to build in each way

### Actual behaviour

- i can build in one direction way further than the other

### Steps to reproduce the problem

1. Replaced townhall
2. Placed townhall in every direction then checked the range
3. Tried to mess in the minecolonies settings, although no success
4. Profit

### Really detailed screenshots

![2018-05-10_11 31 13](https://user-images.githubusercontent.com/39126530/39863620-7bdd23e4-5447-11e8-9dfb-337c0f185644.png)
![2018-05-10_11 30 47](https://user-images.githubusercontent.com/39126530/39863627-7f64bd06-5447-11e8-9685-2a981e51c603.png)
![2018-05-10_11 30 23](https://user-images.githubusercontent.com/39126530/39863635-8587e19a-5447-11e8-90d3-acd2823f1664.png)
![townhall1](https://user-images.githubusercontent.com/39126530/39863659-9975cdd4-5447-11e8-8d40-70269b5962de.png)

**Comment by Raycoms** [comment]
can you go to the colony center and execute /mc colony claim colony:
yourcolonyid range: yourrange?

2018-05-10 10:45 GMT+01:00 ZoniThePothead <notifications@github.com>:

**Comment by ZoniThePothead** [comment]
By colony center you mean town hall?
 @Edit and how do i know what colony id i have?

**Comment by Raycoms** [comment]
Yes

**Comment by ZoniThePothead** [comment]
Could you tell me how to check my colony id, chef?

**Comment by ZoniThePothead** [comment]
nvm i figured out, done, now my colonists froze
@edit all mobs and colonists froze
@edit2 Everything froze, also the chunks that were loading, now no more

**Comment by ZoniThePothead** [comment]
Any fix master?

**Comment by Raycoms** [comment]
Not yet, unfortunately, i'm currently full of university work, you can
paste your world here, if you want me to take a look at it.

2018-05-10 23:38 GMT+01:00 ZoniThePothead <notifications@github.com>:

**Comment by ZoniThePothead** [comment]
the folder is like 50 mb and i cant upload it anywhere
@edit it literally turns off my browser as i try to upload on various sites

**Comment by ZoniThePothead** [comment]
We could try with email or smth

**Comment by Raycoms** [comment]
Upload it on dropbox or google drive =)

**Comment by ZoniThePothead** [comment]
not possible it crashes my browser after i click "upload folder" and i check the world folder, might be cause it contains 644000 files, all from minecolony, called "chunks" i suppose

**Comment by YaibaToKen** [comment]
@ZoniThePothead zip the folder and then attempt to upload that

**Comment by Raycoms** [comment]
you can remove the chunks folder from that.

2018-05-11 18:31 GMT+01:00 Bruno Miguel Faria Gaspar <
notifications@github.com>:

**Comment by ZoniThePothead** [comment]
https://www.dropbox.com/s/bthh47wnlptrmlx/World.rar?dl=0 there!

**Comment by Raycoms** [comment]
Still issues with that, sorry only coming to it now!

**Comment by winex** [comment]
is it fixed in master now?
maybe this range should depend on townHall's level and maxed at config option? like `max( 1<<(LEVEL+1), config_option )`, but this should be fitted into that range somehow to allow colonies larger than 2^(5+1) chunks

**Comment by Nightenom** [comment]
Colonies larger than circle with radius of 64 chunks? This should be limited somewhere around today's average render distance (which doesn't go over 20 in most big modpacks). I think using a command there is enough, maybe we can increase the default radius, which is 8 now (=128 blocks), to 10 (=160 blocks)

**Comment by winex** [comment]
@Nightenom no, just want some good func. but what do you think of increasing colony size with level? iirc, there is no such feature yet

**Comment by Nightenom** [comment]
Nah, it looks good but imagine your wall placement and townhall levelling up or you waiting for the townhall level 5

**Comment by Raycoms** [comment]
Fixed now
