### ISSUE TITLE
Warehouse buildfield changes over levels

### ISSUE THREAD

**Issue by Nightenom** [ldtteam/minecolonies#2445]
### Minecolonies version

version 1.12.2-0.8.8208 (forge 2681)

### Expected behavior

- warehouse building (level 1 -> 2) stays in the same field
- after building to level 1 tape should disappear

### Actual behaviour

- the building field rotates (probably it looks like rotating) when trying to build to level 2
- after building to level 1 tape does not disappear

### Steps to reproduce the problem

1. place warehouse constructor and look where tapes are
2. build level one and ask for upgrading to level two
3. building fields do not match

Possible solution - add an option to config for displaying ghost building before starting building level 0

![inked2018-05-12_13 49 30_li](https://user-images.githubusercontent.com/17338378/39957279-bcf8eb7e-55f0-11e8-9984-803f4cd6b726.jpg)

**Comment by PoroUsedSnax** [comment]
Have you used the building tool to place your warehouse? With that you can view a ghost image of the building you are trying to place.

**Comment by Nightenom** [comment]
You got it, I didn't -> this repository looks like some kind of guidebook is in development?

Still, tapes (which are placed when you place building's founding block) should be as big as the biggest level of the building, so a player can be surprised by the builder doing his job and not being spoiled by building tool.

**Comment by PoroUsedSnax** [comment]
Are you saying you didn't get a tool, or am I missing something? If the former, you can craft a building tool, not sure on the recipe though, think it's on the wiki (Linked below)

There is a guidebook in our modpack, made for the Guidebook mod, although it's somewhat outdated now, it's the same content (bar updates) that is available on our [wiki](https://wiki.minecolonies.com). The tape should always be the size of the largest level, as the schematics are supposed to all match the same footprint, even if the buildings themselves are smaller in lower levels. It does seem to be an issue that the tape can place incorrectly, not 100% though, I'm not one of the mod devs.

**Comment by Nightenom** [comment]
Sorry for the misunderstanding, I got the tool from a supplyship. The crafting recipe is still available. Thank you for the link to the wiki, but I suggest making a standalone book (like in TConstruct, not a mod dependent) or just simply put a book with the link to the wiki when player place supply-ship/camp.

For me, it looks like almost all level 0's tapes (building's founding block) are wrong. Level 1+ seems to be good.

**Comment by marchermans** [comment]
There is no level 0.

**Comment by marchermans** [comment]
Place the building with the tool. We sadly can not prevent you Fram placing the block yourself yet. But are working on it.

@PoroUsedSnax I tested this wirh current release this works just fine when he uses the wand. When he just places the block it is off. This is a known bug and we tell everyone to use the wand instead of the block. I have written it down to look into. Closing this.

**Comment by Nightenom** [comment]
@OrionDevelopment That's exactly what I didn't want to hear (a player can't be surprised by builder doing his job as (s)he already know how the building looks like), but I understand you it's much easier to write it like this.

**Comment by marchermans** [comment]
@Nightenom I know that this is not wahr you wanted to hear. But all our developers are currently under a heavy load and this is a known issue. Join our discord and we are happy to talk about it. However as stated it is known as such, it will be resolved eventually however in the interest of keeping the issues as clean as possible untill the core teams comes back from their rl stuff, Uni etc, I am closing issues for which there currently exists a workaround. I know it is not optimal and it is not perfect. But please bear with us and keep in mind that we are humans who do this for free with limited time on our hands.

I hope to have informed you enough why I closed this issue the way I did. I did not want to offend you. 

Greets. 

Orion
