### ISSUE TITLE
Crash when opening barracks block

### ISSUE THREAD

**Issue by Nightenom** [ldtteam/minecolonies#2447]
### Minecolonies version

version 1.12.2-0.8.8208 (forge 2681)

### Expected behavior

- no crash :)

### Actual behaviour

- crash

### Steps to reproduce the problem

1. will be hard to reproduce since I did many things before (but the world seems to be still corrupted)
2. barracks level 2
(warning: the zip world file contains rar for better compression)

[crash-2018-05-14_09.49.55-client.txt](https://github.com/Minecolonies/minecolonies/files/1999797/crash-2018-05-14_09.49.55-client.txt)
[New World.zip](https://github.com/Minecolonies/minecolonies/files/1999808/New.World.zip)

**Comment by Kisonu** [comment]
This issue is also being recreated with the current updated version and the level 3 smelter. Selecting upgrade is causing the crash below.
[crash-2018-05-30_01.04.45-client.txt](https://github.com/Minecolonies/minecolonies/files/2052738/crash-2018-05-30_01.04.45-client.txt)

**Comment by Raycoms** [comment]
also fixed.
