### ISSUE TITLE
quest

### ISSUE THREAD

**Issue by ironlionThefirst** [ldtteam/minecolonies#2450]
Where is the quest files so i can play this single player?
can someone pls help me

**Comment by Nightenom** [comment]
What do you mean by quest files? You can play this mod without problem in singleplayer. There ~is~ was GuideBook but you need to install the mod first.
@Raycoms when you ported c4eb328 through 951cc31 to the main thread, it seems that you forgot to port other changes made in this commit. I'm going to make a pull request for that if it will work

**Comment by Nightenom** [comment]
After #2456 will get approved and a new build will be available online, you should get a Guidebook immediately when joining your world
If it was the thing you wished to have, please close this issue

**Comment by PoroUsedSnax** [comment]
Since #2456 is merged, and there seems to be no follow up from the original creator, I will be closing this.
