### ISSUE TITLE
Build Tool Important Visual Bug

### ISSUE THREAD

**Issue by dave1505** [ldtteam/minecolonies#2451]
### Minecolonies version

version 1.12.2-0.8.8213

### Expected behavior

- Build Tool rendering builds properly
### Actual behaviour

-buildings textures and apparent shape completely messed up

### Steps to reproduce the problem

1. use the build tool anywhere with anything

![2018-05-16_16 13 56](https://user-images.githubusercontent.com/34339148/40126410-324bc310-5925-11e8-9714-f8213dba6b1c.png)
![2018-05-16_16 14 06](https://user-images.githubusercontent.com/34339148/40126413-3278d01c-5925-11e8-9250-246ccda30ff5.png)
![2018-05-16_16 14 21](https://user-images.githubusercontent.com/34339148/40126416-32a48afe-5925-11e8-828d-e56c02eb05c1.png)
![2018-05-16_16 14 31](https://user-images.githubusercontent.com/34339148/40126417-32d489b6-5925-11e8-814e-10861f7c4b3a.png)

**Comment by marchermans** [comment]
You are using a shader. Shaders are not supported for the near future.

**Comment by SulpherStaer** [comment]
Also, the new rendering causes blocks to render only the backfaces instead of the front faces. So this is a known issue related to the VBO rendering.

**Comment by marchermans** [comment]
@sylcai what do you mean?

**Comment by Nightenom** [comment]
@OrionDevelopment 
![2018-05-17_13 27 07](https://user-images.githubusercontent.com/17338378/40174667-1065f08e-59d6-11e8-91df-3ca92b44fc9a.png)

**Comment by marchermans** [comment]
Are you using a shader or standing inside it?

**Comment by SulpherStaer** [comment]
No, and no.
![2018-05-17](https://user-images.githubusercontent.com/5037244/40177506-1688f9d0-59df-11e8-9ae1-a36135ac02ab.png)

**Comment by Raycoms** [comment]
I think this is the problem because of the substitution blocks at that
location.

2018-05-17 13:26 GMT+01:00 Marc Hermans <notifications@github.com>:

**Comment by Raycoms** [comment]
Carlsanor puts his substitution blocks everywhere so that is good possible.

2018-05-17 13:32 GMT+01:00 Silvester <notifications@github.com>:

**Comment by PoroUsedSnax** [comment]
This issue is one I mentioned in #2399.

> I can confirm this is an issue, and more specifically is related to the Placeholder Block (Not the solid one) Either not rendering due to a bug, or when a change was made to remove their rendering, the blocks around it aren't having their faces rendered at all where they would be touching the Placeholder

**Comment by marchermans** [comment]
Right yep sorry

**Comment by marchermans** [comment]
Fixed in #2454

**Comment by marchermans** [comment]
Shaders still not supported.
