### ISSUE TITLE
Couriers behave strangely!

### ISSUE THREAD

**Issue by ZzylinN** [ldtteam/minecolonies#2452]
Minecolonies version 1.12.2-0.8.8213 (But it was on earlier versions)

Couriers bring into the building things that they should not bring! On a screech it is visible that that on the sheep farm lie eggs and pig meat which are not a drop at the pig. 
https://hostingkartinok.com/show-image.php?id=d095bc56fcab5ce590ddb91174c4f13f

On another sheep farm (seen in the screenshot) are bows. This all brings the courier. and so constantly.
https://hostingkartinok.com/show-image.php?id=800fb5c3c8c46e1250de2e801f56fe14

But it can be sapling and wheat seeds and beet seeds

Also, the courier carries eggs to all houses as food, but since the eggs are not edible my settlers start to starve. On the screen, the inventory of the guard
https://hostingkartinok.com/show-image.php?id=aca42ae06eedea4cb30c28bcd8eb6b21

In the warehouse, a mess is created, things do not stack up, which reduces the available space
https://hostingkartinok.com/show-image.php?id=fc96498c7a23aa980d91355ffa6131fb
https://hostingkartinok.com/show-image.php?id=ab5c49808411a82534d51332b641c026

**Comment by Raycoms** [comment]
Things should be more efficient now in most of these cases
