### ISSUE TITLE
Warehouse sorting no longer functions

### ISSUE THREAD

**Issue by BonaireDreams** [ldtteam/minecolonies#2453]
### Minecolonies version

version 0.8.8147

### Expected behavior

- Warehouse inventories should behave like all other inventories and respect sorting commands added by mods (Inventory tweaks)
- Delivery men seem to create multiple stacks of the same items if there are earlier empty slots in the inventory due to them removing a different item. This causes say 4 stacks of wool with 1-10 items in each stack, currently we need to manually click each stack and move them together. If inventory tweaks worked again we could double click and all similar items would stack together.

### Actual behaviour

- Unable to double click in the inventory to sort all similar items together. This worked in previous versions of minecolonies.

### Steps to reproduce the problem

1. Install inventory tweaks
2. configure middle mouse button double click to sort inventories
3. observe chests and player inventory sort when button is pressed
4. Minecolonies warehouse inventories do not sort (neither do they show the sorting buttons as other inventories do)

**Comment by PoroUsedSnax** [comment]
It is possible to add compatibility for inventory tweaks by adding the following code to your InvTweaksCompatibility.xml
```
<root>
   <chest class="com.minecolonies.coremod.inventory.ContainerRack" row_size="9" large_chest="false"/> <!-- Chests to show the sorting modes buttons on -->
</root>
```
I do feel that a change to respect this mod and similiar would be a nice addition though.

**Comment by marchermans** [comment]
@PoroUsedSnax it is however not possible from our side. Hence the existsence of that file.

**Comment by PoroUsedSnax** [comment]
So, does this have to be added to the mod from InventoryTweaks' side? It seems a good amount of modded storage systems work with it already, such as the items from Iron Chests.

**Comment by Raycoms** [comment]
Yes, it has to be added to it. And these chests work because they're actually chests.
