### ISSUE TITLE
Re-positioning town hall deletes the podium

### ISSUE THREAD

**Issue by TheLeadZombie** [ldtteam/minecolonies#2455]
### Minecolonies version

version latest

### Expected behavior

- will place podium back down

### Actual behaviour

- deletes the podium saying you can not have more than 1 town hall

### Steps to reproduce the problem

1. XYZ
2. ZYX
3. ...
4. Profit

**Comment by Nightenom** [comment]
By the podium, you mean town hall block? Reposition now do not care about building per colony limitation (like #2443)

**Comment by Raycoms** [comment]
I know this bug, I'll fix it soon.
