### ISSUE TITLE
Toolcrafting / Forge still not implemented

### ISSUE THREAD

**Issue by SulpherStaer** [ldtteam/minecolonies#2462]
### Minecolonies version

version 1.12.2-0.8.8218

### Expected behavior

-A 3x3 crafting grid or the Forge / Toolmaker implemented

### Actual behaviour

- Still not implemented, and don't know why / can't find the reason why with search
- What still needs to be done to make the forge functioning?

### Steps to reproduce the problem

No problem to reproduce, this is a question.

**Comment by Raycoms** [comment]
We'Re working on it. Tbh the 3x3 grid crafting is ready already. What's not ready is the integration with the request system. 3x3 crafting won't help anything if the worker can't fulfill requests from it.
Just a bit more patience, me and @OrionDevelopment will work on it in the next week.

**Comment by SulpherStaer** [comment]
Thanks! - Sorry if it seemed like I was impatient, but a year ago it was delayed. So I was just curious what the time line was on it.

This is a wonderful mod, and probably takes a lot of effort.
