### ISSUE TITLE
deliveryman bug

### ISSUE THREAD

**Issue by demon57730** [ldtteam/minecolonies#2464]
minecolonies-universal-1.12.2-0.8.8237.jar

forge-1.12.2-14.23.3.2655-universal.jar

probleme:

the delivery person does not take the food which is in the inventory (table business, entrepreneur, other)
so as he does not go he does not go to the food warehouse and he does not deliver food.

**Comment by Nightenom** [comment]
@demon57730 Can you try the latest version?
