### ISSUE TITLE
Problems with the restaurant. Does not feed settlers and does not raise in waiter level.

### ISSUE THREAD

**Issue by ZzylinN** [ldtteam/minecolonies#2465]
### Minecraft with mods

ChickenHerders is constantly starving. He runs to the restaurant and stands.
https://hostingkartinok.com/show-image.php?id=a52130584513dafa76ccca11199f093d

Satiety is not filled up.
https://hostingkartinok.com/show-image.php?id=f652c5269fe7759752e7ed0f69e82ff5

The restaurant has food available.
https://hostingkartinok.com/show-image.php?id=836ae45e879c1ed068e5b3c9a9d7e233

The settler works in the restaurant and the settler also has food.
https://hostingkartinok.com/show-image.php?id=e2efb8bdb10e0d49002f37a2a9c9708e

Restaurant (wooden) 4 levels. The settler who works does not rise in the level.
https://hostingkartinok.com/show-image.php?id=da78e00e406ac770385e7c2881a89c74

**Comment by Kisonu** [comment]
I have also noticed the restaurant workers levels not increasing. Can't say anything on the food thing because i usually don't pay that much attention.

**Comment by aelfwyne** [comment]
Similar issues. Have baker, have restaurant, have farmer farming wheat, bread seems to be baked (albeit slowly)... but workers get hungry and just stand around refusing to work. I have to manually feed each one like a baby.

Also, they do NOT notify that they are hungry. You have to hunt them down and feed them. There should be a notification just like if they are waiting on a tool.

**Comment by Raycoms** [comment]
Which minecolonies version are you using?
