### ISSUE TITLE
Builder stands idle after "Build request Created", not building(Server)

### ISSUE THREAD

**Issue by LightPrince** [ldtteam/minecolonies#2467]
1.12.2 latest Minecolonies version

version 1.12.2-0.8.8242

### Expected behavior

- Builder stands idle after "Build request Created", not building

### Actual behaviour

- Builder does what he/she is supposed to do

### Steps to reproduce the problem

1. Go for a building
2. click Building or Upgrade
3. Builder stands idle not building

**Comment by Raycoms** [comment]
The build request is that for a building of a higher level than the builders building level?

**Comment by LightPrince** [comment]
@Raycoms , well i just figured the problem out, It was that Mine colonies is not compatible with a mod called [**Extended Days**](http://www.9minecraft.net/extended-days-mod/) which uses silent-lib, whenever i build a building by click "Build Building", the chat says Build request created and the Builders doesn't Reply or react to the call till before Dawn(using extended days), Now everything Works Fine , I hope this Info about Compatibility Helps you guys in your future Development for this Amazing MOD , Thanks for your Reply :)
