### ISSUE TITLE
[BUG?] Cannot enable MeeCreeps to break blocks inside the colony

### ISSUE THREAD

**Issue by hron84** [ldtteam/minecolonies#2471]
### Minecolonies version

version 0.8.7582 from curse

### Expected behavior

- Click on Town City
- Check events
- Allow MeeCreep to break block

### Actual behaviour

- Nothing happens if you press [ADD]

![2018-05-23_06 50 55](https://user-images.githubusercontent.com/88636/40404064-0f578b06-5e56-11e8-8888-ef7eca1bdf93.png)

**Comment by marchermans** [comment]
that Looks like you spelled meecreeps wrong
it says meecreps.

**Comment by Raycoms** [comment]
That's weird, because that's automatic. So meecreeps might have done
something wrong.

2018-05-24 18:52 GMT+01:00 Marc Hermans <notifications@github.com>:

**Comment by marchermans** [comment]
You are right it says meecreps.

**Comment by Raycoms** [comment]
actually add will add it to the list on the other side, this should be fixed
