### ISSUE TITLE
1.12.2 close town hall

### ISSUE THREAD

**Issue by novice112** [ldtteam/minecolonies#2472]
### Minecolonies version : minecolonies-universal-1.12.2-0.8.8242

version 1.12.2 

### Expected behavior

- i don't know...I want to be able to build anywhere ... not just near the town hall

### Actual behaviour

- I can only go to the city hall ... more precisely, even in the town hall

### Steps to reproduce the problem

1. i want to build miner ...
2.I place the building
3.press to build the building
4. and tells me that I can only near the town hall
sorry for bad english ;)

**Comment by Ragnarok96** [comment]
You have to place all colony buildings by default within a 9 chunk radius of where you first placed the town hall (a 17x17 chunks area) centred on that initial chunk. If you want more, I belive you can edit the radius a colony protects/claims via the config file.

**Comment by PoroUsedSnax** [comment]
If you want to extend the build area of your colony, as Ragnarok explained you can change the radius in the config, but this will only change for new colonies, what you would want to do is use this command: `/mc colony claim [colony: colony id] [range: number in chunks] [add: true/false]` make sure to do this from the centre of your colony as to get an even claim radius.

**Comment by Kisonu** [comment]
I've seen this issue as well. It can take several tries to be allowed to place a building even as close as (f3 menu) 20 blocks from town hall. I DID notice that it seemed to give more problems when my biome was registered as deep ocean or ocean. Is this something that could cause an issue? I play with a flatlands biome mod than can sometimes not register the biome as "flatlands" and instead registers as what the minecraft generator would have had there..
