### ISSUE TITLE
[bug] Builder will not use taught recipes in certain situations. 1.12 Build 8242.

### ISSUE THREAD

**Issue by Ragnarok96** [ldtteam/minecolonies#2475]
### Minecolonies version

Build# 8242

### Expected behavior

When the builder is taught a recipe, if the materials to make the recipe are placed in his inventory AFTER he has already made a request for a specific item, his request should then cancel/fulfill itself as he is able to craft the needed items himself.

### Actual behaviour

The request remains and the builder does nothing, however if you cancel the request then the AI realises that the builder does in fact have the resources to craft the required items and he will continue building as normal. This makes it seem like there is a check not in place that there should be, with reference to the items in the builders inventory or chest inventory and the learned recipes.

### Steps to reproduce the problem

(In this example I will demo with wood planks which is what I discovered the issue with)

1. Teach builder how to make wood planks from wood logs.
2. Schedule a building requiring wood planks while the builder has no logs or planks in any of his chests/inventories.
3. The builder will request wooden planks.
4. Place wooden logs in the builders inventory.
5. The builders request will not clear, click cancel.
6. The builder then realises he can actually craft the planks himself and will continue to build as normal.

**Comment by Ragnarok96** [comment]
As a side note, I haven't tested this with other workers, as it may apply to all workers following the same scenario as detailed above if they also have recipes that can be completed for requests in this manner via their own 2x2 craft grids.

**Comment by marchermans** [comment]
7625597484987 possible combinations that Need to be check when the inventory is full.
I talked to him on discord. Closing.
