### ISSUE TITLE
Shingle blocks do not place correctly upside down

### ISSUE THREAD

**Issue by kedamono** [ldtteam/minecolonies#2478]
### Minecolonies version

version 1.12.20.8.8266

### Expected behavior

- Placing the different shingle blocks upside down that they would behave the same as upside down stairs.

### Actual behaviour

- They place facing the opposite direction that stairs are place. Also, when you try to create an upside down inside or outside corner, the corner block behaves oddly.
![2018-05-24_15 14 20](https://user-images.githubusercontent.com/23420636/40518744-f35306b2-5f70-11e8-8c45-1ae76799d3cc.png)
![2018-05-24_15 16 05](https://user-images.githubusercontent.com/23420636/40518748-fadba6f0-5f70-11e8-9584-2d481494e85c.png)
![2018-05-24_15 16 16](https://user-images.githubusercontent.com/23420636/40518757-02a76e50-5f71-11e8-85f1-42d6744ff73f.png)
![2018-05-24_15 17 38](https://user-images.githubusercontent.com/23420636/40518767-0e45022c-5f71-11e8-9d56-457ce6646351.png)
![2018-05-24_15 17 55](https://user-images.githubusercontent.com/23420636/40518769-116da3b4-5f71-11e8-8220-2ad5cd894b89.png)
![2018-05-24_15 18 38](https://user-images.githubusercontent.com/23420636/40518770-13aaf12c-5f71-11e8-9ff5-00101bf3421f.png)
![2018-05-24_15 18 43](https://user-images.githubusercontent.com/23420636/40518797-33b534e6-5f71-11e8-9247-1574803cd6b6.png)
![2018-05-24_15 19 15](https://user-images.githubusercontent.com/23420636/40518811-39ddced2-5f71-11e8-8515-1217ac5f55fd.png)
![2018-05-24_15 19 27](https://user-images.githubusercontent.com/23420636/40518813-3d0e10a8-5f71-11e8-8e3d-cc94df976f21.png)

### Steps to reproduce the problem

1. Facing a two block wall, place a shingle block such that it will be placed upside down.

**Comment by marchermans** [comment]
Stupid question: But why is this supported. Singles are not supposed to be used that way IRL either.

**Comment by kedamono** [comment]
Well, it could be that folks want to use them under buildings when playing Skyblocks. Also, some folks like to do unusual builds and upside down shingles would be part of that.

**Comment by Asherslab** [comment]
This will be fixed in my upcoming Shingles PR.

**Comment by Asherslab** [comment]
Although yes, i'd love to remove the upsidedown shingles all together. but it was voted against
