### ISSUE TITLE
Very strange behavior of settlers after the transition from version 1.12.2-0.8.8242 to version 1.12.2-0.8.8298

### ISSUE THREAD

**Issue by ZzylinN** [ldtteam/minecolonies#2479]
### Minecraft with mods

The settlers stand still. When you click on the "Call employee" button in the building do not respond.
When you click on the "call a resident" button in the town hall calls everyone, but it does not help.
The workers stopped working. It is necessary to re-appoint workers. When appointing workers, they behave strangely. Do not change clothes, for example, when appointing a former shepherd shepherd to the position of a miner, he still stands in farm clothes, does not ask for anything and does nothing. When appointing a former knight again to the position of a knight, he runs around with a bow and not with a sword!

When appointing a courier, a miner (a former shepherd) asks for scissors, an axe and wheat!

**Comment by marchermans** [comment]
@Raycoms

**Comment by Raycoms** [comment]
Weird, I'll run some tests

**Comment by ZzylinN** [comment]
I returned to version 1.12.2-0.8.8242. Settlers behave as they should.

**Comment by Raycoms** [comment]
Currently setting up a test colony in a previous version.

2018-05-26 2:13 GMT+01:00 Sasha <notifications@github.com>:

**Comment by Raycoms** [comment]
Merged a hotfix right now, there should be a new version in the next 30 minutes.
