### ISSUE TITLE
1.12 latest version crashing

### ISSUE THREAD

**Issue by Zygus42** [ldtteam/minecolonies#2482]
### Minecolonies version
minecolonies-universal-1.12.2-0.8.8315
forge-1.12.2-14.23.4.2703-installer-win

Was using version minecolonies-universal-1.12.2-0.8.8208 and it's fine, but the latest version (as above) causes an almost immediate crash upon starting server.  Does not cause a crash report, but does have details in the log:

[latest.log.txt](https://github.com/Minecolonies/minecolonies/files/2041279/latest.log.txt)

**Comment by Raycoms** [comment]
This doesn't seem to be related to us:

	at farseek.core.FarseekClassTransformer.replacements$lzycompute(FarseekCoreMod.scala:55) ~[Streams-Farseek-1.12-2.2.5.jar:?]
