### ISSUE TITLE
Miner "deletes" blocks when "builderInfiniteResources" is enabled

### ISSUE THREAD

**Issue by JAguiar939** [ldtteam/minecolonies#2488]
### Minecolonies version

version 0.9.7587

### Expected behavior

- After miners dig the vertical shaft, they branch out horizontally, mining and gathering any blocks they break.

### Actual behaviour

- When "builderInfiniteResources" is enabled in the config, the miner will delete blocks when branching out horizontally and not gather any of them. This does not happen while digging the vertical shaft.

### Steps to reproduce the problem

1. Set "builderInfiniteResources=false" to "builderInfiniteResources=true" in minecolonies.cfg
2. Build mine and hire a miner
3. Wait for miner to complete the vertical shaft
4. Observe miner inventory while they branch out horizontally.

**Comment by Raycoms** [comment]
Yeah, on purpose. Infinite block means -> your colony doesn't need resources ergo doesn't produce resources.
