### ISSUE TITLE
No chat messages from workers

### ISSUE THREAD

**Issue by Rosomah** [ldtteam/minecolonies#2496]
### Minecolonies version

minecolonies-universal-1.12.2-0.8.8213

### Expected behavior

- They should say what resources or tools they need.

### Actual behaviour

- The only messages that I'm receiving are those from barbarian raids and whenever a builder started or finished building.

**Comment by Asherslab** [comment]
You may see what resources and tools are needed Via the Clipboard item. These messages were causing too much spam

**Comment by Rosomah** [comment]
The clipboard item?

**Comment by Asherslab** [comment]
correct, the clipboard item
https://github.com/Minecolonies/minecolonies/blob/version/1.12/src/main/java/com/minecolonies/coremod/items/ItemClipBoard.java

**Comment by Rosomah** [comment]
Ah, didn't even know this existed. Thank you.
