### ISSUE TITLE
Ability to change the housing of citizens in the town hall

### ISSUE THREAD

**Issue by PoroUsedSnax** [ldtteam/minecolonies#2508]
### Expected behavior

- Player is able to assign or unassign citizens living in the town hall

### Actual behaviour

- Player is not able to assign or unassign citizens living in the town hall

**Comment by Jessman5** [comment]
Are you guys working on this? I have the same Problem atm.
eg. the Miner was automatically assigned to the town hall and the way to the mine too far. theres a citizens hut near the mine, but I can't assign the miner to it. He's basically stuck to the town hall.

**Comment by Nightenom** [comment]
Hmm, just turn to manual hiring and fire a citizen from a citizen hut and assign your miner there

**Comment by Jessman5** [comment]
@Nightenom That is not possible, since the citizens automatically assigned to the townhall are not listed in the list of assign-able citizens..

Next time I'm playing I'll make screenshots if needed.

**Comment by Nightenom** [comment]
Weird, since when you turn to manual housing it should work, try manual housing and hiring too.

**Comment by Jessman5** [comment]
I did...

**Comment by TheYoxy** [comment]
I'm actually working on, I'll ping you when it is fixed

**Comment by Jessman5** [comment]
@TheYoxy Thank you!

**Comment by Jessman5** [comment]
@Raycoms Is there a reason why this is closed without any comment on this?

**Comment by Raycoms** [comment]
The townhall doesn't house citizens anymore, so it's not relevant anymore

Am Mo., 25. März 2019 um 08:45 Uhr schrieb Jessman5 <
notifications@github.com>:

**Comment by Jessman5** [comment]
Thank you
