### ISSUE TITLE
Horse Breeder (Stable)

### ISSUE THREAD

**Issue by Raycoms** [ldtteam/minecolonies#2511]
Since Asher Forgot to open these:

We could need a horse breeder as well similar to the other Breeders.

What's needed:
- Specialized AI Class
- Specialized Building
- Building Design
- Block Texture

**Comment by faeythinpixels** [comment]
Horse/llama/donkey stables could probably be handled by the same building type with the use of a GUI toggle to select which animal you would like to breed.

**Comment by Raycoms** [comment]
Closed in favor of joint issue.
