### ISSUE TITLE
Alpaca Breeder

### ISSUE THREAD

**Issue by Raycoms** [ldtteam/minecolonies#2513]
Since Asher Forgot open these:

We could need a alpaca breeder as well similar to the other Breeders.

What's needed:
- Specialized AI Class
- Specialized Building
- Building Design
- Block Texture

**Comment by WrongWeekend** [comment]
By alpaca I assume you mean llama. In the case of llamas and other mounts, it may be necessary for some other citizen to be able to use them, as there is little point in breeding large numbers of them for only the player to use.

**Comment by pip69** [comment]
What if a citizen having a llama or horse gave them extra inventory space and/or move speed?
Guards learning to fight from horse? 
Mounts used by citizens could have a lifespan before they need replacing.
Mounts would also need food regularly.
The building could only hold X# of mounts per level.  
A separate building "Stable" would only hold extra mounts, and uses the citizen working on Llama or Horse.
Horses would have move speed.
Llama would have more inventory space.

**Comment by Raycoms** [comment]
Closed in favor of joint issue.
