### ISSUE TITLE
Cannot craft supply ship

### ISSUE THREAD

**Issue by theoneandonlydonnie** [ldtteam/minecolonies#2514]
### Minecolonies version

version 0.8.4191

### Expected behavior

- When placing five boats, I expect the supply ship to be in the output box

### Actual behaviour

- I place five boats in the crafting table in the formation as stated in the wiki recipes and no supply ship shows in the output

### Steps to reproduce the problem

1. craft five boats
2. place them in the crafting table

I am wanting to test the mod out so I only have Minecraft Coder Pack 9.42, Forge Mod Loader 8.0.99.99, Minecraft Forge 14.23.3.2655 and Minecolonies loaded. I tried it with and without my resource pack and the issue remains

**Comment by MineShadow7** [comment]
Update to the newest version, please.

**Comment by theoneandonlydonnie** [comment]
I did update it to version 0.8.7582 and the issue still remains
