### ISSUE TITLE
Suggestion: Happiness during Barbarian raids

### ISSUE THREAD

**Issue by wyattzastrow** [ldtteam/minecolonies#2519]
When barbarians are attacking colonist have a habit of getting in the way of arrows/shurikens/swords.  Maybe reduce or have no penalty to player kills on colonist while a barbarian attack is underway.
Thanks

**Comment by MineShadow7** [comment]
This could be abused to kill citizens with low stats btw...

**Comment by wyattzastrow** [comment]
True but there are easier ways to kill your citizens (without penalty) that don't involve waiting for a barbarian raid.  I'm not sure if it's possible but you could set a check to see if they died within a certain distance of a barbarian.
