### ISSUE TITLE
Exception in Server Tick Loop

### ISSUE THREAD

**Issue by NielsPilgaard** [ldtteam/minecolonies#2524]
### Minecolonies version

0.8.8518

### Expected behavior

- The player joins the game and the world loads

### Actual behaviour

- The world crashes

### Steps to reproduce the problem

I don't know unfortunately

Crashlog: https://pastebin.com/HT6vsE9W
Latestlog: https://pastebin.com/0smmqrg7
Original report: https://github.com/NillerMedDild/Enigmatica2/issues/41

**Comment by Raycoms** [comment]
duplicate of https://github.com/ldtteam/minecolonies/issues/2525

**Comment by NielsPilgaard** [comment]
That issue didn't exist when I opened mine. Thanks for looking into it regardless!
