### ISSUE TITLE
MineColony Server Crash 

### ISSUE THREAD

**Issue by KingSnailtan** [ldtteam/minecolonies#2525]
### Minecolonies version

Curse minecolonies-universal-1.12.2-0.8.8618

### Expected behavior

Nothing I guess?

### Actual behaviour

Once I enter and leave a colony my entire server crashes
Here is a crashreport and latest log for you
Crashrep: https://hastebin.com/ujahajokux.sql
Latest.log: https://hastebin.com/solopuyuse.sql

### Steps to reproduce the problem

1. Go into a colony
2. Leave that colony
3. Be happy that your server crashed. Or that you crashed mine. You know what I mean.
4. Profit...?

**Comment by Raycoms** [comment]
I checked this, this is really weird and should not happen, somehow your server seems to have corrupted our files which consider colony claim. Can you check if on your server the colony claim works correctly?

**Comment by KingSnailtan** [comment]
The world doesnt exist anymore, but the modpack I used was enigmatica 2. It
happend right after i built my farmer. The world became unplayable, so now
I dont use it and minecolony anymore, because i dont want it to happen
again.

Raycoms <notifications@github.com> schrieb am So., 17. Juni 2018, 02:42:

**Comment by Raycoms** [comment]
Quite weird, we never had any of these problems, it seems like something
corrupted our data, we're going to rewrite this part to avoid this from
happening soon. But something else must've caused this.

2018-06-16 22:21 GMT-03:00 KingSnailtan <notifications@github.com>:

**Comment by Wissi** [comment]
I guess we close this as it has been un-reproducable issue? Most liekly another mod causing issues?

**Comment by Nightenom** [comment]
I think we can
