### ISSUE TITLE
Mossy Stone Brick Monster Egg in Warehouse Level 5 build

### ISSUE THREAD

**Issue by sickhippie** [ldtteam/minecolonies#2526]
### Minecolonies version

version 1.12.2-0.8.8618

### Expected behavior

- building Birch medieval warehouse level 5 with 1 mossy brick.

### Actual behaviour

- Upgrade template calls for 1 Mossy Stone Brick Monster Egg

### Steps to reproduce the problem

1. Build birch medieval warehouse up to level 4
2. Try to upgrade to level 5
3. Get stuck on mossy stone brick monster egg

Issue was fixed for Spruce Medieval warehouse (https://github.com/Minecolonies/minecolonies/issues/2459), but still exists in birch medieval (and potentially other level 5 medieval warehouses).

**Comment by Nightenom** [comment]
Will fix in few minutes

**Comment by Nightenom** [comment]
Btw: `Mining a monster egg with a Silk Touch tool drops the block that the monster egg is disguised as, and does not spawn the silverfish.`
