### ISSUE TITLE
Placing Buildings with Wand gives 'place over pool' error

### ISSUE THREAD

**Issue by TheDeinonychus** [ldtteam/minecolonies#2528]
### Minecolonies version

version 0.8.5086 
Minecraft verion 1.10.2

### Expected behavior

- When placing buildings with the wand, it should use the item from inventory and place the building in the location, rotation, and style selected. 

### Actual behaviour

- Trying to place a building (regardless of which type) with the building wand fails and returns the same error as when trying to place the supply ship in an invalid location. Placing a building by hand (using the building item from inventory) still works. Placing with building wand had worked as expected in a previous game using the same version of Minecolonies and modpack. 

### Steps to reproduce the problem

1. Started new flat world
2. Placed a Supply Camp (previously had used a Supply Ship)
3. Attempted to place the Town Hall using building wand.
4. Now fails saying it needs flat ground of at least 16x17. Placing by hand with the inventory item still works. 

Tried on a new flat world, placing a Town Hall without first placing a Supply Camp or Supply Ship. Still gives the same 'flat ground' error when trying to place using the wand.

Trying to place down user-made decorations returns the error "You have already placed a supply ship or supply camp!" despite not having placed a supply ship or camp.

**Comment by Raycoms** [comment]
You're around 3000 versions behind, please try to update to one of our
latest builds.

2018-06-11 22:30 GMT-03:00 TheDeinonychus <notifications@github.com>:

**Comment by TheDeinonychus** [comment]
Quite possibly. I haven't played in a good while. I'll look into which version for MC 1.10.2 is most recent. But right now, I'm trying to narrow down what's doing this. Looks like it's a mod conflict at the moment, just trying to figure out which mod in case it's a conflict that's still persistent.

**Comment by Raycoms** [comment]
Ahh 1.10, yeah our 1.10 version is also quite outdated.

2018-06-11 22:53 GMT-03:00 TheDeinonychus <notifications@github.com>:

**Comment by TheDeinonychus** [comment]
Heh, I figured as much. But till certain key mods that I love all update to a newer version of MC, I don't mind playing an outdated version.

**Comment by TheDeinonychus** [comment]
Ok, the issue seems to be some sort of conflict with the 'Compact Machines' mod. Oddly enough, it also seemed to have had caused some of the buttons in the building tool's interface from working. Specifically the buttons to click through the different buildings, though the drop-down menus still worked.
