### ISSUE TITLE
Voice Acting needs improvement!

### ISSUE THREAD

**Issue by DarkWhiteParadox** [ldtteam/minecolonies#2530]
The voice acting is horrible!

Is it possible to disable this/ do you have plans to redo it?

A lot of the speech is hard to understand, the accents don't sound genuine, im pretty sure one of the female NPC's is voiced by a male pretending to be female (very cringy).

Also side note: is there somewhere I can find a way to change the building schematics/ download a pack that changes them? This mod used to have a medieval theme to it but now all the buildings seem like crappy square houses with no character and all the NPC skins are flat shaded and dont follow the medieval theme (The guard looks medieval but the builder looks modern? its gross)

**Comment by Nightenom** [comment]
You can't change buildings, you only can add some your own schematics as decorations, making medieval NPCs with minecraft resolution is a bit hard to do (and they don't look modern so much?)

**Comment by Raycoms** [comment]
There are 8 building styles, one of these should please you. Also, if you produce better worker models and textures as well as sounds, feel free to send them, or pay someone to do so.

**Comment by PoroUsedSnax** [comment]
@DarkWhiteParadox You should note that the team working on Minecolonies are all doing it in their free time, voluntarily. It's rather disrespectful for you to come and say that all these things are terrible (Without even having the decency to at least offer some constructive criticism). As Raycoms has said, should you have anything better to contribute then feel free to do so.

**Comment by Asherslab** [comment]
Just to mention, at least 50% of the schematics are built by our Community. I.E. People who play the mod and love it. 
If you'd like to contribute your own Schematics feel free

**Comment by ProsperCraft** [comment]
The problem with one of the voices I know for sure is somehow it got slowed way down, it was recorded by a professional actress, but with it being slowed down it sounds pretty bad.

**Comment by Raycoms** [comment]
@PoroUsedSnax is working on that now =)

**Comment by Starshak3r** [comment]
W
o
W

but, since we're on the subject of the voices.. can you guys remove that creepy laugh that the female builder does.. its super freakin scary :)
