### ISSUE TITLE
[Enhanc] Accept new styles from local repository

### ISSUE THREAD

**Issue by Nightenom** [ldtteam/minecolonies#2531]
Get all new styles (buildings levels included) made by user from a local dir named something like "minecolonies/styles"

**Comment by Raycoms** [comment]
There are 8 building styles, one of these should please you.

Also, if you produce better worker models and textures as well as sounds,
feel free to send them, or pay someone to do so.

**Comment by Raycoms** [comment]
This works if you put it on the server or if you are in single player, doesn't work on multiplayer to avoid abuse, on purpose.
