### ISSUE TITLE
Working on the About page of MineColonies

### ISSUE THREAD

**Issue by frankremmy** [ldtteam/minecolonies#2534]
While I took my time to play and understand the game, this is what I'm able to gather about MineColonies. Please consider this as an overview item, not to be considered for documentation purpose. 
https://www.dropbox.com/s/bsmlf44nnyrc21m/Concept%20of%20MineColonies.docx?dl=0

**Comment by PoroUsedSnax** [comment]
Looks good! Few bits needing cleaning up for a final version, but I think it gives a good overview coverage of the mod.
:shipit:

**Comment by Asherslab** [comment]
Hey, this looks really good, I think the main thing is the Grammar. But otherwise it provides a great Overview of what the mod is, and does.

**Comment by frankremmy** [comment]
For the homepage to be catchy to visitors and for easy conversion, few things I'll be needing :

- Screenshots of some strategic levels of the mod. This serve as a “sneak peek” of how the inside of MineColonies would look like. Be sure to make the shots very clear and worthwhile. 

- An estimate number of current or total players of the mod. This is something called “a social proof”. Visitors like “already made”, they wouldn't want to be one of the first users. It gives them some insight that “Yeah! This is the killer mod!”, also as a proof that for this project to have such amount of sign-ups and players (I don't know how the number would be, maybe over 100,000 users, 20 levels, 2000 commits, or picking any of the 3 or more), then it's worth a trial. 

- Previous versions of the mod, with descriptions of what's new on each release. This also helps for easy conversion too. (if there's a page for this, kindly provide me the link so it can act as a Call-to-action button.

**Comment by Asherslab** [comment]
our versions are released here:
https://minecraft.curseforge.com/projects/minecolonies/files
we have a download counter on https://minecraft.curseforge.com/projects/minecolonies
as well (Not a user count, but download count works)

**Comment by frankremmy** [comment]
Please review. 
https://docs.google.com/document/d/19cnE3RNdBceJeE5J3ob0V9qfI7-PyFWOf-hE2uoL7co/edit?usp=drivesdk
Note: The "Team" lists isn't well arranged. Couldn't figure out on how to best approach that so as to look like the one on the site.

**Comment by frankremmy** [comment]
The update for “Our Team” https://docs.google.com/document/d/1mSk4FBTlAU5uYpEgmrvrP5RC9ZPgw1_psCQdF7uDSUc/edit?usp=drivesdk
