### ISSUE TITLE
"Just a Few Fish" Mod support.

### ISSUE THREAD

**Issue by wyattzastrow** [ldtteam/minecolonies#2537]
### Minecolonies version

version 4.30

### Expected behavior

- Fisher(person) can use a fishing pole delivered by a delivery(person)

### Actual behaviour

- The iron fishing rod from the mod Just a Few Fish doesn't seem to work with the fisher(person), but the delivery(person)s will deliver it to the fisher(person) or I guess they request a rod and that can be delivered.

### Steps to reproduce the problem

1. Give the fisher(person) an iron fishing rod from the mode Just a Few Fish
2. Watch them walk back and forth and not fish.
3. Remove the iron fishing rod, then give them a regular vanilla fishing rod and watch them start fishing almost instantly.
4. Profit

**Comment by Asherslab** [comment]
Correct, we are currently not focusing on integrations with other mods. =D

**Comment by wyattzastrow** [comment]
Is there a way to keep them from being delivered or for the delivery person to keep requesting fishing rods till they get one they can actually use?

**Comment by Wissi** [comment]
Well if you've crafted some, keep them in a separate chest, one not accessed by d-man. Those rods require a special way of using it to "catch" a fish and are mainly intended to catch that mods fish, not vanilla fish. The mechanics of using it might get integrated, but not any time soon.

**Comment by Raycoms** [comment]
Will be added to a new joint mod compat issue.
