### ISSUE TITLE
Guards gain no experience!

### ISSUE THREAD

**Issue by MattBeard** [ldtteam/minecolonies#2538]
### Minecolonies version

version 1.12.2-0.8.8618

### Expected behavior

- Guards fight mobs
- Guards gain experience
- Guards get better at fighting mobs
- When lots of barbarians turn up, guards can cope

### Actual behaviour

- Guards fight mobs
- Guards gain no experience
- Guards keep fighting like noobs
- Guards die!
- Barbarians turn up
- Guards die even more!

### Steps to reproduce the problem

1. Build colony
2. Add guard(s)
3. Watch them fight mobs
4. After a while, check their experience
5. Weep over their graves

**Comment by Asherslab** [comment]
What level is his CitizenHut?

**Comment by MattBeard** [comment]
They are all level 2

**Comment by GanthorPrime** [comment]
i can confirm this. recently upgrade to latest 1.12.2 versions and the problem of guards (i have rangers) diying a lot is very noticeable. Also, new guards (rangers or knighs) are not gaining experience. (stuck at lvl 0, and 0 experience). buildings at max lvl

**Comment by lebanni** [comment]
I'll add that the patrolling system is slightly broken. Some guard move few blocks away, climb on a block where they are stuck and are teleported to their chest.

**Comment by Asherslab** [comment]
Fixed in latest version
