### ISSUE TITLE
Deposit Inventory AI / Button / Command Enhancement

### ISSUE THREAD

**Issue by desagas** [ldtteam/minecolonies#2545]
I would love it if there was a button / command or AI that would force the citizens or workers to deposit their entire inventory into their respective chests. This is especially important for guards.

I was looking at my barracks guards, especially the ones who are around when one dies and drops their inventory on the ground, and realized that they are picking it up. Forcing them to deposit their inventory will cause them to relinquish / give back their extra swords and shields the pickup, allowing new guards to request or gather what they need.

I thought I had lost swords and armour for every death, but, turns out, others had gathered it. It was a relief, but, it was a major pain to sort through 20 guards to gather their inventory.

Thanks for listening. Awesome mod.

**Comment by Raycoms** [comment]
Closed in favor of joint issue.
