### ISSUE TITLE
colonyX.dat files excessively large

### ISSUE THREAD

**Issue by BonaireDreams** [ldtteam/minecolonies#2549]
### Minecolonies version

version X.X.9540 but could be a carry over form previous versions

### Expected behavior

- colonyX.dat file remains a normal size

### Actual behaviour

- colonyX.dat file is HUGE

### Steps to reproduce the problem

1. Not sure how to reproduce but we have 2 very large files.

Colony 2 - My colony: 17 Level 5 buildings. Citzens restricted to 5. (2 builders, 1 dman, 1 cowboy, 1 miner) But I was at 10 without issue. colony2.dat 194kb,  looking at file using NBTEdit: workorder entries 171 entries (which still seems excessive)

Colony 1 - Our problematic colony (10 Level 2 buildngs. 5 Citizens) colony1.dat 3717 kb. Workorder entries: 13833   (This is the colony where our TPS drops to 4 every 20-30 seconds if he has a builder working)

Colony1.dat (renamed 1-1 for editing purposes)
![screenshot 2928](https://user-images.githubusercontent.com/5133282/41671015-c264fb78-746a-11e8-8452-5af059fe8959.jpg)

Colony 5 - Player doesn't seem to have problems or cause server lag, but he really doesn't build his colony much (3 buildings Level 1, 4 citizens) colony5.dat 2135kb. Workorder entries: 8713

Creating this Issue from work, but tonight I'm going to try deleting the 13k entries from colony1.dat and see if server performance is back to normal when that player has a builder working. Will report late tonight with results.

**Comment by BonaireDreams** [comment]
Colony1.dat with 13K work order entries: [https://www.dropbox.com/s/f8z3hnxy1zg0pud/colony1.zip?dl=0](url)

**Comment by BonaireDreams** [comment]
Just a note, these colony.dat files have been with us since May 25th when we launched our server using Minecolonies version .7582.  (Currenly on .9540 as of June 18th) So it's possible the work order entries bug has already been addressed.

**Comment by Raycoms** [comment]
Uhm, all other colonies which have miners are alright?

I will test this a bit later here. But I got an idea what caused this and
its possible I fixed this already, but the fix doesn't clean up the
corrupted old builds.

2018-06-20 14:15 GMT-03:00 Gerald <notifications@github.com>:

**Comment by BonaireDreams** [comment]
Yes, we have fellow who went full bore on Minecolonies and has built every building. His miner seems fine. My Miner seems ok in Colony 2, although I also had 171 entries which I have just deleted. I did notice that when he was requesting planks etc it seemed to cause some lag, but as as severe. Interestingly while colony 1 had a miner, he fired him days ago as we were trying to troubleshoot. and has only kept a builder dman and cook. Even those he was firing/rehiring every few hours trying to clear the lag.

**Comment by Raycoms** [comment]
Yeah because this list constantly tries to assign someone to the workOrder.

**Comment by BonaireDreams** [comment]
Well I think we've successfully found the mystery lag issue. :D I'me just finishing editing all the colony.dat files and deleting all the workorder entries and will push the files back to the server. I also noticed that some of the requestmanager -> DataStores -> Data -> List 46 entries.  Seems high for a colony of 5 Citizens. Would it be safe to delete all those via NBTEdit as well? Or does the rsreset fix that?

**Comment by Raycoms** [comment]
rs reset cleans those as well.

2018-06-20 15:40 GMT-03:00 Gerald <notifications@github.com>:

**Comment by BonaireDreams** [comment]
OK Servers back up with all Work Order entries deleted from all 5 colonyx.dat files. Seems stable. No one on right now to test but we will have the primary culprit (Colony 1) Test tonight.

I did try removing the requestmanager entries as well, but with those removed the server would crash on startup. Is there any way to safely clean these up?

![screenshot 2931](https://user-images.githubusercontent.com/5133282/41679314-aa7cb6be-7482-11e8-9ad5-6cfc0ab36304.jpg)

Thanks

***EDIT** Just saw your comment above. Will try RSreset tonight.

**Comment by Raycoms** [comment]
yeah, there is a command, I think its mc colony rs reset colony: id

2018-06-20 16:09 GMT-03:00 Gerald <notifications@github.com>:

**Comment by BonaireDreams** [comment]
Hmm no luck with either rsreset nor rs reset.
![screenshot 2933](https://user-images.githubusercontent.com/5133282/41680025-ee10d73c-7484-11e8-9720-4df0dd0cab41.jpg)

I also do not see it listed as a command at: [https://wiki.minecolonies.com/index.php?title=Server](url)

**Comment by Raycoms** [comment]
it's /mc rs reset colony: 1

2018-06-20 16:25 GMT-03:00 Gerald <notifications@github.com>:

**Comment by BonaireDreams** [comment]
Hi @Raycoms That did it!!! Thanks so much for all your help on this one. Looking at the server loads in Mineos manager we're sitting below 0.25 with no one currently on. The last few weeks that's been over 1-1.5 with no one on.  This is going to be night and day difference for everyone. Guess I didn;t really need that new Mobo/cpu/ram afterall. But thats all good. Just gives me another older board I can build a little Skyblock server on or something!! 

Thanks again!! Love the mod and looking forward to being able to bring the colonies back up to more citizens.

**Comment by marchermans** [comment]
51 might however be a valid size for 5 people

**Comment by marchermans** [comment]
They are not only used for citizens but for buildings and other things inside the rs

**Comment by BonaireDreams** [comment]
Of those 5 people there was only the Dman and the builder actively working. Player had fired all the other workers trying to find the lag issue. In any case, Things are looking great on the server. I'm happy if you want to close this one. Otherwise I'll close it tonight after actually getting on line and doing some testing. But looking at loads I can already say its an 80-90% reduction in load.

**Comment by marchermans** [comment]
It does not matter, datastores are citizen, job and building independent. They are created  when the RS requires them on the first attempt to access them. The RS itself provides 8 or 9 of them to manage its data and id and such.

**Comment by BonaireDreams** [comment]
So got home at 11pm. Guys said there's been lag all night. Took a look and the first 4 colony files were still fine. Colony 5, even though I had removed all its workorders as well was 6451kb in size. Opening it up in NBTeditor it had 23457 workorders. Not sure why that file went all crazy again, but cleaning it up now and will push it back to the server and test tomorrow.

**Comment by Raycoms** [comment]
I got a fix ready for that. Will merge it today

**Comment by BonaireDreams** [comment]
Oh Perfect. Is that .9602?

I got up this morning and with Player 5 having been offline all night his colony5.dat has 885 work orders. I can upload both my fixed file that I put back on the server at midnight and the one from this morning to dropbox if there is anything of value in them for you.

**Comment by BonaireDreams** [comment]
So servers been on .9602 all day with numerous players on. Colony dat files all look normal and TPS stable at 20!!!

Thanks guys!

**Comment by BonaireDreams** [comment]
@Raycoms Just wanted to add a quick follow up. We are now on .9646 and everythign seems fine except one interesting disocvery. One new player built Builder, Town hall, Miner. She then tried moved the townhall as she wanted it rotated. Not sure if she used the reposition or if she broke and replaced the block. By the end of the day her .dat file was 800k with 3405 miner work orders.  So there could still be something that breaks workorders if you reposition your Town Hall. Fixed her .dat file manually and then also rs reset her colony. She's been fine since.

**Comment by Raycoms** [comment]
Hi, a new build should hit curse soon which will automatically clean up
these miner orders and fix the bug (if you let the miner continue working).
Else you can delete them from the dat via a nbt editor as well.


2018-06-26 14:18 GMT-03:00 Gerald <notifications@github.com>:
