### ISSUE TITLE
Tier 5 Stone Restaurant record request loop

### ISSUE THREAD

**Issue by BonaireDreams** [ldtteam/minecolonies#2553]
### Minecolonies version

version X.X.9602

### Expected behavior

Builder requests record and places it

### Actual behaviour

Builder requests record.
Builder goes to Restaurant.
Record stays in Inventory.
Builder requests another record.
Rinse and repeat.

### Steps to reproduce the problem

1. Build stone Restaurant
2. Level tier to Tier 5
3. Watch builder build his record collection at your expense.
4.  No Profit

**Comment by BonaireDreams** [comment]
Just checking in, this is still happening in 1.12.2-0.9.4-BETA. Asked Builder to upgrade Tier 4.5 (Its half way done) Stone Restaurant to Tier 5 again. He goes to the build corner and scans the blocks until he gets to the records. The he continuously runs in a circle from the Restaurant to his hut even though he has 3 records on him. He never places them and never finishes the building.

**Comment by marchermans** [comment]
It is being fixed.

**Comment by lunadragnstar** [comment]
I am removing the records from the build.

**Comment by lunadragnstar** [comment]
old issue, closing
