### ISSUE TITLE
RFTools elevator and minecolonies

### ISSUE THREAD

**Issue by Daniele05062006** [ldtteam/minecolonies#2561]
### Minecolonies version

1.10.2-0.9.7587

### Expected behavior

- The RFTools elevator should work everywhere.

### Actual behaviour

- The RFTools elevator doesn't work in the colony

### Steps to reproduce the problem

1. build a town hall
2. build a RFTools elevator in the colony

**Comment by Wissi** [comment]
Do you mean player can't use the elevator placed inside his own Town? or other players not listed in TownHall or Citizens?

**Comment by Raycoms** [comment]
Waiting still for comments

**Comment by tie** [comment]
@Raycoms, happens when the *owner* uses the RFTools elevator with colony protection *enabled*. The bug still exists with the latest releases of Minecolonies and RFTools. Perhaps some workaround or explicit incompatibility statement could be added.
