### ISSUE TITLE
General question on colony size?

### ISSUE THREAD

**Issue by CharCharthemonkey** [ldtteam/minecolonies#2566]
### Minecolonies version

version X.X.XXXX or curse X.X.XX
1.12.2-9630
### Expected behavior
clear size of colony
- XXX

### Actual behaviour
unknown colony size
- YYY

### Steps to reproduce the problem
please define wat the colony size is? cause 16x16 256x256 or 8 chunks by 8 chunks is wrong or something cause i made a colony didnt change the size and barbarians are spawning inside the walls and i was told they only spawn outside the walls
![2018-06-24_17 53 47](https://user-images.githubusercontent.com/30783285/41888040-1286a5c2-78c9-11e8-8cde-179c482ade58.png)
![2018-06-25_12 32 55](https://user-images.githubusercontent.com/30783285/41888042-13eb139e-78c9-11e8-92e7-09107cab1305.png)
![2018-06-25_13 14 53](https://user-images.githubusercontent.com/30783285/41888046-182ca47c-78c9-11e8-8628-8f1c907dfcd4.png)
![2018-06-25_13 15 18](https://user-images.githubusercontent.com/30783285/41888047-18d7edb4-78c9-11e8-846b-8354fb1c1811.png)

thank you

1. XYZ
2. ZYX
3. ...
4. Profit

**Comment by Raycoms** [comment]
No they don't only spawn outside the walls, they spawn in the farthest
loaded chunk.

2018-06-26 0:43 GMT-03:00 CharCharthemonkey <notifications@github.com>:

**Comment by CharCharthemonkey** [comment]
well from wat i was told they are supposed to spawn outside the walls and weirdly on 2 sides of my colony they do but the other 2 sides they dont

**Comment by marchermans** [comment]
@Raycoms I figured something out lately about the spawning. Their was an issue with how we detect the loaded area. However I am. Not sure anymore what it was xd

**Comment by CharCharthemonkey** [comment]
well something either i did or a config derp or coding derp caused the above pictures to happen and from wat i was told the barbs are supposed to spawn outside ure colony not inside it unless the colony size broke

**Comment by Raycoms** [comment]
Then you have been told wrong, the barbs spawn in the farthest longest
chunk, its not guaranteed to be outside of the wall.

2018-06-26 16:08 GMT-03:00 CharCharthemonkey <notifications@github.com>:

**Comment by CharCharthemonkey** [comment]
ok so pretty much a wall is useless then which i was told was 100% sure to work thank you
