### ISSUE TITLE
suggestion for baker, smelter, and similar "crafters"

### ISSUE THREAD

**Issue by yggdrasil75** [ldtteam/minecolonies#2567]
### Minecolonies version

version 1.12.2-0.8.9630 or curse X.X.XX

### Expected behavior

- So, the smeltery and baker have preset furnace recipes, the smeltery does oreX (smeltable ores) and the baker does "bread" but there are times when you have need of a furnace and it is neither for smeltable ores or bread. An example of this is the ore drops that come from certain mods to replace the ore block dropping for various reasons (ie: iron cluster from dungeon tactics) or because of dusts that are for "ore duplication" from various mods such as ae2, every tech mod, and a few magic mods. for a vanilla example, clay into bricks, concrete powder into concrete, and clay into hardened clay. (though with these it ought to be possible to have the smeltery count the amount of the smelted and set itself a limit to prevent running out of the unsmelted due to their useful qualities)

with the baker, it currently makes just bread (reasonable for a baker) but what about potatoes? as for actual baker stuff, what of pam's harvestcraft where there are sandwiches, burgers, pizzas, and more that need bread. there aught to be a chef and a baker, with the baker able to make anything in a furnace that has a food value and the baker able to make anything in a crafting table with a food value. (also a mill might be nice with pams to get seeds from the crops and as a way to get the dusts of other mods while staying with minecolonies instead of building everything in the town square.)

**Comment by bob0bob** [comment]
This is just an FYI,  baker can make cookies, cakes and bread.  The baker makes them in that order,  just depends on what raw ingredients they have.

**Comment by winex** [comment]
@bob0bob are baked potatoes vanilla? i'm using havestcraft, so idk.
@yggdrasil75 potatoes are Cook's deal and definitely not the Baker's. though, i couldn't get Cook to bake it (need to try in latest alpha)
