### ISSUE TITLE
broken chicken herder

### ISSUE THREAD

**Issue by CharCharthemonkey** [ldtteam/minecolonies#2569]
### Minecolonies version
1.12.2-0.8.9630
version X.X.XXXX or curse X.X.XX

### Expected behavior
to make baby chickens
- XXX

### Actual behaviour
feeds the chickens tries to breed them but nothing happens
- YYY

### Steps to reproduce the problem
install both minecolonies and hacthery/chickens/moarchickens build the chicken herder and it breaks
1. XYZ
2. ZYX
3. ...
4. Profit

**Comment by Raycoms** [comment]
That means it's actually not broken, it just means that moarchickens changes the chickens in a way which the herder can't cope with. So it would be a required modcompatability. We got that issues with all herders, but we have unfortunately not enough time to consider all entity changing mods.
