### ISSUE TITLE
mod compat pretty please?

### ISSUE THREAD

**Issue by CharCharthemonkey** [ldtteam/minecolonies#2571]
### Minecolonies version
version 1.12.2-0.8.9360

### Expected behavior

- work like normal

### Actual behaviour

- only the axe works from the mod the other tools and weapons do not

### Steps to reproduce the problem

1. Craft any tool or weapon from mystical agriculture
2. try to give it to the colonist
3. They say "no"

please and thank you

**Comment by CharCharthemonkey** [comment]
btw forgot to mention 1 colonist already uses the Mystical Agriculture tools but none of the others do which is odd (lumberjack is the one that does)

**Comment by Raycoms** [comment]
It's because these mods do not tell minecraft that their tools are:
- Weapons
- Axes
- Pickaxes
etc

**Comment by CharCharthemonkey** [comment]
weird cause the axe works just the rest do not lol hmm

**Comment by Raycoms** [comment]
Yeah that means they didn't add it right for the rest of the tools, they should add the tool classes to them.

**Comment by Wissi** [comment]
@CharCharthemonkey you might want to contact the Mystical Agriculture Mod devs about this? Create an issue w/them?
If they have a fix for it, we'll add to server/clients so there is compatibility.
