### ISSUE TITLE
Cannot delete colonies

### ISSUE THREAD

**Issue by ShaneCourtrille** [ldtteam/minecolonies#2572]
### Minecolonies version
minecolonies-universal-1.12.2-0.8.8618

### Expected behavior

Typing "/mc colony delete 1" should delete the colony

### Actual behaviour

Receive the error "missing required parameter colony"

**Comment by Raycoms** [comment]
Need to be : mc colony delete colony: 1

**Comment by Nightenom** [comment]
That's what I was talking about, only our mod uses this command system

**Comment by Asherslab** [comment]
@Nightenom that’s correct, that’s because our command system is MUCH more advanced than most other systems

**Comment by ShaneCourtrille** [comment]
That's a silly argument to make as the goal of the system should be to
allow users to manage their colonies.  Not to be 'advanced'.

Look at managing Azure via PowerShell or bringing in packages via npm or
any of the other of thousands of command line based management that exist.
They all work fine without having such an obvious point of confusion.

A few alternatives..

/mc colonies [action] [colonyId] so. /mc colonies delete 1 would make the
most sense since now I'm obviously acting on the list of colonies I have
access to.  This is also nice as it separates out the actions on a colony
vs the resources within a colony.

Without adding a new keyword you could go /mc colony [colonyId] delete
would also make sense as now I'm identifying the colony I want to act
upon.  This lets me do more complex scnarios like /mc colony 1 delete
[resource] or /mc colony 1 workers add or whatever you desire.

Just a thought *shrug* for now I'll try to remember to add an example to
the wiki for the next confused schmo :)

**Comment by Raycoms** [comment]
The problem we have is this:

We had two choices: 
=Either we limit the commands strongly:
- Meaning each command only works with 1 parameter.
(Example, get colonist by id and not by name or id, and get colony by id and not by ownername or id)
=Or we implement a system which works with auto complete and allows us to use any parameters in any order. Since minecrafts auto complete didn't work really well we decided for the latter.

Now with the 1.13 command rewrite coming close we will probably have to rewrite all of this anyway. Let's hope their support is better.

**Comment by mkienenb** [comment]
Note also that you're using the old mc command system.

The new system is much more user friendly once you realize that tab can be used to complete the command.    

/mc <tab>

_commands list_

/mc colony <tab>

_sub commands list_

/mc colony delete <tab>

_list of parameters required and optional for the delete command_

/mc colony delete colony: <tab>

list of colonies you can delete

/mc colony delete colony: 1 <tab>

_remaining list of parameters required and optional for the delete command_

Once you realize that tab is your friend, you should find the new system much easier.

**Comment by ProsperCraft** [comment]
I have to agree with Shane here, all we want as users is /mc colony 1 delete, or even better... /mc colony playername delete then we let the computer do its job in finding who owns the colony and save the admin from having to do mundane work.. The current syntax is very unfriendly to users.  Colony Colony: is redundant.

When you re-write the command syntax please take this into consideration.

Would be nice if players could dissolve their own colony as well, and not require admin intervention.

**Comment by mkienenb** [comment]
Have you tried /mc colony delete confirmDelete: true?   You might also need canDestroy: true.    I can't remember the exact syntax and I'm not near the source code or game.

I suspect that colony: is optional and will default your current colony.
