### ISSUE TITLE
Guards teleport themselves to roofs

### ISSUE THREAD

**Issue by lebanni** [ldtteam/minecolonies#2576]
forge-1.12.2-14.23.4.2708-universal.jar
minecolonies-1.12.2-0.8.9646.jar

They even teleport inside rooms with no acces (for example level three guard tower first stage, see picture).

https://imgur.com/a/C29fpQa

It happened a few release back aswell.

**Comment by MineShadow7** [comment]
They should teleport themselves out of there after some time. That happens if mob spawned on the roof and guards had no easy access to it.

**Comment by lebanni** [comment]
They juste teleport randomly. Even when I recall them to their chest, they teleport back where they were.

**Comment by bob0bob** [comment]
I'm seeing it even with citizens.  I find someone the roof all the time.

**Comment by lebanni** [comment]
Seems to work as intended now (0.9.12). Closing.
