### ISSUE TITLE
[Enhancement] Guards Request Armor

### ISSUE THREAD

**Issue by SomewhatDamaged** [ldtteam/minecolonies#2577]
### Minecolonies version

version 0.8.9630

### Expected behavior

Guards request weapon, shield, then armor.

### Actual behaviour

Guards don't request armor.

### Suggestion

Have a toggle option in the Tower settings menu to have guards request armor.

**Comment by bob0bob** [comment]
This change will allow the guard to start requesting armor.  The type of armor will change based on the guards level.  From Leather - Diamond.  level 1 - 8.  At level 8, they stick with Diamond  armor.

Both the Ranger and Knight request the same armor type based on their level.

If you put Diamond armor in the inventory but they are requesting leather, they will only put on leather armor.

**Comment by bob0bob** [comment]
Tweaked the armor request to reflect a combination of building level/guard level on what armor is requested.
