### ISSUE TITLE
Vanilla villagers not repoducing

### ISSUE THREAD

**Issue by wyattzastrow** [ldtteam/minecolonies#2579]
### Minecolonies version

version 0.8.9630 or twitch v4.31

### Expected behavior

- If you throw food at Minecraft vanilla villagers they will pick it up and eat it, then if conditions are right eventually getting frisky and produce little villagers

### Actual behaviour

- They don't pick up the food and look at you like the rat bastards they are.

### Steps to reproduce the problem

1. Throw carrots at villagers
2. Watch them stare at you and not get freaky with their friends
3. ...
4. Profit

**Comment by wyattzastrow** [comment]
I tried this inside my colonies border.  Hero tried it both inside and outside his borders.

**Comment by Nightenom** [comment]
I don't see why is this related to minecolonies, but I think that you can't make a colony near to any village but vice versa you can make a village but mechanism might be suppressed.
Try making or use a village at least 500 blocks away of colony (use F3 to see how far are you from any colony)

**Comment by marchermans** [comment]
Yes all pick ups (including those by villagers) are blocked unless specifically allowed by the player if a Colony is in range. This is intended behavior.
