### ISSUE TITLE
[Proposal] Building level restoration

### ISSUE THREAD

**Issue by Asherslab** [ldtteam/minecolonies#2584]
Currently when your building or colony becomes invalid (for whatever reason), you lose all your progress, including Buildings. To combat this, we could allow for building level restoration using the build tool. 

So the process would be slightly easier than you'd think (hopefully).
You act as if you're placing the building normally with the build tool (select the stylepack and level), the level should match the level of the building was previously. after that you line up the GUI structure with the real structure. When the building is then placed (normally, with the "tick"), if all the blocks are in the correct place, then the building is placed with the same level of the structure.

Multiple benefits of doing it this way:
1. Should be relatively simple code (over that of creating a gui button or etc)
2. The player selects the style and level, as such we only have to check the schematic Once (Not check every possible schematic or level)
3. Allows for at least a little less frustration from players losing their colonies 
4. If a player happens upon an old "dead" colony, if it's structures are still intact, the player could move in with that instead.
5. It's relatively simplistic for player usage (they might not even realize they did it).
6. Helpful for when we introduce slightly breaking changes that require you to replace your hut (E.G. when we introduced the LumberJack changes)

@Raycoms 
@OrionDevelopment 
@pmardle 
@Wissi 

Would love your inputs on this thanks

**Comment by Starshak3r** [comment]
yee.
that could work, what's to stop people from going direct to L5 using this method though?

**Comment by Asherslab** [comment]
Nothing, But they'd have to build the structure first

**Comment by Starshak3r** [comment]
any structure, or the exact same as in a stylepack?

**Comment by Asherslab** [comment]
Well any structure from any Stylepack. As long as they build it correctly (which would not be the focus of this, but is completely possible) they could "restore" it to the level and style they build

**Comment by Nightenom** [comment]
Sounds pretty good and even looks not hard to write

**Comment by marchermans** [comment]
As discussed internally. Their will be performance problems if this is done this way.
We will try to improve this mechanic over time. But for now it stays this way the builder will be relatively quick if said building is put back inplace so the user does not lose to much time when he wants to place it anyway.
