### ISSUE TITLE
Suggestion: Limit Cooks fuel requests to coal, charcoal, wood

### ISSUE THREAD

**Issue by BonaireDreams** [ldtteam/minecolonies#2589]
### Minecolonies version

version X.X.9646

### Expected behavior

- Dman to deliver correct materials to restaurant

### Actual behaviour

- Dman likes to bring whatever he feels like bringing (IE Stacks of wool)

### Steps to reproduce the problem

1. Have restaurant
2. Hire Cook
3. Wait for Dman to bring him stairs, wool, planks etc
4. Profit

Suggestions:

1) Change the cooks requests to specify only Coal, Charcoal and wood. Maybe not even wood as most of that is in the Warehouse as building materials. Specifying only charcoal or coal would ensure the Dman does not deliver things like stairs or wool.

2) Add an option in the restaurant to specify fuel types to request. A check box for Coal, Charcoal, and Wood. Although not sure if its possible to specify only wood and not receive planks or stairs etc.

3) Add a building to create Charcoal. A small building with 1-3 kilns outside depending on the Tier. Inside each Kiln is a furnace. Dman delivers Coal or charcoal as fuel, and wood to turn into charcoal.

**Comment by SomewhatDamaged** [comment]
Maybe a spot in the his building's settings where you can drop a piece of what you want him using as fuel? (Even if it's a ghost of the item.)

**Comment by Raycoms** [comment]
This is planned

**Comment by Enverex** [comment]
Did you guys have a rough idea of when you're implementing this? I noticed my cook seems adept at picking the things I'd least like them to burn as their fuel of choice.

**Comment by Nightenom** [comment]
Actually should be easy to do, but the manpower that has any time to do it is not

**Comment by wetbrownsauce** [comment]
An option to choose what to burn would be nice. Kind of annoying when I build a smeltery and when I come back he hasn't touched a single coal yet he's burned all my acacia doors, torches, and wool
