### ISSUE TITLE
Baker - Enhancements -  User controll over Baker

### ISSUE THREAD

**Issue by bob0bob** [ldtteam/minecolonies#2592]
I did some searches to see if active work is being done on the Baker and I've suggest these features about 9 months ago as what I thought was a good enhancement.   

If there is a procedure on new things and how to go about it.  Please let me know.  I didn't notice one but I manage there is one and hope this doesn't make people mad.  Just trying to make the baker a nicer part of the colony.

This is an enhancement for the Baker.    I've added a second gui that the user can select which recipes the baker will make.  As you can see from the screen shots it shows everything recipe the baker can make.  Click on the items you wish them to make.  So you can control what they produce.  If you only want cookies,  just have the cookies the only item clicked.  The baker will only make cookies.  I've added Pumpkin Pie since it is a vanilla minecraft item.  

So there are 4 recipes for the baker now.

If your town gets over loaded with food, you can also uncheck everything and the baker goes IDLE until there is an item that the baker is allowed to bake.  You don't have to reassign them to another job anymore if you don't wish too.

Also, in this version, you have the ability to have one baker make cakes, and another make bread.  Each building saves what is made in that building so you can have different buildings making different things.

There is no default recipe the baker will request if items are missing like before.  They will find the first recipe that is allowed and request those items and until they receive those items, they will wait for the request to be fulfilled.

If you have more than one item checked for allowed recipes, the baker will just go down the list.  The baker doesn't care if recipe 1 is fulfill-able and recipe 2 is not.  If recipe 2 is the next item to be produce it will request those items and wait for it.

Unless, your building is higher than level 1.  So the baker can make more than one item at a time.  Say it was level 3.  Which means they can be making 3 things at a time.  

I've submitted all the code changes.  I hope that you guys will accept the new changes to the baker.  I think it still follows the scheme of MineColonies.

![untitled-2](https://user-images.githubusercontent.com/30982580/42337528-b42bfd2a-804c-11e8-9417-25b392a297ce.png)
![untitled-1](https://user-images.githubusercontent.com/30982580/42337529-b44031be-804c-11e8-9e03-34f1b74d55f4.png)

**Comment by Raycoms** [comment]
How does he request things? Does he request everything asynch which is ticked in the list?

**Comment by bob0bob** [comment]
Yes.   He makes a call to 	        checkIfRequestForItemExistOrCreateAsynch(...)  and then waits until he is able to fulfill the recipe before moving to Kneading on the next step.   Is that what you meant.

So, if the baker has something in the oven and it finishes while he is waiting, he will finish that product.

**Comment by winex** [comment]
how this will be on par with teachable recipes (2 buttons at bottom)? will they appear on second page?
btw, will it also work with food mods (harvestcraft for ex.)?
p.s. nice addition :)

**Comment by Raycoms** [comment]
That's planned in the future (next PR)
