### ISSUE TITLE
Feature Request- Players ability to delete their own colony.

### ISSUE THREAD

**Issue by ProsperCraft** [ldtteam/minecolonies#2594]
### Expected behavior

- The player who created the colony should be able to destroy it, I don't understand why they can't now and it requires staff intervention.

### Actual behaviour

- Player places a colony, realizes it is in a bad location and is unable to move it and has to find staff to move it inconveniencing the staff member and the player.

**Comment by Nightenom** [comment]
You can delete it with command, something like `/mc colony delete {some arguments}`

**Comment by marchermans** [comment]
It is actually possible for any player to abandon the colony. He can not pick it up how ever to move it.
We discussed this internally and this will stay this way untill we can implement a moving mechanism that we deem demanding and fair.
