### ISSUE TITLE
Town Hall - Should Save build order.

### ISSUE THREAD

**Issue by bob0bob** [ldtteam/minecolonies#2595]
When you take the time to reorder the build order from the town hall gui.  This should be saved.   On reopening the world again.  The order is lost and I have to reorder the building process again.

**Comment by Raycoms** [comment]
It should actually save it, but it might need a few minutes to save this (I
will rework this soon, but for now we need it for performance reasons)

2018-07-06 13:54 GMT-03:00 bob0bob <notifications@github.com>:

**Comment by bob0bob** [comment]
Based on the code.  when writing to the NBT file.  the priority is not saved.  So on load everything is set to 0 again.   Class AbstractWorkOrder   looks like it holds the priority but the writeNBT and createFromNBT is not using that variable.  I've have code changes to fix this.  if you want me to submit them for review.

**Comment by Raycoms** [comment]
Ahh, didn't know that I had forgot that, then we have to add that there.

2018-07-06 15:22 GMT-03:00 bob0bob <notifications@github.com>:

**Comment by bob0bob** [comment]
I tried to submit changes but I guess you can only have one pull request from one branch to another.  It combined the changes into the PR for the enhancement to the baker.

Can you have more than one.  When I click on new pull request and then select across forks.  it pulls up the one pending.  I guess you can't have more than one.

**Comment by Raycoms** [comment]
Weird, it should work with multiple PRs, but combining it works as well

2018-07-06 15:54 GMT-03:00 bob0bob <notifications@github.com>:

**Comment by bob0bob** [comment]
Fixed in PR #2593
