### ISSUE TITLE
[Enhancement] Ghost-Outline Glasses

### ISSUE THREAD

**Issue by SomewhatDamaged** [ldtteam/minecolonies#2599]
### Suggestion

Head-slot glasses to see ghosted images of buildings/changes yet to be made by builder.

### Explanation

Simple glasses item craftable. When worn, buildings scheduled to be constructed/upgraded show ghostly outlines of parts yet to be added, and red highlights on bits that need to be removed. Being head slot means tools and blocks can be held without impeding your vision of your "Grand Design"©™.

### But Why?

So players can assist their builders. Digging out unneeded dirt/rock and adding stuff while the builder runs to the other side of town to get the latest lot... again.

Would also be a great help when aligning and laying out a town, as well as placing build orders for walls.

**Comment by marchermans** [comment]
Good idea.

**Comment by Raycoms** [comment]
Closed in favor of joint issue.
