### ISSUE TITLE
Happinesss - possible changes.

### ISSUE THREAD

**Issue by bob0bob** [ldtteam/minecolonies#2600]
I have a suggestion for an enhancement to the happiness system.  I think it was be easy to implement and can be something that is added to as MC goes on.   

First I suggest moving happiness to each citizen,  then you take an average to find the town happiness.  Then adjust it with the global happiness ei: death of citizens, guards to citizens and etc....

Each citizen happiness changes based on number of factors.   
Like you get a hit on a citizen happiness for not being assigned a house.  
You get a hit if their job is considered far from their house.  Long walks to work.  You have to manage houses better.
Each citizen has a list of things that take a hit on happiness, neutral, or a positive on their happiness.
Examples:
Guard requesting armor and not getting will take a hit.
Food saturation levels have different hits for the type of jobs.
Citizen standing around say half a day waiting for requested items.  (different citizens hit on not getting what they need will be different,  probably more on a guard not getting their weapon vs. a herder not getting their bucket for milk).
Of course you have the normal global happiness that reduce the average citizen happiness.  like citizens dying.

**Comment by bob0bob** [comment]
Each citizen will show their happiness bar on the gui under the food bar.  So a player can see which citizens are unhappy and try and correct it.

**Comment by bob0bob** [comment]
If you like the idea, please suggest other things to add to happiness.  Trying to make it a bit more complex on the happiness and make it more than just thrown a town down and be done.   Happiness is something right now you never have to worry about,  its always a 9.

**Comment by bob0bob** [comment]
Maybe,  the farmer gets a hit growing the same field over and over and not changing it.  Maybe after so many harvest of the same crop they take a hit and wants something else to grow.  Forcing players to switch around.  

This type of method is required in REAL life, you can't grow the same harvest in the same field year after year.  You will start killing the soil.  There is a process to switch it up so the nutrients gets back into the soil instead of just corn.  Sometimes they do not plant the field for a cycle or two.

This data could be saved in the fields data and the farmer assigned to the field takes the hit if the player just keeps growing the same crop over and over.   More management.

**Comment by Raycoms** [comment]
I think this is a nice idea and definitely worth implementing, we could
have a general calculation in each citizen for this and then we can add a
method to the general worker code to decrease it.
For example if a worker waits too long for a blocking request (asynch
requests don't matter).

Then we could also take the quality of food into account (Food that gives
more hunger back gives a happiness boost).



2018-07-07 12:54 GMT-03:00 bob0bob <notifications@github.com>:

**Comment by bob0bob** [comment]
That sounds good also.  It sounds simple and very easy to implement.     Just trying to think of ways to enhance game play and require players to pay more attention to citizens.

**Comment by Raycoms** [comment]
Yeah, definitely, sounds like a good idea. We should also enhance the way
we assign citizens to buildings, at the moment this is too difficult still.

2018-07-07 13:44 GMT-03:00 bob0bob <notifications@github.com>:

**Comment by bob0bob** [comment]
This is an update on some of the new features of the new happiness system.
Features of the new happiness system:

Each citizen has their own happiness indicator.
You can view the citizen happiness indicator by right clicking on citizen.
Also, can view citizen happiness through Town Hall
Colony has its own happiness indicator.

Total happiness on the Town Gui is a combination of the two items from above.

Colony Happiness:
Citizen to Guard Ratio will modify the happiness
Average food Saturation for all citizens will modify the happiness
Citizen to Housing ration will modify the happiness
When a citizen dies it will modify the happiness
   Death modifier will stay around for a period of days before it drops off.
   It keeps a list of all death in a certain period of time and each death modifies happiness

Citizen Happiness:
base happiness
Food saturation will modify the happiness
If player is unable to eat when they go to eat will affect happiness
Citizen getting hit will modify happiness
Citizen not having a house will modify happiness
   Citizen will start demanding a house to live in after a period of time without a house.
Citizen not have a job will modify happiness
   will start demanding a job to work at after a period of time without a job.
A farmer having fields they are not able to farm will modify happiness
A farmer having no fields will modify happiness
Citizen not having a required tool to do their job will modify happiness
    will start demanding the tool after a period of day without requesting being fulfilled.
