### ISSUE TITLE
Happiness reset to 1 and colonists gone upon relog in single player

### ISSUE THREAD

**Issue by Sararainmaker** [ldtteam/minecolonies#2602]
1.12.2 Minecolonies version
(first time posting, not sure if I got this right. I got it from the mod list in-game)

Expected behavior
Happiness and colonists are the same upon login as it is on logout

Actual behaviour
Happiness upon logout was 10 and when logged in is 1 and a few colonists are gone/dead.

Steps to reproduce the problem

1. exit world on single player
2. exiting game isn't required, but same result.
3. enter world on single player

**Comment by bob0bob** [comment]
I'm working on complete rework of happiness.  Yes, many areas were not saving the happiness and would start recalculating it as it started.

The happiness system will be really expanded and more complex in the future and it will save the data.  You will have colony happiness modifiers and individual citizen modifiers.   Both have many area that can modify the happiness level of the colony or citizen.

**Comment by Sararainmaker** [comment]
Thank you for the info and response! 
Nothing i can do in the meantime to stop it from happening?

**Comment by bob0bob** [comment]
Happiness will be added in the following days and then it will be expanded on as we add more happiness modifiers for the colony and citizens.
