### ISSUE TITLE
Guard Option - From Town Hall GUI

### ISSUE THREAD

**Issue by bob0bob** [ldtteam/minecolonies#2603]
Have the ability from the town hall gui to be able to click one button to make all the guard to follow the player.   During a Horde raid on a large town, you don't have the time to run all over the town turning them into "Follow" mode.    You should in a since have the ability to sound a horn and let the guard know we have a raid.   What should change is turn on the guard buildings into follow.  This way they all attack.

If some guards from parts of town is not close enough to the horde, they will not attack and just keep patrolling.

Then have another option to turn them all back to assigned guard job type.

**Comment by Raycoms** [comment]
We got another issue for this "rally guards"
