### ISSUE TITLE
endermen disable barracks tower crash

### ISSUE THREAD

**Issue by yggdrasil75** [ldtteam/minecolonies#2607]
### Minecolonies version

version 0.9.6-ALPHA-universal

### Expected behavior

- disable attacks against endermen

### Actual behaviour

- game crash

### Steps to reproduce the problem

1. barracks tower guard block when on the disable mobs screen disable endermen
2. crash
3. upload https://pastebin.com/ce3qj3xM
4. ask on discord
5. post issue here

**Comment by Asherslab** [comment]
will take a look, thanks

**Comment by bob0bob** [comment]
Can you upload a screen shot of your mob attack gui window.
