### ISSUE TITLE
Guards - standing around like crash dummies.

### ISSUE THREAD

**Issue by bob0bob** [ldtteam/minecolonies#2610]
### Minecolonies version

current MC

### Expected behavior

- Guard should patrol and attack mobs.

### Actual behaviour

- Guards basically stand around and do nothing.

Real problem is the NBT load routine does check to make sure the mob located in the save data still exists.  If the mod has been removed since last save.  The mob is deleted MC will crash (exception caught) and many things about MC doesn't work.  patrolling, some of the guis.

1. XYZ
2. ZYX
3. ...
4. Profit

**Comment by bob0bob** [comment]
Fixed in pr 2609.  Wish you could have more than one pr ticket to merge back into the main branch.  Only one ticket so everything gets merge.  Wish you could select which files.

**Comment by Raycoms** [comment]
What do you mean with this?

2018-07-11 1:42 GMT-03:00 bob0bob <notifications@github.com>:

**Comment by PoroUsedSnax** [comment]
@bob0bob You can make separate branches to merge into version/1.12, that way you can choose which of those get merged as well as creating separate PRs for each branch

**Comment by Raycoms** [comment]
You should also be able to cherrypick certain commits into these branches
to separate your existing PR into a few small ones.

2018-07-11 10:02 GMT-03:00 Mark Fisher <notifications@github.com>:

**Comment by bob0bob** [comment]
Are you saying each bug fix, I have to have a new branch???   As you can see from my test branch I do not have "Create new pr".   Only option is "view" and it automatically pulls everything I check in, into that PR.   I do not see a setting that can turn that off?   I've not been able to locate anything in help on github, at least the way I'm searching for it.


![image](https://user-images.githubusercontent.com/30982580/42575999-2443126c-84e7-11e8-8333-11b908bded93.png)

**Comment by Raycoms** [comment]
Yes, you have to create 1 branch per pr.

2018-07-11 10:49 GMT-03:00 bob0bob <notifications@github.com>:
