### ISSUE TITLE
Doors and their placement

### ISSUE THREAD

**Issue by MokahTGS** [ldtteam/minecolonies#2611]
Can something be done to put doors on the outside of the door blocks so that zombies and mobs can't get away with standing in the overhang?  It drives me nuts.

**Comment by PoroUsedSnax** [comment]
This is all dependant on how stylepack creators want to build their buildings, most are created by the community.

**Comment by MokahTGS** [comment]
Alright, noted.  I'll just have to start an awareness campaign to fight poor door placement.  Maybe I can get Angelina Jolie to do a commercial for me on the horrors of careless door placement.
