### ISSUE TITLE
Client crash when clicking on builder chest

### ISSUE THREAD

**Issue by lebanni** [ldtteam/minecolonies#2618]
minecolonies-1.12.2-0.9.10-ALPHA-universal.jar

[crash-2018-07-13_16.07.14-client.txt](https://github.com/ldtteam/minecolonies/files/2193023/crash-2018-07-13_16.07.14-client.txt)

**Comment by winex** [comment]
it crashes because windowhutbuilder.xml doesn't contain list, commit 01c15bc3abb6cd96fb3d491504ec5476dca2988d doesn't check for null probably at src/main/java/com/minecolonies/coremod/client/gui/AbstractWindowWorkerBuilding.java:139
i've tried to simply edit this file (.xml) and it works now...

**Comment by Raycoms** [comment]
Why don't you make a pull request for the fix you made?

**Comment by winex** [comment]
um, i think that there should be null pointer check in that commit, but i don't know how to properly do it...
xml fix is the same, but crashes will happen again w/o proper checks :(

**Comment by Raycoms** [comment]
Just pushed the hotfix, thanks
