### ISSUE TITLE
mirror structures using build tool, place them in offset coordinates

### ISSUE THREAD

**Issue by GanthorPrime** [ldtteam/minecolonies#2619]
### Minecolonies version

minecolonies-1.12.2-0.9.10-ALPHA-universal
also found in minecolonies-1.12.2-0.9.6-ALPHA-universal

### Expected behavior

When you position some structure using the build tool, the structure is placed in the same position that the preview shows

### Actual behaviour

if you position a structure in the 'mirror' state using the mirror control on the build tool, the build is place in an incorrect postion respect to te preview.

### Steps to reproduce the problem

1. In creative mode (for convenience), select any build from the mod or from your scans using the build tool, make sure is not all simetric so you can see the problem.
2. use the mirror control to set the mirrored state of the preview, keep an eye in the position, and build it
3. structure is displaced some amount of blocks in one of the coordinates respecto to the preview. It seems thats the bigger the structure is, the bigger is the offset.

this happens in creative and survival (in an actual colony) and the builders builds.

I chequed this using only forge and minecolonies, and creating a new world just to be sure other mods interfered. I remeber this works ok in versions for mc 1.11.2 (recently upgraded to 1.12.2)

sorry for my bad english

**Comment by marchermans** [comment]
Will debug this.

**Comment by marchermans** [comment]
@Raycoms do we mirror around the primary block? Or around the center?

**Comment by Nightenom** [comment]
For me it seems that around the primary block (hut block), but it would be better around the center tbh.

**Comment by marchermans** [comment]
Yeah since Center block Is what is rendered

**Comment by marchermans** [comment]
But I have no idea how the builder mirrors when he places

**Comment by winex** [comment]
but what if there is no integer center? i mean the even numbers, size like 12x14.
code should mirror properly around 0.5's half-cubes

**Comment by Raycoms** [comment]
no, actually 0,5 cubes don't work in minecraft, nonetheless, it should
place the building exactly where the buildtool says it is.

2018-07-17 23:02 GMT-03:00 Roman Vasiyarov <notifications@github.com>:

**Comment by winex** [comment]
maybe something can be done on client side? i.e. change position a bit to correct for mirroring?

**Comment by marchermans** [comment]
@winex yeah but then i Need to know what is actually wrong. I tried this and it works for me. So @GanthorPrime Pictures please 🖼

**Comment by winex** [comment]
@OrionDevelopment no pics yet, but basically:
- use build tool
- move to some position, some (10+) farther, some to the side (10+)
- maybe even rotate at the start or after the movement
- try to mirror -- it sometimes teleports to the other side around
maybe it's just using wrong origin (the build tool's initial pos instead of new one) for rotating/mirroring

**Comment by GanthorPrime** [comment]
sorry for not checking this before. i will be posting images as soon is i reach home.

to clarify: the problem becomes aparent not in the preview stage, but after the structures are placed on the map: in creative you can see right afert you 'paste', in survival you can see the tapes appear in another position, displaced from the preview's position.

the only requisite for me, is to 'mirror' the structure in the preview (use the triangles in the centher of the build tool gui) and keep the mirrored position (nothing to do whith the actual 'usage' of the build tool but the mirrored position. 

Dont know if moving the preview have something to do with the displacement amount (i think not), but is not necesary.

i do not have this problem before in 1.11.2 versions,, noticed it, when i upgraded to 1.12.2 (mc 1.12.2-0.9.6-ALPHA).    (im using a lot the scan and build tools to build and add things for my friends to build)

**Comment by Raycoms** [comment]
Hey, does this always happen when you mirror or only when you rotate and
mirror?

2018-07-18 23:52 GMT-03:00 GanthorPrime <notifications@github.com>:

**Comment by GanthorPrime** [comment]
only mirror:

the images

https://imgur.com/a/lWx7wZh

 (using a cleans MC install, 1.12.2-forge1.12.2-14.23.4.2707 and minecolonies-1.12.2-0.9.16-ALPHA-universal

**Comment by GanthorPrime** [comment]
if no one can confirm the bahavior shown in the pictures (3 steps to reproduce in creative), then maybe is in my side, but the only thingfor me left, is try changing forge versions.  ¿some specific forge version to use with the latest new alphas of minecolonies?

**Comment by Raycoms** [comment]
I will check it out tomorrow

2018-07-19 0:23 GMT-03:00 GanthorPrime <notifications@github.com>:

**Comment by winex** [comment]
oh, i've checked the rotation + mirroring from far place in creative, it seems normal except that mirroring is off by 2 blocks (shouldn't be at most +1 to the right?): https://imgur.com/a/Luob7kY
didn't use copy/paste yet, w/e that buttons do...

edit: @GanthorPrime just checked 3 times, Paste works fine for StoneHut, BUT @Raycoms DISPLACES the **SupplyCamp**
- forge-1.12.2-14.23.4.2705.jar
- minecolonies-1.12.2-0.9.27-ALPHA-universal.jar

**Comment by GanthorPrime** [comment]
the behavior of the mirror in the preview stage described by @winex is not relevant, at least for me. You made the necesary displacement, rotating in preview mode, and when you paste / order to build, the result was always exactly like the preview shows.  As @Raycoms says, 

> nonetheless, it should place the building exactly where the buildtool says it is.

**Comment by GanthorPrime** [comment]
@winex i tested whith your version and you are right respect to the Huts, the mirror work as intended in worker buildings. the problem appears only whith decorations (no fuctional huts, and scans). tested with parks, and the displacement is very notorious

tested the latest alpha minecolonies-1.12.2-0.9.30-ALPHA-universal.jar.  and is the same.  huts work, but decorations & scans not.   it must be the same with the versions i tested already,  is just that i was testing with decorations.  Anyway,  that worked ok when using it in 1.11.2.

**Comment by Raycoms** [comment]
Okay nice, I will try it out with scans to see what the issue is.

2018-07-20 0:36 GMT-03:00 GanthorPrime <notifications@github.com>:
