### ISSUE TITLE
MineColonies crashes on loading 

### ISSUE THREAD

**Issue by bob0bob** [ldtteam/minecolonies#2631]
### Minecolonies version

minecolonies-1.12.2-0.9.14-ALPHA-universal

### Expected behavior

To load

### Actual behaviour

To not load

### Steps to reproduce the problem
That is the question.

Actually when MC loads up it crashes every time for me.

Here is a copy of the crash report.   I can't get it to duplicate in debug mode.  My debug mode is missing many MODS that my play system has.  It doesn't crash when its just MC and the MODS MC requires.  But in my play world,  it crashes on load.  It gets to the point it is drawing the world and then does a LivingUpdate on a citizen and then crashes.

[crash-2018-07-15_10.47.55-server.txt](https://github.com/ldtteam/minecolonies/files/2195856/crash-2018-07-15_10.47.55-server.txt)

**Comment by Raycoms** [comment]
I will check when I get home

**Comment by Fireruner** [comment]
If you can add a pastebin instead of a file it would be great 😄

**Comment by Raycoms** [comment]
I just checked, this can't be an issue with minecolonies, that must be caused by something else.
We only call super.onLivingUpdate() on onLivingUpdate()
