### ISSUE TITLE
restaurant keeps requesting food

### ISSUE THREAD

**Issue by zerotheliger** [ldtteam/minecolonies#2639]
### Minecolonies version

1.12.2-0.9.21 

### Expected behavior

-Restaurant doesn't keep requesting food till it says in chat that he needs free inventory space.

### Actual behaviour

-  Restaurant wont stop requesting food 

### Steps to reproduce the problem

1. XYZ
2. ZYX
3. ...
4. Profit

**Comment by Raycoms** [comment]
Weird, in the newest version it should put the food in the racks as well

**Comment by zerotheliger** [comment]
He is putting food into the racks till its completely full. And then complaining about clearing the racks cause their full. Hes requesting wheat so much my baker doesnt have any to make bread.

**Comment by Raycoms** [comment]
Yeah, wheat is a problem because another mod adds it as ItemFood... which
it is not and should not be.
But I just checked the code and noticed he really is requesting a bit too
much food, I will adapt this.

2018-07-18 9:35 GMT-03:00 Zerotheliger <notifications@github.com>:

**Comment by zerotheliger** [comment]
Why is he requesting unlimited food?

**Comment by Raycoms** [comment]
Because we didn't add the saveguard yet.

2018-07-18 9:46 GMT-03:00 Zerotheliger <notifications@github.com>:
