### ISSUE TITLE
Building GUI working wrongly

### ISSUE THREAD

**Issue by Thetawaves666** [ldtteam/minecolonies#2643]
### Minecolonies version

version 1.12.2-0.9.6-BETA-universal (and tested on an old 1.12.2-0.8.7809 and the ALPHAs newers than 0.9.6 BETA and it didnt worked too)

### Expected behavior

- Be able to use the GUI when building huts.

### Actual behaviour

- The building didn't appear to be seen, but when i click it in order to build, it appears.

### Steps to reproduce the problem

1. Use the building tool
2. Check any hut and any type of custom (wooden, medieval, etc).
3. Make guesses about how it will look when placed.
4. Profit?

PD: Can upload the map and config if needed.
PD2: Only Using forge, mc, Tree Chopper and Xaero's Minimap

![image](https://user-images.githubusercontent.com/37487971/42900126-7adaa254-8a9e-11e8-9bd3-e3acac962912.png)

**Comment by MineShadow7** [comment]
I'd recommend to remove optifine because it causes some problems with build tool. See if that works.

**Comment by winex** [comment]
@Thetawaves666 i've found that using `Render regions` option kills the build tool. i think it comes from OptiFine
@MineShadow7 how to assign myself, btw?

**Comment by marchermans** [comment]
@winex Do not bother
Optifine is officially not supported untill furhter notice. Render regions is not part of the official MInecraft client and Optifine is closed source. As such this issue is closed.
