### ISSUE TITLE
Baker not baking

### ISSUE THREAD

**Issue by zerotheliger** [ldtteam/minecolonies#2644]
Version :1.12.2-0.9.27-ALPHA

If the baker has 1 or 2 wheat it will not request enough wheat to finish baking.

if i take away all wheat it will request 3 wheat and only 3 wheat. 

a fix would be for a deliveryman to deliver 63 wheat instead of 64 cause if it gives 64 it will be left with one wheat and never request anymore.

**Comment by marchermans** [comment]
@Raycoms

**Comment by Raycoms** [comment]
Should be fixed by the newest update.
