### ISSUE TITLE
Birch builders hut not using storage racks.

### ISSUE THREAD

**Issue by zerotheliger** [ldtteam/minecolonies#2645]
Version 1.12.2-0.9.27-ALPHA

When builders huts are upgraded to include storage racks for overflow in the birch builders hut (the tall square one) it will not use the storage racks to put overflow items into them to get rid of excess items if the mmain builders hut block is full. Almost like it doesnt recognize the racks as storage. Ive tested the mideval style huts and they work fine so do the stone and wooden huts. Just the birch is not working with the excess storage.

**Comment by Raycoms** [comment]
Have you tried this with a new world?

**Comment by zerotheliger** [comment]
No i have not and it may be a while before i do.

**Comment by Raycoms** [comment]
I found the issue, fixing it right now

2018-07-19 11:30 GMT-03:00 Zerotheliger <notifications@github.com>:
