### ISSUE TITLE
Deliveryguy is not pulling items from extra storage.

### ISSUE THREAD

**Issue by zerotheliger** [ldtteam/minecolonies#2647]
### Minecolonies version

1.12.2-0.9.30

Deliverguy should be pulling items from the extra chests and storage racks provided by upgrading various huts. example being Medieval dark oak forge, Medieval dark oak cowboy, Wooden Chicken hut, Tiaga lumberjack hut. He only pulls things that come from the main building inventory tab and ignores everything else, yet builders will deposit and pull from their extra storage chests.

**Comment by marchermans** [comment]
This is by design. The DMan has a dropoff Location so the requesting citizen knows where to find it.

**Comment by zerotheliger** [comment]
So its by design the dman wont go to the smelters extra chests where the smelter puts ingots first before the main chest to put stuff into the warehouse? How will other workers know its there if its not in the warehouse

**Comment by Raycoms** [comment]
I am fixing this atm.

2018-07-19 16:55 GMT-03:00 Zerotheliger <notifications@github.com>:

**Comment by zerotheliger** [comment]
I think they misunderstood my bad
