### ISSUE TITLE
Baker broken after update.

### ISSUE THREAD

**Issue by zerotheliger** [ldtteam/minecolonies#2648]
Minecolonies version

1.12.2-0.9.30

After the lastest baking update the baker no longer bakes bread or anything else for that matter. i emptied all the food out of the warehouse and resturant and from the bakery inventories. she requests 3 wheat, 1 bucket of milk, 2 sugar, 1 egg. she recieves 15 wheat, 1 bucket of milk, 1 egg, 2 sugar, and does nothing but stand there. this is in a medieval dark oak hut level 5.

**Comment by zerotheliger** [comment]
Also ill add that the check mark for the boxes for the pumpkin pie, bread,cake, cookie when its enabled it shows "?4X" instead of just the X in the grey box button.

**Comment by Raycoms** [comment]
Yeah, I reported that to the dev already.

2018-07-19 15:00 GMT-03:00 Zerotheliger <notifications@github.com>:

**Comment by bob0bob** [comment]
I don't understand the "X" thing.   The 2 bytes in front is the minecraft color coding.

This is what I see on my screen.
![image](https://user-images.githubusercontent.com/30982580/42978123-c8f68794-8b90-11e8-9676-1972a63209dd.png)

**Comment by bob0bob** [comment]
I would say its an issue on the upgrade.   The old baker code had many issues on status and moving forward even without the correct items.   I've just retested it and My baker sat there asking for 3 wheat.   The warehouse had none and sat.   It shows up in the chat window the baker needs 3 wheat. (she had 1 wheat).   Then it showed up in the clipboard.
When I delivered the 3 wheat, he started kneading the bread.

**Comment by bob0bob** [comment]
She put it into the furnace(okay, pretend) and then started asking for more wheat.  I have a level 4 baker.  So the baker can make multiple things at a time.

Try,  Unclicking everything and let it sit there for the day until a new day and then click on a recipe and let me know what happens.  I think it might be an upgrade things where the new work load of status are so different.

**Comment by bob0bob** [comment]
I did make one change and the baker is toggling between bread and pumpkin pie.  Those are the two recipes I checked.

**Comment by zerotheliger** [comment]
I forgot to report here but i already talked to one of the devs on discord. After a random amount of time the baker requested cocoa beans got them and started working. And then i was able to freely select which things to bake or not. But that had to be after like 4 day cycles. I have not tested if it works on a new world yet.

**Comment by bob0bob** [comment]
I thought it would finally move out of the weird status the old baker system had.  It was very bugger.  I saw it create bread when it didn't even have the ingredients.  Old code was always trying to push forward through the steps.   The new code should work much better.

From what I'm seeing they are working well.  Next step is to support the new recipe feature to create any kind of food.

**Comment by zerotheliger** [comment]
Nice cant wait ill be here testing as much as possible. Just as long as you blacklist pineapple pizza we are good ;)
