### ISSUE TITLE
Show 5 remaining barb locations

### ISSUE THREAD

**Issue by Raycoms** [ldtteam/minecolonies#2654]
If only 5 barbarians are left, we could display their positions in the Barracks so the player can find them and kill them.

**Comment by MineShadow7** [comment]
And maybe we can show their position without coordinates (Like: 58 metres on the south-west).


That way we can make our chat cleaner.

**Comment by Raycoms** [comment]
Thinking about it, how about we show 1 remaining on level 1, 2 on level 2, etc.

(Relative position as for example the field distance calc in the fields)

**Comment by rsandfield** [comment]
I've been digging at this code recently. At present, the message is built and then passed to the town to be distributed to whoever has permissions to see messages. We would need to retrieve that list and build a multipart translated string, which I think is doable?

**Comment by Raycoms** [comment]
The list exists all over the colony, we would have to sync it with the client side (view) and then display it in the GUI

**Comment by justin-munyer** [comment]
Currently (finally) working on wrapping this up, I have the data synced to the client view, just need to work on the display.  Hope to have it done soon!

**Comment by Asherslab** [comment]
@Shanseala currently we have issues where there is spam because the raiders are in unloaded chunks.
Is there any chance you can look into fixing this issue?

**Comment by justin-munyer** [comment]
@Asherslab spam as in chat spam? raider spawn spam?  Sure I can look into it!

**Comment by Asherslab** [comment]
@Shanseala technically chat spam.
But caused by the way we detect whether there's any raiders left to kill. if the raiders become unloaded (chunk or otherwise) the chat says they've been defeated, when they become loaded, then unloaded again (player moving around) it sends the message again. becomes spammy very quick
