### ISSUE TITLE
Sleeping Citizen - Sharing Beds

### ISSUE THREAD

**Issue by bob0bob** [ldtteam/minecolonies#2656]
When the citizen is sleeping in a bed.  You the player is able to sleep in the same bed.   MC should prevent you from sleep in the bed when a citizen is in the bed.

**Comment by ghost** [comment]
CitizenSleepHandler.java only reads and verifies that a block is a bed before using the minecolony implementation of putting them to bed.

To fix this, use IBlockState to set the bed to the blockstate boolean of OCCUPIED to true while the citizen is asleep, and false during the onWakeUp Method.

Making a note here for myself, or someone else if they get to it before me.
