### ISSUE TITLE
Hitting guard by accident.

### ISSUE THREAD

**Issue by bob0bob** [ldtteam/minecolonies#2664]
There needs to be some kind of level before the guard hits back.

I set a guard to "FOLLOW" and based on the AI code that basically mean on the same block most of the time.   I was standing there and the guard was not visually be able to be seen.  Assume he was right behind me based on the map MOD.  I shot at a skeleton and it went no where because the guard was in the same block as me, just couldn't be seen.

Then after on hit, just turns and tries to kill you.   
Has no one heard of friendly fire.   It should be more than one hit before they attack you.  Specially with the natural of minecraft and how fighting works inside the game.

**Comment by marchermans** [comment]
@bob0bob I am pretty sure we have an Option to supply a distance to a Point that he Needs to have for the Locomotion System to accept it as being at a given Point, try maybe increasing that range, so he considers 2 or maybe even 3 three blocks as valid range?

**Comment by bob0bob** [comment]
Yeah,  that doesn't solve the accidental hitting of a guard and they turning on you.

**Comment by marchermans** [comment]
Well the question is how would you detect it being accidental?
I mean there are players who hit them on purpose.

So i proposed this cause it will lower the chance of you hitting them accidentally.

**Comment by Nightenom** [comment]
If we are already not preventing hitting by sword sweep attack, I think that adding that might solve this
Or just detect if are barbs/hostiles around

**Comment by Kaju-Bubanja** [comment]
This is still a problem, please reopen and fix
