### ISSUE TITLE
Make method to optimize inventories

### ISSUE THREAD

**Issue by Raycoms** [ldtteam/minecolonies#2665]
Would be good to have a method which optimizes inventories, or even better, item providers.
In that means:

Stack items together,
Move similar items together close to each other.
Move items to the top of the inventory.

**Comment by marchermans** [comment]
If we are talking about IItemHandler that is not going to be possible due to the Interfaces contract nature.
Yes we could overrule this Kind of behaviour, but if we implement it, we should only and i really mean only do this for a select set of inventory types.

**Comment by zerotheliger** [comment]
why not do a system similar to how AE does its storage system. make the warehouse one accessible inventory.

**Comment by marchermans** [comment]
It already is. Internally we can do that, but as of right now we can not display that yet.
