### ISSUE TITLE
Sapplings switching not saved correctly

### ISSUE THREAD

**Issue by nonozelmar** [ldtteam/minecolonies#2669]
![capture](https://user-images.githubusercontent.com/5222164/43034327-bc8d9f2e-8cda-11e8-9d54-b5d308fa8374.PNG)
![capture2](https://user-images.githubusercontent.com/5222164/43034328-bca9ff20-8cda-11e8-8294-65aae8d7960c.PNG)

### Minecolonies version

version 0.9.33-ALPHA-universal

### Expected behavior

- Switching some sapplings to "off" keeps them saved on "off" until you switch them back "on" manually

### Actual behaviour

- Switching some sapplings to "off" is only a temporary solution as they're getting switched to "on" automaticly in a short laps of time

### Steps to reproduce the problem

1. Build a lumberjack hut
2. Switch some of the sapplings "off"
2. Wait around 5mn
3. ...
4. Profit

**Comment by bob0bob** [comment]
Are you clicking on "Toggle" and then changing certain ones?

**Comment by nonozelmar** [comment]
Firstly, every sapplings is "on" then i press the "toggle off" button to disable all of them. Finaly I switch the oak sapplings manually to "on"

**Comment by bob0bob** [comment]
Okay.  Toggle off button doesn't work probably.   Any item altered by toggle all  will not save and will come back.    So if they were on and you hit toggle to turn them off and then turn some one.  
Nothing will happen.   
@Raycoms is going to be handling that.  Toggle doesn't send out notice to the building that data has changed and to get an update.   Only individual buttons.  The quick buttons should be disabled until it is fixed.

**Comment by Raycoms** [comment]
we're going to update this code soon, I change a bunch around this to make
this code more efficient.

2018-07-22 20:50 GMT-03:00 bob0bob <notifications@github.com>:

**Comment by Nightenom** [comment]
@Raycoms is this solved?
