### ISSUE TITLE
Can't pickup items from warehouse racks with Forestry backpacks anymore

### ISSUE THREAD

**Issue by lebanni** [ldtteam/minecolonies#2671]
forge-1.12.2-14.23.4.2739-universal.jar
minecolonies-1.12.2-0.9.37-ALPHA-universal.jar

### Expected behavior

Set the backpack (for example mining backpack) in receiving mode. Shift-click a rack with ores inside. Ores are transfered in the backpack.

### Actual behaviour

Shift-clicking a rack switches the backpack mode as if it was done in the air.

This is happening since a few releases ago.

**Comment by marchermans** [comment]
Please give us version numbers

**Comment by lebanni** [comment]
I don't remember exactly. It began with the new rack system, probably at the same time of the new file naming scheme (alpha-beta-release).

**Comment by Raycoms** [comment]
I checked into this,can you report this to the backpack mod, the issue shouldn't be on our side.
