### ISSUE TITLE
Minecolonies modpack crashes during startup from MultiMC 5

### ISSUE THREAD

**Issue by kenny-evitt** [ldtteam/minecolonies#2672]
### Minecolonies version

version 1.12.2-0.9.6-ALPHA

### Expected behavior

Not crash during startup

### Actual behaviour

Crash during startup

### Steps to reproduce the problem

1. "Launch" instance from MultiMC

### More Info

I'm running MultiMC 5 version "0.6.2-1222 on win32". [Maybe the "win32" is not good as I'm on an x64 computer and 64-bit version of Windows 10].

**Comment by kenny-evitt** [comment]
I'm going to attach the crash report as a link to Pastebin or something.

**Comment by Raycoms** [comment]
Please send us the crashlog as well

**Comment by kenny-evitt** [comment]
The crash report:

 - [Minecraft MultiMC 5 crash report - Minecolonies modpack](https://gist.github.com/kenny-evitt/e9524f46abb5554572046cf97f35126b)

@Raycoms Is the "crashlog" different than the above crash report?

I'm going to:

 - [x] ~~Attach what MultiMC labels the "Minecraft log" too.~~

**Comment by Raycoms** [comment]
Just remove the GuideBook mod jar from the mods folder and it should work

**Comment by kenny-evitt** [comment]
@Raycoms That worked; thanks!

Is there code on GitHub for making the modpack?

**Comment by Nightenom** [comment]
Btw, if you want to have it, we are using guidebook 2.0.1

**Comment by kenny-evitt** [comment]
@Nightenom Thanks
