### ISSUE TITLE
Miner upgraded to level 3 building seems to cause a freeze

### ISSUE THREAD

**Issue by gekkobear** [ldtteam/minecolonies#2674]
### Minecolonies version

version minecolonies-1.12.2-9.4.13-349.jar in Enigmatics2 modpack (many other mods as well).
### Expected behavior

- Normal behavior

### Actual behaviour

- Upgrading the miner to level 3 seems to cause a freeze (2/2 tries); not quite a crash, but an unplayable save.  Quitting/restarting does not help.

### Steps to reproduce the problem

1: Level 2 miner, miner is working fine (has dug down 2 levels at lvl 1, done some other mining).
2: Upgrading miner hut to level 3, game freezes and is unresponsive.

EDIT: I should have given a bit more info.  Stone Miner Hut, Positioned with doors to face south.
hill (sand wall) exists 1 block north of structure (just north of the cobblestone walls at the north of the structure).  Level 2 has my worker mining fine, when I upgrade to level 3, the game freezes.

If there's someplace I should dump the save, I can do that.

Crash report when I forcibly halt the game:
Attached document:
https://docs.google.com/document/d/1zFq575ikjCqJ7V7niWcTwtvRkR_q5j0d9KqrB0aAPMM/edit?usp=sharing

Snippet from top of documents:
Time: 7/21/18 6:42 PM
Description: Ticking entity
java.lang.NullPointerException: Ticking entity
	at com.minecolonies.coremod.entity.pathfinding.EntityCitizenWalkToProxy.getMinerProxy(EntityCitizenWalkToProxy.java:96)
	at ... (see more on attached shared document)

EDIT2: Happened with level 2 miner's hut... miner froze (similar log).  Attaching save file with frozen world, in case that helps (Enigmatica 2 1.42 modpack version).

https://drive.google.com/file/d/1hD8q4Eisel6eCULArq-spUzW1Vb_8tZ3/view?usp=sharing

Will play around a bit with the miner (have an FTB backup shortly before this) and see if I can narrow it down further tomorrow.

**Comment by Nightenom** [comment]
This issue got fixed, now we have to add a check for resetting nbt files when a player loads into a world

**Comment by Raycoms** [comment]
Fixed now

**Comment by gekkobear** [comment]
More info... Maybe it?
The pack does have blood magic; and I'd tossed a light source (sigil of blood lamp) at the bottom as they place torches last it seems.
It was at head level when the miner would walk forward to keep clearing the next level.
Maybe that was it?

Clearing that level myself (including that light), then giving the miner back a pickaxe seems to have worked better in any case.
Maybe the miner has trouble pathing through the blood sigil light blocks for this?
