### ISSUE TITLE
Remove sound duplicates - mob\guard\archer\female and mob\baker\female are all the same

### ISSUE THREAD

**Issue by Nightenom** [ldtteam/minecolonies#2677]
Since our mod has 23.5Mb of sounds, it would be great to remove any duplicates (sometimes up to four of one sound)

**Comment by Raycoms** [comment]
We only have each sound once per worker, they are all unique

**Comment by Nightenom** [comment]
We got a sounds.json file so we can use one sound file multiple times
Then we got these and much more of them
![image](https://user-images.githubusercontent.com/17338378/43045777-2899ad04-8dbf-11e8-8363-92f92f042ff5.png)

**Comment by Raycoms** [comment]
Did you listen to them? They should be of different workers.

**Comment by Raycoms** [comment]
Or different recordings of a similar phrase

**Comment by Nightenom** [comment]
I did, from some of them I got a bit scared, but it takes at least 5.5Mb

**Comment by Nightenom** [comment]
And 2,06Mb are exact duplicates

**Comment by Raycoms** [comment]
Wow weird, if they are exact duplicates you can remove them

**Comment by Nightenom** [comment]
`mob\guard\archer\female` and `mob\baker\female` are all the same

**Comment by Raycoms** [comment]
really? They should be different, spoken by the same person but slighly different

**Comment by Nightenom** [comment]
duplicate checker showed me so, I will leave this open

**Comment by Raycoms** [comment]
weird

2018-07-22 12:32 GMT-03:00 Nightenom <notifications@github.com>:

**Comment by Raycoms** [comment]
Weird. I'll check on it.
