### ISSUE TITLE
Server crashes after upgrading from 0.8.7494  to 0.9.1-RELEASE

### ISSUE THREAD

**Issue by WTFSajuuk** [ldtteam/minecolonies#2679]
### Minecolonies version

Minrcraft version
1.12.2

Forge version:
14.23.1.2555

Mod version:
version a: 0.8.7494 
version b: 0.9.1-RELEASE

Server with existing minecolonies in world crashes as soon as someone joins after upgrading from version a to version b

### Steps to reproduce the problem

1. Have existing world with minecolonies version 0.8.749.
2. Have a colonies with all buildings supported in survival.
3. Upgrade minecolonies to version 0.9.1-RELEASE
4. Start server, join game

[crash-2018-07-22_15.01.59-server.txt](https://github.com/ldtteam/minecolonies/files/2217034/crash-2018-07-22_15.01.59-server.txt)

**Comment by Raycoms** [comment]
Please upgrade your forge version and the peoples forge version to the current recommended.
That's the bug (The method does not exist in post forge versions)
