### ISSUE TITLE
Builder complains of non-existent iron ore

### ISSUE THREAD

**Issue by snowyscales** [ldtteam/minecolonies#2684]
### Minecolonies version

version 1.12.2-0.9.1 Release

### Expected behavior

- Builder builds tier 1 builders hut

### Actual behaviour

- Builder complains of non-existent iron ore block several blocks outside and below building area.

### Steps to reproduce the problem

1. Take stone pick from builder
2. Cancel build
3. Start Build
4. Builder will either move to start building & then complain about phantom iron ore
  4b. or Builder will wait to be given stone pick & then go to start building & then complain about ore

### Note

The game is also played with Forge, Optifine, AppleCore, AppleSkin, Extra Utilities 2, Hunger In Peace, Inventory Tweaks, JourneyMap, JEI, Mouse Tweaks, Quick Leaf Decay, Vanilla Builders Extension, Vein Miner, Waila, Waila Harvestability, and What Are We Looking At

[Kingdoms.zip](https://github.com/ldtteam/minecolonies/files/2220838/Kingdoms.zip)

**Comment by BonaireDreams** [comment]
Check the co-ordinates of the ore. I found they are usually one block down and over from his work area or something similar so you don't see it, but its there. Its a problem fir the T1 because he can't mine that type until you upgrade the hut and give him a better pick. So just go clear it out manually.

**Comment by snowyscales** [comment]
Oh, I did go clear it out manually. You can find the hole I left behind out back of the hut. straight down and then a... 2x2/2x3? (i forget exactly) to the side. But the builder continues to complain about it.

**Comment by BonaireDreams** [comment]
He doesn't know its gone because he didn't remove it so you need to reset him so he scans the area again and sees that its gone. I don't remember if just recalling him works, or if you have to fire and then rehire him, but one of those should do the trick.

**Comment by snowyscales** [comment]
I've fired her and rehired her; fired her and hired somebody else; cancelled the building order and restarted it, and the builder still complains.

EDIT: Resolved. Axeing the builders hut and re-placing it fixes the issue.

**Comment by Nightenom** [comment]
@snowyscales I destroyed those ores (8 iron) and she continued
@Raycoms The question is why she needs to destroy iron ores 6 blocks under the ground and why she can't destroy while having a stone pickaxe

**Comment by Raycoms** [comment]
It's probably because the building level wasn't high enough for her to
destroy it.
And she needs it because it doesn't match the schematic.

2018-07-24 12:23 GMT-03:00 Nightenom <notifications@github.com>:

**Comment by Nightenom** [comment]
Okay, closing it since player solved it and it's also player solvable
