### ISSUE TITLE
Citizens going in circle chasing each other

### ISSUE THREAD

**Issue by realm174** [ldtteam/minecolonies#2686]
### Minecolonies version

minecolonies-1.12.2-0.9.4-BETA-universal

### Expected behavior

Workers go to their assigned task, if any, or wander aimlessly

### Actual behaviour

3 of my citizens (Builder, delivery guy and shepherd go in circle chasing each others.

### Steps to reproduce the problem
Not sure how to reproduce that, I don't think I've done anything out of the ordinary. I've been playing with minecolonies since it was originally created. But here is a video on youtube of what I mean:

https://youtu.be/AW58rrqrTL8e

The only other thing that might be related, there were 3 barbarians (according to the chat) that came over. I killed one, never found the other two.   Citizens started going in circle within half hour of the barbarian being killed.

**Comment by Nightenom** [comment]
Can you attach your world please?

**Comment by realm174** [comment]
I'd love to, but apparently it's too big. 75MB zipped. Suggestion?

**Comment by Nightenom** [comment]
Use any cloud, dropbox etc.

**Comment by Raycoms** [comment]
The newest alpha should solve this issue.

2018-07-25 15:13 GMT-03:00 realm174 <notifications@github.com>:

**Comment by realm174** [comment]
ok, I'll go grab the newest Alpha and report back. If it doesn't fix it, I'll upload my world to my Google-Drive.

**Comment by Raycoms** [comment]
Sounds good =)

2018-07-25 15:17 GMT-03:00 realm174 <notifications@github.com>:

**Comment by realm174** [comment]
Everybody went back to work, thanks!! :)
