### ISSUE TITLE
Colony dissapeared after crash

### ISSUE THREAD

**Issue by TheNumenorean** [ldtteam/minecolonies#2687]
### Minecolonies version

version X.X.XXXX or curse 0.9.50

Using allthemods3 pack

### Expected behavior

- Colony does not stop existing

### Actual behaviour

- Colony stops existing

### Steps to reproduce the problem

1. The game crashed for possibly unrelated reason: "dyn" was typed in to jei
2. log back into single player
3. all colony boxes are inaccessible and commands report no existing colonies.

Error: https://gist.github.com/TheNumenorean/a2866e78ffc350c3245e00f37a8fa29e

**Comment by BonaireDreams** [comment]
1) Exit game, 
2) Go to your World folder/minecolonies
3) restore your colonie.dat file from one of the backups.
4) Profit

You may need to recall all the citizens at the Town Hall at which point they will restore. Minecolonies was probably writing to your colony file at the point of the crash and its corrupted. There's always like 10 incremental backups of the colony file though so its easy to restore.

This is the folder for my server. Start with the latest zip file, if that's still bad go back one more. Worst case a few things the colonists have done in that time is gone, but any buildings that were built/blocks that were placed will be there. You may need to give them their commands again. IE if you had your builder start a new building.

![screenshot 3098](https://user-images.githubusercontent.com/5133282/43270836-da65d9d4-90aa-11e8-8c3c-33fde0f8ff5c.jpg)

**Comment by TheNumenorean** [comment]
Many thanks! Worked perfectly.

It does seem likely the crash wasn't the fault of minecolonies, so perhaps it would be worth adding these recovery steps as a wiki page, either on Github or the standalone.

**Comment by Nightenom** [comment]
Closing it since it's solved, we will try to add some recovery instructions to our wiki
