### ISSUE TITLE
Can´t see building previews after a short period of playing

### ISSUE THREAD

**Issue by Glogiator** [ldtteam/minecolonies#2702]
### Minecolonies version

version 0.9.1

### Expected behavior

- not disappear

### Actual behaviour

- when i play for a little while, the building previews disappear and i have to restart my client to get them back.

I have an old computer and i just wanted to know if its just my hardware or if it happened to more people, therefore making it a bug.

**Comment by Raycoms** [comment]
What do you mean with disappear? Like if you click with the buildtool no
new preview loads?

2018-07-29 12:26 GMT-03:00 Glogiator <notifications@github.com>:

**Comment by Glogiator** [comment]
I just get a little lag spike and then i can't see any building previews when i right-click the building wand until i restart the game.

**Comment by Nightenom** [comment]
@Glogiator if your issue still persists please send a log, otherwise close this
