### ISSUE TITLE
SSP Hard Crash & Lockout

### ISSUE THREAD

**Issue by kreezxil** [ldtteam/minecolonies#2704]
# Data
**Minecraft:** 1.12.2
**Forge:** 14.23.4.2739
**Minecolonies:** 1.12.2-0.9.35-ALPHA

# Description
Submitted to my World of Dragons pack issues thread runeslayer229 at https://minecraft.curseforge.com/projects/world-of-dragons/issues/13
I have been focusing on minecolonies and all i was doing was digging dirt for my buildings and the game crashed and i tried to re log and it crashed again.

# Crash Report
client crash report: https://pastebin.com/uRjADrHJ

**Comment by Nightenom** [comment]
Solved in #2674 and on discord 5 days ago, you wrote that you already updated the pack so it should be ok

**Comment by Nightenom** [comment]
In version 0.9.39-ALPHA
