### ISSUE TITLE
smelter does not smelt ore except for gold ore

### ISSUE THREAD

**Issue by Too-DAMN-Much** [ldtteam/minecolonies#2707]
he's got tons of ore in his chest waiting to be smelted, both mods and vanilla and is ignoring it.

also why does it waste wood as fuel that's just going to add yet another layer of tedium on top of all the useless blocks that you can't see that schematics include for no reason.

**Comment by Raycoms** [comment]
Your lumberjack should provide enough wood for that, the newest jar should fix this, reopen if still an issue
