### ISSUE TITLE
schematics are excessively wasteful of materials

### ISSUE THREAD

**Issue by Too-DAMN-Much** [ldtteam/minecolonies#2708]
too many of the schematics have the builder place a few hundred slabs or stairs for no reason when they could use full blocks to waste less resources.

if you're going to use more than two slabs on top of each other, i will murder you in my worlds, that's just stupid, use a full block.

**Comment by OrionDevelopment** [comment]
For vanilla -> three blocks -> 6 slabs -> 3 full slab blocks. No wasting.

**Comment by OrionDevelopment** [comment]
But we can look into it.

**Comment by Too-DAMN-Much** [comment]
@OrionDevelopment it depends on the case, i see a lot of the time the builder placing slabs or stairs in a way that makes a full block even when it's not offset of the normal block grid by .5 which is the main reason for using a lot of slabs typically.

**Comment by Too-DAMN-Much** [comment]
> For vanilla -> three blocks -> 6 slabs -> 3 full slab blocks. No wasting.

it's more individual blocks that have to be placed and supplied, sure it's same material cost though, also aren't slabs still counted as a half block each? can't say i really ever cared much to keep track.

**Comment by Nightenom** [comment]
walls need to be full or with torch inside of them so they prevent mob spawning, but we may use some waste material like cobble

**Comment by Too-DAMN-Much** [comment]
ah, that must be why there's like 4 full blocks solid in the roofs in some of the buildings vertically.

**Comment by Raycoms** [comment]
Yeah, if we don't fill them mobs spawn there

2018-07-29 21:55 GMT-03:00 Too-DAMN-Much <notifications@github.com>:

**Comment by Nightenom** [comment]
Closing this since it looks solved
