### ISSUE TITLE
colonists want wood or golden level tools ignoring stone despite it being a valid level

### ISSUE THREAD

**Issue by Too-DAMN-Much** [ldtteam/minecolonies#2709]
read title, self explanatory.

**Comment by OrionDevelopment** [comment]
Upgrade both your Buildings and your workers. Stone is Level. Gold and Wood are Level 1.
I just tested this, and verified that it works. Which it does.

Please verify that this issues persists with both higher skilled workers, and higher skilled Buildings.

**Comment by Raycoms** [comment]
Stone only works when your building is on level 1, before that it's gold
and wood. Which version are you playing on? 1.12.2?

2018-07-29 17:01 GMT-03:00 Marc Hermans <notifications@github.com>:

**Comment by Too-DAMN-Much** [comment]
actually from what i've seen gold and wood is from level one, they do use stone and iron and diamond tools later, it just seems weird because the progression is wood->stone->metal->diamond which this mod definitely veers away from, they skip over stone entirely and waste an awful lot of time using wooden tools.

**Comment by Raycoms** [comment]
THey should be using wood on Level 1 of the hut, do you have any other mods
added?

**Comment by Too-DAMN-Much** [comment]
yeah, hundreds.

i might have just misread the request, or upgraded the builder's hut mistakenly but it seemed like they were showing gold shovels in the request by the builder from the start.

but the whole issue is if you have gold you can use stone.... and they still refused it.....

was probably me upgrading it and forgetting.

**Comment by Raycoms** [comment]
Gold level is lower than Stone level. Gold and Wood is one level, the next
one is stone. On the stone level he will accept gold and wood as well, but
should also accept stone without any problem.

2018-07-29 17:10 GMT-03:00 Too-DAMN-Much <notifications@github.com>:

**Comment by Too-DAMN-Much** [comment]
why would gold ever be lower than stone? it requires an iron pick to mine...

**Comment by Raycoms** [comment]
It's not about the ore, it's because a gold tool and a wood tool are
equally useless to mine stuff

**Comment by Too-DAMN-Much** [comment]
it's just confusing to buck the established tier system and reinvent the wheel without warning, that wasn't the real issue anyway, for what it's worth i'm fairly sure gold can be better than stone with the right enchants but i'd have to check.

regardless, it seemed that they were preferring wooden tools when i gave them both stone and wooden ones in the builders chest for a shovel, but i can't be sure i hadn't already upgraded the builder's hut so closing this for now and will keep an eye on it and re-open or create a new issue later as needed.

@Raycoms @OrionDevelopment

**Comment by Raycoms** [comment]
They will prefer the first tool they find in the inventory. And that's not
what we reinvented. Following the minecraft tier system it is like that (Of
course, independendly of enchantments)

2018-07-29 17:30 GMT-03:00 Too-DAMN-Much <notifications@github.com>:
