### ISSUE TITLE
town hall schematic changes position when rotated using reposition.

### ISSUE THREAD

**Issue by Too-DAMN-Much** [ldtteam/minecolonies#2710]
i accidentally built my town hall facing the opposite direction of where i want and i can't turn it around now with repositioning because the blueprint isn't symmetrical (at least in size) and if i turn it 180 degrees it overlaps other buildings i built close to it.

shouldn't be too hard to recenter it inside of it's work area bounding box, also most of the others look fine when built on level ground, except for the town hall which stupidly digs itself a 1 deep block trench around itself when built on flat ground.
some warning to put the town hall block floating in mid air would have been nice and saved a ton of work of the builder too.

**Comment by Too-DAMN-Much** [comment]
the derpy troublemaker's handiwork here, all my buildings were build on level ground which i went to a lot of trouble to flatten first.

https://imgur.com/a/QDMagbX

too much of a waste of time/effort to bother repositioning it.

**Comment by Nightenom** [comment]
We need to make a better ingame tutorial, for now just use +/- in the buildtool gui to make yourself sure it's on the ground

**Comment by Too-DAMN-Much** [comment]
yeah, i know, just they aren't predictable which ones will float over the ground is all if you place them one block above so it's hard to plan.

**Comment by Raycoms** [comment]
You can rotate it and then adjust the position a bit to the left and right (the chest doesn't have to be in the exact same location)
