### ISSUE TITLE
miner chest isn't emptying by deliveryman

### ISSUE THREAD

**Issue by Too-DAMN-Much** [ldtteam/minecolonies#2711]
i have both miner and deliverman hired and present and the miner complains a lot that their chest is full, i notice she puts partial stacks separately a lot, but it also doesn't look like the deliverymen are taking it away either.

i have a warehouse and smeltery too, so there should be plenty of destinations.

**Comment by Raycoms** [comment]
The dman takes it away depending on his hut level, so on hut level 1 only 1
stack at a time, which is quite slow, so you need to level up his hut to
make it more efficient, did you try that?

2018-07-29 22:47 GMT-03:00 Too-DAMN-Much <notifications@github.com>:

**Comment by Too-DAMN-Much** [comment]
i'll try upgrading it some more, screenshot of my things built.

https://imgur.com/a/JsYtgiR

oh it's on the list already, i was wondering if i can hire a second?

**Comment by Raycoms** [comment]
You can hire more builders and you can hire also more deliverymen, up to 5 deliverymen can work at 1 warehouse.

Reopen please if still an issue after upgrade
