### ISSUE TITLE
can we teach workers 3x3 recipes in any way so they can craft stairs, slabs, etc for themselves when building?

### ISSUE THREAD

**Issue by Too-DAMN-Much** [ldtteam/minecolonies#2712]
i can't find a way to teach them 3x3 recipes only 2x2 and you can't make stairs and slabs without a 3x3 so i keep having to either craft or give my builders more of them at some point.

**Comment by Raycoms** [comment]
There are some issues about that already and there is a pr for that, but for 3x3 recipes we will have special workers for that

**Comment by Too-DAMN-Much** [comment]
ah okay, thanks.
