### ISSUE TITLE
Farmer Just Standing Around

### ISSUE THREAD

**Issue by DoctorLovely** [ldtteam/minecolonies#2716]
### Minecolonies version

version 0.8.9646 or curse X.X.XX

### Expected behavior

- Till the field and plant carrots or wheat

### Actual behaviour

- walks to field and stands around

### Steps to reproduce the problem

1. Farmer asks for hoe
2. gives the hoe
3. asks for seeds or carrots
4. give what he asks
5. walks to field and does nothing

**Comment by bob0bob** [comment]
@DoctorLovely Is water under the block for the field?

**Comment by AlexKinney** [comment]
@bob0bob - ran into the same issue and removing the water (generated river if it matters) that was 4 blocks under the field fixed it

**Comment by bob0bob** [comment]
I've noticed that many times, if your citizen is walking and then just stands there.  MANY MANY times it means water is under the ground and that causes the pathing system to get messed up.

**Comment by Raycoms** [comment]
Should be fixed
