### ISSUE TITLE
Config being ignored?

### ISSUE THREAD

**Issue by MayhemBill** [ldtteam/minecolonies#2717]
### Minecolonies version

 curse 1.12.2-0.9.1

### Expected behavior

- When setting infinite colonies in config, it should allow me to make as many as I'd like

### Actual behaviour

- Say I already placed one, even though it's been deleted

### Steps to reproduce the problem

1. B:allowInfiniteSupplyChests=true
2. restart server so config takes place
3. try to place supply chest
4. Fail

**Comment by Raycoms** [comment]
This allows you to place more ships and camps and not more colonies.
did you just remove the townhall or did you delete it with /mc colony
delete colony: 1 (if you're on singleplayer)

2018-07-31 11:08 GMT-03:00 BillyTheHero <notifications@github.com>:

**Comment by MayhemBill** [comment]
I deleted the Colony with the command, and I'm on a server, I have file access, and so far I've been the only person to touch the mod, so i can do whatever is needed.

**Comment by Raycoms** [comment]
and you still can't place a new townhall? what does /mc colonies list give
you?

2018-07-31 11:15 GMT-03:00 BillyTheHero <notifications@github.com>:

**Comment by MayhemBill** [comment]
It returned blank, I restarted the server and I could place a town hall, so I'm not sure what happened
I still can't place Supply chests though

**Comment by Raycoms** [comment]
Will look into that then.

2018-07-31 11:28 GMT-03:00 BillyTheHero <notifications@github.com>:
