### ISSUE TITLE
town hall is GONE

### ISSUE THREAD

**Issue by thecoolboy123** [ldtteam/minecolonies#2718]
### Minecolonies version

version 1.12.2 
### Expected behavior

- use building tool
-place town hall

### Actual behaviour
-i used the building tool to place the townhall,and it spawned these fences into the land as expected however it didnt spawn the town hall chest,i tried going to creative to get and place a new one,but it said that i already have a town hall,ive looked everywere and didnt find my town hall

### Steps to reproduce the problem

1. Use building Tool to place town hall chest
2. townhall chest dissapears
3. try all things possible to get townhall chest back
4. end up deleting the mod because at this point it only slows down your world

**Comment by Raycoms** [comment]
is it possible that it placed the townhall just underground?

2018-07-31 19:38 GMT-03:00 thecoolboy123 <notifications@github.com>:

**Comment by Raycoms** [comment]
Please reopen if you still can't find it
