### ISSUE TITLE
Meal On Wheels (or feet)  - change idea presentation

### ISSUE THREAD

**Issue by bob0bob** [ldtteam/minecolonies#2720]
I have an idea of changing  food eating/restaurant/baker.  it will effect all three areas of the game.
This is my idea.

Restaurant on level 2 ->  has the ability to hire a new citizen.  Means on Wheels guy.  Delivery guy of food.
The restaurant has a list of all citizen when they last were given food to eat by the restaurant.

The config file, would have the ability to list types of food into 3 categories.
Main Dish, Bread, Desert.
You like the the items that meet those categories.

The delivery guy shows up to the restaurant every day and tries to delivery 1 of each type of food to each citizen.  it is based on a list how has not received food the longest.  We say the citizen can delivery (say 8) citizens at a time.  The person tries to gab one of each item for each person on their list from the restaurant and then goes to the baker to get the rest.  
Once they have their entire list or as much as they can get.   They start delivering based on this list.

Each citizen will get one delivery per day no matter what their saturation level is.   The citizen will adjust the new happiness modifier based on quality of food.  if they only get bread because the delivery man ran out of main dishes.  Then they will adjust their happiness based on the 3 areas of food they receive everyday.

At the end of the day  each citizen that receives food gets marked they received food and so the next day they will be at the bottom of the list and the delivery guy will start at the top and work done. 

This would be an easy addition to the game and would start using more of the food and make it so you are using better food.  This will make the restaurant/baker equal part of the colony.

Let me know how this sounds and other ideas, please add comments.

**Comment by Raycoms** [comment]
Closed in favor of joint issue.
