### ISSUE TITLE
[Suggestion-Improvement] Builder Materials List

### ISSUE THREAD

**Issue by MokahTGS** [ldtteam/minecolonies#2721]
Is there any way that a building materials list can be produced and given to the player that lists the materials needed for the next stage of a building?

I was thinking that it would be really handy to have a button on the Builders chest UI that "exports" a list on paper or a clipboard item that the player can take with them to gather all the blocks needed instead of having to run back to the builder hut each time we forget that one blasted hatch or piece of colored wool.

Also, can the builder chest size be increased?  It's no where big enough.

**Comment by Raycoms** [comment]
Might be just something I can produce on the weekend.

**Comment by bob0bob** [comment]
@Raycoms   Was thinking on the clipboard to have multiple tabs (on for each builder) and on that tab list the wanted items the builder has on its gui.   Remove the fulfillment option,  Dman or player needs to deliver it.

This would allow a person to see the entire list while they are in the warehouse collecting things for that builder.

**Comment by BonaireDreams** [comment]
You could make it a book/clipboard that needs to be crafted with tabs for each hut and what they are currently requesting. Not just the builders. It could show the same as the request tab in the crate if the DMAN is already scheduled to deliver the item. It would go a long way to see that, "oh hey, my herder needs shears, DMAN is not delivering any so I must not have any in the warehouse. I better craft some."
