### ISSUE TITLE
[minecolonies]: ForgeHook not in sync with EfficientTool for Block{ic2:resource} and 53xtile.woodSlab@0 Please report to MineColonies with this text to add support!

### ISSUE THREAD

**Issue by Praetorious** [ldtteam/minecolonies#2725]
### Minecolonies version

version 0.8.9646 

I am running an all the mods 3 server for me and some friends and we are having some issues with this 
ForgeHook not in sync with EfficientTool for Block{ic2:resource} and 14xtile.woodSlab@0 and  ForgeHook not in sync with EfficientTool for Block{ic2:resource} and 53xtile.woodSlab@0.  

I don't know exactly what this is so I cannot diagnose what effect it has in game.  I don't know if there is any other info you may need.  

Thanks

**Comment by Raycoms** [comment]
Thanks for reporting it, it's some old log we have in it, so if only the log is printed but there is no ingame issue you don't have to worry about it.
