### ISSUE TITLE
[Request] TUMAT integration

### ISSUE THREAD

**Issue by canitzp** [ldtteam/minecolonies#2728]
In the current LimboCon version there isn't Waila or TOP as InWorld Tooltip. THere is Tumat and to add integration is easy. Per example you can show the profession and tasks of your citizens and much more. 
Curse Forge: https://minecraft.curseforge.com/projects/tumat
Github page: https://github.com/canitzp/TUMAT
Jenkins: https://ci.chaosfield.at/job/TUMAT/job/TUMAT/
Maven: https://maven.chaosfield.at/

**Comment by Raycoms** [comment]
@canitzp there is no instruction page on how to use this.

**Comment by Raycoms** [comment]
Will be added to a new joint mod compat issue.
