### ISSUE TITLE
Can't Upgrade any buildings

### ISSUE THREAD

**Issue by gkulick** [ldtteam/minecolonies#2736]
minecolonies-1.12.2-0.9.50-ALPHA-universal.jar
enigmatica 2  v1.4.3

### Expected behavior

- click upgrade - builder starts building the upgrade

### Actual behaviour

- builder stands around with no requests

### Steps to reproduce the problem

1. make a building 
2. click upgade
3. Chat says Build Request Created
4. Builder doesn't go build any thing

Logs from server related to minecolonies
[16:32:35] [Server thread/INFO] [minecolonies]: WorkOrderBuild at location BlockPos{x=-11, y=84, z=-263} is using schematics/Birch/Citizen1 instead of schematics/Birch/Citizen1
[16:32:35] [Server thread/INFO] [minecolonies]: WorkOrderBuild at location BlockPos{x=-11, y=84, z=-263} is using schematics/Birch/Citizen2 instead of schematics/Birch/Citizen2

Hope that helps.

**Comment by Raycoms** [comment]
can you send us the full log? Maybe even the world

2018-08-03 17:43 GMT-03:00 gkulick <notifications@github.com>:

**Comment by philipjholm** [comment]
I had the same problem and fixed it by removing the \world\stats json file completely. I have no idea why, but it fixed it :)

**Comment by Nightenom** [comment]
Hmm weird but we still need at least logs, a world would be helpful too.

**Comment by bob0bob** [comment]
I currently see that if you click on "fulfill"  for the request.  the citizen doesn't notice this.  If you go to their inventory and manually put it in there then they see it and move forward.  I've only noticed this on builders.  If you click on "fulfill" with armor request from the guards, it kind of works.  It gives them the item but from that point forward the gui doesn't work anymore.  if there was 2, the second gets disabled, the "cancel" does nothing.  You have to close the gui and open it again and the 2 "fulfill" will show back up.

**Comment by Raycoms** [comment]
Gotta refresh the GUI then

2018-08-07 12:33 GMT-03:00 bob0bob <notifications@github.com>:

**Comment by bob0bob** [comment]
its more than that.  Most of the time the "Cancel" button does nothing when you click it.  But not always, some times it works.  I've not been able to pin it down at all some kind of pattern.

**Comment by Raycoms** [comment]
Should be fixed
