### ISSUE TITLE
[Suggestion] Weather2 integration

### ISSUE THREAD

**Issue by ErdbeerbaerLP** [ldtteam/minecolonies#2743]
When Weather2 is istalled the mod should ignore vanilla weather and react to the changed weather.

1. Rain: When it rains most citizens stay in thier house or in the town hall. If some are walking aroud outside they use an umbrella (this could also be implemented for vanilla rain). Builders, deliverymens and guards are still at work.

2. Storm/hail: When it is storming guards are still at work but every other citizen will stay in thier house or the town hall.

3. Tornado/sandstorm: Noone is going outside now till it goes away.

**Comment by QueenBonnydust** [comment]
I second this request!

**Comment by SCAgamer** [comment]
Third as well. I've lost too many villagers due to the weather. I've turned off block breaking and mob grab just because of this issue.

**Comment by mike7998** [comment]
I will add to this. It would be cool if there was a bunker that citizens rushed to when the stage reaches hail so they can get underground. most houses aren't built to withstand tornadoes.

**Comment by shivachirr** [comment]
i wonder if there has been any progress on this as of yet would like to see this implmented

**Comment by Raycoms** [comment]
Yeah, we're currently busy with a lot of other mod features and fixes and
enhancements. Mod compatibility is unfortunately not very high on the list.
If you know anyone who could work on this we're completely open source and
accept outside contributions.

Am Mo., 7. Jan. 2019 um 16:15 Uhr schrieb shivachirr <
notifications@github.com>:

**Comment by Raycoms** [comment]
Will be added to a new joint mod compat issue.
