### ISSUE TITLE
Crash - Viewing Clipboard.

### ISSUE THREAD

**Issue by bob0bob** [ldtteam/minecolonies#2749]
### Minecolonies version

-1.12.2-0.9.82-ALPHA-universal

When I try to open the clipboard I get the following crash.

It appears to happen when there are a bunch of requests at once.

[crash-2018-08-04_23.03.21-client.txt](https://github.com/ldtteam/minecolonies/files/2260036/crash-2018-08-04_23.03.21-client.txt)

**Comment by Nightenom** [comment]
Confirmed from a guy on discord via https://pastebin.com/vBMzDEdy

**Comment by marchermans** [comment]
Problem with the current blockout. We know it exists, yet it is a flaw in its design. Will be fixed once the new BlockOut goes live.
