### ISSUE TITLE
Fisherman not getting experience anymore

### ISSUE THREAD

**Issue by nonozelmar** [ldtteam/minecolonies#2751]
### Minecolonies version

minecolonies-1.12.2-0.9.85-ALPHA-universal

### Expected behavior

- With a level 4 hut , the fisherman should be able to level up until being level 32.

### Actual behaviour

- It stop getting experience after reaching level 16

### Steps to reproduce the problem

1. Build a fisherman hut level 4
2. Hire a worker and let him do his work
3. Profit
![capture](https://user-images.githubusercontent.com/5222164/43688146-d4c0a4b4-98e3-11e8-9d44-3405b091105c.PNG)

**Comment by Nightenom** [comment]
Try upgrading your townhall, a citizen level is capped by placed (s)he lives in. That doesn't match the wiki content and also sounds weird. Can we change it @Raycoms?

**Comment by nonozelmar** [comment]
Oh okay because my townhall is level 4 but all of the citizen hut are level 3 that would explain why. Do you know how to reassign citizen living in the townhall so i can switch some of them ?

**Comment by Nightenom** [comment]
? When you have manual hiring/housing on - if they are not assigned they end automatically in townhall "register"

**Comment by nonozelmar** [comment]
yes but even though i switch to manual hiring , i can't find a way to reassign citizen staying in the townhall as this latter is already full of citizen

**Comment by Nightenom** [comment]
You assign workers in hut blocks

**Comment by nonozelmar** [comment]
i think i misspoke, i meant i want to reassign the place where the citizen is housed and i can't find a way to switch the citizen housed in the townhall while i can with the citizen's hut

**Comment by Nightenom** [comment]
Citizen is housed in a citizen hut (if assigned there, you can only switch citizen's house here) or in townhall (by default)

**Comment by Raycoms** [comment]
should be fixed
