### ISSUE TITLE
Registering on the website

### ISSUE THREAD

**Issue by decurr** [ldtteam/minecolonies#2754]
I tried to register.  It is asking way too many times to verify.  It asked 5 times each for roads then for cars.  I was about ready to give up when it finally accepted my answer and I could click submit.  I did.  The next page tells me I failed the verification.  I had to go through that hell again just to use the "contact us".  Then it only asked twice each for signs, buses, and roads.  It finally accepted my answer and I could click submit that time, it tells me I failed that verification too.

**Comment by Raycoms** [comment]
Hey, that's a common issue with the google captcha. If your IP or country is connected with a lot of spam they make your life a hell.
