### ISSUE TITLE
Add cfg option to disable "you're entering/leaving x's colony" message

### ISSUE THREAD

**Issue by terrapin47** [ldtteam/minecolonies#2755]
The message that displays to both the colony owner and entering/leaving user when crossing colony borders ends up spamming users that are building nearby/together when one of them has a colony.

With certain server setups, this message isn't needed ( servers with known friends, trusted folk etc ).  It would be great if there was a config option to disable these messages, as it is a point of great annoyance for some users.

Thanks.

**Comment by Raycoms** [comment]
Of course, that should be easy to do.

2018-08-05 19:52 GMT-03:00 Terrapin47 <notifications@github.com>:

**Comment by Hgord98** [comment]
What is the command? Having this issue while playing mc eternal with friends.

**Comment by ravenbuilder934** [comment]
MC Eternal is 1.12, which isn't supported any more

**Comment by Hgord98** [comment]
It says it is the 0.11.811 beta, what was the version with the command patched in?
![Base Profile Screenshot 2021 02 03 - 15 00 43 15](https://user-images.githubusercontent.com/78500611/106808922-a5bca880-6630-11eb-9a97-ffb3fc4fe99d.png)

**Comment by ravenbuilder934** [comment]
Again, that's 1.12. We will not help you with 1.12.

**Comment by Hgord98** [comment]
Alright, thanks for the quick response.
