### ISSUE TITLE
Builder not receiving upgrade workorder

### ISSUE THREAD

**Issue by FirzenDark** [ldtteam/minecolonies#2757]
### Minecolonies version

Minecolonies version 1.12.2-0.9.82

### Expected behavior

- Builder to upgrade buildings

### Actual behaviour

- No workorder is received by builder. I can see the workorder in the townhall book.

**Comment by Raycoms** [comment]
is the builders building at least on the upgrade level of the other
building?

2018-08-06 11:32 GMT-03:00 FirzenDark <notifications@github.com>:

**Comment by FirzenDark** [comment]
I tested now and the builder don't even receive the work orders for new buildings

**Comment by Raycoms** [comment]
Uh, that is weird, is it raining, night, did you change the day night
process?

2018-08-06 11:50 GMT-03:00 FirzenDark <notifications@github.com>:

**Comment by FirzenDark** [comment]
It was day time. But I noticed after a days cycle the builder start to build the new building. Will test the upgrade and let you know if the upgrade still not working. Tx for the quick response and keep up the good work on a wonderful mod.

**Comment by FirzenDark** [comment]
Another question, will you be setting up a quest book?

**Comment by Raycoms** [comment]
Yeah, we're working on that =)

2018-08-06 11:59 GMT-03:00 FirzenDark <notifications@github.com>:

**Comment by FirzenDark** [comment]
Ok, it looks like my builder was not upgraded to the correct level. Something I did notice is that when the builder request something and you add it through the required resources the builder don't accept it. You have to give it directly to him

**Comment by Nightenom** [comment]
Possibly same issue as #2736
