### ISSUE TITLE
Extra health for citizens displays badly

### ISSUE THREAD

**Issue by mraof** [ldtteam/minecolonies#2761]
### Minecolonies version

1.12.2-0.9.85-ALPHA

### Problem

When a citizen has too much health, because of something like scaling health, the health goes off the background
![2018-08-07_16 36 22](https://user-images.githubusercontent.com/1010427/43802304-6103699a-9a63-11e8-97ed-2937b17da7f2.png)

**Comment by Raycoms** [comment]
Fixed
