### ISSUE TITLE
Composter Lag

### ISSUE THREAD

**Issue by ItsmeAga** [ldtteam/minecolonies#2762]
### Minecolonies version

minecolonies-1.12.2-0.9.86-ALPHA-universal.jar

### Expected behavior

Not to lag

### Actual behaviour

After building the composter(lvl1) the server started "Can't keep up" messages and the game got laggy, fixed right away after breaking the composter block

### Steps to reproduce the problem

1. Build Composters
2. Check lag

**Comment by Raycoms** [comment]
@Fireruner could you take a look at this?

**Comment by Fireruner** [comment]
Sure I'll take a look 😄

**Comment by Fireruner** [comment]
@ItsmeAga was this on mp or on sp? Can u tell me the specs of the system runing the game and server? Thanks

**Comment by ItsmeAga** [comment]
was on singleplayer, though I run the local server on a different computer, its using a i5-3210M @ 2.50GHz Cpu and got 8GB ram. The server never uses more than ~30% of either though
