### ISSUE TITLE
Warehouse GUI not updating when finished

### ISSUE THREAD

**Issue by PlessyvsFerguson** [ldtteam/minecolonies#2765]
### Minecolonies version

curse minecolonies-1.12.2-0.9.1-RELEASE-universal.jar 
Tested on latest alpha

**Expected behavior**

When Warehouse is complete, I can assign a deliveryman and access the updated GUI.

#### Actual behaviour

GUI is only upgrade building, repair building and inventory.

#### Steps to reproduce the problem

1. Build builder
2. Place warehouse block and build
3. Reopen block GUI
### Minecolonies version

curse minecolonies-1.12.2-0.9.1-RELEASE-universal.jar 
Tested on latest alpha

**Expected behavior**

When Warehouse is complete, I can assign a deliveryman and access the updated GUI.

#### Actual behaviour

GUI is only upgrade building, repair building and inventory.

#### Steps to reproduce the problem

1. Build builder
2. Place warehouse block and build
3. Reopen block GUI

**Comment by Raycoms** [comment]
Actually, you can't assign deliverymen to warehouses, for that we have an
extra building which is the deliveryman hut which includes this.

2018-08-09 9:34 GMT-03:00 PlessyvsFerguson <notifications@github.com>:

**Comment by PlessyvsFerguson** [comment]
Oof
thanks for the quick answer. I feel stupid

**Comment by Raycoms** [comment]
No problem, we're currently building a system which will allow the players
to discover this easier.

2018-08-09 9:40 GMT-03:00 PlessyvsFerguson <notifications@github.com>:
