### ISSUE TITLE
Incompatibility with LucraftCore-1.12.2-2.2.x

### ISSUE THREAD

**Issue by cjser** [ldtteam/minecolonies#2766]
Game crash when try to make village with LucraftCore-1.12.2-2.2.x active. Works better with previous version but it crashes sometimes

**Comment by Nightenom** [comment]
Please attach your logs and next time try to use the issue pattern

**Comment by WenXin20** [comment]
Hi, I had the same thing happen, or at least something similar, after creating a new world. Here is the log and version numbers:

Forge v14.23.4.2747-1.12.2
Minecolonies v0.9.86-ALPHA
Lucraftcore v2.2.5
[Latest.log](https://gist.github.com/WenXin20/5977d10e71a1593414f62a9ebeee5ce4) (_See line 984_)

Steps to reproduce:
1. Create a new world.
2. Wait for it to try to load in the world.

**Comment by Asherslab** [comment]
we can't do anything about this, this is a LucraftCore issue as it's a coremod and is the one in the wrong. Sorry, Please take it to them. Thanks!
