### ISSUE TITLE
You have no permission to do this

### ISSUE THREAD

**Issue by protanium** [ldtteam/minecolonies#2767]
The version is 1.12.2 
I get into the game with minecolonies mod and play for hours then turn off the Minecraft launcher. The second time i get into Minecolonies mod, i cannot do anything due to an error that keeps saying ''You have no permission to do this in this colony''. I checked out to see if there are the same issues here and saw a few. Someone named Raycoms wrote some commands to get the problem solved and it seemed it worked but not for me so, i'm opening this again.

**Comment by Nightenom** [comment]
If it's a singleplayer world, did you already tried `/mc colony ownerchange colony: {ID} player: {playerName}` ?

**Comment by Raycoms** [comment]
Which version are you using?

2018-08-11 18:02 GMT-03:00 Nightenom <notifications@github.com>:

**Comment by protanium** [comment]
What @Nightenom told me to do did work. Thank you so much.
