### ISSUE TITLE
Dark Oak Builder's Hut upgrade bug

### ISSUE THREAD

**Issue by HandsomeKiddo** [ldtteam/minecolonies#2768]
### Minecolonies version

I'm not sure. I'm playing on the All the Mods 3 modpack

### Expected behavior

- When using the Dark Oak (not medieval) building, I upgraded the Builder's Hut from level 3 to 4, I expected him to just replace what blocks needed changed or added.

### Actual behaviour

- When you upgrade it from level 3 to 4, the builder has to destroy the entire tree (minus a wall) in order to upgrade it, so he has to rebuild it from scratch, if my observations are correct, then this is because the tree stump of the building is in a different position, so the builder has to destroy everything above it, which is the entire building.

### Steps to reproduce the problem

1. Upgrade the Builder's hut from level 3 to 4
2. Watch what the builder does
3. ...
4. Cry

**Comment by H3roDude** [comment]
I will take a look, thanks for reporting...
As for ATM3, update minecolonies to the latest alpha version to prevent new behaivour

**Comment by Nightenom** [comment]
@HandsomeKiddo  Since it's ATM modpack please update to the latest version, if your issue will still persist feel free to reopen
