### ISSUE TITLE
Lumber Jack doesn't have a second page to filter which trees to chop/plant

### ISSUE THREAD

**Issue by demfels** [ldtteam/minecolonies#2769]
### Minecolonies version

version 1.12.2-0.9.86

### Expected behavior

- On the sawmill you click on the second page and can toggle which sapplings/trees to cut/plant.  

### Actual behaviour

- Second page is blank and the lumber jack just chops down everything he can find (seems to have evil pleasure when chopping down my silverwood trees - hehe).

See picture: https://drive.google.com/file/d/1m2tTSLN7zOk1cwOlwFbhstv1R5uazsGJ/view?usp=sharing

**Comment by Raycoms** [comment]
![screenshot_2018-08-11_20-44-52](https://user-images.githubusercontent.com/6438347/43997044-75a98784-9da7-11e8-8ca0-f2957b451e41.png)

Working fine for me strangely.

**Comment by Raycoms** [comment]
Can you try the 87? it's weird, since it works for me, in my videos as well

**Comment by Wissi** [comment]
@demfels you can also prevent trees from being chopped down by putting a cobbletone block under the tree instead of dirt. That will prevent the tree from being taken down.

**Comment by Wissi** [comment]
Using same version on the Official Modpack and all is good on Pg. 2 even recognizes the Tinkers and Botania trees fine.

![trees](https://user-images.githubusercontent.com/23312242/43997753-4232e6c0-9dd4-11e8-82dc-aba3ca4c35ba.png)

**Comment by demfels** [comment]
Just a side note on this in case anyone else has the issue.  I updated to 87 and still had the issue.  I also updated forge to 2749, still no luck.  I then created a single player issue with the same modpack and confirmed the issue was not happening in single player.  I then downloaded my server world to single player and the issue was not happening in single player, even with the same world folder.  I still am unable to get it to work properly on my server, but at this point, I am assuming it is something related to my server since the same world doesn't have the issue in single player.

@Wissi Thank you for the workaround, much appreciated.

**Comment by Raycoms** [comment]
Does a new lumberjack have this same problem?

**Comment by demfels** [comment]
I destroyed the sawmill on the server game where I was having the issue.  Then crafted a whole new sawmill and this resolved the issue.  It actually seemed to be tied to the sawmill block itself, because I did break and replace that same sawmill and the issue persisted.  Wierd1? Thanks!

**Comment by demfels** [comment]
Oh, but just a side note... It doesn't seem to support silverwood trees from Thaumcraft, maybe an enhancement request?
