### ISSUE TITLE
problem deleting colonies

### ISSUE THREAD

**Issue by redherrin123** [ldtteam/minecolonies#2775]
### Minecolonies version

version 1.12.2-0.8.7934

### Expected behavior

Clicking delete after typing /mc colony delete colony: 1 deletes the colony

### Actual behaviour

Doesn't delete colony and creates error: /mineColonies colony delete <colony: colony-id> [canDestroy:boolean] [confirmDelete:boolean]: missing required parameter colony

### Steps to reproduce the problem

1. type /mc colony delete colony: 1
2. a message appears saying: Click [DELETE] to confirm the deletion of colony: 1
                                             [DELETE]
3. Click the bottom DELETE button
4. colony is not deleted and error message appears

**Comment by Nightenom** [comment]
Really weird since we didn't touch the command system a while (afaik), it usually takes some time to delete a colony after pressing the delete button. Can you confirm that the colony still exists via `/mc colonies list` ?

**Comment by Raycoms** [comment]
Please update your version, you are 1000 versions behind.
