### ISSUE TITLE
Add automatic reporting to any event

### ISSUE THREAD

**Issue by Nightenom** [ldtteam/minecolonies#2777]
To gather as many as possible errors/exceptions from our mod, we might consider adding some automatic report system (using `try{} catch(e){}`), which will send a crashlog/stacktrace to our server. The server will check for duplication and will display a "hall of fame" with the number of occurrences

It could also show a warning to a player that something went wrong, configurable to a window or a chat message

**Comment by Raycoms** [comment]
I think openeye is good enough since that exists already.
