### ISSUE TITLE
Build tool again

### ISSUE THREAD

**Issue by arepsz** [ldtteam/minecolonies#2780]
[crash-2018-08-12_12.55.37-client.txt](https://github.com/ldtteam/minecolonies/files/2281130/crash-2018-08-12_12.55.37-client.txt)
### Minecolonies version

version 1.10.2-0.8.4063 in Sprout, wich is 1.10.2

### Expected behavior

- Can place buildings with build tool

### Actual behaviour

- Game Crashes when I want to place buildings with build t ool, and I can't install 1.12 because Sprout is 1.10, so I have to use 1.10

### Steps to reproduce the problem

1. Sprout
2. Click with build tool
3. The 3 grey bars are empty, and when I click on the green tick the game crashes

The Crash log is still the same.

**Comment by Raycoms** [comment]
okay, yeah the grey bars being empty is the problem, the crash happens
because they are empty. But your 1.10 version is super old as well, can you
update this?

2018-08-12 13:58 GMT-03:00 arepsz <notifications@github.com>:

**Comment by arepsz** [comment]
I know it is super old, but i've never seen a bug like this on any forums, and I don't know why is this a thing. Like, i can't update the version because Sprout needs the 1.10, and the creators didn't update the modpack since January 2017.

**Comment by Raycoms** [comment]
But can't you just update the minecolonies version?

2018-08-12 14:09 GMT-03:00 arepsz <notifications@github.com>:

**Comment by Raycoms** [comment]
to the latest 1.10

2018-08-12 14:09 GMT-03:00 Ray Neiheiser <ray.neiheiser@gmail.com>:

**Comment by arepsz** [comment]
I will check

**Comment by arepsz** [comment]
It still has the same problems

**Comment by Raycoms** [comment]
can you send me the whole log?

2018-08-12 14:44 GMT-03:00 arepsz <notifications@github.com>:

**Comment by arepsz** [comment]
[crash-2018-08-12_12.55.37-client.txt](https://github.com/ldtteam/minecolonies/files/2281214/crash-2018-08-12_12.55.37-client.txt)
this is the only crash log that i have since i tried to reinstall the modpack

**Comment by arepsz** [comment]
[crash-2018-08-13_11.03.33-client.txt](https://github.com/ldtteam/minecolonies/files/2282429/crash-2018-08-13_11.03.33-client.txt)

**Comment by Raycoms** [comment]
This crashlog shouldn't be the latest 1.10, I checked in the latest 1.10 and it should not crash there
