### ISSUE TITLE
Can't loade world

### ISSUE THREAD

**Issue by Wetz1990** [ldtteam/minecolonies#2782]
### Minecolonies version

Twitch launcher: MineColonies Official. Version: v 4.38
minecolonies-1.12.2-0.9.82-ALPHA-universal.jar

### Expected behavior

- after pressing my world to load it, it was expected to load and be playable

### Actual behaviour

- After selecting my world and pretting enter, it starts to load but then comes up with a catch screen telling me a mod, Minecolonies, is responsible for my crash.
It gave me the following link: https://paste.dimdev.org/exajohejol.mccrash

### Steps to reproduce the problem

1. run game from Twitch launcher
2. click single player
3. select world to enter
4. crash

**Comment by marchermans** [comment]
Please try to reproduce this with only Minecolonies. Something seems to be modifying the EntityAI Tasks.

**Comment by Wetz1990** [comment]
I can load it on its own. However, the world have been playable for several hours already, and out of nowhere it starts to crash on loading

**Comment by Raycoms** [comment]
Yeah, it's weird, but while it's a minecolonies villager that is crashing,
it's not minecolonies causing it. There must be some mod which in parallel
accesses the entities while the minecolonies villagers tick.

2018-08-13 15:32 GMT-03:00 Wetz1990 <notifications@github.com>:

**Comment by Wetz1990** [comment]
So i updated just the minecolonies mod from the Twitch launcher, and i was able to load the world again. I am now using version 1.12.2-0.9.8-Beta-universal.

**Comment by marchermans** [comment]
Well that is weird. @Raycoms did we add new ai tasks? Like for the eating or guards?

**Comment by Raycoms** [comment]
Not recently, not yet.

2018-08-13 16:03 GMT-03:00 Marc Hermans <notifications@github.com>:

**Comment by eproces** [comment]
Similar to #2773 ?

I am having a similar problem. Happened first when another player on my LAN world right clicked on his builder, but that might have been unrelated since it seems to be an issue with my miner.
When I tried to reboot the world in singleplayer, it just crashes immediately after loading.
This world has many hours of playtime with no problems.
I'm going to try updating to beta version for now.

Crash report
https://paste.ee/p/ZJpCf

**Comment by Raycoms** [comment]
Are you on a very old version? This bug has been fixed already eproces

2018-08-15 22:00 GMT-03:00 eproces <notifications@github.com>:

**Comment by eproces** [comment]
Um.. I have the version you have on Curse after clicking the link on your website.. 
1.12.2-0.9.1-RELEASE

Edit: I see you have many versions past release. I'm trying beta 0.9.8 next. Maybe there should be a new release version with bugfixes?

**Comment by Raycoms** [comment]
Yeah, gotta release a new release, please try the newest beta.

2018-08-15 22:18 GMT-03:00 eproces <notifications@github.com>:
