### ISSUE TITLE
Ground Level when using Ghost Build Viewer

### ISSUE THREAD

**Issue by SalsAmorim** [ldtteam/minecolonies#2783]
Minecolonies Version: Every one after this!

I would like to give an idea. When using the Ghost Build Viewer we could see the Coordinate of the Y axis (of the ground of the building) on the screen.

This would be useful when trying to build a leveled city when the ground is still not leveled or even place a building with part of it inside a mountain.

I edited some pictures to give you guys an idea.

![screenshot y63](https://user-images.githubusercontent.com/42359092/44059554-b02994a0-9f49-11e8-86d7-45c9e5dfd267.jpg)
![screenshot y64](https://user-images.githubusercontent.com/42359092/44059555-b0596fcc-9f49-11e8-9b89-beffda499b5c.jpg)
![screenshot y65](https://user-images.githubusercontent.com/42359092/44059556-b0880ecc-9f49-11e8-8d0d-c833c5a47fdc.jpg)
![screenshot y66](https://user-images.githubusercontent.com/42359092/44059557-b0b407a2-9f49-11e8-84a7-89f9a7da7e4d.jpg)

Thanks

**Comment by Raycoms** [comment]
We could display just some red text as well to show that there is more of the building underground.
(Building partially underground)

Or do you really want the y level?

**Comment by SalsAmorim** [comment]
Using the Y coordinate just help when you're comparing different buildings. If you already have a chest placed, then you can put the other building even buried because you know they'll be leveled with each other.

**Comment by SalsAmorim** [comment]
Another way I was thinking is something like a ruler in the squematics corners. That way you could also see how many blocks are below your feet. Now you see what's the best for you and the mod. Also this ruler way is not that invasive.

**Comment by Nightenom** [comment]
The Y level will be hard to say as the hut block is not always on the floor (i.e. is in the floor etc.), also the lowest Y block that will be placed is different for each schematic. Maybe we can add a parameter to the schematics.nbt telling the system what is the ground level there. Would you be satisfied with what Raycoms suggested (showing red lines around of the underground part)?

**Comment by SalsAmorim** [comment]
Thanks guys! Any visual aid is helpful. Those red lines would work wonders. If you can see them then the building will be too high. Perfect!

**Comment by Raycoms** [comment]
Closed in favor of joint issue.
