### ISSUE TITLE
why is the sandstone town hall so gimungously huge compared to the rest?

### ISSUE THREAD

**Issue by Too-DAMN-Much** [ldtteam/minecolonies#2784]
i guess deserts needed nerfing for some reason?

that really sucks it has to be close to 3 or 4 times larger than the oak wooden one and absolutely no reason for the wasted space either that i saw while it was being constructed.

it just has a bunch of useless buildings that come along with it, no clue why.

**Comment by OrionDevelopment** [comment]
This is not a bug or an issue. Post the question on our forums or the discord.

**Comment by Too-DAMN-Much** [comment]
so the blueprint is intended to be that vastly wasteful of the amount of time a player has to spend flattening an area before they can build it? i mean if you intend it to be a gimped building compared to the rest then so be it, i won't be making the sandstone townhall mistake again, that's for sure.

**Comment by OrionDevelopment** [comment]
Well I am not the one who made the blueprint. Given that the builder clears out the grounds for you, it is indeed a bit resource heavy. Make a post for it on discord or the forums, the person who generated that blueprint is probably still there and can help you.
