### ISSUE TITLE
FPS drops and Potential Crash caught

### ISSUE THREAD

**Issue by Lordbaane** [ldtteam/minecolonies#2785]
#minecolonies-1.12.2-0.9.89-ALPHA-universal.jar

1. Back rolled to 9.88 still happened
When outside the colony FPS goes back up and no problems, returned to colony and it crashes the game.

https://paste.dimdev.org/ovugohuqiy.mccrash

**Comment by marchermans** [comment]
Reset the rs of your colony

**Comment by Lordbaane** [comment]
That worked. What causes the issue? Just for curiosity.

**Comment by Raycoms** [comment]
Your request system had too many tasks in it, which caused it to overflow.
(There was a bug a while ago which probably caused this)

2018-08-14 12:28 GMT-03:00 Kevin <notifications@github.com>:
