### ISSUE TITLE
Wegfindung Problem extrem

### ISSUE THREAD

**Issue by saufmalwas** [ldtteam/minecolonies#2786]
### Minecolonies version

version minecolonies-1.12.2-0.9.8-BETA-universal

### Expected behavior

- ich habe meine bau abeiter gesagt das er gebeute bauen soll 
  alle items da und auch Werkzeuge  und er leuft los aber komd nich am gebeude an leuft absulut sin freie Wege so daser das gebeute nicht bauen kann  anzumerken ist das ich in einer selbs angepasten kate spielen mit max Einstellungen  das heist extrem file abründe und so baue aktuel auf höhe 200 und die gebeude stehen oft am abrund aber immer 3 Blöcke zum rand platz trotzdem mach er mist 
hänge bilder an  
mandchmal schafe ich es im alle wege abzuschneiden und er abeitet dan aber das klap eher selten gerade wen die gebeude unterirdisch stehen

**Comment by marchermans** [comment]
In English please.

**Comment by saufmalwas** [comment]
I have told my building abeiter that he should build raid
all items there and also tools and he starts to go but komd not s.bueude on absulut sin free ways so that the raid can not build is noted that I play in a self-adapted kate play with max settings that is extremely file abründe and so build aktuel at the height of 200 and the building are often on the bottom of it but always 3 blocks to the edge of the square anyway he makes a mess
attach pictures
sometimes I sheep it in the way to cut off and he abducted dan but that rarely clap just who the building is underground
