### ISSUE TITLE
suggestion - Miner improvment

### ISSUE THREAD

**Issue by shivachirr** [ldtteam/minecolonies#2787]
a few things i think would be a good idea for the miner.

1 as the miner placed levels. it placed signs with the number. so that way we dont have to count the levels going up and down the ladder to find out what level to start mining. like 10 is a perfect level for getting a lot of ores only on that z level. 

2. as the miner built the tunnels maybe have it place in something a way like always place torches on the left wall. because the mine tunnels quickly become mazes even with journey map running

**Comment by Nightenom** [comment]
The first can be done (probably) easily.
The second I don't know - I got a big miner in a test world (to see if he works correctly) and he has now 600 nodes at the deepest level. Using xaero's map it's readable.

**Comment by Raycoms** [comment]
You can follow the torches on the way out already
