### ISSUE TITLE
Suggestion - town ledger item 

### ISSUE THREAD

**Issue by shivachirr** [ldtteam/minecolonies#2788]
i was thinking of a item that could be added called the town ledger. its a mobile version of the town hall interface. i would suggest adding maybe a range limit. i mean its not electronic maybe only works in town. and i would suggest some configs so you can turn on or off the range limit. and weather or not you can change settings in it. i know you can see a lot of the stuff in it by commands. but this could be an easier way.

**Comment by Nightenom** [comment]
Maybe we can make some kind of counselor (advisor or what's the correct word for that) that would have a post in the townhall, then you will have a page you suggest as a ledger in the new guidebook (released soon after the new wiki) with a button "send to the townhall" which will call the counselor to you, he will pick up a "scroll" with the message and once he will arrive back to the townhall block your settings will get applied
As you suggested it will be available only in your colony and since there is a worker - he will not work in rain as others

**Comment by shivachirr** [comment]
> Maybe we can make some kind of counselor (advisor or what's the correct word for that) that would have a post in the townhall, then you will have a page you suggest as a ledger in the new guidebook (released soon after the new wiki) with a button "send to the townhall" which will call the counselor to you, he will pick up a "scroll" with the message and once he will arrive back to the townhall block your settings will get applied
As you suggested it will be available only in your colony and since there is a worker - he will not work in rain as others 

> 

sounds a bit overly complicated compared to what i was thinking but i guess it could work

**Comment by ghost** [comment]
It seems easier to just have the Deliveryman perform this function. The Ledger would call the Deliveryman to you, and send him to the Town Hall before resuming his normal deliveries. That way we don't need a whole new Job or Citizen to perform the task. Then we just extend the Town Hall functionality to read and execute requests from information from the ledger item we can save to the Item.

Although if we did implement it in this fashion, I would say we should rename the Deliveryman to be called the Courier to be more descriptive.

**Comment by AndrewTru** [comment]
@SwivelDiscourse 
That's one way to do it. I think if you re-work the DM to be a rank-class.
The idea being that the D-man is built with his/her work place and then you get a message saying something along the lines of Class not found/workshop unassigned. you can tell the DM to be a warehouse tech or a town hall mail courier. the idea is just the two tasks are controlled by the player that way you don't stop the item flow for a rule change and the same for the other way around.
I can  understand if you like to not make a new job overall but this will allow the player to stay with the limits but still have this in play.

**Comment by ghost** [comment]
Ah, I see. I forgot about the IoC design we use, assigning a job to a citizen is assigning them to the process dictated by the building, that actually answers a lot of questions I had. I'm still unfamiliar with the overall project structure and hierarchy.

Well in that case, it would just make more sense to create the Courier as a Town Hall Assigned Job, although I can't help but feel it's something of a waste of an entire Citizen to do honestly very little. They're basically idle until you call for them. Maybe have Courier double as a following Guard as well, so he at least can follow you around and help?

If it were me, I'd just have the town ledger create a Carrier Pigeon item/animation that uses the Eye of Ender Stronghold throwing animation. Bird flies up to the sky, in the direction of the town hall, disappears from sight, and then the ledger request gets delivered to the Town Hall. That way it still feels immersive.

**Comment by Raycoms** [comment]
I agree with the eye of ender idea. Could also be included in the recipe of this item.

**Comment by ghost** [comment]
It'd be a lot easier to code as well. Just have the Ledger access the Town Hall Gui that it's linked to, then delay the execution of any command sent through the Ledger until the Bird Animation finished.

**Comment by Raycoms** [comment]
I'd even say delaying the execution is not necessary.

>

**Comment by Nightenom** [comment]
Yeah, I thought of this problem a week after I wrote the initial comment, the result was that a new job is not necessary, not sure about the delay - but a restriction to colony border is a must. Whatever this is waiting for two oncoming PRs...

**Comment by Raycoms** [comment]
Closed in favor of joint issue.
