### ISSUE TITLE
Entity miner (Lucy L. Audeley) generating java.lang.NullPointerException

### ISSUE THREAD

**Issue by KrafT-2004** [ldtteam/minecolonies#2790]
### Minecolonies version

1.12.2-0.9.1-RELEASE

### Expected behavior

- Game crashes  when it tries to take the miner home to sleep at night in a house that is being upgraded.

### Actual behaviour

- Game Crashes whit"java.lang.NullPointerException"

### Steps to reproduce the problem

Simply load the saved game.

Attached the crash log:
[Minecolonies error.pdf](https://github.com/ldtteam/minecolonies/files/2291751/Minecolonies.error.pdf)

**Comment by KrafT-2004** [comment]
Solved by deleting miner entity using MCEdit.

**Comment by Raycoms** [comment]
Also fixed in the newest alpha and beta

2018-08-15 18:25 GMT-03:00 KrafT-2004 <notifications@github.com>:
