### ISSUE TITLE
Suggestion - Lumberjack Improvements

### ISSUE THREAD

**Issue by shivachirr** [ldtteam/minecolonies#2791]
here is a few things i suggest be added to the lumberjack

1. this one is more of general all job suggestion. it basically a button to suspend a job like to stop the lumberjack from going out and chopping wood. or the miner from mining and etc.

3. the lumberjack works a tree field works similarly to the field for the farmers and allows you to control what it cuts down to an area so he dose not cut down a whole forest you wanted to keep for looks in the town.

**Comment by Raycoms** [comment]
Hey, 1) You can actually fire him without a problem if you want to suspend
him
2) You can select on page 2 of his GUI which trees he should cut.
3) You can put cobblestone under trees if you don't want them to be cut,
but we could add an option to select an area as well.

2018-08-15 21:29 GMT-03:00 shivachirr <notifications@github.com>:

**Comment by Nightenom** [comment]
1\) yeah, but who wants to remember where this and that worker was, maybe we can add a `AI_PAUSE` state (plus button) in which a worker will act like unemployed (i.e. it will not spam something missing messages etc.) but it will not affect the happiness, something like _having a vacation_

**Comment by BonaireDreams** [comment]
Also with the new happiness system if you fire the worker, you get constant spam telling you he wants a job. So a pause for all the buildings would be a great enhancement.

**Comment by Nightenom** [comment]
Today or tomorrow implementation

**Comment by taylor-scafe** [comment]
Was this finished in #2828 and should it be closed?

**Comment by shivachirr** [comment]
well the pause button was inplemented but tree fields as far as i know has not been that i suggested

**Comment by Raycoms** [comment]
Closed in favor of: https://github.com/ldtteam/minecolonies/issues/3010
