### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by AndrewTru** [ldtteam/minecolonies#2794]
I was thinking, what if there is a sky factory/sky block setting for the mod.
yes there are miners without jobs at this point, but the idea is to have a setting that
converts the mod into a sky block mod.
Yes you can make the colony in any bio you like but I don't think a sky block bio is on that list.
Here are a few things that will change.
1. Colonist are not walking around but if they are they look for any air blocks or any areas they can fall down from.
2. Re-think how the miner/lumberjack will work to get blocks
3. Having the Builders tool understand there is no starter block to right-click.
4. how the mod may have to auto-path the buildings together.
I can understand if sky block integration is not a big idea at the moment but the mod packs I seen tend to stay on the ground.

**Comment by Nightenom** [comment]
I think we got skycolonies modpack and server for that. Is it what you are searching for, isn't it?

**Comment by AndrewTru** [comment]
true but the idea still is useful
number 1 big time, I played the pack your talking about a long time ago and had to expand it with a block border and hand built paths after a lot of my colonist started falling to there deaths.
the idea is mostly ways to add a self-preservation skill to the colonist that why if potential_damage <= max{
find another route.}
I can understand if you just like to code a if(air_space == 1){ jump} command
but if you do that then you have to give the colonist a way to say when they are coming up to said air block.

**Comment by Nightenom** [comment]
I think we use Minecraft pathfinding system (not 100% sure about that). Did you try the latest version depending on what's your long time about
edit: and it's always good to have fences on skyblock to prevent server lags from killing you

**Comment by AndrewTru** [comment]
just downloaded it, today
I forget when I last played it.
good point on the fences but I was using stone blocks to do it.
ya, minecraft path finding is somewhat a stage 1 VI at best
let me know when you confirm that.
