### ISSUE TITLE
Exception in server tick loop crash

### ISSUE THREAD

**Issue by ogpw** [ldtteam/minecolonies#2795]
### Minecolonies version

version 1.12.2-0.9.8-BETA-universal

### Expected behavior

- Place Town Hall (or other buildings)
- NPCs spawn
- Game continues as normal

### Actual behaviour

- Place Town Hall (or other buildings - I have only placed the builder's hut as well so far)
- Wait a few moments (no more than a minute/half a minutes passes)
- Game crashes

### Steps to reproduce the problem

1. Place Town Hall
2. Request to build town hall
3. Wait (patience, young padawan)
4. Game crashes with following crash log:

[MinecraftCrashLog16_08_18.txt](https://github.com/ldtteam/minecolonies/files/2295175/MinecraftCrashLog16_08_18.txt)

I did check other issues similar to this but no other crash logs look like this one (this log is consistent with all the crashes from this issue)

**Comment by Raycoms** [comment]
Please upgrade to the latest alpha or beta for the fix for this.

Am Do., 16. Aug. 2018 um 17:42 Uhr schrieb Oscar <notifications@github.com>:
