### ISSUE TITLE
Changing mining level crashes game

### ISSUE THREAD

**Issue by ADevilChicken** [ldtteam/minecolonies#2796]
### Minecolonies version

version 1.12.2-0.9.27-ALPHA-universal

### Expected behavior

- Change mining level on mine in order to be able to mine materials
- Miner moves up to selected level
- MIner continues mining at normal pace

### Actual behaviour

- Successful change of mining level
- Minger moves to selected level
- Game crashes 5 minutes later

### Steps to reproduce the problem

1. Have a level 3 mine
2. Set the level for the miner to mine at level 4
3. Wait
4. Crash?

Looking at the crash report it seems to be the miner is taking damage and it is not registering?
I would appreciate the help, as I would not like to lose the progress I have made over the past week.
Code: https://paste.dimdev.org/esinuturoh.mccrash - This is the crash report it fed me when it crashed.

Thanks!

**Comment by Nightenom** [comment]
Already fixed, update to the latest alpha version
