### ISSUE TITLE
Citizen - Happiness - /Bug fix

### ISSUE THREAD

**Issue by bob0bob** [ldtteam/minecolonies#2799]
On the citizen windows,  there is now a "next" and "previous" button on the gui.  This will allow you to toggle between the main view and the happiness view.

The Happiness view allows you to view the different modifiers that affect that citizens happiness.   Each value has a color to it.  
"RED" means has a negative affect on their happiness
"YELLOW" means that it has no affect on their happiness
"GREEN" means it has a positive affect on their happiness

Also, BUG.   The no fields modifier was not checking to make sure they are a "FARMER" and was applying it to every citizen.  That is why most citizen couldn't get above a value of 6.0

This window shows all modifiers and some of the modifiers will not apply to that citizen.  Those values will be always "YELLOW" meaning no affect.

Having everything "YELLOW" will get you a value of 8.  to get higher you need some in green.

**Comment by Nightenom** [comment]
If they have no effect on a certain citizen, wouldn't it be better to make it grey?

**Comment by bob0bob** [comment]
Yes.   But there is no way to know which modifier applies to the citizen.   Right now only a couple of citizen gets the NO TOOL modifier.  and if I put a check in the gui for this job or that job.  Mean each future job where a tool is required and we added the modifier.  the programmer would have to remember.   I thought about it and the coding to make it automatic doesn't appear to out way the fact the "yellow" indicator has no effect on the citizen.  You only need to watch for "RED"

**Comment by Nightenom** [comment]
There is a bunch of ways to know it - e.g. add a list of inactive happiness effects to each worker (then hide them in the GUI, as Raycoms suggested)

**Comment by Raycoms** [comment]
We could have a helper method in the abstract job class which does take
care of the checking of this. (static method)

Am Sa., 18. Aug. 2018 um 13:18 Uhr schrieb bob0bob <notifications@github.com
