### ISSUE TITLE
Builders have difficulties when building the dark oak treehouse schematic

### ISSUE THREAD

**Issue by terrapin47** [ldtteam/minecolonies#2804]
### Minecolonies version

minecolonies-1.12.2-0.9.95-ALPHA-universal

### Expected behavior

- The builder does not need manual assistance in order to build the dark oak treehouse schematics.

### Actual behaviour

- The builder cannot reach the main building block since it is in the air, and needs a staircase built for him to reach it.  However, if you build a staircase where the tree or the floor is supposed to go, the builder will deconstruct it as it is in the way of the build.  This makes completing this build quite an annoyance, as you have to build part of the floor using the correct materials, and then have a staircase outside of the build leading onto it.

### Steps to reproduce the problem

1. Build the builder hut, dark oak tree schematic
2. Watch the builder clear out the area and then fail to continue because he can't reach the builder's hut block.

**Comment by Enverex** [comment]
This only seems to happen specifically when building the Dark Oak builders hut. The builder seems to build the rest of the Dark Oak buildings fine without being able to reach the main construction block.

**Comment by lunadragnstar** [comment]
Works fine now

**Comment by EterniaLogic** [comment]
they just kept on sitting below the builder's hut stand, had to build a staircase for them every single time to get them to work at all.

**Comment by ravenbuilder934** [comment]
Instead of commenting on a two-year-old issue, it's recommended to join our [discord](https://discord.minecolonies.com) for support or create a new issue.
