### ISSUE TITLE
Herders not maintaining animal population

### ISSUE THREAD

**Issue by BonaireDreams** [ldtteam/minecolonies#2805]
### Minecolonies version

curse 0.9.8-BETA

### Expected behavior

Herders kill animals

### Actual behaviour

Herders breed animals but dont kill them

### Steps to reproduce the problem

1. Both my Sheep herder and cowboy are not maintaining their animal population. The sheep herder seems worse than the cowboy.
I have tried firing and re-hiring both of them. Upon rehire the sheep herder did kill a few sheep and then stopped again.

![screenshot 116](https://user-images.githubusercontent.com/5133282/44322144-cb25af80-a400-11e8-83b3-57172420e842.jpg)

**Comment by angelnc1989** [comment]
I can confirm this. It mainly happens with pigs in my experience.

**Comment by BonaireDreams** [comment]
Ya the pigs are especially bad. I killed about 30 pigs in the pig herders pen yesterday, 15 cows and 15 sheep. That got all pens back to 4 animals each.

**Comment by Raycoms** [comment]
This is because of Quark, we didn't find out why yet

**Comment by angelnc1989** [comment]
Maybe because Quark adds those random animal textures?

**Comment by Raycoms** [comment]
It seems to change the animals as well somehow

Am Di., 28. Aug. 2018 um 09:36 Uhr schrieb angelnc1989 <
notifications@github.com>:
