### ISSUE TITLE
Dman stuck with full inventory

### ISSUE THREAD

**Issue by BonaireDreams** [ldtteam/minecolonies#2806]
### Minecolonies version

curse 0.9.8-BETA

### Expected behavior

DMAN delivers things and functions as normal.

### Actual behaviour

DMAN stuck in warehouse with full inventory

### Steps to reproduce the problem

Took a bit time off this summer and just started on our world again. Last 3 times I've logged in and gone into the colony the DMAN is standing in the warehouse with a full inventory.  The items he has on him are from the warehouse, not from huts. If I fire him and re-hire him, he will go drop it all back at the warehouse. He then resumes functioning, but not normal.  I waited for over 20 minutes while a builder was requesting grey carpet (said delivering from warehouse), and the farmer was complaining the entire time that his inventory was full and could not unload. During those 20 minutes the DMAN went to just about every other building in the colony, including non-operational ones with empty inventories. He also goes to the barracks and spends far longer than at any other hut looking into the empty inventory there.
His stats all seem fine.

At Barracks
![screenshot 115](https://user-images.githubusercontent.com/5133282/44322399-e6dd8580-a401-11e8-8c37-edcd8053ef61.jpg)

In warehouse, before rehire
![screenshot 111](https://user-images.githubusercontent.com/5133282/44322409-ee9d2a00-a401-11e8-9871-45c1416de269.jpg)
![screenshot 112](https://user-images.githubusercontent.com/5133282/44322418-f6f56500-a401-11e8-885a-b2ac8516ce03.jpg)
![screenshot 113](https://user-images.githubusercontent.com/5133282/44322419-f957bf00-a401-11e8-9041-2a930bfe0c2a.jpg)
![screenshot 114](https://user-images.githubusercontent.com/5133282/44322423-fbba1900-a401-11e8-978e-eca7605f6e98.jpg)

**Comment by Nightenom** [comment]
Try updating to the latest beta, this should be already fixed

**Comment by Nightenom** [comment]
Try updating to the latest alpha, this should be already fixed

**Comment by BonaireDreams** [comment]
Sorry I should have checked through the latest versions and read the patch notes. Will update tonight!
