### ISSUE TITLE
"Creative resolve" on the Request System.

### ISSUE THREAD

**Issue by Thetawaves666** [ldtteam/minecolonies#2808]
### Minecolonies version

version minecolonies-1.12.2-0.9.9-BETA-universal 

### Expected behavior

- Barracks (Birch) gets stuck mid-building for lack of Terracota.

### Actual behaviour

- Barracks ACTUALLY got terracota, somehow.

###

This is more of a "How do the Creative Resolve work" than any other thing. I was upgrading my Birch Barraks to lvl 4 and i DO know that i didnt had any Terracota. And i mean really: There is no Mesa biome close, never saw terracota until that moment on my map and there was no terracota stored. The only way i guess the System could had made terracota is:
1. Take the clay i had on a random chest (was making bricks with it, btw).
2. Make Clays Blocks with it.
3. Burning it to make Terracota.
4. Dye it with the correct color.

But it seems too complicated for the system to make it on a "Creative Way". So i am asking, was that possibly? The RS did it or it was a bug or something? It wasnt a couple btw, the rs made like 80 dyed terracota or more.

**Comment by Raycoms** [comment]
Do you have creative resolve on in the config file?

Am Mo., 20. Aug. 2018 um 15:33 Uhr schrieb Thetawaves666 <
notifications@github.com>:

**Comment by Thetawaves666** [comment]
I activated it on the mod menu. Didn't do any more.

**Comment by Raycoms** [comment]
Because if you turned this on, this means it creates this blocks out of
thin air.

Am Mo., 20. Aug. 2018 um 16:10 Uhr schrieb Thetawaves666 <
notifications@github.com>:

**Comment by Thetawaves666** [comment]
Do you mean this? It didnt explicitly say it create blocks. I thought it made the builders/dman make some mental gymnastic to create whatever the Request System need.

![captura111](https://user-images.githubusercontent.com/37487971/44425900-92521b80-a563-11e8-8797-732bc82fc51c.PNG)

**Comment by Raycoms** [comment]
Yes this makes the dman make gymnastics in the form of block creation out of thin air =D
