### ISSUE TITLE
Serverlag/Can't keep up messages after update

### ISSUE THREAD

**Issue by ItsmeAga** [ldtteam/minecolonies#2811]
### Minecolonies version

minecolonies-1.12.2-0.9.98-ALPHA-universal.jar

### Actual behaviour

After updating from 9.92 to 9.98 I'm experiencing lag on my local server. Just got one colony which didnt change though and was running lagfree before. It seems to be doing a lot of stuff on worldtick. Not sure if the colony data somehow got corrupted through playing through all the versions or if this is normal/expected behaviour, including some profiler screenshots and the colony data below.

![savenbt](https://user-images.githubusercontent.com/21989452/44429120-b1b66c00-a596-11e8-968a-5b15baa8ecd5.PNG)

![entitycitizen](https://user-images.githubusercontent.com/21989452/44429630-5a190000-a598-11e8-9e59-d55f2e7ebc63.PNG)
![threadpathfinder](https://user-images.githubusercontent.com/21989452/44429640-61d8a480-a598-11e8-934e-a696881a433f.PNG)

After killing all villagers it looked like this: 
![deadvillagers](https://user-images.githubusercontent.com/21989452/44429663-79b02880-a598-11e8-8637-be6cade58d76.PNG)

latest colony backup file:
[colonies-2018-08-21_21.54.16.zip](https://github.com/ldtteam/minecolonies/files/2308099/colonies-2018-08-21_21.54.16.zip)

**Comment by ItsmeAga** [comment]
For some reason my backup doubled in size on 21.08 after updating(from 17 to 43 kb), reverted to a backup from before and it is now working again. But had to rebuild the miner after cause it kept throwing issue when a villager tried to do the mining job.  
Not sure what caused the colony's backup size to double but there probably was some faulty data in, added the working backup below so comparing those two might show an issue.

[colonies-2018-08-20_09.25.12.zip](https://github.com/ldtteam/minecolonies/files/2311910/colonies-2018-08-20_09.25.12.zip)

**Comment by Raycoms** [comment]
That's quite weird, let's keep watching this and if it happens again please send us your world.
