### ISSUE TITLE
Builder running around construction site

### ISSUE THREAD

**Issue by Rosomah** [ldtteam/minecolonies#2813]
### Minecolonies version

minecolonies-1.12.2-0.9.10-BETA-universal.jar

### Expected behavior

- Builder should place blocks.

### Actual behaviour

- Builder stops placing blocks, particularly the roof of the medieval spruce town hall level 1 building.
He cleared the area and started placing the blocks, but stopped when he got to the upper part of the roof, my guess is he can't reach it? He then starts running around the construction site without placing any more blocks. I tried rehiring the builder and making him a staircase to the roof, but even when he was up there, he was just running on the roof until he found his way back down the stairs.

### Steps to reproduce the problem

1. Order the builder to build level 1 medieval spruce town hall.
2. Watch him go crazy lol.

**Comment by Nightenom** [comment]
Hello, wait for minecolonies-1.12.2-0.9.101-ALPHA to get published and try it

**Comment by Rosomah** [comment]
After trying this new version, everyone's happiness dropped to 1 and I no longer get the message about finishing and starting a construction.
