### ISSUE TITLE
Building tool not working right.

### ISSUE THREAD

**Issue by Steampunkmama** [ldtteam/minecolonies#2814]
### Minecolonies version
minecolonies-1.12.2-0.9.10-BETA-universal.jar
minecolonies-1.12.2-0.9.101-ALPHA-universal.jar
minecolonies-1.12.2-0.9.102-ALPHA-universal.jar
### Expected behavior
When using the building tool I should see a ghost of the type of building I want to build and and pick where and what type of build.

### Actual behaviour
When I use the building tool with the blocking that I want to build  it will show what I wan in the pull down tabs but I don't get any ghost of the building . I try to use the arrows and plus signs to try to move it around to see if it shows up but nothing happens.. The only way for me to build a building is to place the block itself on to the grounds.  I have tried in new worlds to see if it would but same thing.. Uninstall the mod and reinstalled but nothing works.

**Comment by marchermans** [comment]
Are you using optifine?

**Comment by someaddons** [comment]
try without shaders

**Comment by Steampunkmama** [comment]
I don't use shaders

**Comment by Steampunkmama** [comment]
Yes I use optifine... I even went and removed all mods and the same thing happened.

**Comment by marchermans** [comment]
Remove optifine. Optifine messes with the shaders used to render and makes simply not work. Some people see a distorted view, others see nothing, entirely depends on what version of Optifine you are using.

Most people do not really need optifine for normal gameplay, so please to test just disable it for now.
