### ISSUE TITLE
Smelter ignores gold and iron ore

### ISSUE THREAD

**Issue by Pickselated** [ldtteam/minecolonies#2817]
### Minecolonies version

version 1.12.2-0.9.102-ALPHA

### Expected behavior

- Smelter smelts gold and iron ore

### Actual behaviour

- Smelter requests smeltable ore and doesn't work despite having iron and gold ore in his inventory. Delivery man will also not deliver iron ore gold ore to the smelter.

### Steps to reproduce the problem

1. Take away all non gold and iron ore
2. Put iron or gold ore in his inventory
3. Watch him do nothing

Link to my world: https://drive.google.com/open?id=1BQlyW_R4-WXnxoYnq6yr3xmBESh1n7j8

**Comment by Raycoms** [comment]
Should be fixed
