### ISSUE TITLE
No Requests on Clipboard after Registering

### ISSUE THREAD

**Issue by shammon5** [ldtteam/minecolonies#2818]
### Minecolonies version

version 1.12.2-0.91-RELEASE

### Expected behavior

After registering the clipboard to my colony, it will show me requests for items from different buildings (i.e. builder needs 4 spruce fences, etc)

### Actual behaviour

After registering the clipboard to my colony, upon opening the clipboard, nothing shows under "open requests" despite my builder needing spruce fences (waiting at builder hut, no fences in warehouse or on the way via delivery man)

### Steps to reproduce the problem

1. Register clipboard with town hall via shift-right click (chat message appears: Registered to colony 1)
2. Right clip with clipboard in hand
3. See "Open Requests" at top of clipboard, but nothing listed underneath
4. Manually check builder, see active request in builder's U.I.
5. Become confused by clipboard :\

**Comment by marchermans** [comment]
The clipboard is not an instant overview. It only shows requests that FINALLY have been assigned to you, while the Request System is still hoping for a citizen to maybe find some fences it will eventually however assign it to you. Just takes some time.
