### ISSUE TITLE
Citizen don't take food from the Restaurant

### ISSUE THREAD

**Issue by angelnc1989** [ldtteam/minecolonies#2823]
### Minecolonies version

curse 0.9.2-RELEASE

### Expected behavior

- Hungry workers go to the Restaurant and take food that is stored there to eat. 

### Actual behaviour

- Hungry workers go to the Restaurant and stand around the actual Restaurant block.
- If you give them food manually they eat it and leave the Restaurant.

### Steps to reproduce the problem

1. Build a Restaurant
2. Supply it with food.
3. Wait until workers are hungry.
4. ...
5. No Profit, cause all the workers chill out in the Restaurant without eating.

![2018-08-27_17 59 17](https://user-images.githubusercontent.com/5382585/44670463-050b3d00-aa23-11e8-893e-255ee4006631.png)
![2018-08-27_17 59 26](https://user-images.githubusercontent.com/5382585/44670487-105e6880-aa23-11e8-9a0a-be4040807203.png)

**Comment by Raycoms** [comment]
You have to hire a cook, he is responsible for giving food to the workers

Am Mo., 27. Aug. 2018 um 13:00 Uhr schrieb angelnc1989 <
notifications@github.com>:

**Comment by angelnc1989** [comment]
I had a cook all the time.
But now I looked at her and realized she had an open request for fuel. (Which hasn't been fullfilled by a Deliveryman for hours despite tons of fuel in the Warehouse)
After I gave her some coal she gave out food. Is it intended that the cook doesn't give out food when there is no fuel?

**Comment by Raycoms** [comment]
Sometimes the request system bugs, we're fixing this atm.
