### ISSUE TITLE
Too many citizens

### ISSUE THREAD

**Issue by Rosomah** [ldtteam/minecolonies#2824]
### Minecolonies version

minecolonies-1.12.2-0.9.2-RELEASE-universal.jar 

### Expected behavior

- A new citizen should appear after building a new house (or upgrading it) or after building a barrackstower.

### Actual behaviour

- I have 2 citizens which spawned after upgrading the town hall to lvl 2. One of them may have arrived after I built the barracks, but I'm not sure.
The problem is that the citizens are asking for a house to sleep in, but if I upgrade a house or build a new one, new people keep coming.

### Steps to reproduce the problem

1. Try building the barracks.
2. Try upgrading the Town hall.

**Comment by Raycoms** [comment]
The barracks are housing citizens as well, always make sure you employ all guards you can at the barracks.

**Comment by Wetz1990** [comment]
I think the problem here is that the townhall also spawns villages but does not allow the villagers to be assigned to it as a house.
I have the the same problem, and i do not have any barrack.

**Comment by Nightenom** [comment]
You really should build barracks just for defending purposes, but it also solves this issue

**Comment by Raycoms** [comment]
The townhall has them assigned automatically, citizens living in the
townhall shouldn't complain about housing

Am Di., 28. Aug. 2018 um 09:34 Uhr schrieb Nightenom <
notifications@github.com>:

**Comment by Wetz1990** [comment]
it could be the problem that i have then assigned the villager who was spawned by  the townhall to another hut, therefor leaving the spot in the townhall unused.

There is no manual way of assigning villagers to the townhall?

**Comment by Raycoms** [comment]
Ah, no, not yet, but if you turn on automatic assignment mode they should
be assigned quickly to it. I will adapt this soon so you can change it
within the townhall.

Am Di., 28. Aug. 2018 um 09:37 Uhr schrieb Wetz1990 <
notifications@github.com>:
