### ISSUE TITLE
Smelter ignores iron and gold ore

### ISSUE THREAD

**Issue by Pickselated** [ldtteam/minecolonies#2826]
### Minecolonies version

version 1.12.2-0.9.109-ALPHA

### Expected behavior

- Smelter smelts gold and iron ore

### Actual behaviour

- Smelter requests smeltable ore and doesn't work despite having iron and gold ore in his inventory. Delivery man will also not deliver iron ore gold ore to the smelter.

### Steps to reproduce the problem

1. Take away all non gold and iron ore
2. Put iron or gold ore in his inventory
3. Watch him do nothing

This was **not** fixed with the recent update

Link to my world: https://drive.google.com/open?id=1BQlyW_R4-WXnxoYnq6yr3xmBESh1n7j8

**Comment by Raycoms** [comment]
I tested this a lot and he should be doing things, if he is not doing anything there must be something else wrong, do you have any additional mods? Coremods? Are there enough furnaces in the hut?

**Comment by Pickselated** [comment]
I do have additional mods, I'm playing with the World of Dragons modpack, I'll talk to other people playing the pack to see if they get a similar issue. There are three furnaces in his hut and he smelts other ores fine, so I'm assuming that part isn't an issue. I imagine it would be pretty difficult to figure out what the issue is if it's caused by one of the many mods in the pack I'm playing :/

**Comment by Raycoms** [comment]
It's weird if he smelts all other ores.

Am Do., 30. Aug. 2018 um 10:35 Uhr schrieb Pickselated <
notifications@github.com>:

**Comment by Pickselated** [comment]
It's very weird. He even smelts mod ores, just not iron and gold.

> It's weird if he smelts all other ores.

**Comment by Pickselated** [comment]
It turns out that the smelter was intentionally disabled from smelting those two ores in order to prevent a duping bug in the pack. I'm so sorry for wasting your time on this.

**Comment by Quest79** [comment]
This is still an issue. I had to hand deliver him the gold ore for him to do anything. I reset him. Reset the world. Reset the couriers. Nothing. Is this still disabled? If so remove it from the smelt-able list to people dont waste time trying to get it to work.

**Comment by Talyda** [comment]
> This is still an issue. I had to hand deliver him the gold ore for him to do anything. I reset him. Reset the world. Reset the couriers. Nothing. Is this still disabled? If so remove it from the smelt-able list to people dont waste time trying to get it to work.

Maybe if you are having an issue with a thing, make a new issue for it. This issue is 6 years old.
