### ISSUE TITLE
Scan Command does not seem to function

### ISSUE THREAD

**Issue by Megistus** [ldtteam/minecolonies#2832]
### Minecolonies version

minecolonies-1.12.2-0.9.2-RELEASE-universal

### Expected behavior

input: '/mc scan 457 63 -1843 465 79 -1856 Citizen1' into command line and a scan of object like with scan wand and scanned nbt file ends up in new folder

### Actual behaviour

returns error message: 'missing required parameter x1'

Unless I am missing something crucial, and may googlefoo has seemed to fail me as to any alternative to the command syntax which if I am understanding the code correctly should work ...

**Comment by PoroUsedSnax** [comment]
The syntax is the following:
`/mc scan [player: online player] <x1: x coord> <y1: y coord> <z1: z coord> <x2: x coord> <y2: y coord> <z2: z coord> [name: name]`
and needs to be entered in the same way, so in your case it would be:
`/mc scan x1: 457 y1: 63 z1: -1843 x2: 465 y2: 79 z2: -1856 name: Citizen1`
The commands were built to work with tab completion, so this is easier to use working with that

**Comment by marchermans** [comment]
Validated and checked the command works. Closing

**Comment by Megistus** [comment]
Great! Might I suggest that this makes its way into the Wiki? 

Thanks for explaining it.

**Comment by Nightenom** [comment]
I suggest making the tab completion work as other mods/minecraft do
