### ISSUE TITLE
can not place camp (minecolonies-1.12.2-0.9.2-RELEASE-universal)

### ISSUE THREAD

**Issue by Ioandar** [ldtteam/minecolonies#2833]
### Minecolonies version

minecolonies-1.12.2-0.9.2-RELEASE-universal

### Expected behavior

- Spawn camp

### Actual behaviour

- ghost image goes away when hitting green to place it

### Steps to reproduce the problem

1.) have the wand
2.) I have the item (camp block made with chest) in inventory
3.) I hit the wand on dirt of big flat area
4.) I move and turn the ghost image as needed
5.) I klick then green check

-> wait and POOF ghost image gone and nothing happens
-> No fail-info was displayed on screen

I am familiar with mods and use minecraft since years but I have no idea why this is happening. Played with minecolonies before and all was fine. Any help/ideas welcome

<a href="https://ibb.co/h011Hz"><img src="https://thumb.ibb.co/h011Hz/2018_09_01_09_23_22.png" alt="2018_09_01_09_23_22" border="0"></a>
<a href="https://ibb.co/ctbhqK"><img src="https://thumb.ibb.co/ctbhqK/2018_09_01_09_39_51.png" alt="2018_09_01_09_39_51" border="0"></a>
logfile: 
`
[20:54:07] [Server thread/ERROR] [minecolonies]: handleDecoration: Could not build schematics/SupplyCamp
[20:54:19] [main/INFO] [minecolonies]: isCorrectMD5: md5:822656D9221EEE028DDB838708EB4B46 other:822656D9221EEE028DDB838708EB4B46
`
EDIT: added pictures to see it fits perfect with even 1 block free space around it.

**Comment by Ioandar** [comment]
Okay, I found out what I did wrong. 

-> Don't craft and use BUILDING wand to BUILD but use camp block to BUILD camp

I would be easy to mention that in GAME! 1 single page info put into players inventory on start


Welcome to MineColonies Version x.y!

"Craft a supply camp or supply ship block"
"rightklick the ground with THAT BLOCK IN HAND to spawn the ghost image"
"Adjust placement with menu"
"You can use ESCAPE any time to look around"
"resume by rightklick with THAT BLOCK IN HAND again "
"When you are content with placement, hit green check"


-> Maybe don't let people craft a building wand if that has no use (yet)
-> It actually looks like it is working when in fact it is not and only misleading people!

IMHO this is a major flaw in design and should be fixed ASAP

**Comment by Raycoms** [comment]
I think blocking the buildTool crafting before having the supplycamp/ship
makes sense.

Am Sa., 1. Sep. 2018 um 17:26 Uhr schrieb Ioandar <notifications@github.com

**Comment by Ioandar** [comment]
ye, it might help noobies like me not fall in that pit...

**Comment by someaddons** [comment]
it kinda sucks positioning the supply cam without though

**Comment by Ioandar** [comment]
> it kinda sucks positioning the supply cam without though

The cam works without using the buildtool, but the buildtool can not place the camp or ship!

But yes, if the buildtool could actually place the supply camp it would be indeed better

**Comment by Ioandar** [comment]
wrong button klick :)

**Comment by Nightenom** [comment]
More like add ability to place camps as decorations, the info will be added through advancements and a guidebook "soon" (I would say up to two months)

**Comment by Ioandar** [comment]
Okay, you have it in the pipe then. I will close this down now

Thank you for your great work! So much fun!

**Comment by Mr-Wallet** [comment]
Just downloaded MineColonies on Twitch yesterday and this gave me a hell of a time! Very glad to find this issue.
