### ISSUE TITLE
Reset button in Worker GUI

### ISSUE THREAD

**Issue by kedamono** [ldtteam/minecolonies#2834]
### Minecolonies version

version 1.12.2-0.9.11-BETA

### Expected behavior

- A worker encounters an item or set of circumstances that makes them request an item only usable at a higher level Worker Hut block. To be able to clear the item or circumstances and reset the Worker to a previous state and not lose any levels they've acquired.
For example: A Hut Level 1 Miner encounters Wub-Wub ore in the course of mining. They request a diamond pickaxe and a higher level hut. I manually clear the Wub-Wub ore and reset the Miner.

### Actual behaviour

- The Worker encounters the item or circumstances and despite me clearing them, the worker still requests the higher level hut, despite firing and hiring them repeatedly.

### Steps to reproduce the problem

1. Create a Level 1 Miners Hut and hire a worker.
2. In creative mode, place a block of obsidian in the mine shaft floor.
3. Worker will encounter it and cannot mine it. Worker requests a diamond pickaxe and the appropriate level hut to use it in.
4. Fire and Hire the worker.
5. The Worker still requests the pickaxe.

**Comment by Nightenom** [comment]
There is an issue for miner and currently unmineable ores
But I'm also for this - make a window with tools for reseting/repairing a worker or whole colony, without a need to use commands

**Comment by kedamono** [comment]
That's why I made this a general statement instead of specific statement. Sometimes a worker gets into a state that they don't do anything. Being able to reset them to a previous working state would be great.

**Comment by Nightenom** [comment]
@kedamono Restart and pause state was added, the pause state is working, restart needs to be adjusted for each worker correctly (now it's only printing fancy messages and clear any open request - similar to rs reset but only for one worker)
