### ISSUE TITLE
Building Digging Hole not building

### ISSUE THREAD

**Issue by minimuscle** [ldtteam/minecolonies#2835]
### Minecolonies version

version 1.12.2-0.9.1

### Expected behavior

- Build barracks based on the schematic that is set there. 

### Actual behaviour

- Digs hole the size of the barracks and keeps digging down, well below the schematic ground

### Steps to reproduce the problem

1. Select 'Medieval Oak' barracks schematic 
2. Set task
3. Builder digs instead of builds

**Comment by Raycoms** [comment]
Please upgrade to a newer version, should be fixed already

**Comment by minimuscle** [comment]
Still isn't fixed. im on 0.9.2 release now. same issue.

**Comment by Raycoms** [comment]
Can you try the latest alpha?

**Comment by Raycoms** [comment]
Else I will reopen and investigate it
