### ISSUE TITLE
Citizens not using restaurant

### ISSUE THREAD

**Issue by Rosomah** [ldtteam/minecolonies#2836]
### Minecolonies version

minecolonies-1.12.2-0.9.2-RELEASE-universal.jar

### Expected behavior

When hunger drops to a certain level where they would get negative happiness they should go grab a bite.

### Actual behaviour

My builder is at 2 points in hunger and he still doesn't go to eat. He does eat if I give the food into his inventory, but what is the point of the restaurant then.

**Comment by marchermans** [comment]
Do you have a cook? Is he requesting something?

**Comment by Raycoms** [comment]
At the moment he only goes to the restaurant when he completely runs out,
in the future he will go more regularly.

Am Sa., 1. Sep. 2018 um 11:38 Uhr schrieb Marc Hermans <
notifications@github.com>:

**Comment by Rosomah** [comment]
> Do you have a cook? Is he requesting something?

Yeah, I have a cook, no he's not requesting anything.

> At the moment he only goes to the restaurant when he completely runs out, in the future he will go more regularly.

Ah, I see, thanks.
