### ISSUE TITLE
 I can only place decorations with the builders tool/wand?

### ISSUE THREAD

**Issue by RoseWolfNThorn** [ldtteam/minecolonies#2839]
minecolonies-1.12.2-0.9.2-release
minecraft 1.12.2
I can only place decorations with the builders tool/wand? but in videos I see other wise, am I missing something, is there something to disable/enable? I can't find anything in the config that seams relevant? thought you could preview buildings you put down manually to.

expected behaviour:
to be able to build the town with the building tool/wand

actual behaviour:
can only build decorations?

**Comment by PoroUsedSnax** [comment]
You need to have the relevant hut in your inventory to be able to preview it, doesn't work for buildings placed manually

**Comment by RoseWolfNThorn** [comment]
thank you, I could not find that out for the life of me
