### ISSUE TITLE
Crash - Clicking Rename Colony Crashes Game  SP Hosted LAN

### ISSUE THREAD

**Issue by MokahTGS** [ldtteam/minecolonies#2842]
SP Hosted LAN, two other LAN players
Forge: 2758
minecolonies-1.12.2-0.9.109-ALPHA-universal.jar

Full Mod List: https://pastebin.com/FBQLJfRx

Pressing the rename colony button in the Town Hall GUI crashes the game.

Crash Log: https://paste.dimdev.org/rapuvucaxe.mccrash

**Comment by Nightenom** [comment]
Fixed #2841 wait for curseforge and grab the latest alpha then
