### ISSUE TITLE
Some Guards work and others just stand beside their chest and do nothing!

### ISSUE THREAD

**Issue by Ioandar** [ldtteam/minecolonies#2847]
### Minecolonies version

minecolonies-1.12.2-0.9.2-RELEASE-universal

### Expected behavior

nothing too fancy for a soldier :)
- go stay on your post
- attack if see hostile

### Actual behaviour

- Guards stands beside chest doing nothing
-> not moving to their assigned place
-> they ignore all hostiles

My guards request armor (in chat and menu) but they never take it 
-> put them in their inventory
-> in their tower chest 
-> warehouse rack
nothing worked

<a href="https://ibb.co/bwfeaK"><img src="https://thumb.ibb.co/bwfeaK/2018_09_03_20_48_13.png" alt="2018_09_03_20_48_13" border="0"></a>

### Steps to reproduce the problem

no idea, sorry

I have small colony with 4 guardtowers

2 move to their assigned place (set with menu) and attack hostiles
2. Just stand and do nothing. They do not move if ordered or attack any hostiles

Is there a way to fire a guard without killing him?

**Comment by Raycoms** [comment]
Hmm, do they have saturation?

>

**Comment by Ioandar** [comment]
oh, I will check... no food - no fight! :) brb

I DO have food in warehouse and the deliveryman is running around doing his thing.

okay, checked. here are the pic... Seems okay to me... Has 2 tasty bread for rations :)

<a href="https://ibb.co/haBfhz"><img src="https://preview.ibb.co/bB6D2z/2018_09_03_21_31_28.png" alt="2018_09_03_21_31_28" border="0"></a>

<a href="https://ibb.co/jR6oKe"><img src="https://preview.ibb.co/cyZxCz/2018_09_03_21_31_35.png" alt="2018_09_03_21_31_35" border="0"></a>

**Comment by Rosomah** [comment]
Check if the armor level is not too high for the guard. Try leather armor, I think all are able to use leather. For iron armor, you need a guard level 5 and guard tower needs to be at lvl 4 i think, not sure though.

**Comment by Ioandar** [comment]
will check, but I am pretty sure they say "from level wood/gold to max iron...."

Jupp, Iron is include. I will try leather and try to move the guard-tower and see if that revives him...

<a href="https://ibb.co/b8kjcz"><img src="https://preview.ibb.co/gP6CVK/2018_09_04_13_38_49.png" alt="2018_09_04_13_38_49" border="0"></a>

<a href="https://ibb.co/haBfhz"><img src="https://preview.ibb.co/bB6D2z/2018_09_03_21_31_28.png" alt="2018_09_03_21_31_28" border="0"></a>

<a href="https://ibb.co/fvbJ4e"><img src="https://preview.ibb.co/dEJnxz/2018_09_04_13_38_25.png" alt="2018_09_04_13_38_25" border="0"></a>

<a href="https://ibb.co/bt5Zcz"><img src="https://preview.ibb.co/mAObqK/2018_09_04_13_38_41.png" alt="2018_09_04_13_38_41" border="0"></a>

**Comment by Raycoms** [comment]
If you turn them to patrolling automatically, does it work?

**Comment by Rosomah** [comment]
Yes, they say iron even if they can't use it, at least that's how it is for me (I think that in older versions it was only dependent on tower level not on guard level, plus the level requirements were different, that's why he requests iron).

**Comment by Ioandar** [comment]
ah, I see... 

I dropped the numb guard a leather helmet...
-> He picks it up but does not use it
<a href="https://ibb.co/eyoUcz"><img src="https://preview.ibb.co/fspD4e/2018_09_04_13_49_58.png" alt="2018_09_04_13_49_58" border="0"></a>

I dropped the woking guard a leather helmet to his feet
-> he picks it up
-> he walks back to his chest
-> he wears it
-> he walks back to his post
-> perfect!!!

I will change patrol on numb guard and report...
-> No change. He remains numb and does not move. 
-> well, he moved a tiny little bit when I switch but he does not patrol
[pic of setting is coming, I have to wait for next free hosting upload :)]

Is there a way to move or dismantel a building or to fire a guard without killing him)?

**Comment by Rosomah** [comment]
Click on "Hire worker" and if someone is already hired, you have the option to fire him. Fire and then re-hire him, see if that works.

**Comment by Ioandar** [comment]
> If you turn them to patrolling automatically, does it work?

I had to be more patient. After a while on "automatic patrol". 
-> He started to move
-> get his leather armor delivered
-> wears it
-> goes on patrol

After that I could set him to his guard post and it worked as intended! YAY!  TYVM!

**Comment by Ioandar** [comment]
> Click on "Hire worker" and if someone is already hired, you have the option to fire him. Fire and then re-hire him, see if that works.

I will try that on the other 'stuck' guard. 
Else I will do the "automatic Patrol" trick
babariens beware! :)

**Comment by Ioandar** [comment]
After I freed the one Guard from being stuck, the other got unstuck as well...
Maybe first guard blocked the second guard from being updated?
Well, for me now all is working as intended. I will close this

Thanks for all your work on this great and fun mod!
