### ISSUE TITLE
Worker instructions reset on server reboot

### ISSUE THREAD

**Issue by Zbrigaider** [ldtteam/minecolonies#2851]
**Minecolonies version**

version 1.12.2-0.8.9646

**Expected behaviour**

preferences in minecolonies worker buildings like lumberjack etc remember their customised lists of things to do or not do

**Actual behaviour**

when server reboots all lists of instructions reset to default 'on' state, causing trees to be cut or mobs to be attacked that were originally disabled. 

**Steps to reproduce the problem**

restart the server.  every time.  server is shut down using the stop command.

**Comment by Raycoms** [comment]
please upgrade to a newer version.
