### ISSUE TITLE
All colonists disappear and unable to access respective chests

### ISSUE THREAD

**Issue by Sickwan** [ldtteam/minecolonies#2857]
### Minecolonies version

version 1.12.2-0.9.2

### Expected behavior

- I should be able to access colonist chests whether it be to withdraw items from inventories, give tools to workers or upgrade buildings

### Actual behaviour

- Cannot access GUIs for colonist huts; no worker huts,citizen huts or townhall. No information regarding colony is visible in F3 menu and /mc colony info returns 0 colonies. I am also unsure as to how to revert to previous .dat files

### Steps to reproduce the problem

1. Colony was functional (even had a chicken chunks, chunk loader for the colony), entered the nether.
2. Game crashed and returned to overworld to broken colony
[latest.log](https://github.com/ldtteam/minecolonies/files/2358616/latest.log)

3. ...
4. Profit

**Comment by Nightenom** [comment]
Hello, just copy the dat files from backups until you will find a working one

**Comment by Nightenom** [comment]
Btw this log does not contain the crash info

**Comment by Sickwan** [comment]
Ah okay, my bad, in the flurry of eagerness to find a fix i uploaded the wrong log, would the correct one be of use?

Thank you, previous attempts at reverting .dat files didnt reveal any results

**Comment by Raycoms** [comment]
Hi, remove the existing colonies.dat and colony1.dat then take a backup from a time the coloyn was still intact and extract both dats from it. Then restart the server and do recall at the townhall.
