### ISSUE TITLE
buildings won't load

### ISSUE THREAD

**Issue by ghost** [ldtteam/minecolonies#2859]
### Minecolonies version
-1.12.2

version 1.12.2 
- I'm using forge

### Expected behavior

- When I use the building stick its supposed to create a small building or something?

### Actual behavior

- None of the things i place loads
- when I right click any of the chests nothing happens.
- builders aren't able to spawn but it says I need builders to upgrade a structure that isn't even there.

###Notes
- I'm super excited for this mod! It looks great and just what I need and want! I'm sad that its not properly working. I hope This issue is either fixed or can be fixed because I still really want this mod!

**Comment by ghost** [comment]
I use the building stick and the screen to build a structure comes up but no ghost image or any building after i check the green checkmark button

**Comment by someaddons** [comment]
doesnt work with shaders, disable those for it

**Comment by Raycoms** [comment]
Hi, try to watch our series on how to get started with minecolonies to see how things work out:
https://www.youtube.com/watch?v=uICFW9KrUdg&t=10s

In general, if you use shaders most likely the previews won't work.
The first step is to craft a "builders hut" and then right click with the build tool to display and position it.
