### ISSUE TITLE
Medival Spruce Miner4 Build Error

### ISSUE THREAD

**Issue by JakeOTwitch** [ldtteam/minecolonies#2861]
### Minecolonies version

version X.X.XXXX or curse 0.9.2

### Actual behaviour

- Medival Spruce Miner4 build has been built with a giant rectangular hole in the back measuring 6 back, 17 wide and 8 deep.

**Comment by someaddons** [comment]
same with birch

**Comment by carlansor** [comment]
can you please post a screenshot?

**Comment by JakeOTwitch** [comment]
![2018-09-09_09 50 31](https://user-images.githubusercontent.com/30060800/45265232-dc694700-b415-11e8-8b38-cf109728de54.png)
![2018-09-09_09 50 12](https://user-images.githubusercontent.com/30060800/45265233-dc694700-b415-11e8-9383-c065a2809ac2.png)
![2018-09-09_09 50 24](https://user-images.githubusercontent.com/30060800/45265234-dc694700-b415-11e8-904b-f2d266defc38.png)

**Comment by carlansor** [comment]
Thanks, found the issue. Ill rescan the schematics and send them to the devs to fix the problem!

**Comment by lunadragnstar** [comment]
Fixed
