### ISSUE TITLE
MineColony wand not working

### ISSUE THREAD

**Issue by BrunoSeriese** [ldtteam/minecolonies#2862]
### Minecolonies version

version 1.12.2 or curse 

### Expected behavior

- to be able to use different options when using the building wand

### Actual behaviour

- Wand is only able to display " decorations on the left"  , clicking next or previous does nothing.
![problem colony](https://user-images.githubusercontent.com/43110626/45263991-ff572380-b434-11e8-9f71-2999ea6bb149.png)

### Steps to reproduce the problem

1.  Place a camp
2. place a townhall
3. use the wand
4. Profit

**Comment by MineShadow7** [comment]
You must have hut block in your inventory. Is the problem solved?

**Comment by ZeusXpresss** [comment]
My inventory is cleared and it is still doing it

**Comment by ravenbuilder934** [comment]
You need to have the hut block in your inventory, not have an empty inventory. Also, please don't necro old issues (this one is 3 years old)

**Comment by ZeusXpresss** [comment]
Ohhhhh, I thought he meant you cant have a hut block in your inventory by the way he worded it.  Thank you, also sorry for doing this on a old issue
