### ISSUE TITLE
not all my custom huts are showing 

### ISSUE THREAD

**Issue by Brainslime1** [ldtteam/minecolonies#2863]
### Minecolonies version
1.12.2-0.9.2
### Expected behavior

show all custom huts

### Actual behaviour

only shows some of the huts like the town hall and builders hut but not my guardtower or restaurant

### Steps to reproduce the problem
use scan tool
put files in schematics folder 
put file into style folder

**Comment by Raycoms** [comment]
did you name it correctly?

Am So., 9. Sep. 2018 um 12:17 Uhr schrieb dylan <notifications@github.com>:

**Comment by Brainslime1** [comment]
i named them Baker1 to 5, BarracksTower1,Builder1 to 5 and TownHall1 to 5 

i took the names from the wiki so they should be right

**Comment by Brainslime1** [comment]
i just noticed im using the wrong names

**Comment by Raycoms** [comment]
It should be GuardTower, barracks tower is for barracks

**Comment by Brainslime1** [comment]
thx

**Comment by Nightenom** [comment]
@Brainslime1 are your issues solved?
btw. take the names from repo -> then it should work for sure
https://github.com/ldtteam/minecolonies/tree/version/1.12/src/main/resources/assets/minecolonies/schematics/wooden

**Comment by Brainslime1** [comment]
Yeah its solved i just didnt notice i was using the wrong name for restaurant and guard tower
