### ISSUE TITLE
Inconsistency with use/make indicators on hut pages

### ISSUE THREAD

**Issue by wilsondgonzales** [ldtteam/minecolonies#2868]
### Minecolonies version

minecolonies-1.12.2-0.9.126-ALPHA-universal.jar

### Expected behavior

- Inconsistency with recipe indicators. For example the farmer hut, specifying which fields to use shows an X symbol. Whereas in the baker's hut, the items marked X are actually excluded items to make. There's also an inconsistency with the lumberjack

### Actual behaviour

- If it could be universally be checkmarks for use/ make and Xs for don't use/ make

**Comment by Nightenom** [comment]
With the release of the new version of our GUI library, all of those and others like those will be replaced with checkboxes (simply with better solution)

**Comment by Raycoms** [comment]
fixed
