### ISSUE TITLE
Happiness on citizen death

### ISSUE THREAD

**Issue by Rosomah** [ldtteam/minecolonies#2869]
### Minecolonies version

minecolonies-1.12.2-0.9.126-ALPHA-universal.jar

### Expected behavior

- When a citizen dies by suffocating in a wall (natural causes), the happiness should drop only by 1.

### Actual behaviour

- When a citizen dies of natural causes, the happiness drops to 1.

### Steps to reproduce the problem

Does it not count as natural causes if I'm the one to drop sand on their head, making them suffocate? Or if I put lava on the ground and they burn?

I have 2 guys with skills at lvl 1 and the library isn't doing anything so I'd really like to get rid of them.

**Comment by Nightenom** [comment]
Library is really slow building, it's a way to level up skills of your citizens so it needs to slow.
If you have higher happiness new spawned citizens will have higher skill stats

**Comment by Rosomah** [comment]
Is there a way to kill the citizens without the happiness dropping to 1?

**Comment by bob0bob** [comment]
There is no reason to kill a citizen anymore.

**Comment by Rosomah** [comment]
The library is too slooooooooooow. :D

**Comment by Rosomah** [comment]
I had a citizen in there for 3 days and nothing increased...

**Comment by Raycoms** [comment]
if their happiness is lower than their skills they won't increase

Am Do., 13. Sep. 2018 um 12:27 Uhr schrieb Rosomah <notifications@github.com

**Comment by Rosomah** [comment]
The individual happiness is at 8, so it should increase.
How long does it take and is it possible to choose which skills to increase?

**Comment by bob0bob** [comment]
@Raycoms this doesn't sound like a bug to me.  If anything people are a faster way to get better citizen and I'm not such if that is something that is needed.

**Comment by Rosomah** [comment]
Ok, but what happens if a citizen dies of actual natural causes, like suffocating in a wall or falling of a cliff? That shouldn't drop the happiness to 1 should it?

**Comment by Raycoms** [comment]
The skills and the time is random.

**Comment by Rosomah** [comment]
OK, I get that.
I'll repeat the last question and then I'm done. :)
What happens if a citizen dies of actual natural causes, like suffocating in a wall or falling of a cliff or if a barbarian kills him/her? That shouldn't drop the happiness to 1 should it?

**Comment by bob0bob** [comment]
The death of 1 citizen will not result in your town happiness to level 1.

**Comment by Rosomah** [comment]
I don't know, it's weird... Does it count as natural cause if I put lava on the floor and he burns to death?
It's also strange cause when he dies, the happiness drops to 0, but the next day, the happiness is all the way back to 10 again.

**Comment by bob0bob** [comment]
Death of a citizen will cause the happiness to fall for a period of time.  The amount it falls depends on if they are a guard or not.  It is an accumulative effect for a period of time up to a max.   So you you have 5 citizen die with in 20 MC days then that would explain your low value.   Each citizen matters to the colony and they mourn the loss for a period of time, over time that happiness modifier is reduce until it gets to 0 and then no reduction for happiness towards the colony.

you can see your happiness for the town hall from that last tab, it will have a red/yellow/green indicator what is happening.

**Comment by Rosomah** [comment]
Ah, I see. Thanks for the detailed info. The info on the wiki page is a bit different, that's why I didn't understand what's happening.

Best regards.

**Comment by bob0bob** [comment]
Yes. When the new wiki is release, it will reflect the new happiness.  It was completely rewritten not to long ago.
