### ISSUE TITLE
Composter hut does not adapt to changes on "listofcompostableitems"

### ISSUE THREAD

**Issue by Thetawaves666** [ldtteam/minecolonies#2871]
### Minecolonies version

Version:  minecolonies-1.12.2-0.9.123-ALPHA-universal

### Expected behavior
 
-  Composter hut worker don't get stuck trying to perform an action it can't do.
I modified the list of compostable items, to add and remove some things so my workers know exactly what things i want to get disposed of. As you can see, i removed the "food" entry, as the one corresponding to weath.
When i "manually" use weath on a compost barrel, i cant use it to fill it (as intended). Using dirt will fill the barrel (as intended). When i give the composter worker some dirt for it to use, it will not use it. If i give him weath, will get stuck going to the barrel and her chest. 
As i can see it, seems like there is _no conecction_ with the list of compostable items, and the working of the hut.
To make things a little worst, seems like the "Request System" also don't have a connection, since the Dman too is bringing to the composter hut, more weath (and other things) that can't be composted (with my new setting).
![image](https://user-images.githubusercontent.com/37487971/45517113-8254e280-b783-11e8-82eb-9004c664e2fa.png)

Only tested it with lvl1 hut. But i assume the error will persist.

### Steps to reproduce the problem

1. Change the list of compostable items. Add and remove things.
2. Give to the composter hut, something from the new list, and something removed from it.
3. Observe the results.
4. ... Profit

**Comment by Nightenom** [comment]
After you edit this list you should restart your client. Then use the second page of composter hut to manage what should be composted

**Comment by Thetawaves666** [comment]
I did it before, and and didn't work. 
Also, casually opened my save to play a little and got corrupted. Bye 440 days city.

**Comment by Raycoms** [comment]
There are backups made of the colonies.dat and colony1.dat

Am So., 16. Sep. 2018 um 11:37 Uhr schrieb Thetawaves666 <
notifications@github.com>:

**Comment by Thetawaves666** [comment]
Sorry to mislead the thread, but how do i backup those?
It got corrupted the map AND the village.

**Comment by Raycoms** [comment]
Oh, if your map got corrupted than there is not much to be done. Only the
colony corrupted can be saved.

Am So., 16. Sep. 2018 um 12:05 Uhr schrieb Thetawaves666 <
notifications@github.com>:

**Comment by Thetawaves666** [comment]
How can i save the colony then? I can try to copy-and-paste chunk by chunk with some editor later.

Btw, can i "copy" the colony to a different map, wright?

**Comment by Raycoms** [comment]
As long as the position of the colony and the buildings stays the same yes.
In the world folder in the minecolonies folder you got the colony data and
the colony backups.

Am So., 16. Sep. 2018 um 12:14 Uhr schrieb Thetawaves666 <
notifications@github.com>:

**Comment by Thetawaves666** [comment]
It worked. Closing.
