### ISSUE TITLE
Dark Oak Treehouse Pathfinding Issues

### ISSUE THREAD

**Issue by Enverex** [ldtteam/minecolonies#2873]
### Minecolonies version
Version: 1.12.2-0.9.126-ALPHA

### Expected behavior
Colonists to take (roughly) the straightest or most sane route.

### Actual behaviour
For some reason, colonists insist on climbing up into treehouses, even if it's clearly not the shortest route (they could just walk under them) and often they'll climb up in to one, walk a few steps, change their mind, climb back down the way they came in and then walk around. This obviously adds in a lot of delay over time. Additionally I had a runner/deliveryman get stuck in a loop doing this. They'd climb up, walk a few steps in, go back, climb back down, walk a few steps from the tree (in the correct location) but then for some reason decide to go back, climb back up, etc.

### Steps to reproduce the problem
1. Build a small town with Dark Oak treehouses.
2. Doesn't matter if you link them or not, the behaviour is roughly the same.
3. Watch as the villagers make questionable routing decisions.

Example: They could simply walk under this treehouse, but instead they'll often climb up, sometimes changing their mind half-way across, turn back, etc. They also often seem to go out of their way to go a less direct route, instead veering off to one side to go through another building rather than just going through the clear path infront of them.
![image](https://user-images.githubusercontent.com/958670/45588597-0b4c5500-b90f-11e8-80b2-989fdd08824c.png)

**Comment by Nightenom** [comment]
This is because waypoints are present, they are used to avoid citizens going random way which might not be safe.

**Comment by Raycoms** [comment]
Placing waypoints around the trunk would solve that. But the best would be
having the building connect up there between them, and not via ladders

Am Sa., 15. Sep. 2018 um 13:59 Uhr schrieb Nightenom <
notifications@github.com>:
