### ISSUE TITLE
Respawn of citizen sets skills to 1

### ISSUE THREAD

**Issue by ShaneCourtrille** [ldtteam/minecolonies#2875]
Version: minecolonies-1.12.2-0.9.127-ALPHA-universal.jar

I had most of my citizens disappear (3/4) and trying to recall them didn't work.  When I did a /mc citizen respawn on my builder she came back but all her skills were down to 1.  Is there a way to manually change her skills?

**Comment by Nightenom** [comment]
Nope, you need to get happiness higher to have higher spawn skills

**Comment by Raycoms** [comment]
i just checked and respawning does not reset it. Something else might've happened. We had an update which had that issue a while ago which has been fixed already. To level them up you can employ them in a library.
