### ISSUE TITLE
Townhall range

### ISSUE THREAD

**Issue by D3laz** [ldtteam/minecolonies#2878]
Hi, im sorry but i dont know how toexpend my range in my old colonie.
Can u help me? i try this : /mc colony claim [colony: colony id] [range: number in chunks] [add: true/false]
but the game tell me : colony dont found
Ive only one colony . name 1, id 1
thx
sorry for my poor english

**Comment by Raycoms** [comment]
try /mc colony claim colony: 1 range: therangeyouwantittobe add: true

In the center of the colony.

Am So., 16. Sep. 2018 um 19:34 Uhr schrieb Denaz <notifications@github.com>:
