### ISSUE TITLE
Builder clearing too large area / outside the build area

### ISSUE THREAD

**Issue by MatthiasMann** [ldtteam/minecolonies#2880]
### Minecolonies version
Version: minecolonies-1.12.2-0.9.123-ALPHA-universal.jar

### Expected behavior
Only the area inside the fence of the building should be cleared

### Actual behaviour
The builder clears roughly 2x the width & length of the fenced in area
![2018-09-18_00 45 11](https://user-images.githubusercontent.com/6777029/45654549-61222800-badc-11e8-84a2-f99970c5a586.png)
I have marked the areas the builder has cleared with red "circles".

Previously he also started to dig a huge square hole half way through his builder's hut only to repair it afterwards ...

### Steps to reproduce the problem
1. Place a building (library)
2. Start a build (medieval oak)
3. Watch where the builder clears (may need in even terrain and or trees around).

**Comment by PoroUsedSnax** [comment]
Did you place the building without using the building tool? The tape looks like it's sized for the wooden library, but the Medieval oak one is *much* larger. 

If you placed the building by hand the tape won't update if you change the style, it only places correctly when you choose the style in the building tool

**Comment by MatthiasMann** [comment]
Hmm - interesting - how do I use the building tool with the buildings? I tried that once and it only showed decorations and a mine even so I had a fisher's hut in hand/used it on.

**Comment by PoroUsedSnax** [comment]
You need to have the building hut in your inventory, then select it from the left dropdown

**Comment by MatthiasMann** [comment]
Ahh - that worked - so I can only build houses when I have their "core" in my inventory or one of the decoration buildings which don't have a core - thanks.
