### ISSUE TITLE
All request fields blank

### ISSUE THREAD

**Issue by lJasonl** [ldtteam/minecolonies#2882]
### Minecolonies version

Version: minecolonies-1.12.2-0.9.2-RELEASE-universal.jar

### Expected behavior

-  Builders showing what they need in their GUI. Delivery workers continue to work.

### Actual behaviour

-  I noticed that the delivery workers stopped moving and just stood at the warehouse. I then noticed that the builders request button in their interface is not showing what the worker needs to complete their work.

![2018-09-17_23 15 17](https://user-images.githubusercontent.com/11781138/45662399-ca4f6e80-bacf-11e8-8822-a613bf905396.png)
![2018-09-17_23 15 23](https://user-images.githubusercontent.com/11781138/45662400-ca4f6e80-bacf-11e8-8ee2-fe280e733456.png)
![2018-09-17_23 21 41](https://user-images.githubusercontent.com/11781138/45662597-78f3af00-bad0-11e8-9d30-ab967fed9d9a.png)

### Steps to reproduce the problem

1.  Tried to start a new build (Guard tower)
2. Builder goes to location then back to hut and stands there.
3. Tried to give the correct material to the builder but it does not show what he needs.
4. ... Profit

**Comment by PoroUsedSnax** [comment]
I'd first recommend updating to one of our latest alphas on curse, as the release is quite old at this stage, see if that fixes the issue. If not, then you could try `/mc rs reset colony: <id>`

**Comment by lJasonl** [comment]
I already tried an updated version prior to posting this issue with no luck. With the command...what would the colony id look like?

Update: I figured it out. So I reset the colony and that brought back the requests to be viewable. I had to fire and rehire the dmen but they appear to be working again. Thank you.

**Comment by Raycoms** [comment]
./mc whereami should give you the colony id, if you are in single player
its most likely 1

Am Di., 18. Sep. 2018 um 01:22 Uhr schrieb lJasonl <notifications@github.com
