### ISSUE TITLE
[Suggestion] Barbarian Outpost

### ISSUE THREAD

**Issue by jwmwebdev** [ldtteam/minecolonies#2884]
I was watching someone playing with this mod, and I was thinking there could be a "Barbarian Outpost" that can randomly generate in the world, and defeating this can reduce the frequency of attacks on nearby villages.

This can be either something that generates with the world, or slowly develops in reaction to your village. If it develops, then it can get bigger and stronger barbarians over time.

**Comment by lJasonl** [comment]
I like this idea.

**Comment by Raycoms** [comment]
Closed in favor of joint issue.
