### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by DYproductions** [ldtteam/minecolonies#2889]
My builders usually just stop and do nothing. I'm not sure if it's a bug or it's because they have 1 everything? It's usually after they do some work they just stop.

**Comment by Raycoms** [comment]
Do they stop forever or do they stop for a little bit and then continue
working?

Am Mi., 19. Sep. 2018 um 16:08 Uhr schrieb DYproductions <
notifications@github.com>:

**Comment by DYproductions** [comment]
I'm not sure but it's definitely over 30 minutes. I'll check next time I play

**Comment by DYproductions** [comment]
OK well I guess it was just the world. I created a new world now and the builder is fine? IDK what happened

**Comment by Raycoms** [comment]
If you find a way to reproduce this, please let us know.

Am Do., 20. Sep. 2018 um 23:39 Uhr schrieb DYproductions <
notifications@github.com>:

**Comment by DYproductions** [comment]
Sure thing
