### ISSUE TITLE
Miner issues

### ISSUE THREAD

**Issue by DominikGamer** [ldtteam/minecolonies#2890]
Version: 1.10.2-0.9.7587
minecraft version: sprout modpack, 1.10.2

Miner is supposed to work, but it doesn't do.

So, there's a point where the miner stops mining, at stone pickaxe level it mines completly fine, but when gets to the level when he can use iron pickaxe it stops working.

It requests an iron pickaxe, even tho there are 10 in it's inventory. No matter how many i give to him, or cancel the request, it keeps coming up.

I've tried it with other workers, and same results, rebuilt miner's hut, same results, different world same results. Btw, miners inventory containes these: 64 cobble, 60 torch, 64 oak wood slab, 2x stone shovel, 55x ladder, 64+6x oak fences, 10 iron pickaxe, non of them are used.

Anyone knows why?? It's so annoying, please help me fix this problem.

**Comment by Raycoms** [comment]
Upgrade your miner hut to a higher level, at least level 2.

Am Mi., 19. Sep. 2018 um 16:25 Uhr schrieb DominikGamer <
notifications@github.com>:
