### ISSUE TITLE
Guards dont move 

### ISSUE THREAD

**Issue by cjser** [ldtteam/minecolonies#2891]
### Expected behavior
Guards patrol around the colonie and defend the people and themselves

### Actual behaviour
They get around the control block of the barrack´s towers and the guard tower and do nothing even if I manually set the patrol route.
When barbarians come they dont move and get murderer along the colonist if I dont interfere,

### Steps to reproduce the problem
The manually set patrol route worked in previous versions (I dont remember what number), but when I update some versions ago they stop working. The ones with automatic set patrol route never do anything since I created them (a couple months ago).

**Comment by mojoyup1528** [comment]
Mine cannot climb all the way up the towers :/ I pick a spot up there to guard, and they go up the ladder and get stuck. For you, are you using the guard wand (green color) or using the option to set guard location? If not, they will sit there, so Im not sure if manually is a part of that or not, but maybe so. Just a thought.

**Comment by Raycoms** [comment]
Can you send me your world so I can debug this?

**Comment by mojoyup1528** [comment]
For cjser right? I don't want to thread jack. Just relating is all :P

**Comment by Raycoms** [comment]
Yeah for cjser

**Comment by Raycoms** [comment]
I can't reproduce them not moving at all.

**Comment by Raycoms** [comment]
and @mojoyup1528 where did you set the guard point on the tower? If it is too close to the ladder it might not work because he will stop pathfinding when he gets too close.

**Comment by mojoyup1528** [comment]
Could be the exact problem. It was about 3 blocks distance. Thanks for the info could be it :)
