### ISSUE TITLE
Periodic messages in chat from removed/destroyed building

### ISSUE THREAD

**Issue by MatthiasMann** [ldtteam/minecolonies#2892]
### Minecolonies version
Version: minecolonies-1.12.2-0.9.133-ALPHA-universal

### Expected behavior
After firing the guard and demolishing the guard tower (using a axe to mine the guard tower core block and then the rest of the house using ore excavator / tinker tools) and then hiring the ex-guard as a delivery man there should be no more messages from this guard tower / ex-guard.

### Actual behaviour
There are messages like this in chat:
[CHAT] GuardTower Humphrey O. Golding§r is in need of §fLeggings§r at Dim: 0 94.67.372 .
[CHAT] GuardTower Humphrey O. Golding§r is in need of §fHelmet§r at Dim: 0 94.67.372 .

The job of Humphrey O. Golding is actually displayed as delivery man - and he is doing deliveries to/from the warehouse.

### Steps to reproduce the problem
0. Turn off automatic job assignment
1. Build a watch tower (level 2, medieval oak - if it matters)
2. Have one guard in it, equip him with a sword
3. Fire that guard
4. Mine the guard tower core block
5. Raze the guard tower to the ground (fire, ore excavator, tinker tools, TNT etc)
6. Build a delivery house somewhere else (level 1, medieval oak)
7. Hire the ex-guard as a delivery man
8. Be annoyed at the messages :)

**Comment by Raycoms** [comment]
Yeah, we are going to rework this as soon as our GUI rework done.
for now /mc rs reset colony: yourid should solve this
