### ISSUE TITLE
Enemy barbarians not spawning, colonist acting as if they're there though

### ISSUE THREAD

**Issue by blaster56745** [ldtteam/minecolonies#2896]
### Minecolonies version
4.37

Version: 

### Expected behavior
Barbarians invade after the message is issued

### Steps to reproduce the problem
<!-- What should we do to make this issue show up in our own game? 
   Not sure on how to reproduce this, i spent 2 days off the server, but thats the only thing that comes to mind

**Comment by PoroUsedSnax** [comment]
I presume that is v4.37 of our pack? If so update, that's probably a pretty old version now and this sounds like an old issue, we're up to 4.47

**Comment by blaster56745** [comment]
im running it on a server, was working fine for a few days
do you have a more up to date server version that i havnt been able to locate?

**Comment by PoroUsedSnax** [comment]
Every version of Minecolonies released is universal, it can be used both Client and Server side

Unless you mean the pack, in which case their isn't, but it's simply dropping the configs/mods and such into the server folder to update
