### ISSUE TITLE
Changelog version numbers do not match up

### ISSUE THREAD

**Issue by BonaireDreams** [ldtteam/minecolonies#2898]
Version: N/Z

### Expected behavior
Looks like the version numbers for the changelog on curse are out of sequence.  IE FILE: minecolonies-1.12.2-0.9.11-BETA-universal.jar  changelog states Version: 1.12.2-0.9.7-BETA

This offset carries on up through 0.9.13 showing changelog as 0.9.9

![screenshot 3106](https://user-images.githubusercontent.com/5133282/45841089-9a6dba00-bccd-11e8-9eac-c749e0b94fcc.jpg)

**Comment by marchermans** [comment]
Noted. It is just a mis match in the numbers the actual content matches

**Comment by BonaireDreams** [comment]
Ya I figured as much, just thought I'd mention that the numbers aren't matched up :D
