### ISSUE TITLE
Industrial Foregoing (aka the new Minefactory) machines do not work

### ISSUE THREAD

**Issue by PumaBlack** [ldtteam/minecolonies#2903]
The Industrial Foregoing machines like Planter or Blockplacer do not work within the building range of minecolonies.

Thanks in advynce for taking care of that problem.

Version: 

Minecraft 1.12.2
Forge 14.23.4.2757
industrialforegoing-1.12.2-1.11.2-212.jar
minecolonies-1.12.2-0.9.127-ALPHA-universal.jar

**Comment by Raycoms** [comment]
If you have a townhall built > level 1, you can give these machines permission via the event they cause in the townhall GUI.
You just click add and configure their permissions on the user page then.

**Comment by PumaBlack** [comment]
> 
> 
> If you have a townhall built > level 1, you can give these machines permission via the event they cause in the townhall GUI.
> You just click add and configure their permissions on the user page then.

ultra fast - thanks!

**Comment by Boomflex** [comment]
Sorry to revive really old ones but this is happening in 1.15.2 and no events are showing in the Information tab?

The version is 0.10.757-ALPHA and is the same for 758 and 759 also.
