### ISSUE TITLE
Lucraft incompatibilities

### ISSUE THREAD

**Issue by Kregoras** [ldtteam/minecolonies#2904]
For some reason with Lucraft installed no citizens appeared at townhall creation. After some review, at the moment a citizen should have spawned the game crashes.

### Minecolonies version
Version: 0.9.2 RELEASE

### Expected behavior
- Normal spawn after creation of townhall or new citizen spawn.

### Actual behaviour
- When I first created the townhall citizens should have spawned, but after a couple hours waiting with no luck I reseted the game. Now whenever a citizen should spawn the game crashes. After mods review, Lucraft makes Minecolonies crash.

Crash report:

[crash-2018-09-23_00.39.48-server.txt](https://github.com/ldtteam/minecolonies/files/2430579/crash-2018-09-23_00.39.48-server.txt)

### Steps to reproduce the problem

1. Fresh install of minecraft modded
2. Create a settlement
3. wait till a new citizen should spawn. If you're lucky and it works the game crashes on spawn. Sometimes you can be waiting for hours.

In case this is a Lucraft error and not minecolonies, please let me know so I can contact them :)

Edit: Uploaded the crash as a file instead as a wall of text.

**Comment by Raycoms** [comment]
Please try the newest alpha

**Comment by Kregoras** [comment]
[crash-2018-09-29_12.55.56-server.txt](https://github.com/ldtteam/minecolonies/files/2430564/crash-2018-09-29_12.55.56-server.txt)

Tried with same result. Crash after placing townhall, whenever the first citizen should spawn.

Newest minecolonies-1.12.2-0.9.138-ALPHA-universal

**Comment by Kregoras** [comment]
Tried last alpha as well: minecolonies-1.12.2-0.9.141-ALPHA-universal

Same crash. Each time a citizen spawns, the game crashes.

[crash-2018-10-02_14.24.12-server.txt](https://github.com/ldtteam/minecolonies/files/2439017/crash-2018-10-02_14.24.12-server.txt)

Edit: attach last crash log

**Comment by Raycoms** [comment]
Im on a trip so I can only look into it on sunday, please attach the crash
log of the latest alpha as well.

Am Di., 2. Okt. 2018 um 09:27 Uhr schrieb Kregoras <notifications@github.com
