### ISSUE TITLE
Barbarian Ladder Strange Placement

### ISSUE THREAD

**Issue by shammon5** [ldtteam/minecolonies#2906]
### Minecolonies version

Version: 1.12.2-0.9.9-BETA

### Expected behavior
Barbarians will build ladders to get over my walls and fences

- 

### Actual behaviour
On the day of a barbarian attack, ladders will appear in random locations in my village, for example on the side of the town hall. 

I have a 2 deep trench surrounding my city with fences at the top, making entry into the village impossible for the barbarians. The strange ladders appear in random places around my village far away from where the barbarians are (still) trapped in the trench. If they spawn SE of my village, I'll have a ladder appear in the north somewhere. 

### Steps to reproduce the problem
Wait for barbarian attack
Keep an eye out for mystery ladders

**Comment by sharkck** [comment]
I think this goes in-hand with my post on the invisible/long-distance attacking.  When they spawn, they're attacking me and they're not even at my town yet.  I had to turn the barbarian attacks off b/c it got too ridiculous running around the town/base constantly being attacked out of thin air... I noticed the ladders and blocks everywhere too... I'm next to an ocean biome and there's random ladders and cobblestone all out in the middle of the ocean as well...

**Comment by shammon5** [comment]
Definitely sounds similar, though mine stay in a large group and I don't take any distanced damage or see any invisible attacks on my guards and citizens, just the ladders.

**Comment by someaddons** [comment]
#2905

**Comment by Raycoms** [comment]
Closed in favor of #2905
