### ISSUE TITLE
Upgrading home adds additional beds to NBT

### ISSUE THREAD

**Issue by MatthiasMann** [ldtteam/minecolonies#2907]
### Minecolonies version
Version: minecolonies-1.12.2-0.9.13-BETA-universal

### Expected behavior
A level 5 home should have 5 beds registered

### Actual behaviour
Looking into the colony1.dat with https://irath96.github.io/webNBT/ shows that the building 13 of the attached file has 10 beds.

I was looking at the NBT because I have more citizens than jobs and was checking for duplicate buildings (which I did not find) but I found too many beds.

### Steps to reproduce the problem
Upgrade a home (medieval Oak) which changes the position of it's beds on the different levels

[colony1.dat.zip](https://github.com/ldtteam/minecolonies/files/2408487/colony1.dat.zip)

**Comment by Nightenom** [comment]
Looks like it's registering both halves of beds, sometimes two beds above, etc.

**Comment by MatthiasMann** [comment]
Ohh right - totally forgot that minecraft beds are 2 blocks :/

**Comment by MatthiasMann** [comment]
Wait - this house has no stacked beds - it has single beds or 2 beds side by side.

**Comment by Nightenom** [comment]
Yeah, it's a bug, I dunno why you closed it :D

**Comment by MatthiasMann** [comment]
You mentioned the 2 blocks per bed and I just thought 2x5 == 10 so it must be ok - but then I read the stacked beds part and remembered seeing the stacked coordinates and reopened it.

Probably shouldn't file bug reports before drinking coffee :D

**Comment by Raycoms** [comment]
There is a upper half of the bed and a lower half of the bed. We register
both afaik
