### ISSUE TITLE
Buggy Farmer Request at Night

### ISSUE THREAD

**Issue by Ibrulz** [ldtteam/minecolonies#2908]
### Minecolonies version

Version: 1.12.2-0.9.127-ALPHA

### Expected behavior

-  When colonists go to bed, to only see requests for housing and jobs, etc.

### Actual behaviour

-  When colonists go to sleep, my farmer requests an axe. This was from when I had pumpkins on my farm. I no longer have pumpkins, and I have given the farmer an axe, and get requests show as empty, but this request comes up every night.

### Steps to reproduce the problem

1. Have a farm containing grown pumpkins, then wait till the farmers axe breaks and they request a new one.
2. Change the crop type in the scarecrow, then harvest and break all the pumpkin crops.
3. Now the farmer no longer need an axe, but still requests it. Even if you give them one.
4. ... Profit

**Comment by Raycoms** [comment]
Yeah, I think we got a bunch of issues about these "phantom requests" around here.
We'll soon give the request system a small rework to deal with this.

**Comment by Raycoms** [comment]
./mc rs reset colony: 1 should fix this for now.
