### ISSUE TITLE
Miner going down and up to the first level of the mine

### ISSUE THREAD

**Issue by lebanni** [ldtteam/minecolonies#2909]
### Minecolonies version

Version: minecolonies-1.12.2-0.9.3-RELEASE-universal.jar

### Expected behavior
Miner starts digging toward lower levels of the mine.

### Actual behaviour
Miner going down and up to the first level of the mine.

https://youtu.be/6V24sNTwmJE

### Steps to reproduce the problem
Upgrade mine to level 2 (Medieval Oak mine).

**Comment by Nightenom** [comment]
Hi, might be a monster there, but check his requests/saturation/tools. If it won't help then try fire&hire method.

**Comment by lebanni** [comment]
There was no monster, no requests, no tool missing, tried to fire/hire him, even killed him.

**Comment by lebanni** [comment]
Wiped the world. Made a new one. Was working fine with alpha 0.9.138. Updated to 0.9.139. Issue occured again, this time with mine level 1.

**Comment by Nightenom** [comment]
Ok, can you send us your world?

**Comment by lebanni** [comment]
https://drive.google.com/open?id=12MmYW07c7_2DHxAnDKWEDoJwmOCVJfsE

The world I have uploaded was created before I did this :

I broke the bloc where the miner was going back

![2018-09-30_19 19 05](https://user-images.githubusercontent.com/2799575/46261004-edc1e280-c4ed-11e8-8cf5-7c7a9f028387.png)

Then, the miner went outside the mine and stopped

![2018-09-30_19 19 57](https://user-images.githubusercontent.com/2799575/46261021-22ce3500-c4ee-11e8-9dea-66b281aa3b91.png)

I dug under the miner who fell in the gallery, He, then, started to mine.

**Comment by Raycoms** [comment]
Should be fixed in the newest versions
