### ISSUE TITLE
Knights not patrolling

### ISSUE THREAD

**Issue by alexrr10** [ldtteam/minecolonies#2910]
Knights in barracks don't patrol, they stand in the hiring place

**Comment by Nightenom** [comment]
Hi, try setting their patrol point (the second page of the hut block)

**Comment by alexrr10** [comment]
It doesn't work

**Comment by Raycoms** [comment]
Do they have anything on the request window and are they on patrol?

Am Mo., 24. Sep. 2018 um 14:16 Uhr schrieb alexrr10 <
notifications@github.com>:

**Comment by alexrr10** [comment]
They don't have requests abd they are set on patrol

**Comment by Raycoms** [comment]
And it is automatic patrol as well?

Am Mo., 24. Sep. 2018 um 14:23 Uhr schrieb alexrr10 <
notifications@github.com>:

**Comment by Raycoms** [comment]
What minecolonies version it is?

**Comment by alexrr10** [comment]
The latest

**Comment by Raycoms** [comment]
Can you send us the world?

**Comment by alexrr10** [comment]
It is in a modpack

**Comment by Raycoms** [comment]
As long as the world is not tooo big, it shouldn't be a problem.

Am Mo., 24. Sep. 2018 um 14:27 Uhr schrieb alexrr10 <
notifications@github.com>:

**Comment by Raycoms** [comment]
This is a duplicate of a similar issue. I will close this in favor of the other issue.
