### ISSUE TITLE
Mine won't upgrade from lvl 1 to 2 

### ISSUE THREAD

**Issue by BIGGZBOY** [ldtteam/minecolonies#2912]
### Minecolonies version

Version: minecolonies-1.12.2-0.8.9646 (on All the Mods 3 v5.9.8d)

### Expected behavior

- Make a mine
- Eventually (Or instantly) upgrade to level 2
- Building request received
- Builder begins getting materials/ building

### Actual behaviour

- Make a mine (tried medieval Oak and Spruce as well as Taiga)
- Upgrade it to level 2
- Building request received 
- Builder doesn't get assigned to the request
- No information or request for necessary materials

[latest.log](https://github.com/ldtteam/minecolonies/files/2417045/latest.log) (most of the info related to this issue is at the end) 

### Steps to reproduce the problem

1. Build Mine
2. Upgrade to level 2 
3. ... Profit

**Comment by PoroUsedSnax** [comment]
Firstly, I would highly recommend updating your version of Minecolonies, ATM3 has a super old one and won't update it themselves. 

But this 'issue' sounds like you haven't upgraded the builder to be able to work on the building, your builder needs to be = to or > the level of a building you're trying to upgrade to

**Comment by Raycoms** [comment]
Newest version should fix this.
