### ISSUE TITLE
Crash Report - Ticking Screen

### ISSUE THREAD

**Issue by Tobanyi** [ldtteam/minecolonies#2915]
### Minecolonies version

Version:  1.12.2-09.137-ALPHA

### Expected behavior

Right click on the clipboard, see what my citizens want.
- 

### Actual behaviour

Right click on a stone block with the clipboard, game crashed.
- 

paste bin: https://pastebin.com/AUWqeAyH
### Steps to reproduce the problem

1.  Sync a clipboard to a town hall
2. right click on a stone block
3.  see if you crash
4. ... Profit

**Comment by Raycoms** [comment]
Postponed until the new GUI system is in place.
We will rework this part, fixing this is unfortunately not so easy.
The rework will definitely fix this completely.
