### ISSUE TITLE
upgrading mine and changing design type causes a problem

### ISSUE THREAD

**Issue by kotoroshinoto** [ldtteam/minecolonies#2918]
### Minecolonies version 

Version: 1.12.2-0.9.127-ALPHA

### Expected behavior

- 
since mineshaft location changed, workers should dig in new location.

### Actual behaviour

- 

workers remember original mineshaft location, and keep returning to it and try to dig through the wrong part of the structure

### Steps to reproduce the problem

build a miner hut, allow miner to do some digging for a while, later change it during upgrade to a design that places the mine in a different location. The miner won't know the new location.

**Comment by kotoroshinoto** [comment]
Is there some way to erase the locations of mineshafts so I can get this miner to behave?

**Comment by kotoroshinoto** [comment]
checking the NBT data, the ladder location was not updated when the building schematic was changed.

That is likely the cause of this.

**Comment by kotoroshinoto** [comment]
I could repair it manually, but I've no idea what the ladder location and cobble location are SUPPOSED to be

**Comment by Raycoms** [comment]
ladder location is the furthest down ladder of the shaft, and cobble is the
cobble behind the ladder

Am So., 30. Sep. 2018 um 00:03 Uhr schrieb Michael Gooch <
notifications@github.com>:

**Comment by kotoroshinoto** [comment]
is it supposed to be the block they would sit on in its initial state?
because the height is 64 and my original surface was 70

medieval oak moves it down a ladder a bit like around a corner and such

**Comment by kotoroshinoto** [comment]
like around a corner and such

**Comment by Raycoms** [comment]
it is the height one above the block he should start digging.

Am So., 30. Sep. 2018 um 00:07 Uhr schrieb Michael Gooch <
notifications@github.com>:

**Comment by kotoroshinoto** [comment]
ah i see thanks.

**Comment by kotoroshinoto** [comment]
Weird, I set the blocks as such, and hes digging on the wrong side
![2018-09-29_23 23 17](https://user-images.githubusercontent.com/1337560/46252952-e1328100-c43e-11e8-9087-30d6751735ed.png)
![2018-09-29_23 23 26](https://user-images.githubusercontent.com/1337560/46252953-e55e9e80-c43e-11e8-8c7a-30cd98f58509.png)
![2018-09-29_23 23 32](https://user-images.githubusercontent.com/1337560/46252954-e7286200-c43e-11e8-803c-9f2a23ed4554.png)

2nd and 3rd image are included for the map coords.

if I understood correctly the ladder location should be x -240 z 751 y 64 and the cobble location should be x -239 z 751 y 64. Maybe I did something wrong... but hes digging on the wrong side of the ladder here.

**Comment by kotoroshinoto** [comment]
There are other values. Perhaps I need to set rotation to something other than 0?

or maybe it was shaftlocation

**Comment by Raycoms** [comment]
probably, not sure, its abit late

Am So., 30. Sep. 2018 um 00:33 Uhr schrieb Michael Gooch <
notifications@github.com>:

**Comment by kotoroshinoto** [comment]
is shaftlocation the next block to be broken or is there a special orientation for it?

**Comment by Raycoms** [comment]
shaft location should be the central block in the hole

Am So., 30. Sep. 2018 um 00:39 Uhr schrieb Michael Gooch <
notifications@github.com>:

**Comment by kotoroshinoto** [comment]
For now i'm purging the NBT entry for the mine. Going to rebuild the structure. Hopefully that doesn't corrupt my colony. I'll see if a fresh build gets correct values at the very least. If not i'll report that.

**Comment by kotoroshinoto** [comment]
I figured that any data relevant to the old shaft and explored tunnels would probably screw with the new orientation a bit. Probably best to burn it all down.

Speaking of which,it wouldnt' be a bad idea to have something like that in the UI, to force it to load all the defaults for the hut given its location and the style chosen and forget everything about the structure acquired from the workers working it.

**Comment by Raycoms** [comment]
Yeah, good idea.

Am So., 30. Sep. 2018 um 00:57 Uhr schrieb Michael Gooch <
notifications@github.com>:

**Comment by kotoroshinoto** [comment]
looks like the purge worked.

if someone chooses to upgrade to a schematic that isn't a direct upgrade to an old one, it should probably check for that to prevent this kind of thing.

**Comment by kotoroshinoto** [comment]
Either that or prohibit upgrading to anything that isn't a direct upgrade.

**Comment by Nightenom** [comment]
Easier solution (eventhough it's a bit late now): fire worker, change style, move building so it matches the mining hole, hire worker
_btw if you solved it you can close this issue_
