### ISSUE TITLE
refresh command doesn't accept an ID

### ISSUE THREAD

**Issue by kotoroshinoto** [ldtteam/minecolonies#2919]
### Minecolonies version

Version: 1.12.2-0.9.127-ALPHA

### Expected behavior

- 
Colony to refresh
### Actual behaviour

- 
 Colony not found.

### Steps to reproduce the problem

nothing special, just a command (mc colony refresh 1 tried at console AND as op command in-game)

**Comment by PoroUsedSnax** [comment]
The command has to be inputted as such: `/mc colony refresh colony: <id>`

**Comment by MelficeSilesius** [comment]
Be that as it may, it doesn't work for me either.

`/mc colony refresh colony: 1` produces `Colony not found.`
EDIT: Variations on that produce the same result.
EDIT AGAIN: 1.12.2-0.9.4-RELEASE

**Comment by Raycoms** [comment]
do /mc whereami in the middle of your colony to find out your id.

Am So., 14. Okt. 2018 um 14:32 Uhr schrieb MelficeSilesius <
notifications@github.com>:

**Comment by MelficeSilesius** [comment]
"You're inside colony Silesius with id: 1, the colony center is approx 0.00 blocks away"

And now it works. I am beyond peeved that it now works, AFTER you've responded.
But only after.

Thank you for the response. It seems to have fixed itself.
