### ISSUE TITLE
Builder not accessing chests

### ISSUE THREAD

**Issue by shammon5** [ldtteam/minecolonies#2921]
### Minecolonies version

Version: 1.12.2-0.9.141-ALPHA

### Expected behavior

I place items in the builder's main and secondary chests (level 5 builder) and she takes out the items to use them in her build. 

### Actual behaviour

I put items in the builder's main and secondary chests but she stands at the builder's chest unresponsive until I manually put the item in her inventory. 

I tried emptying her personal inventory completely, only putting items in the main chest, only putting items in the secondary chest, relogging the game, recalling the builder, but nothing helped. 

With her inventory completely empty, she WILL go to the secondary chest and pick up items out of it. But seems to do so randomly because 2 minutes later she's back down the hill at the builder's hut asking for the 64 cobblestone that are available in BOTH chests. 

I've had the same issues some others reported with building items going missing from the builder's chest (not taken by deliverymen, not in Warehouse) but I don't know if this current issue is related. 

### Steps to reproduce the problem

1. Put items in builder's chest(s)
2. Wait for builder to need item yet not take them from the chests. 

Thanks for all your hard work guys! Keep it up! :)

**Comment by Shwat** [comment]
I believe I have the same if not similar issue where I will put all necessary items in the builder chest, only for the worker to request said items unless I refresh the chest.
![2018-10-05_16 54 31](https://user-images.githubusercontent.com/435553/46526026-b5405100-c8bf-11e8-9e9f-d122f0dd6ead.png)
![2018-10-05_16 54 36](https://user-images.githubusercontent.com/435553/46526033-b8d3d800-c8bf-11e8-9e75-6c13f56d90f5.png)

**Comment by Raycoms** [comment]
I debugged this a bit. /mc rs reset colony: 1 (your colony id)
should fix this. Meanwhile, we'll rework some backend parts of this system which should solve this on the long term as well.
