### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by G1R-Productions** [ldtteam/minecolonies#2922]
### Minecolonies version
1.12.2-0.9.4-RELEASE-universal

Version: 
1.12.2
### Expected behavior
Game not to crash

### Actual behaviour
Game crash

https://pastebin.com/fCRwcw2j

### Steps to reproduce the problem
Load single player world.
World loads.
Game Crashes.

**Comment by Raycoms** [comment]
Try the latest alpha please

**Comment by G1R-Productions** [comment]
Loaded up my singleplayer world. I was able to move around for a little bit before the crash occurred again. I then loaded up the world again and killed several of my colonists and have not had the crash since. But that is not an ideal solution should it happen again.

**Comment by Raycoms** [comment]
Did you try the latest alpha?

**Comment by G1R-Productions** [comment]
Yes, that was on the latest alpha release.

**Comment by Raycoms** [comment]
do you have lucraft installed?

Am Di., 2. Okt. 2018 um 09:40 Uhr schrieb G1R-Productions <
notifications@github.com>:

**Comment by G1R-Productions** [comment]
I do not have lucraft installed.

**Comment by Raycoms** [comment]
I'm traveling currently, I should be able to fix this on Sunday

**Comment by G1R-Productions** [comment]
Okay sounds great! Have a good time traveling.

**Comment by Raycoms** [comment]
I checked the log well and this seems to be a vanilla issue with this particular chunk.
Basically, the citizen tries to load the chunk and crashes. But this should also crash when the player tries to load it.
