### ISSUE TITLE
Build shape/outline doesn't match actual building

### ISSUE THREAD

**Issue by Paril** [ldtteam/minecolonies#2924]
### Minecolonies version

Version: 

### Expected behavior
When Build is pressed, the construction tape outlines the exact area the building needs.

### Actual behaviour
By changing the style of the building (and potentially angle?), often this size is far off from the true size. Makes it impossible to ensure that buildings don't collide or remove things you don't want them to remove.

![](https://i.imgur.com/nkSQXpu.png)
Note that the tape ends several blocks before the builder actually cleared the area.

### Steps to reproduce the problem

1. Plop Town Hall down
2. Press Build, change style to Medieval Dark Oak
3. Watch as builder overextends

**Comment by Nightenom** [comment]
You need to use the buildtool for placing any building to ensure the tape matches location

**Comment by Nightenom** [comment]
We are planning that the tape will change on style changed, but as always no eta

**Comment by Paril** [comment]
But you can't view a lot of the buildings (Medieval Dark Oak for instance) from the Build Tool, so that option doesn't work either

**Comment by someaddons** [comment]
you need the building tool + the block you want to build in your inventory to have all placement options

**Comment by Paril** [comment]
Ah, okay. I'll give that a shot.
