### ISSUE TITLE
Stone Restaurant T5 Not feeding citizens

### ISSUE THREAD

**Issue by BonaireDreams** [ldtteam/minecolonies#2925]
### Minecolonies version
0.9.2-RELEASE, persists in 0.9.13-BETA

Version: 

### Expected behavior
Feed the Hungry

### Actual behaviour
Not feeding the hungry

### Steps to reproduce the problem
Not 100% sure it started in 0.9.3 but it is persisting into 0.9.13. Colonists are standing in the restaurant huddled near the crate. The worker is outside in the stable area. If I fire and rehire the worker she comes in and feeds everyone. She will feed people a few more times and then after a while of playing I notice on my minimap that everyone is standing around in the restaurant again. 

I started building a Birch restaurant last night to see if the issue persists with a different style and level of restaurant.

**Comment by Paril** [comment]
I've noticed that sometimes the worker will get stuck near the work block and not be able to feed. Using Recall Worker often puts them in the right spot.

**Comment by Raycoms** [comment]
Can you upgrade to the newest alpha and check if this persists, the stuck handling should be better there.
