### ISSUE TITLE
[Discord] moving townhall causes citizens to disappear

### ISSUE THREAD

**Issue by Nightenom** [ldtteam/minecolonies#2926]
> Despirien Today at 18:49
> In your newest version of the mod should you build a town hall and then choose reposition the villagers will vanish and the recall button does not work. It's as if they get send to nether or end for some reason. They are registered alive but are ghosted and non reclaimable.

> DespirienToday at 18:50
> I have taken the version back to stable and they are back. But still non fireable and non recallable

**Comment by Raycoms** [comment]
Do you have it on pvp mode?

**Comment by Nightenom** [comment]
I don't think, this guy doesn't have github acc

**Comment by Nightenom** [comment]
> DespirienToday at 21:38
> I'm in an ftb pro modpack. It's solo

**Comment by mojoyup1528** [comment]
Same thing happened to me, but likely due to PVP mode in cfg.

**Comment by Raycoms** [comment]
Probably due to the pvp mode. @Nightenom can you disable the move-townhall option in the pvp mode?
