### ISSUE TITLE
Crash on game load no matter what I try

### ISSUE THREAD

**Issue by VileGoo** [ldtteam/minecolonies#2927]
### Minecolonies version

_Multiple versions tried:_
Version: 1.12.2-0.9.141-ALPHA
Version: 1.12.2-0.9.4-RELEASE

### Expected behavior

- Game loads without issue.

### Actual behaviour

- Game crashes while loading, never reaches main menu. 

Error log produces the same error across multiple versions of Forge: (14.23.4.2704, 14.23.4.2705, 14.23.4.2765)

> _Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from MineColonies (minecolonies)_
[crash-2018-10-02_04.36.08-client.txt](https://github.com/ldtteam/minecolonies/files/2437497/crash-2018-10-02_04.36.08-client.txt)

### Steps to reproduce the problem

1. Fresh install of .minecraft folder
2. Download Minecraft 1.12.2 from launcher
3. Download Forge 1.12.2-14.23.4.2705-installer-win.exe (recommend version)
4. Download Minecolonies universal and api jar files and place into mods folder
5. Add new launch configuration in launcher that uses Forge version mentioned on step 3
6. Launch game with Forge configuration
7. Game crashes when loading

**Comment by Nightenom** [comment]
Huh, it took me a while to find what's probably causing that: don't run API jar on client side unless you are sure you need to do so

**Comment by PoroUsedSnax** [comment]
Yeah, if you're looking to just play Minecolonies the API jar isn't required, just the universal one.

**Comment by Raycoms** [comment]
As nightenom said you only need the minecolonies-universal jar not the API jar.
