### ISSUE TITLE
Barbarians kill colonist World corrupts

### ISSUE THREAD

**Issue by Plisko1** [ldtteam/minecolonies#2929]
### Minecolonies version

Version: 
1.12.2-0.9.125-ALPHA
### Expected behavior

- 
Play normally with no problems for 80-100 game days using the "Life in the Village" modpack from FTB/Twitch.  A colonist gets killed by barbarians at night.   I go to sleep.. Wake up... Mourn them in the morning.

### Actual behaviour

- 
Play normally for 80-100 game days using the "Life in the Village" modpack from FTB/Twitch with no problems.  Colonist gets killed by barbarian at night.  I go to sleep.  I wake up.  It's still night.  Time didn't change. My movement controls are backwards.  I can never sleep again.   I can't save and quit the game.  Force quit is required.  If I play the same world again I Return to before I slept... but the same thing happens if I sleep again.  This happened on one world and I lost it.  I created another world form the same seed, went to the same spot, rebuilt the colony again played normally again... everything was fine until a colonist was killed by a barbarian again.  Then the exact same thing happened the moment I tried to go to sleep.

I have the world saved from a day or so before this incident and then the current corrupted world.  I can provide either or both.

The log from the incident is pasted here:

https://pastebin.com/T1sG9Uyc

### Steps to reproduce the problem

1. Build a fairly complete colony with most buildings up to level 3 or 4 using the "Life on the Village" modpack available on Twitch..
2. Let a citizen get killed by barbarians.  
3. Go to sleep in your bed.
4. Cry

**Comment by Nightenom** [comment]
Definitely weird, not sure what's causing it (-> someone with more knowledge might probably know, @Raycoms), can you report the last four lines of pastebin you posted to Fast Leaf Decay mod?

**Comment by Plisko1** [comment]
Ok I'll post the log to them. I hope someone can track it down.   It was a fun mudpack but this just kills it.  Is there a max number of nights I can set between Barbarian raids?

**Comment by Raycoms** [comment]
The configuration file of your world let's you make the barbarians as weak
and as rare as you want it

**Comment by Plisko1** [comment]
I noticed that I just didn't know if there was a limit to the number of nights between raids... so could I set it to once every 100,000 nights... I guess was the question.   That would probably be enough of a workaround to let me keep playing.

**Comment by Raycoms** [comment]
Yeah you can even execute a command to turn them off for your colony

**Comment by Plisko1** [comment]
Oh is that like a  "/barbarian raid false" type command?   I hadn't seen those yet.

**Comment by Plisko1** [comment]
Ahh found it. thx

**Comment by Raycoms** [comment]
Can you send me the log of the world which fails to start to load?

**Comment by Raycoms** [comment]
I just checked, there is a fix for this world corruption as well in a newer version than 1.12.2-0.9.125-ALPHA
