### ISSUE TITLE
Deliveryman wont deliver materials builder requests

### ISSUE THREAD

**Issue by Shwat** [ldtteam/minecolonies#2932]
### Minecolonies version

Version: 1.12.2-0.9.141-ALPHA

### Expected behavior

- Deliveryman collects materials from Warehouse and delivers to Builder

### Actual behaviour

- Deliveryman will take unneeded materials from Builder, but completely ignores any requests.

### Steps to reproduce the problem

1. Have Warehouse
2. Stock warehouse
3. Build building
4. Wait for builder to request material.

**Comment by Paril** [comment]
The Builder only requests the first item in his request list at a time, and Deliverman can only act on that request. It's unfortunately slow because it seems he has to keep waiting for Builder to request the next thing, so if you're missing a Furnace for instance and it is at the top of his queue he'll just keep asking for that and never move on to other items.

**Comment by Raycoms** [comment]
Yeah, future update. These systems are extremely complex and not so easy to
code and maintain efficiently as you might imagine

**Comment by Shwat** [comment]
The deliveryman never deposits anything into the builder chest. Ive left him waiting for hours, still the same request.

**Comment by marchermans** [comment]
@Shwat open up the request details. It should tell you by who it gets resolved. Check if your DMan is listed there

**Comment by Shwat** [comment]
Ok, so it says the resolver is Player.. how do I change this?
![2018-10-07_15 52 30](https://user-images.githubusercontent.com/435553/46579694-1cd5d800-ca49-11e8-8f27-d91091264a06.png)

**Comment by Shwat** [comment]
Ive fixed this by using /mineColonies rs reset colony: 1

Thanks for the tip off Orion.

**Comment by BenjaminHoegh** [comment]
@Shwat I have the same issue but using ` /mineColonies rs reset colony: 1` dosn't resolve it :(

**Comment by marchermans** [comment]
@BenjaminHoegh there is a fix for it, currently in testing.

**Comment by YosemiteSam3003** [comment]
> @BenjaminHoegh there is a fix for it, currently in testing.

Is it fixed because the delivery man just walks around with nothing in his inventory and doesn't give anyone anything. Im tired of running around doing it myself

**Comment by Raycoms** [comment]
We can't reproduce it, it works fine on our Worlds...

Can you recreate your warehouse or so?
