### ISSUE TITLE
workingRangeTownHallChunks gets treated as if on default infrequently

### ISSUE THREAD

**Issue by SulpherStaer** [ldtteam/minecolonies#2933]
### Minecolonies version

Version: 1.12.2-0.9.141-ALPHA

### Expected behavior
The workingRangeTownHallChunks when set to a higher range, does not (¿randomly?) get treated as if it is on the default 8 when set to higher than 8.

### Actual behaviour
The workingRangeTownHallChunks gets treated as if it is set to 8 after having placed one or more? buildings. I do not know what causes the bug actually.

### Steps to reproduce the problem
I am uncertain what causes the bug.

1a. Set the workingRangeTownHallChunks to 16
1b. Create a new world.
2. Build a townhall & builder. Finish level 1 construction.
3. Build any building (fisherman?) near the edge of the colony, finish level 1 construction.
4. Plan any building (restaurant?) within the default range.
5. Observe strange behaviour?

**Comment by Raycoms** [comment]
This config value only works pré colony creation. Post colony creation you
have to increase it with the claim command

**Comment by SulpherStaer** [comment]
It was set pre-colony creation. It just gets treated as default now.

What is the claim command? Maybe that will turn back time, and increase the range to the config setting again.

**Comment by PoroUsedSnax** [comment]
That would be `/mc colony claim [colony: colony id] [range: number in chunks] [add: true/false]`

I would recommend standing in the central chunk of your colony to execute this as it will claim chunks for the selected colony based on your current location

**Comment by SulpherStaer** [comment]
When I use that command, /mc colony claim 01 16 true

it says missing required parameter colony. I've also tried just a 1 and not 01 - still the same.

**Comment by Raycoms** [comment]
Use tab completion

**Comment by SulpherStaer** [comment]
even with tab complete it fails.
tab complete gets me to /mc colony claim colony:

from there I tried:
/mc colony claim colony:1 range:16

still nothing. (also tried 01)

**Comment by someaddons** [comment]
hard to notice and took me a bit aswell: colony: and range: require a space before the value, so do it like this: /mc colony claim colony: 1 range: 16

**Comment by marchermans** [comment]
@Raycoms we should improve the documentation on our command really. This is a pain else.

**Comment by Raycoms** [comment]
Yeah waiting for the new wiki, it's almost ready

**Comment by JumpySmudge** [comment]
This command doesn't do anything for me. It tells me it has successfully claimed chunks, but I still can't build where the borders would have been. I have tried resetting and refreshing the colony, but nothing changes. Also noticed the command requires dimension too.

**Comment by Raycoms** [comment]
Is part of: https://github.com/ldtteam/minecolonies/issues/3042
