### ISSUE TITLE
Sheep farmer automatically colors sheep

### ISSUE THREAD

**Issue by sharkck** [ldtteam/minecolonies#2935]
### Minecolonies version

Version: 0.9.4-RELEASE

### Expected behavior
Expect the sheep farmer to harvest the wool and meat from sheep without doing anything extra.

### Actual behaviour

Sheep farmer decides it wants to color the sheep... so instead of getting a ton of usable white wool, I have chests full of multi-colored wool that I now have to trash because you cannot dye the wool back to white.

### Steps to reproduce the problem

Play the game, check the sheep farmer from time to time, see colored sheep, use bonemeal on the sheep to turn them back white again, return in the future and find colored sheep again.

**Comment by Raycoms** [comment]
It's a feature

**Comment by Nightenom** [comment]
todo: add a toggle button for that :D I might do that on monday, but I'm not really sure about that

**Comment by sharkck** [comment]
That would be awesome.  Been needing a ton of white wool to craft shield containment blocks and find 1 or two stacks of white but 20 stacks of colored that arent oredict and it's *sadface*.  I appreciate your review and action!

**Comment by Enverex** [comment]
@sharkck : As a sidenote, you can always "reset" wool back to white by dyeing it with bonemeal.

**Comment by dudasl** [comment]
What about have option in sheepherder hut to turn on/off different colors (similar to saplings in lumberjack hut)?

You need only some colors of wool, so why collect all of them? This also allows have specialized sheepherders.

**Comment by Raycoms** [comment]
We did it on random to avoid making it too overpowered to get free colored
wool without being able to control which exactly.

Am Do., 11. Okt. 2018 um 03:31 Uhr schrieb Ladislav Dudáš <
notifications@github.com>:

**Comment by Nightenom** [comment]
Like we can change that by adding a request for getting the correct dye. So we will have random and no requests or one color and dye requests

**Comment by Raycoms** [comment]
For dye requests we will have a) The florist which creates flowers for the
dyes and b) a worker which has the job of dying wool using the dyes there
are in the warehouse on request

Am Do., 11. Okt. 2018 um 10:01 Uhr schrieb Nightenom <
notifications@github.com>:

**Comment by Nightenom** [comment]
Ok, for now I will only add that turn off button

**Comment by Raycoms** [comment]
@Nightenom progress?

**Comment by Nightenom** [comment]
Zero, to be honest

**Comment by someaddons** [comment]
maybe just keep 1 sheep white?

**Comment by Nightenom** [comment]
Meh, finally doing the button
