### ISSUE TITLE
Lumberjack often replants the wrong sapling type

### ISSUE THREAD

**Issue by Paril** [ldtteam/minecolonies#2937]
I have two Lumberjacks, one dedicated to Dark Oak and one dedicated to Spruce. For some reason, the Dark Oak lumberjack is replanting Acacia or Oak saplings where the Dark Oak spots were. I don't even think she had Acacia saplings in her inventory so I'm unsure how she got them (she *did* have some before but I took them from her when I specialized them).

**Comment by Raycoms** [comment]
Are the dark oak trees connected via their leaves to Acacia and/or oak
trees?

Am So., 7. Okt. 2018 um 00:10 Uhr schrieb Jonathan <notifications@github.com

**Comment by Paril** [comment]
Yeah. Does this cause issues?

**Comment by Raycoms** [comment]
Yes, the lumberjack gets the sapling from the leafes, so if it grows
together it's difficult to detect for him

**Comment by Nightenom** [comment]
But he still should not plant disabled saplings

**Comment by Paril** [comment]
Speaking of disabled saplings: one of my Lumberjacks does not display Dark Oak Saplings in her list of saplings. I literally can't stop her from chopping them down. Oddly enough, she's ignoring the Spruce trees that I asked her to chop too.

**Comment by Raycoms** [comment]
What version are you playing? This should be fixed in the newest ones
