### ISSUE TITLE
Birch Shepherd Cannot Reach Worker Block Due to Underground Placement

### ISSUE THREAD

**Issue by Enverex** [ldtteam/minecolonies#2939]
### Minecolonies version
minecolonies-1.12.2-0.9.139-ALPHA-universal

### Issue
Birch shepherd hut worker block is in the floor. This seems to create pathing issues as the worker is constantly taking up a lot of tick time trying to "reach" the block that they're stood next to, but aren't on the same level as. Trying to Recall Worker doesn't work either as it claims you need to make space (I assume this is due to the fact that it's surrounded on all sides by grass).

### Steps to reproduce the problem
Build a level 1 birch shepherd hut, hire a worker and then watch tick time.

Worker trying to reach the block with a recall failed notice:

![image](https://user-images.githubusercontent.com/958670/46582388-bdbe9600-ca3d-11e8-93cd-6977fd73436b.png)

Problematic worker highlighted:

![image](https://user-images.githubusercontent.com/958670/46582429-77b60200-ca3e-11e8-83b8-342b2dd467ae.png)

**Comment by Raycoms** [comment]
That's the same issue as the diamond block tbh =D

Am So., 7. Okt. 2018 um 10:33 Uhr schrieb Benjamin Hodgetts <
notifications@github.com>:
