### ISSUE TITLE
Birch Barracks Level 5 Creates Builder Pathing Issue

### ISSUE THREAD

**Issue by Enverex** [ldtteam/minecolonies#2941]
### Minecolonies version
minecolonies-1.12.2-0.9.139-ALPHA-universal

### Issue
The builder will always get stuck when upgrading a level 4 Birch barracks to level 5. For some reason they seem to think they can jump from the barbican walkway onto the black stained glass. Problem there is that the walkway is a slab so the glass is actually a block and a half above, therefore you can't jump to it.

The builder will basically get stuck forever trying to jump, even if you reset them, because they'll just immediately return to the same spot, trying to make the impossible jump. Putting blocks for them to jump on seems to fix it.

### Steps to reproduce the problem
Upgrade a level 4 birch barracks to level 5.

The stuck builder:

![image](https://user-images.githubusercontent.com/958670/46583883-e43bfb80-ca54-11e8-84cc-ab61356d1391.png)

**Comment by Raycoms** [comment]
Similar to: https://github.com/ldtteam/minecolonies/issues/3005
