### ISSUE TITLE
Barbarian Spawn changes X/Z Coordinate System

### ISSUE THREAD

**Issue by Tarumba** [ldtteam/minecolonies#2946]
### Minecolonies version

Version: 1.12.2-0.9.143-ALPHA

### Issue

- Whenever the Barbarian Horde spawns the coordinate system of the world changes. 
Before:
![2018-10-08_12 24 10](https://user-images.githubusercontent.com/43953707/46604826-e4410780-caf7-11e8-95c8-3df1e3e5e626.png)
After:
![2018-10-08_12 35 55](https://user-images.githubusercontent.com/43953707/46604952-28340c80-caf8-11e8-85fd-4eb3cdfac34b.png)

#### Before Horde spawn -> After Horde spawn:
East (positive X) -> South (positive Z)
West (negative X) -> East (positive X)
South (positive Z) -> West (negative X)
North (negative Z) -> North (negative Z) stayed the same

### Steps to reproduce the problem

1. Create a new Pack on Curse (V:1.12.2, Forge: 14.23.5.2769, MineColonies: 1.12.2-0.9.143-ALPHA) 
2. Set "averageNumberOfNightsBetweenRaids=1" (I also tried it with "/mc raid-now" and the results are the same) and build Colony able to spawn raids.
3. Barbarians spawn and the coordinate system changes (a couple of seconds after the raider-message appears in chat)
4. Coordinate system stays changed until the Minecraft is restarted. The restart reverts it back to the initial. 

#### Notes:
- The coordinate system changes seem to stay when Minecraft is restarted before the last Barbarian is killed
- If not restarting Minecraft the coordinate system changes again at the next Horde spawn
- North only stayed the same in the example, other tries all direction changed/ other directions stayed the same
- As far as I could tell it only changed once at the horde spawn and the changes then stayed the same during/after the raid (until a restart/new spawn)
- I only specifically tested it with version 1.12.2-0.9.143-ALPHA but the same thing definitely happened on my normal play-through with the ALPHA versions dating up to at least a couple weeks back. (Also with different Forge versions)
- This coordinate change might also be the cause for frames popping off/changing the direction they are attached in and Barrack Towers oriented the wrong way, but I wasn't able to verify those. I think the frames issue might only happen if they are not loaded when the coordinate system changes.

**Comment by Raycoms** [comment]
First of all, congratulations on finding that out!
I'll check on that!

Am Mo., 8. Okt. 2018 um 08:46 Uhr schrieb Tarumba <notifications@github.com

**Comment by Tarumba** [comment]
Additionally the coordinate change seems to mess with the placing of blocks as afterwards stairs i tried to place were the wrong orientation. That's how i figured it out initially. It also messes with the directions the schematics are moving in the Building Tool-menu.

Thinking back i also had a similar problem when placing a diamond chest from the Ironchest mod in my normal play-through. It would sometimes place them not facing the Player. I would have first noticed the turning chests around end of June/ beginning July. I hadn't played for a while before that, so I can't really narrow it down further.

On a personal note: Thanks so much for all the work. Minecolonies has easily become my favorite Mod.

**Comment by Raycoms** [comment]
Thanks for this report, we were searching for what was causing this for a
while. Now that you told me where it is, we found it fairly quickly. Will
push out a hotfix immediately.

Am Mo., 8. Okt. 2018 um 09:28 Uhr schrieb Tarumba <notifications@github.com

**Comment by Paril** [comment]
Woo, nice catch!

**Comment by Raycoms** [comment]
Fixed
