### ISSUE TITLE
Delivering useless items etc

### ISSUE THREAD

**Issue by eproces** [ldtteam/minecolonies#2947]
### Minecolonies version

Version: 1.12.2-0.9.4-RELEASE

### Expected behavior

Deliveryperson should deliver requested items and cooked food to various chests around town, and empty chests that are full back into the warehouse. They also shouldn't take tools that that building can use, and/or should deliver tools from the warehouse when they are requested.

### Actual behaviour

I have two deliverypersons, and after I added the second one suddenly a lot of random items started showing up in chests around town. They especially like to deliver colored wool and leather to every chest. They steal axes and shears from my various farmers (e.g. shepherd asking for shears, I check the warehouse, there are 3 party used shears in there that had been taken away from shepherd). They deliver raw meat or potatoes all over instead of to the restaurant. They never empty the farm chest, even though I see them visit it it's always full. They don't seem to take cooked food from restaurant to other chests.
I have tried firing and rehiring them a few times, doesn't seem to help. I fired the second deliveryperson and hired a new citizen. That didn't help either. I didn't have this problem when I had just one, but that was also an earlier version of minecolonies.

### Steps to reproduce the problem

1. Watch deliveryperson..
2. See what they deliver..
3. Curse them for their stupidity..
4. ... Profit

**Comment by PoroUsedSnax** [comment]
Update to one of the recent alphas, this issue should be fixed there.

**Comment by eproces** [comment]
Ok I updated to 1.12.2-0.9.148-ALPHA and the behavior doesn't seem changed. Immediately they brought leaf piles and shady gardens to the builder, and won't get the cobblestone he needs from the warehouse. I paused and restarted both deliverypeople.

**Comment by Raycoms** [comment]
Do /mc rs reset colony: 1
