### ISSUE TITLE
Pathfinding and fluids

### ISSUE THREAD

**Issue by Nightenom** [ldtteam/minecolonies#2948]
So our pathfinding is not as good as one would expect: our barbs don't take into account any fluid that they should encounter on their future path
![image](https://user-images.githubusercontent.com/17338378/46622010-6ac20d00-cb29-11e8-98da-39d7615869d7.png)
^^ the lava to the right is endless, then if you are walking before the red circle from the right zombie will follow you but don't jump into lava, when you are in the red circle or closer to the left lava end zombie will path around
our barbs try to go around for around 7 blocks and then jump into lava no matter what
with water it also applies for citizens -> it should try to path around up to amount shown in the picture, then try to cross or search even bigger detour

**Comment by Raycoms** [comment]
Should be fixed
