### ISSUE TITLE
Cannot place Supply Camp

### ISSUE THREAD

**Issue by dlhitzeman** [ldtteam/minecolonies#2949]
Version: 0.9.4-RELEASE, Minecraft 1.12.2

I am trying to place the Supply Camp. I have ensured I have a clear 16x17 area.

Instead of placing, the dialog returns the following error (the last two lines):

![2018-10-08_12 58 32](https://user-images.githubusercontent.com/30905959/46623116-a72a4480-cafa-11e8-8ded-2d1f8ff7ccce.png)

[latest.log](https://github.com/ldtteam/minecolonies/files/2456920/latest.log)

I have tried replacing the block with another block type, raising the platform area, etc.

If you need more info, I will get it to you as quickly as possible.

**Comment by Nightenom** [comment]
Did you clear the block which is blamed for not being air?
Also, you mentioned it (so just checking), is your platform two layers of solid blocks (dirt, ...)?

**Comment by dlhitzeman** [comment]
I cleared the block, then it says it can't be solid. It is definitely two layers of solid. In the screenshot, I get both those error messages at the same time.

**Comment by dlhitzeman** [comment]
I have no idea what the issue was, but I moved the camp one block further away from me when placing it, and it placed.

**Comment by dlhitzeman** [comment]
Everything else was the same.

**Comment by dlhitzeman** [comment]
I guess I'll close this, then...

**Comment by dlhitzeman** [comment]
Thanks for the great mod, by the way, and for your fast response. If I ever figure out what wasn't working, I'll let you know.

**Comment by Insane96** [comment]
I have the same problem in 1.14
![image](https://user-images.githubusercontent.com/7185104/67199017-84668780-f400-11e9-84dd-3acfbea5b262.png)

**Comment by Raycoms** [comment]
and the block it mentions, is it air?

**Comment by Insane96** [comment]
If it's air I get the message above, if it's solid I get only the last message saying it needs air.

**Comment by Raycoms** [comment]
weird, can you send me the world and maybe put a wool block where you're trying to place it, so that I can test it?

**Comment by Insane96** [comment]
I've put cobblestone at the 4 corners of where I'm trying to place it where the fences are.
[MainColonies.zip](https://github.com/ldtteam/minecolonies/files/3750286/MainColonies.zip)

**Comment by Raycoms** [comment]
Okay, great, I'll check it out tonight probably

**Comment by Insane96** [comment]
Forgot to mention that you need to rotate it 180°

**Comment by Raycoms** [comment]
I pushed a fix

**Comment by JackOfSpade** [comment]
Still not fixed 1.15.2

**Comment by ravenbuilder934** [comment]
What 1.15.2 version are you on? This sounds like you're not on the latest alpha.
