### ISSUE TITLE
Tinkers tool leveling + IronChest failed compat

### ISSUE THREAD

**Issue by Flytre** [ldtteam/minecolonies#2950]
### Minecolonies version

Version: 1.12.2-0.9.4-Release

### Expected behavior

- 
Iron chests from the iron chest mod showing up in building schematic previews when using the build tool.
NPCs providing experience towards leveling tinker tools when using them.

### Actual behaviour

- 
Iron chests from the IronChests mod do not render in the build tool schematic previews.

NPCs do not provide experience to tools when using them.

### Steps to reproduce the problem

1. run minecolonies with Tcon, tinker tool leveling, and iron chests
2.Create a building with an iron chest inside
3.Save it as a schematic
4. Preview the building with the build tool

&&

1. Give a worker (ex. Lumberjack) a tinker construct hatchet
2.When it chops down trees, it uses durability from the hatchet but doesn’t give experience to the hatchet.

**Comment by Raycoms** [comment]
Yes, none of the tileEntities get rendered at the moment. That's something we add in the future.
About the tinker tools, they don't work because they need a player to level up.
Although we got an issue open for that already.

**Comment by Flytre** [comment]
Alright, sounds fair. The tool leveling thing is a shame though.
