### ISSUE TITLE
Builder's hut level 1 can't be build without a builder's hut level 1

### ISSUE THREAD

**Issue by MrVirtualis** [ldtteam/minecolonies#2951]
### Minecolonies version
Version: 1.12.2-0.9.148-ALPHA

### Expected behavior
Builder's hut level 1 can be build without a builder's hut 1 present

### Actual behaviour
It says in the chat, that a builder's hut level 1 is required to build the builder's hut level 1.

### Steps to reproduce the problem
1. Found a new colony
2. Place the builder's hut level 1 and click on "build building"
3. Tadaaa.. :)

**Comment by Raycoms** [comment]
Will produce a hotfix right now.

Am Mo., 8. Okt. 2018 um 14:27 Uhr schrieb MrVirtualis <
notifications@github.com>:

**Comment by MrVirtualis** [comment]
Fix works. Thanks for fixing it. And special thanks for fixing it so quickly!
