### ISSUE TITLE
Deliveryman stopped doing things after update

### ISSUE THREAD

**Issue by Paril** [ldtteam/minecolonies#2954]
Updated to latest alpha (minecolonies-1.12.2-0.9.150-ALPHA-universal.jar) and it seems Deliveryman have stopped Deliverymanning.

It also seems that my .dat file has changed to "colony1_0.dat", I dunno if there's something going on there or if that's intentional; the colony1.dat's last updated seems to be just before I updated to latest version.

I'll attach both just in case they provide any info about what's going on, if not I'm wondering what steps I should take to troubleshoot. They aren't pulling from any chests, not in the warehouse or anybody elses chests, and aren't attempting to fulfill requests.

[minecolonies.zip](https://github.com/ldtteam/minecolonies/files/2462457/minecolonies.zip)

**Comment by Raycoms** [comment]
./mc rs reset colony: 1

Am Di., 9. Okt. 2018 um 19:40 Uhr schrieb Jonathan <notifications@github.com

**Comment by Paril** [comment]
Either that or restarting the server seemed to have fixed it. Thanks!
