### ISSUE TITLE
Medieval Dark Oak Warehouse 5 requires "Mossy Monster Stone Brick Egg"

### ISSUE THREAD

**Issue by Paril** [ldtteam/minecolonies#2959]
Think they made a mistake during making it and grabbed the monster egg rather than the regular one.

**Comment by Nightenom** [comment]
@carlansor, I did it once but also did not send it back to the structure server
> #2527

**Comment by carlansor** [comment]
there is a ghost that appears from time to time, its called "monster egg in x warehouse level" xD dont know how this keeps coming up, the latest schems i provided in the forums contain this fix, from a long time ago

**Comment by Raycoms** [comment]
@Paril what's the minecolonies version?
