### ISSUE TITLE
Colonists not seeing items in building inventory

### ISSUE THREAD

**Issue by G1R-Productions** [ldtteam/minecolonies#2960]
Version: minecolonies-1.12.2-0.9-BETA-universal

### Expected behavior
Colonist should pull out items from building inventory that it needs and request items it doesn't have.
### Actual behaviour
Colonist ask for materials  that are already inside building.

### Steps to reproduce the problem
Colonist asks for materials
Materials are already in building
Player takes materials out of building.
Player puts materials back in building.
Colonist takes materials.

**Comment by dannydjdk** [comment]
Seeing this issue in 0.10.1-RELEASE as well. Any modification to the inventory (such as sorting with InventorySorter mod) will cause the colonist to "see" the inventory. But, each time the colonist returns to the inventory, the player has to meet him/her there to make some change to the inventory.

**Comment by Raycoms** [comment]
Oh that's weird, what kind of mods do you have installed? It seems like some inventory mod does prevent this. Did you try /mc rs reset colony: id ?

**Comment by G1R-Productions** [comment]
Seems fixed after updating to latest version and using that command.

**Comment by Raycoms** [comment]
Okay nice

**Comment by dannydjdk** [comment]
Reset command fixed it for me as well.

**Comment by G1R-Productions** [comment]
This still occurs even with new update. Every time you turn off server and turn it back on again you need to run the command to fix it.
