### ISSUE TITLE
Villagers not present when logging back into world.

### ISSUE THREAD

**Issue by TopHatFetus** [ldtteam/minecolonies#2961]
Version: minecolonies-universal-1.10.2-0.9.7587

### Expected behavior

When logging out and back into a world villagers are present continuing as if nothing had happened.

### Actual behaviour

Logging out and back in causes all villagers to disappear along with their inventories. This forces a restart of the entire colony.

### Steps to reproduce the problem

    

1. Have a colony with villagers. could be just town hall or a city. doesn't matter just needs villagers.
2. Log out of world, as if you had to go do something
3. Reopen the world to play 
4. See lack of villagers and present ghost town.

**Comment by Raycoms** [comment]
Hi, this is a problem we observed a few times but has been fixed in the recent 1.12.2 versions.
A workaround is turning off the server and nbtediting the colonies.dat to increment the colony counter back to 1 should fix the loading process.
