### ISSUE TITLE
Level 4 dark oak mine requires spawn bat item

### ISSUE THREAD

**Issue by G1R-Productions** [ldtteam/minecolonies#2963]
Version: minecolonies-1.12.2-0.9-BETA-universal
The level 4 upgrade for the dark oak mine requires a spawn bat egg. It is not possible to get this item without cheating.

**Comment by Paril** [comment]
Weird, I upgraded the Dark Oak Medieval Mine without that item.

**Comment by someaddons** [comment]
try again pls with the latest version :)

**Comment by G1R-Productions** [comment]
10.1 still requires "Spawn Bat" egg. 
https://imgur.com/a/3TtihiQ

**Comment by Raycoms** [comment]
Ooh, 1.10 yes.

Am Sa., 13. Okt. 2018 um 14:17 Uhr schrieb G1R-Productions <
notifications@github.com>:

**Comment by PoroUsedSnax** [comment]
Most likely this is fixed on our schematic server but hasn't yet been saved and uploaded

**Comment by Raycoms** [comment]
1.10 not

Am So., 14. Okt. 2018 um 16:16 Uhr schrieb Mark Fisher <
notifications@github.com>:

**Comment by StrommKral** [comment]
29 Alpha, dark oak miner building, level 4 requires the spawn bat egg now

**Comment by lunadragnstar** [comment]
Fixed
