### ISSUE TITLE
Request - Recreation

### ISSUE THREAD

**Issue by dannydjdk** [ldtteam/minecolonies#2964]
All work and no play makes my colonists seem unfulfilled. Strange that it doesn't affect their happiness.

I would love to see them letting loose at the local pub, having a picnic at the park, socializing at a cafe, swimming in a pool, or maybe entertaining each other at a local amphitheater. Perhaps having recreation facilities could increase happiness and be demanded by larger populations or citizens at higher levels.

**Comment by Raycoms** [comment]
Definitely an interesting idea. I like it.

Am Sa., 13. Okt. 2018 um 11:26 Uhr schrieb Danny <notifications@github.com>:

**Comment by someaddons** [comment]
kinda seems like the citizen happiness system from the Anno games seems fitting for minecolonies

**Comment by ArodSnaux** [comment]
Agreed, especially since you guys did such a good job with the citizens costumes before they are hired, it's a shame to see them even sleeping in their uniforms. Recreation time would mean they don normal clothing and just wander about, adding greatly to the flavor of the game.

**Comment by Raycoms** [comment]
Closed in  favor if: https://github.com/ldtteam/minecolonies/issues/2586
