### ISSUE TITLE
Deliverymen aren't working properly after latest update.

### ISSUE THREAD

**Issue by sharkck** [ldtteam/minecolonies#2967]
### Minecolonies version
Version: 1.12.2-0.10.1-RELEASE

### Expected behavior

Expect the deliverymen to deliver items to the colonists when they need something

### Actual behaviour

The deliverymen are not supplying the miner with torches when requested nor the builders with the items they're requesting either.  

### Steps to reproduce the problem

Update from version 0.9.4-RELEASE to version 0.10.1-RELEASE, load the server, it happens.

### Notes:

Actually following the deliveryman around, everybody is requesting something but nothing is being transferred.  

They are going back and forth between the buildings and the warehouse but not collecting anything.

I have repeatedly used the /mc colony refresh colony: 1 command at different points trying to persuade them all to do something... One thing I noted is that neither of my builders were going to the restaurant to eat and were sitting there with 0 food.  I put food in both their inventories, they ate it and still sat there without any luck the deliverymen would bring them any materials.  I put the 6 glowstone on my one builder that he was requesting and he did nothing until I used the reset command... he went to the town hall, used it, and went back and is now requesting 19 gravel and nothing showing the delivery guy is going to bring it. And yes, there's plenty of those mats in the warehouse.

**Comment by sharkck** [comment]
Also would like to note that I upgraded my warehouse as far as it would let me with Emerald Blocks either right before the update or after the server first came back up (cannot remember when).  I'm using the Birch style warehouse.  I'm not sure if this has anything to do with it being that all the racks have extra rows in them and all. (I hit repair on it just in case something may be wrong with it... thats why the construction barrier is up)

![image](https://user-images.githubusercontent.com/960552/46912264-a3555280-cf3e-11e8-85bf-3838484b740a.png)

**Comment by sharkck** [comment]
The way the double rack looks when I open it:
![image](https://user-images.githubusercontent.com/960552/46912269-d4358780-cf3e-11e8-8b47-9baefcc10022.png)

Option to upgrade the storage is still there but will not let me anymore even though I have an emerald block on me.
![image](https://user-images.githubusercontent.com/960552/46912275-f202ec80-cf3e-11e8-89e6-4f9140d68559.png)

**Comment by sharkck** [comment]
Request for gravel even though I already hit fulfill and he has some in his inventory:
![image](https://user-images.githubusercontent.com/960552/46912287-43ab7700-cf3f-11e8-873a-27fc07abd13c.png)
![image](https://user-images.githubusercontent.com/960552/46912290-4c9c4880-cf3f-11e8-81f4-624467d3a7e3.png)

Also to note, after that last screenshot, I put a stack of 20 gravel in the building inventory and he took it out and proceeded to use it.

**Comment by Raycoms** [comment]
try /mc rs reset colony: 1

Am So., 14. Okt. 2018 um 00:26 Uhr schrieb sharkck <notifications@github.com

**Comment by sharkck** [comment]
By golly, that did it.  I'm seeing requests now for the delivery guys!  And I just watched em deliver something to my builder.

My apologies if I provided too much information... Didn't see any error logs in the console.  Hope everything I provided may give some insight into why it happened so that there may be a future fix for this.  I'll continue to monitor it and if something else happens I'll let you know!

Again, thank you for the help and your work on this great mod.

**Comment by sharkck** [comment]
By chance, is the upgraded storage the way it's supposed to be?  Also, I'm assuming that since I cannot upgrade again it's at it's max level for extra storage?

**Comment by Raycoms** [comment]
Yes, we're going to improve this GUI soon though. But for now it's like
that.

Am So., 14. Okt. 2018 um 00:34 Uhr schrieb sharkck <notifications@github.com

**Comment by G1R-Productions** [comment]
That reset command only works until server restart. After a restart you need to run the command again or the colonists don't function properly.

**Comment by Raycoms** [comment]
I have a fix incoming

Am So., 14. Okt. 2018 um 11:39 Uhr schrieb G1R-Productions <
notifications@github.com>:
