### ISSUE TITLE
Server not reading the release version of mincolonies1.12.2-0.10.1-release

### ISSUE THREAD

**Issue by mackie419** [ldtteam/minecolonies#2968]
minecolonies-1.12.2-0.10.1-release-universal.jar

This loads fine on my pc but when i try to get it to run it on a hosted server i get this error:

[20:18:53] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_181, running on Linux:amd64:4.4.0-135-generic, installed at /usr/lib/jvm/java-8-oracle/jre 
[31;1m[20:18:53] [main/ERROR] [FML]: Unable to read the jar file minecolonies-1.12.2-0.10.1-RELEASE-universal.jar - ignoring 
java.util.zip.ZipException: error in opening zip file 

I downgraded it to the beta version 1.12.2-0.10.0-beta-universal and it loads fine on hosted server.

not sure what is going on

**Comment by Raycoms** [comment]
Try it again, it seems like there was an error on transmission of the jar.
Try to re-download it.

Am So., 14. Okt. 2018 um 00:38 Uhr schrieb mackie419 <
notifications@github.com>:

**Comment by mackie419** [comment]
Thank you i reuploaded it and it works now.
