### ISSUE TITLE
Builder wont build just stands around.

### ISSUE THREAD

**Issue by BonaireDreams** [ldtteam/minecolonies#2969]
### Minecolonies version

Version:  1.12.2-0.10.1-RELEASE

Just updated from 0.9.4-Release which had same symptom

### Expected behavior
Build building

### Actual behaviour
Builder wont build. Does not request anything. Needs spruce doors (based on his hand) put spruce doors in chest or on builder. still no change.

Console repeating this:
[minecolonies]: WorkOrderBuild at location BlockPos{x=1236, y=77, z=-646} is using schematics/Medieval Spruce/Citizen1 instead of schematics/Medieval Spruce/Citizen1

**Comment by sharkck** [comment]
Try the fix suggested here: https://github.com/ldtteam/minecolonies/issues/2967

**Comment by sharkck** [comment]
Sounds similar to what I ran into...

**Comment by sharkck** [comment]
I did not have that error in the console though.  The only time I've seen that particular error is when the builder wasn't high enough of a level to build the building.  Is the builders hut complete by chance?  Either way, I would still try those two commands to reset everything first.

**Comment by BonaireDreams** [comment]
ya tried both refresh and reset neither worked. Hmm but that was before I updated to 10.1 maybe I'll try that again.
