### ISSUE TITLE
Crash on loading

### ISSUE THREAD

**Issue by cjser** [ldtteam/minecolonies#2977]
Version: minecolonies-1.12.2-0.10.8

World crash on loading.
Description: "Exception in server tick loop java.lang.IllegalArgumentException: Already a colony registered to id=1, colony=Cutucolonia, not changing to colony=Cutucolonia"
crash log:
[crash-2018-10-15_11.24.17-server.txt](https://github.com/ldtteam/minecolonies/files/2479152/crash-2018-10-15_11.24.17-server.txt)

**Comment by Raycoms** [comment]
Hmm, I will have to make a safeguard for that. Let me push something.

>
