### ISSUE TITLE
Server crash, library students

### ISSUE THREAD

**Issue by GanthorPrime** [ldtteam/minecolonies#2979]
Version: 

minecolonies-1.12.2-0.10.8-ALPHA-universal
forge-1.12.2-14.23.4.2707

Server crash during day. maybe related to library, the builder is upgrading it.

Description: Ticking entity

java.lang.NoSuchMethodError: net.minecraft.item.Item.func_190903_i()Lnet/minecraft/item/ItemStack;
	at com.minecolonies.coremod.entity.ai.citizen.student.EntityAIStudy.study(EntityAIStudy.java:131)
	at com.minecolonies.coremod.entity.ai.util.AITarget.apply(AITarget.java:125)

notice this crash happens on the students citizens entity tick (diferrent students on each crash)

Not sure what is happening here, but i set the server to night (citizens goes to sleep), login, and fire all the students on the library.  If i hire again, server crash again (at the start of day).

before that, i tried /mc colony rs, /mc colony refresh, remove the offending colony.dat from the minecolonies server (this one was very annoying, beceause it regenerates the colony file on the next server restart - stop,  no matter what i do: move the backups to other place, restart the server, clear the java cache lol)

[crash-2018-10-15_17.35.38-server.txt](https://github.com/ldtteam/minecolonies/files/2480595/crash-2018-10-15_17.35.38-server.txt)

[colony3_0.zip](https://github.com/ldtteam/minecolonies/files/2480607/colony3_0.zip)

As a side note, im not sure of the library functionality: i have long time students in there and their level is always 0.  ¿maybe they are upgrading their stats and not their level?

**Comment by Raycoms** [comment]
Could you test if it still happens with forge: 14.23.4.2739 ?


Am Mo., 15. Okt. 2018 um 18:29 Uhr schrieb GanthorPrime <
notifications@github.com>:

**Comment by GanthorPrime** [comment]
Just upgrade all to that specific forge version, and it crash again, same exception:

java.lang.NoSuchMethodError on the students.

wow, i completely forgot how old my forge version was.  I will try to upgrade to latest and test again / post my results.  thanks.

**Comment by Raycoms** [comment]
We found the issue @someaddons will fix it =)

**Comment by Raycoms** [comment]
Fix merged =)

**Comment by GanthorPrime** [comment]
thanks!!, will test now
