### ISSUE TITLE
Player can't open Citizen Hut inventory

### ISSUE THREAD

**Issue by NonplussedUltra** [ldtteam/minecolonies#2982]
### Minecolonies version
Version: minecolonies-1.12.2-0.10.7-RELEASE-universal

### Expected behavior
- Clicking the Citizen Hut "Inventory" button opens the hut inventory screen.

### Actual behaviour
- Inventory button makes a "click" sound but nothing happens. The Citizen Hut GUI remains the same. This only happens with Citizen Huts; all other buildings function normally.

### Steps to reproduce the problem
1. Open Citizen Hut GUI
2. Click the "Inventory" button
3. Nothing happens.

**Comment by Raycoms** [comment]
Can you send us your client log when you attempt to do it?

Am Di., 16. Okt. 2018 um 17:44 Uhr schrieb NonplussedUltra <
notifications@github.com>:

**Comment by NonplussedUltra** [comment]
Gladly. Which log do you need? The one from .minecraft/logs/[today's date] ?

**Comment by Raycoms** [comment]
yes

Am Di., 16. Okt. 2018 um 18:07 Uhr schrieb NonplussedUltra <
notifications@github.com>:

**Comment by NonplussedUltra** [comment]
Here is a log containing the error.

I apologize that it's not the only error; I reloaded the game trying to get a new, cleaner log, but Minecraft didn't produce a new log for that play session.

[2018-10-16-4.log.gz](https://github.com/ldtteam/minecolonies/files/2484993/2018-10-16-4.log.gz)

**Comment by Raycoms** [comment]
okay, I checked this. It seems like somehow your world is messed up and you have bed tileEntities where your colony chests should be which I have never seen before.

**Comment by Raycoms** [comment]
I will write some fail save code for this.

**Comment by Raycoms** [comment]
While I'm at this can you send me a: the colony1.dat in your world folder and b) the location of the citizen huts

**Comment by Diablo088** [comment]
'minecolonies_compatibility:citizen_inventory
