### ISSUE TITLE
Deliveryman hangs up at Citizen Huts

### ISSUE THREAD

**Issue by NonplussedUltra** [ldtteam/minecolonies#2983]
Version: minecolonies-1.12.2-0.10.7-RELEASE-universal

### Expected behavior
- Deliveryman enters Citizen Huts, does his thing, and leaves.

### Actual behaviour
- Deliveryman enters Citizen Huts, and stares at the Citizen Hut block forever. This only happens with Citizen Huts; all other buildings work normally.
- Refreshing/resetting the colony using commands appears to have no effect.

### Steps to reproduce the problem
1. Follow Deliveryman until he tries to enter a Citizen Hut.
2. Watch Deliveryman freeze up while looking at the hut block.

**Comment by Raycoms** [comment]
Does this citizen hut have a lot of chests?

Am Di., 16. Okt. 2018 um 18:05 Uhr schrieb NonplussedUltra <
notifications@github.com>:

**Comment by NonplussedUltra** [comment]
No, it has only the Citizen Hut block, no other chests. This happens with at least two different huts in the colony. Here's the log; I believe you'll find the error at timestamp 15:42:22.

[2018-10-16-4.log.gz](https://github.com/ldtteam/minecolonies/files/2484956/2018-10-16-4.log.gz)

**Comment by Raycoms** [comment]
Same issue as #2982
