### ISSUE TITLE
Shepherd skin is broken.

### ISSUE THREAD

**Issue by bonzai1102** [ldtteam/minecolonies#2985]
### Minecolonies version

Version:  minecolonies-1.12.2-0.10.11-ALPHA-universal

### Expected behavior

- 

### Actual behaviour

- The Shepherd skin ist broken in the latest alpha.

![2018-10-17_20 00 12](https://user-images.githubusercontent.com/20872116/47107137-d2bed480-d248-11e8-9764-42fe679ab750.png)

### Steps to reproduce the problem

1. Hire a Shepherd.
2. When you fire him, he gets his normal skin.

**Comment by Raycoms** [comment]
Thanks for reporting it, pushed a hotfix
