### ISSUE TITLE
Builders stop Building Barracks- BUG REPORT

### ISSUE THREAD

**Issue by issuecreator** [ldtteam/minecolonies#2987]
### Minecolonies version

Version: minecolonies-1.12.2-0.10.7-RELEASE

### Expected behavior

The builders would keep building the barracks as normal

### Actual behavior

In the process of building the actual barracks, the builders just stop after digging the plus sign shaped hole, and I have to cancel the build and build something over it

### Steps to reproduce the problem

1. Make a creative mode world
2. make the builders not require any materials from you
3. Have the builders build the barracks
4. ...and they stop building them

**Comment by Raycoms** [comment]
Are you in a superflat world?

**Comment by Raycoms** [comment]
Similar to: https://github.com/ldtteam/minecolonies/issues/3005
