### ISSUE TITLE
Monster egg required for Dark Oak Barracks (level 3)

### ISSUE THREAD

**Issue by DarVillous** [ldtteam/minecolonies#2991]
level 3 of the dark oak barracks contains a chiseled stone monster egg block making it impossible to build in survival without other mods.
### Minecolonies version

Version: 1.12.2-0.10.8-Alpha-universal

### Expected behavior
To not need to cheat in a block to level up the building.

### Actual behaviour
I am unable 
### Steps to reproduce the problem

1. build barracks in survival
2. level it up to 2
3. level it up to 3
4. ponder how to get that non-craft-able block.

**Comment by Raycoms** [comment]
Fixed
