### ISSUE TITLE
Window Position Upgraded Double Storage Rack

### ISSUE THREAD

**Issue by bonzai1102** [ldtteam/minecolonies#2994]
### Minecolonies version

Version:  No specific

### Expected behavior

- 

### Actual behaviour

- The Position of an upgraded Double Storage Rack collides with JEI.

![2018-10-22_14 45 24](https://user-images.githubusercontent.com/20872116/47293624-e97b7780-d60a-11e8-9cbd-63851cdf5ae8.png)

### Steps to reproduce the problem

1. Ugrade Storage with Block of Emerald.
2. Open a double Storage Rack.

**Comment by Raycoms** [comment]
Yeah, that will be fixed with the new GUI rework
