### ISSUE TITLE
Smeltery not an option in the building tool

### ISSUE THREAD

**Issue by FirzenDark** [ldtteam/minecolonies#3001]
### Minecolonies version

Version: 1.10.2-0.9.7587

### Expected behavior

- Using the building tool to place the smeltery

### Actual behaviour

- When I use the building tool I do not see the smeltery in the selection.

**Comment by Raycoms** [comment]
You need to have the smeltery chest for that in the inventory. But not sure
if we ported that worker back to 1.10.2.

>

**Comment by FirzenDark** [comment]
I did build the smeltery chest but cannot see the smeltery in the building tool

**Comment by Raycoms** [comment]
I just checked, the smelter exists in 1.10

Am Mi., 24. Okt. 2018 um 02:12 Uhr schrieb Ray Neiheiser <
ray.neiheiser@gmail.com>:

> You need to have the smeltery chest for that in the inventory. But not
> sure if we ported that worker back to 1.10.2.
>
>>

**Comment by Raycoms** [comment]
when you have the smeltery in your inv, can't you see it?

Am Mi., 24. Okt. 2018 um 02:14 Uhr schrieb FirzenDark <
notifications@github.com>:

**Comment by FirzenDark** [comment]
It is in my inventory but it doesn't show as a item in the building tool selection. I can see all the other building chests.

**Comment by Raycoms** [comment]
Ah, it's that weird bug then


Am Mi., 24. Okt. 2018 um 02:25 Uhr schrieb FirzenDark <
notifications@github.com>:

**Comment by FirzenDark** [comment]
Is there a fix to this?

**Comment by Raycoms** [comment]
Unfortunately not, it would break all the existing smelters. (1.10 has some differences to 1.12 with file namings)

**Comment by Raycoms** [comment]
this is fixed in 1.12 why don't you play in 1.12, it has a bunch of new workers as well
