### ISSUE TITLE
Error on Building Townhall

### ISSUE THREAD

**Issue by Thetawaves666** [ldtteam/minecolonies#3006]
### Minecolonies version

Version: minecolonies-1.12.2-0.10.26-BETA-universal

### Expected behavior

- Being able to build a 2nd Colony with a different name on my PJ on my SinglePlayerMap.

### Actual behaviour

- The 2nd Colony does not spawn any of the 4 inicial citizen.

### Steps to reproduce the problem

1. Spend 420 (joke aside) days in-game building in survival a colony.
2. Get eventually bored and start building a 2nd colony, this time on creative cuz lazy ass.
3. Fly far enough and place the TownHall, 2 Builder's Hut and Instabuild a single house.
4. No a single citizen.

I will attach some pics here.

2nd (new) Colony.
![2018-10-25_16 25 49](https://user-images.githubusercontent.com/37487971/47525483-c30c4500-d873-11e8-8e55-dee6490b48ba.png)
![2018-10-25_16 23 56](https://user-images.githubusercontent.com/37487971/47525484-c3a4db80-d873-11e8-98f0-df49425607ec.png)

1rs (old) Colony
![2018-10-25_16 24 48](https://user-images.githubusercontent.com/37487971/47525486-c3a4db80-d873-11e8-80a6-350b9055dc9e.png)

**Comment by Raycoms** [comment]
Not sure but is the 2nd colony townhall chest in the ground? the colonists
need a bit of space around the townhall to spawn.

Am Do., 25. Okt. 2018 um 16:44 Uhr schrieb Thetawaves666 <
notifications@github.com>:

**Comment by Thetawaves666** [comment]
A little bit. But it does not change the fact that the Townhall has a 0/0

![2018-10-25_18 40 49](https://user-images.githubusercontent.com/37487971/47531990-877a7680-d885-11e8-9d30-91cdcfd40739.png)

Anyway, i will clean the area a bit.

...

Omg it worked i fell so dumb. Thanks.
![2018-10-25_18 42 05](https://user-images.githubusercontent.com/37487971/47532043-b1339d80-d885-11e8-92c9-c16913bc9069.png)


Anyway, the 0/0 may lead to confusion. Maybe a "tip" on the "print help messages" when placing the TownHall may help?

**Comment by Raycoms** [comment]
I just wrote some code I'll merge soon which notifies the player that there
is not enough space =)

Am Do., 25. Okt. 2018 um 18:51 Uhr schrieb Thetawaves666 <
notifications@github.com>:
