### ISSUE TITLE
Citizens raise from the dead

### ISSUE THREAD

**Issue by cjser** [ldtteam/minecolonies#3007]
When a colonie member dies add a tomb with the inventory. The deliverie men can take the items in them and that way you dont lose everything

**Comment by Raycoms** [comment]
Planned, with a gravedigger worker =)

Am Do., 25. Okt. 2018 um 21:08 Uhr schrieb cjser <notifications@github.com>:

**Comment by ArodSnaux** [comment]
On the full moon they should rise from the dead, and if you have a certain magic item, you should also be able to bring them back =)

**Comment by Raycoms** [comment]
#404 duplicate
