### ISSUE TITLE
Endless sleep

### ISSUE THREAD

**Issue by MrVirtualis** [ldtteam/minecolonies#3009]
### Minecolonies version
Version: 0.10.27 release

### Expected behavior
At sunrise/day everyone gets back to work

### Actual behaviour
Colonists that have a bed stay in bed, all others stay in the townhall, as if it was night.
Repeatedly setting the time and going to sleep does not resolve the problem.
[edit] Nor does restarting the game.

This may or may not be triggered by sleeping in a sleeping bag (mod: [comforts](https://minecraft.curseforge.com/projects/comforts)) in a citizens hut. (Maybe test with a normal bed, that is not part of the hut itself first).

Since my colony is now stuck in sleep-mode, I can't really try to reproduce the bug, without building a new colony in a new world.

**Comment by Raycoms** [comment]
Maybe it's because there is a barbarian raid coming in?

>

**Comment by MrVirtualis** [comment]
I can check it, but then, why would they go to sleep and "never wake up"?

**Comment by Raycoms** [comment]
They stay asleep while there are barbarians in the village

Am Fr., 26. Okt. 2018 um 10:24 Uhr schrieb Lars <notifications@github.com>:

**Comment by MrVirtualis** [comment]
> Maybe it's because there is a barbarian raid coming in?
> […](#)

It seems this was the issue. There was a barbarian hiding somewhere.
Still, I think it's strange that they just stay in bed when this happens.
Plus/Alternatively, a message would help, to know this is the reason they are not doing anything.
