### ISSUE TITLE
Suggestion: Tree Farm

### ISSUE THREAD

**Issue by BonaireDreams** [ldtteam/minecolonies#3010]
Suggestion: Tree Farms for Lumberjack
Size would be about the same size as the farmers farm. Need to craft a "stump with axe" which is the central marker (similar to the scarecrow) When placing the effected area is highlighted. In lumberjack hut you can designate fields for certain trees.  1 for oak and birch, 1 for spruce, etc. Lumberjack will only plant and chop trees in the field area if there is one. If there is no field lumberjack works in their current state.

This would allow t use lumberjacks to clear land, chop trees, but then have them only work a certain tree farm as you get your colony established so they don't chop down trees you want to keep, or plant in areas you don't want them.

**Comment by Rosomah** [comment]
You can place a cobblestone under the trees you don't want the lumberjack to take down.
And they only plant a tree at the exact spot they cut it down and it's the same type that was cut down.

**Comment by BonaireDreams** [comment]
Thanks, I did not know that. I still it would be good to have a working area we can specify for the lumberjack so he has an area where he plants and harvests trees. I also don't want him randomly planting trees in my village area.
