### ISSUE TITLE
Happiness is not recovering

### ISSUE THREAD

**Issue by Rosomah** [ldtteam/minecolonies#3011]
Version: 
 minecolonies-1.12.2-0.10.28-ALPHA

### Expected behavior
I accidentally killed a citizen with my epic sword and the happiness dropped to 1.
The happiness should then rise every day by a certain number and to a certain number.

### Actual behaviour
The happiness is at 1 for 3 days now.

Do I just need to wait a little longer or what?

**Comment by Raycoms** [comment]
Depending on your colony it may or may not (depending how happy your citizens are, there are some indications in the townhall and in the GUIs of the citizen)
