### ISSUE TITLE
Barracks dosent't working

### ISSUE THREAD

**Issue by KacpixXx** [ldtteam/minecolonies#3013]
### Minecolonies version

Version: 

### Expected behavior

- 

### Actual behaviour

- 

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit

**Comment by ArodSnaux** [comment]
I had the same problem... update your Forge to the latest, Barracks uses a new command in it and crashes if Forge is not latest

**Comment by PoroUsedSnax** [comment]
Yes, update forge if it isn't already one of the latest, if the problem persists after that feel free to reopen this issue
