### ISSUE TITLE
Adding Towers  CTDs / Destroys World

### ISSUE THREAD

**Issue by ArodSnaux** [ldtteam/minecolonies#3017]
Version:  minecolonies-1.12.2-0.10.27-RELEASE-universal.jar

When placing a GuardTower chest, or when a BarracksTower is auto-deployed by a builder, MC will CTD and the world becomes unrecoverable until MineColonies is uninstalled.

Also have seen two builders seal themselves in floors and suffocate in this build, but then again I am building at 1-tick speed with auto-supply so this might not affect normal users.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  MovingWorldCore (Moving World.jar)
  llibrary (llibrary-1.7.9-1.12.2.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63 (1).jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 10/28/18 1:11 AM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraftforge.registries.IForgeRegistry.getValuesCollection()Ljava/util/Collection;
	at com.minecolonies.coremod.colony.buildings.AbstractBuildingGuards.calculateMobs(AbstractBuildingGuards.java:839)
	at com.minecolonies.coremod.colony.buildings.AbstractBuildingGuards.serializeToView(AbstractBuildingGuards.java:315)
	at com.minecolonies.coremod.network.messages.ColonyViewBuildingViewMessage.<init>(ColonyViewBuildingViewMessage.java:40)
	at com.minecolonies.coremod.colony.managers.BuildingManager.lambda$sendBuildingPackets$1(BuildingManager.java:464)
	at com.minecolonies.coremod.colony.managers.BuildingManager$$Lambda$605/1356582452.accept(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1540)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at com.minecolonies.coremod.colony.managers.BuildingManager.sendBuildingPackets(BuildingManager.java:464)
	at com.minecolonies.coremod.colony.managers.BuildingManager.sendPackets(BuildingManager.java:153)
	at com.minecolonies.coremod.colony.managers.ColonyPackageManager.updateColonyViews(ColonyPackageManager.java:183)
	at com.minecolonies.coremod.colony.managers.ColonyPackageManager.updateSubscribers(ColonyPackageManager.java:154)
	at com.minecolonies.coremod.colony.Colony.onServerTick(Colony.java:623)
	at com.minecolonies.coremod.colony.ColonyManager.onServerTick(ColonyManager.java:689)
	at com.minecolonies.coremod.event.FMLEventHandler.onServerTick(FMLEventHandler.java:34)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_33_FMLEventHandler_onServerTick_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:264)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:710)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 663336272 bytes (632 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 104
	FML: MCP 9.42 Powered by Forge 14.23.1.2555 48 mods loaded, 48 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                                           | Version                  | Source                                            | Signature                                |
	|:--------- |:-------------------------------------------- |:------------------------ |:------------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft                                    | 1.12.2                   | minecraft.jar                                     | None                                     |
	| UCHIJAAAA | mcp                                          | 9.42                     | minecraft.jar                                     | None                                     |
	| UCHIJAAAA | FML                                          | 8.0.99.99                | forge-1.12.2-14.23.1.2555.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                                        | 14.23.1.2555             | forge-1.12.2-14.23.1.2555.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | com.elytradev.movingworld.common.asm.coremod |                          | minecraft.jar                                     | None                                     |
	| UCHIJAAAA | backpack                                     | 3.0.1                    | Backpack.jar                                      | None                                     |
	| UCHIJAAAA | biomesoplenty                                | 7.0.1.2384               | Biomes O' Plenty.jar                              | None                                     |
	| UCHIJAAAA | bullseye                                     | 3.0.3                    | Bullseye-Mod-1.12.1.jar                           | None                                     |
	| UCHIJAAAA | codechickenlib                               | 3.1.5.331                | CodeChickenLib-1.12.2-3.1.5.331-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | customspawner                                | 3.11.3                   | Custom-Mob-Spawner-Mod-1.12.2.jar                 | None                                     |
	| UCHIJAAAA | movingworld                                  | 1.12-6.342               | Moving World.jar                                  | None                                     |
	| UCHIJAAAA | davincisvessels                              | @DVESSELSVER@            | Davinci's Vessels.jar                             | None                                     |
	| UCHIJAAAA | dldungeonsjdg                                | 1.11.1                   | DoomlikeDungeons-1.11.1-MC1.12.2.jar              | None                                     |
	| UCHIJAAAA | exlinetweaks                                 | 1.0                      | exlinetweaks-1.0.jar                              | None                                     |
	| UCHIJAAAA | grapplemod                                   | 1.12.2-v10               | Grappling hook mod.jar                            | None                                     |
	| UCHIJAAAA | gravestone                                   | 1.10.1                   | Gravestone Mod.jar                                | None                                     |
	| UCHIJAAAA | waila                                        | 1.8.26                   | Hwyla-Mod-1.12.2.jar                              | None                                     |
	| UCHIJAAAA | ichunutil                                    | 7.1.4                    | iChunUtil.jar                                     | None                                     |
	| UCHIJAAAA | infernalmobs                                 | 1.7.3                    | InfernalMobs-1.12.jar                             | None                                     |
	| UCHIJAAAA | inventorytweaks                              | 1.63+release.109.220f184 | InventoryTweaks-1.63 (1).jar                      | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJAAAA | jei                                          | 4.8.5.138                | jei_1.12.2-4.8.5.138.jar                          | None                                     |
	| UCHIJAAAA | journeymap                                   | 1.12.2-5.5.2             | journeymap-1.12.2-5.5.2.jar                       | None                                     |
	| UCHIJAAAA | llor                                         | 1.1.4-mc1.12             | Light Level Overlay Reloaded.jar                  | None                                     |
	| UCHIJAAAA | llibrary                                     | 1.7.9                    | llibrary-1.7.9-1.12.2.jar                         | None                                     |
	| UCHIJAAAA | lostcities                                   | 2.0.5                    | lostcities-1.12-2.0.5.jar                         | None                                     |
	| UCHIJAAAA | lostsouls                                    | 1.1.4                    | lostsouls-1.12-1.1.4.jar                          | None                                     |
	| UCHIJAAAA | lycanitesmobs                                | 1.20.3.1 - MC 1.12.2     | LycanitesMobsComplete+1.20.3.1+[1.12.2].jar       | None                                     |
	| UCHIJAAAA | arcticmobs                                   | 1.20.3.1 - MC 1.12.2     | LycanitesMobsComplete+1.20.3.1+[1.12.2].jar       | None                                     |
	| UCHIJAAAA | demonmobs                                    | 1.20.3.1 - MC 1.12.2     | LycanitesMobsComplete+1.20.3.1+[1.12.2].jar       | None                                     |
	| UCHIJAAAA | desertmobs                                   | 1.20.3.1 - MC 1.12.2     | LycanitesMobsComplete+1.20.3.1+[1.12.2].jar       | None                                     |
	| UCHIJAAAA | elementalmobs                                | 1.20.3.1 - MC 1.12.2     | LycanitesMobsComplete+1.20.3.1+[1.12.2].jar       | None                                     |
	| UCHIJAAAA | forestmobs                                   | 1.20.3.1 - MC 1.12.2     | LycanitesMobsComplete+1.20.3.1+[1.12.2].jar       | None                                     |
	| UCHIJAAAA | freshwatermobs                               | 1.20.3.1 - MC 1.12.2     | LycanitesMobsComplete+1.20.3.1+[1.12.2].jar       | None                                     |
	| UCHIJAAAA | infernomobs                                  | 1.20.3.1 - MC 1.12.2     | LycanitesMobsComplete+1.20.3.1+[1.12.2].jar       | None                                     |
	| UCHIJAAAA | junglemobs                                   | 1.20.3.1 - MC 1.12.2     | LycanitesMobsComplete+1.20.3.1+[1.12.2].jar       | None                                     |
	| UCHIJAAAA | mountainmobs                                 | 1.20.3.1 - MC 1.12.2     | LycanitesMobsComplete+1.20.3.1+[1.12.2].jar       | None                                     |
	| UCHIJAAAA | plainsmobs                                   | 1.20.3.1 - MC 1.12.2     | LycanitesMobsComplete+1.20.3.1+[1.12.2].jar       | None                                     |
	| UCHIJAAAA | saltwatermobs                                | 1.20.3.1 - MC 1.12.2     | LycanitesMobsComplete+1.20.3.1+[1.12.2].jar       | None                                     |
	| UCHIJAAAA | shadowmobs                                   | 1.20.3.1 - MC 1.12.2     | LycanitesMobsComplete+1.20.3.1+[1.12.2].jar       | None                                     |
	| UCHIJAAAA | swampmobs                                    | 1.20.3.1 - MC 1.12.2     | LycanitesMobsComplete+1.20.3.1+[1.12.2].jar       | None                                     |
	| UCHIJAAAA | minecolonies                                 | 1.12.2-0.10.27-RELEASE   | minecolonies-1.12.2-0.10.27-RELEASE-universal.jar | None                                     |
	| UCHIJAAAA | mocreatures                                  | 12.0.4                   | Mo-Creatures-1.12.2.jar                           | None                                     |
	| UCHIJAAAA | ruins                                        | 16.9                     | Ruins Spawning System.jar                         | None                                     |
	| UCHIJAAAA | supertnt                                     | 1.0.0                    | SuperTNT-1.12.2-1.0.0.jar                         | None                                     |
	| UCHIJAAAA | torcharrowsmod                               | 1.12.1-3                 | torcharrows-1.12.1-3.jar                          | None                                     |
	| UCHIJAAAA | torched                                      | 7.0.0                    | Torched-Mod-1.12.2.jar                            | None                                     |
	| UCHIJAAAA | bspkrscore                                   | at_0.9                   | Treecapitator.jar                                 | None                                     |
	| UCHIJAAAA | treecapitator                                | at_0.9                   | Treecapitator.jar                                 | None                                     |

	Loaded coremods (and transformers): 
MovingWorldCore (Moving World.jar)
  
llibrary (llibrary-1.7.9-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
Inventory Tweaks Coremod (InventoryTweaks-1.63 (1).jar)
  invtweaks.forge.asm.ContainerTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Snaux'/4116, l='TatersPrecious', x=59.99, y=74.04, z=192.67]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by someaddons** [comment]
your forge version is too old and doesnt have said Method yet, try updating it!
