### ISSUE TITLE
Dark oak Restaurant wrong menu

### ISSUE THREAD

**Issue by Calibos** [ldtteam/minecolonies#3018]
### Minecolonies version

Version:  0.10.29-ALPHA

### Expected behavior

Dark Oak restaurant builds 1-5 found in tabs Rest- Dark Oak - Levels

- 

When I wish to build a restaurant I would select that tab, then dark oak, then the first level, and place the building

### Actual behaviour

- 
When I wish to place a Dark oak restaurant I go to decorations dark oak, then choose the first level

![darkoakrest](https://user-images.githubusercontent.com/44527515/47616279-ccfe9580-da77-11e8-97cd-e3f886d133a3.png)

### Steps to reproduce the problem

right click block with wand, go to decorations, select dark oak tab...
 
1. 
2. 
3. 
4. ... Profit

**Comment by Raycoms** [comment]
Then something went wrong in the process of scanning
I'll take a look at it

Am So., 28. Okt. 2018 um 10:10 Uhr schrieb Calibos <notifications@github.com

**Comment by Raycoms** [comment]
Pushed a fix
