### ISSUE TITLE
Citizen disappeared and Town Blocks are no longer accessible

### ISSUE THREAD

**Issue by xTheDawg** [ldtteam/minecolonies#3021]
Version: 1.12.2-0.9.4-RELEASE

### Expected behavior

Citizens existing as the day before.
Players are able to access the GUI of building blocks (f.e. Town Hall Block)

### Actual behaviour

Citizens disappeared from one day to another and Building Blocks are no longer accessible.

### Steps to reproduce the problem

No known steps to reproduce the problem but restoring to an older backup version like in the following post didn't work.
https://github.com/ldtteam/minecolonies/issues/1964

**Comment by Raycoms** [comment]
is there the loadBackup command already in this version?

Am So., 28. Okt. 2018 um 15:53 Uhr schrieb xTheDawg <
notifications@github.com>:

**Comment by xTheDawg** [comment]
I updated the mod to version 1.12.2-0.10.27. I guess the command should be available in this version.
How should i use it or why would the result be different to the suggestion in the other post?

**Comment by Raycoms** [comment]
the new system is more reliable than the old system. If you execute the command it should reload the colony.

**Comment by xTheDawg** [comment]
How should the command be used? In the version mentioned above I only have the "backup" Command available and not the loadBackup. The Command doesn't seem to take any additional arguments like restore..
![minecolonies](https://user-images.githubusercontent.com/27952293/47735708-5aefa180-dc6d-11e8-80f6-f9d102b0125a.PNG)

**Comment by Raycoms** [comment]
./mc colony loadBackup

Am Di., 30. Okt. 2018 um 14:02 Uhr schrieb xTheDawg <
notifications@github.com>:

**Comment by xTheDawg** [comment]
The command asks for a argument "colony:integer" i guess that's the colony ID. Sadly with /mc colony info it says that there was no colony found with owner XY. Is there another way to find out the ID or what is the default Colony ID since it was the only colony created on the server.. Thanks in advance
![backup](https://user-images.githubusercontent.com/27952293/47751117-3efdf700-dc91-11e8-8fc3-f03eeb54993f.PNG)

**Comment by PoroUsedSnax** [comment]
Easiest way to find a colonies' ID is to use `/mc whereami`, if you're struggling with command syntax at all please refer to #3025, I just put a quick description of how they work there

**Comment by xTheDawg** [comment]
/mc whereami tells me that "there are no colonies close at all"

**Comment by Raycoms** [comment]
If you're alone on this world the ID is 1

**Comment by xTheDawg** [comment]
I tried the command: "/mc colony loadBackup 1 0". Sadly it still gives me the same answer as in the last screenshot posted. "missing required parameter colony". Do you have any other ideas on how to restore the colony? Is manually restoring the file not a good option? Tho i already tried that.

**Comment by Raycoms** [comment]
Mc colony loadBackup colony: 1 dimension: 0

**Comment by xTheDawg** [comment]
Ok thanks now the command executed but the problem still remains.. Do I need to do afterwards like restarting the server or do I need to specify which backup it should load?

**Comment by Raycoms** [comment]
What does the log say after doing that?
