### ISSUE TITLE
Operator overrides colony protection

### ISSUE THREAD

**Issue by ghost** [ldtteam/minecolonies#3023]
While I admire this, it should be off by default and should NOT prevent operators from interacting with blocks.

**Comment by PoroUsedSnax** [comment]
The colony protection is a rather large and important system and the mod is used on quite a few servers, having it disabled by default may mean people miss out on such a feature.

If you're having issues with things unable to interact with the colony, presuming machines and such, check in the town hall for the events section, there you will be able to add that machine's fakePlayer to the colony, allowing it to interact

**Comment by ghost** [comment]
Maybe it would be a good idea to add more granular control of the protection rather than an all-or-nothing approach. Letting each mayor turn it on or off at will would be a good idea, along with control of what actions outsiders can and can't do. My stance on OP override still stands though. As it is, if an issue occurs within a protected colony, I cannot fix it, and have to completely remove the colony, which is undesirable.

All that said, I am impressed with how thorough the protection is, much more than any other mod I've come across.

**Comment by Raycoms** [comment]
In the townhall you can let people turn on/off in a very granular level.

Am Di., 30. Okt. 2018 um 06:45 Uhr schrieb DemonfangArun <
notifications@github.com>:

**Comment by ghost** [comment]
Ah, so you can. I'm new to this mod. That just leaves an OP override

On the same topic, any reason the permission scepter is not craftable? It seems rather important!

**Comment by marchermans** [comment]
OPs override by Default. Only depends on the Server specific configuration.

**Comment by ghost** [comment]
the OP level for minecolonies is set to 3, which is less than the OP level of 4 on the server, yet I cannot do anything to other colonies.

**Comment by marchermans** [comment]
@Raycoms This is not an issue on our server. I am not sure which way around the logic works.

**Comment by ghost** [comment]
> 
> 
> @Raycoms This is not an issue on our server. I am not sure which way around the logic works.

I'm going to assume this was misdirected. The logic works such that higher levels override lower levels. It is possible that maybe this mod is mis-reading the op level such that because this mod is not set for 4 it's acting like there's no OP instead of reading that the server OPs have a higher level and allowing all OP actions. Strangely enough I do have access to commands.

**Comment by marchermans** [comment]
No it was not misdirected. I meant to ask @Raycoms how the logic internally works. Since he has more experience with the system then I do.

**Comment by Raycoms** [comment]
No, it is disable to act in colonies as an admin. But admins can do /mc
colony addOfficer to add themselves to the colony to do things.

Am Do., 1. Nov. 2018 um 12:26 Uhr schrieb DemonfangArun <
notifications@github.com>:

**Comment by marchermans** [comment]
Okey that closes the issue then.

**Comment by ghost** [comment]
The problem is that that does not give ALL permissions by default. I'll just continue on with the protection function disabled since it's an impediment to server moderation.

**Comment by marchermans** [comment]
Ray what is the reason for it being disabled?

**Comment by marchermans** [comment]
@Raycoms ^

**Comment by Raycoms** [comment]
We can add an op level check to it, no problem

**Comment by marchermans** [comment]
We should do that then. Something for a newbe :dagger:

**Comment by ghost** [comment]
> 
> 
> We should do that then. Something for a newbe 🗡

Hey now. I just believe in simple no-knobs server administration :)

**Comment by Raycoms** [comment]
Closed in favor of joint issue.

**Comment by bugescape** [comment]
its so retarded that you code it and stop server op form interacting with colonies LOL, fucking dumb cunt
