### ISSUE TITLE
Spruce Library Level 4 Requires Cobblestone Monster Egg

### ISSUE THREAD

**Issue by Enverex** [ldtteam/minecolonies#3024]
Version: Current GIT.

The level 4 Spruce Library (the middle sized, darker looking library) appears to require monster egg cobble to build.

![image](https://user-images.githubusercontent.com/958670/47676066-7f874300-dbb3-11e8-985e-d898c307d8ae.png)

(this one)
![image](https://user-images.githubusercontent.com/958670/47676135-ac3b5a80-dbb3-11e8-838e-1c87283ece85.png)

**Comment by johnfal92** [comment]
This is the Medieval Spruce Library to be clear: 
Still an issue in minecolonies- 1.12.2-0.10.156-ALPHA-universal

**Comment by lunadragnstar** [comment]
Fixed and rescanned
