### ISSUE TITLE
Commands with ID don't work in SinglePlayer

### ISSUE THREAD

**Issue by ArodSnaux** [ldtteam/minecolonies#3025]
Even simple commands like /mc colonies info 1  are just not working for me. Documentation on them is poor or nonexistant, can someone tell me what is going on? Is there some uber-command to activate them? I am not running mc as a server, I'm just playing the game locally.

I'm pretty sure I turned on all the enable-flags in the configs. All I really want to do is Claim my current town to a much larger radius... my ID of course is 1. So I type "/mc colony claim 1 20 true" and it complains I need to enter the id.... am I doing this wrong or is it bugged in single player?

**Comment by PoroUsedSnax** [comment]
You need to use the commands as such: `/mc colony info colony: 1` that `colony:` part with the space is important, and is required for all commands, in it's own way. (So, for claiming for example, you would use `/mc colony claim colony: 1 range: 20 add: true`) Using the commands runs a lot smoother through tab completion

On a side note regarding documentation, a new wiki is being worked on and is very near completion

**Comment by ArodSnaux** [comment]
That worked, thank you so much... and yes, a simple example of what you ACTUALLY need to type on the wiki would go lightyears towards making it more accessible. I had no idea named parameters were even possible in MC. =)

**Comment by Raycoms** [comment]
The new wiki is almost ready and will contain all this info

Am Di., 30. Okt. 2018 um 21:41 Uhr schrieb ArodSnaux <
notifications@github.com>:

**Comment by Thotly** [comment]
For anyone that needs help with this 4 years later, if you have dimensions on for your colonies type in the following
/mc colony claim colony: 1 dimension: 1 range: 20 add: true
