### ISSUE TITLE
Working Range for Town Hall - Not able to increase

### ISSUE THREAD

**Issue by TheOrionsun** [ldtteam/minecolonies#3028]
### Minecolonies version
Version: 1.12.2-0.10.27-RELEASE-universal - My game is a single player set to survival.

### Expected behavior
When changing the "workingRangeTownHall" in "gameplay-mod settings", from 200 to 1200 there is no change on how far out I can place a building. Currently I can not place anything over 90 blocks from the town hall table.

### Actual behaviour
No change to the colony build range.

N/A

### Steps to reproduce the problem

1. Set workingRangeTownHall over default.
2. Try to place building beyond 90-200 blocks.
3. Get message that you need to place closer to town hall.
4. ... Profit

Is this setting what I should be able to increase to have a larger colony?

Thank you for your time and your excellent Mod,

TheOrionsun

**Comment by Raycoms** [comment]
Yes, this is because this is stored in the colony already. You can adapt
this afterwards with the /mc colony claim range: newRangeInChunks add: true
colony: id command from the middle of your colony

Am Mi., 31. Okt. 2018 um 21:24 Uhr schrieb orionsun <
notifications@github.com>:

**Comment by TheOrionsun** [comment]
OK, not sure I am following you. 
What is an example of the /mc command if I want say 50 chunks?
I see the workingRangeTownHallChuncks setting in gameplay config, but I take it I cannot change it there?

**Comment by Raycoms** [comment]
the chunk setting there is for the new colonies, the command is for
existing colonies.

/mc colony claim range: 50 add: true colony: 1

Am Mi., 31. Okt. 2018 um 21:36 Uhr schrieb orionsun <
notifications@github.com>:

**Comment by TheOrionsun** [comment]
ok, Thank you!

**Comment by TheOrionsun** [comment]
ok, tried that and I get the error:

/mineColonies colony claim <colony: integer> <dimension: integer> [range: integer] [add: boolean]: missing required parameter dimension

So I need dimension? is that all?

Thank you...

**Comment by Raycoms** [comment]
Yes dimension: 0

Am Mi., 31. Okt. 2018 um 22:02 Uhr schrieb orionsun <
notifications@github.com>:

**Comment by TheOrionsun** [comment]
kk ty

**Comment by TheOrionsun** [comment]
Ok, got it...format was a little different.

Added below for reference.

/mc colony claim range colony: 1 range: 50 dimension: 0 add: true

Thank you for your time Raycoms!

Please consider this issue resolved and close.
