### ISSUE TITLE
Fisherman fails to collect items

### ISSUE THREAD

**Issue by Calibos** [ldtteam/minecolonies#3029]
### Minecolonies version

Version: 
1.12.2-0.10.30-Alpha

### Expected behavior

When the fisherman fishes and catches something, he pulls it in, collects whatever he caught, continues fishing.
- 
Fishing behavior dark oak fisherman's hut (if that makes a difference)

### Actual behaviour

The fisherman fishes, and catches things on his line, when he reels it in, the item drops into the water below his feet.

- 

Fisherman ends up with a large pile of fish/items in the water below where he is standing.

### Steps to reproduce the problem

1. 
Build Fisherman's hut
2. 
Give fisherman fishing rod
3. 
Watch items pile up below him
![fisherman1](https://user-images.githubusercontent.com/44527515/47910067-e2e0d180-de4e-11e8-9c92-d7166432b0c5.png)
![fisherman2](https://user-images.githubusercontent.com/44527515/47910073-e8d6b280-de4e-11e8-88f2-84316cc23e85.png)

4. ... Profit

**Comment by Raycoms** [comment]
We need to give him a bit more range
