### ISSUE TITLE
Log in Blocks me from my colony!!!

### ISSUE THREAD

**Issue by melstar66743** [ldtteam/minecolonies#3030]
### Minecolonies version
1.12.02

Version: 

### Expected behavior

- I would be able to log back in and continue working on the colony I had created the evening prior.

### Actual behaviour
I logged in and it states I do not have permission to do that in a colony when I tried to open a building chest. Surprised, I went to town hall, but doors would not open, stating I did not have permission. I broke the doors, but it was as if there was an invisible barrier, and the doors respawned a few seconds later.  What's going on????

### Steps to reproduce the problem

1. Create buildings fully built at least level 1 in colony created
2. save and exit game
3. reenter created world, use crystal orb respawned in hand as always. Choose same options as before.
4. Attempt to access buildings from created colony and building chests.

**Comment by Raycoms** [comment]
What version do you use? did you try /mc colony refresh colony: 1

Am Fr., 2. Nov. 2018 um 12:47 Uhr schrieb melstar66743 <
notifications@github.com>:

**Comment by Raycoms** [comment]
reopen when not fixed. Upgrading to a newer version might solve it as well.
