### ISSUE TITLE
Issue with dark oak framed blocks in singleplayer

### ISSUE THREAD

**Issue by ChezaHoD** [ldtteam/minecolonies#3031]
### Minecolonies version

Version:  1.12.2-0.9.125-ALPHA-universal (Life in the Village)

### Expected behavior

Framed blocks connect/place
- 

### Actual behaviour

Placing "top, bottom and center" pieces of framed dark oak frames. Mouse over to see "Error" show. If a block is touched (Broken or placed) on that block the game crashes.
- 

5G5vCyIDa9N3WiY2x8
### Steps to reproduce the problem

1.  Place bottom dark oak frame
2.  Place top dark oak frame 
3.  Place the middle and get a "Error" greyed out when mousing over. Place next block
4. ... Profit Crash

**Comment by Raycoms** [comment]
Has been fixed in the more recent versions, please update.
