### ISSUE TITLE
Request: All players in LAN can see requests in the clipboard

### ISSUE THREAD

**Issue by Ktanaqui** [ldtteam/minecolonies#3033]
Please add the ability for all players in LAN to see the requests from the Colony via the clipboard.

**Comment by Raycoms** [comment]
Never tested this, will have to check if this is really an issue, never tested it.

**Comment by mcDandy** [comment]
does not work on server either properly.

**Comment by Raycoms** [comment]
People have to shift-right click a colony chest of the colony they want it to work with, did you try that?

**Comment by Raycoms** [comment]
Just walking into another colony with the clipboard does not work

**Comment by Ktanaqui** [comment]
Sorry - just got the notification that you replied. 
I will check with the SO to verify, but I'm almost certain that I had him try shift-clicking because that's what I had to do. (Verified that he did indeed Shift+Click) 

If it's any help, he also can't see the requests in the villagers' own menus either. I have him set as an Officer with all permissions allowed. (So, as an example, I have to supply all tools because those don't go to the chat and he can't see them.)

**Comment by Raycoms** [comment]
Please play multiplayer or single player, supporting lan is too difficult.
