### ISSUE TITLE
Couriers go to the warehouse and stand there constantly.

### ISSUE THREAD

**Issue by ZzylinN** [ldtteam/minecolonies#3034]
Couriers go to the warehouse and stand there constantly. Builder requests are not performed. Items from other buildings can not stand.
I tried to restart the courier, but as soon as he gets to the warehouse, it stops there.
Warehouse level 5.
Couriers (buildings) 4 levels.

minecolonies-1.12.2-0.10.33-ALPHA-universal
forge 1.12.2-14.23.5.2768
+ other mods

Map started on older versions of minecolonies-1.12.2.xxx

**Comment by Raycoms** [comment]
. /mc rs reset colony: 1

**Comment by ZzylinN** [comment]
> . /mc rs reset colony: 1

did not help. As soon as the couriers get to the warehouse. stop at the main warehouse unit and so stand all day.

**Comment by Raycoms** [comment]
is your colony id 1? can you send us the log?

Am So., 4. Nov. 2018 um 16:25 Uhr schrieb Sasha <notifications@github.com>:

**Comment by ZzylinN** [comment]
![2018-11-05_00 30 50](https://user-images.githubusercontent.com/34644142/47968336-c59c4500-e092-11e8-890b-1cb9699aa4ea.png)

**Comment by ZzylinN** [comment]
[log.txt](https://github.com/ldtteam/minecolonies/files/2546146/log.txt)

**Comment by Raycoms** [comment]
Will write a fix for this.

**Comment by ZzylinN** [comment]
Good. Thank.

**Comment by brekrome** [comment]
Hey, im having the same problem with basic resources in my warehouse. My couriers are staying put in their warehouse and not moving. I have all my supplies in the warehouse but they're just standing by the warehouse block

**Comment by MotionlessTrain** [comment]
Rather than resurrecting an issue from four years ago, could you make a new issue with more information, e.g. minecolonies version number, and whether someone is actually requesting something?
