### ISSUE TITLE
The miner not usd the iron pikeaxe

### ISSUE THREAD

**Issue by Hwarug** [ldtteam/minecolonies#3038]
I play the minecraft, the newest version ( 1.13. ).The miner says. I have need  pikaxe. 
The miner used minimum and maximum pikaxe level is iron. 
I gave it to him, the iron pikaxe, and he no going to down the mine.

Sorry, the my horrible englis.

**Comment by PoroUsedSnax** [comment]
You say you're playing on 1.13, do you mean 1.12? Playing 1.13 shouldn't be possible..

Either way, we need to know what **Minecolonies** version you're running
Do they have enough food? Do they have planks, wood slabs, cobble, ladders, torches, fences?

**Comment by Raycoms** [comment]
What is his building level?

Am Di., 6. Nov. 2018 um 06:10 Uhr schrieb Mark Fisher <
notifications@github.com>:

**Comment by Raycoms** [comment]
I believe your miner arrived at a block he can't mine with his current building level. So he wants an iron block for the block he has to mine, but can't use it yet. You gotta upgrade his hut to level 2.
