### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by eraser2011** [ldtteam/minecolonies#3041]
Version: minecolonies-1.12.2-0.10.37-ALPHA-universal.jar

### Expected behavior
Have a starting game
### Actual behavior
Game crashes on the startup process
### Steps to reproduce the problem
I tried updating the mod on the server, no crashes on the old versions 0.10.27 - 0.10.35. Sadly the newer ones doesn't work (.36 and .37).
The issue is only available on my server, no problems on my local game.
Logs:  
[crash-2018-11-06_19.33.31-server.txt](https://github.com/ldtteam/minecolonies/files/2554703/crash-2018-11-06_19.33.31-server.txt)
[2018-11-06-6.log](https://github.com/ldtteam/minecolonies/files/2554705/2018-11-06-6.log)

**Comment by Raycoms** [comment]
Thanks for reporting, just merged a hotfix.
