### ISSUE TITLE
Scout Worker

### ISSUE THREAD

**Issue by PoroUsedSnax** [ldtteam/minecolonies#3043]
Relative to #3042 

A scout worker can go out of the colony to claim new chunks for a colony, the player could be allowed to configure this size range (1 chunk, 2x2, 3x3, etc). 

But with that they will require materials (Armour, tools, food, potions, ingots/gems, building materials, etc) depending on the range selected and how far they have to go to claim, this list of materials will vary in what they need and how much of it.

**Comment by ArodSnaux** [comment]
I think something similar is already in the works, claiming territory is going to be dynamic, and based on where you place guard towers and/or barracks.

**Comment by PoroUsedSnax** [comment]
@ArodSnaux Yes, I'm well aware, which is why I referenced the issue regarding dynamic claiming, I was part of the discussion :D It's an idea as an extra to all that

**Comment by ArodSnaux** [comment]
It would be interesting if your scouts could encounter Barbarian tribes out in the wild that could be conquered, adding not only territory but new citizens that would need to be assimilated, or traded with etc.

**Comment by Raycoms** [comment]
Closed in favor of joint issue.
