### ISSUE TITLE
Construction enhancement #1

### ISSUE THREAD

**Issue by someaddons** [ldtteam/minecolonies#3044]
Seperate the building process into
**1. Cleaning/digging
2. Building the building**

For 1.  it probably makes sense to create a new hut/worker(e.g. a digger) for that task, 1. requires to be completed before 2. should be allowed to start. 

Make it compatible to be further split into even more detailed working steps

**Comment by Raycoms** [comment]
For that it would be good to

- [ ] Add a field to the workorders to add dependency to another work order
- [ ] Before assigning himself to an order a worker checks if the dependency is fulfilled
- [ ] Make the new worker
- [ ] Make the builder only claim the job if the new worker does not exist
- [ ] Make a button in the builder if he can claim the task if the new worker is busy
- [ ] Extend the work order to be able to stop and start after a certain task
(Work order could contain Start_task and End_task)

**Comment by Raycoms** [comment]
Closed in favor of joint issue.
