### ISSUE TITLE
[feature request] Construction enhancement #3

### ISSUE THREAD

**Issue by someaddons** [ldtteam/minecolonies#3046]
Seperate the Building process further into:

1. Cleaning/digging
2. Scaffolding
3. **Add local inventory to the building site which hold the required materials**
4. Building the building

After creating the scaffolding there will be local inventories created where the materials required for the building get delivered. Could be delivered by the Dman through requests(or a new hut that specifically gathers the building materials and takes them there?)
Could be split into multiple inventories, but handled as a combined storage internally. E.g. 

A stone pile as a storage crate:
![Image of stonepile](https://t3.ftcdn.net/jpg/00/70/31/84/160_F_70318436_9swp1dEg7IHr5fOnpwJ4l8gz9JbFhEih.jpg)
A wood pile as a storage crate:
![Image of woodpile](https://thumbs.dreamstime.com/z/pile-wooden-timber-planks-rasped-building-construction-floring-eps-illustration-white-background-44538772.jpg)

**Comment by Raycoms** [comment]
Depends on: https://github.com/ldtteam/minecolonies/issues/3045
- [ ] Create a storage block for this and storage tileEntity.
- [ ] let it place and register by the placing scaffolding worker
- [ ] Let the user builder it as a place to dump the items and let the builder use it as extended storage to search something (before he goes to search it in his building - only applies to builder not other structure ai workers)
- [ ] Let the builder request from there (will require request system rework)

**Comment by kreezxil** [comment]
This is very similiar to my suggestion I just posted at https://github.com/ldtteam/minecolonies/issues/3172 except mine doesn't require you to develop other code right off the bat, you can instead just work on the logistics of the mechanics. Then after that is tweaked introduce more alpha mayhem by making custom crates which would look extremely cool btw.

**Comment by Raycoms** [comment]
Closed in favor of joint issue.
