### ISSUE TITLE
Insta-Build Tool does not recognize CLAIM territory

### ISSUE THREAD

**Issue by ArodSnaux** [ldtteam/minecolonies#3047]
Version:  minecolonies-1.12.2-0.10.27-RELEASE-universal

The insta-build feature of the build tool (green clipboard icon), in Creative Mode, will only generate Worker Chests when used within the boundaries of the original city-size. If you expand city borders using CLAIM, for instance, it will still generate the building, but will not add the chest, even if it is in your inventory.

You can still however use it to create a work order, which DOES place the chest, and have the Builders create the Structure normally. So there is a workaround, albeit a very slow one.

**Comment by Raycoms** [comment]
After the claim command you have to unload and reload the freshly claimed
chunks or visit them to recognize it

**Comment by ArodSnaux** [comment]
I did that already, it still does not work. However after further testing it is apparent that the issue is with specific chunks in the radius surrounding the original territory. For instance, I cannot auto build a guard tower located at the FORMER Southwest (+1) chunk, yet it is able to build on the chunk further south and west of that one.  Likewise I have another one to the direct east on the original village center (again, east +1) that does not work, yet east +2 works. In the east+1 one, you also cannot drop the hut manually, yet you go to +2, and that one works.

Possible coincidence, but both these chunks are transitionals, one is forest->river and the other is forest-desert.

Then again its only a minor annoyance as you can still build there, its just that the building will go unused.
