### ISSUE TITLE
Feature Request: Nobility "workers"

### ISSUE THREAD

**Issue by ArodSnaux** [ldtteam/minecolonies#3048]
It would be cool to have a building like a "Noble's House"; a fancier version of the Citizen Hut that serves as  both Home AND Job for those assigned to live in it. 

As the building level increases, those living in it get more impressive costumes and some even get titles... Lord/Lady, Duke/Duchess, Baron, etc... Nobles basically just wander around town, maybe even gathering in small groups around waypoints to "chat". They add flavor.

Someone say Taxes???? If given a gold brick or gemstone, they will increase happiness and/or worker production in their area. If they don't get paid often enough, it has the opposite effect.  (Heck, maybe in a later version unhappy nobles even break off, form their own towns, and make war against the players)

I got the idea from how fancy the unemployed women look with their parasols and pinafores... its a shame they just get dingy uniforms once employed. Wouldn't it be nice to have a gentry class idly roaming the streets without constant complaining about being unemployed?

**Comment by TheStrato** [comment]
+1 for this.

**Comment by Raycoms** [comment]
Closed in favor of joint issue.
