### ISSUE TITLE
Game crashed

### ISSUE THREAD

**Issue by Rosomah** [ldtteam/minecolonies#3049]
Version: 
minecolonies-1.12.2-0.10.39-ALPHA-universal.jar

I was playing the game and went through 2 in game days. The first crash occurred while I was crafting something. I then reloaded the world and went on playing for 2 more minutes and the game crashed again. Since then, I'm not able to open the world again, it crashes every  time before loading the world.

[crash-2018-11-10_11.59.59-server.txt](https://github.com/ldtteam/minecolonies/files/2568331/crash-2018-11-10_11.59.59-server.txt)

**Comment by someaddons** [comment]
update your forge version, its missing the function used

**Comment by Rosomah** [comment]
Thanks.
