### ISSUE TITLE
Feature Request: STOP MOVING!!!!

### ISSUE THREAD

**Issue by ArodSnaux** [ldtteam/minecolonies#3050]
It would be awesome if we could tell Citizens to simply STOP MOVING so we can give them items or clear their inventory, see requests etc. This is particularly true of guards on patrol... I see a guy running around naked I want to give him armor and weapons and food, but by the time I'm done he's already run off before I can tell if he's even wearing it.

**Comment by PoroUsedSnax** [comment]
I would say this is already doable, just pause them for a moment in the manage workers GUI of their hut, then give them the items and unpause.

**Comment by ArodSnaux** [comment]
True but this does not work with unemployed or guards who are on patrol or in combat. My city has 250 people and growing, and doing a worker recall at city hall is like herding cats. I'm bumping into a similar large-city-problem where I want to manage housing and jobs... the city is too big to not have it on auto all the time, but also too big to run back to city hall to switch to manual for the occasional tweaking.

It would be nice to be able to, say, stop a farmer running across the map, hand him some seeds, some food, ask him where he lives and reassign him to a closer domicile, for instance.
