### ISSUE TITLE
Woodcutter stands after visiting the tavern. Аnd a little about the miner

### ISSUE THREAD

**Issue by ZzylinN** [ldtteam/minecolonies#3052]
The woodcutter visits the tavern and satisfies his hunger. After that stands in the tavern and does not return to the cutting down of trees.
The woodcutter's hut is located in another part of the colony from the tavern.

Version:
minecolonies-1.12.2-0.10.39-ALPHA-universal
forge 1.12.2-14.23.5.2768
other mods

Map started on older versions of minecolonies-1.12.2.xxx

PS: Also, couriers do not bring a survivalist pickaxe from the mod forestry (v1.12.2-5.8.2.354). This pick is available in both packaged and unpacked form. Although if you yourself bring the miner an unpacked pickaxe, then he begins to use it.

**Comment by ZzylinN** [comment]
couriers do not bring a survivalist pickaxe from the mod forestry (v1.12.2-5.8.2.354). This pick is available in both packaged and unpacked form. On the screen you can see that he asks for a pickaxe, although he has a pickaxe in his inventory.
![2018-11-17_23 54 05](https://user-images.githubusercontent.com/34644142/48664168-e6b65a00-eac4-11e8-8c9e-d5e79438ff53.png)
![2018-11-17_23 54 29](https://user-images.githubusercontent.com/34644142/48664169-e74ef080-eac4-11e8-8e95-ff6e2744463b.png)

**Comment by ZzylinN** [comment]
Version:
minecolonies-1.12.2-0.10.45-ALPHA-universal
forge 1.12.2-14.23.5.2768
other mods

**Comment by marchermans** [comment]
Please create a new issue.
