### ISSUE TITLE
Move the Borders

### ISSUE THREAD

**Issue by PestoPosta** [ldtteam/minecolonies#3053]
First sorry if this has been addressed else where, but is there any way to move the center of the town?

I've move my town hall so that it is more centered on my island, but most of my "town" is still off the island.

So is there any way to move my borders?

**Comment by Raycoms** [comment]
there is a command /mc colony claim colony: id range: num add: true
in the middle of the island it will claim it for you.

**Comment by PestoPosta** [comment]
Thanks much :)

**Comment by PestoPosta** [comment]
Ok, so the command seems to have given me the "It worked" message, however the borders do not seem to have moved? Am I missing something?

Thanks for your time, and thanks for the quick response. :)

**Comment by Raycoms** [comment]
The borders that render are static, they don't update (WIP). The actual
chunk claim should update though.

Am So., 11. Nov. 2018 um 18:51 Uhr schrieb PestoPosta <
notifications@github.com>:

**Comment by PestoPosta** [comment]
KK and thanks again :)
