### ISSUE TITLE
Restaurant Medieval Oak upgrade lvl 3 to 4 unknow item needed 

### ISSUE THREAD

**Issue by Ahima49** [ldtteam/minecolonies#3054]
Version: Minecraft version 1.12.2, minecolonie 0.10.27 RELEASE

Hi, i try to upgrade the restaurant from lvl 3 to lv 4.
Builder ask for me one item who doesn't exist, i have looking for it in Just enough item but nothing like that exist.
The item have an icon paper and who's name is "WANTED ! Alice Kyteler, witch..." (in fact, Alice Kyteler was a witch IRL)
When i go to the requires item list in the builder's hut, the item appears in green as if i have it, but when i click on the cross nothing happend.
The building are stopped.

Is it a bug or i have miss something ?

The screen shot : [https://drive.google.com/open?id=1beVluYQZsA8jFW3Wx6qSEUWb4ye1rgVI](url)

Thanks ; )

**Comment by ArodSnaux** [comment]
It evaluates to minecolonies:resourcesscroll which normally is a sort of clipboard for individual builders. NEI lists it as Resource-Scroll, which means  the Wanted bit is merely a renaming of it.

It can be crafted:

stick -buildertool - stick
stick - leather - stick
stick - leather - stick

And then perhaps renamed on an  anvil? But I agree, if its asking for it, its really kind of a bug.

**Comment by Ahima49** [comment]
Thanks a lot ArodSnaux !
I made an other resource-Scroll and without rename it in an anvil the builder accept it and finish the restaurant.
That strange because i tried many time to give him my first ressource scroll and he don't accept it.
I think that should be more explicit.
Have a good day, thanks for your help

**Comment by Ahima49** [comment]
What is the right way for mark this issue at resolved please ?
