### ISSUE TITLE
Custom schematic build issues

### ISSUE THREAD

**Issue by Wrsaith** [ldtteam/minecolonies#3055]
Issue we're having on our server. We can't build a schematic in most places inside the town limits but there is one corner of the town where it won't let use build schematic.

minecolonies-1.12.2-0.10.27-RELEASE-universal

Version: 

Schematic built.

{Server thread/error} [minecolonies]: handleDecoration: Could not build schematics/City Wall

we use the builders wander right click select custom schematic align it to previously build schematic of same schematic and click check box to accept and nothing happens, outline of schematic disappears, and throws above error on server window.

1. right click with builders wand
2. select schematic
3. click accept
4. nothing happens

**Comment by Raycoms** [comment]
in f3, what does it say there, is this chunk claimed by the colony?

Am So., 11. Nov. 2018 um 19:58 Uhr schrieb Wrsaith <notifications@github.com

**Comment by Wrsaith** [comment]
what in the f3 menu am I looking for? 
when I hold the builders wand it shows the blocks with torches that is the bounder of the minecolonie town and we are still inside them.

**Comment by marchermans** [comment]
Press f3 once

**Comment by Raycoms** [comment]
f3 tells you the colony you are in.

Am Mo., 12. Nov. 2018 um 10:22 Uhr schrieb Marc Hermans <
notifications@github.com>:

**Comment by Wrsaith** [comment]
ok so we have the whole upper left, north west corner of the town that f3 says no close colonies. The closest chunk block that is in the colony is 112 blocks away from town center, but just a few chunks away from the corner we're at 130 blocks from center and still inside town on f3 menu.

**Comment by Raycoms** [comment]
When did you start this server?

Am Mo., 12. Nov. 2018 um 20:14 Uhr schrieb Wrsaith <notifications@github.com

**Comment by Wrsaith** [comment]
about 2 or 3 weeks now.

**Comment by Raycoms** [comment]
you can use the /mc colony claim colony: id range: xchunks add: true

Am Mo., 12. Nov. 2018 um 23:00 Uhr schrieb Wrsaith <notifications@github.com

**Comment by Wrsaith** [comment]
so will that claim chunks with in range of the center of the colony?

**Comment by Raycoms** [comment]
this claims chunks within range of your position.

Am Di., 13. Nov. 2018 um 00:22 Uhr schrieb Wrsaith <notifications@github.com

**Comment by Wrsaith** [comment]
ok thanks :3
