### ISSUE TITLE
Unable to target Ancient Tome in command block.

### ISSUE THREAD

**Issue by ArodSnaux** [ldtteam/minecolonies#3056]
This is probably a "me" problem but you guys would know how to fix it... I'm writing a schematic that creates a Statue, that, if present in the city AND the player is holding an Ancient Tome, will reveal the location of any invading barbarians, basically by attaching a particle effect to the little buggers,

The statue uses two hidden command-repeat blocks, but while the targeting block works with Vanilla items such as a diamond sword, it does NOT work with the Ancient Tome. Am I doing something wrong?  Is it the ID? Is it a Forge problem maybe?

/testfor @p {SelectedItem:{id:"minecraft:diamond_sword"}}     <-- this works
/testfor @p {SelectedItem:{id:"minecolonies:ancienttome"}}     <-- this fails to target the player

Any suggestions would be appreciated. I'll gladly share the final statue as a Decoration.

**Comment by marchermans** [comment]
The id of the item is `minecraft:ancienttome`.

@Raycoms We should push out an update which patches all of this before 1.13!
This needs to be `minecolonies:ancienttome` just like with any other item.
@Raycoms To enable that we need to catch the missing registry entry event from FML and remap them.

**Comment by marchermans** [comment]
@ArodSnaux I created a patch that now makes it `minecolonies:ancienttome`.
