### ISSUE TITLE
Restack items after dumping

### ISSUE THREAD

**Issue by someaddons** [ldtteam/minecolonies#3058]
### Expected behavior
- Stack items kept after dumping (e.g. the lumberjack keeps 64 of each sapling) together after dumping, so they don't occupy two inventory slots
### Actual behaviour
- Two stacks of the sapling are kept, e.g. 24 + 40
### Steps to reproduce the problem
1. Give the Lumberjack more than 64 saplings of one type
2. Wait till he goes to dump items
3. Check his inventory for split itemstacks

**Comment by Raycoms** [comment]
Closed in favor of joint issue.
