### ISSUE TITLE
Builder bug .. Help me please ;(

### ISSUE THREAD

**Issue by Neranaton** [ldtteam/minecolonies#3060]
Hello !

I thinks I have a common problem but I cannot find something to fix this.

In fact, I created the colony by placing the town hall, after that, I placed the builders hut and I start the construction of it. But the builder start to delete the fence and then, it don't move.. 

In the server log, I have this message :

[17:43:06] [Server thread/INFO] [minecolonies]: WorkOrderBuild at location BlockPos{x=-877, y=72, z=718} is using schematics/Dark Oak/Builder1 instead of schematics/Dark Oak/Builder1

What do I do ?

**Comment by Raycoms** [comment]
Hi, sorry for the delay, just got time now. Did you place the builders hut too close to the townhall?
(Like were the construction tape overlapping?) Is he requesting something?
You can check in his GUI under requests.

**Comment by Neranaton** [comment]
Ok... 
I think I'm an idiot x) 
It's ok now, the problem is solved. 

It was a shovel problem ^^ the builder didn't accept the diamon shovel
