### ISSUE TITLE
Hole left by the pirate ship

### ISSUE THREAD

**Issue by lebanni** [ldtteam/minecolonies#3061]
Version :
minecolonies-1.12.2-0.10.39-ALPHA-universal.jar

When the pirate ship sail away, it left a big hole where it was. Maybe you could replace with water up to the level of the sea ?

![2018-11-12_23 03 13](https://user-images.githubusercontent.com/2799575/48378002-c014af80-e6cf-11e8-8744-207193bef9ef.png)

**Comment by Raycoms** [comment]
Will be done with https://github.com/ldtteam/minecolonies/issues/3035
