### ISSUE TITLE
Suggestion: More Diminsions+ Villages+ SMAS (Simple Modpack Addition System)

### ISSUE THREAD

**Issue by CTH999** [ldtteam/minecolonies#3063]
So, this is an idea for the distant, distant future. But, what if, you could make vilages in the nether, but theyr are differet? What about the end? You get the idea...

So, my idea has three parts
1. new villagers: in different dimensions, the vilagers look different. In the overworld they are the same, but, you know how originally pigmen were supposed to be the villagers? Well, a pig-men esque mob could be the villagers in the nether. A teleport capable, fast moving, two block tall "enderman" is the end one" So, that's the basic idea
2. In the overworld, it's the same. But, in the nether, the builds are designed to fit together in a nether fortress esque- way. In the end, same, but in an end city esque way.
3. The SMAS (Simple Modpack Addition System) So, you are making a modpack, and you want a special village for this dimension that you created for Advanced Rocketry, that the players can create there. Well, rather than asking you, what they can do is build the TI of the building, save it in the auto-generated SMAS (Using a sturcurute block), they store that file in an area, in this format:
File Path as normal: then: .Minecraft/config/minecolonies/smas/_dimid_/townhall/nb/t1

What that says is: In dimid (Put the dim id you want) (Also, in the minecolnies config, there is a file explaning how do do this), it is saying, this is the townhall, made of nb (Which, in the folder named dimid, you said what "nb" was (Let's say it was netherbrick) so, it's the netherbrick town hall, level one. That's where the structure block file goes. for tier 2, it would be: .Minecraft/config/minecolonies/smas/_dimid_/townhall/nb/t2

So, there is a folder string saying what it is. Everything within a dimid folder can be used on that dimid. If you want to make it work on multiple, just copy and paste the whole thing and put the new name in! Then, you have the name of the building, what the material is (Which, you abbreviate, and you say what the abbreviation is in the dimid folder), and then, you put the sturctue block file. Or, maybe an admin wand that allows you to save the building to the targeted file. Also, you have a folder for possible villagers, so you could make alliens if you want, I hope that makes sense

Also, you could use an .xml file, but using folders could be more intuitive, interesting, and, you might even save the village buildigns you use in there! (Or, if you don't, making a new folder for them overwrites the ones on the overworld, _if_ you use the townhall, it will overwwrite it)

This, I think is a good idea, but, it was easier to understand in my head...

Well, it's your choice. It's you mod, so you decide!

Sincerely, CTH2004

**Comment by CTH999** [comment]
Thanks!

**Comment by Raycoms** [comment]
Will be added to a new joint mod compat issue.
