### ISSUE TITLE
Farms not managing the expected amount of fields.

### ISSUE THREAD

**Issue by tuberasa** [ldtteam/minecolonies#3064]
### Minecolonies version

Version: 1.12.2.0.10.43-ALPHA-universal

### Expected behavior

With 2 farms of level 4 I would expect each of them to manage 4 fields.

### Actual behaviour

I have 6 fields, and 2 farms. One farm can manage 5 fields, the other none. 
(No difference between manual and automatic)

### Steps to reproduce the problem

Sorry don't have details on how this happened. Replacing the fields may mix things up a bit, but not what I expect. Also had a state where they both could only manage 1 field.

**Comment by tuberasa** [comment]
Removing all fields, restarting Minecraft and replacing the fields seem to have fixed it.

**Comment by Raycoms** [comment]
fixed
