### ISSUE TITLE
A few suggestions.

### ISSUE THREAD

**Issue by PestoPosta** [ldtteam/minecolonies#3066]
Ok so, in no particular order, and first and most importantly, thanks for one of only a hand full of mods I think should be integrated into vanilla :)

1: Warehouse worker: Sorts the bloody shelves XD
2: Deliveryman: Level 1 brings stuff to the workers buildings, Level 2 Same, Level 3 Brings things to buildings in progress, Level 4 Same, Level 5 will place chests at build sights and per-deliver materials.
3: Workers if near a store house should go fetch the materials after X amount of time.
4: Builders need to build/deconstruct maybe 15 to 20% faster.
5: There is no number five.
6:  A button to up date individual building schismatic, IE I make a change and I'd like it to stay if I hit repair.
7: WAY TOO MANY GAPS IN BUILDINGS WHERE MOBS CAN SPAWN, please either torch them or fill them XD
8: In general I'd like to see a little more autonomy in the colonists, as it stands I feel a little like I need to stand over my colony and wait for their needs.
9: Not sure if this is you or them, but there are no inventory sort buttons from Inventory Tweaks for the shelves.
10: A general Crafters.
11: Maybe? multiple workers per building?

Last, again I must thank you for an amazing mod :)

**Comment by PestoPosta** [comment]
12: Ok one more, the restaurant, let me pick what they use as fuel, and or only let them use logs and coal.

**Comment by webcrafter-fr** [comment]
A few more : 

13: Add a clipboard to see what the builder need to build something. Actually I need to screenshot the 2nd page of the builder's hut to remember what I need to craft for him. It's super painful.

14 :  Add roads. Solid blocks that would have priority over the other blocks so that citizens would walk on these blocks first. Why not add a speed bonus when citizens walk on these blocks.

15 : When I put up a hut, constructions tap appear all around it. It would be nice if they could appear before I put the hut down (while I use the construction tool) because I am often surprised by the size of the buildings and I have to deconstruct the hut before replacing it correctly.

**Comment by PestoPosta** [comment]
15: If you just switch the building to lv5 it will show you its full size.

**Comment by Raycoms** [comment]
there is an item called resource scroll for 13

Am Fr., 16. Nov. 2018 um 07:04 Uhr schrieb PestoPosta <
notifications@github.com>:

**Comment by webcrafter-fr** [comment]
@Raycoms Ah ? What's the craft ? I dont see the recipe on the wiki.

**Comment by webcrafter-fr** [comment]
Find it : 

![2wiipbe](https://user-images.githubusercontent.com/7268719/48627062-e24e4c00-e9b3-11e8-9e93-d1edd5daf034.png)

**Comment by PestoPosta** [comment]
16: Warehouse black list.

**Comment by lebanni** [comment]
Count me in for n° 12.

**Comment by PestoPosta** [comment]
17: White list/black list for the lumberjack trees. Possibly a similar system as the farmer.

**Comment by PestoPosta** [comment]
18: The ability to build upgraded buildings provided you have the appropriate level builders.

**Comment by marchermans** [comment]
@Raycoms on numbe 18. DId we not enable that?
Or is that creative only?

**Comment by PestoPosta** [comment]
I am not sure.
I know you can preview the build level, but I don't think it can be built at the level...
Granted there may be an error on my part, as I preview things at level 5 so I can see the size of the full building so it may default to level 1...

**Comment by Raycoms** [comment]
He means he wants to build level 5 straight

**Comment by marchermans** [comment]
If he has the builder for it, why not?

**Comment by Raycoms** [comment]
I mean, without building level 1-4 first

Am Di., 20. Nov. 2018 um 20:11 Uhr schrieb Marc Hermans <
notifications@github.com>:

**Comment by PestoPosta** [comment]
That I do.
Again love the mod :)

**Comment by PestoPosta** [comment]
I've had to do a lot of remodeling hence it became an issue.

**Comment by Raycoms** [comment]
many solved, many other scattered over several othe rissues
