### ISSUE TITLE
My game has crashed after the barracks has been finished

### ISSUE THREAD

**Issue by webcrafter-fr** [ldtteam/minecolonies#3068]
Version: minecolonies-1.12.2-0.10.27-RELEASE-universal

### Actual behaviour
My builder just finished the barracks and my game crashed. I can't connect to my save anymore, the game is loading and crash...

### Steps to reproduce the problem

Just build the barracks (spruce medieval)

**Comment by Raycoms** [comment]
do you have a log?

Am Do., 15. Nov. 2018 um 16:55 Uhr schrieb Cryt <notifications@github.com>:

**Comment by webcrafter-fr** [comment]
Yes 
[2018-11-15-5.log.gz](https://github.com/ldtteam/minecolonies/files/2586661/2018-11-15-5.log.gz)
[2018-11-15-4.log.gz](https://github.com/ldtteam/minecolonies/files/2586662/2018-11-15-4.log.gz)

**Comment by Raycoms** [comment]
Can you please update to a newer forge version? It seems like you are using an outdated one

**Comment by webcrafter-fr** [comment]
It works with the version 1.12.2 -14.23.5.2768

I had the 1.12.2-14.23.5.2555 version.

Thanks :)

**Comment by Raycoms** [comment]
np
