### ISSUE TITLE
Guard Tower Placement makes game die forever

### ISSUE THREAD

**Issue by ZoeDVDS** [ldtteam/minecolonies#3070]
### Minecolonies version

Version:  1.12.2

### Expected behavior
 Accessible guard tower. 

- 

### Actual behaviour

-  Game crashes and makes the world file unusable when placing guard tower block.

![image](https://user-images.githubusercontent.com/45092322/48607438-606f1a80-e9d5-11e8-8155-f48d1f05525f.png)

### Steps to reproduce the problem

1.  Place town hall
2.  Place guard tower block - through creative or survival neither matter
3.  Game freezes, computer fans kick in and then game fully crashes and comes up with 'game crashed' error. You cannot re-access the world file - game crashes every-time. 
4. ... Profit

**Comment by someaddons** [comment]
update your forge version

**Comment by ZoeDVDS** [comment]
k thx
