### ISSUE TITLE
Can't craft a field

### ISSUE THREAD

**Issue by webcrafter-fr** [ldtteam/minecolonies#3073]
Version: minecolonies-1.12.2-0.10.27-RELEASE-universal

Hi,

I can't craft a field. I tried with a pumpkin and a hay bale.

![s2](https://user-images.githubusercontent.com/7268719/48634472-e08d8400-e9c5-11e8-9b48-088aff8ccd10.jpg)
![s1](https://user-images.githubusercontent.com/7268719/48634508-f7cc7180-e9c5-11e8-867f-9eb215514eea.jpg)

**Comment by MineShadow7** [comment]
It's leather in the middle

**Comment by webcrafter-fr** [comment]
Thanks :) (The wiki is not up to date)
