### ISSUE TITLE
Warehouse racks 

### ISSUE THREAD

**Issue by DarVillous** [ldtteam/minecolonies#3075]
### Minecolonies version

Version: 1.12.2.-0.10.43-Alpha

### Expected behavior
RFtools inventory scanner should see the correct items in the warehouse rack, translocators would insert items into the rack they are attached to.

### Actual behaviour
Opening the rack shows a different inventory from what the inventory scanner sees.  The inserted items *can* end up in a rack far away from the translocator. 

### Steps to reproduce the problem

I have a dark oak lvl 5 warehouse, in the floor next to a rack there is a refined storage interface with translocators on them.  

The interface is set to auto craft and stock  i64 dark oak plain timber frames.
The receiving item translocator is set to regulator mode with a diamond nugget.  and to keep 32 of them in the rack.  according to the scanner the timbers ended up in a rack at the far end of the warehouse but they didnt appear in the rack when I opened it.

It appears I see one inventory when I open the rack and the scanner sees a different inventory.  Items inserted by the translocator end up in several different racks, none of them accessible by me.

![oddness](https://user-images.githubusercontent.com/7937470/48653246-78d93800-e9c9-11e8-8e33-28375f3158b2.png) Note that despite being the block location the scanner says should contain eye of ender the inventory does not.  The seeds and other items in the rack are not what the scanner sees.

![2018-11-16_18 03 40](https://user-images.githubusercontent.com/7937470/48653307-fac96100-e9c9-11e8-907a-a37daed21396.png)

- I'm not sure which inventory the dman can access.
- I have not been able to reproduce the issue outside of the warehouse connected storage.
- I did some additional testing with eyes of ender because i did not have any in the warehouse.  they ended up in a scanner accessible rack far away from the translocator in one test and in one right next to the translocator in the next.

using the translocator to export items from the rack did return the items from the ghost inventory but did not adjust the real inventory.

**Comment by DarVillous** [comment]
I connected a separate  refined storage system to the one rack.  (a grid and controller and external storage)  the grid sees the "ghost" inventory.  opening the rack from the same side the external storage is attached to shows the "non ghost" inventory.

It looks like the 1 rack (or even double rack) has two different inventories.  One the pipes see and one the player can access.

**Comment by DarVillous** [comment]
The warehouse has had all of the emerald upgrades applied.

**Comment by marchermans** [comment]
Yes there is two inventories for a good reason: Performance.
Entity performance in Minecraft is very bad. So we have an optimized inventory logic backing the racks that allows them to search for items very fast. They support however IItemHandler.

I tested it not personally but @Raycoms should have some information.

Let me note however that you are looking at the wrong block in that image: See that Looking At in F3: says Z:306 while your UI says you have Z305 selected. Just making sure that you are not looking past something here.

**Comment by DarVillous** [comment]
Please look at the image again and notice that there are two images of the inventory scanner, one for 305 and one for 306.  both show the same inventory in the scanner and the show a different inventory when opened by the player.

**Comment by marchermans** [comment]
Both images have the 306 one highlighted, which means it displays the 306 block in the menu, I validated that yesterday, when i made the comment. So please check again that the scanner actually show you the correct inventory.

**Comment by Raycoms** [comment]
Should be fixed by the things we fixed recently.
