### ISSUE TITLE
Builder cannot upgrade Town Hall 4 / Beds Deleted?

### ISSUE THREAD

**Issue by MissMarley** [ldtteam/minecolonies#3076]
### Minecolonies version
Current All The Mods 3 as of Twitch/FTB
Minecraft 1.12.2

### Expected behavior
Trying to upgrade my Town Hall (Spruce) to level 5

### Actual behaviour
Town hall won't build.
My Builders are all level 5 - My Town Hall was in the midst of being upgraded when my builders stopped. 
I have checked as many possible errors (Pathing, Full Builder Inventory, Required Materials, etc) and no errors were found.
I have tried to cancel the build, replace builders, try repairing the building instead. 

I assumed at some point that maybe on some error that perhaps one of my villagers had been killed, and that was blamed on me? (I did not hit her. I did naht. Oh hi Mark) So I thought I would wait out a full day cycle, and followed my Town Hall Builder to her house like a creepy stalker, to make sure everything was ok - and when I got to my Builders House, I checked and realized a number of the Grey Beds in the (Level 5) house were missing. So I replaced them manually, canceled the upgrade, Set that same builder to repair her own house (and others with similar issues of missing beds) which has been done - and still the Town Hall can not be completed, and is still stuck mid-completion. 

My builder simply goes to the Builder Building, stands in front of her chest, and does nothing. Does not pick up items.
Currently has a red circle next to House Modifier (Despite me trying to fix this?)

### Steps to reproduce the problem
Town Hall level 4 - spruce
Builder level 5 
Builder House level 5 (Beds went missing randomly in this, and other houses? Replaced manually, then 'Repaired' House building)

**Comment by MissMarley** [comment]
It should also be noted that -all- three of my builders have stopped working during this.
Both of my Deliverymen have also stopped working.
I haven't bothered to check the other workers in my town, since they aren't tied to this project.

**Comment by someaddons** [comment]
did you try clearing all workorders at the townhall and restarting the upgrade?

**Comment by MissMarley** [comment]
Yes. I've cleared the work order for the Town Hall upgrade
I've set it to repair
I've switched workers. All the stuff mentioned up in my original post.
Nada.

**Comment by Raycoms** [comment]
did you try a /mc rs reset colony: theid ?

Am Sa., 17. Nov. 2018 um 15:30 Uhr schrieb MissMarley <
notifications@github.com>:

**Comment by MissMarley** [comment]
What does that do? The only reason I'm hesitant/asking is cause my town is pretty well put together and it'd suck to have to start from scratch lol

**Comment by Raycoms** [comment]
it would reset the request system (no negative effects) maybe you got  a
stuck request somewhere

Am Sa., 17. Nov. 2018 um 15:35 Uhr schrieb MissMarley <
notifications@github.com>:

**Comment by MissMarley** [comment]
How do I find my colony ID, and I can try that now?

**Comment by Raycoms** [comment]
./mc whereami

Am Sa., 17. Nov. 2018 um 15:42 Uhr schrieb MissMarley <
notifications@github.com>:

**Comment by MissMarley** [comment]
My game runs a bit laggy, but I'll let it run for a bit while I idle, and let you know how/if that worked. Thank you :3

**Comment by Raycoms** [comment]
np, if it didn't work, you can upload your world and I can give it a look

Am Sa., 17. Nov. 2018 um 15:53 Uhr schrieb MissMarley <
notifications@github.com>:

**Comment by MissMarley** [comment]
Ok! So I waited until the building was finished to fully judge if this worked or not - It DID work, I'm having some issues with my builder accessing stuff in his Builder Building Chests? But If I picked up stuff for him and gave it to him he seemed to be ok. Might just be kinks to work through, but I'm at least through the upgrade. THANKS Raycoms! :3
