### ISSUE TITLE
The miner constantly asks for a pickaxe.

### ISSUE THREAD

**Issue by ZzylinN** [ldtteam/minecolonies#3077]
Version:
minecolonies-1.12.2-0.10.45-ALPHA-universal
forge 1.12.2-14.23.5.2768
other mods

The miner constantly requires a pickaxe. Couriers ignore his requests.
The storage has:
-This survivalist pickaxe (the mod forestry (v1.12.2-5.8.2.354)) is available in both: packaged and unpacked.
-Iron pickaxe.

![2018-11-17_23 54 05](https://user-images.githubusercontent.com/34644142/48664168-e6b65a00-eac4-11e8-8c9e-d5e79438ff53.png)
From the screen you can see that the miner constantly asks for a pickaxe

![2018-11-17_23 54 29](https://user-images.githubusercontent.com/34644142/48664169-e74ef080-eac4-11e8-8e95-ff6e2744463b.png)
On the screen you can see that the miner in the inventory has a pickaxe

**Comment by ZzylinN** [comment]
Mine level 4

**Comment by someaddons** [comment]
the miner needs a pickaxe with a certain mining level which fits the ore's he found, probably he needs a better pickaxe

**Comment by ZzylinN** [comment]
Specially checked for the best picks.

![2018-11-20_08 47 15](https://user-images.githubusercontent.com/34644142/48748450-305b9c00-eca1-11e8-8a93-a62a0b1ae21f.png)
And here it is clear that he wants a diamond pickaxe from the requested picks.

![2018-11-20_09 00 17](https://user-images.githubusercontent.com/34644142/48749001-18851780-eca3-11e8-8b9f-ef8c086f9653.png)
And here it is clear that he wants a surviving pickaxe from the requested picks.


![2018-11-20_08 44 21](https://user-images.githubusercontent.com/34644142/48748447-305b9c00-eca1-11e8-9bba-cfb753688db1.png)
Here you can see that the vault contains a diamond pick, an iron pick and a surviving pick.


![2018-11-20_08 45 54](https://user-images.githubusercontent.com/34644142/48748448-305b9c00-eca1-11e8-9e01-c5a08259c0a9.png)
After resetting the request to this place where he resorts and begins to ask for a pickaxe. Here you can see that there is no ore and a good pick is not needed.

PS: For some reason, besides different picks, requests also require a sword. While asking for a pickaxe in the chat. Maybe the sword has the properties of a pickaxe (mod).
![2018-11-20_09 00 15](https://user-images.githubusercontent.com/34644142/48748985-f9868580-eca2-11e8-9d3b-54e7771c9c69.png)

**Comment by PoroUsedSnax** [comment]
You should try giving them the pick they want, instead of trying to wait for the dmen to deliver it. 
The miner will often end up mining out parts that you cannot see when working on a schematic, which would likely explain why you can't see the item they want the pick for.

As you said with the sword, it's likely been implemented as a pickaxe in someway, not much we can do with that, the mod authors should really sort that out if that isn't the intended purpose of the item.

**Comment by ZzylinN** [comment]
> You should try giving them the pick they want, instead of trying to wait for the dmen to deliver it.

Their very first screenshots can be seen that the miner in the inventory is an iron pick. Also there are various picks in stock (seen on screen)

**Comment by Raycoms** [comment]
what does the description say?

Am Do., 22. Nov. 2018 um 13:31 Uhr schrieb Sasha <notifications@github.com>:

**Comment by ZzylinN** [comment]
it's a sword
![2018-11-22_22 07 00](https://user-images.githubusercontent.com/34644142/48913678-40db6480-eea3-11e8-927a-6a5f5ddca1c4.png)

Only the most important thing is that the miner constantly asks for what he has in the inventory or is stored in a warehouse.


Also as a food, for some reason, people carry eggs (although they are not edible, only as an ingredient). And eggs on the ore dictionary refers to "food"
![2018-11-22_22 14 16](https://user-images.githubusercontent.com/34644142/48913964-3a012180-eea4-11e8-8bd1-2f40d76b79e9.png)

**Comment by Raycoms** [comment]
when you click on the info button (theone with the three ~) what does the request say?
Did you try /mc rs reset colony: id?

**Comment by ZzylinN** [comment]
> Did you try /mc rs reset colony: id?

Yes


> when you click on the info button (theone with the three ~) what does the request say?

![2018-11-29_01 56 12](https://user-images.githubusercontent.com/34644142/49178634-7b00a680-f37a-11e8-883c-a30676d2e475.png)

**Comment by Raycoms** [comment]
could you show that in English?

Am Mi., 28. Nov. 2018 um 18:00 Uhr schrieb Sasha <notifications@github.com>:

**Comment by ZzylinN** [comment]
![2018-11-29_07 06 28](https://user-images.githubusercontent.com/34644142/49192539-a351ca80-f3a5-11e8-903a-6a939de16c1c.png)

**Comment by Raycoms** [comment]
Okay, now we'r egetting somewhere. He found an ore which needs a very
strong pickaxe probably, one he can't wear. A modded ore probably. If you
fire/rehire him, check where he walks to and you should find the block
around there


Am Mi., 28. Nov. 2018 um 23:09 Uhr schrieb Sasha <notifications@github.com>:

**Comment by ZzylinN** [comment]
![2018-11-20_08 45 54](https://user-images.githubusercontent.com/34644142/48748448-305b9c00-eca1-11e8-9e01-c5a08259c0a9.png)
After resetting the request to this place where he resorts and begins to ask for a pickaxe. Here you can see that there is no ore and a good pick is not needed.

**Comment by ZzylinN** [comment]
Also in the game there is no ore that can not be mined with a diamond pick.
Moreover, he asks for a minimum diamond pickaxe that is in the storage

**Comment by Raycoms** [comment]
If you put it in his inventory, does he work?

**Comment by ZzylinN** [comment]
> If you put it in his inventory, does he work?

Yes

![2018-11-29_17 53 21](https://user-images.githubusercontent.com/34644142/49220417-57803f00-f400-11e8-859d-6661ab76ea3e.png)
Diamond pickaxe put me in the miner's inventory

![2018-11-29_17 54 01](https://user-images.githubusercontent.com/34644142/49220471-7d0d4880-f400-11e8-88cd-0340c1697fb9.png)
Diamond pickaxe which is in storage

**Comment by Raycoms** [comment]
Your storage chest might be unregistered

**Comment by ZzylinN** [comment]
> Your storage chest might be unregistered

What to do?
from previous issues (Problems with the builder or courier v1.12.2-0.10.49-ALPHA # 3101) I repaired the warehouse. And it did not help as you can see from the requests of the miner

**Comment by Raycoms** [comment]
you would have to remove that rack and then repair the warehouse.

Am Do., 29. Nov. 2018 um 10:30 Uhr schrieb Sasha <notifications@github.com>:

**Comment by ZzylinN** [comment]
after he broke the rack and repaired the warehouse, the miner stopped asking for a pickaxe and went to dig!
At the rack the lower line capacity disappeared.

It was:
![2018-11-29_17 54 01](https://user-images.githubusercontent.com/34644142/49225403-2b6bba80-f40e-11e8-8b6f-02f76833ca2f.png)

has become:
![2018-11-29_19 31 14](https://user-images.githubusercontent.com/34644142/49225416-34f52280-f40e-11e8-86aa-4baa7a3f76c9.png)

Expanded warehouse with emerald block

**Comment by Raycoms** [comment]
Yeah, we will add this in the future. And we'll add a way to reregister
these blocks as well

Am Do., 29. Nov. 2018 um 11:38 Uhr schrieb Sasha <notifications@github.com>:

**Comment by ZzylinN** [comment]
> Yeah, we will add this in the future. And we'll add a way to reregister these blocks as well

That is, now expanding the warehouse using a block of emeralds does not work?

**Comment by Raycoms** [comment]
It won't expand the removed rack to the size of the others. But I could
find a way to fix this.

Am Do., 29. Nov. 2018 um 11:53 Uhr schrieb Sasha <notifications@github.com>:

**Comment by ZzylinN** [comment]
> But I could find a way to fix this.

Well thank you.

Please tell me what the labels need to be in the warehouse?

**Comment by ZzylinN** [comment]
The builder did not put the label in the right places!
