### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by PestoPosta** [ldtteam/minecolonies#3078]
Is there any way to prevent a lumberjack from cutting down a specific tree/s.
/
Is there a way to specify  which trees you want the lumberjack to chop?

**Comment by PoroUsedSnax** [comment]
To prevent trees being cut down, just place cobblestone underneath them. other than that you can't tell them which trees they should/shouldn't chop, only which ones they should/shouldn't replant afterwards

**Comment by PestoPosta** [comment]
Thanks for the quick response :)

And now I have one more point for my suggestion list XD

**Comment by someaddons** [comment]
its on the suggestion list
