### ISSUE TITLE
JEI's items list cover the rack's GUI

### ISSUE THREAD

**Issue by mc-kaishixiaxue** [ldtteam/minecolonies#3079]
### Minecolonies version

Version: 0.10.45-ALPHA
### Expected behavior

- The JEI's items list can't cover the rack's GUI.
### Actual behaviour
![2018-11-17_20 40 08](https://user-images.githubusercontent.com/37864486/48670243-7e608a80-eb4f-11e8-92b4-c49db9a8d167.jpg)
I can't click the inner items in the red area.
### Steps to reproduce the problem

1. Update a warehouse to Lv.5(max level)
2. I put 3 emerald blocks to update capacity.
3. I right clicked a large rack to open its GUI.

**Comment by someaddons** [comment]
thats a pretty normal issue with large inventories and a small resolution, how about you check your keybind to hide JEI and use it when needed?

**Comment by mc-kaishixiaxue** [comment]
I used Ctrl+O key to hide JEI list,that's not convenient.

**Comment by PoroUsedSnax** [comment]
This will be resolved when the new BlockOut is implemented, as it will implement scrollable inventories for the racks

**Comment by someaddons** [comment]
you can change the hotkey

**Comment by Raycoms** [comment]
Will be fixed with the new blockOut then
