### ISSUE TITLE
[Enhancement] bounding boxes before structure creation

### ISSUE THREAD

**Issue by winsrp** [ldtteam/minecolonies#3081]
Could it be possible to have the bounding boxes of the structures at the different levels (mostly 5) shown when presenting them before clicking the check box , so I can tell where I should put my structures so they don't mess up my roads? (simple lines like the ones on some mods to show bounding boxes for chunks, could be a config option as well, or just a simple keymapping, or even an option on the GUI), I get to know with the tape after the confirmation, but most of the time they are off by 1 or 2 blocks, so I need to destroy the initial block and try again until it is just right, would save a lot of trouble.

tx
-Winsrp

**Comment by Raycoms** [comment]
You can just switch to level 5 in the build tool screen on the top right
corner and check the size before confirming as well

Am Di., 20. Nov. 2018 um 04:31 Uhr schrieb winsrp <notifications@github.com

**Comment by winsrp** [comment]
yes but most of the time, the tape put around will also take some land inside my roads which leads to the builder destroying them, even if I lay them to the edge.

**Comment by someaddons** [comment]
click the + button a few times to rise it above the ground to see its actual required space. And you can press escape to view the preview while moving around

**Comment by Raycoms** [comment]
I think he means pos placement

Am Di., 20. Nov. 2018 um 11:44 Uhr schrieb someaddons <
notifications@github.com>:

**Comment by winsrp** [comment]
@someaddons  yeah I already do that, but still can't get them right most of the time. Elevation is no problem but position...... always end up putting and destroying the buildings 1 or 2 times.

**Comment by BonaireDreams** [comment]
^^ This, even looking at the level 5 building there are always 1-2 extra squares of land that the bounding box encompasses. I spent so much time placing a cobble block beside my road, previewing a building in level 5, clicking place, only to see that the fence was 2 block into my road. So then I started looking at a building corner's or stairs to see, ok, left step is on this yellow flower in preview. place building. Its fence is 2 blocks into my road. Break block, back to preview, make sure step is now 2 blocks left of the yellow flower, place building, fence is now beside my road. Build.  Rinse and repeat with every building. It would be great to see the construction tape in the preview mode so get the entire footprint size of the building.

**Comment by someaddons** [comment]
I've got no problems with that at all:
![2018-11-20_23 39 23](https://user-images.githubusercontent.com/38401808/48808146-2a58d000-ed20-11e8-8b50-8cf50a37d7d9.png)
![2018-11-20_23 56 04](https://user-images.githubusercontent.com/38401808/48808147-2dec5700-ed20-11e8-8c7c-bce40c72062e.png)

**Comment by winsrp** [comment]
try medieval houses, those are the worst, like citizen hut, or builders

**Comment by someaddons** [comment]
ah so it doesnt show the full scale area at all schematics I see

**Comment by winsrp** [comment]
Yeah... Just that.... Bounding box for the win =D

**Comment by winsrp** [comment]
Yeah... Just that.... Bounding box for the win =D

**Comment by keldor314** [comment]
It would also be useful if it could show bounding boxes for buildings already built in the world.  For instance, suppose I have a level 2 hut already built, and want to place another building so that it won't collide at some later time when the hut's upgraded.  Right now I can only guess what the footprint of the existing hut will be after it's upgraded later on.

**Comment by winsrp** [comment]
that's normally more difficult because once it is placed in the world is just blocks, what I do, is that while the preview is on, I just mark the boundaries of the level 5, so that way I know how much space does it takes.

**Comment by keldor314** [comment]
The problem with marking them is that it takes me a very long time to get any buildings to level 5 (in fact, the highest I have right now at all are a couple level 4s).  This means that the markings would be sitting there looking ugly for a very long time.

**Comment by winsrp** [comment]
I put the markings, set all the buildings, and then put roads around them, then I remove the markings, since I don't need them anymore, I play in hardcore mode, with enhanced monster AI + red moon, I normally just get 1 or 2 to level 2 XD

**Comment by BonaireDreams** [comment]
Once I place a new building I put a block in the ground under each of the 4 bounding box corners. A nice piece of smooth granite, or diorite so it looks nice. That way I know where the corners of the bounding box are and I dont have a block sitting on the ground.

**Comment by Raycoms** [comment]
okay, I still didn't get it completely, you want that if we render a building in the buildTool it also renders the outlines of the other buildings?
(if you click repair for example then it will put the tapes down for example)

**Comment by winsrp** [comment]
I would like the outline to be displayed on the preview of the building before placing it on the ground.

**Comment by Raycoms** [comment]
Ah an outline in general of the building you are placing right now. Okay,
that is not difficult

Am Mi., 28. Nov. 2018 um 16:18 Uhr schrieb winsrp <notifications@github.com

**Comment by winsrp** [comment]
thanks!

**Comment by BonaireDreams** [comment]
Ya, I think we got a bit derailed with other thoughts. But if the preview showed the "construction tape" that is placed when you place the hut block you could see exactly the size of the building envelope including any extra grass areas. That would really help when placing a few buildings beside each other before they are completely constructed.

**Comment by Raycoms** [comment]
rendering the same outline as the scan tool has would be very easy

Am Mi., 28. Nov. 2018 um 17:25 Uhr schrieb Gerald <notifications@github.com
