### ISSUE TITLE
Copper Rods from Thermal Dynamics do not work for Fishermen

### ISSUE THREAD

**Issue by atxmatt2510** [ldtteam/minecolonies#3083]
### Minecolonies version
minecolonies-1.12.2-0.10.27-RELEASE-universal being used on forge-1.12.2-14.23.4.2765-universal with Minecraft version 1.12 

Version: 

### Expected behavior
Copper Fishing Rods from Thermal Foundation do not work. The Fisherman recognizes it as a valid rod, however.

### Actual behaviour
I get the error that the Fisherman's Hut is too far from water. The villager is trying to move off the edge and will walk on placed blocks toward water. If I switch to a vanilla rod, the problem goes away

### Steps to reproduce the problem
Fulfill the Fisherman's rod request with a Copper Rod from Thermal Dynamics.

### Additional Notes
The other rods from Thermal Dynamics may not work either, I haven't tried them.

**Comment by Raycoms** [comment]
Yeah, the fisher is quite fix on this, we have to add further rod support in the future

**Comment by Raycoms** [comment]
Will be added to a new joint mod compat issue.
