### ISSUE TITLE
warehouse racks dupe bug

### ISSUE THREAD

**Issue by Hazmatik** [ldtteam/minecolonies#3084]
### Minecolonies version

Version:  minecolonies-1.12.2-0.10.34-ALPHA-universal

### Expected behavior

Items not being duped

### Actual behaviour

1. Fill all the slots of a rack (could be all the same item or not) leaving a stack not a full stack
2. Try to shift + click a full stack of whatever item is in that less than full stack
3. The stack in the rack fills up but no items are taken from player inventory

**Comment by Hazmatik** [comment]
[![Image from Gyazo](https://i.gyazo.com/70fbf602f5554106117288faa21e7d63.gif)](https://gyazo.com/70fbf602f5554106117288faa21e7d63)

**Comment by Hazmatik** [comment]
Also just noticed the same thing happens in reverse with the player's inventory being full and shift clicking items from the racks to the players inventory

**Comment by Raycoms** [comment]
Fixed
