### ISSUE TITLE
All workers and Citizens Stoped and Waiting

### ISSUE THREAD

**Issue by TrollCrab** [ldtteam/minecolonies#3085]
### Minecolonies version

Version: 0.10.46

### Expected behavior

- My workers (Builders, Deliveryman, Fisher vs vs) Stoped and waiting everytime.

### Actual behaviour

- Not always but a lot of time i seen this problem after mornings.

### Steps to reproduce the problem

1.  Fire workers
2.  Hire workers
3.  and than they start do something again.
4. ... Profit

**Comment by someaddons** [comment]
Should be fixed in the newest version (47)
