### ISSUE TITLE
Knights do not request shields

### ISSUE THREAD

**Issue by someaddons** [ldtteam/minecolonies#3086]
### Expected behavior

Since knights are able to use shields they should make an async request for them
 

### Actual behaviour

Not requesting shields
 

### Steps to reproduce the problem

Hire a knight

**Comment by Raycoms** [comment]
they should request them starting at level 1

Am Mi., 21. Nov. 2018 um 16:45 Uhr schrieb someaddons <
notifications@github.com>:

**Comment by someaddons** [comment]
ye you're right, they do :D
