### ISSUE TITLE
Server crash doing nothing particular

### ISSUE THREAD

**Issue by lebanni** [ldtteam/minecolonies#3087]
Versions :
minecolonies-1.12.2-0.10.47-ALPHA-universal.jar
forge-1.12.2-14.23.5.2768-universal.jar

[crash-2018-11-21_22.40.30-server.txt](https://github.com/ldtteam/minecolonies/files/2605880/crash-2018-11-21_22.40.30-server.txt)

**Comment by someaddons** [comment]
indeed, broken on servers atm, thx for the report
