### ISSUE TITLE
Colonist Disappered 

### ISSUE THREAD

**Issue by Howman** [ldtteam/minecolonies#3088]
Version: minecolonies-1.12.2-0.10.47-ALPHA-universal.jar

### Expected behavior

Well to work as it should.

### Actual behaviour

Well I had left my game playing and went to the store came back screen was black had to restart computer then started the game back up and all the colonist where gone and could not click any of the chests
tried /minecolonies colony refresh colony: colony 1
and said that there was no mayor for colony found .

**Comment by Raycoms** [comment]
did you try /mc colony loadbackup ?

Am Mi., 21. Nov. 2018 um 20:44 Uhr schrieb Howman <notifications@github.com

**Comment by Howman** [comment]
Missing required parameter when i tried  /mc colony loadbackup

**Comment by GanthorPrime** [comment]
/mc colony loadbackup colony:{yourcolonyid}.  

You can press TAB on any command and it will try to autocomplete with avaible commands - parameters.  If you have more than 1 colony, find {yourcolonyid} with /mc colonies list

**Comment by Raycoms** [comment]
it needs the dimension as well afaik

Am Do., 22. Nov. 2018 um 10:40 Uhr schrieb GanthorPrime <
notifications@github.com>:

**Comment by GanthorPrime** [comment]
if the message was exactly 'there was no mayor for colony found', maybe he will need to do a '/mc colony claim' ?.

**Comment by Raycoms** [comment]
No, the world crashed and the colony data got corrupted so he has to reload
it.

Am Do., 22. Nov. 2018 um 10:44 Uhr schrieb GanthorPrime <
notifications@github.com>:

**Comment by Howman** [comment]
/mc colony loadbackup colony:{1}

For the dimension is that a number or just overworld

**Comment by Raycoms** [comment]
0 for overworld

Am Do., 22. Nov. 2018 um 18:49 Uhr schrieb Howman <notifications@github.com

**Comment by Howman** [comment]
I can click on chests but the there are no colonist  
should i restart game

**Comment by Raycoms** [comment]
Just go to the townhall and click recall all

Am Do., 22. Nov. 2018 um 19:04 Uhr schrieb Howman <notifications@github.com

**Comment by Howman** [comment]
Thank You That Fixed Me Up.
