### ISSUE TITLE
[New Worker] Inn & Brewer

### ISSUE THREAD

**Issue by pmardle** [ldtteam/minecolonies#309]
This will be a great system if we can get it right.

Step 1) Brewer Worker.

Grows reeds, and "Cooks/Ferments" the reeds into Ale
Needs a supply of Glass Bottles (Crafter can make these perhaps)
Turns 2 reeds + 1 glass bottle into 1 Ale.

Step 2)  The Inn.

Needs a supply of Ale to work.
Worker is the "Bartender"
Inn Randomly Spawns NPC's that are "Adventurers" who sell items only attainable from Dungeons (Plus some other mod stuff perhaps) in return for Ale.
NPC Spawn chance is based upon Building Level.

There is a NPC Spawn test every minecraft Hour. (12 per waking day)
Level 0 - Nothing (Building must be built for this worker to do anything)
Level 1 = 5% Chance (one per 20 hours average)
Level 2 = 10% Chance 
Level 3 = 15% Chance
Level 4 = 20% Chance
Level 5 = 25% Chance

The max number of NPC's that can be spawned is 1 per level of building.
NPC's stay in the Inn for a random time between 12-48 Minecraft hours (0.5 - 2 minecraft days)

Each NPC is basically a re-modelled/skinned testificate, with a very similar interface to Vanilla Villagers, just populated with our own items. (E.g. 5 Ale for 1 Nametag)

NPC Adventurers could also provide spawn eggs, heads and other things not normally available in survival mode.

**Comment by Raycoms** [comment]
The farmer could grow the brewers reeds already no?
The brewer could also get different kinds of alcohol from different kind of
products (Vodka from potatoes, beer from crops etc)

Why not let these NPC adventures give the people quests?
Like bring me 20 red wool in change for random rare item x?
But they only stay like 1 minecraft hour per alcohol, therefore to have
more time to supply the items we need more alcohol?

2016-11-29 12:02 GMT-02:00 pmardle <notifications@github.com>:

**Comment by pmardle** [comment]
Yes the Inn was also going to be the hub for future Quests :)

**Comment by tomorrow4268** [comment]
how you wanna do the despawning rate?

**Comment by marvin-bitterlich** [comment]
@tomorrow4268 no idea, still planning for far future

**Comment by winex** [comment]
i see Inn that would also have effect on happiness system. for ex, workers of level 3+ buildings should need it (like restaurant for getting food) or they're not happy otherwise. maybe some colonists even go to drink some ale at the evening every day ;)
p.s. reeds should be grown by farmer, brewers only brews

**Comment by Raycoms** [comment]
Closed in favor of joint issue.
