### ISSUE TITLE
Fisherman eats raw fish

### ISSUE THREAD

**Issue by lebanni** [ldtteam/minecolonies#3091]
Version: 
forge-1.12.2-14.23.5.2768-universal.jar
minecolonies-1.12.2-0.10.48-ALPHA-universal.jar

### Expected behavior
Fisherman eats cooked food at the restaurant.

### Actual behaviour
Fisherman eats the raw fish he has just fished.

**Comment by lebanni** [comment]
I also saw the builder eating a raw salmon while he needed one for level 3 fisherman building, and had bread in his inventory.

**Comment by TheStrato** [comment]
My Shepard has eaten raw mutton before as well when there was plenty of food available in town. They should prioritize "raw" as a last resort after "cooked, in inventory" and "cooked, available from colony supply" imo.

**Comment by Raycoms** [comment]
Closed in favor of: #3147
