### ISSUE TITLE
Scan Tool Compat for Little Tiles

### ISSUE THREAD

**Issue by WenXin20** [ldtteam/minecolonies#3092]
### Minecolonies Version

Version: 0.10.48-ALPHA
### LittleTiles Version

Version: 1.5.0-pre122

### Expected behavior

- Material list from the scan tool should display blocks created by LittleTiles tools. (Similar to how Chisel and Bit blocks are created)

### Actual behaviour

- LittleTiles blocks created with its tools display in the material list as tile.null and have an invisible block texture.

### Steps to reproduce the problem

1.  Chisel any block using the LittleTiles hammer, saw, etc.
2.  Select this area using the Scan Tool
3.  View the material list
4. ... Profit and see that blocks are named tile.null

**Comment by Raycoms** [comment]
fixed
