### ISSUE TITLE
Building Tool Structure Preview Crash with Cooking for Blockheads Fridge

### ISSUE THREAD

**Issue by WenXin20** [ldtteam/minecolonies#3093]
### Minecolonies Version

Version: 0.10.48-ALPHA
### Cooking for Blockheads Version

Version: 6.4.65

### Expected behavior

- To be able to see the Cooking for Blockheads fridge in the custom structure preview.

### Actual behaviour

- Crashes when right-clicking the building tool to preview the custom stucture. The same crash also happens with [Secret Room Blocks](https://minecraft.curseforge.com/projects/secretroomsmod) and [Chisel and Bit](https://minecraft.curseforge.com/projects/chisels-bits) blocks.

[Error Log](https://gist.github.com/WenXin20/05cd663e5d6909df1b77b97e8c425fc1), [Cooking for Blockheads Crash Log](https://paste.dimdev.org/aduyasewov.mccrash), [Chisel & Bits Crash Log](https://paste.dimdev.org/kibayeduqo.mccrash), [Secret Rooms Crash Log](https://paste.dimdev.org/zelunavace.mccrash)
### Steps to reproduce the problem

1.  Create a new schematic containing the cooking for blockheads fridge (place 2, one on top of the other to create a two-high fridge).
2.  Create a new schematic with the scan tool.
3.  Preview the new schematic with the building tool.
4. ... Profit and the game crashes.

**Comment by Raycoms** [comment]
do you have a log for all of these?

Am Fr., 23. Nov. 2018 um 18:02 Uhr schrieb WenXin2 <notifications@github.com

**Comment by Raycoms** [comment]
This is related to the tileEntities which need a world to render, we have
to check into this yet.

Am Fr., 23. Nov. 2018 um 18:06 Uhr schrieb Ray Neiheiser <
ray.neiheiser@gmail.com>:

**Comment by WenXin20** [comment]
I updated the list of mods that also caused the crash and added a crash log for each.

**Comment by Raycoms** [comment]
We checked on our site, and this happens because they use the world in
renderSpecific methods while they should be using IBlockAccess, can you
report that to them?

Am Fr., 23. Nov. 2018 um 18:52 Uhr schrieb WenXin2 <notifications@github.com

**Comment by WenXin20** [comment]
Sure

**Comment by Raycoms** [comment]
I think we can close this here then.
