### ISSUE TITLE
Support for Grimpack's Camo Pressure Plate

### ISSUE THREAD

**Issue by WenXin20** [ldtteam/minecolonies#3094]
### Minecolonies Version

Version: 0.10.48-ALPHA
### Grimpack Version

Version: [6.0.0.6](https://minecraft.curseforge.com/projects/grim-pack)

### Expected behavior

-  For the [camouflage pressure plate](https://grim3212.com/grim-pack/decor/furniture) to change it's texture according to the block underneath, such as dirt or sand. 

### Actual behaviour

-  Retains the texture of the block that was underneath it when creating the schematic. Like the solid-placeholder block.

![2018-11-23_14 19 35](https://user-images.githubusercontent.com/12000593/48960166-3915d180-ef30-11e8-8e92-cf042f705077.png)
![2018-11-23_14 21 18](https://user-images.githubusercontent.com/12000593/48960168-39ae6800-ef30-11e8-9501-d879cf074dd8.png)

### Steps to reproduce the problem

1.  Create a schematic with the solid placeholder block and a camouflage pressure plate on top.
2.  Have a builder build it.
3. ... Profit

**Comment by Raycoms** [comment]
Will be added to a new joint mod compat issue.
