### ISSUE TITLE
Support for EDX Multipart Mod

### ISSUE THREAD

**Issue by WenXin20** [ldtteam/minecolonies#3095]
### Minecolonies Version

Version: 0.10.48-ALPHA
### EDX Multipart Version

Version: [1.1.1](https://minecraft.curseforge.com/projects/edx-multipart)

### Expected behavior

-  To be able to view the blocks required in the material list and in the building tool preview.

### Actual behaviour

-  Slabs aren't listed in the materials list of the scan tool and the building wand does not display the blocks, as if they don't exist.

![2018-11-23_14 44 39](https://user-images.githubusercontent.com/12000593/48960473-82ffb700-ef32-11e8-83ed-163ee51928a2.png)
![2018-11-23_15 13 05](https://user-images.githubusercontent.com/12000593/48960474-85621100-ef32-11e8-9859-2a4534009f4b.png)
![2018-11-23_14 46 54](https://user-images.githubusercontent.com/12000593/48960476-885d0180-ef32-11e8-9e26-47215a048c4d.png)
[Error Log](https://gist.github.com/WenXin20/e27fbda0c969f28f6b09b3622bca76e1)

### Steps to reproduce the problem

1.  Place two different slabs or two torches in the same block space.
2.  Select with a scan tool
3.  View with the build tool
4. ... Profit

**Comment by Raycoms** [comment]
Will be added to a new joint mod compat issue.
