### ISSUE TITLE
Chisel & Bits Integration Improvements

### ISSUE THREAD

**Issue by WenXin20** [ldtteam/minecolonies#3096]
### Minecolonies Version

Version:  v0.10.48-ALPHA

### Expected behavior

- For the builder to be able to use the Chisel & Bits Bag to hold the thousands of bits that will be needed and to use up the bits that are requested.

### Actual Behaviour

-  The builder requests thousands of bits that won't fit into the inventory and the builder can't use the bit bag. The bits requested are also not used up by the builder when placed. 

![c b](https://user-images.githubusercontent.com/12000593/48964807-14901880-ef75-11e8-9536-20bf152ed657.png)

### Steps to reproduce the problem

1.  Creaete a schematic using a lot of chisel & bits
2.  Place the custom schematic.
3. The builder requests bits, but doesn't use it up or use a bit bag.
4. ... Profit

**Comment by WenXin20** [comment]
Looks like issue #3466 is related to this. I can close this one if needed.

**Comment by Raycoms** [comment]
Will have a general inventory support, close din favor of that
