### ISSUE TITLE
Upgrade list and builder hut resource request lists don't match causing delays and DM out of route time. 

### ISSUE THREAD

**Issue by TheStrato** [ldtteam/minecolonies#3098]
### Minecolonies version

Version: minecolonies-1.12.2-0.10.49-ALPHA-universal

### Expected behavior

WYSIWIG build lists. 

### Actual behaviour

You queue up a build/upgrade and it tells you the things you will need for that build. You got to the builder hut to fulfill all those items and several things aren't requested that you just saw on the build/upgrade list. The builder will then attempt to build with what they have and then stop when they have to build the item that wasn't on the list that you didn't give it when the process started. 

### Steps to reproduce the problem

1. Place a deliveryman plot as it is one of the quickest builds that has issues. 
2. See the list of items that will be required for that build and then accept so it queue's a build request for the builder. 
3. Proceed to go to the builder hut to top up all those items and notice that some things like doors, beds, the occasional torch or ladder are not in the resource list. 
4. Wait for the builder to start on that level of the build and see that when it gets to said items it must wait for either you or the warehouse to supply the item since it wasn't on their resource manifesto at the start. 

Quick example. Deliveryman4 waits for a Dark Oak Door for the "wooden" version of the building.

**Comment by Raycoms** [comment]
The problem of this is that in the building process a few of the existing blocks get broken. For example, the doors get broken as soon as the builder changes the block under them, then he will recognize he needs doors a bit later. Unfortunately, that's not something we can actually cope with. That's impossible to detect.

**Comment by TheStrato** [comment]
Could you perhaps give it something to the effect of a 10 block radius "magnet mode" while it is building/upgrading so that if an event like that happens it would pick up the door it broke before it realized it needed another one?

**Comment by Raycoms** [comment]
That's something we can discuss, you would have to create an issue for that
specific idea then.

Am Sa., 24. Nov. 2018 um 09:34 Uhr schrieb Strato <notifications@github.com

**Comment by TheStrato** [comment]
Done. #3099
