### ISSUE TITLE
[Feature Request] Solution for builder resource issues. 

### ISSUE THREAD

**Issue by TheStrato** [ldtteam/minecolonies#3099]
Pulled from bug report #3098 

Could you perhaps give it something to the effect of a 10 block radius "magnet mode" while it is building/upgrading so that if an event like that happens it would pick up the door it broke before it realized it needed another one?

**Comment by Michael-Phoenix** [comment]
It would probably be enough to give it the same pickup distance as the building/placing reach distance.

**Comment by Raycoms** [comment]
Closed in favor of joint issue.
