### ISSUE TITLE
[Feature Request] Set claim limits per person

### ISSUE THREAD

**Issue by n3t-w0rk** [ldtteam/minecolonies#3100]
I'm looking into creating a server that runs minecolonies, and I'd really like it if there was a command to set the chunk radius that can be claimed per person. So, for example, the server max size would be 64 chunks, but each player starts with 8 chunks and can increase their limit through playing more. This would really help in making sure that players can make large towns, but new players can't claim a large area then leave.
Thanks :)

**Comment by Raycoms** [comment]
manually that is possible when admins execute the claim command around a
colony. Automatically, we got an issue for that already to include it in
the progress of playing.

Am Sa., 24. Nov. 2018 um 20:13 Uhr schrieb n3t-w0rk <
notifications@github.com>:
