### ISSUE TITLE
Problems with the builder or courier v1.12.2-0.10.49-ALPHA

### ISSUE THREAD

**Issue by ZzylinN** [ldtteam/minecolonies#3101]
Version:
minecolonies-1.12.2-0.10.49-ALPHA-universal
forge 1.12.2-14.23.5.2768
other mods

The builder asks for wheat although it is in storage. Couriers do not bring wheat to the builder.

On the minecolonies-1.12.2-0.10.45-ALPHA-universal version, the builder built one of the two farms completely. The second part partially completed. After minecolonies has been updated to version 10.49-ALPHA

![2018-11-25_15 25 22](https://user-images.githubusercontent.com/34644142/48977886-706db500-f0cd-11e8-9b01-3cfb6a744487.png)
The construction of the second farm is carried out on the minecolonies-1.12.2-0.10.49-ALPHA-universal version, on which the stander asks for wheat.

![2018-11-25_15 25 52](https://user-images.githubusercontent.com/34644142/48977908-d8bc9680-f0cd-11e8-9cd0-39e15ee42b79.png)
Wheat in stock

![2018-11-25_15 50 04](https://user-images.githubusercontent.com/34644142/48977910-dd814a80-f0cd-11e8-92da-db40bd1bfddd.png)
Builder requires wheat

Logs:
[log25.11.18.txt](https://github.com/ldtteam/minecolonies/files/2612991/log25.11.18.txt)

**Comment by Raycoms** [comment]
please do /mc rs reset colony: yourcolonyid

Am So., 25. Nov. 2018 um 09:08 Uhr schrieb Sasha <notifications@github.com>:

**Comment by ZzylinN** [comment]
> please do /mc rs reset colony: yourcolonyid

Did as you wrote, but did not help!
Wrote:
/mc rs reset colony: 1
![2018-11-25_19 47 01](https://user-images.githubusercontent.com/34644142/48979890-b2a5ef00-f0eb-11e8-9fab-c0479f1e8c78.png)

But the builder asks for wheat anyway :(
![2018-11-25_19 46 29](https://user-images.githubusercontent.com/34644142/48979897-d1a48100-f0eb-11e8-9f4a-569b1b3bcdae.png)
![2018-11-25_19 46 35](https://user-images.githubusercontent.com/34644142/48979900-d5d09e80-f0eb-11e8-828c-c370907afb78.png)

**Comment by Raycoms** [comment]
It seems like the warehouse chest with wheat is not registered, can you try
to tell your builder to repair it?

Am So., 25. Nov. 2018 um 11:54 Uhr schrieb Sasha <notifications@github.com>:

**Comment by ZzylinN** [comment]
Repair warehouse?

**Comment by Raycoms** [comment]
yes

Am So., 25. Nov. 2018 um 11:57 Uhr schrieb Sasha <notifications@github.com>:

**Comment by ZzylinN** [comment]
did not help, still asks for wheat :(

**Comment by Raycoms** [comment]
Now after repair click cancel once, still asking?

Am So., 25. Nov. 2018 um 12:06 Uhr schrieb Sasha <notifications@github.com>:

**Comment by ZzylinN** [comment]
1. I canceled the farm upgrade.
2. clicked to repair the warehouse (ran to the warehouse, climbed to the second floor and wrote the construction of the warehouse in chat) the builder had no requests.
3. clicked to upgrade the farm from level 4 to level 5 (the builder ran to the farm, then returned to his hut with a request)

**Comment by Raycoms** [comment]
did he finish the repair of the warehouse?

Am So., 25. Nov. 2018 um 12:12 Uhr schrieb Sasha <notifications@github.com>:

**Comment by ZzylinN** [comment]
Clicked cancel the request wheat. After a couple of seconds, the request for wheat appeared again.

**Comment by ZzylinN** [comment]
> did he finish the repair of the warehouse?

Yes

**Comment by Raycoms** [comment]
That's weird.

Am So., 25. Nov. 2018 um 12:15 Uhr schrieb Sasha <notifications@github.com>:

**Comment by ZzylinN** [comment]
![2018-11-25_20 14 31](https://user-images.githubusercontent.com/34644142/48980129-1978d780-f0ef-11e8-8e32-ee8b81846feb.png)

**Comment by ZzylinN** [comment]
Now I will try to stop the update, repair and again update from 4 to 5 level

**Comment by Raycoms** [comment]
Maybe destroy the rack and then upgrade, it's weird, because this means
something happened which deregistered the rack badly from the warehouse.

Am So., 25. Nov. 2018 um 12:23 Uhr schrieb Sasha <notifications@github.com>:

**Comment by ZzylinN** [comment]
The builder brought everything he wanted and he finished building the farm!
I apologize if you are disturbed. Probably it turned out some kind of glitch when moving to a new version during construction.

Only with a miner this way is not solved: (
The miner constantly asks for a pickaxe. #3077

PS: What are the labels in the farm and storage?

**Comment by ZzylinN** [comment]
PS: What are the labels in the farm and storage?
