### ISSUE TITLE
Miner spinning endlessly

### ISSUE THREAD

**Issue by J0bzers** [ldtteam/minecolonies#3103]
Version: minecolonies-1.12.2-0.10.48-ALPHA
Forge: 1.12.2-14.23.5.2768
Other mods: What Are We Looking At, Forestry, Just Enough Items, Fairy Lights, Dynamic Trees & Biomes o' Plenty, 

Problem:
The miner goes to 1 spot and starts endlessly spinning. At night he goes to his bed, in the morning he goes back to spinning again. There is enough work for him and he has everything he needs. I fired one and hired another, new one goes to the exact same spot and starts spinning too! I killed one, hired the new one, same result. I repaired, leveled up and moved my mine, all with the same result. Recalling also doesn't do anything. Guy goes straight back to spinning. Destroying the blocks he's spinning on doesn't do anything either. He just moves 1 block and starts spinning there.

**Comment by Raycoms** [comment]
Can you send us your world?

Am So., 25. Nov. 2018 um 12:42 Uhr schrieb J0bzers <notifications@github.com

**Comment by J0bzers** [comment]
Hi, I actually finally fixed it by destroying the block he was spinning on 4 times in a row. So whenever I destroyed the block, he would fall one down, jump up and move 1 block. Repeated this process and somehow he went back to mining again.

**Comment by Raycoms** [comment]
That's weird, when it happens again please send us the world so we can
check on it

Am Fr., 30. Nov. 2018 um 14:29 Uhr schrieb J0bzers <notifications@github.com
