### ISSUE TITLE
[Feature request] Craftsman's Workshop

### ISSUE THREAD

**Issue by keldor314** [ldtteam/minecolonies#3111]
It would be really nice to have the a colonist able to craft a large number of possibly complicated recipes.  

Things like:
All those fiddly medieval wall pieces
Shingles
Stairs, fences, slabs, and so forth, in several different material types
Torches, item frames, armor stands, and any number of semi-rarely used components
Intermediate items such as sticks

The builder just doesn't have enough recipe slots to cut it, and can't craft 3x3 recipes in any case.

**Comment by PoroUsedSnax** [comment]
3x3 crafting has been planned for a while and will come with a range of workers to fit all crafting cases, the system is ready but it still needs to be implemented with the request system properly.
