### ISSUE TITLE
Herders never ever work.

### ISSUE THREAD

**Issue by burah** [ldtteam/minecolonies#3112]
Version: minecolonies-1.12.2-0.10.53-BETA-universal.jar

### Expected behavior

Herders to work after being given what they need.

### Actual behaviour

They just stand in their huts after i fulfill their requests and don't do anything but ask for 2 carrots or 2 wheat or two seeds every few seconds or minutes. They are upgraded to level 2 and I see no cow, pig or chicken. 

### Steps to reproduce the problem
 Just fulfill their requests and watch them do nothing.

**Comment by Raycoms** [comment]
You have to give them the cows, chickens and pigs and then they start
working reproducing them etc.

Am Do., 29. Nov. 2018 um 16:03 Uhr schrieb Spleen Vitals <
notifications@github.com>:

**Comment by burah** [comment]
Oh, thanks, man. It works perfectly.
