### ISSUE TITLE
Builder frequently has full inventory when going to restaurant. 

### ISSUE THREAD

**Issue by masternetra** [ldtteam/minecolonies#3116]
### Minecolonies version
Version: 0.10.27 - 0.10.54

### Expected behavior
Builder Tries to Dump inventory in Build Hut first then goes to stuff his/her face at restaurant. (Or at least tries to free one spot up for food)

### Actual behaviour
Builder heads straight to restaurant with a full inventory.

### Additional Notes
Have "builderInfiniteResources" set to true.
(Also Recommend having Builder zero his personal inventory of everything except food for the following situations [while builderInfiniteResources is set to true of course]: Finishing Construction, When construction is canceled, Going to Home/Townhall for the night, Going to the restaurant. Instead of dumping whatever is spawned into builder hut's inventory.

### Steps to reproduce the problem
1. Have Builder with Worker
2. Have stocked and staffed restuarant.
3. Have Builder build stuff.
4. Wait.

**Comment by Nightenom** [comment]
@Raycoms bump
