### ISSUE TITLE
Assign Teachers to Training Huts

### ISSUE THREAD

**Issue by Raycoms** [ldtteam/minecolonies#3120]
As extensions of the Trainings huts for Archers and Knights one could allow to additionally assign higher leveled people of that profession to act as teachers and boost the xp gain.

**Comment by GanthorPrime** [comment]
That will be realy nice to see.

I general, the idea to get gains on the highers lvls, appart of the enhanced skills for the specific work is very wanted. I thing we need some incentive to keep our citizens leveling up and care about the high leveled ones. 

That can be in the form of:

1.- the ability to acts as teachers like this one starting from a high lvl.
2.- the ability to have a bodyguard (a guard asigned to the citizens, that spawns near on taking mob damage)
3.- special abilities (i.e more inventory for the builder, hp for the guards, etc). 
4.- consume the level points as a resource for something, just like in vanilla you consume your lvl points to enchant, repair, etc.

Im very confindent that in point 4, you can inject some realy cool features to the mod, and maybe start using the book droped by the barbarians (ancient tomes) to, i dont know, imprint the experience gained by the worker in an anchanted book?. or if that workers die, you can transfer some of his experience to a new worker... etc etc

**Comment by Raycoms** [comment]
Closed in favor of joint issue.
