### ISSUE TITLE
Prison for Mobs

### ISSUE THREAD

**Issue by Raycoms** [ldtteam/minecolonies#3121]
Prison building with prison guard and cells.

Can Imprision certain mobs (pirates and barbarians)
Max cap of 1 prisioner per level.
Per prisoner, there is a chance of you getting a coordinate with some loot (written in the GUI).
But, the attacks will be stronger and more often as long as they're captive.

Todo:
- [ ] Prison building
- [ ] Prison guard which can capture 1 K.O Barbarian or Pirate per raid 
- [ ] Chance of Barbarians or Pirates getting K.O from guards (triggers prison guard to come)
- [ ] Triggers stronger raids
- [ ] Random chance of generating position
- [ ] Random loot at position (special chest with some useful items for colonies)

**Comment by Rosomah** [comment]
Looks nice.

**Comment by Raycoms** [comment]
Closed in favor of joint issue.
