### ISSUE TITLE
Upgrading medieval oak fishery  to level 5 removes blocks outside of the building's bounding box

### ISSUE THREAD

**Issue by kmarple1** [ldtteam/minecolonies#3123]
### Minecolonies version

Version: 0.10.48-ALPHA

### Expected behavior

- Construction of buildings should not modify terrain outside of the bounding box created when placing or upgrading them.

### Actual behaviour

- When upgrading the medieval oak fishery to level 5, a section of blocks about 6 deep x the fishery's width x  unknown height is removed. This is probably meant to be on the "outer" (water-side) edge of the structure, but in my case, it wiped out half a house and required manually repairing the terrain.

### Steps to reproduce the problem

1. Upgrade the medieval oak fishery to level 5 with something other than water on each side of it's bounding box.

**Comment by Raycoms** [comment]
That happened because carlsanor updated the fishery hut schematic. This shouldn't happen anymore.
