### ISSUE TITLE
Suggestion - Option to reduce field management to 1 per worker.

### ISSUE THREAD

**Issue by masternetra** [ldtteam/minecolonies#3124]
As it currently stands I frequently find the farmer having difficulty maintaining more then one farm and would like to restrict them to one field per farmer, maybe even have the ability to manually assign workers to a specific fields.

**Comment by Zhythero** [comment]
I think we can already do this via the page 2 of Farmer's GUI

**Comment by Raycoms** [comment]
Closed in favor of joint issue.
