### ISSUE TITLE
crash on minecolonies-1.12.2-0.10.58-ALPHA-universal version

### ISSUE THREAD

**Issue by ZzylinN** [ldtteam/minecolonies#3125]
When you download the game immediately gives crash.

The log is attached:
[log03.12.18.txt](https://github.com/ldtteam/minecolonies/files/2637907/log03.12.18.txt)

**Comment by PoroUsedSnax** [comment]
I'm not seeing anything referencing Minecolonies in that crash log, so I would guess something else is likely causing it

**Comment by cjser** [comment]
Got same problem
[latest.log](https://github.com/ldtteam/minecolonies/files/2638076/latest.log)
[debug.log](https://github.com/ldtteam/minecolonies/files/2638077/debug.log)

**Comment by NotActuallyTerry** [comment]
The issue is 100% related to minecolonies, reverting to 0.10.53 fixes the issue.
The debug log shows FML trying to load minecolonies directly prior to the crash.

**Comment by Raycoms** [comment]
Yeah it is related, we're investigating

**Comment by Raycoms** [comment]
fixed
