### ISSUE TITLE
crash on 1.12.2-0.10.59-ALPHA placing camp second person

### ISSUE THREAD

**Issue by SkyTech6** [ldtteam/minecolonies#3129]
### Minecolonies version

Version: 1.12.2-0.10.59-ALPHA 

When someone other than the host of a local server attempts to place a supply camp, the game just immediately crashes for them on right clicking the ground. It does work for the host though. 

Both using same version, game edition, and forge version. 

### Steps to reproduce the problem
1. Start a LAN world (might happen on servers? idk I'm playing LAN with friend)
2. Second Player (Not Host) get Supply Camp. 
3. Find fitting location for camp. 
4. Right click on ground.
5. Crash.

[crash-2018-12-04_01.46.04.txt](https://github.com/ldtteam/minecolonies/files/2642920/crash-2018-12-04_01.46.04.txt)

**Comment by Raycoms** [comment]
fixed
