### ISSUE TITLE
No housing in barracks towers

### ISSUE THREAD

**Issue by Grummelkater** [ldtteam/minecolonies#3131]
### Minecolonies version

Version: 1.12.2-0.10.62

### Expected behavior
When building/upgrading a barracks tower a new citizen should spawn.

### Actual behaviour
After upgrading to 0.10.59 all my barracks towers aren't recognized as housing any more. All my soldiers demand houses now. Upgrading a 
house will make one of them move in, but be still listed in it's tower. Fireing him will remove him from his house and the tower.
![2018-12-04_16 43 18](https://user-images.githubusercontent.com/40459392/49454937-858dc680-f7e6-11e8-948f-a6ce6ac244d1.png)

**Comment by Grummelkater** [comment]
This also happens when I'm creating a new SP-World. I was on creative, spawnes in a lvl3 TH and a lvl3 Citizen Hut. That gave me the expected 6 citzens. Spawning in a lvl3 Barracks and a lvl3 Barracks Tower I should have got 3 more citizens.
Instead 3 unemplayed ones out of my 6 existing citizens were auto-hired in the tower and no new ones spawned.

**Comment by Rosomah** [comment]
Same here. Also there are some minor inconsistencies such as saying that a Knight needs a new house, where the person is actually a ranger.

It would be very convenient if you could make it so the people that are employed at the barracks count as if they're sleeping at the barracks, regardless if they were spawned by building or upgrading a house or town hall and the other way around; if a citizen is spawned by upgrading a barracks tower and you employ him as a lumberjack for example, he should ask for a house to live in.

**Comment by Raycoms** [comment]
fixed.
