### ISSUE TITLE
Lumberjack Egg Thief

### ISSUE THREAD

**Issue by MissMarley** [ldtteam/minecolonies#3133]
### Minecolonies version
Custom Setup
Minecraft v 1.12.2 (1.12.2 forge 2768)
Minecolonies version ripped from ATM3 via Twitch

Version: 

### Expected behavior
Lumberjack does tree-choppy things. Plants trees. So on.

- 

### Actual behaviour
Theiving hoarder Lumberjack (who's hut is right next to the Chicken Tenders hut) chopped exactly one tree before deciding that he'd much rather incessantly pick up every single chicken egg/feather that spawns. So it becomes a lovely dance of him going into the chicken coop, picking up every item then leaving. Then making it halfway towards a tree before going back like a dirty egg addict.

### Steps to reproduce the problem
1.) Yell at Lumberjack
2.) Set up an intervention with the builders, resturant owner, and chicken tender.
3.) I suppose I could move the lumberjacks setup to somewhere else but I LIKE IT THERE and it fits so nicely. And there's spruce trees near there and thats what I want him to chop, dangit.

**Comment by Rosomah** [comment]
lol

**Comment by marchermans** [comment]
Hahaha that description. Brilliant.
