### ISSUE TITLE
Schematics not Reflecting Upgrade to Structurize

### ISSUE THREAD

**Issue by raistlain** [ldtteam/minecolonies#3134]
### Minecolonies version

Version:  minecolonies-1.12.2-0.10.65-ALPHA-universal.jar
and structurize-1.12.2-0.10.17-ALPHA.jar

### Expected behavior

Buildings already built in Minecolonies would look identical. Schematics would be identical. Structurize would be delivered with Minecolonies or Minecolonies list Structurize as a dependency.

### Actual behaviour
Items specific to Minecolonies such as shingles are not switched to structurize and are removed from the world upon upgrade. Schematics such as the Medieval Oak or Spruce building style no longer have shingles and are not rendered.

### Steps to reproduce the problem
1. Play on a previous version
2. Upgrade to newest version.
3. Problem occurs
3A. Download structurize and install.
4. Problem persists.

**Comment by Raycoms** [comment]
Does this happen on the client or on the server?

**Comment by Raycoms** [comment]
I was able to reproduce it, working on it. Seems to be a forge bug

**Comment by raistlain** [comment]
Problem does not appear in Release 68, but does in Alpha 69.

Occured both from upgrading from Alpha 56 to 69 and 68 to 69 but did not occur when upgrading from Alpha 56 to 68

**Comment by Raycoms** [comment]
Do you mean in the pre-render or in the world?

Am Mo., 10. Dez. 2018 um 23:39 Uhr schrieb raistlain <
notifications@github.com>:

**Comment by ghost** [comment]
In the world, forgot to check the schematics

**Comment by Raycoms** [comment]
I opened a ticket for that on forge support. waiting for them to respond.

Am Di., 11. Dez. 2018 um 03:22 Uhr schrieb Itxpertongit <
notifications@github.com>:

**Comment by Nightenom** [comment]
Bump, any progress? (maybe link to the forge ticket)
