### ISSUE TITLE
workers hard lag

### ISSUE THREAD

**Issue by ghost** [ldtteam/minecolonies#3136]
I noticed superioursly strong lag, i dont know what is the reason of it but when my colony reach a size 22 workers, they just lag strongly,  this lag is connected with chest lag and other ticks, its really hard to describe but below is link to my google drive with movie where you can see what is happening.  my computer is strong ( witcher 3 on ultra ) so this  is not the problem with weak components. i also havent noticed this type of lag even with 100 other mods. 

Minecraft 1.12.2 minecolonies 0.10.63 alpha-universal

### Expected behavior

- make minecolonies working flow, without this lag. 

### Actual behaviour

just watch it : https://drive.google.com/open?id=1RY2isITbUMAow8T3hURXfMn2HdZrrIkx

### Steps to reproduce the problem

1. problem is with optimalization, possibly tickrate or something like that, it should be remanaged 
2. possibly if you would make ticks of workers with first priority ( first game is rendering terrain, then workers and their actions and after that randomticks like seeds growing etc. 
3. it should remove lag 
4. game should works more flowly

**Comment by Raycoms** [comment]
Could you run a profiler on it?

Am Do., 6. Dez. 2018 um 12:16 Uhr schrieb lucibal <notifications@github.com

**Comment by ghost** [comment]
i run tickprofiler ( i thing that you have on mind, ) below link to folder of this issue , there are all movies with lag, profiler etc.
movie with time describe 14 50 24 is this one you already seen  , rest four are the movies with profiler runed.  idk, i use it correctly, if you could give me more precise instructions what i have to do it would be wonderfull because i am not into minecraft programming =)
https://drive.google.com/open?id=1yBuFl3QVAwSzne6EuyD2GBzrBJ3O9ajj

Ps. as you can see on the new movies, lag is always different, sometimes its just half of second , but sometimes even 5 minutes

**Comment by Raycoms** [comment]
That one would be perfect: https://github.com/sk89q/WarmRoast

Am Do., 6. Dez. 2018 um 14:47 Uhr schrieb lucibal <notifications@github.com

**Comment by Raycoms** [comment]
I heard: https://github.com/lucko/spark is easier to use

Am Do., 6. Dez. 2018 um 14:54 Uhr schrieb Ray Neiheiser <
ray.neiheiser@gmail.com>:

**Comment by ghost** [comment]
here you have first one i made with spark https://sparkprofiler.github.io/#2SLnIZYCVC but possibly be carrupted because my computer has turn off thrugh doing it ( software update)
here is a second one maked when lag doesnt have place ( a moment when colony was flow) https://sparkprofiler.github.io/#hwhjV1pH2l
here is when the lag has started  https://sparkprofiler.github.io/#ALlZqe93Al

first scan is longer because i wasnt know how to use spark, secon and third was scaned during 20 seconds. I also uploading at the moment movie from the first sampling, where you cans see that a lot of ticks takes much more than 1000ms , movie will be in folder i sent you before
also , after killing all the workers and start regrowing colony for a few minutes ticks takes  just 2-9 ms ( i note also that lag is not connected with number of workers, sometimes it happens even if there is only one ), on the maps without colony, with all other mods i am using ticks also takes 2-9ms and there is no lag even on rendering radius 64 chunks.

**Comment by Raycoms** [comment]
It says here that 70% of the performance goes to throwing exceptions in the
log, can you send us the log?

Am Do., 6. Dez. 2018 um 18:01 Uhr schrieb lucibal <notifications@github.com

**Comment by ghost** [comment]
how to do that? any tutorial ?
i really dont know where it is

By the way. 
i just delete colony and create a new one in same world, now colony has 150 colonists and no lag noticed. colony stays in same place, building has different positions but colony is much bigger than precious one so it makes this bug much more suspicious

**Comment by aetherpirate** [comment]
What launcher are you using?

**Comment by ghost** [comment]
tlauncher

**Comment by aetherpirate** [comment]
Don't use a cracked launcher

**Comment by ghost** [comment]
i was forced to do it because normal launcher has a lot of crashes on my computer, if mojang will improve it i will back to normal one...  

i find a logs, it takes a few minutes but found it =) 
here you have link https://drive.google.com/open?id=1YIaHSO6Tbu9QKaa1ZVMiPRNenyutWE9j
i copy just logs from the day when i open the issue, because in file with log i have over 300 of them...

**Comment by marchermans** [comment]
Cracked launchers are not supported. Period.
