### ISSUE TITLE
Crash w/ Acorns Mod

### ISSUE THREAD

**Issue by WenXin20** [ldtteam/minecolonies#3140]
### Minecolonies Version

Version: 0.10.65-ALPHA

### [Acorns](https://minecraft.curseforge.com/projects/acorns) Version

Version: ALPHA-0.1

### Expected Behavior

-  For the lumberjack to work normally with the acorns mod. Also for him to be able to plant acorns.

### Actual Behaviour

-  The game crashed, although I don't know what the lumberjack was doing at the time of the crash. I was looking in my inventory when it crashed. I also had the acorns mod installed for a while now, so I don't know why it is just now causing a crash.

[Crash Log](https://paste.dimdev.org/quturukome.mccrash)
[Latest.log](https://gist.github.com/WenXin20/4193d4f869843b1a0d0efea9af20324d)
### Steps to Reproduce the Problem

1.  Install the Acorns Mod
2.  Place a lumberjack
3.  Wait for a crash?
4. ... Profit

**Comment by Raycoms** [comment]
fixed
