### ISSUE TITLE
Lumberjack Compat with Grimpack's Cocoa Sapling

### ISSUE THREAD

**Issue by WenXin20** [ldtteam/minecolonies#3141]
### Minecolonies version

Version: v0.10.65-ALPHA

### Expected behavior

-  For the Lumberjack to plant cocoa saplings, which is done by right-clicking the cocoa fruit on the ground.

### Actual behaviour

- The Lumberjack instead plants an oak sapling.

### Steps to reproduce the problem

1.  Grow a cocoa tree from grimpack
2. Have the lumberjack cut it down
3. Watch him/her place a oak sapling instead.
4. ... Profit

**Comment by Raycoms** [comment]
Will be added to a new joint mod compat issue.
