### ISSUE TITLE
bug a Supply Ship or a Supply Camp 1.12.2

### ISSUE THREAD

**Issue by demon57730** [ldtteam/minecolonies#3143]
minecolonies-1.12.2-0.10.27-RELEASE-universal.jar
forge 1.12.2 14.23.5.2795

solo and server

The Supply Ship does not give the Town Hall and the Building Tool does not work with a Supply Ship or a Supply Camp

with the Supply Camp it works

**Comment by Raycoms** [comment]
Were you in creative mode?

**Comment by demon57730** [comment]
Creative and survival

**Comment by demon57730** [comment]
without the stick its function in survival

**Comment by PoroUsedSnax** [comment]
If you placed the camp/ship whilst you were in creative, you won't get the town hall/building tool from the chest, as you are easily able to spawn them in
