### ISSUE TITLE
Builder not building armor stands / double ferns. and consume the resources

### ISSUE THREAD

**Issue by GanthorPrime** [ldtteam/minecolonies#3146]
### Minecolonies version
Version: minecolonies-1.12.2-0.10.57-ALPHA-universal.jar 

### Expected behavior
- Builders builds all valid items/blocks in the official huts, official decorations and scaned structures.

### Actual behaviour
- On building a hut / decoration, builder request the resources for an armor stand: the stand and the armor pieces. finaly, he consumes the resources but do not place them in the world. This same problem seems to be happening with double ferns and maybe others.

### Steps to reproduce the problem
1.- Order the builder to build something that require some armor stands with armor pieces (i.e. spruce)
2.- Give the stands and the armor pieces, wait it to finish and 
3.- Check if the armor stands are in place, (no armor stands anywhere)
4.- Scan any deco with double fern
5.- Order to build it somewhere, check the double fern, same behaviour

at the end of writing this i saw some alfas that extract the building feature to a separated mod and integrates it as dependency but there are some bugs reports that it seems are still there. will try it tomorrow

**Comment by Raycoms** [comment]
I think I can debug this tomorrow. Maybe I will only get time on
tuesday though.

Am Mo., 10. Dez. 2018 um 00:03 Uhr schrieb GanthorPrime <
notifications@github.com>:

**Comment by GanthorPrime** [comment]
Just to add:   the builder consume the resource AND is counted against the progress of the work correctly like if was placed in the world (builder can finish the job).  

its just that the armor stands or the double fern are not placed so if, for example, you call for a 'repair' on the hut again, the new work will list all the resources for the armor stand / double ferns again.

I confirmed this repairing lvl 5 barracks, and barracks towers.

**Comment by PoroUsedSnax** [comment]
From my experience with this, they do actually place the item (I checked with armour stands) Just that it for some reason gets deleted seconds afterwards, hence why the resources get used but there is nothing to show for it
