### ISSUE TITLE
Herders / Fishers eats all their gathered  raw meat / fish

### ISSUE THREAD

**Issue by GanthorPrime** [ldtteam/minecolonies#3147]
### Minecolonies version
Version: minecolonies-1.12.2-0.10.57-ALPHA-universal

### Expected behavior
Herders gather meat, fishers gather fish and deliveriman gather all to the warehouse. Workers do not eats their raw gathered resources and instead use cooked food or go to the restaurant to find it.  Maybe we need a sort o black list on the food this workers eats since the food they produce is know and we can use some comon sence: Is not that bad when a farmer eats some carrots, or the bakers eats some of the bread they produce, but we do not want our farmers eating all raw potatos, fishers eating all raws fish, herders eating all their raw meat.

### Actual behaviour
In last versions, is almost imposible to find some meat / fish gathered by fishers and herders and wen i start checking, i see this guys eating all their raw food before goin to the restaurant.

¿Are the food properties taked into account to fill the citizen hunger? (is a cooked food better than a raw food in terms of food points?

Not sure the exact alpha version where we notice the food requirements rockets, but now, 50 citizens can empty the entire wooden restauran storage filled with stacks of food in 2 days. (maxed lvl and storage).

### Steps to reproduce the problem
1. build a town, a restaurant, build all herders, fishers, farmers. all max lvl
2. fill the restaurant with food
3. check how the fishers eats raw fish, herders eats raw meat, etc
4. reach 50 citizens, fill the restaurant with lots of food, check in 1-2 days... they wil eat all

**Comment by GanthorPrime** [comment]
Just checking in the second page of issues and found  #3091 that seems related (sheepherder eats raw mutton), but description here i think is more complete

**Comment by Raycoms** [comment]
I agree, we can improve this by not letting them raw food which is cookable.
