### ISSUE TITLE
Custom/imported schematics not showing up in build menu

### ISSUE THREAD

**Issue by Talyda** [ldtteam/minecolonies#3148]
### Minecolonies version
I've tested on 4 or 5 of the alphas since the change with structurize was introduced (.58) the latest one I tried was the current alpha (.67)

### Expected behavior
Build custom buildings

### Actual behaviour
They don't appear in build menu

### Steps to reproduce the problem
I've tried this in the current official minecolonies (v 4.54.1) pack with minecolonies alpha .52 and the schematics show up, and can be built. I put several of the alpha builds in the pack, and as soon as the structurize changes were made, the schematics no longer show up in the build menu.

Schematics have been downloaded from your forums, and I put them in the folder:
D:\Users\username\Documents\Curse\Minecraft\Instances\MineColonies Official\minecolonies\schematics 

I always use the build wand to build.

It was on a clean install of the modpack too, I just reinstalled it today because of another weirdness I was having, and I hadn't changed any of the default settings or config files.

**Comment by PoroUsedSnax** [comment]
With the update to structurize it seems that schematics and such are now moved to its folder, so instead of putting it in `minecolonies/schematics` you will want to put it in `structurize/schematics`.

I'm not 100% sure on this personally, but I do imagine that is the case.

**Comment by Talyda** [comment]
You are exactly correct! =)  Just tested it out on the official pack, with .65 alpha installed, moved them to the structurize folder and they were available to build in game. Didn't even think to look and see if there was a folder for them there. Thanks!
