### ISSUE TITLE
Barrack Guards Do Not Equip Tinker Armor (Construct's Armory Mod Support)

### ISSUE THREAD

**Issue by NachtRaveVL** [ldtteam/minecolonies#3154]
### Minecolonies version

Version:  minecolonies-1.12.2-0.10.68-RELEASE-universal.jar

### Expected behavior

Guard sees tinker forge armor's material level (using Construct's Armory mod, tinker forge extension to allow players to make tinker armor) and applies sames armor level rules to it as it does vanilla armor.

### Actual behaviour

Guard does not equip tinker forge armor past level 3 tower because it sees all tinker armor as Leather.

### Steps to reproduce the problem

1. Craft tinker forge armor using  mod (tinker). Test using Flint Armor set (stone level), and Manyullyn Armor set (obsidian level).
2. Equip guard of tower level <= 3 with armor.
3. Note that guard can wear *all* levels of tinker forge armor.
4. Upgrade tower to level 4, notice that guards can no longer equip any tinker forge armor.

Reference: https://wiki.minecolonies.com/source/systems/workerinfo

**Comment by NachtRaveVL** [comment]
I played around with this more.

It would appear that upgrading the barracks tower to level 4 from level 3 is what is causing this issue.

My level 3 towers still allow me to equip tinker armor on my soldiers. Level 4 does not. I'll try upgrading to a level 5 tower to see if it persists.

**Comment by Raycoms** [comment]
What kind of tinkers armor is it? Depending on the resistence level of the
material they will request something better

**Comment by NachtRaveVL** [comment]
So this is fun, upgrading to level 5 barracks tower, it says, in the open requests section for armor on the soldiers stationed there, "minimal level:Gold and maximal level:Iron"

For the level 4 barracks tower, it says, in the open request section for armor on the soldiers stationed there, "minimal level:Gold"

It was my understanding that upgrading these towers should allow the soldiers to carry higher level gear? It seems to work for the weapons, at least, but not for the armor.

Sounds like there is a bug somewhere in there where it's limiting the max armor rating *down* as the barracks tower increases in level.

The armor I've been experimenting with is osmium, steel, and supremium.

**Comment by NachtRaveVL** [comment]
Level 3 barracks tower (with level 4 barracks), for armor, says "minimal level:Leather and maximal level:Iron".

Funny how the level 3 allows me to equip soldiers with osmium and steel armor, but not level 4 or 5 barracks towers.

**Comment by Raycoms** [comment]
It depends on how the armor is implemented, I believe it doesn't use the
vanilla values, so they are not correctly evaluated and thus we detect it
as a leather or gold type but actually its much higher.

Am Mi., 12. Dez. 2018 um 23:55 Uhr schrieb NachtRaveVL <
notifications@github.com>:

**Comment by NachtRaveVL** [comment]
Well, I realize that the "level" it talks about isn't a directly the same as the tinker "level" - I remember there being some table somewhere that showed how they mapped.

Still, if you were able to wear high level supremium armor at level 3 barracks tower, upgrading to level 4 should not have caused it to stop working. Supremium, for instance, is Cobalt level, one of the highest tiers.

It doesn't appear to be a minimum issue, but rather a maximum issue. I would wager that there's a negative somewhere in there doing the wrong thing.

**Comment by NachtRaveVL** [comment]
Okay, I have figured out what is going on here.

The mod isn't aware of Construct's Armory mod's extension to Tinker Forge, whereby it allows players to craft armors using a forge. Minecolonies sees all of Construct's Armory mod's armor as Leather armor, and does not allow any guards to equip it beyond level 3 tower.

So basically, what is being asked in this ticket, isn't a bug, it's actually a feature request: To support the Construct's Armory mod's armor extension to tinker's forge.

**Comment by hron84** [comment]
A side question: Minecolonies guards do honor other armors that somewhat more related to vanilla? What armor/toughtness level is required for each tower levels? E.g. Acually Additions Obsi chestplate is 4 armor and 1 toughness but vanilla iron chestplate is 6 armor. Do the mod consider obsi chestplate better or not?

**Comment by Raycoms** [comment]
Will be added to a new joint mod compat issue.
