### ISSUE TITLE
spawn server

### ISSUE THREAD

**Issue by demon57730** [ldtteam/minecolonies#3156]
1.12.2

hello I have a question

does he have a command or object that forbids the creation of a spawn colony on a server?

**Comment by Raycoms** [comment]
There is a configuration setting in the configuration file =)

**Comment by demon57730** [comment]
yes I know I configure but the problem on the f3 mark as if we can build a colony and rtp command does not work because it says no need to tp you can already build here and when we build it says we can not because we are close to the spawn

**Comment by Raycoms** [comment]
there are configs for the rtp distance from spawn as well

Am Mi., 12. Dez. 2018 um 14:28 Uhr schrieb demon57730 <
notifications@github.com>:
