### ISSUE TITLE
Field size limiting not working

### ISSUE THREAD

**Issue by Echo51** [ldtteam/minecolonies#3160]
Version: 1.12.2-0.9.1-RELEASE

### Expected behavior
The farmer actually sticking within the borders delimited by both fence and stone blocks

### Actual behaviour
They do not. just till everything tillable within range of the scarecrow.
![javaw_2018-12-13_00-06-58](https://user-images.githubusercontent.com/41641960/49904775-920bc200-fe6b-11e8-9543-838848d1e0dd.jpg)

### Steps to reproduce the problem
Build farmer, build field, place scarecrow. let them till the area and watch them over-till.

Edit:
Is this something the wiki fails to explain properly? it makes it sound like you can border fields like this with blocks to define a size.
https://wiki.minecolonies.com/source/buildings/farm

**Comment by Raycoms** [comment]
I found that as well, I started debugging it already and found one bug in the code, I'll check if this is what causing this

**Comment by Raycoms** [comment]
SHould be fixed
