### ISSUE TITLE
Crash - Viewing clipboard, only 1 request, after teaching Hut a recipe

### ISSUE THREAD

**Issue by spacewolfcub** [ldtteam/minecolonies#3162]
### Minecolonies version

Version: minecolonies-1.12.2-0.10.53-BETA-universal.jar   

### Expected behavior

- Right click Minecolonies clipboard, see list of requests.

### Actual behaviour

- Game crashed when clipboard right-clicked.

https://paste.dimdev.org/ecolorixod.mccrash

### Steps to reproduce the problem

0. Playing single-player on the TownCraft modpack from TwitchLauncher.
1. BuilderNPC says in chat she wants coarse dirt (needs 4 more while building Miner level 1)
2. I go into BuilderHut and see that BuilderNPC is already there.
3. I teach the BuilderHut the recipe for coarse dirt. 
4. I check BuilderHut inventory (I can't remember what I saw, but I guess I didn't find gravel there because the next thing I did was:)
5. I check BuilderNPC inventory, see she already had gravel and dirt. She seems to just be standing there facing the BuilderHut block. I take the dirt and gravel out of her inventory and back into it. 
6. Right-click clipboard in air while looking at one of the fences in the window of the BuilderHut, there was just air between me and the fence. (I intended to check if I needed to click the Cancel button on the request that was there before to make her craft the coarse dirt herself but I never even got to see the clipboard GUI).
7. Crash. 
8. VanillaTweaks mod sends me to main menu instead of desktop, making that crash report link I pasted above.

**Comment by Raycoms** [comment]
Thanks for the report, this is an issue we have for a while and we are unable to find out what it is. We are currently reworking some of our backend processed in relation to GUIs which will fix this as well.
