### ISSUE TITLE
Deliveryman giving smelter all wooden building materials

### ISSUE THREAD

**Issue by Sickwan** [ldtteam/minecolonies#3163]
### Minecolonies version

Version: 0.10.68 RELEASE

### Expected behavior

The Deliveryman would leave all wooden building materials, apart from standard planks, in the warehouse for the builder to use later on.
- 

### Actual behaviour

The Deliveryman takes any and all fuel sources from the warehouse to the smelter including shingle and timber frames which is tedious to replace and a waste of bricks.
- 

### Steps to reproduce the problem

1. Give the builder wooden materials
2. The delivery man takes the materials from the builders chest back to the warehouse
3. Smelter then requests fuel
4. Deliveryman delivers anything that can be used as fuel.

Is there anyway to decide what the deliveryman will and will not give as fuel?

This isn't a bug as far as I know I just wanted some insight into what could be done to fix this if there is a possible fix

**Comment by Raycoms** [comment]
Yeah, we got an issue for that already. Will be worked on soon.
