### ISSUE TITLE
[Question] why does building a camp in multiplayer puts the dummy blocks

### ISSUE THREAD

**Issue by winsrp** [ldtteam/minecolonies#3164]
Hi when we put the camp up in a multiplayer server we get this, the camp gets placed but it replaces all dirt with the dummy blocks, is it some config or something I cannot seem to find what is causing it.

![image](https://user-images.githubusercontent.com/13665046/49975167-54a64380-ff02-11e8-95df-0ba13421d0cd.png)

using minecolonies-1.12.2-0.10.77-ALPHA-universal.jar

Regards, 

Winsrp

**Comment by Raycoms** [comment]
Can't reproduce this with the newest version.
