### ISSUE TITLE
Lumberjack leave branches behind when chopping trees down

### ISSUE THREAD

**Issue by WenXin20** [ldtteam/minecolonies#3166]
### Minecolonies version

Version: 0.10.77-ALPHA

### Expected behavior

-For the lumberjack to chop all logs, including branches.
### Actual behaviour

-The lumberjack leaves behind all branches of the tree. I have noticed this happen with the [Rainbow Oak Trees](https://minecraft.curseforge.com/projects/rainbow-oak-trees) mod and the [Project: Vibrant Journeys](https://minecraft.curseforge.com/projects/project-vibrant-journeys) cottonwood tree. I don't know if this happens with other large trees

![2018-12-14_00 28 40](https://user-images.githubusercontent.com/12000593/49989315-7114a100-ff3f-11e8-89a0-f1cce51ac3d5.png)

### Steps to reproduce the problem

1.  Plant rainbow oak or cottonwood saplings until a big one sprouts.
2.  Have the builder chop it down.
4. ... Profit

**Comment by Raycoms** [comment]
Thanks for reporting this, please be aware that improvements regarding mod supports are implemented based on popularity of the mod and how gamebreaking the issues are (crashes etc).
Unfortunately, since we have limited time it might need a while until we get to this.

**Comment by WenXin20** [comment]
Ok, that's fine, I'm not in any hurry. Thanks.

**Comment by Raycoms** [comment]
Will be added to a new joint mod compat issue.
