### ISSUE TITLE
Server Crash Ticking Entity - Get Mourn Location

### ISSUE THREAD

**Issue by QueenBonnydust** [ldtteam/minecolonies#3167]
### Minecolonies version
minecolonies-1.12.2-0.10.68-RELEASE-universal.jar

[Server Crash Ticking Entity - Get Mourn Location.txt](https://github.com/ldtteam/minecolonies/files/2679869/Server.Crash.Ticking.Entity.-.Get.Mourn.Location.txt)
[Server Crash Ticking Entity - Logging In Crash.txt](https://github.com/ldtteam/minecolonies/files/2679900/Server.Crash.Ticking.Entity.-.Logging.In.Crash.txt)

### Expected behavior
Citizens die and are mourned, game play continues on the server as per normal.

### Actual behaviour
Server crashes on death (?) of citizen? To be honest I'm not sure the citizen is dead as we had a similar crash with an older release and were able to verify the citizen named (is the named citizen the one who died or the one who is mourning?) was indeed alive and well. I am unable to verify in this instance as every time I log into the server it triggers a crash for the same reason.

### Steps to reproduce the problem
Also installed [Weather, Storms & Tornadoes](https://minecraft.curseforge.com/projects/weather-storms-tornadoes) - build colony, suspect it is triggered by having a citizen picked up by severe storm and dying from fall damage. Unfortunately I was afk when the crash occurred.

**Comment by Raycoms** [comment]
Same crash, will make a patch

Am Fr., 14. Dez. 2018 um 09:34 Uhr schrieb QueenBonnydust <
notifications@github.com>:
