### ISSUE TITLE
Colony Borders aways set to 93

### ISSUE THREAD

**Issue by Classic2000s** [ldtteam/minecolonies#3170]
### Minecolonies version

Version: 

### Expected behavior

- 

### Actual behaviour

-The Colony Border is set to 97 instead of 1000000000 why its doing that?

**Comment by Raycoms** [comment]
It's the colony size in chunks which influences it, the othe rone is
deprecated

Am Fr., 14. Dez. 2018 um 11:08 Uhr schrieb Classic2000s <
notifications@github.com>:

**Comment by Classic2000s** [comment]
there all set to 10000000000

**Comment by Raycoms** [comment]
It also doesn't work on first placement. If you placed the colony already
you have to execute /mc colony claim

Am Fr., 14. Dez. 2018 um 11:11 Uhr schrieb Classic2000s <
notifications@github.com>:

**Comment by Classic2000s** [comment]
or I mean this
![2018-12-14_05 13 33](https://user-images.githubusercontent.com/45876016/50005396-155a1000-ff5f-11e8-9deb-e70487980dbe.png)

**Comment by Classic2000s** [comment]
its suppose to not be 93

**Comment by Raycoms** [comment]
That's your current distance and not the total distance.

Am Fr., 14. Dez. 2018 um 11:14 Uhr schrieb Classic2000s <
notifications@github.com>:

**Comment by Classic2000s** [comment]
I was going to show you one block after 93 but I crashed the game ._.

**Comment by Classic2000s** [comment]
![2018-12-14_05 23 41](https://user-images.githubusercontent.com/45876016/50005860-a8477a00-ff60-11e8-8893-59662d8ad6c6.png)

**Comment by Raycoms** [comment]
do the claim command

Am Fr., 14. Dez. 2018 um 11:25 Uhr schrieb Classic2000s <
notifications@github.com>:

**Comment by Classic2000s** [comment]
you know its just me

**Comment by Classic2000s** [comment]
I cant really use a server
