### ISSUE TITLE
[feature request] builder uses supply chests at job site

### ISSUE THREAD

**Issue by kreezxil** [ldtteam/minecolonies#3172]
Basically the builder could take everything required to build a building and put them in chests just outside the schematic, then without leaving their job site, extract from those chests, when done, the builder would pull up those chests and put them back in it's main block. Of course if it collected stuff in the process, it would unload those chests first.

**Comment by Raycoms** [comment]
We got an issue for that already

**Comment by kreezxil** [comment]
You mean other than #3046? Which you see I linked.

**Comment by Raycoms** [comment]
No it's that one, but that one is how we would make it right.

**Comment by kreezxil** [comment]
that one makes it complicated for you. I'm sure you understand the purpose of cross linking. feel free to delete this issue.

**Comment by Raycoms** [comment]
I'll close this here in favor of th eother one. They are linked so when we start working we can finish this here as #1.0
