### ISSUE TITLE
Throwing a town hall into a fire while you have a colony active breaks the chunks

### ISSUE THREAD

**Issue by Heroshrine** [ldtteam/minecolonies#3173]
### Minecolonies version
0.10.68

Version: 

### Expected behavior
I dunno... maybe deletes the colony (not the buildings and people tho)

### Actual behaviour
Causes a bug that crashes the game whenever you load into the chunk. I know this because I originally discovered it on a server, and it crashed the server, but other people could still play as long as I didn't try to log in. On a single player world it crashes me.

### Steps to reproduce the problem
Place down a town hall.

Get a small town going.

Mine the town hall and throw it into a fire.

**Comment by Raycoms** [comment]
Crashlog please, can;t reproduce.
