### ISSUE TITLE
lang: french

### ISSUE THREAD

**Issue by demon57730** [ldtteam/minecolonies#3174]
Hello I am writing because I am French with a French server. I use the version minecolonies-1.12.2-0.10.68-RELEASE-universal
the concern is that a lot of text has not been translated. I wanted to do it but can not add it

**Comment by Raycoms** [comment]
http://translate.minecolonies.com/

That's the site we use to translate. You can apply there as a translator =)

**Comment by demon57730** [comment]
thank you I will do it later
