### ISSUE TITLE
crash eating

### ISSUE THREAD

**Issue by RandomWord23** [ldtteam/minecolonies#3175]
### Version:
 minecolonies-1.12.2-0.10.81-ALPHA-universal
### Expected behavior

Npcs Eating ?

### Actual behaviour

When i give my villagers food, when they try to eat it, game immediately crashes.
So now i cant give my villagers food otherwise whole minecraft crashes.

### Process:
1. Villagers hungry-food bar completely empty
2. So i give food
3. Game crashes after 1/2 seconds

Log:
[latest.log](https://github.com/ldtteam/minecolonies/files/2691497/latest.log)

**Comment by someaddons** [comment]
update your forge version

**Comment by RandomWord23** [comment]
> 
> 
> update your forge version

Thanks it is working now, thank you very much. I wasn't expecting this could be a issue.
