### ISSUE TITLE
Ore dictionary chest in recipes

### ISSUE THREAD

**Issue by LemADEC** [ldtteam/minecolonies#3177]
### Minecolonies version
Version: 1.12.2-0.10.81

### Expected behavior
Recipes are forcing vanilla chest, preventing integration with other mods.
Consider using 'chest' or 'chestWood' ore dictionary entries instead to support other mods.

### Actual behaviour
Current recipe forces to use vanilla chest.

### Steps to reproduce the problem
Try crafting with chests from Quark.

**Comment by Raycoms** [comment]
@MineShadow7
