### ISSUE TITLE
VanilaFix encountered problem before attempt to crash

### ISSUE THREAD

**Issue by scraw-darkblade** [ldtteam/minecolonies#3181]
https://paste.dimdev.org/muhenecivu.mccrash

MC version: 1.12.2

Minecolonies Version: minecolonies-1.12.2-0.10.68-RELEASE-universal

Scenario: Cancelling some requested equipment, then suddenly VanilaFix prompt a report. Details on the link above.

**Comment by marchermans** [comment]
It happens sometimes. This basically means that you were a tick to late and something already resolved the request. You should be able to start the world again. Right now this is intended

**Comment by marchermans** [comment]
Will be fixed in a future version when the rs gets an overhaul.
