### ISSUE TITLE
New Colonists Not Spawning

### ISSUE THREAD

**Issue by Mocha2007** [ldtteam/minecolonies#3196]
### Minecolonies version
Version: 0.10.88-ALPHA

### Expected behavior

- New Colonists Spawn once enough housing has been constructed

### Actual behavior

- Nothing

### Steps to reproduce the problem
Here is my current colony setup:

- Level 2 Town Hall
- Three Level 2 Houses

Yet only four colonists (the inital four) have spawned. The town hall says 4/4 colonists. I haven't recieved any "blah wants to sleep in a house" notifications since I built the second one, but I do notice the town hall says the housing requirement is yellow rather than green. I checked the houses and two of them house two colonists and one houses none, so in theory the housing requirement should be completely fulfilled. Information from the wiki suggests this should be more than enough to spawn more colonists - what gives?

**Comment by Mocha2007** [comment]
Okay, it turns out this is just part of a different problem.

Restarting Minecraft fixes the problem (and restores the notifications, which I didn't notice I was missing) but after maybe an hour(?) or so I stop getting notifications and I have to restart Minecraft.

**Comment by Raycoms** [comment]
Weird, it seems liek a mod runs either in an infinite loop and doesn't update it or your performance dropped to strong. if you find out what triggers this (maybe through a profiler) please update us with a new issue
