### ISSUE TITLE
Multi-block / multi-piston loses settings between version updates

### ISSUE THREAD

**Issue by nekatu** [ldtteam/minecolonies#3197]
(nekatu on discord) 

### Minecolonies version

Version: minecolonies-1.12.2-0.10.89-ALPHA-universal.

### Expected behavior

Block holds configuration settings across updates

### Actual behaviour

Block appears to return to default settings after a minecolonues update (or perhaps the config is stored client rather than server side?) 

### Steps to reproduce the problem

1. Craft Multi-block
2. Set up with custom range and speed settings
3. Update minecolonies
4. Find original settings in Multi-block instead of custom ones

I switched machines during testing as I've been traveling so the only other thing I can think of is that the Multi-block settings are stored client side on my other machine, but that seems unlikely and would be an issue anyway.

**Comment by Raycoms** [comment]
Yeah, we had to update some important things, unfortunately it was not possible to avoid this
