### ISSUE TITLE
Builder getting stuck on edge of structure

### ISSUE THREAD

**Issue by kmarple1** [ldtteam/minecolonies#3207]
### Minecolonies version

Version: 0.10.95-ALPHA

### Expected behavior

- The builder should not get stuck when crossing into the area reserved by a structure, if nothing is there to get stuck on.

### Actual behaviour

- The builder gets stuck at the boundary of the structure, seemingly in empty space. Photo attached. It seems like they're getting stuck on the fence that appears when upgrading a building, but removing the fence doesn't help.

![builder stuck](https://user-images.githubusercontent.com/8404056/50551432-c510cc80-0c45-11e9-8be0-9075e866853c.png)

**Comment by Raycoms** [comment]
Will work on this pathfinding bug the next week

**Comment by kmarple1** [comment]
A couple of things I forgot to mention:

- The bug is intermittent. Sometimes she goes past that point just fine.

- Knocking her past the boundary seems to fix the issue temporarily. I.e. she'll build normally but may get stuck again the next time she comes back.

- It never affects her leaving the building, just coming.
