### ISSUE TITLE
University - Research Tree

### ISSUE THREAD

**Issue by Raycoms** [ldtteam/minecolonies#3208]
Something to individualize the colony development would be a University.
Fairly easy to build early on but gets more complex while you level it up (resource intensive).

There would be several research branches to follow which give your colony certain features.

- More health
- Bigger inventories
- More damage
- More resistance
- Higher speed

The building would employ 1 prof per level, their combined intelligence factor + level would result in higher speed of research

**Comment by someaddons** [comment]
Could unlock buildings or building level upgrades aswell

**Comment by Nightenom** [comment]
Linking #77 for ideas

**Comment by hron84** [comment]
Can we assign different names for different levels? E.g. Elementary school > Secondary school > High school > University
