### ISSUE TITLE
[Improvement] Bakery should make cooked food

### ISSUE THREAD

**Issue by hron84** [ldtteam/minecolonies#3209]
### Expected behavior

As bakery is basically for food creating (from wheat), it could be able to provide cooked meal for villagers, like 

 - Cooked potato
 - Cooked meat (any)
 - Cooked carrot (if available)
 - Cooked egg (if available)
 - Cooked apple (if available)

Basically, it should check food items if they are smeltable on a basic furnace, and only list them if they have valid furnace recipes.

Probably it should be teached for crafted food recipes like Pam's ones or BWM cooked meat + bread that provides more saturation.

**Comment by marchermans** [comment]
See the restaurant.

**Comment by hron84** [comment]
I did not guessed he's the solution
