### ISSUE TITLE
Eating crash

### ISSUE THREAD

**Issue by KacpixXx** [ldtteam/minecolonies#3210]
### Minecolonies version

Version: Newest

### Expected behavior

- 

### Actual behaviour

- 

### Steps to reproduce the problem

1. Delete the citizens eating animation
2. 
3. 
4. ... Profit

**Comment by marchermans** [comment]
Please fill in the correct issue formula. Their are no logs here. No additional reproducibility information nothing.

If you want support for your problem. Do not behave like a 10 year old. And put some effort into it, that way we put at least that same amount of effort into the problem.

Your amount of effort: 0
My amount of effort: 0
