### ISSUE TITLE
Builder stuck in a loop trying to build supply huts

### ISSUE THREAD

**Issue by MasterQuentus** [ldtteam/minecolonies#3212]
trying to upgrade or build something and all the builder wants to do is build supply huts in different area 
 Minecolonies version

Version: 0.10.105-alpha

### Expected behavior

upgraging the proper building/building the proper builoding
### Actual behaviour

builder keeps trying to build supply huts

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit

**Comment by Raycoms** [comment]
How can we reproduce this?

Am Di., 1. Jan. 2019 um 21:08 Uhr schrieb MasterQuentus <
notifications@github.com>:

**Comment by Raycoms** [comment]
Should not happen anymore
