### ISSUE TITLE
Crash when waking up from bed

### ISSUE THREAD

**Issue by Thetawaves666** [ldtteam/minecolonies#3216]
### Minecolonies version

Version: minecolonies-1.12.2-0.10.109-RELEASE-universal.jar (but could be from a older one too)

### Expected behavior

- Do not crash when i wake up?

### Actual behaviour

- It crashes on wake up (from bed).

### Steps to reproduce the problem

Does not have it, really. But i annex a log. There is also other mods i use, but i don't see them on the log. So i suppose those aren't relevant.

[crash-2019-01-02_13.04.22-server.txt](https://github.com/ldtteam/minecolonies/files/2721216/crash-2019-01-02_13.04.22-server.txt)

**Comment by PoroUsedSnax** [comment]
I see you are using forge version 14.23.2.2611, which is outdated and very likely your issue. Please update to at least the latest recommended.

**Comment by Thetawaves666** [comment]
It got fixed. Thanks.
