### ISSUE TITLE
Where are the Shingle, shingle_slab and timber texture folders?

### ISSUE THREAD

**Issue by TheOrionsun** [ldtteam/minecolonies#3218]
### Expected behavior
Unable to find textures for; Shingle, shingle_slab and timber...These folders are missing now?

### Actual behaviour
My resource pack cannot updated shingle textures and timber blocks now that they are missing? 

### Steps to reproduce the problem
Did you remove or move the textures for these items? The items are in the game, but I cannot find them to change those textures...

Thank you,

TheOrionSun

**Comment by Raycoms** [comment]
We moved them to structurize, that's where you'll find them.

Am Do., 3. Jan. 2019 um 00:14 Uhr schrieb orionsun <notifications@github.com

**Comment by TheOrionsun** [comment]
Is this where you are going to keep them now?

**Comment by TheOrionsun** [comment]
There is no mod named structurize, however it is in a folder in the mods folder under; mods\memory_repo\com\structurize\structurize\1.12.2-0.10.25-ALPHA

**Comment by Raycoms** [comment]
Exactly, it gets delivered with minecolonies within the minecolonies jar
where they will be kept from now on. It's kinda like a library mod fo
rminecolonies.

Am Do., 3. Jan. 2019 um 00:30 Uhr schrieb orionsun <notifications@github.com

**Comment by TheOrionsun** [comment]
Ok, so if I create a resource pack for structurize it should change these textures? 

Will this ever be a mod that will show as a mod and not the folders in the mod folder?

Just different from other mods where if one mod needs another mod it loads a mod and one can see it in the mods folder as a mod.

I'm sure you have a reason to have done this, but why not keep it in the main Minecolonies mod?

Thank you for your time,

**Comment by Raycoms** [comment]
Yes, structurize is available as a separate mod as well, we just integrate
it currently in the mod jar. With 1.13 it will be a dependendy to download
minecolonies.

Am Do., 3. Jan. 2019 um 00:48 Uhr schrieb orionsun <notifications@github.com

**Comment by TheOrionsun** [comment]
Ok, Thank you
