### ISSUE TITLE
Builder doesnt know/forgets how to build

### ISSUE THREAD

**Issue by SwordlessLink** [ldtteam/minecolonies#3219]
### Minecolonies version

Version: minecolonies-1.12.2-0.10.68-RELEASE-universal

### Expected behavior

Builder to continue and finish the building. 
- 

### Actual behavior

The builder will cease to follow any orders and commands and will act on her own accord. This means she will wander the location or standing infront of the builders Chest and await a command. 
- 

Here is a list of screenshots to show errors made -----> https://imgur.com/a/1KqCqqR
EDIT: Turned on the Debug menu and took a screenshot of the Logs made in the minecraft Launcher! It can be found attached to the Imgur Link! The log is full of the same repeated code, so you arent missing anything out. 

### Steps to reproduce the problem

1. Assign a Citizen to a builders hut (automatically done via town hall automation) 
2.  Enable an active build. (e.g Clicking warehouse and press "build Building")
3. Builder will announce she is working on "warehouse1" and then build until the end of the day
4. Go to sleep using bed!
5. Builder will completely forget to build and will act like a standard NPC. You can still interact and talk to her but her actions will be null. Secondary error is that they will stand infront of the builders "chest" and await an instruction even though a building is incomplete. 

Personal note: I will not delete the map, I will keep it incase you need it or if you want more information. I hope i provided everything you need to look into this! Hopefully this is all the info you need. Ill check back in a few days

**Comment by Raycoms** [comment]
can you send me the map?

**Comment by SwordlessLink** [comment]
> can you send me the map?

Sure thing, Im not sure which one u wanted so ill provide both! https://imgur.com/a/AvjzhIm

**Comment by Raycoms** [comment]
Sorry, I meant the complete save file =D

Am Do., 3. Jan. 2019 um 14:21 Uhr schrieb SwordlessLink <
notifications@github.com>:

**Comment by SwordlessLink** [comment]
[World!.zip](https://github.com/ldtteam/minecolonies/files/2724537/World.zip)
Im not sure why but the moment you commented, she automatically went back to working! A boatload of commands went through the logs within a second 
The Logs: https://pastebin.com/pmM4BN5A
The picture of her going to do it: https://imgur.com/BWtrGrc

Unfortunately no steps can be reproduced since there was none. No interaction or anything was given. (shes going for the delivery hut now becuase i cencelled the warehouse minutes before she sprang into action) 

The attachment is the world! Hopefully this is what u wanted!

**Comment by Raycoms** [comment]
Were the citizens mourning the death of a citzen?

Am Do., 3. Jan. 2019 um 14:33 Uhr schrieb SwordlessLink <
notifications@github.com>:

**Comment by Raycoms** [comment]
or was it raining?

Am Do., 3. Jan. 2019 um 15:28 Uhr schrieb Ray Neiheiser <
ray.neiheiser@gmail.com>:

**Comment by SwordlessLink** [comment]
they didnt mourn the citizen, i know this becuase when i went to check the events in the town hall, no event was set. At some point it was also raining but after the rain had stopped, she still did nothing.

Shes gone back to not doing anything now. A repeated cycle

**Comment by ErdbeerbaerLP** [comment]
I have an semilar problem. For me it works to use an knockback stick (`/give @p stick 1 0 {ench:[{id:19,lvl:1000}]}`) to get him away from the current position and then he continues building. The bug randomly appeared in my colony.

**Comment by Raycoms** [comment]
Still happening in the latest alphas?

Am Sa., 5. Jan. 2019 um 12:46 Uhr schrieb ErdbeerbaerLP <
notifications@github.com>:

**Comment by ErdbeerbaerLP** [comment]
I currently can not upload anythig to the server, because i don´t have FTP access right now, i will try as soon as i have it back

**Comment by SwordlessLink** [comment]
The problem has stopped, mainly becuase there are two builders now. Im not sure how it works but its working so i like it! 
P.S I havnt tried any other alpha, have they been updated?

**Comment by Raycoms** [comment]
They update almost daily

Am Sa., 5. Jan. 2019 um 15:32 Uhr schrieb SwordlessLink <
notifications@github.com>:
