### ISSUE TITLE
Multi-Block only pulls blocks from beneath it

### ISSUE THREAD

**Issue by CSvenby** [ldtteam/minecolonies#3222]
### Minecolonies version

Version:  0.10.109-RELEASE

### Expected behavior

You should be able to pull blocks from any direction of the multiblock as is shown in the feature video made by Ray.
- 
Blocks should be able to be pulled from either of the 4 cardinal directions or up or down.
### Actual behaviour

The multiblock item only pulls from beneath it. Not any other direction.
- 

Ray's tutorial for building testing example: [Here](https://www.youtube.com/watch?v=-DKFwjbzwZs)
### Steps to reproduce the problem

1. Create 3x3 example as @Raycoms made in his video
2. Activate bottom lever first, works as intended.
3. Reset bottom lever, activate lever on side.
4. Seems to only pull the block beneath the multiblock on the bottom of the right set.

I believe this to be a bug. If it is not a thorough walkthrough of how to use the Multiblock item would be greatly appreciated.

Thanks for all you do!

**Comment by Raycoms** [comment]
Hi, this has nothing to do with where the lever is attached, you have to
change this in the GUI. So you gotta set the arrows there (NSWE)

Am Do., 3. Jan. 2019 um 21:19 Uhr schrieb CSvenby <notifications@github.com

**Comment by CSvenby** [comment]
Hi @Raycoms , 

I guess I maybe didn't explain well enough. I understand the UI. The arrows specify what direction the blocks should go once passed through the multiblock and the plus and minus specify up or down. My issue is that I am trying to create a sideways like gate. The multiblock will not pull the items from the side. Only the blocks beneath it. Those blocks are then outputted to the correct direction specified by the arrow.

Thanks again!

**Comment by Raycoms** [comment]
I tested this in my world with the newest block ingame and it worked perfectly fine =/
Do you have this block from minecolonies or the extra mod?

**Comment by CSvenby** [comment]
The block is from Minecolonies. I am trying to use it in creative if that makes a difference. I suppose I could be using it wrong, but everything that I do has the same effect. The GUI arrow work as intended I believe. If I click the south arrow the blocks will be outputted on that side of the block. The only issue is that the Multiblock only pulls blocks from beneath it to be outputted.

**Comment by Raycoms** [comment]
I know it's getting big, but could you make a video of this:
1) You place the block, right click it, change the settings
2) You execute it
3) you right click and show the settings

Am Mo., 7. Jan. 2019 um 14:03 Uhr schrieb CSvenby <notifications@github.com

**Comment by CSvenby** [comment]
Here ya go:

![multiblock test 1](https://user-images.githubusercontent.com/46360081/50785716-230d6780-1277-11e9-9912-98844308d067.gif)

**Comment by Raycoms** [comment]
The arrow is for north, west, east, south and not for right left in the
front and back. You showed the sun in the east, so it went from down to the
east.

Am Mo., 7. Jan. 2019 um 16:24 Uhr schrieb CSvenby <notifications@github.com

**Comment by CSvenby** [comment]
So yes. I get that.
In GUI:
Up = North
Left = West
Right = East
Down = South
Plus = Up
Minus = Down.

The arrow specifies output direction, correct?

What I wanted to happen was the polished granite block to be put where the grass block was put.

Is there a way to do that? Or am I mistaken? 

Thanks for your time

**Comment by Raycoms** [comment]
Yeah, but in the world, from the perspective of the video, what were the
directions.

Am Mo., 7. Jan. 2019 um 16:52 Uhr schrieb CSvenby <notifications@github.com

**Comment by CSvenby** [comment]
In the video, my character is facing north. The sun is rising in the east on my right.

**Comment by Raycoms** [comment]
Then, its doing it right, it is putting it to the left into the direction
east, isn't it?

Am Mo., 7. Jan. 2019 um 17:14 Uhr schrieb CSvenby <notifications@github.com

**Comment by CSvenby** [comment]
A block(the grass block) is being outputted to the east. The direction I specified in the GUI. In your video on YouTube, introducing the mod feature, you created a sideways moving gate made of wooden planks and fences. I am trying to accomplish the same thing. 
In my video when the lever is activated the grass block that is beneath the multiblock is the block that moves. I am wanting the granite block I placed to move instead.

**Comment by Raycoms** [comment]
There are two clicks involved, left click to say where it should go, and
right click where it should come from. So left click on the east and right
click on the west.
Atm down is still selected (Red)

Am Mo., 7. Jan. 2019 um 17:21 Uhr schrieb CSvenby <notifications@github.com

**Comment by CSvenby** [comment]
That clears it all up. I would suggest adding information about the block to your guys' wiki. Thank you so much. I am sorry that I was confusing in my explanation. Thank you so much for the help and thanks for making this mod. It is by far one of my favorites.

P.S. Maybe next time I'll actually have a bug to report, not just me being silly. Thanks again!

**Comment by Raycoms** [comment]
Np, @Wissi can we add this to the wiki?
