### ISSUE TITLE
Manual delivery priority lost after server restart

### ISSUE THREAD

**Issue by GanthorPrime** [ldtteam/minecolonies#3228]
### Minecolonies version

Version: minecolonies-1.12.2-0.10.112-ALPHA-universal

### Expected behavior

Delivery prioriry configuration persist between server restarts

### Actual behaviour

If you set the delivery priority to 'Manual' and set a value like '1', after a server restart the value is still in 1, but the config is in 'automatic', thus in some point the value returns to '10'

### Steps to reproduce the problem

1. Configure de restaurant delivery priority to manual and set value to 1
2. Put tons of food in the restaurant and verify the delivery man is not moving it all to the wh in the short time
3. Stop - start the server
4. Check de delivery priority again.. is in 'automatic'
5. Shortly after that, delivery man grab all food to the warehouse
6. Restaurant filled with workers claiming for food

**Comment by Talyda** [comment]
Just poking my nose in and adding that this is still happening in version .159 (version currently up on the official server)

**Comment by Raycoms** [comment]
fixed
