### ISSUE TITLE
waila crash 

### ISSUE THREAD

**Issue by oItsSerenityo** [ldtteam/minecolonies#3229]
### Minecolonies Official  

Version: v4.7

### Expected behavior waila crashes , says since vanialla fix is installed it should still work, even after a sever restart is done it still is crashing. 

wailia, or at least the pack to continue to play with or without the tool tips 
- 

### Actual behaviour

all i have on hand is this past bin right now from the crashes.i hope this can help some. as i know this pack is in alpha right now. 
https://paste.dimdev.org/natovabisu.mccrash

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit

**Comment by Raycoms** [comment]
Please report this to waila directly
