### ISSUE TITLE
Fisherman gets confused when built over water

### ISSUE THREAD

**Issue by SyberSmoke** [ldtteam/minecolonies#323]
### Minecolonies version

version 0.6.1908

### Expected behavior

- The fisherman, when active, will look for a solid block to stand on that over looks enough water to fish in.

### Actual behaviour

- When built over water, the fisherman will try to catch fish through the blocks he/she is standing on.  The fisherman may also jitter as it tries to path through the blocks to get to the water.

### Steps to reproduce the problem

1. Build a platform large enough for the fishery over water, the ocean works.  must be two blocks off the surface of the water.
2. Allow the fisherman to be hired.
3. Fisherman will try to fish through the platform he is on.  Or he will say there is no water.

**Comment by kedamono** [comment]
In this situation, I typically put in a floor of oak planks for him to stand on.

**Comment by Raycoms** [comment]
TODO: Give the player the possibility to manually assign the fishing spot.

**Comment by Wissi** [comment]
@Raycoms as per your last comment:

> TODO: Give the player the possibility to manually assign the fishing spot.

Do we still leave this open?
I'll close and you decide to re-open and comment please.
