### ISSUE TITLE
Server not backing up all colonies

### ISSUE THREAD

**Issue by GanthorPrime** [ldtteam/minecolonies#3230]
### Minecolonies version

Version: minecolonies-1.12.2-0.10.109-RELEASE-universal. It seems that the issue is not related with this specific version and comes from far before, maybe minecolonies-1.12.2-0.10.1-RELEASE-universal.jar

### Expected behavior

Each colonies backup files stored in ServerDir/WorldName/Minecolonies contains 1 file por colony with the format colony{n}_0.dat plus the file colonies.dat

### Actual behaviour

In a server with 4 active colonies, the backup files only contains the colonies.dat file and the first colonie colony1_0.dat file. I can confirm that it was backing well before, but sadly i dont know exactly wen started to backup only one colony.

I check some manual backups we made at the begining of december 2018 and the issue is there, but going backwards to a very old backup from 2 months it has all the colonies files as espected but noticed the colonie files does not contains the '_0' ending. Maybe the problem comes with the migration done in minecolonies-1.12.2-0.10.1: "...Extracts backup related things to backup helper chunk data related things to chunk helper colony list related things for storage to capability"

[https://minecraft.curseforge.com/projects/minecolonies/files/2627056](url)

This also seems to be related: i check the contents of colonies.dat file using NbtExplorer and in the 'amountOfColonies' entry, the value is '1' (in the old backups files, is 4).  I backed up all and tried to change that to 4.  I started the server, all seems to be normal, but if i made a backup using /mc colonies backup the backup result is the same. After that, i check the non-zipped files in the backup folder and it seems that at  some point the file is modified and 'amountOfColonies' returns to 1.  

Also noticed the old colonies.dat file does not contains this entry: 'colonycap'.  this is in the new colonies.dat and is valued '1'. cant think on that entry meaning, i dont know any config to limit amount of colonies in the server. Anyway, tried to change that to 4 and like before, no results.  In general, i seems all edits i made in the non zipped colonies files have no effect on server. ¿Maybe they are not the actual store from where the server is loading the colony data?.  ¿How can we actualy effectively edit colony data so changes are taked on server start? (before we can edit this files and changes reflect inmediatly on server start)

### Steps to reproduce the problem

You need to have more than one colonie running in a stand alone server.
Not sure how to reproduce, maybe related to colonie file migration done in minecolonies-1.12.2-0.10.1. This issue has little evidence in gameplay, except for generating and loading backups. maybe some other strange issues we are having (i.e farmers from colony 3 assigning fields from colony 1)

**Comment by Raycoms** [comment]
Will look into it now.

**Comment by Raycoms** [comment]
Fixed

**Comment by GanthorPrime** [comment]
Thanks, will check. 

I see some info on the forge capabilities system. i understand minecolonies now is saving / loading colony info from the world data. maybe that explains wy edits on manager files does not load anymore unless i use /mc loadbackup.

**Comment by Raycoms** [comment]
exactly.
