### ISSUE TITLE
Builder Issue 

### ISSUE THREAD

**Issue by Airisii** [ldtteam/minecolonies#3234]
### Minecolonies version

Version: 1.12.2-0.10.116-ALPHA-univerisal 

### Expected behavior

Builder working 
### Actual behaviour

The builder says "Can't mine block Apatite Ore BlockPos{x=424, y=75, z=195}. Need to upgrade the building to use a tool higher mining level." but I've dug at the coordinates but there is no apatite ore and he won't build. I've given him an upgrade pickaxe but still not moving.

### Steps to reproduce the problem

1. Fix the builder issue
2. Instead of a stone pickaxe as the default tool for level 1, it should be Iron so that problem like this don't happen 
3. Once that is fix the builder should build

**Comment by Raycoms** [comment]
Yeah, I heard that he sometimes seems to report the wrong location of the
block. What mod is this ore from? Can you send me the world?

Am So., 6. Jan. 2019 um 13:57 Uhr schrieb LegendaryCrystalFox <
notifications@github.com>:

**Comment by Airisii** [comment]
I believe the ore is from forestry. 
And the system won't allow me to give you the world. 
Also, my builder started working again I'm not sure why or what was the main issue but I believe the issue is fixed?

**Comment by Airisii** [comment]
Now the builder is taking forever to build.
