### ISSUE TITLE
Cant disable sapling in new filtered lumberjack selection page

### ISSUE THREAD

**Issue by GanthorPrime** [ldtteam/minecolonies#3235]
### Minecolonies version

Version: minecolonies-1.12.2-0.10.116-ALPHA-universal

### Expected behavior

sapling selection page behave like other huts new filetered selection page to enable / disable the chopping of especific saplings in the lumberjack

### Actual behaviour

buttons in the new filtered sapling selection page does nothing, they start all 'on' and you cant disable any sappling.   the replant button in the same page seems to be good

### Steps to reproduce the problem

1. build lumberjack
2. try to deselect some saplings

**Comment by Raycoms** [comment]
hotfixed as well, thanks for reporting it
