### ISSUE TITLE
Builder is to slow

### ISSUE THREAD

**Issue by Airisii** [ldtteam/minecolonies#3237]
### Minecolonies version

Version: 1.12.2-0.10.116-ALPHA-univerisal

### Expected behavior
Builder to build faster

### Actual behaviour
Builder takes hours to build even its own hut. I don't want to wait 2 hours just for a build I want to build my colony faster so i can have fun instead of waiting.

### Steps to reproduce the problem

1. Make the builder faster
2. So that it doesnt take hours just for his own hut or any other building

**Comment by marchermans** [comment]
You can up this in the configuration file.

**Comment by Raycoms** [comment]
Also, he is slow initially and then gets faster when he levels up. There is
a progression in this mod, on purpose.

Am So., 6. Jan. 2019 um 17:35 Uhr schrieb Marc Hermans <
notifications@github.com>:

**Comment by Airisii** [comment]
I edited the config but he's still slow? So when i fill his request for a block he takes forever
