### ISSUE TITLE
Builder 

### ISSUE THREAD

**Issue by Crieslie** [ldtteam/minecolonies#3239]
### Minecolonies version

Version: 1.12.2-0.10.118-ALPHA-universal 

### Expected behavior
Builder working right after being given the items

### Actual behaviour
I've edited the config to make building faster but  I give him the items he needs when upon request and he takes 10 minutes just to build a small portion until  the next request

### Steps to reproduce the problem

1. Fix the error when fulfilling the item request that the builder asks for
2. So that he build faster

**Comment by Crieslie** [comment]
Even after editing the config the builder is just as slow as before

**Comment by Raycoms** [comment]
The rest is then just patience. If you want instance building then turn it on in the config.
