### ISSUE TITLE
Requests not showing on NPC

### ISSUE THREAD

**Issue by jollejonas** [ldtteam/minecolonies#3243]
### Minecolonies version

Version: 
minecolonies-1.12.2-0.10.119-ALPHA-universal
### Expected behavior
Requests shows up when you look under the NPCs requests, but no requests shows up. This makes workers stand still without letting you know why. Requests still pops up in chat, but not all of them and some of them will be visible on the clipboard.

### Actual behaviour
When you look at the NPC open requests list no requests are visible.

### Steps to reproduce the problem
1.  Start the worker
2.  Wait until they are missing some materials/tools
3. No request will show and worker stops working.

### Extra info
Went back to version minecolonies-1.12.2-0.10.118-ALPHA-universal, and the requests seems to be back.

**Comment by Raycoms** [comment]
I'll take a look at it in a bit. We change some things around this which
might've broken it

Am Mo., 7. Jan. 2019 um 11:35 Uhr schrieb jollejonas <
notifications@github.com>:

**Comment by Raycoms** [comment]
Fixed
