### ISSUE TITLE
suggestion ai path markers

### ISSUE THREAD

**Issue by shivachirr** [ldtteam/minecolonies#3244]
so what im thinking is make path markers that the ai would prefer to get to destination. i feel this would help with ai load along with allow a bit more control what path the colonist use to get to a point. and stop them from cutting through buildings and hopping on stuff. so im thinking something like a torch or flag that marks a ai path point and maybe some kinda of way to link 2 points together. 

main reason im suggesting this i hate the fact the my colonist walk through every building and strange place to just to get to a point. or even do a very weird path to get to something when its quicker just to walk to it.

**Comment by Raycoms** [comment]
Good idea, we called them "Waypoints" and your builder builds them for free and register them with the colony. In the decoration/infrastructure folder =) when you have infrastructure selected it will render them in the world.

**Comment by shivachirr** [comment]
really did not know that was a thing

**Comment by Raycoms** [comment]
=D

Am Mo., 7. Jan. 2019 um 18:21 Uhr schrieb shivachirr <
notifications@github.com>:

**Comment by shivachirr** [comment]
suggest putting some info on the wiki when you guys get a chance about this

**Comment by Raycoms** [comment]
@Wissi where did the page for this go? I can't find it anymore

**Comment by shivachirr** [comment]
also one more question is there a tool to see the way points beuacse the only way i can see them is if i have to be using the builder tool and place once down but not confirm building it

**Comment by Raycoms** [comment]
That's the only way to see all of them now.

Am Mo., 7. Jan. 2019 um 18:37 Uhr schrieb shivachirr <
notifications@github.com>:
