### ISSUE TITLE
Dupe/Item Deletion with Tinkers Construct

### ISSUE THREAD

**Issue by Morat2255** [ldtteam/minecolonies#3245]
### Minecolonies version

Version:  minecolonies-1.12.2-0.10.109-RELEASE

### Expected behavior

Clicking "fulfill request" when a colonist requests a tool should remove an appropriate tool from my inventory, and that tool should appear in the colonist's inventory. Colonists should not accept tools that they can't use.
- 

### Actual behaviour

Clicking "fulfill request" on a builder while holding two different picks removed an inappropriate (too high level) pick from my inventory, and the appropriate pick appeared in the colonist's inventory (a duplicate of the pick remaining in my inventory)
- 
More specifically, I was holding my personal pick, named "Top Pick" in my first toolbar slot. I had another pick, named "Builder's Pick" in the middle of my inventory. Both were tinkers picks. The Builder was requesting a wood tier pick (according to the wiki, a tinker pick with mining level stone should be appropriate). When I clicked "fulfill request", Top Pick disappeared from my inventory, while Builder's Pick remained in my inventory. When I checked the builder's inventory, he also had Builder's Pick in his inventory, a duplicate to the pick remaining in my inventory. Top Pick appeared to have been deleted.

After restoring the world from a backup to save my pick, moving the items directly into the builder's inventory appeared to work normally without the bug.

### Steps to reproduce the problem

1. Found colony, set up builder's hut
2. Have a Tinkers pick (or presumably shovel) with high mining level in first toolbar slot
3. Have a Tinkers pick or shovel with mining level stone in any other inventory slot
4. Attempt to give a tool to the builder by talking to him and viewing his "requests".

**Comment by Raycoms** [comment]
Does this happen on the latest algha as well?

**Comment by Michael-Phoenix** [comment]
Yes, happened to me a few days ago
