### ISSUE TITLE
Shape Tool Fill issue while under water

### ISSUE THREAD

**Issue by Spaladino95** [ldtteam/minecolonies#3247]
### Minecolonies version

Version:  1.12.2-0.10.127-ALPHA       

Structurize Version: structurize-1.12.2-0.10.31-ALPHA    

### Expected behavior

-  A shape with the interior filled with Air should be filled with air.

### Actual behaviour

-  When a shape is created inside of water the "Air" tile is placed and instantly filled by the surrounding water.  This is only happening because the shape is built from the bottom up, if it were to be built from the top down then their would never be any water above the air to fill it.

### Steps to reproduce the problem

1.  Create a half sphere or sphere with any solid outer and air.tile interior while below the water level.
2.   Create a shape that is larger in size, mine was 150 wide.
3. it places a group of blocks layer by layer, and has to process the water fill dynamic in between every placement of 'air' during the shape build.  When its all done its still filled with water.
4. ... Profit

**Comment by Raycoms** [comment]
Doesn't happen anymore
