### ISSUE TITLE
Building will not retain ground blocks

### ISSUE THREAD

**Issue by pdvrieze** [ldtteam/minecolonies#3248]
### Minecolonies version
Version: 1.12.2-0.10.109-RELEASE. On upgrade from 1.12.2-0.10.68-RELEASE (and before that 1.12.2-0.10.53-BETA)

### Expected behavior
The existing ground blocks to be retained when building a new building

### Actual behaviour
The ground blocks are removed and not replaced by dirt either. On repair/upgrade the same happens and ground blocks are deleted.

### Steps to reproduce the problem

Have a world created initially in 0.10.53. Initialise the colony.

Update it (either directly or after loading it with 0.10.68) to 0.10.109. Attempt to build any building. It will clear the bottom layer (where the solid placeholder blocks are) rather than retaining existing blocks.

Downgrading back to the older mod version solves the problem.

**Comment by Raycoms** [comment]
Can you test if this also happens in the newest alpha versions?

Am Mi., 9. Jan. 2019 um 18:08 Uhr schrieb Paul de Vrieze <
notifications@github.com>:

**Comment by critchards** [comment]
I can confirm its still happening all the way up to 1.12.2-0.10.141-BETA. Also affects miner, they used to dig a 5x5 shaft, now its 7x7 with a column of cobble and ladder. Im guess this is related, something to do with the placeholder block not working?

**Comment by Raycoms** [comment]
We had a talk with a player these days, it seems like on the way the ids of
your world got messed up which is causing this.

Am So., 20. Jan. 2019 um 21:28 Uhr schrieb dilznick5 <
notifications@github.com>:

**Comment by critchards** [comment]
So what does that mean? Can I fix it or do I just live with it?

**Comment by Raycoms** [comment]
There are ID fixer mods or tools which would allow to do that yes.

Am So., 20. Jan. 2019 um 21:44 Uhr schrieb dilznick5 <
notifications@github.com>:

**Comment by pdvrieze** [comment]
Any suggestions as to the kinds of mods that could work with this. Would jeid work?

**Comment by Raycoms** [comment]
Any id mod should be able to solve it.

Am Mo., 21. Jan. 2019 um 18:47 Uhr schrieb Paul de Vrieze <
notifications@github.com>:
