### ISSUE TITLE
crash on world after accidentally updating to skycolonies and then reverting back to minecolonies

### ISSUE THREAD

**Issue by SDUBZ** [ldtteam/minecolonies#325]
### Minecolonies version

minecolonies-universal-1.10.2-0.4.1870

### Expected behavior

-to load my world

### Actual behaviour

errors out and crashes me back to desktop

forge: 1.10.2-2185

crash report
[crash-2016-12-07_16.42.33-server.txt](https://github.com/Minecolonies/minecolonies/files/635757/crash-2016-12-07_16.42.33-server.txt)

accidentally updated to latest mineclonies which turned out to be skycolonies and after reverting back cant load back into my test world that i use to publish my skyblock through and then i get that crash every single time.

**Comment by marvin-bitterlich** [comment]
@Raycoms that is really weird :O
Any ideas?

**Comment by marvin-bitterlich** [comment]
@SDUBZ if you use a skyblock map I suggest you go with SkyColonies as the buildings there are better for skyblock. 

A fix for this will be out once I know what happened.

**Comment by SDUBZ** [comment]
[fml-client-latest (2).txt](https://github.com/Minecolonies/minecolonies/files/635870/fml-client-latest.2.txt)
i could give you a fresh log if it would help

**Comment by SDUBZ** [comment]
well what happend was i built the supply chest and then created the builder and went back to my base to get things and then it crashed
