### ISSUE TITLE
Tried to read NBT tag that was too big

### ISSUE THREAD

**Issue by phit** [ldtteam/minecolonies#3250]
### Minecolonies version
Version: minecolonies-1.12.2-0.10.80-ALPHA-universal.jar
I would love to update but we are using a premade pack https://minecraft.curseforge.com/projects/life-in-the-village

### Expected behavior
not crash, crash report https://gist.github.com/phit/8389875129ba05d8aba82326838f3747

### Actual behaviour
crash, started randomly happening to one of our players on the server

### Steps to reproduce the problem
sorry, no idea
here is their colony.dat file https://phit.link/s/colony7_0.dat
running `/mc rs reset colony: 7` did not fix the issue

**Comment by Raycoms** [comment]
Hi, two things:
- Can you please insist at the Live in a village pack to update things.
(If enough people insist they might just update it)
- Try an /mc colonies rsresetall

**Comment by phit** [comment]
> Try an /mc colonies rsresetall

that seems to have worked, any idea how to track down what caused it, what exactly is synced to the client? do all clients get all colonies request data?

**Comment by marchermans** [comment]
A colony keeping old request data around. It happens sometimes. Just not colony 7
