### ISSUE TITLE
Can't build new buildings

### ISSUE THREAD

**Issue by Cosmology2727** [ldtteam/minecolonies#3251]
Version: minecolonies-1.12.2-0.10.109-RELEASE-universal

### Expected behavior
I would expect to be able to build a farm on my land.

### Actual behaviour
When I use the building tool to build a farm, it says I'm too far from the town hall. Meanwhile, I'm directly beside the town hall. I've also tried just placing the farm block, but it still says I'm too far from town hall.
I've tried refreshing my colony, didn't work.
I checked the permissions, and I see my colony being located right where it should be, with me as the owner.
I teleported myself to my colony, and it worked fine (meaning I am the owner, and the town hall is located properly).

I can almost guarantee the problem is that I updated forge and minecolonies (forge to recommended, minecolonies to most recent). Please help me out, this mod looks really cool for us on my server, but we REALLY don't want to have to start all over. My buddy has a big colony, and he'll probably just quite if the whole thing has to be reset.

How to reproduce
1. Create a world with minecolonies-universal-1.12.2-0.8.7508
2. Start a colony, have a town hall, a builders hut, and a mine.
3. Update to minecolonies-1.12.2-0.10.109-RELEASE-universal
4. Try to build a farm literally anywhere, even directly beside town hall.

**Comment by Raycoms** [comment]
There seems to have been gone something wrong with the forge capabilities. Maybe through the update.
Try the /mc colony claim command to claim the area around your townhall.

**Comment by Cosmology2727** [comment]
Sorry, that specific command on your website seems to be written wrong, looks like you wrote the teleport command out. I'm trying to guess what the command might be, but none of my guessing is working. How should I do the claim command to claim all my chunks?
I entered this: /mc colony claim 2 0 8 true
I would think this would do my colony (2) in overworld (0) with a range of 8 chunks.

Currently it's giving me the error:
/mineColonies colony claim <colony: integer> <dimension:integer> [range: integer] [add: boolean]: missing required parameter colony
Not sure why, because I clearly put an integer in place for my colony (which is 2).

Thanks for the help! Really appreciate it!

**Comment by someaddons** [comment]
you gotta give the parameters like this: <colony: integer> becomes:   colony: 2      <- note the space before the 2

**Comment by Cosmology2727** [comment]
Thanks so much! You have saved my server :D

**Comment by someaddons** [comment]
👍  glad you figured it out, guess the wiki can use some more examples

**Comment by Cosmology2727** [comment]
Sorry to be a pain, but I "thought" it was fixed because I could create the outline for it, and it accepted the job. The problem now is, the builder won't actually build it. It removed the item from my inventory (the farm block), but I don't see it in the real world for building. There's a fence outline, but nothing else. The builder's hut has no record of anything being done, and my worker just stands there in the builder's hut.
Any ideas?

**Comment by Raycoms** [comment]
Did you click build in the gui?

**Comment by Cosmology2727** [comment]
I used the building wand thing, picked the one I wanted, and clicked the check mark. Doing this removed the farm block from my inventory, and created that fence outline thing.
The builders hut doesn't have a build button in it's GUI, if that's what you mean.

**Comment by Raycoms** [comment]
right click the farmer gui

Am Do., 10. Jan. 2019 um 22:09 Uhr schrieb Cosmology2727 <
notifications@github.com>:

**Comment by Cosmology2727** [comment]
There is no farmer gui. it took the farmer block, but didn't put it in the world. It only created the fence. I tried it again with a cook, and it did the same thing. Took the block out of my inventory, didn't place it in the world, and just created the fence.

**Comment by Raycoms** [comment]
Did it maybe place it underground?

Am Do., 10. Jan. 2019 um 22:19 Uhr schrieb Cosmology2727 <
notifications@github.com>:

**Comment by Cosmology2727** [comment]
Nah I dug way down, there's nothing there. Very confused.

**Comment by Raycoms** [comment]
That's weird. Can you send us th elog?

Am Do., 10. Jan. 2019 um 22:26 Uhr schrieb Cosmology2727 <
notifications@github.com>:
