### ISSUE TITLE
More then one problem going on

### ISSUE THREAD

**Issue by Howman** [ldtteam/minecolonies#3257]
### Minecolonies version
Version:  minecolonies-1.12.2-0.10.132-ALPHA-universal

### Expected behavior
1. to find full fill button
2. knights should patrol like i have set them to
3. builders should build and not stand around
4. miner should mine  

### Actual behaviour
1. The full fill button is missing on the colonist  but it is found on the farmer
2. some of my knights are requesting materials they already have like there weapon 
3. I have 5 builders but only 2 seam to do anything they stand there and request stuff 
4. miner keeps asking for pickaxe when he has like 5

### Steps to reproduce the problem
I have no steeps to reproduce 
But am on a multi player lan 

not sure but these problems have been resent  I believe after 1.12.2-0.10.12*-ALPHA  something version.

**Comment by Justen-N** [comment]
I know it's tedious, but in order to address each problem, please submit a
separate ticket, unless you believe that all your problems are related.

**Comment by marchermans** [comment]
Also logs and Screenshots are required. We have a strict policy on just not being interested in these issues, since they usually just mean the player interpreted something wrong and it takes hours to figure that out without said logs and Screenshots.

A world upload would also be nice.

**Comment by Howman** [comment]
Sorry, Next time I will open separate issues. I under stand what your saying I remember early versions when the colonists did not morn deaths then it was introduced it took me some time to figure out on my own why the colonist where not working. I will try the game for a bit longer cause some problems seam to work them self out on there own. And I do not have the time at the moment to get screen shots and logs together and I would have to get the world upload from the host computer as i was playing through the multi player lan. I will try to get some stuff together asap Thank you for you reply(s)

**Comment by Raycoms** [comment]
Should be fixed, most or duplicated
