### ISSUE TITLE
[New Worker] Alchemist / Witch / Healer

### ISSUE THREAD

**Issue by nytstarlet** [ldtteam/minecolonies#326]
The Witch/Healer can have many directions.. 

List of possible behaviors. 

harvest and grow potion ingredients. 
brew potions such as healing potions.
brew her own potions, could act parallel to the guard at night hunting and killing monsters with her potions and sacrificial dagger. 

The guard can run an inventory check, checking for X amount of healing potions if under set amount goes to the healer and requests X number of potions.. when he is damaged to 50% he uses the potion. and out of battle if he has run out of the potion it triggers the ai to acquire them again.  

Witches AI can determine how many of each potion should be kept in inventory at all times. maybe a menu so the player can adjust the amounts. 

Another possible addition could be using town currency to have her do rituals... such as making it rain for a price.. would rather that be later end game for the witch... but she could preform many tasks.. 

This is just the start of my brainstorming.

**Comment by Raycoms** [comment]
@pmardle can we have some more input on this?

**Comment by neadlak** [comment]
I'm imagining witches throwing splash healing potions at guards. As a bonus, it would hurt zombies, right? If they had a fairly low rate of fire and unlimited internal supply , but didn't just give players free healing potions, that would be a neat way to beef up your guards. At higher hut levels the witch could throw stronger potions.

Maybe when farmers are in a good state you can copy some of their AI and have witches/herbalists 'farm' nether wort and other components where possible.

I think it's a solid idea, subject to good balancing.

**Comment by pmardle** [comment]
This is effectively the "Alchemist" worker that I had planned.

The Alchemist (Witch) should brew potions (All types) - how we do this is up for debate..

I am a fan of having 1 brewing slot per level (Of hut) and therefore the Alchemist can brew 1-5 different potions depending on level.

The Alchemist hut GUI should therefore have up to 5 slots that the player can place a particular potion.  Each slot should have a slider or similar next to it to set a quantity (1-16 say) and the Alchemist should try and maintain that quantity of potions in their chest, requesting items from the D-Man/Material Handling system as required.

The Alchemists level (worker level) could affect the speed at which they brew potions (10-60 seconds per potion (60-Worker level would work well)

Alchemist would require a supply of glass bottles from the crafter as well as all potion ingredients.

I don't think the Alchemist should enter battle themselves.. we can have a healer worker do that, using healing potions the alchemist makes.

**Comment by pmardle** [comment]
P.S The rituals/rain is the domain of the Druid worker we have planned :)

**Comment by Raycoms** [comment]
I propose separating alchemist and healer:

- Alchemist:
Brews potions, worker can request potions for certain use cases then

- Healer:
Walks around and heals citizen
Heals citizen that fell sick (sickness possibility added to the mod)

**Comment by Asherslab** [comment]
@Raycoms On the sickness part i think we could do alot of interesting things with the probability of getting sick. E.g. unhappiness breeds sickness (and vis-versa), eating raw food, overworking workers (e.g. guards), being wounded be enemies or etc (infections). but also decreasing the probability for things like better food (i dunno, steak or something?) or maybe access to water, etc. 

just thoughts

**Comment by Raycoms** [comment]
Yes, I agree I would have for a first iteration done it this way:

- Low saturation increases chance
- Low happiness increases chance
- Low health increases chance
- Each job has an "sickness modifier" that can change depending on the job

(I guess that animal workers are more likely to get sick, and similarly I'd say that an enchanter is less likely to get sick).

Additionally, of course when a worker is sick he will request a "healer building".
Workers don't work when sick (display poison potion effect)

Workers might heal from alone after some time with a certain chance
Workers can be healed by the player by throwing the right potion at them.


In the future:
- We can add that sickness spreads
- We can add that different illnesses require different potions to cure, and the healer requests those from the alchemist.

**Comment by ravenbuilder934** [comment]
Hi, so far we only have the Healer and not the Alchemist. I think this would be a really cool worker to have, so maybe could we add an Alchemist too?
