### ISSUE TITLE
Minecolonies Storybook

### ISSUE THREAD

**Issue by Raycoms** [ldtteam/minecolonies#3260]
Instead of having a guidebook it might be nice to have a storybook which takes you through the process of creating a colony in form of a story.

```
like you place a supplyship
and you get a book
which tells a story about a major
which went somewhere
to found his colony
```

**Comment by spacewolfcub** [comment]
Oooh, hm... I like it.
Steal wholesale all the LexicaBotania GUI ideas?

**Comment by Wissi** [comment]
But since there is NO specific process, create links to pages within the book?
F.e. after you place builder, state several options as "next" worker? 
List several workers player can click on to view the info? 
This because it depends on player preference and biome world type, etc as to which is the next worker to place?

**Comment by lunadragnstar** [comment]
Couldn't we do something like the quest book as the story book?

**Comment by Nightenom** [comment]
Pinging myself to finish our guidebook, _can someone do the builder from wiki..._

**Comment by lunadragnstar** [comment]
After I help wissi with the wiki, I was going to look at the book.

**Comment by bookerthegeek** [comment]
I would look into the patchui mod for a book. I think I spelled the right. It is the same one that pneumatic craft is now using (nit the igw mod) and I heard a rumor that another major mod (Buildcraft) might be moving it to it also.

**Comment by marchermans** [comment]
This is something we can look into.
We have our own gui library and book library in the works, and the goal is to pull the information from the wiki to display in the game using this library.

That said the library is not out yet.

**Comment by Raycoms** [comment]
Closed in favor of joint issue.
