### ISSUE TITLE
Pam's HarvestCraft vs Herders: eating the animal's hay

### ISSUE THREAD

**Issue by spacewolfcub** [ldtteam/minecolonies#3262]
### Minecolonies version
minecolonies-1.12.2-0.10.134-ALPHA-universal
as part of the Official Minecolonies Modpack.

### Expected behavior
NPCs will not eat wheat raw, because normally players cannot eat wheat raw.

### Actual behaviour
Pam's HarvestCraft changes wheat to be edible raw, because the grains produced by HarvestCraft are generally all edible raw. This cannot just be disabled in config because the config that controls that change ALSO scales down vanilla foods to match HarvestCraft food/saturation values.

The config option most likely guilty for it is: 
`# Makes changes to vanilla food item and drop hunger restore and saturation values to be balanced with HarvestCraft food. [default: true]
B:enablevanillafoodBalance=true`

### Steps to reproduce the problem
1) Install both Minecolonies and HarvestCraft.
2) Leave HarvestCraft on default config.
3) Build Rancher or Shepherd and give them wheat for breeding. 
4) NPCs carrying wheat will consider themselves to be carrying food already, so they won't get more food and will instead eat animal fodder. It's probably also a problem with carrots. 

### Nosy recommendations 
1) Make internal definitions of RancherFeed, ShepherdFeed, SwineherdFeed, WarrenerFeed
Because: if this list can be set from config, 
or, if this list can be set depending on other mods detected like Animania, 
then, it makes it much more adaptable for future needs.
I say Feed because it's the best word I could come up with that can still apply to all animals regardless of what the animal is or what the food item is; otherwise it'd end up being silage, fodder, kibble, slop... Too specific and not easy to see at a glance they're all related.

2) Make career-dependent food checks. RancherNPC will not eat anything defined as RancherFeed. 
Because: This way the rest of the colony can still eat carrots if the Swineherd or Warrener (the name for a rabbit farmer) is not allowed to eat it. It also makes it more flexible in future if an animal mod decides pigs only eat cooked potatoes or something.

**Comment by spacewolfcub** [comment]
I still think making animal feed would be a great way to go, 
but since Pam's added a config specifically to disable making wheat edible I guess the central issue is closed. 

All that remains is the suggestion for animal feed.

**Comment by spacewolfcub** [comment]
In related ideas...

If Minecolonies itself introduced a recipe in the furnace for carrots to turn into roasted carrots, then Swineherd NPCs would no longer eat the raw carrots they're supposed to feed the pigs. Combined with the Pam's config for non-edible wheat I think that would solve the practical aspects of NPCs eating the stuff meant to be animal food.

![image](https://user-images.githubusercontent.com/11811417/63828788-73c3f480-c91c-11e9-8f03-008519c44d27.png)

**Comment by Raycoms** [comment]
Closed in favor of joint issue.
