### ISSUE TITLE
Feature Request: Toggle all on/off button for Composter

### ISSUE THREAD

**Issue by spacewolfcub** [ldtteam/minecolonies#3267]
Originally requested by Luna on Discord:
Add a toggle all on/off button for Composter GUI

I'm just posting it here so devs can discuss it or find it in an organized way.

**Comment by Raycoms** [comment]
I think this is not a good idea, for two reasons:
a) Probably no one is going to want all on/off
b) If it is modded there can easily be a few thousand items there, on all on/off that would mean a nice load on the server.

**Comment by spacewolfcub** [comment]
Oh... That makes sense. Specially if players get impatient at not seeing an immediate response in multiplayer and keep toggling it. 

But precisely because there can be a few thousand items there, it's not exactly reasonable to ask a human to toggle all of them by hand. 

Um, what could be a compromise?

**Comment by lunadragnstar** [comment]
Could we do categories, grasses, saplings, raw food, cooked food, etc...

**Comment by Raycoms** [comment]
Difficult, I mean usually you won't need hundreds. Usually you just want a few of your saplings being used, just a few seeds etc.

**Comment by lunadragnstar** [comment]
It was just an idea :D no biggie if it can't be done.
