### ISSUE TITLE
[Feature request] Mo' Bends Compatibility

### ISSUE THREAD

**Issue by SulpherStaer** [ldtteam/minecolonies#3272]
### Minecolonies version
Version: 1.12.2-0.10.135-BETA

### Expected behavior
The citizen models of Minecolonies get the Mo' Bends player animations and limb bends applied when Mo' Bends is installed.
### Actual behaviour
The citizen models animate like default minecraft player models.

### Mod
https://minecraft.curseforge.com/projects/mo-bends

I am not sure how mo bends applies its enhanced animations and player model, so I am not sure if this is even possible with the way that minecolonies creates its citizens. Though It would be a nice feature if added.

If it isn't at all possible, to bad. 🤷

**Comment by Teirdalin** [comment]
I was wondering about this exact same thing today.  lol

**Comment by Raycoms** [comment]
Will be added to a new joint mod compat issue.
