### ISSUE TITLE
Shepherd requesting wooden shears

### ISSUE THREAD

**Issue by critchards** [ldtteam/minecolonies#3273]
Version: 1.12.2-0.10.135-BETA

### Expected behavior

Shepherd LV1 should start with ability to use iron shears since wood doesnt exist? I think? Seems like this changed since the last update, he was using iron fine before.

### Actual behavior

Shepherd requests wooden or stone or golden shears to begin. This is new since the update to 1.12.2-0.10.135 BETA

### Steps to reproduce the problem

1) Have a shepherd
2)Wait for it
3)He asks for wooden shears....

**Comment by Raycoms** [comment]
This only happens if you provide a mod which adds these

**Comment by critchards** [comment]
I dont have a mod installed that adds wood or stone shears. Gold yes, but the shepherd didnt ask for wood stone or gold before updating to 1.12.2-0.10.135-BETAOn Jan 14, 2019 9:27 AM, Raycoms <notifications@github.com> wrote:This only happens if you provide a mod which adds these

**Comment by critchards** [comment]
I dont have any mods that add wood or stone shears. I have gold shears but the shepherd didnt request them before updating to 1.12.2-0.10.135-BETA

**Comment by critchards** [comment]
Actually now that I search more my builder is requesting a shovel, but I am not able to provide one. I have a  wooden and iron shovel in my inventory and he is requesting a shovel, min level wood, max level iron but there is no option to fulfill his request.

**Comment by critchards** [comment]
And the librarian is doing the same thing with paper.

**Comment by Raycoms** [comment]
Yeah, we're investigating this fulfillment issue. You can fix this by
providing the tool in their inventory and then clicking cancel.

Am Mo., 14. Jan. 2019 um 18:52 Uhr schrieb dilznick5 <
notifications@github.com>:

**Comment by Raycoms** [comment]
Tried to reproduce this, seems to be a mod issue (mod which adds thse kinds of tools)
