### ISSUE TITLE
Un-clickable citizens

### ISSUE THREAD

**Issue by scraw-darkblade** [ldtteam/minecolonies#3275]
**Minecolonies Version**
minecolonies-1.12.2-0.10.134 to 137 ALPHA-universal

**Minecraft Version** 
Minecraft 1.12.2

**Expected Behavior**
Citizen display window which their inventory can be viewed.

**Actual behavior**
Idle citizens cannot be clicked therefore inventory cannot be viewed.

**Additional Details**
There are no clear step how to reproduce this problem but the following is situation is present
to produce the issue.

1. Playing at SSP
2. Townhall is repeatedly destroyed at put back again.
3. Because of this, existing citizen wandered too far
3. Colony was repeatedly deleted and restarted (only 1 colony present per game)

Vanilla Fix manage to caught the problem when even the builder became un-clickable. For me to reproduce the problem (but only with  citizens with jobs) is to click the citizen several times.
https://paste.dimdev.org/dilayetohi.mccrash

I also uploaded the list of my mods for reference.

![modlist](https://user-images.githubusercontent.com/40409138/51157057-87f13f00-18c1-11e9-8a40-24596d73e023.png)

**Comment by Raycoms** [comment]
Yeah, it's a vanilla problem with entities, let's hope 1.13 takes care of it.
Hitting them, shift clicking them or recalling them or as last resort /mc citizens respawn solves it
