### ISSUE TITLE
Add Recall to Player option 

### ISSUE THREAD

**Issue by lunadragnstar** [ldtteam/minecolonies#3276]
Is there a way to get a Recall to player thing added, maybe through the black board that Orion was talking about?

**Comment by marchermans** [comment]
The blackboard is more something for the request system at least initially. A recall option exists: recall them to their hut.

**Comment by Wissi** [comment]
Well lunadragnstar's idea is good one. 
Could we add a page to the "clipboard" f.e. (called: Recall Citizen) and have the page list all the citizens names and their job (perhaps). 
Option 1- Option to select the name(s) of the citizen(s) and a button to recall them to player's position.
Option 2- When clicking on the name of the Citizen it will recall that citizen to the player's position?

**Comment by Nightenom** [comment]
I agree with @OrionDevelopment, don't be so lazy

**Comment by Raycoms** [comment]
you got a recall at the townhall for the individual citizens as well, in
the future an item is planned which does this on the fly.

Am Di., 5. Feb. 2019 um 19:10 Uhr schrieb Nightenom <
notifications@github.com>:
