### ISSUE TITLE
Warehouse orders deliveryman to deliver same Stack multiple Times

### ISSUE THREAD

**Issue by schafhierte204** [ldtteam/minecolonies#3280]
-

### Actual behavior

 If the warehouse hasn't enough items to fulfill the request it orders the delivery of the same stack multiple times.

### Suggested behavior
   The warehouse should order to deliver the items it has and pass the rest down the chain

### Steps to Reproduce
1. Build a Townhall,a Deliveryman, a Warehouse and a Postbox
2. Put some items in the Warehouse
3. Request more items than you put in the Warehouse
4. Profit ...

**Comment by schafhierte204** [comment]
Edit: Added Steps to reproduce

**Comment by marchermans** [comment]
Please post which version number you are running!

**Comment by marchermans** [comment]
Since we patched this yesterday.

**Comment by schafhierte204** [comment]
I run my one up to date source build and it still happens when putting 10 cobblestone in the warehouse and requesting 20

**Comment by schafhierte204** [comment]
I did some more testing and found out that it is still happens when you request up to 3 times the items you put in

**Comment by marchermans** [comment]
I need your version number!, anything else is unsupported by nature. I need to know exactly what you run and how it is packaged!

**Comment by schafhierte204** [comment]
commit 7abbf5d3656dfdf166a4f2e67b49de00956e50bb

**Comment by schafhierte204** [comment]
I run my own fork in intellij and it has 0 differences to this repo. It should be version 0.10.289 when the official build finishes,

**Comment by marchermans** [comment]
Okey...
Weird
I and Ray tested it.
