### ISSUE TITLE
Builder Gets Stuck if at build limit

### ISSUE THREAD

**Issue by jsliu013** [ldtteam/minecolonies#3285]
### Minecolonies version

Version: 1.12.2-0.10.139-ALPHA

### Expected behavior

- Message from builder and/or warning indicating at build height/ builder quits building after error. 

### Actual behaviour

-  Builder tries to continuously build and stares into eternity.
   

### Steps to reproduce the problem

1. Get Close to Build Limit
2. Build Oak Town Hall
3. ???
4. ... Profit

**Comment by fizzy6868** [comment]
you can ether cancel the build job by right clicking the building and cancel or if you are admin you can increase build height

**Comment by jsliu013** [comment]
The issue is less that I hit build limit but more along the lines that there is no log or message that informs the player which may cause issues if that building was t1 town hall or in my case builder which means.. i couldn't build anything else.

**Comment by Raycoms** [comment]
So what we need is: A log which tells you that you reached the limit
