### ISSUE TITLE
AI stops working properly when about a chunk away.

### ISSUE THREAD

**Issue by Teirdalin** [ldtteam/minecolonies#3286]
### Minecolonies version

Version: 1.12.2-0.10.139-ALPHA

### Expected behavior

I expect workers to work and NPCs to walk around when at a mid/long range from the player in chunks that are loaded.

### Actual behaviour

Workers/AI starts taking about a step per second once reaching a distance of about 16-20m from the player. 
Seems an intended feature since it relies on the player being close; so curious if it's related to something in the config.

https://i.imgur.com/pkDppmL.jpg

### Steps to reproduce the problem
Hosting a server with forge-1.12.2-14.23.5.2768-universal.jar running quite a lot of mods; although I cannot imagine any really causing behavior such as this.

**Comment by marchermans** [comment]
@Raycoms looks like your update broke some things

**Comment by Teirdalin** [comment]
> @Raycoms looks like your update broke some things

Also unrelated, but I made a field through the decoration build menu and the farmer I hired to the farm kept asking for hoes and not actually doing anything with them.      And I've been having workers spawning with stats of 1/1/1/1/1 and been just killing them off in hopes of some more normal ones spawning;  not sure if that's intended as this is the first version I've used though and neither issues really are as bothersome as the slow movement thing.

**Comment by Raycoms** [comment]
@OrionDevelopment no this is a sponge setting.
About the citizens, the stats depend on the happiness of your colonies, killing citizens resets happiness to 1, so new citizens spawn all 1, you now gotta wait for your happiness to go up to get better ones.

**Comment by Raycoms** [comment]
https://github.com/ldtteam/minecolonies/issues/1874

**Comment by Raycoms** [comment]
This is a sponge issue, you have to increase the entity activation range
for the citizens.

Am Do., 17. Jan. 2019 um 08:29 Uhr schrieb Teirdalin <
notifications@github.com>:

**Comment by Teirdalin** [comment]
Ah,  thanks a lot Raycoms!
Still fairly new to sponge and didn't realize it had an entity activation range integrated in.

**Comment by Paddy69** [comment]
i am not using sponge or a server, im using the [SteamPunk](https://www.curseforge.com/minecraft/modpacks/steam-punk) mod pack and am in singleplayer, (btw i added minecolonies to the pack myself)
version is 1.19.2 
forge - 43.2.14
minecolonies-1.19.2-1.0.1351-RELEASE.jar

**Comment by Raycoms** [comment]
Optifine?

**Comment by Paddy69** [comment]
> Optifine?

no

**Comment by MotionlessTrain** [comment]
It looks like rubidium extras could be doing this. They seem to have a range option outside which entities are not ticked (do not work/are not processed)

Also please don't comment on issues that are closed for 4 and a half years

**Comment by Paddy69** [comment]
> 

my bad, felt like 2019 was a couple of months ago
