### ISSUE TITLE
NPE crash on Clipboard

### ISSUE THREAD

**Issue by MineShadow7** [ldtteam/minecolonies#3287]
### Minecolonies version
1.12.2-0.10.139

Version: 

Issue: 
NPE crash on clicking "back" button after seeing details about request.

Crash report attached:
[crash-2019-01-18_13.20.31-client.txt](https://github.com/ldtteam/minecolonies/files/2772539/crash-2019-01-18_13.20.31-client.txt)

**Comment by fizzy6868** [comment]
looks to me the InventoryTweaks-1.63.jar is causing issues might be a compatibility issue try removing it first and see if that works

**Comment by marchermans** [comment]
@fizzy6868 this has nothing todo with inv tweaks

**Comment by Raycoms** [comment]
Merged the hotfix
