### ISSUE TITLE
peoples

### ISSUE THREAD

**Issue by vesafra** [ldtteam/minecolonies#3288]
### Minecolonies version
10.109 release

Version: 1.12.2

### Expected behavior

-  peoples

### Actual behaviour

- peoples don't spawn when i put town hall, and town hall does not have a gui

### Steps to reproduce the problem

1. place town hall
2. 
3. 
4. ... Profit

**Comment by MineShadow7** [comment]
Try to update to newer version (10.139 for ex). Tell us if it helps...

**Comment by vesafra** [comment]
> 
> 
> Try to update to newer version (10.139 for ex). Tell us if it helps...

it don't

**Comment by Raycoms** [comment]
uhm, a few questions, is there a log when you righ tclick the townhall?
Second, did you try a new world?

Am Fr., 18. Jan. 2019 um 13:31 Uhr schrieb vesafra <notifications@github.com

**Comment by fizzy6868** [comment]
1. delete the mod and the mod configs
2. clear all browser history
3. download the mod again that should work
i believe you have a corrupt file somewhere

**Comment by vesafra** [comment]
problem was structurize. i had old version

**Comment by vesafra** [comment]
works now
