### ISSUE TITLE
Let the builder use the correct blockstates.

### ISSUE THREAD

**Issue by Raycoms** [ldtteam/minecolonies#329]
The builder pretty often places things independently of their damage value.
We have to refine this system.
(Including plantpots, itemframes etc)

**Comment by neadlak** [comment]
This would be why builder requests one color of carpet, then builds a different color in a structure?

**Comment by Raycoms** [comment]
Exactly.

2016-12-08 21:43 GMT-02:00 neadlak <notifications@github.com>:

**Comment by pmardle** [comment]
Yeah this needs fixing/improving :)
