### ISSUE TITLE
Farmer only uses one field

### ISSUE THREAD

**Issue by K1ngAdi** [ldtteam/minecolonies#3290]
### Minecolonies version
Version: currently 0.10.138-ALPHA but problem occured several versions before 

### Expected behavior
A Farmer should work on all assigned fields

### Actual behaviour
The farmer only works on the latest built field. Sometimes he walks to the seccond last built farm and harvests about 1 pumpkin per hour. The field he harvests is planted with wheat. The seccond is pumkin and the third is carrots. 

Farmer level is 17, hut-level is 5
hire+fire had no effect. Recall and Restart  also had no effect. 

Serverrestart also had no effect.

An image of my farmsetup
![2019-01-18_22 35 15](https://user-images.githubusercontent.com/24273522/51414136-a2514400-1b71-11e9-882f-905cec5b6aa7.png)

### Steps to reproduce the problem

1. I don't know how this happend because I realized it while playing

**Comment by Kriiks** [comment]
Exactly same issue at least trough last 10 alpha builds too. Have to do all work for them.
Farmer is only tending one field, even if assigned to 2 or 3.

**Comment by Raycoms** [comment]
Same: #3231
