### ISSUE TITLE
Can't remove supply ship.

### ISSUE THREAD

**Issue by Smearfo** [ldtteam/minecolonies#3293]
### Minecolonies version

Version: 1.10.109-RELEASE

### Expected behavior
Allowing replacement of supply ship via removing achievement

- In order to replace the supply ship, one would revoking the achievement related to it.

### Actual behaviour
Achievements don't exist.

- The achievements for Minecolonies don't exist anymore, and therefore nor does the achievement for the supply ship.

### Steps to reproduce the problem

1. Place supply ship in the wrong area
2. Try to move supply ship
3. Realize there's no achievements any more
4. ... Panic

**Comment by Raycoms** [comment]
It's not in the achievement, its in the player stats, you gotta delete the whole player file for that.
