### ISSUE TITLE
workers are broken

### ISSUE THREAD

**Issue by CharCharthemonkey** [ldtteam/minecolonies#3294]
### Minecolonies version

Version: 1.12.2-0.10.143alpha

### Expected behavior

- not to crash please

### Actual behaviour

-  upon trying to find jobs for wat ever reason the game crashes due to a bug in minecolonies and has happened several times

### Steps to reproduce the problem

1.  load up MC with the 143alpha or possibly later versions
2. have colonists try to find jobs
3. crash
[crash-2019-01-20_12.31.22-server.txt](https://github.com/ldtteam/minecolonies/files/2780130/crash-2019-01-20_12.31.22-server.txt)
[crash-2019-01-20_19.34.21-server.txt](https://github.com/ldtteam/minecolonies/files/2780131/crash-2019-01-20_19.34.21-server.txt)
[crash-2019-01-20_22.44.39-server.txt](https://github.com/ldtteam/minecolonies/files/2780132/crash-2019-01-20_22.44.39-server.txt)
[crash-2019-01-21_12.02.11-server.txt](https://github.com/ldtteam/minecolonies/files/2780133/crash-2019-01-21_12.02.11-server.txt)
[crash-2019-01-21_12.15.23-server.txt](https://github.com/ldtteam/minecolonies/files/2780134/crash-2019-01-21_12.15.23-server.txt)

4. ... Profit

**Comment by Raycoms** [comment]
Should be fixed
