### ISSUE TITLE
Cook not cooking. Ask what fuel to use

### ISSUE THREAD

**Issue by FirzenDark** [ldtteam/minecolonies#3295]
### Minecolonies version

Version:  1.12.2-0.10.145-ALPHA

### Expected behavior

- 

Give coal to add to furnace.

### Actual behaviour

- 

Cook just keep on asking 'Please tell me what type of fuel to use'

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit

**Comment by SulpherStaer** [comment]
Go to the next page for the cook, there you can check on or off what fuel they can use to cook food. Untill you've set the allowed fuel items, they won't use the coal anyway.

**Comment by FirzenDark** [comment]
Thanks Sylvester.

It is working now.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
