### ISSUE TITLE
Builder cannot complete upgrade of Farm

### ISSUE THREAD

**Issue by animedad420** [ldtteam/minecolonies#3296]
### Minecolonies version

Version: 0.10.139-ALPHA

### Expected behavior

- Farm should be upgrading from first level to second. I'm playing on the test server, colony ID 9 if you need to investigate manually.

### Actual behaviour

- Farm won't upgrade. The builder will build the structure itself completely but won't finalise the job, so the upgrade never completes. Every morning they will go to the builder's hut, then to the farm, and then just stand there until I reset them. I've reset the request system, fired and hired the builder, they still go through this routine despite my efforts. Destroying and rebuilding the farm from scratch caused no change in behaviour.
### Some other quirks I've noticed during the upgrade process that might be related:
- Builder couldn't break a tall BoP fern that I had to break for them myself.
- Weird pathing issues, builder would run to a node adjacent to the farm then run right back to the builder's hut without placing a block (This seems to have fixed itself, somehow). The farm is right next to a road, should I not be doing this?
- Builder destroyed crops during the upgrade process. I don't remember them doing this in previous versions.

**Comment by Raycoms** [comment]
Which farmer building?

Am Di., 22. Jan. 2019 um 01:05 Uhr schrieb animedad420 <
notifications@github.com>:

**Comment by animedad420** [comment]
Medieval Oak. I also notice now that there's a torch that they never end up placing. Placing the torch myself has no effect, upgrade still won't complete.

**Comment by lunadragnstar** [comment]
I will look into this to see if it is an issue with the schematic.

**Comment by lunadragnstar** [comment]
The schematic looks fine, and I was able to build it on my single game with all mods in the pack.

**Comment by animedad420** [comment]
My only theory is that this is related to pathfinding and the nodes somehow, the builder is having weird pathing issues that none of the other villagers are having.

Screenshots of the farm:
https://i.snag.gy/0dlF36.jpg
https://i.snag.gy/WfYwpa.jpg

**Comment by animedad420** [comment]
Sorry for the double post, but I have a new theory. In the second screenshot, you'll notice that the barn area on the farm is lit, as if there was a torch there, but no torch. And after I cleared out my supply camp, the area is still lit as if the torches are still there. Perhaps the builder thinks the torch is there when it isn't, so they can't complete the build. Could there be something in the testpack causing these issues?

**Comment by Raycoms** [comment]
There might be a weird bug causing this. Is there any spam in the log?

**Comment by animedad420** [comment]
I'm not sure how to check the logs from an online session

**Comment by Raycoms** [comment]
Oh it is on the official server?

**Comment by animedad420** [comment]
Yeah it's on the test server. I can give you the coords if you need to investigate ingame

**Comment by Raycoms** [comment]
Might be fixed

**Comment by animedad420** [comment]
I'll try to verify that my problem has been solved when the testpack next updates

**Comment by animedad420** [comment]
Tried again after the update, farm was able to upgrade! Nicely done
