### ISSUE TITLE
Minecolonie workers are bugged

### ISSUE THREAD

**Issue by unknownlargo** [ldtteam/minecolonies#3297]
### Minecolonies version

Version: 1.12.2-0.9.1

### Expected behavior
the workers actually walking around doing work

- 

### Actual behaviour

The workers act as if it is always night time. Constantly running in and out of the town hall or their homes. They start a process, i.e the wood cutter starts chopping and is walking around while they chop.  Running to a tree and then running back to the town hall back and forth without actually doing work. Tried killing to reset them. Tried hiring and firing them. Tried using a command to kill barbarians possibly. Same with mobs. Nothing worked.
- 

### Steps to reproduce the problem
only happened once. Hasnt been fixed. Perminantly like this

1. 
2. 
3. 
4. ... Profit

**Comment by Raycoms** [comment]
Do you have a barbarian attack around? did you try /mc kill raider ?

Am Di., 22. Jan. 2019 um 07:46 Uhr schrieb unknownlargo <
notifications@github.com>:

**Comment by unknownlargo** [comment]
Yea. As I said i did try and use the command to kill barbarians. Didnt kill anything. I did get a command got a barb attack but when I killed one it said one left but mc kill barbarians didnt work

**Comment by Raycoms** [comment]
We changed the command to mc kill raider from barbarian.

Am Di., 22. Jan. 2019 um 08:42 Uhr schrieb unknownlargo <
notifications@github.com>:

**Comment by unknownlargo** [comment]
I'll give it a try tonight and let you know if it fixes it.

**Comment by unknownlargo** [comment]
I gave it a try. Mc kill raider does nothing. Shows up the commands list which is barbarians, mob, animals, etc. Npcs are still glitched out and not working

**Comment by Raycoms** [comment]
You might want to update the minecolonies version. I just saw yours is
quite old as well.

Am Do., 24. Jan. 2019 um 06:56 Uhr schrieb unknownlargo <
notifications@github.com>:

**Comment by Raycoms** [comment]
Newest version should fix it

**Comment by unknownlargo** [comment]
It's part of a modpack so that will be fun to deal with.  But ill give it a try.

**Comment by Raycoms** [comment]
Yeah a lot of modpacks are very lazy to update unfortunately.

Am Do., 24. Jan. 2019 um 15:03 Uhr schrieb unknownlargo <
notifications@github.com>:
