### ISSUE TITLE
Warehouse Sort Function breaks Minecraft

### ISSUE THREAD

**Issue by CptTbone** [ldtteam/minecolonies#3299]
### Minecolonies version

Version: 1.12.1-0.10.109-RELEASE-universal

### Expected behavior

- Warehouse inventory sorted

### Actual behaviour

- Minecraft does not crash per se, but once I click the 'Sort' button, I'm essentially no longer able to right click to interact with anything, even things like harvesting wheat. Things like storage racks, crafting tables, etc do not work. I use Mega Loots in this mod pack as well and the jet pack ability acts like its disabled once I click the 'Sort' button. Villagers basically freeze in place. Only when I attempt to save and quit is when the game freezes, in which case I have to ctrl+alt+del and manually end java, which shows its not responding.

### Steps to reproduce the problem

1. Click the 'Sort' button in the Warehouse

**Comment by Raycoms** [comment]
How much RAM did you give to minecraft?

Am Mi., 23. Jan. 2019 um 18:10 Uhr schrieb CptTbone <
notifications@github.com>:

**Comment by CptTbone** [comment]
In game looks like this...not sure which of the two values in the top right is what you need.

![image](https://user-images.githubusercontent.com/46872696/51635113-041ffe00-1f24-11e9-9a5d-77aee5f2994a.png)

**Comment by Raycoms** [comment]
Weird, 8GB is quite a lot, definitely not a potatoe PC, do you have any
special inventories in your warehouse?

Am Mi., 23. Jan. 2019 um 18:33 Uhr schrieb CptTbone <
notifications@github.com>:

**Comment by CptTbone** [comment]
Nothing out of the ordinary and that hasn't already been in there before :/....here is the log in case it helps. You'll notice the error looping at the end, not sure if this is the cause, but I deleted a lot from the log (approx 600 pages that all had the same error).

[latest.log](https://github.com/ldtteam/minecolonies/files/2789160/latest.log)

**Comment by Raycoms** [comment]
Can you try if this also happens with the newest alpha?

Am Mi., 23. Jan. 2019 um 19:11 Uhr schrieb CptTbone <
notifications@github.com>:

**Comment by CptTbone** [comment]
No change unfortunately, acts exactly as it did in the older version.

**Comment by Raycoms** [comment]
Weird, seems like some chest in your warehouse is broken (code-wise), I'll
look into it in a bit.

Am Mi., 23. Jan. 2019 um 19:22 Uhr schrieb CptTbone <
notifications@github.com>:

**Comment by CptTbone** [comment]
Thanks! I'm working towards upgrading it to lvl 5 now in an attempt to fix it, however you likely will finish your review before my builder finishes the building ;)

**Comment by Raycoms** [comment]
Is your warehouse very, very full? As in, 100% full or 99%?

Am Mi., 23. Jan. 2019 um 18:28 Uhr schrieb Ray Neiheiser <
ray.neiheiser@gmail.com>:

**Comment by CptTbone** [comment]
No - that was one of my first thoughts as well...I'd say maybe close to 60-80% full. I still have some empty racks

**Comment by Raycoms** [comment]
Really weird.

Am Mi., 23. Jan. 2019 um 19:49 Uhr schrieb CptTbone <
notifications@github.com>:

**Comment by CptTbone** [comment]
For the sake of testing, let me backup my world and I'll turn the config option to 'true' for building without resources to see if the error persists when it gets repaired.

**Comment by Raycoms** [comment]
you can also just "paste in gamemode 1 with the buildtool" to make it
instant

Am Mi., 23. Jan. 2019 um 19:52 Uhr schrieb CptTbone <
notifications@github.com>:

**Comment by CptTbone** [comment]
No luck :( - a repair and even an upgrade to lvl 5 warehouse didn't fix it

**Comment by CptTbone** [comment]
Looking at the log, looks to show the same error. Think I might offload the contents into chests, remove the racks, and then attempt a repair?

**Comment by Raycoms** [comment]
Might be a work around, can you send me the world?

Am Mi., 23. Jan. 2019 um 20:30 Uhr schrieb CptTbone <
notifications@github.com>:

**Comment by CptTbone** [comment]
I can - what file are you specifically looking for? level.dat?

**Comment by Raycoms** [comment]
No I need the world

Am Mi., 23. Jan. 2019 um 20:53 Uhr schrieb CptTbone <
notifications@github.com>:

**Comment by CptTbone** [comment]
Sorry - unsure what you mean by the world? The entire save folder you mean?

**Comment by Raycoms** [comment]
yeah, just without mods

Am Mi., 23. Jan. 2019 um 21:04 Uhr schrieb CptTbone <
notifications@github.com>:

**Comment by CptTbone** [comment]
Sure thing - let me get it zipped and into Google Drive. Interestingly enough, I tested one of my backups and it the sort function seems to work fine there (backup was done yesterday afternoon).

**Comment by Raycoms** [comment]
Weird, something must've corrupted one of the racks

Am Mi., 23. Jan. 2019 um 21:44 Uhr schrieb CptTbone <
notifications@github.com>:

**Comment by CptTbone** [comment]
Yea - think you're right. I will play from that backup save folder, I'm good with that as not too much happened between then and now. Are you still interested in the world?

**Comment by Raycoms** [comment]
yes please

Am Mi., 23. Jan. 2019 um 21:50 Uhr schrieb CptTbone <
notifications@github.com>:

**Comment by CptTbone** [comment]
Hopefully that's what you need: https://drive.google.com/open?id=1Q1gXMpgkmm7YYU9hP-CombCMHn7NCXAR

**Comment by Raycoms** [comment]
Thanks, will check tomorrow after sleeping =)

Am Mi., 23. Jan. 2019 um 22:04 Uhr schrieb CptTbone <
notifications@github.com>:

**Comment by Raycoms** [comment]
fixed
