### ISSUE TITLE
Workers Pathfinding issues.

### ISSUE THREAD

**Issue by Wissi** [ldtteam/minecolonies#330]
If the Farmer's hut is fenced in with his "fields so that the farmer can't leave the hut/field area, when it's night time he will stand still as close to the direction of the Citizen's hut and even if it turns day time he continues standing still there. Will NOT go back to work until he is "recalled".

Same situation with the Lumberjack. If his hut is "fenced" in with a "grove" so he can't leave this area, he will also stand still at the nearest point towards the Citizens hut and even if it turns day time he will continue standing there. Will NOT go back to work unless he is "recalled".

Can't the Workers with a hut STAY at their hut during night time? And just continue to work from there, forget completely about the Citizen's hut since they have a hut. This would decrease the pathfinding for the workers once employed. They would only be pathfinding from their hut to their field/grove and back?

Unemployed workers might seems logical, but not workers with a hut? Citizen huts were purposely built at the edge of the Townhall radius and both farmers and the lumberjack huts are almost opposite of the Town radius. If they were to leave at night and come back it takes them 1/4 to 1/2 a day just to go and come back to their huts.

**Comment by Raycoms** [comment]
That's intentional behaviour.
The worker huts do not offer any space to sleep or similar. The plan would
even be that later on, the workers will sleep in the beds and get their
food from their home chests.
This would be another factor to consider when planning the town.

2016-12-08 2:57 GMT-02:00 Wissi <notifications@github.com>:
