### ISSUE TITLE
Warehouse sort function not working after upgrading storage of level 5 warehouse

### ISSUE THREAD

**Issue by Zhythero** [ldtteam/minecolonies#3302]
### Minecolonies version
minecolonies-1.12.2-0.10.109-RELEASE-universal.jar

### Expected behavior
Be able to sort warehouse.

### Actual behaviour
Warehouse sort function no longer works after upgrading storage with emerald blocks.

The sort function was functioning since warehouse level 1 to 5 without storage upgrade. Bug exists after upgrading storage with emerald blocks. This happened twice because I built a town twice.

### Steps to reproduce the problem

1. Build warehouse (Medieval Dark Oak schematic)
2. Upgrade warehouse to level 5
3. Upgrade storage with emerald block
4. Try to click sort
4. ... Profit

**Comment by Raycoms** [comment]
fixed
