### ISSUE TITLE
Enhancement Request: Non-Builder citizens do not cross construction tape blocks

### ISSUE THREAD

**Issue by spacewolfcub** [ldtteam/minecolonies#3303]
### Minecolonies version
minecolonies-1.12.2-0.10.134-ALPHA-universal 

### Actual behaviour
Citizens wander into construction sites when idle or unemployed and fall into holes when standing on a block the BuilderNPC removes, and/or get solid blocks or lava placed on them and die. 

### Suggested behaviour
Option 1: Block "Construction Tape" is solid and fence-height but BuilderNPCs can jump just high enough to path over them. 
Option 2: Block "Construction Tape" only allows players and assigned BuilderNPC to walk through it. 
Option 3: Block "Construction Tape" only allows players to walk through until the "Build" button is clicked on a placed hut, then the assigned BuilderNPC is allowed to walk/teleport through it.
Option 4: Block "Construction Tape" only allows players to walk through ever. When the "Build" button is clicked on a placed hut, a box of tools is placed interrupting the ConstructionTape and only the assigned BuilderNPC can walk over the box of tools.

**Comment by Nightenom** [comment]
2 sounds doable and easy to understand

**Comment by Raycoms** [comment]
the problem is allowing one way crossing.

Am Do., 31. Jan. 2019 um 20:20 Uhr schrieb Nightenom <
notifications@github.com>:

**Comment by Nightenom** [comment]
Just add this block as solid when doing pathfinding for non-builders?
AbstractPathJob#isPassable(@NotNull final IBlockState block) looks like the place for doing that

**Comment by Nightenom** [comment]
Sorry for pinging :D wasn't intentional

**Comment by Raycoms** [comment]
The problem is allowing citizens to pass in one direction to leave the build area but not in the other to enter it.

**Comment by someaddons** [comment]
sounds like natural selection to me

**Comment by Raycoms** [comment]
I thought a lot about this and it is not feasible unfortunately, it would have to allow only one way crossing and they would still find a way.
