### ISSUE TITLE
crash before start

### ISSUE THREAD

**Issue by qwerty1av** [ldtteam/minecolonies#3304]
minecolonies version: 1.12.2-0.10.147-ALPHA-universal

### Getting into main menu after opening game

After installing the newest version of minecolonies, I cannot open a game because its crashing.
None of my mods had any conflicts before.

Log details:

---- Minecraft Crash Report ----
// My bad.

Time: 2019-01-26 20:23:02 CET
Description: Initializing game

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from MineColonies (minecolonies)
Caused by: java.lang.NoClassDefFoundError: com/structurize/coremod/placementhandlers/PlacementHandlers$BlockSolidSubstitutionPlacementHandler
      at com.minecolonies.coremod.placementhandlers.MinecoloniesPlacementHandlers.initHandlers(MinecoloniesPlacementHandlers.java:63)
      at com.minecolonies.coremod.MineColonies.init(MineColonies.java:156)
      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      at java.lang.reflect.Method.invoke(Method.java:497)
      at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:606)
      at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      at java.lang.reflect.Method.invoke(Method.java:497)
      at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
      at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
      at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
      at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
      at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
      at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
      at com.google.common.eventbus.EventBus.post(EventBus.java:217)
      at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:278)
      at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:256)
      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      at java.lang.reflect.Method.invoke(Method.java:497)
      at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
      at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
      at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
      at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
      at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
      at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
      at com.google.common.eventbus.EventBus.post(EventBus.java:217)
      at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
      at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:720)
      at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:352)
      at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
      at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3933)
      at net.minecraft.client.main.Main.main(SourceFile:123)
      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      at java.lang.reflect.Method.invoke(Method.java:497)
      at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
      at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: com.structurize.coremod.placementhandlers.PlacementHandlers$BlockSolidSubstitutionPlacementHandler
      at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
      at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
      at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
      ... 42 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Initialization --

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 7 (amd64) version 6.1
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 362919160 bytes (346 MB) / 1073741824 bytes (1024 MB) up to 6442450944 bytes (6144 MB)
  JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.2.2611 Optifine OptiFine_1.12.2_HD_U_C9 30 mods loaded, 30 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                                           | Version               | Source                                            | Signature                                |
       |:----- |:-------------------------------------------- |:--------------------- |:------------------------------------------------- |:---------------------------------------- |
       | UCHI  | minecraft                                    | 1.12.2                | minecraft.jar                                     | None                                     |
       | UCHI  | mcp                                          | 9.42                  | minecraft.jar                                     | None                                     |
       | UCHI  | FML                                          | 8.0.99.99             | forge-1.12.2-14.23.2.2611.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | UCHI  | forge                                        | 14.23.2.2611          | forge-1.12.2-14.23.2.2611.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | UCHI  | ivtoolkit                                    | 1.3.3-1.12            | minecraft.jar                                     | None                                     |
       | UCHI  | com.elytradev.movingworld.common.asm.coremod |                       | minecraft.jar                                     | None                                     |
       | UCHI  | rpghud                                       | 3.6.6.2               | [1.12] RPG-HUD-3.6.6.2.jar                        | None                                     |
       | UCHI  | ambientsounds                                | 2.0.0                 | AmbientSounds v2.0.8 mc1.12.jar                   | None                                     |
       | UCHI  | blockarmor                                   | 2.4.10                | Block-Armor-Mod-1.12.1.jar                        | None                                     |
       | UCHI  | chunkanimator                                | 1.2                   | ChunkAnimator-MC1.12-1.2.jar                      | None                                     |
       | UCHI  | customnpcs                                   | 1.12                  | Custom-NPCs-Mod-1.12.2.jar                        | None                                     |
       | UCHI  | movingworld                                  | 1.12-6.342            | MovingWorld-Mod-1.12.jar                          | None                                     |
       | UCHI  | davincisvessels                              | @DVESSELSVER@         | Davincis-Vessels-Mod-1.12.jar                     | None                                     |
       | UCHI  | hammercore                                   | 2.0.0.3               | HammerCore-1.12.2-2.0.0.3.jar                     | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
       | UCHI  | improvedbackpacks                            | 1.12.2-1.2.0.2        | Improved-Backpacks-Mod-1.12.2.jar                 | None                                     |
       | UCHI  | inventorypets                                | 1.5.3.1               | inventorypets-1.12-1.5.3.1.jar                    | None                                     |
       | UCHI  | llibrary                                     | 1.7.7                 | LLibrary-1.12.2.jar                               | None                                     |
       | UCHI  | lostquiver                                   | 1.0 - MC 1.12.2       | lostquiver-1.0.jar                                | None                                     |
       | UCHI  | structurize                                  | 1.12.2-0.10.38-ALPHA  | structurize-1.12.2-0.10.38-ALPHA.jar              | None                                     |
       | UCHE  | minecolonies                                 | 1.12.2-0.10.147-ALPHA | minecolonies-1.12.2-0.10.147-ALPHA-universal.jar  | None                                     |
       | UCHI  | mopickaxes                                   | 10.0 BETA             | Mo-Pickaxes-1.12.2.jar                            | None                                     |
       | UCHI  | rfpr                                         | 8.1.0                 | Real-First-Person-Render-1.12.2.jar               | None                                     |
       | UCHI  | reccomplex                                   | 1.4.7                 | RecurrentComplex-1.4.7.jar                        | None                                     |
       | UCHI  | additionalstructures                         | 2.0.1                 | Rex's-Additional-Structures-1.12.x+-(v.2.1.0).jar | None                                     |
       | UCHI  | ruins                                        | 17.1                  | Ruins-1.12.2.jar                                  | None                                     |
       | UCHI  | parry                                        | 1.0                   | Shield-Parry-Mod-1.12.2.jar                       | None                                     |
       | UCHI  | vanillafix                                   | 1.0.7+72              | VanillaFix-1.0.7-72.jar                           | None                                     |
       | UCHI  | xaerominimap                                 | 1.15.9                | Xaeros_Minimap_1.15.9_Forge_1.12.jar              | None                                     |
       | UCHI  | xaeroworldmap                                | 1.3.3                 | XaerosWorldMap_1.3.3_Forge_1.12.jar               | None                                     |
       | UCHI  | zeiyocraft                                   | 0.8.4                 | ZeiyoCraft-Mod-1.12.2.jar                         | None                                     |
  Loaded coremods (and transformers): HCASM (HammerCore-1.12.2-2.0.0.3.jar)
                                        com.zeitheron.hammercore.asm.HammerCoreTransformer
                                      MovingWorldCore (MovingWorld-Mod-1.12.jar)
                                        
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.7-72.jar)
                                        
                                      IvToolkit (IvToolkit-1.3.3-1.12.jar)
                                        
                                      llibrary (LLibrary-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
                                        lumien.chunkanimator.asm.ClassTransformer
  GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13542 Compatibility Profile Context 25.20.14011.10001' Renderer: 'AMD Radeon R9 200 Series'
  Hammer Core Information: FluidDictionary Info: Registered 2 fluids.
                           OreDictionary Info: Registered 181 names; 200 stacks.
                           Configuration Info: IyBDb25maWd1cmF0aW9uIGZpbGUNCg0KY2xpZW50IHsNCiAgICAjIFNob3VsZCBIYW1tZXIgQ29yZSByZXBsYWNlIGVuY2hhbnRtZW50IGdsaW50IGNvbG9yIHdpdGggbW9yZSBtYXRjaGluZyBjb2xvcnMgZm9yIHNvbWUgdmFuaWxsYSBpdGVtcz8gW2RlZmF1bHQ6IHRydWVdDQogICAgQjoiQ3VzdG9tIEVuY2hhbnRtZW50IENvbG9ycyBmb3IgVmFuaWxsYSBJdGVtcyI9dHJ1ZQ0KDQogICAgIyBTaG91bGQgSGFtbWVyIENvcmUgcG9ydGZvcndhcmQgeW91ciBsb2NhbCB3b3JsZCB3aGVuIHlvdSBzaGFyZSB3aXRoIGl0IHRvIExBTj8NCiAgICAjIFRoaXMgZmVhdHVyZSBkb2Vzbid0IHdvcmsgb24gYWxsIGNsaWVudHMsIHlvdSBhcmUgZ29pbmcgdG8gZ2V0IGEgbWVzc2FnZSBpbiBjaGF0IGlmIGl0IHdhcyBzdWNjZXNzZnVsL3Vuc3VjY2Vzc2Z1bCBbZGVmYXVsdDogdHJ1ZV0NCiAgICBCOiJMQU4gVVBuUCI9dHJ1ZQ0KDQogICAgIyBSZXBsYWNlIHZhbmlsbGEgZnVybmFjZSBhbmQgYnJld2luZyBzdGFuZCBwcm9ncmVzcyBiYXJzIHRvIHVzZSBzbW9vdGggcmVuZGVyaW5nPyBbZGVmYXVsdDogdHJ1ZV0NCiAgICBCOiJTbW9vdGggVmFuaWxsYSBHdWlzIj10cnVlDQp9DQoNCg0KaXdyZW5jaCB7DQogICAgIyBXaGF0IGlzIHRoZSBjb2xvciB3aGVuIHRoZSBob3ZlcmVkIGJsb2NrIGlzIHdyZW5jaGFibGU/IChjb2xvciBlbmNvZGVkIGluIGhleCBmb3JtIHN1Y2ggYXMgUlJHR0JCKQ0KICAgIFM6R3JlZW49MjJGRjIyDQoNCiAgICAjIFdoYXQgaXMgdGhlIGNvbG9yIHdoZW4gdGhlIGhvdmVyZWQgYmxvY2sgaXMgTk9UIHdyZW5jaGFibGU/IChjb2xvciBlbmNvZGVkIGluIGhleCBmb3JtIHN1Y2ggYXMgUlJHR0JCKQ0KICAgIFM6UmVkPUZGMjIyMg0KfQ0KDQoNCiJ2YW5pbGxhIGltcHJvdmVtZW50cyIgew0KICAgICMgU2hvdWxkIEhhbW1lciBDb3JlIGZvcmNlLXNwYXduIEVuZGVyIERyYWdvbiBFZ2cgb24gRW5kZXIgRHJhZ29uIGRlYXRoPyBbZGVmYXVsdDogdHJ1ZV0NCiAgICBCOiJBbHdheXMgU3Bhd24gRHJhZ29uIEVnZyI9dHJ1ZQ0KfQ0KDQoNCg==
                           Pastebin Connection: Okay.
  Suspected Mods: MineColonies (minecolonies)
  Launched Version: 1.12.2-forge1.12.2-14.23.2.2611
  LWJGL: 2.9.4
  OpenGL: AMD Radeon R9 200 Series GL version 4.5.13542 Compatibility Profile Context 25.20.14011.10001, ATI Technologies Inc.
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: 
  Current Language: Polski (Polska)
  Profiler Position: N/A (disabled)
  CPU: 8x AMD FX(tm)-8350 Eight-Core Processor

**Comment by Raycoms** [comment]
It seems you are using structurize as a separate mod, can you upgrade to
the version 10.40 ?

Am Sa., 26. Jan. 2019 um 18:17 Uhr schrieb -Av- <notifications@github.com>:

**Comment by qwerty1av** [comment]
Thanks for reply!
I updated structurize mod to the version 10.40 and game started working!
However, when Im trying to open a savegame, after few seconds of loading screen Im getting this message:
Shutting ingame server
After the message  my game is either crashing or getting back to main menu.
This problem only happens to me  with 1 specific save, other or new worlds are doing fine.
Thanks for helping me out anyway :)
Here's next log:
---- Minecraft Crash Report ----
// I blame Let's Dev Together Team, author of MineColonies.

Time: 2019-01-26 23:03:06 CET
Description: Ticking entity

java.lang.NoSuchMethodError: net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToAllTracking(Lnet/minecraftforge/fml/common/network/simpleimpl/IMessage;Lnet/minecraft/entity/Entity;)V
      at com.minecolonies.coremod.entity.ai.minimal.EntityAIEatTask.eat(EntityAIEatTask.java:217)
      at com.minecolonies.coremod.entity.ai.minimal.EntityAIEatTask.func_75246_d(EntityAIEatTask.java:185)
      at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
      at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:883)
      at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2350)
      at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:678)
      at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178)
      at com.minecolonies.coremod.entity.EntityCitizen.func_70636_d(EntityCitizen.java:572)
      at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170)
      at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
      at net.minecraft.world.World.func_72866_a(World.java:1990)
      at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:831)
      at net.minecraft.world.World.func_72870_g(World.java:1952)
      at net.minecraft.world.World.redirect$updateEntity$zzm000(World.java:4614)
      at net.minecraft.world.World.func_72939_s(World.java:1756)
      at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)
      at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
      at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
      at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
      at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
      at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Entity being ticked --
  Entity Type: minecolonies:citizen (com.minecolonies.coremod.entity.EntityCitizen)
  Entity ID: 28
  Entity Name: Gregory P. Gooder
  Entity's Exact location: 798.83, 63.00, -500.41
  Entity's Block location: World: (798,63,-501), Chunk: (at 14,3,11 in 49,-32; contains blocks 784,0,-512 to 799,255,-497), Region: (1,-1; contains chunks 32,-32 to 63,-1, blocks 512,0,-512 to 1023,255,-1)
  Entity's Momentum: 0.00, -0.08, 0.00
  Entity's Passengers: []
  Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Affected level --
  Level name: modz
  All players: 1 total; [EntityPlayerMP['GIVEMELOOT'/12, l='modz', x=801.81, y=63.50, z=-500.30]]
  Chunk stats: ServerChunkCache: 936 Drop: 0
  Level seed: 4728022385061131706
  Level generator: ID 00 - default, ver 1. Features enabled: true
  Level generator options: 
  Level spawn location: World: (-240,64,192), Chunk: (at 0,4,0 in -15,12; contains blocks -240,0,192 to -225,255,207), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
  Level time: 6030392 game time, 27565 day time
  Level dimension: 0
  Level storage version: 0x04ABD - Anvil
  Level weather: Rain time: 17153 (now: false), thunder time: 40873 (now: false)
  Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 7 (amd64) version 6.1
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 1014685440 bytes (967 MB) / 1895825408 bytes (1808 MB) up to 6442450944 bytes (6144 MB)
  JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
  IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
  FML: MCP 9.42 Powered by Forge 14.23.2.2611 Optifine OptiFine_1.12.2_HD_U_C9 30 mods loaded, 30 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State     | ID                                           | Version               | Source                                            | Signature                                |
       |:--------- |:-------------------------------------------- |:--------------------- |:------------------------------------------------- |:---------------------------------------- |
       | UCHIJAAAA | minecraft                                    | 1.12.2                | minecraft.jar                                     | None                                     |
       | UCHIJAAAA | mcp                                          | 9.42                  | minecraft.jar                                     | None                                     |
       | UCHIJAAAA | FML                                          | 8.0.99.99             | forge-1.12.2-14.23.2.2611.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | UCHIJAAAA | forge                                        | 14.23.2.2611          | forge-1.12.2-14.23.2.2611.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | UCHIJAAAA | ivtoolkit                                    | 1.3.3-1.12            | minecraft.jar                                     | None                                     |
       | UCHIJAAAA | com.elytradev.movingworld.common.asm.coremod |                       | minecraft.jar                                     | None                                     |
       | UCHIJAAAA | rpghud                                       | 3.6.6.2               | [1.12] RPG-HUD-3.6.6.2.jar                        | None                                     |
       | UCHIJAAAA | ambientsounds                                | 2.0.0                 | AmbientSounds v2.0.8 mc1.12.jar                   | None                                     |
       | UCHIJAAAA | blockarmor                                   | 2.4.10                | Block-Armor-Mod-1.12.1.jar                        | None                                     |
       | UCHIJAAAA | chunkanimator                                | 1.2                   | ChunkAnimator-MC1.12-1.2.jar                      | None                                     |
       | UCHIJAAAA | customnpcs                                   | 1.12                  | Custom-NPCs-Mod-1.12.2.jar                        | None                                     |
       | UCHIJAAAA | movingworld                                  | 1.12-6.342            | MovingWorld-Mod-1.12.jar                          | None                                     |
       | UCHIJAAAA | davincisvessels                              | @DVESSELSVER@         | Davincis-Vessels-Mod-1.12.jar                     | None                                     |
       | UCHIJAAAA | hammercore                                   | 2.0.0.3               | HammerCore-1.12.2-2.0.0.3.jar                     | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
       | UCHIJAAAA | improvedbackpacks                            | 1.12.2-1.2.0.2        | Improved-Backpacks-Mod-1.12.2.jar                 | None                                     |
       | UCHIJAAAA | inventorypets                                | 1.5.3.1               | inventorypets-1.12-1.5.3.1.jar                    | None                                     |
       | UCHIJAAAA | llibrary                                     | 1.7.7                 | LLibrary-1.12.2.jar                               | None                                     |
       | UCHIJAAAA | lostquiver                                   | 1.0 - MC 1.12.2       | lostquiver-1.0.jar                                | None                                     |
       | UCHIJAAAA | structurize                                  | 1.12.2-0.10.40-ALPHA  | structurize-1.12.2-0.10.40-ALPHA.jar              | None                                     |
       | UCHIJAAAA | minecolonies                                 | 1.12.2-0.10.147-ALPHA | minecolonies-1.12.2-0.10.147-ALPHA-universal.jar  | None                                     |
       | UCHIJAAAA | mopickaxes                                   | 10.0 BETA             | Mo-Pickaxes-1.12.2.jar                            | None                                     |
       | UCHIJAAAA | rfpr                                         | 8.1.0                 | Real-First-Person-Render-1.12.2.jar               | None                                     |
       | UCHIJAAAA | reccomplex                                   | 1.4.7                 | RecurrentComplex-1.4.7.jar                        | None                                     |
       | UCHIJAAAA | additionalstructures                         | 2.0.1                 | Rex's-Additional-Structures-1.12.x+-(v.2.1.0).jar | None                                     |
       | UCHIJAAAA | ruins                                        | 17.1                  | Ruins-1.12.2.jar                                  | None                                     |
       | UCHIJAAAA | parry                                        | 1.0                   | Shield-Parry-Mod-1.12.2.jar                       | None                                     |
       | UCHIJAAAA | vanillafix                                   | 1.0.7+72              | VanillaFix-1.0.7-72.jar                           | None                                     |
       | UCHIJAAAA | xaerominimap                                 | 1.15.9                | Xaeros_Minimap_1.15.9_Forge_1.12.jar              | None                                     |
       | UCHIJAAAA | xaeroworldmap                                | 1.3.3                 | XaerosWorldMap_1.3.3_Forge_1.12.jar               | None                                     |
       | UCHIJAAAA | zeiyocraft                                   | 0.8.4                 | ZeiyoCraft-Mod-1.12.2.jar                         | None                                     |
  Loaded coremods (and transformers): HCASM (HammerCore-1.12.2-2.0.0.3.jar)
                                        com.zeitheron.hammercore.asm.HammerCoreTransformer
                                      MovingWorldCore (MovingWorld-Mod-1.12.jar)
                                        
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.7-72.jar)
                                        
                                      IvToolkit (IvToolkit-1.3.3-1.12.jar)
                                        
                                      llibrary (LLibrary-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
                                        lumien.chunkanimator.asm.ClassTransformer
  GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
  Hammer Core Information: FluidDictionary Info: Registered 2 fluids.
                           OreDictionary Info: Registered 185 names; 232 stacks.
                           Configuration Info: IyBDb25maWd1cmF0aW9uIGZpbGUNCg0KY2xpZW50IHsNCiAgICAjIFNob3VsZCBIYW1tZXIgQ29yZSByZXBsYWNlIGVuY2hhbnRtZW50IGdsaW50IGNvbG9yIHdpdGggbW9yZSBtYXRjaGluZyBjb2xvcnMgZm9yIHNvbWUgdmFuaWxsYSBpdGVtcz8gW2RlZmF1bHQ6IHRydWVdDQogICAgQjoiQ3VzdG9tIEVuY2hhbnRtZW50IENvbG9ycyBmb3IgVmFuaWxsYSBJdGVtcyI9dHJ1ZQ0KDQogICAgIyBTaG91bGQgSGFtbWVyIENvcmUgcG9ydGZvcndhcmQgeW91ciBsb2NhbCB3b3JsZCB3aGVuIHlvdSBzaGFyZSB3aXRoIGl0IHRvIExBTj8NCiAgICAjIFRoaXMgZmVhdHVyZSBkb2Vzbid0IHdvcmsgb24gYWxsIGNsaWVudHMsIHlvdSBhcmUgZ29pbmcgdG8gZ2V0IGEgbWVzc2FnZSBpbiBjaGF0IGlmIGl0IHdhcyBzdWNjZXNzZnVsL3Vuc3VjY2Vzc2Z1bCBbZGVmYXVsdDogdHJ1ZV0NCiAgICBCOiJMQU4gVVBuUCI9dHJ1ZQ0KDQogICAgIyBSZXBsYWNlIHZhbmlsbGEgZnVybmFjZSBhbmQgYnJld2luZyBzdGFuZCBwcm9ncmVzcyBiYXJzIHRvIHVzZSBzbW9vdGggcmVuZGVyaW5nPyBbZGVmYXVsdDogdHJ1ZV0NCiAgICBCOiJTbW9vdGggVmFuaWxsYSBHdWlzIj10cnVlDQp9DQoNCg0KaXdyZW5jaCB7DQogICAgIyBXaGF0IGlzIHRoZSBjb2xvciB3aGVuIHRoZSBob3ZlcmVkIGJsb2NrIGlzIHdyZW5jaGFibGU/IChjb2xvciBlbmNvZGVkIGluIGhleCBmb3JtIHN1Y2ggYXMgUlJHR0JCKQ0KICAgIFM6R3JlZW49MjJGRjIyDQoNCiAgICAjIFdoYXQgaXMgdGhlIGNvbG9yIHdoZW4gdGhlIGhvdmVyZWQgYmxvY2sgaXMgTk9UIHdyZW5jaGFibGU/IChjb2xvciBlbmNvZGVkIGluIGhleCBmb3JtIHN1Y2ggYXMgUlJHR0JCKQ0KICAgIFM6UmVkPUZGMjIyMg0KfQ0KDQoNCiJ2YW5pbGxhIGltcHJvdmVtZW50cyIgew0KICAgICMgU2hvdWxkIEhhbW1lciBDb3JlIGZvcmNlLXNwYXduIEVuZGVyIERyYWdvbiBFZ2cgb24gRW5kZXIgRHJhZ29uIGRlYXRoPyBbZGVmYXVsdDogdHJ1ZV0NCiAgICBCOiJBbHdheXMgU3Bhd24gRHJhZ29uIEVnZyI9dHJ1ZQ0KfQ0KDQoNCg==
                           Pastebin Connection: Okay.
  Suspected Mods: MineColonies (minecolonies)
  Profiler Position: N/A (disabled)
  Player Count: 1 / 8; [EntityPlayerMP['GIVEMELOOT'/12, l='modz', x=801.81, y=63.50, z=-500.30]]
  Type: Integrated Server (map_client.txt)
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Client Crashes Since Restart: 0
  Integrated Server Crashes Since Restart: 1

**Comment by Raycoms** [comment]
Seems like an issue with the forge version you're using.

Am Sa., 26. Jan. 2019 um 20:19 Uhr schrieb -Av- <notifications@github.com>:

**Comment by qwerty1av** [comment]
After updating to recommended forge's version it finally worked!
Thanks a lot for your help!

**Comment by Raycoms** [comment]
No problem
