### ISSUE TITLE
Enhancement Request: Feathers can be composted

### ISSUE THREAD

**Issue by spacewolfcub** [ldtteam/minecolonies#3309]
### Minecolonies version
minecolonies-1.12.2-0.10.134-ALPHA

### Current behaviour
Feathers pile up forever and nothing happens with them...

### Suggested behaviour
Allowing feathers to be chosen for the compostable items.

**Comment by lunadragnstar** [comment]
You should be able to add them to the config file

**Comment by spacewolfcub** [comment]
Then could we please have them added by default? Or at least added to the official servers?

**Comment by Wissi** [comment]
I'll add them to the server config. But yeah, if it's a normal drop from Chickens it should be added as a default to the list.

**Comment by Nightenom** [comment]
Actually, I don't think I would compost that 🤔

**Comment by spacewolfcub** [comment]
[https://www.gardeningknowhow.com/composting/ingredients/composting-bird-feathers.htm](url)

> Can you compost bird feathers? You absolutely can. In fact, feathers are some of the most nitrogen rich composting materials around. 
>Bird feathers in compost break down relatively easily – they should break down totally within just a few months. The only real hazard is wind. Make sure to add your feathers on a day without wind, and cover them up with heavier material once you’ve added them to keep them from blowing everywhere. You can also soak them in water for a day beforehand both to weigh them down and jump start the decomposing process.

**Comment by Nightenom** [comment]
So do your first PR, adding an item to list is easy :D it's doable even without IDE

**Comment by spacewolfcub** [comment]
?

I guess that's a good test of how GitHub pulls/pushes. 
If I'm going to be doing that later. 

This issue was posted long before I dragged myself kicking and screaming into attempting to... to deal with the files directly.

**Comment by Raycoms** [comment]
Closed in favor of joint issue.
