### ISSUE TITLE
Miner, Lumberjack and Farmer Stuck.

### ISSUE THREAD

**Issue by Wissi** [ldtteam/minecolonies#331]
The issue remains. The Farmer, Lumberjack and Miner will NOT work at all unless "recalled" back to their huts after transition from night to day and they had not reached the Citizen hut during the night.

Fisherman will eventually work again, but not the other 3 classes.

**Comment by Raycoms** [comment]
The next morning they won't try path back to their huts?

2016-12-08 18:19 GMT-02:00 Wissi <notifications@github.com>:

**Comment by Wissi** [comment]
No, they will stay still (as if stuck) until I go to their hut and "recall" them. I tried leaving them all day long again and 80 % of the time they will stand still where they were. I was alone on Official server last night for a couple hrs so not lag either.

**Comment by Raycoms** [comment]
fixed in the newest version.
