### ISSUE TITLE
Feature Request: A block to stop miners mining in a certain spot

### ISSUE THREAD

**Issue by Talyda** [ldtteam/minecolonies#3310]
To give an idea why I thought of it in the first place - I have a giant ravine running through the centre of my colony, and thought it would be fun to create a populated vanilla village down there, around y level 20 or so, kind of as a curiosity/historic town reference type thing, with a glass floor on the top of the ravine, so as I am walking around ground level I can look down and see them.

But having the miner in the colony, he could in theory mine right through it all, and wreck it. So I thought maybe a block that I could surround the place in, so if the miner would run up against it, they would change directions to work around it.

Ideally (in my mind) it would be transparent, but I know that may make life a lot harder. It would be handy for building bases with basements as well, as well as anything really that the player wanted to protect underground (dungeons etc?)

Not being sure how the coding manages all this, I have no idea if this bit makes sense, but could it even be an existing block that usually doesn't generate underground (glass for example?) that if they run across they change directions?

**Comment by Nightenom** [comment]
The actual problem is that you place a block which occupies place. If you upgrade your miner you can switch him to lower levels than is your ravine
edit: maybe we can add a tool which can be used to create areas within player's colony which would be treated as untouchable

**Comment by Talyda** [comment]
A tool would be lovely too! As a work around at the moment, if I was to surround the area with lava, would that stop the miner going through? Like tall waterfalls of lava (lavafalls I guess that would be =P) around the outside boundaries?

**Comment by ghost** [comment]
I don't know if you're playing a specific pack or on a server, but a number of mods have protection devices.
FTB Utils includes a chunk-claiming system that normally blocks mob griefing in claimed chunks. Or you could add Not Enough Wands and tweak the configuration to only include indestructible protection wands.

**Comment by Raycoms** [comment]
Closed in favor of joint issue.
