### ISSUE TITLE
New Sandstone huts revision

### ISSUE THREAD

**Issue by GanthorPrime** [ldtteam/minecolonies#3311]
### Minecolonies version

Version: minecolonies-1.12.2-0.10.150-ALPHA-universal.jar 

### Actual behaviour

Nice to see new sandstone buildings added to the pack. Here are a few things for revision:

1- Sandstone composter hut includes 2 copies of the building at lvl 5
2- Sandstone combat academy shows an item named 'CombatAcademy' in the levels list, (1,2,3,4,5) and do not correspond with any level
3- Sandstone stonemason hut got displaced at lvl 5

**Comment by lunadragnstar** [comment]
Ok, I rescanned the stonemason (it was missing the hut block. but I don't know what you mean by 2 copies of the building at lvl 5 for the composter

**Comment by GanthorPrime** [comment]
> 
> 
> Ok, I rescanned the stonemason (it was missing the hut block. but I don't know what you mean by 2 copies of the building at lvl 5 for the composter

check it this way:  in creative, start the preview of the composter hut, fly away to see the preview from above at some distance, lets say 32 blocks,  start checking each level of the hut in the preview: At level 5, you will see the preview includes a second composter hut next to the one you  were seeing in lvl 1, 2, 3, and 4, paste and 2 composter huts will appear in the world.  In adition, note that the location it appears in the world is not the same shown in the preview.

**Comment by Raycoms** [comment]
Oh, so both huts were scanned together =D

Am Mo., 28. Jan. 2019 um 18:28 Uhr schrieb GanthorPrime <
notifications@github.com>:

**Comment by lunadragnstar** [comment]
Not on my preview

Oh, and the combat academy will show on the list of items but it is already placed so it will not request it, this is true for all huts

**Comment by GanthorPrime** [comment]
[gif](https://gifmaker.me/PlayGIFAnimation.php?folder=2019012807Nxg1q2466ffHDVzpAHOmsP&file=output_M8AOda.gif)

**Comment by lunadragnstar** [comment]
Ok, I see it now, had an override on. I will rescan

**Comment by lunadragnstar** [comment]
Rescanned and uploaded.
