### ISSUE TITLE
Blocks are missing after update

### ISSUE THREAD

**Issue by leonhearth** [ldtteam/minecolonies#3313]
The problem is when updating the mod all of the mod blocks belonging to 
the Minecolonies mod are gone , shingles and blocks , so all the houses look like swiss cheese ! 
even when trying to repair the houses the shingles ands blocks are not replaced ! 

it does not matter what building the blocks from the mod are used in there just gone , i have a 500x500 block city with around 5000 roof shingles missing ! not a fun job replacing it all.

this has happend with every mod update so is this ever going to be fixed ?
i only update the release versions

**Comment by Raycoms** [comment]
There seems to be an ID issue with the modblocks in your world, a few
people got this issue already (around 1% of th eplayers)
It seems like tools to fix the mod block ids fixes this issue.

Am Di., 29. Jan. 2019 um 13:28 Uhr schrieb leonhearth <
notifications@github.com>:

**Comment by Raycoms** [comment]
We tried to contact forge about it but they didn't send us any solution.

Am Di., 29. Jan. 2019 um 13:30 Uhr schrieb Ray Neiheiser <
ray.neiheiser@gmail.com>:
