### ISSUE TITLE
building problems after blueprints update

### ISSUE THREAD

**Issue by GanthorPrime** [ldtteam/minecolonies#3315]
### Minecolonies version

Version: minecolonies-1.12.2-0.10.152-ALPHA-universal.jar 

### Expected behavior

- Builders building scanned decorations in the previous .nbt format to be able to continue the building process.

- Migrate the old nbt files in the structurize/schematics folder to the new blueprint format. migrate / clear cached schematics if necesary. restart building / request if necesary.

### Actual behaviour

there are a bunch of possible related issues since update from 1.12.2-0.10.146-alpha to latest alpha

- builders that were building a scanned decoration before the update, start throwing NPEs

   [npe pausing builder - server log](https://drive.google.com/file/d/1TZsTvUim4PVYs5zAwoTTKTxYrcvSZPOH/view?usp=sharing)

- starting the preview of decorations scaned in the previous format crash the client (but not the server). if you are in single player your game crashes.  this is seen in the server log:

   [preview client crash - server log](https://drive.google.com/file/d/14JZUBw8jKGaTSdrGwLlJQMgwrj5Ixw1j/view?usp=sharing)

- we tried this:

1. canceled all the jobs from the town hall, fired all builders
2. restarted the server, reset the request (i.e. /mc rs reset colony: 2), rehire builders, no problems
3. stopped the server again, deleted the old nbt decorations, uploaded rescanned decorations
4. start the server again, preview of new blueprints not crashing the client, (we are making pogress)
5. order to build one of the blueprints: server crash just after the message: 'builder xxx started to build...'
6. start the server again, seems normal, connect a player, crashes again as soon as the messsage shows 

   [crash log](https://drive.google.com/file/d/1NIV9hzRHrBDse5JdJ3fYT5bKlzW58lYe/view?usp=sharing)

### Steps to reproduce the problem

1. have builders building scanned decorations in the world
2. update to latest alpha and check the server log for pausing builders
3. try to preview the old decos in SMP and single player
4. update all decos, try to build them in an existing colony

**Comment by Raycoms** [comment]
Fix incoming

Am Do., 31. Jan. 2019 um 11:12 Uhr schrieb GanthorPrime <
notifications@github.com>:
