### ISSUE TITLE
Villagers withered away in loop

### ISSUE THREAD

**Issue by MorueSalee** [ldtteam/minecolonies#3316]
### Minecolonies version

Version: 1.12.2 -  0.10.109-relea

### Expected behavior

- Villagers don't randomly take damages and being killed with the message "withered away"

### Actual behaviour

- Villagers are taking random damages without any mob / mod which could do this
- Villagers then die because of those damages with a message in the chat "withered away"
- Villagers keep dying in loop with no evidence of anything causing that

![2019-01-31_00 34 46](https://user-images.githubusercontent.com/23076071/52076224-8052bb00-258e-11e9-880f-1f6243fe00b9.png)

### Steps to reproduce the problem

1. Create a village
2. Played a while whitout any problem (2 days IG)
3. Appeared when I updated the mod to 0.10.109
5. After some time (more or less 30min) they start taking damages
4. Once started, they're dying non stop
5. Affect villagers one by one

**Comment by Raycoms** [comment]
Any additional mod?

**Comment by MorueSalee** [comment]
Yes, I'm playing on the modpack all the mod 3 remix

**Comment by Raycoms** [comment]
I checked into this and there must be a mod which threw wither potion effect potions at the villagers, else they don't get this. Might be the biome?

**Comment by MorueSalee** [comment]
No, there's nothing like this. I played 2 days in game with my village and nothing like this ever happened. I updated the modpack, and so minecolonies, and then this strange stuff appeared. Downgraded to the previous version and everything's fine.

**Comment by Raycoms** [comment]
Downgraded only minecolonies and it fixed it forever? Might've been the
update of another mod causing it. Never happened in any of our modpacks
with any minecolonies version.

Am Di., 5. Feb. 2019 um 11:00 Uhr schrieb Flobzh22 <notifications@github.com

**Comment by MorueSalee** [comment]
Maybe, I've already checked in the village if there were any block which can do this, but nothing. I need to try with the modpack updated and minecolonies downgraded only.

**Comment by Raycoms** [comment]
Might be a mob as well not only a block.

Am Di., 5. Feb. 2019 um 11:14 Uhr schrieb Flobzh22 <notifications@github.com

**Comment by MorueSalee** [comment]
Just found out what it was : this was because of Nuclearcraft natural radiation in the overworld ... Disabled it in the configs, et voila problem solved :) 

Btw this made me think about something that could be nice to your mod : a hospital, where villagers can go to restore their life, or even a illness system that can spread through the villagers, which needs to go to the hospital to get cured.

Thanks for your help !

**Comment by Raycoms** [comment]
Yes, I'm currently going through some plans of making a healer worker.
