### ISSUE TITLE
Create wall blocks [$20]

### ISSUE THREAD

**Issue by Raycoms** [ldtteam/minecolonies#332]
A block used to manage the walls.
1 wall block can be used to manage a infinite (finite only to colony radius) wall segment.
Wall block always has the walls basic texture (wood or stone depending on the upgrade)

Options are: Upgrade, repair, add segment (left, right)

**Comment by pmardle** [comment]
Interesting..

I would almost have this using the guard tower as the anchor, and you can build walls "north, south, east, west from the guard tower..

**Comment by Raycoms** [comment]
I also thought about that, but the guard tower 1-3 designs don't really
combine with walls.
And the 4-5 are pretty big for simple walls.

I honestly thought about making the central wall segment also a "guard
tower" but one that can be easily integrated into the wall and it can be a
small wall tower, or a gate or a general wall)

2016-12-13 9:19 GMT-02:00 pmardle <notifications@github.com>:
