### ISSUE TITLE
stone blacksmith lvl 3 blueprint using sawmill blueprint

### ISSUE THREAD

**Issue by GanthorPrime** [ldtteam/minecolonies#3320]
### Minecolonies version

Version: minecolonies-1.12.2-0.10.153-ALPHA-universal

### Actual behaviour

 The stone style for the blacksmith is using a blueprint for a sawmill at level 3

### Steps to reproduce the problem

1.  start the preview of a blacksmith and select the stone style
2.  navigate each level and check the changes
3.  check the hut block at lvl 3

**Comment by lunadragnstar** [comment]
Rescanned both
