### ISSUE TITLE
Builder Stalled

### ISSUE THREAD

**Issue by AdamM72** [ldtteam/minecolonies#3322]
### Minecolonies version

Version: 1.12.2-0.10.109-RELEASE

### Expected behavior

- Builder returns to Builder Hut to collect materials and returns to build site to continue working
 OR
- Builder returns to build site after sleeping / raid / rain to continue working
OR
- Builder returns to build site after Recall / Reset to continue working

### Actual behaviour
- My builder has successfully built 10 buildings but has now completely stalled. 
The message Builder Isaiah A. Harris: Started building schematics/ArfBasic/GuardTower1 appears.
He moves to his Builders Hut and simply stands there - he has collected the required resources (they are in his inventory) but he will not move to the work site.
Actions I have tried to resolve this
 - Remove resources and re deposit them in his inventory, hut inventory, hut resources required list.
 - Recall him to Builders Hut
 - Recall him to Town Hall
 - reset mc colony
 - cancel and re-queue the building Build request
- Pause and Restart builder from the Manage Workers page of the Builders Hut

### Steps to reproduce the problem
The builder has got stuck a couple of times finding the path despite the ground being open and clear, although I did place schematics tightly together (there is no free blocks between 'templates' but there is open paths crossing those templates.

**Comment by Raycoms** [comment]
Can you check the latest beta?

Am Sa., 2. Feb. 2019 um 23:03 Uhr schrieb AdamM72 <notifications@github.com

**Comment by AdamM72** [comment]
So far so good - he immediately began work, completed the build and moved on to the next task. Will monitor for a bit
