### ISSUE TITLE
Sleeping bag from another mod error 

### ISSUE THREAD

**Issue by Classical-Muse** [ldtteam/minecolonies#3323]
### Minecolonies version

Version: 1.12.2-0.10.97-BETA

### Expected behavior

I'm not sure what is broken

- 

### Actual behaviour

- I was having my builder working on the town hall and was about to go to sleep using a sleeping bag from Comforts mod. I'd been using it for a couple in game days without a problem before getting this error. Every time I would right click to use the bag a new crash report was made but my game never crashed itself. I'm not too sure what is having a problem.

[crash-2019-02-02_22.10.07-server.txt](https://github.com/ldtteam/minecolonies/files/2825170/crash-2019-02-02_22.10.07-server.txt)

### Steps to reproduce the problem

1. Place the sleeping bag from Comforts down on the ground when it is not night time
2. Right click as if trying to sleep
3. The error should appear every time the bag is right clicked

**Comment by Talyda** [comment]
Try using it from in your hand - for some reason when they are placed in a colony they don't work, but if you leave it in your hand it's fine.

**Comment by Classical-Muse** [comment]
Ok I will. Do you know if the error it creates has messed anything up for my save?

**Comment by Raycoms** [comment]
Will be fixed with the next alpha
