### ISSUE TITLE
problem mod to server

### ISSUE THREAD

**Issue by jakub96124124** [ldtteam/minecolonies#3328]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  SpongeCoremod (spongeforge-1.12.2-2768-7.1.6-RC3561.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.190.jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 2/5/19 9:03 PM
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Structurize (structurize)
Caused by: java.lang.NoClassDefFoundError: org/lwjgl/LWJGLException
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at com.structurize.compat.optifine.OptifineCompat.setupReflectedMethodReferences(OptifineCompat.java:86)
	at com.structurize.compat.optifine.OptifineCompat.intialize(OptifineCompat.java:55)
	at com.structurize.coremod.Structurize.init(Structurize.java:122)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.redirect$onPost$zza000(LoadController.java:560)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:744)
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:108)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:338)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.lwjgl.LWJGLException
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 41 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.server.MinecraftServer.handler$onCrashReport$zjm000(MinecraftServer.java:3977)

-- Sponge PhaseTracker --
Details:
	Phase Stack: [Empty stack]
Stacktrace:
	at net.minecraft.server.MinecraftServer.handler$onCrashReport$zjm000(MinecraftServer.java:3977)
	at net.minecraft.server.MinecraftServer.func_71230_b(MinecraftServer.java:889)
	at net.minecraft.server.dedicated.DedicatedServer.func_71230_b(DedicatedServer.java:371)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:558)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_201, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 671863000 bytes (640 MB) / 1733820416 bytes (1653 MB) up to 3795845120 bytes (3620 MB)
	JVM Flags: 1 total; -Xmx4072M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2810 72 mods loaded, 72 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                        | Version                  | Source                                           | Signature                                |
	|:----- |:------------------------- |:------------------------ |:------------------------------------------------ |:---------------------------------------- |
	| LCHI  | minecraft                 | 1.12.2                   | minecraft.jar                                    | None                                     |
	| LCHI  | mcp                       | 9.42                     | minecraft.jar                                    | None                                     |
	| LCHI  | FML                       | 8.0.99.99                | forge-1.12.2-14.23.5.2810-universal.jar          | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHI  | forge                     | 14.23.5.2810             | forge-1.12.2-14.23.5.2810-universal.jar          | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHI  | ivtoolkit                 | 1.3.3-1.12               | minecraft.jar                                    | None                                     |
	| LCHI  | micdoodlecore             |                          | minecraft.jar                                    | None                                     |
	| LCHI  | spongeapi                 | 7.1.0-005d9ff6           | spongeforge-1.12.2-2768-7.1.6-RC3561.jar         | None                                     |
	| LCHI  | sponge                    | 1.12.2-7.1.6-SNAPSHOT    | spongeforge-1.12.2-2768-7.1.6-RC3561.jar         | None                                     |
	| LCHI  | spongeforge               | 1.12.2-2768-7.1.6-RC3561 | spongeforge-1.12.2-2768-7.1.6-RC3561.jar         | None                                     |
	| LCHI  | infinitylib               | 1.12.2-1.12.0            | infinitylib-1.12.0.jar                           | None                                     |
	| LCHI  | agricraft                 | 2.12.0-1.12.0-a6         | AgriCraft-2.12.0-1.12.0-a6.jar                   | None                                     |
	| LCHI  | baubles                   | 1.5.2                    | Baubles-1.12-1.5.2.jar                           | None                                     |
	| LCHI  | biomesoplenty             | 7.0.1.2425               | BiomesOPlenty-1.12.2-7.0.1.2425-universal.jar    | None                                     |
	| LCHI  | buildcraftlib             | 7.99.21                  | buildcraft-all-7.99.21.jar                       | None                                     |
	| LCHI  | buildcraftcore            | 7.99.21                  | buildcraft-all-7.99.21.jar                       | None                                     |
	| LCHI  | buildcraftbuilders        | 7.99.21                  | buildcraft-all-7.99.21.jar                       | None                                     |
	| LCHI  | buildcrafttransport       | 7.99.21                  | buildcraft-all-7.99.21.jar                       | None                                     |
	| LCHI  | buildcraftsilicon         | 7.99.21                  | buildcraft-all-7.99.21.jar                       | None                                     |
	| LCHI  | theoneprobe               | 1.4.28                   | theoneprobe-1.12-1.4.28.jar                      | None                                     |
	| LCHI  | buildcraftcompat          | 7.99.21                  | buildcraft-all-7.99.21.jar                       | None                                     |
	| LCHI  | buildcraftenergy          | 7.99.21                  | buildcraft-all-7.99.21.jar                       | None                                     |
	| LCHI  | buildcraftfactory         | 7.99.21                  | buildcraft-all-7.99.21.jar                       | None                                     |
	| LCHI  | buildcraftrobotics        | 7.99.21                  | buildcraft-all-7.99.21.jar                       | None                                     |
	| LCHI  | catclearlag               | 0.9.0                    | CatClearLag-0.9.0.jar                            | None                                     |
	| LCHI  | chameleon                 | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                         | None                                     |
	| LCHI  | codechickenlib            | 3.2.2.353                | CodeChickenLib-1.12.2-3.2.2.353-universal.jar    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHI  | console-lock              | 1.1                      | console-lock-1.1.jar                             | None                                     |
	| LCHI  | flexiblelogin             | 0.17.4                   | flexiblelogin-0.17.4.jar                         | None                                     |
	| LCHI  | forgemultipartcbe         | 2.6.1.81                 | ForgeMultipart-1.12.2-2.6.1.81-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHI  | microblockcbe             | 2.6.1.81                 | ForgeMultipart-1.12.2-2.6.1.81-universal.jar     | None                                     |
	| LCHI  | minecraftmultipartcbe     | 2.6.1.81                 | ForgeMultipart-1.12.2-2.6.1.81-universal.jar     | None                                     |
	| LCHI  | ic2                       | 2.8.110-ex112            | industrialcraft-2-2.8.110-ex112.jar              | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCHI  | mantle                    | 1.12-1.3.3.39            | Mantle-1.12-1.3.3.39.jar                         | None                                     |
	| LCHI  | jei                       | 4.14.4.264               | jei_1.12.2-4.14.4.264.jar                        | None                                     |
	| LCHI  | tconstruct                | 1.12.2-2.12.0.115        | TConstruct-1.12.2-2.12.0.115.jar                 | None                                     |
	| LCHI  | galacticraftcore          | 4.0.2.190                | GalacticraftCore-1.12.2-4.0.2.190.jar            | None                                     |
	| LCHI  | galacticraftplanets       | 4.0.2.190                | Galacticraft-Planets-1.12.2-4.0.2.190.jar        | None                                     |
	| LCHI  | improvedbackpacks         | 1.12.2-1.4.0.0           | ImprovedBackpacks-1.12.2-1.4.0.0.jar             | None                                     |
	| LCHI  | keepinventorysponge       | 1.1                      | KeepInventory-Sponge.jar                         | None                                     |
	| LCHI  | lblades                   | 1.0.3b                   | LegendaryWeapons-V1.0.3.jar                      | None                                     |
	| LCHI  | lex                       | 1.0.8                    | LibEx-1.12.2-1.0.8.jar                           | None                                     |
	| LCHI  | luckperms                 | 4.3.75                   | LuckPerms-Sponge-4.3.75.jar                      | None                                     |
	| LCHI  | mekanism                  | 1.12.2-9.4.13.349        | Mekanism-1.12.2-9.4.13.349.jar                   | None                                     |
	| LCHI  | mmcreboot                 | 2.3.1                    | MMCReboot-2.3.1-API-7.jar                        | None                                     |
	| LCHI  | mrtjpcore                 | 2.1.3.35                 | MrTJPCore-1.12.2-2.1.3.35-universal.jar          | None                                     |
	| LCHI  | nucleus                   | 1.8.2-S7.1               | Nucleus-1.8.2-S7.1-MC1.12.2-plugin.jar           | None                                     |
	| LCHI  | placeholderapi            | 4.4                      | PlaceholderAPI-4.4.jar                           | None                                     |
	| LCHI  | projectred-core           | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-Base.jar              | None                                     |
	| LCHI  | projectred-compat         | 1.0                      | ProjectRed-1.12.2-4.9.1.92-compat.jar            | None                                     |
	| LCHI  | projectred-integration    | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-integration.jar       | None                                     |
	| LCHI  | projectred-transmission   | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-integration.jar       | None                                     |
	| LCHI  | projectred-fabrication    | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-fabrication.jar       | None                                     |
	| LCHI  | projectred-illumination   | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-lighting.jar          | None                                     |
	| LCHI  | projectred-expansion      | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-mechanical.jar        | None                                     |
	| LCHI  | projectred-relocation     | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-mechanical.jar        | None                                     |
	| LCHI  | projectred-transportation | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-mechanical.jar        | None                                     |
	| LCHI  | projectred-exploration    | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-world.jar             | None                                     |
	| LCHI  | railcraft                 | 12.0.0-beta-4            | railcraft-12.0.0-beta-4.jar                      | a0c255ac501b2749537d5824bb0f0588bf0320fa |
	| LCHI  | reborncore                | 3.13.2.411               | RebornCore-1.12.2-3.13.2.411-universal.jar       | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| LCHI  | reccomplex                | 1.4.7                    | RecurrentComplex-1.4.7.jar                       | None                                     |
	| LCHI  | scenter                   | 1.12-3.11.0              | scenter-1.12.2-3.12.0.jar                        | None                                     |
	| LCHI  | serverlistplus            | 3.4.7                    | ServerListPlus-3.4.7-Universal.jar               | None                                     |
	| LCHI  | spartanshields            | 1.4.1                    | SpartanShields-1.12.2-1.4.1.jar                  | None                                     |
	| LCHI  | storagedrawers            | 1.12-5.3.5               | StorageDrawers-1.12.2-5.3.8.jar                  | None                                     |
	| LCHI  | tabmanager                | 2.1.3-S7.0-MC1.12.2      | TabManager-2.1.3-S7.0-MC1.12.2.jar               | None                                     |
	| LCHI  | techreborn                | 2.20.5.909               | TechReborn-1.12.2-2.20.5.909-universal.jar       | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| LCHI  | tmotd                     | 1.0                      | TitleMOTD.-.1.0.jar                              | None                                     |
	| LCHI  | totaleconomy              | 1.8.1                    | TotalEconomy-1.8.1.jar                           | None                                     |
	| LCHI  | worldedit                 | 6.1.9-SNAPSHOT           | worldedit-sponge-6.1.9-SNAPSHOT-dist.jar         | None                                     |
	| LCHE  | structurize               | 1.12.2-0.10.45-ALPHA     | structurize-1.12.2-0.10.45-ALPHA.jar             | None                                     |
	| LCH   | minecolonies              | 1.12.2-0.10.157-ALPHA    | minecolonies-1.12.2-0.10.157-ALPHA-universal.jar | None                                     |
	| LCH   | techreborn_compat         | 1.0.0                    | TechReborn-ModCompatibility-1.12.2-1.1.0.15.jar  | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |

	Loaded coremods (and transformers): 
SpongeCoremod (spongeforge-1.12.2-2768-7.1.6-RC3561.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.190.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- theoneprobeIntegration (Enabled/Not Forced)

	RebornCore: 
		Plugin Engine: 1
		RebornCore Version: 3.13.2.411
		Runtime Debofucsation 1
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
	Type: Dedicated Server (map_server.txt)

**Comment by marchermans** [comment]
Remove optifine from the server side mods list!
