### ISSUE TITLE
Villagers disappearing

### ISSUE THREAD

**Issue by YamiKira** [ldtteam/minecolonies#3329]
### Minecolonies version

Version: 

### Expected behavior

- 
Villagers disappeared
### Actual behaviour

- 
While playing, I got bluescreen, restarted computer, opened minecraft and then villagers disappeared. Every building block item was unable to open. Nothing was happening when  press on them. Because of that, I had to rebuild everything, from all levels of buildings. I dont know if its really bug of mod or its just bluescreen and minecraft problem.

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit

**Comment by Raycoms** [comment]
./mc colony loadbackup colony: 1

Am Mi., 6. Feb. 2019 um 18:16 Uhr schrieb YamiKira <notifications@github.com
