### ISSUE TITLE
Suggestion: add button to run /mc rs reset  in TH or each workers hut or clipboard/scroll

### ISSUE THREAD

**Issue by CharCharthemonkey** [ldtteam/minecolonies#3330]
### Minecolonies version

Version: 

### Expected behavior

- 

### Actual behaviour

- 

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit

pretty please consider adding something to allow players to mass reset colonists to fix them to make them work again pretty please cause having to track down each colonist to reset them getsreally annoying after awhile please and thank you <3

**Comment by marchermans** [comment]
No. Rs reset seems to be a fix all do all problem. Al lot of people run this command in the hope to get things fixed. Even though the problem is somewhere entirely different.

**Comment by Raycoms** [comment]
When we find out what causes this
