### ISSUE TITLE
Village happiness

### ISSUE THREAD

**Issue by Wetz1990** [ldtteam/minecolonies#3334]
### Minecolonies version

Version: 1.12.2-0.10.159-Alpha

### Expected behavior
Villager happines level hits 10, and everyone is all excited and gets "born" wiht good stats

### Actual behaviour

Villager level goes from 9.9 till 10. But, instead of setting the villager happiness level to 10 inside the townhall it gets set to 1.
This results in all the villagers getting born with 1-1-1 stats.
This explains how it is possible to go from 9.9 happiness level to 1 over one night not chanching anything.

I manually checked all my villagers, and they are all green in they hapiness messure.

### Steps to reproduce the problem

1. build village
2. get happiness to 10
3. it gets set to 1 in the town hall
4.

**Comment by marchermans** [comment]
@Raycoms Some rounding derpage?

**Comment by someaddons** [comment]
oh a code derp, found it!        
if (happinessTotal > HappinessData.MAX_HAPPINESS) 
        { 
            happinessTotal = HappinessData.MIN_HAPPINESS; 
        }

**Comment by Raycoms** [comment]
Wow what a derp xD

**Comment by marchermans** [comment]
:laughing: :rofl:

**Comment by Wetz1990** [comment]
yay! I de-bugged code, without reading the code! 💃

**Comment by Wetz1990** [comment]
Did this get fixed in the latest version? 161-alpha

**Comment by Raycoms** [comment]
no, not yet

Am Fr., 8. Feb. 2019 um 15:46 Uhr schrieb Wetz1990 <notifications@github.com
