### ISSUE TITLE
Issue with the Treehouse Corner Walkway

### ISSUE THREAD

**Issue by Annon9007723** [ldtteam/minecolonies#3338]
### Minecolonies version

Version: 0.10.162-ALPHA

### Expected behavior
The corner walk for the tree is missing and is...not correct.

The corner walk is a simple L shape that...wait is this really needed? 

### Actual behaviour
Refer to included image to see what the issue is.

### Steps to reproduce the problem
1. Take out builders wand.
2. Right click. Head to decorations, dark oak, and click on the corner walk.
3. Experience rage as you are not able to build your outpost properly.
![2019-02-08_14 19 53](https://user-images.githubusercontent.com/26782997/52506981-798b0000-2bad-11e9-9194-587c3f4c1c9f.png)

**Comment by lunadragnstar** [comment]
I'll check this

**Comment by lunadragnstar** [comment]
Fixed
