### ISSUE TITLE
Alpha.162 - size of Fisher Hat

### ISSUE THREAD

**Issue by Apollon-Theos** [ldtteam/minecolonies#3344]
### Minecolonies version

Version: 
0.10.162-ALPHA
### Expected behavior

Fisher Hut have hidden big field with unknown function, that bigger what show by planing build.
"Sandstone" style.
- 

Builder start demolish near buildings, that "interfere" with fisher hut

### Actual behaviour

- 

### Steps to reproduce the problem

1. 
build fisher hut near (fence to fence) other building, I try 3(three) time with different places.
2. 
3. 
4. ... Profit

**Comment by Raycoms** [comment]
Which fisher style?

**Comment by Apollon-Theos** [comment]
Sorry, "Sandstone"

**Comment by Apollon-Theos** [comment]
https://www.4shared.com/s/fbosSwqoEee
for show situation

**Comment by Raycoms** [comment]
Ahh, this is the area of the highe rlevels of the hut, upgrade it to higher levels and you're going to see why.

**Comment by Apollon-Theos** [comment]
![minecolonies-2019-02-10_14 17 46](https://user-images.githubusercontent.com/46534073/52534402-18506180-2d52-11e9-9b52-872ef50167f2.png)

**Comment by Raycoms** [comment]
Upgrade the building to see

**Comment by Apollon-Theos** [comment]
maybe correct position of construction tape for draw max size area?
