### ISSUE TITLE
Alpha.162 - Builder demolish building self

### ISSUE THREAD

**Issue by Apollon-Theos** [ldtteam/minecolonies#3345]
The builder should detect when he interferes with other building structures and abort the building and message the player that two huts are too close to eachother.

Nevertheless, we gotta see that this can only happen "on destroy" of a block. Since huts might be integrated into other huts.

**Comment by Raycoms** [comment]
Interesting idea. I will change the desc

**Comment by Raycoms** [comment]
Closed in favor of joint issue.
