### ISSUE TITLE
Alpha.162 - Unexpected items for build

### ISSUE THREAD

**Issue by Apollon-Theos** [ldtteam/minecolonies#3346]
### Minecolonies version

Version: 
0.10.162-ALPHA
### Expected behavior

- 

### Actual behaviour

Try build restorant in "Sandstone" style, but builder want Jungle Leaves. No any "Leaves" in list of needed items for build. 
- 

### Steps to reproduce the problem

1. 
Biuld restorant in "Sandstone" style
2. 
3. 
4. ... Profit

**Comment by Raycoms** [comment]
That's also on purpose. Leaves are "free" but the builder needs one of th ekind to build it.
