### ISSUE TITLE
Alpha.162 - not show entrance by planning building

### ISSUE THREAD

**Issue by Apollon-Theos** [ldtteam/minecolonies#3347]
### Minecolonies version

Version: 
0.10.162-ALPHA
### Expected behavior

Every building have entrance, but by place "table" this is unknown. "Table" after palcing, and before start building, cannot rotate.
- 
Street, road, avenue cannot be planning, because building not show entrance in plannins stage.
### Actual behaviour

- 

### Steps to reproduce the problem

1. 
place any "table" and seek side with entrace
2. 
3. 
4. ... Profit

**Comment by Raycoms** [comment]
The entrance shows in the rendering, so you know where the entrance is and can then plan it.
Just not when it is placed already, but you might just render over it to see the doors. You can even plan up to level 5

**Comment by Apollon-Theos** [comment]
I look "render" only by place caravan, other building not show render.

**Comment by Apollon-Theos** [comment]
![2019-02-10_16 42 24](https://user-images.githubusercontent.com/46534073/52534490-35d1fb00-2d53-11e9-8fc3-d43224ac1de2.png)
![2019-02-10_16 42 33](https://user-images.githubusercontent.com/46534073/52534492-379bbe80-2d53-11e9-9629-b57f43b888e4.png)

**Comment by Raycoms** [comment]
Right click with buildtool

**Comment by Raycoms** [comment]
Right click the build tool

**Comment by Apollon-Theos** [comment]
HA-HA-HA !!! I update to Alpha.163 and do right click, as you tell (on barraks)
![2019-02-10_16 49 42](https://user-images.githubusercontent.com/46534073/52534556-243d2300-2d54-11e9-8194-dd6453e1dcb7.png)

**Comment by Apollon-Theos** [comment]
show "Caravan" building :))))))))))))))

**Comment by Raycoms** [comment]
No, you take the block in the inventory and then right click the tool on
the floor

**Comment by Apollon-Theos** [comment]
... and switch two switches in right type of building and right style ... 
very complex, IMHO, but you is a author

maybe after place "table", in building menu add "holography building" ?

**Comment by Apollon-Theos** [comment]
now query is finished
