### ISSUE TITLE
Alpha.162 - Builder cannot usr resiurces stored in "table" inventory

### ISSUE THREAD

**Issue by Apollon-Theos** [ldtteam/minecolonies#3348]
### Minecolonies version

Version: 
-0.10.162-ALPHA
### Expected behavior

- 
Store resources in "table" inventory, better for tracking, instead "in Builder Hut after start building"

### Actual behaviour

If I store resources for build in "table" inventory, builder not use it and wait resources in "Builder Hut" or in his inventory
- 

### Steps to reproduce the problem

1. 
plase any resources to "table" inventory
2. 
3. 
4. ... Profit

**Comment by Raycoms** [comment]
Yeah, depending on the inventory the builder can't use it, you gotta check in the GUI in his hut if he accepted it.

**Comment by Apollon-Theos** [comment]
Maybe allow access to building inventiry, because his inventory very small?
