### ISSUE TITLE
Alpha.162 - Woman NPC in turn ;)

### ISSUE THREAD

**Issue by Apollon-Theos** [ldtteam/minecolonies#3349]
### Minecolonies version

Version: 
-0.10.162-ALPHA
### Expected behavior

- 

### Actual behaviour

- 
Woman NPC with long hair in turn - first turn body with all hair, next time turn head - head rotate inside hair !!!

;)

Woman NPC with pigtail - animation good.

### Steps to reproduce the problem

1. 
look at woman npc in game some time

2. 
3. 
4. ... Profit

**Comment by Raycoms** [comment]
Which female npc? Do you have a screenshot?

**Comment by Apollon-Theos** [comment]
Please:
![2019-02-10_16 29 33](https://user-images.githubusercontent.com/46534073/52534364-c4457d00-2d51-11e9-8fa5-3fca4dd6acf8.png)
![2019-02-10_16 29 39](https://user-images.githubusercontent.com/46534073/52534365-c6a7d700-2d51-11e9-8ec3-fa599b072f50.png)
![2019-02-10_16 29 44](https://user-images.githubusercontent.com/46534073/52534366-c8719a80-2d51-11e9-8039-0bf60891c569.png)
![2019-02-10_16 29 58](https://user-images.githubusercontent.com/46534073/52534367-ca3b5e00-2d51-11e9-8055-e686c6a2d6cd.png)
![2019-02-10_16 30 02](https://user-images.githubusercontent.com/46534073/52534368-cc052180-2d51-11e9-85bf-903a4cce8217.png)
![2019-02-10_16 30 24](https://user-images.githubusercontent.com/46534073/52534369-ce677b80-2d51-11e9-9b84-56a2d98ca120.png)

**Comment by MineShadow7** [comment]
@Raycoms Actually same happens with other NPCs like with male skin for fisherman (his hat)

**Comment by Apollon-Theos** [comment]
Fisherman Hut and Fisher Man is failed. :) Peoples without fish are starving :)
In MCA (Minecraft Comes Alive) use similar models, but lower part of pigtail is painted on the skin.

**Comment by Wissi** [comment]
Update to the latest ALPHA and report back if issue still persist please.
And join us on [Discrod ](https://discord.gg/uCUH8dM)for questions, comments and faster reply.
