### ISSUE TITLE
Crashing on 1.11 Alpha

### ISSUE THREAD

**Issue by spoopyghostramses** [ldtteam/minecolonies#335]
### Minecolonies version

Version 1.11-0.6.1977 Alpha

### Expected behavior

- To load into the game.

### Actual behaviour

- Crashing to log.

### Steps to reproduce the problem

1. Place mod in mods folder (with or without other mods present)
2. Open game
3. Crash
4. Profit

[crash-2016-12-10_15.13.45-client.txt](https://github.com/Minecolonies/minecolonies/files/644027/crash-2016-12-10_15.13.45-client.txt)
[crash-2016-12-10_15.10.45-client.txt](https://github.com/Minecolonies/minecolonies/files/644026/crash-2016-12-10_15.10.45-client.txt)

**Comment by Raycoms** [comment]
You have to take the recommended forge version or it won't work.

2016-12-10 18:17 GMT-02:00 spoopyghostramses <notifications@github.com>:

**Comment by spoopyghostramses** [comment]
Recommended crashes as well, with or without mods present.

[crash-2016-12-10_15.42.00-client.txt](https://github.com/Minecolonies/minecolonies/files/644045/crash-2016-12-10_15.42.00-client.txt)
[crash-2016-12-10_15.43.27-client.txt](https://github.com/Minecolonies/minecolonies/files/644046/crash-2016-12-10_15.43.27-client.txt)

**Comment by Raycoms** [comment]
can you please try with: Forge version 13.19.1.2188

2016-12-10 18:43 GMT-02:00 spoopyghostramses <notifications@github.com>:

**Comment by Cntrldfusion** [comment]
I get the same crash as reported by others on both server and client on Forge 2188.  I have other mods present but they were all working fine.  It only crashes when I add Minecolonies.

[crash-2016-12-10_15.46.57-server.txt](https://github.com/Minecolonies/minecolonies/files/644049/crash-2016-12-10_15.46.57-server.txt)

**Comment by spoopyghostramses** [comment]
Forge version 13.19.1.2188 is the recommended correct? That is the version I tried in my previous comment.

**Comment by Raycoms** [comment]
That's strange I didn't get these errors in the development environment. I
will investigate and return as soon as I have a solution.

2016-12-10 19:01 GMT-02:00 spoopyghostramses <notifications@github.com>:

**Comment by spoopyghostramses** [comment]
Thanks!

**Comment by Raycoms** [comment]
Uploaded a new version, could you test if the problem persists?

2016-12-10 19:14 GMT-02:00 spoopyghostramses <notifications@github.com>:

**Comment by spoopyghostramses** [comment]
Fixed for me in version 1.11-0.6.1994.

Thanks!
