### ISSUE TITLE
Snow collects on shingle slabs

### ISSUE THREAD

**Issue by cinnamennen** [ldtteam/minecolonies#3353]
### Minecolonies version

Version: 1.12.2-0.10.68

### Expected behavior
- Snow doesn't collect on top of shingle slabs

### Actual behaviour

- Snow collects on shingle slabs

### Steps to reproduce the problem

1. Place shingle slabs in snowy biome
2. let it rain/snow

**Comment by Raycoms** [comment]
Fixed on structurize side
