### ISSUE TITLE
Alpha.164 - Fisher cannot fish in the river

### ISSUE THREAD

**Issue by Apollon-Theos** [ldtteam/minecolonies#3354]
### Minecolonies version

Version: 
0.10.164-ALPHA
### Expected behavior

Fisherman's Hut build on rever coast
- 

### Actual behaviour

But fisherman not fish, walk over coast and turn head, look around
- 

### Steps to reproduce the problem

This situation (I stay at fisherman's roof)
![2019-02-10_20 37 22](https://user-images.githubusercontent.com/46534073/52537158-5c545e00-2d74-11e9-906e-1429cc31bf78.png)
In fly:
![2019-02-10_20 43 35](https://user-images.githubusercontent.com/46534073/52537179-9a518200-2d74-11e9-9d9b-7c110c902b3c.png)

1. 
2. 
3. 
4. ... Profit

**Comment by Raycoms** [comment]
her hut must be on the same y level as the water

Am So., 10. Feb. 2019 um 15:44 Uhr schrieb Apollon Z Theos <
notifications@github.com>:

**Comment by Apollon-Theos** [comment]
highly capricious fisherwoman :)
I go dig 9x9 water swimming pool (and fishing)

**Comment by Apollon-Theos** [comment]
coast of water only as in Wiki? Cobbler with grass? Or can be stone?

**Comment by Raycoms** [comment]
coast doesn't work, what is important is that the hut block is only 1 block
above water height.

Am So., 10. Feb. 2019 um 16:15 Uhr schrieb Apollon Z Theos <
notifications@github.com>:

**Comment by Apollon-Theos** [comment]
Where is my fail ?
River one block below hut, pool in same level:
![2019-02-10_21 23 51](https://user-images.githubusercontent.com/46534073/52537668-5a8d9900-2d7a-11e9-9d5c-63a1ae06e51c.png)

**Comment by Apollon-Theos** [comment]
Other look:
![2019-02-10_21 26 35](https://user-images.githubusercontent.com/46534073/52537711-945e9f80-2d7a-11e9-8a67-ba684246f654.png)

**Comment by Raycoms** [comment]
1 too high

Am So., 10. Feb. 2019 um 16:27 Uhr schrieb Apollon Z Theos <
notifications@github.com>:

**Comment by Apollon-Theos** [comment]
Warum? Wie viele Blöcke können?
I don't understand this moment
maybe destroy Hut and build at one block lower?

**Comment by Raycoms** [comment]
yes, build one lower

Am So., 10. Feb. 2019 um 16:49 Uhr schrieb Apollon Z Theos <
notifications@github.com>:

**Comment by Apollon-Theos** [comment]
tomorrow ....
