### ISSUE TITLE
Building upgrade not working

### ISSUE THREAD

**Issue by Kazulixa** [ldtteam/minecolonies#3355]
### System Details
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 2461679992 bytes (2347 MB) / 7062683648 bytes (6735 MB) up to 9306112000 bytes (8875 MB)
  JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx9984m -Xms256m -XX:PermSize=256m
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2768 216 mods loaded, 215 mods active

### Expected behavior

-  I want to upgrade my Cook 4 to Cook 5 with a builder (5). After creating the build request for upgrade, the worker have to build (requesting materials a.s.o.)

### Actual behaviour

-  after clicking on "Upgrade Building" on Cook 4 (upgrading to 5) the builder next to it began to build but somehow quit at a point. He is not requesting any materials and in the builders hut (5) there are resources listed but no specific building they are for. There's only "Required Resources –". After canceling the upgrade for the Cook 5, this list does not disappear. When re-upgrade the cook, only a new buildrequest is created, but nobody is beginning to build. The builder is tier 5, not hungry, not far away and there are no circumstances for him not to work. 

### Steps to reproduce the problem

1. make a t5 builder and a t4 cook
2.  upgade the cook, so the builder start working
3.  builder is standing around. does not request any resources, the build request for the cook 5 is not named in the builders hut list
4. ... Profit

heres the bug report minecraft gave me to report 
[minecolonies_bug.txt](https://github.com/ldtteam/minecolonies/files/2849391/minecolonies_bug.txt)

**Comment by Nightenom** [comment]
minecolonies-1.12.2-0.10.7-RELEASE-universal.jar => can you try the newest alpha, please?

**Comment by Raycoms** [comment]
Should be fixed
