### ISSUE TITLE
Mod dependent block in structure, new guard tower. 

### ISSUE THREAD

**Issue by Azragor** [ldtteam/minecolonies#336]
### Minecolonies version

version 0.6.1948

### Expected behavior

- No texture for stage 3 guard tower. 

The corner wall (stonebrick wall) the block is added by the Quark mod.

Just to let you know.

**Comment by Raycoms** [comment]
thanks for the work. We'll work on fixing this =)

**Comment by SyberSmoke** [comment]
I have corrected the design and Raycoms has them.

Please explain "no texture" as the third stage is all minecraft generic parts.

**Comment by Raycoms** [comment]
Will update them these days.

2016-12-11 21:01 GMT-02:00 SyberSmoke <notifications@github.com>:
