### ISSUE TITLE
Construction Tape Suggestion

### ISSUE THREAD

**Issue by lunadragnstar** [ldtteam/minecolonies#3361]
Can we make the construction tape fall if nothing is under it. Construction tape ends up in trees and things and doesn't always disappear when the build is done, but if we could make the tape drop when there isn't anything under it, even if it stays, we can clean it up easier.

**Comment by Asherslab** [comment]
this is possible, but not without the block becoming alot more complex. we could make it like sand, kind of

**Comment by lunadragnstar** [comment]
That's all I was thinking

**Comment by Raycoms** [comment]
@Asherslab we can make it extend BlockFalling, that's easy

**Comment by spacewolfcub** [comment]
I see your label there, Ray...
