### ISSUE TITLE
LAN Multiplayer bug

### ISSUE THREAD

**Issue by Jockster99** [ldtteam/minecolonies#3364]
### Minecolonies version 4.8.4 release

Version: 1.12.2

### Expected behavior

Town Hall successfully placed

My friend and I are trying to play a LAN world together with seperate colonies, but it won't let us place the second town hall, we have travelled quite a ways from each other to see if that would help but it still only allowed one town hall to be placed

### Steps to reproduce the problem

1. Start a LAN world
2. Place the first town hall
3. Get someone else to join and fly out of your colony
4. Have them try to place their town hall
5. If it is like ours it won't work

[Minecolonies multiplayer bug.txt](https://github.com/ldtteam/minecolonies/files/2853497/Minecolonies.multiplayer.bug.txt)
[Minecolonies multiplayer bug.txt](https://github.com/ldtteam/minecolonies/files/2853499/Minecolonies.multiplayer.bug.txt)
[Minecolonies multiplayer bug.docx](https://github.com/ldtteam/minecolonies/files/2853505/Minecolonies.multiplayer.bug.docx)

**Comment by Raycoms** [comment]
shoudl be fixed

**Comment by Jockster99** [comment]
> shoudl be fixed

I tested it and unfortunately it is having the same problem, I don't know why, or whether I'm doing something wrong, we are running it through twitch, is that a problem?

**Comment by someaddons** [comment]
did you update to the latest alpha?

**Comment by Jockster99** [comment]
Yeah, both parties did

**Comment by Raycoms** [comment]
I just tried it locally and it worked for me...

Am Do., 21. Feb. 2019 um 07:05 Uhr schrieb Jockster99 <
notifications@github.com>:

**Comment by Raycoms** [comment]
Are you playing on a cracked client?

Am Do., 21. Feb. 2019 um 10:20 Uhr schrieb Ray Neiheiser <
ray.neiheiser@gmail.com>:

**Comment by Jockster99** [comment]
Nah, I'm just playing it through twitch, is there a better version to download it and play through?

**Comment by Raycoms** [comment]
The newest alpha should have this working of 1.12

**Comment by Jockster99** [comment]
Okay , thankyou, is that just the standalone mod, or is that for twitch aswell?

**Comment by Raycoms** [comment]
Should be able to get it via twitch as well

**Comment by Jockster99** [comment]
Awesome, thanks for all your help
