### ISSUE TITLE
Colony stuck at 3/3

### ISSUE THREAD

**Issue by AbelBloodstone** [ldtteam/minecolonies#3367]
### Minecolonies version

Version:  0.10.109-RELEASE

### Expected behavior

- Placing 6 citizens huts and having the cap increase

### Actual behaviour

- after building 4 alt wooden huts and 1 lvl 1 wooden hut and 1 lvl 2 wooden hut the cap has decreased to 3/3 after a couple deaths

### Steps to reproduce the problem

1. killed 2 unproductive citizen
2. waiting for new citizen to spawn
3. citizen cap instead decreased
4. creating more huts does not increase cap anymore

**Comment by Wissi** [comment]
This issue has been addressed and fixed already.
Please update your minecolonies version to the latest [ALPHA](https://minecraft.curseforge.com/projects/minecolonies/files), that version is extremely old.
Newest versions have new workers and tons of fixes.
also you can join our [Discrod ](https://discord.gg/uCUH8dM) for more information and faster response.
