### ISSUE TITLE
Alpha.170 - Strange query from Guard

### ISSUE THREAD

**Issue by Apollon-Theos** [ldtteam/minecolonies#3368]
### Minecolonies version

Version: 
-0.10.170-ALPHA
### Expected behavior

- 

### Actual behaviour

Guard in BarracksTower not accept IronSword, but in list of request exist Gold Sword. Also not accept sword from other meals, from thrid party mod, example Bronze or Silver.

But guard accept armor from wide list of metals, include bronze, tin, silver and etc.
![2019-02-12_22 44 05](https://user-images.githubusercontent.com/46534073/52663574-00c2d580-2f18-11e9-8dff-7a4a9d27b1c6.png)
![2019-02-12_22 44 16](https://user-images.githubusercontent.com/46534073/52663584-07514d00-2f18-11e9-8ca7-5250b5e5ca3d.png)
![2019-02-12_22 44 29](https://user-images.githubusercontent.com/46534073/52663605-0e785b00-2f18-11e9-97dd-4915d6e3077b.png)

- 

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit

**Comment by Wissi** [comment]
That answer is in WIKI. Please do NOT post questions related to gameplay.
Read the [WIKI ](https://wiki.minecolonies.com/source/systems/happiness)first.
Else posts will be removed.
