### ISSUE TITLE
Alpha.170 - Guard not accept ENCHANTED armor

### ISSUE THREAD

**Issue by Apollon-Theos** [ldtteam/minecolonies#3369]
### Minecolonies version

Version: 
-0.10.170-ALPHA
### Expected behavior

- 

### Actual behaviour

Gold body armor with enchantment (example: Projective Protection IV) not accept by guard as possible for wear.
- 

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit

**Comment by someaddons** [comment]
each enchant level counts as additional armor level, so Iron armor with a level 1 enchant would require the guard to be able to wear diamond armor. They'll just need a higher building/experience level to wear them.
