### ISSUE TITLE
Alpha.170 - Geard can select (pull, stole) armor from player.

### ISSUE THREAD

**Issue by Apollon-Theos** [ldtteam/minecolonies#3371]
### Minecolonies version

Version: 

### Expected behavior

Only from inventory, not weared.
- 

### Actual behaviour

Stole non enchanted JetPack (from "Simple Jetpacks 2" mod) and cannot wear.
- 

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit

**Comment by Wissi** [comment]
Again. Answer is in [WIKI](https://wiki.minecolonies.com/source/systems/happiness).
Read WIKI first.
And visit [Discrod ](https://discord.gg/uCUH8dM)for gameplay questions. This is for Bugs/fixes support only.

**Comment by Apollon-Theos** [comment]
Happiness? Guard is a thief, he stole my jetpack!! I found it in his inventiry. 
Citizen must take items only from player's inventory, not from player wear slots.

**Comment by Wissi** [comment]
What Version of mod did this happen on.
We have never ever had a citizen take any block from a player's inventory, or any chest/storage other than the ones in the schematics.
They are not coded to work that way. 
And join us on [Discrod ](https://discord.gg/uCUH8dM)for questions, comments and faster reply.

**Comment by spacewolfcub** [comment]
When you click the "Fulfill" button, the first item found in your player data that meets the criteria will be grabbed. 

Your player data lists what you are wearing first, so it is found first. 

If you want the NPC to take a _specific_ item and not another: put it in their hut, and cancel their request... or put it in their personal inventory and cancel their request. 

The next time the Request System prods the NPC to calculate if it needs anything, the NPC will find the items it wanted and go back to work.

**Comment by Raycoms** [comment]
We got an issue for that
