### ISSUE TITLE
Alpha.170 - Strange design for BarracksTower

### ISSUE THREAD

**Issue by Apollon-Theos** [ldtteam/minecolonies#3372]
### Minecolonies version

Version: 
-0.10.170-ALPHA
### Expected behavior

- 

### Actual behaviour

Where is 4th column? I place two blocks and start "Repair Building", builder remove placed blocks.
Why 3 legs design?
![2019-02-12_23 17 46](https://user-images.githubusercontent.com/46534073/52665487-c0b22180-2f1c-11e9-80f0-de332b2bd89f.png)

- 

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit

**Comment by Wissi** [comment]
Thank you for reporting the issue. 
We will check the schematics to see if this is a bug or not.
Please visit our [Discrod ](https://discord.gg/uCUH8dM)for more immediate response to Schematic issues (if they exist).

**Comment by lunadragnstar** [comment]
This was an issue, it has been fixed and will be in a future release.
