### ISSUE TITLE
Alpha.170 - Constuction tape not removed after "Repair Building"

### ISSUE THREAD

**Issue by Apollon-Theos** [ldtteam/minecolonies#3373]
### Minecolonies version

Version: 

### Expected behavior

Garbage must be recycled :)
- 

### Actual behaviour

![2019-02-12_23 21 35](https://user-images.githubusercontent.com/46534073/52665635-1be41400-2f1d-11e9-9ff6-8a2f341ac8b7.png)

- 

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit

**Comment by Wissi** [comment]
Thank you. 
This is a well know issue and is being currently worked on.
Please visit our [Discrod ](https://discord.gg/uCUH8dM)for more immediate response to Schematic issues (if they exist).
