### ISSUE TITLE
Alpha.170 - Numbering buildings ?

### ISSUE THREAD

**Issue by Apollon-Theos** [ldtteam/minecolonies#3374]
### Minecolonies version

Version: 
-0.10.170-ALPHA
### Expected behavior

Internal number of building same kind ?
- 

### Actual behaviour

- 
![2019-02-13_00 09 33](https://user-images.githubusercontent.com/46534073/52668218-045c5980-2f24-11e9-8a56-62fab195f92e.png)

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit

**Comment by lunadragnstar** [comment]
This is not a glitch, that is the level of the building

**Comment by Wissi** [comment]
And join us on [Discrod ](https://discord.gg/uCUH8dM)for questions, comments and faster reply.
