### ISSUE TITLE
Alpha.170 - "Sandstone" citizen's hut - design without glass in windows 

### ISSUE THREAD

**Issue by Apollon-Theos** [ldtteam/minecolonies#3376]
### Minecolonies version

Version: 

### Expected behavior

Windows with glasses, pronert aginst spider
![2019-02-13_01 12 58](https://user-images.githubusercontent.com/46534073/52671677-c1eb4a80-2f2c-11e9-8e51-52bf70c5d42b.png)

- 

### Actual behaviour

- 

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit

**Comment by Wissi** [comment]
What level of the Citizen hut is this?
If it is not a bug but designed this way due to complexity of level this "report" will be closed.
Join us on [Discrod ](https://discord.gg/uCUH8dM)for questions, comments and faster reply.

**Comment by lunadragnstar** [comment]
This is the way it is designed, it is not a glitch.
