### ISSUE TITLE
possible building derp

### ISSUE THREAD

**Issue by CharCharthemonkey** [ldtteam/minecolonies#3377]
### Minecolonies version

Version: 

### Expected behavior

- 

### Actual behaviour

- 
im pretty sure these are not correct but if they are feel free to tell me on discord

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit
![2019-02-12_16 05 32](https://user-images.githubusercontent.com/30783285/52675511-b710c580-2eec-11e9-9997-38168dbebc07.png)
![2019-02-12_15 34 45](https://user-images.githubusercontent.com/30783285/52675516-bb3ce300-2eec-11e9-8b5e-4e0b3813504a.png)

**Comment by lunadragnstar** [comment]
Fixed
