### ISSUE TITLE
Alpha.171 - Where is Well and BREWERY ??

### ISSUE THREAD

**Issue by Apollon-Theos** [ldtteam/minecolonies#3380]
### Minecolonies version

Version: 
0.10.171-ALPHA
### Expected behavior

- 

### Actual behaviour

1 water buket + 1 sugar + 3 wheat = 1 bottle of BEER (receipt only NPC-create)
1 beer = guard arrive strengh +1? bravery +1 and intelligence -1, + agro for all mods (maybe include creeper)
1 beer = player receive "slow motion" for some time, down to "full stop" after count of beer :)
- 

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit

**Comment by Nightenom** [comment]
Planned, search first next time

**Comment by Apollon-Theos** [comment]
Today your WIKI not work "Error 502, bad gateway"

**Comment by Apollon-Theos** [comment]
already work, now search ....

**Comment by Apollon-Theos** [comment]
not found "Planned building", please? give me a URL

**Comment by lunadragnstar** [comment]
Search GitHub
