### ISSUE TITLE
Woodman

### ISSUE THREAD

**Issue by Gio1959** [ldtteam/minecolonies#3382]
Version:  minecolonies-1.12.2-0.10.170-ALPHA-universal

### Expected behavior
**That starts working**

- 

### Actual behaviour
**the Woodman arrives and remains always stationary**

- 
**I canceled the first city because many workers remain inactive. then I built the town hall, the builder and the Woodman. I tried to manually assign the worker without solving the problem.**

![2019-02-13_21 55 34](https://user-images.githubusercontent.com/47612082/52743636-bd7d6b00-2fda-11e9-9c19-b7b28468facb.png)
![2019-02-13_21 58 08](https://user-images.githubusercontent.com/47612082/52743643-c0785b80-2fda-11e9-9a36-fbb51baed899.png)
![2019-02-13_21 58 17](https://user-images.githubusercontent.com/47612082/52743653-c4a47900-2fda-11e9-8995-353976dc9bdb.png)
![2019-02-13_21 58 28](https://user-images.githubusercontent.com/47612082/52743656-c706d300-2fda-11e9-9659-85b3d47afa16.png)

**Comment by Raycoms** [comment]
I don't see any trees around there, you gotta place some for him to cut them down.
