### ISSUE TITLE
Lumberjack not chopping acacia trees

### ISSUE THREAD

**Issue by AlosjeN** [ldtteam/minecolonies#3386]
### Minecolonies version

Version: minecolonies-1.12.2-0.10.109-RELEASE-universal

### Expected behavior

Lumberjack cutting down trees, collecting them and dropping them to chest.

### Actual behaviour

Everything works fine in the MineColony except the lumberjack. He just stands by an acacia tree, and looks at it, without doing anything. Tried Firing/Hiring, but it happens again. He just takes the axe, runs to the nearest tree and just stands there. Tried reloading world, hiring other poeple, building new lumberjack huts, nothing worked. And all the tree types are on in the settings of lumberjacks hut. With other trees there is no problem but with acacia he just freezes next to the tree

- 

### Steps to reproduce the problem

1. Build lumberjack hut
2. Hire a person and give him axe, plant trees nearby if there weren't already.
3. Lumberjack starts his work, chops down oaks, but stops at the acacia tree.
4. ... Profit

**Comment by Nightenom** [comment]
Acacia trees were (are?) buggy because of diagonal log placing, not sure how it's now

**Comment by Raycoms** [comment]
It's working fine for me, really not working for you?

**Comment by someaddons** [comment]
Should be fixed.
