### ISSUE TITLE
Add a marriage system

### ISSUE THREAD

**Issue by choalover** [ldtteam/minecolonies#3387]
I realized Minecolonies doesn't have a marriage system, which would be very fitting with Minecolonies in my opinion. You would have to get a church built in your colony first, before you can get married using the Minecolonies mod, and to get divorced you will have to go to the town hall to do so. Marriage to someone includes special features, such as being able to receive gifts from your husband or wife.

**Comment by Nightenom** [comment]
Planned, the only thing we can satisfy your need is #3331

**Comment by Raycoms** [comment]
Closed in favor of joint issue.
