### ISSUE TITLE
workers get stuck inside the cocoa beans

### ISSUE THREAD

**Issue by Thomasdavid097** [ldtteam/minecolonies#339]
### Minecolonies version
0.4.78
version X.X.XXXX or curse X.X.XX
0.4.78 using the one on curse
### Expected behavior
workers get stuck inside the cocoa beans
https://puu.sh/sLM2x/dcae7b05b0.png
https://puu.sh/sLMdw/e1346a1fcb.png
- XXX

### Actual behaviour

- YYY

### Steps to reproduce the problem

1. XYZ
2. ZYX
3. ...
4. Profit

**Comment by Raycoms** [comment]
That's most probably minecraft pathfinding.

2016-12-11 13:35 GMT-02:00 Thomasdavid097 <notifications@github.com>:

**Comment by kedamono** [comment]
I've seen this happen with vanilla villagers as well. I think it's something in Minecraft itself.
