### ISSUE TITLE
Minecolonies Guard tower

### ISSUE THREAD

**Issue by 1g33kyNerd** [ldtteam/minecolonies#3390]
I'm trying to build a guard tower next to the opening of my colony and it won't let me, it keeps telling me that the barracks need to be updated, which the barracks is updated, all the way up to 5. I'm curious if maybe it's too far away from the barracks, since the barracks are towards the back of the colony

**Comment by Raycoms** [comment]
is it a guard tower or a barracks tower?

Am Fr., 15. Feb. 2019 um 21:27 Uhr schrieb 1g33kyNerd <
notifications@github.com>:

**Comment by 1g33kyNerd** [comment]
They're barracks towers, but that probably explains why they aren't working. I didn't realize there were two different ones. My bad.
