### ISSUE TITLE
Iron Chests Compatibility (add Mcol protection)

### ISSUE THREAD

**Issue by spacewolfcub** [ldtteam/minecolonies#3393]
### Minecolonies version
minecolonies-1.12.2-0.10.172-ALPHA-universal

### Expected behavior
Minecolonies colony protection will prevent all chests and chest-like inventories from being opened.

### Actual behaviour
󠂪󠂪󠂪H3roDude:
diamond chests arent protected by minecolonies

### Steps to reproduce the problem
1) Place chest from IronChest mod in the colony
2) Have someone without perms try to open it
3) They can open it

**Comment by marchermans** [comment]
This is intended behavior the player can control this via the townhall ui.
