### ISSUE TITLE
Leisure places/buildings

### ISSUE THREAD

**Issue by Nightenom** [ldtteam/minecolonies#3394]
Adding other types of waypoints to indicate a leisure place/building
Useable in [the paused state](https://github.com/ldtteam/minecolonies/blob/version/1.12/src/main/java/com/minecolonies/coremod/entity/ai/minimal/EntityAIStatePausedHandler.java#L46)

> spacewolfcub:
> If you're doing that, maybe already make waypoints that are adult only, adult/children, children waypoints?
> So it's easier later to tell children where to leisure. Instead of wandering through the Foundry or the Mine. 0.o

**Comment by spacewolfcub** [comment]
> There's types of buildings, Producers Crafters Service
> There could be leisure buildings...?
> Playgrounds, gardens, picnic parks, beaches?
So citizens that are unemployed or paused might idle in Service or Leisure buildings but not at Producers or Crafters which are workplaces.

**Comment by Talyda** [comment]
Not really sure if I should put this in here or not, but if they are paused, and off doing leisure activities, could they take off their "uniform" and wear regular clothing too? Yes, I just want to see my pretty ladies wandering around with their purses and parasols!

*edit* Also, leisure buildings such as Wolf mentioned, could be a good thing as a design contest too, to get more people involved! =) ...and we would need larger colony borders =P

**Comment by lunadragnstar** [comment]
I've made some leisure things to do, parks, playgrounds, and even a beach.

**Comment by Nightenom** [comment]
@Raycoms since we have now decoration controller - can we add some kind of attribute to them? and then have a list to get nearest to npc, random etc.?

**Comment by Raycoms** [comment]
Closed in favor of joint issue.
