### ISSUE TITLE
Deliveryman can't sort for toffee

### ISSUE THREAD

**Issue by MattBeard** [ldtteam/minecolonies#3395]
### Minecolonies version
Version: Modpack v 4.8.4, so Minecolonies 1.12.2-0.10.159

### Expected behavior
- Deliveryman respects order in the racks
- This means that when arriving with an item that there is already one or more of in one of the racks, he/she adds the new item to that rack (as long as there is room)
- Ideally there should be sensible groupings, so if oak wood is in rack 3, and there is no birch wood in any rack, this is also put in rack 3 as it is a related item (some sort of group list or relatedness heuristics would be required to group minecraft:oak_log and minecraft:birch_log). Similarly minecraft:oak_door and minecraft:spruce_door etc....
- Also if at all possible, the frames above racks should be checked if there is no item in the racks of the type
- And... just to make it harder, but better, it would be great if there was a way to record that the last item in a warehouse of a particular type came from rack n so it can be used next time that item needs to be shelved!

### Actual behaviour
- Sometimes items get added to the same rack as existing groups, but more often than not they are just put in any random rack.

### Steps to reproduce the problem
1. Build a colony
2. Build a warehouse
3. Populate a few of the racks with carefully grouped items
4. Employ a deliveryman
5. Watch the chaos ensue!

**Comment by Raycoms** [comment]
Yeah, we got some things planned with the sorting system, but its quite complex and it is very expensive computationally. Will close this for now, but with the new GUI system something will come which will solve all your issues with this.
