### ISSUE TITLE
Sort function is just a way to mess up the warehouse!

### ISSUE THREAD

**Issue by MattBeard** [ldtteam/minecolonies#3396]
### Minecolonies version
Version: Modpack v 4.8.4, so Minecolonies 1.12.2-0.10.159

### Expected behavior
- Sort button works as if a perfect deliveryman had been working all along
- This means that the racks are re-arranged as if issue #3395 had been fixed all along
- In other words each item type is moved into the racks that has the most of that item type in it at the moment

### Actual behaviour
- The items are moved to racks that seem to be totally random, but are grouped. The racks used are not grouped together, so you may have: Empty rack, rack with (diamonds, pumpkin seeds, stone swords and cobblestone), empty rack, empty rack, rack with (oak wood, buckets of lava, pumpkin seeds, gold nuggets), empty rack... etc.

### Steps to reproduce the problem
1. Make a warehouse
2. Run with a deliveryman for a while (trying to keep the racks in order)
3. Press sort
4. Cry

**Comment by Raycoms** [comment]
Yeah, this is because we can't so simply consider the position in the world of a rack for sorting unfortunately. We will add in the future a GUI in the building which allows players to see all stacks nicely sorted on button click which should solve this issue.
