### ISSUE TITLE
No way to create new colony after deleting

### ISSUE THREAD

**Issue by airaani** [ldtteam/minecolonies#3399]
### Minecolonies version

Version: minecolonies-1.12.2-0.10.68-RELEASE-universal.jar

### Expected behavior

After deleting a colony through Commands, Town Hall returned to Supply Camp chest or to Player Inventory or left on the ground to pick up
- 

### Actual behaviour

After deleting a colony through Commands, Town Hall block disappears but Supply Camp does not, leaving no way to create a new colony
- 

### Steps to reproduce the problem

1.  Place Town Hall block
2.  Delete colony through Commands
3.  Town Hall block is gone but Supply Camp is not, leaving no way to create a new colony

**Comment by Talyda** [comment]
You have to pick up the town hall before you delete the town if you want to build another colony.

**Comment by airaani** [comment]
Unfortunately that doesn't help if you don't know it in advance. I've already deleted it so I can't go back and pick the town hall block up first. It just seems there should still be a way to continue.

**Comment by spacewolfcub** [comment]
Go into creative and spawn in a new TownHall block. You can use that to start a new colony. 

I'd be interested to know if it's possible to code in a way that is not abused by dupers: 
(accept command to delete colony and demolish) 
If TownHall controller block will be demolished, 
then spawn a new TownHall controller block in owner's inventory during colony demolish.

**Comment by Raycoms** [comment]
I got an update coming which will fix this

Am So., 17. Feb. 2019 um 23:18 Uhr schrieb spacewolfcub <
notifications@github.com>:

**Comment by airaani** [comment]
Is it possible to go into creative and spawn a new one on someone else's server? Can the admin spawn it for me? How does this work?

**Comment by Raycoms** [comment]
the admin can spawn one /give player minecolonies:blockHutTownHall

Am So., 17. Feb. 2019 um 23:41 Uhr schrieb airaani <notifications@github.com
