### ISSUE TITLE
Farmer problem(s)

### ISSUE THREAD

**Issue by Nibor62** [ldtteam/minecolonies#3403]
### Minecolonies version

Version: minecolonies-1.12.2-0.10.177-ALPHA-universal.jar

### Expected behavior

Go to the field hoed it, then plant it, then harvest seeds that are grown.
And go working another field when the first one is growing.

### Actual behaviour

To, the hoeing works as expected, but the plating is made seed by seed. I mean the farmer take *one* seed, then plant it, then go back take another seed and so on, ...*

And, btw, some time the wheat harvested just disappear !

### Steps to reproduce the problem

Well, create a farm and watch it.
(note : farm using wheat)
(note2 : do not have a delivery man)

### Workaround

Manually put a stack of seeds in its inventory and it manage to plant a field in ~2 days

**Comment by Nibor62** [comment]
Note about the harvesting field:
The farmer always make the weath disappear when he tries to put it in the farm chest.
However, since I have built a deliveryman, the weath seem to have magically reappeared in the warehouse !

**Comment by LaysDragon** [comment]
I meet the same problem here,can't find any crops that farmer harvested,it just walk back to farms then all crops he harvested gone...cannot find any crops in farmers interventory.I guess I have to build a warehouse to retrieve those mystery disappear crops for now

**Comment by Asherslab** [comment]
@LaysDragon don't necro year old issues. make new ones

**Comment by Venv5** [comment]
> I meet the same problem here,can't find any crops that farmer harvested,it just walk back to farms then all crops he harvested gone...cannot find any crops in farmers interventory.I guess I have to build a warehouse to retrieve those mystery disappear crops for now

I got the same problem but I got deliverymen AND a warehosue. Both on level 3. Where is the wheat?

**Comment by MotionlessTrain** [comment]
As Asherslab indicated previously, don't revive issues that are so old. Please make a new issue

**Comment by Venv5** [comment]
> As Asherslab indicated previously, don't revive issues that are so old. Please make a new issue

Wow, nice help. I don't have a new problem and I won't create a new. I wanna now where the wheat is gone. But... thanks anyway.

**Comment by Raycoms** [comment]
The issue back then was because of a particular bug which was solved by then. If you still got some issue, and you got a warehouse and courier, you might have to open a new issue, because then it's a new problem
