### ISSUE TITLE
Townhall employed/unemployed list

### ISSUE THREAD

**Issue by dave75vgnut** [ldtteam/minecolonies#3408]
Version: 0.10.178 Alpha

Town Hall Information
Unemployed
job description: number employed

### Actual behaviour
Town Hall Info
Unemployed
job desc. = com.minecolonies.coremod.gui
does that for the following huts: Crusher, Sawmill, Combat Academy, Archery, Stone Smelter, Stone Mason, Blacksmith

**Comment by Nightenom** [comment]
@dave75vgnut even though the topic itself says enough it's nice to provide so more info

**Comment by Nightenom** [comment]
Maybe filter buttons might be enough

**Comment by dave75vgnut** [comment]
Here are some pictures of what I'm talking about.
![image](https://user-images.githubusercontent.com/21197338/53094080-2be49080-34e7-11e9-9a3d-716d223ed6a3.png)
![image](https://user-images.githubusercontent.com/21197338/53094138-59c9d500-34e7-11e9-953a-8a398368d9d2.png)
