### ISSUE TITLE
[1.10.2] Massive amounts of SMP log spam from Minecolonies

### ISSUE THREAD

**Issue by b0bst3r** [ldtteam/minecolonies#341]
### Minecolonies version

version minecolonies-universal-1.10.2-0.6.1948 but some of this was happening with older version too

### Expected behavior

I don't expect a mod to make logfiles in excess of 20MB long in a single 24 hr period

### Actual behaviour

They are HUGE log files 97% of which are Minecolonies spam

### Steps to reproduce the problem

Run Minecolonies in a server environment with a lot of players

1 log file - https://www.dropbox.com/s/qunajlojafbqrfn/fml-server-latest.zip?dl=1

Repetative spamming in the servers logs include:

Pausing entity for 5 seconds followed by exception spam - http://pastebin.ubuntu.com/23616518/
Movement spam - http://pastebin.ubuntu.com/23616521/
More crashes - http://pastebin.ubuntu.com/23616526/
More Spam with the exceptions - http://pastebin.ubuntu.com/23616534/

All the above can be found in the zipped logfile above.

Please make 

pathfinding {
    # Render pathfinding results for debugging purposes (SSP only)
    B:debugDraw=false

    # Debug output verbosity of pathfinding (0=none, 1=results, 2=live work)
    I:debugVerbosity=0

Work for SMP

**Comment by Raycoms** [comment]
Hello there,

Thanks for the report.
The next version will have the pathing logging removed.
I actually forgot to remove that for the current version.

The other bugs are really strange.
I believe old miners are causing this.
Since we've completely changed how the miner works it would be handy if the
players rehire/fire their current workers or even place the miner building
again.
Anyway, I will provide a version which will at least avoid the exceptions.


2016-12-11 22:08 GMT-02:00 b0bst3r <notifications@github.com>:

**Comment by Raycoms** [comment]
https://www.dropbox.com/sh/9cnqcjl0nan57cy/AADnsckxgJEFWa5qTovtiNN1a/branch/feature/%23159-invalid-block-interactions?dl=0&preview=minecolonies-universal-1.10.2-0.6.2010.jar

It shouldn't occur in this file though.

2016-12-11 22:21 GMT-02:00 Ray Neiheiser <ray.neiheiser@gmail.com>:

**Comment by marvin-bitterlich** [comment]
@b0bst3r The `I:debugVerbosity=0` is an even more spammy setting ;)

We can't stop exceptions from printing, that would not be good. But we can fix the exceptions.

And the pathfinding spam can be removed/deactivated imo @Raycoms

**Comment by Raycoms** [comment]
Should be solved in the newest version I will upload today.

**Comment by b0bst3r** [comment]
Thanks but that version above is not good, you place the town hall, nothing happens (no colonists appear and the block has no interface).  Once you break the town hall and replace it things start to happen.  But after placing the builders hut, a builder gets assigned and he does nothing except move so slowy a snail could beat his pace :)

**Comment by Raycoms** [comment]
I fixed that in the newest version on curse already =)

2016-12-12 14:21 GMT-02:00 b0bst3r <notifications@github.com>:

**Comment by Raycoms** [comment]
Additionally, are you aware of the admin commands we added to the game?

- Delete colony, colonist, find colony etc.

2016-12-12 14:30 GMT-02:00 Ray Neiheiser <ray.neiheiser@gmail.com>:

**Comment by b0bst3r** [comment]
No not at all, is there a list of them on the wiki?  I couldn't find any.

**Comment by Raycoms** [comment]
No not yet:

short version:

/mc colonies list (Lists all colonies)

/mc colony info <colonyid | playername> (info)
/mc citizens list <colonyid> list of citizens of the colony
/mc colony delete <colonyid | playername> delete his colony
/mc colony kill | respawn <colonyid> <citizenid> (kills or respawns citizen)



2016-12-12 17:55 GMT-02:00 b0bst3r <notifications@github.com>:
