### ISSUE TITLE
Builders' Hut - Birch - Level 2 is Bugged

### ISSUE THREAD

**Issue by ghost** [ldtteam/minecolonies#3419]
### Minecolonies version

Version: 0.10.109-RELEASE

### Expected behavior

- The builder should go in and out easy.

### Actual behaviour

- The Builder gets stuck in the Builders' Hut can't get out again, if he/she gets in.
![2019-02-22_20 43 07](https://user-images.githubusercontent.com/47212347/53260416-83028500-36e2-11e9-8d0c-af11f5ee09f1.png)

### Steps to reproduce the problem

1. Build a Builders' Hut with Birch
2. Upgrade it to Birch Level 2
3. Let citizen get inside of it
4. He/she's bugged inside.

**Comment by Raycoms** [comment]
Please upgrade
