### ISSUE TITLE
Officer Permission Bug

### ISSUE THREAD

**Issue by Azragor** [ldtteam/minecolonies#342]
### Minecolonies version

version 0.6.1948

### Expected behavior

- Breaking a builder block

### Actual behaviour

- Don't work as an officer level right. I thing a read I should be able to move building block as 
an officer of the coloni

### Steps to reproduce the problem

1. Log in other game an officer of a colonie
2. Try to break a colonie block

**Comment by marvin-bitterlich** [comment]
The Officers should be able to break all blocks except the Townhall.
Can you try again and then send client and server logs from when you did?

**Comment by Raycoms** [comment]
Is it possible that not even the owner is able to break that block?
That sometimes happen and we don't know why yet.

2016-12-12 5:06 GMT-02:00 Marvin Hofmann <notifications@github.com>:

**Comment by Azragor** [comment]
The owner is able to break the block, even after the attempt from the officer.

`[08:21:02] [Server thread/INFO] [minecolonies]: Colony 4 - new AbstractBuilding for class com.minecolonies.coremod.blocks.BlockHutBuilder at BlockPos{x=-276, y=63, z=450}
`
That's the relevant code from the event.

Furter details : It's seem that the block was break, since you can't acces the GUI anymore and everything
spill out of the container. The block is still present in the world. The only way the change this is for the owner to come and break the block.

I did test if placing an other building block at the same position would work for the officer and it
does. The first buikding block is broken and drop in item form.

Hope that help.

My test for the log was done with this mod list:
-Inventory Tweaks 1.61-58
-jei 3.13.6.389
-journeymap 5.3.0b2
-optifine U_D4
-Waila B3_1.9.4
-Wawla 2.3.1.214

**Comment by Raycoms** [comment]
Thanks for the report.
It seems like sometimes the tileEntities of our blocks get lost which makes
them inaccessible.
We guess that's some minecraft related issue and are working on a
workAround to now affect the gameplay.

2016-12-12 11:29 GMT-02:00 Azragor <notifications@github.com>:

**Comment by kedamono** [comment]
I've run into the same issue. In the middle of a session on SSP Minecolonies, with a custom modpack, I stopped being able to open chests, access workbenches, sleep, break dirt blocks with my empty hand, and open some doors. I can still access the townhall block and I'm listed at mayor when I run the /minecolonies colony info command. I can use tinkers tools to break blocks.

As soon as I'm far enough outside of my colony, I can open chests, benches, break blocks, etc.

minecolonies-universal-1.10.2-0.6.2097

**Comment by Raycoms** [comment]
You should try to restart your colony.
Or use the new commands to add you as officer in the meanwhile.

2016-12-28 17:44 GMT-02:00 kedamono <notifications@github.com>:

**Comment by Raycoms** [comment]
restart the server I wanted to say.

2016-12-28 21:01 GMT-02:00 Ray Neiheiser <ray.neiheiser@gmail.com>:

**Comment by kedamono** [comment]
The Latest build fix this problem. But, there's another problem. :-(

**Comment by Raycoms** [comment]
please report it as a seperate issue

2016-12-28 21:57 GMT-02:00 kedamono <notifications@github.com>:
