### ISSUE TITLE
Builder needs Oak Door instead of Cactus Door

### ISSUE THREAD

**Issue by fr3akb0y** [ldtteam/minecolonies#3421]
### Minecolonies version
Version: minecolonies-1.12.2-0.10.187-ALPHA-universal

### Expected behavior
- Builder using Cactus Door as a Cactus Door

### Actual behaviour
- The Builder requests a normal Oak Door instead of a Cactus Door in the Sandstone Style. He also places these doors as Cactus Doors even though they are Oak Doors

### Steps to reproduce the problem
1. Order Builder to build a Building that needs a Cactus Door
2. Look into the resources he needs
3. See that he will need an Oak Door instead of a Cactus Door

**Comment by Nightenom** [comment]
Cactus things are added to their respective oredicts where vanilla wooden things are

**Comment by Raycoms** [comment]
Fixed on structurize side, will be merged into minecolonies soon
