### ISSUE TITLE
Scan Tool Capture box sizing / placement

### ISSUE THREAD

**Issue by AdamM72** [ldtteam/minecolonies#3424]
### Minecolonies version

Version:  Minecraft 1.12.2, 
               MineColonies 1.12.2-0.10.154-BETA
              Structurize 1.12.2-0.10.45-ALPHA

### Expected behavior

1. Pressing Esc key allows Scan box to remain and player to move / view selection. Reclicking with Scan Tool reenters the existing Scan Tool selection as per Build tool
2. As Dimensions are updated in the Scan Tool GUI, the bounding box also updates.

### Actual behaviour

1.  Player cannot reenter the Scan Tool GUI - trying to do so clears the existing Scan Tool selection box and the user must 'reselect' box points. ie. the Scan box resets.

2. Updating the dimensions in the Scan tool GUI does not update the scan tool box in the world. If you update the points manually in the dimension box and then go through the Replace process the box updates after this.

**Comment by Raycoms** [comment]
Fixed on structurize side, will be merged into minecolonies soon
