### ISSUE TITLE
scan tool dimension text entry

### ISSUE THREAD

**Issue by AdamM72** [ldtteam/minecolonies#3425]
### Minecolonies version

Version: Minecraft 1.12.2,
MineColonies 1.12.2-0.10.154-BETA
Structurize 1.12.2-0.10.45-ALPHA

### Expected behavior

Deleting text and reentering new values in the Scan Tool GUI From: and To: works if the last character is deleted.

### Actual behaviour

Deleting the last character in the field results in the GUI closing and an Invalid Number - Closing! message.

### Steps to reproduce the problem

1. Use the Scan Tool to select an area
2. In any of the X, Y,or Z fields, use the backspace key (or Delete key) to delete the existing values.
3. On deleting the last digit, the error occurs.
4. ... Profit

**Comment by Raycoms** [comment]
Fixed on structurize side, will be merged into minecolonies soon
