### ISSUE TITLE
No way to specify metadata in lucky block config

### ISSUE THREAD

**Issue by chazwarp923** [ldtteam/minecolonies#3426]
### Minecolonies version

Version: 0.10.187-ALPHA

### Expected behavior

A way to specify metadata in the section of the config for lucky block when the miner is mining.
I have tried the only two ways that i could think of to specify metadata, thermalfoundation:ore:1, and thermalfoundation:ore=1. 

### Actual behaviour

Unable to specify metadata.

### Steps to reproduce the problem

1. Add thermalfoundation:ore:1 or thermalfoundation:ore=1 to the lucky blocks section of the config.
2. Load up minecraft
3. Observe error in log "[minecolonies]: Invalid lucky block: thermalfoundation:ore:1!48"
4. ... Profit

**Comment by Raycoms** [comment]
you're right, there is no way to specify metadata yet.
Let me check into this,
