### ISSUE TITLE
Builders digging up floors

### ISSUE THREAD

**Issue by FallingLeaf14** [ldtteam/minecolonies#3427]
![builder bug](https://user-images.githubusercontent.com/47936090/53450493-3a441800-39d1-11e9-9af6-3bacd5185176.PNG)
![builder bug 2](https://user-images.githubusercontent.com/47936090/53450494-3adcae80-39d1-11e9-8a06-28674281ad96.PNG)
![builder bug 3](https://user-images.githubusercontent.com/47936090/53450495-3adcae80-39d1-11e9-88ac-97f8f6c92615.PNG)

Version: 
0.10.109-RELEASE
### Expected behavior

 Builders build the building ontop of the ground
- 

### Actual behaviour

The builders dig to the normal floor level, but continue digging down until they reach the last level with blocks, and then remove every block at that level. They then build the building in the completely empty space, often having it float in the air. Within the building parameters, they dig down and create a completely empty square, one level below the lowest block that they place for the build. 
- 

### Steps to reproduce the problem

 I just set the builders to building, and they did it both with the medieval spruce builders hut and taigia town hall.
1. 
2. 
3. 
4. ... Profit

**Comment by Nightenom** [comment]
Some screenshots would be nice

**Comment by Raycoms** [comment]
Please update

**Comment by Raycoms** [comment]
Please update description with screenshots of what you mean if still an issue, until then -> closed

**Comment by FallingLeaf14** [comment]
Sorry, wasn't getting updates from this thread. Thank you for your quick response time.

**Comment by Raycoms** [comment]
Did you try updating?

**Comment by FallingLeaf14** [comment]
Updating the mod or minecraft?

**Comment by Raycoms** [comment]
the mod

Am Di., 26. Feb. 2019 um 19:28 Uhr schrieb FallingLeaf14 <
notifications@github.com>:

**Comment by FallingLeaf14** [comment]
I thought 0.10.109-RELEASE was the most current version? If there is a more current version, where would I find that?

**Comment by Raycoms** [comment]
Please always download through here:
https://minecraft.curseforge.com/projects/minecolonies

Am Di., 26. Feb. 2019 um 19:30 Uhr schrieb FallingLeaf14 <
notifications@github.com>:

**Comment by Nightenom** [comment]
Actually from the third screenshot it looks like someone swapped air/solid placeholders
