### ISSUE TITLE
Townhall block is under the building

### ISSUE THREAD

**Issue by lebanni** [ldtteam/minecolonies#3430]
minecolonies-1.12.2-0.10.192-ALPHA-universal.jar

Level 1 townhall. Townhall block is under the building.

![2019-02-24_17 25 42](https://user-images.githubusercontent.com/2799575/53301998-d3e8b980-3859-11e9-886f-fdcf5c5787d4.png)
![2019-02-24_17 25 53](https://user-images.githubusercontent.com/2799575/53302012-01356780-385a-11e9-94c9-f961c0460141.png)

**Comment by Raycoms** [comment]
@lunadragnstar did you fix this yet?

**Comment by tindin** [comment]
its seems to only be medieval oak.  the town block isnt present in the viewing when using the wand to place it.  when you do place it it puts the town hall block in the middle  under the bottom layer when upgrading it causes the builder to build upwards (basement doesnt go down it goes up over the main building)

**Comment by lunadragnstar** [comment]
Seemed fine on my end, but I rescanned it, just to be sure.
