### ISSUE TITLE
Decorations are shifting positions from where they are placed if you rotate them, if you rotate to the left, they go north 1 block, if you rotate right, they go south 1 block

### ISSUE THREAD

**Issue by lunadragnstar** [ldtteam/minecolonies#3433]
Using the cave colonies mod pack on the server

Decorations are shifting positions from where they are placed if you rotate them, if you rotate to the left, they go north 1 block, if you rotate right, they go south 1 block

**Comment by marchermans** [comment]
@Raycoms That worked previously, is there a Problem with the Primary block calc, if the template does not contain the any interesting block? Maybe it falls back to 1,1,1 instead of 0,0,0?

**Comment by Raycoms** [comment]
fixed

**Comment by lunadragnstar** [comment]
Apparently this is still happening on .215
