### ISSUE TITLE
Fancy Path placement is off from visual.

### ISSUE THREAD

**Issue by masternetra** [ldtteam/minecolonies#3435]
### Minecolonies version

Version: 1.12.2-0.10.189-BETA

### Expected behavior
Expected the Fancy path to place as seen.

### Actual behaviour
Fancy path gets placed one block off on the x positioning. (+1 I think)

### Steps to reproduce the problem
1. Use wand to start placing Fancy Path
2. rotate and place.

**Comment by Raycoms** [comment]
Update please

Am Di., 26. Feb. 2019 um 15:26 Uhr schrieb masternetra <
notifications@github.com>:
