### ISSUE TITLE
crafting recipe for the town hall does not work

### ISSUE THREAD

**Issue by SulpherStaer** [ldtteam/minecolonies#3436]
### Minecolonies version

Version: 1.12.2-0.10.202-RELEASE-universal

### Expected behavior
Put the crafting recipe in the crafting table, and get a town hall block.

### Actual behaviour
The crafting recipe does not give a town hall block, it remains empty as if it is a bad recipe.

![2019-02-26](https://user-images.githubusercontent.com/5037244/53440774-9c1e7500-3a05-11e9-9cde-25c84891c5c0.png)

### Steps to reproduce the problem

try making a town hall through crafting alone (not having placed a boat or tent)

**Comment by Raycoms** [comment]
Yes, this is correct, the recipe is only unlocked once you placed a boat or tent.
