### ISSUE TITLE
[suggestion] Tools

### ISSUE THREAD

**Issue by tomorrow4268** [ldtteam/minecolonies#344]
Workers/Miners/Lumberjacks first use up low-tier tools and only mining high tier ores then instantly switching back to low tier tools.

They normally use the one tool that is positioned at a prior position of their inventory, so if you got an iron at 1. und a stone-tool at 2. he will use up iron first even for mining stone.

**Comment by marvin-bitterlich** [comment]
That behavior was the case for some time, but we decided to switch it. Because there are cases where you want your miner to use the really fast tools on stone too.

I think there even was a time where he asked for stone tools even if he had iron ones.

We are planning to add this behavior as an option for the miner again, but not as a high priority for now :)

**Comment by pmardle** [comment]
Using tools (and good tools) is part of the payment for having someone mine for you..  if you want perfectly efficient mining, do it yourself :)

The miner will by far generate more iron per iron tool that the tool uses..

**Comment by neadlak** [comment]
If you want to make your workers more efficient regarding materials use:

You can already create huge efficiencies by using Tinker's Construct tools on your miners. Repairing those when they break is relatively cheap. A sharpening kit is 2 ingots, versus 3 and sticks for a new iron tool. Modifiers don't need to be re-applied. You can exchange tool parts to upgrade them to higher tiers without re-enchanting or re-modifying. You can use a sharpening kit to make a wood tool able to mine any vanilla block up to and including obsidian.

The minecolonies testpack has tinker's construct built in, so it's a fair assumption that you have access to these tools.

**Comment by tomorrow4268** [comment]
i am aware of that, that they should use up tools as payment xD i have very cheap diamondtools from my villagers, so doesn't bother me ;D
