### ISSUE TITLE
Waypoint placeholders in birch buildings causing pathing issues

### ISSUE THREAD

**Issue by JumpySmudge** [ldtteam/minecolonies#3442]
Version: minecolonies-1.12.2-0.10.204-ALPHA-universal

### Expected behavior
Citizens to go straight to work (day) or home (night).

At the start of the day, any workers should go straight to their work location and at night, they should go back to their house.

### Actual behaviour

Citizens go to all birch buildings before going to work/home.

Birch buildings have waypoint placeholders in the schematics, so when they have been built, any of my citizens are going to all birch buildings first before going to work/home.

This only happens with birch buildings, not medieval birch.

### Steps to reproduce the problem

1. See the waypoint placeholders in the blueprints of birch buildings
2. Build any regular birch (not medieval birch) building
3. Citizens will now go to all birch building first before going to work/home
4. ... Profit

**Comment by Raycoms** [comment]
What is the issue with that? They use waypoints to reduce processing requirements, this way the resulting path may not be optimal. You can fix this by placing your own waypoints.
