### ISSUE TITLE
Citizens vanished and could not interact with blocks

### ISSUE THREAD

**Issue by MozesX50** [ldtteam/minecolonies#3446]
### Minecolonies version

Version: minecolonies-1.12.2-0.10.206-ALPHA-universal

### Expected behavior

Citizens stayed in existence. I already used the back up command but my issue is that a ton of Level 5 buildings are now being considered lower after loading the back up.. is there any way to use a command to set say, a library block to be level 5 (to reflect the actual structure). its a lot of progress lost.
- 

### Actual behaviour

they vanished and i couldnt interact with blocks (townhall, Houses, Bakerey, etc)
- 

### Steps to reproduce the problem

I have no Idea
1. 
2. 
3. 
4. ... Profit

**Comment by Raycoms** [comment]
After loading the backup, use the recall all methods at the townhall to get them back.
Colonies sometimes mess up when forge fails to save it accordingly unfortunately.
In terms of getting building levels back, you can go to creative mode and paste the building in with one click on the buildtool.
