### ISSUE TITLE
Medieval Oak Town Hall Placement Issues.

### ISSUE THREAD

**Issue by InnuendoSA** [ldtteam/minecolonies#3448]
Version: minecolonies-1.12.2-0.10.206-ALPHA-universal

### Expected behavior

When Building a medieval oak Town Hall, the Town Hall "desk" was by the entrance.

### Actual behaviour

Now when Building a medieval oak Town Hall, the Town Hall "desk" is not by the entrance but in the middle of the build 3-4 blocks under ground  where no one can access it. 
This includes Level 1-5.

Older build Town Halls removes the Town hall "desk" if you upgrade it.

### Steps to reproduce the problem

Just place a medieval oak Town Hall or Upgrade a old one.

**Comment by lunadragnstar** [comment]
This has been fixed, will be in the next update if not already in the newest alpha
