### ISSUE TITLE
Guards are goats (figuratively)

### ISSUE THREAD

**Issue by NIKITAzed** [ldtteam/minecolonies#3450]
### Minecolonies version

Version: 1.12.2-0.10.22-ALPHA in All The Mods 3 modpack

### Expected behavior
Guards on automatic patroll, patrolling

### Actual behaviour
Some of them start to channel their inner goat and when I sometimes walk into the settlement I see 3 of them standing on the warehouse, and 2 on various other roofs

img
https://cdn.discordapp.com/attachments/453661287830913024/551116277041856522/unknown.png

### Steps to reproduce the problem
I honestly have no idea how you would reproduce this, I'm sure there has to be something that triggers it, but my base is in the deep dark, the portal to which is more or less in the middle of the village, so when I go back and forth entities don't load up well, but the area stays loaded 90% of the time as the other people are based right next to the colony.

**Comment by Raycoms** [comment]
Oh yeah, they love climbing these kinds of things, don't they ever come down?

**Comment by NIKITAzed** [comment]
not that I've seen, they just sit there, one time I saw 3 on the warehouse, 1 on a tree, 1 on top of the little hut in barracks, and 2 on top of different fence posts in barracks

**Comment by Raycoms** [comment]
Does restarting the world fix it?

Am Sa., 2. März 2019 um 08:46 Uhr schrieb NIKITAzed <
notifications@github.com>:

**Comment by NIKITAzed** [comment]
it's on an actual server not a lan hosting world, so that would make it a bit difficult to restart every time, I was about to try it anyway just to find out, but there are other people on right now

**Comment by Raycoms** [comment]
Oh no, I just want to know if it works in general, trying to find out what
is causing it.

Am Sa., 2. März 2019 um 09:04 Uhr schrieb NIKITAzed <
notifications@github.com>:

**Comment by NIKITAzed** [comment]
ok will update this when I try it

**Comment by NIKITAzed** [comment]
restarting the server fixed the guard that was stuck on top of the warehouse, but there are still other ones stuck elsewhere, I noticed 3 getting stuck in the actual guard tower as they were all trying to go down the same ladder at the same time, pushing each other out of the way, but once they managed to go down it, they just sat at the bottom of it

**Comment by Raycoms** [comment]
Weird

Am Sa., 2. März 2019 um 11:00 Uhr schrieb NIKITAzed <
notifications@github.com>:

**Comment by NIKITAzed** [comment]
the weirdest part is the warehouse, as there is no way they should physically be able to get up there, unless they get stuck somewhere and the game teleports them on it

**Comment by Michael-Phoenix** [comment]
I think I've just witnessed how that happens.
Concussion creepers teleport upon detonation. That's how my guard ended up on a rooftop.

**Comment by NIKITAzed** [comment]
I was using the All The Mods 3 modpack at the time, I don't believe it has concussion creepers in it
