### ISSUE TITLE
Cannot interact with own colony

### ISSUE THREAD

**Issue by Devouring-One** [ldtteam/minecolonies#3452]
### Minecolonies version

Version: minecolonies-1.12.2-0.10.202-RELEASE-universal

### Expected behavior

- Interact with village

### Actual behaviour

- Cannot do anything

### Steps to reproduce the problem

1. Start game, on dedicated server, play around with colonies
2. Disconnect and re-connect
3. Wait couple of minutes
4. Lose access to own permission
5. ... Profit

### Additional info

Tried to refresh colony with refresh command, tried switching owner and giving it back, tried adding owner as officer - no result. Please fix.

**Comment by Raycoms** [comment]
Does the colony still exist?

**Comment by Devouring-One** [comment]
Yeah

Workaround for us was to delete client config folder and replace it with server config. Seems that creating (or visiting) a colony in local world breaks something.

**Comment by Raycoms** [comment]
Wow, that's weird

Am Sa., 2. März 2019 um 13:16 Uhr schrieb Devouring-One <
notifications@github.com>:

**Comment by Raycoms** [comment]
Let's reopen this if it happens again, can't reproduce
