### ISSUE TITLE
workingRangeTownHallChunks doesn't work right.

### ISSUE THREAD

**Issue by masternetra** [ldtteam/minecolonies#3453]
### Minecolonies version

Version: 1.12.2-0.10.202

### Expected behavior
Expect the the number set for workingRangeTownHallChunks to be the distance in chunks from townhall you can place buildings.

### Actual behaviour
Value doesn't seem to be used or not used right. I have the value set to 8 but can only place structures within 5 chunks. This remained the case for two new worlds.

### Steps to reproduce the problem

Set value to 8 and play the game.

### Additional Notes
As I write this I noticed I haven't tried yet just increasing the value further to see if it's locked at 5 regardless of the value or if it increases still with value will try afterwards.
Also have.
Also to note of possible importance I have "enableInDevelopmentFeatures" set to true if that's of any help.

**Comment by Raycoms** [comment]
Weird, the chunk value is only for new colonies it doesn't increase
automatically, but in new worlds it should load them, did you try relogging
to check?

>

**Comment by masternetra** [comment]
The border though was at 8th chunk but wasn't allowing me to build past the 5th.

I think it was a weird glitch with the settings, I changed it to 9 and now it's behaving as it should on new worlds now. Maybe something to do with the number of upgraded versions been through or perhaps I had the value set before turning on experimental stuff, who knows at this point. Either way working now.

**Comment by Raycoms** [comment]
Great

**Comment by masternetra** [comment]
Though recently had a weird glitch where I initially couldn't put down a decoration after the 4th chunk (was fifth in a queue of decoration placements) but tried a different decoration and was able to. I dunno seems a little sketchy somewhere.
