### ISSUE TITLE
Woodcutter stand and does nothing

### ISSUE THREAD

**Issue by ZzylinN** [ldtteam/minecolonies#3455]
Version:
minecolonies-1.12.2-0.10.209-BETA-universal
(it was in previous versions)

forge 1.12.2-14.23.5.2768
other mods

Map started on older versions of minecolonies-1.12.2.xxx

---------------------------------------------------------------
The woodcutter worked 100% in the version minecolonies-1.12.2-0.10.58-ALPHA-universal

A Woodcutter stands and does nothing. Did reset Woodcutter but it also did not help
Applied command /mc rs reset colony: 1 did not help.

Woodcutter stand and does nothing
![2019-03-03](https://user-images.githubusercontent.com/34644142/53691384-291b5280-3da7-11e9-9e20-5f39ee027826.png)

At the woodcutter in the inventory is a diamond axe.
![2019-03-03 2](https://user-images.githubusercontent.com/34644142/53691375-f5d8c380-3da6-11e9-95f5-70594c66ca0b.png)

Woodcutter's hut level 5. The level of the woodcutter 1
![2019-03-03 5](https://user-images.githubusercontent.com/34644142/53691382-1739af80-3da7-11e9-879f-041b542efc28.png)

His queries are empty.
![2019-03-03 1](https://user-images.githubusercontent.com/34644142/53691389-3c2e2280-3da7-11e9-88c1-80c843c55d8b.png)

Nearby there is a forest for cutting.
![2019-03-03 3](https://user-images.githubusercontent.com/34644142/53691394-4d772f00-3da7-11e9-939b-f937a84f269a.png)
![2019-03-03 4](https://user-images.githubusercontent.com/34644142/53691396-510ab600-3da7-11e9-9d2d-b618e96b9a06.png)

All types of trees for cutting are included.
![2019-03-03 6](https://user-images.githubusercontent.com/34644142/53691407-7eeffa80-3da7-11e9-8fe8-93286d4ecc28.png)

And the woodcutter’s hut does not need to be restored.
![2019-03-03 7](https://user-images.githubusercontent.com/34644142/53691450-a4313880-3da8-11e9-8ebe-fc8fb2ce6d4a.png)

**Comment by someaddons** [comment]
You're using dynamic trees, the lumberjack only fells them when they've reached a certain size(configurable in the minecolonies.cfg)

**Comment by ZzylinN** [comment]
I have included all trees for felling, including vanilla. Here are just a woodcutter does not chop them.

**Comment by Raycoms** [comment]
All the close trees seem too "thin" to be cut yet.
You gotta wait for them to be more mature.

**Comment by ZzylinN** [comment]
What about vanilla trees? They have no growth! But the woodcutter does not chop them!

**Comment by Raycoms** [comment]
Are they activated and close enough? And is he requesting an axe?

Am Mo., 4. März 2019 um 22:01 Uhr schrieb Sasha <notifications@github.com>:

**Comment by ZzylinN** [comment]
How far does a woodcutter work?

**Comment by Raycoms** [comment]
Depends on the building level

**Comment by ZzylinN** [comment]
building level 5
45-50 blocks distance to vanilla tree.

In previous versions, the woodcutter handled the whole place with trees planted and even further.
![2019-03-03 4](https://user-images.githubusercontent.com/34644142/53804816-ad6e0100-3f72-11e9-9a90-c84d3a465c2b.png)

**Comment by Raycoms** [comment]
did you try to fire and rehire him?

Am Di., 5. März 2019 um 09:19 Uhr schrieb Sasha <notifications@github.com>:

**Comment by ZzylinN** [comment]
Yes, I fired and re-hired a woodcutter. Hired another woodcutter. He still does not want to cut trees.


updated to version minecolonies-1.12.2-0.10.214-ALPHA and planted close (4 cubes from the end of the building) The woodcutter cut down a vanilla tree. I repeat the level 5 building.

And vanilla trees on the glade (screenshot above) do not want to chop. Although I used to cut everything

**Comment by Raycoms** [comment]
weird, could you replace the hut maybe?

Am Di., 5. März 2019 um 11:16 Uhr schrieb Sasha <notifications@github.com>:

**Comment by someaddons** [comment]
try an iron axe

**Comment by ZzylinN** [comment]
Completely rearrange and rebuild the hut from scratch?


> 
> weird, could you replace the hut maybe? Am Di., 5. März 2019 um 11:16 Uhr schrieb Sasha <notifications@github.com>:
>

**Comment by ZzylinN** [comment]
I tried to give an iron ax! The woodcutter does nothing as well. Cuts only close to version minecolonies-1.12.2-0.10.214-ALPHA
> 
> 
> try an iron axe
