### ISSUE TITLE
Build tool doesn't show .nbt-schematics

### ISSUE THREAD

**Issue by Tarumba** [ldtteam/minecolonies#3456]
Version: Ever since minecolonies-1.12.2-0.10.184-ALPHA-universal

### Expected 
The build tool is backwards compatible with the old .nbt schematics and/or the .nbt schematics are not converted to the new schematics file type

### Actual behaviour
The build tool no longer shows the .nbt schematics (I copy/pasted them into both the structurize/scans and minecolonies/scans folder, structurize/cache and structurize/schematics didn't work either)

### Steps to reproduce the problem
1. have .nbt schematic file in structurize/scans made in an old build
2. try to build them using the build tool in version 0.10.183 and earlier -> works
2. try to build them using the build tool in version 0.10.184 and later -> schematic doesn't show up

**Comment by marchermans** [comment]
You need to use the available update procedure. The new system is required for future expansion and systems, as such it is not backwards compatible. Please use the available update procedure to update your schematics.

If you need help with this, Join the minecolonies discord or look at the minecolonies wiki.
