### ISSUE TITLE
[1.10.2] Invalid tool crowbar not implemented as tool!

### ISSUE THREAD

**Issue by b0bst3r** [ldtteam/minecolonies#346]
minecolonies-universal-1.10.2-0.6.2018

No idea how he got it, maybe from a loot chest?
No idea how to find out which miner, the server operates a playerbase of around 30 individual players most have minecolonies.

http://pastebin.ubuntu.com/23629305/

Can you check for invalid tools and get him to I dunno drop it or trash it or anything cept use it (and yeah logs are full of these)?

**Comment by Raycoms** [comment]
@Kostronor can you take a look at this?
Why is this getting called for a crowbar?

**Comment by marvin-bitterlich** [comment]
@Raycoms because crowbar is a new tool category added by a mod and I added that catch so we get shouted at if someone f.e. called his pickaxe "pickhammer" :D We could add a check for crowbar and all other tools we just ignore, so that we see when mods do something stupid

**Comment by Raycoms** [comment]
Ahk =D We really need a "Log without spam" method xD

2016-12-16 16:22 GMT-02:00 Marvin Hofmann <notifications@github.com>:
