### ISSUE TITLE
Max citizen number not increasing

### ISSUE THREAD

**Issue by JJPederson** [ldtteam/minecolonies#3463]
### Minecolonies version 

Version: minecolonies-1.12.2-0.10.202-RELEASE-universal.jar

### Expected behavior

I have been attempting to raise my citizen cap, but it's simply not going up. I've built several houses (4 level 3 houses and 1 level 2), but the cap was stuck at 4. I then killed one of my citizens to see if this would work (I'm not a smart guy), and now the citizen cap is simply 3/3. I would expect the number to go up according to my housing levels (which if my math serves, should be 14.)

### Actual behaviour

The cap stays the exact same.

![2019-03-04_18 47 02](https://user-images.githubusercontent.com/48219778/53752046-f740e380-3ead-11e9-8e9e-9a91d1612efc.png)
![2019-03-04_18 48 01](https://user-images.githubusercontent.com/48219778/53752100-0de73a80-3eae-11e9-9820-ad4546fbf6ab.png)

### Steps to reproduce the problem

Well, as you can see I've built a townhall and several houses. I will say; while messing around with the reposition feature, I accidentally broke my townhall and had to place a new one, I have no idea if this is somehow messing with the mod, but I didn't even think about it until some time later.

**Comment by JJPederson** [comment]
I forgot to say, but I'm simply playing on the All The Mods 3 - Remix modpack. So I don't know if there's something conflicting there?

**Comment by someaddons** [comment]
hm I cannot reproduce the issue locally, maybe due to the TH breaking your citizen huts arent registered with the colony anymore. Could try building another new one and checking your log for any exceptions thrown

**Comment by JJPederson** [comment]
Making another townhall? How do I check my log for exceptions exactly? Thanks

**Comment by Raycoms** [comment]
He meant, the colony townhall doesnt count as home for citizens anymore,
might this be your issue?

Am Mo., 4. März 2019 um 17:55 Uhr schrieb JJPederson <
notifications@github.com>:

**Comment by JJPederson** [comment]
How would I go about confirming that? The citizens are visible in the GUI of the townhall. Should I just delete the colony and make a new townhall, or should I attempt to recreate the issue in a singleplayer world?

**Comment by Raycoms** [comment]
Hmm, Just checked your description again, it's weird. This cap should be
increasing. Can you send a recruitment package?

Am Mo., 4. März 2019 um 18:05 Uhr schrieb JJPederson <
notifications@github.com>:

**Comment by JJPederson** [comment]
How do I send a recruitment package, exactly?

**Comment by Raycoms** [comment]
In the townhall there is a recruitment tba

**Comment by GanthorPrime** [comment]
got a similiar issue like this and noted that in the debug screen (F3) the colony was not show in the nearest colony text in the left column (it shows something like 'ColonyName: xxx blocks from center').

so, after check using '/mc colony list'  i claimed using 'mc colony claim'.  That solves the problem afetr a restart
