### ISSUE TITLE
Deliveryman NPE in warehouse

### ISSUE THREAD

**Issue by GanthorPrime** [ldtteam/minecolonies#3464]
### Minecolonies version

Version: minecolonies-1.12.2-0.10.212-ALPHA-universal

### Actual behaviour

Deliveryman is throwing an NPE randomly when he reach the warehouse, and then put in pause to crash again on restart.

the NPE: [link to gdrive](https://drive.google.com/file/d/1AeFqCMAikIivVc-kw8K_4yTmenRMwlwQ/view)

[link to pastebin](https://pastebin.com/zt7AXXMe)

### Steps to reproduce the problem

2 deliverimans, medieval spruce warehouse, but not sure how they entered in this state. 

I tried so far:

1. Fire and rehire only to throw a NPE again inmediatly at warehouse
2. Restart worker seems to solve the npe for a while, but it throws again shortly after
3. Sometimes restarting the request system (/mc rs reset) solves the npe but i will fail eventually

**Comment by Nightenom** [comment]
@GanthorPrime wrong link, also don't use drive, pastebins are the best option for that
edit: fixed

**Comment by Raycoms** [comment]
Can you do an /mc rs reset colony: id, that will fix it?

**Comment by GanthorPrime** [comment]
already tried /mc rs reset and didnt solve the problem permanently, at some point nearby they start to show the npe again.

Since this problem start showing on 1 of 4 colonies and that changing workers didnt solve the problem, i started to think maybe something goes wrong with the colony data: building info goes wrong  somewhere: deliveryman, warehouse.. etc.

I did the following and it seems to solve the problem:

1.- backed the world
2.- in the problematic colony: destroy the deliveryman hut block (theres 2 o them)
3.- workers got unemployed at spected,  no deliverymans: mc/ rs reset colony: n (maybe not needed?)
4.- place the huts block again in the same location / orientation without ordering to build them
5.- all seems good, backed colony data: /mc backup
6.- shutdown the server
7.- open problematic colony manager file whith nbtexplorer (minecolonies/colonyn.dat)
8.- Edit: the 'isBuilt:0'  to  'isBuilt:1', the 'level:0' - to previusly level, save
9.- Replace the backed file with the edited one
10.- start server, login to load colony (if no one logins in colony, restore didnt work)
11.- restore:  /mc colony loadbackup colony: n dimension: 0
12.- rehire same delivery mans, they recover their lvl

from there, played with that and it seems all delivery man problems got solved.  didnt see the NPE again in logs.  also, they are fullfiling requests correctly (using the mailbox to test). 

Considering what i've done, Do you thing its safe to keep playing with that?

**Comment by Raycoms** [comment]
The bug sounds weird, maybe the dmen had some old data in their hut causing issues. But yeah, what you did should be doing fine.

**Comment by GanthorPrime** [comment]
Not seeing this anymore in a server with 4 colonies. maybe related to an old worlds and many version updates. thanks for the help
