### ISSUE TITLE
Cactus / cactus seeds not listed in lumberjack (while all other species listed)

### ISSUE THREAD

**Issue by GanthorPrime** [ldtteam/minecolonies#3465]
### Minecolonies version

Version: minecolonies-1.12.2-0.10.212-ALPHA-universal

### Expected behavior

- Lumberjack can shop cactus in desert colonies to get cactus materials (used mainly in the sandstone style included in the mod)

- Support for cactus on the dynamic trees mod as the mod already support dynamic trees

### Actual behaviour

In lumberjack building, the tree selection page does not list vanilla cactus nor cactus seed from the dynamic trees while it shows all other saplings from vanilla and dynamic trees.

Note that using biomes o plenty and a dinamic trees compat for that, minecolonies also detect all saplings and seeds for BOP/Dynamic.

For cactus in dynamic trees, i think the logic for shoping is the same aplied for any tree: You get all cactus blocks and then replant a cactus seed if replant is activated (maybe it only need to be added to the list as other dynamic trees species).

For cactus in vanilla, maybe the logic need to be a little different, as theres no cactus sapling, and you need to maintain the lowest block for the cactus to grow again (or shop all and put one again as if where a sapling).  This same logic can be aplied to farm sugar canes so maybe it will be usefull for sugar farming.

### Steps to reproduce the problem

1. Build a Sandstone style colony
2. upgrade to latests Minecolonies versions
3. All buildings need cactus materials now, tons of it
4. Go to lumberjack to start a cactus gathering operation
5. No way for the lumberjack to gather cactus
6. Start getting cactus manualy
7. Cry.
8. Plan a cactus operation using the builder: scan a one block tall cactus field with air above, to get him farming cactus on rebuild
9. see the builder diying from catus on first harvest :(

**Comment by someaddons** [comment]
It is intentional that the lumberjack is not able to chop cactus, may be changed in the future.
