### ISSUE TITLE
Chisel and Bits Duplication issue

### ISSUE THREAD

**Issue by KasKatto** [ldtteam/minecolonies#3466]
### Minecolonies version
Version: 1.12.2-0.10.202-RELEASE

### Expected behavior
When using the builder to build schematics containing bitted? blocks (blocks that have been built with chisel and bits), the builder requests the amount of bits correctly and uses the bits to construct the blocks (ideally from a bits bag)

### Actual behaviour
The builder will place the blocks correctly (same pattern/ shape/ size/ material and position) BUT will do so out of thin air using NO bits. (even though the builder hut requests bits)

This can be easily abused to quickly duplicate blocks (most notably hard to obtain blocks) as the blocks can be turned back into bits by the player and use to reconstruct a full block.

![2019-03-05_11 25 34](https://user-images.githubusercontent.com/48245049/53802402-aa0a5380-3f39-11e9-970a-08c0c1c28953.png)
![2019-03-05_11 26 16](https://user-images.githubusercontent.com/48245049/53802403-aa0a5380-3f39-11e9-851b-ba1a3c95d19c.png)
![2019-03-05_11 26 33](https://user-images.githubusercontent.com/48245049/53802404-aa0a5380-3f39-11e9-9233-80c2a79a2e0d.png)
![2019-03-05_11 26 37](https://user-images.githubusercontent.com/48245049/53802405-aa0a5380-3f39-11e9-8698-dcaf32a42210.png)

### Steps to reproduce the problem

1)Join a server (i have only confirmed this on a server, but haven't tested on single player)
2)Create something out of chisel and bits in survival.
3)Use the scan tool to save the schematic.
4)Use the build tool to request the schematic to be built
5)The builder will start building without anything.
6)Profit from unlimited diamonds and infinity blocks

**Comment by Raycoms** [comment]
Can you please test this:
https://teamcity.minecolonies.com/guestAuth/repository/download/LetSDevTogether_Minecolonies_Branches_Build/25930:id/build/libs/minecolonies-1.12.2-0.10.797-PERSONAL-universal.jar
