### ISSUE TITLE
Builder wont place torches

### ISSUE THREAD

**Issue by Tydog** [ldtteam/minecolonies#3468]
### Minecolonies version

Version: 4.8.6

### Expected behavior

-  Builder wont't place torches

### Actual behaviour

-  Everytime my builder gets to the placing the torches stage of the build it never will. They just stand there with a different block in there hand even though the only thing they have left is torches

### Steps to reproduce the problem

1.  Place the building
2.  make builder work
3.  give materials
4. ... Profit

**Comment by RoyalReject** [comment]
Can confirm only on version 
minecolonies-1.12.2-0.10.215-ALPHA-universal.jar
I downgraded and builder finished the buildings

**Comment by Colmund** [comment]
I can confirm this behavior too. 
After i've upgraded to version 1.12.2-0.10.215-ALPHA the builder seems to have problems placing torches, Item Frames and other "finishing decorations". The info command shows, that the builder is in the SPAWN_STEP. Sometimes after ~30 Minutes the builder get it done.
This happens with different Buildings (fisherman, Blacksmith, Farm, Composter...)

**Comment by Nendreia** [comment]
I also had this issue, along with not placing carpet, and levers in the combat build.

**Comment by Raycoms** [comment]
fixed
