### ISSUE TITLE
[1.10.2] Placing down town hall does nothing - no GUI, no achievement, no colonists

### ISSUE THREAD

**Issue by b0bst3r** [ldtteam/minecolonies#347]
minecolonies-universal-1.10.2-0.6.2018

### Intended behaviour

 - Expected it to have a GUI, give you the achievement and have colonists

### Actual behaviour

- it does nothing, as per the title, breaking and replacing does nothing.

I know this is supposed to be fixed in this version, I'm wondering if there's a limit to the amount of towns a map can have and whether the 

Allow infinite placing of Supply Chests? 
B:allowInfiniteSupplyChests=true

Is somehow still limited?

Anything else we can try?

**Comment by Raycoms** [comment]
The townhall block places on your server but doesn't give you the
achievement neither gets opened?

2016-12-14 17:06 GMT-02:00 b0bst3r <notifications@github.com>:

**Comment by Raycoms** [comment]
Found the bug, fixing it and then uploading it.

2016-12-14 19:45 GMT-02:00 Ray Neiheiser <ray.neiheiser@gmail.com>:

**Comment by Raycoms** [comment]
Should be fixed in the last update, with build tool and by hand.
