### ISSUE TITLE
Schematic not working

### ISSUE THREAD

**Issue by SirPrijter** [ldtteam/minecolonies#3471]
### Minecolonies version

Version: 1.12.2-01.10.206-ALPHA

### Expected behavior

- My schematic to be accepted by the builder

### Actual behaviour

- Nothing happens, like clicking away. https://youtu.be/hkswj5JLaCg

### Steps to reproduce the problem

1. No clue

**Comment by walker-dev** [comment]
`[minecolonies]: handleDecoration: Could not build scans/new/Newest_Addition`

**Comment by Raycoms** [comment]
Is it a .nbt?

**Comment by SirPrijter** [comment]
No

**Comment by Raycoms** [comment]
Can you send me the scan?

**Comment by SirPrijter** [comment]
All of my schematics?

**Comment by Raycoms** [comment]
I'll check it out

**Comment by Raycoms** [comment]
It does work for me, can you send me one of the scans which isn't working?

**Comment by SirPrijter** [comment]
That's one of them
[Fucked schem.zip](https://github.com/ldtteam/minecolonies/files/2949507/Fucked.schem.zip)

**Comment by SirPrijter** [comment]
Relogging seems to work for one schematic

**Comment by Raycoms** [comment]
Weird, he built the lamp for me fine.

**Comment by SirPrijter** [comment]
I think it got patched with the new update, because I'm not facing the problem anymore

**Comment by Raycoms** [comment]
yay =) I'll close this then
