### ISSUE TITLE
Builder not avoiding cactus during build pathing (and diying)

### ISSUE THREAD

**Issue by GanthorPrime** [ldtteam/minecolonies#3472]
### Minecolonies version

Version: minecolonies-1.12.2-0.10.215-ALPHA-universal

### Expected behavior

Not sure, but by some testing, it appears citizens normaly avoid to walk over a cactus no matter its height. If not, then this is a request: 

During building, the builder must avoid to walk over a cactus block, just like in normal pathing.  Better yet, cactus blocks can be considered like fence blocks during normal walking: i never see a citizen pathing trought / over a fence  block. they do not try to walk over a fence block by any means.  

### Actual behaviour

When a builder starts to build, he choose different positions ramdonly to start building from. In this process they sometimes choose to walk over a cactus block (if there is a 1 block tall cactus in the area).
It appears he is not using the logic to avoid cactus used in other scenarios.  I just started to do some testing with some basic blueprints using cactus / fences, and it becomes more aparent that they are not treated same way during building.

### Steps to reproduce the problem

1. test1: scan a schematic containing 1 cactus block in a square arena area and include some layers of anything so builder keeps building after placing the cactus block.
2. test1: see how sometimes during building, he choose to walk over the cactus and continues building from there, then he dies
3. test2: try to build any schematic in an area where there is a 1 tall cactus block already
4. test2: see how sometimes during cleaning, he choose to walk over the cactus to keep cleaning and dies
5. test3: repeat all the previous tests using a fence block instead of a cactus
6. test3: you can see builder never paths on the fence block, no matters if it was there before the building or it was placed by the schematic

**Comment by Raycoms** [comment]
Closed in favor of joint issue.
