### ISSUE TITLE
Miner doesn't show required building materials

### ISSUE THREAD

**Issue by MatthiasMann** [ldtteam/minecolonies#3474]
Version: minecolonies-1.12.2-0.10.216-ALPHA-universal

### Expected behavior
Miner tells (via the requests page or a 3rd page in the hut like the builder) what materials are required to build the mineshaft

### Actual behaviour
Currently one has to guess which materials are required for him to continue building the mine shaft. 

I have a level 4 miner hut, the miner has an iron pick axe, shovel, 1 stack of cobble stone, ~50 oak wood planks, ~60 oak wood slabs, ~40 oak wood fences, ~20 ladders, ~40 torches but he is just standing around not doing anything after digging down one level below the starting mine shaft which came with the hut.

There are also no requests listed in the miner's UI.

### Steps to reproduce the problem
1. Not sure - I just build a miner hut and upgraded it to level 4
2. Hired a miner with ~5 on strength.
3. Gave him ladders, torches, pick axe and he did dig a hole and then stopped (and placed ladders).

**Comment by Daihok41** [comment]
I am having this same issue. Miner only dug one level down from the beggining and now has stopped. He has planks, slabs, fences, torchs, and ladders. He has pickaxe and shovel so not sure what else to try. He also has plenty of cobblestone as well.

**Comment by Raycoms** [comment]
what does his status say /mc citizens info ?

Am Mo., 25. März 2019 um 07:03 Uhr schrieb Daihok41 <
notifications@github.com>:

**Comment by Daihok41** [comment]
Says Desired Activity: Work 
Current Activity: Miner_Mining_Shaft

**Comment by Daihok41** [comment]
Ok for me it has something to do with the birch build i went and filled in everything dug and messed it all up he started rebuilding the mineshaft the way he wanted so when the builder make the place something is wrong. I had it built to lvl 4 and had to do this.

**Comment by Raycoms** [comment]
What exactly is the schematic name?

Am Mo., 25. März 2019 um 16:42 Uhr schrieb Daihok41 <
notifications@github.com>:

**Comment by Daihok41** [comment]
Just Birch Mine Was built at y65 and for some reason the miner wanted to start the mine at y67

**Comment by Raycoms** [comment]
which level?

Am Mo., 25. März 2019 um 17:23 Uhr schrieb Daihok41 <
notifications@github.com>:

**Comment by Daihok41** [comment]
I had it at Level 4

**Comment by Daihok41** [comment]
I am actually trying right now to reposition it 2 lvls higher see if miner starts working then.

**Comment by Raycoms** [comment]
what do you mean, 2 levels higher?

Am Mo., 25. März 2019 um 17:32 Uhr schrieb Daihok41 <
notifications@github.com>:

**Comment by Daihok41** [comment]
Ok that is what the problem is you have to raise the building up 2 lvls from where it originally places it.

**Comment by Raycoms** [comment]
Ohhh, you repositioned the Miner, yeah that can break it badly

**Comment by Daihok41** [comment]
Yea but in my case repositioning solved my problem. I raised the Mining Structure by 2 levels. Now the miner works away.

**Comment by Raycoms** [comment]
weird

Am Mo., 25. März 2019 um 19:19 Uhr schrieb Daihok41 <
notifications@github.com>:
