### ISSUE TITLE
Suggestion: Make it make it's own decisions

### ISSUE THREAD

**Issue by Knito58** [ldtteam/minecolonies#3476]
### Expected behavior
Minecolony is a helpful and resourceful place for the player with a lot of nice surprises.

### Actual behaviour
Havinng a mine colony is a pain in the a..  and not recommended for early game as it eats all of your resources. You're stuck here and stuck there and the mod still wants more of that cobble or dirt.

### Steps to reproduce the problem
Install it and build a colony in early game.

Suggestion: When a colony is started, there's a master plan. Which is engaged when the player does not intervent after one day. Any time when a project is finished and the player(s) don't decide anything for a specific amount of time (to be configurable) the colony decides by itself. This may result in buildings being placed where the player doesn't want them - but that would be the new risk. No risk, no fun.

Its very nice to have a colony. The building blocks are great! But it is not helpful at all. I wished I could place a colony in early game and then come visiting and get resources like wood or iron instead of having to feed them.

**Comment by Raycoms** [comment]
Very early on it does eat a bunch of resources as any mod which provides
utility. There is no free lunch. If you place a lumberjack, Miner and
fisherman they'll provide you with a lot without requesting toooo much
