### ISSUE TITLE
Blacksmith Medieval Oak Level 1 error

### ISSUE THREAD

**Issue by Colmund** [ldtteam/minecolonies#3478]
### Minecolonies version

Version: minecolonies-1.12.2-0.10.218-ALPHA

### Expected behavior

- 
Builder builds the medieval oak blacksmith building.

### Actual behaviour

- 
Builder stops before DECORATION_STEP in the SPAWN_STEP. The Server give following error Message:
[Server thread/ERROR] [minecolonies]: Pausing Entity Oswyn W. Compton (com.minecolonies.coremod.job.Builder) at BlockPos{x=-1290, y=71, z=2286} for 3200 Seconds because of error:
[22:58:28] [Server thread/INFO] [STDERR]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:331]: java.lang.NullPointerException
> 
[Server thread/INFO] [STDERR]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:331]: 	at com.minecolonies.coremod.entity.ai.util.StructureIterator.isAtPos(StructureIterator.java:441)
.
Pastebin Link for full error log: [Link](https://pastebin.com/AFp2WZ8c)

### Steps to reproduce the problem

1.  Build a Blacksmith Medieval Oak Level 1
2.  Let the Builder do his magic and wait until he stucks. Should be the time when he place carpets and torches.
3.  Log file report above error and builder is in SPAWN_STEP
4. ... Profit

**Comment by Raycoms** [comment]
Merged a fix for this a little bit of time ago.
