### ISSUE TITLE
Woodcutter and steps from the acacia.

### ISSUE THREAD

**Issue by ZzylinN** [ldtteam/minecolonies#3479]
Version:
minecolonies-1.12.2-0.10.220-BETA-universal
(it was in previous versions)

forge 1.12.2-14.23.5.2768
other mods

Map started on older versions of minecolonies-1.12.2.xxx

--------------------------------
Lumberjack stands and does nothing
The woodcutter is hampered by a block of steps from the acacia for moving to the place of felling trees!

The woodcutter stands and does nothing. The tree has grown!
![2019-03-09 (3)](https://user-images.githubusercontent.com/34644142/54066867-e69fbd00-4261-11e9-8beb-e499d93c42e2.png)

Steps from Akatsi on the route of the woodcutter
![2019-03-09 (4)](https://user-images.githubusercontent.com/34644142/54066881-22d31d80-4262-11e9-8302-e7f2d850e737.png)

Steps from acacia cut down
![2019-03-09 (5)](https://user-images.githubusercontent.com/34644142/54066888-439b7300-4262-11e9-9082-274daac1751c.png)

The woodcutter went to cut trees. When the steps were removed, the woodcutter was climbing blocks of land.
![2019-03-09 (6)](https://user-images.githubusercontent.com/34644142/54066902-5a41ca00-4262-11e9-9eb1-23d40e60ac7c.png)

**Comment by Raycoms** [comment]
So you mean the stair blocks of this mod don't work for our workers, right? Can you link the mod?

**Comment by ZzylinN** [comment]
Acacia wood stairs are not mod blocks. These are vanilla stairs from minecraft.

**Comment by Raycoms** [comment]
I confused it because you said "Akatsi" =D

Uhm, can you send me this world?

**Comment by ZzylinN** [comment]
world size ~ 400 Mb + to start saving, you also need the mods and config folder
Here is a link to the necessary files to run:
https://mega.nz/#!EfJlRAzB!Ry15wzELKNzlvo3uV6PSwHxwD2mjfY_Sr5gmJzzbKcg
PS: forge 1.12.2-14.23.5.2768

**Comment by Raycoms** [comment]
Should be able to download it from university this week =)

Am Sa., 9. März 2019 um 18:55 Uhr schrieb Sasha <notifications@github.com>:

**Comment by ZzylinN** [comment]
Good, thank you very much! :)
