### ISSUE TITLE
Intermittent crashing to title screen

### ISSUE THREAD

**Issue by Ladysarajane** [ldtteam/minecolonies#3481]
### Minecolonies version

Version: Modpack Minecolonies Official Pack version 4.8.6 
I think it is using minecolonies 1.12.2-0.10.215 alpha

### Expected behavior

Gameplay in single player should not crash to title screen during play
- 

### Actual behaviour

Intermittent crashing to desktop without notice....just suddenly while walking from one play to another in my colony my game crashes. 
[crash-2019-03-09_17.03.05-server.txt](https://github.com/ldtteam/minecolonies/files/2948888/crash-2019-03-09_17.03.05-server.txt)

- 

### Steps to reproduce the problem

Nothing particular causes it, just intermittent walking  and sprinting in the colony. Didn't have a problem with the earlier version of this modpack...just started when I upgraded the modpack to the 4.8.6. version
1. 
2. 
3. 
4. ... Profit

**Comment by Raycoms** [comment]
Got fixed in 216: https://minecraft.curseforge.com/projects/minecolonies/files/2684508
