### ISSUE TITLE
Feature request: add a page to citizens that show which level are for each work station that have been assigned to

### ISSUE THREAD

**Issue by critchards** [ldtteam/minecolonies#3484]
It would be great if I could tell which citizens had been workers or farmers or rangers when they are not currently assigned to those roles. That way if I send someone to get trained up at a library or archer/combat school and then forget what their job was before I dont have to go through building by building to find the one they are good at.

Suggest adding a 3rd page to citizen information, after happiness that shows job assignment history and level.

**Comment by lunadragnstar** [comment]
If a worker changes jobs, they lose all levels for a previous job.

**Comment by Raycoms** [comment]
they don't

Am Do., 28. März 2019 um 20:07 Uhr schrieb lunadragnstar <
notifications@github.com>:
