### ISSUE TITLE
[Feature Request] Cubic Chunks Compatibility

### ISSUE THREAD

**Issue by CrioChamber** [ldtteam/minecolonies#3486]
Greetings:

  There is a mod currently for Minecraft 1.12.2 compatible with forge that allows for Y height to act the same way as Z and X in Minecraft in that Y is now infinite. The problem is for most mods is that they are programmed for the standard Y = 0-256 height range, meaning  for most anything outside of those boundaries are either not run or mishandled by most mods.

  How it works:
Cubic Chunks divides the current 0-256 Y range into 4 pieces for regions, then divides those into 2 for the height chunks for pre-existing worlds, and continues this for all height elevations; essentially creating a 3D 16x16x16 chunk grid left-right-up-down into infinity instead of the current 16x16 2D grid left-right into infinity with a highest height of 256 and lowest height of 0. Cubic Chunk worlds are processed normally as any other world as well, with the exception of the bedrock layer and being able to go below Y level 0 and go above Y level 256.

How do the developers of Cubic Chunks cope with memory? Chunks that are 'Vacant' are marked with a boolean value; if that boolean value is 1, the rest of the chunk's file is ignored so kept unloaded. A 'Vacant' chunk is a chunk that has neither blocks nor entities inside of them. They have also implemented a vertical render distance so that not everything below and above is rendered, instead vertical chunks are rendered similarly to horizontal chunks.

  How Minecolonies can support this mod:
Minecolonies can support this mod by implementing a Cubic Chunks compatible version with AI and positional commands being rewritten to allow for near-infinite height elevations. There may be some other technicalities that I am unaware of to support Cubic Chunks's infinite height at this time.

Notes:
Cubic Chunks does have a CurseForge, if that helps at all.

Thanks,
CrioChamber

**Comment by Raycoms** [comment]
The question is, what is not working?

**Comment by Raycoms** [comment]
Will be added to a new joint mod compat issue.
