### ISSUE TITLE
Miner problem

### ISSUE THREAD

**Issue by VarezQ** [ldtteam/minecolonies#3487]
### Minecolonies version

Version:  1.12.2-0.10.222-ALPHA with Minecraft forge 14.23.5.2815

### Expected behavior

- Miner working independently 

### Actual behaviour

-  Miner idling by his hut without any request and the only way to make him mine down is to place ladder with block underneath then he will mine just that plane

here are logs:
[latest.log](https://github.com/ldtteam/minecolonies/files/2951998/latest.log)
[2019-03-10-5.log.gz](https://github.com/ldtteam/minecolonies/files/2951999/2019-03-10-5.log.gz)
[2019-03-10-6.log.gz](https://github.com/ldtteam/minecolonies/files/2952000/2019-03-10-6.log.gz)
[2019-03-10-4.log.gz](https://github.com/ldtteam/minecolonies/files/2952001/2019-03-10-4.log.gz)

### Steps to reproduce the problem

1. Have minecraft with minecolonies
2. Build miner
3. ... Profit

**Comment by Raycoms** [comment]
what miner style?

**Comment by VarezQ** [comment]
> what miner style?

i belive it is medival oak, i cant confirm it right now but it is most likely that style cause i used it in almost every building

**Comment by Raycoms** [comment]
did you try to give him ladders?

**Comment by VarezQ** [comment]
Of course. I gave him ladders, pickaxes, food, torches, sign, cobblestone, cobble stairs, slabs, walls. I even gave him oak planks, fence and slabs beacuse i through that he will use them in this style

**Comment by Raycoms** [comment]
weird, he is working fine for me

Am Di., 12. März 2019 um 09:16 Uhr schrieb VarezQ <notifications@github.com

**Comment by VarezQ** [comment]
I will check it on another world then when i get back home and post results here. Meaby something went wrong while building this one idk

**Comment by VarezQ** [comment]
Ok i managed to fix the problem by destroying old mine and build new one from scratch. I have no idea what caused that bug but if you want to search for anwer i can provide you logs, map save or whatever you need to find it. Case closed i guess

**Comment by VarezQ** [comment]
Nvm it happend again. He stoped at building first node and i have no idea why.

**Comment by Raycoms** [comment]
If you know how to reproduce it, tell us =D

Am Di., 12. März 2019 um 17:21 Uhr schrieb VarezQ <notifications@github.com

**Comment by VarezQ** [comment]
No idea really

**Comment by VarezQ** [comment]
[latest.log](https://github.com/ldtteam/minecolonies/files/2958651/latest.log)
[2019-03-11-2.log.gz](https://github.com/ldtteam/minecolonies/files/2958652/2019-03-11-2.log.gz)
[2019-03-11-3.log.gz](https://github.com/ldtteam/minecolonies/files/2958653/2019-03-11-3.log.gz)
[2019-03-11-1.log.gz](https://github.com/ldtteam/minecolonies/files/2958654/2019-03-11-1.log.gz)
[2019-03-10-5.log.gz](https://github.com/ldtteam/minecolonies/files/2958655/2019-03-10-5.log.gz)
[2019-03-10-6.log.gz](https://github.com/ldtteam/minecolonies/files/2958656/2019-03-10-6.log.gz)
here are logs 

https://drive.google.com/file/d/1dxlH7xGfydOY0iDHyC8FeTsZm9N5IX0m/view?usp=sharing
here are save

https://drive.google.com/file/d/1z9DPm0MtfyM5NRAsRGQZpNxrZQF417Az/view?usp=sharing
and here is mod folder

if you need anything else just let me know

**Comment by Raycoms** [comment]
I'll close it for now until I got a way to reproduce it
