### ISSUE TITLE
Accidental Silktouch?

### ISSUE THREAD

**Issue by Justen-N** [ldtteam/minecolonies#3488]
### Minecolonies version
minecolonies-1.12.2-0.10.202-RELEASE-universal

Version: 

### Expected behavior
Coal and other mined ores drop the associated item for the miner, not the ore itself. 

### Actual behavior
No logs, just wondering if silktouch was intended behavior for the miner. At the moment, I am getting coal ore, not coal. 

### Steps to reproduce the problem

1. create a level one miner
2. Have them find coal ( hopefully quickly)
3. They mine the silktouched block, not the coal itself
4. ... Profit

**Comment by Raycoms** [comment]
Actually, it's the random reward generation which gives them the blocks like "silk touch" which is on purpose =) When they actually mine ores they will get them correctly.
