### ISSUE TITLE
Is this desired behavior

### ISSUE THREAD

**Issue by Howman** [ldtteam/minecolonies#3490]
### Minecolonies version
minecolonies-1.12.2-0.10.223-ALPHA-universal

Version: 

### Expected behavior
stone smeltery, stone cutter, Blacksmith to work,  request stuff, make things
### Actual behaviour
They do nothing
Out of all the workers these 3 (stone smeltery, stone cutter, Blacksmith) do nothing, request nothing, and usually do not move to far from there bed. They gain no levels .  

More of a question about  stone smeltery, stone cutter, Blacksmith is this desired behavior until l add some recipes?? Should there be a default like the crusher, sifter?  

### Steps to reproduce the problem
Just build building and colonist gets assigned then bingo bango you got a colonist assigned to a job that does absolutely nothing.

**Comment by Raycoms** [comment]
yeah, on purpose there is no default. You can let them work via requests from other workers or via the postbox.
