### ISSUE TITLE
Create a command, /mc raidinfo or whatever, that will tell you the coordinates of where the barbarians spawned and how many are in the raiding party.

### ISSUE THREAD

**Issue by CuriousCam** [ldtteam/minecolonies#3492]
### Minecolonies version

Version: 

### Expected behavior

- 

### Actual behaviour

- 

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit

**Comment by Asherslab** [comment]
please use the issue format correctly, and explain what you want further

**Comment by Raycoms** [comment]
You can see this information in the barracks level 3+

Am Di., 12. März 2019 um 18:38 Uhr schrieb Marc Hermans <
notifications@github.com>:
