### ISSUE TITLE
On version 0.10.230 stopped building a builder.

### ISSUE THREAD

**Issue by ZzylinN** [ldtteam/minecolonies#3498]
Version:
minecolonies-1.12.2-0.10.230-BETA-universal

forge 1.12.2-14.23.5.2768
other mods

Map started on older versions of minecolonies-1.12.2.xxx

-----------------------------

After upgrading to version 0.10.230, I stopped building a builder. it is not possible to clear the request sheet in the builder’s hut (canceled the request to upgrade the baker’s building in the baker’s building and town hall, but the request sheet wasn’t cleared anyway).
used the command:  /mc rs reset colony: 1, but it did not help.

**Comment by Raycoms** [comment]
The sheet only gets cleared once the builder actually starts the new task,
so not when it rains, barbarians attack, they mourn, etc

**Comment by ZzylinN** [comment]
The builder does not work at all.
I canceled the construction (upgrade) of the building. But the list of necessary items and blocks for the upgrade was not cleared. I'm talking about it.

**Comment by ZzylinN** [comment]
I play in the world that threw you in the issues # 3479

**Comment by Raycoms** [comment]
Oh yeah, I didn't get to download it yet. Internet at home is terrible atm

Am Sa., 16. März 2019 um 10:26 Uhr schrieb Sasha <notifications@github.com>:

**Comment by Raycoms** [comment]
fixed

**Comment by ZzylinN** [comment]
I use version 0.10.236, but the builder is standing, he is waiting for something.
![2019-03-25](https://user-images.githubusercontent.com/34644142/54908691-afdcce80-4f12-11e9-8ab9-b197d3091741.png)

The builder has nothing in the queries.
![2019-03-25 (1)](https://user-images.githubusercontent.com/34644142/54908715-bbc89080-4f12-11e9-98db-d7a1ff75f84f.png)

The construction task is available
![2019-03-25 (2)](https://user-images.githubusercontent.com/34644142/54908769-d6026e80-4f12-11e9-9334-fe291043d0c2.png)

Nothing was written to the chat from the builder
![2019-03-25 (3)](https://user-images.githubusercontent.com/34644142/54908884-17931980-4f13-11e9-9ad9-a528557080d4.png)

**Comment by Raycoms** [comment]
Is he standing for forever, or just for some time, maybe he is scanning the
inventories.

Am Mo., 25. März 2019 um 06:31 Uhr schrieb Sasha <notifications@github.com>:

**Comment by ZzylinN** [comment]
I waited 10 minutes, but the builder did not do anything, once he slowly left the builder’s hut to block 6 and ran back. After standing and doing nothing.

**Comment by Raycoms** [comment]
Did you try to fire/re-hire him?

Am Mo., 25. März 2019 um 13:55 Uhr schrieb Sasha <notifications@github.com>:

**Comment by Raycoms** [comment]
and, is there log output?

Am Mo., 25. März 2019 um 13:56 Uhr schrieb Ray Neiheiser <
ray.neiheiser@gmail.com>:

**Comment by ZzylinN** [comment]
before that, he built a house and behaved in the same way. I myself brought him the necessary resources (although there were no requests from him) and he continued to build. And then I decided to see if the builder would request resources and rendered it just worth it.

Like I tried to fire and re-hire and it did not help.
I can send logs only tomorrow.

**Comment by ZzylinN** [comment]
I apologize for the inconvenience.
Today included minecraft, miracle !, the builder began to build!
I do not know what happened to him.
