### ISSUE TITLE
Cavecolonies: barbs spawning on bedrock

### ISSUE THREAD

**Issue by faeythinpixels** [ldtteam/minecolonies#3499]
### Minecolonies version
minecolonies-1.12.2-0.10.228-ALPHA-universal.jar

Version: 

### Expected behavior
 

- 
Barbarians not spawning on bedrock at the top of the world.

### Actual behaviour

- 
Barbarians are spawning on top of the bedrock in the stoneblock-style world.

### Steps to reproduce the problem

.
1. Play CaveColonies pack and build until raiding parties start
2. carefully check journey map for barbarians
3. sometimes they are spawning on top of the bedrock layer at the top of the world.
4. ... Profit

**Comment by Asherslab** [comment]
ooooh... that's going to be difficult to fix, well.. properly.... great XD

**Comment by spacewolfcub** [comment]
Top of world bedrock is like, y 255?
Would it be easier to say Barbarian spawns are not allowed above y 253 ?

**Comment by Raycoms** [comment]
we could even say not over 200

Am Sa., 16. März 2019 um 20:43 Uhr schrieb spacewolfcub <
notifications@github.com>:
