### ISSUE TITLE
Crash with build tool

### ISSUE THREAD

**Issue by Raycoms** [ldtteam/minecolonies#350]
### Minecolonies version
All the newest ones 1.10 and 1.11

### Actual behaviour

- Use build tool -> switch to decoration mode -> switch back to hut mode. Still able to switch decoration style. That shouldn't be possible.

**Comment by xenoflot** [comment]
Heh, I was about to point out that you should add a crashlog then I realised it was you :-)

Here's mine! http://pastebin.com/meiiFQCQ

minecolonies-1.10.2-0.6.2038

**Comment by Raycoms** [comment]
Created a fix will upload as soon as Internet is back

Am Mittwoch, 21. Dezember 2016 schrieb xenoflot :

**Comment by xenoflot** [comment]
Great! Looking forward to it!

**Comment by Raycoms** [comment]
Should be good with this build:
https://minecraft.curseforge.com/projects/minecolonies/files/2360011

2016-12-24 18:25 GMT-02:00 wafflebot[bot] <notifications@github.com>:

**Comment by xenoflot** [comment]
Looking good to me, thank you! I didn't spam click it but I alternated around a bit between deco and huts and other buttons and no kaboom!
