### ISSUE TITLE
Builder is digging not actually building

### ISSUE THREAD

**Issue by Kabbozo** [ldtteam/minecolonies#3501]
Version: 
1.12.2-0.10.232-ALPHA
### Expected behavior
The builder actually builds something
### Actual behaviour
I gave the builder all the resources and tools that they asked for, and for some reason they decided to dig a hole instead of actually build. Its mildly infuriating because now I have a big hole in my survival world, my only solution is to just not give the builder a shovel otherwise they keep digging.

![2019-03-18_01 47 59](https://user-images.githubusercontent.com/48669736/54512030-da31f900-4920-11e9-960c-434a1165aea8.png)

### Steps to reproduce the problem
1. Make the supply boat thing
2. Create townhall template, can't build it until builders hut is made
3. Try to make builders hut, give all resources needed and wooden shovel asked for
4. Builder digs hole???

**Comment by spacewolfcub** [comment]
Did you place the Builder Hut using the Building Tool?
Or did you put the Hut on the ground and then right click inside it to tell it to build?

If you placed it on the ground by hand, which style did you choose to build?

If the schematic is incorrect, we cannot find the problem without knowing these answers. Huts were never meant to be placed by hand, only with the Building Tool so you can see a preview of the building and place it correctly. It is likely that the style you chose has the Hut block high up off the ground, so the BuilderNPC is digging out the dirt so it can build what the schematic tells her to. 

We won't know until we get your answers.

**Comment by Kabbozo** [comment]
I will try that in the morning. There’s a good chance I placed it by hand.

**Comment by Kabbozo** [comment]
> Did you place the Builder Hut using the Building Tool?
> Or did you put the Hut on the ground and then right click inside it to tell it to build?
> 
> If you placed it on the ground by hand, which style did you choose to build?
> 
> If the schematic is incorrect, we cannot find the problem without knowing these answers. Huts were never meant to be placed by hand, only with the Building Tool so you can see a preview of the building and place it correctly. It is likely that the style you chose has the Hut block high up off the ground, so the BuilderNPC is digging out the dirt so it can build what the schematic tells her to.
> 
> We won't know until we get your answers.

Ok so I placed the builder hut using the tool, but then I still need to select what they need to build by clicking through it. Whenever I did that, my builder kept on digging.

**Comment by Raycoms** [comment]
Should be fixed in newest, else reopen

**Comment by forry** [comment]
(Edit)
My bad. I have not realized that the builder's hut had such an extensive cellar :-O.

Hi, same problem here.  I did try to place it several times using the wand (and was otherwise following the wiki, I think). Builder is still digging down to hell. It could be even useful if it wasn't too slow :).
Minecraft 1.18.1
Mine Colonies 1.0.455-BETA
ModPack Moonlit Myths 4.10-1

**Comment by MotionlessTrain** [comment]
This is a very old github issue (3 years old!), and as such not relevant at all anymore.

For the next time, please ask on discord (https://discord.minecolonies.com) for support, or open a new issue if you are sure you encounter a similar bug
