### ISSUE TITLE
[BETA 209] Crafting Recipe of Barracstower Placeholder messed up

### ISSUE THREAD

**Issue by Shandoo94** [ldtteam/minecolonies#3502]
### Minecolonies version
0.10.209-BETA

### Expected behavior
Normal crafting of Barracstower Placeholder

### Actual behaviour
The displayed item in JEI looks normal, but the displayed recipe in the gui looks like in the added image (see recipe in center and normal block in JEI-interface on the right).
Crafting the placeholder like this yields a pink square. Cheating the placeholder in via JEI yields the normal block

![2019-03-19_10 24 10](https://user-images.githubusercontent.com/21018028/54595071-30db2800-4a32-11e9-9e99-949b57768fe8.png)

### Steps to reproduce the problem
1. looking the recipe up in JEI
2. crafting the block

**Comment by spacewolfcub** [comment]
You're not supposed to craft the block, to be honest. 
In recent versions, the Builder asks for it and other placeholder items -- ignore that. When it comes time to place them, the Builder will place the correct invisible item or produce the correct visible item that you can interact with once the parent building is finished. 

Placeholders have recipes in case for some incredibly strange reason you decide to make (in this case, a new Barracks and BarracksTower) Hut schematics in survival mode. Every schematic designer I have met so far builds in creative mode, and most often in single player.

**Comment by Shandoo94** [comment]
I see, thanks for the help.

**Comment by Raycoms** [comment]
There is not even supposed to be a recipe =O

Am Di., 19. März 2019 um 08:02 Uhr schrieb Shandoo94 <
notifications@github.com>:

**Comment by Shandoo94** [comment]
Ok, well all placeholderblocks have recipes if I remember correctly.

**Comment by Nightenom** [comment]
https://github.com/ldtteam/minecolonies/blob/version/1.12/src/main/resources/assets/minecolonies/recipes/blockBarracksTowerSubstitution.json
hmm xD, this is a technical placeholder (not meant to be used in survival at all)

**Comment by Asherslab** [comment]
yeah and frankly i believe i never implemented it.
@Nightenom can you remove the recipe for me plz? even unregister the block for now (just comment out that line)

**Comment by Asherslab** [comment]
if you want to implement it that'd be even better. i believe most of the code is commented out in the barracks hut code

**Comment by Asherslab** [comment]
wait a second, apparently i did implement it. 
wow, huh. okay XD

**Comment by Raycoms** [comment]
Asher, don't unregister this block, I fixed the block and it is working for
the barracks now =D

Am Di., 19. März 2019 um 19:04 Uhr schrieb AshersLab <
notifications@github.com>:

**Comment by Asherslab** [comment]
@Raycoms yeah i saw that =P
