### ISSUE TITLE
Baker "issus"

### ISSUE THREAD

**Issue by yiumail** [ldtteam/minecolonies#3505]
### Minecolonies version

Version: minecolonies-1.12.2-0.10.232

### Expected behavior

- 
baker request only 1 bucket of milk instep of 3 in making cake process. 
this make baker stop working until player given the rest 2 buckets of milk.  
 

### Actual behaviour

- 

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit

**Comment by usafphoenix** [comment]
similar to my issue with the builder. the "delivery man" seems to only deliver a single "stack" of items even though it should be able to deliver a chest's worth of inventory. this slows EVERYTHING way down.

**Comment by Raycoms** [comment]
Should be fixed in newest, else reopen
