### ISSUE TITLE
Crash on latest ALPHA and RELEASE too.

### ISSUE THREAD

**Issue by MesterDavid** [ldtteam/minecolonies#3506]
### Minecolonies version

1.12.2-0.10.202-RELEASE
AND (same problem)
1.12.2-0.10.234-ALPHA  

### Actual behaviour

Fully random crash.
if minecolonie village is loaded.

nothing more. (or i dont know)

### Steps to reproduce the problem

1. PLAY
2. PLAY
3. and Boom... random crash. 

Please help me.
One mod is wrong for this? Or it is a simple bug?

1.12.2-0.10.234-ALPHA report:
[crash-2019-03-20_21.00.58-server.txt](https://github.com/ldtteam/minecolonies/files/2990076/crash-2019-03-20_21.00.58-server.txt)

1.12.2-0.10.202-RELEASE report:
[crash-2019-03-20_21.42.49-server.txt](https://github.com/ldtteam/minecolonies/files/2990077/crash-2019-03-20_21.42.49-server.txt)

Thanks.
David

**Comment by Raycoms** [comment]
Please set the updateRate in the configuration file to at least 1, or else these crashes happen. (You increase for performance not decrease)
