### ISSUE TITLE
Citizen3 House causing builder to go into activity "SPAWN_STEP"

### ISSUE THREAD

**Issue by Madelyficent** [ldtteam/minecolonies#3508]
Newest version of CaveColonies

### Expected behavior
Builder actually building the rest of Citizen3

Builder should completely build citizen 3.

### Actual behaviour
Builder never completes Citizen3

Builder builds Citizen3 almost fully until the armor stand is next in queue.

### Steps to reproduce the problem

1. Get a citizen2 and a builder3
2. Upgrade the citizen2 to a citizen3, and wait for the armor stand
3. do /mc citizens info colony: 1 citizen: (Citizen Name) and it should say that the current activity is SPAWN_STEP
4. ... Profit

**Comment by Nightenom** [comment]
more than a builder...

**Comment by Madelyficent** [comment]
well ive tried everything, replacing the worker, replacing the hut, i even started a new citizen house to see if it was just that one home
but it wasnt

**Comment by Raycoms** [comment]
@Wissi did you update it already?

**Comment by Wissi** [comment]
Latest CaveColonies is ver 2.1
And using minecolonies-1.12.2-0.10.234-ALPHA-universal.jar (which is the latest to this day.)
Was updated 3 days ago as soon as the file was available.

**Comment by Raycoms** [comment]
found a fix
