### ISSUE TITLE
[feature request] trash can

### ISSUE THREAD

**Issue by kreezxil** [ldtteam/minecolonies#3509]
Warehouses could use a trash can.

IDEA: a trash can object, that is part of all the warehouses. 
DESCRIPTION: 
level 1: has 9 slots
level 5: has 64 slots
each slot holds a ghost item or 1 real item, your choice as to how to code it.
if any item is brought in to the warehouse matching the items in the trash can it is deleted from the game.
the player will set the items in the can.

see also #2953

**Comment by Raycoms** [comment]
Closed in favor of #1635 which suggests it already
