### ISSUE TITLE
Crashing Server

### ISSUE THREAD

**Issue by Falcon7617** [ldtteam/minecolonies#351]
### Minecolonies version: Current

version X.X.XXXX or curse X.X.XX

### Expected behavior

- Entire server shouldn't crash

### Actual behaviour

- While out exploring, I came across 2 very old colonies, upon their discovery . . . server crash.

### Steps to reproduce the problem

1. Explore
2. Search
3. Eventually find an old colony
4. SERVER CRASH!

**Comment by Raycoms** [comment]
I have the fix ready I will upload it within the next hours.

2016-12-17 9:30 GMT-02:00 Falcon7617 <notifications@github.com>:

**Comment by Falcon7617** [comment]
Thanks

**Comment by Raycoms** [comment]
Uploaded it to the server you can now join again.

2016-12-17 9:31 GMT-02:00 Falcon7617 <notifications@github.com>:
