### ISSUE TITLE
Guards never able to wear Iron or Diamond armor

### ISSUE THREAD

**Issue by bjfranks** [ldtteam/minecolonies#3510]
### Minecolonies version

Version: 1.12.2-0.10.202-RELEASE
1.12.2-0.10.234-ALPHA similar

### Expected behavior
At some point of upgrade for a GuardTower or BarracksTower, Knight or Rangers could wear iron armor, or perhaps even diamond armor.

### Actual behaviour
Until level 4 minimum armor: leather maximum armor:chain, at level 5 minimum armor:gold maximum armor:chain

Unable to make Guards wear Iron armor in any configuration, basically no reason to upgrade tower to level 5

### Steps to reproduce the problem
1. Build Builders Hut Level 5
2. Build GuardTower Level 5
3. Remove requests from GuardTower
4. Recheck requests from GuardTower

**Comment by Talyda** [comment]
Armour depends on both tower level AND guard level. There's a chart on the wiki
https://wiki.minecolonies.com/source/systems/workerinfo
They need to be minimum level 5, with a minimum level 3 tower to wear iron armour.

**Comment by Nightenom** [comment]
If you are still unable to get them using a better armor please reopen

**Comment by GanthorPrime** [comment]
I can confirm part of this report

From my experience and testing: guards can use diamond armor, at least in lvl 5 tower, when they reach lvl 15. 

The problem i can confirm is with the enchanted pieces. It seems that the level / ammount of the enchants can stop a guard from using some armor.  As for diammond, in some scenarios, you can only provide unenchanted diammond armor, and in other sceenarios, you can provide any enchant.

With that said, i never found an scenario where you can provide enchanted iron armor. even in an lvl 5 tower, you cant provide enchanted iron armor to the guard no matters is lvl, the lvl of the enchant or the ammount (tested guards bellow lvl 30 in a lvl 5 tower to match table ).  This is not a problem with iron swords so there must be a bug for the iron armor.
