### ISSUE TITLE
Town Hall Cant Be Crafted

### ISSUE THREAD

**Issue by JuddSamurai** [ldtteam/minecolonies#3512]
Version: 
Release 4.8.7
minercft 1.12.2
 What would you expect to see if this feature was working as intended? -->
Being able to craft a town hall
To start the game properly you have to build a town hall. And you are suppost to be able to craft this in a crafting table, with a crafting recipe
 What actually happens when this feature is used in it's current state? 
 However, it is not working this way, instead you can see the town hall item in just enough items, and the book on the table itself however when you put the recipe in it does not show the item in the output spot. You can not take this invisible item either.
![Screenshot (39)](https://user-images.githubusercontent.com/48883485/54880056-79328580-4e38-11e9-9266-e893984869d4.png)
What should we do to make this issue show up in our own game? 

1. get items for it
2. open a crafting table
3. try crafting a town hall
4.and it wont show up

**Comment by Raycoms** [comment]
Townhall is only craftable when you placed the camp or ship
