### ISSUE TITLE
No Birch Library Schematics

### ISSUE THREAD

**Issue by GrokDuckFarmer** [ldtteam/minecolonies#3515]
### Minecolonies version
Version: 1.12.3-0.10.236-ALPHA

### Expected behavior
Building a library gives me a Birch wood option.

### Actual behaviour
There are no options for Birch libraries.  The options jump from Acacia to Dark Oak.

### Steps to reproduce the problem
1. Run Minecraft with latest MineColonies build
2. Establish a Minecolonies town
3. Craft a Library block from MineColonies.
4. Use the Building Tool to show all the build options for the Library.
5. Notice that the Library options jump from Acacia to Dark Oak.
6. Cry buckets of tears that your Birch-themed town won't have a Birch Library.
7. Build one out of stone, but be sad.

**Comment by Raycoms** [comment]
Yeah, our schematics are community based, if you send us a nic ebirch library we can include it, please keep this here for code issues or broken schematics
