### ISSUE TITLE
BUG ISSUE PLEASE READ!

### ISSUE THREAD

**Issue by chuckdafox** [ldtteam/minecolonies#3516]
### Mine colonies version

Version: 
0.10.236 
### Expected behavior

-  being able to craft the town hall

### Actual behavior

-  i put the recipe in and nothing happens yes i do have the mod installed

![2019-03-26_21 20 23](https://user-images.githubusercontent.com/48971896/55043800-33c7b100-500e-11e9-9056-dbfe69e91603.png) 

### Steps to reproduce the problem

1. put in the two builders wands on top slot and middle slot 
2.  surround this by VANILLA mine craft wood
3.  craft the town hall
4. ... Profit um profit?

**Comment by chuckdafox** [comment]
![2019-03-26_21 33 57](https://user-images.githubusercontent.com/48971896/55043971-e435b500-500e-11e9-83c3-1d76a02701d5.png)

**Comment by chuckdafox** [comment]
this is the recipe that jei gave me it could be wrong just thought you would want to fix that

**Comment by Talyda** [comment]
You can only craft the Town Hall if you have already received one (and lost it at some point) from the supply camp, or supply ship. Still need to craft either of those two things to receive it normally - it's there as an emergency thing in case you accidentally delete it.

**Comment by Raycoms** [comment]
Yes @Talyda is right. We'll add this to the wiki too @lunadragnstar @Wissi

**Comment by lunadragnstar** [comment]
I believe I've added that to the wiki, just waiting on reviews.
