### ISSUE TITLE
Crashes when Barbarian attack is initiated.

### ISSUE THREAD

**Issue by Zaniun** [ldtteam/minecolonies#3517]
### Minecolonies version

Version: 1.12.2-0.10.236-ALPHA

### Expected behavior

- I would expect the game not to crash and the barbarian attack to actually happen

### Actual behaviour

- Game crashes. https://paste.dimdev.org/poxajocare.mccrash

### Steps to reproduce the problem

1. Start a new world
2. Upgrade to have at least 5 or more npcs
3. Game crashes as soon as a barbarian attack is supposed to happen
4. ... Profit

**Comment by Raycoms** [comment]
fixed
