### ISSUE TITLE
Farm looses food

### ISSUE THREAD

**Issue by critchards** [ldtteam/minecolonies#3518]
Version: minecolonies-1.12.2-0.10.234-ALPHA-universal

### Expected behavior
Farmer drops inventory into farm block.

- 

### Actual behaviour
Farmer comes to farm block with wheat in inventory, hangs out for a bit, leaves with no wheat and the farm block is empty. I dont have a warehouse or deliverymen yet so no one is taking the wheat.

If I manually place stuff in inventory it stays so I am guess its got something to do with the farmer dropping his inventory off.

### Steps to reproduce the problem

1. Have a farmer
2. Farmer has wheat in inventory
3. Farmer drops it off at farm
4. Farm has nothing in inventory.

**Comment by Grummelkater** [comment]
Are there racks or chests in the building? Workers use them as well, they don’t necessarily drop their stuff in the hut block.

**Comment by critchards** [comment]
Nope, no other storage locations. It's a lv1 medieval oak farm.On Mar 27, 2019 1:18 AM, Grummelkater <notifications@github.com> wrote:Are there racks or chests in the building? Workers use them as well, they don’t necessarily drop their stuff in the hut block.

**Comment by Rosomah** [comment]
I think I have the same issue. I built a medieval oak farm and the farmer is not collecting any wheat (in a way). The seed stack is getting bigger, but there is no wheat at times in his inventory. When I manually place a wheat item in his inventory, he starts stacking or gathering it. I don't know what triggers him to lose the wheat and stop gathering it, but at times when I go check the farmer out, he doesn't have any wheat in the inventory, neither does he have it in the chest.

**Comment by mykepwnage** [comment]
I have this issue as well. 

There _is_ another storage.  If I place a Tinker's Table beside the farm interface, I'm able to find the "missing" wheat and put it in my inventory

However, doing this makes it seem like you've lost your inventory, but you can get it back (and the wheat) if you go back into the farm block and check it's inventory.

**Comment by Rosomah** [comment]
Where is this storage though? Can the deliveryman access it?

**Comment by marchermans** [comment]
@Rosomah @mykepwnage  Interesting @Raycoms We have (at least as far as I know) no hidden inventories anywhere, all our blocks are simply chests and behave as such, have a ui for them etc.

**Comment by Rosomah** [comment]
I've made myself a deliveryman and he brought the missing wheat to the warehouse, but I still can't figure out where he took it from, cause before making the deliveryman there was only a stack of wheat and some seeds in the Farm chest and now there's 5 stacks of wheat in the warehouse.

**Comment by marchermans** [comment]
Interesting, I have to say that I am running into this phenominon my self sometimes during debugging, allthough in all cases it turned out, i was just blind. @Raycoms Maybe we can do something about this and somehow add a find item option?

**Comment by Raycoms** [comment]
Should be fixed in newest, else reopen
