### ISSUE TITLE
Lumberjack seems to want to alway cut down the Betweenlands portal tree.

### ISSUE THREAD

**Issue by thakyZ** [ldtteam/minecolonies#3522]
### Minecolonies version

Version: 
MineColonies 0.10.202-RELEASE
Minecraft 1.12.2
Forge 14.23.5.2823
The Betweenlands 3.4.6

### Expected behavior

- The lumberjack should not ever cut down the portal to the betweenlands.

### Actual behaviour

- The lumberjack decides it's a great idea to cut it down, leaving the frames behind as they aren't as useful but the blocks for the tree seem to count as wood.

![2019-03-28_05 58 41](https://user-images.githubusercontent.com/950594/55159812-1e8e7780-511f-11e9-9803-49b526d63c80.png)
![2019-03-28_05 59 15](https://user-images.githubusercontent.com/950594/55159818-20f0d180-511f-11e9-8d69-8e5043c6fb42.png)

### Steps to reproduce the problem

1. Make a colony and hire a lumberjack
2. Place any regular sapling in range for the lumberjack but far enough away for the tree to spawn.
3. right click the sapling with the swamp talisman from the betweenlands.
3. wait for the lumberjack to walk to the tree and start cutting.

NOTE: the lumberjack doesn't seem to always go for it right away, but maybe when there are no trees around it cuts it down?
4. ... Profit

**Comment by Raycoms** [comment]
You should be able to disable this on the second page of his GUI

**Comment by thakyZ** [comment]
No there is no option as you can see here:
(The leaves happen to be weedwood leaves)
![2019-03-28_06 20 09](https://user-images.githubusercontent.com/950594/55160905-9362b100-5121-11e9-8b2f-ed8d9b7574c8.png)

**Comment by Raycoms** [comment]
Ah, it's not a specific sapling, right?

Am Do., 28. März 2019 um 10:20 Uhr schrieb Neko Boi Nick <
notifications@github.com>:

**Comment by thakyZ** [comment]
No it's created via using a wand on any sapling, also all the saplings are off except birch

**Comment by marchermans** [comment]
You will need to put cobblestone under the entire tree then.
The LJ detects a woodblock in a tree like structure and tries to chop it down.

**Comment by marchermans** [comment]
Closing nothing we can do. Place cobble under the tree to prevent chopping.
