### ISSUE TITLE
Workers are constantly moving in between homes/work.

### ISSUE THREAD

**Issue by Purevega** [ldtteam/minecolonies#3524]
### Minecolonies version

Version: Latest

### Expected behavior

- Workers traveling to their places of work (Fishing hut/Mine/Farm) after sleeping at night, and staying there for the day.

### Actual behaviour

- Workers will go to their place of work in the morning just to turn around as soon as they reach their destination and head back home, this happens until night comes and it's time to go to bed.

### Steps to reproduce the problem

1. I have no idea
2. ...
3. ...
4. ... Profit

**Comment by Purevega** [comment]
> * happens

repeats.

**Comment by Raycoms** [comment]
that sounds weird, do you have barbs or pirates around? Did you try /mc
kill raiders

Am Do., 28. März 2019 um 22:00 Uhr schrieb Purevega <
notifications@github.com>:

**Comment by OCDCleric** [comment]
Ive come across similar issue. Farmer just hired and i've given tools and seed but all farmer does is goes from field to farm and infinitely repeats except only to sleep at night.

Using 0.10.291ALPHA
Acacia Farm lvl.1
Acacia Plain Field.

**Comment by Raycoms** [comment]
Should be fixed in newest, else reopen
