### ISSUE TITLE
Moving the colony causes problems

### ISSUE THREAD

**Issue by kreezxil** [ldtteam/minecolonies#3526]
**initial post**:https://github.com/kreezxil/World-of-Dragons/issues/110

[start of content]
Went to move my colony from minecolonies and it said i needed to abandon or delete my colony upon deletion i can not place a town hall. this is stopping me from claiming and protecting my items.

# To Reproduce

1. start a colony
1. build it up a bit
1. remove townhall block
1. place in new area
1. click delete colony
1. try placing townhall block after a while
1. townhall block placed and puff gone
1. relog and like magic its back in inventory

# Versions:

**Minecraft:** 1.12
**Forge:** 14.23.5.2823
**Mod Pack**: World of dragons V:14.38.170
**Mod Name**: minecolonies
**Mod Version**: 1.12.2-0.10.236-ALPHA

[end of content]

# Notes
The player decided to move their colony and didn't check any documentation on how to do it. Honestly why should they? Harvested their townhall block and placed it in a new location outside the colony borders. The block appears to place and then vanishes. 

# Things to consider when evaluating:

* they did not know about the new mechanic where you craft a townhall block and then place that outside the colony borders to establish a new colony
* instead they naturally assumed that picking up the townhall block and placing it down somewhere else would change the colony to a new location
* it's probably time to change the code that sets the colony center from the first time to any time the townhall block is placed
* and probably shouldn't have to require making a new townhall block to move the colony, **however** or maybe a **corollary** have the townhall block once placed become unmineable like bedrock and that when an attempt is made to harvest it, a message appears telling the player the proper way to move the colony is to make a new townhall block and place it outside the colony.

**Comment by Raycoms** [comment]
It can be the same townhall block, it doesn't have to be a new townhall
block.

Am Fr., 29. März 2019 um 08:21 Uhr schrieb kreezxil <
notifications@github.com>:

**Comment by Raycoms** [comment]
It disappeared because the location he tried to place it was invalid (too
close to another colony or village) it disappeared because we can only do
this check on the server side.

Am Fr., 29. März 2019 um 08:23 Uhr schrieb Ray Neiheiser <
ray.neiheiser@gmail.com>:

**Comment by kreezxil** [comment]
there needs to be a better way to handle this and to notify the player what
is happening.
