### ISSUE TITLE
Town Hall Lost By Rotating & Can't Replace

### ISSUE THREAD

**Issue by Rosomond** [ldtteam/minecolonies#3528]
VERSION:
1.12.2

EXPECTED BEHAVIOR:
Rotate town hall 180 degrees

ACTUAL BEHAVIOR:
After selecting rotation, town hall block did not move. I thought maybe chopping the block with an axe and placing it again would fix problem but, since I have multiple colonies, I am only an officer at this one (the first one I made) and I "do not have permission" to place the block. 

STEPS TO REPRODUCE THE PROBLEM:
1. Allow for more than one colony and make yourself an officer at the problem colony
2. Have a Level 5 Wooden Town Hall
3. Build Options of Town Hall
4. Reposition
5. Rotate 180 degrees
6. Block does not move
7. Chop down block and try to place again
8. "You do not have permission to do this."

**Comment by Raycoms** [comment]
same as #3526
