### ISSUE TITLE
Door Issue

### ISSUE THREAD

**Issue by Delranis** [ldtteam/minecolonies#3529]
### Minecolonies version
1.12.2-0.10.239-BETA-universal

Version: 

### Expected behavior
Doors would open and close properly.

- The doors either keep changing to rotating doors or the show as open but are closed and you cant interact with them other then breaking them. I am running the mallis door mod as well, but have disabled it and still have issues.

### Actual behaviour

- 

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit

**Comment by Raycoms** [comment]
Should be working int he newest version
