### ISSUE TITLE
*

### ISSUE THREAD

**Issue by rathmerdominik** [ldtteam/minecolonies#353]
Minecolonies version 0.4.78

Curse 0.4.78
I placed my Townhall Accidentally wrong.
Then i thought:"Ok i think i can break it and bring it to a new Spot.
Answer: NOPE
It just continue saying: "you already placed a Townhall"
But there isn't any TownHall.
So i can't do anything now.
I can't place it and now i am Stuck i need your Help.

Btw it was on the minecolonies Server.

### Steps to reproduce the problem

1. Accidentally placed the Townhall wrong
2. Tried to remove and replaced it.
3. The Server said: Nope and didn't let me
4. I am stuck and i can't do anything.

I really need your Help.

**Comment by Raycoms** [comment]
Can you please contact the staff on the server so that we can reset your
colony.

2016-12-17 14:18 GMT-02:00 DevilDemon001 <notifications@github.com>:
