### ISSUE TITLE
With Optifine and Chocapic Shader Enabled, Build previews turn white/glitchy.

### ISSUE THREAD

**Issue by pkinggd** [ldtteam/minecolonies#3530]
Version:  1.12.2

### Actual behaviour
When im previewing a townhall at level 5 with the chocapic shader enabled, it glitches out and my screen turns white, still able to play but very hard to see anything. Mainly got this with level 5 buildings while previewing, also made a custom townhall and has the same problem while trying to preview it

![2019-03-30_19 27 59](https://user-images.githubusercontent.com/49107957/55282927-cfc72480-534e-11e9-9eb1-a47e0acd4a6d.png)

### Steps to reproduce the problem
If you would want to try this problem, just download the Chocapic shader, and enable it while using the build tool, try for example to preview certain level 5 town halls and your screen will turn white.

If anyone knows if there is a fix or workaround for this, i would absolutely love to know it. Since i've been playing with this shader and optifine for a while now and i got a texturepack and mods to complement it, and i would love to just fix the problem but still make use of the shader if possible ofcourse.

**Comment by Nightenom** [comment]
combination of shaders and optifine is painful for us, if it happens every time to every preview then don't expect something good, if it's only for certain buildings then it might be fixable easily

**Comment by pkinggd** [comment]
> ine is painful for us, if it happens every time to every preview then don't expect something good, if it's only for certain buildings then it might be fixable easily

Hey thank you for your response,

Luckily it doesn't happen to every build i preview, all the 1-4 levels are safe so far atleast what i've previewed, its just that some level 5 and now my own schematic made townhall appear whiteish while previewing, i think it has something to do with the sky texture from the shader but that would also be kinda strange because only certain previews are affected by this bug.

**Comment by Raycoms** [comment]
I'll close this because I think we already were able to make it as close to compatible as possible.
Since optifine is closed source and shaders mix seriously with the game engine it's difficult to support them all.

**Comment by Nightenom** [comment]
I recommend you to find a block which is causing it (since levels 5 contain various blocks) and report it to shader author - he might be able to say something more

**Comment by GanthorPrime** [comment]
Only to add.. if you are using more mods maybe some of them include some shaders / effects that can broke the preview.   In the case of 'The betweenlands', i have to edit their config to disable some incorporated shaders, at least they allow you to enable them only for betweenland dimension and that solves the problem.   

Another mod causing issues with all optifine shaders in general, where 'twilight forest' and also comes with an option in their config file.

**Comment by pkinggd** [comment]
> Only to add.. if you are using more mods maybe some of them include some shaders / effects that can broke the preview. In the case of 'The betweenlands', i have to edit their config to disable some incorporated shaders, at least they allow you to enable them only for betweenland dimension and that solves the problem.
> 
> Another mod causing issues with all optifine shaders in general, where 'twilight forest' and also comes with an option in their config file.

I am in fact using the twilight forest mod! which setting should i change in the config files?

**Comment by Nightenom** [comment]
since twilight forest is a very old mod I assume that devs are doing things right so there shouldn't be big incompatibilities

**Comment by GanthorPrime** [comment]
Twilight forest:
B:firstPersonEffects=false

The betweenlands:
B:dimension_shader_only=true

in the remore case you want to build a colony precisely in that dimension, disable them completely for preview to work:
B:use_shader=false
