### ISSUE TITLE
Unclaimed chunks in colony

### ISSUE THREAD

**Issue by Grummelkater** [ldtteam/minecolonies#3531]
### Minecolonies version
Version: 
minecolonies-1.12.2-0.10.241-ALPHA-universal.jar

### Expected behavior

- 
No unrecognized chunks in colony.
### Actual behaviour

At least one chunk (Chunk 5 5 10 in 16 4 -57
) in my colony is not recognized. All surrounding chunks belong to my colony.
A simple "claim" via command does not work.
How could I claim that chunk?

Uploaded my world to google Drive:
https://drive.google.com/file/d/11OHnqHCBI6W_p3raO-9ztKmGeyF2IxZ2/view?usp=sharing

### Steps to reproduce the problem

1. Create a new world
2. Check for unclaimed chunks
3. find at leas one
4. ... Profit

**Comment by Raycoms** [comment]
you gotta do the claim command from the neighboring chunk.

Am So., 31. März 2019 um 10:33 Uhr schrieb Grummelkater <
notifications@github.com>:

**Comment by Grummelkater** [comment]
That did it! Thanks a lot! Sorry for bothering you...

**Comment by Raycoms** [comment]
Np, will find a way to fix the chunk issue all along in the future. We got
some plans on it already.

Am So., 31. März 2019 um 15:16 Uhr schrieb Grummelkater <
notifications@github.com>:
