### ISSUE TITLE
Unable to limit Field size

### ISSUE THREAD

**Issue by Gar1onriva** [ldtteam/minecolonies#3532]
### Minecolonies version

Version: 1.12.2-0.19.241-ALPHA-universal

### Expected behavior

The farmer to farm only within the limited borders.

### Actual behaviour

Just farms the entire range of the Field block regardless of cobblestone in the floor or fences blocking access.

![2019-03-31_22 32 28](https://user-images.githubusercontent.com/49048417/55295456-12e3cf00-5405-11e9-90f1-214705475b61.png)

### Steps to reproduce the problem

Place the Farm and Field, limit borders with cobblestone and fences, assign farmer, watch as farmer farms the full range.

**Comment by GanthorPrime** [comment]
try to put the scarecrow in the midle of the area?

**Comment by Raycoms** [comment]
Yeah, we got an issue open for this, but, nonetheless the scarecrow gotta
go in the middle

Am Fr., 12. Apr. 2019 um 02:01 Uhr schrieb GanthoR <notifications@github.com
