### ISSUE TITLE
Blacksmith not working

### ISSUE THREAD

**Issue by Diwill13** [ldtteam/minecolonies#3534]
### Minecolonies version 1.12.2

Version: 1.12.2-0.10.237-ALPHA

### Expected behavior

When the blacksmith has ingots and sticks and a worker needs a special tool, the blacksmith will craft this tool.

### Actual behaviour

The blacksmith doesn't even leaves his home, even though I taught him a lot of recipes to make axes, shovels and picks. The lumberjack and the miner for example don't have their tools to work, but the blacksmith won't craft anything even though he has the necessary materials.
He also does not request anything.

NOTE : I don't have a deliveryman is that the problem ? (I don't think so but, maybe)

### Steps to reproduce the problem

1. Build a blacksmith
2. Teach it some recipes for weapons/tools/armor
3.Wait for other workers to need weapons/tools/armor
4. DON'T Profit !

**Comment by Raycoms** [comment]
The crafting workers only work on request, this means, your builder requests something (or you request something via postbox) and the dman brings him the materials, he produces, and the dman delivers it back to the requester.

**Comment by Diwill13** [comment]
Ooh, thanks !
