### ISSUE TITLE
Miner won't change mining location 

### ISSUE THREAD

**Issue by unqiu3** [ldtteam/minecolonies#3536]
Version: 2.0

### Expected behavior
Miners hut is moved so he should start mining in the new mineshaft set up by builder 

- 

### Steps to reproduce the problem

     
1. Build a miners hut
2. Realize you fucked up the placing of the miners hut
3. Change location of miners hut
4. build hut
5. Watch the Miner destroy his own hut

**Comment by Raycoms** [comment]
Yeah we gotta disable moving for miner, the miner building should not be
moved at all after the miner started his shaft. it will break everything.

Am Di., 2. Apr. 2019 um 10:17 Uhr schrieb unqiu3 <notifications@github.com>:

**Comment by unqiu3** [comment]
Is there any way to fix it? It's really screwed up the whole town.

**Comment by Nightenom** [comment]
Ray - what's the problem with forgetting mineshaft references?

**Comment by Raycoms** [comment]
There are two problems a) If you move it only slightly he is going to try
to work half on his old shaft which will mess up badly.
You can try to place him some ladders downwards and reset him and hope he
will calculate it correctly

Am Di., 2. Apr. 2019 um 10:44 Uhr schrieb Nightenom <
notifications@github.com>:

**Comment by Nightenom** [comment]
So disable miner moving when new building spot (not mineshaft) collides with the old one.

**Comment by Raycoms** [comment]
It would still be weird since it would leave a hole in the ground of the
old shaft. I think it should be disabled if the miner started mining
already.

>

**Comment by unqiu3** [comment]
Would it be possible just to move the Miner to a new location to fix it?

**Comment by Raycoms** [comment]
Not sure, I never moved a miner =D

Am Di., 2. Apr. 2019 um 10:55 Uhr schrieb unqiu3 <notifications@github.com>:

**Comment by Nightenom** [comment]
That's a player problem, I would expect him to leave a hole there if I moved him, it's up to player to cover it necessarily

**Comment by Nightenom** [comment]
@unqiu3 you may also try to rebuild him

**Comment by unqiu3** [comment]
Moving it entirely worked. Thanks guys

**Comment by marchermans** [comment]
Yeah a move of the hut, should make the miner forget.
