### ISSUE TITLE
Again the builder does not want to build.

### ISSUE THREAD

**Issue by ZzylinN** [ldtteam/minecolonies#3537]
Version:
minecolonies-1.12.2-0.10.245-BETA-universal
(it was in previous versions)

forge 1.12.2-14.23.5.2768
other mods

Map started on older versions of minecolonies-1.12.2.xxx

--------------------------------------

Again I caught the same bug. The builder does not want to do anything and his requests are empty. 

Builds archers. building level 1. The hut of the archer is far away. In the request for the construction itself indicates the builder.

I put 64 oak logs in the builder’s hut and he took 14 logs and went to build.

Log
[log.txt](https://github.com/ldtteam/minecolonies/files/3048036/log.txt)

**Comment by Raycoms** [comment]
I heard of this issue already, it seems like the request is not displaying
correctly, is this reproduceable?

Am Fr., 5. Apr. 2019 um 10:14 Uhr schrieb Sasha <notifications@github.com>:

**Comment by ZzylinN** [comment]
He appeared to me during the construction of an archer’s hut. In the absence of the builder in the inventory of logs, he goes to his hut and just stands.

on my map you can check for yourself if you download it from: Woodcutter and steps from the acacia. # 3479

**Comment by Raycoms** [comment]
Is the building of the builder in a loaded chunk?

**Comment by ZzylinN** [comment]
Yes, it is.
The builder's hut is located X: 205 Y: 69 Z: 188
The hut of the archer that a builder with erects X: 328 Y: 70 Z: 191
As can be seen 9 chunks

**Comment by Raycoms** [comment]
Can you send me your world?

Am Fr., 5. Apr. 2019 um 12:15 Uhr schrieb Sasha <notifications@github.com>:

**Comment by ZzylinN** [comment]
I laid out my world in Issues: Woodcutter and steps from the acacia. # 3479

**Comment by Raycoms** [comment]
Ahh yes, could you upload the "current" version with the builder issue happening right now?

**Comment by ZzylinN** [comment]
In the current version, I gave myself to the builder of the log and he went to build (as he wrote above) so it’s hard to catch a bug. But if you want I can throw it off. But you have to download not only the world but also the mods and config.

**Comment by Raycoms** [comment]
Ouch, damnit, will try to reproduce it locally then

Am Fr., 5. Apr. 2019 um 14:05 Uhr schrieb Sasha <notifications@github.com>:

**Comment by ZzylinN** [comment]
You can download from Issues: Woodcutter and steps from the acacia. # 3479 and replace minecolonies-1.12.2-0.10.245-BETA-universal there. on the coordinates X: 328 Y: 70 Z: 191 to start the construction of the archer’s hut and observe (with a probability of 70%) this bug will appear as after that saving I almost did not play, since I was on a business trip

**Comment by ZzylinN** [comment]
This is a link to the current save.
https://yadi.sk/d/XxHIP8vngNg7Kg

**Comment by ZzylinN** [comment]
This is a link to the old save.
https://mega.nz/#!EfJlRAzB!Ry15wzELKNzlvo3uV6PSwHxwD2mjfY_Sr5gmJzzbKcg

**Comment by ZzylinN** [comment]
Found another bug in the construction of an archer’s hut. During the construction of the first level, the builder asks for 3 sets of leather armor and 3 racks for armor. In fact, puts only 1 rack and 1 set of leather armor. But after providing 3 sets of leather armor and 3 racks, the builder constantly asks for them, gives him, he again asks and so on ad infinitum (issued 8 times).
Cancel construction and start again tried it does not help

**Comment by Talyda** [comment]
Did you give them to the builder himself? If you put them in his building's inventory, then cancel his request does he still keep asking for them?

**Comment by GanthorPrime** [comment]
Are you giving him the items pressing the 'fulfill' button on the builders GUI? (the citizen gui).

That button nevers works for me: You give the items he is requesting while you have them in your inventory,  the items passes to him, but in his GUI the button 'fullfil' is still active for that items and you can give him again using that button. in that way, it apears he needs more than 1 of the item, but in the hut GUI requirements list you can see he need only one.

**Comment by ZzylinN** [comment]
I fully issued 3 sets of armor and a stand in the inventory of the builder’s hut, but using them, the builder asked again. I also put him on one subject (as requested by the builder), but it also did not help.
> 
> Did you give them to the builder himself? If you put them in his building's inventory, then cancel his request does he still keep asking for them?

_________________________________________________

If you give items directly to the builder through the request interface (through the button to give out) then the items just disappear (they are not in the builder’s inventory, not in the builder’s inventory)!
> 
> Are you giving him the items pressing the 'fulfill' button on the builders GUI? (the citizen gui).
> 
> That button nevers works for me: You give the items he is requesting while you have them in your inventory, the items passes to him, but in his GUI the button 'fullfil' is still active for that items and you can give him again using that button. in that way, it apears he needs more than 1 of the item, but in the hut GUI requirements list you can see he need only one.

_________________________________________________

PS: The builder installs all the racks for armor and armor at one point!
Striking several times on this point I knocked out all 9 stands for armor and sets of leather armor.

**Comment by Raycoms** [comment]
I'll debug this well tomorrow.

Am So., 7. Apr. 2019 um 00:28 Uhr schrieb Sasha <notifications@github.com>:

**Comment by Reivax114** [comment]
I have the armor stand in the archery bug as well, and it's pretty annoying. What's the news about it? I tried building the hut myself using the building tool as pattern , but once I finished The archery gui's continued asking the armor stand with all it's leather set, three of them.

**Comment by Raycoms** [comment]
Did you try the newest alpha?

Am Do., 18. Apr. 2019 um 15:00 Uhr schrieb Reivax114 <
notifications@github.com>:

**Comment by Reivax114** [comment]
Finally worked! Thank you very much. Anyway, on the gui it asked for three sets of armor and armor stand. I think the builder ignored it.

**Comment by Raycoms** [comment]
Hmm, weird

Am Do., 18. Apr. 2019 um 16:44 Uhr schrieb Reivax114 <
notifications@github.com>:

**Comment by ZzylinN** [comment]
With version minecolonies-1.12.2-0.10.268-ALPHA, the builder still completed the archer’s hut.


But in the builder's hut, on the request page, it still required 3 sets of leather armor and 3 racks for armor. Although the builder used only 1 set of leather armor and 1 rack for armor.
![2019-04-19_17 57 27](https://user-images.githubusercontent.com/34644142/56424370-cd167a00-62d1-11e9-9733-2bcd37cc48f1.png)

**Comment by marchermans** [comment]
Could you test a PR-Build for me: [Here](https://teamcity.minecolonies.com/repository/download/LetSDevTogether_Minecolonies_Branches_Build/27591:id/build/libs/minecolonies-1.12.2-0.10.906-PERSONAL-universal.jar) It contains fixes for DMan and Crafters not interacting properly with the rest of the colony.

Remember to run a Request System Reset, see our wiki for the command details.

**Comment by EurypteriD192** [comment]
I have same issue. The problem lies in that they are not requesting. But they are holding the block they need (not in inventory but on the character) 

I have two builders i have to manual feed as they are not getting anything from the 5 delivery guys.  i am on the latest alpha (downloaded yesterday) 

shes standing with something in her hand there is not in the system and the clibboard stands blank.. please let me know if you need logs or save or anything

**Comment by TMarc** [comment]
I have the same issue on all Acacia building.

The workarround is removing racks from the builder or crafters and it works again.
