### ISSUE TITLE
Barbariand raids badly listed in Barracks

### ISSUE THREAD

**Issue by GanthorPrime** [ldtteam/minecolonies#3540]
### Minecolonies version

Version: minecolonies-1.12.2-0.10.246-ALPHA-universal.jar 

### Expected behavior

Barbarians raids listed chronologicaly in Barracks: actualy it uses a numbered list to show all raids and to tell from where they come:

1.- first raid... far from the nortwest
2.- second raid... far from the southwest
.. and so on

### Actual behaviour

The numbering in the list got inverted (olders appears with biggers numbers, and current raid is listed using number 1. Im pretty sure it doesnt use that ordering in prevous versions.

In case that the intention is to use the list as a sliding log (fifo log?), so current raid is always visible (not a bad idea), i thing the numbers of the items must be removed or inverted.

### Steps to reproduce the problem

1. Wait until your town got raided 2 or more times
2. Forget from where they come before
3. In current raid, run like crazy in the direction listed with last number in the barracks
4. Found nothing, and start earing your citizens screams and you town in flames from the other side

**Comment by Raycoms** [comment]
It was always listed like that, but yeah, maybe just removing the numbering
would make it better or just put behind the last one a Current:

Am Sa., 6. Apr. 2019 um 20:49 Uhr schrieb GanthoR <notifications@github.com
