### ISSUE TITLE
Farming Rice/Tea

### ISSUE THREAD

**Issue by LatentDesire** [ldtteam/minecolonies#3549]
The farmer doesn’t know how to farm the crops from the Tea the Story mod. Suggest compatibly.

Since the rice is rather non standard to grow, this is how.

First place mod’s rice seed in standard farmland. Grow crop. When ready, click crop with item (iirc it’s a sickle or something like it). Make farmland. Then right click the farmland with a shovel. Right click results with a water bucket (doesn’t currently empty water bucket. Also waters connected blocks.) and place rice plants in paddy. From there just wait until fully grown and break.

**Comment by LatentDesire** [comment]
Oh, as for the tea, you just need to right click the tea plant at a certain point to get the leaves. I think said point is before the crop is fully grown. I’m not to sure if left the it’s own devices that a tea plant will flower on it’s own, but when using bonemeal to speed things up, sometimes the plant would flower. Afterwards it would give additional seeds instead of leaves when right clicked. 

There are also some altitude and Biome temperature requirements for the crops, but that shouldn’t effect the farmer.

**Comment by Raycoms** [comment]
Will be added to a new joint mod compat issue.
