### ISSUE TITLE
Suggestion: /dank/null Builder Integration

### ISSUE THREAD

**Issue by Elrol** [ldtteam/minecolonies#3550]
I was thinking that a sweet feature would be having the ability to just toss a /dank/null into the builder's hut or inventory and have the builder use the /dank/null to build with. Here is kind of a layout of different ideas that I have with this:

- Each /dank/null needs the respective builder level, for example a builder hut 2 could use a tier 2 /dank/null
-  The builder would refrain from using the last block in the /dank/null so that it will stay partitioned.
- Have the blocks inside of the /dank/null register as blocks for the reuqirements (so you can see how much more you still need even with the /dank/null in the hut)
- Have the builder deposit blocks into the /dank/null if able to (if the /dank/null is allocated to take the block then have it add it to it) so that you dont need to empty the hut as often after they clear a build area
- maybe include some kind of debug notices about the /dank/null, a single message anytime:
     > A /dank/null is empty (exept for the single block mentioned earlier)
     > A /dank/null is filled fully (still have it delete items from the inventory if the /dank/null is full)

These are just a few ideas that I could think of, feel free to change them around to fit what is possible and what would fit the mod best. If I can think of any other ideas relating to this I will comment again.

**Comment by Raycoms** [comment]
What is a dank/null?

Am Mi., 10. Apr. 2019 um 16:43 Uhr schrieb Elrol <notifications@github.com>:

**Comment by Elrol** [comment]
a /dank/null is like a dev/null from open blocks, it stores a certain amount of an item, and it deletes any item that is picked up after it is full.

https://minecraft.curseforge.com/projects/dank-null

**Comment by Raycoms** [comment]
Ah yes, backpack integration is planned

Am Mi., 10. Apr. 2019 um 16:53 Uhr schrieb Elrol <notifications@github.com>:

**Comment by Elrol** [comment]
I guess it is like a backpack, but with a void function

**Comment by Raycoms** [comment]
If properly implemented we'll be fine

**Comment by Elrol** [comment]
Sounds good then!

**Comment by Raycoms** [comment]
Will be added to a new joint mod compat issue.

**Comment by Raycoms** [comment]
Will be added to a new joint mod compat issue.
