### ISSUE TITLE
Guards ignoring mob attack list

### ISSUE THREAD

**Issue by GanthorPrime** [ldtteam/minecolonies#3552]
### Minecolonies version

Version: minecolonies-1.12.2-0.10.259-RELEASE-universal.jar

### Expected behavior

Guards only attack mobs enabled in their huts mob list. This was good in prevous versions

### Actual behaviour

Guards are fighting mobs disabled in their list:  I have disabled enderman and zombie villagers in all guard towers and barracks towers. After update to last release, they start attacking all.  Checked the configuration page in their huts and it has not changed..   ¿maybe a desync related to the update?

**Comment by Raycoms** [comment]
Just tested it here it should still be working, can you try switching them
on and then off again?

Am Fr., 12. Apr. 2019 um 02:39 Uhr schrieb GanthoR <notifications@github.com

**Comment by Raycoms** [comment]
Closed until update is given.
