### ISSUE TITLE
Aroma1997s-Dimensional-World-1.12.2-2.0.0.2

### ISSUE THREAD

**Issue by Spaladino95** [ldtteam/minecolonies#3553]
### Minecolonies version

Version: minecolonies-1.12.2-0.10.256-BETA-universal

### Expected behavior

-  Should be able to create colony in another dimension.  Aroma1997's mining dimension specifically. 

### Actual behaviour

-  States that other dimension colonies are not allowed per config, even though the config has been set to allow.

### Steps to reproduce the problem

1.  GO to mining dimension
2.  try to place colony
3.  error displayed.
4. ... Profit

**Comment by Asherslab** [comment]
dimensional colonies are only allowed in other OverWorld dimensions. not any other, we do not support them as of yet

**Comment by Raycoms** [comment]
They are allowed, and if the server config dimension and client config
dimension are on true it should work.

Am Fr., 12. Apr. 2019 um 18:41 Uhr schrieb AshersLab <
notifications@github.com>:

**Comment by Asherslab** [comment]
well then apparently i was misinformed and also have this bug? ( i was told the above was the case )

**Comment by Raycoms** [comment]
I heard they very able to get it to work
