### ISSUE TITLE
Crash upon world loading

### ISSUE THREAD

**Issue by MineShadow7** [ldtteam/minecolonies#3556]
### Minecolonies version
Version: minecolonies-1.12.2-0.10.262-ALPHA-universal

### What happened? 
Minecraft crashed due to POSSIBLY minecolonies citizen

### Steps to reproduce the problem
Earlier this morning I tried to citizen recruitment and hired a new citizen to a stonemason work. He behaved very strange. Not responding to builder requests and just walking around like a normal citizen would do. I decided to re-hire him and now my world crashes upon loading.

Crash log - https://paste.dimdev.org/dabinolipe.mccrash

**Comment by Nightenom** [comment]
Does not look like minecolonies problem, I would blame one of those:
your resource pack
your graphics drivers / anything that changes its behaviour
the world got corrupted when saving

**Comment by Nightenom** [comment]
Ouch, you've got optifine :D can you try playing without it? Since it's rendering crash

**Comment by MineShadow7** [comment]
Ok, I'll try

**Comment by MineShadow7** [comment]
Nope. I disabled all resource packs and removed optifine. 


NEW CRASHLOG - https://paste.dimdev.org/abugasibek.mccrash

**Comment by Raycoms** [comment]
Configurations.gameplay.updateRate has to be a positive number.
