### ISSUE TITLE
[Suggestion] Prohibit the possibility to place hut without build tool

### ISSUE THREAD

**Issue by MineShadow7** [ldtteam/minecolonies#3557]
This should improve knowledge of players with build tool and make life easier with working with issues, bcs most of the people don't even know about build tool's existence. 

How does this work? 
Just make hut blocks unplacable by hand. Make "Use build tool instead" message appear in chat.

Profit.

**Comment by Asherslab** [comment]
we've talked about this before, and correct me if i'm wrong @Raycoms but we can't do this properly due to how blocks are placed and etc. it would cause more issues than it would fix

**Comment by Raycoms** [comment]
Yeah we discussed this already, some people can't use the buildtool, we would lock them out with this.

**Comment by marchermans** [comment]
@Raycoms What was the exect need for the placement? The buildtool should by now be useable by anyone. If not I think we should redesign the entire thing......

**Comment by Raycoms** [comment]
I mean some few shaders don't work and crappy computers sometimes don't
either
