### ISSUE TITLE
Stuck in Leaves

### ISSUE THREAD

**Issue by ghost** [ldtteam/minecolonies#3561]
Minecolonies: 0.10.259-Release
Forge: x.2824
Passable Leaves 2.0.0

Issue:
Passable leaves make it so that mobs/players/etc... can walk/fall through leaves, but slowly. The villager AI seems to be unable to handle this, so they just get stuck instead. This can be anything from just having to walk through the leaves to jumping up a block while in leaves.

**Comment by Asherslab** [comment]
@Raycoms do you think this is even feasible to fix?

**Comment by Raycoms** [comment]
Not sure if we can allow them to noclip through leaves easily.

Am Mo., 15. Apr. 2019 um 22:30 Uhr schrieb AshersLab <
notifications@github.com>:

**Comment by Asherslab** [comment]
well i think s/he's saying that they have a mod that already *does* that, which causes issues because the citizens think that the leaves are solid (which they should be mind you...)

**Comment by Raycoms** [comment]
Ahhh, weird. Hmm, we do some check for is passable over them, maybe that's
messing it up in the pathfinder

Am Mo., 15. Apr. 2019 um 22:47 Uhr schrieb AshersLab <
notifications@github.com>:

**Comment by ghost** [comment]
It's more of a thing to have them act like real life, where you can push them out of the way, but at a speed penalty.

**Comment by Raycoms** [comment]
Oh, do you mean you can't even push/hit them out of it?

Am Mo., 15. Apr. 2019 um 22:49 Uhr schrieb DemonfangArun <
notifications@github.com>:

**Comment by ghost** [comment]
I can push/hit them out of the leaves just fine, assuming I notice.

**Comment by Raycoms** [comment]
Kk, let me check on it.

>

**Comment by Raycoms** [comment]
Do other mobs walk through it normally?

Am Mo., 15. Apr. 2019 um 22:54 Uhr schrieb DemonfangArun <
notifications@github.com>:

**Comment by ghost** [comment]
Yes, other mobs have no issues, even vanilla villagers.

**Comment by ghost** [comment]
I'll leave this here:
Observed notes with 873:
-They eventually make it through leaves most* of the time
-Lots of jumping, sometimes going backwards in progress towards destination
-Occasionally they'll quickly move 4-12 blocks away and try again
-Will hang up on 2+block high obstacle **_IF_** it's buried in leaves
-In some configurations of leaves and obstacles they WILL get stuck in a loop

I think part of the issue may be the jumping. The leaves should effectively be treated as if they aren't there if passable leaves is installed. While they will slow down the villagers movement, other mechanics related to the villagers movement through them is unaffected.

**Comment by Raycoms** [comment]
That might not be possible since they use certain parts of the code where our citizens just act like any passive npc.
