### ISSUE TITLE
Wand border bug

### ISSUE THREAD

**Issue by ghost** [ldtteam/minecolonies#3562]
Minecolonies: 0.10.259-Release
Forge: x.2824

Issue:
Orphaned chunks that actually aren't show up with the building tool.

**Comment by Nightenom** [comment]
Please describe your issue a bit more (mostly follow the issue pattern) and attach some screenshots if possible

**Comment by ghost** [comment]
Sorry for the lack of screenshots, The issue went away magically while troubleshooting another issue. It's related to the new function whereby the building tool will show colony borders when held. The function can glitch out and show what appear to be orphaned chunks (a very old bug that was fixed) within the colony area.

**Comment by Raycoms** [comment]
the orphaned chunks might still be there or not updated yet on the client side of the world, this is possible, walking around or inside the chunk will fix that then, else claiming will fix it
