### ISSUE TITLE
How should barracks work exactly?

### ISSUE THREAD

**Issue by Reivax114** [ldtteam/minecolonies#3566]
### Minecolonies version

Version: minecolonies-1.12.2-0.10.259

### Expected behavior
 When I started using minecolonies I understood barracks spawned itself it's guards and housed them as well, as it said in the wiki. 

- 

### Actual behaviour
 Once I finally built the barracks in survival (Medieval birch) and I built the first barracks tower, nothing happened. I chosed one of the citizens I already had and used her as guard. I supposed a new citizen would appear, but it didn't. How are they supposed to work?

- 

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit

**Comment by Raycoms** [comment]
When you hire someone, after some time you should get a kid.
Kids explained: https://www.youtube.com/watch?v=D4cHKF5i-YE
