### ISSUE TITLE
Minecraft crash at Startup (Singleplayer)

### ISSUE THREAD

**Issue by bufu1337** [ldtteam/minecolonies#3567]
### Minecolonies version
Version: 1.12.2-0.10.259-RELEASE

Hi guys,
i am playing a singleplayer world with many many mods (264 mods without MineColonies, loading time about 25mins) and minecraft works.
A little bit laggy because of so many mods, sometimes a crash, and i would need a HIGH-HIGH-HIGHEnd PC to run it smooth but its working.
Some mods are not up to date because i get a crash when i use the latest forge versions, which is require to update the mod.

Now i found MineColonies and i was always looking for this kind of mod.
Unfortuneatly it crashes at Startup. Something is wrong with the sub-mod "structurize".
I hope it only conflicts with another mod, because like i said i cant install a newer forge version.

Can someone help me figuring out the problem please? 

[crash-2019-04-17_19.07.38-client.txt](https://github.com/ldtteam/minecolonies/files/3095577/crash-2019-04-17_19.07.38-client.txt)

i have tried another, older release-version and there was an error at MineColonies itself:
1.12.2-0.10.202-RELEASE

[crash-2019-04-17_19.29.43-client.txt](https://github.com/ldtteam/minecolonies/files/3095664/crash-2019-04-17_19.29.43-client.txt)

**Comment by Raycoms** [comment]
Weird issue, definitely.

**Comment by someaddons** [comment]
nah its a very common one, he's using a very old forge version which doesnt have the method structurize uses. Did you try the recommended forge version 14.23.5.2768 instead of the latest?

**Comment by Raycoms** [comment]
Ah okay, then close and please upgrade at least to recommended.

**Comment by bufu1337** [comment]
Why closing this instantly?
Thats what i get with you recommended forge version:

[crash-2019-04-20_15.44.11-client.txt](https://github.com/ldtteam/minecolonies/files/3100183/crash-2019-04-20_15.44.11-client.txt)

**Comment by someaddons** [comment]
why leave it open when it is not a minecolonies issue? Your latest crashlog is about extra utilities
