### ISSUE TITLE
Town Hall Book block buried by Townhall itself

### ISSUE THREAD

**Issue by Hilk5** [ldtteam/minecolonies#3568]
### Minecolonies version

Version: Either 1.12.2-0.10.258 BETA-universal or 1.12.2-0.10.259 RELEASE-universal. I'm not quite sure. 

### Expected behavior

- Town Hall Book being accessible after completing Town Hall construction 

### Actual behaviour

- My builder built the entire Town Hall above the Town Hall Book itself (the book being buried under the ground of the main hall, so there was no way for me to access it without breaking blocks + dirt).

When I tried to break the Town Hall Book block and place it inside in the Town Hall manually (above ground) it shows I haven’t built any Town Hall at all (level = 0) and it displays the ‘under construction’ fences when I place the block again. My citizens are still there though. 

Even if I place the Town Hall Book block back on the same tile I initially placed it, it doesn't seem to solve the issue. 

I've been searching but can't seem to find a fix. Any idea how to solve this? 

### Steps to reproduce the problem

1.  Place Town Hall Book block on an unequal surface
2.  Assign Builder to construct Town Hall
3.  Town Hall is being built above the Town Hall Book block so it's hidden underneath the ground of the Town Hall itself
4. ... Profit

**Comment by lunadragnstar** [comment]
Which style

**Comment by Hilk5** [comment]
Medieval Oak is the style I've built the Town Hall in

**Comment by lunadragnstar** [comment]
version 202, old issue
