### ISSUE TITLE
Hiring/Assigning Workers Suggestion

### ISSUE THREAD

**Issue by SyberSmoke** [ldtteam/minecolonies#357]
Suggestion: An interface in the work hut showing the top five available workers.

The interface would show the player the top five workers for that hut type.  It would highlight the attributes that are best for that hut (highlight then in green) and allow the user to select the worker and press a button to assign at the work hut itself.

If a worker that is better suited to the hut is working at another hut of a different type, the hut they are working at will also be listed.  This way a player can choose to reassign the worker if they are a better fit.

Workers at a like hut would be excluded from the list.

**Comment by marvin-bitterlich** [comment]
Sounds useful! We should at least sort by best Workers and highlight their stats

**Comment by pmardle** [comment]
I agree with highlighting the relevant skills, but we shouldn't show workers who are already working.  The skills system is supposed to be a boost to players who take the time to use and understand it.  Having the system always show you the best choice makes getting your citizens into the best jobs too easy.

**Comment by SyberSmoke** [comment]
I am a casual player, I do not have the time nor desire to search through the entire colony to find the best fit.  That is what management tools are for.  So that I can play the game and not play "hunt the civ".  Just saying...

**Comment by pmardle** [comment]
Then you can just leave the Hiring on Automatic..  The manual system is
supposed to be there as a bonus for those who do take the time..
Eventually, if you keep them alive long enough, all workers will achieve
level 50 in a profession and therefore be just as good, however they will
take longer to get there.

**Comment by SyberSmoke** [comment]
See that seams off because you are saying because I do not have all the time in the world, I should not gain some of the same benefits as someone with more time to spend.  While I am not saying this has to be casual friendly.  It should offer some tools to allow us to get the same benefits from spending a little time.  And to offer some interface options so that say...my 10 year old daughter I play minecraft with, can easily understand who is going where.

This is not something that is typically considered.  And I know this is your mod and all and do as you please.  But all kind play mods from me (Tech Savvy Adult), to 10 years olds (She is artistic and likes to farm), to even five year olds (She just builds houses out of blue wool and spams bunnies).  May wanna keep it in mind that all kinds will use your mod.

**Comment by marvin-bitterlich** [comment]
@SyberSmoke You can always use automatic, that will work fine for people who don't care. And you can also choose Manual and assign people by whatever you desire. A 10 year old may assign people whose names sound cool to jobs she thinks they fit. That will work just fine. (And also be lots of fun, more fun then having a worker be 10% faster)

But if you want the extra 20% speed, then you have to learn the mechanics behind it. No one is forcing you. But removing this gameplay element sound like the wrong was to go. We plan on color coding it and maybe make automatic somewhat smart (but not too smart) so it will be easier, but it was never intended to be easy.

**Comment by pmardle** [comment]
Bear in mind the game is balanced around the Automatic hiring, so that is
the norm.  However for those with the
time/effort/inclination/understanding, they can get a small increase in
efficiency from specifically tailoring workers to tasks.. This is
optional.  If we make it super easy for all to optimise perfectly, where is
the gameplay and draw for those who like to micro manage and really get
under the skin of the mod/gameplay?

We are not penalising people who don't do it, we are rewarding those that
do.
