### ISSUE TITLE
Miner Needs to be Able to Skip Blocks

### ISSUE THREAD

**Issue by MokahTGS** [ldtteam/minecolonies#3571]
The miner is constantly hitting blocks it can't mine and the stopping instead of just skip[ping the block and moving on.  This is especially a problem with modded ore and mods like Fossils and Archaeology that have fossil ore that can't be mined unless you have a diamond pick but are at any level.  The miner just get stuck asking for a better pick but can't use it because the mining hut is too low level.  This basically makes the miner useless.

**Comment by Raycoms** [comment]
We got an issue for that open already, the problem here is that there are two possibilities:
a) Destroy if he doesn't have the tool (could destroy if ore as well)
b) Ask for tool
Skip doesn't work because we don't know if the block is in the way (we can't find that out too easily)
