### ISSUE TITLE
Do not bring the requested items from the repository to the builder

### ISSUE THREAD

**Issue by ZzylinN** [ldtteam/minecolonies#3575]
Version:
minecolonies-1.12.2-0.10.270-ALPHA-universal
(it was in previous versions)

forge 1.12.2-14.23.5.2836
other mods

Map started on older versions of minecolonies-1.12.2.xxx

------------------------------------------------------

Do not bring the requested items from the repository to the builder

Builder requests spruce fence.
![2019-04-22_20 04 25](https://user-images.githubusercontent.com/34644142/56504658-1289b000-653b-11e9-9327-17b3cc6966da.png)

Here you can see that the fence is in stock
![2019-04-22_20 05 36](https://user-images.githubusercontent.com/34644142/56504735-5086d400-653b-11e9-8216-88958dce14d8.png)

log
[log 22.04.19.txt](https://github.com/ldtteam/minecolonies/files/3103624/log.22.04.19.txt)

PS: Four courier runs around the city

**Comment by Raycoms** [comment]
Do you know a way to reproduce this? I also noticed it already but I wasn't able to reproduce it yet to debug it

**Comment by GanthorPrime** [comment]
I stoped to bring resources to my builders on a colony and noted this also,  delivery mans are running  but not fullfiling requests.  Is the same colony were guards are ignoring the mobs attack configuration and the lumberjack is ignoring the tree type selection page.  i think something goes wrong in that colony.

i will try changin the prioriry in a way builders get the max priority.  /mc rs reset maybe will be necesary also.

not sure the scope of /mc colony refresh. maybe we can give a try to that too?

**Comment by ZzylinN** [comment]
>> 
> Do you know a way to reproduce this? I also noticed it already but I wasn't able to reproduce it yet to debug it

This appears when upgrading a home from 4 to 5 level.

**Comment by marchermans** [comment]
Please try the following test build: [Here](https://teamcity.minecolonies.com/repository/download/LetSDevTogether_Minecolonies_Branches_Build/27591:id/build/libs/minecolonies-1.12.2-0.10.906-PERSONAL-universal.jar) It is a test build that should fix some problems with the DMan and Crafter interaction with your colony.

Remember to run a Request System Reset, see our wiki for the exact command details!

**Comment by Raycoms** [comment]
Should be fixed with the newest alpha, if not please reopen.
