### ISSUE TITLE
Unable to interact with citizens or buildings control blocks after changing dimensions

### ISSUE THREAD

**Issue by cjser** [ldtteam/minecolonies#3577]
Every time I change dimensions when I can't interact with citizens or buildings control blocks. Have to reload the save game to work.

minecolonies-1.12.2-0.10.270-ALPHA-universal.jar
Forge 1.12.2 - 14.23.5.2836

**Comment by GanthorPrime** [comment]
¿is you colony in another dimension? (different than the overworld)

Try to check this: When you are in the colony dimension, look for the nearest colony info in the debug screen (F3),  Left column of info must shown something like: '-Colony Name- xxx blocks from center'.  If it says 'No close colony', go to the same location (x, z) but in the overworld dimension and check if the colony info is beign showed in that dimension.

that will not solve the problem but maybe give a light on what is happening

You can also use /mc whereami to ouput nearest colony info

**Comment by cjser** [comment]
No. The colony is in the overworld original dimension,  the problem is when
I go to another dimension (nether, twilight etc) and go back and try to
interact.

**Comment by Raycoms** [comment]
Can you send us the log of this happening?

**Comment by cjser** [comment]
There is not crashing. So not crashing log, what other log?

**Comment by Raycoms** [comment]
the general log you have when playing but I want the log data from entering
another dimension when things work and then coming back and things don't

Am Fr., 26. Apr. 2019 um 20:29 Uhr schrieb cjser <notifications@github.com>:

> There is not crashing. So not crashing log, what other log?
>

**Comment by cjser** [comment]
I have problems to run minecraft today (not sure what I change since 2 days ago when it start fine), when I manage to do it I come back with the logs.

**Comment by cjser** [comment]
I dont know if this helps. Its a log from the last time I manage to play.
[2019-04-24-2.log](https://github.com/ldtteam/minecolonies/files/3124439/2019-04-24-2.log)

**Comment by Raycoms** [comment]
Can't open this file

**Comment by GanthorPrime** [comment]
i do some testing in a dedicated server enviroment and i was able to reach the state described by the author (cant interact with building blocks nor citizens), but in my case i can only reproduce it when i disconnect / close the server while i was in another dimension, then restart, connect and travel from the dimension to the overworld.  cant interact with any colonie / citizen unless i reconnect to the server.

**Comment by Raycoms** [comment]
Thanks for this =) now I was able to reproduce it
