### ISSUE TITLE
Problem with nbt

### ISSUE THREAD

**Issue by cjser** [ldtteam/minecolonies#3579]
Version: 
1.12.2-0.10.270-ALPHA
### Expected behavior
Builder excavate and make building 

- 
Worker runs around and do nothing and message keep appearing of problem with minecolonies

I have to upload crash log later.

**Comment by Raycoms** [comment]
Crashlog please

**Comment by cjser** [comment]
[crash-2019-04-24_13.47.46-client.txt](https://github.com/ldtteam/minecolonies/files/3122595/crash-2019-04-24_13.47.46-client.txt)

**Comment by Raycoms** [comment]
It seems like you are trying to build something which is much too big to send it over, is thi spossible?

**Comment by cjser** [comment]
I´m just building the level 5 birch house and the stone cutter hut.

**Comment by Raycoms** [comment]
which stone cutter hut?

**Comment by cjser** [comment]
After I eliminate all the buildings orders the message keep appearing, so the problem is somewhere else in the colony not related to the builder. I can't find where.
[crash-2019-05-04_02.35.43-client.txt](https://github.com/ldtteam/minecolonies/files/3144068/crash-2019-05-04_02.35.43-client.txt)
Can it be related to some recipe?

**Comment by Raycoms** [comment]
please do a /mc rs reset colony: yourcolonyid
This should fix it for you =)
