### ISSUE TITLE
Horse Disappearing after lag spike

### ISSUE THREAD

**Issue by Falcon7617** [ldtteam/minecolonies#358]
### Minecolonies version

Current

### Expected behavior

- Riding a horse during a lag spike doesn't cause complete disappearance of the horse

### Actual behaviour

- Horse vanishes

### Steps to reproduce the problem

1. Find a horse
2. Saddle it
3. Ride around until you lag out. 
4. Keep riding during the lag spike
5. No Horse

Note: Can I be reimbursed with 2 horse eggs, 1 iron horse armor, and a saddle please?

**Comment by marvin-bitterlich** [comment]
Has nothing to do with minecolonies...
