### ISSUE TITLE
Tree Chopper mod

### ISSUE THREAD

**Issue by Dordoux** [ldtteam/minecolonies#3581]
### Minecolonies version

Version: release forge-14.23.5.2768

### Expected behavior

Expected to chop a tree with the tree chopper mod with chopping one log.

### Actual behaviour

The Tree Chopper mod seems not to be installed (while it is) . So Im unable to chop trees that simple like it would be with the tree chopper mod.

### Steps to reproduce the problem

1. dowlload the tree chopper mod
2. try to chop trees without the modpack (of minecolonies of course)
3. Try to chop trees with the modpack

**Comment by Raycoms** [comment]
That's not our mod, please report it either to the tree chopper mod, or on our discord if it is related to the modpack. This github is only for reports regarding the mod itself.
