### ISSUE TITLE
Server crash on start (client code in server side)

### ISSUE THREAD

**Issue by GanthorPrime** [ldtteam/minecolonies#3582]
### Minecolonies version

Version: minecolonies-1.12.2-0.10.272-ALPHA-universal.jar  and .273

### Actual behaviour

Dedicated server crashing on start.  maybe related with #3580. Client code calling on server? :

java.lang.NoClassDefFoundError: net/minecraft/client/multiplayer/WorldClient
	at com.minecolonies.coremod.MineColonies.<clinit>(MineColonies.java:77)

**Comment by Raycoms** [comment]
Can you send me the complete log please?

**Comment by GanthorPrime** [comment]
[crash log](https://pastebin.com/NPJ8Buqs)

returned to 1.12.2-0.10.271-ALPHA and server starts normally. problem is in 1.12.2-0.10.272

**Comment by Raycoms** [comment]
Fix pushed
