### ISSUE TITLE
[Feature Request] Add config option to change hunger rates of citizens

### ISSUE THREAD

**Issue by ThePwnd** [ldtteam/minecolonies#3585]
Firstly, forgive me if the wording in my title is confusing.  What I mean by "hunger rates" is the passive decay rate of a citizen's hunger stat.  In most of my modpacks, I've included a food mod that allows me to increase the player's passive hunger decay rate, so that I would have to eat 2 or 3 meals per day in the game to keep my hunger bar full.  It would be nice if I could do the same for the citizens in my colony.  I would enjoy making the mod harder, especially in the early game, by increasing the demand for food.

Is this something that would be feasible to implement, and would the dev team find it a worthwhile endeavor?

**Comment by Raycoms** [comment]
Would be pretty easy to implement tbh

Am Mo., 29. Apr. 2019 um 16:53 Uhr schrieb ThePwnd <notifications@github.com

**Comment by ThePwnd** [comment]
Cool, is it something the dev team would find a worthwhile endeavor, or should I make a pull request?  I only have a little experience creating mods for Minecraft, and the little experience I do have comes from 1.7.10, but if you guys have your plate full, I could try my hand at it.

**Comment by Raycoms** [comment]
Would be nice if you could look into it

Am Fr., 3. Mai 2019 um 18:18 Uhr schrieb ThePwnd <notifications@github.com>:

**Comment by someaddons** [comment]
solved in https://github.com/ldtteam/minecolonies/pull/3631
