### ISSUE TITLE
[Request] Add default values to config file

### ISSUE THREAD

**Issue by DWX12** [ldtteam/minecolonies#3586]
Something that I had hoped that would become a standard practice is to place the default values for each option in the config file.

For example:
        Currently
        # Delay modifier to mine a block (Decreasing it, decreases the delay)
        I:blockMiningDelayModifier=500

        # Delay modifier to mine a block (Decreasing it, decreases the delay)
        # Default: 500
        I:blockMiningDelayModifier=500

This helps everyone out when they're making changes so that they don't have to delete the config or make a copy of it to be able to get the default values back.

Thank you guys for all of your hard work and dedication on this truly awesome mod.

**Comment by Asherslab** [comment]
huh, i would have thought forge did that for us. If you use the GUI for configs on the client it does include default values, so i would've assumed it'd do the same for file configs (as it does with comments and etc)

**Comment by DWX12** [comment]
I seldom change configs in-game and opt to change as much as I can through mods' config files. It's much more consistent than having some mods that you can and other mods that you can't change configs with. Plus, it's easier for me to be able to switch between Minecraft and Notepad ++ than going into configs through Minecraft.

**Comment by Elrol** [comment]
I can work on this tonight.
