### ISSUE TITLE
[Suggestion] Config option to remove chain mail recipes

### ISSUE THREAD

**Issue by DWX12** [ldtteam/minecolonies#3587]
Sometimes other mods add recipes for chain mail or server owners or pack makers might want to disable the recipe. I know the temporary solution is to use a mod like Craft Tweaker, but I'd much rather go through the official mod to remove it.

Thanks.

**Comment by marchermans** [comment]
Why are you asking us todo that?
We do not add a recipe for it.

**Comment by DWX12** [comment]
![2019-04-30_02 41 13](https://user-images.githubusercontent.com/37384543/56953482-8c004000-6af1-11e9-92ee-dc75785a3400.png)
![2019-04-30_02 41 04](https://user-images.githubusercontent.com/37384543/56953483-8dca0380-6af1-11e9-858e-a7ac87474ae4.png)

Any reason why this says that the recipe is added by Minecolonies then?

**Comment by Raycoms** [comment]
We added it to have a good recipe for the armor stands with chainmail and to have a cheaper armor for guards

**Comment by DWX12** [comment]
Thank you for reopening this issue and hope this option can be added in the future.

**Comment by marchermans** [comment]
Oooooh I am so sorry
I did not know this........
I would have never closed this if i knew that.....

**Comment by marchermans** [comment]
@DWX12 If you are on 1.12, recipes are controlled via resource packs
If you want to disable them
Just remove the recipe using a resource pack. There are enough tutorials out there.

**Comment by Asherslab** [comment]
it's very much feasible (note our stuff on the townhall recipe), but it would probably be better to do that via resource pack instead

**Comment by marchermans** [comment]
Especially since in 1.13 this stuff will all go away. Forge and Minecraft make that impossible.

**Comment by DWX12** [comment]
If this isn't going to be a possibility, then I'll just have to figure something out with CraftTweaker or another method.

Thanks for the replies. If there isn't any further progress on this subject of crafting recipes, chain mail or otherwise, then this issue can be closed.

**Comment by Raycoms** [comment]
yeah, overriding the recipes is probably the easiest here. Within the mod it would be very "messy" to offer a config value.
