### ISSUE TITLE
REQUEST - More Villager Interaction with the player aside jobs

### ISSUE THREAD

**Issue by RodrigoTaipe93** [ldtteam/minecolonies#3591]
First of all, let me say this mod is so fantastic! It easily competes with Millenaire and MCA.

However, the only thing that I feel it lacks is a more "interaction" with the villagers...like the marriage system or the quest/culture feature of Milleinare...
Aside from that, it's awesome!!

**Comment by Asherslab** [comment]
Please make a better name for your issue =D

**Comment by RodrigoTaipe93** [comment]
> Please make a better name for your issue =D

done! :D please please! Make the villagers skins editable, so we can have thanos in our world xD

**Comment by Raycoms** [comment]
Closed in favor of joint issue.
