### ISSUE TITLE
Colony Deletion Crash

### ISSUE THREAD

**Issue by Nightressa** [ldtteam/minecolonies#3592]
### Minecolonies version

Version: minecolonies-1.12.2-0.10.279-ALPHA

### Expected behavior
Delete the colony once i press delete

### Actual behaviour
  What actually happens when this feature is used in it's current state? 
  I misplaced the town hall block and wanted to reposition it. After repositioning it the builder DID not put the block back and asked if i wanted to delete the colony. So I go to delete the colony to start again. I start the deletion process and once i click delete after a few seconds the server crashes and when you try to rejoin after the server is up it crashes again as if the chunk the town hall block is corrupted. I went to test it in single player to recreate the crash by just straight up breaking the block in creative then queueing the colony for deletion. Still crashed-

Crash Log: https://pastebin.com/WwFx9SVd

### Steps to reproduce the problem

1. Break town hall block
2. Queue deletion of colony 
3. Crash

**Comment by Reploidsham** [comment]
Can confirm, a user on my server had the same issue and the server closes with a similar OOB. 

After trying to head near the deleted colony, I crash the server as well. The chunks themselves are unusable and are basically an unmanageable quarantine zone.

It still seems to exist in minecolonies-1.12.2-0.10.280-ALPHA as well.

**Comment by tainted-feathers** [comment]
This happened to me, same situation as OP. It happened in a singleplayer world, and when I try to load the world it crashes almost instantly.

**Comment by marchermans** [comment]
Yeah we are working on it. Looks like there is an issue when the Colony list is being updated.
