### ISSUE TITLE
Deliveryman stops working/parent cancellation failed

### ISSUE THREAD

**Issue by Leivel** [ldtteam/minecolonies#3593]
### Minecolonies version

Version: minecolonies-1.12.2-0.10.202-RELEASE-universal.jar

### Expected behavior

- Builder orders crafteable materials
- Miller goes to work
- Deliveryman brings requested items to the Miller
- Deliveryman brings requested items to Builder
### Actual behaviour

- Deliveryman delivers items and reaches the Builders request
- Following error message appears: https://prnt.sc/ndnw21 (NOTE: the id changes everytime)
- Deliveryman starts walking around town without carrying anything from this point forward
Resetting all requests by command sometimes works for a few minutes, but the error will sooner or later pop up as long as the Builder requests something.
This problem wasn't such an issue and it scarcely happened until I built the sawmill. From this point forward it was a 3-5 minutes occurence.

### Steps to reproduce the problem

1. Started Singleplayer world
2. Swapped pretty early on to server (and kept map, I think the builder was created but the deliveryman wasn't at this point)
3. After a while of play the error message shows up and the Deliveryman doesn't work anymore.

Additional info: "Keeping entity minecraft:sheep that already exists with UUID..." pops up also pretty often. At this point I dont have a sheep herder, but maybe this information helps.

If I can provide any files, please let me know.
Thanks

**Comment by marchermans** [comment]
@Leivel Thanks for the report: Could you download a custom jar from our buildsystem [here](https://teamcity.minecolonies.com/repository/download/LetSDevTogether_Minecolonies_Branches_Build/27591:id/build/libs/minecolonies-1.12.2-0.10.906-PERSONAL-universal.jar). It hopefully contains a fix for this problem.

I found an issue with the reporting of the completion of crafting and delivery tasks. So I hope this fixes it.

**Comment by Leivel** [comment]
Alright, thanks for the help.

I've tried out this version for a while. The bug still occurs, but only builders are affected now. The deliveryman still delivers items to other workers.
From time to time the deliveryman is haltet for x*100 seconds.
I'll attach the latest log and the debug log.
[latest.log](https://github.com/ldtteam/minecolonies/files/3153937/latest.log)
[debug.log](https://github.com/ldtteam/minecolonies/files/3153944/debug.log)

**Comment by marchermans** [comment]
@Leivel Try this again: https://teamcity.minecolonies.com/repository/download/LetSDevTogether_Minecolonies_Branches_Build/27599:id/build/libs/minecolonies-1.12.2-0.10.908-PERSONAL-universal.jar

It contains a fix for the crash that holds the DMan when he is done delivering.

**Comment by marchermans** [comment]
The builder seems to be a different problem @Raycoms Did you look into this already?

**Comment by Raycoms** [comment]
Still traveling

**Comment by Leivel** [comment]
The 1.12.2-0.10.908-Version seems to solve the problem with the deliveryman.
Occasionally the parent cancellation error pops up, but it doesn't affect the deliveryman anymore.
Sometimes the builders will just stand in front of the builder's hut block without requesting anything.
Giving them all the needed items solves this issue though. Reseting the build request doesn't work.

**Comment by Raycoms** [comment]
Will investiage the builder. Will close this issue then
