### ISSUE TITLE
courier/deliveryman only takes a single stack. builder is SLOW.

### ISSUE THREAD

**Issue by usafphoenix** [ldtteam/minecolonies#3594]
### Minecolonies version

Version: 1.12.2-0.10.259-RELEASE

### Expected behavior

Builder queries build order for upgrade/new building and puts in a request for the items that build requires. Deliveryman checks warehouse and delivers as many of the requested materials are available and he then can delivers them and places them (if space available) into builder's hut. If builder's hut is full, delivery man returns to stockroom and empties own inventory until a new request is placed (perhaps waiting a moment to see if space becomes available for a moment at builder's hut. 

- 

### Actual behaviour

Builder gets build order, and requests one item sort at a time. rather than a list of items. he then proceeds to the buildsite and starts building initially with that one material. as soon as he switches to a different material the build requires (and he doesn't have) he runs back and places ANOTHER request. waits for the deliveryman, then returns to the buildsite, only to require aNOTHER item. repeat * n-number of item types. 

- 

### Steps to reproduce the problem

Actually, as far as i'm aware, this is a known issue. perhaps by design. But if the deliveryman has an inventory, that is equivalent to about a chest. and so does the worksite blocks as well as the other workers...they should attempt to fulfill the builder's LIST of items required for a specific building. otherwise (and this is compounded by larger and larger colonies) it takes forever to build UNLESS you manually place everything the builder needs directly into his inventory, circumventing the NEED for the deliveryman. 

1. 
2. 
3. 
4. ... Profit

**Comment by Seba244c** [comment]
I can confirm that two!

**Comment by usafphoenix** [comment]
tried moving things around. Builder ended up getting self stuck and going in a loop trying to find a pathinig to build something i told him to build, but he was being stupid and going through a building that only had one entrance....kept getting stuck....so i murdered him. I stabbed him twice.

**Comment by usafphoenix** [comment]
okay, so i found out what was going on on the wiki, but it wasn't anywhere else: an ingame documentation / manual would be very helpful. The deliveryman only carries a single stack when they're first level. As the deliveryhut upgrades, they're able to carry more. Not sure if this will correct the builder only requesting a single item at a time, but i'll do some more testing.....

**Comment by Raycoms** [comment]
Yeah, we got an issue for that already to have the builder request more. Is a future feature to come.
