### ISSUE TITLE
Builders filling space with dirt one by one

### ISSUE THREAD

**Issue by fr3akb0y** [ldtteam/minecolonies#3598]
### Minecolonies version

Version: minecolonies-1.12.2-0.10.280-ALPHA-universal for MC 1.12.2

### Expected behavior

- The Builder should take the amount of dirt he needs to fill the rest of the emty space.

### Actual behaviour

- Whenever you terraform in the area of a building currently under construction and make a hole in the ground where dirt/grass actually needs to be, the Builder then tries to fill that hole that you made with dirt. However, if he runs out of dirt in his inventory before he finishes filling up the hole, he will walk back to get more dirt. Right after he pulls dirt out of the chest he puts back all of that dirt except for 1 and goes back to placing dirt. He does that every time until that manually created hole is finished filling up. This process can make him extremely slow if you dont help him. (he seems to be only checking for the next missing block after the initial scan for what he needs if something becomes wrong while building (he also wont update the resource list if he needs more dirt than initially scanned for))

Manually made hole in a place where dirt/grass needs to be that the Builder fills up 1 by 1:
![2019-05-08_20 43 05 - Kopie](https://user-images.githubusercontent.com/33865311/57404063-5e935080-71db-11e9-9d53-e38d81966b17.png)

### Steps to reproduce the problem

1. Start constructing a new building with a Builder
2. Wait for the initial resource need scan and start removing some terrain where the Builder will refill that area with dirt
3. Wait for the Builder to reach the point where you removed some block and remove all dirt from the Builders inventory (the building chest should still have dirt in it)
4. ... Profit

**Comment by Raycoms** [comment]
Yeah this is true, it's because the builder takes as much dirt with him as he thinks he needs. I think we should probably rescan the building area when we encounter this problem.

**Comment by fr3akb0y** [comment]
I also noticed today that he does that with all resources (got to see it while the lumberjack cut down the citizen house >.< (tree spawned near it so the wood connected with the house)) so yeah that is probably a solution. Also while the lumberjack cut down the house he requested a pickaxe and mined some of the stone dont know why xD

**Comment by Raycoms** [comment]
Addressed in a PR
