### ISSUE TITLE
Composter Hut 3 bugged in latest version

### ISSUE THREAD

**Issue by JevorTrilka** [ldtteam/minecolonies#3599]
### Minecolonies version

Version: MineColonies Official modpack v 2.0, so MineColonies mod v 1.12.2-0.10.280-ALPHA

### Expected behavior

- The Composter Hut to get upgraded.

### Actual behaviour

- When going from level 3 to 4 the builder just went bonkers and destroyed the building and terrain next to the existing Composter Hut and built the new building nearly 40 blocks away. (I have a screenshot but don't know how to send it to you.)

### Steps to reproduce the problem

1. All I did was try to upgrade from Composter Hut 3 to 4.

**Comment by JevorTrilka** [comment]
Oh, and I forgot to mention this happened twice in a row, so... Yeah...

**Comment by Talyda** [comment]
What style building were you using?

**Comment by Talyda** [comment]
I'm gonna guess wooden? Cos I just previewed that one and the preview is very odd!

**Comment by JevorTrilka** [comment]
Oh yeah, forgot to mention that too... Haha. But yeah, it was the wooden one.

**Comment by Raycoms** [comment]
@lunadragnstar I guess this one needs to be rescanned

**Comment by lunadragnstar** [comment]
Rescanned
