### ISSUE TITLE
Bugged Logger Inventory Access

### ISSUE THREAD

**Issue by Falcon7617** [ldtteam/minecolonies#360]
Current Version

Can't access logger's inventory

No idea why, but I relogged to see if it was just server lag, and to no avail.

Please fix.

**Comment by marvin-bitterlich** [comment]
Please post logs and screenshots of your lumberjack

are you playing locally or on a server? more infos please

**Comment by Falcon7617** [comment]
I was on the server.

I killed my lumberjack and rebuilt the building.

The lumberjack works fine now.
