### ISSUE TITLE
Children Won't Grow Up

### ISSUE THREAD

**Issue by hotluck** [ldtteam/minecolonies#3600]
### Minecolonies version

Version:  259 Release

### Expected behavior

Children to grow up and become workers.

### Actual behaviour

I am hoping this is just a setup I am missing. I keep creating more citizen huts and every time I do, I get a child. That would be fine but I have now have 3 children who won't grow up. The first one has been there for at least 70 minecraft days. I even changed the config file to speed the growth rate, but no change. They aren't starving or anything. Am I doing something wrong? I can't increase my colony without more workers! Please help because I am loving the improvements you keep making to this mod and I don't like playing the game without it :)

### Steps to reproduce the problem

I couldn't tell you what steps i took because it wasn't until the third child had arrived that I noticed the first 2 were still children.

**Comment by Raycoms** [comment]
Kids only grow up when they are not hungry, did you check for that?

**Comment by Nightenom** [comment]
@Raycoms
> They aren't starving or anything.

**Comment by Raycoms** [comment]
Weird, can you update to the latest alpha and double check?

**Comment by hotluck** [comment]
Okay, I will try that now :)

**Comment by hotluck** [comment]
Sadly that didn't fix it...still have 3 children. One question - what are the stat bars on each citizen. I know the first is health and the second is food, but what are the green and purple ones? The green one is 0 on all the children.

**Comment by Nightenom** [comment]
green = xp (obviously 0), purple = happiness. see wiki for more info

**Comment by Raycoms** [comment]
@someaddons can you take a look at this?

**Comment by someaddons** [comment]
what did you set the config value to?

**Comment by hotluck** [comment]
It was 1 but a few hours after I realised the problem I read about the config parameter and changed it to 5 before restarting the game. It has been 5 ever since.

**Comment by hotluck** [comment]
> green = xp (obviously 0), purple = happiness. see wiki for more info

Thanks for that. I had looked in the wiki before asking but couldn't find that info.

**Comment by hotluck** [comment]
Any luck with this?

**Comment by someaddons** [comment]
@hotluck could you try this build for a while? and keep your childs fed/chunks loaded there for a while
https://teamcity.minecolonies.com/guestAuth/repository/download/LetSDevTogether_Minecolonies_Branches_Build/28160:id/build/libs/minecolonies-1.12.2-0.10.919-PERSONAL-universal.jar

**Comment by hotluck** [comment]
I will try it out when I wake up in the morning (if my kids let me on the pc lol) :)

**Comment by hotluck** [comment]
I want to hug you. Whatever you did to the code has fixed it. They've all started growing up. I can play my world again. Thank you 😁

**Comment by someaddons** [comment]
perfect :)

**Comment by CameraCow** [comment]
I'm having this same issue and the link doesn't work anymore. I have to end up killing the children after several days and just recruiting new citizens but it's getting expensive. Anyone know why they won't grow up?

**Comment by Talyda** [comment]
Are you on the latest alpha CameraCow?

**Comment by CameraCow** [comment]
I'm using the mod pack version through twitch, I believe it is the latest one, but I could be wrong

**Comment by someaddons** [comment]
keep them fed and they'll grow after a while, takes some patience
