### ISSUE TITLE
Building Outside Colony Border

### ISSUE THREAD

**Issue by Electrocutor** [ldtteam/minecolonies#3602]
### Minecolonies version
Version: 0.10.280-alpha

### Expected behavior
Builder/Miner will either build where they should or give an error about placement

### Actual behaviour
If you place a building hut at the edge of your colony border, the builder will only build blocks that go up to the hut block, anything past that, the blocks are instantly deleted, but he keeps "building" anyway, losing all blocks to deletion.

If the miner tries to mine/build framework past the colony border, he gets locked up and has be fired-rehired in an attempt to make him pick a different direction.

### Steps to reproduce the problem
1. Place a hut block at the very edge of colony border (prefer something big, like barracks so it is obvious.
2. Attempt to build it.

**Comment by Electrocutor** [comment]
[Update]
After a server reboot, this behavior was no longer present and the builder returned to building as normal without deleting any blocks.

**Comment by marchermans** [comment]
@Raycoms problems with claiming?

**Comment by Raycoms** [comment]
Will have to check this.

**Comment by Raycoms** [comment]
I checked it out, this is more likely a problem which is related to sponge or a permission plugin.
Minecolonies doesn't stop building as long as the hut block is within the own colony.
