### ISSUE TITLE
Game crashes upon placing town hall

### ISSUE THREAD

**Issue by TheArbinator** [ldtteam/minecolonies#3603]
### Minecolonies version

Version: 0.10.259 RELEASE

### Expected behavior
 Once the Town Hall is placed, the town would be created as expected.

### Actual behaviour
 Once the Town Hall is placed, the game drops to 1 frame per second, and a few seconds later, crashes.

### Steps to reproduce the problem

1.  Obtain Town Hall
2.  Place Town Hall using Building Tool
3.  Wait for frame drops and crashes
4. ... Profit

**Comment by Raycoms** [comment]
Log please

Am Sa., 11. Mai 2019 um 17:26 Uhr schrieb TheArbinator <
notifications@github.com>:

**Comment by Raycoms** [comment]
Closed until log is provided.
