### ISSUE TITLE
custom buildings for april 12 release

### ISSUE THREAD

**Issue by Phaserra** [ldtteam/minecolonies#3605]
### Minecolonies Version

Version: 1.12.2 (1.12.2-0.10.259-RELEASE )

### Expected behavior

 I'm having trouble building custom buildings like the bakery, whereas citizen huts are namely called citizen1.blueprint , doing baker1.blueprint doesn't work like it says in the wiki. It said that it was the version back on 22 March 2019.. So has the names changed?

### Actual behaviour
Only Certain buildings use the names..

### Steps to reproduce the problem
Make a shack with a bakery, scan it. Name it Shack/Baker1. Move it from scan to structurize. Reveal the fact that you can't get a builder to build it because it isn't there.

Help

**Comment by Asherslab** [comment]
https://github.com/ldtteam/minecolonies/tree/version/1.12/src/main/resources/assets/minecolonies/schematics/wooden

All schem names can be found here
It would seem that you need Baker1.blueprint, however capital letters shouldn't matter IIRC

**Comment by Raycoms** [comment]
capital matters do probably matter. Especially depending on the OS
