### ISSUE TITLE
Tried to read NBT tag that was too big; tried to allocate: 2097216bytes where max allowed: 2097152

### ISSUE THREAD

**Issue by glepet1962** [ldtteam/minecolonies#3606]
Version: minecolonies-1.12.2-0.10.281-ALPHA-universal.jar	

I have VanillaFix in modpack. It begins spamming this issue: 

Included crash log:
[crash-2019-05-12_06.12.39-client.txt](https://github.com/ldtteam/minecolonies/files/3170043/crash-2019-05-12_06.12.39-client.txt)

doing a /mc rs reset stops the issue temporarily

**Comment by Raycoms** [comment]
Does this issue return after a while again? After the rs reset?

**Comment by glepet1962** [comment]
Yes. After doing the rs reset, after 3-4 minutes it happened again. I was doing nothing but walking around the colony.

**Comment by Raycoms** [comment]
@OrionDevelopment there seems to be a leak somewhere?

**Comment by Nightenom** [comment]
How this can happen now, I would really like to know
https://github.com/ldtteam/minecolonies/blob/version/1.12/src/main/java/com/minecolonies/coremod/colony/ColonyView.java#L228

**Comment by Raycoms** [comment]
Because this only checks the size of the Request manager and not the size of the entire view.

**Comment by Nightenom** [comment]
but it crashes on the read nbtcompound not whole bytebuf

> Caused by: java.lang.RuntimeException: Tried to read NBT tag that was too big; tried to allocate: 2097216bytes where max allowed: 2097152
>     at com.minecolonies.coremod.colony.ColonyView.handleColonyViewMessage(ColonyView.java:579)

**Comment by Raycoms** [comment]
Ahh, weird...

Am So., 12. Mai 2019 um 10:02 Uhr schrieb Nightenom <
notifications@github.com>:

**Comment by Nightenom** [comment]
The only possibility I can see is that `colony.getRequestManager().reset()` didnt somehow clear the rs

**Comment by Nightenom** [comment]
@glepet1962 Can you send us the world?

**Comment by glepet1962** [comment]
update: I did another rs reset around 6:41 and have not had it happen since (now 7:40).  I have been in the colony the whole time. I closed the game out during this time when I removed a couple mods, and then started up again. Not having any issues yet. 
Maybe the first rs reset didn't take, but the second did?
I've never sent a world, what file(s) would I need to send?

**Comment by Nightenom** [comment]
If it occurs again then zip the world folder under .minecraft/saves

**Comment by marchermans** [comment]
As @Nightenom No idea how this happens since it should kill it self.
The reset can not not take, it overrides local fields directly by creating a new instance of the datastore manager, as well as new Central datastores and resolvers for retrying and Player so unless @glepet1962 can actually reproduce this again, I would put some money on: Something somewhere does something stupid

**Comment by K1ngAdi** [comment]
I run into the same issue with the following report: 
https://paste.dimdev.org/ceyiyexovu.mccrash

**Comment by K1ngAdi** [comment]
but it stopped when it became night and restarted after a couple of minutes after i slept

**Comment by gleybergood** [comment]
Same problem here 

https://paste.dimdev.org/metehosiha.mccrash

**Comment by marchermans** [comment]
Please update to a newer Version.
