### ISSUE TITLE
Incorrect/changing footprint size in Wooden Town hall

### ISSUE THREAD

**Issue by Talyda** [ldtteam/minecolonies#3608]
I was in creative trying to replicate a bug I had in my level 4 wooden citizen hut on the server (I couldn't walk through the doorway for some reason  - I broke the doors so I could get in and it gave me 4 doors - replaced them still couldn't walk through, but after server reboot I can again) 

Anyway, while I was there, I played with the wooden town hall too, and that one is different sized footprints as I scroll through the levels of building.

Also in the level 4 wooden citizen hut, the citizens that sleep on the top floor are getting stuck on the bed where the upside down stairs are.  All happening in version .282

**Comment by lunadragnstar** [comment]
Fixed and rescanned
