### ISSUE TITLE
[Improvement] Specify allow recipe on restaurant

### ISSUE THREAD

**Issue by orblazer** [ldtteam/minecolonies#3610]
Hello,

I play on modpack `Life in the village - 1.11` and in this have DungeonTactics and MoreCharcoal. This make problem in restaurant because cooked meat make leather and all other make charcoal like.

For fix that i propose same interface for fuel for available recipe (or simply register recipe like stone smeltery)

Note: With MoreCharcoal the citizen wont eat.
Thanks.

**Comment by Raycoms** [comment]
I will make an easy fix by requiring the result of the cooking process also being food

**Comment by markuskoeppen** [comment]
I am currently using 0.10.298 Alpha as a manual replacement with Life in the Village 1.11.

Unfortunately, this problem persists with cooked fish being processed to leather (which vanishes?).
