### ISSUE TITLE
Items with furnace recipe are 'raw', even if resulting item isn't food

### ISSUE THREAD

**Issue by therodet** [ldtteam/minecolonies#3613]
### Minecolonies version

Version: minecolonies-1.12.2-0.10.259-RELEASE-universal

### Expected behavior

Cooked food should be considered edible
- 

### Actual behaviour

Food that is cooked, but which has a furnace recipe for another item, even if that item is not edible results in that food being considered raw. Colonists will not eat it, and the cook will cook the items into items that may not be food
- 

### Steps to reproduce the problem

The issue is specifically being experienced in the mod pack "Life in the Village"
Many cooked meat items can cooked into leather (don't know what adds that), and bread can be  cooked into charcoal (More Charcoal mod)
Give meat or bread to the cook, and it will get cooked into leather/charcoal
Give meat/bread to colonist and they will complain food is too raw

**Comment by Raycoms** [comment]
Same issue: #3610
