### ISSUE TITLE
Dark Oak Blacksmith Level 1 error

### ISSUE THREAD

**Issue by kd5crs** [ldtteam/minecolonies#3614]
### Minecolonies version

Version: minecolonies-1.12.2-0.10.283-ALPHA-universal

### Expected behavior

- Dark Oak Level 1 Blacksmith would be in the same position as levels 2-5.

### Actual behaviour

- Dark Oak Level 1 Blacksmith is mis-scanned such that it is several blocks up and to the side from levels 2-5.

### Steps to reproduce the problem

1. Place preview of Dark Oak Blacksmith Level 1.
2. Switch to Level 2-5.
3. Note wierdness.
4. ... Profit

**Comment by lunadragnstar** [comment]
Rescanned and uploaded
