### ISSUE TITLE
Dark Oak Barracks build error

### ISSUE THREAD

**Issue by kd5crs** [ldtteam/minecolonies#3615]
### Minecolonies version

Version: minecolonies-1.12.2-0.10.283-ALPHA-universal

### Expected behavior

- After Dark Oak Barracks is placed, click Build to start build process.

### Actual behaviour

- Barracks block is placed, right clicking the block flashes up an error in the middle of the screen. Something like ... minecolonies.... upgradeRepair? It is too fast to catch. Clicking the build button does nothing. Village has several other buildings without issue.

### Steps to reproduce the problem

1. Place Dark Oak Barracks.
2. Right click on it.
3. See very fast blink of error message.
4. ... Profit

**Comment by kd5crs** [comment]
Ok, that's wierd, I experienced this bug every time I tried to build the barracks over the last two days, then I wrote this error report, and when I went back to Minecraft it works. So, uh. Dunno.

**Comment by lunadragnstar** [comment]
Closing, if it happens again, reopen this.

**Comment by Raycoms** [comment]
Will push a fix for the barracks build button in a few hours.
