### ISSUE TITLE
No barracks-tower placeholder for taiga barracks

### ISSUE THREAD

**Issue by Kairosy** [ldtteam/minecolonies#3620]
### Minecolonies version

Version: minecolonies-1.12.2-0.10.286-ALPHA

### Behavior

 For the other styles of the barracks, there is the barracks tower placeholder which allows for the barracks tower to be built, however in the taiga style of the barracks the placeholder is missing, and the tower does not get built. 

### Images

-- This is a picture of the medieval oak crafting materials (Notice the placeholder and the tower gets built)
![image](https://user-images.githubusercontent.com/32999346/58085770-5cda6d00-7b8b-11e9-9f23-aa4524de5532.png)

-- This is a picture of the barracks with the taiga style (No placeholder, and no tower gets built.)
![image](https://user-images.githubusercontent.com/32999346/58085737-4e8c5100-7b8b-11e9-9fda-37483dd07c50.png)

**Comment by lunadragnstar** [comment]
Uploaded
