### ISSUE TITLE
Randomly throughout playthrough, workers randomly stop working. 

### ISSUE THREAD

**Issue by Myo0** [ldtteam/minecolonies#3621]
Version: Minecolonies-1.12.2-0.10.286-ALPHA-universal.jar (most recent as of this post on May 21st, 2019)

All workers should just continue building and fulfilling what their job is.

Everything initially goes great, but at some point seemingly randomly throughout what I am doing they just stop working. They walk around like normal citizens as if they have nothing to do. When I close my game and reopen it, everybody goes to their respective job chest and then they act like normal citizens again. (Note, I am currently using the tornado mod with this, not sure if this could be the issue or not, in previous versions when I played 1.10 it did not affect minecolonies.) The only way to avoid this is to create a new world, and I would rather not have to scrap my current world, or at the very least know that this will be fixed in a future build.

![2019-05-21_16 08 27](https://user-images.githubusercontent.com/50885209/58121849-e406ff80-7be2-11e9-8cde-72673d1b6f6d.png)
Note how it says that this builder is going to build cook1. They went to their builders chest then every worker started behaving as normal citizens.
![2019-05-21_16 08 35](https://user-images.githubusercontent.com/50885209/58121882-f84afc80-7be2-11e9-95a0-c6046fbe8dc5.png)
![2019-05-21_16 08 47](https://user-images.githubusercontent.com/50885209/58121887-faad5680-7be2-11e9-84da-9358bbe8f8e7.png)

Steps to reproduce: Honestly I have no idea, all I did was progressively grow the colony and let the tornado mod go through without editing it.

1. Just play it normally (though I give them infinite resources)

**Comment by Raycoms** [comment]
Those weather mods don't work well with minecolonies. They add that the weather is "raining" and our workers stop working.
