### ISSUE TITLE
No New Citizens

### ISSUE THREAD

**Issue by maizonya** [ldtteam/minecolonies#3622]
I'm playing this mod, I have a max citizen number of 16, and a house of every level. But, I only have 4 citizens, and the Citizen Recruitment doesn't work.. I dont know what to do

**Comment by ArodSnaux** [comment]
So they made some changes recently that may be affecting you: adding houses no longer auto-adds adult citizens. Instead, you must have **a male and a female citizen living together in the same house**, and **have a free bed i**n that house or another one. Once this happens there is a chance each night for a child to be born.

So basically, at night, sneak into the houses and make sure at least one house has both a male ana female in it. If no houses have this, you wont grow your population. Also, citizen recruitment will not work if there are no free beds, and also will not work if you do not the required items (hay, books, emerals diamonds i think) in your inventory.

Or it might just be a bug. Try doing a RECALL CITIZENS at your townhall to see if that fixes it. Or maybe grab  a more recent build of the mod.

**Comment by Raycoms** [comment]
^
