### ISSUE TITLE
Pirate Captains too Overpowered 

### ISSUE THREAD

**Issue by ArodSnaux** [ldtteam/minecolonies#3623]
minecolonies-1.12.2-0.10.285-ALPHA-universal

At least in the latest alpha, the Pirate Captains in the largest ship are WAY too overpowered for _any_ number of guards to handle. Or rather, maybe they are over-armored? One captain I saw had a reasonable 85hps, but hitting him with a +5 sharpness diamond sword barely scratched him, and it took over 50 arrows form a similarly enchanted bow to actually drop him.

ONE of these guys would be ok as a nemesis boss... but because they are tied to spawners we are talking about dozens of these guys at a time... maybe you should tone them down a bit? Or maybe just spawn one per ship?

They wiped out half the town before I could type /mc raiders kill; and that was after wiping out numerous level 30+ guards all in enchanted armor and magic weapons.

Or maybe there is a special weapon to hurt them harder like axes with ents? If so, that should be in the wiki.

The normal pirates are fine though, although the spawner system spews them out a little fast (maybe we can configure the spawn rate in the ini file?)

Keep up the good work, love the mod.

**Comment by Raycoms** [comment]
what difficulty do you have the mod on?

Am Mi., 22. Mai 2019 um 21:47 Uhr schrieb ArodSnaux <
notifications@github.com>:

**Comment by ArodSnaux** [comment]
Fairly low, 5 difficulty and a maxnum of 40. By comparison, Barbarian Chiefs are spawning at 160 hps and are easily defeated by the very same guards who are then getting destroyed by the Pirate Captains. I think the Captains have WAY too much damage reduction in their armor, and also spawn too frequently... opening the cabin door on the big ship released like... 20 of them?

**Comment by Raycoms** [comment]
okay, I will reduce this a bit then.

>

**Comment by ArodSnaux** [comment]
Thanks. Also, a suggestion... since you are using spawners for the pirates, why not use several multi-spawners instead of a dedicated one for each mob type, so the spawn rates are a little balanced? There is an excellent example at https://minecraft.gamepedia.com/Tutorials/Command_blocks_and_functions about 2/3 of the way down the page, under  Part 3: SpawnPotentials. He shows how to make one spawner that spawns 6 different mobs... I figure 10 normal pirates per captain might be a good start, and that way you don't get overwhelmed by captains when you open that cabin door.
