### ISSUE TITLE
Feature Request: Recruitment Price Cap

### ISSUE THREAD

**Issue by ArodSnaux** [ldtteam/minecolonies#3624]
I love the idea of paid citizen recruitment, I dislike the implementation.

1) Doubling the price for each recruit is understandable (breeding is preferable) but maybe put a cap on it in the config file, say default it to 250 max? That way you can still recruit viable adults  in a pinch, say after a particularly bad raid.

2) Why does recruiting a lowbie guy (hay) double the price for the godlike guy (diamonds)??? This make no sense, they should be separate stats.

3) Maybe some adult citizens should still appear randomly, maybe as a reward for defeating a raid ie "Word of your great victory has spread... Refugees from a distant land have arrived seeking protection!"

4) If I can request a diamond sword from the Mailbox, why not be able to request a Citizen with certain stats (ie high str and end)????

Keep up the good work, this mod is why  I still play Minceraft!!!

**Comment by Raycoms** [comment]
1) Yes, a cap does sound like a good idea.
2) We wanted to cap the overall quantity of people you can hire, so we
decided on doing that by increasing all prices
3) Yes, that is planned
4) That's a bit complicated. With a future economic system we might
incorporate this.

Am Mi., 22. Mai 2019 um 22:01 Uhr schrieb ArodSnaux <
notifications@github.com>:

**Comment by GanthorPrime** [comment]
i always wanted some kind of reward by citizens reaching lvl 99, considering they max theirs jobs abilities at 32, and you get nothing after that.   maybe the ability to consume these citizens lvls to reduce the recruitmen cost (high lvl workers increase the town prestige, so more ppl are willing to join the town, thus you need to pay less)
