### ISSUE TITLE
Cannot delete colony ID

### ISSUE THREAD

**Issue by MyWorldNetwork** [ldtteam/minecolonies#3626]
### Minecolonies version

Version: minecolonies-1.12.2-0.10.286-ALPHA-universal.jar

### Expected behavior

Incorrectly placed Town Hall block to be deleted when instructed.

### Actual behaviour

The Town Hall block itself is gone however the colony ID (1) remains active and I cannot delete this regardless of how many times I click [DELETE] to confirm. This had initially caused chunk corruption where I was unable to log in without crashing both my client and server. I managed to resolve this by both upgrading from 280 to 286 AND deleting my Playerdata but on testing 24 hours later the colony ID still exists.

### Steps to reproduce the problem

1. Place Town Hall block
2. Destroy Town Hall block
3. Attempt to place a new Town Hall block
4. Click [DELETE] when prompted to delete colony ID
[latest.log](https://github.com/ldtteam/minecolonies/files/3219683/latest.log)

**Comment by MyWorldNetwork** [comment]
Interestingly, while in Creative, i can place a Town Hall block which uses the same ID and which has just spawned a settler

**Comment by Raycoms** [comment]
I checked through the log but I can't find anything related to this. Following the log it was successful. Are you able to reproduce this somehow?

**Comment by MyWorldNetwork** [comment]
I can reproduce this endlessly if not in creative. The log entries which relate are;

[20:33:29] [Server thread/INFO] [minecolonies]: Removing citizens for 1
[20:33:29] [Server thread/INFO] [minecolonies]: Removing buildings for 1
[20:33:29] [Server thread/INFO] [minecolonies]: Deleting colony: 1
[20:33:29] [Server thread/INFO] [minecolonies]: Done with 1

However nothing is actually deleted and without being in creative.

**Comment by Asherslab** [comment]
i believe he meant, can you reproduce this in a new world. give a few steps
(E.g. new world, place town hall, delete colony, doesn't work) or whatnot =D

**Comment by sentinel618** [comment]
That was absolutely not clear or even implied...

**Comment by Raycoms** [comment]
I'll close this for now. Seems to me like a one time bug.
