### ISSUE TITLE
Ops cannot remove MineColony Boxes

### ISSUE THREAD

**Issue by devanchya** [ldtteam/minecolonies#363]
This is tested with the last 3 1.10 releases of MineColony as of Dec 20 2016.

Ops on Multiplayer servers cannot remove MineColony boxes (such as the miner) as they pop back immediately.   This is hurting servers that need the Miner removed due to previous code changes and the user has not returned since.

**Comment by xenoflot** [comment]
You're running into the anti-griefing mechanism which is being discussed over in #292 

Try...
/mc colony delete <playername>

If that doesn't work immediately, update to the beta build linked in 292 because it does work in that.

**Comment by Raycoms** [comment]
In some rare cases the boxes don't get removed accordingly. That's quite
strange but we weren't able to reproduce it in the development environment
yet in order to fix that bug.

2016-12-24 22:43 GMT-02:00 xenoflot <notifications@github.com>:

**Comment by Raycoms** [comment]
Please reopen if able to reproduce.
