### ISSUE TITLE
Builders are working WAY too slow

### ISSUE THREAD

**Issue by iTheCuteKitten** [ldtteam/minecolonies#3633]
### Minecolonies version

    Mine Colonies Build 288 Alpha

Version:  1.12.2

### Expected behavior
Builders taking all the supplies out of the builder's chest (At least as much as they can possibly carry) and walking over to the designated area that they need to build and build it all unless they need a tool or something or if they need to go grab more materials if one chest won't fit it all.

### Actual behaviour

Builders taking a small amount of blocks and not even using all of the blocks they just took out of the chest and walking back to their hut for no reason to grab more blocks, and every time they go to the thing that needs to be built they place 1 - 5 blocks and walk back to their hut

### Steps to reproduce the problem

1. Go on a singleplayer world with superflat and creative and place a townhall
2. Place a builders hut with the builders wand and build it.
3. Place any building and watch them be a snail
4. ... Profit

**Comment by ArodSnaux** [comment]
This is kinda normal actually, but I agree, it's annoying sometimes. The builders work from the ground up, "top right to bottom left" so to speak and therefore only take what they need to get that section done. As I understand it though more experienced builders work faster and grab more stuff, I think.

Also, you can config the build speed in the Mod Settings page, which I highly recommend. the default settings are REALLY slow, especially for removing blocks.

**Comment by someaddons** [comment]
should be better in 289
