### ISSUE TITLE
Game crashes when loading world

### ISSUE THREAD

**Issue by TwmMeredydd** [ldtteam/minecolonies#3634]
### Minecolonies version

Version: 1.12.2-0.10.259-RELEASE-universal

### Expected behavior

The game does not crash when loading the world

### Actual behavior

The game crashes when loading the world

[crash-2019-05-29_10.35.46-server.txt](https://github.com/ldtteam/minecolonies/files/3231861/crash-2019-05-29_10.35.46-server.txt)

### Steps to reproduce the problem

1. Create a world
2. Create a colony
3. Progress through the mod
4. Watch the game suddenly crash
5. Re-open Minecraft
6. Load the world
7. ... Profit

**Comment by someaddons** [comment]
the error you posted doesnt seem to be related to minecolonies at all, but to optifine

**Comment by marchermans** [comment]
This is not related to minecolonies as far as I can see. Closing.
