### ISSUE TITLE
Villagers Won't Move By Themselves

### ISSUE THREAD

**Issue by jelaw21** [ldtteam/minecolonies#364]
### Minecolonies version

version 1.10.2-0.6.2033
Forge version: forge-1.10.2-12.18.2.2171
Spongforge Version: spongeforge-1.10.2-2171-5.1.0-BETA-2000 

### Expected behavior

- Villagers are to move on their own when chunk is loaded.

### Actual behaviour

- Villagers only move, smoothly, if player is in chunk with them. Otherwise they move at what seems 1/8 pace,

**Comment by Raycoms** [comment]
That's a problem with the sponge settings with entities and not our mod.

Am Dienstag, 20. Dezember 2016 schrieb jelaw21 :

**Comment by jelaw21** [comment]
Is there a config i  sponge to help with it?

**Comment by Raycoms** [comment]
Yes Inside The Sponge Configs There is a setting for how many chunks
entities are still loaded you have to increase this to the amount you'd
like

Am Dienstag, 20. Dezember 2016 schrieb jelaw21 :

> Is there a config i sponge to help with it?
>
> On Dec 20, 2016 1:58 PM, "Raycoms" <notifications@github.com

**Comment by jelaw21** [comment]
thanks.

**Comment by Raghounet** [comment]
Hello 

could you tell me what option in sponge config file I must increase, because I don't find it ?

**Comment by jelaw21** [comment]
There is an option in the modules section of the sponge config for entity
activation range, I turned that off.

**Comment by Raghounet** [comment]
Ok thanks a lot ^^

2017-01-17 14:33 GMT+01:00 jelaw21 <notifications@github.com>:

> There is an option in the modules section of the sponge config for entity
> activation range, I turned that off.
>
