### ISSUE TITLE
Sawmill/Stonemason not working

### ISSUE THREAD

**Issue by hotluck** [ldtteam/minecolonies#3645]
Version: Personal version from Children Won't Grow Issue

### Expected behavior

When builders request items that the Sawmill and Stonemason can make, they should make them when the deliverymen bring the items needed to make them.

### Actual behaviour

The builder requests the items, the bits to make them are at the Sawmill but the worker doesn't go to the Sawmill, and when recalled, does nothing.

The builder has the request...
![image](https://user-images.githubusercontent.com/11139297/58704512-2f1fd000-83a4-11e9-9fed-aadee9ee6539.png)

When I get to the Sawmill, no-one is there...
![image](https://user-images.githubusercontent.com/11139297/58704569-6db58a80-83a4-11e9-8207-582e72b7b50b.png)

I recall the worker and she just stands there doing nothing...
![image](https://user-images.githubusercontent.com/11139297/58704618-976eb180-83a4-11e9-93d0-042f2c14bbfb.png)

The Sawmill shows the items in there to make the requested item...
![image](https://user-images.githubusercontent.com/11139297/58704671-b705da00-83a4-11e9-9a80-acb0cc899aeb.png)

The recipe has been learned...
![image](https://user-images.githubusercontent.com/11139297/58704745-f2080d80-83a4-11e9-87e8-d605bba1c873.png)

And the worker is happy and fed...
![image](https://user-images.githubusercontent.com/11139297/58704781-0815ce00-83a5-11e9-8932-7a7653033a72.png)

The Stonemason is exactly the same.

Now this is the first time I have built these workshops since they were added to the mod so I am assuming that they don't create items unless a builder requests them.

My questions are these -

1) Do the items only get created when the builder requests them or when the item is required as soon as a new build is started?

2) Do the workers needed the the total materials needed before they will create the item?

3) Do you need a postbox for this to work properly?

4) Or have I found a bug?

If there is anything else you need from me, just let me know :)

P.S. It didn't show it but even though there were only some of the dark wood planks in the inventory, there is plenty of dark wood in the warehouse (2 delivery men) and she knows the recipe to change the wood to planks.

**Comment by someaddons** [comment]
version is 0.10.287 btw

**Comment by someaddons** [comment]
could you check with /mc citizens info colony: 1 citizen: 1  what he's doing atm and post it here? note that the 1 for colony and the 1 for citizen gotta be adjusted for whatever ids your colony has and which id the citizen has(can just test numbers for this)

**Comment by schafhierte204** [comment]
I think this is the result of #3280. The request is still in the deliver required resources to crafter stage

**Comment by marchermans** [comment]
This was patched yesterday in the newest alpha.

**Comment by YosemiteSam3003** [comment]
> This was patched yesterday in the newest alpha.

Im still having the same problem with the stonemason today. Im using 1.12.2

**Comment by Raycoms** [comment]
Oh, the bigger patches only get to 1.15.2 atm. We don't have the capacity unfortunately to port all the changes to other versions.

**Comment by YosemiteSam3003** [comment]
> Oh, the bigger patches only get to 1.15.2 atm. We don't have the capacity unfortunately to port all the changes to other versions.

Thank u for the fast reply but do u know any troubleshooting ideas I could do?

**Comment by Raycoms** [comment]
Usually /mc colony rs reset solves a lot of the issues in this regard on 1.12

**Comment by YosemiteSam3003** [comment]
> Usually /mc colony rs reset solves a lot of the issues in this regard on 1.12

U are a lifesaver

**Comment by slendeboy88** [comment]
Hey i am having the same issues is there a way  I can port my world too 1.15.2 with all my minecolonies stuff there?

**Comment by Raycoms** [comment]
No, you can't port a world from 1.12 to 1.15

**Comment by Cosmology2727** [comment]
I'm having this same issue, and typing "/mc colony rs reset" gives me red text saying stuff like "info:delete:shl:barbarians...."
How do I actually do that command? And what exactly does the reset do?

**Comment by ravenbuilder934** [comment]
Are you on 1.12? What minecraft version are you on?

**Comment by Cosmology2727** [comment]
Minecraft 1.12.2
minecolonies-1.12.2-0.11.811-BETA-universal

**Comment by ravenbuilder934** [comment]
1.12 is not supported anymore

**Comment by Cosmology2727** [comment]
Yeah I know it's not supported anymore. I'm not asking for a bugfix or anything. People in the above conversation are mentioning a workaround fix for 1.12.2 by resetting the colony. I'm saying the command doesn't work for me, even though it worked for them, and they were on 1.12.2.
@Raycoms Is this the right command? Or is it something else? "/mc colony rs reset"
Also what does resetting the colony in this way actually do?
Thanks for any help you can give me!

**Comment by ravenbuilder934** [comment]
That would be supporting 1.12. We can't provide any help for 1.12 users.

**Comment by dd8630** [comment]
Cosmology2727, if it helps, I had trouble in a 1.12 modpack that I added MC to, and I figured out the syntax as: '/mc rs reset colony: 1'
