### ISSUE TITLE
Proper Tinker tool for Farm

### ISSUE THREAD

**Issue by tgstyle** [ldtteam/minecolonies#3653]
### Minecolonies version

Version: 1.12.2-0.10.291

I gave the Farmer all tool levels of a Kama, Scythe and Mattock. He still complains that he needs a hoe. Other Buildings/Professions seem to use Tinkers tools just fine. Is there something else I should use or is there an actual bug?

**Comment by marchermans** [comment]
Kama, Scythe and Mattocks are not supported.
As per TCon Definition they use external Technologies, like game events, to be have like a hoe, but are in fact not a hoe.
This is undetectable for our citizens, as such they can not use them.

**Comment by tgstyle** [comment]
Just curious about a mattock, it does have an ore dictionary entry as a
hoe. Would that work?

**Comment by tgstyle** [comment]
More specifically I believe it is "toolHoe"

**Comment by marchermans** [comment]
Actually that only works for crafting, sadly their "Hoe"-logic is not part of the tool, but part of external handlers that just do not really work well with our citizens, we are trying to improve the compatibility but for now it is stuck on tools that actually implement the logic properly.

**Comment by tgstyle** [comment]
Ah I see now https://github.com/SlimeKnights/TinkersConstruct/issues/2749

**Comment by tgstyle** [comment]
Ah I see now https://github.com/SlimeKnights/TinkersConstruct/issues/2749
