### ISSUE TITLE
[Suggestion] Normalise version and filename

### ISSUE THREAD

**Issue by xenoflot** [ldtteam/minecolonies#366]
I noticed when updating today that there's a discrepency between the version number on curse and the actual filename. e.g. Minecolonies v0.5 v23 is minecolonies-1.10.2-0.6.2036

It would be helpful if the version number and the filename were the same.

Thanks!

**Comment by Raycoms** [comment]
Our version numbers are more like internal build numbers.  We don't publish
them all.  Therefore,  if we would put these build numbers as version
numbers we'd had significant jumps between the numbers all the time.
That'd confuse the people

Am Dienstag, 20. Dezember 2016 schrieb xenoflot :
