### ISSUE TITLE
Wrath of the builder?

### ISSUE THREAD

**Issue by OCDCleric** [ldtteam/minecolonies#3660]
Ver.1.12.2-0.10.293

Expected:  ......

Actual: Mysterious phenomenon involving blocks mysteriously appearing in locations.

Examples include cobblestone block appearing in air, Ladder replacing a barracks gate, and more.

1. ???
2. Builder rages?
3. ???
4. Profit?????

I'm confused...

**Comment by Raycoms** [comment]
Those are the barbarians placing

Am Sa., 8. Juni 2019 um 14:05 Uhr schrieb OCDCleric <
notifications@github.com>:

**Comment by GanthorPrime** [comment]
Barbarians can place coblestone to bridge areas or over water, they also usualy place ladders to climb.  not sure wy they place ladders in hut doors, but in some cases that causes some problems (workers trapped in huts / houses)
