### ISSUE TITLE
River Pirates

### ISSUE THREAD

**Issue by OCDCleric** [ldtteam/minecolonies#3664]
### Minecolonies version
Ver. 1.12.2-0.10.295

### Expected behavior
Barbarian raid!

### Actual behaviour
Pirate Raid!

Saw a message saying a raid was coming but noticed it was for pirates? I got confused and had to really search for them and found this (picture to follow)

![2019-06-08_18 25 08](https://user-images.githubusercontent.com/29760230/59194482-245cfc00-8b57-11e9-9d75-335321419ba2.png)

### Steps to reproduce the problem

1. Dig up desert by river?
2. Wait for a raid... Or three.
3. ...
4. ... Profit

**Comment by Raycoms** [comment]
I don't see a problem tbh, they appear when there is enough water for them to sail in =)

**Comment by OCDCleric** [comment]
I guess so but in that case would be nice if they appeared on rafts in rivers?

**Comment by Raycoms** [comment]
We're going to add biome depending mobs in the future and then we will adapt things like that as well. But for that exactly we got an issue already. So, will close the issue in favor of that one.
