### ISSUE TITLE
Citizen Recruitment Failure

### ISSUE THREAD

**Issue by OCDCleric** [ldtteam/minecolonies#3666]
### Minecolonies version

Version: 1.12.2-0.10.295

### Expected behavior

- 

### Actual behaviour
Button in gui pressed but diamonds not taken and no new citizen.

### Steps to reproduce the problem

1. Press button for 11 diamondsn
2. Observe as button goee dark.
3. Realize diamonds don't decrease.
4. ... Profit

**Comment by Asherslab** [comment]
Do you have space for more citizens? look on the tab in your TownHall

**Comment by OCDCleric** [comment]
My first attempt was when i had 2 extra slots. 15 minutes later they were filled by child npcs.

**Comment by Asherslab** [comment]
okay. @someaddons think you can look at this?

**Comment by someaddons** [comment]
should be some errors in the log, else it just fails silently if trying to recruit despite having full pop(e.g. invisible citizens bug allowing you to use the button)

**Comment by OCDCleric** [comment]
Im sure pop wasnt full since 2 slots were there. I'll try for my lvl.4 homes and see if it happens again.

**Comment by someaddons** [comment]
click recall citizen on the townhall before trying, it respawns all citizens. To make sure it is not the citizens get randomly lost bug

**Comment by OCDCleric** [comment]
Ok. I think i'll make a feature request after this since it seems the larger this colony gets the more trouble i find...

**Comment by OCDCleric** [comment]
Ok i did an evil and lavad an npc. Was able to use package.

**Comment by someaddons** [comment]
Alright :D closing this then, since it likely was the other issue
