### ISSUE TITLE
[Feature] NPC Management Tools

### ISSUE THREAD

**Issue by OCDCleric** [ldtteam/minecolonies#3667]
Got a few ideas for enhancing management of npcs.

1. Town Hall Gui - Housing management
Would like a gui to manage citizens placement in houses. As more houses are built the more difficult it is to locate npcs, who they are, and what house to put them in. It's especially needed for putting kids in houses with two adults.

2. Waypoints - Tool for placing/removing/controlling waypoints
I have a builder who walks 1000 blocks in various loops and wrong turns to get to a build. I believe that a tool that lets us use waypoints controllably would help. Example would be being able to right-click a waypoint with tool to set a priority similar to delivery system so we can determine main roads from secondary roads. This would tell the npcs to use this first before other roads cutting back on wasted travel.
Related to Issue #3545 

3. Delivery System - Seperate the Delivery and Collection
More often then not Im finding that delivery workers aren't collecting everything. I hope that by making Collection a seperate option on delivery gui that collection of items would go smoother.

**Comment by Raycoms** [comment]
1 is planned
3 Sounds like a good idea.
2 We are planning on rewriting big parts of the pathfinding in the future. But there are a bunch of priority tasks in front yet.

You can remove waypoints by placing a block on them, and you can add one by letting the builder place it. But there is no easy way to add any priority system without making this rewrite.

**Comment by Asherslab** [comment]
@Raycoms i think you switched 2 and 3 around lol

**Comment by Raycoms** [comment]
Github did it for me, weirdly, I'll revert

**Comment by Raycoms** [comment]
Closed in favor of joint issue.
