### ISSUE TITLE
Building Glitch?

### ISSUE THREAD

**Issue by OCDCleric** [ldtteam/minecolonies#3669]
![2019-06-11_19 39 34](https://user-images.githubusercontent.com/29760230/59345588-6bc1c480-8cde-11e9-883e-743e2bdd4fc2.png)

So Im calling this a glitch since it reminds me of the issue where using tinkers construct hammer too fast leaves imvisible blocks behind. Unfortunately I can't seem to reproduce this one. What happened is that I started two builders around the same time, they finished at the same time to. I was busy messing in my chests making items and when i saw the message for completion I saw that weird sight.

How to reproduce?
1. Build two buildings at once.
2. Let them build?
3. ???
4. Happy Halloween?

**Comment by Raycoms** [comment]
I strongly believe that this is a minecraft bug, a few people reported it already but restarting always fixed it. It seems like the workers actions are not accepted randomly by the minecraft world.

**Comment by Wissi** [comment]
It is a Minecraft Issue. It will happen randomly with any mod or block (vanilla or not). 
Restarting will fix it. 
If you still have issues after restarting then report back so it can be checked.
