### ISSUE TITLE
No Spawn Platform in the End

### ISSUE THREAD

**Issue by Falcon7617** [ldtteam/minecolonies#367]
### Minecolonies version

Server, Current

### Expected behavior

- Normally there is a platform in the end to spawn on when jumping though the end portal

### Actual behaviour

- Some pos mined out the entire platform and I lost everything

### Steps to reproduce the problem

Go to the portal at x=9492, z= -6203, y=29
Jump in
Fall helplessly to your death

It would also be beneficial if my items could be restored to me. I died at 2:42 AM Pacific Time. Also, if you have some way of finding out who mined the platform, please permaban the pos.

**Comment by marvin-bitterlich** [comment]
This is no random server support, sorry

**Comment by Raycoms** [comment]
It seems like there is a bug which causes people to fall through the
existing platform.
We might have to place it a bit lower.
Probably some minecraft lag problem

Am Donnerstag, 22. Dezember 2016 schrieb Marvin Hofmann :
