### ISSUE TITLE
Miner takes too long to break blocks.

### ISSUE THREAD

**Issue by Xaleth** [ldtteam/minecolonies#3675]
### Minecolonies version

Version: minecolonies-1.12.2-null-universal

### Expected behavior

- Miner breaks blocks with stone pickaxe at pickaxe speed.

### Actual behaviour

- Miner takes significantly longer to break a block than pickaxe speed.

### Steps to reproduce the problem

1. Give Miner a stone pickaxe
2. Watch miner break blocks.
3. Equip a stone pickaxe and break blocks as well.
4. Compare speed.

**Comment by Xaleth** [comment]
About the version, I don't know. But I cloned this repository and compiled it yesterday.

**Comment by someaddons** [comment]
the miner's breaking speed depends on his worker level, with more levels he gets quite fast. (crazy fast actually) :)

**Comment by Xaleth** [comment]
Ohhh, didn't take that into consideration. Sorry for wasting your time!

**Comment by someaddons** [comment]
dont worry about it :D
