### ISSUE TITLE
Another Builder Bug

### ISSUE THREAD

**Issue by OCDCleric** [ldtteam/minecolonies#3678]
Version: 1.12.2-0.10.297

### Expected behavior
Give resources via "Fulfill" button and it gives the EXACT resources.

### Actual behaviour
Gave less than "Exact" resources but recorded it as if it had been given all required resources.

Current case;
Gave 4 out of 8 hay bales to the builder. Somehow gets recorded as being all 8 hay bales given.
![2019-06-17_08 28 32](https://user-images.githubusercontent.com/29760230/59619427-7a521680-90f8-11e9-9934-735378be2cba.png)
You can see it says 8/8 of hay bales given but in his inventory theres only 4 of them.

### Steps to reproduce the problem

1. Get a build order going.
2. Give less than required.
3. Check if order for item was "Fully" given.
4. ... Profit?

Unfortunately this bug couldn't be recreated even with same setup. Not sure if this is a randomly occurring bug either.

**Comment by Nightenom** [comment]
There are many reasons for hay bales to appear: dman, inventory recheck, worker pickups item, etc.

**Comment by OCDCleric** [comment]
@Nightenom Unfortunately it's becoming a repetitive bug when i deposit insufficient materials its now showing up as the [max materials + deposited materials] and only shows the actual amount when the builder comes around to get more materials.

**Comment by OCDCleric** [comment]
Argh! Now i gave it exact amount but it hows almost three times what i gave it. This is just weird...

**Comment by Raycoms** [comment]
Can you send us a world where you were able to reproduce this? I think I
know what is causing this.

Am Di., 18. Juni 2019 um 17:05 Uhr schrieb OCDCleric <
notifications@github.com>:

**Comment by OCDCleric** [comment]
[Trails of Cold Steel.zip](https://github.com/ldtteam/minecolonies/files/3303665/Trails.of.Cold.Steel.zip)

@Raycoms Heres the world.

**Comment by OCDCleric** [comment]
I cant be sure but i think a portion of items are being deleted... Might just be me seeing it wrong though...

**Comment by Raycoms** [comment]
Found the error of this here
