### ISSUE TITLE
What does the Waypoint Placeholder do?

### ISSUE THREAD

**Issue by iTheCuteKitten** [ldtteam/minecolonies#3679]
Well, you read the title. So.. What does the Waypoint Placeholder do in minecolonies and why does it even exist?

**Comment by TheMerricat** [comment]
https://wiki.minecolonies.com/source/items/waypoint

**Comment by Sandriell** [comment]
That article doesn't really answer the question of what they are for. I understand they are used in schematics/builds, but for what purpose? How do they affect the build or, I presume, the NPCs behavior?

**Comment by Raycoms** [comment]
They improve the pathing abilities and processing speed

Am Do., 20. Juni 2019 um 20:05 Uhr schrieb Sandriell <
notifications@github.com>:
