### ISSUE TITLE
Problem Spawning in the End

### ISSUE THREAD

**Issue by Falcon7617** [ldtteam/minecolonies#368]
I have no clue where to post this, so I'll do it here again . . . I tried to go into the end again Kos. I fell to my death as soon as I spawned. When I tried /back . . . it said "Can't return you to your previous location safely" Make it a $100 warp if you don't want everyone to go there, but the spawning is broken. Also, there was no platform when I fell. Believe me or not, but this is bugged.

When I get on tomorrow. Tp me to the portal . . . hop in. I will follow. If I spawn on the platform, great. If not . . .

**Comment by marvin-bitterlich** [comment]
write it on our discord. The github is only for bugs in minecolonies, not the server.
And sadly that is a minecraft bug. I would have to see where you spawned and why you fell... And then make a platform under the platform or so...

**Comment by Falcon7617** [comment]
Sounds good
