### ISSUE TITLE
Oak Wood Stairs disappear upon being delivered to Builder Hut

### ISSUE THREAD

**Issue by Samofsock** [ldtteam/minecolonies#3681]
### Minecolonies version
Version: minecolonies-1.12.2-0.10.259-RELEASE-universal

### Expected behavior
The builder receives oak wood stairs from the sawmill, takes those stairs, and builds the structure (in this case a LVL 2 citizen hut Medieval Oak Style)

### Actual behaviour
Builder sits in the hut doing nothing, doesn't request oak wood stairs, the hut says they have oak wood stairs, I watched them get crafted and delivered, I crafted and delivered some myself. They don't show up in the inventories if I don't deposit them directly into the chests or colonist inventory.

### Steps to reproduce the problem
1. build level 2 builder
2. tell it to build something requiring oak wood stairs
3. watch as the stairs get delivered and disappear from existence
4. ... Deficit

**Comment by Raycoms** [comment]
Are you sure they are not in some chest or rack which is "hidden" somewhere
in the building?

Am Mi., 19. Juni 2019 um 16:50 Uhr schrieb Samofsock <
notifications@github.com>:

**Comment by Samofsock** [comment]
thank you... I found them in a basement chest in the builder's hut. Still I don't think it should be putting stuff in there.

**Comment by OCDCleric** [comment]
@Raycoms Im having similar issue in #3678
Somethings definitely gone wrong with the builder.

**Comment by Raycoms** [comment]
we didn't change anything with the builder for a long while. Must be
related to the inventories of the building then.

Am Mi., 19. Juni 2019 um 17:00 Uhr schrieb OCDCleric <
notifications@github.com>:

**Comment by OCDCleric** [comment]
@Raycoms im going to try downgrading to see if anything changes since this is first time this has happened.

**Comment by Saatvik-Aggarwal** [comment]
this has happened to me before... the builder needs 108 oak planks to complete something. i give them to him so it shows 108/108 in the second page. i come back a day later and its 0/36.

**Comment by Raycoms** [comment]
I usually suspect the deliveryman here.

Am Do., 20. Juni 2019 um 19:55 Uhr schrieb Mystical-Codez <
notifications@github.com>:

**Comment by Saatvik-Aggarwal** [comment]
I did not have a warehouse. I think it happened during my barracks construction which you can see was glitched in #bugs in discord. 

Edit: I am pretty sure it happened during my warehouse construction too. I gave the builder all 300 something planks and later he shows 0/76. I creative them in and then it goes to 140 something / 76. 
Not sure what happened.

**Comment by Raycoms** [comment]
weird

Am Do., 20. Juni 2019 um 19:58 Uhr schrieb Mystical-Codez <
notifications@github.com>:

**Comment by Raycoms** [comment]
Please upgrade, on the newest this should not happen (alpha)
