### ISSUE TITLE
place townhall then game just freezes

### ISSUE THREAD

**Issue by NootNootnot** [ldtteam/minecolonies#3682]
### Minecolonies version

Version: minecolonies-1.12.2-0.10.259-RELEASE-universal
             minecraft forge 1.12.2-14.23.5.2838

### Expected behavior
place townhall block expect it to spawn first citizen and start the town
### Actual behaviour
after placing townhall block around the time the townsperson spawns it just freezes the game and upon pressing any keys crashes the game. it never gets beyond this point.

### Steps to reproduce the problem
not sure exactly whats causing the crash

**Comment by OCDCleric** [comment]
Crash log?

**Comment by NootNootnot** [comment]
16:55:32
game
info
[16:55:32] [Server thread/INFO] [minecolonies]: New Colony Id: 1 by N00T_N00T_
16:58:55
monitor
Process Monitor
fatal
Process crashed with exit code -805306369

**Comment by NootNootnot** [comment]
and sorry its not giving me the crash log just says java binary stopped

**Comment by OCDCleric** [comment]
Java stopped? Have you retried placing the town hall and does it recur?

**Comment by NootNootnot** [comment]
Yes I’ll load back into the game try to replace it and the same results occur

**Comment by Raycoms** [comment]
Is there no crash or stall report?

Am Mi., 19. Juni 2019 um 18:52 Uhr schrieb NootNootnot <
notifications@github.com>:

**Comment by NootNootnot** [comment]
[crash-2019-06-17_21.23.00-client.txt](https://github.com/ldtteam/minecolonies/files/3308324/crash-2019-06-17_21.23.00-client.txt)

**Comment by NootNootnot** [comment]
thats the most  recent one i can pull up

**Comment by Raycoms** [comment]
That's a crash of forge on startup unfortunately only.
Can you try out the latest alpha and check again?

Am Mi., 19. Juni 2019 um 21:38 Uhr schrieb NootNootnot <
notifications@github.com>:

**Comment by NootNootnot** [comment]
No dice on installing a clean alpha removed all the mods and texture packs went back to vanilla and start a new clean world I can place it the game will stutter for a few seconds then it just totally freezes and still gives me the java binary is unresponsive not quite sure where to trouble shoot from here if it’s any help I’ve allocated 16gb of ram to it and I’ve also run previous versions with no issues. Is there an upper end of town size in the menu that will just crash the game?

**Comment by Raycoms** [comment]
That's weird, never had this issue at all...

Am Mi., 19. Juni 2019 um 23:41 Uhr schrieb NootNootnot <
notifications@github.com>:

**Comment by NootNootnot** [comment]
I’ll try to trace my steps and whatever I find tommorow I’ll relay here

**Comment by Nightenom** [comment]
I would try updating/installing a different java jre
Don't forget to set path to the newest version in launcher settings

**Comment by Nightenom** [comment]
Maybe if symptoms in those matches your problems try some suggested solutions.
https://bugs.mojang.com/browse/MC-137429
https://bugs.mojang.com/browse/MC-138093
edit: don't get baited on installing java7, use the latest java8

**Comment by Raycoms** [comment]
Can you send us a few more crash reports. It's in the logs folder.

**Comment by NootNootnot** [comment]
[2019-06-19-4.log.gz](https://github.com/ldtteam/minecolonies/files/3312558/2019-06-19-4.log.gz)
[2019-06-19-5.log.gz](https://github.com/ldtteam/minecolonies/files/3312559/2019-06-19-5.log.gz)
[2019-06-19-6.log.gz](https://github.com/ldtteam/minecolonies/files/3312560/2019-06-19-6.log.gz)
[2019-06-19-7.log.gz](https://github.com/ldtteam/minecolonies/files/3312561/2019-06-19-7.log.gz)
[2019-06-19-1.log.gz](https://github.com/ldtteam/minecolonies/files/3312562/2019-06-19-1.log.gz)
[2019-06-19-2.log.gz](https://github.com/ldtteam/minecolonies/files/3312563/2019-06-19-2.log.gz)
[2019-06-19-3.log.gz](https://github.com/ldtteam/minecolonies/files/3312564/2019-06-19-3.log.gz)
those should be the ones that would include the crash

**Comment by NootNootnot** [comment]
just did a complete clean install of java then minecraft and added all my mods think i have it down to the texture and shader pack

**Comment by Raycoms** [comment]
I analyzed the log you sent me, and there is nothing crash or erroring on the mods side.
But it seems to me that you are overloading either the amount of RAM you are giving to the pack or your CPU. I read several times in your log that the system was overloaded and had to skip several ticks (with and without colony placement). The moment you place the townhall, the citizens spawn and cost a little bit more CPU which completely overloads it and we get this log again but skipping even more ticks taking down the server

**Comment by NootNootnot** [comment]
think ive got it pegged down to the shader and texture was using too much cpu works as directed right now without texture and shaders

**Comment by Raycoms** [comment]
Great to hear you got it working =)

**Comment by NootNootnot** [comment]
thank you guys so much for your patience
