### ISSUE TITLE
The First Builder

### ISSUE THREAD

**Issue by OCDCleric** [ldtteam/minecolonies#3683]
After ALOT of different testing only one actually showed a major difference.
Referencing #3678 and #3681 

That was in the builder used. For some reason Builder 1, that is to say the first builder the colony aquires is the bug source. After being made and building level 1 schematic, all further schematics made when given resources, will have the resources maxed and doubled.
Builder 2, the second builder aquired did not exhibit this bug.
Resources dissapear at random intervals even after confirming all resources in inventory. The resources don't appear in other inventorys either. During building it seems to make those resources dissapear as it works occasionally as well.

The first builder seems to be messing with us. Not sure whats causing it either as downgrading several versions didn't help.

**Comment by Raycoms** [comment]
Can you send me the world of this?

**Comment by Raycoms** [comment]
Can you join us on discord?

**Comment by Raycoms** [comment]
Is it possible that the builder died and lost the res?

**Comment by OCDCleric** [comment]
Sorry for late comment. The builder doesnt die though i did smack him once or twice. It happens after lvl 1 build hut completes, ots always the first builder too. The glitch affects lvls 1,2,3 of the first builder. 4 and above seem to be ok for now. Ill get a copy of the world in the morning.

**Comment by OCDCleric** [comment]
[Trails of Cold Steel.zip](https://github.com/ldtteam/minecolonies/files/3314822/Trails.of.Cold.Steel.zip)

Heres the world used. Im gonna make a new one and double check.

**Comment by Raycoms** [comment]
Does the issue appear atm regularly on this world? (In a way that I can
reproduce and debug this?)

Am Fr., 21. Juni 2019 um 11:24 Uhr schrieb OCDCleric <
notifications@github.com>:

**Comment by OCDCleric** [comment]
It should be pretty aparent with first builder... Try using the Wooden schematics? Not sure what else to say. The first builder of each new world has this.
