### ISSUE TITLE
the farmer harvests but the wheat disappears

### ISSUE THREAD

**Issue by Stayfire** [ldtteam/minecolonies#3687]
Everything is in the title, my farmer harvests the wheat but when he puts it in the inventory the wheat disappears.

Another bug, when I have the full inventory and for example 63 oak woods and I get the wood from the lumberjack's inventory, the wood is duplicated: for example, if there are 40 logs in the log Lumberjack inventory (and that we have 63 in the inventory with our inventory full,) so we go to 64 logs in our inventory but there are still 40 logs in the inventory of the logger's hut.

Well, sorry it's a bit confusing but it was just to report that I have these bugs, I play in 1.12.2.

**Comment by Raycoms** [comment]
I fixed that, it shouldn't appear in the newest alpha anymore.

Am Do., 20. Juni 2019 um 17:21 Uhr schrieb Stayfire <
notifications@github.com>:

**Comment by Raycoms** [comment]
Or did you reopen it because of the duplication? I didn't check into that yet

**Comment by Stayfire** [comment]
Great, thank you for your quick response, so I close this post.

**Comment by bblay** [comment]
Hi, the disappearing resources bug is happening on the latest version of Twitch's _Valhelsia 2_, for at least the farmer, lumberjack and miner. The version is listed by Twitch as `minecolonies-1.15.2-0.11.948-universal.jar`. Love this mod, thanks for making it.
