### ISSUE TITLE
Can't place structure in snow or snow covered ground

### ISSUE THREAD

**Issue by TheQuadShot** [ldtteam/minecolonies#3688]
### Minecolonies version

Version: 
mincraft-1.12.2
forge-14.23.5.2838
minecolonies-1.12.2-0.10.259-RELEASE-universal
ModList: https://pastebin.com/RT9gtjNJ
### Expected behavior

be able to place structures that has been snowed on.
- 

I love to build in biomes that have snow. I don't want to have to "shovel" snow prior to placing a building. The biggest problem is, if it's snowing I can't clear it fast enough to place it, so I have to wait around for it to stop or enable cheats and toggle downfall.

### Actual behaviour

If there is snow on the ground I can't place a structure, I get an error that it must be clear ground for  x by x   space
- 

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit
I will be glad to provide more info if it's needed. Thanks

**Comment by OCDCleric** [comment]
Have you tried using the latest alpha? I don't have this issue on the latest alpha.

**Comment by Raycoms** [comment]
I think he means the supplycamp

Am Fr., 21. Juni 2019 um 14:29 Uhr schrieb OCDCleric <
notifications@github.com>:

**Comment by OCDCleric** [comment]
@TheQuadShot More info required such as what structure you tried to place.

**Comment by TheQuadShot** [comment]
Yes, the supplycamp, and you have to have a +1 block buffer cleared around the area as well.

**Comment by Raycoms** [comment]
I can fix that (later today)

Am Fr., 21. Juni 2019 um 14:40 Uhr schrieb James <notifications@github.com>:
