### ISSUE TITLE
Hut Block orientation

### ISSUE THREAD

**Issue by Azragor** [ldtteam/minecolonies#369]
### Minecolonies version

version 0.6.2038

### Expected behavior

- When you place one of the Builder Block or TownHall Block is facing the correct direction.

### Actual behaviour

- When you place the block with your hand is facing toward you but when you place it with
the building wand the block rotate 180. 

I'm maybe a little OCD. I would just like that those block face the same way as when a scan them.
I'm pretty sure it's a problem with when you place the block with the Building wand.

**Comment by marvin-bitterlich** [comment]
With the building wand you can turn the structure and that turns the block, because the block is oriented to the building not to your temporary location

**Comment by Azragor** [comment]
I know that. It's more like the scan tool do not record the orientation of the Builder Hut or the build tool doesn't use it when it's place the block. After some testing it's seem like there a static position for the HutBlock, it's always facing the same way in reference of the general structure orientation.

**Comment by Raycoms** [comment]
Yes the Hut block has to face a certain position when being scanned.  To
find out the position place a Hut with the build tool without adjusting the
position

Am Donnerstag, 22. Dezember 2016 schrieb Azragor :

**Comment by pmardle** [comment]
Its probably because the building was scanned when we had the old block, which wasn't orientation specific.

If this annoys you, feel free to use the scan tool to re-scan the building in once you have manually re-orientated the block and substitute for the original building file (or send to us so we can roll it out for everyone :) )
