### ISSUE TITLE
Can't repair custom made Huts

### ISSUE THREAD

**Issue by FeedTheChunk** [ldtteam/minecolonies#3691]
### Minecolonies version

Version:  1.12.2-0.10.202-RELEA

### Expected behavior

- 
Pressing the Repair button under the upgrade should allow you to upgrade the hut.

### Actual behaviour

- 
When using a custom blueprint (Citizen Hut) you can't repair the Hut.  Select the correct "model" under the blueprint drop down and click repair always seems to select the wooden hut option.

### Steps to reproduce the problem

1.  Select Build Options
2. Find your customer blueprint model in the dropdown list (it's blank).

![image](https://user-images.githubusercontent.com/35508630/59966726-1cea0b00-94e6-11e9-956b-558502b38cc7.png)

3. Click Repair.
4. The builder gets this request:

![image](https://user-images.githubusercontent.com/35508630/59966743-3f7c2400-94e6-11e9-8f7a-148049d9148d.png)

5. This is not the Repair for this Hut.

**Comment by Raycoms** [comment]
you mean upgrade works but repair doesn't?

>

**Comment by FeedTheChunk** [comment]
Correct. I can upgrade the hut just fine but not use the repair function.  The repair works fine with the standard huts just not with the custom ones.  I have not tried repairing other custom huts as I only made new Citizen huts.

**Comment by Raycoms** [comment]
Can you describe the progress you setup the custom ones? (And send us the
custom huts?)

>

**Comment by FeedTheChunk** [comment]
I followed the steps on the [Wiki ](https://wiki.minecolonies.com/source/tutorials/schematics)to create the blueprints. I did make them in a creative world and then move them to the minecraft\structurize\schematics folder as described on the wiki.


[schematics.zip](https://github.com/ldtteam/minecolonies/files/3317165/schematics.zip)

**Comment by FeedTheChunk** [comment]
I'm thinking now there may be a bigger issue at hand.  I've tried to build some other schematics and nothing seems to be working.  It seems to be okay if I place a new hut it will build but none of the decorations or other custom blueprints that I have will build.   Or I'm doing something wrong,

**Comment by FeedTheChunk** [comment]
Single player if that makes an difference,

**Comment by Raycoms** [comment]
What do you mean with "not working" ?

Am Sa., 22. Juni 2019 um 16:09 Uhr schrieb FeedTheChunk <
notifications@github.com>:

**Comment by FeedTheChunk** [comment]
Ignore the comment about other schematics. I was building too far outside of the colony

**Comment by OCDCleric** [comment]
@FeedTheChunk Are you using modded blocks in your schematic?

**Comment by FeedTheChunk** [comment]
Yes. a Lantern from Rustic and Fir wood from Traverse

**Comment by Raycoms** [comment]
Should not be an issue, if upgrade works and repair doesn't, I gotta check
into it

Am Sa., 22. Juni 2019 um 16:43 Uhr schrieb FeedTheChunk <
notifications@github.com>:

**Comment by FeedTheChunk** [comment]
All The Mods 3 v5.12.1 is the pack for what it's worth.

**Comment by OCDCleric** [comment]
Guess that explains the old version of minecolonies.

**Comment by FeedTheChunk** [comment]
you want I should upgrade to the newest MC version?

**Comment by OCDCleric** [comment]
If a fix gets in itll be on the latest alpha so you could wait till then or you could see of latest alpha fixes your issue.

**Comment by Raycoms** [comment]
I tested this in the newest alpha and it works for me, so I'm going to close it
