### ISSUE TITLE
MineColonies disconnected when building is done

### ISSUE THREAD

**Issue by JanniJensenDahm** [ldtteam/minecolonies#3692]
### Minecolonies version

Version: minecolonies-1.12.2-0.10.302-ALPHA-universal

### Expected behavior

I would stay in the game.

### Actual behaviour

I joined a game (open LAN), and when a minecolonies building was done, I got kicked out of the game.
The host is not getting kicked out. I got the saved game and ran it as host, then it was my friend that got kicked out when a building was created. so it only happens for the one joining the game.

![image](https://user-images.githubusercontent.com/35970764/59966800-a8cd5880-9521-11e9-84b1-14dfac305b34.png)

### Steps to reproduce the problem

1. Create a game
2. Get someone to join your game (LAN)
3. Create a building with minecolonies, and wait for it to get done.

**Comment by Raycoms** [comment]
Can you send us the log?

Am Sa., 22. Juni 2019 um 14:17 Uhr schrieb Janni Jensen-Dahm <
notifications@github.com>:

**Comment by JanniJensenDahm** [comment]
[latest.log](https://github.com/ldtteam/minecolonies/files/3317551/latest.log)

**Comment by Raycoms** [comment]
Fixed

**Comment by BigAngelUK** [comment]
Its not fixed i am having the same problem

**Comment by Raycoms** [comment]
With the newest alpha?

Am Mi., 10. Juli 2019 um 10:05 Uhr schrieb BigAngelUK <
notifications@github.com>:

**Comment by BigAngelUK** [comment]
I downloaded the pack today so i think it is. The one other thing i found out was if i was not in the colony i did not get kicked.

**Comment by Raycoms** [comment]
Ahh, the modpack, yeah, it was not updated yet with it.

Am Mi., 10. Juli 2019 um 18:24 Uhr schrieb BigAngelUK <
notifications@github.com>:
