### ISSUE TITLE
minecolonies barracks towers notspawning new citizens in 1.12 release version.

### ISSUE THREAD

**Issue by chyper111** [ldtteam/minecolonies#3693]
### Minecolonies version
1.12 

Version: 0.9.2

### Expected behavior
 I expected to have a new citizen spawn at the citizen hut for each new guard i assign to the barracks towers.

- 

### Actual behaviour
no new citizens are spawning.

- I have a level5 medieval oak barracks with 4 level 5 towers. i have 8 medieval oak level 5 citizen huts with 40 total citizens. I hired 5 of the citizens to work at the barracks. the 5 guards have now been unassigned from the citizen huts and assigned to the barracks towers. I now have 5 empty beds in my citizen huts and no one is spawning to fill them. I thought new citizens were going to spawn. is this a bug or am i doing something wrong?

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit

**Comment by Raycoms** [comment]
A few questions:

a) Do you have a male and a female living together in one of the buildings?
b) Did you wait some time to check if kids are spawning?
c) Did you try the newest alpha?

>

**Comment by chyper111** [comment]
a) We have mutiable male/female at different citizen huts
b) We waited 16 hours (real-time) for kids and we can't recruit because it won't let us click the packages.
c) And we cant use the alpha or any like it because upon loading in it crashes even when using an older alpha it will crash.

**Comment by chyper111** [comment]
I'd give you a crash report but I don't think those are supposed to go here and I don't know where to leave one or how to. Sorry...XC

**Comment by Raycoms** [comment]
Just leave them here.

Am Sa., 22. Juni 2019 um 22:08 Uhr schrieb chyper111 <
notifications@github.com>:

**Comment by Raycoms** [comment]
When you try to recruit do you have the cost items in the inventory?

**Comment by chyper111** [comment]
i had 64 stacks of all of the diffrent ones

**Comment by chyper111** [comment]
im sorry but im not currently on the computer with the report so i will post it there tommorow...

**Comment by Talyda** [comment]
Someone had this happen before and doing a repair on the citizen huts made new kidlets spawn - dunno if the recalculation was fixed, but it might be worth trying a repair and seeing?

**Comment by chyper111** [comment]
well I tried to manually assign people from the hut and leave one of the citizens unassigned to the hut but even after hiring the unassigned citizen it still wouldn't even tho the hut said there was one that could be.

**Comment by chyper111** [comment]
also, it doesn't give me that option to repair as far as I know unless the build has taken damage and I have 6 different one as well,'

**Comment by Talyda** [comment]
Every hut should have the option, when you go into "build options" the bottom left corner of the next screen will have "repair"

**Comment by chyper111** [comment]
Hum if I never noticed it before I'll try it when I'm on that computer
again. I'll keep you updated if it continues to keep from spawning.

**Comment by Raycoms** [comment]
@someaddons did we have a fix for this "you have to repair a house to force recalc issue" ?

**Comment by chyper111** [comment]
sorry i wasn't clear I'm currently not able to play to say whether i have a fix or not its all on another computer im away i sent the original post not expecting a response so quickly

**Comment by chyper111** [comment]
i will be able to check if that works tomorrow when i play again sorry

**Comment by someaddons** [comment]
it does recalculate on barracks tower upgrade

**Comment by chyper111** [comment]
Not as far as we have seen we have 6 citizen huts and a level 5 barracks
and 4 level 5 towers yet it says we have a pop of 40 and when we send 1 or
7 it still says 40 so ether im doing something wrong or I found a bug cuze
it says on the wiki that a child or recruits can come take the bed that's
left but after 16 hours and not being able to recruit due to another bug I
can't get any more Peps

**Comment by someaddons** [comment]
ye its buggy, only recalculates on building upgrade, not on worker assignment. gonna change it

**Comment by chyper111** [comment]
so i have a crash report for the newest alpha do i send it to raycons link or do you have one someaddons?

**Comment by someaddons** [comment]
just put it in a new report

**Comment by Raycoms** [comment]
paste it  here

Am So., 23. Juni 2019 um 14:17 Uhr schrieb chyper111 <
notifications@github.com>:

**Comment by chyper111** [comment]
sorry im kinda bad with that stuff where and how can i do that do you mean just paste it here on this site?

**Comment by chyper111** [comment]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.12.2.jar)
  ShetiPhian-ASM (ShetiPhian-ASM-1.12.0.jar)
  BedPatch (bedpatch-2.2-1.12.2.jar)
  Quark Plugin (Quark-r1.5-161.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.4.153.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 6/23/19 12:15 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.minecraftforge.items.wrapper.SidedInvWrapper.hashCode(SidedInvWrapper.java:66)
	at java.util.HashMap.hash(HashMap.java:338)
	at java.util.HashMap.put(HashMap.java:611)
	at java.util.HashSet.add(HashSet.java:219)
	at com.minecolonies.api.util.InventoryUtils.getItemHandlersFromProvider(InventoryUtils.java:536)
	at com.minecolonies.coremod.tileentities.TileEntityColonyBuilding.lambda$getCapability$0(TileEntityColonyBuilding.java:440)
	at com.minecolonies.coremod.tileentities.TileEntityColonyBuilding$$Lambda$3846/181872197.apply(Unknown Source)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1540)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.minecolonies.coremod.tileentities.TileEntityColonyBuilding.getCapability(TileEntityColonyBuilding.java:441)
	at com.minecolonies.coremod.colony.buildings.AbstractBuildingContainer.getCapability(AbstractBuildingContainer.java:315)
	at com.minecolonies.api.util.InventoryUtils.getItemHandlersFromProvider(InventoryUtils.java:533)
	at com.minecolonies.api.util.InventoryUtils.findFirstSlotInProviderNotEmptyWith(InventoryUtils.java:621)
	at com.minecolonies.coremod.entity.ai.minimal.EntityAIEatTask.goToHut(EntityAIEatTask.java:382)
	at com.minecolonies.coremod.entity.ai.minimal.EntityAIEatTask.func_75246_d(EntityAIEatTask.java:180)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2359)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178)
	at com.minecolonies.coremod.entity.EntityCitizen.func_70636_d(EntityCitizen.java:597)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraftforge.items.wrapper.SidedInvWrapper.hashCode(SidedInvWrapper.java:66)
	at java.util.HashMap.hash(HashMap.java:338)
	at java.util.HashMap.put(HashMap.java:611)
	at java.util.HashSet.add(HashSet.java:219)
	at com.minecolonies.api.util.InventoryUtils.getItemHandlersFromProvider(InventoryUtils.java:536)
	at com.minecolonies.coremod.tileentities.TileEntityColonyBuilding.lambda$getCapability$0(TileEntityColonyBuilding.java:440)
	at com.minecolonies.coremod.tileentities.TileEntityColonyBuilding$$Lambda$3846/181872197.apply(Unknown Source)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1540)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.minecolonies.coremod.tileentities.TileEntityColonyBuilding.getCapability(TileEntityColonyBuilding.java:441)
	at com.minecolonies.coremod.colony.buildings.AbstractBuildingContainer.getCapability(AbstractBuildingContainer.java:315)
	at com.minecolonies.api.util.InventoryUtils.getItemHandlersFromProvider(InventoryUtils.java:533)
	at com.minecolonies.api.util.InventoryUtils.findFirstSlotInProviderNotEmptyWith(InventoryUtils.java:621)
	at com.minecolonies.coremod.entity.ai.minimal.EntityAIEatTask.goToHut(EntityAIEatTask.java:382)
	at com.minecolonies.coremod.entity.ai.minimal.EntityAIEatTask.func_75246_d(EntityAIEatTask.java:180)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2359)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178)
	at com.minecolonies.coremod.entity.EntityCitizen.func_70636_d(EntityCitizen.java:597)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)

-- Entity being ticked --
Details:
	Entity Type: minecolonies:citizen (com.minecolonies.coremod.entity.EntityCitizen)
	Entity ID: 11817
	Entity Name: Millicent G. Cox
	Entity's Exact location: 7663.07, 65.00, -979.51
	Entity's Block location: World: (7663,65,-980), Chunk: (at 15,4,12 in 478,-62; contains blocks 7648,0,-992 to 7663,255,-977), Region: (14,-2; contains chunks 448,-64 to 479,-33, blocks 7168,0,-1024 to 7679,255,-513)
	Entity's Momentum: 0.11, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: Promised Land 3000
	All players: 1 total; [GCEntityPlayerMP['Chyper111'/195, l='Promised Land 3000', x=7756.84, y=84.17, z=-989.15]]
	Chunk stats: ServerChunkCache: 1442 Drop: 0
	Level seed: -1895858090
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (168,64,180), Chunk: (at 8,4,4 in 10,11; contains blocks 160,0,176 to 175,255,191), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 41292394 game time, 10432 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 6000 (now: false), thunder time: 6000 (now: true)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 8533042408 bytes (8137 MB) / 14730395648 bytes (14048 MB) up to 15032385536 bytes (14336 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx14G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 8, allocated: 13, tallocated: 96
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 94 mods loaded, 94 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                    | Version                 | Source                                               | Signature                                |
	|:------ |:--------------------- |:----------------------- |:---------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft             | 1.12.2                  | minecraft.jar                                        | None                                     |
	| LCHIJA | mcp                   | 9.42                    | minecraft.jar                                        | None                                     |
	| LCHIJA | FML                   | 8.0.99.99               | forge-1.12.2-14.23.5.2838.jar                        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                 | 14.23.5.2838            | forge-1.12.2-14.23.5.2838.jar                        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | ivtoolkit             | 1.3.3-1.12              | minecraft.jar                                        | None                                     |
	| LCHIJA | micdoodlecore         |                         | minecraft.jar                                        | None                                     |
	| LCHIJA | opencomputers|core    | 1.7.4.153               | minecraft.jar                                        | None                                     |
	| LCHIJA | ctm                   | MC1.12.2-0.3.3.22       | CTM-MC1.12.2-0.3.3.22.jar                            | None                                     |
	| LCHIJA | appliedenergistics2   | rv6-stable-6            | appliedenergistics2-rv6-stable-6.jar                 | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCHIJA | redstoneflux          | 2.1.0                   | RedstoneFlux-1.12-2.1.0.6-universal.jar              | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | p455w0rdslib          | 2.1.44                  | p455w0rdslib-1.12.2-2.1.44.jar                       | None                                     |
	| LCHIJA | ae2wtlib              | 1.0.6                   | AE2WTLib-1.12.2-1.0.6.jar                            | None                                     |
	| LCHIJA | jei                   | 4.15.0.272              | jei_1.12.2-4.15.0.272.jar                            | None                                     |
	| LCHIJA | quark                 | r1.5-161                | Quark-r1.5-161.jar                                   | None                                     |
	| LCHIJA | autoreglib            | 1.3-28                  | AutoRegLib-1.3-28.jar                                | None                                     |
	| LCHIJA | bibliocraft           | 2.4.5                   | BiblioCraft[v2.4.5][MC1.12.2].jar                    | None                                     |
	| LCHIJA | biomesoplenty         | 7.0.1.2439              | BiomesOPlenty-1.12.2-7.0.1.2439-universal.jar        | None                                     |
	| LCHIJA | buildcraftlib         | 7.99.24                 | buildcraft-all-7.99.24.jar                           | None                                     |
	| LCHIJA | buildcraftcore        | 7.99.24                 | buildcraft-all-7.99.24.jar                           | None                                     |
	| LCHIJA | buildcraftbuilders    | 7.99.24                 | buildcraft-all-7.99.24.jar                           | None                                     |
	| LCHIJA | buildcrafttransport   | 7.99.24                 | buildcraft-all-7.99.24.jar                           | None                                     |
	| LCHIJA | buildcraftsilicon     | 7.99.24                 | buildcraft-all-7.99.24.jar                           | None                                     |
	| LCHIJA | buildcraftcompat      | 7.99.24                 | buildcraft-all-7.99.24.jar                           | None                                     |
	| LCHIJA | buildcraftenergy      | 7.99.24                 | buildcraft-all-7.99.24.jar                           | None                                     |
	| LCHIJA | buildcraftfactory     | 7.99.24                 | buildcraft-all-7.99.24.jar                           | None                                     |
	| LCHIJA | buildcraftrobotics    | 7.99.24                 | buildcraft-all-7.99.24.jar                           | None                                     |
	| LCHIJA | chisel                | MC1.12.2-0.2.1.35       | Chisel-MC1.12.2-0.2.1.35.jar                         | None                                     |
	| LCHIJA | chiselsandbits        | 14.31                   | chiselsandbits-14.31.jar                             | None                                     |
	| LCHIJA | codechickenlib        | 3.2.2.353               | CodeChickenLib-1.12.2-3.2.2.353-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | cofhcore              | 4.6.3                   | CoFHCore-1.12.2-4.6.3.27-universal.jar               | None                                     |
	| LCHIJA | cofhworld             | 1.3.0                   | CoFHWorld-1.12.2-1.3.0.6-universal.jar               | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | ic2                   | 2.8.159-ex112           | industrialcraft-2-2.8.159-ex112.jar                  | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCHIJA | compactsolars         | 1.12.2-5.0.18.341       | CompactSolars-1.12.2-5.0.18.341-universal.jar        | None                                     |
	| LCHIJA | cookingforblockheads  | 6.4.70                  | CookingForBlockheads_1.12.2-6.4.70.jar               | None                                     |
	| LCHIJA | elevatorid            | 1.3.8                   | ElevatorMod-1.12.2-1.3.8.jar                         | None                                     |
	| LCHIJA | enderstorage          | 2.4.5.135               | EnderStorage-1.12.2-2.4.5.135-universal.jar          | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | energyconverters      | 1.0.1.2                 | energyconverters_1.12.1-1.0.1.2.jar                  | None                                     |
	| LCHIJA | umm3185118519         | release 1.3 - MC 1.12.2 | Extended+ItemsOres+[1.12.2]+(release+1.3).jar        | None                                     |
	| LCHIJA | waila                 | 1.8.26                  | Hwyla-1.8.26-B41_1.12.2.jar                          | None                                     |
	| LCHIJA | extracells            | 2.6.2                   | ExtraCells-1.12.2-2.6.2a.jar                         | None                                     |
	| LCHIJA | galacticraftcore      | 4.0.1.181               | Galacticraft-Mod-1.12.2.jar                          | None                                     |
	| LCHIJA | galacticraftplanets   | 4.0.1.181               | Galacticraft-Planets-Mod-1.12.2.jar                  | None                                     |
	| LCHIJA | mjrlegendslib         | 1.12.2-1.1.8            | MJRLegendsLib-1.12.2-1.1.8.jar                       | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LCHIJA | extraplanets          | 1.12.2-0.5.3            | ExtraPlanets-1.12.2-0.5.3.jar                        | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LCHIJA | extrautils2           | 1.0                     | extrautils2-1.12-1.9.9.jar                           | None                                     |
	| LCHIJA | opencomputers         | 1.7.4.153               | OpenComputers-MC1.12.2-1.7.4.153.jar                 | None                                     |
	| LCHIJA | zerocore              | 1.12.2-0.1.2.8          | zerocore-1.12.2-0.1.2.8.jar                          | None                                     |
	| LCHIJA | bigreactors           | 1.12.2-0.4.5.66         | ExtremeReactors-1.12.2-0.4.5.66.jar                  | None                                     |
	| LCHIJA | forgemultipartcbe     | 2.6.1.81                | ForgeMultipart-1.12.2-2.6.1.81-universal.jar         | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | microblockcbe         | 2.6.1.81                | ForgeMultipart-1.12.2-2.6.1.81-universal.jar         | None                                     |
	| LCHIJA | minecraftmultipartcbe | 2.6.1.81                | ForgeMultipart-1.12.2-2.6.1.81-universal.jar         | None                                     |
	| LCHIJA | ftblib                | 5.4.3.103               | FTBLib-5.4.3.103.jar                                 | None                                     |
	| LCHIJA | silentlib             | 3.0.13                  | SilentLib-1.12.2-3.0.13+167.jar                      | None                                     |
	| LCHIJA | funores               | 1.6.3                   | FunOres-1.12.2-1.6.3-124.jar                         | None                                     |
	| LCHIJA | cfm                   | 6.3.0                   | furniture-6.3.0-1.12.2.jar                           | None                                     |
	| LCHIJA | gottschcore           | 1.7.0                   | GottschCore-mc1.12.2-f14.23.5.2768-v1.7.0.jar        | None                                     |
	| LCHIJA | gravisuite            | 3.1.1                   | Gravitation+Suite-3.1.1.jar                          | None                                     |
	| LCHIJA | ichunutil             | 7.2.1                   | iChunUtil-1.12.2-7.2.1.jar                           | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | trackapi              | 1.1                     | TrackAPI-1.1_1.12.jar                                | None                                     |
	| LCHIJA | immersiverailroading  | 1.6.1                   | ImmersiveRailroading-1.6.1_1.12-1138.jar             | None                                     |
	| LCHIJA | ironchest             | 1.12.2-7.0.59.842       | ironchest-1.12.2-7.0.59.842.jar                      | None                                     |
	| LCHIJA | journeymap            | 1.12.2-5.5.4            | journeymap-1.12.2-5.5.4.jar                          | None                                     |
	| LCHIJA | lex                   | 1.0.8                   | LibEx-1.12.2-1.0.8.jar                               | None                                     |
	| LCHIJA | metallurgy            | 0.2.1                   | Metallurgy-4-Reforged-0.2.1.jar                      | None                                     |
	| LCHIJA | numina                | 1.12.2-1.0.38           | Numina-1.12.2-1.0.38.jar                             | None                                     |
	| LCHIJA | railcraft             | 12.0.0-beta-5           | railcraft-12.0.0-beta-5.jar                          | a0c255ac501b2749537d5824bb0f0588bf0320fa |
	| LCHIJA | powersuits            | 1.12.2-1.0.41           | ModularPowersuits-1.12.2-1.0.41.jar                  | None                                     |
	| LCHIJA | harvestcraft          | 1.12.2zb                | Pam's+HarvestCraft+1.12.2zd+Surprise+for+Yogcast.jar | None                                     |
	| LCHIJA | placeableitems        | 3.3                     | placeableitems-3.3.jar                               | None                                     |
	| LCHIJA | quarkoddities         | 1                       | QuarkOddities-1.12.2.jar                             | None                                     |
	| LCHIJA | quickleafdecay        | 1.2.4                   | QuickLeafDecay-MC1.12.1-1.2.4.jar                    | None                                     |
	| LCHIJA | reccomplex            | 1.4.7                   | RecurrentComplex-1.4.7.jar                           | None                                     |
	| LCHIJA | redstonepaste         | 1.7.5                   | redstonepaste-mc1.12-1.7.5.jar                       | None                                     |
	| LCHIJA | additionalstructures  | 2.2.2                   | Rex's-Additional-Structures-1.12.x-(v.2.2.2).jar     | None                                     |
	| LCHIJA | rockhounding_core     | 3.16                    | rockhounding_core-1.12.2-3.16.jar                    | None                                     |
	| LCHIJA | gbook                 | 2.9.1                   | Guidebook-1.12.2-2.9.1.jar                           | None                                     |
	| LCHIJA | rockhounding_rocks    | 1.12.2-3.18             | rockhounding_rocks-1.12.2-3.18.jar                   | None                                     |
	| LCHIJA | secretroomsmod        | 5.3.2                   | Secret-Rooms-Mod-1.12.2.jar                          | None                                     |
	| LCHIJA | shetiphiancore        | 3.5.9                   | shetiphiancore-1.12.0-3.5.9.jar                      | None                                     |
	| LCHIJA | terraqueous           | 1.4.17                  | terraqueous-1.12.2-1.4.17b.jar                       | None                                     |
	| LCHIJA | thermalfoundation     | 2.6.2                   | ThermalFoundation-1.12.2-2.6.2.26-universal.jar      | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | thermalexpansion      | 5.5.3                   | ThermalExpansion-1.12.2-5.5.3.41-universal.jar       | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | thermaldynamics       | 2.5.5                   | ThermalDynamics-1.12.2-2.5.5.21-universal.jar        | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCHIJA | treasure2             | 1.3.0                   | Treasure2-mc1.12.2-f14.23.5.2768-v1.3.0.jar          | None                                     |
	| LCHIJA | bspkrscore            | at_0.9                  | Treecapitator-1.12-at_0.9a.jar                       | None                                     |
	| LCHIJA | treecapitator         | at_0.9                  | Treecapitator-1.12-at_0.9a.jar                       | None                                     |
	| LCHIJA | twilightforest        | 3.8.689                 | twilightforest-1.12.2-3.8.689-universal.jar          | None                                     |
	| LCHIJA | wanionlib             | 1.12.2-2.2              | WanionLib-1.12.2-2.2.jar                             | None                                     |
	| LCHIJA | wct                   | 3.11.87                 | WirelessCraftingTerminal-1.12.2-3.11.87.jar          | None                                     |
	| LCHIJA | wrcbe                 | 2.3.1                   | WR-CBE-1.12.2-2.3.1.30-universal.jar                 | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | yabba                 | 1.1.2.52                | YABBA-1.1.2.52.jar                                   | None                                     |
	| LCHIJA | structurize           | 1.12.2-0.10.93-ALPHA    | structurize-1.12.2-0.10.93-ALPHA.jar                 | None                                     |
	| LCHIJA | minecolonies          | 1.12.2-0.10.302-ALPHA   | minecolonies-1.12.2-0.10.302-ALPHA-universal.jar     | None                                     |
	| LCHIJA | unidict               | 1.12.2-2.9.2            | UniDict-1.12.2-2.9.2.jar                             | None                                     |

	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.12.2.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
ShetiPhian-ASM (ShetiPhian-ASM-1.12.0.jar)
  shetiphian.asm.ClassTransformer
BedPatch (bedpatch-2.2-1.12.2.jar)
  com.mordenkainen.bedpatch.BedPatchASM
Quark Plugin (Quark-r1.5-161.jar)
  vazkii.quark.base.asm.ClassTransformer
TransformerLoader (OpenComputers-MC1.12.2-1.7.4.153.jar)
  li.cil.oc.common.asm.ClassTransformer
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  net.fybertech.nwr.NWRTransformer
CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	AE2 Version: stable rv6-stable-6 for Forge 14.23.5.2768
	AE2 Integration: IC2:ON, RC:ON, MFR:OFF, Waila:ON, InvTweaks:OFF, JEI:ON, Mekanism:OFF, OpenComputers:ON, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:OFF
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [GCEntityPlayerMP['Chyper111'/195, l='Promised Land 3000', x=7756.84, y=84.17, z=-989.15]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by chyper111** [comment]
sorry if i did that wrong

**Comment by chyper111** [comment]
Also upon repaireing my pop grew so that fixed the problem with the barracks so that closes this issue but id like to know why it crashed in 1.12.2-0.10.302-ALPHA-universal.jar still tho so I can update it one-day especially since there are other bugs that I'm dealing with please any help would be appreciated and thanks for the building fix tip someaddons and raycom

**Comment by marchermans** [comment]
It is a mod compat issue I think. @Raycoms are we using SidedInvWrapper anywhere?

**Comment by chyper111** [comment]
mod compat?

**Comment by Raycoms** [comment]
This is exactly the same issue with the nuclear craft.

**Comment by chyper111** [comment]
so how do i get around it?

**Comment by Raycoms** [comment]
Don't have modded inventory blocks in the huts

Am So., 23. Juni 2019 um 22:36 Uhr schrieb chyper111 <
notifications@github.com>:

**Comment by chyper111** [comment]
like what the racks?

**Comment by Asherslab** [comment]
@chyper111 any inventories that are not racks, or vanilla chests

**Comment by chyper111** [comment]
??? i haven't added anything aside from an enderchest to fill the warehouse with coconuts. if i get rid of that will i be able to update to the most current alpha and also why does having that matter in the first place?

**Comment by chyper111** [comment]
is there a population cap?

**Comment by Captainaviator** [comment]
The same thing is happening to me too, and I don't have any modded blocks inside any building

*I'm also using the latest version
