### ISSUE TITLE
Tinkers Tools and Workers

### ISSUE THREAD

**Issue by CoporalKritz** [ldtteam/minecolonies#3694]
I'm using the most recent version as of June 22nd

I'm expecting it to use the tool I provided from tinkers ((Clumsy level tool with an iron head and binding, and a bone handle)) like any other tool I would provide them

The actual behavior is that the tool is ignored completely and treated as another block, and is put in the hut block of whatever profession I tried to hand it to. What's even more odd is that it HAS used other clumsy level tools, simply though it was mostly stone with a wooden handle.

1. Make the tool I described
2. Make sure it's the only tool they have available
3. Watch as they demand for a pickaxe, even providing an image of other tinkers pickaxes.

Frankly, I have no idea what's going on and I'm completely new to this version of the mod, last time I played was back in 2017, and wow does the game look a lot better. But would appreciate any help as soon as possible, as I refuse to expand until this is solved since I need them to use iron tools. Also Also, this is a brand new colony, so maybe that has something to do with it.

**Comment by OCDCleric** [comment]
Ok so more info needed.
1. What level is the hut your giving the tool to?
2. What mining level is the pickaxe?
3. What huts are refusing the pickaxe in question?

**Comment by Raycoms** [comment]
Closed after no further response.
Tinker tools are supported but the levels can't be higher than the worker levels (if he can't use vanilla iron he won't use tinkers iron either).
