### ISSUE TITLE
Can't place Supply Camp

### ISSUE THREAD

**Issue by ASimpleEgg** [ldtteam/minecolonies#3695]
Minecolonies version: 1.12.2-0.10.282-ALPHA-universal. 

Expected behavior
Having ensured that there is a 17x17 area of grass with 1 layer of pure dirt 1 block below (as suggested on the thread for Issue #1544), and with no ferns, flowers, long grass etc, I place the Supply Camp. 

Actual behaviour
I use the Builder's Tool to position the Supply Camp where I want it to go but after clicking the green tick it then disappears without any sort of error message or explanation.

![2019-06-23_23 33 52](https://user-images.githubusercontent.com/51216869/59983086-38066900-9613-11e9-899e-06d0276ab013.png)
![2019-06-23_23 34 14](https://user-images.githubusercontent.com/51216869/59983087-38066900-9613-11e9-9384-6cab9c1d8755.png)
![2019-06-23_23 49 05](https://user-images.githubusercontent.com/51216869/59983088-389eff80-9613-11e9-9939-fefbad35d8f8.png)
![2019-06-23_23 33 27](https://user-images.githubusercontent.com/51216869/59983089-389eff80-9613-11e9-94fc-3be8bf3096ce.png)

Steps to reproduce the problem
Copy what I outlined and pictured above?

(thank you)

**Comment by Talyda** [comment]
The supply camp/ship are the only things you shouldn't use the build tool to place =) Just put the camp or ship straight onto the ground/water.
There's a decoration of each one that you use the build tool for, but for placing it to start you just place the block (in theory you shouldn't have a build tool until you have placed the camp, and receive the tool and townhall hut block from the camp =))

**Comment by Asherslab** [comment]
@ASimpleEgg you cannot use the build tool to place the supply schems. please use their respective items
