### ISSUE TITLE
Unable to break blocks after breaking town center block and placing it a few blocks away

### ISSUE THREAD

**Issue by ghost** [ldtteam/minecolonies#3696]
Version: 1.12.2-0.10.302-ALPHA-universal

### Expected behavior

Destroying a town center block and moving it to a new location would not disable the owner from being able to break blocks.

### Actual behaviour

-I am the owner of a colony. I destroyed a town center block that was not in "Build Mode" and re-positioned it somewhere else (within 4 blocks of the original location.) When I tried to break some blocks-Dirt,Grass,Stone,Coal etc I was unable to except glow-stone. Glowstone is the only block I can break. Breaking blocks outside of the Colony limits is possible. I am able to do every other function like open chests or interfaces, fight mobs, and so on. I attempted disabling protections in the config file and nothing changed.

Side note: I had 2 builder Huts, Restaurant and a mining place built before i broke the town center

### Steps to reproduce the problem

1. Become Owner of Colony
2. Build a Dark oak medieval town center block 
3. destroy town center block 
4. Place town center block somewhere else 
5. Attempt to mine a block

**Comment by OCDCleric** [comment]
Check your permissions in the town hall block. Its on the second page where you can assign officers in multilayered.

**Comment by ghost** [comment]
All Permission nodes are set to on and I still experience the same problem as described.
