### ISSUE TITLE
[Feature] Shingle Enhancement

### ISSUE THREAD

**Issue by OCDCleric** [ldtteam/minecolonies#3697]
I'm troubled... I need more shingles and varriations. To be exact I need two new things for new shingles. One easy! The other not so much...

 1. Shingle Colours: To be exact I would like to request colored shingles or a system to dye the shingles colours. Would be nice having blue, yellow, and green shingles right?

 2. Shingle slabs? This one is a bit tough to explain so I'll put a picture here.
![2019-06-24_18 16 13](https://user-images.githubusercontent.com/29760230/60055557-fc6bad80-96ab-11e9-8bc5-b5843b3a2513.png)
So on the left is the roof style i'm using for a schematic set i'm making. On the right is the result of using shingles. What i'm hoping for is a new shingle type that could smooth this out somehow or for the two shingle types to interact?

**Comment by Asherslab** [comment]
shingles colours already planned

**Comment by Asherslab** [comment]
for the second thing, you'd probably have to be more specific in how you'd want it to look.

**Comment by OCDCleric** [comment]
Well its hard to explain... But i did have an idea. One would be a slab and the other a block and the two would form a set. The slab would be the same as the roof shingle block/stair except the height and angle would be half. From that. The block would litterally be the the new slab shingle on top of a regular slab but as an actual block... I'll try making a picture of it tomorrow.

Placement might be difficult, but i think you can reference Immersive Engineering's conveyor placement for help.

**Comment by TheMerricat** [comment]
What might be easier to request would be a set of shingles that have a different amount of slant to them so that instead of being a 45 degree angle they slope more along a 30 degree angle (from looking at the picture). That would give you the 2 horizontal 1 vertical slope that I think you are aiming for.

**Comment by OCDCleric** [comment]
The problem is orientation and height though. Since slabs don't act like stairs... Though i suppose you could use stairs for them even if the look slab sized...

**Comment by Graepix** [comment]
These could be added through the use of vertical slabs. You could have two variations of the shingle slabs, a horizontal and a vertical version.

**Comment by OCDCleric** [comment]
Actually i hust got some graph paper so i can draw up a rough idea of how it would work but i just stupidly realized you could do this by making both as a set of stairs. Gonna start drawing now.

**Comment by OCDCleric** [comment]
![20190719_143813](https://user-images.githubusercontent.com/29760230/61557890-7be26780-aa33-11e9-8f94-c85bf7ba1de1.jpg)

Ok so heres the really rough idea of it. Two different shingles both using the stair block as a base. The slopes connect to each other. Since both use the stairs as a base orientation is no problem.

**Comment by Raycoms** [comment]
Are planned, will be in structurize
