### ISSUE TITLE
Colonies not deleting

### ISSUE THREAD

**Issue by SeaDonkey81** [ldtteam/minecolonies#3698]
### Minecolonies version
minecolonies-1.12.2-0.10.302-ALPHA-universal

### Expected behavior
colony border completely gone and i should be able to place another camp down without it telling me i can't because of an existing colony.

### Actual behaviour
As the server owner when i delete a colony that i placed the colonies border stays up even though the colony is gone from game and from colony list. I cannot place another supply camp in the same location because of existing colony. 

### Steps to reproduce the problem
1. Place supply camp (I used the land based one)
2. place TH using build tool.
3. /mc colony delete colony: 1 confirmdelete: true
4. ... Profit

https://gist.github.com/SeaDonkey81/33002f3c9e8e1476d427bb7cfb4a5b67

**Comment by Raycoms** [comment]
You can only place one supplycamp per player per world. If you want a new colony you gotta either keep the townhall or craft it.

**Comment by SeaDonkey81** [comment]
Thanks for closing my issue when you didn't even read fully what my issue was.. I am testing MC out as the server owner and I'm having an issue with the colonies not being fully deleted. I can move a good distance away and place another camp, but i cannot place another camp next to where i USED to have a colony. It tells me there is an existing colony there when it was DELETED. No, it does not show up in the colony list. If you're not gonna help then at the least tell me where i can find the server files that store player colony data and i'll figure it out my self.
