### ISSUE TITLE
Miner Breaking Blacks

### ISSUE THREAD

**Issue by Xaleth** [ldtteam/minecolonies#3700]
### Minecolonies version

Version: idk, but it's the latest git version.

### Expected behavior

- When miner breaks coal/diamond/redstone ore, there should be coal/diamonds/redstone in inventory.

### Actual behaviour

- When miner breaks coal/diamond/redstone ore, there are coal/diamond/redstone ore blocks in inventory instead.

### Steps to reproduce the problem

1. Watch miner break coal.
2. Look in inventory.
3. See coal ore block.
4. Get pissed off that you have to break the ore blocks.

**Comment by Raycoms** [comment]
Those are bonus blocks, not the blocks he finds =)
