### ISSUE TITLE
NPE with Deliveryman

### ISSUE THREAD

**Issue by Sandriell** [ldtteam/minecolonies#3701]
### Minecolonies version

Version: minecolonies-1.12.2-0.10.298-ALPHA-universal

### Expected behavior

Not to throw an NPE

### Actual behaviour

https://gist.github.com/Sandriell/f6a9ae1de48ed5d82d863ad4d54dd555

These happen regularly. Usually it breaks the deliveryman and she stops working and I have to restart Minecraft.

### Steps to reproduce the problem

Not sure why this has started happening. :(

**Comment by marchermans** [comment]
Run a RS reset, seems like you have some dangling request in there, fix for it is being worked on, is a bit more complicated though.
