### ISSUE TITLE
[Bug] Builder destroys blocks instead of picking them up

### ISSUE THREAD

**Issue by Frjlh01** [ldtteam/minecolonies#3702]
I noticed that when upgrading buildings, if an old block is in the way of a new block or if it is no longer needed in the new building it will simply be destroyed and the worker will not get the old block back. This makes the whole process require a lot more resources, and it is unrealistic. For example when upgrading medieval oak citizen hut from lv1 to lv2 the old white bed is destroyed rather than recycled, the whole roof is destroyed too even though the upgrade practically just moves the roof up a bit.

I'm not sure if this is intended, but it does slow progress down a lot so please do consider changing this.

**Comment by TheMerricat** [comment]
The builder actually keeps blocks they intentionally break (assuming those blocks are the sort that aren't destroyed by being broken (aka glass), to be dropped off into the warehouse if they weren't needed for the build any more or replaced if they fit into it somewhere else.

I don't know about the roof, but the bed isn't being 'destroyed' but rather in the middle of placing the new floor plan the builder accidently breaks the bed by placing a block where one half of the bed is. When that happens the bed 'pops' off and becomes an item to pick up and if you or the builder don't walk over and pick it up, it'll despawn in the normal time frame for dropped items. 

Typically I go through my buildings and proactively break any title entity (torches, item frames, paintings) and two block items (doors, beds) that I consider 'valuable' or a pain to replace, and just put them back in the builder's inventory to put down.

Outside of lag issues where builders think they placed a block but the server didn't and so the builder 'eats' the block, those are the only times I've seen a builder 'destroy' blocks.

You can see the same issue with torches.

**Comment by Sandriell** [comment]
I have watched my builder replace blocks. She is definitely not picking up the replaced blocks unless they are going into some other inventory that I cannot see. And even if that is true they are not ending up back at the warehouse. For example, I had an anvil in my miners hut, it got replaced when I upgraded, and now it is gone. It is not in the warehouse, the miners hut or anywhere else.

**Comment by Raycoms** [comment]
Fix pushed, oopsy

**Comment by WenXin20** [comment]
I noticed this happened during the repairing of buildings as well.

**Comment by Raycoms** [comment]
both fixed

Am Do., 27. Juni 2019 um 16:54 Uhr schrieb WenXin2 <notifications@github.com
