### ISSUE TITLE
Feature Request: Choose the ores the Smelter requests

### ISSUE THREAD

**Issue by MemeryMachinery** [ldtteam/minecolonies#3703]
So, just the other day I noticed that my smelter received a redstone ore lucky block. He smelted it and received 1 redstone dust. Doesn't that seem like a waste? Even if the smelter was to be at the level to triple ores you would still only get 3 which is still less than the 4-5 or so that you get from mining it yourself. On that same note, who smelts coal ore or Lapis either?

As such, my suggestion is that we either get a feature to turn off and on ores that we want the smelter to request (from the warehouse) or we have the lucky blocks give the correct drops to the miner so there won't be any redstone ore or Lapis Lazuli smelting. Not smelting coal ore would be nice too as that kind of is redundant in itself if you are smelting it with coal.

I mean I wouldn't know since I am very much so a noob when it comes to coding mods, but for the miner lucky blocks solution couldn't it just be made a config option to change whether the miner receives the ore block or the drop itself for the correct amount? I think that would be a quicker solution at the source of the issue so then the smelter wouldn't need to be touched. I'm fine either way as long as I can stop my smelter from smelting redstone, lapis and coal ore 😅

I find that the doubling of ingot ores is already enough incentive to upgrade the smelter but wasting ores that drop multiple items already really seems like a waste...

**Comment by Asherslab** [comment]
Personally, i do not believe we should have an exemption list for the smeltery, instead what's happening here is that the miner, when he gets the random blocks, is getting ores for things that usually give drops e.g. coal, redstone, lapis. we should instead, very very easily, adjust the config to give the drops themselves, and not the ores

**Comment by OCDCleric** [comment]
Hm... Adding a filter to the smelter isnt a bad idea since it would allow focusing on Iron ore or making charcoal.

Adding a config for the chance to get a lucky ore feels like it shoulda been added a while ago. Maybe an additional config option for the amount of lucky ore gotten as well?

**Comment by Raycoms** [comment]
He creates lucky ores for a long time

**Comment by OCDCleric** [comment]
Just had a thought but maybe lucky ores can only occur when miner is using a pickaxe with silktouch?

**Comment by Raycoms** [comment]
There are also lucky ores for the miner =P

Am Fr., 28. Juni 2019 um 12:16 Uhr schrieb OCDCleric <
notifications@github.com>:

**Comment by MemeryMachinery** [comment]
Sorry that I havent responded to any if the discussion here lately. My internet has been down for an entire day and it still isnt up for my computer. All im getting is a temporary weak wifi and im sending this on my phone. Messaging is a lot more time consuming this way so im going to wait for my pc to be back up to continue here.

But for the most part here I am fine with the miner getting lucky blocks/ores and such normally. There just doesnt appear to be an easy way to change the drop of the lucky ores from ore blocks to the actual items like instead of getting 1 redstone ore they receive 5 redstone dust and so on for lapis and coal.

For the smelter I never even thought of using him for creating charcoal. Having a system that allows you to choose what he requests from the warehouse would be usefull for determining specifically what you want him to focus on. And it should be what he requests not just what he will smelt. Because then he probably would still request the ores but not smelt them. Then you would have ores build up in his worker hut block eventually causing clutter.

**Comment by OCDCleric** [comment]
I havent checked but does smelter target anything on ore dictionary?

The only other option, and less convenient playerwise, is to add a blacklist config option to prevent certain ores from.being smelted. Not exactly the best but it would solve the issue and give an option for mod packs and servers.

Ps. Maybe all the huts need their own configs?

**Comment by MemeryMachinery** [comment]
@OCDCleric I wouldn't say that there would need to be a blacklist option to prevent ores from being smelted. It should just change what they ask for from the warehouse. Because if they still request all ores but an ore is blacklisted from being smelted it would just _sit in their inventory and build up over time._ So, I think if the smelter would be changed he should also be able to smelt wood blocks into charcoal and add another page to his worker hut block that allows you to turn on and off what blocks he will request from the warehouse to smelt. I mean the second page already has you choose what he uses to smelt items with. Why not have another page that chooses what he requests to be delivered to smelt?
