### ISSUE TITLE
is there a population cap in minecolonies?

### ISSUE THREAD

**Issue by chyper111** [ldtteam/minecolonies#3704]
### Minecolonies version

Version: 

### Expected behavior

- 

### Actual behaviour

- 

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit

**Comment by MemeryMachinery** [comment]
Yes, I am quite sure it is at 50 default. You can raise it in the minecolonies.cfg file.

**Comment by chyper111** [comment]
tks
