### ISSUE TITLE
Fishermen accept, but won't use, modded fishing rods

### ISSUE THREAD

**Issue by WenXin20** [ldtteam/minecolonies#3707]
### Minecolonies

Version: 0.10.303-Alpha

### Expected Behavior

-  I had expected to see the fishermen able to accept and use the modded fishing rods. Or at least only accept vanilla fishing rods. 
- The mods I have that add fishing rods are Aquaculture, Just a Few Fish, and Thermal Foundation.

### Actual Behavior

-  The fisherman accepts all fishing rods, modded or vanilla, but will just walk around until he/she is given a vanilla fishing rod.

### Steps to reproduce the problem

1.  Hire a Fisherman
2.  Provided him/her with a modded fishing rod.
3.  Watch the fisherman just walk around, doing nothing else.
4. ... Profit

**Comment by Raycoms** [comment]
Yeah for the time being that won't change. The fishing system is quite a pain to work with to support other rods. Maybe in the future.
