### ISSUE TITLE
[Feature] Inn/Pub

### ISSUE THREAD

**Issue by OCDCleric** [ldtteam/minecolonies#3708]
In reference to #3673 

Thinking about hostile mobs early game got me thinking about multiplayer aspects as well. The result is the Inn/Pub combo. This would be a replacement to the restaurant.

Features:
   1. Pub - The first floor of the structure would act as a place for the npcs to get food like usual.
   2. Inn - Consists of 1st, 2nd, and maybe 3rd floor. Would act as a place of adventurer/mercenary recruitment.
   3. Purchase contracts at pub on first floor. Contract would be length of time x resources. Food is provided by pub anyways.
   4. Inn would provide lodging for adventurers/mercenaries. May provide lodging for a feature like travelling merchants.
   5. Number of rooms available would probably start as 2 or 3 and reach 6-9.
      5a. Config option to restrict number of contracts?
   6. Inn may provide lodging for excess citizens.

This is all i can think of at the moment.

**Comment by Asherslab** [comment]
https://github.com/ldtteam/minecolonies/issues/309
