### ISSUE TITLE
[Request] Lumberjack enhancement with dynamic trees

### ISSUE THREAD

**Issue by lebanni** [ldtteam/minecolonies#3709]
If possible, have the lumberjack to cut most valuable trees first, ie those that give more logs.

**Comment by Raycoms** [comment]
Finding trees is a complex problem which requires a lot of processing so we take the first we find. I think finding many and selecting the best would be not feasible within Minecraft

**Comment by someaddons** [comment]
you could also increase the config setting, so he only cuts larger/older trees

**Comment by lebanni** [comment]
I didn't see this was added. Thanks.
