### ISSUE TITLE
Bugged Guard

### ISSUE THREAD

**Issue by Falcon7617** [ldtteam/minecolonies#371]
### Minecolonies version

Current

### Expected behavior

- I switched the guard's job from ranger to knight and then back to ranger hoping the guard would become a ranger.

### Actual behaviour

- The guard requires the sword and will not use the bow

I have no clue if it is when the guard gets a kill or if it should be an instantaneous switch.

**Comment by marvin-bitterlich** [comment]
We intentionally removed that. Otherways you could just switch at any moment or level as ranger and then make him a Knight. A new guard will change his job.

**Comment by Falcon7617** [comment]
Thanks Kos for the explanation.
