### ISSUE TITLE
Shape Tool Crash

### ISSUE THREAD

**Issue by OCDCleric** [ldtteam/minecolonies#3713]
### Minecolonies version

Version: 0.10.302

### Expected behavior

-  Shape Tool able to make shapes upon inputting numbers.

### Actual behaviour

-  Upon inputting numbers into Height Width Length a crash occurs. Specifically if you enter a number into Width and a larger number than Length.

[crash-2019-07-03_13.39.33-client.txt](https://github.com/ldtteam/minecolonies/files/3356709/crash-2019-07-03_13.39.33-client.txt)

### Steps to reproduce the problem

1. Start Shape Tool
2. Input 1 - Infinity in Width
3. Input +1 to the number in Width into Length
4. ... Profit

**Comment by marchermans** [comment]
What are you trying todo: You can NOT enter none Numbers in those boxes it is a known issue!
