### ISSUE TITLE
crash from ticking entity.

### ISSUE THREAD

**Issue by chyper111** [ldtteam/minecolonies#3714]
### Minecolonies version

Version: 0.9.126-alpha

### Expected behavior
it was working fine and then after 30 mins it crashed i tryed to start again but it crash the momnet i loaded in see crash report 2.

- 

### Actual behaviour

- 

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit
https://gist.github.com/chyper111/2a4dcd39a53faec9386fe15383e4ab85
https://gist.github.com/chyper111/f8f2fe738d38f05b37e914ed38acf740

**Comment by chyper111** [comment]
sorry I had to write this quick ill be away for a day or so please let me know if you need anything else

**Comment by OCDCleric** [comment]
0.9.126? Cant find this version... Since it seems to be an old version try updating it first? Unless this is an old modpack?

**Comment by marchermans** [comment]
Na he is running 1.12.2-0.10.304-ALPHA, but for now issue I will Redirect him to discord to get more details when he Comes back.
