### ISSUE TITLE
console spam

### ISSUE THREAD

**Issue by siroosi** [ldtteam/minecolonies#3715]
Hi Everyone,
i am facing a problem with Minecolonies;

**Minecolonies version:**
minecolonies-1.12.2-0.10.259-RELEASE-universal
forge-1.12.2-14.23.5.2838-universal

**Actual behaviour**
After updating from 1.12.2-0.8.7582 to 1.12.2-0.10.259, Minecolonies is spamming the console with

"[minecolonies]: Missing world capability with colony manager!" 

about 20 times per second. Starts right after server is loaded completely and will never stop. If i use 0.8.7582 it does not appear. Let me know what other information i should provide.

**Steps to reproduce the problem**
update Minecolonies from 1.12.2-0.8.7582 to 1.12.2-0.10.259

Thank You

**Comment by Raycoms** [comment]
I don't even know how this is possible =O

Am Do., 4. Juli 2019 um 16:05 Uhr schrieb siroosi <notifications@github.com

**Comment by someaddons** [comment]
might be an upgrade issue from that really old version

**Comment by marchermans** [comment]
He is coming from a version with the external store to a version with the cap based stores. How did we convert them?

**Comment by Raycoms** [comment]
On Load, but the error he is getting only happens when the world has no
capability attached. Which is weird.

>

**Comment by siroosi** [comment]
If there was a major change with the stores, is there a version which converts the world to the new cap based stores maybe?

edit; i actually don´t want to bother you with that problem from an ancient version. I tried for weeks to find a solution on my own. But maybe a workaround to rescue our world would do. I would be ok with losing the colonies in it, but i can´t lose the complete save.

**Comment by someaddons** [comment]
just load the world without minecolonies then, and readd it later

**Comment by siroosi** [comment]
That´s what i tried as well. Did not help. But i finally found a way to fix it:

1. set up a new forge server with complete modpack from scratch
2. start it up and let it create a new world with same settings and seed as the old one
3. copy only the region files from the old server to the new one
4. profit

thank you guys and take care
