### ISSUE TITLE
How to download an older release?

### ISSUE THREAD

**Issue by Rencer** [ldtteam/minecolonies#3716]
There are no older versions on Curseforge than for Minecraft 1.10.
The only option here is to go to the releases, scroll down, than click next, then scroll down, click next, scroll, click , scroll, click...
With as many releases as this mod have, it is almost literally impossible to reach those old releases; nobody has time to click and scroll down for ages.
It would be nice, if we have a quick way, to reach versions of the mod for specific Minecraft versions, from one place. Curseforge would be (IMO) the easiest way, but it is fine, if at least here on GitHub, we can access those older releases easily. Thanks.

**Comment by someaddons** [comment]
1.10 is the oldest version aviable and only 1.12 is still updated.

**Comment by Rencer** [comment]
So all the older versions are gone forever?
I'm so sad, that we can't get our nostalgia dose of this mod anymore...
