### ISSUE TITLE
Idea: Improved Housing

### ISSUE THREAD

**Issue by CTH999** [ldtteam/minecolonies#3717]
So, a lot of the buildings have beds in the second floor. But, those people still need a "Citezens Hut"

What I propose is that those buildings, people who work there sleep in those beds. Buildings that don't have beds, then they need a "Citzens Hut". Then, some of the different versions might require more or less "Citezens Huts". Some might have beds in all buildings, requiring none. Others might have beds in only full-time jobs (Not the restaurant, for instance), and so on.

Also, maybe some jobs for the Town Hall?

**Comment by lunadragnstar** [comment]
The beds in the worker huts are just decoration and don't function as a citizen bed.

**Comment by Raycoms** [comment]
Yeah, citizen hut chests are necessary. We will in the future allow to integrate citizen huts into worker huts (similar to the barracks with barrack towers) but for now not.

**Comment by CTH999** [comment]
@Raycoms 

Glad to see it's in the works! Can't wait for the update, but I'll have to, eh?

@lunadragnstar I wasn't say it did, I said it _should_. I know it doesn't.

and, I'll get back to you about the town hall. (I'm just thinking. You have all those rooms...)
