### ISSUE TITLE
Intermittent Tick Spike

### ISSUE THREAD

**Issue by Castone22** [ldtteam/minecolonies#372]
While running a profile, i saw a fairly long tick time spike occurring intermittently seemingly having to do with saving.

http://pastebin.com/h87iDXLJ

**Comment by Raycoms** [comment]
Does this happen a lot?
We're storing the colony info to disk at that location

Am Samstag, 24. Dezember 2016 schrieb Luke Ridge :

**Comment by marvin-bitterlich** [comment]
As I see that tick is 200ms long, seems to be fairly okay for me. Saving needs disc access and with the current minecraft design we can't offload that without stopping the Thread anyways or running into all kinds of problems. 

How many colonies do you have, what kind of server and what kind of hard drive? Do you have a disc drive that maybe needed to spin off and that caused the spike?

On our main server with over 200 colonies we have a 2.2MB save file for minecolonies on a SSD and no noticeable lag spikes while saving. We have all other sorts of lag, normal for big servers, but saving is currently not that much of an issue.

If you have any ideas how to improve our saving process, we are always open for ideas/pull requests/developers 😉

**Comment by Castone22** [comment]
I was trying to narrow down the cause of a recurring tps spike when I found this.  Quick glance now that I had the chance shows that things on your end are fairly optimal.  Thanks for responding though :)
