### ISSUE TITLE
Storage Rack Quark Chest Buttons Support

### ISSUE THREAD

**Issue by WenXin20** [ldtteam/minecolonies#3720]
### Minecolonies Version
- 0.10.306-Alpha

### [Quark Version](https://quark.vazkii.net/)
- r1.5-168

###Description
- Support for Quark's Sort, Deposit, and Merge Chest buttons for the Storage Rack would be nice.
- The link above takes you to the Quark website, the buttons are found under the management tab.

**Comment by mummabia** [comment]
I too would like to see this, as well as racks working with other inventory sorting mods such as Inventory Tweaks.  A previous post suggested that it's a problem on the Inventory Tweaks mod side, but perhaps you could work with them to implement this feature?  It would be very much appreciated.

**Comment by Raycoms** [comment]
It's actually a config setting of inventory tweaks the player has to setup
to detect racks as containers. The same I believe is true with the other
mods with similar functionality.

Am Sa., 3. Aug. 2019 um 23:22 Uhr schrieb mummabia <notifications@github.com

**Comment by WenXin20** [comment]
I don't see a way to do that through the config file for Inventory Tweaks. I'm pretty sure that other mods have to add support for it. 
For Quark, there is an option to add it through the config, but that forces it into the GUI. It might be best if the mod adds support for it.
