### ISSUE TITLE
Scrolling Improvement for the Building Tool

### ISSUE THREAD

**Issue by WenXin20** [ldtteam/minecolonies#3721]
### Minecolonies Version

Version: 0.10.306-Alpha

### Expected behavior

- Smooth scrolling for the building tool, and/or a bigger drop-down box.

### Actual behaviour

-  The drop-down box is very small, and scrolling causes it to skip over several options, especially when choosing the design type for the hut.

### Steps to reproduce the problem

1.  Craft a hut
2.  Open the building tool GUI
3.  Click on the drop-down box.
4. Try to scroll up or down without skipping over several options.
5. ... Profit

**Comment by Nightenom** [comment]
Will get fixed in 1.14 with updates of other libraries, if you feel that you can't select some options now (in 1.12) please reopen

**Comment by WenXin20** [comment]
Sounds good. It was just annoying, but not unplayable.
