### ISSUE TITLE
Crashes server with a structurize error on server

### ISSUE THREAD

**Issue by taluseve** [ldtteam/minecolonies#3724]
[forge-1.12.2-14.23.5.2838-installer-win.exe.log](https://github.com/ldtteam/minecolonies/files/3390452/forge-1.12.2-14.23.5.2838-installer-win.exe.log)

**Comment by someaddons** [comment]
follow the given reporting format

**Comment by Raycoms** [comment]
This seems the wrong log =D

Am So., 14. Juli 2019 um 18:46 Uhr schrieb taluseve <
notifications@github.com>:

**Comment by Leonature26** [comment]
i had this same issue because i forgot to remove optifine on server side. Might help others.
