### ISSUE TITLE
Lumberjack doesn't replace snow layers with saplings

### ISSUE THREAD

**Issue by WenXin20** [ldtteam/minecolonies#3728]
### Minecolonies version

Version: 0.10.307-Alpha

### Expected behavior

-  The lumberjack should be replacing the snow layer with saplings after the tree is cut down. 
- He should be allowed to replace any replaceable block with a sapling, such as tall grass or snow layers.

### Actual behaviour

-  The tree is cut down but not replanted if a snow layer forms on top of the block before he can replant it. In my case, I have a mod called Snow Real Magic, which allows snow layers to fall like sand, but ends up blocking lumberjacks from replanting.

### Steps to reproduce the problem

1.  Plant any sapling in a snow biome.
2.  Let the Lumberjack cut it down.
3.  Place a snow layer on the dirt where the tree was before he can replant.
4. ... Profit and he won't replant.

**Comment by OCDCleric** [comment]
Im confused here. The spot where sapling gets planted shouldnt have snow on it. So did snow cover it up after?

**Comment by Raycoms** [comment]
Probably he cut it down, then it snowed and then he wasn't able to replace the sapling

**Comment by OCDCleric** [comment]
They do have a tendency to not replant immediately if there is a tree connected or right next to it.

**Comment by WenXin20** [comment]
Yes, @Raycoms is right. 
At the time I had checked, the area had been cleared of trees, but no saplings were planted.

**Comment by Raycoms** [comment]
That's not much of a problem, we can allow him to clear snow, that's an
easy code fix.

Am Mi., 17. Juli 2019 um 11:36 Uhr schrieb WenXin2 <notifications@github.com
