### ISSUE TITLE
[Suggestion] Separate player data into separate files

### ISSUE THREAD

**Issue by xenoflot** [ldtteam/minecolonies#373]
Hi guys,

If I'm reading your .dat file correctly, minecolonies is storing all player data in a single file. From an admin perspective, it would be better if there was one .dat per player UUID. That way if one player's colony is bugged, the player's file can be deleted without affecting other users.

Cheers!

**Comment by xenoflot** [comment]
OK discovered that you store some data in playerdata as well. Definitely better to have everything in one place and separated by player :)

**Comment by Raycoms** [comment]
Unfortunately, that might cause a gigantic folder full of .dat files for
each player.
There is a command to delete the colony of a specific player /mc colony
delete <playername>

2016-12-24 21:46 GMT-02:00 xenoflot <notifications@github.com>:

**Comment by xenoflot** [comment]
Fair enough.
