### ISSUE TITLE
GUI from Travellers back pack dont oben but server error from Minecolonies

### ISSUE THREAD

**Issue by SpartaWarsec** [ldtteam/minecolonies#3731]
We have a server with ("all the mods 3 mod pack")

### Minecolonies version

Version: minecolonies-1.12.2-0.10.202-RELEASE-universal

### Expected behavior

 it would open the gui from Travellers Backpack

### Actual behaviour

First of all you have to craft it and when you have it in your quick bar, you can usually open it with right click on your mouse but that doesn't work for me. I can also place it anywhere i want and when i placed it i can also pick it up and carry it on my back but i can't open it. I already tried to change the controls but that didn't work either. That means i can't take it off my back either cause i can't open it but the gui for tank and tools appears at bottom right and with shift and the mousewheel i can switch tools but i can't open the backpack itself.

and this error from server 

[22:01:39] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_211]
at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_211]
at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.NullPointerException
at com.minecolonies.coremod.util.TownHallRecipe.func_77569_a(TownHallRecipe.java:67) ~[TownHallRecipe.class:?]
at net.minecraft.item.crafting.CraftingManager.func_82787_a(CraftingManager.java:199) ~[aku.class:?]
at com.tiviacz.travellersbackpack.gui.container.ContainerTravellersBackpack.func_75130_a(ContainerTravellersBackpack.java:346) ~[ContainerTravellersBackpack.class:?]
at com.tiviacz.travellersbackpack.gui.container.ContainerTravellersBackpack.(ContainerTravellersBackpack.java:63) ~[ContainerTravellersBackpack.class:?]
at com.tiviacz.travellersbackpack.handlers.GuiHandler.getServerGuiElement(GuiHandler.java:27) ~[GuiHandler.class:?]
at net.minecraftforge.fml.common.network.NetworkRegistry.getRemoteGuiContainer(NetworkRegistry.java:253) ~[NetworkRegistry.class:?]
at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:88) ~[FMLNetworkHandler.class:?]
at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2550) ~[aed.class:?]
at com.tiviacz.travellersbackpack.items.ItemTravellersBackpack.func_77659_a(ItemTravellersBackpack.java:113) ~[ItemTravellersBackpack.class:?]
at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:217) ~[aip.class:?]
at net.minecraft.server.management.PlayerInteractionManager.func_187250_a(PlayerInteractionManager.java:358) ~[or.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:765) ~[pa.class:?]
at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:32) ~[mb.class:?]
at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:9) ~[mb.class:?]
at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_211]
at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_211]
at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
... 5 more

### Steps to reproduce the problem

First of all you have to craft it and when you have it in your quick bar, you can usually open it with right click on your mouse but that doesn't work for me. I can also place it anywhere i want and when i placed it i can also pick it up and carry it on my back but i can't open it. I already tried to change the controls but that didn't work either. That means i can't take it off my back either cause i can't open it but the gui for tank and tools appears at bottom right and with shift and the mousewheel i can switch tools but i can't open the backpack itself.

This is the modlist 

Guide-API (by TehNut)
Crafting Tweaks (by BlayTheNinth)
CoFH Core (by TeamCoFH)
[SBM] Wooden Shears (by darkguardsman)
MobTotems (by CorwinJ)
KJLib (by kjmaster2)
ReAuth (by TechnicianLP)
CoFH World (by TeamCoFH)
QuantumStorage (by Gigabit1011)
Tinkers' Tool Leveling (by bonusboni)
OpenModsLib (by OpenMods)
Just Enough Dimensions (by masa_)
No Mob Spawning on Trees (by oldjunyi)
Mystical Agradditions (by BlakeBr0)
Shadowfacts' Forgelin (by shadowfactsmc)
AppleCore (by squeek502)
Ore Excavation (by Funwayguy)
Not Enough Wands (by romelo333)
ExtraCells2 (by Destroyer7128)
Real Filing Cabinet (by bafomdad)
Cooking for Blockheads (by BlayTheNinth)
Quark (by Vazkii)
Cyclops Core (by kroeser)
Extra Utilities (by RWTema)
AppleSkin (by squeek502)
Binnie's Mods (by Binnie567)
Thaumic Inventory Scanning (Thaumcraft Addon) (by BlayTheNinth)
Compact Solars (by progwml6)
Extreme Reactors (by ZeroNoRyouki)
Woot (by Ipsis)
ShadowMC (by shadowfactsmc)
Water Strainer (by Rubironi)
Pam's Cookables - Pam's Harvestcraft Addon (by BloodWorkXGaming)
Wizardry Mod (by Demoniaque)
RFTools (by McJty)
FastWorkbench (by Shadows_of_Fire)
Compact Machines (by Davenonymous)
Traverse (by ProfessorProspector)
Thermal Dynamics (by TeamCoFH)
TombManyGraves 2 API (by M4thG33k)
Dark Utilities (by Darkhax)
Redstone Flux (by TeamCoFH)
Overloaded (by cjm721)
Controlling (by jaredlll08)
Magic Bees (by MysteriousAges)
Blockcraftery (by epicsquid319)
Baubles (by azanor)
Iron Backpacks (by gr8pefish)
WrapUp (by TheLMiffy1111)
EnderCore (by tterrag1098)
Fairy Lights (by pau101)
AI Improvements (by darkguardsman)
The One Probe (by McJty)
BetterFps (by Guichaguri)
Reborn Core (by modmuss50)
Chisels & Bits (by AlgorithmX2)
RandomPatches (by TheRandomLabs)
NotEnoughIDs (by fewizz)
WanionLib (by WanionCane)
Applied Energistics 2 (by AlgorithmX2)
Waystones (by BlayTheNinth)
Bad Wither No Cookie - Reloaded (by kreezxil)
BdLib (by bdew)
Aroma1997s Dimensional World (by Aroma1997)
Just Enough Items (JEI) (by mezz)
Natura (by mDiyo)
Just Enough Resources (JER) (by Way2muchnoise)
Pressure Pipes (by bdew)
More Overlays (by feldim2425)
Ranged Pumps (by raoulvdberge)
Custom Backgrounds (by lumien231)
Redstone Arsenal (by TeamCoFH)
Mystical Agriculture (by BlakeBr0)
Placebo (by Shadows_of_Fire)
Immersive Tech (by ferroo2000)
MalisisCore (by Ordinastie)
KleeSlabs (by BlayTheNinth)
Construct's Armory (by theillusivec4)
Ender Storage 1.8.+ (by covers1624)
Psi (by Vazkii)
DiscordSuite (by HRZNStudio)
OpenBlocks (by OpenMods)
The Lost Cities (by McJty)
Career Bees (by RWTema)
Integrated Tunnels (by kroeser)
PneumaticCraft: Repressurized (by desht)
Rustic (by mangoose3039)
Nature's Compass (by ChaosTheDude)
LibrarianLib (by yrsegal)
Quick Leaf Decay (by lumien231)
Forestry (by SirSengir)
Chameleon (by jaquadro)
Tinkers Construct (by mDiyo)
Aroma1997Core (by Aroma1997)
MCMultiPart (by amadornes)
HelpFixer (by matthewprenger)
CraftTweaker (by jaredlll08)
Lost Souls (by McJty)
Advanced Rocketry (by zmaster587)
Useful Nullifiers (by Bartz24)
Tinker I/O (by gkbm2011)
Industrial Craft (by Player)
JAOPCA (by TheLMiffy1111)
AbyssalCraft (by Shinoow)
Additional Banners (by Darkhax)
Armory Expansion (by YaibaToKen)
Unloader (by Unnoen)
Default Options (by BlayTheNinth)
Custom Main Menu (by lumien231)
Morph-o-Tool (by Vazkii)
Simply Jetpacks 2 (by Tomson124)
Thaumic JEI (by Buuz135)
ZeroCore (by ZeroNoRyouki)
Iron Chests (by progwml6)
No Night Vision Flashing (by TeamCoFH)
Chisel (by tterrag1098)
Advanced Generators (by bdew)
Thaumcraft (by azanor)
Mod Name Tooltip (by mezz)
OC XNet Driver (by Davenonymous)
Diet Hoppers (by RWTema)
Thermal Foundation (by TeamCoFH)
MTLib (by jaredlll08)
RFTools Dimensions (by McJty)
ConnectedTexturesMod (by tterrag1098)
Xtones (by TehNut)
Better Advancements (by Way2muchnoise)
MrTJPCore (by Mr_TJP)
Soul Shards: The Old Ways (by SgtPunishment)
Mantle (by mDiyo)
Ender IO (by CrazyPants_MC)
Immersive Petroleum (by theFlaxbeard)
Mouse Tweaks (by YaLTeR97)
Roots (by epicsquid319)
Portal Gun (by iChun)
Angel Ring To Bauble (by Portablejim)
Embers (by epicsquid319)
Botania (by Vazkii)
Biomes O' Plenty (by Glitchfiend)
Inventory Tweaks (by Kobata)
MysticalLib (by epicsquid319)
Flat Colored Blocks (by AlgorithmX2)
Colossal Chests (by kroeser)
Thermal Innovation (by TeamCoFH)
CompatLayer (by McJty)
Portality (by Buuz135)
Actually Baubles (by Jacky1356400)
Integrated Dynamics (by kroeser)
Resource Loader (by lumien231)
Initial Inventory (by jaredlll08)
Thermal Expansion (by TeamCoFH)
CodeChicken Lib 1.8.+ (by covers1624)
Better Builder's Wands (by Portablejim)
Industrial Foregoing (by Buuz135)
Ore Excavation Integration (by BloodWorkXGaming)
Cyclic (by Lothrazar)
FTB Library (by FTB)
Mekanism Tools (by aidancbrady)
Refined Storage (by raoulvdberge)
Practical Logistics 2 (by Ollie_Lansdell)
Storage Drawers (by jaquadro)
Minecolonies (by H3lay)
Mekanism Generators (by aidancbrady)
Brandon's Core (by brandon3055)
ShetiPhianCore (by ShetiPhian)
Default World Generator (port) (by EzTerry)
p455w0rd's Library (by TheRealp455w0rd)
Reborn Storage (by modmuss50)
Funky Locomotion (by RWTema)
Ding (by iChun)
OpenComputers (by SangarWasTaken)
The Twilight Forest (by Benimatic)
Tech Reborn (by modmuss50)
Magical Psi (by wiiv)
Industrial Wires (by malte0811)
Tomb Many Graves 2 (by M4thG33k)
ValkyrieLib (by ValkyrieofNight)
Shield Parry (by Drullkus)
Sonar Core (by Ollie_Lansdell)
Storage Drawers Extras (by jaquadro)
Cosmetic Armor Reworked (by ZLainSama)
Reliquary v1.3 (by P3pp3rF1y)
Astral Sorcery (by HellFirePvP)
PlusTiC (by Landmaster_phuong0429)
Refined Storage Addons (by raoulvdberge)
JEI Bees (by bdew)
AbyssalCraft Integration (by Shinoow)
Steve's Carts Reborn (by modmuss50)
Pam's HarvestCraft (by MatrexsVigil)
UniDict (by WanionCane)
Thermal Cultivation (by TeamCoFH)
Doomlike Dungeons (by BlackJar72)
Akashic Tome (by Vazkii)
Bed Patch (by Mordenkainen3141)
BiblioCraft (by JDSinclair)
Environmental Tech (by ValkyrieofNight)
iChunUtil (by iChun)
AE2 Stuff (by bdew)
Forge MultiPart CBE (by covers1624)
Excore (by elix_x)
Cucumber Library (by BlakeBr0)
Exchangers (by Jacky1356400)
WirelessCharger (by ZLainSama)
Common Capabilities (by kroeser)
Inventory Generators (by kjmaster2)
Platforms (by ShetiPhian)
Gendustry (by bdew)
ComputerCraft (by dantwohundred)
JEI Integration (by SnowShock35)
All the Mods: Tweaks (by BloodWorkXGaming)
JAOPCAAdditions (by TheLMiffy1111)
ModTweaker (by jaredlll08)
Integration Foregoing (by Jacky1356400)
Morpheus (by Quetzi)
Terraqueous (by ShetiPhian)
MalisisDoors (by Ordinastie)
NuclearCraft (by TLJGames)
Mekanism (by aidancbrady)
Draconic Evolution (by brandon3055)
SlimyBoyos (by jaredlll08)
WAIM - What am I missing? (by jaredlll08)
YNot (by asiekierka)
RFTools Control (by McJty)
Blood Magic (by WayofTime)
Actually Additions (by Ellpeck)
Toast Control (by Shadows_of_Fire)
Tesla Core Lib (by Face_of_Cat)
McJtyLib (by McJty)
Extra Rails (by shadowfactsmc)
Immersive Engineering (by BluSunrize)
Fence Jumper (by TheRealp455w0rd)
PackMode (by SkySomm)
TOP Addons (by DrManganese)
Plants (by Shadows_of_Fire)
FoamFix for Minecraft (by asiekierka)
AutoRegLib (by Vazkii)
Bookshelf (by Darkhax)
RFTools Power (by McJty)
LibVulpes (by zmaster587)
XNet (by McJty)
Ceramics (by KnightMiner)
JourneyMap (by techbrew)
Pack Crash Info (by BloodWorkXGaming)
Modpack Configuration Checker (by matt_r__)
FTB Utilities: Backups (by LatvianModder)
FTB Utilities (by FTB)
Project Red - Base (by Mr_TJP)
Project Red - Mechanical (by Mr_TJP)
Project Red - Compat (by Mr_TJP)
Project Red - Fabrication (by Mr_TJP)
Project Red - Lighting (by Mr_TJP)
Project Red - World (by Mr_TJP)
Project Red - Integration (by Mr_TJP)
AE2 Wireless Terminal Library (by TheRealp455w0rd)
Wireless Crafting Terminal (by TheRealp455w0rd)
LunatriusCore (by Lunatrius)
[ANGRY PIXEL] The Betweenlands (by MrCompost)
TravellersBackpack-1.12.2-1.0.19.19.jar Thaumic-Energistics-Mod-1.12.2.jar SuperFactoryManager-1.12.2-2.0.19.jar Railcraft-Mod-1.12.2.jar NetherPortalFix_1.12.1-5.3.17.jar MicdoodleCore-1.12.2-4.0.2.211.jar InfinityLib-1.12.2.jar GalacticraftCore-1.12.2-4.0.2.211.jar GalacticraftCore-1.12.2-4.0.2.211.jar fluxnetworks-1.12.2-3.0.19-21.jar AgriCraft-Mod-1.12.2.jar

**Comment by marchermans** [comment]
This is an error in the traveler's backpack. Please refer to them and tell them that they need to pass an actual player instance instead of null when they scan for recipes.
