### ISSUE TITLE
Allow all citizens to wear armor

### ISSUE THREAD

**Issue by WenXin20** [ldtteam/minecolonies#3735]
### Minecolonies version

Version: 0.10.310-Alpha

### Expected behavior

-  All citizens should be allowed to wear armor to provide some protection, especially with the introduction of the new option to allow mob attacks.
- They should also be allowed to use their strongest tool as a weapon to fight.

### Actual behaviour

-  Citizens easily die if a mob decides to Target him/her.

### Steps to reproduce the problem

1.  Enable mob attacks in the config
2.  Wait for night
3.  Citizens easily die...
4. ... Profit

**Comment by OCDCleric** [comment]
Theres a mercenary functuon in townhall. Hire at your own risk.

**Comment by WenXin20** [comment]
Forgot that was added, but citizens are dying to only a single zombie or skeleton.

**Comment by OCDCleric** [comment]
Health boost wont help much... Maybe make a wall around town hall? A single entrance would be easy to defend.

**Comment by WenXin20** [comment]
Well, it's not a really small village anymore, more medium sized, and the one guard I do have also keeps dying.

**Comment by OCDCleric** [comment]
If even the guard is dying then they is just too squishy huh? I need to check on something about this.


Edit. -So I dug around and didnt find much. Seems like in 2013 there was a stat for defence but was removed? Theres also not alot of info on how stats affect citizens.

**Comment by Asherslab** [comment]
all i have to say is that, while we could, allowing citizens to wear armour wouldn't be very realistic, generally speaking armour was left for those who actually needed it, not just anyone

**Comment by WenXin20** [comment]
Considering that there is a config option for all hostile mobs to attack citizens, which I had enabled, wouldn't that mean that citizens do have a need for armor? 
Or at least some way to defend against mob attacks if guards aren't strong enough?

**Comment by someaddons** [comment]
Citizens are supposed to be vulnerable and guards should be used to deal with that, if you got modded mobs which are killing guards easily you can always change the config values for the guards(hp/dmg multiplier). 

Design wise it wouldnt make sense to make normal citizens stronger than guards and them wearing armor doesnt fit either, since they all got their "working" clothes.

**Comment by Asherslab** [comment]
agreed
