### ISSUE TITLE
Can't create cactus planks

### ISSUE THREAD

**Issue by hotluck** [ldtteam/minecolonies#3736]
Version: 0.10.310-ALPHA

When you put cactus in the crafting table, it creates cactus planks.

What it actually does is create cactus juice which is part of the Natura mod.

I'm not sure how to get around this...maybe a config? As I am trying to build a sandstone stonemason, I need to be able to create cactus items for it.

**Comment by OCDCleric** [comment]
Unfortunately Cactus Planks and Cactus juice got nothing to do with this mod. If you want to fix it yourself though try Craft Tweaker or just removing one of the conflicting mods.

**Comment by Justen-N** [comment]
Actually, cactus planks are implemented by MineColonies, OCDCleric.
Amanda,  Crafttweaker would be a good option to fix the issue,

**Comment by hotluck** [comment]
I will look into that, thank you :)

**Comment by Asherslab** [comment]
actually it's implemented on our structurize mod =D 
however recipe conflicts aren't something we can fix. recipe/craft tweaker, or another mod will be your solution to this issue
