### ISSUE TITLE
Cook is not cooking

### ISSUE THREAD

**Issue by hotluck** [ldtteam/minecolonies#3737]
Version:  0.10.310-ALPHA

Recipe is learnt for bread. When there is barley in the chest, the cook should start making bread.

When I first set up this recipe, the cook did start making bread. Now she does nothing. There is fuel in the furnace (not that she needs it to make bread), and there are stacks of barley in the chest. The recipe is definitely still there, and I have tried removing the recipe and re-learning it, but she just stands there and does nothing. She isn't requesting anything either. I have also tried recalling her. The version of bread I am using is using barley from the Natura mod.

**Comment by OCDCleric** [comment]
Are any citizens requesting food to eat? That is to say are there any citizens that have gone to the cook?

**Comment by hotluck** [comment]
No. Is that why she isn't cooking? Is she like the other people, such as the stonemason who don't make anything unless requested? I thought she did it anyone. Maybe every other time I have had a cook, there has just been less other food available for my citizens lol

**Comment by Raycoms** [comment]
No, the cook should request food and fuel all the time and cook.

Am Mo., 22. Juli 2019 um 08:30 Uhr schrieb Amanda <notifications@github.com

**Comment by hotluck** [comment]
Thank you :)

**Comment by hotluck** [comment]
Sorry, I think I misread that before I closed it. Does that mean it is a problem?

**Comment by Raycoms** [comment]
Now I rechecked your issue, the cook doesn't produce bread, the cook only requests fuel and requests "cookable" food and cooks it. No recipe invocations.
