### ISSUE TITLE
Worker Won't Level After Upgrading Hut After Hitting Level Cap Once

### ISSUE THREAD

**Issue by YutaTakano** [ldtteam/minecolonies#3738]
### Minecolonies version 1.12.2 - 0.10.259 - RELEASE

Version: 

### Expected behavior
A worker whose hut is at level 2 will level cap at 8.
As a worker's hut is upgraded, it should be able to gain further experience and resume levelling up.

### Actual behaviour
Ranger had reached level 8 at a guard tower level 2 and had stopped gaining any experience. I thought that upgrading the tower would help, but even with guard tower level 4 it is still on level 8 despite having made many mob kills. Resetting, pausing, fire-rehire, switching to knight and back, and removing items from inventory have had no effect. 

Same thing for builder - capped on level 2, then upgraded to builder hut 5 and still won't get past builder level 8. 

### Steps to reproduce the problem

1. Hire worker at hut level 2.
2. Allow ranger to max out levelling to level 8
3. Upgrade hut...
4. ... Profit

![Capture](https://user-images.githubusercontent.com/24360223/61592810-0ea31380-aba6-11e9-9b79-81aa9db6ad4d.PNG)

**Comment by YutaTakano** [comment]
Confirmed this behavior with other guards as well

**Comment by YutaTakano** [comment]
Noticed the same behavior on one of my builders. Updating title

**Comment by Raycoms** [comment]
Their level cap is defined by their HOME building and not by their work building. Their work building improves the leveling speed.

**Comment by YutaTakano** [comment]
Oh jeez, well I'm glad it wasn't a defect. Please clarify this in the wiki!

**Comment by Raycoms** [comment]
@lunadragnstar could you pr that?

**Comment by lunadragnstar** [comment]
I changed the Wiki and created a PR

**Comment by Asherslab** [comment]
thanks luna
