### ISSUE TITLE
Colonists can't path find on lower half slabs

### ISSUE THREAD

**Issue by Graepix** [ldtteam/minecolonies#3739]
### Minecolonies version

Version: minecolonies-1.12.2-0.10.310-ALPHA

### Expected behavior

-  Colonists should be able to function normally on half slabs placed on the bottom of the block. 
### Actual behaviour

-  When standing on a half slab, colonists do not move or do work at all. When night comes, they stay where they are and don't return to their homes. They also don't attempt to get food when they are hungry.

### Steps to reproduce the problem

1.  Build Medieval Oak Fisherman's hut.
2.  Hire a worker and wait until night fall. 
3.  Watch them stand there, and then push them onto a full block. 
4. Once on a full block, they will return to normal.

**Comment by GanthorPrime** [comment]
'they also don't attempt to get food when they are hungry'. 

Im noticing this part only for guards and it appear has noting to do with slabs

**Comment by OCDCleric** [comment]
Fisherman has always been a pain... Maybe ill play around with a few of them and see what comes out.

**Comment by Raycoms** [comment]
I can't reproduce this, do you have any special half slab?

**Comment by Graepix** [comment]
I don't know if this changes anything, but I forgot to mention that the hut is entirely over water. So both the half slabs and the hut block themselves were over water. But other than that, the slabs were regular half slabs

**Comment by Raycoms** [comment]
Oh, that changes things. I'll look into it again

Am Sa., 27. Juli 2019 um 16:03 Uhr schrieb Bluepikmin64 <
notifications@github.com>:
