### ISSUE TITLE
bakers hut error

### ISSUE THREAD

**Issue by plenet10** [ldtteam/minecolonies#374]
### Minecolonies version

minecolonies-universal-1.10.2-0.6.2097

### Expected behavior

-  Bakers hut being build

### Actual behaviour

- The baker hut isn't working. In the Gui it says com.minecolonies.coremod.gui.workerHuts.bakerhut 0.
the bakers hut is also not getting build. if you click the bakers hut you get this error message in the consel:
http://pastebin.com/XhvtBwSX

### Steps to reproduce the problem

1. place the bakers hut down
2. open the block
3. error....

if you need anything, i will try to help the best of my ablity.

**Comment by Raycoms** [comment]
Yes the Baker hut isn't implemented yet,  only obtainable in creative
therefore

Am Sonntag, 25. Dezember 2016 schrieb plenet10 :

**Comment by plenet10** [comment]
thanks, can you tell me more about the player interaticon error?

**Comment by Raycoms** [comment]
Yeah should be fixed soon,  right click it with an item in the hand for the
meanwhile.

Am Sonntag, 25. Dezember 2016 schrieb plenet10 :

**Comment by plenet10** [comment]
i have got an  another error
http://pastebin.com/fLrhvmbQ

Thanks for the quik responce!

**Comment by Raycoms** [comment]
Yes that's normal behavior.  You're trying to build a building with no
specified structure.
I will add an additional check which should prevent the nullpointer
exception.
But besides that,  please don't try to build anything we don't talk about
on YouTube or in the official wiki.


Am Sonntag, 25. Dezember 2016 schrieb plenet10 :

**Comment by plenet10** [comment]
thank you very much,
1 for making this mod possible
2 for beeing so awsome
