### ISSUE TITLE
[Feature] Schematic size difference message

### ISSUE THREAD

**Issue by Asherslab** [ldtteam/minecolonies#3740]
Currently there's no warning if a schematic is a different size when you upgrade your building. Adding a simple message in chat, or in the gui, that tells the user:
"This next upgrade <schem file name> is a different footprint size than the current one, please alert the schematic creator! You may use this upgrade, however your building may overlap with nearby ones!"

Should at least help us diagnose schematic issues, and for users to understand what's going wrong. It may not always affect our internal schematics, but other author's schematics. (especially when structurize's server is implemented)

**Comment by Raycoms** [comment]
That's easy even, good idea

**Comment by Raycoms** [comment]
Closed in favor of joint issue.
