### ISSUE TITLE
Farmer constantly requesting shovel - chat message only at night

### ISSUE THREAD

**Issue by hotluck** [ldtteam/minecolonies#3741]
Version: Version: 0.10.310-ALPHA

Farmer should be planting seeds and picking as it becomes ready.

My farmer is now level 2 and has 2 working fields. All of a sudden I got a message saying she needed a shovel, so next morning I made her a wooden shovel. Next night, same message, so I made her a stone shovel. Next night, message appeared again. Gave her an iron shovel, so now she has 3 shovels on her but is still asking for a shovel. The weird thing is that when you select her and click on requests, there is no request for a shovel, just more seeds!

**Comment by Raycoms** [comment]
request system issues should be solved
