### ISSUE TITLE
Medieval Spruce Barracks 4th Tower in Wrong location

### ISSUE THREAD

**Issue by Sandriell** [ldtteam/minecolonies#3742]
### Minecolonies version

Version: Versions 1.12.2-0.10.312-ALPHA

### Expected behavior

Having the tower in the right place.

### Actual behavior

The final tower added to the barracks at level 4 is placed in the wrong location. Its in the right place at level 5 though.

### Steps to reproduce the problem

Upgrade the Medieval Spruce Barracks to level 4.

**Comment by Raycoms** [comment]
should be fixed
