### ISSUE TITLE
Citizens could pull directly from warehouse

### ISSUE THREAD

**Issue by kd5crs** [ldtteam/minecolonies#3743]
### Minecolonies version

Version: minecolonies-1.12.2-0.10.310-ALPHA-universal

This is just a suggestion to increase fun, not an issue or bug. 

The current behavior is that deliverymen move goods from huts to the warehouse, and from the warehouse to huts. I think it would be more fun if they only moved from huts to warehouse, and the citizens treated the warehouse like their own inventory. 

There would be a lot less running back to the work hut and waiting on deliverymen. 

Example: Miner goes to dig mine. Planks, fences, ladders, would be pulled directly from the warehouse. The Miner would work until either he gets hungry (in which case he'd go to the restaurant), or the warehouse runs out of a material, or the day ends. Stuff the miner mines would get deposited in the Mine Hut inventory as is currently done, and the Deliveryman would move it from the Mine Hut to the Warehouse as is currently done too. The Smelter, then, would pull the raw ore directly from the Warehouse, put ingots in the Smelter Hut inventory, and then the Deliveryman would move the ingots to the Warehouse, etc.

If this is felt to speed things up too much, it would be neat to slow it back down with relaxation activities, like that citizens break at noon to hang out at the restaurant, or other locations to be added (fountains, parks).

I think this would keep all the fun parts of the village economy, and get rid of the tedious part of Builders and Miners and Crafters only getting resources in drips. It would be the same effect as the Player moving lots of material to the Huts, which is honestly how I spend much of my time due to the Deliverymen being such a bottleneck.

Thanks for consideration.

**Comment by OCDCleric** [comment]
I actually made a suggestion in #3667 for dividing the roles of pickup and delivery for deliverymen so that things would speed up.

But this might work too. In which case:
   1. Delivermen will do pickups only to put in warehouse.
   2. Workers get there own stuff from warehouse.

I prefer the deliverymen but theres still a few issues that are being waited on so who knows.

**Comment by Raycoms** [comment]
No, it's pretty much against out idea of the mod. (Specialization of workers).
But, we are working on improving the deliveryman to make him more efficient.
