### ISSUE TITLE
Gun Turret Power Drainage

### ISSUE THREAD

**Issue by hotluck** [ldtteam/minecolonies#3744]
Version: 0.10.310-ALPHA

When the gun turret is connected with power, the power is drained when it is firing.

I don't know whether this is a bug or not, but I am in the process of setting up powered lanterns and some gun turrets around my colony. I have 2 windmills (covered in tough fabric) and 3 waterwheels (together) which I am getting my power from. I have an LV capacitor attached to each and then insulated LV wires connected to the lanterns and gun turrets. If I have the gun turrets switched on, they are constantly draining power until there is none left so when it comes to night time, they can't fire anything. Am I doing something wrong/missing something or is this a bug because it surely shouldn't drain power until it is actually being fired?

**Comment by Asherslab** [comment]
wrong mod mate

**Comment by hotluck** [comment]
My apologies. I thought I was in the Immersive Engineering area...so many github pages to select lol
