### ISSUE TITLE
Raids spamming the chat.

### ISSUE THREAD

**Issue by alsi0205** [ldtteam/minecolonies#3746]
Minecolonies version
version 1.12.2-0.9.104-alpha
Expected behavior
Barbarians will appear and colonists will fight or be killed by them.
Actual behaviour
I get the alert of the upcoming attack (in red) followed by maaany repetitions of "Only 2 barbarians left! Only 1 barbarians left! You successfully defended your colony against the Barbarian intruders!" Over and over again. 2, then 1, then success, then 2 again, then 1, etc.
Steps to reproduce the problem
Get red alert
See no barbarians, but recieve repeated messages about decreasing numbers if barbarians
Have chat spammed by these messages
Profit?

**Comment by Asherslab** [comment]
it's due to the raiders being in unloaded chunks. when the chunk loads/unloads it causes this. however we do need to fix this either way

**Comment by Rosomah** [comment]
Same for me and when I find the barbarians and kill them, I get the "You successfully defended your colony against the Barbarian intruders!" for every one I kill. The barracks also don't show the current barbarian position or the last barbarian spawn.
