### ISSUE TITLE
[bug]Wrong minPercentageToCraft formula

### ISSUE THREAD

**Issue by averman** [ldtteam/minecolonies#3748]
https://github.com/ldtteam/minecolonies/blob/d6bedf0077ec4feb9f685aa85bc614bc6ba9b23b/src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingSawmill.java#L122

instead of `blocks/amountOfValidBlocks`
it should be
`amountOfValidBlocks/blocks`

my test case: I create a recipe of 1 wood + 1 dirt that yield stairs
according to this recipe
`blocks = 2;
amountOfValidBlocks = 1`

with the original formula of `blocks/amountOfValidBlocks` the percentage will be 2
it supposed to be 0.5

**Comment by Raycoms** [comment]
True, good catch, fix merged
