### ISSUE TITLE
Exception with Dynamic Trees

### ISSUE THREAD

**Issue by WenXin20** [ldtteam/minecolonies#3749]
### Minecolonies version

Version: 0.10.313-Beta

### Dynamic Trees versions

DT: v0.9.5
DT BOP: v1.4.1e
DT Traverse: v1.5

### Expected behavior

-  The Lumberjack should be working fine with dynamic trees, cutting them down and replanting.

### Actual behavior

- The Lumberjack will occasionally run into the error reported below, which causes him/her to freeze and have to be restarted. I don't know what causes it.
[Error Log](https://gist.github.com/WenXin20/c87fe12cdcdc46a63a15bce2eeee16bd)

### Steps to reproduce the problem

1. Hire a Lumberjack
2. Plant some dynamic saplings
4. ... Profit?

**Comment by Raycoms** [comment]
Should be fixed.
