### ISSUE TITLE
permission's

### ISSUE THREAD

**Issue by plenet10** [ldtteam/minecolonies#375]
### Minecolonies version

minecolonies-universal-1.10.2-0.6.2097

### Expected behavior

- opening the Gui

### Actual behaviour

- Gives a error message:
http://pastebin.com/y7CPJq45

### Steps to reproduce the problem

1. place
2. open
3. error

**Comment by Raycoms** [comment]
Same problem as in #292,  fixed it already just has to be uploaded

Am Sonntag, 25. Dezember 2016 schrieb plenet10 :
