### ISSUE TITLE
Misplaced colony chunks and server "can't keep up, overloaded" after minecolonies-1.12.2-0.10.313-BETA actualization

### ISSUE THREAD

**Issue by RioPlatense** [ldtteam/minecolonies#3752]
### Minecolonies version

Version: minecolonies-1.12.2-0.10.313-BETA

### Expected behavior
Don't misplace chunks

### Actual behaviour
Server says: "Can't keep up!" and chunks gets misplaced
I play alone in my server, I've been playing a lot of time in a world, creating a big colony with 49 colonists. Everything was going good, but when I actualized to minecolonies-1.12.2-0.10.313-BETA, the server started to work badly and to consume a lot of RAM, (I have 8 GB and 64 bits), after that a lot of chunks got misplaced. I tried using the previous version (0.10.0312), but the problem persist. Now the server has crashed.
Pictures:
![bug](https://user-images.githubusercontent.com/46036774/62000164-db311f00-b0a6-11e9-9376-a581d0af7452.png)
Misplaced chunks
![2019-07-26_20 24 07](https://user-images.githubusercontent.com/46036774/62000175-fbf97480-b0a6-11e9-9c8d-c8109f8473c4.png)
![2019-07-27_19 11 45](https://user-images.githubusercontent.com/46036774/62000178-09aefa00-b0a7-11e9-82f0-5266f9a2b550.png)
Crash report:
[crash-2019-07-27_19.26.29-server.txt](https://github.com/ldtteam/minecolonies/files/3438677/crash-2019-07-27_19.26.29-server.txt)

### Steps to reproduce the problem

To reproduce it you should have my server folder and just try it
I have others mod, but in my opinion they are working fine
Craftable hourse armour
Currency mod
IndustrialCraft
Millenaire mod (millenaire villages are far and inactive)

**Comment by Raycoms** [comment]
Wow, that misplaced chunk issue seems severe. And we don't do anything with
the chunks which could cause this. Really strange. The crash log, indicates
that your builder is working in an unloaded chunk.

Am Sa., 27. Juli 2019 um 19:48 Uhr schrieb RioPlatense <
notifications@github.com>:

**Comment by Raycoms** [comment]
Which should be fixed in the newest beta, but not in the older version you
switched back to.

Am Sa., 27. Juli 2019 um 20:12 Uhr schrieb Ray Neiheiser <
ray.neiheiser@gmail.com>:

**Comment by RioPlatense** [comment]
Thank for answer!, so, to sum up, I wait for the new update and this won't happen again?, I can fix those uggly chunks with McEdit, there's no problem with that

**Comment by Raycoms** [comment]
Can you send me your server folder so that I can try it out?

Am Sa., 27. Juli 2019 um 20:17 Uhr schrieb RioPlatense <
notifications@github.com>:

**Comment by RioPlatense** [comment]
Of course!, I'm uploading it. It weighs 311 MB

**Comment by Raycoms** [comment]
Ouch, anyway to reduce that?

Am Sa., 27. Juli 2019 um 20:32 Uhr schrieb RioPlatense <
notifications@github.com>:

**Comment by RioPlatense** [comment]
It's impossible, because the world weighs much
Link: https://www.mediafire.com/file/h6cird33kr1bawr/RioPlatense%27s_server.zip/file

**Comment by RioPlatense** [comment]
I forgot to say that my character was reseted when that happened, I mean I lost all my inventory and experience

**Comment by GanthorPrime** [comment]
hope you have a backup somewhere.  Its always a good idea to zip a backup before an upgrade.

I also play in a server and always got the server overloaded message every 10 secs. i read somewere that is related to ticks taking more than 50ms.  You can use /debug start, /debug stop to generate a file that gives you a hint of what is taking more to process.

**Comment by RioPlatense** [comment]
I undersand. My computer is very strong, so it's very strange to get overloaded. I have a very old backup, I can fix chunks with that, but I need a way to don't continue misplacing chunks in my map

**Comment by RioPlatense** [comment]
> hope you have a backup somewhere. Its always a good idea to zip a backup before an upgrade.
> 
> I also play in a server and always got the server overloaded message every 10 secs. i read somewere that is related to ticks taking more than 50ms. You can use /debug start, /debug stop to generate a file that gives you a hint of what is taking more to process.

[profile-results-2019-08-03_22.24.25.txt](https://github.com/ldtteam/minecolonies/files/3464484/profile-results-2019-08-03_22.24.25.txt)
It's here, but I don't understand what says that file

**Comment by RioPlatense** [comment]
Any solution?, the problem still happening

**Comment by Raycoms** [comment]
Sorry, I'm in the middle of something atm, and will only be able to analyze
this in a few days.

Am Sa., 10. Aug. 2019 um 20:53 Uhr schrieb RioPlatense <
notifications@github.com>:

**Comment by Raycoms** [comment]
Never was able to tie this to our mod or reproduce this. No one else reported similar either. So i guess something else was causing this
