### ISSUE TITLE
In dynamic claim mode, the lumberjack doesn't cut trees behind the border limit

### ISSUE THREAD

**Issue by lebanni** [ldtteam/minecolonies#3758]
### Minecolonies version
Version:  minecolonies-1.12.2-0.10.324-ALPHA-universal.jar
DynamicTrees-1.12.2-0.9.5.jar

### Expected behavior
Lumberjack cut trees all around his building

### Actual behaviour
In dynamic claim mode, the lumberjack doesn't cut trees behind the border limit.

**Comment by marchermans** [comment]
That is because that area does not belong to your colony.
Build up your colony and the area will increase, additionally we might be willing to look into ways of increasing the influence of your colony in the surrounding areas.

**Comment by lebanni** [comment]
In normal mode, they cross the limits.
