### ISSUE TITLE
Bugged Guards

### ISSUE THREAD

**Issue by Falcon7617** [ldtteam/minecolonies#376]
### Minecolonies version

Current

### Expected behavior

- Guards should patrol the areas designated by the guard - scepter

### Actual behaviour

- Guard will patrol some areas close by, but other close by areas seem to be "off" limits. The hut block says they are to patrol it, but pathfinding might be saying it is impossible to actually go there

![2016-12-25_20 08 00](https://cloud.githubusercontent.com/assets/11009872/21475334/2e6ecd1c-cadf-11e6-86c5-58fe5814c9d8.png)
This lower section, the guard will patrol normally.

![2016-12-25_20 08 09](https://cloud.githubusercontent.com/assets/11009872/21475335/2f02986c-cadf-11e6-8b98-4590a4495b46.png)
I can get him to follow the path, but he will not travel into the field

![2016-12-25_20 08 13](https://cloud.githubusercontent.com/assets/11009872/21475333/2e547048-cadf-11e6-882d-4a8de2f13f17.png)

More of the bottom to show more architecture

![2016-12-25_20 08 20](https://cloud.githubusercontent.com/assets/11009872/21475336/2f0e0508-cadf-11e6-8eb8-1ecd04a6f4d9.png)

He will patrol the path here as well sometimes . . . but refuses to go into the field up here

**Comment by Raycoms** [comment]
Depending on the location and depending on when you set it he won't pass or
he will pass eventually only.
Pathfinding is very complex and we can't tell if it can't path to a
specific location.


Am Montag, 26. Dezember 2016 schrieb Falcon7617 :

**Comment by Raycoms** [comment]
Ah and I almost forgot. The guard has a max range of 40*guardtower level.
