### ISSUE TITLE
Scan Tool Missing from Guidebook

### ISSUE THREAD

**Issue by WenXin20** [ldtteam/minecolonies#3760]
### Minecolonies version

Version: 0.10.324-Alpha

### Guidebook version

Version: 2.9.2

### Expected behavior

-  The guidebook should be displaying the item icon for the Scan Tool.

### Actual behaviour

- The guidebook only displays the recipe, but not the Scan Tool icon.

![2019-07-30_20 32 53](https://user-images.githubusercontent.com/12000593/62177680-70345200-b30b-11e9-9cd9-60c3460b0503.png)

### Steps to reproduce the problem

1.  Open Guidebook
2.  Flip to page 97 and 107
4. ... Profit

**Comment by Nightenom** [comment]
the old guidebook, which is outdated as hell, will be replaced one day. there should be note on the first page about visiting wiki for live version
