### ISSUE TITLE
Client crash on right click on Postbox

### ISSUE THREAD

**Issue by K1ngAdi** [ldtteam/minecolonies#3761]
Version: minecolonies-1.12.2-0.10.334-ALPHA

Actual and expected behavior should be clear from title.
One side note: if I try to re-join the server thanks to vanilla fix my game does nothing besides 'Logging in'.  

crash report: [https://paste.dimdev.org/uwobuzupuy.mccrash]()

### Steps to reproduce the problem
simple right click works

**Comment by OCDCleric** [comment]
Were you holding something in your hand when right-clicking?

**Comment by K1ngAdi** [comment]
makes no difference

**Comment by marchermans** [comment]
That link is broken

**Comment by LoopeeDK** [comment]
I have the exact same error if i plant it the second i try to open the thing up i crash, just simply placed it on a hopper and then tried to rightclick to open ui and poof

**Comment by marchermans** [comment]
Yeah but I can not reproduce it, without a crashlog.

**Comment by LoopeeDK** [comment]
Ok here u go @OrionDevelopment 
https://pastebin.com/WCYtmGtE

**Comment by marchermans** [comment]
Oke funny you seem to have missing data in your view.
Can you break the block and place it somewhere else and try again?

**Comment by Raycoms** [comment]
fixed
