### ISSUE TITLE
Knight/Ranger Attacks One Spot Repeatedly

### ISSUE THREAD

**Issue by WenXin20** [ldtteam/minecolonies#3762]
### Minecolonies version

Version: 0.10.334-Alpha

### Expected behavior

- Knights and Rangers should patrol normally.
- Maybe a debug log to show what the knight/ranger is attacking.

### Actual behavior

-  The Knight/Ranger will repeatedly try to attack the same spot, but waste sword/bow durability.
- The knight will repeatedly swing a sword, while the ranger will endlessly shoot arrows.
- The Knight always goes to the coordinates `-1396, 67, -1017` to try to attack something.
- As seen in the image below, the knight is just standing in that one spot and swinging her sword until it breaks.
- If switched to a ranger, she endlessly shoots arrows at that general area.
- There are no other entities that I can find, even when looking around using the glowing effect or spectator.
- Firing and rehiring doesn't fix it.
- Currently, the tower is set to Knight manually, while patrol and retreat is set to automatic.
- The tower is level 2 and the worker level is 1.

![2019-07-31_23 47 02](https://user-images.githubusercontent.com/12000593/62266514-35571a80-b3ee-11e9-8601-dac7a3027ce8.png)

### Steps to reproduce the problem

Not entirely sure how to reproduce, but...
1.  Hire a guard
2.  Set to patrol?
4. ... Profit

**Comment by Raycoms** [comment]
Didn't see this occurring in a while anymore since AI improvements for guards.
