### ISSUE TITLE
Miner won't use iron pickaxe or above

### ISSUE THREAD

**Issue by pinkpenguin464** [ldtteam/minecolonies#3763]
### Minecolonies version

Version:  1.12.2-0.10.259-RELEASE

### Expected behavior

-  Miner using iron pickaxes and above

### Actual behaviour

- My miner wants a pickaxe, but only stone and below

### Steps to reproduce the problem

1. Level up to whatever level is required for iron pick
2. Go into requests
3. They only want stone or below
4. I don't know
https://user-images.githubusercontent.com/53586916/62336050-18752280-b494-11e9-94a5-30c211fe984a.png 
https://user-images.githubusercontent.com/53586916/62336056-1c08a980-b494-11e9-88f1-05fbf951086d.png

**Comment by Talyda** [comment]
Tool level depends on building level - what level is your miner's hut?

**Comment by OCDCleric** [comment]
I think thats a lvl 1 or 2 in the background. Lvl.3 miner required for iron tools.

**Comment by marchermans** [comment]
Yep, please refer to the wiki or discord. Not an error Closing.
