### ISSUE TITLE
You have no permission in the colony! (I know why)

### ISSUE THREAD

**Issue by fdczck** [ldtteam/minecolonies#3768]
### Minecolonies version

Version: 1.12.2-0.10.259-RELEASE

### Expected behavior

- You have permission in the colony!

### Actual behaviour

- You lost permission in the colony!

### Steps to reproduce the problem

1. enter the nether (or other dimension)
2. leave the game
3.  enter the game 
4.  You have no permission in the colony!

**Comment by Raycoms** [comment]
Can you try the newest alpha please?

>

**Comment by fdczck** [comment]
sorry and thank you .
