### ISSUE TITLE
Tried to read NBT tag that was too big crashes

### ISSUE THREAD

**Issue by gleybergood** [ldtteam/minecolonies#3769]
### Minecolonies version
 1.12.2-0.10.313 beta

Version: 

### Expected behavior

- 

### Actual behaviour

- Keep getting crash logs for minecolonies when simply walking around my town. Nothing in perticular causes it, just keeps spamming my screen. 
![2019-08-02_22 34 59](https://user-images.githubusercontent.com/53272967/62406199-d4f2e500-b575-11e9-94ca-c4a6b8f86e92.png)

https://paste.dimdev.org/hefedayufa.mccrash

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit

**Comment by Nightenom** [comment]
Update to the latest alpha and do request system reset via commands. Issues was fixed like several months ago but for unknown reason it still persists in old saves.

**Comment by Nightenom** [comment]
Also follow #3606 if problem persists
