### ISSUE TITLE
permission commande not op

### ISSUE THREAD

**Issue by demon57730** [ldtteam/minecolonies#3774]
forge-1.12.2-14.23.5.2838-universal.jar

minecolonies-1.12.2-0.10.259-RELEASE-universal.jar
spongeforge-1.12.2-2825-7.1.6.jar
LuckPerms-Sponge-4.4.27.jar

all permission on luckperm works except those of minecolonies he says i have not permission even if i just do / mc he put i dont have permission i even put the perm com.minecolonies.coremod.* & com .minecolonies.* & perm *
he continues to say I do not have permission

**Comment by lunadragnstar** [comment]
Do you have OP?

**Comment by demon57730** [comment]
if i get op the command works but i want to put the permission of the rtp to no op

**Comment by marchermans** [comment]
This is not Minecolonies related. Closing, please report this to the author of LuckPerms.

**Comment by demon57730** [comment]
the concern does not come from luckperms but from your mod which does not take the permission because it requires to be op on the server

**Comment by marchermans** [comment]
That is correct, Minecolonies is a Forge mod, and LuckPerms a Sponge Plugin, we just register vanilla commands to Forge, since that is the only thing we can do, as such there is nothing we can do, and it is a problem on LuckPerms side if it is not able to processes modded commands properly.

**Comment by demon57730** [comment]
precisely I give myself permission * which gives all those perms even those of mod who have a permission they are accept except you because you have put in the mod that you have to be op on the server obligatorily and therefore you have to block the permissions

**Comment by demon57730** [comment]
small precision in the wiki give you control that and for the simple player so not op but in the derneir same version it is command it asks op in time we had the command mc home for those who were not op except that all orders order to be op 
even without dreaming the commands that are for the simple player he asks to be op

( /mc citizens list <colony: colony id> [page: page number]

Permission node: com.minecolonies.coremod.ListCitizens
Default permission level: ALL) forge server and mod without sponge he asks to be op while these well written level all

**Comment by marchermans** [comment]
I really have a hard time reading your english, and I am not understanding what your issue is.
Either tells us what your native tongue is and write in that, in the hope that I can read it, have it translated by somebody else, or wait for somebody else that can read your problem

**Comment by demon57730** [comment]
french
j’explique ,j'ai essayé avec un serveur sans spongeforge et j'avais oublié de dire que dans votre wiki vous avez mis des commandes pour tous les joueurs sans être opérateur mais ces commandes son aussi bloquer, il demande d’être opérateur du serveur

**Comment by marchermans** [comment]
Ooh interesting, I can read that, so keep it French :D

So I hope you can read my english. I checked our sourcecode, most of our commands depend on the configuration value you set in the config. All others are just requested as OP to Forge, and I have no idea how that translates into SpongeForge, can you try without Sponge and set yourself as OP. Cause then you should be able to execute the commands just fine. At least I am able to.

**Comment by demon57730** [comment]
ce que j'ai expliqué 
le dossier config je l'ai pas modifié mais sans spongeforge les commande pour tous les joueurs fonctionne que si on ait opérateur sur le serveur

exemple 
( /mc citizens list <colony: colony id> [page: page number]

Permission node: com.minecolonies.coremod.ListCitizens
Default permission level: ALL)

il fonctionne que si ont est opérateur meme le /mc fonctionne que si on est opérateur, donc ceux qui ne sont pas ne peux pas executer les commandes qui son normalement destiné a eux

**Comment by pyscho974** [comment]
does minecolonies  use permission node like vanilla does with minecraft.command.gamemode if so what is it using for 1.12.2 alpha 841.   ive had this work before in past btw.. just cant recall the permission line to use.  pretty sure id seen it in the past with ftbu permissions settings they seem to reflect the vanilla op mechanics. just wish i remembered what pack it was in that id found it before.

**Comment by Talyda** [comment]
1.12.2 isn't supported any more

**Comment by pyscho974** [comment]
isnt supported is not really an answer... not asking to change anything.. just searching for something that is already there. shame no one remembers how they wrote the code to answer a simple question as 3 words for a reply. not to mention.. not everyone wants to go to 1.16 since it offers nothing ive yet to see worth it with so many mods not moving forward and not much in the way of good mods coming out.

**Comment by ravenbuilder934** [comment]
Changing anything = updating 1.12
Answering your question = supporting 1.12
We do neither. And there are in fact *many* benefits to 1.16, including (as you've already seen) support just about anywhere.

**Comment by pyscho974** [comment]
then maybe you just shouldnt do anything even make updated versions.  what ever im done here.. waste of my time hope your mod dies out lazy people.
