### ISSUE TITLE
Builder often does not use quick way to reach destination

### ISSUE THREAD

**Issue by ErdbeerbaerLP** [ldtteam/minecolonies#3779]
### Minecolonies version

Version: 1.12.2-0.10.341-ALPHA

### Expected behavior

The builder would walk the fastest way to its destination along some of the waypoints

### Actual behaviour

The builder attempts to walk along almost all waypoints i have placed

(Green line: Fastest way, Red line: Path the builder walked along)
![image](https://user-images.githubusercontent.com/27149563/62716133-ff272580-ba01-11e9-8b48-0e8d53186358.png)

### Steps to reproduce the problem

1.  Place down some waypoints
2.  Give the builder something to build
3.  See the builder walking a very long way to its destination
4. ... Profit

**Comment by Raycoms** [comment]
Can you send me this world?

Am Do., 8. Aug. 2019 um 12:33 Uhr schrieb ErdbeerbaerLP <
notifications@github.com>:

**Comment by ErdbeerbaerLP** [comment]
It is an server. https://www.technicpack.net/modpack/uwm-space-exploration.1188932

**Comment by Raycoms** [comment]
I'd need a similar setup to be able to reproduce and debug this.

>

**Comment by ErdbeerbaerLP** [comment]
Well, i could try sending you the an part of this world (and the coordinates) but not sure if it will completely work (because of the missing blocks/items)

**Comment by Raycoms** [comment]
That's usually not problem (the blocks items)

Am Do., 8. Aug. 2019 um 12:48 Uhr schrieb ErdbeerbaerLP <
notifications@github.com>:

**Comment by ErdbeerbaerLP** [comment]
Coordinates: 256 80 -250
World: http://erdbeerbaerapi.tk/world.zip
You could try to upgrade the miner, that was the example i made. It might walk a different way everytime

**Comment by Raycoms** [comment]
I think I got a fix for it, thanks for the world, that was very helpful. Will send the jar in a few minutes to test.

**Comment by Raycoms** [comment]
https://teamcity.minecolonies.com/guestAuth/repository/download/LetSDevTogether_Minecolonies_Branches_Build/29669:id/build/libs/minecolonies-1.12.2-0.10.1085-PERSONAL-universal.jar

**Comment by ErdbeerbaerLP** [comment]
Currently uploading to modpack and server to test it

**Comment by ErdbeerbaerLP** [comment]
Seems to be better/fixed now. He does not wander around too much anymore

**Comment by ErdbeerbaerLP** [comment]
Oh, he started the next building and he went to the warehouse, turned around and walked to the other side of the colony just to walk back to the minig area

**Comment by Raycoms** [comment]
Which build?

Am Do., 8. Aug. 2019 um 14:46 Uhr schrieb ErdbeerbaerLP <
notifications@github.com>:

**Comment by ErdbeerbaerLP** [comment]
I started to upgrade the blacksmith. (or do you mean the version with build? i used that one you sent mt)

**Comment by ErdbeerbaerLP** [comment]
Oh, he was building it  from the inside of the warehouse, so that is a different thing. Looks like everything else works

**Comment by Raycoms** [comment]
ah yeah, that is the position to build he calculated, but besides that is
there another problem?


Am Do., 8. Aug. 2019 um 14:51 Uhr schrieb ErdbeerbaerLP <
notifications@github.com>:

**Comment by ErdbeerbaerLP** [comment]
Just tested another building, pathfinding is fixed. Did not find any problem for now. (Close this now?)

**Comment by Raycoms** [comment]
sounds good

Am Do., 8. Aug. 2019 um 14:56 Uhr schrieb ErdbeerbaerLP <
notifications@github.com>:
