### ISSUE TITLE
farmer bug

### ISSUE THREAD

**Issue by demon57730** [ldtteam/minecolonies#3783]
forge-1.12.2-14.23.5.2838-universal.jar
minecolonies-1.12.2-0.10.343-ALPHA-universal.jar

au bout d'un moment le fermier se bloque dans le champ et il ne bouge plus, il faut le faire respawn a son atelier pour qu'il se remette à travailler

<img width="960" alt="farmer" src="https://user-images.githubusercontent.com/5184008/62830205-fd7c7e00-bc0a-11e9-9c60-55430a9be933.png">

**Comment by demon57730** [comment]
j'ai changer le texte du probleme car il avais un bug que j'avais oublier de dire

**Comment by Raycoms** [comment]
Sorry, I don't speak french, what's the issue?

**Comment by Kvykv** [comment]
At some point the farmer is getting stuck in the field and doesn't move anymore. One has to respawn him to its farmer block (I guess he meant recall) to make him go back to work

**Comment by Raycoms** [comment]
The citizens have issues with slabs and similar above water. (there are other issues for this) which cause this.
