### ISSUE TITLE
Children not growing up

### ISSUE THREAD

**Issue by DarkRuin** [ldtteam/minecolonies#3785]
### Minecolonies version

Version: 1.12.2-0.10.202 (All The Mods 3)

### Expected behavior

- 
Children should grow up after x amount of time
### Actual behaviour

- 
Children are not growing up. I've been playing for about 20 hours over a couple of days with a child in my village.

**Comment by Talyda** [comment]
You're playing a REALLY old version of the mod - try updating it =)

**Comment by DarkRuin** [comment]
I’m playing on a mod pack (all the mods 3) and that’s the latest version of the pack. Can I manually update the individual mod separately?

**Comment by Talyda** [comment]
As long as you are either in single player, or on a server where admin will update for everyone you can =) Try for one of the latest alphas (they update very regularly)

**Comment by Asherslab** [comment]
This is a bug present only in old versions of the mod. closing.
