### ISSUE TITLE
restaurant

### ISSUE THREAD

**Issue by demon57730** [ldtteam/minecolonies#3786]
forge-1.12.2-14.23.5.2838-universal.jar
minecolonies-1.12.2-0.10.341-ALPHA-universal.jar

voila, le restaurant reçoit les aliments crus, il les cuit puis le livreur vient prend les aliments cuit et les ramener au stockage sauf que après les citoyens vont au restaurant, car ils ont faim mais ils ont rien à manger car tous les aliments cuit sont au stockage et pour finir un moment le livreur a aussi faim ce qui fait que tous les citoyens sont bloqués au restaurant sans nourriture, car la nourriture cuite reste au stockage

---------------------------------------------------
Google Translated --- @Asherslab 

here it is, the restaurant receives the raw food, it cooks it and then the delivery man comes takes the cooked food and bring it back to storage except that after the citizens go to the restaurant, because they are hungry but they have nothing to eat because all the cooked food is in storage and to end a moment the driver is also hungry so that all citizens are stranded in the restaurant without food, because the cooked food remains in storage

**Comment by Aelhan** [comment]
Ça m'est arrivé aussi, essaie de leur donner à tous un peu à manger manuellement puis une fois qu'ils sont rassasiés vas à l'hôtel de ville et "rappeler tous les citoyens " ça devrait corriger, au moins temporairement. 

That happened to me, try to manually give all of them some food, and once they aren't anymore hungry, go to town hall and "recall all citizens". That should fix your issue, at least for a while

**Comment by gleybergood** [comment]
I second this issue, it happens at least once a day for me

**Comment by demon57730** [comment]
probleme résolu pour ma part j'ai pris la dernier version(alpha) et j'ai annuler la requête du restaurant et maintenant il as plein d'aliment dans son coffre donc aucun citoyen meurt de faim
