### ISSUE TITLE
Removing Hut block leaving hole behind in dynamic claims

### ISSUE THREAD

**Issue by spacewolfcub** [ldtteam/minecolonies#3787]
Reported by @Kriiks#9778 on Discord.

### Minecolonies version
minecolonies 342 alpha with dynamic colony size enabled

### Expected behavior
Hut block is placed down with Build Tool inside an already claimed chunk, 
player decides to move Hut before clicking Build and so breaks Hut block, 
the chunk it was in remains claimed because it did not depend on that Hut block that was removed.

### Actual behaviour
Hut block is placed down with Build Tool inside an already claimed chunk, 
player decides to move Hut before clicking Build and so breaks Hut block, 
the chunk it was in **becomes unclaimed**, leaving a hole in the middle of other claim areas.

It can only be fixed by using a claim command, which might not be available on many servers. And this should not be breaking anyway. 

![image](https://user-images.githubusercontent.com/11811417/62908212-b20dc100-bd2b-11e9-9cfa-e4611f2450a8.png)

### Steps to reproduce the problem
1. Place Hut block down with Build Tool inside an already claimed chunk, do not order it built
2. Wait 5 minutes, or 1 hour (random lengths of time) 
3. Break the Hut block 
4. Look at claim boundaries with built tool, see hole left behind

**Comment by Raycoms** [comment]
@spacewolfcub are you able to reproduce this in a single player world easily?

**Comment by Raycoms** [comment]
fixed
