### ISSUE TITLE
Reposition does not destroy original building

### ISSUE THREAD

**Issue by ErdbeerbaerLP** [ldtteam/minecolonies#3789]
### Minecolonies version

Version: 1.12.2-0.10.1085-PERSONAL

### Expected behavior

- 
The builder would completely remove the old building and then build the new one
### Actual behaviour

- 
The builder simply looks at the old one and then starts building the new one

### Steps to reproduce the problem

1.  Build a building
2.  Start repositioning
3.  Builder does not remove the old building
4. ... Profit

**Comment by Raycoms** [comment]
Closed in favor of joint issue.
