### ISSUE TITLE
Supply Ship Underwater made of WATER.

### ISSUE THREAD

**Issue by Wissi** [ldtteam/minecolonies#379]
Minecolonies version 1.10.2 on Official Server
When placing the Supply ship underwater it spawns a supply ship made of WATER and the chest as well.
![underwater](https://cloud.githubusercontent.com/assets/23312242/21511168/a778fdac-cc62-11e6-9abe-d0ded3042ffb.png)
![underwater_1](https://cloud.githubusercontent.com/assets/23312242/21511171/afafa7f0-cc62-11e6-8e9e-25e1e811aed2.png)

**Comment by Raycoms** [comment]
I can't reproduce this.
It seems like while placing this there has been a lagspike on the server which deleted the placed blocks directly again.
Which resulted in the image you sent us.

Would be nice if someone would be able to reproduce this.
