### ISSUE TITLE
How/where to install the 4.6v mod?

### ISSUE THREAD

**Issue by SenseiGrove** [ldtteam/minecolonies#3790]
I've used past versions of minecolony and the installation was a breeze. Now it seems the installation process has changed and i'm a bit lost on where to place everything in my .minecraft folder in AppData... for example where do i place the items in the Override folder (scripts, resources, config and servers.dat)?

Noob here, be kind, lol.

**Comment by Asherslab** [comment]
nothing has changed about minecolonies installation process at all.

**Comment by Raycoms** [comment]
Compared to very very very past version it has.

https://wiki.minecolonies.com/

Here we got a guide on how to solve it.
