### ISSUE TITLE
Stonemason not working

### ISSUE THREAD

**Issue by Paril** [ldtteam/minecolonies#3792]
Latest version. Stonemason is in START_WORKING stage, but does not move from his bed after waking up. Miner requested slabs, but he never got the memo/never requested cobble to fulfill it. Might be a (newer) dupe of https://github.com/ldtteam/minecolonies/issues/3645 ?

**Comment by Rosomah** [comment]
I have an issue with the miller. The builder requested spruce stairs and the request system showed that the request will be fulfilled by the crafter, but he needed some more spruce planks. I was hoping that the miller could request the rawest material which would be the spruce wood, making it into planks and then into stairs if planks were unavailable at first. I also noticed that until the miller doesn't have the necessary amount of wood to craft all the stairs, he doesn't start working.

**Comment by Asherslab** [comment]
@Rosomah make a seperate issue please.

**Comment by Raycoms** [comment]
fixed
