### ISSUE TITLE
Miner requests only 3 oak wood planks for support beams

### ISSUE THREAD

**Issue by Rosomah** [ldtteam/minecolonies#3793]
### Minecolonies version
minecolonies-1.12.2-0.10.341-ALPHA-universal

Version: 

### Expected behavior
The miner should ask for a full stack of planks, so he doesn't need to go to the top for every section of the tunnel he makes.

### Actual behaviour
Bringing only 3 planks with him means he has to go up and down everytime, which means he's climbing ladders more than mining

**Comment by Asherslab** [comment]
not a bug, he can't predict things like that

**Comment by Raycoms** [comment]
We can have him set the total amount to 64 that's fixable

**Comment by Rosomah** [comment]
Yeah I didn't think of it as a bug, but as a possible improvement.
