### ISSUE TITLE
Weird hiccup when flying in Creative?

### ISSUE THREAD

**Issue by darthvader45** [ldtteam/minecolonies#3802]
### Minecolonies version

Version: 1.12.2-0.10.259-RELEASE

### Expected behavior
Chunks load and the player is able to change gamemodes reliably (i.e. things respond normally)

### Actual behaviour
Chunks simply won't load, trying to change gamemode results in no response (much like (internal) server lag or something)

### Steps to reproduce the problem

1. Setup and load a Minecraft modded instance with this mod
2. Create a world and fly around in creative
3. Problem happens
4. ... Profit

**Comment by Talyda** [comment]
The mod is currently at version 1.12.2-0.10.346-ALPHA so you are nearly 100 version out of date  - try updating it then seeing if it still happens!

**Comment by darthvader45** [comment]
The heck?  I was at the latest version uploaded on CurseForge.

Edit:  Apparently the latest release, I'll test the alpha and see what happens.

Edit2:  Seems the same problem happens.  Not sure why it mentions Quark, Primal Core, Astral Sorcery, LLibrary and Ice & Fire.  This time, it said "Can't keep up" before it started, so I'm assuming something's up with the server-side chunk loading stuff.  Think it might be Ancient Warfare 2, as apparently their mod can be a bit hacky with the worldgen stuff.  Check out my issue over on their issue tracker: https://github.com/P3pp3rF1y/AncientWarfare2/issues/1011

**Comment by Raycoms** [comment]
I'm pushing a fix which improves memory usage a bit, this might improve this too.

**Comment by darthvader45** [comment]
Thanks, Ray.  Hopefully I don't have to deal with this anymore.
