### ISSUE TITLE
[1.14.4] Game crashed when clicking on Infrastructure button in Builder's Tool UI

### ISSUE THREAD

**Issue by kedamono** [ldtteam/minecolonies#3804]
### Minecolonies version

Version: minecolonies-0.10.1192-PERSONAL-universal
structurize-0.10.153-ALPHA

### Expected behavior
Using the Builder's Tool UI, be able to select the Infrastructure button to see what schematics are available.

- 

### Actual behaviour

- Do the following:

1. Right click a spot on the ground with the Builder's Tool.
2. The tool UI appears.
3. Select the middle drop down list and scroll until you see **Infrastructure**.
4. Select **Infrastructure**.

You receive the following error:
_The game crashed whilst unexpected error
Error: net.minecraft.util.ResourceLocationException: Non [a-z0-9/._-] character in path of location: minecolonies:blockhutWaypoint_

[crash-2019-08-22_15.46.49-client.txt](https://github.com/ldtteam/minecolonies/files/3532213/crash-2019-08-22_15.46.49-client.txt)

**Comment by Raycoms** [comment]
fixed
