### ISSUE TITLE
Colonists not showing on journeymap

### ISSUE THREAD

**Issue by ghost** [ldtteam/minecolonies#3805]
Minecolonies: 0.10.344 (I looked at changelogs on newer versions and could not find anything relevant)
Forge: x.2838

Colonists used to show up on journeymap, now they don't, fairly self explanatory. If more detail is needed, I can provide it.

**Comment by Talyda** [comment]
I noticed that too - but I've only been playing the test version so I thought it was to do with that. Is making finding particular colonists a little more difficult!

**Comment by Raycoms** [comment]
Closed in favor of joint issue.
