### ISSUE TITLE
Crash involving Structurize when creating world

### ISSUE THREAD

**Issue by darthvader45** [ldtteam/minecolonies#3806]
### Minecolonies version

Version: 0.10.346-ALPHA

### Expected behavior
World is created as normal

### Actual behaviour
Game crashes with mention to Structurize

1. Install Forge and MineColonies 0.10.346-ALPHA
2. Start Minecraft and create a world
3. Game crashes with log mentioning Structurize
4. ... Profit

https://paste.ee/p/uKhzp

**Comment by Asherslab** [comment]
i mean.. you didn't even provide the crash? also, https://github.com/ldtteam/structurize

**Comment by darthvader45** [comment]
It only happens when MineColonies is installed.  Last I checked, it didn't say it required Structurize to run.

**Comment by Asherslab** [comment]
There's no crash in this log caused by structurize

**Comment by darthvader45** [comment]
Then what's the NoSuchFileException on line 4921?

**Comment by Asherslab** [comment]
Just an error, it's been in the mod for ages. does not cause a crash

**Comment by darthvader45** [comment]
Huh, I get kicked out of my game when it happened.  What else can I do to avoid this, aside from uninstalling MineColonies?

**Comment by Asherslab** [comment]
This stack trace did not kick you out of the game, nor caused you any issues. there is however a different stack trace in the crash log *after* the structurize one, caused by bibliocraft

**Comment by darthvader45** [comment]
Yeah, it's just my game closed, wonder what caused it.  The Bibliocraft one is just failing to get to the version check site, which never caused game-breaking problems for me.

**Comment by Asherslab** [comment]
yeah, the structurize one is just simply not finding a folder that's completely optional. it's been in the mod for 100+ versions and does not crash anyone, it's not your issue

**Comment by darthvader45** [comment]
Well, it seems to not play nice with Forge 14.23.5.2838, backing down to 2831 seems to have eliminated the crash issue.  Maybe an update to the Forge version its built against would be nice.
