### ISSUE TITLE
Colony fails to place with "had colony" spam in server log

### ISSUE THREAD

**Issue by dragonshardz** [ldtteam/minecolonies#3807]
### Minecolonies version
Version: 1.12.2-0.10.348-RELEASE

### Expected behavior
One of the people on my server is trying to place a colony. When the town hall is placed down, the colony should place and mark out the bounds of the town hall schematic

### Actual behavior
The town hall places, but cannot be interacted with, and the server log shows this line:

`Server thread/ERROR 16:45:06 BuildTool: building is null!`

Then proceeds to spam this until the server is rebooted

`16:50:37 TileEntityColonyBuilding at Biome Bundle:[-843,72,750]: had colony.`

### Steps to reproduce the problem
No idea. The person trying to place a colony is an officer in another colony, but the nearest colony is 742 blocks away.

**Comment by Nightenom** [comment]
Please entire log or at least entire error with stacktrace (if there is any)

**Comment by dragonshardz** [comment]
Unfortunately there's no stracktrace, as the server doesn't crash. I've attached the server log below.

[2019-08-25-7.log](https://github.com/ldtteam/minecolonies/files/3544516/2019-08-25-7.log)

**Comment by Raycoms** [comment]
this is a weird bug, was there a colony at that place already once?

**Comment by dragonshardz** [comment]
Sort of? The affected player tried placing a colony and encountered the error, so we deleted it for him and rebooted the server. After he tried to place it again, same bug. We can try placing a colony elsewhere.

**Comment by dragonshardz** [comment]
OK, so, we tried placing in a different location and the player was able to place it. We deleted that colony and got an error in the server log, but when he placed a town hall in the original location after that everything was fine. Wack.

Here's the error that popped in the server log: https://pst.klgrth.io/paste/ubxq6gygxn5v92vu35vxwgww

**Comment by Raycoms** [comment]
Hmm, this seems to be a problem related to placing a colony at the place of a previously deleted one. That gives me something to work with.

**Comment by Raycoms** [comment]
We fixed this.
