### ISSUE TITLE
Citizens without restaurant can't find proper cooked meal if there is something not cooked

### ISSUE THREAD

**Issue by Nightenom** [ldtteam/minecolonies#3808]
[Link to problematic method](https://github.com/ldtteam/minecolonies/blob/12e4645bb4944faa31d54300aebdcc7197069bba/src/main/java/com/minecolonies/coremod/entity/ai/minimal/EntityAIEatTask.java#L453)
This method should browse entire inventory and check list of found food to prevent blaming because of raw_eat.
Do stream check if there is anything cooked, then check if there is anything raw eatable (I don't remember if we mark things like carrot as not raw, otherwise skip this), then blame raw_eat if stream is not empty orElse blame no_food.

**Comment by spacewolfcub** [comment]
edible*

**Comment by SergeyAn70** [comment]
All residents, along with couriers and cook, crowd into the restaurant hungry, instead of bringing from the warehouse and raw (for cooking) and even ready-made food to satisfy their hunger.

**Comment by Raycoms** [comment]
@Nightenom I double checked this, we do check beforehand if there is an edible food source, if not we search the restaurant, and while we search the restaurant we complain if we have some "not cooked food" in the inv
