### ISSUE TITLE
Barbarians not attacking players

### ISSUE THREAD

**Issue by perecnicek** [ldtteam/minecolonies#3812]
### Minecolonies version

Version: minecolonies-1.12.2-0.10.348-RELEASE-universal.jar

### Expected behavior
When a Barbarians see us they have to attacks on us (players)

-  

### Actual behaviour

- I have raids in my colony but barbarians behavior is like they didn't see us and attack citizens after i hit them still nothing. Note we yesterday updated server on this version from beta version minecolonies-1.12.2-0.10.322-BETA-universal.jar

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit

**Comment by Raycoms** [comment]
same issue https://github.com/ldtteam/minecolonies/issues/3813
