### ISSUE TITLE
Hostiles not targeting citizens.

### ISSUE THREAD

**Issue by HarroldSaxon** [ldtteam/minecolonies#3813]
### Minecolonies version

Version: 1.12.2-0.10.348

### Expected behavior
Hostile mobs should target citizens.
### Actual behavior
barbarians and pirates each only occasionally (once every few seconds) attack an adjacent citizen, with all other hostile mobs (vanilla or moded) complacently ignoring them.
### Steps to reproduce the problem

1. load up the mod and start a new game
2. make a town hall block out in the open.
3. watch the zombies just chillin with your new citizens that night.
4. ... Profit?

 I also spawned in a pirate and a barbarian, however they would just stand next to a citizen, hitting them so infrequently, they would always re-gen to full between hits. Is the mod intended to be this easy? or is this incorrect behavior?

**Comment by Raycoms** [comment]
Noticed it too, on it

**Comment by someaddons** [comment]
zombies and other nonminecolonies hostile mobs only attack if you turn on the config option for it
