### ISSUE TITLE
[Feature] Hut Priority -1 to opt out of DeliveryPerson

### ISSUE THREAD

**Issue by spacewolfcub** [ldtteam/minecolonies#3816]
Related to issue [https://github.com/ldtteam/minecolonies/issues/3119](url) which is marked as Closed. 

We now have adjustable DeliveryPerson priority for Huts, going from 0 to 9, as requested in the above issue. 

What we don't have and still need (unless I've missed it entirely) is a way to opt out a Hut from the DeliveryPerson's list of places to check up on. So I'm opening a new Issue, so the suggestion for that setting is not entirely lost.

**Comment by someaddons** [comment]
I'd kinda like priorities like those instead of numbers: "High,normal,low,ignored"

**Comment by Raycoms** [comment]
Makes sense definitely

Am Mo., 2. Sept. 2019 um 11:51 Uhr schrieb someaddons <
notifications@github.com>:

**Comment by spacewolfcub** [comment]
I also like the idea of using a method less abstract than numbers to show priority. However, having only 4 priority settings takes away a lot of useful control in fine-tuning priorities, and relying on completely text-based interfaces actually lowers accessibility for groups like players with dyslexia or whose language is not supported by the mod. 

I think the GUI would be horrible to code, but if you'd like not just plain numbers I suggest:

(checkbox) Include in Courier route

if above is true (checked) then: 

Courier Priority: 
(downArrow) (radio) (radio) (radio) (flatLine) (radio) (radio) (radio) (upArrow)

**Comment by Raycoms** [comment]
Closed in favor of joint issue.
