### ISSUE TITLE
Miner constantly wants a new pick

### ISSUE THREAD

**Issue by kedamono** [ldtteam/minecolonies#382]
### Minecolonies version

version 0.6.2106

### Expected behavior

- Miner uses either a vanilla iron pick or a Tinkers Construct iron pick

### Actual behaviour

- Miner has both a vanilla iron pick and a TC iron pick in his inventory, but still requests for a new pick. Firing and hiring the miner results in him going down into the mine, and then returns and again requests a new pick.

### Steps to reproduce the problem

1. Updated to Minecolonies 1.10.2 0.6.2106 version.
2. Open existing world.
3. Miner immediately requests a new pick of wood or gold quality even when given a vanilla iron pick.

**Comment by Raycoms** [comment]
That's not a bug, that's a feature.
He is requesting a pick of wooden or gold quality (mining level 1) at early
levels of his building hut.
If you want him to use the iron pick please upgrade his hut.

2016-12-28 22:04 GMT-02:00 kedamono <notifications@github.com>:

**Comment by kedamono** [comment]
D'oh! I didn't realize that there was a change! The Lumberjack is fine with an iron axe, for now. :-)
