### ISSUE TITLE
[Feature] Show DMan statuses and what request Crafters are working on

### ISSUE THREAD

**Issue by TMarc** [ldtteam/minecolonies#3822]
This is a new feature request and I make it because I like this mod :)

### Minecolonies version

Version: 1.12.2-0.10.351-ALPHA

### Expected behavior
Lack of information on GUI :
- Currently when the builder request something to craft, we can only see the progression on the builder request maybe add a section on other crafters (Stonemasson,sawmill, etc) "Currently working on XX craft for XX" 
- Same if the deliver, adding on GUI a line on "Delivering XX to XX"

Actually, we can not see ingame what a crafter is doing.

**Comment by Asherslab** [comment]
using the Clipboard you can view things like that

**Comment by TMarc** [comment]
> using the Clipboard you can view things like that

Yes, the clipboard give what he need to build and the progression.

Unfortunately, you can see what the crafter is doing.
Example : I have a miner and a builder, both request fences to the sawmill, on sawmill you see the worker moving but you do not know who's the requester or what he's making.

**Comment by Asherslab** [comment]
Ah, you want exactly what request the worker is working on

**Comment by marchermans** [comment]
As of not not possibly, and will most likely not be possible in the future, the AI and the Job instances handle what a given citizen is doing at any given time. These only exist on the server and not on the client for obvious reasons. Without this data ("The what am I doing and what am I going todo data") creating a UI for this is simply impossible, even though the request data exists on the client. There is currently no way to figure out what request is assigned to what citizen on the client side alone.

**Comment by marchermans** [comment]
I have closed this issue, however i have made a note to possibly take a look at it again when we figure out how to sync the job and its data properly.
