### ISSUE TITLE
Add ability for colonists to pilot boats and ride in them with player/colonist pilot.

### ISSUE THREAD

**Issue by MonzterAssassin** [ldtteam/minecolonies#3824]
Colonists should have the ability to ride in and pilot minecraft boats to fulfill the plausibility of a port city / docks city. It's a small feature that fills a niche colony style, but I feel it enables further creativity with how colonies can be designed.

Further considering the feature itself, it can perhaps be enabled through the use of a building, requiring both the destination and departure location have this building across a length or body of water. If that is too complicated to add, it can be as simple as just having out-of-the box ability to preferably find and hop in a boat when needing to cross water.

Editing for grammar.

**Comment by marchermans** [comment]
Interesting idea
Would require an entire rework of the pathing AI I think, also I am not sure AIs even tick when NPC are in boats. But that might be wrong.

**Comment by Raycoms** [comment]
Closed in favor of joint issue.
