### ISSUE TITLE
"You need to be closer to your town hall!"

### ISSUE THREAD

**Issue by mnemonicmonkeys** [ldtteam/minecolonies#3825]
### Minecolonies version

Version: minecolonies-1.12.2-0.10.337-ALPHA-universal

### Expected behavior

- Successfully place a builder's hut only 30 blocks from my town hall

### Actual behaviour
Builder' hut won't place, and get error message saying "You need to be closer to your town hall!". Tried placing builder's hut closer, maybe 15 blocks from the town hall block, same result. Tried placing both manually and with the building tool, same result. Exited and restarted game, same result 

### Steps to reproduce the problem

1. Place town hall block
2. Can't adjust town hall placement (height above ground, direction its facing) without being built so break block with axe and re-place town hall to fix it 
3. Now I can't place the builder's hut

**Comment by Raycoms** [comment]
walk into the chunk, or relog to load the chunk correctly with the necessary data. Or switch to dynamic claiming which does it automatically. The buildtool in the hand will render the area you can place in.
