### ISSUE TITLE
Server Crash with ClassCastException on PathFinding

### ISSUE THREAD

**Issue by GanthorPrime** [ldtteam/minecolonies#3826]
### Minecolonies version

Version: minecolonies-1.12.2-0.10.354-ALPHA-universal.jar

### Actual behaviour

Dedicated server is crashing randomly with the following exception:

[log](https://pastebin.com/FXuQaUu2)

### Steps to reproduce the problem

this happens mainly when nigth start, cant see another pattern

**Comment by Asherslab** [comment]
need an actual log please...

**Comment by GanthorPrime** [comment]
wow,  issue updated

**Comment by GanthorPrime** [comment]
just want to report this is solved in version
minecolonies-1.12.2-0.10.357-ALPHA-universal
