### ISSUE TITLE
Miner stops working after digging some of a hole.

### ISSUE THREAD

**Issue by Aryathel** [ldtteam/minecolonies#3827]
I am new to minecolonies, but have gotten this issue twice now where the miner breaks and stops mining.

### Minecolonies version
Version: 1.12.2-0.10.348-RELEASE-universal

### Expected behavior
The miner should go down, dig out the hole, leave platforms (create the levels for the mine) and then be assigned to the proper level to go mining.

### Actual behaviour
In the process of digging out the hole, the miner always stops at roughly the same point, comes back to the surface, and then just sits at the miner block.
![2019-09-08_19 51 05](https://user-images.githubusercontent.com/32232419/64500451-157b0800-d272-11e9-87da-3154f001c397.png)

This issue has persisted across a relocation of the entire level 2 mine. I have tried completely emptying the inventory, giving him a bunch of the usual mine related blocks, etc, but never seem to get any response from the miner. I have tried restarting him as well.
This is the inside of the mine:
![2019-09-08_19 53 23](https://user-images.githubusercontent.com/32232419/64500607-b49fff80-d272-11e9-99c7-e02be62137df.png)

The miner is also not requesting any items or blocks.

### Steps to reproduce the problem

1. Make a miner building.
2. Miner starts mining.
3. While miner is mining (before any platforms are completed), upgrade the building to level 2.
4. Soon afterwards, the miner will eventually stop, come to the surface, and not do anything.

**Comment by VampBloodknight** [comment]
Getting this also, have upgraded to level 3 and he digs the main shaft and stops, no side tunnels, goes to the surface and does and asks for nothing. 
Just re created my server and started a new world for my troops.

**Comment by Raycoms** [comment]
Can you please update your versions and report if it still happens?
