### ISSUE TITLE
classcastexception 0.10.356 crashes dedicated server Forge 1.14.4 build 101

### ISSUE THREAD

**Issue by kreezxil** [ldtteam/minecolonies#3828]
Issue:  0.10.356 crashes dedicated server Forge 1.14.4 build 101

Notes:
     class cast exception

crash report:
http://paste.ubuntu.com/p/FBcHv9vqmN/

fml server latest:
http://paste.ubuntu.com/

**Comment by kreezxil** [comment]
I'm fairly certain I downloaded your update with the fix but you kept version numbers the same essentially so it feels odd.

The class cast exception still remains, also now on build 102 of Forge for 1.14.4

Issue:  1.14.4-0.10.356 crashes dedicated server Forge 1.14.4 build 102

Notes:
     class cast exception still exists

crash report:
http://paste.ubuntu.com/p/2tTmmG8HsS/

**Comment by Raycoms** [comment]
Seems to be an issue with another mod.
