### ISSUE TITLE
forge and quarry not building

### ISSUE THREAD

**Issue by knightslayer14** [ldtteam/minecolonies#383]
### Minecolonies version

version 0.6.2100 or curse X.X.XX

### Expected behavior

- the quarry and forge to be built

### Actual behaviour

- not being registered and the builders standing in their huts

### Steps to reproduce the problem

1. place forge/quarry
2. click build building
3. watch the builders and chat
4. Profit

**Comment by nekatu** [comment]
I don't believe these huts have been fully implemented yet as per the wiki page:
http://www.minecolonies.com/workers

Hopefully soon- really looking forward to some of the other workers on that list!

**Comment by Raycoms** [comment]
Yep, not implemented yet. That's why not obtainable by recipe yet.
