### ISSUE TITLE
[Suggestion] Milk jugs to hold multiple buckets worth of milk

### ISSUE THREAD

**Issue by DWX12** [ldtteam/minecolonies#3833]
Instead of storing tons of milk buckets that take up storage room and use up alot of iron in the process, I propose ceramic and iron milk jugs to hold milk that can be placed in cowboy huts and in warehouses. Ceramic jugs could hold less and iron could hold more.

The block for the milk jug would be a 1x2 tall, much like the building placeholders. If milk is requested by a villager, the delivery person would look for an empty bucket, remove the bucket and replace it with a milk bucket and one bucket of milk would be removed from one jug.

Jugs would just make storing milk much much easier instead of a bucket by bucket basis.

**Comment by Raycoms** [comment]
Closed in favor of joint issue.
