### ISSUE TITLE
[1.14.4] [Bug] Server Crashes when trying to load mod on server.

### ISSUE THREAD

**Issue by Gbergz** [ldtteam/minecolonies#3835]
### Minecolonies version
Version: minecolonies-1.14.4-0.10.357-ALPHA-universal.jar

### Expected behavior

- That the server boots normally.

### Actual behaviour

- Server crashes.

Crash-report: [Pastebin](https://pastebin.com/BHZnaHA7)

### Steps to reproduce the problem

1. Start server
2. Wait a little bit
3. Server errors & then crashes.
4. ... Profit

Forge: 28.0.104
MC: 1.14.4

**Comment by Asherslab** [comment]
```
Raycoms Today at 23:18 
this is a mod compat issue
Another mod is causing this
 
AshersLab Today at 23:18
know which?
 
Raycoms Today at 23:18
Merlin forge is one of them
```
from Discord
