### ISSUE TITLE
idk why my game is crashing please help 

### ISSUE THREAD

**Issue by jcdriftekv2** [ldtteam/minecolonies#3836]
[crash-2019-09-12_19.58.31-server.txt](https://github.com/ldtteam/minecolonies/files/3608213/crash-2019-09-12_19.58.31-server.txt)

### Minecolonies version

Version: 1.14.4-0.10.356-ALPHA-universal.jar

### Expected behavior

- 

### Actual behaviour

- 

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit

**Comment by Asherslab** [comment]
please put the text file in a https://gist.github.com
downloading txt files is a hassle for people trying to help you 😄

**Comment by Raycoms** [comment]
Fixed in the newest already =)
