### ISSUE TITLE
Game crashes when pirate event spawns

### ISSUE THREAD

**Issue by TearsOfLA** [ldtteam/minecolonies#3837]
### Minecolonies version

Version: 0.10.348-release

### Expected behavior

- Pirate ship spawns, Pirates spawn on ship and do pirate things

### Actual behaviour

- The message that the pirate ship appears shows up in chat and immediately the game (happened in single player and on server) crashes. when I relaunch the game, all of the spawners on the ship are for pigs, no pirates have spawned, however the event still continues as normal, after a few days the "pirates" sail away and the ship despawns.

### Steps to reproduce the problem

1. Start colony
2. have pirates attack
3. ... Profit

**Comment by Raycoms** [comment]
Log please

**Comment by Raycoms** [comment]
No log, please reopen when providing crash log.
