### ISSUE TITLE
[1.14.4] [Bug] Schematic Missing issue on 1.1.4

### ISSUE THREAD

**Issue by SoNick** [ldtteam/minecolonies#3839]
### Minecolonies version

Version:  minecolonies-1.14.4-0.10.357-ALPHA-universal

### Expected behavior

Supply Ship/Supply Camps build the items in question and/or after spawning the Build Tool in Creative Mode sending a command to spawn a building does anything at all.
- 

### Actual behaviour

Nothing happens in Creative Mode. In Survival, a message appears advising the schematic is missing for the Supply Ship/Supply Camp. Attempting to build a Town Hall in Creative Modes gives only a well as a building option.
- 

### Steps to reproduce the problem

1.  Load game
2.  Craft Supply Ship/Supply Camp item, attempt to place
3.  Chat displays error message advising schematic is missing
4. ... [lack of] Profit.

**Comment by SoNick** [comment]
Running Structurize 0.10.165 on Forge 28.1.10 for Minecraft 1.14 if that helps! Minecolonies version is 1.14.4-0.10.357-ALPHA-universal as stated in the original post.

**Comment by Raycoms** [comment]
Fixed already
