### ISSUE TITLE
Crash on Farmer chest interaction

### ISSUE THREAD

**Issue by nekatu** [ldtteam/minecolonies#384]
### Minecolonies version

version 0.6.2114

### Expected behavior

- Select Farmer chest and click next page option
- Review Farmer jobs and field assignment

### Actual behaviour

- Select Farmer chest and click next page option
- Small box in center of the screen shows "Shutting down internal server"
- Crash to desktop

### Steps to reproduce the problem

1. Select Farmer chest
2.  Click next page option

Have found that I can get to the next page option if I populate a field with a type of seed first, but within a minute or two of reaching the second page the game crashes anyway.

[crash-2016-12-29_10.58.24-server.txt](https://github.com/Minecolonies/minecolonies/files/676977/crash-2016-12-29_10.58.24-server.txt)

**Comment by Raycoms** [comment]
One of your coremod seems to overwrite the standard vanilla fishingrod.
That causes your crash.

**Comment by nekatu** [comment]
Thanks, @Raycoms !

Will dig through and check- not sure why that would be affecting the Farmer though, but could just be a coincidence that I've timed my attempts to access the Farmer with something the Fisherman is trying to do.

Supported by the fact that the Farmer is now working and the game is crashing at random intervals with an almost identical crash log.

Any ideas on which of my core mods could be causing it?

Still finding my feet with Forge mods so any help would be greatly appreciated.

**Comment by Raycoms** [comment]
Can't really tell from the log. You would have to remove one by one and
test if it still crashes.

2016-12-29 9:37 GMT-02:00 nekatu <notifications@github.com>:

**Comment by nekatu** [comment]
Thanks- confirmed it definitely is the rod causing the crashes by grabbing it out of the fisherman's inventory. Can't see any other fishing rods in the item list.

Will see what I can find- thanks again! :-)

**Comment by nekatu** [comment]
Ended up with running no other mods except MineColonies and still had the same issue.

I noticed that another user had the same issue in ticket #395 and that you shared a link to a new build. This appears to have solved my problem too.

Thought I'd let you know that it definitely appears to be an underlying issue with 0.6.2114 and 1.11.2.

**Comment by nekatu** [comment]
...and the game still crashes when you interact with the 2nd page of a Farmer chest before assigning a seed to a nearby field, even on 0.6.2161.

Crash log here: http://pastebin.com/BnEsnDZE
