### ISSUE TITLE
Cannot create a new world

### ISSUE THREAD

**Issue by OraziiK** [ldtteam/minecolonies#3841]
### Minecolonies version
Minecraft 1.14.4
Forge 28.1.0
Minecolonies 0.10.358
Structurize 0.10.167
8gb of ram allocated to the game

Note: this also is a problem with the previous version of Minecolonies and Structurize.

### Expected behavior
Create a world with large biomes and enter it.

### Actual behaviour
The game crashes and gives this error:  The game crashed whilst exception in server tick loop
Error: net.minecraft.util.ResourceLocationException: Non [a-z0-9/._-] character in path of location: minecolonies:blockhutCorner 

Note: if you create a new default world it will only say that the game has crashed without a message why.

### Steps to reproduce the problem
1. Create a new world with large biomes
2. wait
3. wait some more
4. ... Profit

**Comment by Raycoms** [comment]
do you have custom schematics?

Am Fr., 13. Sept. 2019 um 18:40 Uhr schrieb OraziiK <
notifications@github.com>:

**Comment by Raycoms** [comment]
I'll add a fix for this, to avoid a crash and it logs the issue.

**Comment by Raycoms** [comment]
Will be fixed in next structurize version (tonight)
