### ISSUE TITLE
[1.14.4][build 358] grass block in medieval dark oak builders hut level 1

### ISSUE THREAD

**Issue by kreezxil** [ldtteam/minecolonies#3843]
The medieval dark oak builders hut for level 1 has 2 grass blocks in it's schematic essentially making this a late game model because silk touch is required to get grass blocks.

I know it's an oversight and you can rescan without those grass blocks.

Just as easily you could provide a grass block recipe. like dirt surrounded by wheat seeds for instance.

**Comment by Raycoms** [comment]
Will be fixed in next release (tonight)
