### ISSUE TITLE
Builder causing entity tick crash

### ISSUE THREAD

**Issue by anthonyispenguin** [ldtteam/minecolonies#3849]
### Minecolonies version

Version: 1.14.4-0.10.358-ALPHA-universal

### Expected behavior

-  builder expected to finish a building and not cause a crash when doing so 
### Actual behaviour

-  builder entity will do their job for a while no problem. Seemingly at random, when a task is soon to be finished either the game will crash, or nothing will happen. Oddly enough upon reboot they will finish building and then the crash will cycle through. An easy fix is to kill the entity, but in my current game I'm too far away and too late to do so. Damn auto save messed up my back up. 

### Steps to reproduce the problem

1. Assign a builder tasks to do in a survival game, give them stuff, etc...
2. maybe after a while the ticking entity crash might occur? (Pending they finish the building)
[crash-2019-09-14_17.54.35-server.txt](https://github.com/ldtteam/minecolonies/files/3613232/crash-2019-09-14_17.54.35-server.txt)

**Comment by someaddons** [comment]
upgrade your forge version to the newest, the crash is caused by a renamed function of it.
To: 1.14.4 - 28.1.1 https://files.minecraftforge.net/

**Comment by anthonyispenguin** [comment]
> 
> 
> upgrade your forge version to the newest, the crash is caused by a renamed function of it.
> To: 1.14.4 - 28.1.1 https://files.minecraftforge.net

Will do, much obliged.

**Comment by Asherslab** [comment]
@anthonyispenguin fixed?

**Comment by anthonyispenguin** [comment]
> 
> 
> @anthonyispenguin fixed?

Yup sure is!

**Comment by someaddons** [comment]
nice
