### ISSUE TITLE
Children not growing

### ISSUE THREAD

**Issue by AndresHdzArv** [ldtteam/minecolonies#3850]
### Minecolonies version

Version: minecolonies-1.14.4-0.10.358-ALPHA-universal

### Expected behavior
Children should grow

### Actual behaviour
Days pass and children don't grow 

I feed them and keep them safe

### Steps to reproduce the problem
Have a child and wait until nothing happens

**Comment by someaddons** [comment]
tested it and mine did grow up after a while, maybe you simply didnt wait long enough :D

**Comment by lunadragnstar** [comment]
The only time I had issues with children growing is when they didn't have enough food. but their growth times are varied, sometimes they grow quickly and sometimes slowly, there isn't a set time.

**Comment by someaddons** [comment]
ye it is chance based, so it does indeed vary^^

**Comment by Raycoms** [comment]
Yeah it needs some time
