### ISSUE TITLE
[1.14.4] Town hall bug

### ISSUE THREAD

**Issue by Elrol** [ldtteam/minecolonies#3851]
### Minecolonies version
Version: 0.10.358-ALPHA-universal

### Expected behavior
Using the build tool to place the town hall, I expected the block to be placed (it was), and for villagers to spawn.

### Actual behaviour
I chose the Medieval Oak style, confirmed the location, it placed the town hall in the air (no solid blocks under it) then for a long while I was getting client lag in what seemed a fairly regular periods, like the code was trying to do something, there was nothing sent to the server console. After a while, I decided to replace the town hall to fix it, and upon breaking it my client crashed.

Crash Log:
https://pastebin.com/PeWHzRjN

### Steps to reproduce the problem
1. Get the town hall, and build tool
2. Select the Medieval Oak syle, and confirm the townhall location.
3. Break the town hall block after a while
4. Profit

**Comment by Elrol** [comment]
I got back on the server, used the /setblock to change the block to air, then gave myself another town hall, built a platform up to where the hut was, and placed it again and it worked as expected. So not sure if the hut that I got from the ship was the issue or that the town hall was placed in the air, but either way.

**Comment by bicobus** [comment]
I get the same behavior, my log: [crash-2019-09-15_22.28.57-client.txt](https://github.com/ldtteam/minecolonies/files/3614248/crash-2019-09-15_22.28.57-client.txt)

Haven't tried to fix it as @Elrol did yet.

**Comment by Raycoms** [comment]
Should be fixed
