### ISSUE TITLE
Workers are all standing around

### ISSUE THREAD

**Issue by slendeboy88** [ldtteam/minecolonies#3852]
### Minecolonies version

Version:  Minecolonies 1.12.20.10.259-RELEASE

### Expected behavior

- 
all workers should be working doing their normal thing everyday
all workers like a miner,lumberjack, etc. should be working
### Actual behavior

- 
all the workers in my town have stopped working, all the workers were working properly but then I saw my worker just walking around and all my other workers were not working as well. I tried recalling citizens, etc. I read other articles about this issue and my problem hasn't been solved

### Steps to reproduce the problem

1. I don't know how it started but I think when I placed the citizen's hut and the worker started to build but then he stopped with all the rest of the workers.
2.. it looks like  they all stopped when he built it halfway

please help me fix this issue because I don't wanna make a new world again!

**Comment by Asherslab** [comment]
you're ~100 versions behind, please update

**Comment by slendeboy88** [comment]
ok but the mod was working fine before though. I installed the new version but the problem still persists

**Comment by slendeboy88** [comment]
ok after playing a bit more they start to work but then they stop after a while

**Comment by Asherslab** [comment]
low level citizens have small/medium breaks while working. consider them "lazy workers"

**Comment by slendeboy88** [comment]
ok but is it normal for them all to stop working at the same time and not work for like 10mins? all me workers are level 1 and I have a level 2 builder

**Comment by Raycoms** [comment]
They stop working when it rains or to grief a death

**Comment by Raycoms** [comment]
Please reopen when they stopped working and were not griefing and it was not raining either.
