### ISSUE TITLE
[1.14.4] Server boot crash

### ISSUE THREAD

**Issue by Gbergz** [ldtteam/minecolonies#3853]
### Minecolonies version
Version: 0.10.358-ALPHA

### Expected behavior
- That the server is booting up normally, like without the mod installed.

### Crash Report:
[https://pastebin.com/FpGJsp4i](https://pastebin.com/FpGJsp4i)

### Actual behaviour
I'm creating a Server and i put the jar into the mods folder (server side) and start the server. It crashes before even loading for 10 seconds.

### Steps to reproduce the problem
Add it to a server and start.

1. Create a server
2. Start server with mod installed
3. Wait.. then crash.
4. ... Profit

### Additional Info
Forge version: 28.1.1
MC Version: 1.14.4
Mod Version: 0.10.358-ALPHA

**Comment by Raycoms** [comment]
Does this still happen?

**Comment by Raycoms** [comment]
Should work now
