### ISSUE TITLE
[1.14.4] Restaurant gui is bugged

### ISSUE THREAD

**Issue by Elrol** [ldtteam/minecolonies#3855]
### Minecolonies version
Version: 0.10.358-ALPHA-universal

### Expected behavior
To open the hut gui, click the arrow, and select the fuels for the cook to use.

### Actual behaviour
The gui where the fuels should be is blank, meaning that I am unable to set a fuel so the cook cant work, and thus my villagers will get rather hungry.

https://imgur.com/a/5Qizhi6

### Steps to reproduce the problem
1. Build a Restaurant
2. Open the hut gui
3. Click the arrow to the next page
4. Profit

**Comment by Elrol** [comment]
I just reopened it after a few restarts (and a day or so) and now it shows the fuels. So im not too sure what was wrong earlier

**Comment by bicobus** [comment]
For me the behavior is reversed. The fuel list was fine, but with the latest update (359), the list became empty.

**Comment by Raycoms** [comment]
Should be fixed in the next one.
