### ISSUE TITLE
Bug with Townhall in multiplayer

### ISSUE THREAD

**Issue by Yancha3112** [ldtteam/minecolonies#3856]
### Minecolonies version

Version: 0.10.358-ALPHA-universal

### Expected behavior

- On my multiplayer server, placing townhall makes citizens spawn and rightclicking the townhall open the GUI.

### Actual behaviour

- On my multiplayer server, when I place the townhall, citizens don't spawn and I can't open the village GUI, and trying to break it makes my game crash.

### Steps to reproduce the problem

1.  Go on a multiplayer server
2. Place Townhall
3. Citizens don't spawn, no village GUI, try break it in survival mode and you will crash

**Comment by bicobus** [comment]
Why did you close this? I kind of get the same behavior.

**Comment by Elrol** [comment]
Because I had the same one #3851
