### ISSUE TITLE
Upgrading a building kills all animals in it

### ISSUE THREAD

**Issue by MatthiasMann** [ldtteam/minecolonies#3857]
Version: minecolonies-1.14.4-0.10.358-ALPHA-universal

### Expected behavior
Animals (esp in the herders buildings) are not killed

### Actual behaviour
All Animals (and leads) vanish when upgrading a building.

### Steps to reproduce the problem
1. Make a Cowboy's hut (level 1)
2. Put 2 cows in
3. Click upgrade building to level 2
4. Cows are gone => no more Profit :(

**Comment by Raycoms** [comment]
fixed
