### ISSUE TITLE
Crash on opening Build GUI for alternatestone Citizen's Hut

### ISSUE THREAD

**Issue by SoNick** [ldtteam/minecolonies#3858]
### Minecolonies version

Version: minecolonies-1.14.4-0.10.358-ALPHA-universal

### Expected behavior

- Selecting "Build Options" after placing alternatestone design Citizen's Hut lists required materials and allows the player to add the building to the build queue

### Actual behaviour

- The building style can be selected as expected and then the block can be placed using the Build Tool. Interacting with the placed block for the Citizen's Hut brings up the usual GUI, however clicking the "Build Options" button on the first page consistently causes the game to crash.

Error message:
The game crashed whilst mouseclicked event handler
Error: net.minecraft.util.ResourceLocationException: Non [a-z0-9/._-] character in path of location: minecraft:minecolonies.ColonyBuilding

### Steps to reproduce the problem

1. Craft Citizen's Hut
2. Select the style of alternatestone using the build tool and use it to place the block
3. Open the Citizen's Hut GUI
4. Select "Build Options"

Edit: Formatting

**Comment by Raycoms** [comment]
fixed
