### ISSUE TITLE
Rtp command [$5 awarded]

### ISSUE THREAD

**Issue by Raycoms** [ldtteam/minecolonies#386]
Would be nice if we'd had our own /mc rtp -> command.
That way we don't rely on other mods.

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=40477973)](https://www.bountysource.com/issues/40477973-rtp-command?utm_source=40477973&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by marvin-bitterlich** [comment]
@opmis wanna claim this bounty or should I reimburse the team?

**Comment by opmis** [comment]
How I claim a bounty. Dont even know about this

**Comment by marvin-bitterlich** [comment]
@opmis you can go to bountysource and claim the bounty there (this issue has a link). That way you can earn the 5$ for this feature. Or you tell me to let minecolonies claim it and I put it on a different issue of your choice.
