### ISSUE TITLE
Config comments

### ISSUE THREAD

**Issue by Nightenom** [ldtteam/minecolonies#3860]
1.14 branch is missing config comments
copying them from field javadocs should be fine

**Comment by cogrinn** [comment]
How would I do that?

**Comment by Asherslab** [comment]
@cogrinn are you looking to make a PR to make that change?
If so, i take it you understand how to import the project and get yourself setup yes?

**Comment by cogrinn** [comment]
I do not, I'm just trying to get the config file so I can change citizen limit and builder speeds

**Comment by Asherslab** [comment]
oh, then this isn't the place for that, check our wiki, our discord, or create a new issue.

**Comment by cogrinn** [comment]
Thank you :)

**Comment by Nightenom** [comment]
DMed you the solution :D just copy the hack from language handler in structurize and adjust it if needed
