### ISSUE TITLE
1.14.4 version server problem. Town hall builders hut, nothing working

### ISSUE THREAD

**Issue by alexmohler** [ldtteam/minecolonies#3864]
### Minecolonies version

Version: 1.14.4

### Expected behavior
if i click on town hall or builder hut it will work.

-

**Comment by Asherslab** [comment]
need more details please. proper minecolonies version, logs, other mods you might have, what you've tried. etc etc

**Comment by alexmohler** [comment]
I install last version of minecolonies (minecolonies-0.10.359-ALPHA) and Structurize Mod 1.14.4. Start server and then i set ship . Take town hall and building tool. And set up town hall. Place builder hut then click on it. It working. but after few second if i try click on it again they say me: "You do not have permission to do this in this colony." I already set owner and all but still doing this. After i reconect it work for a while but after few seconds it sad it again. Or if i remove town hall and place it again i can´t click on it. After while people start spawning. But still saying "You do not have permission to do this in this colony" And i can´t break any blocks. - still cant brake blocks after remove tawn hall with gamemode creative. and i dont know how "reset" that mod. i remove it from server and /fml confirm remove. But if i add it and connect i have stilll that problems and "construction tapes" is still here.

**Comment by alexmohler** [comment]
It working for now. but i have more problems. Lumberjack hut do not have texture when is placed. Lumberjack do not collecting wood. They just dissapear. And builder place glasspane and door wrong. Glass pane is not conected to near block.

**Comment by alexmohler** [comment]
It is on server and i have also this mods: Crafting station mod, Durability notifier, fishtraps, globalxp, iron chest mod, jei, light overlay, mr crayfish furniture mod, open blocks elevator mod, practical tools mod, reap mod, simple farming, simply light mod, spiketraps, storage drawers, structurize mod, tree chopper mod, useful backpacks mod, u team core, voxel map.

**Comment by Raycoms** [comment]
The glasspane, door, and lumberjack block issues are known and being worked on. (Lumberjack texture is because forge is missing something).

The lumberjack disappearing and the permission issues should not be happening though.

**Comment by Raycoms** [comment]
Closed in favor of other issue
