### ISSUE TITLE
Lumberjack station texture missing when first placed.

### ISSUE THREAD

**Issue by Michael-McKinley** [ldtteam/minecolonies#3868]
### Minecolonies version

Version:  0.10.359-ALPHA from the 2.3.4 version of the Minecolonies Getting Started pack installed on September 18, 2019, from Twitch Launcher

### Expected behavior

- 
The Lumberjack station to have a texture and not look like a cuboid with just the pink and black texture placeholder.

### Actual behaviour

- 
The Lumberjack station appears as a cuboid with just the pink and black texture placeholder.

How it looks in-game:
![2019-09-19_09 17 01](https://user-images.githubusercontent.com/5976433/65262333-fc1e5b00-dabe-11e9-9132-4b4488158074.png)

my resourcepack settings:
![2019-09-19_09 22 51](https://user-images.githubusercontent.com/5976433/65262444-35ef6180-dabf-11e9-8193-4e2fa6640408.png)

### Steps to reproduce the problem

(Not sure if all of this is needed. This is just what I have done in-game so far.)
1. install a fresh instance
2. Follow links on Twitch from Overview page to download texture packs and shaders recommended. (Note: Norton Antivirus detects malicious website when trying to download shaders through Chrome - I decided not do download them).
3. Start game and Open Resource packs folder.
4. Select the resource packs downloaded to be used, and arrange them in the order suggested on the overview page. (Note: the resource packs are for 1.12, but I over-rode the error anyway to see what would happen). (Note 2: I did not select the Programmer art resource pack at this time)
5: Begin a new Solo World - all settings default.
6: Removed the 1.12 texture packs and enable the Programmers art resource pack. (The first tree I found (Oak) had the place holder texture for the logwood )
7: No texture issues are seen until I placed the Lumberjack station. (The item in inventory looks fine)
8: create and place the resource caravan
9: Create and place the town hall station
10: Create, place, and build the builders hut
11: create the lumberjack station (used the stone axe recipe)
12: Place the lumberjack station in a suitable location (per boundaries seen while holding builders tool)
13: Removed the Programmers art resource pack as a test, no change in texture for the lumberjack station.

**Comment by Raycoms** [comment]
Yeah, we're waiting for forge to finish the multi-layer code again to allow the lumberjack and swineherder blocks.

**Comment by Michael-McKinley** [comment]
Cool, no worries.  I figured this had to be known by someone, but I saw nothing in the list of issues yet.
