### ISSUE TITLE
Builder accepting fewer than required items as full satisfaction of requirements.

### ISSUE THREAD

**Issue by Michael-McKinley** [ldtteam/minecolonies#3869]
### Minecolonies version

Version:  0.10.359-ALPHA from the 2.3.4 version of the Minecolonies Getting Started pack installed on September 18, 2019, from Twitch Launcher

### Expected behavior

- If builder hut indicates that it needs a particular count of an item, that it changes to fully supplied of that item only after being supplied with, at least, the required number of items.

### Actual behaviour

- No matter the number of items requested, delivering even a single item of that type, switches the builders hut to show fully supplied.  (Example (seen below): Builder is building the lumberjack hut and requires two storage racks. I built and supplied just one through the builders hut interface, and it now shows that both have been supplied.

At the builders hut:
![2019-09-19_09 42 11](https://user-images.githubusercontent.com/5976433/65264125-ce3b1580-dac2-11e9-8a98-360b92455be7.png)

inventory button of builders hut (shows my inventory and builders hut:
![2019-09-19_09 42 29](https://user-images.githubusercontent.com/5976433/65264189-f32f8880-dac2-11e9-8e87-7388bda15730.png)

Required Resources interface showing it needs 2 and that I am one short
![2019-09-19_09 42 42](https://user-images.githubusercontent.com/5976433/65264299-25d98100-dac3-11e9-8fab-5355db7d175d.png)

Required Resource interface after clicking the up arrow button to supply the resources I have in my inventory.
![2019-09-19_09 42 48](https://user-images.githubusercontent.com/5976433/65264366-473a6d00-dac3-11e9-8695-7cc2e704e492.png)

### Steps to reproduce the problem

1. have builder begin to build a new station (possibly upgrade as well, I have not gotten there yet in my game).
2. open builder hut station
3. use the up arrow button to provide less than the required number of resources for the build
4. interface updates to reflect fully satisfied resource request

**Comment by Raycoms** [comment]
Are you in creative gamemode? Have you checked if really two racks arrive in the builder hut inventory?

**Comment by Michael-McKinley** [comment]
I am not in creative.
The builder was standing there when I delivered the one and immidiate took off to continue his build, so I did not check.

As soon as I got your message I popped back into the game and I had seen he had placed only one, and ran off back to his hut with the appearance of one in his hand (usually meaning that is what he is looking for).  Before I could catch up to him, he started back to the lumberjack hut and placed the second one.

I will pay more attention to what I see in his and the huts inventory on my next building and update this post.

**Comment by Raycoms** [comment]
okay, thanks

Am Do., 19. Sept. 2019 um 14:04 Uhr schrieb Michael McKinley <
notifications@github.com>:

**Comment by Michael-McKinley** [comment]
Next building: Fishermans hut.

Builders hut indicated needed 44 dirt. 
Builder shows request for 44 dirt.
none in builders inventory.
none in builders hut inventory.

Verified I only had 1 dirt in my inventory.
Supplied dirt through builders hut, shows satisfied.
builder took it immediately,
-still none in builder hut
-1 in builder inventory
-builder no longer shows request for dirt

builder returns to fisherman hut location and places 1 dirt and returns to builders hut showing grass block in hand, and making placing animation move.
before I can catch up to him, he is returning to the fisherman's hut location, but now with the remainder of the dirt blocks needed showing in his inventory.

My next test: provide one item and remain at builders hut and keep checking the builder hut inventory to see if/when the rest of the resources appear, or if they just "magically" appear in the builders inventory.

**Comment by Michael-McKinley** [comment]
Next resource request; 8 cobblestone wall.

behavior as above after supplying just one through the builders hut interface.
kept checking builder hut inventory, and at no point did the remaining 7 wall pieces show up, however after returning to the hut for a moment, he turned around and headed back to the build site now with the remaining 7 in his inventory "magically".

Next resource request: 6 trapdoors

supplied just one directly to builder through his request.
he placed it and returned to the builders hut request 5 more.
I supplied one more to the builders hut interface this time and it now shows fully supplied.

**Comment by LazyNachos** [comment]
This is indeed happening you can just have 1 of the required item and hit the button it will fulfill the request and will duplicate the item to the required amount.
