### ISSUE TITLE
[1.12.2] Unable to teaching a recipe to NPC

### ISSUE THREAD

**Issue by TMarc** [ldtteam/minecolonies#3872]
### Minecolonies version

Version: minecolonies-1.12.2-0.10.362-ALPHA-universal

### Expected behavior

- No craftfing terminal when try to teach a recipe 

### Actual behaviour

- On all blocks with Teach recipe we can't teach new craft to NPC
https://imgur.com/a/bCYBZkr

Seems to have the same button in inventory/Teach recipe

### Steps to reproduce the problem

1. Go to a builder / crafter
2. Try to teach a recipe
3. ... Profit

**Comment by TMarc** [comment]
still present on version  minecolonies-1.12.2-0.10.377-ALPHA-universal

**Comment by Raycoms** [comment]
Fix pushed
