### ISSUE TITLE
Delivery man dont deliver 

### ISSUE THREAD

**Issue by richy1998** [ldtteam/minecolonies#3877]
Exact version, eg: 0.10.379-ALPHA 
Version: 1.14.4 forge 28.1.0

Hi Guys. 

At first. I really like this mod :) but i have a Problem with the deliveryman. I have 1 warehous at lvl 2 and 2x deliverymans huts lvl 2. both deliverymans take items from huts to the warehous. But none of both take items and deliver them to the huts. If i klick for example the the baker and klick on requests i can see he needs 64x wheat and one other task that mean the item comes from the warehous. The required items are in the warehous. 
And i habe one question. Does the citizen hut need a bed or chest? Because the stone citizen hut dont have a chest or bed. But the Wood hut have one bed.
Thanks a Lot guys :)

Richy :)

**Comment by richy1998** [comment]
Hi Guys

Forge 1.14.4-28.1.0
Minecolonies 10.379-alpha-universal

I have a Problem with the dileveryman. He took items from huts and bring it into the warehous. But he wont deliver huts with Open request. I have 1x warehous at lvl 2 and 2x deliverymanshut lvl 2. 

Richy :)

**Comment by richy1998** [comment]
If i Show the request task of a hut/worker there is a list with the requiered item and a other Information that says the item comes from the warehous.

**Comment by Raycoms** [comment]
Do you have other deliverymen? huts?

Am So., 22. Sept. 2019 um 17:16 Uhr schrieb richy1998 <
notifications@github.com>:

**Comment by richy1998** [comment]
No. Only 2x deliveryman hut at lvl 2. its a very small Village with 1x mine 1x Farm 1x baker 1x lumber Jack 1x Restaurant all at lvl 2

**Comment by Raycoms** [comment]
There are some issues with the dman we're currently fixing, are there any
exception in the log?

>

**Comment by bicobus** [comment]
Let me jump on this issue as I noticed some exception linked to the dman:

https://gist.github.com/bicobus/007392b1d33bc47c98a5cbe878e58d8f#file-latest-log-L467

**Comment by richy1998** [comment]
I can send the latest Log after work today :)

**Comment by bicobus** [comment]
To be more precise about my log, as I figured out today: for the exceptions to happen, I need to restart the request system using the appropriate command. Playing normally, the d-men don't deliver the things but no exception is being thrown.

**Comment by Slefje** [comment]
I also have same issue with deliveryman, doesnt deliver, just gathering and dumping. When I reset
request system, got same exeptions that bicobus have. After reset, deliveryman delivers one request, but builder still request same delivery that deliveryman has just delivered. I have to manually cancel builders request, then he continues building. minecolonies-0.10.393-ALPHA-universal and structurize-0.10.167-ALPHA

**Comment by fr3akb0y** [comment]
The thing with the Builder getting his request not resolved properly that Slefje mentioned. I noticed that too (same version as him). The deliveryman seems to dump the requested stuff (sometimes?) in the racks that are present in the builders hut. The Builder itself doesnt seem to notice it being deposit in a rack (at least I sometimes see his requested materials being in the rack when I check if the dman delivered and thats when he doesnt finish his request).
