### ISSUE TITLE
Postbox freezes the game and isn't working

### ISSUE THREAD

**Issue by AndresHdzArv** [ldtteam/minecolonies#3878]
Version:  minecolonies-0.10.379-ALPHA (1.14.4)

### Expected behavior
PostBox Gui should show and work

### Actual behaviour
Clicking the postbox just freezes the game, it doesn't show the GUI, until you press ESC you can walk again

### Steps to reproduce the problem

1. Build a PostBox
2. Interact with it.

**Comment by G1R-Productions** [comment]
I have a similar issue but instead because of the large size of the modpack the mailbox freezes your game for an extended period of time until it finishes loading all the items in the modpack and then runs at a very low framerate until you either search for an item or exit the mailbox.

**Comment by Raycoms** [comment]
#3833

**Comment by Sandriell** [comment]
> #3833

@Raycoms Did you reference the wrong issue? That seems completely unrelated.

**Comment by Raycoms** [comment]
Definitely referenced the wrong one =D
#3829 
#3937
