### ISSUE TITLE
[0.10.259] Builder places upgraded Thermal Expansion machines but requests their Basic versions

### ISSUE THREAD

**Issue by Cheetah97** [ldtteam/minecolonies#3880]
### Minecolonies version

Version: 0.10.259-RELEASE-universal

### Expected behavior

Builder properly recognizes Thermal Expansion's upgraded machines in custom schematics and requests augments and upgrade/conversion kits

### Actual behaviour

Builder only requests basic machines, **but** places their upgraded and augmented versions.

### Steps to reproduce the problem

1.  Make a schematic including an upgraded TE Machine, e.g. a Hardened Pulverizer with an Auxiliary Reception Coil augment.
2.  Load a Survival world and tell a Builder to build the schematic.
3.  The Builder requests a basic Pulverizer, but places a Hardened Pulverizer with an Auxiliary Reception Coil.
4. Repeat with a Creative Energy Cell.
5. ... Infinite energy

**Comment by Raycoms** [comment]
Yeah, probably can't do anything there. It depends on how they handle their metadata. I don't think its something we can easily fix.
