### ISSUE TITLE
[0.10.396] changing jobs leaves citizens standing around confused

### ISSUE THREAD

**Issue by MatthiasMann** [ldtteam/minecolonies#3881]
Version: minecolonies-0.10.396-ALPHA-universal

When firing a citizen (the library after training to 9/9/9/9)  and hiring it in a different job it should pick up the new "cloth" and start working at the new hut.

### Actual behaviour
The citizen walks to the new hut (delivery man hut, level 4) but keeps his unemployed cloth and starts wandering around.

This also happened with the miner before (also firing from the library and hiring at the miner level 3).

After reloading the game the citizen take up their new cloth and start working.

### Steps to reproduce the problem
1. Have a citizen learning at the library
2. Fire him/her
3. Hire him/her at a hut like deliver man / miner etc
4. Watch him/her not liking the new job

**Comment by Seilican** [comment]
happens with any firing and hiring  like moving around where working are working

**Comment by Raycoms** [comment]
Fixed in the latest
