### ISSUE TITLE
Items do not drop when a rack gets destroyed

### ISSUE THREAD

**Issue by fr3akb0y** [ldtteam/minecolonies#3884]
### Minecolonies version

Version: minecolonies-0.10.396-ALPHA-universal.jar for 1.14.4

### Expected behavior

- Have the items from a destroyed rack dropped.

### Actual behaviour

- If a rack gets destroyed they do not drop any items stored in it.

### Steps to reproduce the problem

1. Place a rack
2. Put items in rack
3. Destroy the rack (doesnt matter how)
4. ... Profit

**Comment by Raycoms** [comment]
Duplicate #3863
