### ISSUE TITLE
Building is null issue - version 0.10.393-ALPHA / 0.10.396

### ISSUE THREAD

**Issue by Kheldarath** [ldtteam/minecolonies#3885]
### Minecolonies version
version 0.10.393-ALPHA

Version: 

### Expected behavior
Expect town hall lectern to be placed and be useable.

When trying to place a new town hall using the buidling tool I have set the template to what should be the correct area, double checked the area for drops, planets and missing bricks. I have confirmed the building. expect town hall to place and book to be useable.
 

### Actual behaviour
Town Hall Lectern appears but is not useable

When trying to place a new town hall using the buidling tool I have set the template to what should be the correct area, double checked the area for drops, planets and missing bricks. I have confirmed the building. Lectern (town hall book block) appears on its own or floating in the air, i try to right click on it to use it - nothing happens.  

server log prints out this exception :  [Server thread/ERROR] [minecolonies/]: BuildTool: building is null!

in addition, when then trying to place a builders hut, it states that i need to place a townhall first.
which i have already done.

I am trying to place in a badlands biome

### Steps to reproduce the problem

1. construct camp, 
2. retrieve townhall and building tool from chest
3. attempt to place town hall.
4. ... Profit

**Comment by Campermangreg** [comment]
I'm also having this exact problem, can't use the mod as once the townhall is placed nothing happens.

**Comment by Kheldarath** [comment]
this issue has reappeared for me on Alpha 396 aswell

**Comment by Bucketsmith** [comment]
I am also suffering this bug, as described above. Trying to place a citizen's hut. My mate who owns the server, but not the colony (I own the colony) has no issues.

**Comment by Insane96** [comment]
Same bug as of 0.10.462-ALPHA. Can't place the townhall. 
Placing the ghost building and re-joining the world seems to have fixed the problem

**Comment by someaddons** [comment]
can't reproduce this on the newest, try upgrading minecolonies,structurize and forge and try it again, please

**Comment by MazeusXenon** [comment]
I am running into this exact same issue, but with ALPHA 10.564... confirmed newest structurize and forge

**Comment by someaddons** [comment]
could you add screenshots/exact details of what you're doing? Basically any click/action

**Comment by MazeusXenon** [comment]
Reloading my client while I type this to get some screen shots, but basically I use the building wand to place the town hall, select the town hall I want (Medieval Oak), check the final size and position on L5, then move it back to L1, then check the box to place it (the green check box). Let me know if you want screen shots as well.

The server does not have the latest Forge (28.1.90; latest from the forge site is 28.1.96) but does have 10.199-ALPHA for structurize. A solo game I was testing with to match the server's forge worked just fine - town hall placed with issue and uses the exact same mods as the server.

I should also mention this for 14.4 of MC. That would probably also help.

**Comment by MazeusXenon** [comment]
Okay, this is crazy. Once I had it work on a solo game, logged back onto the server and it worked... yay?

**Comment by MazeusXenon** [comment]
Probably need to make a new item, but now whenever I get a new colonist (now that it is working), the game crashes. See attached log.

[crash-2019-11-29_12.09.39-client.txt](https://github.com/ldtteam/minecolonies/files/3906149/crash-2019-11-29_12.09.39-client.txt)

**Comment by someaddons** [comment]
ye the version 564 has a crash, update to the newest 566

**Comment by someaddons** [comment]
problem with this is that we can't reproduce the bug :D

**Comment by MazeusXenon** [comment]
Yeah, I run into that myself - easily the most frustrating bugs!
Updating to the newest - thanks!

**Comment by MazeusXenon** [comment]
Wait - 566 is for 12.2, not 14.4 (our server is 14.4) - or am I missing it on the curseforge download site?

**Comment by someaddons** [comment]
you're right, seems 1.14 is missing the fix, then downgrade to 563

**Comment by MazeusXenon** [comment]
seems simple enough - thanks again!
