### ISSUE TITLE
Remove blocks really does! 

### ISSUE THREAD

**Issue by Tivaala** [ldtteam/minecolonies#3887]
So i was taking a schematic of my barns but i didn't want to copy the livestock.  What i didn't realise was the remove option wouldn't just remove them from the save like i expected but actually deleted all my horses out of existence. Might want to put a warning label on that. Or even better adjust the save not the "real" world.

**Comment by Raycoms** [comment]
Yeah, it really changes the real world, since else it would be difficult to show you how things look like.
It's supposed to be a worldedit replacement.

**Comment by Asherslab** [comment]
i mean, delete does kinda mean delete.

**Comment by Tivaala** [comment]
I get what you're saying. And it's my fault as i was thinking of it as more of a schematica replacement than a world edit replacement.

 I just didn't expect it to do that,  i thought it was editing the save not the live copy. In schematic terms that would be very useful,  you want a copy of something you're using but not necessarily the decorations/ furnishings... Remove them from the save and then go place a copy of the blank shell.

But at least you guys now know there are numpty's out here who are busy thinking 'woohoo, instaplace schematics!' and not realising that that means world edit is involved.

**Comment by Raycoms** [comment]
I think then we'd furnish it in the build tool to edit before placement
