### ISSUE TITLE
Null Pointer Exception on loading the game with Minecolonies

### ISSUE THREAD

**Issue by MinerTurtle45** [ldtteam/minecolonies#3891]
### Minecolonies version

Version: 0.10.406-ALPHA-universal

### Expected behavior

- Being able to load the game

### Actual behaviour

- Game crashes with a Null Pointer Exception of startup

Pastebin of Crash Report: https://pastebin.com/bcBxtWXY
Modlist is in the pastebin. Tried with and without pre-release Optifine build since it was the most likely culprit and there wasn't any change. Structurize by itself loads fine, problems only occur when adding Minecolonies itself. Please let me know if anything sticks out like a sore thumb (memory issues, known incompatibilities, etc.)

**Comment by Nightenom** [comment]
Welp, com.jaquadro.minecraft.storagedrawers, not our mod problem

**Comment by Asherslab** [comment]
Yup, has nothing todo with minecolonies. contact Storage Drawers mod
