### ISSUE TITLE
Lumberjack placing items into void

### ISSUE THREAD

**Issue by Seilican** [ldtteam/minecolonies#3894]
Version: 
minecolonies-0.10.403-ALPHA-universal.jar

### Expected behavior

the lumberjack harvesting tree's and placing the logs and so on in the inventory of the hut

### Actual behaviour

as far as i can tell the lumberjack stop's seeing the inventory of the hut block at all for anything but still come's back and drop's things into something i can't access or the void

### Steps to reproduce the problem

1. set up a lumberjack
2. play for a while all works find like we want
3. log out
4. log back in to server
5. lumberjack is now not using same hut block as we are

**Comment by Seilican** [comment]
still happening in minecolonies-0.10.417-ALPHA-universal.jar very off and on this time i was playing for 4 hours now its doing it once more :(

**Comment by Raycoms** [comment]
Can't reproduce, shouldn't happen anymore.
