### ISSUE TITLE
medievaloakalternate citizen4 burns down

### ISSUE THREAD

**Issue by MatthiasMann** [ldtteam/minecolonies#3895]
### Minecolonies version
Version: minecolonies-0.10.408-ALPHA-universal ? (the building was build with 39x)

### Expected behavior
Thatb the house doesn't burn down on it's own

### Actual behaviour
The dual fire place in the middle of the building burns down the house

### Steps to reproduce the problem
1. Build a medievaloakalternate citizen hut
2. upgrade it to level 4
3. wait until it starts burning
4. wait for the fire fighter citizen to extinguish it ... except there is no fire fighter hut (yet) :(

**Comment by MatthiasMann** [comment]
![2019-09-30_19 46 58](https://user-images.githubusercontent.com/6777029/65902644-3212e780-e3bb-11e9-8731-a5c047ed9134.png)
![2019-09-30_19 47 27](https://user-images.githubusercontent.com/6777029/65902655-363f0500-e3bb-11e9-93be-1057d232d99c.png)
![2019-09-30_19 47 37](https://user-images.githubusercontent.com/6777029/65902661-3939f580-e3bb-11e9-8f15-204b476d7f70.png)

**Comment by Raycoms** [comment]
@carlansor @lunadragnstar

**Comment by MatthiasMann** [comment]
What about replacing fire with campfires in 1.14.4 ? these can't burn houses down and also produce smoke as a side effect

**Comment by carlansor** [comment]
im already at it. Changing the fires with campfires is one of the small changes all medieval buildings will have in 1.14 version.

**Comment by Raycoms** [comment]
closed since carl is on it.
