### ISSUE TITLE
[Mod compatibility] Cannot build under layer 1

### ISSUE THREAD

**Issue by NatNgs** [ldtteam/minecolonies#3896]
### Minecolonies version

Minecraft: **1.12.2**
Forge: 14.23.5.2768
Minecolonies: **0.10.348-RELEASE**
Structurize: 0.10.124-ALPHA
CubicChunks: 0.0.1003.0

### Steps to reproduce the problem

The "CubicChunks" mod is making minecraft Y dimension act like X and Z: No bedrock, and can build to ~ -infinity to +infinity.

1. Install CubicChunk mod (I'm not from developers or contributor of this team, just player)
2. Create a world type "Cubic: true" (so that the bottom limit is replaced by endless caves and ground)
3. Dig down or teleport to layer Y 0 (any X, any Z; can also be repeated for layers Y under 0)
4. Place a village near (with Y above 0, let's say around Y 12 for example)
5. Place any building (example: Builder) on Y 0 layer, or under.
6. Open it, and click on "Build options", and "Build" to create the build request.

### Expected behaviour

7. (As if do the same operation on above layer, like Y 62) Some non busy builder take the request and starts to build.

### Actual behaviour

7. The following message appears in chat:

> &lt;building name&gt; is too low, please raise the building above Y 0

then nothing append, build request seems ignored (as expected as suggested by the message).

### Note

- It works fine for higher Y (like Y 256 or more). No error message and the builders is able to start working.
- I did suppose the problem was on MineColonies mod, and so I did not yet contacted CubicChunks teams about this issue. In case it is needed, there is a link to their repo (all issues/backlog of their is using github):
https://github.com/OpenCubicChunks/CubicChunks
- Other issue currently open, maybe related: https://github.com/ldtteam/minecolonies/issues/3486

**Comment by Asherslab** [comment]
We do not support Cubic Chunks, it's a coremod that changes too many aspects of minecraft for us to support. 

We've looked into it before, but it's too big and changes too much for it to be feasible for us as a team

**Comment by NatNgs** [comment]
You mean that removing this constraint to build under layer 0 need lot of changes ?
Minecolonies is already working pretty fine with CubicChunks, this Y limit is the only one I currently found, I did not expected that difficulty unfortunatelly.

But still thanks

**Comment by Asherslab** [comment]
two things:
1. Yes it would be difficult because it would cause issues with normal MC.
2. There's a lot of other issues with cubic chunks that are under the hood that you're not seeing.
