### ISSUE TITLE
Fisherman's Hut will not proceed construction past the digging part. Get's stuck in build queue.

### ISSUE THREAD

**Issue by stormbringerGT** [ldtteam/minecolonies#3900]
### Minecolonies version
Version: minecolonies-1.12.2-0.10.1036-PR-universal

### Expected behavior
Builder would build and complete the oak medieval fishery

### Actual behaviour
The builder started digging out a plot for the fishery. As this was a superflat world for testing, there was no water, but he dug out the pond for the water that was included in the oak medieval blueprint.

After doing the digging for the water and then the wood posts he would run back to his house and then run back to the fishery and repeat this pattern, never finishing starting to build the fishery.

He had all the needed materials. Firing him and rehiring him did not help.

Now the fishery is stuck in the building queue. I can move it around but I cannot remove it and doing either makes the game throw up an exception as listed here:
https://paste.dimdev.org/ayigibayeq.mccrash

### Steps to reproduce the problem
1. Start a super flat world
2. Continue progression in Mine colonies until you have a builder
3. Order a fishery building
4. note that after digging out the plot building never starts
5. note that the fishery is now stuck in your queue

![2019-10-01_19 32 42](https://user-images.githubusercontent.com/40723259/66009932-4a016e80-e482-11e9-8f93-c7b746d74340.png)

**Comment by Raycoms** [comment]
Please update to the latest
