### ISSUE TITLE
Fulfilling a request throws an exception

### ISSUE THREAD

**Issue by stormbringerGT** [ldtteam/minecolonies#3901]
### Minecolonies version
Version: Version: minecolonies-1.12.2-0.10.1036-PR-universal

### Expected behavior
Should not throw exception when fulfilling a request?

### Actual behaviour
When you fulfill a request the game generates a crash log as follows:
https://paste.dimdev.org/ahodagomat.mccrash

### Steps to reproduce the problem
1. Start a minecolony
2. wait until the builder requests materials
3. Fulfill that request
4. Note the crash log generated

**Comment by Raycoms** [comment]
please update to the latest
