### ISSUE TITLE
1.14.4 0.10.412 noclassdefined w/ structurize 1.14.4 0.10.180

### ISSUE THREAD

**Issue by kreezxil** [ldtteam/minecolonies#3902]
Client crash report
https://pastebin.com/mueD0y9R

**Comment by kreezxil** [comment]
this seems to be a one off, if you can't duplicate it just close it for now

**Comment by lunadragnstar** [comment]
I'm having the same issue

**Comment by Raycoms** [comment]
Can't duplicate it either, seems like the jar failed loading accordingly
