### ISSUE TITLE
Sawmill cannot store the recipe to make Oak Planks

### ISSUE THREAD

**Issue by fr3akb0y** [ldtteam/minecolonies#3903]
### Minecolonies version

Version: minecolonies-0.10.412-ALPHA-universal.jar for Minecraft 1.14.4

### Expected behavior

- Successfully save the recipe for Oak Planks to the Sawmill

### Actual behaviour

- If you try to save the recipe to make Oak Planks out of Oak Logs at the sawmill, it says that it doesnt correspond with its profession. Every other wood recipe that i've tried works. Also same with the 6 sided logs and the sripped variants. Other workers that are capable of having their own recipes can store that recipe so I guess its just something in the wood recipe calculation? I wonder if Minecraft changed the way how logs are handled cause of the new variants or just cause of something else.

### Steps to reproduce the problem

1. Build a Sawmill
2. Try and save the recipe of Oak Planks made out of Oak Logs
3. ... Profit

**Comment by Raycoms** [comment]
fixed
