### ISSUE TITLE
[request] make herder and rancher compatible with genetic animals mod

### ISSUE THREAD

**Issue by kreezxil** [ldtteam/minecolonies#3906]
In my new 1.14.4 Minecolonies Getting Started pack we're using Genetic Animals Mod to give a variety to the animals. 

But it was soon discovered that none of them are compatible with Minecolonies, original report at https://github.com/kreezxil/minecolonies-getting-started/issues/13

I'm requesting to have this put on the todo stack for something from which to be compatible.

**Comment by Raycoms** [comment]
Animal mob compat is always difficult because if they change things too substantially, it needs substantial work as well.

**Comment by Raycoms** [comment]
Will be added to a new joint mod compat issue.
