### ISSUE TITLE
1.14.4 build 415 server crashes when player logs on

### ISSUE THREAD

**Issue by kreezxil** [ldtteam/minecolonies#3908]
We're getting there friend. 

 report name | paste
 ----------- | -----
crash-2019-10-03_11.05.19-server.txt | http://paste.ubuntu.com/p/RzjMPysqWb/
debug.log | http://paste.ubuntu.com/p/CCVWxCWP6z/
latest.log | http://paste.ubuntu.com/p/7MFK5phvtD/
seilican's client log - no crash.log | http://paste.ubuntu.com/p/Nm94yfB5fr/

**Comment by Raycoms** [comment]
fix pushed
