### ISSUE TITLE
[1.12.2] Builders take a very long time to dig out dirt or chop down trees

### ISSUE THREAD

**Issue by stormbringerGT** [ldtteam/minecolonies#3909]
### Minecolonies version
Version:  minecolonies-1.12.2-0.10.409-ALPHA-universal

### Expected behavior
Builders should remove dirt and wood from a new build site at an acceptable speed.

### Actual behaviour
Will try and capture a video, but currently the builder takes a very long time to dig out basic earth with a wooden shovel.

### Steps to reproduce the problem
1. start a colony
2. play until you have a builder
3. build a new building, sink it down one level so the builder has to dig out the base for the building.
4. Note the speed at which the builder digs out the site for the building.

**Comment by Raycoms** [comment]
Yeah it scales, at the beginning they are slow, later they get much much faster. You can improve this in the config file if you want.

**Comment by stormbringerGT** [comment]
I totally don't remember this in my previous testing. We are talking in game days to dig out a single layer, haha.

**Comment by Raycoms** [comment]
When you level the hut, tools and the worker itself he gets much much faster. But the first levels you should probably build buildings which don't require a lot of digging.

**Comment by stormbringerGT** [comment]
Here is the wooden citizens hut level one. It is about a minute a block:
https://imgur.com/a/qlWZOUW
