### ISSUE TITLE
[request] add NPC-only recipe registry

### ISSUE THREAD

**Issue by nephatrine** [ldtteam/minecolonies#3911]
There are modpacks where it is useful to disable many vanilla item recipes. For instance, one might want to disable normal tool crafting in favor of Tinker's Construct or force player's to use a special chopping block, kiln, oven, worktable, etc. to create items that are otherwise craftable normally in vanilla.

I don't expect NPCs to gain support for crafting things with those sort of unique mod-added crafting methods, but it would be nice to have the crafting NPCs not be utterly useless at the same time. So I was thinking via crafttweaker or config files it would be nice to add in recipes that ONLY the NPCs can use to allow modpack makers to give NPCs a route to actually create them without giving the player themselves such a shortcut. For example, I require a chopping block or sawmill to create planks/slabs of wood, but the the miller should still be able to make those things.

**Comment by Raycoms** [comment]
Closed in favor of joint issue.
