### ISSUE TITLE
Delivery man cannot detect Warehouses

### ISSUE THREAD

**Issue by Lezzax** [ldtteam/minecolonies#3912]
### Minecolonies version

Version: minecolonies-1.12.2-0.10.409-ALPHA-universal

### Expected behavior

Delivery Man is supposed to detect Warehouses

### Actual behaviour

Unable to find Warehouses and consistently requesting me to build another one or upgrade my current lvl 5 one

**Comment by Raycoms** [comment]
can you send us your world?

Am Sa., 5. Okt. 2019 um 03:34 Uhr schrieb Lezzax <notifications@github.com>:
