### ISSUE TITLE
[1.14.4] Forge 140 - Game doesn't load, log spammed with resource error

### ISSUE THREAD

**Issue by Partonetrain** [ldtteam/minecolonies#3919]
### Minecolonies version
0.10.415

Version: 
1.14.4
Forge 28.1.40 ([They changed blockstates in this version](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.14.4-28.1.40/forge-1.14.4-28.1.40-changelog.txt))

### Expected behavior
Minecraft reaches the title screen as normal

### Actual behaviour
Log gets spammed with 
`[Server-Worker-7/WARN]: Exception loading blockstate definition: 'minecolonies:blockstates/blockhutlumberjack.json' in resourcepack: 'Mod Resources' for variant: 'base': Unknown blockstate property: 'base'
[Server-Worker-7/WARN]: Exception loading blockstate definition: 'minecolonies:blockstates/blockhutlumberjack.json' in resourcepack: 'Mod Resources' for variant: 'overlay': Unknown blockstate property: 'overlay'`
and game doesn't reach title screen

### Steps to reproduce the problem

1. Install just Minecolonies, Structurize, and newer Forge
2. Launch game
3. Read log
4. Never reach the title screen :(

**Comment by fr3akb0y** [comment]
Probably updating Minecolonies fixes this since in version 0.10.423 it says "Make minecolonies launch on 1.40 forge" ^^

**Comment by Raycoms** [comment]
yes, fixed
