### ISSUE TITLE
[request] Minecolonies Growth Hormone

### ISSUE THREAD

**Issue by kreezxil** [ldtteam/minecolonies#3928]
Until the issue with 1.14.4 children not growing up is resolved how about a new item called **Minecolonies Growth Hormone**.

Perhaps it can be crafted from cookies, milk, and cake.

s | s | s
-- | -- | --
c | m | c
s | s | s

s = cake slice
c = cookie
m = milk

I suggest a full stack per child, because after all this is bug we're circumventing. If anything add it as a config option that can be turned on and the pack dev can decided how much MGH to apply to the children, default 64 or 16 or w/e. I chose an expensive recipe.

**Comment by Raycoms** [comment]
We pushed a fix to this today xD

**Comment by someaddons** [comment]
yep fixed today :D

**Comment by kreezxil** [comment]
which build?

**Comment by kreezxil** [comment]
I'll assume build 430

**Comment by someaddons** [comment]
429+

**Comment by kreezxil** [comment]
ok, MGH would still be cool tho.

**Comment by Raycoms** [comment]
I agree it's a decent idea to make it faster

**Comment by Raycoms** [comment]
could make it a "max times used per kid" or make their stats worse when used too much

**Comment by someaddons** [comment]
would call it differently though, hormones arent exactly a medival thing to use ^^

**Comment by Raycoms** [comment]
Could call it Fruchtzwerge (Little german joke).

Yeah, we could research what kind of thing they used if they wanted someone to grow up quicker, I'm sure they had some "crazy stuff they thought works well"

**Comment by kreezxil** [comment]
maybe you can make treacle in a cauldron by say putting in 5 stacks of
sugar cane to produce say 8 buckets worth of a dark so sweet it's
disgusting substance. Feed it to the kids. It makes them hyper and they run
from you. There's a 20% chance they get addicted and want treacle instead
of other foods as an adult. If they don't get they can be seen doing weird
stuff much like a meth addict does.

**Comment by Raycoms** [comment]
Well, that escalated quickly =P

**Comment by Raycoms** [comment]
Closed in favor of joint issue.
