### ISSUE TITLE
Sand Town Structures Problems

### ISSUE THREAD

**Issue by Seilican** [ldtteam/minecolonies#3930]
### Minecolonies version

minecolonies-0.10.430-ALPHA-universal.jar

Version: 
Minecolonies getting started 
Version: 2.18.19

Minecraft Version: 1.14.4

(modded) forge-28.1.44

### Expected behavior
upgrade sand barracks to level 3 and the towers are cool 
 
### Actual behaviour
upgrade sand barrack to level 3 and the towers get a new floor in the middle of the room and cut off ladder down so they can't get to beds

### Steps to reproduce the problem

1. build a sand town
2. see the structures are not right
3. make a barracks
4. see towers and barracks destroy each other

**Comment by Raycoms** [comment]
@lunadragnstar

**Comment by lunadragnstar** [comment]
I'll look into this
