### ISSUE TITLE
build 430 crashes dedicated server with a "nosuchmethod" and something about a spawn egg

### ISSUE THREAD

**Issue by kreezxil** [ldtteam/minecolonies#3931]
server crash report: http://paste.ubuntu.com/p/kYKfHgq9wb/

**Comment by kreezxil** [comment]
ok, i think this is related to children being born.

happened again

http://paste.ubuntu.com/p/tVSW4dXJC7/

**Comment by someaddons** [comment]
the miner AI is causing it

**Comment by Raycoms** [comment]
Someone scanned in an entity with a schematic

**Comment by drizzs** [comment]
-- Entity being ticked --
Details:
	Entity Type: minecolonies:citizen (com.minecolonies.coremod.entity.citizen.EntityCitizen)
	Entity ID: 5714
	Entity Name: Reagan X. Gooder
	Entity's Exact location: 1997.63, 55.75, 165.29
	Entity's Block location: World: (1997,55,165), Chunk: (at 13,3,5 in 124,10; contains blocks 1984,0,160 to 1999,255,175), Region: (3,0; contains chunks 96,0 to 127,31, blocks 1536,0,0 to 2047,255,511)
	Entity's Momentum: 0.05, 0.04, -0.07
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:684)
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:394)

What seems to be the problem officer? Your back tail light is out... we dont load broken stuff :P Entity Vehicle is getting a null pointer exception? is that normal?

**Comment by drizzs** [comment]
at com.minecolonies.coremod.entity.citizen.EntityCitizen.func_70636_d(EntityCitizen.java:1068)

line 1068 of entity citizen. Whatever that is doing is the problem

**Comment by kreezxil** [comment]
do we know which schematic tho?

**Comment by kreezxil** [comment]
@Raycoms what's the eta on the fix?

**Comment by kreezxil** [comment]
Will rolling back to a previous build even solve this problem?

**Comment by Raycoms** [comment]
there is no eta, because I'm waiting for forge to respond. Must be some
custom schematic having a bat inside.

Am Sa., 12. Okt. 2019 um 21:11 Uhr schrieb kreezxil <
notifications@github.com>:

**Comment by kreezxil** [comment]
is there a way as OP to force load the schematics into a world?

wait wait wait

are schematics even supposed to have mob entities in them? if that was not ever the plan, can't you create code that sanitizes the schematics on load, ie removing mobs.

However, back to the first question, if that's possible I'll commence to doing the work of finding the bat in the belfry.

**Comment by Raycoms** [comment]
I'm pushing a workaround for this.
