### ISSUE TITLE
crashing on loading Minecolonies Getting Started

### ISSUE THREAD

**Issue by ladyannie68** [ldtteam/minecolonies#3932]
### Minecolonies version
Minecolonies Getting Started 20.20.21 release current
Version: 

### Expected behavior
I would be able to load up and play game

- 

### Actual behaviour
once the minecraft screen is loaded and i press play to go to the minecolonies screen the game crashes
[latest.log](https://github.com/ldtteam/minecolonies/files/3719982/latest.log)

- 

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit

**Comment by Raycoms** [comment]
I advice you to download forge version 1.40 max. This is a forge issue
