### ISSUE TITLE
[1.14.4] Minecolonies spamming errors into the logs of the game. "latest.log"

### ISSUE THREAD

**Issue by Gbergz** [ldtteam/minecolonies#3935]
No crash.

### Minecolonies version
Version: 0.10.424-ALPHA

MC Version: 1.14.4
Forge Version: 28.1.44

### Explain issue
There's alot of error spam in the logs "latest.log" file, like.. alot more than i paste in this: [GistGithubPaste](https://gist.github.com/Gbergz/923fdd42feb3e731fc5d3a28424f9569)

**Comment by Raycoms** [comment]
upgrade please

**Comment by Gbergz** [comment]
> upgrade please

did that same errors appear in logs

**Comment by Raycoms** [comment]
are you on the latest alpha of minecolonies?

Am So., 13. Okt. 2019 um 15:28 Uhr schrieb Gbergz <notifications@github.com

**Comment by Gbergz** [comment]
> are you on the latest alpha of minecolonies?

No, i was using this one "**minecolonies-0.10.424-ALPHA-universal.jar**", upgrading to the latest alpha made so my game couldn't be launched with mods for some weird reason. 424 works fine.

**Comment by Raycoms** [comment]
Upgrade to a newer one and upgrade also to a version of structurize > 192

Am Mo., 14. Okt. 2019 um 07:40 Uhr schrieb Gbergz <notifications@github.com
