### ISSUE TITLE
Ticking Entity : NullPointerException

### ISSUE THREAD

**Issue by gabzzel** [ldtteam/minecolonies#3938]
### Minecolonies version

Version: minecolonies-0.10.432-ALPHA-universal
Minecraft version 1.14.4

### Expected behavior

- No Ticking Entity Error

### Actual behaviour

Every once in a while (say 5 minutes) the whole server crashes on an "Ticking Entity" error.
This has happened even with previous "release" versions of the mod 0.10.430 and 0.10.424. 
It almost always gives a certain mob as the ticking entity, like vanilla zombies. I also have Lycanites Mobs installed. Sometimes mobs from that mod with also appear as the ticking entity in the crash log. However, I even encoutered it with an vanilla arrow.  I have seen the minecolonies guards fighting minecolonies barbarians and/or lycanites mobs with no problem when taking damage. 

[Zoataur](https://pastebin.com/W02WyLMx)
[Arrow](https://pastebin.com/9hwFcPfH)
[Zombie](https://pastebin.com/RNU2r2DW)

We only use the server with the two of us. There are 45 mods total on the server. However, because every error log involved the following line : 

`com.minecolonies.coremod.entity.citizen.EntityCitizen.handleDamagePerformed(EntityCitizen.java:718)` 

I got suspicious. 

### Steps to reproduce the problem

1. Install the most recent minecolonies version (and possibly lycanites mobs while you are at it)
2. Build a colony with around 5 villagers.
3. Wait until they take damage from an entity.
4. ... Profit

**Comment by Raycoms** [comment]
pushing fix
