### ISSUE TITLE
crash on client while rendering scarecrow

### ISSUE THREAD

**Issue by kreezxil** [ldtteam/minecolonies#3939]
client crash: https://gist.github.com/kreezxil/bc91deb558fb721b881fa98b4b566a30

forge 28.1.47
minecraft 1.14.4
mod version 0.10.432-alpha

**Comment by Asherslab** [comment]
that doesn't make any sense. i'm going to guess there's an issue with another mod somehow?
@Raycoms how could we have a missing class there? it wouldn't even compile if it were missing
