### ISSUE TITLE
Suggestion: Colonist add colony ID to their requests

### ISSUE THREAD

**Issue by kedamono** [ldtteam/minecolonies#394]
### Minecolonies version

version 0.6.2106

### Expected behavior

- Colonist such as the Builder, when requesting an item, prefaces which colony they belong to.

### Actual behaviour

- Colonist doesn't ID which colony they belong to.

### Why this request?

As a officer of more than one colony on the official Minecolonies server, it's hard to know which colonist belongs to which colony when they request an item. It would be nice if they preface their request with a colony ID: [Player Colony] I need...

**Comment by forReason** [comment]
This is totally needed. Im building a colony with my cousin. we both have one and since we both are officers we never know which colony the requests are coming from
