### ISSUE TITLE
Colonists eating ingredients, not prepared food

### ISSUE THREAD

**Issue by richardmv** [ldtteam/minecolonies#3942]
Version: 1.12.2-0.10.348

Expected behavior: Cook receives ingredients and cooks/makes food items; colonists come to the restaurant and eat prepared food.

Actual behavior:
The cook sometimes makes the recipe he's been instructed to make (using Pam's Harvestcraft tools/ingredients) but I frequently see colonists taking and eating just the produce, which restores very little hunger, leaving my entire village a few ticks above starving most of the time.

Steps to reproduce the problem:
1. Run Pam's Harvestcraft along with Minecolonies
2. Build a farm with Harvestcraft crops and have a delivery person bring them to a restaurant
3. Give the restaurant crafting recipes for Harvestcraft meals
4. Watch the colonists constantly eat the raw produce grown by the farmer instead of prepared food

Tested using Harvestcraft cactus fruit with the fruit salad recipe

**Comment by Asherslab** [comment]
please update, you're over 100 versions behind

**Comment by richardmv** [comment]
This issue persists in version 0.10.438.

The cook does not make any recipes with Harvestcraft produce at all. I saw something in another issue report regarding food that is considered raw; I'm thinking perhaps the cook does not see the produce as raw and assumes it is a finished food.

I do see that there are alpha and beta releases that are more recent. I am usually hesitant to update when a release version is available; I run over 100 mods so it can be difficult to determine which mod is at fault for issues that may arise. If this issue may be fixed in one of those releases, however, I'd be happy to try out the most recent version and let you know if the cook's behavior changes.

**Comment by Asherslab** [comment]
the cook does not support pam's recipes

**Comment by richardmv** [comment]
Ah, okay. Thank you; I guess I'll handle the cooking and let the cook serve the food.
