### ISSUE TITLE
[1.12.2] Rack doesn't have Inventory Tweaks buttons

### ISSUE THREAD

**Issue by ExDomino** [ldtteam/minecolonies#3943]
Rack doesn't have Inventory Tweaks buttons.
Version: 1.12.2-0.10.348
Shortcuts don't work either, for example middle mouse to sort items.

![inventorytweaksbuttons](https://user-images.githubusercontent.com/1377729/66979371-3a397b00-f07b-11e9-9fb4-844abc26d8f0.png)

**Comment by Asherslab** [comment]
That's normal, we don't support it, they don't support us

**Comment by Raycoms** [comment]
You can config it with the inventorytweaks config files.

Am Do., 17. Okt. 2019 um 03:55 Uhr schrieb AshersLab <
notifications@github.com>:
