### ISSUE TITLE
Jungle tweaks

### ISSUE THREAD

**Issue by kd5crs** [ldtteam/minecolonies#3945]
### Minecolonies version

Version: minecolonies-0.10.435-ALPHA-universal

### Expected behavior

Jungle villages should look like they are in a jungle.
### Actual behavior

 
The tops of the trees included in the buildings do not have leafy tops, they look sawn off.

The Builder chops down everything above deck height, which really destroys the "jungle" feel.

### Details

I love the new Jungle set! Dark Oak was my previous favorite, but Jungle raises the bar in treehouse style living. It would look so much better if the builder did not clearcut the jungle so much. Is there a way to make it so that the only stuff the Builder cuts down is things inside the Jungle buildings, and leaves everything else that is replaced with "air" alone? I would love it if you could hardly see the village for the jungle trees unless you knew just where to look (or you look up above the canopy). 

If I understand correctly, this would be replacing most of the "air" blocks with the "placeholder" block?

Also, what's up with the trees used in the buildings being cut flat on top? Shouldn't they look like full trees with the jungle built on it, like the dark oak style?

Otherwise loving the jungle village style, very cool.

**Comment by kedamono** [comment]
Well as the creator of the style, it's designed so that you can use existing trees or grow trees in the right places. Otherwise you'd have to harvest all those leaves that would be needed for the tops of the trees.
