### ISSUE TITLE
1.14 blueprints must be lowercase

### ISSUE THREAD

**Issue by kd5crs** [ldtteam/minecolonies#3946]
### minecolonies-0.10.435-ALPHA-universal

Version: 

### Expected behavior

- Player made schematics should work in 1.14 just like 1.12

### Actual behaviour

- Schematics that start with an uppercase letter are not recognized.

### Steps to reproduce the problem

1. Add the Urban style to .minecraft\structurize\schematics
2. Run Minecraft
3. Schematics do not show up
4. Change schematic names to lowercase
5. Run Minecraft
6. Schematics and category now show up.

**Comment by Asherslab** [comment]
That’s normal. 1.14 enforces *everything* in resource and datapacks to be lowercase. Nothing we can do

**Comment by Raycoms** [comment]
Yes, this is not in our control, minecraft doesn't allow us handling anything with any lower case letters without crashing on us in the realm of minecraft resources.
