### ISSUE TITLE
Builder basement chest bug

### ISSUE THREAD

**Issue by Jasonss1** [ldtteam/minecolonies#3949]
### Minecolonies version . 

Version: minecolonies-1.12.2-0.10.348-RELEASE-universal.jar

### Expected behavior

Builder would be able to access materials in chests in basement
- 

### Actual behaviour

The builder waits around in front of his station and doesn't send a request for the block to the deliveryman or take it into his inventory from the chest. He appears to store stuff in there just fine, but then I occasionally need to get it out for him
- 

### Steps to reproduce the problem

1.  Get a level 2 builders hut
2.  have him store something in the basement chest by the stairs 
(don't know about other chests or levels)
3.  He will wait if front of the station trying to access the materials he needs and the player will need to get it for him. (I'm not sure if this happens every time but its come up a lot already
4. ... Profit

**Comment by Raycoms** [comment]
Any errors in the log?

**Comment by Jasonss1** [comment]
What log?

**Comment by Jasonss1** [comment]
2 more things I found out with this bug that I’m not sure I made clear is that the builder can still get food from his chests and he still puts out a request for the material which is ignored by the delivery man and not put in chat.

**Comment by Raycoms** [comment]
Your server log

**Comment by Jasonss1** [comment]
I should also mention that the builder can still get food from his chest just fine and that the request shows up on his requests tap but doesn’t get a deliver or send it out into chat

**Comment by Jasonss1** [comment]
I can’t find anything

**Comment by Jasonss1** [comment]
I am playing with a lot of other mods on the Life in the Village mod pack on twitch

**Comment by Jasonss1** [comment]
I did find a work around by breaking the chests in the builders hut

**Comment by Raycoms** [comment]
I can't reproduce it, he took it out for me perfectly fine.

**Comment by Raycoms** [comment]
Are there any exceptions in the log for you?

**Comment by Jasonss1** [comment]
It doesn’t happen every time for me either, but I have found that it also includes his builders hut block inventory and happens maybe 1/4 of the time. I am using medieval dark oak style if that helps

**Comment by Jasonss1** [comment]
No exceptions or anything I can find, it appears to be normal

**Comment by Raycoms** [comment]
Can you use a newer version and check again?

**Comment by Jasonss1** [comment]
I tried the new version and it seems to have been fixed.
