### ISSUE TITLE
enchanted fishing pool crash

### ISSUE THREAD

**Issue by icha-senpai** [ldtteam/minecolonies#395]
### Minecolonies version

 curse 1.11 beta v7

### Expected behavior

- gave my world class fisherman, Richard Z. Robinson, an enchanted pool with mending...unbreaking 3, luck of the sea 3, lure 3 to continue being the worlds greatest fisherman 

### Actual behaviour

- every time he throws the lure out i crash here is my first crash report http://pastebin.com/crY1X8Cr
Here is my second crash report when trying to reproduce it http://pastebin.com/4wAvTjgN

### Steps to reproduce the problem

1. logged back in heard him throw and boom crash
2. so enchant a pool with the same enchants
3. wait for it
4. crash

**Comment by Raycoms** [comment]
Will take a look at it and try to fix it as soon as possible. (Tomorrow).

2016-12-30 22:24 GMT-02:00 Icha <notifications@github.com>:

**Comment by icha-senpai** [comment]
awesome thank you and appreciate it alot

tomorrow that's fast 
i'll make a temp world until then..figured this one would be lost forever but hopefully not

**Comment by Raycoms** [comment]
There should appear a new version here in around 10 minutes:
https://www.dropbox.com/sh/9cnqcjl0nan57cy/AAC99g-CJiTZjQiXMuLKkDgja/branch/version/1.11?dl=0

With the fixed bug if you could test it out.

2016-12-30 22:40 GMT-02:00 Icha <notifications@github.com>:

**Comment by icha-senpai** [comment]
it works he throws his plow and catches things and no crashes

TY very much
👍 👍 👍 👍 

Richard Z. Robinson is gonna get many 🥇
