### ISSUE TITLE
Scanned in structure will not place or start building

### ISSUE THREAD

**Issue by reebcode** [ldtteam/minecolonies#3950]
### Minecolonies version 

Version: 1.12.2-0.10.348-RELEASE

### Expected behavior

- For the building to place and the builder start building it as normal

### Actual behaviour

- Building is not placed or scanned in any way, the tool simply closes and nothing happens.

### Steps to reproduce the problem

1. Scan a structure in singleplayer (in my case it is a large one) that uses mainly chisel and decocraft blocks. Scan it in two halves.
2. Go into multiplayer and build the first half
3.  When the first half is at 100% complete but has blocks you cant obtain in survival, cancel the build through town hall. (In our case the block was double tall ferns).
4. Attempt to build second half of building directly next to first.

Essentially I have a large house that I am attempting to have my builder build on a survival server, I had to split the building into two parts due to its size. The first half worked fine, when I attempt to have the builder start working on the second half, it does not place at all.

**Comment by Raycoms** [comment]
Can you send us the log? And, does the buildtool error or is the problem that the builder doesn't start building?

**Comment by reebcode** [comment]
The only error I get is "CCL Caught an exception rendering a block", when I press the checkmark on the build tool it just exits and nothing happens. 

Maybe this is the problem? Just found it in the logs. Didnt have this problem with any other building though.

[17:15:32] [Client thread/WARN]: BuildTool: server does not have cache/3A74A60B93F952F3480836AE2CEAE256

Here is the full logs https://pastebin.com/P0hUE6H9

The scan file itself is BigHouseLeft2.blueprint

**Comment by Raycoms** [comment]
Ahh, I remember that there was some kind of bug with loading schematics.

**Comment by reebcode** [comment]
> Ahh, I remember that there was some kind of bug with loading schematics.

Any way you know of to fix it?

**Comment by Raycoms** [comment]
I guess your cache is full, go into the cache server folder and empty it.

**Comment by Raycoms** [comment]
![image](https://user-images.githubusercontent.com/6438347/67157979-c1e7e980-f308-11e9-9c10-8e5d8ad41007.png)
