### ISSUE TITLE
Delivery Man don´t work

### ISSUE THREAD

**Issue by Arloma** [ldtteam/minecolonies#3956]
Minecolonies version

Version: minecolonies-1.12.2-0.10.438-Realease-universal
Expected behavior

Delivery Man is supposed to detect Warehouses
Actual behaviour

Unable to find Warehouses and consistently requesting me to build another one or upgrade

**Comment by Raycoms** [comment]
can you send me the world?

**Comment by Raycoms** [comment]
Also, please go to minecolonies-1.12.2-0.10.451-ALPHA-universal.jar

**Comment by Arloma** [comment]
ok

**Comment by Arloma** [comment]
https://workupload.com/file/jwErTDEL

my world

**Comment by Arloma** [comment]
we have 2 colonie 1 work and the other don´t work

**Comment by Arloma** [comment]
minecolonies-1.12.2-0.10.451-ALPHA-universal.jar

dont´work :(

**Comment by Arloma** [comment]
how ca i find them? ftp?

**Comment by Arloma** [comment]
i am a noob by serveraction^^

**Comment by Raycoms** [comment]
https://teamcity.minecolonies.com/guestAuth/repository/download/LetSDevTogether_Minecolonies_Branches_Build/31639:id/build/libs/minecolonies-1.12.2-0.10.1289-PERSONAL-universal.jar

**Comment by Arloma** [comment]
it works big thanks :)
