### ISSUE TITLE
Issue when starting modpack with Minecolonies

### ISSUE THREAD

**Issue by HenrikoMagnifico** [ldtteam/minecolonies#3959]
### Minecolonies version
minecolonies-1.12.2-0.10.438-RELEASE-universal.jar

### Expected behavior
Not crashing the game on boot.

### Actual behaviour
The game crashes when at the Mojang screen.

### Steps to reproduce the problem
Use the Yao Pack modpack version 3.1.10 in Technic Launcher, otherwise I do not know how to reproduce it. Sorry!

Crash log: https://paste.dimdev.org/tihumibuqo.mccrash

**Comment by Asherslab** [comment]
`Maybe try a lower resolution resourcepack?`
says it in the log

If you're not using a resource pack then one of your mods does nasty things to textures

**Comment by HenrikoMagnifico** [comment]
That's what I'm suspecting. I am not the one receiving this error, it's one of the users of my modpack. They've disabled all resource packs but still get the error. Their specs consist of an old i5 and intel hd 620 graphics with 8Gb of DDR3. I am suspecting that's the issue here.

**Comment by Raycoms** [comment]
Yeah their graphics card is too old for that texture we have, I'll scale it down later today when I get home.

**Comment by HenrikoMagnifico** [comment]
Oh wow really? That would be fantastic! :)
