### ISSUE TITLE
Worker requests sometimes not showing up

### ISSUE THREAD

**Issue by Howman** [ldtteam/minecolonies#3969]
### Minecolonies version

Version:  minecolonies-0.10.460-ALPHA-universal

### Expected behavior

Well builders, actually all works and guards should request stuff when then need it  

### Actual behavior

I find that the builders will walk from there hut to there project not doing anything or requesting anything but if you give them the block that's showing in there hand they will work again till the next block which is in there huts inventory  but they will not pull it out .
the guards when you go to requests they will show up then disappear if you wait long enough they will show up the disappear again if you wait even longer you maybe able to give them what they want before it disappears again.
Tried to reset and it will not work 

### Steps to reproduce the problem

  No steps just not working

**Comment by Raycoms** [comment]
OKay, I changed the label to fit it better, do you know a way to reproduce this? This usually works very well for us. Do you have a world where this issue persists over restarts?

**Comment by Howman** [comment]
yes it's I still have that world as it is a lan world I play with my friend. I know it's and alpha and you have not had it for 1.14.4 that long. I be leave this may have shown up 3 or 4 up dates ago. there are also other smaller problems like the builders have started to ware armor unless this is a new behavior this is not normal.
I have to go out here in a bit I will be back after 4:00 pm eastern 
so if you tell me how to send the word and where to send I can do that (Is it just the save you need)
and the lan minecolonies is not working I can have a colony but not my lan friend.
you need log too will that help

**Comment by Raycoms** [comment]
Are you playing in the lan mode? We don't support that. Unfortunately that doesn't work well at all since it changes a lot of the basic premises. If you want to play in LAN mode you should host a real local server and both access it via LAN.

**Comment by Howman** [comment]
oh so the problems are all do to lan so if i move (save) to server or play alone it will be fine?

**Comment by Raycoms** [comment]
It should be yes, I don't have any of these issues.

**Comment by Howman** [comment]
Ok will give a try when i get back home
