### ISSUE TITLE
Builders and Miners getting tired or developing dementia?

### ISSUE THREAD

**Issue by nekatu** [ldtteam/minecolonies#397]
Not sure if this is just an issue with my server, a conflict with other mods, or just an issue with a specific map. Will be able to answer the last one when I start my new map- but thought I'd raise this here anyway.

### Minecolonies version

version 0.6.2114

### Expected behavior

- Queue up activities indefinitely
- Workers complete activities indefinitely
- Profit!

### Actual behaviour

- Queue up activities indefinitely
- Workers complete activities for a few real time hours
- Workers return to their huts or just stand around like they don't know what to do
- Quit game and come back in
- Workers resume activities like nothing happened, for at least a few more hours

### Steps to reproduce the problem

1. Start game
2. Load save
3. Queue activities
4. Workers perform their duties admirably (truly, it's amazing to watch the little devils working)
5. Workers cease activities anywhere from an 1 to 3 hours of game play (not consistent, from what I've seen)
6. Either killing the worker or reloading the save appears to fix it

**Comment by Raycoms** [comment]
Does the problem exist with all workers and can you connect it with daylight cycles? Like after a minecraft night they stop?

**Comment by Raycoms** [comment]
The lumberjack fix should've fixed that one here as well I guess.

**Comment by nekatu** [comment]
This one doesn't appear to have affected the lumberjack, but I suppose he has a different kind of work package? Farmers are likewise unaffected.

Doesn't appear to be related to day/night cycles as they'll leave their huts as normal at the end of the day, return to their huts the next day and then just stand there doing nothing. Seems to be less of an issue with 0.6.2176, but I've only had that for the last few hours.

I've just updated to 0.6.2179 and have my new server running, so we'll see if that irons out the issues I was having with the LAN version.

Will let you know how things go as soon as I have my new town built.

**Comment by Raycoms** [comment]
can you send me the log when that stucking happens?

2017-01-01 14:41 GMT-02:00 nekatu <notifications@github.com>:

**Comment by nekatu** [comment]
sure thing

**Comment by Raycoms** [comment]
if it's only builder and miner it might be something throwing exceptions.

2017-01-01 15:50 GMT-02:00 nekatu <notifications@github.com>:
