### ISSUE TITLE
Miner path issue stuck on loop

### ISSUE THREAD

**Issue by pjradz** [ldtteam/minecolonies#3972]
**Minecolonies version**

Version: 0.10.455-ALPHA

**Expected behavior**

The miner stays down in the mine and mines

**Actual behaviour**

The miner is unable to path correctly if mineshaft has no solid block connecting to platform

**Steps to reproduce the problem**

   1. Have Minecolonies
    2. build mineshaft
    3. wait for mine to get to mine level 2 and wait for miner to dig deeper in mineshaft
    4. Observe the miner looping out of check mineshaft and clear steps.
    5. Add a solid block connecting to said mineshaft then works

note: it gets tedious to always put a solid block for miner to work and not stuck on loop

**Comment by Raycoms** [comment]
can you make a video of this?

**Comment by pjradz** [comment]
Where or how will i upload it, ill record it after i wake up pretty late in night on my end

**Comment by Raycoms** [comment]
just put it on youtube or google drive and link it here

**Comment by pjradz** [comment]
https://drive.google.com/file/d/1VXbJGMDm4kHIExGae5HwV7ptj5xreJdJ/view?usp=sharing

**Comment by Raycoms** [comment]
Ahhhh, this is a schematic, issue from 1.12 to 1.14, in due time we'll rescan those shafts and make them work again =D

**Comment by pjradz** [comment]
Nice! glad to hear it.
