### ISSUE TITLE
Building tool doesn't render cobble walls

### ISSUE THREAD

**Issue by Insane96** [ldtteam/minecolonies#3977]
Version: minecolonies-0.10.465-ALPHA

### Expected behavior
The building tool ghost blocks don't render walls (maybe some other blocks)

### Actual behaviour
Render Walls 

### Steps to reproduce the problem
Try to place a Lumberjack dwarves level 1 building.

**Comment by Asherslab** [comment]
Not sure what you’re talking about, please provide images and clarify your issue

**Comment by Raycoms** [comment]
Okay, I double checked, this is an issue from 1.12 to 1.14.
We will rescan those soon so they will show again in the build tool.
