### ISSUE TITLE
Lumberjack text and odd chest behaviour

### ISSUE THREAD

**Issue by nekatu** [ldtteam/minecolonies#398]
### Minecolonies version

version 0.6.2114 (same with a few of the previous versions that I've tested too)

### Expected behavior

Issue 1: Lumberjack reports specific type of axe needed
Issue 2: Lumberjack fills his chest until it's full and goes on his way

### Actual behaviour

Issue 1: Lumberjack reports he requires an axe with "a maximum grade of ."
Issue 2: Lumberjack fills his chest until it's full and goes on his way for a few hours of real time and starts reporting that the chest needs emptying, even if it's empty and he only has a single item in his inventory (other than his axe)

### Steps to reproduce the problem

Issue 1: Occurs all the time, nothing needed to reproduce- maybe a type in the Lumberjack's lookup or something like that? (not a programmer, just an IT guy)

Issue 2:

1. Load save
2. Play as normal for a few hours
3. Lumberjack reports that chest is full and he can't dump his inventory
4. Removing all items from the chest makes no difference, removing any single item/stack from the Lumberjack's inventory allows him to continue, or just quitting and reloading the game works too.

**Comment by nojo121** [comment]
Issue 1: It's not a bug it's a feature! To use better tools you have to upgrade the worker.
Issue 2: @Raycoms u know a fix?

**Comment by Raycoms** [comment]
No,  couldn't even reproduce it yet

Am Samstag, 31. Dezember 2016 schrieb nojo121 :

**Comment by nekatu** [comment]
For clarity sake: Issue 1-
![2017-01-01_01 41 43](https://cloud.githubusercontent.com/assets/1908371/21579916/a336794a-cfc3-11e6-9db5-3b52f0d3eadd.png)
It doesn't actually tell you what grade he needs- and the building is level 5 so can't be upgraded any further. It's shown the same message through all levels and across the last 4 builds of the mod that I've tried.

Issue 2-
Message:
![2017-01-01_01 45 29](https://cloud.githubusercontent.com/assets/1908371/21579919/1cd759e0-cfc4-11e6-9474-aea96d9859af.png)

LumberJack's Inventory:
![2017-01-01_01 42 12](https://cloud.githubusercontent.com/assets/1908371/21579920/2e0a9380-cfc4-11e6-840d-2c0ef9c33568.png)

Lumberjack Chest:
![2017-01-01_01 42 08](https://cloud.githubusercontent.com/assets/1908371/21579921/376d968e-cfc4-11e6-8d67-cf9c89e83879.png)

As you can see, plenty of space in both inventory and chest. Clearing the chest makes no difference, but taking a single stack of items from the his inventory sends him on his way, for a while at least.

**Comment by nekatu** [comment]
I thought it may be that there weren't enough free blocks for him to fully unload his inventory, but clearing addition space still leaves him with at least 2 items/stacks in his inventory and he won't go back to work until one of those two is manually removed from his inventory.

**Comment by Raycoms** [comment]
I found the bug and fixed it, the next 1.11 will be without it.

**Comment by nekatu** [comment]
Thanks- I've updated to 0.6.2179 and will let you know how things go as soon as I have my new town built.
