### ISSUE TITLE
Two in the door will not fit

### ISSUE THREAD

**Issue by slowiu06** [ldtteam/minecolonies#3982]
I can commonly see my workers stucks at doors/ladders when they both want to use it. Maybe they should be like ghosts to each other (to let them move thru)?

**Comment by Raycoms** [comment]
Improved the stuck radius, eventually they detect they're stuck and one will give up

**Comment by slowiu06** [comment]
They are still having problems with ladders
![2019-11-11_14 19 36](https://user-images.githubusercontent.com/7887594/68590353-97fc8f80-048e-11ea-8e9d-2788ab3c3333.png)

**Comment by Raycoms** [comment]
Eventually they should clear that up, do they get stuck forever or do they solve this after a few minutes?

**Comment by slowiu06** [comment]
After night they usually came back to normal. I solved this temporary by removing some wood planks around ladder.

**Comment by Raycoms** [comment]
They have some code to break free, but maybe that doesn't work on a ladder, I can check on this these days.
