### ISSUE TITLE
Lumberjack ignores trees in specific build

### ISSUE THREAD

**Issue by pjradz** [ldtteam/minecolonies#3983]
Version:  0.10.465-ALPHA

Expected behavior
- Lumberjack chops down tree near him/her

Actual behaviour
- Lumberjack seeks out further trees to chop down

Steps to reproduce the problem
1. build "Sandstone type lumberjack"
2. grow trees on built dirt
3. lumberjack seeks other trees far away
4. ... Profit

![2019-10-25_23 40 34](https://user-images.githubusercontent.com/50167018/67584784-ea486b80-f780-11e9-8915-2847451dd00a.png)

*note: i tried this with acacia & stone type both work fine, only the sandstone type lumberjack has a problem on trees planted on it.

**Comment by Raycoms** [comment]
yes, the lumberjack doesn't recognize trees in his building because we wanted to avoid him cutting down buildings. It's on purpose. (We have to update the schematic though)
