### ISSUE TITLE
Everything is not clickleable anymore. Neither Villagers or Buildings

### ISSUE THREAD

**Issue by JensBue** [ldtteam/minecolonies#3988]
### Minecolonies version
I've played succesfully for several Days with:
MineColonies 0.10.448-BETA
Forge 1.14.4-28.1.65
Structurize 0.10.193-ALPHA
(No other mods installed!)

After issue i tried to update everything. Now using:
MineColonies 0.10.480-ALPHA
Forge 1.14.4-28.1.69
Structurize 0.10.194-ALPHA

### What would you expect to see if this feature was working as intended?
Right-Click on villagers or Building-Blocks opens the menu where you can interact with them.
Holding the 'Building Wand' shows border of the village.

### What actually happens when this feature is used in it's current state
Right-Click does nothing. No menu, any interaction, lags or crashes. Just nothing happens.
Holding the 'Building Wand' shows no border of the village. Right-Click is working but placing of decoration does not work. Nothing happens when clicking the green check mark. (The preview disappear like normal, but nothing gets placed)
Vanilla MC blocks (chests, oven, ...) still working fine.

### What should we do to make this issue show up in our own game?

I honestly don't know how to reproduce it. I've tried with a new world and it doesn't let me place the supply camp or ship. Preview is shown, but clicking on the green check mark does not place anything.

**Comment by Raycoms** [comment]
I have to try on newer forge versions.

**Comment by Raycoms** [comment]
did you try the loadbackup command?

**Comment by JensBue** [comment]
Tried the loadbackup command.
It's working now! Thanks for the hint. Didn't know there was such a thing.

**Comment by Raycoms** [comment]
=D

Sometimes minecraft loses data from the world, that's why we left it in =D
