### ISSUE TITLE
Level 5 Citizen House allows Citizens to climb onto the roof

### ISSUE THREAD

**Issue by nekatu** [ldtteam/minecolonies#399]
### Minecolonies version

version 0.6.2114

### Expected behavior

- Citizens obey health and safety rules and do not scale the building

### Actual behaviour

- Citizens join circus and perform death defying feats of monumental stupidity

### Notes

Just a minor note in the design of the Citizen houses- there's a wood block between the roof (stair) blocks and the iron bars that allows citizens to jump up and either walk along the iron bars or up onto the roof. My 11 year old was convinced that "Charlotte P. Mardle" was about to jump and started trying to talk her down... kids, eh? ;-)

To solve this I've just removed the wooden block and added another iron bar in its place. No more circus acts here- at least until you guys develop a circus tent! ;-)

**Comment by Raycoms** [comment]
@pmardle can you fix that?

**Comment by nekatu** [comment]
Seems to happen on the new Town Hall Level 5 too, and even with my block fix still occasionally happens on the Level 5 houses. Seems to be the combo of stairs and iron bars that allows NPCs and players to circumvent the 1.5 block height of the iron bar and scale the rest of the building.

**Comment by nekatu** [comment]
Wondered where all my citizens were hiding... found them partying on the roof! ;-)
![2017-01-02_13 54 06](https://cloud.githubusercontent.com/assets/1908371/21590371/2deb225e-d0f3-11e6-91b8-cccebca91c40.png)

**Comment by pmardle** [comment]
lol :)

yeah will have a crack at it :)

**Comment by pmardle** [comment]
Its because the iron bars are only 1 block high not 1.5 as per the fences

Might have to change all iron bars to fences, which is a shame

**Comment by nekatu** [comment]
Could you tweak the iron bars to use the same settings as a fence?
Or create a Mine Colonies copy that is 1.5?

I love the iron bar look too and wouldn't want to see that change if possible.
