### ISSUE TITLE
0.10.472 Dedicated Server Crash NPE while ticking BE

### ISSUE THREAD

**Issue by kreezxil** [ldtteam/minecolonies#3992]
## mod version
1.14.4-0.10.472-RELEASE
## forge
1.14.4-28.1.69

## Crash Reports
crash-2019-10-27_07.45.13-server.txt http://paste.ubuntu.com/p/bswFVVJgvM/
crash-2019-10-27_12.43.34-server.txt http://paste.ubuntu.com/p/KqgFCyn5JN/
crash-2019-10-27_13.01.17-server.txt http://paste.ubuntu.com/p/sXFZ3GQF2F/

## Additional Logs
2019-10-27-1.log http://paste.ubuntu.com/
2019-10-27-2.log http://paste.ubuntu.com/p/vcprzmGNGY/
2019-10-27-3.log http://paste.ubuntu.com/p/d5bgXF2R2J/
debug-1.log http://paste.ubuntu.com/p/27Jkhkb8MP/
debug-2.log http://paste.ubuntu.com/
debug.log http://paste.ubuntu.com/p/SNt4NpNpmt/
latest.log http://paste.ubuntu.com/p/fb8tbSSsGK/

**Comment by Raycoms** [comment]
fixed
