### ISSUE TITLE
Smeltery

### ISSUE THREAD

**Issue by Daydreamer78** [ldtteam/minecolonies#3996]
### Minecolonies 1.1 server

Version: 

### Expected behavior
not sure first time with smelter

- 

### Actual behaviour

- 
smelter smelts fine but when he grabs the finished product and brings it inside it disappears

### Steps to reproduce the problem

1. have him smelt
2. watch furnace is done smelting
3. he goes inside and bars arent in his or smeltery invetory
4. ... Profit

**Comment by Raycoms** [comment]
Check out the other chests and racks in the building.
