### ISSUE TITLE
Miller wont stop produce the requested item.

### ISSUE THREAD

**Issue by Nightmare4k** [ldtteam/minecolonies#3998]
### Minecolonies version

Version: 1.15 "Life in village"

### Expected behavior

- Miller only produce the requested amount.

### Actual behaviour

- Miller keep producing non stop the requested item, and none of the produced item will be given away to the builder.

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit

**Comment by Raycoms** [comment]
The sawmill you mean?

**Comment by Raycoms** [comment]
can you look in the request tab? in the clipboard? Does it say some crazy amount? If so, cancel the request, that should fix it

**Comment by Nightmare4k** [comment]
Hi after i started the game it all was in perfekt order???
But how can i solve this next time?

**Comment by Raycoms** [comment]
./mc rs reset colony: id
