### ISSUE TITLE
[Request] Show other boundries while placing buildings

### ISSUE THREAD

**Issue by MrGrim48** [ldtteam/minecolonies#3999]
Currently only the boundary of the building being placed is shown (That I'm aware of).
I've found this can make it difficult to prevent overlapping of buildings.

Allowing the boundaries of nearby buildings to be visible either with the building tool in hand or while placing buildings could help with this issue.

**Comment by Raycoms** [comment]
For now you can click repair to show the outlining of the construction tape.
But yeah it's planned.

**Comment by Raycoms** [comment]
Closed in favor of joint issue.
