### ISSUE TITLE
SUGGESTION: Interaction with other mods and other functionality

### ISSUE THREAD

**Issue by nekatu** [ldtteam/minecolonies#400]
Just a few general thoughts from the last few days of playing with this and other mods- coming from an IT support background I don't usually like putting loads of different things into a single ticket, but I also don't want to bombard you with emails and tickets... ;-)

**CITIZENS**

I love the building aspect of this mod and the "life" that it brings to the game with NPCs running around like they actually have something to do. The citizens themselves though do feel a little basic and lacking in personality.

I've seen it suggested a few times now that players should have the ability to edit the citizens- maybe something similar to the way the Custom NPCs mod works? A dedicated wand that you can bring up a list of all your NPCs and change their names, sounds, textures, and even the dialog options that are available for interaction. They also have a load of roles/jobs that could be fun to weave into your mod; some that cross over like the Guard and Builder, but additional ones like the Mailman and Follower/Companion that could really breathe more life into the game with your excellent colony systems.

A lot of that is likely already in the pipeline, I'm sure- but thought I'd raise it as the Custom NPC guys have already done the hard work so maybe a collaboration? Speaking of the Builder, they also do buildings, but the system is so complex I'm not sure many people bother- so having their NPC interaction with your mod, and your superior building system with theirs would be a killer combo.

Further to the mention of the Follower/Companion roles, interaction with the questing and faction aspects of Custom NPCs would be amazing. Their system is a little clunky, but would add a whole new level to your mod if you could hire citizens as followers, complete quests for them, or just generally engage them in conversations.

**VILLAGERS**

I noticed a forum post a while back about whether citizens would effectively be replacing standard villagers or if there would be any plans for interaction between them. I'd love to see this, but at the very least I think having the villagers look a little more like your citizens would help with the immersion. 

The closest I've found to this is Stevian Villagers, which hasn't been developed much in recent years but still works with the new versions of Minecraft and has an almost identical design to your NPCs, so despite the lack of names at least my cities and towns have a consistent looking populous. 

Maybe looking to replace the built in villagers completely when your trading system comes in, or at least just overhauling their look and ideally sounds would be possible?

**MINING**

I really love the art style and the way the miner works, though it doesn't seem like they are able to recognise non-standard ores, but that could just be some of the specific ores in my game. The Farmer is able to plant any seed from what I've seen, but the miner only appears to collect original minecraft ores. Something to do with ore-dict support or something like that, maybe? Though it could just be that some of the ores I have don't have ore-dict support if your mod does...

**GUARDS**

Guards and, more specifically, weapons spring to mind. I have crossbows in the game and it would be great if the rangers could make use of these as well as bows. Likewise for the plethora of other weapons mods other there it would be amazing to see the guards sporting a little more diversity in their tools of death. Armour seems to work great, though I think they should be able to pick that up from their chest as well rather than having to have it put into their inventory directly.

**CITY MANAGEMENT**

Something you've possibly already got on the list, but having the list of citizens in the Townhall show you what their current job is and even the ability to TP to them would be really handy. 

Being able to centrally manage the queues/jobs/activities of all the workers from the townhall would be great too- or at least to get an overview of what level the miner is working on, what farmers are planting in what field, etc without having to go to each shop would be great too. 

Linking back to the citizen editing, this would also be somewhere that you could edit the NPCs from to bring up a Custom NPC style editing window.

**Comment by Raycoms** [comment]
The miner should recognize all ores which are defined as ore in the code.
If the mod developers don't use the minecraft ore classes it unfortunately
won't work.  Would be nice to know which he doesn't recognize to fix that
in the future.
We ate planning on a huge amount of additional workers but need a lot more
people to realize this.

Am Samstag, 31. Dezember 2016 schrieb nekatu :

**Comment by marvin-bitterlich** [comment]
Closing this as too broad…
@nekatu please open one issue per problem
