### ISSUE TITLE
All of the cactus blocks are missing from the sawmill

### ISSUE THREAD

**Issue by oldjollysanta** [ldtteam/minecolonies#4000]
### Minecolonies version

Version: minecolonies-0.10.465-ALPHA-universal

### Expected behavior

- Being able to add recipes for: Cactus planks and all cactus related blocks (Stairs, slabs, fences, doors, etc)

### Actual behaviour

- Met with error message: _Unable to store the blueprint. Either the sawmill has no space for any more blueprints, or the blueprint doesn't correspond with its profession._

### Steps to reproduce the problem

1. Teach recipe on sawmill hut block
2. Add recipe for any cactus block
3. Failed result

---

Also missing is the the iron ingot (from Iron nuggets) recipe from the blacksmith 
^ would be very useful with the sifter

**Comment by RyTechro** [comment]
Underling issue is that cactus and cactus planks are not tagged with ItemTags.Logs and ItemTags.Planks

**Comment by RyTechro** [comment]
@Raycoms this issue can be closed. To get these changes the structurize update needs to roll out if it hasn't already

**Comment by Raycoms** [comment]
Rolled out already
