### ISSUE TITLE
Level 3 stone mason (sandstone) requiring 6 infested chiseled stone bricks

### ISSUE THREAD

**Issue by oldjollysanta** [ldtteam/minecolonies#4001]
### Minecolonies version

Version: minecolonies-0.10.465-ALPHA-universal

### Expected behavior

![Screenshot 2019-10-29 13 22 49](https://user-images.githubusercontent.com/1407323/67735781-ee121180-fa50-11e9-8071-23034e5c71a2.png)
- Is this a mistake? Seems like a rather impossible find for a lower level building..

### Actual behaviour

- 

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit

**Comment by Raycoms** [comment]
@lunadragnstar 

it's a mistake

**Comment by lunadragnstar** [comment]
Fixed.
