### ISSUE TITLE
Blacksmith not working

### ISSUE THREAD

**Issue by Nightmare4k** [ldtteam/minecolonies#4003]
### Minecolonies version

Version:  Life in village 1.15

### Expected behavior

- When worker request at tool the blacksmith should start make the tool,

### Actual behaviour

- The blacksmith do nothing he have the recipe and everything. 

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit

**Comment by Raycoms** [comment]
What minecolonies version is this?

**Comment by Nightmare4k** [comment]
V. 1.12.2-0.10.438-Relea

**Comment by Raycoms** [comment]
can you update and test if it works then?

**Comment by Nightmare4k** [comment]
Hi Raycoms

Have updated to 471-RELEASE

And i have the same problem.

**Comment by Raycoms** [comment]
Did you reset your request system since the update? /mc colony rs reset

**Comment by Raycoms** [comment]
What do you mean exactly with not working? What are you trying to do, and what is it doing?

**Comment by Nightmare4k** [comment]
I have done a /mc colony rs reset
But same problem

**Comment by Nightmare4k** [comment]
When the worker request a tool, the blacksmith does nothing?
But when i request the same tool from the postbox i can see the request system need iron and stick
But the blacksmith never make the tool.

**Comment by Raycoms** [comment]
Okay, I found out what is causing this, I will find a better way to handle this.
