### ISSUE TITLE
Ticking Entity Error - Builders

### ISSUE THREAD

**Issue by CmdrStormpilot** [ldtteam/minecolonies#4008]
### Minecolonies version
 

Version: 0.10.465-ALPHA

### Expected behavior

- 
The builders would complete a build request as normal with the resources given to them in their inventory OR with unlimited resources per configuration.

### Actual behaviour

- 
Server crashing due to Ticking Entity error when builders are building certain buildings or upgrading them. Issue has been seen with Oak Stonesmelter Level 5, Medieval Oak Cook Level 4, and others. Multiple builders have experienced the issue. I've attempted to teach builders the recipes, but builders only have a 2x2 crafting screen. Issue occurs even when the "BuilderInfiniteResources" modifier is set to True so they don't have to craft anything. Even if the builders have no resources, something is causing the crash before I can get to them to resolve their request and I don't know what it is or how to fix it.

[crash-2019-10-30_09.07.12-server.txt](https://github.com/ldtteam/minecolonies/files/3789678/crash-2019-10-30_09.07.12-server.txt)
[crash-2019-10-30_09.08.14-server.txt](https://github.com/ldtteam/minecolonies/files/3789679/crash-2019-10-30_09.08.14-server.txt)
[crash-2019-10-30_10.41.22-server.txt](https://github.com/ldtteam/minecolonies/files/3789680/crash-2019-10-30_10.41.22-server.txt)
[crash-2019-10-30_10.43.53-server.txt](https://github.com/ldtteam/minecolonies/files/3789681/crash-2019-10-30_10.43.53-server.txt)
[crash-2019-10-30_10.44.53-server.txt](https://github.com/ldtteam/minecolonies/files/3789682/crash-2019-10-30_10.44.53-server.txt)
[crash-2019-10-30_10.46.45-server.txt](https://github.com/ldtteam/minecolonies/files/3789683/crash-2019-10-30_10.46.45-server.txt)
[crash-2019-10-30_10.49.26-server.txt](https://github.com/ldtteam/minecolonies/files/3789684/crash-2019-10-30_10.49.26-server.txt)
[crash-2019-10-30_10.50.27-server.txt](https://github.com/ldtteam/minecolonies/files/3789685/crash-2019-10-30_10.50.27-server.txt)
[crash-2019-10-30_10.51.34-server.txt](https://github.com/ldtteam/minecolonies/files/3789686/crash-2019-10-30_10.51.34-server.txt)

### Steps to reproduce the problem

1.   Set BuilderInfiniteResources to True, or be sure to give enough of each resource required for the job into the builder's inventory
2.  Build the Wooden Stonemason to Level 5, the MedievalOak Cook to Level 4
3.  StackOverflow will crash the server when the builder's entity creates a Ticking Entity error.
4. ... Profit

**Comment by Raycoms** [comment]
This was fixed in newer versions of minecolonies/structurize, please update

**Comment by CmdrStormpilot** [comment]
Updated to 0.10.472-ALPHA and had the same issue. In this attempt I had BuilderInfiniteResources True, and the builder did not even get all the way to her Hut after the request was made before the game crashed.

[crash-2019-10-30_11.48.57-server.txt](https://github.com/ldtteam/minecolonies/files/3789889/crash-2019-10-30_11.48.57-server.txt)

**Comment by Raycoms** [comment]
urgs, found and fixed, version will be out within the next 20 minutes

**Comment by CmdrStormpilot** [comment]
great, thanks!

**Comment by CmdrStormpilot** [comment]
It works perfectly now, thank you so much! This mod revitalized minecraft for my group of friends.
