### ISSUE TITLE
Citizen pathing / orgies...

### ISSUE THREAD

**Issue by nekatu** [ldtteam/minecolonies#401]
Just a quick note that from time to time we I seem to have Guards (and other citizens) bunching up against a wall or in a doorway. I'm not one to judge, but I'm pretty sure that's not acceptable behaviour in public... ;-)

![2016-12-31_13 04 42](https://cloud.githubusercontent.com/assets/1908371/21577645/373b8f96-cf5a-11e6-8e73-7d05a93348a8.png)

As a side note, Citizens also appear to have issues with any objects on the ground, such as the rocks added by the Actually Additions mods. When they encounter these in their path they stand there spinning for 10-15 seconds and then work out how to move around them. Not a major issue, just something to note.

![2016-12-31_13 17 04](https://cloud.githubusercontent.com/assets/1908371/21577675/80af1476-cf5b-11e6-8489-5c8b0be9c6d4.png)

### Minecolonies version

version 0.6.2114

### Expected behavior

- Citizens respect personal space

### Actual behaviour

- Citizens get up in each other's grills

### Steps to reproduce the problem

1. Load game
2. Set guards to patrol (or just wait for night time)
3. Watch the Citizens grind
4. Feel strangely dirty for taking a screenshot...

With specific regard to the Guards, if you go to their towers and recall them then it seems to fix it for a while, but it's not long until they all end up in a bundle again. Guess they just can't fight those urges, or it's a survival technique to stay warm... ;-)

**Comment by Raycoms** [comment]
I've actually never seen that happen.
Minecraft pathfinding ist doing strange stuff sometimes.  We should give
that a little rework again,  when we get time.

Am Samstag, 31. Dezember 2016 schrieb nekatu :

**Comment by Raycoms** [comment]
The 2nd one is pretty normal. We have a list of items they can't cross, if they try to cross others this behavior might happen.
The first one, is there a way to guaranteed reproduce it.

**Comment by nekatu** [comment]
Will let you know on the 1st on as soon as we have guard towers on the new server.
