### ISSUE TITLE
StringBuilder StackOverflowError Crashing Game

### ISSUE THREAD

**Issue by nephatrine** [ldtteam/minecolonies#4014]
I left my colony to do some exploring while my builders are working and when I tried coming back to base my server crashed. Upon restarting and joining again, it still crashes the server when I get near my colony after the chat shows the builders resume their work.

https://pastebin.com/ZHpG7Lm3

### Minecolonies Versions

Tried both of these:

- minecolonies-1.12.2-0.10.488-RELEASE-universal.jar
- minecolonies-1.12.2-0.10.499-ALPHA-universal.jar

### Expected behavior

No crash to occur.

### Actual behaviour

Crashes game.

### Steps to reproduce the problem

No idea tbh. It looks like some issue with the warehouse resolving, but I don't know what specifically is being requested to cause the issue since it crashes before I can get to the builders and check. It's a lvl3 nordic warehouse. I've got one lvl3 nordic builder working on upgrading my nordic town hall to lvl3. The other builder is a lvl2 dwarven builder who is currently upgrading himself to lvl3.

The last time I was able to check on them, the lvl2 builder was trying to get 88 birch planks from the warehouse and some birch stairs from my sawmill crafter. No idea what the other might have been working on.

Hopefully the crash log illuminates what could be the cause.

**Comment by Raycoms** [comment]
can you send us the world?

**Comment by nephatrine** [comment]
Since it takes a moment for the builders to resume work once the chunks are loaded, I've been able to inch my way into the colony. It seems to crash shortly after the builder gets back to work on builder3, but I can't see anything in the request window before it crashes so I guess it's as soon as he requests it that it happens. I've managed to cancel the upgrade prior to it crashing and that stops it from crashing... but if I ask it to upgrade again it crashes again so it looks like I'll just leave it at lvl2 or change it to a different theme in the meantime to hopefully avoid whatever it causing it.

I've taken the world prior to me cancelling the request though and it's zipped up [here](https://br0wnbr1x.nephatrine.net/world.7z) for now. We're using [JustEnoughIDs](https://www.curseforge.com/minecraft/mc-mods/jeid) so I don't think you'll be able to load it without that since it changes the chunk format.

The builder in question is located at -282,-55.

**Comment by Raycoms** [comment]
do you have any crafter workers?

**Comment by nephatrine** [comment]
Just the sawmill. It's got all 10 blueprint slots filled with recipes for vanilla planks, stairs, and fences. Some of those recipes are adjusted by mods, but none of the items are mod-added ones.

**Comment by nephatrine** [comment]
So based on your question, I have removed the recipes from my sawmill and restarted the builder upgrade... and it seems to have resolved it though I had to craft a bunch of birch planks myself. I think maybe the issue could be that the recipes were to convert back and forth between planks and stairs so maybe it was getting into an infinite loop needing more stairs to craft more planks but needing more planks to craft the stairs, etc.?

**Comment by Raycoms** [comment]
do you have a circular recipe? That probably caused it! But since I have the world I can check if I can detect this better in the future.
