### ISSUE TITLE
Crash related to sleeping habits of (ghostly) colonists

### ISSUE THREAD

**Issue by L0neGamer** [ldtteam/minecolonies#4015]
### Minecolonies version

Version: 0.10.493-RELEASE

### Expected behavior

Not crashing; 
possibly citizens being able to sleep?

### Actual behaviour

Shortly after loading into the world the only player on the server with a Minecolony crashed, giving me his crashlog ([linked here](https://pastebin.com/8g00gvMx)).

Reading it, it seems to be something to do with a citizen's sleeping habits.

(possibyl unrelated is that all his citizens look like [this](https://imgur.com/a/UUBusRD), but they work as usual)

### Steps to reproduce the problem
I've got nothing, sorry.

**Comment by someaddons** [comment]
you're launching with a too old java version: 1.8.0_51
try updating it pls, you can find a new one here: https://adoptopenjdk.net/

**Comment by ozBillo** [comment]
I'm also seeing ghostly citizens with the 1.12.2 version. Is it a Halloween thing?
Java 1.8.0_231-b11
minecolonies-1.12.2-0.10.488-RELEASE-universal

**Comment by Asherslab** [comment]
halloweeen
