### ISSUE TITLE
Scan tool buildings don't "join up" elements

### ISSUE THREAD

**Issue by nekatu** [ldtteam/minecolonies#402]
### Minecolonies version

version 0.6.2114

### Expected behavior

- Scan an amazing building or decoration
- Rename NBT schematic in scans folder to preferred name
- Copy NBT schematic into decorations folder
- Quit and reload game
- Build new schematic
- Profit!

### Actual behaviour

- Scan an amazing building or decoration
- Rename NBT schematic in scans folder to preferred name
- Copy NBT schematic into decorations folder
- Quit and reload game
- Build new schematic
- Weep...
- Remove and replace fence posts (from original game), benches (from mods), etc
- Profit!

### Steps to reproduce the problem

As above.

Have to say, I really love the scan tool; such an ingenious way of adding new schematics to your excellent build system (should really be somewhere we can share our designs- provided they're not copies of other people's work...) but it does seem to be a little buggy on blocks that join up with each other after placement or otherwise change state based on their environment. 

I'm no programmer so not sure what's involved there, but some kind of block state check/update after placement seems to be needed as per the way a player would place a block.

**Comment by marvin-bitterlich** [comment]
This is a vanilla mc bug as we are using their rendering. I guess it would have cost too much cpu

**Comment by nekatu** [comment]
Noted, thanks @Kostronor
