### ISSUE TITLE
Sandstone buildings missing floors

### ISSUE THREAD

**Issue by oldjollysanta** [ldtteam/minecolonies#4026]
### Minecolonies version

Version: minecolonies-0.10.493-RELEASE-universal

### Expected behavior

- Sandstone buildings should have floors (2nd floors)

### Actual behaviour

- Multiple buildings are missing floors (eg: sandstone mines, Sandstone library)
![Screenshot 2019-11-03 15 01 13](https://user-images.githubusercontent.com/1407323/68080645-49764200-fe4b-11e9-8122-6ade227e20da.png)

My guess is it is cactus half slabs that are meant to be used, but did not get saved in the schematics.

### Steps to reproduce the problem

1. Build Sandstone Library
2. Upgrade to level 2

Or:
1. Build a sandstone mine
2. Wait for miner to start mining on any level. (Cactus fences will be placed, but floor will be missing)

**Comment by oldjollysanta** [comment]
Cactus half slabs seem to be missing from all buildings

**Comment by lunadragnstar** [comment]
We are still working on fixing the schematics for 1.14
