### ISSUE TITLE
SUGGESTION: Assign Lumberjack to seek out specific types of wood

### ISSUE THREAD

**Issue by nekatu** [ldtteam/minecolonies#403]
Just a quick one, would be great if we could tell the Lumberjack what wood to harvest, similar to the mechanic used by the Farmer to plant specific seed. If no preference is made then the Lumberjack could continue as normal, harvesting whatever he finds, but if you're working on a specific building or have a need for a specific material it would be really helpful if you could just tell them to find you the relevant woods.

In some respects you could potentially do the same for the stone mason and possibly even the miner- or least have another worker at the mine who specialising in excavating of specific ores while the other miner specialises in construction.

**Comment by Raycoms** [comment]
We actually have that planned for the lumberjack,  we even have an issue
for that

Am Samstag, 31. Dezember 2016 schrieb nekatu :
