### ISSUE TITLE
How do I update minecolonies to a newer version ?

### ISSUE THREAD

**Issue by Ibis21** [ldtteam/minecolonies#4034]
### Minecolonies version

Version: minecolonies-0.10.415-ALPHA-universal

### Expected behavior

- 
Hey, have searched all over the web but have not found anything on how to update the mod. Have tried to download the latest version (0.10.493) and overwrite the old one, unsuccessfully.

### Actual behaviour

- 

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit

**Comment by Raycoms** [comment]
What is the issue you are having with this?
Why didn't the replacing one work?

**Comment by Ibis21** [comment]
Hey, sorry my bad. Forge just needed to be updated 

but thanks for the quick reply
