### ISSUE TITLE
Citizens jobs list starts adding blank rows

### ISSUE THREAD

**Issue by MrGrim48** [ldtteam/minecolonies#4037]
### Minecolonies version

Version: 1.12.2-0.10.488-RELEASE-universal

### Expected behavior

- Lists all occupied jobs regardless of amount.

### Actual behaviour

- Lists occupied jobs up to a certain point.
- Beyond that point blank lines are added.

![BlankJobs](https://user-images.githubusercontent.com/1344461/68170403-7c980d00-ffd4-11e9-97da-f2fe87d345c4.png)

### Steps to reproduce the problem

1. Provide many jobs. (a little more than enough to have a scroll bar)
2. ... Profit

**Comment by MrGrim48** [comment]
Likely similar issue #3993

**Comment by Raycoms** [comment]
Should be fixed now.
