### ISSUE TITLE
[A Life in the Village] Raids spamming "Enemies Left" messages & incorrectly. 

### ISSUE THREAD

**Issue by Caferino** [ldtteam/minecolonies#4039]
### Minecolonies version

Version: 1.16 (most recent release as to 4 Nov 2019)

### Expected behavior

- If x Barbarians are attacking my village; I should see the "Enemies Left" counter go down from x to successful defend appropriately. 

### Actual behaviour

- The counter instead spams dozens of times incorrect amounts of enemies left, even when none have been killed or spawned yet. Noticeably seen that the counter doesn't go beyond 5 enemies either, it goes from 5 enemies left to 4, 3... "success defend" which randomly loops aswell and the enemies counter also resets randomly. It becomes heavily spammy, looping from 5 down to "Successfully defending the colony" when it actually is still under attack. The only fix is to kill all the barbarians as soon as possible. 

### Steps to reproduce the problem

1. Haven't done anything unusual. 
2. Installed A Life in the Village modpack 1.16.
3. Play closely to vanilla, bug will happen. Build village in a snow biome really close to a Millenaire village. 
4. ... Execute a raid.

I know A Life in the Village contains a bunch of mods, however, they should be compatible with your mod. Not sure if the bug happens stand alone, it might, I can't see what could conflict with the raids.

**Comment by Asherslab** [comment]
`Version: 1.16`
that's not a minecolonies version, please provide the actual minecolonies version

**Comment by Raycoms** [comment]
Duplicate issue, we're aware and working on it @Shanseala
