### ISSUE TITLE
[Feature] Gravestones

### ISSUE THREAD

**Issue by nekatu** [ldtteam/minecolonies#404]
One of my favourite mods, Gravestone Mod, solves an issue I've always had on my private server in that users hate losing their stuff when they die, but adding the keepInventory rule breaks immersion and takes the risk out of dying.

Having something similar for Citizens, either in the form of an actual graveyard, or like the mod, a grave that appears wherever they were when they died with access to the items they were carrying would be amazing and definitely add immersion to the game.

If you did go for the graveyard idea, you could stick a zombie spawner in there too... ;-)

**Comment by kedamono** [comment]
A graveyard hut would be nice. Make them tiered so it goes from wooden crosses up to mausoleums.

**Comment by nekatu** [comment]
If you're like me and build you colonies around existing villages then it could be a nice touch having it off the back/side of the Church...

![2016-12-31_16 05 18](https://cloud.githubusercontent.com/assets/1908371/21578303/f34c8100-cf72-11e6-86a5-7b55dc1e1407.png)

**Comment by Raycoms** [comment]
Would be an interesting worker,  we will think about it.
But as always,  we need more coders xD

Am Samstag, 31. Dezember 2016 schrieb nekatu :

**Comment by Gohu29** [comment]
Same problem here.
Another solution would be to be able to add the names of some blocks that players can place and break even when they are not allowed.

**Comment by xavierh** [comment]
I really like the idea.
Would be nice to have a church + cemetery as 1 building. Levelling up the church would provide more space in the cemetery. Maybe the church could have a positive impact on the citizens somehow ?

**Comment by AndrewTru** [comment]
@xavierh , I am with you there, if you do that the code is less as well.
I think if you make a 'timeframe' so like if the world starts a day 0 every 7 days they go to the church and 'study' something in order for them to be happy.
The graves will have all the items that a dearly departed had on them at the time, but what if we have a limiter in place so something like [Grave][Grass][Grave]. that's just my two cents on the matter.

**Comment by xavierh** [comment]
I was thinking about it the other day. Each level could have a certain amount of grave (empty).
When a colonist die, the player could choose or not to bury him:

- An empty grave would be use, where the name of the colonist would be written
- The level of a **buried** citizen would be preserved and use for the next citizen.

In other words, this would allow to save the citizen level instead of loosing it, but only if we still have room in the cemetery

**Comment by AndrewTru** [comment]
it's a start, @Kostronor what's your take on all of this?

**Comment by Wissi** [comment]
I thik it's a great idea. It should have levels as well as the other buildings and at level 5 should have enough gravesites for at least 50 Citizens as well. maybe even in a tiered/layered graves (by floors or subfloors) so as not to create a large footprint just for that.

**Comment by Raycoms** [comment]
Closed in favor of joint issue.
