### ISSUE TITLE
Deliveryman's gluttony

### ISSUE THREAD

**Issue by slowiu06** [ldtteam/minecolonies#4043]
minecolonies-0.10.515-ALPHA-universal

Deliveryman requests food over and over, because he leaves all of it in Warehouse.

**Comment by fr3akb0y** [comment]
Also noticed that behavior. I put some food in their delivery hut which worked as a temporary solution.

**Comment by Raycoms** [comment]
What do you mean with him requesting food? you should build a restaurant?

**Comment by mojoyup1528** [comment]
Even the restaurant worker does the same thing. I have given them a LOT of a bunch of different things, but maybe it is because the request might be for 64 of something and not just "something" even though in the request page it does not specify like other requests do. Hope that helps!

**Comment by jdm311** [comment]
I sometimes fire my workers so they will eat the bread I give them. But after adding a restaurant, I don't see this problem very much anymore.

**Comment by Raycoms** [comment]
You should build a restaurant definitely, that's what we added it for. Manual feeding is only supposed to be the way early on in the game.
