### ISSUE TITLE
Builder Hut issue

### ISSUE THREAD

**Issue by WH17EW0LF** [ldtteam/minecolonies#4046]
### Minecolonies version
minecolonies-1.12.2-0.10.488-RELEASE

Version: 

### Expected behavior
Builders using their hut Correctly

### Actual behaviour
Builders stand out the back of their huts to restock/load items
- 

I only noticed this issue, (not really that big of an issue as they still build, its just an odd thing to do,) after I built the rank 5 Medieval Oak builders hut. I cant say for sure if it happened at an earlier stage or on another builders hut build but on the rank 5 medieval oak builders hut the builders will always walk around the back of the building to gather materials before wandering off to build something. They hut is set up in my town so that the fastest route to get to any building would be to walk into the hut then out again, going around the edge to refill from the back takes longer for them. I have checked for pathfinding nodes and there are none that I can see.

**Comment by WH17EW0LF** [comment]
As a note, I have tried fencing off the back of the building so that they had no choice but to go inside (I have 2 builders both doing this). they just wandered around for a while until they found a way over the fence, I then made it impossible to get over the fence so they have now decided that the side of the house is more fun... they seem really unsure about going into the hut.

**Comment by Raycoms** [comment]
Not sure what the issue is. The builder walks around in his building before taking off? That's the problem?

**Comment by WH17EW0LF** [comment]
Sorry, I didnt explain it clearly enough, The builder will go into the building if I recall them there after that then never set foot inside it again, when they go back to restock they will always walk around the rear of the building (or the sides if the rear is blocked off) but they refuse to go through the door.

**Comment by Raycoms** [comment]
ahhh okay, and with which styles did this happen?

**Comment by WH17EW0LF** [comment]
I have only seen it with Medieval Oak - Rank 5 but I didnt see if it happened at an earlier rank or not, it could have but I wasnt watching that closely. I have not tried any other styles so I could not say if they are affected Im affraid.

**Comment by WH17EW0LF** [comment]
I have now blocked off access to both sides of the hut and the rear of the hut, I also added a few extra block to the front corners. after all this they will now go inside, I assume its that they are looking for the closest access point to the storage and unless its blocked off, though the wall is the shortest.

**Comment by Raycoms** [comment]
Does this still happen with the newest alpha now?
