### ISSUE TITLE
Lumberjack attacks villager food supply- call the guards!

### ISSUE THREAD

**Issue by nekatu** [ldtteam/minecolonies#405]
### Minecolonies version

version 0.6.2114

### Expected behavior

- Lumberjack works in the forest, keeps his filthy hands off the village! ;-)

### Actual behaviour

- Lumberjack takes all wood, no matter where he finds it...
![2016-12-31_15 29 58](https://cloud.githubusercontent.com/assets/1908371/21578169/5f75a8ca-cf6e-11e6-876b-5cbd569c2182.png)
Screenshot taken just before I finished replacing the wood with planks to prevent the issue happening again.

### Steps to reproduce the problem

Not sure why, but the lumberjack (who works right next to a forest) decided he'd had enough of all those trees and wanted a slightly easier target- the local village food supply borders. I noticed a similar "issue" with the builder taking down villager buildings for their supply of resources.

My bad for creating my colony inside a village, but it looks so awesome with your buildings alongside the village buildings plus the random buildings generated by Recurrent Complex...

![2016-12-31_15 37 13](https://cloud.githubusercontent.com/assets/1908371/21578201/3aa77ca2-cf6f-11e6-888c-e920de5657c4.png)
![2016-12-31_15 37 24](https://cloud.githubusercontent.com/assets/1908371/21578202/3aa85a96-cf6f-11e6-81f7-a7bfa0c7c219.png)

**Comment by Raycoms** [comment]
Strange bug he should only recognize trees with leaves. Will have to
analyze that.

Am Samstag, 31. Dezember 2016 schrieb nekatu :

**Comment by nekatu** [comment]
Just had him do to the same thing to a farm, so it's not just a village thing; he'll take out other MineColonies buildings too. He also went into a field and picked up all the items after I cleared a harvest to plant a different crop.

Is he possessed? ;-)

**Comment by Raycoms** [comment]
Ahhh! He will search for dropped items on the ground and run there. That
might be the issue?

2017-01-01 0:45 GMT-02:00 nekatu <notifications@github.com>:

**Comment by nekatu** [comment]
Nice- explains many of the exotic items he brings back- possibly something to break out at some point for a Scavenger worker?

Doesn't explain why he takes down buildings though.

I'm going to build a new server soon, if it has the same issues as my LAN then I'll happily let you guys log into it and see the issues live, if it helps?

**Comment by Raycoms** [comment]
He takes down buildings with no leaves at all?

**Comment by Raycoms** [comment]
Okay I've been trying to reproduce the cut down field problems but I'm not able to.
Is it possible that he cuts houses and logs which are in contact with leaves?
Like there is a line of logs of the field which lead into a building and the line of logs there leads into some leaves of a tree?

**Comment by nekatu** [comment]
Could be the reason for the farms being taken down, but not the villager crop plots, definitely no leaves near them.

**Comment by Raycoms** [comment]
How strange..
If there is a way to reproduce it, please tell us.

**Comment by pmardle** [comment]
Maybe the code looking for leaves accidentally takes crops to be leaves for some reason?

**Comment by nekatu** [comment]
Haven't seen it happen in the last few versions, so it may just have been fluke, but I've come across a building (from the Actually Additions mod) recently that had all the timber removed from it. Didn't see the lumberjack do it, but no other axe wielding wood fetishists running around my towns... ;-)

**Comment by Raycoms** [comment]
Never able to reproduce this.
As soon as you're able to find a guaranteed way to reproduce this. Please contact us =D
