### ISSUE TITLE
1.14.4(520 alpha) Error processing base model for forge blockstates pseudo-model:

### ISSUE THREAD

**Issue by SDUBZ** [ldtteam/minecolonies#4051]
Forge: 1.14.4-28.1.86
Minecolonies: minecolonies-0.10.520-ALPHA-universal
noticing so many blockstate errors while loading the mod

client:
[latest.log](https://github.com/ldtteam/minecolonies/files/3822158/latest.log)

**Comment by Raycoms** [comment]
Yep, already an issue, forge has to fix the multi-laye rmodels
