### ISSUE TITLE
Workers not working if player is too far

### ISSUE THREAD

**Issue by IAmDoot** [ldtteam/minecolonies#4052]
### Minecolonies version
Version: 1.12.2-0.10.348-RELEASE

### Expected behavior
- Workers start working/building once they have a job

### Actual behaviour
- Workers stop if the player is too far (up to maybe a half chunk away)
- Workers require the player to be on top of them in order to move and work

### Steps to reproduce the problem
1. Place a hut
2. Start the build
3. Wait for builder to start building
4. Stand a chunk away or more
5. Builder proceeds to stand where they are

Also does the same for workers who aren't building, or citizens going to bed. Occurs even when there is no lag, both server and client side. It's annoying to have to shadow each worker for them to get their job done.

**Comment by Raycoms** [comment]
That's a sponge feature, you have to increase the range entities tick in sponge.
