### ISSUE TITLE
schematic incomplete

### ISSUE THREAD

**Issue by XanthDrake** [ldtteam/minecolonies#4053]
Version: 0.10.520-ALPHA

- just thought I should let you know that on the supply camp there is a trapdoor missing on one of the cart wheels! it is just a small thing but i thought i should let you guys know!

[Minecraft 1.14.4 2019-11-08 08-45-12.zip](https://github.com/ldtteam/minecolonies/files/3823686/Minecraft.1.14.4.2019-11-08.08-45-12.zip)

**Comment by Raycoms** [comment]
@lunadragnstar

**Comment by lunadragnstar** [comment]
We are updating the supply camp/ship and other deco items. That is the next project.

**Comment by mojoyup1528** [comment]
Wanted to add to this, that I noticed on Building Level 4 of the Town Hall, built with medieval oak, that the stairs going up, you can still fall from :P. Hope that helps! Very easy for us players to add oak planks, but just wanted to help out and note it in here too :)

**Comment by lunadragnstar** [comment]
Fixed, Medieval is being worked on.
