### ISSUE TITLE
Baker - Bread Dissaperes 

### ISSUE THREAD

**Issue by chrismvp** [ldtteam/minecolonies#4064]
### Minecolonies version

Version: 

### Expected behavior

-

**Comment by Raycoms** [comment]
Depending on how little he is producing, he might be eating it.

**Comment by chrismvp** [comment]
So I've got question then. How much wheat it takes to make bread for baker? Is it classic 3wheat for 1 bread? Becasue he took like 3x64 wheat(wheat dissaperes in act of using) and he was making bread for whole one day and didn't make even 1 bread.

**Comment by Raycoms** [comment]
He is supposed to take 2-4 wheat per loaf and he might need a while to output them. He kinda makes intermediary versions which he stores in his memory. So there might be a ton of unfinished loafs in his memory which he made out of all the wheat and now he is working on baking and finishing them up, that's entirely possible. Else, if we knew your exact version we could check if he is discounting too much wheat.

**Comment by chrismvp** [comment]
He unbuged at this moment. Now he is making bread. Before he was just staying infront of bakery block and punching air with wheat in hand all day. Now he is running back and forth to furnace and bakery block.

**Comment by Raycoms** [comment]
Both is correct behavior, he runs different steps.

**Comment by cy8ersword** [comment]
happened to me aswell 
I gave the baker a few stacks of wheat
no bread are found in warehouse /restaurant / bakery and everywhere else
1.14.4 minecolonies alpha.530

**Comment by Raycoms** [comment]
Baker stores dough in "memory" will then start producing the bread slowly.
