### ISSUE TITLE
Farmer will try to plant, but plant nothing

### ISSUE THREAD

**Issue by mojoyup1528** [ldtteam/minecolonies#4066]
### Minecolonies version

minecolonies-1.12.2-0.10.508-BETA-universal - I have also tried the last 3 before versions both stable and alphas as well. 
Version: 1.12.2 Forge 2705
57 mods loaded
with Optinfine and MCP 9.42

NOTE: I did have a previous 1.12.2 version an while back that worked great but I dont remember which one :P Suggestions on version maybe? Windows 10 64bit Home Forged
### Expected behavior

1. Build a farm, and assign worker when NPC is available
2. Create a farm and add a seed in the item placement
3. Give the farmer the tools needed, etc and requests. 
4. Watch them configure the route, and start harvesting
5. Harvest the crops as excepted
- 
Keep in mind, I am testing seeds with normal growth rate and it still does not work. I follow the flow of creating workers, both auto and manual and even reset, fire, and reassign workers. They all have the same outcome. Ive rebuilt the farms too as repairs. 

### Actual behaviour

- 
I follow what I do above, and the farmer goes to the field, which is assigned properly, and starts to hoe, but does not plant anything. The farmer continues the "process" and paths as if it were actually doing something but nothing is planted therefore nothing is harvested. 
I have also made sure that I have used both the stable version and the most updated version of MColonies for 1.12.2. Hope this information helps!

Youtube unlisted link of farmer not putting crops down after setting them up: https://youtu.be/O3XuAzj4yN4
### Steps to reproduce the problem

1. 
make sure the same forge, and most recent minecolonies is updated. Windows 10 Home PC setup. Load the game, create the town hall, building hut, then create a farmer hut. place farmer hut and assign worker. Fullfill worker requests. Create a farm, based on the notification that the farmer needs a farm to start. Put the crop in the farm, give the essentials for the farmer to plant the same crop. Let them try. Auto assign for everything just to start. 
2. 
3. 
4. ... Profit

SIDENOTE: At the moment, since I know you guy sare probably really busy on this, (thank you so much for your hard work btw!), I will go ahead and test different updates starting with 10.202 :) Will update if I find all stable so you guys have that info for the future :)

**Comment by Raycoms** [comment]
Can you send us your log maybe? It seems something is preventing him from planting the crops

**Comment by mojoyup1528** [comment]
Sure thing :) I will try to recreate and then make sure it records the logs and send if possible :) TY very much! Sorry I posted on a closed topic just recently. Ill make a new if you like about something else. But going to try to get logs now for you. Bless your hard work!

EDIT: Do you need the .log file or the .gz file? Thank you :)

**Comment by mojoyup1528** [comment]
[debug.log](https://github.com/ldtteam/minecolonies/files/3828903/debug.log)
[latest.log](https://github.com/ldtteam/minecolonies/files/3828904/latest.log)
And here is a video of it gong through start to error:

https://youtu.be/r7jt83rT44Y Video is uploading as I am typing this, but keep trying, it will be up soon. Fast forward if needed. Got stuck trying to gather resources in the GUI.

**Comment by Raycoms** [comment]
Can you put some water sources next to the field block?

**Comment by mojoyup1528** [comment]
I will try that now :) Update soon!

**Comment by mojoyup1528** [comment]
So I arranged 4 blocks that was in front, left, and diagonal right rear, and diagonal right front, as well as an infinite source just outside the range of the farm and the worker on the order "PLANT" is now planting "some" of the blocks :) I dont know if I added too many water sources, but Im awaiting another NPC cycle to see if the code recognizes the changes and accounts for them. So, planting is partially working :)

**Comment by mojoyup1528** [comment]
I would like to simplify it down to one water source block for others, so Ill test out of the 8 spaces around, which (if not all or any single), does just fine. Could be an easy "fix"  with no code change needed :)

**Comment by mojoyup1528** [comment]
UPDATE: As of right now, with the latest BETA, for the farmer, (1) water source right in front of the scarecrow works for the planting process on my end for seeds. I will say this is a fix for me at the moment because that is all I wanted the farmer to do was plant. I will update if any other errors occur with hoeing, planting, inventory, etc :) 
![planting](https://user-images.githubusercontent.com/43324644/68550708-5eb31980-03d3-11ea-8b05-2391e36c6fca.PNG)

**Comment by mojoyup1528** [comment]
If you want me to ever test anything on any of the issues, message me and Ill gladly do my best to help!

**Comment by Raycoms** [comment]
Great
