### ISSUE TITLE
Typo on wiki "About the mod" page

### ISSUE THREAD

**Issue by CrafterKolyan** [ldtteam/minecolonies#4068]
Link to wiki page: https://www.minecolonies.com/about.php
and
https://wiki.minecolonies.com/

Text: Featuring many NPC workers such as: ... Cook/Rest**ua**rant
Expected: Restaurant
Actual: Restuarant

**Comment by Raycoms** [comment]
Our wiki is open for contributions as well:
Please report or PR it here: https://github.com/ldtteam/MinecoloniesWiki

**Comment by Asherslab** [comment]
@Raycoms you can use the Transfer issue button in the bottom right in the future btw =P

**Comment by Raycoms** [comment]
Ahhhh =D
