### ISSUE TITLE
Typo on wiki "Tutorial" page

### ISSUE THREAD

**Issue by CrafterKolyan** [ldtteam/minecolonies#4069]
Link to page: https://wiki.minecolonies.com/source/tutorials/tutorial#placement-of-the-supply-ship-or-supply-camp

Text: (Hint: if you’re not using **hte** Building... )
Expected: the
Actual: hte

**Comment by Raycoms** [comment]
Our wiki is open for contributions as well:
Please report or PR it here: https://github.com/ldtteam/MinecoloniesWiki
