### ISSUE TITLE
Wiki appears to be down...

### ISSUE THREAD

**Issue by nekatu** [ldtteam/minecolonies#407]
Do you guys need hosting?

I work for a managed service provider and could get the wiki and/or website set up on my development server at no cost.

Just let me know what you need- love this mod and while I may be no coder, I really want to help out where I can to keep it alive and bring more attention to it.

**Comment by marvin-bitterlich** [comment]
@nekatu We used Roadkill wiki for current one. If you can provide hosting and maintenance, that would be really cool!

**Comment by nekatu** [comment]
Would be a pleasure.

I've got a linux host, so can run pretty much anything you guys need. My server has unlimited storage, unlimited bandwidth, and unlimited mailboxes. So plenty of scope for anything you guys need.

Once we have things set up it would just be a matter of you guys pointing your domain towards to the new server; or I can take that on for you as well as I'm already hosting a tonne of other domains and one more isn't going to break the bank. ;-)

**Comment by marvin-bitterlich** [comment]
We'll see with @Nollig if we can get the wiki data back (I really hope so!) and could you setup a roadkill wiki we can insert the data in?

**Comment by nekatu** [comment]
Sure thing, I'll see what i can do.

**Comment by sebiweise** [comment]
The problem will be that ASP .NET web pages do not run on Linux host systems. Therefore we have immoment a windowsserver rented, which after an indefinite time apparently has any errors. After a reboot it always goes. If you had nh solution for that would already suffice. Or you have a server that you provide, but I will continue to rent my server anyway.

**Comment by nekatu** [comment]
We can throw a copy of your server up into Azure, if you like? Can happily host that if you need the "real" Windows experience; though there are other Wiki platforms out there that could be run on a standard web server alongside the website, which I'll gladly host on my dev server,

Let me know either way.

**Comment by sebiweise** [comment]
Anything you want. I am free to new ideas and we can test everything that might help to improve performance uptime safety and all these stuff.

**Comment by nekatu** [comment]
Cool- will look into this tomorrow, just ironing out some testing on the latest build I have access to to see if they resolve the bugs I've been logging over the last few days.

**Comment by sebiweise** [comment]
OK. Do you have to pay for MS Azure?

**Comment by nekatu** [comment]
Generally- but my company does a lot of Microsoft work and we host a fair bit of stuff in Azure, so plenty of resources going spare for development.

**Comment by sebiweise** [comment]
Ah ok. I just requested my "Study Account" but these is really depressing. Just SQL, APPs and so stuff xD

**Comment by Raycoms** [comment]
This got cleared up? Can I close this?

**Comment by sebiweise** [comment]
Do you want to get the wiki data, nekatu?

**Comment by marvin-bitterlich** [comment]
@nekatu can you provide us witha new wiki hosting? :)

**Comment by sebiweise** [comment]
I would welcome this. However, I would like to continue to help with the development of the online appearance. If so, could you host the site? @Kostronor I would also like to help more in the direction of web appearance and "marketing". Less in the mod development per se. :D

**Comment by marvin-bitterlich** [comment]
@nekatu can you contact us for your wiki hosting offer?
