### ISSUE TITLE
Miner not working properly 1.14

### ISSUE THREAD

**Issue by lunadragnstar** [ldtteam/minecolonies#4070]
.535 minecolonies
Using the modpack

Build a miner (Known Dark Oak)
But the miner doesn't use mineshafts associated with that style. Miner using cobble when it should be using dark oak the same as wooden (oak).

**Comment by RyTechro** [comment]
Having the same issue on the development branch. Level 1 miner did work for me and placed the birch slabs, planks and sign with no problem. Upgrade to level 2 and the miner is creating levels out of cobblestone and even the sign is replaced by cobble

**Comment by Raycoms** [comment]
I'll be able to check on this tomorrow night probably, maybe even earlier
