### ISSUE TITLE
[FEATURE REQUEST] Builder requests and Warehouse

### ISSUE THREAD

**Issue by slowiu06** [ldtteam/minecolonies#4071]
I never know which items are missing for Builder. I was thinking about additional x/x tag to show items that are already in Warehouse and which I don't have to provide by myself.

PS.
Is the Dman always take one stack of item to Builder? Even If he is lvl 3 or above?

**Comment by Raycoms** [comment]
Duplicate request, got another issue for that already.

Dman takes more when his building level is higher.
