### ISSUE TITLE
Prob a simple fix :)

### ISSUE THREAD

**Issue by mojoyup1528** [ldtteam/minecolonies#4072]
The only thing I want to add is that when I place a building from minecolonies, then create a build request, if I had been given more than 1 upon crafting, then I end up with 2 again if I refresh or sort my inventory, even though one has already been placed down. 

Latest BETA minecolonies
windows pc 10 home forge 1.12.2
If you need me to fill out the info below I will but I figured this would be something either already reported (cant find it but just in case), or something easy to know what to do as it is likely just an item inventory count change and check. 

-------------------

### Minecolonies version

Version: 

### Expected behavior

- 

### Actual behaviour

- 

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit

**Comment by Asherslab** [comment]
Please always fill out the issue form correctly. And please title the issue appropriately according to what the issue is.
We need the full version name

**Comment by Raycoms** [comment]
Are you in creative mode?

**Comment by Raycoms** [comment]
Couldn't reproduce in survival
