### ISSUE TITLE
Sawmill tries to make thousands too much

### ISSUE THREAD

**Issue by Josral** [ldtteam/minecolonies#4076]
### Minecolonies version

Version: minecolonies-1.12.2-0.10.545-ALPHA-universal

### Expected behavior

       Sawmill making what is needed.
- 
         When a request for oak wooden fences is placed by the miner and the builder at the same time things go crazy at the sawmill.  The sawmill tries to make thousands of sticks and planks.
### Actual behaviour

- 
          As stated above.

     Didn't think to take a screenshot.  It has happened twice.  I'll try to get a screenshot on next occasion.
### Steps to reproduce the problem

      
1. Not sure.  Just have the builder and miner initiate a request for oak fences at the same time.
2. 
3.   Sawmill tries to make thousands of sticks and planks.
4. ... Profit

**Comment by Raycoms** [comment]
Fixed in the newest
