### ISSUE TITLE
Pathfinding ThreadPoolExecutor doesn't get shutdown

### ISSUE THREAD

**Issue by Bricktricker** [ldtteam/minecolonies#4087]
### Minecolonies version

Version: minecolonies-0.10.552-BETA-universal
Minecraft: 1.14.4
Forge 28.1.90

### Expected behavior

- The dedicated server shuts down normally, when closed with the `stop` command

### Actual behaviour

- When shutting down the dedicated server, the jvm doesn't close.
I think the problem is, that the ThreadPoolExecutor for pathfinding https://github.com/ldtteam/minecolonies/blob/3c1e5aede7389a31c635d18f1c033c9a308cf442/src/main/java/com/minecolonies/coremod/entity/pathfinding/Pathfinding.java#L29
never gets shut down when closing the server, because the created threads are non-daemon threads.

### Steps to reproduce the problem

1. Start a dedicated server
2. Play a bit, so villagers use pathfinding
3. Stop the server with the `stop` command
4. The jvm never closes

### Verification
1. Add a simple ThreadFactory to the ThreadPoolExecutor:
```java
private static class DebugThreadFactory implements ThreadFactory {
        private ThreadFactory defaultFactory;
        
        public DebugThreadFactory() {
            this.defaultFactory = Executors.defaultThreadFactory();
        }
        
        @Override
        public Thread newThread(Runnable r) {
            Thread t = this.defaultFactory.newThread(r);
            t.setName("minecolonies-pathfinding-" + t.getName());
            return t;
        }
        
    }
```
2. Get a thread dump after stoping the server. See that there is only one non-deamon thread running, which is the minecolonies-pathfinding  thread.

**Comment by Asherslab** [comment]
you're welcome to make a PR to fix said issue if you're capable enough to find it
