### ISSUE TITLE
[Feature Request] Move In

### ISSUE THREAD

**Issue by kreezxil** [ldtteam/minecolonies#4088]
There are instances where a colony will become uninhabited whether by config and someone didn't log on during a time period or that a colony was deleted from the database.

1. My idea is that in such situations where the building is intact with the hutblock in it. 
1. That if your colony now covers that building with the hutblock you never crafted.
1. That there is either a new button to allow an npc of yours to inhabit that building  **or** hiring an npc will do the same thing.
1. **AND** furthermore, the buildings level is saved and not regressed, if it is higher than the npc moviing into it the npc will play catchup instead of dismantling the building.

**Comment by Asherslab** [comment]
that sounds like a cool idea. a couple notes:
1. > that a colony was deleted from the database.

4 won't work with that, as the building level is stored in the colony itself.
and furthermore if a hut isn't protected (i.e. can have another colony over it), it does not have a level any more.

2. for number 3, it'd just work the same as if you placed the hut yourself most likely.
we'd probably simply detect when you right click the hut block if it's currently inside a colony, if it is then it'd join said colony as if it were just placed.

**Comment by Raycoms** [comment]
Yeah, if the colony gets deleted that's complicated since we delete all related data to it. If the colony is still there and "abandoned" copying data over would be easy.

**Comment by someaddons** [comment]
So basically the idea is that old/unsed colonies at one point can become "free to claim" to be overtaken by other colonies

**Comment by kreezxil** [comment]
basically that would be a good explanation.

or even alternatively

when you finally got the factions component working correctly, if 2
colonies goto war and the one wins. if the right setting is enabled (like
maybe it's called *occupy*) you would be able to claim what you wanted out
of a colony. However I'm not holding my breath for that. I know how
difficult the code and the bugs are to manage on this project.

**Comment by someaddons** [comment]
when the colony still exists which you're overtaking it should be pretty straight forward to do, would likely make sense to have some kind of abadoned/free to claim colony-status for that

**Comment by Raycoms** [comment]
Closed in favor of joint issue.
