### ISSUE TITLE
Builder issue

### ISSUE THREAD

**Issue by VladimirPalpatine** [ldtteam/minecolonies#4089]
Version: 
0.10.493-RELEASE

Expected behavior: 
Builder upgrades town hall

Actual behavior:
Builder almost finishes and  then returns to their hut and stops moving.

Steps to reproduce the problem
1. Build medieval oak townhall
2. Attempt to upgrade townhall

*UPDATE*
It appears to be a path finding issue because pushing them sorta fixes it

*UPDATE 2*
Only worked for tier 2

**Comment by Raycoms** [comment]
Couldn't reproduce this, can you check with the latest alpha if you can reproduce it?

For now, closed.
