### ISSUE TITLE
Game crash on farm land block state change?

### ISSUE THREAD

**Issue by nekatu** [ldtteam/minecolonies#409]
### Minecolonies version

version 0.6.2190

### Logged Error

get property PropertyEnum{name=variant, clazz=class net.minecraft.block.BlockDirt$DirtType, values=[dirt, coarse_dirt, podzol]} as it does not exist in BlockStateContainer{block=minecraft:farmland, properties=[moisture]}

### Log Files
[fml-server-3.zip](https://github.com/Minecolonies/minecolonies/files/680217/fml-server-3.zip)
[McMyAdmin-20170101-162037.zip](https://github.com/Minecolonies/minecolonies/files/680218/McMyAdmin-20170101-162037.zip)

Also noticed that a lot of the labels for items and achievements are not in a user friendly format on this build.

**Comment by Raycoms** [comment]
Can you try to reproduce it with the one which will launch in the next 10
minutes?

Way to reproduce this?

2017-01-01 20:16 GMT-02:00 nekatu <notifications@github.com>:

**Comment by nekatu** [comment]
Haven't been near the farms when it happens; just seems to happen within 10 minutes of game play.

Rolled back to 0.6.2179 and haven't had the issue in the last 15 minutes.

On a side note, I keep seeing this in the server logs though:

[minecolonies]: ForgeHook not in sync with EfficientTool for Block{minecraft:potatoes} and 28xitem.potato@0

Will try the new version once you've uploaded it and see what that does.

**Comment by nekatu** [comment]
I suspect the side note message is due to me equipping the farmer with a hoe from a mod, have switched to a standard hoe and haven't seen that error since.

**Comment by nekatu** [comment]
Actually, I take it back...

thread/INFO] [minecolonies]: ForgeHook not in sync with EfficientTool for Block{minecraft:wheat} and 1xitem.hoeIron@0

**Comment by Raycoms** [comment]
Yeah I already notified the responsible people for this =D

But, important is the crash, does it still happen with the newest?

2017-01-01 20:39 GMT-02:00 nekatu <notifications@github.com>:

**Comment by nekatu** [comment]
Just loaded 0.6.2194 onto my server now.

Will let you know ASAP.

**Comment by nekatu** [comment]
No crash so far... so bodes well.

**Comment by nekatu** [comment]
2 hours without a crash so far, Farmer seems happy; nice work! :-)
![2017-01-02_01 22 49](https://cloud.githubusercontent.com/assets/1908371/21583837/1062719c-d08a-11e6-9c11-3748598ad9f4.png)

**Comment by nekatu** [comment]
0.6.2194 was great for over 4 hours.
0.6.2195 crashed with the original issue in under 20 mins.

**Comment by nekatu** [comment]
Rolling back to 0.6.2194 resulted in almost instant crashes...

[fml-server-3.zip](https://github.com/Minecolonies/minecolonies/files/680398/fml-server-3.zip)

**Comment by nekatu** [comment]
Testing 0.6.2196 for the issue now

**Comment by nekatu** [comment]
Still the same error after a few minutes of play:

[12:09:11] [Server thread/WARN] [minecolonies/]: Action for target com.minecolonies.coremod.entity.ai.util.AITarget@7a330e5b threw an exception:
java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=variant, clazz=class net.minecraft.block.BlockDirt$DirtType, values=[dirt, coarse_dirt, podzol]} as it does not exist in BlockStateContainer{block=minecraft:farmland, properties=[moisture]}

I destroyed the scarecrows, took the hoe off the farmer, cleared the fields, and even filled in the water blocks, so it's not that the Farmer is even doing anything any more, but the game still looks like it's referencing a block state change for moisture on dirt/podzol/coarse-dirt.

[fml-server-3.zip](https://github.com/Minecolonies/minecolonies/files/680745/fml-server-3.zip)

**Comment by Raycoms** [comment]
It's the builder who tries to build or remove farm land.
test it in the 2200 please. There should be no way that he enters with
farmland there...

2017-01-02 10:14 GMT-02:00 nekatu <notifications@github.com>:

**Comment by Raycoms** [comment]
Found the problem. Pushed a solution, have to wait for the new build.

2017-01-02 10:29 GMT-02:00 Ray Neiheiser <ray.neiheiser@gmail.com>:

**Comment by nekatu** [comment]
Haven't seen the builder anywhere near it- but will test the 2200 build anyway.

Thanks! :-)

**Comment by nekatu** [comment]
Actually, spotted 2207 just as I posted that, so I'm testing on that instead.

**Comment by nekatu** [comment]
so far so good on 2207, but just having the builder rebuild the fields, so we'll see how that goes.

**Comment by nekatu** [comment]
nope- still an issue on 2207-

13:00:32 CONSOLE: get property PropertyEnum{name=variant, clazz=class net.minecraft.block.BlockDirt$DirtType, values=[dirt, coarse_dirt, podzol]} as it does not exist in BlockStateContainer{block=minecraft:farmland, properties=[moisture]}

[fml-server-3.zip](https://github.com/Minecolonies/minecolonies/files/680786/fml-server-3.zip)

Switching to 2212 now.

**Comment by nekatu** [comment]
so far so good on 2212

**Comment by nekatu** [comment]
I swear this game is just waiting for me to post here- the last 3 times I've posted that everything seems fine the game crashes almost instantly! ;-)

Seems 2212 has the same issue after all.

[fml-server-3.zip](https://github.com/Minecolonies/minecolonies/files/680859/fml-server-3.zip)

**Comment by Raycoms** [comment]
Okay whatever minecraft did what that farmland block, it doesn't have a
damage value...

Will have to dig a bit deeper then.

2017-01-02 12:01 GMT-02:00 nekatu <notifications@github.com>:
