### ISSUE TITLE
Mine support are all made by cobblestone and strange floor number

### ISSUE THREAD

**Issue by tomchang25** [ldtteam/minecolonies#4090]
### Minecolonies version
Version: minecolonies-0.10.493-RELEASE-universal

### Expected behavior
1.Mine support and platform are consist of  cobblestone.  
2.If miner hut level up. The miner floor would jump over. And repeat previous floor number.
for example. If level 2 mine has 44 40 36 floor . If i upgrade it. the level 3 would become 44 40 36 40 28 floor.
32 is jump over and 40 is repeat
### Actual behaviour
1.Mine support and platform should be replace by wood.  
2. They should be in order.
### Steps to reproduce the problem
1. I just build Miner and first level platform is normal. and second and below floor are all made by cobblestone.

2.It happened after i upgrade miner to level 3

**Comment by Raycoms** [comment]
yes, we found and fixed this in the most recent ones.
