### ISSUE TITLE
Guard training/tower skills not matching

### ISSUE THREAD

**Issue by someaddons** [ldtteam/minecolonies#4092]
### Minecolonies version

Version: All

### Expected behavior

Guard training buildings should require the same skills as the actual guard job ranger/knight.
 

### Actual behaviour

The guard training buildings require different skills than the guard tower does for the corresponding guard job.

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit

**Comment by Asherslab** [comment]
Lol, realise you did something wrong?

**Comment by someaddons** [comment]
just forgot to add the link to the guard PR :)

**Comment by someaddons** [comment]
its fixed now^^
