### ISSUE TITLE
Minecolonies not accepting armor with custom NBT

### ISSUE THREAD

**Issue by AzureDoom** [ldtteam/minecolonies#4094]
### Minecolonies version
Version: minecolonies-0.10.559-ALPHA-universal

### Expected behavior
1. Put armor on Guard 

### Actual behaviour
Guard does not wear the armor.

### Steps to reproduce the problem
1. Use Mine and Slash and have it add it's NBT data to the armor
2. Try and have the guard use the armor that gains the NBT

##Cross link for kreezxil/World-of-Dragons-A-New-Age#76

**Comment by Raycoms** [comment]
That custom nbt data, is that like enchantments? If so the guards will only accept enchantments over a certain level (enchantsment add one requirement level)

**Comment by Raycoms** [comment]
Else, we don't adapt anything. Probably the building level must be higher.

**Comment by AzureDoom** [comment]
Yeah it might be counting as enchantment. I'll test tonight when I'm free.
