### ISSUE TITLE
Dynamic colonies not expanding with various buildings

### ISSUE THREAD

**Issue by CriswellCodes** [ldtteam/minecolonies#4099]
### Minecolonies version
minecolonies-0.10.559-ALPHA

Version: 
Minecraft 1.14.4
Forge 28.1.92

### Expected behavior
All other Worker Hut Buildings (non decoration):
Level | Additional Chunks | Total Area
1 | initial chunk | Total: 1x1
3 | +1 chunk radius | Total: 3x3
5 | +1 chunk radius | Total: 5x5

### Actual behavior
(Excerpt from Discord discussion with Raycoms)
Tarlin Last Thursday at 11:19 AM
ok, so far fishermans hut level 5. citizen huts level 3 and 5, bakery 5, composter 5 did not expand the borders at all
Acacia style

### Steps to reproduce the problem

1. Set a dynamic colony on a server
2. Build the above buildings
3. Watch the border not expand
4. ... Profit

**Comment by CriswellCodes** [comment]
Might also help to know that the townhall was built from level 1 to level 5 by the builder. The remaining buildings were pasted in using admin powers while being an officer in the colony due to a previous colony issue.

**Comment by CriswellCodes** [comment]
Sorry for more and more comments, just dropping notes as I am reminded/remember them. Not been in good health lately so forgetting a ton of stuff.

The Townhall after being full constructed to level 5 did not expand out to the full 13x13 dynamic claim size. This only affected 1 colony that was done this way, the other colony that was repaired is functioning fully the way intended. I will attach the affected colonies data file.

**Comment by CriswellCodes** [comment]
Requesting how to add the colonies .dat file for review....

**Comment by Raycoms** [comment]
Okay, I tested it well and it works fine, I think the confusion is the following:
- You think it will expand 1 chunk around the building.
- Actually it expands 1 chunk around the chest of the building.

This means if the chest is in the other chunk, and the rest of the building in the chunk close to the border, it won't expand the area.
