### ISSUE TITLE
Worker Hire for Miner highlighting Lumberjack stats

### ISSUE THREAD

**Issue by nekatu** [ldtteam/minecolonies#410]
### Minecolonies version

version 0.6.2179

### Expected behavior

- "Hire Worker" on Miner Hut should highlight Strength in green and Endurance in yellow

### Actual behaviour

- "Hire Worker" on Miner Hut highlights Strength in green and Charisma in yellow (as per the Lumberjack stats)

### Steps to reproduce the problem

1. Select Miner chest
2. Select Hire Worker

![2017-01-01_22 28 15](https://cloud.githubusercontent.com/assets/1908371/21583275/f3dc564a-d071-11e6-8db4-b042b7b407f8.png)

**Comment by Raycoms** [comment]
good catch =D

2017-01-01 20:30 GMT-02:00 nekatu <notifications@github.com>:

**Comment by marvin-bitterlich** [comment]
btw @nekatu does your texture pack work with all guis? Like show the citizens experience bar and such? Could you tell me which one it is?

**Comment by nekatu** [comment]
The overall texture pack is "John Smith Legacy", but I also have "Stevian Villagers", an older mod that makes the the villagers look a lot like the Citizens from MineColonies for better immersion as I generally build my colonies inside existing villages as the VIllager becomes a Town and then a City.

So far as I'm aware it works on all GUIs and it makes your excellent building designs look even more amazing, as you'll likely have seen from a few of my screenshots.

Though assuming you mean the bar under a citizen's name when you select them then I'm not sure it is working correctly:

![2017-01-02_12 07 20](https://cloud.githubusercontent.com/assets/1908371/21588969/54e29572-d0e4-11e6-8434-0c01be4f907f.png)
![2017-01-02_12 08 44](https://cloud.githubusercontent.com/assets/1908371/21588968/54e2718c-d0e4-11e6-8b4d-55467037564e.png)
