### ISSUE TITLE
Builder not building

### ISSUE THREAD

**Issue by fR0zeNNN** [ldtteam/minecolonies#4100]
### Minecolonies version

Version: minecolonies-0.10.493-RELEASE-universal

### Expected behavior

- 

### Actual behaviour

- 

### Steps to reproduce the problem

1.  Command your builder to build.
2.  Fulfill requirements.
3.  He needs those again, but if you fulfill he does not notice.

**Comment by Raycoms** [comment]
duplicate issue, will close
