### ISSUE TITLE
Unable to See Most GUI on MAC

### ISSUE THREAD

**Issue by holty07** [ldtteam/minecolonies#4102]
Version: Minecraft 1.14.4 - minecolonies-0.10.561-ALPHA-universal

### Expected behavior
I should be able to select a worker for each building. I should be able to see what is required before building. I should be able to see required items.

### Actual behaviour
I can't see any of these. If I change from full screen to not full screen I can see some of the items as though there is a block of nothing in the way. Screenshots help with this.

Not full-screen: https://imgur.com/CItgsmV
Full-screen: https://imgur.com/lvFME8i

### Steps to reproduce the problem
You probably need a MAC to see this issue as I only have this and Structurize installed, but let me know if there is anything else I can provide that may help.

**Comment by Graepix** [comment]
This is the same problem as issue #3993. Posting the specs of your computer there might be helpful

**Comment by holty07** [comment]
Thanks mate, I'll follow along there and see if I can provide any extra help.
