### ISSUE TITLE
Lumberjack farming leaves not wood

### ISSUE THREAD

**Issue by hotluck** [ldtteam/minecolonies#4103]
Version: minecolonies-0.10.493-RELEASE-universal

### Expected behavior
Lumberjack chops down trees.

### Actual behaviour
They look like they are chopping wood but with a sapling and it's the leaves that appear to be being chopped (although not in their inventory).

### Steps to reproduce the problem
It started with the lumberjack holding a sapling and just walking backwards and forwards near the hut. I tried removing all saplings from their inventory but it made no difference. They had an axe in their inventory. So I fired them and re-hired them.
This stopped their walking problem and they went to the trees to chop them. However, after an hour or so, I went to collect the wood from them. There was none. When I looked closer, I could see the lumberjack was still holding a sapling and bits were coming off the leaves not the wood.
![2019-11-26_14 26 37](https://user-images.githubusercontent.com/11139297/69642613-ecd90200-1059-11ea-9448-ffccdf144ed1.png)

I am now going to try and fire this lumberjack and hire a different one to see if they will actually chop wood. If they don't, I will add more to this issue.

**Comment by Raycoms** [comment]
Is there no wood in a rack or chest or so in their building?

**Comment by hotluck** [comment]
No, none. And I have just hired someone else, given them axes, and they have gone to the same tree with wheat seeds in hand, chopping leaves! So lumberjack is useless right now.
![2019-11-26_14 39 41](https://user-images.githubusercontent.com/11139297/69643191-db442a00-105a-11ea-9ffd-4584f83ef053.png)

**Comment by hotluck** [comment]
I will say that after the hut was built, they did chop some wood, but only for a few hours before this behaviour started.

**Comment by Raycoms** [comment]
Did you add any mod which changes trees or leafes?

**Comment by hotluck** [comment]
No I have added no mods since starting this world. I do had other mods, and a resource pack that changes the look of things called something like Winthor Medieval, but would a resource pack interfere?

P.S. Could you take a look at issue #4077 because it is getting to be a major pain, but not like this one (I don't think they are related either).

**Comment by hotluck** [comment]
Any news on this?

**Comment by Raycoms** [comment]
Weekend is close, allowing me to look at this.

**Comment by hotluck** [comment]
No problem :)

**Comment by dcazrael** [comment]
I'm having the exact same issue. 
My lumberjack actually had 21 Wood on him and tried to place it in the job site inventory.
I could see it disappearing from his inventory, but nothing in the job site inventory.

**Comment by Raycoms** [comment]
I can't reproduce this, for me the lumberjack is cutting down trees nicely

**Comment by hotluck** [comment]
I am using the following other mods (in case one of these is interfering) -

bambooeverything-1.14-1.4.0
Biomes-OPlenty-1.14.4-9.0.0.258-universal
chickenshed-1.14.4_2
ditr14-1.62
doubledoors_1.14-1.2
furniture-7.0.0-pre13-1.14.4
Hwyla-forge-1.10.6-B67_1.14.4
jei-1.14.4-6.0.0.25
luckyores-1.14.4-1.2
Masonry-0.3.1
OptiFine_1.14.4_HD_U_F4
StorageDrawrs-1.14.4-6.0.5
structerize-0.10.199-ALPHA
tombstone-4.1.7-1.14.4
UniversalClockHUD-1.0
Xaeros_MiniMap_1.18.9_Forge_1.14.4
XaerosWorldMap_1.5.0.1_Forge_1.14.4

And the resource pack I mentioned earlier.

Like I said, I had been playing a few hours before this behaviour started.

**Comment by dcazrael** [comment]
I updated the mine colonies version to the newest alpha.
After I checked the lumberjack and it put some wood in the inventory.
The problem is less with cutting down, but more with him not retaining wood.

I'm using these mods

AppleSkin-mc1.14.4-forge-1.0.13
BetterAdvancements-1.14.4-0.1.0.93
betteranimals-1.14.4-5.2.1
classicbar-2.0.0a
Hwyla-forge-1.10.6-B67_1.14.4
jei-1.14.4-6.0.0.25
minecolonies-0.10.564-ALPHA-universal (before)
minecolonies-0.10.567-ALPHA-universal (now)
preview_OptiFine_1.14.4_HD_U_F5_pre1
structurize-0.10.200-ALPHA
tombstone-4.1.7-1.14.4
u_team_core-1.14.4-2.7.8.138
useful_backpacks-1.14.4-1.7.4.46
Vampirism-1.14.4-1.6.0-alpha+20191021-1133
Xaeros_Minimap_1.19.1_Forge_1.14.4
XaerosWorldMap_1.5.2_Forge_1.14.4

**Comment by dcazrael** [comment]
Just another update.
I monitored with the 567 version and the problem disappeared.

**Comment by hotluck** [comment]
I installed the latest alpha (574) and I thought it was fixed, but then it started to happen again after about 3 hours play :(

**Comment by hotluck** [comment]
Any news on this please?

**Comment by Raycoms** [comment]
I improved some code surrounding it in the latest alphas, but I couldn't reproduce this under any circumstances. I was playing for 6h and more.
