### ISSUE TITLE
Incorrect enchantment id for sweeping edge.

### ISSUE THREAD

**Issue by gswvmware** [ldtteam/minecolonies#4105]
### Minecolonies version

Version: 0.10.561-ALPHA

### Expected behavior

This message not showing up in the log.
`[Client thread/WARN] [minecolonies/]: Enchantment: minecraft:sweeping_edge doesn't exist!`
Using the actual id for sweeping edge: `minecraft:sweeping`
### Actual behaviour

This message showed up in the log.
`[Client thread/WARN] [minecolonies/]: Enchantment: minecraft:sweeping_edge doesn't exist!`
https://github.com/ldtteam/minecolonies/blob/401bc1858b68a505399779e0b88a9bca780c9e51/src/api/java/com/minecolonies/api/configuration/Configurations.java#L506
and 4 more

### Steps to reproduce the problem

1. Start the server.
2. Check the log.
3. Find [Client thread/WARN] [minecolonies/]: Enchantment: minecraft:sweeping_edge doesn't exist!
4. ... Profit

**Comment by Asherslab** [comment]
can you make a PR to fix that? thanks!

**Comment by gswvmware** [comment]
Thanks for labeling.
New to GitHub. Didn't know how to make PRs. Don't know how to compile & test it. Am I doing it right? https://github.com/ldtteam/minecolonies/pull/4106

**Comment by gswvmware** [comment]
wow that was fast

**Comment by Asherslab** [comment]
@gswvmware with such a small update you can easily do it via github’s editing features. 
Thanks for the contribution!
