### ISSUE TITLE
Unobtainable blocks

### ISSUE THREAD

**Issue by SpiderGlitch** [ldtteam/minecolonies#4108]
### Minecolonies version

Version: 0.10.493-RELEASE

### Expected behavior

- 
I'm not sure, see actual behavior
### Actual behaviour

- 
A lot of the recipes for some of the early buildings require Grass blocks and Path blocks. To my knowledge, you can't get these without silk touch, with is impossible to have this early (I don't even have iron). Is there any other way to get them, because this is annoying

### Steps to reproduce the problem

Spruce medieval lumber whatever and the town hall both need grass blocks, and the town hall needs path blocks. Not sure what else
1. 
2. 
3. 
4. ... Profit

**Comment by hotluck** [comment]
They are just reminders built in for the builders. They will automatically create them themselves :) (I found that out when my builder said the same)

**Comment by SpiderGlitch** [comment]
> They are just reminders built in for the builders. They will automatically create them themselves :) (I found that out when my builder said the same)

So I didn't need to turn on cheats and pop them in (':
Thanks for the explanation 👍
