### ISSUE TITLE
SUGGESTION: Current job/activity in NPC "Title" field

### ISSUE THREAD

**Issue by nekatu** [ldtteam/minecolonies#411]
Just switched on the developer features in the config file and have to say I absolutely love seeing what each citizen is up to and where they're going. 

If this was show in a more graphical format I think it would be an awesome feature to have in the non-dev mode.

**Comment by Raycoms** [comment]
On single player, in the newest version execute /mc colony citizenInfo
<citizenid | citizenName> or /mc colony citizenList and click on the
citizen, this also contains this information.
We're also planning on add similar information to their GUI.

2017-01-01 21:04 GMT-02:00 nekatu <notifications@github.com>:

**Comment by nekatu** [comment]
Will try that in my next single player test- on a server any /mc commands tell me to use /minecolonies instead, and that generates an "Unknown Error" message.

**Comment by Raycoms** [comment]
could you send us a log of that?

2017-01-01 21:15 GMT-02:00 nekatu <notifications@github.com>:

**Comment by Raycoms** [comment]
Are you op level 3 on the server?

2017-01-01 21:16 GMT-02:00 Ray Neiheiser <ray.neiheiser@gmail.com>:

**Comment by nekatu** [comment]
Any specific log file?

I'm running McMyAdmin- so many a log file to choose from! ;-)

**Comment by Raycoms** [comment]
the fml-latest and the latest.

2017-01-01 21:23 GMT-02:00 nekatu <notifications@github.com>:

**Comment by nekatu** [comment]
[latest.zip](https://github.com/Minecolonies/minecolonies/files/680240/latest.zip)
[fml-server-latest.zip](https://github.com/Minecolonies/minecolonies/files/680239/fml-server-latest.zip)

**Comment by Raycoms** [comment]
Sent to responsible dev.

2017-01-01 21:26 GMT-02:00 nekatu <notifications@github.com>:

**Comment by nekatu** [comment]
Thanks- hope it helps! :-)

**Comment by nojo121** [comment]
I need some more info @nekatu :
-Which command did you exactly use? (with arguments)
-What did the minecraft chat say?
-Have you got your own colony?
-Which rank have you got in this colony? (friend, officer, owner)
-Is this on a server? if yes, are you op?
-What does the log say when you perform this command?

**Comment by nekatu** [comment]
* "/mc colony citizenInfo" and "/mc colony citizenList" do not work, it just tells me to use "/minecolonies" instead and shows a number of options in the chat lot
* "/minecolonies colony citizenList" shows the same list of options in the chat log
* "/minecolonies colony citizenInfo" shows the"Unknown Error" in the chat log

I'm the owner of the colony, and yes, this is on a server that I'm the Op on.

The log doesn't appear to say anything when I'm running the commands- appears to all be happening client side. I attached the server logs in an earlier post.

**Comment by nojo121** [comment]
ok thx, i know what's causing this.

**Comment by nojo121** [comment]
/mc colony citizenList does not excist. So it shows you which commands are possible with /mc colony *
possible commands are /mc /minecolonies /mcol
if you want to list citizens, do /mc citizens list
the Unknown error message when using /mc colony citizenInfo will be fixed by myself

**Comment by nekatu** [comment]
thanks- good to know! :-)

**Comment by nojo121** [comment]
please don't close issues.
we'll do that when we have finished!

**Comment by nekatu** [comment]
no worries- sorry!

**Comment by nekatu** [comment]
More on this one here: #432

**Comment by nojo121** [comment]
I think, everything is fixed....
