### ISSUE TITLE
Builder is building the Farm 2 blocks at a time

### ISSUE THREAD

**Issue by blkarcher77** [ldtteam/minecolonies#4111]
### Minecolonies version
Version: minecolonies-0.10.493-RELEASE-universal

### Expected behavior
Like previous buildings, the builder should take all the materials, walk to the area designated, and start building, until it gets a problem, like lack of supplies, or lack of tools.

### Actual behaviour
The builder goes to the builders hut, hangs out for a second, then runs to the build area. He places 2 blocks down, and then goes back to the builders hut. When he was building the Mine, he took all the supplies, ran to the area, and kept building until he got an error. I started the build over multiple times, seeing if that would fix it, but not luck. Here is a few gifs

https://imgur.com/a/vboU2Zl

### Steps to reproduce the problem
Not entirely sure. I have multiple builds pending, with no build order yet. I also destroyed and replaced the builders hut box, because it was facing the wrong way. I let the building "rebuild," and the builder just replaced the torches, and the build was complete.

### Edit
So it turns out the error was only when it came to the floor using the grass path blocks. Once it actually started building the building, he worked as intended

**Comment by Raycoms** [comment]
Does this happen through the entire build or only through the placement of those path blocks?

**Comment by blkarcher77** [comment]
Only on the placements of the path blocks. Once they were all placed, the builder worked fine, standing in place and building the rest of the building

**Comment by Raycoms** [comment]
what building style is this, so I can look into it.

**Comment by blkarcher77** [comment]
Nordic farmer building level 1

**Comment by blkarcher77** [comment]
Should I close this thread?

**Comment by Raycoms** [comment]
No, I'll look into what is the problem with those paths.

**Comment by JensBue** [comment]
I have the same issue in Version 0.10.567-ALPHA, MC 1.14.4
Style is a mix of "Wooden", "Birch", "MedivialBirch" and "MedivialBirchAlternative".
Happens with every new building but also on upgrading existing ones. Everytime "Grass Path" is still on its Material List he does that, once finished with it, everything goes on normally.
