### ISSUE TITLE
Realistic Torches Miner Compat

### ISSUE THREAD

**Issue by DonTheBreton** [ldtteam/minecolonies#4112]
### Minecolonies version

Version: 0.10.348-RELEASE

### Expected behavior

- Miner compatible with Realistic Torches mod item lit torch (realistictorches:torch_lit)

### Actual behaviour

- Miner requires minecraft:torch item in order to work.

**Comment by Raycoms** [comment]
You can scan in those schematics with those modded torches and override ours.

**Comment by DonTheBreton** [comment]
Edited: I was mistaken. Thank you for the clarity.

**Comment by Raycoms** [comment]
He requests torches because the schematics he builds (the shafts) contain those torches.

**Comment by DonTheBreton** [comment]
How do you replace a shaft schematic? That's not listed in the wiki.

**Comment by Raycoms** [comment]
https://github.com/ldtteam/minecolonies/tree/version/1.12/src/main/resources/assets/minecolonies/schematics/Medieval%20Oak/miner

There in the miner subfolder within the schematic style

**Comment by Raycoms** [comment]
they require the same dimensions exact as those and same rotation

**Comment by DonTheBreton** [comment]
Thank you! I appreciate the clarity!

Also, in case you haven't seen the comment, I'm working with a team to create a modpack that centers around the MineColonies mod. One of us streams it every night after RimWorld on twitch.tv/MicoInkwell. I hope if you can you'll join us. We'd love to help contribute to your development.

**Comment by Raycoms** [comment]
Ahh, nice project =) Good luck!
