### ISSUE TITLE
Bibliocraft Compat

### ISSUE THREAD

**Issue by DonTheBreton** [ldtteam/minecolonies#4113]
### Minecolonies version

Version: 1.12.2-0.10.348-RELEASE
Bibliocraft Version: v2.4.5 MC1.12.2

### Expected behavior

- Colonists only sit in chairs when idle and leave chairs when job or sleep requires.

### Actual behaviour

- When provided with a Bibliocraft seat, colonists will sit in the seat and not leave even when it becomes night or when they have a job to do.

### Steps to reproduce the problem

1.  Place Bibliocraft seat in an area where a citizen will go idle.
2. Wait for a citizen to use the seat. I recommend the delivery person.
3. Then start a job that would require that citizen to move or wait until night time.
4. ... Profit

**Comment by Asherslab** [comment]
Citizens aren’t supposed to be using those seats in general. They can’t get up because they aren’t players and don’t have the same capabilities.
