### ISSUE TITLE
Lumberjack

### ISSUE THREAD

**Issue by blkarcher77** [ldtteam/minecolonies#4115]
### Minecolonies version
Version: minecolonies-0.10.493-RELEASE-universal

### Expected behavior
Should be showing the log with the axe in it, as it shows in the HWYLA menu

### Actual behaviour
Instead, it shows a pink and black squared cube, as shown in image below

https://imgur.com/a/ATXyA7v

### Steps to reproduce the problem
I mean, I just made one. Not sure how to reproduce

### Sidenote
I'm not sure if this is important enough to make a new thread, as it's more of a design flaw. But in the Nordic Citizen house level 1, one of the sides of the roofs has a misplaced block. In the image below.

https://imgur.com/a/MgLDj4Z

**Comment by Asherslab** [comment]
issue is forge related, not us. 
Will be fixed when forge fixes
