### ISSUE TITLE
Building block crashes server when breaking it

### ISSUE THREAD

**Issue by byalexeykh** [ldtteam/minecolonies#4118]
### Minecolonies version

Version: minecolonies-0.10.493-RELEASE-universal

### Expected behavior

- Do not crash server

### Actual behaviour

- Server throw NullPointerException when trying to harvest (destroy) building block (for example builder's hut or Town Hall block)
- Minecraft version: 1.14.4
- Forge: 28.1.92
 - Crash log: https://pastebin.com/iG1AjKn6

### Steps to reproduce the problem

1. Launch forge 28.1.92 server with Minecolonies
2. Place Town Hall block (or any other building block) (i'm placing it with building tool)
3. Break it 
4. Crash server with java.NullPointerException

**Comment by Raycoms** [comment]
Can you try with the latest alpha?

**Comment by byalexeykh** [comment]
> Can you try with the latest alpha?

It worked!
