### ISSUE TITLE
Miner needs an unknown item or block...

### ISSUE THREAD

**Issue by nekatu** [ldtteam/minecolonies#412]
### Minecolonies version

version 0.6.2194

### Expected behavior

- Miner tells you what specific item they need

### Actual behaviour

- Console reports:
com.minecolonies.coremod.job.Miner Elizabeth I. Jones (Working)[NEEDS_ITEM]: entity.miner.messageNeedBlockAndItem

![2017-01-01_23 09 23](https://cloud.githubusercontent.com/assets/1908371/21583445/db949e10-d078-11e6-9d96-4d336f3dab7c.png)

**Comment by Raycoms** [comment]
and I thought I had fixed this =(

2017-01-01 21:20 GMT-02:00 nekatu <notifications@github.com>:

**Comment by Raycoms** [comment]
Is your game in another language?

2017-01-01 21:22 GMT-02:00 Ray Neiheiser <ray.neiheiser@gmail.com>:

**Comment by nekatu** [comment]
nope- just english

**Comment by Raycoms** [comment]
All worker are talking this glibberish or only the miner in this case?
Starting to hate 1.11 bugs =D

2017-01-01 21:25 GMT-02:00 nekatu <notifications@github.com>:

**Comment by nekatu** [comment]
Just the miner at the minute, but I have the builder on infinite resources and the farmer doesn't tend to need much more than a good hoe, same story with the lumberjack- he has his axe so he's happy.

**Comment by nekatu** [comment]
Turns out it was cobblestone- but I went through all the standard building gear before that-

* Ladder
* Oak Planks
* Fence Posts
* Torches

**Comment by nekatu** [comment]
Happens for the Fisherman too-

![2017-01-02_01 37 34](https://cloud.githubusercontent.com/assets/1908371/21583907/1389547e-d08c-11e6-8f7d-e4ebdf6345d1.png)

**Comment by nekatu** [comment]
Guards get the same message too, even on build 2212

![2017-01-02_14 19 40](https://cloud.githubusercontent.com/assets/1908371/21590775/8b2b6d90-d0f6-11e6-9ffc-3a785cbd97ba.png)

**Comment by Raycoms** [comment]
smp and ssp or both?

2017-01-02 12:20 GMT-02:00 nekatu <notifications@github.com>:

**Comment by nekatu** [comment]
SMP for sure, haven't tried the recent builds in SSP yet.

**Comment by nekatu** [comment]
Doesn't seem to happen in SSP; and the same for a LAN game, it's only on a server deployment it seems to have the issue.

![2017-01-02_16 00 03](https://cloud.githubusercontent.com/assets/1908371/21592380/e86cf0e2-d104-11e6-9de6-997f03f4d8e5.png)
![2017-01-02_16 01 54](https://cloud.githubusercontent.com/assets/1908371/21592381/e870570a-d104-11e6-90be-a40241f5510f.png)

**Comment by nekatu** [comment]
Feels like it's maybe not loading the relevant language file... is that possible?

**Comment by nekatu** [comment]
Also noticed that the Guards are referring to Miner items, as per my earlier screenshot.

![8b2b6d90-d0f6-11e6-9ffc-3a785cbd97ba](https://cloud.githubusercontent.com/assets/1908371/21595802/d8058546-d129-11e6-99f4-cae66b682a0f.png)

Sounds like a continuation of the strings issues you're already aware of then.

**Comment by Raycoms** [comment]
Could you create a new issue for the guard problems to get this issues here cleaned up?
