### ISSUE TITLE
No guide book, but the setting is enabled

### ISSUE THREAD

**Issue by dark-penguin** [ldtteam/minecolonies#4123]
I see in the mod options that I am supposed to receive some kind of guide book upon joining a world for the first time. That setting is enabled. I start a new singleplayer world, but do not receive any book.

I can't even find any book in JEI (if I have it installed) - I've looked at all items from `@minecolonies`.

### Minecolonies version
minecolonies-1.12.2-0.10.488-RELEASE-universal

### Expected behavior
I create a new singleplayer world, and immediately see a book in my hotbar like many other mods do.

### Actual behaviour
I create a new singleplayer world, and my hotbar and inventory are empty.

Actually, I would prefer to get the book by crafting if needed to avoid overwhelm (I have exactly 100 mods, and several of them want to give me book on join; of course, I've tried it on a newly-created profile with only Minecolonies.) However, I was unable to find any mention of how to get "the guide book" if you don't have it.

I suspect that I may need some other mod installed for the book to appear, but the CurseForge dependencies do not list anything other than Structurize (even if I choose "optional dependencies").

### Steps to reproduce the problem
Start a new single-player game with Minecolonies (default settings, no other mods installed).

**Comment by Raycoms** [comment]
You do need the guidebook mod installed alongside minecolonies to receive it.

**Comment by dark-penguin** [comment]
Oh, I thought so, but there are too many guidebook mods, and I thought I had them all. :) I never even heard about this one.

Then, the issue is "[Guidebook](https://www.curseforge.com/minecraft/mc-mods/guidebook) is not specified on the Curseforge dependencies page". :)

**Comment by Raycoms** [comment]
Yeah because it is not a necessary dependency, it is an optional one

**Comment by dark-penguin** [comment]
But I clicked "Optional dependencies" specifically to make sure I didn't miss anything... It should probably be there to avoid this situation (and to show off your fancy guide book!) :) Or at least the tooltip in the settings should probably indicate that for this setting, another mod is required. But with a name like "Guidebook", it will still be confusing - I thought I have all "guidebook" mods there are.

Still, is it possible to obtain this book in any other way?

**Comment by Raycoms** [comment]
We're currently working on integrating all this information with an "info" button at every building for the particular building to avoid requiring a guidebook at all.

**Comment by dark-penguin** [comment]
Ah, so you don't want to add it and then have to remove it again. That makes sense.

Thank you!
