### ISSUE TITLE
Fisherman not working

### ISSUE THREAD

**Issue by Inomutso** [ldtteam/minecolonies#4127]
### Minecolonies version

Version: MC 1.14.4 - Minecolonie minecolonies-0.10.576-ALPHA - structurize-0.10.201-ALPHA
             Forge-1.14.4-28.1.102

### Expected behavior
Fisherman should start work

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit

Hi Team

my english is not good, but i hope you will understand

from the start on with minecolonies-0.10.356-ALPHA-universal as singleplayer, i can´t get my fisherman to work, he/she is just standing near the water saying "start fishing" (have # Should in development features be enabled # to true) but they never was throwing out the fishing line, having a fishing rod in the hand. I tried another worker, no change, have build two other Fisherman Hut´s, one near a pod from the world, another one with a built pod, shown in your wiki.
The first one has his hut near a shore at the coast. No matter what i do, they do not want to start fishing, sometimes also saying "searching_water", walking into the water and swimming around there. 

i have minecolonies-0.10.576-ALPHA and structurize-0.10.201-ALPHA on Forge-1.14.4-28.1.102, but the Fisherman issue is from the beginning on minecolonies-1.12.2-0.10.310-ALPHA-universal, with no other mods running. Playing with German Language

I have a colonie running on MC 1.12.2 on a server for years now, with 65 Citizens living in, but there i had never these issues with the Fisherman or Lumberjack, just a few probs with them, that you have fixed already.

i could not find anyone else saying anything about this issue on Git or somewhere else, so i am just wondering, what is going wrong here

would be nice, if you have an idea
 
kind regards

**Comment by Asherslab** [comment]
Seperate github issues for seperate in game issues please

**Comment by Inomutso** [comment]
minecolonies-0.10.603-ALPHA-universal

Hi Team

I have an update on this issue, just when i saw the issue in #4181 "Fisherman not stopping fishing"
I have tried to set my Colonie from "friendly" to "normal" where I get Mobs.
Then I have the same behavior as shown in Issue #4181, the fisherman is throwing out the rod, never pulling it back and also not catching anything, so the fisherman is staying always on level 0. Normally I play in "friendly" mode

kind regards

Inomutso

**Comment by Raycoms** [comment]
#4181 is happening to us as well, although this one here I can't reproduce he is fishing well for me, do you have any fishing mods?

**Comment by Inomutso** [comment]
Hi there
as you have asked, I have no fishing Mod on this world
here are the Mods / System, that i play with in a friendly Singelplayer World

worldedit-forge-mc1.14.4-7.0.1         -> you should know about
cfm-7.0.0-pre11-mc1.14.4                -> this is Mr.Crayfish´s furniture Mod
structurize-0.10.201-ALPHA
minecolonies-0.10.603-ALPHA-universal

as described in #4127, I just get a change in the behavior from both fishermen, (that is described in #4181) when i change from playing "friendly" in the MC Launcher Options, to "normal" where Mobs are spawning.

even when I take out the extra Mods, it stays the same, no fishing at all or not catching anything.
This was from the beginning on, when I started this world with the MC 1.14.4 Version (singleplayer)

Hint & Question on this :

I have minecolonies-1.12.2-0.10.1374-PR-universal on my 1.12.2 Server, with this the issue #4156
has been fixed and the server could start again.

Thince I have minecolonies-1.12.2-0.10.1374-PR-universal on my server, i have found a Problem with
one of my two fisherman. He did not work anymore ! Could not bring him back to work. This was my
first fisherman in this Colonie and I never had any Problems with him. But maybe he was getting to
old and so I fired him and got anotherone for this Job. The old one, came in the morning first into the
Hut, then walked to the water, stayed there for a while, not throwing out his rod and then started to swim in the Pod, from one end the other, than he walked back to the Hut and the same behavior started again, whole day long.
For me that maybe looks like a Pathfindig Issue that I found in #4127, where the fisherman says quiet often "searching_water" and then swims around in the water for a while.
Some of my many fisherman on 1.14.4. have drowned with this behavior.
The other fisherman that I have in the 1.12.2 Version is still ok and working a usual.

Question here is:
should / can I get Back to the current 1.12.2-0.10.617-ALPHA Version with my 1.12.2 Server 

thx and kind regards

Inomutso

**Comment by Inomutso** [comment]
Ping

**Comment by RZiegler979** [comment]
Minecolonies version
Version: 0.10.655-BETA

Expected behavior
Fisherman keeps fishing when provided with enchantment free rods and food.

Actual behaviour
Fisherman casts line once or twice then stands around indefinitely until fired or the game is restarted.

Steps to reproduce the problem
Install mod, build fishing hut, provide with supplies.

As a side note I do have quite a few mods installed. None that should conflict with mine colonies fisherman behavior. If anyone is aware of a conflicting mod though please let me know.

**Comment by keybladegames** [comment]
My fisherman doesnt fish much. She has some fish now and then but not as much for someones hut is right next to the ocean
