### ISSUE TITLE
Unable to craft town hall block

### ISSUE THREAD

**Issue by forylla** [ldtteam/minecolonies#4128]
Version: 0.10.488-RELEASE-universal

### Expected behavior
I should be able to craft a town hall block using 5 planks and 2 building tools

### Actual behaviour
I am unable to use this recipe to craft a town hall block, I place the materials in the crafting table and nothing comes up. I have also tried using planks from different types of trees and none of them work either. The only way I am able to obtain the town hall block is by going to creative mode and giving myself one.

### Steps to reproduce the problem

1. Place 5 planks in a U-shape in a crafting table
2. Place 2 building tools in the middle and upper-middle slots
3. Town hall block does not appear in the product slot

**Comment by Asherslab** [comment]
You must have placed a supply item previously
