### ISSUE TITLE
Duplicate citizen?

### ISSUE THREAD

**Issue by nekatu** [ldtteam/minecolonies#413]
Not sure if it's a big problem or not, but seems to have started showing up in the most recent builds; I'm assuming as part of the unique citizen tests you guys are doing?

### Minecolonies version

version 0.6.2195

### Error

[minecolonies]: EntityCitizen '81be7537-606c-454c-a13f-1f3b14d0690f' attempting to register with Colony #1 as Citizen #8, but already have a citizen ('81be7537-606c-454c-a13f-1f3b14d0690f')

### Error

[latest.zip](https://github.com/Minecolonies/minecolonies/files/680405/latest.zip)
[fml-server-latest.zip](https://github.com/Minecolonies/minecolonies/files/680404/fml-server-latest.zip)

**Comment by nojo121** [comment]
It's still in progress so it has nothing to do with the unique names.
We'll see what we can do!

**Comment by Raycoms** [comment]
No that's normal. That's because minecraft does strange things with
entities. Always happened =D

2017-01-02 8:31 GMT-02:00 nojo121 <notifications@github.com>:

**Comment by nekatu** [comment]
Noted, Thanks!
