### ISSUE TITLE
Citizen's Names Not Appearing

### ISSUE THREAD

**Issue by bubblebumper** [ldtteam/minecolonies#4130]
### Minecolonies version

Version: minecolonies-0.10.493-RELEASE and structurize-0.10.193-ALPHA and 1.14.4-forge-28.1.30

### Expected behavior

-  The names would be appearing in the UIs

### Actual behaviour

- The names are invisible. I am still able to click on citizens but cannot see which ones.

 
<img width="1440" alt="Screen Shot 2019-12-08 at 4 56 15 PM" src="https://user-images.githubusercontent.com/58672291/70399770-bc8b4f00-19db-11ea-97e8-568bfa1d8bea.png">
<img width="1440" alt="Screen Shot 2019-12-08 at 4 58 32 PM" src="https://user-images.githubusercontent.com/58672291/70399813-070ccb80-19dc-11ea-993d-02d0cd9606a2.png">
<img width="1440" alt="Screen Shot 2019-12-08 at 4 59 54 PM" src="https://user-images.githubusercontent.com/58672291/70399848-36bbd380-19dc-11ea-9bfc-dc483be3507c.png">

### Steps to reproduce the problem

1.  Download the the different versions mentioned?
2.  Put the mine colonies and structurize .jar files in the mods folder
3.  Launch Forge and play a new world realizing the UIs are wonky
4. ... Profit

**Comment by bubblebumper** [comment]
I should also mention, I had tried uninstalling and reinstalling MineColonies and Structurize multiple times and tried multiple different versions of Forge

**Comment by Raycoms** [comment]
Should be fixed in the newest alphas.
