### ISSUE TITLE
[1.14.4] Invalid Dist Server

### ISSUE THREAD

**Issue by kreezxil** [ldtteam/minecolonies#4131]
Issue:  0.10.581-alpha crashes dedicated server Forge 1.14.4 build 28.1.104

Notes:
     invalid dist server

crash report:
http://paste.ubuntu.com/p/zddMwFQB5h/

fml server latest:

**Comment by kreezxil** [comment]
seem issue with 0.10.580
http://paste.ubuntu.com/p/WRW7rPJC4p/

noticed that both versions are complaining about blockout too

**Comment by kreezxil** [comment]
headsup 577 loads on the server without issue.

**Comment by Raycoms** [comment]
Fixed
