### ISSUE TITLE
Non power of 2 textures

### ISSUE THREAD

**Issue by MatthiasMann** [ldtteam/minecolonies#4133]
### Minecolonies version
Version: minecolonies-0.10.582-ALPHA-universal for MC 1.14.4

### Expected behavior
No warnings while loading the game

### Actual behaviour
[net.minecraft.client.renderer.texture.AtlasTexture/]: Texture minecolonies:blocks/map with size 855x855 limits mip level from 4 to 0

### Steps to reproduce the problem
1. Start game with minecolonies mod
2. Look in latest.log (doesn't require entering a world)

**Comment by Asherslab** [comment]
this is normal and fine
