### ISSUE TITLE
Allow waterlogging of blocks

### ISSUE THREAD

**Issue by WenXin20** [ldtteam/minecolonies#4134]
### Versions
`Minecolonies v0.10.581-ALPHA`
`Structurize v0.10.201-ALPHA`
`Minecraft v1.14.4`
`Forge v28.1.44`

### Expected behavior
- All blocks should be able to waterlog, similarly to shingle stairs.

### Actual behavior
- Currently, Shingle Slabs and Timber Frames cannot be waterlogged. Allowing this would add more immersion to the game.
- Block Huts, Scarecrow, Drying Racks, Construction Tape, etc. from Minecolonies could also be allowed to waterlogged.

### Steps to reproduce the problem

1. Place Blocks Underwater
4. Profit

![2019-10-12_02 15 11](https://user-images.githubusercontent.com/12000593/66696932-2adeba00-ec96-11e9-9fb1-b4da23b58083.png)

**Comment by Raycoms** [comment]
Sorry, that would require as far as I know a lot of extra models to make that work for the different sides etc.
