### ISSUE TITLE
1.12.2 Smeltery ore delivery issues

### ISSUE THREAD

**Issue by Kriiks** [ldtteam/minecolonies#4137]
### Minecolonies version

Version: minecolonies-1.12.2-0.10.584-ALPHA

### Expected behavior

Smeltry requests fuel and ore and recieves both in stacks or maximum amount of ore in warehouse.

### Actual behaviour

Often after server reboot I see my smeltery requesting ore and being completely ignored even if I have stacks of ore in warehouse. 
After rehiring a worker, dmans sometimes starts delivering ore (or keep ignoring smeltery requests), but instead of delivering a stack, they deliver one single ore block.
I have 5 dmans, 4 of them have lvl4 huts and one has lvl5 hut, they really should handle more then one block per delivery :)

**Comment by Raycoms** [comment]
should be improved now.
