### ISSUE TITLE
doors and fence gates can not be opened or closed

### ISSUE THREAD

**Issue by Inomutso** [ldtteam/minecolonies#4138]
### Minecolonies version

Version:
 minecolonies-0.10.582-ALPHA
 structurize-0.10.201-ALPHA
 Forge-1.14.4-28.1.102

playing singleplayer / creative mode

### Expected behavior

doors should be automatically close after passing

### Actual behaviour

Hi Team

I notice about a new issue with the workers and citizens in my colonie
This is since minecolonies-0.10.581-ALPHA-universal, what fixed my Problem with the huts.
I saw many cows running around in the colonie and found a huge herd of shep.
I checked what the workers are doing and saw, that they can not open fence gates or doors,
or they can open a fence gate or a door, and this fence gate or door is not closing anymore, when they have passed it. So, they cannot get into the hut or they are leaving the enclosure animal gates open and the animals flee

also an issue in the other houses or huts, the doors are all always open now, whoever is going in our
out a door, the door stays open.
From my first start with a colonie on 1.14.4 I saw an issue with all built Double Doors from Houses or Huts. One of these doors is always built in the wrong way around.

I have tried a few things to fix that, let the Builder repair the hut, bevor i destroyed the doors there,
that did not help, i changed the style for the shepards hut and had it rebuild, no change with the doors.  I changed the worker shepard or cowboy, did not make a change either.
So it is in the whole colonie. Migth be something wrong with the citizens.

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit

**Comment by someaddons** [comment]
fixed in the newest alpha :)
