### ISSUE TITLE
Lumberjack can get stuck in leaves growing trees

### ISSUE THREAD

**Issue by MatthiasMann** [ldtteam/minecolonies#4142]
### Minecolonies version
Version:  minecolonies-0.10.593-RELEASE-universal

### Expected behavior
When a tree grows and it's leaves surround the lumberjack so that (s)he can't move anymore (s)he should start removing leaves to free the way (can just remove all leaves around him/her until pathing works).

### Actual behaviour
Lumberjack stays in the leaves and can't move / sleep / work / eat anymore until a player rescues him/her.

### Steps to reproduce the problem
1. Get some trees to grow around the lumberjack so that all paths are blocked
2. Lumberjack gets stuck
3. No more logs for the colony :(

Btw - this looks a lot like https://github.com/ldtteam/minecolonies/issues/98 - but it still happens and day time doesn't help.

**Comment by Raycoms** [comment]
yeah, it's always been like this, there is a small chance of him getting stuck in those leaves and you gotta help him out. His AI turns off when the leaves are in his head.
