### ISSUE TITLE
stone smelter keep making unnecessary stone

### ISSUE THREAD

**Issue by lebanni** [ldtteam/minecolonies#4144]
### Minecolonies version
Version: 
minecolonies-1.12.2-0.10.592-RELEASE-minimal.jar
structurize-1.12.2-0.10.198-ALPHA.jar
forge-1.12.2-14.23.5.2847-universal.jar

### Expected behavior
Stone smelter smelt requested cobble into stone.

### Actual behaviour
Stone smelter keep smelting cobble into stone. Also the stonemason won't make requested stonebricks with the stone made by the smelter.

All buildings are level 1 medieval birch.

**Comment by Raycoms** [comment]
They only do this on request, doesn't this work? Did you teach all these recipes?

**Comment by lebanni** [comment]
Yes, I taught the recipes. I made other worlds that were working fine in the past.

**Comment by Raycoms** [comment]
Duplicate issue
