### ISSUE TITLE
Can't place Town Hall

### ISSUE THREAD

**Issue by YubarReingok** [ldtteam/minecolonies#4146]
### Minecolonies version 1.10.2

Minecraft 1.12.2

Forge 14.23.5.2844

### Expected behavior
Expect to be able to place town hall and begin new colony

### Actual behaviour
As soon as I go to place my town hall, it allows me into the go into the builder as if I'm placing it. The normal message pops up fine for when placing it the first time. However, once I've picked where I want to place it and click confirm, it tells me that I have already placed a town hall. I've tried using commands to rectify this issue, but it doesn't detect any other town halls or anything else. So I'm unable to even begin building a new colony because it seems to think I've already placed a town hall whenever I click confirm on the placement. Placement worked fine prior to me updating it.

**Comment by Raycoms** [comment]
Please update
