### ISSUE TITLE
Suggestion: Higher Level Builder requests more building materials in advance

### ISSUE THREAD

**Issue by JensBue** [ldtteam/minecolonies#4147]
### Minecolonies version

Version: 0.10.567-ALPHA

### Expected behavior

- I wish the builder could request more than one item/stack at once.
- This would speed up building a lot.
- Maybe every 2-4 level the builder gains one extra "request slot"

### Actual behaviour

- Especially when building/upgrading huts with a lot of different blocks (Builder Hut at higher levels for example) the Deliveryman couldn't get the blocks fast enough, this causes a lot of downtime or Player help.
- But if the Builder request a few Blocks at the same time the building process would be more effective.
- Even if it does not request the blocks in the right order it would help alot.

### Steps to reproduce the problem

1. Upgrade Builder hut, for best example 4 to 5
2. Place everything needed in the warehouse racks
3. Wait a few hours that the building is actually completed...
4. ... No Profit

**Comment by Raycoms** [comment]
Yeah, we got an issue for that already somewhere, a bunch of issues tbf, it's planned
