### ISSUE TITLE
Builder is only using Flint and Steel once, then requesting a unused one

### ISSUE THREAD

**Issue by JensBue** [ldtteam/minecolonies#4148]
### Minecolonies version

Version: 0.10.567-ALPHA

### Expected behavior

- When a building/upgrade requires the use of "Flint and Steel" he will use the one in its inventory, instead of requesting a completly new one.

### Actual behaviour

- Everytime he needs to use Flint and Steel he make a request for a unused one.
- This get's really annoying...

### Steps to reproduce the problem

1. Build or Upgrade a building which needs "Fire". In my Case "Medievalbirchalternative Citizen Hut" from 3 to 4
2. The builder use the Flint of Steel once
3. For the next upgrade he wants a unused one
4. ... Profit

**Comment by Raycoms** [comment]
1.12 or 1.14?

**Comment by JensBue** [comment]
1.14
