### ISSUE TITLE
Suggestion: Crafter not only works on request, but also on treshold

### ISSUE THREAD

**Issue by JensBue** [ldtteam/minecolonies#4149]
### Minecolonies version

Version: 0.10.567-ALPHA

### Expected behavior

- The crafters e.g. Miller, Smelter, etc. will work until a set treshold is reached.

### Actual behaviour

- In the moment everyone is working on request only.
- For example: The builder needs 100 Planks, there are plenty of logs in the warehouse but no planks.
- After the request from the builder he produces the needes planks. This slow things down by alot
- If you can define a treshold of for example four stacks of planks. The builder doesn't need to wait for them to be made.
- Same goes for any other thing made by crafters

**Comment by Raycoms** [comment]
Yeah, a similar thing is planned by @Asherslab , do you have an issue for that already asher?

**Comment by Asherslab** [comment]
Don’t have an issue for it nah, but is already planned yes

**Comment by Raycoms** [comment]
Closed in favor of joint issue.
