### ISSUE TITLE
Suggestion: New item/block to check the stockage of items in the Warehouse

### ISSUE THREAD

**Issue by JensBue** [ldtteam/minecolonies#4150]
### Minecolonies version

Version: 0.10.567-ALPHA

### Expected behavior

- Like the "Ressouce Scroll" or the "Clipboard" make an item/block that shows the stockage of any items in the warehouse with filtering/search possible.
- This would made targeted farming/crafting by the player more easily if he can see whats missing or on low treshold in the moment.

### Actual behaviour

- There is no such item/possibility afaik.

**Comment by Raycoms** [comment]
That's actually planned yes.

**Comment by Raycoms** [comment]
Closed in favor of joint issue.
