### ISSUE TITLE
Deliverymen stuck

### ISSUE THREAD

**Issue by lebanni** [ldtteam/minecolonies#4153]
### Minecolonies version
Version: 
minecolonies-1.12.2-0.10.598-ALPHA-minimal.jar
structurize-1.12.2-0.10.198-ALPHA.jar
forge-1.12.2-14.23.5.2847-universal.jar

### Expected behavior
Deliverymen going from chest to chest collecting an distributing items.

### Actual behaviour
They stop working and are stuck at the warehouse chest. Sometimes responding to the builder request.

The issue didn't start with this latest version but some versions before.

**Comment by lebanni** [comment]
v 0.10.599
I don't think it's fixed. Dmen not collecting. I tried to rehire them, issued several rs resets, no results.

**Comment by zeno-desaqqara** [comment]
I'm having the same issue, in 1.12.2-0.10.592-RELEASE. It's a bit game-breaking when it happens!

**Comment by Raycoms** [comment]
@someaddons is working on it

**Comment by lebanni** [comment]
minecolonies-1.12.2-0.10.617-ALPHA-minimal.jar
Issue Still happening. And d-men seem not collecting all buildings when they work.
