### ISSUE TITLE
Server crashes -- Entity being ticked --

### ISSUE THREAD

**Issue by Inomutso** [ldtteam/minecolonies#4156]
### Minecolonies version

Version: forge-1.12.2-14.23.5.2836-universal 
 minecolonies-1.12.2-0.10.599-ALPHA-universal
 structurize-1.12.2-0.10.124-ALPHA
 

### Expected behavior

-  Server should start 

### Actual behaviour

-  Server is crashing, while trying to start

### Steps to reproduce the problem

Hi Team 

This time I have an Issue with my 1.12.2 Forge Server (hosted server)
The Server crashed and I cannot bring him back to start up

I have played for a while with minecolonies-1.12.2-0.10.545-ALPHA-universal.jar and nearly everything was fine
At the 12/16/2019 I updated to minecolonies-1.12.2-0.10.592-RELEASE-universal.jar and it was fine, played for a while
At the 12/17/2019 I logged on, checked a few things and left the Server for an hour or so running, with only me loggend on.
When I came back to my System, I found the Server crashed and couldt not startup the Server again.
With minecolonies-1.12.2-0.10.545-ALPHA-universal and all my mods in these Versions, I have already played for weeks, with no big issues or crashes.

Today i tried to update to minecolonies-1.12.2-0.10.599-ALPHA-universal.jar, just to see if there was any change. The Server crashed again, while stating up. In the crash log I can find

-- Entity being ticked --
Details:
	Entity Type: minecolonies:sitting_entity (com.minecolonies.coremod.entity.SittingEntity)
	Entity ID: 439
	Entity Name: entity.SITTING_ENTITY.name
	Entity's Exact location: 107.62, 72.00, 582.57
	Entity's Block location: World: (107,72,582), Chunk: (at 11,4,6 in 6,36; contains blocks 96,0,576 to 111,255,591), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,0,512 to 511,255,1023)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: [EntityCitizen['Charity S. Gorney'/440, l='world', x=107.62, y=72.38, z=582.57]]
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
	
so it might be, that one of my Guards fell asleep in maybe one of Mr.Crayfish cars, but I am not sure
I have tried to start the Server with deactivated Mr.Crayfishs Vehicle Mod, but no change, the Server still crashes with the same issue

I have added the Server Logs here from the 17. and 18. maybe you can see more

Hope you will have an idea to fix this some way

Best Regards

Inomutso

[Inomutso_20191218_Server_Log.zip](https://github.com/ldtteam/minecolonies/files/3980875/Inomutso_20191218_Server_Log.zip)

**Comment by Asherslab** [comment]
@someaddons 

Also please provide the server log text file in the form of a gist not a zip file upload

**Comment by Inomutso** [comment]
I have saved the logfiles here, but there where a few issues while saving them there (timeout)
Hope you can see them there, else i will try again

https://gist.github.com/Inomutso/8a635f96ff42846d228e0cebd7a3e50a

**Comment by Raycoms** [comment]
@someaddons was this fixed?

**Comment by Inomutso** [comment]
Hi there

Sorry, but it is still the same issue. I have updatet to minecolonies-1.12.2-0.10.601-ALPHA-universal,
but the server is still crashing on start with this NullPointerException

-- Entity being ticked --
Details:
	Entity Type: minecolonies:sitting_entity (com.minecolonies.coremod.entity.SittingEntity)
	Entity ID: 439
	Entity Name: entity.SITTING_ENTITY.name
	Entity's Exact location: 107.62, 72.00, 582.57
	Entity's Block location: World: (107,72,582), Chunk: (at 11,4,6 in 6,36; contains blocks 96,0,576 to 111,255,591), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,0,512 to 511,255,1023)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: [EntityCitizen['Charity S. Gorney'/440, l='world', x=107.62, y=72.38, z=582.57]]
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

I hope there is a way to fix this, would be very sad if I had to give up the server, after building him 2 years, or have to reset him with an old backup.

and also a hint on the Guards feature with the guards on 1.14.4 or also on 1.12.2
Guards from the Guard Tower (not from Barracks) are mostly sitting down to sleep for a while,
even if they have walked around only 30-40 Blocks, so they are mostly sleeping. They do not notice any Mobs, Barbarians or Pirates around them. Normally the server is running in friendly mode.

kind regards

Inomutso

**Comment by Raycoms** [comment]
Can we have a better log?

**Comment by Inomutso** [comment]
[debug-2019-12-27_10.52.59.log](https://github.com/ldtteam/minecolonies/files/4005115/debug-2019-12-27_10.52.59.log)

**Comment by Inomutso** [comment]
[latest-2019-12-27_10.52.59.log](https://github.com/ldtteam/minecolonies/files/4005117/latest-2019-12-27_10.52.59.log)

**Comment by Inomutso** [comment]
[crash-2019-12-27_10.52.59-server.txt](https://github.com/ldtteam/minecolonies/files/4005119/crash-2019-12-27_10.52.59-server.txt)

**Comment by Inomutso** [comment]
I hope these logs are ok for you

**Comment by someaddons** [comment]
could you try this version and see if it fixes it?

https://teamcity.minecolonies.com/guestAuth/repository/download/LetSDevTogether_Minecolonies_PullRequests_2_DeployTestServer/33897:id/build/libs/minecolonies-1.12.2-0.10.1370-PR-universal.jar

**Comment by Inomutso** [comment]
Hi there

Server crashes with the same issue.
I have updated to minecolonies-1.12.2-0.10.1370-PR-universal, but the server is still crashing on start with this NullPointerException

-- Entity being ticked --
Details:
	Entity Type: minecolonies:sitting_entity (com.minecolonies.coremod.entity.SittingEntity)
	Entity ID: 439
	Entity Name: entity.SITTING_ENTITY.name
	Entity's Exact location: 107.62, 72.00, 582.57
	Entity's Block location: World: (107,72,582), Chunk: (at 11,4,6 in 6,36; contains blocks 96,0,576 to 111,255,591), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,0,512 to 511,255,1023)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Entity being ticked --
	Entity's Passengers: [EntityCitizen['Charity S. Gorney'/440, l='world', x=107.62, y=72.38, z=582.57]]
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

difference is, that the name in "Entity's Passengers:" is not shown anymore, but the location is the same

kind regards

Inomutso

**Comment by Inomutso** [comment]
[crash-2019-12-27_14.14.48-server.txt](https://github.com/ldtteam/minecolonies/files/4005384/crash-2019-12-27_14.14.48-server.txt)

**Comment by Inomutso** [comment]
[latest-2019-12-27_14.14.48.log](https://github.com/ldtteam/minecolonies/files/4005386/latest-2019-12-27_14.14.48.log)

**Comment by Inomutso** [comment]
[debug-2019-12-27_14.14.48.log](https://github.com/ldtteam/minecolonies/files/4005387/debug-2019-12-27_14.14.48.log)

**Comment by someaddons** [comment]
could you zip up and send us the world? its easier to debug when I can reproduce the error

**Comment by Inomutso** [comment]
ok, so what would you need ? the whole server ? or just the "world" folder and where should i put it ?

**Comment by Raycoms** [comment]
world folder should be fine, google drive for example

**Comment by Inomutso** [comment]
Hi there

so I tried it with Google Drive, hope it works

https://drive.google.com/drive/folders/1_AAKqeTblIdRr26sFGYahsQwhu8VmuqA?usp=sharing

thanks for helping me with that

Regards Inomutso

**Comment by MightyLuu** [comment]
I got identical crashes on my server, (mod version: minecolonies-1.12.2-0.10.599-ALPHA-universal) it looks like a guard got stuck in a Cauldron and crashed the server. Thats only one case, the other one in another colony i cant verify because the server crashes as soon i log on to this location, ill download the map and and try it local without the mod to see what is at he entity location when i have time.
Also the guard standing in a cauldron is no problem most of the time, as they do it all the time, even right now. Maybe it crashes when they try to sit down and sleep in there?

**Comment by Inomutso** [comment]
Hi Guys
Happy new year alltogether
is there a chance that you can look for the Issue ?
would be nice, if the kids couldt play on our server again
thx & best regards
Inomutso

**Comment by hotluck** [comment]
Thank goodness I'm not the only one getting this. In any existing world I was using minecolonies in, it gets this error immediately, and any new world where I make a start using minecolonies (get as far as putting down the town hall block) crashes within about 10 minutes, and the latest time, I was just clearing a piece of dirt with an iron spade!

EDIT: Sorry forgot to mention I am using the 603 alpha version.

And this is the start of the crash log (not all of it) -

Description: Exception in server tick loop

java.lang.IllegalAccessError: null
	at com.minecolonies.coremod.entity.citizen.EntityCitizen.<init>(EntityCitizen.java:229) ~[?:0.10.603-ALPHA] {re:classloading}
	at com.minecolonies.apiimp.initializer.EntityInitializer$$Lambda$2517/952610115.create(Unknown Source) ~[?:?] {}
	at net.minecraft.entity.EntityType.func_200721_a(EntityType.java:412) ~[?:?] {re:classloading}
	at com.minecolonies.coremod.colony.managers.CitizenManager.spawnCitizenOnPosition(CitizenManager.java:196) ~[?:0.10.603-ALPHA] {re:classloading}
	at com.minecolonies.coremod.colony.managers.CitizenManager.spawnOrCreateCitizen(CitizenManager.java:167) ~[?:0.10.603-ALPHA] {re:classloading}
	at com.minecolonies.coremod.colony.CitizenData.updateCitizenEntityIfNecessary(CitizenData.java:718) ~[?:0.10.603-ALPHA] {re:classloading}
	at com.minecolonies.coremod.colony.managers.CitizenManager$$Lambda$5499/2122639064.accept(Unknown Source) ~[?:?]

**Comment by someaddons** [comment]
would be nice if one of you could try this version, it should fix the issue: https://teamcity.minecolonies.com/guestAuth/repository/download/LetSDevTogether_Minecolonies_PullRequests_2_DeployTestServer/33919:id/build/libs/minecolonies-1.12.2-0.10.1374-PR-universal.jar

At least it did for me locally :D

**Comment by hotluck** [comment]
Sorry, didn't notice that the OP was talking about 1.12...I was talking about 1.14 so have you got a version to test for that version?

**Comment by someaddons** [comment]
not yet, gonna do the 1.14 when 1.12 is finished

**Comment by Inomutso** [comment]
Hi Team
With minecolonies-1.12.2-0.10.1374-PR-universal.jar the Issue has been fixed !
We are happy and thanks a lot. I will let the server run for a while, see what happens,
but anyway, big thank you from the kids too
I leave this issue open for a moment, just to see, if something new will happen
kind regards
Inomusto

**Comment by hotluck** [comment]
I take it that as you have closed this, 1.14 has also been fixed?
