### ISSUE TITLE
Textures not showing on the Lumberjack Hut block 1.14.4

### ISSUE THREAD

**Issue by Earendilgrey** [ldtteam/minecolonies#4157]
The textures aren't showing on the Lumberjack Working station, just showing the pink and black block.  Shows fine in the inventory, just not when placed.
![2019-12-18_21 06 19](https://user-images.githubusercontent.com/7344454/71141741-c3377480-21da-11ea-9280-d9f76aa1dec9.png)

**Comment by Asherslab** [comment]
Known, forge issue. nothing we can do
