### ISSUE TITLE
Crafter Request system uses wrong amount of resources

### ISSUE THREAD

**Issue by MineShadow7** [ldtteam/minecolonies#4158]
Version:  Minecraft 1.14.4 forge - 28.1.99
Minecolonies Version 0.10.596 ALPHA

How to reproduce: unknown. 
I'll attach screenshots and a world in zip. 
(Since GitHub can't process screenshots for some reason)

Full Mods list: 
betterwithminecolonies-1.14.4-1.8.9
blockdrops-1.14.4-1.0.2
Clumps-4.0.0
EnchantmentDescriptions-1.14.4-1.3.8
ironchest-1.14.4-9.1.5
jei-1.14.4-6.0.0.26
minecolonies-0.10.596-ALPHA-universal
OreExcavation-1.6.145
structurize-0.10.201-ALPHA

Zip files attached - https://www.dropbox.com/s/uu5urusziq0ftt4/Minecolonies%20Crafter%20RS%20Issue.zip?dl=0

**Comment by Raycoms** [comment]
Duplicate issue
