### ISSUE TITLE
Sometimes Crafters keep on making resources until request is fullfilled

### ISSUE THREAD

**Issue by fr3akb0y** [ldtteam/minecolonies#4159]
### Minecolonies version

Version: minecolonies-0.10.600-ALPHA-universal

### Expected behavior

- Crafters only crafting the requested amount of resources.
### Actual behaviour

- Sometimes when Crafters finish the requested resources they don't successfully send a message to the request system that they finished it to let the dman know they can pick it up. Instead they just keep on secretly requesting resources to try to fullfill the request. This way the dman is being occupied all the time by bringing the crafter the resources he needs (if it is a small amount of resources).

### Steps to reproduce the problem

I tried to reproduce it but I couldnt. It just appears to be super random.

**Comment by Raycoms** [comment]
So you mean the crafter never detects that he finished and crafts indefinitely?

**Comment by fr3akb0y** [comment]
yes it seems that way normally in the (for example) builders request tab when the crafter finished those resources it says that the dman will go and pick it up. Sometimes this doesnt happen and then it gets stuck on that request.

**Comment by fr3akb0y** [comment]
now I have an even weirder behavior. First the builder requested 3 Chests but the sawmill made 21 and at the same time the builder requested 64 Planks. To fulfill the requirements to make the 3 chests the request showed only 2 logs at first (which is not correct) then it got delivered and that number changed to 8? It now stucks on delivering 8 logs for that request and 16 logs for the 64 planks request and the sawmill is just crafting a massive amount of planks and the 2 dmans are busy bringing logs to him all the time.

This is what the request currently looks like (he already made 21 chests that are sitting in the hut block but the dmans are busy delivering logs so they wont pick it up)
![Weird Requests](https://user-images.githubusercontent.com/33865311/71185455-bdde3680-227b-11ea-8c0d-cc8e08cddc93.png)

**Comment by MineShadow7** [comment]
I can support this issue with mine. But then I went around my colony and saw that second builder requested around 7.000 wood planks for sticks and 6.000 planks. All of this was just for 15 fence.

**Comment by fr3akb0y** [comment]
Okay. So now I've observed and fiddled with this issue some more. But somehow the sawmill is not only repeating the process but is also completely broken at the same time. xD
1. Once the crafter stands near the station, items put into his first item slot will somehow return to your inventory if you exit and reenter his inventory
2. If you put any things in other inventory slots during that time they just vanish, not even a rendering bug.
3. Dont know why but the crafter after processing the delivered items he just puts them back to the chest and requests the same amount of the same resources again instead of keeping them in the inventory until all items are successfully crafted.
4. After giving him some planks so he doesnt habe to make them from logs he startet to make 8 of the requested stairs. After that he now keeps the items he crafts in his inventory but startet again the loop (which is delivering 2 logs over and over again atm) and even now that he has the needed resources to craft the requested things he just keeps on requesting more stuff.
Really weird and is confusing me sooo much (I programm a lot and have logical knowledge but I really cant think of any reason here)

**Comment by gswvmware** [comment]
same on 0.10.602-ALPHA

I got a modpack & save where issues below happens constantly, idk if it's helpful to share those files or where could i upload these files to

> Okay. So now I've observed and fiddled with this issue some more. But somehow the sawmill is not only repeating the process but is also completely broken at the same time. xD
> 
> 1. Once the crafter stands near the station, items put into his first item slot will somehow return to your inventory if you exit and reenter his inventory
> 2. If you put any things in other inventory slots during that time they just vanish, not even a rendering bug.
> 3. Dont know why but the crafter after processing the delivered items he just puts them back to the chest and requests the same amount of the same resources again instead of keeping them in the inventory until all items are successfully crafted.
> 4. After giving him some planks so he doesnt habe to make them from logs he startet to make 8 of the requested stairs. After that he now keeps the items he crafts in his inventory but startet again the loop (which is delivering 2 logs over and over again atm) and even now that he has the needed resources to craft the requested things he just keeps on requesting more stuff.
>    Really weird and is confusing me sooo much (I programm a lot and have logical knowledge but I really cant think of any reason here)



> ### Minecolonies version
> Version: minecolonies-0.10.600-ALPHA-universal
> 
> ### Expected behavior
> * Crafters only crafting the requested amount of resources.
> 
> ### Actual behaviour
> * Sometimes when Crafters finish the requested resources they don't successfully send a message to the request system that they finished it to let the dman know they can pick it up. Instead they just keep on secretly requesting resources to try to fullfill the request. This way the dman is being occupied all the time by bringing the crafter the resources he needs (if it is a small amount of resources).
> 
> ### Steps to reproduce the problem
> I tried to reproduce it but I couldnt. It just appears to be super random.

**Comment by raistlain** [comment]
1.12.2-0.10.601 - Alpha

I am also having this issue with the blacksmith and with the sawmill. My blacksmith made ~50ish iron shovels until he ran out of space and I manually canceled the request.

**Comment by jdm311** [comment]
I had this same problem with my stone mason making stacks of cobblestone stairs when only 16 were needed by the miner.
