### ISSUE TITLE
Selecting an NPC shows a different NPC's stat screen and inventory

### ISSUE THREAD

**Issue by nekatu** [ldtteam/minecolonies#416]
### Minecolonies version

version 0.6.2212

### Expected behavior

- Selecting an NPC shows their stats and inventory

### Actual behaviour

- Selecting an NPC shows a different NPC's stats and inventory

### Steps to reproduce the problem

1. Locate any NPC
2. Select NPC

### Logs

[fml-server-latest.zip](https://github.com/Minecolonies/minecolonies/files/680936/fml-server-latest.zip)
[latest.zip](https://github.com/Minecolonies/minecolonies/files/680937/latest.zip)

### Screenshots

Not happening with all NPCs, but definitely with new ones created in one of the recent builds.

NPC name in background, info/inventory screen in foreground
![2017-01-02_14 29 50](https://cloud.githubusercontent.com/assets/1908371/21591070/c6f69b4a-d0f8-11e6-82b9-6b14e1528173.png)
![2017-01-02_14 32 05](https://cloud.githubusercontent.com/assets/1908371/21591058/aec101be-d0f8-11e6-8cdc-7fd525b8f72e.png)
![2017-01-02_14 32 12](https://cloud.githubusercontent.com/assets/1908371/21591059/aec642d2-d0f8-11e6-8347-8bb16951f733.png)

**Comment by nekatu** [comment]
Server crashed again due to the ongoing farm land issue, noticed this in the startup logs-

14:39:41 CONSOLE: thread/WARN]: Tried to add entity minecolonies:citizen but it was marked as removed already
14:39:41 CONSOLE: thread/WARN]: Tried to add entity minecolonies:citizen but it was marked as removed already
14:39:41 CONSOLE: thread/WARN]: Tried to add entity minecolonies:citizen but it was marked as removed already
14:39:41 CONSOLE: thread/WARN]: Tried to add entity minecolonies:citizen but it was marked as removed already
14:39:41 CONSOLE: thread/WARN]: Tried to add entity minecolonies:citizen but it was marked as removed already
14:39:41 CONSOLE: thread/WARN]: Tried to add entity minecolonies:citizen but it was marked as removed already
14:39:41 CONSOLE: thread/WARN]: Tried to add entity minecolonies:citizen but it was marked as removed already
14:39:41 CONSOLE: thread/WARN]: Tried to add entity minecolonies:citizen but it was marked as removed already
14:39:41 CONSOLE: thread/WARN]: Tried to add entity minecolonies:citizen but it was marked as removed already
14:39:41 CONSOLE: thread/WARN]: Tried to add entity minecolonies:citizen but it was marked as removed already
14:39:41 CONSOLE: thread/WARN]: Tried to add entity minecolonies:citizen but it was marked as removed already

**Comment by Raycoms** [comment]
Yes we noticed that We're working on it

2017-01-02 12:41 GMT-02:00 nekatu <notifications@github.com>:

**Comment by nekatu** [comment]
Figured you'd be on it! ;-)

**Comment by Raycoms** [comment]
Newest in a few mins should be fixed

**Comment by nekatu** [comment]
You guys rock!

**Comment by nekatu** [comment]
Looking good! Nice work. 👍
