### ISSUE TITLE
Guard death message not showing correctly

### ISSUE THREAD

**Issue by GanthorPrime** [ldtteam/minecolonies#4165]
### Minecolonies version

Version: minecolonies-1.12.2-0.10.601-ALPHA

### Expected behavior

On guard death, an information chat messagge is displayed showing wo died and coordinates, like in previous versions.

### Actual behaviour

On guard death, the following is the only info yo see in the chat: 'block.blockhuttownhall.messageworkerdead'

### Steps to reproduce the problem

1.- update to latest alphas, the ones that incorporate the rol chat system
2.- wait until a guard dies

**Comment by GanthorPrime** [comment]
In lang file added this and repacked the jar (client and server) to see coordinates on colonists deaths again

block.blockhuttownhall.messagecolonistdead=The colonist %s has died at %d %d %d of %s!
block.blockhuttownhall.messageworkerdead=The %s %s has died at %d %d %d of %s!

in replace of

tile.blockHutTownHall.messageColonistDead=The colonist %s has died at %d %d %d of %s!
tile.blockHutTownHall.messageWorkerDead=The %s %s has died at %d %d %d of %s!

**Comment by Raycoms** [comment]
fixed in next patch

**Comment by jinkhya** [comment]
Hello, 
I just got that error message with minecolonies-1.12.2-0.10.714-RELEASE-universal.jar

**Comment by SirOutlander** [comment]
Hello,
Same on minecolonies-1.12.2-0.11.804-RELEASE-universal
