### ISSUE TITLE
Townhall GUI citizen/jobs info page lost

### ISSUE THREAD

**Issue by GanthorPrime** [ldtteam/minecolonies#4166]
### Minecolonies version

Version: minecolonies-1.12.2-0.10.601-ALPHA

### Expected behavior

In previous versions, the town hall GUi got a page showing a resume of citizens and jobs assignments

### Actual behaviour

The page is lost, no way to find it again

### Steps to reproduce the problem

Update to latests alphas, check for the mentioned information page in the townhall GUI

**Comment by Raycoms** [comment]
Just verified, it's still there =)

**Comment by Raycoms** [comment]
![image](https://user-images.githubusercontent.com/6438347/71489830-61908f00-2806-11ea-8471-9cd2fb9dc2bc.png)

**Comment by GanthorPrime** [comment]
we tested a bunch of versions with forge 2768 and found the specific version that broke this for us.
Is minecolonies-1.12.2-0.10.584-ALPHA-universal.jar.

Maybe this has something to do with the OS languaje (we use windows spanish lang)
