### ISSUE TITLE
[1.14.4] Crash moving items in Colony inventories.

### ISSUE THREAD

**Issue by ghost** [ldtteam/minecolonies#4169]
### Minecolonies version

Version: 0.10.600

### Expected behavior
Shift-click, right-click, and left-click items to move them around inventories, and remove items from a Colony's rack/hut inventory

- 

### Actual behavior
Game soft locks for 5-10 seconds, hard locks, then crashes after shift-clicking/moving items in and out of Minecolonies Inventories.

### Steps to reproduce the problem
1. Build/Upgrade a Colony Hut (any type should work)
2. Wait until items end up in that inventory (or place them in)
3. Right-click storage inventory (hut block, or storage rack)
4. Move items into or out of the Minecolonies inventory GUI
5. May not crash after 1st item, try moving 2-4 stacks.
6. Game freezes then crash.
[crash-2019-12-21_17.53.13-client.txt](https://github.com/ldtteam/minecolonies/files/3992062/crash-2019-12-21_17.53.13-client.txt)

**Comment by Raycoms** [comment]
Does this happen always when you do this? Or at least regularly?
I tried a lot and couldn't reproduce it.

**Comment by ghost** [comment]
It is fairly consistent. I can sometimes move a few items around, but more often than not it crashes it. I can probably upload a screencapture of how exactly it crashes if that's helpful.
________________________________

**Comment by Raycoms** [comment]
Should work fine in the newest.
