### ISSUE TITLE
Citizen clone spawner...

### ISSUE THREAD

**Issue by nekatu** [ldtteam/minecolonies#417]
Citizens appear to be spawning far above the number of max citizen count, and while each new NPC has a unique name they all appear to be a clone (from the inventory and stat screen) of the last NPC that was generated. This continues as each new NPC is generated, changing the stat and inventory screens for all the recently spawned NPCs to that of the new NPC.

Only noticed the problem in 2212, but may have been there as far back as 2200.

### Minecolonies version

version 0.6.2212

### Steps to reproduce error

Related to issue #416 

1. Wait in Town Hall
2. Watch the chaos unfold...

### Logs

[fml-server-latest.zip](https://github.com/Minecolonies/minecolonies/files/680951/fml-server-latest.zip)
[latest.zip](https://github.com/Minecolonies/minecolonies/files/680952/latest.zip)

### Screenshots

![2017-01-02_14 48 07](https://cloud.githubusercontent.com/assets/1908371/21591362/2ed18570-d0fb-11e6-8309-adf345c7157a.png)
![2017-01-02_14 48 19](https://cloud.githubusercontent.com/assets/1908371/21591361/2ecdc1ec-d0fb-11e6-945f-dcde6cdd20ae.png)
![2017-01-02_14 50 07](https://cloud.githubusercontent.com/assets/1908371/21591363/2ed5b47e-d0fb-11e6-95e5-5e25b135c816.png)
![2017-01-02_14 50 14](https://cloud.githubusercontent.com/assets/1908371/21591364/2ed5e638-d0fb-11e6-8a65-b8bd3b24edc1.png)
![2017-01-02_14 50 34](https://cloud.githubusercontent.com/assets/1908371/21591365/2ed6297c-d0fb-11e6-841b-0e433f6aacdd.png)
![2017-01-02_14 50 44](https://cloud.githubusercontent.com/assets/1908371/21591366/2ed6bbf8-d0fb-11e6-852a-8e8aebf30157.png)
![2017-01-02_14 53 00](https://cloud.githubusercontent.com/assets/1908371/21591367/2ee1bd96-d0fb-11e6-823d-34d083e17237.png)

**Comment by Raycoms** [comment]
like the previous issue. Working on it =D

2017-01-02 12:55 GMT-02:00 nekatu <notifications@github.com>:

**Comment by nekatu** [comment]
Go Team! ;-)

**Comment by Raycoms** [comment]
Newest in a few mins should be fixed

**Comment by nekatu** [comment]
👍

**Comment by nekatu** [comment]
Looks great, thanks for that! :-)
