### ISSUE TITLE
[Feature] Hotel Hut or configurable size citizens hut (in persons count)

### ISSUE THREAD

**Issue by specklogan** [ldtteam/minecolonies#4170]
### Minecolonies version
0.10.601-ALPHA
Version: 
1.12.2
### Expected behavior
Either a hotel hut, which houses more people in a single space, yet much larger, requires more resources and certain amenities like paper, cookies, etc. 
Or
Customizable sized citizens hut which will be able to be configured to allow more citizens to be 'housed' 

### Actual behaviour
Maximum limit of 5 persons at level 5 citizens hut.

**Comment by Asherslab** [comment]
Most likely if we implemented a high capacity housing hut it’d have a decent caveat, most likely very bad happiness debuf, or else something of the like

**Comment by lunadragnstar** [comment]
Hotel would be nice to allow new citizens to move in without a house, but they should complain more that they want a house.

**Comment by Raycoms** [comment]
Closed in favor of joint issue.
