### ISSUE TITLE
LV 1 Combat academy not working

### ISSUE THREAD

**Issue by gswvmware** [ldtteam/minecolonies#4173]
### Minecolonies version

Version: 0.10.602-ALPHA

### Expected behavior

- Citizens train & level up in LV 1 combat academy.

### Actual behaviour

- Citizens hired by LV 1 combat academy keep wandering in/around the academy. They will never practice swinging/blocking, neither gain any exp.
When upgraded to LV 2, citizens may start training.
Is this intended?

### Steps to reproduce the problem

1. Build a combat academy.
2. Hire a citizen.
3. Fullfill any of the citizen's request.
4. ... Profit

**Comment by gswvmware** [comment]
wait a minute
it's working now

**Comment by Raycoms** [comment]
@gswvmware which style is this?

@lunadragnstar I think something must be missing in this schematic

**Comment by gswvmware** [comment]
Wooden, birch and nordic as far as i know.

**Comment by jdm311** [comment]
I'm noticing the same problem with medieval oak lvl 1.

**Comment by lunadragnstar** [comment]
I'm not showing any issues with the schematics.

**Comment by Raycoms** [comment]
Fixed, remove jack o lantern, repair building to fix it.
