### ISSUE TITLE
Crash after Crafter picking up item

### ISSUE THREAD

**Issue by MineShadow7** [ldtteam/minecolonies#4175]
Version: minecolonies-0.10.603-ALPHA-universal Minecraft 1.14.4

### Actual behaviour

- Crafter picks up item and the game crashes 

### Steps to reproduce the problem
This is what happened in detail

1. Crafter crafts oak stairs
2. I drop oak planks
3. Game crashes right after pick up sound
4. ... not really gained any profit but here is my log - 

[crash-2019-12-25_19.52.43-server.txt](https://github.com/ldtteam/minecolonies/files/4000647/crash-2019-12-25_19.52.43-server.txt)

**Comment by Raycoms** [comment]
fixed
