### ISSUE TITLE
Tool of Class Unknown

### ISSUE THREAD

**Issue by WikiNation-sudo** [ldtteam/minecolonies#4177]
Version: minecolonies-0.10.603-ALPHA-universal
Minecraft Version: 1.14.4

I was expecting it to start construction as soon as I gave it the required resources.
I'm trying to build the acacia builder's hut so I would expect to start construction so I can build other buildings
 
The builder just stands there next to the builder hut block doing nothing except giving me requests for "Unknown".
This happens with every person I employ as a builder. At the moment I'm running this with the Valhelsia mod pack and this is my first colony. I gave all the required resources and gave them a wooden axe, shovel and other wooden tools but they won't start building. At the start they had requests and I gave them resources and I got to fulfill them now it won't give me the chance to fulfill them and they won't start building. The surrounding area is totally flat.

![2019-12-26_13 23 42](https://user-images.githubusercontent.com/59255761/71479353-f1750f80-27eb-11ea-84cc-e9973f85f6f9.png)
![2019-12-26_14 26 25](https://user-images.githubusercontent.com/59255761/71479356-f4700000-27eb-11ea-8bee-68335b6f0613.png)
![2019-12-26_14 26 30](https://user-images.githubusercontent.com/59255761/71479359-f6d25a00-27eb-11ea-8bcd-22d835d5614e.png)
![2019-12-26_14 26 52](https://user-images.githubusercontent.com/59255761/71479363-f934b400-27eb-11ea-8714-1cdf4fde54f1.png)

1.Place Town Hall Block 
2. Wait for first civ
3.Place down hut block
4.Employ civ as builder
5. Clicked on "Build" button in build options
6.Give all resources
I'm not sure this happens for other people

**Comment by Raycoms** [comment]
This should be fixed in 603.
But, if this request was created in 602, this can still occur. did you create this world in 603?

**Comment by WikiNation-sudo** [comment]
I just solved it so, the  minecolonies and structurise folders, i deleted them because they probably still had 602 data on them so.... problem solved i guess i hope this helped other valhelsia users too since it still uses 602 i think

**Comment by Raycoms** [comment]
okay, sounds right yes, please re-open if it occurs again in 603.
