### ISSUE TITLE
1.14.4 logs disappears in lumberjack huts inventory 

### ISSUE THREAD

**Issue by perecnicek** [ldtteam/minecolonies#4179]
### Minecolonies version

Version: minecolonies-0.10.593-RELEASE-universal.jar
forge-1.14.4-28.1.107
### Expected behavior

-  Lumberjack mine logs and bring it to store in huts inventory

### Actual behaviour

-  Lumberjack came to huts block store the log but when i open huts inventory logs are nowhere to find and texture of hut is also buged 

https://imgur.com/a/hu3DIzD
### Steps to reproduce the problem

1.  just play the game with this version minecolonies-0.10.593-RELEASE-universal.jar 
i play it with more mods i give here the list of them in screen https://imgur.com/mqfjXoW
2. 
3. 
4. ... Profit

**Comment by perecnicek** [comment]
temporary solution delivery can pick up the logs and bring it to the warehouse

**Comment by Raycoms** [comment]
duplicate
