### ISSUE TITLE
Limited reporting from builder and no details on dead colonists

### ISSUE THREAD

**Issue by nekatu** [ldtteam/minecolonies#418]
### Minecolonies version

Version 0.6.2214 (and as far back as 0.6.2179, at least)
Issue is Likely already on your radar given that these are not public builds that I've been using.

### Expected behavior

- Builder informs you of which activity they are working on when they Start/Finish
- Names of dead colonists are reported along with their location

### Actual behaviour

- Builders just report "Started building" and "Finished building"
- Dead colonists are just reported as "The colonist   has died at   !"

Other recent odd behaviour included a guard not wanting to automatically patrol until I set a manual patrol route and then switched them back to automatic. Before that they just stood at the guard tower.

Also had a Guard Tower upgrade go wrong and report as SupplyShip in the work orders, which involved the Builder levelling the guard tower and a few nearby buildings before I realised what was going on and cancelled the work order. Could just be fluke though, and hasn't happened since.

### Screenshot of console output-

![2017-01-02_17 21 21](https://cloud.githubusercontent.com/assets/1908371/21593576/9b493792-d110-11e6-88e3-620066ab30e7.png)

**Comment by Raycoms** [comment]
Guards only patrol up to towerLevel * 40 distance

2017-01-02 15:28 GMT-02:00 nekatu <notifications@github.com>:

**Comment by nekatu** [comment]
Guard wasn't patrolling at all- I had to set manual patrol points, and then switched back to automatic patrol and she's been fine since. This is my fifth guard, the other four work fine, so could just be fluke, like the SupplyShip build, but the lack of detail on building projects and dead colonists is consistent.

**Comment by Raycoms** [comment]
Yeah I believe that's the same problem as the strange strings.

2017-01-02 15:47 GMT-02:00 nekatu <notifications@github.com>:

**Comment by Falcon7617** [comment]
5th guard problems . . . strange that my 5th guard doesn't even go where I want the guard to go . . . coincidence . . . I think not

**Comment by Raycoms** [comment]
He doesn't patrol, guard, follow, inside the limiter of 40* guardTowerLevel?

2017-01-03 6:25 GMT-02:00 Falcon7617 <notifications@github.com>:

**Comment by Falcon7617** [comment]
I made this post earlier @Raycoms. It is now in the closed instances tab, but my guard would not go to certain areas within the 40 block range, even though it was ~10 blocks and my tower was level one. And . . . I was wrong, this is the third guard tower in my colony. I think it was a height difference.
