### ISSUE TITLE
Losing resources when using the builder UI "required resources" page.

### ISSUE THREAD

**Issue by KorovaMB** [ldtteam/minecolonies#4183]
Minecolonies version
Version: 1.14.4 version 0.10.593 RELEASE-Universal

### Actual behaviour

- This is occuring at Tier 1 builder huts.  I have not progressed further yet.  This never happened to me on previous versions of Minecolonies.

### Steps to reproduce the problem

1. Gather resources.
2. Open up the builder's building GUI
3. Use the small buttons alongside each resource to insert them into the buildings inventory.
4. ... not Profit.  Actually the exact opposite.  Damn underwear gnomes.

**Comment by hotluck** [comment]
I believe this is the same as #4077

**Comment by Raycoms** [comment]
duplicate
