### ISSUE TITLE
Rotation of the hutblock "barrackstower" is ignored.

### ISSUE THREAD

**Issue by carlansor** [ldtteam/minecolonies#4184]
### Minecolonies version

Version: minecolonies-0.10.603-ALPHA-universal

While building a new barracks schematic, i came across a weird behavior. The barrack tower is built rotated 90degrees clockwise. That shouldn't happen, since the barrackstower placeholder placed in the barracks schematics shares the same "facing" attribute as the barrackstower hutblock in the barracks tower schematic. This only happens when a builder builds it. If i paste the schematic with the build wand in creative, it gets placed as it should be. Also, after the builder builds a barrack tower, the hutblock faces the correct way, but the tower gets built rotated. Any idea why this happens or if there's any way to sort this arround?

**Comment by Asherslab** [comment]
If the tower is rotated then it’s an issue with how you scanned the tower, not the barracks

**Comment by carlansor** [comment]
the scan its fine, since when i place a barrack tower with the build tool it gets placed as it should be. The problem is when a builder does the job. The tower gets build rotated 90 degrees clockwise. I fixed it by rotating the barrack tower block 90 degrees counterclockwise. It doesnt match the "facing" attribute between placeholder and tower hutblock. But it works.
*EDIT*
It doesnt. Rotating the hutblock of the barracks tower didnt fix the issue. Will try with the placeholders in the barracks schematic.

**Comment by lunadragnstar** [comment]
I can verify this is an issue. It seems to only work when both barracks towers and placeholders are facing a specific direction. Even if you change both and they match, the rotation gets messed up.

**Comment by GearsOfClockwork** [comment]
![2020-02-14_13 52 50](https://user-images.githubusercontent.com/48742177/74583294-9b268080-4f93-11ea-85cf-17a8d5e72ee0.png)

This still seems to be an issue in minecolonies-1.12.2-0.10.679-RELEASE-universal.jar
