### ISSUE TITLE
Miner runs off to barracks basement

### ISSUE THREAD

**Issue by jdm311** [ldtteam/minecolonies#4186]
### Minecolonies version

Version: minecolonies-0.10.493-RELEASE-universal

### Expected behavior

-  Miner mines as expected

### Actual behaviour

- Miner runs off to barracks basement and stays there. Recall the miner and it repeats itself. It started happening as soon as level 4 or 5 barracks was built. Both mine and barracks are medieval oak style and both are level 5 now. The barracks is in between the townhall and the mine (which is further away). The miner has reached bedrock with no nodes anywhere except level 12 (last level above bedrock) of the mine. I've forced it to work by fencing off the area and preventing the miner from leaving. As soon as a break a hole in the fence, he escapes. Firing/re-hiring or hiring someone else continues the behavior.

**Comment by Asherslab** [comment]
> minecolonies-0.10.493-RELEASE-universal

you're over 100 versions behind, please update

**Comment by jdm311** [comment]
Will do, thanks.

**Comment by jdm311** [comment]
Still exists in minecolonies-0.10.593-RELEASE-universal

**Comment by jdm311** [comment]
When I block all exists, the miner goes down the shaft and does work until hungry. If I leave an exit open, he runs off to the townhall basement (now built). If he's hungry and I let him escape, he will correctly go to the restaurant, but he won't come back unless recalled and will escape unless all exits are again blocked.

**Comment by Raycoms** [comment]
This is a common problem, this happens when the node he tries to mine is blocked off (most likely of gravel or similar).

Either you go on the level he is supposed to work and try to find it. Or you assign a different level and then fire the miner and rehire him afterwards.

**Comment by Raycoms** [comment]
(You can do this in the GUI of the building).
