### ISSUE TITLE
Field won't accept pumpkin seeds

### ISSUE THREAD

**Issue by jdm311** [ldtteam/minecolonies#4187]
### Minecolonies version

Version: minecolonies-0.10.493-RELEASE-universal

### Expected behavior

- Insert pumpkin seeds into field

### Actual behaviour

- Cannot insert pumpkin seeds into field.

### Steps to reproduce the problem

1. Build farm (medieval oak) and insert wheat seeds into the first field.
2. Upgrade farm to level 2 and create 2nd field. 
3.  Try putting pumpkin seeds in field. 
4. ... Profit

**Comment by Asherslab** [comment]
> minecolonies-0.10.493-RELEASE-universal

you're over 100 versions behind, please update

**Comment by jdm311** [comment]
Will do, thanks.

**Comment by jdm311** [comment]
Updated to minecolonies-0.10.593-RELEASE-universal and still seeing the problem. Does updating the mod require a new game?

**Comment by Asherslab** [comment]
No, if it's still there then it's a valid issue

**Comment by jdm311** [comment]
After restarting again, I can place the seeds. Not sure if I did anything different.
