### ISSUE TITLE
Can't place ex-knight/ranger into available home slot

### ISSUE THREAD

**Issue by jdm311** [ldtteam/minecolonies#4188]
### Minecolonies version

Version: minecolonies-0.10.493-RELEASE-universal

### Expected behavior

- Fire knight/ranger from barracks tower, go to citizen home with available slot, and find recently fired vet in list of names to fill that slot.

### Actual behaviour

- The name is not in the list until reset of the game, at which point the ex-vet can be placed.

**Comment by Asherslab** [comment]
> minecolonies-0.10.493-RELEASE-universal

you're over 100 versions behind, please update

**Comment by jdm311** [comment]
Will do, thanks.

**Comment by jdm311** [comment]
Still exists in minecolonies-0.10.593-RELEASE-universal

**Comment by someaddons** [comment]
works for me on the newest minecolonies
