### ISSUE TITLE
Builder doesn't bring the right resources to the target building

### ISSUE THREAD

**Issue by jdm311** [ldtteam/minecolonies#4189]
### Minecolonies version

Version: minecolonies-0.10.493-RELEASE-universal

### Expected behavior

- Builder brings the next needed resources to build the target building.

### Actual behaviour

- On higher tier buildings, there are so many resources that the builder takes with them that aren't needed yet, that several return trips to the builder hut may occur. Watching the inventory of the builder when first getting back to the builder hut shows that the next needed item is put in the inventory, but then a cleanup occurs which may remove this needed item if there are too many items in the builder's inventory. I've seen this happen over a 30mins-1hour time frame where the builder had all the materials needed to upgrade, but made 0% progress due to this issue. The builder spends most time walking back and forth to the hut than progressing the building. This also occurs with grass paths.

### Suggestion

- Instead, clear builder inventory when back at the builder hut and add the next 10 items that will be needed to build the target building.

**Comment by Asherslab** [comment]
> minecolonies-0.10.493-RELEASE-universal

you're over 100 versions behind, please update

**Comment by jdm311** [comment]
Will do, thanks.
