### ISSUE TITLE
Builder bug

### ISSUE THREAD

**Issue by MostExcellent** [ldtteam/minecolonies#419]
### Minecolonies version

version 1.11.2-5.4.0

### Expected behavior

- Builder building shit

### Actual behaviour

-Nothing

### Steps to reproduce the problem

1. Build supply chest/townhall
2.  build builder hut
3. builder sits around smacking nothing in particulat
4. Profit

**Comment by marvin-bitterlich** [comment]
maybe he is currently clearing the area, if he is smacking stuff?

**Comment by MostExcellent** [comment]
Actually he is he is just standing so far away it didn't appear to be doing anything
