### ISSUE TITLE
Request system problem when carrying more than requested

### ISSUE THREAD

**Issue by jdm311** [ldtteam/minecolonies#4190]
### Minecolonies version

Version: minecolonies-0.10.493-RELEASE-universal

### Expected behavior

- Worker asks for exact number of resource and upon fulfilling, worker proceeds.

### Actual behaviour

- If resource can be stacked and amount of resource exceeds the requested amount, the requestor does not process the request and proceed, but rather asks again. For example, the builder asks for 20 cobblestone stairs and I have 30 in my inventory. I fulfill the request and it disappears from the gui for half a second and then returns. The builder has 20 cobblestone stairs at this point, but is still waiting as if I haven't given them yet. If I fulfill again, it gives the remaining 10 cobblestone stairs. Now the builder has all 30 cobblestone stairs, but the request now appears to be processed. If I originally only had 20 cobblestone stairs in my inventory when fulfilling the request, it would have processed as expected.

**Comment by Asherslab** [comment]
> minecolonies-0.10.493-RELEASE-universal

you're over 100 versions behind, please update

**Comment by jdm311** [comment]
Will do, thanks.

**Comment by GanthorPrime** [comment]
Playing in latest alpha: minecolonies-1.12.2-0.10.601-ALPHA and i experienced the described behaviour. This is a long term bug, that i frecuently got around by cancelling the request after giving the materials.

I think @jdm311 pinpoint the key cause: if you have more item count than the requested ones, it seems the request system will retry the request or something like that. I just confirmed that with 2 builders requesting 1 brick in my server

**Comment by jdm311** [comment]
Still exists in minecolonies-0.10.593-RELEASE-universal

**Comment by kedamono** [comment]
And I can confirm that this behavior is still happening in minecolonies-0.10.603-ALPHA-universal.
