### ISSUE TITLE
Firing a knight/ranger from barracks results in funny colonist count

### ISSUE THREAD

**Issue by jdm311** [ldtteam/minecolonies#4191]
### Minecolonies version

Version: minecolonies-0.10.493-RELEASE-universal

### Expected behavior

- Total colonist count to count all colonists correctly: 

   current colonists/total possible

### Actual behaviour

- The total possible is less then the current population. I've seen this issue prevent children from showing up if there was an extra citizen home available. Building another or upgrading a home would fix the ratio and generally 2 children would soon show up. 

![2019-12-29_23 03 26](https://user-images.githubusercontent.com/59353508/71571902-86e4fd80-2a91-11ea-8e3c-56aa975e24d7.png)

**Comment by Asherslab** [comment]
> minecolonies-0.10.493-RELEASE-universal

you're over 100 versions behind, please update

**Comment by jdm311** [comment]
Will do, thanks.

**Comment by jdm311** [comment]
Still exists in minecolonies-0.10.593-RELEASE-universal, and now the employment count ends prematurely. Only about a page worth show up, while scrolling down shows only blank lines thereafter.
