### ISSUE TITLE
I delete the colonie and the town hall item disapear

### ISSUE THREAD

**Issue by Shezis91** [ldtteam/minecolonies#4192]
### Minecolonies version
 
Version: 0.10.600-ALPHA- universal

I want to restart a colony because i have an issue with a worker that request me an unknown item, so i try to resolve it deleting the colonie with the command.

The colony was deleted but, the town hall too and now i can't place an other colony

**Comment by Raycoms** [comment]
You can now craft the townhall item with two build tools (top and mid) and planks around it.
