### ISSUE TITLE
[1.14.4] Nordic miner is destroying his own mineshaft

### ISSUE THREAD

**Issue by MatthiasMann** [ldtteam/minecolonies#4193]
### Minecolonies version
minecolonies-0.10.603-ALPHA-universal
structurize-0.10.201-ALPHA

### Expected behavior
Miner is creating the vertical shaft layer by layer and then moving on to the next layer without destroying the above layers or the ladders.

### Actual behaviour
The miner is building one layer, removes part of the wall where the ladders is placed which causes him to get stuck in the mine shaft (need to recall to his hut and manually fixing the wall and ladders). This can be seen bottom right in the screenshot where I placed cobble stone to repair the ladders.

And he also removes the slabs from the layer above partially:
![2019-12-30_18 09 15](https://user-images.githubusercontent.com/6777029/71592283-f1e51180-2b2f-11ea-84df-ffdba92e4108.png)

### Steps to reproduce the problem
1. Build a nordic miner level 1
2. Assign a worker if not done so automatically
3. Upgrade to nordic miner level 2
4. Watch him destroy his work :(

**Comment by MatthiasMann** [comment]
Picture of damaged ladder:
![2019-12-30_20 38 45](https://user-images.githubusercontent.com/6777029/71598084-ccfb9900-2b45-11ea-8693-11ace7bbb028.png)

**Comment by MatthiasMann** [comment]
Also upgrading the nordic miner from level 2 to 3 blocks the mineshaft entrance:
![2020-01-01_21 38 19](https://user-images.githubusercontent.com/6777029/71645893-1501f380-2cdf-11ea-8e42-1ed4098c7774.png)

**Comment by LordNetro** [comment]
Same problem, please someone help

**Comment by Raycoms** [comment]
@lunadragnstar

**Comment by lunadragnstar** [comment]
Ok, for some reason it looks like it isn't using the updated shafts. I've rescaned them

**Comment by LordNetro** [comment]
@lunadragnstar Any suggestion to fix it, or i have to build another mine?

**Comment by lunadragnstar** [comment]
I've scanned them so when the next update comes out, update and hopefully that fixes it.

**Comment by Raycoms** [comment]
@LordNetro can you check out the newest alpha?

**Comment by MatthiasMann** [comment]
Still not fixed with minecolonies-0.10.607-ALPHA-universal:
![2020-01-05_19 57 56](https://user-images.githubusercontent.com/6777029/71784637-c82b5f00-2ff5-11ea-9a5b-440134c189c1.png)

As you can see the block breaking particles on the fence - the miner is still destroying the newly build layer of the mine (he build it just a few minutes ago).

Edit: I also had to fix the ladder for him as he got himself stuck down there again.

**Comment by MatthiasMann** [comment]
And after that the fences have been replaced and a layer of cobble stone placed:
![2020-01-05_20 29 31](https://user-images.githubusercontent.com/6777029/71784969-4b4eb400-2ffa-11ea-82bf-f5c72283504c.png)
![2020-01-05_20 30 34](https://user-images.githubusercontent.com/6777029/71784970-4ee23b00-2ffa-11ea-904b-fa45f370c0de.png)

And it appears that now the ladder is on the other side of the mine shaft as before the update.

**Comment by LordNetro** [comment]
Yeah, make another type of mine, when they fix it then just change it and thats it

**Comment by MatthiasMann** [comment]
@LordNetro just change the type in the building menu? I never did something like that before

Edit: I'll just build a 2nd miner on the other side of town :) Any recommendation on which one works reliable? In the past the medieval oak was working fine.

**Comment by MatthiasMann** [comment]
This also affects the "stone" miner:
![2020-01-08_23 26 46](https://user-images.githubusercontent.com/6777029/72021507-73464d80-326e-11ea-8e2d-04a14cf3fd11.png)

**Comment by MatthiasMann** [comment]
Is it OK/intended to have level Y:55 twice in the list?
![2020-01-11_01 43 55](https://user-images.githubusercontent.com/6777029/72195692-f05ef780-3413-11ea-8ad0-09d6104cc8f0.png)

I have seen that now several times:
1. Let a miner1 mine to it's maximum depth
2. After it recht it's depth limit it will start mining on the lowest level
3. Upgrade to miner1 to miner2
4. The miner will extend the mineshaft - and now one Y is duplicated in list

**Comment by anakhasilver** [comment]
Effects sandstone builder, too. Have a problem where my sandstone builder keeps tearing down parts of her level 5 miner building to build up a cobblestone wall and block stuff up.

**Comment by lunadragnstar** [comment]
I think this is fixed in the newest update, still a small issue with birch and spacewars, but I will get those fixed next.

**Comment by lunadragnstar** [comment]
All of the miners and shafts should be correct and working properly now.

**Comment by jacluvsya** [comment]
My miner just started doing this Medieval Birch miner 4 in progress to miner 5. minecolonies-1.17.1-1.0.141-ALPHA

![image](https://user-images.githubusercontent.com/93809495/145162120-dcd9afeb-ab12-46e3-88a9-9be910bc95d5.png)

**Comment by uecasm** [comment]
Please discuss on Discord or create a new issue rather than posting to a closed 2 year old issue for an ancient mod version.
