### ISSUE TITLE
Miner needs unkown tool

### ISSUE THREAD

**Issue by 1Nightmare** [ldtteam/minecolonies#4194]
### Minecolonies version
 Miner working.

-  I expect the miner to be collecting ores and such, and just actually working.

### Actual behaviour
 The miner is just standing around with an error message and won't do any work.

- I had the medieval spruce mine upgraded four times when the miner got the error message saying they needed something. When I went to see what it was, the picture was black and said that the tool was unknown. I try to fill it and it will go away for a moment before coming back. I've also tried giving them all the tools I have available and nothing works.

![2020-01-01_10 38 12](https://user-images.githubusercontent.com/59415687/71643125-2fa67f00-2c83-11ea-98dd-e339a3c958a6.png)
![2020-01-01_10 38 16](https://user-images.githubusercontent.com/59415687/71643126-2fa67f00-2c83-11ea-8a7d-5f2b9ca5748a.png)
![2020-01-01_10 38 20](https://user-images.githubusercontent.com/59415687/71643127-2fa67f00-2c83-11ea-8a3a-f20e5ba7d088.png)

### Steps to reproduce the problem
 Um, honestly I'm not sure what you should do to fix this or how to get it to show up in your own game. I'm sorry I can't help you with that.

1. 
2. 
3. 
4. ... Profit

**Comment by AnotherPogo** [comment]
I am seeing the same thing with my builder.  I have tried wooden, stone, iron, and gold tool sets in the inventory.  Doesn't seem to pick up any of them.

![Capture](https://user-images.githubusercontent.com/59422649/71646979-27ab0700-2ca4-11ea-875c-416c694f22f2.PNG)

![Capture2](https://user-images.githubusercontent.com/59422649/71646980-2b3e8e00-2ca4-11ea-93c7-73c464bc5fbd.PNG)

![Capture3](https://user-images.githubusercontent.com/59422649/71646981-31346f00-2ca4-11ea-9333-cd7cc4ceb03d.PNG)



Version Info:
![Capture4](https://user-images.githubusercontent.com/59422649/71646977-1eba3580-2ca4-11ea-8e34-6640853d0e4d.PNG)

**Comment by Asherslab** [comment]
You didn’t fill out the template properly. List your MineColonies version

**Comment by 1Nightmare** [comment]
Oh, my bad! I could swear I did add it in. Sorry about that, I'm using the 0.10.5930-RELEASE.universal.jar I hope that's right. Sorry again....

**Comment by Asherslab** [comment]
that's definitely not a valid version, can you check again please?

**Comment by Raycoms** [comment]
Please try the 603-ALPHA, that one fixes it.
