### ISSUE TITLE
[1.14.4] Florist is standing on the wither rose and dies

### ISSUE THREAD

**Issue by MatthiasMann** [ldtteam/minecolonies#4195]
### Minecolonies version
Version: minecolonies-0.10.603-ALPHA-universal

### Expected behavior
The florist will stay a bit away from the planting beds (composted dirt) so that a spawning wither rose doesn't kill it.

### Actual behaviour
The florist stands on the wither rose and keep taking damage without moving away.

### Steps to reproduce the problem
1. Upgrade your florist to at least level 2 
2. Wait for the florist to stand on one of the planting beds and a wither rose to spawn
4. "the florist luís q. goring has died at 34 68 -248 of wither!"

**Comment by MatthiasMann** [comment]
Actually - why is it creating wither roses in the first place - I thought these should be only optained from a wither fight?

**Comment by Raycoms** [comment]
Will be fixed in next patch (he won't plant those roses anymore)
