### ISSUE TITLE
Crusher doesn't do job daily

### ISSUE THREAD

**Issue by jdm311** [ldtteam/minecolonies#4196]
### Minecolonies version

Version: minecolonies-0.10.593-RELEASE-universal

### Expected behavior

- Everyday the crusher makes requests for the materials needed to crush up to double the max amount. 

### Actual behaviour

-  The crusher doesn't make the request everyday, but only after the builder has built/upgraded the crusher hut, as far as I can tell. Sleeping in a bed right by the crusher hut shows the crusher does nothing the next day, even with the needed resources in his inventory. I've noticed this since first building the crusher hut and currently up to level 4. The crusher hut style is medieval oak.

**Comment by jdm311** [comment]
Does he need to sleep in his bed to reset his worker action?

**Comment by jdm311** [comment]
The Sifter is doing the same thing now, after staying up all night and watching her go home. The crusher looks like he is working again after a few days of doing nothing.

**Comment by jdm311** [comment]
It looks like may you have to help them get into their beds and then they perform their jobs the next day. The sifter was just standing by her bed. Since the sifter and the crusher are the only ones that have daily limits, it seems that they are the only two that need escorting to their beds before you can sleep. The other ones will walk to the their beds in the morning and then go to work. Not sure if this is a bug or desired behavior. If it's desired, then more information should probably be added to the wiki regarding daily max.

**Comment by Raycoms** [comment]
Found the reason this happens, should be able to finish this today.
