### ISSUE TITLE
Colony View Dose Not Exsit Log Spam and unable to access Colocny Blocks

### ISSUE THREAD

**Issue by shivachirr** [ldtteam/minecolonies#420]
### Minecolonies version

curse 1.10.2-0.6.2115

### Expected behavior

Should not happen and should be able to use colony blocks. and get pings if something is wrong with the colony. note my friend owns the colony and i have officer grade access to it

### Actual behaviour

you cant do anything with the colony and nolonger get pings about whats wrong with the colony. and as result the log is spamed with 

"[Netty Local Client IO #0/ERROR] [minecolonies]: Colony view Dose not exsit For ID #1

### Steps to reproduce the problem

Every few Loads at random

Fixed by reloading the world

**Comment by Raycoms** [comment]
That's a random bug we weren't able to reproduce yet.
Very strange bug, probably due to how minecraft fails at loading the world.

2017-01-03 3:39 GMT-02:00 shivachirr <notifications@github.com>:

**Comment by shivachirr** [comment]
the world loads fine everything else works fine so its awerid byg them

**Comment by Raycoms** [comment]
Yeah the world loads fine because minecraft is probably able to recuperate
these errors with itself. We're not yet.

2017-01-03 9:41 GMT-02:00 shivachirr <notifications@github.com>:

**Comment by shivachirr** [comment]
well if i see any change ill tell you

**Comment by shivachirr** [comment]
not sure if you will see this but ive noticed happens more with ever fresh load of minecraft latly
