### ISSUE TITLE
[1.14.4] Villagers getting stuck at 1 block steps after latest update

### ISSUE THREAD

**Issue by MatthiasMann** [ldtteam/minecolonies#4208]
### Minecolonies version
Version:  minecolonies-0.10.610-ALPHA-universal

### Expected behavior
Villagers can jump up 1 block height differences.

### Actual behaviour
They do "micro" jumps and don't get up and don't try to path around it either.

The screenshot shows the height they jump:
![2020-01-06_17 50 05](https://user-images.githubusercontent.com/6777029/71833372-0cc60180-30ad-11ea-9057-35c5085c8cf5.png)

Edit: doesn't happen all the time - eg the builder seems to be having no issues - but my miner can't get to his home and the delivery guy gets stuck often.

### Steps to reproduce the problem
1. Upgrade to .610
2. Watch villagers get stuck

**Comment by Raycoms** [comment]
I'll look into it.

**Comment by Raycoms** [comment]
Fix pushed, thanks for the report.

**Comment by jdm311** [comment]
I have also noticed this. My fisherman hut is near the outer ring of my colony and I sometimes find up to 3 of my deliveryman stuck on the platform near the fisherman hut block. Found in version minecolonies-0.10.593-RELEASE-universal and medieval oak style.

**Comment by Raycoms** [comment]
That's a different bug which should also be fixed in the most recent alphas.
