### ISSUE TITLE
1.14 Ticking error

### ISSUE THREAD

**Issue by hotluck** [ldtteam/minecolonies#4211]
Same as #4156 but for version 603 of 1.14

It was mentioned in that issue that 1.14 would be fixed once 1.12 had been. The issue was then closed off after the OP said 1.12 was working, but there was no mention of whether 1.14 had also been fixed or not, so I have opened this to find out if it has been fixed in 1.14 also.

**Comment by someaddons** [comment]
got any logs for 1.14 on it?

**Comment by hotluck** [comment]
Yes, it's at the bottom of #4156

**Comment by someaddons** [comment]
thats just a small part of the log, please paste the full crash into https://gist.github.com/ and link it here properly

**Comment by hotluck** [comment]
Don't worry about it. I have just installed the latest as I saw there have been quite a few other fixes, and I can get in without the error now, so whatever fixes were done fixed that too :)

**Comment by hotluck** [comment]
Spoke too soon. It just happened again. Just getting the log together for you.

**Comment by someaddons** [comment]
from what I saw in the other issue it could've been a different crash, thats why I'd rather see the logs :D

**Comment by hotluck** [comment]
[crash-2020-01-07_10.21.47-server.txt](https://github.com/ldtteam/minecolonies/files/4030130/crash-2020-01-07_10.21.47-server.txt)

I added the file in your link but didn't know how to link it back in here so I've just uploaded it straight into this comment.

**Comment by someaddons** [comment]
ye this is a different issue, it crashes on citizen spawn

**Comment by someaddons** [comment]
https://gist.github.com/someaddons/29e8bd534ab981e5ec2dfa0e3ff66a5e

**Comment by someaddons** [comment]
could you put your full latest.log into gist.github.com ? just paste the content there and click bottom right create public gist

**Comment by someaddons** [comment]
just saw that your forge version is pretty old and might very well cause the issue, could you update to the newest 1.14 forge and try again? http://files.minecraftforge.net/

**Comment by someaddons** [comment]
closing since it should be fixed

**Comment by hotluck** [comment]
I can confirm this is fixed.
