### ISSUE TITLE
Bakery practically feeding him/herself

### ISSUE THREAD

**Issue by douyabian** [ldtteam/minecolonies#4213]
Version: 0.10.614-ALPHA for 1.14

### Expected behavior
Bakery to bake bread to supply for the rest of the colonists or warehouse

### Actual behaviour
Baker mills the wheat, bakes the bread, gets hungry and eats the bread. Essentially no profit on bread, repeats and levels up but nothing improves. Baker is at level 47 now and still eating her own bread

### Steps to reproduce the problem
1. Build a baker
2. Have a farm/supply wheat
3. Watch the baker bake bread and eat it themselves
4. ...Baker profits?

**Comment by Raycoms** [comment]
Yeah the baker eat their own bread, but there should still be enough left
for the rest of the colony (provided there is enough wheat to produce
enough bread).

Am Di., 7. Jan. 2020 um 17:26 Uhr schrieb douyabian <
notifications@github.com>:
