### ISSUE TITLE
 The settlers do not reproduce.

### ISSUE THREAD

**Issue by jhosmen** [ldtteam/minecolonies#4214]
### Minecolonies version

Version: 1.12.2-0.10.592-REALSE.

### Expected behavior

-  That citizens should reproduce if they have houses to spare.

### Actual behaviour

- Do not reproduce.

### Steps to reproduce the problem

1. Create a colony with a town hall level one, builder hut level two, farm level two, two houses level two two houses level one, lumberman's hut level two, mining level two, a guard tower level 2 and a soul in level 1.

**Comment by Asherslab** [comment]
Do either of your two level two houses have both genders?

**Comment by Raycoms** [comment]
Yeah you need a male and a female living in the same house for this.
