### ISSUE TITLE
1.14.4 Crash

### ISSUE THREAD

**Issue by SadHorizion77210** [ldtteam/minecolonies#4216]
<I am making a bug report due to game crashing 
Minecolonies version

- 

### Actual behaviour

- 

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit

**Comment by SadHorizion77210** [comment]
[crash-2020-01-08_18.11.53-client.txt](https://github.com/ldtteam/minecolonies/files/4034835/crash-2020-01-08_18.11.53-client.txt)
This is the crash report

**Comment by Asherslab** [comment]
Please make a new issue and fill out the issue template properly. 
Also, use a gist to share the log (https://gist.github.com)
