### ISSUE TITLE
Archery 3 stone blueprint requires minecraft:monster_egg (Stone Brick Monster Egg)

### ISSUE THREAD

**Issue by gelonsoft** [ldtteam/minecolonies#4218]
### Minecolonies version

Version: minecolonies-1.12.2-0.10.612-ALPHA-universal.jar

### Expected behavior

Blueprint without monster_egg requirements cause monster_egg could not be crafted in survival without mods.
- 

### Actual behaviour

Blueprint Archery 3 stone requires monster_egg 
- 

### Steps to reproduce the problem

1. Start minecraft survival game with mods, incl. minecolonies
2. Build Archery stone lvl1
3. Upgrade to Archery stone lvl2
4. Upgrade to Archery stone lvl3
5. Stuck on monster_egg requirements

Also, found usage of monster_egg in other schematics:
\src\main\resources\assets\minecolonies\schematics\Jungle\Stonemason3.blueprint
\src\main\resources\assets\minecolonies\schematics\Jungle\Stonemason4.blueprint
\src\main\resources\assets\minecolonies\schematics\Jungle\Stonemason5.blueprint
\src\main\resources\assets\minecolonies\schematics\mesa\Stonemason3.blueprint
\src\main\resources\assets\minecolonies\schematics\mesa\Stonemason4.blueprint
\src\main\resources\assets\minecolonies\schematics\mesa\Stonemason5.blueprint
\src\main\resources\assets\minecolonies\schematics\Sandstone\Stonemason3.blueprint
\src\main\resources\assets\minecolonies\schematics\Sandstone\Stonemason4.blueprint
\src\main\resources\assets\minecolonies\schematics\Sandstone\Stonemason5.blueprint
\src\main\resources\assets\minecolonies\schematics\stone\Archery3.blueprint

**Comment by lunadragnstar** [comment]
I'll look into all of these

**Comment by lunadragnstar** [comment]
Fixed
