### ISSUE TITLE
Lumberjack doesn't pick wood from dynamic trees

### ISSUE THREAD

**Issue by whisper2shade** [ldtteam/minecolonies#4219]
### Minecolonies version

Version: 1.12.2-0.10.592-RELEASE

### Expected behavior

Lumberjack picks all drops from dynamic trees

### Actual behaviour

Lumberjack picks up only 30-50% of drops. Other times he is standing too far for the drops to get into his inventory and then walks away.

### Steps to reproduce the problem

1. be dynamic trees
2. be dark oak trees around lumberjack
3. lumberjack cut only dark oak trees (that's my current setting of the lumberjack - only dark oak acorns)
4. watch
5. start a non-profit ;) (as without drops, there's no profit)

**Comment by shivachirr** [comment]
ive seen this and its sometiems just related to the wood spawns to far from the lumberjack or the lumberjack starts doing something else before it can pick up the wood
