### ISSUE TITLE
Farmer crashes when swiching to the second page of the GUI if there are several fields

### ISSUE THREAD

**Issue by Zarke** [ldtteam/minecolonies#422]
### Minecolonies version

version 1.11 beta v7

### Expected behavior

- second page of he farmer GUI displays all the fields detected by it

### Actual behaviour

- second page of he farmer GUI causes the game to crash if there are more fields set up (in my case it happened when i placed the second field)

### Steps to reproduce the problem

1. Build the farmer hut
2. Hire the farmer and give him/her tools and seeds
3. set up the first field and let farmer do it's thing
4. set up second field and then try to switch to the second page of the farmer GUI

I allso have another problem with the farmer - my farmer just stopped planting seeds and it started
replanting the old ones for no reason (it did not finish the field which is 5x5 block)

**Comment by Raycoms** [comment]
Will be fixed in the next one:
1.11 beta v8	5.10 MB	3 hours ago	1.11.2 +1	0	Under Review

**Comment by Zarke** [comment]
When can we expect the beta v8 btw ?

**Comment by Raycoms** [comment]
As soon as curse approves, in the next hours.

2017-01-03 14:19 GMT-02:00 Zarke <notifications@github.com>:

**Comment by nekatu** [comment]
Same issue I was having- #384
