### ISSUE TITLE
Crash randomly

### ISSUE THREAD

**Issue by carstorm** [ldtteam/minecolonies#4221]
### Minecolonies version

Version: 0.10.603-ALPHA

### Expected behavior

- 
Crashed when just walking around my base

### Actual behaviour

- 
Crashed when at my base, there is a someone elses colony very near to me (edge is about 75 blocks from from base)

### Steps to reproduce the problem

I was simply walking around so it seems pretty random but here is the crash report:
https://pastebin.com/vbVGCNnk

**Comment by Raycoms** [comment]
Please redownload the jar. Something of it must be corrupted.
