### ISSUE TITLE
Library learn rate option? [Suggestion]

### ISSUE THREAD

**Issue by masternetra** [ldtteam/minecolonies#4222]
I noticed there is currently, at least up to 12.2-0.10.592, there is no option in config to adjust the rate of learning/skill improvement from the library. Would like one if possible.

**Comment by someaddons** [comment]
I think the config for them using items to study at an increased rate is enough for that

**Comment by masternetra** [comment]
Ohhh I completely missed the configliststudyitems part I was looking for a rate thing. My bad.
