### ISSUE TITLE
[1.14.4] crash while flying into colony from outside of chunk loading range

### ISSUE THREAD

**Issue by MatthiasMann** [ldtteam/minecolonies#4225]
### Minecolonies version
minecolonies-0.10.616-ALPHA-universal
structurize-0.10.203-ALPHA
performant-1.14.4-1.4

### Expected behavior
No crash

### Actual behaviour
[crash-2020-01-11_00.00.11-server.txt](https://github.com/ldtteam/minecolonies/files/4048507/crash-2020-01-11_00.00.11-server.txt)

### Steps to reproduce the problem
1. I was ~200 blocks away from the colony and made a nether portal and went into the nether
2. Mine stuff you need in the nether (~30 minutes)
3. Go back into the overworld
4. Fly back to the colony (using iron back packs)
5. Crash

**Comment by MatthiasMann** [comment]
After loading the world again, I was still in the nether. Repeating the dimension change and flying back to the colony worked this time without crash. So not sure how to reproduce it or what really caused it.

Maybe it was a class loading order / dependency issue. As I was starting the world next to the nether portal before going into the nether so the colony was not yet loaded.

**Comment by Raycoms** [comment]
Please redownload the jar. Something of it must be corrupted.

**Comment by MatthiasMann** [comment]
The JAR file was and still is intact - as the game is working fine after starting again.

**Comment by Raycoms** [comment]
I mean, when this happens, there is something small missing in the jar
probably. That's the only way this can fail.

Am Sa., 11. Jan. 2020 um 09:33 Uhr schrieb MatthiasMann <
notifications@github.com>:

**Comment by MatthiasMann** [comment]
Class loading from a transformer can also fail if that transformer decides it can't handle the request (eg recursion etc).

In the stack trace you can see that the mod performant (which I think is also from your group) tried to load a Minecolonies class:
	at com.performant.coremod.entity.ai.CustomGoalSelector.func_75774_a(CustomGoalSelector.java:247) ~[?:1.14.4-1.4] {re:classloading}

That's probably the cause why it can't find the file as each mod has it's own class loader.

Are these 2 mods compatible - or should I remove performant when Minecolonies is also installed?
