### ISSUE TITLE
Suggestion: Allow Proximity based build orders for builders.

### ISSUE THREAD

**Issue by mischievousmimi** [ldtteam/minecolonies#4226]
I think that there should be a function to allow build orders to have the order they are done in changed between which one was created first to being based on the proximity to a builder, so that builders will prioritize orders closer (or farther) to them. This can reward players who strategically place builder huts by reducing the amount of time spent walking by their builders and allowing them to get more work done effectively.

It has always been good for games to reward creativity and ingenuity. A system like this, while difficult to make, would both allow for the streamlining of colony jobs and rewarding players for reaching for new heights of skill and creativity. It could also theoretically be applied to other jobs as well.

**Comment by Raycoms** [comment]
Actually, in the build/upgrade GUI you can assign a specific builder (the closest) to this, and only that specific builder will pick up the request.

**Comment by mischievousmimi** [comment]
I'm more of suggesting an automated version of this where you don't have to remember which one of your builders goes where, and they'll automatically choose the closest open order to them over which one was made first.

**Comment by Raycoms** [comment]
Like I said, that's not possible.

I'll give you an example.

You got two builders, one 8 blocks away, one 12 blocks away.

Now, you can design the system in two ways:

a) Auto assign it to the closest, always.

Drawback: Always the one with 8 blocks away gets it, even though he is upgrading something else and the one 12 blocks away is idle.

b) Assign it to the closest available:

Drawback: Sometimes it's not optimal, but at least you don't have to wait eternally.
We chose path b. And we added that no builder over 100 blocks away will be assigned automatically, you have to do that manually.

**Comment by mischievousmimi** [comment]
it's not possible to have a builder automatically pick to the next closest open, available build after finishing up with the one they're working on?

**Comment by Raycoms** [comment]
Buildings are sorted by the date they are created, so the builders pick up the oldest order, else we will have starvation and some builds will never be started.
