### ISSUE TITLE
Combat Acedemy is looking funky

### ISSUE THREAD

**Issue by Paint233** [ldtteam/minecolonies#4227]
So Im using newest version, that being minecolonies-1.12.2-0.10.623-ALPHA-universal.jar  on of course 1.12.2. No shades or resource packs are being used. The block works as usual just looks off.
![HOWGG](https://user-images.githubusercontent.com/59771237/72206955-6afe3600-3459-11ea-94dd-53f89f89e6e8.png)

**Comment by Raycoms** [comment]
working fine for me.
