### ISSUE TITLE
(1.15 mineclolonies render crashes)

### ISSUE THREAD

**Issue by SDUBZ** [ldtteam/minecolonies#4231]
minecolonies: minecolonies-0.10.639-ALPHA-universal
forge: 1.15.1-30-36

getting crashes after placing and building town hall then again with the builder hut

crash reports:

[crash-2020-01-13_22.10.33-client.txt](https://github.com/ldtteam/minecolonies/files/4053250/crash-2020-01-13_22.10.33-client.txt)
[crash-2020-01-13_22.04.00-client.txt](https://github.com/ldtteam/minecolonies/files/4053251/crash-2020-01-13_22.04.00-client.txt)

**Comment by Raycoms** [comment]
Sorry, let me remove those from curse again, they were not supposed to get built there yet.
Yes, rendering is completely broken yet.

**Comment by SDUBZ** [comment]
oh okay thank you :D cant wait until its done
