### ISSUE TITLE
Minecolonies 0.10.593+ crashing Minecraft at launch.

### ISSUE THREAD

**Issue by masternetra** [ldtteam/minecolonies#4232]
### Minecolonies version
Version: 0.10.631-BETA (applies to  as far back as minecolonies-0.10.593 as well)
 

### Expected behavior

Minecraft launches and does it's thing.
 
Minecraft to load up and start loading mods.

### Actual behaviour

Crashes as soon as MC tries to launch.

- 
In addition to using it in the pack I am I've even created a instance where it's only minecolonies and still versions 0.10.593+ simply crash just as the MC windows launches, no modloading attempt or anything windows just flashes up and closes instantly. Switching back to 0.10.592 however still works.

Log: https://pastebin.com/m0BSRs5b

### Steps to reproduce the problem

1. Download a version of minecolonies version 0.10.593 or higher.
2. Move mod to mods folder.
3. Attempt to run game.
4. Crash Instantly.

**Comment by someaddons** [comment]
you're trying to launch 1.12 with the 1.14 version :) 631 doesnt exist on 1.12

**Comment by masternetra** [comment]
oof. I dunno how that happen I was quite certain I was clicking on the 1.12 stuff, maybe I'm more tired then I thought.
