### ISSUE TITLE
building tool did not work normaly

### ISSUE THREAD

**Issue by ferdinandwda** [ldtteam/minecolonies#4233]
if i play this mod i can use building tool but after a few minutes the building tool do not work.
after I do left click using the building tool the building should appear as a thing that we cant touch but we can look but it do not work on me i can fix it my self by relaunching the minecraft but the same thing happen
Minecolonies version:1.12.2
minecraft version:1.12. 2 (forge)

**Comment by someaddons** [comment]
its right click to activate the building tool

**Comment by ferdinandwda** [comment]
@someaddons 
oh yeah i'm sorry i mean right click and at the first time i can make the ghost of the building but after serveral minute i cant do it again and i need to re launching the minecraft after that i can do it again but the same thing happen

**Comment by Raycoms** [comment]
any log to help us?

**Comment by ferdinandwda** [comment]
later i will sent a picture wait ok ty
