### ISSUE TITLE
Crash during spawn villager

### ISSUE THREAD

**Issue by Ibirtem** [ldtteam/minecolonies#4234]
Link on Crash report:
https://github.com/Ibirtem/lmao/blob/master/Crash

**Comment by Asherslab** [comment]
As a note, https://gist.github.com
I mean, putting logs in a repo is a bit strange lol

**Comment by Raycoms** [comment]
Yeah we know, 1.15 is highly experimental yet, please don't report issues yet, we didn't even start testing yet. We're still fixing known issues.
