### ISSUE TITLE
Nordic Miner

### ISSUE THREAD

**Issue by chriskeena** [ldtteam/minecolonies#4235]
### Minecolonies version

Version: 0.10.593-RELEASE-universal

### Expected behavior

- I would expect to see the miner extend teh shaft vertically and build platforms at intervals.

### Actual behaviour

- Miner built spruce platform at 1st level but now is halfway through chopping it out again. I aslo noticed they had earlier removed two of the ladder blocks plus the spruce blocks behind them. These were subsequently replaced by the miner but have now been removed again.

**Comment by chriskeena** [comment]
![2020-01-17_08 53 48](https://user-images.githubusercontent.com/29703373/72572201-e5293180-3915-11ea-992f-37db55dcc60b.png)
After posting it occured to me that the miner was removing the platform in the same patern as when digging the shaft. This sugests the miner has forgotten progress when excavating.
I did also notice weird behaviour when the miner tried to mount the ladder to decend into the shaft after collecting supplies.

**Comment by chriskeena** [comment]
Well, perhaps this is a clue. After updating Forge to 115 I allowed the miner to continue.
I've discovered they botched the placement of the next level creating it a block higher than it should be causing the need to cut out the platform above.

**Comment by chriskeena** [comment]
I'm guessing the ladder is used to measure progress down the shaft during construction. This leads to oddities when the Miner glitches while mounting the ladder.
Why not use the y co-ord of the miners workstation with a +/- offset for teh different miner building designs to set the origin? This gives a value independant of the Miners potential confusion.

**Comment by lunadragnstar** [comment]
I am still testing this, but it takes a while to run these tests and I haven't run into the same issue yet.

**Comment by lunadragnstar** [comment]
closing see #4193
