### ISSUE TITLE
Farmer ignoring damaged tools

### ISSUE THREAD

**Issue by SuiguraTaiki** [ldtteam/minecolonies#4242]
### Minecolonies version
Version: minecolonies-0.10.631-BETA-universal.jar
 

### Expected behavior
Farmer would ask for tools (Shovel and/or Hoe), which when obtained would be used until broken, which would cause for him/her to stop working until a new tool is obtained.

### Actual behaviour
Farmer would ask for tools (Shovel and/or Hoe), which when obtained would be each used once, leaving the slightly damaged tool in their inventory, which would cause for him/her to stop working until a new, undamaged tool is obtained.

### Steps to reproduce the problem
1. Create a new village
2. Build the level 1 Builder's Hut 
3. Build the level 1 Farm
4. Assign a Farmer job to a villager
5. Place a Field block where a farm is supposed to be
6. Give a set of tools and seeds to the farmer.
7. The moment the farmer would work in the field once with each tool, they will get a point of durability damage on the tool, which would make the Farmer stop recognizing the damaged tool as a workable tool.
![1](https://user-images.githubusercontent.com/43149111/72646955-1cb7ce00-3956-11ea-940a-5922acf8be74.png)
![2](https://user-images.githubusercontent.com/43149111/72646957-1f1a2800-3956-11ea-80b8-c52bbaaff1a8.png)

**Comment by Raycoms** [comment]
Tested it, works on the latest alpha.
