### ISSUE TITLE
Lumberjack small problem

### ISSUE THREAD

**Issue by chris5022** [ldtteam/minecolonies#4244]
### Minecolonies version

Version: 0.10.593-RELEASE

### Expected behavior

i whould expect the lumber jack to start cutting trees store them and eat

### Actual behaviour

lumberjack leval 2 he was going through tons of axes and putting logs in the chest but the logs would not stick in the box just vanish. his inv was also empty at the point of placing. if i maintain a log of each type in the chest they will then stick in the chest without vanishing. Also he seems to be a vegetarian. he will STARVE to death if meat is all that is available. the others eat meat just not him. so maybe bug maybe feature on that part lol

### Steps to reproduce the problem

1.  built Acacia lumberjack hut level 1 (level one will work fine)
2.  upgrade to level 2. give him axe and emprty his chest.
3. he will cut wood go to store it put it in his box and wood will vanash
4. ... Profit

**Comment by Raycoms** [comment]
a) is the meat raw?
b) is this in multiplayer?

**Comment by chris5022** [comment]
no meat is cooked and it is a single player game

**Comment by chris5022** [comment]
the others eat the same meat he is being fed

**Comment by chris5022** [comment]
we updraded it to lvl 3 and found all the wood blocks. the were in the chests availble for the lvl 3 version. not sure how that works

**Comment by Raycoms** [comment]
which style was that?

**Comment by chris5022** [comment]
Acacia

**Comment by Entaigner** [comment]
Got the same Problem.

It started after i've updated the Lumberjack from Level 1 (double chest as storage) to level 2 ( two racks as storage). The Lumberjack is currently at level 3 (three racks as storage) but the problem persists.

Building: Lumberjack (DarkOak)
Version: minecolonies-0.10.716-RELEASE-universal.jar
Multiplayer Server: yes (two player and two colonies)

If you tell me what to do i can log on to our server, make some changes and get more data. The MC Server runs on a dedicated server to which we have full access.

**Comment by Entaigner** [comment]
> Got the same Problem.
> 
> It started after i've updated the Lumberjack from Level 1 (double chest as storage) to level 2 ( two racks as storage). The Lumberjack is currently at level 3 (three racks as storage) but the problem persists.
> 
> Building: Lumberjack (DarkOak)
> Version: minecolonies-0.10.716-RELEASE-universal.jar
> Multiplayer Server: yes (two player and two colonies)
> 
> If you tell me what to do i can log on to our server, make some changes and get more data. The MC Server runs on a dedicated server to which we have full access.

A MC server restart has fixed the problem so there won't be any reproducing anymore, sorry.
