### ISSUE TITLE
Minecolonies Border missing a chunk.

### ISSUE THREAD

**Issue by tonyvans** [ldtteam/minecolonies#4247]
### Minecolonies version

Version: minecolonies-0.10.631-BETA-universal.jar in Enigmatica 4 - 0.4.4

### Expected behavior

-  Minecolonies Border would not be missing a chunk

### Actual behaviour

- The border would be straight though and I would be able to build there.

![image](https://user-images.githubusercontent.com/6739653/72695944-45bf9680-3aef-11ea-9ac0-1ac73dd790c4.png)

The whole border on that side with the missing chunk.
![image](https://user-images.githubusercontent.com/6739653/72697023-4528ff00-3af3-11ea-9531-11c76fca053b.png)

### Steps to reproduce the problem

1. Unknown, it has, as far as I know been like that from the beginning of the colony. I just never tried to build in it before.

2. Thank you for your great work.

**Comment by Raycoms** [comment]
We fixed this a while ago, but some chunks might still be missing. You can fix it by running the claim command or in the case of dynamic borders  by upgrading the guard tower.
