### ISSUE TITLE
minecolonies border protection

### ISSUE THREAD

**Issue by Nazgoul9** [ldtteam/minecolonies#4252]
### Minecolonies version

Version: 0.10.656-ALPHA

### Expected behavior

prevent players from breaking block in your colony without permission

### Actual behavior

all players being able to break blocks in your colony with or without permissions

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit

**Comment by Raycoms** [comment]
Where is this a problem? Is the anti griefing turned on in the config file?

**Comment by Nazgoul9** [comment]
I don't know, my friend running the world told me to report it here.

**Comment by Raycoms** [comment]
Yeah, we need more details, we never had this problem

**Comment by Seilican** [comment]
Minecolonies version
Version: 0.10.656-ALPHA
the Seilican experience server 

Expected behavior
prevent players from breaking block in your colony without permission

Actual behavior
all players being able to break blocks in your colony with or without permissions

Steps to reproduce the problem
![Capture](https://user-images.githubusercontent.com/16024289/72838424-7b7a9180-3c4d-11ea-953c-8011b568d701.PNG)


... Profit

**Comment by Raycoms** [comment]
Are you sure the players are in your colony? Is that chunk really claimed?

**Comment by Raycoms** [comment]
Didn't you turn it off in the colony config itself?

**Comment by Seilican** [comment]
I will attempt to reproduce it again tonight but as far as we could test the colony was set up protection properly I went over was able to do and bust things within their colony I am not a part of their colony all of the claims I linked how the permissions were set up everything should be working fine and the permissions haven't changed from the server previously on one 4.14 or were just standard stuff sorry if this came out gobbledygook Ali I'm replying on my phone and I just got off of work I have to do a bunch of shopping and then I will be home to actually clean this up and get this fixed

**Comment by Raycoms** [comment]
are you an op level administrator?

Am Fr., 24. Jan. 2020 um 20:08 Uhr schrieb Seilican <
notifications@github.com>:

**Comment by Seilican** [comment]
Nope

**Comment by Seilican** [comment]
You are right normally I am but I have not been updated to that status on 1.15 yet

**Comment by Raycoms** [comment]
Also fixed in next version
