### ISSUE TITLE
Colonists duplicate

### ISSUE THREAD

**Issue by Adde2000** [ldtteam/minecolonies#4253]
### Minecolonies version

Version: 1.12.2-0.10.592-RELEASE
Forge Version: 1.12.2-14.23.5.2847

### Expected behavior

- Not more than one of every colonist. 

### Actual behaviour

- Colonists seem to duplicate seemingly randomly. This seems to happen to all colonists but mostly my builder and miner. This issue seems to be similar to #2424

![2020-01-21_15 00 42](https://user-images.githubusercontent.com/32800613/72812171-4e37de80-3c61-11ea-83fa-dfd803ab276f.png)
![2020-01-21_15 00 50](https://user-images.githubusercontent.com/32800613/72812173-4e37de80-3c61-11ea-94a5-156dfa9c8a4d.png)

### Steps to reproduce the problem

1. I'm not really sure how to reproduce this, it seems to do it randomly.

**Comment by Raycoms** [comment]
Yes, old reason, that's vanilla entity management. We advice to regularly restart your server, that fixes it.
