### ISSUE TITLE
[Suggestion] Config option to allow colonists work at night

### ISSUE THREAD

**Issue by SeriousCreeper** [ldtteam/minecolonies#4258]
Heya,

was wondering if we could get a config option to keep colonist work at night time, similar to the option to work during rain. 
I'm planning on using minecolonies inside the betweenlands, which doesn't really have a concept of day/night, but depending on the current time, the workers will still stop working (since it's technically night). It's a bit odd to see them just idle when there is no real visual indicator in that dimension that it's night time in the overworld. 

Would that be possible? 

Thanks a lot,
SC

**Comment by Asherslab** [comment]
Currently we do not fully support any dimensions other than overworld. When we do add support for external dimensions we will probably look into figuring out a solution to dimensions that are "always night" or etc. until then i suggest not making colonies in non-overworld dimensions

**Comment by SeriousCreeper** [comment]
Understandable, thanks! I think the same would also be useful for overworld colonies, if the sleep mechanic is disabled.

**Comment by Raycoms** [comment]
Closed in favor of joint issue.
