### ISSUE TITLE
Fisherman Stops Working Very Quickly

### ISSUE THREAD

**Issue by RZiegler979** [ldtteam/minecolonies#4259]
### Minecolonies version

Version: 0.10.655-BETA 

### Expected behavior
Fisherman keeps fishing when provided with enchantment free rods and food.

### Actual behaviour
Fisherman casts line once or twice then stands around indefinitely until fired or the game is restarted. 

### Steps to reproduce the problem
Install mod, build fishing hut, provide with supplies.

As a side note I do have quite a few mods installed. None that should conflict with mine colonies fisherman behavior. If anyone is aware of a conflicting mod though please let me know.

**Comment by Raycoms** [comment]
Duplicate issue #4127
