### ISSUE TITLE
Jungle bounding boxes

### ISSUE THREAD

**Issue by chriskeena** [ldtteam/minecolonies#4260]
### Minecolonies version

Version:  0.10.655-BETA

### Expected behavior

- When building the Jungle structures I would expect the high walkways to meet those of neighbouring structures.

### Actual behaviour

- When the building the Jungle Town hall I noticed the walkways stopped a block short of the bounding box. No matter, I manually placed blocks to bridge the gap to the Builders Hut.

- When the builder was finalising the structure the blocks I'd placed to connect teh walkways were replaced with air. I'm concerned this will be repeated at each upgrade stage with the links being deleted.

### Steps to reproduce the problem

1. Place Jungle Builder and Town Hall adjacent so their walkways align without intruding into the others bounding box.
2. Place blocks during construction to fill gaps between walkways .
3. Watch as builder deletes blocks at end of build.
4. ... Profit

**Comment by Raycoms** [comment]
@lunadragnstar

**Comment by lunadragnstar** [comment]
I need more information on this issue, I'm showing all the walkways going to the edge of the build borders.

**Comment by chriskeena** [comment]
![2020-01-26_15 55 32](https://user-images.githubusercontent.com/29703373/73130838-60948c80-4054-11ea-8d9a-616693ebdb68.png)
At the bottom of the picture you can see the construction barriers for the upgrade.
At top-center the position of torches on fences reveal the extent of the blueprinted structure.
I manually placed timbers to bridge the gap whilst the Town Hall was nearing completion. After placing torches teh builder deleted my timbers so the completed project would match the blueprint.
The construction barriers are one block outside the blueprint but anything placed in that space is deleted.

**Comment by chriskeena** [comment]
You could possibly test this by pasting in a completed structure, adding blocks at the bridge ends, then ordering a repair.
One thing I've noticed is these structures are back to back, the ground level access does not face each other. Therefore teh issue exists at the back of each structure, the other faces apear to extend to the box.

**Comment by lunadragnstar** [comment]
Ok, I think I found the problem, the townhall scan is off by 1 block, I will double check the scans and get them fixed

**Comment by chriskeena** [comment]
The builder seems to have the same issue at the back. I haven't checked any other structures, I put this save aside for later.

**Comment by lunadragnstar** [comment]
yeah, I'll double check all the jungle scans

**Comment by lunadragnstar** [comment]
all the scans were off, I've fixed them and they should be in the next update
