### ISSUE TITLE
Nordic Style Flower Shop lvl 3 missing

### ISSUE THREAD

**Issue by Gh3ttoboy** [ldtteam/minecolonies#4261]
### Minecolonies version
 minecolonies-1.12.2-0.10.630-BETA-universal

Version: 

### Expected behavior

-  missing LVL 3 Nordic Style Flower Shop https://gyazo.com/9ab5a0030467e1ff68092fafa47859db 
Level 1 looks fine Level 2 Looks fine Level 3 not there Level 4 looks fine Level 5 Looks fine
it might also just be that my game ismissing the file but im not sure if that would be the problem

### Actual behaviour

-  When im building the level 3 Flower shop its basicly not there this Gyazo https://gyazo.com/9ab5a0030467e1ff68092fafa47859db

Level 1 Nordic Flower Shop https://gyazo.com/191f47631fb0dd21cabf9a912a00fe8f
Level 2 Nordic Flower Shop https://gyazo.com/afea59520021147095d500480d6b6288
Level 3 Nordic Flower Shop https://gyazo.com/9ab5a0030467e1ff68092fafa47859db
Level 4 Nordic Flower Shop https://gyazo.com/3625c894ca39221b280ce18f24fdfe4b
Level 5 Nordic Flower Shop https://gyazo.com/2c06d73497b56c1bb3900c5f57c862aa

### Steps to reproduce the problem

1.  Get a building tool and Flower Shop then change to the Nordic Style structure
2.  then select level 3
3.  https://gyazo.com/9ab5a0030467e1ff68092fafa47859db
4. ... Profit Maybe

**Comment by Raycoms** [comment]
@lunadragnstar

**Comment by lunadragnstar** [comment]
fixed
