### ISSUE TITLE
No version of structurize listed as a dependency for 1-15

### ISSUE THREAD

**Issue by trogarus** [ldtteam/minecolonies#4263]
minecolonies-0.10.660-ALPHA-universal

Says it requires structurize but there is no 1.15 version of structurize as of submitting this issue.

**Comment by Raycoms** [comment]
There is, they are alpha (click view all), I'll make the newest one a release as well for easier visibility though

**Comment by trogarus** [comment]
Thanks, wasn't showing and I had hit files link to look. Thanks,
