### ISSUE TITLE
Replacing blocks with scan tool issues

### ISSUE THREAD

**Issue by lunadragnstar** [ldtteam/minecolonies#4265]
minecolonies-0.10.663-ALPHA-universal
structurize-0.10.225-ALPHA

When using the scan tool to replace block, any block that is dependant on another "pops" off such as buttons, pressure plates, doors.

![image](https://user-images.githubusercontent.com/29446488/73116885-eb1da480-3f0b-11ea-8c39-95465c049fd4.png)

The pressure plate and torch were attached until the blocks the were attached to were replaced.

**Comment by Raycoms** [comment]
This worked fine with 225 for me.
