### ISSUE TITLE
Player made schematics don't work

### ISSUE THREAD

**Issue by lunadragnstar** [ldtteam/minecolonies#4266]
minecolonies-0.10.663-ALPHA-universal
structurize-0.10.225-ALPHA

Putting scans into the schematic folder does not cause them to show up on the style list.

It shows up under My Schematics if put in the scans folder. 

Even when double checking the config file, are set to allow player schematics is set to true

**Comment by Raycoms** [comment]
Tested, it has to go in the structurize/schematics folder to work.
