### ISSUE TITLE
Infinite Resources not working for miner

### ISSUE THREAD

**Issue by lunadragnstar** [ldtteam/minecolonies#4267]
minecolonies-0.10.663-ALPHA-universal
structurize-0.10.225-ALPHA

#Should builder and miner build without resources? (this also turns off what they produce). [Default: false]
	builderinfiniteresources = true
#Should the request system creatively resolve (if possible) when the player is required to resolve a request. [Default: false]
	creativeresolve = false

Do not work for the miner but does for the builder.

**Comment by Raycoms** [comment]
It doesn't work for cobble and ladders but it should work for the shaft resources?

**Comment by lunadragnstar** [comment]
correct, it doesn't work for tools, cobble or ladders.

**Comment by Raycoms** [comment]
So that's intentional. If you want those too you need creative resolve of
the request system and not infinite resources

**Comment by lunadragnstar** [comment]
I have both of them set to true

**Comment by Raycoms** [comment]
Then I gotta check what's up with creative resolve

**Comment by Raycoms** [comment]
okay, you gotta setup the creativeresolve = true and delaybetweenretries = 1 then it works
