### ISSUE TITLE
Missing Information Tab in Town Hall GUI

### ISSUE THREAD

**Issue by Sirfancytoad** [ldtteam/minecolonies#4269]
### Minecolonies version

Version: minecolonies-1.12.2-0.10.592-RELEASE-universal

### Expected behavior

- I would expect to see an information tab on the side that shows that colony's happiness and the amount of citizens present in the colony.

### Actual behaviour

- There is instead just a blank tab (no question mark present) and it is unclickable, so I am unable to get that information.

### Steps to reproduce the problem

1. I am not sure, it happens when I load this version. Don't remember doing anything special from when I've loaded this before.

**Comment by Asherslab** [comment]
you need to update to a later version
