### ISSUE TITLE
Build Tool rotation and movement lags out of creative mode

### ISSUE THREAD

**Issue by nekatu** [ldtteam/minecolonies#427]
### Minecolonies version

version 0.6.2214

### Expected behavior

- Smooth rotation and general movement in the build tool menu in all modes

### Actual behaviour

- Player movement and building ghost rotation is slow and feels like the system is lagging in survival mode
- Player movement and building ghost rotation is smooth and quick in creative move

### Steps to reproduce the problem

1. Switch between modes
2. Click Build Tool on a block
3. Press ESC to move around or use rotation/placement arrows

**Comment by Raycoms** [comment]
Can you tell me your pc stats? And how much RAM did you assign to minecraft?

2017-01-04 20:47 GMT-02:00 nekatu <notifications@github.com>:

**Comment by nekatu** [comment]
Specs-

```
Operating System
	Windows 10 Enterprise 64-bit
CPU
	AMD Phenom II X4 955
	Deneb 45nm Technology
RAM
	8.00GB Dual-Channel DDR3 @ 666MHz (9-9-9-24)
Motherboard
	ASUSTeK Computer INC. M4A785TD-V EVO (AM3)	63 °C
Graphics
	Mstar Demo (1920x1080@60Hz)
	BenQ FP222W (1680x1050@59Hz)
	DELL E1709W (1440x900@60Hz)
	4095MB NVIDIA GeForce GTX 980 (EVGA)	52 °C
Storage
	465GB Seagate ST95005620AS ATA Device (SATA)	35 °C
	931GB Hitachi HDS721010CLA332 ATA Device (SATA)	37 °C
Optical Drives
	PLDS DVD+-RW DH-16A6S ATA Device
Audio
	VIA HD Audio(Win 10)
```

Been experimenting with differing amounts of RAM to allocate to MC, it's currently at 5GB.

**Comment by Raycoms** [comment]
That's strange. The tool works without any problem for me. Without any lag
or similar. Do you have any other mods active? any graphic mods?

2017-01-04 22:08 GMT-02:00 nekatu <notifications@github.com>:

**Comment by nekatu** [comment]
I'm thinking it could be my texture pack- I'm running BDCraft, which is quite an extensive overhaul.

Just weird that it works fine in creative but not survival, same server, same world, same session.

**Comment by Raycoms** [comment]
That's even stranger =O

2017-01-04 22:48 GMT-02:00 nekatu <notifications@github.com>:

**Comment by Raycoms** [comment]
I guess it has something to do how minecraft renders stuff.
Could you test this 1.10 build for me:
https://www.dropbox.com/sh/9cnqcjl0nan57cy/AAAd1fJzOOvzerJQ8VWOlIMEa/branch/fix/builder-metadata?dl=0&preview=minecolonies-universal-1.10.2-0.6.2244.jar

It will place flowers and saplings in plant pots correctly and will now also place all tile entities and request them. Would be nice to have it tested.

**Comment by nekatu** [comment]
not a problem- will throw it up to my server and test it later today

**Comment by nekatu** [comment]
Generally seems good so far, though I'm finding a crash if I try and preview a Fisherman beyond level 3.

[fml-client-2.zip](https://github.com/Minecolonies/minecolonies/files/688647/fml-client-2.zip)
[fml-client-latest.zip](https://github.com/Minecolonies/minecolonies/files/688646/fml-client-latest.zip)
[latest.zip](https://github.com/Minecolonies/minecolonies/files/688648/latest.zip)

Will continue testing though.

**Comment by nekatu** [comment]
Also finding that the builder seems to get stuck or bored from time to time and just stands there, switching from day to night and then back to day seems to wake him up though as he goes to the townhall and then comes back to his work.

Worst case I've had to cancel the current job (Town Hall upgrades have twice stuck him, so maybe something in that?) and then letting him move on to the next job.

**Comment by nekatu** [comment]
OK- a few things-

1: My original issue does look like it's resource pack (or mod) related as running the current version on 10.2 with the mystic minecolonies pack resulted in smooth building in or out of creating mode.

2: Flowers and pots were placed, though when you upgrade the citizen house from level 4 to level 5 the bits it replaced were left floating-

![2017-01-05_23 34 14](https://cloud.githubusercontent.com/assets/1908371/21702052/2fa7b0a2-d3a1-11e6-9db0-451195d41de5.png)
![2017-01-05_23 34 04](https://cloud.githubusercontent.com/assets/1908371/21702053/2fa9ef0c-d3a1-11e6-9337-8d2da9e1c09c.png)

3: At least one string is still wrong/missing; the Guard upgrade achievement-

![2017-01-05_23 38 39](https://cloud.githubusercontent.com/assets/1908371/21702073/4814cd00-d3a1-11e6-9bac-c6b7aea5b03e.png)

4: The miner may be glitched, or it could just be fluke. She was building the 1st level but was standing on the ladder for 4-5 minutes not doing anything. When I recalled her to the chest she started building the level that she was supposed to but over the top of the actual building-

![2017-01-05_23 41 04](https://cloud.githubusercontent.com/assets/1908371/21702112/8b959a32-d3a1-11e6-8903-fef8a93d9bc1.png)
![2017-01-05_23 41 11](https://cloud.githubusercontent.com/assets/1908371/21702114/8b99805c-d3a1-11e6-814e-3604deb0dc19.png)
![2017-01-05_23 41 12](https://cloud.githubusercontent.com/assets/1908371/21702113/8b990136-d3a1-11e6-9a52-17e2f5bc4b38.png)
![2017-01-05_23 41 16](https://cloud.githubusercontent.com/assets/1908371/21702115/8b99ade8-d3a1-11e6-9373-b5c02eed0412.png)
![2017-01-05_23 41 24](https://cloud.githubusercontent.com/assets/1908371/21702116/8b9ac19c-d3a1-11e6-9d40-fc6b8ca7e56b.png)

The game crashed about 2 minutes after that, but again could be fluke.

[fml-client-3.zip](https://github.com/Minecolonies/minecolonies/files/688690/fml-client-3.zip)
[fml-client-latest.zip](https://github.com/Minecolonies/minecolonies/files/688692/fml-client-latest.zip)
[latest.zip](https://github.com/Minecolonies/minecolonies/files/688691/latest.zip)

**Comment by nekatu** [comment]
Game crashes whenever I load that world now... 

[fml-client-3.zip](https://github.com/Minecolonies/minecolonies/files/688700/fml-client-3.zip)
[fml-client-latest.zip](https://github.com/Minecolonies/minecolonies/files/688698/fml-client-latest.zip)
[latest.zip](https://github.com/Minecolonies/minecolonies/files/688699/latest.zip)

Works fine on other worlds.

**Comment by Raycoms** [comment]
Fixed that in the upcoming version too =D.
Glad to hear it's rendering good again.
Yeah the mining of the flower pots doesn't work very well.
The placement is important for now =D


2017-01-05 21:58 GMT-02:00 nekatu <notifications@github.com>:
