### ISSUE TITLE
Lumberjack cutting leaves

### ISSUE THREAD

**Issue by meTundra** [ldtteam/minecolonies#4273]
### Minecolonies version
Version: 0.10.660-ALPHA-universal

### Expected behavior

- lumberjack should cut trees, i think.

### Actual behaviour

- A lumberjack cuts several trees, then begins to cut leaves from a particular tree. He can first chop this tree down, then start chopping the leaves, or he can chop down the leaves first, and then start chopping the tree. He ignores the rest of the leaves of the remaining trees. Then, when there are no leaves at a height of 4 blocks, the lumberjack walks back and forth for about a minute, and returns to normal functioning. After several felled trees (there may be 3, or maybe 12), everything repeats.

The mods that I have installed:
![image](https://user-images.githubusercontent.com/39331539/73137221-ea4d5580-4066-11ea-88ef-75850365aa5d.png)

Video:
https://youtu.be/nbHFwW3bbf4

### Steps to reproduce the problem

I have no idea how to reproduce this. It may have started after upgrading the lumberjack (medieval oak) to level 2, but I'm not sure. I can try to upload this world and the mods folder so you can look at it if necessary.

**Comment by Raycoms** [comment]
This happens when he is unable to path close enough to a tree because of the leaves, so he tries to remove leaves around him in an attempt to get closer. So as long as he returns to normal functioning afterwards again this is not an issue.

**Comment by meTundra** [comment]
But right now he's standing right next to a tree and chopping leaves, is that normal?
https://youtu.be/10whTfTQjh4

**Comment by Raycoms** [comment]
Yeah, detection is not perfect, it's kinda difficult to calculate these
things.

Am So., 26. Jan. 2020 um 14:07 Uhr schrieb iLednev <notifications@github.com

**Comment by meTundra** [comment]
Okay, got it, thanks
