### ISSUE TITLE
Colonist Stuck in the Town Hall

### ISSUE THREAD

**Issue by FATE-Punky** [ldtteam/minecolonies#4274]
I have had a few recent issues with newer colonists standing in the Town Hall, not doing anything, no job, etc. When I have a stuck colonist, typically I can just use a Lead and drag them a bit and they become unstuck. However, these colonists do not move at all. The only thing I could do was actually kill the colonist off as nothing else fixed the problem. 

By the way, FANTASTIC mod. I love this mod. This was exactly what I was looking for when I started playing on PC. Thank you for keeping up with it. :D

**Comment by Raycoms** [comment]
Is there any log? Besides that, are you sure it's not night, or you have daylight turned off, or you got a barbarian raid going on, or they are mourning?

**Comment by FATE-Punky** [comment]
> Is there any log? Besides that, are you sure it's not night, or you have daylight turned off, or you got a barbarian raid going on, or they are mourning?

No. It's during daylight with no hostile events occuring. All of the other citizens are going about their jobs. I have noticed that occasionally I will see a citizen with no job standing in the town hall but the same one will also be roaming around. It also happens with delivery people. They are seemingly standing in a spot, immovable, but there is a second instance of them that is actually running materials. I haven't gotten any feedback errors thus far. It doesn't impede upon my gameplay though as most of the time it's just a second instance of the citizen that doesn't function.

**Comment by Raycoms** [comment]
Oh yeah, in SMP because of vanillas entity management sometimes duplicate colonists occur, we restart our servers regularly so we don't notice this (Restart fixes this).

**Comment by FATE-Punky** [comment]
> Oh yeah, in SMP because of vanillas entity management sometimes duplicate colonists occur, we restart our servers regularly so we don't notice this (Restart fixes this).

Yea. I did a restart of the server and noticed it fixed it. Definitely going to be sure I restart more often to keep things running smooth. Thank you for your quick replies :D
