### ISSUE TITLE
Knight/Guard Damage 

### ISSUE THREAD

**Issue by FATE-Punky** [ldtteam/minecolonies#4275]
For some reason unbeknownst to me, knights or guards in the barrack's towers repeatedly are taking damage. I can hear the hit marker but I can not find one cause for this. I have looked in their inventory at their armor to solidify my suspicions that this is what I was hearing and it has clearly taken damage from something. I have not been able to identify what is doing it. I have tried respawning and recalling, clearing inventories; everything aside from fully killing them.

It doesn't bother me so much that their equipment is taking damage. However, constantly hearing the sound is really becoming irritating and since I have not been able to find a fix thus far I felt it should be reported.

**Comment by lunadragnstar** [comment]
Could it be the sweetberries?

**Comment by Raycoms** [comment]
It's not a bug, when they sleep, the other guards hit them to wake them up, they are not taking damage and neither should their equipment.
