### ISSUE TITLE
Weird graphical glitch

### ISSUE THREAD

**Issue by lunadragnstar** [ldtteam/minecolonies#4276]
MC.669 ST.228

weirdest issue i've ever seen

I'm going through and checking schematics, The schematic isn't the issue, but look at the builders wand, it looks perfectly fine in the picture below.
![image](https://user-images.githubusercontent.com/29446488/73154040-fd324b00-40a3-11ea-8e03-276e2ba88802.png)
****
However, when I change to the next schematic

![image](https://user-images.githubusercontent.com/29446488/73153870-5d74bd00-40a3-11ea-932c-bcbf0a292b7d.png)

Some of it changes

![Animated GIF-downsized_large](https://user-images.githubusercontent.com/29446488/73154135-5a2e0100-40a4-11ea-8562-5db03f870549.gif)

**Comment by Asherslab** [comment]
if anyone can't see it, look at the pixel disappearing on the bottom right hand side of the handle of the wand

**Comment by Nightenom** [comment]
MC occlusion culling was always messy, I bet on it's the same problem as chests/banners disappearing when being in the edge of the view field
