### ISSUE TITLE
NPC use the chest and other items in huts

### ISSUE THREAD

**Issue by shivachirr** [ldtteam/minecolonies#428]
so im wondering if its possiable for npc to use the chest, furnaces, and crafting tables in there huts. chest for more storage. and the crafting table and furnaces make sense for some of them like the builder and maybe the miner to make its own torches. i feel it woud make them better if when you get your town to the point they can make there own basic supplys and tools. and only way they can be upgraded is if you provoid the tools. and maybe the town hall can be the massive storage on the top floor. if not that if its easier a way to desnate a chest for npcs know where to dump excess stuff and pick up sutff they need

**Comment by kreezxil** [comment]
this sounds like a great idea.

I have been assuming that the as yet not released "forge" and "deliveryman" would satisfy this to some extent.

**Comment by shivachirr** [comment]
yeah and the crafter but i feel like even after the crafter is made the npc should be able to make some stuff that they need from what materails they get

**Comment by Raycoms** [comment]
We will add various crafter workers to handle that.

2017-01-06 11:10 GMT-02:00 shivachirr <notifications@github.com>:

**Comment by kreezxil** [comment]
Yeah I was thinking that too!!! ;)

-----Original Message-----

**Comment by Raycoms** [comment]
planned

**Comment by nekatu** [comment]
Just to add to this; the Hut chest acts as a conventional chest, which means you can use hoppers (or conveyors, etc from mods) to move items out of the main chest and into other chests around the hut. I've got this working for the miner and lumberjack so far, next step is to try a more complex design for the farmer where it take specific items and move them to the relevant chest at the back of the barn.

**Comment by shivachirr** [comment]
i know that but they are the size of 1 chest and the fact buidlings like the buildier have a chest in there hut but they dont use it kinda feels well not right

**Comment by Raycoms** [comment]
Don't worry. These chests will have a purpose in the future =D

2017-01-07 12:16 GMT-02:00 shivachirr <notifications@github.com>:
