### ISSUE TITLE
Builder can't upgrade own hut

### ISSUE THREAD

**Issue by Awesomespore** [ldtteam/minecolonies#4280]
### Minecolonies version
0.10.669-ALPHA 

Version: 

### Expected behavior

I'd expect the builder to upgrade his hut successfully.

### Actual behaviour

Builder is unable to upgrade hut, I'd imagine this is due to the fact that if it were to take apart own hut, it would not have the builder's hut level required to upgrade the hut.

### Steps to reproduce the problem

1. Place and construct a Builder's hut
2. Once hut is built, go into build options and click Upgrade
3. Only the builder who works in that Builder's hut will attempt to upgrade the hut
4 The builder will stand next to his hut block and do nothing. They will not ask for/take any resources, nor break or place any blocks.

**Comment by Awesomespore** [comment]
This is frustrating because I cannot upgrade any other buildings without a level 2 Builder's hut :(

**Comment by lunadragnstar** [comment]
What happens when you click update? Any error messages, or does it show up in the townahll.

**Comment by Awesomespore** [comment]
I'm trying to get a level two builder's hut, and it doesn't come up with errors, he just stands at his hut block....

**Comment by Awesomespore** [comment]
aha, I tore apart the level one hut, leaving only the hut block, now he's requesting items YAY

**Comment by Awesomespore** [comment]
or at least he asked for 30 oak slabs

**Comment by Awesomespore** [comment]
after going into spectator mode, he appears to be starting construction from underground

**Comment by Awesomespore** [comment]
![2020-01-29_19 04 22](https://user-images.githubusercontent.com/59407684/73331921-3c41e580-42ca-11ea-8f12-255f7f2fc7d0.png)

**Comment by lunadragnstar** [comment]
ahh yes, at level 2 the medieval Oak builders hut has a basement

**Comment by Awesomespore** [comment]
so it's possible that he was indeed building without me knowing

**Comment by lunadragnstar** [comment]
very possible
