### ISSUE TITLE
Crash to desktop when opening "Build Options" in Builders Hut GUI

### ISSUE THREAD

**Issue by kkbearxo** [ldtteam/minecolonies#4281]
### Minecolonies Version
- minecolonies-0.10.593-RELEASE-universal for 1.14.4

### Forge Version
- Forge version 28.1.116

### Expected behavior

- Not crashing after clicking "Build Options" in Builder Hut GUI, and being able to go into the "Build Options" GUI so my builder can build.

### Actual behaviour

- Upon entering the Builder Hut GUI, it doesn't crash, but as soon as I click "Build Options" I get an immediate crash to desktop with the following error on my Minecraft launcher:

"_The game crashed whilst saving entity nbt
Error: java.lang.IllegalArgumentException: Invalid null NBT value with key sndctrl:entityfx_"

Pastebin of my crashlog: https://pastebin.com/73Kp1Fks

### Steps to reproduce the problem

1. Craft Citizen Hut
2. Select the "sandstone" style using the build tool and use it to place the block
3. Open Citizen Hut GUI
4. Select "Build Options"

**Comment by Asherslab** [comment]
This issue is not ours, it is created by the Sound Control mod

**Comment by Raycoms** [comment]
Yeah, definitely another mod injecting things they shouldn;t

java.lang.IllegalArgumentException: Invalid null NBT value with key sndctrl:entityfx

**Comment by fpayne27** [comment]
How did you fix the problem? I have the same issue

**Comment by ravenbuilder934** [comment]
likely unrelated, new issue please

**Comment by fpayne27** [comment]
I have the exact same issue as the other person. When I open Build Options it crashes the game completely.

**Comment by ravenbuilder934** [comment]
do you have the same error in the log? because if not, it's unrelated

**Comment by fpayne27** [comment]
Yes I do.

**Comment by ravenbuilder934** [comment]
okay, then report to the Sound Control mod - its fault
