### ISSUE TITLE
Schematics with disconnected leaves

### ISSUE THREAD

**Issue by seppestuyck** [ldtteam/minecolonies#4282]
version: minecolonies-0.10.669-BETA-universal.jar

Expected behavior:

     leaves that are placed down dont despawn

Actual behaviour:

    leaves despawn as if they where naturaly generated

Steps to reproduce the problem

1. let the builder build a building with leaves
2. any leaves that arent connected (timely an within range) to a log start to despawn
3. ...
4. Profit

**Comment by Raycoms** [comment]
Yeah, that's actually a problem of the schematic not of the mod, we don't change the game mechanics.
Please report which structures have this problem so we can fix them.

**Comment by seppestuyck** [comment]
I use a custom schematic that has leaves that are not within reach of logs, but hand placed leaves shoudnt despawn.
Also the dark oak set of buildings have their leaves despawn during building because they arent connected to a log in time.

**Comment by seppestuyck** [comment]
Ive also noticed that some of the dark oak medieval buildings dont use dark oak.

**Comment by lunadragnstar** [comment]
Dark oak hasn't been updated yet, doing that now.

There was also an issue with medieval dark oak schematics that was fixed last night.

**Comment by seppestuyck** [comment]
i think the medieval dark oak schematics got reverted to the regular oak in one of the latest patches lol

edit: also found out the schematic update was only for 1.15 and not for 1.14

**Comment by lunadragnstar** [comment]
we are still working on the Medieval Schematics Sorry. we will have all the schematics updated as soon as possible, this should correct this issue.
