### ISSUE TITLE
Suggestion: Warehouse Catalog

### ISSUE THREAD

**Issue by Awesomespore** [ldtteam/minecolonies#4283]
Hello, I'd like to suggest adding an item that's something along the lines of a "warehouse catalog", an item that can be used to view all items stored in a warehouse, including their quantities (Think of a modded storage system interface).
The item would need to be bound to a warehouse block, binding it to that warehouse. The item would only be for viewing quantities of stored items, and would not allow the user to take items out via the item itself.

**Comment by Raycoms** [comment]
Already got some issues for that.

**Comment by Awesomespore** [comment]
Okay, well thanks for reading

**Comment by Raycoms** [comment]
We didn't do it yet, because we need a scrollable inventory GUI, and we're waiting for our GUI library to be ready for it. Making it by hand is a lot of work.
