### ISSUE TITLE
Miner Breaks surface layer of his structure

### ISSUE THREAD

**Issue by Awesomespore** [ldtteam/minecolonies#4287]
### Minecolonies version
0.10.699-BETA

Version: 

### Expected behavior

I would expect the miner to not dig a hole in the floor of the level 5 hut

### Actual behaviour
The miner removes the surface layer of his hut and builds a cobblestone platform 2 blocks lower.

- 

![2020-02-02_12 56 04](https://user-images.githubusercontent.com/59407684/73600882-f338ac80-45bb-11ea-967b-baf2396e2f73.png)

### Steps to reproduce the problem

1. Get a level 5 mine with Medieval Oak as the style
2. I'm not sure, I upgraded the hut and when I came back later on he had dug the floor out and built a cobblestone platform 2 blocks lower than it should be.
![2020-02-02_13 02 17](https://user-images.githubusercontent.com/59407684/73600897-44e13700-45bc-11ea-88ae-8497c8366715.png)

**Comment by Raycoms** [comment]
yeah, that happens when his ladder breaks for some reason, maybe an enderman took it, maybe something else broke it, but this only happens when his ladder gets broken.

**Comment by Raycoms** [comment]
We completely lose the ability to detect these things when the ladder gets broken.

**Comment by Awesomespore** [comment]
huh... so protect the ladder

**Comment by Awesomespore** [comment]
No, he's still doing it...

**Comment by Awesomespore** [comment]
I set a repeating command block to keep the ladder intact
Is it the very very top ladder? like the one touching the ceiling?

**Comment by Awesomespore** [comment]
NOPE! He's STILL doing it!

**Comment by Awesomespore** [comment]
there needs to be a way to protect blocks from the miner

**Comment by Raycoms** [comment]
Process now : fire the Miner, fix the ladder for at least 3 blocks, hire
the Miner

**Comment by Awesomespore** [comment]
Okay
