### ISSUE TITLE
Stonesmelter unable to store "cracked stonebricks"-recipe

### ISSUE THREAD

**Issue by Thielquis** [ldtteam/minecolonies#4288]
### Minecolonies version
minecolonies-0.10.669-BETA-universal

### Expected behaviour
Adding stone bricks to the recipes to produce cracked stone bricks.

### Actual behaviour
"Unable to store blueprint. ..."

![2020-02-02_04 05 58](https://user-images.githubusercontent.com/7520025/73602415-0b84d900-4574-11ea-9b5b-429b133a188e.png)
![2020-02-02_04 06 01](https://user-images.githubusercontent.com/7520025/73602416-0b84d900-4574-11ea-9771-77254961d0ad.png)

There were no other recipes stored in the stone smelter at the time I took the screenshots.
I tried it both on a server in a "played" colony and in singleplayer on a new empty world in a fresh colony with a freshly pasted stone smelter.

### Steps to reproduce the problem

1. Open Stonesmelter UI
2. Press Teach Recipe
3. Place stone bricks in the upper slot
4. Press Done

**Comment by LittleWoglug** [comment]
We are seeing this same problem in minecolonies-0.14.110-ALPHA-universal
