### ISSUE TITLE
Guard ai Very bad

### ISSUE THREAD

**Issue by shivachirr** [ldtteam/minecolonies#429]
### Minecolonies version

curse 1.10.2-0.6.2115

### Expected behavior

Attack zombies closest and right next to them after killing one other zombie

### Actual behaviour

kill one zombie then retrun to patrol with mutiable zombies with in 3 blocks. 80% guard death caused

### Steps to reproduce the problem

1. have a guard
2. have a zombie horde
3. watch

**Comment by Raycoms** [comment]
The guard Ai is quite simple and has been restricted out of purpose. Each
guard has a maximum amount of attacks until he has to recover a bit at his
own tower.

2017-01-06 13:00 GMT-02:00 shivachirr <notifications@github.com>:

**Comment by shivachirr** [comment]
yeah but they are not recovering they kill one mob then return to patrol never going back to there tower at times when they return the run int to a horde of zombies or something heck ive seen them path around them perfectly while patroling

**Comment by Raycoms** [comment]
Haha, We're using some minecraft mechanics like "can see entitiy" that
might bug them =D
You can turn on "return on low health" in their tower as well.

2017-01-06 14:39 GMT-02:00 shivachirr <notifications@github.com>:

**Comment by shivachirr** [comment]
the return to low health dose not seem to work they fight to the death or prefer to patrol

**Comment by shivachirr** [comment]
I mean i leitterly watch my 2 rangers run to patrol the fishermans hut while activly being attacked by zombies and died at the same time compeltly the wrong drection from there tower and they never treid to turn around also im thinking the armor stats are not really applying to them as much ive giving them high end armor and they still die quickly

**Comment by shivachirr** [comment]
also i dont know if this is right but i suggest looking at anchent warfare 2 from 1.7.10 combat ai. its very well flushed out last checked and with plently of command setups. in fact ancheint warfare 2 dose alot of the same stuff your doing in terms of npcs
