### ISSUE TITLE
I can't build barracks towers

### ISSUE THREAD

**Issue by xxxumutxxx** [ldtteam/minecolonies#4290]
### Minecolonies version

Version: 1.12.2-0.10.341-ALPHA

### Expected behavior
Barracks towers should be able to be started

### Actual behaviour
I have built the Barracks and upgraded it to level 2 but I am still unable to build any barracks towers whatsoever despite repairing the building. It simply states "please upgrade barracks first"

**Comment by lunadragnstar** [comment]
Have you tried repairing the barracks to see if that helps?

**Comment by Raycoms** [comment]
Try to remove the tower, and then repair the barracks and then try it.

**Comment by xxxumutxxx** [comment]
Yes I have tried that

**Comment by lunadragnstar** [comment]
You are on a very old version of the mod, updating should fix any old bugs

**Comment by lunadragnstar** [comment]
The most resent update is minecolonies-1.12.2-0.10.679-RELEASE-universal.jar

**Comment by xxxumutxxx** [comment]
I’m using the twitch client for my mods.. is there a way to update one mod?

**Comment by xxxumutxxx** [comment]
I’m playing atm3 pack

**Comment by lunadragnstar** [comment]
If you click the picture instead of play on twitch, it will show you a list of mods, just scroll down till you see minecolonies and click the up arrow

**Comment by Raycoms** [comment]
Did a newer version work?
