### ISSUE TITLE
[Suggestion] Meta value support for Crusher recipes

### ISSUE THREAD

**Issue by SeriousCreeper** [ldtteam/minecolonies#4291]
Currently the crusher recipes only accept items without meta values (from what i can tell). 
I'd love to do something like `geolosys:cluster:1!magneticraft:chunks:1`. Or is there already a way of specifying meta values?

**Comment by Raycoms** [comment]
Yes, meta value like this is supported already, exactly like this, but you don't need to specify "geolosys". It gets it by name I think it will work without.

**Comment by SeriousCreeper** [comment]
I dont know why i didnt just try that... sorry about that lol, but it's working indeed! Thanks fo rthe quick response.
