### ISSUE TITLE
Smelter eats produce

### ISSUE THREAD

**Issue by Michael-Phoenix** [ldtteam/minecolonies#4294]
### Minecolonies version
Version: 0.10.672-ALPHA (Current Comp 1.14 Server)

### Expected behavior
Smelter smelts ores into ingots, 
then picks them up from furnace, 
then drops them into hut inventory.

### Actual behaviour
Smelter smelts ores into ingots, 
takes it out of furnace,
after a while the ingots from the inventory disappear and can not be found in any of the hut's inventories/chests

No error message.

### Steps to reproduce the problem

1. build lvl 3 Madieval Oak smelter
2. Give Ore + fuel
3. Smelty smelt
4. ... No Profit :(

**Comment by Raycoms** [comment]
no hidden rack anywhere?

Am Mo., 3. Feb. 2020 um 10:36 Uhr schrieb Michael-Phoenix <
notifications@github.com>:

**Comment by Michael-Phoenix** [comment]
If there is one in the medieval oak schematic, then it's not accessible to the user :/

**Comment by Raycoms** [comment]
upstairs maybe?

Am Mo., 3. Feb. 2020 um 10:53 Uhr schrieb Michael-Phoenix <
notifications@github.com>:

**Comment by Michael-Phoenix** [comment]
tried, all chests empty

**Comment by Michael-Phoenix** [comment]
Cou can come to my colony and repro it on the challenge server if you want <3

**Comment by Michael-Phoenix** [comment]
After building a dman for my village, he could somehow pull the missing ingots out of some kind of inventory I could not access in the smelter. Can we check the Medieval Lvl3 Smeltery Schematic for hidden racks or chests? - I suspect that there is one somewhere. But even after repairing the whole building, there is no new chest or anything :/

**Comment by Raycoms** [comment]
Can you send me the world?

**Comment by Michael-Phoenix** [comment]
It's the 1.14 competition server. You should have it ;) <3

**Comment by Raycoms** [comment]
Same problem as #4294

**Comment by Michael-Phoenix** [comment]
> Same problem as #4294

The reference seems to lead back to this issue. Was there another one?

**Comment by Raycoms** [comment]
https://github.com/ldtteam/minecolonies/issues/4244 same as this
