### ISSUE TITLE
Items keep disappearing when workers try to deposit them into their respective blocks

### ISSUE THREAD

**Issue by SomeDumbNinja** [ldtteam/minecolonies#4299]
Version: minecolonies-0.10.680-RELEASE

Expected behavior:

> Workers work
> Workers deposit items into their blocks
> Items are in the block

Actual behavior:

> Workers work
> Workers deposit items into their blocks
> Items are not in the block

Steps to reproduce the problem

> Get a citizen a job
> Worker works
> Worker deposits their items into their block
(This only happens for some blocks, like the farmer, fisher, lumberjack)

**Comment by Raycoms** [comment]
Can you send me the world? and tell me exactly which workers do this in that world?

**Comment by bblay** [comment]
This is happening in the latest version from Twitch/Bisect (2.2.1a) for the miner, farmer and lumberjack.
