### ISSUE TITLE
Broken Builder

### ISSUE THREAD

**Issue by Remyrios** [ldtteam/minecolonies#430]
### Minecolonies version

Curse 0.4.78

### Expected behavior

- Builder will build in a place that i showed him with Building Tool

### Actual behaviour

- Builder is building few blocks away from place that i showed him with Building Tool

### Steps to reproduce the problem

1. Use building tool to show a blueprint
2. Place town hall block
3. Tell builder to build this town hall
4. http://imgur.com/a/6EfaO

**Comment by Remyrios** [comment]
I already sloved it!

**Comment by Remyrios** [comment]
Or not :/ I thought that i  solved it but i don't

**Comment by Raycoms** [comment]
Builder will construct it in a safe distance from the building to not get closed in by walls.
