### ISSUE TITLE
Multiplayer (Players with Owner status and all permissions turned on are unable to interact with blocks in the colony.

### ISSUE THREAD

**Issue by Vanken76** [ldtteam/minecolonies#4301]
### Minecolonies version

Version: 

### Expected behavior

-  Modpack MC.Eternal Version: 1.3.2

Minecraft Version: 1.12.2

(modded) forge-14.23.5.2847

### Actual behavior

-  When setting other players to 'Owner' and turning on all permissions, the other player still cannot interact with any blocks in the colony.

### Steps to reproduce the problem

1.  Install Modpack
2. Create world, build colony, (multiplayer)
3.  Adjust permissions to enable other players to interact with colony.  Player unable to interact...
4. ... Profit

**Comment by Vanken76** [comment]
Update:  Tried /mc addOfficer command with no change, /MC refresh with no change.  I was able to go in config and set colonyprotection to false, however, this is just a workaround for the issue.

**Comment by Raycoms** [comment]
What's the minecolonies version?

**Comment by Vanken76** [comment]
minecolonies-1.12.2-0.10.668 looks like however that I should probably update it to .679...

**Comment by Raycoms** [comment]
Fixed in next alpha
