### ISSUE TITLE
[Suggestion] Warehouse upgrades

### ISSUE THREAD

**Issue by ghost** [ldtteam/minecolonies#4302]
-Assuming multiple warehouses, have a system to designate certain blocks going to certain warehouses, while still optionally leaving them open for other items to be put in.

-Designate given deliverymen to given resource production huts and warehouses. This would prevent a dman from one end of the town running to the other end to pick up items, then moving them to the warehouse next door, then running all the way back. 

-Have the dman go to another warehouse to deposit items if one is full instead of just complaining that there's no room.

**Comment by Raycoms** [comment]
Closed in favor of joint issue.
