### ISSUE TITLE
[1.12.2] Server crash StackOverflow Error

### ISSUE THREAD

**Issue by ProsperCraft** [ldtteam/minecolonies#4305]
### Minecolonies version

Version: minecolonies-1.12.2-0.10.592-RELEASE-universal-modified

### Actual behaviour <----spelling in template.

- 
Crash report-
https://gist.github.com/ProsperCraft/35083d214528df88d9ab5cbfb454a6c4

### Steps to reproduce the problem

Multiplayer server, not sure what they did, they don't seem to know either.

**Comment by ProsperCraft** [comment]
This happens every time one of our players goes to the nether

**Comment by Raycoms** [comment]
is there a colony in the nether?

**Comment by ProsperCraft** [comment]
No, but he thinks a colonist may have gone through.

**Comment by someaddons** [comment]
probably one of the raider mobs, since those caused the issue

**Comment by Raycoms** [comment]
@someaddons can you in your rework avoid portal entry of our mobs?

**Comment by someaddons** [comment]
in my rework they'd try to access the colony by id and not load a chunk, and since they won't find it they'll die

**Comment by someaddons** [comment]
so even if they enter a portal it should be fine I think

**Comment by Raycoms** [comment]
They shouldn't go through it anyway though

**Comment by ProsperCraft** [comment]
Guess you would need to handle minecarts taking them through, or being pushed through.
