### ISSUE TITLE
[1.15.2] Client Crash on load- MalformedJsonException

### ISSUE THREAD

**Issue by ProsperCraft** [ldtteam/minecolonies#4307]
### Minecolonies version

Version:  minecolonies-0.10.686-ALPHA-universal

- 
Latest Log
https://gist.github.com/ProsperCraft/0b69bebd0904eb67276821f46ba56a55

![2020-02-06_14 43 31](https://user-images.githubusercontent.com/4427684/73981284-28f8d080-48ef-11ea-9026-3cf6ab10aac0.png)

**Comment by Raycoms** [comment]
@Asherslab please fix and push directly!

**Comment by Asherslab** [comment]
Not sure why that didn't crash in my IDE, but done
