### ISSUE TITLE
builder doesn't build and crazy lag/ram usage

### ISSUE THREAD

**Issue by p0rtalmazter** [ldtteam/minecolonies#4308]
### Minecolonies version
minecolonies-1.12.2-0.10.679-RELEASE-universal

Version: 

### Expected behavior

builder builds things and colonists and mobs move smoothly

### Actual behaviour

Builder goes to the builders hut and stares at it for hours causing extreme lag, and apparently generating thousands of chunks (refer to image)

![image](https://user-images.githubusercontent.com/20197194/73990235-90764680-4916-11ea-9514-17088b801a49.png)

### Steps to reproduce the problem

1. not entirely sure, but happened after I made a deliveryman hut, testing now
2. 
3. 
4. ... Profit

**Comment by p0rtalmazter** [comment]
editing, I accidentally hit enter and apparently that finishes it

**Comment by Raycoms** [comment]
Found and fixed
