### ISSUE TITLE
ghost colonial village

### ISSUE THREAD

**Issue by judgefear** [ldtteam/minecolonies#431]
### Minecolonies version

version 0.6.2038 and curse version 7.1.6192.1696

### Expected behavior

- find the village working again

### Actual behaviour

- NPC disappear and all blocs MineColonies Mods inactive (non clickable)
I don't know if there is a way to repair that.

### Steps to reproduce the problem

1. walk far away from the colonial village (I was around 1400 blocs)
2. return to the colonial village
3. and note the bug

**Comment by marvin-bitterlich** [comment]
need client and server forge logs and more infos

**Comment by Raycoms** [comment]
and it seems like minecraft does corrupt data in some rare occasions when
it unloads chunks.

2017-01-07 12:13 GMT-02:00 judgefear <notifications@github.com>:
