### ISSUE TITLE
[Feature Request] More Player Models Compatibility

### ISSUE THREAD

**Issue by Jackal-z** [ldtteam/minecolonies#4311]
- Add a GUI for MPM (more player models) on colonists

- Possibly allow pieces of armor on guards to be set to invisible for aesthetic purposes?
       -i.e. If colonist is set as a centaur or satyr legs, leg armor wouldn't ruin the appearance of the legs

- I've seen requests for way to change skins on reddit, MPM has that as an option.

- MPM doesn't change hitboxes, only physical appearances.

This could allow players to customize their colonists to whatever style or motif they want whether it be dwarves, fey, giants, elves, etc. Or even if they just want to change their colonists skins to make them more unique on a server without going crazy with it.

**Comment by lendrick** [comment]
Just wanted to add something here because I was about to request something closely related:

It would be nice for modpack makers to be able to configure your villagers in a config file to look like any model from any mod.

**Comment by Raycoms** [comment]
Closed in favor of joint issue.
