### ISSUE TITLE
Builder no longer functioning

### ISSUE THREAD

**Issue by Avalonzo** [ldtteam/minecolonies#4316]
I was repositioning the town hall and the went afk for awhile and came to find the builder hadn't finished building the town and was stuck in place. I then tried to cancel and request the build again got a message on screen saying minecolonies had encountered a problem. Since then no matter what I do the builder won't build I tried restarting, hiring/firing different builders and even tearing down the builder hut and replacing it to no avail.

https://pastebin.com/eGu5JZ9t

**Comment by Raycoms** [comment]
Fire/rehire -> cancel, didn't work yet?

**Comment by Avalonzo** [comment]
No the two citizens I tried with just stand there idle and one of the citizens I tried hiring has the red cog with the ! but asks for a restaurant.

Edit: I loaded a back-up and all seems to be working for now.

**Comment by Raycoms** [comment]
the one with the red ! you can give food

**Comment by Raycoms** [comment]
Kk, something about this building got corrupted weirdly. I'll close it, please reopen it if you're able to reproduce it.
