### ISSUE TITLE
[1.12.2] Farmer not using hoes from Adventurer's Toolbox

### ISSUE THREAD

**Issue by SeriousCreeper** [ldtteam/minecolonies#4317]
### Minecolonies version
Tried with 1.12.2-0.10.679-RELEASE and 1.12.2-0.10.685-ALPHA

### Expected behavior
Farmer accepting hoe and going to work

### Actual behaviour
Farmer is requesting hoe. Crafted a wooden (also tried stone) hoe from Adventurer's Toolbox and clicked "fullfill request". She takes the how but then does nothing (the request for a hoe does go away). Giving her the hoe manually made no difference. Tried to use the colony requestsystem reset command as well.
If i give her a vanilla wooden hoe she immediately goes to work. 

As a side note, the lumberjack uses the axes just fine, builder uses pickaxe and shovel from adventurer's toolbox as well.

**Comment by Raycoms** [comment]
Will be added to a new joint mod compat issue.
