### ISSUE TITLE
RFTools Blocks....again

### ISSUE THREAD

**Issue by da3dsoul** [ldtteam/minecolonies#4319]
### Minecolonies version
Version: minecolonies-1.12.2-0.10.668-BETA

### Expected behavior
- Use RF Tools blocks such as the elevator or builder.

### Actual behaviour
- Permissions Error

I've seen this listed several times, and you (Raycoms) close the issues without anything being discussed or resolved. I'm not asking for specific code to work around it (though that'd be nice). I just want to know what I can do to make it work. For example, I looked at the code for RFTools, and the name of the fake player for the elevator should be `rftools_elevator` with the UUID of `acd65577-c30f-32af-b61e-90a819491259`.
When I add either one of those to the Permissions menu at the Town Hall, it doesn't take them.
What can I do?

**Comment by Raycoms** [comment]
If you try to use them, they trigger an event in the colony, (update to latest release first).
Then, in the townhall you will see a mention of this and a button with addPlayer, that will solve it

**Comment by da3dsoul** [comment]
Thanks. I should probably mention it to MCEternal, as that's the version I was using.

**Comment by da3dsoul** [comment]
... Sooo, is this a thing only on 1.14?

**Comment by Raycoms** [comment]
No, 1.12, 1.14 and 1.15

**Comment by da3dsoul** [comment]
Yeah I found it thanks.
