### ISSUE TITLE
In Game Config MineCraft 1.14

### ISSUE THREAD

**Issue by chriskeena** [ldtteam/minecolonies#4320]
### Minecolonies version

Version:  0.10.680-RELEASE
MC Ver: 1.14.4
Forge 28.2.0

### Expected behavior

- in game config button working

### Actual behaviour

- In-Game Config button is grey within MC 1.14.4. Checked against MC 1.12.2 for comparison.

### Steps to reproduce the problem

1. Launch Game
2. Click Mods button
3. Highlight Minecolonies
4. Config button remains dark and unuseable
5. ... Profit

**Comment by Raycoms** [comment]
Does this work with any other mod?

**Comment by Asherslab** [comment]
@Raycoms @chriskeena this has not been implemented by forge yet. and as such we cannot support it. please direct this issue to forge if you wish for it to be a thing again

**Comment by Nightenom** [comment]
There are already (or were) open PRs for that
