### ISSUE TITLE
hutblock not placing

### ISSUE THREAD

**Issue by Nazgoul9** [ldtteam/minecolonies#4321]
### Minecolonies version

Version: 0.10.689-ALPHA

### Expected behavior

- hut block to be placed with either building tool or by hand

### Actual behavior

- the hut block gets consumed but isn't placed in the world I've tried both placing it with and without the building tool and it doesn't work. the block isn't intersecting with anything and it doesn't matter how much space is cleared before it just won't place in the world. it isn't building specific, or building type specific my friend can place the hut blocks and it works just fine. I don't know if this issue is Minecolonies related or if its the server I'm playing on but I figured it wouldn't hurt to post this here

### Steps to reproduce the problem

1. get a hut
2. place in the world
3. it does/doesn't place in the world
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

**Comment by Raycoms** [comment]
Are you within a nother colony or so?

**Comment by Raycoms** [comment]
Is there a protection mod?

**Comment by Nazgoul9** [comment]
it's happening in my own colony and its any hut I try to place. I believe that there is no protection mod on the server or in the mod pack but I could be wrong.

**Comment by Raycoms** [comment]
are you in dynamic border mode?
is there any log output?
Did you try restarting and then trying?

**Comment by Nazgoul9** [comment]
i hadn't tried restarting it yet and I just did and it is working now

**Comment by Raycoms** [comment]
kk
