### ISSUE TITLE
[SUGGESTION] Nether building style for colonies in 1.16

### ISSUE THREAD

**Issue by Nazgoul9** [ldtteam/minecolonies#4322]
I think this could be cool if when 1.16 is available that mine colonies have a nether type of build to let players have colonies in the nether. I think the new updates to the nether could be used in its creation. I don't know how you would do it, because I've seen on multiple accounts that the colonist walk right through portal blocks and don't teleport like other mobs but I think it would be sweet to see this feature added in if/when the mod updates to 1.16

**Comment by Raycoms** [comment]
Build styles get contributed by the community, it's an artists individual choice, so we don't take suggestions on this end.
