### ISSUE TITLE
Cant place a warehouse 

### ISSUE THREAD

**Issue by michael33997788** [ldtteam/minecolonies#4324]
Minecolonies version:
minecolonies-0.10.678-RELEASE-universal.jar

Version: 
1.15.2
Expected behavior:
place a structure block and placement area for a warehouse.

Actual behaviour:
gives me a GUI to place it but then it disappears and says tile.blockhut.warehouse.limit

![image](https://user-images.githubusercontent.com/60942443/74272723-59b07f80-4ccc-11ea-9a12-6ce0af738125.png)

Steps to reproduce the problem:

1. i placed a warehouse block and it worked but it was on my fisherman's hut so i broke the block
2. i then placed a new warehouse block but it disappears
3. and it just says the tile.blockhut.warehouse.limit text

Logs:

i don't know how to get the logs

**Comment by michael33997788** [comment]
got it to work if i don't use the build tool

**Comment by Raycoms** [comment]
I found a bug related to this, I'll have to check it out.

**Comment by michael33997788** [comment]
ok i also keep needing to reinstall the mod if my game a has a forced shutdown like if i crash, or turn off my pc, etc

**Comment by michael33997788** [comment]
it only breaks if i try and use the build tool

**Comment by Raycoms** [comment]
That sounds weird with th ereinstall mod, why?

**Comment by michael33997788** [comment]
if my game has a forced shut down the GUI's don't work at all and i cant access anything within the mod
