### ISSUE TITLE
Rendering issues

### ISSUE THREAD

**Issue by thaylar** [ldtteam/minecolonies#4327]
### Minecolonies version

Minecolonies Version:  0.10.696
Structurize Version: 0.10.250

### Expected behavior

Placement of "Up/Down Gate Framed (block)" and "Side Framed (block)" connects with ground.

### Actual behaviour

Placement of blocks with the ground leaves a transparent strip, similar to x-ray vision, along the un-framed border of the block as noted in the image.  Happens with all Side Framed and UP or Down Gate Framed blocks.

### Steps to reproduce the problem

place a Side Framed block from structurize on the ground, vertical or horizontal will produce the x-ray vision like transparency.

![Untitled](https://user-images.githubusercontent.com/59156985/74288849-23d2c180-4cf3-11ea-8c09-49453d72c002.png)

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

**Comment by Raycoms** [comment]
fix pushed
