### ISSUE TITLE
Ticking Entity

### ISSUE THREAD

**Issue by jelaw21** [ldtteam/minecolonies#4328]
### Minecolonies version
Version: minecolonies-1.12.2-0.10.679-RELEASE-universal.jar

### Expected behavior

In earlier version, storage drawers worked in production huts.

### Actual behaviour

- 

I think the baker tried to remove wheat from a storage drawer and it caused a ticking entity.
[crash-2020-02-11_19.30.31-server.txt]

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:(https://github.com/ldtteam/minecolonies/files/4189304/crash-2020-02-11_19.30.31-server.txt)

**Comment by Raycoms** [comment]
hotfix pushed
