### ISSUE TITLE
Crash on looking at miners inventory

### ISSUE THREAD

**Issue by SadHorizion77210** [ldtteam/minecolonies#4329]
### Minecolonies Version
 Minecoloines -0.10.680-Release - universal 

### Expected behavior
<I had expected to see the miners inventory 
- <OI had gone to the Acacia mine lv1 to check on how the miner was getting on and went to check his inventory and look at what he had got >

### Steps to reproduce the problem

1. 
2. 
3. 
- latest.log:
- crashlog:

**Comment by Asherslab** [comment]
Those logs did not attach or anything. 
please use https://gist.github.com to attach them

**Comment by SadHorizion77210** [comment]
[crash-2020-02-13_11.39.29-client.txt](https://github.com/ldtteam/minecolonies/files/4196525/crash-2020-02-13_11.39.29-client.txt)

**Comment by Asherslab** [comment]
> please use https://gist.github.com to attach them

downloading text files is annoying and causes issues. as said^

**Comment by Raycoms** [comment]
Redownload, somehow the jar got an issue
