### ISSUE TITLE
Archery citizen doesn't return to job after sleeping

### ISSUE THREAD

**Issue by mashirochan** [ldtteam/minecolonies#4330]
### Minecolonies version

Version: minecolonies-0.10.680-RELEASE-universal

### Expected behavior

- Upon waking up, the citizen working at the archery hut should go back to their job and continue training archery.

### Actual behaviour

- Instead of going back to their job, the citizen will wake up, and stand in place. According to the debug they are currently stuck in the `ARCHER_SHOOT` state, which I believe might be the problem.

### Steps to reproduce the problem

1. Build an archery hut (mine was level 2, I doubt level matters though)
2. Wait for it to become night time and citizens go to sleep
3. Either sleep yourself or wait for daytime
4. All other citizens go about their jobs, but archer is standing still near bed in the `ARCHER_SHOOT` state

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: https://gist.github.com/mashirochan/31ec8a537691a39ed9145e9a85c156d0

**Comment by Raycoms** [comment]
Fixed,
