### ISSUE TITLE
Sloop creates an extra layer of water above the ocean that remains after the sloop leaves.

### ISSUE THREAD

**Issue by darkyth** [ldtteam/minecolonies#4332]
### Minecolonies version

Version: minecolonies-0.10.699-ALPHA-universal

### Expected behavior

- Pirate Sloop placed one block lower so that it is even with sea level and doesn't create flowing water around the sloop one block above the ocean.
### Actual behavior

- When mysterious sailors invade a colony the small sloop is placed too high in the water creating a layer of flowing water above the ocean that remains after the sloop leaves.

![2020-02-13_18 54 57](https://user-images.githubusercontent.com/44108740/74497949-dfcaf280-4e93-11ea-9bf4-76541ff9d2c1.png)

### Steps to reproduce the problem

1. Play Minecraft with the Mine Colonies mod.
2. Progress to the point when invasions can occur.
3. Be annoyed when a sloop comes and creates extra water above the ocean.
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: https://gist.github.com/darkyth/b9ec7304157d5be261e1be9ff518d854
- crashlog: N/A

**Comment by Raycoms** [comment]
Currently in work to be fixed =)
