### ISSUE TITLE
Fisherman not receiving fish

### ISSUE THREAD

**Issue by pauldavinjohansen** [ldtteam/minecolonies#4334]
### Minecolonies version

Version: 
minecolonies-0.10.678-RELEASE-universal
structurize-0.10.223-ALPHA

### Expected behavior

- Fisherman casting into nearby water and receiving fish with a durability loss on the fishing pole.
### Actual behaviour

- Fisherman tries to cast at various water blocks nearby, but the fishing pole does not receive a durability loss and no fish are received.

### Steps to reproduce the problem

1. Create world
2. Place Town Hall (tried acacia and norse)
3. Place Fisherman's Hut
4. Give the fisherman a fishing pole
5. Watch fisherman try to fish and fail repeatedly.

This issue initially occurred on a custom modpack in survival. I then made a new modpack with only the minecolonies and structurize mods to test this issue and it still occurred. 

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

**Comment by Raycoms** [comment]
Fixed in latest alpha, yes.
