### ISSUE TITLE
Game Crashes after placing structures

### ISSUE THREAD

**Issue by StonedBbg100** [ldtteam/minecolonies#4338]
### Minecolonies version

Version: 0.10.709-Alpha

### Expected behavior
For the buildings to be placed down 

 When placing down the  townhall structure I expect a bit of lag before placing the building. 

### Actual behaviour
The game crashes
 
When placing down any kind of structure game crashes.

### Steps to reproduce the problem

1. Be In creative mode 
2. Place structure down 
3. The game crahses
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog: [crash-2020-02-17_18.36.23-client.txt](https://github.com/ldtteam/minecolonies/files/4217126/crash-2020-02-17_18.36.23-client.txt)

**Comment by Raycoms** [comment]
Hotfix pushed

**Comment by Raycoms** [comment]
Please also update structurize

**Comment by StonedBbg100** [comment]
Thank you!!
