### ISSUE TITLE
[1.15][Bug] Builder freezes whenever he runs out of resources.

### ISSUE THREAD

**Issue by RZiegler979** [ldtteam/minecolonies#4339]
Minecolonies version: minecolonies-0.10.716-RELEASE-universal.jar
Minecraft 1.15.2

### Expected behavior
When provided with adequate food and materials the builder eventually builds things.

### Actual behaviour
Builder will build until he runs out of materials, instead of creating a request or returning to his building he stops right next to his base and stands there permanently. See Screenshot below.
If I finish supplying all materials for a building to the builders hut then recall the worker he will resume after a short delay(2-3 sec) and finish the building. If I don't recall the worker he will stand there indefinitely, ignoring night time, rain, etc.

![Builder Stuck](https://user-images.githubusercontent.com/60249008/74751481-ed390180-5232-11ea-982a-ca30d17ce5ce.png)

### Steps to reproduce the problem
1. Install Mod
2. Try to build a building and let him run out of supplies.
3. Builder gets stuck
4. Supply builders hut, shove worker, whatever. He won't resume until you recall him.
[latest.log](https://github.com/ldtteam/minecolonies/files/4220094/latest.log)

### Logs: Latest.log and crashlog at https://gist.github.com/
On reviewing the log I see a ton of messages from wall jump... possibly causing lag and leading to path finding issues?? Will try without the wall jump mod and report back if this is a compatibility issue.

**Comment by RZiegler979** [comment]
As a supplementary note, in case there was an issue with that specific spot where he kept getting stuck I built fences around it and made him path around it. He just gets stuck on the nearest block to that spot that he can still path to.

**Comment by RZiegler979** [comment]
Wall Jump is not the source of the problem. I observed the builder glitching into a house while trying to path to a build site. After a few seconds of glitching through the wall of the house trying to get to his destination he gave up, returned to his builders hut, and froze in place out by the fence where I took the original screenshot. Refuses to resume work until I recall him again. Can confirm that path finding is the source of the problem.

**Comment by Raycoms** [comment]
A few questions
a) Can we get the log (gist)
b) Is there a hole under the location he is at?
c) If you recall him, does he work correctly again?

**Comment by RZiegler979** [comment]
[latest.log](https://github.com/ldtteam/minecolonies/files/4221149/latest.log)
I already uploaded the log earlier, here is another one though, will check for a hole in a bit. If I recall him he works correctly for a little bit, until he runs out of resources, or paths into a building... etc. He eventually finds his way back to get bugged out here. On average about 2-3 minutes between getting bugged out. Can't finish a building without getting stuck a couple times.

**Comment by RZiegler979** [comment]
There was a hole under the path there, cable line for refined storage terminal... I buried the line deeper and added three layers of blocks to the ground. See if that makes a difference.

**Comment by RZiegler979** [comment]
Several buildings in a row with no issues. The problem was the hole under the path. I don't know if this is as intended or not so I won't close the ticket but you are welcome to do so. Maybe the builder stopping there is still a bug, even if we know what caused it.

Thank You.

**Comment by Raycoms** [comment]
I thought I fixed this pathfinding bug, I gotta test that out again.

**Comment by lunadragnstar** [comment]
I just ran into this, I'm on creative with infinite resources turned on. And my builder is just standing there. Has been standing there for at least 1 full in game day. However, after the night ran, the builder finally told me what he needed.

**Comment by Raycoms** [comment]
Yes, infinite resources is different.
