### ISSUE TITLE
Dark Oak Mine Level 3

### ISSUE THREAD

**Issue by Airidal** [ldtteam/minecolonies#4342]
### Minecolonies version

Version: 1.12.2-0.10.668-BETA

### Expected behavior

Would expect to see the level 3 dark oak mine be placed over the top of the level 2 without the bounding box moving when upgrading from level 2 to three.

### Actual behaviour

The level 3 dark oak mine builds and entirely new version up and to the right of the original when upgrading from level 2 to level 3.

![Mine Lvl 3 Fail](https://user-images.githubusercontent.com/24929153/74891483-26699280-5355-11ea-9240-77e2de07045e.png)

### Steps to reproduce the problem

1. Build a dark oak mine.
2. Upgrade the mine to level 2
3. Upgrade the mine to level 3
4. Be very confused when the mine is no longer functional and then figure out that the level 3 was built from scratch off centered from where the level 2 was built.

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:  N/A
- crashlog: N/A

**Comment by Raycoms** [comment]
@lunadragnstar

**Comment by lunadragnstar** [comment]
I'll check into this

**Comment by lunadragnstar** [comment]
Fixed, level 3 was missing the hut block

**Comment by Airidal** [comment]
Thank you *hug*
