### ISSUE TITLE
Maven Repository?

### ISSUE THREAD

**Issue by slushieboy99** [ldtteam/minecolonies#4343]
Hi there, I would like to make an addon for this mod but I cannot find a maven repository anywhere. Does one exist for minecolonies?

**Comment by Raycoms** [comment]
https://ldtteam.jfrog.io/ldtteam/webapp/#/artifacts/browse/tree/General/mods/com/minecolonies/minecolonies

**Comment by Raycoms** [comment]
maven {
        name 'LDTTeam - Modding'
        url 'https://ldtteam.jfrog.io/ldtteam/modding/'
    }

**Comment by marchermans** [comment]
It is highly recommended to use the API instead of the main mod as dependency.
There are no guarantees on the stability of the main mods implementation
However the API is pretty stable and will suffice in most cases.
