### ISSUE TITLE
Server Error 1.14.4 - Building Is Null When Trying To Place Any Building

### ISSUE THREAD

**Issue by stargateguy1** [ldtteam/minecolonies#4344]
### Minecolonies version

Version: 0.10.715-RELEASE-universal.jar

### Expected behavior

- Building placed with building tool.

### Actual behaviour

- Building item is removed from inventory like normal. Building then does not appear in world, and no error pops up in game. In server console, though, an error line appears stating:  

[Server thread/ERROR] [minecolonies/]: BuildTool: building is null!

### Steps to reproduce the problem

1. Place any building with builder's tool.

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: https://gist.github.com/stargateguy1/b3f849e33736a21c270449ddd06685ca
Apologies for long file. This is a server, so log is long. Error in question comes up around 2250 - 2300 hrs, towards bottom of file.

- crashlog: No crash. Game stays up and running.

**Comment by Raycoms** [comment]
Short question, do you have an item in your offhand?

**Comment by stargateguy1** [comment]
No I do not.

**Comment by Raycoms** [comment]
Weird bug, we had this in the past already and supposedly solved it, now it seems to have  reappeared in some cases. Is there a way to reproduce that?

**Comment by Raycoms** [comment]
Does this happen in singleplayer to you?

**Comment by stargateguy1** [comment]
Sorry for the delayed reply. I have not yet tested it in singleplayer.  I will test when I get the chance and post results here. 
I don't have any specific method to reproduce the issue other than by saying place any building. Sorry for the lack of any specific details. I'm relatively new to reporting issues with open source stuff like this. That, and I don't spend excessive amounts of time playing games.

**Comment by Raycoms** [comment]
Np, your doing better than most people =D

So, it happens for every building you are trying to place?

**Comment by stargateguy1** [comment]
I didn't test with each individual building, but I did try the archer hut, builder's hut, and one or two others. Also, one of the other players on the server reported the same issue in their colony shortly after I discovered the error. This led me to believe the error wasn't just me.

**Comment by DmasterD** [comment]
My server I have has the same issue, although it's just the huts.
A town hall works for example, as well as the decorational buildings. 
All the huts don't show any building with the building tool.

What appears to be strange to me, is that the most left selection shows decorations, the middle the huts or whatever, and the right selection is for selecting the builder's hut for example.

Shouldn't it be the huts on the left; the middle the builder's hut for example; and the right the type, like medieval oak?

**Comment by someaddons** [comment]
![image](https://user-images.githubusercontent.com/38401808/75375086-b49dc580-58cd-11ea-91cb-a644a8d8b38f.png)
Left is hut, middle is schematic type, right is level.

**Comment by DmasterD** [comment]
![MineColonies_Bug_2020-02-26_19 48 54](https://user-images.githubusercontent.com/8190232/75376972-39d6a980-58d1-11ea-96d0-83dc94c31779.png)

**Comment by someaddons** [comment]
well thats just a decoration thing, not an actual hut :D
you need to craft the hut block and have it in your inventory

**Comment by DmasterD** [comment]
I tried to place the hut block down. 
I pressed the button to use the build tool (not the place anyways).
This opens the builders tool in whatever was my last choice of decorations.
I can't find any hut.

**Comment by someaddons** [comment]
hutblocks are an item you craft, see https://wiki.minecolonies.com/source/misc/recipes the building tool only previews the item and lets you position it easier

**Comment by DmasterD** [comment]
What should happen when I'm trying to place the citizen hut? I'm not getting a preview of it.

**Comment by someaddons** [comment]
did you craft the item?

**Comment by DmasterD** [comment]
Yes I did

**Comment by someaddons** [comment]
you craft the item, put it into your own inventory, THEN use the buildtool with rightclick and the the topleft lets you choose the citizen hut instead of "decorations"

**Comment by DmasterD** [comment]
For some reason it worked now.
I've done the same thing last weekend, and no preview was showing up.
I've placed huts by guessing and being lucky lol.
Sorry for this. It sounded really similar to this bug.

**Comment by Sanysvo** [comment]
I have this problem in my server world(((

**Comment by Sanysvo** [comment]
Building is null in logs
