### ISSUE TITLE
Supply Camp places one to the left of the ghost image

### ISSUE THREAD

**Issue by WilxGaming** [ldtteam/minecolonies#4345]
Minecraft Version: 1.15.2 (modded) forge-31.1.0

minecolonies-0.10.716-RELEASE-universal.jar

### Expected behavior
The camp would place where the ghost image is.

### Actual behavior
The camp actually places 1 to the left of the ghost image. 

I have a 17x17 sky platform. I know the Camp is 16x17, but the 16 is up/down, not left/right. If I try to place it so the ghost image fits on the grass platform, when I hit the check mark it actually creates a new row of grass on the left and shifts the whole camp one to the left.

If the ghost image is 1 to the right, hanging off the right side of the platform, I would have expected an error, but it places the camp so it fits properly on the 17 wide platform.

Tested this many times trying to figure out what I did wrong, before I figured out the ghost image was off.

**Comment by lunadragnstar** [comment]
I tested this and it happens when you place the camp so that it faces north or east.

I'm checking other schematics to see if it is just the camp or if it is all

**Comment by WilxGaming** [comment]
I was facing north in all my tests.

**Comment by lunadragnstar** [comment]
Deco schematics are offsetting as well when rotating them

**Comment by lunadragnstar** [comment]
Huts are pasting fine as far as I can tell

**Comment by Raycoms** [comment]
Fixed in next structurize version
