### ISSUE TITLE
Weird crash while testing pasting

### ISSUE THREAD

**Issue by lunadragnstar** [ldtteam/minecolonies#4346]
MC .716
ST .254

Running paste test, I pasted several supply camps without issue (all in the same world, no errors that I've already pasted but that could be because I'm in creative)

But then when I went to test something else, and clicked the ground with the build tool, the game crashed

https://gist.github.com/lunadragnstar/46bf6949828702198a6c3f06b87fa33e

**Comment by Raycoms** [comment]
Definitely a weird crash

**Comment by Raycoms** [comment]
Added a safeguard
