### ISSUE TITLE
[1.15.2] No Event list generated for Digital Miner from Mekanism

### ISSUE THREAD

**Issue by Boomflex** [ldtteam/minecolonies#4350]
Modpack: Just Not Enough Mods 2 v0.4.5
Minecolonies RELEASE-0.10.716

In previous versions of Minecolonies an Event would be created when a Digital Miner tried to mine within a Colony.

As of RELEASE-0.10.716 this is no longer the case.

**Comment by Raycoms** [comment]
I made a small fix for this, however, there is also a chance that this is not working because the townhall must be level 1+ for this to work.
