### ISSUE TITLE
Decoration bug and others

### ISSUE THREAD

**Issue by lucalattanzio97** [ldtteam/minecolonies#4355]
minecolonies-0.10.716-RELEASE-universal.jar
minecraft 1.15.2

When I try to build a decoration such as the fortress angle wall, the builder only builds the 1st on the list and cant build the other 3. Also it gives me problems with the orientation. the field had the same problem: the builder couldn't build the 2nd or 3rd one, although the orientation was not an issue here.

There are also lots of visual bug: the shigle have shadow problems, some building chest are misplaced inside the building (the builder's chest is facing a wall for example) and have shadow problems, the racks shift places when placed by the builder (you can access the storage by clicking both on the actual position of the rack and where the racks looks to be).

I play the RaoulTech modpack so some of this can be due to a compatibility problem.

list of mods:
A Lib 
Additional Enchanted Miner 
Alchemistry
Ama's Damage Indicator
Biomes O' Plenty 
Blue Power 
Bonsai Trees 2
Chem Lib 
Corpse 
Default Amplified Biomes(DAB)
Dimensional Dungeons
Essentials
Expanded Storage
Extra Disks
Falling Tree 
Fast Leaf Decay
Gauges and Switches
Hwyla 
Inventory Sorter
Just Enough Items (JEI
Large Fluid Tank
Libnonymous
Mekanism
Mekanism Generators 
Mekanism Tools 
Minecolonies 
Miner's Helmet
Morpheus
OpenBlocks Elevator 
Ore Excavation
Packing Tape
Patchouli
Planet Evelon 
Potions Master
Ranged Pumps 
Refined Storage
Refined Storage Addons
Ropes Mod!
Scalable Cat's Force 
Serene Seasons 
Simple Chunk Loaders 
Spice of Life: Carrot Edition
Storage Drawers
Structurize
Tool Belt 
TorchBowMod 
Tubes Reloaded 
U Team Core 
Useful Backpacks 
ValkyrieLib 
Water Erosion (Forge and Fabric)
Xaero's Minimap (Fair-play Edition)
Xaero's World Map

**Comment by Raycoms** [comment]
Which exact decoration is it, I can't find "fortress angle wall", which buildings got the rack issues, and which building hut blocks have shadow problems?

**Comment by Raycoms** [comment]
All other bugs are fixed.

**Comment by lucalattanzio97** [comment]
sorry, i was talking about "wallcorner3" in the fortress tree. the rack issue happens in every building where more than 2 racks are placed next to each other. the shadow varies from level. at level 1 it didn't occur whereas at level 3 it does (builder hut). probably it depends on what blocks are near to it. the shigle have the same problem only when placed next to a wood block.
also i forgot to mention, in the barracks (fortress type) the barracks tower blocks are placed rotated and not in the right spot. i had to destroy the block and replace it myself.

![2020-02-22_12 25 02](https://user-images.githubusercontent.com/41806417/75091607-71f78880-556f-11ea-8a6c-a6d07c4367f3.png)
![2020-02-22_12 31 23](https://user-images.githubusercontent.com/41806417/75091608-7328b580-556f-11ea-9e70-5cceaec39d3a.png)

**Comment by Raycoms** [comment]
I fixed the hut block rotation issue already. And the shadow of the shingles too. Only building block shadow and rack remains

**Comment by lucalattanzio97** [comment]
even with the latest update i can only build the fortresscorner1 and even if i try to build any other fortresscorner (2,3,4) the builder just build the 1st. same mods, latest updates
minecolonies-0.10.720-ALPHA-universal.jar
structurize-0.10.257-ALPHA.jar

**Comment by Raycoms** [comment]
Ahhhhhhh, now I got your complaint regarding this =D
Hahahaha.

Let me check with the creator of the schematic. Meanwhile, check if you find a small decoration block in it that looks like a paper on a wall. Right click this, to upgrade it to higher levels.
