### ISSUE TITLE
Minecolonies not working on server

### ISSUE THREAD

**Issue by VorpalDefiance** [ldtteam/minecolonies#4358]
### Minecolonies version

Version:  minecolonies-0.10.709-ALPHA-universal

### Expected behavior

- right click on ground with supply cart item
- use build tool interface to position supply camp 
- confirm to place supply camp 
- supply camp appears

### Actual behaviour

1st attempt (on my Minecraft multiplayer server hosted on the same PC using the java edition server)
- Right-click on the ground with supply cart item
- use build tool interface to position supply camp but the ghost image seems to be missing
- confirm to place supply camp 
- game crashes  - crash log - https://pastebin.com/98vafGfe

2nd attempt (done in single player)
- Right-click on the ground with supply cart item
- use build tool interface to position supply camp (image visible)
- confirm to place supply camp 
- supply camp places and is interactable

3rd attempt (now back on the same multiplayer server)
- Right-click on the ground with supply cart item
- use build tool interface to position supply camp (image visible this time)
- confirm to place supply camp 
- the image disappears
- supply camp doesn't spawn

4th attempt
- Right-click on the ground with supply cart item
- use build tool interface to position supply camp (image visible)
- purposefully place incorrectly  
- confirm to place supply camp 
- image disappears
- received error message in chat regarding incorrect block types found in locations

no further crash logs beyond attempt 1 but just no result 

### Logs: Latest.log and crashlog

- latest.log:  https://pastebin.com/ZbZYYupt
- crashlog: https://pastebin.com/98vafGfe

if i find anything else as i work on fixing the issue il come back and add it

**Comment by Raycoms** [comment]
Please try the newest alpha
