### ISSUE TITLE
Citisens die to fall damage in front of Citisens hut

### ISSUE THREAD

**Issue by SirSmuggler** [ldtteam/minecolonies#4361]
Version: minecolonies-0.10.678-RELEASE-universal.jar and minecolonies-0.10.716-RELEASE-universal.jar

### Expected behavior
Citicens not dying falling out of theire houses to their death.

### Actual behaviour
Every once in a while a citisen dies due to fall damage, but when I go to the coordinates in the death message there is nothing for them to fall from.
It seems to be related to the citicens hut of the "Alternate wood"-type. I has happened in front of that kind of building of lvl 4 and 5.
Once I saw a citicen glitching out from the second floor repeatedly and taking falldamage on the exact spot where people have died before. In that instance, the gliching stoped befor he was killed, but I imagine that is how it has happende before. In this case it was evening and he was apparently trying to sleep in the bed at that floor.
Other times it has happened during daytime, but perhaps it is still linked to trying to access the bed?
In the screenshot you can see the deathmessage, and I'm standing at the same coordinates (even if it's a bit hard to see the debug text behind the chat text). As can bee seen there is nothing but the house to fall from.

### Steps to reproduce the problem
- Build citicen hut Alternative wood-style to lvl 4 or 5.
- Wait.

![2020-02-22_21 19 04](https://user-images.githubusercontent.com/1886337/75119814-a14ce900-5686-11ea-9624-fc2869ca4577.png)

**Comment by SirSmuggler** [comment]
After a lot more playtime, I feel confident saying this has to do with citisens trying to sleep in the bed/beds on the second and/or third floor. While doing so they tend to glitching out of the bed and end up outside the house and fall to the ground. That is not enough to kill them, but they get stuck in a loop doing it over and over untill they die.

**Comment by Raycoms** [comment]
Does this happen with the newest version?

**Comment by SirSmuggler** [comment]
I have played with minecolonies-0.10.763-BETA-universal.jar for a while today and so far has not had any unexpected deaths.

**Comment by Raycoms** [comment]
I did improve the bed handling with the newest update so it should be fine.
