### ISSUE TITLE
bug with fortress tree decoration

### ISSUE THREAD

**Issue by lucalattanzio97** [ldtteam/minecolonies#4363]
I cant build the fortresscorner2 (also 3 and 4) because every time i try to, the builder just build the fortresscorner1 oriented in a different direction. I already reported this problem but I assume I was not clear enugh.
![2020-02-24_10 55 37](https://user-images.githubusercontent.com/41806417/75142958-726d5c00-56f4-11ea-9252-6816aaa6225b.png)
![2020-02-24_10 54 47](https://user-images.githubusercontent.com/41806417/75142951-700b0200-56f4-11ea-876d-6f60664f001d.png)
![2020-02-24_10 56 39](https://user-images.githubusercontent.com/41806417/75142962-739e8900-56f4-11ea-86cc-733785ee8276.png)
I want to build the corner on the first picture (fortresscorner3) rotated 90 degree right, but the builder starts building the fortresscorner1 rotated as in the picture. 

i use minecolonies-0.10.727-ALPHA-universal.jar

the modpack is the raoultech with minecolonies updated as previously mentioned.
mod list:
A Lib
Additional Enchanted Miner
Alchemistry
Ama's Damage Indicator
Biomes O' Plenty
Blue Power
Bonsai Trees 2
Chem Lib
Corpse
Default Amplified Biomes(DAB)
Dimensional Dungeons
Essentials
Expanded Storage
Extra Disks
Falling Tree
Fast Leaf Decay
Gauges and Switches
Hwyla
Inventory Sorter
Just Enough Items (JEI
Large Fluid Tank
Libnonymous
Mekanism
Mekanism Generators
Mekanism Tools
Minecolonies
Miner's Helmet
Morpheus
OpenBlocks Elevator
Ore Excavation
Packing Tape
Patchouli
Planet Evelon
Potions Master
Ranged Pumps
Refined Storage
Refined Storage Addons
Ropes Mod!
Scalable Cat's Force
Serene Seasons
Simple Chunk Loaders
Spice of Life: Carrot Edition
Storage Drawers
Structurize
Tool Belt
TorchBowMod
Tubes Reloaded
U Team Core
Useful Backpacks
ValkyrieLib
Water Erosion (Forge and Fabric)
Xaero's Minimap (Fair-play Edition)
Xaero's World Map

**Comment by Raycoms** [comment]
Okay, in the fortresscorner building, there is a decoration controller block. (Looks like a paper at the wall). You can upgrade it using this.

(builder will only upgrade them from 1-2,2-3,3-4 etc and not build 2,3,4 directly).

About the rotation I would have to investigate

**Comment by lunadragnstar** [comment]
I am getting with the designer to get this figure out.

**Comment by lucalattanzio97** [comment]
> Okay, in the fortresscorner building, there is a decoration controller block. (Looks like a paper at the wall). You can upgrade it using this.
> 
> (builder will only upgrade them from 1-2,2-3,3-4 etc and not build 2,3,4 directly).
> 
> About the rotation I would have to investigate

the fortresscorner 3 has completely different dimensions from the other 3. also, i can't find the block you are talking about
are you sure you can upgrade them? maybe it's a different minecraft version...

**Comment by Raycoms** [comment]
We're waiting for the author of those to respond.

**Comment by lunadragnstar** [comment]
Fixed the naming for the corners, they are not degradable, but different options
