### ISSUE TITLE
Builders won't upgrade Medieval Oak Town Hall

### ISSUE THREAD

**Issue by Zuraax** [ldtteam/minecolonies#4366]
### Minecolonies version
Tried with 1.12.2-0.10.725-BETA (the latest version in 1.12.2), 1.12.2-0.10.714-RELEASE (the latest "Release" version in 1.12.2) and 0.10.716-RELEASE (the latest "Release" version in 1.15.2)

(Tried with both 1.12.2 and 1.15.2 to see if the problem was persisting - and it does)

### Expected behavior
Builders upgrade my Medieval Oak Town Hall to level 2

### Actual behaviour
When asking the upgrade of the Medieval Oak Town Hall, the builder will go to his hut then won't move at all. He won't ask for anything and won't do anything but standing still in front of his "Builder Hut" block

### Steps to reproduce the problem
1. Place the Medieval Oak Town Hall
2. Build it
3. Ask a builder to upgrade it to level 2
4. ... Profit

**Comment by Raycoms** [comment]
Tested it, and worked fine for me:
a) Please provide a log
b) Please try the latest alpha

**Comment by Zuraax** [comment]
How much time did your builder take before moving to the Town Hall ?

**Comment by Raycoms** [comment]
A minute or so. Depending on the size of the building. If the style matches, how much he has to scan it may need some time.

**Comment by Zuraax** [comment]
Well ,Medieval Oak Town Hall is quite big, especially the Level 5 one (not as big as the fortress though). I'll try waiting much longer and tell you if it works

**Comment by Zuraax** [comment]
Are you sure it worked with the Medieval Oak Town Hall ? Because i've already tried with another one and it works, only that specific one refuses to be upgraded and it's been 10 minutes i am waiting and there's nothing different : the builder still doesn't move

**Comment by Raycoms** [comment]
Yeah, it worked fine, can you try the latest alpha?

**Comment by Zuraax** [comment]
Already tried the last 1.12.2 alpha

**Comment by Raycoms** [comment]
and 1.15?

**Comment by Zuraax** [comment]
I've only tried the 1.15.2 Release version, not the Alpha one, but i'm more interested in a 1.12 version than a 1.15

**Comment by Raycoms** [comment]
When you use the schematic in the build tool to see level 1-5, do you see a significant change of rotation or position when you go through it?

**Comment by lunadragnstar** [comment]
It will take some time to "see" the builder upgrading to level 2 because level 2 has part of a basement and the builder needs to dig it out first.  That may be why you aren't seeing the builder doing anything but standing there.

**Comment by Maggoony** [comment]
I am getting this as well with upgrading the same building to level 2. The builder doesn't go to the town hall site, just stays in their hut doing nothing, even if you leave it a really long time. Upgrading other buildings not a problem. v 0.10.714

**Comment by Raycoms** [comment]
Should be fixed in the newest

**Comment by Vexikuri** [comment]
Sorry to bump, but i'm having this issue in 1.12.2-0.11.804 Release version as well.  Builder will build and upgrade other buildings, but just stands in the hut not doing anything.
