### ISSUE TITLE
Crash when open the citizenhut GUI

### ISSUE THREAD

**Issue by lordfriend** [ldtteam/minecolonies#4367]
### Minecolonies version

Version: 0.10.348-RELEASE

### Expected behavior

- 
It should not crash
### Actual behaviour

- 
When the citizen hut just finished upgrade to lv2,It crashed (this is a custom schematic)

### Steps to reproduce the problem

1. Build this citizen hut using the schematic provided
[Scandinavian.zip](https://github.com/ldtteam/minecolonies/files/4248787/Scandinavian.zip)
2. I upgrade to lv2

3. Once it finished, open the GUI of citizen, click build options

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: 
- crashlog: https://gist.github.com/lordfriend/661927f80989a572aca6aed980a08f4d

**Comment by Raycoms** [comment]
Okay
a) Is this 1.12.2 or 1.14.4 or 1.15.2?
b) Please update to the latest version, you are 300 versions behind.

**Comment by lordfriend** [comment]
MC: 1.12.2,
I tried with latest version minecolonies-1.12.2-0.10.714-RELEASE-universal.jar it still crash

**Comment by Raycoms** [comment]
Of course, it's because there is no level 3 citizen hut, so it will crash. You need all 5.

**Comment by lordfriend** [comment]
Ah, My bad. I forgot to put citizen3.bluprint in the schematics folder
