### ISSUE TITLE
"Infinite Ressource" and "Should the request system creatively resolve (if possible) when the player is required to resolve a request." doesn't work

### ISSUE THREAD

**Issue by MarxRoyal** [ldtteam/minecolonies#4368]
### Minecolonies version

Mod Version:  0.10.676-BETA

Game version: 1.14.4

### Expected behavior
- Builder would construct without asking for ressources

### Actual behaviour
- They ask like it wasn't active (And don't ask me if I restarted my game, I did)

![2020-02-25_15 31 11](https://user-images.githubusercontent.com/46058202/75256592-f4887e00-57e3-11ea-901f-478e62df462a.png)
![ds](https://user-images.githubusercontent.com/46058202/75256632-05d18a80-57e4-11ea-8d25-45da51a4983c.png)

**Comment by Asherslab** [comment]
1.14 is no longer supported. please update to 1.15

**Comment by MarxRoyal** [comment]
can't update to 1.15 if there is mods that isn't in 1.15

**Comment by Raycoms** [comment]
Tested, this works fine in 1.15
