### ISSUE TITLE
Tile Roof Half Slab Transparency

### ISSUE THREAD

**Issue by thaylar** [ldtteam/minecolonies#4369]
### Minecolonies version
Version:
Minecolonies 0.10.729
Structurize 0.10.263

### Expected behavior
Edges of structurize half slab clay/slate tile roof meet nicely when placed next to other half slab blocks.

### Actual behaviour
Half slab edge where it meets another block creates a transparent edge in the other block.

![Untitled](https://user-images.githubusercontent.com/59156985/75284044-a2425f80-57d9-11ea-8783-99c3e9856361.png)

### Steps to reproduce the problem

Place the structurize half slab roof tile next to another half slab.  Problem does not occur when next to full blocks.

### Logs: Latest.log and crashlog at https://gist.github.com/

No logs to report.  Problem does crash game. Just a rendering error.

**Comment by Asherslab** [comment]
i know why that is, just not certain how to fix it @Raycoms 
Basically it's because our roof slabs are considered a normal half slab model, so the vanilla slabs cull off edges against our slabs.

**Comment by Raycoms** [comment]
We just make their shape smaller.
