### ISSUE TITLE
Lumberjack not chopping, maybe path finding?

### ISSUE THREAD

**Issue by TheHotBaconBaker** [ldtteam/minecolonies#4371]
### Minecolonies version
minecolonies-0.10.716-RELEASE-universal.jar

### Expected behavior
Expect to chop down trees. collect wood and saplings, return to chest, start chopping again

### Actual behaviour
1. also have installed FallingTree-1.15.2-2.0.3+19 (do not know if this could be part of the problem)
2. does come to work
3. does not have axe in hand
4. does not eat I believe, which is odd
5. delivery man does come around, but just takes the surplus of axes that I had made and put into the warehouse.

### Steps to reproduce the problem

(set up townhall, did not build it. set up builder, build it. set up miner, build it. set up 4 houses, build it, set up lumberjack, delivery man, warehouse, build lumberjack)
1. make the lumberjack with an stone axe
2. be in plains biome, with no trees in sight
3. plant trees, oak and spruce
4. build
5. kill of 1st worker by lava (so NPC's won't be too upset)
6. hire better worker (this is what I did)
7. give stone and wooden axe
8. give saplings of both spruce and oak
9. I have tried setting both a perimeter and not, replant saplings and not
10. (I even reset the worker, fire/hire a couple times as well)
11. wait if something happens?

### Logs: Latest.log and crashlog at https://gist.github.com/
- latest.log:
- crashlog:
[crash-2020-02-26_11.56.48-client.txt](https://github.com/ldtteam/minecolonies/files/4255358/crash-2020-02-26_11.56.48-client.txt)
[fml-crash-2020-01-24_22.32.46.txt](https://github.com/ldtteam/minecolonies/files/4255359/fml-crash-2020-01-24_22.32.46.txt)

**Comment by Raycoms** [comment]
Any latest.log, I believe this is probably related to that tree mod.

**Comment by Asherslab** [comment]
also, please read the template. please upload those logs to https://gist.github.com

**Comment by TheHotBaconBaker** [comment]
[latest.log](https://github.com/ldtteam/minecolonies/files/4255380/latest.log)

**Comment by Asherslab** [comment]
@TheHotBaconBaker again, please upload logs to https://gist.github.com

**Comment by TheHotBaconBaker** [comment]
Never been on gist before. is this how you want it?
<script src="https://gist.github.com/TheHotBaconBaker/715fa5701e4f41ec818ec4686ad7f9c7.js"></script>

**Comment by Raycoms** [comment]
The crash is due to some invalid key. But I couldn't see anything related to the lumberjack in the logs.
But I highly suspect it is due to FallingTree-1.15.2-2.0.3+19.

**Comment by TheHotBaconBaker** [comment]
Did indeed solve the issue. However, its a shame that it is not compatible.

ty

**Comment by Raycoms** [comment]
Did you turn on all trees on the 2nd page?

**Comment by TheHotBaconBaker** [comment]
I did not at first, but did try only oak and spruce, then after also all saplings.

Now I have removed the treefalling mod, it worked at first. Just restarted MC, now it does not again. 

#https://gist.github.com/TheHotBaconBaker/de047f3ef72d05d8f08adb8fa3ad4ef4

Lovely

**Comment by Raycoms** [comment]
Hmm, that is very strange. What does the lumberjack do exactly, does he walk up to the tree?

**Comment by TheHotBaconBaker** [comment]
No, he does not stand or walk up to trees. He does not even stand near his work station. He stands 2 blocks beside it. 

![2020-02-27_15 56 23](https://user-images.githubusercontent.com/61498766/75455511-c8066a80-5979-11ea-9f8a-55a60d89965b.png)

**Comment by TheHotBaconBaker** [comment]
@Raycoms 

I did move the unbuild townhall. Then I noticed that the delivery man stopped as well. Killed them both of. Then the new ones asked me to build a warehouse (even though there was one). So I took 1 block out of every building, asked the builder to rebuild them in the exact spot. Delivery man started working again, lumberjack did not. 

I think this whole issue has to do with moving the unbuild townhall...

#https://gist.github.com/TheHotBaconBaker/d7b65ead4d3242268990b1c21f408190

**Comment by Raycoms** [comment]
Shouldn't happen with newer versions anymore.
