### ISSUE TITLE
my guard is break

### ISSUE THREAD

**Issue by AlphaRend** [ldtteam/minecolonies#4376]
Version: 1.12.2 forge

My guards and archer start typing and shoot in the void and I can no remove them, they always come back.
They are in a level 4 tower, with armor and sword, they ask Nothing.

You could me help? thank you

![2020-02-26_22 57 40](https://user-images.githubusercontent.com/60363898/75392036-84651f80-58eb-11ea-9c27-b57310ec8eb1.png)

![2020-02-26_22 57 24](https://user-images.githubusercontent.com/60363898/75392062-91820e80-58eb-11ea-8f76-edbae07598fb.png)

**Comment by someaddons** [comment]
sounds like an old bug, update and open a new report following the template.
