### ISSUE TITLE
supply ship and camp don't have any items in racks and no chest. and therefore you can't get a town hall.

### ISSUE THREAD

**Issue by bloodyraoul** [ldtteam/minecolonies#4377]
Version: minecolonies-0.10.730-ALPHA-universal

Actual behaviour
Build a supply ship or camp
Racks are empty
there is no chest with townhall

Bonus question : one of my player did it; he don't have a townhall and cannot build another camp
how to reset it so he can build a camp ?

**Comment by Raycoms** [comment]
For now they can just craft the townhall with 2 build tools (build tool middle and top and the rest planks)

**Comment by Raycoms** [comment]
While we fix this

**Comment by Raycoms** [comment]
fixed
