### ISSUE TITLE
Recipes disappear after server restart - 1.12

### ISSUE THREAD

**Issue by laeyon85002** [ldtteam/minecolonies#4378]
Version: minecolonies-1.12.2-0.10.592-RELEASE-universal.jar

### Expected behavior

I expect that entered recipes are still available after a server restart. 

### Actual behaviour

Recipes are saved and can also be viewed in the list. When the server is restarted, the recipes are gone and the list is accordingly empty.

### Steps to reproduce the problem

1.  Add a recipe.
2.  Restart server.
3.  Recipe isn´t saved annymore.
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: Don´t have any logs, they just disappeared.
- crashlog:

**Comment by Raycoms** [comment]
Fixed in 1.15.2. Unfortunately I don't have the time to merge those fixes back.

**Comment by Mortivarus** [comment]
How would this be fixed? It pretty much defeats the purpose of many of the buildings.

**Comment by Raycoms** [comment]
It still works when shutting down the server accordingly and not crashing it. However, it does not work when the server doesn't shut down completey. /mc colony backup also saves it for example. (as workarounds for 1.12)

**Comment by Mortivarus** [comment]
Will try that then, thanks!
