### ISSUE TITLE
Minecolonnies is conflicting with Advanced Chimneys mod

### ISSUE THREAD

**Issue by xavierh** [ldtteam/minecolonies#438]
### Minecolonies version
minecolonies-universal-1.11-0.6.2214.jar

### Expected behavior
- Builder use cobble stone when needed

### Actual behaviour
- Builder ask for Cobblestone Chimneys but do no build with it when the Advanced Chimneys mod is install
https://mods.curse.com/mc-mods/minecraft/244830-advanced-chimneys

### Steps to reproduce the problem

1. Create a Builder Chest
2. Ask him to build his hut
3. Builder ask for  Cobblestone Chimneys (instead of Cobblestone)
4. Builder is given Cobblestone Chimneys
5. Builder is still asking for Cobblestone Chimneys and is not building

Tested in **SSP** only

PS: I need to check what happen if I give him Cobblestone

/EDIT: SSP not SMP

**Comment by kreezxil** [comment]
I realize you are using 1.11 and not 1.11.2 as I am in issue #421, but did I just hear you right in that you said on your '''hopefully''' dedicated server that the npcs actually talk to you via the chat interface?

Which makes me wonder what the Forge team changed between 1.11 and 1.11.2 that caused the npcs to stop transmitting their strings correctly ... (again in regards to #421) [and hoping that your issue brings some insight]

**Comment by xavierh** [comment]
Hi Kreezxil,

Sorry I misstyped, I meant SSP. I have the same problem as #421 

Also I am using minecraft 1.11.2 but for some reason the package is called minecolonies-universal-1.11-0.6.2214.jar on curse

**Comment by kreezxil** [comment]
oh darn, I was hopingI found a clue to the #421 issue.  thanks for clearing it up. :)

**Comment by xavierh** [comment]
Yep sorry for that.

BTW do you know where the complete documentation for forge is ?

**Comment by kreezxil** [comment]
AFAIK, the most complete and latest as done by the Forge team theirselves is at https://mcforge.readthedocs.io/en/latest/

**Comment by xavierh** [comment]
I have done more testing on this issue today. The minecolonies mod seems to work fine with advancedChimney. The only problem is when worker need Cobblestone, they ask for Cobblestone Chimney.  If I give them what they ask for, they don't build but if I give them cobblestone, they start building as normal.

**Comment by xavierh** [comment]
Btw I also use Quark mod, and I don't have similar problem with it. Not sure if the problem lie on Minecolonies or AdvancedChimney side

**Comment by xavierh** [comment]
I have been testing advancedChimney in creative, I can clearly see that **Cobblestone** have been renamed by **Stone Brick Chimney**

I messaged the mod's dev. Closing the issue here
