### ISSUE TITLE
Colonists duplicating, 1.12.2

### ISSUE THREAD

**Issue by Bluepugs** [ldtteam/minecolonies#4380]
### Minecolonies version
minecolonies-1.12.2-0.10.714-RELEASE-universal
[latest.log](https://github.com/ldtteam/minecolonies/files/4270053/latest.log)

Version: 1.12.2

### Expected behavior
Only one colonist present.

### Actual behaviour
Standing, still duplicants that are largely visual. They can be interacted with and their inv updates live to their real clone somewhere in the colony.

http://prntscr.com/r9e0gf
### Steps to reproduce the problem
Don't know how to reproduce this - I suspect it has something to do with unloading/re-rendering chunks while the server is lagging a little.

### Logs: Latest.log and crashlog at https://gist.github.com/
Included in attachment, latest.jog
https://gist.github.com/Bluepugs/d6f3e3c25a657657c0996540fd782130

**Comment by Raycoms** [comment]
Yeah, we got an issue for that already, restart fixes it.
