### ISSUE TITLE
Guard keeps falling asleep on the ground

### ISSUE THREAD

**Issue by vhhawk** [ldtteam/minecolonies#4381]
### Minecolonies version

Version: 0.10.716

### Expected behavior

-  Guard uses bed in citizens hut. 

### Actual behaviour

-  A new child is born in unused bed in citizens hut. Guard still has no place to sleep.

### Steps to reproduce the problem

1.  My sequence. Start minecolonies. Build 4 citizens huts. Build Builders hut, Lumberjack hut, Mine, Fishers hut, Guard tower. Upgrade citizens huts. New children are born, grow to maturity.
2.  One of the newly grown children is assigned as the Guard. 
3.  The Guard patrols around, then falls asleep on the ground. Patrols, sleeps. When I click on the Guard, his icon is red for home. Upgrade another citizens hut, and instead of the Guard receiving a bed, a new child is born. I don't have a Barracks. 
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

**Comment by someaddons** [comment]
should be fixed now, guards need no home as they live in their work buildings
