### ISSUE TITLE
Supply Camp racks are empty. No Town Hall.

### ISSUE THREAD

**Issue by WilxGaming** [ldtteam/minecolonies#4388]
minecolonies-0.10.732-BETA-universal.jar

Minecraft Version: 1.15.2

(modded) forge-31.1.18

### Expected behavior
After placing the Supply Camp, there should be stuff in the racks, including the town hall.

### Actual behaviour
The racks are empty. Worked fine before the update.

**Comment by Raycoms** [comment]
Can you update to a newer version and then check?

**Comment by WilxGaming** [comment]
minecolonies-0.10.733-ALPHA-universal.jar

Racks still empty.

**Comment by Raycoms** [comment]
and latest structurize too?

**Comment by WilxGaming** [comment]
structurize-0.10.271-ALPHA.jar

**Comment by Nightenom** [comment]
@Raycoms your commit wasn't built cause of errors

**Comment by Raycoms** [comment]
Fixed. sorry

**Comment by WilxGaming** [comment]
Thanks. The update fixed it.
