### ISSUE TITLE
Command /mc colonies info <number>

### ISSUE THREAD

**Issue by xavierh** [ldtteam/minecolonies#439]
### Minecolonies version

minecolonies-universal-1.11-0.6.2214.jar

### Expected behavior

- Display the colony information

### Actual behaviour

- An unknown error occurred while attempting to perform this command

### Steps to reproduce the problem

1. Start a server 
2. Build at least 1 colony
3. Type _/mc colonies info 1_ in the **telnet** interface
4. get a nice java.lang.NullPointerException

I assume it try to get the information about the player running the command. As the command have been issue with the "telnet" interface, there is no player
[minecraft log.txt](https://github.com/Minecolonies/minecolonies/files/698674/minecraft.log.txt)

**Comment by Raycoms** [comment]
Yeah unfortunately you have to run the commands as a player. We will have
to change some things in the future to get it working with the console.

2017-01-11 9:36 GMT-02:00 xavierh <notifications@github.com>:

**Comment by xavierh** [comment]
In the present case, as I specified which colony I want to show the infos for. the player information is not even been used (ShowColonyInfoCommand.java:56)

**Comment by xavierh** [comment]
My bad, it is used to send the message back :/

**Comment by xavierh** [comment]
Actually the command _/mc colonies list_ list works but not _/mc colony info <number>_

This is because ShowColonyInfoCommand.java is getting the colony from the player information just in case the colony id have not been supplied (or is invalid)
