### ISSUE TITLE
Fisherman breakes upon reaching lvl 6.

### ISSUE THREAD

**Issue by SirSmuggler** [ldtteam/minecolonies#4392]
### Minecolonies version
Version: minecolonies-0.10.716-RELEASE-universal

### Expected behavior
I expect fisherman to keep catching fish even after reaching lvl 6.

### Actual behaviour
Fisherman will start fishing when first hired. Once reaching lvl 6, he/she will walk to water and cast out the line as normal, but nothing ever bites again.

### Steps to reproduce the problem
1. Build fishermans hut.
2. Hire fisherman.
3. Make sure he can level up to lvl 6 (seems to require upgrading the hut to lvl 2 and assigning a place in a citisens hut to the fisherman)
4. Let the fisherman work til he/she reaches lvl 6.
5. Watch as he/she stands and saddly look at the bober never moving again.

I first observed this in my survival world, after testing in two other creative worlds I came to the conclution that the trigger for the bug indeed seems to be reaching lvl 6.
I tryed building the fisher to lvl 1 and no citicens hut. Fisher then reached lvl 2 and stoped leveling, but keept getting fish.
I tryed adding a citicens hut, the fisherman then reached lvl 4 before leveling stopped, he still keept catching fish.
I upgraded the fishing hut to lvl 2. Fisherman then reached lvl 6, but imediatley upon reaching lvl 6, no more fish would bite.
Same thing witnesed in thre separate worlds now.

**Comment by Fey142** [comment]
Happens to me to but even sooner, he/she might catch like 15-20 drops then just stare at the water with the bobble in it but only visually. If you fire and re-asign someone else they also keep the rod on their character model (even doing another job untill they equip something else) -> even if they don't have a fishing rod in their inventory. 

Using the latest alpha for 1.15.2

PS: same thing happens to the next person on the job so fisherman is completely broken right now.

**Comment by Raycoms** [comment]
Found it!
