### ISSUE TITLE
Builder drops blocks (like signs and lanterns) when upgrading university and they despawn

### ISSUE THREAD

**Issue by mummabia** [ldtteam/minecolonies#4394]
Version: 0.10.738-alpha

Expected - Builder removes blocks in a specific order to collect all blocks from previous level before breaking the block they are attached to.

Actual - (Noticed this when upgrading from level 2 to level 3) Builder removes walls that have items attached to them, causing that item to pop off and drop.  The builder does not pick up the item and so they despawn.  Then, when they need to replace the item the item is missing and you need to recraft and provide them.  This has happened for signs, lanterns and banners that I've noticed.

Reproduce:
1. Upgrade University building (this may happen for other buildings, I have not checked) to at least level 2
2. Trigger the Builder to upgrade to level 3 and observe them when swapping out cobble for stone brick.

Thanks.

**Comment by Raycoms** [comment]
Yeah, that has always been like that and is actually very difficult to handle.

**Comment by pixar02** [comment]
This might not be the cleanest way but when the builder goes back for materials, before he leaves have him check for dropped items and make him pick them up. after that he can go and get the rest of the materials.

**Comment by Raycoms** [comment]
Closed in favor of joint issue.
