### ISSUE TITLE
Display Bug

### ISSUE THREAD

**Issue by TrystanB09** [ldtteam/minecolonies#4395]
### Minecolonies version
  0.10.716 - RELEASE

Version: 1.15.2

### Expected behavior

-  ?

### Actual behaviour
 

-  My problem is that I can't see all the block page when we open them, like the furniture needed to build a building or any other pages like allies list. 

 
<img width="852" alt="Capture d’écran, le 2020-03-07 à 08 06 02" src="https://user-images.githubusercontent.com/61908657/76144077-af1d4980-604a-11ea-89b9-06250d5ec898.png">
<img width="855" alt="Capture d’écran, le 2020-03-07 à 08 06 22" src="https://user-images.githubusercontent.com/61908657/76144078-b0e70d00-604a-11ea-888e-0b7b9ae87b11.png">

### Steps to reproduce the problem
 

1.   ?
2.  ? 
3.  ?
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: No
- crashlog: No

**Comment by Raycoms** [comment]
Are you on MAC?

**Comment by TrystanB09** [comment]
Yes I am on MAC.

**Comment by Raycoms** [comment]
We're having an insistent bugs related to Mac holders with our views. We could not figure out what is causing this yet. Playing around with screen resolutions of minecraft works as a temporary workaround. I'll close the issue since we got another one already.

**Comment by TrystanB09** [comment]
alright thx!
