### ISSUE TITLE
Request problem

### ISSUE THREAD

**Issue by Beaver831** [ldtteam/minecolonies#4397]
hey, i'm playing 1.12.2 on a server with the version 1.12.2-0.10.735 alpha of minecolonies, also i have a mod to have stack larger than 64 but it has never caused any problems (only graphical on the request), my buildings are almost all level 4.
i encountered bugs like the builder making request for items that he no longer need (he gets stuck on it), i restarted, fired him and make a reboot of the server but nothing work. (in addition there is no fullfill button)
![2020-03-07_17 03 52](https://user-images.githubusercontent.com/61879537/76147718-84111500-609f-11ea-8e19-39d22730ead9.png)
![2020-03-07_17 06 17](https://user-images.githubusercontent.com/61879537/76147727-8a06f600-609f-11ea-8969-fbb2c2e4c240.png)

also, i have a problem with the miner who doesn't make request and don't work, i did the same steps and that doesn't solve anything, after a long time the request will appear but it often does.
(the miner has been doing nothing for a while on the screen)
![2020-03-07_17 29 20](https://user-images.githubusercontent.com/61879537/76147806-406adb00-60a0-11ea-91cf-894bac5c1ddf.png)
![2020-03-07_17 29 22](https://user-images.githubusercontent.com/61879537/76147815-54aed800-60a0-11ea-93de-bdd214bd8081.png)

**Comment by Raycoms** [comment]
So when you cancel the request of the builder what happens?

**Comment by Beaver831** [comment]
sorry for the late response, when i cancel the builder's request it turns it off but only temporarily, it comes back after a while and he doesn't move from his place

**Comment by Raycoms** [comment]
I believe a /mc rs reset should fix most of your problems.

The request system seems troubled in this case. I can't reproduce it.
