### ISSUE TITLE
ModLoading not working

### ISSUE THREAD

**Issue by Wutupdawg600** [ldtteam/minecolonies#440]
### Minecolonies version

version 1.0? or curse 1.0
### Expected behavior

- Mods to all load so it can be updated and continue to play on minecolonies

### Actual behaviour

- Error Message: AppleCore is missing mods it depends on.  Include the following mods or remove AppleCore.  Forge 12.18.2.2123 or above.  See 'fml-client-latest.log' for technical information.

![image](https://cloud.githubusercontent.com/assets/25056695/21849175/c19bf8b2-d804-11e6-9f91-8699afa8cc66.png)

### Steps to reproduce the problem

1. Update again with this problem fixed?
2. Manually go in and remove AppleCore?
3. ...
4. Profit

**Comment by Raycoms** [comment]
Fixed with the newest version.
