### ISSUE TITLE
Deliveryman male model issue

### ISSUE THREAD

**Issue by MineShadow7** [ldtteam/minecolonies#4400]
### Minecolonies version

Version: minecolonies-0.10.743-BETA-universal
Forge - 31.1.9
MC - 1.15.2

### Expected behavior

- Deliveryman has the normal model without stretches and weird arms and head.

### Actual behaviour

- 
![2020-03-08_15 07 18](https://user-images.githubusercontent.com/28764927/76162430-ccd3d700-614e-11ea-9304-65e8b5a04fe3.png)
![2020-03-08_15 12 03](https://user-images.githubusercontent.com/28764927/76162479-3fdd4d80-614f-11ea-9bc6-303b57c62fc6.png)

### Steps to reproduce the problem

1. Have a deliveryman
2. Go to the previous versions like 1.14 or wiki to see the normal version like this: 
![image](https://user-images.githubusercontent.com/28764927/76162460-13c1cc80-614f-11ea-8809-d2de07122bb6.png)
3. ... Profit

**Comment by lunadragnstar** [comment]
I've showed this to the dev.
