### ISSUE TITLE
Warehouse not working after i downloaded the latest 1.12.2 version of Minecolonies

### ISSUE THREAD

**Issue by badacsonyigorenyember** [ldtteam/minecolonies#4403]
I saw some problem about that a long time ago. I started playing and i built a warehause first then a DM. The delivery man started saying the warehouse is full... I tried to damage the Warehouse and repaire it, but still don't work.
### Minecolonies version:
Minecraft 1.12.2
Version: Minecolonies 0.10.714

### Expected behavior
He doesn't say anything and put the items in the warehouse

### Actual behaviour
Saying Warehouse is full

**Comment by Raycoms** [comment]
did you try removing the racks and then repair?

**Comment by badacsonyigorenyember** [comment]
oh if everything is going well he put 5 dirts in the racks a few secs ago.

**Comment by badacsonyigorenyember** [comment]
yeah it is working now
