### ISSUE TITLE
Guards

### ISSUE THREAD

**Issue by Frogwisard1984** [ldtteam/minecolonies#4406]
### Minecolonies version

Version: 
minecolonies-0.10.688-ALPHA-universal.jar

### Expected behavior
i expect guards to guard my city not sleep while a Barbarian walks past him.

### Actual behaviour
guards sleep while a raid is going on and let raiders walk right past.

### Steps to reproduce the problem
just play the game and watch the town get ravaged by a raiding party while guards sleep too often

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:
### Suggestion: if its possible, make Barbarian raids and pirate Raids an event and guards not able to sleep while the event is ongoing. Another idea would be to have guards sleep in shifts thereby getting rid of the napping habit altogether.

**Comment by someaddons** [comment]
it is intended that they sometimes fall asleep, raiders should attack them on sight though and thus waking them up. Upgrading to the newest should fix the raiders running past
