### ISSUE TITLE
[Quickie] Restaurant and Hospital use the same recipe?

### ISSUE THREAD

**Issue by MineShadow7** [ldtteam/minecolonies#4407]
### Minecolonies version

Version: minecolonies-0.10.746-ALPHA-universal
MC - 1.15.2

### Expected behavior
- Different recipes

### Actual behaviour
- 
![2020-03-09_02 46 26](https://user-images.githubusercontent.com/28764927/76173384-36380200-61b0-11ea-87a6-41d3c28db81e.png)
![2020-03-09_02 46 31](https://user-images.githubusercontent.com/28764927/76173386-37692f00-61b0-11ea-8370-92e2d6300231.png)

**Comment by Raycoms** [comment]
(i am a) fail
