### ISSUE TITLE
Tinker's Construct crafting station bugging town hall recipe

### ISSUE THREAD

**Issue by justaguy38** [ldtteam/minecolonies#4408]
Version: 1.12.2-0.10.714-REALEA

Modpack: ETERNAL 1.3.3

Expected behavior: I expected to craft a town hall

Actual behavior: The town hall bugged out. I can not take it out. I tried shift click it and got a "ghost" town hall that can not be place and disappear on click.

Video: https://drive.google.com/open?id=1M3VRzTzZmP9PoVKINl8qBy94Gppyw1ER

Steps to reproduce the problem:
1. Craft town hall using Tinker's Construct crating station
2. Try to take out town hall
3. Shift Click town hall
4. Click on "ghost" town hall in your inventory

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
[latest.log](https://github.com/ldtteam/minecolonies/files/4305762/latest.log)

- crashlog:

**Comment by Raycoms** [comment]
Yeah, probably TConstruct doesn't support this kind of crafting recipes then. It is highly complex to make optional recipes in minecraft nowadays. That's the only way we can do it. And we cannot support crafting tables that differ too much in their implementation from vanillas.
