### ISSUE TITLE
Fortress style barrack towers placed weird/wrong

### ISSUE THREAD

**Issue by Frogwisard1984** [ldtteam/minecolonies#4410]
### Minecolonies version

Version: 

### Expected behavior

i expect the towers to have the towers and place holders in reasonable locations
### Steps to reproduce the problem

2. 
3. 
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

**Comment by bradogden** [comment]
Confirmed on mine also

**Comment by Raycoms** [comment]
I think they are in those places on purpose. What is the weird of it, does it destroy the structure around it?

**Comment by Grummelkater** [comment]
Yes, that’s what’s happening. They are overlapping and destroying the barracks and parts of the townhall if placed as suggested.

**Comment by Raycoms** [comment]
I'll contact the creator

**Comment by Kao713** [comment]
Still happening
