### ISSUE TITLE
NPE crash ticking entity

### ISSUE THREAD

**Issue by MineShadow7** [ldtteam/minecolonies#4411]
### Minecolonies version

Version: minecolonies-0.10.748-ALPHA-universal
MC 1.15.2

### Expected behavior

- non crash

### Actual behaviour

- Game Crashes

### Steps to reproduce the problem

I'm... Not really sure. Tbh it all started when I built the hospital in my colony. I tried to investigate until the game crashes, and saw lots of guards at the hospital (which has no healer since I haven't hired one yet). So probably:

1. Build a hospital
2. Have lots of people standing in it
3. Have no healer?
4. ... Profit??

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:  https://gist.github.com/MineShadow7/eebd77562717486f33b33837a33a353b
- crashlog: https://gist.github.com/MineShadow7/4c5fa2e003e5827913a8f13438aaf641

**Comment by Raycoms** [comment]
fixed
