### ISSUE TITLE
1.15.2 Floor/Roofless

### ISSUE THREAD

**Issue by MUHAKLorTheDorfTrottel4Github** [ldtteam/minecolonies#4416]
MC 1.15.2 
forge-1.15.2-31.1.16
minecolonies-0.10.748-ALPHA-universal
structurize-0.10.272-ALPHA
__________________________________________________________
most of the building ( huts, builder, warehouse etc) are without roof / floor

regards

### Minecolonies version

Version: 

### Expected behavior

- 

### Actual behaviour

- 

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

**Comment by lunadragnstar** [comment]
what style are you looking at? If you are working with dwarven, then that is by design, they are meant for underground. They were built for cavecolonies modpack.
