### ISSUE TITLE
[1.12.2] Pathfinding crash

### ISSUE THREAD

**Issue by mads256h** [ldtteam/minecolonies#4418]
A random crash i got while playing.

### Minecolonies version

1.12.2-0.10.714-RELEASE

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: https://gist.github.com/mads256h/00b1ddc9075e4cb0664d20b4e688e748
- crashlog: https://gist.github.com/mads256h/ee0495e3569a1eb7965ed65895979ab4

**Comment by Raycoms** [comment]
Fixed in the latest alpha
