### ISSUE TITLE
Builder will not build anything

### ISSUE THREAD

**Issue by forReason** [ldtteam/minecolonies#442]
### Minecolonies version

version minecolonies-universal-1.11-0.6.25

### Expected behavior

- Builder will build his hut when he has enough materials

### Actual behaviour

- Builder stands in front of his chst doing nothing

### Steps to reproduce the problem

1. build the supply chest
2. place the townhallchest
3. place the builders chest
4. click on "build"
5. Builder starts to clear the area from trees and bushes and so
6. Builder wont build

I tried everything:
built a new town, slept, restarted, put the required items in the builders inventory, put the items in his chest, fire him, hire him, replace the chest, recall the builder

The builder also says nothing in the chat what he needs. all he says is "hey there" or "Ill take care of it" every now and then 

I dont know what else to try. its very frustrating
![2017-01-11_22 29 01](https://cloud.githubusercontent.com/assets/12736950/21867193/612041a2-d84d-11e6-9cfc-b0dead62080c.png)

![2017-01-11_22 29 46](https://cloud.githubusercontent.com/assets/12736950/21867217/7feb43c0-d84d-11e6-8a49-7de1fb54666b.png)

![2017-01-11_22 30 26](https://cloud.githubusercontent.com/assets/12736950/21867240/99b3b148-d84d-11e6-92cd-5581117e6fd7.png)

![2017-01-11_22 30 29](https://cloud.githubusercontent.com/assets/12736950/21867245/9e0c6bd6-d84d-11e6-9688-e8c7f013fac6.png)

**Comment by Raycoms** [comment]
1.11 has some problems where build don't talk a lot. try fire and rehire
him.

2017-01-11 19:29 GMT-02:00 Julian B. <notifications@github.com>:

**Comment by forReason** [comment]
I fired him and hired him. then he walks aront the chest a half cirkle, looks at the chest as if he is interacting with it and then nothing will happen

![2017-01-11_22 33 45](https://cloud.githubusercontent.com/assets/12736950/21867369/2d2c680c-d84e-11e6-8639-566c4b267228.png)

**Comment by Raycoms** [comment]
he probably wants tools, looks like the language bug isn't fixed. Give him
a wooden shovel =D

2017-01-11 19:34 GMT-02:00 Julian B. <notifications@github.com>:

**Comment by forReason** [comment]
WOW really thank you. that solved it

**Comment by forReason** [comment]
If I have other workers like the lumberjack, do i have to craft the tools or can they do it with the rawmaterials? do I have to put the tools in their homechests?

**Comment by Raycoms** [comment]
You have to make the tools and materials for them still. But we're working
on automatic ways.

2017-01-11 19:39 GMT-02:00 Julian B. <notifications@github.com>:

**Comment by forReason** [comment]
thank you very much

**Comment by mistresskahlan** [comment]
I have this issue too, he just stops after a while, as if he gets bored!

![2017-05-19_11 35 47](https://cloud.githubusercontent.com/assets/2369033/26244429/86a72bae-3c87-11e7-8a2a-cbd61b383bd4.png)
![2017-05-19_11 35 51](https://cloud.githubusercontent.com/assets/2369033/26244431/86a9bb9e-3c87-11e7-96e5-6d38a6e4203c.png)
![2017-05-19_11 35 59](https://cloud.githubusercontent.com/assets/2369033/26244427/86a53934-3c87-11e7-87d8-cfeddcccb4ca.png)
![2017-05-19_11 36 02](https://cloud.githubusercontent.com/assets/2369033/26244430/86a76088-3c87-11e7-9caa-023bf3e71964.png)
![2017-05-19_11 36 05](https://cloud.githubusercontent.com/assets/2369033/26244428/86a59820-3c87-11e7-913a-131a833b0091.png)
![2017-05-19_11 36 10](https://cloud.githubusercontent.com/assets/2369033/26244432/86aa48ac-3c87-11e7-9f12-5847448b5f8b.png)

**Comment by mistresskahlan** [comment]
I also can't fire and re-hire a builder, he just sits there all the time doing nothing. I've cancelled all the jobs and tried placing again, and even cancelled those and tried upgrades but nothing. I've emptied his and the bench's inventory.... still nothing :(

**Comment by mistresskahlan** [comment]
killed everyone... no new people arrived.

**Comment by Foxiverse** [comment]
> killed everyone... no new people arrived.

If anyone ever experiences this, there is a option when in the fire/hire area that says automatic, I was finding it was seemingly impossible to fire him, clicking on that "automatic" option, you can click on it to change what it says, go to manual and it should fix it. To check if he is fixed try talking to him/checking stats, if it says he needs something, as long as it states what he needs and not "Unknown" it should be fixed, they do take a second to get to building so have patience.
