### ISSUE TITLE
Crash on launch 1.15.2  Error: java.lang.NullPointerException: Registry Object not present

### ISSUE THREAD

**Issue by Iglesias-Leafwind** [ldtteam/minecolonies#4420]
Minecolonies version
minecolonies-0.10.716-RELEASE-universal

Version: 
minecraft 1.15.2
forge 31.1.18
structurize 0.10.273-ALPHA

Expected behavior
After FML early loading progress to finish should launch minecraft.

Actual behaviour
Finishes FML early loading progress and when minecraft shows up crashes.

Steps to reproduce the problem
1.Launch minecraft
2.Click play.
3.Wait for FML early loading progress to finish
4.Minecraft opens and instantly crashes

Logs: Latest.log and crashlog:
- latest.log:
[latest.log](https://github.com/ldtteam/minecolonies/files/4320387/latest.log)

- crashlog:
[crash-2020-03-11_19.02.03-client.txt](https://github.com/ldtteam/minecolonies/files/4320389/crash-2020-03-11_19.02.03-client.txt)

**Comment by someaddons** [comment]
use the newest minecolonies alpha

**Comment by Iglesias-Leafwind** [comment]
Yep it's working thx just updated to version: minecolonies 0.10.757-ALPHA-universal.
