### ISSUE TITLE
[1.15.2]Client boot crash

### ISSUE THREAD

**Issue by EnterFor** [ldtteam/minecolonies#4422]
Crash on startup, can you see which side is the problem?
Details：https://github.com/mekanism/Mekanism/issues/5962

**Comment by EnterFor** [comment]
I found that it could be a localization problem

**Comment by Raycoms** [comment]
Is that the newest version?

**Comment by EnterFor** [comment]
> 那是最新版本吗？

No, when I deleted the Chinese localization, it still crashed when started, this is the latest log
Mod：minecolonies-0.10.753-BETA-universal
           structurize-0.10.274-ALPHA
logs：
[latest.log](https://github.com/ldtteam/minecolonies/files/4324925/latest.log)

**Comment by Raycoms** [comment]
Can you try the latest alpha?

**Comment by EnterFor** [comment]
> 您可以尝试最新的Alpha版吗？

Yes, the latest Alpha version can boot successfully!
In general, I don't dare to use the Alpha version because I'm afraid something will go wrong..

**Comment by Raycoms** [comment]
I'll create a new beta then as well.
