### ISSUE TITLE
Build GUI Bug

### ISSUE THREAD

**Issue by Wallenx** [ldtteam/minecolonies#4424]
Version:  1.12.2-0.10.714-RELEASE

### Expected behavior

hitting escape while in the build tool gui will keep the interface up

### Actual behavior

the interface vanished, and now the ghost of a building is stuck with no way to get rid of it

### Steps to reproduce the problem

1. place a hut down
2. hit esc while in the build gui
3. the interface will have vanished

### Logs:

N/A

**Comment by Raycoms** [comment]
right click with the tool in the air and then click x
