### ISSUE TITLE
unable to retrieve effect with id: null from the research effects map

### ISSUE THREAD

**Issue by Eddhkh** [ldtteam/minecolonies#4425]
Version: minecolonies-0.10.716-RELEASE & 758 -BETA

### Expected behavior
Place an order to upgrade /build a buildings

### Actual behaviour
No Builders is arranged for the orders, and the server log keeps repeating 

< unable to retrieve effect with id: null from the research effects map>

Fire & rehire NPC did not help, they just standing in their huts and not receiving any order to proceed 

### Steps to reproduce the problem

1. Assign builder 1 for building / upgrading
2. Place an order of upgrade / build

**Comment by Raycoms** [comment]
What are you trying to upgrade?

**Comment by Eddhkh** [comment]
Everything is the same, now I have reload a older backup, the function seems resumed, but the error message keeps occurring even I have do nothing.

**Comment by Raycoms** [comment]
Can you send me the world?

**Comment by Eddhkh** [comment]
How do I upload file here?

**Comment by Raycoms** [comment]
Needs to be on gdriver or dropbox

**Comment by Raycoms** [comment]
I fixed the error message in the next PR. =)
