### ISSUE TITLE
[1.15.2]Console error message? I don't know

### ISSUE THREAD

**Issue by EnterFor** [ldtteam/minecolonies#4427]
### Minecolonies version

Version: minecolonies-0.10.758-BETA-universal、structurize-0.10.274-ALPHA
Forge:31.1.18

### Expected behavior

-<! -- no error expected -- >

### Actual behaviour

-<! -- appears every time a player enters the server -- >

### Steps to reproduce the problem

1. <! -- start server -- >

2. <! -- waiting for players to join -- >

3. 
![image](https://user-images.githubusercontent.com/10114685/76629903-11f66f80-657a-11ea-9d96-289c24e5bf33.png)

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

**Comment by Raycoms** [comment]
Yeah that's some forge stuff issue.
