### ISSUE TITLE
Builder requiring 'Air' block to continue.

### ISSUE THREAD

**Issue by harleypig** [ldtteam/minecolonies#443]
### Minecolonies version

minecolonies-universal-1.11-0.6.2290.jar
Forge Mod Loader version 13.20.0.2206 for Minecraft 1.11.2
Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_111, running on Linux:amd64:4.4.0-51-generic

### Expected behavior

- Not require impossible block.

### Actual behaviour

- Requiring air block to continue upgrading

### Steps to reproduce the problem

Upgrade Miner to level 3.

http://imgur.com/23VXMrY

**Comment by Raycoms** [comment]
Working on it.

2017-01-11 19:37 GMT-02:00 Alan Young <notifications@github.com>:

**Comment by harleypig** [comment]
I started dinking around in minecolonies.dat in the saves dir and stupidly didn't make a back up copy.

I've totally bunged up the file, and now the builder and the miner are staring into space and the wall, respectively. Probably contemplating the owner's stupidity.

I'll restart and let you know if the same thing happens when I get to updating the miner to level 3 again.

**Comment by forReason** [comment]
same here. builder needs "Air"x0 times  for the basic field

version:
minecolonies-universal-1.11-0.6.25

Steps to reproduce the problem:

?!? Had it one time only when building a basic field

**Comment by Raycoms** [comment]
Should be fixed in the version I'll upload in a minute.
