### ISSUE TITLE
Can't craft a townhall

### ISSUE THREAD

**Issue by lunadragnstar** [ldtteam/minecolonies#4433]
Can't craft a townhall, using mc .762 (or .760) and st .275 (or .279)

steps:
place a townhall
try to craft a new one

results, nothing

**Comment by lunadragnstar** [comment]
The problem is that I was in creative, you should be able to craft a townhall in creative at all times, but that is up to you. :D

**Comment by Raycoms** [comment]
No, why should you craft it in creative if you can just obtain it?
