### ISSUE TITLE
Villagers gone

### ISSUE THREAD

**Issue by L1ght0ne** [ldtteam/minecolonies#444]
### Minecolonies version

version "minecolonies-universal-1.10.2-0.6.2038" from Curse mod pack "FTT3" (removes like 40 mods)

### Expected behavior

- All running good

### Actual behaviour

- Villagers disappeared
- Can't interact with the town hall and all

### Steps to reproduce the problem

1. Having fun on minecolonies (LAN server with my girlfriend, each have our own village at 1200 blocks)
2. Getting town hall lvl 3, builder lvl 4, villagers hut lvl 3
3. Launching builder lvl 5
4. Sleep in a bed
5. get stuck in bed (random minecraft bug)
6. ALT + F4 because game totally locked
7. Restart the game
8. No more villagers, no more interactions with buildings. In both villages

**Comment by Raycoms** [comment]
Sorry to hear that.  It seems like minecraft occasionally totally corrupts
our save files.
We're still researching how we could prevent that.

Am Mittwoch, 11. Januar 2017 schrieb L1ght0ne :
