### ISSUE TITLE
barrack research

### ISSUE THREAD

**Issue by MUHAKLorTheDorfTrottel4Github** [ldtteam/minecolonies#4444]
mc 1.15.2
forge-1.15.2-31.1.16
minecolonies-0.10.764-ALPHA-universal

please explain how to
RESEARCH BARRACKS

trying to build universtity 3:
builder alway ask for leather hat, if fulfill, ask again and again

**Comment by Raycoms** [comment]
Open GUI of university. Go to page 2, open combat page, get resoruces for research, click button, wait some time (hire a researcher)
