### ISSUE TITLE
increase in population / children

### ISSUE THREAD

**Issue by Gio1959** [ldtteam/minecolonies#4448]
### Minecolonies version

Version: 1.15.2
structurize : 0.10.281-alpha
Forge: 31.1.18
Minecolonies: 0.10.766-alpha

### Expected behavior
increase in population / children
I edited the following line of 
minecolonies-common.toml: maxcitizenpercolony = 70
also in the town hall I don't see the list of all the inhabitants but only a part

- 
they do not increase even though I have houses built but they are empty.
### Actual behaviour

 Try to give as much detail as possible here to help us properly understand the issue. -->
I attach images
### Steps to reproduce the problem

1. I can't replicate it

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: https://gist.github.com/Gio1959/4405c4dc67ce4c9ed1cdab05c0bc1e03
- debug.log: https://gist.github.com/Gio1959/0f58a8aaa654239fb9104b83ddfcaed0

![mine_3](https://user-images.githubusercontent.com/47612082/76790628-7fdfa880-67bf-11ea-96e2-3595ef1c6485.png)
![mine_6](https://user-images.githubusercontent.com/47612082/76790657-8a01a700-67bf-11ea-9f4c-1a955632755b.png)
![mine_4](https://user-images.githubusercontent.com/47612082/76791103-7145c100-67c0-11ea-849d-e04e69436b60.png)
![mine_2](https://user-images.githubusercontent.com/47612082/76791144-8589be00-67c0-11ea-8165-6982974a5ab7.png)

**Comment by Raycoms** [comment]
Some settings need a restart to take effect. Is this still a problem?

**Comment by Gio1959** [comment]
I have restarted several times, but the problem remains

**Comment by Raycoms** [comment]
can you upgrade to the latest alpha?

**Comment by Raycoms** [comment]
Did you test the latest version yet?

**Comment by Raycoms** [comment]
Please reopen if able to reproduce. Please send me the world then too.
