### ISSUE TITLE
Fortress barracks places Barracks Tower wrong

### ISSUE THREAD

**Issue by Kao713** [ldtteam/minecolonies#4451]
### Minecolonies version

Version: minecolonies-0.10.768-ALPHA

### Expected behavior

- Build barracks, then build Barracks Towers without problems

### Actual behaviour

- If you build barracks, it places barrack towers wrongly rotated and if build towers, they breaks walls and everything

### Steps to reproduce the problem

1. Build fortress barracks
2. Build fortress barracks tower
3. Wait to your builder to destroy walls and everything

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

**Comment by Flabuk** [comment]
Same issue Version: minecolonies-0.10.714-RELEASE
