### ISSUE TITLE
Dark Oak barracks wants the placeholder block: cant craft it

### ISSUE THREAD

**Issue by ChuckleMan** [ldtteam/minecolonies#4456]
### Minecolonies version
Version: 0.10.738-ALPHA, in the valhesia 2 2.1.1 pack
### Expected behavior
- Barracks Tower Placeholder block to be craftable, or the builder to not require/skip over/produce the block/the barracks have 4 placeholders in its inventory
### Actual behaviour
-  Builder cannot progress past the building step to place the placeholder 

![Screenshot_101](https://user-images.githubusercontent.com/51891881/76980500-2c8d6780-6931-11ea-8273-3b13b6b9b59d.png)
![2020-03-18_15 56 12](https://user-images.githubusercontent.com/51891881/76980729-79713e00-6931-11ea-8026-f8c1b4022ce5.png)
![2020-03-18_15 57 11](https://user-images.githubusercontent.com/51891881/76980733-7aa26b00-6931-11ea-95bb-27580598dea3.png)

### Steps to reproduce the problem

1.  Create a dark oak colony 
2.  Meet prerequisits for barracks 
3.  Place dark oak barracks, build order and fill builder
4. I have not tested other tilesets.

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

**Comment by Raycoms** [comment]
What version is this?

**Comment by ChuckleMan** [comment]
Apologies, typed it into the bit to comment it out. Updated it to the main body

**Comment by Raycoms** [comment]
That has been fixed in a newer alpha =)
