### ISSUE TITLE
Dark oak barracks lvl 2 upgrade traps builder

### ISSUE THREAD

**Issue by ChuckleMan** [ldtteam/minecolonies#4457]
### Minecolonies version
Version: 0.10.738-ALPHA, in the valhesia 2 2.1.1 pack

### Expected behavior
Builder upgrades dark oak barracks from lvl 1 to 2

### Actual behaviour
He can get trapped inside the main hut after placing blocks, meaning he has no way out, is trapped, and must either be recalled or blocks broken
![2020-03-18_17 56 11](https://user-images.githubusercontent.com/51891881/76991942-5a2edc80-6942-11ea-8eab-82f6b1a73379.png)

### Steps to reproduce the problem
1. Place barracks lvl 1
2. upgrade to lvl 2
3. This may not happen 100% of the time- Will vary on what he holds and where he pathfinds

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

**Comment by Raycoms** [comment]
Doesn't he teleport out after a while?

**Comment by ChuckleMan** [comment]
I watched him for about 5 minutes before recalling him, so not in that time

**Comment by lunadragnstar** [comment]
This is apparently the Medieval Dark Oak which isn't updated for 1.15 yet

**Comment by EnterFor** [comment]
I've had a similar problem where a construction worker would lock himself in a building and have to be recalled to continue,
I was building a compost hut, and any hut could recreate the problem.

I don't think the problem has much impact.

**Comment by Raycoms** [comment]
Fixed
