### ISSUE TITLE
[Problem] MinersAdvantage Compatability Issue (not working in colony boundaries)

### ISSUE THREAD

**Issue by 0xebjc** [ldtteam/minecolonies#4458]
### Minecolonies Version:
Minecolonies: minecolonies-1.12.2-0.10.714-RELEASE-universal.jar
Minecraft: 1.12.2
Forge: 14.23.5.2847
MinersAdvantage: MinersAdvantage-1.12.2-1.3.19.243.jar

### Expected behavior:
Using MinersAdvantage to mine a complete vein of an ore, or mine a shaft of blocks, or cut down an entire tree, basically all the MinersAdvantage features to work.

### Actual behavior:
MinersAdvantage works as expected outside of colony boundaries. Inside a minecolonies colony boundary it does not function.  I have verified this by holding the structurize tool in my hand to see the mineconlony boundary.  Going outside of the boundary MinersAdvantage work as expected.  Going into the minecolony boundary MinersAdvantage no longer functions.  It seems that the pathanation function still seems to work at times, but the shaftanation, vienation, and lumbination no longer work.

### Steps to reproduce the problem
1. Run Minecraft 1.12.2 with forge 14.23.5.2847, minecolonies-1.12.2-0.10.714-RELEASE-universal.jar, and  MinersAdvantage-1.12.2-1.3.19.243.jar.  create a server and client game, run the server, then login from a separate client system.
2. Create a supply ship and place it.
3. Get the Town hall and structurize tool.
4. Place the Town hall, and start a new colony
5. Start a builders hut, ( I usually start 3 builders huts )
6. Try to use the 'grave key' or alt key to mine blocks with pickaxe inside the colony boundary, MinersAdvantage no longer works.
7. Try to mine an ore with a pickaxe inside the minecolony boundary, MinersAdvantage no longer works.
8. Try to chop down an entire tree with an axe inside the colony boundary, MinersAdvantage no longer works.
9. Using the structurize tool in main hand to view the minecolony boundary, go outside the minecolony boundary
10. Perform steps in 6, 7 & 8, to accomplish mining, shaftination, vienation, and lumbination, all outside the minecolony boundary.  All MinersAdvantage functions work correctly.

### Logs:
None produced.

### Related Bug Tickets:
https://github.com/DuelMonster/MinersAdvantage/issues/38

**Comment by Raycoms** [comment]
If you ask me, I'm pretty sure that's on them. They mine the blocks without adding your player UUID to it. I'll keep this open but please request this to them as well.

**Comment by 0xebjc** [comment]
Yep, I did put in the comments here: 
DuelMonster/MinersAdvantage#38

Thanks for looking into this, so basically it the mod would apply a UUID when mining, then it should fix the issues?

**Comment by 0xebjc** [comment]
I'm tempted to fix this issue myself and recompile for my modpack, how to you add the player UUID when mining a block?  I see there is a lot of calls to fakePlayer, is that what causes no UUID to be applied?

**Comment by Raycoms** [comment]
basically he has to call the breakBlock method that gets a player and give it the player that is using the tool. And not set the block air and drop it. That should be all that's needed.
