### ISSUE TITLE
Workers not moving properly

### ISSUE THREAD

**Issue by MCninjakitty308** [ldtteam/minecolonies#4459]
### Minecolonies version 1.12.2-0.10.714 RELEASE

Version: 

### Expected behavior
My workers moving and doing what they need to do when they should.
My builders need to go to what they need to build when they have the proper resources.
### Actual behavior
Two of my builders follow the exact same path and walk into each other even when I relog or force them to move.

### Steps to reproduce the problem
I have no idea. This just happened randomly after I opened the game.

### Logs: Latest.log and crash log at https://gist.github.com/

**Comment by Raycoms** [comment]
Yeah, stuck handling will fixed. https://github.com/ldtteam/minecolonies/issues/4457

Same issue
