### ISSUE TITLE
Miners try helping each other casues issues

### ISSUE THREAD

**Issue by shivachirr** [ldtteam/minecolonies#446]
### Minecolonies version

curse 1.10.2.-0.6.2281

### Expected behavior

Miners mine there own mine area

### Actual behaviour

randomly when they are right next to another miner they try to mine the same mine of the other randomly. which causes issues with the main owner of the shaft issues

### Steps to reproduce the problem

1. Build 2-3 miners side by side to were the border fences will connect
2. hire and watch

**Comment by Raycoms** [comment]
Is it a bug or is it a feature?

Unfortunately we calculate the mine position from it's ladder. Therefore he
might find the others miner ladder and choose his mine to work on.
Please don't place them that close to each other.
That's also quite inefficient for them =D

2017-01-12 20:33 GMT-02:00 shivachirr <notifications@github.com>:

**Comment by shivachirr** [comment]
its a bug becuse it messes up the levels and how the main mine shaft owner miner works. and i place them that close to buidl the shafts and work on 3 differt levels in the same area

**Comment by Wissi** [comment]
The miners can't "share" the same level so close together. Where 1 miner will create the shaft, another might see it as "air" that needs to be blocked, they will interfere with each other. The pathfinding will be all confusing for both as well. The code is not designed for them to "share" a space or a mine shaft. It's not a bug. They just can't work in the same area so close, they're not coded that way. For efficiency in the way they work they need to be "alone" in their own space. I've found that at least 50 blocks away from each other (if not more) or these issues and more will be seen. Sorry, but they're not bugs.
