### ISSUE TITLE
[1.15.2]A trivial question

### ISSUE THREAD

**Issue by EnterFor** [ldtteam/minecolonies#4460]
![image](https://user-images.githubusercontent.com/10114685/77038448-c2d39300-69ee-11ea-9be1-86cbd598305c.png)
My building worker requested farmland block
How do I get it?

**Comment by Raycoms** [comment]
For which building?

**Comment by EnterFor** [comment]
university..
Is this a mistake?
I thought it was normal.

**Comment by EnterFor** [comment]
Any progress?
What the hell is going on
Is this normal?

**Comment by Raycoms** [comment]
Slow your horses. People sleep you know. What university style and which university level is this?

**Comment by EnterFor** [comment]
> 放慢你的马。人们睡觉你知道的。这是什么大学风格和大学水平？

I'm sorry. I apologize..

Acacia style
level：0-1（Just started construction）
I updated the latest version today
I will investigate whether it will happen again

**Comment by Raycoms** [comment]
fixed in latest structurize
