### ISSUE TITLE
Builder Requesting Items To Be Crafted When They Already Exist In The Warehouse.

### ISSUE THREAD

**Issue by drafro101** [ldtteam/minecolonies#4463]
### Minecolonies version

Version: 0.10.768-ALPHA

### Expected behavior

The Builder should request items from the deliveryman if they exist in the warehouse. If the item amount is not complete, the builder should request the rest from the crafters.
- 

### Actual behaviour

The builder will request items to be crafted when there are enough items in the warehouse. For example, he will request gravel from the crusher when there are gravel in the warehouse. The deliveryman also misses items that are crafted in any building.
- 

### Steps to reproduce the problem

1. Have required material in the warehouse
1. Upgrade or build a structure
2. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: https://gist.github.com/drafro101/eeb55e1305160724180111cac4abe455
- crashlog:

**Comment by kd5crs** [comment]
I am also seeing this in minecolonies-0.10.773-BETA-universal. The nice thing is that the crafter system is working great, unfortunately it seems to be prioritized over the warehouse amount.

**Comment by Raycoms** [comment]
I cannot confirm that. The warehouse is priority. The only reason the warehouse would do that is if the itemStack is not recognized in the warehouse.

**Comment by Raycoms** [comment]
Can you confirm if the deliveryman delivers it when there is no crafter?

**Comment by Raycoms** [comment]
Please reopen if able to reproduce.
