### ISSUE TITLE
crash when trying to paste a structure

### ISSUE THREAD

**Issue by kszysztoff** [ldtteam/minecolonies#4464]
### Minecolonies version

Version: minecolonies-0.10.757-ALPHA-universal

### Expected behavior

- 
after pressing the button the structure should appear
### Actual behaviour

- 
the game crashes

The game crashed whilst mouseclicked event handler
Error: java.lang.NullPointerException: mouseClicked event handler
### Steps to reproduce the problem

1. use buildtool on the ground
2. select a structure
3. use one of the blue buttons in the bottom right corner
4. game crashes

### Logs: Latest.log and crashlog at https://gist.github.com/

- crashlog: https://gist.github.com/kszysztoff/6e32cf8aa3a51aab812cd1b5661744e2

**Comment by someaddons** [comment]
update structurize and minecolonies to the newest alpha and try again pls

**Comment by kszysztoff** [comment]
tried it couple days ago before the new versions came out. works now. thanks
