### ISSUE TITLE
Minecraft Forge Crashes. (LINUX UBUNTU)

### ISSUE THREAD

**Issue by ghost** [ldtteam/minecolonies#4465]
So my Minecraft forge copy. It keeps crashing on ALL VERSIONS.  Like it will say that there was an error and there is NO LOG. Yesterday it worked. Then today it just stopped. Also before today Minecraft 1.15.5 would keep loading forever with forge. If I minimize that tab, then reopen it I can see
the Pause Menu just for 1 second. I was able to fastly click "back to the game" but then it showed the home screen for 1 second, then followed by a loading screen then 1 second then load. I'm on an old Linux ubuntu computer. (used to be windows 7)

**Comment by Raycoms** [comment]
Did you add optifine, the latest optifine is not forge compatible yet.
