### ISSUE TITLE
Placing a 'wooden' hospital just places a block of oak wood planks

### ISSUE THREAD

**Issue by MatthiasMann** [ldtteam/minecolonies#4466]
Version: minecolonies-0.11.775-ALPHA-universal

### Expected behavior
The hospital hut block to be placed.

### Actual behaviour
A block of oak wood planks is placed.

### Steps to reproduce the problem
1. Craft or otherwise get a hospital hut block
2. Use the building tool to place the hospital  using the style 'wooden'
3. A oak wood planks block is placed and the hospital is taken from your inventory.
4. ... Go back to 1 and try again - but this time use 'nordic' as that one works :/

**Comment by Raycoms** [comment]
fixed
