### ISSUE TITLE
Fortress University is copy of Dwarven

### ISSUE THREAD

**Issue by kd5crs** [ldtteam/minecolonies#4467]
### Minecolonies version

Version: minecolonies-0.10.773-BETA-universal

### Expected behavior

- Fortress University is unique

### Actual behaviour

- Fortress University is a copy of Dwarven

### Steps to reproduce the problem

1. Use build tool to look at both Fortress and Dwarven Universities

Also, Fortress has lots of jack o'lanterns, are those supposed to be a different block? Check out the Stonemason. Also also, alternatefortress/citizen used stripped oak logs, for which there is not a recipe. Thanks!

**Comment by lunadragnstar** [comment]
Fixed, should be in the next update
