### ISSUE TITLE
[1.15.2]Miscellaneous questions

### ISSUE THREAD

**Issue by EnterFor** [ldtteam/minecolonies#4469]
My mod version is always up to date
Can you leave this question open?
I will write all the strange things I found in the game in this question.

1. I couldn't find a string for the hospital text, so I couldn't localize it,I know it might take time.
![image](https://user-images.githubusercontent.com/10114685/77220023-96e31980-6b76-11ea-9c7e-2546c06325fb.png)

2. University GUI localization issues，I know it might take time.
![image](https://user-images.githubusercontent.com/10114685/77220222-d4e13d00-6b78-11ea-9b2a-e54163938fa8.png)
![image](https://user-images.githubusercontent.com/10114685/77220225-e0ccff00-6b78-11ea-84da-20788279508b.png)

3. Is this a pirate's sword?
![image](https://user-images.githubusercontent.com/10114685/77221692-ef221780-6b86-11ea-9ceb-98788f56ae0c.png)

4. Some progress is not added to the progress list.

5. I did not find the delete colony command, did not add it?
My player colony made an error, I can't delete it.

6. Farmers only plant seeds，Will not harvest..
![image](https://user-images.githubusercontent.com/10114685/77248512-dee86600-6c74-11ea-9d0a-919d0c1bb667.png)

Waiting supplement......

**Comment by Raycoms** [comment]
1-3) We got community people translating the mod. These things will be translated over time.
4) Yes, progress is mainly some initial guideline, not for all things
5) There is this command /mc colony delete. You can also trigger it by trying to place a new colony
6) Being reported and being fixed.
