### ISSUE TITLE
null pointer when adding build city hall lvl 5 order

### ISSUE THREAD

**Issue by ArnoSaxena** [ldtteam/minecolonies#447]
### Minecolonies version

version minecolonies-universal-1.11-0.6.2114

Action for target com.minecolonies.coremod.entity.ai.util.AITarget@7d35004 threw an exception:
java.lang.NullPointerException

### Steps to reproduce the problem

1. add city hall lvl 5 work order
2. see builder inactive
3. see above mentioned exception thrown every 5 seconds

**Comment by Raycoms** [comment]
Is there any complete log or only this?

2017-01-12 20:54 GMT-02:00 Arno Saxena <notifications@github.com>:

**Comment by ArnoSaxena** [comment]
fixed in minecolonies-universal-1.11-0.6.2265.jar
