### ISSUE TITLE
Can't build a warehouse.

### ISSUE THREAD

**Issue by TheNodop** [ldtteam/minecolonies#4470]
### Minecolonies version 
1.12.2-0.10.772-RELEASE

Version: 

### Expected behavior
I would expect to be able to place a warehouse

### Actual behaviour
When placing a warehouse and finalizing (through build-gui) it's position game says "you can only have 1" (Jungle City, no warehouse exist currently).

### Steps to reproduce the problem

1. Create Colony
2. Build Buldings
3. Craft Warehouse and Place somewhere
4. Place, move building-frame, (press esc and check the position, then place again), confirm. (Not sure if necessary.)
5. (No) Profit

**Comment by TH3Frag** [comment]
Had the same problem. I just kept trying to place it and build it. Took a few tries for it to not do that.

**Comment by Raycoms** [comment]
Turn on multiple warehouses in the config file is the easiest fix.
We reworked some systems in 1.15.2 where this is not occuring anymore.
But we won't be able to port that to 1.12
