### ISSUE TITLE
M.C.E - minecolonies Medieval styles building ladder BUG !

### ISSUE THREAD

**Issue by kl486134862** [ldtteam/minecolonies#4474]
Minecolonies version
- Version:  1.12.2-0.10.714-RELEASE-universal

### Expected behavior

- the villager can climb the ladder up and down of the Medieval styles building, and do the work he or she working on!

### Actual behaviour

- Villager stuck at the ladder, and then climb up and down repeatedly.

- https://youtu.be/8L9GmTXu7Mk

### Why I asked?

- because the issue is, I ask this question to the mod pack I'm playing, and they just told me to ask the origin mod owner. So I come here to ask this problem is fixed or not. Also, I saw there were two new versions, I don't know it fixed my problem or not, it yes I just tell the modpack owner to upgrade the modpack. Thank you

**Comment by Raycoms** [comment]
Update to newer version
