### ISSUE TITLE
All blocks are missing precise hitboxes

### ISSUE THREAD

**Issue by WenXin20** [ldtteam/minecolonies#4478]
### Minecolonies version

Version: `0.11.780-ALPHA`

### Expected behavior

- All blocks should have a more precise hitbox, similar to how the minecraft bell or lecturn has a precise hitbox

### Actual behaviour

- Instead, blocks often have hitboxes that are smaller than the actual block size, which can make it difficult to select the block. 
- A good example is the scarecrow, which is about two blocks tall, but it can only be broken from the bottom.
- Another good example is the barrel, despite having a taller hitbox, selecting it is only possible from the bottom half.

As seen from the image, the hitbox is smaller than the actual block
![2020-03-22_00 31 55](https://user-images.githubusercontent.com/12000593/77243185-58c91280-6bd5-11ea-88f0-3a620345cca0.png)

### Steps to reproduce the problem

1.  Place a hut.
2.  Observe its hitbox
3.  Most have a hitbox smaller than the actual block
4. ... Profit

**Comment by Raycoms** [comment]
Closed in favor of joint issue.
