### ISSUE TITLE
Construction Tape does not connect properly

### ISSUE THREAD

**Issue by WenXin20** [ldtteam/minecolonies#4479]
### Minecolonies version

Version: `0.11.780-ALPHA`

### Expected behavior

- Construction tape should connect similar to how fences connect

### Actual behaviour

- Instead, construction tape will only connect on two sides, and doesn't take 3 or 4 connections into account, which looks quite odd.
- This often occurs if the borders of two or more buildings are placed next to each other.

As seen from the image, the Construction Tape does not connect correctly.
![2020-03-21_19 20 32](https://user-images.githubusercontent.com/12000593/77243260-18b65f80-6bd6-11ea-9784-64900c110c3b.png)

### Steps to reproduce the problem

1.  Place construction tape
2.  Observe its connections
4. ... Profit

**Comment by Raycoms** [comment]
Closed in favor of joint issue.
