### ISSUE TITLE
builder got stuck on "fishing boat"

### ISSUE THREAD

**Issue by ArnoSaxena** [ldtteam/minecolonies#448]
### Minecolonies version

version minecolonies-universal-1.11-0.6.2114

### Expected behavior

- builder moving from fishery to building yard for new material

### Actual behaviour

- builder trying to move across "closed" trapdoor used for modelling fishing boat, but stopped by trapdoor indefinitely. As soon as trapdoor is opened, builder is moving again and continuing with her jobs.

### Steps to reproduce the problem

1. XYZ
2. ZYX
3. ...
4. Profit

**Comment by Raycoms** [comment]
We'll have to analyze that behavior the next time we'll improve our pathfinding =)

**Comment by nekatu** [comment]
I had the same issue with builders and guards; setting waypoints around the fishery helped the builder but the guard seemed adamant that he wanted to go through the boat. Dropping the sides of the boat seemed to workaround it though.

**Comment by Raycoms** [comment]
I took a look at it. Minecraft mobs also get stuck on that. It's the fault of minecrafts own locomotion code...
