### ISSUE TITLE
Citizens stuck of Grass Path

### ISSUE THREAD

**Issue by Senapaat1456** [ldtteam/minecolonies#4482]
### Minecolonies version

Version: minecolonies-0.10.715-RELEASE-universal.jar

### Expected behavior

- Citizens walking around town.

### Actual behaviour

- Grass paths (The vanila paths you get by right clicking grass blocks witha shovel) cause the citizns to get stuck in the middle of the paths I made. 

### Steps to reproduce the problem

1. Have a town
2. Use Grass Paths to connect buildings in the city
3. Wait
4. Pretty quickly, citizens will just stop moving, getting stuck in the middle of the paths. The only way to fix it is to fire / recall the worker.

If I had a hunch, the issue is caused by the fact that path blocks are slightly smaller then a full bloc (similart to soul sand)

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: No crashes
- crashlog: No crashes

**Comment by Raycoms** [comment]
fixed in newer versions.
