### ISSUE TITLE
Make bread be delivered to and served by cook at restaurant

### ISSUE THREAD

**Issue by drafro101** [ldtteam/minecolonies#4483]
When citizen are hungry and both a restaurant and baker exist they tend to only go to the restaurant. Can we have the bread the baker makes be delivered to and served by the cook?

**Comment by filikun** [comment]
I've noticed this to, is the bakery having any other purpose? We built a bakery first and it did not seem to deliver bread to the citizen at all.

**Comment by Raycoms** [comment]
The baker only makes bread. This gets picke dup by the dman and delivered to the warehouse and from there then to the restaurant. The baker doesn't serve bread.

**Comment by drafro101** [comment]
Why was this close? The issue is still not resolved because bread is not being delivered to the restaurant from the warehouse

**Comment by drafro101** [comment]
@Raycoms

**Comment by lexustec** [comment]
same here.
Restaurant asks for recipes also,
People go to restaurant and starve.
Warehouse has plenty of food. ( 6 stacks pork, 6 stacks cooked pork, chicken, cooked chicken, Bread .... )
