### ISSUE TITLE
Fortress Level 3 guard tower has grass (plant), dead bush, and fern

### ISSUE THREAD

**Issue by kd5crs** [ldtteam/minecolonies#4484]
### Minecolonies version

Version: minecolonies-0.11.785-BETA-universal

### Expected behavior

- No unbuildable blocks

### Actual behaviour

- Some unbuildable blocks scanned in

### Steps to reproduce the problem

1. Level 3 guard house
2. AlternateFortress Citizen also has unbuildable blocks (stripped oak)
3. 
4. ... Profit

If I understand correctly, the dead shrub issue gets included in scans by accident. A permanent solution to that problem would be for the builder to just automatically place any block without a recipe. That would take care of things like dead shrubs and stripped oak blocks, but if a mod adds a recipe for stripped oak blocks, the builder would request it like normal. If there is no recipe, it would place it and move on. That would really cut down on the trips into Creative mode. Thanks, loving Fortress style!

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

**Comment by Raycoms** [comment]
Being worked on, several reports exist already. Thanks for reporting.

Grass and dead should be obtainable via shears afaik same for ferns.
