### ISSUE TITLE
problems with fortress buildings

### ISSUE THREAD

**Issue by lucalattanzio97** [ldtteam/minecolonies#4487]
minecolonies-0.11.787-ALPHA

in the fortress-type barracks, the barrackstower are placed incorrectly: they are misplaced and misrotated.

the university in the fortress-type tree looks like the dwarven one. i didnt try to build it, but it doesnt look like a visual bug.

the hospital in the wooden-type tree will be built without its block. it has also already been reported that when you place it down, only a wooden block is placed. 

ty for your work

**Comment by Raycoms** [comment]
Being worked on, several reports exist already. Thanks for reporting.
