### ISSUE TITLE
[1.11.2] Builder and others still not telling what they need (commit 54fb0c7)

### ISSUE THREAD

**Issue by forReason** [ldtteam/minecolonies#449]
### Minecolonies version

Latest Commit 54fb0c710118074f92401f3881decf869d62cc2d on Minecraft 1.11.2

### Expected behavior

- Workers will Call for help if they are missing Materials or Tools
- Workers might give an error report on why they are standing around doing nothing

### Actual behaviour

- Workers stand around doing Nothing

### Steps to reproduce the problem

1. Build a village
2. Try to build the Building

The Commit attempted to fix the builders not saying what they need. It got better, however often you still have to crawl inventorys to see what they are missing

**Comment by Raycoms** [comment]
It would be nice to know in what of situations what kinds of items doesn't get requested =)

**Comment by forReason** [comment]
phew the situations are quite hard to investigate since they dont tell you what they need.
I have attached a screenshot of a builder watching the property doing nothing. he has got all materials and tools he needs (at least as far as I know) but i cant tell what is missing. often "fire & hire" solves the problem
same goes for my miner atm, i just cant figure out why he is not digging

probably related to #450?
![2017-01-14_00 08 57](https://cloud.githubusercontent.com/assets/12736950/21948880/381478bc-d9ee-11e6-90cd-859559b0c15a.png)

**Comment by Raycoms** [comment]
Might it be possible he requested it a while ago a few times and you didn't
read it?

**Comment by forReason** [comment]
nope. they have all materials. I insert them right after starting to build, when they are still clearing the place
also they finish the building if i fire & hire them. but sometimes i have to do it muiltiple times

**Comment by Raycoms** [comment]
okay I saw on your photo that there is a like a crater next to the build
side.
The builder calculates a save position to build from. Is it possible he is
unable to reach it?
Recall him and try to follow him where he goes.

2017-01-13 21:26 GMT-02:00 Julian B. <notifications@github.com>:

**Comment by forReason** [comment]
after 2 fire and hire it worked.

**Comment by Raycoms** [comment]
Probably wasn't able to find a good position and after hire fire he found a better one.

**Comment by forReason** [comment]
#457 Others having the same issue
