### ISSUE TITLE
farmer behaviour issue

### ISSUE THREAD

**Issue by lucalattanzio97** [ldtteam/minecolonies#4491]
minecolonies-0.11.787-ALPHA

the farmer wants to destroy fences and iron bars. i dont know if it applies also to other blocks such as gates, grass, flower,... can you please disable his ability to destroy blocks and just farm werever is possible? or you can add a option in the building menu so you can check if you dont want this behaviour from your farmer.
ty

**Comment by Raycoms** [comment]
version?

**Comment by Raycoms** [comment]
As already pointed out in another issue. Setup the border of the field at x/z level directly. So the farmers detect the end of the field there.
