### ISSUE TITLE
I cant break anything after place Town Hall

### ISSUE THREAD

**Issue by Kuttasy** [ldtteam/minecolonies#4493]
Version: minecolonies-0.10.715-RELEASE-universal

After placing the town hall (I bought it from creative mode because it is not in my inventory and cannot be crafted), I cannot place and break blocks anywhere on the map.

1. Create a world on adventure mode
2. Take town hall in creative mode
3. Place town hall and click place anyway
4. Back advanture mode

**Comment by Raycoms** [comment]
have you tried the latest alpha?

**Comment by Kuttasy** [comment]
Latest alpha working on 1.14.4 forge 28.2.0 ?

**Comment by Raycoms** [comment]
ohh, you are on 1.14.4. We stopped supporting 1.14.4 because of a lack of time.
1.15.5 has this bug fixed already (as does 1.12.2).

**Comment by Kuttasy** [comment]
1.15.5 ? Did you mean 1.15.2 ?

**Comment by Raycoms** [comment]
Sorry, yes
