### ISSUE TITLE
Farmer requesting axe for farming

### ISSUE THREAD

**Issue by NesiciCoding** [ldtteam/minecolonies#4496]
### Minecolonies version

Version: 0.11.788-ALPHA

### Expected behavior

-Farmer to use a hoe to farm instead of using an axe 

### Actual behaviour

- Farmer constantly requests an axe to farm, while having a hoe in his inventory which he isn't using. Cancelling the request doesn't help.

![IMG 1](https://user-images.githubusercontent.com/14938906/77462836-f6565900-6e04-11ea-9f69-bc5e69fca3a3.png)
![IMG 2](https://user-images.githubusercontent.com/14938906/77462834-f5bdc280-6e04-11ea-8f01-e7224a56b363.png)
![img 3](https://user-images.githubusercontent.com/14938906/77462835-f6565900-6e04-11ea-9d0e-1f291dcc3f0b.png)

### Steps to reproduce the problem

1. Open farmer
2. Look at requests 
3. See Axe instead of Hoe
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

**Comment by Raycoms** [comment]
Give him the axe, something is obstructing his field.

**Comment by NesiciCoding** [comment]
I checked, but there is nothing blocking the field. Gave him the axe, he just used the axe to farm. the hoe was untouched, but was still producing produce

**Comment by Raycoms** [comment]
What is he farming atm?

**Comment by kd5crs** [comment]
I can confirm, my farmer also uses an axe to chop wheat. The farmer does use the hoe properly to turn dirt into farmland.

**Comment by carlansor** [comment]
i have this same issue

**Comment by NesiciCoding** [comment]
He is farming both wheat and carrots, just two fields, that are completely clear of any obstructions

**Comment by PasixTheValkyrie** [comment]
Can confirm aswell. It just seems that sometimes something goes wrong and there's no produce though. I had a pretty min-maxed food stockpile going which seemed to rather abruptly stop when the farmer wasn't delivering enough out of nowhere.
