### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by TH3Frag** [ldtteam/minecolonies#4497]
Version:  minecolonies-1.12.2-0.10.714-RELEASE-universal

I helped the builder

I was helping the builder finish a building

Crashed the server

When I helped him complete the building, he came out look forward and then the game crashed.

Help the builder

Help the builder finish his building.

1. Place the last block needed to finish the building.
2.Nothing because it crashes

**Comment by someaddons** [comment]
Follow the issue template.

**Comment by TH3Frag** [comment]
Tell me where I did not follow it?

**Comment by kreezxil** [comment]
let's start with you need to update to the latest version of the mod. you are so way behind.
