### ISSUE TITLE
Client crash when confirming supply ship. Valhelsia 2 Modpack

### ISSUE THREAD

**Issue by EspieBodespie** [ldtteam/minecolonies#4498]
### Minecolonies version

Version: 0.11.785-BETA-universal

### Expected behavior

- Place *SupplyShip Chest - free* found in shipwreck in ocean.

### Actual behaviour

- I found a *SupplyShip Chest - free* in a 1.15.2 vanilla shipwreck.  Upon trying to place it in the ocean, my client crashes.  I am playing the Latest version of the Valhelsia 2 modpack, 2.1.3a.

![2020-03-24_12 45 27](https://user-images.githubusercontent.com/51254988/77470414-dd7e8100-6dcd-11ea-91d3-15e815079631.png)

![2020-03-24_12 45 50](https://user-images.githubusercontent.com/51254988/77470413-dc4d5400-6dcd-11ea-952e-867b47fba92f.png)

### Steps to reproduce the problem

1. Using *SupplyShip Chest - free* found in shipwreck, right-click water.
2. Select any ship type or leave default.
3. Position ship further into ocean without changing y-axis
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log and crashlog: https://gist.github.com/EspieBodespie/4e84342a443e3bf12af5c7e61909a48d

**Comment by someaddons** [comment]
upgradte to structurize 286 alpha to fix it
