### ISSUE TITLE
Farmer&Field wont stop create farmland

### ISSUE THREAD

**Issue by ventusanima** [ldtteam/minecolonies#4499]
Minecolonies version:
minecolonies-0.11.788-ALPHA-universal.jar

Version: 

### Expected behavior
The farme has to stop creating farmland if there are some non tillable blocks. (like the discription in the wiki)

### Actual behaviour
The farmer try to continue the work at the 11x11 grid of the field.

![2020-03-24_22 04 22](https://user-images.githubusercontent.com/62621596/77476886-c0709f00-6e1b-11ea-8759-84a4fb8dd921.png)
![2020-03-24_22 05 06](https://user-images.githubusercontent.com/62621596/77476897-c49cbc80-6e1b-11ea-978e-36cfe1163ed2.png)

### Steps to reproduce the problem

1. Rebuild the setup in the picture
2. The farmer will try continue the work
3. So that tiles wich should be protectet will be tilled

**Comment by Raycoms** [comment]
the farmer scans at the x/z for a block above ground. If you put the fence at the x/z level at the max length he will stop there. We don't consider any block to be the border since people might build paths in the field etc.
