### ISSUE TITLE
[1.11.2] Miner standing on top of Ladder not digging

### ISSUE THREAD

**Issue by forReason** [ldtteam/minecolonies#450]
### Minecolonies version

version latest Commit 54fb0c710118074f92401f3881decf869d62cc2d on version 1.11.2

### Expected behavior

- Miner goes down his mine and mines

### Actual behaviour

- Miner stands on the ladder of the mine looking downwards, doing nothing
- Workaround: check for missing Items (in most cases he still has enough items), "recall" the miner or if it doesnt help "fire and hire" 

### Steps to reproduce the problem

1. Build a Miner
2. Let him start working

**Comment by Raycoms** [comment]
Will take a look at that today.

**Comment by Raycoms** [comment]
Can't reproduce that. Did you give him the right tools for his hut?

**Comment by forReason** [comment]
he has got all the tools he needs but i cannot investigate further, as my workers often don't speak.
at the moment I cant even get him to work with "fire & hire"

**Comment by Raycoms** [comment]
That's quite strange I couldn't reproduce that.
He might need depending on his level (stone shovel, stone pickaxe) if he
finds stuff down there maybe higher tools or an axe.
He might need wooden slabs, ladders, planks, torches, fences.

2017-01-13 21:14 GMT-02:00 Julian B. <notifications@github.com>:

**Comment by forReason** [comment]
he wont take the stone tools
![2017-01-14_00 28 17](https://cloud.githubusercontent.com/assets/12736950/21949186/60a79532-d9f0-11e6-87d9-2a5758921e4c.png)

**Comment by Raycoms** [comment]
Remove the wooden ones =D he always takes the first he finds in his
inventory and not the best. He also needs cobblestone and fences.

2017-01-13 21:28 GMT-02:00 Julian B. <notifications@github.com>:

**Comment by forReason** [comment]
okay, removed the woodtools, and gave him fences and cobble. fired and hired him. still the same

**Comment by Raycoms** [comment]
can you show me the place he is currently working at?
Are you using the newest version of 1.11 on curse?

**Comment by forReason** [comment]
he is not working. he is standing around.

I am using the latest build from github

**Comment by Raycoms** [comment]
he never started working.

2017-01-13 22:21 GMT-02:00 Julian B. <notifications@github.com>:

**Comment by forReason** [comment]
He did work. until the hole was 3 deep
![2017-01-14_01 30 24](https://cloud.githubusercontent.com/assets/12736950/21950231/080a6de2-d9f9-11e6-923a-0182a45730af.png)

**Comment by forReason** [comment]
As Fire and hire did not work, i fired the worker and tried to hire another one - which worked well. the other worker is digging now

**Comment by forReason** [comment]
now the other miner stopped mining too
![2017-01-14_02 33 29](https://cloud.githubusercontent.com/assets/12736950/21951084/e39f1dfa-da01-11e6-9a61-763d497e4a1d.png)

seems like a pathfinding problem. after "recall" he goes down until he has to go up again,

**Comment by Raycoms** [comment]
Ahhh haha, that's a pathfinding bug. Just give him a little push forward,
he isn't able to path down there atm =D

2017-01-13 23:33 GMT-02:00 Julian B. <notifications@github.com>:
