### ISSUE TITLE
Builder does not keep destroyed items and destroys player owned overlapping buildings

### ISSUE THREAD

**Issue by Rithenar** [ldtteam/minecolonies#4502]
### Minecolonies version

Version: 1.12.2-0.10.714-RELEASE

### Expected behavior

This may be more of user error than a bug, but I have some of my own buildings in a sky base high above my colony. I placed down a farm that happened to overlap with one of my buildings on the same chunk. I didn't see the tape boundaries going over my building so the builder destroy part of my building including the AE2 system.

So 2 questions:

1- No drops remained with the builder or in  the warehouse so I had to craft again everything that was destroyed. Is there a way to make so the builder keeps the blocks destroyed?

2- Is there a way to make it so the builder does not destroy player buildings if they happen to overlap? Or once the build request is submitted, is there a way to move the building tape?  See pictures below

The area on the upper section of the picture (marble bricks and cursed earth was all destroyed by the building below
![destroyed area](https://user-images.githubusercontent.com/9939332/77496014-06c3ff00-6e18-11ea-9aa4-66be9be22c4e.png)

Builder destroyed part of the AE2 system and drawers but they are not in any inventories so they were all deleted.
![items destroyed](https://user-images.githubusercontent.com/9939332/77496162-5a364d00-6e18-11ea-817e-17aaf3397787.png)

- 

### Actual behaviour

- 

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

**Comment by Raycoms** [comment]
1) As far as I know AE only drops blocks when they are mined with specific items. So we can only support that for blocks that use the normal minecraft behaviour.

2) That is unfortunately impossible to detect.
