### ISSUE TITLE
NPC's stuck ladder

### ISSUE THREAD

**Issue by StijnMartens** [ldtteam/minecolonies#4505]
Version: minecolonies-1.12.2-0.10.714-RELEASE

### Expected behavior
NPC's descend the ladder and go do their job.

### Actual behaviour
NPC's get stuck at the top of the ladder and stay there.

### Steps to reproduce the problem
1. Build a house in medieval oak style
2. NPC's using the bedrooms you can reach with a ladder often get stuck and stay there permanently.

**Comment by Raycoms** [comment]
later alpha should have this fixed. Can you try that?

**Comment by StijnMartens** [comment]
Updated to latest release and it is indeed working now. Thank you very much!
