### ISSUE TITLE
Level 2 Nordic cowboy upgrade requires nether bricks

### ISSUE THREAD

**Issue by jolandepoel** [ldtteam/minecolonies#4507]
The schematic for the level 2 Nordic Cowboy's Hut (MC 0.10.716 in Boothill modpack 1.3.1 for Minecraft 1.15.2) requires 3 nether brick stairs. Since nether brick is a level 4 Builder's Hut material, I feel this material is too high level for the Cowboy's Hut lv 2, and should be replaced with a more appropriate building material to prevent unnecessary gating of the Cowboy's Hut upgrades.

Suggested solution: replace nether brick stairs in level 2 Nordic Cowboy's Hut with an overworld material such as dark oak stairs.

**Comment by lunadragnstar** [comment]
Rescanned
