### ISSUE TITLE
Server crush immediately right after pirate ship spawned

### ISSUE THREAD

**Issue by AWPgodkiller** [ldtteam/minecolonies#4508]
## Minecolonies version

Version: 0.10.772-RELEASE
(Play on Crackpack 3)

### Expected behavior

- Pirate ship spawned without any problem.

### Actual behavior

- Server crash immediately right after a Pirate ship spawned.

### Steps to reproduce the problem

1. Wait for the pirate ship to spawn
2. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog: https://gist.github.com/AWPgodkiller/4e824f1e54ca6ae6c367e9f51a2a56e8

**Comment by Raycoms** [comment]
A mod is removing normal vanilla spawners from the game it seems. Or replacing and removing their tileEntities. There is not much we can do in tht case. Please report it to the responsible mod author.
