### ISSUE TITLE
[1.11.2] Builder Working speeds

### ISSUE THREAD

**Issue by forReason** [ldtteam/minecolonies#451]
### Minecolonies version

latest Commit on version 1.11.2 54fb0c710118074f92401f3881decf869d62cc2d

### Expected behavior

- Builder Works at (roughly) the Players speed or Maybe half as fast to let the workers level do the Progress 
- Miner and forester may be a lot slower, progressing greatly by levels

### Actual behaviour

- When Digging/Clearing The Builder is roughly 10 Times slower than the player. While this is fine for All workers for the builder it is terribly annoying because you cann not watch for example when he clears out the area. I changed my behavior to clear all trees and dig out the area manually due to that

- When Building the builder is roughly 100-1000 times(!) faster than normal players. This is a result of blocks beeing placed instantly and no repositioning is needed - probably a _bigger_ pause (0.5~2 seconds) between placement of Blocks ould be great

### Steps to reproduce the problem

1. Build a building and whatch the builder do his Job

**Comment by xavierh** [comment]
I have done a modification to allow to adjust the speed for mining and the speed for building.

Adjusting the speed of mining is done by adjusting the AbstractEntityAIInteract::DELAY_MODIFIER while for the speed of building is affected by adding a delay after a (non-air) block is placed.

Both are modifiable through the config/minecolonies.cfg file.

I haven't done a pull request for it yet, planning to do it this week end.

I have done the change for the speed of mining to allow fast testing.

For the speed of building, it annoy me that they are building so fast.

**Comment by forReason** [comment]
are builder and specialized worker mining speed configurable separately?

**Comment by xavierh** [comment]
No, AFAIK they are both using the same DELAY_MODIFIER in the current source code and I left it as is.

I implemented this for test purpose, so I can build quickly and see if everything is working correctly

**Comment by Raycoms** [comment]
Has been implemented already.
