### ISSUE TITLE
Minecolonies Chickenherder eats too much

### ISSUE THREAD

**Issue by simonboasaeter** [ldtteam/minecolonies#4512]
### Minecolonies version

Version: 0.10.715-RELEASE-universal

### Actual behaviour

The chickenherder eats ALOT, not 5 bread. He eats 18 breads at once... This must be a bug?

**Comment by someaddons** [comment]
the chickenherder doesnt have anything special regarding eating, its the same for all workers

**Comment by simonboasaeter** [comment]
He is the only one eating the enormous amount however? I cant remember the last time I fed the other citizens.. Does he eat for the whole city?

**Comment by Raycoms** [comment]
Can you update to a much later version? This should be fixed
