### ISSUE TITLE
My citizens bugged, no one is in the town hall registered

### ISSUE THREAD

**Issue by Fekrix** [ldtteam/minecolonies#4513]
### Minecolonies version

Version: minecolonies-1.12.2-0.10.714-RELEASE-universal

### Expected behavior

The citizens behaving as usual

### Actual behaviour

2 Citizens dissapeared from nothing, they arent registered in the town hall and 1 of them is in a place in the world but i cant interact with it in any way. I tried to get new citizens  but i couldnt as i cant build anything more since I have no builder, so i killed the remaining 2 citizens in the colony and now nothing appears anymore

### Steps to reproduce the problem

1. Dont know
2. Still dont know
3. Bugged
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

**Comment by Raycoms** [comment]
1) Update to a slightly newer version
2) You can hire some workers in the GUI in the townhall to come instantly
3) Recall All should usually work to fix those lost citizens, But that shoulld also be fixed in the newest version
