### ISSUE TITLE
Villagers duplicating themselves 

### ISSUE THREAD

**Issue by Rami-Pastrami** [ldtteam/minecolonies#4519]
### Minecolonies version

Version:  minecolonies-1.12.2-0.10.772-RELEASE-universal

### Expected behavior
Villagers don't duplicate

### Actual behaviour
At random, the villagers seem to duplicate themselves. the dupes do not have hitboxes. restarting the server fixes this.

https://cdn.discordapp.com/attachments/691374798424768582/692902374548963428/2020-03-26_21.05.13.png

https://cdn.discordapp.com/attachments/691374798424768582/692902377677651998/2020-03-26_21.05.27.png

https://cdn.discordapp.com/attachments/691374798424768582/692902261654814821/unknown.png

### Steps to reproduce the problem
Unknown, currently just occurs on its own
[debug.log](https://github.com/ldtteam/minecolonies/files/4391194/debug.log)

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: attached
- crashlog: (no crash

**Comment by someaddons** [comment]
should be fixed in the newest already

**Comment by Scampi-ml** [comment]
Hello, i want to re-open this issue.

![image](https://user-images.githubusercontent.com/1528455/152658595-44ef3be8-d9b7-4091-8755-e2284926e7cb.png)

They are duplicating them selfs at the work bench, i have 3 duplicates running around

Running at minecolonies-1.18.1-1.0.378-ALPHA.jar

**Comment by MotionlessTrain** [comment]
That is a vanilla bug actually. Restarting the game should fix it.
