### ISSUE TITLE
[1.11.2] Builder Safezone broken

### ISSUE THREAD

**Issue by forReason** [ldtteam/minecolonies#452]
### Minecolonies version

version 1.11.2 on latest commit 54fb0c710118074f92401f3881decf869d62cc2d

### Expected behavior

- Builder goes out of the Property, only placing blocks when noone is on the property
- When someone enters the Property, the builder will speak a warning that he cant build while dudes are on there
- Villagers will not enter a property which is in building phase

### Actual behaviour

- Builder will leave the property around 50 Blocks away, which is too much. if this is set because the townhall maybe a value per building would be great
- Villagers will enter the building site and eventually get stuck by builder building blocks on them
- Builder may place blocks on the player when they are on the Building Site
**- Builder may get stuck himself(!) because he starts building the moment he starts to leave the property for safety. this means that he can build onto himself whilst leaving the property**

### Steps to reproduce the problem

1. Build something

**Comment by Raycoms** [comment]
Builder will calculate a maximum of length or width and stand this amount
away from the center. All villagers will notice if something has been
placed on them and run. The player should be smart enough to avoid it.
Builder should also notice and run away fast enough.

2017-01-13 6:44 GMT-02:00 Julian B. <notifications@github.com>:

**Comment by pmardle** [comment]
This is not something I have seen, but can understand that in pretty rare occasions it can happen.
No-one should get stuck in the mod provided buildings as they always have doors and access/egress from the building.

If this does happen on occasion, The recall button is your friend here.

**Comment by forReason** [comment]
workaround with recall button
