### ISSUE TITLE
[1.15.2]Server crashed, very anxious

### ISSUE THREAD

**Issue by EnterFor** [ldtteam/minecolonies#4520]
### Minecolonies version
0.11.790-ALPHA
Version: 1.15.2

unknown aetiology
[crash-2020-03-27_22.34.39-server.txt](https://github.com/ldtteam/minecolonies/files/4394109/crash-2020-03-27_22.34.39-server.txt)
[debug.log](https://github.com/ldtteam/minecolonies/files/4394110/debug.log)

**Comment by EnterFor** [comment]
I removed the wrong chunk and temporarily fixed the problem
It could happen again

**Comment by Raycoms** [comment]
hotfix pushed
