### ISSUE TITLE
[1.15.2]Rendering Issues

### ISSUE THREAD

**Issue by lucsoft** [ldtteam/minecolonies#4522]
### Minecolonies version
Forge (31.1.27)
Minecolonies (0.11.785-BETA)

see everything in every gui

### Actual behaviour

![image](https://user-images.githubusercontent.com/11093382/77800875-06c23a00-7078-11ea-957a-8cbecc79c394.png)

![image](https://user-images.githubusercontent.com/11093382/77800906-16418300-7078-11ea-9b18-e6ca70a5370e.png)

### Steps to reproduce the problem

Im using macos with the lates version of Forge (31.1.27) with everything on default and open a gui

**Comment by someaddons** [comment]
known issue/unknown whats causing it, likely mac messing with drivers. Gonna close this one since theres existing ones for it

**Comment by lucsoft** [comment]
can you give ref me a ticket?

**Comment by someaddons** [comment]
https://github.com/ldtteam/minecolonies/issues/3993
