### ISSUE TITLE
[1.15.2]Console error

### ISSUE THREAD

**Issue by EnterFor** [ldtteam/minecolonies#4524]
### Minecolonies version
minecolonies-0.11.790-ALPHA-universal
Version: 1.15.2

I don't know how to reproduce this error,
The server doesn't see anything unusual
[debug.log](https://github.com/ldtteam/minecolonies/files/4396991/debug.log)

**Comment by Raycoms** [comment]
Can you send us this world?

**Comment by EnterFor** [comment]
Could you elaborate on that?
I just send the world folder or the whole server?
Does the Mod need to be sent together?

**Comment by Raycoms** [comment]
world folder

**Comment by EnterFor** [comment]
I deleted DIM1 and dim-1 folders to reduce the size.
I am uploading, I will edit this message again when finished.
Server player ID: LittlePhilosophy, I suspect his colony caused this, hope this information is helpful to you

Link: https://c-t.work/s/66e52b86b1e143    password:pgy8wd

**Comment by Raycoms** [comment]
I checked colony 5 but there are no huts at all. It seems it was removed?

**Comment by EnterFor** [comment]
> I checked colony 5 but there are no huts at all. It seems it was removed?

Who owns colony 5
What's his ID?
I forgot...

**Comment by Raycoms** [comment]
LittlePhilosophy

**Comment by EnterFor** [comment]
> LittlePhilosophy

It occurred to me that LittlePhilosophy had accidentally destroyed the townhall block, and he couldn't reposition it, so he lived with a player with the ID qiuyizhi

**Comment by Raycoms** [comment]
okay, will check on that colony then =D

**Comment by Raycoms** [comment]
He can just do /mc colony delete: 5 to delete his colony and then craft a new townhall (buildtool center and top and rest planks)

**Comment by EnterFor** [comment]
> He can just do /mc colony delete: 5 to delete his colony and then craft a new townhall (buildtool center and top and rest planks)

I have tried this before, but the command is invalid. Maybe I typed it wrong

**Comment by Raycoms** [comment]
possibly =D

**Comment by EnterFor** [comment]
Are you testing with the server?
Is it possible that this problem will not be repeated by the client?

**Comment by Raycoms** [comment]
It should not, else I'll try to launch a server with it

**Comment by Raycoms** [comment]
This error means there is an issue with some corrupted tileEntity. When I load this with the latest 1.15.2 alpha it does not happen.
Luckily it is not game breaking and I believe it is a normal world corruption issue.
