### ISSUE TITLE
Cant assign fifth field to farmer

### ISSUE THREAD

**Issue by perecnicek** [ldtteam/minecolonies#4525]
### Minecolonies version
Version: minecolonies-0.10.763-BETA-universal

### Expected behavior
- 
I expect that i can assign  field to my farmer but i can just 4 but i have another farmer where it work and i have 5 fields. Difference is in field type for working farmer i have just 5 wheat fields and for that with issue i have 2 potatoes 2 carrots and 1 wheat is that a issue ? because on wiki is not say just that each level is 1 field and i have both huts level 5.
i post here screen
![chyba](https://user-images.githubusercontent.com/46170414/77830408-80b1fc00-7128-11ea-87e2-8e6fb3efccb7.png)

**Comment by Raycoms** [comment]
Can you give us more info?

What happens when you try to assign a 5th field?

Maybe that other field is assigned to another worker?

**Comment by perecnicek** [comment]
> Can you give us more info?
> 
> What happens when you try to assign a 5th field?
> 
> Maybe that other field is assigned to another worker?

I have 12 fields 5 fields are used by working farmer and 4 are used by not working farmer and i have 3 more fields left. I can't click on icon to assign fifth field as you can see on screen it is dark grey.

**Comment by Raycoms** [comment]
Is that a single player world, could you upload that somewhere and send it to me?

**Comment by perecnicek** [comment]
https://mega.nz/#!4qJmGYSI!gIp0k4Ya_z9hx67cbBuPPTfkIDbjs0xoeMBalum3bgY
here you are my world thank you for your help

**Comment by Raycoms** [comment]
Do you have any world generation mod there?

**Comment by perecnicek** [comment]
yes TerraForged-1.15.2-0.0.3

**Comment by Raycoms** [comment]
Kk, I gotta get that one then

**Comment by stkterry** [comment]
I came to post the exact same issue.  I can't seem to assign a 5th wheat field to a level 5 farm.  It's recognized in the GUI but won't assign automatically and can't be assigned manually.  I also happen to be using TerraForged, for what it's worth.

**Comment by Raycoms** [comment]
@perecnicek which colony id was this in?

**Comment by perecnicek** [comment]
colony 2

**Comment by Raycoms** [comment]
I haven't launched it yet because of the othe rmods, but I'm reading the data and the farmer already has 5 assigned to him. It seems there is a fail in the cleanup. Let me check tht out.
