### ISSUE TITLE
Colonists - Items go missing by fulfilling Request

### ISSUE THREAD

**Issue by simonboasaeter** [ldtteam/minecolonies#4530]
Mod version
0.10.715-RELEASE-UNIVERSAL

Issue
My colonists(mainly my builder, not noticed with others) seems to lose his requested items during building. I usually give him everything he needs from the start but items I gave him earlier seems to disappear and he requires them again. I cant find them in his inventory, builder hut inventory or his personal Rack. I have tried to give him some time but the items dont come back. It usually only happens to a single stack of items. And sometimes he wont notice I actually gave him the items, so I have to take them out of his inventory and give it back again. I have noticed it happens mostly when I use the Fulfill button inside the Request tab. It rarely happens if I put the items directly in my builders inventory.

**Comment by perecnicek** [comment]
yes i agree i have this issue too on version minecolonies-0.10.763-BETA-universal

**Comment by simonboasaeter** [comment]
> yes i agree i have this issue too on version minecolonies-0.10.763-BETA-universal

Glad to see that its not only me, its driving me insane haha

**Comment by Raycoms** [comment]
Fixed in a later version
