### ISSUE TITLE
Playing on 1.14.4+ Requieres Structurize right?

### ISSUE THREAD

**Issue by Spid3rdr4gon** [ldtteam/minecolonies#4532]
So I wanted to use this mod with a bunch of other mods and after installing it, I realized sort of that the most recent version requires a version of Structurize that seems to be non existent because i already used the most recent version of Structurize (for 1.14.4)
![asdgjaiosdg](https://user-images.githubusercontent.com/22280742/77851349-0beaca80-71d9-11ea-97cf-832019d54c4d.JPG)

 which is 0.10.193 ALPHA Is there a Version of Structurize i don't know or is this a serious issue?
Any version of Structurize above 0.10.193-ALPHA is for 1.15+ and there is no 0.10.200-ALPHA on their Curse site

**Comment by someaddons** [comment]
https://www.curseforge.com/minecraft/mc-mods/structurize/files/all?page=2
![image](https://user-images.githubusercontent.com/38401808/77851557-1f4a6580-71da-11ea-9e88-4ecbf38c7644.png)
