### ISSUE TITLE
Server keeps crashing

### ISSUE THREAD

**Issue by BalintBorsos** [ldtteam/minecolonies#4534]
Version: V5.2

- When i log onto the server it usualy runs for a couple seconds then crashes. The server ran for at least 5 mins without anyone logging in, however I suspect that's becouse the colony is not loaded as it is some 4000 blocks from spawn.
-Latest.log: [latest.log](https://gist.github.com/BalintBorsos/487f9cf9b6ff64f8d56cc744772de629) 
-Crashlog: [Crashlog](https://gist.github.com/BalintBorsos/56b68b6b2a3e1ee7e5bbd2db451918b1)

**Comment by someaddons** [comment]
its fixed since a long while, you're 150+ versions behind. Update!

**Comment by BalintBorsos** [comment]
It's the current version in the curse launcher I think i wrote the wrong version number but i'm quite sure I'm not 150 versions behind.

**Comment by Nightenom** [comment]
<https://www.curseforge.com/minecraft/mc-mods/minecolonies/files/all>
<https://www.curseforge.com/minecraft/mc-mods/structurize/files/all>

**Comment by BalintBorsos** [comment]
Edit the version is
Minecolonies-1.12.2-0.10.654-BETA-universal.jar
Sorry for the mistake

**Comment by someaddons** [comment]
ye I saw your old version in the logs you posted, the newest atm is minecolonies-1.12.2-0.11.786-ALPHA-universal.jar

**Comment by BalintBorsos** [comment]
Thank you sorry for the trouble it just all seemed so modern. Can't wait to see the new versions.

**Comment by BalintBorsos** [comment]
Are the ones you sent up to date?

**Comment by someaddons** [comment]
yes they are the newest version you can get, just download the most recent minecolonies alpha for 1.12

**Comment by BalintBorsos** [comment]
Thanks again
