### ISSUE TITLE
Miner Not doing It's Job

### ISSUE THREAD

**Issue by WeaponGod243** [ldtteam/minecolonies#4538]
### Minecolonies version: Version used in MC Eternal Lite 1.0

Version: Forge 1.12.2 

### Expected behavior

Mining Properly
- I was expecting the miner to start making the levels as intended but instead...

### Actual behaviour

Ladder Spinning
- The miner will dig out some of the dirt, but on the next day, it will try to go down the ladder, then start spinning on the ladder without mining. After spinning, it will go up the ladder, try to jump the fence, and then repeat the ladder spinning.

### Steps to reproduce the problem

1.  Build Oak Miner Hut
2. Give Miner Materials to mine
3. Wait for the second day it's active
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

**Comment by Raycoms** [comment]
What version are you on?

**Comment by WeaponGod243** [comment]
> What version are you on?

When you say what version, what do you mean by that?

**Comment by WeaponGod243** [comment]
@Raycoms I found it: "0.10.714-RELEASE"

**Comment by Raycoms** [comment]
Can you try the latest alpha?

**Comment by WeaponGod243** [comment]
Not necessarily, as it's part of a modpack. How would you switch the mod version? And would my Town data transfer over?

**Comment by WeaponGod243** [comment]
Actually, I figured out how to update the version, but again, would my data save?

**Comment by Raycoms** [comment]
yes, it is

**Comment by WeaponGod243** [comment]
Okay, thanks

**Comment by Raycoms** [comment]
Did it fix it?

**Comment by WeaponGod243** [comment]
@Raycoms, it ended up working itself out without updating the mod. I don't know why, but it did. Thanks for the help though!(I'll probably end up updating it anyway to stay safe.)
