### ISSUE TITLE
[1.11.2] - Builder will try to clear area again and again

### ISSUE THREAD

**Issue by forReason** [ldtteam/minecolonies#454]
### Minecolonies version

version 1.11.2 on latest commit 54fb0c710118074f92401f3881decf869d62cc2d

### Expected behavior

- Builder clears area and starts to build

### Actual behaviour

- When there is a building with dirt in the blueprint (foresters hut lvl 1 for example) the builder will clear unneccesarly the grassblocks replacing them whith dirt. If he is to slow The grass will start to spread out from the side again. The builder will attempt to clear the grass replacing it with dirt in an infinite, shovelorgy 

### Steps to reproduce the problem

1. Build a Foresters hut on the grass

**Comment by Raycoms** [comment]
If you don't log out and on again he only will clear once.
But for sure we plan on having equally dirt and grass.
