### ISSUE TITLE
Medieval Upgradeable Gate Rotation Issue 

### ISSUE THREAD

**Issue by carlansor** [ldtteam/minecolonies#4540]
### Minecolonies version

Version:  minecolonies-0.11.797-ALPHA-universal.jar

### Expected behavior

Using a build wand, i place down a upgradeable gate medieval schematic, and when upgrade it, it keeps its rotation well.

### Actual behaviour

When placing upgradeable gates and towers, and when triying to upgrade them, the builder marks the deco as it is rotated 90 degrees. So it gets upgraded wrong.

### Steps to reproduce the problem

1. Place a medieval upgradeable gate (not the one included in the mod)
2. Build it to lvl1
3. Try to upgrade it to lvl2
4. A mess is created

NOTE: i think this may be caused by two reasons:
1.- the schematics included in the mod have the deco controller mirroed, and the mod mix up the deco even if they are different files, as they have the same name.
2.- the schematics included in the mod are scanned rotated 90 degrees different from the one included in medieval pack, and when upgrading, the mod thinks its the schem files added in the mod so the rotation gets applied

2nd NOTE:
Ive replaced the schems inside the mod with the ones in the medieval pack and the issue persist. Also i see that the path its different since i link the decos to "schematics/medievaloak/walls/gate" and the ones included in the mod list to "schematics/walls/medievaloak/gate"

**Comment by Raycoms** [comment]
I tested it out, it worked fine for me. Must be something wrong with the scans.
