### ISSUE TITLE
Multiple citizens of same type appearing

### ISSUE THREAD

**Issue by Azur0** [ldtteam/minecolonies#4541]
### Minecolonies version

Version: minecolonies-1.12.2-0.10.772-RELEASE-universal.jar

### Expected behavior

- Bug where multiple of same citizen occur. Other players do not see the multiple citizens. Problem still persists after relogging

### Actual behaviour

- Only 1 citizen should be shown

https://i.imgur.com/4o1a7Hu.png

### Steps to reproduce the problem

1. Build baker
2. Upgrade (bug happened with me while upgrading from Lvl 4 to Lvl 5
3. Multiple citizens of same appear

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

**Comment by Raycoms** [comment]
fixed in latest alpha
