### ISSUE TITLE
Not working in YAMDA dimension 

### ISSUE THREAD

**Issue by RoyalReject** [ldtteam/minecolonies#4546]
Version: minecolonies-0.11.802-BETA-universal.jar 1.15.2

### Expected behavior

Enabled minecolonies to work in other dimensions, go to YAMDA dimension place town hall people spawn place builder, assign to build. Builds it, profit?

- 

### Actual behaviour

Assigns builder, sets to build, just sits there and does not request anything or go to builders hut, even if i recall builder he runs straight to town hall.
- 

### Steps to reproduce the problem

1. Go to YAMDA dimension https://www.curseforge.com/minecraft/mc-mods/yamda
2. place town hall and builder
3. assign builder to build

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: https://pastebin.com/rGx032ND

**Comment by Raycoms** [comment]
It's probably almost night there. Moved to mod compatibility requests
