### ISSUE TITLE
Cast exception

### ISSUE THREAD

**Issue by MaTaMoR** [ldtteam/minecolonies#4547]
Version: 
Minecraft: 1.12.2
Mod version: 1.12.2-0.11.804-RELEASE

Error log:
https://paste.dimdev.org/luxodexiju.mccrash

There error is in this line '[https://github.com/ldtteam/minecolonies/blob/version/1.15/src/main/java/com/minecolonies/coremod/event/EventHandler.java#L364](https://github.com/ldtteam/minecolonies/blob/version/1.15/src/main/java/com/minecolonies/coremod/event/EventHandler.java#L364)' i really tried to compile the mod myself, but i only managed to do it with the latest version, i couldn't do it with the branch 'release/1.12', for some reason the forge dependecy is not working... I'm really bad with gradle only used to work with maven so i'm really lost here. 

Just gotta check if TileEntity is actually instance of 'MobTileEntity' before casting it. I wish i could fix it myself...

**Comment by someaddons** [comment]
fixed in next alpha
