### ISSUE TITLE
Requests disappear from Postbox randomly as if canceled

### ISSUE THREAD

**Issue by justinbey** [ldtteam/minecolonies#4550]
### Minecolonies version

Version: minecolonies-0.11.785-BETA-universal

### Expected behavior

when entering a request for something in the postbox, it would be expected to activate a delivery man or other workers as needed to deliver the requested item to the postbox. 
### Actual behavior

when I type in a block or item in the post box, I specify the amount and hit enter. Sometimes it works, most times it doesn't. The request will show up in the list of requests and sometimes stay there until the item is delivered, but most times it will just randomly disappear with no reason as to why. It acts like I canceled the request. This happens with both big and small orders, and when the selected item is in the warehouse and just needs to be delivered to the postbox, and also when it needs to be crafted by a separate worker and then delivered to the postbox. 

[Postbox Error.zip](https://github.com/ldtteam/minecolonies/files/4418225/Postbox.Error.zip)

### Steps to reproduce the problem

since its random, it's hard to reproduce, but these are the steps that I do in order for it to happen.

1. open postbox
2. select an item and type the amount
3. hit request
4. the time it takes for it to happen varies but it's usually 30 seconds to 1:30. when it does happen you'll open the postbox and see your request gone and the item not delivered. 

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: [latest.log](https://github.com/ldtteam/minecolonies/files/4418258/latest.log)
- crashlog: [crash-2019-10-13_17.19.04-client.txt](https://github.com/ldtteam/minecolonies/files/4418261/crash-2019-10-13_17.19.04-client.txt)
this crash report is old but it's the latest one I have.

**Comment by someaddons** [comment]
upload the logs to https://gist.github.com/ pls

**Comment by Raycoms** [comment]
https://teamcity.minecolonies.com/guestAuth/repository/download/LetSDevTogether_Minecolonies_Branches_Build/36603:id/build/libs/minecolonies-0.11.1861-PERSONAL-universal.jar

please try this fix
