### ISSUE TITLE
Skill system ,,issuse"

### ISSUE THREAD

**Issue by dedziek** [ldtteam/minecolonies#4551]
### Minecolonies version
0.11.807-ALPHA
Version: 1.15.2

###This picture say all
![image](https://user-images.githubusercontent.com/63029526/78204040-d542d780-7498-11ea-852f-e5a9c6581bdd.png)

**Comment by Raycoms** [comment]
What's the issue?

**Comment by Raycoms** [comment]
It seems it converted the past skills nicely to new skills. I don't think there is a problem.
