### ISSUE TITLE
Citizens stay home after destroying pirate ship and kill all pirates

### ISSUE THREAD

**Issue by Rithenar** [ldtteam/minecolonies#4555]
### Minecolonies version

Version: 0.10.772-RELEA

### Expected behavior

Citizens go back to work after Pirate ship is destroyed and all pirates killed
- 

### Actual behaviour

I got the message that a pirate ship arrived. I approached the ship and decided to try something new. I destroyed the ship using the Destruction Gadget from the Building Gadgets mod. I manually destroyed all the rest of the ship and the spawners.  I have a 5X3 wall around my base and I checked to see if any pirates made it through but found none. I checked the town and no pirates were there either.  Still, the citizens will not leave their houses as if they are being attacked.  Once the MC day was over, I got the message the ship sailed away and the citizens came out the next day.

- 

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

**Comment by someaddons** [comment]
when the spawners aren't destroyed by proper block break events(e.g. mining with a pickaxe) you'll have to wait 3 days till it sails away. This is intended and block breaking mods should implement that instead of replacing blockstates.

**Comment by Rithenar** [comment]
I actually destroyed the spawners with a Thermal Dynamics fluxbore since the gadget does not destroy spawners, chests, trapdoors,

**Comment by someaddons** [comment]
ye then that one is at fault

**Comment by Rithenar** [comment]
Gotcha, I will destroy the next ship's spawners with a pickaxe and will report back if the behavior persists.

**Comment by Rithenar** [comment]
Well, I just had another pirate invasion and I had the same results.

1- Destroyed all spawners using pickaxe
2- Manually killed some pirates, turrets finished the rest off
3- Checked all around outside wall of city and no pirates or ladders were found
4- All citizens still in bed
5- No "You successfully defended your colony..." message received

Spawners destroyed
![Pirate Ship](https://user-images.githubusercontent.com/9939332/78277580-5ff7f680-74da-11ea-983c-fe742d865f11.png)

Note the time - 1:00 MC time
![Citizens Sleeping](https://user-images.githubusercontent.com/9939332/78277535-4f478080-74da-11ea-923a-1454d75fb4c2.png)

**Comment by someaddons** [comment]
should get a ship sailed away message at nightfall after killing all spawners

**Comment by Rithenar** [comment]
Oh ok, so the citizens will remain home for the rest of the day until the next evening when you get the sail away message?
