### ISSUE TITLE
Town Hall GUI not showing all professions

### ISSUE THREAD

**Issue by jmed001** [ldtteam/minecolonies#4557]
Any idea why my Delivery guys aren't showing up? And what com.minecolonies.coremod.gui is showing this error?  

Recently I accidently destroyed the Town Hall block but crafted a new one and set it down in the same spot. Not sure if that has anything to do with the error below.

Any advice or help would be great.  Thanks!

Version: 
 1.15.2-forge-31.1.0  //minecolonies-0.11.785-BETA-universal
### Expected behavior

- Would expect that all of the professions be listed 
- 

### Actual behaviour

Image
http://zte.webdrake.com/Image%201.png

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: [latest.log](https://github.com/ldtteam/minecolonies/files/4424173/latest.log)

Edited: Update
- I think when I accidently destroyed the Town Hall block and replaced it with a newly crafted one, the new Town Hall block doesn't recognise that I have a town hall or at least it will not let me upgrade or repair it.  As you can note from the image below, there isn't a upgrade button. Clicking on the Repair button has no affect.

Image:
http://zte.webdrake.com/Image%202.png

**Comment by jmed001** [comment]
Anyone?
Others are having the same issue.

https://forum.minecolonies.com/showthread.php?tid=866

**Comment by EnterFor** [comment]
I had the same problem, but I didn't know what occupation it was, so I didn't report it.
I encountered more than 2 incorrect displays.

**Comment by someaddons** [comment]
When you break a hut block the building is gone. You'll have to rebuild it after breaking the block
