### ISSUE TITLE
[1.14.4] Game crashed after town hall is placed

### ISSUE THREAD

**Issue by ZarameJake** [ldtteam/minecolonies#4558]
**Minecolonies version**
Version: 0.10.715 Release
Using: structurize 0.10.200 Alpha (other versions come up with a need language provider javafml: 30) 
Forge: 28.1.64

**Expected behavior**
Place the town hall then the builders hut. Builder begins to build.

**Actual behaviour**
Once I have the town hall placed it seems to be fine for a short moment. I have enough time to place a builders hut before my game crashes. Once I log back in both are were I placed them, no villagers show up and after a moment it crashes again. I chose the Nordic design. This is in single player.
 
**Crash Log:**
(https://github.com/ldtteam/minecolonies/files/4424803/crash_1.14.4_col.txt)

**Steps to reproduce the problem**
1. Create a new save (superflat)
2. Place supply camp and get town hall/building wand
3. Select Nordic design and place
4. Place Builders hut
5. Crash

**Comment by GamertechAU** [comment]
As it's 1.14.4, likely the same as: https://github.com/ldtteam/minecolonies/issues/4556

Look away from the villagers and keep an eye on the memory Java's using in task manager, it should be pretty stable. Then look at the villagers and usage should start skyrocketing until it crashes.

**Comment by ZarameJake** [comment]
no villagers show up before it crashes

**Comment by someaddons** [comment]
update to the newest structurize for 1.14 (its not 200) clieck view all files :)
