### ISSUE TITLE
[1.15.2]Server crash

### ISSUE THREAD

**Issue by EnterFor** [ldtteam/minecolonies#4559]
### Minecolonies version
790

Version: 
1.15.2
### Expected behavior
I don't know how he happened

[debug.log](https://github.com/ldtteam/minecolonies/files/4424942/debug.log)
[crash-2020-04-02_23.22.56-server.txt](https://github.com/ldtteam/minecolonies/files/4424945/crash-2020-04-02_23.22.56-server.txt)

**Comment by someaddons** [comment]
Please upload the text files to https://gist.github.com/ instead.
