### ISSUE TITLE
build 2291 - Logged into server and builder is Standing at chest ...

### ISSUE THREAD

**Issue by kreezxil** [ldtteam/minecolonies#456]
### Minecolonies version

version 1.11-0.6.2291

### Expected behavior

- Builder tells me what he needs when I approach him

### Actual behaviour

- I think he was smoking a cigarette or on coffee break, couldn't tell, either way he was standing at the chest not saying anything.

### Steps to reproduce the problem

1. Install mod on a dedicated server
1. start builder building
1. logout before the builder finishes
1. reconnect and builder will probably be standing around not saying anything
   1. if your builder is talking to you, then consider i'm using Persistent Bits Chunk Loader
   1. install a chunk loader so that your builder keeps going after you log out and finds his way to the chest
   1. since you are gone from the server he has no one with which to talk and think that is what happened here
   1. you (that is me in this case) thinks that he is broken but he has already talked to you and is waiting for you to supply something
   1. this is where the npc should respond when I enter his personal space. In fact based on your code for no spam, i think it should only work in personal space and each time I cross through it. Let's say the personal space of the builders should be 20 blocks, that way when I am within 20 blocks of a builder, they will tell me things according to the no spam rule, however, if I leave their personal space and reenter it, they should tell me things all over again as if they encountered me the first time, I think that would provide an excellent workaround.
      1. conversely, just add the current item needed to the npcs info graphic

**Comment by Raycoms** [comment]
We're going to add something which adds the currently required item to his
gui.

2017-01-13 18:36 GMT-02:00 kreezxil <notifications@github.com>:

**Comment by kreezxil** [comment]
cool

**Comment by xavierh** [comment]
kreezil, I noticed that the builder hold the item it need in his hand (even if it does not have it in his inventory)

**Comment by forReason** [comment]
related to issue #457

**Comment by Raycoms** [comment]
same as issue #457
