### ISSUE TITLE
1.15.2 delivery person

### ISSUE THREAD

**Issue by Hugekase** [ldtteam/minecolonies#4560]
### Minecolonies version

Version: 
1.15.2; just not enough mods 2
### Expected behavior

Delivery person delivering items
- 
Delivery person should be taking items from the warehouse and delivering them to the respected areas
### Actual behaviour

- 
Person goes and picks up items from the locations, does not deliver. Only delivered once, delivers fine on other person's settlement.

### Steps to reproduce the problem

1. Make request
2. Put items in warehouse
3. Person runs around shitless without doing their job
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

**Comment by someaddons** [comment]
Please fill in the correct minecolonies version, and attach the latest.log you had during the error to gist.

**Comment by Raycoms** [comment]
Please upgrade to the latest alpha. We made some improvements to do this.
