### ISSUE TITLE
Metal/Stone Smelters go back and forth when given smeltable ore instead of smelting it

### ISSUE THREAD

**Issue by pa1nki113r** [ldtteam/minecolonies#4561]
### Minecolonies version

Version: minecolonies-0.10.771-RELEASE-universal

### Expected behavior

After the smelter is given a smeltable ore, they should put it in the designated furnace. They seem to put the fuel correctly in the furnace.

### Actual behaviour

The smelter citizen runs back and forth from the hut block to the furnace when given a smeltable ore such as iron, and does not place it in the respective furnace, however they place fuel in it correctly. I've rebuilt the hut, fired/rerehired/restarted the worker and same behavior with different citizens.

### Steps to reproduce the problem

1. Built a Smelter/Stone Smelter Hut
2. Assign a citizen
3. Give fuel to citizen
4. Watch citizen place fuel and request ore
5. Give ore to citizen 
6. Observe citizen run back and forth from the hut block to the furnace but not place ore in it

**Comment by ztmart** [comment]
I was the player having the issue with the Stone Smelter and they weren't pacing back and forth they were just having issues putting cobblestone in the furnace. I had to take it out of their inventory and put it in the furnace. When it was done cooking they would take it out of the furnace and put it in the building inventory. But unlike when the sawmill finishes a requested item and triggers a deliveryman to come pick it up they just put it in their inventory and wait for the delivery man to eventually pick it up by clearing their building storage and take it to the warehouse. The builders request then sits there uncompleted until I cancel the request and they request again and the stone is now in the warehouse. It just breaks the idea of automating stone smelting. 

Back to the Metal Smelter, I had built the metal smelters hut and also had the smelter just pace back and forth between the building block and the furnace. Once I decide to put the ore in the furnace for them everything else works. They take it out of the furnace to dupe and store it.

Also the delivery men are not recognizing the request for ore from the Metal smelters. I had iron ore in my warehouse and I cancelled the smelters request for ore and they still didn't recognize it in there and asked me for it. Also another way that breaks the idea of automation of a colony. 

I noticed something else in the town hall. When I look at the screen that shows all the professions and if they are filled. That seems buggy as well, I am missing some of the professions in my colony and the Smelters profession shows 1/null. I currently have 16 professions plus 1 for unemployed and no kids currently, but the screen only shows 12 professions plus unemployed. 

![MC Bug Pic](https://user-images.githubusercontent.com/13373820/78378010-ff2df400-7595-11ea-937e-e6ea7d87a792.PNG)

**Comment by someaddons** [comment]
try the newest minecolonies version

**Comment by pa1nki113r** [comment]
On curse forge, would this be the 11.802 BETA or the 11.807 ALPHA? For Minecraft 1.15.2

Also thank you for the prompt reply. Just trying to ensure if switching minecolony versions on my server will be stable.

**Comment by Raycoms** [comment]
Both Beta and alpha should have this fixed.

**Comment by Raycoms** [comment]
and yes, you shouldn't have problems upgrading from those.

**Comment by pa1nki113r** [comment]
You can close the issue, it seems fixed.
