### ISSUE TITLE
Lumberjack exception

### ISSUE THREAD

**Issue by kd5crs** [ldtteam/minecolonies#4562]
### Minecolonies version

Version: minecolonies-0.11.802-BETA-universal

Lumberjack threw several AI exceptions, see attached log file. I like the in-game error message, makes knowing when to report much easier. Game did not crash, and other citizens kept going.

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: 
[latest.log](https://github.com/ldtteam/minecolonies/files/4425842/latest.log)

- crashlog:

**Comment by someaddons** [comment]
Please post the log using https://gist.github.com/

**Comment by kd5crs** [comment]
https://gist.github.com/kd5crs/761e0fd94f1e27cbfd7284210dce2b4d
