### ISSUE TITLE
Builder Issue

### ISSUE THREAD

**Issue by Kyzoku** [ldtteam/minecolonies#4564]
### Minecolonies version
Version: 
minecolonies-1.12.2-0.11.804-RELEASE-universal
As a part of MC Eternal v1.3.5

### Expected behavior
Builder should walk back and forth to job site normally.

### Actual behaviour
Builder walks back and forth from job site at a very low rate of speed.
https://streamable.com/q6eag9

### Steps to reproduce the problem
Haven't the slightest clue on how to reproduce.  The builder was working fine for a while.

### Logs: Latest.log and crashlog at https://gist.github.com/
latest.log:
https://gist.github.com/Kyzoku/99a919d27b2d99e7909495a9a78236af

**Comment by Raycoms** [comment]
He does this while he is scanning the building site quite often.

**Comment by Kyzoku** [comment]
This has been going on now for about 4 hours (not game time)

Edit:
I've tried cancelling build, firing and rehiring, but he still remains very slow compared to others.

**Comment by Kyzoku** [comment]
Alright I used the /mc citizens respawn command and he is chugging along again as he should.
