### ISSUE TITLE
[Feature] [QoL] Builder request everything missing at Job start

### ISSUE THREAD

**Issue by ToMe25** [ldtteam/minecolonies#4571]
I suggest changing the Builder to request all missing items at the start of his new project,
so the Production and/or Deliveryman don't have to always start working once he needs that item,
but can instead start before that,
so some items are already finished and delivered once he needs them,
meaning he can work with a little less breaks,
and also the Player knows earlier what items he actually needs to get,
and what not because for example the Warehouse already contains it.

**Comment by Raycoms** [comment]
already in the planned feature list.

**Comment by ToMe25** [comment]
sorry, i didn't see it.
