### ISSUE TITLE
[Question] Beds, Glass, Glass Panes, Bows, and Arrows?

### ISSUE THREAD

**Issue by Timeslice42** [ldtteam/minecolonies#4572]
(Using minecolonies-1.12.2-0.11.804-RELEASE-universal.jar)

Which buildings/workers are meant to be crafting these? Right now I have the Cook making a few of these because they don't seem to have any crafting restrictions, but it just feels wrong.

I was expecting there to be a Fletcher for bows and arrows, for the Smelter to handle glass, and for the ~~carpenter~~ miller to handle beds. That still leaves out glass panes, but it seems overkill to have a Glassblower building/worker for just panes...

**Comment by Raycoms** [comment]
Those will be future workers yes.

**Comment by Raycoms** [comment]
Please refer to the issue of requested and planned features.

**Comment by Timeslice42** [comment]
Nope, they're still not listed there.

**Comment by ravenbuilder934** [comment]
Also fishing rods and torches. Right now, there's not a dedicated worker for any of these.

**Comment by Raycoms** [comment]
In due time =D
