### ISSUE TITLE
[1.15.2]Server crash, compatibility issues?

### ISSUE THREAD

**Issue by EnterFor** [ldtteam/minecolonies#4573]
[crash-2020-04-04_20.36.32-server.txt](https://github.com/ldtteam/minecolonies/files/4431327/crash-2020-04-04_20.36.32-server.txt)

I don't know whose problem it is,
Mine and slash also appeared

**Comment by someaddons** [comment]
follow the template and upload the log on gist.

**Comment by EnterFor** [comment]
Then forget it
