### ISSUE TITLE
Removing a mod while a colonist is requesting an item from it causes crash on world load

### ISSUE THREAD

**Issue by SeriousCreeper** [ldtteam/minecolonies#4574]
### Minecolonies version

Version: minecolonies-1.12.2-0.11.806-ALPHA-universal

### Expected behavior

- If a colonist is requesting an item from a mod that has been removed it should ignore that tool (remove it from the request list?) but instead causes a crash.

### Actual behaviour

- I was using Adventure's Toolbox for my tools in my modpack, but because some players keep running into an issue where the colonist don't recognize them properly, i decided to remove that mod. However, if there was a colonist requesting an item from it in an existing world (in my case i taught someone how to craft the axe heads from adventures toolbox), the game crashes on startup, making it impossible to continue with that world. 

### Steps to reproduce the problem

1. Download Minecolony + adventures toolbox
2. Teach someone the recipe to make the tool parts
3. Have them request said tool parts
4. Uninstall Adventures Toolbox and reload the world

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: https://gist.github.com/Kiyaku/13a6a61f5879ef1f1af9eb02df5a00cc
- crashlog: https://gist.github.com/Kiyaku/04f1f07cba37d0a00faff5c98b121bbe

**Comment by marchermans** [comment]
There is nothing we can do.
Forge and FML clearly warn you that they are missing registry entries. And as such if the system tries to then load them from disk. This exception might occur.

I have considered it not throwing this exception but that would require a massive rework of the Rs. This might be considered for the future but as of right now I do not think we can easily fix this. I have added it to the list of things to consider for rs upgrades though. 

Sorry that we are not able to help you. 
Orion

**Comment by Raycoms** [comment]
I dug deeper in the code again and that is really almost impossible to avoid. The problem is not the recipe but actually an open request. When removing a mod like that, the best thing is to clean up those things first.
