### ISSUE TITLE
Crash on citizen death

### ISSUE THREAD

**Issue by kd5crs** [ldtteam/minecolonies#4575]
### Minecolonies version

Version: minecolonies-0.11.808-ALPHA-universal

This crash happened right as a colonist was killed by an arrow. I saw the death message and then the crash happened right after. 

### Logs: Latest.log and crashlog at https://gist.github.com/

- crashlog and latest.log: https://gist.github.com/kd5crs/549511df9475e8dc5a108aea06c5525d

**Comment by marchermans** [comment]
@Raycoms I am guessing we are doing this somehow twice?

**Comment by Raycoms** [comment]
Yes, we are, I'm fixing it atm
