### ISSUE TITLE
Builder issues when upgrading townhall

### ISSUE THREAD

**Issue by NinjaMedik** [ldtteam/minecolonies#4577]
### Minecolonies version

Version: 1.14.4

### Expected behavior

Want to upgrade Mesa townhall2 to townhall3. 

### Actual behaviour

Builder, after being given appropriate materials/tools, walks over to build site, “loses” certain materials (ie chests disappear from inventory and are not placed), then comes back to hut and requests additional materials. If the replacement materials are given, builder repeats the same process (walks to build-> dumps chests somewhere -> returns).

Since this is a server (I can ask for op if needed), i replicated this issue in super flat single player (level 3 Mesa builder, level 2 Mesa townhall) except when prompted to upgrade here the builder does not ask for anything and simply does nothing. The build order is logged and the chat notification saying construction has begun by builder is present.

Im fairly new to the mod, but I didn’t have an issue like this when upgrading or building any other building, including the townhall1 to townhall2 upgrade. Needless to say, I’m pretty confused.

### Steps to reproduce the problem

1. build level 2 Mesa townhall and level 3 Mesa builder hut. Ask builder to upgrade to Mesa townhall3
2.  Builder eats materials/does nothing
3.  Sadness happens
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

**Comment by Raycoms** [comment]
Yeah, we're aware that there are some issues in 1.14. However, we had to stop supporting it because we're supporting 1.15 and 1.12 already.

**Comment by NinjaMedik** [comment]
okay, but.... are you implying its an issue thats been fixed in 1.15? so you have seen it before?

**Comment by Raycoms** [comment]
yes, its fixed in 1.15 and never existed in 1.12

**Comment by NinjaMedik** [comment]
I udnerstand. Is there anything i can do about this on 1.14 or am I out of luck?

**Comment by Raycoms** [comment]
Make sure the worker has never more than 1 stack of a resource. That should improve the situation.
