### ISSUE TITLE
[Feature] Add IRequestable for Entities in RS

### ISSUE THREAD

**Issue by Asherslab** [ldtteam/minecolonies#4579]
Simple enough, for now there'd be no resolvers other than the player, but this would allow an intuitive way to display that an animal is needed in herder huts and etc. And in the future if we provide a worker that actually "finds" animals or otherwise this would be even more useful.

**Comment by Raycoms** [comment]
zzz, that should be a part of the #3803 issue and not its own issue =P

**Comment by Asherslab** [comment]
@Raycoms how does this have anything todo with #3803 ?

**Comment by Raycoms** [comment]
wrong issue, I meant the issue combing the other ones =D
