### ISSUE TITLE
Crash Minecolonies Knights

### ISSUE THREAD

**Issue by xlCyanz** [ldtteam/minecolonies#4580]
### Minecolonies version

Version: minecolonies-0.10.771-RELEASE-universal

### Expected behavior

- Have my guards follow me around to gibberish.

### Actual behaviour

- Well, I was going to mobilize my troops from the headquarters for a walk at night to make a fool of myself but suddenly the game crashed and I put my sword guards in closed division and they followed me. But when I got bright and they went somewhere else and didn't follow me just poof crash. I went back inside to see if it was just a crash. Sometimes it happens but I didn't crash again when I went inside and I showed up inside the headquarters but before the crash I wasn't inside. The crash log mentions a citizen and his name was left below.

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog: https://gist.github.com/xlCyanz/565f62137418d3e421daa9f406f671bb

**Comment by Asherslab** [comment]
fixed in 
#4447
update to a more recent version of MineColonies
