### ISSUE TITLE
Huts Missing Models

### ISSUE THREAD

**Issue by WenXin20** [ldtteam/minecolonies#4581]
### Minecolonies version
Version: 0.11.813-Alpha

### Expected behavior
- Huts should display their model

### Actual behaviour
- In the inventory, several huts are completely invisible, and when placed, display a missing purple & black texture. I suspect this is caused by Optifine & Optiforged when a model is using the Multi-layer type.
- Any hut containing a chest in its model has an incorrect texture mapping, I believe this is because the minecraft chest texture mapping changed slightly in 1.15.2. (The inside texture of the chest is on top, etc.)
- Models missing textures include the Farm, Lumberjack's Hut, Warehouse, Shepherd's Hut, Swineherder's Hut, Chicken Herder's Hut, Archery, Combat Academy, Stone Smeltery, Flower Shop, University, & Hospital. 

![2020-04-05_21 32 33](https://user-images.githubusercontent.com/12000593/78518787-0d8f3200-7787-11ea-89e1-5effe0ad2b68.png)

### Steps to reproduce the problem
1. Install Optifine
1. Open the Minecolonies tab
2. Place an invisible hut
4. ... Profit

**Comment by Asherslab** [comment]
This is optifine's fault, they are not currently compatible with forge properly

**Comment by WenXin20** [comment]
Though the chest texture isn't Optifine's fault
