### ISSUE TITLE
Schoolhouse for Children

### ISSUE THREAD

**Issue by Exeden** [ldtteam/minecolonies#4582]
I believe that children should all be attending school on a regular basis.  This feature would create a new building called Schoolhouse where children would funnel into each morning to learn, and 1 Teacher will be assigned to run the class.  

A typical day includes:
1. Sit and learn
2. Lunch
3. Recess
4. Sit and learn

By attending school, the children will grow faster into adults.

**Comment by Raycoms** [comment]
yeah, that's what I am working on atm =D
