### ISSUE TITLE
Fisherman swim

### ISSUE THREAD

**Issue by NoNikName** [ldtteam/minecolonies#4584]
### Minecolonies version

Version: 1.15.2

### Expected behavior

- 

### Actual behaviour

- 

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

**Comment by NoNikName** [comment]
Sorry for my English but I have a problem. My fisherman dont fish. He just swim in water. I try rebuild his hut but its dont working.
![2020-04-06_19 01 38](https://user-images.githubusercontent.com/63251863/78580811-067a2980-7844-11ea-8d34-74df92f6480f.png)

**Comment by Raycoms** [comment]
Can you try placing a bit more land around his hut?

**Comment by NoNikName** [comment]
Yes but its still dont working

**Comment by Raycoms** [comment]
weird, did you try recalling and firing/hiring him?

**Comment by NoNikName** [comment]
Yes. Its works but 1 min. After his go swim again

**Comment by Raycoms** [comment]
can you send me your world?

**Comment by NoNikName** [comment]
Yes, but its moded

**Comment by Raycoms** [comment]
any world gen mods?

**Comment by NoNikName** [comment]
If i understand what you say-yes

**Comment by NoNikName** [comment]
Sorry, its some Hard to me

**Comment by Raycoms** [comment]
can you send me the mod list and the world then?

**Comment by NoNikName** [comment]
Yes, 1 min

**Comment by Raycoms** [comment]
No stress, I'll only be able to check on it tomorrow

**Comment by NoNikName** [comment]
Oh, ok, i'm just tired today. I'll send it today and you can check tomorrow if you can.

**Comment by NoNikName** [comment]
How can I send it for you ?

**Comment by Raycoms** [comment]
you can upload it on drive for example and link it here

**Comment by NoNikName** [comment]
[Map.zip](https://github.com/ldtteam/minecolonies/files/4441151/Map.zip)
I thing its work. See tomorrow.

**Comment by Raycoms** [comment]
great

**Comment by Raycoms** [comment]
This zip doesn't work. something went wrong zipping it I believe

**Comment by NoNikName** [comment]
And what I need to do now

**Comment by Raycoms** [comment]
redo it.

**Comment by NoNikName** [comment]
https://drive.google.com/file/d/1aoF43m3w0jdX2ZO26wHW2gtxapnFV2CZ/view?usp=sharing               
Ok. Does it work ?

**Comment by Raycoms** [comment]
yes

**Comment by Raycoms** [comment]
I checked on it, I agree that the fisherman sometimes falls int he water and swims around, but his is because navigating in the world is difficult. They may fall in the water meanwhile. But 90% of the time the fisherman was working just fine for me and producing plenty of fish.
