### ISSUE TITLE
Miner (nordic) won't get into action

### ISSUE THREAD

**Issue by VPelt** [ldtteam/minecolonies#4586]
### Minecolonies version

Version: 

minecolonies-1.12.2-0.10.772-RELEASE-universal.jar
--

### Expected behavior
Start mining

### Actual behaviour

My miner (noric style) won't do anything

### Steps to reproduce the problem

1. Build a noridic miner lvl 1 at hight > 48
2. Give him cobbelstone slabs
3. Give him cobbelstone stairs
4. Give him cobbelstone
5. Give him torches
6. Give him signs
7. Give him (stone) pickaxe and shovel
8. Give him ladders
9. Give hiim cobblestone walls (P.S. nordic style would do well with spruce wood fences instead?)

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

**Comment by Raycoms** [comment]
Did he request anything, is there any log?

**Comment by VPelt** [comment]
No he just stands in the corner of his room, recall worker oesn't unstuck him

update: server restart does

**Comment by Raycoms** [comment]
is he now working fine?

**Comment by VPelt** [comment]
yep

**Comment by Raycoms** [comment]
Can you please reopen when it happens again and attach your latest.log then so we can see if there was something bothering him?
