### ISSUE TITLE
Huts with Chests Display Incorrectly

### ISSUE THREAD

**Issue by WenXin20** [ldtteam/minecolonies#4587]
### Minecolonies version
Version: 0.11.813-Alpha

### Expected behavior
- Huts with Chests should look like a chest

### Actual behaviour
- Any hut containing a chest in its model has an incorrect texture mapping, I believe this is because the minecraft chest texture mapping changed slightly in 1.15.2. (The inside texture of the chest is on top, etc.)

### Steps to reproduce the problem
1. Open the Minecolonies tab
2. Place the warehouse
4. ... Profit

**Comment by lunadragnstar** [comment]
Most warehouses use racks not chests

**Comment by WenXin20** [comment]
I meant the hut models, not the chests in the buildings.

**Comment by lunadragnstar** [comment]
Oh, odds are if the huts aren't displaying properly, you are using optifine. There is issues with optifine and our mod or forge or something that causes it not to display our huts properly.

**Comment by WenXin20** [comment]
This still happens without Optifine. I was using the development version to fix some display properties, and thought that was just a bug with the development version, but I later found out that Minecraft had changed the texture file for chests slightly in 1.15.2.

**Comment by Raycoms** [comment]
@WenXin20 would it possible for you to make a PR to fix that?

**Comment by WenXin20** [comment]
If I find the time to fix them, then yes, I could submit a pr

**Comment by Raycoms** [comment]
Awesome
