### ISSUE TITLE
Hospital hut disappears upon placing

### ISSUE THREAD

**Issue by JalterPlays** [ldtteam/minecolonies#4589]
### Minecolonies version

Version: minecolonies-0.11.794-BETA-universal

### Expected behavior

Expexted to place the hospital hut  
### Actual behaviour

Block disappears from inventory, and doesn't place. It is not burried.

### Steps to reproduce the problem

1. Place hospital building guide

4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

**Comment by lunadragnstar** [comment]
fixed
