### ISSUE TITLE
[1.15.2] GUI missing items

### ISSUE THREAD

**Issue by b52src** [ldtteam/minecolonies#4590]
### Minecolonies version

Version: 
Minecraft 1.15.2
modpack: [Valhelsia 2](https://www.curseforge.com/minecraft/modpacks/valhelsia-2)
minecolonies-0.11.810-BETA-universal

### Expected behavior

-   that build menus would display needed resources and that text would not be invisible.

### Actual behaviour

-  Missing text on Build Menus to show required resources for the build and also on some other pages in the GUI such as the worker list in the town hall.screen shots here: https://imgur.com/a/vQNTdnL

### Steps to reproduce the problem

1.  look at one of the GUIs  noted above.

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: [https://gist.github.com/b52src/c68a190bbdeb16ecb8cd0f10631130fe](https://gist.github.com/b52src/c68a190bbdeb16ecb8cd0f10631130fe)
- crashlog:

**Comment by Raycoms** [comment]
Fixed in latest alpha
