### ISSUE TITLE
Placeholder block

### ISSUE THREAD

**Issue by lunadragnstar** [ldtteam/minecolonies#4591]
I've been testing the placeholder block, I'm not sure what is going on with it, but I created a warehouse with deliveryman hut underneath it. I placed the placeholder sign in the right area and set it for the deliveryman hut, I had to rotate the deliveryman hut so it is facing the right way. When the builder builds the warehouse, it places the hut in the right orientation but the hut itself is facing the wrong way according to the hut block placement.

I re-setup the placeholder block so when I replaced it with the deliveryman hut, it placed the hut facing the right way. When the builder built the warehouse, it placed the deliveryman hut block facing the right way, but when building the deliveryman hut portion, the hut was rotated wrong.

Deliveryman hut block placement with placeholder block 
![image](https://user-images.githubusercontent.com/29446488/78633083-a2b92600-786e-11ea-87cd-c736302029f4.png)

Deliveryman hut as the builder builds it 
![image](https://user-images.githubusercontent.com/29446488/78633154-d300c480-786e-11ea-8927-c2818d9d941e.png)

Deliveryman hut as it should be built
![image](https://user-images.githubusercontent.com/29446488/78633210-fe83af00-786e-11ea-8331-94889c2fcb29.png)

**Comment by marchermans** [comment]
@Raycoms I do not think this is working: https://github.com/ldtteam/minecolonies/blob/476411910ca4c0f6c6418c00971e534f29c63326/src/main/java/com/minecolonies/coremod/placementhandlers/MinecoloniesPlacementHandlers.java#L275

**Comment by Raycoms** [comment]
fixed
