### ISSUE TITLE
mod version update 1.14.4 to 1.15.2 and All colony data was lost

### ISSUE THREAD

**Issue by Sogang123** [ldtteam/minecolonies#4593]
### Minecolonies version

Version: minecolonies-0.11.810-BETA-universal.jar

### Expected behavior

i was update my server 1.14.4 to 1.15.2 

I thought of better colonies.

### Actual behaviour

All colony data was lost. All residents were also gone.
![2020-04-07_20 30 46](https://user-images.githubusercontent.com/63293854/78664627-5d990080-790f-11ea-8ff0-494ebe41ffc4.png)

1. mod version update 1.14.4 to 1.15.2
2. and 1.15.2 server open
3. All gone

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:
https://gist.github.com/Sogang123/b8a3d8a31410a1ebb8846418d332d264

**Comment by Raycoms** [comment]
yeah, you can't update from 1.14 to 1.15 without losing stuff. Forge doesn't support this either.

**Comment by Sogang123** [comment]
Should I reset the world?

**Comment by Raycoms** [comment]
Yes, you have to start new.
