### ISSUE TITLE
Suspected conflict mod

### ISSUE THREAD

**Issue by Rithenar** [ldtteam/minecolonies#4594]
### Minecolonies version 

Version: 1.12.2-0.11.804-RELEASE

### Expected behavior

Allow spawners to be broken
- 
I am not able to break spawners in the Betweenlands. VanillaFix is avoiding the crash so I am ataching the launcher and server log. This happens in both, Survival and Creative on both Single Player and Server. Both point at Minecolonies as the suspected mod
### Actual behaviour

     Try to give as much detail as possible here to help us properly understand the issue. -->
Try to break spawners in Betweenlands but instead I get a crash error. The spawner dissapears for a brief moment and then re-appears

### Steps to reproduce the problem

1. Locate a spawner in Betweenlands
2. Break with pick
3. Get error message
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: https://gist.github.com/Rithenar/aa0a0e7b58acac67040956eb442eb8bd
-latest server log: https://gist.github.com/Rithenar/ad4dfe90727cd99a17b592b7ba3ecd32
- crashlog:https://gist.github.com/Rithenar/ddece940784ee7fb4ef3db44135be844

**Comment by someaddons** [comment]
already fixed in the latest alpha
