### ISSUE TITLE
[Feature] more compostable stuff

### ISSUE THREAD

**Issue by ToMe25** [ldtteam/minecolonies#4595]
The composter can already compost alot of stuff the Vanilla composter can't handle, i would however suggest adding support for a few more things, some of which the Vanilla composter can compost and some more, that kinda just feel missing, as why should for example some seeds not be compostable?
Here the list of things i would suggest to make compostable:

- Pumpkin Seeds
- Melon Seeds
- Pumpkins?
- Carved Pumpkins?
- Grass
- Tall Grass
- Kelp?
- All 6 types of Leaves
- Sea Grass?
- Cactus
- Sugar Cane
- Vines
- Cocoa Beans?
- Fern
- Large Fern
- Sunflower
- Lilac
- Peony
- Lily Pad
- Sea Pickle?
- Wheat
- Brown Mushroom Block
- Red Mushroom Block
- Mushroom Stem
- Cake?
- Rabbits Foot?
- Fermented Spider Eye

The items on the list with a question mark are the ones i am not sure about, but felt like i had to include them for different reasons.

**Comment by someaddons** [comment]
you can add additional composter items with the config

**Comment by ToMe25** [comment]
I feel like atleast the other tall flowers should be compostable by default tho.
