### ISSUE TITLE
Black Banner not being accepted

### ISSUE THREAD

**Issue by Puinthos** [ldtteam/minecolonies#4597]
Playing MCEternal, trying to upgrade the Town Hall to level 4, Nordic style, when the builder asks for 4 black banners i tried giving him the vanilla ones in the pack and he doesn't seem to accept that they are the correct ones. a couple items requests before that he had asked for a cyan banner and accepted that one.

not 100% what version of the mod the pack has installed, but i'm playing on the most current update for the pack.

**Comment by Raycoms** [comment]
Shouldn't be a problem in the nwest version anymore.

**Comment by Charismara** [comment]
Black Banners not being accepted working in version minecolonies-1.12.2-0.11.811-BETA (which is the newest 1.12.2 version on curse)

**Comment by BlackJac** [comment]
Yellow Banner on Medieval Oak Town Hall Lvl 2 still doesn't work properly in version 1.12.2-0.11.811-BETA.

**Comment by ghost** [comment]
ok Just wait and i will get the fix.

**Comment by drakray** [comment]
Is there any news for this fix for 1.12.2?, we just encountered it on my server :/
Thanks :)

EDIT: using MineColonies-1.12.2-0.11.841-ALPHA-universal, Medieval Oak Town Hall lvl 2

**Comment by SeeTwoDev** [comment]
Same issue with the latest MCEternal version. Black Banner for tier 4 town hall.

**Comment by Chinthor** [comment]
Also having this issue /w latest Alpha release, minecraft version 1.12.2. Upgrading the Nordic style town hall, requiring [Black Banner]. The Builder's Hut recognizes that I have them in my inventory, I can use the arrow button to provide them, but they never leave my inventory and the interface pops back to asking me to provide them again. My builder won't accept them from me. No fulfill button.

Might this be a repeat of the Yellow Banner issue where the schematic is demanding a particular color pattern, but cannot communicate that to the player? In some views, the black banner wanted looks like it has some kind of symbol on it. In the builder's request menu, it is a solid magenta square.

**Comment by ravenbuilder934** [comment]
1.12.2 is not receiving support or fixes any more.

**Comment by Butzelmann** [comment]
There's a workaround in the Minecolonies forum that works for me.  https://forum.minecolonies.com/showthread.php?tid=3915

**Comment by Jen7NZ** [comment]
This is still an issue in the latest release. The workaround link does not work, and can't find a fix anywhere else. Please help, I'd like to upgrade my building.

**Comment by Raycoms** [comment]
Make a new issue please if it's a problem in 1.18+ with a reproduction. Have you asked on discord already?

**Comment by Jen7NZ** [comment]
The latest release was for 1.12.2 5 days ago...

**Comment by Talyda** [comment]
1.12 isn't supported at all any more for Minecolonies

**Comment by Raycoms** [comment]
Latest release for 1.12 you mean, well, yeah, that doesn't work. You can use the search function on discord for info

**Comment by Jen7NZ** [comment]
It was updated just 5 days ago

**Comment by Talyda** [comment]
Are you somehow on the wrong github? For the wrong mod?

**Comment by Jen7NZ** [comment]
Minecolonies, 1.12.2. 4 black banners not being accepted by rhe builder for Town Hall, level 4 Nordic style. The last update to this mod was only a few days ago.

**Comment by uecasm** [comment]
The last update to 1.12 was two months ago, not "a few days", and it was a special case.  It does not mean 1.12 is supported, and it isn't.  If you want bugfixes, upgrade to a supported version; otherwise you're on your own.

**Comment by Jen7NZ** [comment]
So my builder is just stuck in limbo cause he can't finish the townhall and I can't get level 5.
