### ISSUE TITLE
New colonists are only female.

### ISSUE THREAD

**Issue by Sipiri** [ldtteam/minecolonies#4598]
# Minecolonies version
Version: 0.11.817-ALPHA

### Expected behavior
Upon slaughtering my  entire community, one should expect 50/50 distribution of immigrants across sex.

### Actual behaviour
New villagers are exclusively female. Sample size: 50.

### Steps to reproduce the problem

Cause an unfortunate incident which kills your starting 4 citizens, then wait.

### Logs: Latest.log and crashlog at https://gist.github.com/
none

**Comment by someaddons** [comment]
1. is female
2. is male
3. is female
4. is male

you gotta wait and not just keep killing the first
