### ISSUE TITLE
[Feature Request] builder unlimited resources, by build level?

### ISSUE THREAD

**Issue by 0xebjc** [ldtteam/minecolonies#4599]
Version: 
MC 1.12.2

It would be nice to find a healthy balance for the unlimited builder resources, I wish there was a config setting to enable unlimited builder resources to be enabled or disabled by building level.  

Example:
#Builder_Unlimited_Resource_Level: {0..5}

if it's set to 0, builder never has unlimited resources,
if it's set to 1, builder has unlimited resources for all level 1 building levels
if it's set to 2, builder has unlimited resources for all level 2 building levels and below,
if it's set to 5, builder has unlimited resources for all level

**Comment by Raycoms** [comment]
added to requested list
