### ISSUE TITLE
Server Bug Report

### ISSUE THREAD

**Issue by IncubusMango** [ldtteam/minecolonies#460]
### Minecolonies version

version 1.11-0.6.2291

### Expected behavior

- Having Fun

### Actual behaviour

- Crash

### Steps to reproduce the problem

I really dont know it was the Server:
[18:17:35] [Server thread/INFO] [minecolonies/]: Colony 2 - new AbstractBuilding for class com.minecolonies.coremod.blocks.BlockHutBuilder at BlockPos{x=-126, y=70, z=195}
[18:17:36] [Server thread/INFO] [minecolonies/]: Starting AI job com.minecolonies.coremod.job.Builder
[18:17:48] [Server thread/INFO] [minecolonies/]: ForgeHook not in sync with EfficientTool for Block{minecraft:tallgrass} and 1xtile.air@0
Please report to MineColonies with this text to add support!

More on File

[fml-server-3-log.txt](https://github.com/Minecolonies/minecolonies/files/706140/fml-server-3-log.txt)

**Comment by Raycoms** [comment]
Can you send us more of the logs. Can't find anything in that log which may
have lead to the server crash.
The ForgeHook not in sync is more for debug purposes and shouldn't crash
anything.

2017-01-14 16:34 GMT-02:00 IncubusMango <notifications@github.com>:

**Comment by IncubusMango** [comment]
[fml-server-1.txt](https://github.com/Minecolonies/minecolonies/files/706146/fml-server-1.txt)
[fml-server-2.txt](https://github.com/Minecolonies/minecolonies/files/706145/fml-server-2.txt)

I call it a crash but i can start the server but no one is able to join after that happend ^^

**Comment by Raycoms** [comment]
It seems like mojang has some problems with the authentication servers atm.
It seems like all servers have the problem with not being able to join very well.
Can't find any exception thrown by our mod in there.
Can you attach the fml latest?

**Comment by IncubusMango** [comment]
[fml-server-latest.txt](https://github.com/Minecolonies/minecolonies/files/706150/fml-server-latest.txt)
[latest.txt](https://github.com/Minecolonies/minecolonies/files/706149/latest.txt)

**Comment by Raycoms** [comment]
yes, not our fault, sorry. all servers atm experience this.
