### ISSUE TITLE
Dark oak barracks tower rotation

### ISSUE THREAD

**Issue by gerb82** [ldtteam/minecolonies#4600]
### Minecolonies version
Version: 0.11.813-ALPHA

### Expected behavior
When placing the barracks in different rotations, the towers will rotate accordingly

### Actual behaviour
The towers placed by the barracks appear to have the wrong orientation, building into the barracks itself, instead of where they're supposed to build.
Attempting to manually place the towers in the same block but properly rotated cause them to not build, asking for the barracks to be upgraded first.

![image](https://user-images.githubusercontent.com/13512001/78746919-c2d10e00-7970-11ea-8249-0ca23bf15d9b.png)

### Steps to reproduce the problem

1. Place barracks so that the leather armor stands are facing north
2. Build the first level
3. Look at the tower placed by the barracks
4. ... Profit?

- latest.log: <script src="https://gist.github.com/gerb82/9ec52c94f0ca1934a56974b8276a294e.js"></script>
- crashlog: N/A

**Comment by gerb82** [comment]
Furthermore, i just noticed that the armor stands themselves also don't rotate, meaning that if the leather ones are facing north, all armor stands will look inwards, but if they're towards the south, then they will look outwards, and the same goes for the rest of the stands (might be a slightly different issue, but still thought i'd mention it)

**Comment by Raycoms** [comment]
Add to the schematic issue list please.
