### ISSUE TITLE
cheats disabled after some time in singleplayer

### ISSUE THREAD

**Issue by ToMe25** [ldtteam/minecolonies#4603]
Version: 1.15.2:0.11.810

### Expected behavior
I would expect that cheats keep being enabled even if i play for more than a few hours.

### Actual behaviour
The worlds i created with cheats enabled have cheats disabled after some time.
I had this happen to multiple worlds, atleast one in 1.14.4 and one in 1.15.2.

### Steps to reproduce the problem
1. create a bew single player world with cheats enabled
2. play for some time idk how long exactly, my guess is like 20 hours.
3. try a command and see cheats being disabled

### Logs: Latest.log and crashlog at https://gist.github.com/
as there is no crash and i have alot of logs over the around 25 hours, i can't really provide a log as i don't know for sure at what point cheats got disabled.

**Comment by Raycoms** [comment]
Should probably report this to mojang or forge =)

**Comment by ToMe25** [comment]
but i never had it without Minecolonies, and in like half of my worlds with Minecolonies, so i expect it to be a Minecolonies bug...

**Comment by Raycoms** [comment]
No, we don't do anything in this regard

**Comment by ToMe25** [comment]
i revisited the worlds, and figured something out that might cause it, i will search some of the logs and create a new Issue for the other problem that i think might also cause this :)
