### ISSUE TITLE
1.15.2 claim issue

### ISSUE THREAD

**Issue by perecnicek** [ldtteam/minecolonies#4604]
### Minecolonies version

Version: minecolonies-0.11.817-ALPHA-universal

### Expected behavior

I set static mod for claim 12 chunks radius and i expect when i place the town hall i would claim that radius.

### Actual behaviour

When i place townhall claim is just 6 chunks on each sides

### Steps to reproduce the problem

Play this game version and place town hall

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

**Comment by someaddons** [comment]
townhallpaddingchunk is the initial claim size, could you upload your config to gist?
