### ISSUE TITLE
Combat Training

### ISSUE THREAD

**Issue by Imothep80** [ldtteam/minecolonies#4606]
### Minecolonies version

Version: 0.11.802-BETA

### Expected behavior

Combat Academy Level 3 - The second worker say that i give you this informations.

### Actual behaviour

- I have no idea. But i think the Workers should Training together.

### Steps to reproduce the problem

No idea how to reproduce this.

1. 
2. 
3. 
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
https://gist.github.com/Imothep80/bd0fc5141267b5880ccd4f1de2a245dd
- crashlog:
no crash

**Comment by Raycoms** [comment]
Can you try the latest alpha?

**Comment by Imothep80** [comment]
Alpha was not longer aviable on curseforge. I try and use minecolonies-0.11.810-BETA-universal.
The Problem is fixed with this Version. Thank you.
If you have no further concerns, you can close that.
