### ISSUE TITLE
Other players can't access GUI in multiplayer

### ISSUE THREAD

**Issue by DriesVE** [ldtteam/minecolonies#4607]
### Minecolonies version

Version: minecolonies-0.11.817-ALPHA

### Expected behavior

- 
When right clicking the town hall or other block the GUI needs to open.
### Actual behaviour

- 
The GUI only opens for the player that placed the block.
If the town hall is destroyed and another player places it, that player is the only one that can open the GUI.
All players where made officers and the officer permissions where all enabled. 

### Steps to reproduce the problem

1.  Player 1 places the town hall
2.  Player 2 tries to open the town hall GUI
3.  Player 2 won't get the GUI
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: https://gist.github.com/DriesVE/4297199ea3860c8cd07498fcf5c70bca
- crashlog:

**Comment by Raycoms** [comment]
Are you in a LAN game?

**Comment by DriesVE** [comment]
No, this is not a LAN game.
The other players are connected over the internet.
