### ISSUE TITLE
2 issues that go side by side

### ISSUE THREAD

**Issue by shivachirr** [ldtteam/minecolonies#461]
### Minecolonies version

curse 1.10.2.-0.6.2305

Issue #1

### Expected behavior

Firing a worker from lets say being a guard to be a builder and works fine

### Actual behavior

hiring a worker from another job to builder dose not work and builder ai seems not active even tho the console reads it was started

### Steps to reproduce the problem

1. fire somone from any job
2. hire to builder

Issue #2
### Expected behavior

after 2 mins(config changed) or default time should spawn new colonist 

### Actual behavior

Never dose suspect damaged townhall building but townhall still reads a limit of 10 colonist and im down to 5 from zombies and attempts to fix things by killing them

### Steps to reproduce the problem

should be obvious how to reproduce

**Comment by forReason** [comment]
please open one issue per single issue.
I would say issue 1 correlates with #457 please approve that.

the max builders need time to refresh. try to build another settlers hut to update.

**Comment by shivachirr** [comment]
No it dose not correlate becuse that realtes to freezes due to builders using resources this is hiring the from like guard or farmer to buidler. and i have one builder and it took 6-7 hours of gameplay till the builder started to work  just now actully becuse he started pinging me for needed rescources
