### ISSUE TITLE
Minecolonies Citizen walk problem

### ISSUE THREAD

**Issue by benkiller96** [ldtteam/minecolonies#4611]
minecolonies-1.12.2-0.11.804-RELEASE-universal.jar

Version: 1.12.2

### Expected behavior
Citizen work and walk normal

- 
Bug with MDXLib and alien vs predator mod

### Actual behaviour
The citizens stops and start to move very slow without walk animation, they stay that way until you punch them or recall them. It happens a lot with all the citizens. I already make the tests and the problem is with MDXLib and alien vs predator mod. It also happened with the latest builds.

### Steps to reproduce the problem

1. Install the mentioned mods
2. Create a world 
3. Create a colonie
4. ... All citizens works normal till they stop

**Comment by Raycoms** [comment]
I believe that those mods then alter something of our citizens, can you please report this in #4510 and also report this to the MDXLib creator?
