### ISSUE TITLE
Builder only gets next block delivered

### ISSUE THREAD

**Issue by kd5crs** [ldtteam/minecolonies#4612]
### Minecolonies version

Version: minecolonies-0.11.808-ALPHA-universal

### Expected behavior

- Builder gets as much of the resources required for the build as possible, then builds the building.

### Actual behaviour

- Works well until the Delivery Hut and Warehouse are built. After that, 

1. the Builder requests a block
2. the Delivery Man delivers the block
3. the Builder runs to the worksite
4. the Builder places as many blocks of the schematic as they have, which if the next block is different is just one
5. the Builder runs back to the Builder's Hut
6. the Delivery Man delivers the next block
7. Repeat until finished

In other words, the request system for the Builder seems to be working great, but the end result is, unfortunately, slow and boring. The Builder spends much more time running back to the hut for a single block than actually building, even though all of the required material is in the Warehouse. This happens even with a level 5 Delivery Man when there are a lot of single blocks in a row in a structure.

My suggestion: 

1. Change the Delivery Man to not deliver to the Builder's Hut.
2. Change the Builder to pick up from the Warehouse directly, to the limit of the Builder inventory, in the order the blocks are needed.
3. If the item isn't in the warehouse, the Builder requests it from the player as normal.
4. Other Delivery Man behavior stays the same.

I think the Delivery Man is working great except for the Builder, and unfortunately that means the Builder part of the game gets less fun once a Warehouse is built. Before the Warehouse (and DMan) you can pre-load the Builder with everything and builds happen really fast. Even if you want to move stuff manually to the Builder's Hut, the DMan takes it out back to the warehouse (plus in that case, might as well not build a Warehouse/DMan at all.) In my opinion, I don't think having the Builder pick up from the Warehouse compromises the vision of the request system, it just removes what I'm guessing is an unintended bottleneck. 

Thanks for the consideration.

**Comment by Raycoms** [comment]
Yeah that is already in the list of planned features on the github here too =)

**Comment by kd5crs** [comment]
Excellent!
