### ISSUE TITLE
datagenerators.0.1.35 Structurize 0.10.297 changes in buid.graddle

### ISSUE THREAD

**Issue by lexustec** [ldtteam/minecolonies#4617]
Update of build.properties 
and
build.graddle
needed

Opening Project in IntelliJ with graddle ends in an error 404 for datagenerators.0.1.33.jar

Bump Version of Structurize from 288 to 297 inside build.properties
Structurize needs datagenerator.
Version 288 requests datagenerator 0.1.33
ends in an 404 error
Version 297 requests datagenerator 0.1.35 which is available.

and

update dependencies in build.graddle from 0.1.34 to 0.1.35

**Comment by Nightenom** [comment]
we know about it, update at your side locally, deps versions are changed during common prs
