### ISSUE TITLE
Syntax Error in Log

### ISSUE THREAD

**Issue by kwerin** [ldtteam/minecolonies#4618]
### Minecolonies version

Version: minecolonies-0.11.821-BETA-universal.jar

### Expected behavior

- No errors in log

### Actual behaviour

- Error in the log - please see linked latest.log file. Starts at "[org.antlr.v4.runtime.ConsoleErrorListener:syntaxError:38]: line 36:0 token recognition error at: 'S'" and the errors spell "SpawnerNBT", lines 4-12.

### Steps to reproduce the problem

1. Start up Minecraft with Forge, Minecolonies, and Structurize
2. Check the latest.log
(Error does not occur with just Structurize)

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: https://gist.github.com/kwerin/9b8f04a3dfa7556b1086f894498fda7b
- crashlog:

**Comment by marchermans** [comment]
This is not an issue caused by Minecolonies or Structurize.
Minecolonies is not even loaded at that point and FML is still parsing information.

As such please report this either to Forge.
