### ISSUE TITLE
NullPointerException on raids when running server on Linux

### ISSUE THREAD

**Issue by Silwing** [ldtteam/minecolonies#4619]
### Minecolonies version

Version:  1.12.2-0.11.804-RELEASE

### Expected behavior

- Raiders spawn successfully on a server running Linux

### Actual behaviour

- No raiders spawn and the log shows a NullPointerException trying to test whether Pirates spawn.

### Steps to reproduce the problem

1. Install a Minecraft server with Forge and Minecolonies on a server running Linux
2. Run command mc raid-tonight
3. Wait until nightfall 
4. No raiders spawn and server log has NPE

The issue is that in the Minecraft 1.12 latest release the schematics/Ships directory has a capital S, whereas the PirateEventUtils has the path specified as /ships/ with lowercase s. Since Linux is case sensitive in its paths it doesn't find the schematics.
It looks like it is already fixed by changing the schematics/ships directory to lowercase s in the 1.15 branch.

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

**Comment by someaddons** [comment]
this is fixed in the newest already
