### ISSUE TITLE
Colony no longer spawns replacement colonist

### ISSUE THREAD

**Issue by shivachirr** [ldtteam/minecolonies#462]
### Expected behavior

after 2 mins(config changed) or default time should spawn new colonist

### Actual behavior

Never dose suspect damaged town hall building but town hall still reads a limit of 10 colonist and im down to 5 from zombies and attempts to fix things by killing them

### Steps to reproduce the problem

should be obvious how to reproduce but ill epxlain

1. have a colony with town hall 4
2. lose a colonist and wait

Note: now i have set the colonist limit in the config to 1 thinking that only effects what you start with because i wanted to make the citizen huts feel a bit more useful and needed so you atleast start with one for a starter builder

**Comment by Raycoms** [comment]
Did I understand correctly. You changed the config to 10 colonists and they
started dieing and no new colonist spawned?
Did you set the dayNightCycle off?

2017-01-14 21:47 GMT-02:00 shivachirr <notifications@github.com>:

**Comment by shivachirr** [comment]
no the config is set to 1 and i have 2 lvl 5 citizen huts i and my colonist were dieing due to zombies and me due to crossfire via my bow. and no i dont have day night cycle set to off but i do have a mod called realistic time so the sun is link to my computer clock and is 24 hours but the fact i played a good chunk the day before the sun set and no replacements

**Comment by Raycoms** [comment]
yeah that mod for sure causes that. if the time passes slowly they also
spawn extremely slowly.

2017-01-14 23:22 GMT-02:00 shivachirr <notifications@github.com>:

**Comment by shivachirr** [comment]
intresting i disable it and it worked im kinda surpsied that its link to the day night cycle time and not the tick rate of the game its self becuse its only mod i have that is having issues with the time mod and everything else with the mod works at normal rate

**Comment by Raycoms** [comment]
Atm we can't change it but we will probably eventually.
It would require some mayor code changes.
