### ISSUE TITLE
sorting

### ISSUE THREAD

**Issue by VPelt** [ldtteam/minecolonies#4621]
### Minecolonies version
minecolonies-1.12.2-0.10.772-RELEASE-universal.jar

Version: 

### Expected behavior
Woord pieces sorted together

### Actual behaviour
Sorting by modpack seems to work fine
However, stone, wool and wood logs seem to be sorted into the same rack

Doors, fences and stairs seem to go in complexly different racks

### Steps to reproduce the problem

1. Put many items in the warehouse
2. press sort

- Rack : Oak door, spruce fence gate, redstone
- Rack : Oak fence, Spruce fence, Oak saplings, Spruce saplings, Ladders
- Rack: Cobblestone, Oak wood, Oak wood planks, Gravel

I would expect sawmil related items to be sorted seperately from stonemason related items

**Comment by Raycoms** [comment]
We use creative tabs to sort things. Unfortunately there are not much other things we can use as decent similarity measures on that scale I believe.
