### ISSUE TITLE
Crash when opening world 

### ISSUE THREAD

**Issue by carlansor** [ldtteam/minecolonies#4625]
### Minecolonies version

Version: 
minecolonies-0.11.817-ALPHA-universal

##Actual Behavior

The world just doesnt load, and it crash whenever i try to open it. Ill add the crashlog below.

### Logs: Latest.log and crashlog at https://gist.github.com/

- crashlog: https://gist.github.com/carlansor/1af36b5cc19bdf37f9679b72c1771644

**Comment by marchermans** [comment]
Interesting. We will need your world since it looks like you somehow have a corrupt world, with it missing output types.

**Comment by carlansor** [comment]
Deleting the minecolonies folder and the playerdata inside the world folder allowed me to open the world again. Gladly it was a creative world so lost colony info doesnt matter, ill think ill close this
