### ISSUE TITLE
[Feature] [$5] Dynamic Colonist Skins [$5]

### ISSUE THREAD

**Issue by Megistus** [ldtteam/minecolonies#463]
### Minecolonies version

minecolonies-universal-1.10.2-0.6.2305

I am a texture artist and have created a number of extra colonist textures, but after looking at the code, and if I am understanding it correctly, is hard-coded to accept only a certain number of textures ... i.e three male and three female colonist textures.

I would ask that you adjust the code so that it looks into the texture folder and determine how many textures are available to determine the size of array so that, say, SettlerMale4.png is a valid texture. 

Thanks!

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=40978182)](https://www.bountysource.com/issues/40978182-suggestion-dynamic-array-for-colonist-skins?utm_source=40978182&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by Raycoms** [comment]
You can create a pull request with the textures you created and I can
adjust the code to accept them (for the time being).

2017-01-15 14:27 GMT-02:00 Megistus <notifications@github.com>:

**Comment by Megistus** [comment]
Hard coding new numbers just for this is not necessary. If you have time in the future to make it dynamic, it would be appreciated.

**Comment by xavierh** [comment]
Megistrus, I guess you want to be able to dump a bunch of skins in a folder and have minecolonies to pick them up at run time ?

This is not as simple as this. If you dump the skins on the server, someone would have to implement the client side i.e. download the skins from the server.

At the moment it is easy because the skins are in the jar i.e. available on client and server side

(For what I understand)

**Comment by Raycoms** [comment]
Megistus,

If you have some nice texture we could add them to the mod officially
that's what I was thinking about.

2017-01-16 13:22 GMT-02:00 xavierh <notifications@github.com>:

**Comment by Megistus** [comment]
Xavierh ... yes, that would be a correct assessment as to what I am requesting. I did not consider the SMP aspect. Hmm ... well, if it can be done...

Raycoms, the skins I have developed at the moment are specifically for Glimmar's Steampunk. However, that isn't to say that I could not develop more skins for 16x so that I could implement the ones for my pack. Give me a bit, and I will come up with something that should blend nicely with what you already have.

Thanks!

**Comment by AndrewTru** [comment]
My bad didn't mean to close the issue and refer to this one, I support the idea as an extension idea for Issue #937 , Not that I am taking the idea from the issuing party but the two seem to mesh.

**Comment by AndrewTru** [comment]
@Megistus 
Due to a call by the devs, your issue/idea has over lapped mine.
The team call is to forget my issue #937 and work on this one.
Let's hope your idea here helps my issue as well.

**Comment by Raycoms** [comment]
Closed in favor of joint issue.
