### ISSUE TITLE
Builder won't build

### ISSUE THREAD

**Issue by Prince-Zodiac** [ldtteam/minecolonies#4630]
Version: 1.12.2

### Expected behavior

Builder building his hut and other things

### Actual behaviour

Builder just stands at his hut, not doing anything. At night her goes to the town hall marker like all the other citizens and in the morning he goes back to his hut and just stands there. The hut is partially built, around 25 - 50% is done, but now he just doesn't do anything. No request for materials or tools, nothing. Also hiring more builders they do nothing from the start, not requesting stuff they need to build their homes or anything.

### Steps to reproduce the problem

1. Tell him to build his hut.
2. He builds till around 25 - 50% done
3. Stops and does nothing.

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

**Comment by Raycoms** [comment]
anything in the log?

**Comment by Raycoms** [comment]
No answer
