### ISSUE TITLE
Citizens invisible

### ISSUE THREAD

**Issue by TheKrowi** [ldtteam/minecolonies#4633]
So today I've started my game and all my citizens are visible. I've went to the nether and now all but the builder are invisible. Recalling to the town hall does not fix this. I've got a builder, fisherman, woodcutter and unemployed citizen. Going out and in the game again fixes this issue (so there is a fix if you want to call is that).

### Minecolonies version

Version: 1.12.2-0.11.804-RELEASE-universal
Modpack: MC Eternal

### Expected behavior

- Citizens should be visible

### Actual behaviour

- Citizens are invisible

### Steps to reproduce the problem

1. Start game with active colony (citizens are visible)
2. Go to the nether and back
3. Citizens are invisible

**Comment by Raycoms** [comment]
Entities going invisible is a vanilla issue unfortunately. does this happen in a new world too?

**Comment by TheKrowi** [comment]
This was a pretty new world. I would have to test and see what happens in an actual new world which I did not. I've been to different dimensions lately like the Nether and the Beneath and citizens going invisible didn't happen again. So not sure what caused this. If you say it's a vanilla bug, not much you can do about it :)

**Comment by someaddons** [comment]
afaik  its optifine causing it

**Comment by Raycoms** [comment]
There is a vanilla bug that can cause entities go invisible under certain conditions. If you got optifine you got your villain right there already =D

Either way, I'm glad it didn't happen again so I can close this.
