### ISSUE TITLE
Builders losing materials when placing in inventory (1.15.2-Forge-31.1.36)

### ISSUE THREAD

**Issue by pa1nki113r** [ldtteam/minecolonies#4635]
### Minecolonies version

Version: minecolonies-0.11.821-BETA-universal

### Expected behavior

I place a required item in the builders inventory, they should keep the item for building.

I either retrieve or craft the item for the builder to use, place it in his inventory, the hut inventory, or fulfill his request, and they should hold on to the item for building.

### Actual behaviour

Upon placing items in the builder's inventory, some or all of the items disappear, and are not recoverable, which is very frustrating. Multiple people on my server including me have come across this issue and have complained.

### Steps to reproduce the problem

1. Build a builders hut
2. When they require building materials, fulfill their requests and/or place required materials in hut storage
3. Builder will suddenly make the same request again and the required items will be removed for no reason
4. Frustration ensues after the last hour of gathering resources was seemingly wasted :(

Hope that's descriptive enough to help!

**Comment by Raycoms** [comment]
A few questions:
a) Does this happen on all resources or mainly on doors, glasspanes, flowers, torches (blocks that may drop when the builder replaces the block under them).

b) Does he re-request it but page 2 of the builder hut still detects it as in the hut?

**Comment by pa1nki113r** [comment]
A) It's done it for different types of colored whool, blacksmith tables, oak fences, and other blocks. So I'd say all resources as far as I've seen

B) I've checked this and can confirm that they are no longer detected when in the hut's inventory. When I place required items using the page two method, it says they are there, but when I come back to the builder when he has the red request icon above his head, he's requiring the items I've given him and they're no longer in the hut's inventory. I can also confirm this happens without a delivery man being created yet, as this happened to one of my friends when he tried to start his own colony.

**Comment by Raycoms** [comment]
Any way to reproduce this yet?

**Comment by pa1nki113r** [comment]
Results have been inconsistent, it seems to happen when I gather most of the required items and fulfill the requests via the second page of the builder hut, that's what seems to cause this bug. 

Example:

I'm trying to upgrade the builder hut to level 4. I see he needs materials Light Blue Wool, Pink Wool, a blacksmith table (among others). I craft said items, and place them in the hut's inventory via second page UI. The items are placed and I see them being recorded in the counts for required materials, but a minute or two later (without a delivery man visiting the hut) the materials vanish and I'm required to place them in the inventory again.

**Comment by Raycoms** [comment]
Are you sure that those items did not stay behind in your inventory because the hut inventory was too full for them to fit in?

**Comment by pa1nki113r** [comment]
Yes there was enough room in the hut inventory, Those items were not returned to my inventory, however. Noticed this happened once we switched to beta builds instead of the release version on our server. The only other thing I could think of is a server desync or ticking issue, but I don't have the expertise on what goes on behind the scenes, nor do I think that's the cause behind the problem.

Seems to only happen on our private server. I can paste our config if you want to check for any discrepancies. I recall increasing the builder's build rate to be slightly faster from the default value, could that be causing it??

**Comment by pa1nki113r** [comment]
`
#All configuration items related to the core gameplay
[gameplay]
	#AI Update rate, increase to improve performance. [Default: 1]
	#Range: 0 ~ 100
	updaterate = 1
	#Automatically fix orphaned chunks which were caused by chunk loading and saving issues. [Default: false]
	fixorphanedchunks = false
	#Max citizens in one colony. [Default: 50]
	#Range: 4 ~ 500
	maxcitizenpercolony = 100
	#Amount of blocks the builder checks (to decrease lag by builder). [Default: 1000]
	#Range: 1000 ~ 100000
	maxblockscheckedbybuilder = 1000
	#How common diseases are. 1 = Very common, 100 = extremely rare. [Default: 5]
	#Range: 1 ~ 100
	diseasemodifier = 40
	#Should in development features be enabled (might be buggy). [Default: false]
	enableindevelopmentfeatures = false
	#Should builder place construction tape? [Default: true]
	builderplaceconstructiontape = true
	#Should builder and miner build without resources? (this also turns off what they produce). [Default: false]
	builderinfiniteresources = false
	#Whether to generate supply ship/camps in chests occasionally [Default: true]
	generatesupplyloot = false
	#Should players be allowed to abandon their colony to create a new one easily? [Default: false]
	allowinfinitecolonies = true
	#Child growth modifier, default on avg they take about 60min to grow (at 1.0x modifier). Setting to 5 = 5x as fast. [Default: 1]
	#Range: 1.0 ~ 100.0
	growthmodifier = 1.0
	#Should citizen name tags be rendered? [Default: true]
	alwaysrendernametag = true
	#Should players be able to place an infinite amount of supplychests? [Default: false]
	allowinfinitesupplychests = false
	#Average citizen respawn interval (in seconds). [Default: 60]
	#Range: 10 ~ 600
	citizenrespawninterval = 60
	#Should colonies in other dimensions be allowed? [Default: false]
	allowotherdimcolonies = false
	#Should workers work during the rain? [Default: false]
	workersalwaysworkinrain = false
	#Should player made schematics be allowed [Default: false]
	allowplayerschematics = false
	#Quantity of dirt per Compost filling. [Default: 1]
	#Range: 0 ~ 100
	dirtfromcompost = 1
	#Chat frequency of worker requests. [Default: 30]
	#Range: 1 ~ 100
	chatfrequency = 30
	#Food consumption modifier (Min: 1.0). [Default: 1.0]
	#Range: 0.0 ~ 100.0
	foodmodifier = 1.0
	#Delay modifier to mine a block (Decreasing it, decreases the delay) [Default: 500]
	#Range: 1 ~ 10000
	blockminingdelaymodifier = 250
	#Chance to get a sponge drop for the fisherman starting at level 4. [Default: 0.1]
	#Range: 0.0 ~ 100.0
	fisherspongechance = 0.1
	#Should Players be sent entering/leaving colony notifications? [Default: true]
	sendenteringleavingmessages = true
	#Should players be allowed to change names? -1 for false, 0 for specific groups, 1 for true. [Default: 1]
	#Range: -1 ~ 1
	allowglobalnamechanges = 1
	#Delay after each block placement (Increasing it, increases the delay) [Default: 15]
	#Range: 1 ~ 500
	builderbuildblockdelay = 10
	#Amount of initial citizens. [Default: 4]
	#Range: 1 ~ 10
	initialcitizenamount = 8
	#If the builder should be slower underground or as fast as anywhere else. [Default: true]
	restrictbuilderunderground = false
	#Should there be at max 1 warehouse per colony?. [Default: true]
	limittoonewarehousepercolony = true
	#Should player get one guidebook on first join to a new world? [Default: true]
	playergetsguidebookonfirstjoin = true
	#Chance to get a lucky block in percent. [Default: 1]
	#Range: 0 ~ 100
	luckyblockchance = 1
	#Suggest build tool usage when trying to place a building without build tool. [Default: true]
	suggestbuildtoolplacement = true
	#Should special holiday content be displayed? [Default: true]
	holidayfeatures = true
	#The minimum level a townhall has to have to allow teleportation to other colonies. [Default: 3]
	#Range: 0 ~ 5
	minthleveltoteleport = 3
	#Disable citizen voices. [Default: false]
	disablecitizenvoices = false

#All configurations related to the Minecolonies commands
[commands]
	#Should the player be allowed to use the '/mc colony teleport' command? [Default: false]
	canplayerusecolonytpcommand = false
	#Which level counts as op level on the server. [Default: 3]
	#Range: 0 ~ 3
	oplevelforserver = 3
	#Sets weither or not Colony structures are destroyed automatically. [Default: true]
	autodestroycolonyblocks = true
	#Should the player be allowed to use the '/mc rtp' command? [Default: true]
	canplayerusertpcommand = true
	#minecolonies.config.numberofattemptsforsafetp.comment
	#Range: 1 ~ 10
	numberofattemptsforsafetp = 4
	#Should the player be allowed to use the '/mc colony delete' command? [Default: true]
	canplayerusedeletecolonycommand = true
	#Sets the amount of hours until a colony will be deleted after not seeing it's mayor, set to zero to disable. [Default: 0]
	#Range: 168 ~ 10000
	autodeletecoloniesinhours = 168
	#Should the player be allowed to use the '/mc colony info' command? [Default: true]
	canplayeruseshowcolonyinfocommand = true
	#Should the player be allowed to use the '/mc colony addOfficer' command? [Default: true]
	canplayeruseaddofficercommand = true
	#Time until a next teleport can be executed (in seconds). [Default: 120]
	#Range: 30 ~ 99999
	teleportbuffer = 120
	#Should the player be allowed to use the '/mc home' command? [Default: true]
	canplayerusehometpcommand = false
	#Can Player Teleport to allied colonies? [Default:true]
	canplayeruseallytownhallteleport = false
	#Should the player be allowed to use the '/mc citizens kill' command? [Default: true]
	canplayerusekillcitizenscommand = true

#minecolonies.config.claims.comment
[claims]
	#The minimum distance between colony townhalls. [Default: 5]
	#Range: 1 ~ 200
	mintownhallpadding = 8
	#Should the min/max distance from spawn also affect colony placement? [Default: false]
	restrictcolonyplacement = false
	#minecolonies.config.officersreceiveadvancements.comment
	officersreceiveadvancements = false
	#Max distance from world spawn. [Default: 8000]
	#Range: 1000 ~ 100000
	maxdistancefromworldspawn = 8000
	#Should the colony have a fixed radius or should it be dynamic. [Default: false]
	enabledynamiccolonysizes = true
	#Maximum claim range for a townhall. [Default: 20]
	#Range: 1 ~ 50
	workingrangetownhallchunks = 30
	#Initial townhall claim size [Default: 5]
	#Range: 1 ~ 200
	townhallpaddingchunk = 5
	#Should players be allowed to build their colonies over existing villages? [Default: false]
	protectvillages = false
	#Min distance from world spawn. [Default: 512]
	#Range: 1 ~ 1000
	mindistancefromworldspawn = 512

#All configuration items related to the combat elements of Minecolonies
[combat]
	#The minimum number of nights between raids. [Default: 1]
	#Range: 1 ~ 30
	minimumnumberofnightsbetweenraids = 6
	#Days until the pirate ships despawn again. [Default: 3]
	#Range: 1 ~ 10
	daysuntilpirateshipsdespawn = 1
	#minecolonies.config.citizencallforhelp.comment
	citizencallforhelp = true
	#Whether or not to barbarians can break, scale, bridge obstacles. [Default: true]
	dobarbariansbreakthroughwalls = true
	#Should Mobs attack citizens? [Default: false
	mobattackcitizens = false
	#The max size of a barbarian horde. [Default: 20]
	#Range: 6 ~ 40
	maxBarbarianSize = 30
	#Health multiplier for all Guards. [Default: 1.0]
	#Range: 0.1 ~ 5.0
	guardhealthmult = 5.0
	#minecolonies.config.barbarianhordedifficulty.comment
	#Range: 0 ~ 10
	barbarianhordedifficulty = 5
	#The average amount of nights between raids. [Default: 3]
	#Range: 1 ~ 10
	averagenumberofnightsbetweenraids = 8
	#Damage multiplier for Knight Guards. [Default: 1.0]
	#Range: 0.1 ~ 5.0
	knightdamagemult = 5.0
	#Turn on Minecolonies pvp mode, attention (colonies can be destroyed and can be griefed under certain conditions). [Default: false]
	pvp_mode = false
	#minecolonies.config.shouldraiderbreakdoors.comment
	shouldraiderbreakdoors = true
	#Max Y level for Barbarians to spawn. [Default: 200]
	#Range: 1 ~ 500
	maxyforbarbarians = 200
	#Whether or not to spawn barbarians. [Default: true]
	dobarbariansspawn = true
	#Damage multiplier for Ranger Guards. [Default: 1.0]
	#Range: 0.1 ~ 5.0
	rangerdamagemult = 5.0
	#The spawn size of a barbarian horde. [Default: 5]
	#Range: 1 ~ 10
	spawnbarbariansize = 5
	#Should Guard Rangers benefit from Power/Smite/Bane of Arthropods enchants? [Default: true]
	rangerenchants = true

#All permission configuration options
[permissions]
	#Blocks players should be able to final ForgeConfigSpec.IntValueeract with in any colony (Ex vending machines)
	freetointeractblocks = ["dirt", "0 0 0"]
	#Should the colony protection be enabled? [Default: true]
	enablecolonyprotection = false
	#Independent from the colony protection, should explosions be turned off? [Default: true]
	turnoffexplosionsincolonies = false
	#Seconds between permission messages. [Default: 30]
	#Range: 1 ~ 1000
	secondsBetweenPermissionMessages = 30
	#minecolonies.config.specialpermgroup.comment
	specialpermgroup = ["_Raycoms_"]

#All configuration related to mod compatibility
[compatibility]
	#Experience multiplier of the enchanter (how much more experience does he get from a citizen than he drains) [Default: 2.0]
	#Range: 1.0 ~ 10.0
	enchanterexperiencemultiplier = 2.0
	#minecolonies.config.extraores.comment
	extraOres = ["minestuck:ore_cruxite", "minestuck:ore_uranium"]
	#The items and item-tags that the florist can plant.
	listofplantables = ["minecraft:sunflower", "minecraft:lilac", "minecraft:rose_bush", "minecraft:peony", "minecraft:tall_grass", "minecraft:large_fern", "minecraft:fern", "minecraft:sugar_cane", "minecraft:cactus", "small_flowers"]
	#minecolonies.config.siftableblocks.comment
	siftableblocks = ["minecraft:dirt", "minecraft:sand", "minecraft:gravel", "minecraft:soul_sand"]
	#All diseases citizens can get. The name, how common it is, and all ingredients to cure it.
	diseases = ["Influenza,100,minecraft:carrot,minecraft:potato", "Measles,10,minecraft:dandelion,minecraft:kelp,minecraft:poppy", "Smallpox,1,minecraft:honeycomb,minecraft:golden_apple"]
	#minecolonies.config.configliststudyitems.comment
	configliststudyitems = ["minecraft:paper;400;100"]
	#The possible enchantments for the enchanter
	enchantments = ["1,minecraft:aqua_affinity,1,50", "1,minecraft:bane_of_arthropods,1,50", "1,minecraft:blast_protection,1,50", "1,minecraft:depth_strider,1,50", "1,minecraft:feather_falling,1,50", "1,minecraft:fire_aspect,1,50", "1,minecraft:fire_protection,1,50", "1,minecraft:flame,1,50", "1,minecraft:frost_walker,1,50", "1,minecraft:knockback,1,50", "1,minecraft:looting,1,50", "1,minecraft:power,1,50", "1,minecraft:projectile_protection,1,50", "1,minecraft:protection,1,50", "1,minecraft:punch,1,50", "1,minecraft:respiration,1,50", "1,minecraft:sharpness,1,50", "1,minecraft:smite,1,50", "1,minecraft:sweeping,1,50", "1,minecraft:unbreaking,1,50", "2,minecraft:aqua_affinity,2,25", "2,minecraft:bane_of_arthropods,2,25", "2,minecraft:blast_protection,2,25", "2,minecraft:depth_strider,2,25", "2,minecraft:feather_falling,2,25", "2,minecraft:fire_aspect,2,25", "2,minecraft:fire_protection,2,25", "2,minecraft:flame,2,25", "2,minecraft:frost_walker,2,25", "2,minecraft:knockback,2,25", "2,minecraft:looting,2,25", "2,minecraft:power,2,25", "2,minecraft:projectile_protection,2,25", "2,minecraft:protection,2,25", "2,minecraft:punch,2,25", "2,minecraft:respiration,2,25", "2,minecraft:sharpness,2,25", "2,minecraft:smite,2,25", "2,minecraft:sweeping,2,25", "2,minecraft:unbreaking,2,25", "3,minecraft:aqua_affinity,3,15", "3,minecraft:bane_of_arthropods,3,15", "3,minecraft:blast_protection,3,15", "3,minecraft:depth_strider,3,15", "3,minecraft:feather_falling,3,15", "3,minecraft:fire_aspect,3,15", "3,minecraft:fire_protection,3,15", "3,minecraft:flame,3,15", "3,minecraft:frost_walker,3,15", "3,minecraft:knockback,3,15", "3,minecraft:looting,3,15", "3,minecraft:power,3,15", "3,minecraft:projectile_protection,3,15", "3,minecraft:protection,3,15", "3,minecraft:punch,3,15", "3,minecraft:respiration,3,15", "3,minecraft:sharpness,3,15", "3,minecraft:smite,3,15", "3,minecraft:sweeping,3,15", "3,minecraft:unbreaking,3,15", "4,minecraft:aqua_affinity,4,5", "4,minecraft:bane_of_arthropods,4,5", "4,minecraft:blast_protection,4,5", "4,minecraft:depth_strider,4,5", "4,minecraft:feather_falling,4,5", "4,minecraft:fire_aspect,4,5", "4,minecraft:fire_protection,4,5", "4,minecraft:flame,4,5", "4,minecraft:frost_walker,4,5", "4,minecraft:infinity,1,5", "4,minecraft:knockback,4,5", "4,minecraft:looting,4,5", "4,minecraft:power,4,5", "4,minecraft:projectile_protection,4,5", "4,minecraft:protection,4,5", "4,minecraft:punch,4,5", "4,minecraft:respiration,4,5", "4,minecraft:sharpness,4,5", "4,minecraft:smite,4,5", "4,minecraft:sweeping,4,5", "4,minecraft:unbreaking,4,5", "5,minecraft:aqua_affinity,5,1", "5,minecraft:bane_of_arthropods,5,1", "5,minecraft:blast_protection,5,1", "5,minecraft:depth_strider,5,1", "5,minecraft:feather_falling,5,1", "5,minecraft:fire_aspect,5,1", "5,minecraft:fire_protection,5,1", "5,minecraft:flame,5,1", "5,minecraft:frost_walker,5,1", "5,minecraft:infinity,1,1", "5,minecraft:knockback,5,1", "5,minecraft:looting,5,1", "5,minecraft:mending,1,1", "5,minecraft:power,5,1", "5,minecraft:projectile_protection,5,1", "5,minecraft:protection,5,1", "5,minecraft:punch,5,1", "5,minecraft:respiration,5,1", "5,minecraft:sharpness,5,1", "5,minecraft:smite,5,1", "5,minecraft:sweeping,5,1", "5,minecraft:unbreaking,5,1"]
	#minecolonies.config.siftermeshes.comment
	siftermeshes = ["minecraft:string,0", "minecraft:flint,0.1", "minecraft:iron_ingot,0.1", "minecraft:diamond,0.1"]
	#minecolonies.config.listofcompostableitems.comment
	listOfCompostableItems = ["minecraft:rotten_flesh", "minecraft:tallgrass", "minecraft:brown_mushroom", "minecraft:red_mushroom", "minecraft:rose_bush", "minecraft:feather", "saplings", "small_flowers"]
	#minecolonies.config.sifterdrops.comment
	sifterdrops = ["0,0,minecraft:wheat_seeds,25", "0,0,minecraft:oak_sapling,1", "0,0,minecraft:birch_sapling,1", "0,0,minecraft:spruce_sapling,1", "0,0,minecraft:jungle_sapling,1", "0,1,minecraft:wheat_seeds,50", "0,1,minecraft:oak_sapling,5", "0,1,minecraft:birch_sapling,5", "0,1,minecraft:spruce_sapling,5", "0,1,minecraft:jungle_sapling,5", "0,1,minecraft:carrot:0,1", "0,1,minecraft:potato:0,1", "0,2,minecraft:wheat_seeds,50", "0,2,minecraft:oak_sapling,10", "0,2,minecraft:birch_sapling,10", "0,2,minecraft:spruce_sapling,10", "0,2,minecraft:jungle_sapling,10", "0,2,minecraft:pumpkin_seeds:0,1", "0,2,minecraft:melon_seeds:0,1", "0,2,minecraft:beetroot_seeds:0,1", "0,2,minecraft:carrot,1", "0,2,minecraft:potato,1", "0,2,minecraft:dark_oak_sapling,1", "0,2,minecraft:acacia_sapling,1", "0,3,minecraft:wheat_seeds,25", "0,3,minecraft:oak_sapling,10", "0,3,minecraft:birch_sapling,10", "0,3,minecraft:spruce_sapling,10", "0,3,minecraft:jungle_sapling,10", "0,3,minecraft:pumpkin_seeds:0,5", "0,3,minecraft:melon_seeds:0,5", "0,3,minecraft:beetroot_seeds:0,5", "0,3,minecraft:carrot:0,5", "0,3,minecraft:potato:0,5", "0,3,minecraft:dark_oak_sapling,5", "0,3,minecraft:acacia_sapling,5", "1,0,minecraft:cactus,2.5", "1,0,minecraft:sugar_cane,2.5", "1,1,minecraft:cactus,5", "1,1,minecraft:sugar_cane,5", "1,1,minecraft:gold_nugget,5", "1,2,minecraft:cactus,10", "1,2,minecraft:sugar_cane,10", "1,2,minecraft:cocoa_beans,10", "1,2,minecraft:gold_nugget,10", "1,3,minecraft:cactus,15", "1,3,minecraft:sugar_cane,15", "1,3,minecraft:cocoa_beans,15", "1,3,minecraft:gold_nugget,15", "2,0,minecraft:iron_nugget,5", "2,0,minecraft:flint,5", "2,0,minecraft:coal,5", "2,1,minecraft:redstone,10", "2,1,minecraft:iron_nugget,10", "2,1,minecraft:flint,10", "2,1,minecraft:coal,10", "2,2,minecraft:redstone,15", "2,2,minecraft:iron_nugget,15", "2,2,minecraft:coal,15", "2,2,minecraft:lapis_lazuli,5", "2,2,minecraft:iron_ingot,1", "2,2,minecraft:gold_ingot,1", "2,2,minecraft:emerald,1", "2,2,minecraft:diamond,1", "2,3,minecraft:redstone,20", "2,3,minecraft:coal,20", "2,3,minecraft:lapis_lazuli,10", "2,3,minecraft:iron_ingot,2.5", "2,3,minecraft:gold_ingot,2.5", "2,3,minecraft:emerald,2.5", "2,3,minecraft:diamond,2.5", "3,0,minecraft:nether_wart,5", "3,0,minecraft:quartz,5", "3,1,minecraft:nether_wart,10", "3,1,minecraft:quartz,10", "3,1,minecraft:glowstone_dust,5", "3,2,minecraft:nether_wart,10", "3,2,minecraft:quartz,10", "3,2,minecraft:glowstone_dust,10", "3,2,minecraft:blaze_powder,1", "3,2,minecraft:magma_cream,1", "3,3,minecraft:nether_wart,15", "3,3,minecraft:quartz,15", "3,3,minecraft:glowstone_dust,15", "3,3,minecraft:blaze_powder,5", "3,3,minecraft:magma_cream,5", "3,3,minecraft:player_head,5"]
	#minecolonies.config.crusherproduction.comment
	crusherproduction = ["minecraft:cobblestone!minecraft:gravel", "minecraft:gravel!minecraft:sand", "minecraft:sand!minecraft:clay"]
	#minecolonies.config.guardresourcelocations.comment
	guardresourcelocations = ["minecraft:slime", "tconstruct:blueslime"]
	#Harvest trunk-size for dynamic trees:1-8. [Default: 5]
	#Range: 1 ~ 5
	dynamictreeharvestsize = 5
	#minecolonies.config.luckyblocks.comment
	luckyblocks = ["minecraft:coal_ore!64", "minecraft:iron_ore!32", "minecraft:gold_ore!16", "minecraft:redstone_ore!8", "minecraft:lapis_ore!4", "minecraft:diamond_ore!2", "minecraft:emerald_ore!1"]

#All configurations related to pathfinding
[pathfinding]
	#Amount of additional threads to be used for pathfinding. [Default: 2]
	#Range: 1 ~ 10
	pathfindingmaxthreadcount = 2
	#Draw pathfinding paths (might be laggy). [Default: false]
	pathfindingdebugdraw = false
	#Verbosity of pathfinding. [Default: 0]
	#Range: 0 ~ 10
	pathfindingdebugverbosity = 0
	#Max amount of Nodes(positions) to map during pathfinding. Lowering increases performance, but might lead to pathing glitches. [Default: 5000]
	#Range: 1 ~ 10000
	pathfindingmaxnodes = 5000

#minecolonies.config.requestsystem.comment
[requestSystem]
	#The maximal amount of tries that the request system will perform for retryable requests. Higher increases server load. [Default: 3]
	#Range: 1 ~ 10
	maximalretries = 3
	#Should the request system creatively resolve (if possible) when the player is required to resolve a request. [Default: false]
	creativeresolve = false
	#Should the player be allowed to use the '/mc colony rs reset' command? [Default: false]
	canplayeruseresetcommand = false
	#The amount of ticks between retries of the request system for retryable requests. Lower increases server load. [Default: 1200]
	#Range: 30 ~ 10000
	delaybetweenretries = 1200
	#The maximal amount of buildings the Delivery Man should try to gather before attempting a drop off at the warehouse. [Default: 6]
	#Range: 1 ~ 50
	maximalbuildingstogather = 6
	#Should the request system prfinal ForgeConfigSpec.IntValue out debug information? Useful in case of malfunctioning of set system. [Default: false]
	enabledebuglogging = false
	#The minimal amount of buildings the Delivery Man should try to gather before attempting a drop off at the warehouse. [Default: 3]
	#Range: 1 ~ 50
	minimalbuildingstogather = 3

#minecolonies.config.research.comment
[research]
	#minecolonies.config.steelarmour.comment
	steelarmour = ["minecraft:iron_ingot*64"]
	#minecolonies.config.mightycleave.comment
	mightycleave = ["minecraft:iron_block*16"]
	#minecolonies.config.masterbowman.comment
	masterbowman = ["minecraft:bow*64"]
	#minecolonies.config.regeneration.comment
	regeneration = ["minecraft:emerald*1"]
	#minecolonies.config.squiretraining.comment
	squiretraining = ["minecraft:shield*5"]
	#minecolonies.config.woundingshot.comment
	woundingshot = ["minecraft:flint*128"]
	#minecolonies.config.accuracy.comment
	accuracy = ["minecraft:iron_ingot*1"]
	#minecolonies.config.captaintraining.comment
	captaintraining = ["minecraft:shield*25"]
	#minecolonies.config.duelist.comment
	duelist = ["minecraft:iron_ingot*64"]
	#minecolonies.config.ironskin.comment
	ironskin = ["minecraft:iron_ingot*16"]
	#minecolonies.config.improvedevasion.comment
	improvedevasion = ["minecraft:diamond*16"]
	#minecolonies.config.tactictraining.comment
	tactictraining = ["minecraft:iron_block*3"]
	#minecolonies.config.boiledleather.comment
	boiledleather = ["minecraft:leather*64"]
	#minecolonies.config.ironarmour.comment
	ironarmour = ["minecraft:iron_ingot*32"]
	#minecolonies.config.whirlwind.comment
	whirlwind = ["minecraft:iron_block*32"]
	#minecolonies.config.provost.comment
	provost = ["minecraft:diamond*16"]
	#minecolonies.config.diamondskin.comment
	diamondskin = ["minecraft:diamond*64"]
	#minecolonies.config.preciseshot.comment
	preciseshot = ["minecraft:flint*16"]
	#minecolonies.config.tickshot.comment
	tickshot = ["minecraft:bow*5"]
	#minecolonies.config.feint.comment
	feint = ["minecraft:emerald*8"]
	#minecolonies.config.fullretreat.comment
	fullretreat = ["minecraft:emerald*64"]
	#minecolonies.config.masterswordsman.comment
	masterswordsman = ["minecraft:diamond*64"]
	#minecolonies.config.rapidshot.comment
	rapidshot = ["minecraft:bow*25"]
	#minecolonies.config.repost.comment
	repost = ["minecraft:iron_ingot*32"]
	#minecolonies.config.fear.comment
	fear = ["minecraft:emerald*16"]
	#minecolonies.config.improvedleather.comment
	improvedleather = ["minecraft:leather*32"]
	#minecolonies.config.dodge.comment
	dodge = ["minecraft:emerald*64"]
	#minecolonies.config.improveddodge.comment
	improveddodge = ["minecraft:leather*32"]
	#minecolonies.config.cleave.comment
	cleave = ["minecraft:iron_block*8"]
	#minecolonies.config.deadlyaim.comment
	deadlyaim = ["minecraft:flint*256"]
	#minecolonies.config.agilearcher.comment
	agilearcher = ["minecraft:diamond*64"]
	#minecolonies.config.captainoftheguard.comment
	captainoftheguard = ["minecraft:shield*64"]
	#minecolonies.config.avoidance.comment
	avoidance = ["minecraft:iron_block*3"]
	#minecolonies.config.penetratingshot.comment
	penetratingshot = ["minecraft:flint*32"]
	#minecolonies.config.knighttraining.comment
	knighttraining = ["minecraft:shield*10"]
	#minecolonies.config.multishot.comment
	multishot = ["minecraft:bow*10"]
	#minecolonies.config.piercingshot.comment
	piercingshot = ["minecraft:flint*64"]
	#minecolonies.config.parry.comment
	parry = ["minecraft:iron_ingot*16"]
	#minecolonies.config.retreat.comment
	retreat = ["minecraft:emerald*32"]
	#minecolonies.config.improvedbows.comment
	improvedbows = ["minecraft:iron_block*6"]
	#minecolonies.config.improvedswords.comment
	improvedswords = ["minecraft:iron_block*6"]
	#minecolonies.config.evasion.comment
	evasion = ["minecraft:leather*64"]
	#minecolonies.config.avoid.comment
	avoid = ["minecraft:emerald*8"]
	#minecolonies.config.powerattack.comment
	powerattack = ["minecraft:iron_block*4"]
	#minecolonies.config.quickdraw.comment
	quickdraw = ["minecraft:iron_block*2"]

`

**Comment by Raycoms** [comment]
Weird, no increasing the speed should not cause it.

**Comment by Raycoms** [comment]
Can you post a modlist and maybe the latest.log during a time this happened?

**Comment by marchermans** [comment]
No response in more then 2 weeks. And not reproducible by us. Closing.
