### ISSUE TITLE
I CANT USE ANY OTHER HUTS!

### ISSUE THREAD

**Issue by vangelo** [ldtteam/minecolonies#4637]
1.10.2 Minecolonies version alpha

Version: 1.10.2-alpha

### Expected behavior

- i right click on the hut and it opens its gui

### Actual behaviour

i right click and it moves my hand like im clicking it but nothing happens 

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

**Comment by Asherslab** [comment]
A) Don't make issues with all capital names, also make them more descriptive.
B) Use. The. Issue. Template. It even mentions giving a log, etc.

Create a new issue and try again
