### ISSUE TITLE
Builder Placing Scarecrow outside colony boundaries

### ISSUE THREAD

**Issue by Raycoms** [ldtteam/minecolonies#4638]
As title suggests.

We gotta detect that in a placement handler to make sure the builder doesn't place colony blocks (through placeholder blocks) or scarecrow blocks outside of the colony boundaries.

**Comment by someaddons** [comment]
currently any action is restricted to be inside the boundaries, miner lumberjack etc. Should we really allow him to do anything outside of it?

**Comment by Raycoms** [comment]
Another solution would be not allowing a worker order to be placed where a partial part of it is outside of the colony border.

**Comment by someaddons** [comment]
ye thats what I was thinking, would avoid issues with other claims outside too
