### ISSUE TITLE
Unable to update any building that needs to be unlocked

### ISSUE THREAD

**Issue by outnampichtim** [ldtteam/minecolonies#4643]
### Minecolonies version

Version: 0.11.830-ALPHA

### Expected behavior
The ability to update a building that was already build before the part of the research tree was added.

- 

### Actual behaviour
If I clicked the "upgrade" button in the "build options" and I got a message to research the building while I already did that.

- 

### Steps to reproduce the problem

1. Construct a building ( I tested the smeltery and hospital) in a version before the part of the research tree was implemented
2. Then updated it to the latest version and research the building then update it
3.  it will not update
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

**Comment by Raycoms** [comment]
Added a fix, will merge it tomorrow probably.
