### ISSUE TITLE
No Previous hut recognition

### ISSUE THREAD

**Issue by FatalBlade** [ldtteam/minecolonies#4646]
### Minecolonies version
minecolonies-0.10.771-RELEASE-universal.jar

Version: 1.15.2

### Expected behavior
auto hut recognition

When replacing an accidentally broken building block (Sawmill, Miner, Deliveryman) the mod will recognize an already built structure rather than having to rebuild from scratch and remove existing blocks or waiting for it to be brought up in the builder que/sit unusable.

### Actual behaviour
Builder begins breaking down Current building and Building a level one version in it's place

In this case I had a level 3 sawmill and when the builder finally started working on it they began replacing it with a level 1 sawmill. 

### Steps to reproduce the problem

1. Break hut settings block
2. Place new block and que for building
3. ???
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/
I'm not sure logs are needed in this case but if they are I can dig them up.

**Comment by Asherslab** [comment]
Not feasible. has been requested, will not happen

You may use Creative mod to paste a building at whatever level you wish in the build tool

**Comment by FatalBlade** [comment]
Unfortunately pasted buildings won't be usable by the citizens, 

If it's not feasible to detect previous buildings is it then possible to Place a usable hut block at different intervals? Such as having Sawmill blocks for level 1, 2, etc? That way the citizens will recognize the block and be able to be hired and such?

**Comment by Raycoms** [comment]
you can make a style that has level 1-5 but only consists of the hut block.

**Comment by lunadragnstar** [comment]
Pasted buildings are usable by citizens as long as you use the paste button that looks like the clipboard in the bottom right corner in creative. This pastes the building how it would be built by the builder. If you have any issues with the building after pasting, go into the build options and click repair.

**Comment by FatalBlade** [comment]
I'm so sorry for the confusion I thought you had meant using something like worldedit to paste buildings I didn't even realize that button was there thank you so much!
