### ISSUE TITLE
stairs issue

### ISSUE THREAD

**Issue by lucalattanzio97** [ldtteam/minecolonies#4647]
Version: 
minecolonies-0.11.830-ALPHA-universal.jar

### Expected behavior

builder asks for stairs and place them as it should be

### Actual behaviour

the builder doesnt ask for stairs, instead it place stairs-like blocks that wila and other similar mods can't code. if you break it, it drops the vanilla stairs, but if it's in creative you cannot middle click it to pick it up. also, with this method, since the builder doesnt ask for stairs, you get free blocks.

### Steps to reproduce the problem

1. request a building with stairs in its schematics
2. the builder doesn't ask for stais
3. the builder places fake stairs
4. u get free stairs

**Comment by Raycoms** [comment]
This never happened to me, do you have any extra mods there?

**Comment by lucalattanzio97** [comment]
yes, it's the raoultech modpack. you find it on twitch. version 1.0.69

**Comment by Raycoms** [comment]
Some of these mods for sure mess up the vanilla stair blocks then. This would be mod support then.
