### ISSUE TITLE
cityzen pathing

### ISSUE THREAD

**Issue by lucalattanzio97** [ldtteam/minecolonies#4648]
#4461 # Minecolonies version
minecolonies-0.11.830-ALPHA-universal.jar

### Expected behavior

i don't really know how the npc calculate the best path to get to the building, so I don't kow what to expect

### Actual behaviour

the npcs straight up avoid passing over wood slabs placed alongside the grass path. also sometimes prefer a longer route, passing over stone bricks, instead of a shorter one made of grass path. Lastly, i noticed that when i placed a big structure in front of the builder's hut, he chosed a much longer path avoiding grass, and he also got stuck for no reason alongside the longer route. the only way to unstuck him was to hit him a few times so he moved, and only then he proceeded to go to the destination.

![2020-04-16_15 05 36](https://user-images.githubusercontent.com/41806417/79460353-fce78300-7ff4-11ea-97ba-fde35d7f2017.png)

i don't really know what else to say, but in my opinion you could insert a menu in the townhall where can be selected the blocks the player wants as best pathing routes

**Comment by Raycoms** [comment]
There are waypoint blocks you can use to guide him. For sure there are some alongside there.
