### ISSUE TITLE
Builder won't accept shields as material

### ISSUE THREAD

**Issue by Manatee1337** [ldtteam/minecolonies#4649]
### Actual behaviour:

When building combat academy 3, builder requests 2 shields. Gets stuck in requesting shields from player loop, here's a picture.
![ss+(2020-04-16+at+04 56 47)](https://user-images.githubusercontent.com/63800898/79472358-06c4b280-8004-11ea-89c3-803a962fc23d.png)

The pink seems odd. Builder has 2 shields in inventory, directly placing into it does nothing, cancelling request ends up in the same request, putting shields anywhere else does not work. Deliverymen grab the shields from chests/bench soon as they pass by to store. Handplacing the shields on the combat dummies, then cancelling request does nothing.
The request menu does allow you to press the turnin button - but doing so doesn't take the shields from your inventory and it immediatly goes back to 0/2.

### Steps to reproduce the problem

1. Have builder start combat academy 3
2. Give it all the materials
3. Watch it fail at using the shields.

**Comment by Raycoms** [comment]
fix pushed
