### ISSUE TITLE
Loot pools with null names added in LootTableLoadEvent

### ISSUE THREAD

**Issue by SilentChaos512** [ldtteam/minecolonies#4650]
### Minecolonies version

Version: 0.11.831-ALPHA (also tried 0.11.821-BETA)

### Expected behavior

- Loot tables to load correctly, regardless of how many mods modify them.

### Actual behaviour

- Minecolonies adds pools without setting a name to some vanilla loot tables, causing a `NullPointerException` the next time a pool is added to that table. This results in empty loot chests, and misleading stacktraces in the log file.
- I reproduced this with just Minecolonies and Botania, other combinations could get similar results. In this case, the stacktraces show Botania, but Minecolonies needs to fix this (Forge also needs to improve the `addPool` function, but this needs to be fixed regardless).

### Steps to reproduce the problem

1. Install Minecolonies and Botania (or another mod that modifies the same loot tables)
2. Run game and **load up a world**
3. See errors in the log file

### Logs
- latest.log: https://gist.github.com/SilentChaos512/4d9eeb80a764273a2e3810004016de3f#file-gistfile1-txt-L168
- crashlog: N/A (does not crash)

### How To Fix

- Call `name()` and set a unique pool name on the `LootPool.Builder` at https://github.com/ldtteam/minecolonies/blob/f32cd6deb512e86bb17d4f256cb4d2e9cbb1440b/src/main/java/com/minecolonies/coremod/loot/SupplyLoot.java#L90

**Comment by someaddons** [comment]
fixed in newest
