### ISSUE TITLE
Citizen Entities not Loading in Game When Created (birth, recruited)

### ISSUE THREAD

**Issue by Rixhephtos** [ldtteam/minecolonies#4654]
### Minecolonies version

Version: 
Minecraft: 1.15.2
Forge: 31.1.43
Minecolonies: 0.11.810-BETA

### Expected behavior

When clicking on the button in the Town Hall GUI to recruit citizens, it gives 4 options. I have diamonds on hand, they option for diamonds is lit up. There is an empty bed in the colony, so a citizen should be recruited.

- 

### Actual behaviour

- 
Clicking on the Actions tab gives me multiple options, including the option for citizen recruitment. I have diamonds in my hand. The letter with a diamond on it is lit. I click on it, it grays out, nothing happens. The diamond is not consumed. No new citizen comes, there is no text, nothing happens at all besides the graying out of the letter. I have tried recruiting using the other materials as well, the same thing occurs. Click on any one of them and all options gray out.

https://drive.google.com/open?id=1Lx4FXahCHr-oz04ZZIXMqneurZl2Bw-q

### Steps to reproduce the problem

1.  Have one of your original citizens die from a monster (mine died to a Silent's Gems 3 wisp), and two others have a baby which never existed? (I was informed a child was born after the citizen died. It never showed up in the citizen log, I never saw it, and it says I have 3/4 citizens.) I also completely removed and rebuild 2 citizen huts, one level 1, one level 2. Two citizens moved into the level 2 right away. The third refused to move into the level 1 hut until I upgraded to level 2. 
2.  Attempt to recruit a new citizen, when you have 3/4.
3.  You are haunted by the ghost of your dead citizen and/or the child-who-never-existed, and you can't house your citizens properly or recruit new ones.
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: https://gist.github.com/Rixhephtos/b2c6b26668a497cff9b1b137e5b88c31
- crashlog: none

**Comment by Rixhephtos** [comment]
![2020-04-16_22-06-32](https://user-images.githubusercontent.com/61978807/79524448-92533900-802e-11ea-980b-93ac257d7ef7.png)

It looks like the child that doesn't exist is the cause of all this- Ethan R. Asger. We first tried getting info on him, it said "Citizen entity not loaded!". Then we tried reloading him using commands, "Updated entity for citizen id 3", tried info again, same message. He cannot be killed using commands either, it gives the "Citizen entity not loaded!" message for that as well. I have tried recalling the citizens using the town hall, he does not appear. His name doesn't exist in the citizen hut either. Doing /forge entity list only shows 3 citizens.

**Comment by Rixhephtos** [comment]
Another update, I upgraded a citizen hut so I had room for 5, I was able to recruit another person. However, they weren't loaded either. The owner of the server I play on was nice enough to restart the server though, and both missing colonists appeared and are fully working. So it seems to be an issue with loading the colonist entities upon creation, which is a whole other issue.

**Comment by Raycoms** [comment]
Are there any mods that could interfere with the spawning of citizens? this is not happening on our servers so some mod must be causing this.

**Comment by Raycoms** [comment]
After the restart, is this still the case with new citizens now?

**Comment by Rixhephtos** [comment]
I'm not sure what mod could interfere with it, we're playing with a bunch on The Endless Frontier modpack. I left my game logged in overnight and I was notified that child had grown up and was awaiting a job, but was never notified of his creation. But he was acting normally so I suppose all is well. Hopefully this was just a one time thing. I'll close the issue now.

**Comment by Raycoms** [comment]
Okay, there was some issue lately with loading the wrong world for the colony which has been fixed in reason versions. This issue could cause the problem you described.

**Comment by Rixhephtos** [comment]
Nice, hopefully the modpack will update to a more recent version, thanks for all the help!
