### ISSUE TITLE
MISSING:container.inventory error

### ISSUE THREAD

**Issue by wikidone** [ldtteam/minecolonies#4657]
### Minecolonies version

Version: 0.11.832 Alpha Universal

### Expected behavior
Not sure what it should say

### Actual behaviour
Where the inventory button is both on the builders workstation and in his menu it states "MISSING:container.inventory

### Steps to reproduce the problem
1.Talk to the builder or open his workstation
2. Look at bottom where inventory button is and error shows there

### Logs: Latest.log and crashlog at https://gist.github.com/
Logs
[latest.zip](https://github.com/ldtteam/minecolonies/files/4491252/latest.zip)

**Comment by Raycoms** [comment]
This is again the building is null issue, the buildings did not get placed accordingly.

**Comment by Raycoms** [comment]
At the place you've placed the building, is there the colony?
