### ISSUE TITLE
Miner remembers mineshaft position after repositioning

### ISSUE THREAD

**Issue by ToMe25** [ldtteam/minecolonies#4658]
Version: 0.11.832-ALPHA

### Expected behavior
I expect the miner to forget his old mine after getting repositioned, or broken and rebuild somewhere else.

### Actual behaviour
If you reposition the miner, or break his hut and rebuild it somewhere else, he remembers his old mine, as long as there are still some ladders left. 

### Steps to reproduce the problem

1. Build a miner
2. let him start a mineshaft
3. move his hut
4. see him using his old mineshafts.

### Logs: Latest.log and crashlog at https://gist.github.com/
- latest.log: [latest](https://pastebin.com/2bgpnBKM)
- crashlog: Not a Crash.
Note that this log is from a dev enviroment test, i however also had this problem in a normal setting.

**Comment by ToMe25** [comment]
After some more testing i figured out he doesn't remember the old mineshaft, it was just barely in range, and was deeper than the newly created one, so the miner selected the old inaccessible mineshaft as the right one to use.

**Comment by Raycoms** [comment]
I just tested that yes, it's because the old shaft is too close.

**Comment by ToMe25** [comment]
it still might be a bad thing that he prefers the old mineshaft, if it is deeper.
