### ISSUE TITLE
Manually assigning Citizens to Citizen hut. [$5]

### ISSUE THREAD

**Issue by Wissi** [ldtteam/minecolonies#466]
Can we have a GUI in the Citizen hut to be able to "assign" what citizen will be "housed" there?

The Town radius being 360 blocks makes the spreading of the Town huts and Citizen huts a challenge. 
Being able to assign the Citizens to each specific Citizen hut would be great. 
Instead of having a Citizen hut near a worker and the worker walking away to a further citizen hut at night.

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=40987317)](https://www.bountysource.com/issues/40987317-manually-assigning-citizens-to-citizen-hut?utm_source=40987317&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by pmardle** [comment]
I would support this enhancement.. most of the code/work must already be done by the hire/fire workers system, and hopefully could be adapted.

Could be an interesting mechanic later on when we add the "Happiness" system, that "homeless" citizens would cause a big negative effect.

**Comment by Wissi** [comment]
Any comments about progress on this enhancement?
Since Pmardle says: "... most of the code/work must already be done by the hire/fire workers system, and hopefully could be adapted."  Thanks.

**Comment by nojo121** [comment]
Will do it after LJ fixes :)

**Comment by Wissi** [comment]
So anyone else might be able to tackle this one, since nojo is no longer in the scene and Pmardle's comments make it seem like an easy task?

**Comment by xavierh** [comment]
I like to take this. But I don't know when. If I do, I will do the assign a
builder t9 a job issue too

**Comment by Wissi** [comment]
I really hope you can if not someone else. It really is important for large colonies and of course the "assign the builder to a job" as well.  
They definitely need to be addresses together and both are much needed.

**Comment by Wissi** [comment]
Thanks @Raycoms , Close issue now?
