### ISSUE TITLE
children spawn randomly

### ISSUE THREAD

**Issue by slendeboy88** [ldtteam/minecolonies#4660]
Version: mine colonies 1.12.2-0.10.348-RELEASE

### Expected behavior
children should only spawn if the citizen hut has been upgraded and there is a free slot to spawn a child

### Actual behavior
every 10 minutes a child spawns into the village and all the citizen's huts are full capacity, which then I need to make new citizen huts to house them.

### Steps to reproduce the problem
honestly idk because this has never happened to me before

**Comment by someaddons** [comment]
try updating to the newest version, yours is really old
