### ISSUE TITLE
Research Circus or Gourmand with restaurant lvl 5 doest not met requirements

### ISSUE THREAD

**Issue by DiabolosMan** [ldtteam/minecolonies#4662]
### version
Minecolonies version 0.11.832-ALPHA
Minecraft version 1.15.2
Forge version 3.11.46

### Expected behavior
Research Circus or Gourmand that requires restaurant lvl 2... with a restaurant lvl 5 should start
![Requirement Issue](https://user-images.githubusercontent.com/63854770/79569708-6b414980-80b8-11ea-9cd3-ef146dfb0497.jpg)

### Actual behaviour
I was trying to research Circus or Gourmand that requires restaurant lvl 2... I have a restaurant lvl 5, however, I get a message 'Minimum research requirement not met'
See screenshot

### Steps to reproduce the problem
1) have a colony with restaurant lvl 5 
2) Try to research 'Circus' or 'Gourmand'
3) Research is not started

**Comment by Raycoms** [comment]
Ty, I'll look into it

**Comment by DiabolosMan** [comment]
Wahooo ….. I have seen your commit. You did it so quick !!! ;-) I will wait for your next alpha.
Thanks.

**Comment by DiabolosMan** [comment]
I confirm that it is fixed in the latest alpha. Thanks.
