### ISSUE TITLE
Pirate ship question

### ISSUE THREAD

**Issue by Divinesmiter** [ldtteam/minecolonies#4666]
Possibly more or a question then an issue.
Pirate ships:
A) chests have nothing in them (dont care really just not sure if they are supposed to.
B) no way to disable the ship raid so workers return to work, other theb waiting for them to sail off.
C) i have killed them over and over, the spawners and destroyed the ship both in survival and creative. 

No error logs or crashes or anything like that. I have searched far and wide and cat seem to get any info to show up.

**Comment by Raycoms** [comment]
a) Yes, for now we have not put any loot in them
b and c) that is fixed in the latest alphas =)
