### ISSUE TITLE
HOW TO FIX {Please tell me which fuel i should use in Furnace}

### ISSUE THREAD

**Issue by ghost** [ldtteam/minecolonies#4668]
FOLLOW THESE SIMPLE STEPS TO FIX OR SOLVE THE PROBLEM
-------------------FIRST--------------------
![2020-04-18_01 07 42](https://user-images.githubusercontent.com/63372171/79606555-9ad16f80-8113-11ea-8519-9de642c2b6c2.png)
------------------SECOND-------------------
![2020-04-18_01 10 00](https://user-images.githubusercontent.com/63372171/79606583-a45ad780-8113-11ea-936a-ab8335eafdfd.png)
------------------THIRD----------------------
![2020-04-18_01 13 41](https://user-images.githubusercontent.com/63372171/79606611-ade43f80-8113-11ea-8ff0-f81128ce2933.png)

 DO THIS STEPS TO FIX AND COMMENT ME BACK IF U HAVE ANY OTHER PROBLEM

**Comment by Raycoms** [comment]
Ty =)
