### ISSUE TITLE
My AI has run into an issue

### ISSUE THREAD

**Issue by funkyhumi** [ldtteam/minecolonies#4671]
### Minecolonies version

Version: Minecolonies 0.11.840-BETA. Forge 31.1.44

### Expected behavior

- 
Just gave a citizen a task "create a citizen hut" and he creates the hut
### Actual behaviour

- 
A request just popped up saying " My AI has run into an issue. please checkout the latest.log file (or contact the server owner when on a serverà and let the minecolonies authors know."

https://ibb.co/vwkJ5sK

### Steps to reproduce the problem

I haven't been able to reproduce this
1. 
2. 
3. 
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: https://pastebin.com/QuruUmUL
- crashlog:

**Comment by Raycoms** [comment]
Please also execute /mc colony rs-reset.
This is due to some backwards compatibility update

**Comment by JackOfSpade** [comment]
/mc colony rs-reset is not a proper command

**Comment by ravenbuilder934** [comment]
It's /mc colony requestsystem-reset (your colony ID here)
