### ISSUE TITLE
Suggestion: Scheduled Backups

### ISSUE THREAD

**Issue by caseyjfer** [ldtteam/minecolonies#4674]
### Expected behavior
Server running longer than a configured time would run the '/mc colony backup' command on a scheduled interval (configurable in Minecolonies config). 

This is similar to functionality that I have seen that will save world backups on an interval (every hour while a user is logged in/chunks are loaded).

### Actual behaviour
Server was online, running smoothly on a personal computer for 10 days. Since no server restart was needed to fix any issues in the interim, no backup was created for the colony. When the computer ITSELF had an issue (graphics card error), on hard reboot of the system the colony data for that 10 days was lost and restored from the previous state (last restart) since no manual backup had been performed (I was unaware of this command until after the crash).

**Comment by Raycoms** [comment]
Moved to feature requests
