### ISSUE TITLE
Worker's Request For An Unknown Tool

### ISSUE THREAD

**Issue by RebmaV** [ldtteam/minecolonies#4675]
### Minecolonies version
 1.12.2-0.11.804-RELEASE

Version: 1.12.2

### Expected behaviour
 Builder requesting tools to start building 
Builder asks for a needed tool such as a pickaxe, axe or spade to begin construction of a building 

### Actual behaviour
 Placed builder's table down, selected a worker and waited. The right builder came but made confusion particle, I clicked on her and she was asking for an 'unknown tool' made of wood or gold. I put wooden pickaxes, axes, spades and even a sword into the box inventory and her inventory but she wouldn't accept them. 

### Steps to reproduce the problem

1.  Put a builders block down 
2. Select a builder 
3. Select the Building you want them to build
4. Wait for them to ask you for resources

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

**Comment by Raycoms** [comment]
Did you try the latest alpha too?

**Comment by RebmaV** [comment]
It was on the latest alpha that I noticed it, so then I went back and tried on the 1.12.2 release instead but got the same problem. Also, bit of an oddity, but endermen keep killing the villagers as well. I have no idea why but as the builder isn't building anything at the moment, the townhall isn't built. So at night, the endermen bump off my villagers if i don't make them temporary housing. Not a problem per se, but not sure it was by your design.
________________________________

**Comment by Raycoms** [comment]
Fix merged
