### ISSUE TITLE
Builder won't take food out of his chest

### ISSUE THREAD

**Issue by SevenChords** [ldtteam/minecolonies#4676]
minecolonies version 1.12.2-0.11.804
there is almost a full stack of bread in the chest inside the builder's hut, yet the builder still complains about being hungry and having no food. when i take the food out of his chest and put it into his inventory manually he will eat a part of the food, put the rest of it back into the chest, soon after that complaining again about how he has no food.

**Comment by iiEpic** [comment]
The citizens either need to be manually fed or you need to construct a Restaurant (Cook) building.

https://wiki.minecolonies.com/source/workers/cook
https://wiki.minecolonies.com/source/buildings/restaurant

**Comment by iiEpic** [comment]
Do you have a Restaurant constructed with a worker in it?

**Comment by Raycoms** [comment]
Please construct a restaurant yes
