### ISSUE TITLE
Builder inventory management problem

### ISSUE THREAD

**Issue by arough007** [ldtteam/minecolonies#4678]
### Minecolonies version

Version: 0.11.812-ALPHA on 1.15.2

### Expected behavior

- The builder (to my knowledge) scans the building site and starts filling his inventory.
He takes the item he needs for the next block to place and goes through the schematic to see what block is needed next and so on.
He then walks over to the building site and starts building until his inventory is either empty or he needs a new type of block.

### Actual behaviour

- The builder fills his inventory with seemingly random stuff (e.g. roof tiles when just starting to build). The first item he needs is in there, so he starts bulding.
Soon he won't find the next needed item in his inventory and walks back to his hut.
He takes the requiered item, offloads stuff he picked up and then offloads the needed item as well.
He then goes back to the building site and turns around immediately, because he doesn't have the item.
Sometimes he only does it once, but sometimes he does it multiple times with the same item.
Here is a video of it: https://youtu.be/x8WXyZzZgEM
In the video the block of interest is the stone bricks.

Under "similar issues" #2308 is listed and was closed due to a similar issues already being reported.
The issue still seems to be present and on top of it my issue is with the builder dropping items he needs as the next block.

### Steps to reproduce the problem

1. Request the building of the new house
2. Clumsy builder does his stuff
3. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: [latest.log](https://github.com/ldtteam/minecolonies/files/4499128/latest.log)

**Comment by Raycoms** [comment]
Planned feature yes.

**Comment by arough007** [comment]
The main problem here isn't the prefetching.
It's that the builder takes an item he needs and puts it back in the huts inventory in the same cycle, so he walks of without the needed item.
In the video at 1:00 he places some blocks and then needs stone bricks.
He goes to his hut, puts the bricks in his inventory and offloads stuff he doesn't need...along side the stone bricks.

I noticed that it seems to help when the needed item is in the first two rows of his inventory.
So you can babysit him by standing in his hut and moving the needed item that he takes, in the first row of his inventory manually. This speeds up the building process significantly, because there are no unnecessary trips anymore. But this this costs the player (e.g. me) a lot of time and boring labour.

I hope the problem is clearer now.

**Comment by Raycoms** [comment]
Yes, the problem is prefetching if the inventory gets too full. We have to make sure some space is left fo rhim to operate so he might dump it again randomly to make space since we don't have the information at the time.

We want to do bucket prefetching where never has too many items in his inventory and all the random things are not needed.

**Comment by arough007** [comment]
Oh. I'm sorry ;)
Thanks for clarifying.
