### ISSUE TITLE
Barracks towers placing wrong

### ISSUE THREAD

**Issue by Kao713** [ldtteam/minecolonies#4680]
### Minecolonies version

Version: 0.11.852-ALPHA

### Expected behavior

- Build a Barracks and then the barracks towers without problems

### Actual behaviour

- Barrack towers spawns in wrong places or rotated and if try to move it they rotate again 

### Steps to reproduce the problem

1. Build barracks
2. Build barracks tower

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

**Comment by Asherslab** [comment]
what schematic style is this with

**Comment by Asherslab** [comment]
and what levels

**Comment by Kao713** [comment]
For me, it was in every update of the jungle and fortress styles, but i've read comments for it happening in others. 
also, the problem when moving seems to be indepent of the style

**Comment by melv-n** [comment]
I just noticed the same (`minecolonies-0.11.831-ALPHA-universal`) when trying to build a nordics Town Hall. It shows up great in the building tool, but once you start the actual build the construction tape is wrong and offset from how you placed the white outline during the build process. Frustrating :(

**Comment by Raycoms** [comment]
should be fine now
