### ISSUE TITLE
Colonies not loading properly after update.

### ISSUE THREAD

**Issue by TheKLC** [ldtteam/minecolonies#4681]
![2020-04-19_18 26 09](https://user-images.githubusercontent.com/63223287/79703827-61137c80-826b-11ea-9fea-6643c2a02974.png)

### Minecolonies version
happening on update from minecolonies-0.11.813-ALPHA-universal to minecolonies-0.11.840-BETA

Version: 
1.15.2
### Expected behavior
Load colony boundaries, citizens, and such.

### Actual behaviour
We just updated enigmatica 4 from 0.4.1 to 0.4.2. Colonies were working fine before update, after update you are met with what seems like a never ending loop of the "we suggest you use the build tool, show that or continue" query popup that you get when placing a building with the block instead of the build tool. It seems that each of those instances is the colony trying to load in its chunk they pop up as you go from chunk to chunk (as long as the server is able to process and keep up). Instead of seeing the nice square around your colony as to build limits, the boundary is jagged and dependent on what chunk you have been in prior. This all resets if you are disconnected from the server and relog. 

No colonists appear to be assigned to any of their huts, and none show up in the town hall GUI. But, they do continue on working as though they were assigned. The uploaded image shows a screenshot of what should be the southwest corner of the colony, looking to the town hall. Building grid is only shown around chunk that I was currently in.

### Steps to reproduce the problem

1. Log into server
2. Wait for use build tool query to pop up
3. cancel
4. loads chunk to colony (minus any colonists)
4. fly to next chunk
5. repeat from step 2
5a. Disconnect from server, at which time, start from step 1 with NO chunks assigned to town hall.

### Logs: Latest.log and crashlog at https://gist.github.com/
No crashlog, but upon logging into server this (https://pastebin.com/7ALNG3yq) starts running over and over again until client disconnects

**Comment by Raycoms** [comment]
I believe you're logging in with the wrong version (different version that on the server) which is causing this. Pelase confirm

**Comment by TheKLC** [comment]
Both the client and the server had the 0.11.840-BETA version of minecolonies installed. Also, this is the Enigmatica5 pack not Enigmatica4 as I had originally mis-typed.

**Comment by Raycoms** [comment]
Is this solved? Afaik this only happens when there is a version mismatch somehow (server didn't load the new one yet, or client was missing out because twitch was slow)
