### ISSUE TITLE
Sudden Crash related to structurize:placeholderblock

### ISSUE THREAD

**Issue by carlansor** [ldtteam/minecolonies#4688]
### Minecolonies version ###

Version: 
minecolonies-0.11.853-ALPHA-universal
### Expected behavior

Just dont crash

### Actual behaviour

Crashes after a freeze

### Steps to reproduce the problem

just opened my creative world and got near the pirate ships.

### Logs: Latest.log and crashlog at https://gist.github.com/
the launcher said this after the crash:
```
The game crashed whilst rendering block entity
Error: java.lang.IllegalArgumentException: Cannot set property DirectionProperty{name=facing, clazz=class net.minecraft.util.Direction, values=[north, south, west, east]} as it does not exist in Block{minecraft:spawner}
```

- crashlog:
https://gist.github.com/carlansor/35a1986e414a81e7fb2c1966bcd6337b

**Comment by Raycoms** [comment]
fixed
