### ISSUE TITLE
Needing the Building Tool GUI name for compat with Blur

### ISSUE THREAD

**Issue by KiroTheBlueFox** [ldtteam/minecolonies#4690]
**Version :**
Minecolonies v0.10.341-ALPHA for 1.12 (Modpack ATM3 (modified for private uses))

I'm using the mod Blur to add a cool blur effect to the background of each GUI, but it also appears on the building tool GUI (the one to place, move and rotate buildings) as it is not in the exclusion list, so I wanted to know what is the full name of the GUI so Blur can exclude it (example of GUI excluded : net.minecraft.client.gui.GuiChat)

Thanks in advance !
_~Kiro_

**Comment by Raycoms** [comment]
com.ldtteam.blockout.BOScreen should be it

**Comment by KiroTheBlueFox** [comment]
It doesn't work, maybe it's just Blur which doesn't detect it

**Comment by Asherslab** [comment]
Our GUI systems are not the same as most mods. you'll need to find a way to figure out the classpath that the mod expects

**Comment by TheButterbrotMan** [comment]
@KiroTheBlueFox Did you figure this out? :)
