### ISSUE TITLE
[1.14.4] Citizens ignoring waypoints

### ISSUE THREAD

**Issue by Sandriell** [ldtteam/minecolonies#4696]
### Minecolonies version

Version: minecolonies-0.10.715-RELEASE-universal

### Expected behavior

Citizens make proper use of the waypoints

### Actual behaviour

The citizens are not using the waypoints properly and actually walk around them.

![2020-04-21_23 11 25](https://user-images.githubusercontent.com/10704907/79936938-ad56ec00-8426-11ea-9465-40602b14b27c.png)
![2020-04-21_23 13 11](https://user-images.githubusercontent.com/10704907/79936948-b0ea7300-8426-11ea-9b0f-35728248f4d4.png)

In fact if I put a fence post in the circled area marked below, it completely breaks their pathfinding and they just get permanently stuck next to it.
![Inked2020-04-21_23 11 25_LI2](https://user-images.githubusercontent.com/10704907/79937532-1c811000-8428-11ea-96a6-5af0f6327ad2.jpg)

**Comment by Raycoms** [comment]
Yeah 1.14 won't get additional pathing updates. We had to move on to 1.15 =)
