### ISSUE TITLE
BuildTool: building is null

### ISSUE THREAD

**Issue by Ruisi-Lu** [ldtteam/minecolonies#4697]
### Minecolonies version

Version: minecolonies-0.11.827-ALPHA

### Expected behavior

Use building Tool to place Town Hall block, and not error

### Actual behaviour

- Tow Hall block is disappear
- Get "Start Your Colony" advancement
- Server error

### Steps to reproduce the problem

1. Use building tool place Town Hall

### Logs: Latest.log and crashlog at https://gist.github.com/

![image](https://user-images.githubusercontent.com/34283364/79937088-91396600-848b-11ea-8adb-e2bfe5fc77b4.png)

**Comment by Raycoms** [comment]
Are you within the colony boundaries?

**Comment by Ruisi-Lu** [comment]
> Are you within the colony boundaries?

It's new map, and first colony

**Comment by Raycoms** [comment]
wield the build tool and check the boundary, the place you're trying to place it, is it within the boundary?

**Comment by Ruisi-Lu** [comment]
> wield the build tool and check the boundary, the place you're trying to place it, is it within the boundary?

Before I place Town Hall, I never create any colony.
I ended up use Town Hall block to create a colony directly in creative mode

**Comment by Raycoms** [comment]
Ah, you tried to paste the townhall in creative?

You'll have to first place the townhall once, right click it, click to create a colony. Pick up the townhall. Paste it now in the newly created colony.

(Colony creation is now done via GUI)

**Comment by LaysDragon** [comment]
HI,I'm play with @lhc03952  in same server,he try to create the townhall with builder 
 tool first time in survival mode,it failed and lost the townhall block,we have no idea how to get second townhall block,so we can only take the townhall second from creative mode and use it in creative mode.the Error is happen in survival mode and not in any colony.

**Comment by LaysDragon** [comment]
I mean,you see,lost of townhall block from the beginning for new player should avoid,it still buggy

**Comment by Raycoms** [comment]
Did he lose the townhall block, or was the townhall block placed underground somewhere?

**Comment by Ruisi-Lu** [comment]
> Did he lose the townhall block, or was the townhall block placed underground somewhere?

Lose the townhall block, and many forum discus this question

**Comment by Raycoms** [comment]
Was this previous to the update where colony creation was made in the GUI?

**Comment by LaysDragon** [comment]
> Ah, you tried to paste the townhall in creative?
> 
> You'll have to first place the townhall once, right click it, click to create a colony. Pick up the townhall. Paste it now in the newly created colony.
> 
> (Colony creation is now done via GUI)

That wired,I don't think it is necessary to pick the town hall up again to create the building.

1. I can put the town hall in single player world,it will guide me to the building GUI to setup the build init place.
2. Then after that.I can see the town hall floating on the air,now right click the town hall to create colony . After the colony is created,the construction tape for building area is appear around the town hall.

I think @lhc03952 is failed at step one,town hall disappear with Null Pointer Error. I can't reproduce the error myself under single player world...it might have some condition to trigger the building failed bug.
