### ISSUE TITLE
Builders told me to give you a log(Nightly build)

### ISSUE THREAD

**Issue by tintinz** [ldtteam/minecolonies#4698]
### Minecolonies version

Version: 

### Expected behavior

- 

### Actual behaviour

- No problem showed up jet, The builder told me to put up a log.

### Steps to reproduce the problem
I have build a builders hut, Miners hut, lumberjack, and now trying to build a delivery hut

Also notis that When you have clieced on deliverys hut, "build options" you cant click on Cancel building.

### Logs: Latest.log and crashlog at https://gist.github.com/
https://gist.github.com/tintinz/31b8883270c4cd6bc2e62aa4278c807b

- latest.log:
- crashlog:

**Comment by Raycoms** [comment]
Please execute /mc colony rs-reset 

This was due to some backlog fixing lately in minecolonies.

Thanks for the report.
