### ISSUE TITLE
Builder's Hut and Builder not accepting Clock

### ISSUE THREAD

**Issue by TheKrowi** [ldtteam/minecolonies#4699]
### Minecolonies version
Version: minecolonies-1.12.2-0.11.811-BETA-universal
Modpack: MC Eternal 1.3.5.3

### Expected behavior
Either
- Builder requests clock, giving him clock fulfills request
- Builder's Hut requests clock, giving clock fulfills request

### Actual behaviour
- Builder requests Clock, request can;t be fulfilled (no button)
- Giving Builder clock via either putting in his inventory or dropping on the ground and him picking it up does not fulfill request
- Builder's Hut requests Clock, pressing the button puts Clock in Rack or Builder's inventory

### Steps to reproduce the problem
1. Build deliveryman mirrored
2. Upgrade to level 4
3. Builder will get stuck here on that request
4. ... Profit

### Screenshots
![2020-04-22_11 32 24](https://user-images.githubusercontent.com/22818581/79966283-82ec4980-848d-11ea-9c59-8231896f5d39.png)
![2020-04-22_11 33 15](https://user-images.githubusercontent.com/22818581/79966286-8384e000-848d-11ea-9407-c189b6f5b979.png)
![2020-04-22_11 37 25](https://user-images.githubusercontent.com/22818581/79966391-a8795300-848d-11ea-92f0-1776d1eca712.png)

**Comment by Raycoms** [comment]
Do you have any mod altering the clock?

**Comment by TheKrowi** [comment]
Holding shift while hovering the Clock in JEI
![2020-04-22_12 01 32](https://user-images.githubusercontent.com/22818581/79968890-0a878780-8491-11ea-890d-3162e7432cbc.png)

Holding shift while hovering the Clock in my inventory, appears to have an NBT tag
![2020-04-22_11 59 09](https://user-images.githubusercontent.com/22818581/79968806-ed52b900-8490-11ea-9b3a-b82379d53577.png)

"/entitydata @e[type=Item,r=3] {}" on a dropped clock, looks like Quark might be the culprit?
![2020-04-22_11 59 49](https://user-images.githubusercontent.com/22818581/79968811-ef1c7c80-8490-11ea-9fb2-b879ccb603cb.png)

**Comment by Raycoms** [comment]
It's definitely the NBT tag on the clock not making the builder accept it

**Comment by Raycoms** [comment]
Closed in favor of #4510
