### ISSUE TITLE
Job not canceled when removing block hut

### ISSUE THREAD

**Issue by xavierh** [ldtteam/minecolonies#470]
### Minecolonies version

version 1.11 latest from github

### Expected behavior

- Picking up a hut block should cancel/remove the job with it

### Actual behaviour

- Job still available in Town Hall Job list

### Steps to reproduce the problem

1. Craft a hut block
2. Place the block
3. Start building
4. Break the Hut box
5. Go to the Town Hall to see that the job is still there

Test on CSP in order to reproduce the problem

I did get the same issue in SMP plus the resources needed were still listed in the Builder's Hut

Additionally the builder refuse to work (IDLE) and need to be fired/hired

**Comment by ProsperCraft** [comment]
I am having the same problem on my server.

**Comment by Raycoms** [comment]
Should now work in the newest version.
