### ISSUE TITLE
Composter requires Barracks Researched

### ISSUE THREAD

**Issue by AlMasque** [ldtteam/minecolonies#4700]
### Minecolonies version

Version: 0.11.858-ALPHA-universal

### Expected behavior

Building the Composter
- After researching the Composter in the University, you should be able to build it
### Actual behaviour

- At this point in time, trying to click the build option on the composter comes up with the message, "You must research the Barracks first"

### Steps to reproduce the problem

1. Research Composter (without researching the barracks)
2. Make the Composter Block
3. Place and click Build
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

**Comment by Raycoms** [comment]
Fixed in the latest.
