### ISSUE TITLE
[1.15.2/0.11.863] Citizen cap research does not affect cap size in town hall gui

### ISSUE THREAD

**Issue by AlienXAXS** [ldtteam/minecolonies#4701]
### Minecolonies version
Version: 0.11.863 ALPHA

### Expected behavior
Upon researching up to +175 Citizen Cap, i expect to see more than a cap of 50 citizens in the town hall info GUI.

### Actual behaviour
Note: All research for citizen cap was done before the hotfix for citizen cap was pushed to github.
After upgrading to v 0.11.863 and checking the town hall, i noticed that the citizen cap says the max is 50, even though research is currently at +175.

I do wonder if this is a GUI bug instead of an actual enforced limit, as our citizen cap is currently at 92/50, but I am unsure how the colony got to this number (there are around 10 of us that play in this colony, so I am not always online to see when new citizens move in / are born)

The config file "maxcitizenpercolony" is set to 150.

Advise in Discord from SomeAddons "try firing/rehiring some worker and check again" did not fix the issue.

You can download the world here: https://www.playplex.media/minecraft/agn_mc_github_report_world.zip
The modpack being used: https://www.curseforge.com/minecraft/modpacks/agn-gaming-minecraft-modpack/files/2937296

### Steps to reproduce the problem
1) Research to more than +50 on citizen cap.
2) Check town hall to see max citizen cap.
3) Notice how the citizen cap does not relate to the completed research.

### Logs: Latest.log and crashlog at https://gist.github.com/
https://gist.github.com/AlienXAXS/48cdac3148beee581ab2ce56d37cc5dc

**Comment by Desim8r** [comment]
11.866-ALPHA with Structurize 10.305

Same issue on a server I'm playing on. Researched 3 citizen upgrades, each time the cap increases but then resets to 50 on server restart. The current max in the config is 75. 

maxcitizenpercolony = 75

**Comment by Inomutso** [comment]
I´m having the same since one of the last 0.11.8xx Alpha Releases.
As a result, i don´t get more citizens than 50. In my config I have 65 configured

**Comment by Raycoms** [comment]
fixed

**Comment by FeepoR** [comment]
My citizen cap is still stuck at 50. How did you fix it Raycoms?

> fixed

**Comment by Raycoms** [comment]
Are you on the newest?

**Comment by FeepoR** [comment]
I'm not sure. I'm sorry, I'm pretty new in the mod world. I'm currently playing in 1.14.4. Could you possibly point me in the right direction? I already tried editing the 'config' file, but nothing happened. Thank you!

> Are you on the newest?

**Comment by Raycoms** [comment]
oh 1.14 doesn't have any of this. =D You'd have to update to 1.15 for that =/

**Comment by FeepoR** [comment]
I dont think I can :/ I'm using 20 mods and some of them arent available for 1.15.. I just dont understand why I cant just expand the '50' limit directly in 1.14 :(

**Comment by AlienXAXS** [comment]
Does 1.14 even have the research stuff?
If not, then you'll need to modify your server config file for minecolonies to expand past 50 citizens.

I'm sure @Raycoms can correct me if im not quite right.

**Comment by Raycoms** [comment]
yeah, it's a server config file thing in 1.14

**Comment by FeepoR** [comment]
Hi guys, yeah I already tried before to modify the config file, but it didnt change anything. This is what i changed it to: (I changed the 50 to 200)

#Max citizens in one colony. [Default: 200]
	#Range: 4 ~ 500
	maxcitizenpercolony = 200
