### ISSUE TITLE
MalisisDoors compatibility

### ISSUE THREAD

**Issue by TheKrowi** [ldtteam/minecolonies#4702]
### Minecolonies version
Version: minecolonies-1.12.2-0.11.811-BETA-universal
Modpack: MC Eternal 1.3.5.3

### Expected behavior
- Builder builds building with doors, builder breaks doors to move them and places them again or stores them in his inventory for another build.

### Actual behaviour
- Builder builds building with doors, builder breaks doors **but with additional NBT data** to move them and places them again or stores them in his inventory for another build. When the player places and breaks door this does not happen.

**Data before breaking door by builder**
[CHAT] The data tag did not change: {Motion:[-2.2786001928954276E-9d,-0.0d,1.622391890578087E-8d],ForgeData:{thrower:"Krowi"},UUIDLeast:-5107144616847838309L,Health:5s,RelativeAABB:[-0.125d,0.0d,-0.125d,0.125d,0.25d,0.12499999999999822d],Invulnerable:0b,Air:300s,OnGround:1b,Dimension:0,PortalCooldown:0,Rotation:[288.58057f,0.0f],Thrower:"Krowi",UpdateBlocked:0b,FallDistance:0.0f,Item:{id:"minecraft:dark_oak_door",Count:1b,Damage:0s},UUIDMost:4010322374550636071L,Pos:[202.73851570610134d,65.9375d,9.29838081340925d],PickupDelay:0s,Fire:-1s,ForgeCaps:{"llibrary:extendedentitydatacapability":{}},Lifespan:6000,Age:41s}

**Data after breaking door by builder**
[CHAT] The data tag did not change: {Motion:[-1.3140797138299237E-10d,-0.0d,4.4556523639988285E-10d],ForgeData:{thrower:"Krowi"},UUIDLeast:-5023684647931000930L,Health:5s,RelativeAABB:[-0.125d,0.0d,-0.125d,0.125d,0.25d,0.125d],Invulnerable:0b,Air:300s,OnGround:1b,Dimension:0,PortalCooldown:0,Rotation:[175.91942f,0.0f],Thrower:"Krowi",UpdateBlocked:0b,FallDistance:0.0f,Item:{id:"minecraft:dark_oak_door",Count:1b, **tag:{item:431,redstoneBehavior:0,proximityDetection:0b,sound:"vanilla_door",openingTime:6,autoCloseTime:0,block:197,doubleDoor:1b,movement:"rotating_door"},** Damage:0s},UUIDMost:-2250664205057769295L,Pos:[202.8332173463168d,66.0d,7.192460202636389d],PickupDelay:0s,Fire:-1s,ForgeCaps:{"llibrary:extendedentitydatacapability":{}},Lifespan:6000,Age:44s}

**Comment by Raycoms** [comment]
Closed in favor of #4510
