### ISSUE TITLE
This block is missing its respective building, try restarting or loading a backup

### ISSUE THREAD

**Issue by DiabolosMan** [ldtteam/minecolonies#4703]
### Minecolonies version
Minecolonies version 0.11.862-ALPHA
Minecraft version 1.15.2
Forge version 3.11.47

### Expected behavior
I was trying to move my chickenherder's hut 2 layers below… and I was expecting it building moved 2 layers below.

### Actual behaviour
Right clicking on Building hut show the error message:
This block is missing its respective building, try restarting or loading a backup
Unable to to anything. In town hall, the chickenherder is still there but no more worker assigned to it

![BugChickenHerder2](https://user-images.githubusercontent.com/63854770/79988007-6f050f80-84ae-11ea-88c6-c73e0c081865.jpg)
![BugChickenHerder](https://user-images.githubusercontent.com/63854770/79988006-6ca2b580-84ae-11ea-9d83-0a8ec507b633.jpg)

### Steps to reproduce the problem
1) Build a ChickenHerder's hut lvl 5
2) Select reposition in building menu and move it 2 layers below using - (minus) sign)
3) Validate the new position.
4) The builder hut block is moved 2 layers below, good….
5) But to see it, I needed to dig the ground… So I destroyed the ground, where was located previously the hutblock
6) Then right click on the ChickenHerder block…. And there is the error message.
7) The worker changed apparence to a normal citizen, no more a chiken herderer

8) After that, I also used my pickaxe to take the ChickenHerder block; and move it back manually to the original position…. Now, the game considers that it is a new building and not lvl5 anymore.
9) I restarted the server, and in town hall, there is still one ChickenHerder somewhere in the void, but no more herderer and no more herder block linked to it

### What next
I already had this kind of issue when moving a building but was not a problem on my local game
Here it is a multiplayer world and restoring a backup is not an option as it means ruining what was done since yesterday for all players.
What can be done in minecolonies files to restore that building or make it disappear. I will have to rebuild but it will imply me only, not other players.

Thanks in advance

**Comment by kd5crs** [comment]
This happened to me and a player on a LAN server, it turned out we had different ALPHA versions. I guess close enough for most things to work but not all. Going to the latest version fixed it.

**Comment by DiabolosMan** [comment]
I was able to make this building disappear by destroying all blocks, replacing the buildinghut to the exact same location, start the building and cancel the building.
Then I had to rebuild again, lvl1, 2, 3 4 and 5. I tried to move down again and had exactly the same issue.
So I did again my trick to destroy everything, and then start from beginning 2 layers below.
So 100% reproductible.

**Comment by someaddons** [comment]
So your problem is with relocating/moving the hut right?

**Comment by DiabolosMan** [comment]
yes correct

**Comment by Kao713** [comment]
I'm having the same issue every time I try to move anything

**Comment by Raycoms** [comment]
fixed

**Comment by 123Tristan321** [comment]
I can't build the builders hut because of this error any ideas?
Its on my minecraft server

**Comment by MotionlessTrain** [comment]
Please don't comment on very old issues. This particular issue has been solved more than two years ago. You are probably running into a new one.

Please open another issue or rather go to our [discord](https://discord.minecolonies.com) for support
