### ISSUE TITLE
java.lang.NoClassDefFoundError: com/minecolonies/api/colony/permissions/Action

### ISSUE THREAD

**Issue by DiabolosMan** [ldtteam/minecolonies#4704]
### Minecolonies version
Minecolonies version 0.11.862-ALPHA
Minecraft version 1.15.2
Forge version 3.11.47

### Expected behavior
No crash

### Actual behaviour
Crash when right clicking on Builder Hut

### Steps to reproduce the problem
I logged in, did some chat then right click on builderhut => client crash
I restarted the game and it does not happened anymore

### Logs
- latest.log:
[2020-04-22-2.log](https://github.com/ldtteam/minecolonies/files/4516446/2020-04-22-2.log)

- crashlog:
[crash-2020-04-22_13.34.39-client.txt](https://github.com/ldtteam/minecolonies/files/4516397/crash-2020-04-22_13.34.39-client.txt)

**Comment by Raycoms** [comment]
Yeah its a forge modloading issue. Not our fault

**Comment by DiabolosMan** [comment]
ok ;-). thanks for the info. You can close ^^

**Comment by NielsPilgaard** [comment]
Do you happen to know if there is there we can do to help Forge fix this bug? :)

**Comment by Raycoms** [comment]
Maybe bother them about it

**Comment by NielsPilgaard** [comment]
Yikes, okay. I guess I'll just re-enable Colony protection, that ought to fix it. Thanks.
