### ISSUE TITLE
Leaving a colony message each time we log in for a colony over spawn area

### ISSUE THREAD

**Issue by DiabolosMan** [ldtteam/minecolonies#4705]
### Minecolonies version
All versions since a long time

### Expected behavior
No chat message everytime we log in about leaving the colony of another player that set it on spawn area

### Actual behaviour
[13:28:11] [Render thread/INFO]: Connecting to ##########.omgcraft.fr., 10037
[13:28:41] [Render thread/INFO]: Starting JEI...
.... Many logs.....
[13:28:45] [Render thread/INFO]: Starting JEI took 4.227 s
[13:28:46] [Render thread/INFO]: [CHAT] Farewell, you're leaving nicotontige's colony.

### Steps to reproduce the problem
1) Have a player setting a colony closed to the spawn :-(.   
2) Another player connect to the server, he always have the notification he is leaving the colony of this player

**Comment by DiabolosMan** [comment]
I have still the issue in version 0.11.886-BETA

**Comment by DiabolosMan** [comment]
The issue is still there in version 0.11.907-ALPHA
I also have the same issue when I go back from nether or ender.

**Comment by DiabolosMan** [comment]
Issue fixed in latest alpha. Thanks

**Comment by someaddons** [comment]
ye forgot to mention
