### ISSUE TITLE
Issues with some NPCs

### ISSUE THREAD

**Issue by dalekistler** [ldtteam/minecolonies#4707]
### Minecolonies version

Version: minecolonies-1.12.2-0.10.772-RELEASE-universal (From the Life in the Village curseforge/twitch modpack)

### Expected behavior

- One instance of every citizen rather than 3 or more in different positions. It can make building a problem, because you can hit them one time, but no matter how strong a sword, it only does 2 1/2 hearts. You cannot push them, it's almost as if they're void.-

### Actual behavior
- There are multiple instances of a person at times, the most seen at once was five. The most common workers this happens to is the Deliveryman and the Builder (See below an example with deliveryman)
![image](https://user-images.githubusercontent.com/54081261/79997895-086cfb00-8488-11ea-8457-82af7445bd4c.png)

### Steps to reproduce the problem

1. Find a non-moving NPC.
2. Fly out of the chunk and back to see if they disappear.
3. For me, they haven't, and that's the furthest I've got.

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: N/A
- crashlog: N/A

**EDIT** Was fixed a while ago

**Comment by someaddons** [comment]
fixed in the latest a while ago

**Comment by Raycoms** [comment]
That should be fixed in the following versions =)

**Comment by dalekistler** [comment]
> That should be fixed in the following versions =)

Thank you. Question regarding the difference though, if I just removed the mod and put the latest version, would it likely corrupt or cause issues in the game?
