### ISSUE TITLE
Switching mod versions

### ISSUE THREAD

**Issue by dalekistler** [ldtteam/minecolonies#4710]
### Minecolonies version

Version: minecolonies-1.12.2-0.10.772-RELEASE-universal (From Life in the Village curseforge/twitch modpack)

### Expected behavior

I want to change the version so the issue with the null citizens goes away, but I'm afraid going to minecolonies-1.12.2-0.11.841-ALPHA-universal.jar might corrupt or mess up the world or mods. Would it?

**Comment by Raycoms** [comment]
Just do it, nothing bad will happen through this.

**Comment by dalekistler** [comment]
> Just do it, nothing bad will happen through this.

Thanks for the help.
