### ISSUE TITLE
Deliveryman stuck in Warehouse

### ISSUE THREAD

**Issue by wafebreaker** [ldtteam/minecolonies#4712]
### Minecolonies version
minecolonies-1.12.2-0.11.804-RELEASE

Version: 
MC Eternal 1.3.5b

### Expected behavior
Delivery Man walks normaly and not get stuck in warehouse

### Actual behaviour
The Delivery man get stucked in warehouse moving from one spot to another within 4 blocks

Both times i recognize this behavior the builder needed oak doors

Video: https://youtu.be/fJyyaXyc0Gs

### Steps to reproduce the problem
1. Builder needs some items (in my case both times they needed oak doors)

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: https://gist.github.com/wafebreaker/ab3024183343635ee2f85e94a6386660
- crashlog:

**Comment by Raycoms** [comment]
Do those doors have some weird nbt values from Malisis or so?

**Comment by wafebreaker** [comment]
How can i look this up? These are normal vanilla oak doors

**Comment by Raycoms** [comment]
extended tooltip with f3 options

**Comment by wafebreaker** [comment]
It says: 

Oak door ( # 0324)
minecraft:wooden_door
Fuel Details
Burn Time 300 ticks
Ore Dictionary names:
-doorWood
minecraft:wooden_door
