### ISSUE TITLE
Smelter Level 3 does not double ingots

### ISSUE THREAD

**Issue by kd5crs** [ldtteam/minecolonies#4713]
### Minecolonies version

Version: minecolonies-0.11.863-ALPHA-universal

### Expected behavior

- The level 3 Smelter is supposed to have a 100% chance of doubling ore.

### Actual behaviour

- The level 3 Smelter smelts the ore they are given, at 1:1. I tried watching the furnace, not watching the furnace, and leaving it alone and only checking after the ingots were moved by the Delivery Man to the Warehouse, in each case the ore to ingots was just a normal 1:1. 

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: https://gist.github.com/kd5crs/1553394d72d87f6faabc437e47909452
- crashlog:

**Comment by Raycoms** [comment]
The doubling occurs when the works retrieves the items from the furnace.
Did you check this?

**Comment by kd5crs** [comment]
Whoops, I see you are correct and it is working.

**Comment by drakray** [comment]
sorry to piggyback on this @Raycoms , but in minecolonies-1.18.1-1.0.463-alpha Smeltery seems to not double ore.
I gave 20 raw gold and 8 ancient debris to a lvl3 Smeltery, and when I checked later in the Warehouse, there was 20 gold ingot and 8 netherite scrap.
I checked everywhere else and no sign on doubling(nor is there anyone who used them)
Any ideas?

**Comment by drakray** [comment]
Also, playing on a DS, on forge 39.1.2
I retested:
Smeltery lvl/theme: 4, Fortress
Smelter stats: Athletics19, Strengh12
I gave 8 raw copper and 8 raw iron, got 8 copper ingot and 8 iron ingot
Tried ore block too, same result

**Comment by Talyda** [comment]
You realise this issue is neaerly 2 years old, right?
And things can (and do) change in 2 years?
Ask for help on discord before commenting on things this old.
Things don't work the same in 1.18. The smelter uses fortune now for ore blocks, not raw ore. And fortune doesn't work on debris.

**Comment by drakray** [comment]
Yeah sorry, I have the habit of going to the issue trackers, not Discord for these type of report lol
Thank you for the info, i'll check on the Discord from now on
