### ISSUE TITLE
Deliverymen stay in warehouse

### ISSUE THREAD

**Issue by outnampichtim** [ldtteam/minecolonies#4714]
### Minecolonies version

Version: 0.11.865-ALPHA-universal

### Expected behavior

- Deliverymen walking around and collecting items
.

### Actual behaviour

- They stand around all day doing noting except fulfilling requests. it began during the upgrade to level 3 of the warehouse

![2020-04-22_21 23 24](https://user-images.githubusercontent.com/63748997/80026971-506d3b80-84e3-11ea-995f-3b953f8cda49.png)

### Steps to reproduce the problem

1. I don't really, know try upgrade the warehouse to level 3
2. 
3. 
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

**Comment by Raycoms** [comment]
Please to a /mc colony rs-reset, the last update might've caused this to happen temporarily.
Does this solve it?

**Comment by outnampichtim** [comment]
It worked, thanks
