### ISSUE TITLE
can you make another build style?

### ISSUE THREAD

**Issue by KingOnSki** [ldtteam/minecolonies#4716]
I like to see an under water build style, with big glass domes were the building would be build inside of. And the supply ship can be like a submarine. The town hall will be partly above the water but mostly underwater.

**Comment by Asherslab** [comment]
the mod is available in 1.14.4, it's just EOL
we also don't take schematic requests, schematics are able to be made by all players

**Comment by Raycoms** [comment]
Schematics are contributed by the community
