### ISSUE TITLE
Barbarian dont spawn (even in creative)

### ISSUE THREAD

**Issue by odiseus22** [ldtteam/minecolonies#4721]
i try to spawn barbarians or pirates
by using the spawners (the eggs) in creative, they spawn for 0,5 seconds and disappear and i got a error msg when trying to make a raid-now and raid-tonight dont spawn barbarians either
### Minecolonies version
 1.12.2

Version: minecolonies-1.12.2-0.11.804-RELEASE-universal

### Expected behavior
 i expect to the barbarians appear when i spawn them in creative, and when a raid start the barbarians or pirates appear

-   

### Actual behaviour
 if i spawn a barbarians/pirate in creative (the egg shape spawner) they appear for 0,5 secs and then disappear, if i try to start a raid-now, i got an error in the chat if i use raid-tonight i dont get the error but the mobs dont appear

- 

### Steps to reproduce the problem
 

1.  start minecraft with my same mods 
2.  go single player creative mode or server (i tested both)
3.  create a town hall, make the town hall and builder huts  
4. ... Profit  try the comand raid-now, or raid-tonight or try to spawn in creative the mobs (pirate/barbarian, it dont work with all the variations)

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
[latest.log](https://github.com/ldtteam/minecolonies/files/4521087/latest.log)
[debug.log](https://github.com/ldtteam/minecolonies/files/4521088/debug.log)

- crashlog:

**Comment by Raycoms** [comment]
Yes, they only spawn in raids. On purpose. Eggs were added for testing purposes (Creative only items after all)

**Comment by odiseus22** [comment]
and what about the comand raid-now?

**Comment by Raycoms** [comment]
Triggers a raid if your colony fulfills the requirements for a raid

**Comment by odiseus22** [comment]
aa, oky, thanks for the feedback, in any case its seems not intuitive to get an error msg, maybe to get a msg saying your village dont fulfils the requirements can help to other players in a future, the mod is really cool, have a good day

**Comment by Raycoms** [comment]
Yeah those are creative commands we've added for debugging purposes mostly, that's probably why they don't do that =)

**Comment by someaddons** [comment]
if you got an error with the command you probably didnt use the right syntax for it

**Comment by odiseus22** [comment]
i wrote /mc raid-now  and /mc raid-tonight in the latest log at the end you can see the error wrning at time [04:28:00]

**Comment by someaddons** [comment]
try /mc colony raid colony: 1
(if 1 is your colonies id)

**Comment by odiseus22** [comment]
oky i wil try, thanks

**Comment by odiseus22** [comment]
![image](https://user-images.githubusercontent.com/50801109/80077269-a366e300-8523-11ea-8a49-ac04e6f19ddb.png)
i wrote : /mc colony raid colony: 1          (this colony has 14 villagers, 4  towers, 1 barracks and more civilian buildings)

**Comment by someaddons** [comment]
not sure what the issue is, updating to the latest 1.12 might help

**Comment by odiseus22** [comment]
oky, i will try a beta version, i was using the last release, thanks for the feedback, your mod is really cool, keep doing it  ;)
