### ISSUE TITLE
Restaurant Stone Level 5 missing wall

### ISSUE THREAD

**Issue by TheKrowi** [ldtteam/minecolonies#4726]
### Minecolonies version
Version: minecolonies-1.12.2-0.11.811-BETA-universal
Modpack: MC Eternal 1.3.5.3

### Description
Is it possible the level 5 stone restaurant has a missing wall? Building it does indeed miss the wall so it's not only the preview.
![2020-04-23_15 33 25](https://user-images.githubusercontent.com/22818581/80105139-6ed14680-8578-11ea-9302-2e87d85c2a18.png)
![2020-04-23_15 37 11](https://user-images.githubusercontent.com/22818581/80105141-6f69dd00-8578-11ea-9297-425271c443d5.png)

**Comment by Raycoms** [comment]
report it at #4536 please
