### ISSUE TITLE
Decoration controller, miss upgrade button and repair button don't make anything (sometimes gones too)

### ISSUE THREAD

**Issue by Alfakiller2001** [ldtteam/minecolonies#4729]
### Minecolonies version

Version: minecolonies-0.10.771-RELEASE-universal

### Expected behavior

- I build Fortress wall 1, enter in the GUI of the Decoration Controller, press "Upgrade" Button, a builder come to upgrade the wall to Fortress wall 2, if is damaged, press the "Repair" Button and the builder come to repair the structure.

### Actual behaviour

- I build Fortress wall 1, enter in the GUI of the Decoration controller, and realize there is not a "upgrade" button and sometimes the "Repair" button is gone too, "Repair" button don't make anything when is pressed.

![image](https://user-images.githubusercontent.com/64235318/80162572-01eb9a00-85d4-11ea-9696-a79d9e5bd450.png) I typed the number two trying to fix it, in other five walls i don't change anything and the issue don't dissapear.

### Steps to reproduce the problem

1. Build a Fortress wall 1 (i think happens to more walls, i try with this wall)
2. Enter in the GUI of the Decoration Controller
3. There is not a "Upgrade" button, the "Repair" button don't make anything and some times is gone.
4. ... Profit (I don't know what I'm supposed to have I wrote here sorry)

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

**Comment by mcmanustfj** [comment]
Seconded, see: https://i.imgur.com/20iCvMk.png

**Comment by Alfakiller2001** [comment]
My bad, the issue it's fixed in the Alpha's version.

Problem: Works in NEW WORLDS, if you try fix your world, the walls already placed still broken
                                           PD: Idk if you build a new one in a broken world, what happens

**Comment by Alfakiller2001** [comment]
Then I close the report.
