### ISSUE TITLE
addOfficer doesn't overwrite existing entry of that name

### ISSUE THREAD

**Issue by xenoflot** [ldtteam/minecolonies#473]
### Minecolonies version

minecolonies-1.10.2-0.6.2305

I added myself to a player's colony earlier tonight, using addOfficer. When I got sick of the builder-spam I went to remove myself but I clicked the demote button instead of delete.

re-running the addOfficer command gives the usual success message however the permission level isn't changed; I'm stuck at Friend.

Please have each run of addOfficer overwrite any existing perms for that username.

Cheers!

**Comment by forReason** [comment]
rather a message like "Officer X already exists. use /mc removeofficer or /mc elevateOfficer instead"

* fictional commands

**Comment by Raycoms** [comment]
Should be fixed.
