### ISSUE TITLE
Error when move a building

### ISSUE THREAD

**Issue by Alfakiller2001** [ldtteam/minecolonies#4730]
### Minecolonies version

Version: minecolonies-0.11.871-ALPHA-universal

### Expected behavior

- When you move's a building, the builder deconstruct de building and recontruct in the new position

### Actual behaviour

- When you move a building, the hut block teleports and you can't open the hut GUI and pop up an error in chat duplicated

![image](https://user-images.githubusercontent.com/64235318/80172451-54858000-85ed-11ea-98f5-74e40d344e6c.png)

### Steps to reproduce the problem

1. build a builder hut
2. try to move it
3.  the hut block teleports, the npc lost the job and when try enter in the hut pop up an error
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

**Comment by Raycoms** [comment]
fixed
