### ISSUE TITLE
Sort function not working

### ISSUE THREAD

**Issue by wikidone** [ldtteam/minecolonies#4732]
### Minecolonies version

Version: minecolonies-0.11.871-ALPHA-universal

### Expected behavior

Sort function not working in warehouse

### Actual behaviour

When hitting sort, warehouse inventory sorts.

### Steps to reproduce the problem

1. Sometimes this works, sometimes this doesn't, it would be great if some type of conformation message was displayed when hitting sort, or if the button gave some type of animation when pressed to know its working.

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
[latest.log](https://github.com/ldtteam/minecolonies/files/4526878/latest.log)

- crashlog: no crash logs

**Comment by lexustec** [comment]
Good Morning Wikidone,

The confirmation of the Sortfunction is the Audioeffect on the Buttonclick.

Can You tell me if it is on Singleplayer or on Server Environment ?

The Sort function Button displays a  A^ if it is sorting by Name Ascending ( First word after this Second word ), 
It Displays Av if it sorts by Name Decending,

Then  1^ if it sorts by Number Ascending means lowest count on top regardless the Name,
then 1v if it sorts by Numver Descending means highest count on top.

At last there is the Option for not sorting which is indicated by  v^ that means "take as You get it " it takes all the vales and doesnt sort it.. sometimes this Mode is equal to other listings depending which stack is in which rack... 

Please have a look on the Button itself and test it out :-)

Many greetings

lexarion

**Comment by Raycoms** [comment]
@wikidone do you mean the warehouse sort button (the one to sort the itemstacks in the racks) or the sort button in the overview window?

**Comment by wikidone** [comment]
Hello,

My sort button does not show any of those symbols on it, and this is in a server environment.

**Comment by wikidone** [comment]
The warehouse sort button. I am not aware of the other sort button, where is that located?!

**Comment by Raycoms** [comment]
Added
