### ISSUE TITLE
1.15.2 TechColonies Crash Report

### ISSUE THREAD

**Issue by SadHorizion77210** [ldtteam/minecolonies#4733]
### Minecolonies version

Version: Minecolonies ver 0.11.858 ALPHA

### Actual behaviour

- 

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:https://gist.github.com/SadHorizion77210/3a3f10ef14e95760afb11a93f0f92556

**Comment by Raycoms** [comment]
Yes,this is some weird issue forge has. Redownload the mod will fix this.
