### ISSUE TITLE
[1.15.2] Asian Barracks Towers not oriented correctly

### ISSUE THREAD

**Issue by b52src** [ldtteam/minecolonies#4734]
### Minecolonies version

Version: 
minecolonies-0.11.872-ALPHA-universal.
### Expected behavior

-  when you build on the barracks tower to the barrics that it matches up correctly they end up getting built rotated

### Actual behaviour

-  When you build the barracks towers they end up being rotated 90 degrees and do not match the build. I am using the Asian Style and the entrance of my Barracks is facing South. on my barracs for example the tower on my south west corner ends up having the entrance facing West Rather than North

- another issue i have seen on repositioning builds is when rotating the it dose not end up being built in the repositioned location  and puck a different orientation than what you selected, if needed i can open a separate issue ion that though

Will add a screen shot one i rebuild one of the towers.
### Steps to reproduce the problem

1.  hit build on one of the barracks towers 
2.  Once built the tower is facing 90 degrees in the wrong direction so the walls also do not align correctly as well.

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

**Comment by b52src** [comment]
screen shot: [https://i.imgur.com/nF0A0pz.jpg](https://i.imgur.com/nF0A0pz.jpg)

**Comment by Raycoms** [comment]
Can you please add this to the schematics issues issue?
