### ISSUE TITLE
Minecolonies NPC's walks extremely wrong when outside of chunk. MULTIPLAYER.

### ISSUE THREAD

**Issue by DANIELAG3** [ldtteam/minecolonies#4735]
Hey so ive been having some issues with my NPC's on the multiplayer server i play on we use Sponge as our plugin thing and when we walk outside of a chunk from it it moves extremely slow. we have looked for a fix in the Sponge configs but the minecolonies section isnt there?
### Minecolonies 1.12.2-0.11.804-RELEASE

Version: 1.12.2-forge

### Expected Behaviour:
 NPC's walking normaly when you are more than one chunk away.

### Actual behaviour
NPC's walk extremely slow when outside of their chunk around 1 millimeter per 3 second.
 

- 

NPC's walk very slowly when you move away from them.

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit

**Comment by someaddons** [comment]
you gotta add the stuff to the sponge config manually:
```
For Sponge servers you need the following set:

entity-activation-range {
    minecolonies {
        defaults {
            misc=512
            monster=24
        }
        enabled=false
        entities {
            archerbarbarian=24
            archerpirate=24
            arbarian=24
            chiefbarbarian=24
            chiefpirate=24
            citizen=512
            fishhook=512
            pirate=24
        }
    }
}
```

**Comment by DANIELAG3** [comment]
where should it be put though?

**Comment by someaddons** [comment]
sponge config

**Comment by DANIELAG3** [comment]
jesus where in the sponge config
