### ISSUE TITLE
Fix not working!

### ISSUE THREAD

**Issue by DANIELAG3** [ldtteam/minecolonies#4736]
you gotta add the stuff to the sponge config manually:

For Sponge servers you need the following set:

entity-activation-range {
    minecolonies {
        defaults {
            misc=512
            monster=24
        }
        enabled=false
        entities {
            archerbarbarian=24
            archerpirate=24
            arbarian=24
            chiefbarbarian=24
            chiefpirate=24
            citizen=512
            fishhook=512
            pirate=24
        }
    }
}

This supposed fix was made to fix the thing but its not working! NPC's are still moving slowly and its getting very annoying!
First of all:
1: where are we supposed to put it?
2: dont close so fast please some people needs to ask questions.
3: give us a screenshot where to put it? were pretty new to this stuff.

**Comment by Raycoms** [comment]
This is not our doing, this is what the plugins you have installed do to our entities =D

**Comment by Raycoms** [comment]
This is nucleus afaik

**Comment by DANIELAG3** [comment]
problem is we got no plugins only Sponge so we can get spawn protection later on.

**Comment by someaddons** [comment]
you can use minecolonies for that

**Comment by DANIELAG3** [comment]
and tpa and stuff?

**Comment by Raycoms** [comment]
There is code to teleport to other peoples colonies through townhalls =D

**Comment by DANIELAG3** [comment]
oh ok

**Comment by DANIELAG3** [comment]
you still need OP for that though.

**Comment by DANIELAG3** [comment]
AND we have several colonies that are enemies.

**Comment by Raycoms** [comment]
yes, you have to setup each other as officers to teleport to eachother

**Comment by DANIELAG3** [comment]
how do we do that?

**Comment by DANIELAG3** [comment]
and if you dont know were trying to play this in survival without everyone having Operator

**Comment by Raycoms** [comment]
just have two colonies add eachother as officers. Then build the townhall and you can teleport through the townhall GUI to eachother.

**Comment by Raycoms** [comment]
But yes, the issue with the colonists you are having is a sponge issue where they tune down entities for performance reasons (I suggest installing the performant mod for that).

I think @Wissi knows where to put that config.

**Comment by DANIELAG3** [comment]
Raycoms were trying to have a colony war thing going on

**Comment by DANIELAG3** [comment]
alright so we removed sponge and now server wont start up. it seems we need sponge.

**Comment by DANIELAG3** [comment]
so @Raycoms could you please direct us to where we put the fix for the NPC's?

**Comment by Raycoms** [comment]
/config/sponge/global.conf

**Comment by Raycoms** [comment]
![image](https://user-images.githubusercontent.com/6438347/80233915-2afd4080-864f-11ea-88e0-d9023554d204.png)

**Comment by DANIELAG3** [comment]
yes i know that but problem is does it matter where we put it?

because we used that and it didnt do anything?

**Comment by Raycoms** [comment]
did you restart after setting it?

**Comment by DANIELAG3** [comment]
yes we did

**Comment by DANIELAG3** [comment]
it didnt do anything tbh

**Comment by Raycoms** [comment]
there is an entity-activation-range setting already, don't add a new one, add the content to the existing setting. Did you do that?

**Comment by DANIELAG3** [comment]
where do we find that?

**Comment by Raycoms** [comment]
I added it to the screenshot

**Comment by DANIELAG3** [comment]
ok do we just replace it or?

**Comment by DANIELAG3** [comment]
also please answer me in Discord in the Norwegian Futanari guy. i think it would be easier if we just screenshared you it.
