### ISSUE TITLE
Can't upgrade university / other building gates are broken

### ISSUE THREAD

**Issue by bbbower** [ldtteam/minecolonies#4738]
### Minecolonies version

Version:  minecolonies-0.11.827-ALPHA-universal
Pack; Jnem2 .6.0 (1.15.2)
### Expected behavior
Should use player head, or any head.  
After research buildings should be build-able.

Trying to upgrade the university (fortress) to level 4 requires a player head.
Trying to build stone smelter / smeltery after researching appropriate research to unlock.

### Actual behaviour

When given a head of any kind including player's builder continues to request it and does not reckognize it as the item he needs.
When trying to build buildings stone smeltery and smeltery after researching gives generic message to build university and unlock barracks.
![unknown](https://user-images.githubusercontent.com/15827105/80249129-49f3d680-863f-11ea-850f-d5c5918a9863.png)

**Comment by Raycoms** [comment]
Can you please add this to the schematics issues issue?
