### ISSUE TITLE
Disabling block protection not working?

### ISSUE THREAD

**Issue by xenoflot** [ldtteam/minecolonies#474]
### Minecolonies version

minecolonies-1.10.2-0.6.2305

I have the following config set on both server and client:
    B:enableColonyProtection=false

However players not on the town hall permissions list are unable to break blocks in the area. Adding myself as an officer allowed that.

Is this config option for that purpose? Is it supposed to be functional in this version?

Cheers!

**Comment by Raycoms** [comment]
It normally should work. Did you restart the server?

2017-01-18 17:09 GMT-02:00 xenoflot <notifications@github.com>:

**Comment by xenoflot** [comment]
This is on our production server. The config hasn't been adjusted since we went live and it reboots twice daily.

**Comment by Raycoms** [comment]
Hmm that's strange. We will do some tests and will try to reproduce it.

2017-01-18 23:24 GMT-02:00 xenoflot <notifications@github.com>:

**Comment by Raycoms** [comment]
Okay I tried to reproduce it on a server here is it still not working?

**Comment by Raycoms** [comment]
Please reopen if able to reproduce.
