### ISSUE TITLE
NPE for Farmer AI: "My AI has run into an issue"

### ISSUE THREAD

**Issue by Egaro555** [ldtteam/minecolonies#4740]
### Version
Minecraft 1.15.2 (on multiplayer server)
Mod pack Valhelsia 2: 2.1.6
Minecolonies version:  0.11.8.31
Simple Farming: 1.15.2-1.2.7

### Expected behavior
Just that AI don't have falure

### Actual behaviour
I have replace seed of 2 farms:
I replace Bettroot Seeds (minecraft item) by Broccoli Seeds (Mod: Simple Farming)
and replace Corn Seeds (Mod: Simple Farming) by Radish Seeds (Mod: Simple Farming)

After that Niamh request me:
![image](https://user-images.githubusercontent.com/23615953/80258959-c78e0580-8684-11ea-9760-017094d99e4f.png)

### Steps to reproduce the problem
Maybe try to use Broccoli Seeds on farm because Niamh don't place it (Broccoli Seeds stay in Niamh inventory) and she place Radish Seeds correctely.

### Logs: Latest.log and crashlog at https://gist.github.com/
https://gist.github.com/Egaro555/302532cabb61c305aef9e8900e69e58b
conatines:
- debug.log
- latest.log
- minecolonies-latest.log (contain only minecolonies logs of latest.log)
- exception.log (contain only the NPE stacktrace)
- minecolonies-common.toml
- world/minecolonies/colonies.dat (named world_minecolonies_colony.dat) in base64
 -world/minecolonies/colony1_0.dat (Niamh's colony) in base64

thank you very much for this awesome mod
Good luck ;)
and sorry if my english is too bad

**Comment by Raycoms** [comment]
Can you update to the latest version and retry (please with new log then too)?

**Comment by Egaro555** [comment]
I can't reproduce the bug (in 0.11.8.31) so I don't think I will reproduce it in the latest version

**Comment by Raycoms** [comment]
Neither with those modded seeds?

**Comment by Egaro555** [comment]
no and after restart Broccoli Seeds work correctly

**Comment by Raycoms** [comment]
Okay, I'll close this then until there is a reproduce with the newest version.
