### ISSUE TITLE
When you move a building, the builders don't delete the original building

### ISSUE THREAD

**Issue by Alfakiller2001** [ldtteam/minecolonies#4745]
### Minecolonies version

Version: minecolonies-0.11.874-ALPHA-universal

### Expected behavior

- When you move a building, the builders delete the original building, and reconstruct it in the new place

### Actual behaviour

- When you move a building, the builders don't delete the original building, appears the construction tape, the builder aproach, and the construction tape dissapear

### Steps to reproduce the problem

1. build a builder hut, build any hut
2. try to move the hut
3. the original hut is not deconstructed
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

**Comment by domek16** [comment]
I have the same problem
+1
