### ISSUE TITLE
Crash when colonist dies of arrow

### ISSUE THREAD

**Issue by destrofer** [ldtteam/minecolonies#4748]
### Minecolonies version 

Forge: 1.15.2-31.1.48 / 1.15.2-31.1.49
Version: 0.11.871-ALPHA / 0.11.874-ALPHA

### Expected behavior
Game continues to run.

### Actual behavior
Game crashes when colonist is killed by arrow. At least this happened last 3 times (2 times were 15 seconds after loading save).

Screenshot made after minecraft froze and right before it crashed:
![Annotation 2020-04-25 143319](https://user-images.githubusercontent.com/2089465/80278878-77ee1f00-8702-11ea-9e9a-8258fda2d45c.png)

### Steps to reproduce the problem

1. Make pirates attack your colony
2. Wait till an archer pirate kills a colonist.

I don't know if it was actually a pirate who killed colonist, but it happened during a pirate attack.

Also it might be that colonist must be a deliveryman since it happened all 3 times only after my deliveryman got killed by arrow.

### Logs
- crashlog: [crash-2020-04-25_14.32.47-server.txt](https://gist.github.com/destrofer/7fad590a7198073dc0161d7950057c2d)

**Comment by Cap-Salt** [comment]
I had the problem too

**Comment by Raycoms** [comment]
Anyone can reproduce this? (I can't)

**Comment by Cap-Salt** [comment]
I can try to record it

**Comment by Raycoms** [comment]
record doesn't help, a world where it will happen the next time a worker does -> helps

**Comment by destrofer** [comment]
I can pack my save with all mods (twitch instance) and whatnot if it really helps. Though I already updated colonies to 877.

**Comment by Raycoms** [comment]
Yeah, just the world should be fine

**Comment by destrofer** [comment]
There you go: [save.zip](https://www.dropbox.com/s/osp3cif93ciea2x/save.zip?dl=0)

**Comment by MCChiter** [comment]
i shall add to the issue. whenever colonist dies by any means: Starvation, potions of harming, anything else, game freezes and implodes, using valhelsia 2 modpack. providing food also did not help to resolve my issue
