### ISSUE TITLE
Upgrade Townhall to Level 2 | Fail to upgrade because its not the same spot and rotation

### ISSUE THREAD

**Issue by f0kx** [ldtteam/minecolonies#4749]
### Minecolonies version

Version: minecolonies-0.11.871-ALPHA-universal

### Expected behavior
When i normally upgrade a building it will take the same spot and same rotation

### Actual behaviour
Townhall 1 to Townhall 2 upgraded to level 2 and rotated 180 degrees and out of position!  

### Steps to reproduce the problem
1. I had an old version i think minecolonies-0.11.866-ALPHA-universal 
2. when i first build the townhall than upgrade the version to .871 
3. and want to upgrade it and this happens!

### Logs: Latest.log and crashlog at https://gist.github.com/
No crashlogs because there is no crash!

**Comment by Raycoms** [comment]
Yeah, sometimes the version you had probably had a wrong rotation in it initially which was fixed by now.
Can you please double check with the buildtool if when you go through the list it changes?

**Comment by f0kx** [comment]
"Can you please double check with the buildtool if when you go through the list it changes?" what do you mean with that?

**Comment by f0kx** [comment]
so you say it is fixed? so when i will upgrade to newer minecolonie version there is not such a bug anymore?

**Comment by Raycoms** [comment]
get a townhall block (there is a recipe, buildtool in middle and top slot rest planks) -> Then click with the buildtool select the townhall and select levels 1-5 to see if it rotates when you do so.

**Comment by f0kx** [comment]
https://imgur.com/a/HSVVgDi no recipe like you said
also when i click on JEI there is no recipe

**Comment by Raycoms** [comment]
did you place the supplycamp/ship in survival to obtain the townhall?

**Comment by f0kx** [comment]
yes i create a supplycamp and than i get the townhall in rack

**Comment by f0kx** [comment]
so my only question is hen i update my minecolonies version to a newer one will i get also this bug that my buildings get out of rotation only by pressing upgrade button in build option thats all i want to know??

**Comment by Raycoms** [comment]
No, this happened because it was wrong in the old version, this should not happen again with new buildings.
