### ISSUE TITLE
PLEASE HELP

### ISSUE THREAD

**Issue by LadyUmbreon** [ldtteam/minecolonies#475]
### Minecolonies version

version 1.10.2 or curse X.X.XX

### Expected behavior

- im building town hall 5 and my builder has what hes requested. he should keep building

### Actual behaviour

- instead he stands there all day and does nothing. he wont continue building
ive tried multiple things to fix it

1. fired and rehired multiple times
2. killed and replaced him
3. emptied all of his inventory and put in the requested items again
4. cancelled the project and requested it again.

still nothing! help please

**Comment by LadyUmbreon** [comment]
he also seems to need multiple armour stands and armour for the same spot. he just stacks them?

**Comment by forReason** [comment]
please have a look at #457 workaround is to turn manual worker assignment on in the townhall fire and hire him. also put all needed materials into his inventory. I have created fix #471 but it needs approval first :(

**Comment by Raycoms** [comment]
You used the newest version on curse?
Because my townhall level 5 build without any problem.

**Comment by Raycoms** [comment]
everytime you hire/fire him he will build the entities again.
