### ISSUE TITLE
Fisher always trying fishing on slabs

### ISSUE THREAD

**Issue by Cap-Salt** [ldtteam/minecolonies#4750]
### Minecolonies version

Version: minecolonies-0.11.874-ALPHA-universal

### Expected behavior
Fisher fishing in ocean and gets food and other stuff

- 

### Actual behaviour
The fisher throws his rod on its own building (mainly on slabs). Sometimes he throws the rod in the water and then it works perfectly, but after a a few throws he walks around and throws it on the slabs agian :/. After each failed throw he runs around in his building or swims arbitrarily in the water.

- 

Video coming soon

### Steps to reproduce the problem
Simply build a fisher in medival oak style on tier 2

1. Build a medival oak fisherhut on tier 2
2. assign a worker and give him a rod
3. look what he is doing

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:[latest.log](https://github.com/ldtteam/minecolonies/files/4532983/latest.log)
- crashlog:

**Comment by Cap-Salt** [comment]
Pls fix that my colonists getting hungry :smile:

**Comment by Raycoms** [comment]
I checked this out and he was fairly fine, not perfect, but most of the times he fished quite well. Navigation in the three dimensional always changing world of minecraft is not easy and sometimes the behaviour might seem wonky. But that cannot always be avoided. What matters is that the workers recover and bring home some fish =)
