### ISSUE TITLE
Deliveryman ai run into an issue

### ISSUE THREAD

**Issue by Cap-Salt** [ldtteam/minecolonies#4755]
### Minecolonies version

Version: minecolonies-0.11.877-ALPHA-universal

### Expected behavior

- 

### Actual behaviour

![2020-04-25_19 34 01](https://user-images.githubusercontent.com/62767037/80286796-c06f0200-872d-11ea-8993-34d96f59d54f.png)
- 

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
[latest.log](https://github.com/ldtteam/minecolonies/files/4533636/latest.log)

- crashlog:

**Comment by Raycoms** [comment]
Yeah, this is due to some backwards compatibility issues we had, please run once /mc colony rs-reset to solve it.

**Comment by Cap-Salt** [comment]
Okay :)
