### ISSUE TITLE
1.15.2 Schematic University Fortress Needs  Fixing I believe 

### ISSUE THREAD

**Issue by Howman** [ldtteam/minecolonies#4757]
Version: minecolonies-0.11.877-ALPHA-universal

1.15.2 Schematic university Fortress
Version 1 and 2 of Schematic are like 3 blocks off of matching to other Schematics when joining to other sides of wall Left,right but versions 3,4,5 are fine and match
Level 1
![2020-04-25_14 01 12](https://user-images.githubusercontent.com/2965824/80288214-77ef1e80-8704-11ea-9592-0daa4fa1fee1.png)
Level 2
![2020-04-25_14 30 54](https://user-images.githubusercontent.com/2965824/80288219-89d0c180-8704-11ea-8178-1940c5951ddc.png)
level 3
![2020-04-25_14 31 44](https://user-images.githubusercontent.com/2965824/80288225-95bc8380-8704-11ea-8e0b-f4bbd40ba394.png)
level 4
![2020-04-25_14 32 18](https://user-images.githubusercontent.com/2965824/80288229-a66cf980-8704-11ea-8d41-0521d2d8e687.png)
level 5 Is not very different from level 4 ( wall portion )

**Comment by Raycoms** [comment]
Please report in the schematic issues collect issue.
