### ISSUE TITLE
Stock window not showing all items if multiple stacks of the same item are in the same rack

### ISSUE THREAD

**Issue by ToMe25** [ldtteam/minecolonies#4758]
### Minecolonies version
Version: 0.11.880

### Expected behavior
I expect the Stock window to show the amount of all items of the same type added together.

### Actual behaviour
If more than one stack(doesn't have to be a full stack) of the same type of item is in the same rack, it only counts one of the stacks.
Under some circumstances it also shows more items of a type than there are, but i can't reproduce that yet.

### Steps to reproduce the problem
1. Build a warehouse(i tested it with nordic and fortress level 2)
2. distribute a stack of items into multiple slots of the same rack
3. go to the stock window in the warehouse block
4. see only some of your items

### Logs: Latest.log and crashlog at https://gist.github.com/
- latest.log:[ByrpvEJA](https://pastebin.com/ByrpvEJA)
- crashlog: Not a Crash.

**Comment by lexustec** [comment]
Hey ToMe25,

Which Stock window You mean. At the moment we have two Stock Windows

One is labeled Inventory and one which has the Chest icon.

The chest icon at the moment can not count the Inventory of the central Block ( will fix that soon )

The inventory Button counts only the Items inside the central block.

**Comment by ToMe25** [comment]
This issue is with the one with the Chest Icon.

**Comment by lexustec** [comment]
I am fixing it. it shows always all identical stocks together added up. so if You have 3 stacks of Cobble it ads it up so You know You have 192 Cobblestone.

**Comment by ToMe25** [comment]
> it shows always all identical stocks together added up. so if You have 3 stacks of Cobble it ads it up so You know You have 192 Cobblestone.

I know that it does that, except that it currently isn't doing that if more than one stack of the same item is in the same rack. thats what my pr changes.
