### ISSUE TITLE
New achievements: [$15 awarded]

### ISSUE THREAD

**Issue by Raycoms** [ldtteam/minecolonies#476]
Gone Right:
Gold Fever: Your miner mines 16+ gold ore.
Diamonds are a Girls Best Friend: You miner mines 16+ diamonds
Breadbasket: Your farmer harvests 1000+ wheat
Potatoes Mister Frodo: Your farmer harvests 1000+ potatoes
Eh, What's Up Doc?: Your farmer harvests 1000+ carrots
Groovy: Your Guard kills 20 zombies
Thigh Bone: Your Guard kills 20 skeletons
I'm Batman: Your Guard kills a Enderman
Urban Renewal: Your Builder builds 20 separate huts
Whale of a Tale: Your fisherman catches 1000+ fish

Gone Wrong:
Dug Too Deep: Your miner dies in lava
I Am Groot: Your Lumberjack is killed by a tree
Terror from the Deep: Your fisherman is killed by a guardian
Don't tug on Superman's Cape: Your Guard is killed by an Enderman
It's the Stop at the End: Your miner falls to their death
Friendly Fire: You are killed by one of your Rangers
Now That's A Knife: You are killed by one of your Knights

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=41115413)](https://www.bountysource.com/issues/41115413-new-achievements?utm_source=41115413&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by kedamono** [comment]
You'll have to change "I am Groot" as that's an existing achievement as I was told by someone else. And I think I've seen it, just not sure where. So maybe "The Ents are Hungry." or "Carnivorous Trees" could be a substitute.

**Comment by nojo121** [comment]
I'M GOING TO DO THIS SH*T!
😂

**Comment by marvin-bitterlich** [comment]
@kedamono That achievement is too good to be changed :D I suggest we keep that and fight whatever mod also uses this xD
