### ISSUE TITLE
Upgrade of Midevil spruce alternative townhall from lvl 4 to lvl 5 does not line up

### ISSUE THREAD

**Issue by wikidone** [ldtteam/minecolonies#4762]
### Minecolonies version

Version:  minecolonies-0.11.880-ALPHA-universal

### Expected behavior

Medieval Spruce Alternative Lvl 5 town-hall upgrade should upgrade in place from level 4 to level 5.

### Actual behaviour

When performing the upgrade attempts to move the building 5 blocks to the left and 2 blocks back from its original position.

### Steps to reproduce the problem

1. Have a level 4 townhall of the midevil spruce alternative and upgrade it

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
[latest.log](https://github.com/ldtteam/minecolonies/files/4533944/latest.log)

- crashlog: no crash log

**Comment by Raycoms** [comment]
Please report this to the schematic collect issue

**Comment by wikidone** [comment]
This happened when we went from version: minecolonies-0.11.871-ALPHA-universal at level 4 to Version: minecolonies-0.11.880-ALPHA-universal at level 5
