### ISSUE TITLE
[feature request] Keep Chunks Loaded

### ISSUE THREAD

**Issue by forReason** [ldtteam/minecolonies#477]
Who doesnt know the problem?

You are building your lovely villgae and go on adventure, visit the village of your freind or simply go to bed/school/work in real life while your server is still running. Anyways what I want to say: You are not anywhere near your colony.

You come back and nothing at all has changed.

How would it feel if the lumberjack continued lumbering, the miner anf farmer continued working and the next building is finished by your builder (assuming future economy releases with carpenter, blacksmith, food usage)

Simillar issues have been found by other mods long time ago like in chickenchunks, railcraft, buildcraft or minefactory reloaded

My request would be the possibility to set "keep chunks active" in the config so that the village can continue running even if no one is nearby

**Comment by ProsperCraft** [comment]
Or, you could add a chunkloading mod.

**Comment by Raycoms** [comment]
Better add a chunkloading mod.  keeping all player bases loaded at every time would be very heavy load for the server.
