### ISSUE TITLE
Builder wouldn't accept book and quill

### ISSUE THREAD

**Issue by Grummelkater** [ldtteam/minecolonies#4770]
### Minecolonies version

Version: 0.11.886-BETA

### Expected behavior

- 
When upgrading medieval warehouse to lvl4 the builder requests a book and quill. I would expect him to accept a book and quill.

### Actual behaviour

- 

The builder doesn't reconize my book an quill. The request isn't fulfilled. Even teaching him the recipe for book and quill doesn't work.

### Steps to reproduce the problem

1. 
Try to upgrade a medieval warehouse to lvl4
2. 
Wait for builder requesting book and quill
3. 
Beeing unable to fulfill this request
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

**Comment by Raycoms** [comment]
make a book and quill with a "d" on the first line. That one should be accepted. Meanwhile the schematic creator will rescan it and we hpe to update it =)

**Comment by lunadragnstar** [comment]
Nordic Warehouse Fixed
