### ISSUE TITLE
Fortress miner only places North/South on the long axis

### ISSUE THREAD

**Issue by svnrex2019** [ldtteam/minecolonies#4772]
### Minecolonies version

Version: 0.11.878-ALPHA

### Expected behavior

 When the Fortress Miner is built with the building tool the building will be built in the orientation shown by the hologram

### Actual behaviour
 Regardless of what orientation is shown by the building tool, the miner will be built with the long axis either north or south.

### Steps to reproduce the problem

1.  Make a miner block
2.  Use the build tool to place miner block and select the Fortress version
3.  The building will be built with the long axis either north or south
4. ... Profit

**Comment by Raycoms** [comment]
Please update to the latest version, this just got fixed =)
