### ISSUE TITLE
Negative Citizens stats

### ISSUE THREAD

**Issue by MineShadow7** [ldtteam/minecolonies#4775]
### Minecolonies version

Version: minecolonies-0.11.886-BETA-universal
1.15.2

### Actual behaviour
Sometimes citizens can get negative stats or zero. Just want to ask if this is a normal behavior?
![2020-04-26_19 51 32](https://user-images.githubusercontent.com/28764927/80314056-9550e500-87f7-11ea-8cf8-76394730e0a4.png)

**Comment by Raycoms** [comment]
0 is even possible, how it gets negative I wonder.

**Comment by MineShadow7** [comment]
I was actually surprised myself

Never seen that before on the previous versions. I can tell for sure that this child existed on the previous versions but I've never looked at his stats. Maybe he got corrupted by the update or corrupted before. 

I can't really tell if there are any ways to reproduce this, but I'll let you know if I find something on this.

**Comment by MineShadow7** [comment]
On the latest version happened again. Hope the fix will fix  this :з
![2020-04-28_10 52 43](https://user-images.githubusercontent.com/28764927/80461848-90e31400-893e-11ea-902b-b942e030d94c.png)
