### ISSUE TITLE
StackOverFlow: Ticking Entity while idling in MineColony

### ISSUE THREAD

**Issue by NielsPilgaard** [ldtteam/minecolonies#4778]
Original issue: https://github.com/NillerMedDild/Enigmatica5/issues/242

### Minecolonies version

Version: 0.11.858-ALPHA

### Expected behavior
A player was standing idle in his Minecolony, he expected to not crash.

### Actual behaviour
The game crashed after a while, while he was still afk.

### Steps to reproduce the problem
No idea I'm afraid. 

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: I've asked the original reporter for his latest.log
- crashlog: https://gist.github.com/NillerMedDild/f030f89d3f7537c7606da32042568201

**Comment by Raycoms** [comment]
Fixed in the latest version fortunately =)

**Comment by NielsPilgaard** [comment]
Awesome, thanks!
