### ISSUE TITLE
[Suggestion] Allow chief sword to be repaired with Obsidian

### ISSUE THREAD

**Issue by MineShadow7** [ldtteam/minecolonies#4779]
Atm there are no ways to repair chief sword without a second one. This sword is very useful in battles against raiders and quite rare too. Maybe players should be able to keep this rarity for longer if they consider spending their time for mining obsidian and wasting XP on the anvil.

**Comment by Asherslab** [comment]
they're quite rare for a reason, we don't want it repairable, it's super OP
