### ISSUE TITLE
Crash Caused by: java.lang.ClassNotFoundException: com.minecolonies.coremod.colony.buildings.workerbuildings.BuildingBarracks$View

### ISSUE THREAD

**Issue by Greypelt** [ldtteam/minecolonies#4780]
Version: minecolonies-0.11.858-ALPHA-universal.jar

Expected behavior
Game Continues to run after starting a new build project using building tool.

### Actual behaviour
Tried building a medieval spruce barracks with builders tool with barraks hut in inventory, on going to confirm placement the game crashed, with a 'saving game' error screen and it produced a crash log. I did not posses university research which I didn't know I would need until after reloading to find the placed building block. 
[crash-2020-04-26_22.09.56-client.txt](https://github.com/ldtteam/minecolonies/files/4537152/crash-2020-04-26_22.09.56-client.txt)

**Comment by Raycoms** [comment]
I'll also tag @OrionDevelopment here to show him these kind of reports.

This is a forge issue, we don't know what is causing this. Somehow forge sometimes is not loading all the classes.

**Comment by marchermans** [comment]
Yeah no clue....
