### ISSUE TITLE
[1.15.2-885-Alpha] Citizens showing red Happiness for long-fixed issues.

### ISSUE THREAD

**Issue by thecanidcoder** [ldtteam/minecolonies#4782]
I actually have a couple of different issues, but I'm not sure how interrelated they are. I don't want to spam y'all's issues unnecessarily, so for the moment I'll leave everything here.

### Minecolonies version
Version: 885-Alpha
Note: These issues have persisted through several updates. 

### Expected behavior
Increased happiness after solving the relevant problems, and for my Builder to stop complaining to me about the same things.

### Actual behaviour
All four of my colonists are showing red happiness for Homelessness. While there was an extended period of homelessness at the beginning of the colony, it has been solved for nearly two real-world days and, in any case, three of the four were not present at that time. (Originals died and were replaced; look, my colony had a rough start, okay?!)

In addition, my Builder has been constantly display a notification bubble. On interaction, he shows me the same two messages: the first that "he hasn't been able to work for two weeks" despite having been working almost non-stop since I first got him his job. As with the housing, there was an extended period of joblessness at the beginning, but that hasn't been a problem for awhile. 

The second message he constantly shows me is claiming that something went wrong with his AI and I should look at the log. Latest.log will be attached; looking through, I haven't personally anything relevant so far.

Both of these notification bubbles will disappear if I tell him that "This has to work for now!," but they always come back. In the previous versions prior to this, they simply stayed there all the time no matter what I did.

### Steps to reproduce the problem
I couldn't possibly say. I let these problems sit for a couple days in the hopes they'd disappear in the natural course of events, but that hasn't borne fruit.

### Logs: Latest.log and crashlog at https://gist.github.com/

https://gist.github.com/ridjack/40148cd9354a2d9ea9ddd7b35891af2d

Please let me know what further info or testing I can provide. I'm decently technically proficient, and I do have IntelliJ etc installed, though I barely know what I'm doing with it.

**Comment by Raycoms** [comment]
Yeah the latest log is not very useful, I have fixed the issue with the "not been able to work" and will PR that soon.

However, please check the latest.log again when the builder has this behaviour. This means there is an exception.

**Comment by thecanidcoder** [comment]
New log, seems much more relevant this time: https://gist.github.com/ridjack/6b4feb008870d09b182e2921c2d559f3

He was un-moving while constructing my warehouse, so I punched him(after a recall failed to make a difference). On his way back from fleeing, I saw the notification.

**Comment by Raycoms** [comment]
yeah that's a backwards compat issue, please run once /mc colony rs-reset and tell me if it occurs again please.

**Comment by thecanidcoder** [comment]
rs-reset is an invalid command. I see requestsystem-reset in the autocomplete; I assume that's what I want?

**Comment by Raycoms** [comment]
yes

**Comment by thecanidcoder** [comment]
That actually also comes up invalid, and the chat-message explaining it displays oddly: 

https://i.imgur.com/AqxDYvR.png

**Comment by Raycoms** [comment]
reset and then put 1 as the argument

**Comment by thecanidcoder** [comment]
Success that time. 

I will update this if I see the same thing again; I'll try to remember to close it tonight otherwise.
