### ISSUE TITLE
Unable to accept Book and quill for upgrade

### ISSUE THREAD

**Issue by SimonSoby** [ldtteam/minecolonies#4783]
### Minecolonies version

Version: minecolonies-0.11.840-BETA-universal

### Expected behavior

- Upgrading Warehouse to level 4, and the upgrade requires a Book and Quill. Give it to him, and he will finish the upgrade

### Actual behaviour

- Giving the Item, either by forfilling the request, dropping it, putting it in a chest doesn't work. The item wont be accepted. Trying crafting, Spawning and giving the item, won't work

### Steps to reproduce the problem

1. Request Upgrade
2. Wait for the book to be needed
3. Nothing happens when the book is given to the builder
4. ... Profit

**Comment by SimonSoby** [comment]
Tried changing worker, restarting server, restarting the upgrade

**Comment by Raycoms** [comment]
Yeah its a schematic issue, put a letter "d" in the book and quill to fix this.
Meanwhile we rescan it =)

**Comment by SimonSoby** [comment]
So.. Having the same problem again, this time with a clock

**Comment by Raycoms** [comment]
That's a quark problem. Quark changes the clock nbt...
