### ISSUE TITLE
After leaving overworld dim, then returning, unable to interact with any colony object.

### ISSUE THREAD

**Issue by BrewingCoder** [ldtteam/minecolonies#4787]
### Minecolonies version

Version: 0.11.888-ALPHA

### Expected behavior

I- 
That I would be able to right click on building control  block, or interact with Citizens

### Actual behaviour

- 

There is no ability to interact with colony objects.  I can add blocks, break blocks, break colony building blocks I just cannot get MC UI to load and interact.

### Steps to reproduce the problem

1. Have Active Colony
2. Travel to other dimension. I tried Nether, custom mining Dim, Dim via RFTools Dim. All exhibit same behavior.  I tried all the two custom dims separately so to ensure mods did not clash.

3. 
No UI displays when right clicking on colony interaction item like block or citizen.
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: 
https://gist.github.com/BrewingCoder/108c0ecf6c7817aa7157c31788865d96

- crashlog: No Crash.

**Comment by someaddons** [comment]
could you send us your debug.log aswell from that time? think it would be helpful

**Comment by BrewingCoder** [comment]
do you still need a debug log? I nuked that instance because I reduced the number of mods down to the essentials to rule out conflict. I can re-create if you need me to but I see you've already liked a PR.
