### ISSUE TITLE
Building Tool isn't placing right

### ISSUE THREAD

**Issue by ghost** [ldtteam/minecolonies#4788]
Version: 0.11.878-ALPHA

### Expected behavior
![image](https://user-images.githubusercontent.com/13827077/80440023-20210500-8908-11ea-8997-294176602021.png)

### Actual behaviour
![image](https://user-images.githubusercontent.com/13827077/80440057-38911f80-8908-11ea-80ac-3d023b2df965.png)

**Comment by Raycoms** [comment]
For buildings fixes in a later one.
