### ISSUE TITLE
Citizen info messup between GUI and info command

### ISSUE THREAD

**Issue by apfelgluck89** [ldtteam/minecolonies#4789]
### Minecolonies version
Version:  Minecraft : 1.15.2 
MC : 0.11.888-ALPHA 

### Expected behavior
Same citizens attributes values in the GUI and the info cmd message

### Actual behaviour
The citizens  attribute values seems to be messed  up (randomized) in the info command message
also the job looks incorrect (pupil instead of teacher)

![MC citizen Info Issues](https://user-images.githubusercontent.com/64461066/80459174-422f7d00-8932-11ea-98fe-8519a3814f64.png)

### Steps to reproduce the problem
just installed the new version a start a new game

### Logs: Latest.log and crashlog at https://gist.github.com/
[Lastest.log](https://github.com/ldtteam/minecolonies/files/4544083/Lastest.log)

**Comment by mcmanustfj** [comment]
The job showing as pupil is because `/mc citizens info` job is populated by BuildingSchool.getJobName(), which  is always "com.minecolonies.coremod.job.pupil".
