### ISSUE TITLE
Name of the builder in the start building message

### ISSUE THREAD

**Issue by xavierh** [ldtteam/minecolonies#479]
### Minecolonies version

Future version 

### Expected behavior
When starting a build, we currently have
"Started building BuilderHut1"

### Actual behaviour
It would be preferable to have the name of the builder doing the work
"Started building BuilderHut1 by John P. White"
That way the player know which builder's hut he need to go to give the resources

Difficulty: easy

To be tagged as enhancement please

**Comment by harleypig** [comment]
I'd suggest following the current format, consisting of `First Last: <message>`

**Comment by marvin-bitterlich** [comment]
@xavierh did your latest patch fix this?

**Comment by xavierh** [comment]
@Kostronor No I took it out because I am not satisfied with it.
- Could not test when the worker chest is full and the d-man try to deliver
- Worker speeches is too verbose, I am thinking to remove the colony name when it is a worker from the player's own colony.
