### ISSUE TITLE
Pupil not studing

### ISSUE THREAD

**Issue by apfelgluck89** [ldtteam/minecolonies#4790]
### Minecolonies version
Version: Minecraft : 1.15.2
MC : 0.11.888-ALPHA

### Expected behavior
Having a teacher teaching and a pupil studying

### Actual behaviour

The teacher is marked as pupil in the info command message (see [https://github.com/ldtteam/minecolonies/issues/4789])

The actual pupil never comes at school or study

### Steps to reproduce the problem
- create a library lvl 2
- push student to 7 in INT (int leveling stop at 7 for this citizen but at 4 and 5 for the two others ...)
- create school 
- affect student to school
- wait for a child
- affect child to school
- giving paper 

### Logs: Latest.log and crashlog at https://gist.github.com/
[Lastest.log](https://github.com/ldtteam/minecolonies/files/4544084/Lastest.log)

**Comment by Raycoms** [comment]
Are you sure the pupils dont come to school? Because they only come before noon (in the morning) half of the day.

**Comment by marcBugnicourt** [comment]
unfortunatly yes. i even recalled teacher and pupil right after night ends. pupil wanders a few minutes and leaves. teacher just stays until evening.

**Comment by Raycoms** [comment]
there is a random wandering task, they never come back?

**Comment by marcBugnicourt** [comment]
nop :( 
could that be linked to the teacher marked as pupil in the info message ?

**Comment by Raycoms** [comment]
The kids should stay in the school independent of there being a teacher or not.

**Comment by marcBugnicourt** [comment]
well ... they don't :)

**Comment by mcmanustfj** [comment]
The teacher marked as pupil is totally unrelated to any sorts of behavior, that's a bug in the `/mc citizens info`, not in the actual AI.

**Comment by mcmanustfj** [comment]
Try saying `/time set day`, it usually fixes it for me.  Also this might be fixed in #4781
