### ISSUE TITLE
bug repport: miner destroy mine

### ISSUE THREAD

**Issue by marissonsoneur** [ldtteam/minecolonies#4792]
### Minecolonies version
0.10.2-RELEASE

- 
my miner destroy is mine (dwarven mine)
### Actual behaviour

- 

![2020-04-28_17 26 09](https://user-images.githubusercontent.com/64485368/80506482-f1417800-8975-11ea-86b4-ae0655dac07d.png)
### Steps to reproduce the problem

1. 
I do a dwarven mine
2. 
my miner destroy the wodd of my mine
3. 
he dont collect stone fo me!

4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

**Comment by Raycoms** [comment]
This happens when there is
a) Ladders too close to his hut block (causing him to detect this as his mineshaft)
b) The ladders at the actual mineshaft were meddled with.
