### ISSUE TITLE
Asian Barracks guardtower placements all out of place

### ISSUE THREAD

**Issue by AlMasque** [ldtteam/minecolonies#4793]
### Minecolonies version

Version: Minecolonies-0.11.888-ALPHA-universal

### Expected behavior

Building the barracks and the corresponding guard towers should have them all lined up properly

### Actual behaviour

When building each guard tower, every single one of them is off centered by 1 down and 1 across, (they're off by 1 block diagonally)

https://www.reddit.com/user/AlMasque/comments/ga0phq/alignment_problems_with_the_barracks_in_the_asian/
### Steps to reproduce the problem

1. Build the barracks to level 5
2. Build Each Tower to level 5
3. Barracks towers should be misaligned
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

**Comment by Kao713** [comment]
I'm having the same issue with Jungle Barracks

**Comment by Raycoms** [comment]
Please re-report in #4536
