### ISSUE TITLE
Builder tries to break water

### ISSUE THREAD

**Issue by ToMe25** [ldtteam/minecolonies#4796]
### Minecolonies version
Version: 0.11.893

### Expected behavior
I am not sure what i expected, to be honest.

### Actual behaviour
when the builder is ordered to build a building, he will first break all the blocks in that area, including water, which doesn't make much sense as the water will just regenerate in most cases.

### Steps to reproduce the problem
1. Find or create a lake
2. place a building over it
3. see the builder wasting its time by trying to break the water that is instantly regenerating

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

**Comment by KingOnSki** [comment]
i would love it when this is a thing. pls make it so that the builder builds first and if there is any water left to remove, let the builder do that before the torches are placed

**Comment by ToMe25** [comment]
thats the plan.
