### ISSUE TITLE
AbstractWindowBuilding: cost of the next upgrade in a tab

### ISSUE THREAD

**Issue by xavierh** [ldtteam/minecolonies#480]
### Minecolonies version

Future version
### Expected behavior

- Add a tab with the list of resources needed if we where to upgrade

Difficulty: moderate (as it is similar to the Builder huts resources tab)

### Actual behaviour

- In the current version, we don't know what an upgrade is going to cost

### Steps to reproduce the problem

1. Try to upgrade Builder's hut to level 3
2. Find out that you need Coarse dirt
3. Realise that you haven't seen one of them yet
4. Scream and cry like a baby

**Comment by forReason** [comment]
Gravel = g
Dirt = d
```
[ ] [ ] [ ]
[ ] [d] [g]
[ ] [g] [d]
```
maybe swap dirt and gravel

anyways. Good Idea

**Comment by xavierh** [comment]
Dammit, it is craft-able !!!! TIL

Anyway that was just an example ;)

**Comment by forReason** [comment]
lol why would one use un-craftable materials? In fact it is fairly simple compared to stage 4 and 5 materials :D
