### ISSUE TITLE
Miner removing ladders and platform

### ISSUE THREAD

**Issue by benbenlaw** [ldtteam/minecolonies#4800]
### 0.11.886-Beta-universal

Version: 

### Expected behavior

Miner to carry on mining lower instead of remove the platform

### Actual behaviour

After miner has finish clearing the next level, they will start to break the ladder back up to the to of the mine causing it to be stuck. sometime they will break the platform above as well

### Steps to reproduce the problem
1 build miner 
2 start miner
3 miner dont work correctly

**Comment by Raycoms** [comment]
Yeah that's a schematic issue can you please report to #4536 which style ths was?
