### ISSUE TITLE
[1.15.2/0.11.893] Citizen cap research does not affect cap size in town hall gui

### ISSUE THREAD

**Issue by dkkoronakis** [ldtteam/minecolonies#4804]
### Minecolonies version

Version: 0.11.893

### Expected behavior
I researched the civilian upgrades to have more citizens for example +25, +50, +75.

### Actual behaviour
The citizen cap stays at 50, i tried changing the cap from the config file but nothing changes too.

### Steps to reproduce the problem

1. start a colony
2. start getting more citizens and research the cap upgrades
3. the cap stays at 50

### Logs:
- latest.log:
https://gist.github.com/dkkoronakis/77b1298a9a1cf9765537a7cdae25bb42

**Comment by Raycoms** [comment]
none of the cap upgrades works, or only the first one works?

**Comment by dkkoronakis** [comment]
> none of the cap upgrades works, or only the first one works?

None of them, my citizen cap has stayed at 50, and i have done all but the last one.

**Comment by Desim8r** [comment]
Commented the same issue in #4701
We are playing on an established server with a cap of sixty at the time. When the research came out the trouble started. Each time the cap increased after completing a research stage but then reverted back to 50 on server restart. Changing the max in the server config to 75 and 175 has made not difference. I currently have 71/50 citizens after I completed to +175 research and children started spawning again. So I stopped the server to confirm and the town hall went from 71/73 to 17/50 on restart.

**Comment by dkkoronakis** [comment]
> Commented the same issue in #4701
> We are playing on an established server with a cap of sixty at the time. When the research came out the trouble started. Each time the cap increased after completing a research stage but then reverted back to 50 on server restart. Changing the max in the server config to 75 and 175 has made not difference. I currently have 71/50 citizens after I completed to +175 research and children started spawning again. So I stopped the server to confirm and the town hall went from 71/73 to 17/50 on restart.

I know but i am at a newer version of the mod that is why i said it again

**Comment by Raycoms** [comment]
my fault, found the problem
