### ISSUE TITLE
Rotation problem when upgrading a building

### ISSUE THREAD

**Issue by Flywalker753** [ldtteam/minecolonies#4808]
Version:    minecolonies-0.11.893-BETA-universal

### Expected behavior
Upgrade the building at the same position as the building

### Actual behaviour

When i upgrade or repair my two citizens hut and my worker, it's rotating the building 

![](https://cdn.discordapp.com/attachments/620499986349555742/705203407761178704/unknown.png)

![](https://cdn.discordapp.com/attachments/620499986349555742/705203925090959370/unknown.png)

And i think someone has the same problem as me on the reddit

![image](https://user-images.githubusercontent.com/54818057/80659046-17573d00-8a88-11ea-81ca-68526d66d0ee.png)

### Steps to reproduce the problem

I played on valhesia 2 modpack build all the buildings and upgrade the mod to the newer version

**Comment by lunadragnstar** [comment]
I've double checked the hut block placement and it is fine.

**Comment by Raycoms** [comment]
Have you placed those by hand?

**Comment by Flywalker753** [comment]
What do you mean by hand ?
I build the original building with the build tool and then i just upgrade it without repositioning

**Comment by Raycoms** [comment]
I believe some buildings were initially be placed wrongly (Dueto a bug) and due to us fixing it, they are now upgrading the right way, you could use the reposition feature to rotate it (then go to townhall and cancel both build requests) and then do upgrade.
