### ISSUE TITLE
WindowHutBuilder: material needed tab improvement

### ISSUE THREAD

**Issue by xavierh** [ldtteam/minecolonies#481]
### Minecolonies version

Future version

### Expected behavior
Open the **resources needed** tab in the builder's hut gui:
- Have list of the needed resources with added informations: each item have it name display, the number of block available to the builder (i.e how many he have in his inventory + the chest's inventory) and the number needed. Example:
  - Coblestone 2/10 (color red)
  - Oak wood 0/10 (color red)
  - Oak wood plank 100/10 (color green)
- Click on a resource needed item to add it to the chest from the player inventory 
- Color coded item: 
  - green resource are already in the chest or builder inventory
  - red resource will need to be added to the chest if we want the build to be done 
- Order the list with the missing resources first to avoid constant scrolling
- Refresh the list every time we click on an item to reflect the changes

Difficulty: moderate 
Tag: enhancement

### Actual behaviour
- Go to the **resource needed** tab to have a look at what is missing
- switch to the chest to add the resources
- Close the gui
- Open the Builder gui again
- Navigate to the resource tab
- repeat and rinse until we have everything while memorizing what the builder have in his inventory and memorizing what the Builder chest have.

**Comment by mikeskey** [comment]
This would be an extremely welcomed addition to the builders functionality. I can say from personal experience I have gotten extremely frustrated at times when he needs so much and there is not a good way to get it to him and he is constantly running back to his hut for the next item....he should automatically pick everything he needs from the chest BEFORE he goes to start building.

**Comment by forReason** [comment]
I would add two things:
1. A Item image left of the text so you don't have to read the text. you will see it with one single glimpse of your eyes
2. color: yellow/orange for Items that are in the chest but not enough.

I wouldnt colorize the text but add a little square beneath or so since text colorisation increases the difficulty to read the text.

**Comment by xavierh** [comment]
This is almost done, I just need to merge it with the new delivery man

> A Item image left of the text so you don't have to read the text. you will see it with one single glimpse of your eyes

That sound reasonable

> color: yellow/orange for Items that are in the chest but not enough.

The current version works as follow:
- Black: The builder have everything he need either in his inventory or chest
- red: the builder is missing resources that the player does not have in his inventory
- orange: the builder is missing resources that the player have in his inventory but does not have enough
- darkgreen: the builder is missing resources that the player have in quantity in his inventory

Items are order with green first, then orange, red and finally black

The color is on the text: I do agree that it can make the text more difficult to read especially with orange, I might or might not change this with a little colored square

**Comment by forReason** [comment]
the coloring sounds a bit confusing to me but lets see

**Comment by mikeskey** [comment]
That sounds perfect to me Xavierh! Thank You! The orange does sound like it might be a bit difficult to see depending on the background. I'm sure there is some other logical color or background or something that could be done. What about using a yellow, blue or light green but make the green easily distinguishable from the dark green. Kind of a way to let the player know they have some but not quite enough of what they need.

**Comment by xavierh** [comment]
I chose dark green instead of green because the green is far to bright to be readable. So I would not use green instead of orange.
I use green and red because people understand green as good and red as not good.

I chose orange as an intermediate color between both as it is commonly use in monitoring system or traffic light as the "in between" good and not good.

I might drop the orange for:
- dark green, button enabled: the player have enough in his inventory
- red, button enabled: the player have some  in his inventory
- red, button disabled: the player have none  in his inventory
- black, button disabled: the builder have enough

thought ?

**Comment by xavierh** [comment]
FYI, a couple of screen-shots
![2017-01-27_12 17 22](https://cloud.githubusercontent.com/assets/2778556/22372253/838718b8-e493-11e6-9013-cd366a65f46e.png)
![2017-01-27_12 17 49](https://cloud.githubusercontent.com/assets/2778556/22372252/8383f930-e493-11e6-81a9-be1b93bcf5da.png)

 from the current implementation

**Comment by mikeskey** [comment]
I like the looks of it so far.....other than that orange lol. It is somewhat difficult to read on that background. What about maybe darkening it just a tad but still leave it orange? The button enabled/disabled thing would work as well.

**Comment by forReason** [comment]
I like it. Maybe an easy "workaround" for the color would be to only colorize the needed amount(0/1)
what I still think is confusing is that the numbers come from the inventory. Users will think the the builder has these materials eighter in his chest or in his inventory

**Comment by xavierh** [comment]
I will replace the orange by red and disable the button when the player does have any.

As for the number, I might add a hint when I hover over it with:
X in player inventory
Y in builder inventory or chest
Z needed to do the build

Where at the moment I show Y / Z only
depends if it is quick to do or not

**Comment by xavierh** [comment]
> Users will think the the builder has these materials either in his chest or in his inventory

He does, the first number (Y as above) is how many item he does have in his inventory and/or chest, while the second (Z) is what he need to finish the job.

So when Y >= Z, he does have enough and the color become black.

**Comment by xavierh** [comment]
Can this be closed now ?
