### ISSUE TITLE
Size range of colnyu changing

### ISSUE THREAD

**Issue by benbenlaw** [ldtteam/minecolonies#4810]
Version: 

minecolonies-0.11.886-BETA

### Expected behavior
Raddius shown by building tool has changed shape. should be square

After changing the location of a building at the edge of the town it seems to shrink and change size of the colony

![2020-04-30_11 36 44](https://user-images.githubusercontent.com/42780877/80701488-5bbdf980-8ad7-11ea-8a05-770924cfd721.png)

![2020-04-30_11 36 37](https://user-images.githubusercontent.com/42780877/80701498-5f518080-8ad7-11ea-95ed-52f32a64bed3.png)

### Steps to reproduce the problem

start town
add chicken hut towards edge of town
remove chicken hut to change location
size has changed

**Comment by someaddons** [comment]
That is intended/normal, read https://wiki.minecolonies.com/source/systems/townclaimmodes
