### ISSUE TITLE
Minecraft Composter usable without materials

### ISSUE THREAD

**Issue by EchoingZen** [ldtteam/minecolonies#4816]
### Minecolonies version
Version: minecolonies-0.11.888-ALPHA-universal.jar (in the MC-TechColonies modpack v2.5)

### Expected behavior
Vanilla Minecraft Composter should generate bone meal when giving it the required materials.

### Actual behaviour
Vanilla Minecraft Composter appears to not require the standard materials needed to make bone meal. Just clicking on it with an empty hand is enough to generate bone meal.

### Steps to reproduce the problem
1. Download the modpack listed above
2. Create a supply camp
3. Use the composter provided in that camp
4. It should yield bone meal without using resources

**Comment by Raycoms** [comment]
We don't alter the vanilla composter, we got our own compost block, maybe you're confusing those too =)
