### ISSUE TITLE
Minecolonies buildesr mess up

### ISSUE THREAD

**Issue by IBurnTurds01** [ldtteam/minecolonies#4819]
### Minecolonies version

Version: 0.11.886-BETA

### Expected behavior

- The whole colony working again.

### Actual behaviour

- The colonist act  like there is nothing to do and the delivery man will say something to check the AI and to check the latest log or report it to the mod developer.

### Steps to reproduce the problem

1. pick the fortress design
2. Find an island with water around it. Set up the town hall, and set up the miner
3. Eventually the miner will start reverse mincing to the sky and the builder will stare off into space. Then once you get the delivery man, it will say i need a two week vacation, i am unable to work. Then the AI message will pop up.
4. Dont try and kill the person with the error over there head or it will crash the whole server.

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: https://www.dropbox.com/t/1o0Am6agD9LRK4e6
- crashlog: n/a
[latest.log](https://github.com/ldtteam/minecolonies/files/4562484/latest.log)

**Comment by Raycoms** [comment]
We had a bit ago an update that caused some issues.
To fix the dman please run /mc colony rs-reset colonyid (use auto complete to adjust to the exact comment if necessary). This will probably also fix the builder then.

The miner is fixed by fixing his ladders, for sure the ladders got broken and he got confused. We got a bit more resilience planned on this regards.

**Comment by IBurnTurds01** [comment]
i also have guy who will not get out of delivery man outfit and i can not hire him to anything

**Comment by IBurnTurds01** [comment]
![2020-05-01_03 27 08](https://user-images.githubusercontent.com/64626613/80793080-bd27ac00-8b5b-11ea-9ab8-155061cef5c1.png)

**Comment by Raycoms** [comment]
the rs reset will adjust this yes, then you can fire him and hire him somewhere else.

**Comment by IBurnTurds01** [comment]
but i can not hire him anywhere

**Comment by Raycoms** [comment]
even after rs-reset ?

**Comment by Raycoms** [comment]
I had this same problem yesterday (because of loading versions badly) and resetting this fixed it for me and I was able to hire him correctly then

**Comment by IBurnTurds01** [comment]
yeah and just rest the server
