### ISSUE TITLE
Research Stuck

### ISSUE THREAD

**Issue by Perlo0ung** [ldtteam/minecolonies#4820]
### Minecolonies version

Version: minecolonies-0.11.827-ALPHA-universal /minecolonies-0.11.900-ALPHA-universal

### Expected behavior

- Research should make progress, but does not for some options.

### Actual behaviour

- The initial mod version used was "minecolonies-0.11.827-ALPHA-universal". Back then all reseach options where stuck at 0%. I updated to "minecolonies-0.11.900-ALPHA-universal" which resolved the issued with research for some of the options. But "outpost" for example is still stuck on 0% and does not make any progress.

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: does not show any related exceptions 
- crashlog: unrelated

**Comment by Raycoms** [comment]
Do you still have a researcher assigned to the building?

**Comment by Perlo0ung** [comment]
Yes and the chunk is loaded. I still do reseach other stuff which works without problems

**Comment by Raycoms** [comment]
Only a certain number of research can run in parallel, and only if you got enough workers for parallel research, might that be it?

**Comment by Perlo0ung** [comment]
![Image](https://i.imgur.com/aIgu745.png)

I started school and nimble after "outpost", they both progress. I'll check if it progresses with only "outpost" left and willl report back then.

**Comment by Raycoms** [comment]
okay sounds good, the list is not ordered, so there is the possibility that a later started one gets the xp first.

**Comment by Perlo0ung** [comment]
> okay sounds good, the list is not ordered, so there is the possibility that a later started one gets the xp first.

Ty for that hint, that was definately the problem. However I still think there's a lack of clarity on what is being researched at a certain time. Maybe an ordered research would resolve a lot of confusion here

**Comment by Raycoms** [comment]
okay, we'll think about a better indication for that =)
