### ISSUE TITLE
[Suggestion] Request info window fulfill button

### ISSUE THREAD

**Issue by ToMe25** [ldtteam/minecolonies#4821]
I suggest adding a fulfill button to the bottom of this window next to the back button.
![2020-05-01_10 34 49_1](https://user-images.githubusercontent.com/38815969/80793709-23322480-8b98-11ea-83ff-43f78e1e2cda.png)

**Comment by Raycoms** [comment]
Yeah, probably a good idea to have cancel/fullfilment there too

**Comment by ToMe25** [comment]
If someone messes with this window anyways maybe also move the Tool of class block a few pixels up.

**Comment by Raycoms** [comment]
or the button down, yes

**Comment by ToMe25** [comment]
I thought about that too, but i think that wouldn't look good with the text in the background texture.

**Comment by Raycoms** [comment]
But yeah, probably all of it could be moved slightly up

**Comment by Ampaex** [comment]
I'm on it

**Comment by Ampaex** [comment]
Done.
![Capture](https://user-images.githubusercontent.com/9005862/81485362-bc260700-924c-11ea-9079-0cdea831672e.png)
Pull request #4951
