### ISSUE TITLE
placing fortress buildings with the build tool BUG

### ISSUE THREAD

**Issue by kadnkson** [ldtteam/minecolonies#4824]
### Minecolonies version

Version: 0.11.878-ALPHA

### Expected behavior

- 
When placing buildings, you should see the orientation they will be set at before accepting the position.
### Actual behaviour

- 
When placing buildings for the "fortress" they are not placing in the correct orientation. sometimes 90 degrees off, sometimes 180. appears to be direction based. (North, East, South, West)

### Steps to reproduce the problem

1. 
use the build too to place a building from the Fortress tab. (this happened to me with the smeltery and miner hut so far)
2. 
check each cardinal direction
3. 
if you place it so that the orientation of the wall is on the East side, it will place it so that the wall is on the north side.
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

**Comment by Raycoms** [comment]
yes, the 787 version had this issue unfortunately, can you update to the latest and check again?
