### ISSUE TITLE
Delivery Man stuck on the same spot randomly.

### ISSUE THREAD

**Issue by boriandrea1994** [ldtteam/minecolonies#4826]
### Minecolonies version

Version: 
- minecolonies-0.11.896-ALPHA-universal.jar
- structurize-0.10.306-ALPHA.jar
- Minecraft 1.15.2

### Expected behavior
The delivery man continues his tasks.

### Actual behaviour
While the delivery man heads towards the miner's structure, he stops in front of (small) stairways.
The delivery man gets stuck and only unlocks when I push him away or pull him with the rope.
It always freezes in the same place, rarely also the miner freezes in that point.

### Steps to reproduce the problem
I do not know how to reproduce the problem, it happens in a pseudo-random way.

### Logs: Latest.log and crashlog at https://gist.github.com/
- latest.log: https://gist.github.com/boriandrea1994/1f09e1b5d53734e35e51b48b67f226c5

![2020-05-01_19 34 34](https://user-images.githubusercontent.com/60262817/80832922-d4af7500-8bed-11ea-84f4-7a60e986ead8.png)

In the attached image you can see both the delivery man and the miner stuck in the same place.
it's the only proof I found!
Looking in the logs, I don't find any exceptions relevant to similar behavior.
It is not a serious problem because in any case by pushing it it recovers, the problem is if I don't notice it he remains motionless there.

Thank you so much for your patience and for your valuable support.

**Comment by ToMe25** [comment]
i had that problem in 1.14, but never in 1.15

**Comment by Raycoms** [comment]
@someaddons merged a hotfix for this last night =) should be fixed in the newest again

**Comment by boriandrea1994** [comment]
> @someaddons merged a hotfix for this last night =) should be fixed in the newest again

You always amaze me for your speed. Shocked.

Thanks so much :)

So just download the latest alpha version of minecolonies?

**Comment by Raycoms** [comment]
yes
