### ISSUE TITLE
Citizens name tags are not displayed correctly on the journey map

### ISSUE THREAD

**Issue by Cap-Salt** [ldtteam/minecolonies#4829]
### Minecolonies version

Version: minecolonies-0.11.907-ALPHA-universal

### Expected behavior

- 

### Actual behaviour

- 

![2020-05-01_22 06 03](https://user-images.githubusercontent.com/62767037/80839504-b0f32b80-8bfb-11ea-966c-de5d05a6de05.png)

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

**Comment by Raycoms** [comment]
Don't you have to switch for big symbol for this?

**Comment by domek16** [comment]
> Don't you have to switch for big symbol for this?

Yeah, I had the same issue and it worked for me.

**Comment by Cap-Salt** [comment]
Okay i will try it

**Comment by Raycoms** [comment]
9

**Comment by Cap-Salt** [comment]
Please help me I cant find the option to change that (maybe a screenshot)

**Comment by Cap-Salt** [comment]
![2020-05-02_20 53 54](https://user-images.githubusercontent.com/62767037/80873236-5cad8180-8cb7-11ea-8033-938b3d896f82.png)
Why are the names displayed correctly outside the map?

**Comment by Raycoms** [comment]
That is weird, that you might want to report to the JourneyMap mod

**Comment by Cap-Salt** [comment]
Okay I will ask them.
On fullscreen it works perfect
