### ISSUE TITLE
Field gui missing?

### ISSUE THREAD

**Issue by ProsperCraft** [ldtteam/minecolonies#483]
### Minecolonies version

minecolonies-universal-1.11-0.6.25

### Expected behavior

A large gui as seen in the wiki.

### Actual behaviour

https://gyazo.com/5ef76993a49859e124e755c7d4abd69c

### Steps to reproduce the problem

1. open the field scarecrow.

**Comment by forReason** [comment]
for me it shows exactly as in the wiki,
could you further explain your done steps?

**Comment by ProsperCraft** [comment]
Are you using the 1.11.2 version?

**Comment by xavierh** [comment]
I am too, working as intended except the translated title

**Comment by ProsperCraft** [comment]
Must be specific to the hotfix version I am using.

**Comment by Raycoms** [comment]
Your client is set to which language ProsperCraft?

2017-01-20 15:13 GMT-02:00 ProsperCraft <notifications@github.com>:

**Comment by ProsperCraft** [comment]
English

**Comment by Raycoms** [comment]
British English, Canadian English or US English?

2017-01-20 18:28 GMT-02:00 ProsperCraft <notifications@github.com>:

**Comment by ProsperCraft** [comment]
US English.

**Comment by Raycoms** [comment]
Okay that's pretty strange seems like something didn't went well with the
language strings when I built it on my pc locally.

2017-01-20 18:34 GMT-02:00 ProsperCraft <notifications@github.com>:

> US English.
>
