### ISSUE TITLE
Suggestion for a new bulding

### ISSUE THREAD

**Issue by Cap-Salt** [ldtteam/minecolonies#4830]
Wouldn't it be cool if there was a horse stable where a worker takes care of the horses?

## Expected behavior
The use of the horses would be a means of transport for the deliverymans to make them faster AND a militairic benefit for the guards (or a new kind of guardian next to ranger and knights)

That would be a really cool feature and I think would fit well with minecolonies (of course with the corresponding research etc)

**Comment by Raycoms** [comment]
yeah, got them on the list already =)
