### ISSUE TITLE
Vanilla barrels are not counted as inventory space for builder

### ISSUE THREAD

**Issue by MagiMaster** [ldtteam/minecolonies#4831]
### Minecolonies version

Version: minecolonies-0.11.900-ALPHA-universal.jar

### Expected behavior

- A Minecraft barrel in a builder hut blueprint should function the same as a chest or rack.

### Actual behaviour

- The barrel is constructed as part of the hut, but any items placed inside are not recognized as building material.

### Steps to reproduce the problem

1. Make a new builder's hut blueprint that includes a barrel
2. Build the hut
3. Start a new build task using that builder
4. Place the materials in the barrel
5. The material list in the hut block will continue to request those materials
6. Move the materials to the hut block, a chest or a rack
7. The material list will now detect that those materials are available

### Logs: Latest.log and crashlog at https://gist.github.com/

[latest.log](https://github.com/ldtteam/minecolonies/files/4566430/latest.log)
Note that swamp/builder2 contains a barrel, but swamp/builder1 does not, so this issue would only become visible after line 95.

**Comment by marchermans** [comment]
That is indeed true. They behave differently internally. I will mark it as a good first issue and see if some of the newer guys can pick it up again.

**Comment by Raycoms** [comment]
I think we want barrels and chests to not become valid storage in the new future because we don't have enough access to them to detect several things.
