### ISSUE TITLE
Sawmill Teach Recipe Locked at 2x2 But Shows 3x3

### ISSUE THREAD

**Issue by SCBionicle** [ldtteam/minecolonies#4832]
### Minecolonies version

Version: 0.11.878-ALPHA-universal

### Expected behavior

1. Build Level 1 or higher (at max level 3) Saw Mill
2. Open the build block
3. Click Teach Recipe
4. Being able to place items in the third rows and columns of the crafting grid.
- 

### Actual behaviour

When opening the teach recipe to the sawmill block in levels 1, 2, and 3, the 3x3 grid opens, but it'll only let me place items in the upper 2 rows and columns. It completely ignores my mouse and items in the 3rd row from the top and the 3rd column from the left essentially restricting me to making 2x2 recipes.
- 

### Steps to reproduce the problem

1.  Build a wooden sawmill (this was tested up to level 3)
2.  Press teach recipe in the sawmill block
3.  You can't place any items in the 3rd row from the top and the third column from the left in the 3x3 crafting grid, nor will it light up to mouse-overs. (This was only tested in a dedicated server environment)
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: https://gist.github.com/SCBionicle/1be0081343ec314a5c0717d165fa0df1
- crashlog:

**Comment by Raycoms** [comment]
Fixed in latest

**Comment by domek16** [comment]
Not to bother, but you are running kinda old version, that issue isn't a thing on newer ones
