### ISSUE TITLE
Barbarians not looting or attacking?

### ISSUE THREAD

**Issue by Pixelmnkey** [ldtteam/minecolonies#4833]
Version: minecolonies-0.10.715-RELEASE-universal

### Expected behavior
Barbarians are just standing there looking at the doors instead of doing....barbaric things? 
dobarbariansbreakthroughwalls = true and still they just stand there.

**Comment by Raycoms** [comment]
We updated this around 180 versions later =D

**Comment by Pixelmnkey** [comment]
180 versions? 10.715 is the latest version for 1.14 on twitch, am I missing something?

**Comment by domek16** [comment]
1.14 isn't supported anymore :(

**Comment by Pixelmnkey** [comment]
Oh rly? Wtf

**Comment by someaddons** [comment]
ye we do everything in our freetime, so we have to limit where we work on. Which means that we can't spend time on an older intermediary version(1.14 is like 1.11 to 1.12) to support it any longer if we want to move this mod forwards

**Comment by Pixelmnkey** [comment]
Makes sense, didn't mean to undermine your work, thanks for the reply tho ;D
