### ISSUE TITLE
RTP command works for non-op

### ISSUE THREAD

**Issue by 2blade30** [ldtteam/minecolonies#4834]
### Minecolonies version

Version:  minecolonies-0.11.907-ALPHA-universal

### Expected behavior

the RPT command shoudnt work for non op

### Actual behaviour

i get teleport randomly in map even if i<m not an OP

### Steps to reproduce the problem

1. make sure you are not op
2. do the command /minecolonies rtp
3. get teleported randomly

**Comment by Raycoms** [comment]
That is intended behaviour.

**Comment by someaddons** [comment]
disable the command in the config if you do not want this
