### ISSUE TITLE
Citizens create impossible paths and won't stop trying.

### ISSUE THREAD

**Issue by Plisko1** [ldtteam/minecolonies#4837]
### Minecolonies version¡  

Apologies for double posting this.  

Version:  1.12.2-0.10.772-RELEASE. 

### Expected behavior

- 
Citizens create paths that get them to their destination
### Actual behaviour

- 
Citizens create paths that are impossible.  Miner doesn't go in mine, runs across town to a cave and stops 60 blocks above his mine tunnel.  Need to dig ladder down to tunnel to continue.  Reset, fired, rehired, restart... didn't help.

Fisherman swims out to water block and tries to fish... can't... swims back to hut block...turns around and does it again... forever.  Firing and rehiring fixes him.

Delivery man runs into side of house instead of around it.  Spins around at the wall until I break a hole in the wall.  He enters room... stops at opposite wall for a while then paths out the door to the warehouse next to the house.  Reset, firing, rehiring, didn't stop him.  He just ran back to the same spot and spun.  He needs the hole in the house to keep working.   If I close the hole.. he gets stuck again.

![Screen Shot 2020-05-01 at 8 07 56 PM](https://user-images.githubusercontent.com/6001661/80854058-09213200-8bea-11ea-86ac-45e815125117.png)
![Screen Shot 2020-05-01 at 8 08 12 PM](https://user-images.githubusercontent.com/6001661/80854065-0d4d4f80-8bea-11ea-8b8c-a51f05f85f7b.png)
![Screen Shot 2020-05-01 at 8 08 17 PM](https://user-images.githubusercontent.com/6001661/80854066-0de5e600-8bea-11ea-940c-e45e7e1e5eac.png)
![Screen Shot 2020-05-01 at 8 08 39 PM](https://user-images.githubusercontent.com/6001661/80854068-0e7e7c80-8bea-11ea-9eb1-1b3e582b9f45.png)
![Screen Shot 2020-05-01 at 8 08 40 PM](https://user-images.githubusercontent.com/6001661/80854070-0fafa980-8bea-11ea-8b61-9f0c84aafab5.png)

### Steps to reproduce the problem

1. Create mine near a cavern complex.  Set him to mine at Y11.   Wait for tunnels to get close to cavern complex.  Miner eventually tries to path to the tunnel through surface caves and gets stuck 60 blocks or so above the tunnel..
2. Create delivery hut down a road and around the corner from warehouse.  Wait for delivery man to get confused. (see photos)
3. Set up fishing hut on the shoreline.  Fisherman eventually swims out to water block and tries to fish... starts looping.
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
[latest.log](https://github.com/ldtteam/minecolonies/files/4567022/latest.log)

- crashlog:

**Comment by Raycoms** [comment]
Yeah, we pushed a bunch of fixes for this behaviour to 1.15 but unfortunately we can't push them to 1.12 because that is too much porting work.

Thanks for your understanding.
