### ISSUE TITLE
Raid eventually switches to every night after first raid

### ISSUE THREAD

**Issue by BrewingCoder** [ldtteam/minecolonies#4838]
### Minecolonies version

Version: 0.11.907-ALPHA

### Expected behavior

- 
The raid timing mechanics followed what is in the config (6 days between raids in my case)

### Actual behaviour

- 
Once a raid happens it happens again every night, night-after-night, until server is restarted.

### Steps to reproduce the problem

1. Restart dedicated server
2. Wait some random # of days for your first raid
3. Expect Raid after Raid for each night.
4.  I have experienced this 3 times in a row on my test dedi server.  Once raiding starts it does not let up.

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: Nothing mentioned in log besides the fact that raids will happen tonight.
- crashlog:

**Comment by someaddons** [comment]
fixed
