### ISSUE TITLE
Builder taking enormous amount of time to complete Build, slow on DECO and REMOVAL steps

### ISSUE THREAD

**Issue by BrewingCoder** [ldtteam/minecolonies#4839]
### Minecolonies version

Version: 0.11.907-ALPHA

### Expected behavior

- 
That the builder can complete his task in a timely fashion, like pre 905 builds
### Actual behaviour

- 

A level 5 worker in a level 5 building hut takes approximately 1/2 a minecraft day to build a level 1 medieval Oak citizen hut.

The worker then spends 1.5 minecraft days on the Decoration and removal steps while he does nothing but stand in the structure looking around in circles.

I'm not sure, but I believe this is related to the recent commit that worked with the builder potentially leaving artifacts from previous builds in the buildings.

However it now takes the builder three times as long to complete a structure as it did during builds in the 890s range.

### Steps to reproduce the problem

1. Build
2. Watch Builder struggle

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

**Comment by Raycoms** [comment]
fixed
