### ISSUE TITLE
Server Crash - 

### ISSUE THREAD

**Issue by ProsperCraft** [ldtteam/minecolonies#484]
### Minecolonies version

minecolonies-universal-1.11-0.6.25

### Crashlog

https://gist.github.com/ProsperCraft/bc2b78fe2edf908f1787f19e5abfc8fb

### Steps to reproduce the problem

Not sure what the players were doing at the time, and it has only happened once.

**Comment by Raycoms** [comment]
Seems like a player was trying to bring a building or similar to the nether.

2017-01-20 14:14 GMT-02:00 ProsperCraft <notifications@github.com>:

**Comment by ProsperCraft** [comment]
We have not been to any dim other then the overworld, we tried to got the nether but evilcraft crashed the server, so we have not been outside.

**Comment by Raycoms** [comment]
Please reopen if still happening.
