### ISSUE TITLE
Cannot teach bread recipe to cook

### ISSUE THREAD

**Issue by Obbay2** [ldtteam/minecolonies#4840]
Version: 0.11.907-ALPHA

### Expected behavior
Cook should be able to make bread by using 3 wheat side by side.

### Actual behaviour
Adding wheat recipe shows message:
Unable to store the blueprint. Either the cook has no space for any momre blueprints, or the blueprint doesn't correspond with its profession.

### Steps to reproduce the problem
1. Build cook make sure there is no recipes taught
2. Try to teach wheat -> bread

### Logs
No logged error messages.

**Comment by AlMasque** [comment]
you need the baker for that

**Comment by Raycoms** [comment]
Yep, Baker = Bread, on purpose the cook doesn't know how to learn it.

**Comment by Raycoms** [comment]
The cook can't learn recipes with wheat.
