### ISSUE TITLE
Cancel Build button doesn't update properly

### ISSUE THREAD

**Issue by Obbay2** [ldtteam/minecolonies#4841]
Version: 0.11.907-ALPHA

Expected behavior
Pressing Cancel Build in UI should update to Build Options text instantly.

Actual behaviour
Need to close the menu and reopen the menu for the UI text to update from Cancel Build to Build Options

Steps to reproduce the problem
1. Press Cancel Build
2. Note that the text doesn't update

Logs
No logged error messages.

**Comment by Raycoms** [comment]
fixed
