### ISSUE TITLE
The given token is not registered as a request to this manager

### ISSUE THREAD

**Issue by boriandrea1994** [ldtteam/minecolonies#4843]
### Minecolonies version

Version:
minecolonies-0.11.908-ALPHA-universal.jar
structurize-0.10.306-ALPHA.jar
Minecraft 1.15.2

### Expected behavior
The delivery man shows no exceptions in the dialog.

### Actual behaviour
The delivery man reports an error in the AI ​​as shown in the attached image.

![2020-05-02_12 31 40](https://user-images.githubusercontent.com/60262817/80861835-614f4700-8c71-11ea-824b-2fb8fee1da9b.png)
![2020-05-02_12 03 21](https://user-images.githubusercontent.com/60262817/80861845-6f04cc80-8c71-11ea-8575-332b5e4054aa.png)

### Steps to reproduce the problem
I don't know how to reproduce

### Logs
- latest.log: https://gist.github.com/boriandrea1994/f54e9cf125851f46e01efb6365e43f86

**Comment by Raycoms** [comment]
Duplicate
