### ISSUE TITLE
My Structures Placing Crash My Game

### ISSUE THREAD

**Issue by Spacetimemaster999** [ldtteam/minecolonies#4844]
### Minecolonies version
0.11.886-BETA

Version: 1.15.2

### Expected behavior
When I use a schematic it should place the building.

- The construction rope should be made and the normal process should begin.

### Actual behaviour

- When I place any type of structure the game crashes. Whether it is Asain or Spruce and whether it is a camp or a town hall it crashes.

### Steps to reproduce the problem

1. Open the game on the specified version.
2. Try to place a structure.
3. The issue happens.

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
[2020-05-02-12.log.gz](https://github.com/ldtteam/minecolonies/files/4567625/2020-05-02-12.log.gz)

- crashlog:
[crash-2020-05-02_21.56.04-client.txt](https://github.com/ldtteam/minecolonies/files/4567622/crash-2020-05-02_21.56.04-client.txt)

**Comment by Raycoms** [comment]
upgrade both structurize and minecolonies, you got a version mismatch (forge is having an issue detecting this somehow)
