### ISSUE TITLE
citizens death by cramming

### ISSUE THREAD

**Issue by Inomutso** [ldtteam/minecolonies#4845]
### Minecolonies version

Version: minecolonies-0.11.907-ALPHA-universal.jar
structurize-0.10.306-ALPHA.jar
forge-1.15.2-31.0.1

### Expected behavior

- 

### Actual behaviour

- 

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit

Hi Guys

Today I tried minecolonies-0.11.907-ALPHA-universal.jar, because in was waiting for a fix with the Issue #4701. That went fine, after starting I had 9 new Kid´s and could go on, growing up the colonie

Later on, I found several citizens are died, because of "cramming" ¿
so, what does that mean ? Did not have that before. What do you mean with cramming ?
What can I do ?

[02Mai2020 09:20:01.117] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT]  Der Ritter Bella F. Smith starb bei 849 59 745 durch cramming!
[02Mai2020 09:50:42.486] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT]  Der Ritter Lillian E. Culpepper starb bei 849 58 745 durch cramming!
[02Mai2020 09:51:40.193] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT]  Der Healer Barnaby A. Barstaple starb bei 848 58 747 durch cramming!
[02Mai2020 11:25:57.749] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT]  Der Brecher Julia F. Gooder starb bei 841 67 681 durch cramming!
[02Mai2020 12:51:33.203] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT]  Der Ritter Benjamin S. Culpepper starb bei 849 58 746 durch cramming!
[02Mai2020 14:26:37.623] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT]  Der Ritter Helen I. Ayde starb bei 848 59 745 durch cramming!

thx & regards

Inomutso

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

**Comment by dkkoronakis** [comment]
have you tried changing your game's language to english and see what the log would say then?

**Comment by Asherslab** [comment]
Death by cramming is a vanilla minecraft mechanic where entities will die if there's too many in a single block, you'll need to figure out where and when that happens for us to determine if it's a bug and fix it

**Comment by Inomutso** [comment]
Hi again

on this I found out the following behavior

For a long time already I have the delivery man´s (4) Hut build with Acadia Level 5
With these Hut´s here, also a few rails has been placed from the builder, at one side from the Hut.
First i did not know, what the rails are god for, but later on when I had done the researches in the university, I could see the citizens spawning minecarts there, driving a few blocks, jumping out and the minecarts disappeared, but not always, so at some special places the minecarts stayed there.
I have build a few Railways trough the colonie and they all drove up and down the colonie,
even Bee´s Mobs and so on.
But nothing else happend, even when I sometimes had the Rails full with minecarts, some just standig still, some of them still driving up and down, but empty. I wasn´t able to destroy them properly, they had no Block ID an they where like air.
Everybody was able to drive trough them. Sometimes I destroid them with
/kill @e[type=minecolonies:minecart]

But from today on, with minecolonies-0.11.907-ALPHA-universal.jar citizens died, if they try to spawn a minecart at a place, where I have some of these Ghost Minecarts on the Rail. I have a screenshot attached, with on of these places

So for now, I have just destroyed the Rails, where I found most of the stucked Minecarts.

But I think, this must be kind of a Bug. Loaded up the Logfiles, so that you can check

regards

Inomutso

https://gist.github.com/Inomutso/dc0dba904034f32cf1877a7e5ee1638b

![2020-05-02_21 26 21](https://user-images.githubusercontent.com/43415134/80891224-034b4f80-8cc3-11ea-8d17-a54fd185e093.png)

**Comment by Raycoms** [comment]
Ahhhh! so it was that =D. I'll fix it =D
