### ISSUE TITLE
Builder Stops at [Remove_Step] at 100% Building State

### ISSUE THREAD

**Issue by rubyblack16** [ldtteam/minecolonies#4846]
### Minecolonies version

Version: minecolonies-0.11.908-ALPHA-universal

### Expected behavior

- Builder should finish the building when reaching 100%

### Actual behaviour

- Builder stops inside the building at the [remove step] and the building doesn't get finished (both client and server side)

### Steps to reproduce the problem

Was made server side:

1. Start the Colony
2. Start any building (it happens with builder's hut and any other building)
3. At 100% building state the builder get stuck at [remove step] process
4. Killing the citizens and hire a new worker sometimes fix this

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: https://gist.github.com/rubyblack16/a9cf05dcc14a7c5c4904dd136203391e.js
- crashlog: No Crash
![Builder Inv](https://user-images.githubusercontent.com/64697855/80868789-99b44c80-8c94-11ea-98c1-a7214a04e2f2.png)
![Building State 2](https://user-images.githubusercontent.com/64697855/80868793-9ae57980-8c94-11ea-82df-e2a9383f2215.png)
![Building State](https://user-images.githubusercontent.com/64697855/80868794-9b7e1000-8c94-11ea-9168-c9329d781332.png)
![Working State](https://user-images.githubusercontent.com/64697855/80868798-9c16a680-8c94-11ea-97df-7bc34c67b3da.png)

**Comment by Raycoms** [comment]
Haha, I literally just fixed that in 909 =D
