### ISSUE TITLE
Buildtool: Allow mirror image of buildings [$5 awarded]

### ISSUE THREAD

**Issue by xavierh** [ldtteam/minecolonies#485]
### Minecolonies version

Future version

### Expected behavior

- being able to build a mirror image of a building

### Actual behaviour

- We can only rotate at the moment

### Implementation

Difficulty: unknown
Tag: enhancement
Goal: offer more diversity  without multipliying the number of nbt files
The mirror attribute will need to be stored in the building to allow correct upgrade (Same way as the rotation is done)

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=41163787)](https://www.bountysource.com/issues/41163787-buildtool-allow-mirror-image-of-buildings?utm_source=41163787&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by Raycoms** [comment]
Difficulty - relatively easy.

Most of it is there it's mostly a gui thing.

2017-01-20 14:29 GMT-02:00 xavierh <notifications@github.com>:
