### ISSUE TITLE
Building building with build tool

### ISSUE THREAD

**Issue by Pfcande** [ldtteam/minecolonies#4851]
### Expected behavior
From the way I guessing it should work is I'm either supposed to place a hutblock with the build tool, the builder is supposed to place the hutblock (which is what happens), and then I'm supposed to use the build tool to choose the building orientation and such.  Or, the build tool should be giving me this option when I use it to place the hut block.

### Actual behaviour
I place the hut block, doesn't matter which, with the build tool. Doesn't ask me for any building orientation or height or anything.  Builder comes over, places the hutblock.  Then I click on the hutblock with either the tool or my hand and I get a message stating "The block is missing its respective building, try restarting or loading a backup."  I can place the hutblock by hand (and get a message telling me to use the build tool) and it works I can start the building.  But I can't choose an orientation.  It's random.

### Steps to reproduce the problem
Try to place a hutblock with a build tool and then do stuff with it, I guess

### Logs: Latest.log and crashlog at https://gist.github.com/
Doesn't crash.  No log.

**Comment by Raycoms** [comment]
Please upgrade to the latest. That will solve this issue =)

**Comment by Pfcande** [comment]
Didn't even see the latest ones.  Thanks for the quick response!
