### ISSUE TITLE
Builder does not remove the dirt blocks above the field of medival oak farm

### ISSUE THREAD

**Issue by Cap-Salt** [ldtteam/minecolonies#4852]
### Minecolonies version

Version: minecolonies-0.11.910-ALPHA-universal

### Expected behavior

The Builder removes all dirt blocks above the field
- 

### Actual behaviour

He doesn't care for the poor farmer finds a pile of dirt on his field XD
- 

![2020-05-02_22 39 06](https://user-images.githubusercontent.com/62767037/80891884-3394ed00-8cc7-11ea-9267-d0dc91ce0b58.png)

### Steps to reproduce the problem

1. Build a medival oak farm on tier 1
2. 
3. 
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

**Comment by Raycoms** [comment]
That field is done like that on purpose because else the builder will remove your crops as well on upgrades and repair
