### ISSUE TITLE
Builder AI issue : The given token is not registered as a request to this manager

### ISSUE THREAD

**Issue by lebanni** [ldtteam/minecolonies#4854]
minecolonies-0.11.910-ALPHA-universal.jar

[latest.log](https://github.com/ldtteam/minecolonies/files/4569586/latest.log)

finally it crashed.

[crash-2020-05-03_05.50.52-server.txt](https://github.com/ldtteam/minecolonies/files/4569594/crash-2020-05-03_05.50.52-server.txt)

**Comment by Raycoms** [comment]
duplicate #4854
