### ISSUE TITLE
[Suggestion] Add Minimum Quota to Warehouse (Not Talking About Minimum Stock)

### ISSUE THREAD

**Issue by SCBionicle** [ldtteam/minecolonies#4855]
While I know that's there's the ability to add minimum stock to the warehouse, from what I can see in version [minecolonies-0.11.886-BETA-universal], it prevents the delivery people from taking any more than that amount that remains in the warehouse. It might make resource management a little easier by setting a quota within the warehouse on what quota the crafters are required to maintain the warehouse that are still usable by the colonists and request system, but a level just above that target is largely maintained so that we're never out of the user-specified material.

**Comment by Asherslab** [comment]
the minimum stock function should already function that way (as a quota), if it's not then that's a bug

**Comment by marchermans** [comment]
No asher a quota is an amount that the DMan can pick up but the warehouse keeps in stock. Regardless this is already working I just checked. Could you explain what you want in more detail. Cause right now I can tell it to keep 2 stacks of planks and the Crafters make them. But the DMan can still hand these out to others.

**Comment by Asherslab** [comment]
@OrionDevelopment the minimum stock function functions that way (as a quota) as far as i've been told

**Comment by Raycoms** [comment]
yes it does

**Comment by SCBionicle** [comment]
If that is the case, why won't the cook cook more food themselves if the minimum stock requires it but rather requires the player to supply that food? If you want to test that yourself, build a restaurant supplied with fuel, raw beef, and possibly having a surplus of apples might be having something to do with this, but no cooked steak. Then, set a minimum of stock of cooked steak, and the cook should request the player to supply the cook with cooked steak rather than having it delivered from the warehouse or the cook cooking it themselves.

**Comment by Raycoms** [comment]
ohh, the minimum stock is only for crafting at the cook. The cook is not a smelter crafter itself at the moment.

**Comment by Raycoms** [comment]
If you upgrade the cook hut, the minimimum food stock at the cook increases and the cook will request more food to cook.

**Comment by SCBionicle** [comment]
@Raycoms the cook is requesting already cooked foods, not raw foods so that they can cook it.

**Comment by Raycoms** [comment]
The cook requests any food, if the warehouse finds cooked first that gets
delivered

**Comment by SCBionicle** [comment]
I just found out that the cook will not cook anything themselves if they have recipes taught through the UI for the cook. After I removed a modded recipe from the cook, the cook started cooking potatoes, mutton, beef, etc.

P.S. I did fork the code to take a look myself (I'm still studying the API), but I wonder if this issue has something to do with the first if statement in the craft() method in the com.minecolonies.coremod.entity.ai.citizen.cook.EntityAIWorkCook class.

**Comment by marchermans** [comment]
I think this was intended design. People kept complaining about the cook feeding the wrong stuff and nor being able to deal with Pam's Harvestcraft so @Raycoms decided to make it this way.

Allthough i am not sure. @Raycoms Is this intended to behave in this way?

**Comment by Raycoms** [comment]
No that's a different reason, he seems to get stuck in the crafting task.

**Comment by Raycoms** [comment]
I'll wrote it on my list
