### ISSUE TITLE
Delivery man not delivering raw food for the cook

### ISSUE THREAD

**Issue by Obbay2** [ldtteam/minecolonies#4856]
Minecolonies version
Version: minecolonies-0.11.910-ALPHA-universal

Expected behavior
Delivery person delivers raw food to the cook

Actual behaviour
Delivery person does not deliver. No request to be fullfilled by the warehouse message.

Steps to reproduce the problem
1. Have warehouse with delivery people
2. Have cook
3. Note that delivery people don't deliver raw food to the cook.

Logs:
No logs

**Comment by marchermans** [comment]
I just tested this. The DMan delivers raw ingredients for the cook just fine. How do you know that your DMan is not delivering them?

Check the requests ui on your citizen. It should tell you what he or she needs.

**Comment by marchermans** [comment]
Also which game version is this?

**Comment by Obbay2** [comment]
@OrionDevelopment You are correct, it seems to be working.
