### ISSUE TITLE
Crash Report re "Rendering Block Entity"

### ISSUE THREAD

**Issue by SadHorizion77210** [ldtteam/minecolonies#4857]
### Minecolonies version

- <Logon to MC-Techcolonies and just got to my base and would expect to start doing things

### Actual behaviour

- <I logon in got to my base and just started to move and it crashed>

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:https://gist.github.com/SadHorizion77210/33aa66e41c925a88df53f2e71e12b2bc

**Comment by Raycoms** [comment]
Yeah, this is forges fault. They still haven't figured out what is causing this.
Somehow inner classes sometimes fail to load in forge.

:shrug: 

I reported this to them already. Sorry that we can't do anything to solve this.
