### ISSUE TITLE
Citizen Hut Assignment

### ISSUE THREAD

**Issue by MineShadow7** [ldtteam/minecolonies#4859]
Version: minecolonies-0.11.913-BETA-universal
MC 1.15.2
### Expected behavior
Can assign citizens in hut without bugs. Citizens will come to a hut to live and won't take twice space in huts, which causes problems with citizens colony expansion.

### Actual behaviour
If you manually (and maybe even automatically) assign citizens to a hut, they take twice as much space. For quite a while I was experiencing some problems with children, since I haven't seen any even though I have 4 empty citizens huts (lvl2). Each existing filled citizen huts have male and female. 

Also, here is the video showing what's going on -  https://youtu.be/0d7FtXTttPY
### Steps to reproduce the problem
1. Assign citizens to a hut
2. See them take twice as much space
3. Unable to remove the ghost without the original which halts the citizens reproduction
4. ... no profit for your colony...

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: https://gist.github.com/MineShadow7/dee53a4448a76e2741bd1860c396fa94
- crashlog:

**Comment by someaddons** [comment]
fixed
