### ISSUE TITLE
Internal Exception: io.netty.handler.codec.DecoderException: java.lang.RuntimeException: Tried to read NBT tag that was too big; tried to allocate: 16777226bytes where max allowed: 16777216

### ISSUE THREAD

**Issue by DSA3222AS** [ldtteam/minecolonies#4863]
### Minecolonies version

Version: 

### Expected behavior

- 

### Actual behaviour

- 

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

**Comment by DSA3222AS** [comment]
playing on a mod pack server, however, there is a problem when connecting to the server from any moment. Is there any workaround?

**Comment by Raycoms** [comment]
If you'd fill in the form, we could maybe help you =D

**Comment by Asherslab** [comment]
fill out the issue template properly
