### ISSUE TITLE
Game crashes when trying to start a new colony in new world.

### ISSUE THREAD

**Issue by AVFD** [ldtteam/minecolonies#4865]
### Minecolonies version

Version: minecolonies-0.11.918-BETA-universal // structurize-0.10.311-RELEASE // Minecraft-1.15.2 // Forge-31.1.63

### Expected behavior

- Create a new world, and try to create a new colony. Starting with a SupplyCamp Chest.

### Actual behaviour

- When I try to put the SupplyCamp Chest, my game crashes and close. I tried with two schematics: asian, stone. But got crashes in both.

### Steps to reproduce the problem

1. Create a new world.
2. Try to start a colony with 'SupplyCamp Chest'.
3. Get a crash!
4. ... Profit

### Logs:
- latest.log: https://gist.github.com/AVFD/82e148ac4ebf4479ee753a1e4c56634d
- crashlog:

**Comment by someaddons** [comment]
use structurize 310 alpha

**Comment by AVFD** [comment]
TY @someaddons .... that was my mistake
