### ISSUE TITLE
fail of request for investigation

### ISSUE THREAD

**Issue by xlCyanz** [ldtteam/minecolonies#4869]
### Minecolonies version
Version: minecolonies-0.11.918-BETA-universal

### Expected behavior
To let me investigate

### Actual behaviour
Well, I was in my pilot world (test) and I wanted to investigate "Iron Armor" but the requirement is City Hall level 4 and currently my town hall is level 5 and it tells me just as it is very low.

I leave two images for you to see what happened.
Research: 
https://i.imgur.com/TecnPZ7.png
Town Hall:
https://i.imgur.com/TecnPZ7.png

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

**Comment by Raycoms** [comment]
do you have the university level to research this?
