### ISSUE TITLE
Trapped miner

### ISSUE THREAD

**Issue by xlCyanz** [ldtteam/minecolonies#4870]
### Minecolonies version

Version: minecolonies-0.11.918-BETA-universal

### Expected behavior

- The miner can go up normally and go to sleep every night.

### Actual behaviour

- Every night when I am checking that everything is in their houses that have not been locked or something I see that the miners after their mines are a little advanced, they stay at the bottom without being able to climb thanks to the fact that their stairs are never there, they remove them to build the next level but it only generates them to stay there. Then what happens to my most advanced miner who was killed by a skeleton for not being able to climb.

- There is an error with the stairs in the mines.

This is an image of how the stairs or part of them are
- https://i.imgur.com/UeNLNTV.png

**Comment by Raycoms** [comment]
Is this still the case with the newest version? We updated the schematics to place always cobble behind them?

**Comment by xlCyanz** [comment]
I installed the newest version and everything was fine. A skeleton killed one of my miners with an arrow and there were also some guards stuck.

**Comment by Raycoms** [comment]
Improved in the newest too
