### ISSUE TITLE
Minecolonies barbarian and archer are not spawning

### ISSUE THREAD

**Issue by vyang2968** [ldtteam/minecolonies#4872]
### Minecolonies version

Version: 0.11.804-RELEASE

### Expected behavior
Spawns any variation of a barbarian or pirate from a spawn egg or /summon command. 

- The entity would appear and begin to walk around and perform its intended actions like any other mob. 

### Actual behaviour
 Does not spawn mentioned barbarian or pirate. 

-  Instead, when using the /summon command it displays the red error message "Unable to summon object". For example, I type in chat: /summon minecolonies:archerbarbarian and press enter. The output is "Unable to summon object." When attempting to spawn in pirates or barbarians via spawn eggs, they appear for less than a second and immediately disappear. This is all in creative by the way. 

![2020-05-03_23 05 37](https://user-images.githubusercontent.com/64762673/80934005-1417c600-8d94-11ea-9bc1-8c16ca91053b.png)

### Steps to reproduce the problem

1. Have forge 1.12.2 installed. 
2. Download the Minecolones mod by going to Minecolonies.com and clicking the download button on the front page
3. Click on the Curse Forge logo that has "Our Mod" underneath it and it should bring you to Curseforge. 
4. Click the purple download button. At the time of writing, it downloads a file named "minecolonies-1.12.2-0.11.804-RELEASE-universal". 
5. Insert the mod into your Minecraft mods folder by following these steps: Click on windows search, type in "%appdata%" and click enter, click on ".minecraft", click on "mods", and drag the file into the folder.
6. Open Minecraft Launcher and select the appropriate Forge version. Hit play.
7. Once Minecraft is launched, start a new creative world. 
8. Do a /summon command that spawns in any type of barbarian or pirate or use a spawn egg for the same entities.

**Comment by Raycoms** [comment]
Yes, that is intended by design, barbarians/pirates without a raid and without a colony do not function propperly.
