### ISSUE TITLE
Warehouse not consolidating storage

### ISSUE THREAD

**Issue by AdamM72** [ldtteam/minecolonies#4874]
### Minecolonies version

Version: 0.11.794-BETA

### Expected behavior

Warehouse consolidates (non-player) deposited items into stacks.
- 
The warehouse should ensure that identical items are consolidated into stacks, ideally moving them between racks to do so. An enhancement would be to be able to 'limit' the materials so that you could 'group' similar items eg. All wood in one, all stone in another, all food, etc.
### Actual behaviour

Small stacks of identical items in multiple racks
- 
The delivery person is collecting 'excess' items from the various locations and adding them to the warehouse as separate stacks. This results in small stacks of only a few blocks in one rack, and other small stacks in other racks of the same item.

### Steps to reproduce the problem

1. 
Put single or small stacks of item in a building (builder, mine, lumberjack) that are not used by that building.
2. 
The deliveryman will go around collecting these items and delivering them to the warehouse
3. 
After one lot is delivered, add another small stack of the same item to a different building
4. .
The deliveryman will collect these and deliver them to the warehouse in another stack (in another rack)

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

**Comment by Asherslab** [comment]
We do our best to consolidate items when possible, however doing so all the time can easily cause a lot of TPS lag. If you're having issues the warehouse has a Sort function at level3 which will consolidate all the items (and obviously sort them)
