### ISSUE TITLE
Town Hall misplacement & repositioning

### ISSUE THREAD

**Issue by Snapdragyn** [ldtteam/minecolonies#4877]
(With great apologies for not following the template; IANAT (I am not a techie).)

The Minecolonies version in the latest Valhelsia 2 modpack as of 5/3/20, AND the version in the immediately prior V2 modpack.

When attempting to place the town hall, the space shown in preview mode & the space where the building actually builds are not the same. The offset between preview & actual might even be random; I did not do enough testing to verify that, however. The displacement occurs on both of the horizontal axes; the vertical axis appears stable.

Attempting to use the reposition feature resulted in displacement as well. Additionally, the old structure was only removed where the new 'footprint' overlapped it; parts of the building beyond that were left intact & had to be manually dismantled.

**Comment by someaddons** [comment]
its fixed already, the valhelsia version is outdated
