### ISSUE TITLE
Lumberjack still not able to chop down certain trees due to foliage.

### ISSUE THREAD

**Issue by BrewingCoder** [ldtteam/minecolonies#4880]
### Minecolonies version

Version: 0.11.917-ALPHA

### Expected behavior

- 
That the Lumberjack can actually get close enough to the trunk of the tree to chop the tree down
### Actual behaviour

- 
The lumberjack just bounces off the leaves of the tree repeatedly and gets stuck.  Will not give up on tree.  After an evening of returning to sleep lumberjack goes back to the same tree and is stuck.  This loop continues until the tree is manually chopped down.

This bug was opened previously and closed via a commit. I am still experiencing this in build 917 as shown in this video:

https://youtu.be/19yxRp8a8E8

### Steps to reproduce the problem

1. have lumberjack find odd tree (might be that he was up one level)
2.  don't profit, since he/she won't chop that sucker down! :P

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

Nothing is logged in the latest.log or debug.log

**Comment by ravenbuilder934** [comment]
This happens to me too! My lumberjack just stares at the leaves and won't break them to get to the trunk. She walks around the tree and tries to break it from a different place, though, which usually works.

**Comment by staviq** [comment]
Temporary workaround that works for me:

Plant the trees on a single dirt block above ground level, you can even make them pretty with tradoors around.

This way, even if a tree has leaves at level 1, there are 2 levels for the lumberjack fit under.

Something like this: https://i.imgur.com/fuGhX.png

**Comment by Tobiti** [comment]
The same happens with leave blocks above the worker when he tries to jump up a block
