### ISSUE TITLE
Warehouse stock display numbers increase by the amount stored every time the interface is opened

### ISSUE THREAD

**Issue by Scorch-Mechanic** [ldtteam/minecolonies#4881]
### Expected behavior
The stock view interface to show the number of items exactly, to the correct number.

### Actual behaviour
Every time I open the stock interface, the number of a given item is incremented by the amount of the item actually stored. For example, I have 4 spruce doors in my warehouse. I open the stock interface, and it shows 44. I close the interface. I open it again. The interface now shows 48 spruce doors. This incrementing behavior appears to affect every item stocked in the warehouse. 

Furthermore, the behavior continues even if all of a given item is removed from the warehouse and later re-added. For example, checking the interface will show 64 spruce doors (there are in fact only 4). I closed the interface and removed the 4 spruce doors. Checking the interface again shows there are no spruce doors. However, after re-adding the 4 spruce doors and re-opening the interface will show that I have 72 spruce doors.

### Steps to reproduce the problem
Have items in a warehouse. Open the stock interface and note how many are in there. Close the interface, and then open it again, and compare the numbers.

**Comment by ToMe25** [comment]
I can't currently reproduce this the way you describe, but not for the reason i expected, for some reason the stock view isn't showing any items from racks for me atm, but maybe thats caused by something i did wrong.
I had this issue earlier, but couldn't find a way to reproduce it, so either it got worse and is now as easy to reproduce as what you say, or its just an issue with something else you do.

**Comment by ToMe25** [comment]
OK, i can now reproduce this, seems like it really did get alot worse since i had this issue.

**Comment by Raycoms** [comment]
I guess we're just not resetting the counter

**Comment by ToMe25** [comment]
the other problem is that sometimes the count of one item seems to be copied to another one, i had this done until one door was 8, then i added one stone and it was saying 8 stone instantly.

**Comment by ToMe25** [comment]
i think i found the problem.

**Comment by ToMe25** [comment]
I am not sure whether the pr will fix the rare older variant of this issue, but it will fix that it always occures.
