### ISSUE TITLE
Wooden Player Housing has no upgrade option

### ISSUE THREAD

**Issue by WitheredHope** [ldtteam/minecolonies#4883]
###Minecolonies version
minecolonies-0.11.919-ALPHA-universal

Version: 

### Expected behavior
Upgrade option when clicking on decoration controller

### Actual behaviour

![image](https://user-images.githubusercontent.com/44926846/81019915-98834b00-8e5f-11ea-80b1-ff6fddbf3310.png)

### Steps to reproduce the problem

1. Build Player Housing Wooded 1
2. Click on Decoration Controller
3. 
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

N/A

**Comment by ravenbuilder934** [comment]
I think this might be due to the version you're running. It looks pretty outdated to me, but I'm not sure. Have you tried a different version?

**Comment by WitheredHope** [comment]
I was on v910 and this bug is still present on v919, which is, as of now the latest version, which other versions would you like me to try?

**Comment by Raycoms** [comment]
#4536 please
