### ISSUE TITLE
Guard tower counting as bed

### ISSUE THREAD

**Issue by Obbay2** [ldtteam/minecolonies#4887]
Minecolonies version
Version: 0.11.918-BETA

Expected behavior
Guards working in guard tower should still have their home assignment to the house.

Actual behaviour
Guard is assigned, number of total people the colony supports goes up by 1. 
(This could easily be a wiki issue? It seems like from the wiki that only barracks will act as bed for guards not guard towers).

Logs:
No logs

**Comment by ToMe25** [comment]
This is the intended behavior, guards are meant to live in their guard tower, like they live in their barracks tower.

**Comment by Asherslab** [comment]
intended behaviour
