### ISSUE TITLE
Guard tower lvl8 required

### ISSUE THREAD

**Issue by DiabolosMan** [ldtteam/minecolonies#4888]
### Minecolonies version
Minecolonies version 0.11.907-ALPHA
Minecraft version 1.15.2
Forge version 3.11.74

### Expected behavior
A menu to upgrade a guard tower after lvl5

### Actual behaviour
Only switch style is available for my gard tower lvl5 and for my 4 barrack towers lvl5.

### Steps to reproduce the problem
Have guard tower lvl5, go to combat researches. The third column asks for lvl8 guard towers

**Comment by someaddons** [comment]
it is combined levels of multiple buildings

**Comment by ToMe25** [comment]
It adds the levels of all guard towers up, so two level 4 guard towers **should** suffice.
There were however some bugs with this, not sure whether they are fixed.

**Comment by DiabolosMan** [comment]
ok. Thanks. Was not clear for me. I understand now how the 4th column is working also ;-). You can close

**Comment by Raycoms** [comment]
Bugs related to this were fixed =)
