### ISSUE TITLE
Server crashing when entering town/colony

### ISSUE THREAD

**Issue by rac6d** [ldtteam/minecolonies#4889]
### Minecolonies version
Version: minecolonies-0.11.918-BETA-universal

### Expected behavior
Server not to crash when entering my town.

### Actual behavior
Currently, when I'm leaving my colony to help for example a friend and then heading back to my colony the server crashes and I get the screen "timed out". Mostly, on the same spot.

As given in the Crash-Log a single server tick took 60.00 seconds (should be max 0.05) when entering my town. The chunks aren't loading when nearing my town hall then it starts to lag. After this it'll automatically crash. I changed the max tick time to -1 to avoid the crashing but even then it'll crash. The problem now is that when it crashes and the server went offline it won't give me a crash report instead, it'll still say that the server is online on the server interface and I have to manually turn it off without receiving any kind of crash log. With that being said I can only provide the crash log that was given to me before changing the max tick time.

### Steps to reproduce the problem
I'm not sure if I'm able to reproduce the problem since I'm not even sure if minecolonies is causing it. But it just appeared after installing the newest version minecolonies.

### Logs: Latest.log and crash log at https://gist.github.com/
- latest.log and crashlog: https://gist.github.com/rac6d/3a2d944b2a5507218eb757a62ee898bc

**Comment by Raycoms** [comment]
Double checked the log, definitely not us, just correlated with the update.
