### ISSUE TITLE
Colony Permissions: [$5 awarded]

### ISSUE THREAD

**Issue by Raycoms** [ldtteam/minecolonies#489]
We could need a townhall tab which let's the player manually set the certain permission level for certain actions at certain ranks.

And might allow any players to drop and pick up but no one to place and destroy etc.

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=41169534)](https://www.bountysource.com/issues/41169534-colony-permissions?utm_source=41169534&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by forReason** [comment]
uhm one question... you can actually elevate minecraft players by adding their ID.. 

What I would Like more would be if someone steals from a chest or destroys a block the guards will start chasing him down :)  (pick up dropped Items should be legal anyways)

**Comment by Raycoms** [comment]
Done =D
