### ISSUE TITLE
Hospital and university hut blocks not showing up in creative inventory

### ISSUE THREAD

**Issue by ravenbuilder934** [ldtteam/minecolonies#4892]
This is probably my version (I'm running 1.12.2-0.11.804-RELEASE), but neither the hospital or the university hut blocks are showing up in my inventory (I'm in creative mode). I can't craft them, either.

P. S. If it is my version, does anyone have a way to convert worlds made in 1.12.2 to 1.15.2 so I can put a hospital in my city?

**Comment by Raycoms** [comment]
Yeah, they are only in 1.15
