### ISSUE TITLE
Error executing task on Server

### ISSUE THREAD

**Issue by Obbay2** [ldtteam/minecolonies#4896]
### Version
Minecolonies Version: 0.11.918-BETA
Forge version: forge-1.15.2-31.1.0

### Expected behavior
Clicking on things in the GUI results in what one would expect the button to do.

### Actual behaviour
On client it appears as if nothing is happening. Just the buttons don't work.

On server we get the following error:
 [Server thread/FATAL] [net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Server
java.lang.ArrayIndexOutOfBoundsException: null

### Steps to reproduce the problem
This issue seems difficult to reproduce and seems to occur randomly due to server startup. Restarting the dedicated server usually seems to fix the problem.

### Logs: 
lastest.log: https://gist.github.com/Obbay2/e2b671db4160b5c0e13332691fbab7b9
No crashes

**Comment by Raycoms** [comment]
This seems like a weird issue. No where is minecolonies mentioned, can you try updating forge and then trying again? If still not working please report it to forge.
