### ISSUE TITLE
Client crash while using this mod on a server.

### ISSUE THREAD

**Issue by BlueYoshi68** [ldtteam/minecolonies#4897]
### Minecolonies version

Version: minecolonies-1.12.2-0.11.804-RELEASE-universal

### Expected behavior

- I expect it to not crash when trying to place a town hall using the build tool.

### Actual behaviour

- it...crashes?

### Steps to reproduce the problem

1. Load this mod, and OTG
2. Try and place a building on a server using the structurize tool
3. crash
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- crashlog: https://paste.dimdev.org/suyakezayi.mccrash

**Comment by Raycoms** [comment]
You are using 'OTGCorePlugin' which is causing you these issues. This is not a problem without this mod please report it to them.

**Comment by Asherslab** [comment]
you using the LITV modpack? 
if so, that's an issue caused by that mod doing stupid stuff in that modpack.
contact their support discord, they have a way to fix it
