### ISSUE TITLE
Enchanter's Tower Hut Block does not get placed

### ISSUE THREAD

**Issue by DaDuly** [ldtteam/minecolonies#4899]
### Minecolonies version
minecolonies-0.10.715-RELEASE

Version: 

### Expected behavior
Enchanter's Tower Hut Block get's placed when you want to build the Tower

- 

### Actual behaviour
Enchanter's Tower Hut Block (fortress Type) does not get placed after using the Builder Tool. All this happens in Creative Mode in my case.

- 

### Steps to reproduce the problem

1. Try to place the Enchanter's Tower Hut Block
2. Configure placement with BuildersTool
3. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: 
[latest.log](https://github.com/ldtteam/minecolonies/files/4585817/latest.log)

- crashlog: game didn't crashed

**Comment by someaddons** [comment]
update
edit: If its v1.14 then we aren't updating it anymore
