### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by darkbear40** [ldtteam/minecolonies#4903]
### Minecolonies version

Version: minecolonies-0.11.878-ALPHA-universal.jar

### Expected behavior
I would want the builder to accept materials for building upgrades ?

-  builder dose not accept materials needed for building upgrades
 
### Steps to reproduce the problem

1.  I'm sorry i cannot give much detail as i was doing normal progression on the mod and it happened naturally i did not do any thing that would be game braking just delivering items to the builder
2. 
3. 
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

**Comment by Raycoms** [comment]
If the worker doesn't recognize it, "cancel" on the request page fixes it always. The other problem is probably the duplicate #4905
