### ISSUE TITLE
[Suggestion] Make citizens use the same .png skin format as the player model

### ISSUE THREAD

**Issue by carlansor** [ldtteam/minecolonies#4904]
Hi guys, this is just a small suggestion i pictured while working on a medieval texture pack for the colonist. Would it be difficult to make some of the colonist use a texture template similar to the current one the player model use? I know that a lot of colonist models are different from the player model (steve or alex) but checking around some citizens use a texture wich just mirrors the arm and the leg, like the rangers and the male builder for example. How about making those simple models use a texture format like the regular up-to-date skin, that supports the armor layer as well?

**Comment by Raycoms** [comment]
Unsure tbf, we just use the vanilla mechanics there, it should normally work.

**Comment by carlansor** [comment]
yes i know, there isnt really any issue about it right now, but it will give more freedom in texture design if we can use the actual skin template for the citizens that use the player model i think. Just a suggestion thought. Havent really tested if already works tbh

**Comment by carlansor** [comment]
Ok tested and citizens that use the player model wont support uptodate skin texture format.

**Comment by marchermans** [comment]
I do not see this as an issue. We are working towards replacing every citizen model with a custom one anyway, and as such this issue is not really relevant for us.
