### ISSUE TITLE
Miner Hut disappearing

### ISSUE THREAD

**Issue by PeterFunny** [ldtteam/minecolonies#4906]
### Minecolonies version

Version: minecolonies-0.11.918-BETA-universal

### Expected behavior

Normally, I would place down the miner hut and then assign a builder in order to build it.

### Actual behaviour

Instead of spawning the building outlines to mark the building ground, the item for the miner hut disappears and nothing happens

### Steps to reproduce the problem

1. Start a new village
2. Place down the town hall and the builder hut and finish those two
3. Place down the lumberjack
4. Place down the miners hut

I don't know if this happens if you try to put down the miner first.
The lumberjack doesn't have a texture, btw.

**Comment by PeterFunny** [comment]
*EDIT: 
I am running MineColonies on a 1.15.2 server, in singleplayer it works fine. Any thoughts on why it might not work on a server?

**Comment by Raycoms** [comment]
The lumberjack texture missing is an optifine problem, please report it to them. The miner problem seems weird, can you reproduce that?

**Comment by PeterFunny** [comment]
Hi, after some testing last night I saw that you guys put out a new alpha build, I installed it and now it works fine, but thanks for answering so fast.
