### ISSUE TITLE
Suggestion: help command prints wiki url

### ISSUE THREAD

**Issue by spacewolfcub** [ldtteam/minecolonies#4909]
I suggest that the command: 
/minecolonies help 

Print in chat:
https://wiki.minecolonies.com

Or possibly the link to a specific wiki page that lists the major help options, like: 
Tutorial wiki page 
Commands wiki page 
Discord permalink 

Maybe this page could also have right at the top a big automated display of:
ONLY CURRENT VERSIONS ARE SUPPORTED
The current version for Minecraft 1.12 is: (automated name of file with curseforge link to it)
The current version for Minecraft 1.14 is: (automated name of file with curseforge link to it)
The current version for Minecraft 1.15 is: (automated name of file with curseforge link to it)

**Comment by PowerSchill** [comment]
If the command includes text how would language translation work? Would Google translate work for an initial attempt to translate the text into other languages?

**Comment by Asherslab** [comment]
same way all other translation in minecraft works, using lang files

**Comment by PowerSchill** [comment]
Yeah, I know that but I only know one (verbal) language so I wasn't sure the process for the other languages.

**Comment by Raycoms** [comment]
You'd put it in the en_us file, and people would then translate it at translate.minecolonies.comand we merge that back into the mod
