### ISSUE TITLE
[updated config] Got tired of the same old names and too long build times

### ISSUE THREAD

**Issue by kreezxil** [ldtteam/minecolonies#491]
https://gist.github.com/424ab1a16425aeee65cf5b04e487bfa5 save the raw as minecolonies.cfg into your config folder

I've added around 1000 first names for both ladies and men (2000ish total) and around 800 surnames.

Also reduced the painfully slow build delay from 1000 to 10.

**Comment by marvin-bitterlich** [comment]
@kreezxil do you mind if we use the names in the game for the default config?

**Comment by kreezxil** [comment]
please be my guest, you can credit me and my website "kreezxil" and "
www.kreezcraft.com", it's all I ask. However, I MIT all my work, so you
technically don't even have too. :)

**Comment by marvin-bitterlich** [comment]
If you want credits, you can make a pr and it will show merged on your github account ;)
Our current CLA requires to relicence all work: https://cla-assistant.io/Minecolonies/minecolonies so you would have to agree to that so we can add the change

**Comment by kreezxil** [comment]
Ok, I signed it. Have fun with it.

**Comment by forReason** [comment]
the changes were done a while ago in my local config already.

**Comment by cltnschlosser** [comment]
Can this be closed now? after #499

**Comment by kreezxil** [comment]
Sure

-----Original Message-----
