### ISSUE TITLE
Mysterious Sailors don't stop spawning

### ISSUE THREAD

**Issue by PeterFunny** [ldtteam/minecolonies#4911]
### Minecolonies version

Version:  0.11.928-ALPHA

### Expected behavior

A Sailboat spawns near my colony and a chat message appears saying I should destroy the ship.
Afterwards, I would expect the attack to be over and the villagers should go back to work

### Actual behaviour

After destroying the ship, the Sailors/Barbarians just don't stop spawning. I tried sleeping but the next day they were still spawning. I tried restarting the server but that didn't fix it either.

### Steps to reproduce the problem

1. Wait for the message that a ship with mysterious sailors or something like that arrives
2. Fight them off
3. See that they don't stop spawning
4. The villagers can't get back to work because of the constant attack

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

**Comment by someaddons** [comment]
fixed in newest
