### ISSUE TITLE
when i place the hospital with a buildtool it only place an oak plank (1.15.2)

### ISSUE THREAD

**Issue by xq29510** [ldtteam/minecolonies#4915]
### Minecolonies version

Version: 

### Expected behavior

- 

### Actual behaviour

- 

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

**Comment by Raycoms** [comment]
Which schematic? This is likely a schematic issue so #4536 please

**Comment by xq29510** [comment]
> Which schematic? This is likely a schematic issue so #4536 please
wooden
