### ISSUE TITLE
CTD When Using BuildTool

### ISSUE THREAD

**Issue by Linkmasterxxxx** [ldtteam/minecolonies#4916]
### Minecolonies version

Version: 1.12.2-0.11.841-ALPHA

### Expected behavior

- Bring up general buildtool GUI

### Actual behaviour

-  As soon as I right click the ground with the buildtool the game crashes to desktop
[crash-2020-05-07_15.44.10-client.txt](https://github.com/ldtteam/minecolonies/files/4595399/crash-2020-05-07_15.44.10-client.txt)

### Steps to reproduce the problem

1.  Craft a build tool
2.  right click on any block with the buildtool
3.  game crashes to desktop

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog: [crash-2020-05-07_15.44.10-client.txt](https://github.com/ldtteam/minecolonies/files/4595410/crash-2020-05-07_15.44.10-client.txt)

**Comment by Raycoms** [comment]
Please report to malisis doors mod, that's what is actually causing the crash.
