### ISSUE TITLE
First citizen has all ones for skills

### ISSUE THREAD

**Issue by ravenbuilder934** [ldtteam/minecolonies#4918]
### Expected behavior

The first citizen in a new colony would have skills as if the happiness level was 5.5 (the happiness level after the first few citizens show up).

### Actual behavior

The first citizen's skills are all ones since the happiness level is 0 (because there are no citizens to raise it higher).

### Steps to reproduce the problem

1. Start a brand-new colony
2. Wait for the first citizen to appear
3. Look at their skills
4. ... Don't profit, because they're all ones!

**Comment by PowerSchill** [comment]
@Raycoms want to assign this to me and I will take a look at it.
