### ISSUE TITLE
Suggestion: Groundskeeper?

### ISSUE THREAD

**Issue by ravenbuilder934** [ldtteam/minecolonies#4919]
Okay, so this is based on [#307](https://github.com/ldtteam/minecolonies/issues/307) (which is closed), especially harleypig's comment. We could have a new worker called a Groundskeeper, who would walk around the colony, clearing grass (not grass blocks!), ferns, flowers, and maybe some other things. They would get all the regular drops from them, plus some more (like breaking a fern and sometimes getting a random sapling). 
*Would need to set it so they don't break the florist's flowers.*
The chance of them getting good stuff would increase based on their worker level/building level, or they could have a tool like the Sifter's meshes that would allow them to get more and better stuff as drops after you upgrade it. (Shovel? Hoe?)
Possible skills would be Focus, Dexterity, but could also have Stamina as one of them.
You could set in their hut block what things you want them to break and if you want them to break things that are part of schematics (like the flowers outside the Florist's Hut).
*This is different from the Sifter because they would break all the annoying grass in your area and wouldn't delete/make vanish dirt, gravel, or whatever you want the Sifter to sift.*

**Comment by Raycoms** [comment]
Please add to #4535

**Comment by ravenbuilder934** [comment]
How can I add it? @Raycoms

**Comment by Asherslab** [comment]
comment on the issue

**Comment by ravenbuilder934** [comment]
@Asherslab Okay

**Comment by ravenbuilder934** [comment]
@Asherslab Like that?
