### ISSUE TITLE
Mass lag with sawmill worker and a forest

### ISSUE THREAD

**Issue by NyleGarcia** [ldtteam/minecolonies#492]
### Minecolonies version

version X.X.XXXX or curse X.X.XX

### Expected behavior

no lag with a sawmill worker in a forest 

### Actual behaviour

mass amounts of lag and tps dropedges when using a sawmill worker in a forest

### Steps to reproduce the problem

hire worker tps drops to below 10
fire worker tps goes back to 20

https://gyazo.com/75768de1b804dae5ea2eff9831903b05

**Comment by Raycoms** [comment]
can you send us your log?

2017-01-21 2:08 GMT-02:00 Bebabo10 <notifications@github.com>:

**Comment by ProsperCraft** [comment]
@bebabo10 let's close this and reopen it with a version number, warmroast and tickprofile.  If it happens again.
