### ISSUE TITLE
Sifter deletes whatever they're sifting

### ISSUE THREAD

**Issue by ravenbuilder934** [ldtteam/minecolonies#4921]
### Expected behavior

The sifter sifts through dirt, gravel, or whatever you want them to sift and finds items *without deleting what they're sifting.* For example, if you tell your sifter to sift dirt and give them a stack of dirt, when they're done, they should have the stack of dirt and whatever items they found. This is how it works in real life.

### Actual behavior

If you tell your sifter to sift dirt and give them a stack of dirt, when they're done, they just have the items they found, and the dirt has vanished.

### Steps to reproduce the problem

1. Build a sifter's hut
2. Hire a sifter
3. Wait until they start sifting
4. ... Profit

Note: This might be intentional, I'm not sure. I just noticed that it was different from real life and wasn't sure if you meant to do that (as a trash bin for dirt?).

**Comment by Raycoms** [comment]
This is on purpose, else we got infinite free items?
