### ISSUE TITLE
[Suggestion] The lumberjack should be able to craft stripped logs/wood

### ISSUE THREAD

**Issue by JiaYow** [ldtteam/minecolonies#4922]
### Feature Suggestion
The new (awesome) Asian building style requires a fair bit of stripped wood.
Stripped variants of woods cannot be crafted, but must be made by right-clicking woods/logs with an axe. Which becomes old really quickly when the buildings require hundreds of them.

It makes sense for the lumberjack to be able to craft stripped versions of logs.

### Draft implementation
https://github.com/JiaYow/minecolonies/compare/feature/stripped-lumberjack provides a functional draft implementation for this.

1. Lumberjack turns vanilla wood/log to stripped versions if a request for this exists in the request pipeline.
2. The lumberjack hut's GUI shows the list of recipes (i.e. the stripped versions), but you can't remove them and you also can't teach new recipes.

### Open considerations
1. Turning wood into its stripped version does not cost anything (but the original wood) currently. This is because I have no idea how to damage the axe properly (I looked at AbstractEntityAllInteract.java:234, and I don't understand how that would do anything). We could just make it cost 2 logs per stripped version :-P
2. It would be preferable if this was gated behind a university research. I have not found a way to update the building's recipe list onResearchCompleted (this event doesn't seem to exist). Therefore, one would have to reload the chunk/restart the server after researching to enable the feature. Which is worse than not gating the feature at all imho. How about linking this to the building level instead? There's an onUpdate-event for that.

Please review (thoroughly! I touched a lot of code in there with which I have no experience yet). Thanks :-)

**Comment by Asherslab** [comment]
This is an issue, you should be making a Pull Request

**Comment by JiaYow** [comment]
https://github.com/ldtteam/minecolonies/blob/version/1.15/.github/CONTRIBUTING tells you to create an issue before submitting a pull request ...? :-P

**Comment by Asherslab** [comment]
ignore that, no need
