### ISSUE TITLE
Builder's Resources Disappear After Given from Player to Builder

### ISSUE THREAD

**Issue by sjstark** [ldtteam/minecolonies#4923]
Version:  minecolonies-0.11.910-ALPHA-universal

### Expected behavior
Expected builder to accept resources, keep them in their inventory, and start using them to build.

### Actual behaviour
Builder will accept resources into their inventory, but a few seconds later 'forget' they had them and it gets deleted from their inventory and the resource is added back to the build list scroll

https://youtu.be/q-MtgeydbQ4

### Steps to reproduce the problem
I piggy backed on someone else's issue earlier, but it hasn't been tagged as open, or a good first issue. Redoing it in your desired format to make it easier for your team! (thanks for all the work you guys have done on this mod, love getting lost in the world)

See steps described in issue  https://github.com/ldtteam/minecolonies/issues/4905

### Logs: Latest.log and crashlog at https://gist.github.com/
No crash logs as it did not produce a crash. If it happens again, I'll snag the latest.log

**Comment by sjstark** [comment]
Just happened again. Got the latest.log (see copied below) as well as a shadow play of when I noticed it. Not as clear in the shadow play as my other example.

https://gist.github.com/sjstark/04f88f98d090726b1252a8d0678e7766

https://youtu.be/Q4I5yjAZgxE

**Comment by Asherslab** [comment]
you're 23 versions behind, please update and try again

**Comment by sjstark** [comment]
Gotcha, I'll try to get the server admin to drop in the latest update and report back.

**Comment by someaddons** [comment]
That seems to be more a case of "the builder later notices he needs X more of Y after starting building"

**Comment by Raycoms** [comment]
Yeah that is entirely possible. @sjstark can you check if he actually loses items or if new item requests pop up?

**Comment by Raycoms** [comment]
Duplicate #4905
