### ISSUE TITLE
Suggestion: Enchanter changes

### ISSUE THREAD

**Issue by ravenbuilder934** [ldtteam/minecolonies#4927]
This is from Asherslab's comment on [#115](https://github.com/ldtteam/minecolonies/issues/115) saying *I dunno why, but I kinda want the model for the enchanted to include two (one on left and right) glass "jars" on his back like a backpack, and when he sucks up experience those fill up with experience "juice".

Also maybe ghost busters style vacuum cleaner for grabbing experience from workers. Lol*

I figured nobody would see the issue anymore because it's closed, but the enchanter doesn't have glass jars on their back, so I decided to open a new issue (hope that's okay). Right now, the enchanter shares their texture with the library student, so it would be easier to tell them apart if they had experience jars on their back. It would also look cool and be really funny.  :)

Also, could we maybe have the enchanter put the enchanted books on tools/armor using an anvil (or have a new/different worker do it)? This way, the player doesn't have to do it and can focus on running the colony.

Last thing. To make the way the enchanter enchants things more like the way the player enchants things, can we change it so they need lapis to do their work? (If they already need it, can we change the wiki so it says so?)

**Comment by Asherslab** [comment]
All suggestions go in here, please don't create new issues for suggestions: 
#4535

Copy paste the whole suggestion there

**Comment by ravenbuilder934** [comment]
@Asherslab Okay, sorry I forgot.
