### ISSUE TITLE
Ticking Entity crash

### ISSUE THREAD

**Issue by KaazONFIRE** [ldtteam/minecolonies#4929]
Version: MC : 1.15.2 on Modpack Valhelsia 2 2.1.8a (minecolonies-0.11.910-ALPHA)

### Expected behavior

- 
not crashing ?
### Actual behaviour

- 
serv instantly crashing when i try to connect cause of a problem with one of my citizen

I'll put the crashlog under the post
### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog: https://gist.github.com/KaazONFIRE/caea05b5f4a0b9880061d8f811472bc7

I'm sry for missed infos, if u need more specific details i'm gonna check the post oftenly

**Comment by Raycoms** [comment]
Please update to the newest here =D, That has the fix
