### ISSUE TITLE
Crash on entering the Nether

### ISSUE THREAD

**Issue by Zarepheth** [ldtteam/minecolonies#493]
### Minecolonies version

minecolonies-universal-1.11-0.6.2306

### Expected behavior

- Expected to appear in the Nether.

### Actual behavior

- Game crashed to desktop.

### Steps to reproduce the problem

Pre-req: Minecraft 1.11.2, Forge 13.20.0.2223, Substratum-1.11.2-1.9.1.0, and minecolonies-universal-1.11-0.6.2306

1. Acquire 10 Obsidian, 1 iron, 1 flint.
2. In the Overworld, Construct a Nether portal with the 10 Obsidian (2 bottom, 3 left, 3 right, 2 top).
3. Construct flint & steel igniter from the iron and flint.
4. Ignite the inside of the portal.
5. Step into the portal and wait for transport to the Nether.
6. Game crashes to desktop.

### More info

The crash occurred on my first foray into the Nether for the current world.
The MineColonies crash occurred on the Server 1 or 2 seconds after a Client-side crash with a different mod.
Upon reloading the world, the crash recurred as the Nether was loaded.

Initial Server-side crash:
[crash-2017-01-20_23.54.46-server.txt](https://github.com/Minecolonies/minecolonies/files/720951/crash-2017-01-20_23.54.46-server.txt)

Second Server-side crash:
[crash-2017-01-20_23.57.54-server.txt](https://github.com/Minecolonies/minecolonies/files/720952/crash-2017-01-20_23.57.54-server.txt)

The issue for the Client-side crash: [Substratum Issue 33](https://github.com/EXTER7/Substratum/issues/33).

**Comment by Raycoms** [comment]
Substratum-1.11.2-1.9.1.0 does what exactly?

2017-01-21 4:26 GMT-02:00 Zarepheth <notifications@github.com>:

**Comment by Zarepheth** [comment]
Substratum adds ores to the game, along with ingots, nuggets, dust, plates, gears, and tools created from those ores. Basically, it's a mod to add metals one might use in Tinker's Construct (if Tinker's Construct worked in MC 1.11.2). The client-side crashes occurred when attempting to render the ore in the Nether. But because the Mine Colonies server-side crash occurred within a second or two of the client crash, I figured there might be a relation or conflict between them.

[Substratum on Curse](https://minecraft.curseforge.com/projects/substratum?gameCategorySlug=mc-mods&projectID=241113)

**Comment by Zarepheth** [comment]
Attempting to load the world this evening, MineCraft crashed again, but this time only the client-side crash log was generated. There is a good chance that the internal server crash was a response to the client crash. Feel free to review the referenced issue on Substratum.

**Comment by Raycoms** [comment]
We have 2 issues related to this already. That's why I will close it here for now.

**Comment by Zarepheth** [comment]
@Raycoms, Before closing due to issue duplication, please link to the active issues so we can easily find and follow them.

**Comment by Raycoms** [comment]
https://github.com/Minecolonies/minecolonies/issues/509

2017-01-28 22:46 GMT-02:00 Zarepheth <notifications@github.com>:
