### ISSUE TITLE
Ticking Entity Crash

### ISSUE THREAD

**Issue by MrMeender** [ldtteam/minecolonies#4931]
### Minecolonies version 0.11.918-BETA

Version: 1.15.2 - Forge-31.1.77

### Expected behavior

- Game not crashing

### Actual behaviour

- Game crashes showing error: "java.lang.StackOverflowError: Ticking entity"

### Steps to reproduce the problem

I don't know how the crashes started happening. I think that they are related to a citizen placing blocks. 

1.  Something has to happen and some files maybe have to get corrupted...?
2. I give the miner the blocks it needs to build (there is a request which I have to fulfill)
3. It starts building...
4. ... after placing few blocks (in this case they are cobblestone stairs) the game crashes giving the error mentioned above 

### Logs: Latest.log and crashlog at https://gist.github.com/
- latest.log: https://gist.github.com/MrMeender/1a6461a9a5a52a44d2be1215d30f11f7

In crashlog I put 7 crashlogs. As you will see they all refer to the same entity except for the fifth. That's because I tried killing that specific entity and the crashed happened on another one.
The entity that caused 6 crashes was a miner trying to build a mineshaft. The other one was a builder. 
- crashlog: https://gist.github.com/MrMeender/6129075a6d552f6dc641ac08f02a3642

Should I upload the world so you can see if it happens on your computer or some files on mine are corrupted? I wanted to avoid reinstalling forge or the mods but I'll try.

Also I'm not using any modpack, the mods I have installed are only Minecolonies (Version specified above) and Structurize 0.10.313-RELEASE. I use the sound resourcepack for Minecolonies too.

Edit: I know this has been posted but the first post was ignored because of not using the correct template and the other one was a previous version

**Comment by Raycoms** [comment]
World download would be nice

**Comment by MrMeender** [comment]
I don't know exactly where to upload it. I'm going to send you a link for Google Drive. Is it ok?
It is taking some time to upload because my internet isn't that good

**Comment by Raycoms** [comment]
yes, np

**Comment by MrMeender** [comment]
Anyway this is the link to download the world: https://drive.google.com/file/d/1ivL4Tx2oXtOf-NEI74BCodXNjq5tYzGO/view?usp=sharing

**Comment by Raycoms** [comment]
You need to give me access

**Comment by MrMeender** [comment]
Access to what?

**Comment by MrMeender** [comment]
Uhm ok. I just noticed. I'm doing it right now

**Comment by MrMeender** [comment]
Now you should have access.

**Comment by Raycoms** [comment]
got it, ye

**Comment by Raycoms** [comment]
Can you try the newest, it works fine for me on the newest?

**Comment by MrMeender** [comment]
Which is the newest?

**Comment by MrMeender** [comment]
I think I have the newest available on Curseforge

**Comment by Raycoms** [comment]
minecolonies-0.11.932-ALPHA-universal.jar

**Comment by Raycoms** [comment]
?

**Comment by MrMeender** [comment]
Where can I find it?
I have this as the most recent:
![immagine](https://user-images.githubusercontent.com/59515203/81416145-9cf28100-9149-11ea-9643-254d7924cdd9.png)

**Comment by MrMeender** [comment]
Wait that doesn't show the ALPHA versions. I found it. Now I try it and see if it works.

**Comment by MrMeender** [comment]
Well looks like nothing strange is happening.
Sorry if I didn't properly check if I was playing on the most recent version but I didn't now.

Anyway thanks a lot.
