### ISSUE TITLE
Missing colony manager spam (SimpleDimensions)

### ISSUE THREAD

**Issue by sa-shiro** [ldtteam/minecolonies#4932]
Version: 1.12.2-0.11.841-ALPHA

### Expected behavior
no log spam of a missing world capability

### Actual behaviour
When a custom dimension was created with *SimpleDimensions* Minecolonies will spam a warning every tick and thats not only annoying, it also impacts the performance (using latest versions ofc)

Error Message:
`Missing world capability with colony manager!`

### Steps to reproduce the problem

1. Install Minecolonies & SImpleDImensions
2. Create a new World
3. Create a new dimension with `/simpledimensions create`
4. teleport to the dimension (using tpx 0 100 0 30000 if cofh is installed or any other dimension tp command)
5. minecolonies will spam the log

### Logs:
- latest.log:
https://gist.github.com/sa-shiro/f6b80e946b79756d6306734bde388f5a
(spam starting at 16:24:32 in log2.log)

Any way to fix this?

**Comment by Raycoms** [comment]
@OrionDevelopment should be weirdto not have our capability which we apply on the right spot, no?

**Comment by someaddons** [comment]
seems that simpledimensions mod is outdated/notmaintained and doesnt not create dimensions correctly.

**Comment by marchermans** [comment]
Yeah this is not our issue.
We just follow Forge guidelines on how to attach capabilities to worlds. 

It works with other mods that add dimensions and it works with all vanilla worlds.
So closing this.
