### ISSUE TITLE
Book pages for building blank

### ISSUE THREAD

**Issue by a22315** [ldtteam/minecolonies#4935]
All of the pages for books on buildings like town hall and builders huts and clipboards are showing up blank but only showing the bottom 2 inches of the page. It is like this for everything. 
![image](https://user-images.githubusercontent.com/64995171/81356759-f605da80-909f-11ea-98ec-ca195f88cddd.jpg)

**Comment by Raycoms** [comment]
What version are you on?

**Comment by a22315** [comment]
1.15.2

**Comment by Raycoms** [comment]
What minecolonies version exactly?

**Comment by a22315** [comment]
I don’t have my computer with me right now but the most recent version.

**Comment by a22315** [comment]
I believe it was like 10.771 release is what I downloaded.

**Comment by Raycoms** [comment]
okay, that has been fixed by the newest one then.

**Comment by a22315** [comment]
Ok, thank you.
