### ISSUE TITLE
Builder not Building

### ISSUE THREAD

**Issue by Midnight888** [ldtteam/minecolonies#4936]
My builder sits in front of his level 5 hut and won't move to upgrade Medieval Oak town hall to level 4. His hut is level 5 and he will build anything but the town hall. I tried with another level 5 hut builder but they both won't do it. With development features enabled, it says they are on the clear step.

**Comment by marchermans** [comment]
We will need more information. Like logs and other things that are normally in the issue template.
This issue will stay marked as invalid untill things like logs, worlds, and other details are provided by  @Midnight888

**Comment by Midnight888** [comment]
After leaving the builder for 25-30 minutes on clear step he started building. I've noticed that the bigger a build is the longer they will stay on clear step (sitting in front of their hut).
