### ISSUE TITLE
Other Chests for Postbox and Stash

### ISSUE THREAD

**Issue by HugoOlafSchnittlauch** [ldtteam/minecolonies#4937]
Im using: minecolonies 0.11.918.-Beta-universal

When I try to Craft Stash or a Postbox JEI say I Need a regular Vanilla Chest. I can´t use Chests from Quark.

Can you please add the Tag: Accepts any: forge:chest like the in the Warehous-Recipe, so we can use all types of chests and not only minecraft:chest.

LG Jonas

**Comment by marchermans** [comment]
Good catch.
