### ISSUE TITLE
Builder Not Building Medieval oak Town Hall Level 4

### ISSUE THREAD

**Issue by Midnight888** [ldtteam/minecolonies#4938]
Version: minecolonies-1.12.2-0.11.804-RELEASE-api.jar

### Expected behavior
1. The builder builds the town hall (Medieval oak) Upgrading to level 4.

Description :
Builder stands in front of their hut. They do not collect items or interact with anything. This is the only upgrade/building they refuse to do. I have tried with 2 builders with huts both at level 5. The builders can repair it but not upgrade.

### Steps to reproduce the problem

1. Build a level 3 Medieval oak town hall.
2. Attempt to upgrade.
3. Give the builders all necessary materials. 
4. ... Profit

**Comment by marchermans** [comment]
We will need more information.
Things like logs.
Worlds
Any details.
Research progress.

We won't be able to sniff your problem from our desks i think. :P If we could that would be amazing but none of us can. So sadly this issue will stay invalid untill more information is provided.

**Comment by Midnight888** [comment]
After leaving the builder for 25-30 minutes on clear step he started building. I've noticed that the bigger a build is the longer they will stay on clear step (sitting in front of their hut).

**Comment by marchermans** [comment]
Yeah they scan and determine what they need.
That is something that just needs to happen sadly, as such it will happen now and then.
