### ISSUE TITLE
1.11-0.6.2306 kicks player after being added to colony if building is going

### ISSUE THREAD

**Issue by kreezxil** [ldtteam/minecolonies#494]
### Minecolonies version

1.11-1.11-0.6.2306

### Expected behavior

- Add player to colony
- business as usual

### Actual behaviour

- if a builder is building
- add player to colony
- apparently builder is tring to tell that player stuff too but for w/e reason can't and kicks them

### Steps to reproduce the problem

1. go to townhall
1. add player to townhall
1. get that builder working

crash log: http://pastebin.com/dD9a1R3x <-- from player's client

**Comment by Raycoms** [comment]
Hmm is that a 100% reproduce. Can't find minecolones inside the log.

2017-01-21 14:39 GMT-02:00 kreezxil <notifications@github.com>:

**Comment by kreezxil** [comment]
I can't guarantee that yet, are you familiar with the "already building" thing? The player was on my server no more than 5 minutes, hadn't crafted anything, I tp'd him to my base and added them at the town hall. Then all started happening bad. I can setup a test server to test just this one thing.

**Comment by Raycoms** [comment]
No never saw that. But it's for sure not related with the builder. It's
related to the minecraft rendering.

2017-01-21 14:45 GMT-02:00 kreezxil <notifications@github.com>:

**Comment by kreezxil** [comment]
ok, i'll setup a test to see if i can isolate it

**Comment by Raycoms** [comment]
Great that'd help us a lot. Thanks

2017-01-21 15:21 GMT-02:00 kreezxil <notifications@github.com>:
