### ISSUE TITLE
Lumberjack Freezes w/ Dynamic Trees

### ISSUE THREAD

**Issue by nephatrine** [ldtteam/minecolonies#4941]
### Minecolonies version

Version: **minecolonies-1.12.2-0.11.841-ALPHA-universal**

### Expected behavior

Lumberjack should work correctly with Dynamic Trees.

### Actual behaviour

Seems to be same issue as #3749 which was closed as fixed. Lumberjack pauses and doesn't seem to process correctly.

### Steps to reproduce the problem

All my trees are Dynamic Trees. Just want Lumberjack to chop 'em down.

### Logs:

https://pastebin.com/5nV8QtV9

**Comment by marchermans** [comment]
Sadly this is for 1.12.2 and we are in EOL Support mode for that Minecraft version, meaning that we only will bugfix core bugs in the mods code, and no compatibility issue or bring new features to this minecraft version.

We wish that we had the manpower and time to maintain several different mc versions at once. But that is simply not the case. We are already stretched relatively thin.

As such I hope you can understand that we can not fix this issue.

Greets, Orion.

**Comment by Tenchu98** [comment]
I understand you are in EOL, but that seems strange given that it is still the main version for developing modpacks. I am currently experiencing the same issue and was hoping you had a fix for it. oh well.
