### ISSUE TITLE
Fortress fletcher doesn't have fletcher block

### ISSUE THREAD

**Issue by Kao713** [ldtteam/minecolonies#4943]
### Minecolonies version

Version: minecolonies-0.11.936-ALPHA-universal.jar

### Expected behavior

- Be able to build fortress fletcher

### Actual behaviour

- Can't build fortress fletcher because there is no fletcher block

### Steps to reproduce the problem

1. Try to place fortress fletcher
2. That's all

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

**Comment by Raycoms** [comment]
#4536 please
