### ISSUE TITLE
Right click on Portable Crafter crashes both the server & client

### ISSUE THREAD

**Issue by Thanaen** [ldtteam/minecolonies#4944]
### Minecolonies version

Version: MC-TechColonies 2.8

### Expected behavior

- Using the [Portable Crafter](https://www.curseforge.com/minecraft/mc-mods/portable-crafter-forge) works

### Actual behaviour

- When you try to use the [Portable Crafter](https://www.curseforge.com/minecraft/mc-mods/portable-crafter-forge) (right click when the item is in hand), both the client and the server you're playing on crashes

### Steps to reproduce the problem

1. Make a [Portable Crafter](https://www.curseforge.com/minecraft/mc-mods/portable-crafter-forge)
2. Select it in your hand
3. Right click
4. Yay

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: https://gist.github.com/Thanaen/76cacf325e9e84c97eee9d968a1a8bc3
- crashlog: https://gist.github.com/Thanaen/76cacf325e9e84c97eee9d968a1a8bc3

**Comment by marchermans** [comment]
This is not for minecolonies.... Closing. Create an issue with the Portable Crafter mod.

**Comment by Thanaen** [comment]
Note that [this](https://www.curseforge.com/minecraft/mc-mods/portable-crafter-forge) mod should probably be removed from the TechColonies modpack, as the mod [CraftingCraft](https://www.curseforge.com/minecraft/mc-mods/craftingcraft) already adds a portable crafting table.

**Comment by Thanaen** [comment]
The TechColonies modpack is broken. Where should I report it then ?
This mod is included in your modpack, reporting it here makes sense to me.

**Comment by Greypelt** [comment]
It should be reported on the specific mods page, the people running the modpack aren't able to edit that code directly. Report it here [https://github.com/MarioAndWeegee3/Portable-Crafter-Forge/issues/1](url)

**Comment by Thanaen** [comment]
The issue [already exists on their side](https://github.com/MarioAndWeegee3/Portable-Crafter-Forge/issues/1)

I'll just make a second issue about the fact that this mod is redundant

**Comment by Raycoms** [comment]
Modpack issues please report on the discord. These issues here are only for the minecolonies mod.

**Comment by Thanaen** [comment]
Will do

**Comment by Thanaen** [comment]
Done, but apparently issues & suggestions on modpacks aren't that welcomed on the discord
