### ISSUE TITLE
Farmer asking for hoe for ages and stucked

### ISSUE THREAD

**Issue by DiabolosMan** [ldtteam/minecolonies#4946]
### Minecolonies version

Minecolonies version 0.11.933-ALPHA
Minecraft version 1.15.2
Forge version 3.11.77

### Expected behavior

- Farmer go to work with its hoe
- No more asking for hoe

### Actual behaviour

- Farmer is asking for Hoe. We can fullfill request but still show the request
- Request is not cancellable
- The crafter request is not cancellable either
- See screenshots

![2020-05-06_21 51 34](https://user-images.githubusercontent.com/63854770/81482519-f20cc080-9237-11ea-8d32-604109ba050a.png)
![2020-05-06_21 52 35](https://user-images.githubusercontent.com/63854770/81482521-f2a55700-9237-11ea-97bb-eb3d3eff6128.png)

### Steps to reproduce the problem

1. Have a farmer and a crafter in a colony
2. Let the farmer do its job and wait until it asks for a hoe
3. Wait the the crafter does the craft (it has sticks and stone in his inventory, same in hut, and there is the materials in warehouse also)
4. Nothing happens. So fullfill the request. The hoe is in the farmer inventory… However, still asking for a hoe and does not do anything
5. Try to cancel requests, none of the 2 requests in screenshot are cancellable

6. I tried to fire the farmer and free its inventory, assign another worker, and same behavior

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

**Comment by Raycoms** [comment]
Fixed this right now in my current branch, will be fixed this weekend =)

**Comment by DiabolosMan** [comment]
It is still not fixed in minecolonies-1.15.2-0.11.949-universal-universal. Is it supposed to be fixed in this version ?
It is now 17 days that my farmer does not do anything at all, I cannot cancel and I have no workaround. I tried to fire and hire another worker and have the same problem.

**Comment by Raycoms** [comment]
He is working fine for me again in the newest. Why can't you cancel the request, and what kind of hoe are you trying to give him?

**Comment by DiabolosMan** [comment]
You have all the answers in the screen shot above in the issue.
I gave her a wood hoe, a stone hoe and a diamond hoe. I fullfilled successfyllu the request with all the hoes…. But still showing the same message in picture. There is no cancel button for the crafter, when I cilck cancel on hoe, it does not do anything. If I go to the man who is supposed to craft it, I gave him stones and sticks in his inventory AND in his hut. I put a stone hoe in wharehouse (I also put the ingredients for crafting)….. But I cannot do anything

**Comment by Raycoms** [comment]
This seems weird, did you try /mc colony requestsystem-reset on your colony?

**Comment by DiabolosMan** [comment]
And also a strange thing….. If you look to the screenshot, you will see that the farmer used the stone hoe a little bit…. It was just before I build the crafter…. In fact, it happens since I have a crafter

No I did not try. I am not admin. I will ask the admin

**Comment by DiabolosMan** [comment]
Indeed, the command fixed the issue. Thanks. So you can close the bug. If it happens again, I will create a new one
