### ISSUE TITLE
Combat Academy Level 5 Medieval Dark Oak not buildable

### ISSUE THREAD

**Issue by BlackFranky** [ldtteam/minecolonies#4948]
The Combat Academy (Style: Medieval Dark Oak) can not be upgraded to Level 5, because the clock item is not recognised correctly by the builder.

If I put the clock manually into the builder's inventory or into any chests of the builder's hut it is not recognised in the needed items list.
If I click on the add button in the item list, the option vanishes, but comes back immediately without doing anything. The clock item is still in my inventory afterwards.

**Comment by Raycoms** [comment]
Yeah that is already in #4510
