### ISSUE TITLE
Builder will not build if inventory is full.

### ISSUE THREAD

**Issue by ProsperCraft** [ldtteam/minecolonies#495]
### Minecolonies version
minecolonies-universal-1.11-0.6.2357

### Expected behavior

Builder builds even if his inventory is full.

### Actual behaviour

Builder is not builder, so I remove one item from his inventory and he starts building again.

**Comment by Raycoms** [comment]
He will try to dump his full inventory into the chest if his inventory gets
full and if the chest is full as well he will request that someone empties
it.
That's necessary for correct working.

2017-01-21 19:17 GMT-02:00 ProsperCraft <notifications@github.com>:

**Comment by ProsperCraft** [comment]
He didn't request someone empty, he just stared at his construction project doing nothing.

**Comment by Raycoms** [comment]
hmm will have to test that with the 1.11 then...

2017-01-21 19:53 GMT-02:00 ProsperCraft <notifications@github.com>:

**Comment by forReason** [comment]
It is not only the builder but Every worker. 

This may be related to worker not telling what He needs when items to build are messing.

**Comment by Raycoms** [comment]
I fixed that problem now the next push may fix the remaining problems as
well.

2017-01-21 20:51 GMT-02:00 Julian B. <notifications@github.com>:
