### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by staviq** [ldtteam/minecolonies#4953]
minecolonies-0.11.918-BETA-universal

The game crashed right after i got the message about a raid i think, starting with "Buckle up", didn't read it whole before the crash.

[crash-2020-05-10_04.11.06-server.txt](https://github.com/ldtteam/minecolonies/files/4605030/crash-2020-05-10_04.11.06-server.txt)

[latest.log](https://github.com/ldtteam/minecolonies/files/4605029/latest.log)

[config.zip](https://github.com/ldtteam/minecolonies/files/4605032/config.zip)

**Comment by staviq** [comment]
Just got another one.

I think it's actually the stash thingy. Both times it crashed shortly after i put things for delivery in the stash.

**Comment by Raycoms** [comment]
Please update to the latest
