### ISSUE TITLE
Fisherman is broken

### ISSUE THREAD

**Issue by lebanni** [ldtteam/minecolonies#4955]
minecolonies-0.11.937-ALPHA-universal.jar

Building is Nordic lvl1. Fisherman is trying to fish from inside of the building, waisting the fishing rod. Sometimes, he goes outside in the water. He rarely succeeds to catch fish.

**Comment by Raycoms** [comment]
screenshot please

**Comment by lebanni** [comment]
https://youtu.be/N9KZpiWWYsI

**Comment by Raycoms** [comment]
Can you send me that world?

**Comment by lebanni** [comment]
https://www.dropbox.com/s/pn43crgmmm75n0z/world-2020-05-10_10-41-39.zip?dl=0

**Comment by Raycoms** [comment]
Okay, fix will come out probably this weekend.

On another note, which biome mod did you use? The biomes look amazing

**Comment by lebanni** [comment]
It's Terraforged, and The Lost Cities. I also have Traverse, but I don't think it's handled.
