### ISSUE TITLE
Crash on death of deliveryman

### ISSUE THREAD

**Issue by SirSmuggler** [ldtteam/minecolonies#4956]
### Minecolonies version
Version: 0.11.937-ALPHA

### Expected behavior
No crash

### Actual behaviour
My world is in a state of defending a barbarian invation, and the game crashes every time I load that save.
Reading the crash log it seems to happen becouse a delivery man get killed by a barbarian and the request system tryes to reasign active requests or something like that.

### Steps to reproduce the problem
Hard to say for sure. Kill a delivery person with active requests?

### Logs: Latest.log and crashlog at https://gist.github.com/
https://gist.github.com/SirSmuggler/4d051a012495f23e0151d8eead6c56f0

**Comment by Raycoms** [comment]
I'll add it to my PR too.
