### ISSUE TITLE
friend needs help

### ISSUE THREAD

**Issue by LadyUmbreon** [ldtteam/minecolonies#496]
### Minecolonies version

version 1.10.2 

so my friend accidentally broke her town hall on our server and can't place a new one. she's wondering if there is a way she can fix this problem?

**Comment by forReason** [comment]
There are two solutions
1 build The  townhall in the exct same spot 
2 if that is not Working you can delete the colony and Bild a new one please look up The command with /help colony

**Comment by marvin-bitterlich** [comment]
@LadyUmbreon our server command (for ops only) is `/mc` so you find out the colony id with `/mc colonies list` and then delete the one you want gone with `/mc colony <number> delete`

**Comment by Raycoms** [comment]
Hello @LadyUmbreon she can place her townhall inside a certain radius around the center of her colony.
