### ISSUE TITLE
Sawmill overproducing

### ISSUE THREAD

**Issue by Sorkin02** [ldtteam/minecolonies#4960]
0.11.804
Before reporting: Update to the newest minecolonies alpha and see if your issue might be fixed already.
-->

Version: 

### Expected behavior

- <The miller producing the right amount of products->

### Actual behaviour

- 

### Steps to reproduce the problem

1. <Start the colony as usual>
2. <Build a sawmill and assign a miller>
3. <Build a storage and deliverymen>
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

**Comment by Asherslab** [comment]
follow the issue template
