### ISSUE TITLE
Miner AI stuck after mine shaft crossed with natural cave

### ISSUE THREAD

**Issue by staviq** [ldtteam/minecolonies#4961]
minecolonies-0.11.938-BETA-universal

Stuck forewer like this, trying to pathfind to the other side.

When i build bridge for her, she immadiately went on to continue mining on the other side.

![2020-05-11_02 55 30](https://user-images.githubusercontent.com/15910535/81515215-3fba2380-9333-11ea-8a97-47cf20a0642f.png)

**Comment by Raycoms** [comment]
That one I hadn't seen yet, normally the miner crosses the shaft completely with a cobble tunnel.

**Comment by Raycoms** [comment]
Fixed with newest pr and outcoming version
