### ISSUE TITLE
Repair on player housing wooden1 NPE

### ISSUE THREAD

**Issue by Obbay2** [ldtteam/minecolonies#4962]
### Minecolonies version
minecolonies-0.11.936-ALPHA

### Expected behavior
Repair to be queued for builder to fix.

### Actual behaviour
NullPointerException on server, nothing seems to happen on client.
NullPointerException at com.ldtteam.structures.helpers.Structure.rotate(Structure.java:322)
...

### Steps to reproduce the problem
1. Build wooden1 player housing template
2. Try to repair it.
3. Profit...?

### Logs: Latest.log

https://gist.github.com/Obbay2/4f850689834b822de38b2326f1e91198

**Comment by Raycoms** [comment]
update structurize and minecolonies
