### ISSUE TITLE
No upgrade button on playerhousing wooden1

### ISSUE THREAD

**Issue by Obbay2** [ldtteam/minecolonies#4963]
Minecolonies version
minecolonies-0.11.936-ALPHA

Expected behavior
Upgrade button to build to wooden2 template

Actual behaviour
No upgrade button

Steps to reproduce the problem
1. Build wooden1 player housing template
2. Open build menu and no upgrade button exists.
3. Profit...?

**Comment by Raycoms** [comment]
Yes, that is a schematic issue please #4536 for that
