### ISSUE TITLE
Baker cannot be taught to make bread

### ISSUE THREAD

**Issue by staviq** [ldtteam/minecolonies#4964]
minecolonies-0.11.938-BETA-universal

![2020-05-11_04 52 14](https://user-images.githubusercontent.com/15910535/81520068-7bf58000-9343-11ea-82fd-a0c944c03a85.png)

![2020-05-11_04 52 19](https://user-images.githubusercontent.com/15910535/81520092-8f085000-9343-11ea-8e95-405bc85d3a99.png)

**Comment by Raycoms** [comment]
Yes, because the baker already knows the bread recipe, there is no need to teach the baker that one.

**Comment by staviq** [comment]
Hmm, ok, why then is he constantly complaining that i need to teach him a recipe to work with ?

**Comment by Raycoms** [comment]
Check out page 2 of his GUI

**Comment by ravenbuilder934** [comment]
You need to choose which recipe you want him to make
