### ISSUE TITLE
Multiple villagers sleeping in the same bed

### ISSUE THREAD

**Issue by staviq** [ldtteam/minecolonies#4965]
minecolonies-0.11.938-BETA-universal

After switching home assignment from auto to manual, unassigning homes, and swithing back to auto, some beds are assigned to multiple villagers even though buiding gui says everything is ok.

![2020-05-11_04 12 33](https://user-images.githubusercontent.com/15910535/81520234-03db8a00-9344-11ea-9377-f83cb40be894.png)

**Comment by Raycoms** [comment]
Yeah that can happen for 1-2 nights until it balanced out. However it should then balance itself out and then they will sleep separately again.
