### ISSUE TITLE
Miner Inactivity

### ISSUE THREAD

**Issue by Stultophobia** [ldtteam/minecolonies#4967]
My miner is standing staring at a wall. 
When I reset her, she starts back up at her hut, makes her way back and stares at the wall again. She eats and sleeps but doesn't work. She's made 2 levels with nodes and now just stares at the wall.
I previously contacted the author because of an issue I had with the released version on the game and he/she advices me to go onto the 1.15.2 Alpha which fixed my previous issue and now I have this one. I have spent a few hours trying to figure it out and nothing works. 
![IMG_20200511_131931](https://user-images.githubusercontent.com/65118449/81561197-b6ced680-938a-11ea-966f-680ef28b5a10.jpg)

**Comment by ravenbuilder934** [comment]
Does she have a pickaxe, shovel, wood planks, torches, cobblestone, and fences?

**Comment by Raycoms** [comment]
When they stare at a wall make a tunnle into the direction they're staring

**Comment by Stultophobia** [comment]
Yes, she has all of the above items and all tools are currently at her level

**Comment by Stultophobia** [comment]
That fixed it thank you, it seems that she started working through a wall and then maybe stopped when she couldn't reach any more blocks and just stared at the wall.Many thanks!

**Comment by Raycoms** [comment]
Yeah, it happens rarely through some glitch, but sometimes they get stuck due to that and mining them a little path fixes it.
