### ISSUE TITLE
[fd5ba7d] - Builder wont request tools anymore

### ISSUE THREAD

**Issue by forReason** [ldtteam/minecolonies#497]
### Minecolonies version

version lastest build of today
### Expected behavior

- Builder requests tools
- Builder clears area
- Builder requests material
- Builder starts building

### Actual behaviour

- Builder will not request Tools anymore

### Steps to reproduce the problem

1. build Townhall
2. Build Builders Hut
3. Click "Build Building"

**Comment by Raycoms** [comment]
Should be fixed as well I think in the next one.
