### ISSUE TITLE
[TechColonies 2.6] Builder AI crash

### ISSUE THREAD

**Issue by Thanaen** [ldtteam/minecolonies#4970]
### Minecolonies version

Version: minecolonies-0.11.907-ALPHA (Modpack TechColonies 2.6)
--

The builder regularly has a red icon on his head (like he needs something), then tells me that he had some troubles with its AI, and that I should contact the devs and show them the latest.log file.
So here we are !

Haven't figured out repro steps yet, seems to happen very regularly when building.

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: https://gist.github.com/Thanaen/36fa293805d8640146f98af814e41de5
In this gist, they are two files: first the whole latest.log file, then a builder-related crash log found in the latest.log (in case it helps)

**Comment by Thanaen** [comment]
Note: It didn't happen for a long time after the creation of the colony, but now it seems systematic.

**Comment by Obbay2** [comment]
I filed an issue with this same bug awhile ago. It should be fixed with a newer version of minecolonies. See #4835.

**Comment by Raycoms** [comment]
4966
