### ISSUE TITLE
minecolonies-0.11.938-BETA on 1.15.2  -- Some Huts are missing textures and turn invisible or black/pink block"

### ISSUE THREAD

**Issue by madden92** [ldtteam/minecolonies#4971]
### Minecolonies version

minecolonies-0.11.938-BETA on  Minecraft    1.15.2 

The following huts are missing textures  and turn invisible or black/pink block:
Farm
Lumberjack Hut
Warehouse
Shephers Hut
Swineherderhut 
Chiken hut
Archery 
Combat Archery
Stone SMeltery
Flower Shop
University 
Hospital

**Comment by someaddons** [comment]
optifine's issue
