### ISSUE TITLE
Game crash on loading save after new Minecolonies update

### ISSUE THREAD

**Issue by RagingAlpaca** [ldtteam/minecolonies#4976]
### Minecolonies version

Version: minecolonies-0.11.940-ALPHA-universal

### Expected behavior
Minecraft should be able to load my save with the updated version of Minecolonies + needed version of structurize(structurize-0.10.313-RELEASE, with the newest update)

### Actual behaviour
When I try to load in my save I was using before the last (2) updates (The save was used in minecolonies-0.11.918-BETA-universal (minecolonies-0.11.938-BETA-universal gives me the same error as the newest version.)) my game freezes and eventually crashes

### Steps to reproduce the problem

1. Load a minecolonies world with old version I mentioned above
2. Try loading it in with newest version of minecolonies
3. Game crashes

- latest.log: https://gist.github.com/RagingAlpaca/acc5dfa19fbdd4a099d078a8a40a126a
- crashlog: https://gist.github.com/RagingAlpaca/9854a748ac20cb1e8d310b270affa3ac

**Comment by Raycoms** [comment]
What structurize version did you download? You seem to have gotten a deobfed one?

**Comment by RagingAlpaca** [comment]
> 
> 
> What structurize version did you download? You seem to have gotten a deobfed one?

I downloaded the new one: 0.10.315-ALPHA. There were only two files in this so I thought I had to put these files in the older version's map (0.10.313) Maybe that is something that I should not have done. But structurize wouldnt load otherwise

**Comment by Raycoms** [comment]
You should only download the universal jar and not the api or other jars from curseforge

**Comment by RagingAlpaca** [comment]
Alright, I see what I did wrong. It works now. Thanks a lot!
