### ISSUE TITLE
Fulfilling builder's requests twice.

### ISSUE THREAD

**Issue by ArchangelEkim** [ldtteam/minecolonies#4977]
### Minecolonies version

Version: 0.11.939-ALPHA

### Expected behaviour
Fulfil builder request once without asking again.

### Actual behaviour
Have to fulfil builder request twice which takes the requested amount of items twice before the request disappears properly.

I've noticed it on both 1.12 and 1.15 which I'm using now.

- After fulfilling the builder request once through the request window, without closing the window, the same request appears again a few seconds later and fulfilling that takes another amount of requested resources.

### Steps to reproduce the problem

1.  Wait for a builder request for building resources of any size
2.  Fulfil that request through the builder's window by going to 'I will do that' button then immediately open the requests window.
3.  Without closing the window after fulfilling the request the same request will pop up after a few seconds.
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

**Comment by Raycoms** [comment]
Should be fixed in newest
