### ISSUE TITLE
Citizen sharing bed in hospital

### ISSUE THREAD

**Issue by DiabolosMan** [ldtteam/minecolonies#4978]
### Minecolonies version

Minecolonies version 0.11.940-ALPHA
Minecraft version 1.15.2
Forge version 3.11.78

### Expected behavior
Each sick citizen should be in different beds

### Actual behaviour
Sicks citizens share same hospital bed ;-)

See pictures:
![2020-05-12_13 58 50](https://user-images.githubusercontent.com/63854770/81690539-b7836d80-945b-11ea-9812-89ff11057d2a.png)
![2020-05-12_13 59 02](https://user-images.githubusercontent.com/63854770/81690541-b81c0400-945b-11ea-841a-2ad495ee21b9.png)

**Comment by Raycoms** [comment]
Not possible to reproduce this, similarly happens sometimes in houses. I believe vanilla messes up the bed occupied state. I'll close this for now.

**Comment by DiabolosMan** [comment]
It happens to me everydays. I have 64 citizen so I have always people in hospital.... So my healer consumes a lots of carrots and potatoes ;-)
I do really think it is strange to have always someone in hospital. They are so often ill.… And maybe it is the reason it happens SO frequently.

It is not a blocking bug, it is just funny to see citizens in hospital sharing beds ;-)

For ex, in the screenshot below done few minutes ago, if you look well, there are 5 citizens. I had from left to right:
1 empty bed, the healer, 1 bed occupied by two citizens and another bed with ALSO 2 citizens.
In the back, there are 3 unoccupied beds.
![2020-05-28_13 23 57](https://user-images.githubusercontent.com/63854770/83140270-1ac4ff00-a0ee-11ea-8fd1-61f4a67a482e.png)

I noticed that most of the time, it is bed in the middle where it happens the most.

Hope it helps.

**Comment by Raycoms** [comment]
I took a colony with 20 citizens, made all of them sick, restarted the world several times
and they would just be fine and choose the right bed. Maybe I have to restart the instance completely to reproduce it.
