### ISSUE TITLE
Builders won't place racks in warehouse lvl 2

### ISSUE THREAD

**Issue by KateKit16** [ldtteam/minecolonies#4980]
I told one of my builders to upgrade the warehouse and they get pretty far in the build and then they have to place the racks and then they just stand there with the racks in their hand and do nothing. I have fired and re-hired them. I have pause and restarted them. I have canceled the build and had my other builder upgrade it. nothing works. if I knew where the racks went I might be able to fix it but I don't.

I am playing MC Eternal lite on twitch. minecolonies-1.12.2-0.10.714-RELEASE-universal.jar this is all the info I have.

**Comment by Raycoms** [comment]
Try updated to the newest
