### ISSUE TITLE
Game Breaking Crash Related to this Mod That We've Yet to Find A Pattern To

### ISSUE THREAD

**Issue by SCBionicle** [ldtteam/minecolonies#4982]
Sorry, I would really give more info if I could figure out what exactly is causing this to crash but it's literally crashing at random 3 times in 15 minutes with the stack trace pointing to an API used by this mod. I will post the log in the appropriate section. The only thing I can gather is that it's related to the request system and the delivery men.

### Minecolonies version

Version: minecolonies-0.11.918-BETA-universal

### Expected behavior

- Not crash

### Actual behaviour

- Crashes where it boots all players and kills the dedicated server.

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: https://gist.github.com/SCBionicle/6bdad85388245218db2ad96683873d3a
- crashlog:

**Comment by Raycoms** [comment]
Fixed in the latest version.
