### ISSUE TITLE
Baker won't make pumkin pie

### ISSUE THREAD

**Issue by Perlo0ung** [ldtteam/minecolonies#4984]
### Minecolonies version

Version:  minecolonies-0.11.944-ALPHA-universal

### Expected behavior

- Baker should make all food selected.

### Actual behaviour

- Baker constantly bakes bread, cookies and cake without any problems, but refuses to make any pumkin pie.

### Steps to reproduce the problem

1. Activate pumkin pie for baker
2. wait

### Logs: Latest.log and crashlog at https://gist.github.com/

- logs: no related problems or excetions shown

**Comment by Perlo0ung** [comment]
Update: 
If only pumpkin is activated he does bake it.
The wierd thing is that if bread is selected for example, he always requests new wheat and ignores other recipes.

**Comment by Raycoms** [comment]
Yeah, he will basically make what he can, and that's bread. It's kinda an exclusive list. There is no code to vary through them (it's either or).

**Comment by Perlo0ung** [comment]
Then the select option is kinda misleading, since u can activate multiple. This implies that he is able to craft all of them

**Comment by Raycoms** [comment]
It's because you could turn on pumpkin pie and cookies and he would craft whichever has the available resources. But since he always has the resources for bread that always works.

I guess we could add some random order to the list to have him make sometimes the others too

**Comment by Perlo0ung** [comment]
I actually looked at the code. How its done at the moment is pretty good, theres not much variance and its simple as is. Maybe make it so that the list just rotates, then he basicly just tries to make one after the other.

**Comment by ToMe25** [comment]
I will look at this tomorrow, but i will probably just end up making it random like Raycoms suggested.

**Comment by ToMe25** [comment]
as a defined order might not be that great sometimes, and also fitting imo.
