### ISSUE TITLE
Suggestion: Pirates remaining time/number somewhere + spies

### ISSUE THREAD

**Issue by DiabolosMan** [ldtteam/minecolonies#4986]
### Minecolonies version
Minecolonies version 0.11.940-ALPHA
Minecraft version 1.15.2
Forge version 3.11.78

### Actual behaviour
I was attacked yesterday evening by a pirate ship… And while my knights were holding the unstopable waves of pirates I tried to destroy all spawners…. After a long time,  I thought I destroyed all and went back to my village to help my knights. Hopefully, thanks to the 'spies' in combat academy, I was able to locate the pirates with their aura…. but until the morning. During the day, all auras disappeared and I had no more spy. So it was complicated to distinguish my citizens from the pirates. To locate them I was looking in the chat for citizen died location which is not nice.
I thought it was finished but I was missing 2 spawners (underwater) and when destroyed, I had no idea if I had destroyed all... until I noticed no more citizen died. After few nights, the ship disappeared.

### Suggestion
- Spies work also during day (can consume other gold) or add another kind of resource
- Each time a spawner is destroyed, a chat message saying the number of spawners left to destroy
- When all spawners are destroyed, a chat message saying the pirate ship is destroyed and the number of remaining pirates
- Like for barbarians, when 5 pirates are left, a chat message
- When everything is done, a chat message saying you defended the colony from pirates

If you think it can be instead an object like the 'clipboard' that could summarise that kind of info, it could be enough.

**Comment by someaddons** [comment]
I've been thinking to use the vanilla raidbar tied to the spawner count as raid progress indicator. Pirates keep spawning so an X are left message would only make sense once the spawners are killed

**Comment by DiabolosMan** [comment]
Yes perfect! The raid bar could be idealto have the spawner count as a raid indicator, and better than chat messages. And of course, the "X are left message" is only when all spawners are destroyed

**Comment by Raycoms** [comment]
Please list in #4535

**Comment by DiabolosMan** [comment]
In which version is it supposed to be integrated ? Is it possible to find somewhere from which version  the pull request is included ?

**Comment by Raycoms** [comment]
In the newest

**Comment by DiabolosMan** [comment]
Not fixed, cf the gloabl bug I am entering about Pirate ship: https://github.com/ldtteam/minecolonies/issues/5209

**Comment by DiabolosMan** [comment]
Confirmed that no raid is shown when a pirate attack occurs
