### ISSUE TITLE
Minecolonies crash when near town.

### ISSUE THREAD

**Issue by Callamasthia** [ldtteam/minecolonies#4987]
Version: minecolonies-0.11.910-ALPHA-universal.jar

My Minecraft crashes from time to time but this time I got an error log, apparantly something has to do with minecolonies, no idea I hope you can help me.
It crashed when I went near my village.
 
[crash-2020-05-13_15.22.10-client.txt](https://github.com/ldtteam/minecolonies/files/4622236/crash-2020-05-13_15.22.10-client.txt)

**Comment by Raycoms** [comment]
Yeah, this is one of the 1.15 issues that's weird. We're getting around one of these per day. This doesn't seem to be anything on our side but instead probably something on forges side.

There is unfortunately no way to reproduce this nor fix it on our end.
