### ISSUE TITLE
No chat message when decorations finish building

### ISSUE THREAD

**Issue by ravenbuilder934** [ldtteam/minecolonies#4988]
### Expected behavior

After the builder finishes building a decoration, there is fireworks and a chat message like there is for huts.

### Actual behaviour

No fireworks, no chat message. (There is a message when the builder starts building a decoration though.)

### Steps to reproduce the problem
1. Have the builder build a decoration
2. Wait for him to finish
4. ... Profit

**Comment by PowerSchill** [comment]
@Raycoms want to assign this to me and I will take a look at it. This is another nuisance I've personally encountered on the server. :)
