### ISSUE TITLE
crash when placing Supply Camp ver. 0.10.771

### ISSUE THREAD

**Issue by SamoRDSA** [ldtteam/minecolonies#4991]
### Minecolonies version

Version: minecolonies-0.10.771-RELEASE-universal.jar

### Expected behavior
Place Supply Camp. Supply Camp placed... game continues

### Actual behaviour
When placing Supply Camp game crashes, same issue with different version 

### Steps to reproduce the problem

1. new world 
2. build supply camp
3. place supply camp
4. ... game crashes

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: don't know where to get that
- crashlog: https://github.com/SamoRDSA/crashlog

**Comment by Raycoms** [comment]
Update to latest

**Comment by SamoRDSA** [comment]
isn't that the latest stable version?

**Comment by someaddons** [comment]
https://www.curseforge.com/minecraft/mc-mods/minecolonies/files
alphas are stable too just newer/less tested yet

**Comment by SamoRDSA** [comment]
Ok thanks
