### ISSUE TITLE
Citizens not working correctly

### ISSUE THREAD

**Issue by 486dx33mhz** [ldtteam/minecolonies#4992]
### Minecolonies version

Version: 0.11.811-BETA 

### Expected behaviour

- Citizens performing jobs as usual, and working correctly.

### Actual behaviour

- Citizens to not move to do their job and are idle, but do move reacting to time by going home, but couldn't properly react to weather, walking around randomly.

### Steps to reproduce the problem

1. Asked builder to upgrade a house from Level 1 to Level 2, then these errors occured.
2.  n/a
3.  n/a
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/
- latest.log: https://gist.github.com/486dx33mhz/1310c54bdb8ed540170ff48caf0bac17
- crashlog: n/a

**Comment by Raycoms** [comment]
upgrade to latest please

**Comment by 486dx33mhz** [comment]
Hi Raycoms, just upgraded to latest, and the same errors are still being output. Unfortunately I am not the host of the server, so I cannot get the logs right now as the admin is AFK.

**Comment by Raycoms** [comment]
The log above doesn't show any error though too. (Is it the latest alpha you've updated too).

**Comment by 486dx33mhz** [comment]
Latest alpha, yes. When the user having the issue joins the server it crashes the server, and I was sent this crash log from the older version (admin did it hastily as he is WFH and cannot reply to DMs right now) 
[crash-2020-05-13_10.36.28-server.txt](https://github.com/ldtteam/minecolonies/files/4624497/crash-2020-05-13_10.36.28-server.txt)

**Comment by Raycoms** [comment]
![image](https://user-images.githubusercontent.com/6438347/81862535-c6544800-9561-11ea-8545-1a9082478da8.png)

**Comment by compulshun** [comment]
Hey Raycoms, admin here, here's two crash logs from after updating to latest alpha:
[crash-2020-05-13_13.03.06-server.txt](https://github.com/ldtteam/minecolonies/files/4624592/crash-2020-05-13_13.03.06-server.txt)
[crash-2020-05-13_13.12.33-server.txt](https://github.com/ldtteam/minecolonies/files/4624593/crash-2020-05-13_13.12.33-server.txt)

**Comment by Raycoms** [comment]
Okay, I got a nasty deadline tomorrow, so I won't be able to look into this today unfortunately. Normally we don't offer much support anymore for 1.12 but since it is a gamebreaking bug I will definitely fix this as soon as I get to it. Sorry if this might delay a day.

**Comment by compulshun** [comment]
I compiled your fix tonight and have it running on the server now - seems to have fixed the error. You're a saint, thank you!

**Comment by Raycoms** [comment]
Awesome
