### ISSUE TITLE
[Suggestion] Add configuration option to control university research speed

### ISSUE THREAD

**Issue by Scorch-Mechanic** [ldtteam/minecolonies#4993]
I play solo and I don't have a habit of leaving my game running while I'm AFK. Early research time requirements of 1, 4, and even 8 hours are certainly reasonable, but the higher tier research period requirements of 16 and 32 hours are simply out of reach for me.

**Comment by Raycoms** [comment]
Those are intentionally difficult to achieve, research is not meant to be maxed out in most games.
However, we're thinking about some ways you can get it progress a little bit during offline sessions too.
