### ISSUE TITLE
University research shows wrong level

### ISSUE THREAD

**Issue by Obbay2** [ldtteam/minecolonies#4994]
### Minecolonies version
0.11.936-ALPHA

### Expected behavior
Guard tower levels should be achievable to research

### Actual behaviour
![image](https://user-images.githubusercontent.com/4176173/81891310-f220ff00-955c-11ea-844f-90201df88199.png)

### Steps to reproduce the problem
1. Create university building
2. Look at the combat tree
3. Notice the Feint and Avoid paths have the wrong guardtower levels

### Logs
No logs

**Comment by Raycoms** [comment]
No, it's because they are additive. 3 level 4 guard towers = 12
