### ISSUE TITLE
University research says "Too low building level" despite having the building level

### ISSUE THREAD

**Issue by sweg4552** [ldtteam/minecolonies#4998]
### Minecolonies version

minecolonies-0.10.771-RELEASE-universal

University won't let me start research which is locked behind hut levels, despite having those buildings at that level. Gives the "Too low building level" message. To be exact:
-smeltery level 3 to unlock "The Flintstones" (unlock the smeltery)
-blacksmith level 1 to unlock "Stone cake" (unlocks stonemason)

The level 1 guard tower was correctly detected and let me do the "Accuracy" Research
I've added screenshots in case ive missed something obvious
I had the required research resources with me.
I've tried having workers hired and getting them to work, everything else works fine
Only weird thing I've done is enlarged the colony area by 1 chunk with the claim command I believe, in order to put the university where I wanted it, if that's relevant.

### Steps to reproduce the problem

1. Set up colony with university
2. Level up work huts to unlock research
3. Research ui still says hut level is too low
4. ... Loss

![minecraftskilltree](https://user-images.githubusercontent.com/54961025/81968268-74bcc380-961c-11ea-87ad-334b430f41cc.jpg)
![minecolonies](https://user-images.githubusercontent.com/54961025/81967964-07109780-961c-11ea-92d2-64c440d7a928.png)

**Comment by JiaYow** [comment]
Just to rule that out, your University is level 2, is it?

**Comment by sweg4552** [comment]
no its level 1
didn't think each column was restricted by uni level, I assume that's it then
