### ISSUE TITLE
[develop question]

### ISSUE THREAD

**Issue by forReason** [ldtteam/minecolonies#500]
When I Build Beautiful things. is there a way, I can add the schematics? like More versions of huts, improved farmers barn etc?

**Comment by Raycoms** [comment]
Yes you can. But you'd have it to the jar

2017-01-22 12:45 GMT-02:00 Julian B. <notifications@github.com>:

**Comment by Raycoms** [comment]
you can create your own stylepack and upload it to the jar or send it to us so that we can add it to the mod =D
