### ISSUE TITLE
https://wiki.minecolonies.com/ is down

### ISSUE THREAD

**Issue by TheJokingHydra** [ldtteam/minecolonies#5000]
The minecolonies wiki (https://wiki.minecolonies.com/) can not be reached.
<img width="960" alt="12Capture" src="https://user-images.githubusercontent.com/65374400/81995490-9bbbd980-969e-11ea-9fa8-8307cd8bf904.PNG">

**Comment by ravenbuilder934** [comment]
Can you move this to the Minecolonies Wiki repository? https://github.com/ldtteam/MinecoloniesWiki/issues

**Comment by SeeTwoDev** [comment]
it's simply that the URL changed. https://ldtteam.github.io/MinecoloniesWiki/
