### ISSUE TITLE
Unable to Build Fortress L3 farmer as it requires composted dirt but research to build composter requires a L3 farmer

### ISSUE THREAD

**Issue by svnrex2019** [ldtteam/minecolonies#5002]
### Minecolonies version # Update to the newest minecolonies and structurize alpha first and see if your issue might be already fixed!

Version:  minecolonies-1.15.2-0.11.946

### Expected behavior

- Being able to research the composter with our requiring composted dirt 

### Actual behaviour

- Using the Fortress schematics the level 3 farmer requires composted dirt to be built, the composter requires a level 3 farmer in order to be researched at the university 

### Steps to reproduce the problem

1.  Build L2 farmer
2. Upgrade to Level 3 farmer requires composted dirt
3. University research to get the composter requires the L3 farmer to have already been built
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

**Comment by Raycoms** [comment]
#4536 please
