### ISSUE TITLE
Barrack Tower issues

### ISSUE THREAD

**Issue by lunadragnstar** [ldtteam/minecolonies#5004]
We are still getting several complaints that the barracks towers aren't being placed right. This is not a schematics issue. I've spent days testing all the barracks and they are working fine for me.

Not sure if this is related to the issues Asher was working on with the rotation or something else.

**Comment by lunadragnstar** [comment]
https://github.com/ldtteam/minecolonies/issues/4536#issuecomment-621554357

**Comment by lunadragnstar** [comment]
https://github.com/ldtteam/minecolonies/issues/4536#issuecomment-628037035

**Comment by Raycoms** [comment]
Anyone on the latest with this problem?

**Comment by wolfsilver00** [comment]
> Anyone on the latest with this problem?

Yup, latest, just made Dark Oak Barracks, towers are badly oriented (also, they have a "lip" of leaves that makes it so that, even if properly rotated, it would not match and would leave open ground)

**Comment by Raycoms** [comment]
Fixed in newest as observed by author
