### ISSUE TITLE
Nordic hospital misplace

### ISSUE THREAD

**Issue by lebanni** [ldtteam/minecolonies#5007]
minecolonies-1.15.2-0.11.946-universal.jar

The preview and the placed nordic hospital don't match.

![2020-05-15_19 23 13](https://user-images.githubusercontent.com/2799575/82089019-16164900-96f3-11ea-8559-4a74aa97d77f.png)

![2020-05-15_19 23 26](https://user-images.githubusercontent.com/2799575/82089053-25959200-96f3-11ea-8319-2a4e4827bbe4.png)

**Comment by Raycoms** [comment]
@lunadragnstar I believe it's probably missing the block.

**Comment by lunadragnstar** [comment]
I'll double check it

**Comment by lunadragnstar** [comment]
level 5 hospital block was rotated wrong, fixed
