### ISSUE TITLE
Supply camp placement is trying to place on half slab/less then half slabs. 

### ISSUE THREAD

**Issue by ZephyrWindSpirit** [ldtteam/minecolonies#5009]
Version: minecolonies-1.15.2-0.11.948-universal, structurize-0.10.315-ALPHA 

### Expected behavior
Place supply camp on a completely flat area of dirt.

### Actual behaviour
Building render shows the camp on a half slab view. 

![2020-05-15_15 30 58](https://user-images.githubusercontent.com/16616656/82101795-5a3d2580-96c2-11ea-9198-e3c60eca80b8.png)
![2020-05-15_15 31 03](https://user-images.githubusercontent.com/16616656/82101796-5b6e5280-96c2-11ea-9284-e4307a278525.png)

### Steps to reproduce the problem

1. Click on the ground to place supply camp
2. adjust to place in proper area
3. click the green checkmark
4. Error on placement. 

### Logs: 

[m[1;31m[15:31:03] [Render thread/ERROR] [minecraft/MainWindow]: ########## GL ERROR ##########
[m[1;31m[15:31:03] [Render thread/ERROR] [minecraft/MainWindow]: @ Render
[m[1;31m[15:31:03] [Render thread/ERROR] [minecraft/MainWindow]: 65539: Invalid key -1
[m[33m[15:33:00] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Is the server overloaded? Running 2027ms or 40 ticks behind
[m[32m[15:33:12] [Render thread/INFO] [minecraft/NewChatGui]: [CHAT] Placing a supply camp requires flat solid ground. These blocks must be solid: (-828 65 -203), (-827 65 -203), (-826 65 -203), (-825 65 -203), (-824 65 -203)....

**Comment by ZephyrWindSpirit** [comment]
I've checked most buildings that I can access without placing a colony. All the renders are about half a block higher or lower then should be.

**Comment by Raycoms** [comment]
Ae you using optifine or similar?

**Comment by ZephyrWindSpirit** [comment]
No sir. Here's a list of mods I'm using. 
Forge 31.1.87
Abnormals-Core-1.15.2-v1.0.4.jar
AdLods-1.15.2-3.0.3.0-build.0035.jar
AdPoles-1.15.2-4.0.1.0-build.0009.jar
AI-Improvements-1.15.2-0.3.0.jar
AkashicTome-1.3-13.jar
AmbientEnvironment-3.0.0.jar
AmbientSounds_v3.0.19_mc1.15.2.jar
angelring-1.15.2-1.2.0.jar
Apotheosis-1.15.2-3.1.1.jar
AppleSkin-mc1.15.2-forge-1.0.13.jar
Aquaculture-1.15.2-2.0.13.jar
archers_paradox-1.15.2-0.4.0b.jar
Atmospheric-1.15.2-v1.3.0.jar
AttributeFix-1.15.2-7.0.2.jar
AutoRegLib-1.5-40.jar
backpacked-1.4.1-1.15.2.jar
Bamboo-Blocks-1.15.2-v1.4.0.jar
bamboo2-1.15.2_0.1.jar
bambooeverything-1.15-1.0.0.jar
BasicNetherOres-1.15.2-4.0.1.jar
berry_good-2.0.0.jar
BetterAdvancements-1.15.2-0.1.0.96.jar
betterbedrockgenerator-1.15.2-0.0.6.jar
BetterBurning-1.15.2-1.3.4.jar
bettertridentreturn-1.15.2-1.0.1.jar
betterwithminecolonies-1.15.2-1.15.16.jar
BiomesOPlenty-1.15.2-10.0.0.360-universal.jar
Bloomful-1.15.2-v1.4.0.jar
bluepower-1.15.2-0.4.188-alpha-universal.jar
BonsaiTrees-2.1.2.6.jar
Bookshelf-1.15.2-5.5.36.jar
Botania-r1.15-384.jar
BotanyPots-1.15.2-2.0.18.jar
Bountiful-1.15.2-3.1.1.jar
buildinggadgets-3.3.5.jar
Buzzier-Bees-1.15.2-v1.5.0.jar
caelus-FORGE-1.15.2-2.0-beta2.jar
camera-1.6.6.jar.disabled
campfiretorches-1.15.2-1.0.2.jar
CapabilityProxy-1.15.2-2.1.5.jar
carpetstairsmod-1.15.2_v1.4.4.jar
carrotslib-mc1.15.2-2.5.jar
CauldronRecipes-1.15.2-1.1.4.jar
cherishedworlds-FORGE-1.15.2-3.0.jar
citadel-1.1.5-1.15.2.jar
ClickMachine-1.15.2-3.0.2.jar
Clumps-5.0.2.jar
CobbleForDays-1.1.3.jar
cofh_core-1.15.2-0.4.0b.jar
colytra-FORGE-1.15.2-3.0.jar
comforts-FORGE-1.15.2-2.0.0.2.jar
CommonCapabilities-1.15.2-2.4.4.jar
conduitsprdr_1.15.2-1.0.jar
config-2-3.0.jar
Controlling-6.1.4.jar
CookingForBlockheads_1.15.2-8.0.1.jar
corail_woodcutter-1.1.3-1.15.2.jar
CosmeticArmorReworked-1.15.2-v3a.jar
craftingstation-3.1.0.jar
CraftingTweaks_1.15.1-11.0.0.jar
CraftTweaker-1.15.2-6.0.0.27.jar
Cucumber-1.15.2-3.0.5.jar
curioofundying-FORGE-1.15.2-3.0.jar
curios-FORGE-1.15.2-2.0.2.2.jar
curiouselytra-FORGE-1.15.2-2.0.jar
curiousshulkerboxes-FORGE-1.15.2-2.0.0.1.jar
cyclepaintings_1.15-1.2.jar
Cyclic-1.15.2-0.4.1.jar
CyclopsCore-1.15.2-1.6.2.jar
damage_indicator-0.1.0.jar
DangerousStoneCutter-1.15.1-1.2.0.jar
dankstorage-2.6.jar
DarkPaintings-1.15.2-1.0.4.jar
DarkUtilities-1.15.2-3.0.6.jar
decorative_blocks-6d.jar
DefaultOptions_1.15.2-11.0.1.jar
DefaultSettings-1.15.2-2.1.9.jar
despeggshatch_1.15-1.2.jar
dimdungeons-1.051-forge-1.15.2.jar
Ding-1.15.2-1.1.0.jar
DoubleSlabs-1.15-2.3.0.jar
DungeonCrawl-1.15.2-1.6.3.jar
dwmh-1.15.2-4.0.0.jar
easyelytrato_1.15-1.2.jar
Elementary Staffs 1.7.2.jar.disabled
elevatorid-1.15.2-1.7.0.jar
embellishcraft-1.15.2-2.2.0.0.jar
EnchantmentDescriptions-1.15.2-2.0.8.jar
EnderBags-1.15.1-5.0.0.jar
EnderMail-1.15.2-1.1.0.jar.disabled
engineersdecor-1.15.2-1.0.20-b7.jar
enigmatica-0.3.1.jar
ensorcellation-1.15.2-0.4.1b.jar
environmentalcreepers-forge-1.15.2-1.6.1.jar
EquipmentTooltips-1.15.2-1.4.0+11.jar
EverlastingAbilities-1.15.2-1.6.1.jar
extlights-2.0.jar
extradisks-1.15.1-1.2.jar
extratags-1.1.jar
extremeSoundMuffler-1.2.2_forge-1.15.2.jar
FarmingForBlockheads_1.15.2-6.1.2.jar
FastFurnace-1.15.1-3.0.0.jar
FastLeafDecay-v22.jar
FastWorkbench-1.15.1-3.0.0.jar
findme-1.15.2-1.3.0.jar
fishingreal-1.2.jar.disabled
forbidden_arcanus-1.15.2-1.3.1.jar
ForgeEndertech-1.15.2-6.0.3.0-build.0036.jar
FpsReducer-mc1.15.2-1.15.jar
ftb-backups-2.1.0.1.jar
ftb-chunks-1.0.1.7.jar
ftb-gui-library-1.0.0.14.jar
ftb-ranks-1.0.0.2.jar.disabled
ftb-teams-1.0.0.5.jar.disabled
furniture-7.0.0-pre16-1.15.1.jar
fxcontrol-1.15-1.0.2.jar
GameStages-1.15.2-5.0.2.jar.disabled
gardentools-1.15.2-1.0.0.jar
give-1.15.2-1.1.0.jar
glassential-forge-1.15.2-1.1.2.jar
globalxp-1.15.2-v1.4.11.jar
goblintraders-1.2.0-1.15.2.jar
goprone-1.15.x-1.3.0.jar
Hwyla-forge-1.10.8-B72_1.15.2.jar
incontrol-1.15-4.0.3.jar
industrial-foregoing-1.15.2-2.3.0-6f57752.jar
Interactio-1.15.2-2.0.2.jar
inventorysorter-1.15.2-17.0.0.jar
invtweaks-1.15.2-2.0.3.jar
ironchest-1.15.2-10.0.3.jar
IronJetpacks-1.15.2-3.0.1.jar
item-filters-2.2.0.14.jar
JAOPCA-1.15.2-3.2.0.9.jar
jei-1.15.2-6.0.0.4.jar
JEITweaker-1.0.1.jar
journeymap-1.15.2-5.7.0b2.jar
justenoughbeacons-2.0.jar
JustEnoughResources-1.15.2-0.10.1.77.jar
Kiwi-1.15.2-2.7.1.jar
KleeSlabs_1.15.2-8.0.0.jar
Kottle-1.5.2.jar
kubejs-2.6.1.34.jar
LetSleepingDogsLie-1.15.2-1.1.0.jar
libnonymous-1.15.2-1.1.1.5.jar
LightOverlay-4.6.1.jar
Lollipop-1.15.2-1.0.15.jar
Ma-Enchants-1.15.2-3.1.0.jar
Ma-Essentials-1.15.2-3.0.3.jar
managear-1.1.1.jar
Mantle-1.15.2-1.5.15.jar
mapperbase-1.15.2-1.1.0.0.jar
mcjtylib-1.15-4.1.0-beta.jar
mcw-bridges-1.0.4fix-mc1.15.2.jar
mcw-furniture-1.0.1-mc1.15.1 1.15.2.jar
mcw-roofs-1.0.2-mc1.15.2_1.15.1.jar
mcw-windows-1.0.1-mc1.15.2_1.15.1.jar
Mekanism-1.15.2-9.10.5.418.jar
MekanismGenerators-1.15.2-9.10.5.418.jar
MekanismTools-1.15.2-9.10.5.418.jar
mgui-1.15.2-2.1.1.jar
minecolonies-1.15.2-0.11.948-universal.jar
mininggadgets-1.3.5.jar
MixinBootstrap-1.0.3.jar
modular-routers-1.15.2-6.1.0-17.jar
moredragoneggs-1.0.jar
morevanillalib-1.15.2-1.2.4.jar
Morpheus-1.15.2-4.2.50.jar.disabled
MouseTweaks-2.13-mc1.15.1.jar
multibeds-1.15-1.6.0.jar
MysticalAgradditions-1.15.2-3.0.0.jar
MysticalAgriculture-1.15.2-3.0.4.jar
mysticallib-1.15.2-2.0.0.jar
NaturesAura-27.0.jar
NaturesCompass-1.15.2-1.8.5.jar
Neat 1.6-22.jar
NetherPortalFix_1.15.2-6.0.2.jar.disabled
netherpspr_1.15-3.0.jar
no-nitwits-1.15.2-1.0.0.jar
occultism-0.2.8.jar
OpenLoader-1.15.2-4.0.5.jar
OreExcavation-1.7.151.jar
oreveins-forge-1.15.2-5.1.1.jar
PackingTape-1.15.2-0.9.6.jar
PackMenu-1.15.2-1.2.4.jar
pamhc2foodcore-1.15.2-1.0.3.jar
PassableFoliage-1.15.2-1.1.0.jar
PassthroughSigns-1.15.2-2.3.3.jar
Patchouli-1.15.2-1.2-33.jar
phosphor-forge-mc1.15.2-0.5.2+build.4.jar
pitg-1.15.2-1.3.0.jar
Placebo-1.15.2-3.0.2.jar
playerplates-1.15-forge-1.0.0.jar
pneumaticcraft-repressurized-1.15.2-1.1.2-14.jar
portality-1.15.2-2.1.2-aaa257f.jar
Powah-1.15.2-1.1.14.jar
PrettyBeaches_1.15.1-4.0.0.jar
projectvibrantjourneys-1.15.2-2.0.1.jar
Psi r1.2-79.jar
Quark-r2.1-237.jar
QuarkOddities-1.15.2.jar
QuickLeafDecay-MC1.15.2-1.2.5.jar
quickstack-3.0.3c.jar
rad-1.15-3.0.1.jar
randompatches-1.15.2-1.21.1.2.jar
rats-5.2.2-1.15.2.jar
reap-1.12.3.jar
ReAuth-1.14-1.15-3.8.1.jar
refinedpipes-0.4.1.jar
refinedstorage-1.8.3.jar
refinedstorageaddons-0.6.1.jar
repurposedstructures-1.15.2-1.4.1.jar
respawnablepets-1.1.jar
rftoolsbase-1.15-1.1.1-beta.jar
rftoolsbuilder-1.15-2.1.1-beta.jar
rftoolspower-1.15-2.1.1-beta.jar
rftoolsstorage-1.15-1.1.2-beta.jar
rftoolsutility-1.15-2.1.2-beta.jar
RingOfAttraction-1.15.2-1.1.31.jar
rsgauges-1.15.2-1.2.3-b3.jar
SaveMyStronghold-1.15.2-1.0.0.jar
SBM-BoneTorch-1.15.2-0.0.1.jar
scaffoldingpower-1.15.2-1.2.1.jar
ServerTabInfo-1.15.2-1.2.6.jar.disabled
shetiphiancore-1.15-3.7.1.jar
SilentGear-1.15.2-1.6.4+90.jar
SilentGems-1.15.2-3.5.3+86.jar
SilentLib-1.15.2-4.6.1+49.jar
SilentMechanisms-1.15.2-0.7.1+51.jar
SimpleDiscordRichPresence-1.15.2-1.2.6.jar.disabled
simplefarming-1.15.2-1.2.7.jar
simply_trophies-2.0-1.15.2.jar
simplybackpacks-1.15.2-1.4.5.jar
simplylight-1.15.2-0.9.0.jar
SlimeTweaks-1.15.2-1.0.2.jar
smallernp_1.15-1.2.jar
Smoke-1.15.2-2.0.0.jar
SnowRealMagic-1.15.2-1.8.0.jar
softerhayb_1.15.2-1.0.jar
solcarrot-1.15.2-1.9.4.jar
StepUp-1.15.2-0.2.1.jar
stonecatalysts-1.15.2-1.2.0.jar
StorageDrawers-1.15.2-7.0.2.jar
StrongerSnowballs-1.15.2-1.0.1.jar
structurize-0.10.315-ALPHA.jar
Swamp-Expansion-1.15.2-v1.7.1.jar
swingthroughgrass-1.15.2-1.4.0.jar
TerraForged-1.15.2-0.0.14.jar
tetra-1.15.2-2.5.0.jar
themidnight-0.5.7-3.jar
theoneprobe-1.15-2.0.2.jar
titanium-1.15.2-2.4.0.jar
TMechworks-1.15.2-2.1.0.jar
ToastControl-1.15.2-3.0.1.jar
tombstone-4.3.7-1.15.2.jar
ToolBelt-1.15.2-1.14.1.jar
TOOLKIT-1.15.2-1.6.4.jar
torchmaster-2.1.1-rc0.jar
tramplestopper-1.15.2-2.0.0.1-universal.jar
Transport-1.15.2-2.2.0.jar
TrashSlot_1.15.2-11.0.0.jar
ultra_amplified_dimension-1.15.2-7.4.2.jar.disabled
Upgrade-Aquatic-1.15.2-v1.6.0.jar
upsizer-mc1.15.2-5.1.jar
valhelsia_structures-15.0.2a.jar
vanillaexcavators-1.15.2-2.1.jar
vanillafoodpantry-mc1.15.2-5.5.jar
vanillahammers-1.15.2-2.1.jar
vanillathings-1.15.2-0.5.7.jar
venture-1.0.0-1.15.2.jar
villagernames
vilnames_1.15-2.0.jar
vmt-1.15.2-1.0.jar
WaterStrainer-1.15.2-9.0.0.jar
Waystones_1.15.2-6.0.1.jar
whoops-1.15.2-0.0.1.2.jar
WitherSkeletonTweaks-1.15.1-4.0.0.jar
World-Stripper-1.7.2-1.15.1.jar.disabled
XL-Food-Mod-1.15.2-2.2.2.jar
xnet-1.15-2.1.2-beta.jar

**Comment by Raycoms** [comment]
@Nightenom any idea which one could be causing this?

**Comment by Nightenom** [comment]
This was only happening for paintings. So I would blame it on mods.
Some of my guesses:
randompatches-1.15.2-1.21.1.2
quark (less possible since many players are using it along minecolonies)
camera-1.6.6
basically any mod altering rendering (from camera settings to world rendering)
If it can be reproduced in pure vanilla, please, note that

**Comment by Raycoms** [comment]
Since we use randompatches and quark on our server and its not a problem I'd say its the camera mod. Probably sets the view position off by 0.5 which causes this problem

**Comment by ZephyrWindSpirit** [comment]
Hm, camera is disabled, maybe I need to remove it fully. Vanilla minecolonies places just fine. I'm adding quark and quark oddities now to try it out.
Hm. adding quark and quark oddities doesn't change it. Lets try random patches alone. Nope, its fine... lets try camera. 
So playing with those mods alone in a vanilla world does not alter the placement of the supply chest. 

The pack I posted is a heavily spliced version of enigmatica 5 and cids modded life 3 with extra mods. Enigmatica is known for config changes.

**Comment by Raycoms** [comment]
It's because our rendering uses what we're supposed to use to calculate the camera positions for rendering. If a mod changes that and our rendering then broke, it is most likely the mods faulty for messing with those values only half done.

**Comment by ZephyrWindSpirit** [comment]
I've confirmed in the enigmatica discord I'm not the only one with the problem, so we'll try to find the cause and report back.

**Comment by Raycoms** [comment]
Awesome, ty

**Comment by ZephyrWindSpirit** [comment]
It's a bit of a long shot, but we believe the issue is being caused by Neat. Neat seemed to be causing rendering problems with building gadgets, mining gadgets, and minecolonies for the ghost block rendering on placement. Disabling neat seems to have solved it for now. Their github mentions leaking states or something I don't understand properly, so keeping an eye on that is recommended. @Raycoms

**Comment by ZephyrWindSpirit** [comment]
I had the same issue pop up last night with neat removed, but removing PSI fixed it, oddly enough.
