### ISSUE TITLE
Deliveryman level 3 house needs stone brick monster eggs?

### ISSUE THREAD

**Issue by Icebelly** [ldtteam/minecolonies#501]
### Minecolonies version

minecolonies-universal-1.10.2-0.6.2404

### Expected behavior

- Level 3 deliveryman probably needs regular stone and not stone monster egg blocks?

### Actual behaviour

- Builder specifically asks for stone monster egg blocks while upgrading the house.

### Steps to reproduce the problem

1.  Make a deliveryman house
2. Upgrade to level 3

**Comment by Raycoms** [comment]
yeah before we make a release we will fix that =D
Eta 1 day =D

2017-01-22 23:18 GMT-02:00 Chandler Woodruff <notifications@github.com>:

**Comment by pmardle** [comment]
GRRRRRRR DAMN STONE EGGS - BANE OF MY LIFE :D
