### ISSUE TITLE
1.15.2 Minecolonies crash while placing building

### ISSUE THREAD

**Issue by Grimlorc** [ldtteam/minecolonies#5010]
Version: 1.15.2 forge 31.1.77
Minecolonies version: minecolonies-0.10.771-RELEASE-universal
Structurize version: structurize-0.10.313-RELEASE
- Just download the mod yesterday and want to try it on creative
  Crash when using the ship or the building scepter after click on tick button

- latest.log: https://gist.github.com/Grimlorc/6ddfb3b86cee40f2dc8c4f9b250bbda0
- crashlog: https://gist.github.com/Grimlorc/1ccab8b0d9d231511500d1cb43d06bcc

**Comment by Raycoms** [comment]
You need to download the newest mod version (alpha) and the newest structurize version (alpha)
