### ISSUE TITLE
Can't build mechanic

### ISSUE THREAD

**Issue by Kao713** [ldtteam/minecolonies#5012]
Version: minecolonies-1.15.2-0.11.948-universal

### Expected behavior

Research mechanic, then build it

### Actual behaviour

After research the mechanic, when try to build it still saying "Build and university and research first"

### Steps to reproduce the problem

1. Research mechanic
2. Place and try to build it

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

**Comment by Ampaex** [comment]
Fixed issue.
