### ISSUE TITLE
[Suggestion] Option for showing the building limit

### ISSUE THREAD

**Issue by Ampaex** [ldtteam/minecolonies#5013]
When I try to place a new building near another I always try to figure out which is the limit of the actual building. 
Actually I do so by using the option repair building but this involve the builder.
I'd like to see an **option for seeing the building border**, just like when it is in process of building.
An approach to this may be placing the same construction tape as when the building is in process of being builded but **with a blue tape** instead of white.

This option gives the player the option of overlapping buildings if he wants but now being conscious of the limits and capable of showing them.

**Comment by MatthiasMann** [comment]
If would be nice to show the outline of existing buildings in a different color when placing a new building. Currently I mark the outline of every building on the ground to avoid overlapping buildings.

**Comment by Wissi** [comment]
The concept has been brought up many times and it is a very necessary idea that should be implemented soon. 
The simplest solutions might be a simple code of adding a button to exisiting builds to "show" area by placing the construction tape (whether a diff colored one or same exisitng one) for that existing build, then turn it off again.

Maybe SomeAddons might look into it soon.         
-fingers crossed  xD

**Comment by Raycoms** [comment]
You can just click repair to display this tape though

**Comment by Wissi** [comment]
But the problem with that is that doing that will generate a build order and will not be removed until it's cancelled or builder is done, etc. Which is a lot of trouble and running around, etc?

But as you say there is a button function already that will create this, just a matter of adding another button with just the code for "displaying" the construction tape (like on repair or new build) and then on pressing again it will "remove it" (as when the builder is finished anyways?).

See simple !    xD

**Comment by sweg4552** [comment]
Its funny because this exact feature was available back in the day
In the intro of [this video](https://www.youtube.com/watch?v=rjchqo6aKMk)

**Comment by Raycoms** [comment]
#4535 please
