### ISSUE TITLE
Citizens maxed at 25, won't go beyond

### ISSUE THREAD

**Issue by mcfindlay** [ldtteam/minecolonies#5014]
Version: minecolonies-1.15.2-0.11.948-universal.jar (Although this has been going on for over a month.

### Expected behavior
Max Colony Size won't pass 25/25. One save/world made it to 28/25 though.

I've got the config set:
	#Max citizens in one colony. [Default: 50]
	#Range: 4 ~ 500
	maxcitizenpercolony = 75
	#minecolonies.config.maxcolonysize.comment
	#Range: 1 ~ 50
	maxColonySize = 50

### Actual behaviour

No increases, I've added a lot of citizen huts, spread across the town in a similar radius, but I never seem to get new citizens. I've probably got double the beds than citizens, but that worked till 25. I have extra jobs, school, happiness varies from 9.8-10.

### Steps to reproduce the problem

Try to create a city with more than 25 people with more jobs and citizen hut beds available than citizens.
I've deleted my config everytime I've upgraded minecolonies in case that fixes it but still can't get past 25.

### Logs: Latest.log and crashlog at https://gist.github.com/

No crashing etc, everything looks fine... Just not sure why on multiple saves I'm constantly capped at 25 citizens.

**Comment by Raycoms** [comment]
You have to research it at the university
