### ISSUE TITLE
[Suggestion] Allies and guard caravans

### ISSUE THREAD

**Issue by Ampaex** [ldtteam/minecolonies#5015]
First of all introduce the **concept of allies**, other colonies which are friendly to you (and now allies) will have certain privileges with your colony and a first approach for this privileges could be the ability of receiving military support from allies.

For counterpart also add enemy colonies which attack you or your units if they see you or any of your citizen/guards.

In both townhall you will be able to **enable or disable the military support** and if both allies have it enabled both could receive military support in case of raid or enemy attack (maybe with a distance limit).
This is susceptible to be changed depending on buildings tier.

This can be cool if the **guards march from one colony to another in a caravan** (loading the needed chunks) and removing the distance limit because the distance limit would be if the guards arrive on time.

In addition to this, if the player has a certain tier of barracks and researched at the university this feature, the player should be able to ask for military aid at any moment.

This could open new horizons to new buildings such as **embassies** or **citizen diplomats** which notices the mayor(player) of events.

Maybe a caravan with a horse like this with food and weapons followed by guards:
[Caravan](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fstatic.planetminecraft.com%2Ffiles%2Fresource_media%2Fscreenshot%2F1331%2F2013-08-01_160205_6077209.jpg&f=1&nofb=1)
(The caravan should have real moving wheels)
The same concept could be used for automatic trading between colonies.

**Comment by Raycoms** [comment]
Yeah, the entire concept of PvP will be essentially reworked.

I'll close this here because I already got a pretty nice idea on how it will work in the future. However, you can be sure that we got some nice plans in place for this.

The first step will definitely be more related to alliances including traders/guards etc.
And the next step then more related to actually colonies fighting with eachother

**Comment by Ampaex** [comment]
@Raycoms
Alright, thank you. I'm impatient for seeing players and colonies interactuating.

I will try to help as much as possible.
