### ISSUE TITLE
Crash on building placement in ATM5

### ISSUE THREAD

**Issue by CptKjrk** [ldtteam/minecolonies#5018]
Minecolonies Version-1.15.2-0.11.948-universal / 0.10.771-RELEASE-universal
Structurize Version-0.10.315-ALPHA / 0.10.313-RELEASE

When I accept the placement of the building the game crashes. On a server the same thing happens to me, but not to a friend who is hosting the server when they build a townhall. I've tried with multiple buildings, mostly townhalls with a crash everytime, however placing a supply ship worked as intended.

Crash Logs and Latest
https://gist.github.com/CptKjrk/2783683d60b92a7a72b1a5c577d43269

**Comment by Raycoms** [comment]
Please report to:

 at com.thevortex.potionsmaster.events.PotionRemoved.on(PotionRemoved.java:21) ~[?:0.1.4] {re:classloading}

Their mod interfering with our citizens and crashing them.
