### ISSUE TITLE
Windyhill upgrade. 

### ISSUE THREAD

**Issue by Sh4dowAxe** [ldtteam/minecolonies#5019]
Hello, I am trying to upgrade my playerhousing windyhill1 to a windyhill2 but there is no upgrade button anywhere.

Mod version minecolonies-0.11.945-ALPHA-universal

**Comment by ravenbuilder934** [comment]
This is a duplicate issue, please close it (since you already commented in #5006)

**Comment by Sh4dowAxe** [comment]
I am new to this website, sorry just wanted to make sure I got it right :3

**Comment by ravenbuilder934** [comment]
It's fine! I'm kinda new too.
