### ISSUE TITLE
Delivery 5 Warehouse requesting Stone Monster Eggs

### ISSUE THREAD

**Issue by Megistus** [ldtteam/minecolonies#502]
### Minecolonies version

minecolonies-universal-1.10.2-0.6.2423

### Expected behavior

- Builder builds without needing Stone Monster Eggs

### Actual behaviour

- Requests two stone monster eggs 

### Steps to reproduce the problem

1. request upgrade from warehouse and builder starts upgrading

**Comment by pmardle** [comment]
./facepalm

Will fix today. pretty sure these snuck into to the doorstep :P - pesky monsters !!

**Comment by forReason** [comment]
better take care whilst building .schematics :D
