### ISSUE TITLE
Lumberjack still getting stuck in leaves

### ISSUE THREAD

**Issue by MatthiasMann** [ldtteam/minecolonies#5024]
Version: minecolonies-1.15.2-0.11.948-universal

### Expected behavior
Lumberjack should remove leaves if they block the way.

### Actual behaviour
If the path requires going up one block, but leaves prevent jumping the lumberjack get stuck (continuously tries to jump).

![2020-05-17_17 24 08](https://user-images.githubusercontent.com/6777029/82152722-90fe7180-9863-11ea-9427-31a02d06770f.png)
(Not as clearly visible as I hoped: there is a leave block directly above the head, but no leaves in front/walking direction - after removing the leave block above the head he continued his path to the next tree).

And if a tree grows around the lumberjack (so that the head in the leaves) he/she stops moving complete.

### Steps to reproduce the problem
1. Create a tree farm on a hill side
2. Plant trees and put a lumberjack nearby
3. Wait until he gets stuck
4. ... Profit (not really - we run out of wood)

**Comment by Ampaex** [comment]
Bug confirmed.
It seems that the lumberjack does not check if there is a block on top of him before jumping.

**Comment by Raycoms** [comment]
duplicate issue
