### ISSUE TITLE
[Suggestion] Translatable citizen names

### ISSUE THREAD

**Issue by Ampaex** [ldtteam/minecolonies#5025]
### Actual behaviour
Citizen's names are independent of the language. They are always the same.

### Suggested behavior
Although it may seem not important, this is a crucial step in the gameplay. It gives the player a more personal approach to the citizens and also helps remembering the names of each citizen.

But there is more, giving the translators the possiblity of adding names, the citizens will have more different names to offer the player, he will not see the same names as often even if he replay the mod several times.

The feeling of the mod will be greatly increased. 
Even the bugs are funnier when the lumberjack which is stuck in a wooden log have the name of your friend.

**Comment by Wissi** [comment]
Anyone can change/add/remove any name (or list of names) they want in the config file, heck you can leave just one name: John Smith and everyone will be called John Smith.

So any player, translator or server owner can "customize' the names they want to show up for male and female. The config file is the `minecolonies-server.toml` located in the `./minecraft/world/serverconfig` folder.

Players can even rename individual citizens/workers with a name tag (unless that got removed recently)

**Comment by Ampaex** [comment]
Thanks to @Wissi we can close this issue. I think we must add this to the wiki (if it is not added yet) and also add a link to official templates. (I can do the spanish one)

**Comment by lunadragnstar** [comment]
Added to the Wiki to do list
