### ISSUE TITLE
Max 1 level 6 per branch not shown before

### ISSUE THREAD

**Issue by DiabolosMan** [ldtteam/minecolonies#5027]
### Minecolonies version 
Version minecolonies-1.15.2-0.11.948-universal.jar
Forge version 31.2.0

### Expected behavior
Be notified that a research level 6 will disable ALL researches lvl 6, before starting it
Have all level 6 column grayed (disabled)
Have no message "Missing resource" but "Max 1 lvl 6 per branch (or nothing)
    or the ability to remove a lvl 6 research to start this instead

### Actual behaviour
- Per branch is for Civilian, Techno and Attack ? Correct ? Or is it by sub branch ? It would be better by sub branch instead because it means only 3 lvl6 lvl for all researches which is not a lot. Is it by design, is it wanted ?
- Missing resource is written. When all resources met, message change "Max 1 lvl 6 per branch"
- No way to know before that it will be the case. I would not have done some choices
- No information about lvl6 blocking
- Would it be possible to cancel a research lvl 6. I would prefer to remove one of my previous lvl6 research (I will loose my materials but I prefer having another research instead) by having a button to search and remove other lvl 6

![2020-05-18_08 22 46](https://user-images.githubusercontent.com/63854770/82192593-7c1dee80-98f4-11ea-8e53-fdc4a263c895.png)
![2020-05-18_08 23 09](https://user-images.githubusercontent.com/63854770/82192596-7d4f1b80-98f4-11ea-9f8c-786bbfdf4f19.png)

**Comment by Raycoms** [comment]
It is on purpose to be only 1 per branch (total of 3). Since those are "very powerful" researches that need a long time.

I got on my list already to add a button to undo a research.

**Comment by Ampaex** [comment]
So:
* Display correctly the unreachable researchs in gray
* Option for cancel a research(Splash window "Do you really want to forget this research?"[yes/no])
* Warning in case of researching 6th level research (Splash window "You only can research one at 6th lvl. Are you sure?"[yes/no].)

I'll do it

**Comment by Raycoms** [comment]
- [ ] After having ressarched an option to "undo it" would also need a "Do you really want to forget this research?"

**Comment by Ampaex** [comment]
Alright, I'm gonna edit

**Comment by DiabolosMan** [comment]
Thanks ! Sounds perfect !

**Comment by Ampaex** [comment]
@Raycoms Don't close this issue, is not complete yet. I have to do the warning window, I'm just awaiting to have a little bit of free time.
