### ISSUE TITLE
Guards housing should count as classical citizen hut housing

### ISSUE THREAD

**Issue by DiabolosMan** [ldtteam/minecolonies#5028]
### Minecolonies version
Version minecolonies-1.15.2-0.11.948-universal.jar
Forge version 31.2.0

### Expected behavior
Guards housing should count as classical citizen hut housing

### Actual behaviour
- If you look at the first screen shot, you will see that I have 52/52 citizen and 21/21 knights, and no unemployed or child.
- 3 of my guards died
- If you look at screen shot 2, I have 49/49 citizen and 18/21 knights, and still no unemployed or child
- It will stay like that for ever… If I let all automatic, I will loose day after days all my guards without any new children… And finally reach 31/31 citizen, 0/21 knights. If I build more citizen hut, for my case I need 4 citizen hut lvl5 + 1 citizen hut lvl 1, I will have new children…. But after that I will have 21 unemployed citizen.

- In order to have again X more guards, I have to fire X workers and hire them manually X as guard, then reput everything automatic in order to have new child in the colony.

- The simplest thing to do is stop this complicated housing count for guard and only count guards bed like citizen bed. Simpler algorithm that will solve that issue.

![before](https://user-images.githubusercontent.com/63854770/82193789-2f3b1780-98f6-11ea-88a4-9d3880f358d7.png)
![after](https://user-images.githubusercontent.com/63854770/82193802-33ffcb80-98f6-11ea-82ee-4ddcb99da63a.png)

**Comment by Raycoms** [comment]
This is done on purpose because else it causes a lot of problems. (Normal citizens living in guard towers although not being guards for example)

**Comment by DiabolosMan** [comment]
I don't agree. Normal citizen cannot leave in guard tower. If the system assign guard automatically, its bed would be the guard tower. I do not see how a normal citizen could be assigned in guard bed.

However, please do not close it.

If you think you cannot change that system, so I propose the following:

-  let the maximum population to the number of citizen bed + guards bed.
- It will enable to have new child that would be after wards assigned to guard.
- Today, it is VERY complicated to maintain the guards count.

**Comment by someaddons** [comment]
no it is intended this way.

**Comment by Raycoms** [comment]
And that new child, where would it live? It would have to live in a guard tower because that's the only available bed. But that's not the intended behaviour.

It's realistic, consider this:


You have a city, the number of citizens that can live in the city is bound by the number of beds you have. But if you send some of your people off to war, beds will be free for new citizens.

But those are only free when a citizen leaves to go to war and not when there is an open spot for war.

**Comment by DiabolosMan** [comment]
So if I summarize:
-  A guard die… He will NEVER be replaced… At the end all guards would die…. So no more guard in colony.
- What workaround could be done by player to have new guards in the colony ? If you say, build more citizen hut, it does not work because I will have at the end as many unemployed citizen as guards bed

**Comment by Raycoms** [comment]
When in a medieval city all military people died, other normal people had to become guards. No kids were born to become guards, right?

**Comment by DiabolosMan** [comment]
Right for the kids,
According to your last 'image' of war, it means that I have to manually select for ex my farmer that I wanted to make up its stats + my builder, same + my luberjack + my deliverman + my cooker + … ? 

Is there not another easier way to have a "pool" of waiting guards to be assigned automatically to guards ? I have for exemple 5 trainees in combat academy. They are good candidate to be automaticcaly assigned to guard. Would it be possible to have that ? I think it is a good way to match the reality. 
Trainee will be assigned to guards… So they leave empty bed….. So children could come to the city and become later trainee as well…. What do you think about that change ?

**Comment by Raycoms** [comment]
Always have more citizens that you need to fill the normal jobs. You should have spare people assigned in combat academy and archery for those cases.

**Comment by Raycoms** [comment]
+ Library

**Comment by DiabolosMan** [comment]
I have 5 trainee in combat academy…. But it is few days there are not automatically set as guard.
I have also 5 students in library….. Not set as guards also.
Is there somewhere a button to let them go automatically as guard? Would it be possible to add that ability to assign automatically trainee in combat acadamy or archery to guards ?

**Comment by Raycoms** [comment]
atm you'd have to fire them and then deploy them to the guard towers and barracks. In the future we might add things to allow setting them automatically when they reach a certain level.
