### ISSUE TITLE
Suggestion: Have global patrol area for all guards in barrack

### ISSUE THREAD

**Issue by DiabolosMan** [ldtteam/minecolonies#5029]
# Minecolonies version 
Version minecolonies-1.15.2-0.11.948-universal.jar
Forge version 31.2.0

### Suggestion
Today, if I want to define patrols, I need to go for each tower and define patrol area.
It would be nice to be able to do the same globally for the colony and the best place should be in barrack (like for spies)

**Comment by Raycoms** [comment]
#4535 please report here.

**Comment by DiabolosMan** [comment]
In which version is it supposed to be included ? I am using minecolonies-1.15.2-0.11.954-universal.jar and I did not see it.

**Comment by DiabolosMan** [comment]
I still not see this thing in the latest. In which building did you added that change ?

**Comment by Raycoms** [comment]
Not included anywhere. Feature requests should go into #4535
