### ISSUE TITLE
Delivery Man requesting warehouse even though one is built

### ISSUE THREAD

**Issue by Megistus** [ldtteam/minecolonies#503]
### Minecolonies version

minecolonies-universal-1.10.2-0.6.2423

### Expected behavior

- Delivery man actually does his job

### Actual behaviour

- Delivery Man stands in the warehouse complaining he does not have one

### Steps to reproduce the problem

1. Build the warehouse and hire worker
2. Firing and rehiring does not change the behavior

**Comment by Raycoms** [comment]
You build a warehouse level 1 and have a deliveryman level 1?

2017-01-24 9:20 GMT-02:00 Megistus <notifications@github.com>:

**Comment by Megistus** [comment]
Warehouse level 4, deliveryman level 0. Is that the issue? Tho, in all honesty, I am uncertain on how to get the delivery man to start going up in level ... or doing anything for that matter. He just stood there when the warehouse was at level 1

**Comment by Raycoms** [comment]
How many deliverymen do you have? only 1?

2017-01-24 10:42 GMT-02:00 Megistus <notifications@github.com>:

**Comment by Megistus** [comment]
Just the one

**Comment by Raycoms** [comment]
his building level is level 1?

2017-01-24 11:19 GMT-02:00 Megistus <notifications@github.com>:

**Comment by Megistus** [comment]
Level 4 currently.

**Comment by Raycoms** [comment]
Ahhh okay.
There are two buildings you need:
1- deliveryman hut (leather boots in the middle)
2- warehouse (chest in the middle)

2017-01-24 11:53 GMT-02:00 Megistus <notifications@github.com>:

**Comment by Megistus** [comment]
OH! wait! ... there is another building!!!! I completely missed that. doh!
