### ISSUE TITLE
Lumberjack not doing anything after getting a axe. 11.938-BETA

### ISSUE THREAD

**Issue by deadspidervenom** [ldtteam/minecolonies#5031]
Version: minecolonies-0.11.938-BETA-universal

I have been making a colony underground, i made the lumberjack building with a the small dwarven plot so that i could get some wood income.

I gave the lumberjack the axe this asked for, but after they just sit in the hut doing nothing, even though the trees are grown 10 blocks next to them.

A birch tree is shown in the background of this picture as well as the axe. However they just sit there. I also made sure that the trees were checked on page 2.

https://cdn.discordapp.com/attachments/486752085082112024/712025394890407956/unknown.png

**Comment by Raycoms** [comment]
a) Is the axe the right level for the hut level (iron axe might be too good for a level 1 hut)
b) Are the trees one block higher without adjacent blocks?

This should work if the two above conditions are met.

**Comment by deadspidervenom** [comment]
> a) Is the axe the right level for the hut level (iron axe might be too good for a level 1 hut)
> b) Are the trees one block higher without adjacent blocks?
> 
> This should work if the two above conditions are met.

A) yes its a level 2 hut not level 1
b) its your guys tree farm plot for for dwarven style, you can see in the background (though blurry) that there is 1 block of dirt from the tree and the floor.

I legit do not see why you would assume i am a idiot with rocks for brains, i know how to use the mod and how it should be working. and IT WAS NOT and could still be not. So dont close a bug report if it has not been addressed like sweeping dust under the rug.

Conditions were met nothing happened you have a problem.

EDIT: now that i think about it several huts refused to function, including the fishing hut.

**Comment by Raycoms** [comment]
This is modded axe, did you try vanilla?

**Comment by deadspidervenom** [comment]
Yes, on both, though i dont see why modded tools would be the issue sense all other huts accept the same tools just fine.

**Comment by deadspidervenom** [comment]
Also the ai registers it as a valid tool, it just does nothing

**Comment by Raycoms** [comment]
Sometimes modded tools are registered as "higher" as the material. (Since we base it on mining level).

Those trees stand on a single dirt block? When you place slabs around them, does it fix it?

**Comment by deadspidervenom** [comment]
I would test that but i no longer host the world, after a few mods updated the world became unplayable due to everyone getting lag spikes that froze their client for a good minute.

Also the design is in your guys stuff so if it needs slabs then wouldn't the design have slabs?

**Comment by Raycoms** [comment]
Designs are contributed by the community
