### ISSUE TITLE
Miner goes and becomes afk in the middle of the city/town. Not afk in townhall, citizen hut, or Miner hut, and she will go home to sleep, then return to her spot.

### ISSUE THREAD

**Issue by DylanSchneiderman** [ldtteam/minecolonies#5032]
### Minecolonies version # Update to the newest minecolonies and structurize alpha first and see if your issue might be already fixed!

Version: whichever is used in MC Eternal, I'm sorry I can't go more detailed, but I don't know how to check actual version number

### Expected behavior

- I would expect to see the miner going into the mine, and only coming up to get supplies, or sleep.

### Actual behaviour

- Miner goes afk in a random seeming spot above ground. This happened to me when the level she was digging at had a sign saying y level 11, and she had mined out quite a few nodes. Then she started walking from the miner's hut to a spot above ground. I tried firing and rehiring, and she would go to the miner's hut and then back to her spot. When I tried selecting a different level to mine at, and then selecting the deepest level again, she mines a little, and then goes to a different random spot above ground, but somewhat close to the previous random spot. I created a waybpoint beacon using journeymap in the spot where she would go afk, and then wandered the mine she had created, and at the end of one of the tunnels she had mined was the waypoint beacon (aka she would go afk in a spot directly over the end of one of her tunnels). I theorized that maybe it was an issue with pathfinding, and something saw it was quicker to go above the spot and find a way down than it would be to travel down her ladders? That seems unlikely, but I checked with a beacon multiple times, and it always right above the end of one of her tunnels, so that can't be a coincidence. I finally just told her to dig the level above the deepest one, and there have been no problems, although I'm not getting as much ore as I would like (due to higher y level)

### Steps to reproduce the problem

1.  Make a miner
2. Level 3 Miner's hut, level 12 is at y level 122
3. Profit ... for a short time
4. Watch miner go afk above ground in the middle of your city

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: https://gist.github.com/MSixteen16/d6b4189edf3fa5a9480bfc9f29e72639
- crashlog: Didn't crash

#### Unrelated 
Unrelated, but it's really annoying that a sheep farmer that needs wheat in order to breed the sheep will eat the wheat when it has safe alternatives, like a stack of carrots, or even the raw sheep meat that it has gathered.

**Comment by ravenbuilder934** [comment]
The wheat thing should have been fixed in #5011. MC Eternal needs to update Minecolonies.

**Comment by Raycoms** [comment]
Only fixed in 1.15

**Comment by Raycoms** [comment]
For the miner, this means grave is blocking its way in the mines. Go down there and check for that
