### ISSUE TITLE
warehouse repair issue

### ISSUE THREAD

**Issue by bloodyraoul** [ldtteam/minecolonies#5034]
Version: 

minecolonies-1.15.2-0.11.948-universal.jar
forge 31.2.0

I have repaired my level 4 warehouse because the doors were missing due to barbarian raid.
all the resources have disappeared from racks
the building facing have changed
there is a message telling me the warehouse is full....but all the racks are empty
how can i get all my resources back ?

**Comment by PowerSchill** [comment]
When you use the warehouse block and click on the chest icon on the bottom right do you see any contents?

**Comment by Raycoms** [comment]
Closed because of inactivity
