### ISSUE TITLE
Smelter being delivered one fuel/ore at a time

### ISSUE THREAD

**Issue by NilsMoller** [ldtteam/minecolonies#5035]
### Minecolonies version # Update to the newest minecolonies and structurize alpha first and see if your issue might be already fixed!

Version: 0.11.948-ALPHA

### Expected behavior

- Smelter requesting/being delivered a full stack of ores/fuel for his tasks.

### Actual behaviour

- Smelter requests/gets delivered 1 single ore/fuel every time.

### Steps to reproduce the problem

1. Have a warehouse, deliveryman and smeltery set up.
2. Set smelter to use fuel and smelt ores wanted.
3. Put a stack of fuel/ore in the warehouse racks.
4. Smelter requests/gets delivered 1 fuel/ore at a time.
![image](https://user-images.githubusercontent.com/41434155/82331915-080f4380-99e5-11ea-90c2-13340427efa1.png)

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: https://gist.github.com/AydenWasTaken/e3ab884d97b63fb15c2348856169857a

**Comment by Raycoms** [comment]
Have you tried this on the newest too?

**Comment by NilsMoller** [comment]
Doing it right now. Will edit this comment as soon as I have.
EDIT: yes, still happens on 0.11.948. Will update the main post as well.

**Comment by patgoull** [comment]
Same issue with composter here on 948. Dman is bringing in 1 oak sapping at a time while there are plenty in the wharehouse. He is also requesting 64.

**Comment by BrewingCoder** [comment]
Yes, I'm experiencing this systemically across all requests, be it fuel or otherwise.  DM are only delivering one item at a time when a full stack is requested.

**Comment by Tobiti** [comment]
I think the problem is that a delivery man is always only taking the item out of one chest in the warehouse instead of grabbing them from multiple chests. So if only one item is in the chest he will only deliver that

**Comment by NilsMoller** [comment]
> 
> 
> I think the problem is that a delivery man is always only taking the item out of one chest in the warehouse instead of grabbing them from multiple chests. So if only one item is in the chest he will only deliver that

I just tested this (948). I put a stack of ores and a stack of fuel in two different racks and the dman grabbed the full stack of ores but still 1 piece of fuel

**Comment by Raycoms** [comment]
fixed
