### ISSUE TITLE
MC-TechColonies Server keeps kicking me off

### ISSUE THREAD

**Issue by SadHorizion77210** [ldtteam/minecolonies#5036]
### Minecolonies version # Update to the newest minecolonies and structurize alpha first and see if your issue might be already fixed!

Version: 

### Expected behavior

- 

### Actual behaviour

- 

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:https://gist.github.com/SadHorizion77210/e9eae8e8b6eac0b38b73800d6a5cf0ec
- crashlog:

**Comment by Raycoms** [comment]
Please send us the things on the discord since this is not related to minecolonies the mod itself.
