### ISSUE TITLE
Texture bug with optifine

### ISSUE THREAD

**Issue by tannermc201** [ldtteam/minecolonies#5038]
### Minecolonies version # Update to the newest minecolonies and structurize alpha first and see if your issue might be already fixed!

Version: 0.9.2

### Expected behavior

- 

### Actual behaviour

- 

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

**Comment by someaddons** [comment]
https://github.com/sp614x/optifine/issues
