### ISSUE TITLE
Crash related to obtaining Dye from flower after starting the minecolonie with supplycamp in inventory

### ISSUE THREAD

**Issue by Ruumablood** [ldtteam/minecolonies#5039]
Hey guys Ran into a issue that has taken a while to figure out. Its a strange one.. Okay so, game works fine and ill go get some flowers to turn into dye, ill put the flower in the box and i can pull the dye out fine no issues... soon as i make the Supplycamp before even putting it down, its still in my inventory, and when i go to put a flower in, its okay but soon as i try to pull out the dye it crashes.  I tried with all 3 versions.  First time trying to post a crashlog idk if thats enough to do it
### Minecolonies version # Update to the newest minecolonies and structurize alpha first and see if your issue might be already fixed!

Version:  1.12.2-0.11.841-ALPHA

### Expected behavior

The Crash happens after i try to pull Dye from my box into the inventory
### Actual behaviour

To be able to put a flower in the box and pull out the dye, only crashes AFTER i have the supply camp in my inventory and after placing it etc. 

### Steps to reproduce the problem

1. put the supply camp in your inventory ready to be placed on the ground
2. Go find a flower
3. Try to pull out dye from flower
4. ...  Crash
[crash-2020-05-19_10.31.18-client.txt](https://github.com/ldtteam/minecolonies/files/4652547/crash-2020-05-19_10.31.18-client.txt)

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

**Comment by Raycoms** [comment]
Optifine bug, please report to optifine.

**Comment by Ruumablood** [comment]
Thank you!


Sent from Yahoo Mail for iPhone


On Tuesday, May 19, 2020, 3:06 PM, Raycoms <notifications@github.com> wrote:




Closed #5039.
