### ISSUE TITLE
Scan Filename's

### ISSUE THREAD

**Issue by pmardle** [ldtteam/minecolonies#504]
### Minecolonies version

version minecolonies-universal-1.10.2-0.6.2440 

### Expected behavior

- Scan Filename something like 128758273548758734.nbt

### Actual behaviour

- Scan Filename like SCAN_§r§r-§r1485297892146.nbt§r
Note the filename it gives you in game is correct, but in your directory it looks like the above

### Steps to reproduce the problem

Scan anything :)

**Comment by cltnschlosser** [comment]
Looks like the name is colored or something, that's when I've seen characters like that in the past.

**Comment by Raycoms** [comment]
Sorry I think I have fixed that already.
Should test if it still happens with the newest version on curse.
The problem is when he retrieves the language string wrongly.

2017-01-28 1:26 GMT-02:00 Colton Schlosser <notifications@github.com>:
