### ISSUE TITLE
Minecolonies keep closing my game

### ISSUE THREAD

**Issue by Aaladytoonice** [ldtteam/minecolonies#5040]
### Minecolonies version # Update to the newest minecolonies and structurize alpha first and see if your issue might be already fixed!

Version: 1.15.2

### Expected behavior
 Be able to put down ship or supply camp

- 

### Actual behaviour

- 
When I try to put the ship down in water one part is red underneath no matter where I try to put it and when I okay it, it closes my whole Minecraft game. 

### Steps to reproduce the problem

1.  Fix the putting down the ship or supply camp
2.  not have it close my game
3.  I will be able to get the town hall and building tool to start it
4. ... Profit
I can play Mine colonies

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

**Comment by someaddons** [comment]
update to the newest minecolonies and structurize, just like the template already tells you...

**Comment by Aaladytoonice** [comment]
I did update it to the newest version. I went on your website to get the
latest minecolonies which said latest was 1.15. Is that the correct one?

**Comment by Raycoms** [comment]
https://minecraft.curseforge.com/projects/minecolonies

**Comment by ravenbuilder934** [comment]
There are multiple versions of Minecolonies within a Minecraft version.

**Comment by Aaladytoonice** [comment]
I have the Mine colonies 1.15.2 release and structurize release but still
closing my game

**Comment by Raycoms** [comment]
Don't download the release, download the alphas.

**Comment by Aaladytoonice** [comment]
OK I will try that

**Comment by Aaladytoonice** [comment]
I got it to work. Can you in longer extend the town hall distance building.
I looked in config and option is in longer there

**Comment by Aaladytoonice** [comment]
How to extend the boundaries from the townhall in 1.15.2 alpha version?

**Comment by ravenbuilder934** [comment]
Upgrade town hall to level 3 or 5, build guard towers near the edge of the build range and upgrade them.
To see the current size hold the build tool in hand.
Make sure that no building touches or is outside the town area - or you can't build them.

(from #5089)
