### ISSUE TITLE
no Barbarian Raids

### ISSUE THREAD

**Issue by Xologamer** [ldtteam/minecolonies#5042]
### Minecolonies version # Update to the newest minecolonies and structurize alpha first and see if your issue might be already fixed!
minecolonies-1.12.2-0.11.804-RELEASE

Version: 

### Expected behavior

Babarian raids should happen every few days
- 
no babarian raids after more than 20real life days
### Actual behaviour

thats the problem its not happening
- 
^

### Steps to reproduce the problem

1. Play Minecolonies
2. continue play Minecolonies
3.  ...
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

**Comment by ravenbuilder934** [comment]
When they weren't happening, did you have four or less citizens? They're only triggered if you have 5 or more.

**Comment by Xologamer** [comment]
yea about 20-30

**Comment by Xologamer** [comment]
are there other requirments or just 5 people?

**Comment by ravenbuilder934** [comment]
Not sure. I play on Peaceful myself, so...

**Comment by Ampaex** [comment]
First of all update to the latest version and check if it's still happening. Second, did you change the config file or it's like default?

**Comment by Xologamer** [comment]
> First of all update to the latest version and check if it's still happening. Second, did you change the config file or it's like default?

we checked the config files like 5times and there is everything like it should be - isnt this the latest 1.12 version?

**Comment by ravenbuilder934** [comment]
New versions stopped coming out on 1.12. I think Ampaex means update to the latest 1.15.2

**Comment by someaddons** [comment]
![image](https://user-images.githubusercontent.com/38401808/82487137-3d4b8c80-9ade-11ea-9048-2d942906a43e.png)

**Comment by Ampaex** [comment]
This is the last version:
[Link to curseforge](https://www.curseforge.com/minecraft/mc-mods/minecolonies/files/2932783)
And as ravenbuilder said, actually we don't release new 1.12 minecolonies versions, only if it's for fixing a critical bug.

**Comment by Xologamer** [comment]
> This is the last version:
> [Link to curseforge](https://www.curseforge.com/minecraft/mc-mods/minecolonies/files/2932783)
> And as ravenbuilder said, actually we don't release new 1.12 minecolonies versions, only if it's for fixing a critical bug.

ok, thats to bad :c  - what are the other requirments to get raided maybe its our fault and not a bug (but we tryed everything)?

**Comment by Raycoms** [comment]
There is a command to turn off raids, maybe you triggered that at some moment. When in peaceful it also doesn't trigger raids. You could try the /mc raid-all-now commands to see.
