### ISSUE TITLE
Deliverymen not picking up stuff from racks in miner

### ISSUE THREAD

**Issue by outnampichtim** [ldtteam/minecolonies#5043]
### Minecolonies version # Update to the newest minecolonies and structurize alpha first and see if your issue might be already fixed!

Version: 0.11.948-ALPHA 

### Expected behavior

The deliverymen taking stuff from the racks in the miner.

### Actual behaviour

- I have a miner level 3 medieval spruce and there are racks one level down and the miner stores his stone and ores there but the deliverymen never pickup the stuff from those racks.

### Steps to reproduce the problem

1.  Build a miner level 3.
2.  put stuff in the racks.
3. Wait until the deliverymen don't take stuff.
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

**Comment by Ampaex** [comment]
Have you checked in the miner's hut if delivery is enabled?

**Comment by outnampichtim** [comment]
It is, the hut's inventory is emptied by Dmen but non of the racks.

**Comment by Raycoms** [comment]
Can you send us the world?

**Comment by outnampichtim** [comment]
[rom2.zip](https://github.com/ldtteam/minecolonies/files/4667017/rom2.zip)

**Comment by Tobiti** [comment]
I have the same problem

**Comment by Raycoms** [comment]
@outnampichtim this is missing a bunch of things actually. I need the full world.

**Comment by outnampichtim** [comment]
Sorry 
[rom2.zip](https://github.com/ldtteam/minecolonies/files/4756976/rom2.zip)
And I think I have the same issue with the farmer

**Comment by Raycoms** [comment]
Tested this, at least in the newest version the dman does pick things up for me.
