### ISSUE TITLE
Petrified oak slab recipe

### ISSUE THREAD

**Issue by DiabolosMan** [ldtteam/minecolonies#5044]
### Minecolonies version # Update to the newest minecolonies and structurize alpha first and see if your issue might be already fixed!

Version minecolonies-1.15.2-0.11.948-universal.jar
Forge version 31.2.0

### Expected behavior
Have a way to create petrified oak slab

### Actual behaviour
I was upgrading my citizen hut to lvl 5 (Birch style) but it is now asking for Petrified oak slab.
Unable to find a way to create it by JEI. I had a look in google and one forum was talking about stonecutter. Here is what I have when I use stone cutter:
![Petrified](https://user-images.githubusercontent.com/63854770/82445922-f8a3ff00-9aa5-11ea-9c3a-5702572c6341.png)

All in all, I know lvl 5 should be expensive and hard to do and I really like that because it forces to know more Minecraft and go everywhere in everybiomes. However, for citizen huts, the recent change (for my case birch style) is really TOO expensive and i will prefer stay at lvl4 for all my citizen huts and have more lvl 4 instead. It does not change a lot to have 10 citizen hut lvl 4 instead of 8 citizen hut lvl 5 for my case. Only 2 more buildings for my whole colony. I know it is on purpose but I think it is really too complex and expensive amount of time. I only need one lvl5 and for others, I will stay 4.

**Comment by Raycoms** [comment]
This is a schematic issue, schematics shouldn't include those slabs #5006

**Comment by DiabolosMan** [comment]
It is still not fixed in minecolonies-1.15.2-0.11.949-universal-universal. Is it supposed to be fixed in this version ?
I still cannot upgrade all my citizen huts to lvl 5 because of that petrified oak

**Comment by Raycoms** [comment]
@lunadragnstar is that fixed in the latest schematic PR?

**Comment by lunadragnstar** [comment]
It should be as I don't see any on the server.

**Comment by DiabolosMan** [comment]
It is still not fixed in minecolonies-1.15.2-0.11.954-universal.jar. Is it supposed to be fixed in this version ? Still cannot lvl up my citizen hut. Is there a way to see from which version a schematic PR is included ?

**Comment by Raycoms** [comment]
Not atm, as soon as the buildsystem is online again then yes.
