### ISSUE TITLE
How to cancel construction of Decorations ? (i.e. Big_Well)

### ISSUE THREAD

**Issue by Kasilyn** [ldtteam/minecolonies#5045]
Version: minecolonies-0.11.938-BETA-universal

### Expected behavior
Some UI to be able to delete a decoration. I missclicked and placed a well instead of the building I intended to place and I have no idea how to delete it

### Actual behaviour
Unable to find a UI, either in builders hut, either in town hall, the builder was  auto assigned and has started working on the missplaced well

### Steps to reproduce the problem

1. Missplace a well
2. be unable to delete it
3. ...
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/
- latest.log:
- crashlog:

**Comment by Raycoms** [comment]
go to the townhall, there is a list of workorders, delete the one for this decoration.

**Comment by Kasilyn** [comment]
I did this already but the builder is still building :/

**Comment by Raycoms** [comment]
the builder should place one more block, detect it and then stop after removed from the list
