### ISSUE TITLE
Pirates' Consistantly Crashing Server

### ISSUE THREAD

**Issue by Yourname942** [ldtteam/minecolonies#5046]
### Minecolonies version # 
minecolonies-1.12.2-0.11.841-ALPHA-universal.jar

Version: 
Minecraft Version: 1.12.2
forge-14.23.5.2847

### Expected behavior
To be invaded by pirates, and not have the server crash shortly afterwards. 

### Actual behaviour
Note:
- There are two different players who own their own mine colonies (myself, and another player)
- I have only 4 citizens and do not get invaded yet.
- The other player who owns their own mine colony has 8 citizens and about 10 buildings

What happens:
- There is a message that says the pirates are spawning and where
- Then the server crashes a min or so later
- This happens every time pirates invade (but not when the other type of raiders invade)
- Relaunch the server
- The server will not crash for the remainder of the current pirate's invasion, but this happens every time he gets invaded by pirates 
- I was told that the spawn rate occurs every 20 "minecraft minutes" (ie. 8:10 830 850)

### Steps to reproduce the problem
1. Be in multiplayer, as I do not know if this occurs in Singleplayer
2. Create a mine colony with about 6~8 citizens near a body of water like a river
3. Get invaded by pirates and see if you crash

If you cannot reproduce the problem with the above, then 
1. download my modpack and serverpack (maybe it is a compatibility issue?)
2. Disable or remove these two mods: In control and Mo Glowstone (that is our current setup)
2. Run the server
3. Be in multiplayer, as I do not know if this occurs in Singleplayer
4. Create a mine colony with about 6~8 citizens near a body of water like a river
5. Get invaded by pirates and see if you crash

### Logs: 
- latest.log: https://gist.github.com/Yourname942/e823ce92b5fd380f4d77f9fbfda5c3a6
- crash log: https://gist.github.com/Yourname942/7f691754c764e44f2291248780e3c7e4
- Minecolonies.cfg: https://gist.github.com/Yourname942/765defc3627fa51a9b728121fb08340d

**Comment by someaddons** [comment]
gonna need you to upload the crashlog, your latest.log has nothing in it

**Comment by Yourname942** [comment]
Yes I will ask the other player for his crashlog as I was offline at the time. Also, just to verify, did you click the little hyperlink that says view the full file?

**Comment by Yourname942** [comment]
Here is the most recent latest.log:
https://gist.github.com/Yourname942/e823ce92b5fd380f4d77f9fbfda5c3a6
Here is the crash log:
https://gist.github.com/Yourname942/7f691754c764e44f2291248780e3c7e4

**Comment by Yourname942** [comment]
I posted in Minecolonies' discord, and Apotheosis was mentioned. I can confirm that something between Minecolonies and Apotheosis is the issue. According to Shadows (one of their devs) 

> that's a bug with minecolonies, they're directly setting spawner tile entities in the world, which breaks apoth
> it's not even a necessary thing to do, as setting the spawner block makes the right tile enttiy

**Comment by Spray-Art-Rick** [comment]
I've run into this same bug, however I'm running MineCraft version 1.15.2 and using minecolonies-0.11.938-BETA-universal.jar with structurize-0.10.317-Alpha.

About the only difference I have is that when my minecraft server crashes and is restarted there is no ongoing pirate raid. It's as if it never happened.
[crash-2020-05-27_02.05.14-server.txt](https://github.com/ldtteam/minecolonies/files/4686861/crash-2020-05-27_02.05.14-server.txt)

**Comment by someaddons** [comment]
its not the same bug and you're using an outdated minecolonies version with the newest structurize version...

**Comment by Spray-Art-Rick** [comment]
My apologies if this was not the place to post, but I was directed to not open a new report if there were similar bug report already made. Since mine matched so closely I felt that I would be adding information to an already addressed problem. I did note the difference in Minecraft versions and erred on the side of caution by adding here.

 I also ran the correct version of structurize (0.10.313-Alpha) with the version of minecolonies I am running. I upgraded to the latest alpha structurize to see if that would correct the problem and it did not. Other than the crash from the pirates spawning the mod seemed to run fine under .317-alpha so I left it in.

**Comment by Raycoms** [comment]
What minecolonies version are you on?

**Comment by Spray-Art-Rick** [comment]
minecolonies-0.11.938-BETA-universal

**Comment by Raycoms** [comment]
get the latest alpha there too

**Comment by Spray-Art-Rick** [comment]
Moving to the Alpha version seems to have cleared my crashes, at least for a command activated raid. But if that worked I'm sure the normal spawn raids should work as well. Thank you for encouraging me to do that, I was hesitant to try the alpha.

**Comment by Yourname942** [comment]
Even with using this command the pirates causes an instant crash for me: /mc raid-now

**Comment by Raycoms** [comment]
Remove the aposthesis coremod.

**Comment by Yourname942** [comment]
That seems like a temporary workaround than a fix to an issue.

**Comment by Raycoms** [comment]
They have a coremod that meddles with the spawner tileEntity.
