### ISSUE TITLE
AI Issues. 1.15.2 - 11.938-BETA

### ISSUE THREAD

**Issue by deadspidervenom** [ldtteam/minecolonies#5047]
Version: minecolonies-0.11.938-BETA-universal

Builder - Tier 4 and Tier 3

Issue 1: Does not register items in the warehouse most times, will sit there and wait for me to craft the item.
Issue 2: Items randomly disappear, from tools to items for building, usually when involving the fulfill request button or the resource button on the second page of the builder hut.
Issue 3: Wont register damaged tools as vaild tools (this might just be a incompatibility with silent tools)

Final Issue: Saved the "best" for last. My tier 4 builder was working on upgrading the tier 2 townhall too a tier 3. They went back to to their hut and requested for a item, it did not show the icon above their head, but it spammed the console(which i found out after a crash(possiblely unrelated))

They only spammed it when they went to their builder hut and "requested" a item. and it only happened recently 

This first paste is a quick copy i made, the second one is the entire log up to the crash, i would give the crash report however it just states that the server shut itself down cause a tick took 60 seconds which i believe was just user error on my part and not the mod.

https://pastebin.com/VvE580vC

https://pastebin.com/tBSVhijE

**Comment by Raycoms** [comment]
Can you try the latest?

**Comment by deadspidervenom** [comment]
> Can you try the latest?

Umm to my knowledge that IS the latest.

https://cdn.discordapp.com/attachments/486752085082112024/713002772747780187/unknown.png

**Comment by Raycoms** [comment]
alpha

**Comment by deadspidervenom** [comment]
> alpha

Took a moment to find it, and idk about the rest but the one about the console spam, is still the case.

**Comment by deadspidervenom** [comment]
Good news i fixed the console spam by fulfilling the request. Though i would still check into it.
