### ISSUE TITLE
Pirates on .948 absolutely impossible in singleplayer

### ISSUE THREAD

**Issue by wolfsilver00** [ldtteam/minecolonies#5048]
Version: 948

### Expected behavior

Pirates spawn, normally, maybe 10? 15? 

### Actual behaviour

Pirates spawn. They dont stop spawning. Ive got a one hit kill sword and I still got drowned. 10 to 20 archers, 10 to 20 melee guys. If I killed, more of them kept coming. At some point I had to /mc kill raider  because they were getting into the colony. It was not a pirate raid, it was a mini-army that a solo player cant deal with at all. There was no way for me to get into the ship to destroy the spawners.

**Comment by Raycoms** [comment]
you were supposed to go to the ship and destroy the spawners =D

**Comment by wolfsilver00** [comment]
Yeah, I know.. Thing is, its impossible to get to the ship with 30+ dudes hitting me in the face, and more spawning..

**Comment by Raycoms** [comment]
But yeah, we got some things planned to reduce this significantly. Howevr, you are meant to let your guards handle a part of this
