### ISSUE TITLE
build 2414 colony owner can be added to other colonies

### ISSUE THREAD

**Issue by kreezxil** [ldtteam/minecolonies#505]
### Minecolonies version
build 2414

### Expected behavior

- when player b tries to add player a to his colony and player a already has a colony player be should be notified that he can not do that

### Actual behaviour

- player a who has a colony is added to player b's colony and now recieves messages of both builders

### Steps to reproduce the problem

1. player a creates a colony
2. player b creates a colony
3. player b adds player a to his colony and succeeds

**Comment by Raycoms** [comment]
That's not a problem for me.
Why shouldn't a player be able to be owner in one colony and friend,
officer, neutral or feud in another one?

2017-01-25 19:55 GMT-02:00 kreezxil <notifications@github.com>:

**Comment by forReason** [comment]
that is intended. but a neat feature would be to turn off messages from other colonies or a max blockrange 

and knowing of which colony the messages come from (<- already requested)

**Comment by Raycoms** [comment]
The knowing will come in the next version =D It's implemented in 1.11
already.

2017-01-25 21:03 GMT-02:00 Julian B. <notifications@github.com>:

**Comment by Raycoms** [comment]
You actually should only receive messages from colonies you are "officer".
But there is a bug which does prevent that in some versions.

2017-01-25 21:04 GMT-02:00 Ray Neiheiser <ray.neiheiser@gmail.com>:

**Comment by forReason** [comment]
well even if im officer a option or so would be nice. so if the original owner is online I can shut down the messages so i can lead my own colony and he can lead his

or maybe you just want officer to use the chests and build at his colony.

**Comment by ProsperCraft** [comment]
The issue I foresee with anyone being able to add anyone is a harassment issue, nobody should be allowed to add me to their town without my permission, much like how towny had an add on called questioner that caused a major adding you to get asked to the player do you want to be added and they had the option to deny.

**Comment by kreezxil** [comment]
The other issue is the incessant amount of spam from all of the builders
talking to you from all of the colonies you are a "member" of. So in
addition to a permission system as ProsperCraft points out, there should be
an option to limit which builders to which you want to listen.

BTW, FWIW, I became a donator last night. :)

**Comment by Raycoms** [comment]
Does this spam still happen?
Is it still bad, do we need to work here?

**Comment by kreezxil** [comment]
Players on the server have stopped teaming up as friends between colonies
to avoid it. So not sure if it's an issue any longer.


On Mar 5, 2017 9:18 AM, "Raycoms" <notifications@github.com> wrote:

Does this spam still happen?
Is it still bad, do we need to work here?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Minecolonies/minecolonies/issues/505#issuecomment-284234640>,
or mute the thread

**Comment by Raycoms** [comment]
Only officers should remove the needed messages. But, due to the
deliveryman, we should have less worker spam as well atm.

2017-03-05 12:21 GMT-03:00 kreezxil <notifications@github.com>:

> Players on the server have stopped teaming up as friends between colonies
> to avoid it. So not sure if it's an issue any longer.
>
>

**Comment by marvin-bitterlich** [comment]
Closing this for now
