### ISSUE TITLE
Town Hall Build Preview Not Matching

### ISSUE THREAD

**Issue by DerrickHarrigton** [ldtteam/minecolonies#5050]
Minecolonies version 0.11.878 - Alpha
Minecraft Version: 1.15.2

### Expected behavior
When placing the town hall, the previewed tape outline should match after pressing the green check mark.

### Actual behaviour
When pressing the green check, the tape outline and build layout completely changes. The build is in pretty much an entirely new place.

### Steps to reproduce the problem
   

1.  Place town hall and use build tool to preview the expected build
2.  With your desired placement, press the green check to confirm
3.  After pressing the green check the layout shouldn't be the one you wanted.
![2020-05-21_18 14 44](https://user-images.githubusercontent.com/65741894/82615166-5f511780-9b8f-11ea-9e1a-678f3245f148.png)
![2020-05-21_18 14 51](https://user-images.githubusercontent.com/65741894/82615179-66782580-9b8f-11ea-8b92-b24aaeaf1456.png)
![2020-05-21_18 14 56](https://user-images.githubusercontent.com/65741894/82615182-6a0bac80-9b8f-11ea-8ae6-e8cda7146c8a.png)
![2020-05-21_18 15 03](https://user-images.githubusercontent.com/65741894/82615185-6d069d00-9b8f-11ea-8e68-b81df103ccfb.png)

**Comment by DerrickHarrigton** [comment]
The same thing has also happened with chickenherders and citizen's hut.

**Comment by Asherslab** [comment]
update. you're many versions behind
