### ISSUE TITLE
Unreasonable hospital/illness design

### ISSUE THREAD

**Issue by tcz717** [ldtteam/minecolonies#5051]
### Minecolonies version # Update to the newest minecolonies and structurize alpha first and see if your issue might be already fixed!

Version: minecolonies-1.15.2-0.11.948-universal

### Expected behavior

When a colony is in the beginning stage (5-6 citizens). It has a large chance that some citizens get sick. However, at this stage, the player has too little resources and workers to build a university and hospital. So, those sick citizens will lay in bed forever and become useless until you finally build a hospital. 

In my opinion, sick citizens should not lay forever to become the blocker of the colony growing.
there are a couple of ways we could try to workaround:
1. Sick citizens could die if don't get healed for a long time
2. After certain days, sick citizens have a chance to recover by themselves
3. Provide more option to allow the player to heal sick citizens at the beginning stage
 

### Actual behaviour

Sick citizens will lay in bed forever and become useless until you finally build a hospital. 

### Steps to reproduce the problem

N/A

### Logs: Latest.log and crashlog at https://gist.github.com/

N/A

**Comment by Raycoms** [comment]
Citizen already have a chance to get healed "miraculously" + as a player you can heal 99% of the illnesses with carrots + potatoes, that should be not too difficult to get.
