### ISSUE TITLE
Minecolonies saving then crashing

### ISSUE THREAD

**Issue by 99skyline** [ldtteam/minecolonies#5052]
### Minecolonies version # Update to the newest minecolonies and structurize alpha first and see if your issue might be already fixed!

Version: minecolonies-0.10.771-RELEASE-universal on minecraft 1.15.2 with newest released version of forge as of 5/21/2020

### Expected behavior

- To be able to put down settlement pieces.

### Actual behaviour

- As soon as either the ship or the other supply starter piece is put down, it saves the world and then it crashes to my desktop.

Here are all my mods I'm currently using: [here](http://prntscr.com/slf3wf)
Here is the setup to my .minecraft folder: [here](http://prntscr.com/slf4kj)

### Steps to reproduce the problem

1. Open minecraft
2. Start a new world in creative 
3. Put down either of the two starter supply bases.
4. ... Profit (crash)

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: https://gist.github.com/99skyline/bb730693f422366ecebdcde50c952b76
- crashlog: https://gist.github.com/99skyline/b21393cb6750f4fb3c793a806782da73

**Comment by Raycoms** [comment]
Update to latest alpha
