### ISSUE TITLE
Reposition issue - 1.15.2 - minecolonies-1.15.2-0.11.948-universal

### ISSUE THREAD

**Issue by deadspidervenom** [ldtteam/minecolonies#5053]
Version: minecolonies-1.15.2-0.11.948-universal

When you reposition a structure it will point one direction and not rotate, regardless of what direction you want it to rotate.

**Comment by Raycoms** [comment]
duplicate issue, yeah we're working on reworking reposition completely. It is not working nicely how it is done atm.
