### ISSUE TITLE
Signs and vines confuses colonists

### ISSUE THREAD

**Issue by SilentSoulsSr** [ldtteam/minecolonies#5055]
### Version:
MC-TechColonies: Version: v 3.0 Minecraft Version: 1.15.2 (modded) forge-31.1.87
minecolonies-1.15.2-0.11.948-universal.jar
structurize-0.10.315-ALPHA.jar
(older versions as well)

### Expected behavior
Placing sings (or vines), colonists just ignore them. and walk through them.
Pathing would ignore signs / vines, and treat them as air. (perhaps an added weight for vines due to the lower speed it might involve)

### Actual behaviour
When a sign is in the path of a colonist, the colonist gets confused.
The colonist keeps turning around not knowing which direction to go. eventually it will but can take up to 10 seconds. The fortress build has signs everywhere, and it is obvious there.

As an aditional problem, pathing will try and not takes routes with signs. this especially was obvious on the Fortress set, where they rather walk over blocks around houses, and through other areas then to take the 1 block wide space with signs in it., when i removed the signs, or placed them higher, they picked the correct paths. 

### Steps to reproduce the problem
1. place a sign in the pathway of a colonist.
2. wait
3. Colonist walks over sign
4. Colonist gets confused 

### Logs: Latest.log and crashlog at https://gist.github.com/
logs not relevant i presume

**Comment by Tobiti** [comment]
Banners are creating this behaviour too and cacao beans are although ignored, but then the workers are stuck, because they can't get through it

**Comment by SirSmuggler** [comment]
I have observed similar behaviours with chorus plants and trapdoors.
