### ISSUE TITLE
Create notification when pirates have been dealt with

### ISSUE THREAD

**Issue by PowerSchill** [ldtteam/minecolonies#5056]
### Minecolonies version # Update to the newest minecolonies and structurize alpha first and see if your issue might be already fixed!

Version: 

### Expected behavior

When **all** of the pirate ship spawners have been destroyed and all pirates killed there should be a notification message stating that the pirate incursion has been dealt with.

- 

### Actual behaviour

- There is currently no warning until the ship has departed. 

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit

**Comment by someaddons** [comment]
already in planned features

**Comment by Raycoms** [comment]
He'll do it, so to make sure no one does the same work twice

**Comment by someaddons** [comment]
ah ok

**Comment by DiabolosMan** [comment]
Is it this change ? https://github.com/ldtteam/minecolonies/issues/4986#issuecomment-628001419

**Comment by PowerSchill** [comment]
No. I searched in Forge but i didn’t see any implementations other than the boss bar. It was mentioned looking at the vanilla Minecraft source but I wouldn’t know where to start.
