### ISSUE TITLE
Suggestion: Deliver building materials to the job site not the builder's hut

### ISSUE THREAD

**Issue by Snoopydude** [ldtteam/minecolonies#5057]
Once your town gets to be a decent size the builders are running around a lot even if you space them out around the town.  I have 4, one on each corner of the town hall and it takes them a long time to construct anything.  If the materials for the build could be delivered to the inventory of the new building then the builder could just stay in place and build.  I would even keep him from going back to his hut to get items from the player.  The player could just bring them to the build as well.

**Comment by Asherslab** [comment]
Please put suggestions in the pinned suggestion issue: #4535
