### ISSUE TITLE
Builder Not Building

### ISSUE THREAD

**Issue by Kangy1103** [ldtteam/minecolonies#5059]
### Minecolonies version # Update to the newest minecolonies and structurize alpha first and see if your issue might be already fixed!

Version: minecolonies-1.12.2-0.11.811-BETA-universal

Mod part of MC Eternal on Twitch and unable to update mod

### Expected behavior

- Builder man takes materials from Builder hut and builds mine

### Actual behaviour

- Builder stands in hut. He isn't asking for tools or materials and has no requests related to the mine. Mine only needs 1 ladder and 8 torches. He does go back to his house to sleep at night though

![image](https://user-images.githubusercontent.com/42292756/82693844-25007c80-9c5a-11ea-8173-430b48c723c8.png)
![image](https://user-images.githubusercontent.com/42292756/82693883-38abe300-9c5a-11ea-86a8-301e15619ee3.png)
![image](https://user-images.githubusercontent.com/42292756/82693916-46616880-9c5a-11ea-88df-86f1433ede41.png)

### Steps to reproduce the problem

1. Start construction of a mine
2. Give builder hut all materials required
3. When nearly finished the builder doesn't complete the build
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: N/A
- crashlog: N/A

**Comment by Raycoms** [comment]
How many days did you wait?

**Comment by Kangy1103** [comment]
It's been at least 15 in game days. I've been busy making 10/10/10 crops and other stuff so it could be longer

**Comment by Raycoms** [comment]
Any exceptions int he log?

**Comment by Raycoms** [comment]
Is he hungry or sick?

**Comment by Kangy1103** [comment]
I had no idea I had to give them food so you may be on to something there. I'll research how to feed them, give him food and get back to you if that's okay?

**Comment by Raycoms** [comment]
sure

**Comment by Kangy1103** [comment]
So the builder is completely starving. I've put some bread in his inventory for him to eat and he is still just standing there. He isn't eating the food.

Honestly, this is my first experience with the mood so I may just be an idiot. If that's the case I hugely apologise!

**Comment by Raycoms** [comment]
Try to fire him quickly, and rehire him, he'll eat the bread quickly and be fine (fire/re-hire is the go-to solution for 99% of your problems).

**Comment by Kangy1103** [comment]
Okay he was just hungry. Fired him, didn't eat. Gave him toast instead of bread and he ate it. Rehired him and he went off to build.

Should he have ate the bread or do they only eat certain foods?

Also, sorry for being an idiot and wasting your time but thanks for helping me!

**Comment by Raycoms** [comment]
They eat only stuff that can not be further cooked. (Bread can be cooked to toast one further step)

**Comment by Kangy1103** [comment]
Gotcha. Thanks again for your support!

I'll close the issue
