### ISSUE TITLE
The Name of the guard is missing.

### ISSUE THREAD

**Issue by ProsperCraft** [ldtteam/minecolonies#506]
### Minecolonies version

2414

https://gyazo.com/b3987d9447c021569eb2429ee93853c0

**Comment by Raycoms** [comment]
Yeah that will be fixed with the next update for sure =D
I have the fix in the branch for the merge for the deliveryman already.

2017-01-25 19:59 GMT-02:00 ProsperCraft <notifications@github.com>:
