### ISSUE TITLE
Builder Requesting Unobtainable Items

### ISSUE THREAD

**Issue by GhostWarriorDS** [ldtteam/minecolonies#5061]
Version: 
minecolonies-1.15.2-0.11.948-universal (alpha)
structurize-0.10.315-ALPHA

### Expected behavior
Builder generates unobtainable items (grass blocks, grass, etc) for construction and upgrades.

For me it has been building lvl 1 medieval oak fishing hut and lvl 2 medieval oak lumberjack hut.

### Actual behaviour
Builder repeatedly requests grass blocks and grass but I cannot supply them in survival without silk touch.

The builder walks to the construction project from the builder hut after selecting try cancel option. However, the request reappears just before he arrives at the construction site and he heads back to the builder hut. 

### Steps to reproduce the problem

1. Build a lvl 1 medieval oak fishing hut and lvl 2 medieval oak lumberjack hut
2. Supply all the needed materials that can be acquired in survival
3. Watch in pain as the builder demands an object that a mere mortal cannot provide (without cheats on or silk touch).

**Comment by Tobiti** [comment]
I think you can give him dirt and he will just create grassblocks out of it

**Comment by MatthiasMann** [comment]
Yes, grass will be substituted with dirt, and grass is obtainable using shears.
