### ISSUE TITLE
Builder having trouble with compass and clock

### ISSUE THREAD

**Issue by wolfsilver00** [ldtteam/minecolonies#5063]
Version:  948

### Expected behavior
Give clock or compass, builder uses it correctly

### Actual behaviour

No matter if you put it via the builders hut menu or via fulfilling the request on the builder or just putting it into their inventory manually, they dont seem to recognize clocks and compasses, also duping them some times when leaving it in the hut (it does not seem to happen for a particular reason, some times it does, some it doesnt)

Builder will stay in the hut block for a while, until at some point, even if he does not move from there, the building just.. builds itself. This can be accelerated by punching the shit out of the builder, one punch and wait at a time, until he starts working.

### Steps to reproduce the problem

Level up something (for example, dark oak citizen level 5 or delivery level 5) that requires a clock or compass, watch as he wont work properly.

**Comment by Raycoms** [comment]
It's a duplicate issue, we got this reported already to #4510 since mods change the default vanilla items for those, that's why its causing issues.
