### ISSUE TITLE
Suggestion: Make the builder request more than one thing if the Dman is able to do it

### ISSUE THREAD

**Issue by wolfsilver00** [ldtteam/minecolonies#5065]
### Expected behavior

Builder has 20 things he needs, he puts up a request based on the level of Dman (for example, if there is a Dman level 5, he asks for everything), bonus points if a Dman can be assigned to a particular builder. That or make Dmans deliver things to huts (if its in the list of needed items) even if another colonist has not requested it yet.

### Actual behaviour
Right now the builder asks for one thing, dman gets it, builder goes, does its thing, comes back, asks for another.. rinse and repeat. Having a higher level dman is worthless, Ive upgraded 3 dmans and the building process has not been made any faster because they only bring one item even if they can bring more (except of course, when the builder needs a lot of stacks of a particular item, in which case they only bring one stack because only one is requested at a time)

**Comment by Raycoms** [comment]
Yeah, that is in the list of planned things, please read the list of suggested/planned feature and suggest new features there.

**Comment by wolfsilver00** [comment]
> Yeah, that is in the list of planned things, please read the list of suggested/planned feature and suggest new features there.

I did, and I just double checked and there does not seem to be a suggestion like this one, closest one is to have a minimum inventory on builders and this is quite different and easier to code I believe.

**Comment by Raycoms** [comment]
We called it "prefetch" materials, might have left it out there. but def planned.
