### ISSUE TITLE
crash after placing supply ship or camp

### ISSUE THREAD

**Issue by fenpaws** [ldtteam/minecolonies#5069]
Version: 0.10.771-RELEASE-universal

### Expected behavior
after placing the supply ship or supply camp the corresponding building should appear

### Actual behavior
game crashes immediately

### Steps to reproduce the problem

1. download this version of mine colonies and structurize 0.10.313-RELEASE
2. use recommended forge
3. build a ship or camp
4. place it

### Logs: Latest.log and crashlog at https://gist.github.com/
- latest.log: https://paste.ee/p/8wfrZ
- crashlog: https://paste.ee/p/9H2uT

**Comment by fenpaws** [comment]
why was this issue closed?

**Comment by someaddons** [comment]
for not reading the template
