### ISSUE TITLE
Crashing When I Place a Supply Ship

### ISSUE THREAD

**Issue by OllyEland** [ldtteam/minecolonies#5072]
I downloaded Minecolonies on the 24th of May and downloaded the newest version, everything ran fine until I tried to place a supply ship and the whole game crashed. There was nothing in the way of it and then everything just crashed. 

Version: 1.15.2

### Expected behavior
Supply Ship placed OR it said there was something in the way

- 

### Actual behaviour
The whole game crashed

- 

I cant get the logs up but the previous issues to do with this I had the same message

### Steps to reproduce the problem
idk

**Comment by Raycoms** [comment]
You updated structurize to a much newer version that the minecolonies one you're playing. Update both to the latest alpha and you'd be fine.
