### ISSUE TITLE
Same as last time

### ISSUE THREAD

**Issue by OllyEland** [ldtteam/minecolonies#5073]
Hey Raycon can you not close it, what do you mean the struturize is different version. They are all the latest?

**Comment by OllyEland** [comment]
Can you tell me which versions of each to download, Thanks

**Comment by Raycoms** [comment]
a) You can comment on closed issues. Please don't open new ones for questions.
b) You downloaded the latest structurize alpha but an old minecolonies release.
Just download the latest alpha of each and you'll be fine.

**Comment by OllyEland** [comment]
I downloaded the minecolonies: minecolonies-1.15.2-0.11.949-universal.jar
Structurize: structurize-0.10.315-ALPHA.jar

Minecolonies apparently now has an error during the load_registries.

**Comment by someaddons** [comment]
949 needs structurize 316

**Comment by OllyEland** [comment]
But Minecolonies is the one not working.

**Comment by OllyEland** [comment]
Does Structurize effect whether Minecolonies will load or not

**Comment by Raycoms** [comment]
yes it does

**Comment by OllyEland** [comment]
ok

**Comment by OllyEland** [comment]
THERE IS NO 316

**Comment by OllyEland** [comment]
its 312, 313 or 315

**Comment by Raycoms** [comment]
So this? https://www.curseforge.com/minecraft/mc-mods/structurize/files/2965256

**Comment by OllyEland** [comment]
![image](https://user-images.githubusercontent.com/65893767/82799986-d2e67380-9e72-11ea-8c71-eb5a81518b22.png)

**Comment by OllyEland** [comment]
look on the right

**Comment by OllyEland** [comment]
there was no 316

**Comment by OllyEland** [comment]
the one u gave me just then is 317

**Comment by Raycoms** [comment]
Maybe you should report this to curseforge. It's in the list of files.

**Comment by OllyEland** [comment]
where has all my comments gone

**Comment by OllyEland** [comment]
ok, the one u gave me was 317, but the other guy said I needed 316

**Comment by Raycoms** [comment]
bigger or equals to 316

**Comment by OllyEland** [comment]
ok

**Comment by OllyEland** [comment]
trying it now...

**Comment by OllyEland** [comment]
IT WORKED!

**Comment by Raycoms** [comment]
![image](https://user-images.githubusercontent.com/6438347/82801153-c4995700-9e74-11ea-970e-d4040e3d3d40.png)
