### ISSUE TITLE
Changing range of townhall

### ISSUE THREAD

**Issue by 99skyline** [ldtteam/minecolonies#5080]
### Minecolonies version # Update to the newest minecolonies and structurize alpha first and see if your issue might be already fixed!

Version: minecolonies-1.15.2-0.11.948-universal

### Expected behavior

- Be able to expand the radius of placeable building from town hall

### Actual behaviour

- Well I haven't found out how to do it, I have searched for over an hour at this point on over a dozen different sites and cant find any answer to this problem. I want to be able to build if I wanted, 500 chunks away from the townhall. I just dont understand how to expand it. I've seen others having this problem and someone named "ray-something" answer with a command line but it doesnt work in my game. My minecraft version is 1.15.2

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

**Comment by Raycoms** [comment]
You place and upgrade guard towers at your colony border, that will allow you to do it.
Similarly upgrading the townhall, building barracks and upgrading other huts to level 3 and 5 will expand your area.
