### ISSUE TITLE
Fisherman just walks into water and then back to the fisherman hut block.

### ISSUE THREAD

**Issue by FuckFaceBecauseSomeoneStoleMyUserhandle** [ldtteam/minecolonies#5081]
My fisherman just repeats, over and over, going from the fisherman hut block, into the water, and then back to the hut block. She doesn't fish, I tried upgrading the hut but that didn't help. I'm using the Nordic building plans. She was fishing up until the inventory was full, then I freed up space but now she just goes back and forth as if she expects there to be ground exactly two blocks away from the edge of the peer that she is supposed to be fishing from.

**Comment by FuckFaceBecauseSomeoneStoleMyUserhandle** [comment]
I built out the space she expected ground to be and now she just stands there, staring out into the water...

**Comment by FuckFaceBecauseSomeoneStoleMyUserhandle** [comment]
https://www.reddit.com/r/Minecolonies/comments/gqnkic/fisherman_just_walks_into_water_and_then_back_to/?utm_source=share&utm_medium=web2x
https://www.reddit.com/r/Minecolonies/comments/gqn7p5/fisherman_just_walks_into_water_and_then_back_to/?utm_source=share&utm_medium=web2x

**Comment by Asherslab** [comment]
Image (literally just copy/paste it):
![image](https://user-images.githubusercontent.com/28527281/82852001-ebbf5980-9f44-11ea-984c-8fd71d0b53c6.png)

**Comment by Raycoms** [comment]
This is also fixed in the newest version.
