### ISSUE TITLE
Glassblower Breaking permanently removes buildable area

### ISSUE THREAD

**Issue by mikejhoff22** [ldtteam/minecolonies#5083]
### Minecolonies version # Update to the newest minecolonies and structurize alpha first and see if your issue might be already fixed!
 

Version: 
structurize-0.10.313-RELEASE
minecolonies-0.11.918-BETA-universal

### Expected behavior

just delete the glassblower outline 
- 

### Actual behaviour

- 
Placing a glass blower near the edge of the placement area to prepare for building then removing it to move it permanently makes that area of your plotted build area unbuildable.

https://media.discordapp.net/attachments/706927907356016740/714675352387190835/unknown.png?width=1442&height=406
### Steps to reproduce the problem

place a glassblower at the edge of your build area and break it.

1. 
2. 
3. 
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

**Comment by Raycoms** [comment]
Fixed in the newest alpha
