### ISSUE TITLE
Bizarre entity flashing within colony border

### ISSUE THREAD

**Issue by snietop** [ldtteam/minecolonies#5084]
Minecolonies 1.15.2
Version: 1.15.2-0.11.949 ALPHA

### Expected behavior
It would be nice if the entity flashing would stop so I don't have to always run a shader.

### Actual behaviour
For the past 2-3 weeks I have been experiencing a bizarre flashing that I can only describe as appearing to be bits of distorted texture from the blueprint schematics (those when you view the template before you place a structure). This problem only occurs within the colony limits and occurs in any world with the colony. I have tried deleting and reinstalling the game version folder ( I have separate folders for every version, each with entirely different saves and a fresh install of the game version) 

I tested if it was caused by other mods such as JEI, timber, useful backpacks, and optifine, but it all seems to be coming from minecolonies. I will continue testing out different solutions and update if I find one. 
I am not able to include a video in this report but I am more than willing to send one via email if necessary.

### Steps to reproduce the problem
My colony has townhall level 3, the entire colony in medieval spruce alternative theme
2 builders at level 3
A warehouse at level 2
2 deliverymen at levels 2 and 3
2 level 3 citizen huts, 4 level 2 citizen huts, and 1 level 1 citizen huts
1 Blacksmith level 1
1 smelter level 1
1 university level 3
1 mine level 3
1 restaurant level 1
1 shepherd level 3
1 farm level 3
1 cowboy level 2
1 lumberjack level 3
2 guard towers, level 2 and 3
1 pig farm level 2

I don't exactly know how to reproduce it but perhaps it has come with one of the buildings. It wasn't an issue when first building the colony.

**Comment by Asherslab** [comment]
There's absolutely nothing we can do about this issue as of current. it's Optifine's issue and fault
