### ISSUE TITLE
How do You change the size of the village?

### ISSUE THREAD

**Issue by OllyEland** [ldtteam/minecolonies#5089]
I am trying to find out how to increase the size of my colony. For example how far away I can build things from my townhall. How???

**Comment by MatthiasMann** [comment]
Upgrade town hall to level 3 or 5, build guard towers near the edge of the build range and upgrade them.
To see the current size hold the build tool in hand.
Make sure that no building touches or is outside the town area - or you can't build them.

**Comment by OllyEland** [comment]
Thanks

**Comment by MrMeender** [comment]
Someone should close this issue
