### ISSUE TITLE
2459 odd crash 

### ISSUE THREAD

**Issue by kreezxil** [ldtteam/minecolonies#509]
### Minecolonies version

2459

### Expected behavior

- to not crash

### Actual behaviour

- crash

### Steps to reproduce the problem

1. use test build

https://gist.github.com/b5a9546f4c58297c05a0842cbfb57819

**Comment by forReason** [comment]
please attach your logfiles. They are located in your minecraft Folder / Logs

**Comment by Raycoms** [comment]
@colton how can this happen?

2017-01-26 6:07 GMT-02:00 Julian B. <notifications@github.com>:

**Comment by kreezxil** [comment]
Server Crash Log: https://gist.github.com/b5a9546f4c58297c05a0842cbfb57819

I haven't gotten this to happen again, so it might be a fluke caused by a stray graviton or some other nonsense.

**Comment by kreezxil** [comment]
I'm thinking it might be safe to push this build to 1.11.2 as I didn't see any new reports from the ProsperCraft gang in the last 10 hours.

**Comment by Raycoms** [comment]
I believe so. I will push it to the 1.11.2 and to curse.

2017-01-26 14:01 GMT-02:00 kreezxil <notifications@github.com>:

**Comment by Raycoms** [comment]
#484 is the same thing.
