### ISSUE TITLE
[Suggestion] Water channels/roads (like in Venice)

### ISSUE THREAD

**Issue by Cap-Salt** [ldtteam/minecolonies#5092]
Well we already have railway tracks and the normal way to walk. Is it possible to teach the colonists to use a boat? I think it's pretty hard but it would be really nice.  :D

btw how is the auto build system going?

**Comment by Raycoms** [comment]
Feature discussion please in #4535 so we got a better overview of bugs in the main issues.

We're missing some cables yet, those are expected to arrive tomorrow.


I'm still thinking about boats, but I didn't decide on it yet.

**Comment by Cap-Salt** [comment]
Just one thing pls
were can I find the git changlog? :S

**Comment by Cap-Salt** [comment]
and sry for wrong upload

**Comment by Raycoms** [comment]
https://github.com/ldtteam/minecolonies/commits/version/1.15
