### ISSUE TITLE
Wall upgrade/repair

### ISSUE THREAD

**Issue by Arbore01** [ldtteam/minecolonies#5095]
### Minecolonies version # Update to the newest minecolonies and structurize alpha first and see if your issue might be already fixed!

Version: minecolonies-1.15.2-0.11.949-universal-universal and structurize-0.10.316-ALPHA

### Expected behavior
 Ability to upgrade and repair segmented wall (**walls/medievaloak segment1**)

- 

### Actual behavior

This is how the UI looks when I just completed building a segment of the wall: https://ibb.co/LghgQNX

This is the issue that happens **after I reload the game**: 
https://ibb.co/L996DmF

### Steps to reproduce the problem

I'm not sure how to fix this :) all I know is; I'm unable to upgrade/repair the wall segment after I reload the game. Something is not being saved when I close the game...?

**Comment by Raycoms** [comment]
What version are you on, please always include this into the reports.

**Comment by DaftBugger** [comment]
Having the same issue, using the 1.15.2-0.11.949 version of Minecolonies and the 0.10.317 version of Structurize.

**Comment by Arbore01** [comment]
minecolonies-1.15.2-0.11.949-universal-universal and structurize-0.10.316-ALPHA

**Comment by Arbore01** [comment]
Awesome! has been fix! thank you for the quick fix with latest (minecolonies-1.15.2-0.11.954-universal)

**Comment by DaftBugger** [comment]
I'm now indeed able to upgrade/repair wall segments, if i input the name in creative. But now when I try to upgrade it rotates the segment.

**Comment by Arbore01** [comment]
> I'm now indeed able to upgrade/repair wall segments, if i input the name in creative. But now when I try to upgrade it rotates the segment.

I tried in survival and it works great! cant say anything about creative though

**Comment by DaftBugger** [comment]
Tried in survival and creative didn't make a diffrence.

**Comment by bastientanesie** [comment]
I still have the same issue with 1.15.2-0.11.954 as previously [reported here](https://www.reddit.com/r/Minecolonies/comments/gwhge8/enable_to_upgrade_decorationswalls/).

Although, as soon as my builder has finished building the "walls/mediavaloak/segment1", the decoration controler UI is completly empty: https://imgur.com/a/wNuvjU9

**Comment by dancofo** [comment]
I am having nearly the same issue with 1.15.2-0.11.957.  When I build fortress walls 1, I can upgrade them to 2, however once they are finished as level 2, when I go into the Decoration Controller GUI, it states that the level of the build is 1, so upgrading makes the builder come, update to level 2 (which it already is) and not change anything.  Updating to level 3 seems impossible currently.

**Comment by Arbore01** [comment]
_minecolonies-1.15.2-0.11.960-universal_ and _structurize-0.10.324-ALPHA_ has been released, see if that fixed the issue
