### ISSUE TITLE
Game crashes whenever i try to place anything

### ISSUE THREAD

**Issue by Marxanne** [ldtteam/minecolonies#5096]
### Minecolonies version # Update to the newest minecolonies and structurize alpha first and see if your issue might be already fixed!

Version: 0.10.771

### Expected behavior

- I'd expect to be able to place the Supply ship (or any other building) in a completely clear space.

### Actual behaviour

-  The game saves and then crashes

### Steps to reproduce the problem

1. Try and place a building.

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:https://gist.github.com/Marxanne/09153aa9452c80ed3b5e78e8ab38ef49

**Comment by Asherslab** [comment]
read what it says at the **very** top of your issue you just created

**Comment by Raycoms** [comment]
(update to latest alpha)
