### ISSUE TITLE
Version 0.11.349 builders hut nor builder accept clock needed for medieval oak builders hut..

### ISSUE THREAD

**Issue by DarkAmulek** [ldtteam/minecolonies#5097]
Minecolonies version 0.11.349 ALPHA

**Expected behavior**
Take a clock and and either place it in the builders hut inventory or use the second page of the interface to place in inventory. Builder's hut registers that it has the clock needed for the project. Builder takes clock from builder's hut inventory and puts it wherever it goes. Sometimes builders hut wont place in inventory via second page. It can be placed manually and be registered.

**Actual behavior**
Take a clock and attempt to place in builder's hut inventory with second page of the interface. It acts like inventory is full. Place clock in builder's hut inventory manually. Check on second page of builder's hut interface clock still not registered as in inventory. Wait for builder to need the clock similar to the builder's hut acts like the clock is not there. Attempt to fulfill the request manually, builder doesn't register that you have a clock in your inventory. Place clock in builders inventory manually, builder doesn't register clock is in it's inventory. Ask builder to try to cancel the request. takes clock from their inventory and places it in builder's hut inventory then takes the clock again, cycle repeats.

**Steps to reproduce the problem**
Builder's hut part
1. Start building a level 4 builder's hut
2.  Attempt to place a clock in builder's hut inventory via second page of the interface.
3. Profit part one
3.  Attempt to work around initial error by manually placing the clock in builder's hut.
4.  Check second page of the builder's hut interface.
5. Profit part two

Builder's part
1. Builder attempts to find clock in builder's hut inventory, generates request for clock that you placed in builder's hut inventory.
2. Attempt to fulfill request with the clock in your inventory.
3. Profit part one
4. Attempt to manually fulfill request by placing clock in to builder's inventory.
5. Profit part two

Clock inventory loop
1. Do step 4 of the builder's part.
2. Ask builder to try to cancel that request.
3. Profit
### Logs: 
No Log was generated for May 28th, 2020

**Comment by Raycoms** [comment]
already noted in #4510

**Comment by DarkAmulek** [comment]
Sorry should have looked deeper for the problem. i'll be sure to check more than just titles next time I run into an error.
