### ISSUE TITLE
Pathing

### ISSUE THREAD

**Issue by mikeskey** [ldtteam/minecolonies#510]
There seems to be some major pathing issues at times with the citizens. I would like to make a suggestion that might solve most of it if not all. Make the citizens stay to the dirt paths we are now able to create via the shovel and right clicking. It's a simple, fast and cheap way to make "roadways" for the citizens to travel on and then there wouldn't be any issues with the majority of them getting stuck where they shouldn't be. Obviously they can't be made to stay on the paths 100% of the time but just code it so the paths are their preferred route if there is a path available in the vicinity.

**Comment by forReason** [comment]
while ths is a nice Idea especially for Workers I believe it would remove some "liveliness" of the village. I think sometimes the Villagers also have to stoll around.

**Comment by Raycoms** [comment]
The thing is,  is that it isn't very easy to keep them to the paths

Am Freitag, 27. Januar 2017 schrieb Julian B. :
