### ISSUE TITLE
optifine lost blocks

### ISSUE THREAD

**Issue by map788** [ldtteam/minecolonies#5104]
Version: minecolonies-1.15.2-0.11.949-universal.jar

The problem is that some blocks are not displayed when combined with optifine

[latest.log](https://github.com/ldtteam/minecolonies/files/4703131/latest.log)
[crash-2020-05-29_19.57.25-client.txt](https://github.com/ldtteam/minecolonies/files/4703132/crash-2020-05-29_19.57.25-client.txt)
- crashlog:

**Comment by Raycoms** [comment]
You got that wrong. It's not that minecolonies has a problem. But optifine has. Please report to them.
