### ISSUE TITLE
Sandstone Barracks

### ISSUE THREAD

**Issue by Funbydeath** [ldtteam/minecolonies#5107]
### Minecolonies version # Update to the newest minecolonies and structurize alpha first and see if your issue might be already fixed!

Version: 1.12.2-0.11.811-BETA, through MC Eternal Version 1.3.5.3

### Expected behavior

- The sandstone template barracks towers should connect to the barracks itself in a certain fashion

### Actual behaviour

- Below is the photo of the towers. they seem to be rotated one 90 degree tick to many. Also, the knights themselves seem to be silly and constantly climb the ladder instead of doing anything, although I have not set patrol routes for them. 
![2020-05-29_21 52 42](https://user-images.githubusercontent.com/66151205/83318029-d4a79280-a1f6-11ea-9657-460a1c2a7050.png)
![2020-05-29_21 52 49](https://user-images.githubusercontent.com/66151205/83318031-d5d8bf80-a1f6-11ea-8ab1-27ece4ed2f31.png)
![2020-05-29_21 52 52](https://user-images.githubusercontent.com/66151205/83318033-d709ec80-a1f6-11ea-8683-17ab40504e46.png)

### Steps to reproduce the problem

1. set of a colony with the sandstone template
2. build the builders hut and level it to level 5
3. build a barracks and level it along with the 4 towers to 5
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: No crash report, just a annoying rotation issue
- crashlog:

**Comment by Raycoms** [comment]
#5006 please
