### ISSUE TITLE
Plantation worker stays at home and doesn't go to work

### ISSUE THREAD

**Issue by MatthiasMann** [ldtteam/minecolonies#5108]
Version: minecolonies-1.15.2-0.11.954-universal

### Expected behavior
The plantation worker should go to his/her work place to look 'busy' :)

### Actual behaviour
The plantation worker stays at the hous after waking up and seems to be not worker (but actually is working)

This is the output of "/mc citizen info 1 19":
ID:  19  Name:  Florence F. Cod
Citizen position: x=-2586 y=66 z=-1004
Home position: x=-2585 y=66 z=-1005
Work position: x=-2561 y=70 z=-1016
Health: 21.0 Max Health: 21.0
Athletics: 2 Dexterity: 6 Strength: 3\nAgility: 6 Stamina: 2 Mana: 2\nAdaptability: 10 Focus: 3 Creativity: 6\nKnowledge: 1 Intelligence: 8
Job: plantation
Desired activity: WORK Current Activity: START_WORKING Task: EntityAIWorkPlanter

It appears that he/she only goes to the plantation once either sugar cane has grown high enough or new one needs to be planted - eg while it is growing he/she is not going to the plantation.

### Steps to reproduce the problem
1. Have a plantation (in my case level 3 medieval oak)
2. Have a working in it living near by (~30 blocks in an alternative wooden level 2 home)
3. Watch the worker
4. ... Profit

**Comment by Raycoms** [comment]
I don't see a problem with this. Cut them some slack =P Let them hang around at home a bit =D
