### ISSUE TITLE
Feature request - clients upload schematics(nbt)

### ISSUE THREAD

**Issue by ProsperCraft** [ldtteam/minecolonies#511]
On games such as star made you can upload ship designs that you have made and saved elsewhere then provide the resources to build it in your current server.

I would love as a client on a server to be able to upload my own nbt designs and have my villagers build them.

Related - https://github.com/Minecolonies/minecolonies/issues/488

**Comment by cltnschlosser** [comment]
There are definitely some security and space concerns here, but I feel like this is something we could do. We just need to make sure we have this be in a config file and disabled by default. Also maybe byte limits per player (potentially total as well).

**Comment by xavierh** [comment]
Will be covered by #487 and #488
