### ISSUE TITLE
Colonists are not aware fire will kill them.

### ISSUE THREAD

**Issue by Giovanni-NL** [ldtteam/minecolonies#5110]
### Minecolonies version # 
Version: minecolonies-1.15.2-0.11.948-universal

### Expected behavior
Colonists being smart enough to not walk into fire. 

### Actual behaviour
The Archery 4 and 5 huts, type Fortress, have an open fire in their design.  Colonists that just wander around sometimes walk into that fire and die.  

### Steps to reproduce the problem
Build an Archery level 4 or 5, type Fortress. Let some citizens walk around in it, and watch them walk into the fire and die.

So please make colonists smarter, or alternatively, do not use structures that have open fires that can be walked into. 

### Logs: Latest.log and crashlog at https://gist.github.com/
n/a

**Comment by anakhasilver** [comment]
Going to add I SOMEHOW have had the same thing happen... In the fortress-type restaurant.

**Comment by Giovanni-NL** [comment]
Also, the Stone Smeltery has some lava flowing where citizens can walk into. Lost a Citizen to that today...  Lava should be treated the same way as fire as far as pathfinding is concerned.
