### ISSUE TITLE
Targets of the guard are displayed repeatedly in the list of the guard tower

### ISSUE THREAD

**Issue by Cap-Salt** [ldtteam/minecolonies#5112]
### Minecolonies version # Update to the newest minecolonies and structurize alpha first and see if your issue might be already fixed!

Version: minecolonies-1.15.2-0.11.954-universal

### Expected behavior

- 

### Actual behaviour

- 

[Aufnahme_2020_05_30_14_38_27_693.zip](https://github.com/ldtteam/minecolonies/files/4705622/Aufnahme_2020_05_30_14_38_27_693.zip)

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

**Comment by Asherslab** [comment]
Fill out the template properly.

**Comment by Cap-Salt** [comment]
lol sry for second Upload Von meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: AshersLab <notifications@github.com> Datum: 30.05.20  14:48  (GMT+01:00) An: ldtteam/minecolonies <minecolonies@noreply.github.com> Cc: Cap-Salt <schmelterkevin4@gmail.com>, Author <author@noreply.github.com> Betreff: Re: [ldtteam/minecolonies] Targets of the guard are displayed repeatedly in the list of the guard tower (#5112) 
Fill out the template properly.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ldtteam/minecolonies/issues/5112#issuecomment-636326485",
"url": "https://github.com/ldtteam/minecolonies/issues/5112#issuecomment-636326485",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
