### ISSUE TITLE
The targets of the guards are displayed repeatedly in the guard tower

### ISSUE THREAD

**Issue by Cap-Salt** [ldtteam/minecolonies#5113]
### Minecolonies version # Update to the newest minecolonies and structurize alpha first and see if your issue might be already fixed!

Version: minecolonies-1.15.2-0.11.954-universal

### Expected behavior

- Each mob should only be shown once in the list

### Actual behaviour

- Each mob is listed several times

[Aufnahme_2020_05_30_14_38_27_693.zip](https://github.com/ldtteam/minecolonies/files/4705646/Aufnahme_2020_05_30_14_38_27_693.zip)

### Steps to reproduce the problem

I don't know exactly how to reproduce the issue I just did this:
1. Build a guard tower at lvl 1 and assing a guard to it
2. check the list
3. if it is correctly displayed restart ur world
4. check it again

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

**Comment by Asherslab** [comment]
***same as before***
fill out the template properly

**Comment by FinnT730** [comment]
Make an good issue, or nothing will get fixed...... and NO world downloads??

Also, hi Asher!!

**Comment by Cap-Salt** [comment]
Sorry I didnt saw that u closed it

**Comment by Cap-Salt** [comment]
Finn wtf I made a good issue why should they need a world downlaod
I even recorded it
Just was confused and wanted help

**Comment by Cap-Salt** [comment]
@Asherslab I is fixed now I needed to restart the game thats it :)
sorry for the second upload I was confused because u closed it so fast :S

**Comment by Raycoms** [comment]
There is a problem there, I found it and it will be fixed with the next update.
However, please make sure to fill the issue template in completely.

**Comment by Cap-Salt** [comment]
Sorry for that

**Comment by Cap-Salt** [comment]
I trought the video would be enought

**Comment by Raycoms** [comment]
The video should be more like "if the text doesn't explain it well enough, you can download the video". I rather won't download every video that is posted here.

**Comment by Cap-Salt** [comment]
@Raycoms 
@Asherslab 
Omg I am so stiuped.....
Now I understand what u want :S

**Comment by Cap-Salt** [comment]
Sorry XD

**Comment by Cap-Salt** [comment]
I think that should be a little better but still useless because its fixed

**Comment by Cap-Salt** [comment]
Oh one is that embarrassing but anyway I won't bother you now with your good work continues so I love this mod and the support you offer us.

Sorry dudes

**Comment by Cap-Salt** [comment]
Hey it happened again. I restarted my world and now they displayed again wrong

**Comment by Raycoms** [comment]
I wrote up there that I fixed it in the next built =D

**Comment by Cap-Salt** [comment]
Well, do you know when you want to stream next time?

**Comment by Raycoms** [comment]
in around 5 hours

**Comment by Cap-Salt** [comment]
Hahaha well midnight XD

**Comment by Cap-Salt** [comment]
I will try to be there
Youtube?

**Comment by Raycoms** [comment]
https://www.twitch.tv/minecoloniesteam

**Comment by Cap-Salt** [comment]
:) thx

**Comment by FinnT730** [comment]
> Finn wtf I made a good issue why should they need a world downlaod
> I even recorded it
> Just was confused and wanted help

Yeah.... I thought it was an world download because it was in an zip...... Did not know it was an video until I opened it. My mistake. But it seems like it is resolved. So I will leave, and leave Ray and Asher be..... this is not even an project I am an part off...... :)

**Comment by Cap-Salt** [comment]
> 
> 
> > Finn wtf I made a good issue why should they need a world downlaod
> > I even recorded it
> > Just was confused and wanted help
> 
> Yeah.... I thought it was an world download because it was in an zip...... Did not know it was an video until I opened it. My mistake. But it seems like it is resolved. So I will leave, and leave Ray and Asher be..... this is not even an project I am an part off...... :)

Np dude I just didnt understand what they want :D
