### ISSUE TITLE
Deliveryman run into an issue

### ISSUE THREAD

**Issue by Cap-Salt** [ldtteam/minecolonies#5115]
### Minecolonies version # Update to the newest minecolonies and structurize alpha first and see if your issue might be already fixed!

Version: minecolonies-1.15.2-0.11.954-universal

### Expected behavior

I dont know exactly what the deliveryman should do I didnt coded him =)
but I think he should fullfill the requests and get the stuff he needs to fullfill that requests
- 

### Actual behaviour

First he only got the stuff from my fisherman and ignored that my lumberjack needed an axe,the builder needes logs ect. he did nothing other anymore.

I let him do his job and hoped he will do that other things soon and then happened that:
![2020-05-30_22 26 13](https://user-images.githubusercontent.com/62767037/83338820-31bf4900-a2c8-11ea-8005-94364ffdbc15.png)

Btw I saw the new interface in the deliveryman hut. At the beginnings of that issue it was full of pickup requests and some delivery requestes. After the issue it was completly empty and didnt filled anymore. I had to destroy the hutblock and place it again. The hut filled with requests again but the deliveryman had still that issue. 

Idk if that informations helps u but I do my best :/

- 

### Steps to reproduce the problem

Sorry Idk how to reproduce that ;-; I give u the latest log

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
[latest.log](https://github.com/ldtteam/minecolonies/files/4706486/latest.log)

Maybe thats the problem? idk:

[30Mai2020 22:24:12.947] [Server thread/ERROR] [minecolonies/]: Parent cancellation of delivery request failed! Unknown request: StandardToken{id=60bda442-a900-4683-99bf-3c1b65e5b769}
java.lang.Exception: null

That happened very often
- crashlog:

**Comment by Cap-Salt** [comment]
What was wrong?

**Comment by Raycoms** [comment]
You destroyed some buildings with requests that were not cleared from the dmans schedule.

**Comment by Cap-Salt** [comment]
Oh okay
I just destroyed the deliveryman hut because it didnt got requests anymore

**Comment by Cap-Salt** [comment]
Is the auto build system still down?

**Comment by Raycoms** [comment]
yeah, will come up today or tomorrow

**Comment by Cap-Salt** [comment]
Well I will play now and see if I find some other problems :)

**Comment by Cap-Salt** [comment]
How can I share a bigger video file with u?

**Comment by Cap-Salt** [comment]
It is a bit complecated to explain in English for me

**Comment by Cap-Salt** [comment]
I really want that u See the Problem

**Comment by Cap-Salt** [comment]
Okay forget the last messages I found the problem. I can't open a single building inventory anymore (and the demn apparently can't access it)

Should I make a new issue for that?

**Comment by Cap-Salt** [comment]
Ahhhhh my colonie is so broken helllp!!!
Idk what to do can I send u the world data?

**Comment by Raycoms** [comment]
you can do /mc colony loadbackup

**Comment by Cap-Salt** [comment]
![2020-05-31_17 24 16](https://user-images.githubusercontent.com/62767037/83356052-b612da00-a363-11ea-8d79-b867a182183f.png)

**Comment by Cap-Salt** [comment]
I am so confused
;-;

**Comment by ravenbuilder934** [comment]
did you do /loadBackup or /mc colony loadbackup?

**Comment by ravenbuilder934** [comment]
then idk

**Comment by Raycoms** [comment]
Auto complete the rest of the command....

**Comment by Cap-Salt** [comment]
I try

**Comment by Cap-Salt** [comment]
![2020-05-31_17 28 23](https://user-images.githubusercontent.com/62767037/83356125-2e799b00-a364-11ea-94d9-a3d8607cce09.png)

**Comment by Cap-Salt** [comment]
didnt works

**Comment by Raycoms** [comment]
yes, and there are no further arguments for this command?

**Comment by Cap-Salt** [comment]
I don't really want to annoy you that much

**Comment by Cap-Salt** [comment]
no

**Comment by Raycoms** [comment]
it's mc colony loadBackup colonyid (your colony id)

**Comment by Cap-Salt** [comment]
okay now I can delete the colony

**Comment by Cap-Salt** [comment]
The backup dublicated all my colonists

**Comment by Raycoms** [comment]
restart the world now, that will fix it

**Comment by Cap-Salt** [comment]
2 builders in 1 hut
2 lumberjacks in 1 hut
etc

**Comment by Cap-Salt** [comment]
okay

**Comment by Cap-Salt** [comment]
Well that worked and it looks like everything got fixed

I thank u so much for the great support
0.o

**Comment by Cap-Salt** [comment]
sry for the trouble :/
