### ISSUE TITLE
Not owner of my colony LAN

### ISSUE THREAD

**Issue by Pietinguy** [ldtteam/minecolonies#5117]
### Minecolonies version # Update to the newest minecolonies and structurize alpha first and see if your issue might be already fixed!

Version: 
minecolonies-1.12.2-0.11.804-RELEASE-universal
### Expected behavior

I would be the owner of my colony.
- 
I got on and I was no longer the owner of my colony on a LAn world with friends. My computer was not the host computer
### Actual behaviour

I am not able to do anything as if I were neutral
- 
I cannot do anything in my colony except for walk around outside the buildings, when I try to do anything else, it says 'you do not have permission to do that is this colony'

### Steps to reproduce the problem

I have no Idea what I did
1. 
2. 
3. 
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

**Comment by Raycoms** [comment]
Unfortunately we can't support LAN mode since there are many vanilla oddities which doesn't make it a proper multiplayer game. Please run a local dedicated server to play minecolonies with your friends.
