### ISSUE TITLE
Mod crashes or is unresponsive when placing structure

### ISSUE THREAD

**Issue by SangurianSoul** [ldtteam/minecolonies#5118]
Ill start by saying this is the first time ive ever tried this mod, so i may be doing something very simple and wrong, so please inform me.

Im on a brand new, superflat world, in creative. I just wanted to get the build tool out and look at some of the awesome structures.

### - Expected behavior
When placing a structure with the Building tool in creative, the structure should be placed?

### - Actual behavior
The game crashes when i hit the green check mark to place structure. (crash log attached)
[crash-2020-05-30_19.26.20-client.txt](https://github.com/ldtteam/minecolonies/files/4706806/crash-2020-05-30_19.26.20-client.txt)

### - Expected Behavior
Tried to place structure again, as above.

### - Actual behavior
I only have access to Decorations. no huts. No structure will place. Upon clicking the green check mark, it just disappears. It does not crash though.

### - EDIT
- I: I even tried going back and placing a supply camp and a supply ship using their tokens, same issue.

The only mods i have installed are Minecolonies, Structurize, Perfomant, JEI, Quark, and their dependancies. However, i tried again with only Minecolonies and Structurize, and the exact same issues happen regardless.

- II: Same issues occur even with a custom schematic. i scanned and saved a 3x3 block of stone, and the same crash/vanish occurred on the individual releases.

**Comment by SangurianSoul** [comment]
Anyone have an idea?

I cant believe i would be the only one with this issue when this is such a popular mod...

**Comment by Raycoms** [comment]
Update to the newest alphas of both structurize and minecolonies

**Comment by SangurianSoul** [comment]
Im sorry to make a fuss here, but as i stated in my original report, i already did.

I used the latest Alphas when the release didnt work


> ### Version: 1.15 Alpha
> ### - Expected Behavior
> Tried to place structure again, as above.
> 
> ### - Actual behavior
> I only have access to Decorations. no huts. No structure will place. Upon clicking the green check mark, it just disappears. It does not crash though.

**Comment by Raycoms** [comment]
Use the latest alpha of both structurize and minecolonies. The crash is due to a version mismatch.

**Comment by SangurianSoul** [comment]
Arent the most recent ones the files released on Curse 2 days ago?

Thank you, ill try again, i may have grabbed the wrong ones

**Comment by Raycoms** [comment]
yeah, those should be fine

**Comment by SangurianSoul** [comment]
Okay i got it, thank you! I had to start with the Supply Camp and work up

Is there a way in creative to simply spawn in the buildings? Just to be looked at?

**Comment by Raycoms** [comment]
yes, if you have the blocks in your inv, there is a button on the lower right in the build tool to paste them

**Comment by SangurianSoul** [comment]
Awesome! thank you!
