### ISSUE TITLE
Town hall missing from Space Wars supply camp

### ISSUE THREAD

**Issue by Xnosis** [ldtteam/minecolonies#5119]
### Version
minecolonies-1.15.2-0.11.954-universal
structurize-0.10.319-ALPHA

### Expected behavior

Town hall and building tool in chest/rack of supply camp

### Actual behaviour

No town hall or building tool in the racks/dispensers/hopppers of the Space Wars supply camp. 

### Steps to reproduce the problem

1. Craft supply camp
2. Use supply camp on ground
3. Select space wars supply camp from right-most drop down
4. Position accordingly and press green check.
5. Search the structure for town hall block

**Comment by Raycoms** [comment]
fixed in newest (release some time today)
