### ISSUE TITLE
Citizen hut not adding to colony limit and missing recipies

### ISSUE THREAD

**Issue by ghost** [ldtteam/minecolonies#512]
### Minecolonies version

minecolonies-universal-1.10.2-0.6.2452

### Expected behavior

- citizen hut to increase number of citizens
- buildings to be craftable (bakery forge quarry)

### Actual behaviour

- citizen hut does not increase number of citizens
- buildings not craftable (bakery forge quarry)

### Steps to reproduce the problem

1.build a citizen hut
2.look around anxiously
3.check watch
4.no citizen arrives (possibly due to the poor working conditions in my colony, my builder is already on a go slow ...really really slow) 

check jei bakery, forge and quarry have no recipies

**Comment by abdullamu** [comment]
I thought its bug but its not, build more huts the current 4 citizens will move there. After everyone leave the hall and live in the huts build new one so new citizens will move to the new hut,so i bulid 4 huts in the 4th one new citizen moved in so the limit increased to 5.
So basically each hut 2 citizens female and male if you have 3 males 1 female so you need 3 huts 3 for males and female will live with one of the males bulid new hut so total 4 leads to new family to move in and town hall is your the mayor to live in. 
The bakery, forge,quarry not implemented i think. I downloaded thiz mod yeaterday and i love it lot. I have modpack of 170 i left all mods and babysitting my colony. :)

Edit: sorry the male female theory is wrong i forgot that, that specific hut was level 2 so each level hold more citizen so you have to start building 5 huts level one to get extra citizen,or level up the current one to get more.

**Comment by ghost** [comment]
Ah cool, thanks. Hopefully my builder will cease his current strike and build my huts while I'm at work lol (he is chunk loaded but when I left he was just stood there)

**Comment by abdullamu** [comment]
Well make sure you supply him with everything including tools of the right level, i had him one time getting stuck when he was building level 3 town hall he want carpet when i give it to him he does nothing so i killed him another spawned took his place and life moved on.

**Comment by Raycoms** [comment]
Also since the last update you have to restart the build requests (cancel
in the townhall and restart) because we changed the folder structure.

2017-01-28 19:59 GMT-02:00 abdullamu <notifications@github.com>:

**Comment by ghost** [comment]
Didn't think the town hall could be upgraded? Didn't see the option.     
Also didn't know another would respawn... If he is still on strike when I get home I will "retire" him with haste (well a shovel). 
Thanks.

**Comment by abdullamu** [comment]
You are welcome there wiki on the official site which answer most of your question but not all.

The button to upgrade is the build the building so its the samw one just press it.
