### ISSUE TITLE
Builder being picky on tools

### ISSUE THREAD

**Issue by Buthurtgamez** [ldtteam/minecolonies#5120]
I'm playing on version forge-31.1.63. I'm playing on a Mod pack called Just Not Enough Mods 2.

Expected:
The builder uses a tool even if it's slightly damaged. (The builder is level 7 and I'm pretty sure the hut is level 2).

Actual:
The builder uses the tool a little bit and demands for another brand new tool and so I have to keep making him tools.

It all started when I had a problem assigning him to a citizen hut that a female citizen was in but for some reason, it likes to put their name down twice. He then glitched out and started walking to the Townhall lying down on his back and then it said he had an AI problem but my dumb self decided not to do anything about until now.

I'm not sure how to check the latest logs. Sorry

**Comment by Raycoms** [comment]
Please follow the template. If we don't know what version you're playing on we assume you're not on the newest where this is potentially fixed.

**Comment by Buthurtgamez** [comment]
Sorry, the version I'm playing on is forge-31.1.63

**Comment by Raycoms** [comment]
Minecolonies version?

**Comment by Buthurtgamez** [comment]
What I'm seeing is 0.11.909-ALPHA

**Comment by Raycoms** [comment]
update to the latest

**Comment by Buthurtgamez** [comment]
What is the website? And will it mess up my world and the mod pack?

**Comment by Raycoms** [comment]
https://www.curseforge.com/minecraft/mc-mods/minecolonies

and no

**Comment by Buthurtgamez** [comment]
I replaced the newest Minecolonies version and when I opened Minecraft it says "Files minecolonies-12.2-0.11.804-RELEASE-universal.jar is for an older version of Forge and cannot be loaded"

And then I either have the option to Open mods folder, Open latest.log and Proceed to main menu

**Comment by Buthurtgamez** [comment]
So you're just gonna close it even though it didn't work? Great help by the way

**Comment by Raycoms** [comment]
The issue you opened this for was fixed in the newest version. You are having incompatible versions of structurize and minecolonies. Your forge version is a bit too high atm. So you have to have a bit of patience until we upgrade to a newer forge too.

**Comment by Buthurtgamez** [comment]
Alright. Thank you
