### ISSUE TITLE
Delivery man stuck in warehouse

### ISSUE THREAD

**Issue by lebanni** [ldtteam/minecolonies#5123]
minecolonies-1.15.2-0.11.954-universal.jar
structurize-0.10.319-ALPHA.jar

Warehouse is nordic lvl 1.

Sometimes the d-man walks back and forth in front of the chest : 

https://youtu.be/EQJtNoYw2zE

Restarting the server often solve the issue.

But now, he is stuck in front of the chest.

![2020-05-31_17 22 09](https://user-images.githubusercontent.com/2799575/83356235-0ccce380-a365-11ea-8165-b06351184e6e.png)

**Comment by ravenbuilder934** [comment]
The deliveryman is supposed to do that when they have no requests from workers: https://github.com/ldtteam/minecolonies/pull/5067

**Comment by lebanni** [comment]
He has requests. Firing and hiring him again solve temporarily the issue, but he does it again after a while.

**Comment by ravenbuilder934** [comment]
then idk

**Comment by Raycoms** [comment]
Does he have requests in his list in the dman hut?

**Comment by lebanni** [comment]
No, only in the builder's request list.

**Comment by Raycoms** [comment]
And to who are these requests assigned? Do you have multiple dmen?

**Comment by lebanni** [comment]
Only 1 dman. Delivery is requested from the warehouse. Also the cook request fuel (sticks, spruce logs).

**Comment by lebanni** [comment]
The warehouse was full. I made some room. Issued a reset request. Dman is unstuck for now. Maybe shoud there be a message when the warehouse is full.
