### ISSUE TITLE
Demn gets confused when enchanted fishing rods are in the warehouse

### ISSUE THREAD

**Issue by Cap-Salt** [ldtteam/minecolonies#5125]
### Minecolonies version # Update to the newest minecolonies and structurize alpha first and see if your issue might be already fixed!

Version: minecolonies-1.15.2-0.11.954-universal

### Expected behavior

If there are unenchated rods and enchanted rods the demn should took the unenchanted (because my fisherman hut is lvl 1 so he cant use enchanted rods)
- 

### Actual behaviour

The demn is stuck in the warehouse because he tries to bring the fisher the enchanted rod but something in the request system keeps him from taking it out of the chest at all so he just stands around the chest until another request with a higher delivery prio. comes in
- 

### Steps to reproduce the problem

1. Put a fishing rod in the warehouse which is unenchanted and one that is enchanted
2.The demn will try to get the enchanted one or the unenchanted (sometimes it works I think it depends on which chests they are in)
### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

**Comment by Raycoms** [comment]
Should be fixed
