### ISSUE TITLE
Workers only show 2x2 Crafting Table

### ISSUE THREAD

**Issue by jackocallam** [ldtteam/minecolonies#5126]
Version: minecolonies-1.12.2-0.11.811-BETA-universal

### Expected behavior
A 3 x 3 Crafting grid when teaching recipes

### Actual behaviour
We only get a 2x2 grid when teaching recipies
http://prntscr.com/sr9z6w

### Steps to reproduce the problem
Attempt to teach a recipe to a worker

**Comment by Raycoms** [comment]
Only specific workers allow 3x3 grids. That's intentional

**Comment by Ampaex** [comment]
If you want to craft 3 x 3 items you will need a sawmill for example, in case of wooden items.
