### ISSUE TITLE
Sawmill overproducing, then AI issue occurs.

### ISSUE THREAD

**Issue by TRAkuma** [ldtteam/minecolonies#5128]
### Minecolonies version # Update to the newest minecolonies and structurize alpha first and see if your issue might be already fixed!

Version: minecolonies-1.15.2-0.11.948-universal.jar

### Expected behavior

The Sawmill, producing two stacks of spruce stairs for two different builder requests at the same time.

### Actual behaviour

Extra information about current running infrastructure and buildings involved in this process.
The Builders where working on University level 2 and Citizens 1.
The Sawmill level is 1. 

https://imgur.com/a/Sb9P8Pz
### Steps to reproduce the problem

Try to have two builder requests running at the same time for two full stacks of spruce stairs.

1. 
Starts the two buildings that need said Spruce Stairs.
2. 
Wait for the request while having none in the warehouse.
3. 
Problem shall arise over time.
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:https://gist.github.com/TRAkuma/7cb7dbc66ec117c3779aad97b1f1e66d
- crashlog: None.

**Comment by TRAkuma** [comment]
Apologies before hand if the issue is already solved. I just noticed that there is a update. I will update the server and clients and see if the issue arises again.

**Comment by Raycoms** [comment]
okay. Please reopen of reproducable.
