### ISSUE TITLE
Empty Racks

### ISSUE THREAD

**Issue by Pupp3tt** [ldtteam/minecolonies#5129]
Mine colonies version: 0.11.954-universal

structurize version: 0.10.319-ALPHA

forge version: 31.2.5

Minecraft version: 1.15.2

Expected behavior:
Place down supply ship/camp and grab build tool and town hall block

 Actual behavior:
When in the preview mode for either supply structure, the racks are full. However when the structure is built, all the racks are empty. I have removed all other mods to troubleshoot but nothing has changed.

![Previewed](https://user-images.githubusercontent.com/62075791/83375815-bf1c9f00-a395-11ea-901b-5c6d009aa14f.jpg)

![Built](https://user-images.githubusercontent.com/62075791/83375820-c3e15300-a395-11ea-8a9d-9131057faf8c.jpg)

Steps to reproduce the problem:
(Either in survival or creative)
(Also either on superflat or regular world type)
1. Craft or spawn in a supply structure.
2. Place in an appropriate destination.
3. Board ship and view empty racks
(Optional: Use camp preview to view filled racks and then build to view empty)

(No crash logs.)

**Comment by Raycoms** [comment]
Yes, this will be fixed in todays update. Sorry for the inconvinience.
