### ISSUE TITLE
Plantation worker should be able to produce sugar

### ISSUE THREAD

**Issue by Perlo0ung** [ldtteam/minecolonies#5131]
### Minecolonies version

Version: Head

### Expected behavior

- Plantation worker should be able to craft sugar from sugarcane, as he is also able to craft paper and books.

### Actual behaviour

- Sugar recipe is not teachable.

**Comment by McKitten** [comment]
The paper issue has been touched on by a few but I believe a new npc is required. The problem of course is what to name it; and how much of the university path is added to it (i'd rather see plantation need less and this be a next step personally).

Personally I would rather see a baker/cook create sugar than the plantation worker tho.

**Comment by Perlo0ung** [comment]
I agree with what u said.

The thing is, I dont think the plantation worker should be able to craft paper and books at all, but if he is able to do both of them, then i think he should be able craft suger too,

On an addtional note, i think its quite wierd that one has to chose what the worker plants, as there is so little space..... i think he should harvest all 3 kinds of plants.
