### ISSUE TITLE
Crash when placing Supply Camp

### ISSUE THREAD

**Issue by C0D33X** [ldtteam/minecolonies#5133]
**Version:** 
 Minecolonies: 0.10.771 Release
 Structurize: 0.10.313
 Minecraft: 1.15.2

**Issue:**

- When I click and the green button to place the Camp, my modpack crashed completly. 

### Steps to reproduce the problem

1.  Craft the Supply Camp
2.  Place the Supply Camp
3.  Click on the Green button and the modpack crash

### Logs: Latest.log and crashlog at https://gist.github.com/

- crashlog: [crash-2020-06-01_15.32.56-client.txt](https://github.com/ldtteam/minecolonies/files/4711547/crash-2020-06-01_15.32.56-client.txt)

**Comment by ravenbuilder934** [comment]
Update to the latest alpha of Minecolonies and Structurize.

**Comment by C0D33X** [comment]
Ok, I go test that.
It's a problem with the placement system of Structurize I think

**Comment by Raycoms** [comment]
Yes, you have a mismatch of both. Get the latest alpha of both and you should be fine.
