### ISSUE TITLE
minecolonies-1.15.2-0.11.956 will not work with structurize-0.10.321-ALPHA

### ISSUE THREAD

**Issue by IchigoGames** [ldtteam/minecolonies#5137]
look at pic
![Capture](https://user-images.githubusercontent.com/11888162/83470033-c6e84c00-a446-11ea-9c0b-534d22739df5.PNG)

also minecolonies-1.15.2-0.11.956-universal needs structurize-0.10.320-ALPHA and does not work with 
structurize-0.10.321-ALPHA and well you can see from pic the issue with that.

**Comment by jeridan** [comment]
Just updated and confirm this.  Cannot find a structurize-0.10.320-ALPHA to download.

**Comment by Raycoms** [comment]
fixed
