### ISSUE TITLE
[request] crystal ball

### ISSUE THREAD

**Issue by kreezxil** [ldtteam/minecolonies#514]
Craftable crystal ball. Right click on Colonist, tells you what they are thinking.

Got the latest version titled "delivered". There is a lot of standing around, not doing anything, with unfinished projects with no clue as to why they are doing it. I mean if they are break shouldn't they be sitting on the ground eating lunch or toking something?

**Comment by Raycoms** [comment]
Yeah the newest update broke current builds you have to restart them.

2017-01-28 11:53 GMT-02:00 kreezxil <notifications@github.com>:
