### ISSUE TITLE
Waypoint memory leak

### ISSUE THREAD

**Issue by someaddons** [ldtteam/minecolonies#5141]
### Minecolonies version # Update to the newest minecolonies and structurize alpha first and see if your issue might be already fixed!

Version: 

### Expected behavior

- 

### Actual behaviour

Memory leak when rendering waypoints
- 

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

**Comment by Raycoms** [comment]
should be fixed in newest
