### ISSUE TITLE
Builders Won't Build University L4

### ISSUE THREAD

**Issue by ghost** [ldtteam/minecolonies#5143]
### Minecolonies version # Update to the newest minecolonies and structurize alpha first and see if your issue might be already fixed!

Version: 1.15.2.0.11.948

### Expected behavior

-  Builder's to begin building the Fortress style University L4 after initiating the upgrade from L3.

### Actual behaviour

-  Upgrade is initiated and the build request creates successfully. Builder accepts the upgrade but only stands at the hut without doing anything. No transferring inventory or pending requests. Attempted resetting the builder and attempted on multiple builders with the same effect.

### Steps to reproduce the problem

1.  Initiate upgrade from L3 to L4
2.  Watch the builder do nothing.

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: https://gist.github.com/thebeeskneez/563179aecb0526cfdb25def6cc389184
- crashlog: Not crashing.

Thanks in advance for the help!

**Comment by Raycoms** [comment]
Please try the newest version for this first.
