### ISSUE TITLE
Texture missing for Combat Academy

### ISSUE THREAD

**Issue by AngleWyrm10** [ldtteam/minecolonies#5144]
[1.12.2-0.11.804-RELEASE]
![missingTexture](https://user-images.githubusercontent.com/55937426/83594834-19903980-a515-11ea-9a8f-f6ef6ca17112.png)

**Comment by Raycoms** [comment]
Not missing, report to optifine. Please search issues before opening a new one.

**Comment by AngleWyrm10** [comment]
> Not missing, report to optifine. 

Not using OptiFine

> Please search issues before opening a new one.

You've led by example on that point

**Comment by Raycoms** [comment]
This exists in the newest 1.12 for sure. All the hut blocks in 1.12 are working and visible. If not, another mod changes the behaviour.

Besides, as already mentioned in many issues. 1.12 is only supported for gamebreaking bugs, please update to 1.15 for fixes and new content.
