### ISSUE TITLE
third page on npc crashes game

### ISSUE THREAD

**Issue by ItzMeDB** [ldtteam/minecolonies#5146]
### Minecolonies version # Update to the newest minecolonies and structurize alpha first and see if your issue might be already fixed!
Exact version, 0.11.957 (MC1.15.2)

-->

Version: 0.11.957

### Expected behavior
 some third page about the npc like the first two when you right click them 

- 

### Actual behaviour
 the game freezes for a second, saves the world, and proceeds to crash. -

- 

### Steps to reproduce the problem

1.  create town hall 
2.  get npc to spawn 
3.  right click them 
4. ... click the arrow at the top left twice

### Logs: Latest.log and crashlog at https://gist.github.com/
 https://gist.github.com/ItzMeDB/6d86003455e1ed721ccf5178acc716d2. 
- latest.log:
- crashlog:

**Comment by Raycoms** [comment]
Always happens?

**Comment by ItzMeDB** [comment]
yes, i made sure to try multiple times, happens even if its the first thing u do in game

**Comment by Raycoms** [comment]
All your citizens?

**Comment by ItzMeDB** [comment]
it seems just to be the people who were recruited and don't have jobs yet

**Comment by Raycoms** [comment]
Yeah got it reproduced, that will be a quick fix.

**Comment by Raycoms** [comment]
Will be fixed in next uploaded version
