### ISSUE TITLE
Random crashes after updating

### ISSUE THREAD

**Issue by ZakTheFallen** [ldtteam/minecolonies#5147]
### Minecolonies version # Update to the newest minecolonies and structurize alpha first and see if your issue might be already fixed!

Before reporting: Update to the newest minecolonies alpha and see if your issue might be fixed already.
-->

Version: MineColonies 1.15.2-0.11.957 (alpha), Structurize 0.10.321-ALPHA

### Expected behavior
The game will actually run without crashing.

### Actual behaviour
After updating to the latest alpha (both Minecolonies and Structurize), the game will randomly crash to desktop with no clear cause. Both in a previous colony and in a new world will cause this crash. Nothing else in this instance changed or was updated, and the logs don't seem to give an explanation for the crash happening only at runtime, no on load.

I should specify that I'm using other mods in this instance, but they have never caused a crash when combined with MineColonies, this crash only started happening after updating MineColonies.

### Steps to reproduce the problem

1. Upgrade to latest alpha of both MineColonies and Structurize
2. Start new world
3. Randomly experience crashes, even though I haven't started a colony yet.

### Logs: Latest.log and crashlog at https://gist.github.com/
- latest.log: https://gist.github.com/ZakTheFallen/988272a649dcdb30c82775c519151abb
- crashlog: https://gist.github.com/ZakTheFallen/9b52b61e8655604f33aad835483a8cf9

**Comment by Raycoms** [comment]
both of this is latest.log, don't you have a crashlog?

**Comment by ZakTheFallen** [comment]
I had to use a log from yesterday, due to messing around with mod combinations while trying to find the cause of the crash. It only kept one log file from the previous day, I don't know why. The 'crash-report' folder also had no file for that day, likely because it crashes to desktop without showing an error.
I'll try using just MineColonies and Structurize, but the crashes are very random.

**Comment by Raycoms** [comment]
How often do those happen?

**Comment by ZakTheFallen** [comment]
Very randomly. Sometimes a few minutes, sometimes a couple hours. But it does eventually happen. The most recent crash happened while still exploring a new world and gathering resources, before even putting down the camp. 
I did just find a debug log, I didn't realize they were storied in a different zip folder. I'll edit it into my original post.

**Comment by Raycoms** [comment]
From what I can see this is not related to minecolonies. Have you tried it without as well? Since minecolonies doesn't change anything if there are no colonies at all.

**Comment by ZakTheFallen** [comment]
I'm now trying Minecolonies with only the mods used on your dev server (SuperTools, Quark, Optifine, Biomes o Plenty, JEI). After a few minutes of testing, I'm not encountering any crashes. I have a feeling it was another mod conflicting with something in MineColonies. I'm not sure why it only happened after updating MineColonies and Structurize though. 

I'll continue testing with just the mods you're using on the dev server. I agree that it doesn't look like MineColonies is involved at all with this crash, I'm just very confused on what happened.

**Comment by ZakTheFallen** [comment]
I played for a couple hours, and I don't experience any crashes now. You were absolutely correct, Ray, it was some other mod that caused the crash.

**Comment by Raycoms** [comment]
great
