### ISSUE TITLE
Stash not in list of deliveries

### ISSUE THREAD

**Issue by ravenbuilder934** [ldtteam/minecolonies#5148]
Version: 954 alpha

### Expected behavior

When a Deliveryman is picking up things from a stash, the pickup should show on the second page of the Deliveryman's Hut.

### Actual behavior

It doesn't show up. It might just be that I didn't look soon enough though.

### Steps to reproduce the problem

1. Place a stash block
2. Create a pickup request by putting something in it
3. Look at the second page of the Deliveryman's Hut
4. ... Profit

Note: I only have one Deliveryman, so I wasn't looking at the wrong hut.

**Comment by JiaYow** [comment]
Confirmed, neither the Stash nor the Postbox cause the Deliveryman's hut to serializeToView().
Maybe markDirty() needs to be added here or there, but I've too little experience with that. One of the main devs will know what to do ^-^

**Comment by ravenbuilder934** [comment]
For some reason, it works now in alpha 957 and I can see both postbox and stash. Closing this
