### ISSUE TITLE
I lost my town hall. 

### ISSUE THREAD

**Issue by RobinGoodfellow88** [ldtteam/minecolonies#515]
Minecolonies curse version 1.1.1

### Expected behavior

Some way to make a new town hall block or be able to place a new supply ship.

### Actual behaviour

I accidentally destroyed my town hall block and have NO WAY TO REPLACE IT.
It would be nice to be able to make a replacement for my town hall, or to maybe make more than 1 colony, but NO. I am stuck with no way to fix shit and will have to make a new world if I want to play the mod. 

### Steps to reproduce the problem

1. Place town hall block.
2. Destroy town hall block.
3. spend 6 - 8 hours trying to figure out how to get a new one through normal means or by cheating and find FUCKING NOTHING!!!
4. Not want to play mod and want to tell others not to bother.

**Comment by Raycoms** [comment]
If you're in single player without cheats -> go into lan mode and obtain it
with cheats. Else just obtain it with cheasts.
Multiple colonies for 1 player would be problematic.

2017-01-28 16:19 GMT-02:00 RobinGoodfellow88 <notifications@github.com>:

**Comment by emanuele246gi** [comment]
Can you be more specific, this happened to me too and I don't remember the block where I placed and now my builder doesn't want to rebuild it anywhere else

**Comment by emanuele246gi** [comment]
no problem, i solved it
