### ISSUE TITLE
Suggestion forge

### ISSUE THREAD

**Issue by abdullamu** [ldtteam/minecolonies#516]
Hello
I would like to suggest something for the forge building , it would be really nice if you make tinkers constract auto detect and if its detected you have the forge building inside is tinkers smeltery and tables and the smith craft you weapons or player can use it or smith ore doubling so its nice start up smeltery or ore doubling mechanics.and without tinkers its just ore doubling building where deliveryman takes for from miner and ore doubling them in forge.

**Comment by Raycoms** [comment]
We're actually planning on a building with worker for that in the future.

2017-01-28 20:11 GMT-02:00 abdullamu <notifications@github.com>:

**Comment by Raycoms** [comment]
For the time being just scan in a forge and use it with the scan build tool
as a decoration.

2017-01-28 20:13 GMT-02:00 Ray Neiheiser <ray.neiheiser@gmail.com>:
