### ISSUE TITLE
[Suggestion] Allow stonemason to craft flower pot recipe

### ISSUE THREAD

**Issue by sweg4552** [ldtteam/minecolonies#5161]
Version:  minecolonies-1.15.2-0.11.957-universal.jar

### Expected behavior

Allow stonemason to craft flower pot recipe from three bricks.
only one brick less than the brick block recipe.
useful as there are some blueprints with a lot of flower pots
Still seems relevant to his job

### Actual behavior

cannot currently teach stonemason flower pot recipe, 

1. Allow stonemason to delve into pottery
2. Get flower pots
3. ... Profit

**Comment by PowerSchill** [comment]
https://github.com/ldtteam/minecolonies/pull/5058 enables this functionality.
