### ISSUE TITLE
Create Inventory Scroll

### ISSUE THREAD

**Issue by PowerSchill** [ldtteam/minecolonies#5163]
# Inventory Scroll Requirements

## Story

*As a* minecolonies user
*I want to* be able to remotely view an inventory of my warehouse
*So that* I am able to make gameplay decisions based on my current inventory.

## Acceptance Criteria

*Given* a colony officer
*When* they shift right click a new inventory scroll on the warehouse
*Then* it will be activated for the colony

*Given* a colony officer
*When* they shift right click an initialized inventory scroll on the warehouse
*Then* it will obtain a current inventory of the colony's warehouse

## Additional Notes

* The Inventory Scroll will present a list of all items in the warehouse's inventory along with the total quantity.
* A fuzzy search will be located on the form to filter the list of items displayed.
* The list of items can be sorted by either name or quantity in either ascending or descending order.
* The inventory list will be static until updated by shift right clicking on the warehouse.

**Comment by ravenbuilder934** [comment]
Why did you close this?
