### ISSUE TITLE
Guards do not move out of guard tower once fired

### ISSUE THREAD

**Issue by GIDustin** [ldtteam/minecolonies#5164]
### Minecolonies version

Version:  minecolonies-1.15.2-0.11.957-universal   structurize-0.10.321-ALPHA

### Expected behavior
- Once a citizen is assigned to a guard position, and their "bed" is set to that guard tower or barracks tower, and then you fire them, you should then be able to assign them to a regular house.

### Actual behaviour
- Once a citizen is a guard, they have permanent residence at that guard tower for the remainder of their life.  Even if you fire them as a guard, hire a replacement at the guard tower, and hire them at a normal building, they do not "move" to a regular house.  You cannot assign them a regular house manually as they do not appear on the list to assign.

### Steps to reproduce the problem

1. Start colony.  Let 4 citizens move in.
2. Cheat in guard tower.  Let a citizen auto-assign to the guard tower as a guard
3. Wait for guard to fall asleep, and smack him.  This step is not technically required for this bug report
4. Turn on manual work assignment, fire guard.  You should now have 4 unemployed homeless citizens, one of which is a former guard.
5. "Cheat" in a level 4 house.  Notice that only 3 of the citizens will live there.  The former guard will return to the guard tower each night to sleep even though he is not a guard anymore.
6. Hire and Fire each citizen from the guard tower in sequence so that each one gets a chance to be the guard for a few seconds.
7. House will now be empty.  All 4 citizens sleep in the guard tower since they, at some point in their life, had worked there, even though they do not anymore.

**Comment by GIDustin** [comment]
After some more testing, it appears that this behavior does not persist through a server restart.  After restarting my server, my citizens realized that they weren't guards anymore and decided to move into a house.  Should probably still be addressed though

**Comment by ravenbuilder934** [comment]
This happened to me too. After a few in-game days, they were available for a house, though.

**Comment by teagan75** [comment]
I have an opposite issue. One of my citizens was assigned to a house and then became a guard. She never leaves the house even with a restart.
