### ISSUE TITLE
Wrong spawn of pirate ship

### ISSUE THREAD

**Issue by lebanni** [ldtteam/minecolonies#5167]
minecolonies-1.15.2-0.11.957-universal.jar
structurize-0.10.321-ALPHA.jar

Pirates spawners spawn without ship on river. There is no ocean biome near this location.

![2020-06-07_01 18 34](https://user-images.githubusercontent.com/2799575/83956406-06a39f00-a85e-11ea-952b-de23a7083888.png)

**Comment by Raycoms** [comment]
Will be fixed in next release. Has been fixed in last PR.
