### ISSUE TITLE
Decoration controller replaces "path to file" content when scanning

### ISSUE THREAD

**Issue by carlansor** [ldtteam/minecolonies#5168]
###Minecolonies version # 

Version: 
minecolonies-1.15.2-0.11.957-universal
structurize-0.10.321-ALPHA

### Expected behavior

-Make a upgradeable decoration
-Scan it via command block with /scan command
-Be able to upgrade the deco

### Actual behaviour

-Make the decoration
-Scan it via command block with /scan command
-The "path to file" text gets replaced with the schematic name followed with the lvl. example:
              -the pathfile that should stay as "schematics/walls/medievaloak/corner" gets replaced with      "corner1" after the scan. This prevents players to be able to upgrade the decoration.

**Comment by carlansor** [comment]
This issue persist only using command blocks in minecolonies-1.15.2-0.11.961-universal. Using the scan tool seems to work.

**Comment by lunadragnstar** [comment]
Can we please make this so that it saves the name in the block, or something, so we don't have to worry about filling out a path or something on the deco controller itself, because if the path changes, that just makes it a hassle to update.

**Comment by Raycoms** [comment]
Not really, no
