### ISSUE TITLE
Minecolonies Alpha 11.95.7 Colonist reports AI issue request I submit latest.log

### ISSUE THREAD

**Issue by Mystara0001** [ldtteam/minecolonies#5169]
### Minecolonies version # Update to the newest minecolonies and structurize alpha first and see if your issue might be already fixed!

Version: Alpha 11.95.7

- 
Our Sawmill worker is reporting an AI issue and requested we submit our latest.log, so here it is.

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: https://gist.github.com/Mystara0001/ae6073e72919ab52c13da5d93f13d159
- crashlog: NA

**Comment by Raycoms** [comment]
Will be fixed in the next release.
