### ISSUE TITLE
Placeholder recipe is broken

### ISSUE THREAD

**Issue by bloodyraoul** [ldtteam/minecolonies#5170]
Version: 

minecolonies-1.15.2-0.11.957-universal.jar

I cannot craft placeholder blocks needed for some level 5 buildings
If I try to craft them it craft solid placeholder block instead

**Comment by Raycoms** [comment]
You shouldn't need those. Will be fixed in next version tomorrow

**Comment by bloodyraoul** [comment]
Builder is still waiting placeholders in version minecolonies-0.13.9-ALPHA-universal.jar
I dont know if it is intended
but now i can craft them
![2020-07-01_00 23 18](https://user-images.githubusercontent.com/16031618/86183177-bb656f00-bb31-11ea-9962-d27a48d98877.png)

**Comment by lunadragnstar** [comment]
builder doesn't actually place, placeholder blocks, what style are you using, dwarven?

**Comment by bloodyraoul** [comment]
Yes, dwarven style

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
