### ISSUE TITLE
Miner and Lumberjack store collected materials in non-existent chest/rack; Miner complains of full non-existent chest.

### ISSUE THREAD

**Issue by TOAST7312** [ldtteam/minecolonies#5171]
Version: 1.15.2-0.11.957

### Expected behavior

Miners would retrieve items from and store items in the mining hut block as normal. Lumberjack would store items in the hut block or rack as normal and retrieve items from these sources.

### Actual behaviour

The Miner and Lumberjack store excess items from their inventory somewhere that is not the mining hut block or any known rack/chest in the building. The Miner seems to think there is a proper storage container, and will complain when it gets 'too full'. The Lumberjack will continually store logs in the invisible with no perceivable limit. The two hut designs are the Medieval Spruce Alternative Mine, and Nordic Lumberjack. The issue has occurred at levels 1 and 2 of both buildings, and I haven't been able to progress further due to resource constraints. This issue is not occurring with other players on our server, only with me. The issue began after a skeleton killed a lumberjack and the lumberjack was replaced with a new one, though I doubt that has any relation. I should note that the first time I was able to 'fix' the issue and get the wood fro mteh lumberjack block by breaking it. When I broke the hut block, all the items exploded out of it like they'd been stored there.

UPDATE: I broke the miner hut block and all the saved materials exploded out of it just like the previous lumberjack. Strangely, I couldn't move into the space where the miner hut block use to be - it was glitchy like when you try to stand on a block that's still there that your client is saying is gone. I couldn't find the miner hut block in my inventory but it was gone. I attempted to place a block where the old hut block was, then the hut block appeared again but gave the error "This block is missing its respective building, try restarting or loading a backup!"

UPDATE 2: The miner is still here despite there being no miner hut block, still mining. I'mnot sure what to do. I'd be willing to let someone on the server to see if needed.

### Steps to reproduce the problem
I'm honestly not certain. I built the first Lumberjack and it worked for the first drop-off of wood before it was killed and replaced by a new lumberjack, who started storing items in the non-existent chest.

- latest.log: https://gist.github.com/TOAST7312/2a5e1abffbc297a37aef29efbf0d977a
- crashlog: No crash

**Comment by Asherslab** [comment]
> **_Logs: Latest.log and crashlog at https://gist.github.com/_**

**Comment by Raycoms** [comment]
Is the world really big, like too big to send to us?

**Comment by TOAST7312** [comment]
The world is a group server which I'm not running. I will ask them for the world files to share here.

**Comment by Raycoms** [comment]
That'd be nice

**Comment by TOAST7312** [comment]
I acquired the world file, but its roughly 600mb; bigger than the 10MB that this site will let me upload. Any preference in sites for me to upload it to for you guy?

**Comment by TOAST7312** [comment]
Below I've provided a link to the world and the modpack used to play on that world. This instance of the world file is from before I broke the mining/lumberjack hut blocks as mentioned in the OP. I run the pack using Twitch; when you try to log on it will give you incompatible FML modded server, but you should be able to get into the world anyway. My colony is at the below coordinates (I recommend TPing there). 

Coords:  x: 75, Z: -2255, y: 68
Link: https://drive.google.com/drive/folders/1pr9ZFAkGx17grqLmGVEizjX8gEUDc4DG?usp=sharing

**Comment by Octofoxy** [comment]
Hello! I'd like to say that I'm having the same problem. The lumberjacks chest has a missing texture, and all wood she tries to store in it never actually appears in the huts inventory. Playing on 1.15.2 too.

**Comment by Raycoms** [comment]
The missing texture is an optifine bug, please report it to them. The wood you'll find in the racks of the building.

**Comment by TOAST7312** [comment]
It should be noted that I'm still having the same issues. Our server has since update to minecolonies-1.15.2-0.11.960-universal, and even thought I'm using the Nordic lumberjack at level 3 which has many racks, they still don't store logs in them.

**Comment by Raycoms** [comment]
there are sometimes some hidden racks and chests, are you sure you checked all of them?

**Comment by TOAST7312** [comment]
> there are sometimes some hidden racks and chests, are you sure you checked all of them?

I suppose I wouldn't know where to find hidden racks. I would think the building would be designed not just for aesthetics, but also for practical use. Does the Nordic design have hidden racks? Where would they be if not inside the tent-like building? Underground?

**Comment by Raycoms** [comment]
Not really hidden, but not as obvious as you'd think. Around the corner somewhere or so.

**Comment by Octofoxy** [comment]
@Raycoms

Neither MedievalSpruce Lumberjack lvl 1 nor MedievalSpruce Farm lvl 1 have any hidden racks where the collected resources could be hidden. Both the farmer and the lumberjack are walking to their respective hut chests with a full inventory, and return with an empty inventory. However, the hut chests inventory appears to remain empty. Only when I destroy the chests, all the contents pop out. 

This means that I can only collect the Lumberjacks wood and the farmers wheat by destroying their plot chest. However after doing that, I have to rebuild the whole plot, since the builder does not recognize that the plot itself is still intact after replacing the chest.

So the bug seems to be real.

**Comment by Raycoms** [comment]
a) can you send me this world
b) You can extract it with a hopper too then.

**Comment by Raycoms** [comment]
(I can't reproduce this)

**Comment by TOAST7312** [comment]
As of using minecolonies-0.13.8-ALPHA-universal.jar, I no longer seem to be having this issue. Lumberjack seems to be working fine now?
