### ISSUE TITLE
Minecolonies Citizen Cap Not Growing

### ISSUE THREAD

**Issue by JimmyB97** [ldtteam/minecolonies#5172]
Version:  0.11.938-BETA-universal.jar

### Expected behavior
I have 7 level 3 houses, 2 level 2 houses, 2 level 1 houses and 1 level 4 house
I'd assume my citizen cap should be 31

### Actual behaviour
my current citizen cap has sat at 25 for a while even after building new houses, cap wont increase and so im not having any new babies spawn even with a male and female living in the same home

### Steps to reproduce the problem

Not sure how to reproduce as the citizen cap just stopped increasing after the first 6 houses finished building

Not sure if I just keep building more houses and hope for the best or is it something wrong with my saved game?

**Comment by MatthiasMann** [comment]
You can research +25 and +50 citizen cap in the university.

**Comment by JimmyB97** [comment]
> You can research +25 and +50 citizen cap in the university.

Just rechecked the university, haha im a numpty for not realizing that
Thank you
