### ISSUE TITLE
My mine is broken

### ISSUE THREAD

**Issue by bloodyraoul** [ldtteam/minecolonies#5173]
Version: minecolonies-1.15.2-0.11.957-universal.jar

My mine was level 4 dwarnen model
I have wanted to upgrade it to level 5 but it seems to have been rotated from level 4 to level 5 (maybe due to change minecolonies version).
So i have wanted to reposition building before upgrade to level 5 to not build over my other buildings.
After reposition it, i can upgrade to level 5
but it seems my miner don't jnow anymore where is the mine and no level appears anymore.
how can I fix it ? the only way is the destroy the mine and build a new ?
![2020-06-08_10 33 32](https://user-images.githubusercontent.com/16031618/84010134-858afb80-a974-11ea-9978-eabe8f50045a.png)
![2020-06-08_10 33 21](https://user-images.githubusercontent.com/16031618/84010140-8754bf00-a974-11ea-94ca-ad458a155533.png)
![2020-06-08_10 33 29](https://user-images.githubusercontent.com/16031618/84010144-87ed5580-a974-11ea-9b01-bc6fcc555549.png)

**Comment by Raycoms** [comment]
Okay, this is unfortunate.
@lunadragnstar this seems to be a schematic issue.

Unfortunately you can't reposition a miner without him losing all the shaft information as of now.

We will look into fixing the schematic problem though.
What you can try is do the loadback command, to load your oclony from backup to fix this.

**Comment by Raycoms** [comment]
#5006 are for schematic issues, that's why closed already.

**Comment by bloodyraoul** [comment]
Ok to lose shaft info, but why the miner dont try to dig again to the same place ?

**Comment by Raycoms** [comment]
Because there is a ladder all the way down already and they don't know the side shaft positions atm.

**Comment by lunadragnstar** [comment]
There isn't anything wrong with the schematic that I can see.

**Comment by Raycoms** [comment]
Might've been due to the version upgrade
