### ISSUE TITLE
Clipboard has fulfill button

### ISSUE THREAD

**Issue by PowerSchill** [ldtteam/minecolonies#5174]
### Minecolonies version # Update to the newest minecolonies and structurize alpha first and see if your issue might be already fixed!

Version: 

### Expected behavior

- 

### Actual behaviour

- 

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

**Comment by Raycoms** [comment]
Does the clipboard display this?
