### ISSUE TITLE
Plantation only checks for pure water - should also accept sea weed / corals / pickles

### ISSUE THREAD

**Issue by MatthiasMann** [ldtteam/minecolonies#5178]
The current medieval oak schematic of the plantation (the one distributed as separate download) uses decorated water blocks which prevent the plantation working from using all spots.

https://github.com/ldtteam/minecolonies/blob/2c8a5afbdff8bb50b0de568fb38e95fce2c6bc92/src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingPlantation.java#L169

Would be nice to extend the check to all water logged blocks.

**Comment by Raycoms** [comment]
#4535
