### ISSUE TITLE
Deliveryman hired, goes to warehouse, immediately gives error

### ISSUE THREAD

**Issue by TOAST7312** [ldtteam/minecolonies#5179]
Version: 1.15.2-0.11.957 ALPHA - newest version listed on Twitch

### Expected behavior

Hire deliveryman; begin working as deliveryman.

### Actual behaviour

Hired deliveryman. Deliveryman walked over to the warehouse and directly to the warehouse block. Symbol appeared above their head indicating an issue. Upon talking to them, the below message (link) came up:

### Steps to reproduce the problem
I'm not sure how to reproduce this ,but the latest.log provided some detail into what happened. that I don't understand.

The world (a server) I'm on has had multiple issues regarding this, one of which I've already posted here. This issue takes place on the same world as the following issue. A link to the mod pack and world file are provided there:
https://github.com/ldtteam/minecolonies/issues/5171

1. Hire deliveryman
2. See if they work?

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: https://gist.github.com/TOAST7312/6688379138413abc7f21fa2dcbfa7f57
- crashlog: None

**Comment by Raycoms** [comment]
Should't happen in newest
