### ISSUE TITLE
Game CTD After Placing Any Supply Camp

### ISSUE THREAD

**Issue by PumpkinKing72** [ldtteam/minecolonies#5181]
### Minecolonies version # 0.10.771-RELEASE-universal.jar
This is the latest Alpha!
-->

### Expected behavior
I would like to be able to place the supply camp and actually play the mod Minecolonies.

### Actual behaviour

As soon as the Supply camp is placed Minecraft Crashes to Desktop! Updating to the Latest Alpha Raycoms does not solve the problem as under as in issue #4898 stated by NoopSloop quoted under the version section that he/she was using is the latest version of the Alpha so telling them to updating to the latest Alpha I would guess didn't help them either. Is there known compatibility issues with other mods?

### Steps to reproduce the problem
Creating the SupplyCamp Chest goes fine as soon as you try to finalise the placement Minecraft Crashes.

1. Create 5 chests
2. Use the 5 Chests to create SupplyCamp Chest
3. Right click flat area to place the SupplyCamp Chest
4. Pick any camp options at all Doesn't matter
5. click the green checkmark box to place it and CTD

### Logs: Latest.log and crashlog at https://gist.github.com/
[latest.log](https://github.com/ldtteam/minecolonies/files/4749130/latest.log)

Thank you.

**Comment by someaddons** [comment]
Update minecolonies and structurize, 771 is quite old
