### ISSUE TITLE
Can't handle Builder Request/ Access inventory

### ISSUE THREAD

**Issue by xenocide12** [ldtteam/minecolonies#5182]
### Minecolonies version # 1.12.2-0.11.841-ALPHA 

Version: 1.12.2

### Expected behavior

- 
Expected to be able to fulfill builders request for a new shovel.  Expected to be able to access the NPC's inventory to be able to fulfill this request.  Expected lumberjacks hut to finish upon build completion.  Expected lumberjack construction progress to be displayed properly from builder's hut 
### Actual behaviour

- 
Builder NPC has permanent request notification.  Cannot access NPC request screen. Cannot access NPC Inventory.  Lumberjack is physically constructed, yet not recognized as finished.  Lumberjack construction progress is displayed at 0 percent  

### Steps to reproduce the problem

1.   Upgrade builder's hut to level 2
2.  Request build order on dark oak Lumberjack
3.  Wait for NPC's wooden shovel to break
4.  Toss two wooden shovels at npc's feet
5.  Toss iron shovel at npc's feet
6.  Take out wooden slabs from Builder's rack during Lumberjack construction.  Place slabs back later.

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: https://gist.github.com/xenocide12/84bae335c01a64ed8017eddd87fd3674#file-minecraft-log-6-8-2020-xenocide12
- crashlog: N/A

**Comment by Raycoms** [comment]
Did you try relogging, and recalling?
