### ISSUE TITLE
Game CTD After Placing Any Supply Camp #5181

### ISSUE THREAD

**Issue by PumpkinKing72** [ldtteam/minecolonies#5184]
Same issue as before.
You say 771 is quite old that is the latest version from https://www.curseforge.com/minecraft/mc-mods/minecolonies 
Where does one get the latest download then. I tried going to the download page directly from the MineColonies Official website and that brings one to a download link even older https://www.curseforge.com/minecraft/modpacks/minecolonies-testpack.

So where is the magical new version located?

Also perhaps resolving issues before closing an incident would be an idea maybe even give the poster of the issue time to respond would be a good idea.

I also removed the mods as a factor the only mod I tested this with is JEI. 

So I would love to know where to get the latest versions of minecolonies and structurize if it is not from https://www.curseforge.com/?

**Comment by Raycoms** [comment]
It's the latest RELEASE but not the latest version. Please download the latest alpha. You are having a mismatch of structurize + minecolonies (too new structurize, too old minecolonies)

**Comment by PumpkinKing72** [comment]
I tried the minecolonies-0.11.938-BETA-universal.jar as well and Minecraft says it is not a valid mod so where do I find the latest alpha?

**Comment by Raycoms** [comment]
click on "all files" on curse
