### ISSUE TITLE
Worker levels higher than maximum allowed 

### ISSUE THREAD

**Issue by cozyducking** [ldtteam/minecolonies#5186]
Version: 
minecolonies-1.15.2-0.11.958-universal
structurize-0.10.322-ALPHA

### Expected behavior

**Maximum** worker level is tied to the workers assigned citizen hut, regardless of stats.

### Actual behaviour
Workers with high stats when assigned a job immediately have high worker level. 
Regardless of the them being in the tavern (level 1 tavern) or level 1 citizen house. 

Started colony -> built builder -> built tavern -> built citizen hut -> used recruit 2 citizens using diamonds and they thus had very high stats -> assigned them to work-> immediately had 11/14 in worker level despite having no houses -> later on one had a lvl 1 house, one had a tavern spot.

https://i.imgur.com/cIIxSht.png - Level 14 Lives in tavern (level 1)
https://i.imgur.com/TzO3BCV.png - Level 11 Lives in citizen house (level 1)

### Steps to reproduce the problem

1. Spawn townhall 

2. Disable and set to manual for:
''automatic work assignments''-> manual
''automatic home assigments'' -> manual
''let citizens move in'' -> disable

3. Build tavern + house
4. Recruit high stat citizens through ''citizen recruitment button''
5. Assign work
6. Check level

**Comment by Raycoms** [comment]
What's the problem with this?

**Comment by cozyducking** [comment]
I forgot to add that I specify this problem as I am reading the git.hub minecolonies wiki, I am the one who posted it in reddit with the 'possible' bug as I didn't know if I am misinterpreting the wiki.

From the wiki https://ldtteam.github.io/MinecoloniesWiki/source/systems/worker
''**here is a system in place for how the workers skills “Level Up”. The level of their HOME is what will put a limit on the “Worker Skill Level” they can achieve. Every time you level up their HOME, the worker’s max level limit will be DOUBLE the previous limit! Currently the limit on the Workers’ “Skill Level” is 100 (once you have made his building level 5, of course). The level of their WORK building determines the speed at which they level up.**''

> What's the problem with this?

So my understanding is that my workers shouldn't be able to have a higher worker level then the corresponding hut as according to the wiki. So for example my worker with a lvl 1 hut should only be able to reach worker level 4.

From wiki
Building Level | Max Worker Level
-- | --
0 | 2
1 | 4


As mentioned I may be wrong in this bug-reporting, I am only currently seeing it as a bug in that to me it seems as my workers are way higher level then they should be able to.

**Comment by Raycoms** [comment]
No, it's not that they can't have a higher level. It means they won't level up over these levels naturally unless the conditions are met. It's not a "hard cap".
