### ISSUE TITLE
Cook not working because of 'missing items'

### ISSUE THREAD

**Issue by ravenbuilder934** [ldtteam/minecolonies#5187]
### Expected behavior

The cook not complaining about 'missing items' when he has no requests.

### Actual behavior

The cook asks for 'missing items,' even though he has no requests, plenty of food, and lots of fuel. He has stopped working because of it.

![2020-06-08_15 22 58](https://user-images.githubusercontent.com/63612548/84158040-07405f00-aa31-11ea-9c98-572f84358d2a.png)

### Steps to reproduce the problem

No idea. It just started happening, when before he had been working fine.

**Comment by Raycoms** [comment]
Is this still happening? Or did it solve itself?

**Comment by ravenbuilder934** [comment]
I will check.

**Comment by ravenbuilder934** [comment]
Now he says that he's been unable to work for more than two weeks already.

![2020-06-13_10 11 37](https://user-images.githubusercontent.com/63612548/84572239-5acae980-ad5e-11ea-8c91-e1d14187d50a.png)

**Comment by Raycoms** [comment]
Can you send me this world?

**Comment by ravenbuilder934** [comment]
I will try, but I have never done it before

**Comment by ravenbuilder934** [comment]
[myworld.zip](https://github.com/ldtteam/minecolonies/files/4774903/myworld.zip)

Like that? Is that the right file?

**Comment by Raycoms** [comment]
yes

Am Sa., 13. Juni 2020 um 16:56 Uhr schrieb ravenbuilder934 <
notifications@github.com>:

**Comment by Raycoms** [comment]
Okay I double checked. It's because you have to let it get night and then day again for this to reset =)

**Comment by ravenbuilder934** [comment]
I did, and he still says it. (He went to sleep.)

**Comment by Raycoms** [comment]
Weird, I opened it, did the same thing, and it got reset =D

**Comment by ravenbuilder934** [comment]
I restarted him and fired then rehired him, and he still says it.

**Comment by Raycoms** [comment]
Restarting doesn't fix this, regular night arriving, and happiness recalculating should fix it. I did time set night, and then afterwards time set day and it reset after a few seconds.

**Comment by ravenbuilder934** [comment]
I will try setting it to night using commands.

**Comment by ravenbuilder934** [comment]
Didn't work

**Comment by Raycoms** [comment]
That's weird

**Comment by ravenbuilder934** [comment]
very

**Comment by ravenbuilder934** [comment]
Now, for some reason, it's fixed.

**Comment by ravenbuilder934** [comment]
It's still not fixed. Can you reopen this?

**Comment by ravenbuilder934** [comment]
Never mind, I used a command to reload him and he stopped.

**Comment by ravenbuilder934** [comment]
Now he's saying it again...

**Comment by ravenbuilder934** [comment]
It looks like he's stuck in START_WORKING.

**Comment by ravenbuilder934** [comment]
His task is OpenDoorGoal, and it's been like that for a while...he's just walking back and forth, opening and closing a door.

**Comment by ravenbuilder934** [comment]
Now he switched his task to EntityAIWorkCook, then to LookAtGoal, then to OpenDoorGoal, and back and forth.

**Comment by ravenbuilder934** [comment]
He has open requests, though, and leveled up while he was still saying it.
