### ISSUE TITLE
Builder placing.... Villagers

### ISSUE THREAD

**Issue by Warrof** [ldtteam/minecolonies#519]
### Minecolonies version

version 6.1

### Expected behavior

- Not placing Villagers

### Actual behaviour

- Places a handful of villagers from a Scan

### Steps to reproduce the problem

1. Build somthing and spawn villagers into it
2. Scan that something.
3 Build the Scan using the builder and Build tool on Infinite Resources
![2017-01-28 1](https://cloud.githubusercontent.com/assets/21962742/22402104/120c2fd0-e5a0-11e6-998d-c79b8ee9b6c8.png)

**Comment by Raycoms** [comment]
Did the citizen die?

2017-01-29 3:20 GMT-02:00 Warrof <notifications@github.com>:

**Comment by Warrof** [comment]
I assume you mean the builder?  No She did not.

As for the villagers themselves. Only 4 were placed out of what should have been 14.

**Comment by Raycoms** [comment]
Okay I don't understand what the problem is?

VIllagers aren't spawning and the builder isn't placing?

2017-01-29 13:34 GMT-02:00 Warrof <notifications@github.com>:

**Comment by Warrof** [comment]
The Builder is placing Villagers.  I assume that is NOT supposed to happen?  

I scanned in a build that had some villagers held in it (14 villagers exactly)  When I had the builder build that build, she actually spawned in Villagers.

Meaning that the villagers somehow became a required part of the build according to the code.

**Comment by marvin-bitterlich** [comment]
Well we actually have worked hard to spawn entities that are scanned in. Like item Frames for example. So if you scan in a zombie, there will be a zombie coming out.

**Comment by Raycoms** [comment]
I'm glad it's working accordingly.
Definitively not a bug =D

**Comment by Warrof** [comment]
Then i should add that only 4 of the 14 villagers were spawned in.
