### ISSUE TITLE
Barabarian Texture is violet/black

### ISSUE THREAD

**Issue by Richardk2n** [ldtteam/minecolonies#5190]
### Minecolonies version # Update to the newest minecolonies and structurize alpha first and see if your issue might be already fixed!

Version: minecolonies-1.15.2-0.11.958-universal

### Expected behavior

- Working textures

### Actual behaviour

- Broken Barbarian texture

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

**Comment by Richardk2n** [comment]
raid was already in prograss before the update from 957

**Comment by Raycoms** [comment]
Fixed with #5175
