### ISSUE TITLE
Crash while starting up the new ALPHA 1.15.2

### ISSUE THREAD

**Issue by Inomutso** [ldtteam/minecolonies#5191]
- 

### Actual behaviour

Crash while starting up

### Steps to reproduce the problem

Hi Team

Today i tried to use the new Alphas

minecolonies-1.15.2-0.11.958-universal.jar
structurize-0.10.322-ALPHA.jar
with Forge 1.15.2-forge-31.2.0

With them I could not even startup, it crashes already while starting up in the MC Launcher
I tried to switch back to Forge forge-31.1.0.. but the new Alphas  won´t run with Forge forge-31.1.0

I see this in the Log and cannot remember, if we had an Issue before in this Folder "Failed to load class com.ldtteam.structurize.Structurize"

[09Jun2020 18:20:59.291] [Render thread/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to load class com.ldtteam.structurize.Structurize

So I went back to Minecolonies-1.15.2-0.11.957-universal.jar Structurize-0.10.321-ALPHA.jar with Forge forge-31.2.0 in my MC Profile and that work´s

Hope you can see more in the Log´s

best regards

Inomutso

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

https://gist.github.com/Inomutso/541980d754467e899688d66ef6552ece

**Comment by Raycoms** [comment]
You'll need 31.2.8 forge.
