### ISSUE TITLE
Doc Request: Worker Level

### ISSUE THREAD

**Issue by Geoffrotism** [ldtteam/minecolonies#5192]
I scoured the docs looking for what worker levels do and it is only briefly mentioned on the tutorial page. It would be great if an explanation of what worker levels do/benefits was added to the Systems > Worker System part of the Wiki.

**Comment by ravenbuilder934** [comment]
Please make an issue here: https://github.com/ldtteam/MinecoloniesWiki/issues

**Comment by Geoffrotism** [comment]
done
