### ISSUE TITLE
Miner leaves exposed ore in walls/ceiling/floor

### ISSUE THREAD

**Issue by Mekle001** [ldtteam/minecolonies#5193]
### Minecolonies version # Update to the newest minecolonies and structurize alpha first and see if your issue might be already fixed!

Version: 0.11.958

### Expected behavior

-  Miner would dig tunnels that has cobblestone replacing every block that was ore within a few blocks of the tunnel

### Actual behaviour

-  Miner leaves ores visible in the tunnel surface and only collects ores it dug to make the tunnel.  

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

**Comment by Asherslab** [comment]
that is correct, not a bug. please make a feature request (Look at the pinned issues) if you would like it otherwise

**Comment by Mekle001** [comment]
Something changed within the last several releases, as there was a significant drop in ore being collected (and that portion of the mine looks the way I'd expect) I believe the website claims the miner will attempt to collect whole veins, but I'm not seeing that behavior.

**Comment by Raycoms** [comment]
Fixed in the newest
