### ISSUE TITLE
Lumberjack ignores trees growing on a single raised block

### ISSUE THREAD

**Issue by Geoffrotism** [ldtteam/minecolonies#5194]
### Minecolonies version # Update to the newest minecolonies and structurize alpha first and see if your issue might be already fixed!

Version: 

### Expected behavior

Lumberjack cuts tree down

### Actual behaviour

I used the define area tool and noticed the lumber jack not cutting down some trees. Debugging I found out that if you put a tree on a single raise dirt block, the lumberjack ignores that tree.
I had done this to help prevent the lumberjack getting stuck when a tree grew around them, trapping them. 
![trees](https://user-images.githubusercontent.com/5430964/84320925-693bba00-ab40-11ea-8ad4-7feb65fc0194.PNG)

As soon as I put a block next to the platform block holding the tree, the lumberjack recognized it as a target.
![cutting](https://user-images.githubusercontent.com/5430964/84321343-f2eb8780-ab40-11ea-81f5-28e344fe2798.PNG)

**Comment by Raycoms** [comment]
That is on purpose tbf. Those are not recognized as trees. Put a block next to them to make it work.
