### ISSUE TITLE
[Suggestion] High level barbarian raids come from multiple directions.

### ISSUE THREAD

**Issue by LlmDl** [ldtteam/minecolonies#5195]
I've been watching the streams and playing world of my own and I think you could make the barbarian raids more difficult at higher levels by making them spawn at more than one side of the colony. This could start by coming at the north east and north west but get harder still by making them spawn on opposite sides at even higher difficulties.

Hopefully @someaddons likes this idea. It could become more punishing.

**Comment by someaddons** [comment]
nice idea, but that is already implemented :D once you go over a certain raidlevel you get two raids

**Comment by LlmDl** [comment]
Aha, very nice. Hopefully your stream's colony gets up to that point soon.

**Comment by someaddons** [comment]
yea looking forward to Ray's reaction xD
