### ISSUE TITLE
Unable to disable citizen audible messages in config

### ISSUE THREAD

**Issue by Warhawker** [ldtteam/minecolonies#5196]
Version: 1.15.2-0.11.957
Forge: 31.2.0
"Valhelsia 2"

### Expected behavior
Line 87 in the minecolonies-common.toml allows disabling citizen messages. Setting this value to "true" should disable messages

### Actual behaviour
The citizens still speak, frequently.

### Steps to reproduce the problem
`	disablecitizenvoices = false`
to
`	disablecitizenvoices = true`

- Restart the client
- Rejoin a server (not singleplayer)
- citizens still speak

Unless the server handles the client-side sounds, it would be nice to be able to disable them.

**Comment by Raycoms** [comment]
Server only config yes. We send the messages from there.
