### ISSUE TITLE
Healer eating carrots instead of using them to heal

### ISSUE THREAD

**Issue by mfk1016** [ldtteam/minecolonies#5197]
### Minecolonies version # Update to the newest minecolonies and structurize alpha first and see if your issue might be already fixed!

Version: minecolonies-1.15.2-0.11.958-universal

### Expected behavior

The healer should use the potato and carrot he has in his inventory to heal the ill npc.

- He should only eat stuff, which is not a part of his working materials. (This should be the case for all citizens, since the farmer is also eating his farmed carrots.)

### Actual behaviour

The healer eats the carrots if he's hungry and starts moving back and forth between the hospital and the ill citizen without any further action.

This breaks the whole colony, because more ill citizens will walk to the hospital and wait indefinetly.

### Steps to reproduce the problem

1. Build a hospital and assign a healer
2. Wait until a citizen gets influenza (healed with carrot+potato)
3. Wait until the healer has low saturation and give him both items
4. ... Profit

**Comment by ravenbuilder934** [comment]
My baker also eats the bread he's just crafted and eats it as fast as he can craft it. So now I have no bread.

**Comment by DiabolosMan** [comment]
Still happening in the latest version. Previous opened bug: https://github.com/ldtteam/minecolonies/issues/4979

**Comment by Raycoms** [comment]
No, I double checked this. The healer CAN not eat carrots in the latest version in 1.15.
