### ISSUE TITLE
[Suggestion] Let the builder request more items of a single type at once.

### ISSUE THREAD

**Issue by mfk1016** [ldtteam/minecolonies#5200]
When I started to upgrade my warehouse to tier 3 (which requires more than 1000 planks), I have seen the builder requesting only batches of 10 or maybe 20 planks at once, which is quite heavy on those deliverymen. (especially since they were only 2 at this time).

I would suggest, that a builder should always request either a full stack of the material if a full stack or more is still missing (he does that sometimes only), or the exact amount required for the current build.

**Comment by Raycoms** [comment]
The builders will actually request 64, if they need 64 or more for it. However, depending on how those are spread over the warehouse, they might get a stack of 20/30 and not the entire 64. This is already in #4535. To make sure they pre-request the actual quantity they need so dmen can fill that up.
