### ISSUE TITLE
Weird claim chunk command behaviour

### ISSUE THREAD

**Issue by mfk1016** [ldtteam/minecolonies#5201]
### Minecolonies version # Update to the newest minecolonies and structurize alpha first and see if your issue might be already fixed!

Version: minecolonies-1.15.2-0.11.958-universal

### Expected behavior

I'm playing on our own server with a friend and we both have a colony (separated by about 5k blocks).
When my friend wanted to place a alternative spruce sawmill, he found, that he had not enough space in his colony so he asked if i could increase the size of his colony.

So I performed a claim chunk command for his colony, while standing in my own, so he would have more space.

I expected either a increased size for my friends colony at his site or an error message.

### Actual behaviour

After I have run the command a few times, I realized, that I wasn't able to access any chest in my colony anymore and that the townhall seemed to be part of my friends colony.

After "resetting" his size through "/mc colony claim x 10 false" (when I was at his colony this time) it worked again as expected (I had to readjust the size by more commands afterwards).

### Steps to reproduce the problem

1. Have 2 proper defined colonies
2. Go to colony 1
3. Claim chunks  for colony 2 through /mc colony claim
4. ... Profit

**Comment by Raycoms** [comment]
The claim command works around the position you stand and not around the center of the colony. This is intentional because it allows to claim very specific areas and not just round shaped around a colony.

**Comment by mfk1016** [comment]
Good to know. Thanks.
