### ISSUE TITLE
Crash while fulfilling builder request

### ISSUE THREAD

**Issue by MatthiasMann** [ldtteam/minecolonies#5202]
Version: minecolonies-1.15.2-0.11.958-universal

### Expected behavior
No crash

### Actual behaviour
Minecraft (integrated server) crashed

### Steps to reproduce the problem
1. The builder was building medieval oak townhall2 and requested 4 gravel to craft coarse dirt
2. I use the 2nd page of the builder's hut and the '+' button to put 4 gravel into the hut's inventory
3. Crash
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/
https://gist.github.com/MatthiasMann/7ef21a8776f8a8e8db93c7e3d97a15f5

**Comment by MatthiasMann** [comment]
Don't know if it's relevant but I had only build a builder (level 3), lumberjack (level 2), tavern (level 1) and a miner (level 3). No warehouse or deliveryman yet.

**Comment by Raycoms** [comment]
how much coarse dirt did he need? (So I can try reproducing this)

**Comment by MatthiasMann** [comment]
He tried to craft 6 coarse dirt

**Comment by Raycoms** [comment]
Can you find a way to reproduce this? I couldn't

**Comment by MatthiasMann** [comment]
No, hasn't happened again - but I removed the coarse dirt crafting recipe from the builder - and now I have a warehouse + deliverman.

But I fulfilled many requests, put items in his personal or hut inventory etc - no crashes since then.

**Comment by Raycoms** [comment]
Yeah, it is tied to the crafting recipe, but I tried to reproduce it with, and I couldn't.

**Comment by Raycoms** [comment]
Will close until we have a reproduce. Could've been some old data in the system.
