### ISSUE TITLE
[Suggestion] Add version to  command line

### ISSUE THREAD

**Issue by Geoffrotism** [ldtteam/minecolonies#5203]
Not sure what you call the text commands in Minecraft, but would be great to have a `minecolonies --version` or `mc --version` to print out what version is being used in game to the minecolonies CLI.

**Comment by Nightenom** [comment]
This would probably be a better addition to forge, but honestly, in the client you can use mods screen and on the server you usually have direct access to mods directory

**Comment by Raycoms** [comment]
#4535 please for feature suggestions.
