### ISSUE TITLE
Medieval Oak (and Dark) Barracks missing Tower Placeholders

### ISSUE THREAD

**Issue by Geoffrotism** [ldtteam/minecolonies#5204]
Barracks do not have tower placeholders in the design nor the list of materials.

![2020-06-11_11 54 07](https://user-images.githubusercontent.com/5430964/84409458-71950300-abdb-11ea-8e93-9630785fb094.png)

**Comment by Raycoms** [comment]
that's good, that's on purpose.

**Comment by Geoffrotism** [comment]
Could you explain why this barracks is different than the others that this would be intended?
