### ISSUE TITLE
Rangers and Rangers in Training don't use up arrows

### ISSUE THREAD

**Issue by ravenbuilder934** [ldtteam/minecolonies#5208]
## Expected behavior

Rangers and Rangers in Traning using up arrows when they shoot their bows.

## Actual behavior

When Rangers and Rangers in Training shoot, they don't use up arrows, so they have unlimited shots (as long as their bow doesn't break).

## Steps to reproduce the problem

1. Hire a ranger or ranger in training
2. give them a bow and arrows
3. wait for them to shoot something
4. ... Profit

**Comment by cinnamennen** [comment]
If you shoot into a wall, can't you recover the arrows? This seems like it would actually make sense.

**Comment by ravenbuilder934** [comment]
Yes, but they don't walk over and pick their arrows up. And even when they shoot a mob, they don't use up arrows.

**Comment by Raycoms** [comment]
That is on purpose.

**Comment by ravenbuilder934** [comment]
Why?

**Comment by Asherslab** [comment]
because arrows are expensive and annoying to craft, rangers can go through hundreds in a day at higher levels
