### ISSUE TITLE
Pirate ship should pop over building, neither very closed to town hall, and other issues with pirate ship

### ISSUE THREAD

**Issue by DiabolosMan** [ldtteam/minecolonies#5209]
### Minecolonies version
Version:  minecolonies-1.15.2-0.11.958-universal.jar

### Expected behavior
1) Pirate ship should not destroy existing building
![2020-06-12_08 07 39](https://user-images.githubusercontent.com/63854770/84480793-68686c80-ac95-11ea-85ce-e509ecf5f8ec.png)

2) Pirate ship should not pop very closed to townhall
(linked to this bug: https://github.com/ldtteam/minecolonies/issues/4684)
![2020-06-12_08 00 49](https://user-images.githubusercontent.com/63854770/84481019-bf6e4180-ac95-11ea-86c5-a34b8c4307e7.png)

3) Pirate ship should be a pirate ship, not something that we can imagine
![2020-06-12_08 08 25](https://user-images.githubusercontent.com/63854770/84481193-065c3700-ac96-11ea-9080-7e2f0de46e3d.png)

4) Pirate ship spawners should be visible
cf previous picture

5) Raid bar was not visible
Cf bug https://github.com/ldtteam/minecolonies/issues/4986

6) Pirate ship should not have spawners… or have very limited time of life (I will explain why later)

### Actual behaviour

I had a pirate ship raid…. But this time, it occured very closed to my base, 26blocks (cf screenshot 2)
It destroyed a part of my initial boat (that I cannot rebuild, **there is no build option for that**), cf screenshot 1
I tried first to find it… But as you can see in screenshot 3, it does not look like a pirateship… We can imagine it.
I am supposed to break all spawners…. But there was no spawner visible at all (cf screenshot3) and pirates were poping from the invisible spawners continuously.
For more than 1 HOUR real life, I killed huge number of endless pirates waves which was hard to handle…. But as it was impossible to kill any spawner, I stopped…. And of course, all my villagers died. This morning remaining were all 'happy'.... Strange (is it because they were happy to be safe…. They were safe because they were stuck). I came from 66 citizens to 9 citizen, the 9 guards stucks
![2020-06-12_07 58 35](https://user-images.githubusercontent.com/63854770/84482209-9b136480-ac97-11ea-8dfd-ab9428cbcabf.png)

So for the point 6, I definitely think spawners should be removed… Or disappear after a fixed number of waves. Indeed, pirates are infinites, guards are not…. So it is obvious that they all die if we are not there to help them…. And beeing with them is not enough.

I am really sad to have lost so many villagers, that were with good stats. I tried to restore a backup but it did not work, the last backup was already the one without all my villagers dead (I do not know how to restore a more previous backup)

Hope it was detailed enough but this was very weird.

**Comment by Raycoms** [comment]
I got a PR open to at least detect spawners as gone if they don't spawn. Either way, you had a weird bug where the pirate ship didn't spawn in. Do you have any mod installed that could interfere there? Did you see any log message?

**Comment by DiabolosMan** [comment]
There are many mods in the server. Maybe the best thing is to give you the world backup ?

**Comment by Raycoms** [comment]
World backup won't help a lot probably. Maybe a mod list.

**Comment by DiabolosMan** [comment]
If you use Twitch client, you can find the ModPack "RaoulTech 1.0.151"

Otherwise, copied/pasted:
[Forge] Expanded Storage | NinjaPhenix | expandedstorage-1.1.8+1.15.2.jar
-- | -- | --
A Lib | al132 | alib-1.15.2-1.jar
Abnormals Core | SmellyModder | Abnormals-Core-1.15.2-v1.0.5.jar
Additional Lights | mgen256 | additional_lights-1.15.2-1.2.0.jar
Alchemistry | al132 | alchemistry-1.15.2-5.jar
Ama's Damage Indicator | ZeAmateis | damage_indicator-0.1.0.jar
AppleSkin | squeek502 | AppleSkin-mc1.15.2-forge-1.0.13.jar
Atmospheric | paradiscal | Atmospheric-1.15.2-1.4.0.jar
AutoRegLib | Vazkii | AutoRegLib-1.5-40.jar
Bamboo Blocks | bageldotjpg | Bamboo-Blocks-1.15.2-v1.4.0.jar
Biomes O' Plenty | Forstride | BiomesOPlenty-1.15.2-10.0.0.365-universal.jar
Bloomful | bageldotjpg | Bloomful-1.15.2-v1.4.0.jar
Blue Power | Quetzi | bluepower-1.15.2-0.4.188-alpha-universal.jar
Bookshelf | DarkhaxDev | Bookshelf-1.15.2-5.6.40.jar
Buzzier Bees | bageldotjpg | Buzzier-Bees-1.15.2-1.5.1.jar
Charm | svenhjol | Charm-1.15.2-1.5.9.jar
Chem Lib | al132 | chemlib-1.15.2-3.jar
ChunkNoGoByeBye | LexManos | ChunkNoGoByeBye-1.15.2-1.2.0.jar
Comforts | TheIllusiveC4 | comforts-FORGE-1.15.2-2.0.0.2.jar
Cooking for Blockheads | BlayTheNinth | CookingForBlockheads_1.15.2-8.0.2.jar
Corpse | henkelmax | corpse-1.15.2-1.0.7.jar
CubePlus | plopyy | Cube++-1.2.1.jar
Dimensional Dungeons | Catastrophe573 | dimdungeons-1.06-forge-1.15.2.jar
DimStorage | 3divad99 | DimStorage-1.15.2-3.1.5.jar
Dramatic Doors | FizzWare | DramaticDoors-1.15.2-1.1.0.jar
Essentials | Technomancer_isTaken | essentials-1.15.2-2.7.2.jar
Evelon Warehouse | enginfirestorm | EvelonWarehouse-Core-1.1.jar.disabled
Extra Disks | MelanX | extradisks-1.15.1-1.2.jar
Falling Tree | RakSrinaNa | FallingTree-1.15.2-2.1.4.jar
Farming for Blockheads | BlayTheNinth | FarmingForBlockheads_1.15.2-6.1.3.jar
Fast Leaf Decay | olafskiii | FastLeafDecay-v22.jar
Gauges and Switches | wilechaote | rsgauges-1.15.2-1.2.3.jar
Hwyla | TehNut | Hwyla-forge-1.10.8-B72_1.15.2.jar
Incubation | Markus1002 | incubation-1.0.4-1.15.2.jar
Inventory Sorter | cpw | inventorysorter-1.15.2-17.0.0.jar
Just Enough Items (JEI) | mezz | jei-1.15.2-6.0.0.4.jar
Large Fluid Tank | Kotori316 | LargeFluidTank-15.3.0.jar
Lollipop | owmii | Lollipop-1.15.2-1.0.15.jar
Macaw's Furniture | sketch_macaw | mcw-furniture-1.0.1-mc1.15.1 1.15.2.jar
Macaw's Windows | sketch_macaw | mcw-windows-1.0.1-mc1.15.2_1.15.1.jar
Mekanism | bradyaidanc | Mekanism-1.15.2-9.10.7.420.jar
Mekanism Generators | bradyaidanc | MekanismGenerators-1.15.2-9.10.7.420.jar
Mekanism Tools | bradyaidanc | MekanismTools-1.15.2-9.10.7.420.jar
MineColonies | H3lay | minecolonies-1.15.2-0.11.958-universal.jar
Miner's Helmet | ModdingLegacy | mining-helmet-1.15.2-1.0.8.jar
MixinBootstrap | LX_Gaming | MixinBootstrap-1.0.3.jar
More Mekanism Ores | Rosi275 | MoreMekanismOres-1.15.2-1.0.5.jar
Morpheus | Quetzi | Morpheus-1.15.2-4.2.50.jar
NetherPortalFix | BlayTheNinth | NetherPortalFix_1.15.2-6.0.2.jar
OpenBlocks Elevator | vsngarcia | elevatorid-1.15.2-1.7.1.jar
Packing Tape | gigaherz | PackingTape-1.15.2-0.9.6.jar
Pam's HarvestCraft 2 - Crops | pamharvestcraft | pamhc2crops-1.15.2-1.0.5.jar
Pam's HarvestCraft 2 - Food Core | pamharvestcraft | pamhc2foodcore-1.15.2-1.0.3.jar
Pam's HarvestCraft 2 - Trees | pamharvestcraft | pamhc2trees-1.15.2-1.0.5.jar
Patchouli | Vazkii | Patchouli-1.15.2-1.2-33.jar
PlantTech 2 | chrisland | planttech2-0.02.11 - 1.15.2.jar
Powah! | owmii | Powah-1.15.2-1.1.14.jar
Quark | Vazkii | Quark-r2.1-244.jar
RandomPatches | TheRandomLabs | randompatches-1.15.2-1.21.1.3.jar
Ranged Pumps | raoulvdberge | rangedpumps-0.7.1.jar
Redstone Gates | se7kn8 | gates-1.5.2.jar
Refined Storage | raoulvdberge | refinedstorage-1.8.4.jar
Refined Storage Addons | raoulvdberge | refinedstorageaddons-0.6.1.jar
Reliquary v1.3 | P3pp3rF1y | Reliquary-1.15.2-1.3.4.995.jar
Ropes Mod! | TheGoldCrayon | tgcropesmod-1.15.2-1.2.0.jar
Scalable Cat's Force | Kotori316 | ScalableCatsForce-2.13.2-build-2-with-library.jar
Serene Seasons | TheAdubbz | SereneSeasons-1.15.2-3.0.0.72-universal.jar
Spice of Life: Carrot Edition | lordcazsius | solcarrot-1.15.2-1.9.6.jar
Storage Drawers | Texelsaur | StorageDrawers-1.15.2-7.0.2.jar
Strange | svenhjol | Strange-1.15.2-1.0.0-beta.5.hotfix1.jar
Structurize | H3lay | structurize-0.10.322-ALPHA.jar
Taffy - Date and Forecast (TaffyDAF) | Gerflargle | taffydaf-1.15.2-0.3.jar
Titanium | HRZNStudio | titanium-1.15.2-2.4.1.jar
Tool Belt | gigaherz | ToolBelt-1.15.2-1.14.1.jar
TorchBowMod | noriokun4649 | [1.15.1-1.15.2]TorchBowMod_v1.4.jar
Transport | Sky_Som | Transport-1.15.2-2.3.0.jar
U Team Core | HyCraftHD | u_team_core-1.15.2-2.11.0.156.jar
Useful Backpacks | HyCraftHD | useful_backpacks-1.15.2-1.9.4.63.jar
Valhelsia Structures | ValhelsiaTeam | valhelsia_structures-15.0.3a.jar
ValkyrieLib | ValkyrieofNight | valkyrielib-1.15.2-3.0.2.1.jar
Venture | MrCrayfish | venture-1.0.0-1.15.2.jar
Water Erosion | 13rac1 | water-erosion-1.15.2-forge-1.1.2.jar
Wawla - What Are We Looking At | DarkhaxDev | WAWLA-1.15.2-3.0.2.jar
Wireless Redstone FE | feonen | wirelessredstone-1.15.2-0.1.0.jar
Xaero's Minimap (Fair-play Edition) | xaero96 | Xaeros_Minimap_FP20.12.2_Forge_1.15.2.jar
Xaero's World Map | xaero96 | XaerosWorldMap_1.6.3_Forge_1.15.2.jar

**Comment by Raycoms** [comment]
960 should handle this a lot more gracefully now.
