### ISSUE TITLE
Buckets disappear

### ISSUE THREAD

**Issue by bloodyraoul** [ldtteam/minecolonies#5210]
Version : minecolonies-1.15.2-0.11.958-universal.jar

I give buckets to my cowboy to produce milk buckets
milk buckets are given to the backer to cook cakes
after that, i should have empty buckets

Where are my empty buckets ?
I have given tens of them and cannot find them anymore ?

**Comment by Raycoms** [comment]
Did yur dman take them to the warehouse?

**Comment by bloodyraoul** [comment]
no, i have check every rack in every house and every pockets of every citizen, no bucket
