### ISSUE TITLE
Citizen should take care of light level

### ISSUE THREAD

**Issue by bloodyraoul** [ldtteam/minecolonies#5211]
Version : minecolonies-1.15.2-0.11.958-universal.jar

I ask to upgrade my building :
- the builder remove torches
- the builder start to build the new level
- ho, it is 18h00, end of day, he goes to sleep
- hey, wait, and the torches ?....
-then monster spawn and kill peoples

other problem, there is not enought light, monsters can spawn in archery and weapon academy level 3 (dwarnen style)

other problem, miner often die because monster spawning in cave.
maybe he could flee away and ask for help

**Comment by Raycoms** [comment]
#4535
