### ISSUE TITLE
Some Hut Textures and Models are Missing

### ISSUE THREAD

**Issue by CHead2000** [ldtteam/minecolonies#5212]
### Minecolonies version # Update to the newest minecolonies and structurize alpha first and see if your issue might be already fixed!

Version: 1.15.2-0.11.958-universal

### Expected behavior

- Huts have completed models and textures

### Actual behaviour

- The following hut blocks have no models or textures:
     - Farm
     - Lumberjack's Hut
     - Warehouse
     - Shepherd's Hut
     - SwineHerder's Hut
     - ChickenHerder's Hut
     - Archery
     - Combat Academy
     - Stone Smeltery
     - University
     - Hospital
     - School

![2020-06-12_10 47 55](https://user-images.githubusercontent.com/65131882/84515315-4fae8580-ac9a-11ea-941b-7af74580a42c.png)
![2020-06-12_10 48 10](https://user-images.githubusercontent.com/65131882/84515324-51784900-ac9a-11ea-8cf1-4391e82d145e.png)
![2020-06-12_10 48 20](https://user-images.githubusercontent.com/65131882/84515328-53420c80-ac9a-11ea-9f03-16cc051a01a4.png)

### Steps to reproduce the problem

1. Load Game Normally

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: [latest.log](https://github.com/ldtteam/minecolonies/files/4771482/latest.log)
- crashlog: N/A

**Comment by ravenbuilder934** [comment]
Are you using OptiFine?

**Comment by Raycoms** [comment]
1) Please search similar issues before reporting to save us time
2) This is an optifine issue with forge multilayer models. Please report this to optifine.
