### ISSUE TITLE
Issue with Builder Resources

### ISSUE THREAD

**Issue by Rithenar** [ldtteam/minecolonies#5213]
### Minecolonies version # Update to the newest minecolonies and structurize alpha first and see if your issue might be already fixed!

Version: 
minecolonies-1.15.2-0.11.958-universal.jar
structurize-0.10.322-ALPHA.jar

### Expected behavior

Builder would accept their requests or clear them when materials are given to the Builder's Hut in the Required Resources window
- 

### Actual behaviour

I believe there are 2 separate issues. First is that after playing for a while I give the builder a job. I receive the message that she started building and I go to the Builders Hut. Click on the blue arrow on the upper right and if I have the ingredient in inventory I click on the arrow to deposit into the inventory. The item disappears from the list momentarily and then appears again. I check my inventory and the items are still there, they were never transferred to the builder's hut.  I try to place the materials directly in the hut's inventory but the list will not recognize them. I have to restart the server in order for things to start working again normally.  Also the builder will have a request and I click the fulfill button, but although the listing goes away, the material is not taken from my inventory so the request icon above the builder's head pops up again.

The second issue is a follow up of the first, and similarly reported already.  When I log back in, all materials that were accepted by the hut before the problem started disappear. It almost looks like nothing that was done in the last 5 minutes of game play were saved or it reverts to a state about 5-10 min prior to restart.

- 

### Steps to reproduce the problem

1. Click requested material arrow in the Required Materials tab in the hut
2. See item line disappear
3. See item line re-appear
4. ... check all inventories...nothing changed
5. ...Profit!

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: https://paste.ee/p/sELUj
- crashlog:

**Comment by Raycoms** [comment]
Duplicate issue.
