### ISSUE TITLE
Activating multi-pistons crashes the game

### ISSUE THREAD

**Issue by Consumerx54** [ldtteam/minecolonies#5214]
### Minecolonies version # Update to the newest minecolonies and structurize alpha first and see if your issue might be already fixed!

Version:  11.958

### Expected behavior

- I expect blocks to be placed or removed

### Actual behaviour

-   As soon as I flip the lever to operate the multi-pistons the game crashes.  If on a server the server crashes or if on single player the client crashes 

### Steps to reproduce the problem

1.   Just activate a multi-piston
2. 
3. 
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

**Comment by Raycoms** [comment]
fixed in newest structurize already. Will be released this weekend.
