### ISSUE TITLE
[Bounty: $30] [Request] Aquaculture 2 Mod Support

### ISSUE THREAD

**Issue by Cacc22** [ldtteam/minecolonies#5218]
### Minecolonies version #

Version: 0.11.957

### Expected behavior

- Fisher will fish with Iron/Gold/Diamond/Neptunian rods.

### Actual behaviour

- Fisher will hold Iron/Gold/Diamond/Neptunian rods and clear notification of needing a rod, but will otherwise just stand around not fishing.

### Steps to reproduce the problem

1. Give Fisher an Aquaculture 2 fishing rod.
2. Participate in staring contest.

**Comment by Cacc22** [comment]
Apologies for missing the Mod support pin, I wanted to add a bounty so I was more focused on that part -_-

**Comment by ravenbuilder934** [comment]
Fixed
