### ISSUE TITLE
Major Bug: My Colonists are gone

### ISSUE THREAD

**Issue by Warrof** [ldtteam/minecolonies#522]
I just updated to Version 6.2 of Mincolonies.

MY Colonists are all gone and I can;t access any of the Minecolonies Chests.

**Comment by Warrof** [comment]
I just downgraded to 6.1 through the Curse Client, Whatever happened stayed the same.  No Colonists.

BTW I was playing just fine for hours before the update.

Edit:  Seems the game think I Haven't placed a Townhall Chest.  I can't place any other chests.

**Comment by Raycoms** [comment]
can you send us your logs please?

2017-01-29 22:35 GMT-02:00 Warrof <notifications@github.com>:

**Comment by Warrof** [comment]
[Warrof's Logs.zip](https://github.com/Minecolonies/minecolonies/files/737999/Warrof.s.Logs.zip)

There they are.
