### ISSUE TITLE
Can't load newest version

### ISSUE THREAD

**Issue by teagan75** [ldtteam/minecolonies#5222]
Version: minecolonies-0.11.938-BETA-universal.jar

### Expected behavior

I expected it to load.
- 
This version of Minecolonies is asking for a version of Structurize not available.
![error](https://user-images.githubusercontent.com/12485764/84580405-4574b000-ad9c-11ea-9fd5-e161295116b6.PNG)

**Comment by someaddons** [comment]
go to curseforge click view all, download newest version of both

**Comment by teagan75** [comment]
That doesn't work when using the launcher FYI
