### ISSUE TITLE
Broken miner

### ISSUE THREAD

**Issue by tiffany352** [ldtteam/minecolonies#5224]
### Minecolonies version

Minecolonies: 1.15.2-0.11.958-universal 
Structurize: 0.10.322-ALPHA

### Expected behavior

- Miners should be able to handle the case that there are some ladders inside their plot when the building is first placed.

### Actual behaviour

I built a new miner and realized part way through construction that one of my old manual mines was there. I was hoping it wouldn't be an issue, but...

First my miner kept telling me he couldn't dig any further until he got upgraded. I realized that there were ladders inside the building's area, so I removed them. Then he started erroring out.

![image](https://user-images.githubusercontent.com/1254344/84582680-119d8880-ada4-11ea-9970-6617e2b3a719.png)

Snippet from log file is here: https://gist.github.com/tiffany352/777b6020060d22d63fd54acae4ba2c44

### Steps to reproduce the problem

1. Place a miner in a spot that already has ladders underground.
2. Wait for it to get built.
3. Observe broken behavior.

I was able to fix the issue by destroying all the ladders and then breaking and replacing the miner and building it again. Restarting him didn't work, firing and rehiring didn't work. Ideally there should be a way to reset building state like this without having to rebuild your building as level 2 and re-upgrade it.

### Logs
- latest.log: Gist won't let me upload the whole 29 megabyte file. Let me know if there's anything I missed in the snippet I posted above.

**Comment by Raycoms** [comment]
Yeah,t here can't be ladders in the build area. We can't support this unfortunately. That is one of the limitations of the AI.
