### ISSUE TITLE
new buildings are missing

### ISSUE THREAD

**Issue by 40mboudreaux** [ldtteam/minecolonies#5226]
Version: minecolonies-1.12.2-0.11.841-ALPHA-universal.jar

### Expected behavior
I expect to see the new buildings that were added: dyer, glassblower, hospital, university etc.

- 

### Actual behaviour
Buildings do not show up at all. I tried seeing if I could craft the building, ie the dyer and nothing happens. Going into creative and looking at the minecolonies mod shows just the original buildings with the exception of the florist and the enchanter.  I do not have optifine as I am using the Twitch launcher and minecolonies official modpack. I updated what needed to be updated and still nothing is showing.  I have not added any mods to the modpack.  When I create a new world I have tried creating everything from default to biomes a plenty to see if maybe there was an issue there but no such luck.

**Comment by Raycoms** [comment]
1.15 only

**Comment by 40mboudreaux** [comment]
Thank you for clearing that up. 

    On Sunday, June 14, 2020, 10:07:52 AM CDT, Raycoms <notifications@github.com> wrote:  
 
 


Closed #5226.
