### ISSUE TITLE
Game crash when viewing UI of Librarian

### ISSUE THREAD

**Issue by tiffany352** [ldtteam/minecolonies#5228]
### Minecolonies version

Minecolonies: 1.15.2-0.11.958-universal
Structurize: 0.10.322-ALPHA

### Expected behavior

- Game to not crash to desktop

### Actual behaviour

- Crash

### Steps to reproduce the problem

1. Get a library and assign a librarian.
2. Right click to view their UI.
3. Flip to the third page where it should show their current job.
4. Game crashes every time.

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: https://gist.github.com/tiffany352/d428b451ff5428def3c05e38c5057970
- crashlog: https://gist.github.com/tiffany352/c612c0d3915f973334ede5d2a8c92981

**Comment by ravenbuilder934** [comment]
What version of Forge are you on? 958 alpha requires 31.2.9 or later.

**Comment by tiffany352** [comment]
@ravenbuilder934 Sorry for forgetting to include it. It's Forge 31.2.9.

**Comment by Raycoms** [comment]
yeah, I know what this is.
