### ISSUE TITLE
sendEnteringLeavingMessages doesn't work when set to false

### ISSUE THREAD

**Issue by rockett1** [ldtteam/minecolonies#5231]
### Minecolonies version # Update to the newest minecolonies and structurize alpha first and see if your issue might be already fixed!

Version: 1.12.2-0.11.811-BETA
Modpack: MC Eternal

### Expected behavior

It does not disable entering and leaving message when set to false
- 
It does not disable the messages that pop up for entering and leaving a mine colony
### Actual behaviour

I still get the entering and leaving messages
- 
The entering and leaving messages still spam

image of the setting being set to false but still getting messages in MC, restarting the game doesnt change anything either
https://storage.googleapis.com/rockettsharex/ShareX/2020/06/EaSJam9UbH.png
### Steps to reproduce the problem

1.  Set sendEnteringLeavingMessages to false
2.  walk in and out of a minecolony
3.  message gets spammed entering and leaving a minecolony
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: N/A
- crashlog: N/A

**Comment by Raycoms** [comment]
This is a server side setting, did you turn that off on the server?

**Comment by rockett1** [comment]
We just disabled it on the server and It still gets spammed for us. 

It's now disabled on client and server but still gets spammed.

We typed reload though in server not restarted it we will try restart it now.

**Comment by Raycoms** [comment]
Yeah, gotta restart to make sure.

**Comment by rockett1** [comment]
it worked after a restart! no more message spam :D Sorry for causing a worry/concern. Thanks for the super quick replies and support its much appreciated.
