### ISSUE TITLE
Problem with miner schematic

### ISSUE THREAD

**Issue by lebanni** [ldtteam/minecolonies#5233]
minecolonies-1.15.2-0.11.959-universal.jar
structurize-0.10.323-ALPHA.jar

Building is miner nordic level 1.

I think there's something wrong :

![2020-06-16_02 36 43](https://user-images.githubusercontent.com/2799575/84725691-78c96180-af8b-11ea-934d-d077d96fb965.png)

Really wrong :

![2020-06-16_04 08 59](https://user-images.githubusercontent.com/2799575/84731090-12970b80-af98-11ea-8905-5be8143757c9.png)

![2020-06-16_09 45 42](https://user-images.githubusercontent.com/2799575/84746485-4e40ce00-afb6-11ea-82f5-5f481b9e750f.png)

**Comment by Raycoms** [comment]
Same problem: #5234
