### ISSUE TITLE
Multiple colonists burned to death in fortress cook level 3.

### ISSUE THREAD

**Issue by PatrickGoulet** [ldtteam/minecolonies#5237]
Version:  minecolonies-1.15.2-0.11.959-universal.jar

### Expected behavior

Colonist can go eat without burning to death in level 3 fortress cook. I could not notice if it happened everytime or not yet.

### Actual behaviour

Over a 30 min playtime after updating to 959 (coming from 956 I think), I've had a shepard and delivery man burning to death in the fortress cook level 3. They are dying 2 blocks in front of the fire under the building block. I did not test it with other levels and did not record any video but it never happened before and this colony has many hours of playtime. 

I removed the fire to prevent further suicide. 

### Steps to reproduce the problem

Might be hard to take a video or reproduce rapidly but 2 times over 30 min ish seemed enought to report for me just in case.

### Logs: Latest.log and crashlog at https://gist.github.com/

No AI path crash for the burned workers or anything significant to report here.

**Comment by Raycoms** [comment]
#5006
