### ISSUE TITLE
Builder not accepting red carpet - Builder hut3 Asian template

### ISSUE THREAD

**Issue by EthanKincaid** [ldtteam/minecolonies#5238]
Version: Minecraft 1.15.2 release
Minecolonies 0.10.771 -RELEASE (yes I tried downloading the newest Alpha; it just crashes)

### Expected behavior

- Expected builder interaction panel to offer the options of FULFILL or CANCEL
Expected builder to find the two red carpets placed in his inventory and place them.
Expected builder to retain the two red carpets in his inventory if unable to place them.

- Ordinarily, builder should request the items required (2 red carpets), accept them when given by the player, and place them.

### Actual behaviour
- Builder requests the 2 red carpets needed for the builderhut3 asian template, however only CANCEL is available to select. 
If the 2 red carpets are placed manually in the builder's inventory, he discards them into the nearest rack or his hut inventory and continues to ask for the items.

Firing and rehiring the builder does not help. Restarting the builder does not help. Exiting the game and rebooting does not help. Filling up the nearby racks and hut inventory so he cannot discard the items does not help. He appears to simply not recognize the item.

### Steps to reproduce the problem

1. Tell builder to construct builderhut3 in the Asian style
2. Proceed with the build until it is time for the builder to place the two red carpets.
3. Respond to builder's request for 2 red carpets. 
4. Attempt to give it to him.
5. Scream. (optional)

**Comment by Raycoms** [comment]
Super old version, please update

**Comment by EthanKincaid** [comment]
> Super old version, please update

"(yes I tried downloading the newest Alpha; it just crashes)" As stated, newest version is unplayable for me. Shall I file a report for that instead?

**Comment by MatthiasMann** [comment]
You also need to update forge to at least .8 or newer

**Comment by Raycoms** [comment]
Update forge to 31.2.8+ Like Matthias pointed out

**Comment by EthanKincaid** [comment]
Aha! That is helpful. Thank you :)
