### ISSUE TITLE
MC-Techcolonies Remote player in multiplayer kicked when they "see" my machete

### ISSUE THREAD

**Issue by DrLucky007** [ldtteam/minecolonies#5239]
I've reported this to Silent's Gear issue tracker.  https://github.com/SilentChaos512/Silent-Gear/issues/143
I'm replicating here in case it helps you close issues / workaround.

## Versions
- **Minecolonies**: minecolonies-1.15.2-0.11.958-universal
- **Structurize**: structurize-0.10.322-ALPHA
- **Silent Gear**: SilentGear-1.15.2-1.7.2+96
- **Silent's Gems**: SilentGems-1.15.2-3.5.5+88
- **Silent Lib**: SilentLib-1.15.2-4.6.1+49
- **Forge**: 31.2.9
- **Modpack**: MC-Techcolonies 3.4
- **Optifine Installed**: No

## Expected Behavior

The player to not get kicked.

## Actual Behavior

Remote player gets kicked with one of a variety of messages.  (Null Pointer Exception or Timeout are common).

## Links/Images

Link to my (host) log: https://pastebin.com/WuQnC13S
showing a typical attempt to login by a remote player.

Link to remote player log.  Their system clock seems to be within about 2s of mine: https://pastebin.com/5uaPQZCW

## Steps to Reproduce the Problem

1. Put my machete in my hotbar (Pyrope, Pyrope, Hardened Stone, Iron Rod, Lapis Coated)
2. Walk up to player
3. Select the machete 
4. Player immediately gets kicked from the game
5. Player tries to log back in
6. Player gets kicked
7. Select another tool
8. Player tries to log in
9. Player succeeds.

I believe I've experienced this as a remote player, but I had made a multi-material pick in that case, and it was in my own inventory.  I was subsequently unable to log back in successfully.  I will be asking the host to delete my player files to see if we can replicate that way.

It's very likely tied to multi-material tools, since we are using single-material tools frequently without issue.  Might also be the Lapis coating.

It does not appear to affect me as host.

**Comment by Asherslab** [comment]
bug is from silent gear
