### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by DemonSlayer953** [ldtteam/minecolonies#5242]
### Minecolonies version # Update to the newest minecolonies and structurize alpha first and see if your issue might be already fixed!

Version: 1.15.2

### Expected behavior

- 

### Actual behaviour

- 

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: https://gist.github.com/DemonSlayer953/abfa7dc68929791d9c0be592e2ca33ab
(didn't know how to add the file but a small mod line is missing at the end of the first line)
- crashlog:

**Comment by someaddons** [comment]
update forge
