### ISSUE TITLE
colonists having AI errors, not doing jobs

### ISSUE THREAD

**Issue by LuckyFalkor** [ldtteam/minecolonies#5243]
updated mincolonies and related files and now any builds or requests the people had pending seem to be stuck.

lots of errors like this one:
 [Server thread/FATAL] [net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Server
java.lang.IllegalArgumentException: The given request: StandardToken{id=3ae1b20d-8fe5-4736-947a-2e88c5bbe11c} is not resolved.
	at com.minecolonies.coremod.colony.requestsystem.management.handlers.ResolverHandler.getResolverForRequest(ResolverHandler.java:334) ~[?:1.15.2-0.11.960]
(more levels to the error, see attachment at end of file)

previous versions:
structurize-0.10.315-ALPHA
minecolonies-1.15.2-0.11.948-universal
forge-1.15.2-31.2.0

Current versions:
structurize-0.10.324-ALPHA
minecolonies-1.15.2-0.11.960-universal
forge-1.15.2-31.2.8

### Expected behaviour

delivery requests registering as fulfilled once the delivery is made by the delivery guy.
builder, miner, etcetera, then take the delivered materials/tools and use them as expected.

### Actual behaviour

delivery requests that were queued prior to the update are not being fulfilled by the delivery guys.
they are simply standing around not delivering.
had to destroy the various huts they had pending requests for and rebuilt before they started working again.
(the miner is not working right since the rebuild, something about level 3 is not high enough to mine, eventually started filling in the mine with cobble and then started mining it again)

### Steps to reproduce the problem

1. have a server configured with the previous versions as stated above and a colony with delivery people running around fulfilling requests.
2. update the server and clients with the current versions as stated above and launch server and connect
3. watch NPCs be confused

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: https://gist.github.com/LuckyFalkor/f4d5eb315b6ea825f39f3d13b9dd7301
- crashlog: nothing is crashing the server

**Comment by harmalom** [comment]
same error, since the last update, two colonists with a message of, AI broken, and the rest no longer work.

crash report: https://gist.github.com/harmalom/c4e5cf23b4b3d279224a1f9ca8592c95

**Comment by Asherslab** [comment]
@LuckyFalkor 
> Logs: Latest.log and crashlog at https://gist.github.com/

Please use it..

**Comment by LuckyFalkor** [comment]
> 
> 
> @LuckyFalkor
> 
> > Logs: Latest.log and crashlog at https://gist.github.com/
> 
> Please use it..

Alright, thought i had, didn't realize the "gist" part of the address was not used when dragging the file onto the editor.
My apologies, i updated the post.
If there is anything else i need to do, please be a bit more specific, it was not obvious at first what the issue was as both address's domain was so similar.

https://gist.github.com/LuckyFalkor/f4d5eb315b6ea825f39f3d13b9dd7301

**Comment by McKitten** [comment]
Modpack Valhelsia 2.2.3
Forge 31.2.21
minecolonies-1.15.2-0.11.960-universal
structurize-0.10.324-ALPHA

https://gist.github.com/McKitten/59354abf3d2f489e88a8a01a74d9b52f

This (unix based) server has also been experiencing the builder loosing resources pre-update and them not recognising the order has been filled post update.

I believe in this case she was waiting for stripped oak logs.

**Comment by Raycoms** [comment]
Duplicate to #5227 and anotjher one.

**Comment by LuckyFalkor** [comment]
> 
> 
> Duplicate to #5227 and anotjher one.

thanks
