### ISSUE TITLE
Requests created with some (not all) items already in the wharehouse are never finished.

### ISSUE THREAD

**Issue by patgoull** [ldtteam/minecolonies#5246]
Version:  minecolonies-1.15.2-0.11.960-universal

### Expected behavior

When builder request an item which has some already crafted in the warehouse and some that need crafting, the missing items are correctly crafted via the appropritate crafter and delivered to the builder.

### Actual behaviour

Wharehouse has 1 flower pot out of 6 required by the builder. He requests 6 (1 picked up and 5 to be crafted. All is good on the UI). However, it is never delivered to the first crafter (in this case, clay is never delivered to the stone smelter so he cannot craft bricks to allow the stonemason to craft pots). Some other requests that were created after the pots even got priorised and smelted super quickly by the stonesmelter and fully crafted correctly.

### Steps to reproduce the problem

1- Have a request created by the builder which has items partially present in the warehouse.
2- Make sure you have all the raw items needed in the warehouse.
3- Wait for it to be done. You can even see other requests being done in the meantime through the same required crafter.

I did not take screenshots from the flower pots issue but I reproduced it with torch on the builder itself. The request is stuck this way. In this case, charcoal or sticks will never be delivered to the builder (same for clay on original flower pot issue). He will neither received the 1 torch present in the wharehouse.

![image](https://user-images.githubusercontent.com/25259519/84960231-17121000-b0cf-11ea-85bc-075f47cbc34a.png)

This is the recipe the builder knows.

![image](https://user-images.githubusercontent.com/25259519/84960255-24c79580-b0cf-11ea-9912-d16517546df0.png)

Just to prove items are in the wharehouse.

![image](https://user-images.githubusercontent.com/25259519/84960207-08c3f400-b0cf-11ea-84c9-4cfe20ebbe57.png)
![image](https://user-images.githubusercontent.com/25259519/84960268-327d1b00-b0cf-11ea-8cd6-69acacd387f0.png)

### Logs: Latest.log and crashlog at https://gist.github.com/

No crash or any message in the latest.log when I reproduce this problem.

**Comment by patgoull** [comment]
Another case stuck with 13 needed fence gate and 12 already in wharehouse.

![image](https://user-images.githubusercontent.com/25259519/85097013-19a26180-b1c4-11ea-8fb3-7057c68807ef.png)

**Comment by PatrickGoulet** [comment]
On my last post, I meant 1 already in the wharehouse and 12 to be crafted.

**Comment by patgoull** [comment]
Another one on minecolonies-1.15.2-0.11.961-universal.

![image](https://user-images.githubusercontent.com/25259519/85335887-beb28800-b4ab-11ea-876a-46bee974dbb0.png)

I am wondering if the only issue is the fact that they are getting assigned to "resolved by player". It seems like they would get resolved correctly otherwise.
