### ISSUE TITLE
AI error on stonemason asking for report. java.lang.NullPointerException.

### ISSUE THREAD

**Issue by patgoull** [ldtteam/minecolonies#5247]
Version: minecolonies-1.15.2-0.11.960-universal

AI error on stonemason asking for report. java.lang.NullPointerException.

### Logs: Latest.log and crashlog at https://gist.github.com/

https://gist.github.com/patgoull/2cce326ef83a04d72b30b68f7c5e4867

**Comment by Strohtaler** [comment]
looks like the same Exception as #5236 - at least thrown from same source line: `AbstractEntityAICrafting.java:279` (but different worker)

**Comment by Raycoms** [comment]
duplicate yes
