### ISSUE TITLE
AI error

### ISSUE THREAD

**Issue by lordseppe** [ldtteam/minecolonies#5249]
what does this mean and how do i fix it?
[latesterror.txt](https://github.com/ldtteam/minecolonies/files/4801542/latesterror.txt)
![mcerror](https://user-images.githubusercontent.com/66175471/85079008-0beddb80-b1c6-11ea-9d88-52f3a818d15d.PNG)

**Comment by someaddons** [comment]
follow the template

**Comment by lordseppe** [comment]
the issue template i need to fill in?

**Comment by someaddons** [comment]
of course

**Comment by Asherslab** [comment]
@lordseppe yes, of course, that's why it's there?

**Comment by lordseppe** [comment]
owkay ;3

**Comment by lordseppe** [comment]
can i post the asnwer to the template here or should i make a new and proper issue report?

**Comment by Asherslab** [comment]
make a new one
