### ISSUE TITLE
AI crash solution?

### ISSUE THREAD

**Issue by lordseppe** [ldtteam/minecolonies#5250]
not sure if i and how i should update the mod inside a modpack im playing from the twitch launcher. valhelsia 2.

Exact Version:  1.15.2-0.11.948-universal

### Expected behavior

The lumberjack should destroy and replant trees to gather wood. she was doing this fine for a few hours. suddenly i got an error pop-up saying the AI crashed. after that she hasnt moved.

### Actual behaviour

Nothing, she isnt moving anymore.
![mcerror](https://user-images.githubusercontent.com/66175471/85079625-96830a80-b1c7-11ea-86b3-a0207cbaf77b.PNG)

### Steps to reproduce the problem

not really sure if i should answer to this. but maybe add what the solution is to the problem of the AI crash.

- latest.log: [latest.log](https://github.com/ldtteam/minecolonies/files/4801575/latest.log)
- crashlog: //

**Comment by Raycoms** [comment]
duplicate
