### ISSUE TITLE
Missing resources and possible chunk or colony/building corruption after filling build list

### ISSUE THREAD

**Issue by cwg930** [ldtteam/minecolonies#5252]
### Minecolonies version # Update to the newest minecolonies and structurize alpha first and see if your issue might be already fixed!

Version: Minecolonies 0.11.960 / Structurize 0.10.324 / Minecraft 1.15.2 / Forge 31.2.20

### Expected behavior

- Filling out build requirements by clicking the arrow buttons on the second page of the builder block should add those blocks to the inventories of the builder hut and set the amounts in the build list accordingly. The builder should then use those resources to complete the requested building.

### Actual behaviour

- 
Filling out build requirements by clicking the arrow buttons on the second page of the builder hut removes them from the player's inventory and temporarily marks the given amount on the build resources list. No resources are added to the inventory of the build hut, any additional inventories in the build hut, nor the builder associated with that hut. After some time the build list is cleared and reset to the amounts from before attempting to fill the request. The resources are not available to the builder, and the build hut inventories remain empty. The player is also not refunded the given materials. On Leaving and rejoining the world, and/or loading the chunk containing the build hut, the server will hang. 

![bug](https://user-images.githubusercontent.com/613260/85087766-6c701f00-b1ac-11ea-9ff8-b8b7baca7936.PNG)
### Steps to reproduce the problem

(specific building used when issue occurred: Medieval Oak University Level 1)

1. Begin construction of a building by placing a blueprint with the build tool and starting the build from build options of the building block interface.
2. Wait for a builder to begin construction of the building and populate the resource requirements list
3. Fill the entire resource requirements list from the second page of the build hut interface by using the arrow on the right side of each resource row.
4. Observe that the resource list shows all requirements as filled
5. Open the inventory of any or all inventory blocks in the build hut, including the build hut's own inventory and observe that none of the given resources are present.
6. Open the inventory of the builder assigned to the build hut and observe that none of the given resources are present.
7. Wait several minutes
8. Observe that after some time the resource list has returned to the unfilled state it was in before filling the requirements 
9. Observe that the builder requests resources to complete the build once the initial space clearing is completed
10. Observe that all of the inventories (build hut, build hut blocks, builder) remain empty aside from any blocks gained while clearing the build area.
11. Log out of the server and back in, or leave the area until the chunk unloads then return
12. Notice that no mobs move and very few chunks will load (and automatic crash detection kicks in after a while if on a hosted dedicated server)
13. Right-click the builder hut block and observe that it prints a message about not having the required building structure.
### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: https://gist.github.com/cwg930/ea58d10576be63a55143222ebd84d982#file-latest-log
- crashlog: https://gist.github.com/cwg930/ea58d10576be63a55143222ebd84d982#file-crash-2020-06-18_20-51-23-server-txt

**Comment by Raycoms** [comment]
Duplicate #5171
