### ISSUE TITLE
If you break a stash, all the contents get voided

### ISSUE THREAD

**Issue by cinnamennen** [ldtteam/minecolonies#5253]
### Minecolonies version # Update to the newest minecolonies and structurize alpha first and see if your issue might be already fixed!

Version: .598

### Expected behavior

- The contents to get dropped on the ground

### Actual behaviour

- poof

### Steps to reproduce the problem

1. put items in a stash
2. break it

**Comment by Raycoms** [comment]
Only needs the loot table.

**Comment by Raycoms** [comment]
I just double checked, this works fine in the newest version
