### ISSUE TITLE
Placing a supply camp or ship causes crash

### ISSUE THREAD

**Issue by Jarrry** [ldtteam/minecolonies#5258]
Version:
Minecolonies: 0.10.771-RELEASE
Structurize: 0.10.313-RELEASE

### Expected behavior

I try to place the "supply camp" or "supply ship" to start a colony.

### Actual behaviour

Game Crashes

I get the overlay. I can control it's orientation/style as intended. However, as soon as i click the green check mark, the game freezes for a couple seconds then crashes. 

I tried it with and without the builder wand.

### Steps to reproduce the problem

1. Craft supply camp/ship
2. Place in appropriate flat surface
3. Click green check mark
4. ... Profit ... 

### Logs: 

- crashlog: https://gist.github.com/Jarrry/88fd00b5620d5aa80e892b1c0392feb0

**Comment by someaddons** [comment]
update

**Comment by ravenbuilder934** [comment]
Update to the latest alphas, your structurize and minecolonies are mismatching

**Comment by CplPibald** [comment]
Is there a newer release version?  I just encountered this issue with the latest RELEASE version of Minecolonies (0.10.771) and the latest RELEASE version of structurize (0.10.313).  Are the current release versions not meant to work together?  I'm usually wary of putting alpha software on a production server.

**Comment by ravenbuilder934** [comment]
Though in some other instances alphas mark "unstable" versions, MineColonies alphas are just minor releases and primarily have nothing to do with stability/instability. 
Alphas are just too small to call them beta/release.
