### ISSUE TITLE
Backup the minecolonies.dat [$10 awarded]

### ISSUE THREAD

**Issue by xavierh** [ldtteam/minecolonies#526]
It would be nice if the minecolonnies.dat was backup automatically at each start of the server/world.

- Backup the dat file as minecolonnies-YYYY-MM-DD.dat and continue to use minecolonnies.dat 
- Do it when the server start
- add a command to do the back so server admin could schedule an automatic backup even when the server is not restarted

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=41473573)](https://www.bountysource.com/issues/41473573-backup-the-minecolonnies-dat?utm_source=41473573&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by marvin-bitterlich** [comment]
Works like a charm @asiekierka thanks!
![image](https://cloud.githubusercontent.com/assets/644950/23057584/200a2e24-f4f1-11e6-9811-eb609068be93.png)
![image](https://cloud.githubusercontent.com/assets/644950/23057653/68b113d6-f4f1-11e6-857b-48893f9f4853.png)

**Comment by marvin-bitterlich** [comment]
Seems like the command permissions have to be fixed as OP lvl 4 is int 3 in mc code. We should already have a config option handling this I guess...
