### ISSUE TITLE
0.10.714 Minecolonies Builder will not stop digging.

### ISSUE THREAD

**Issue by Mrs-Ghevious** [ldtteam/minecolonies#5265]
The builder will not stop digging. I have used the building tool to place the building. I have taken away the shovel and pickaxe. They now sit with the request needed icon on. I have canceled the request multiple times. To no avail, they will not build.

**Comment by cinnamennen** [comment]
have you tried updating?

**Comment by Raycoms** [comment]
Yes, please update.
