### ISSUE TITLE
Town Hall disconnected from reality

### ISSUE THREAD

**Issue by ghost** [ldtteam/minecolonies#5267]
Forge: x.2854
Colonies: 0.11.841-ALPHA

This has been going on for a while now. The information page of the town hall seems to be disconnected from reality. In the following image the following are wrong:
-I do have a baker
-Null smelters...? (I do have one)
-Whatever is going on below deliverymen that lost its localization
-The max citizens has issues and is often 3-5 below what it actually is depending on what angle your tongue is at when you look at it
-Events I'm assuming should have raids in it? I'm not familiar with it

https://www.dropbox.com/s/tarrtjy2b1gzd31/TownHallDC.png?dl=0

**Comment by Raycoms** [comment]
I guess this is 1.12?

**Comment by ghost** [comment]
> 
> 
> I guess this is 1.12?

Yes, it is.

**Comment by Raycoms** [comment]
Yes, the 1.12 townhall GUI didn't receive the fix updates at the 1.15 version due to lack of time. We're currently only supporting the 1.15 version actively. Nonetheless, anyone is invited to port fixes and updates to 1.12 if they want to.

**Comment by ghost** [comment]
Alright, thanks for the info, I'll make a note that the 1.12 version isn't supported anymore. I look forward to 1.15.
