### ISSUE TITLE
Restaurant doesnt work well

### ISSUE THREAD

**Issue by bloodyraoul** [ldtteam/minecolonies#5273]
Each time I connect on my server, i see all citizen in the restaurant waiting for food.
I need to manually go to find food in each rack of the warehouse or in the worker huts and bring them to the restaurant myself.
![2020-06-23_09 00 06](https://user-images.githubusercontent.com/16031618/85403668-13aed680-b55e-11ea-8359-b4486f62e389.png)

citizen, especially guards grab all items they found and never put them back in the warehouse
they keep all eggs, feathers and steaks...very annoying

I put buckets in the cowboy hut....i find them back in the warehouse but without milk or cakes
backer seems to not do any bread

I use chunkloader to load my colony, I dont know if it can be linked to the problem

version : 
minecolonies-1.15.2-0.11.961-universal.jar

**Comment by Raycoms** [comment]
Chunk loaders don't work with minecolonies atm. The colony stops doing stuff when you're offline but the hunger will go down. So food won't get delivered while you're ofline. This is intentional for now.

**Comment by bloodyraoul** [comment]
I dont understand. It doesnt seem to work always the same between colonies...
On the same server, the @Diabolosman 's colony continue to do things when he's not connected : his building requests launched before disconnect are done in the morning when he connect again. He use the same chunkloaders and dont have any problem with his restaurant.
My colony seems to do exactly what you say : stop totally when i am offline

**Comment by Raycoms** [comment]
Is anyone who is officer in his colony online after he went offline?

**Comment by Raycoms** [comment]
(Doesn't have to be in his colony, but has to be online)

**Comment by bloodyraoul** [comment]
ho, yes, we are officer of each other colony

**Comment by Raycoms** [comment]
As long as an officer is online the colony continues working. But if no officer is online it stops. (To avoid for example raids when no ifficer is online but a colony is loaded)

**Comment by bloodyraoul** [comment]
ok, so, Diabolosman is generally connected before me, his colony works well
I'm connected just after he left, so his colony continue to work because i am officer
I disconnect
The next morning, diabolosman connect again, my colony should work because he's officer. but during the night, my colonist lost all their hunger, too bad for me....
why hunger continue to go down if the colony dont do anything ?

**Comment by Raycoms** [comment]
Because the colony is still loaded and hunger is ticked in the citizen and requests are ticked on the colony level. Potentially we could look into stopping this too though.

**Comment by Raycoms** [comment]
@someaddons what do you think? Should we stop hunger and illnesses while no officer is online too?

**Comment by DiabolosMan** [comment]
To add some info about what @bloodyraoul says, every morning, I have about 20 citizens stuck in hospital, most of them sharing the same bed (cf bug I already entered).

I think your suggestion about stoping hunger and illness while no officer online could fix the issue
