### ISSUE TITLE
help me !!

### ISSUE THREAD

**Issue by keylel1234** [ldtteam/minecolonies#5274]
my new version strturize 0.10.324-ALPHA and minecolonies-1.15.2-0.11.961-universal downlaod I added to the file and new forge version downloaded result CRASHED

**Comment by Raycoms** [comment]
forge version?

**Comment by ravenbuilder934** [comment]
I think it was 31.2.22

**Comment by Raycoms** [comment]
Downgrade to 31.2.8.
