### ISSUE TITLE
Waypoints not visible/rendering when using the Builder's Wand

### ISSUE THREAD

**Issue by nephilese** [ldtteam/minecolonies#5277]
# Before reporting please make sure that this issue was not reported yet (Check out similar issue suggestions).
## Also update to the latest alpha of both minecolonies and structurize before reporting

Version: Minecolonies-1.15.2-0.11.960 in the Valhelsia2 modpack

### Expected behavior

I was told that existing waypoints should be visible when using the Builder's Wand and selecting Decorations -> Infrastructure -> Waypoints.

### Actual behaviour

Well, nothing happens. They are not visible. 

### Steps to reproduce the problem

I tested this specifically by creating a waypoint and having my builder complete it, then immediately using the Builder's wand to setup another waypoint. The recently created one was not visible.

**Comment by Raycoms** [comment]
They are not invisble, they are disappearing. I got this on my list for tomorrow to fix.
