### ISSUE TITLE
Game unresponsive

### ISSUE THREAD

**Issue by cwg930** [ldtteam/minecolonies#5279]
# Before reporting please make sure that this issue was not reported yet (Check out similar issue suggestions).
## Also update to the latest alpha of both minecolonies and structurize before reporting

Version: minecolonies-1.15.2-0.11.961/structurize-0.10.324-ALPHA/forge-31.2.8

### Expected behavior

- game works normally

### Actual behaviour

- I can move around, place blocks, but nothing is interactable and all NPCs/mobs are frozen. Only a few chunks load. Block Entities don't do anything.
Colony blocks complain about not having their building and the town hall doesn't have a colony. Restoring from all the backups I had didn't change this. 

https://youtu.be/BtVGteX9s6U

### Steps to reproduce the problem

1. Honestly I have no clue
2. I've had this happen several times now, I got around it by deleting the region file where my colony is located but the past couple days I've spent more time repasting my colony in creative mode than actually playing.
3. It's not even a big colony compared to what I've seen, only like 14 villagers. 
4. Buildings are all medivaloak or medievaloakalternative. Town Hall1, Builder3, Delivery2x1,Delivery1x2,Warehouse2,Farm2,Mine3,Lumberjack3,Lumberjack1,Citizen3x1,Citizen2x2,Citizen1x2,Tavern1,Fisherman1,Smeltery1,Sawmill1,Several guardtower1 and guardtower2(forget exact count, not more than 5 though), Cook1,University1. All staffed except for the guardtowers, only 1 guardtower2 is staffed. Also lots of walls+a few gates and tower decorations, and a bunch of various road segments.
5. Custom modpack on twitch launcher, I have several other mods but the issue persists when minecolonies/structurize are the only mods. I can upload the modpack and world if needed.

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: https://gist.github.com/cwg930/ac1c600663e95dde4648e6b84586b748 not that it's any use
- crashlog: game says it crashed when I force close from task manager but doesn't produce a log

**Comment by Raycoms** [comment]
Does this happen in a new world too? Seems like your world corrupted? Does this also happen with only minecolonies?

**Comment by cwg930** [comment]
I haven't tried to reproduce it in a new world, but it has happened multiple times in the same world after deleting the region files+my colony with /mc colony delete. 

I've scanned the world files with https://github.com/Fenixin/Minecraft-Region-Fixer and it didn't find any issues, don't know that that's conclusive for saying the world isn't corrupted though. 

The youtube link in my report shows a demonstration of the issue with minecolonies 0.11.961 and structurize 0.10.324 as the only mods used.

Additional possibly important details I forgot in the first post: 
The world was originally on a dedicated server, where the issue manifests as the server crash detection kicking in due to the tick timeout, that is also where I've had it reoccur most often. Copying the world to singleplayer results in the issue as described+presented in the video. Reported the single player version of the issue because it seemed like it might be more relevant to the actual problem (world hanging). 
The issue has also started happening to my friend a bit after he started working on his colony (don't know his exact progress, but he said the last buildings he built the day before it happened to him were a mine, warehouse2, and guard tower).
 Logs from the server for one of the crashes: https://gist.github.com/cwg930/5287daeedfe90baf8db2b3dd360c4702

**Comment by someaddons** [comment]
can you zip up and send us the world?

**Comment by cwg930** [comment]
world: https://drive.google.com/file/d/1bSjbPEWohJdKIcNbPzFZRXN2pZZe9Rug/view?usp=sharing
and if it helps my custom modpack: https://drive.google.com/file/d/10xK9CcLZ8AvBbt2C527XNE8iJQl-wmP4/view?usp=sharing

My colony is located around -1800x, +or-200z(can't remember exactly)

**Comment by someaddons** [comment]
I'm not sure what you did to the world, but when trying it locally in singleplayer with just minecolonies/structurize its even crashing trying to generate a vanilla chunk. Which isnt anything minecolonies related as it does not touch generation at all. All minecolonies does is accessing the chunk where an entity is added to, not sure how you borked the world but that one should never be timing out.
