### ISSUE TITLE
GUI Not working?

### ISSUE THREAD

**Issue by TiborBrink** [ldtteam/minecolonies#5281]
Version: minecolonies-0.10.715-RELEASE-universal

### Expected behavior
It should show a GUI with the names of my citizens and I should be able to assign them accordingly.

### Actual behaviour
I don't see a GUI with the names of my citizens, I can't assign them and there is a texture missing. 

<img width="1440" alt="Schermafbeelding 2020-06-24 om 10 13 36" src="https://user-images.githubusercontent.com/67364402/85521360-6f339f80-b604-11ea-88b0-6a8a86a8d4f4.png">
<img width="1440" alt="Schermafbeelding 2020-06-24 om 10 16 29" src="https://user-images.githubusercontent.com/67364402/85521370-72c72680-b604-11ea-8e4f-449441cd995c.png">
<img width="1440" alt="Schermafbeelding 2020-06-24 om 10 16 49" src="https://user-images.githubusercontent.com/67364402/85521375-73f85380-b604-11ea-97fe-ec26e9ab55e4.png">

### Steps to reproduce the problem

It might be important to note that this mod is running on a server with a friend of mine, he has a fully working colony while mine doesn't work. On his screen he sees the complete GUI, citizen name, and able to assign them how he pleases. I was the second person to start a colony, far away from his, I am the only one that has this problem. I'm not sure how to recreate this problem as it just happens without indication why it happened.

**Comment by Raycoms** [comment]
Download latest alpha

**Comment by TiborBrink** [comment]
@Raycoms That's not helping, this is the latest available version for 1.14.4.

EDIT: Can you open this issue again please.

**Comment by Raycoms** [comment]
Ohh 1.14.4, we don't offer support for that version anymore unfortunately. Make sure you're not in a LAN game and if you need things fixed you'd have to update to 1.15.2 we unfortunately don't have the manpower to support multiple versions.

**Comment by TiborBrink** [comment]
That's rather unfortunate. I'm connected over the internet, not LAN. Do you think it's server sided or client sided?

**Comment by Raycoms** [comment]
Good question, never had that problem

**Comment by TiborBrink** [comment]
I am browsing similar problems on the forum, Minecolonies should work regardless of running Windows or iOS(mac) right?

**Comment by Raycoms** [comment]
Yes, that should not matter

**Comment by TiborBrink** [comment]
Alright! I've figured out how to fix the issue, might be some information to mention somewhere in the future, all I had the do was change the resolution, since I've got a retina-display, the resolution got all funky in Minecraft.

![Schermafbeelding 2020-06-24 om 11 06 42](https://user-images.githubusercontent.com/67364402/85527209-f6841180-b60a-11ea-9f49-5c0dd3f13b1b.png)
