### ISSUE TITLE
Minecolonies Villager AI Issue

### ISSUE THREAD

**Issue by Amunsul** [ldtteam/minecolonies#5282]
# Before reporting please make sure that this issue was not reported yet (Check out similar issue suggestions).
## Also update to the latest alpha of both minecolonies and structurize before reporting

Version: Structurize 0.10.324-ALPHA
Minecolonies 1.15.2-0.11.960-universal

### Expected behavior
 Villager performing job normally. 

-  Villager was working as deliveryman. 

### Actual behaviour

-  Villager should be moving from different structures taking materials to and from structures. Instead hes just standing in one spot. Right clicked him and hes reporting that he has an AI issue and i should report it to the mod authors. Tried recalling him back to delivery hut to see if that would reset him. He did wander off to get food but then just stood there again. Still stating he has AI issue. 

Additionally, i was able to fire the villager from his current job, delivery man, and then rehired him as farmer and he is no longer reporting the AI issue. I didnt try him in other positions prior to farmer so not sure if farmer specifically fixed it or just the act of firing/hiring fixed it? I didnt check in between firing and hiring to see if issue resolved so supposedly just firing may have resolved it. 

### Steps to reproduce the problem

Not sure. I dont know how it was triggered. 

1. 
2. 
3. 
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:  https://gist.github.com/Amunsul/85194494ade9dd487fe53f534d25efa1
- crashlog:  Game did not crash so crashlog was not generated.

**Comment by Raycoms** [comment]
That log is missing the exception.

**Comment by XenoMustache** [comment]
> That log is missing the exception.

`Game did not crash so crashlog was not generated.`

**Comment by Raycoms** [comment]
I mean, if the AI says this error it should be in the latest.log, if it's not then you sent me a too old or too new of a log that doesn't contain the error and I can't help you then.

**Comment by Raycoms** [comment]
Stale issue auto close
