### ISSUE TITLE
Lumberjack chopping logs in buildings

### ISSUE THREAD

**Issue by zoimos** [ldtteam/minecolonies#5286]
Version: 1.15.2-0.11.961

### Expected behavior

Lumberjack not chopping logs in his own house

### Actual behaviour

![](https://cdn.discordapp.com/attachments/620499986349555742/725408435415416915/2020-06-24_18.52.30.png)

### Steps to reproduce the problem

1. Base of tree outside hut range but nearby
2. Grows super large and a branch connects to building
3. watch lumberjack destroy his own house :D

**Comment by Raycoms** [comment]
This can happen and is incredible difficult to detect unfortunately (how trees are managed in minecraft).
At least you can repair the building.
