### ISSUE TITLE
Instant crash with build tool

### ISSUE THREAD

**Issue by H2O-Distributor** [ldtteam/minecolonies#5287]
Version: Minecolonies 0.10.771 release

### Expected behavior
Right click to build tool, and when selection for the building is made and should shart to build

### Actual behaviour
Game instacrashes with exit code -1

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: https://gist.github.com/H2O-Distributor/b2f4040e3672e67780efccc36f97ac54
 crashlog: https://gist.github.com/H2O-Distributor/f63910d219101713d6283c92e44e10af

Please help, Id love to play the mod and see all the buildings but I cant when it keeps crashing on me.

**Comment by Raycoms** [comment]
Update to latest alpha
