### ISSUE TITLE
Minecolonies AI Issues

### ISSUE THREAD

**Issue by Knight-Of-Solari** [ldtteam/minecolonies#5289]
# Before reporting please make sure that this issue was not reported yet (Check out similar issue suggestions).
## Also update to the latest alpha of both minecolonies and structurize before reporting

Version: minecolonies-1.15.2-0.11.960-universal
structurize-0.10.324-ALPHA

### Expected behavior

- Colonists performing jobs

### Actual behaviour

- Various colonists including the miner, deliveryman, and lumberjack stood around saying they had an AI error. Warehouse was supposed to be being upgraded by the builder, who stopped building but didn't say he had an error. Tried to fire and rehire all the colonists having issues with no success. Tried canceling and re-requesting warehouse upgrade with no success.

### Steps to reproduce the problem

I do not know how to reproduce issue as I am unsure what the caused the issue in the first place or what exactly the issue is.

1. 
2. 
3. 
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: https://gist.github.com/Knight-Of-Solari/47dcc4a774f75d9b5fad88b38414b68d
- crashlog: No crash log

**Comment by Raycoms** [comment]
Please update to 961.
