### ISSUE TITLE
Request System malfunction

### ISSUE THREAD

**Issue by LordDarkWolf** [ldtteam/minecolonies#5291]
# Before reporting please make sure that this issue was not reported yet (Check out similar issue suggestions).
## Also update to the latest alpha of both minecolonies and structurize before reporting

Version: minecolonies-1.15.2-0.11.961-universal

### Expected behavior
My miner asks for Oak Signs, the sawmill asks for planks and sticks, the deliveryman delivers them ...

### Actual behaviour
Request system requests logs while I have them in stock, better, I also have planks !

### Steps to reproduce the problem
1. Teach to Sawmill sticks recipe from Oak planks
2. Teach to Sawmill sticks recipe from Birch planks
3. Teach to Sawmill Oak planks from Oak logs
4. Teach to Sawmill Birch planks from Birch logs
5. Teach to Sawmill Oak Sign
6. Miner ask Oak Signs...

### Logs: Latest.log and crashlog at https://gist.github.com/
- latest.log: https://gist.github.com/LordDarkWolf/a6f6792b0dd18720091b7da5ae0783e7
- crashlog: no crash
![image](https://user-images.githubusercontent.com/33444937/85738420-51e3fb80-b700-11ea-8cef-aeb58b1eb7c5.png)
![image](https://user-images.githubusercontent.com/33444937/85738551-69bb7f80-b700-11ea-81f6-c33c51af3eb6.png)
![image](https://user-images.githubusercontent.com/33444937/85738648-79d35f00-b700-11ea-89ac-7cd388a764a5.png)
![image](https://user-images.githubusercontent.com/33444937/85738718-88217b00-b700-11ea-8327-36d52bae6468.png)

**Comment by Raycoms** [comment]
Duplciate yes, the open PR should fix this.

**Comment by LordDarkWolf** [comment]
a link please ?

**Comment by ravenbuilder934** [comment]
https://github.com/ldtteam/minecolonies/pull/5290 and https://github.com/ldtteam/minecolonies/issues/5246
