### ISSUE TITLE
2 Citizens stuck in their house

### ISSUE THREAD

**Issue by Rithenar** [ldtteam/minecolonies#5292]
# Before reporting please make sure that this issue was not reported yet (Check out similar issue suggestions).
## Also update to the latest alpha of both minecolonies and structurize before reporting

Version: 
MC 1.15.2 -0.11.960-Universal.jar
Structurize: 0.10.324-ALPHA.jar
Forge: 31.2.21

### Expected behavior

Citizens to go to their beds and sleep

- 

### Actual behaviour

- 
2 citizens are going into their house and path straight to a corner by the building block. I am using Asian style buildings, an dthe block where they stand used to be a barrel. I changed the block for wool in case that was making them stuck but they still go there. After a Client and Server restart, the citizens changed places with the one that was sleeping going to the stuck point, and one of the stuck citizens going to bed.  I believe it may be a pathing issue because when the citizens enter the house they go straight to that point.
UPDATE: It seems that they cannot see the beds because whichever citizen arrives first takes the far right bed. I broke the beds and placed them again but that didn't fix it.

![image](https://user-images.githubusercontent.com/9939332/85755108-43cbb600-b6d3-11ea-8970-c08da781cda4.png)

![image](https://user-images.githubusercontent.com/9939332/85755137-48906a00-b6d3-11ea-86c0-8124f7e87f54.png)

### Steps to reproduce the problem

1.  Wait until is night
2. go to their house
3. see them get stuck :/
4. ... Profit and head my head against the desk

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:  https://paste.ee/p/kT2t7
- crashlog:

**Comment by Raycoms** [comment]
If you push one of them away, will the other one walk out and they'll be fine?

**Comment by Raycoms** [comment]
OKay, I'll close this because it was a schematic problem having both beds occupied by other blocks.
