### ISSUE TITLE
Children aren't going to school

### ISSUE THREAD

**Issue by lebanni** [ldtteam/minecolonies#5296]
minecolonies-0.13.4-ALPHA-universal.jar
structurize-0.13.0-ALPHA.jar

The issue is not specific to this version.

The building is nordic level 1. The teacher has the same untouch stack of paper I gave him a while ago.

**Comment by MatthiasMann** [comment]
Pupils need to be hired at the school - but they don't get paid :P
If you have the town wide hiring mode set to manual, you should set the hiring mode of the school building to automatic.

**Comment by lebanni** [comment]
I thought it was only to hire the teacher. Thanks.
