### ISSUE TITLE
[0.13.4a] Chunk loading broken with Optifine

### ISSUE THREAD

**Issue by SkyeRise** [ldtteam/minecolonies#5297]
# Before reporting please make sure that this issue was not reported yet (Check out similar issue suggestions).
## Also update to the latest alpha of both minecolonies and structurize before reporting

Version: 0.13.4a

### Expected behavior

Chunks load with the occasional small issue (like in version 0.11) with the experimental Optifine. Optifine exp 30 had fixed a lot of chunk loading issues (ticket for that done by me there) but with new MC it is broken again.

### Actual behaviour

Chunkloading fails after only loading a few chunks.

### Steps to reproduce the problem

1. Play the game with Optifine exp 30 installed

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: 
- crashlog:

**Comment by Raycoms** [comment]
Not our fault
