### ISSUE TITLE
Deliveryman takes all. Farmers have not crops for planting.

### ISSUE THREAD

**Issue by Umiyaki** [ldtteam/minecolonies#530]
### Minecolonies version

1.11.2 delivered

### Expected behavior

- Farm - Deliveryman leave one stack each type of crop for the next planting.

### Actual behaviour

- Farm - Deliveryman takes all. Farmers have not crops for planting.

**Comment by Raycoms** [comment]
Fixed for vanilla crops, other issues existing for modded crops
