### ISSUE TITLE
Structurize 0.13.0-ALPHA isn't working.

### ISSUE THREAD

**Issue by HannahJ2000** [ldtteam/minecolonies#5300]
# Before reporting please make sure that this issue was not reported yet (Check out similar issue suggestions).
## Also update to the latest alpha of both minecolonies and structurize before reporting
I've already downloaded the alpha version of both mods in 1.15.2, but when I try to load Minecraft some screen comes up that says " Mod minecolonies requires structurize 0.13 or above. Currently, structurize is 0.13.0-ALPHA" I've tried everything that I can think of but nothing works. So I was wondering if you had a way to fix this.

Version: 
minecolonies:0.13.2-ALPHA , structurize:0.13.0-ALPHA
### Expected behavior
I hope to be able use the mod in this version.

- 

### Actual behaviour
After the mods load a screen comes up that says " Mod minecolonies requires structurize 0.13 or above. Currently, structurize is 0.13.0-ALPHA".

- right now I cant even get to the start screen of Minecraft

![image](https://user-images.githubusercontent.com/67448488/85873369-a2a63380-b796-11ea-8865-53b05e93ab5a.png)

### Steps to reproduce the problem

I don't know how or why this happened so I don't know if you can recreate this.
1. first I make sure that I have the correct mods in my mods folder 
2. then I open the Minecraft launcher
3. then I press play and then wait for Minecraft to load
4. then the screen comes up and I have to close Minecraft

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: 
[latest.log](https://github.com/ldtteam/minecolonies/files/4838140/latest.log)

- crashlog:

**Comment by Raycoms** [comment]
Did yout ry minecolonies-0.13.3-BETA-universal.jar  and later?

**Comment by HannahJ2000** [comment]
No I didn't. Thanks for the help!
