### ISSUE TITLE
stash information

### ISSUE THREAD

**Issue by cobaltthunderwing** [ldtteam/minecolonies#5301]
# Before reporting please make sure that this issue was not reported yet (Check out similar issue suggestions).
## Also update to the latest alpha of both minecolonies and structurize before reporting

Version: minecolonies-0.10.715-RELEASE-universal.jar

### Expected behavior

- stash information, not a bug per se, I would like to know in what version of minecolonies the stash came to be

### Actual behaviour

-  as per description, if the stash if after my current version then I need to update minecolonies, if it is in my current version, it is currently not craftable

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: 
- crashlog:

**Comment by Raycoms** [comment]
Update to latest alpha
