### ISSUE TITLE
Builder stays in his bed (at home) instead of going to hospital when sick

### ISSUE THREAD

**Issue by MatthiasMann** [ldtteam/minecolonies#5302]
Version: minecolonies-0.13.6-ALPHA-universal

### Expected behavior
Builder goes to hospital and lies on that bed

### Actual behaviour
Builder stays at his home and lies in his own bed when sick instead of going to the hospital.

When I then recall him to his hut, he goes to the hospital to get healed - but doesn't lie in that bed either - he stands next to the healer and eats his medicine.

### Steps to reproduce the problem
1. Not 100% sure - either needs to get sick while sleeping - or get sick before sleeping?
2. See the red gear above his head while lying in his bed (in a level 3 tavern in my case)
3. Recall him to his work hut
4. Watch how he now goes to the hospital but will not use that bed (it was free)
5. ... Profit

**Comment by ravenbuilder934** [comment]
The part about citizens not lying in the hospital beds happens to me as well, but not just after a citizen has been sleeping (I think).

**Comment by carlansor** [comment]
i experienced this as well but never saw it as an issue, since sometimes the doctor goes to the house of the ill person and proceeds to heal him/her. I even liked this in first place.

**Comment by ravenbuilder934** [comment]
> i experienced this as well but never saw it as an issue, since sometimes the doctor goes to the house of the ill person and proceeds to heal him/her. I even liked this in first place.

Wait, what? They do?!

**Comment by Raycoms** [comment]
That is intented yes, the doctor will then go to the home of the citizen and heal them.

**Comment by ravenbuilder934** [comment]
> That is intented yes, the doctor will then go to the home of the citizen and heal them.

AWESOME!

**Comment by MatthiasMann** [comment]
Ok, I had the case again (this time with my Lumberjack - also lives in the Tavern) - was sick and stayed in bed (over 2 Minecraft days) - but the healer did not visit. Do I need to do / research anything for home visits?

**Comment by Raycoms** [comment]
Might mean that the healer did not have the ingredients for healing at that moment.

**Comment by MatthiasMann** [comment]
He could heal the lumber jack directly once I recalled the lumber jack to his hut.

**Comment by Raycoms** [comment]
It is a bit randomized. So it can need a little bit of time until the healer takes care of a patience. On our server I sometimes notice patience in the hospital in bed for 2-3 days while the healer does the home visits =D
