### ISSUE TITLE
Can't create cactus planks

### ISSUE THREAD

**Issue by LordDarkWolf** [ldtteam/minecolonies#5303]
Version: minecolonies-0.13.7-ALPHA-universal

### Expected behavior
When I teach the recipe for cactus planks at Sawmill or Planter, then he adds it.

### Actual behaviour
It does not add, I have a message: "Unable to store th blueprint. Either the sawmill has no space for any more blueprints, or the blueprint doesn't correspond with its profession". Even if there is no recipe.
Or then I don't have the right worker ...

### Steps to reproduce the problem
1. Teach "Cactus plank" to Sawmill or Planter

### Logs: Latest.log and crashlog at https://gist.github.com/
- latest.log: no needed
- crashlog: no crash

**Comment by ravenbuilder934** [comment]
What level is your Sawmill and how many recipes does it already know?

**Comment by LordDarkWolf** [comment]
My Sawmill is level 3, I even tried to delete all my recipes, but it doesn't work anyway.

**Comment by ravenbuilder934** [comment]
Weird, I think I taught it to my Sawmill.

**Comment by LordDarkWolf** [comment]
I just did the test again, I deleted all the recipes from my sawmill, and I have the same message.

**Comment by PowerSchill** [comment]
I was able to add the recipe for cactus planks. Do you have any other mods installed that could be conflicting?
