### ISSUE TITLE
Guards run into sweet berries and stay there getting hurt

### ISSUE THREAD

**Issue by MatthiasMann** [ldtteam/minecolonies#5305]
Version: 0.13.7-alpha

### Expected behavior
Guards should avoid walking into sweet berries or walk quickly out again

### Actual behaviour
They walk onto the sweet berry and stay put until they either die or their armor breaks and the player rescue them

### Steps to reproduce the problem
1. Plant a few sweet berries where guards might find them (in my case it happens very seldom as they are in a mini park besides a path.
2. Wait for a guard to find the berries
3. Guards gets hurt and doesn't try to avoid the berries.
4. ... Profit

**Comment by Raycoms** [comment]
#4510

**Comment by MatthiasMann** [comment]
Sweet berries are vanilla Minecraft items - not from some other mod.

**Comment by Raycoms** [comment]
Oh, really? I've never seen them.

**Comment by Raycoms** [comment]
Will include in my next PR
