### ISSUE TITLE
Builders seem to have issues placing items again

### ISSUE THREAD

**Issue by lunadragnstar** [ldtteam/minecolonies#5307]
# Before reporting please make sure that this issue was not reported yet (Check out similar issue suggestions).
## Also update to the latest alpha of both minecolonies and structurize before reporting

Version: .960 + 

### Expected behavior

- Builder should just get the items he needs and places them.

### Actual behaviour

- Seems the builder gets stuck when placing certain items, I've seen issues mostly with armor stands (with and without arms) and item frames. The problem is that they don't always have issues. Medieval and Fortress are great ones to test with. Sometimes it is an issue with fulfilling the request at the builder hut, or them seeing the items in the racks/chests. Or even sometimes their own inventory. I've placed needed items in all locations and they don't seem to see them, so they have issues placing them.

### Steps to reproduce the problem

A good sample to try is Medieval Oak Alternative Townhall from level 3 --> level 4, others are having issues with Fortress Guard towers from level 4 --> level 5

**Comment by Raycoms** [comment]
Yeah, it's because those are armor stands with old data. The armor on the armorstand still has like 1.12 data.

**Comment by Raycoms** [comment]
So that causes issues in 1.15
