### ISSUE TITLE
new AI error, now it's the sifter's turn

### ISSUE THREAD

**Issue by harmalom** [ldtteam/minecolonies#5309]
the sifter shows an error message in its AI, although apparently it still works normally, so it seems when you look and listen to it, but the message is there

![2020-06-28_07 47 44](https://user-images.githubusercontent.com/67077986/85949974-7bc73900-b91f-11ea-907b-b37e16773834.png)

https://gist.github.com/harmalom/644d8eb6aac65dbd3fa90afda3428e61

**Comment by Raycoms** [comment]
Will be fixed with my upcoming PR too
