### ISSUE TITLE
My planter doesn't plant what I want

### ISSUE THREAD

**Issue by LordDarkWolf** [ldtteam/minecolonies#5310]
Version: minecolonies-0.13.7-ALPHA-universal

### Expected behavior
After unlocking Plant 2, I want to have cactus and sugar cane.

### Actual behaviour
I can only configure one plant, I configure cane sugar, but my planter plant of cactus and bamboo.

### Steps to reproduce the problem
1. Unlock Plant 2
2. Confifure Planter for Sugar Cane
3. Wait

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: no needed
- crashlog: no crash
![image](https://user-images.githubusercontent.com/33444937/85957542-840a8d00-b98e-11ea-9a81-49fa4ea4df6d.png)
![image](https://user-images.githubusercontent.com/33444937/85957548-9258a900-b98e-11ea-967c-780a596fbacd.png)
![image](https://user-images.githubusercontent.com/33444937/85957555-a4d2e280-b98e-11ea-8e31-e00e8d8e02f4.png)

**Comment by MatthiasMann** [comment]
That is intended - when you researched the double trouble the UI selects what is NOT planted.

**Comment by Raycoms** [comment]
^
