### ISSUE TITLE
stash sometimes doesn't let the delivery people take from it

### ISSUE THREAD

**Issue by LuckyFalkor** [ldtteam/minecolonies#5313]
# Before reporting please make sure that this issue was not reported yet (Check out similar issue suggestions).
## Also update to the latest alpha of both minecolonies and structurize before reporting

Version: 
structurize-0.13.4-ALPHA
minecolonies-1.15.2-0.13.28-BETA-universal
forge-1.15.2-31.2.8

### Expected behavior

1. drop items in stash
2. delivery person comes by and picks up the items
3. items in stash are no longer visible

### Actual behaviour

1. drop items in stash
2. delivery person comes by.
3. items are still visible in the stash
4. items never make it to the warehouse

### Steps to reproduce the problem

does not seem to always happen, though when it does it stays happening, the only fix is to break the stash and place it again.
things i have done to isolate the issue:
when the stash is working, i can break it and the items contained spill out (as expected).
when the stash is not working, breaking the stash does not give the items back and they are lost forever.
this losing of items occurs even for items placed in the stash before the delivery person gets to it.

when i notice the issue, i take everything out manually and break the stash and place it back down, then add my items to it again.

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: https://gist.github.com/LuckyFalkor/b318ce1fa4944bcee621b70dfce3519d
- crashlog: nothing crashes, so no crash log.

**Comment by Raycoms** [comment]
Is there a way to reproduce this?

**Comment by Raycoms** [comment]
Does restarting fix it?

**Comment by patgoull** [comment]
I had the same issue sometimes. In my case, it was the glassblower making 8 panes when 4 were requested. It's ok since the recipe produces 8 but the delivery man never goes to pick the 4 up for the builder request. He doesn't go put them in the wharehouse either.

**Comment by patgoull** [comment]
Happening quite often now for me. Blacksmith makes requested tool and put it in his stash and no one come to deliver it to it's builder. Stairs for stonemason,etc. Even on minecolonies-0.13.10-ALPHA-universal.jar

![image](https://user-images.githubusercontent.com/25259519/86247973-3b63f700-bb7b-11ea-89c0-19f97047ebd0.png)

**Comment by Raycoms** [comment]
yeah in the crafters this can happen. That is a problem we've almost solved now. But in the stash, that is new for me

**Comment by patgoull** [comment]
Oh I totaly missread ... I'll delete my message they have nothing to do with the stash.

**Comment by LuckyFalkor** [comment]
> Is there a way to reproduce this?

I have not been able to reproduce it reliably.
If I had to guess, it seems to happen more often if I fill up at least a whole row in one shot.
Another player's theory is it happens more often when placing stuff in the stash when everyone is in bed.

**Comment by Raycoms** [comment]
I don't need it reliably. I need a way in 1 out of 10 to have it happen.

**Comment by LuckyFalkor** [comment]
> Does restarting fix it?

I will have to test that next time it happens.
I try not to restart the server if I can help it as others are often on when it happens. I have been just emptying it, breaking it, and replacing it to get it working again lately.
If I have to, I'll spin up a copy of the server in a test environment, though it might have to wait till this Monday.

**Comment by LuckyFalkor** [comment]
> I don't need it reliably. I need a way in 1 out of 10 to have it happen.

Well my setup right now is a level one warehouse and four level one delivery huts.
Then drop in like ten different items of various amounts a few times.
it might also be occurring as a result of dropping a bunch of items and after some buy not all of picked up, drop some more.

**Comment by LuckyFalkor** [comment]
sorry for the late reply.
had a chance to watch the logs while the issue was happening finally and this keeps coming up when a delivery person tries to take from the stash.

`Fetching packet for removed entity ExperienceOrbEntity['Experience Orb'/723410, l='stuckInside', x=459.52, y=63.50, z=54.22]`

this error does not come up when the stash is working properly.

**Comment by LuckyFalkor** [comment]
> 
> 
> Does restarting fix it?

the issue had cropped up during a time that restarting the server was possible.
it did not fix the issue and putting item into it does not trigger the "so&so will do a pickup soon" message.
again breaking the stash and placing it again temporarily fixes it.

as luck would have it, after breaking the stash, placing it, and trying it again with 40 paper; the delivery person came by and suddenly had a big issue.
i have added the log file to the original post with the issue starting out right at the bottom.
here is it as well: https://gist.github.com/LuckyFalkor/b318ce1fa4944bcee621b70dfce3519d

the delivery person name is Lisa V. Asger that had the error if you want to do a find for it.

i went and clicked the "this will have to do for now" button and she did take the paper and the stash was empty.

**Comment by LuckyFalkor** [comment]
_well my server was having the issue then i updated to the latest (1.15.2-0.13.21.1) and it fixed itself.
i am hopeful the issue is corrected now actually._

EDIT: yeah the issue is still happening.

**Comment by LuckyFalkor** [comment]
this issue is still happening with the 0.13.28-BETA-universal version.
it seems to happen more, it seems, if i put something in the stash during the night when the NPCs are in bed.
