### ISSUE TITLE
annoying bug 

### ISSUE THREAD

**Issue by abdullamu** [ldtteam/minecolonies#532]
### Minecolonies version

version 6.2 

### Expected behavior

- all workers do their job same as before i update to 6.2

### Actual behaviour

- no worker work just wondering around nothing helps killing them firing them hiring them 

### Steps to reproduce the problem

i have city with all workers working just fine beautifully organized everyone know what to do when to do, until i updated to 6.2 all workers stopped doing their job and just wondering around ii killed them all new spawned do the same just wounder like npc without job they say nothing and do nothing.

btw others have encountered this bug while updating but i didnt see anyone helping them.

**Comment by Raycoms** [comment]
Can you test if it still happens with this version:
https://www.dropbox.com/sh/9cnqcjl0nan57cy/AAAc33E4xWoKz16l2JJZlwlha/branch/feature/more-anti-griefing?dl=0&preview=minecolonies-universal-1.10.2-0.6.2543.jar

When did you update to 6.2?

2017-01-31 13:37 GMT-02:00 abdullamu <notifications@github.com>:

**Comment by abdullamu** [comment]
same behavior nothing changed unfortunately.

**Comment by Raycoms** [comment]
can you send us your log?

2017-01-31 15:59 GMT-02:00 abdullamu <notifications@github.com>:

**Comment by abdullamu** [comment]
i think this morning maybe couple of hours after the update pushed i updated my mod because i keep checking if the mod updated for new features.

http://www.filedropper.com/logs_24

**Comment by Raycoms** [comment]
can you upload here directly or use pastebin?

2017-01-31 16:09 GMT-02:00 abdullamu <notifications@github.com>:

**Comment by abdullamu** [comment]
I tried here it doesnt allow me says not supported pastebin which file name exactly you need ? Because there's in tge log file couple

**Comment by Raycoms** [comment]
latest.log and fmllatest.log

2017-01-31 17:50 GMT-02:00 abdullamu <notifications@github.com>:

**Comment by abdullamu** [comment]
http://pastebin.com/SGG1RR61 last


the fml last is 7 mb which is why i couldnt upload it here or in pastebin but i upload it to my drive 
https://drive.google.com/open?id=0B0Z9E3JbjOxAcUxfSlRKdnN3dEk

**Comment by Raycoms** [comment]
hmm couldn't find anything in the log which shows anything relating to your
issue.
They really just stand around and do nothing? Don't go to work anything?
Might it be raining?

2017-01-31 18:52 GMT-02:00 abdullamu <notifications@github.com>:

**Comment by abdullamu** [comment]
what is the behavior i should expect when its raining ? going to home or wondering ? because what they do is behave exactly like NPC without job i'll revert to the last working version and check again and let you know.

**Comment by Raycoms** [comment]
They wander around like zombies if it's raining, like people without a job.

2017-01-31 19:44 GMT-02:00 abdullamu <notifications@github.com>:

**Comment by abdullamu** [comment]
ok the test result are up and seems promising.
first while i was writing my last post i was cleanning the pack and found out that there was mod preventing rain or something around that meaning, i deleted it than downgraded to 6.1 run the pack voala raining toggled raining off they started working again like before.

exit enable the version you gave me, and they continue to work.

now to solve this problem so next time so no one will come complaining and waste your and their time it would be helpful to mention this in the wiki and when its raining the npc say something and type it in chat is better or any indication which i think some npc said something about rain which is why i was searching for the mod which prevent raining visual or sound because its seems to be popular among modpacks
