### ISSUE TITLE
Builder AI error java.util.NoSuchElementException: null at java.util.ArrayDeque.getFirst(Unknown Source)

### ISSUE THREAD

**Issue by patgoull** [ldtteam/minecolonies#5321]
Version: minecolonies-0.13.10-ALPHA-universal

Happened to one of my builder immediatly after updating and restart. He has a citizen house started before the update.

latest.log

https://gist.github.com/patgoull/d2cad8d2b1c3711c1667cfb791e1bd36

**Comment by Raycoms** [comment]
Will be fixed by: https://github.com/ldtteam/minecolonies/pull/5320

**Comment by harmalom** [comment]
The same, the errors of the sifter follow and now the builder's is added.

Version:
minecolonies-0.13.10-ALPHA-universal
structurize-0.13.4-ALPHA

![2020-07-01_14 01 28](https://user-images.githubusercontent.com/67077986/86282760-77ac4d00-bba5-11ea-9b9e-90b03e679b03.png)

latest.log
https://gist.github.com/harmalom/4763871a9d5ceba3933dee8e995a3133
