### ISSUE TITLE
Workers keep unnecessary item in their inventory

### ISSUE THREAD

**Issue by lebanni** [ldtteam/minecolonies#5322]
minecolonies-0.13.10-ALPHA-universal.jar
structurize-0.13.4-ALPHA.jar

This is the healer personal inventory :

![2020-07-01_23 43 29](https://user-images.githubusercontent.com/2799575/86294685-5e32f180-bbf5-11ea-8f87-557cc71c975d.png)

and here is one builder's rack :

![2020-07-01_23 45 50](https://user-images.githubusercontent.com/2799575/86294774-84f12800-bbf5-11ea-8551-c7f2c3cd4c0b.png)

**Comment by Raycoms** [comment]
and dmen passed there and picked up things several times? And the healer already dumped?

**Comment by lebanni** [comment]
His chest is empty and he never dumps his inventory, so the dmen have nothing to pick up. They only deliver what is needed by the healer. I checked the researchers, for example, who don't dump either, and the cook's rack which has several stacks of leather.

**Comment by Raycoms** [comment]
the healer will dump, but rarely

**Comment by Raycoms** [comment]
when you click on the cook, to ask the dman to come by, will he take those things?

**Comment by lebanni** [comment]
I asked for a pick up from the dman, had the confirmation in the chat, dman came but picked up nothing.
