### ISSUE TITLE
why are my builder not building both tavern and townhall?? (1.15.2)

### ISSUE THREAD

**Issue by aatgi** [ldtteam/minecolonies#5324]
# Before reporting please make sure that this issue was not reported yet (Check out similar issue suggestions).
## Also update to the latest alpha of both minecolonies and structurize before reporting

Version: 

### Expected behavior

- 

### Actual behaviour

- 

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: 
- crashlog:

**Comment by Raycoms** [comment]
Same as #5321
