### ISSUE TITLE
Waterlogged racks and construction tape

### ISSUE THREAD

**Issue by ravenbuilder934** [ldtteam/minecolonies#5328]
From AravanFox on Discord:

https://discord.com/channels/139070364159311872/620499986349555742/728326267685830656

**Comment by Raycoms** [comment]
Please screenshots and description and not links to discord.

**Comment by ravenbuilder934** [comment]
The stuff on Discord is all I have, aravan didn't want to make it herself

**Comment by Raycoms** [comment]
Will need more info for an issue then.
