### ISSUE TITLE
Crashing when interacting with builder

### ISSUE THREAD

**Issue by SheepyBuckett** [ldtteam/minecolonies#5329]
Version: minecolonies-0.13.13-ALPHA-universal.
structurize-0.13.4-ALPHA
forge-31.2.29

### Expected behavior
Fulfilling a builder request

### Actual behaviour
As soon as I right click the game crashes and give me:

java[29928:1432857] [JRSAppKitAWT markAppIsDaemon]: Process manager already initialized: can't fully enable headless mode.
AL lib: (EE) alc_cleanup: 1 device not closed

[Log](https://gist.github.com/SheepyBuckett/7b4ba50764e9058c857bd1677913dbf9)

### Steps to reproduce the problem
Right-click on the builder (there doesn't have to be a notification or request}
Game will close
Get crash log
Easy

**Comment by Raycoms** [comment]
Can you reproduce this?

**Comment by Proy777** [comment]
I also tried to fulfill a request however it only crashed minecolonies not the whole Minecraft. As in the villagers are frozen and I can't fix it.

**Comment by Raycoms** [comment]
Crashlog?

**Comment by Raycoms** [comment]
no answer in 2 weeks, closing
