### ISSUE TITLE
[request] picketing npcs

### ISSUE THREAD

**Issue by kreezxil** [ldtteam/minecolonies#533]
Since the npcs appear to be on strike most of the time, I thought it would be fitting that when they are standing waiting for me to craft that crystal ball for which to read their minds, they could actually be patrolling the build area carrying signs that say something like:

"No [thing], No work!"

"I can't work with this [thing]"

"<player> sucks, we need [thing]"

"[thing] [amt] to save the world!"

etc...

Then all I have to do is read the sign to get them going again.

**Comment by abdullamu** [comment]
good idea but the sign thing is not fitting they are not protesting but bubble over their head like they are chatting with each other and we can see read it .

**Comment by ProsperCraft** [comment]
Something like this...https://mods.curse.com/mc-mods/minecraft/235520-chat-bubbles

**Comment by abdullamu** [comment]
yes this will help alot so the player will be more informed of whats going on especially in a rainy day @Raycoms :p

**Comment by Raycoms** [comment]
Actually we're planning on giving them rainy day voices. The fisherman and
woman do actually already talk about that rainy day. (in voice)
But we should also add it to the wiki, that's right.

2017-01-31 20:38 GMT-02:00 abdullamu <notifications@github.com>:

**Comment by Raycoms** [comment]
I'd say when you run into them (like collide with them)
we could have them provide a "bubble" with the "last up to".
We could have a textField in each citizen with "lastUpto" which we can set in different jobs like "waiting for x" "clearing x for y" "fishing" "gathering" etc.

**Comment by kreezxil** [comment]
That would be awesome. It's the kind of information I'd want from my
citizens as their colonial magistrate.
