### ISSUE TITLE
AI error on Dman. The given token is not registered as a request to this manager (0.13.14)

### ISSUE THREAD

**Issue by patgoull** [ldtteam/minecolonies#5331]
Version:  minecolonies-0.13.14-ALPHA-universal

getRequest and onRequestedRequestComplete

Latest.log

https://gist.github.com/patgoull/69e37d05b5968549f2343a8e9c4782d4

**Comment by dtupitza** [comment]
This issue is present in minecolonies-0.13.247-ALPHA-universal.jar
