### ISSUE TITLE
Crash on world loading (Ticking Entity)

### ISSUE THREAD

**Issue by 3x1at1on** [ldtteam/minecolonies#5332]
# Before reporting please make sure that this issue was not reported yet (Check out similar issue suggestions).
## Also update to the latest alpha of both minecolonies and structurize before reporting

Version: Minecolonies 0.13.14-Alpha / Structurize 0.13.4-Alpha
Minecraft: 1.15.2
Forge: 31.2.30

### Expected behavior
World loading normally

### Actual behaviour
Game crashes on world loading with Ticking entity error

### Steps to reproduce the problem

1. Minecolonies installed
2. Have builder, farmer, sheep herder and lumbar jack.

### Logs: Latest.log and crashlog at https://gist.github.com/
- latest.log: https://paste.ofcode.org/XpeuDy5jsSpHffLkjXiLki
- crashlog: https://pastebin.com/rujF6m5D

**Comment by Raycoms** [comment]
Yeah, that's a forge problem. Happens occasionally.
