### ISSUE TITLE
Builder requests -25 Dirt

### ISSUE THREAD

**Issue by MatthiasMann** [ldtteam/minecolonies#5335]
Version: minecolonies-0.13.14-ALPHA-universal

### Expected behavior
Builder is building Medieval oak alternative sawmill level 4

### Actual behaviour
Builder is requesting -25 Dirt :/
![2020-07-04_00 58 59](https://user-images.githubusercontent.com/6777029/86500545-2b723000-bd92-11ea-805e-0b02b31e34b8.png)

### Steps to reproduce the problem
1. Upgrade sawmill from level 3 to 4
2. Give the builder all materials except dirt (dirt is available in the warehouse)
3. At some point (38%) he requested -25 Dirt
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/
There are no messages from Minecolonies (or Structurize) in either latest or debug log except the MD5 hash sums of the schematics when I queued new build jobs. The rest are journey map, chat and other mod debug messages.

**Comment by Raycoms** [comment]
oh weird, I'll add a count check.
