### ISSUE TITLE
Minecolonies-0.13.14-ALPHA-api.jar shows up as NOT a valid jar file!

### ISSUE THREAD

**Issue by roadblockx** [ldtteam/minecolonies#5336]
I posted a question (https://github.com/ldtteam/minecolonies/issues/5333#issue-650776099) where I went over an issue I was experiencing with the delivery guy and builder in Minecolonies.  A quick reply by raycoms said to "download .14" and then promptly closed out the post.  Imagine my surprise when, after downloading .14, it shows up as NOT a valid jar file and thus the issue isn't closed.

Went to ((https://www.curseforge.com/minecraft/mc-mods/minecolonies/files/2995436) and used this link to download the .14 (https://www.curseforge.com/minecraft/mc-mods/minecolonies/download/2995437).

The screenshot with corresponding error message in MC.
![IMG_5767](https://user-images.githubusercontent.com/3145653/86501620-8bec7780-bd68-11ea-9999-78a0522014c9.jpg)

Is there anyone that is available to work through this issue rather than a fire and forget reply?  I would appreciate it.

**Comment by MatthiasMann** [comment]
The -api.jar is not the mod - it's an API file you use for developing an addon mod.

**Comment by roadblockx** [comment]
Cool.  Where is the .14 raycoms mentioned?

**Comment by roadblockx** [comment]
Link to the curseforge page that has that mod and related downloads- https://www.curseforge.com/minecraft/mc-mods/minecolonies

"Download .14" is a little vague.

**Comment by roadblockx** [comment]
I'm starting to see a pattern here.  Just looking for a little help/direction beyond a coy reply.

**Comment by ravenbuilder934** [comment]
Here's .14: https://www.curseforge.com/minecraft/mc-mods/minecolonies/files/2995436
The devs can only work on the mod in their free time, so they might be busy right now.

**Comment by roadblockx** [comment]
> Here's .14: https://www.curseforge.com/minecraft/mc-mods/minecolonies/files/2995436
> The devs can only work on the mod in their free time, so they might be busy right now.

I fully understand and respect that.  I'd rather a reply with a link like you posted or if someone is busy, perhaps it's better not to reply at all.  You were so much more personable.  .14 doesn't help anyone and as someone that wants to donate to those that put this mod together that I've (along with my family) have enjoyed, it seems only fair.  But it's tough to with the previous interactions.

There's enough BS in the world right now, we can all agree.  Let games be our escape.  Thanks for being decent/checking into your link and suggestion now.

**Comment by ravenbuilder934** [comment]
No problem. By the way, you might get faster replies/ongoing support if you went on the [discord server](https://discord.minecolonies.com).

**Comment by roadblockx** [comment]
> No problem. By the way, you might get faster replies if you went on the [discord server](https://discord.minecolonies.com).

Much appreciated!

Updated the server and local MC.  The .14 is running but I continue to have the issue where the delivery woman wants a warehouse, the builder wants the delivery person and nothing is getting done.

**Comment by roadblockx** [comment]
By the way, if I click on "request pickup" from the builder's hut, I get "pickup unavailable, pickup already in progress"

Never used discord server.  Guess it's an evening of trying new things.  I appreciate the assistance.

**Comment by roadblockx** [comment]
When building the warehouse, craft a delivery guy hut and give it to the builder.  Seriously, don't over think it (like I did).

**Comment by roadblockx** [comment]
Thanks Raven
