### ISSUE TITLE
Miner gets stuck after digging and before placing torch

### ISSUE THREAD

**Issue by Mekle001** [ldtteam/minecolonies#5339]
Version: minecolonies-0.13.16-ALPHA-universal.jar

### Expected behavior

- Miner digging tunnels everywhere, and bringing back that sweet, sweet ore. 

### Actual behaviour

- Miner digs out a node, places the support structure, and then stops before placing the torch. Sometimes he'll run back and forth between the shaft down, and the node he's working on.  Citizen Info shows him alternating between idle and check mineshaft. 

### Steps to reproduce the problem

1. Build and hire a miner
2. Let them dig down as far as they can for the level of miner, and start digging nodes
3. Will get hung on first node, or if you've upgraded next node. 
4. ... Profit

**Comment by jelaw21** [comment]
Started a world in minecolonies-0.13.14-ALPHA-universal.jar (Enigmatica 5) and saw this exact behavior, updated to minecolonies-1.15.2-0.13.21.1-ALPHA-universal.jar in same world and still see behavior. Do I have to make a new world to see corrected behavior?
