### ISSUE TITLE
Fisherman bugged! Fisherman forgot how to reel in fish! :O

### ISSUE THREAD

**Issue by Dragolance117** [ldtteam/minecolonies#5341]
Hey fellow minecolonists !

I have enjoyed minecolony a lot recently however i have now run into this **_strange bug_**.

After fishing without problems for about 4-5 hours (fished up about 2 stacks of fish and some random other loot), my fisherman is now **unable to reel in any fish** ! As you can see from the picture below she is able to throw her fishing line and it is making the standard "splashing" animation. However the fish never bites and thus she is stuck there, waiting eternally. Normally after throwing the fishing line, water particles move towards the fishing line and make it sink, at which point you reel in, this never happens to the fisherman's line.

Fisherman specifics:

- She is using a normal unenchanted fishing rod. I tried giving her a new fishing rod but this changed nothing to the bug. She did use an enchanted fishing rod once without problems I believe (this was long before the bug happened).

- She is fishing in a vanilla river biome, right next to her hut.

- The fishermans hut was lvl 1 when the bug occurred, I tried levelling it to lvl 2 but that did not help.

- The fisherman is lvl 6 and has not gotten a single drop of xp towards lv 7. I think this is because her level was capped at lvl 6 due to her hut being lvl 1 when the bug occurred and since then she has not gotten any fish and thus no xp.

- I can use the "Get in the bucket" mod to pick up the fisherman and then put her down again. This resets the fishing line but then she just throws a new fishing line and the same thing happens.

- Strangely enough I think that the bug occurred after I used a fishing rod myself for the first time. Perhaps me using a fishing rod made the fishermans fishing rod unable to attract fish?

Technical specifics:

- I am using the "Better Than Minecolonies Getting Started" modpack by Kreezxil

-  This is minecolonies version "0.10.715 -RELEASE" I believe

- As far as I know, nothing in this modpack is preventing her from reeling up fish. I can fish myself without problems.

- I have not had any technical difficulties so far, this is purely a gameplay bug.

![Fisherman](https://user-images.githubusercontent.com/67859381/86530267-95382a00-beb7-11ea-97a9-4d1585c0cf74.png)

**Comment by Raycoms** [comment]
This is a very very very old version. Please update to the newest where this should work.
