### ISSUE TITLE
Builder places none to at most single digits worth of blocks before going to get more.

### ISSUE THREAD

**Issue by jt1399** [ldtteam/minecolonies#5350]
Version: 
minecolonies-0.13.14-ALPHA-universal.jar
structurize-0.13.4-ALPHA.jar
### Expected behavior

The builder places everything they bring with them before heading back for resources.

### Actual behaviour

They only place a few blocks and then run back for resources even though they could be placing more.

https://youtu.be/hKKBIszK1XE
### Steps to reproduce the problem
Outside of this only started when I went to upgrade the fortress university to tier 3 I have no clue whatsoever as to how to replicate this.

### Logs: Latest.log and crashlog at https://gist.github.com/
https://gist.github.com/jt1399/27e111f8339f132195552327ccd2cf52

**Comment by Raycoms** [comment]
Try the newest please.

**Comment by jt1399** [comment]
Is the next update far off? It's on a server and a mod pack and I have no way of replicating this...so I have to talk the pack dev into updating :/
