### ISSUE TITLE
Crash to desktop when knight dies

### ISSUE THREAD

**Issue by NilsMoller** [ldtteam/minecolonies#5353]
# Before reporting please make sure that this issue was not reported yet (Check out similar issue suggestions).
## Also update to the latest alpha of both minecolonies and structurize before reporting

Version: 0.13.18-ALPHA

### Expected behavior

1. Knight dies.
2. Death message in chat.
3. Game continues as normal.

### Actual behaviour

1. Knight dies.
2. Death message in chat.
3. Game crashes to desktop.

### Steps to reproduce the problem

1. Get a knight to die
2. See the message in chat of them dying
3. Crash to desktop

### Logs: Latest.log and crashlog at https://gist.github.com/

[latest.log and crashlog](https://gist.github.com/AydenWasTaken/e1ddde18db11c0cf882b7cd2b7b3c20a)

**Comment by Raycoms** [comment]
Can you reproduce that?

**Comment by NilsMoller** [comment]
> 
> 
> Can you reproduce that?

It has been happening for a while with different knights. Currently trying it in a test world to see if its just the guard tower knight, the barracks tower knight or both.
EDIT: No, i can't reproduce this in either a test world or the world it was happening in. Does that mean it is specific to that world? What could be causing it? Regardless, i will take this to the discord server. My apologies for posting it here.

**Comment by Raycoms** [comment]
There might've been some corrupted requests in the other world. You could try to do a request-system-reset and check if that solves it, in the first world too.
