### ISSUE TITLE
Workers working but not crafting anything

### ISSUE THREAD

**Issue by lebanni** [ldtteam/minecolonies#5354]
minecolonies-0.13.20-ALPHA-universal.jar
structurize-0.13.4-ALPHA.jar

I didn't check every crafter but the sawmill has the same issue.

https://youtu.be/gxbJuF7wcWM

**Comment by frankpbrady** [comment]
I'm seeing the same issue with both the sawmill and stone cutter.  Tried requestsystem-reset-all, firing and re-hiring, restart, cancelling and restarting builds, but behavior continues.

minecolonies-0.13.21-ALPHA-universal.jar
structurize-0.13.0-ALPHA.jar

**Comment by antihutka** [comment]
I noticed this issue when I upgraded from 0.13.8 to 0.13.20. It looks like crafters move their materials from their inventory to the building before the crafting cycle finishes, which causes it to fail. Putting more materials into their inventory manually right before the crafting cycle finishes allows them to craft one item successfully.
