### ISSUE TITLE
Enchantment Glint Crash on Login

### ISSUE THREAD

**Issue by Divineaspect** [ldtteam/minecolonies#5356]
Version: 
Forge 31.2.20
minecolonies-0.13.9-ALPHA
structurize-0.13.4-ALPHA

### Expected behavior
Rendering modified enchantment glints as expected, or perhaps not at all.

### Actual behaviour
Client Crash on login to server

### Steps to reproduce the problem
Give Modified Enchanted Items to Minecolonists
On a Server
Log into Server

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: 
- crashlog: https://pastebin.com/ApYtfGbh

**Comment by Raycoms** [comment]
Modified enchantement glints?

**Comment by Divineaspect** [comment]
such as from quark

**Comment by someaddons** [comment]
we're  using the vanilla mob/item renderer, if that one is crashing report to quark which modifies it

**Comment by Divineaspect** [comment]
I am in fact reporting to everyone who appears in it, because it seems to be one hell of a tangled crash log.

**Comment by Raycoms** [comment]
I'll close this. I dug into this. And this is definitely not on us but on one of those coremods.
