### ISSUE TITLE
Suggestion: Tavern Doesn't Count For Creating Children

### ISSUE THREAD

**Issue by MaxAstro** [ldtteam/minecolonies#5357]
Considering its limited level and non-scaling number of beds, the Tavern seems to play an early-game role as a place to get your initial four colonists to stop complaining about the lack of beds.  Ideally, it seems like you would then switch over to using houses instead, which allow for higher level colonists.

I'm currently at the point that I'd like to make that transition, but I'm running into a problem: Every time I build a new house, the people in my tavern immediately create a child to occupy it.  Since I currently have three men and three women in my colony, there's no combination of people I can put in the tavern to stop this from happening.

Since it seems a little odd that someone who doesn't even have their own house would start a family in the first place, maybe colonists living in the Tavern could be excluding from creating children?  That would smooth the transition from the Tavern to actual housing.

**Comment by ravenbuilder934** [comment]
#4535 please
