### ISSUE TITLE
Builders, delivery, lumberjack, miner displayed error and are now no longer working

### ISSUE THREAD

**Issue by CaptainMorganX5** [ldtteam/minecolonies#5358]
Version: I believe it was minecolonies-1.15.2-0.11.956-universal.jar
I just upgraded and tested 0.13.21 to see if that would fix the issue but it didn't.

### Expected behavior
The builders, delivery, lumberjack, miner would be working as usual.

### Actual behaviour
I think the miner was the first to have an alert bubble above their head that when I went to talk to them said something about "my AI has encountered an issue...etc". The lumberjack later said the same thing. Since then the builders, delivery, lumberjack, and miner have stopped working. I've tried updating the version, delivering materials my self, and recalling all colonists but the issue persists. Researchers, guards, fisherman, farmer, and everyone else in the colony seem to be working fine. 

### Steps to reproduce the problem
I have no idea, here's loosely was happening before: The researchers finished the first research about ore veins and were starting the first barracks research, lumberjack was being upgraded to lvl 4, other builder was building a new guard tower, both builders had a few other upgrades queued up. I had placed a library and sawmill recently. 

I think I've placed the logs below.

### Logs: Latest.log and crashlog at https://gist.github.com/
[2020-07-07-1.log.gz](https://github.com/ldtteam/minecolonies/files/4888510/2020-07-07-1.log.gz)
[2020-07-07-2.log.gz](https://github.com/ldtteam/minecolonies/files/4888513/2020-07-07-2.log.gz)
[2020-07-07-3.log.gz](https://github.com/ldtteam/minecolonies/files/4888515/2020-07-07-3.log.gz)

**Comment by CaptainMorganX5** [comment]
Thanks in advance!

**Comment by CaptainMorganX5** [comment]
I did some more testing last night. The delivery person will deliver items still to the farmer and guards. I moved the citizens out of lumberjack and miner, new citizens in those jobs work fine but the original citizens will walk to the new job but still won’t move or function anymore.

**Comment by Raycoms** [comment]
Your entities are missing a colony. Did your colony die somewhat?

**Comment by CaptainMorganX5** [comment]
Die in what way? Not to my knowledge. What entities are you talking about? The citizens still act as if they are part of the colony, they all are still shown in the townhall menu, most of the citizens are still working.

**Comment by CaptainMorganX5** [comment]
I just updated to the version released today and everything is back to working normally. I’ll upload the logs here in a bit so we can check if there is still entity issues.
