### ISSUE TITLE
Mod Version 1.16.1

### ISSUE THREAD

**Issue by Romaindu35** [ldtteam/minecolonies#5359]
Hello,
Can you develop the mod in 1.16.1?
Romaindu35

**Comment by Romaindu35** [comment]
Pk ?

**Comment by ToMe25** [comment]
Two things:
1. People requesting stuff like "UPDATE YOUR MOD" are annoying
2. I am pretty sure that the people working on the mod know that the 1.16.1 exits, and have plans to update it, that is just maybe more work then "i will do this today by myself"

**Comment by Romaindu35** [comment]
And 1.15.2 will be released?

**Comment by Romaindu35** [comment]
Ok
