### ISSUE TITLE
Need 0 Air block BUG

### ISSUE THREAD

**Issue by M4cr0ne** [ldtteam/minecolonies#536]
### Minecolonies version

version 0.6.2290

### Expected behavior

- when I upgrade some buildings such as the Town Hall level 2 or the builder's hut at level 2 everything should proceed without problems 

### Actual behaviour

- when I upgrade some buildings such as the Town Hall level 2 or the builder's hut to level 2 the builder asks me to give "0 Air Block" which is impossible, and prevents me from continuing the construction.

### Steps to reproduce the problem

1. build town hall lv1
2. upgrade town hall to lv2
3. builder will ask for "0 air blocks" and stop working
![2017-01-31_23 45 29](https://cloud.githubusercontent.com/assets/25468646/22487859/6b33bc6a-e80f-11e6-83c7-a211698d8348.png)

**Comment by Raycoms** [comment]
We actually fixed that already. The next version on curse will have that
fix.
https://www.dropbox.com/sh/9cnqcjl0nan57cy/AAC99g-CJiTZjQiXMuLKkDgja/branch/version/1.11?dl=0&preview=minecolonies-universal-1.11-0.6.2550.jar

2017-01-31 20:46 GMT-02:00 M4cr0ne <notifications@github.com>:

**Comment by xavierh** [comment]
@Raycoms I did have this problem yesterday in the resource needed tab when testing https://github.com/Minecolonies/minecolonies/pull/529
I had to had a test at https://github.com/Minecolonies/minecolonies/blob/feature%23481-resources-needed-tab/src/main/java/com/minecolonies/coremod/colony/buildings/BuildingBuilder.java#L217

**Comment by Raycoms** [comment]
@xavierh anyone does this still happen?

**Comment by kotshot** [comment]
@xavierh I have this problem right now with minecolonies-universal-1.11-0.6.2837 from 3 days ago. It occurs with my own scanned building that i put into an aditional folder. I can build my custom Citizen1 just fine, but when i try to upgrade it to my custom Citizen2 the builder requests 0 Block Air to finish the construction...

**Comment by xavierh** [comment]
Not that I am aware of

**Comment by Raycoms** [comment]
Please reopen if able to reproduce.
