### ISSUE TITLE
Guard tower lvl 10 or 12 needed for research

### ISSUE THREAD

**Issue by nightwing367** [ldtteam/minecolonies#5361]
Version: minecolonies-0.13.18-ALPHA-universal.jar Can't currently update or post screenshot cause my only world is a server that is currently offline for another bug.

### Expected behavior

- Techs at the university should ask for buildings lvl 1 to 5

### Actual behaviour

- Techs in the military branch that require a guardtower end up needing a lvl 10 and 12 guard tower.

### Steps to reproduce the problem

1. Open the tech tree
2. See the guard tower techs (at least 3 if I recall) that need impossible towers
3. Have a good laugh. (Very important)

### Logs: Latest.log and crashlog at https://gist.github.com/

Not relevent

**Comment by Raycoms** [comment]
It'a additive. Level 10 = 2x5, or 5x2

**Comment by Raycoms** [comment]
10 levels of, not level 10 of

**Comment by nightwing367** [comment]
ah I see now. It's a bit confusing tbh as are the descriptions of many techs. Any plans to make either or both clearer?

**Comment by Raycoms** [comment]
Possibly with the info button in the university we'll add that info.

**Comment by nightwing367** [comment]
Thank you!
