### ISSUE TITLE
Scheduling Medieval Spruce Walls (Gate 3) Error

### ISSUE THREAD

**Issue by wog890** [ldtteam/minecolonies#5362]
# Before reporting please make sure that this issue was not reported yet (Check out similar issue suggestions).
## Also update to the latest alpha of both minecolonies and structurize before reporting

Version: 

Minecraft 1.15.2
Minecolonies-1.15.2-0.13.21.1-ALPHA-universal
Structurize-0.13.4-ALPHA

### Expected behavior

I place the Medieval Spruce Walls Gate 3 to be built by my builder. I expect them to then build the Medieval Spruce Walls Gate 3.

### Actual behaviour

I place the Medieval Spruce Walls Gate 3 to be built by my builder. They start to build Medieval Spruce Walls Gate 1.

### Steps to reproduce the problem

1. Use builders wand to place down Medieval Spruce Walls Gate 3
2. Wait a few seconds for builders to take up build order
3. See chat log of them building Medieval Spruce Walls Gate 1
4. Fight urge to murder entire village

### Logs: Latest.log and crashlog at https://gist.github.com/

No crashlog :-)

**Comment by ravenbuilder934** [comment]
Gate 3 is the upgraded level of gate 1. You need to upgrade the level 1 gate to get the level 3 gate.

**Comment by wog890** [comment]
Alrighty then, that is good to know. I raise you a new issue then. Medieval Spruce Wall Gate 1 cannot be upgraded. Clicking the block to upgrade it shows, "This schematic is already at the highest level or not upgradeable." (See picture)

![2020-07-09_22 03 11](https://user-images.githubusercontent.com/12422891/87108324-0b2def80-c230-11ea-954a-1ca8e0b31d98.png)

**Comment by Raycoms** [comment]
#5006 then
