### ISSUE TITLE
Miner gets stuck needing cobblestone and doesn't request it.

### ISSUE THREAD

**Issue by Mekle001** [ldtteam/minecolonies#5365]
Version: 0.13.21.1

### Expected behavior

- Miner busily mining and building tunnels

### Actual behaviour

- Miner can run out of cobblestone, and stand around indefinitely. 

### Steps to reproduce the problem

1. Have a miner that decides to build tunnels out into the air over a lava lake
2. Miner builds cobblestone walls for all the nodes, until he runs out of cobblestone
3. Miner sits and stares at the partially completed node, only taking a break to sleep. 
4. ... Profit

**Comment by jelaw21** [comment]
I believe I have the same problem, but my miner is requesting dirt. I wasn't even sure the miner used dirt.

**Comment by Mekle001** [comment]
Yeah, mine was requesting dirt too, the dirt request is the right size for what should be a cobble request.

**Comment by jelaw21** [comment]
I also reported it here: as this is exactly what was happening to me: https://github.com/ldtteam/minecolonies/issues/5339

**Comment by jelaw21** [comment]
Update ... seems like just Miner levels 2 did it. I upgraded mine to level 3 and she's digging nodes fine.

**Comment by Mekle001** [comment]
I'm guessing that moved her to a different level of the mine? I'd guess that broke her out of the stuck condition, though if you sent her back to the original level she might get stuck again.

**Comment by janisl** [comment]
I also have this issue with miner requesting dirt instead of cobblestone. My guess is it's because schematic specifies a solid block, in this case the builder would use dirt while the miner cobblestone, but it seams this difference is not considered when requesting items and in both cases the dirt is being requested.
