### ISSUE TITLE
When a builder repairs, rails get placed wrong

### ISSUE THREAD

**Issue by cinnamennen** [ldtteam/minecolonies#5367]
# Before reporting please make sure that this issue was not reported yet (Check out similar issue suggestions).
## Also update to the latest alpha of both minecolonies and structurize before reporting

Version: .21.1

### Expected behavior

- rails would connect properly

### Actual behaviour

- Rails don't connect, e.g. HHHHHHHHH when they should be in a line

### Steps to reproduce the problem

Saw this with a lvl4 fortress dyer that was west/east aligned

**Comment by Raycoms** [comment]
Do you have any rails mod installed? This doesn't happen for me.

**Comment by cinnamennen** [comment]
Nope. here's a MMC zip https://www.dropbox.com/s/h9p5d2gpx1gjq5p/Test.zip?dl=1

**Comment by Mekle001** [comment]
I should note that I'm seeing this on upgrades, but only when the building is rotated appropriately. IE: Fortress level 3 -> fortress level 4, upgrading the buildings on two sides does this, but the other two don't.  This is in a vanilla world with only MC and Structurize.

**Comment by Raycoms** [comment]
which two sides?

**Comment by Mekle001** [comment]
Just checked. Buildings on the east and west side end up with the rails wrong. The rails should be north to south, and end up east to west.

**Comment by cinnamennen** [comment]
Ray, the MMC zip contains a simple save that has the problematic orientation if you’d like to use that to see the issue.

**Comment by Raycoms** [comment]
Does this also happen when you build a decoration to you?

**Comment by Mekle001** [comment]
Decorations appear to work fine.

**Comment by cinnamennen** [comment]
Perhaps something worth noting is that this happens even if there are rails already, which I would think shouldn’t be touched. My guess is that on initial build, the rails get placed “wrong” but because they are being placed one by one, they correct. When a repair or upgrade happens, instead the rails all get touched and forced into the wrong orientation.

**Comment by Raycoms** [comment]
I placed decorations over eachother and it didn't happen, that's what confused me

**Comment by Raycoms** [comment]
Okay I checked into this. This is a minecraft vanilla issue. They messed up rail rotations. I'll make a bug report at mojang and close this issue.
