### ISSUE TITLE
Sick guards keep running around and the healer is chasing them all over town

### ISSUE THREAD

**Issue by MatthiasMann** [ldtteam/minecolonies#5372]
Version: 0.13.24-alpha

### Expected behavior
Sick guards go to the hospital and lay in a bed

### Actual behaviour
Sick guards go to the hospital and walk out again, the healer is chasing them (but typically can't catch them).
Also if potato+carrot is given to a sick guard they keep running around and only try to eat/heal once their patrol brings them into the hospital.
While the healer is chasing the guards (probably he thinks they are in the hospital?) he is not healing anyone else.

### Steps to reproduce the problem
1. Have guards get sick
2. Have a healer / hospital
3. ???
4. ... Profit

**Comment by ravenbuilder934** [comment]
This happens to me too!

**Comment by Raycoms** [comment]
Do you have a world where this happens that you can send me?
