### ISSUE TITLE
Not really a bug but a compatibility issue

### ISSUE THREAD

**Issue by Consumerx54** [ldtteam/minecolonies#5377]
# Before reporting please make sure that this issue was not reported yet (Check out similar issue suggestions).
## Also update to the latest alpha of both minecolonies and structurize before reporting

Version: Just d/l newest

### Expected behavior

-I would see this block place things in the world 

### Actual behaviour

-Nothing happens!-- Description here -->

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit
I am working with a new mod called Create.  In this mod there is a block called deployer and it does a lot of things a player can do like plant, break blocks, push buttons etc.  Inside of the minecolonies boundary this block will not function properly but outside the colony boundary it works great.  I am guessing that the colony sees it like a player and will not let it place anything in the colony boundary.   I really hope there is a fix for this soon because the create mod is a fun mod to use

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: 
- crashlog:

**Comment by Mekle001** [comment]
Have you looked in the Townhall? I would expect there to be events there where it blocked the deployer from working, and you should be able to grant it access from there.

**Comment by Raycoms** [comment]
^ and else #4510
