### ISSUE TITLE
Shepard can shear baby sheeps

### ISSUE THREAD

**Issue by ToMe25** [ldtteam/minecolonies#5379]
Structurize Version: 0.13.0-ALPHA
Minecolonies Version: 91c98de

### Expected behavior
I expect the shepard to not shear baby sheeps, because the player can't do that either.

### Actual behaviour
he does.
![2020-07-13_12 29 54](https://user-images.githubusercontent.com/38815969/87295088-f9389f00-c504-11ea-99bd-2bf1366a99b6.png)

### Steps to reproduce the problem

1. build a shepard
2. give him some sheeps
3. wait for him to breed two of them
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: 
- crashlog:

**Comment by Raycoms** [comment]
Tbf I like it. When the entity supports it, and it looks fine. Is a bonus compared to normality

**Comment by ToMe25** [comment]
OK, closing this.
