### ISSUE TITLE
[Feature request] - Sublte/immersive "debug output"

### ISSUE THREAD

**Issue by forReason** [ldtteam/minecolonies#538]
### Minecolonies version

I request more Information on what the NPC's are "thinking" ehile this may help developers it is mainly adressed to "normal" users so they can better understand why npc's are doing what they do.

### Current Behavior
When you walk near npc's they will talk some random things to you like "Serve with pleasure" or "Its your money"

### Requested Behavior:
NPC's will bring out random sounds based on their current situation. Some examples:

|Situation|Audio|
|-|-|
|Going to work 1|Today is a beautiful day to work|
|Going to work 2|Ahh, its monday again Work is calling 😭 |
|Working|Work work work work work - ah sir wanna help me?|
|Insufficient Items|Well - suddenly my toold broke|
|Build just completed|Oh what a Beautiful building!|
|Sunny day|Oh what a wonderful day|
|Raining|Whoow the Rain is so strong I even cant get to work|
|Monster nearby 1|AHHHH A ZOMBIE|
|Monster nearby 2|HELP ME! SOMEONE! HELP|

**Comment by Raycoms** [comment]
Yeah that's stuff we have planned but we're missing sound creators =D

2017-02-01 6:02 GMT-02:00 Julian B. <notifications@github.com>:

**Comment by forReason** [comment]
well what soundfiles do you need? MP3/Wav?

**Comment by forReason** [comment]
and also what kind of licence. there are tons of attribution 3.0 and Sampling plus 1.0 Licenses out there

**Comment by marvin-bitterlich** [comment]
Closing for now, we accept sounds now
