### ISSUE TITLE
permissions confusion

### ISSUE THREAD

**Issue by LuckyFalkor** [ldtteam/minecolonies#5381]
and a couple others have our own Colonies on a server and when one person gets an achievement, everyone else that is on gets it as well.

now a bunch of us are in the friend list of each other's colony so i am thinking this is a permission issue and just not sure which one it might be.

also i think it is a permissions issue that is allowing colonies of people whom are offline to still be attacked, we have the keep loaded permission off between us, but that doesn't seem to cut it.

i did try looking on the wiki and various forums before posting this, so i am hoping i did not simply miss this info somewhere.

thanks for all your hard work, great mod.

**Comment by Raycoms** [comment]
Both the issues of advancements and getting attacked should only be when the person is an officer. Isn't that the case?

**Comment by LuckyFalkor** [comment]
oh, ok, that makes more sense.
i thought officer and friend were just labels, but they each imply different things as well?
as in if i set the permissions the same for both, still only the officer one does the achievement sharing and such?
if that is the case, i will make sure no one is using officer and just the friend category.
thanks,

**Comment by Raycoms** [comment]
Yes, exactly. Besides achievements officer have those additional roles.
Friend doesn't have any implications though

**Comment by LuckyFalkor** [comment]
cool, thanks for the quick response.
