### ISSUE TITLE
Can't rotate when placing a building/decoration near another building/decoration.

### ISSUE THREAD

**Issue by jelaw21** [ldtteam/minecolonies#5382]
# Before reporting please make sure that this issue was not reported yet (Check out similar issue suggestions).
## Also update to the latest alpha of both minecolonies and structurize before reporting

Version:  0.13.29-ALPHA

### Expected behavior

- When placing a building, I should be able to use the rotate button to rotate the building.

### Actual behaviour

      
- When placing the building near another building (i.e. blue guidelines appear and level 5 ghost image is shown on already built building) the rotate buttons don't rotate the building, it seems to just move the current rotation.  

### Steps to reproduce the problem

1. Build a building
2. Try and place another building/decoration neat but not overlapping, then attempt to rotate it
3. It goes a bit bonkers and doesn't rotate, but just displaces.
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: 
- crashlog:

**Comment by Mekle001** [comment]
I noticed this earlier today when testing something else. The outline, and anchor point rotate, but the ghost render does not.  I used a Fortress corner wall, where the anchor point is in one corner of the chunk, and you can see it easily there.

**Comment by MatthiasMann** [comment]
The issue is not that the building you are trying to place isn't rotating - I had the case where the existing buildings (blue wire frame) were rendered with the wrong rotation. So for me it looks that rotation/mirroring information gets mixed up between the different buildings when close together.
