### ISSUE TITLE
Builder won't complete buildings with item frames

### ISSUE THREAD

**Issue by Preselier** [ldtteam/minecolonies#5384]
Version: 1.15.2-0.13.21.1-ALPHA

I have set two seperate builders to build two sperate buildings, fisherman's hut and town hall, both level 4, however they will not complete the build. When it comes towards the end, both need to place an item frame, but neither will place it. Instead, they will hold a flower pot in their hand and will both repeatedly go to a fixed spot and attempt to place the pot over and over, without any actual changed happening.

### Steps to reproduce the problem

1. Build town hall to level 3
2. Set it to upgrade
3. watch the builder attempt to place the frame
4. ... Profit

Thank you!

**Comment by ravenbuilder934** [comment]
What happens if you place it yourself?

**Comment by Preselier** [comment]
So after a bit of experimenting, and comparing what the finished build should look like to what the builder is doing, it looks like flower pots are the issue rather than item frames, sorry! The builder isn't registering that the pot has already been placed and keeps trying to place it. I've tried breaking it and letting them do it themselves, and breaking it and placing myself, but neither have worked.
