### ISSUE TITLE
Server Pack

### ISSUE THREAD

**Issue by Endergamer20011** [ldtteam/minecolonies#5389]
# Before reporting please make sure that this issue was not reported yet (Check out similar issue suggestions).
## Also update to the latest alpha of both minecolonies and structurize before reporting

Version: 

### Expected behavior

- 

### Actual behaviour

- 

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: 
- crashlog:

**Comment by Asherslab** [comment]
***fill out the issue template***
