### ISSUE TITLE
Raiders are missing, Raid won't end

### ISSUE THREAD

**Issue by ffgghhjj** [ldtteam/minecolonies#5390]
# Before reporting please make sure that this issue was not reported yet (Check out similar issue suggestions).
## Also update to the latest alpha of both minecolonies and structurize before reporting

Version: 0.13.29 ALPHA

### Expected behavior

Sometimes at dusk you get a message saying that some citizens reported sightings of a group of Raiders, and then a direction of where they are. The game tells you how many raiders are left.

- 

### Actual behaviour

- 
The game tells me that there is two raiders left, but they are nowhere to be found. I tried looking around in spectator mode and there is no evidence of raiders anywhere underground and above ground.

### Steps to reproduce the problem

1. The game tells you there are raiders
2. I killed a few of them until the game tells me there are two more left
3. There are no more raiders anywhere in the vicinity of my colony, and spectator mode shows me that they are literally nowhere.
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: 
- crashlog:

**Comment by shanekremer** [comment]
I had a similar issue, but the raiders ended up being in a cave waaaaaaaaayyy underneath in a cave no where near the town. I think they fell and water pushed them and they tried to take the wrong back way. It took 30m to hunt them down.

**Comment by Raycoms** [comment]
this should be vastly improved with the last updated.
