### ISSUE TITLE
Server crash: nbt structure not found

### ISSUE THREAD

**Issue by xavierh** [ldtteam/minecolonies#540]
### Minecolonies version

Using Feature#481-resources-needed-tab (but not related)

### Expected behavior

- Upgrade a buidling builder to level 2
[structurenotfound.log.zip](https://github.com/Minecolonies/minecolonies/files/748342/structurenotfound.log.zip)

 without crashes

### Actual behaviour

- Make the server crash.
- For some reason, java.io.FileNotFoundException: ./minecolonies/wooden/Builder2.nbt

### Steps to reproduce the problem

Don't know how to reproduce it.
I restarted the server and the problem went away.

Regardless of that, when a structure is not found, it should not make the server crash

**Comment by xavierh** [comment]
I had it again on a different world using version/1.11 from github:
java.io.FileNotFoundException: ./minecolonies/default/Builder3.nbt (No such file or directory)

**Comment by Raycoms** [comment]
crashing?
it shouldn't crash... I will have to put a switch to the new default.

2017-02-02 17:08 GMT-02:00 xavierh <notifications@github.com>:

**Comment by xavierh** [comment]
Yes, but only the first time. not sure why

**Comment by xavierh** [comment]
I guess this one can be close now
