### ISSUE TITLE
Food being stored willy nilly

### ISSUE THREAD

**Issue by Mizque** [ldtteam/minecolonies#5400]
# Before reporting please make sure that this issue was not reported yet (Check out similar issue suggestions).
## Also update to the latest alpha of both minecolonies and structurize before reporting

Version: minecolonies-1.12.2-0.10.714-RELEASE-universal.

### Expected behavior
Edible foods would be stored in restaurant pending consumption by citizens

### Actual behavior
Food is stored in random places

- It's being placed in the following ways: in the racks in the restaurant that the citizens don't seem to access, or, the delivery man absconds with all the food throwing it all into the warehouse

### Steps to reproduce the problem
<!-- What should we do to make this issue show up in our own game? 
   Just have alot of food being made, and a delivery man/warehouse most of the food will end up in the warehouse and cause issues with the citizens not eating

**Comment by Raycoms** [comment]
That has been vastly improved in 1.15. Due to time constraints we can;t offer support for those kind of bugs in 1.12 anymore unfortunately.
