### ISSUE TITLE
Tavern2 Update issues

### ISSUE THREAD

**Issue by MineShadow7** [ldtteam/minecolonies#5401]
Version: minecolonies-0.13.42-ALPHA-universal
Minecraft 1.15.2

### Expected behavior
1. Newly arrived citizens should at least come back to tavern at night
2. Citizens Recruitment should ask for items to recruit

### Actual behaviour
![2020-07-18_15 48 12](https://user-images.githubusercontent.com/28764927/87852872-72bdfc00-c90e-11ea-9ada-ee164731a413.png)
![2020-07-18_15 11 45](https://user-images.githubusercontent.com/28764927/87852873-73ef2900-c90e-11ea-9721-115f06547652.png)

### Steps to reproduce the problem
Have a tavern in your colony (pre-built before the update to be certain).

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: https://gist.github.com/MineShadow7/e81a513eda15979d41ea5c632f3f2f1b
- crashlog:

**Comment by Raycoms** [comment]
Fixed in my PR
