### ISSUE TITLE
Colonist pathing issue

### ISSUE THREAD

**Issue by catrina339** [ldtteam/minecolonies#5404]
Version: 0.13.37
Mod is used in the Valhelsia 2 mod pack

### Expected behavior
Colonists sleeping in the beds in the tavern

- 

### Actual behavior
The colonists congregate on the outside of the tavern 

![2020-07-18_21 34 19](https://user-images.githubusercontent.com/68488601/87866064-62277900-c942-11ea-80e9-af24e5fff4b2.png)

### Steps to reproduce the problem
I am not sure as I am not experiencing this issue with a level one birch tavern on a different world using the same mod pack. However, the theme that I am building with is the Medieval Oak. It did not happen with the level one tavern but with levels 2 and three.

**Comment by Raycoms** [comment]
Is the entry to the basement somehow blocked?

**Comment by Raycoms** [comment]
It doesn't happen for me for the same style and level 2+3. Is there maybe something obstructing the way to the other rooms?

**Comment by MatthiasMann** [comment]
I had the same issue until I blocked of the area where the citizen are standing in your screen shot using a few roses and fence around it (5x2 area between the 2 oak logs)

**Comment by catrina339** [comment]
@Raycoms negative to both of those.

**Comment by catrina339** [comment]
@MatthiasMann i will give that a go

This hack worked. I put a bunch of leaves/bushes in the area and it fixed the pathing issue.

**Comment by Raycoms** [comment]
I can't reproduce this. @catrina339 is there a way you can reproduce this on a new world?

**Comment by gaminggirl** [comment]
I'm having the same problem with a birch tavern on version 1.6 of Minecolonies Official. They stand around the barrel outside the tavern until i push them into the door hole. Every night so having big problems with those 4 complaining about lack of sleep.

**Comment by ravenbuilder934** [comment]
You could try using waypoints

**Comment by gaminggirl** [comment]
> 
> 
> You could try using waypoints

I've tried waypaoint in just about every place I can think of now, they are not going into the tavern without me pushing them in.
