### ISSUE TITLE
Acacia University Level 3 never finishes

### ISSUE THREAD

**Issue by kd5crs** [ldtteam/minecolonies#5405]
# Before reporting please make sure that this issue was not reported yet (Check out similar issue suggestions).
## Also update to the latest alpha of both minecolonies and structurize before reporting

Version: minecolonies-0.13.34-ALPHA-universal

### Expected behavior

- Builder finishes placing University Level 3.

### Actual behaviour

- I think it is maybe the armor on the armor stands: instead of placing anything, the builder just runs to the same spot, turns around, and runs back to the Builder's Hut. After some time, it repeats. Nothing gets placed. Builder has all required items.

### Steps to reproduce the problem

1. Build Level 2 Acacia University.
2. Upgrade to Level 3, provide all items.
3. Builder fails to complete build when it gets to the armor stands.
4. I can upload the world, but it is 150mB zipped.

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: https://gist.github.com/kd5crs/7d0772d0ce4ffb1537fb17a16989cd43
- crashlog: No crash
- debug.log: https://gist.github.com/kd5crs/27c3afabf73b9fe34578c676177b374e

**Comment by Thoughtleech** [comment]
I see this behavior for every building that has armor stands/armor.

**Comment by Raycoms** [comment]
Can you try this with the newest structurize?

**Comment by kd5crs** [comment]
Did not fix it. I updated to structurize-0.13.24-ALPHA and minecolonies-0.13.73-ALPHA-universal. No change in behavior. I cancelled the university upgrade and started it again, Builder ran around in a different pattern for a bit but settled into the exact same behavior, did not place armor stands. I used the preview tool with another university block to find where the armor stands and armor should go and placed them manually. Builder is still requesting them, and requests them again when I cancel the request. The Builder's Hut still shows the manually placed armor and armor stands as required and not present. I also tried taking everything from the Builder's inventory, and fulfilling the requests when they appeared. No change in behavior. Next I'll try turning "Builder requires resources" in the configuration file off to see if that at least gets me past this issue.

**Comment by kd5crs** [comment]
Setting builderinfiniteresources = true allowed the Builder to finish, seemingly without placing anything. I've set it back to false and the Builder has moved on to the next building.

**Comment by valveo** [comment]
I just run this problem. Almost same but error is second level armor room, there are 4 armor stand at window (Right from frontdoor, upstairs, first room on right). Upgrading stop at 89%-90%, because 2 lanterns are placed where armor stands should be. Checked error from Lv3 wooden university blueprint and those items doesnt stack.

**Comment by ravenbuilder934** [comment]
> I just run this problem. Almost same but error is second level armor room, there are 4 armor stand at window (Right from frontdoor, upstairs, first room on right). Upgrading stop at 89%-90%, because 2 lanterns are placed where armor stands should be. Checked error from Lv3 wooden university blueprint and those items doesnt stack.

Please create a new issue instead of necroing an old one (and fill out the template)
