### ISSUE TITLE
Colony 1 has a very big memory imprint, this could be a memory leak

### ISSUE THREAD

**Issue by Tbear1825** [ldtteam/minecolonies#5408]
Version:  0.13.48-ALPHA on minecraft 1.15

### Actual behaviour
We have two minecolonies one each for two players.  Four total players on the server, two with a colony.  Server continues giving error: "[Server] Server thread/WARN [minecolonies/]: Colony 1 has a very big memory imprint, this could be a memory leak, please contact the mod author!"

When player owning colony 1 attempts to log in he gets kicked with client side error that reads: "Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Payload may not be larger than 1048576 bytes"

This also prevented player with Colony 2 from being able to log into server and that player is ficen the same client side error.

Minecolonies and Structurize were both updated after this occured.  Upon update player 2 with Colony 2 logs in without an issue.  Player 1 with colony 1 logs in and this causes both player 1 and 2 to be kicked with the same client side error. And the same "imprint too large" warning on the server.

When either player tries to log back in after being kicked the are given the same client side error as before and the server warning reads: 
"19.07 14:17:10 [Connect] User Tbear1825, IP 71.87.92.220
19.07 14:17:10 [Server] Server thread/INFO Tbear1825 joined the game
19.07 14:17:10 [Multicraft] Tbear1825 ran command Message of the Day
19.07 14:17:10 [Server] Server thread/INFO [Waila/]: Syncing config to Tbear1825 (03f09de3-0689-4ae5-affe-c8a0c4143414)
19.07 14:17:10 [Server] Server thread/INFO [se.mi.te.da.DataManager/]: Sending data to client: Tbear1825
19.07 14:17:10 [Server] Netty Epoll Server IO #12/ERROR Could not serialize net.minecraftforge.server.command.ModIdArgument@1f658113 (class net.minecraftforge.server.command.ModIdArgument) - will not be sent to client!
19.07 14:17:10 [Server] Netty Epoll Server IO #12/ERROR Could not serialize net.minecraftforge.server.command.EnumArgument@2253fa53 (class net.minecraftforge.server.command.EnumArgument) - will not be sent to client!
19.07 14:17:10 [Server] Netty Epoll Server IO #12/ERROR Could not serialize com.ldtteam.structurize.commands.arguments.MultipleStringArgument@473ba7c0 (class com.ldtteam.structurize.commands.arguments.MultipleStringArgument) - will not be sent to client!
19.07 14:17:12 [Server] Server thread/WARN [minecolonies/]: Colony 1 has a very big memory imprint, this could be a memory leak, please contact the mod author!
19.07 14:17:12 [Server] Server thread/WARN [minecolonies/]: Owning field not considered because not loaded: BlockPos{x=523, y=74, z=-970}
19.07 14:17:12 [Server] Server thread/WARN [minecolonies/]: Owning field not considered because not loaded: BlockPos{x=595, y=72, z=-870}
19.07 14:17:12 [Server] Server thread/WARN [minecolonies/]: Owning field not considered because not loaded: BlockPos{x=595, y=72, z=-882}
19.07 14:17:12 [Server] Server thread/WARN [minecolonies/]: Owning field not considered because not loaded: BlockPos{x=523, y=74, z=-970}
19.07 14:17:12 [Server] Server thread/WARN [minecolonies/]: Owning field not considered because not loaded: BlockPos{x=595, y=72, z=-870}
19.07 14:17:12 [Server] Server thread/WARN [minecolonies/]: Owning field not considered because not loaded: BlockPos{x=595, y=72, z=-882}
19.07 14:17:12 [Disconnect] User Tbear1825 has disconnected, reason: Disconnected
19.07 14:17:12 [Server] Server thread/INFO Tbear1825 left the game"

NOTE:  This does not kick or prevent other players that do not have a colony from joining or playing and does not crash the server.

### Steps to reproduce the problem
Not sure what caused the issue itself therefore not sure how to recreate it.

**Comment by Raycoms** [comment]
you can do a request system reset on the colony to avoid this issue for now. Before doing that, could you either send us the world or the colony dat in question?

**Comment by Tbear1825** [comment]
Thank you, that seemed to have worked.  Here is a link to the world file.
 server21646 - 19 Jul 2020 14_6_5.zip
<https://drive.google.com/file/d/1rC0B1mUAuhQCbC4v_tjv1XzcNdrV8omb/view?usp=drive_web>

**Comment by Raycoms** [comment]
I double checked. This memry leak was fixed. So it should nt appear anymroe on the newer versions.
