### ISSUE TITLE
stash sometimes glitches and delivery people no longer take from it.

### ISSUE THREAD

**Issue by LuckyFalkor** [ldtteam/minecolonies#5417]
I realize this is a duplicate to my closed issue, but this is still happening.
I have put additional details below that i have figured out so far since that last issue.

Version:
structurize-0.13.18-ALPHA
minecolonies-1.15.2-0.13.44-BETA-universal
forge-1.15.2-31.2.8
Expected behaviour

    drop items in stash
    delivery person comes by and picks up the items
    one of the items appears in the citizen's hand before walking away
    items in stash are no longer visible

Actual behaviour

    drop items in stash
    delivery person comes by.
    items are still visible in the stash
    nothing appears in the citizen's hand and the citizen walks away after a few seconds
    items never make it to the warehouse
   
    does not seem to effect all players

Steps to reproduce the problem

I can not seem to reproduce the issue on purpose, just occurs randomly
I have two stash boxes now, when one starts having the issue, they both have the issue.
I can break one and place it again and it will work, but the other one remains broken till i do the same.
restarting the server seems to fix the issue as well.
I tried the "/mc colony requestsystem-reset-all" and it does not seem to fix the issue.

When the stash is glitching, if i do not empty it before breaking it, i lose my items; where normally they just pop out when i break the block.

I could send a copy of my world and see if that helps.

Logs: Latest.log and crashlog at https://gist.github.com/

    latest.log: nothing seems to show up in the logs, no errors in game either
    crashlog: nothing crashes, so no crash log.

**Comment by Raycoms** [comment]
Duplicate issue: #4905

But I hope this is fixed in the newest alpha, can you try that out?

**Comment by LuckyFalkor** [comment]
k, got it installed.
giving it a try now.
also the issue in #4905 was a thing for us as well, just was infrequent enough to not be WTF.
i hoping both are fixed now.
thanks,

**Comment by PowerSchill** [comment]
It's happening on the MC Official server. I've had the same results as you did.

**Comment by ravenbuilder934** [comment]
This happened to me. I found that breaking and placing the stash (temporarily) fixes it.
