### ISSUE TITLE
Crusher not working and breaks the Request/Delivery System

### ISSUE THREAD

**Issue by MerlinplaysGames** [ldtteam/minecolonies#5419]
# Before reporting please make sure that this issue was not reported yet (Check out similar issue suggestions).
## Also update to the latest alpha of both minecolonies and structurize before reporting

Version: minecolonies-0.13.53-ALPHA-universal.jar
             structurize-0.13.19-ALPHA.jar
             Fortress Style

### Expected behavior

- Order 32 Gravel in Postbox
- 64 Cobble delivered from Warehouse to Crusher
- Crusher makes it into Gravel
- 32 Gravel gets delivered to Postbox

### Actual behaviour

- Order 32 Gravel in Postbox
- Subrequest is getting opened for Delivery of 64 Cobble
- Subrequest changes into Delivery of 1 Sand
- At the Moment: 1 Sand gets delivered, Request is closing
- 2 hours before: All Deliveryman running crazy between Crusher and Warehouse, 1 of them with some Error  
![Request](https://user-images.githubusercontent.com/65611175/87971241-4c8e8c80-cac5-11ea-9f26-856ccb535c89.png)

I tried:
- Using different Worker (because first keeps saying "Not able to work for 2 Weeks" from her Job before)
- Setting the Crusher to Cobble/Gravel/Sand and save
- Deconstruct and remove Crusher - restart - rebuild
- Deconstruct and rebuilt the Deliveryman because he was stuck on delivery of 1 Sand
- After that I didn't touch the second Page of the Crusher, worked 2 times, then same Problem

### Steps to reproduce the problem

1. Remove Gravel, Sand, Clay from Warehouse
2. Order 32 Gravel in Postbox
3. If it works order 32 Sand
4. If it still works order some Clay, there it broke the whole System for me

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: https://gist.github.com/MerlinplaysGames/708ee17ffe6ed7ad0f4e4a87941a9800

- crashlog:

**Comment by Raycoms** [comment]
fix pushed
