### ISSUE TITLE
Client crash on login

### ISSUE THREAD

**Issue by ProsperCraft** [ldtteam/minecolonies#542]
### Minecolonies version

minecolonies-universal-1.11-0.6.2604

### Pastebin
http://pastebin.com/xzPkejPD

A new user to my server logged and got this crash, others are not having it.

**Comment by marvin-bitterlich** [comment]
Weird thing. Seems like the world was null for him. Should normally not happen. Is it reproduceable?

**Comment by ProsperCraft** [comment]
It didn't happen after he relogged

**Comment by marvin-bitterlich** [comment]
I'll be closing this for now as a minecraft weird thing
