### ISSUE TITLE
Warehouse Racks are twitching/not recognised

### ISSUE THREAD

**Issue by MerlinplaysGames** [ldtteam/minecolonies#5420]
# Before reporting please make sure that this issue was not reported yet (Check out similar issue suggestions).
## Also update to the latest alpha of both minecolonies and structurize before reporting

Version: minecolonies-0.13.53-ALPHA-universal.jar
             structurize-0.13.19-ALPHA.jar
             Fortress Style

### Expected behavior

- Racks should connect in pairs of two, be all visible and recognized by the DelMan 

### Actual behaviour

- The Racks connect to each other every time you click one of them (first to the left, then to the right)
- Some Racks get invisible if you click another one
- Some Racks are not accessible for the Deliveryman (Tools/Items can not be requested if they are in that Rack)
- If the accessible Slots are full, the DelMan get stuck without the Prompt "Warehouse full"

![2020-07-20_19 16 21](https://user-images.githubusercontent.com/65611175/87975084-67fc9600-cacb-11ea-820e-42daa247216f.png)

I tried:
- Rebuild the Racks per hand: Visible and connected OK, but not all accessible
- Remove Racks and then let the Builder repair the WH: same as before

### Steps to reproduce the problem

1. Build Warehouse Fortress (Lvl 1 or 2) 
2. Let the Racks be filled 
3. Click the Racks and check which are empty 

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: https://gist.github.com/MerlinplaysGames/708ee17ffe6ed7ad0f4e4a87941a9800 
- crashlog:

**Comment by patgoull** [comment]
Can confirm I've had this issue ever since Fortress existed I think. I got around by breaking them and placing them by hand. Can confirm it's still happening too.

**Comment by janisl** [comment]
Happens for me too

**Comment by CiramorDev** [comment]
Hello, I am currently playing in 1.19.2 and I happen to have the same issue. 
I am using fortress theme and I have to replace all of them by hand to have them appear properly, I think this is a minor issue, but it is quite annoying

**Comment by Thodor12** [comment]
If you replace racks by hand they will become unknown to the warehouse, don't do this.

**Comment by MotionlessTrain** [comment]
There is an open pull request for a fix for those racks

Besides, this is a very old issue. Please open a new one if you encounter it again. Minecolonies opens very frequently, so a bug from 3 years ago is very likely not relevant anymore
