### ISSUE TITLE
Fortress Town Hall Level 1 not being finished

### ISSUE THREAD

**Issue by Fireisle** [ldtteam/minecolonies#5422]
Version:  minecolonies-0.13.54-ALPHA-universal.jar and structurize-0.13.19-ALPHA.jar
Fortress Style

### Expected behavior
Builder should finish building the Town Hall as usual

### Actual behaviour
Builder stops when the clipboard and item frame are the only items left, builder just ends up standing on top of the Town hall block, exits the town hall, runs around for a bit, then goes back inside and repeats

### Steps to reproduce the problem
1. Place Fortress Town Hall and create colony
2. Build Fortress builder's hut (have attempted with one and several builders, same results)
3. Assign builder to construct Fortress Town Hall level 1
4. For the clipboard and item frame to be the only steps left.

### Logs: Latest.log and crashlog at https://gist.github.com/
- latest.log: https://gist.github.com/Fireisle/7fba204313f4bd852001764ff1451b20

**Comment by Raycoms** [comment]
Duplicate #5405
