### ISSUE TITLE
Delivery man are unable to comply

### ISSUE THREAD

**Issue by Dulap3** [ldtteam/minecolonies#5430]
Version: 0.13.59

### Expected behavior
Expected for the delivery man to go and pick up excess items from lumberjack, miner etc. and make them room in hut's inventory automatically or by requesting them to.

### Actual behaviour
They just stick around the warehouse answering to requests given by the citizens normally but would not go pick up anything being produced by the huts. If a request is given by the player for a pick up the only message given is "Unable to comply, pick up already in progress"

### Steps to reproduce the problem 

1. Build your first huts like a miner, lumberjack etc
2. Build the warehouse first
3. Build the delivery hut
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: https://gist.github.com/Dulap3/a613eac60271d9fef023c0e1241d15cc
- crashlog:

**Comment by Dulap3** [comment]
It seems that breaking and rebuilding the working huts that existed before the delivery man was made fixes the problem and they start picking up items again

**Comment by Raycoms** [comment]
Any way to reproduce this?

**Comment by DavidSlva** [comment]
Confirmo lo que dice, el repartidor se queda en el almacén sin hacer nada.

**Comment by DavidSlva** [comment]
> ¿Alguna forma de reproducir esto?

De la misma forma que se menciona

**Comment by someaddons** [comment]
english only

**Comment by Dulap3** [comment]
It happened to me in 2 different wolrds, basically all i did was staring with: 

1.The town hall and builder
2. A tavern, a lumberjack, a miner, a farm, houses (i was pretty much following the indications and achievements) 
3. After those i built the warehouse first and then the carrier. All huts were the medieval spruce  lvl 1.
4. Carriers start the problem described. 

As i mentioned destroying the huts and rebuilding them after the carrier hut is already built fixes the problem. 
I don't know if its relevant but those villages where built using creative (not pasting them, but supplying the builder from the hut's menu)

**Comment by q107580018** [comment]
me too! i don‘t know how to deal with it !!!
