### ISSUE TITLE
Plantation sugarcane issue

### ISSUE THREAD

**Issue by janisl** [ldtteam/minecolonies#5432]
# Before reporting please make sure that this issue was not reported yet (Check out similar issue suggestions).
## Also update to the latest alpha of both minecolonies and structurize before reporting

Version: 0.13.56-ALPHA

### Expected behavior

- Sugarcane is planted and harvested when grown 3 high

### Actual behaviour

- Only works on specific schematics, when switched to cactus and bamboo it works fine in the cases I tested.

### Steps to reproduce the problem

1. Start superflat creative world, place town hall and create colony
2. Paste in the following plantations: Acacia level 1, fortress level 2, medieval spruce level 3, wooden level 5
3. Give workers sugarcane they require
4. In acacia and fortress nothing works, in medieval spruce sugarcane is planted in only 3 spots, in wooden it works as expected
5. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: 
- crashlog:

**Comment by Raycoms** [comment]
please report in: #5006 @lunadragnstar
