### ISSUE TITLE
Crash upon Town Hall placement

### ISSUE THREAD

**Issue by ComradeMaethor** [ldtteam/minecolonies#5438]
Version: 0.10.771 RELEASE

### Expected behavior

- Click green check mark to finish placement and resume game with the perimeter of the Town Hall laid out

### Actual behaviour

- Game freezes briefly then goes to a "Saving World" screen before fully exiting the application. The launcher then gives this crash report:
```
The game crashed whilst mouseclicked event handler
Error: java.lang.NoSuchMethodError: com.ldtteam.structures.lib.BlueprintUtils.getPrimaryBlockOffset(Lcom/ldtteam/structures/blueprints/v1/Blueprint;)Lnet/minecraft/util/Tuple;

```

### Steps to reproduce the problem

1. Right click town hall on ground
2. Click the green check mark
3. Game exits and goes to Saving World screen
4. Crash

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: 
- crashlog: https://gist.github.com/ComradeMaethor/5177c24c1bd812f226f7ca147b0efcd1

**Comment by ravenbuilder934** [comment]
Update to the latest alphas of MineColonies and Structurize. Though in some other instances alphas mark "unstable" versions, MineColonies alphas are just minor releases and primarily have nothing to do with stability/instability. 
Alphas are just too small to call them beta/release.

**Comment by Asherslab** [comment]
as above. Update
