### ISSUE TITLE
Healer inventory issue

### ISSUE THREAD

**Issue by janisl** [ldtteam/minecolonies#5439]
# Before reporting please make sure that this issue was not reported yet (Check out similar issue suggestions).
## Also update to the latest alpha of both minecolonies and structurize before reporting

Version: 0.13.56-ALPHA

### Expected behavior

- 
If there are items healer needs to work in hut's inventories, he picks them up and heals other citizens.

### Actual behaviour

- 
Healer has potatoes in his inventory, there are carrots in rack of the hospital. The healer continually walks between citizen who needs help and hut block, doesn't pick up carrots and hospital gets full with sick citizens.

When I took out carrots from the rack, healer requested them from warehouse and was able to proceed.

### Steps to reproduce the problem

1. Have potatoes in healers inventory and carrots in rack of hospital
2. Have a citizen wo needs to be healed with carrot and potato
3. Watch hospital get full with sick people
4. ... Profit

**Comment by Mekle001** [comment]
I too have seen this, and can confirm it's happening. At a quick glance, nothing jumps out at me, but I'll dig a bit.

**Comment by fr3akb0y** [comment]
Same is happening for me with the Farmer. He never picks up the crops I put in the Hut inventory. Might relate to this might not.
(latest 1.15 alpha)
