### ISSUE TITLE
Voices slider in Music & Sounds does not affect citizen voices

### ISSUE THREAD

**Issue by Techiastronamo** [ldtteam/minecolonies#5440]
Version: Minecolonies 0.13.44 Beta, Structurize 0.13.19 Alpha, Minecraft 1.15.2.

### Expected behavior
I expect the citizens to not speak or sing when I turn the slider down to zero.

### Actual behaviour
It does nothing to their audio. They won't stop singing and speaking.

**Comment by Talyda** [comment]
If it helps, there is a "disable citizen voices" option in the config

**Comment by Raycoms** [comment]
which slider are you turning dwn to 0?

**Comment by ravenbuilder934** [comment]
The Voices slider in Music and Sounds (not sure what that does in vanilla. Maybe villager voices?)

**Comment by Raycoms** [comment]
![image](https://user-images.githubusercontent.com/6438347/88288336-893bcd00-cceb-11ea-8f7b-efeb4f868450.png)

**Comment by Techiastronamo** [comment]
> If it helps, there is a "disable citizen voices" option in the config

That is very helpful, thank you.
