### ISSUE TITLE
Lumberjack stops working if leaves are blocking his way

### ISSUE THREAD

**Issue by ffgghhjj** [ldtteam/minecolonies#5451]
Description: If a tree grows and there is a leaf block two blocks up from the ground surrounding a log in any of the 4 cardinal directions, the Lumberjack will attempt to walk towards the tree to cut it down, then stop because there is a leaf block there, the lumberjack will then proceed to be stuck like this until you manually remove the leaf block for them.

**Comment by Raycoms** [comment]
Duplicate: #5431
