### ISSUE TITLE
Opening Door only opens second half (block)

### ISSUE THREAD

**Issue by Strohtaler** [ldtteam/minecolonies#5452]
### Versions

Minecraft: `1.15.2`/Multiplayer (`online-mode=false`)
Forge: `31.2.20`
Minecolonies: `minecolonies-0.13.69-ALPHA-universal`
Structurize: `structurize-0.13.19-ALPHA`
_no other mods_

### Expected

Both door blocks stay closed when trying to open a door without having colony's permission (foreign colony).

### Actual

The clicked door block (half) stays closed but the second block opens.

![2020-07-25_07 35 47](https://user-images.githubusercontent.com/62442477/88452023-ee5a0480-ce4a-11ea-82b0-6d4c3ff7dcba.png)

_nothing relevant in logs_

**Comment by Raycoms** [comment]
That's actually an issue with another mod that causes double doors to open together. So it's #4510

**Comment by Strohtaler** [comment]
@Raycoms  this is not related to another mod - as described (even _emphasized_), I have only `Structurize` and `minecolonies` - it is not the double door bug. Single doors are also affected. 

![Annotation 2020-07-25 075740](https://user-images.githubusercontent.com/62442477/88452236-991ef280-ce4c-11ea-97f2-b96e440c88ce.png)

![2020-07-25_07 55 50](https://user-images.githubusercontent.com/62442477/88452203-5230fd00-ce4c-11ea-93a7-f0c0d69d30e2.png)

**Comment by Raycoms** [comment]
Ahh, not only double doors. Then this is because we cancel the event on the serverside about the permission.

**Comment by Raycoms** [comment]
yeah, I double checked, since we block events serverside this happens. I'd call that a vanilla or even forge but. Since when the event is cancelled serverside half of the door doesn't notice this.
