### ISSUE TITLE
Hello, things disappear in my warehouse after I quit the game, but so far I just noticed that every single thing disappears, I now have version 0.13.62-ALPHA-universal

### ISSUE THREAD

**Issue by Epeeckwar** [ldtteam/minecolonies#5458]
# Prerequisites

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies [Wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**
- [x] This is an issue and not a feature request. Please create all feature requests [here](https://github.com/ldtteam/minecolonies-features/issues).

### Context

- Minecraft Version:
- MineColonies Version:
- Related Mods and Their Versions:

### Steps to reproduce the issue

1. 
2. 
3. 
4. ... Profit

### Logs

- latest.log: 
- crashlog:

**Comment by Raycoms** [comment]
Yes, version 62 is broken. Please update to a newer one (we have removed version 62 from curse shortly after release)
