### ISSUE TITLE
still getting crash on place items 15.2

### ISSUE THREAD

**Issue by tails1974seeyounextgame** [ldtteam/minecolonies#5460]
still getting crash on place items 15.2 

game instantly saves and unloads when trying to make ANY mod building using the gui. 

nothing in the log.

happened in a completely different modpack too. ill try running it with just jei and post back.

**Comment by Raycoms** [comment]
There must be something in the log.

**Comment by tails1974seeyounextgame** [comment]
just tested on a flatlands with literally only the mod enabled and jei- toggled to non creative and it crashed. ill attempt to find some portion of log

**Comment by tails1974seeyounextgame** [comment]
[crash-2020-07-26_06.17.39-client.txt](https://github.com/ldtteam/minecolonies/files/4977663/crash-2020-07-26_06.17.39-client.txt)
k. i cant make heads or tails of the log tho, if you figure it out please do tell

**Comment by Raycoms** [comment]
You're on the wrong structurize version, go to the latest alpha of both structurize and minecolonies.

**Comment by tails1974seeyounextgame** [comment]
i checked curseforge for the latest version and according to it that is the latest.. wheres the alpha?

**Comment by Raycoms** [comment]
click on "view all" to see the alpha.

**Comment by tails1974seeyounextgame** [comment]
thank you. ill try it now and report back, i get the sensation their may still be issues when i activate the other mods

**Comment by tails1974seeyounextgame** [comment]
ok im highly confused about your naming structure. the first alpha for 15.2 is on the second page, shouldnt i be using a beta (third iteration)?

**Comment by tails1974seeyounextgame** [comment]
it may be more effective to give a direct download link, for me and for others probably making the same mistakes.

**Comment by ravenbuilder934** [comment]
https://www.curseforge.com/minecraft/mc-mods/minecolonies/files/3015097 for minecolonies and https://www.curseforge.com/minecraft/mc-mods/structurize/files/3015073 for structurize

**Comment by tails1974seeyounextgame** [comment]
you are awesome. have kickass day

**Comment by ravenbuilder934** [comment]
np

**Comment by tails1974seeyounextgame** [comment]
face desks
the first one is for 16.1 not 15.2

**Comment by ravenbuilder934** [comment]
oops, try https://www.curseforge.com/minecraft/mc-mods/structurize/files/3015068 instead (for structurize)

**Comment by tails1974seeyounextgame** [comment]
will report on the status once i load up the mods

**Comment by tails1974seeyounextgame** [comment]
ok it worked without other mods. testing with all the mods , crosses fingers.

**Comment by tails1974seeyounextgame** [comment]
success!!!!! now for optifine and my premium shaders and resource packs xD

**Comment by ravenbuilder934** [comment]
Optifine doesn't work with MineColonies, the textures glitch

**Comment by tails1974seeyounextgame** [comment]
supposedly they fixed that 3 builds ago.. i hope it does.

**Comment by ravenbuilder934** [comment]
wdym? it wasn't fixed, it's Optifine's fault

**Comment by tails1974seeyounextgame** [comment]
what i mean is three builds ago optifine released something that fixes render glitches on both amd and nvidia

**Comment by ravenbuilder934** [comment]
oh. I think that's different tho. This glitch has to do with forge multipart models (or something like that)

**Comment by tails1974seeyounextgame** [comment]
![image](https://user-images.githubusercontent.com/5803466/88481160-b4523680-cf0e-11ea-93a5-a5e8db5c09ea.png)
nope works fine now. i still have yet to test my packs but there it is.

**Comment by ravenbuilder934** [comment]
it's only the hut blocks

**Comment by tails1974seeyounextgame** [comment]
testing in progress xD

**Comment by tails1974seeyounextgame** [comment]
damn even the icon preview is missing. looks like its fixed for 16.1 tho on your end?

**Comment by tails1974seeyounextgame** [comment]
"This reverts commit 8af28ef4625f763f835231299df859f25d426f15. * Fix Optifine compatibility (#113)" ? cant tell if that undoes the fix or redoes the fix. but 15.2 version in that commit crashes tho huh

**Comment by Nightenom** [comment]
That's structurize commit making building previews render when using shaders and optifine. Hut blocks having missing texture is completely different problem
