### ISSUE TITLE
[1.15.2] server crash from ServerHangWatchdog

### ISSUE THREAD

**Issue by jarquafelmu** [ldtteam/minecolonies#5463]
# Prerequisites

- [ ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [ * ] I checked the MineColonies [Wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [ * ] I made sure that **this issue is not a duplicate of any existing issue.**
- [ * ] This is an issue and not a feature request. Please create all feature requests [here](https://github.com/ldtteam/minecolonies-features/issues).

### Context

- Minecraft Version: 1.15.2
- MineColonies Version: 0.10.771-RELEASE-universal
- Related Mods and Their Versions:

### Expected behavior

The server not crash

### Actual behaviour

     The server crashed while player was exploring and generating chunks

### Steps to reproduce the issue

     I'm not really sure

1. 
2. 
3. 
4. ... Profit

### Logs

- latest.log: https://gist.github.com/jarquafelmu/654b73bfa1f0df67013ea68066d10fa4
- crashlog: https://gist.github.com/jarquafelmu/f7278bc975897817020b3d08dcc8a659

**Comment by Raycoms** [comment]
Please run: I am running the latest alpha version of MineColonies for my Minecraft version.

To check if it is still occuring.

**Comment by Raycoms** [comment]
You are 300 versions behind
