### ISSUE TITLE
Pathfinding(?) with citizens huts

### ISSUE THREAD

**Issue by Jackman3323** [ldtteam/minecolonies#5464]
There's a frustrating bug where anyone other than deliverymen can't correctly pathfind to citizen huts that they are assigned to. They pace back and forth right outside but don't go in and sleep.

**Comment by Raycoms** [comment]
Probably means the beds are occupied. Is there some blck, torch or banner above them?

**Comment by someaddons** [comment]
reports not following the template are frustrating too and won't be considered :)
