### ISSUE TITLE
Farmer keeps asking to define seeds in scarecrow

### ISSUE THREAD

**Issue by ffgghhjj** [ldtteam/minecolonies#5465]
# Prerequisites

- [yes ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [yes ] I checked the MineColonies [Wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [yes ] I made sure that **this issue is not a duplicate of any existing issue.**
- [yes] This is an issue and not a feature request. Please create all feature requests [here](https://github.com/ldtteam/minecolonies-features/issues).

### Context

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.75 ALPHA
- Related Mods and Their Versions: 

### Expected behavior

Farmer working. Fields keeping their seeds defined without going away.

### Actual behaviour

Farmer keeps asking to define what seed to plant in each farm plot. I have to continuously define what seed a farmer should plant in each field.

### Steps to reproduce the issue

1.  Define a seed for a farmer to plant in a field
2.  go away, do other things
3.  come back after some time, farmer is doing nothing and is asking that you define what seeds she should plant in a given field
4. ... Profit

### Logs

- latest.log: 
- crashlog:

**Comment by Djidjey** [comment]
i have the same issue. how can i fix this ? 
![image](https://user-images.githubusercontent.com/93743322/231570936-38e46326-3c31-47df-817d-bc53b1cf9832.png)

**Comment by Thodor12** [comment]
Please do not necro-bump years old issues, make a new one
