### ISSUE TITLE
Town Hall  Medieval Oak ( up to 2 level)

### ISSUE THREAD

**Issue by DartVeiper** [ldtteam/minecolonies#5466]
Hi. I want to improve my town hall to level 2, all the resources the Builder accepts, but the yellow flag that needs to be painted, he does not want to accept. Help please
![image](https://user-images.githubusercontent.com/68863462/88562515-730a7580-d039-11ea-8f52-1253aeed1b3c.png)
![image](https://user-images.githubusercontent.com/68863462/88562580-87e70900-d039-11ea-88a7-3f3a4abcf6dd.png)
![image](https://user-images.githubusercontent.com/68863462/88562642-9af9d900-d039-11ea-93dc-860107ebf6d3.png)

**Comment by ravenbuilder934** [comment]
Give him a plain yellow banner, he magically paints it himself.

**Comment by DartVeiper** [comment]
He doesn't want to take the yellow flag either.

**Comment by Raycoms** [comment]
Please fill out the issue template accordingly.

**Comment by DartVeiper** [comment]
How do I fill it out correctly?

**Comment by Raycoms** [comment]
We need your mod version and minecraft version at least.

**Comment by DartVeiper** [comment]
Minecraft 1.12.2, 
![image](https://user-images.githubusercontent.com/68863462/88564837-68051480-d03c-11ea-9add-90e91cad645f.png)

**Comment by Raycoms** [comment]
Yep, that's a bug that was fixed in 1.15. Unfortunately we can't offer 1.12 support anymore because of lack of time.
