### ISSUE TITLE
Game crash upon pressing start in the launcher.

### ISSUE THREAD

**Issue by TYRAlan** [ldtteam/minecolonies#5467]
After pressing start in the game launcher everything goes smoothly, the game loads and everything is fine until finally it finished loading and tells me the following: "Error loading mods 1 error has occurred during loading". in red text followed by: "Mod File structurize-0.13.28-ALPHA.jar needs language provider javafml.32 or abote to load." Please help me solve this issue! I also attached the latest.log if that helps! 

Much love: TYRAlan
[latest.txt](https://github.com/ldtteam/minecolonies/files/4986665/latest.txt)

**Comment by Talyda** [comment]
Just checking - you did realise that is the structurize version for 1.16?

**Comment by Raycoms** [comment]
Additionally, you are running the wrong java version. Please get java8.
