### ISSUE TITLE
Crash issue please help

### ISSUE THREAD

**Issue by TYRAlan** [ldtteam/minecolonies#5468]
# Prerequisites

- [yes] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [yes] I checked the MineColonies [Wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [yes] I made sure that **this issue is not a duplicate of any existing issue.**
- [yes] This is an issue and not a feature request. Please create all feature requests [here](https://github.com/ldtteam/minecolonies-features/issues).

### Context

- Minecraft Version: 1.15.2-forge-31.2.33
- MineColonies Version: 0.10.771-RELEASE-universal
- Related Mods and Their Versions: structurize-0.10.313-RELEASE

### Expected behavior

Have a supply camp placed down and get started with my own colony.
### Actual behaviour
The preview loads in fine and I can move the building around using the arrows. Once I press the green check mark the game lags out and then crashes giving me a screen with: "saving world" and then the game closes.

Once I find the perfect location for the camp and I press the green check mark it all freezes, crashes and closes bringing me back to the launcher with an error screen.
![image](https://user-images.githubusercontent.com/68893172/88643546-7ef24800-d0ca-11ea-8ed6-d145b697ca3a.png)

### Steps to reproduce the issue

1.  Load into world and find a suitable place to put down the camp.
2.  Click the green check mark when ready to put the camp down.
3.  The game freezes and crashes.
4. ... Profit

### Logs

- latest.log: 
- crashlog:  https://gist.github.com/TYRAlan/7082f6893a3fa56112f56703d5e09a7c

**Comment by Raycoms** [comment]
Update structurize to latest alpha and minecolonies too.
