### ISSUE TITLE
Ranger accidentally walked into lava, crashing the game

### ISSUE THREAD

**Issue by SurfShackTito** [ldtteam/minecolonies#5470]
# Prerequisites

- [ ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x ] I checked the MineColonies [Wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**
- [x ] This is an issue and not a feature request. Please create all feature requests [here](https://github.com/ldtteam/minecolonies-features/issues).

### Context

- Minecraft Version:  1.15.2
- MineColonies Version:  0.13.29
- Related Mods and Their Versions:

invtweaks 1.15.2-2.0.8
jei-1.15.2-6.0.2.12
structurize 0.13.8

### Expected behavior

Ranger steps into lava, takes damage and either lives or dies

### Actual behaviour

Ranger stepped into lava and after about 2-3 damage ticks, the server crashed giving an error of 'removing entity whil ticking'

Uploaded and linked via gist

### Steps to reproduce the issue

1.  Barracks based ranger, no armor, plain bow
2.  Jumped up to go up a block, pushed(?) by another ranger in the same group into lava.
3.  Ranger ticks and server crashes
4. ... Profit

### Logs

- latest.log: 
- crashlog: 
https://gist.github.com/SurfShackTito/6c1aba266358d427ad3a20e3cb1a2f13

**Comment by Raycoms** [comment]
That log doesn't tell us anything, can you send us the latest.log too?
