### ISSUE TITLE
The baker cannot make bread

### ISSUE THREAD

**Issue by q107580018** [ldtteam/minecolonies#5471]
# Prerequisites

- [yes ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [yes ] I checked the MineColonies [Wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**
- [ ] This is an issue and not a feature request. Please create all feature requests [here](https://github.com/ldtteam/minecolonies-features/issues).

### Context

- Minecraft Version:1.15.2
- MineColonies Version:0.13.78 alpha
- Related Mods and Their Versions:

### Expected behavior
The baker makes every three wheats into bread

### Actual behaviour
The baker always consumes wheats, but does not produce bread

### Steps to reproduce the issue

1. 
2. 
3. 
4. ... Profit

### Logs

- latest.log: 
- crashlog:

**Comment by Mekle001** [comment]
Can you confirm that the bread doesn't eventually show up? The baker behaves very differently from other crafters, and consumes ingredients quite a while before it produces output.

**Comment by q107580018** [comment]
yes, I cry again.I gave her 64 wheats, she consumes 3 wheats every three seconds, and eventually the wheat ran out, but none of the bread was produced

**Comment by q107580018** [comment]
Is its mechanism to consume wheat first and then slowly produce bread? Because I found a bread later

**Comment by q107580018** [comment]
oh! i am sorry. It's not a BUG. just need long time
