### ISSUE TITLE
messageColonistDead error

### ISSUE THREAD

**Issue by ghost** [ldtteam/minecolonies#5472]
Why did the colonists show up when they died tile.blockHutTownHall.messageColonistDead instead of 市民%s已于%d%d%d（%s）死亡！
minecraft version: 1.12.2
mod version: 1.12.2-0.11.841-ALPHA
[zh_cn.txt](https://github.com/ldtteam/minecolonies/files/4992603/zh_cn.txt)

**Comment by Raycoms** [comment]
Unfortunately we do not offer fixes for 1.12 anymore due to a lack of time. Since it is not a critical bug.
