### ISSUE TITLE
Only one chunk loads

### ISSUE THREAD

**Issue by cvialar** [ldtteam/minecolonies#5474]
# Prerequisites

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies [Wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**
- [x] This is an issue and not a feature request. Please create all feature requests [here](https://github.com/ldtteam/minecolonies-features/issues).

### Context

- Minecraft Version: 1.15.2-forge-31.2.33
- MineColonies Version: minecolonies-0.13.78-ALPHA-universal
- Related Mods and Their Versions: structurize-0.13.27-ALPHA

### Expected behavior

Should load more than one unique chunk

### Actual behaviour

Only loads one chunk (the initial spawn's chunk); impossible to get out of it without flying; blocks don't load, you can definitely land on them even though it makes your character shiver constantly.

![image](https://user-images.githubusercontent.com/64534895/88815253-6d3c9d80-d1bb-11ea-9f99-13c3e9e9a93b.png)

### Steps to reproduce the issue

1. Use aforementioned forge, minecolonies and structurize versions
2. Have these few mods installed (working perfectly before Minecolonies): 
![image](https://user-images.githubusercontent.com/64534895/88815450-aaa12b00-d1bb-11ea-95c7-8cb954a08efe.png)

3. Create or load into an existing world

4. ... Profit

### Logs

- latest.log: (sorry parts of it are in French)
https://gist.github.com/kauraneden/a657c1ab8c22a8b3b662a6177df353b9.js

**Comment by ravenbuilder934** [comment]
Wait, you have OptiFine? OptiFine doesn't work well with MineColonies. Try removing it and see if that helps.

**Comment by Raycoms** [comment]
But it's not related to optifine + minecolonies. This is optifine alone causing this. Try to do f3 + a to reload the chunks and see if optifine loads more chunks. But this is 100% sure not minecolonies causing it.

**Comment by ravenbuilder934** [comment]
Already tried F3 + A, it didn't do anything (not even the right chat message)
