### ISSUE TITLE
Using Twitch Launcher pulls up regular minecraft rather than the modpack

### ISSUE THREAD

**Issue by Ahshed** [ldtteam/minecolonies#5480]
# Prerequisites

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies [Wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**
- [x] This is an issue and not a feature request. Please create all feature requests [here](https://github.com/ldtteam/minecolonies-features/issues).

### Context

- Minecraft Version:1.15.2
- MineColonies Version:1.6
- Related Mods and Their Versions:

### Expected behavior
I would be able to play the mod pack from the launcher

### Actual behaviour

Minecraft loads up but is regular minecraft that says its modded without having the mod pack
### Steps to reproduce the issue

1. download the official modpack from the twitch desktop app
2. run the modpack

**Comment by Raycoms** [comment]
You should potentially contact twitch then and not us about this. It works fine for the rest of us.
