### ISSUE TITLE
Like 5419, Crusher breaks request system

### ISSUE THREAD

**Issue by kd5crs** [ldtteam/minecolonies#5484]
![2020-08-01_00 01 20](https://user-images.githubusercontent.com/50682958/89094513-46809180-d38a-11ea-9dec-220e1ddb722d.png)
# Prerequisites

- [X ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [X ] I checked the MineColonies [Wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**
- [X ] This is an issue and not a feature request. Please create all feature requests [here](https://github.com/ldtteam/minecolonies-features/issues).

### Context

- Minecraft Version: 1.15.2
- MineColonies Version: minecolonies-0.13.84-ALPHA-universal
- Related Mods and Their Versions:

### Expected behavior

Crusher processes requests like other workers.

### Actual behaviour

Crusher looks like he is working, but the quantities in inventory never change, the requests never complete, and the daily quantities on Page 2 of the Crusher's Hut are never made.

### Steps to reproduce the issue

1. I don't know, I think the Crusher was working when I first built the hut, but there's nothing now. There's no detail on the Crusher or Crusher's Hut pages to help diagnose what should be happening except the particles popping up from the hut block (see attached picture).

### Logs

- latest.log: 
- crashlog:

**Comment by nsluhrs** [comment]
I too am seeing this in 0.13.61
