### ISSUE TITLE
Decoration controller not saving data

### ISSUE THREAD

**Issue by bizarremonkey1** [ldtteam/minecolonies#5486]
# Prerequisites

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies [Wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**
- [x] This is an issue and not a feature request. Please create all feature requests [here](https://github.com/ldtteam/minecolonies-features/issues).

### Context

- Minecraft Version: 1.15.2
- MineColonies Version: minecolonies-0.13.84-ALPHA-universal.jar
- Related Mods and Their Versions: [mods.txt](https://gist.github.com/bizarremonkey1/934a084a5a9d0f2f30c5b8adf7d2e617)

### Expected behaviour

When placing fortress walls using the build tool, the builder builds the wall. When the level 1 build is finished the correct data should be stored in the decoration controller and upgrade is possible.

### Actual behaviour

Place the fortress wall 1 blueprint. The builder finishes building but the data in the decoration controller is not updated. Clicking the upgrade button straight away creates a rotated build request of the level 1 wall (not shown in video). Upon logging out and back into the world there is no data displayed in the decoration controller at all.

https://youtu.be/500Dp-LUXPg

### Steps to reproduce the issue

1. Place fortress wall level 1.
2. Wait for the builder to finish.
3. Log out and back in.
4. Check the decoration controller.
5. ... Profit

### Logs

- latest.log: [latest.log](https://gist.github.com/bizarremonkey1/dfcfc4606f0cebd040a22ac9534ec837)
- crashlog: no crash
- debug.log: [debug.log](https://gist.github.com/bizarremonkey1/ae726842db1a1a4de2bf7df1815142f3)

**Comment by bizarremonkey1** [comment]
May be related to #5168 and #5095 although it seems those issues were waiting for an appropriate response and got none.

**Comment by Raycoms** [comment]
Atm it is pretty static how the controller handles data so it has to be set exactly by the creator of the structure to fit the exact folder structure and leveling scheme. this will be improved in the future. But up to now it's a schematic issue.
