### ISSUE TITLE
Russian text builder GUI crawls out of scope

### ISSUE THREAD

**Issue by FireGuyVT** [ldtteam/minecolonies#5488]
![image](https://user-images.githubusercontent.com/46681676/89108076-6e313180-d43e-11ea-8c34-bdde73088bf2.png)
It's page builder's restrictions
It seems that adding a page to the GUI would solve this problem
requisites
- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies [Wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**
- [x] This is an issue and not a feature request.

**Comment by Raycoms** [comment]
yeah, you'll have to translate it shorter then and try to find shorter ways. We can't do this in code.
