### ISSUE TITLE
[0.13.86-ALPHA] mouseClicked crash on setting up supply camp

### ISSUE THREAD

**Issue by jarquafelmu** [ldtteam/minecolonies#5489]
# Prerequisites

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies [Wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**
- [x] This is an issue and not a feature request. Please create all feature requests [here](https://github.com/ldtteam/minecolonies-features/issues).

### Context

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.86-ALPHA
- Related Mods and Their Versions: Structurize

### Expected behavior

The Supply camp should place and the user should not crash

### Actual behaviour

When the client clicks the confirm checkmark the user and client crash but the server stays online

![image](https://user-images.githubusercontent.com/5807272/89113531-92394680-d42f-11ea-9620-f8b180988814.png)

### Steps to reproduce the issue

1. Get a camp
2. Prepare to place it
3. Hit that green checkmark
4. ... Profit

### Logs

- latest.log: https://gist.github.com/jarquafelmu/ee8651e3638914f7397724e6062da9aa
- crashlog: https://gist.github.com/jarquafelmu/e87debcc5c329f247b7488a2b48c5222

**Comment by Talyda** [comment]
You're placing it with the build tool - unless something has changed, you are supposed to place it by using the supply camp item (in theory you shouldn't even have a build tool until after you have placed the camp)

**Comment by Raycoms** [comment]
Downgrade structurize version by one. Newest structurize API changes will be fixed with next version.
