### ISSUE TITLE
Scan/Build Tool bug

### ISSUE THREAD

**Issue by Warrof** [ldtteam/minecolonies#549]
### Minecolonies version

0.6.2604

Minecraft Ver 1.11.2 out of the curse modpack

### Expected behavior

1. 
Scanning/Building all entities in a build

2. 
Also, Scanning in Blocks that are not there.

### Actual behavior

1. 
Not building All Entities.

2. 
Scanning only the block that are there.

### Steps to reproduce the problem

1. 
I've scanned in an Iron Golem Farm, which requires a minimum of 10 Villagers over 4 separate places within the build.  To make sure I had enough I placed 6 Villagers in each pocket.

The Builder Chest on 'No Unlimited Resources' shows only 12 Villager spawns required, out of what should be 24.

 
2. 
Also, The Builder Chest shows 3 'Stone Monster Egg' as part of the build.  Why?  I didn't put those in.  Unless it's referring to the Iron Golem that got scanned in as part of the build.

![2017-02-04](https://cloud.githubusercontent.com/assets/21962742/22622946/d6e0a968-eafe-11e6-8976-a0e67347068a.png)

**Comment by Raycoms** [comment]
I bet you put in stone monster egg by accident. They almost look like
normal stone blocks. Ask Peter =D

We're using vanilla mechanics here, it's minecraft itself which doesn't
recognize all the entities it should.

2017-02-04 23:26 GMT-02:00 Warrof <notifications@github.com>:

**Comment by Warrof** [comment]
Yeah, I looked in my inventory and it turned out the block i was using was Monster Egg.

Ohh, I didn't know that.  So i should be happy that 12 will spawn in?

**Comment by xavierh** [comment]
@Raycoms ready to be closed ?
