### ISSUE TITLE
My AI has run to issue...

### ISSUE THREAD

**Issue by perecnicek** [ldtteam/minecolonies#5491]
# Prerequisites

- [ ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [ ] I checked the MineColonies [Wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**
- [x] This is an issue and not a feature request. Please create all feature requests [here](https://github.com/ldtteam/minecolonies-features/issues).

### Context

- Minecraft Version: 1.15.2
- MineColonies Version: minecolonies-0.13.81-RELEASE-universal
- Related Mods and Their Versions: structurize-0.13.19-ALPHA

### Expected behavior

Baker after switching off his setting to made bread he would just stood and do nothing.

### Actual behaviour

I switch off making bread with my baker and he got this error 
"My AI has run to issue.." and after him few more citizens started getting this issue too my 2 builders also got this issue

### Steps to reproduce the issue

1. 
2. 
3. 
4. ... Profit

### Logs

- latest.log:  https://gist.github.com/perecnicek/319cefd116655121a36df08a7cb35e44
- crashlog:

**Comment by mrPaintMan** [comment]
Hello,

I had the same issue with a knight in the barracks. He requested a sword, and when receiving an iron sword, the same error was shown. 

Once the error was discarded, the knight restarted and seemed fine. The error only occurred once.

Minecraft version: 1.15.2
Minecolonies version: 0.13.85-ALPHA

lates.log: [https://pastebin.com/jsPxaeGr](https://pastebin.com/jsPxaeGr)
