### ISSUE TITLE
[1.15.2] Crash when accessing chest with build tool in hand

### ISSUE THREAD

**Issue by Drethic** [ldtteam/minecolonies#5493]
# Prerequisites

- [ ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies [Wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**
- [x] This is an issue and not a feature request. Please create all feature requests [here](https://github.com/ldtteam/minecolonies-features/issues).

### Context

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.86-Alpha
- Structurize Version: 0.13.35-Alpha
- Related Mods and Their Versions: Please see Craft to Exile version 2.1.3b for full list/versions.

### Expected behavior

Chest opens

### Actual behaviour

With the build tool in right hand and trying to access a chest (tried regular and spruce) the game crashes.  This may be related to 
#5492 as it has the same NoSuchMethodError but being called from different places.

### Steps to reproduce the issue

1. Have "Craft to Exile v2.1.3b" mod pack
2. Run game in multiplayer on a server
3. Right click a chest (regular or spruce) with Builder Tool to access the inventory
4. Crash happens to desktop.  Tested with multiple people on the server.  

### Logs

- crashlog: [Crash Log on Pastebin](https://pastebin.com/PGNPERqS)

**Comment by Raycoms** [comment]
Update minecolonies
