### ISSUE TITLE
Ai teleporting on roofes or into lava

### ISSUE THREAD

**Issue by KarmaCoraa** [ldtteam/minecolonies#5496]
# Prerequisites

- [ ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [ ] I checked the MineColonies [Wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**
- [x ] This is an issue and not a feature request. Please create all feature requests [here](https://github.com/ldtteam/minecolonies-features/issues).

### Context

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.88-beta
- Related Mods and Their Versions:
Structurize 0.13.35-alpha
### Expected behavior

Not teleporting into lava or roofes

### Actual behaviour

the guard teleport them selves into lava underground but there are no mobs or anything.
the npc's teleporting on the roofs  but there is no way to get up there

**Comment by AngellusMortis** [comment]
It is not just guard that do this. It is also visitors to the tavern. I keep having mine teleport to the tops of houses and then fall to their death (Nordic style so super tall roofs). Then I get the message saying my tavern is unsafe and I will get less travelers. 

Guards you can set up manual patrol points to get around them suiciding, but you cannot do that with the visitors. 

It makes sense that the NPCs might need to teleport to get themselves "unstuck", but maybe some stricter rules on where they can teleport too? First thought is only to block that are exposed to sky and not a "building block" like wood, stone, cobblestone etc.

**Comment by JonesiBlitz** [comment]
> It makes sense that the NPCs might need to teleport to get themselves "unstuck", but maybe some stricter rules on where they can teleport too? First thought is only to block that are exposed to sky and not a "building block" like wood, stone, cobblestone etc.

Also maybe attempt to run a pathfinding algorithm on returning to their home from the teleported to spot to see if that can be completed prior to teleportation.

**Comment by Raycoms** [comment]
fixed
