### ISSUE TITLE
Occasional crash when right-clicking the Lumberjack colonist

### ISSUE THREAD

**Issue by WenXin20** [ldtteam/minecolonies#5503]
# Prerequisites

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies [Wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**
- [x] This is an issue and not a feature request. Please create all feature requests [here](https://github.com/ldtteam/minecolonies-features/issues).

### Context
- `Minecraft v1.15.2`
- `MineColonies v0.13.89-Alpha`
- `Structurize v0.13.35-Alpha`

### Expected behavior
- No Crashes

### Actual behaviour
- My game occasionally will crash after right-clicking the Lumberjack colonist.

### Steps to reproduce the issue
1. Right-click the colonist
4. ... Profit

### Logs

- [Crash Report](https://gist.github.com/WenXin20/078c0c1c28b93394eb8c9156ab4d9e91)

**Comment by Raycoms** [comment]
Yes, this is a forge issue. They merged the fix, but I'm not sure if it entered 1.15.2 already since it's the modloader part.

**Comment by WenXin20** [comment]
Ok thanks
