### ISSUE TITLE
Icons and Textures [bug]

### ISSUE THREAD

**Issue by xXLightAngelXx** [ldtteam/minecolonies#5507]
Some of the Icons for Items in your Mod are iccorectly displayed and/or missing and the objects themself invisable due to missing object textures.

Why Update to Forge 3.33 [Latest] when you knew in advance from other people that it has issues with correctly loading assets from the minecolonies mod?

It is my strongest advise that if you update to a version of a modloader that struggles to work correctly with your mod that you either get in contact with the Mod Loader Devs and have them try to rectify it or create a Libary mod that has the correct objs etc and make it a required mod for the minecolonies mod to fix the issue.

**Comment by Raycoms** [comment]
Are you sure you're not using optifine?

**Comment by xXLightAngelXx** [comment]
I am sure I tried it both with and without

**Comment by xXLightAngelXx** [comment]
It was also addressed previously by other players on the forum to the devs that it occurs prior to the Modpack beign udpated to latest forge version

**Comment by Raycoms** [comment]
And I'm going to close this issue until you grow some human decency to word an issue without attacking the mod developers that are offering you this service for free.

**Comment by Raycoms** [comment]
Btw, this works perfect for me, with forge >= 31.2.33

**Comment by xXLightAngelXx** [comment]
Has nto for me and sorry for being breash

**Comment by Raycoms** [comment]
So another mod is causing this. It works perfect for us. I'm sure optifine causes this. But that is THEIR fault and not ours. Maybe there is another mod that fucks up rendering in a stupid way.

**Comment by xXLightAngelXx** [comment]
Also is it possible to make it so you can have multiple conoloies in 1 world? or is that intetional that onyl one is allowed per world?

**Comment by Raycoms** [comment]
For these kind of questions please visit our discord.

**Comment by xXLightAngelXx** [comment]
Whats ur link for disc?

**Comment by ravenbuilder934** [comment]
https://discord.minecolonies.com
