### ISSUE TITLE
memory leak?

### ISSUE THREAD

**Issue by igoldarm** [ldtteam/minecolonies#5509]
# Prerequisites

- [ x ] I am running the latest **alpha** version of MineColonies for my Minecraft version.

- [ x ] I checked the MineColonies [Wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [ x ] I made sure that **this issue is not a duplicate of any existing issue.**
- [ x ] This is an issue and not a feature request. Please create all feature requests [here](https://github.com/ldtteam/minecolonies-features/issues).

### Context

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.95-ALPHA
- Related Mods and Their Versions: Structurize 0.13.35-ALPHA

### Expected behavior

Joining the server as normal

### Actual behaviour

message when trying to connect to server:
Internal exeption io.netty.handler.codec.decoderExeption: java.io.IOExeption: payload may not be larger than 1048576 bytes

### Steps to reproduce the issue

 Do not know how to reproduce,
sorry.

### Logs

- latest.log: https://gist.github.com/igoldarm/94deba30c47bbd4281382818ac6b8494
Line 4637: [06Aug2020 20:42:20.188] [Server thread/WARN] [minecolonies/]: Colony 1 has a very big memory imprint, this could be a memory leak, please contact the mod author!
- crashlog:  Server does not crash but simply shuts off after awhile, does not generate a crash log.

**Comment by Raycoms** [comment]
yeah. We had a problem in the past with this. It was fixed already but the big files remain. You can run the /mc colony requestsystem-reset-all command
