### ISSUE TITLE
AI issue

### ISSUE THREAD

**Issue by nebc** [ldtteam/minecolonies#5511]
# Prerequisites

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies [Wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**
- [x] This is an issue and not a feature request. Please create all feature requests [here](https://github.com/ldtteam/minecolonies-features/issues).

### Context

- Minecraft Version: 0.13.79-ALPHA
- MineColonies Version: 1.15.2 forge (Sightly tweaked Valhelsia 2 Modpack)
- Related Mods and Their Versions:

### Expected behavior

The farmer stops working and says it is having an AI issue and to report it. The farmer should plant and harvest fields but doesn't.

### Actual behaviour

Farmer says she has an AI issue and stops working. Firing and rehiring fixes it for a short time. No input from user causes the bug, it happens on its own.

### Steps to reproduce the issue

Have a farmer and wait? Unknown trigger.

1. 
2. 
3. 
4. ... Profit

### Logs

- latest.log: https://gist.github.com/nebc/7c63b6e97badb09848cf361f9c9063cd
- crashlog: No crash.

**Comment by ShadowProtocol** [comment]
Update to the latest alpha. 0.13.95 I think.
