### ISSUE TITLE
Lvl 3 farm only have 2 fields?

### ISSUE THREAD

**Issue by lucas02061** [ldtteam/minecolonies#5513]
The wiki says a lvl 3 farm can have 3 fields, but my own lvl 3 farm only has access to 2 fields?

(I have th newest version as of today 7th august)

**Comment by Raycoms** [comment]
how close is the third field to the farmer
and how long did you wait for automatic assignment to work?
And how did you test potatoes, they work very well for us on our server atm?

**Comment by lucas02061** [comment]
20-30 blocks away. Although that should not be the problem since i changed
the same field to carrots which worked fine

fre. 7. aug. 2020 18.04 skrev Raycoms <notifications@github.com>:

**Comment by lucas02061** [comment]
I just placed a field put in a potato and let it run? He used the hoe on
the field, but that was it. He did not touch it for 60 min. After changing
it to carrots he started planting right away

fre. 7. aug. 2020 18.04 skrev Raycoms <notifications@github.com>:

**Comment by Raycoms** [comment]
Did he have the potatoes in his inventory? Were there potatoes planted already? What version is this on?

**Comment by lucas02061** [comment]
Im not on my pc right now, but updated yesterday.

He had potatoes in his inventory but i could see that he made a request for
potatoes.

fre. 7. aug. 2020 18.52 skrev Raycoms <notifications@github.com>:
