### ISSUE TITLE
Negative percentages sometimes when building

### ISSUE THREAD

**Issue by lucas02061** [ldtteam/minecolonies#5515]
![unknown](https://user-images.githubusercontent.com/61451563/89661023-753ec080-d8d2-11ea-8477-9bd299878bd3.png)

As you can see on the picture, the building is negative done? :b i have not touched the building/helped the construction of the building. It has only happened to the mine lvl2 and cook lvl1 for now.

(I have updated to the newest version as of today the 7th of august)

**Comment by Raycoms** [comment]
fixed
