### ISSUE TITLE
Lumberjack requests Hoe to cut trees

### ISSUE THREAD

**Issue by Dyonovan** [ldtteam/minecolonies#5517]
# Prerequisites

- [X ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [X ] I checked the MineColonies [Wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [X ] I made sure that **this issue is not a duplicate of any existing issue.**
- [X ] This is an issue and not a feature request. Please create all feature requests [here](https://github.com/ldtteam/minecolonies-features/issues).

### Context

- Minecraft Version: 1.16.1
- MineColonies Version: commit-68087d4
- Related Mods and Their Versions: 
      Structurize: 0.13.37-ALPHA
      Forge: 32.0.106
### Expected behavior

Lumberjack would use up the hoe completly before asking for another

### Actual behaviour

Lumberjack puts almost new hoe back into hut inventory and asks for another

### Steps to reproduce the issue

1. Give Lumberjack a new wooden hoe
2. Wait for lumberjack to return slightly used hoe to hut inventory
3. Pull hoe out of hut inventory then return same hoe to hut inventory
4. Lumberjack takes used hoe and only uses it for a couple times. Rinse and repeat

### Logs

- latest.log: https://gist.github.com/Dyonovan/eaf87b708050fc7cabfbd395b73efc68
- crashlog: no crash

**Comment by Raycoms** [comment]
Hoe, or axe?

**Comment by Dyonovan** [comment]
Hoe. Axe seems to work fine. To be honest, dont know why he would use a hoe.

**Comment by Raycoms** [comment]
He will probably use the hoe once, notice it's not an axe. And stop using it. He needs an axe.

**Comment by Dyonovan** [comment]
https://gyazo.com/37c7c29ffa3d3312e63464c0b865d5d1
https://gyazo.com/bfa7fc6a84b68c9d101f3a039c20ee65
Hes asking for a hoe

**Comment by Raycoms** [comment]
Wth, I'll check on this tomorrow...

**Comment by Raycoms** [comment]
I adjusted the issue name

**Comment by Raycoms** [comment]
fixed

**Comment by Dyonovan** [comment]
Using the latest version/1.16 branch with the lumberjack fix, I am getting the request still/again.

https://gyazo.com/2ba04b4659214237c8f150e822a0b364

**Comment by Raycoms** [comment]
Gotta cancel the past request. New requests will then be fixed

**Comment by Dyonovan** [comment]
Even after cancelling the requests, he is still asking for a hoe. https://gyazo.com/8e261062a6437d50f7d9c4a2d3713ef0
