### ISSUE TITLE
Not a mod

### ISSUE THREAD

**Issue by Zeppo279** [ldtteam/minecolonies#5520]
# Prerequisites

- [x ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x ] I checked the MineColonies [Wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**
- [x ] This is an issue and not a feature request. Please create all feature requests [here](https://github.com/ldtteam/minecolonies-features/issues).

### Context

- Minecraft Version:1.16.1
- MineColonies Version:0.13.96 ALPHA version
- Related Mods and Their Versions:

When loading the game I get a message indicating that minecolonies is not a valid mod.  I am currently using MultiMC to load the game and all the mods I usually used.  It does allow me to go to title screen after it informs me that it is not a mod.  I tried loading it on the two latest forge versions, 106 and 107

**Comment by Nightenom** [comment]
Welp, you have been asked to provide logs, please do so automatically next time

**Comment by Raycoms** [comment]
fixed
