### ISSUE TITLE
Why can't my colony recruit any citizen 

### ISSUE THREAD

**Issue by AndyOoi** [ldtteam/minecolonies#5524]
My colonies is not full still have 10 bed left but why i cannot recruit any citizen?

**Comment by Raycoms** [comment]
a) Research at university
b) Config value

**Comment by ravenbuilder934** [comment]
Are you trying to recruit from the Town Hall? Recruiting has been moved to the Tavern.

**Comment by AndyOoi** [comment]
Huh how??

**Comment by AndyOoi** [comment]
How to change the config?

**Comment by Raycoms** [comment]
it's the minecolonies-common file, search through that one.

**Comment by ravenbuilder934** [comment]
> Huh how??

Visitors will randomly visit your colony if you have a tavern. You can recruit them with items to join your colony. Check the wiki for more info https://wiki.minecolonies.ldtteam.com/source/buildings/tavern
