### ISSUE TITLE
builder not accepting quark 

### ISSUE THREAD

**Issue by madlymercury** [ldtteam/minecolonies#5528]
# Prerequisites

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies [Wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**
- [x] This is an issue and not a feature request. Please create all feature requests [here](https://github.com/ldtteam/minecolonies-features/issues).

### Context

- Minecraft Version: minecolonies-0.13.101-ALPHA-universal
- MineColonies Version:
- Related Mods and Their Versions:

### Steps to reproduce the issue

1. build a building that uses a chest
2. get to the part with the chests
3. the next block is a normal chest and not quark
4. ... Profit

### Logs

- latest.log: 
- crashlog:

**Comment by Raycoms** [comment]
That is a feature request for mod compatibility. This is supposed to be there https://github.com/ldtteam/minecolonies-features/issues
