### ISSUE TITLE
AI error with builder

### ISSUE THREAD

**Issue by nebc** [ldtteam/minecolonies#5529]
# Prerequisites

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies [Wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**
- [x] This is an issue and not a feature request. Please create all feature requests [here](https://github.com/ldtteam/minecolonies-features/issues).

### Context

- Minecraft Version: 1.15.2
- MineColonies Version: minecolonies-0.13.101-ALPHA-universal
- Related Mods and Their Versions: Forge Valhelsia 2 with dungeon crawl mod added and scenic mod removed.

### Expected behavior
Builder builds what she is ordered to.

### Actual behaviour
She stands there ans says my AI has an error

### Steps to reproduce the issue

1. Have builder 
2. Wait for her to complain about AI error
3. 
4. ... Profit

### Logs

- latest.log: https://gist.github.com/nebc/5e8b2287cb2da306b17b5a75af411106
-updated latest.log: https://gist.github.com/nebc/106e4243ba29453fcce6550a7c050be5 
- crashlog:

**Comment by Raycoms** [comment]
Can you do a /mc colony requestsystem-reset ?

**Comment by nebc** [comment]
@Raycoms It says unknown command

**Comment by nebc** [comment]
I built a new builder and he ran into the same issue within the hour, tried firing and rehiring a new person and she had the same problem. I'm using the fortress tileset on a server with a few other people.

**Comment by Raycoms** [comment]
Ye, there is a request system issue. Use auto complete do find /mc colony requestsystem-reset colonyid or so

**Comment by nebc** [comment]
Okay I did that and their both still complaining about their AI, does it take some time or is there something else I should do?

**Comment by Raycoms** [comment]
the message will stay for a while. You can click the "ignore button" to make it go away

**Comment by nebc** [comment]
Now their just standing there. I reset it a few times and it says each time "after 1.618 second it reinstantiated completely new" I've waited 10 minutes to see if it just needed time but their still just standing there.

**Comment by nebc** [comment]
@Raycoms (I don't know if its proper etiquette to @ you so if its not please tell me :)I tried firing and rehiring them after 20 minutes and they just instantly got AI errors again, any other ideas for troubleshooting, should I update my latest.log?

**Comment by DasNilpferd77** [comment]
Try to delete the config files.

**Comment by nebc** [comment]
@DasNilpferd77  That didn't work, the only config things I change are decreasing the build delay to 5 (from 15) and the break delay to 50(from 500), and the disease chance to 30.

**Comment by nebc** [comment]
I see that there are some new updates, one of them hot fixed delivery man, will that help me out?

**Comment by DasNilpferd77** [comment]
i deleted both minecolony config files and have no problems no

**Comment by nebc** [comment]
I tried and I'm still having the problem, not sure what to do

**Comment by Raycoms** [comment]
Reupload log, upload world and I'll check on it tomorrow

**Comment by nebc** [comment]
I'm not sure how to upload the world so here is a google drive link with it and a readme for the mods you'll need, alternatively it is being hosted on a server so if you would rather just connect once you get the mods then that would work as well.
https://drive.google.com/drive/folders/1sG5HrUEbb6gO8blmkejNpTUzH6x1n_VP?usp=sharing

**Comment by nebc** [comment]
Been fidiling with it and I think it has something to do with the racks in the warehouse, they were arranged in a 2x2 so they fought over which one connected with what and I think the workers had problem seeing what existed and what didn't as the racks were broken, I emptied my warehouse and took out half the racks so none of them were fighting and everyone is working fine now.
