### ISSUE TITLE
[Feature Request] Tinkers Leveling [$5 awarded]

### ISSUE THREAD

**Issue by kedamono** [ldtteam/minecolonies#553]
### Minecolonies version

version 0.6.2595 

### Expected behavior

- As workers use Tinker's Construct tools, such as the Hatchet, the tool will level with use.

### Actual behaviour

- The tool does not level.

### Reasons for this request

It would nice if the workers could level Tinkers Tools using Tinkers Leveling. It would allow the player to upgrade the tool with more "features" from Tinkers making the tool more valuable for use by the worker.

Right now, I have to use a tool to level it up, but never at the rate the colonist use tools. I do understand that this would be difficult, as the leveling requires XP and other mechanisms implemented by Tinkers Leveling. 

But, it would be nice to have.

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=41721334)](https://www.bountysource.com/issues/41721334-feature-request-tinkers-leveling?utm_source=41721334&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by marvin-bitterlich** [comment]
We would need to create a fakeplayer for this as it seems. And that was not a good solution. Tinkers wanted to change that at some point but for now they won't. 

We should make a general issue for all the mod support issues I guess. Would be nice to have a bounty on that one then.

**Comment by DarVillous** [comment]
Tinkers tool leveling currently checks to see if the entity using the tool is a player before applying XP.  
The MoodToolLeveling.java has several checks to see if the EntityLivingBase is an instance of EntityPlayer.  Tinkers construct itself might also have code that would need to change.

https://github.com/SlimeKnights/TinkersToolLeveling/issues/89

**Comment by Raycoms** [comment]
Difficult and OP, I think we should just leave this.
