### ISSUE TITLE
[BUG]Server restart,Miner Unable to read.

### ISSUE THREAD

**Issue by binglingyao** [ldtteam/minecolonies#5530]
# Prerequisites

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
 【minecolonies-0.13.105-ALPHA-universal】

- [x] I checked the MineColonies [Wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
【The url could not be opened for regional reasons or an open error.】

- [x] I made sure that **this issue is not a duplicate of any existing issue.**
【Yes, I'm pretty sure, because many versions have passed and still haven't been fixed.】
【I started with version 85 of version 1.15.2, and now Version 105 of version 1.15.2.】

- [x] This is an issue and not a feature request. Please create all feature requests [here](https://github.com/ldtteam/minecolonies-features/issues).
【It's sure】

### Context

- Minecraft Version:
【Minecraft Version 1.15.2】

- MineColonies Version:
【minecolonies-0.13.105-ALPHA-universal】
【That's right, just six hours ago】

- Related Mods and Their Versions:
【My MOD list】
【inventoryprofiles-forge-1.15.2-0.4.2】
【StorageDrawers-1.15.2-7.0.2】
【minecolonies-0.13.105-ALPHA-universal】
【NetherPortalFix_1.15.2-6.0.2】
【preview_OptiFine_1.15.2_HD_U_G1_pre30】(This item is not on the server, but is owned by the client.)
【ironchest-1.15.2-10.0.3】
【jei-1.15.2-6.0.2.12】
【Harvest-forge-1.15.1-1.2.11-24】
【TravelersBackpack-1.15.2-4.0.6】
【journeymap-1.15.2-5.7.0b3】
【CustomSkinLoader_Forge-14.12-SNAPSHOT-109】
【UtilityWorlds-1.15.2_1.1.0】
【Aquaculture2-1.15.2-2.0.16】
【Morpheus-1.15.2-4.2.50】
【Mine+and+Slash-1.15.2-3.6.14】
【curios-FORGE-1.15.2-2.0.2.6】
【structurize-0.13.41-ALPHA】
【BowInfinityFix-1.15.2-rv8】
【over】

### Expected behavior

【[Miner] does not fail after the server is restarted】

### Actual behaviour

【Everything worked fine after the initial run】
【When I restart the server, it's different】
【Miner's clothes became the default】
【At the same time I went into [Miner]】
【Wondering why the miners stopped working】
【So I right-click the [Miner] menu block.】
【It says】
【This block is missing its respective buildings, please restart or load a backup.】
【I swear I've rebooted it many times, and every time it's like this, I unzipped the backup and overwrote it with the backup.】
【But is invalid】
【It's still a lost state】
【This may seem a little hard to read because of the translation machine I use.】

【No, because of regional issues.】

### Steps to reproduce the issue

1. 
2. 
3. 
4. ... Profit
【1.Build a [Miner]】
【2.Upgrade to levels 2 to 5】
【3.NPC miners dig underground (the title of the wooden plate is about 8~10)】
【4.The NPC begins to build a mine hole all around】
【5.Restart the server after a while】
【Over】

### Logs

- latest.log: 
【https://github.com/binglingyao/ModError/blob/master/latest.log】
- crashlog: 
【Server does not crash】
【So there is no】

**Comment by Raycoms** [comment]
Can you send me your colony.dat files?

**Comment by binglingyao** [comment]
For some reason, I couldn't upload Colon.dat to Github, nor could I upload the Zip and 7Z Zip packs.
And then I used the cloud disk that I used in my country.

Link：https://pan.baidu.com/s/1W1IqwA4hPdC1CdOSHSKwhQ 
code：q0nh

There are Zip packages,7Z packages, scattered files.
My colony ID Code should be 1
Files are extracted from the [Server \ World \minecolonies] folder
Hope to be helpful to the analysis

**Comment by Raycoms** [comment]
That website isn't letting me download it (I don't speak the language either). Do you have like a google drive link or so?

**Comment by binglingyao** [comment]
I asked my friend to upload Google Drive, but I'm not sure if the link he gave me was a download link because I couldn't open it.
https://drive.google.com/file/d/1z64qMYbVbRa4M1wVXQBMiwXbZuohZO-T/view?usp=sharing

**Comment by Raycoms** [comment]
ty, that worked

**Comment by Raycoms** [comment]
Can you try the newest version?

**Comment by binglingyao** [comment]
Of course, I have downloaded the latest version!
So I'm going to try to create [New Saves]
I will also load the old save that has a problem
I will report whether the problem has been solved or not.
It may take some time (mainly new saving)

**Comment by binglingyao** [comment]
Now I'm trying to use old save
The problem with [Miner] will not be reactivated with an update to the MOD.
Trying to break the [invalid [Miner] box] rebuild [Miner] in [old save].(it is known that rebuilding [Miner] on the original address will start at Level1.)
[Miner] established at the same address will not be mined four weeks from [Y:11 to 30], and will prompt you to upgrade [Miner] even if it has been built to Level5.
What is certain, however, is that my old save [Miner] is no longer invalid after I restart the server.(This one is reconstructed)

**Comment by binglingyao** [comment]
Hey, man!The problem with [Miner] that failed when the server was restarted appears to have been fixed in the new version.
But there's a new problem.
Defunct buildings will not be reactivated by this restoration.
And when I rebuild it on the same site.
He won't be lost restarting the server, but...
It will prompt you," The building needs to be upgraded before I can dig deeper," and even though [Miner] was Level 5, it will prompt you.
It's important to note that my new save hasn't found this problem yet.
The only thing that presents this problem is the old archive

**Comment by Raycoms** [comment]
Yes, unfortunately defunct miners can't be retrieved easily. What you can do is get an NBT editor. and copy the old miner data to the newest colony.dat and then loadbackup on the colony (check wiki for instructions of command)
