### ISSUE TITLE
Can't recruit more citizens

### ISSUE THREAD

**Issue by Sheepchick** [ldtteam/minecolonies#5537]
# Prerequisites

- [ Yes] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [Yes ] I checked the MineColonies [Wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [ Yes] I made sure that **this issue is not a duplicate of any existing issue.**
- [Yes ] This is an issue and not a feature request. Please create all feature requests [here](https://github.com/ldtteam/minecolonies-features/issues).

### Context

0.13.78-ALPHA 

- Minecraft Version: 1.15.2-1.3
- MineColonies Version: 0.13.78-ALPHA
- Related Mods and Their Versions:

### Expected behavior

That the UI pops up and that more citizens will appear

### Actual behaviour

I can't click on certain buttons when in the Townhall UI, such as Toggle specialization and Recruit citizens and it won't get more citizens beyond the standard 4 even when some die or get born, i do have enough housing etc, so that is not the issue. 

### Steps to reproduce the issue

No idea.. 

1. 
2. 
3. 
4. ... Profit

### Logs

- latest.log: 
- crashlog:

**Comment by ravenbuilder934** [comment]
Recruiting has been moved to the tavern. Check the wiki for more information: https://wiki.minecolonies.ldtteam.com/source/buildings/tavern

Toggle specialization currently has no function.

**Comment by Sheepchick** [comment]
I see, thanks! is there a reason for why more children arent being born then beyond the 4?

**Comment by Raycoms** [comment]
do you have a male and female living in one house together?

**Comment by Sheepchick** [comment]
Ah i see! thanks alot! its a newer version from what i played earlier, so got confused by it, thanks alot guys!
