### ISSUE TITLE
Warehouse sorts items into hut block

### ISSUE THREAD

**Issue by PowerSchill** [ldtteam/minecolonies#5543]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.106-BETA
- Structurize Version: 0.13.42-ALPHA
- Related Mods and their Versions:

## Expected behavior

When you sort the warehouse using the sort button it should not place items in the hut box. 

## Actual behavior

When you sort the warehouse using the sort button it will place items in the hut inventory. This inventory is not available to the deliveryman so you could sort the warehouse and make items not available. 

## Steps to reproduce the issue

1. Fill the warehouse
2. Click the sort button in the warehouse
3. Check the hut's inventory.

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Mekle001** [comment]
Is items in the hut block still unavailable to the delivery people in the current alpha builds? I seem to remember @Raycoms fixing that in the last day or so.

**Comment by Raycoms** [comment]
Yeah, that should be fixed
