### ISSUE TITLE
Unable to insert spaces in warehouse search field

### ISSUE THREAD

**Issue by PowerSchill** [ldtteam/minecolonies#5544]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.106-BETA
- Structurize Version: 0.13.42-ALPHA
- Related Mods and their Versions:

## Expected behavior

The warehouse search field should act like the postbox search field and allow space when searching. You enter "clay spruce" and it brings up clay spruce shingles.

## Actual behavior

When you type a space into the warehouse search field like "clay spruce" it won't bring up any items. 

## Steps to reproduce the issue

1. Open the warehouse search and type "clay spruce"

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by robotunicr0n** [comment]
I was not able to repro this issue on the stated versions. I built a warehouse and added lots of Spruce items.. when I search with spaces, the results appear appropriately. Note: I'm using the Minecolonies modpack. Tried both survival and creative and it worked on both.

**Comment by Raycoms** [comment]
I think they mean the menu that opens when you click "add" on the last page.

**Comment by robotunicr0n** [comment]
Ah yes I was wrong, I was using the wrong search bar. 

Issue has been reproduced now, looking into a fix

**Comment by robotunicr0n** [comment]
Confirmed same issue with the Restaurant. Possibly affects Structurize too but unsure
