### ISSUE TITLE
AI issue with farmer and builder

### ISSUE THREAD

**Issue by TheOncelor** [ldtteam/minecolonies#5546]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 
(Valhalsia Modpack on Twitch)
- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.78-ALPHA
- Structurize Version: 0.13.31-RELEASE

## Problem description
The builder has blocks in his request menu, but they aren't being filled by the warehouse and if I go to manually fill the requests there is no fill option but I can still place the blocks in his inventory.

The farmer reported an issue with his AI, but it never seemed to actually break anything, and it hasn't re-reported any problems in the last few hours.

[latest.log](https://github.com/ldtteam/minecolonies/files/5054004/latest.log)

### Notes or related things
I realize this isn't the newest version of the mod, but since i'm playing through a public pack I don't really have any control over it.

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
You should be able to update mods individually within a pack. Not sure how to do it on Twitch but it's really easy on GDLauncher.

**Comment by TheOncelor** [comment]
I mean im aware of that, but if the modpack author pushes a patch that doesnt include the new version of minecolonies it will revert.

**Comment by Raycoms** [comment]
Fixed in newest
