### ISSUE TITLE
Colony became unassigned, colonists disappeared

### ISSUE THREAD

**Issue by crystallinegirl** [ldtteam/minecolonies#5547]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.1 (modded) forge-32.0.106
- MineColonies Version: 0.13.118-ALPHA-universal.jar
- Structurize Version: 0.13.43-ALPHA.jar
- Related Mods and their Versions: Personal kitchen sink modpack, but don't think anything is conflicting. No optifine.

## Expected behavior

Log in, have colonists, be able to interact with colony

## Actual behavior

Updated to newest alpha versions after having a server-crashing memory leak (on a personal server, put pack together less than a week ago), logged in, colonists are gone, when I click on my Town Hall block I get "Colony with ID 1 is nearby. You do not currently own a colony." and below that "There is an existing colony too close." Clicking on any other building's block gets me "This block is missing its respective building" in chat, and can't access the building's gui. 

I only have a few buildings - Builder 2, Citizen 2, Citizen 1, Lumberjack 1, Cook 1, Town Hall 1, and the start of a Miner hut. 

I DID skip yesterday's (8/9) update and went straight to today's. (8/10/2020)

I can still break blocks within the colony boundaries. 

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
The crash potentially rolled back past data or similar. What you can try is /mc colony loadbackup for your colony id and see if that fixes it. However, world corrupting crashes corrupting the capability data where our colonies are stored are difficult if not impossible to solve for us unfortunately.
