### ISSUE TITLE
Deliveryman has issue were it says to report logs to owner.

### ISSUE THREAD

**Issue by kilodom22** [ldtteam/minecolonies#5549]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.124-ALPHA-universal
- Structurize Version:0.13.42-ALPHA
- Related Mods and their Versions:

## Expected behavior

I would have to deliveryman working properly

## Actual behavior

The Dileveryman will not move and say there is a log issue.

![error](https://user-images.githubusercontent.com/69507453/89880938-b0aee880-db79-11ea-9272-c27e2b49401f.PNG)

## Steps to reproduce the issue

Just having these files cause the error. I do not know how it happened 

1. 
2. 
3. 

### Logs

- latest.log: 
[latest.log](https://github.com/ldtteam/minecolonies/files/5056029/latest.log)

- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Fixed in newest

**Comment by kilodom22** [comment]
When will the new files be available?
