### ISSUE TITLE
Update Version 1.14.4-1.15.2

### ISSUE THREAD

**Issue by SlavikSnek** [ldtteam/minecolonies#5553]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.14.4
- MineColonies Version: 1.10.715-release
- Structurize Version: 0.10.245-alpha

## Problem description
Sorry, I know this isnt a problem but i wasn't sure where else to look i was wondering if there was a way to update the version as well as keeping all of your colonies saved ( I am running it on a server)

### Notes or related things

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
No, you can't switch worlds between Minecraft versions.

**Comment by Nightenom** [comment]
@ravenbuilder934 wrong, you can update modded world as long as the mod has support for it
@SlavikSnek I'm not aware of any game-breaking changes between 1.14 and 1.15, but don't expect it to work flawlessly or get any support for it

**Comment by SlavikSnek** [comment]
> @ravenbuilder934 wrong, you can update modded world as long as the mod has support for it
> @SlavikSnek I'm not aware of any game-breaking changes between 1.14 and 1.15, but don't expect it to work flawlessly or get any support for it

Okay thanks alot. I'll use a test world first. 👍
