### ISSUE TITLE
AI builder reports an issue and says to include log

### ISSUE THREAD

**Issue by shakaama** [ldtteam/minecolonies#5554]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.15.2
- MineColonies Version: 1.15.2 latest
- Structurize Version: 1.15.2 latest
- Related Mods and their Versions: 1.15.2 latest (i'm new at all this, spoke to you all on youtube to get it to work, been playing for a week)

## Expected behavior

no issues (whatever is going on is invisible to me)
## Actual behavior

red cog appears over builder head (just the main builder) and message appears in conversation

## Steps to reproduce the issue

no idea, the message just constantly appears to check latest.log
1.  build
2.  queue more builds
3.  get ai error message

### Logs

https://gist.github.com/shakaama/9a955410245a2461cc27eea2613ba336
- latest.log: 
https://gist.github.com/shakaama/9a955410245a2461cc27eea2613ba336
- crashlog: 
there is no crash log, game doesn't crash.

### Notes

The only thing I can think of is, as the main builder he is given a lot more builds, than other builders, since he upgraded first.
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Fixed in newest
