### ISSUE TITLE
Builder refusing to build, what a stubborn problem.

### ISSUE THREAD

**Issue by JevilFromVSauce** [ldtteam/minecolonies#5555]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: minecolonies-0.13.120-ALPHA-universal.jar
- Structurize Version: structurize-0.13.42-ALPHA.jar
- Related Mods and their Versions: N/A

## Expected behavior
1. The builder says he "Starts building (something)(In this case, builder 5)"
2. The builder actually places blocks and completes the build.

## Actual behavior
1. The builder says he "Starts building (something)(In this case, builder 5)"
2. The builder sometimes completes part of the build but ends up just walking around doing absolutely nothing
## Steps to reproduce the issue

1. Upgrade a builders hut and he will just stop.
### Logs

- latest.log: https://gist.github.com/JevilFromVSauce/ec6b79d15f39511702079f789216001f

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Fixed in newest

**Comment by JevilFromVSauce** [comment]
> Fixed in newest

Im using the newest and it isnt working, unless the newest isnt released or something.

**Comment by Raycoms** [comment]
Because above it says 120 instead of 124 alpha, are you on that one?

**Comment by Raycoms** [comment]
The last stage of each building can take a while, there are several scan processes running. So it might take a few minutes for it to finish. Maybe above an ingame day as well

**Comment by JevilFromVSauce** [comment]
120 is the highest available on twitch rn IG
![image](https://user-images.githubusercontent.com/69450308/89956166-9f5dee80-dc02-11ea-9241-29a25575de05.png)

**Comment by Talyda** [comment]
https://www.curseforge.com/minecraft/mc-mods/minecolonies/files/all?filter-game-version=1738749986%3A68722
Download and update manually

**Comment by JevilFromVSauce** [comment]
> https://www.curseforge.com/minecraft/mc-mods/minecolonies/files/all?filter-game-version=1738749986%3A68722
> Download and update manually

so I tried but it didnt update.

**Comment by JevilFromVSauce** [comment]
![image](https://user-images.githubusercontent.com/69450308/89957594-cff35780-dc05-11ea-86dc-36ae9980b707.png)
![image](https://user-images.githubusercontent.com/69450308/89957636-ebf6f900-dc05-11ea-8c2b-05d257cf8873.png)

**Comment by Raycoms** [comment]
Gotta wait for twitch to be stable again

**Comment by JevilFromVSauce** [comment]
I have to or you do?

**Comment by ravenbuilder934** [comment]
Everybody does 😛 
Twitch/Curseforge are having problems right now

**Comment by JevilFromVSauce** [comment]
That kinda sucks, is there a temp fix yall know of?

**Comment by JevilFromVSauce** [comment]
I notice its pretty much SPECIFICALLY with builder 5, and somewhat with sawmill 4, both medieval spruce.

**Comment by JevilFromVSauce** [comment]
![image](https://user-images.githubusercontent.com/69450308/89962989-531baa00-dc14-11ea-936d-67b2191998ad.png)

**Comment by JevilFromVSauce** [comment]
NEVERMIND It happens with every building 👍

**Comment by JevilFromVSauce** [comment]
Hey Raycoms, I just updated to 24, and... Its still not working...

**Comment by JevilFromVSauce** [comment]
He just walks around and once every 5th time I fire/rehire and restart him he SOMETIMES builds...
