### ISSUE TITLE
Deliveryman won't pickup from Stash

### ISSUE THREAD

**Issue by PowerSchill** [ldtteam/minecolonies#5557]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.106-BETA
- Structurize Version: 0.13.42-ALPHA
- Related Mods and their Versions:

## Expected behavior

The Deliveryman should always pick up items when they are placed in the stash. When breaking the Stash the contents should drop out as items. 

## Actual behavior

Occasionally the Deliveryman won't pick up any resources from the Stash. Furthermore, when in this state, breaking the Stash will cause all of the contents in the Stash to be voided. 

## Steps to reproduce the issue

At the moment the exact cause of the issue is not known but it happens periodically to a majority of users on the Patreon server. 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Taking all items out of the stash, breaking it, placing it, and putting the items back temporarily fixes it.

**Comment by Raycoms** [comment]
Is there any way to reproduce this?

**Comment by PowerSchill** [comment]
Yeah, just wait long enough. I've had it happen at least 4 times since I started playing today.

**Comment by Raycoms** [comment]
Placed 20 in a single-player world. Waited 4h and nothing

**Comment by PowerSchill** [comment]
So you think its just an issue with the server?

**Comment by Raycoms** [comment]
I tried on a local server too. I can't reproduce it consistently enough to be able to debug it.

**Comment by ravenbuilder934** [comment]
😞 boo. This can get really annoying. I think it might happen when I leave the colony/stop chunkloading it and there's a pickup request at the Stash, but not sure.

**Comment by PowerSchill** [comment]
Is there anything on the Patreon server that would interfere/intercept with the Stash and it's requests?

**Comment by Mekle001** [comment]
Is there any chunkloading possibly going on? I've seen this on my test server a time or two, and my colony there is about half covered by spawn loading.  The warehouse and ~2 of the dmen are probably loaded in my world.

**Comment by Mekle001** [comment]
I should note: many mods have blocks that can cause chunkloading as a side effect. For instance, Refined Storage will load and keep chunks loaded.

**Comment by Raycoms** [comment]
Same problem as the item loss problem. So, duplicate. Will close, fix is imminent.
