### ISSUE TITLE
some bugs

### ISSUE THREAD

**Issue by alskion** [ldtteam/minecolonies#5558]
Hello, I want to report that there is a bug that I do not know where it comes from ... I explain, I started to build my neighborhood, but when I build the warehouse, and the delivery house, the delivery is hired and it goes directly to the warehouse and does not move , he stays there, he doesn't work. Another error that appears is that the lumberjack at that time marks me an AI error and tells me to report it. 
[latest.log](https://github.com/ldtteam/minecolonies/files/5059729/latest.log)

**Comment by Raycoms** [comment]
Please fill in the full template. We need more data
