### ISSUE TITLE
Workorders not appearing 1.15.2

### ISSUE THREAD

**Issue by EtherialMind** [ldtteam/minecolonies#5559]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.15.2
- MineColonies Version:0.13.122-ALPHA
- Structurize Version:0.13.42-ALPHA
- Related Mods and their Versions: n/a

## Expected behavior

I would expect a work order to be generated when a building is scheduled to be built.

## Actual behavior
When I schedule a building to be built there is no workorder generated and the builder doesn't react.

![2020-08-12_11 43 27](https://user-images.githubusercontent.com/68166645/90037826-a5031500-dc92-11ea-8f99-21646e855289.png)

![2020-08-12_11 43 29](https://user-images.githubusercontent.com/68166645/90037841-a7656f00-dc92-11ea-9b05-88d8c9db0cf4.png)

![2020-08-12_11 43 44](https://user-images.githubusercontent.com/68166645/90037859-ac2a2300-dc92-11ea-9906-40ac3b040cc2.png)
## Steps to reproduce the issue
As far as I can tell the bug is produced whenever I schedule a building to be built.

### Logs
As this doesn't cause a crash I don't have a crashlog and also don't know where to find the latest.log.

### Notes
I found this bug in a highly modded instance so a conflict could be the cause. also I have disabled land protection and barbarians through the config in said instance.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Does this workorder appear after 5 minutes or so?

**Comment by EtherialMind** [comment]
I'll have to check.

**Comment by EtherialMind** [comment]
It didn't the first time I encountered this bug.

**Comment by EtherialMind** [comment]
It seems to have appeared this time around. after logging back in it was there.

**Comment by Raycoms** [comment]
Since you said it was heavily modded, is there anything that could delay network messages etc and could delay the client side updates?

**Comment by EtherialMind** [comment]
I don't know
any idea of what type of mods could cause that.
It would help me narrow it down as I am still new to bugfixing.

**Comment by Raycoms** [comment]
No idea, it's weird since it works fine for us on our servers

**Comment by Raycoms** [comment]
Should be a bit better in newest, the pickup speed. In general, it might always need a minute or so until the system reacts. We do this to avoid overloading servers with performance Minecraft is bad already
