### ISSUE TITLE
Wrong rotation of Dark Oak Barrack towers

### ISSUE THREAD

**Issue by Wetz1990** [ldtteam/minecolonies#5560]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.106-Beta-universal.jar
- Structurize Version: 0.13.42-ALPHA.jar
- Related Mods and their Versions:

## Expected behavior

That the towers would allign with the barrack itselv

## Actual behavior

The barrack towers seems to be rotated 90 degrees to much CW

![image](https://user-images.githubusercontent.com/33292786/90044106-7191ac00-dccd-11ea-828b-ffc85d9b82b2.png)

## Steps to reproduce the issue

1. Place dark oak barrack
2. build it
3. See towers are rotated wrong

### Logs

- latest.log: 
- crashlog: 

### Notes
may be related to mirroring the barrack. Im currently trying to test this on the server.
All schematics have been checked by Lunar, and they do not have the issue.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Schematic issue bug. Please add to joint schematic issue.

**Comment by ravenbuilder934** [comment]
Not a schematic issue, the schematics have been checked multiple times and are fine.

**Comment by Raycoms** [comment]
Then it must be the same problem for all barracks. It can't be only related to the dark oak.
