### ISSUE TITLE
Server Config not fully working

### ISSUE THREAD

**Issue by Vexikuri** [ldtteam/minecolonies#5561]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 13.81-Release
- Structurize Version:13.31-Release
- Related Mods and their Versions:

## Expected behavior

**In the server  config and tried client side.  I have voices set to false and mobs don't attack citizens, yet I'm hearing voices and citizens are dying to mobs.

https://gist.github.com/Vexikuri/d16c43419098d462f84edf998aee6a13

**

## Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Nightenom** [comment]
Will get fixed with first 1.16.2 alpha since it's breaking change

**Comment by Vexikuri** [comment]
LOL Thanks.
We just started this server yesterday on 1.15.2 lol

**Comment by someaddons** [comment]
the mob attack config does work, if there is still some attacks its some other mod not respecting neutral entities/npcs

**Comment by Vexikuri** [comment]
I can understand that, but what about the citizen voices not being turned off?

**Comment by Raycoms** [comment]
Sounds are sent serverside

**Comment by Vexikuri** [comment]
I re-made the server with less other mods which I believe one of which were conflicting with MC.  Same version of MC, Forge etc and I dont hear voices.  So I believe it was conflict issue.

**Comment by Vexikuri** [comment]
Nope, spoke to soon.  Voices are back.

**Comment by TheNuclei** [comment]
I'm having this issue as well.

mobattackcitizens = false, they still die to barbarians
shouldraiderbreakdoors = false, they break doors regularly

I am also running the latest alpha via valhelsia2

**Comment by Raycoms** [comment]
adjusted in 1.16
