### ISSUE TITLE
Builder does not complete builds.

### ISSUE THREAD

**Issue by MercuryCandies** [ldtteam/minecolonies#5562]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.125-ALPHA-universal
- Structurize Version: 0.13.42-ALPHA
- Related Mods and their Versions:

## Expected behavior

Builder completes his or her work and the announcement pops up that the build was finished.
## Actual behavior

The builder will walk to the job site and swing their arm with an empty hand. This will continue until nightfall when the builder goes back home for the night. This repeats the following day. The worker has no open requests. The job on the site being built is listed as being at 100% completion. Recalling the worker does nothing and neither does firing and hiring another one. 

## Steps to reproduce the issue
1. Assign them a build order.
2. Wait for the builder to finishing placing the final piece of the build.
3. Run into the bug.

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MercuryCandies** [comment]
I found this line in my latest log. 

WorkOrderBuild at location BlockPos{x=-2447, y=64, z=-813} is using schematics/stone/farmer1 instead of schematics/stone/farmer1

**Comment by Raycoms** [comment]
The builder has a last step that is not included in the 100% cost. THis is clearing blocks that were from previous upgrades. depending on the size of the building this can take 2-3 ingame days. Please confirm if the builder will finish

**Comment by MercuryCandies** [comment]
I left the game on and let him continue with the same build for at least 10 in game days.

**Comment by Raycoms** [comment]
If you log off and leave the game on, there will not be a lot of progress at all.

**Comment by MercuryCandies** [comment]
What I mean to say is I just went afk with the game running and kinda just watched him for a while.

**Comment by Raycoms** [comment]
ah okay. Which building was it?

**Comment by MercuryCandies** [comment]
The first stone farm. On another world it was the first tier asian builder's hut.

**Comment by ravenbuilder934** [comment]
The builder might be scanning the build to make sure it's done. This can take a *while* if it's a big build.

**Comment by MercuryCandies** [comment]
It was the first tier stone farm, it had like 5 different materials. I'm pretty sure it might be one of the smallest builds in the mod.

**Comment by EtherialMind** [comment]
I have a similar if not related issue where the builder will accept a work order but will not request any resources 
![2020-08-13_17 44 22](https://user-images.githubusercontent.com/68166645/90190463-0c04f480-dd8d-11ea-9db3-4a00ac28f3e1.png)
![2020-08-13_17 44 08](https://user-images.githubusercontent.com/68166645/90190470-0effe500-dd8d-11ea-8ad9-c6d83bbfdeb7.png)
I tried resetting the request system but it didn't help.

**Comment by Raycoms** [comment]
the builder will only accept it once he enter the task and only then the builder will calculate the list. SO when the builder is hungry, sick, sleeping, doing something else they won't calculate the requirements

**Comment by EtherialMind** [comment]
the problem is that the builder isn't calculating the requirements even though they are not hungry, sick, sleeping, or doing something else.

**Comment by JevilFromVSauce** [comment]
I have a very similar problem, the builder for me just sits outside his hut which im trying to upgrade and doesnt do a thing.

**Comment by JevilFromVSauce** [comment]
Its been stuck for several days now, no matter if I update it or anything, and on other builds I have to fire/rehire several times for him to even make progress.

**Comment by nickmuenster** [comment]
is this fixed? i habe the same problem on the lates build (townhall)

**Comment by MotionlessTrain** [comment]
In the final steps of building a building (usually when placing torches and similar items), the builder will seem to stand still and not work. However, they are most likely performing calculations/checks to ensure that every block is placed correctly. This may take a while, especially the larger buildings, so be patient. Firing and re-hiring a builder risks forcing the builder to start all of these calculations over again.

This is not a bug, by the way, and certainly not related to an issue from two years ago. (And I nstead of resurrecting issues from so long ago, please open new issues)

**Comment by nickmuenster** [comment]
sry i didnt want to be rude :/ i just wait longer :) thanks for the quick respond. I love your Mod
