### ISSUE TITLE
Scarecrow Crash

### ISSUE THREAD

**Issue by WenXin20** [ldtteam/minecolonies#5563]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft: v1.15.2
- MineColonies: v0.13.124-Alpha
- Structurize: v0.13.42-Alpha

## Expected behavior
- No crashes

## Actual behavior
- Sometimes while on my server, the scarecrow will crash my game client-side while loading the chunk with the scarecrow.
- I only have one farmer with one scarecrow nearby

## Steps to reproduce the issue

1. Place Medieval Farmer hut with scarecrow
2. Crash

### Logs

- latest.log: https://gist.github.com/WenXin20/4d8dfe0b456346cfc2404fda17c81f47
- crashlog: https://gist.github.com/WenXin20/bb073946f1a511fd665cc58ecb677c82
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Nightenom** [comment]
Instance of MinecraftForge/MinecraftForge#6719
