### ISSUE TITLE
The Guard tower in Japanese barracks is not located correctly.

### ISSUE THREAD

**Issue by binglingyao** [ldtteam/minecolonies#5565]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
【Minecraft Version: 1.15.2】
- MineColonies Version:
【MineColonies Version: 0.13.125-ALPHA-universal】
- Structurize Version:
【Structurize Versison:  0.13.42-ALPHA】

## Problem description

【Open the link below】
【https://github.com/binglingyao/ModError】
【See 1~3.png】
【You will notice that the Guard tower in The Japanese barracks is not in the right position.】
【And this part cannot be corrected manually because it will prompt [please upgrade barracks]】
### Notes or related things

【Please fix it.】
---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Please report it on the discord as schematic bugs
