### ISSUE TITLE
Game Crashes when talking with Builder NPC

### ISSUE THREAD

**Issue by Dreadnouhgt** [ldtteam/minecolonies#5566]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16
- MineColonies Version: 0.13.123 alpha
- Structurize Version: 1.2.1
- Related Mods and their Versions:

## Expected behavior
Open the NPC Gui and see why she had a red gear on the Head

## Actual behavior
When i rightlick on the NPC my game Crashes

## Steps to reproduce the issue

Rightclick the NPC to talk with her.

### Logs

https://gist.github.com/Dreadnouhgt/dc0ab2c2a4ed46956261f49e9b9c8f17
### Notes

Server restart did not help. 

http://prntscr.com/tz234b Second Builder also start with the weirdness now.... moves around the house, gos in the house, gos up and down, moves outside and not finishing the build. 
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
For sure not the pastebin you wanted to send us?

**Comment by Dreadnouhgt** [comment]
I dont know what this is but this not what i uploaded.

**Comment by Dreadnouhgt** [comment]
Deliverymans now also start to act strange

**Comment by Dreadnouhgt** [comment]
https://gist.github.com/Dreadnouhgt/236b51756ea9810e6dfb9791e8dcb014

**Comment by Dreadnouhgt** [comment]
http://prntscr.com/tz4jjf So the Gui looks like this and then it crashes, she says she is missing some items in her inventory and i should fix that, after clicking on the i will take care of that the game crashes
