### ISSUE TITLE
I cant Right Click on the civilians (Any of them)

### ISSUE THREAD

**Issue by zhombiehjam** [ldtteam/minecolonies#5567]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: Forge - MC 1.16.1 - 32.0.108
- MineColonies Version: 0.13.127-ALPHA - universal
- Structurize Version: 0.13.44 - ALPHA
- Related Mods and their Versions: 

I have my own minecraft server with the same mods but it doesn't work, in version 1.15.2 it worked.

## Expected behavior

I want to see the menu of the colonists, but when I right click on them, they only speak and do not open the menu.

## Actual behavior

By right clicking on any civilian, it only speaks and does not display a menu.

## Steps to reproduce the issue

Right click an any civilian

1.  Right Click on the Civilian
2.  only speak
3. 

### Logs

Dont show nothing.

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Remove optifine, it's their fault
