### ISSUE TITLE
[Feature Request] Player Item Exchange at Spawn

### ISSUE THREAD

**Issue by kedamono** [ldtteam/minecolonies#557]
### Minecolonies version

Current Minecolonies Testserver version

### Expected behavior

- Two players meet at the Spawn and trade items with each other.

### Actual behaviour

- Because of Spawn restrictions, players cannot pick up items or trade with other players.

### Suggested methods

One version I've seen is to have a room where each player visible deposits the item in question so that the other person can see it and verify it's what they asked for. Then a button is pushed and the item is swapped to the other player with the proper permissions allowing them to pick it up.

Another method is an "open" chest where items are deposited and they can be taken by other players.

**Comment by marvin-bitterlich** [comment]
The correct way to solve this would be a setting in the townhall to choose if the anti item spam should be enabled or disabled for this colony.

**Comment by kedamono** [comment]
The request is for the World Spawn at the center of the Minecolonies Testserver. I can always set someone to "friend" in my townhall.

**Comment by Raycoms** [comment]
Exactly that's why that command he mentioned would resolve it.

2017-02-07 13:14 GMT-02:00 kedamono <notifications@github.com>:

**Comment by marvin-bitterlich** [comment]
Closing as server related
