### ISSUE TITLE
Deliveryman Just stands and says error and check logs

### ISSUE THREAD

**Issue by kilodom22** [ldtteam/minecolonies#5573]
### Prerequisites 

- [ x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- MineColonies Version: 0.13.125-ALPHA_universal
- Structurize Version:0.13.42-ALPHA
- Related Mods and their Versions:

## Expected behavior

The Deliveryman would collect resources to warehouse

## Actual behavior

The Deliveryman just stands Idle.

![2020-08-10_22 49 38](https://user-images.githubusercontent.com/69507453/90212273-c86bb400-dda7-11ea-8273-77b3a937b4c6.png)

## Steps to reproduce the issue

1. 
2. 
3. 
Just loading up the game does this.

### Logs

- latest.log: 
- crashlog: 
[latest.log](https://github.com/ldtteam/minecolonies/files/5072589/latest.log)

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
duplicate
