### ISSUE TITLE
chunkcapdata client crash

### ISSUE THREAD

**Issue by kreezxil** [ldtteam/minecolonies#5576]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.115-alpha **I see there a quite few new ones, i will try them next**
- Structurize Version: 0.13.42-alpha
- Related Mods and their Versions: **this is vague not sure what you mean, do you mean the other mods in the pack and their versions?** __It's Vague__ because there is no mod related to Minecolonies on 1.15.2 such as MCA for instance.

Mods in **The Seilican Experience**
 name | version 
 ------- | --------
 bambooeverything | 1.15-1.0.0 
 BiomesOPlenty | 1.15.2-10.0.0.366-universal 
 BonsaiTrees | 2.1.2.6 
 CHAS | v1.3 for 1.15 
 Controlling | 6.1.5.6 
 CraftTweaker | 1.15.2-6.0.0.38 
 create | mc1.15.2_v0.2.4d 
 Cucumber | 1.15.2-3.0.9 
 curios | FORGE-1.15.2-2.0.2.6 
 damage_indicator | 0.1.0 
 DungeonCrawl | 1.15.2-2.0.2 
 elevatorid | 1.15.2-1.7.1 
 exp_bottling | 1.15.2-1 
 f2l | 0.3.1 
 FallingTree | 1.15.2-2.2.1 
 fancymenu | 1.4.4_MC_1.15-1.15.2 
 FastLeafDecay | v22 
 FeaturedServers | 1.15.2-1.2.1 
 gravestone | 1.17.5 
 inventorysorter | 1.15.2-17.0.0 
 jei | 1.15.2-6.0.2.12 
 JEITweaker | 1.15.2-1.0.1.3 
 journeymap | 1.15.2-5.7.0b3 
 Kiwi | 1.15.2-2.8.2 
 libnonymous | 1.15.2-1.1.1.5 
 Lollipop | 1.15.2-1.0.16 
 Ma-Essentials | 1.15.2-3.1.1 
 massunbind | 1.0 
 minecolonies | 0.13.115-ALPHA-universal 
 mining-helmet | 1.15.2-1.0.8 
 MixinBootstrap | 1.0.3 
 morecharcoal | 1.15.2-1 
 moredragoneggs | 1.0 
 Morpheus | 1.15.2-4.2.50 
 MouseTweaks | 2.13-mc1.15.1 
 MysticalAgriculture | 1.15.2-3.0.10 
 nethercraft | 1.15.2-1.0.9 
 noautojump | 1.15.2-1 
 noRecipeBook | v1.5.4formc1.15.2 
 Placebo | 1.15.2-3.1.0 
 polymorph-FORGE | 1.15.2-0.10 
 Powah | 1.15.2-1.1.15 
 quartz-chests | 1.1.0.5 
 ReAuth | 1.14-1.15-3.8.1 
 refinedstorage | 1.8.8 
 refinedstorageaddons | 0.6.3 
 respawnablepets | 1.1.4 
 ScalableCatsForce | 2.13.2-build-2-with-library 
 simplybackpacks | 1.15.2-1.4.8 
 SnowRealMagic | 1.15.2-1.8.0 
 SoulShardsRespawn | forge-1.15.2-1.2.0-15 
 structurize | 0.13.42-ALPHA 
 terrible_chest | 1.15.2-2 
 theoneprobe | 1.15-2.0.4 
 ToastControl | 1.15.2-3.0.1 
 tramplestopper | 1.15.2-2.0.0.1-universal 
 VanillaTweaks | 1.15.2.1.5.30 
 walljump-forge | 1.15.2-1.3.5 
 WaterStrainer | 1.15.2-9.0.0 
 WitherSkeletonTweaks | 1.15.1-4.0.0 
 XL-Food-Mod | 1.15.2-2.2.2 

## Expected behavior

no crash and my players connecting to the server and having fun

## Actual behavior

I don't know, I will have my player who witnessed it come here and tell you more about it.

## Steps to reproduce the issue

When Seilican gets here, he will post steps.

1. 
2. 
3. 

### Logs

- crashlog: https://gist.github.com/kreezxil/5ebf18365e39bb27e3706e706cac0d31

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
That's one of the forge bug crashes. Could affect any class randomly.

**Comment by kreezxil** [comment]
ok, thanks.
