### ISSUE TITLE
Colony bug

### ISSUE THREAD

**Issue by Pocire** [ldtteam/minecolonies#558]
0.6.2038 Minecolonies version

version 0.6.2038 or curse X.X.XX

### Expected behavior

- Colony  depop after a crash (power cutt)
  When i try to use "/mc colony respawn" it says No citizen -1 found in colony -1
  When i try "/mc colony info" it says ID:0 Name:  Mayor: username Citizen 0/4 Coordinates: X Y Z
  
### Actual behaviour

- Now i have replace another townhall but citizens spawn and instant dispawn, please help :(

### Steps to reproduce the problem

1. no step to reproduce i think..
2. 
3. ...
4. Using minecraft 1.10.2, curse modpack "FTT3" (108 mods), no texture pack

**Comment by marvin-bitterlich** [comment]
What do you mean with depop? You have to give us crash logs and forge logs. And your command is missing citizenid and colonyid

**Comment by Pocire** [comment]
Citizens try to spawn but instant despawn on this place (tried to screen them) 
![2017-02-08_11 13 12](https://cloud.githubusercontent.com/assets/25608815/22732834/f0d6748a-edef-11e6-99f9-a5a94b2a5816.png)

i want to mean with "depop", there is a power cut, the computer shut down and when i reload modpack, and my game, there is no citizen in my town, so i try this command
/mc colony respawn

![2017-02-08_11 15 23](https://cloud.githubusercontent.com/assets/25608815/22732835/f0d68c68-edef-11e6-9fd8-391158ce8273.png)

**Comment by Raycoms** [comment]
Can you tell us the mods you installed?

2017-02-08 8:23 GMT-02:00 Pocire <notifications@github.com>:

**Comment by Pocire** [comment]
AppleCore, AppleSkin, Aquaculture, ArchitectureCraft, AutoSapling, Autopackager, Autoreglib, bagelsmore: The Return, Baubles, BdLib, Better Agriculture, Better Achievements, Biomes O'Plenty, Block Drops (JEI addon), Blood Magic, Bookshelf, Botania, Chameleon, Chest transporter, Chiken Chunks 1.8+, Chisel, Chunk Animator, Class armor: Beast master, berserker, mage, archer, necromancer, paladin   Code chicken Core, Codechicken lib
Coral reef, decocraft2, druidry, enchanting plus,, Ender IO, FastleafDecay, Fence overhaul, Forestry, Grappling hook mod, gravestone mod, guide API, Hatchery, HoloInventory, Immersive Engineering, Inventory tweaks, Inron chests, JEI bees, JourneyMap, JurassiCraft 2.0, Just Enough Items, Just Enough Ressources, KleeSlabs, Levels, Light lever overlay reloaded, Linelib, Litteral Ascension, LLibrary, Magneticraft, MalisisCore, MalisisDoors, Mantle, MCMultipart, Minecolonies, More bees, Morpheus, Multistorage, Neat, Netherportalfix, Pam's Harvestcraft, Photopics, Ping, Quark, Railcraft, Realistic terrain generation, redstone Paste, Rockhounding: Chemestry and Ore tiers, Roguelike Dungeons, Roots, ShadowFacts Forgelin, ShadowMC, ShetiphianCore, Skyressources, Slashblade, SoldiXp, Sound Filters, Spartant, shields, Stellar API, Stellar Sky, Stimmedcow: Nomorerecripeconflict, Storagedrawers, StorageNetwork, Sublib, Therpginventory and classarmor mod,The spice of life, Tinkers construct, Tinkers toll leveling, veinminer, waila, waila harvestability, water strainer, Wawla, waystones, woot
all the 108 mods :)

**Comment by Raycoms** [comment]
Please reopen if able to reproduce.

**Comment by CronoxXL** [comment]
my bug is that when I want to improve my town hall I get a bug and the fences are increased I remove them and then I ask for fences again and the town hall never improves I need help please
the minecraft version is 1.11.2 forge
![2017-12-31_20 52 18](https://user-images.githubusercontent.com/34991691/34464757-8d63e49e-ee6d-11e7-8a14-657f8bc4a750.png)

![2017-12-31_20 52 06](https://user-images.githubusercontent.com/34991691/34464756-8ba6e1f6-ee6d-11e7-80ab-7c81d1769434.png)

![2017-12-31_20 52 02](https://user-images.githubusercontent.com/34991691/34464755-89b4a55e-ee6d-11e7-9ae7-673891e91fdb.png)

![2017-12-31_20 52 00](https://user-images.githubusercontent.com/34991691/34464754-868aa068-ee6d-11e7-8166-df11efc03ff7.png)

![2017-12-31_20 51 59](https://user-images.githubusercontent.com/34991691/34464753-84acfb2e-ee6d-11e7-8442-c23a3dc1dfc4.png)

![2017-12-31_20 51 57](https://user-images.githubusercontent.com/34991691/34464752-832e2b56-ee6d-11e7-9aeb-959396184888.png)

![2017-12-31_20 51 56](https://user-images.githubusercontent.com/34991691/34464751-80b97a9c-ee6d-11e7-90bc-0178ca237429.png)

![2017-12-31_20 51 54](https://user-images.githubusercontent.com/34991691/34464750-7e7c34b8-ee6d-11e7-8bb0-1418174d5932.png)

**Comment by Raycoms** [comment]
Which Download and from which to which level?

**Comment by Raycoms** [comment]
Which style?
