### ISSUE TITLE
Warehouse not fulfilling requests

### ISSUE THREAD

**Issue by kd5crs** [ldtteam/minecolonies#5580]
### Prerequisites 

- [X ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: minecolonies-0.13.133-ALPHA-universal
- Structurize Version: structurize-0.13.37-ALPHA
- Related Mods and their Versions: 

## Expected behavior
DMan gets items in Warehouse when requested.

## Actual behavior

The DMan picks up and puts stuff in the Warehouse like normal, but fulfills no requests from the Warehouse. This is new since version 13.125 where this worked as expected.

## Steps to reproduce the issue

1. Build a Warehouse and Dman.
2. Have the Builder request something that is stored in the Warehouse. (tested using Fortress)
3. The Clipboard says Fulfilled by Player.
4. The Builder's request screen says Fulfilled from Warehouse.
5. DMan does not deliver from Warehouse, but does pick up from Lumberjack and Miner.

### Logs

- latest.log: https://gist.github.com/kd5crs/fd358c55b33264a4bfdbe01fdc99cd72
- crashlog: No crash

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Can you try the newest one we just released?

**Comment by Raycoms** [comment]
That should fix it.

**Comment by kd5crs** [comment]
Yes 13.136 fixed it. Thanks!

**Comment by kd5crs** [comment]
@Raycoms Ok, it seems very strange, but it seems like everything is being fulfilled except Dark Oak Fences? Whenever the build gets down to needing Dark Oak Fences, the behavior comes back. The Builder says it is being fulfilled from the warehouse, there are fences in the warehouse, but the DMan never delivers them. I haven't had any other fence type come up on Fortress style yet. That's the only thing I've seen not being delivered in 13.136.

**Comment by Raycoms** [comment]
Are those in a different kind of storage block?
