### ISSUE TITLE
Miner lost his hutblock

### ISSUE THREAD

**Issue by PiTTl** [ldtteam/minecolonies#5582]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.95-ALPHA
- Structurize Version: 0.13.39-ALPHA

## Problem description

a players miner suddenly lost his hut block. Only a short Message appears in the server log: "Citizen Noah V. Hambard has lost its building, type does not match found BuildingMiner expected BuildingMiner."  The Block is no longer clickable. Affected building is Asian Style Level 3
### Notes or related things

The Miner has been working for a week since using this version. (we have now updated to latest version).
I'm sorry if this all is wrong or confusing, this is my very first report and I'm not english.
---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
fixed in latest

**Comment by PiTTl** [comment]
THANK you Ray :+1:
