### ISSUE TITLE
Deliveryman error

### ISSUE THREAD

**Issue by kilodom22** [ldtteam/minecolonies#5585]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.15.2
- MineColonies Version:0.13.136-ALPHA-universal
- Structurize Version: 0.13.42-ALPHA
- Related Mods and their Versions:

## Expected behavior

To collect Items and store in the warehouse.

## Actual behavior

Just responds with the AI has experienced an error as soon as I start

## Steps to reproduce the issue

1. 
2. 
3. 
Happens instantly when I start the game

### Logs

- latest.log: 
[debug.log](https://github.com/ldtteam/minecolonies/files/5079095/debug.log)
[latest.log](https://github.com/ldtteam/minecolonies/files/5079096/latest.log)

- crashlog: 

### Notes

![2020-08-15_09 14 19](https://user-images.githubusercontent.com/69507453/90316680-8beba580-ded8-11ea-89e7-f8346a133d83.png)

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Hopefully fixed in latest (message needs manually "that has to do for now" still though)
