### ISSUE TITLE
Colonist NPC Interface Won't Appear On Right-Click

### ISSUE THREAD

**Issue by AmerGoalieBeast123** [ldtteam/minecolonies#5587]
When I try to give building supplies or talk to the colonist then no Colonist Interface wont appear. I spammed it a couple times, but nothing. I only get repeats of the dialog of the colonist. Like "I Get To Build It Again" from the female. The males interface wont appear either and he just repeats "I'll Take Care Of This". Please help me and thank you.

**Comment by AmerGoalieBeast123** [comment]
I'm playing on the 1.16.1 Forge 0.13.138-Alpha version with other mods

**Comment by angeerey** [comment]
Yeah I have the exact same problem on the same version.

**Comment by Raycoms** [comment]
Remove optifine and report to them.

**Comment by AmerGoalieBeast123** [comment]
Optifine means no shader man. I got the seues PTGI hrr one too

**Comment by ravenbuilder934** [comment]
Either shaders or the GUI, your choice

**Comment by Raycoms** [comment]
Then tell optifine to fix this. We can't fix what they broke
