### ISSUE TITLE
Deliveryman not working.

### ISSUE THREAD

**Issue by kilodom22** [ldtteam/minecolonies#5589]
### Prerequisites 

- [ x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.15.2
- MineColonies Version:0.13.136-ALPHA_universal
- Structurize Version:0.13.42-ALPHA
- Related Mods and their Versions:

## Expected behavior

The Deliveryman would collect resources to warehouse
## Actual behavior

The Deliveryman just stands Idle.

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 
[latest.log](https://github.com/ldtteam/minecolonies/files/5080125/latest.log)
[debug.log](https://github.com/ldtteam/minecolonies/files/5080126/debug.log)

![](https://user-images.githubusercontent.com/69507453/90212273-c86bb400-dda7-11ea-8273-77b3a937b4c6.png)

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
you're not running the latest alpha. Please update

**Comment by kilodom22** [comment]
I am running the latest 1.15.2 If i try to use 1.16.1 It crashes my game and wont start.

**Comment by kilodom22** [comment]
I am at the most up to date for 1.15.2. I am playing on version 1.15.2 I can not use 138 since it is on 1.16.1. The issue can not be fixed for 1.16.1 versions since I am on 1.15.2.

**Comment by Raycoms** [comment]
125 is far from the latest 1.15.2 though

**Comment by kilodom22** [comment]
I put it wrong i am using 0.13.136 as the latest I copied an old one

**Comment by Raycoms** [comment]
We added a few more updates. Can you try the latest one?

**Comment by kilodom22** [comment]
Updated and fixed it thank you for the hard work! Now I can play it non stop!:D
