### ISSUE TITLE
Crash with minecolonies

### ISSUE THREAD

**Issue by Glassait** [ldtteam/minecolonies#5591]
Hello i'm using minecolonies-0.13.81-RELEASE-universal in my dedicated serveur forge 31.2.36, and mi friend have this crash. 
I read the crash report and i think it's do to minecolonies, but to don't know have slove this crash. So i report this.

[crash-2020-08-16_16.20.38-client.txt](https://github.com/ldtteam/minecolonies/files/5080838/crash-2020-08-16_16.20.38-client.txt)

**Comment by ravenbuilder934** [comment]
Use gist.github.com to upload crashlogs, follow the issue template, and update to the latest alpha. Thanks.

**Comment by ShadowProtocol** [comment]
Hi Glassait,
We provide support and fixes for our **alpha** versions only. While they normally indicate instability, in this case they are simply small releases. So please update to the latest before asking for support.
Also as Raven said, use the template in future - it is there for a reason
