### ISSUE TITLE
Crash with unexpected error

### ISSUE THREAD

**Issue by Glassait** [ldtteam/minecolonies#5592]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: minecolonies-0.13.144-ALPHA
- Structurize Version: structurize-0.13.42-ALPHA
- Related Mods and their Versions: 
[1.15.2]+SecurityCraft+v1.8.19.1
Abnormals-Core-1.15.2-1.0.6
absentbydesign-1.15.2-1.1.0
additional_lights-1.15.2-2.0.2
additionalbars-1.5.0
aiotbotania-1.15.2-1.2.3
Aquaculture-1.15.2-2.0.16
astikorcarts-1.15.2-1.0.4
Atmospheric-1.15.2-1.4.1
autumnity-1.3.3-1.15.2
backpacked-1.4.1-1.15.2
BasicNetherOres-1.15.2-4.0.3
betteranimalsplus-1.15.2-8.2.1.96
BiomesOPlenty-1.15.2-10.0.0.366-universal
Bookshelf-1.15.2-5.6.40
Botania-r1.15-388
BotanyPots-1.15.2-2.0.27
Bountiful-1.15.2-3.1.2
carpetstairsmod-1.15.2_v1.4.7
ceilingtorch-1.15.2-v1.7
collective-1.15.2-1.35
compactores-1.15.2-2.1.3
CookingForBlockheads_1.15.2-8.0.3
corpse-1.15.2-1.0.6
create-mc1.15.2_v0.2.4d
curios-FORGE-1.15.2-2.0.2.6
decorative_blocks-6e
DeExtinction-1.15.2-1.0.2
DungeonCrawl-1.15.2-2.0.2
EditSign-1.15.2-2.0.0+7
elevatorid-1.15.2-1.7.1
EnderMail-1.15.2-1.1.3
exoticbirds-1.15.2-1.0.2
Explorercraft-1.15.2-4.0.2
extraanvils-3.1a
extraboats-1.3.6-1.15.2
extragolems-10.2.1
ExtraWeaponsModv1.15.5.2.b237
fairylights-3.0.7-1.15.2
FallingTree-1.15.2-2.2.1
fixedanvilrepaircost_1.15-1.1
flexible_skills-1.15.2-1.2.1-beta
good-nights-sleep-1.15.2-1.1.2
guardvillagers-1.15.2-1.0.8
Harvest-forge-1.15.1-1.2.11-24
Inspirations-1.15.2-1.1.0
ironchest-1.15.2-10.0.3
jei-1.15.2-6.0.2.1
journeymap-1.15.2-5.7.0b32
Kottle-1.5.2
luckyblock-1.15.2-1
luckyores-1.15.2-1.3.1
Ma-Chat-1.15.2-3.1.0
Ma-Enchants-1.15.2-3.1.0
Ma-Essentials-1.15.2-3.1.1
MagicDoorknob-1.15.2-0.0.6.315
mahoutsukai-1.15.2-v1.21.6
Mantle-1.15.2-1.5.15
masonry-1.15.2-0.3.4
mcw-bridges-1.0.4fix-mc1.15.2
mcw-doors-1.0.0-mc1.15.2
mcw-furniture-1.0.1-mc1.15.1+1.15.2
mcws-roofs-1.15.2-v2.0.0
mcws-win-1.15.2-v1.0.2
Mekanism-1.15.2-9.10.9.422
MekanismGenerators-1.15.2-9.10.9.422
MekanismTools-1.15.2-9.10.9.422
minecolonies-0.13.144-ALPHA-universal
mining_dimension-1.15.2-1.0.4
MixinBootstrap-1.0.3
Morpheus-1.15.2-4.2.50
MutantBeasts-1.15.2-1.0.7
mysticallib-1.15.2-2.0.1
mysticalworld-1.15.2-2.0.6
obfuscate-0.4.3-1.15.2
pamhc2crops-1.15.2-1.0.5
pamhc2foodcore-1.15.2-1.0.9
pamhc2trees-1.15.2-1.0.5
pandoras_creatures-1.15.2-1.0.0
Patchouli-1.15.2-1.2-35
performant-1.15-3.10m
planttech2-0.02.11+-+1.15.2
premium-wood-1.15.2-1.1.0
ReadyPlayerFun-1.15.2-1.2.0.5.
shulkersstructures-0.3
simplefarming-1.15.2-1.3.0
SimpleOres2-1.15.2-2.1.8.1
simplylight-1.15.2-0.9.0
Skye's+Bakery+2.1.1+for+MC1.15.2
SolarFluxReborn-1.15.2-15.2.3
Statues-1.15.2-0.1.4.1
StorageDrawers-1.15.2-7.0.2
structurize-0.13.42-ALPHA
The-Endergetic-Expansion-1.15.2-v1.3.2
TinyMobFarm-1.15.2-1.0.8
titanium-1.15.2-2.4.2
torchslabmod-1.15.2_v1.7.0
u_team_core-1.15.2-3.0.2.169
ultra_amplified_dimension-1.15.2-8.0.3
unenchanting-1.15.2-2.0.0
useful_backpacks-1.15.2-1.10.2.73
UselessSword-1.15.2-V1.2.2
valhelsia_structures-15.0.3a
Vulcanite-2.1.2-mc1.15.2
worldedit-forge-mc1.15.2-7.1.0
WorldOfWonder-1.15.2-1.0.6

## Expected behavior

No crash. 

## Actual behavior

My friend connects to my dedicated serveur, and 5 minute later, she crash.
We have a little town with 6 villagers. In buildings we have: town hall, warhouse, delevery hut, 2 bulder hut, 4 citizen hut, farm adn a field.

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: https://gist.github.com/Glassait/72e1e4c479f01e5813f63c06a64b02ba 
- crashlog: https://gist.github.com/Glassait/4413e068389f6d23151d0c0edca3c323 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Yeah, this is a forge bug that happens now and then. Does this happen all the time, or here and there?

**Comment by Glassait** [comment]
1 day nothing, and 1 day she crash everytime, when she connect.
For exemple yesterday she played 3 hours with nothing, and today she can't play.

**Comment by Raycoms** [comment]
When she restarts does it fix it?

**Comment by Glassait** [comment]
No, when she restarts his computer that not fix it, and when i restars the serveur no again

**Comment by Raycoms** [comment]
Tell her to download the jar again and try then please.

**Comment by Glassait** [comment]
Download what? sorry i don't understand what should she download.

**Comment by Raycoms** [comment]
download the mod again

**Comment by Glassait** [comment]
We just dowload it from curseforge.

**Comment by Raycoms** [comment]
Yes, download it again. The jar she has is corrupted.
