### ISSUE TITLE
citizen complaint

### ISSUE THREAD

**Issue by AlmiraVex** [ldtteam/minecolonies#5597]
one of My citizens continuously complains about not working while having a job and having all the items to do said job.... doesn't matter what i do i've changed his job multiple times and nothing changes  not sure if this is a bug or user error!
![2020-08-17_07 03 46](https://user-images.githubusercontent.com/69801335/90399329-04c53b80-e058-11ea-8985-49514644df1d.png)
![2020-08-17_07 03 49](https://user-images.githubusercontent.com/69801335/90399331-055dd200-e058-11ea-9cb4-42dfd270ca50.png)
![2020-08-17_07 03 52](https://user-images.githubusercontent.com/69801335/90399332-05f66880-e058-11ea-98fd-4649649c43f3.png)
![2020-08-17_07 03 55](https://user-images.githubusercontent.com/69801335/90399333-068eff00-e058-11ea-95ca-58a51dfac96a.png)
![2020-08-17_07 03 58](https://user-images.githubusercontent.com/69801335/90399335-068eff00-e058-11ea-9e5d-dcfe18ad6c55.png)

**Comment by Raycoms** [comment]
What is this workers profession?

**Comment by AlmiraVex** [comment]
currently composter but has also been cook and researcher all with the same issue of complaining about not working while literally working or having the stuff to work

**Comment by AlmiraVex** [comment]
> What is this workers profession?
currently composter but has also been cook and researcher all with the same issue of complaining about not working while literally working or having the stuff to work
