### ISSUE TITLE
Builder once again having a phat stroke (He's refusing to build again)

### ISSUE THREAD

**Issue by JevilFromVSauce** [ldtteam/minecolonies#5599]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: minecolonies-0.13.146-ALPHA-universal.jar
- Structurize Version:structurize-0.13.42-ALPHA.jar 
- Related Mods and their Versions:

## Expected behavior
1. HIM TO BUILD SOMETHING.

## Actual behavior
1. HE'S NOT BUILDING ANYTHING!!!! AHHHHHHHHHH!

## Steps to reproduce the issue

1. Build just about anything and he will stager and refuse to build it no matter how many times I restart and fire/rehire him.
2. This especially happens when I try and build the bigger buildings such as Medieval Spruce Warehouse 5, he will sometimes go to place things and just place _ghoooooooost_ racks, because he doesn't actually place anything.

### Logs

- latest.log: https://gist.github.com/JevilFromVSauce/f6074a3203fe75d3683de0337b1b3522
- crashlog: 
### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Please don't open 50000 issues for the same thing. First look through existing issues if there is one open for the same issue.
