### ISSUE TITLE
NPC never clear the hunger

### ISSUE THREAD

**Issue by PSYCLE321** [ldtteam/minecolonies#5602]
I gave him a lot of breads but they keep hunger and don't do anything please help

**Comment by Raycoms** [comment]
They will only accept food that can not further be cooked. Also please fill in the complete template the next time

**Comment by PSYCLE321** [comment]
​
​
-----Original Message-----

**Comment by PSYCLE321** [comment]
I put bread in the inventory because I got a hunger alert, and I didn't do anything after I filled my hunger. It's the same with more bread, and it's the same with other foods. 1.15.2

**Comment by Raycoms** [comment]
Are you on the latest alpha?

**Comment by PSYCLE321** [comment]
0.13.147 or 0.13.146

Maybe 0.13.147

**Comment by PSYCLE321** [comment]
If you leave your job at the chicken farm, you'll get a warning saying you have an AI problem.
How can i solve this?
