### ISSUE TITLE
Food issue

### ISSUE THREAD

**Issue by JevilFromVSauce** [ldtteam/minecolonies#5604]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: minecolonies-0.13.148-ALPHA-universal.jar
- Structurize Version: structurize-0.13.42-ALPHA.jar
- Related Mods and their Versions:

## Expected behavior
1. Citizens (builder I'm specifically @ing) go to get food and they go back to work after served food.

## Actual behavior
1. Citizens go to get food and then they just sit there and don't do anything, but specifically, this happens with the builder, he will say he's hungry but his saturation bar is full.

![image](https://user-images.githubusercontent.com/69450308/90560555-4a275d00-e16d-11ea-8d0c-fc9623d23050.png)

## Steps to reproduce the issue

1. Wait till the builder's hunger goes down after not doing anything (Different issue, he still refuses to build anything that's level 5 passed around 20%)
2. He goes to get food.
3. He just stands there and doesn't go back to the hut afterward.

### Logs

- latest.log: https://gist.github.com/JevilFromVSauce/4ae7f8de42a556913222f54b62f56dfd
- crashlog: 

### Notes
This can easily be fixed by reloging but it happens EVERY TIME they go to get food so its quite annoying.
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by WenXin20** [comment]
I'm using version 0.13.146-alpha for 1.15.2, and have run into this same or similar issue where the colonists are always hungry. I gave one colonist an entire stack of cooked chicken, and she ate the entire stack but is still hungry. 
So my colony is now at a standstill because everyone is constantly hungry...
