### ISSUE TITLE
Construction tape issues

### ISSUE THREAD

**Issue by marvin-bitterlich** [ldtteam/minecolonies#561]
When placing the tape these are some problems at the moment:

When there are stairs, it will remove them:
![image](https://cloud.githubusercontent.com/assets/644950/22708110/6d954b8e-ed75-11e6-9e98-2d9875364e17.png)

The corners render a bit weird:
![image](https://cloud.githubusercontent.com/assets/644950/22708123/78ac431a-ed75-11e6-8f9d-29017b5f0b38.png)

**Comment by marvin-bitterlich** [comment]
Also there are some cases where the tape blocks citizens:

![image](https://cloud.githubusercontent.com/assets/644950/22708157/a0baf144-ed75-11e6-95c6-6b0605ebde96.png)

So I suggest we make it passable.

**Comment by Warrof** [comment]
It also Wipes out Fence Posts, Torches, and Glass
![2017-02-09_12 51 31](https://cloud.githubusercontent.com/assets/21962742/22803117/7febe424-eec8-11e6-95c3-0428e4e8a3e6.png)

![2017-02-09_13 01 58](https://cloud.githubusercontent.com/assets/21962742/22803138/9417da16-eec8-11e6-9d28-278ffca6fed3.png)

It seems that anything that ISN'T a solid block get wiped out.

**Comment by nojo121** [comment]
@Warrof I know... :joy:

**Comment by marvin-bitterlich** [comment]
I suggest we change this to only replace air. This will make patches and holes in the tape, but better that then removing stuff the player may care about. 

We could add a list of blocks that are allowed to be replaced, like f.e. high grass, but idk if that is even needed much.

**Comment by nojo121** [comment]
i allready fixed it. it replaces grass,air and flowers.

**Comment by marvin-bitterlich** [comment]
Does it drop the flowers? I guess some people will complain there xD

**Comment by nojo121** [comment]
No f*ck flowers dude!
