### ISSUE TITLE
tavern isnt save for visitors

### ISSUE THREAD

**Issue by Tyrokas** [ldtteam/minecolonies#5611]
Building: Tavern
Style: Asian
Building Level: 1

Visitors keep dying from "InWall".
they seem trying to both go through and above the fence gates and also keep getting somehow stuck in the building walls.

getting rid of the fence gates doesnt keep them from dying. the tavern is a dangerous place.

**Comment by JevilFromVSauce** [comment]
This happens with all taverns, kinda kooki.

**Comment by someaddons** [comment]
I've got a level 1 asian tavern too and can't reproduce it xD, kinda hard to find the cause

**Comment by Tyrokas** [comment]
Maybe Just Server side ?

**Comment by ScholliYT** [comment]
I'm having the same problem now. Before upgrading my MedievalOak tavern from level 1 to 2 nobody died from `inWall`. Now almost every 5 minutes someone dies. Looks like "the tavern is a dangerous place" 🤣 

Edit: seems like they spawn outside the tavern and try to sit down there
![image](https://user-images.githubusercontent.com/12571895/103317846-c17ad080-4a2c-11eb-8807-b5d763ea5dc6.png)
