### ISSUE TITLE
Deliveryman Exception

### ISSUE THREAD

**Issue by WenXin20** [ldtteam/minecolonies#5612]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- `Minecraft v1.15.2`
- `MineColonies v0.13.152-Alpha`
- `Structurize v0.13.42-Alpha`

## Expected behavior

- For the Deliveryman to deliver items

## Actual behavior

- The deliveryman produces an exception and stops working
- It seems to have occurred after visiting the stash, and after updating to the latest alpha.

## Steps to reproduce the issue

1.  Hire a deliveryman
2.  Place a stash 
3.  Error?

### Logs

- latest.log: https://gist.github.com/WenXin20/5554ed37f2b99872ffd6c186840e4d7f

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Bookshield** [comment]
I got the same Issue in the new Release- Version: minecolonies-0.13.81-RELEASE-universal.jar

**Comment by Raycoms** [comment]
Can you try the latest alpha?

**Comment by jarquafelmu** [comment]
I'm not sure if this is related but I get deliveryman AI error in version 171-Alpha
![image](https://user-images.githubusercontent.com/5807272/90994842-58afb300-e577-11ea-8dfb-5de285501e4f.png)

log https://gist.github.com/jarquafelmu/f918439ad06482b8f1b4b9f203046401

**Comment by Beralath** [comment]
With 171 Beta, courier just ignore the Stash after the first use. They will come pick up the stuff I put inside if I break the Stash and place it back again.

**Comment by Raycoms** [comment]
In the latest this shouldn't happen anymore then

**Comment by Beralath** [comment]
Small addon to this bug : the stuff in the Warehouse Hut (not in the racks) doesn't count as stock. The villager won't see/use it.
It was already the case in the previous version I was using, and still now.

**Comment by ravenbuilder934** [comment]
And sometimes, when you press Sort, it goes into the hut block.

**Comment by Raycoms** [comment]
This should be fixed int he newst. But needs a rs-reset
