### ISSUE TITLE
Town Hall 100% done but the builder doesn't think so

### ISSUE THREAD

**Issue by UndoneDestiney** [ldtteam/minecolonies#5618]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version. 
(according to twitch)
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: minecolonies-0.13.125-ALPHA-universal.ja
- Structurize Version: structurize-0.13.42-ALPHA.jar
- Related Mods and their Versions: forge-31.2.36, Minecolonies Official Pack on Twitch v2.0

## Expected behavior
 The Builder finishes the Town Hall when everything is done

## Actual behavior
 I'm building a medieval birch alternative town hall level 1 and the progress gets up to 100% and then doesn't complete

] 

## Steps to reproduce the issue

1.  Start a colony build some buildings (miner, builder, lumberjack, farmer, large field, guardhouse, tavern) all medieval birch or medieval birch alternative and level 1 successfully
2.  have the builder build the town hall
3.  get to 100 % everything all done and have the builder keep building

### Logs

- latest.log:  <script src="https://gist.github.com/UndoneDestiney/1765b1576882a99002e6ab58cc7a0bc1.js"></script>
- crashlog: 

### Notes
 I went to the discord first and they directed me here I have screenshots of the building request gui and the resource scroll but I couldn't figure out how to upload them to gist, the gui they both show that nothing else is needed and that the building is 100% complete, at first he was stuck trying to place the last 3 torches (the ones next to the doors) it was like that for about an hour before I gave up on him doing it and did it myself, I make sure they were in the correct spot and the building gui agreed with me because it then showed that everything was correct after that it turned to what I said before i even tried hiring him as a guard and making sure that worked before putting him back as a builder again, I also tried canceling the job having him build the guardhouse and then going back to the town hall, there were no problems with the guardhouse it was complete perfectly, I didn't mine the town hall though I didn't know if that would mess things up, I also tried canceling the build request, firing the builder, exiting the game, destroying part of the town hall and having him finish it again but it still won't finish, the town hall is built there is nothing else left to do but the builder just keeps building, its been days in game, and at least 4 hours real time that this has been going on I also tried various combinations of all those things I've never played with Minecolonies before so it is possible I'm doing something wrong and just can't figure out what but it seems like it should just complete the build but all the builder does is run all over the roof run back to the builder run back to the town hall run around it some more then repeat, if I let night come he goes to sleep in the tavern just like all the rest of them, gets up in the morning and continues, I also still have the original 4 citizens so no kids no raids, the world is terraforge biomes o' plenty and I'm in a plains biome if that's important thank you

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by UndoneDestiney** [comment]
I am not that tech savvy so I might have missed something important, if so I'm sorry and I'd very happy to give it to you thank you for the help

**Comment by Talyda** [comment]
You need to update the mod first, that might fix it - you're not on the latest alpha. Latest is minecolonies-0.13.155, and structrize is structurize-0.13.46

**Comment by Raycoms** [comment]
100% does only mean all resources were consumed. We've added a more accurate progress calc to the newest

**Comment by UndoneDestiney** [comment]
It worked thank you, sorry for the trouble
