### ISSUE TITLE
[2669] Builder stops working, goes on strike

### ISSUE THREAD

**Issue by kreezxil** [ldtteam/minecolonies#562]
When the builder encounters an object that doesn't respond to removal with normal vanilla tools, such as the beehive from forestry it presents the following (in this case from a dedicated server): https://gist.github.com/kreezxil/71f864237acfa6ad976431f77c8000d5

My suggestion is to assume that if the player wanted to keep said item they would've removed it before hand, so in the case of this type of issue, it should just remove the block from the world.

**Comment by marvin-bitterlich** [comment]
This is a catch inserted by us, because the beehive asks for a scoop to be mined with and we have not implemented scoop usage for the miner. We will likely improve that notification soon.

**Comment by kreezxil** [comment]
thanks. :)
