### ISSUE TITLE
Builder wants unknown item

### ISSUE THREAD

**Issue by I3estOFF** [ldtteam/minecolonies#5620]
I have this mod with 216 other in my modpack, builder wants unknown item, i tried install new beta .811 for 1.12.2 but still don't work.

![image](https://user-images.githubusercontent.com/63112899/90760316-f7bb7d00-e2e1-11ea-88ca-cf448ac2e6cc.png)

**Comment by Raycoms** [comment]
yeah, unfortunately this is a problem that exists in 1.12 we couldn't solve. This is fixed in 1.15+. However, due to time restrictions we can't offer more support for 1.12.2. Usually a fix is to check which block is in their way and mine it for them.

**Comment by I3estOFF** [comment]
> yeah, unfortunately this is a problem that exists in 1.12 we couldn't solve. This is fixed in 1.15+. However, due to time restrictions we can't offer more support for 1.12.2. Usually a fix is to check which block is in their way and mine it for them.

is there any way to check id of this block?

**Comment by Raycoms** [comment]
apparently the latest alpha got the fix,

**Comment by I3estOFF** [comment]
> apparently the latest alpha got the fix,

It works! On existing world, need to delete colony and create it again ;)
Thanks for help and fast reply ;)

**Comment by I3estOFF** [comment]
@Raycoms 
Alpha have a good fix! 
But its implemented to only first builder!
Next builders have same issue!

To make other builders work, the first builder need to build a buildershut for them.
So it is happening only with lvl 0 builders who need a unknown tool to build their own builder huts

I'm writing just to tell you - the fix is working, but need to be implemented to other builders too :)))

**Comment by ravenbuilder934** [comment]
1.12 isn't supported any more

**Comment by I3estOFF** [comment]
alright! 
Just telling info if u want to fix it

**Comment by baraks300** [comment]
If you are still looking for a workaround for 1.12.2, downgrading to minecolonies-1.12.2-0.11.811-BETA-universal should help. I remembered using it in a Project Ozone 3 world and had no issues with the builders. downside is losing out on some of the  additions that come along with later builds.
