### ISSUE TITLE
Trouble with miner's stairs

### ISSUE THREAD

**Issue by chey-to-mozg** [ldtteam/minecolonies#5631]
After miner mining next level, he have problems with placing of stairs. Because of it he cant go to sleep, or even work
![image](https://user-images.githubusercontent.com/22994194/90893005-e9935c80-e3c6-11ea-94ed-70eb68fc8dfc.png)

**Comment by Raycoms** [comment]
if you destroy the ladder, will it fix itself?

**Comment by chey-to-mozg** [comment]
he replace them as normal after level is complited. main problem is missed stairs, if you place it he will work again
