### ISSUE TITLE
Builder's stopped working on Fortress style colony

### ISSUE THREAD

**Issue by lyricalprimeboy** [ldtteam/minecolonies#5633]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.15.2
- MineColonies Version:0.13.125 Aplha
- Structurize Version: idk, i downloaded the official modpack ver 2.0
- Related Mods and their Versions: Minecolonies Official Modpack ver 2.0, updated on Aug 14, 2020

## Expected behavior

Builders building buildings, colonists not getting stuck on double fence gates
## Actual behavior

When trying to build the fortress town hall, the builders take forever to "finish" it. The structure is there, everything is built, but they just stand there. Eventually it completes, after maybe 30 min or so, idk, didnt record time it took. Then, out of no where, 2 of my 3 builders just wouldn't work. They were fed, they had no requests, etc. They had level 3 builder's huts, and a level 2 town hall. I tried clearing the que, relogging, and nothing worked. They just wouldn't accept or acknowledge any build requests. The third was working fine, until i tried tyo build a level 3 citizen's hut (fortress). It said that an error in the AI had occured and to contact the minecolonies team. Also, in the fortress town hall, they seem to get stuck on all the fince gates. the will open one, then just stand there opening and closing it, trying to open the one next to it so they can walk through. I have to manually right click it for them to get them unstuck.

## Steps to reproduce the issue

I was building the fortress, with all of the buildings placed as expected. I had 3 level 3 builders, a level 2 town hall, 3 level 2 citizen's huts, a level 2 tavern, a level 2 lumberjack and miner, a level 1 deliveryman and warehouse, with requests for the other surrounding buildings: a composter, a resturaunt/cook, a bakery, another deliveryman, a farm, and a cowboy, all being built (as in the structure isn't built yet)
1.  request level 3 fortress citizen's hut
2.  builder attempts to accept build request
3.  he shows a request, and once right clicked, i get the error message of his AI not working

### Logs

- latest.log: N/A
- crashlog: N/A

### Notes

I've uploaded my save file.
[Minecolonies.zip](https://github.com/ldtteam/minecolonies/files/5110416/Minecolonies.zip)
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Mekle001** [comment]
Please upgrade to the newest alpha of Minecolonies and verify it still reproduces, you're running a very old version.
