### ISSUE TITLE
Decorations medievalOak/spruce can not be build/upgrade towards south/north directions

### ISSUE THREAD

**Issue by Bookshield** [ldtteam/minecolonies#5634]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: minecolonies-0.13.161-ALPHA-universal.jar
- Structurize Version: structurize-0.13.42-ALPHA.jar
- Related Mods and their Versions: -

## Expected behavior
- building(segment medieval spruce/oak wall or gate) aligns in the designated direction (south/north direction) with build tool
- Builder builds it
- To upgrade: click upgrade button in the decoration menu
- The builder upgrades in the same direction

## Actual behavior
-Build tool: Building has automatically a west/east alignment
-after correction with the build tool: gets built in the south/north direction correct
-upgrading: clicks upgrade
-building: realigns in a west/east-direction
- can not be cleared by changing player directions
-repeatable

## Steps to reproduce the issue
- See above

### Logs
- latest.log: https://gist.github.com/Bookshield/8fd2a4aadaf37f54a0664763a60e37c0

### Notes
- note: corners remember their orientation correctly and do upgrade correctly.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
You're 80+ versions behind, try updating to the latest alpha, and see if that fixes it =)

**Comment by Bookshield** [comment]
I did. Same errors. Therefore I updated my versions in the main comment. But thanks for reminding me. =3

**Comment by Raycoms** [comment]
It's a schematic issue yeah. Someone has to scan them back in accordingly. #5006
