### ISSUE TITLE
Warehouse voiding items

### ISSUE THREAD

**Issue by Leviwulfish** [ldtteam/minecolonies#5637]
- Minecraft Version: 1.15.2 
- MineColonies Version:  1.13.81 RELEASE
- Structurize Version:structurize-0.13.31-RELEASE
- Related Mods and their Versions: Threw the mod into ATM5, probably the reason for the issue :/

Expected behavior : 
Deliveryman places objects into the warehouse

Actual behavior : 
Deliveryman collects the item, it is visible in their hands, they walk into the warehouse, it disappears, and it is not placed inside the warehouse. Warehouse design is Medieval Dark Oak level 1.

Steps to reproduce the issue

1. Place warehouse and delivery hut
2. Give items to delveryman
3. Wait for deliveryman to enter warehouse
4. Items disappear

### Notes
Survival Multiplayer

**Comment by Raycoms** [comment]
Can you try the latest alpha?

**Comment by Leviwulfish** [comment]
Yeah I'll give it a shot!

**Comment by Leviwulfish** [comment]
Works now! Thank you!
