### ISSUE TITLE
Crash on death

### ISSUE THREAD

**Issue by Beralath** [ldtteam/minecolonies#5641]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.115-ALPHA
- Structurize Version: 0.13.42-ALPHA
- Related Mods and their Versions: modpack Valhelsia 2

## Expected behavior

Not crashing the server.

## Actual behavior

When a citizen dies, and he had a request for the blacksmith, the server crashes.

## Steps to reproduce the issue

1.  Build blacksmith.
2.  Give recipes.
3.  Wait for some guard dies.

### Logs

- latest.log: 
- crashlog:  https://pastebin.com/gUJTUG7i

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MatthiasMann** [comment]
I'm sure that has been fixed in a later version - you should update.

**Comment by Raycoms** [comment]
yes
