### ISSUE TITLE
Bugs and complaints

### ISSUE THREAD

**Issue by AlexFrezerX** [ldtteam/minecolonies#5643]
Hey. I play Minecraft with your assembly, on game version 1.16.1 and Forge version 32.0.108. The first bug was found in a tavern (building style - asian) - the visitors of the tavern "sit" not on the blocks of wood, which are intended for this, but on the blocks that make up the corners of the building. They sit in these corners and begin to choke there, which is why there are constant problems with notification that the number of visitors will be reduced due to rumors that people are dying in my tavern. The second bug was discovered when recruiting knights in watchtowers - they constantly complain that they need a shield despite the fact that the shield is already in their inventory and equipped. The third bug - the builder sometimes "forgets" about the construction of the building and just stands at the builder's house. You have to restart the construction / improvement of the building for the builder to come to his senses. The fourth bug was discovered exclusively on version 1.16.1 - after installing OptiFine, the colonist's interface ceases to appear if you right-click on it. As soon as I uninstalled OptiFine, the interface began to open again.
And in the end, a complaint about the gameplay: It is maddening that all the mobs in the game, which are neutral to the player by default, consider the colonists to be hostile. I have never seen such a large spawn of endermen in the original Minecrfat, but with the installation of Minecolonies, their spawn breaks all records. And one or two endermen can kill half the colony in a matter of seconds until the player sees it. It becomes almost impossible to play, since an enderman who "accidentally" enters the colony kills half of the colonists, which simply destroys all the mood for the game, since you have to wait for the birth and raising of children, and then re-download the experience to these colonists.

**Comment by ravenbuilder934** [comment]
The fourth bug is OptiFine's fault, we can't fix it. The other three bugs might've been fixed in later versions, what version are you running? 

About the endermen, you can turn off mobs attacking colonists in the config. Knight guards should also be able to kill them.

Also, please fill out the entire issue template, it's there for a reason.

**Comment by Raycoms** [comment]
Thanks for the feedback. Please use the template next time. We got issues for 1-2, 4 is optifine. Endermen issues will probably addresses. 3 usually means "fulfill the requests of the builder" or wait some time until the scanning is finished (but also got open issues for it)
