### ISSUE TITLE
After rollback some towns have no owner or officers

### ISSUE THREAD

**Issue by ProsperCraft** [ldtteam/minecolonies#565]
### Minecolonies version

minecolonies-universal-1.10.2-0.6.2724.jar

### Expected behavior

rolling back the world folder would bring the world back to exactly the state it was before the rollback.

### Actual behaviour

The town was fine, the citizens were fine, but some towns not all are missing their permissions entirely.

**Comment by Raycoms** [comment]
Will be fixed with the next update, will offer a "refresh owner command"
