### ISSUE TITLE
Unable to unlock research related to town hall level 4.

### ISSUE THREAD

**Issue by LlmDl** [ldtteam/minecolonies#5650]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.15.2
- MineColonies Version: minecolonies-0.13.171-BETA-universal.jar
- Structurize Version: structurize-0.13.42-ALPHA.jar

## Problem description

When I was building my level 4 townhall the builder stalled, and after repeated hirings and firings, still would not finish the job with only a handful of tile entities left to go (this was on many versions past.)

To get the townhall built I used creative mode to finish it.

This made it so I cannot do any of the research requiring the level 4 townhall. 

I thought that upon completion of the level 5 townhall I would have the ability to complete the level 4 townhall-required researchs but no luck.

Can I manually edit something to be able to do the research? 

### Notes or related things

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Which exact research is this?  Even having the townhall pasted this should work (I do this all the time)

**Comment by LlmDl** [comment]
The first and most important is the Village 75 citizen cap, it requires a level 4 townhall.
Iron Armour, Agile, and Livesaver II also require it.

Am I able to use an NBT editor or a command to unlock these researchs?

**Comment by Raycoms** [comment]
Do you have an university level that is high enough for it?

**Comment by LlmDl** [comment]
This might be the facepalm moment. I'll go check later.

**Comment by LlmDl** [comment]
I haven't had the upgrade complete yet but I'm sure it was the only thing hanging me up. I guess the message it shows "Building not high enough level" (paraphrasing it) had me thinking it was referring to the Town Hall level not being a high enough level, and not the University itself.
