### ISSUE TITLE
Colonist Menu does not Open When Right Clicking Colonists

### ISSUE THREAD

**Issue by Numnums22** [ldtteam/minecolonies#5651]
### Prerequisites 

- [X ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.1
- MineColonies Version: 0.13.154-ALPHA
- Structurize Version: 0.13.44-ALPHA

## Problem description

Whenever I right-click on my colonists, the menu that is supposed to pop up does not appear. Instead, they simply say a voice line. Everyone else on the server I'm on does not have this issue. When I go to right-click on their colonists, I have the same issue.
### Notes or related things

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Remove OptiFine, it's their fault.
