### ISSUE TITLE
AI bugs

### ISSUE THREAD

**Issue by PSYCLE321** [ldtteam/minecolonies#5654]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.171 BETA
- Structurize Version:0.13.35 ALPHA
- Related Mods and their Versions:

## Steps to reproduce the issue

1. A
2. 
3.  AIs are getting more and more error.
/

### Logs

- latest.log: 
https://gist.github.com/PSYCLE321/ea127326d8ef25ced011c82d2a28490c
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Please update to the latest
