### ISSUE TITLE
No one is working

### ISSUE THREAD

**Issue by johananderssonv** [ldtteam/minecolonies#5655]
Don't know what I'm doing wrong, the first day builders are doing just fine, then night comes, all citizens gather around the town hall and the next day no one is working, they just stand around the town hall. I've given them one stack of steak each, the clipboard is empty even though I have build orders and the builders _do_ have tools. halp pls
![halp](https://user-images.githubusercontent.com/69393005/91299758-6f861d80-e7a2-11ea-950a-5cd6f48d2547.PNG)

**Comment by Raycoms** [comment]
Unless you fill in the full template we can't help you.

**Comment by johananderssonv** [comment]
Oh sorry, what template?

**Comment by Nightenom** [comment]
https://github.com/ldtteam/minecolonies/issues/new/choose

**Comment by johananderssonv** [comment]
My bad, got redirected from the minecolonies website and it didn't give me a template

**Comment by johananderssonv** [comment]
- Minecraft Version: 1.16.1
- MineColonies Version: 0.13.154 alpha
- Structurize Version: 0.13.44 alpha

## Problem description
Don't know what I'm doing wrong, the first day builders are doing just fine, then night comes, all citizens gather around the town hall and the next day no one is working, they just stand around the town hall. I've given them one stack of steak each, the clipboard is empty even though I have build orders and the builders do have tools.

### Notes or related things
I'm using the valhelsia 3 modpack
---

**Comment by Raycoms** [comment]
yep, guessed so. fixed in the newest.
