### ISSUE TITLE
Colonie disappeared after update to 1.16.2 - 0.13.182-ALPHA

### ISSUE THREAD

**Issue by Inomutso** [ldtteam/minecolonies#5659]
Hi Team

Today I got an Issue while updating the 1.16.1 Alpha to minecolonies-0.13.182-ALPHA-universal.
Starting up with the MC Launcher, Forge told me that I have to update to forge-1.16.2 and structurize needs to be updatet too.
I did so und installed forge-1.16.2-33.0.22 and took structurize-0.13.48-ALPHA.

Starting up my Colonie with that was ok, but I could not see any citizens running around.
Had a look in the Town Halls Hut, and the block is telling me, that there is a Colonie near by, but could not see my Colonie anymore
The Town Hall Hut Block gave me only the option, to start a new Colonie.

So I had to restore a Backup from my Colonie with minecolonies-0.13.179-ALPHA-universal and structurize-0.13.44-ALPHA, and this one is still ok.

My 1.16.x Colonie has been started with minecolonies-0.13.123-ALPHA-universal and is nearly ready and full researched, having a few known issues

I am playing Singleplayer, almost in Creativ Mode. I could not see much about this Issue in the Logs, they are just full of errors with the Server Config.

regards

Inomutsu

[Inomutso_Logs_20200827.zip](https://github.com/ldtteam/minecolonies/files/5136181/Inomutso_Logs_20200827.zip)

**Comment by konsaril** [comment]
It is not possible to port Saves between Minecraft versions. The newest Version of Minecolonies for 1.16.1 is the 179

**Comment by Raycoms** [comment]
Yeah, I'd expect this. 1.16.2 changed again way too much for this to be well compatible.
