### ISSUE TITLE
Guardtower isn't buildable

### ISSUE THREAD

**Issue by Kemtari** [ldtteam/minecolonies#5660]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.16.2
- MineColonies Version:0.13.182-ALPHA-universal
- Structurize Version:0.13.48-ALPHA
- Related Mods and their Versions: None

## Expected behavior

Placing the Guardtower would remove the item from the inventory.
Building menu after right clicking the guard tower would appear.
## Actual behavior

Placing the Guardtower dosn't remove the item from the inventory but still places the block.
After right clicking the Guard tower block a error appears saying:
"This block is missing its respective building, try restarting or loading a backup!"

![2020-08-27_16 15 57](https://user-images.githubusercontent.com/70330942/91454092-da0d8b00-e880-11ea-8075-857be2e6b8b7.png)

## Steps to reproduce the issue

1. 
place any guardtower with or without the structurice tool (without will remove the item from inventory)
2.  rightclick the guardtower block
3.  Error message appears

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
This must be either outside of a colony or your colony is broken. At least in the newest 1.16.2 this works fine for me
