### ISSUE TITLE
Right-click Bug on Minecraft 1.16.1

### ISSUE THREAD

**Issue by JospehPoggi** [ldtteam/minecolonies#5664]
I play a multiplayer server and cannot right click any colonie.
P.D.: I'm spanish player sorry for bad inglish.

**Comment by ravenbuilder934** [comment]
This is OptiFine's fault. Remove it and you should be able to.

**Comment by Raycoms** [comment]
and please report it to them too

**Comment by oliandcharis** [comment]
Being that optifine is a must have for a majority of players it kinda leaves it to you guys for compatibility not to just close the post, if we can't right click on our colonists it makes it unplayable, even adding a tool that opens up the relevant gui would work, i have sent an email to optifine also as suggested, but i honestly don't think they are going to change their code for one mod, apologies for the hard truth but it is down to your dev team to fix the 1.16 port

**Comment by Raycoms** [comment]
That's where you are wrong. If optifine breaks shit, they fix it. It can't be the right solution that every cleans up after them.
