### ISSUE TITLE
little tiles compat

### ISSUE THREAD

**Issue by Darcmut** [ldtteam/minecolonies#5665]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.12.2
- MineColonies Version: 1.12.2-0.11.841-ALPHA-universal
- LittleTiles Version: v1.5.0-pre199_34_mc1.12.2
- CreativeCore Version: v1.10.16_mc1.12.2

## Expected behavior
Material list from the scan tool should display blocks created by LittleTiles tools. (Similar to how Chisel and Bit blocks are created)

## Actual behavior
LittleTiles blocks created with its tools display in the material list as tile.null and have an invisible block texture.

## Steps to reproduce the issue

1. Chisel any block using the LittleTiles hammer, saw, etc.
2. Select this area using the Scan Tool
3. View the material list
4. Profit and see that blocks are named tile.null

### Notes
https://github.com/ldtteam/minecolonies/issues/3092 says its fixed but it isnt.

**Comment by someaddons** [comment]
1.12 is not receiving updates anymore

**Comment by Raycoms** [comment]
(that's why that issue is also closed)
