### ISSUE TITLE
Error Loading mods & in game

### ISSUE THREAD

**Issue by DangerDr** [ldtteam/minecolonies#5666]
### Prerequisites 

- [X ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.184-ALPHA
- Structurize Version: 0.13.52-ALPHA
- Related Mods and their Versions: https://i.imgur.com/AuPLA7T.png

## Expected behavior

able to get into the game

## Actual behavior

https://i.imgur.com/x0joR08.png &/or https://i.imgur.com/N7fSPuh.png

## Steps to reproduce the issue

1.  
2.  
3. 

### Logs

- latest.log:  https://gist.github.com/DangerDr/de403d5a65985cc85df15acc19567183
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
yes, you got an incompatible structurize/minecolonies version either upgrade minecolonies or downgrade structurize

**Comment by DangerDr** [comment]
so which one is compatible with which?

**Comment by ravenbuilder934** [comment]
Get the latest alphas of each, those should work.

**Comment by DangerDr** [comment]
but thats what i had when i got the error

**Comment by ravenbuilder934** [comment]
Maybe downgrade Structurize then

**Comment by Raycoms** [comment]
oh meh, our buildsystem got an issue and didn't release the newest minecolonies, go to < 51 structurize until then

**Comment by DangerDr** [comment]
that fixed it. Thank you
