### ISSUE TITLE
Restaurant

### ISSUE THREAD

**Issue by Dallas1117** [ldtteam/minecolonies#5667]
I've tried placing the restaurant 3 times now. Tried a restart. and it won't place. It places this block where the restaurant block should be. And in the logs on console I get the message "[16:13:44] [Server thread/ERROR] [minecolonies/]: BuildTool: building is null!
java.lang.Exception: null"

Medieval Spruce restaurant
https://hastebin.com/liqugojeda.bash exact error in console

It's placing a Solid Placeholder in the place of the restaurant block. 

Usually a quick restart fixes this issue for me but didn't seem to make a difference. 

Latest versions for 1.16.1 for both minecolonies and structurize and forge 108

**Comment by Raycoms** [comment]
Yeah, it's a schematic issue #5006 for this.
