### ISSUE TITLE
Builder doesn't build his/her hut

### ISSUE THREAD

**Issue by Bease80** [ldtteam/minecolonies#567]
### Minecolonies version

version 1.11-0.6.2290

### Expected behavior

- Builder's chat and builder building his/her hut

### Actual behaviour

- No chat for builder (he/she doesn't request anything) and he/she doesn't build just keeps by the builder's chest's side and looks at it,

### Steps to reproduce the problem

1. Build supply ship
2. Place Town hall chest
3. Place Builder's hut chest
4. Click build on builder's hut
5. Supply required resources (shows when I click on the chest)
6. Builder comes to the chest and just stays there doing nothing and asking for nothing

**Comment by xavierh** [comment]
Does he have the correct tools? I notice that sometime the builder are not asking for them.

**Comment by Bease80** [comment]
I gave them wooden AND cobblestone pickaxe, axe and shovel just to be sure still nothing happens, they just keep looking at the block. 
Tried 3 different worlds. same problem. 
Tried firing builder and hiring someone else, as well as killing them, same problem.

**Comment by Raycoms** [comment]
if his hut is level 0 you have to give him wooden tools.

2017-02-09 19:15 GMT-02:00 Bease80 <notifications@github.com>:

**Comment by Bease80** [comment]
As I said before, I gave them wooden tools as well as stone ones but they definitely had wooden tools. Don't know what's wrong

**Comment by Raycoms** [comment]
can you provide us with the log?

2017-02-09 19:45 GMT-02:00 Bease80 <notifications@github.com>:

**Comment by Bease80** [comment]
For some strange reason, just because I was going to send you the logs the bastard started to work... lol... but thank you guys anyway!

**Comment by Raycoms** [comment]
Did it rain?

2017-02-09 20:02 GMT-02:00 Bease80 <notifications@github.com>:

**Comment by Bease80** [comment]
Not really, I  just logged in the game to know to copy the latest log and the builder started to do her thing!

**Comment by Raycoms** [comment]
Really can't reproduce this in the latest versions.
