### ISSUE TITLE
Lumberjack gives error and stops working

### ISSUE THREAD

**Issue by IlonaOttenEmphebion** [ldtteam/minecolonies#5670]
I am playing the 1.16 modpack Valhelsia 3 and the Lumberjack gives an error like "my AI has encountered an issue, let server owner or mod owner know". He will eventually stop working, restarting does not help, only firing and re-hire will help for a while, but the error will return. Exception is found at 10:34 in enclosed log. Cheers!
[Log.txt](https://github.com/ldtteam/minecolonies/files/5143689/Log.txt)

**Comment by Raycoms** [comment]
Fixed in newest
