### ISSUE TITLE
(1.15.2) minecolonies-0.13.184-ALPHA Tried to access field 

### ISSUE THREAD

**Issue by McKitten** [ldtteam/minecolonies#5671]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: forge-1.15.2-31.2.36
- MineColonies Version:minecolonies-0.13.184
- Structurize Version:structurize-0.13.52
- Related Mods and their Versions:
dcintegration-1.3.3-1.15 (not local which still crashes but mentioned in server crash-report)
CTM-MC1.15.2-1.1.1.13 (had to be disabled locally to view the minecolonies crash but disabling on server has no effect)

Update from 
minecolonies-0.13.161 to 184 alpha
structurize-0.13.42 to structurize-0.13.52
& boot server as usual.

https://gist.github.com/McKitten/719c0f1f8ce1f528b3181d3cb174a9cd
server debug available but at cursory glance provides no new information

### Notes
https://gist.github.com/McKitten/77e9fedb97455610e6c99f22ef9442c0 is the debug from local rather then server an appears to have the same issues but I can't verify this from what I am reading.

retrograde to minecolonies-0.13.180 & structurize-0.13.42 loaded fine.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Nightenom** [comment]
Known, wait for new version to come out

**Comment by Raycoms** [comment]
Orion will take care of it tomorrow, downgrade structurize until then to < 51
