### ISSUE TITLE
Colony Banner Crash

### ISSUE THREAD

**Issue by AkGamerRo** [ldtteam/minecolonies#5673]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.1
- MineColonies Version: minecolonies-0.13.160-ALPHA-universal
- Structurize Version: structurize-0.13.43-ALPHA
- Related Mods and their Versions: 

## Expected behavior
The game should show perview of structure that contain colony banner.

## Actual behavior
Game crashes when trying to view structures that contain colony banner.

Videos: https://youtu.be/ykcfFeUud9I
             https://youtu.be/B12pXr3ZOx0

## Steps to reproduce the issue

1.  Scan a structure that contains Colony Banner.
2.  Use build tool to preview the schematic that contains Colony Banner.
3.  Game crashes.

### Logs

- latest.log: https://gist.github.com/AkGamerRo/6591a19b5b1ae159a71f1b3b0f062c5b
- crashlog: https://gist.github.com/AkGamerRo/ac15f14ca8506ba8661432754be14cd4

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Bandaid fix applied until Night checks on structurize
