### ISSUE TITLE
Delivery Man just stands in the Warehouse

### ISSUE THREAD

**Issue by kingledo** [ldtteam/minecolonies#5676]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1,16,1
- MineColonies Version: latest
- Structurize Version: latest
- Related Mods and their Versions: -

## Expected behavior
 Delivery guy hired, should start picking stuff up and put it in the rack

## Actual behavior
 As soon as I hire the Deliv. guy he walks into the warehouse and stands still next to the warehouse chest. He goes to sleep etc but doesn´t work

## Steps to reproduce the issue

1. just hire the dev guy
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
They're supposed to do this if they don't have anything to do. Run /mc colony requestsystem-reset (your colony ID here), then click 'Request Pickup Now' on a hut.

**Comment by kingledo** [comment]
That really seem to do the trick 
thanks a lot :)
