### ISSUE TITLE
Issue with maximum number of citizens in a colony

### ISSUE THREAD

**Issue by Flar3on12** [ldtteam/minecolonies#5678]
Hi there, I am playing Valhelsia 2 Minecolonies 0.13.78 ALPHA and Structurise 0.13.31 and Forge 1.15.2 31.2.33
I am having an issue with my citizen cap
The default is 25 and I have the first university research level would should put it at 50. However in my town hall it states my max is 25. is there a way to change that config or to redo a university research part, or a way to circumvent this? Perhaps there is a way to edit the number in my configs??? I can provide logs if needed. Just not sure what logs would be required.

**Comment by Raycoms** [comment]
Usually the thing is:
a) Do you have enough housing?
b) Is the research finished
c) Is the config value in the common config big enough
d) Did you try to restart after config change?
