### ISSUE TITLE
Warehouse won't build

### ISSUE THREAD

**Issue by MightyGaming66** [ldtteam/minecolonies#568]
### Minecolonies version

version 1.10.2

### Expected behavior

- For the Builder or the Building wand to build the WareHouse

### Actual behaviour

- Builder won't build the warehouse and the building tool says it isn't there

### Steps to reproduce the problem

1. Retrying it multiple times
2. Puting the Warehouse in different spots

**Comment by marvin-bitterlich** [comment]
Hmm any more infos on what happened? The building tool does not show you stuff btw

Can you check your TownHall for the Workorder? Try rehring the builder? Stuff like that

**Comment by Raycoms** [comment]
Please reopen if able to reproduce.

**Comment by MightyGaming66** [comment]
Ive tried all that stuff and it still does not work

**Comment by Raycoms** [comment]
can you try the newest version?

2017-03-05 18:31 GMT-03:00 MightyGaming66 <notifications@github.com>:
