### ISSUE TITLE
Barracks towers and guard towers dont work, when barracks is being built Builders say they have run into a AI issue.

### ISSUE THREAD

**Issue by ULittleTurd** [ldtteam/minecolonies#5686]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context  

- Minecraft Version: 1.16.2
- MineColonies Version: 0.13.197-ALPHA
- Structurize Version: 0.13.48-ALPHA
- Related Mods and their Versions: 

## Expected behavior
 When right clicking the barracks tower or guard tower, it will open the GUI and you will be able to use it.

## Actual behavior
  When the builder is building the barracks, after placing the Barracks Tower it gives and error that says something along the lines of "My AI has run into an issue, please locate the latest .log file" It also says "This block is missing its respective building, try loading a backup or restarting" Twice in chat.

## Steps to reproduce the issue

1.  Start a new world (creative)
2.  Place town hall
3.  Place guard tower or build a barracks and have a builder build it.

### Logs

- latest.log:  This should hopefully be it https://gist.github.com/DarpaTheSav/06d27c33b06a83b535cecf75e44c7c31
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
We do need the latest.log file

**Comment by ULittleTurd** [comment]
> We do need the latest.log file

I'll try to find it

**Comment by ULittleTurd** [comment]
Forgot to mention, I added it.

**Comment by Raycoms** [comment]
Not in this latest.log, can you check through some older ones if it contains a com.minecolonies.coremod exception?

**Comment by ULittleTurd** [comment]
I'll look around and try to find it

**Comment by ULittleTurd** [comment]
If I were to try to reproduce the problem and gave you that latest.log file, would that work?

**Comment by ULittleTurd** [comment]
https://gist.github.com/DarpaTheSav/06d27c33b06a83b535cecf75e44c7c31

**Comment by Raycoms** [comment]
Fixed in next release (already version merged, missing release)
