### ISSUE TITLE
minecraft crashes

### ISSUE THREAD

**Issue by ENC4YP7ED** [ldtteam/minecolonies#5689]
![SharedScreenshot](https://user-images.githubusercontent.com/70538228/91751660-6d1e2c00-ebc5-11ea-9d5e-5c413836544c.jpg)
![wtweterzwrrzz](https://user-images.githubusercontent.com/70538228/91751663-6db6c280-ebc5-11ea-8851-35616cfb33a3.jpg)
 Idk why it say that pls help

**Comment by ravenbuilder934** [comment]
Please fill out the entire template

**Comment by Nightenom** [comment]
And downgrade structurize...
