### ISSUE TITLE
Minecoloines not working on 1.16.2 server

### ISSUE THREAD

**Issue by Anthonys1** [ldtteam/minecolonies#5690]
I made a 1.16.2 server with just minecolonies, Forge, and JEI, My server has the mods and so does my Client. When I log into the server and look at JEI the recipes for minecoloines are there. If I click them it does nothing (Which normally with JEI a recipe comes up) if I use the wiki to see the recipe and try it in the crafting table nothing comes up, its just blank but weirdly enough showing up perfectly fine in JEI. No Server errors or anything.

**Comment by Nightenom** [comment]
Please use the bug issue template.

**Comment by Raycoms** [comment]
Are you sure the versions are fine on the server/client? This looks like the server started without minecolonies or the client did

**Comment by Anthonys1** [comment]
The server console has no errors on the matter, i made sure the server file is running 1.16.2, my client and forge.

**Comment by Raycoms** [comment]
I mean, the minecolonies nd structurize jars, do they both load on both sides?

**Comment by Anthonys1** [comment]
I do see a bunch of lines in the console saying minecolonies and structurize, nothing about errors just seems like a normal loading process.

**Comment by Raycoms** [comment]
Please fill out the complete template and send the latest.log

**Comment by Anthonys1** [comment]
I actually got a new error retrying the server launcher, it just says missing data pack mod: Minecolonies in the console

**Comment by Raycoms** [comment]
download the newest minecolonies 1.16.2 and newest structurize (minecolonies should be only a few minutes old)

**Comment by Anthonys1** [comment]
Would you be able to provide the links to the proper downloads, just so i can’t possibly mess this up and waste more of your time. I appreciate the help thus far

**Comment by Raycoms** [comment]
https://www.curseforge.com/minecraft/mc-mods/minecolonies/files/3046794
https://www.curseforge.com/minecraft/mc-mods/structurize/files/3046516

**Comment by Anthonys1** [comment]
tyvm, everything is working fine now. Appreciate the help
