### ISSUE TITLE
Problem with decoration "walls/asian gate2"

### ISSUE THREAD

**Issue by gabrielmariense** [ldtteam/minecolonies#5691]
Millenaire for MC 1.15.2 - Alpha 0.13.200

The decoration is created as the gate1 version to be upgraded but on the decoration controller there's no option to upgrade because it says I the decoration is at max level or not upgradable.
![image](https://user-images.githubusercontent.com/53842256/91788081-b2e8ed80-ebe1-11ea-956e-333ca521ecb6.png)

**Comment by Raycoms** [comment]
#5006

**Comment by Raycoms** [comment]
Please repost there
