### ISSUE TITLE
Town Hall not completing (stuck at 50%-58%)

### ISSUE THREAD

**Issue by Dragonbornn** [ldtteam/minecolonies#5693]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context : Town Hall not completing (stuck at 50%-58%)
- Minecraft Version:1.16.2
- MineColonies Version:0.13.203
- Structurize Version:0.13.59
- Related Mods and their Versions: tested on Forge: 33.0.31 and Forge 33.0.22

## Expected behavior
After place all the blocks, the Town Hall should be completed

## Actual behavior
 Sometimes the builder cannot place all the blocks (missing touchers and carpets) but after cancel and try again sometimes he puts all the blocks but still not completing the building(in the Builder's hut show me that only 50% or 58% is completed but all blocks were place)

## Steps to reproduce the issue

1. Place the Town Hall ( Medievalsprucealternative)
2. Start the building
3. Building completing getting stuck

### Logs

- latest.log: 
- crashlog: 

### Notes
I tested in a Server(with other mods) and my personal world(with just minecolonies and structurize), when in Server i can see in the console something like this (Town Hall ''coordinates'' World Structure using Medievalsprucealternative instead of Medialsprucealternative), Yes the same names. The whole colony just have 1 builder's hut (level 1) and 1 House (level 1) (Town Hall not completing)

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Dragonbornn** [comment]
i Forgot to mention that the whole colony just have 1 builder's hut (level 1) and 1 House (level 1) (Town Hall not completing)

**Comment by Raycoms** [comment]
Same as #5687
