### ISSUE TITLE
Client crash when interacting with builder

### ISSUE THREAD

**Issue by jadewolf05** [ldtteam/minecolonies#5700]
When I try interacting with my builder my client crashes with the following stack:
https://pastebin.com/gVijyLXx

Builder's Hut 4
Worker Level: 9

minecolonies-0.13.125-ALPHA-universal.jar

Let me know if more information is needed.,

**Comment by ravenbuilder934** [comment]
Try updating and see if it still happens. The latest 1.15.2 version is 210 last I checked.
