### ISSUE TITLE
Builder won't complete town hall

### ISSUE THREAD

**Issue by dcniedan** [ldtteam/minecolonies#5702]
When trying to build the Medievalsprucealternative structure the builder eventually stops working. I've gotten to the point where all that is left to place is the 2 carpets, 13 torches, and 7 ladders, but I cannot get the builder to make any further progress.

**Comment by AlmiraVex** [comment]
Having the same issue with barracks lvl 3 Asian style it looks done but they have a couple chiseled stone and item frames to place still but they just keep walking in circles . I've stopped and restarted the build  with no difference even changed the builder and nothing

**Comment by Raycoms** [comment]
Same as #5693
