### ISSUE TITLE
Warehouse not showing location of rack

### ISSUE THREAD

**Issue by Iuhegi** [ldtteam/minecolonies#5704]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.1
- MineColonies Version: 0.12.201-ALPHA
- Structurize Version: 0.13.44-ALPHA
- Related Mods and their Versions: N/A

## Expected behavior
When i click the question mark next to an item in the warehouse inventory viewer, I expect it to outline the rack which contains said item. I saw this working before and it usually draws a green outline around the rack containing the item.

## Actual behavior
The rack is not displaying anything, there is a message that shows up in chat, but no visible marker shows up to say which rack it found.

## Steps to reproduce the issue

1. Open the game with minecolonies installed.
2. Open the warehouse and click the chest in the bottom right corner of the first page.
3. Click the question mark next to an item
4. Look around and there are no highlighted blocks.

### Logs

[latest.log](https://gist.github.com/LukeGi/5ad1ccfefcd3c00c1fd8bd5ea6e4bfd9)

### Notes
I'm playing the Valhesia 3 modpack with minecolonies updated to the lastest verion before launching.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Nightenom** [comment]
_there is latest.log field for reason, not everything wrong will result in crash_

**Comment by Nightenom** [comment]
There is something wrong with the depth buffer. Please, try to reproduce using a copy of the same world but with minecolonies only installed.
Discovered error:
`[16:29:44] [Thread-65/INFO]: OpenGL debug message, id=1282, source=API, type=ERROR, severity=HIGH, message=GL_INVALID_OPERATION error generated. Depth formats do not match.`
opengl description:
GL_INVALID_OPERATION is generated if mask​ contains GL_DEPTH_BUFFER_BIT or GL_STENCIL_BUFFER_BIT and the source and destination depth and stencil formats do not match.

**Comment by Iuhegi** [comment]
attempted to repoduce in a vanilla environment and the issue no longer persisted... I guess the issue is with whomever is causing the opengl error... I'll report it to the valhesia team if I can.
