### ISSUE TITLE
fully upgraded town hall but the border didnt expand

### ISSUE THREAD

**Issue by AlmiraVex** [ldtteam/minecolonies#5705]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.1
- MineColonies Version: 0.13.127 Alpha
- Structurize Version: 0.44 Alpha
- Related Mods and their Versions:

## Expected behavior

town hall causes the border to expand at lvl3 lvl4 lvl5
## Actual behavior

border expands when i put other huts near it but not when i lvl up town hall

## Steps to reproduce the issue

no idea
1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
Was your town hall hut block closer than 5 chunks from the current border? If it was further away, it won't expand the borders, because the borders are already more than 5 chunks away.

**Comment by AlmiraVex** [comment]
> Was your town hall hut block closer than 5 chunks from the current border? If it was further away, it won't expand the borders, because the borders are already more than 5 chunks away.

that's a possibility i didnt know that was something that changed whether the border expanded or not

**Comment by Raycoms** [comment]
Yeah, if you place two guard towers in the same chunk it won't give you double the claim. Similarily, if you already claimed a lot of space around the townhall with guard towers, the townhall won't add additional claim around it.

**Comment by Talyda** [comment]
I keep sharing my very bad drawing - This post I made on on discord was for the swineherder, but same method applies.

> Pretend the red line is your colony border. Solid blue squares are the chunk you place your swineherder in, semi-filled squares are the chunks the swineherder will expand.
> Top left one won't actually expand your colony borders at level 1, because the colony is already expanded that far - but bottom right one will expand those three chunks out to the side

![image](https://user-images.githubusercontent.com/17323101/92219819-394f4900-eeda-11ea-870c-1060e6deb6af.png)
Assuming that worked there should be a very bad drawing attached =P
