### ISSUE TITLE
Updated. Builder Bug. 

### ISSUE THREAD

**Issue by Dallas1117** [ldtteam/minecolonies#5707]
[X ] I am running the latest alpha version of MineColonies and Structurize for my Minecraft version.
[ X] I checked the MineColonies/Structurize wiki and made sure my issue is not covered there.
[X ] I made sure that this issue is not a duplicate of any existing issue.
Context
Minecraft Version: 1.16.1
MineColonies Version: 0.13.213
Structurize Version: 0.13.61
Related Mods and their Versions:
Not Sure.
Expected behavior
Builder upgrading hut. (he was before updating)

Actual behavior
Giving error when headed to upgrade House/Citizen Hut from level 3 to level 4. 

https://gyazo.com/cb158bd6654bcdbb8aa72d262c0f55cd

Steps to reproduce the issue
Basically I was upgrading my citizen huts to level 4 before I logged off 2 days ago. I got on today and saw structurize and minecolonies were both updated (1.16.1) and I updated. I went into game and walked over to my builder. He was working like normal then I saw he was over at the "House" Hut with a red gear like he wanted something so I did recall worker to the builder hut and got the error that says post my lastest.log.

Maybe start an upgrade then go update the files?
The builder had everything he needed and went to work on the hut.
He went to the House to start upgrading and got the error.
Logs
https://gist.github.com/Dallas1117/acf98168a70cb78b547260c0aefecad7

latest.log:
crashlog:
Notes
Viewers
Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Dallas1117** [comment]
Also Ray if you need access to my server. I can give FTP information and IP/Modpack to server

**Comment by Raycoms** [comment]
can you go through the older logs and try to find a log where a search for "com.minecolonies" brings up an exception in the log?

**Comment by Dallas1117** [comment]
Things I have tried:
I cancelled all build requests. No fix.
I fired and rehired the Builder. (Fixes the error until she tries upgrading another building again)
I tried doing a different build. 

I'll find that com for you.

**Comment by Dallas1117** [comment]
This is the log which I started the upgrades. 08/29/2020
https://gist.github.com/Dallas1117/ca8da0412b67ca2119686ae491c72e69

Here is a log where that threw some exceptions: 08/28/2020
https://gist.github.com/Dallas1117/8d95d97e1f755e962e035a04082dd44a

Here is a log where it threw some errors related to placing supply camps in the wild (unrelated to my village): 08/29/2020 
https://gist.github.com/Dallas1117/3603f4e92a04c0dc5fd7034e526dea92 

First time the Worker paused from working due to the error: 09/04/2020
https://gist.github.com/Dallas1117/952162e5ed37a0c6a798ccd5d7ef5ecf

As you can where I started the upgrades, he was having no issues going through each one.

**Comment by Raycoms** [comment]
Strange, no builder related error in any of them...

**Comment by Dallas1117** [comment]
Okay so I fired the builder and let someone else take the job to recreate the error with someone new. (more information.)

Was working fine until she went to start building.

Heres the LASTEST log with that information.

https://gist.github.com/Dallas1117/72edbab8060b7980e3ec24d83aa7d1be

**Comment by Dallas1117** [comment]
Also the new builder didn't throw an error until I started to give her some of the items and she started to head towards the House hut.

**Comment by Raycoms** [comment]
still nothing in this log... Maybe in the debug.log?

**Comment by Dallas1117** [comment]
Debug log:
https://gist.github.com/Dallas1117/814e9035ef937861ca3d7d98d680195d

New issue
Miner is throwing same error in console now.
Here is the lastest log for that:

https://gist.github.com/Dallas1117/a57aba2defa4c0c688b4553f60fb9627

**Comment by Raycoms** [comment]
fixed structurize pushed out

**Comment by Dallas1117** [comment]
Still getting the error in console for Miner and Builder.

**Comment by Raycoms** [comment]
On the latest structurize?

**Comment by Dallas1117** [comment]
Lastest log

https://gist.github.com/Dallas1117/187ca375a012051d9594dade45ef6538

Yes the lastest structurize.

**Comment by Dallas1117** [comment]
Sorry here is the exception from console

https://gist.github.com/Dallas1117/08daf9130133f922a9401af9e24db227
