### ISSUE TITLE
Builder breaks fences before continuing building

### ISSUE THREAD

**Issue by Iuhegi** [ldtteam/minecolonies#5708]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.1
- MineColonies Version: 0.13.213-ALPHA
- Structurize Version: 0.13.61-ALPHA
- Related Mods and their Versions:

## Expected behavior

When a builder has stopped building for some reason, due to dying or being fired or having the contract cancelled temporarily, they should restart building the structure from where they left off.

## Actual behavior

The builder breaks blocks like fences when they restart building a half completed structure, before continuing to build it.

## Steps to reproduce the issue

1. Start a builder building.
2. Let them get to a point where they have places fences horizontally connected.
3. Fire them
4. Wait a Second
6. Rehire them.
7. The builder starts to break the fences they just placed.

### Logs

Not sure if logs are needed, let me know if they are, i didn't see anything in them relating to this.
- latest.log: 
- crashlog: 

### Notes

I'm playing on the Valhesia 3 modpack with minecolonies and structurise updated to the latest version before launching.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
This is because we can't store the progress position 100% of the times to avoid lag. This way, the progress is +- a bunch of blocks. Since fences adjust to their position their blockstate might be off and they have to be removed and placed again. This is intended behaviour since everything else would cause lag.
