### ISSUE TITLE
[Feature] Builder/Miner Blacklist

### ISSUE THREAD

**Issue by WenXin20** [ldtteam/minecolonies#571]
### Expected behavior

- A blacklist for blocks that you don't want the builder or miner to break, such as chests.
- Builder then leaves the chest added by the player alone when repairing a building if its not in the way of other blocks, such as in an empty area.

### Actual behaviour

- No blacklist, so builders break chests placed within the building area.

**Comment by xavierh** [comment]
I do agree with you and I will add:

- The builder should not remove leave when clearing out (wast of time)
- The builder should not remove grass and replace it later on with dirt

**Comment by Raycoms** [comment]
So how would you add this list in a config?
In some cases we want him to remove chests etc? A list of ids?
Additionally, if he does that he should, when removing chests or anything.
Always look for items on the ground inside the build site.

**Comment by WenXin20** [comment]
Maybe have a section in the config to blacklist block & tile entity ids.
Yes, he would only remove the chests or the blacklisted block id if it is in the way of building/repairing the building, but not if there is space for it. The builder would check the config for which blocks to potentially ignore.
Yes, if the chests are borken, the builder should pick up the items instead of leaving them on the ground.
.

**Comment by harleypig** [comment]
If the builder breaks a full chest he won't be able to pick up all the items. Perhaps have all citizens notice items left on the ground and pick them up just before they despawn?

**Comment by Raycoms** [comment]
Closed in favor of joint issue.

**Comment by darthvader45** [comment]
Agreed.  When it comes to the miner, I usually mine modded ores and in many cases use Mystical Agriculture to create the ingots directly.  As such, I don't want the Minecolonies miner to be digging em up if the workers don't use em.
