### ISSUE TITLE
Builder AI Bug-"My AI has run into an issue..."

### ISSUE THREAD

**Issue by KalSkirata45** [ldtteam/minecolonies#5711]
[latest.log](https://github.com/ldtteam/minecolonies/files/5176690/latest.log)
![2020-09-04_14 39 46](https://user-images.githubusercontent.com/70776687/92279720-88d34c00-eebd-11ea-9a6e-977b8d8fba89.png)

I am playing on the Valhelsia 3 modpack and the pack just updated. I am not sure if this is the reason why my builder decided to bug out, but they did. I recalled the worker, restarted the game, and restarted the worker as well. I could not fire them, the button is grayed out. The message just says, " My AI has run into an issue, please locate the latest.log file and send it to the Minecolonies authors with this message. 

Let me know what else you need.

**Comment by Raycoms** [comment]
Please use the full template

**Comment by Orangutan-Steve** [comment]
I've got the same issue. Valhelsia 3 modpack when I try to have the builder upgrade their hut, it gives me the same error. 
[latest.log](https://github.com/ldtteam/minecolonies/files/5212350/latest.log)

**Comment by Raycoms** [comment]
Update to the newest alpha

**Comment by Orangutan-Steve** [comment]
okay updating to the newest version fixed the issue on a single player world. but after updating on the server, all of the buildings say they don't have a respective building and i don't own the colony anymore

**Comment by Raycoms** [comment]
something corrupted your colony from loading then, you can try the loadbackup command
