### ISSUE TITLE
Missing graphic elements

### ISSUE THREAD

**Issue by MBalent** [ldtteam/minecolonies#5712]
### Prerequisites 

- [ x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.222-ALPHA
- Structurize Version: 0.13.64-ALPHA
- Related Mods and their Versions:

## Expected behavior

Shepherds's, Swineherd's, Chicken Farmer's, and Forester's Hut icons appear in the crafting bench and in inventory when crafted.  When placed the block graphics show.  GUI with builder's hut and colonists do not show "missing element..." text.

## Actual behavior

Shepherds's, Swineherd's, Chicken Farmer's, and Forester's Hut icons do not appear in the crafting bench and in inventory when crafted.  When placed the black&purple 'missing graphic' block appears.
GUIs for huts and townspeople have 'missing element' message on them

![image](https://user-images.githubusercontent.com/26933892/92303825-9c76c500-ef46-11ea-9ee1-acd54eb4bb95.png)
![image](https://user-images.githubusercontent.com/26933892/92303830-aa2c4a80-ef46-11ea-96b5-12ee6c7566ef.png)
![image](https://user-images.githubusercontent.com/26933892/92303835-b44e4900-ef46-11ea-9a3b-fcd8c225f2ea.png)

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by someaddons** [comment]
optifine breaks it
