### ISSUE TITLE
Builder UI has run into a issue

### ISSUE THREAD

**Issue by Slimjimjimmy** [ldtteam/minecolonies#5714]
### Prerequisites 

- [ x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1:16:1
- MineColonies Version: 0.13.213-ALPHA
- Structurize Version: 0.13.61-ALPHA
- Related Mods and their Versions:
Valhelsia 3 Modpack

## Expected behavior
 Trying to upgrade builders hut to level 2

## Actual behavior

MY builders brain breaks and he doesn't do anything except stand around and sleep

## Steps to reproduce the issue
[latest.log](https://github.com/ldtteam/minecolonies/files/5178194/latest.log)

1.  
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Slimjimjimmy** [comment]
first time trying to submit a bug report sorry for anything that I may have missed or done wrong.

**Comment by Raycoms** [comment]
Update to the latest alpha of both minecolonies and structurize please
