### ISSUE TITLE
Builder Drowns

### ISSUE THREAD

**Issue by TheJellyCat** [ldtteam/minecolonies#5715]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.1
- MineColonies Version: 0.13.213-ALPHA
- Structurize Version: 0.13.63-ALPHA

## Problem description
Builder will stand under water while attempting to build and drown themselves.

### Notes or related things
EDIT: fixed copy-paste error. (oops).

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
screenshots?

**Comment by TheJellyCat** [comment]
He was working on the fisher's hut here. (Included is his death alert.)

![Minecolonies_Issue2](https://user-images.githubusercontent.com/65913379/92308054-e670a280-ef68-11ea-8371-22fce9746970.PNG)

I found his inventory floating here. He didn't trap himself, it seems, just... never came up for air.
![Minecolonies_Issue1](https://user-images.githubusercontent.com/65913379/92308057-ecff1a00-ef68-11ea-8ad8-5ab4c763f311.png)

**Comment by Nikademus** [comment]
I've had this happen when building bridges as well.  I think they build over their own head and drown.
