### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by nico10n** [ldtteam/minecolonies#5717]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: minecolonies-0.13.180-ALPHA
- Structurize Version: structurize-0.13.42-ALPHA
- Related Mods and their Versions:

## Expected behavior
 Everything working as intended

## Actual behavior
 Whenever I interact with the builder and he sets off building something I (and everyone else) get kicked off the server and am unable to log in again, we get the error message saying that payload may not be larger than 1mb 

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Run /mc colony requestsystem-reset-all. Also, please fill out the full template.

**Comment by nico10n** [comment]
Im trying to locate the latest.log file, and the problem is that I can not log into the server at all because of this problem, give me a moment

**Comment by Raycoms** [comment]
yeah, the cmmand raven said
