### ISSUE TITLE
Builder's hut won't upgrade.

### ISSUE THREAD

**Issue by HappyDuc** [ldtteam/minecolonies#5718]
When I try and make my builder upgrade their hut from level 1 to level 2 it requests all the items and when I give them all of the items they say something like "There has been a problem with my AI", I'm playing on the twitch launcher and playing the Valhelsia 3 mod pack which runs on 1.16.1, I am trying to build the cave style builder's hut and it constructs level 1 fine but I can't get a level 2 hut.

**Comment by Raycoms** [comment]
Upgrade, valhelsia picked the 213 version that has a bug on 1.16
