### ISSUE TITLE
Deconstructed and placed again huts don't keep their taught recipes

### ISSUE THREAD

**Issue by ravenbuilder934** [ldtteam/minecolonies#5720]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 195 alpha
- Structurize Version: not related
- Related Mods and their Versions: none

## Expected behavior
When you deconstruct, pick up, and then place a hut block again, the hut block wouldn't lose taught recipes.

## Actual behavior
All the taught recipes are deleted (except the defaults).

## Steps to reproduce the issue

1. Teach a hut recipes
2. Deconstruct it and pick it up
3. Place it again and look at its recipes

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
yep, they only keep their level. They don't keep the worker or any other settings either. That is intended.
