### ISSUE TITLE
Builder digging up too much grass in Medieval Oak Alternative Restaurant

### ISSUE THREAD

**Issue by iShockGIT** [ldtteam/minecolonies#5722]
Hello. I am reporting I believe is to be a bug.

My builder dug up too much grass and it made my Medieval Oak Alternative Restaurant look like it's floating. I hope that you can identify it and then fix it. Because I don't think he should dig up that much grass.
![2020-09-06_09 59 42](https://user-images.githubusercontent.com/18996042/92327550-77f31980-f028-11ea-84c1-a72c91bfdd61.png)
![2020-09-06_09 59 43](https://user-images.githubusercontent.com/18996042/92327551-77f31980-f028-11ea-9ad4-aead0ded06b2.png)
![2020-09-06_09 59 40](https://user-images.githubusercontent.com/18996042/92327552-77f31980-f028-11ea-9dbd-68c16d221960.png)

**Comment by Raycoms** [comment]
#5006
