### ISSUE TITLE
Private Server Structurize Crash on Startup

### ISSUE THREAD

**Issue by Kenzec** [ldtteam/minecolonies#5724]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context minecolonies-0.13.231-ALPHA-universal.jar +structurize-0.13.66-ALPHA.jar and 1.16.2 Minecraft

- Minecraft Version:1.16.2
- MineColonies Version: 1.16.2
- Structurize Version:1.16.2
- Related Mods and their Versions: Minecraft Forge 1.16.2 - 33.0.37

## Expected behavior
 Server would start normally 

## Actual behavior
 Server crashes on startup

Log Link : https://gist.github.com/Kenzec/abd81b507dec3dd71c7ae8af4475253f
(Sorry that the Log is so messy the server tries to restart itself the time

Crash Report Log: https://gist.github.com/Kenzec/0e1331ce30b590d867f4f8e59d17bf7e

### Notes
 I wish it would work

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
So it crashes, but you don't send us the crashlog? =D

**Comment by Kenzec** [comment]
Quite new to all this let me add the crash log

**Comment by Kenzec** [comment]
Like this?

**Comment by Raycoms** [comment]
Can't find anything Minecolonies related in this log.

But ther eis this: "rate limit exceeded"

**Comment by Kenzec** [comment]
What does this mean?

**Comment by Raycoms** [comment]
Idk :shrug:

**Comment by Raycoms** [comment]
But those are just manual restarts and no crashes. Can you check in your crash-logs folder?

**Comment by Kenzec** [comment]
Just a second i paste a new link in the request

**Comment by Kenzec** [comment]
There we go

**Comment by Nightenom** [comment]
update your forge, logs you have provided are for 33.0.5

**Comment by Raycoms** [comment]
I double checked, yes this should be fixed with a newer forge version
