### ISSUE TITLE
Construction marker alternative design

### ISSUE THREAD

**Issue by marvin-bitterlich** [ldtteam/minecolonies#573]
We should have an alternative/changed design for the construction marker. Something more like sticks with rope.

An example (without the fancy stuff) would be: 
![image](https://cloud.githubusercontent.com/assets/644950/22833184/3c2552cc-efb1-11e6-8686-a0309b89d287.png)

We should then let the players decide what skin they like more

**Comment by nojo121** [comment]
How do you like this one:
![constructiontape_south2](https://cloud.githubusercontent.com/assets/17111591/22850685/5f8ad28e-f00e-11e6-9c8c-96a703b6e29a.png)

**Comment by kedamono** [comment]
There's this as well:
![barrier-construction4](https://cloud.githubusercontent.com/assets/23420636/22851656/fbf66f38-efdd-11e6-8b5f-097052069b5b.jpg)

**Comment by marvin-bitterlich** [comment]
@kedamono That one looks not really medieval 😆 

@nojo121 that is definitely not bad!
