### ISSUE TITLE
My builder can't finish the building

### ISSUE THREAD

**Issue by xtcaurora** [ldtteam/minecolonies#5730]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.1  (I am playing Valhelsia 3, if that helps)
- MineColonies Version:
- Structurize Version:
- Related Mods and their Versions:

## Expected behavior
  My builder would build normally.

## Actual behavior
 I get this message I saved as a screenshot.

 
![Screenshot_123](https://user-images.githubusercontent.com/70870739/92343488-e4563300-f091-11ea-8351-b398deef2dda.png)

## Steps to reproduce the issue

  I'm not sure how this happened in the first place. I was going back and forth, giving him supplies and then he started giving me this message.

1. 
2. 
3. 

### Logs

  

- latest.log:     https://gist.github.com/xtcaurora/e27559718005b6e5e974c8aa7d133c85
- crashlog:  No crash

### Notes
  

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Update
