### ISSUE TITLE
Anything from minecolonies that I place crashes the game

### ISSUE THREAD

**Issue by cvexxx** [ldtteam/minecolonies#5731]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.81-release-UNIVERSAL
- Structurize Version: 0.13.42-ALPHA

## Problem description

Placing a town hall or supply camp crashes my game

### Notes or related things

[crash-2020-09-07_11.43.43-client.txt](https://github.com/ldtteam/minecolonies/files/5182729/crash-2020-09-07_11.43.43-client.txt)

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
You're very far behind on versions, update both to the latest alpha and try again maybe

**Comment by Raycoms** [comment]
yes, update to latest alpha of both structurize + minecolonies
