### ISSUE TITLE
Medieval Spruce Cook (Restaurant) structure difference between level 3 and 4

### ISSUE THREAD

**Issue by eractnod** [ldtteam/minecolonies#5732]
In Mine Colonies 0.13.221-Alpha with Minecraft 1.16.1 and forge 32.0.108, When doing the preview of the Medieval Spruce Cook, it looks like the entire building shifts and lifts when going between level 3 and 4.  This looks like it will require the entire structure to be removed and built differently when increasing levels.  It also changes the marked build location.  Attached screen shots of the level 3 and 4 previews.  I looked through some of the other cook previews and none of them do this change.
![2020-09-07_07 34 30](https://user-images.githubusercontent.com/5204558/92383980-4a1bdc80-f0dd-11ea-9756-1f9863b3e9a4.png)
![2020-09-07_07 34 45](https://user-images.githubusercontent.com/5204558/92384015-53a54480-f0dd-11ea-8fb2-adc447c2c39d.png)

**Comment by Raycoms** [comment]
#5006
