### ISSUE TITLE
Tavern Visitors suffocating in walls

### ISSUE THREAD

**Issue by JasonEpic** [ldtteam/minecolonies#5735]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.1
- MineColonies Version: 0.13.232-ALPHA
- Structurize Version: 0.13.5-ALPHA
- Related Mods and their Versions:

## Expected behavior
Tavern visitors sit in chairs normally

## Actual behavior
Tavern visitors sit in non-existent chairs from the level 1 Asian Tavern structure, causing them to suffocate in walls of level 2 Asian Tavern

![2020-09-07_09 33 49](https://user-images.githubusercontent.com/70909337/92406725-9a029f80-f0ed-11ea-89b9-4b1eefda3a73.png)
![2020-09-07_09 34 26](https://user-images.githubusercontent.com/70909337/92406726-9b33cc80-f0ed-11ea-9296-20737382ba6e.png)

The seats from the Level 1 tavern compared to where they align with the Level 2 Tavern, causing the visitors to suffocate when they sit in them.

![2020-09-07_13 53 14](https://user-images.githubusercontent.com/70909337/92416536-c8df3c80-f112-11ea-8a3b-dd26af008f12.png)
![2020-09-07_13 53 18](https://user-images.githubusercontent.com/70909337/92416540-cd0b5a00-f112-11ea-8557-aad76f972dd2.png)

## Steps to reproduce the issue

1. Build level 1 Asian Tavern
2. Upgrade to level 2
3. Wait for death messages to come in every morning saying your Tavern is a dangerous place

### Logs

- latest.log: https://gist.github.com/JasonEpic/b275581135879d02514c4ec6f9bc09e8
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by JasonEpic** [comment]
I had to put glass blocks in place of where their heads would be so they dont suffocate when they sit there anymore, I just covered them up with oak trap doors from another mod to hide them, as well as placing more around the building to make it symmetrical and look like they actually belong on the build. (also side note when i first discovered this i was walking by the tavern when i saw a visitor sit in the wall, after saving them by mining them out another did the same thing like a minute later and i had to save them, causing me to preemptively take out the whole wall on the right side. Then while I was off managing a builder giving them resources I got another death message and found they were also sitting somewhere in the back wall so I took out all of the walls, resulting in the first picture. It wasn't until finding another visitor sitting on a block of air on the inside of the building (where the fourth log bench is in the level 1 tavern) when I realized that it wasn't the stipped logs at the bottom of the walls they were sitting on, it was the past positions of the original tavern

**Comment by someaddons** [comment]
can you try repairing the building?

**Comment by JasonEpic** [comment]
> can you try repairing the building?

I broke down the walls of the building to stop them from suffocating, like in the first and second picture

**Comment by someaddons** [comment]
repairing should restore the right positions, thats why :D

**Comment by JasonEpic** [comment]
Ohh i see what you’re saying, I thought you meant place the blocks back by hand lol. I’m new to minecolonies so i didnt realize you meant like actually hitting repair in the build options menu. I’ll try that out if it happens again when I upgrade the building eventually

**Comment by someaddons** [comment]
ye those positions are part of the schematic and set by the builder when he finishes a task

**Comment by JasonEpic** [comment]
I see, I tried it in a creative world and it seems to have worked, haven't seen anyone sit in those positions plus they’ve sat in the new chairs

**Comment by someaddons** [comment]
think the issue then was caused by sth preventing the builder from setting it nicely, like a loading issue or crash
