### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by CyborgRyno603** [ldtteam/minecolonies#5738]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: Forge 1.15.2
- MineColonies Version: 0.11.852 ALPHA universal
- Structurize Version: 0.13.31 RELEASE

## Problem description

I launch the game and get the error. "Minecolonies (minecolonies) encountered an error durring the common_startup event phase
tried to access field com.ldtteam.structurize.util.StuctureLoadingUtils.originFolders from class com.minecolonies.coremod.MineColonies"
### Notes or related things

[latestlog.txt](https://github.com/ldtteam/minecolonies/files/5189019/latestlog.txt)

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Update your versions. Both your MineColonies and Structurize are very old.

**Comment by CyborgRyno603** [comment]
> Update your versions. Both your MineColonies and Structurize are very old.

I don't think I can, these are the latest for 1.15.2 and my friend doesn't want to update his server.

**Comment by ravenbuilder934** [comment]
The latest alphas are MineColonies 0.13.237 and Structurize 0.13.64. If your friend won't update, it'll keep crashing.

**Comment by CyborgRyno603** [comment]
> The latest alphas are MineColonies 0.13.237 and Structurize 0.13.64. If your friend won't update, it'll keep crashing.

Ok, I'll see what I can do.
