### ISSUE TITLE
Game crashes when placing supply camp. Have newest version!

### ISSUE THREAD

**Issue by senzamorej** [ldtteam/minecolonies#5739]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.237 ALPHA
- Structurize Version:0.13.64 ALPHA
- Related Mods and their Versions: Valhelsia Modpack, Optifine

## Expected behavior
 Placing supply wagon to begin my colony

## Actual behavior
 game crashes on right clicking with Supply Camp in hand

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
log?

**Comment by senzamorej** [comment]
what is that?

**Comment by senzamorej** [comment]
how do i get it?

**Comment by Raycoms** [comment]
there is a folder with crash-logs or crahs-reports or so, the newest there should be it

**Comment by ravenbuilder934** [comment]
Go to your instance folder, then find the latest.log. Paste that into https://gist.github.com and share the link here

**Comment by senzamorej** [comment]
i don't know how to do that i've had to open valhelsia like 8 times and it takes 10 minutes each time

**Comment by senzamorej** [comment]
[latest.log](https://github.com/ldtteam/minecolonies/files/5189417/latest.log)

**Comment by ravenbuilder934** [comment]
Open your instance folder, then go to the folder crash-reports. Paste the latest one into https://gist.github.com and post the link here.

**Comment by senzamorej** [comment]
website says it takes to long and stops

**Comment by senzamorej** [comment]
i don't know what you're asking for can i just post the log here
 is this what you want https://gist.github.com/senzamorej/ce01a53f193f486bad72b207494ea39a

**Comment by Nightenom** [comment]
update your optifine
if issue persists send new logs

**Comment by ravenbuilder934** [comment]
Yes, except Ray needs the crashlog, not the latest.log. Go to your crash-reports folder (in your instance folder) and paste the latest one.

**Comment by Nightenom** [comment]
@ravenbuilder934 this one was enough

**Comment by senzamorej** [comment]
but val2 doesnt support past pre23?

**Comment by Nightenom** [comment]
you have to either update or remove optifine

**Comment by senzamorej** [comment]
i just want to play block game not learn2code

**Comment by Raycoms** [comment]
Are you using optifine at the moment? Optifine is currently not compatible with minecolonies.

**Comment by senzamorej** [comment]
are you kidding? fuck modded minecraft lol this is why i pay for games

**Comment by Nightenom** [comment]
just update your optifine, with this attitude you are not gonna play half of existing games

**Comment by Raycoms** [comment]
You just earned yourself a block from our github repos. Learn how to treat others properly and then come back maybe.
