### ISSUE TITLE
Warehouse inventory isn't recognized by deliveryman

### ISSUE THREAD

**Issue by Pelemesh** [ldtteam/minecolonies#5740]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.2
- MineColonies Version: 0.13.185
- Structurize Version: 0.13.44
- Related Mods and their Versions:

## Expected behavior

Put some items requested by builder into stash, expected them to be brought into warehouse and then delivered to builder

## Actual behavior

Items sometimes brought into warehouse block inventory instead of racks, same happens when using sort button
items sometimes sorted into that inventory
Looks like Delivery man do not recognize it as part of warehouse storage because builders keep asking for same items and requesting those items by post box doesn't work either

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
yeah, should be fixed in newest. Please take care, the warehouse chunks have to be loaded to be able to deliver anything
