### ISSUE TITLE
Warehouse lvl5 emerald rack upgrade

### ISSUE THREAD

**Issue by Pelemesh** [ldtteam/minecolonies#5741]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.2
- MineColonies Version: 0.13.185
- Structurize Version: 0.13.44
- Related Mods and their Versions:

## Expected behavior

Expected to upgrade lvl5 warehouse 3 times with emerald and have items nicely sorted

## Actual behavior

After i used upgrade 3 times all double racks had 108 slots as expected but could not longer be sorted by sort button.
Also deliveryman stopped placing items on those racks aswell as seeing items on them as part of warehouse inventory.
There was only one single rack that they used, when it got full items delivered or sorted went into nowhere, but taking items of the rack and sorting warehouse returned items back to that rack.
After clearing all items this way I ended up with all warehouse stock duped.

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
That's a rather old version, this should be fixed in the newest
