### ISSUE TITLE
Crash oping clipboard

### ISSUE THREAD

**Issue by Pelemesh** [ldtteam/minecolonies#5742]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.2
- MineColonies Version: 0.13.185
- Structurize Version: 0.13.44

## Problem description

crash report
https://pastebin.com/pnG8029e
### Notes or related things

That started happeing after my builder requested flint and steel, which recipe I taught to blacksmith crashes started happening after that
Even though resource scroll says that he has flint and steel he still has cog above his head and keeps asking for one
Opening his gui and clicking past his request speech crashes game in the same way

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Fixed in newest
