### ISSUE TITLE
Crafters improved recipes

### ISSUE THREAD

**Issue by Pelemesh** [ldtteam/minecolonies#5745]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.2
- MineColonies Version: 0.13.185
- Structurize Version: 0.13.44
- Related Mods and their Versions:

## Expected behavior

Requested 3 red beds to be crafted, with fletcher having improved her recipe she should request 6 wool and 6 planks
https://gyazo.com/913b470a8dc236bb39fe4efae2f21af8

## Actual behavior

9 wool and planks been delivered, so 3 of both were leftover in block inventory
3 beds are delivered into postbox, request updated 
https://gyazo.com/5454ce9ec331335976bff23c94a36e9b
now they are just crafting beds undlesly

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Also on the next request? Because if the recipe is improved during the request, this is normal.

**Comment by Pelemesh** [comment]
No, I made request with fletcher having improved recipe already, but i just found second default recipe in recipe list, removed it, made request it worked fine, not sure why there were 2 recipes though

**Comment by Pelemesh** [comment]
to update on improved recipes:
Deliveryman keeps running iron chestplates from blacksmith to a guard tower, there are 3 in tower's inventory 
https://gyazo.com/4fefa82af3b3440b383487767b320899
All 3 guards have full gear sets though
https://gyazo.com/31cbace845cfd4538b730d6f27a9d361

**Comment by Raycoms** [comment]
Yeah, stuck requests are already in the dman issue reported
