### ISSUE TITLE
Deleted Colony; Can't Replace

### ISSUE THREAD

**Issue by lkendal793** [ldtteam/minecolonies#5746]
The most recent player to join my server placed his townhall underground wanting to make a dwarven town. We realized that it would take a lot of excavation so we deleted the colony so we could blow up a bunch of space for it. Towards the end of doing so he went to place his townhall again but it won't let him do it anywhere near where the old one was. It switches between saying that there is a colony there and other things like the nearest colony being within 600 blocks. It even will say that the colony id 4 (his deleted colony) is too close.

**Comment by ShadowProtocol** [comment]
Please use the issue template next time. Or for questions like this one, ask at the MineColonies [Discord](https://discord.gg/zjA75K8).

If you haven't used it already, you may find the ``abandon`` command useful. Check it out in more detail on the wiki.

**Comment by Raycoms** [comment]
Try again to delete colony id 4. Did it get properyl deleted? And ye discord is good for these things
