### ISSUE TITLE
Restaurant Recipe/Request Issue

### ISSUE THREAD

**Issue by JesseLeeBusch** [ldtteam/minecolonies#5747]
### Prerequisites 

- [X] I am running the _near_ latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.222-ALPHA
- Structurize Version: 0.13.64
- Related Mods and their Versions: Minecolonies Official Modpack v2.4

## Expected behavior
In the Level 3+ restaurant, when I teach the hut recipes for specific items and set the hut to maintain a stock of those same items, I expect the cook to request the items of her assistant. I then expect the assistant to request the ingredients he/she needs to craft the recipes and satisfy the cook's request. 

## Actual behavior
The restaurant's cook puts in a request with a "crafter" to make the recipe, but nothing progresses further than that. The request sits in the cook's queue indefinitely. 

**The recipe taught to the restaurant**
![image](https://user-images.githubusercontent.com/7978407/92558888-59f20880-f224-11ea-9693-32648f7f2ee3.png)
**The keep item in stock request**
![image](https://user-images.githubusercontent.com/7978407/92558908-65ddca80-f224-11ea-90c2-999569e33f5a.png)
**The cook's craft request**
![image](https://user-images.githubusercontent.com/7978407/92558925-6e360580-f224-11ea-9c79-99d446d5434b.png)
**The assistant cook's open requests, which are blank. It is interesting to note that the "paper scroll" texture is not loading for the assistant cook.**
![image](https://user-images.githubusercontent.com/7978407/92559058-af2e1a00-f224-11ea-8778-e1b55b420410.png)

## Steps to reproduce the issue

1. Get a restaurant to level 3
2. Hire a cook and assistant cook
3. Teach restaurant the minecraft:beetroot_soup recipe
4. Add minecraft:beetroot_soup to minimum stock list with 1 stack
5. Observe errant behavior with cook's request system.

### Logs

- latest.log: https://gist.github.com/JesseLeeBusch/b624bdfb8708f10947e849606c34737f

### Notes
I do have a few other mods installed in addition to the Minecolonies Official Modpack. I'll list them here (in case there is a known incompatibility.) 
- titanium 1.15.2-2.4.2
- industrial-foregoing 1.15.2-2.3.3
- Mekanism 1.15.2-9.10.9.422
- MekanismGenerators 1.15.2-9.10.9.422
- MekanismTools 1.15.2-9.10.9.422
- refinedstorage 1.8.8
- ImmersiveEngineering 0.15-108
- buildinggadgets 3.3.5
- MysticalAgriculture 1.15.2-3.0.10
- Cucumber-1.15.2-3.0.8
- Industrial+Agriculture[Core] 1.15.2-1.7.0
- Industrial+Agriculture[Mekanism] 1.15.2-1.6.1
- Industrial+Agriculture[Industrial+Foregoing] 1.15.2-1.6.1
- Cyclic 1.15.2-0.4.1
- BonsaiTrees 2.1.2.6
- ftb-backups 2.1.0.2
- ChickenChunks 1.15.2-2.5.0.77-universal
- pamhc2foodextended 1.15.2-1.0.0

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
So you ticked you got the latest alpha but you wrote you got MineColonies Version: 0.13.222-ALPHA, which one is true?
This was improved/fixed in a recent PR. So I'll close it for now.

**Comment by JesseLeeBusch** [comment]
@Raycoms I updated to the latest I could find on CurseForge as of this morning: 0.13.244. 
The errant behavior is fixed with the vanilla Beetroot soup recipe. Thank you for letting me know of the recent fix.
