### ISSUE TITLE
[2669] fisherman says hut too far from water, but hut is on water!

### ISSUE THREAD

**Issue by kreezxil** [ldtteam/minecolonies#575]
![2017-02-10_10 31 16](https://cloud.githubusercontent.com/assets/3880072/22834866/4bf6dc64-ef7c-11e6-91ce-fd62eb6410fa.png)

1. See the hut
2. see the water
3. be confused

**Comment by marvin-bitterlich** [comment]
We had that one already I think? Can you do a search and link them?

**Comment by kreezxil** [comment]
Possibly related issue at #323

**Comment by kreezxil** [comment]
btw, this is not new with 2669, it was also prevalent in 2604 and possibly the other builds as well.

**Comment by Raycoms** [comment]
That occasionally happens but he should notice he is close pretty fast?
He stopped working?

Am Freitag, 10. Februar 2017 schrieb kreezxil :

**Comment by kreezxil** [comment]
Nope, he works good little behind off. Unlike that builder.

-----Original Message-----

**Comment by Raycoms** [comment]
So no problem =D

It's something related to pathfinding, we unfortunately can't calculate if he didn't find any correctly.
