### ISSUE TITLE
building medieval oak alternative forester wrong bottom floor

### ISSUE THREAD

**Issue by Swantsy** [ldtteam/minecolonies#5750]
On the forester medieval oak alternative the bottom floor gets dug out whilst it should be on ignore mode. plaving blocks down before it is done the builder removes the dirt flooring.

![image](https://user-images.githubusercontent.com/19387179/92615628-9a519500-f2bd-11ea-83f0-b159fb2d59f2.png)

easy to replicate, just build the building and see for yourself.

**Comment by Raycoms** [comment]
post to #5006 please
