### ISSUE TITLE
Restaurant LvL 3 + Pam's Harvestcraft Issue

### ISSUE THREAD

**Issue by JesseLeeBusch** [ldtteam/minecolonies#5752]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.244
- Structurize Version: 0.13.64
- Related Mods and their Versions: pamhc2foodcore-1.15.2-1.1.0

## Expected behavior
A restaurant @ lvl 3 taught a recipe for Pam's Harvestcraft that involves a secondary output is able to cook the recipe. 

## Actual behavior
The Cook's Assitant gets stuck in a loop, fetching a cooking tool from the hut's inventory only to return it to the huts inventory before they can use it.

## Steps to reproduce the issue

1. Teach the restaurant the recipe for Stock (pot + cod)
2. Teach the restaurant the recipe for Carrot Soup (pot + carrot + stock)
3. Request restaurant keeps 1 stack of Carrot Soup in stock
4. Insert ingredients into hut's inventory manually. (32 cod, pot, 64 carrots)
5. Observe Assistant Cook's errant behavior.

### Logs
- latest.log: https://gist.github.com/JesseLeeBusch/668b81aa791c1a289c2cae97f3c4c80d

### Notes
I know that generally bugs like this should be mentioned as part of *Mod Compatability* requests. However, the changelogs from previous releases specifically mention that Pam's Harvestcraft pots and other secondary outputs should be supported, and I can't find a mention of a time when that support was dropped. 

## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by JesseLeeBusch** [comment]
Small update: The walking back and forth was being caused by the fact the Pot kept being put in storage in another part of the restaurant. When the pot is in the hut block, the Assistant cook takes the pot out of inventory and then puts it back into the inventory endlessly.

**Comment by Mekle001** [comment]
I think I need more details. I am unable to reproduce this

**Comment by JesseLeeBusch** [comment]
@Mekle001 
https://www.dropbox.com/s/arrvtvjs3ihhcra/RestaurantPam%27sHCIssue.mp4?dl=0 Here is a link to a video of me observing the issue. 

Happy to try and provide more details. What kind of things would you want to know?

**Comment by Mekle001** [comment]
can you double check the requests for the cook, and make sure that you have enough in the hut?

**Comment by JesseLeeBusch** [comment]
I have double-checked things, and it looks like the Cooking Assistant was actually short the number of carrots he needed for the request. (He had 61 carrots instead of 64.) 

Now that he has all the carrots he needs, he is properly cooking. I do not know why he wasn't requesting the last few carrots he needed from the inventory, but that's probably a seperate issue. (And might be explained with why the pot was going in and out of his inventory.)

**Comment by Mekle001** [comment]
Ok, that matches my expectation. I suspect a colonist stole your other 3 carrots. I'll see if I can limit that.

**Comment by JesseLeeBusch** [comment]
Thanks! That and it looks like the cook is stealing things from her assistant if its something she can cook in a furnace. 

When I provided the Cook's Assistant with cod to make the soup stock, the chef stole the cod to put in the furnace. I was able to get around that by using one of the alternative soup stock recipes. (Bone + Pot)

**Comment by Mekle001** [comment]
That should only happen if the request for the soup stock hasn't actually been created yet. My guess is that you provided the cod before the cook made the request to the assistant, since that happens on a relatively slow cadence (~25 seconds)

**Comment by JesseLeeBusch** [comment]
Okay, that's good to know. Thanks so much!

**Comment by JesseLeeBusch** [comment]
@Mekle001 Actually, I just tried doing the cod stock recipe again, and the moment the delivery person brought the ingredients that could be put in the furnace, the cook snagged them and put them in the furnace.
