### ISSUE TITLE
Problem with builder 

### ISSUE THREAD

**Issue by Charlistic** [ldtteam/minecolonies#5753]
My builder is showing this msg 
![billede](https://user-images.githubusercontent.com/71036327/92637469-27eeae00-f2d9-11ea-905e-c9cc585ca48f.png) 

This is my latest log file. [latest.log](https://github.com/ldtteam/minecolonies/files/5197204/latest.log)

The builder was upgrading the builders hut from lvl 1 to 2. I tried to change his building style, recall him, give him something else to do, nothing of it worked. It looked shortly like the changing of his building style worked but under 5 min later he came with the same msg again.
[latest.log](https://github.com/ldtteam/minecolonies/files/5197204/latest.log)

**Comment by Charlistic** [comment]
Im playing with the Valhelsia 3 - 1.16 modpack version 3.0.15 on a server

**Comment by ravenbuilder934** [comment]
The server needs to update its Structurize and MineColonies versions. (By the way, next time please fill out the entire template.)
