### ISSUE TITLE
Bug with Courier's IA

### ISSUE THREAD

**Issue by tchumat** [ldtteam/minecolonies#5754]
![U5saIzi](https://user-images.githubusercontent.com/71040313/92646308-9c672400-f2bc-11ea-94c2-1200adfe7a1e.png)
[latest.log](https://github.com/ldtteam/minecolonies/files/5197677/latest.log)

**Comment by ravenbuilder934** [comment]
Please fill out the entire template. It has information we need to troubleshoot.
