### ISSUE TITLE
Lag and/or crash

### ISSUE THREAD

**Issue by y2kansas** [ldtteam/minecolonies#5755]
Since upgrading to Minecraft 1.16.2 (and upgrading relevant mods including the latest releases of Minecolonies and Structurize) I have had an issue with severe lag and /or crashing. This problem did not happen in the previous version of Minecraft. The problem is intermittent, sometimes letting me play for a few minutes before it happens, but most times it crashes while loading a saved world. The log I am including is the latest, but it seems that every time it crashes it mentions a different NPC. Whether that actually has anything to do with the crash or not, I am unsure.

[crash-2020-07-13_00.08.48-server.txt](https://github.com/ldtteam/minecolonies/files/5197709/crash-2020-07-13_00.08.48-server.txt)

**Comment by ravenbuilder934** [comment]
Use the latest _alphas_ of MineColonies and Structurize instead of the releases (alphas aren't unstable, they're just minor releases here). Also, please fill out the entire template next time.

**Comment by Nightenom** [comment]
IO issue when reading your configs, check your hdd/ssd health, may help to backup configs and delete them so they can recreate from scratch

**Comment by Raycoms** [comment]
Also the next time please fill in the entire template
