### ISSUE TITLE
Accidentally right clicked a rack with the build tool, crashed my game.

### ISSUE THREAD

**Issue by PortalsCoolToo** [ldtteam/minecolonies#5758]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- MineColonies Version: 0.13.215-ALPHA
- Structurize Version: 0.13.64-ALPHA
- Related Mods and their Versions:

## Expected behavior
Only one or the other was used, like, y'know.... the rack opened OR the build menu showed up.

## Actual behavior
Minecraft couldn't decide and defaulted to it's always magical third option, and crashed.

## Steps to reproduce the issue!

1.  Hold the build tool.
2. Right click any block that opens or does something apon right clicking it. I'm chests and racks and all that are going to do the same thing.
3. Crash your game.

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by PortalsCoolToo** [comment]
Oops sorry I didn't see Minecraft version pop up. I'm running 1.15.

**Comment by Raycoms** [comment]
crash report?

**Comment by PortalsCoolToo** [comment]
Oh... I just tried to replicate it and it didn't happen. I'm not sure why... and I'm not sure weather I should close this now... bc it still happened.
