### ISSUE TITLE
Stone smelter can't make charcoal and use charcoal as fuel

### ISSUE THREAD

**Issue by MatthiasMann** [ldtteam/minecolonies#5759]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: minecolonies-0.13.244-ALPHA-universal
- Structurize Version: structurize-0.13.64-ALPHA
- Related Mods and their Versions:

## Expected behavior
Being able to setup charcoal as the stone smelter's fuel, and have him able to 'craft' charcoal by 'smelting' logs.

## Actual behavior
The stone smelter requests 'Fuel' with a black square as an icon and won't accept charcoal as fuel - the fulfill button on the request page is also not shown.

## Steps to reproduce the issue
1. Setup charcoal as a stone smelter fuel
2. Setup a crafting recipe of oak logs -> charcoal
3. Setup a minimum stock of charcoal in the warehouse
4. Try to give him charcoal as fuel

### Logs
Can provide logs if needed.

### Notes
This was working in minecolonies-0.13.237-ALPHA-universal where I made the setup - after I update to 0.13.244 today the stone smelter stopped working.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Oh wait, this is right. The worker cannot use charcoal to produce charcoal. this is correct and intended. you need multiple fuel types then.

**Comment by MatthiasMann** [comment]
Can I set a preference to charcoal somehow?

**Comment by Raycoms** [comment]
the first one you "click on" has preference

**Comment by Shados** [comment]
I've run into this as well, and I'm pretty confused. Why is using charcoal to create charcoal disabled? Is this deliberate limitation actually *documented* anywhere...?

**Comment by Raycoms** [comment]
It's just difficult to handle this logically in the code.

**Comment by Kaju-Bubanja** [comment]
This would be a great addition

**Comment by uecasm** [comment]
It's not really sensible.  A request would only be queued if you didn't have enough charcoal, which means you have to produce charcoal using the charcoal you don't have, and everything would deadlock.  Just use a different fuel type, possibly in a separate stone smeltery.

**Comment by Kaju-Bubanja** [comment]
I mean you could implement it such, that you can define a base stack of charcoal that the smelter should keep for himself as fuel. When somebody requests charchoal he uses his to make more. If he falls below he uses his stack to smelt until he has the minimum again.

**Comment by uecasm** [comment]
That's my point though: now you're introducing special cases and extra UI and functionality for a corner case that can more easily be solved by just avoiding that particular setup.  It's not hard to just build an extra building to take care of those requests using a different fuel.

In any case, this (an already-closed issue from years ago) is not the correct place for discussion on the topic; if you want to discuss this further, then please do so in the appropriate Discord channel.
