### ISSUE TITLE
Delivery problem - too many shovels.

### ISSUE THREAD

**Issue by ProsperCraft** [ldtteam/minecolonies#576]
### Minecolonies version

minecolonies-universal-1.10.2-0.6.2724

### Expected behavior

Deliver one shovel

### Actual behaviour

Filled the buidlersentire chest with shovels.
https://gyazo.com/259b28b678b05ad98635a9623b530bdf

**Comment by Raycoms** [comment]
The buider was level 1 only?

**Comment by ProsperCraft** [comment]
Hut level 2 worker level 4
Hut level 2 worker level 3

**Comment by Raycoms** [comment]
Guessed that. Worker continued requesting because he never received the
right one, will have work on that.

2017-02-10 17:51 GMT-02:00 ProsperCraft <notifications@github.com>:

**Comment by Raycoms** [comment]
Is someone able to reproduce this?

**Comment by marchermans** [comment]
As per request I started merging Issues that are related to things I found while going through the source code. One of these is the request system. Closing this in favor of #638
