### ISSUE TITLE
Delivery Man just stops

### ISSUE THREAD

**Issue by PortalsCoolToo** [ldtteam/minecolonies#5760]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.215-ALPHA
- Structurize Version: 0.13.64-ALPHA
- Related Mods and their Versions:

## Expected behavior
Delivery Man does literally anything other than stand in the warehouse and sleep

## Actual behavior
He just stands in the warehouse and sleeps. He has jobs and I tried recalling him a few times, restarting him, and giving him a new job. He goes and does it, but then he returns to the same spot in the warehouse. 

## Steps to reproduce the issue

1. No
2. Clue

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Did you try running /mc colony requestsystem-reset (your colony ID here)?

**Comment by PortalsCoolToo** [comment]
I have now tried that, but it wouldn't allow me to do it and said I had to change the config. Then i went to the main menu and found Mine Colonies and the config button is dark and i can't click it.

**Comment by ravenbuilder934** [comment]
In 1.14+ you need to go to the file to change the config. Go to your instance folder, then the config folder, then minecolonies-common.toml and edit that.

**Comment by Raycoms** [comment]
It's normal for the dman to stand there, if he has nothing to do.

**Comment by PortalsCoolToo** [comment]
No he has a full list of things.

**Comment by Raycoms** [comment]
any AI error in the log?

**Comment by Raycoms** [comment]
Can you try the latest alpha?

**Comment by PortalsCoolToo** [comment]
Am I not on the latest? I thought I updated with the last announcement. (I'm looking through the config right now)

**Comment by Raycoms** [comment]
We're on 247, so just 30 versions behind =P

**Comment by PortalsCoolToo** [comment]
I could swear I just.... alright. I'll have to work on this later, I have more... school

**Comment by PortalsCoolToo** [comment]
Oh that's odd. It worked for now... thanks. Now I'm off to create a suggestion.... wEEEEEEEEEEEEEEE
