### ISSUE TITLE
Builder stops working on Upgrade to builder level 2 and says KI-Error

### ISSUE THREAD

**Issue by lenne98** [ldtteam/minecolonies#5761]
I started the Upgrade from Builder to level 2 and my Builder says, that she has an KI-error.
Maybe its just coincidence, but it appeared after starting this and keeps continuous appearing.
The Builder keeps building other Buildings but does not upgrade the Builder.
[log.txt](https://github.com/ldtteam/minecolonies/files/5207993/log.txt)

**Comment by Raycoms** [comment]
Please fill in the template completely first
