### ISSUE TITLE
'Ticking Entity' dedicated server crashing

### ISSUE THREAD

**Issue by nanonestor** [ldtteam/minecolonies#5764]
### Prerequisites 

- [ x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2 (Forge 31.2.36)
- MineColonies Version: minecolonies-0.13.247-ALPHA-universal
- Structurize Version:structurize-0.13.64-ALPHA

## Problem description

Dedicated server - world loads, upon client join attempt server crashes with 'ticking entity' errors.

### Notes or related things

'Latest' log:
https://pastebin.com/gz5ZCczK

'Crash Report'
https://pastebin.com/A2WgaPjM

---------------------------
Some more interested crash logging when I attempt to revert to my previous working server setup with MC 0.13.245
'Latest' log:
https://pastebin.com/5i3fM08B (1/2)
https://pastebin.com/r4XP4cYE (2/2)

'Crash Report'
https://pastebin.com/ydxfxQK5

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
should be fixed in the latest
