### ISSUE TITLE
Plantation Problem - Floating Crops

### ISSUE THREAD

**Issue by CirusOmega** [ldtteam/minecolonies#5765]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.247-ALPHA
- Structurize Version: 0.13.64-ALPHA

## Problem description

The plantation worker plants the sugar cane, bamboo, and cactus one block above the sand so it is floating in the air.
### Notes or related things

It might only be the Asian Style Plantation that does it. Tested Acacia and they planted it on the sand.
---
![2020-09-12_03 51 26](https://user-images.githubusercontent.com/42567264/92991698-54f2ba80-f4ab-11ea-8aec-398c9c7501dc.png)

## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
#5006 then the wrong block was tagge din this style
