### ISSUE TITLE
Guard Death message

### ISSUE THREAD

**Issue by Pelemesh** [ldtteam/minecolonies#5766]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16
- MineColonies Version: 0.13.238
- Structurize Version: 0.13.65
- Related Mods and their Versions:

## Expected behavior

Wanted to see death message from guard on a server

## Actual behavior

Hit a patrolling guard and let him kill me, this message was shown in the chat (one of guards name)
https://gyazo.com/3f54639029ada7dc9110708fa884fe20

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Lughbaloo** [comment]
Same issue over on my server. Instead of guards though, this was reproduced with visitor citizens. 
Counts as a server message too, so it got output into my discord relay. That's how I identified it.
![image](https://user-images.githubusercontent.com/44557173/93576167-9205f380-f968-11ea-94bb-4445ad6b4824.png)

**Comment by Raycoms** [comment]
This works fine for me, what is your language setting?

**Comment by Raycoms** [comment]
This is a problem with the translation. You can help with those at translate.minecolonies.com
