### ISSUE TITLE
Error during the common_setup event phase

### ISSUE THREAD

**Issue by kalaposelemer** [ldtteam/minecolonies#5767]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.81
- Structurize Version: 0.13.58

## Problem description

After launching Minecraft, before getting to the main menu, it tells me that an error has occurred during loading and lists the following lines:
Minecolonies (minecolonies) encountered an error during the common_setup event phase
tried to access field com.ltdteam.structurize.util.StructureLoadingUtils.originFolders from class com.minecolonies.coremod.MineColonies
### Notes or related things

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Your MineColonies and Structurize versions are very old. Please update to the latest alphas for each.

**Comment by kalaposelemer** [comment]
They are the latest releases for Minecraft 1.15.2 on Curse Forge

**Comment by ravenbuilder934** [comment]
Please use the latest _alphas._ Here, alphas aren't unstable, they're just minor releases.

**Comment by kalaposelemer** [comment]
I didn't realize the alphas are on the right side and not among the releases in the files section. Using the proper versions, my problem is solved. Thank you very much!
