### ISSUE TITLE
University - missing resources

### ISSUE THREAD

**Issue by GauthierDupr** [ldtteam/minecolonies#5769]
Hi,
so i'm playing on a private server with some friends, we're playing on Valhesia 2 modpack and just started using minecolony.
We just got a bug  and can't make research with university
![image](https://user-images.githubusercontent.com/56693574/93005573-883c5480-f552-11ea-8653-bf16d2b5bca3.png)
as you can see on screenshot there are "missing ressources" but we placed like 64 carrots or/and potato in university inventory and it still say that there is missing ressources.

can anyone help ?

**Comment by Raycoms** [comment]
you need them in your inventory not in the building inventory

**Comment by GauthierDupr** [comment]
> you need them in your inventory not in the building inventory


oh ok thank you
