### ISSUE TITLE
Builder is refusing Grass

### ISSUE THREAD

**Issue by AnthonyKwon** [ldtteam/minecolonies#577]
### Minecolonies version

MineColonies TestPack 0.6.3 (MineColonies 1.10.2-0.6.2724)

### Expected behavior

- Places block on both Dirt and Grass

### Actual behaviour

- Breaks Grass and replace it into Dirt

**Comment by nojo121** [comment]
This has to do with the Building model.
The builder first breaks every block that is in the way of the new building.
He places the dirt so that if there's a hole the dirt will close it.
Otherwise it could happen, that a building won't have a floor.
