### ISSUE TITLE
Medieval Birch Buildings Go Outside of Marked Boundaries

### ISSUE THREAD

**Issue by Typhonidite** [ldtteam/minecolonies#5774]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.12.2
- MineColonies Version: 1.12.2-0.10.259-RELEASE
- Structurize Version: 1.12.2-0.10.79-ALPHA
- Related Mods and their Versions: None

## Expected behavior
For builders to build medieval birch structures only inside the boundary construction fences of the building.

## Actual behavior
Builders break boundary fences and build outside of boundaries.

https://cdn.discordapp.com/attachments/628242282646208538/754733760108298250/2020-09-13_11.00.15.png
https://cdn.discordapp.com/attachments/628242282646208538/754733741976584232/2020-09-13_11.00.23.png

## Steps to reproduce the issue

1. Create a colony
2. Have a builder create a medieval birch themed structure
3. Results

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
1.12 is not supported anymore. Sorry
