### ISSUE TITLE
Can't interact with settlers

### ISSUE THREAD

**Issue by Daffur** [ldtteam/minecolonies#5777]
I am using the latest version (minecolonies 0.13.249 alpha universal) of minecolony and struct from 1.16.2, and I am presented with the problem that

**Comment by Raycoms** [comment]
Use template, remove optifine

**Comment by Daffur** [comment]
I remove the optifine to test if that is the problem, although in 1.5.2 I
have the optifine and it does not happen to me, however, will they fix that
error? Thanks for answering. I will try to remove the optifine.
