### ISSUE TITLE
guard tower: this block is missing its respective building

### ISSUE THREAD

**Issue by assasin1123** [ldtteam/minecolonies#5778]
- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.16.2
- MineColonies Version:0.13.220
- Structurize Version:0.13.66
- Related Mods and their Versions:

## Expected behavior
Use guard tower

## Actual behavior
can't interact with blok. error:this block is missing its respective building

## Steps to reproduce the issue

place guard tower blok and richt-click on it
(builder, town-hall, colonists, etc. are available)

1.  place guard tower 
2.  right-click on block

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
update forge
