### ISSUE TITLE
Wall segments orientation issues

### ISSUE THREAD

**Issue by thekrugers** [ldtteam/minecolonies#5779]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.81-RELEASE
- Structurize Version: 0.13.31.RELEASE
- Related Mods and their Versions: N/A

## Expected behavior
Wall segments built in selected orientation and remaining in that orientation when upgraded.

## Actual behavior
Note: I will NOT run the Alpha version, I had to abandon a world because the alpha code is so broken I had to keep resetting the builder to get anything done.

Upgrading a wallsegment1 structure to wallsegment2 rotates the structure by 90 degrees.

Blocks from the old wallsegment1 build that fall outside the new incorrect orientation are left in place, making a mess. Which means it isn't all that great to just build all your wall segments at the incorrect orientation and let them get turned around at upgrade time.

## Steps to reproduce the issue

1. Using the Building Tool, place a wallsegment1
2. Wait for the builder to complete the build
3. Right-click the control block for the wall segment and click Upgrade
4. Watch the builder build the upgraded wall segment with the orientation rotated 90 degrees around the control block

### Logs

- latest.log: 
- crashlog: 

### Notes
I really thought this was fixed back in 0.11, I seem to recall this issue being reported back then and someone replying that it was fixed.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
#5006 please report here

**Comment by ravenbuilder934** [comment]
Also, please open an issue for the bug you experienced with the alpha version-it works for me.

**Comment by Raycoms** [comment]
Might've randomly picked a bad alpha (we have those in 1/100)
