### ISSUE TITLE
Issue with Builder

### ISSUE THREAD

**Issue by Solarius66** [ldtteam/minecolonies#5782]
[latest.log](https://github.com/ldtteam/minecolonies/files/5220376/latest.log)
"My AI has run into an issue [...] send it to the minecolonies authors with this message".

Hi, I play on a Valhelsia 2 server with 10 peoples, and this appear sometimes, on different buildings (this time on Town Hall 3, but also occured on PlayerHouse 2).
Hope you can fix it soon, have a nice day :)

**Comment by ravenbuilder934** [comment]
Please update to the latest alphas of MineColonies and Structurize.
