### ISSUE TITLE
Tavern Visitors Randomly falling out of the world

### ISSUE THREAD

**Issue by Fluffyfou** [ldtteam/minecolonies#5783]
### Prerequisites 

- [X ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.2
- MineColonies Version: 0.13.239-ALPHA
- Structurize Version: 0.13.66 Alpha

## Problem description

Seemingly at random, a message saying "X Visitor died from outOfWorld at X=0, Y=-182, X=0 and word spreads around that your Tavern is a dangerous place. You are likely to see less visitors in the future!" appears at chat box, which is impossible since my colony is around -1004, 64, 1704 in a Giant Tree Taiga biome; as the following screenshot shows(link below the text) ; doesn't seem to affect visitors either, my guess is they die instead of despawning. 

https://cdn.discordapp.com/attachments/741531022872674314/755459968102301736/javaw_wCDeFPw66W.png

### Notes or related things

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
this should be fixed in the newest version

**Comment by Raycoms** [comment]
Please reopen if not (might have only be set to 1.16.3)
