### ISSUE TITLE
New clipboard feature doesn't work

### ISSUE THREAD

**Issue by ravenbuilder934** [ldtteam/minecolonies#5784]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: MineColonies Official modpack
- Structurize Version: MineColonies Official modpack
- Related Mods and their Versions: none

## Expected behavior
The new clipboard feature would, when clicked, remove unimportant requests from your view, like the smelter requesting ore.

## Actual behavior
It removes _all_ requests from the clipboard's view, even ones from builders which are important.

## Steps to reproduce the issue

1. Craft a clipboard
2. Have a builder request something
3. Use the new feature

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Actually, I just discovered that it only shows requests made by the request system itself.

**Comment by ravenbuilder934** [comment]
...Wait, now one of my builder's requests also shows up. I think I got it-that request is what they need _right now,_ right?

**Comment by Raycoms** [comment]
yes

**Comment by Raycoms** [comment]
the "right now"= important, the rest = the other ones you can trigger between
