### ISSUE TITLE
Ownership of the currently built building no longer belongs to the colony.

### ISSUE THREAD

**Issue by Sogang123** [ldtteam/minecolonies#5787]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.2
- MineColonies Version: 1.16.2
- Structurize Version: 1.16.2
- Related Mods and their Versions: minecolonies-0.13.249-ALPHA-universal.jar

## Expected behavior

i have access rights.

## Actual behavior

Over time, the access rights disappear.

## Steps to reproduce the issue

1, Built a building.
2, Ownership is in the colony.
3, Over time, you will lose access to the building.

### Logs

- latest.log: https://cafe.naver.com/44throyalengineers/15649
- crashlog: https://cafe.naver.com/44throyalengineers/15649

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Can you consistently reproduce this or did this happen when you placed a building and restarted/crashed shortly after?
