### ISSUE TITLE
Builder Medieval Spruce Blacksmith Level 3 item need causing crash of client

### ISSUE THREAD

**Issue by Bidgam** [ldtteam/minecolonies#5789]
- Minecraft Version: 1.16.1
- MineColonies Version: minecolonies-0.13.154-ALPHA-universal
- Structurize Version: structurize-0.13.44-ALPHA
- Related Mods and their Versions: Valhelsia 3 3.0.13

Client crashes upon viewing the builder needs list either in the clipboard or directly from the builder. Causes a -0 java error.

## Steps to reproduce the issue

1. Request Level 3 build of Medieval Spruce Blacksmith
2. Wait until they are nearly finished, as it seems to crash with one of the final items (the flint and steel or something

Final items seem to be:

- Flint and Steel
- Torch
- Anvil
- Item Frame

Couldn't find local client crash log specifics.

100% reproducible on my client.

**Comment by ravenbuilder934** [comment]
Try updating your MineColonies and Structurize versions.

**Comment by Raycoms** [comment]
yes, this was fixed in a later version

**Comment by Bidgam** [comment]
My apologies, will do.
