### ISSUE TITLE
My miner doesn't work. Problem with his IA

### ISSUE THREAD

**Issue by charlot97** [ldtteam/minecolonies#5791]
[latest.log](https://github.com/ldtteam/minecolonies/files/5240278/latest.log)
When I start playing the miner starts to work, but after a while I get the message that there is a problem with his IA and to check the latest.log file.
I would like to have a solution so I can keep playing.

**Comment by ravenbuilder934** [comment]
Please fill out the entire template. It has needed information for us to troubleshoot.

**Comment by Raycoms** [comment]
as well as logs

**Comment by charlot97** [comment]
> [latest.log](https://github.com/ldtteam/minecolonies/files/5240278/latest.log)
> When I start playing the miner starts to work, but after a while I get the message that there is a problem with his IA and to check the latest.log file.
> I would like to have a solution so I can keep playing.

**Comment by ravenbuilder934** [comment]
What version are you running? We need more information than just the log.

**Comment by charlot97** [comment]
> What version are you running? We need more information than just the log.

Minecraft 1.15.2 version

- minecolonies-0.13.81-RELEASE-universal
- structurize-0.13.8-ALPHA
- jei-1.15.2-6.0.2.11

**Comment by Raycoms** [comment]
Super old version, update

**Comment by charlot97** [comment]
> Super old version, update

What version should I get?

Thanks!

**Comment by ravenbuilder934** [comment]
The latest alphas of MineColonies and Structurize
