### ISSUE TITLE
My miner doesn't work

### ISSUE THREAD

**Issue by charlot97** [ldtteam/minecolonies#5792]
**Prerequisites**
 I am running the latest alpha version of MineColonies and Structurize for my Minecraft version.
 I checked the MineColonies/Structurize wiki and made sure my issue is not covered there.
 I made sure that this issue is not a duplicate of any existing issue.

**Context**
Minecraft Version: 1.15.2
MineColonies Version: 1.15.2
Structurize Version: 1.15.2
Related Mods and their Versions: 

- minecolonies-0.13.81-RELEASE-universal
- structurize-0.13.8-ALPHA
- jei-1.15.2-6.0.2.11

**Actual behavior**
When I start playing the miner starts to work, but after a while I get the message that there is a problem with his IA and to check the latest.log file.

**Steps to reproduce the issue**
1, Built a mine.
2, Upgrade mine to level 2.
3, After a while, he stops working and stand next to the mine with the message "My AI has run into an issue".

**Logs**

[latest.log](https://github.com/ldtteam/minecolonies/files/5240308/latest.log)

**Comment by ravenbuilder934** [comment]
Again, please fill out the entire template. We need more information than just the log.

**Comment by charlot97** [comment]
> Again, please fill out the entire template. We need more information than just the log.

Sorry, I'm new and I don't know how this works
