### ISSUE TITLE
Cannot log into server near friends colony: Payload may not be larger than 1038576 bytes

### ISSUE THREAD

**Issue by TTVKazhang** [ldtteam/minecolonies#5793]
- [] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

- Minecraft Version: 1.16
- MineColonies Version:  0.13.22-ALPHA-universal
- Structurize Version: 0.13.63-ALPHA
- Related Mods and their Versions: Valhelsia 3

## Expected behavior
Mod to function - able to load in.

## Actual behavior
Crashes as soon as the block in question becomes loaded. 

## Steps to reproduce the issue

1. Log into server
2. Go anywhere near the colony that would load it in
3. Everyone on server gets kicked

### Logs

- latest.log: https://gist.github.com/TTVKazhang/fedeb7944c850a9646beca7fb47fbd91
- crashlog: N/A

### Notes
The server console talks about memory overflow (Under latest.log gist) at a certain block placement, that block is a minecolonies postbox. So as soon as that is loaded in, the server doesn't crash, but every player gets kicked off. 

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
updated to newest: then run /mc colony requestsystem-reset-all
