### ISSUE TITLE
Builders not building unless manually restart them

### ISSUE THREAD

**Issue by ItsErisGaming** [ldtteam/minecolonies#5795]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.260-ALPHA
- Structurize Version: 0.13.64-ALPHA
- Related Mods and their Versions:

## Expected behavior
 Builders will build their own huts and other buildings as like the other previous versions

## Actual behavior
 Builders not building at first try. It stucks on [LOAD_SCHEMATIC] unless you restart them manually

 I might do it later on due to slow internet and have schedule limited on using computer

## Steps to reproduce the issue

1. Place Builder's hut
2. Let the builder build his/her own hut and wait for seconds
3. Then it won't build unless manually restart. (I use Dev mode for it tho. It's still an issue on non-dev mode)

### Logs

- latest.log: 
- crashlog: 

### Notes

Note: I don't know if it's the issue of Structurize or Minecolonies itself. I only have few mods like MrCrayFish's Vehicles and Guns
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ItsErisGaming** [comment]
![2020-09-19_07 48 34](https://user-images.githubusercontent.com/46648706/93656858-39198680-fa60-11ea-97a8-45451f7382fa.png)
![2020-09-19_07 42 35](https://user-images.githubusercontent.com/46648706/93656861-420a5800-fa60-11ea-95bd-d96a34117252.png)
![2020-09-19_07 42 49](https://user-images.githubusercontent.com/46648706/93656869-4c2c5680-fa60-11ea-8ad0-ad68de92192c.png)
![2020-09-19_07 43 37](https://user-images.githubusercontent.com/46648706/93656875-5bab9f80-fa60-11ea-8c1d-9a3029a7f13a.png)
![2020-09-19_07 43 55](https://user-images.githubusercontent.com/46648706/93656881-649c7100-fa60-11ea-8728-dbc09dd84edc.png)
![2020-09-19_07 43 57](https://user-images.githubusercontent.com/46648706/93656885-682ff800-fa60-11ea-85ce-742861ea4601.png)
![2020-09-19_07 44 03](https://user-images.githubusercontent.com/46648706/93656889-6d8d4280-fa60-11ea-8014-687b2dc36eda.png)
![Uploading 2020-09-19_07.46.49.png…]()

**Comment by Raycoms** [comment]
How long are you actually waiting? when you got a slow computer, there might be 5 minutes loading time until the builder calculated all necessary materials.

**Comment by ItsErisGaming** [comment]
10 Minutes. And here's my PC Specs

AMD A6-7480K
4GB RAM DDR3 (3.5GB of it allocated to Minecraft)
Radeon R5 Graphics
500 GB HDD

**Comment by ItsErisGaming** [comment]
And I am using infinite resources

**Comment by Raycoms** [comment]
Ahhh, infinite resources is more a debug tool, we don't provide support for it, it might not always work as expected. Please try without infinite resources.

**Comment by ItsErisGaming** [comment]
I already did it like 3 hours ago and still persists

**Comment by ItsErisGaming** [comment]
I have no problems with builders at the release version of Minecolonies with infinite resources but they disappear when I reload the same world

**Comment by ItsErisGaming** [comment]
Nevermind, it works because me being hating farming resources. I will try re-enable infinite resources to see if it's fixed

**Comment by ItsErisGaming** [comment]
It didn't fixed tho. Looks I am going to do it the hard way. Can you guys fix it on next update? Imma close this issue due to my problem is solved
