### ISSUE TITLE
If I try to build the dark oak town hall, it keeps telling me that the block is too high.

### ISSUE THREAD

**Issue by HannahJ2000** [ldtteam/minecolonies#5796]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.2
- MineColonies Version: 1.16 Alpha 0.13.263 universal
- Structurize Version: 1.16 Alpha 0.13.67 

## Problem description

Every time I try to build the dark oak town hall at the height that it should be it tells me in the chat that the block is too high and it should be below y 256, but the block is below y 256. So I can't build it.
### Notes or related things

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
at which height are you trying to build it'?

**Comment by HannahJ2000** [comment]
I've tried every height from literally sitting on top of the ground to as high as y 242. All were below y 256.

**Comment by Raycoms** [comment]
@lunadragnstar might that buildingn be scanned in too high?

**Comment by HannahJ2000** [comment]
I don't think so.

**Comment by HannahJ2000** [comment]
I've also tried level 1 but it's doing the same thing.

![24008777-3509-4511-A359-C53EB75304B4](https://user-images.githubusercontent.com/67448488/93648268-fad48680-f9cf-11ea-824b-2aa90a195f07.jpeg)
It's also doing it with other buildings like the university.

**Comment by lunadragnstar** [comment]
That is because you are building it at a too high of an altitude in the game. The highest ground level the dark oak townhall can be is at 239, but there are other buildings in the dark oak that are taller. You need to go to a lower Y level to build. To ensure all buildings will build properly, you shouldn't build any hut above Y230 for Dark Oak. (That is the highest ground level they should be on).

**Comment by lunadragnstar** [comment]
The tallest structure in the mod is 57 blocks tall, so to ensure any/all buildings can be placed, they should be below Y198

**Comment by HannahJ2000** [comment]
Alright I will try this really quick.

**Comment by HannahJ2000** [comment]
I tried to do it as low as I could without it being inaccessible to the colonists, but it still didn't work so I just chose a different townhall.

**Comment by HannahJ2000** [comment]
I would still like to use the dark oak townhall in the future though.

**Comment by Raycoms** [comment]
Kk, that is a minecraft limitation then, you're building in such a high biome that the structure doesn't fit.

**Comment by HannahJ2000** [comment]
I did it on super flat.

**Comment by ravenbuilder934** [comment]
Which preset? If I remember correctly, the snowy one is very high.

**Comment by HannahJ2000** [comment]
Oh yeah that was the one. Thanks
