### ISSUE TITLE
Guard Patrol distance

### ISSUE THREAD

**Issue by FaiconX** [ldtteam/minecolonies#5797]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.257-ALPHA
- Structurize Version:  0.13.64-ALPHA
- Related Mods and their Versions: Using the last MineColonies Official modpack version

## Expected behavior

The guards should patrol the entire colony

## Steps to reproduce the issue

1. Build a Barrack and Barracks Tower
2. Try to set manually their patrol route far from the tower, but inside the colony. Or build another building farm from the Tower and set the patrol to automatic

### Logs

- latest.log: 
- crashlog: 

### Notes

There is no mention on the wiki about the patrol range on the guards based on their levels. After reporting on their github they said it might be a bug on the mod. https://github.com/ldtteam/MinecoloniesWiki/issues/439
Sorry for the inconvenience  if this is not a bug.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
There is a max range for patroll points. Even though there is no mention on the wiki for it @ravenbuilder934

**Comment by ravenbuilder934** [comment]
What's the max range?
