### ISSUE TITLE
Minecolonies Crash on Server (Ticking Entity)

### ISSUE THREAD

**Issue by Nouser12** [ldtteam/minecolonies#5798]
Hello there,
So my friends and I wanted to create a new server for us to play with minecolonies and other mods. However, while running good at the beginning, the server crashed, showing the following crash report. We have no idea how to fix that and there seems to be no answer to our problem on the internet (every solution we found didn't work). 

Can anyone help?

Cheers!

---- Minecraft Crash Report ----

WARNING: coremods are present:
  FutureMC (future-mc-1.12.2-0.2.4.0.jar)
  TransformLoader (DynamicSurroundings-1.12.2-3.6.1.0.jar)
  ForgelinPlugin (Forgelin-1.5.1.jar)
  LevelUpCore (levelup2-1.4.2.jar)
  LoadingPlugin (Reskillable-1.12.2-1.10.0.jar)
Contact their authors BEFORE contacting forge

// Why is it breaking :(

Time: 9/18/20 5:49 PM
Description: Ticking entity

java.lang.ClassCastException: com.minecolonies.coremod.entity.citizen.EntityCitizen cannot be cast to net.minecraft.entity.player.EntityPlayerMP
	at com.dmonsters.ai.EntityAITopielecAttack.func_75250_a(EntityAITopielecAttack.java:32)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:94)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2359)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.minecraft.entity.monster.EntityMob.func_70636_d(EntityMob.java:45)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:50)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.dmonsters.ai.EntityAITopielecAttack.func_75250_a(EntityAITopielecAttack.java:32)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:94)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2359)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.minecraft.entity.monster.EntityMob.func_70636_d(EntityMob.java:45)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:50)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)

-- Entity being ticked --
Details:
	Entity Type: dmonsters:topielec (com.dmonsters.entity.EntityTopielec)
	Entity ID: 471
	Entity Name: Topielec
	Entity's Exact location: -1137.50, 62.56, -197.50
	Entity's Block location: World: (-1138,62,-198), Chunk: (at 14,3,10 in -72,-13; contains blocks -1152,0,-208 to -1137,255,-193), Region: (-3,-1; contains chunks -96,-32 to -65,-1, blocks -1536,0,-512 to -1025,255,-1)
	Entity's Momentum: -0.42, 0.03, -0.28
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: TBB_EXP_S07
	All players: 2 total; [EntityPlayerMP['Nouser12'/144, l='TBB_EXP_S07', x=-192.31, y=67.00, z=-325.32], EntityPlayerMP['MuZzLFuZzL'/468, l='TBB_EXP_S07', x=-1152.03, y=64.00, z=-207.15]]
	Chunk stats: ServerChunkCache: 1019 Drop: 0
	Level seed: -6684642155907437731
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-180,64,-168), Chunk: (at 12,4,8 in -12,-11; contains blocks -192,0,-176 to -177,255,-161), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 73326 game time, 103922 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 115146 (now: false), thunder time: 143882 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 5.3.7-301.fc31.x86_64
	Java Version: 1.8.0_265, Red Hat, Inc
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Red Hat, Inc
	Memory: 738255240 bytes (704 MB) / 2163736576 bytes (2063 MB) up to 6681526272 bytes (6372 MB)
	JVM Flags: 2 total; -Xms256M -Xmx7168M
	IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 76 mods loaded, 76 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                      | Version                 | Source                                           | Signature                                |
	|:------ |:----------------------- |:----------------------- |:------------------------------------------------ |:---------------------------------------- |
	| LCHIJA | minecraft               | 1.12.2                  | minecraft.jar                                    | None                                     |
	| LCHIJA | mcp                     | 9.42                    | minecraft.jar                                    | None                                     |
	| LCHIJA | FML                     | 8.0.99.99               | minecraft_server.jar                             | None                                     |
	| LCHIJA | forge                   | 14.23.5.2847            | minecraft_server.jar                             | None                                     |
	| LCHIJA | anvilpatch              | 1.0.0                   | anvilpatch-1.0.0.jar                             | None                                     |
	| LCHIJA | babymobs                | 1.5.5                   | BabyMobs-1.12-1.5.5.jar                          | None                                     |
	| LCHIJA | baubles                 | 1.5.2                   | Baubles-1.12-1.5.2.jar                           | None                                     |
	| LCHIJA | betteragriculture       | 1.2.3                   | betteragriculture-1.12.2-1.2.3.jar               | None                                     |
	| LCHIJA | bettercaves             | 1.12.2                  | bettercaves-1.12.2-2.0.4.jar                     | None                                     |
	| LCHIJA | bettercombatmod         | 1.5.6                   | BetterCombat-1.12.2-1.5.6.jar                    | None                                     |
	| LCHIJA | bettermineshafts        | 1.12.2-2.1.0            | BetterMineshaftsForge-1.12.2-2.1.0.jar           | None                                     |
	| LCHIJA | biomesoplenty           | 7.0.1.2441              | BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar    | None                                     |
	| LCHIJA | guideapi                | 1.12-2.1.8-63           | Guide-API-1.12-2.1.8-63.jar                      | None                                     |
	| LCHIJA | bloodmagic              | 1.12.2-2.4.3-105        | BloodMagic-1.12.2-2.4.3-105.jar                  | None                                     |
	| LCHIJA | blue_skies              | 1.1.3                   | blue_skies-1.12.2-v1.1.3.jar                     | None                                     |
	| LCHIJA | bookshelf               | 2.3.590                 | Bookshelf-1.12.2-2.3.590.jar                     | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | redstoneflux            | 2.1.1                   | RedstoneFlux-1.12-2.1.1.1-universal.jar          | None                                     |
	| LCHIJA | cofhcore                | 4.6.6                   | CoFHCore-1.12.2-4.6.6.1-universal.jar            | None                                     |
	| LCHIJA | boptools                | 0.0.3                   | boptools-1.12-0.0.3.0.jar                        | None                                     |
	| LCHIJA | bountifulbaubles        | 0.0.1                   | Bountiful+Baubles-1.12.2-0.1.6.jar               | None                                     |
	| LCHIJA | comforts                | 1.4.1.3                 | comforts-1.12.2-1.4.1.3.jar                      | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
	| LCHIJA | extendedrenderer        | v1.0                    | coroutil-1.12.1-1.2.37.jar                       | None                                     |
	| LCHIJA | coroutil                | 1.12.1-1.2.37           | coroutil-1.12.1-1.2.37.jar                       | None                                     |
	| LCHIJA | configmod               | v1.0                    | coroutil-1.12.1-1.2.37.jar                       | None                                     |
	| LCHIJA | darknesslib             | 1.1.0                   | DarknessLib-1.12.2-1.1.0.jar                     | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| LCHIJA | dmonsters               | 1.7                     | Deadly+Monsters+1.71.jar                         | None                                     |
	| LCHIJA | deadlyworld             | 1.0.0_for_mc1.12.2      | deadlyworld-1.0.0_for_mc1.12.2.jar               | None                                     |
	| LCHIJA | death_compass           | 0.0.3                   | DeathCompass-0.0.3.jar                           | None                                     |
	| LCHIJA | doubledoors             | 1.2                     | doubledoors_1.12-1.2.jar                         | None                                     |
	| LCHIJA | orelib                  | 3.6.0.1                 | OreLib-1.12.2-3.6.0.1.jar                        | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA | dsurround               | 3.6.1.0                 | DynamicSurroundings-1.12.2-3.6.1.0.jar           | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA | eerieentities           | 1.0.7                   | EerieEntities-1.12.2-1.0.7.jar                   | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | eplus                   | 5.0.176                 | EnchantingPlus-1.12.2-5.0.176.jar                | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | explorercraft           | 2.2.14                  | Explorercraft-2.2.14.jar                         | None                                     |
	| LCHIJA | falling_tree            | 2.1.0                   | FallingTree-1.12.2-2.1.0+25.jar                  | None                                     |
	| LCHIJA | familiarfauna           | 1.0.11                  | FamiliarFauna-1.12.2-1.0.11.jar                  | None                                     |
	| LCHIJA | farlanders              | 1.0.1                   | farlanders-1.12.2-1.0.1.jar                      | None                                     |
	| LCHIJA | forgelin                | 1.5.1                   | Forgelin-1.5.1.jar                               | None                                     |
	| LCHIJA | futuremc                | 0.2.4                   | future-mc-1.12.2-0.2.4.0.jar                     | None                                     |
	| LCHIJA | goodskeletonsdontstrafe | 1.1.1                   | GoodSkeletonsDontStrafe-v1.1.1-1.12.2.jar        | 12d137bcc36051a1c2c8ea7211cfc1da1c6e9dea |
	| LCHIJA | gravestone              | 1.3.1                   | GraveStone-1.12.2-Graves-1.3.1.jar               | None                                     |
	| LCHIJA | gravestone-extended     | 1.3.5.1                 | GraveStone-1.12.2-Extended-1.3.5.1.jar           | None                                     |
	| LCHIJA | grue                    | 1.8.0                   | Grue-1.12.2-1.8.0.jar                            | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| LCHIJA | hardcorerevival         | 1.2.0                   | HardcoreRevival_1.12.2-1.2.0.jar                 | None                                     |
	| LCHIJA | harvestersnight         | 1.1.0                   | harvestersnight-1.12.2-1.1.0.jar                 | None                                     |
	| LCHIJA | waila                   | 1.8.26                  | Hwyla-1.8.26-B41_1.12.2.jar                      | None                                     |
	| LCHIJA | ichunutil               | 7.2.2                   | iChunUtil-1.12.2-7.2.2.jar                       | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | jei                     | 4.16.1.301              | jei_1.12.2-4.16.1.301.jar                        | None                                     |
	| LCHIJA | jrftl                   | 1.1                     | JRFTL[1.12.2]-1.1.jar                            | None                                     |
	| LCHIJA | levelup2                | ${version}              | levelup2-1.4.2.jar                               | None                                     |
	| LCHIJA | mobends                 | 1.0.0-beta-20.06.20     | MoBends_1.12.2-1.0.0-beta-20.06.20.jar           | None                                     |
	| LCHIJA | roots                   | 1.12.2-3.0.32           | Roots-1.12.2-3.0.32.jar                          | None                                     |
	| LCHIJA | mysticalworld           | 1.12.2-1.9.2            | mysticalworld-1.12.2-1.9.2.jar                   | None                                     |
	| LCHIJA | patchouli               | 1.0-21                  | Patchouli-1.0-21.jar                             | None                                     |
	| LCHIJA | placebo                 | 1.6.0                   | Placebo-1.12.2-1.6.0.jar                         | None                                     |
	| LCHIJA | reskillable             | 1.12.2-GRADLE:BUILD     | Reskillable-1.12.2-1.10.0.jar                    | None                                     |
	| LCHIJA | roguelike               | 1.8.0                   | RoguelikeDungeons-1.12.2-1.8.0.jar               | None                                     |
	| LCHIJA | savemystronghold        | 1.12.2-1.0.0            | savemystronghold-1.12.2-1.0.0.jar                | None                                     |
	| LCHIJA | somanyenchantments      | 0.5.0                   | SoManyEnchantments-0.5.0.jar                     | None                                     |
	| LCHIJA | specialai               | 1.1.0_for_mc1.12.2      | specialai-1.1.0_for_mc1.12.2.jar                 | None                                     |
	| LCHIJA | stellarapi              | 1.12.2-0.4.2.9          | Stellar+API-1.12.2-0.4.2.9.jar                   | None                                     |
	| LCHIJA | stellarsky              | 1.12.2-0.5.2.8          | Stellar+Sky-1.12.2-0.5.2.8.jar                   | None                                     |
	| LCHIJA | stg                     | 1.12.2-1.2.3            | stg-1.12.2-1.2.3.jar                             | None                                     |
	| LCHIJA | torchmaster             | 1.8.4.84                | torchmaster_1.12.2-1.8.4.84.jar                  | 5e9a436b366831c8f54a7e80b015784da69278c6 |
	| LCHIJA | trumpetskeleton         | 1.12-1.0.2.1            | trumpetskeleton-1.12-1.0.2.1.jar                 | None                                     |
	| LCHIJA | waystones               | 4.1.0                   | Waystones_1.12.2-4.1.0.jar                       | None                                     |
	| LCHIJA | weather2                | 1.12.1-2.6.12           | weather2-1.12.1-2.6.12.jar                       | None                                     |
	| LCHIJA | witherskelefix          | 2.6.3                   | WitherSkeletonTweaks-1.12.2-2.6.3.jar            | None                                     |
	| LCHIJA | xpfromharvest           | 1.2.0                   | XPFromHarvest-1.12.2-1.2.0.jar                   | None                                     |
	| LCHIJA | xpbook                  | v1.1.6                  | xptome-1.12.2-v1.1.6.jar                         | None                                     |
	| LCHIJA | structurize             | 1.12.2-0.10.277-RELEASE | structurize-1.12.2-0.10.277-RELEASE.jar          | None                                     |
	| LCHIJA | minecolonies            | 1.12.2-0.11.841-ALPHA   | minecolonies-1.12.2-0.11.841-ALPHA-universal.jar | None                                     |
	| LCHIJA | simpleundergroundbiomes | 1.0.0                   | simpleundergroundbiomes-1.0.0.jar                | None                                     |
	| LCHIJA | ladylib                 | 2.1                     | Ladylib-2.1.jar                                  | None                                     |
	| LCHIJA | lumen                   | 0.4.0                   | lumen-Beta+0.4.1.jar                             | None                                     |
	| LCHIJA | mysticallib             | 1.12.2-1.9.0            | mysticallib-1.12.2-1.9.0.jar                     | None                                     |

	Loaded coremods (and transformers): 
FutureMC (future-mc-1.12.2-0.2.4.0.jar)
  thedarkcolour.futuremc.asm.CoreTransformer
TransformLoader (DynamicSurroundings-1.12.2-3.6.1.0.jar)
  
ForgelinPlugin (Forgelin-1.5.1.jar)
  
LevelUpCore (levelup2-1.4.2.jar)
  
LoadingPlugin (Reskillable-1.12.2-1.10.0.jar)
  codersafterdark.reskillable.base.asm.ClassTransformer
	Profiler Position: N/A (disabled)
	Player Count: 2 / 4; [EntityPlayerMP['Nouser12'/144, l='TBB_EXP_S07', x=-192.31, y=67.00, z=-325.32], EntityPlayerMP['MuZzLFuZzL'/468, l='TBB_EXP_S07', x=-1152.03, y=64.00, z=-207.15]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by ravenbuilder934** [comment]
This looks like Minecraft 1.12.2, which is no longer supported here.

**Comment by someaddons** [comment]
deadlymonsters issue
