### ISSUE TITLE
Lumberjack disappeared [$5 awarded]

### ISSUE THREAD

**Issue by Thanaen** [ldtteam/minecolonies#580]
1.10.12-0.6.2724 Minecolonies version

version X.X.XXXX or curse 7.1.6249.2188 Beta

### Expected behavior

- My lumberjack should be at my colony, working

### Actual behaviour

- The lumberjack doesn't exist any more, but he's still counted as existing, which makes it impossible to recruit another villager

### Steps to reproduce the problem

1. Get a lumberjack
2. Do regular minecraft stuff
3. Look for you lumberjack
4. cry

**Comment by marvin-bitterlich** [comment]
Try the respawn command if that works. Minecraft sometimes does weird things to entities and we are still trying to get around that

**Comment by Thanaen** [comment]
Respawn doesn't work, says there isn't enough space for it to be teleported! Tried on Town hall, and on the lumberjack's hut, both failed.
I also Tried to fire the villager, but the villager doesn't come back either.
Me and Goshen have tried a lot of different ways to make the villager come back, but everything failed :|

**Comment by Raycoms** [comment]
entity of the villager got missing  @colton has to change something back I
guess.

2017-02-12 13:08 GMT-02:00 Thanaen <notifications@github.com>:

**Comment by marvin-bitterlich** [comment]
Thanks @Thanaen for your contribution :)
I guess putting a bounty on this issue is just fair ;)

**Comment by Raycoms** [comment]
I fixed this already with the newest update.

2017-02-13 7:10 GMT-02:00 Marvin Hofmann <notifications@github.com>:
