### ISSUE TITLE
Barrels not producing compost

### ISSUE THREAD

**Issue by ab9rf** [ldtteam/minecolonies#5800]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.2 with Forge 33.0.59
- MineColonies Version: 0.13.263-ALPHA
- Structurize Version: 0.13.66-ALPHA
- Related Mods and their Versions: (multiple mods but none seem relevant to this bug)
## Expected behavior

Barrel should produce compost that can be recovered and used as fertilizer.

## Actual behavior

Barrel does not produce recoverable compost. Filling the barrel with appropriate source materials causes a lid to appear. After about two days in-game time the lid disappears and the barrel appears to be full of compost, but right-clicking on the barrel simply empties it without any compost items being created.

## Steps to reproduce the issue

Place a barrel. Fill barrel. Wait until barrel state updates. Right click barrel. Get nothing.
### Logs

- latest.log: https://gist.github.com/ab9rf/2c2067c519e30e39a6364a1a3482c36e
- crashlog: (none, no crash)

### Notes

This was first experienced in 0.13.239 in a server world. I replicated it in a 0.13.239 single-player creative world and then again in a 0.13.263 single-player creative world.

My understanding is that composting barrels that are making compost are supposed to emit particles. Mine do not. They also appear empty while they're working; I don't know if this is what they're supposed to do or not. (I'm relatively new to Minecolonies.)

There are other behaviors that appear glitchy to me but I'm not an expert on how barrels are supposed to behave so I might simply be using them wrong. (The available documentation on how these are supposed to work is a bit sparse.)

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
I double checked that in the newest version with the newest forge in 1.16.3 and it works nicely. So it must be something else
