### ISSUE TITLE
Game crashes when interacting with minecolony inventories 

### ISSUE THREAD

**Issue by benjamini999** [ldtteam/minecolonies#5805]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.14.4
- MineColonies Version: 0.10.715
- Structurize Version: 0.10.245
- Related Mods and their Versions: N/A

## Expected behavior
Items would move from player inventory into minecolony inventories (Racks, colonists, buildings ect) and vice versa

## Actual behavior
The game crashes when attempting to move the item.

## Steps to reproduce the issue

1. Start a colony
2. Place a building
3. attempt to move items to building inventory from player inventory and vice versa

### Logs

- latest.log: 
- crashlog: <script src="https://gist.github.com/benjamini999/2aec4a7fb08150f94b42fa15df3f0aaf.js"></script>
### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
1.14.4 is not supported anymore.
