### ISSUE TITLE
Fortress Town Hall Not Finishing Due To Tree Grow

### ISSUE THREAD

**Issue by Sargae** [ldtteam/minecolonies#5806]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.1
- MineColonies Version: minecolonies-0.13.238-ALPHA
- Structurize Version: structurize-0.13.65
- Related Mods and their Versions:

## Expected behavior
<!x What would you expect to see if this feature was working as intended? -->
Completed Build

## Actual behavior

Town Hall (Fortress) doesn't finish due to tree growing during build. 

## Steps to reproduce the issue

1.  Place Townhall
2.  Let Dark Oak Tree Build
3.  Builder Doesn't Finish Build

### Logs

- latest.log: No Crash
- crashlog:  No Crash

### Notes

Ive been trying for about 2 days now (real days not MC) to get this builder to finish my fortress townhall and cannot figure out what is going on. I have canceled the build-recalled worker-changed worker-reset the build) and he just stands there and doesn't finish the last 8 trees. Any ideas? btw love the mod so far! The attention to detail is amazing thanks!

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
#5006 please
