### ISSUE TITLE
1.16.3 -> minecolonies-common.toml not created

### ISSUE THREAD

**Issue by DouglasHennrich** [ldtteam/minecolonies#5807]
`minecolonies-0.13.261-ALPHA-universal.jar`

I have created a new instance and put Minecolonies mod inside it.
But when forge loads, it didn't create previously `minecolonies-common.toml` so I can't configure minecolonies.
I'm playing on single player

Minecraft -> 1.16.3
Forge -> 34.0.9

**Comment by Raycoms** [comment]
This is all in the minecolonies-server now

**Comment by DouglasHennrich** [comment]
So how can I config in single player?

**Comment by Raycoms** [comment]
The minecolonies-server exists in the world in singleplayer too

**Comment by DouglasHennrich** [comment]
Where can I find it? I couldn't find it on Curse or website

**Comment by Raycoms** [comment]
It's in your game folder

**Comment by DouglasHennrich** [comment]
Found it, Thanks!
