### ISSUE TITLE
Builder voiding items

### ISSUE THREAD

**Issue by Coji4000** [ldtteam/minecolonies#5808]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.** **-only closed issues**

### Context 

- Minecraft Version: 1.15.2 (modded) forge-31.2.37
- MineColonies Version: minecolonies-0.13.81-RELEASE-universal.jar
- Structurize Version: structurize-0.13.31-RELEASE.jar
- Related Mods and their Versions:  https://docs.google.com/spreadsheets/d/1gmLlAouWQohXnxXVsCyD52yCEa1orkTeXyXvCX46ibw/edit?usp=sharing

## Expected behavior

Give Builder Items, Builder uses those Items to build a building.

## Actual behavior

Give Builder Items (through builder hut page 2), He collects the items and begins heading to construction site only to stop part way and return to the hut requesting items he has already been given. Items no longer exist in racks, builder inventory or hut inventory.

It's sporadic that I couldn't capture images of it. (I'd almost swear my builder knows I'm watching) I have to head out for the night but if I can capture images I will attach them. I don't currently have any screen recording software available.
## Steps to reproduce the issue

1. Create a builders hut (mine is Nordic currently level 4 but this happened at lower levels as well)
2. Create a build task (I've had this happen on multiple buildings/upgrades but my most recent and painful was  building a nordic library level 1)
3. Give the Builder Items through page 2 of the builders hut interface. I gave items in bulk, with the library that's about 40 bookshelves almost a thousand spruce planks etc.
4. The builder heads off as if to start the  task but returns. when he returns the items are missing.

### Logs

- latest.log: https://gist.github.com/Coji4000/26d929db28b86bed993d01a19937a0c4
- crashlog: no crash

### Notes
The latest is attached but doesn't appear to show anything relevant to the issue.
21:17:35 is the timestamp where after my builder lost the items so I switched to creative to re-deposit the items needed rather than farm them up again. In this instance he lost 20 bookshelves, ~700 spruce planks and ~300 spruce slabs.
I am experiencing this on a Dedicated Server located on my LAN. I can say with high confidence that it isn't network latency as I have 0ms ping.
This is hugely sporadic.  I know it's severely difficult to chase issues like these but after losing thousands of spruce to this I had to open something back up. 
I  will continue to try and get screen grabs of this happening and provide them once they are available.
Outside of library mods the only mods that (with my limited knowledge) could be interacting with minecolonies is performant.
I will try and spin up a few LAN servers with a more limited mod-list to try and narrow this issue down as much as possible and follow up. any suggestions to test scenarios would be helpful if  you can think of some.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
I'm fairly confident that I can say the first thing anyone will ask you to do is update the mod - you're months and more than a hundred versions behind - I know that this was improved in that time!

**Comment by ShadowProtocol** [comment]
Yes definitely update, this issue was addressed in that time. Use ALPHA versions, as they are not any more or less buggy in the case of MineColonies and Structurize, but rather indicate minor releases. Make sure you can check all of the checkboxes before creating an issue.

**Comment by Coji4000** [comment]
It's the latest RELEASE version and the version twitch installs automatically when choosing to add minecolonies. I'll update.

**Comment by Talyda** [comment]
Change twitch to allow alphas - always use the latest alpha for minecolonies

**Comment by Coji4000** [comment]
I appreciate the comment but I will not be making that adjustment. ALPHA denotes a "not ready to be released" build for most other mods. I will not make a global adjustment for a build naming choice by the minecolonies team. Build names are up to the mod team in all aspects but most mod teams do not recommend alpha builds for stable mod releases. (Not hating just explaining myself)

**Comment by ravenbuilder934** [comment]
You might be able to update individual mods to alphas-I know GDLauncher lets you do that, not sure about Twitch.

**Comment by Coji4000** [comment]
Twitch does let you, I am also familiar with pulling the mod and applying it without a launcher. Thanks everyone for all your help and suggestions I truly appreciate it. I'm getting everything up to latest alpha  today. have a few clients that need hand holding.
