### ISSUE TITLE
Miners get killed too easily

### ISSUE THREAD

**Issue by bugSandwich** [ldtteam/minecolonies#5809]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version:0.13.250 (B)
- Structurize Version: 0.13.64. (A)
- Related Mods and their Versions:

## Expected behavior
The miner survives a reasonable length of time in the mines or at least lights the mine well enough to not allow for large dark areas.

## Actual behavior
The miner will often create large dark areas, often due to having to leave to go sleep before completing them, then be immediately killed in the morning (although this can also happen at any time) by some hostile mob, very often a skeleton. This happens often enough that miners will often die far more regularly than guards and almost never last more than 10 days in the mines. This is especially a problem in deeper mines where guards take longer to arrive to help the miner.

## Steps to reproduce the issue

1. Build a mine
2. Hire a miner
3. Await imminent mourning

## Notes

 Perhaps the miner could receive bonus health, 
immunity to projectiles, reduced damage from mobs, or have some early-ish research that allows them to better survive encounters with hostile mobs. The miner currently dies far too frequently.

## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
a) Research the fire resistancy
b) Station a guard on the level the miner works
