### ISSUE TITLE
Citizens duping, Getting killed, and Their dupe just... sits there

### ISSUE THREAD

**Issue by ghost** [ldtteam/minecolonies#5812]
I'm using minecolonies on its 1.12.2 version in a technic modpack called the Yao pack. Recently I made a colony and began to get some builders doing tasks, since it was a undefended area they died a couple of times ad new ones would take their place. Before each one of these builders died they duplicated themselves beside their hut block and I can't kill this extra npc or interect with it at all, when I use commands to kill the npc it tells me that they aren't even there

**Comment by ShadowProtocol** [comment]
Sorry, Minecraft 1.12 is no longer supported. The 1.12 version of MineColonies is significantly behind in features and will contain unresolved bugs.
