### ISSUE TITLE
can't delete colony

### ISSUE THREAD

**Issue by Drakemilember** [ldtteam/minecolonies#5815]
hi need help i started the colony today and i put the town hall down the the builder but the npc didnt do anything event with all the mats for the building then i tried to delete the colony so i can try again but say my id is not valid but when i look at the colony list my colony is there with the id i used 
here what i used as command : /mc colony delete colony: 1 
and i tried it both as op and directly on the server command console

**Comment by Raycoms** [comment]
Please fill in the template
