### ISSUE TITLE
cant delete colony

### ISSUE THREAD

**Issue by Drakemilember** [ldtteam/minecolonies#5816]
**minecolonies version**
minecolonies-1.12.2-0.10.22-ALPHA-universal.jar

**expected behavior**
Delete colony

**Actual Behavior**
invalid value '1' for required argument colony

**Step to recreate**
1: start a server
2: start a colony
3: remove town hall 
4: try to delete colonie

**Comment by Raycoms** [comment]
Sorry, we don't offer 1.12 support anymore. But the command is /mc colony delete colony: 1
