### ISSUE TITLE
move resipe down button in list of recipes not functioning

### ISSUE THREAD

**Issue by Kai-Tooley** [ldtteam/minecolonies#5818]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.2
- MineColonies Version: 0.13.270-ALPHA
- Structurize Version: 0.13.66
- Related Mods and their Versions:

## Expected behavior

the recipe would move down in the recipe list when the button is pressed

## Actual behavior

nothing happens

## Steps to reproduce the issue

1. add more than one item to a recipies list
2. click the down arrow on the top recipe
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by WenXin20** [comment]
I have also seen this happen in 1.15.2, and if there is 3 or more recipes in the list, and I press the down button, instead the recipe above it is moved up.
I have also noticed that if I want to teach a recipe, there is no way to use tags such as `minecraft:planks`, and if a mod adds a conflicting recipe there is no way to specify the correct output item.
