### ISSUE TITLE
"very big memory imprint"

### ISSUE THREAD

**Issue by piesio98** [ldtteam/minecolonies#5819]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.1
- MineColonies Version: 0.13.258-ALPHA
- Structurize Version: 0.13.65-ALPHA
- Related Mods and their Versions: https://gist.github.com/piesio98/0811e419f2f59401a697fc5ad0fa1499

## Expected behavior
No spam/errors

## Actual behavior

Console spam:

[Server thread/WARN] inecolonies/]: Colony 2 has a very big memory imprint, this could be a memory leak, please contact the mod author!

## Steps to reproduce the issue

When player joins warns starts appearing.

### Logs

- latest.log: https://gist.github.com/piesio98/a9f737646bf421b2282613c6e5ab43cc
- crashlog: no crashlog

### Notes

Error log from minecolonies at line 1048

[24Sep2020 15:41:03.824] [Server thread/WARN] [minecolonies/]: Active Triggered resulted in exception
java.lang.NullPointerException: null

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Update, then run /mc colony requestsystem-reset-all.

**Comment by Raycoms** [comment]
what she said
