### ISSUE TITLE
[Bug] Builder requests planks from sawmill instead of crafting them from logs

### ISSUE THREAD

**Issue by mcmanustfj** [ldtteam/minecolonies#5820]
### Prerequisites 

- [ x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ ]x I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.2
- MineColonies Version: minecolonies-0.13.270-ALPHA
- Structurize Version:structurize-0.13.66-ALPHA

## Expected behavior

When the builder needs oak planks, they request oak logs and craft the planks themselves.

## Actual behavior

The builder requests oak planks from the Sawmill and the sawmill fulfills the request.

## Steps to reproduce the issue

1. Have builder who knows log->plank recipe 
2. Have carpenter who knows log->plank recipe
3. Have builder start a schematic with planks

### Notes

Probably happens to any other 2x2 recipes that a hut has a recipe for.
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Why is this a bug? Seems intentional to me.

**Comment by Raycoms** [comment]
yeah, sawmill has prio over local crafting.

**Comment by Raycoms** [comment]
That is, at the moment at least, intended.
