### ISSUE TITLE
[Bug] Sawmill crafter breaks sometimes

### ISSUE THREAD

**Issue by mcmanustfj** [ldtteam/minecolonies#5821]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.2
- MineColonies Version: minecolonies-0.13.270-ALPHA
- Structurize Version: structurize-0.13.66-ALPHA

## Expected behavior
Sawmill crafts normally after interruption.

## Actual behavior
When sawmill (and probably every crafter) is interrupted (through pause-restart, loading a game, probably going to bed or getting hit by a monster as well) while working on complex recipes (I've noticed it with Oak Fence, but couldn't reproduce with sticks or planks), they stop working until their inventory is emptied. 

## Steps to reproduce the issue

1. Have sawmill, courier, warehouse
2. Request oak fence
3. Pause and restart worker from sawmill hut block (or save/load, or maybe hit them, or go to sleep, or travel far enough to unload their chunk or pause their AI)
4. See that worker doesn't resume working
5. Empty worker inventory
6. See that worker requests materials and continues working

Sometimes it takes a couple times, when I was trying to reproduce it it only worked the first try by pausing and restarting the worker.  It might depend on the contents of the hut inventory or something else entirely.  

### Notes
Tricky to reproduce, might have some variables I couldn't figure out

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Should be fixed with the newest afaik.
