### ISSUE TITLE
Forester doesn't cut down trees that contain stripped logs

### ISSUE THREAD

**Issue by WenXin20** [ldtteam/minecolonies#5822]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.268-Alpha
- Structurize Version: 0.13.64-Alpha
- [Lord of the Rings](https://www.curseforge.com/minecraft/mc-mods/the-lord-of-the-rings-mod-renewed/) Version:  v2.1.3

## Expected behavior

- For the Forester to cut down trees that contain Stripped Logs or Wood blocks.

## Actual behavior

- Currently, the mod Lord of the Rings adds in several trees that contain Wood blocks or Stripped Wood blocks. This includes the Green-Oak, Red-Oak, and Pine trees.
- Since the Forester does not recognize stripped logs or wood as part of the tree, half of the tree is left floating.

## Steps to reproduce the issue

1.  Grow a Red-Oak Sapling
2.  Have a Forester try to cut it down
3.  Half the tree is left floating

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Would this be a https://github.com/ldtteam/minecolonies-features/issues/135 thing?

**Comment by WenXin20** [comment]
I think it could also be replicated with oak trees if you strip a couple of logs in the middle, it probably will only be cut down partially. I haven't tested this yet though.

**Comment by Raycoms** [comment]
Not possible since the connection of stripped logs to normal logs doesn't really exist in code. So it's mod compat yes.
