### ISSUE TITLE
Colony 1 has a very big memory imprint, this could be a memory leak, please contact the mod author!

### ISSUE THREAD

**Issue by georgio3333** [ldtteam/minecolonies#5823]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2 Forge 31.2.20
- Java version : 1.8.0_261
- MineColonies Version: 0.13.81
- Structurize Version: 0.13.31

## Problem description

i 've this message in my server's log "Colony 1 has a very big memory imprint, this could be a memory leak, please contact the mod author!"

### Notes or related things

The server is in local (we are 2 on this), 
it is equipped with 16go of Ram and a ssd.
there are 74 mods

Abnormals-Core-1.15.2-1.0.6                       
AdditionalEnchantedMiner-1.15.2-15.3.1            
aiotbotania-1.15.2-1.2.2                          
AppleSkin-mc1.15.2-forge-1.0.13                   
Aquaculture-1.15.2-2.0.14                         
Atmospheric-1.15.2-v1.3.0                         
AutoRestart-1.15.2-1.1.0                          
bettertridentreturn-1.15.2-1.0.1                  
BonsaiTrees-2.1.2.6                               
Bookshelf-1.15.2-5.5.34                           
Botania-r1.15-385                                 
BotanyPots-1.15.2-2.0.17                          
charginggadgets-1.0.0                             
ChunkNoGoByeBye-1.15.2-1.2.0                      
Clumps-5.0.2                                      
CookingForBlockheads_1.15.2-8.0.2                 
corpse-1.15.2-1.0.6                               
curios-FORGE-1.15.2-2.0.2.4                       
decorative_blocks-6d                              
ditr15-1.8.1                                      
DoggyTalents-1.15.2-1.15.2.3                      
elevatorid-1.15.2-1.7.1                           
FallingTree-1.15.2-2.1.4                          
FastFurnace-1.15.1-3.0.0                          
FastLeafDecay-v22                                 
FastWorkbench-1.15.1-3.0.0                        
FluxNetworks-1.15.2-5.0.3-4                       
FruitTrees-1.15.2-1.4.1                           
ftb-backups-2.1.0.1                               
FunOres-1.15.2-2.5.1+17                           
Hwyla-forge-1.10.8-B72_1.15.2                     
Inventory-Tweaks-Reborn-Mod-1.15.2                
ironchest-1.15.2-10.0.3                           
jei-1.15.2-6.0.0.4                                
journeymap-1.15.2-5.7.0b3                         
Kiwi-1.15.2-2.7.1                                 
LargeFluidTank-15.3.2                             
libnonymous-1.15.2-1.1.1.5                        
mcjtylib-1.15-4.1.4                               
mcw-bridges-1.0.4fix-mc1.15.2                     
mcw-furniture-1.0.1-mc1.15.1 1.15.2               
mcw-roofs-1.0.2-mc1.15.2_1.15.1                   
mcw-windows-1.0.1-mc1.15.2_1.15.1                 
Mine+and+Slash-1.15.2-3.6.14                      
minecolonies-0.13.81-RELEASE-universal            
mining-helmet-1.15.2-1.0.8                        
mininggadgets-1.3.5                               
MixinBootstrap-1.0.3                              
Patchouli-1.15.2-1.2-34                           
PersistentBits-1.15.2-2.0.2                       
phosphor-forge-mc1.15.2-0.5.2+build.4             
Placebo-1.15.2-3.0.2                              
rftoolsbase-1.15-1.1.3-beta                       
rftoolscontrol-1.15-3.0.4-beta                    
ScalableCatsForce-2.13.2-build-2-with-library     
SereneSeasons-1.15.2-3.0.0.72-universal           
serversync-forge-loader-1.1.0                     
SilentLib-1.15.2-4.6.3+55                         
SolarFluxReborn-1.15.2-15.0.0                     
StorageDrawers-1.15.2-7.0.2                       
structurize-0.13.31-RELEASE                       
swingthroughgrass-1.15.2-1.4.0                    
TerraForged-1.15.2-0.0.14                         
The-Endergetic-Expansion-1.15.2-v1.3.1            
themidnight-0.5.9                                 
ToolBelt-1.15.2-1.14.1                            
torchmaster-2.1.1-rc0                             
trash-1.15.2-0.1.4                                
u_team_core-1.15.2-2.12.1.158                     
Upgrade-Aquatic-1.15.2-v1.6.1                     
useful_backpacks-1.15.2-1.9.4.63                  
valhelsia_structures-15.0.3a                      
Waystones_1.15.2-6.0.1                            
xnet-1.15-2.1.7-beta

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

Deliveryman indicates that there is an error with his AI
[2020-09-24-4.log.gz](https://github.com/ldtteam/minecolonies/files/5279025/2020-09-24-4.log.gz)
[debug-5.log.gz](https://github.com/ldtteam/minecolonies/files/5279026/debug-5.log.gz)

**Comment by georgio3333** [comment]
thanks a lot for help

**Comment by Raycoms** [comment]
Update minecolonies. Run /mc colony requestsystem-reset-all
