### ISSUE TITLE
Medieval Oak Gate (decoration) not leveling up

### ISSUE THREAD

**Issue by DangerDr** [ldtteam/minecolonies#5824]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.268-ALPHA
- Structurize Version: 0.13.64-ALPHA.jar
- Related Mods and their Versions:

## Expected behavior

The ability to upgrade the medieval oak gate decoration past level 2

## Actual behavior

Medieval Oak gat stays stuck on its current level.

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by DangerDr** [comment]
So I fixed this issue a MINUTE after posting this *faceplams* - the final path file name had its level it however I haven't been putting the number there so the game is putting the file path in wrong.

**Comment by Raycoms** [comment]
great

**Comment by emiliejirci** [comment]
Hi, I don't really understand the solution and I'm having the same issue. Is there any way someone could clear this up for me?

**Comment by ravenbuilder934** [comment]
Likely this is a different issue, please open a new issue
