### ISSUE TITLE
Builders freezing and repeating "finished building" messages after build is finished

### ISSUE THREAD

**Issue by JasonEpic** [ldtteam/minecolonies#5825]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.260 & 0.13.271 (Tried updating the version to see if it would fix the issue, it did not)
- Structurize Version:
- Related Mods and their Versions:

## Expected behavior

Builders finish the build, the construction tape goes away and the fireworks go up.

## Actual behavior

The builder places the final block to finish the build and i get a message saying the builder finished building x but the construction tape sticks around and the fireworks dont go off, then a few seconds later the builder repeats the "finished building" message. This has happened with both of my builders (in a creative testing world to set up a layout for what I want my colony to look like in my survival world) when building the warehouse, enchanter's tower, and now when upgrading both citizen houses. All of them are in the Asian theme.

![2020-09-24_14 16 13](https://user-images.githubusercontent.com/70909337/94206028-5b087400-fe79-11ea-99d1-e81d9f483290.png)
![2020-09-24_14 16 26](https://user-images.githubusercontent.com/70909337/94206033-5cd23780-fe79-11ea-88b0-ee7da535650b.png)
![2020-09-24_15 00 46](https://user-images.githubusercontent.com/70909337/94206037-5e9bfb00-fe79-11ea-9018-d31f4abd130b.png)
![2020-09-24_15 00 55](https://user-images.githubusercontent.com/70909337/94206040-6065be80-fe79-11ea-9c5e-383df0fdb2cb.png)

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: <script src="https://gist.github.com/JasonEpic/68f49ea7b486f869c3d20e33118ce089.js"></script>
- crashlog: 

### Notes

The only way I could temporarily "fix" the issue is by disabling the construction by clicking on the hut block and clicking "cancel build" and then by resetting my builders by recalling them to their huts and then fireing them and rehireing them so when i right click them they dont display the "My AI has run into an issue" message. But this method would'nt work at all for a survival world rather than a world where I just test layouts of colonies because the builds are technically finished but the base hut block doesnt recognize it as finished so it doesn't funtion like a completed build, and when you try to re-do the build and have the builder finish it (i.e. remove construction tape and launch fireworks) the issue just restarts again where the builder's AI breaks.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
This is the most basic of questions, but did you log out and in again when it happened? Happened to me yesterday on the server, logging fixed it =)

**Comment by JasonEpic** [comment]
Yes i tried that, logging off and on, as well as switching mine colonies versions. Still stuck around

**Comment by LucidDreamer0322** [comment]
This only happens (for me) when a builder tries to finish a task while you have no town hall to report it to. (Was rearranging my town lol)
