### ISSUE TITLE
Fuel menu displays chests inaccurately

### ISSUE THREAD

**Issue by WenXin20** [ldtteam/minecolonies#5829]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.271-Alpha
- Structurize Version: 0.13.64-Alpha

## Expected behavior

- Chests should display correctly

## Actual behavior

- Chests display incorrectly with a white line in the chest

![2020-09-25_23 57 29](https://user-images.githubusercontent.com/12000593/94330585-6a77e200-ff8b-11ea-8c4a-cb2450997d15.png)

## Steps to reproduce the issue

1.  Open fuel menu of a cook or smeltery
2. Search for chests

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Seems to be a mod compat issue then:

![image](https://user-images.githubusercontent.com/6438347/94336582-42fd3580-ffdc-11ea-920a-c1c067631ceb.png)
