### ISSUE TITLE
name tag

### ISSUE THREAD

**Issue by MrIceCreamy** [ldtteam/minecolonies#5832]
Completely new to this website so bare with me but I was playing with some friends on Life in a village and I accidentally sheared a civilian trying to open a door next to him. He then became entity.Citizen.name and I had his name in my hand. I was like oh ill just put it back on him. Nope, it consumed it and hes still stuck as that.

**Comment by Raycoms** [comment]
Yeah, that's a problem with another mod that adds the shearing functionality of names
