### ISSUE TITLE
Stone Smelter requesting "itemless" fuel

### ISSUE THREAD

**Issue by taggianto** [ldtteam/minecolonies#5837]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.272-BETA
- Structurize Version: 0.13.64-ALPHA
- Related Mods and their Versions: N/A

## Expected behavior
Stone smelter uses fuel specified in their hut block to smelt logs into charcoal

## Actual behavior
When teaching the charcoal recipe, it doesn't automatically detect that putting a log in the top slot will result in charcoal - you have to specify that it will (I don't know if this is part of the issue or not). When a request for charcoal is given and the type of fuel specified in the hut block is charcoal, the stonesmelter requests "fuel" but there is no icon of what type of fuel they are requesting. When you enter creative mode and attempt to fulfill the request, nothing happens. Giving the stonesmelter the type of fuel they are supposed to use does nothing.

If you change the type of fuel that the stonesmelter can use (I changed it to sticks) then it will perform expected behavior.

Stone smelter request:
<a href="https://gyazo.com/f2bcf00b4982ab79ae3cf9e31c079e74"><img src="https://i.gyazo.com/f2bcf00b4982ab79ae3cf9e31c079e74.png" alt="Image from Gyazo" width="933"/></a>

Stonesmelter hut block fuel specified:
<a href="https://gyazo.com/ef8aa0663efe9a2213beabdceb1787be"><img src="https://i.gyazo.com/ef8aa0663efe9a2213beabdceb1787be.png" alt="Image from Gyazo" width="574"/></a>

Stonesmelter inventory at time of request:
<a href="https://gyazo.com/77635bc1b686ed1edad8b768c47b91d1"><img src="https://i.gyazo.com/77635bc1b686ed1edad8b768c47b91d1.png" alt="Image from Gyazo" width="596"/></a>

Stonesmelter request as seen on clipboard:
<a href="https://gyazo.com/35ebd43e48f9c9af063da9091846134b"><img src="https://i.gyazo.com/35ebd43e48f9c9af063da9091846134b.png" alt="Image from Gyazo" width="562"/></a>

## Steps to reproduce the issue

1. Build stonesmelter and hire worker
2. Specify the type of fuel to be used as charcoal
3. Teach recipe [log] = [charcoal] (I have tried with both spruce and oak)
4. Wait for citizen to request charcoal (I set it to a minimum requirement in the warehouse block)
5. Couriers will deliver logs
6. Stonesmelter will place logs in the furnace and request "fuel"
7. Nothing happens
8. Add another fuel type in the hut block (I chose sticks) and give that item to the stonesmelter
9. Stonesmelter actually does their job

### Logs

- latest.log: <script src="https://gist.github.com/taggianto/64ca4776a69f7abb5997a05ad17ab33a.js"></script>
- crashlog: N/A

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
you need to turn other things on for charcoal production, yes.
