### ISSUE TITLE
[2829] Miner still on strike [$5]

### ISSUE THREAD

**Issue by kreezxil** [ldtteam/minecolonies#584]
In build 2829, miner still stands at his box not saying or do something. I used the new 

/mc citizens citizenInfo <full name> command to discover he was stuck in a need item task. So I started added all of the tools from wood to diamond for shovels, axes, and pickaxes, still nothing,  then I started giving him mats from oak planks up to torches and cobblestone. He grabbed cobblestone and ladders and went to work. He's still not saying anything in server console or in game chat. But at least you can get him to work if use your Psychic mind reading skills on him.

On the command, can you also make it so that we can access the citizenInfo via citizen ID as well, as typing their full name seems a little unnecessary especially when the list command gives their ids. Keep the full name thing tho.

**Comment by marvin-bitterlich** [comment]
The miner not saying stuff he needs is a long time bug we still have not fixed (and I am honestly clueless xD)

The colony info command should accept ids. It was more a feature to also accept names xD

**Comment by Raycoms** [comment]
Doesn't it work via citizen id? It should work via id.

**Comment by Raycoms** [comment]
Okay it's now only the miner who is quiet or miner and builder?

And is he only quiet about cobble? Or about all blocks, or about all blocks and tools?

**Comment by kreezxil** [comment]
It ignored me when I tried the id 

-----Original Message-----

**Comment by kreezxil** [comment]
About everything I'll have to recheck the builder later

-----Original Message-----

**Comment by Raycoms** [comment]
it's /mc citizens info colonyId citizenId

2017-02-13 13:31 GMT-02:00 kreezxil <notifications@github.com>:

**Comment by kreezxil** [comment]
Ok, that seems a bit much, from the colony owner perspective I did, /mc citizens citizenInfo Nathan T. Inman ... And it worked. Help probably should be more verbose then.

-----Original Message-----

**Comment by Raycoms** [comment]
If it is your own colony /mc citizens info citizenId should work as well.
I'll test if it works.

2017-02-13 14:39 GMT-02:00 kreezxil <notifications@github.com>:

**Comment by Raycoms** [comment]
OKay I fixed it. The next update will allow that.

2017-02-13 14:52 GMT-02:00 Ray Neiheiser <ray.neiheiser@gmail.com>:

**Comment by kreezxil** [comment]
I just checked it on build 2837 and the builder and the miner both don't say anything, at least you can play psychic roulette with them and sort of figure it out, like 10 versions ago.

**Comment by kreezxil** [comment]
I was thinking that you should have an option if not already (then what is it), to make the client and server consoles very verbose to help with debugging. For instance, I have the sneaky feeling that you have a lot of Try-Catch code to intercept error conditions and then move on with things. If there were an option to stop all this error capturing and just let it pass through to the console that might be most helpful.

**Comment by marvin-bitterlich** [comment]
@kreezxil all actual errors get violently thrown at the console, the problem are bugs not errors ;)

**Comment by kreezxil** [comment]
Seems you know what I meant, is there a way to turn that on for your "bugs"?

-----Original Message-----

**Comment by Raycoms** [comment]
bugs is something which does something we don't want without throwing
errors messages and are therefore quite hidden.
Errors can be easily be found because we always log them.

2017-02-14 17:59 GMT-02:00 kreezxil <notifications@github.com>:

**Comment by kreezxil** [comment]
Then do you have poured can you make a debug build that prints to console before and after suspect events, this would help is to help you by finding out what has stopped firing.

-----Original Message-----

**Comment by marvin-bitterlich** [comment]
@kreezxil The thing is, such a debug log would cripple a server with output. We could do that but I'd say that is a github issue for itself ;)

**Comment by kreezxil** [comment]
I'm all for it, because that last request would mean that I wouldn't be running any companion mods, as running such verbose level of data would be as crippling. However, I think that it would be instrumental in helping to solve this current state of issues where no errors are being reported to the console, ie because of "logic" bugs.

**Comment by Thanaen** [comment]
I have the same issue right now, so the bug is still here :3

**Comment by kreezxil** [comment]
I may have just given you $5, reason is, I did a world wipe on my test server and lo and behold the miner actually talks to me.

The only things that I can think that even cause this issue are:

1. upgrading a minecolonies world with a new version of minecolonies
1. using chunkloaders in your minecolony -- meaning that your people are talking to someone when you are not around and when you finally do show up perhaps they no longer want to talk to you (just theory and conjecture)

**Comment by Raycoms** [comment]
chunkLoaders 100% cause this.

They will talk to no one and then not talk for a while anymore

2017-02-15 21:05 GMT-02:00 kreezxil <notifications@github.com>:

**Comment by marvin-bitterlich** [comment]
I think our timeout was 10 minutes right? Or was it more?
We incrementally increase the time it takes for a citizen to ask again but it has a cap

**Comment by kreezxil** [comment]
Thinking about this, seems it would be ideal that of no member of the colony was online the villagers would go quiet. However as soon as a member connects they should take talking. Why a chunk loader would cause the aberrant behavior doesn't make sense to me ... ?

-----Original Message-----

**Comment by Raycoms** [comment]
We usually assume that no chunkloaders are installed, therefore, if the
chunk is loaded, a player must be close.

2017-02-16 8:41 GMT-02:00 kreezxil <notifications@github.com>:

**Comment by marchermans** [comment]
We should probably check if there are players inside the colony before we process the messages

**Comment by kreezxil** [comment]
Well, there are chunk loaders that keep chunks loaded when players aren't
on a server, this behavior is allowed on quite a few servers, mainly the
smaller ones, and all of mine, as they are small in population only, chunk
loaders for ProsperCraft are limited to when a player is on, so it
shouldn't be so much an issue for them.

Making in assumptions in code might be ok for launching a manned colony
ship to Mars for the NASA team, but Minecraft? You probably need to not
assume because a chunk is loaded that the player is on, what if the player
had visitors walking about in their colony interacting with stuff but the
player and other colony members were all offline, the same scenario would
appear.

A custom event to check if any of the colony members are on should be
adequate to determine to what if at all the npcs should be talking too.

**Comment by marvin-bitterlich** [comment]
@Raycoms we could check the subscriber list if there are any. Would still be a bit ugly to pass that to the spamfilter...

**Comment by marvin-bitterlich** [comment]
Or we could reset all spamfilters on player login

**Comment by marchermans** [comment]
As per request I started merging Issues that are related to things I found while going through the source code. One of these is the request system. Closing this in favor of #638
