### ISSUE TITLE
Colony forces their owner out, possibly due to server backup

### ISSUE THREAD

**Issue by Aasterza** [ldtteam/minecolonies#5841]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

Minecraft Version: 1.15.2

MineColonies Version: 0.13.275-ALPHA

Structurize Version: 0.13.64-ALPHA

After backing up my world for my server, the colonist wouldn't interact with the players. The players could interact with the huts very minimally, but even if there was a worker at the hut, the hut would tell the player that nobody works there. Town hall would tell the player that they already had an existing town (even though they never tried to make a second town hall) and force them to delete. 

Restaurant owners would call the owners of the town by governor, despite them not being able to do anything. Same with player officers in town, so it's partially working???

![2020-09-27_19 40 31](https://user-images.githubusercontent.com/71990972/94385321-78a03c80-010a-11eb-9512-3fa3048a4cac.png)
![2020-09-27_20 11 49](https://user-images.githubusercontent.com/71990972/94385322-79d16980-010a-11eb-9feb-158bcb1489d8.png)

**Comment by LucidDreamer0322** [comment]
something similar to this happens to me when i return from the end (possibly related?)
@Raycoms

**Comment by Raycoms** [comment]
Same as #5848
