### ISSUE TITLE
Crash on opening clip board

### ISSUE THREAD

**Issue by MatthiasMann** [ldtteam/minecolonies#5845]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- MineColonies Version: minecolonies-0.13.285-ALPHA-universal
- Structurize Version: structurize-0.13.86-ALPHA-universal
- Related Mods and their Versions:

## Expected behavior
Clip board opens and shows requests 

## Actual behavior
Crash to desktop (Client crash as the "Saving World" message was displayed, Single player)

## Steps to reproduce the issue
1. Load the world
2. Open the clip board by right clicking while holding it in the hot bar
3. Crash

### Logs
- latest.log: 
- crashlog: https://gist.github.com/MatthiasMann/8269c9c3c57f4499ecbc3d8334a60c20

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
This happens to me too when I'm in one of the YAMDA dimensions. Might also happen in the nether/end, I haven't checked.

**Comment by MatthiasMann** [comment]
I was in the over world, and right clicked directly after loading the world - maybe it wasn't synced yet from the server?

**Comment by ravenbuilder934** [comment]
Were you in your colony? That happened to me once too when I wasn't in my colony on world load.

**Comment by MatthiasMann** [comment]
Yes, standing between tavern and a courier right next to the town hall (fortress style).
