### ISSUE TITLE
When right-clicking on a citizen, their interaction menu doesn't open.

### ISSUE THREAD

**Issue by marioman3200** [ldtteam/minecolonies#5846]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.16.3
- MineColonies Version: 0.13.283-ALPHA-universal
- Structurize Version: 0.13.79-ALPHA-universal
- Related Mods and their Versions: jei-1.16.3-7.3.2.36 
OptiFine_1.16.3_HD_U_G3_MOD
## Expected behavior
I would expect to see the citizen interaction menu containing the citizens requests, health, hunger, etc when right-clicking on a citizen.

## Actual behavior
What actually happens, is when right-clicking on a citizen, their menu doesn't show up at all, leaving me unable to answer requests and see their stats.

## Steps to reproduce the issue

1. walk up to a citizen and right click them.
2. the citizen says something, but their menu doesn't open.

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
optifine
