### ISSUE TITLE
Baker not working, giving AI error

### ISSUE THREAD

**Issue by Reidlos65** [ldtteam/minecolonies#5847]
Note The AI error was when I broke the furnace trying to figure out whats wrong.  Not happening anymore as far as that particular error subject title eludes too.   However same issue below

- [ X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.15.2
- MineColonies Version: Latest (9/28)
- Structurize Version: Latest (9/28)

## Problem description
Baker isnt doing any of his job tasks.  Tried restart both of game and job via GUI.  Single player modded pack (Valhesia 2)

### Notes or related things

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MatthiasMann** [comment]
That's not a version number ...

**Comment by Raycoms** [comment]
Bakers now work on request (postbox, or minimum stock of warehouse)
