### ISSUE TITLE
What's supposed to happen after the end?

### ISSUE THREAD

**Issue by LucidDreamer0322** [ldtteam/minecolonies#5848]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- MineColonies Version:
- Structurize Version:
- Related Mods and their Versions:

## Expected behavior

Return home to continue ulgrading my town as normal, just with new mats :)

## Actual behavior

Online server, friend and i ran to the end, killed the dragon, farmed a city.  Then we got the "block is missing building" message on every root block in town and town hall says colony 1/2 is to close to claim a new colony there.

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: there was no crash, and no errors in the server to upload. Its like the game thinks this is normal.

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Please fill in the template.

**Comment by Raycoms** [comment]
Missing at least version numbers

**Comment by LucidDreamer0322** [comment]
My apologies. I didnt mean to submit as i was not finished. Was intending to add my troubleshooting. I tried a few different things, but restarting the server was ultimately what fixed it.

Forge 34.1.0
Mcolonies 13.269.alpha
Mc 1.16.3

**Comment by Raycoms** [comment]
Can you reproduce this? It can happen that there is a desync between client/server data. However, that should solve itself after a minute tops. Maybe for a very small colony it takes a little bit longer or a trip to the nether and back. Is the end portal in your colony? How did you come back to your colony?

**Comment by LucidDreamer0322** [comment]
I got yeeted into the void twice so i respawned there twice. Never checked with the buildings though before hopping off to continue the adventure. Noticed when i came home via credits portal.  The end portal we used is a naturally spawned one about 1,500 meters from my town hall. I used a waystone (mod) to tp to the portal the times i fell into the void.  My town has no other modded blocks (aside from this mods of course. And has no portals (nether, end, otherwise) anywhere near it.  I do fairly often get desync messages in the server gui. Didnt think they would be able to cause this. It seemed almost like poor garbage collection in ram clearing and the mod was missing some/all of its supporting data. Like colony/building registry and inventory links ect. Its really late and i have a long day today. I may be able to try and reproduce the issue later tonight. Will update when i can.

**Comment by LucidDreamer0322** [comment]
it happens every time i get back from the end, at first it doesnt recognize that there is even a colony present. (I run to the town hall block and it says that i am able to create a new town there as there is not on nearby) but if i leave it for a bit then it will recognize the colony, but not my ownership over it. (town hall block says i can't start a colony as there is one to close by.)  Your recommendation to enter and leave the nether does fix the issue though, so its not as much of an issue anymore as just a miner :) inconvenience.

**Comment by LucidDreamer0322** [comment]
my colony is fairly small still at only 37 citizens and about 1/3 of those being guard towers, so it shouldn't be caused by strained resources, the pc i have the server running on have an i7 processor and is set to allocate 8gb of ram, and i monitor if i should allocate more frequently, have 16gb available. I am connected via lan and my friend through online connect via public ip.  I also have a good internet package "up to" 1gb/s speeds and a fairly new router model, so while possible, i don't think it should be latency issues, particularly since i am connected locally.

**Comment by marchermans** [comment]
Syncing issue?
