### ISSUE TITLE
AI Crashed 

### ISSUE THREAD

**Issue by tanaliko** [ldtteam/minecolonies#5850]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version:  minecolonies-0.13.290-ALPHA-universal
- Structurize Version: minecolonies-0.13.290-ALPHA-universal

## Problem description
AI Crashed

![2020-10-01_16 14 29](https://user-images.githubusercontent.com/62307717/94816829-03cc4b80-0405-11eb-8587-061d1f38db54.png)
[debug.log.gz](https://github.com/ldtteam/minecolonies/files/5312387/debug.log.gz)
[latest.log.gz](https://github.com/ldtteam/minecolonies/files/5312388/latest.log.gz)

**Comment by Raycoms** [comment]
Which worker is this?

**Comment by tanaliko** [comment]
Job: Backer

**Comment by Raycoms** [comment]
@Mekle001 there seems to be some issues with furnaces sometimes it seems for bakers?

**Comment by Mekle001** [comment]
It's all smeltercrafters. I know what it is.
