### ISSUE TITLE
Bakery Worker AI Issue

### ISSUE THREAD

**Issue by Pyrocantaes** [ldtteam/minecolonies#5854]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 15.2
- MineColonies Version: minecolonies-0.13.272-BETA-universal
- Structurize Version: structurize-0.13.64-ALPHA
- Related Mods and their Versions:See latest.log

## Expected behavior
No Idea .. the worker says it's AI is broken and to report the error

## Actual behavior
Worker reports its AI is broken

## Steps to reproduce the issue

1. 
2. 
3. 

No idea .. Worker reports its AI is Broken..

### Logs

- latest.log: https://gist.github.com/Pyrocantaes/f314d61d3790ad7bd5280c9a5f9a1787
- crashlog: N/A

### Notes

Search for Leo T. Andrews which is the Worker in question
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
duplicate
