### ISSUE TITLE
Infinite resources don't work in 1.16.2

### ISSUE THREAD

**Issue by julius5** [ldtteam/minecolonies#5856]
infinite resources do not work in version 1.16.2. i already set to true creativeresolve and true builderinfiniteresources and the constructor just does nothing but freeze.

I play creatively and it really is quite boring for me to have to give the resources to each citizen.
I prefer to focus on how I want my village and defend it from incursions. What can I do to make the construction work without resources?

**Comment by Raycoms** [comment]
Just paste the structures with the buildtool then, why upgrading at all?
