### ISSUE TITLE
Using the new resource menu to give the builder items duplicates said items

### ISSUE THREAD

**Issue by Icebelly** [ldtteam/minecolonies#586]
### Minecolonies version

minecolonies-universal-1.10.2-0.6.2827

### Expected behavior

- Pressing the arrow in the builders hut to give them materials should take it out of your inventory

### Actual behaviour

- Materials are spawned into the inventory rather than being moved.

### Steps to reproduce the problem

1. Create a builder hut,
2. As the builder asks for materials, provide them from the resource tab rather than the direct inventory.

**Comment by marvin-bitterlich** [comment]
Can you try relogging and see if the items then vanish from your inventory?

**Comment by Icebelly** [comment]
Relogging did not remove them from my inventory.
I also tested by de-oping myself on the server. Same effect, still duping the items.

**Comment by marvin-bitterlich** [comment]
@xavierh can you see why this is happening?

**Comment by xavierh** [comment]
I can not have a look the week.
 Is it only  with 1.10?

**Comment by xavierh** [comment]
@Kostronor, in what branch is it in? Does not seem so be in the develop branch

**Comment by marvin-bitterlich** [comment]
@xavierh This is the version from the newest develop
@Icebelly can you test it in 1.11 too?

**Comment by xavierh** [comment]
@Kostronor looking at the branch develop, I can not see the trace of my patch. For instance TransferItemsMessage.java is not there

**Comment by marvin-bitterlich** [comment]
dang it, https://github.com/Minecolonies/minecolonies/pull/581 is still open @xavierh

**Comment by Raycoms** [comment]
fixes it with the next. It was 1.10 only
