### ISSUE TITLE
Guards can hit you when flying over them

### ISSUE THREAD

**Issue by FrostyPinkPlume** [ldtteam/minecolonies#5860]
### Prerequisites

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.1
- MineColonies Version: 0.13.258-ALPHA
- Structurize Version: 0.13.65-ALPHA
- Related Mods and their Versions: Mekanism 10.0.9

## Expected behavior
1- Hitting a guard
2- Fly with Mekanism's jetpack to miss counterattack
3- Having guards crying over their pitiness of being unable to fly to hit you

## Actual behavior
1- Hitting a guard
2- Fly with Mekanism's jetpack to miss counterattack
3- Guards hitting you anyway

## Steps to reproduce the issue

1- Hit a guard
2- Fly and suffer

### Logs

Don't seem to be any log since it don't make anything crash nor freeze

### Notes

N/A

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by someaddons** [comment]
that is actually intended
