### ISSUE TITLE
Knights and archers are not getting automatically hired

### ISSUE THREAD

**Issue by Zegahg4m3r** [ldtteam/minecolonies#5861]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
_I can't seem to find the latest alpha on curseforge, only the latest beta._
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: minecolonies-0.13.272-BETA-universal
- Structurize Version: structurize-0.13.64-ALPHA
- Related Mods and their Versions: WorldEdit-Fabric-1.15.2, AmbientSounds_v3.0.20_mc1.15.2, preview_OptiFine_1.15.2_HD_U_G1_pre30

## Expected behavior

If knights or archers are killed by hostile mobs, their work position as a knight/archer is getting automatically replaced by an unemployed citizen.

## Actual behavior

The following happened: Two knights and one archer were killed by some minecraft vanilla mobs (zombies, skeleton, etc.). Afterwards their work position as a guard was not replaced/filled in automatically by unemployed citizen and the colony population limit also went down. I can also not hire new guards, even in "manual hire mode" directly at the barracks tower hut block. I tried tearing the barracks tower down and rebuilding it from the ground up, to no avail (The hut block was also destroyed in the process and reconstructed using the "repair" button in the building screen of the barrack). I should add that the barracks and the barracks tower is at level 4, so in total I should get around 16 guards. In reality the guard counter is (seemingly?) stuck.

Lastly I just wanted to say that you guys are doing a fantastic job with the mod, I haven't played minecraft so vigorously in a loooong time. Big shout out!

I hope that some pics describe the situation better:
![error1](https://user-images.githubusercontent.com/72282507/94974203-1d0cef00-050e-11eb-9806-d6f11008ff58.PNG)
![error2](https://user-images.githubusercontent.com/72282507/94974204-1da58580-050e-11eb-83a9-9e400bd0294b.PNG)

## Steps to reproduce the issue

1. Have some guards
2. Let minecraft vanilla mobs kill them (haven't tested with raid-mobs)
3. Their position at the barracks should be freed up, but they are "frozen" and can't be re-occupied.

### Logs

- latest.log: 
[2020-10-02-6.log.gz](https://github.com/ldtteam/minecolonies/files/5320535/2020-10-02-6.log.gz)
[2020-10-02-7.log.gz](https://github.com/ldtteam/minecolonies/files/5320536/2020-10-02-7.log.gz)
[2020-10-02-2.log.gz](https://github.com/ldtteam/minecolonies/files/5320537/2020-10-02-2.log.gz)
[2020-10-02-3.log.gz](https://github.com/ldtteam/minecolonies/files/5320538/2020-10-02-3.log.gz)
[2020-10-02-4.log.gz](https://github.com/ldtteam/minecolonies/files/5320539/2020-10-02-4.log.gz)
[2020-10-02-5.log.gz](https://github.com/ldtteam/minecolonies/files/5320540/2020-10-02-5.log.gz)

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
If there are no unemployed people, no one can be hired for it.
