### ISSUE TITLE
Null pointer exception while resolving crafting recipes

### ISSUE THREAD

**Issue by ab9rf** [ldtteam/minecolonies#5866]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.3
- MineColonies Version: 0.13.298-ALPHA
- Structurize Version: 0.13.79-ALPHA
- Related Mods and their Versions: Forge 34.0.9

## Expected behavior

I do not expect colonists to complain that their AI has crashed. I also imagine that null pointer exceptions while resolving crafting recipes are not intended.

## Actual behavior

Multiple colonists report that their AI has crashed. Reviewing the log file shows multiple NPEs in the crafting system. Some crashed colonists cannot be interacted with at all.

## Steps to reproduce the issue

1. 
2. 
3. 

The problem arises from world load and requires no particular steps to experience.

Resetting the request system (/mc colony requestsystem-reset-all) generates multiple NPEs in the crafting system; see attached log.

### Logs

- latest.log: https://gist.github.com/ab9rf/089914f1b1f5774f57abaf9b015f5632
- crashlog: (none, no crash)

### Notes

---
This world was created using 0.13.263-ALPHA and upgraded to 0.13.298-ALPHA due to a bug in 263 which caused raids to never happen.
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
fixed in latest PR

**Comment by Raycoms** [comment]
(just needs to be merged into other versions)

**Comment by ab9rf** [comment]
Which PR fixes it?
