### ISSUE TITLE
builderinfiniteresources not working 

### ISSUE THREAD

**Issue by mikiepoo** [ldtteam/minecolonies#5868]
- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

- Minecraft Version: 1,16,1
- MineColonies Version: 0.13.258-ALPHA
- Structurize Version: 0.13.65-ALPHA
- Related Mods and their Versions:

## Expected behavior
Builder would start building the building and eventually finish

## Actual behavior
Builder does not ever begin building. I have builderinfiniteresources set to true and the creativeresolve option set to true. 
With the development features on the builders always get stuck with (WORKING)(LOAD_STRUCTURE) above their heads. They are standing next to their builder huts when this happens. The only way I have been able to make them progress is to manage their job and pause, then restart. They then immediately start and finish the job request. This happens with every building and upgrade. You always have to pause and restart.

## Steps to reproduce the issue

1. Place a building and click the build option
2. Receive notification that a builder has started building
3. Builder goes to their building hut and stands next to the station.
4. Builder never progresses past LOAD_STRUCTURE

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by mikiepoo** [comment]
Another note. I walked away, went afk and died overnight. 

I had 6 builder huts setup, 3 of the 6 started building after i went to bed and woke back up after my death. The other 3 are still stuck at LOAD_STRUCTURE.

**Comment by Raycoms** [comment]
ye, this is a debug mode. If you want stuff for free, go in creative mode and paste it.
