### ISSUE TITLE
Colonist appear to not function - also other game aspects are affected

### ISSUE THREAD

**Issue by Aduis1210** [ldtteam/minecolonies#5870]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: minecolonies-0.13.307-BETA-universal
- Structurize Version: structurize-0.13.86-ALPHA-universal
- Related Mods and their Versions:

## Expected behavior
Colonists not to freeze

## Actual behavior
Since updating to latest BETA - my colonists have stopped fully - also noticed im unable to place a bed down to sleep and commands arent working 

## Steps to reproduce the issue

1.  - Update pack
2.  play game
3.  nobody works 👎 

### Logs

- latest.log: [https://paste.ee/p/oZLIv]

- crashlog: no crash

### Notes
Playing on ALPHA 301 my game appears all well and nothing broken - since updating to Beta. - its caused issues.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Sure it's not just raining or they are mourning?

**Comment by Raycoms** [comment]
Can't find anything in the log

**Comment by Aduis1210** [comment]
Not Raining or mourning - literally just froze - unable to access their inventories either

**Comment by Raycoms** [comment]
anything else working? Can you interact with other entities?

**Comment by Aduis1210** [comment]
tried placing a sleeping bag and it only shown half the bag - im unable to use commands as well.
Additionally - noticed that all mobs freeze.

**Comment by Aduis1210** [comment]
Ive downgraded back to 0.13.301 to see how that goes

**Comment by Raycoms** [comment]
Seems something got caught in an infinite loop.

**Comment by Aduis1210** [comment]
since downgrading my whole town is working fine

**Comment by MatthiasMann** [comment]
I also had a lockup using 0.13.302 and I looked with jps at the strack trace (sadly I did not keep the stack trace). But the render thread was stuck on a chunk loading lock/mutex called from Journeymap, and the server thread was stuck in removeXPFromSkill (or similar) called from the cow herder.
