### ISSUE TITLE
Builder view (inventory and stats)

### ISSUE THREAD

**Issue by A-Dunois** [ldtteam/minecolonies#5872]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.313 BETA
- Structurize Version: 0.13.86 ALPHA
- Related Mods and their Versions: 

## Actual behavior

I'm trying open the inventory/stat view of one builder

## Steps to reproduce the issue

1.  Right click on builder
2.  See the client crash

### Logs

- latest.log: 
https://gist.github.com/A-Dunois/eca7946f730e0849a43369d624d33005
- crashlog:  
https://gist.github.com/A-Dunois/ee4b5164e22bea115e5129ac8c507c8e

### Note

No server crash, just my client.
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by A-Dunois** [comment]
Affect only builder.

update:
I have fired one builder and i can see his menu again. But right after he's start a construction, i can't see his menu (crash)

**Comment by A-Dunois** [comment]
hmm, to debug, i must click on a builder with special demand (sick, need something, ....) 
My buddies have same crash.

**Comment by Raycoms** [comment]
Update to latest

**Comment by A-Dunois** [comment]
Update to last version (318 alpha).
I have the bug again.

**Comment by Raycoms** [comment]
Send us the new log then please

**Comment by A-Dunois** [comment]
https://gist.github.com/A-Dunois/204ff8a32dbce6a8b0ab11f81e47f37e

**Comment by Raycoms** [comment]
Can you try a /mc colony requestsystem-reset-all ?

**Comment by A-Dunois** [comment]
It's working perfectly.

I don't know this command can perform that. 
Thank for your help.
