### ISSUE TITLE
Builder AI Bug

### ISSUE THREAD

**Issue by tanaliko** [ldtteam/minecolonies#5873]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: minecolonies-0.13.297-ALPHA
- Structurize Version: structurize-0.13.86-ALPHA
- Related Mods and their Versions:  The Endless Frontier 5.4 pack  

Builder AI Bug 

![2020-10-04_22 28 23](https://user-images.githubusercontent.com/62307717/95025311-6df92080-0691-11eb-9246-e43617c9b7ea.png)

### Logs
[latest.log.gz](https://github.com/ldtteam/minecolonies/files/5324176/latest.log.gz)

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
fixed in latest
