### ISSUE TITLE
ticking screen error

### ISSUE THREAD

**Issue by Nikademus** [ldtteam/minecolonies#5878]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.16.3
- MineColonies Version: 0.13.312 beta
- Structurize Version:  0.13.90
- Related Mods and their Versions:

## Actual behavior

Client has crashed twice while accessing builder request list.

## Steps to reproduce the issue

1. Click on builder (not hut)
2. select request list and scroll to bottom.
3.  client crashes.

### Logs

both are here: https://gist.github.com/Nikademus/18b4d1a2f8e04d278eaa5cb0150432eb
- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
fixed in latest
