### ISSUE TITLE
Stonemason won't craft stone bricks

### ISSUE THREAD

**Issue by MatthiasMann** [ldtteam/minecolonies#5880]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.318-alpha
- Structurize Version: 0.13.91-alpha
- Related Mods and their Versions:
- Singleplayer

## Expected behavior
Stone mason will craft stone bricks when requested

## Actual behavior
Stone mason gets stone delivered (stored in hut block), the task view (2nd page of the hut block) shows for a brief moment the task to craft stone bricks for my builder and then the task vanishes again without having done any crafting.

## Steps to reproduce the issue
1. The stone mason last worked in 0.13.293
2. He improved the stone -> stone bricks recipe twice - now it only needs 2 stones to craft 4 stone bricks
3. Then I updated to 0.13.318 (I also tried 0.13.302 which had other issues so I rolled back to a backup of my world and tried today with 0.13.318 again).
4. Now the stone mason seems to be broken
5. I did restarts, fire&hire, RS resets, cancelled the requests for the 123 stone bricks several time - nothing got the stone mason working.

### Logs
I looked in both debug.log and latest.log and there are no debug messages or error messages from Minecolonies - only the messages I saw in the chat from resetting the RS or restarting the stone mason.

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
can you send us that world?

**Comment by MatthiasMann** [comment]
The Problems seems to have been fixed either by a game restart or by the update to minecolonies-0.13.324-ALPHA-universal. I'll close the issue for now.

If the problem reappears I'll reopen it.

**Comment by MatthiasMann** [comment]
It has reappeared in 0.13.328 - I send you the link to the world save.

**Comment by MatthiasMann** [comment]
I updated to 0.13.334 and did a RS reset - still happens.

**Comment by Aduis1210** [comment]
I had issued with my sawmill - fired and rehired the worker and did a RS reset as well and it seemed to work

**Comment by Mekle001** [comment]
Ray and I are both looking at different possible aspects of this. 

In all of the cases I've seen, the worker appears to be in a state where as far as the deliveryman is concerned all of the resources have been delivered, but the building doesn't actually have enough to start the crafting job.

One of two things appears to fix it, either removing all of the ingredients from the hut, or adding the missing ingredients. 

There are two pull requests pending right now. #5904 may be part of the problem, and I tweaked some of the counting logic in #5905 to enable the reliable secondary outputs.

**Comment by Aduis1210** [comment]
Loving the updates 💯

**Comment by MatthiasMann** [comment]
I also just looked at the chest button (bottom right in the UI) of the stone mason - which shows much more resources than the racks (empty) and the hut block actually contained - which would match with what you said Mekle001. Moving these resources in the hut block around fixed the count displayed by the chest button.

**Comment by Mekle001** [comment]
I spent quite a bit of time watching this scenario happen and recover on it's own last night as I was testing changes. I believe #5905 fixes this. Once that is released, can you take a look again?

**Comment by Aduis1210** [comment]
sure Mekle, do you have a eta?

**Comment by Mekle001** [comment]
I just submitted what I believe is the last changes for feedback, so as soon as the reviewers get a chance to look at those, it will likely merge and release. Probably by tomorrow at the latest, barring any more feedback.
