### ISSUE TITLE
[1.16.3] When a player types commands all players on the server see the reply.

### ISSUE THREAD

**Issue by ProsperCraft** [ldtteam/minecolonies#5882]
### Prerequisites 

- [X ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

Minecraft Version: 1.16.3
MineColonies Version: minecolonies-0.13.315-ALPHA-universal
Structurize Version:structurize-0.13.92-ALPHA-universal
Related Mods and their Versions: TownCraft TWO

## Actual behavior

![2020-10-05_21 01 28](https://user-images.githubusercontent.com/4427684/95154055-2b494e00-074e-11eb-8e94-c2c13f951708.png)
![2020-10-05_21 03 10](https://user-images.githubusercontent.com/4427684/95154067-313f2f00-074e-11eb-80c3-c9c2bdacf47f.png)

## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Are you sure it goes to all players and not just the admins (that one is automatic)

**Comment by someaddons** [comment]
it goes to OP's, its a vanilla setting

**Comment by someaddons** [comment]
we do have logging to console enable for most commands, so that they actually are useable via console. The server.properties setting "broadcast-console-to-ops=true" then sends it also to all OP's
