### ISSUE TITLE
1.15.2 Builder stuck on certain building upgrade

### ISSUE THREAD

**Issue by nanonestor** [ldtteam/minecolonies#5883]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.318-ALPHA
- Structurize Version: 0.13.91-ALPHA
- Related Mods and their Versions:

## Expected behavior

Successful building upgrade by builder.

## Actual behavior

While attempting to upgrade 'Stone' version university from level 2 --> 3 builder refuses to progress beyond a point.  All of the recommended methods to resolve builder issues has been tried, including repairing the structure back to L2 and starting over.  At the point builder gets stuck they travel back and forth from building hut to university and do not do anything.  However to amuse themselves the builder while in the hut side will shuffle around some items back and forth between their inventory and a rack, then head out to do the quick hike to building and back.  Builder insists on requiring grass blocks if inventory is emptied.  If supplied with grass blocks, etc builder request disappears but does not resolve building progress.

Additionally - during construction to this point builder keeps placing grass blocks below lanterns placed around the university despite them not appearing in the L3 version of the stone university if viewed in game using the build tool and a different university hut block.  Will attach photo link of what this looks like.  The builder additionally shows a brief red error icon above themselves in the moments they get to the uni and do an about-face.

If this is a structurize or blueprint issue sorry - this seemed like a reasonable category to start.

## Steps to reproduce the issue

1.  Attempt to upgrade a stone university from L2 to L3
2.  Or look at the blueprint in question?  I did ask on Discord if this seemed like a blueprint issue and someone said it sounded more like a mechanics problem? Above my pay grade.
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

https://i.imgur.com/ideL4nD.png
https://i.imgur.com/qlXwOsy.png
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Fixed in newest
