### ISSUE TITLE
Citizen stay outside their houses at night

### ISSUE THREAD

**Issue by lebanni** [ldtteam/minecolonies#5884]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version:0.13.318-ALPHA
- Structurize Version:0.13.91-ALPHA
- Related Mods and their Versions:

## Expected behavior

Citizen get in their beds at night.

## Actual behavior

At night, citizen stay outside their house. Buildings affected are spacewars houses level 4.

![2020-10-03_10 07 50](https://user-images.githubusercontent.com/2799575/95157268-ce26ba00-0798-11eb-96e8-03ed2dd1a1b0.png)

## Steps to reproduce the issue

1. 
2. 
3. 
Build level 4 spacewars house.

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
is their path inside somehow blocked?

**Comment by lebanni** [comment]
It looks like that with the latest versions of minecolonies and structurize, it working fine again. Sorry for the inconvenience.
