### ISSUE TITLE
Building/Supply Ship preview not displaying.

### ISSUE THREAD

**Issue by Dushall** [ldtteam/minecolonies#5888]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

- Minecraft Version: 1.16.3
- MineColonies Version: 0.13.312 Beta
- Structurize Version: 0.13.90 Alpha

## Problem description
When I started the game I build the boats to get me the supply ship. When I would click on a block close to the water it would open up the GUI but the ship was not visible. I moved the ship around and eventually got it to spawn way out in the water. When I gathered my town hall and build tool I attempted to place down my town hall but it was not visible either. I started a new minecraft game after closing out of the game and it did the same thing to me. 

### Notes or related things
Not running any other mods on this game and I do not have optifine installed. 

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Are you on fabolous setting?

**Comment by Dushall** [comment]
That worked. Thank you.
