### ISSUE TITLE
I get kicked from my server when klicking on a minecolonies block (did not happen before updating versions)

### ISSUE THREAD

**Issue by nicoo1708** [ldtteam/minecolonies#5889]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: minecolonies-0.13.324-ALPHA-universal
- Structurize Version: structurize-0.13.91-ALPHA-universal

## Problem description
 
I've just updated to the newest alpha versions on my server. Now, as i click on any minecolonies block like the postbox or the builders hut block for example, i get kicked from the server with the error message "Payload may not be larger than 32767 bytes". 

### Notes or related things

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Any log?

**Comment by Raycoms** [comment]
@OrionDevelopment did you try this with a server instance too?

**Comment by nicoo1708** [comment]
Which logs do you need?

**Comment by Raycoms** [comment]
latest.log which includes the problem

**Comment by nicoo1708** [comment]
from my client or from the server?

**Comment by Raycoms** [comment]
both

**Comment by nicoo1708** [comment]
[latest.log](https://github.com/ldtteam/minecolonies/files/5337279/latest.log)      <--- Client
[latest.log](https://github.com/ldtteam/minecolonies/files/5337283/latest.log)      <--- Server

**Comment by Raycoms** [comment]
@OrionDevelopment

**Comment by lebanni** [comment]
I have the "Block entity invalid" issue and also "Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Payload may not be larger than 32767 bytes" when opening clipboard (building spacewars level 1 enchanter) and disconnected from server.

**Comment by Mstevens24** [comment]
Getting the same thing. I updated 1.15.2 and the GD launcher and everything was fine for around 2-3 hours then all of a sudden whenever I open the clipboard it crash's the client. The server stays up though. This happens if I click on any minecolonies block.

[console.txt](https://github.com/ldtteam/minecolonies/files/5337922/console.txt)

**Comment by marchermans** [comment]
I tested this... And this worked. I created a colony and ran tests on the colony, interacted with citizens etc.
No clue why this is all of a sudden broken, and why a much smaller max packet size is now all of a sudden needed.......
