### ISSUE TITLE
[BUG] Colony lost / not functional anymore 

### ISSUE THREAD

**Issue by Florianer** [ldtteam/minecolonies#589]
### Minecolonies version 

version 0.6.2669

Hi,
I'm using MineColonies alongside with 60 mods in MC 1.11.2. I built the town hall, builder, lumberjack and citizen hut and leveled them all up to the max. I also build decorations. I recognized the error when I wanted to start building the stone mason. I can place the block, but I cannot use the scepter gold anymore. Decorations are still fine, but switching to the buildings menu, I get the "no buildings" text on the left button. 

I messed around with the town hall and now I can click on it but it is totally broken. Recalling workers quit with "make more space", /minecolony colonies list brings 1 matching result, /minecolony colony respawn|citizenInfo|… results in "unknown error". Colony got the ID 1, but I also see "couldn't find colony -1"

Colonies.dat got 4kb. Restarting the single player world had also no positive effect. Whatever happened, now also my 5 citizens are gone. Town hall lists them, but I can't find them anymore. 

This is now the 2nd time in this world since I created it on Saturday. Last time, I believe, I solved the problem by deleting the town hall's and the builders' block and recreated the little colo from scratch. But now I got a few more buildings. And without recalling the people back to me, it could be hard to recreate the town. 

I'm also not sure how to reproduce it but if I can provide you with any further information tell me.

**Comment by Raycoms** [comment]
The versions we uploaded today should fix the make more space problem.
Please beware, stonemason is not ready yet. Using him with the build tool
could cause problems.

2017-02-13 21:58 GMT-02:00 Florian Mycka <notifications@github.com>:

**Comment by marvin-bitterlich** [comment]
Also commands are still a bit arcane. You f.e. got -1 because you ommited the id.

And the | is an or, only use on of the commands :D

**Comment by Florianer** [comment]
Hey,
I updated to 0.6.2837 and retested it. I removed the stonemason block. Nothing changed. Recalling the citizens still results in "recall failed - Please make more space". I removed and set the town hall block where it was. Same result. Desperately I removed the town hall building completely. Used the build tool to position a new town hall. Worked. I also see now the fancy and really helpful construction line. Nicely done.   I can interact with the town hall block. It still knows the colony name and also tells me that I got 5/5 citizens. Interesting fact: unemployed: 3, building worker: 1, post man: 0. 5 != 4.

**Comment by Florianer** [comment]
@Kostronor yap, I know about |. It was meant to indicate, that I tried all those commands separately with the same result :P But the -1 info was helpful. More to me than to my colony :D Used the kill command. Now it is gone. Set up a new town hall with ID 2 now. But all other buildings lost relationship to the colony. Can I readd them? Destroying the builder's hut block and setting a new one seems not to work. 4 people spawned, but right now, nothing is happening.  Maybe because the new set block on the same position got the data back from the old one. The worker do not exist anymore, I also cannot interact with it. Town hall set to manually, but firing the builder have no effect. The only working button is the inventory.

**Comment by Raycoms** [comment]
Removing your colony will remove the working of all building blocks. You
have to remove and replace them as well.

2017-02-14 7:07 GMT-02:00 Florian Mycka <notifications@github.com>:

**Comment by Florianer** [comment]
Ok, that did the trick. Used the kill command, removed the colony. Checked with colonies list that all is gone, removed all colony build blocks, killed all citizens. Started with a fresh new town hall, lvl 1 builder, placed a miner, started a warehouse. I'll let them build and report back, when/if it happens again.

About the colony removal: Wouldn't it be an option the click on a building block and click readd or so the get them back in the list? My builder removed a lvl builder's hut just to build on the exact same spot lvl 1.

**Comment by Raycoms** [comment]
I'd say we close this here for now. For the future, if you seem to be not able to access your colony do /mc colony refresh which might help.

For the second 1. You could open an issue of that particular issue and we could discuss it.

**Comment by guitarguy0124** [comment]
I've had this same issue more times than I can count. Pretty much every other time minecraft crashes. And I'm not doing anything with the stone mason. Restore doesn't work. Just have to start a new world...amazing mod, but there's got to be some way to recover.
