### ISSUE TITLE
aside from owner no opening of the colonist menu by other players

### ISSUE THREAD

**Issue by Swantsy** [ldtteam/minecolonies#5890]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.1
- MineColonies Version: 0.13.258-ALPHA
- Structurize Version: 0.13.65-ALPHA
- Related Mods and their Versions: valhesia 3 modpack

## Expected behavior
have other members of the colony, officers be able to talk to the colonists

## Actual behavior
When they click the colonist in order to open up the colonist menu, the colonist talks but it does not open the menu. only the owner of the colony can open up the menu of the colonist and see their needs individually.

can be seen on https://www.twitch.tv/lokiwankenobi_ where it is failing to open in the vod of 06/10/2020 and 07/10/2020

## Steps to reproduce the issue

make a colony, make someone officer and they can't open up the colonists menus.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Do the officers have OptiFine installed? It messes with colonist GUIs.

**Comment by Swantsy** [comment]
indeed they are, weird that it does that, one of them is disabling it to see if that is the problem, actually both are. Weird that it does that but an easy fix.

yup, they can open it now. I would suggest putting something on the wiki about this so others don't open tickets like this :)

**Comment by ravenbuilder934** [comment]
OptiFine fixed it in the latest 1.16.3 preview, so this isn't going on the wiki as 1.16.1 isn't supported anymore
