### ISSUE TITLE
Open requests - Not updating when adding to current stacks in warehouse

### ISSUE THREAD

**Issue by Aduis1210** [ldtteam/minecolonies#5897]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.15.2
- MineColonies Version: 0.13.328-Alpha-Universal
- Structurize Version:0.13.94-Alpha-Universal
- Related Mods and their Versions:

## Expected behavior
Update item stacks in Warehouse and this to update the clipboard open requests as fufilled.

## Actual behavior
Update stacks ( for example, building guard towers - request for ladders - craft and update a current stack in the warehouse - request stays the same)

## Steps to reproduce the issue

Request building to be built.
Place half the required items (eg. Ladders) into warehouse.
When builder requests items on clipboard. then place items on stack in warehouse to complete the request.
Clipboard should still show items requested, but the warehouse already has the items.

### Logs
No Crash log - just weird behaviour

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
That's not a bug, that's a feature request.

**Comment by ravenbuilder934** [comment]
Wait, what? Why is this a feature request?

**Comment by Raycoms** [comment]
the clipboard doesn't show those requests.

**Comment by ravenbuilder934** [comment]
I interpreted this as more "Builder needs 64 ladders. There are 32 in the warehouse. I can see on clipboard that the builder needs 64 ladders, and I know there are 32 in the warehouse. I crafted 32 more and put them in the warehouse, but the request for 64 is still on the clipboard (and so the builder doesn't recognize there are enough ladders now)."

**Comment by Raycoms** [comment]
Ahhh, now I am getting this.

**Comment by Aduis1210** [comment]
Is this a know issue?
Im confused as Ray is getting the problem and this has been closed?

**Comment by Raycoms** [comment]
I double checked this, if you have one warehouse, this works perfectly fine for me (I requested 64, and then put in two separated actions 32 in)

**Comment by MatthiasMann** [comment]
The issue is if there is already a partial stack in the warehouse - and you add things to that stack. This is not seen by Minecolonies (eg if you shift click 10 logs onto a stack which has say 30 log resulting in a stack of 40 - the RS still thinks there are only 30).

**Comment by Raycoms** [comment]
Ahhhhh, let me test that

**Comment by Aduis1210** [comment]
Apologies for the rubbish description. Thanks matt for helping with this one
