### ISSUE TITLE
Visitor entity set to zero pos, report to mod author

### ISSUE THREAD

**Issue by onlyamonth** [ldtteam/minecolonies#5898]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- MineColonies Version: minecolonies-0.13.328-ALPHA-universal
- Structurize Version: structurize-0.13.94-ALPHA-universal

## Actual behavior

Log is spammed with the message:
[1;31m[21:12:39] [Server thread/ERROR] [minecolonies/]: Visitor entity set to zero pos, report to mod author:
Until eventually tick timing out and server stops. 
Upgraded from minecolonies-0.13.245-ALPHA-universal 

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: https://gist.github.com/onlyamonth/7d7539837a8941527c97386628da4221

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by someaddons** [comment]
add the latest.log please the stacktrace when the error is first thrown is important

**Comment by onlyamonth** [comment]
Latest Log: https://gist.github.com/onlyamonth/16370971d2cbf5fdd847ec2a31f7aa99

I have been hurrying to get the server playable again, so have gone back to 313 beta, the log still gets spammed and the crash still (sometimes) occurs. Othertimes a player gets the message "visitor died from outofworld at 0 -182 0)"
