### ISSUE TITLE
Loosing Permissions in your own colony.

### ISSUE THREAD

**Issue by pmardle** [ldtteam/minecolonies#590]
Pretty frequently I log in to the server and find myself unable to interact with my colony.  A simple /mc colony addOfficer <colonyID> <myname> works as a workaround, but for those who are not OP's this must be a real turnoff to our mod.

Do we know why this happens (corruption of save data)?
Is there any way of stopping it?
Is there anything we can do to work around it to at least make sure the colony owner is restored if the mod looses its data? 

This happened on the old server a LOT and has happened to me on the new one as well..

Happy for a bounty to be added to this one.

**Comment by Raycoms** [comment]
I added a /mc colony refresh command which restores the owner if lost.
I guess the problem is corruption of the data on save.
And I think we can close that, therefore.

**Comment by pmardle** [comment]
Thats awesome :)

**Comment by protanium** [comment]
That command does not work
