### ISSUE TITLE
Game not load when using  Hwyla or The One Probe

### ISSUE THREAD

**Issue by Eisar93** [ldtteam/minecolonies#5900]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.3
- MineColonies Version: 0.13.330 ALPHA
- Structurize Version: 0.13.92 ALPHA
- Related Mods and their Versions:

## Expected behavior

Game will load.

## Actual behavior

The game don't load

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: https://gist.github.com/Eisar93/8aa21c9439b7ee0a1c3125f30954e3d6#file-crash-2020-10-10_00-44-55-client-txt

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
have you tried without optifine?

**Comment by Eisar93** [comment]
Yes and the problem still is minecolonies:particle/sleeping. Like I said only occur when 1 of the 2 mods in the title is in the mod folder.

Here is the crashlog without optifine: https://gist.github.com/Eisar93/aed5d99e19b23d839b7feb6a994718a8

I don't needed repared, I only create the issue for you to knowing so you can improve even more this fantastic mod.

PD: forgive my english, it isn't my mother language.

**Comment by Raycoms** [comment]
I'm leaving this issue open for now. However, I'll have you know that this is most likely not out faulty (It does happen with a lot of other mods too that add particles). I will investigate to see what exactly is causing this.

**Comment by Eisar93** [comment]
Ok. I will still trying to move in/out mods to see if the problem can be resolved. If it isn't your fault forgive me for posting here, I only do it because of the particle that causes the bug. I will update if I find the problem. And thanks for the attention.

**Comment by Eisar93** [comment]
It was the Torch Slabs Mod that was causing the problem so you can close the issue now.
