### ISSUE TITLE
1.15.2 Guards "jiggling" when guarding

### ISSUE THREAD

**Issue by Borkius** [ldtteam/minecolonies#5901]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.328
- Structurize Version: 0.13.94

## Expected behavior

Guard stands in location normally.

## Actual behavior

Guards "jiggle/turn" back and forth violently when assigned to guard a location.

Zip file includes .flv recording of glitch.
[Guard Jiggle.zip](https://github.com/ldtteam/minecolonies/files/5358155/Guard.Jiggle.zip)

## Steps to reproduce the issue

Assign a guard to guard a location/block.

### Logs

- latest.log: https://gist.github.com/Borkius/7227b2e89821850fcb343a4adf98c4a2

### Notes

Using Craft to Exile (Dissonance) modpack, just to explain all the other mods in the log.
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
That can happen when they get stuck on a block. That is quite normal.

**Comment by Borkius** [comment]
All my guards do this when I set any of them to guard in any spot though. They can stand on a spot I set them to guard by themselves without jiggling but if I set them to guard anywhere they do it.
