### ISSUE TITLE
[suggestion] allow terracotta to be used with timber framed blocks

### ISSUE THREAD

**Issue by mvdhoning** [ldtteam/minecolonies#5906]
I already love the new possibilities with timber frame blocks.
But what i would like to see to be added is that one can use terracotta (or stained wood) with the timber frame blocks to allow for some more colored housing.

**Comment by ravenbuilder934** [comment]
This repository is only for bug reports. Open an issue at https://github.com/ldtteam/minecolonies-features/issues.
