### ISSUE TITLE
Game Crashes Every Time When Accessing Builders Stat Menu

### ISSUE THREAD

**Issue by Runieman** [ldtteam/minecolonies#5907]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.3
- MineColonies Version: 0.13.312-BETA-universal
- Structurize Version: 0.13.90-ALPHA
- Related Mods and their Versions: 
Optifine 1.16.3 HD U G4 pre2 (INCLUDES A PATCH)
Xaeros Minimap 20.25.0
Jei 1.16.3 - 7.5.0.43
Invtweaks 1.16.2 - 1.0.0
FastLeafDecaY - V25

## Expected behavior
Access the builders menu to view stats and further access the inventory.

## Actual behavior
Upon right-clicking the builder, the menu will display missing items for construction however will crash when progressing to the stats men it will crash.

## Steps to reproduce the issue

right click the builder
Progress through required items for construction project
game will freeze for a second then close to the crash-log

### Logs

- latest.log: https://gist.github.com/Runieman/d0c19740ebfc4289fb634b758d042a76
- crashlog: https://gist.github.com/Runieman/2c9201ee6259b12ea7003511bfe6959d

### Notes
Was working fine for the last couple of hours (Including with optifine), Believe issues started when I requested a level 2 Bakery possibly.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Please update to the latest alpha and see if this issue still occurs.

**Comment by Runieman** [comment]
> Please update to the latest alpha and see if this issue still occurs.

That seems to have fixed it!
Thanks!

**Comment by Izalcomax** [comment]
I dunno what's happened but this is still a bug
6 years later

**Comment by Talyda** [comment]
> I dunno what's happened but this is still a bug 6 years later

No, 6 years later it is not still a bug. It might be a new bug, but it is not one from 6 years ago =P

Make an issue, provide all the information the template asks for. Or better yet, ask on discord first, cos it probably is an outdated version, or a mod interaction
