### ISSUE TITLE
Bakery Request crashes Game

### ISSUE THREAD

**Issue by dinomiteX** [ldtteam/minecolonies#5909]
### Prerequisites 

- [] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.3
- MineColonies Version: minecolonies-0.13.312-BETA-universal
- Structurize Version: structurize-0.13.90-ALPHA-universal
- Related Mods and their Versions: can be found in the minecraft crash report

## Expected behavior

Open Bakery Worker Request Screen

## Actual behavior

Game Crashes while trying to open either the clipboard or the baker worker gui directly

## Steps to reproduce the issue

1. Build Bakery
2. Try to open Clipboard or bakery worker gui while having a request from bakery

### Logs

- crashlog: https://gist.github.com/dinomiteX/95d035d28d78b985cace83c8b3006a04ü

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Update to latest alpha
