### ISSUE TITLE
Stone Smelter AI issue

### ISSUE THREAD

**Issue by Jackpotmans** [ldtteam/minecolonies#5912]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.15.2
- MineColonies Version: 0.13.291-ALPHA-universal
- Structurize Version: 0.1386-ALPHA-universal
- Related Mods and their Versions: Valhelsia 2 modpack with adds Biomes of Plenty, Silent Gear, and the like.

## Expected behavior

Stone smeltery to be functional past level 2

## Actual behavior

When I build the stone smelter, it began to work as normal.  However, once I upgraded it to level 2 and level 3, the npc showed this error.  I tried restarting the npc, firing and rehiring, and gving the job to a new colonist and the same message appeared.

![bug_stonesmelter2](https://user-images.githubusercontent.com/39043011/95763796-27995800-0c75-11eb-9f19-e6b14dee40c6.png)

## Steps to reproduce the issue

1.  build the stone smelter
2.  set recipes as: cobble to stone, each vanilla log to charcoal, clay to bricks, and clay block to terracotta
3. Upgrade Stone Smelter to level 2

### Logs

- latest.log: https://gist.github.com/Jackpotmans/95d152af3ce5f9142453a2c3734b54b2
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Update to latest alpha
