### ISSUE TITLE
Asian Player house rotating between 1st and second level

### ISSUE THREAD

**Issue by Nikademus** [ldtteam/minecolonies#5915]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.3
- MineColonies Version: 0.13.336
- Structurize Version: 0.13.92
- Related Mods and their Versions:

## Expected behavior

Asian player house would upgrade properly

## Actual behavior

When upgrading from 1st to 2nd level for the Asian style player house, the design rotates 1/4 turn counter clockwise.  The third level updates in place over the 2nd level fine.

![2020-10-06_15 48 16](https://user-images.githubusercontent.com/1380028/95799438-a799df00-0cc2-11eb-8103-2e7249ebe260.png)
![2020-10-06_15 48 23](https://user-images.githubusercontent.com/1380028/95799439-a963a280-0cc2-11eb-907f-a8bf74c3be05.png)
![2020-10-11_10 06 48](https://user-images.githubusercontent.com/1380028/95799447-b1bbdd80-0cc2-11eb-964b-bdf9403b8119.png)

## Steps to reproduce the issue

1. Build level 1 Asian style player house, 
2. upgrade it
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

I spoke with Thaylar and he believes it's something with the mod and not a schematic issue.
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
There was a whole long conversation last night between Ray and another player (in #schem-bugs channel on the discord if you want to check it out) Did you place the first level without using the build tool?

**Comment by Talyda** [comment]
(Just realised I mis-read, so deleted =P)

**Comment by Raycoms** [comment]
I fixed it in the latest.
