### ISSUE TITLE
Crash on opening certain citizens views

### ISSUE THREAD

**Issue by Sereliana** [ldtteam/minecolonies#5916]
---	
name: Game crashes on opening certain citizen overviews
about: Please follow the given template	
title: 'Crash on opening certain citizens views'	
labels: Bug	
assignees: ''	

---	

### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2 
- MineColonies Version: minecolonies-0.13.313-BETA-universal
- Structurize Version: structurize-0.13.86-ALPHA-universal
- Related Mods and their Versions: Using the Life in the Village 2 Pack so lots of other mods

## Expected behavior
I would usually skip chit-chat and click on requests to fulfill everything I can.

## Actual behavior
I click on skip chit-chat, the game freezes then crashes. It gives the following error message: 

The game crashed whilst ticking screen
Error: java.lang.ClassCastException: com.minecolonies.coremod.colony.buildings.workerbuildings.BuildingLumberjack$View cannot be cast to com.minecolonies.coremod.colony.buildings.AbstractBuildingCrafter$View
Exit Code: -1

I can still click through the requests by themselves, but as soon as character info would show the game just crashes. This first happened with a new miner when the old one had died. A new 4th citizen spawned, took the miner job and requested 40 stripped logs and some other stuff.
When trying to see all requests by skipping the chit-chat the game crashed. I also tried killing the villager, after the new one spawned I kept their character view open until they took the job, which instantly crashed the game as soon as they took it. This now also started happening with my level two builder, I was able to fulfill a few requests but then it suddenly crashed. Now I can't open his character view either.

## Steps to reproduce the issue

I have no idea, I have a miner, forester and 2 builder. This happened after one miner had died and a new one took the job, so that might be the reason. Can't explain the builder though.

1. Build mine, assign miner
2. Let it get killed by mob
3. Wait for new villager to arrive and assign it to the miner job, it should now just stand around with requests

### Logs

- latest.log: https://gist.github.com/Nocull/ab53c57722d64123b80d618c0d95e2c2
- crashlog: https://gist.github.com/Nocull/e9b559753f7af66f710b926b4d785a70

### Notes
This is on a dedicated multiplayer server.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
update
