### ISSUE TITLE
Crash on World Load 

### ISSUE THREAD

**Issue by xanthophyll** [ldtteam/minecolonies#5917]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.347-BETA (occurs on 0.13.344-ALPHA & 0.13.341 ALPHA)
- Structurize Version: 0.13.94-ALPHA
- Forge Version: 31.2.45

## Problem description
Crash on load existing world, applies to this specific world only. "The given compound holds an unknown output type for this Controller" displayed from launcher, appears to be related to colony manager/request system manager. 
Full latest.log in the following dump: [https://gist.github.com/xanthophyll/01116cb7d6be3b19df4655c1443a164d](https://gist.github.com/xanthophyll/01116cb7d6be3b19df4655c1443a164d)

### Notes or related things
Please contact me on discord (archAng3l#0589) with requests for information or for solutions. I will append any additional information or solutions (prospective or actual) to this post in timestamped edits.

EDIT 13/10/20:
I believe it has something to do with the minecolonies "colonies" file (attached below). Transplanting the region/playerdata files into a freshly generated world circumvented the problem.
[colonies.zip](https://github.com/ldtteam/minecolonies/files/5374943/colonies.zip)

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
@xanthophyll can you try with the latest please and a) tell me if still happening and b) give us the log?
