### ISSUE TITLE
Lanterns need to be placed in the decoration phase (like torches)

### ISSUE THREAD

**Issue by MatthiasMann** [ldtteam/minecolonies#5919]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.349-alpha
- Structurize Version: 0.13.94-alpha
- Related Mods and their Versions:

## Expected behavior
Lanterns are placed like torches when the walls and roofs are completed.

## Actual behavior
They are placed before the roof is on the house - this can lead to them falling when the roof blocks are placed.
![2020-10-14_19 44 13](https://user-images.githubusercontent.com/6777029/96025838-00e64780-0e56-11eb-9bc6-53de15fe52e1.png)

## Steps to reproduce the issue
1. Upgrade a fortress warehouse from level 3 to level 4

### Logs
I can provide log if required - but I think this is unrelated to anything which might appear in logs.
- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
The lanterns are also like that for the wooden beekeeper 2 -> 3 (iirc), but I don't think they broke-I'll need to check again

**Comment by MatthiasMann** [comment]
Yeah - I expected they break - but somehow they didn't - lucky :D

**Comment by Mekle001** [comment]
The place where they consistently break is when they are placed, and then the ceiling material is replaced. This is a fairly common occurrence in our schematics during upgrade.
