### ISSUE TITLE
1.16.3 Warehouse/Courrier issue

### ISSUE THREAD

**Issue by Danickar** [ldtteam/minecolonies#5920]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.3
- MineColonies Version: 0.13.348-BETA
- Structurize Version: 0.13.92-ALPHA
- Related Mods and their Versions:

## Expected behavior

Couriers make deliveries from the warehouse to needed huts.

## Actual behavior

The couriers run back and forth within the warehouse. Every now and then they run out to pick something up from a hut, but never make deliveries to the huts.

## Steps to reproduce the issue
Level 5 warehouse decided to upgrade storage with emeralds, then decided to hit the Sort button I had never noticed before. Since then the workers have done nothing. I know I have 4 emeralds left. When I look at the entire inventory of the warehouse using the Simple Storage Network I setup it shows only 4 emeralds. When I go looking in random racks I have seen a stack of 4 emeralds in at least 3 chests. I have noticed that this "duplicate" of items has occurred for other items in the warehouse as well but the total still shows correctly on the SSN.

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
You can't attach other storage networks to the warehouse, it messes stuff up. Disconnect the SSN, run /mc colony requestsystem-reset (your colony ID here), then sort the warehouse

**Comment by Danickar** [comment]
I will certainly try that, although I have had SSN attached the entire time and it worked perfectly before. Since it doesn't add any storage, just shows me what is in the storage of the racks the builder placed, how does that mess everything up? (Serious question not meant to sound sarcastic). I would understand the issue completely if it was trying to add/merge to sets of storage.

**Comment by Danickar** [comment]
I will certainly try that, although I have had SSN attached the entire time and it worked perfectly before. Since it doesn't add any storage, just shows me what is in the storage of the racks the builder placed, how does that mess everything up? (Serious question not meant to sound sarcastic). I would understand the issue completely if it was trying to add/merge to sets of storage.

**Comment by Raycoms** [comment]
I guess sorting with an SSN attached can cause weird desyncs.

**Comment by ravenbuilder934** [comment]
*facepalm* I thought SSN added storage (I've never used it before)

**Comment by Danickar** [comment]
Nah, SSN gives you an Applied Energistics type ME interface, but is just connected to whatever chests you have. It is great for dealing with warehouse stuff since I can see everything in one place.

**Comment by Danickar** [comment]
Ok, completely detached the SSN, did the reset command, tried sorting again. Everything still looks messed up inventory wise (emeralds in multiple places) and the couriers are all still standing around. I tried resetting them and firing/hiring them as well.

**Comment by Raycoms** [comment]
Weird, seems like the racks are disconnected from the warehouse now

**Comment by Danickar** [comment]
I should also throw in that I took out a few blocks and then used the building Repair option to have my builder reset everything and that didn't make a change to anything either.

**Comment by Raycoms** [comment]
If you click repair and the builder repairs it, does it fix it?

**Comment by Danickar** [comment]
No, the builder repairing doesn't change anything. Also looking around the warehouse it seems the single racks look sorted and like what I would expect them to. All of the double racks on the other hand are all a hot mess. I do not know if it is because they are double racks or if it is because only the double racks had their storage capabilities increased by using emeralds and that might be what caused the problem with everything.

**Comment by Raycoms** [comment]
the single one should've been extended too

**Comment by Danickar** [comment]
Then that makes this even more strange, because they were not extended.

**Comment by Inomutso** [comment]
Hi there

have the same behavior, no matter what I try with the Request System
this is already for a long time like that, even on 1.16.2 and 1.15.x

----

minecolonies-0.13.360-BETA-universal.jar
structurize-0.13.92-ALPHA-universal.jar
Forge is 1.16.3 - 34.1.20

obfuscate-0.5.0-mc1.16.3.jar (mr.crayfish)
cfm-7.0.0-pre19-mc1.16.3.jar (mr.crayfish) 
worldedit-forge-mc1.16.3-7.2.0-beta-05.jar
ImmersiveEngineering-1.16.3-4.0.1-121.jar

I have always tried to work/test with all these Request Issues, even with no other Mods activ

I have two Warehouses now (tried to fix Request Issues with that) and 8 Courier´s running

regards 

Inomutso
