### ISSUE TITLE
Request system not recognizing items in warehouse hut block

### ISSUE THREAD

**Issue by ravenbuilder934** [ldtteam/minecolonies#5922]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: MineColonies Official pack v2.9
- Structurize Version: MineColonies Official pack v2.9
- Related Mods and their Versions: none

## Expected behavior
The request system would recognize items in the warehouse hut block.

## Actual behavior
The request system ignores things in the warehouse hut block, even though couriers sometimes deposit things there and the sort button also puts things there.

## Steps to reproduce the issue

1. Put something in the warehouse hut block
2. Request it from the postbox
3. Request is marked as player-resolve

### Logs

- latest.log: I'm playing on the 1.15 patreon server so ask Wissi for the logs :P
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Pyrocantaes** [comment]
It doesn't only affect thins players deposit. It also means any crafter will also ignore anything in the ware house so if they havve recipes and materials they continually produce that item.. warehouse full of slabs, stairs, and iron picks as a result

**Comment by ravenbuilder934** [comment]
That's actually #5395, as it happens even when my hut block is full (and crafters can't put stuff in it).
