### ISSUE TITLE
Interacting with Builder, player gets booted from game

### ISSUE THREAD

**Issue by McArgent** [ldtteam/minecolonies#5924]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:  1.16.3
- MineColonies Version:  0.13.312-Beta
- Structurize Version:  0.13.90-Alpha
- Related Mods and their Versions:

## Expected behavior
I expect the conversation to close and go back to world view.  
I expect to get a chance to check builder inventory.  

## Actual behavior
When I start a conversation with a (specific) builder, or end a conversation with them, the game boots me from the server (my server on my local machine).  It should also be noted that my builder has a need bubble over their head that I'm trying to satisfy so they can continue upgrading the building they've been working on for a while now.  I've tried canceling that build (upgrade) and then restarting the request.  It's always that same builder.  The world doesn't crash, just my client.  
The builder is getting tasked with upgrading my (asian) library to level 2.  They're approximately 50% complete.  
The builder's hut is level 3.  

## Steps to reproduce the issue

1. Right click to interact with builder (crash sometimes happens as builder's skills are displayed)
2. Go through requests from builder needed to complete build project
3. Hit esc to exit list of required materials (if it hasn't crashed before this point, it will here)

### Logs

- latest.log: https://gist.github.com/McArgent/8608a719f45e6a4a6932b3f4cfa98548
- crashlog:  https://gist.github.com/McArgent/8608a719f45e6a4a6932b3f4cfa98548

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
You're a bit out of date - I'm about 99% sure that was fixed (I might be wrong! Worth upgrading to see though!)

**Comment by McArgent** [comment]
I was also able to fix it by firing the builder.  She picked up a job as a carpenter (very fitting).  
I'll try updating as well.  Thanks.
