### ISSUE TITLE
Builder do not consume Field block

### ISSUE THREAD

**Issue by PsychoBelka** [ldtteam/minecolonies#5925]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.3
- MineColonies Version: 0.13.345-ALPHA
- Structurize Version: 0.13.92-ALPHA

## Expected behavior
When building Field from schematic Builder is expected to place Field block, removing it from his inventory.

## Actual behavior
Field block remains in Builders inventory after he places it. 

## Steps to reproduce the issue

1. Place any Decorations/Field schematic
2. Supply builder with necessary resources and wait for him to finish construction
3. Inspect Builders inventory to confirm Field block duplication

## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
okay, this is a schematic issue, they have to be rescanned in 1.16. Works fine with new ones

**Comment by ravenbuilder934** [comment]
I've also noticed this in 1.15 though.

**Comment by Raycoms** [comment]
I fixed this relatively recently. I can't reproduce this anymore in 1.16 with newly scanned things.

**Comment by ravenbuilder934** [comment]
Oh, if you fixed it recently then that's ok-my instance was quite a few weeks ago
