### ISSUE TITLE
Builder requests item - RS doesn't recognise its been fulfilled.

### ISSUE THREAD

**Issue by Aduis1210** [ldtteam/minecolonies#5926]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

- Minecraft Version:1.15.2
- MineColonies Version: 0.13.349-Alpha
- Structurize Version:0.13.94-Alpha
- Related Mods and their Versions:

## Expected behavior
Builder requests item - Sawmill
Crafting system to complete a task once completed at sawmill and item is then taken of the request of the builder after delivery

## Actual behavior
Crafting system doesn't complete and I'm now left with 20 gray beds that the builder keeps requesting.

## Steps to reproduce the issue

1. request building to be built
2. Builder requests items not in warehouse, but are craftable.
3. item then gets crafted but request remains open
4. you now have lots of items being made that are not needed

### Logs
- latest.log: https://paste.ee/p/bQl8J

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Aduis1210** [comment]
Please also note, you have to go to the builder and manually stop the request - then they start building

**Comment by Raycoms** [comment]
duplicate #5395
