### ISSUE TITLE
1.15.2 Visitor entity set to zero pos, Condition check for transition

### ISSUE THREAD

**Issue by piesio98** [ldtteam/minecolonies#5927]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.349-ALPHA
- Structurize Version: 0.13.94-ALPHA
- Related Mods and their Versions:  https://gist.github.com/piesio98/800e10e633d96baa1fbb324c119cabaa

## Expected behavior
no spam

## Actual behavior
spam in console with:

Condition check for transition com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickingTransition@1c124242 threw an exception:
java.lang.NullPointerException: null ...

and

Visitor entity set to zero pos, report to mod author:
java.lang.Exception: null ....

## Steps to reproduce the issue

none 

### Logs

- latest.log: https://gist.github.com/piesio98/3b9c5c6a6081004ad8d57afe5a52c1dc
- crashlog: none

### Notes

This creates lag spikes.

I know that this issue was posted before (#5898 , #5002) but my is without crash and with additional error code.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Pyrocantaes** [comment]
I have this bug as well, but it's being reported relating to the control block for the Rancher. I get the report about every 30 seconds, and it appears to have no other effects other than preventing any children being born or visitors arriving at the Tavern, which is massively holding up my colony.
