### ISSUE TITLE
Citizens stay at home

### ISSUE THREAD

**Issue by Raveen222** [ldtteam/minecolonies#5929]
Minecraft: 1.15.2
Minecolonies: 0.13.349 alpha
Structurize: 0.13.94 alpha

Problem:
My citizens stay at home in the morning. They only go to work, if I'm near their houses (<15 Blocks).  
Their houses are level 1 spruce medieval citizen houses ( no changes).
I do not sleep at night. At daytime 00:00 I have to go to their houses. Else they will stay at home.
My citizens are not stuck. As soon as I'm near their houses (any daytime) they come out and do their duty. 
(Sorry for my english.)

**Comment by Raycoms** [comment]
this works very well in our enormous colonies. Are you sure you don't have low chunk loading distances, etc?

**Comment by MatthiasMann** [comment]
Might or might not be the same - but I have citizen getting stuck in houses too with the same version - but I think in my case it's related to the carpet around the bed (fortress citizen hut level 3). I can stand next to them and they won't move  - once I recall them in the house they work.

**Comment by Raycoms** [comment]
there is a pathfinding bug atm, with an open PR for it.

**Comment by Raveen222** [comment]
> this works very well in our enormous colonies. Are you sure you don't have low chunk loading distances, etc?

I tried some changes. No difference. The problem only exist in the morning. The citizens go to bed. Even if I'm not there.

**Comment by Raveen222** [comment]
I tried a little bit more and solved the problem. I moved optifine out of the mods folder - and the problem disappears.
Thank you for your food of thought.
