### ISSUE TITLE
[Request] Add miner handling for biomes o plenty stalagtites/stalagmites

### ISSUE THREAD

**Issue by ProsperCraft** [ldtteam/minecolonies#593]
Currently the miner doesn't know how to handle "rock formations" from biomes o plenty, if a ladder is supposed to go where one is, he doesn't place it, and falls to his death.

**Comment by Raycoms** [comment]
Does he throw something in the console about this?

Normally he should remove the stalagtite and add cobblestone

2017-02-14 16:14 GMT-02:00 ProsperCraft <notifications@github.com>:

**Comment by marvin-bitterlich** [comment]
I guess they are treated as solid but it is not possible to place a ladder against them. Maybe we should replace all behind-ladder-blocks with a ssfety-cobbler

**Comment by Raycoms** [comment]
We removed that? I added that we replace all of them?

2017-02-14 16:27 GMT-02:00 Marvin Hofmann <notifications@github.com>:

**Comment by ProsperCraft** [comment]
![2017-02-14_13 53 08](https://cloud.githubusercontent.com/assets/4427684/22944091/d8f334d6-f2ac-11e6-8cd8-a09a178d1490.png)

Here is an example.

**Comment by Raycoms** [comment]
and it doesn't show anything in the server log?

**Comment by marvin-bitterlich** [comment]
@Raycoms can we not just replace anything there is with cobble and ladder?

**Comment by Raycoms** [comment]
It should

**Comment by marvin-bitterlich** [comment]
@ProsperCraft is this still relevant?

**Comment by ProsperCraft** [comment]
I have not tried with a pack with BoP lately, but what I think could be done on it would be if it sees those blocks remove them.

**Comment by Raycoms** [comment]
Should be fixed.
