### ISSUE TITLE
1.16.3 Courier AI Issue

### ISSUE THREAD

**Issue by Laydralae** [ldtteam/minecolonies#5931]
After creating my first Postbox, I requested some items I was sure were in my warehouse. However, none of my requests were being added to the queue. After performing a restart of my client, the queue correctly showed the requested items. I cancelled some requests, but the Courier still tried to deliver them, leading to her notifying me to make this issue report and share the log file, located below via Pastee. 

https://paste.ee/p/kQHeV

**Comment by Talyda** [comment]
Please fill in the template to get help!
