### ISSUE TITLE
Citizens in houses wake up only when player near house 

### ISSUE THREAD

**Issue by tanaliko** [ldtteam/minecolonies#5933]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.347-BETA
- Structurize Version: 0.13.94-ALPHA 
- Related Mods and their Versions: The Endless Frontier 5.4 

## Expected behavior
Citizens wake up and goto to work from houses

## Actual behavior
Citizens wake up only when player close to house. Every morning need run circle around colony to wake up citizens 

[minecolonyWakeUp_e.zip](https://github.com/ldtteam/minecolonies/files/5392274/minecolonyWakeUp_e.zip)

## Steps to reproduce the issue

Sleep  far from houses and at morning citizens sleep at houses while player goto houses close 

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Do you have optifine installed?

**Comment by tanaliko** [comment]
Yes, named preview_OptiFine_1.15.2_HD_U_G1_pre30

**Comment by ravenbuilder934** [comment]
https://github.com/ldtteam/minecolonies/issues/5929

**Comment by Raycoms** [comment]
It was reported that this is apparently an optifine problem
