### ISSUE TITLE
Miner gets stuck before getting on ladder.

### ISSUE THREAD

**Issue by piotr-turek** [ldtteam/minecolonies#5935]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.3
- MineColonies Version: 0.13.348-BETA
- Structurize Version: 0.13.92-ALPHA
- Related Mods and their Versions: -

## Expected behavior

The miner should easily get on a ladder and climb up back to his hut block. 
## Actual behavior

Miner acts like he doesn't see the ladder hitbox, he is walking too close to the wall so the side of the ladder is blocking him from getting on the ladder :v

Photo: https://imgur.com/a/km62AWp
## Steps to reproduce the issue

1.  Build miner (Medieval Spruce style)
2.  Let him go down
3.  Wait till he gets stuck for the 100000th time

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Was fixed in the latest 1.15 afaik. Currently porting to 1.16 and releasing soon both jars
