### ISSUE TITLE
No Visitors Spawning since last Update

### ISSUE THREAD

**Issue by monster2mermaid** [ldtteam/minecolonies#5936]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.3
- MineColonies Version: 0.13.348-BETA
- Structurize Version: 0.13.92-ALPHA
- Related Mods and their Versions:

## Expected behavior
 Visitors spawning in the two taverns that I have that are level 3 as they were before this last update to the above Minecolonies and Structurize

## Actual behavior
Yep. Just not a single visitor in over an hour of gameplay with two taverns after the update to the versions above.

## Steps to reproduce the issue: 

1. Create Colony
2. Build Tavern
3. No visitors spawn

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by someaddons** [comment]
fixed in newest alpha

**Comment by monster2mermaid** [comment]
Hi Sam,

Vincentius says it looks like the newest ALPHA is expecting Minecraft 1.16.2
Here's what I got when I went to log in…
![Screen Shot 2020-10-17 at 2 41 44 PM](https://user-images.githubusercontent.com/72993594/96351090-32922500-1087-11eb-97e7-da68a973b030.png)

**Comment by Raycoms** [comment]
there should be another alpha for 1.16.3

**Comment by monster2mermaid** [comment]
Thanks!  He found it.
