### ISSUE TITLE
Minecolonies Config bug

### ISSUE THREAD

**Issue by Warrof** [ldtteam/minecolonies#594]
Version 0.6.2849

In the Minecolonies config, when I set Deliveryman Infinite Resources to False, I could no longer access my Builder's Inventory.  When I set Deliveryman Infinite Resources to True I regained access to my Builder's Inventory.

**Comment by marvin-bitterlich** [comment]
That is really weird. Is that reproduceable? If I remember correctly delmaninfres is currently not used anywhere

**Comment by Raycoms** [comment]
I just double checked it, it's not used anywhere.
It's just for decoration atm.

2017-02-14 18:50 GMT-02:00 Marvin Hofmann <notifications@github.com>:

**Comment by Warrof** [comment]
That was literally the only change I made before the Bug showed up.  I'll try to reproduce it.

**Comment by Warrof** [comment]
Odd... It hasn't shown up again in the couple attempts I just made...

Maybe it just a One-Off bug?  Or a combination of other bugs? Not that I noticed any.
