### ISSUE TITLE
Concrete mixer not working

### ISSUE THREAD

**Issue by ravenbuilder934** [ldtteam/minecolonies#5948]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: MineColonies Official pack v2.9
- Structurize Version: MineColonies Official pack v2.9
- Related Mods and their Versions: none

## Expected behavior
The builder would request concrete, and the concrete mixer would make it.

## Actual behavior
After several in-game days, the concrete still isn't made. The task shows up on the 2nd page of the concrete mixer's hut, but the concrete mixer is just standing there.

## Steps to reproduce the issue

1. Build a concrete mixer
2. Schedule a build that requires concrete
3. Put materials in warehouse

### Logs

- latest.log: This is on the 1.15 patreon server, unless you need client-side logs I'm not going to be of much help
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Mekle001** [comment]
Which style? I know that the spacewars style has this issue.

**Comment by ravenbuilder934** [comment]
Birch

**Comment by Mekle001** [comment]
Ok, yeah. Birch has the same issue as spacewars. I have a fix inbound.
