### ISSUE TITLE
herders don't do any damage

### ISSUE THREAD

**Issue by FoxxiePlayz** [ldtteam/minecolonies#5949]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: minecolonies-0.13.359-BETA-universal
- Structurize Version:structurize-0.13.94-ALPHA-universal
- Related Mods and their Versions: Craft To Exile [Dissonance] 2.5.3b

## Expected behavior

the herder will take their axe to butcher the animals and kill them, collect the loot and store it.

## Actual behavior

the herder deals no damage to animals, despite showing a harm effect. I tried all axes (even modded ones) using both unenchanted, sharpness and fire aspect, not even the fire procced however. I also tried different worlds, versions of minecolonies and none made a difference.

## Steps to reproduce the issue

1.  start a colony in any world
2.  get any herder (in my case, cow and sheep) and give them their preferred killing tool, an axe.
3.  the animals don't take damage and carry on with their lives

### Logs

- latest.log: 
- crashlog: 

### Notes

I am playing in the modpack Craft To Exile [Dissonance]
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
don't they ever kill them? On purpose they need quite a bunch of hits to kill them. They should be dealing low damage on low levels.

**Comment by FoxxiePlayz** [comment]
they never kill, they deal an absolute 0 damage, and enchantments dont trigger either.

**Comment by lucalattanzio97** [comment]
even with a wooden axe? maybe they are a level too low to use higher tier axes

**Comment by FoxxiePlayz** [comment]
I have tried wood throughout diamond and even some other modded axes, on different herders in different worlds and versions of the mod, none did damage.

**Comment by Raycoms** [comment]
what levels does this herder have?

**Comment by FoxxiePlayz** [comment]
I have tried building level 1,2 and 5, and worker level 1-10 and 49

**Comment by Raycoms** [comment]
Hmm, it seems to be there must be some mod in your modpack that causes this. Could you experiment removing them experimentally?

**Comment by FoxxiePlayz** [comment]
I'll try right now, and see if I can find out what mod is incompatible

**Comment by FoxxiePlayz** [comment]
I deleted mine n slash, and the herder can hurt animals, must be some confliction going on there

**Comment by Raycoms** [comment]
Yeah, must be a problem with mine n slash then. Maybe they disable fakeplayer damage to mobs?

**Comment by mahjerion** [comment]
Hey there, I'm one of the maintainers (taken over) of the Mine and Slash mod and this is something I'm interested in fixing. What exactly do you mean by fakeplayer damage?

**Comment by Raycoms** [comment]
Our workers create a fakeplayer to kill the cow, I wondered if that's an event mine and slash catches and cancels.

**Comment by RobertSkalko** [comment]
` final FakePlayer fp = FakePlayerFactory.getMinecraft((ServerWorld) worker.getEntityWorld());
            final DamageSource ds = DamageSource.causePlayerDamage(fp);`

Yeah they use fake player damage. I don't think i have anything disabling fake player damage so it's probably some other check. Gimme a few minutes.

**Comment by RobertSkalko** [comment]
Okay i'm pretty sure the problem is this. Minecolony creates a fakeplayer and forces it to deal damage as soon as it's "born". 
Fakeplayers are players, and mine and slash requires players to have energy to deal damage. 

I assume the fake players aren't in the player list so they don't get to regenerate energy?

Always at 0 energy, fake players get their attack canceled.

**Comment by Raycoms** [comment]
That makes sense

**Comment by zsy0073** [comment]
In the latest version 1.20.1, our server also encountered this issue, but we did not have the mine n slash mod. However, we added the curtain mod to create a dummy. Does the inability of the Wrangler to cause damage have anything to do with it?
