### ISSUE TITLE
Construction tape in a void world hangs the game

### ISSUE THREAD

**Issue by SimonMeskens** [ldtteam/minecolonies#595]
Version 0.6 Solid (0.6.2849)

On a skyblock map, if the construction tape is allowed in settings and the tape would be above the void, the game hangs indefinitely. Turning off construction tape in the settings fixes the issue.

**Comment by Raycoms** [comment]
@nojo121

2017-02-15 1:58 GMT-02:00 Simon Meskens <notifications@github.com>:
