### ISSUE TITLE
Colonist info/inventory panel bug

### ISSUE THREAD

**Issue by lucalattanzio97** [ldtteam/minecolonies#5952]
- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

- Minecraft Version: 1.16.1
- MineColonies Version: 0.13.258-ALPHA
- Structurize Version: 0.13.65-ALPHA
- Related Mods and their Versions: valhelsia-3 ver 3.0.20

## Expected behavior
being able to interact with colonists to verify if they need anything or just check their status/name

## Actual behavior
the panel with the info doesnt come out and they keep saying something each time i click on them. i can't access the inventory panel nor the info panel, and even the request panel doesnt pop up. everything else works: if they have the materials or the tools for the job, they work just fine...

## Steps to reproduce the issue
just right click a villager i guess...

### Notes
i posted a few hours ago the same issue on the valhelsia github but they removed my post and banned me... i then asked on discord and got sent here. (i previously searched both in the valhelsia threads and minecolonies threads but found nothing)

## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
remove optifine
