### ISSUE TITLE
Builder crashes games after closing requested materials menu

### ISSUE THREAD

**Issue by BrassMcCrafty** [ldtteam/minecolonies#5954]
https://gist.github.com/BrassHerbologist/87435159feee640f0b9370262ac3e5ef

minecolonies-0.13.360-BETA-universal.jar for 1.16.3

structurize-0.13.92-ALPHA-universal.jar for 1.16.3

How to recreate this error:
1-load a new world, place a townhall and start your colony to spawn citizens
2-place a builder hut, wait for the builder to be hired
3-choose schematic for builders hut then start the build
4-recall him to his station then open his dialogue
5-here he will show you a list of what he needs
*NOTE* average crash time: around 50% completed builders hut
talking to the builder when his build is 50% done (has happened at 0% upon the first material request but tends to show more around 50%)
6-closing his material request screen brings you to his stats
7-upon hitting this screen, the UI will freeze, the cursor will show low framefrate and choppy trail before 'saving world' appears
8-the game will crash and reveal this exit code:

The game crashed whilst mouseclicked event handler
Error: java.lang.NullPointerException: mouseClicked event handler
Exit Code: -1

I am not good to diagnosing errors but this as much info as I have to work with

**Comment by BrassMcCrafty** [comment]
H3lay I'm sorry if this doesn't suffice, I've never really reported mod errors officially

**Comment by Raycoms** [comment]
Some other mod you've added must be causing this. can you figure out which by selectively removing them?

**Comment by ravenbuilder934** [comment]
Optifine's installed, could it be that?

**Comment by Raycoms** [comment]
Unlikely, I suspect a tool mod.

**Comment by Raycoms** [comment]
@BrassHerbologist did you have time finding out which mod causes this?

**Comment by BrassMcCrafty** [comment]
I have Vanilla hammers and Easypaxel installed. Is there a way to make
these support minecolonies so they don't crash?

**Comment by Raycoms** [comment]
You should try it out without them and if it works fine without them, report it to these mods and say they are not setting up their tool types correctly.

**Comment by BrassMcCrafty** [comment]
Thank you and will do
