### ISSUE TITLE
Builder stuck in a loop between actions

### ISSUE THREAD

**Issue by ghost** [ldtteam/minecolonies#5958]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: minecolonies-0.13.364-ALPHA-universal
- Structurize Version: structurize-0.13.94-ALPHA-universal
- Related Mods and their Versions: Abnormals-Core-1.15.2-1.0.6.jar, AI-Improvements-1.15.2-0.3.0, Aquaculture-1.15.2-2.0.21, AutoRegLib-1.5-40, Bamboo-Blocks-1.15.2-1.4.1, BetterAdvancements-1.15.2-0.1.0.99, betteranimalsplus-1.15.2-10.0.0, BetterMineshaftsForge-1.15.2-1.3.1, betterwithminecolonies-1.15.2-1.15.16, blockcarpentry-1.15.1-0.8.1, BonsaiTrees-2.1.2.6, Bookshelf-1.15.2-5.6.40, BotanyPots-1.15.2-2.0.28, buildinggadgets-3.4.0, Buzzier-Bees-1.15.2-1.5.2, Charm-1.15.2-1.5.9, Charmonium-1.15.2-1.0.1, clayconversion-1.15.x-1.4.1, Clumps-5.0.2.6, collective-1.15.2-1.53, comforts-FORGE-1.15.2-2.0.0.4, config-2-3.0, Controlling-6.1.5.6, CookingForBlockheads_1.15.2-8.0.3, CosmeticArmorReworked-1.15.2-v3a, Cucumber-1.15.2-3.0.9, DoggyTalents-1.15.2-1.15.2.3, embellishcraft-1.15.2-2.2.1.0, enchantedbookredesign-2.0a, Enhanced-Mushrooms-1.15.2-v1.2.2, ExtendedNetherBackport-1.15.2-Beta-4.2, extlights-2.1, extraboats-1.3.6-1.15.2, fairylights-3.0.12-1.15.2, FastLeafDecay-v22.1, ftb-gui-library-1.0.0.14, ftb-quests-1502.0.2.251, gravestone-1.17.5, incubation-1.0.4-1.15.2, inventorysorter-1.15.2-17.0.0, item-filters-2.2.0.15, jei-1.15.2-6.0.3.15, JEIEnchantmentInfo-1.16.1-1.2.0, journeymap-1.15.2-5.7.0b3, jumbofurnace-1.15.2-1.0.0.2, JustEnoughResources-1.15.2-0.10.1.77, libnonymous-1.15.2-1.1.1.5, light-overlay-4.7.2, logprot-1.15.1-1.2, mapperbase-1.15.2-1.1.1.0, mcw-bridges-1.0.4fix-mc1.15.2, mcw-doors-1.0.1fix-mc1.15.1-2, mcw-furniture-1.0.1-mc1.15.1 1.15.2, mcws-roofs-1.15.2-v2.0.0, mcws-win-1.15.2-v1.0.2, MouseTweaks-2.13-mc1.15.1, OreExcavation-1.7.151, PackMenu-1.15.2-1.2.8, pamhc2crops-1.15.2-1.0.5, pamhc2foodcore-1.15.2-1.1.0, PickleTweaks-1.15.2-4.0.4, Placebo-1.15.2-3.1.0, preview_OptiFine_1.15.2_HD_U_G1_pre30, productivebees-1.15.2-0.4.1.4, projectvibrantjourneys-1.15.2-2.0.3, Quark-r2.1-245, QuarkOddities-1.15.2, randompatches-1.15.2-1.22.1.1, ReAuth-1.14-1.15-3.8.1, SoundFilters-0.14_for_1.15.2, starterkit_1.15.2-2.1, StorageDrawers-1.15.2-7.0.2, Strange-1.15.2-1.0.0-beta.5.hotfix1, swingthroughgrass-1.15.2-1.4.1, TextDamageIndicators-1.15.2-1.0.1, The-Endergetic-Expansion-1.15.2-v1.3.2, theoneprobe-1.15-2.0.7, TrashSlot_1.15.2-11.0.0, Upgrade-Aquatic-1.15.2-1.7.1, Uppers-0.2.12, Waystones_1.15.2-6.0.2

## Expected behavior

Builder gathers blocks/items and takes them to build site where the building is continued in construction.
## Actual behavior

The builder requests items then once they are fulfilled request more even when items are as of yet used. If one decides to only to fulfill one request the builder gets stuck in a loop of attempting to get the necessary resources and not having them. This holds true for once all request are full filled with the behavior repeating indefinitly. To add minor details the builder concludes its inventory is full after each cycle where it precedes to shuffle around the items that where given. In essence the builder gets stuck in an loop between gathering resources, going to build, not having the right items to inventory is full to gathering resources and finally going to build.

![2020-10-19_16 29 57](https://user-images.githubusercontent.com/73135060/96515878-b553e500-122b-11eb-85e7-58003c3e2074.png)
![2020-10-19_16 30 04](https://user-images.githubusercontent.com/73135060/96515886-b7b63f00-122b-11eb-8d91-c2fc541c6d24.png)
![2020-10-19_16 30 08](https://user-images.githubusercontent.com/73135060/96515896-bb49c600-122b-11eb-806c-fb3aa2519df7.png)
![2020-10-19_16 30 21](https://user-images.githubusercontent.com/73135060/96515898-bc7af300-122b-11eb-9523-f070ecc0fdac.png)
![2020-10-19_16 30 26](https://user-images.githubusercontent.com/73135060/96515912-c0a71080-122b-11eb-91a1-110d32576be7.png)
![2020-10-19_16 30 36](https://user-images.githubusercontent.com/73135060/96515919-c3096a80-122b-11eb-8d76-6b50f6d5345b.png)

## Steps to reproduce the issue

1.  Have a tavern 1 in fortress style
2.  Upgrade tavern to level 2
3. Wait for the builder reach a certain point
4. The builder fails to place blocks and enters the loop as stated above

### Logs

- latest.log: https://gist.github.com/Brent101Awesome/f1a867d0c1360604d7483005a8591ece#file-gistfile1-txt
- crashlog: 

### Notes

The builder's inventory is never full usually about half of it is empty
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ghost** [comment]
Issue #5883 is heavily related with different outcomes. Placing grass blocks is not done, however, the request for grass blocks does appear randomly during the events.

**Comment by ghost** [comment]
A temporary fix is to turn on infinite resources for a bit then wait until a small section is done then turn it back off. Grass block issue is also present.
![2020-10-19_17 31 10](https://user-images.githubusercontent.com/73135060/96519206-141c5d00-1232-11eb-8ba3-865e5303a4ff.png)

**Comment by ghost** [comment]
This issue appears to be the same as issue #5883 it is welcomed to be closed once analyzed.

**Comment by ghost** [comment]
I believe it is lantern's that cause the issue with them being treated as block instead of as torches since lanterns cannot be placed in midair and should be placed last in the build like torches are placed. I would recommend this behavior for all light sources to not have a possibility of  breaking with modded lights of similar design or if possible some code based around how lights connect to blocks.

**Comment by ravenbuilder934** [comment]
https://github.com/ldtteam/minecolonies/pull/5943
