### ISSUE TITLE
Valhelsia 3 modpack server builders AI broke. .

### ISSUE THREAD

**Issue by JaseKetrin** [ldtteam/minecolonies#5959]
Builders on server have been working fine since server was started. However on login today first the second builders AI informed it had encountered a problem. Builder2 stopped functioning properly. deconstructed builder2 and fired builder2. After that builder 1 started showing same message. Stopped server to pull log as message instructed to send to you. Included are latest, and debug logs ( was instructed to send you latest figured I'd send both.
 Minecolonies and structurize versions
structurize-0.13.65-ALPHA.jar
minecolonies-0.13.258-ALPHA-universal.jar

[latest.log](https://github.com/ldtteam/minecolonies/files/5406046/latest.log)l

[debug.log](https://github.com/ldtteam/minecolonies/files/5406045/debug.log)

**Comment by marchermans** [comment]
Please update you are running about 100 versions behind
