### ISSUE TITLE
[Request] Config option to specify minimum tool quality

### ISSUE THREAD

**Issue by SeriousCreeper** [ldtteam/minecolonies#596]
Heya,

would it be possible to add a config option to determine what the lowest tool quality the NPCs need is? 
For example, in my pack all wooden tools only have a durability of 1. To build stuff, the builder is asking for either wooden or gold tools. Gold tools would work, but also only have 32 durability. 

Telling builders to be able to use stone tools right away would be awesome. 

Thanks,
SC

**Comment by marvin-bitterlich** [comment]
This would mean adding config options for each tool level and at what worker/townhall/hutlevel it will work. We would have to make this config quite sophisticated I guess. 

Or we could just make a toggle to allow some tool levels all the time.

**Comment by Raycoms** [comment]
At the level 0 builder hut you need a bad tool, all the other workers will use at least stone. I think that's fair.
