### ISSUE TITLE
Latest Alpha issues - Sawmill not crafting

### ISSUE THREAD

**Issue by Aduis1210** [ldtteam/minecolonies#5965]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: minecolonies-0.13.370-ALPHA-universal
- Structurize Version:structurize-0.13.94-ALPHA-universal
- Related Mods and their Versions:

## Expected behavior
Requested items for crafting at the sawmill, gets crafted once items are collected.
## Actual behavior
Delivery men, supply goods and keep looping taking the item back and forward.
Sawmill doesnt reconise the items are delivered and the crafting function loops in the huts menu. from request to no request.

1. Update to latest Alpha
2. Attempt to request items from Sawmill
3. No actions taken.

### Notes
Please note, after downgrading to minecolonies-0.13.369-ALPHA-universal it worked like it should.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MatthiasMann** [comment]
I had the same issue where my builder requested 1 'plain horizontal dark oak cobblestone timber frame'.

1. The courier brought 1 dark oak plank and 1 cobble stone and nothing happened.
2. I canceled the request and a new one was made
3. An additional dark oak plank and cobble stone was brought to the saw mill - nothing happened.

I looked at the 2nd page of the sawmill hut and saw the typical task appearing and disappearing effect I had with the stone mason before (#5880) where this behavior was the result of not having enough materials to start crafting.
