### ISSUE TITLE
AI Issue with Deliveryperson

### ISSUE THREAD

**Issue by fightmesun** [ldtteam/minecolonies#5968]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 1.3.95 ALPHA
- Structurize Version: 0.13.3.9 ALPHA
- Related Mods and their Versions:

## Expected behavior
The deliveryperson doing their job instead of standing in front of the stash

## Actual behavior
The stand infront of the stash. They'll go home and come out when everyone else does but they do nothig else. 

![image](https://user-images.githubusercontent.com/46666382/96752422-4a1d2680-1383-11eb-9a8e-cf6c655193c2.png)

## Steps to reproduce the issue

1. Put object into Stash
2. Break Stash.
3. Repeat step 1 and 2 about 5 more times. 

### Logs

- latest.log: https://paste.atlauncher.com/view/f34b9665
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
You're running a very very old version, almost 300 versions behind. Update and see if it still occurs.
