### ISSUE TITLE
Recipe count incorrect on crafters

### ISSUE THREAD

**Issue by Aduis1210** [ldtteam/minecolonies#5971]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.15.2
- MineColonies Version: minecolonies-0.13.374-ALPHA-universal
- Structurize Version:structurize-0.13.94-ALPHA-universal
- Related Mods and their Versions:

## Expected behavior
Teaching recipes at crafters - with correct recipe count.

## Actual behavior
Recent update, has defaulted my stone crafter to 8 maximum recipes where the wiki states:
Building Level | Number of Recipes
-- | --
1 | 10
2 | 20
3 | 40
4 | 80
5 | 160

## Steps to reproduce the issue
1. update to latest alpha
2. check recipe count

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Now, it's one thing what the wiki stats, it's a different question if you can teach as many.
Could you teach more recipes than it said ingame?

**Comment by Aduis1210** [comment]
prior to the update. I was able to do allot more, but since the update. its now showing 12/8 recipes

**Comment by Aduis1210** [comment]
Sawmill level 4 = 22/16
Stone Mason level 3 = 12/8
Stone Smeltery level 3 = 4/8
crusher level 4 = 4/16
Sifter level 3 = 0/8
Library level 3 = 0/8

**Comment by Aduis1210** [comment]
just seems a bit low thats all

**Comment by Raycoms** [comment]
@nekosune small overlook here.

The original calculation was: return (Math.pow(2, buildingLevel) * EXTRA_RECIPE_MULTIPLIER) >= (learnedRecipes + 1);

The new calculation doesn't use the additional "crafter multiplier" 

(int) (Math.pow(2, getBuildingLevel()) * increase);

So, if the building "canCraftComplexRecipes" it has to be * EXTRA_RECIPE_MULTIPLIER additionally

**Comment by Aduis1210** [comment]
Mistakes happen :) - only noticed when one of my bigger projects needed more crafting

**Comment by Mekle001** [comment]
This is an interesting one. We originally had two formulas, and both were 'wrong' One had the right multiplier, but no research effect, the other had the research effect, but no multiplier.

**Comment by Aduis1210** [comment]
Also to mention, i dont have any recipe upgrades - im about to unlock one if you would like a update?

**Comment by FirzenDark** [comment]
Was this issue fixed? I notice after my update to Minecolonies V3 the allowable number and the how many recipes saved is turned around.

**Comment by Raycoms** [comment]
yes

**Comment by FirzenDark** [comment]
My Sawmill is on level 2 and suddenly the list of recipes shows after the update 40/20

**Comment by ravenbuilder934** [comment]
Update the individual MineColonies mod within the pack-the devs update so often, even the official modpack can't keep up
