### ISSUE TITLE
Server crashes

### ISSUE THREAD

**Issue by Ropay** [ldtteam/minecolonies#5972]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.16.3
- MineColonies Version:0.13.376-ALPHA
- Structurize Version:0.13.92-ALPHA
- Related Mods and their Versions:

## Expected behavior
My server shouldn't crash.

## Actual behavior
So when I log in with an account that is in my asian colony, which has all the buildings that were avaliable few weeks ago, the server can't keep up, and 1 tick takes 60 secs, the chunks won't load, and it crashes. But when I use another account, which is in another colony (a dark-oak), the server runs smoothly. Also, my friends can play without causing a crash, so the problem must be in my main colony.

## Steps to reproduce the issue

I don't know actually, I just teleported back to my main colony.

1. 
2. 
3. 

### Logs

- latest.log: https://gist.github.com/Ropay/edec6e5d324cb08ed8b797a2d5a80e58
- crashlog: https://gist.github.com/Ropay/eb5ff63b11815f4182f86dd9a66a6ced

### Notes
We were playing on version 1.16.1, but today, as quark came out on version 1.16.3, we decided to update the server. After I updated everything, and started the server, there were no problems until I moved back to my main colony.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Can you try executing /mc colony requestsystem-reset-all ?

**Comment by Ropay** [comment]
Didn't work unfortunately. It says this a dozen times: Owning field not considered because not loaded: BlockPos{x=-569, y=69, z=-349}

**Comment by Raycoms** [comment]
that's fine, that's not a problem. what did not work? the reset command, or is it still crahsing after the reset?

**Comment by Ropay** [comment]
It's still crashing after the reset.

**Comment by Ropay** [comment]
Crashlog: https://gist.github.com/Ropay/a89eea42799eb213db2840e7b6b3a9f7
Latest log: https://gist.github.com/Ropay/a0bd02971bc8c5f1b7689150b70b1360

**Comment by Raycoms** [comment]
That's a different crahs now though. And not related to us anymore

**Comment by Raycoms** [comment]
Did you do anything with this world? Port to a different version, remove mods or so?

**Comment by Ropay** [comment]
I added biomes o plenty, but nothing more. This issue appeared  after we upgraded from 1.16.1 to 1.16.3. It has to be related to minecolony, because it only occurs when I go to my asian colony.

**Comment by Raycoms** [comment]
I believe something in the 1.16.1 to 1.16.3 update progress messed with it then and corrupted some data around there.
Unfortunately there is nothing I can do there. The only thing that can be done to fix that is potentially delete the colony and remove all the building blocks and start over (maybe pasting the buildings to speed it up)

**Comment by Ropay** [comment]
Is there a way to save my citizens tho? Or anyway to speed up the building process? Like make the builder build the level 5 building at the start?

**Comment by Raycoms** [comment]
If you go into creative mode you can instantly place buildings at the level you want. And in citizen GUIs level the citizens up.

**Comment by Ropay** [comment]
Well then... it's goint to be this way. Thanks!
