### ISSUE TITLE
Builder Not Building

### ISSUE THREAD

**Issue by nm2588** [ldtteam/minecolonies#598]
### Minecolonies version

Curse version 0.6.4

### Expected behavior

Once the build request is selected in the hut menu, they construction tape should be placed and the builder will then begin building the building

### Actual behaviour

The build request is selected and the builder starts building but the blocks are not placed and disappear from his inventory.  Once the builder "completes" the build request, the construction tape is then placed around the building.

### Steps to reproduce the problem

1. Create build request
2. Watch builder try to build
3. Realize builder hasn't built
4. Turn in bug to github

Picture of completed Farmer 4 attached. 
![2017-02-15_12 14 14](https://cloud.githubusercontent.com/assets/25800036/22986566/066aace6-f37a-11e6-8240-c23e387ccfab.png)

**Comment by Raycoms** [comment]
Does this also happen in single player?

2017-02-15 15:27 GMT-02:00 nm2588 <notifications@github.com>:

**Comment by nm2588** [comment]
The builder is building in single player.  I will keep testing to make sure, but it looks like it is server side.
