### ISSUE TITLE
Height of buildings not correctly calculated for the removal of buildings

### ISSUE THREAD

**Issue by stepech** [ldtteam/minecolonies#5980]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 13.379
- Structurize Version: 13.94
- Related Mods and their Versions: None

## Expected behavior

FOUND 2 ISSUES!!
1) When I delete colony with comand /mc colony delete [id] true delete buildings, I expect most of the buldings to be completely deleted, if not all. I understand it's hard to keep track of all decorations, so I don't count that as bug, but normal buildings should be deleted entirely.
2) When I abandon colony during raid, the colony should be no longer mine and the raid hero bar should at least disappear, if not cancel the whole raid (here I understand that if you would cancel whole raid, people might abuse it, so ok..)

## Actual behavior

1) This is what happened when I deleted colony built entirely on dark oak schematics, everything on the "y" level of hut block and above gets succesfully deleted, but everything below just stays and sits there. Again, I don't count bridges and roads.
![2020-10-23_16 15 06](https://user-images.githubusercontent.com/29132060/97014798-1a207f80-154b-11eb-9923-d61b5d136e9d.png)
![2020-10-23_16 15 17](https://user-images.githubusercontent.com/29132060/97014807-1b51ac80-154b-11eb-804e-d885cf707a19.png)
![2020-10-23_16 15 26](https://user-images.githubusercontent.com/29132060/97014812-1c82d980-154b-11eb-9d2d-8c81e38c35fb.png)
![2020-10-23_16 15 37](https://user-images.githubusercontent.com/29132060/97014818-1d1b7000-154b-11eb-8074-f82f95675b88.png)

2) If I abandon colony during raid, there is no "logical" way for me to get rid of raid hero bar. I haven't really tried to do some experiments with this bug, but I suppose I have to kill the barbarians anyway, as the bar kept showing for really loooong time, even after reconnecting. Right now it already disappeared, but it would be nice to have it disappear when I abandon colony. May be let the raid proceed but delete the hero bar.

## Steps to reproduce the issue

Issue 1:
1. Build colony using dark oak scheme
2. Remove colony including buildings
3. Watch

Issue 2:
1. Wait for raid
2. Abandon colony
3. watch

### Logs

- latest.log: [server log](https://gist.github.com/stepech/567f768a65e90e1432ab6c90091c0476)
- crashlog: no crash log

### Notes

I am sorry to put 2 issues under 1 thread, I am under time pressure. I hope the second issue is small enought so that it's ok to put it here. Very sorry, it's great mod, you do great job and I love your update frequency and active development. Thanks.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Issue 1 is a problem yes. Issue 2, I wouldn't describe as one.
