### ISSUE TITLE
Pathfinding issue 1.15.2

### ISSUE THREAD

**Issue by perecnicek** [ldtteam/minecolonies#5981]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.15.2
- MineColonies Version:minecolonies-0.13.379-ALPHA-universal
- Structurize Version:structurize-0.13.94-ALPHA-universal
- Related Mods and their Versions:

## Expected behavior

Worked should use red road like others
## Actual behavior

worker dont wont use red road like other citizens. Instad he use blue road which is stupid and he cant pass that cliff and just standing up there at the edge also deliverman has the same problem but only with that hut down in circle others huts works well. Firstly he worked normally and used red road but now he only see that blue road.

![unknown](https://user-images.githubusercontent.com/46170414/97038896-ce320280-156b-11eb-8803-03c47a569854.png)

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
I wouldn't describe this as an issue since pathfinding must be limited. If we search too many blocks it will cause issues.
However, I'm 100% sure that this can be solved with significantly more waypoints (at least one waypoints every 10 blocks along the route they should take)
