### ISSUE TITLE
Farmer continuously requests hoe

### ISSUE THREAD

**Issue by Malorn44** [ldtteam/minecolonies#5983]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.** Or at the very least no solution I found online worked.

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.347-BETA-universal
- Structurize Version: 0.13.94-ALPHA-universal

## Expected behavior
The farmer should be tilling land and planting crops and should be satisfied when provided with the correct tools.

## Actual behavior
The farmer continuously requests hoes no matter how many he has. He has the correct level of hoe but will not do anything. He only stands next to the farm block. 

## Steps to reproduce the issue

I'm unsure. I am the first I found with this particular issue online. It happened to me the first time I created a farm  and happens regardless of which citizen I assign the job to.

### Logs

- latest.log: https://gist.github.com/Malorn44/e54c04308299a21887cb9ad94b9039d3

### Notes
If this has been fixed in a newer version then great, unfortunately, I am playing a modpack (Life in the Village 2) and will just have to wait for the modpack author to update.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Same as #5395
