### ISSUE TITLE
Problem on server

### ISSUE THREAD

**Issue by Sonmar03** [ldtteam/minecolonies#5985]
### Hello,
I installed Minecolonie on my server but I can't use it. When i'm in creativ mode, I can see all craft. But, when I want to put the Supply Ship/Camp, it's impossible.

**Error on consol :** 
[Server thread/FATAL] [net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Server
java.lang.ArrayIndexOutOfBoundsException: null

If you have a solution, thank you
_(Sry for my english)_

**Comment by someaddons** [comment]
fill out the template
