### ISSUE TITLE
Library students not gaining intelligence

### ISSUE THREAD

**Issue by ravenbuilder934** [ldtteam/minecolonies#5987]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: MineColonies Official pack v3.0
- Structurize Version: MineColonies Official pack v3.0
- Related Mods and their Versions: none

## Expected behavior
Library students would gain intelligence from working at the library

## Actual behavior
I left students in there for several in-game weeks, and they haven't gained any levels. Their home is level 5 and the library is level 4. I gave them several stacks of paper.

## Steps to reproduce the issue

1. Assign colonists to a library
2. Wait
3. 

### Logs

- latest.log: This is on the 1.15 patreon server, unless you need client logs I can't help
- crashlog: 

### Notes
The 3rd page of their GUI, where normally the skills affected by their job are, is blank.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
'The 3rd page of their GUI, where normally the skills affected by their job are, is blank.' this one here is correct.

But they should be gaining xp still.

**Comment by ravenbuilder934** [comment]
Nope, I've had one at level 4 for quite a while now

**Comment by Knaxia** [comment]
I also was thinking that I had that issue, but it just takes very long. I had to wait around 6 in-game days for 2 of my students to get +1 int with a level 3 library and with a normal influx of paper.

**Comment by ravenbuilder934** [comment]
Hmm, I think you're right-I checked again and the student at level 4 is now at level 5
