### ISSUE TITLE
Lumberjack Unable to Find Trees

### ISSUE THREAD

**Issue by djhajjar** [ldtteam/minecolonies#5994]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.3
- MineColonies Version: 0.13.386-alpha
- Structurize Version: 0.13.92-alpha
- Related Mods and their Versions: No other mods would interface in this.

## Expected behavior
Locate vanilla trees.

## Actual behavior
Unable to locate trees.

## Steps to reproduce the issue

1. Have forester block on edge of colony border.
2. Outside of border, grow vanilla tree. (in first encounter, 35 blocks away)
3. At a further distance away from the forester, inside of the colony borders, grow another tree. (in first encounter 50 blocks away)
4. Lumberjack appears to be in a "no tree found" state despite having a valid target within range.

### Logs

No logs available

### Notes
Only potential other mod that is interacting is Macaw's Bridges version 1.0.4-mc1.16.3 as a bridge has been placed to allow transversal over a ravine, but as demonstrated by a guard on patrol, a colonist is able to avoid the bridge altogether. Side note, colonists constantly jump on these bridges.

I am running a private server that is up 24/7 and can provide the twitch modpack and ip address if necessary.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Intentional, forester only gets tree within the colony borders

**Comment by ravenbuilder934** [comment]
Their second tree was inside the border

> At a further distance away from the forester, inside of the colony borders, grow another tree. (in first encounter 50 blocks away)

**Comment by Raycoms** [comment]
Depending on the building level there is a distance level for low levels.

**Comment by djhajjar** [comment]
What's the distance level then? Everything says 150 blocks with no scaling.

**Comment by ravenbuilder934** [comment]
I'll go update the wiki on that now

**Comment by Raycoms** [comment]
I can look into this again. But with a brief glimpse at the code the search-code continues fine. There are some factors that can limit the search but overally the calc is pretty straightforward. What you could test is, if you remove the tree outside the borders, will the Lj take the tree in the 50 blocks distance?

**Comment by djhajjar** [comment]
I'm currently checking, the day cycled

**Comment by djhajjar** [comment]
![2020-10-27_10 12 07](https://user-images.githubusercontent.com/35077250/97321485-eab88e00-183c-11eb-8b51-f196c445cf97.png)

the tree on teh left is 36 blocks away and the trees on the right are less than 50 blocks away; hut level 2

Edit: The Sappling visible in the middle of the screenshot was placed by the LJ after cutting down a tree

**Comment by Raycoms** [comment]
can you try to use a normal bridge, like made out of slabs or so?

**Comment by djhajjar** [comment]
![Uploading 2020-10-27_10.27.39.png…]()

Will try, though the guard does take it

**Comment by djhajjar** [comment]
![2020-10-27_10 27 39](https://user-images.githubusercontent.com/35077250/97323826-2e13fc00-183f-11eb-97a2-58addc541f86.png)

**Comment by djhajjar** [comment]
![2020-10-27_10 30 35](https://user-images.githubusercontent.com/35077250/97324092-77fce200-183f-11eb-9f9c-c6dc6b4dc793.png)

still reports unable to find trees

**Comment by djhajjar** [comment]
![2020-10-27_10 31 03](https://user-images.githubusercontent.com/35077250/97324180-8ba84880-183f-11eb-8907-2bc3a72b1f79.png)

and the bridge is in the border

**Comment by djhajjar** [comment]
![2020-10-27_10 32 39](https://user-images.githubusercontent.com/35077250/97324367-c14d3180-183f-11eb-8a05-4e2889a762dc.png)
there's also this tree
Edit: just measured distance, exactly 50 blocks

**Comment by djhajjar** [comment]
Turned on the restriction mode and the LJ found the trees he couldn't find before; but his pathing was a direct beeline for it and would not find the paths that the others were taking. He was also unable to get to the location as the beeline would have him go outside of the border. Have to go for now.

Also ignored the waypoints I placed.
