### ISSUE TITLE
Hospital hut block causes major lag spikes after placement

### ISSUE THREAD

**Issue by iCreamedUrPie** [ldtteam/minecolonies#5995]
I am running Minecolonies 0.13.386 and Structurize 0.13.92.
On minecraft 1.16.3
Also running Voxelmap 1.10.11
No other mods

I get intense lag spikes after I place down the fortress hospital hut block. I have tried to move the block to different locations, and have placed other hut blocks to try to recreate the issue, but it is specific to the hospital hut block

**Comment by ravenbuilder934** [comment]
Please fill out the template or at least provide the latest.log

**Comment by Raycoms** [comment]
a) template
b) Does it happen with other hut styles too?

**Comment by iCreamedUrPie** [comment]
Prerequisites:
 I am running the latest alpha version of MineColonies and Structurize for my Minecraft version.
 I checked the MineColonies/Structurize wiki and made sure my issue is not covered there.
 I made sure that this issue is not a duplicate of any existing issue.

Context:
Minecraft Version: 1.16.3
MineColonies Version: 0.13.386 Alpha
Structurize Version: 0.13.92 Alpha
Related Mods and their Versions: None

Expected behavior:
After I place down the Hospital hut block, I should not see a consistent FPS drop to 0 every 3 or 4 seconds.

Actual behavior:
After I place down a fortress hospital hut block, I receive lag spikes every 3 or 4 seconds.

Steps to reproduce the issue:
Place a fortress type hospital hut block and experience lag spikes.

Notes:
I tried restarting MC, and my computer. I also placed down other hut blocks to try to recreate the issue, but it seems to be specific to the hospital hut block.

I will try with a different type (such as acacia hospital). And if you need any logs as well

**Comment by Raycoms** [comment]
I looked into this. I think this is because the hospital block has a relative "complex" model which on weaker gpus/cpus is causes some issues. However, I tested this exhaustively and it should not be responsible for those extremely low drops.

**Comment by Talyda** [comment]
Had someone on discord with this same problem - couldn't remember where I had seen it reported before! They were on mcol .547 and structurize .104 - fortress hospital block as well, completely lagged them out and chewed up their memory. They gave the game 1 gig more memory and it didn't stop, then gave it another 1 gig before it stopped (they had assigned 4 to the game, ended up with 6 to stop the hospital block lag)
