### ISSUE TITLE
Builder and Miner hut blocks randomly become unusable with block missing error

### ISSUE THREAD

**Issue by Starshak3r** [ldtteam/minecolonies#6006]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: minecolonies-0.13.383-ALPHA-universal
- Structurize Version: structurize-0.13.94-ALPHA-universal
- Related Mods and their Versions: 
[✔️] Abnormals-Core-1.15.2-1.0.6
  [✔️] AmbientSounds_v3.0.20_mc1.15.2
  [✔️] Aquaculture-1.15.2-2.0.16
  [✔️] BiomesOPlenty-1.15.2-10.0.0.366-universal
  [✔️] Bountiful-1.15.2-3.1.2
  [✔️] craftingstation-3.1.0
  [✔️] CraftTweaker-1.15.2-6.0.0.24
  [✔️] Cucumber-1.15.2-3.0.9
  [✔️] FastLeafDecay-v22
  [✔️] FruitTrees-1.15.2-1.5.2
  [✔️] furniture-7.0.0-pre16-1.15.1
  [✔️] goblintraders-1.2.0-1.15.2
  [✔️] Harvest-forge-1.15.1-1.2.11-24
  [✔️] Hwyla-forge-1.10.8-B72_1.15.2
  [✔️] immersive-portals-0.24forMc1.15withForge
  [✔️] inventorysorter-1.15.2-17.0.0
  [✔️] ironchest-1.15.2-10.0.3
  [✔️] jei-1.15.2-6.0.2.12
  [✔️] jeiintegration_1.15.2-3.1.0.1
  [✔️] journeymap-1.15.2-5.7.0b3
  [✔️] Kiwi-1.15.2-2.8.2
  [✔️] Kottle-1.5.2
  [✔️] Ma-Essentials-1.15.2-3.1.1
  [✔️] Mekanism-1.15.2-9.10.9.422
  [❌] minecolonies-0.13.359-BETA-universal.jar (disabled)
  [✔️] minecolonies-0.13.383-ALPHA-universal
  [✔️] mining-helmet-1.15.2-1.0.8
  [✔️] MixinBootstrap-1.0.3
  [✔️] morecharcoal-1.15.2-1
  [✔️] MouseTweaks-2.13-mc1.15.1
  [✔️] MysticalAdaptations-1.15.2-1.2.3
  [✔️] MysticalAgradditions-1.15.2-3.0.1
  [✔️] MysticalAgriculture-1.15.2-3.0.10
  [✔️] NaturesAura-28.4
  [✔️] OreExcavation-1.7.151
  [✔️] pamhc2crops-1.15.2-1.0.5
  [✔️] pamhc2foodcore-1.15.2-1.0.9
  [✔️] pamhc2trees-1.15.2-1.0.5
  [✔️] Patchouli-1.15.2-1.2-35
  [✔️] PickleTweaks-1.15.2-4.0.4
  [✔️] Placebo-1.15.2-3.1.0
  [✔️] randompatches-1.15.2-1.22.1.1
  [✔️] refinedstorage-1.8.8
  [✔️] SereneSeasons-1.15.2-3.0.0.74-universal
  [✔️] SilentGear-1.15.2-1.8.2+109
  [✔️] SilentGems-1.15.2-3.5.5+88
  [✔️] SilentLib-1.15.2-4.6.6+59
  [✔️] SilentMechanisms-1.15.2-0.8.0+59
  [✔️] simplefarming-1.15.2-1.3.0
  [✔️] SolarFluxReborn-1.15.2-15.2.3
  [✔️] StorageDrawers-1.15.2-7.0.2
  [✔️] structurize-0.13.94-ALPHA-universal
  [✔️] sweetconcrete-1.15.2-1.7.1
  [✔️] swingthroughgrass-1.15.2-1.4.0
  [✔️] The-Endergetic-Expansion-1.15.2-v1.3.2
  [✔️] u_team_core-1.15.2-3.0.1.164
  [✔️] useful_backpacks-1.15.2-1.10.1.70
  [✔️] valhelsia_structures-15.0.3a
  [✔️] WailaHarvestability-mc1.15.2-1.1.12

## Expected behavior
I would click the builder hut and be able to interact with the hut or upgrade etc 

## Actual behavior
hut block gives an error saying [CHAT] This block is missing its respective building, try restarting or loading a backup! 

https://cdn.discordapp.com/attachments/620499986349555742/769574940901900328/2020-10-24_10.52.27.png 

## Steps to reproduce the issue

1. Open game, log in to the server and spawn at the colony 
2.  click on builder or miner hut block 
3. get error listed above 

### Logs

- latest.log: https://gist.github.com/Starshak3r/d4bf57bbfaf5c490ed0a308166f727fd 
- crashlog: N/A 

### Notes

MultiMC version: 0.6.11-1430

This only seems to happen on a private server, but only to me so far, but since we haven't opened up to testers yet I can't verify that I am the only one who is having the issue, but the server owner hasn't noticed it on his colony. I also verified that this issue happens regardless of which schematic set I use for builder and miner. I haven't noticed any other building having this issue as of yet.. 

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
What's the expected and actual behavior? How can you reproduce this? Also, please provide logs.

**Comment by Raycoms** [comment]
does this solve itself after some seconds?

**Comment by Starshak3r** [comment]
not really. It will partially sort itself for a few minutes if I start a new project, but I still cant' use the GUI or give the builder his requests

**Comment by Starshak3r** [comment]
I should have also noted that it happens on the BETA version as well (which is why it's in the modlist, disabled) but didn't happen on the most recent 1.15.2 Release version prior our updating on the server. And it's really confusing me that it only happens on the server and hasn't happened at all with either Beta or Alpha version on my single player world

**Comment by someaddons** [comment]
need client and server logs on this

**Comment by Raycoms** [comment]
@Starshak3r are you sure there is not a mod-mismatch from client to server?

**Comment by Starshak3r** [comment]
there shouldn't be unless there was some miscommunication between the owner and myself, but I will ask him for the log and double check that asap
I created the initial mod pack that we are running myself so unless he updated to a different version than I specified we should be in sync

**Comment by Raycoms** [comment]
@Starshak3r figure dit out?

**Comment by Starshak3r** [comment]
Unfortunately, no.
My server owner is MIA for some reason right now so I haven't been able to get the logs from him. I am sure it is like you are thinking, a mod/client mismatch but I won't be able to verify that until he answers my messages.

**Comment by Raycoms** [comment]
@Starshak3r updates?

**Comment by Starshak3r** [comment]
was in fact due to a mismatch.

I will mark as closed

**Comment by Starshak3r** [comment]
issue caused by client server mismatch. 
 *newer client version than server.*
