### ISSUE TITLE
Mod minecolonies requires structurize 0.13.66-ALPHA

### ISSUE THREAD

**Issue by kmo093** [ldtteam/minecolonies#6007]
My version is 1.16.3 I just installed the new update but I get the following error
29.10 18:34:30 [Server] INFO net.minecraftforge.fml.ModLoadingException: Mod minecolonies requires structurize 0.13.66-ALPHA
29.10 18:34:30 [Server] INFO Currently, structurize is 0.13.92-ALPHA
the version that it says it requires is minecraft 1.16.2 and it is a slightly older version than the one I currently use, could you please review it
Minecolonies version used is minecolonies-0.13.398-ALPHA-universal.jar

**Comment by ravenbuilder934** [comment]
So you have https://www.curseforge.com/minecraft/mc-mods/minecolonies/files/3096421 and https://www.curseforge.com/minecraft/mc-mods/structurize/files/3071945?

**Comment by kmo093** [comment]
yes, Those are the ones that I have on the server but when it tries to start the error shown above appears

**Comment by ravenbuilder934** [comment]
Which ones do you have on the client?

**Comment by kmo093** [comment]
the server and the client use the same mods, the version is forge 1.16.3-34.1.23

**Comment by ravenbuilder934** [comment]
And you don't have duplicate Minecolonies or duplicate Structurize on either the server or the client?

**Comment by kmo093** [comment]
nop
