### ISSUE TITLE
Could not find net.minecraftforge:forge:1.15.2-31.2.33_mapped_snapshot_20200606-1.15.1_at_cb2c348669d4247ac6bd90d0f130be6a4cde8e4c.

### ISSUE THREAD

**Issue by LookUpPls** [ldtteam/minecolonies#6008]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.15.2 and 1.16
- MineColonies Version:
- Structurize Version:

## Problem description

BUILD FAILED in 1m 30s
1 actionable task: 1 executed
Could not find net.minecraftforge:forge:1.15.2-31.2.33_mapped_snapshot_20200606-1.15.1_at_cb2c348669d4247ac6bd90d0f130be6a4cde8e4c.
Searched in the following locations:
  - https://jcenter.bintray.com/net/minecraftforge/forge/1.15.2-31.2.33_mapped_snapshot_20200606-1.15.1_at_cb2c348669d4247ac6bd90d0f130be6a4cde8e4c/forge-1.15.2-31.2.33_mapped_snapshot_20200606-1.15.1_at_cb2c348669d4247ac6bd90d0f130be6a4cde8e4c.pom
  - https://jcenter.bintray.com/net/minecraftforge/forge/1.15.2-31.2.33_mapped_snapshot_20200606-1.15.1_at_cb2c348669d4247ac6bd90d0f130be6a4cde8e4c/forge-1.15.2-31.2.33_mapped_snapshot_20200606-1.15.1_at_cb2c348669d4247ac6bd90d0f130be6a4cde8e4c.jar
  - https://repo.maven.apache.org/maven2/net/minecraftforge/forge/1.15.2-31.2.33_mapped_snapshot_20200606-1.15.1_at_cb2c348669d4247ac6bd90d0f130be6a4cde8e4c/forge-1.15.2-31.2.33_mapped_snapshot_20200606-1.15.1_at_cb2c348669d4247ac6bd90d0f130be6a4cde8e4c.pom
  - https://repo.maven.apache.org/maven2/net/minecraftforge/forge/1.15.2-31.2.33_mapped_snapshot_20200606-1.15.1_at_cb2c348669d4247ac6bd90d0f130be6a4cde8e4c/forge-1.15.2-31.2.33_mapped_snapshot_20200606-1.15.1_at_cb2c348669d4247ac6bd90d0f130be6a4cde8e4c.jar
  - https://ldtteam.jfrog.io/ldtteam/modding/net/minecraftforge/forge/1.15.2-31.2.33_mapped_snapshot_20200606-1.15.1_at_cb2c348669d4247ac6bd90d0f130be6a4cde8e4c/forge-1.15.2-31.2.33_mapped_snapshot_20200606-1.15.1_at_cb2c348669d4247ac6bd90d0f130be6a4cde8e4c.pom
  - https://ldtteam.jfrog.io/ldtteam/modding/net/minecraftforge/forge/1.15.2-31.2.33_mapped_snapshot_20200606-1.15.1_at_cb2c348669d4247ac6bd90d0f130be6a4cde8e4c/forge-1.15.2-31.2.33_mapped_snapshot_20200606-1.15.1_at_cb2c348669d4247ac6bd90d0f130be6a4cde8e4c.jar
  - file:/C:/JAVA/MC/minecolonies/libs/forge-1.15.2-31.2.33_mapped_snapshot_20200606-1.15.1_at_cb2c348669d4247ac6bd90d0f130be6a4cde8e4c.jar
  - file:/C:/JAVA/MC/minecolonies/libs/forge.jar
  - https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.15.2-31.2.33_mapped_snapshot_20200606-1.15.1_at_cb2c348669d4247ac6bd90d0f130be6a4cde8e4c/forge-1.15.2-31.2.33_mapped_snapshot_20200606-1.15.1_at_cb2c348669d4247ac6bd90d0f130be6a4cde8e4c.pom
  - https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.15.2-31.2.33_mapped_snapshot_20200606-1.15.1_at_cb2c348669d4247ac6bd90d0f130be6a4cde8e4c/forge-1.15.2-31.2.33_mapped_snapshot_20200606-1.15.1_at_cb2c348669d4247ac6bd90d0f130be6a4cde8e4c.jar
  - file:/C:/Users/42527/.gradle/caches/forge_gradle/bundeled_repo/net/minecraftforge/forge/1.15.2-31.2.33_mapped_snapshot_20200606-1.15.1_at_cb2c348669d4247ac6bd90d0f130be6a4cde8e4c/forge-1.15.2-31.2.33_mapped_snapshot_20200606-1.15.1_at_cb2c348669d4247ac6bd90d0f130be6a4cde8e4c.pom
  - file:/C:/Users/42527/.gradle/caches/forge_gradle/bundeled_repo/net/minecraftforge/forge/1.15.2-31.2.33_mapped_snapshot_20200606-1.15.1_at_cb2c348669d4247ac6bd90d0f130be6a4cde8e4c/forge-1.15.2-31.2.33_mapped_snapshot_20200606-1.15.1_at_cb2c348669d4247ac6bd90d0f130be6a4cde8e4c.jar
  - https://libraries.minecraft.net/net/minecraftforge/forge/1.15.2-31.2.33_mapped_snapshot_20200606-1.15.1_at_cb2c348669d4247ac6bd90d0f130be6a4cde8e4c/forge-1.15.2-31.2.33_mapped_snapshot_20200606-1.15.1_at_cb2c348669d4247ac6bd90d0f130be6a4cde8e4c.jar
  - https://repo.maven.apache.org/maven2/net/minecraftforge/forge/1.15.2-31.2.33_mapped_snapshot_20200606-1.15.1_at_cb2c348669d4247ac6bd90d0f130be6a4cde8e4c/forge-1.15.2-31.2.33_mapped_snapshot_20200606-1.15.1_at_cb2c348669d4247ac6bd90d0f130be6a4cde8e4c.pom
  - https://repo.maven.apache.org/maven2/net/minecraftforge/forge/1.15.2-31.2.33_mapped_snapshot_20200606-1.15.1_at_cb2c348669d4247ac6bd90d0f130be6a4cde8e4c/forge-1.15.2-31.2.33_mapped_snapshot_20200606-1.15.1_at_cb2c348669d4247ac6bd90d0f130be6a4cde8e4c.jar
Required by:
    project :
22:15:11: Task execution finished 'prepareRunClient'.
### Notes or related things

help me please
---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
do some gradle refreshes that should solve it.

**Comment by LookUpPls** [comment]
No matter use, I refreshed gradle   @Raycoms

**Comment by Raycoms** [comment]
It's not really a Minecolonies issue since it's trying to query a forge version/mapping. However, that one works fine for us. 
So I'm not sure what to tell you here.

Gradle has its "issues" quite often, so querying back and forth etc usually ends up solving it.

**Comment by LookUpPls** [comment]
https://forums.minecraftforge.net/topic/93143-could-not-find-netminecraftforgeforge1163-34135_mapped_snapshot_20201028-1163/
solved in there. this is a problem of gradle. thanks
