### ISSUE TITLE
No loot in vanilla Minecraft chests

### ISSUE THREAD

**Issue by Sunekaer** [ldtteam/minecolonies#6009]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.16.3 forge-34.1.25
- MineColonies Version: 0.13.360-BETA
- Structurize Version: 0.13.92-ALPHA
- Related Mods and their Versions: ChanceCubes-1.16.3-5.0.2.394

## Expected behavior
To be loot in the chests from structures 

## Actual behavior
Any structure that generates a vanilla Minecraft chest with possible loot in it doesn't contain anything.

## Steps to reproduce the issue
Install forge, chancecubes, minecolonies and structurize 
Start the instance and create a world
Go to a mineshaft and find a chest 
No loot in chest 

### Logs
- latest.log: https://paste.feed-the-beast.com/view/9b40127a

### Notes
Im not sure if its you guys or chance cubes there is doing something wrong.. but having both mods in a pack is causing the issue

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Not us. Works fine with just us, other mod must be causing this.

**Comment by Raycoms** [comment]
Our 1.16 is also out for a while already without ever getting this report.

**Comment by marchermans** [comment]
I tested this myself
Minecolonies + Structurize + Mineshaft = Filled chests.
As such not reproducible and i am 99% sure this is not is.

**Comment by WenXin20** [comment]
It's most likely being caused by Chance Cubes: TheTurkeyDev/ChanceCubes#225
Or maybe a combination of this mod and chance cubes.

**Comment by lulabyte** [comment]
Can confirm seems to be Chance Cubes, maybe a conflict with Botania
