### ISSUE TITLE
Right clicking a Composter Barrel with an Empty Hand Crashes the Game in 1.15.2

### ISSUE THREAD

**Issue by BestBluePenguin** [ldtteam/minecolonies#6010]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.31 Release
- Structurize Version: 1.15.2 - 1.10.0
- Related Mods and their Versions: Xaeros Minimap 20.12.2, jei 6.0.0.4, XaerosWorldMap 1.7.0

## Expected behavior

Nothing
## Actual behavior

The game freezes then crashes

## Steps to reproduce the issue

1. right-click the composter barrel with an empty hand.
2. ????
3.  game crashes (profit?)

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MatthiasMann** [comment]
You are using *very* old versions - update.
