### ISSUE TITLE
Courier doesn't deposit in warehouse

### ISSUE THREAD

**Issue by Aduis1210** [ldtteam/minecolonies#6012]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version:minecolonies-0.13.390-ALPHA-universal - was 0.13.394
- Structurize Version:structurize-0.13.94-ALPHA-universal
- Related Mods and their Versions:

## Expected behavior
Stores items correct as mod intends

## Actual behavior
my courier is only using the original half of the warehouse to store - the building is level two currently
in addition, when he stores items, he gets stuck with items still in their inventory

## Steps to reproduce the issue
1. Build warehouse
2. upgrade warehouse to level two
3. Courier gets stuck with items they are trying to deposit into warehouse second section.

### Logs
 - Logs do not show error

### Notes
This was fixed by down grading my Alpha to 0.13.390

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Aduis1210** [comment]
Seems to be affected by the update: 0.13.391 and above

**Comment by DrFlash99** [comment]
Same issue here, but in my case Medival spruce warehouse, level 5 with several emerald block upgrades. There is plenty of space in the racks, but the NPC's act as if the warehouse is full - not clearing their inventory, and just standing there. Version 0.13.394

**Comment by Knaxia** [comment]
I had that problem on 0.13.394-ALPHA, but sometimes just using the "sort" option in the warehouse fixed it for a limited time. Now I updated to 0.13.409-ALPHA and it's the other way around. They all go to the warehouse, empty themselves but never restock or go on their normal way to pick up or deliver stuff. They just all stay at the warehouse with empty inventory.

I tried: 
-restarting the request system
-Going to each courier's hut, recall, pause and restart each of my 4 courier
-fire, hire, recall, same thing.
-Adding some random things in their inventory, but they would deposit it and stop there.

Nothing worked, they all went back to standing at the warehouse, doing nothing with empty inventory.

**Comment by Aduis1210** [comment]
> I had that problem on 0.13.394-ALPHA, but sometimes just using the "sort" option in the warehouse fixed it for a limited time. Now I updated to 0.13.409-ALPHA and it's the other way around. They all go to the warehouse, empty themselves but never restock or go on their normal way to pick up or deliver stuff. They just all stay at the warehouse with empty inventory.
> 
> I tried:
> -restarting the request system
> -Going to each courier's hut, recall, pause and restart each of my 4 courier
> -fire, hire, recall, same thing.
> -Adding some random things in their inventory, but they would deposit it and stop there.
> 
> Nothing worked, they all went back to standing at the warehouse, doing nothing with empty inventory.

Just tried updating to latest alpha, still same issue - downgraded back to 390
