### ISSUE TITLE
Fortress Walls Rotate When Upgraded

### ISSUE THREAD

**Issue by ArcusMG** [ldtteam/minecolonies#6016]
### Prerequisite
- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 
- Minecraft Version:1.16.3
- MineColonies Version: 0.13.398-ALPHA
- Structurize Version: 0.13.92-ALPHA
- Related Mods and their Versions: forge 34.1.25, JEI 1.163.-7.6.0.49

## Expected behavior
Had the builder build a fortress wall 4 decoration. Upgraded it and expected it to be in the same orientation. 

## Actual behavior
Every time I try to upgrade fortress wall 4 from level 1 up to level 2, it’s rotated 90 degrees. I didn’t try it on all the other walls but it also happens on wall 3

## Steps to reproduce the issue
1. Have builder build decoration fortress wall 4 or 3 (maybe others as well, those are the only two I tested)
2. Have the builder upgrade from level 1 to 2
3. Wall should be rotated 90 degrees from how it started. 

### Logs
- latest.log: https://gist.github.com/praus1/f8d5bd6349df112aaa1101c6afe1baea
- crashlog: N/A

### Notes
I first encountered this in the FTB unstable pack but I tried in a totally empty Minecraft install with just the forge version, JEI, and the latest Alpha of Minecolonies and Structurize and got the same behavior. 

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Which fortress wall?

**Comment by ArcusMG** [comment]
> Which fortress wall?

The fortress walls in decorations. I tested wall 3 and wall 4. I used the build tool to select decorations and then walls/fortress, then wall 3 or wall 4. 
![954A5FE7-AA28-4951-A5E6-378B9A4891DA](https://user-images.githubusercontent.com/20156689/97795833-7aa56180-1bc8-11eb-8a4e-3909bf4a1aaf.jpeg)
