### ISSUE TITLE
updated minecolonies official modpack, now miner wont eat or mine, also have to restart builders all the time.

### ISSUE THREAD

**Issue by TawnyaBuster** [ldtteam/minecolonies#6017]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.15.2
- MineColonies Version:0.13.379
- Structurize Version:0.13.94
- Related Mods and their Versions:

## Expected behavior
<the miner would mine and eat when necessary, builders would go to next task.

## Actual behavior
<the miner just stands there and starves until you fire him. then he eats and goes about regular life. until you hire him back. or another npc. the builders just finish a task and start another, but never leave builder hut to do next task. have to pause and restart them.
Try to give as much detail as possible here to help us properly understand the issue. -->

## Steps to reproduce the issue

1. <not sure what versions i was playing before. using the minecolonies official modpack, but bugs came with update.
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Which version of the modpack did you update to?

**Comment by TawnyaBuster** [comment]
not sure if extreme hunger bug is the culprit. miner wont work or do anything at all. not even eat. until you fire him. then he acts normally. give it another job elsewhere i.e. smelter, works just fine. just not miner.

**Comment by WrongWeekend** [comment]
I have this same issue with the latest alpha and I'm not using extreme hunger or any other mods (except tetra which doesn't affect food/hunger at all)
