### ISSUE TITLE
Extreme Hunger Bug

### ISSUE THREAD

**Issue by BellePullman** [ldtteam/minecolonies#6018]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.3
- MineColonies Version: 0.13.410
- Structurize Version: 0.13.92
- Related Mods and their Versions:

## Expected behavior

Colonists eating
## Actual behavior

Colonists not eating - even the cook with loads of food in their inventory, 0 hunger, hunger particles, not eating.

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
duplicate, fix upcoming #6017
