### ISSUE TITLE
different names in documentation and ingame

### ISSUE THREAD

**Issue by linwetalion** [ldtteam/minecolonies#6022]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

Minecraft Version: 1.16.3
MineColonies Version: 0.13.401-BETA-universal
Structurize Version:0.13.92-ALPHA-universal
Related Mods and their Versions:forge 34.1.35

## Problem description
here it is called "forester hut"
https://wiki.minecolonies.ldtteam.com/source/buildings/forester
and ingame it is called luberjack hut.

pls fix

### Notes or related things

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
They've said somewhere that it would break a lot of stuff to change that now, so will probably do it in 1.17 (maybe)

**Comment by Raycoms** [comment]
yep

**Comment by Raycoms** [comment]
Most huts ingame are called forester too

**Comment by ravenbuilder934** [comment]
I'm assuming you mean the schematic name, not the hut block itself? Yeah, it would break a lot of stuff to change that now
