### ISSUE TITLE
Request System Bug

### ISSUE THREAD

**Issue by ArchEzekiel** [ldtteam/minecolonies#6023]
[latest.log](https://github.com/ldtteam/minecolonies/files/5473065/latest.log)
In MC Version 1.15.2, Minecolonies version: "minecolonies-0.13.81-RELEASE-universal", a bug arose with the request system right after the time I tried sleeping in a Hammock in the Comforts mod, version "comforts-FORGE-1.15.2-2.0.0.4" 

Let me know if you have any questions

**Comment by ArchEzekiel** [comment]
Update: The deliverywoman's AI will walk her to the Stash, but she wont actually pick up anything out of it, and a request for her to pick it up doesnt seem to be being added to the system (At least as I can tell from the clipboard

**Comment by MatthiasMann** [comment]
You are using a very old version - update to the latest alphas.
