### ISSUE TITLE
Cannot Craft Certain buildings

### ISSUE THREAD

**Issue by MisterChester77** [ldtteam/minecolonies#6024]
### Prerequisites 

- [] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: minecolonies-0.13.405-BETA-universal
- Structurize Version: structurize-0.13.94-ALPHA-universal
- Related Mods and their Versions:

## Expected behavior

Able to craft University, ware house and others.
## Actual behavior

I cannot craft university, warehouse and others. They do not show up as recipes on JEI and I cannot craft them by placing the items on a crafting bench.  Also Forester hut block seems to be missing texture. More over I'm having this issue since previous versions of the mod.

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Remove optifine
