### ISSUE TITLE
Constant Homelessness

### ISSUE THREAD

**Issue by MisterChester77** [ldtteam/minecolonies#6025]
### Prerequisites 

- [] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: minecolonies-0.13.405-BETA-universal
- Structurize Version: structurize-0.13.94-ALPHA-universal
- Related Mods and their Versions:

## Expected behavior

Citizens will be happy to have a home
## Actual behavior

My citizens still appear unhappy even after I've assigned them to a house. Moreover I've had this issue since previous versions.

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
They are unhappy with "low level housing". Might that be the problem you are having?

**Comment by MisterChester77** [comment]
At the moment all my workers are level 2 and so are their houses. The happiness indicator is always red for everyone.

**Comment by Raycoms** [comment]
that's fine, they stay red until level 3 at least yes.

**Comment by MisterChester77** [comment]
Oh thanks mate!

**Comment by Sandriell** [comment]
Seems like this should be a new category then as it is confusing. Came here confused about the same thing as OP. Maybe a "Housing Quality" category?
