### ISSUE TITLE
Crop farmer is producing wood and saplings

### ISSUE THREAD

**Issue by JDoeBoy** [ldtteam/minecolonies#6027]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: minecolonies-0.13.410-ALPHA-universal.jar
- Structurize Version: structurize-0.13.92-ALPHA-universal.jar

## Problem description

My farm is supposed to produce wheat, but is producing birch wood, and birch saplings.
### Notes or related things

I was trying to get the wood farmer to work, and he would not do his job, even chopped part of his own hut, so I dismantled the hut, and picked it up.  After, I set up a crop farm, and told it to plant wheat.  It didn't plant, so I manually tilled, and planted the wheat in part of the field.  After some time, I noticed that the NPC had planted some more wheat, and wanted an axe to do his job.  I emptied his inventory, as well as the inventory of the hut, and gave him an axe.  After a bit, he went to the first wheat, and I heard a wood chopping noise, so I checked his inventory, and he had harvested birch.
---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
the farmer makes space around the field you place. If there are blocks above dirt blocks they could plant on, they'll remove those blocks. That's what you've been seeing.

**Comment by ravenbuilder934** [comment]
They said they manually tilled and planted though

**Comment by JDoeBoy** [comment]
Yes, it was a tilled field, and a quarter of it was pre-planted by me as well.  I watched his animation harvest three wheat, and all he gained was wood/saplings.

**Comment by Raycoms** [comment]
Then something with the drop tables in your pack was messed up.
