### ISSUE TITLE
loaded my game cant move after resent update

### ISSUE THREAD

**Issue by BarlockJKD** [ldtteam/minecolonies#603]
### Minecolonies version

version 0.6.4 or curse lastest can't find where it listed

### Expected behavior

- I was moving fine last time i was onit.

### Actual behaviour

- I cant move at all laod of sounds around me and villagers zoom by me.

### Steps to reproduce the problem

1. start game with curse launcher
2. start game without curse launcher
3. turn of everything i can in game.
4. nothing works

**Comment by marvin-bitterlich** [comment]
what? I don't get what happens here, sorry

**Comment by Raycoms** [comment]
Do you have the problem on our server?
You might have to turn off the custom texture pack.

**Comment by Raycoms** [comment]
Please reopen if able to reproduce.
