### ISSUE TITLE
Miner "mining" but not actually. 

### ISSUE THREAD

**Issue by viniciusdel** [ldtteam/minecolonies#6032]
### Prerequisites

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

- Minecraft Version: 1.16.3
- MineColonies Version: Latest
- Structurize Version: Latest
- Related Mods and their Versions:

## Expected behavior
Miner goes down mineshaft, mines, creates levels. 

## Actual behavior
Instead, he's just sitting there (has been for days) not mining. His status shows mining, but he's not really doing anything.

![image](https://user-images.githubusercontent.com/19553214/98125822-e31f6780-1e82-11eb-8ea0-eeaae58fc695.png)

The mineshaft isn't even that deep and there's nothing for him to cover with cobblestone, he has enough cobblestone but is not using any. 

I fired him, re-hired him, took away his ladders, he asked for more and the proceeded to keep doing nothing

## Steps to reproduce the issue

Hire a miner, have him mine a shaft using the cave model. 

### Logs

No crash caused by this.

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
This looks like #6017 which was fixed already. What specific version are you on?

**Comment by viniciusdel** [comment]
He's not really starving, and I'm on 13.418, the latest on GD Launcher

**Comment by timstoop** [comment]
I have the same issue on 423.

**Comment by Raycoms** [comment]
which building style?

**Comment by timstoop** [comment]
Fortress for me.

**Comment by Raycoms** [comment]
anything special in the log?

**Comment by timstoop** [comment]
Nothing at all, no crash, so no logs for me (MultiMC).

I solved it by firing the miner and hiring another person as the miner.

**Comment by viniciusdel** [comment]
I did the same but the new miner does the same thing.

**Comment by Raycoms** [comment]
should be working fine now.
