### ISSUE TITLE
Guards not moving And Citizens Wont Eat From The Cook

### ISSUE THREAD

**Issue by keepinitreal247** [ldtteam/minecolonies#6033]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.3 
- MineColonies Version:-0.13.410-ALPHA
- Structurize Version:-0.13.92-ALPHA
- Related Mods and their Versions:pamhc2foodcore-1.16.3-1.0.0 -pamhc2crops-1.16.3-1.0.1

## Expected behavior

guards patrolling the area and citizens eating from the resturant when hungry
## Actual behavior

![2020-11-04_11 11 39](https://user-images.githubusercontent.com/72453022/98150845-e28fcc80-1e94-11eb-8684-61c3ac1bc1e0.png)
https://www.youtube.com/watch?v=Jzbzu-4mS8I
## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log:https://gist.github.com/keepinitreal247/93613f3464f6af915f3e2aa1b4575f08 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
fixed in newest
