### ISSUE TITLE
Builder only requests pickups when their hut storage is full

### ISSUE THREAD

**Issue by ravenbuilder934** [ldtteam/minecolonies#6036]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: MineColonies Official pack
- Structurize Version: MineColonies Official pack
- Related Mods and their Versions: none

## Expected behavior
The builder would request a pickup whenever they deposit something they don't need for their current build, like wheat seeds (from clearing land).

## Actual behavior
They only request a pickup when their hut storage fills up

## Steps to reproduce the issue

1. Have the builder deconstruct a building
2. They don't request a pickup
3. 

### Logs

- latest.log: This is on the 1.15 patreon server, unless you need client-side logs I can't help
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
That is actually on purpose because people asked to not have the couriers pick up things to regularly at the builder because a lot of things will be required on the next upgrade/build task. It is not only on completely full I think. There are some other earlier thresholds too afaik.

**Comment by MrcotinSol** [comment]
Could it not be a townhall setting ?
