### ISSUE TITLE
Guards constantly request shields

### ISSUE THREAD

**Issue by Nikademus** [ldtteam/minecolonies#6037]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.3
- MineColonies Version: minecolonies-0.13.420-ALPHA-universal
- Structurize Version: structurize-0.13.96-ALPHA-universal
- Related Mods and their Versions:

## Expected behavior

Guards would only request a shield when they don't have one.

## Actual behavior

Guards constantly request and re-request shields.

Image shows a guard with a shield (verified in their inventory) and is requesting another one.   I did not give them one at all, they already had one.
![2020-11-05_20 50 28](https://user-images.githubusercontent.com/1380028/98316903-4e635980-1fa9-11eb-8290-ce30085ffdb3.png)

## Steps to reproduce the issue

1.   Verify they have a shield in their inventory, clear their request either through their interface or the clipboard
2.  Wait 5-10 minutes
3.   They request another shield.

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
same as #5395

**Comment by MatthiasMann** [comment]
This still persists in minecolonies-0.13.547-ALPHA-universal and clearing / canceling / rearranging inventory etc doesn't help:
![2020-12-31_14 02 12](https://user-images.githubusercontent.com/6777029/103411587-16276400-4b71-11eb-9cca-b78140078e0b.png)
![2020-12-31_14 02 18](https://user-images.githubusercontent.com/6777029/103411592-1d4e7200-4b71-11eb-9bc1-d5b68ee9f0a2.png)

**Comment by KKomrade** [comment]
I want to add that guards also request shields even though the research hasn't been completed for it. Not sure if that should be in a separate issue.

**Comment by Rithenar** [comment]
Tried hiring/firing as well...FYI

**Comment by Justen-N** [comment]
@Raycoms, could this have something to do with NBT? it looks like the shield in both pictures has been crafted with a banner.

**Comment by Rithenar** [comment]
FYI it happened with regular shields too.  I just started a new playthrough so I will see if the issue persists in a new colony on a new world

**Comment by Justen-N** [comment]
Appreciated.

**Comment by MatthiasMann** [comment]
I only gave them the standard Minecraft shields - the colored ones must have been made by the guards themself?

**Comment by Raycoms** [comment]
Yes, the guards color them themselves

**Comment by Justen-N** [comment]
Okay. I'll start digging into this.

**Comment by Raycoms** [comment]
I tried to reproduce this but couldn't. Is there any nbt data on it?

**Comment by Raycoms** [comment]
Nvm, I got 2 nbt tags on the shield here but it still works fine.

**Comment by Rithenar** [comment]
Update: I just hired 2 Knights in my newly created colony on a brand new world (0.13.566-ALPHA) and having the exact same issue. 
![image](https://user-images.githubusercontent.com/9939332/105634303-f2c7a000-5e22-11eb-8897-77dfaebbfa3c.png)
The shield in the Knight's inventory has no special NBT tags 
![image](https://user-images.githubusercontent.com/9939332/105634327-10950500-5e23-11eb-92a5-141740a4d138.png)

**Comment by Raycoms** [comment]
is this before researching or after researching shields?

**Comment by Raycoms** [comment]
Does this happen with the newest alpha too? I've changed some things around NBT recognition

**Comment by Rithenar** [comment]
> is this before researching or after researching shields?

Before researching shields. It is a brand new colony.

**Comment by Rithenar** [comment]
> Does this happen with the newest alpha too? I've changed some things around NBT recognition

I will test with the new version tonight when the server is empty

**Comment by Rithenar** [comment]
Upgrading and then resetting the colony request system did it. Thanks, Raycoms!

**Comment by Rithenar** [comment]
Sadly the issue is back. My guards died and I hired from the tavern. Both have shields, both are requesting them. I reset the request system and they go back to requesting shields 
![image](https://user-images.githubusercontent.com/9939332/106038344-75f42a80-609d-11eb-9d41-17bc9369c921.png)

**Comment by Rithenar** [comment]
Update: Some of my guards stopped asking for shields so I thought it had fixed itself.  Nope! They are hoarding! LOL
![image](https://user-images.githubusercontent.com/9939332/106364292-8d2c5580-62f3-11eb-9944-5108347e6ca0.png)

**Comment by Talyda** [comment]
I noticed this yesterday too, so this morning I updated to .596 and took all the extra shields away from my guards, and now have one asking for another (they have 1 undamaged one on them) Only been playing 10 minutes, so I assume the others will ask soon too

**Comment by ravenbuilder934** [comment]
> I want to add that guards also request shields even though the research hasn't been completed for it. Not sure if that should be in a separate issue.

different issue prolly

**Comment by Raycoms** [comment]
Fixed
