### ISSUE TITLE
[Bug][Major] Tavern Visitors

### ISSUE THREAD

**Issue by TheRealM18** [ldtteam/minecolonies#6039]
### Prerequisites

- [ x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 
- Minecraft Version: 1.16.3
- MineColonies Version: minecolonies-0.13.420-ALPHA-universal.jar
- Structurize Version: structurize-0.13.96-ALPHA-universal.jar
- Related Mods and their Versions:

## Expected behavior
The visitors not to instantly teleport away on joining the colony

## Actual behavior
The tavern visitors, will delete themselves, the second they enter the colony.  This is happening on multiple different taverns, and does not always happen.  It was on a stream on DragonRealmsGaming, showing off 2 days ago, and I will get a video of this happening again.

This in not 100% of the time to happen, but seems to happen when your colony is unloaded completely, and can not force its way back.

## Steps to reproduce the issue

1. Make a new world
2. Make the builder then townhall
3. make the tavern, and test in multiplayer to get it to trigger
4. happens at least 4 times a day, and was not happening on 1.16.2

### Logs

There is not a log or crash report involved with this.

### Notes

If needed, we can give you access to our server to see for yourself

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by someaddons** [comment]
sure they teleport away and dont just despawn?

**Comment by TheRealM18** [comment]
We have noticed that the despawn instantly.  They will spawn in, on first load of colony, and when the load is unloaded, like the nether, it will not load the tavern npcs correctly.
