### ISSUE TITLE
Cowhand will not breed cows

### ISSUE THREAD

**Issue by shalazan** [ldtteam/minecolonies#6040]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.3
- MineColonies Version: 0.13.420-ALPHA
- Structurize Version: 0.13.96
- Related Mods and their Versions: All The Mods 6 1.2.1

## Expected behavior
Cowhand should breed cows when provided wheat and breeding enabled

## Actual behavior
Cowhand (In a wooden designed hut) is standing in the hut, not breeding. She has been provided 2 and 4 cows, has a stack of wheat in her inventory, the rack, and the hut inventory, the cows are not on breeding cooldown, and stands inside the hut. She has no pending requests. She will milk appropriately and kill to an appropriate minimum (2 at lvl1, 4 at lvl2) but does not breed.

## Steps to reproduce the issue

1, Build cowhand hut
2. hire cowhand
3. give wheat, buckets and axe
4. observe.

### Logs

- latest.log: https://gist.github.com/shalazan/68535bef3d11485a7b4cdf0b5f0287a9
- crashlog: N/A
### Notes
Thanks :D

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
fixed
