### ISSUE TITLE
Game crashed after loading the worldwith "Ticking entity" exception

### ISSUE THREAD

**Issue by xiaobbl** [ldtteam/minecolonies#6042]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.15.2
- MineColonies Version:0.13.394(also happens in 0.13.421)
- Structurize Version:0.13.94
- Related Mods and their Versions:jei 6.0.3.15

## Expected behavior

world load normally

## Actual behavior

My chickenheader and cowboy always gave AI exceptions.But i didnt take them seriously because i didn't need a large number of milk or chicken.But i quit game by the chickenheader and cowboy(they were close to each other)and workers are "working".Then i cant load world anymore.
By the way,this may happen by the moment after finishing loading world for which you can still see the world by minimize the window while loading the game(as tou know,it was a pause GUI,then game crashed after returning the game).

## Steps to reproduce the issue

1. stand by a worker(or maybe building) that always gives out AI exception
2. quit the game
3. load the world
4. see it

### Logs

- latest.log: https://gist.github.com/xiaobbl/505473ed023a46c7c015c2c1cea963bd
- crashlog: https://gist.github.com/xiaobbl/dcb1d0e3588b8eefe088d9199fe6310e

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Apparently the building went null out of the blue. This is weird

**Comment by Raycoms** [comment]
The worker crashing is your cook assistant and not the worker you've noted

**Comment by xiaobbl** [comment]
well,i got another information...
my cook was always asking for more and more food(not as #5395,but a request that seems can never been solved).it used to happens to my builder.at that moment i remove the builder's hut,build another one and hire it again.So this time i do this again.it was strange that after i rebuild the resteraurant,i can rehire my cook but my assistant cook seem to be never fired and worked as usual.everything goes well in an hour until i quit the game:(

**Comment by Raycoms** [comment]
It seems like something corrupted that assistant cooks data weirdly.

**Comment by xiaobbl** [comment]
well,so the issue is that the assistant cook cant be fired automatically after remove the restaurant...
now im trying to delete the citizen with NBT tools:(

**Comment by xiaobbl** [comment]
@Raycoms i wonder if the file uder the save/my_world_name/minecolonies can save my world:(

**Comment by Raycoms** [comment]
Fixed in latest (will be on curse in 5 minutes)
