### ISSUE TITLE
Tools not breaking when used by npcs

### ISSUE THREAD

**Issue by Cherubi09** [ldtteam/minecolonies#6045]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version. 1.16.3
- [ ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.3
- MineColonies Version: latest alpha 
- Structurize Version: latest for version
- Related Mods and their Versions:

## Expected behavior
 npcs to use up tools 

## Actual behavior

The tool gets used however they never use any durability. 
No videos to show sorry
## Steps to reproduce the issue
I just gave then the tool and noticed no other tool were ever being used. 

### Logs
There were crashes so no logs can be provided

- latest.log: 
- crashlog: 

### Notes

While i know its a bug its been helpful. 
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Aduis1210** [comment]
same issue - reported on discord
