### ISSUE TITLE
Raids disabled?

### ISSUE THREAD

**Issue by lucas02061** [ldtteam/minecolonies#6049]
Hi,

Raids seem to be disabled totally since i started playing Minecolonies again after a 3 month break. I have tried following:

1. Difficulty normal.
2. Tried using both Twitch and GD as launchers
3. Tested in both 1.16 and 1.15
   - Both versions was updated to the newest version.
4. Tried to disable all other mods
5. Tried using both raid commands and the "can spawn raiders" command
6. Played in 4 different world
   - Largest town had about 20 citizens and 30 buildings
   - Smallest town had 8 citizens and 10 buildings
   - All towns had guards
7. The only commands I have used that might interfere with the raids is "/set time day" command, "/difficulty peaceful and "/gamerule doDaylightcycle"
   - Set time was not used very often
   - Peaceful command and gamerule command was only used when afk. Was not activated for very long at a time.

I really hope you can fix this problem :) I have been struggling with this for a week now, and have not been able to find a solution... :/ I love raids so I really hope to find a fix for this problem :b Please let me know if you find a fix :)

I do not know if you need it, but here is my "latest.log":

https://www.dropbox.com/sh/y4qpa1ukrt27t1s/AAD0mtMqvpWGCAz-yAPhDeaga?dl=0

**Comment by Raycoms** [comment]
While daylight cycles are off they do not spawn, that is a certain too.

**Comment by lucas02061** [comment]
I thought that might have an impact, but daylight cycle is only changed for 1 hour or so every 10 hour.

**Comment by Raycoms** [comment]
do you set time to day automatically every x ticks or so or with a daylight detector?

**Comment by lucas02061** [comment]
No, I do sleep most days when all citizens has gone to sleep.

**Comment by Raycoms** [comment]
What's your chunk loading radius?

**Comment by lucas02061** [comment]
I guess the default? I have not changed it.

**Comment by lucas02061** [comment]
If you are talking about the render distance, it is set to 12 chunks.

**Comment by Raycoms** [comment]
I double tested this again. Spawned in 11 citizens and a few huts and I spawned a bunch of raids just fine.

**Comment by lucas02061** [comment]
Hmmm, I really do not know what is my problem then :( I mean, I have installed multiple version of the mod, reinstalled the game so it was totally fresh. I have not touched any config settings...

**Comment by lucas02061** [comment]
It worked like a charm a couple of months ago, but since i installed the new version, nothing seems to work :/

**Comment by Raycoms** [comment]
can you in creative spawn a few level 5 buildings and spawn 15 citizens (mc citizens spawnNew colonyid) in a new world, normal mode and test?

**Comment by Aduis1210** [comment]
Have you tried a test world? To see if the issue stems from your original world?

**Comment by lucas02061** [comment]
I will do that Raycoms, give me a minute.

Adius1210 I have not made a test world, but I thought it might have been the world so i restarted twice. I therefor have 3 colonies in 3 different modpacks, one of which is in 1.15 and the other two in 1.16. Still does not work.

**Comment by lucas02061** [comment]
Raycoms, I just made a test world, spawned in a few lvl 5 buildings and 17 citizens. And it works for some reason?

**Comment by Raycoms** [comment]
I wonder if there is any gamerule activate when you initially created your other world, and when you "restart" it, those will be copied over.

**Comment by Raycoms** [comment]
But I am certain this is not on our side xD

**Comment by lucas02061** [comment]
Raycoms, is it because I do not have enough citizens? Or? I mean what gamerules would carry over when i restart if I made a totally new modpack, with a new version of minecraft, and even tried to uninstall all other mods?

It seems like the reason im not getting raids is because i have to few people or my buildings are too low level? What level buildings do you need before raids start?

**Comment by Aduis1210** [comment]
you get a notification at around 6 citizens saying barbarians have noticed your colony- best to make a guard tower

**Comment by lucas02061** [comment]
I never got that message

**Comment by lucas02061** [comment]
In either of the 3 worlds

**Comment by Raycoms** [comment]
In the past there was a hard cap, after 6/8 citizens you'd get raids. That doesn't exist anymore. Nowadays it's based on a joint development value of the colony. It's difficult to say when they start coming, the 20 people colony should be big enough. But maybe in normal mode they come even a bit later since there are not enough worker buildings etc.

**Comment by lucas02061** [comment]
Okay, so it could be simply because my colony is not big enough? 

The only thing those 3 colonies have incommon which the test world did not have is that at one point during the 10-30 hours i played each of the other world, i changed the time or the gamerule. Do you think changing the gamerule once could make it so that raiders will never spawn again?

**Comment by Raycoms** [comment]
changing the time doesn't affect it, that I'm sure about. But the gamerule, could be a minecraft bug where it drags down the world time. But changing the worldtime will mess with the colonies in general too, so it's not adviced.

**Comment by lucas02061** [comment]
Okay, I did the same thing back 3 months ago when it worked fine, so it is a bug that is introduced in the last 3 months. It would just be weird if it was a minecraft bug since I am playing in 1.15 which is older than 3 months?

**Comment by lucas02061** [comment]
Okay it is because of my town level that I do not get raided. Tried to make a copy of my world and spawn in a couple of lvl 5 buildings and spawn some villagers in. After this I could spawn in a raid. It seems like you need quite a big town before raids start.

Anyway, thanks for the help :)
