### ISSUE TITLE
second warehouse not taken into account

### ISSUE THREAD

**Issue by gd71** [ldtteam/minecolonies#605]
### Minecolonies version

version 1.10.2-0.6-2849

### Expected behavior

- Second warehouse taken into account by deliverymen

### Actual behaviour

- second warehouse not taken into account by deliveryman

### Steps to reproduce the problem

1. Build 2 deliveryman huts
2. Build 2 warehouses
3. level up everything to level 5

Thanks for your addictive Minecraft mod !

**Comment by Raycoms** [comment]
Like we wrote in the Wiki. Please place only 1 warehouse.
Deliverymen are assigned to warehouses.
A deliveryman only works at one warehouse at a time.

**Comment by gd71** [comment]
I tried to check the wiki but seems off today ...
Does it mean that storage capability is limited or do I need to hire more deliverymen to let them handle the second warehouse?
Thanks anyway for your quick answer

**Comment by marchermans** [comment]
You cannot have more then one warehouse per, i think.

**Comment by Raycoms** [comment]
Upgrade your warehouse to have more space.
Warehouse level 5 is quite big.
if you need even more, change the schematics =D

2017-02-16 9:49 GMT-02:00 Orion <notifications@github.com>:

**Comment by gd71** [comment]
Right
Time to works with schematics!

**Comment by gd71** [comment]
I probably need to wait for #579 as we are on a local server for all the family ... =D

**Comment by Raycoms** [comment]
If it is with the whole family just put the schematics in the jar at the
right location and give that jar to the whole family

2017-02-16 10:19 GMT-02:00 gd71 <notifications@github.com>:

**Comment by gd71** [comment]
yep, I checked that way but have to do it each time you deliver an upgrade.
And you are delivering so often! lol
No matter depending how far is the delivery of #579 I will manage accordingly
