### ISSUE TITLE
Couriers not doing requests

### ISSUE THREAD

**Issue by cobdude** [ldtteam/minecolonies#6053]
### Prerequisites 

- 

> [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.

- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.405-BETA-universal
- Structurize Version: 0.13.409 Aplha
- Related Mods and their Versions: None

## Expected behavior

Couriers work and do requests.

## Actual behavior

Couriers are able to pick up items from the workplaces racks not main blocks inv but not to big of an issue, but if they receive a request they just freeze in the warehouse doing nothing and won’t stop until the request has been done by the player and will move on to the next thing they are doing which it is pickup will work but if request will freeze again. I’ve restarted the world once before and the next time I played it happened again so unlikely to be uncommon.

## Steps to reproduce the issue

1.  get couriers and warehouse
2.  get a worker to request something and they will freeze at the warehouse
3.  this is all I did twice in a row and it broke 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
fixed in latest
