### ISSUE TITLE
Farmer won't use hoe and Miner won't use pickaxe

### ISSUE THREAD

**Issue by rennenga** [ldtteam/minecolonies#6054]
### Prerequisites 

- [ x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: minecolonies-0.13.438-ALPHA-universal
- Structurize Version: structurize-0.13.94-ALPHA-universal
- Related Mods and their Versions:

## Expected behavior

    I placed a farmer and expected that when it asked for a hoe and i gave a wooden hoe to them, they would use it on the farm plot that i set up with a seed in the scarecrow.  I tried to work around the glitch by upgrading the farm to level 2 but that didn't fix it either
    I thought that maybe the bug was just related to my farmer but i just built a miner and he won't use any pickaxes i give him either (gold and wood).
   
## Actual behavior

    I set up a farm and hired a farmer. I set up a plot and pre-tilled most of the surrounding tiles (to help them out because they are typically slow), I place the wheat seed in the scarecrow and turned around to see the Farmer asking for a hoe. I said okay, and crafted a wooden hoe. I walked up to the farmer, looked at the request and it said I couldn't fulfill it. I tried placing the hoe directly into their inventory and into the farmer block, neither triggered the farmer to say "Cool, thanks for the hoe!" or whatever. Frustrated, I tried all of the troubleshooting steps, I tried most of the different available versions of minecolonies 1.15.2, I fired the farmer and hired a different guy wondering if there was a new "dumb" mechanic since last i played, i upgraded the farm to level 2 thinking maybe it would override a "what level farmers can use" value. No matter what i do, the farmer will not accept any hoes I give them. 
    I gave up initially, thinking I didn't really need a farmer at this point and set up a mine. THEN the miner wouldn't accent any pickaxes I gave him! My forester uses his axes properly, but both my miner and farmer won't operate. Please help!!

## Steps to reproduce the issue

1. Build a farm
2. Hire a farmer
3. Give a stack of seeds
4. Set up farm plot near by
5. Farmer should ask for a hoe and fertilizer

### Logs

- latest.log: 
- crashlog: 

### Notes

There may be a different mod that is conflicting but i have no idea where to start so here is my complete mod list. It is the Life in the Village 2 mod pack: https://www.curseforge.com/minecraft/modpacks/life-in-the-village-2
 Total current Mod list:

World & exploration:
--
MineColonies (by H3lay)
Upgrade Aquatic (by minecraftabnormals)
Aquaculture 2 (by Shadowclaimer)
YUNG's Better Mineshafts (Forge) (by YUNGNICKYOUNG)
Doggy Talents (by percivalalb)
Charm (by svenhjol)
Buzzier Bees (by bageldotjpg)
The Endergetic Expansion (by endergized)
Quark Oddities (by Vazkii)
Strange (by svenhjol)
Quark (by Vazkii)
Project: Vibrant Journeys (by solis_nova123)
Enhanced Mushrooms (by Ep1c312)
Better Animals Plus (by cybercat5555)
Pickle Tweaks (by BlakeBr0)
Charmonium (by svenhjol)
GraveStone Mod (by henkelmax)
Comforts (by TheIllusiveC4)
TrashSlot (by BlayTheNinth)
Technology & Automation:
Productive Bees (by LobsterJonn)
Incubation (by martianarchitecture)
Extra Boats (by martianarchitecture)
Storage Drawers (by Texelsaur)
Decoration & building:
Fairy Lights (by pau101)
Macaw's Bridges (by sketch_macaw)
Macaw's Furniture (by sketch_macaw)
Bamboo Blocks (by bageldotjpg)
Uppers (by vadis365)
Macaw's Windows (by sketch_macaw)
Extended Lights (by Polyvalord)
Macaw's Roofs (by sketch_macaw)
Farming:
Pam's HarvestCraft 2 - Food Core (by pamharvestcraft)
Spice of Life: Carrot Edition (by lordcazsius)
Pam's HarvestCraft 2 - Crops (by pamharvestcraft)
Utility and QOL:
ReAuth (by TechnicianLP)
Better Advancements (by way2muchnoise)
Cosmetic Armor Reworked (by LainMI)
Just Enough Resources (JER) (by way2muchnoise)
Item Filters (by LatvianModder)
FTB Quests (by LatvianModder)
PackMenu (by Shadows_of_Fire)
Unity: Dark Edition (by theCyanideX)
JourneyMap (by techbrew)
Mouse Tweaks (by YaLTeR)
Unity: Extras (by theCyanideX)
The One Probe (by McJty)
Light Overlay (Rift/Forge/Fabric) (by shedaniel)
Starter Kit (by Serilum)
Fast Leaf Decay (by olafskiii)
Mo's Improved Leaves and Foliage (by mo_shark)
Enchanted Book Redesign (by tfarecnim)
Controlling (by Jaredlll08)
RandomPatches (by TheRandomLabs)
JEI Enchantment Info (by Phylogeny)
Just Enough Items (JEI) (by mezz)
Libraries and coremods:
Bookshelf (by DarkhaxDev)
FTB GUI Library (by LatvianModder)
Placebo (by Shadows_of_Fire)
AutoRegLib (by Vazkii)
Structurize (by H3lay)
Collective (by Serilum)
Cloth Config API (Forge) (by shedaniel)
Abnormals Core (by SmellyModder)
Libnonymous (by davenonymous)
Cucumber Library (by BlakeBr0)

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Pyrocantaes** [comment]
I don't have a problem with the miner and pickaxes (medieval Spruce mine) but I do have the issue with the farmer not recognizing either a wooden or stone hoe. Doesn't matter whether you put it in their inventory or the farm inventory. Also firing and rehiring the farmer doesn't solve the issue nor does resetting the request queue

**Comment by Raycoms** [comment]
Usually the way to find out which mod is causing it, is by removing like half the mod seeing if it fixed it, if not remove half again etc, until you find out which mod does it.

**Comment by Pyrocantaes** [comment]
Using a flint hoe works..so is it something to do with the way tool levels work?

**Comment by Raycoms** [comment]
yep, some mod broke tool levels most likely.

**Comment by Raycoms** [comment]
We use the materials tools provide to calculate tool levels, if mods alter this behaviour, unfortunately there is not much we can do and you'll have to experiment around a bit with alternative materials.
