### ISSUE TITLE
Fortress gate with moat and drawbridge builder then breaks the iron gate as he builds it

### ISSUE THREAD

**Issue by SadHorizion77210** [ldtteam/minecolonies#6055]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: 0.13.437
- Structurize Version:0.13.92
- Related Mods and their Versions: 

## Steps to reproduce the issue

1. <place a fortress gate with moat and drawbridge 
2. <request the builder to build it>
3. <then wait till he gets to the gateway of the gate and watch him build the gate and walk through it as he is building it>

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
The iron gate are the minecolonies iron gates we provided, are they part of that schematic?

**Comment by SadHorizion77210** [comment]
Yes the iron gate is now on the  fortress moat gateway which is in the fortress deco pack there is 2 gateways the large and the small gateway with iron gate on the outside entrance of the gate with the dark oak doors on the innerside of the gate   as  i made on the comp server

**Comment by Raycoms** [comment]
Tested, at least as of now, the builder builds those flawlessly
