### ISSUE TITLE
Builder will not except armor or weapons for builds

### ISSUE THREAD

**Issue by mkiefer3711** [ldtteam/minecolonies#6056]
I am trying to build the level five birch style mine and the level 1 birch style combat academy in the modpack called Life in the Village. The problem is that for the mine build, the builder needs an iron pickaxe and iron shovel. I have tried giving the builder both items but it will not fulfill their request. I have tried every type of shovel and pickaxe as well and it will still not work. I have hired, and rehired the builder and reset them but that still does not work. The same problem is happening with the combat academy. The builder is requesting leather armor but will not except it when I give it to them as part of the build. Please tell me if there is anything I can do to fix this. I am loving this mod and would like to keep playing it. Thank you.

**Comment by Raycoms** [comment]
Please fill in the whole template. This is the second life in a village complaint, can you please remove mods selectively to find out which one is causing this behaviour?

**Comment by Raycoms** [comment]
Same as here https://github.com/ldtteam/minecolonies/issues/6054
