### ISSUE TITLE
file minecolonies-0.13.426-ALPHA-api.jar is not a valid mod file

### ISSUE THREAD

**Issue by pete-koning** [ldtteam/minecolonies#6057]
Hi there.

I am running 1.15.2 under multimc 0.16.11. This error is from the latest alpha version but I got the same error from the previous ALPHA (0.13.394).

I'm not sure what's going on here or if some configuration settings have changed. 

I note that the naming convention for the alpha releases has changed. Previous to the last two releases, they were in this format: minecolonies-0.13.379-ALPHA-universal.jar and minecolonies-0.13.358-ALPHA-universal.jar. I don't know if that makes a difference.

Hopefully, this is the right place to post this.

![image](https://user-images.githubusercontent.com/56967525/98629059-0c5a5080-22e6-11eb-981f-4869bc386b8b.png)

**Comment by Aduis1210** [comment]
You're using the wrong file. - API is for modders.

[https://www.curseforge.com/minecraft/mc-mods/minecolonies/files/all](url)
