### ISSUE TITLE
Miner wanders off when selecting higher levels on mine

### ISSUE THREAD

**Issue by Aduis1210** [ldtteam/minecolonies#6058]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

- Minecraft Version: 1.15.2
- MineColonies Version: minecolonies-0.13.438-ALPHA-universal
- Structurize Version: structurize-0.13.94-ALPHA-universal
- Related Mods and their Versions:

## Expected behavior
Miner mines upper levels as expected

## Actual behavior
After recalling - He wanders off and stops in a random area topside

## Steps to reproduce the issue

1. Maker miner - recruit miner
2.  wait for them to build the mine shaft
3. change level to level 0
4. miner wanders off

### Logs
no errors on log

## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
okay I double checked at that. This should work fine. Unless there is sth blocking the miner to actually enter the shaft (like lava, or gravel or sand). Those might be blocking it.
