### ISSUE TITLE
Farmer not keeping seeds/crops from other mods

### ISSUE THREAD

**Issue by gd71** [ldtteam/minecolonies#606]
### Minecolonies version

version 1.10.2-0.6-2849

### Expected behavior

- Farmer keep 1 stack of seeds from other mod if needed

### Actual behaviour

- Farmer don't keep seeds from other mods
- Deliveryman don't deliver those seeds

### Steps to reproduce the problem

1. Create Farm hut and hire farmer
2. Create field and set it to use some pam's harvestcraft seeds (here cotton seeds and lettuce crops)
3. Give the farmer some seeds to start
4. Farmer is harvesting well the field but empty his inventory not keeping the seeds/crops
5. The farmer request these seeds or crop but the deliveryman does not deliver them

**Comment by marchermans** [comment]
We would probably need to implement ore dictionary keeping....

**Comment by Raycoms** [comment]
We should make it something like keep everything which extends  ItemSeed.

2017-02-16 9:38 GMT-02:00 Orion <notifications@github.com>:

**Comment by marchermans** [comment]
That would also be enough
I am currently working my way through the code....... I am finding stuff that needs a rewrite to fix these kinds of compatibility issues and extensibility issues. Will make a Project / Milestone for it and will then start creating issues / prs for it. But this is low on my list. So somebody else should take a look at this and handle it.

**Comment by marvin-bitterlich** [comment]
@OrionDevelopment That sounds awesome! Once we have an issue to track it, most bugs are fixed really quick (or get a bounty ;) )

**Comment by Raycoms** [comment]
Should be fixed already
