### ISSUE TITLE
wrong max citizen per colony

### ISSUE THREAD

**Issue by radoslawKnitter** [ldtteam/minecolonies#6062]
Prerequisites
[x ] I am running the latest alpha version of MineColonies and Structurize for my Minecraft version.
[ x] I checked the MineColonies/Structurize wiki and made sure my issue is not covered there.
[ x] I made sure that this issue is not a duplicate of any existing issue.
Context
Minecraft Version: forge-1.16.3-34.1.0
MineColonies Version: minecolonies-0.13.428-ALPHA-universal
Structurize Version: structurize-0.13.96-ALPHA-universal
Related Mods and their Versions: AI-Improvements-1.16.2-0.3.0 , FastLeafDecay-v25, Neat+1.7-24, Xaeros_Minimap_20.25.0_Forge_1.16.3, XaerosWorldMap_1.11.0_Forge_1.16.3

## Expected behavior
the town hall should count the correct number of places in the colony and on this basis young residents should normally be born, and I should be able to hire new ones from the tavern if I have a place.

## Actual behavior
I have set:
maxcitizenpercolony = 500
and although the village is full of unoccupied houses, new ones are not born, the Town Hall shows that I have 25/25, and also from the tavern I can't hire anyone as there is no place in the colony.

## Steps to reproduce the issue

1. set in config  **maxcitizenpercolony = 500**
2. build a colony with more than 25 places
3. wait until 25 slots are full to make sure there are still houses available

### Logs
there is nothing in the logs

- [latest.log](https://gist.github.com/radoslawKnitter/8c75262c34f48a0ed89b33a711bb33d9): 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Have you completed the research to let you have more than 25 citizens?

**Comment by Raycoms** [comment]
The research restricts this. you need to do the research first in the university
