### ISSUE TITLE
[1.16.3] Supply Ship Won't Place Even When Area is Clear

### ISSUE THREAD

**Issue by MokahTGS** [ldtteam/minecolonies#6064]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 
- Minecraft Version: 1.16.3
- MineColonies Version: 0.13.437-RELEASE
- Structurize Version: 0.13.96-ALPHA
- Related Mods and their Versions:

## Expected behavior
Supply Ship should place in the water

## Actual behavior
Ship is not placing.  Continually spams that there needs to be water in certain blocks that there is water.  Everything is clear, nothing is in the way.  Tried multiple blocks in every direction.

This is beyond frustrating.  I'm in creative, and it should just place where I tell it to.

https://www.dropbox.com/s/13imodpyxo7ikb1/2020-11-10_19.03.38.png?dl=0
https://www.dropbox.com/s/3jeptvhi2kjzd58/2020-11-10_19.03.31.png?dl=0
https://www.dropbox.com/s/yity7id0bgj7yxp/2020-11-10_19.03.18.png?dl=0
https://www.dropbox.com/s/oiaqukmzurhdeia/2020-11-10_19.03.03.png?dl=0
https://www.dropbox.com/s/96k03m5sro9f68w/2020-11-10_19.02.52.png?dl=0
https://www.dropbox.com/s/php1efqwacnhubp/2020-11-10_19.02.36.png?dl=0

## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Update Structurize to the latest alpha. Your minecolonies and structurize versions are not compatible

**Comment by MokahTGS** [comment]
OK, did not put the right info....updated to the right one in the bug report.  It is not working on the most current alpha of Structureize.

**Comment by ravenbuilder934** [comment]
Wait, I thought 437 needed 94 of structurize? How did you even launch?

**Comment by MokahTGS** [comment]
Don't ask me...launches just fine on client and server.

**Comment by MokahTGS** [comment]
Version 94 isn't available on the launcher.

https://www.dropbox.com/s/zbwbl9hjsln1ckm/Ver96.jpg?dl=0

**Comment by ravenbuilder934** [comment]
🤦‍♀️ I was thinking of 436 release (1.15.2), which needs 94

**Comment by Raycoms** [comment]
there is kelp in the waer

**Comment by Raycoms** [comment]
might that be it?

**Comment by Aduis1210** [comment]
yup Kelp can cause this issue.
Give it a trim and your good to go

**Comment by MokahTGS** [comment]
There is no kelp underneath the boat...I cleared everything.  Does it have to be clear for so many blocks in every direction?  Shouldn't it just check the blueprint boundaries?

**Comment by Raycoms** [comment]
We'll release a fix soon that might fix it for you

**Comment by MokahTGS** [comment]
OK, thank you.
