### ISSUE TITLE
Miner leaves ores in the walls of the mine

### ISSUE THREAD

**Issue by timstoop** [ldtteam/minecolonies#6069]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.423-ALPHA
- Structurize Version: 0.13.94-ALPHA
- Related Mods and their Versions: Velhelsia 2 with Immersive Engineering disabled

## Expected behavior

All ores in the tunnels of a mine on the level that the miner is working on replaced by cobblestone.

## Actual behavior

When walking through the tunnels of the mine on the level that the miner is currently working on, I still see a lot of ores (iron ore, bismuth ore, coal ore, etc.) in several walls spread over the tunnels.

## Steps to reproduce the issue

1. Have the miner mine a large mine on a single level. My mine had 100 nodes.

### Logs

- latest.log: 
- crashlog: 

No crashes and nothing about this in the logs, so not attaching. Let me know if you still need them.

### Notes

Discussed on the Discord and was told by ravenbuilder934 that I should open an issue about this.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
how old is that world? We fixed that some weeks ago, but old worlds might still have mines like this

**Comment by timstoop** [comment]
Two weeks to the day.

**Comment by timstoop** [comment]
But this miner has only been working since last Monday, it's my fourth one.

**Comment by Raycoms** [comment]
What kind of ores are in the walls, all?

**Comment by Aduis1210** [comment]
All types of ores - I've noticed as well with the miner.

**Comment by Aduis1210** [comment]
![2020-11-12_18 01 13](https://user-images.githubusercontent.com/56609195/98978038-3f345c80-2511-11eb-829a-3f7d208eb310.png)
![2020-11-12_18 01 46](https://user-images.githubusercontent.com/56609195/98978040-40658980-2511-11eb-8cb5-6526d79064bd.png)

**Comment by Aduis1210** [comment]
I am using a texture pack - but its diamonds and iron im seeing missed.

**Comment by Raycoms** [comment]
This is not the wall though, this is the ceiling.
