### ISSUE TITLE
[EXT] Detaching the creation of Buildings from the Colony and their Blocks

### ISSUE THREAD

**Issue by marchermans** [ldtteam/minecolonies#607]
In the current situation a new Building is constructed by calling its constructor:
`Building(Colony c, BlockPos p);`

_It is currently being called from:_
- `AbstractBuilding.createFromNBT(final Colony colony, @NotNull final NBTTagCompound compound)`
- Many of the Constructors use it as super(Colony c, BlockPos p). (This should stay)

_Solution_:
- Create a singleton Factory class that holds IBuildingConstructors which create a new Building from the given colony and location.
- Create a default construction class that wraps the current method of creating new instances.

**Comment by Wissi** [comment]
@OrionDevelopment Is this still something you are working on or no longer needed?
Since it's been a year already. 
I'll close and you can reopen if needed with comments?
