### ISSUE TITLE
i can recruit to many citizens from tavern

### ISSUE THREAD

**Issue by thijspoon28** [ldtteam/minecolonies#6070]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.3
- MineColonies Version: minecolonies-0.13.440-ALPHA-universal.jar
- Structurize Version: structurize-0.13.96-ALPHA-universal.jar
- Related Mods and their Versions:

## Expected behavior
when there is no more place for citizens, you should not be able to get new citizens from the tavern

## Actual behavior
even tho there is no space in my city, i can still get new citizens from the tavern

i now have 21/19 citizens in the village

## Steps to reproduce the issue

1. get x amount of space for citizens
2. get that amount of citizens for example 20 housing 20 citizens (20/20)
3. now go to the (level 2 Asian) tavern and recruit someone. BOOM now u have 21/20

### Logs

- latest.log: 
- crashlog: 

### Notes
all of my village is build in Asian style

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by someaddons** [comment]
that is actually normal, you can recruit tavern ppl for empty guard building slots. As those are not normal living space it doesnt show on the townhall

**Comment by thijspoon28** [comment]
i could not before, but i think u are right. il check
