### ISSUE TITLE
Networking issue in 1.16.3

### ISSUE THREAD

**Issue by rmortes** [ldtteam/minecolonies#6073]
### Prerequisites 

- [x] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.3
- Structurize Version: 0.13.96-ALPHA
- MineColonies Version (if related bug): Probably not related, but 0.13.440-ALPHA
- Related Mods and their Versions:
  - Forge: 34.1.40
  - Endertech: Not sure, I'm not running the affected seerver

## Expected behavior

A working server

## Actual behavior

The server cannot be accessed. It returns the following exception: "io.netty.handler.codec.DecoderException: Badly compressed packet - size of 2230335 is larger than protocolo maximum of 2097152
![Emss88YXEAY1znk](https://user-images.githubusercontent.com/56652057/99075646-1e741180-25ba-11eb-9825-47a53f6d9e50.png)

In the server the following exceptions can be read
![EmstJfbXUAAJI44](https://user-images.githubusercontent.com/56652057/99075886-84f92f80-25ba-11eb-8387-9adf89fa5eb8.png)

## Steps to reproduce the issue

I'm not too sure as I'm not the one running the server, but the exception occurs when entering the world

### Logs

I don't have access to the logs. If required, I could try to request them

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
More likely related to minecolonies. But it's weird, this should not be able to happen anymore. A) are there custom schematics on the server? b) are you sure there is no verison mismatch with the server? c) if you run /mc colony requestsystem-reset-all, does i t stop?

**Comment by rmortes** [comment]
I'll ask

**Comment by rmortes** [comment]
- No custom schematics
- The server is running the latest minecolonies version avaliable in Curse, with the required Structurize version
- The same exception occurs

**Comment by lucsoft** [comment]
Same issue here

**Comment by Raycoms** [comment]
@OrionDevelopment any idea?

**Comment by Raycoms** [comment]
I tested this, works fine in the newest even with a bloated up message

**Comment by lucsoft** [comment]
did you test singleplayer or multiplayer (singleplayer works fine)

**Comment by Raycoms** [comment]
Multiplayer
