### ISSUE TITLE
Deliveryman deliver useful things into warehouse

### ISSUE THREAD

**Issue by xiaobbl** [ldtteam/minecolonies#6074]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.15.2
- MineColonies Version:0.13.421
- Structurize Version:
- Related Mods and their Versions:

## Expected behavior

a worker produce materials(such as glass)and then delivery man delivery this to who needs it

## Actual behavior

the deliveryman delivery it directly into warehouse.those who need it cant recognize materials in warehouse.the producer wont produce the material one more time either

## Steps to reproduce the issue

1. let worker ask for sth
2. wait for delivery(requesting for picking immediatly may let this happen sooner)
3. So that this happens

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Update, some bugs regarding this were just squased
