### ISSUE TITLE
Item transfer bug (possibly Mousetweaks related)

### ISSUE THREAD

**Issue by Dragolance117** [ldtteam/minecolonies#6078]
Good day dear developers of the awesome minecolonies mod !

I am playing on a singleplayer world with the minecolonies official modpack version 3.1 for minecraft 1.15.2 .

Whenever i use the scroll wheel to transfer a quantity of a singular item from my own inventory into the inventory of any citizen, only 1 item is transferred even though more disappears from my inventory. Stacking multiple quantities of the same item onto each other inside a citizen`s inventory also destroys the whole stack, leaving only 1 of the item. Other transfer of items, such as shift clicking or manually moving them, works fine.

This bug started after the version 3.1 update, i updated my modpack today as usual, using the twitch application.
The bug might be related to an interaction with the Mouse Tweaks mod (which i think is responsible for the scroll-transfer function). 

I made a shareable link to show the bug in action.
https://streamable.com/k02wlf

Thanks in advance and have a nice day !

**Comment by Raycoms** [comment]
Reported to mousetweaks

**Comment by Dragolance117** [comment]
Thanks ! Have a nice day !
