### ISSUE TITLE
Missing hired citizens

### ISSUE THREAD

**Issue by Riddler92** [ldtteam/minecolonies#6079]
`##<!--` PLEASE DO NOT DELETE TOPICS AS YOUR ISSUE WILL GET CLOSED -->
### Prerequisites 

- [ x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.15.2
- MineColonies Version:0.13.291-ALPHA
- Structurize Version:0.13.86-ALPHA

## Problem description

Visitors hired in tavern dissapear and use up a housing slot, their name shows up blank in the house and I am unable to remove them from that house.
### Notes or related things

Their names do not show up in town hall and it shows that there is space for housing more citizens but when I do try to hire more, am unable to. Issue remains after restarting modpack (valhelsia 2) and restarting the computer. Currently there are 11 citizens with max capacity of 13 but the two spots are filled by these ghost citizens.
---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MatthiasMann** [comment]
Update - you are using a very old version (why did you even put the check mark there).
