### ISSUE TITLE
AI error from deliveryman

### ISSUE THREAD

**Issue by Stardestroyer0** [ldtteam/minecolonies#6080]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.3
- MineColonies Version: 0.13.440 ALPHA
- Structurize Version: 0.13.96 ALPHA
- Related Mods and their Versions: Valhelsia 3 pre 4 1.16.3 pack plus Mystical Agriculture, Agraddition, and Customization

## Expected behavior

Deliveryman picking up items from the warehouse and then delivering it

## Actual behavior

Deliveryman goes to warehouse worktable and then gives an AI error

## Steps to reproduce the issue
(we are playing on a server)
It happens every time he goes in the warehouse. We tried to empty it but we found out that every time we shift-click items in the racks and then shift-click items out the racks keep them and we also have them in our inventory, doubling it.
We tried to destroy all the racks and then repair the building with the builder's order but it happens every time. We also tried to replace or restart the deliveryman but to no avail. We found out that if the deliveryman goes to the warehouse when all the racks are destroyed (and the warehouse workbench full) it does not give an error but keep saying that the warehouse is full.
Since this is happening auto jobs assignment is not working anymore for grown up children in the colony.

### Logs

- latest.log: https://gist.github.com/Stardestroyer0/bbe16a38915afe514367cf75f8bfaa68
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
The log does not contain the error

**Comment by Stardestroyer0** [comment]
I updated the log file. It gets truncated but the full one should contain the error at the end

**Comment by ravenbuilder934** [comment]
Can you try updating and checking if it still occurs?

**Comment by Stardestroyer0** [comment]
We tried using the command /mc colony requestsystem-reset-all after reading the suggestion in another AI error posted here and we removed all the items that we probably duplicated in the rack and now it works. I will update the mod and let you know if the problem reappears

**Comment by Raycoms** [comment]
Same as https://github.com/ldtteam/minecolonies/issues/5672
