### ISSUE TITLE
no more citizens allowed

### ISSUE THREAD

**Issue by thijspoon28** [ldtteam/minecolonies#6084]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- MineColonies Version: minecolonies-0.13.450-ALPHA-universal.jar
- Structurize Version: structurize-0.13.96-ALPHA-universal.jar
- Related Mods and their Versions: -

## Expected behavior

i have space left for citizens in my tavern and in my houses, to children should be born and i should be able to get/hire new citizens from the tavern.

## Actual behavior

no children are born and i can't hire anyone from the tavern

## Steps to reproduce the issue

1. have a colony with space left in houses
2. make sure that children can be born
3. see how they are not being born
no clue what else to tell you. in my case 1 have 3 level 5 Asian housen and 1 level 2 Asian tavern.
i should have 19 spaces but i get no more than 16 citizens

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by someaddons** [comment]
what does the townhall show? its displaying the citizen/max limits

**Comment by thijspoon28** [comment]
townhall says 25/25 witch is weird as i have only 19 housing

**Comment by thijspoon28** [comment]
the 25 includes all my knights i think

**Comment by ravenbuilder934** [comment]
Have you completed the research to increase the cap to 50 citizens?

**Comment by thijspoon28** [comment]
aaaaaaa, i think we found the problem. so that one does include army

**Comment by thijspoon28** [comment]
my bad

**Comment by thijspoon28** [comment]
is there a way to cheat research so i can check?

**Comment by ravenbuilder934** [comment]
Do it in creative

**Comment by thijspoon28** [comment]
yes, it fixed it.
i was just being stupid i guess XD
i do suggest some form of warning response kind of deal saying that you are at the cap and u need to research it. because there are no messages or anything
