### ISSUE TITLE
Visitors getting in the way of attacking archers and when hit, gang up and kill the archer + tavern resident stats possible issue?

### ISSUE THREAD

**Issue by Knaxia** [ldtteam/minecolonies#6085]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: minecolonies-0.13.448-ALPHA-universal
- Structurize Version: structurize-0.13.94-ALPHA-universal
- Related Mods and their Versions: MineColonies Official Modpack v3.1 from Twitch (updated on 15/11/2020)

## Expected behavior
During the night / early morning, if there are mobs near by and the colony archers are attacking them, the visitors from the tavern should hide and / or not get in the way and / or not be able to get hit by the archer. If they do, they shouldn't retaliate.

## Actual behavior
If a visitor from a tavern is around and mobs / raid starts attacking, they will go crazy and just run around aimlessly in front of the guards. If an archer shoots and a visitor "intercepts" the arrow and gets it, all the visitors will turn hostile and gang up and slain the archer that attacked them.

The other guards will NOT react or try to defend the archer, they won't attack or taunt the visitors. The visitors seems very overpowered as they can kill a high level, well geared archer in a few hits then take all of the loot for themselves then return passive.

## Steps to reproduce the issue

1. Have a tavern with visitors
2. have archers near by, equiped and guarding/patrolling
3. Let it be night so random mobs will spawn like skeletons and zombies.
4. Wait and hope the visitors will actually run around and get hit by an arrow that was destined to an hostile mob
5. Mourn the death of your archer and look at the visitor run around with their armor/weapon.

SECONDARY ISSUE? :

I have also noticed that citizens who reside in the Tavern do not seem to respect the "house level cap" of their stats. I'm not sure if it's intended but my Tavern, being level 3 (maximum), my 4 citizen who reside in there have really high stats (sheperd with 80 focus, cowboy with 76 athletics). I'm not sure that if it's because the building is max level, it means it does as if their house was max level (5).

### Logs

No logs needed.

### Notes
This happened a few times already in the past, each time I end up slaughtering all the visitors to get the items back. I lost some of my oldest, highest level archers because of that.

I would also like to suggest the follow possible work around towards that issue:

-Add an option to toggle visitors from the tavern, so you can just use as housing.
-Have visitors hide inside the tavern at night and / or if hostile mobs are present near
-Have colony guards unable to hurt (no "friendly" fire?) on visitors

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Aduis1210** [comment]
had this about three times.

**Comment by shalazan** [comment]
This also applies to archer trainees who have the visitor walk in front of them when shooting at targets

**Comment by someaddons** [comment]
fixed
