### ISSUE TITLE
Worlds do not load or create. or they crash.

### ISSUE THREAD

**Issue by Naten0992** [ldtteam/minecolonies#6086]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: minecolonies-0.13.437-RELEASE-universal
- Structurize Version: structurize-0.13.96-ALPHA-universal
- Related Mods and their Versions: Minecolonies+Official+1.16.4+v1.0

## Expected behavior

Worlds loading properly

## Actual behavior

Worlds will not create or load

## Steps to reproduce the issue

1. try to create a world

### Logs

- latest.log: https://gist.github.com/Naten0992/18db1bb355f0be62c8bd60dd72f5b6ca#file-latest
- crashlog: 

### Notes
I tried about 5 or 6 times to create a new world and they either stopped at 54% or 83% and stops, or crashed

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Not a minecolonies bug.
