### ISSUE TITLE
Sorting warehouse crashes game

### ISSUE THREAD

**Issue by timstoop** [ldtteam/minecolonies#6087]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.448-ALPHA
- Structurize Version: 0.13.94-ALPHA
- Related Mods and their Versions: Valhelsia 2 with Immersive Engineering disabled

## Expected behavior

The game continues.

## Actual behavior

The game stops working. The minecraft app actually stays running, but all entities simply stop functioning and I can no longer interact with anything.

## Steps to reproduce the issue

1. Sort the warehouse.
2. 
3. 

### Logs

The logs are several 100s of MBs large, so I gzipped them and you can download them from these URLs:

- latest.log: https://nextcloud.timstoop.nl/s/GZMtjT4mjR3QT5C
- crashlog: (debug.log) https://nextcloud.timstoop.nl/s/TC5DRbrqQFTJ2Dc

### Notes

The only thing I did was press the Sort button on my lvl 3 warehouse. It was complaining about being full.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Pyrocantaes** [comment]
I can confirm the issue is back.. at least on servers. Managed to crash ours tonight, although this was about the 4th time I've sorted it since upgrading to level 3. The first sort threw a whole load of errors into the log but didn't result in a crash. The last sort did. Unfortunately I don't have access to the server so can't get the relevant section of the log. I'll see if I can repeat on my single player world.

**Comment by Raycoms** [comment]
Is there a good way to reproduce this on a fresh world?

**Comment by timstoop** [comment]
Maybe @Pyrocantaes knows, but I'm not aware of a way to reproduce it, at least, as I have no idea what might be causing this. I was hoping the logs would give a clue about that.

**Comment by timstoop** [comment]
In the same world, with only an upgrade of MineColonies to latest, it now works again. I'm not sure if you want to keep this open or not, but I have no way of duplicatng it at all anymore now.

**Comment by timstoop** [comment]
Bah, seems to be on and off, sometimes it works, sometimes it crashes. I cannot find a pattern.

**Comment by Raycoms** [comment]
But is there a way you can reproduce this happening like randomly? Even if it only happens in 50% of the cases?

**Comment by Raycoms** [comment]
Stale issue
