### ISSUE TITLE
plantation error - wrong plant fields

### ISSUE THREAD

**Issue by radoslawKnitter** [ldtteam/minecolonies#6088]
### Prerequisites 

- [ x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version:minecolonies-0.13.440-ALPHA-universal
- Structurize Version:structurize-0.13.96-ALPHA-universal
- Related Mods and their Versions:

## Steps to reproduce the issue

1. build plantation
2. wait to worker
3. the worker tries to plant outside his area

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by radoslawKnitter** [comment]
![2020-11-16_11 10 47](https://user-images.githubusercontent.com/20985316/99240728-3091c200-27fd-11eb-9dc6-4870c6bb23d6.png)

**Comment by Raycoms** [comment]
That is #5006 @AravanFox could you look at this?
