### ISSUE TITLE
after someone dies, some of the inhabitants climb onto the roof of the town hall

### ISSUE THREAD

**Issue by radoslawKnitter** [ldtteam/minecolonies#6089]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version:minecolonies-0.13.440-ALPHA-universal
- Structurize Version:structurize-0.13.96-ALPHA-universal
- Related Mods and their Versions:

## Expected behavior

![2020-11-16_11 06 36](https://user-images.githubusercontent.com/20985316/99240991-8b2b1e00-27fd-11eb-9ad5-8f88c98c7864.png)

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Yeah that happens, there is really nothing we can do agains that, eventually they come down again

**Comment by radoslawKnitter** [comment]
they will jump off like this - 2 have already died so

**Comment by Raycoms** [comment]
now that is a different problem, citizens should not jump off high places
