### ISSUE TITLE
[2829] Miner talks but doesn't work

### ISSUE THREAD

**Issue by kreezxil** [ldtteam/minecolonies#609]
After a while the miner gets down to a point where she wants a higher grade pickaxe than a stone one and asks "I need a pickaxe of at least Iron grade and at maximum Stone grade". At this point she'll accept both a stone and an iron axe, but won't use either and will stand there repeatedly asking for them, she'll shut up when you provide both but will not work.

I am thinking that you used a logic test in the wrong way and that she is reflecting this in her speech as there is no such thing as an iron_pickaxe that is at maximum stone_grade, however, the other way around would make sense that she should ask for a pickaxe of at least stone grade and at maximum iron grade.

And then I went into the shaft and there are some ores down there requiring harvest level 1 and 2, I destroy them all and she begins to build again.

So maybe the miner is saying the wrong thing and what she should be saying until you implement whatever it is you said was coming, "I don't know how to handle the block x y z", which will mean to the player to go and handle it theirselves.

**Comment by Raycoms** [comment]
That means she needs a pickaxe of iron grade and only can handle stone grade.
But I agree we should put this like "I can't mine Ore X - please upgrade my hut"

**Comment by kreezxil** [comment]
is that what that means

**Comment by Raycoms** [comment]
Is this still happening with the newest version?

**Comment by marvin-bitterlich** [comment]
Closing this for now
