### ISSUE TITLE
Worlds will not create or load

### ISSUE THREAD

**Issue by Naten0992** [ldtteam/minecolonies#6090]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: minecolonies-0.13.450-ALPHA-universal
- Structurize Version: structurize-0.13.96-ALPHA-universal
- Related Mods and their Versions: Minecolonies Official 1.16.4 v1.2
 Download

## Expected behavior

Worlds loading properly

## Actual behavior

Worlds will not create or load

## Steps to reproduce the issue

1. try to create a world

### Logs

- latest.log: https://gist.github.com/Naten0992/e6070ec4a7ddd2c70dd50c3129062dd0#file-latest
- crashlog: 

### Notes
I tried about 3 times to create a new world and it stops at 100% and never generates. I left it for over an hour and it never generated a world. 

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
This is a modpack issue, this is our mod page. This has nothing to do with the minecolonies mod. Please report this on discord.
