### ISSUE TITLE
i can't get children in my village

### ISSUE THREAD

**Issue by thijspoon28** [ldtteam/minecolonies#6095]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.3
- MineColonies Version: minecolonies-0.13.450-ALPHA-universal.jar
- Structurize Version: structurize-0.13.96-ALPHA-universal.jar
- Related Mods and their Versions: 

## Expected behavior
normally when there is place in the housing children are born, now that since the update to 450 this doesn't happen anymore.

## Actual behavior
nothing gets born

## Steps to reproduce the issue

1. try to get children and it won't work
2. dono what else to tell you
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

before you ask children born is on
i did the research for 100 citizens when i have 30
man and woman in same house check
hippieness is 9.9
there is a school. 
the is place in housing
i have waited for more than 8 irl hours at least and done some things during that time and never a child. however i am able to hire from the tavern.
also place in training and towers for knights
(btw the village will no longer sleep when someone is training as the facility does not have any beds, and the townhall does not display what is is supposed to display. probably the same issue)
this all changed when going to alpha 450

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Aduis1210** [comment]
Also Affected - 1.15.2 - latest Alpha (always)
