### ISSUE TITLE
Opening clipboard crashes the game.

### ISSUE THREAD

**Issue by antihutka** [ldtteam/minecolonies#6097]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.3
- MineColonies Version: 0.13.450
- Structurize Version: 0.13.96
- Related Mods and their Versions:

## Expected behavior

Working clipboard without a crash

## Actual behavior

Opening a clipboard crashes the game. Sometimes scrolling down is needed, sometimes it happens immediately.

## Steps to reproduce the issue

1. Start a single player game with this save: https://hammy.sk/download/crash-save.tar.xz
2. Open clipboard
3. If the game hasn't crashed yet, scroll down

### Logs

- latest.log: https://gist.github.com/antihutka/0e6d922e859deb0dd907aaf2f7877590 
- crashlog: 

### Notes

This started on 0.13.440 after teaching my stonesmelter stone brick -> cracked stone brick recipe, but removing the recipe didn't fix the issue, so it could be unrelated.
The game seems to work fine otherwise, I played for a while and didn't get a crash anywhere else.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by YeesterPlus** [comment]
i'm having this on vanilla mc 1.21

**Comment by Talyda** [comment]
> i'm having this on vanilla mc 1.21

You really need to open a new issue, and include version numbers and logs and such =)
An issue from over 4 years ago is not very likely to be the same thing!
