### ISSUE TITLE
Vampirism conflict

### ISSUE THREAD

**Issue by Chrysarius** [ldtteam/minecolonies#6098]
### Prerequisites

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context

- Minecraft Version: forge-1.16.4-35.0.18.jar
- MineColonies Version: minecolonies-0.13.450-ALPHA-universal.jar
- Structurize Version: structurize-0.13.96-ALPHA-universal.jar
- Related Mods and their Versions: Vampirism-1.16.4-1.6.2.jar

## Expected behavior
Server launches without issue

## Actual behavior
After most of the loading, forge crashes with the message that there's a non-character in the namespace of minecolonies:citizen.

## Steps to reproduce the issue
Launch a server with the listed versions of Vampirism/Minecolonies/Structurize/Forge

### Logs

- latest.log: https://gist.github.com/Chrysarius/7968e05b7bda8f397f8985315babd23f
- debug.log: https://gist.github.com/Chrysarius/403b2b2358af3d2af398393d11d91f33

### Notes
Is this a vampirism problem or a minecolonies problem? I can report it over there if need be, but the error message made it look like a minecolonies problem.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Since that works flawlessly without vampirism please report this to them.
