### ISSUE TITLE
[GENERAL] Create a unified way of initializing the mod. 1.11 and Upwards.

### ISSUE THREAD

**Issue by marchermans** [ldtteam/minecolonies#610]
_Current situation:_
A lot of core components are registered in a Static part of the most abstract variant class. (Eg. Buildings: AbstractBuilding)
This is not very flexible and hard to handle from an Extension point of view.

_Desired Situation:_
- A central initialization system that is handled from the Proxy classes. And by the Forge Registry system.
- Create a Interface which handles the initialization phases of the mod.
- Create implementations of this Interface to handle different initialization components of the mod. (Eg. InitializeBuildings to register the buildings at a appropriate point). This class should also fire events that allow for disabling and replacing entire components at a time.

**Comment by Wissi** [comment]
Over a year old. 
@OrionDevelopment Does it still need to be open?
I'll close and you can re-open if needed.
