### ISSUE TITLE
Pathing Issue

### ISSUE THREAD

**Issue by AndromedaFallen** [ldtteam/minecolonies#6100]
**Prerequisites**
[x] I am running the latest alpha version of MineColonies and Structurize for my Minecraft version.
[x] I checked the MineColonies/Structurize wiki and made sure my issue is not covered there.
[x] I made sure that this issue is not a duplicate of any existing issue.

**Context**

- Minecraft Version: 1.16.3
- MineColonies Version: 0.13.450
- Structurize Version: 0.13.96

**Expected behavior**
Colonists and travelers will properly pathfind up the jungle tavern ladder (T1)

**Actual behavior**
Colonists and travelers will get most of the way up the ladder, and try to go directly away from the ladder, resulting in them taking fall damage and eventually dying.

**Steps to reproduce the issue**

1. Go through normal colony building procedures with jungle style.
2. Build jungle tavern (T1)
3. Wait.

**Comment by AndromedaFallen** [comment]
couldn't figure out how to properly add a label, sorry

**Comment by Raycoms** [comment]
Screenshot please

**Comment by AndromedaFallen** [comment]
![2020-11-17_10 46 23](https://user-images.githubusercontent.com/71393014/99412145-65b41800-28c2-11eb-943c-7594e3221009.png)
![2020-11-17_10 46 26](https://user-images.githubusercontent.com/71393014/99412153-66e54500-28c2-11eb-8dc6-20dff83e563f.png)
![2020-11-17_10 46 28](https://user-images.githubusercontent.com/71393014/99412158-68af0880-28c2-11eb-9f2d-2ad252e76b3d.png)
![2020-11-17_10 46 29](https://user-images.githubusercontent.com/71393014/99412165-69e03580-28c2-11eb-9567-d4e428a2092f.png)
![2020-11-17_10 46 31](https://user-images.githubusercontent.com/71393014/99412171-6b116280-28c2-11eb-8e92-c47c2b7acd8f.png)
![2020-11-17_10 46 34](https://user-images.githubusercontent.com/71393014/99412174-6cdb2600-28c2-11eb-81dc-872554854c09.png)


its a bit long but i had to try to get some good images

**Comment by AndromedaFallen** [comment]
my solution to stop the people from dying is just to put a slab over the top trapdoor

**Comment by Raycoms** [comment]
can you show me where this ladder is leading?

**Comment by AndromedaFallen** [comment]
![2020-11-17_11 01 41](https://user-images.githubusercontent.com/71393014/99413950-4f0ec080-28c4-11eb-8c76-a1389fe8c2ff.png)

**Comment by AndromedaFallen** [comment]
![2020-11-17_11 02 07](https://user-images.githubusercontent.com/71393014/99413973-57ff9200-28c4-11eb-8048-0608cba3631a.png)

**Comment by Raycoms** [comment]
when you try to extend the ladder one more block after the trapdoor, will it work?

**Comment by AndromedaFallen** [comment]
yes, but they still fall off, just a lot less

**Comment by Raycoms** [comment]
if you replace the trapdoor entirely with a ladder?

**Comment by AndromedaFallen** [comment]
switching the trapdoor to a ladder and having a ladder above where the trapdoor was previously makes them entirely stop pathfinding off the ladder, it seems. just changing the schematic would be a fix then
