### ISSUE TITLE
World Load Crash

### ISSUE THREAD

**Issue by WenXin20** [ldtteam/minecolonies#6102]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.451
- Structurize Version: 0.13.94

## Expected behavior

- No crashes

## Actual behavior

- Loading the mod on my server caused it to crash.

## Steps to reproduce the issue

1.  Load the mod on a server.
2.  Crash

### Logs

- [Crash Report](https://gist.github.com/WenXin20/2df505dc0fefa19ea662cf1111eee7c5)

### Notes

- The previous version (0.13.448) doesn't crash the server.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
So, I double checked on this, and actually this mod:

	at com.fuffles.justanotherheadmod.common.item.AnotherSkullItem.func_150895_a(AnotherSkullItem.java:344) ~[?:1.0] {re:classloading,pl:runtimedistcleaner:A}


Is causing the crash. Please report to them

**Comment by WenXin20** [comment]
The previous version of minecolonies doesn't crash with it though. Do that mod need to change something?

**Comment by Raycoms** [comment]
Yes, we've added code to detect all subitems possible to detect modded fuel that uses nbt data for example. Now that item crashes when asking it for that kind of data

**Comment by WenXin20** [comment]
Ok, thanks
