### ISSUE TITLE
Not Enough Living Space in Colony

### ISSUE THREAD

**Issue by wowzentori** [ldtteam/minecolonies#6104]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

I am running Valhelsia 2 (2.3.0) updated 11/17/20

- Minecraft Version: 1.15.2
- MineColonies Version:  minecolonies-0.13.448-ALPHA-universal.jar
- Structurize Version:

## Problem description
Currently I have 2 level two houses, 1 tavern, level 2 town hall,  and 1 guard tower and I still cannot recruit more citizens. I had this issue yesterday too, with multiple level 3 houses and I could not recruit any citizens. Everything is up to date, and I've tried  a few fixes to no avail.

### Notes or related things
My english is a bit broken so I am sorry for misreading how to do this.

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Please fill out the issue template. Also, what exact version are you running? The devs often update multiple times a day, so you might not actually be up to date.

**Comment by wowzentori** [comment]
Any help??

**Comment by ravenbuilder934** [comment]
Update to https://www.curseforge.com/minecraft/mc-mods/minecolonies/files/3113971, this was fixed already
