### ISSUE TITLE
NPCs "sitting" in the air

### ISSUE THREAD

**Issue by xinpig** [ldtteam/minecolonies#6105]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: minecolonies-0.13.451-ALPHA 
- Structurize Version: structurize-0.13.95-ALPHA-universal
- Related Mods and their Versions: Enigmatica 5

## Expected behavior
NPC's not sitting in the air

## Actual behavior
NPC's sitting in the air
`https://i.imgur.com/AAvElVf.png`

I also have some that sit half in the ground or below it and die due to being in a wall

## Steps to reproduce the issue

I know I had a level 2 tavern built, decided to move it, did deconstruct, and then removed all the blocks by hand. Had my builder do the rebuild. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
https://i.imgur.com/AAvElVf.png

**Comment by someaddons** [comment]
must be building tags going bad somehow, like on upgrade or so

**Comment by xinpig** [comment]
If there's any files I can add that will help, let me know.

**Comment by Raycoms** [comment]
Definitively #5006 can you re-report this there?
