### ISSUE TITLE
Planter giving AI error.

### ISSUE THREAD

**Issue by Knaxia** [ldtteam/minecolonies#6109]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: minecolonies-0.13.454-ALPHA-universal
- Structurize Version: structurize-0.13.94-ALPHA-universal
- Related Mods and their Versions: MineColonies Official Modpack v3.1 from Twitch (updated on 15/11/2020)

## Expected behavior
Planter working fine?

## Actual behavior
Planter gave me an AI error and asked me to post it here, along with latest.log. She's stuck in place and tries to plant something without anything in her inventory. Seems like the sugar cane keep appearing in her inventory as she hits the air with the "knocking" sound.

![2020-11-18_18 54 32](https://user-images.githubusercontent.com/73440864/99602733-03e1d400-29d0-11eb-877a-c3a99e933a98.png)

## Steps to reproduce the issue

1. Have a plantation with a planter
2. ???
3. AI crashes!

### Logs

- latest.log: [latest.log](https://github.com/ldtteam/minecolonies/files/5563432/latest.log)

### Notes
She's the one who asked me, only following order, sir!

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Same issue as #5672
