### ISSUE TITLE
[EXT] Create a Registry for Buildings.

### ISSUE THREAD

**Issue by marchermans** [ldtteam/minecolonies#611]
_Current situation:_
A building is registered using addMapping as a static part of the AbstractBuilding Class. This fairly inflexible and a weird place to execute this kind of code.

_Desired solution:_
- Create a IForgeRegistry which currently holds the data that is stored in the maps of AbstractBuilding class.
- Initialize it in a Class created by Issue: #610.

**Comment by asiekierka** [comment]
Do note that Forge registries are primarily intended to be used for IDs which need to be (a) assigned automatically as integer<->name mappings, and (b) synchronized between the server and client. For instance, Minecraft tile entities do not use the Forge registry system, as they're synchronized by their names. You might want to consider writing a simpler registry of your own if you don't need both - it is generally a better idea.

**Comment by marchermans** [comment]
I am not sure what currently is needed yet. As for syncing.... It is a nice feature to have.... As well as a fully tested system. No need to invent the wheel twice so to speak. Especially with me not knowing what we might need in the future.

**Comment by Wissi** [comment]
@OrionDevelopment Still needed?
I'll close and you can re-open with comments if still needed.
