### ISSUE TITLE
Work orders bug

### ISSUE THREAD

**Issue by washinoboku** [ldtteam/minecolonies#6110]
Upgrading smeltery to tier 4, accidentally broke de main block (the smeltery block itself), and the builder stop placing blocks. After that I placed the smeltery block again and restart the build from tier 0 to tier 1. It was going good until to upgrade to tier 4 again and the builder stop placing block exactly where stops earlier. Looking in town hall work orders, shows two order for the same building (upgrade to tier 1 and tier 4) and cant cancel any.
There is some comand to solve this?

PD: I dont have any problems to upgrade or build other buildings.

Thanks!

**Comment by ravenbuilder934** [comment]
Please fill out the entire template

**Comment by Raycoms** [comment]
can you send us your world?

**Comment by Raycoms** [comment]
and fill out the template
