### ISSUE TITLE
Missing texture in menu screen

### ISSUE THREAD

**Issue by mickyyman** [ldtteam/minecolonies#6111]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: minecolonies-0.13.452-ALPHA-universal
- Structurize Version: structurize-0.13.96-ALPHA-universal
- Related Mods and their Versions:

## Expected behavior

To see a screenshot of the minecraft itself

## Actual behavior

![Image of Yaktocat](https://i.imgur.com/nJBuRvD.png)

## Steps to reproduce the issue

1.  Install latest 1.16.4 version through GDLauncher either from twitch or through zip file

### Logs

- latest.log: https://gist.github.com/mickyyman/bc5cfffd493711d4cff554d89c1707c1

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Not related to minecolonies the mod

**Comment by mickyyman** [comment]
Where would I post this? As this only happens with the modpack.

**Comment by Raycoms** [comment]
discord or modpack page on curse
