### ISSUE TITLE
Vanishing items if stacking them to citizens inventory

### ISSUE THREAD

**Issue by TheDucksheep** [ldtteam/minecolonies#6113]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: 0.13.452
- Structurize Version: 0.13.96
- Related Mods and their Versions: Forge 35.0.18 (Using the official modpack)

## Expected behavior

Stacking or placing items in their inventory should not disappear.

## Actual behavior

I am noticing that food **sometimes** disappears when I shift click (to stack it upon existing food) in their inventory.
It justs defaults to 1 food when I add like 40 ish of that food type.

## Steps to reproduce the issue

1. Access the inventory of a random citizen
2. Add 1 (eg. carrot) to their inventory
3. Shift click multiple carrots to their inventory.

I found another way to reproduce it: (best way to show the issue 😄)
1. add a stack of something to their inventory
2. right click the items to split it in 2x 32
3. add the 32 back to the original slot to get it back to 64.
4. after doing that a few times, you'll see the items vanishing

### Logs

- latest.log: 
Nothing is showing in my latest log that would be interesting. Sorry 😢 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Bart-Roels** [comment]
They don't always disappear. Sometimes you can just put a maximum of 1 type of the same item in their slot. Not only does this happen via shift, but also when you try to drag in their inventory!
