### ISSUE TITLE
Miner Pathfinding

### ISSUE THREAD

**Issue by BellePullman** [ldtteam/minecolonies#6116]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: 0.13.452
- Structurize Version: 0.13.96
- Related Mods and their Versions:

## Expected behavior

Miner descends mineshaft, begins mining out node at set level.

## Actual behavior

Miner approaches their destination on the surface, stands around "Working".  I think this common on relatively shallow levels where the X/Z coordinates are further from the hut block than the Y coordinate - the miner finds their way closer on the surface than via the mineshaft. If I break blocks in front/beneath them, they will walk closer to their destination.
I have also had miners try to reach their destination via the wrong Y level of the mine, one level up/down, and be unable to pathfind to their destination node unless I break the blocks in front/above or below of them.
![2020-11-13_21 08 49](https://user-images.githubusercontent.com/73602195/99680052-8c19b500-2a74-11eb-86a8-76f3a4297cb6.png)
(note, this miner is not attached to the sandstone mine in the distance, his stone mine is mostly behind the camera)

## Steps to reproduce the issue

1. Mine at a shallow level
2. Allow long corridors to develop
3. Miner path-finds to the destination on the surface not through the mine.

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
I've also noticed something close to this when I'm deep in my miner's mine and rally my guards.

**Comment by Raycoms** [comment]
this should be only the case if the miners path is obstructed through the mine, because of sand, gravel, lava or similar

**Comment by ravenbuilder934** [comment]
My guards definitely weren't obstructed, when I came back up, got them, and came back down they were fine

**Comment by Raycoms** [comment]
Guards yes, guards don't know how to pathfind in the mine, that is correct.

**Comment by BellePullman** [comment]
Hmm, there is a live example in my game atm (the other two miners are dead :P ) and the miner DID seem to be working in the area of some lava - not blocked from accessing the location, but trying to work through it.  However, removing the lava and then restarting the miner, and restarting Minecraft, have had no effect, the miner is still standing on a path looking clueless!  It is quite a large level, 88 nodes, and it has wrapped around the mineshaft to "behind" the ladder.  It's actually visible on the screenshot above, the lava to the right on the sandstone mineshaft.

**Comment by Raycoms** [comment]
The miner will try to follow a very specific path to the next node to mine (that might not always be the direct path). That path will follow the nodes they had to mine out to arrive there. If one of these nodes is obstructed it might not work. Could you send us that world?

**Comment by BellePullman** [comment]
How would I do that?  I have had miners blocking off paths their predecessors had made, but I don't think that's the case in this mine.

**Comment by Raycoms** [comment]
upload it it somewhere

**Comment by BellePullman** [comment]
Uhh, let's see if this works?   https://drive.google.com/file/d/1lWwUh_bMfMVa9c7D42ocTg0kBY2oMkM1/view?usp=sharing

**Comment by Raycoms** [comment]
I don't have permission
