### ISSUE TITLE
Builder not doing anything after changing "builderinfiniteresources" to true

### ISSUE THREAD

**Issue by MichelLaPerche** [ldtteam/minecolonies#6117]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: 0.13.452-ALPHA
- Structurize Version: 0.13.96-ALPHA
- Related Mods and their Versions:

## Expected behavior
 The builder would be building and moving around

## Actual behavior
 Whenever i change "builderinfiniteresources" to true in the "minecolonies-server.toml" file, the builder stops doing anything and just stands there.

## Steps to reproduce the issue

1.  Change "builderinfiniteresources" to true in the config file
2.  Load the World
3.  The builder stops doing anything

### Logs

- latest.log:  https://gist.github.com/MichelLaPerche/a1f8b4fc75cade0612c88c2550acac43
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Yeah it's not anything we support at the moment since you can just "paste" buildings in creative mode anyway.
