### ISSUE TITLE
Builder requires Grass Block to place under huts in certain circumstances.

### ISSUE THREAD

**Issue by gattsuru** [ldtteam/minecolonies#6118]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: 
- Structurize Version: minecolonies-0.13.437-RELEASE-universal.jar or minecolonies-0.13.452-ALPHA-universal, structurize-0.13.96-ALPHA-universal.jar
- Related Mods and their Versions: N/A

## Expected behavior

When a schematic is placed over an open area, and the schematic includes blocks which obey gravity (such as gravel), I would expect the builder to place dirt, cobble, or a similar block underneath; or to place the block over air and it to fall.

## Actual behavior

The Builder requests biome-specific exact blocks to fill the remaining space, which in many cases will be the Silk Touch-only Grass block.
![buildovercave1](https://user-images.githubusercontent.com/39036909/99717596-9a1d0500-2a77-11eb-961a-349e746bcf29.png)
![buildovercave2](https://user-images.githubusercontent.com/39036909/99717594-99846e80-2a77-11eb-826a-4f1ad4dc3b6e.png)
![buildovercave3](https://user-images.githubusercontent.com/39036909/99717592-98ebd800-2a77-11eb-838e-9ed4561f4358.png)

## Steps to reproduce the issue

1.  Place a Town Hall.
2.  Place a Dark Oak Builder Tier 1 schematic, such that the gravel block would have an air pocket underneath it.  In Creative, either attempting to build the schematic in mid-air, or making a 1-deep layer of dirt with a 3-block deep layer of air underneath as in the images above, is easiest.  During survival play, the problem is more likely to be encountered from small caves or underlying pockets of air, or repaired creeper-holes.
3.  Give the Builder all non-Grass Block requested items, including spare dirt.  The builder will not complete assembly, usually stopping part-way through the first vertical layer.  Cancelling and restarting the build, or cancelling the Grass Block request, only causes the builder to move around a bit.

### Notes

This _seems_ to be caused by gravity-obeying blocks (gravel in these tests, but I assume sand would have same issue) without underlying spruce placeholder blocks in the schematic; the number of requested Grass Blocks reflects exactly the number of gravel in a Birch Citizen Hut, for example.

Placing any stable block under the location where the gravity-obeying solves the problem, though you may have to restart or cancel the Builder to clear the Grass Block request.  Modifying the schematic to use Andersite instead of Gravel, or to have a layer of spruce placeholder blocks underneath, resolves the issue, but may be undesirable.

Some early-game schematics with this issue include:

* Dark Oak and Medieval <log type> Alternative Builder 1, 
* Acacia and Birch, Citizen Hut 1s
* Birch Farmer 1
* Birch Warehouse 1
* Birch and Dark Oak Blacksmith 1
* Birch Restaurant 1.
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
1. Why did you check the "latest alpha" box? You're over 10 versions behind.
2. Just giving them dirt should work, no need for silk touch

**Comment by Raycoms** [comment]
ohh nice, you figured it out!

**Comment by gattsuru** [comment]
Sorry, copied the wrong version number.  Issue replicates in minecolonies-0.13.452-ALPHA-universal (and the github commit from the 11/15/2020 evening, since I'm a cheater with the research times).

EDIT: have tried throwing several stacks of dirt onto Builder, and into Builder Hut inventory.  It is specifically Grass Blocks and only Grass Blocks that seem to let them finish assembly (or putting a block under the gravity-obeying block location), unlike when the Builder is filling a spruce placeholder block.

**Comment by Raycoms** [comment]
I was wondering for a while how to reproduce this. Now that is sth I can work with =D Will be fixed by tomorrow =D (will require a structurize update then, though)

**Comment by Talyda** [comment]
Oh! I'm really glad you figured that out too! I spent AGES trying to work it out when I was upgrading an Asian builder to level 3 (I think it was level 3) I couldn't even FIND grass blocks in the schematic!

**Comment by Spongman** [comment]
what version is this released in? i'm running 0.13.479-BETA-universal on 1.15.2 and it's still asking for grass blocks.

**Comment by Raycoms** [comment]
that particular fix made it only to 1.16 so far

**Comment by Spongman** [comment]
ok, thanks for the quick response.
