### ISSUE TITLE
Warehouse Sorting

### ISSUE THREAD

**Issue by camcamhow** [ldtteam/minecolonies#6119]
### Prerequisites 

- [❌] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [✔] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [✔] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.436-RELEASE
- Structurize Version: 0.13.94-ALPHA

## Problem description

My server keeps crashing when clicking the sort button in the ware house not sure whats causing this issue

### Notes or related things

https://drive.google.com/file/d/19sRQ08UZdEGawDguWkycMKzdOQRVOw9q/view?usp=sharing server logs

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Please update to the latest alpha and check if this still occurs.

**Comment by Raycoms** [comment]
Duplicate #6087
