### ISSUE TITLE
No extension for file: minecraft:missingno - client crash

### ISSUE THREAD

**Issue by radoslawKnitter** [ldtteam/minecolonies#6120]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: 0.13.452-ALPHA-universal
- Structurize Version: 0.13.96-ALPHA-universal
- Related Mods and their Versions:

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- [latest.log](https://gist.github.com/radoslawKnitter/a1cb45e0b11b4ab370d0836043f33088)
- [client crash log ](https://gist.github.com/radoslawKnitter/740de1b91cc7e4927cd2eea5b1b8439b)

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by radoslawKnitter** [comment]
this bug is made by Stone Smeltery - If he wants to see what he needs in the building menu, the game crashes with this error

**Comment by Raycoms** [comment]
Also crashes in the building menu, do you have a crash for that too? What I'm seeing in the log is only the clipboard

**Comment by radoslawKnitter** [comment]
not building but worker
[log](https://gist.github.com/radoslawKnitter/1dfeb58491c52f57c706725abf320dc2)

**Comment by radoslawKnitter** [comment]
ok i found how to trigger it.
the only fuel it can use should be charcoal, and charcoal should be created by it.
I bet the loop comes out.

after adding the second fuel + reset request system. it does not crash

**Comment by Raycoms** [comment]
Yes, I'll fix the crash, the reason that you need more fuels is fixed though, we can't changed that.

**Comment by Raycoms** [comment]
We got a loop detection for this.
