### ISSUE TITLE
4 issues

### ISSUE THREAD

**Issue by xiaobbl** [ldtteam/minecolonies#6121]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.15.2
- MineColonies Version:0.13.453
- Structurize Version:
- Related Mods and their Versions:

## Actual behavior
1.the archer trainee and combat trainee stand by the hut block at night instead of going to beds..
2.the combat trainee stand for the whole day without doing anything!(except eating)
![2020-11-20_22 27 53](https://user-images.githubusercontent.com/73425315/99814692-48ae6c00-2b84-11eb-9b64-109c3f13aeda.png)
3.the baker gives AI issues while receiving requests.
4.hmm...(and he is still moving as walking!he can combat as well!scary!)
![2020-11-20_22 18 42](https://user-images.githubusercontent.com/73425315/99815033-c1152d00-2b84-11eb-87ff-3372aa214a50.png)

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: https://gist.github.com/xiaobbl/15e716faf778e50d4b5acd9365d41170
latest.log for issues 3(the baker named Walter Y. Crocker)
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
4 was recently fixed, 1+2 are #5006
