### ISSUE TITLE
Recruit and max Town people

### ISSUE THREAD

**Issue by azluun** [ldtteam/minecolonies#6123]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: 0.13.452 ALPHA
- Structurize Version: 0.13.96 ALPHA

## Problem description

I have houses to live in, (They are empty now) and I have jobs without peoples. Mut when I try to recruit a wanderer the game says "you lack living space in your colony". In my town hall it says 11/11 (In the config files it set to 10 starter people and one little guy was born. When there was only 4 starter people the issue was the same, my kid born when I changed it to 10.

### Notes or related things

We are using:
Biomes O plenty
AquaCulture2
ImmersivePortals
Neat
Nei
and AI Improvements

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
fixed in latest
