### ISSUE TITLE
Emerald Block expansion needs better display

### ISSUE THREAD

**Issue by Nikademus** [ldtteam/minecolonies#6124]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: minecolonies-0.13.456-ALPHA-universal
- Structurize Version: structurize-0.13.96-ALPHA-universal
- Related Mods and their Versions:

## Expected behavior

There would be an indicator of how many emerald blocks have been put into Warehouse.  I wasn't aware that you can put up to 5 emerald blocks into the warehouse.  The wiki doesn't mention it, and the interface simply says 0/1 even if you put one in.   It should say 0/5, 1/5, 2/5, etc.

## Actual behavior

Put in an emerald block, and it seems like it disappears.

## Steps to reproduce the issue

1.  Upgrade warehouse to level 5
2. Put an emerald block into the warehouse hut slot
3.  No acknowledgment happens, no visual indicator.   The racks do expand, however.

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
I'll add this to the wiki, but I agree that it should be 0/5 instead of 0/1
