### ISSUE TITLE
Opening “Decoration” on builders tool crashes the game

### ISSUE THREAD

**Issue by Closhee** [ldtteam/minecolonies#6128]
### Prerequisites 

- [ x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- MineColonies Version:
- Structurize Version:
- Related Mods and their Versions:

## Expected behavior
 I would expect to be able to scroll through the different decorations without the game freezing or crashing.

## Actual behavior
 When I open the decorations tab and try to scroll through the different decorations the game either freezes for an extended period of time or crashes. I first noticed this when I was looking at markets. The black market stand cause my game to freeze for 5 minutes and eventually crashed it. Then I wasn’t even able to scroll down to paths. Eventually I was able to get to paths but I froze/crashed my game about 5 time.

## Steps to reproduce the issue

 

1.  open up the decorations tab on the builders tool
2.  try to scroll through types of decorations and then the decorations under that type (marketplaces > market stands)
3.  The game will freeze, lag, or crash

### Logs

 I don’t sorry 

- latest.log:  I’m not sure how to get this. My discord is Closhee#1129
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
You find it in the logs folder (next to the mods flder)

**Comment by Raycoms** [comment]
still wating for logs, reopen when you got some
