### ISSUE TITLE
Build Orders unable to be deleted and workers “working” while standing in one place

### ISSUE THREAD

**Issue by Closhee** [ldtteam/minecolonies#6129]
### Prerequisites 

- [ x] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- Structurize Version: 0.13.96
- MineColonies Version (if related bug): 0.13.465
- Related Mods and their Versions:

## Expected behavior
 Being able to delete work orders and builders doing their job

## Actual behavior
 if the glitch happens a work order gets stuck in queue. It cannot be reset with commands or through town hall. 

 (I posted a video in discord) 

## Steps to reproduce the issue

 it seems to happen when I cancel a build and then delete/pick up the identity block. 

1.  Try to begin a build. 
2.  cancel the build and remove the identity block
3.  the work order get glitched in town hall and cannot be removed 

### Logs

 I do not have a crash log. 

- latest.log: 
- crashlog: 

### Notes
 I was sent here from the discord I am Closhee#1129 it seems other people have experienced the same issue. 

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
same as #6129

**Comment by ravenbuilder934** [comment]
What? This *is* #6129.
