### ISSUE TITLE
2nd page of warehouse GUI looks weird

### ISSUE THREAD

**Issue by ravenbuilder934** [ldtteam/minecolonies#6134]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 459 alpha
- Structurize Version: 94 alpha
- Related Mods and their Versions: none

## Expected behavior
Only the 0/3 counter (introduced in https://github.com/ldtteam/minecolonies/pull/6130) would show.

## Actual behavior
Both the 0/3 and the old 0/1 counter show. (I had an emerald block in my inventory when taking the screenshot below.)

![2020-11-21_13 24 05](https://user-images.githubusercontent.com/63612548/99885834-52c08100-2bfd-11eb-9b1f-22690a69a920.png)

## Steps to reproduce the issue

1. Build a warehouse level 5
2. Put an emerald block in your inventory
3. Look at page 2 of the warehouse gui

### Logs

- latest.log: 
- crashlog: 

### Notes
https://github.com/ldtteam/minecolonies/issues/6124 says that up to 5 emerald blocks can be used, but the counter says 0/3 instead of 0/5.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
It's only 3, not 5

**Comment by Raycoms** [comment]
the 0/1 is a counter of how many emerald blocks are already there

**Comment by ravenbuilder934** [comment]
Already there? But I had an emerald block in my inventory. Shouldn't it have read 1/1?

**Comment by Raycoms** [comment]
It's the same type of GUI the building has, so that is like "emerald blocks in the building".

**Comment by ravenbuilder934** [comment]
Why does it care about those? I thought you needed to have the block in your inventory for it to work.

**Comment by Raycoms** [comment]
because it's the same functionality as at the builder

**Comment by Raycoms** [comment]
same code

**Comment by ravenbuilder934** [comment]
Oh, for the second page of the builder's hut?

**Comment by Raycoms** [comment]
ye

**Comment by ravenbuilder934** [comment]
Okay, then I guess this issue is for the warehouse caring about what it has and not what the player has :D

**Comment by Raycoms** [comment]
It cares about both probably (same for the builder)

**Comment by ravenbuilder934** [comment]
But I had an emerald block in my inventory and it still said 0/1

**Comment by Raycoms** [comment]
Should be the same as in the builder, it's green because you got one, but there is none in the hut

**Comment by ravenbuilder934** [comment]
Okay, then I need to use the resource scroll more :P
