### ISSUE TITLE
Waypoints unable to be removed.

### ISSUE THREAD

**Issue by Closhee** [ldtteam/minecolonies#6138]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context  

- Minecraft Version: 1.16.4
- MineColonies Version: 0.13.456 ALPHA
- Structurize Version: 0.13.96 ALPHA
- Related Mods and their Versions:

## Expected behavior
 I was told by putting a block on top of a way point for 5 minutes the waypoint would go away.

## Actual behavior
 After 2 hours, I had 5 different waypoints I was trying to get rid of (I checked at 5, 30, 60 and 120 minutes and have one still running) the waypoint won’t despawn and cannot be removed.

## Steps to reproduce the issue

 

1.  Use the builder’s tool to open decorations > Infrastructure > waypoint and have a builder place a waypoint 
2.  once built place sand or another block on top of the waypoint and wait a few minutes 
3.  Remove the block and the waypoint is still there.

### Logs

 I do not have one. My discord is Closhee#1129 if you could help me find/make one

- latest.log: 
- crashlog: 

### Notes
 sent here from the discord 

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
I just double checked this. Put a block inside the waypoint position and it disappeared fine, sth else must be interfering here that is not from our mod.
