### ISSUE TITLE
Colorblind friendly citizen happiness index

### ISSUE THREAD

**Issue by FesterHead** [ldtteam/minecolonies#6139]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: `1.16.4`
- MineColonies Version: `0.13.458-ALPHA-universal`
- Structurize Version: `0.13.96-ALPHA-universal`

## Problem description

The happiness system is color-based which makes it difficult for colorblind people to know a citizens happiness index.
For example, on the wiki page I see two 'colors'; light - most likely yellow - and dark - everything else.

### Notes or related things

Recommended course of action:  augment the happiness index with an icon and/or number to help us colorblind folks know the correct value.

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
We definitely can add a nice hover text there over the bubbles.
