### ISSUE TITLE
Bugs w/ Capturing Citizens using other Mods' Items

### ISSUE THREAD

**Issue by WenXin20** [ldtteam/minecolonies#614]
### Mod versions

Forge 2221
Minecolonies v0.6.2867
[Grim Pack](https://minecraft.curseforge.com/projects/grim-pack) v3.4.17.53 (Originally reported here at grim3212/grim-pack#75)
[Extra Utils](https://minecraft.curseforge.com/projects/extra-utilities) v1.3.0

### Expected behavior

- To be able to capture a villager and to be able to place him/her somewhere else.
- To keep any inventory items.

### Actual behaviour

- If you try to place a captured villager down, it teleports back to the original point instead of where you placed him/her.
- The villager's inventory is also cleared.

### Steps to reproduce the problem

1. Get the Pokeball from the Grimpack Mod or the Lasso from Extra Utils 2.
2. Capture a Villager that has something in its inventory
3. Try to place the villager at a different spot.
4. Then check to see if the villager kept its items.

**Comment by marvin-bitterlich** [comment]
Villager or Citizen?

Citizen teleport when stuck because mc pathfinding is weird. Capturing citizens is a use case I really don't get. What do you accomplish with that?

**Comment by WenXin20** [comment]
I meant Citizens.
As for uses, I was just testing things out in creative when I found that bug, but maybe for easier relocation when trying to get buildings built while in creative.

**Comment by marvin-bitterlich** [comment]
Their intended behavior is to not get stuck, so teleporting as a last resort is intended. 

For the inventory, we are currently overhauling that. No idea what caused that

**Comment by WenXin20** [comment]
Ok, the inventory disappeared after being spawned back in from the lasso. And does the citizen think it is stuck when its suddenly in a different spot when spawned back in with the item?

**Comment by Raycoms** [comment]
Its possible that the citizen loses his position on the way and might think
he is stuck because his position hasn't changed in 2 minutes.

2017-02-16 19:37 GMT-02:00 WenXin20 <notifications@github.com>:

**Comment by WenXin20** [comment]
Ok, that makes sense.
