### ISSUE TITLE
the cook distributes food to strangers

### ISSUE THREAD

**Issue by radoslawKnitter** [ldtteam/minecolonies#6141]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: 0.13.458-ALPHA-universal
- Structurize Version:0.13.96-ALPHA-universal

## Problem description
the cook distributes food to hungry people outside the colony. If a hungry person from outside the colony will only be standing and not eating it, he will get as much as he will get into his inventory.

### Notes or related things

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
> hungry people outside the colony

Do you mean colonists? Or players?

**Comment by radoslawKnitter** [comment]
players
