### ISSUE TITLE
[1.12.2] Error messages are sent in the chat to all players in the server

### ISSUE THREAD

**Issue by ExDomino** [ldtteam/minecolonies#6143]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.12.2
- MineColonies Version: minecolonies-1.12.2-0.11.841-ALPHA
- Structurize Version: structurize-1.12.2-0.10.277-RELEASE
- Related Mods and their Versions: -

## Expected behavior
Error message are showed in the chat only for the player concerned.

## Actual behavior
The error message is shown in the chat like the player concerned typped it and sent it to all players like normal chatting.

## Steps to reproduce the issue

I'm not the player concerned by the bug, I just saw another player typping an english message in the chat despite the server is french and after aking to him, he said it's an error message from MineColonies. All players have seen this error message like the concerned player has typped it himself.

### Logs

I have no log, it's not a crashlog.

### Notes

I have no notes.

## Viewers

I have no viewers.

**Comment by someaddons** [comment]
1.12 is no longer upadted
