### ISSUE TITLE
Citizen GUI crashes game - java.lang.NullPointerException: Ticking screen

### ISSUE THREAD

**Issue by mcsunnishines** [ldtteam/minecolonies#6144]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: forge-1.16.3-34.1.23
- MineColonies Version: minecolonies-0.13.452-ALPHA-universal
- Structurize Version: structurize-0.13.96-ALPHA-universal
- Related Mods and their Versions: theoneprobe-1.16-3.0.4-beta, EasyPaxel(1.16.3)+-+1.0.4, jei-1.16.3-7.6.0.49

## Expected behavior

Citizen has a request, player can open citizen GUI or clipboard to see what they need. 

## Actual behavior

Citizen has a request, player clicks to open citizen GUI or clipboard and game crashes. 

## Steps to reproduce the issue

1.  Load game
2.  Wait for citizen to have a request
3.  Click citizen GUI or use clipboard

### Logs

- latest.log: 
https://gist.github.com/mcsunnishines/e4a402fa0862ead5065523288d3d204a
- crashlog: 
https://gist.github.com/mcsunnishines/2a64e5d4e2d6ac4a3ab900bc1b175546

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Are you using any tool mods?

**Comment by Raycoms** [comment]
This is a tool mod issue that is having issue with the tool classes. That mod has to fix it.

**Comment by mcsunnishines** [comment]
Yes, I was. Sorry, I've been sick. Thank you. I took that mod out and all is well.
