### ISSUE TITLE
Unable to place buildings

### ISSUE THREAD

**Issue by Closhee** [ldtteam/minecolonies#6145]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: 0.13.472-ALPHA
- Structurize Version: Structurize 0.13.100 RELEASE
- Related Mods and their Versions:

## Expected behavior
 to be able to place build huts to then build and upgrade

## Actual behavior
 I click the green check on the build tool and then nothing happens no construction tape, no build hut block (it isn’t underground) 

 I posted in the discord a video

## Steps to reproduce the issue

1.  pick any hut block
2.  try to place it using the build tool
3.  nothing appears

### Logs

- latest.log: 
- crashlog: 

### Notes
 it seems to be a server issue rather than a single player issue since both me and my friend can still place them in single player but not on our server which is up to date as well

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
We'll need a log there

**Comment by Raycoms** [comment]
Fixed in latest
