### ISSUE TITLE
Trying to build a townhall but dimension config is bugged.

### ISSUE THREAD

**Issue by Hatsu-m** [ldtteam/minecolonies#6146]
### Prerequisites 

- [X ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context  0.13.473

- Minecraft Version: 1.16.4
- MineColonies Version:0.13.473
- Structurize Version:0.13.100
- Related Mods and their Versions:All the mods 6 modpack

## Expected behavior
Town hall build

## Actual behavior

It pops up with a message saying building in other dimensions is prohibited 

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Can you try the newest alpha too?

**Comment by Hatsu-m** [comment]
> Can you try the newest alpha too?

I did im on .473

**Comment by Raycoms** [comment]
Still a problem in 473?

**Comment by Hatsu-m** [comment]
Yes. It just pops up saying that building in different dimensions is not allowed and to check the config. Even though I'm on the overworld.

**Comment by ArmlessMatt** [comment]
We also have the dimension message when we try to place a supply camp in the overworld. We're using the latest alpha version.

**Comment by Raycoms** [comment]
That is weird, I just tried the latest alpha and it works very well for me in single and multiplayer without a problem.

**Comment by ravenbuilder934** [comment]
Maybe it's only on servers?

**Comment by Raycoms** [comment]
I tried on a server too

**Comment by someaddons** [comment]
forge versions?

**Comment by Raycoms** [comment]
I tried 35.0.1 and 35.1.1

**Comment by Hatsu-m** [comment]
I editied the config on the world itself it worked i think Quark is making the overworld not register as the regular dimension

**Comment by ArmlessMatt** [comment]
Yes we're also using quark with the quark_realistic level generation. Is there a way to configure the default dimension for minecolonies ?

**Comment by Swantsy** [comment]
same problem, we did change the config file to allow in other dimensions but it is still not working. Pack is ATM 6 latest version 1.3.3 that came out today.

**Comment by Swantsy** [comment]
ok, it looks like this was a temporary bug, latest version new server file on 1.3.3 did work. It looks like there was a forge build that messed up the dimensions, don't know which one though.

**Comment by Raycoms** [comment]
Great =)

**Comment by ViRb3** [comment]
Indeed, the problem was Forge's incorrect dimension handling before https://github.com/MinecraftForge/MinecraftForge/pull/7513 was merged. Check the issue linked above for help with fixing an old world.

**Comment by smmmadden** [comment]
seeing the same on 35.1.0 Forge 1.16.4 with minecolonies 0.13.486-alpha.  Updating the minecolonies-server.toml for 	allowotherdimcolonies = true
and a restart allowed us to place buildings again in the same colonies.

**Comment by ravenbuilder934** [comment]
If you updated forge, you wouldn't have needed to change the config

**Comment by smmmadden** [comment]
That may be true, but a <1 minute change fixes the issue on the "recommended forge build".  Taking the latest untested build, upgrading servers, clients, modpack and retesting of all mods (assuming they work on the latest build) is a much higher effort and time to do.  Config files are there so that changes like these can be made quickly so that the user can continue game play. :-)

**Comment by ravenbuilder934** [comment]
The forge team tries to save breaking changes for new Minecraft versions. Even though it's untested, the latest should work fine. Direct quotes from a forge team member: "Latest always has the newest bug fixes" "We always recommend latest over recommended"
