### ISSUE TITLE
Block placement/Break delay doesn't influence in-game

### ISSUE THREAD

**Issue by Rexeit** [ldtteam/minecolonies#6147]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: minecolonies-0.13.473-ALPHA-universal
- Structurize Version: structurize-0.13.100-RELEASE-universal
- Related Mods and their Versions:

## Expected behavior

Changing the block placement and break delay to the minecolonies-server.toml (to the minimal or maximum value) should change the speed of the builders

## Actual behavior

Changing these values don't change the speed of the builders and are building at exactly the same speed

## Steps to reproduce the issue

1. Change "#Delay after each block placement (increasing it increases the delay). [Default: 15, min: 1, max: 500]
	#Range: 1 ~ 500
	builderbuildblockdelay = whatever the number, at 500 they're still as fast, at 1 still as slow"
2. Changing the value for "#Delay modifier to mine a block (decreasing it decreases the delay). [Default: 500, min: 1, max: 10000]
	#Range: 1 ~ 10000
	blockminingdelaymodifier = " have the exact same result
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Rexeit** [comment]
I talked with other peoples
Basically, the config files (both minecolonies-server and minecolonies-client) just aren't applied
Whatever you change in them, in-game, nothing changes and still stay as "basic" minecolonies config

**Comment by Raycoms** [comment]
Just tested this, this works fine, that is either are user problem or a forge problem, but it works perfectly for me.
