### ISSUE TITLE
Where is the config file that is referenced in wiki?

### ISSUE THREAD

**Issue by smmmadden** [ldtteam/minecolonies#6148]
### Prerequisites 

- X I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- X I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- X I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: minecolonies-0.13.456-ALPHA-universal
- Structurize Version: structurize-0.13.96-ALPHA-universal

## Problem description
I was looking for the references to CONFIG file on both the server and client and found no config files with any settings matching the wiki page (https://wiki.minecolonies.ldtteam.com/source/systems/border).  Can you point me to where they are?

### Notes or related things
Not an issue, just a question.  So far my wife and I are loving the mechanics and all the attention to detail added to this mod.  By far one of the best I've used in the last 5 years!  Nice work Team! :-)

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Go to your minecraft folder, then /saves/nameOfYourWorld/serverconfigs/minecolonies-server.toml (this is different in 1.15).

By the way, further questions would be better for the Discord at https://discord.minecolonies.com
