### ISSUE TITLE
1.16.4 Running the newest version of both minecolonies and structurize doesn't boot

### ISSUE THREAD

**Issue by GetOnThat** [ldtteam/minecolonies#6149]
Using current newst versions on Curse:
minecolonies-0.13.437-RELEASE-universal(1)
structurize-0.13.100-RELEASE-universal(1)

Same thing with:
minecolonies-0.13.465-BETA-universal(1)

**Comment by ravenbuilder934** [comment]
Neither of those MineColonies versions are the newest. Please try with the latest minecolonies _alpha._

**Comment by GetOnThat** [comment]
Where do i find those on Curse or somewhere else?

**Comment by ravenbuilder934** [comment]
On Curse, but you need to click the View All button

**Comment by GetOnThat** [comment]
thank you very much

**Comment by ravenbuilder934** [comment]
No problem 😄
