### ISSUE TITLE
Miner broken (#bug)

### ISSUE THREAD

**Issue by Thanaen** [ldtteam/minecolonies#615]
### Minecolonies version 0.6.5

version X.X.XXXX or curse Version 7.1.6251.1229 Beta

### Expected behavior

- The miner should ask for tools, and work

### Actual behaviour

- Doesn't ask for anything, and doesn't work

### Steps to reproduce the problem

1. Get a miner
2. Cry
3. Cry more
4. Profit

###Extra knowledge
Steps done: 
- Fire / Hire
- Killed the villager to hire another villager
- Repair the mine
- Upgrade the mine
- Hire differents villagers
- Give the miner everything a miner would need, even if he doesn't ask for anything
- Make space in his inventory
- Try to recall the worker

**Comment by Cyranth** [comment]
I had similar issue, gave him cobble stone and he went back to work

**Comment by Thanaen** [comment]
I tried giving him cobblestone, it didn't work :(

**Comment by marvin-bitterlich** [comment]
closing this in favor of one big issue
