### ISSUE TITLE
AI Bug.

### ISSUE THREAD

**Issue by Minion0ne** [ldtteam/minecolonies#6150]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.2
- MineColonies Version: minecolonies-0.13.473-ALPHA-universal.jar
- Structurize Version: structurize-0.13.100-RELEASE-universal.jar

## Problem description

![Capture](https://user-images.githubusercontent.com/11524320/100150009-99fc7b00-2e64-11eb-8880-f5ba78d4b6c4.PNG)

### Notes or related things

https://gist.github.com/Minion0ne/410789043b0aa64527f1c3995ba2b0d3
---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Unfortunately this log doesn't contain the actual AI issue.

**Comment by Raycoms** [comment]
same as https://github.com/ldtteam/minecolonies/issues/5672
