### ISSUE TITLE
Max population "stuck" 

### ISSUE THREAD

**Issue by Vitoush** [ldtteam/minecolonies#6151]
Hello,
i am playing Minecolonies on 1.15.2 and i have an issue ....
when i build a house it will increase max population but when i upgrade one of houses it wont increase max pop. 
it will just make space for citizen move in from other houses ....

for example ..... i have my four starter citizens and zero houses (4/0) then i build five houses (4/5) and then i upgrade two of them (4/5 remains) 

thanks for answers and sorry for grammar :D

**Comment by ravenbuilder934** [comment]
Update, this was already fixed
