### ISSUE TITLE
[1.16.4] Visitor entity set to zero pos, report to mod author

### ISSUE THREAD

**Issue by Sandriell** [ldtteam/minecolonies#6152]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: minecolonies-0.13.473-ALPHA-universal
- Structurize Version: structurize-0.13.100-RELEASE-universal
- Related Mods and their Versions: Modpack: All The Mods 6 v1.3.1

## Expected behavior
Expect no error.

## Actual behavior
The following error spams the log dozens of times every second: https://gist.github.com/Sandriell/a261263f462d2f5f57b250f56755c1fd

## Steps to reproduce the issue

I started a colony, assigned a builder, built the Builders Hut and then built the Tavern. Started getting the log spam soon as the Visitors started spawning.

### Logs

https://gist.github.com/Sandriell/a261263f462d2f5f57b250f56755c1fd

### Notes

This was previously reported for 1.15.2, however it doesn't seem the fix ever made it into the 1.16.4 version of the mod, or it was assumed the issue was unique to 1.15.2.
https://github.com/ldtteam/minecolonies/issues/5927
https://github.com/ldtteam/minecolonies/issues/5898

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by someaddons** [comment]
ye not an actual bug, one probe just makes a client entity at 0 0 for rendering purposes

**Comment by Sandriell** [comment]
So why is this only an issue with Minecolonies visitors then and not with any other mobs?

**Comment by Raycoms** [comment]
Because our entities have very strict requirements to where they are supposed to be (close to a colony, related to a colony). While other mobs are just free to spawn anywhere.

**Comment by Sandriell** [comment]
Ok I get that, but it doesn't occur with colonist or barbarians, so there is something unique to visitors that is causing it to happen to them. And the massive amounts of log spam it generates makes troubleshooting other issues very difficult.
