### ISSUE TITLE
[Release]AI issue, report to mod author. [1.15.2]

### ISSUE THREAD

**Issue by RVOtakuMike** [ldtteam/minecolonies#6153]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: minecolonies-0.13.436-RELEASE-universal
- Structurize Version: structurize-0.13.94-ALPHA-universal

## Problem description

An AI bug popped up for one of my users. I sent screenshot as well as server log, which i did check, and it does seem to have the error in it.
### Notes or related things

I saw a simular issue, but that was with an alpha build on a different minecraft version, if that is still considered a duplicate, I apologize.
---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by RVOtakuMike** [comment]
I am an idiot and forgot to attach the files. Here they are.

I keep getting the "something really went wrong" error. 
I would mirror it on my site, but I think youd prefer google? [Here.](https://drive.google.com/file/d/1RwlXKccCSKd975fbL2jvnJxOZx5nfaXE/view?usp=sharing)

**Comment by Raycoms** [comment]
I need the latest.log

**Comment by Raycoms** [comment]
Best in a gist or pastebin

**Comment by RVOtakuMike** [comment]
latest.log:
https://gist.github.com/RVOtakuMike/2ebba9a10837c15f3e8af77dd8dc4713

**Comment by Raycoms** [comment]
same as https://github.com/ldtteam/minecolonies/issues/5672
