### ISSUE TITLE
Citizen is hungry, with full health bar

### ISSUE THREAD

**Issue by Nikademus** [ldtteam/minecolonies#6155]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: minecolonies-0.13.473-ALPHA-universal
- Structurize Version: structurize-0.13.100-RELEASE-universal
- Related Mods and their Versions:

## Expected behavior

Worker will not be hungry when full

## Actual behavior

Worker is still hungry after eating.

![2020-11-25_12 56 58](https://user-images.githubusercontent.com/1380028/100265418-36368880-2f1e-11eb-9ec1-b6b0d1df3242.png)

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
He isn't full, he's still missing half a shank

**Comment by Raycoms** [comment]
Doesn't necessarily mean they are hungry, this means they are still in the eating stage (so they probably've just eaten)

**Comment by Nikademus** [comment]
He's been standing around for over a day, but ok.  I fully filled his bar, and he started working again.
