### ISSUE TITLE
Courier Error - Tells me to view latest.log

### ISSUE THREAD

**Issue by seanimusprime** [ldtteam/minecolonies#6157]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.** 

There are related issues but they have been marked closed and resolved.

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: minecolonies-0.13.472-ALPHA-universal
- Structurize Version: structurize-0.13.100-RELEASE-universal
- Related Mods and their Versions: All the Mods 6 mod pack

## Expected behavior
Courier gives me some normal text.

## Actual behavior
Courier tells me he ran into an issue and to check latest.log

![image](https://user-images.githubusercontent.com/19805394/100278252-8fa8b280-2f32-11eb-8728-f97977bf55b9.png)

## Steps to reproduce the issue

1. Builder was working on a project.
2. Talk to courier.
3. Shows error message.

### Logs

- latest.log: https://gist.github.com/seanimusprime/7ad24ee114f26a7ff97f6ab3575a67b7

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
thanks for the report - closed because duplicate
