### ISSUE TITLE
I am having a very hard time placing a SupplyShip in my minecraft modded world and it keeps saying the same 5 blocks need to be in the water but my whole boat is in the water yet it still wont let me place it. Someone please tell me what im doing wrong or is it the mod pack im playing on.

### ISSUE THREAD

**Issue by Pleasehelp2040** [ldtteam/minecolonies#6159]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- MineColonies Version:
- Structurize Version:
- Related Mods and their Versions:

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
update version
