### ISSUE TITLE
Delivery man acts weirdly (#bug)

### ISSUE THREAD

**Issue by Thanaen** [ldtteam/minecolonies#616]
### Minecolonies version 0.6.5

version X.X.XXXX or curse 7.1.6251.1229 Beta

### Expected behavior

- The D-M should empty my worker's chest, and give them items they need.

### Actual behaviour

- He doesn't empty worker's chests, and keeps his inventory full of items that could be stored

### Steps to reproduce the problem

1. Hire a D-M
2. Ask for help in the Discord
3. Cry in darkness
4. Profit

###Extra knowledge
- Upgrade the D-M's hut
- Get a warehouse
- Upgrade the warehouse
- Fire / Hire the D-M
- Teleport the D-M to his hut

**Comment by Thanaen** [comment]
###UPDATE
###Game version: 0.6.6

The D-M is walking again, he goes through every worker's chest, but he doesn't takes any item anymore

**Comment by Raycoms** [comment]
Are you sure?
The items might be marked as keep

Am Samstag, 18. Februar 2017 schrieb Thanaen :

**Comment by Thanaen** [comment]
I'm sure he takes nothing, all my workers are now complaining that their chest is full, and i've been checking the D-M's inventory for all a day, and it's always empty :(

**Comment by Raycoms** [comment]
That's very strange,  I will take a look at it once back from the trip.
Can you try to unlock their chests?
Do you use the locks plug in?

Am Sonntag, 19. Februar 2017 schrieb Thanaen :

**Comment by Thanaen** [comment]
I haven't used to locks plug in!
There is a thing that works: I can open D-M inventory, and give manually the items I want him to store. This is the only thing working right now!

**Comment by marchermans** [comment]
As per request I started merging Issues that are related to things I found while going through the source code. One of these is the request system. Closing this in favor of #638
