### ISSUE TITLE
Server crash after loading spawn during "Listners"

### ISSUE THREAD

**Issue by judicius** [ldtteam/minecolonies#6162]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: 0.13.475 Alpha
- Structurize Version: 0.13.100 Stable
- Related Mods and their Versions:

## Expected behavior

Server would load and world gen
## Actual behavior

Server loads to preparing Spawn  100% - Crashes during Listeners. Excerpt of console below.

`27.11 23:04:45 [Server] Worker-Main-10/INFO Preparing spawn area: 99%
27.11 23:04:45 [Server] Server thread/INFO Time elapsed: 25706 ms
27.11 23:04:45 [Server] Startup Done (36.066s)! For help, type "help"
27.11 23:04:45 [Server] Server thread/INFO [bl.du.du.DustrialDecorMod/]: HELLO from server starting
27.11 23:04:45 [Server] Server thread/INFO [FTB Chunks/]: Server 9098e35f-a2ac-4c00-bbd0-af6eafedc020: Loaded 0 chunks (0 force loaded) from 0 players in 1.920083ms
27.11 23:04:45 [Server] Server thread/INFO [bl.je.je.JellyfishingMod/]: HELLO from server starting
27.11 23:04:46 [Server] Server thread/INFO [structurize/]: Trying jar discover: assets/structurize
27.11 23:04:46 [Server] Server thread/INFO [structurize/]: Trying jar discover: assets/minecolonies
27.11 23:04:47 [Server] Server thread/INFO [structurize/]: Load additional huts or decorations from ./structurize/schematics
27.11 23:04:47 [Server] Server thread/INFO [structurize/]: Load cached schematic from ./structurize/cache
27.11 23:04:47 [Server] Server thread/INFO [structurize/]: Load cached schematic from ./structurize/cache
27.11 23:04:47 [Server] Server thread/INFO [Silent Gear/TraitManager]: Traits loaded: 71
27.11 23:04:47 [Server] Server thread/INFO [Silent Gear/PartManager]: Parts loaded: 32
27.11 23:04:47 [Server] Server thread/INFO [Silent Gear/PartManager]: - Compound: 29
27.11 23:04:47 [Server] Server thread/INFO [Silent Gear/PartManager]: - Simple/Legacy: 3
27.11 23:04:47 [Server] Server thread/INFO [Silent Gear/MaterialManager]: Materials loaded: 148
27.11 23:04:47 [Server] Server thread/INFO [Silent Gear/MaterialManager]: - Standard: 148
27.11 23:04:47 [Server] Server thread/ERROR [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: null
27.11 23:04:47 [Server] INFO Index: 8
27.11 23:04:47 [Server] INFO Listeners:
27.11 23:04:47 [Server] INFO 0: NORMAL
27.11 23:04:47 [Server] INFO 1: ASM: class snownee.snow.GameEvents onWorldTick(Lnet/minecraftforge/event/TickEvent$WorldTickEvent;)V
27.11 23:04:47 [Server] INFO 2: ASM: class com.endertech.minecraft.forge.world.GameWorld$WorldData onWorldTick(Lnet/minecraftforge/event/TickEvent$WorldTickEvent;)V
27.11 23:04:47 [Server] INFO 3: ASM: class com.mrcrayfish.goblintraders.world.spawner.GoblinTraderSpawner onWorldTick(Lnet/minecraftforge/event/TickEvent$WorldTickEvent;)V
27.11 23:04:47 [Server] INFO 4: ASM: class com.endertech.minecraft.mods.adchimneys.world.Events onWorldTick(Lnet/minecraftforge/event/TickEvent$WorldTickEvent;)V
27.11 23:04:47 [Server] INFO 5: ASM: me.paulf.fairylights.server.ServerEventHandler@1639ffbc onWorldTick(Lnet/minecraftforge/event/TickEvent$WorldTickEvent;)V
27.11 23:04:47 [Server] INFO 6: net.minecraftforge.eventbus.EventBus$$Lambda$2680/1623014027@b212e1
27.11 23:04:47 [Server] INFO 7: ASM: class com.ldtteam.structurize.event.EventSubscriber onWorldTick(Lnet/minecraftforge/event/TickEvent$WorldTickEvent;)V
27.11 23:04:47 [Server] INFO 8: ASM: class com.minecolonies.coremod.event.FMLEventHandler onWorldTick(Lnet/minecraftforge/event/TickEvent$WorldTickEvent;)V
27.11 23:04:47 [Server] INFO 9: ASM: class net.silentchaos512.lib.util.EntityHelper onWorldTick(Lnet/minecraftforge/event/TickEvent$WorldTickEvent;)V
27.11 23:04:47 [Server] INFO 10: ASM: class net.silentchaos512.gems.chaos.ChaosHandler onWorldTick(Lnet/minecraftforge/event/TickEvent$WorldTickEvent;)V
27.11 23:04:47 [Server] INFO 11: ASM: class vazkii.quark.oddities.magnetsystem.MagnetSystem tick(Lnet/minecraftforge/event/TickEvent$WorldTickEvent;)V
27.11 23:04:47 [Server] INFO 12: ASM: vazkii.quark.automation.module.FeedingTroughModule@2ac78a7b buildTroughSet(Lnet/minecraftforge/event/TickEvent$WorldTickEvent;)V
27.11 23:04:47 [Server] INFO 13: ASM: vazkii.quark.automation.module.PistonsMoveTileEntitiesModule@6325d915 onWorldTick(Lnet/minecraftforge/event/TickEvent$WorldTickEvent;)V
27.11 23:04:47 [Server] INFO 14: ASM: vazkii.quark.tweaks.module.ImprovedSleepingModule@6fd9bff8 onWorldTick(Lnet/minecraftforge/event/TickEvent$WorldTickEvent;)V
27.11 23:04:47 [Server] INFO 15: ASM: com.natamus.giantspawn.events.GiantEvent@2e6862d5 onWorldTick(Lnet/minecraftforge/event/TickEvent$WorldTickEvent;)V
27.11 23:04:47 [Server] INFO 16: ASM: com.natamus.skeletonhorsespawn.events.SkeletonHorseEvent@25c9b308 onWorldTick(Lnet/minecraftforge/event/TickEvent$WorldTickEvent;)V
27.11 23:04:47 [Server] INFO 17: ASM: com.natamus.zombiehorsespawn.events.ZombieHorseEvent@5c99a86c onWorldTick(Lnet/minecraftforge/event/TickEvent$WorldTickEvent;)V
27.11 23:04:51 [Multicraft] Server shut down (running)
27.11 23:04:51 [Multicraft] Restarting crashed server in 300 seconds`

## Steps to reproduce the issue

Attempting installation of Builders Delight 2 Beta v1.1 for 1.16.4 located on Curseforge
server fails initial world creation while minecolonies is enabled. 
Disabling the minecolonies jar file allows server to start.

### Logs

- latest.log: 
- crashlog: 

https://gist.github.com/judicius/ec67f190a5148efea51461a1270da5e0

### Notes

Working latest.log with no minecolonies.jar enabled for comparison.

https://gist.github.com/judicius/f6e00a373214424a23d69b285db51a06
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by marchermans** [comment]
@judicius How do you conclude this is a minecolonies issue?

**Comment by judicius** [comment]
by the fact that disabling the mod on the server fixes the issue.

**Comment by Raycoms** [comment]
There is a mod, that adds a broken item, this broken item causes this crash. 

```
final NonNullList<ItemStack> list = NonNullList.create();
                                                 item.fillItemGroup(ItemGroup.SEARCH, list);
                                                 return list.stream();
```

We execute this per item, every item should be able to execute this code without a problem.
(It works in huge modpacks too).

Please try to find out which mod is causing this, and report it to them.

**Comment by judicius** [comment]
ok...now i just have to figure out how to determine what mod does that.  Can you tell me where you found that information. I mean I'll do the legwork to load the mods to look for it if i know where to look.

**Comment by Raycoms** [comment]
Sorry for the delay, the log tells us that while it crashes at the code I've linked above, this is because the other mod does something invalid in this call which causes the crash.

**Comment by judicius** [comment]
Going to close this, identified and fixed by Advanced Chimneys

https://www.curseforge.com/minecraft/mc-mods/advanced-chimneys/issues/44
