### ISSUE TITLE
Following guards not eating/ignoring hunger

### ISSUE THREAD

**Issue by TraipsingShadow** [ldtteam/minecolonies#6163]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: minecolonies-0.13.474-ALPHA-universal.jar
- Structurize Version: structurize-0.13.94-ALPHA-universal.jar
- Related Mods and their Versions:

## Expected behavior

Following guards would eat the food inside their inventory to fill their hunger regardless if following, in patrol, or guarding.

## Actual behavior

Following guards (specifically) would both ignore the food in their inventory and their hunger bar and let their hunger drain until manually resetting the guard to either guard/patrol and waiting for them to eat.

## Steps to reproduce the issue

1. Let any guard of any level from any guard tower to follow you (either tight/loose, does not matter) and place any kind of food in their inventory
2. Make the guard fight/walk around until hunger naturally depletes from exhaustion
3. Even if their hunger hits rock-bottom (negative Hunger particle effects plus slowness is applied), they will ignore whatever stacks of food you placed inside their inventory

##Notes

It is rather cumbersome to run all the way back to wherever the guard tower is just to manually reset the guard just to make them eat. Does making them follow ignore their hunger altogether? If so, why do they still get hungry?

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Atm this is intended behavior due to certain limitations there are. We will in the future improve this behaviour in certain ways.
