### ISSUE TITLE
Following guard forgetting follow state when leaving game/when dying

### ISSUE THREAD

**Issue by TraipsingShadow** [ldtteam/minecolonies#6164]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: minecolonies-0.13.474-ALPHA-universal.jar
- Structurize Version: structurize-0.13.94-ALPHA-universal.jar
- Related Mods and their Versions:

## Expected behavior

When leaving/re-joining a game: Following guards would retain their "follow" behavior to the player after leaving and re-joining the game (both Multiplayer and Singleplayer).
When dying: Following guards would both teleport and retain their "follow" behavior after death.

## Actual behavior

When leaving/re-joining a game: Following guards completely forget they were following a player once the player either exits the singleplayer world and/or a multiplayer server.
When dying: Following guards correctly teleport to the player's spawnpoint but would no longer follow the player.

## Steps to reproduce the issue

1. Pick any guard of any level from any guard tower to follow you (either singleplayer or multiplayer; either tight or loose)

a. For leaving/re-joining a singleplayer and multiplayer game:
2a. Exit the game (if singleplayer) or disconnect from the server (if multiplayer)
3a. Re-join the game and observe the guard that once followed you has completely forgotten that they were following someone

b. For dying:
2b. Die.
3b. Respawn and observe as the guard does teleport to your location/spawnpoint but just stays in that area, completely forgetting their follow target (and why they got teleported in that area in the first place)

### Notes

A simple solution would be, "Just run back to the Guard Tower and reset it manually!". But I really do think this wasn't the intended behavior and is therefore a bug.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
That is intended behaviour not a bug.
