### ISSUE TITLE
[Compatibility] Extend the ItemStorage system to enable use of OreDictionary and NBT Specific storage.

### ISSUE THREAD

**Issue by marchermans** [ldtteam/minecolonies#617]
_Current Situation:_
I am guessing to circumvent the fact that two ItemStacks instances are not comparable by the standard means Minecolonies uses a class called `ItemStorage` to track which kind of stacks to keep and which to drop.
This system works for things that only depend on Items and Metadata. However there are a lot of mods out there that either partly or completely disregard Metadata and use NBT for their data. These kind of items should be taken into account.

_Desired Solution (Route 1):_
- Extend the current system to take NBT Dependent variants into account
- Extend the current system to take OreDic Dependent variants into account.

_Desired Solution (Route 2):_
- Change the current system to use TCustomMaps and TCustomLists from guava (standard in MC)

_Desired Target_:
- A system where not only the AI can set the ItemStacks to keep, but also the User.

**Comment by Raycoms** [comment]
Should be done afaik
