### ISSUE TITLE
[1.16.4] Stash blocks do not drop items when broke or retain their items when replaced.

### ISSUE THREAD

**Issue by Sandriell** [ldtteam/minecolonies#6176]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: minecolonies-0.13.486-ALPHA-universal
- Structurize Version: structurize-0.13.100-RELEASE-universal
- Related Mods and their Versions: All the Mods 6 1.3.1

## Expected behavior
Break a Stash block/container and it would drop the items contained within,

## Actual behavior

Break the Stash block and any items inside do not drop and are not inside it when replaced.

## Steps to reproduce the issue

Place a stash block and break it.

1. 
2. 
3. 

### Logs

N/A

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by someaddons** [comment]
works for me, contained items are dropped just fine
