### ISSUE TITLE
in-game config

### ISSUE THREAD

**Issue by CoconutCurry** [ldtteam/minecolonies#618]
It'd be awesome to be able to change some things in the config for the mod from in-game. Things like if builders have infinite resources or not, or adjusting the build/dig speed for citizens.

**Comment by Raycoms** [comment]
We have exactly that in the config

Am Freitag, 17. Februar 2017 schrieb CoconutCurry :

**Comment by marvin-bitterlich** [comment]
@Raycoms ingame

**Comment by Raycoms** [comment]
Ah okay.
I don't think we should do it.
People will use it to cheat.
Everything in game is meant to be adapted

Am Freitag, 17. Februar 2017 schrieb Marvin Hofmann :

**Comment by CoconutCurry** [comment]
How could someone use that to cheat? 

Ideally, it'd only be able to be changed to infinite resources in a creative map.

**Comment by Raycoms** [comment]
All that settings should imo.


Am Freitag, 17. Februar 2017 schrieb CoconutCurry :
