### ISSUE TITLE
Guards not being responsive

### ISSUE THREAD

**Issue by JDoeBoy** [ldtteam/minecolonies#6180]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.3
- MineColonies Version: minecolonies-0.13.486-ALPHA-universal.jar
- Structurize Version: structurize-0.13.100-RELEASE-universal.jar

## Problem description

None of my guards are responding, I have tried firing and rehiring them, punching them, and downgrading the minecolonies version.
### Notes or related things

While Twitch was being changed over, I had my client running, and the Twitch app disabled some of the mods while I was playing.  After reenabling the few mods, and restarting my client, my guards had stopped responding.  I think there is a possibility that something in my save got corrupted, but as far as I am into Minecolonies, I would like to know if there are any solutions.
---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
if the blocks are still placed you can run the loadbackup command. For support please discord. This is for general bugs.

**Comment by ravenbuilder934** [comment]
They already posted on the discord and couldn't find an answer

**Comment by JDoeBoy** [comment]
I have restored from a backup, and I am still not getting any response from my guards/archers.  I have even tried trimming the world down to the chunks that only contain the colony, and surrounding chunks.  All the other citizens are working happily.

**Comment by Raycoms** [comment]
tried firing/rehiring?

**Comment by JDoeBoy** [comment]
Tried firing/rehiring, recalling them to their huts, and recalling them to town hall.  Backup didn't seem to change anything, and guards no longer get knocked back when hit, they just make a woosh sound when hit.

**Comment by Raycoms** [comment]
that sounds weird, anything in the logs?

**Comment by Raycoms** [comment]
Did those guards wear any special armour or swords of mods that are gone?

**Comment by JDoeBoy** [comment]
Just the following that gives any flags 
`WorkOrderBuild at location BlockPos{x=-29, y=76, z=-333} is using schematics/fortress/guardtower5 instead of schematics/fortress/guardtower5
[12:32:07] [Server thread/INFO]: WorkOrderBuild at location BlockPos{x=-29, y=76, z=-333} is using schematics/fortress/guardtower5 instead of schematics/fortress/guardtower5`

**Comment by Raycoms** [comment]
nah, that's not related

**Comment by JDoeBoy** [comment]
It shows me calling my guards, and that they are answering, but they didn't

**Comment by JDoeBoy** [comment]
Any way to keep my build, and export it to a new world, or is a restart going to be needed, I think this is a corruption issue.

**Comment by Raycoms** [comment]
When you hire the same citizens for other jobs, do they work?

**Comment by JDoeBoy** [comment]
I will test that

**Comment by JDoeBoy** [comment]
Set a knight as the baker, and they changed clothes, and walked to town hall because they had no bed.  So I set them as an archer, in a different tower, and they asked for a bow, them became unresponsive after getting their tools.  They moved, but didn't answer the banner, or respond to a hit.

**Comment by Raycoms** [comment]
are they maybe hungry?

**Comment by JDoeBoy** [comment]
Not hungry, they all have food, and all the medical needs in their inventory.  Nothing showing in their GUI

**Comment by Raycoms** [comment]
the Icon is showing "working" ?

**Comment by JDoeBoy** [comment]
Correct, it shows working.

**Comment by Raycoms** [comment]
if you hire a diff citizen to be a guard it also gets stuck?

**Comment by JDoeBoy** [comment]
That one hit me back.  I made my builder an archer, and he worked.

**Comment by Raycoms** [comment]
That is really strange. Then I guess you could just "kill" off those broken ones and get new ones. That might be an easy way to fix the weird behaviour.

**Comment by JDoeBoy** [comment]
I will do that, thank you for the help.
