### ISSUE TITLE
[1.16.4] Deliveryman AI issues with Stash block

### ISSUE THREAD

**Issue by Sandriell** [ldtteam/minecolonies#6183]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: minecolonies-0.13.486-ALPHA-universal
- Structurize Version: structurize-0.13.100-RELEASE-universal
- Related Mods and their Versions: All the Mods 6 1.3.1

## Expected behavior
When my delivery people attempt to pick up from the stash block I am regularly having issues with the AI crashing. I have done resets to the request system as well as breaking, recrafting, and replacing the Stash block and the same thing will still regularly happen.

## Steps to reproduce the issue

 Unsure how to reproduce. Sometimes they pick up ok, but the majority of times they don't.

### Logs

https://gist.github.com/Sandriell/eac4dbde57fc119e3c3d782d8e2ad5b0

### Notes
I have been having additional issues with the stash block as well: https://github.com/ldtteam/minecolonies/issues/6176

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Duplicate issue, this is related to the other AI issue as well.
