### ISSUE TITLE
Citizen count issue

### ISSUE THREAD

**Issue by Rithenar** [ldtteam/minecolonies#6186]
### Prerequisites 

- [ x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: minecolonies-0.13.486-ALPHA-universal.jar
- Structurize Version: structurize-0.13.100-RELEASE-universal.jar
- Related Mods and their Versions: ATM 6 1.3.3

## Actual behavior
 I started noticing this bug yesterday when I built a tier 2 house and it was immediately filled by a child. The Town Hall list showed the child as unemployed but I couldn't hire him of course. After the child grew up that went away so I didn't think much more of it.

Today, however, my miner was killed by a mob. I had turned off "kids will be born" so I can hire visitors with better stats. When the miner died, however, the spot he otherwise would have left is now filled by a "ghost". I can't hire a visitor to replace him because this "ghost" is using up his space. If I turn the child feature on, no child will spawn. The video shows that in a short time span, however, I have left the option ON for over 1/2 hour with the same results.   The Town Hall does not list a Miner as 0/1 but instead, it shows an unemployed citizen. When I try to hire it I have no citizens available.

https://youtu.be/tjUeEGxxHcY

## Steps to reproduce the issue

 Don't have steps as it is constant

1. 
2. 
3. 

### Logs

- latest.log:  https://gist.github.com/Rithenar/3aaef966c8a57ad019c60d37a6516764
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Aduis1210** [comment]
Noticed as well on Server - The figures are completely wrong

**Comment by Raycoms** [comment]
Did you maybe hire a worker at the tavern that was supposed to be for the spot in a guard tower, in another job?

**Comment by Rithenar** [comment]
no, I wasn't able to hire a worker at the tavern because it kept saying there is no room

**Comment by Raycoms** [comment]
I mean, before the death

**Comment by Rithenar** [comment]
Before the death, I had hired a couple of citizens for the tavern and they went to other jobs and I reassigned them. I believe one of them was a guard, yes.

**Comment by Raycoms** [comment]
Do you have an open space at a guard tower somewhere?

**Comment by Rithenar** [comment]
not at the moment. I have 5 guardhouses filled out. the guards are bugged in their own regard though, but that is a different subject.

**Comment by Rithenar** [comment]
Just wanted to update you that I upgraded my Town Hall to see if that helped. After upgrading a couple of houses I now have a total of 22 available beds (including the tavern), and 5 guard towers. This gives a total of 25 citizens and 2 open spaces. The Town Hall is counting the 25 but not the open spaces.  I cannot hire any visitors from the tavern

![image](https://user-images.githubusercontent.com/9939332/101223877-aea1f580-3652-11eb-9d06-696a3682d2e5.png)

![image](https://user-images.githubusercontent.com/9939332/101223901-c24d5c00-3652-11eb-8aa2-325dc900d52d.png)

![image](https://user-images.githubusercontent.com/9939332/101223920-cbd6c400-3652-11eb-8d21-6e77429fd585.png)

![image](https://user-images.githubusercontent.com/9939332/101225048-1148c080-3656-11eb-9c8d-d973b9e78d05.png)

**Comment by someaddons** [comment]
to go beyond 25 you need to do a research

**Comment by Rithenar** [comment]
oops thanks someaddons.  Raycoms ignore the "additional information" then XD

**Comment by camrex** [comment]
I am running into a similar if not the same issue. According to the townhall I have 16 of 16 citizens (2 unemployed). But my citizen list only shows 14 (all employed); the 2 unemployed are missing from the citizen list and I have been unable to find them in the world (jungle makes it hard). I built a hospital which should employ one of the unemployed, but the townhall doesn't show the hospital, but shows a ": 0/1" where the hospital should be (all other buildings fully employed.) And the hospital doesn't shoe anyone available to employ. I am running 0.13.490-ALPHA.

**Comment by camrex** [comment]
Just to add, I just upgraded a house, and a child was born, my citizen count stayed at 16/16, my unemployed went to 1 and children went to 1. I am still unable to employ anyone at the hospital.

**Comment by Nilok7** [comment]
I'm having this exact same issue, after my citizen dying they are still taking up space under "Number of Citizens".

What makes it even weirder is that my citizens are at 10/9 and 6 unemployed citizens, but I only have 4 citizens left in my colony.

I'm on a server running 1.16.4, MineColonies 0.13.480 Beta Universal

![unknown](https://user-images.githubusercontent.com/8335377/107114515-3820a000-681b-11eb-9f21-aad5ae21ee39.png)
![totalcitizens](https://user-images.githubusercontent.com/8335377/107114530-4f5f8d80-681b-11eb-9980-4f7f15640ada.PNG)

**Comment by Talyda** [comment]
You're gonna want to update, cos you are over 100 versions behind. If you still have a problem then, start a new issue

**Comment by Nilok7** [comment]
> You're gonna want to update, cos you are over 100 versions behind. If you still have a problem then, start a new issue

I'm sorry to ask, but where do I find the update? The latest version I see on CurseForge is the 0.13.480-BETA-universal.jar, the same one my server host is running.

Does my server host need to compile the Github version?

**Comment by Raycoms** [comment]
click "view all" on curseforge, new betas and release are coming out soon
