### ISSUE TITLE
Sever server Lag on more than 1 player online

### ISSUE THREAD

**Issue by DaddyP1G** [ldtteam/minecolonies#6187]
### Prerequisites 

- [X ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: 1.13.486
- Structurize Version: 0.13.100
- Related Mods and their Versions:
 -BYG 1.1.5
-citadel 1.5.2
-Classes 1.2.2
-Forge 35.1.0 AND 35.1.7
-IceandFire 2.1.3
-project MMO 3.34.3

## Problem description
Server runs no problem with 1 person.   As soon as a 2nd person logs in the Server ticking can't keep up and drops to 12-13 TPS.  I had 86 mods and removed them down to Minecolonies and the ones above causing the issue when in more than one colony was actively being used.     Checked with host, both RAM and Processor never get over 50% load.  https://status.starlancer.com/report/uptime/3f22ba4f6c39177ed23c0e7a9d4debde/   6 gig server.  

Lastest:
https://gist.github.com/DaddyP1G/25746f3c7080974fbb6c548883b4d0b1

### Notes or related things
Was running 1.16.3 on the same server with Minecolonies .437 and structurize .96 with no issues and 6 people on the server.  
---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Can you run a profiler?

**Comment by DaddyP1G** [comment]
Do you have a profiler you prefer  ?

**Comment by Raycoms** [comment]
spark is fine

**Comment by DaddyP1G** [comment]
I don't see Spark for 1.16.4 Forge.

**Comment by DaddyP1G** [comment]
NM.. found it on the Github.  I'll run it now and when someone logs on.
Standby.

**Comment by DaddyP1G** [comment]
https://spark.lucko.me/#snq2MSJvdE

I hope I did that right

**Comment by someaddons** [comment]
no you only ran it on the client, not on the server

**Comment by someaddons** [comment]
do /spark sampler,   not /sparkc sampler

**Comment by DaddyP1G** [comment]
OK, so if i did this right, maybe it's not Minecolonies.

https://spark.lucko.me/#nuEAalayEx

**Comment by someaddons** [comment]
thats right indeed and its an ice an fire dragon using up 96% of the server tick, we got a winner! xD

**Comment by DaddyP1G** [comment]
Glad to hear it! Thank.  Sorry for the false alarm
