### ISSUE TITLE
Allow seeing building size again

### ISSUE THREAD

**Issue by CoconutCurry** [ldtteam/minecolonies#619]
Is there any way to have the builder's rod be able to show a preview of a building for a block that's already placed (by say having that block in the reticule when using the rod) to preview upgrades to the building?

I'd love to be able to double check the size of level 5 buildings and such. Currently the townhall does not give construction tape for the size of the final upgrade... so even just fixing that would be awesome.

**Comment by marvin-bitterlich** [comment]
Construction tape is for all upgrades. If it doesn't happen, please file an issue for it

**Comment by Raycoms** [comment]
We should make that if you right click a building with the build tool it
displays as well but is unable to move or rotate

Am Freitag, 17. Februar 2017 schrieb CoconutCurry :

**Comment by Raycoms** [comment]
We have a quite similar issue which wants you to be able to rotate and move keeping the level of the hut.
So I merge them
