### ISSUE TITLE
Workers does not sleep anymore / Life in the village 2

### ISSUE THREAD

**Issue by Arilesdra** [ldtteam/minecolonies#6191]
Hi,

sorry my english issnt very well. 

I play /gamemode creative & without Monsters
I use /gamerule doDaylightCycle false, /gamerule doFireTick fakse & /gamerule doWeatherCycle false
If i change into /time set nigth the Workers don´t sleep anynmore. Bevor the Town Hall was upgrade to 5, my workers sleep everytime normal if i chance frome day to nigth. After than not more. But i didnt know if this is causal or have any ather reason.

Forge 31.2.45
Minecraft 1.15.2
MCP 20200515.085601

1 Town Hall - 5
1 Restaurant - 5
1 Tavern - 5
4 Bulider´s - 5
1 Builder - 2
1 School - 5
1 Universität - 2 (but all research various!!)
1 Cowherd´s Hut - 5
1 Farm - 5 & 3 Field 
1 Hospital - 5
4 House´s - 5
1 Fisher´s Hut -5
1 Chicken Framer´s Hut - 5
1 Warehouse - 5
1 Courier’s Hut - 5
1 Courier’s Hut - 2
3 Guard Tower -5
1 Guard Tower - 3

Thanks for help and any ideas. 

Greetings

**Comment by Raycoms** [comment]
/gamerule doDaylightCycle false,

this MUST be true.

**Comment by Arilesdra** [comment]
no, becouse its work bevor WiTH True ?!

The Workers sleep bevor with the same Cheat. This can´t be the solutin?

**Comment by ravenbuilder934** [comment]
Then you need to update your minecolonies version, there was a bugged version.

**Comment by Arilesdra** [comment]
nope, sorry i try it, but this issnt the solution... :( 

these do not sleep no matter true or false :(

**Comment by ravenbuilder934** [comment]
You tried updating?

**Comment by Raycoms** [comment]
We adjusted the calculation and our citizens require world time to change. So we need the cycles.

**Comment by Arilesdra** [comment]
with one? i think i have the lastet version?

**Comment by Arilesdra** [comment]
GDLauncher v 1.0.11- i have this Launcher

**Comment by ravenbuilder934** [comment]
That's your launcher version, not your minecolonies version. You need to update your minecolonies version

**Comment by Arilesdra** [comment]
But if i do this, i cant play my last Server with my friend :( annymore. We have a Server with a big Map an i dont like to give it up.

I dont understand wath this new Version have to do with the old Version? 

Yesterday my Workers sleep normal with CyclesCheat false. The run to bed anytime if i change into nigth.

How can influence the new Version the old one, if i dont install the new one?

**Comment by ravenbuilder934** [comment]
You can play on the server if the server and your friend also update.

Download the new version, delete the old version, and put the new version where the old one was. Do this on the server, your computer, and your friend's computer.

**Comment by Arilesdra** [comment]
Ok, thanks for try to help me. But i dont like a new Version i like to fix the old - respectively i need to understand way it works bevore and now no more. Sorry, i think maybe my english is not enough to make you understand wath i need.

I think you're right if you suggests its easier to update, but ... how shall I.... öhm... hm... i am to stubborn to go the easy way ;)...

Because i do not want do have a TimeCycle in my Game. I will be the "Master" that determines t is time to sleep ;)...

LOL sorry XD XD ;) Thank you so much...

**Comment by Arilesdra** [comment]
hm. i do not know wath i have done. but i works... and i now use /time set 12000 not /time set nigth... if i use /time set nigth the time will setting on 13000 ... perhabs.. and my timecycles is still "false"... killing me, but i have no no explanation... strange - somtimes its strange

**Comment by ravenbuilder934** [comment]
The timecycles need to be on true

**Comment by Arilesdra** [comment]
You need /time set 14500

sorry, i have prescribed unhappy

i use  /time set 14500 and /gamerule doDaylightCycle **false**

so its trigger at 8:30 PM (Playtime) the Worker to get sleep... 

first i try 12000 than 12500 than 12800 than and so on and so on...
but i do not watch out which time is the triggertime last

ok solution is: 
_Use /gamerule doDaylightCycle **false**
BUT the Sleeptriggertime /time set 14500_

i try this now 5 x and it works every time

(/time set nigth is just 13000)

**Comment by ravenbuilder934** [comment]
The best solution is /gamerule doDaylightCycle true

**Comment by Arilesdra** [comment]
? Why should this be the best for me, if my solution works for me - so i if i like it? ;)

Its my Problem and so my solution?!?! Individually problem = individually solution? But thank you for give me the correct input. You help me realy much, even if I do it differently ;)... So have a good time. And thanks... :)

**Comment by ravenbuilder934** [comment]
I guess you can use your solution, but setting the daylight cycle to true removes the need to keep doing /time set 14500

**Comment by Arilesdra** [comment]
but I don't want the day to run by itself ;)
