### ISSUE TITLE
AI Issues

### ISSUE THREAD

**Issue by Altamarie** [ldtteam/minecolonies#6193]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.484-ALPHA-universal
- Structurize Version: 0.13.94-ALPHA-universal

## Problem description
I have had two villager stop working and then appear with the red gear and exclamation point above there head which then states "My AI has run into an issue, please locate the latest.log file and send it to the Minecolonies authors with this message. 

### Notes or related things
I have attached both screenshots and the logs in [questions](url
[message.txt](https://github.com/ldtteam/minecolonies/files/5639215/message.txt)
[message (1).txt](https://github.com/ldtteam/minecolonies/files/5639216/message.1.txt)
![Villager 1](https://user-images.githubusercontent.com/75453889/101094805-9662a580-3582-11eb-9489-e1f00abb58d7.PNG)
![Villager 2](https://user-images.githubusercontent.com/75453889/101094812-98c4ff80-3582-11eb-8ee7-59ab72da992d.PNG)

)
---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by someaddons** [comment]
please update to the newest alpha and see if the issue persists/add logs with the new version

**Comment by Altamarie** [comment]
> please update to the newest alpha and see if the issue persists/add logs with the new version

I am running the newest ALPHA for 1.15 which is 0.13.484-ALPHA-universal

**Comment by ravenbuilder934** [comment]
Can you please put the logs in a https://gist.github.com

**Comment by Altamarie** [comment]
Done

**Comment by ravenbuilder934** [comment]
Can you send the link to the gist?

**Comment by Altamarie** [comment]
https://gist.github.com/Altamarie/e9d53384ce46d963bdddec187588192b

**Comment by Raycoms** [comment]
same problem @someaddons

**Comment by someaddons** [comment]
ye should be fix with my PR

**Comment by Altamarie** [comment]
SO we have updated to the newest version and are still having problems

**Comment by ravenbuilder934** [comment]
The newest alpha?

**Comment by Altamarie** [comment]
https://gist.github.com/Altamarie/f024d195591f40edfdac952b7bf38c62

**Comment by Altamarie** [comment]
yes 0.13.512
