### ISSUE TITLE
Warehouse Features

### ISSUE THREAD

**Issue by Raz0rLegend** [ldtteam/minecolonies#6194]
### Prerequisites 

- [ x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.16.1
- MineColonies Version:0.13.145
- Structurize Version:0.13.44

## Problem description

I played 1.15.2 minecolony last week. I had a very useful feature inside the warehouse, i could fold all the items, and i could show the item inside the rack and for now i did not find the "?" to show the item. Is this a removed feature, or i have a bug on the server ? 
Thanks in advance.
### Notes or related things

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
0.13.145 is a very very VERY old version, that's probably why (we're in the 0.13.480s)

**Comment by Raycoms** [comment]
update, yes
