### ISSUE TITLE
Miner AI fails when nodes loop

### ISSUE THREAD

**Issue by sjjgaal** [ldtteam/minecolonies#6199]
### Prerequisites
- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: minecolonies-0.13.438-ALPHA-universal
- Structurize Version: structurize-0.13.94-ALPHA-universal
- Related Mods and their Versions: Life in the Village modpack 1.07

## Expected behavior
Miner keeps mining and does not break when the path of the nodes come into contact

## Actual behavior
It seems that when the nodes get laid out in such a way that it starts to "touch" itself by doing a loop, the AI is not able decide on where to go next. The miner will stop working and visually explains that an error occured in the AI, with the cog above his head. Assigning him to mine in the level above it did seem to work for a while, but eventually that still made his AI fail again.

## Steps to reproduce the issue

1. Have the miner mine out nodes. 
2. As it switches directions it should eventually do a loop somewhere
3. The AI would return errors and the miner will be inactive

### Logs
- latest.log: https://gist.github.com/sjjgaal/23396956240810726411b4ccb0024c6d#file-gistfile1-txt
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Update, if I remember correctly this was already fixed

**Comment by someaddons** [comment]
![image](https://user-images.githubusercontent.com/38401808/101246881-3ef53e80-3716-11eb-978d-6788cf9c1c3c.png)
You are clearly not running the latest version.
