### ISSUE TITLE
No Work Orders Register in TH block after breaking/placing it again.

### ISSUE THREAD

**Issue by Wissi** [ldtteam/minecolonies#620]
Official 1.10.2 Server Issue:

Placing TH block to create Town Protection area and building builder's hut. 
Then breaking the TH block to place elsewhere (or even exact same coords) and new WO's won't register in TH or builder's hut GUI.
Break/place any hut block with and without building tool, no WO's are created in TH block or Builder's GUI anymore.

**Comment by Wissi** [comment]
Update: After the 3rd  Server restart the TH finally registered the work orders again. Not sure why it took so long (and several server restarts) for the TH to be able to recognize and register the Work Orders.

**Comment by Raycoms** [comment]
Strange it seems like the colony doesn't know the townhall has been placed
again

Am Samstag, 18. Februar 2017 schrieb Wissi :

**Comment by marvin-bitterlich** [comment]
closing tor now
