### ISSUE TITLE
CTD when shift-rightclicking on a hut block with a scroll

### ISSUE THREAD

**Issue by ravenbuilder934** [ldtteam/minecolonies#6208]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4 
- MineColonies Version: 496 alpha
- Structurize Version: 100 release
- Related Mods and their Versions: none

## Expected behavior
No crash

## Actual behavior
When I shift+rightclicked on the Town Hall or a Guard Tower (might be others as well, I haven't checked) while holding the guard reinforcement scroll (might be others as well, I haven't checked), I crashed to my desktop.

## Steps to reproduce the issue

1. Hold a guard reinforcement scroll
2. Shift + right-click on the town hall or a guard tower
3. Kaboom!

### Logs

- latest.log: https://gist.github.com/ravenbuilder934/8e3b7041780533c3fa23220b4f0ec16d
- crashlog: https://gist.github.com/ravenbuilder934/8e3b7041780533c3fa23220b4f0ec16d

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Shift+rightclicking on the Town Hall with a colony teleport scroll works

**Comment by ravenbuilder934** [comment]
But actually using the colony teleport scroll crashes

**Comment by Raycoms** [comment]
Was this in multiplayer @ravenbuilder934 ?

**Comment by ravenbuilder934** [comment]
Nope, singleplayer superflat creative world that I use for testing/wiki screenshots
