### ISSUE TITLE
New to Github -0 AI issues?

### ISSUE THREAD

**Issue by FalcorTrueblade** [ldtteam/minecolonies#6209]
I am running a Craft of Exile [Dissonance] server and one of my NPC's requested I provided the lastest.log file to you guys. 
Something about an AI issue. He seems to get caught up whenever he begins building. He is my first builder and this is his own hut. After recalling him or pushing him manually around he starts back up but keeps asking for me to share the log file. So here it is.

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.484-ALPHA-universal
- Structurize Version: ?
- Related Mods and their Versions: ?

### Logs
- latest.log: https://gist.github.com/FalcorTrueblade/f645be6ca54f01d18f97d0d2d655111e

**Comment by Raycoms** [comment]
Fixed in newest 1.16 version

**Comment by ravenbuilder934** [comment]
(Will be ported soon)
