### ISSUE TITLE
Changing Language Crash

### ISSUE THREAD

**Issue by CoconutCurry** [ldtteam/minecolonies#621]
### Minecolonies version

version 0.6.6

### Expected behavior

- Change language to spanish will change all the game text to spanish. 

### Actual behaviour

- CPU goes to 100%, screen freezes. Game crashes or I have to end the process in task manager.

### Steps to reproduce the problem

1. Open Minecolonies Minecraft
2. Go to the Languages option menu.
3. Select Español (México)
4. Crash.

The crashlog seems to suggest it's my texturepack? I'm using Invictus
[CrashLog.txt](https://github.com/Minecolonies/minecolonies/files/782649/CrashLog.txt)

**Comment by marvin-bitterlich** [comment]
This is missing many lines. Is there an actual crash log? in the crash-reports folder or so?

**Comment by CoconutCurry** [comment]
I'd copy/pasted from the crash log that the launcher gave.  There isn't a crash log for that day saved in the crash log folder for some reason.

**Comment by Raycoms** [comment]
Please reopen if able to reproduce and able to show the complete crashlog.
(We only have Espanol - Spain though)
