### ISSUE TITLE
MedievalOak Tavern Level 1 - Pathfinding Issue

### ISSUE THREAD

**Issue by Moleculor** [ldtteam/minecolonies#6214]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: 0.13.496-ALPHA
- Structurize Version: 0.13.100-RELEASE
- Related Mods and their Versions: Don't think other mods are relevant in this specific issue, but I'm running the official showcase pack from y'all?

## Expected behavior
The colonist can make it to bed, even if that requires re-pathfinding or whatever. 

## Actual behavior
A colonist _can_ (though it's random) get 'stuck' at the side of the external stairs in the MedievalOak Level 1 Tavern.

In the MedievalOak style Level 1 Tavern, all beds for colonists are up some external stairs. 

Since all colonists head to bed in a manner that means they all arrive around the same time, you usually end up with all the colonists attempting to climb the same set of stairs. If visiting colonists, Minecraft pathfinding wiggling, or other mobs/entities happen to nudge them off of the stairs, they can end up 'stuck' just standing off the side. In my 'main' world where I've been testing out the pack, the colonist just hops in place over and over. In a test world where I recreated the issue, the colonist in question just appeared to stand motionless. 

The Level 2 version of the building adds railings which seems to mitigate the issue, but I was stuck on Level 1 for quite a while, so it got to be a noticeable issue. 

![2020-12-07_10 28 05](https://user-images.githubusercontent.com/3865976/101378372-a0cdb980-3878-11eb-9a57-2b56618ad623.png)

I placed a single block of red wool to indicate the spot they get stuck at. The above image is from my test world where I recreated the issue.

You can ignore the red gear! icon above his head. He's just complaining about lacking a tool for his job.

![2020-12-07_10 01 40](https://user-images.githubusercontent.com/3865976/101378513-cb1f7700-3878-11eb-934c-13407f89f685.png)

In case it's relevant/helpful, this is the 'main' world where I've since upgraded the Tavern to level 2. The place with the purple block is where the colonist would be 'bouncing' when the Tavern was still Level 1. 

[OakLevel1Pathfind.zip](https://github.com/ldtteam/minecolonies/files/5653963/OakLevel1Pathfind.zip)

And here's a copy of the test world.

I don't know if the building's 'facing' or anything matters, but the screenshots should show that the front of the building faces south when this issue occurs. I do not know if other directions have an impact.

## Steps to reproduce the issue

1. Have a MedievalOak style Tavern at Level 1. Possibly front facing south?
2. Wait _slowly_ for night to descend. Do not advance time artificially, as each colonist seems to decide to head to bed based on a goal of arriving simultaneously.
3. Nudge a colonist off the stairs as they climb them, or wait and hope for them to be nudged off by another colonist.

### Logs

...uuuughhh.

- latest.log: https://gist.github.com/Moleculor/f7bdf55fd71f9964c26837f5245f1b62

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by daddy77gaming** [comment]
there are some other buildings with similar block layouts, ergo a stair on a block the citizens are trying to get up on.
ofc similar style taverns and hospitals as the designs are 'shared' by a couple of wood types.

example birch hospital lvl2

![image](https://user-images.githubusercontent.com/31905330/101914152-31333380-3bc4-11eb-86a9-4be012e3a1a3.png)

**Comment by swiftgeek75** [comment]
This also happens in the "Wooden Tavern" when everyone is leaving in the morning. Multiple citizens leave at the same time and get stuck at the door. Like multiple animals trying to follow bait through a single gate - they keep nudging each other and no one courteously steps aside and lets another go through first.

I tried adding another door, but they still went to the main door.

**Comment by PasixTheValkyrie** [comment]
It's safe to say that the issue @mhswift mentioned happens at nearly every building with a single door that multiple colonists enter at once. Luckily these aren't many, but both the wooden and stone tavern have this issue. It's unresolvable by placing additional doors, as they seem to generally ignore these.

**Comment by ShaneCourtrille** [comment]
Housing in the Fortress style also has this issue.  Two people will keep toggling the door state over and over in a race condition.

**Comment by Raycoms** [comment]
https://buildsystem.ldtteam.com/guestAuth/repository/download/LetSDevTogether_Minecolonies_Branches_Build/66850:id/build/libs/minecolonies-0.13.1198-PERSONAL-universal.jar

Can you tell me if this fixes the problem?

**Comment by Raycoms** [comment]
or this: https://buildsystem.ldtteam.com/guestAuth/repository/download/LetSDevTogether_Minecolonies_Branches_Build/66944:id/build/libs/minecolonies-0.13.1204-PERSONAL-universal.jar
