### ISSUE TITLE
Updating from 496 to 502 broke my entire village.

### ISSUE THREAD

**Issue by Moleculor** [ldtteam/minecolonies#6215]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: 0.13.502-ALPHA
- Structurize Version: 0.13.100-RELEASE
- Related Mods and their Versions: The official Minecolonies showcase pack with Forge 35.0.18

## Expected behavior
I expect my village to still be accessible and functional without full and complete rebuilds of the entire thing after upgrading.

## Actual behavior
Every building (except the town hall) claims its building is gone. The clipboard has all the previous requests that used to be on it listed as if they're from \<UNKNOWN\> rather than the villagers in question. 

![2020-12-07_20 00 58](https://user-images.githubusercontent.com/3865976/101429834-70fad200-38c9-11eb-9217-3aacb13790d0.png)
![2020-12-07_20 01 18](https://user-images.githubusercontent.com/3865976/101429837-71936880-38c9-11eb-8e40-35548f0c97da.png)
![2020-12-07_20 01 25](https://user-images.githubusercontent.com/3865976/101429839-722bff00-38c9-11eb-8f67-1174a8f88a8f.png)
![2020-12-07_20 01 45](https://user-images.githubusercontent.com/3865976/101429841-722bff00-38c9-11eb-820c-72dfed8899e9.png)
![2020-12-07_20 01 52](https://user-images.githubusercontent.com/3865976/101429842-722bff00-38c9-11eb-8b42-a68b1f7f04bd.png)
![2020-12-07_20 02 13](https://user-images.githubusercontent.com/3865976/101429844-72c49580-38c9-11eb-809a-44746a08e7d4.png)
![2020-12-07_20 09 00](https://user-images.githubusercontent.com/3865976/101429845-72c49580-38c9-11eb-9683-2b9bd5b9471d.png)
![2020-12-07_20 09 02](https://user-images.githubusercontent.com/3865976/101429847-72c49580-38c9-11eb-9aa9-e58670496561.png)

## Steps to reproduce the issue

1. Be running the Minecolonies pack with Minecolonies updated to 496.
2. Update to 502.

### Logs

- latest.log: https://gist.github.com/Moleculor/bd63752a0514c8df264e5fc5722f1de3

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by gattsuru** [comment]
My environment isn't set up to easily debug this, but can replicate it.

One spot to check, in AbstractBuildingWorker.java: 
>public String getJobDisplayName()
    {
        if (jobDisplayName.isEmpty())
        {
            jobDisplayName = createJob(null).getName();
        }
        return jobDisplayName;
    }

But in AbstractBuildingFarmer.java: 
>@NotNull
    @Override
    public IJob<?> createJob(@NotNull final ICitizenData citizen)
    {
        if (!farmerFields.isEmpty())
        {
            for (@NotNull final BlockPos field : farmerFields)
            {
                final TileEntity scareCrow = getColony().getWorld().getTileEntity(field);
                if (scareCrow instanceof ScarecrowTileEntity)
                {
                    ((ScarecrowTileEntity) scareCrow).setOwner(citizen.getId());
                }
            }
        }
        return new JobFarmer(citizen);
    }

Looking into it further to see if there are other effects going on, or if just popping the Farmer hut stops the behavior.

EDIT: for anyone having this issue, I'd be _very_ interested to know if tearing up the farmer hut solves the problem after ~30 seconds, or if they see the issue without having a farmer built.

**Comment by Aduis1210** [comment]
issue is affecting the patron server as well

**Comment by Raycoms** [comment]
fix pushed
