### ISSUE TITLE
Suddenly not owning my colony

### ISSUE THREAD

**Issue by itismee** [ldtteam/minecolonies#6219]
**Prerequisites**
 I am running the latest alpha version of MineColonies and Structurize for my Minecraft version.
 I checked the MineColonies/Structurize wiki and made sure my issue is not covered there.
 I made sure that this issue is not a duplicate of any existing issue.

**Context**
Minecraft Version: 1.16.4
MineColonies Version: 0.13.502-ALPHA
Structurize Version: 0.13.100-RELEASE
Related Mods and their Versions: I'm running your official modpack on curseforge.

**Expected behavior**
Continuing to use the townhall to check happiness etc.

**Actual behavior**
Seeing message "You are inside [colony name] owned by [colony owner]. You do not currently own a colony" as officer of the town. As owner, it's the same message just with "you own a colony at [coordinates where the town hall block I'm accessing]" ...

**Steps to reproduce the issue**
Not sure. It has happened twice now, but I don't see any resemblance between behaviour before it.

**Logs**
There is no log from after the incidents, but I can attach the latest log...

[latest.log](https://github.com/ldtteam/minecolonies/files/5662188/latest.log)

**Comment by ravenbuilder934** [comment]
Update to v1.9 of the modpack, this was already hotfixed

**Comment by itismee** [comment]
v1.9 isn't out for me yet... :)

**Comment by ravenbuilder934** [comment]
It's out, the launchers just haven't recognized it yet. Download it manually from the curseforge website

**Comment by itismee** [comment]
Alright, thanks
