### ISSUE TITLE
Builder stops walking/working untill player is close to builder.

### ISSUE THREAD

**Issue by Wissi** [ldtteam/minecolonies#622]
1.10.2 v0.6.5

Builder will stop walking to/from builder's hut/build if player is more than 25 blocks away. Will also stop working/building.
Builder will continue if player shortens the gap between the player and builder.

All other workers have no issue doing their job even if player is 50 blocks away or more.

**Comment by marchermans** [comment]
As per request I started merging Issues that are related to things I found while going through the source code. One of these is the request system. Closing this in favor of #638

**Comment by Wissi** [comment]
This is NOT related to the "Materials/Requests" handling system. Why merge it with #638?

It is a separate issue involving the builder's Pathfinding/AI detecting the player at a certain distance to be able to move to/from a build.

This issue is only for the builder, other workers do not have this issue. Guards, farmer, miner.

**Comment by marvin-bitterlich** [comment]
Is this something that can be reproduced? The spawn colony builder at least works.

**Comment by marchermans** [comment]
@Wissi misread this i will reopen as soon as you create a reproduction.

**Comment by Raycoms** [comment]
There shouldn't be anything like this. The workers should only stop if
you're like sooo far away so that the chunk isn't rendered.

2017-02-25 15:23 GMT-03:00 Orion <notifications@github.com>:

**Comment by Wissi** [comment]
Sry...  it was a problem at the beginning of the new server (and an issue since the last server) now I've made 2 different SSP worlds and tried to reproduce with latest Minecolonies v0.6.6 and the issue seems to have been cleared. Must have been cleaned out sometime in all the coding.

Thank you for closing the issue, can't reproduce it with latest.
