### ISSUE TITLE
Colony population remains at 4/4 perpetually

### ISSUE THREAD

**Issue by AnkaraSoulreaver** [ldtteam/minecolonies#6225]
I've seen several bug reports but I see no viable solutions.  I have a level 2 town hall.  I have 2 level 1 houses and a level 2 house (with a male and female resident).  I have a tavern with no residents.  This means I have a minimum of 8 beds, 9 if the bed in the town hall is a viable occupant.  However, my town hall still states 4/4 citizens.

One suggestion mentioned is recalling citizens to the town hall.  I see no button to do this.  

Visitors indicate there is no room to accept a new resident.  Children are not being born.  The base 8 villagers will not arrive.

Please help.

**Comment by ravenbuilder934** [comment]
Update, this was already fixed
