### ISSUE TITLE
Townhall LVL 1 schematic too small

### ISSUE THREAD

**Issue by CoconutCurry** [ldtteam/minecolonies#623]
### Minecolonies version

version 6.

### Expected behavior

When TH block placed, construction tape will show max size for level 5 building

### Actual behaviour

Construction tape only shows level 1 size.

**Comment by pmardle** [comment]
That's actually a scan failure with the Level 1 TH.. The Scan size of the Level 1 TH should be the same as the other levels to prevent this.

**Comment by xavierh** [comment]
@Kostronor I wonder if we should do some sanity check when starting the server and have a warning when the sizes are different between upgrade

**Comment by Raycoms** [comment]
Could you rescan the TH correctly @pmardle ?

**Comment by marvin-bitterlich** [comment]
@pmardle any news? :P

**Comment by pmardle** [comment]
Remind me later and i'll try and do it tonight :)

**Comment by marvin-bitterlich** [comment]
@pmardle remind xD

**Comment by cltnschlosser** [comment]
@pmardle Just going to throw another poke here.

**Comment by Raycoms** [comment]
@pmardle

**Comment by Raycoms** [comment]
Should be fixed in the newest alpha
