### ISSUE TITLE
Stonemason cannot craft polished basalt or polished blackstone

### ISSUE THREAD

**Issue by ravenbuilder934** [ldtteam/minecolonies#6231]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version:
- Structurize Version:
- Related Mods and their Versions: none

## Expected behavior
The Stonemason would be able to craft polished basalt or polished blackstone, since they're made from 4 basalt and 4 blackstone respectively, and both basalt and blackstone can be considered stone.

## Actual behavior
The recipes cannot be taught to the stonemason.

## Steps to reproduce the issue

1. Try to teach the polished blackstone or polished basalt recipes to the stonemason
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes
Reported on Discord

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Mekle001** [comment]
Ok, those aren't part of the normal forge:stone tag. We'll have to do a pass through all of our crafter permission tags to add them and the appropriate variants.
