### ISSUE TITLE
Build Tool can not be used from left hand in survival while Minecolonies is installed.

### ISSUE THREAD

**Issue by Lejoni** [ldtteam/minecolonies#6232]
### Prerequisites 

- [x] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- Structurize Version: 1.13.102-ALPHA
- MineColonies Version (if related bug): 1.13.510-APLHA
- Related Mods and their Versions: Minecolonies Official Modpack 2.1

## Expected behavior

Expect to be able to use the build tool in left hand as well as right hand.

## Actual behavior

When I right click on a solid block with Build tool in left hand, the GUI pops up and disappears and I get a chat message (see image bellow.

![Build Tool Bug](https://user-images.githubusercontent.com/10013087/101825680-3c3b8480-3b2e-11eb-9236-f7d7afa80c5d.png)

## Steps to reproduce the issue

1. Use Official MineColonies Modpack
2. Put Build tool in off-hand (left hand)
3. Right click on a solid block.

### Logs

- latest.log: 
- crashlog: 

### Notes

I obviously have Minecolonies installed.
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Lejoni** [comment]
> Not sure if we want to fix this (afaik vanilla things like book and quill don't open when if off-hand), but a different message should be printed

The reason I wanted to try to have it in my off-hand was so I could still open doors and such.
If it's in main hand, it triggers even if what you are right clicking is something like a door.

**Comment by marchermans** [comment]
This is a minecolonies issue.
It probably does not properly handle the override.
