### ISSUE TITLE
workers will make a new whole request if deliverman is stopped by accident while the completed items are in the deliverman's backbag.

### ISSUE THREAD

**Issue by xiaobbl** [ldtteam/minecolonies#6237]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [xI checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.15.2
- MineColonies Version:0.13.484
- Structurize Version:
- Related Mods and their Versions:

## Actual behavior
justas the title said.
by the way,these wasted items will be put into the warehouse and they can be recognized and used again.

## Steps to reproduce the issue

1. make a request
2.make the final delivery happen at dusk and make sure that deliveryman has already gotten the items(it needs to be "lucky" enough)
3. come to see the request GUI so that happens.

### Logs

- latest.log: 
- crashlog: 

### Notes
it does seem to be a issue happens in old versions,but i noticed that neither was it in opened issue nor closed in recent days.So i give this issue.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
That is intentional yes. It is very hard to do any partial recovery if a failure occurs down the chain. Thus, to make sure the system is somehow robust, we restart the process entirely.

**Comment by xiaobbl** [comment]
> That is intentional yes. It is very hard to do any partial recovery if a failure occurs down the chain. Thus, to make sure the system is somehow robust, we restart the process entirely.

yep,but i wonder if it is normal that a new request is needed even if deliveryman just go sleep and the wasted items cant be recognized by the same worker.so the meterials are made again and again, just like #5395 .now a lot of resource of mine are wasted unreasonbly.

**Comment by ravenbuilder934** [comment]
5395 was fixed

**Comment by xiaobbl** [comment]
> 5395 was fixed

it seems like 5395 but not really.5395 is a large amount of resource in one request but this isnt.
