### ISSUE TITLE
Pathfinding issues with Medieval Dark Oak House (level 2)

### ISSUE THREAD

**Issue by Moleculor** [ldtteam/minecolonies#6238]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: 514
- Structurize Version: 102
- Related Mods and their Versions: v2.1 of the Minecolonies pack, otherwise.

## Expected behavior
I would expect the colonists to be able to walk to the stairs, up them, and to bed.

## Actual behavior
They are unable to find their way to the base of the stairs.

![2020-12-12_13 30 48](https://user-images.githubusercontent.com/3865976/101993263-bda22c80-3c7e-11eb-9405-a24962754b4b.png)
![2020-12-12_13 29 29](https://user-images.githubusercontent.com/3865976/101993264-c0048680-3c7e-11eb-9032-7e3efe63ee48.png)

The two people staying in this house enter through the double doors (which I have oriented on the western wall of the building) of the Medieval Dark Oak level 2 House. The man invariably arrives first and arrives at the hut block, hops once, then simply stands, staring wistfully at the stairs just on the opposite side of the hut block instead of taking a left turn to reach the base of those stairs.

The woman arrives second, and repeatedly attempts to jump over the man and the hut block, but is repeatedly pushed back by the soft forcefield that is a mob in Minecraft, repeatedly jumping and being pushed back over and over and over again. 

They never arrive in their beds.

## Steps to reproduce the issue

1. Have a level two Medieval Dark Oak house. (Orientation with the double doors to the west may matter here?)
2. Wait for night to slowly fall.
3. Observe as the two residents approach (from the north?) and fail to ever reach the stairs.

### Logs

- latest.log: https://gist.github.com/Moleculor/bd4801d9eaed3380af5401f70eb36bf8

### Notes

This was happening on 513, as well. Not sure if earlier versions would have been affected, since this building wasn't here before then. It happens basically every night.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Same problem as 6214 inherently

**Comment by Moleculor** [comment]
> Same problem as 6214 inherently

Really? Because from #6214's description and you mentioning it on stream, it sounds like #6214 is about being knocked off of stairs, while this one seems to be colonists very much _choosing_ this path but still struggling with it somehow. It's the initial path they try to take, not one they're knocked in to. 

So I switched on pathfinding debug and recorded a little video. In it you can see the path planned out is directly up and over the hut block in question, but the guy who first arrives for some reason simply chooses to jump too early to get over the block, and then seems to get confused. He's never knocked off at all.

https://youtu.be/UbdorF4JDNA

I honestly have no idea if these pictures may help. Probably the fourth and sixth image?

![Base Profile 2020 12 12 - 15 10 00 02 DVR mp4_snapshot_02 22_ 2020 12 12_15 15 14](https://user-images.githubusercontent.com/3865976/101995482-be8f8a00-3c8f-11eb-92de-9b567983b6a7.jpg)
![Base Profile 2020 12 12 - 15 10 00 02 DVR mp4_snapshot_02 35_ 2020 12 12_15 17 01](https://user-images.githubusercontent.com/3865976/101995489-bfc0b700-3c8f-11eb-8914-7136f4b962f6.jpg)
![Base Profile 2020 12 12 - 15 10 00 02 DVR mp4_snapshot_02 40_ 2020 12 12_15 17 32](https://user-images.githubusercontent.com/3865976/101995488-bfc0b700-3c8f-11eb-8079-7bd9c2d3df78.jpg)
![Base Profile 2020 12 12 - 15 10 00 02 DVR mp4_snapshot_02 45_ 2020 12 12_15 17 53](https://user-images.githubusercontent.com/3865976/101995487-bf282080-3c8f-11eb-92bf-dff10b251c6d.jpg)
![Base Profile 2020 12 12 - 15 10 00 02 DVR mp4_snapshot_02 51_ 2020 12 12_15 18 31](https://user-images.githubusercontent.com/3865976/101995486-bf282080-3c8f-11eb-832b-dde55b4e0845.jpg)
![Base Profile 2020 12 12 - 15 10 00 02 DVR mp4_snapshot_02 52_ 2020 12 12_15 18 39](https://user-images.githubusercontent.com/3865976/101995485-bf282080-3c8f-11eb-86a1-a45daa606d01.jpg)
![Base Profile 2020 12 12 - 15 10 00 02 DVR mp4_snapshot_02 56_ 2020 12 12_15 18 48](https://user-images.githubusercontent.com/3865976/101995484-be8f8a00-3c8f-11eb-9162-86894e276aa0.jpg)

**Comment by Raycoms** [comment]
The falling off the stairs leads to the same situation that you have

**Comment by Moleculor** [comment]
Ah, so whatever the falling-off-stairs-fix is will also fix jumping too early to get over the hut block?
