### ISSUE TITLE
Builder building Marketplace in survival mode wants grass blocks

### ISSUE THREAD

**Issue by Cyranth** [ldtteam/minecolonies#624]
### Minecolonies version

version X.X.XXXX or curse 1.11.2

### Expected behavior

- Builder will build the marketplace

### Actual behaviour

- Builder wants a grass block to put around the fountain in the marketplace.  In survival mode, a grass block cannot be created, so the builder becomes frustrated and yells for a grass block every few minutes and does not complete the marketplace.  Giving him a dirt block does not satisfy him.

### Steps to reproduce the problem

1. start game in survival mode with builderInfiniteResources set to false
2. use builder wand to place schematic for marketplace.  make sure that a non-grass block is in the location where the perimeter of the fountain will be.  In my case it was gravel.
2. Builder digs out the non-grass block area.
3. Builder asks for grass block
4. Profit

### Workaround
1. wait for builder to yell for grass blocks
2. place dirt blocks where he wants to put the grass blocks (ensure connection to existing grass block)
3. wait for grass to spread to dirt blocks
4. listen but ignore builder yelling for grass blocks
5. when all dirt blocks become grass blocks, save and exit game
6. load saved game
7. builder re-assess the situation, realises that grass blocks exists where he wants them, continues to build marketplace.

**Comment by marvin-bitterlich** [comment]
Weird, the builder should be able to distinguish this.. Maybe this is a regression of that. Thanks for the report.

**Comment by Raycoms** [comment]
I will fix this when I am back

Am Samstag, 18. Februar 2017 schrieb Marvin Hofmann :

**Comment by Nitrato-de-putasso** [comment]
Hey, thanks for the tip, you a genius!!!

I'm play Minecraft 1.15.2 with de MOD and the game still have a few glitch glitchs... :(
