### ISSUE TITLE
smelter complete failure(too many ores?)

### ISSUE THREAD

**Issue by tails1974seeyounextgame** [ldtteam/minecolonies#6240]
smelter complete failure. 
arrives at smelter and does nothing,
will not work or retreive any ore 
likely the ore list is so long that its infinitely parsing the list but never reches the end

https://imgur.com/a/9hXAuNz <rack with more ore and insanium coal blocks (botania)
https://imgur.com/a/x8EtcaQ   <smeltist with coal and ore grabbed
https://imgur.com/a/DmxSx0a <completely empty furnace
https://imgur.com/a/Di3Rbyf   <ore list

**Comment by tails1974seeyounextgame** [comment]
also i cant force teach any ore recipes because the recipe wont let you insert anything for the output and thus cannot click done. likely related to 1.4 changes

**Comment by ravenbuilder934** [comment]
Please fill out the entire template

**Comment by tails1974seeyounextgame** [comment]
there is no template pinned to this channel?

**Comment by ravenbuilder934** [comment]
What do you mean? Github doesn't have channels or pins. When you clicked on Create New Issue, you should've seen a list of templates to choose from.

**Comment by tails1974seeyounextgame** [comment]
(i just cloned someone elses, im using firefox 65 with an array of donottrack and adblock ultimate features, and others)
I am running the latest version of MineColonies and Structurize for my Minecraft version.
I checked the MineColonies/Structurize wiki and made sure my issue is not covered there.
I made sure that this issue is not a duplicate of any existing issue.

Context

    Minecraft Version: 1.16.4
    MineColonies Version: 513
    Structurize Version: 102


Expected behavior
Logs

   https://paste.atlauncher.com/view/1f6ea032

**Comment by tails1974seeyounextgame** [comment]
ok so i noticed myself in the logs that it states coal not a json object, so i removed coal from the smelters inventory and they cycled once, then stopped moving again., checked they do not have or recieve coal

could be an issue with trying to wait for the insanium fuel to burn out in the furnace, it hasa burn time of about 1.6 million seconds.

could someone please update the code so that the smelter doesnt wait for fuel to burn out but instead works on a 10k tick timer?

**Comment by tails1974seeyounextgame** [comment]
right so i did 
[12/12/2020 16:57:24 PM] [16:57:24] [Render thread/INFO]: [CHAT] Restart for citizen Judith B. Grofhurst scheduled.
[12/12/2020 16:57:25 PM] [16:57:25] [Render thread/INFO]: [CHAT] Citizen Judith B. Grofhurst succesfully restarted.
and purged the inventory of the racks, reinserted the furnace with nothing inside, and purged inventory for the smelter.

...now she literally has no request and no inventory and the delivery people arent delivering any of the tons of ore i have trapped in the warehouse.

**Comment by tails1974seeyounextgame** [comment]
issue resolved, by itself, 5 ingame days later >.>
 mod incompatability is likely botania > insanium additions
if you could resolve the furnace issue with "insanium coal" and "insanium coal block" that would be awesome otherwise case closed.

**Comment by tails1974seeyounextgame** [comment]
ok actually. the issue resolved EMMEDIATELY after i sorted the warehouse tier 5. you might want to adda checkbox feature to the warehouse to auto sort every day at 625, and i recommend having it on by default. finding things wasa nighmare to begin with.. and youll have less conflicts with itemid finding.

**Comment by Raycoms** [comment]
okay, I looked into this and thought about it. I definitely don't agree with a mod adding fuel that burns basically for forever. And if it doesn't work with any of our workers that is completely fine for me.

**Comment by Raycoms** [comment]
You should be able to turn off that kind of fuel in the smelter such that only regular fuel is requested and used.

**Comment by tails1974seeyounextgame** [comment]
after long analysis my brain actually returned that it was an issue with atm6 particularly allthemods "alltheores.jar" which undefines default ores and was spamming that every 10 seconds in the atlauncher(which is NOT tlauncher) error window). and atm6 devs are literally drinky drinky trolls so not worth the effort to fix. but the point is insanium coal works just fine
![image](https://user-images.githubusercontent.com/5803466/111867902-a8533300-893c-11eb-93bd-450f3bec5f86.png)
