### ISSUE TITLE
Failed to creat modpacks: CaveColonies

### ISSUE THREAD

**Issue by Coldame** [ldtteam/minecolonies#6243]
https://cdn.discordapp.com/attachments/417642620425338880/787756949646606366/unknown.png

i don't know how to fix this

**Comment by Raycoms** [comment]
curse problem

**Comment by Coldame** [comment]
I know .... how to fix it so...

**Comment by Coldame** [comment]
> curse problem

But how to fix it ... i know there is a bug ...

**Comment by Raycoms** [comment]
Ask curse, they are having modpack issues
