### ISSUE TITLE
Modpack will not install in CurseForge due to "Failed to get mod loader from manifest!"

### ISSUE THREAD

**Issue by jakey1995abc** [ldtteam/minecolonies#6246]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: 2.1
- Structurize Version: n/a

## Problem description

Modpack will not install in CurseForge due to "Failed to get mod loader from manifest!"

### Notes or related things

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
This is a curseforge issue, report to them and in the meantime we recommend gdlauncher https://gdevs.io
