### ISSUE TITLE
[1.16.4] Citizens don't stay inside during a raid

### ISSUE THREAD

**Issue by Sandriell** [ldtteam/minecolonies#6248]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: minecolonies-0.13.515-ALPHA-universal
- Structurize Version: structurize-0.13.102-RELEASE-universal
- Related Mods and their Versions: All the Mods 6 1.3.3

## Expected behavior
That citizens would stay inside and hide during a raid. I'm like 99% sure they used to do this.

## Actual behavior

When a raid begins, and after sleeping, the citizens all run out just like normal and end up getting themselves killed.

## Steps to reproduce the issue

Raid starts
Sleep
Watch citizens running about like nothing is going on and getting killed.

### Logs

N/A

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
I can confirm they used to stay inside

**Comment by Sandriell** [comment]
This appears to be fixed and working now. Thanks!
