### ISSUE TITLE
Miners and Mineshafts

### ISSUE THREAD

**Issue by pmardle** [ldtteam/minecolonies#625]
The miner stops and get stuck whenever he comes across rail tracks when either building his vertical or horizontal shafts..

When he comes across it he just stands there looking at it's shininess and does nothing.. As soon as the player breaks the rail track.. off he goes again happily..

**Comment by Raycoms** [comment]
Damit that's because of the rail mod

Am Freitag, 17. Februar 2017 schrieb pmardle :

**Comment by pmardle** [comment]
hmmm.. any easy way to fix it ?

**Comment by Raycoms** [comment]
@Kostronor can we make that for every block he doesn't recognize he has to
use a diamond pickaxe?

Am Samstag, 18. Februar 2017 schrieb pmardle :

> hmmm.. any easy way to fix it ?
>
>
> On Sat, Feb 18, 2017 at 1:55 AM, Raycoms <notifications@github.com

**Comment by marvin-bitterlich** [comment]
tracking this on #637
