### ISSUE TITLE
Added mobs to Guard Attack List, are ignored by Guards

### ISSUE THREAD

**Issue by Neitcore** [ldtteam/minecolonies#6250]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: 0.13.515-ALPHA
- Structurize Version: 0.13.102-ALPHA
- Related Mods and their Versions: Ice and Fire 2.1.3

## Expected behavior

Mobs that added to Guard Attack List in config will be attacked by Guards
## Actual behavior

Guards ignoring new mobs in list. 

## Steps to reproduce the issue

1. Add mobs to config to guardresourcelocations list
2. Enter the map 
3. Check if new mob attack statement is "On"
4. Click the "recalculate" button
5. Guards will not attack recently added mobs

### Logs

- latest.log: https://gist.github.com/Neitcore/edc931db2719d5d9674c69f7ca615f35
- crashlog: 

### Notes

I tried add rabbit and Fire Dragon to config, both of them are added to list, but are ignored by guards
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Just pushed out this fix.
