### ISSUE TITLE
Miner enjoys doing the backstroke

### ISSUE THREAD

**Issue by ziba1** [ldtteam/minecolonies#6253]
### Prerequisites 

- [ x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: 0.13.521
- Structurize Version:0.13.104
- Related Mods and their Versions:

## Expected behavior

Miner would be walking about 

## Actual behavior

miner slides along the floor 

![citizen bug](https://user-images.githubusercontent.com/12607900/102282004-d719d180-3f27-11eb-9594-17430337fa5b.jpg)

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Can you reproduce this?

**Comment by ziba1** [comment]
> 
> 
> Can you reproduce this?

Ive updated a few times since this, and they dont seem to do it anymore
