### ISSUE TITLE
problems with the number of colonists

### ISSUE THREAD

**Issue by poltoseg** [ldtteam/minecolonies#6257]
Good afternoon. I have 4 colonists, but the system writes 11/11 and no new ones are born. I have: structurize-0.13.104-ALPHA-universal and minecolonies-0.13.521-ALPHA-universal

I use Google Translate and write here for the first time. Sorry.

![alt text](https://ibb.co/9ytrytB)

**Comment by poltoseg** [comment]
built a new house. It became 12/12, but the colonist is still 4.

**Comment by Raycoms** [comment]
seems to be corrupt world

**Comment by Raycoms** [comment]
(user was able to solve issue by making a new world)
