### ISSUE TITLE
Workers

### ISSUE THREAD

**Issue by PainGoated** [ldtteam/minecolonies#6259]
my worker has a chat symbol on top of his head and it wont let me see what he has to say, he just keeps spamming the same lines every time I right click.

someone said delete optifine but not sure what will happen if i just delete it, will it affect my game?

im using 0.13.258-alpha for curseforge its the only one you can use.

any help on the optifine deletion or this issue would be great

**Comment by Raycoms** [comment]
Please fill in the entire template

**Comment by ravenbuilder934** [comment]
Deleting optifine will *not* affect your game, as optifine only changes the way your game looks. However, optifine actually fixed this issue already in a 1.16.3/1.16.4 release, so it might be better to just update optifine. 

What do you mean it's the only one you can use? The latest is 0.13.521 and multiple people use it without issues.
