### ISSUE TITLE
[Feature] Citizen Speed boost based on path material

### ISSUE THREAD

**Issue by gd71** [ldtteam/minecolonies#626]
Polished andesite is a nice block to build path
It should be recognized as stone bricks letting citizen go faster

**Comment by Raycoms** [comment]
We should probably have a nice way of calculating the "rarity" of a material, or the difficulty of making it and  use this to calculate the speed bonus of it.
Else we have to add a config option to allow players to add custom blocks, or a way to do that in the ingame GUI.

**Comment by Wissi** [comment]
@Raycoms I think the best is to have a config option for as you stated:

> add a config option to allow players to add custom blocks

Due the huge variety of blocks in so many mods and the way they are coded.
Is this still considered an open issue, or can we close it now?

**Comment by Raycoms** [comment]
Closed in favor of joint issue.
