### ISSUE TITLE
Plantation Farm not working

### ISSUE THREAD

**Issue by Danzle00** [ldtteam/minecolonies#6260]
![ps](https://user-images.githubusercontent.com/76173661/102510621-c94c8380-40c2-11eb-99c1-e3e6ae998f01.png)
Playing on Single Player Valhelsia 3 modpack v1.16.4
Plantation Asian Sugarcane not planting correctly and if i'm not mistaken it doesn't auto harvest(applies to bamboo too if i am not wrong)

**Comment by ravenbuilder934** [comment]
Please fill out the entire template
