### ISSUE TITLE
Only women spawn in my colonie

### ISSUE THREAD

**Issue by CyberlabDK** [ldtteam/minecolonies#6266]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.16.4
- MineColonies Version: minecolonies-0.13.525-ALPHA-universal.jar
- Structurize Version:
structurize-0.13.104-ALPHA-universal.jar
- Related Mods and their Versions:All the mods 6

## Expected behavior

That men also spawn
## Actual behavior

Only women spawns in my village tried starting a new one twice, 

## Steps to reproduce the issue

1. 
2. Create town
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Just to be clear, all of your initial 4 citizens are women?

**Comment by CyberlabDK** [comment]
no actually i got one man at the begning, accidents happened and he died, but after him i just got women, tried killing 10 or so just to be sure it was not bad rng

**Comment by ravenbuilder934** [comment]
Intentional then, the fourth colonist is always a woman. Killing two at once should get you a man, or you can build a tavern and recruit one
