### ISSUE TITLE
Scrolling through a colonists requests crashes Minecraft

### ISSUE THREAD

**Issue by KodisMaximus** [ldtteam/minecolonies#6268]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**
(As near as I can tell)
### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: 0.13.525-Alpha-Universal
- Structurize Version: 0.13.104-Alpha-Universal
- Related Mods and their Versions:

justenoughbeacons | 3.1-1.16.3
-- | --
inventoryprofiles | 0.4.2
elenaidodge | 1.16.2-1.7.2
beenfo | 1.16.4-forge35.0.7-1
astrosorc | 1.16.4-1.3.0
astralsorcery | 1.16.4-1.13.4
doggytalents | 2.0.1.1
terraforged | 0.2.0-ALPHA-1
xaeroworldmap | 1.11.4
cookingforblockheads | 9.2.2
controlling | 7.0.0.11
placebo | 4.3.3
citadel | 1.5.3
gemsnjewels | 0.18.0
bookshelf | 9.2.16
sophisticatedbackpacks | 1.16.4-0.11.1.88
waila | 1.10.11-B78_1.16.2
waterstrainer | 1.16.3-10.0.0
jeresources | 0.12.0.100
mineralchance | 1
peace | 1.16.2-1.0.1.0
supplementaries | 0.9.9
farmersdelight | 1.16.3-0.2.4b
aequivaleo | 0.1.19-ALPHA
ambientsounds | 3.0.3
toolswap | 1.2.0
lollipop | 3.2.3
ornamental | 4.3.2
horsemodifiers | 1.3.1
pamhc2foodextended | version
curios | 1.16.4-4.0.3.0
sisser | 1.7
patchouli | 1.16.4-48
peacefulsurface | 1.16.4-v1
collective | 1.53
infinitymending | 0.1.0
observerlib | 1.16.4-1.4.4
productivebees | 1.16.3-0.5.1.1
cloth-config | 4
bettas | 1.1.0
hearthstonemod | 1.16.3-0.5.2
geckolib3 | 3.0.0-beta.10
repairchests | 1.6
betteradvancements | 0.1.0.102
alchemistinfusion | 1.0.0
clienttweaks | 5.2.0
doubledoors | 2.1
goo | 0.8.0.2
cucumber | 4.1.5
inventoryspam | version
pamhc2trees | 1.0.0
craftingstation | 4.1.1
jei | 7.6.0.58
elementalcraft | 1.16.3-2.4.13
optiforge | 0.4.3
callablehorses | 1.2.1.4
scannable | 1.7.1.7
wawla | 7.0.2
waystones | 7.3.1
clumps | 6.0.0.12
shutupexperimentalsettings | 1.0.1
mgui | 3.1.3
appliedenergistics2 | 8.1.0
naturescompass | 1.16.4-1.8.5
sereneseasons | 1.16.4-4.0.0.76
botanypots | 6.0.6
curioofundying | 1.16.4-5.1.0.0
farmingforblockheads | 7.2.1
alib | 1.16.3-2
tinymobfarm | 1.1.1
dads_sewing | 6
ars_nouveau | 1.7.1
mysticalworld | 1.16.4-0.3.1.2
forge | 35.1.7
ceramics | 1.5.2
craftingtweaks | 12.2.0
alchemistry | 1.16.3-1
minecraft | 1.16.4
enchdesc | 6.0.2
swingthroughgrass | 1.16.4-1.5.3
playerplates | 1.16.3-forge-1.0.0
toolbelt | 1.15.2
mana-and-artifice | 1.2.0.1
immersiveengineering | 1.16.4-4.1.1-128
bettercontrols | 1.1.0
pamhc2crops | version
creativecore | 2.0.0
mantle | 1.6.43
xaerominimap | 20.29.1
chemlib | 1.16.3-1
notenoughbreeding | 1.16.4-1.0.0
fastbench | 4.4.1
polymorph | 1.16.4-0.18
autoreglib | 1.6-47
quark | r2.4-277
apotheosis | 4.4.1
storagedrawers | 8.2.1
regrowth | 1.42.0.17
tubesreloaded | 1.5.0.2
structurize | 0.13.104-ALPHA
ambientenvironment | 4.0.0.5
minecolonies | 0.13.525-ALPHA
fastfurnace | 4.3.0
actuallyusefulstonecutter | 1.0.4 mc 1.16.3
appleskin | 1.0.14
mobcatcher | 3.1
easypaxelmod | 1.16.4-1.0.8
solcarrot | 1.16.3-1.9.8
durabilityviewer | 1.16.4-forge35.0.7-1
exnihilosequentia | 1.16-1.3.2.0
balancedenchanting | 1

## Expected behavior
Scrolling through the request list of a colonist shouldn't crash the game

## Actual behavior
I right click on a colonist, skip the chit chat, and click on view requests. I am able to scroll up and down but when I try to scroll to the bottom of the list the game freezes, and then closes down. 

## Steps to reproduce the issue
I can reproduce this in creative by following the normal getting started steps to create a town hall, create a colony, create a builders hut, start the build, and then viewing the builders requests. 

1. Place a town hall
2. Start a new colony
3. Place a builders hut using the build tool
4. Wait for a worker to be hired 
5. Begin the build of the builders hut
6. View the colonists request list
7. Scroll down to the bottom of the request list. 

### Logs

https://gist.github.com/KodisMaximus/c4ff4d6ed1eb8517f8185eafe95bbaf6

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Can you send us the crash log as well?

**Comment by Raycoms** [comment]
Stale issue
