### ISSUE TITLE
Lumberjack and custom trees

### ISSUE THREAD

**Issue by gd71** [ldtteam/minecolonies#627]
Noooooooooo ! =D
![2017-02-18_16 48 09](https://cloud.githubusercontent.com/assets/25818272/23094490/5da52248-f5fa-11e6-8bfa-36a34f98aec8.png)
Any chance to get LumberJack ignore custom trees?

**Comment by marvin-bitterlich** [comment]
place cobblestone under it like always

**Comment by gd71** [comment]
wow I didn't know that
I will check and close the issue if successful

**Comment by gd71** [comment]
yep seem to fix the issue 
Thanks for the tip!

**Comment by gd71** [comment]
unfortunately,
it took some days but the lumberjack started again.
the cobblestone correspond to the original wood fingerprint
![2017-02-25_20 59 36](https://cloud.githubusercontent.com/assets/25818272/23334412/3bdba3ea-fb9e-11e6-9b18-156f695bddce.png)

**Comment by Raycoms** [comment]
the last log was about the cobblestone and he still mined it? Not a part of
the tree was over the dirt?

2017-02-25 17:07 GMT-03:00 gd71 <notifications@github.com>:

**Comment by gd71** [comment]
you make me doubt! lol
No, I don't think so, I took care about that

**Comment by Raycoms** [comment]
the thing is, if 1 part of the tree was over that dirt he will go there and
mine it, he is quite picky about that.

2017-02-25 17:18 GMT-03:00 gd71 <notifications@github.com>:

**Comment by gd71** [comment]
wait & see
![2017-02-25_21 27 54](https://cloud.githubusercontent.com/assets/25818272/23334553/9a64fed6-fba1-11e6-91c3-ad3060d0e2a0.png)
no more dirt around...

**Comment by Raycoms** [comment]
other side as well?

2017-02-25 17:32 GMT-03:00 gd71 <notifications@github.com>:

**Comment by gd71** [comment]
please! :D
![2017-02-25_21 36 36](https://cloud.githubusercontent.com/assets/25818272/23334606/840ec4c2-fba2-11e6-86f3-fa01fab5b5ec.png)

**Comment by Raycoms** [comment]
and he is still cutting it?

2017-02-25 17:37 GMT-03:00 gd71 <notifications@github.com>:

**Comment by gd71** [comment]
Not for now,
it's an other try

**Comment by gd71** [comment]
maybe one of the logs was above a polished andesite
can it be the issue I had?

**Comment by Raycoms** [comment]
that's possible.
He is quite picky with that.

2017-02-25 17:42 GMT-03:00 gd71 <notifications@github.com>:

**Comment by gd71** [comment]
lol! ok I will reopen it if it still occurs, but this time I have screens !
