### ISSUE TITLE
sandstone houses only have 2 beds so they are broken at lvl 3 and up

### ISSUE THREAD

**Issue by batty2112** [ldtteam/minecolonies#6271]
### Prerequisites 

- [x] I am running the minecolonies-0.13.479-BETA-universal and structurize-0.13.94-ALPHA-universal for my Minecraft 1.15.2.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.479-BETA-universal
- Structurize Version: 0.13.94-ALPHA-universal
- Related Mods and their Versions:

## Steps to reproduce the issue

1. play the game and build sandstone houses
2. upgrade them to lvl 3. then 4 then 5
3. you will notice that at level 3 and up there are only 2 beds in the houses, there should be 3 beds at level 3, 4 beds at lvl 4, and 5 beds at lvl 5.

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
MineColonies doesn't use the traditional alpha/beta/release classifications, as the entire mod can be considered in a beta state. However, curseforge limits the amount of releases and betas we can put out, so most often, the latest version will be an alpha. Alphas are just as stable as betas and releases. For this reason, please update to the latest alpha of both MineColonies and Structurize, as if I remember correctly this issue was already fixed.

**Comment by Raycoms** [comment]
Schematic issues to #5006

**Comment by batty2112** [comment]
I just tested the latest minecolonies-0.13.528-ALPHA-universal and structurize-0.13.105-ALPHA-universal for mc 1.15.2 by replacing the old mods in the mods folder, and the sandstone house/citizen has not been fixed/changed. just wanted to give you a heads up. do I need to restart my minecraft world etc to see the fix/change?

________________________________

**Comment by ravenbuilder934** [comment]
> I just tested the latest minecolonies-0.13.528-ALPHA-universal and structurize-0.13.105-ALPHA-universal for mc 1.15.2 by replacing the old mods in the mods folder, and the sandstone house/citizen has not been fixed/changed. just wanted to give you a heads up. do I need to restart my minecraft world etc to see the fix/change?

Closing Minecraft and reopening it should suffice, no need to make an entirely new world
