### ISSUE TITLE
[Mod Suggestion] 'Dustrial Decor

### ISSUE THREAD

**Issue by BlueDuckYT** [ldtteam/minecolonies#6279]
https://www.curseforge.com/minecraft/mc-mods/dustrial-decor

'Dustrial Decor adds a bunch of industrial themed building blocks.  I think it would integrate very nicely with minecolonies, as you would have the ability to add more houses/buildings with better industrialized themes.

**Comment by Raycoms** [comment]
This is for mod support and not modpack support. Modpack suggestions can be left on the curseforge modpack page.
