### ISSUE TITLE
Harvestcraft Shipping Bay Sponge problems

### ISSUE THREAD

**Issue by ProsperCraft** [ldtteam/minecolonies#628]
### Minecolonies version

minecolonies-universal-1.10.2-0.6.2879.jar

https://gist.github.com/ProsperCraft/ad291cfd3718f9f30d751c8c36db4139

### Steps to reproduce the problem

1. click on newly hired(to replace a missing buidler) inventory button.

**Comment by marvin-bitterlich** [comment]
`at com.pam.harvestcraft.tileentities.MessageShippingBinBuy.onMessage(MessageShippingBinBuy.java:66)`

I reported this at MatrexsVigil/harvestcraft#227 but no response the last 4 days
