### ISSUE TITLE
java.lang.NullPointerException: Ticking screen  Crash to Desktop

### ISSUE THREAD

**Issue by judicius** [ldtteam/minecolonies#6286]
### Prerequisites 

- [ x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: 0.13.535 ALPHA
- Structurize Version: 0.13.104 ALPHA
- Related Mods and their Versions:
Builders Delight 2 Mod pack

## Expected behavior
Right clicking to interact with builder would open panel or dialogue

## Actual behavior
Right clicking on builder opens dialogue "grey box" and immediately crashes to desktop with error.
This happens if the builder is requesting dialogue, showing an issue icon, or needing of nothing.
If "grey box" opens for dialogue, and you click on any of the options, crashes to desktop

## Steps to reproduce the issue
Created survival world
Cheated in wand, town hall, builder
placed town hall and builder
selected builder and build
right clicked on builder to interact
  if "grey box" for dialogue loads click enough with the chit chat
CTD

### Logs

- [latest.log](https://gist.github.com/judicius/bc2470c27afa6568c8a5848ee76bc954): https://gist.github.com/judicius/bc2470c27afa6568c8a5848ee76bc954
- [crashlog]( https://gist.github.com/judicius/fb9269cf7764ab4c4ffd847f10f6caea): https://gist.github.com/judicius/fb9269cf7764ab4c4ffd847f10f6caea

### Notes
I'm currently rebuilding the modpack (Builders Delight 2) one mod at a time and trying to duplicate. I've played hours with Minecolonies alone with Toast Control and JEI with no issue. If anything in the logs, crash logs, or from your experience can help narrow it down I'll test it into the ground.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Yes, there is a tool mod that doesn't correctly implement the tools which causes this crash. Unfortunately not much we can do there, they have to fix that on their side.

**Comment by judicius** [comment]
https://github.com/mrp-v2/VersatilePortals/issues/2

Reported to the mod i believe responsible, adding here for cross reference

**Comment by mrp-v2** [comment]
@Raycoms When you said the tool is incorrectly implemented, could you elaborate on that? Can you link me to a tool that is implemented correctly for comparison?

**Comment by Raycoms** [comment]
``` 
set.addAll(stack.getItem().getToolTypes(stack).stream().map(net.minecraftforge.common.ToolType::getName).collect(Collectors.toList()));
```

It's this line that crashes, so either the mod returns a null for getToolTypes on the item, or returns a list with a null value.

**Comment by mrp-v2** [comment]
Strange, all of Versatile Portals' items are not  given a tool type, and should just return an empty set. Are you able to figure out exactly which item is causing the crash?
P.S. The logs posted in https://github.com/mrp-v2/VersatilePortals/issues/2 show the narrowed-down mod list.

**Comment by mrp-v2** [comment]
Nevermind, turns out some are given a tool type for some reason. I'll remove that and see if it fixes the problem.

**Comment by Bidgam** [comment]
It would still do everyone a favor if you showed which mod was causing it, if possible... or at least prevent your mod from going "omg, crash".
