### ISSUE TITLE
Medieval Oak Gate (Decoration) Can't Upgrade to Level 3

### ISSUE THREAD

**Issue by emiliejirci** [ldtteam/minecolonies#6289]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: 0.13.525-ALPHA
- Structurize Version: 0.13.104-ALPHA
- Related Mods and their Versions:

## Expected behavior

Ability to upgrade the medieval oak gate decoration past level 2

## Actual behavior

Medieval oak gate stays stuck at level 2 with no option to upgrade it to level 3

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
Did you report that on discord? It's being looked at.

**Comment by Raycoms** [comment]
#5006
