### ISSUE TITLE
Colony Information shows always max number of Villagers

### ISSUE THREAD

**Issue by atcen** [ldtteam/minecolonies#6290]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.6.4
- MineColonies Version: 0.13.535
- Structurize Version: 0.13.104
- Related Mods and their Versions: none

## Expected behavior

Showing th number of villagers living in colony
## Actual behavior

Information shows always the max number of Villagers

![image](https://user-images.githubusercontent.com/1451287/103043136-1d041480-457c-11eb-9b08-9695d608a690.png)

## Steps to reproduce the issue

I tired to reproduce it by myself. so i just created a new colony in an instance only with mcol and structurize.
The behaviour was the same after building a few houses and guardtowers.

### Logs
none

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by X-Niter** [comment]
minecolonies-0.13.537-ALPHA-universal has this same issue. 

I never know how much I really have and so I just keep trying to add the people from the taverns to see if it either adds them or doesn't.
On top of this, the limit size of how many citizens we can have never changes unless I restart the server, or like last time where I updated to the latest.
![image](https://user-images.githubusercontent.com/30506033/103119926-2d2ef900-463b-11eb-950d-cccc4d86276e.png)

**Comment by atcen** [comment]
fixed in latest version
