### ISSUE TITLE
[AI] Couriers twitch on ladder.

### ISSUE THREAD

**Issue by Moleculor** [ldtteam/minecolonies#6291]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: 537
- Structurize Version: 104
- Related Mods and their Versions: Mostly the Minecolonies pack, with a few additions like Performant.

## Expected behavior
I would expect the couriers to pathfind properly.

## Actual behavior

The couriers twitch on the top of this ladder for a good minute or so before breaking free. If it helps, this is the level 1 Medieval Dark Oak sawmill. 

![2020-12-24_14 15 57](https://user-images.githubusercontent.com/3865976/103105408-4613bc00-45f3-11eb-8b25-27c2af58989c.png)

![2020-12-24_14 18 32](https://user-images.githubusercontent.com/3865976/103105409-46ac5280-45f3-11eb-889f-2644d34e75a1.png)

## Steps to reproduce the issue

1. Have a warehouse and courier(s).
2. Have a level 1 Medieval Dark Oak sawmill positioned so that the shortest path to the hut block is directly over the logs with rails/ladders on them.
3. Have the sawmill request something the couriers need to deliver. 
4. Play some rave music.

### Logs

- latest.log: https://gist.github.com/Moleculor/8a3217c1a60f564e52d98570e21c6b79

### Notes
Unce unce unce unce!

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Lielac** [comment]
I also noticed something similar with a level 3 wooden warehouse: its second level is accessible only by a ladder, and the couriers spend a lot of time flailing around unable to climb the ladders to access items on the second level. I eventually replaced the ladders with a little staircase, and so far they've been able to path up that just fine.

**Comment by Raycoms** [comment]
Fixed in newest

**Comment by tecnobrat** [comment]
I'm not sure this is fixed.  I still am having issues with my courier's getting stuck on ladders in my warehouse.

I think this is the fix you were referring to being in latest? https://github.com/ldtteam/minecolonies/pull/6378

Looking at it, it doesn't seem to fix ladders, only rails.

**Comment by Raycoms** [comment]
There are rails after those ladders, they tried to take the rails and got stuck afaik.

**Comment by tecnobrat** [comment]
Okay maybe I should open a different issue, but I'm confirming what @Lielac mentioned earlier that couriers get stuck trying to climb the ladder in the tier 3+ wooden (and other) warehouses.  They twitch back and forth for a long time, sometimes forever, unless you recall them back to their hut and let them have another try at it.

**Comment by Raycoms** [comment]
that's a different issue then. Please open a new one then, with the new info and potentially a way to reproduce it easily.
