### ISSUE TITLE
Crash - Spatial Guard Reinforcement Scroll

### ISSUE THREAD

**Issue by X-Niter** [ldtteam/minecolonies#6294]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- Forge Version: 1.16.4 - 35.1.13
- MineColonies Version: minecolonies-0.13.537-ALPHA-universal
- Structurize Version: structurize-0.13.104-ALPHA-universal
- Related Mods and their Versions:
> fastleafdecay-v25
> flatbedrock-1-16-4-1-1-6
> hwyla-forge-1-10-11-b78-1-16-2
> ironfurnaces-1-16-4-2-5-4
> jei-1-16-4-7-6-0-62
> justenoughresources-1-16-3-0-12-0-100
> mcw-bridges-1-0-4-mc1-16-4
> mcw-doors-1-0-1fix-mc1-16-4
> mcw-trapdors-1-0-0-mc1-16-4
> mcw-windows-1-0-2-mc1-16-4
> repairchests-1-16-4-1-6
> speedyladders-1-16-3-1
> wailaharvestability-mc1-16-2-forge-1-1-13
> worldedit-forge-mc1-16-3-7-2-1-dist

## Expected behavior

Hover over the item and simply get the little tooltip GUI showing its name and any other tool tip info that it may have.

## Actual behavior

Once you hover over the item, you freeze, then crash back to the launcher.

https://user-images.githubusercontent.com/30506033/103144424-a8051c00-46ee-11eb-89c6-3cec9cecbddc.mp4

## Steps to reproduce the issue

1. Get a Spatial Guard Reinforcement Scroll
2. Shift + Right Click a guard building to link it as needed
3. Click E to access inventory and hover over Spatial Guard Reinforcement Scroll

### Logs

- [latest.log](https://gist.github.com/X-Niter/5b64928c41ca3e3d1eb6421a00b2c924): 
- [crashlog](https://gist.github.com/X-Niter/abb53586623ad53358f2e51edbb1528c): 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by X-Niter** [comment]
Further troubleshooting has happened in regards to this crash. 
This crash only happens on a server instance and not in single player, I also was able to go to the nether and the end on the server-side instance, it was mentioned to me that Forge is having some kind of dim issue so I wanted to make sure I shared that info. :)

**Comment by gattsuru** [comment]
Looks to be specific to the scrolls calling ColonyManager.getColonyByDimension, but does impact all of them.  I'm not sure if there's a better place to get a colony's name from its id; while there are some safer options in ColonyManager like getColonyByWorld, I don't think any will be populated in a remote situation.
