### ISSUE TITLE
'Smoke' particles from citizens without visible cause

### ISSUE THREAD

**Issue by MatthiasMann** [ldtteam/minecolonies#6296]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: minecolonies-0.13.537-ALPHA-universal
- Structurize Version: structurize-0.13.104-ALPHA-universal
- Related Mods and their Versions:

## Expected behavior
Smoke particles are only generated when the citizen is completely hungry or ill etc

## Actual behavior
Smoke particles are emitted by my builder but he is neither hungry nor ill.

![2020-12-26_12 01 52](https://user-images.githubusercontent.com/6777029/103159806-2edcf600-47ce-11eb-951b-b3ddfa3699aa.png)
![2020-12-26_12 01 56](https://user-images.githubusercontent.com/6777029/103159809-36040400-47ce-11eb-868e-eafd4833cc21.png)

## Steps to reproduce the issue
No idea appears randomly.

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Sandriell** [comment]
I am also having this issue using minecolonies-0.13.537-ALPHA-universal as well.

I tried giving the citizen all the different cure items, but he didn't use them and there was no change.

**Comment by MatthiasMann** [comment]
Ahh - one thing I forgot to mention - this doesn't seem to hinder the builder from working in any way.

**Comment by Raycoms** [comment]
Does this happen for a very long time? This is checked around every 5 seconds and potion effects removed

**Comment by MatthiasMann** [comment]
My builder runs around with this active most of the time

**Comment by Sandriell** [comment]
The effect persists for a long time.

**Comment by Sandriell** [comment]
Wanted to add to this that today I observed one of my citizens get actually sick, go to the hospital and get cured, but the smoke particles never went away. I don't know if this is the only way this issue is happening though.

Minecolonies version: 557

**Comment by MatthiasMann** [comment]
For me an update of performat seems to have fixed this.

**Comment by Sandriell** [comment]
Performant fixed this for me too.

**Comment by Raycoms** [comment]
Can people reproduce this without performant?

**Comment by Sandriell** [comment]
Just to clarify, it appears this was a bug with performant and never with minecolonies.

As seen here, https://www.curseforge.com/minecraft/mc-mods/performant/files/3154304
"Fix potion effects particles sometimes not removing on client side"

**Comment by Raycoms** [comment]
ty
