### ISSUE TITLE
Colony Banner Issues

### ISSUE THREAD

**Issue by MiniNinja1810** [ldtteam/minecolonies#6299]
Half of the banner "add-ons" (the shapes you put on them) are purple and black glitch textures in the colony banner editor in the town hall. There's no flower, skull, gradient, brick or mojang symbols.

i am in 1.16

**Comment by ravenbuilder934** [comment]
Please fill out the entire template

**Comment by Raycoms** [comment]
There is most likely a mod adding more, the remaining ones are unlocked on higher townhall levels
