### ISSUE TITLE
Miner hangs on ore of LibVulpes Mod

### ISSUE THREAD

**Issue by RedAlex** [ldtteam/minecolonies#630]
### Minecolonies version

version 0.6.6

### Expected behavior

- XXX

### Actual behaviour

- Miner Citizen block by ore of LibVulpes Mod

### Steps to reproduce the problem

1. Miner building lvl 1
2. at y:54
3. Copper ore 4283:4
4. Miner stop to do anyting and say nothing.

**Comment by Raycoms** [comment]
It might be possible that the mod doesn't implement the effective tool
method.
Can you show us the console log and post the problem on their GitHub?

Am Samstag, 18. Februar 2017 schrieb RedAlex :

**Comment by RedAlex** [comment]
I don't know how to get a debug of the pnj miner to get a log for that.

**Comment by marvin-bitterlich** [comment]
What does PNJ even mean? 😂

**Comment by RedAlex** [comment]
Sorry PNJ are in french for NPC

**Comment by marvin-bitterlich** [comment]
Closing as not enough info
