### ISSUE TITLE
Town hall tooltips are squished

### ISSUE THREAD

**Issue by ravenbuilder934** [ldtteam/minecolonies#6302]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 545
- Structurize Version: 105
- Related Mods and their Versions: none

## Expected behavior
The tooltips for the town hall GUI's tabs would look normal

## Actual behavior

![image](https://user-images.githubusercontent.com/63612548/103176579-83b55680-4838-11eb-9c9c-2ab1f8a37339.png)

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes
Not reproducible on 1.16.4

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
1.15 will have to live with that

**Comment by ravenbuilder934** [comment]
Are we done updating 1.15?

**Comment by Raycoms** [comment]
This is a rendering problem in structurize, but rendering of GUIs got reworked in 1.16, so we're not porting those things fr a while now

**Comment by ravenbuilder934** [comment]
Ah, kk
