### ISSUE TITLE
Colonists not going to bed

### ISSUE THREAD

**Issue by MisterChester77** [ldtteam/minecolonies#6303]
### Prerequisites 

- [Y] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [Y] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [Y] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.542-ALPHA-universal
- Structurize Version: 0.13.105-ALPHA-universal
- Related Mods and their Versions:

## Expected behavior

Citizens sleep in bed
## Actual behavior

At night citizens walk to their houses but hug the hut block instead of going to bed.

![2020-12-27_17 44 48](https://user-images.githubusercontent.com/50875867/103176681-a6149780-486b-11eb-9a50-a80d3f3013fb.png)
![2020-12-27_17 45 59](https://user-images.githubusercontent.com/50875867/103176683-a745c480-486b-11eb-86e3-8083459e92a2.png)

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Are the beds obstructed?

**Comment by MisterChester77** [comment]
No. I recently came back from a holiday and updated the mod to the newest version.

Maybe that's related?

**Comment by Raycoms** [comment]
Can you do a repair on the hut and see if it works afterwards?

**Comment by MisterChester77** [comment]
I did. and it didn't :(

**Comment by MisterChester77** [comment]
Just updated to minecolonies-0.13.545-ALPHA-universal.

Still have the issue.

**Comment by MatthiasMann** [comment]
Also happened after I upgraded to minecolonies-0.13.544-ALPHA-universal (from minecolonies-0.13.543-ALPHA-universal) on 1.16.4:
![2020-12-28_14 01 00](https://user-images.githubusercontent.com/6777029/103216015-470b5d00-4915-11eb-835f-8734515eaa52.png)
 
Edit: I'm very sure that it is commit d9c79fb24dafc9e37dbf6e2160d4ed0c4104ce7b - which also breaks the cow handler (haven't build other animal farms so far so couldn't test).

**Comment by mcsunnishines** [comment]
Same here, 1.16.4 updated today.

**Comment by Raycoms** [comment]
fixed

**Comment by MisterChester77** [comment]
Sweet, Thanks!
