### ISSUE TITLE
Player House Wood 3

### ISSUE THREAD

**Issue by thomasaeddy** [ldtteam/minecolonies#6307]
### Prerequisites 

- [X ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.16.4
- MineColonies Version: 0.13.525-ALPHA (20201102.104115)
- Structurize Version:
- Related Mods and their Versions:
- Ambient Environment: 4.0.0.6
- ApleSkin 1.0.14
- Basic Nether Ores 5.4.0
- Better Advancements 0.1.0.103
- Better Bedrock Generator 0.1.2
- Better Conduit Placement 1.1
- Bookself 9.3.18
- Caelus API 1.16.4-2.1.0.0
- Ceiling Torch v1.8
- Ceramic Bucket 2.5.1-1.16.2+
- Ceramic Shears 1.3.2-1.16.1+
- CHA&5 - Craftable Horse Armor and Saddle 1.16.4-1.4.0
- Clumps 6.0.0.13
- Collective 1.53
- Comforts 1.16.4-4.0.02
- Connect Glass 1.0.6
- Controlling 7.0.0.11
- Cooking for Blockheads 9.2.2
- Corail Tombstone 1.16-6.2.0
- CosmeticArmorReworked 1.16.4-v1
- Crafting Tweeks 12.2.0
- Crash Utilities 3.7
Curio of Undying 1.16.4-5.1.0.0
Curious API 1.16.4-4.0.3.0
Curious Elytra 1.16.3-4.-.-.1
Death Counter 1.2.1
DiceMC tiered Armor 1.16.4-1.0
Ding 1.2.0
Durablity101 0.0.3
Enchantment Discriptions 6.0.2
Extra Armor Mod 1.16.4-1.1.3
Farming for Blockheads 7.2.1
FastLeadDecay v25
Forge 35.1.13
Gislbears Durability Viewer 1.16.4-forge35.0.7-1.9
Glass Harvesters 1.16.3-2.0.0
Glassential 1.1.5
Global Data - & Resouresepacks 1.16.4-1.7.3
Immersive Engineering 1.16.4-4.1.3-129
Inventory Tweeks Renewed 1.16.4-1.0.1
Jei Intergration 6.1.1.11
Just enough Items 7.6.0.62
Just enough resoureces 0.12.0.103
Macaw'sBridges 1.0.4
mgui 3.1.3
Mincolonies 0.12.525-ALPHA
Minecraft 1.16.4
More Overlays Updates 1.18.11-mc1.16.4
Morpheus 4.2.68
Mouse Tweeks 2.13
Nature's Compass 1.16.4-1.8.6
Neat 1.7-24
Netherite Horse Armor Mod 1.5
MetherPortalFix 7.2.1
Oh the Biomes You'll Go 1.1.5
Pack Menu 2.3.0
Placebo 4.3.3
Rapid Leaf Decay 1.0.0
ReAuth 3.9.3
Repurposed Structures 1.16.4-2.3.3
Sever Tab Info 1.3.1
ShetiPhan-Core 3.8.4
Shutup Experimental Settings! 1.0.1
Silent Lib 4.9.0+63
Simple Farming 1.16.4-1.3.5
Simply Light 1.16.1-1.1.1
Storage Drawers 8.2.1
Structurize 0.13.104-ALPHA
Stupid Horse Stand Still 1.16.3-1.0.1
Tetra 3.3.1
Toast Control 4.3.0
Torch Bandolier 1.5.1+11
TorchBowMod 1.4
TrashSlot 12.2.1
U Team Core 3.1.16.190
Useful Backpacks 1.11.6.86
Valhelsia Structures 16.0.5
Vanilla+ Tools version
Variant16x 0.17.4.1_beta
Waila 1.10.11-B78_1.16.2
Wala Harvestablity 1.1.13
WAWLA 7.0.2
Waystones 7.3.1
Wither Skeleton Tweeks 5.2.1
Xearo's Minimap 20.29.1
Yung's Better Caves 1.16.3-1.06
Yung's Better Mineshafts 1.16.3-1.1 

## Expected behavior
 Builder build a Wood3 Player's House (I also tried a bayou3 and got a bayou1)

## Actual behavior
 Builder built a Wood1 Player's House

## Steps to reproduce the issue

 

1. Try to build a Wood Player's House 3
2.  Check Townhall to see what is actually being built
3.  Show that work order is for a Play's House 1 instead of a 3

### Logs

 No crash so no log

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
The player houses are the same as other buildings in the mod - you build level 1, then upgrade to level 2, then upgrade to level 3. Not a bug =)

**Comment by thomasaeddy** [comment]
How do you upgrade?  There is no "player house hut" to click on for an upgrade.  When I try to build a playerhouse wood2 or bayou2 after building a playerhouse wood1 or bayou1 the work order at the townhall says wood1 or bayou1 not 2.  The builder just keeps building the same building.

**Comment by ravenbuilder934** [comment]
To upgrade a decoration, look for the decoration controller-a small, gray rectangle somewhere on the decoration. Right-click one to open a build options menu like the one in huts

**Comment by thomasaeddy** [comment]
OK thanks.  It that in the Wiki?

**Comment by ravenbuilder934** [comment]
Not yet
