### ISSUE TITLE
Players forcibly disconnected

### ISSUE THREAD

**Issue by colingoodman** [ldtteam/minecolonies#6309]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: 0.13.546-ALPHA
- Structurize Version: 0.13.104-ALPHA

Related Mods and their Versions:
- Forge 35.1.15
- _There are about 35 additional mods included, I can post them if desired._

Note: This was also tested on the release version of MineColonies. The same problem occurred. 

## Expected behavior
Players should ideally have no connection troubles on the server. I am unsure what the message in the log does or refers to. More info below.

## Actual behavior

Player randomly gets disconnected from the (forge) server. Log states `[B#608]  [15:44:13.297] [Render thread/INFO] [minecolonies/]: Removed all colony views` shortly before they are disconnected.

The server console simply states that the player has disconnected. 

## Steps to reproduce the issue

1. Player connects to server and plays for some arbitrary period of time.
2. Player's client reports getting behind in ticks from the server.
3. Player client reports "removed all colony views" as shown above and below.
3. Player is disconnected. Server console states they simply disconnected with no additional info.

### Logs

This is all that is provided:
`[B#608]  [15:44:13.297] [Render thread/INFO] [minecolonies/]: Removed all colony views`

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Removed all colony views  gets triggered by getting disconnected and not triggers disconnecting.
