### ISSUE TITLE
Farmer not letting crops grow before harvesting.

### ISSUE THREAD

**Issue by Arystina** [ldtteam/minecolonies#631]
### Minecolonies version

version 0.6.2837

### Expected behavior

- Harvest grown crops.

### Actual behaviour

- Plants seeds of crop then picks planted crop right back up.

### Steps to reproduce the problem

1. Build farm. Hire farmer.
2. Stick scarecrow nearby over water source. Place wanted seed in scarecrow and give same seeds of crop to farmer. 
3. Watch.

I'm not sure why my farmers are doing this, but like with wheat for example, my farmer is stockpiling seeds but hardly any wheat. I changed it to carrots and they planted the carrots, but then immediately dug up the carrot that they just planted.

**Comment by Raycoms** [comment]
Are you using any additional mods?

Am Samstag, 18. Februar 2017 schrieb Arystina :

**Comment by Arystina** [comment]
Some. Extra Utilities, Journeymap, Just Enough Items, Waila, Mr Crayfish's Furniture Mod, and Harvestcraft. Are one of those known for having a conflict? I know it can't be Harvestcraft. I added that mod not too long ago. I had problems with the farmer already before I added it.

**Comment by Raycoms** [comment]
No these ones shouldn't cause any problems

Am Sonntag, 19. Februar 2017 schrieb Arystina :

**Comment by Arystina** [comment]
May be a bug then. I removed everything but minecolonies and forge still my farmer digs up crops before they are grown.

**Comment by marvin-bitterlich** [comment]
Could you make a small video of what happens? Maybe that can help us pinpoint what is happening.

**Comment by Arystina** [comment]
I can try. Internet upload speed is not good. Give me some time.

**Comment by Arystina** [comment]
Got it: https://www.youtube.com/watch?v=lIcITGRn0ro

The farmer does this with wheat and potatoes as well.

**Comment by marvin-bitterlich** [comment]
Closing in favor of #301
