### ISSUE TITLE
Cannot create new colony after deleting 

### ISSUE THREAD

**Issue by Callum-Mason** [ldtteam/minecolonies#6310]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: minecolonies-0.13.547-ALPHA-universal
- Structurize Version: structurize-0.13.104-ALPHA-universal
- Related Mods and their Versions:

## Expected behavior

when i do "/mc colony delete <colony ID>" it will delete the coloy and i can place a new one down afterwads in the same place with out issues.

## Actual behavior

ere i have done "/mc colony delete <colony ID>" and then tried to re place the town hall as i wanted to start again, but it is now saying that there is a colony near by, but when i do "/mc whereami" it says no close colony. when i also do "/mc list" it is blank

![Town Hall](https://i.imgur.com/wQSUaMW.png)

![Command Output](https://i.imgur.com/Z6u97iu.png)

## Steps to reproduce the issue

1. Do /mc colony delete <colony ID>
2. Palce down another town hall

### Logs

- latest.log: https://gist.github.com/Callum-Mason/1aa3076f7f3782e81cc9de87a4b3fa8e#file-lastest-log

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Two questions, a) when did you delete the colony (with the above version?) b) when you hold the buildtool do you see colony borders?

**Comment by Callum-Mason** [comment]
A) Yes
B) No

**Comment by Raycoms** [comment]
Very strange, from the looks of it, the server side data got wiped but client side is left, did you try relogging?

**Comment by Callum-Mason** [comment]
yes

**Comment by Callum-Mason** [comment]
is there something i can do on the server side (as i am the owner)

**Comment by Raycoms** [comment]
So relogging didn't fix it? That is very strange indeed.

**Comment by Raycoms** [comment]
Can you try a client restart too? Sometimes data stays around in the client.

**Comment by Callum-Mason** [comment]
sure, let me try that now

**Comment by Callum-Mason** [comment]
Still nothiing

**Comment by Raycoms** [comment]
Okay, this is strange then, tried a different location in the world too?

**Comment by Raycoms** [comment]
And, do you have the log around from the time when you deleted the colony?

**Comment by Callum-Mason** [comment]
i have tried creating else ware in the world and it works and ill try and find the log files (server files right)

**Comment by Raycoms** [comment]
okay, this means there are some blocks around still. Do a /mc colony claim 1 5 false at the location you want to place it and see if that solves it.

**Comment by Callum-Mason** [comment]
That still didt fix it, also here is the log file - https://gist.github.com/Callum-Mason/255a9228fa5fa96b8a93c2c8477b805c

**Comment by Raycoms** [comment]
strange, deletion ran smoothly.

**Comment by Callum-Mason** [comment]
Anything else i can test or provide you to help more?

does MineColonies save data other than i nthe world folder

**Comment by Raycoms** [comment]
Capability data. There must be achunk arund with colony data in it

**Comment by Callum-Mason** [comment]
Is there anywhere i would beable to check for that?

**Comment by Raycoms** [comment]
flying arund with the build tool mostly

**Comment by Callum-Mason** [comment]
I have flown over the entire land and a few chunks in evey direction and still nothing found.

inside the minecolonies folder is blank - ![Screenshot](https://i.imgur.com/gf1qTGp.png)

**Comment by Raycoms** [comment]
yeah, this folder only holds backup data, the actual data is stored in a capability in world and chunk.

**Comment by Raycoms** [comment]
try the claim command once with 8 instead of 5, and did you alter the minColonyDistance?

**Comment by Raycoms** [comment]
https://buildsystem.ldtteam.com/guestAuth/repository/download/LetSDevTogether_Minecolonies_Branches_Build/63240:id/build/libs/minecolonies-0.13.911-PERSONAL-universal.jar

And can you run this version and give me the log on the client side after opening the townhall GUI?

**Comment by Raycoms** [comment]
./mc colony claim 2 8 false to be exact

**Comment by Callum-Mason** [comment]
Shall i run that command to test before chaning mod version, and also where about would the client log be under?

**Comment by Callum-Mason** [comment]
and no i havent altered the minColonyDistance,

**Comment by Raycoms** [comment]
run that command first. Client log is in your local instance.

**Comment by Callum-Mason** [comment]
would it be latest.log?

**Comment by Raycoms** [comment]
on the client instance, yes

**Comment by Callum-Mason** [comment]
Just opened the town hall with that version of the mod installed and it now says i can now create a colony

 - Log file https://gist.github.com/Callum-Mason/320507eb4fcb6b1ce3797b5ef7ec8962

**Comment by Raycoms** [comment]
oh, I think I got an idea what is causing this then
