### ISSUE TITLE
Dupe bug

### ISSUE THREAD

**Issue by Callum-Mason** [ldtteam/minecolonies#6311]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: minecolonies-0.13.547-ALPHA-universal
- Structurize Version: structurize-0.13.104-ALPHA-universal
- Related Mods and their Versions:

## Expected behavior

When you put an iteam in a rack after you delete your colony, the item doesnt dupe

## Actual behavior

if you have a warehouse and then delete your colony,  but keep your buildings the racks stay, if you then shift right click an item into the racks it will then go into it but when you exit and re-enter you will still have the items in your inventory
and the items are still in the racks

## Steps to reproduce the issue

1. Delete your colony with a warehouse built
2. shift click items from your inventory into the racks of the warehouse
3. exit the rack then reenter and see you ahve created duplicated items
4. profit

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by gattsuru** [comment]
I'm having difficulty replicating this.  By "exit and reenter" you mean leaving the world to the title screen?  Was this on local single player, local multiplayer (aka open to lan), or connecting to a dedicated server?  Do you have any mod like InvTweaks or MouseTweaks running?

**Comment by Callum-Mason** [comment]
dedicated server, and exit the rack then reenter

**Comment by Raycoms** [comment]
I can't reproduce this, can you make a video or so where you show this?

**Comment by ravenbuilder934** [comment]
@Callum-Mason

**Comment by Callum-Mason** [comment]
Hi Unfortianly, i haven been about to recreate it again, sorry.
