### ISSUE TITLE
LootTable error, no loot in dungeon/village/mineshaft chests

### ISSUE THREAD

**Issue by Ryutso** [ldtteam/minecolonies#6313]
[latest.log](https://github.com/ldtteam/minecolonies/files/5752773/latest.log)

### Prerequisites
- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: 0.13.437-RELEASE
- Structurize Version: 0.13.96-ALPHA

## Problem description
Starting up a server throws an error about the LootTable and there's no loot in chests in dungeons or towns or mineshafts

### Notes or related things
There were several mods listed in the readout and I asked on the Forge forums for which mod caused this and it was said that it looked like a Minecolonies issue.

https://forums.minecraftforge.net/topic/95728-1164-no-loot-in-chests-cant-tell-which-mod-it-is/

server startup log is attached

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by gattsuru** [comment]
Update.  The current alpha for 1.16 is [547](https://www.curseforge.com/minecraft/mc-mods/minecolonies/files/all).  You will need to update Structurize's alpha as well.

**Comment by Ryutso** [comment]
> Update. The current alpha for 1.16 is [547](https://www.curseforge.com/minecraft/mc-mods/minecolonies/files/all). You will need to update Structurize's alpha as well.

Okay will do. Anyway you know of to generate loot for the chests already opened?

**Comment by WenXin20** [comment]
I am also seeing this error on line 1915 with Minecolonies v0.13.544-alpha. When I removed Minecolonies, this error stopped occurring.
https://gist.github.com/WenXin20/70496dd85a7c9d6064a3c75a08af2e40#file-minecolonies_latest-log-L1915

**Comment by Raycoms** [comment]
Very strange, my guess is that forge broke sth, this used to work fine for ages

**Comment by Raycoms** [comment]
could you try the newest forge?

**Comment by Raycoms** [comment]
Tested with newest forge version myself, doesn't happen. Either you're on a broken forge version or some other mod adds mixins where it shouldn't which breaks it. But I'm 100% sure it's not us.
