### ISSUE TITLE
Leaves decay

### ISSUE THREAD

**Issue by cinnamennen** [ldtteam/minecolonies#6314]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: 13.547
- Structurize Version: 13.104
- Related Mods and their Versions: n/a

## Expected behavior

dark oak builds correctly

## Actual behavior

when building the dark oak tavern, leaves decay

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
#5006

**Comment by ravenbuilder934** [comment]
Again why is this #5006? Shouldn't the builder apply a "nondecaying" state or sth to placed leaves?

**Comment by MatthiasMann** [comment]
The builder is placing the leaves as they were scanned - so if you placed 'normal' leaves they will be normal leaves once placed by the builder.
I haven't tried it - but I assume that in creative you need to go some extra steps to get permanent leaves as the ones you get from the inventory are the normal once :(
But placing non permanent leaves is problematic anyway as the order in which they are placed likely causes a lot of them to decay before the logs are placed (esp with mods like fast leave decay).
So I think it would make the life of schematic designers much easier if the builder would fix all leaves to be permanent.
