### ISSUE TITLE
Dark Oak Tree Plot is dug up by the forester

### ISSUE THREAD

**Issue by cinnamennen** [ldtteam/minecolonies#6315]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: 13.547
- Structurize Version: 13.104
- Related Mods and their Versions: n/a

## Expected behavior

dark oak farm doesn't get torn up

## Actual behavior

when using the dark oak tree plot, it gets torn up
![2020-12-30_12 58 24](https://user-images.githubusercontent.com/2693113/103372111-2a9b2c00-4a9f-11eb-8e81-f1615d304fd0.png)

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
#5006

**Comment by ravenbuilder934** [comment]
Why is this #5006? The tree got chopped down by the forester even though there's cobble underneath it and it's in the building schematic.

**Comment by Raycoms** [comment]
Ah, I thought it was the schematic overlap, but it's the same bug then as the sleepinng bug which was fixed
