### ISSUE TITLE
Postboxe/stashes place tape under them

### ISSUE THREAD

**Issue by cinnamennen** [ldtteam/minecolonies#6323]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: 13.547
- Structurize Version: 13.104
- Related Mods and their Versions: n/a

## Expected behavior

no tape

## Actual behavior

If you put a postbox/stash in the air, it puts tape under it

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
You're not placing it with the build tool, right?

**Comment by cinnamennen** [comment]
Correct

Caleb Mennen
