### ISSUE TITLE
Blue lvl 5 previews don't match the rotation of the base building

### ISSUE THREAD

**Issue by cinnamennen** [ldtteam/minecolonies#6324]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: 13.547
- Structurize Version: 13.104
- Related Mods and their Versions: n/a

## Expected behavior

preview shows correctly

## Actual behavior
Place a dark oak citizen down.
Use the builders wand to start to place another
set the level of the new build to 5
click rotate and both previews rotate

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MatthiasMann** [comment]
The issue is that nearby existing builds (previewed as level 5 with blue outline) will copy the rotation / mirror setting of the building your are currently trying to place if they are the same type of building (eg both delivery huts or citizen huts etc).
