### ISSUE TITLE
Delivery person error

### ISSUE THREAD

**Issue by mcsunnishines** [ldtteam/minecolonies#6326]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.3
- MineColonies Version: 0.13.547-ALPHA
- Structurize Version: 0.13.104-ALPHA
- Related Mods and their Versions: Many mods but all are updated and have been playing with this specific pack for awhile. 

## Expected behavior

Delivery person delivers items
## Actual behavior

Delivery person gets error bubble while delivering items

## Steps to reproduce the issue

1.  Play world like normal
2. 
3. 

### Logs

- latest.log:  https://gist.github.com/mcsunnishines/fc6ecf2ad37b2dcf250d2b19f5954650
- crashlog: 

### Notes

Asked in Discord and was asked to post here
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
duplicate error
