### ISSUE TITLE
Build queues all changed to downgrading by 1 tier instead of upgrading

### ISSUE THREAD

**Issue by rtbittaker** [ldtteam/minecolonies#6327]
### Prerequisites 

- [ X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 16.4
- MineColonies Version: 13.531-Alpha
- Structurize Version: .13.104-Alpha

## Problem description
I had roughly a dozen builds queued upon logging off 10 hours prior on a server. When I relogged on, all the builds I had queued began to de-construct by 1 level. So a Tier 2 tower in the process of being upgraded to Tier 3 was then downgraded to a Tier 1. In addition, I noticed at least 2 hut blocks that were bugged and stated the structure around them did not exist. This was a Tier 1 Library and an unbuilt house hut block. The server did experience a crash a little while before I got on, but many hours prior to my last log in. 

### Notes or related things

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Can you please try to reproduce this on the latest alpha? 531 is a bit out of date.

**Comment by rtbittaker** [comment]
I'll see what I can do. It's on a Valhelsia Server that I don't run. I also have no idea how to reproduce it. Seemingly happened out of the blue, I was the only one on the Server affected.

**Comment by Raycoms** [comment]
I'll close to. But I'll explain you what happened. Minecraft world data is sometimes unstable, if a server is turned on for a long time and crashes or shuts down badly world data may get lost, that includes colony data. We have a backup system such that your colony data since the last regular shutdown is restored. This is what happened in this case.
