### ISSUE TITLE
AI Issue

### ISSUE THREAD

**Issue by cinnamennen** [ldtteam/minecolonies#6328]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: 13.547
- Structurize Version: 13.104
- Related Mods and their Versions: n/a

## Problem description

Deliveryman seems to not like the stash
https://paste.ee/p/maCNK

### Notes or related things

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Duplicate issue
