### ISSUE TITLE
farmer hangs on harvestcraft seeds as a tool

### ISSUE THREAD

**Issue by chris5022** [ldtteam/minecolonies#633]
### Minecolonies version

version X.X.XXXX or curse 0.6.2837

### Expected behavior

- XXX

### Actual behaviour

[Server] Server thread/INFO [minecolonies]: ForgeHook not in sync with EfficientTool for Block{minecraft:tallgrass} and 13xitem.seeds@0
[Server] Server thread/INFO [minecolonies]: ForgeHook not in sync with EfficientTool for Block{minecraft:red_flower} and 16xitem.seeds@0
doing that over and over
### Steps to reproduce the problem

1. XYZ
2. ZYX
3. ...
4. Profit

**Comment by marvin-bitterlich** [comment]
need a modlist for that

**Comment by chris5022** [comment]
crayfish furniture mod
chameleon
fairylights
malsiscore
malsisdoors
Netherportalfix
Pam's Harvestcraft
RealBench
Storagedrawers
Veinminer
placeable items

**Comment by marvin-bitterlich** [comment]
Hmmm, seems like one of these mods is modifying the seeds to change things there.

**Comment by marchermans** [comment]
Probably Pams Harvestcraft

**Comment by chris5022** [comment]
is it a game breaking conflict? wondering if i need to remove one?

**Comment by marvin-bitterlich** [comment]
@chris5022 naah this just means that that mod has things we have to do custom code to get it to work. And because many mods do this we print this log to get players to tell us when a mod makes this.

**Comment by gd71** [comment]
If it can help
I'm using minecolonies latest and pam's harvestcraft for two months on 1.10.2 and I never seen these logs

**Comment by chris5022** [comment]
im on 1.11.2 using the beta expected to see some issues. just thought i would post what i had seen

**Comment by marvin-bitterlich** [comment]
@OrionDevelopment can we improve our system there?

**Comment by Raycoms** [comment]
Should be fixed.
