### ISSUE TITLE
Builder not placing any blocks. Appears to be placing nothing.

### ISSUE THREAD

**Issue by Skidd17** [ldtteam/minecolonies#6331]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: 0.13.437
- Structurize Version: 0.13.96
- Related Mods and their Versions:

## Expected behavior

Builder holds whatever block they need in hand and finishes building
## Actual behavior

Builder will appear to be placing/building blocks (has all materials and needs filled). But instead is holding nothing and while it animates them placing stuff they never do. 

Have tried 'sitting it out' for multiple days, tried firing and re-hiring, tried firing and hiring someone else. Cancelled build order ect. The building in question is a stone mine, they were able to complete almost all of it then literally on the last couple blocks (which I've tried filling in myself but to no avail) they have started this bug. I've also tried moving the last few items they need into their chest, their inventory and the builders chest. I've tried emptying inventory and giving it back to them when they need it. I have had them build another building and come back to this order, which they were able to do just fine, then when they came back to this its the same issue. Last item they need to place are wooden ladders.

![image](https://user-images.githubusercontent.com/76845740/103442603-82a28000-4ca3-11eb-81b4-7976b18cc1d9.png)
![image](https://user-images.githubusercontent.com/76845740/103442648-dd3bdc00-4ca3-11eb-94e2-2d3a1fec2b49.png)

## Steps to reproduce the issue

1.  I've tested it trying to build a mine in another world (creative mode) and worked fine. So not sure how to reproduce issue.
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by gattsuru** [comment]
Can you update to the most recent version?  1.16.4 is on [547](https://www.curseforge.com/minecraft/mc-mods/minecolonies/files/3152142) -- you will need to update Structurize as well.

**Comment by Skidd17** [comment]
> 
> 
> Can you update to the most recent version? 1.16.4 is on [547](https://www.curseforge.com/minecraft/mc-mods/minecolonies/files/3152142) -- you will need to update Structurize as well.

My bad, didn't realise I was behind. Updated and issue is still persistent.

**Comment by ravenbuilder934** [comment]
Okay, can you try canceling the build order, taking everything away from them (including things in their hut), running /mc colony requestsystem-reset (your colony ID here), then restarting the build order?

**Comment by Skidd17** [comment]
> 
> 
> Okay, can you try canceling the build order, taking everything away from them (including things in their hut), running /mc colony requestsystem-reset (your colony ID here), then restarting the build order?

Ok just tried this and no change unfortunately. :c

**Comment by ravenbuilder934** [comment]
Weird. What if you cancel the current mine and try to build it again in a different location (same builder)?

**Comment by Skidd17** [comment]
> 
> 
> Weird. What if you cancel the current mine and try to build it again in a different location (same builder)?

I'll give it a shot.

**Comment by gattsuru** [comment]
If you're using Quark, does the builder have specifically Oak Ladders?  Quark's other variant ladders may cause odd results.

**Comment by Skidd17** [comment]
> 
> 
> If you're using Quark, does the builder have specifically Oak Ladders? Quark's other variant ladders may cause odd results.

Not using Quark or any other mod that adds/affects ladders. The builder does have specifically Oak ladders anyways since that was his request.

**Comment by ravenbuilder934** [comment]
Do you have any invisible light sources in the build area? That can mess the builder up

**Comment by Skidd17** [comment]
![image](https://user-images.githubusercontent.com/76845740/103443334-f5165e80-4ca9-11eb-8b44-e71c7712b2d1.png)

This is the *nearly* completed mine he did. (I have him now building another mine as a test).

I wouldn't be sure what to look for with invisible light sources 🤔

**Comment by Skidd17** [comment]
He was able to build the second mine (not too far away) without any issues so it seems this is an isolated weird problem with this location. 

![image](https://user-images.githubusercontent.com/76845740/103443378-7e2d9580-4caa-11eb-861b-3ddf8ba7e1b8.png)

Would it be worth digging up all the stuff he's built in this mine and seeing if he can rebuild it from scratch? I have a back up copy of the world just in case.

**Comment by ravenbuilder934** [comment]
> Would it be worth digging up all the stuff he's built in this mine and seeing if he can rebuild it from scratch? I have a back up copy of the world just in case.

Sure, might work

**Comment by Skidd17** [comment]
![image](https://user-images.githubusercontent.com/76845740/103443523-dfa23400-4cab-11eb-8037-e6136bda1363.png)

Empited all the previous build out and put the mine in the same spot. He got stuck again. This time it was before he began putting torches down. This must just be cursed land 🙃

**Comment by ravenbuilder934** [comment]
Quite cursed lol
Can you check if there are any monster spawners in the build area or near it?

**Comment by Skidd17** [comment]
> 
> 
> Quite cursed lol
> Can you check if there are any monster spawners in the build area or near it?

I couldn't find any that nearby but went searching deeper underneath anyways and found one a decent amount underground. Destroyed it, same issue.

**Comment by ravenbuilder934** [comment]
Hmm, can you send your modlist?

**Comment by Skidd17** [comment]
> 
> 
> Hmm, can you send your modlist?

-Xaeros Minimap Mod (1.16.4)
-Mr Crayfishes furniture mod (7.0.0-pre19)
-obfuscate (0.5.1)
-Serene Seasons (40.0.0.83)
-Extended Lights (3.3) (Haven't actually used anything in that mod yet)
-Macaw's Windows (1.0.2)
-ForgeEndertech (7.0.8.0 build0028)
-Advanced Chimneys (6.0.4.1 build 0029)
-Simple Farming (1.3.5)
-Jei (7.6.0.62)
-MineColonies (Latest ALPHA (0.13.547)
-Structurize (Latest ALPHA 0.13.104)

**Comment by ravenbuilder934** [comment]
I don't see anything there that could cause an issue
Can you try building something else on the cursed land?

**Comment by Skidd17** [comment]
> 
> 
> I don't see anything there that could cause an issue
> Can you try building something else on the cursed land?

Alrighty, going to try build a stone house (citizen hut)

**Comment by Skidd17** [comment]
> 
> 
> I don't see anything there that could cause an issue
> Can you try building something else on the cursed land?

Got right to the end of it and them bugged out again. Issue seems to be in regards to placing torches in this area.

Builder is just waiving their hands in the air pretending to build and has the audacity to say "It's your gold" smh

**Comment by Skidd17** [comment]
> 
> 
> > I don't see anything there that could cause an issue
> > Can you try building something else on the cursed land?
> 
> Got right to the end of it and them bugged out again. Issue seems to be in regards to placing torches in this area.
> 
> Builder is just waiving their hands in the air pretending to build and has the audacity to say "It's your gold" smh

Quick little follow up, they've placed torches but refuse to officially declare the building done. No fireworks, notif, barrier removal ect.

**Comment by Raycoms** [comment]
It takes a while f cleaning up the space and finishing detection if everything is in place

**Comment by Skidd17** [comment]
It was like that before but I waited about 10ish in game days and nothing changed. Anyway I guess its just a mine in that area is just a no-go. Still unsure why but sometimes it be like that. TY for speedy replies.

- Cheers
