### ISSUE TITLE
[1.16.4] 0.13.437 Release - University - Can't research Know the End? despite having appropriate requirements

### ISSUE THREAD

**Issue by kingofrunes** [ldtteam/minecolonies#6337]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: 0.13.437
- Structurize Version: 0.13.96
- Related Mods and their Versions: N/A

## Expected behavior

When I have at least a Level 3 University and at least a Level 3 Bakery I should have the requirements to research "Know The End?"

## Actual behavior

It says I am missing requirements for "Know The End?" research despite having a Level 5 Bakery, Level 4 University, and a Level 5 Baker. I have the 64 Chorus Fruit in my inventory as well.

![javaw_2021-01-02_10-47-17](https://user-images.githubusercontent.com/1063298/103460900-26158400-4ce8-11eb-9ace-cafe1e4ab1d7.png)
![javaw_2021-01-02_10-45-35](https://user-images.githubusercontent.com/1063298/103460902-27df4780-4ce8-11eb-9b10-12a31fe9300d.png)
![javaw_2021-01-02_10-45-58](https://user-images.githubusercontent.com/1063298/103460905-29107480-4ce8-11eb-9508-cf9ce5d405df.png)

## Steps to reproduce the issue

1.  Get a Level 3 University and Level 3 Bakery
2.  Research "Hot!", "The Flintstones" to gain access to "Know the End?"
3.  Says Missing Requirements for "Know the End?"

### Logs

None applicable for this situation

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
> MineColonies doesn't use the traditional classifications (alpha, beta, release) as the entire mod can be considered in a beta state just based on the number of features still planned. However, Curseforge limits the number of releases and betas we can push out, and due to the devs' speed, the latest version will most often be an alpha. One classification is as stable as the others, so always get the latest version of MineColonies, regardless of its classification.

> Because Curseforge hides alphas in the sidebar, you need to go to the Files tab and then View All to see them. Here's a quick link: https://www.curseforge.com/minecraft/mc-mods/minecolonies/files/all

^ Please use the latest alpha 😄

**Comment by ravenbuilder934** [comment]
Someone reproduced this on the latest alpha, so this issue can be reopened.
