### ISSUE TITLE
Colonists disappeared, blocks can't be interacted with and can't load a backup 

### ISSUE THREAD

**Issue by DarthPepo** [ldtteam/minecolonies#6339]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: minecolonies-0.13.547-ALPHA-universal
- Structurize Version: structurize-0.13.104-ALPHA-universal
- Related Mods and their Versions: none

## Expected behavior
Being able to restore my world by loading a backup, whether i do it ingame using commands or manually from the minecolonies folder

## Actual behavior
Colonist are all missing, can't interact with any of the building blocks and trying to do what other threats with similar issues have done doesn't work, loading a backup ingame gives a succesfully loaded backup message but doesn't have any effect, doing it from the minecolonies folder doesn't have any effect either, i might be doing that las one wrong, i copy the .dat file from one of the .rars and replace the one already in the folder, tell me if i have to do it in another way, and when trying to use the hall building it says there is already a colony nearby. Using some commands like delete it says ''colony with ID 1 could not be found in this dimension!'' even tho, the hall building clearly detects there is a colony and it doesn't let me access it

## Steps to reproduce the issue

I was trying to restore my Nether dimension, so i deleted the DIM-1 folder from the minecraft world, but, before doing that i made a backup of the whole world just i case, when i opened the world without the DIM-1 folder all the problems i mention appeared, but removing and replacing that world with the backup i had just make was of no use either.

1. Make a backup of the world
2. Delete the DIM-1 from the world in the saves folder
3. Open the game
4. Replace the world in the saves folder with the backup previously made 
5. Open the game again to find out it's still broken

### Logs

 

- latest.log:  https://gist.github.com/DarthPepo/3798e57062de05ba570df89895df370b
- crashlog: 

### Notes

This is my first issue here, my apologies if i've done something wrong 

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Was your colony in Dim-1 or just normally in the overworld?

**Comment by DarthPepo** [comment]
> Was your colony in Dim-1 or just normally in the overworld?

It was in the overworld and in a vanilla biome

**Comment by Raycoms** [comment]
Hi there, sorry for the delay, I moved and couldn't follow up. Do you still have the world and problem with this?

**Comment by DarthPepo** [comment]
yep, i kept the backup just in case, any new suggestions?

**Comment by Raycoms** [comment]
can you send us the world?

**Comment by DarthPepo** [comment]
world.zip
<https://drive.google.com/file/d/1aE9oxMkYXH91e5-QJ0bqCNuEmiy0gnGY/view?usp=drive_web>
yep, here it is

**Comment by DarthPepo** [comment]
i didn't even got a proper response to mi problem...

**Comment by Raycoms** [comment]
It was closed via a pull-request, this means the issue was fixed in the code
