### ISSUE TITLE
Miner stopped working

### ISSUE THREAD

**Issue by Liguma** [ldtteam/minecolonies#634]
Minecolonies Testserver
### Expected behavior

should mine

### Actual behaviour

stopped worling

### Steps to reproduce the problem

Have upgraded building to lvl 3 after he stopped
Then he dug 2-4 dirt and stopped again

G
Gunvaldfar

**Comment by marvin-bitterlich** [comment]
any news on this? Have you tried giving him the regular miner stuff? We currently have problems with citizens not requesting stuff

**Comment by Liguma** [comment]
He had everything - recalled/fired/rehired - fiered and hired another citizen. Broke ladders and repaird building - upgraded building.

PS.: there are limestone (chisel) and marbel (chisel)  in the mine maybe the same issue u have with railcraft-rail - tried to remove theme but nothing.

**Comment by marchermans** [comment]
As per request I started merging Issues that are related to things I found while going through the source code. One of these is the request system. Closing this in favor of #638
