### ISSUE TITLE
Gates remain open if they were open when the colony unloaded

### ISSUE THREAD

**Issue by kmarple1** [ldtteam/minecolonies#6340]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: minecolonies-0.13.547-ALPHA-universal
- Structurize Version: structurize-0.13.104-ALPHA-universal
- Related Mods and their Versions:

## Expected behavior
Gates should always be closed after a colonist goes through them, unless left open by a player. Note: they do get ignored if left open by a player, I'm assuming this is intentional.

## Actual behavior

If a gate is opened by a colonist when disconnecting or otherwise unloading the colony, it will be left open and ignored by the colonist after the colony is reloaded.

## Steps to reproduce the issue

1. Wait for a colonist to open a gate to the pen in one of the huts.
2. Disconnect before the colonist closes the gate. May take a few tries to get the timing right.
3. When you reconnect, the colonist will leave the gate open.

### Logs

N/A

### Notes
Doors may also be affected, but the real problem is the gates to the pens in the animal huts, as this allows the animals to escape. I don't know much about how things work internally, but this might be fixable by checking the status of gates and doors when the buildings load, at least for the animal huts?

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
We've discussed this internally. It's very complex to solve. So we've decided on "It's not a bug, it's a feature".
Citizens are not machines, they're not perfect, occasionally they leave doors and pens open. It gives the players something to do here and there as well. 
@ravenbuilder934 could add to the wiki to the herders that this could happen occasionally and the player has to solve it.
