### ISSUE TITLE
Fulfilling requests at the builder's hut doesn't clear them from the builder

### ISSUE THREAD

**Issue by kmarple1** [ldtteam/minecolonies#6342]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: minecolonies-0.13.547-ALPHA-universal
- Structurize Version: structurize-0.13.104-ALPHA-universal
- Related Mods and their Versions:

## Expected behavior

Adding requested items to the Builder's Hut inventory or clicking the fulfill arrow next to them on the Required Resources page should also remove the request from the Builder.

## Actual behavior

The material will be fulfilled in the hut GUI and any associated Resource Scrolls, but the builder will still have the request open. They may also pause construction to wait for the request to be fulfilled or manually cancelled, even though the items are in their hut's inventory.

## Steps to reproduce the issue

1. Wait for the builder to request an item such that it shows up in the "Requests" page of their personal GUI.
2. Add the requested items to their hut's inventory, either manually or through the hut's GUI.
3. The builder will still have the request open.

### Logs

N/A

### Notes

N/A

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by PasixTheValkyrie** [comment]
I seem to only have this issue once there is a warehouse available. If you have one, try demolishing it and then seeing what the builder's up to. Chances are it might fix itself. Obviously not a solution, but could proof some insight for the devs.

**Comment by Raycoms** [comment]
I can't reproduce this, does this happen all the time for you?

**Comment by PasixTheValkyrie** [comment]
For me it doesn't. It usually happens with resources that could realistically be produced by the colony itself, such as wooden planks coming from a lumberjack. Continually denying the request or (obviously) giving the resources yourself seems to reset anything else that is queued, if the resources are available.

**Comment by kmarple1** [comment]
It's definitely inconsistent. Sometimes the requests will clear properly, sometimes they won't. As JNoppers said, it mainly seems related to things that the colony can produce or delivery from the warehouse.

**Comment by Sandriell** [comment]
From my observations this seems to occur when the fulfilled item goes into a rack (maybe storage blocks like chests too) instead of into the hut block itself.
