### ISSUE TITLE
Unable to place buildings on a server due to resource pack(s)

### ISSUE THREAD

**Issue by NekoChan545** [ldtteam/minecolonies#6345]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.548-ALPHA
- Structurize Version: 0.13.105-ALPHA
- Related Mods and their Versions: Pillagers to Pirates v1.4
- https://www.dropbox.com/s/0fghri13kz1s1i6/PillagerToPirate%2Bv1.4.zip?dl=0

## Expected behavior

Awesome resource pack, alongside minecolonies. Buildings would be placed, built, and colonies would be started, with awesome looking blocks, items, etc.

## Actual behavior

When first starting the mod, ABLE to place supply camp. When trying to place town hall, or other buildings(ex. builders hut), the block won't place.
When trying to place a building, a prompt appears "we suggest using the build tool to place this schematic...." click, "Place anyway" block won't place.
When trying to use the build tool to place town hall/other buildings, set schematic, click the green check mark, the block won't place.
A sound plays but nothing is placed.

## Steps to reproduce the issue

For server embedded resource packs:
1. Be on a server(don't be on the same computer as the server, placing will work. Must be an external computer connecting to the server computer)
2. Make sure the server has a resource pack in the server.properties file w/ SHA1 hash
3. Try to place town hall block or any other buildings with or without build tool

For client-side resource packs:
1. Be on a server(can be on the same computer as the server, placing will NOT work.)
2. Make sure resource pack(s) are NOT in server.properties file
3. Have a resource pack downloaded and place it in YOUR resource packs file in .minecraft file
4. Switch resource pack(through Minecraft resource packs selector) **MIDGAME**
5. Try to place town hall block or any other buildings with or without build tool

### Logs

- latest.log: 
- crashlog: N/A no crash log

### Notes

Seems to be a resource pack compatibility issue. Works in singleplayer worlds, even when switching resource packs midgame. The problem seems to only appear in servers.
Switching resource packs in the game menu does not affect gameplay, it's only when switching in the server, midgame.
This happens with any resource pack, not only the one listed. We've tested other resource packs(from vanilla tweaks, curse forge, etc.), and the same problem occurs.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Mekle001** [comment]
I can't reproduce this on 1.16.4, it will take me a bit to try 1.15

**Comment by Raycoms** [comment]
We can't reproduce this, can you reproduce this in the latest yet?

**Comment by NekoChan545** [comment]
We can try with the latest 1.15 alpha release, and we'll let you know how it goes in another comment on this post.

**Comment by CobbieFox** [comment]
https://www.youtube.com/watch?v=FcOTVFLze_4&feature=youtu.be
Here is us reproducing it in 1.15.2
The Forge version is 1.15.2-31.2.47
We try both the original alpha release and the most recent

**Comment by Mekle001** [comment]
Ok, I'll set up again to try to repro this. I must have missed something, or there is a factor we're not aware of.

**Comment by ravenbuilder934** [comment]
Same issue on 1.16? 1.15 isn't being updated any more

**Comment by NekoChan545** [comment]
I just checked it out in 1.16, I don't think the same issue is on 1.16

**Comment by ravenbuilder934** [comment]
great
