### ISSUE TITLE
[Suggestion] Voice-lines

### ISSUE THREAD

**Issue by PasixTheValkyrie** [ldtteam/minecolonies#6352]
- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

- Minecraft Version: 1.16.4
- MineColonies Version: 0.13.557-ALPHA
- Structurize Version: 0.13.104-ALPHA

## Problem description
The NPCs in this mod have only a few voicelines and generally spam these a lot. At first it's not that annoying, but when you've been playing for a while, especially with a lot of villagers, it becomes a true nuisance.

In my case, it also seems that female characters get prioritized when using voicelines. I believe there's two or three voicelines for male and two or three for female characters, but I rarely hear the male ones, even though I have a somewhat male dominated colony.

I would like to suggest a few alternatives

- Being able to mute the voicelines specifically
- Adding more voicelines, or have the voicelines actually fit the worker ("I need to build this again?") seems to get spammed the most, for me.
- Make voiceline priority more gender equal
- Allow players to add their own custom voicelines, if prefered.

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
We already added more voice lines in https://www.curseforge.com/minecraft/mc-addons/minecolonies-immersed, the rest of the suggestions go in https://github.com/ldtteam/minecolonies-features/issues

**Comment by PasixTheValkyrie** [comment]
Is there a reason this isn't integrated with the main mod?

**Comment by ravenbuilder934** [comment]
To reduce the file size of the mod itself
