### ISSUE TITLE
Fisher destroys his fishing rods instead of fishing

### ISSUE THREAD

**Issue by FlashZange** [ldtteam/minecolonies#6354]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] it was the latest version until two days ago 
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: minecolonies-0.13.547-ALPHA-universal
- Structurize Version: structurize-0.13.104-ALPHA-universal
- Related Mods and their Versions: forge 35.1.10

## Expected behavior

The fisher doing his job even after his first day at work

## Actual behavior

When I hire a fisher he is working fine. After sleeping for the first night, he goes to his hut, pulls out his fishing rod, throws it in the water close to the edge and pulls it out immediately. He continues to do so until his fishing rod is broken. Hire and fire or pause and restart did not help.
I noticed this after updating from minecolonies-0.13.480-BETA-universal and structurize-0.13.100-RELEASE-universal. But after checking, he does the same there as well.
No other mods installed.

## Steps to reproduce the issue

1. Create a new world (I used worldtype overworld because that makes it easy)
2. Build a town hall and start your colony, build a fisher's hut and a tavern (I did everything in creative)
3. Give the fisher a fishing rod, give everyone food
4. Wait for the night, go to sleep
5. Watch your fisher go to work and fail miserably
6. Profit?

### Logs

- latest.log: https://gist.github.com/FlashZange/1ff44f1d200bd963fd82c77a9e945984
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
fixed

**Comment by Dife2K** [comment]
Hello, I had this issue and I updated the mod yesterday to alpha 587 noticing this post. It was all working fine but today I found out that my fisher was still a lot inaccurate about throwing his hook in the water.

That's what I saw:

1. Whenever a fisher is assigned with a fishing rod to his job, it works fine for the first day, he throws the hook into the water 3-4 blocks away from the structure.
2. After he goes to bed when he returns to the working place, he starts throwing the hook on the floor, then he goes near the water after few tries and starts casting the hook on the first water block, continuously until he breaks the rod. If I give him another fishing rod he keeps throwing in the same spot.
3. If you refresh the chunk like leaving the server and rejoining it restarts the behavior from step one (1.)

I am using Asian style schematics.

**Comment by Talyda** [comment]
While I haven't actually taken as much notice of the "why" as Dife2K has - I can definitely confirm after watching my fisher last night that they are burning through rods quite quickly, and without really catching much at all (also on .587)

**Comment by Talyda** [comment]
As a test, gave fisher new rod at start of day, by the end of the day they had the rod down to 35/64 durability and caught 11 items (I noticed after several of the catches they threw in "empty" casts for another 4-6 durability loss each time - but they didn't do it every time) Then they went to bed. Next day empty casts until the rod was down to 9/64 durability, Then 2 fish, then empty casts til the rod broke

**Comment by Raycoms** [comment]
Any other fishing mod installed?

**Comment by Dife2K** [comment]
The only one that I have is Aquaculture 2, I don't believe it changes fishing mechanics tho.

**Comment by Talyda** [comment]
I realise you have the PR in for a fix, but answering anyway - no fishing mod that I can see (am using the official modpack)
