### ISSUE TITLE
抱歉，我的英语水平不高，我遇到了一些问题。

### ISSUE THREAD

**Issue by wkurumi** [ldtteam/minecolonies#6355]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.16.4
- MineColonies Version:minecolonies-0.13.557-ALPHA-universal
- Structurize Version:structurize-0.13.104-ALPHA-universal
- Related Mods and their Versions:

## Actual behavior

医院在forge服务器中会造成殖民地卡顿，玩家一进入放有医院的殖民地时就非常卡。

## Steps to reproduce the issue

1. 创建殖民地
2. 放下医院方块
3. 开始卡顿，移除医院，恢复正常。

### Logs

- latest.log: 
- crashlog: 

### Notes

我是来自中国的Minecraft玩家，非常喜欢您的殖民地模组，并将其放在forge服务器中与朋友一起游玩！
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Sorry, none of our team members speaks your language. Please attempt to make an english report.

**Comment by ravenbuilder934** [comment]
From google translate, I think they're saying that the hospital block is causing extreme lag

**Comment by wkurumi** [comment]
Yes,the hospital block is causing extreme lag!Only in the confines of the colony&nbsp;cause extreme lag.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "ravenbuilder934"<notifications@github.com&gt;; 
发送时间: 2021年1月5日(星期二) 晚上10:27
收件人: "ldtteam/minecolonies"<minecolonies@noreply.github.com&gt;; 
抄送: "随便嘛"<1501089968@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ldtteam/minecolonies] 抱歉，我的英语水平不高，我遇到了一些问题。 (#6355)





 
From google translate, I think they're saying that the hospital block is causing extreme lag

**Comment by ravenbuilder934** [comment]
https://github.com/ldtteam/minecolonies/issues/5995 then

**Comment by wkurumi** [comment]
I am currently using 3900X, can you recommend which CPU I should use?




---原始邮件---
发件人: "Raycoms"<notifications@github.com&gt;
发送时间: 2021年1月5日(周二) 晚上10:19
收件人: "ldtteam/minecolonies"<minecolonies@noreply.github.com&gt;;
抄送: "wkurumi"<1501089968@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [ldtteam/minecolonies] 抱歉，我的英语水平不高，我遇到了一些问题。 (#6355)




 
Sorry, none of our team members speaks your language. Please attempt to make an english report.
