### ISSUE TITLE
"My AI has run into an issue, please locate latest log and send it to MC authors with this message"

### ISSUE THREAD

**Issue by Hirschney** [ldtteam/minecolonies#6356]
### Prerequisites 

- [ x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.3
- MineColonies Version:  0.13.547-Alpha
- Structurize Version: 0.13.104-alpha
- Related Mods and their Versions:

## Expected behavior
  Just following orders here.. it said to report it

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log:  https://gist.github.com/Hirschney/370de752f2952c350b4e1a59ccd805a5
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Hirschney** [comment]
![image](https://user-images.githubusercontent.com/42725539/103674132-64ab7880-4f4c-11eb-8d02-da1c6db7fd4c.png)

**Comment by ravenbuilder934** [comment]
Can you please update and check if it's fixed?

**Comment by Hirschney** [comment]
let me see if my pack updated recently.  Unfortunately, I don't know how to update an individual mod, and it's with a server with other people.

**Comment by ravenbuilder934** [comment]
Download [the file](https://www.curseforge.com/minecraft/mc-mods/minecolonies/files/3157803) from Curseforge, locate the Mods folder, remove the old file, and drop the new file in. The server needs to be off when you do this, and everyone that plays on it also needs to update.

**Comment by Hirschney** [comment]
it has not updated, but the worker does not seem to have the issue anymore?  I don't know.  It said report it so I did. I guess if you do not need the info from the latest log you can close this :-D

**Comment by ravenbuilder934** [comment]
I checked and this was already fixed in https://github.com/ldtteam/minecolonies/pull/6346, so I'll close this
