### ISSUE TITLE
Pupil count not reflected in Town Hall GUI

### ISSUE THREAD

**Issue by smmmadden** [ldtteam/minecolonies#6358]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4 (35.1.28)
- MineColonies Version: minecolonies-0.13.547-ALPHA-universal
- Structurize Version: structurize-0.13.104-ALPHA-universal
- Related Mods and their Versions:

## Expected behavior

Teacher Counts should (I believe) be 1 of 1 (when there is a school & teacher assigned)
Pupil Counts should reflect how many children are enrolled(hired) in the school.  This has nothing to do with # of teachers which is skewed when pupils are added.  I have 4 pupils and 1 teacher, but my Town Hall says I have 4 of 11 teachers and 4 pupils.

Town Hall GUI incorrectly displays # of pupils and Teachers
## Actual behavior

Just inaccurate information about teachers and pupils

## Steps to reproduce the issue

Build a school to level 5
Hire a teacher
Have children turned on in Town Hall
Hire them to the school
Review Town Hall GUI to see the counts for Teachers, Pupils and Children.  Pupils and Children can be different if some don't get hired first.  But the total pupils should not change the Teacher counts.
1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Can you please try updating and check if it fixes it?
