### ISSUE TITLE
Smelter asks for Ores to smelt, but courier s/b supplying the Smelter

### ISSUE THREAD

**Issue by smmmadden** [ldtteam/minecolonies#6359]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4 (35.1.28)
- MineColonies Version: 0.13.547-ALPHA-universal
- Structurize Version: 0.13.104-ALPHA-universal
- Related Mods and their Versions:

## Expected behavior

Miner digs up ores and courier picks up, delivers to warehouse
Smelter requesting Ores, should send request to Courier to check warehouse and deliver xx stacks to smelter
## Actual behavior

Smelter never gets couriers to pick up smelted ores (ingots, diamonds, etc) or deliver ores to be smelted

## Steps to reproduce the issue

Verified in 3 colonies that the Smelter asks for ores and players have to provide to them as well as remove smelted items from inventory and deliver to warehouse manually.  All builds are at level 5 and there are plenty of ores in the warehouses.
1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
I can't reproduce this, is there any NBT data on those ores?

**Comment by Raycoms** [comment]
Can you also check the latest alpha?

**Comment by smmmadden** [comment]
Just upgraded the mods to their latest versions, rechecked and I'm no longer seeing the behavior.  
Thanks!
