### ISSUE TITLE
Builder not requesting item to player

### ISSUE THREAD

**Issue by kreezxil** [ldtteam/minecolonies#636]
I have to be psychic again, I think this is related to all other issues where an npc is appearing to "stop" working.

If I feed her the right materials she'll begin working again, she does actively scan her workbox tho.

Need to make a strong suggestion here, on the following info screen there needs to be another information line that says exactly what the needed item is.

![2017-02-19_16 16 37](https://cloud.githubusercontent.com/assets/3880072/23107265/61b2d004-f6bf-11e6-8433-ffd66ee7965a.png)

**Comment by kreezxil** [comment]
Possible related items: #634, #622, #615, #609, #584, #570

**Comment by marchermans** [comment]
As per request I started merging Issues that are related to things I found while going through the source code. One of these is the request system. Closing this in favor of #638
