### ISSUE TITLE
Deleting default recipes causes the workstation to reset to just default recipe

### ISSUE THREAD

**Issue by cinnamennen** [ldtteam/minecolonies#6362]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: 13.547
- Structurize Version: 13.104
- Related Mods and their Versions: n/a

## Expected behavior

you can delete a default recipe

## Actual behavior
place down a dyer
delete the cactus to green recipe
watch the block reset to initial recipes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by XykoZ** [comment]
I just had this happen on the sawmill too.
After adding recipes, it adds additional ones. Deleting these results in the whole recipe list being deleted.
Re-testing, this is reproducable after adding wood slab recipes.

**Comment by Raycoms** [comment]
Can you reproduce this consistently?

**Comment by aryst0krat** [comment]
This behaviour is still present and consistently reproducible as of 1.19.2-1.1.628-BETA. Removing one recipe will result in it coming back shortly, potentially increasing the amount of known recipes to an invalid state such as "11/10 recipes". Removing multiple recipes seems to occasionally result in all non-default recipes being removed.
