### ISSUE TITLE
Crash while opening the build menu of asian barracks 3

### ISSUE THREAD

**Issue by MatthiasMann** [ldtteam/minecolonies#6363]
### Prerequisites

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: 0.13.557
- Structurize Version: 0.13.104
- Forge Version: 1.16.4-35.1.31
- Related Mods and their Versions:

## Expected behavior
No crash

## Actual behavior
Minecraft crashed (single player)

## Steps to reproduce the issue
1. Open the build options menu of asian barracks 3
2. Crash

### Logs
- latest.log: https://gist.github.com/MatthiasMann/0610d14dddf115beca8f7e55546cdc92
- crashlog: https://gist.github.com/MatthiasMann/443d4794c980e948afc3c2f6e06a2965

### Notes
The client crash is likely a follow up crash caused by this error: https://gist.github.com/MatthiasMann/6ef5f417588fae5e605b0c9bf35082cf
But I think the UI should be able to handle an empty resource list and disable the build button in that case.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MatthiasMann** [comment]
Actually - the barracks displayed 'Barracks 2' in the first UI. But I did upgrade them from 2->3 before closing done Minecraft yesterday.
And as my builder had no open requests and didn't do anything - I assumed it finished upgrading.

**Comment by ravenbuilder934** [comment]
Fixed
