### ISSUE TITLE
Server log is getting spammed with "Skipping entity with id "

### ISSUE THREAD

**Issue by tobi1449** [ldtteam/minecolonies#6364]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4, Forge 35.1.28
- MineColonies Version: 0.13.557-ALPHA
- Structurize Version: 0.13.104-ALPHA
- Related Mods and their Versions:

## Expected behavior
Log isn't getting spammed

## Actual behavior
As soon as a player gets close enough to one of the two colonies on our server, the log spam starts.
The message is just "Skipping entity with id ", no actual entity ID is given.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by lessthanzach** [comment]
I find that additionally running /ftbchunks unload_all seems to clear the error for a short time before the problem comes back. Very interesting behavior and unfortunately 4 people on my server have the colonies so it's a very consistent error. 
I will also add that it appears to happen even when no one is logged into the server. Maybe the colonies are attempting to force chunks to stay loaded?
I'm on ATM 6 1.3.7 modpack currently. Issue wasn't initially present.

**Comment by someaddons** [comment]
how about attaching the log? :D

**Comment by tobi1449** [comment]
There you go, I snipped it at the first occurrence of the skipping
https://www.dropbox.com/s/domk05f841wtkjh/debug.log?dl=0

**Comment by Raycoms** [comment]
I double checked this, it seems at one moment you had world corruption around the colonies, maybe loaded the world once without the mod installed, or so. You got things like this "Block entity invalid:" in your log around that area too. - can't reproduce. Most likely not our fault.

**Comment by AKLKZ** [comment]
In my case problem solved after using command /minecolonies prune-world-now with the 3 stages.
