### ISSUE TITLE
The BeeKeeper asked me to send you a Log file

### ISSUE THREAD

**Issue by GeekJay206** [ldtteam/minecolonies#6367]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: 0.13.510 Alpha
- Structurize Version: 0.13.102 Alpha

## Problem description

While plating the Minecraft + MineColonies my Bee Keeper displayed the Red Exclamation + Gear icon so I clicked on the Worker and got a message box telling me that there was a problem with the Worker's AI and requesting that I send the developer team my latest.log file, which I've attached.
[latest.log](https://github.com/ldtteam/minecolonies/files/5780454/latest.log)

### Notes or related things

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
There have been some AI fixes recently, can you please try updating (latest is 557 last I checked) and see if that fixes it?

**Comment by Rithenar** [comment]
Also, when I experienced this issue, it went away after restarting server and client if the update does not fix it.
