### ISSUE TITLE
Lvl 5 Medieval Birch Citizen House Has No Beds

### ISSUE THREAD

**Issue by GeekJay206** [ldtteam/minecolonies#6368]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: 0.13.510 Alpha
- Structurize Version: 0.13.102 Alpha

## Problem description

The Medieval Birch Citizen House has no beds at level 5 so assigned citizens just congregate around the table at night and are never "tucked in" and don't sleep. And the "Getting Sleep" Happiness rating quickly goes red and stays there.

### Notes or related things

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
#5006
