### ISSUE TITLE
Builder's Hut cannot be crafted with cactus door

### ISSUE THREAD

**Issue by Galaxy2Alex** [ldtteam/minecolonies#6369]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: 0.13.557-ALPHA
- Structurize Version: 0.13.104-ALPHA
- Related Mods and their Versions: n/a

## Expected behavior
You can craft the Builder's Hut block with cactus doors

## Actual behavior
You can't: https://i.imgur.com/KMn3pGH.png

## Steps to reproduce the issue

1. Try crafting a Builder's Hut with a cactus door
2. Fail

### Logs

More than happy to provide if necessary but I don't think that is needed here.

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by WenXin20** [comment]
The door in the recipe could be replaced with the `minecraft:wooden_doors` tag to make it compatible with all modded doors.
