### ISSUE TITLE
structurize

### ISSUE THREAD

**Issue by 0rb1tall** [ldtteam/minecolonies#6372]
"Mod minecolonies requires structurize 0.13.96-ALPHA currently, structurize is 0.13.108-Alpha

**Comment by Raycoms** [comment]
Downgrade to the right version

**Comment by ravenbuilder934** [comment]
Actually, you should update MineColonies. If your version of mcol needs 96 alpha, it's _very_ out of date. We recommend getting the latest alpha in all cases. (Downgrade Structurize to 104 though, the version of minecolonies that goes with 108 isn't out yet.)
