### ISSUE TITLE
Colonists don't use rails that change elevation

### ISSUE THREAD

**Issue by lawl281** [ldtteam/minecolonies#6374]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: 0.13.557-ALPHA-universal
- Structurize Version: 0.13.104-ALPHA-universal
- Related Mods and their Versions:

## Expected behavior

I expect colonists traveling up or down a sloped rail to ride it like a minecart normally would.

## Actual behavior

The colonist hops out of the cart at the bottom of the slope and walks up.
The colonist hops in and out of the cart at each step down the slope.

## Steps to reproduce the issue

1.  build a colony with a rail system your colonists will use and get the rail research.
2.  put a bridge in your colonists rail system so they have an up and down slope
3.  Colonists ride to the base of the bridge, get off their cart and climb to the top. Colonists hop in their car and ride across the bridge, then proceed to hop into cart at each level of the decent.

### Logs

- latest.log: 
- crashlog: 

### Notes

Tested on minecolonies official modpack to verify the issue wasn't due to the pack I first noticed on.
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Fixed
