### ISSUE TITLE
Can not add fake player to permissions list

### ISSUE THREAD

**Issue by KySoto** [ldtteam/minecolonies#6375]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.** (i searched "fake" for fakeplayer issues)

### Context 

- Minecraft Version:1.16.4
- MineColonies Version: minecolonies-0.13.557-ALPHA-universal.jar
- Structurize Version: structurize-0.13.104-ALPHA-universal.jar
- Related Mods and their Versions:
- Valehlsia 3.1.4 https://www.curseforge.com/minecraft/modpacks/valhelsia-3/files/3162332

## Expected behavior

i expect to see a + sign next to a player trying to do things in my colony
## Actual behavior

there is no + sign

![image](https://user-images.githubusercontent.com/835408/104077134-4a340200-51cd-11eb-8ac3-4941ae7299f2.png)
## Steps to reproduce the issue

1. Have a mod that uses fake players
2. have default permissions
3. attempt to use a block that uses the fake player
4. see the fake player in permissions log with no + next to the name

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Please report to IF to handle their fakeplayers accordingly. Fakeplayers are supposed to hold the UUID of the player that placed them, that is how we also designed the initial compatibility. The + is only a workaround to allow players to handle that while those mods are denying their responsibility to handle the fakeplayers accordingly.
