### ISSUE TITLE
The mercenary caused the game to crash.

### ISSUE THREAD

**Issue by wkurumi** [ldtteam/minecolonies#6377]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.16.4
- MineColonies Version:minecolonies-0.13.559-ALPHA-universal
- Structurize Version:structurize-0.13.104-ALPHA-universal
- Related Mods and their Versions:

## Actual behavior

The mercenary caused the game to crash.

## Steps to reproduce the issue

1. Hire some mercenaries.
2. The game crashes.
3. The game crashes.
[minecraft-exported-logs-2021-01-10T01-45-04.log](https://github.com/ldtteam/minecolonies/files/5791533/minecraft-exported-logs-2021-01-10T01-45-04.log)
[latest.log](https://github.com/ldtteam/minecolonies/files/5791534/latest.log)

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by wkurumi** [comment]
Downgrade to the stable version can be resolved.

**Comment by ravenbuilder934** [comment]
Fixed
