### ISSUE TITLE
Can't teach recipes to my workers

### ISSUE THREAD

**Issue by Domvel55** [ldtteam/minecolonies#6381]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: 0.13.557-ALPHA
- Structurize Version: 0.13.104-ALPHA
- Related Mods and their Versions:

## Expected behavior

The ability to teach a recipe to a worker/building.
## Actual behavior

Not able to teach any recipe to any worker/building. 
Once the recipe is in the crafting grid the crafted item does not appear on the output and the done button does not save the recipe.

## Steps to reproduce the issue

1. Start a mine colony world
2. Increase size of colony
3. One day the bug started

### Logs

- latest.log: 
- crashlog: 

### Notes

I tested this on another world in the same mod pack and I have the ability to teach my citizens recipes.
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MatthiasMann** [comment]
which building and which recipe did you try to teach? Not all crafters can craft all the things.

**Comment by Domvel55** [comment]
I cant teach any recipe to anyone. I tried simple stuff like an oak door recipe to the sawmill. This did not work and the oak planks in the craft grid produced no output when inside the teach recipe tab in the saw mill but did produce an output when inside of a normal crafting bench.

**Comment by Domvel55** [comment]
I figured it out after a bunch of trial and error with mods I found it. The FastWorkbench mod which caches workbench data to increase fps and smoothness of gameplay breaks the building recipe builder.

**Comment by Raycoms** [comment]
oh, how do they do that. Please report it to them then. And here it's https://github.com/ldtteam/minecolonies-features/issues/135
