### ISSUE TITLE
Medieval Spruce Restaurant not placeable

### ISSUE THREAD

**Issue by Graphicscore** [ldtteam/minecolonies#6382]
I am running Minecolonies 0.13.437 on MC 1.16.4 with Structurize 0.13.100.

The "cook" , restaurant building not placeable with the Building Tool, it makes an "error" beep and consumes my restaurant item. Only one structurize placeholder ist placed where I guess the the restaurant block should have gone.

` 
[14:51:53] [Server thread/ERROR] [minecolonies/]: BuildTool: building is null!
Jan 10 14:51:53 vmd36315.contaboserver.net start.sh[8944]: java.lang.Exception: null
Jan 10 14:51:53 vmd36315.contaboserver.net start.sh[8944]:         at com.minecolonies.coremod.network.messages.server.BuildToolPlaceMessage.setupBuilding(BuildToolPlaceMessage.java:352) ~[minecolonies:0.13.437-RELEASE] {re:classloading}
Jan 10 14:51:53 vmd36315.contaboserver.net start.sh[8944]:         at com.minecolonies.coremod.network.messages.server.BuildToolPlaceMessage.handleHut(BuildToolPlaceMessage.java:265) ~[minecolonies:0.13.437-RELEASE] {re:classloading}
Jan 10 14:51:53 vmd36315.contaboserver.net start.sh[8944]:         at com.minecolonies.coremod.network.messages.server.BuildToolPlaceMessage.onExecute(BuildToolPlaceMessage.java:179) ~[minecolonies:0.13.437-RELEASE] {re:classloading}
Jan 10 14:51:53 vmd36315.contaboserver.net start.sh[8944]:         at com.minecolonies.coremod.network.messages.splitting.SplitPacketMessage.lambda$onExecute$1(SplitPacketMessage.java:128) ~[minecolonies:0.13.437-RELEASE] {re:classloading}
Jan 10 14:51:53 vmd36315.contaboserver.net start.sh[8944]:         at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:215) ~[forge:?] {re:classloading}
Jan 10 14:51:53 vmd36315.contaboserver.net start.sh[8944]:         at com.minecolonies.coremod.network.messages.splitting.SplitPacketMessage.onExecute(SplitPacketMessage.java:128) ~[minecolonies:0.13.437-RELEASE] {re:classloading}
Jan 10 14:51:53 vmd36315.contaboserver.net start.sh[8944]:         at com.minecolonies.coremod.network.NetworkChannel.lambda$setupInternalMessages$2(NetworkChannel.java:262) ~[minecolonies:0.13.437-RELEASE] {re:classloading}
Jan 10 14:51:53 vmd36315.contaboserver.net start.sh[8944]:         at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:128) ~[forge:?] {re:classloading}
Jan 10 14:51:53 vmd36315.contaboserver.net start.sh[8944]:         at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_212] {}
Jan 10 14:51:53 vmd36315.contaboserver.net start.sh[8944]:         at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:128) ~[forge:?] {re:classloading}
Jan 10 14:51:53 vmd36315.contaboserver.net start.sh[8944]:         at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:162) ~[forge:?] {re:classloading}
Jan 10 14:51:53 vmd36315.contaboserver.net start.sh[8944]:         at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:80) ~[forge:?] {re:classloading}
Jan 10 14:51:53 vmd36315.contaboserver.net start.sh[8944]:         at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-3.0.5-service.jar:?] {}
Jan 10 14:51:53 vmd36315.contaboserver.net start.sh[8944]:         at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-3.0.5-service.jar:?] {}
Jan 10 14:51:53 vmd36315.contaboserver.net start.sh[8944]:         at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?] {}
Jan 10 14:51:53 vmd36315.contaboserver.net start.sh[8944]:         at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:84) ~[forge:?] {re:classloading}
Jan 10 14:51:53 vmd36315.contaboserver.net start.sh[8944]:         at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:88) ~[forge:?] {re:classloading}
Jan 10 14:51:53 vmd36315.contaboserver.net start.sh[8944]:         at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_212] {}
Jan 10 14:51:53 vmd36315.contaboserver.net start.sh[8944]:         at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:88) ~[forge:?] {re:classloading}
Jan 10 14:51:53 vmd36315.contaboserver.net start.sh[8944]:         at net.minecraft.network.play.ServerPlayNetHandler.func_147349_a(ServerPlayNetHandler.java:1413) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:reach_set_server_entity_interact,xf:fml:astralsorcery:allow_entity_interaction}
Jan 10 14:51:53 vmd36315.contaboserver.net start.sh[8944]:         at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:42) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
Jan 10 14:51:53 vmd36315.contaboserver.net start.sh[8944]:         at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:12) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
Jan 10 14:51:53 vmd36315.contaboserver.net start.sh[8944]:         at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?] {re:classloading}
Jan 10 14:51:53 vmd36315.contaboserver.net start.sh[8944]:         at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
Jan 10 14:51:53 vmd36315.contaboserver.net start.sh[8944]:         at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:classloading,pl:accesstransformer:B}
Jan 10 14:51:53 vmd36315.contaboserver.net start.sh[8944]:         at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:classloading}
Jan 10 14:51:53 vmd36315.contaboserver.net start.sh[8944]:         at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:733) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
Jan 10 14:51:53 vmd36315.contaboserver.net start.sh[8944]:         at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
Jan 10 14:51:53 vmd36315.contaboserver.net start.sh[8944]:         at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:classloading,pl:accesstransformer:B}
Jan 10 14:51:53 vmd36315.contaboserver.net start.sh[8944]:         at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:716) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
Jan 10 14:51:53 vmd36315.contaboserver.net start.sh[8944]:         at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:710) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
Jan 10 14:51:53 vmd36315.contaboserver.net start.sh[8944]:         at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?] {re:classloading,pl:accesstransformer:B}
Jan 10 14:51:53 vmd36315.contaboserver.net start.sh[8944]:         at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:696) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
Jan 10 14:51:53 vmd36315.contaboserver.net start.sh[8944]:         at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:645) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
Jan 10 14:51:53 vmd36315.contaboserver.net start.sh[8944]:         at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
Jan 10 14:51:53 vmd36315.contaboserver.net start.sh[8944]:         at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212] {}`

**Comment by Raycoms** [comment]
fixed in later alpha. Else #5006
