### ISSUE TITLE
MineColonies requires Structurize 104 even though 110 is available

### ISSUE THREAD

**Issue by smmmadden** [ldtteam/minecolonies#6383]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4 Forge 35.1.36
- MineColonies Version: 0.13.566
- Structurize Version: 0.13.110
- Related Mods and their Versions:

## Expected behavior

MineColonies should be checking for latest Structurize build, not ask for older build (104-ALPHA)
## Actual behavior

Server fails to start due to hard coded dependency to Structurize v0.13.104

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
This is intentional as sometimes Structurize has breaking changes. The version of mcol accepting 110 will be out soon though

**Comment by ravenbuilder934** [comment]
Fixed
