### ISSUE TITLE
latest alpha version wants a structurize version that doesn't exist

### ISSUE THREAD

**Issue by Zygus42** [ldtteam/minecolonies#6389]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: forge-1.16.4-35.1.29-installer
- MineColonies Version: minecolonies-0.13.566-ALPHA-universal.jar
- Structurize Version: minecolonies-structurize-0.13.110-ALPHA-universal

## Expected behavior
It would work with Structurize Version: minecolonies-structurize-0.13.110-ALPHA-universal

## Actual behavior
error message on startup saying that it wants Structurize Version: minecolonies-structurize-0.13.104-ALPHA

## Steps to reproduce the issue
1. start game with minecolonies-0.13.566-ALPHA-universal.jar

### Logs
not relevant

### Notes
Had a look in the Files section of CurseForge but I couldn't find a version called minecolonies-structurize-0.13.104-ALPHA

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Moleculor** [comment]
It exists. Use the version it tells you to use.

https://www.curseforge.com/minecraft/mc-mods/structurize/files/all

**Comment by Zygus42** [comment]
Hah, never even knew there was an All Files button.  Always assumed I was already looking at the full list under the Files tab.

**Comment by ravenbuilder934** [comment]
Also fyi the version of minecolonies accepting 110 will be out soon: #6353

**Comment by Tashy1** [comment]
Mine tells that needs " $(project.minecraftVersion)-(structurize_version) " version . What is that thing ?
