### ISSUE TITLE
SUGGESTION: Allow lumberjack to not plant seedlings.

### ISSUE THREAD

**Issue by Kellochli** [ldtteam/minecolonies#639]
Have a way to enable / disable the placement of seedlings by the lumberjack, after cutting down a tree, to allow for the clearing of an area to build in.

**Comment by cheongchan** [comment]
I had a similar problem with the lumberjack filling up the inventory with eggs due to a number of chickens in the area he works. Is there a way to have him only pick up wood and saplings?
