### ISSUE TITLE
Stonemason missing some Nether Quartz recipes

### ISSUE THREAD

**Issue by KKomrade** [ldtteam/minecolonies#6391]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: 0.13.566-ALPHA
- Structurize Version: 0.13.104-ALPHA
- Related Mods and their Versions: Valhelsia 3 Modpack v3.1.2

## Expected behavior
Stonemason should accept all quartz recipes (similar to nether brick crafting)

## Actual behavior
Stonemason does not accept the Quartz Block(from 4 nether quartz crystals) recipe as well as the Quartz Brick recipe. I attempted every other recipe involving nether quartz including the smooth variants and they all accepted just fine.

## Steps to reproduce the issue

1. Build a stonemason
2. Add the listed recipes above
3. Get a message saying wrong profession

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Mekle001** [comment]
The quartz block is a Mechanic recipe. The brick is definitely an issue that we need to fix.
