### ISSUE TITLE
Citizen Cap not Increasing

### ISSUE THREAD

**Issue by Wolfinskin** [ldtteam/minecolonies#6394]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: 0.13.480
- Structurize Version: 0.13.100
- Related Mods and their Versions: N/A

## Expected behavior

When I upgraded the Town hall I thought it would increase the citizen cap. It did not. I then proceeded to increasing the amount of housing I had and upgrading the houses so that it would increase the citizen cap. 

## Actual behavior

upgrading the town hall and upgrading my houses is not increasing the citizen cap

![image](https://user-images.githubusercontent.com/77360380/104374275-935fbb00-5519-11eb-834d-806832cd8e37.png)
![image](https://user-images.githubusercontent.com/77360380/104374312-9fe41380-5519-11eb-8cb6-660f4e1381c7.png)
![image](https://user-images.githubusercontent.com/77360380/104374378-b9855b00-5519-11eb-9ce1-8b22f603e37d.png)

![image](https://user-images.githubusercontent.com/77360380/104374473-d3bf3900-5519-11eb-9e2b-23a364aad955.png)

## Steps to reproduce the issue

1. Build the town hall. 
2. Then build the tavern 
3. Then build the houses and upgrade the town hall 

### Logs

I have no crash logs

### Notes

---

**Comment by ravenbuilder934** [comment]
This was already fixed in the latest alpha, please update (the way we use them, alphas are not any less stable)

**Comment by Wolfinskin** [comment]
Ah thank you and great I was worried about using the alpha straight away. Sorry as well feel like an utter noob

**Comment by ravenbuilder934** [comment]
lol that's ok, for most mods alphas actually are less stable
