### ISSUE TITLE
[1.16.4] CTD Related to Colony Flags

### ISSUE THREAD

**Issue by Sandriell** [ldtteam/minecolonies#6396]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: minecolonies-0.13.566-ALPHA-universal
- Structurize Version: structurize-0.13.104-ALPHA-universal

## Expected behavior

Not to crash?

## Actual behavior

Got a crash to desktop, looks to be related to the colony flag.

## Steps to reproduce the issue

Unsure of steps to reproduce, but I had a building upgrade going and that building did have a colony flag on it that the builder would have wanted to remove because it was not actually part of the schematic- I had placed it manually.

After the crash I was able to reload and continue playing without issue (least for a couple minutes as of writing this lol).

### Logs

- crashlog: https://gist.github.com/Sandriell/cad2ca97979def7852dfc5765660e2d2

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Bob-of-Death** [comment]
CTD while crafting colony flag, now results in failure to use AE2 wireless crafting at all

**Comment by Talyda** [comment]
> CTD while crafting colony flag, now results in failure to use AE2 wireless crafting at all

If you have an issue in a current version of minecolonies that is still being supported, you should make a new issue. This particular issue is over 4 years old, and was fixed then =)
