### ISSUE TITLE
Valhelsia_3/Courier informed me to tell you something is wrong.

### ISSUE THREAD

**Issue by atbjacobs** [ldtteam/minecolonies#6398]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: 0.13.566-ALPHA
- Structurize Version: 0.13.104-ALPHA

## Problem description

I was playing and a courier informed me (by the red exclamation and cog) to let the developers see the "latest.log" file. I closed out of the game and reloaded it, no more red exclamation or cog, just wanting a guard tower nearby. Hope I'm submitting this right as it's my first time. Also, running the Valhelsia 3 ver. 3.1.5 with this modpack preloaded.
[latest.log](https://github.com/ldtteam/minecolonies/files/5812765/latest.log)

### Notes or related things

Things seem to be working ok, but I am unsure as I'm still learning this setup. Fantastic Mod!!! (Except my miner just got killed by a mob and still trying to figure out how to protect them. He found a cavern haha.)
---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Can you put the file in a https://gist.github.com please?

**Comment by atbjacobs** [comment]
I added it to my ticket. It may not be the same as I've been playing
survival mode today. The issue arose while playing on Creative mode. Do I
need to do something else besides put it in a gist (secret) as the link
entails?

**Comment by ravenbuilder934** [comment]
No, although I don't see it in the ticket. Are you use it saved?

**Comment by atbjacobs** [comment]
https://gist.github.com/atbjacobs/3d699d92c6a07bbe306e1f3ed9f1b469

**Comment by Raycoms** [comment]
Same as: https://github.com/ldtteam/minecolonies/issues/5672
