### ISSUE TITLE
Unable to break town hall block to move it

### ISSUE THREAD

**Issue by Talyda** [ldtteam/minecolonies#6401]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: 0.13.566
- Structurize Version: 0.13.104
- Related Mods and their Versions:
(all the ones in the official modpack)

## Expected behavior
After placing town hall to create the colony, I should be able to (used to be able to!) break the town hall hut block with an axe so I could place the building where I wanted it to be
Now it seems like I have to build it and use the deconstruct and pick up options which is very inconvenient if you have placed the building in an awkward spot to build just to set the town centre! 

## Actual behavior
Try to break it as soon as colony is created, and I get told I don't have permission to do that

## Steps to reproduce the issue

1. place town hall
2. break town hall
3. read message

### Notes
I don't know if this is a bug, or a feature, but the old way was much better! If you don't want the builder digging up the environment just to build a building you don't even want there, this is frustrating

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by gattsuru** [comment]
Looks like the on(PlayerEvent.BreakSpeed) isn't firing reliably when trying to break the hut block itself.  As a temporary workaround, starting to dig or mine nearly _any_ simple non-instant harvest block within the bounds of the colony (while not in creative) should fire that event and then let you axe the Town Hall block, but should be something to fix since it may point to a bug in PVP mode.

**Comment by Talyda** [comment]
Yep! That worked! Just dug up a bit of dirt, then I could break the hut block =)
Thanks for the workaround!
