### ISSUE TITLE
Builder AI asks to send latest.logs

### ISSUE THREAD

**Issue by Kobeanss** [ldtteam/minecolonies#6402]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.533
- Structurize Version: 0.13.105
- Related Mods and their Versions:

## Expected behavior
Builder does not run into AI error message

## Actual behavior
Builder AI runs into AI error message asking for latest.log

## Steps to reproduce the issue

1. Have builder
2. See error message when interacting with builder

### Logs

- latest.log: https://gist.github.com/Kobeanss/f29cb4f9db2d754ddefb73a69be203fb

### Notes
I'm having so much fun with the mod, and so far it's not creating any more problems that I notice. The builder is still building but the error message keeps popping up.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
You're around 30 versions out of date and there have been some AI fixes recently, please update

**Comment by dylithian** [comment]
I am having this issue on 0.13.610-ALPHA as well.

**Comment by ravenbuilder934** [comment]
That's probably a different AI error, can you create a new issue?

**Comment by dylithian** [comment]
Not entirely sure what fixed it, but breaking and replacing the builder hut seems to have resolved the issue
