### ISSUE TITLE
deleted colony gets automatically restored as i restart my forge server

### ISSUE THREAD

**Issue by nicoo1708** [ldtteam/minecolonies#6406]
### Prerequisites 

- [ x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- MineColonies Version: minecolonies-0.13.566-ALPHA-universal.jar
- Structurize Version: structurize-0.13.104-ALPHA-universal
- Related Mods and their Versions:

## Expected behavior
 The deleted colony should stay deleted and i should be able to build a new colony (when i try to build a new colony it just says i should try it somewhere else, at this point the old one does not exist anymore or does not show up in colony list until i restart my server and it gets automatically restored for some reason, while trying to build a new one the townhall block also says im not near an existing colony, neither am i the owner of one)

## Actual behavior
 I succesfully delete an existing colony but it automatically gets restored as soon as i restart my server. I can't build a new colony near it even right after deleting the old one (does not show up in colony list until i restart my server and it gets automatically restored) 

## Steps to reproduce the issue

1.  Delete an existing colony and try to build a new one (which does not work on my end)
2.  Restart forge server
3.  Deleted colony gets restored for some reason 

### Logs

- latest.log:  https://gist.github.com/nicoo1708/f9d17575e1ce64d1f39999c3d39cb8db
- crashlog: 

### Notes
 

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
this is in SMP right?

**Comment by Raycoms** [comment]
Are you regularly shutting down the server and not crashing it?

**Comment by nicoo1708** [comment]
yes, i am shutting it down regularly

**Comment by KKomrade** [comment]
Just out of curiosity were you using medieval alt town hall?
