### ISSUE TITLE
AI error with Cowherd

### ISSUE THREAD

**Issue by Boodlyneck** [ldtteam/minecolonies#6407]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.15.2
- MineColonies Version:0.13.562-ALPHA
- Structurize Version:0.13.105-ALPHA
- Related Mods and their Versions:

## Expected behavior
No AI error

## Actual behavior
A player on my Craft To Exile Dissonance server got this AI error today, I'm just dropping off the log file as requested by your mod. It didn't cause a crash. (Worker in question is Cowherd)
![unknown](https://user-images.githubusercontent.com/68196907/104793353-1ed28980-5770-11eb-95db-8fff1e28d7f9.png)

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: https://gist.github.com/Boodlyneck/52fd7c47d5cf2411000c1848e8cfb69e
- crashlog: No crash

### Notes
Filled in by raven

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Justen-N** [comment]
I'm not sure there's anything to do with this one, between Mine and Slash, which has caused issues previously, and performant, which is the only other call that may have affected this, it looks more like a compat issue than an Issue with minecolonies itself. In fact, after a closer look, it's definitely Mine and Slash. I'll take a look and see what was said the last time this issue came up.

**Comment by Raycoms** [comment]
it is actually mine/slash that is crashing when our herders kill a cow. Could you please report that to them with the same info?
