### ISSUE TITLE
Colonists stuck at Harvest Festival's decorative blocks

### ISSUE THREAD

**Issue by DcNdrew** [ldtteam/minecolonies#641]
### Minecolonies version

version 0.6.6

### Expected behavior

- Jump/step up on branches, trunks and stones

### Actual behaviour

- Colonists start to walk to their destination, but when they reach Harvest Festival's decor blocks, they stop there and won't move until I remove the obstacle. I can hit them, to the other side of the block, there they still want to step on the decor, and after some moments they became sensible and try to find another route.
I can remove the obstacle too, in that case, the colonist jumps when the block breaks.

### Steps to reproduce the problem

1. Install HF and Minecolonies
2. Wait until some decor blocks appear around and let colonists to work
3. ...
4. Profit

**Comment by marvin-bitterlich** [comment]
Do Zombies and other mobs get stuck on these as well? It seems that Harvest Festival has made these blocks hard to deal with for the minecraft locomotion system. We can do some limited blacklisting for that but then they will simply walk around these blocks, that may not be what you want. Can you mention the Harvest Festival devs here? Or cross-post this issue there?

**Comment by DcNdrew** [comment]
No, other mobs don't have this problem.
How does your workers choose path? For me it looks like they choose a direction and they want to go on that path, and repeating the walking until they are on it.
Well, Harvest Festival's decors are just appearing, they are not generated. What if a decor appears on the workers' path? He want to step on the block under the decor, but he can't, so he's just trying. If I hit him, he's off the path, so he choose another direction.
If I break the decor, the block updates, the worker "finds" it and want to jump over.
What do you think?

**Comment by Raycoms** [comment]
Pathfinding works the following: Worker pre-calculates a path from A to B.
After calculation he will take that path no matter what. If something
appears on the way, there is a certain timeout for recalculation and he
will avoid these blocks.

2017-04-05 9:08 GMT-03:00 DcNdrew <notifications@github.com>:

**Comment by DcNdrew** [comment]
When did you coded the timeout? Because this problem was on in February, and there was a bug where HF decors appeared in too big numbers. Nowadays workers don't contact with decors, so I'll try to add some by myself.

**Comment by Raycoms** [comment]
Around a year ago they recalculated directly without a timeout which causes
a lot of lag. I think the timeout is around 10 seconds.

2017-04-05 9:22 GMT-03:00 DcNdrew <notifications@github.com>:

**Comment by DcNdrew** [comment]
I see. Well, actually something similar happened sometimes without decor. When I see it next time, I'll shoot some pics. Worker starts to look down to the ground, and stand on a specific block. When I push him away, he goes back. Sometimes he comes back, and start to work, but for example the lumberjack was running around a tree, and doesn't want to work until I broke some logs or fire/hire him.

**Comment by joshiejack** [comment]
@DcNdrew This is something I can easily do something about. At the moment they act like fences for every entity except for players. I did that so that animals wouldn't escape from climbing on top of them when they spawn inside their fenced areas :p. I can just change it so only animals are affected =P.

**Comment by Raycoms** [comment]
Okay great to know. I think I can close that then.
