### ISSUE TITLE
Cannot complete "Check out the Guide" advancement.

### ISSUE THREAD

**Issue by Slyklaw** [ldtteam/minecolonies#6411]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16
- MineColonies Version: Currently minecolonies-0.13.557-ALPHA, but world started around minecolonies-0.13.530-ALPHA
- Structurize Version: structurize-0.13.104-ALPHA

## Problem description
I've been playing Direwolf20 1.16. The world has been upgraded from version 1.1.1 to 1.3.1. Opening the Builder's Hut does not complete the "Check out the Guide" advancement.

![2021-01-19_06 52 02](https://user-images.githubusercontent.com/44900062/104973021-15724700-5a26-11eb-924c-b3d2b633f98b.png)

### Notes or related things
I cannot reproduce this in a new world.

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
side effect of https://github.com/ldtteam/Structurize/issues/244?

**Comment by Raycoms** [comment]
No, I think I know some things that could cause it, I'll add a fallback

**Comment by gattsuru** [comment]
If that guide opens, it'll trigger the achievement (specifically, when clicking the button on the bottom-right-hand-side of the WindowGuide), but even the distorted display doesn't seem to consistently open on new worlds.  Seemed like it was related to the way Minecraft's achievement system works, but I haven't been able to figure enough of the cause to try and fix it.

**Comment by Raycoms** [comment]
When you open the builder hut, no guide opens, right? Even after restarts, etc?

**Comment by Slyklaw** [comment]
> When you open the builder hut, no guide opens, right? Even after restarts, etc?

Correct. Server and client restarted. Pretty sure I never saw the guide.

**Comment by Slyklaw** [comment]
It works now. Thanks!
