### ISSUE TITLE
NullPointerException with Optifine when joining a Server

### ISSUE THREAD

**Issue by tobi1449** [ldtteam/minecolonies#6415]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: minecolonies-0.13.566-ALPHA-universal
- Structurize Version: structurize-0.13.104-ALPHA-universal
- Related Mods and their Versions: OptiFine_1.16.4_HD_U_G6

## Actual behavior

```
java.lang.NullPointerException: Unexpected error
	at com.minecolonies.api.compatibility.CompatibilityManager.isCompost(CompatibilityManager.java:237)
```

### Logs
- crashlog: https://paste.ee/p/UezQs

### Notes
Really only happens with Optifine active.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Report to Optifine
________________________________

**Comment by Raycoms** [comment]
If optifine doesn't allow to access this here:

```
        final List<ItemStack> stacks = StreamSupport.stream(Spliterators.spliteratorUnknownSize(ForgeRegistries.ITEMS.iterator(), Spliterator.ORDERED), true)
```

Please report this to them, they messed up something seriously.

**Comment by tobi1449** [comment]
Interestingly enough, the with the latest stable version of Optifine for 1.16.5 this crash doesn't occur to me anymore.

**Comment by ravenbuilder934** [comment]
Yea, OF fixed it (thank goodness!)

**Comment by Raycoms** [comment]
Yeah, I talked with them, they fixed it
