### ISSUE TITLE
Multiple colonists have AI Error

### ISSUE THREAD

**Issue by Epic-guy33** [ldtteam/minecolonies#6418]
I'm Currently playing ATM6 And a large quite a few of my colonists have flagged the error
It started with my one of my builders and then spread to courier and then others

-------
Minecolonies Version   0.13.566-Alpha
[latest.log](https://github.com/ldtteam/minecolonies/files/5848519/latest.log)

**Comment by Raycoms** [comment]
I checked the log and it seems some inventories went corrupt in your world. Can you check racks and hut chests around the world and see if their inventories still work?

**Comment by Epic-guy33** [comment]
Just loaded up the world again and i havent got the ai error and the chest are fine althou racks arent joining correctly


![2021-01-22_18 58 38](https://user-images.githubusercontent.com/59932954/105533591-4089be80-5ce4-11eb-9fd6-0be1aea00a7e.png)

**Comment by Raycoms** [comment]
Yeah, the racks is fine. I think there was a quick problem with corruption in your world that solved itself. You can reopen this if you find a way to reproduce this.
