### ISSUE TITLE
[Feature] [$10] Minimum stock for Workers [$10]

### ISSUE THREAD

**Issue by Wissi** [ldtteam/minecolonies#642]
Deliveryman to keep a minimum inventory in each workers chest at all times and never remove these items. Having a GUI where player can select the amount and type of materials/tools each worker should have in their chest at all times.

Well I guess it's not that complicated to list it here (the coding on the other hand I have no idea how much work it might be). IMO the best way would be a tab (or page 2-3) in each workers chest GUI and a selection of the essentials of each worker to always have that in chest. The essentials for each worker are:

**Fisherman** - 2 Fishing Rods at all times, that's all he needs.

**Miner** - 1 stack each; Cobble, oak fence, oak slab, oak planks, torches. 1 pick and 1 shovel.  (highest Tiers avail, w/enchants if avail) (ladders until the shaft is finished in level 5 miner hut).

**Lumberjack** - 1 stack sapling (you define which variety or all), 1 axe (highest Tiers avail, w/enchants if avail).

**Farmer** - 2 stack each of the "crop" he has in his field(s) and 1 hoe (highest Tiers avail, w/enchants if avail).

**Guard** - 1 sword, 1 bow, 1 set of armor (highest Tiers avail, w/enchants if avail).

**Builder** - I suggest D-man only take/deliver if/when the builder ask/complains about needing materials/space in chest. I've noticed the d-man will remove materials from builder's chest while builder is working on a build and even takes materials needed for the current build. Here IMO there is no need for D-man to remove from chest or even bring anything unless the builder requests more space in chest or materials for build. Builder does NOT produce anything to have mats removed from chest at all, unless he complains about space.

Having a tool always in chest ensures that the worker will have 1 backup always in hut chest (since he has 1 in his personal inventory he's using to work with). Once the backup is taken there will be a missing tool in chest that D-man will have to replenish.  Ensuring that the worker will almost never ask for a tool or stop working because of that. Sounds good, right?

**Comment by marchermans** [comment]
As per request I started merging Issues that are related to things I found while going through the source code. One of these is the inventory keep system. Closing this in favor of #617

**Comment by marvin-bitterlich** [comment]
I reopen this as it is a separate thing imo. This one talks about a gui and changing what to keep

**Comment by marchermans** [comment]
Ah okey, that was Quick XD

**Comment by marchermans** [comment]
I added a note to the other Issue which states that a function like this should be a desired target of the new system when it is implemented

**Comment by Raycoms** [comment]
The idea of this here would be having a GUI in each worker hut where the player can add certain items to which should be kept in this particular building.

**Comment by Raycoms** [comment]
Closed in favor of joint issue.
