### ISSUE TITLE
[Server] java.lang.IndexOutOfBoundsException: Index: 0, Size: 0 involving Listeners

### ISSUE THREAD

**Issue by thorsanvil** [ldtteam/minecolonies#6421]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.6.4
- MineColonies Version: 0.13.570
- Structurize Version: 0.13.104
- Related Mods and their Versions:

## Expected behavior
World gens and server is stable.

## Actual behavior
World generates (as noted by spawn gen and world files presence) but then crashes.

## Steps to reproduce the issue
On server, haven't tried client yet.
minecolonies-0.13.570-ALPHA-universal
structurize-0.13.104-ALPHA-universal
May be sufficient but if not I had them present within the Monumental Experience mod pack.
It may simple be the mod doesn't play well due to volume of other mods (no expert talking here).

### Logs

- latest.log: https://gist.githubusercontent.com/thorsanvil/2c5071247dc3d8abb728e5279bc3d0e2/raw/6c846856f2494ca37d2402f6b93ab9b3d94252a0/gistfile1.txt

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
There is some mod, adding a furnacerecipe that is invalid and contains no input. Can you a) try with the newest minecolonies/structurize alphas and b) try to experiment with the pack a bit to find out which mod is causing this?

**Comment by thorsanvil** [comment]
@Raycoms  Ill give it a go with both a) and b), at a glance did you see any hinting to the mod? if not no need to respond, just asking :) .

**Comment by Raycoms** [comment]
No, couldn't see anything sticking out in the log.

**Comment by thorsanvil** [comment]
Attempt A): https://gist.githubusercontent.com/thorsanvil/1dccbf0401a6ecf481c820f0992faf58/raw/068ecf97c410ddc61683d11c7cab843e865eb13d/gistfile1.txt

Seem to have the same issue, appearance wise at least as I am not expert :).
structurize-0.13.113-ALPHA-universal
minecolonies-0.13.574-ALPHA-universal

**Comment by gattsuru** [comment]
Looks like the issues in that pack are from immersiveengineering:crafting/gold_ingot_from_dust and immersiveengineering:crafting/iron_ingot_from_dust, and _probably_ specifically the way the modpack's integrated jsons are 'disabling' those recipes.
`{"type":"minecraft:smelting","ingredient":{"item":"minecraft:air"},"result":"minecraft:air","experience":0.0,"cookingtime":200}`

(Or at least the immediate issues; there's an astounding amount of mess in there.)

I'm really tempted to throw some bounds checking or a try/catch block to better identify the cause of this type of problems, but this particular crash is more on the modpack maker than Minecolonies.

**Comment by Raycoms** [comment]
ohhh, disabling the recipe like that could exactly lead to that problem I believe.

**Comment by Raycoms** [comment]
I guess we could add a safeguard for that, even though I'm not happy how they solve that.

**Comment by Raycoms** [comment]
Can you try this one?

https://buildsystem.ldtteam.com/guestAuth/repository/download/LetSDevTogether_Minecolonies_Branches_Build/65670:id/build/libs/minecolonies-0.13.1170-PERSONAL-universal.jar

**Comment by thorsanvil** [comment]
So it worked, I got both server and client off that mod, and spun up both. Got into the server and so far so good. Spawned a ship and there are blocks missing, not sure if this is out of the scope of this ticket though.
Gist just in case its needed: https://gist.githubusercontent.com/thorsanvil/efb38cb54e17396920ce3764174a5c77/raw/554539bc9c0cafe6907b2317b74d34d51f89d5f1/gistfile1.txt

<img width="1862" alt="Capture" src="https://user-images.githubusercontent.com/10477436/105429457-787afe00-5c1f-11eb-9f77-411ff372c4b5.PNG">

**Comment by Raycoms** [comment]
the version I posted above, it works fine with the same modpack exactly?

**Comment by Raycoms** [comment]
And are those blocks missing consistently or only randomly?

**Comment by thorsanvil** [comment]
Consistently on new world, so I relogged in and out of the world and its back to normal, but every time I delete the world and load into it then spawn a ship its consistently missing parts in the same areas (can atleast confirm the front part)

mod list is huge so not sure the severity of it, but if relog is the fix I mean cant complain to to much.


Raven is suggesting a binary search through mods to check for possible problem, Raven had me test the struct + mine together on a clean client and no problem.
