### ISSUE TITLE
Cannot expand past 125 colonists

### ISSUE THREAD

**Issue by insufficient-funds** [ldtteam/minecolonies#6424]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.13.574-ALPHA
- Structurize Version: 0.13.113-ALPHA
- Related Mods and their Versions: JEI-1.16.4-7.6.1.65 

## Expected behavior

With all research completed, and available housing; I expect the max number of colonists to be 150, based on the default value in the config files.

## Actual behavior

With all research completed, available housing and available guard jobs, colony is not growing past 125 individuals. No new babies are being born, cannot recruit travelers from the tavern.

Showing a house with 2 available beds
![image](https://user-images.githubusercontent.com/20713737/105564984-949b9f80-5cf2-11eb-8bc3-1d0e1388b797.png)

Town citizen info:
![image](https://user-images.githubusercontent.com/20713737/105565018-b6952200-5cf2-11eb-8ee9-7b21db817639.png)

Hard to show any evidence that this is from the same town at the same time - but message showing I can't recruit anyone
![image](https://user-images.githubusercontent.com/20713737/105565040-d298c380-5cf2-11eb-9182-cb4d9a135f0c.png)

## Steps to reproduce the issue

1. Create a city
2. unlock all research related to # of citizens
3. Grow the city until you reach 125 citizens, and get no additionals

### Logs

- latest.log: https://gist.github.com/insufficient-funds/eebcaa7f21beed634bc8bb49363fed0c
- crashlog: 

### Notes
Discussed on Discord briefly- conversation starts here- https://discord.com/channels/139070364159311872/741531022872674314/802347247148073031

Another user suggested others have encountered this before, and someone made a change somewhere to fix it on their server; unknown what was done.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
When you hover, the 125 number, what does it say?

**Comment by insufficient-funds** [comment]
Just launched the game to check. It sows 124/125 citizens now (showed 125 lastnight, odd).  But the hover text is "Needs Housing."

For housing, I have a total of 78 usable beds (per my calculations):
6 - level 5 houses
2 - level 4 houses
12 - level 3 house
Tavern

Town hall shows 63 guards (I think those are the only ones that don't need their own housing, right?):
38 archers
25 knights

**Comment by gattsuru** [comment]
The current CitizenManager.java has an issue in maxCitizensFromResearch where a research-based cap of 200 or greater will return MineColonies.getConfig().getServer().maxCitizenPerColony.get() - 25. 

As a short-term fix, adding 25 on top of the intended actual maxCitizens in your serverconfig will work (ie, if you want it to mean 150, set the config to 175).  It's one of the secondary fixes in (https://github.com/ldtteam/minecolonies/pull/6181); not sure if we want to push the fix separately.

I'm not sure why you're seeing 124 citizens, though, unless you had a citizen die recently.

**Comment by insufficient-funds** [comment]
About 10 minutes after I posted the reply, the citizen count was back to 125 (with no birth messages).  Not sure what happened there.

I'll up the citizen cap in the config file as a workaround for now; thanks!

**Comment by Raycoms** [comment]
@gattsuru yes please, make a fix PR seperately (if you want to put some other minor fixes the branch might already have too, that'd be great)
