### ISSUE TITLE
Lumberjack destroys Buildings

### ISSUE THREAD

**Issue by Liguma** [ldtteam/minecolonies#643]
TestPack on Minecolonies Server 0.6.6 (Colonie Tiveden)

### Expected behavior

- Lumberjack cuts trees

### Actual behaviour

- destroys Fishermans hut

![2017-02-21_00 42 53](https://cloud.githubusercontent.com/assets/24432099/23153789/bbf38e2c-f80a-11e6-8d1f-ceaf02dd89ba.png)
![2017-02-21_00 49 05](https://cloud.githubusercontent.com/assets/24432099/23153790/bc1eedc4-f80a-11e6-8489-67fb043d11be.png)
![2017-02-21_00 52 45](https://cloud.githubusercontent.com/assets/24432099/23153792/bc220298-f80a-11e6-8e03-426cb11909ad.png)
![2017-02-21_00 52 50](https://cloud.githubusercontent.com/assets/24432099/23153791/bc1ef440-f80a-11e6-851a-e241d0ea9c7f.png)

**Comment by pmardle** [comment]
This is strange.. the Lumberjack will only recognise logs as trees if there are leaves nearby..  I can't see any leaves in your screenshots..

**Comment by Liguma** [comment]
Thera are now leafes - you are right :-)

**Comment by KarmicForager** [comment]
Lumberjack also took dark oak logs from decorative walls that were placed. 1.11.2. sorry no screen shots.

**Comment by Raycoms** [comment]
Yeah if leaves get into the building he might take the building down, unfortunately.
I see no way to improve his tree analysis.

**Comment by Liguma** [comment]
U can add the corner-points of every minecolonies-building to a table. The lumber-function, after a check, excludes now every wood within this area.
