### ISSUE TITLE
Builder doesn't use bed once higher tier is built

### ISSUE THREAD

**Issue by NetMasterFlex** [ldtteam/minecolonies#6433]
Mine Colonies Version: minecolonies-0.13.566-ALPHA-universal

Builder worker doesn't change bed to builder hut once the upgrade provides a bed, thus preventing another candidate from joining the colony.

I'm new to mine colonies, so if this is intended please advise.  Just doesn't make sense for there to be a bed in the builder hut or any other higher tier hut, when the occupant or worker isn't going to use it.

Please advise.

Thanks

NMF

**Comment by Raycoms** [comment]
Yes, the beds in worker hut are purely decorative. Only military buildings provide beds that the workers use.

**Comment by NetMasterFlex** [comment]
Military beds?  When do those come into play?  oh and Thanks for the clarification and lightening fast response.

NMF

**Comment by Raycoms** [comment]
Guard towers, barracks and combat academy and archery provide their own beds. So if you hire a person there, they will free up a bed somewhere else in the colony.

**Comment by NetMasterFlex** [comment]
Ah!  Good to know.  Thanks
NMF
