### ISSUE TITLE
all of my colony's huts' gui's cannot be accessed

### ISSUE THREAD

**Issue by TheoK47** [ldtteam/minecolonies#6435]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.585
- Structurize Version: 0.13.109
- Related Mods and their Versions: 

## Expected behavior

This bug would not happen
## Actual behavior

There comes a point where I have built/upgraded a certain number of buildings and then my builder's progression on those projects are stuck on whatever percent is showed at the time and I get an in game chat announcement saying the project was completed but the gui in the builder's hut shows otherwise. I restart my game and now I am unable to access any of my buildings hut blocks and when I try to access my townhall it shows me the attached image. I've tried doing a backup and reloading it from there and restarting my client but no dice. This has happened to me exactly like this twice now at similar spots in my town's progression so I don't think it was a one time fluke. 

![minecolonies](https://user-images.githubusercontent.com/39417448/105647230-ff66eb00-5e58-11eb-9240-1f06339b53d3.PNG)

## Steps to reproduce the issue

1. create a colony like usual
2. upgrade and build buildings (seems not to matter what they actually are just having builders do enough projects)
3. any hut interacted with will say that the respective building is missing message

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Do you have us a) logs before restart b) logs after restart and c) maybe
the world?

Am So., 24. Jan. 2021 um 20:34 Uhr schrieb TheoK47 <notifications@github.com

**Comment by TheoK47** [comment]
It seems to have resolved itself after I made another builder's hut and built another building with the new builder in the colony. The townhall seems to be functioning as intended again and I can interact with all the buildings again now. I dont have the logs before restart but I can upload the logs after and the world if you would like.

**Comment by Raycoms** [comment]
Ah, if it's not broken anymore it's difficult. Is this on a dedicated
server? Sometimes after a restart it might take a few seconds to get all
the data for the GUI.

Am So., 24. Jan. 2021 um 21:26 Uhr schrieb TheoK47 <notifications@github.com

**Comment by TheoK47** [comment]
No it's my single player world. I'm on a modpack called craft to exile dissonance

**Comment by Raycoms** [comment]
Still send us the logs, potentially all three now (third of the restart where it started working again)

**Comment by TheoK47** [comment]
Sorry, I'm not exactly sure how or what I'm supposed to send. Is there a separate minecolonies log I'm supposed to access somewhere or just the logs from the logs folder. Also, how should I send them, by just attaching a text file here or going through the gist link? I'm not experienced with github or gist so I'm not quite sure how to use gist, should I just copy and paste the log text to gist?

**Comment by ravenbuilder934** [comment]
Just the `latest.log` in the log folder, and gist please (yes, copy and paste)

**Comment by TheoK47** [comment]
https://gist.github.com/TheoK47/1f01d07490278cbe621e5977bf9020b3

I think it just broke again now that I fired that other builder that had fixed it

**Comment by Raycoms** [comment]
found the problem

**Comment by TheoK47** [comment]
yea it's broken again with both my original builder getting stuck again after completing their projects but the gui shows a progress bar
![chat notification](https://user-images.githubusercontent.com/39417448/105650207-e0bc2080-5e67-11eb-8aed-ac7298e88d1e.PNG)
![tab 1 builder 1](https://user-images.githubusercontent.com/39417448/105650209-e154b700-5e67-11eb-9f57-d118c6d6049a.PNG)
![tab 2 builder 1](https://user-images.githubusercontent.com/39417448/105650210-e1ed4d80-5e67-11eb-9b68-8a7bd3e943da.PNG)

**Comment by TheoK47** [comment]
> found the problem

what's the problem?

**Comment by Raycoms** [comment]
Fix pushed, next alpha will be released soon. It's a serialization issue for manual builders

**Comment by TheoK47** [comment]
ah so I can't have them on manual for now? and this will be fixed next update so I can just download the newest version then and this shouldnt be an issue?

**Comment by Raycoms** [comment]
Already released
