### ISSUE TITLE
miner requests ladders and voids them when fulfilled

### ISSUE THREAD

**Issue by Spongman** [ldtteam/minecolonies#6436]
- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ x] I made sure that **this issue is not a duplicate of any existing issue.**

- Minecraft Version: 1.15.2
- MineColonies Version: -0.13.562
- Structurize Version: 0.13.105
- Related Mods and their Versions:

my miner wasn't accepting the ladders he was requesting. they would go into his inventory (either by clicking the 'fulfill' button, or directly placing them in the inventory, or given by courier), however shortly after that they would slowly start to disappear - then number decreasing about 3 or 4 per second. they didn't appear in any other inventory nearby ('mine' block, or racks)

i have a darkoak mine level 4, and the cobble block at the top of the ladder was missing a ladder (maybe a barbarian broken it, who knows). replacing the ladder at the top (on the cobble block) fixed the issue.

![image](https://user-images.githubusercontent.com/1088194/105652640-9ab68b00-5e6e-11eb-9308-56e31bd57c26.png)

**Comment by Talyda** [comment]
Adding that I had that happen yesterday too - I know that I accidentally broke the ladder, then noticed the miner asking for ladders over and over again. Using the Caledonia style, while not a style in the mod, it is the exact same problem. Didn't report it cos I thought it was a fluke thing - but seems not!
*edits* I was on whatever was latest alpha for 1.16.5 at the time I was playing - I don't remember what that was now - I think I updated 3 versions today?
