### ISSUE TITLE
Lumberjack Making Stripped / Normal wood

### ISSUE THREAD

**Issue by SplashNetwork** [ldtteam/minecolonies#6437]
### Prerequisites 

- [] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: minecolonies-0.13.557-ALPHA-universal
- Structurize Version: structurize-0.13.104-ALPHA-universal

## Problem description
 My lumberjack makes large amounts of stripped wood + also some normal wood (i.e. 4 wood in a square in a crafting grid)

### Notes or related things
 My lumberjack just seems to make large amounts of both, is there a way to stop this? Someone said they sometimes do this if another colonist is requesting these types of wood (I assume builders) but he is doing it even when there are no open requests for these blocks. I find I need way way more normal logs than stripped/wood variants so it would be good for him to not do this basically. Let me know, thanks :)

P.S. Not using latest alphas because we're using the v2.5.1 server files

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Are you sure they're doing this unasked? They do this always when asked by another worker specifically, if you then pick it up there, and the request remains open, they will craft another batch

**Comment by SplashNetwork** [comment]
Sorry for my late response. He was doing it for a long time, hence why I made the issue, but so far he has stopped for now so this issue can be closed
