### ISSUE TITLE
1.15.2 - Barbarian Raid Starts, but no Barbarians Spawns if Colony is in a mountain (BoP Alps)

### ISSUE THREAD

**Issue by Beer1976** [ldtteam/minecolonies#6438]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2 (server)
- MineColonies Version: 0.13.576-ALPHA
- Structurize Version: 0.13.109-ALPHA
- Related Mods and their Versions: BiomesOPlenty-1.15.2-10.0.0.366

## Expected behavior
When the Barbarian raid bar appears, camps should appear somewhere within proximation of the colony to deal with them and enjoy their phat lewtz.

## Actual behavior
No camps appear.  either the barbarians kill themselves off at the start, at some point when they 'march' or never die.  Even with the /kill @e type command to kill the flavor of barbiarian/norsemen.  went into spectator mode to see if I could locate camps - no dice.

## Steps to reproduce the issue

1. Go to an Alps mountain in Biomes o plenty - keep colony at Y64ish (I didn't dig down - just in)
2. Dig out enough to start a colony large enough to meet requirements to trigger raids - add entry points into the mountain (I have 3)
3. When raid 'starts' you never get raided

### Logs

- latest.log: 
- crashlog: 

### Notes
In any other environment this is a non-issue.  Barbs spawn.  Seems that the Alps mountain within Biomes o Plenty are large enough and tall enough to spawn barbarians in some random location still inside the mountain.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by michmerr** [comment]
I've found a few barbarian campfires in caves near my above ground colony, and I found ladders that they used to climb out. Your supposition about spawning inside the mountain might be right.

**Comment by Raycoms** [comment]
Yeah that can happen
