### ISSUE TITLE
Guard Towers show more than guards as workers

### ISSUE THREAD

**Issue by smmmadden** [ldtteam/minecolonies#6441]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4 (Forge 35.1.36)
- MineColonies Version: 0.13.581 ALPHA (was latest yesterday) :-)
- Structurize Version: 0.13.113 ALPHA
- Related Mods and their Versions:

## Expected behavior

Previous builds when hiring workers to guard towers (barracks or standalone), the available workers shown only included hirable workers and other guards that have already been hired. 
## Actual behavior

Now I can see Librarians, Archer/Knights in training, workers to be hired and guards.

Here is a screen shot taken from the barracks tower (one of the four) - also checked the standalone tower and it shows more than it should but not as much as barracks since I have four towers.
![image](https://user-images.githubusercontent.com/10309346/105798533-5e635780-5f60-11eb-8d1d-848484e6ee06.png)

## Steps to reproduce the issue

1. Build barracks/towers to level 5
2. Hire some guards to fill positions
3. Go back and try to hire more once you have library built - they will be listed as well.

### Logs

- latest.log: 
- crashlog: 

### Notes

Note that my library is not near my barracks or single guard tower, nor is the Archery and Combat centers near either.  Let me know if you need anything further.  Thanks!  -Steve
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by smmmadden** [comment]
I checked the changelog for build 587 and didn't see anything listed about the UI being updated so I'm assuming its still in that build too?

**Comment by Justen-N** [comment]
This is a feature, not a bug. All training building citizens are included in the hiring lists as of 581.

**Comment by Justen-N** [comment]
and now I see why you posted the issue. That is... unfortunate. I'll see if I can't fix that( I think I know what's happening)
