### ISSUE TITLE
Inaccurate count of guard towers.

### ISSUE THREAD

**Issue by Slyklaw** [ldtteam/minecolonies#6442]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: Currently minecolonies-0.13.557-ALPHA
- Structurize Version: structurize-0.13.104-ALPHA
- Modpack: Direwolf20 1.16 version 1.3.1

## Problem description
I have L5 University, L5 Library, L5 School, and a L5 Barracks with 4x L5 Towers.

The advancement "Grand Garrison" does not complete.
![2021-01-26_16 13 47](https://user-images.githubusercontent.com/44900062/105826091-eeea7800-5ff2-11eb-8f25-7c271407508a.png)

The research "Piercing Shot" cannot be started.  With a stack of flint in my inventory, the research button says, "Missing Requirements". I was however able to complete "Cleave" which also has a similar requirement.
![2021-01-26_16 22 29](https://user-images.githubusercontent.com/44900062/105826115-f6aa1c80-5ff2-11eb-8d6a-85cd7674a6f6.png)

### Notes or related things

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
The research is because Piercing Shot and Cleave are on separate paths, you can only choose one of the paths

**Comment by Slyklaw** [comment]
Ah, yes, I didn't train Cleave. I am on the Piercing Shot path.

**Comment by Slyklaw** [comment]
"Fear" is also un-researchable.
![2021-01-27_14 32 43](https://user-images.githubusercontent.com/44900062/105958129-cd4dc700-60ac-11eb-9cb7-0999ec0ef326.png)

**Comment by Raycoms** [comment]
Do you have enough guard tower levels? (not considering barrack towers)

**Comment by Slyklaw** [comment]
What do you mean "guard towers"? Barracks towers are literally called "guard towers".
![2021-01-28_02 04 12](https://user-images.githubusercontent.com/44900062/106040724-6ca2a680-610d-11eb-9e71-1a81d449f548.png)

**Comment by Raycoms** [comment]
@ravenbuilder934 they are barracks towers, not guard towers, the lang string is off

**Comment by ravenbuilder934** [comment]
Yup I was checking on that
The lang string doesn't exist I think
I'll take a look at fixing it

**Comment by Raycoms** [comment]
Okay, when you make a PR, it can then close this issue here

**Comment by Slyklaw** [comment]
I built another guard tower, and now I can train Piercing Shot. Thanks for the clarification.

But I still cannot get the Advancement Grand Garrison.
