### ISSUE TITLE
Failed to update from 1.15.2 to 1.16.5

### ISSUE THREAD

**Issue by XakepSDK** [ldtteam/minecolonies#6443]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 
- Minecraft Version: 1.15.2
- MineColonies Version: minecolonies-0.13.585-ALPHA-universal.jar
- Structurize Version: structurize-0.13.109-ALPHA-universal.jar

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.13.587-ALPHA-universal.jar
- Structurize Version: structurize-0.13.113-ALPHA-universal.jar

## Expected behavior
Works as good as on older version

## Actual behavior
Does not work after update
I can't interact with mod blocks in my colony, it suggests to restart server or load backup
When i open main colony block, it says colony with id 1 found nearby
When i use structurize rod, it does not show my colony boundaries

## Steps to reproduce the issue
I am updating from 1.15.2 to 1.16.5

1. Play minecolonies on 1.15.2
2. Copy world to 1.16.5 server with same mods
3. Minecolonies does not update properly

### Logs

- latest.log: https://gist.github.com/XakepSDK/f8792aa8383983ce749cfdef7b2bfc15

### Notes
On 1.16.5
```
> team list
[18:08:46] [Server thread/INFO] [minecraft/DedicatedServer]: There are 2 teams: [colony_0_1], [RAIDERS_TEAM]
```

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
We don't support updating between versions for several reasons, one of them is that Mojang changed how world data is stored in 1.16
