### ISSUE TITLE
Pirate Raids - Ship Spawns but Raiders do not

### ISSUE THREAD

**Issue by KKomrade** [ldtteam/minecolonies#6447]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.13.584-ALPHA
- Structurize Version: 0.13.113-ALPHA
- Related Mods and their Versions: N/A

## Expected behavior
After pirate raid is announced and ship is spawned, the raiders should also spawn from the ships to assault the colony.

## Actual behavior
Pirate ship spawns, but there are no raiders and the status bar remains at the top of the screen.

## Steps to reproduce the issue

1. Start a colony next to ocean
2. Build up population so that a raid spawns
3. Watch as empty pirate ship spawns in a raid event

### Logs

Latest.log: https://gist.github.com/KKomrade/e5fe74ceda2397a710761ad707349881

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
How long did you wait after this? It takes I think around 30s for the waves to start or so.

**Comment by gattsuru** [comment]
Looks like a schematic scan issue; only the largest pirate variant has a Gold Block to be turned into a spawner, and it's crammed into the bottom of the ship behind a door.  The medium and small variants don't have any.

Norse ships look fine, though.

**Comment by Raycoms** [comment]
It's not based on gold blocks anymore, it's based on tags

**Comment by gattsuru** [comment]
CreativeRaiderStructureHandler's triggerSuccess still tests against `if (getWorld().getBlockState(worldPos).getBlock() == Blocks.GOLD_BLOCK && map != null)` before allowing any of the setupSpawner calls.  Are the spawner setups handled somewhere else?

**Comment by Raycoms** [comment]
Oh, you're right.

**Comment by Raycoms** [comment]
Weird, I checked right now, and all pirate and norsemen schematics had plenty of gold blocks.

**Comment by gattsuru** [comment]
May I ask what branch?  I think the issue popped up from the recent [bulk rescan](https://github.com/ldtteam/minecolonies/pull/6410): see default (1.16.5) branch on left, vs 1.15 on the right.
![image](https://user-images.githubusercontent.com/39036909/106218163-cf934c80-61a4-11eb-8042-0352f2f97940.png)

**Comment by ravenbuilder934** [comment]
If it's a schem issue I should be able to fix it

**Comment by Raycoms** [comment]
yes, 100% from the rescan then, all the boat schematics have to be rolled back, the schematic server doesn't have the updated versions from them. The updated versions were in the jar.
