### ISSUE TITLE
Colony color and show help messages settings reset to defaults on world load

### ISSUE THREAD

**Issue by TheEzzran** [ldtteam/minecolonies#6449]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.13.584 ALPHA
- Structurize Version: 0.13.113 ALPHA
- Related Mods and their Versions: Running the DW20 pack with all its mods, plus Optifine at the latest version for 1.16.5. Doubt any of those are relevant, though.

## Expected behavior

All town settings are maintained between play sessions.

## Actual behavior

Upon loading the world, the town color reverts to white and the help messages get turned off.

## Steps to reproduce the issue

1. Have a colony created.
2. Open town hall GUI and change the colony color setting to anything that isn't white. Toggle Show Help Messages on as well.
3. Save and quit to title.
4. Load back into world. Show Help should be reset to OFF, and colony color will be reset to white.

### Logs

- latest.log: https://gist.github.com/Narcisism/c1bcc51bdf08759393fcd9d12729eb8d#file-latest-log
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
How long did you wait before saving and quitting? We got certain saving cycles, so not everything you do the last second gets saved as well.

**Comment by TheEzzran** [comment]
For testing, not very long at all, admittedly. But I noticed it because I had to fix it regularly and had to track down the cause. I'll make a mental note to check it any time I have to reload the world for whatever reason in the near future.

**Comment by Raycoms** [comment]
I'll work around this code in the next weeks, so I'll give it a test then too and see what the problem is.

**Comment by TheEzzran** [comment]
Just double checked and can confirm that it happens on world load, even after a few hours of playing around in the colony.

**Comment by Raycoms** [comment]
perfect, ty

**Comment by Seba244c** [comment]
I can confirm that this happens in the newest GitHub version. I created a new colony and I changed the colony color immediately. Even after playing for a few hours, it still reset to white when leaving the world.
