### ISSUE TITLE
clipboard shows non-existant blacksmith tasks

### ISSUE THREAD

**Issue by Spongman** [ldtteam/minecolonies#6452]
[x ] I am running the latest alpha version of MineColonies and Structurize for my Minecraft version.
[ x] I checked the MineColonies/Structurize wiki and made sure my issue is not covered there.
[ x] I made sure that this issue is not a duplicate of any existing issue.
Minecraft Version: 1.15.2
MineColonies Version: -0.13.562
Structurize Version: 0.13.105

my blacksmith has no tasks or requests, but the clipboard shows a bunch of weird items:

![image](https://user-images.githubusercontent.com/1088194/106041755-1001a600-6091-11eb-952c-edd0cdfeccea.png)

those 'Cancel' buttons do nothing.

**Comment by ravenbuilder934** [comment]
1. Fill out the entire template please
2. Can you try updating? We're in the 580s now

**Comment by Spongman** [comment]
i filled out the entire template.

**Comment by ravenbuilder934** [comment]
```
## Expected behavior
<!-- What would you expect to see if this feature was working as intended? -->

## Actual behavior
<!-- What actually happens when this feature is used in its current state?
Try to give as much detail as possible here to help us properly understand the issue. -->

<!-- If you have any videos or images relating to the issue, please post them here as well. -->

## Steps to reproduce the issue

<!-- What should we do to make this issue show up in our own game?
     Try to give as much detail as possible here too so it's easier for us to reproduce this issue. -->

1. <!-- Do this -->
2. <!-- And then this -->
3. <!-- So that this happens -->

### Logs

<!-- Add your latest.log and crashlog (if you have one) to https://gist.github.com/ and put the link below. These are often important in figuring out where issues are. -->

- latest.log: <!-- USE GIST DON'T DIRECT UPLOAD PLEASE -->
- crashlog: <!-- USE GIST DON'T DIRECT UPLOAD PLEASE -->

### Notes
<!-- Add any other context about the problem here. -->

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.
```
^ all that is missing

**Comment by Spongman** [comment]
i would recommend just closing this issue if you feel it's more important to have a correctly filled out form than a functioning mod.

be grateful that i took the time to give the information i did.

**Comment by ravenbuilder934** [comment]
That information is very helpful for us to debug this. We wouldn't ask for it if it wasn't necessary.
But if you want me to ok ¯\_(ツ)_/¯

**Comment by Spongman** [comment]
personally i don't care. it's _you_ that should care if there's a bug in your code. maybe you don't? looks like it. in either case, helpful hint: your public relations is toxic.

**Comment by Raycoms** [comment]
Who is toxic is you @Spongman. This is done for free, you're not paying a cent for this. All we ask is for you to take a minute and fill out a template like a first grader could. If you don't think it's worth your time, it's not worth our time helping you.

**Comment by Spongman** [comment]
i already gave you more time than _you_ paid for.

i watched an ad before downloading this. you _are_ getting paid.

**Comment by Spongman** [comment]
remember: the quality of your code is not defined by the number of bugs marked as open in your bug tracking system, it's defined by the number of bugs in your code. marking bugs as closed without fixing them doesn't improve quality in any way.

**Comment by Spongman** [comment]
> like a first grader could

insults? nice.

**Comment by Raycoms** [comment]
Yeah, we got a cent for content that costs you 20$ elsewhere. Get lost.

**Comment by stormCup** [comment]
nice, I assist you in improving your product, you insult me, then you ban me.

keep closing those unfixed bugs, though. i'm sure one day it'll be perfect.

**Comment by Raycoms** [comment]
Open another one and I'll report you for harassment. Get lost.
