### ISSUE TITLE
Obtaining Gates for Research?

### ISSUE THREAD

**Issue by tyler489** [ldtteam/minecolonies#6453]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 
- Minecraft Version: 1.16 4
- MineColonies Version: 0.13.566Alpha
- Structurize Version:0.13.104Alpha

## Problem description
Researching Enhanced Gates require 64 wooden gates. But mechanics only craft gates if there is a request for them? are we really expected to build a gate just to pillage it multiple times for research ?
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Request gates from the postbox
