### ISSUE TITLE
Carpenter stairs recipe doesn't work when flipped

### ISSUE THREAD

**Issue by TwoPointInfinity** [ldtteam/minecolonies#6454]
EDIT : i found out what was happening (while i was writing this), i removed the spruce stairs from the sawmill recipes and then re-added it, BUT i flipped the stairs recipe. instead of it being slanted from left to right, i made the stairs recipes slanted from right to left. 
I think a bug still exists where the carpenter will not craft stairs when the recipe is slanted the other way.
[THIS RECIPE DOESN'T WORK](https://imgur.com/a/YIkNWbo)
[THIS ONE WORKS](https://imgur.com/a/JitKYSb)

- [ x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ x] I made sure that **this issue is not a duplicate of any existing issue.** I did my best to look, but only found similar issues from 2019

Exact MineColonies and Structurize versions

- Minecraft Version: 1.15.2 Valhelsia 2 (modified to update stucturize and minecolonies)
- MineColonies Version: 0.13.588 ALPHA 
- Structurize Version: 0.13.109 ALPHA
- Related Mods and their Versions: 

## Expected behavior
The warehouse has spruce logs. The Carpenter knows how to make then into planks, then half slabs, stairs, signs and a few others. When the builder needs spruce stairs but doesn't have any in their inventory or racks, they request materials to be sent to the carpenter, carpenter will have a task to make their items. once they get the materials carpenter will make planks to stairs then send them over so the builder can build.

## Actual behavior
The builder is requesting stairs to be built by the carpenter, somewhere saying they want the player to resolve it too when we have 2 couriers who can deliver things. Couriers are fine, they are making runs to everyone else to empty their racks. The carpenter does not have any requests, the sawmill does not have any tasks. Builder is stuck waiting because a courier should bring materials to the sawmill and doesn't. I don't know which job is supposed to request items from warehouse to sawmill.

## Steps to reproduce the issue

1. be me
2. and dumb
3. i think keeping this is important so other people having this issue can find it by searching what they think the issue is.

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
can you send us the log?

**Comment by TwoPointInfinity** [comment]
im sorry, but after fixing the issue we played for awhile and finding the exact moment when this was happening in the log would be very difficult and time consuming. im sure its easily reproducible, i just hoped to do my part in bug reporting would be good enough. I'm not too invested with helping this issue be fixed since i have an easy way of fixing it myself, by just flipping the recipe.

**Comment by Raycoms** [comment]
can you try with the latest alpha if you can reproduce this? I've added a fix around those things lately

**Comment by Raycoms** [comment]
fixed
