### ISSUE TITLE
Barbarians destroy environment with ladders when spawning?

### ISSUE THREAD

**Issue by Nyrox** [ldtteam/minecolonies#6456]
### Prerequisites 

- [ x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 
- Minecraft Version: 1.16.4
- MineColonies Version: 0.13.556-ALPHA
- Structurize Version: 0.13.104-ALPHA
- Related Mods and their Versions:

## Expected behavior
Not.

## Actual behavior
I have a base at the edge of my minecolony and periodically barbarians will spawn inside my base (btw. would be cool if they could maybe only spawn the surface instead of in my basement) and leave ladders and wreckage behind.

Machines (ae2 autocrafting stuff mostly so far) next to the ladders are destroyed

## Steps to reproduce the issue
1. Have a mine colony
2. Put stuff next to it
3. Get unlucky with barbarian spawns

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by someaddons** [comment]
they can break blocks when they get stuck, this is intended behaviour
