### ISSUE TITLE
Server Crash when I edit Config 

### ISSUE THREAD

**Issue by fortheps909** [ldtteam/minecolonies#6457]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: MineColonies 0.13.589 Alpha 
- Structurize Version: Structurize 0.13.113 Alpha
- Related Mods and their Versions: Forge 1.16.5 36.0.7

## Expected behavior

 Edit builder infinite resources to true and place block delay to 10 
## Actual behavior

My server crashes and wont launch calling the file corrupt

## Steps to reproduce the issue

1.Edit server config 
2.I launch 
3. My server crashes 

### Logs

- latest.log: https://gist.github.com/fortheps909/0efaa9087ac94abbb177be44aa5a3474  
- crashlog: https://gist.github.com/fortheps909/d6bfb37249343b9821cead715556fe0f

### Notes

Only crashes when I edit this mod none others

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
We did some troubleshooting in Discord and determined that this is true for any changed config setting

**Comment by Raycoms** [comment]
I'm not sure this is a Minecolonies problem at all. At first look this seems like a forge problem. Did you try different forge versions?

**Comment by fortheps909** [comment]
I have not can you tell me what version is running on the server
minecolonies host and ill just copy that one

**Comment by fortheps909** [comment]
Update i have now tried forge 1.16.4-35.1.37 and forge 1.16.4-35.1.4 as
well with same issue corrupts the file and crashes.

**Comment by Raycoms** [comment]
I can't reproduce this. I edited a bunch of files and it works fine for me. Can you delete the config file and have it regenerate on restart and then try again?

**Comment by fortheps909** [comment]
I did multiple times with same result. Sorry for the headache btw

**Comment by Edy-kun** [comment]
I think I have the same issue? This also happens with new minecolonies version
[crash-2021-02-01_01.14.31-client.txt](https://github.com/ldtteam/minecolonies/files/5901217/crash-2021-02-01_01.14.31-client.txt)

**Comment by someaddons** [comment]
can't reproduce either

**Comment by Raycoms** [comment]
I double checked this. This is not related to Minecolonies but a problem with a specific forge version or similar.
