### ISSUE TITLE
Nordic 5 library got self destructed

### ISSUE THREAD

**Issue by aaronegger** [ldtteam/minecolonies#6459]
### Prerequisites 

- [ x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: minecolonies-0.13.547-ALPHA
- Structurize Version: structurize-0.13.104-ALPHA
- Related Mods and their Versions: Valhelsia 3

## Expected behavior
Buildings should not be destroyed by themselves

## Actual behavior
Building got destroyed without any reason

## Steps to reproduce the issue
I have no Ideas how to reproduce this. I was flying around building stuff and suddendly i saw the library (nordic-5) got destructed.
![bug](https://user-images.githubusercontent.com/27417675/106266766-20e51f80-6229-11eb-9c1a-8e69574a9476.png)

**Comment by aaronegger** [comment]
I looks like that only wooden stuff got broken..
Maybe there was a fire for some reason i don't know.

If you guys have any ideas please let me know otherwise you can close this issue.

**Comment by TwoPointInfinity** [comment]
yea it looks like a fire to me too, if you can confirm a builder is destructing this then you can probably call it a bug.

**Comment by Raycoms** [comment]
Yes, looked like it burned down

**Comment by aaronegger** [comment]
I don't believe the builder was the reason for that.
After some research i think it was a lightning that set the library on fire.
But thanks for the repair feature :D
The builder fixed everything for me.
