### ISSUE TITLE
Suggestion: Minecolonies Waypoint Goggles [$15 awarded]

### ISSUE THREAD

**Issue by kedamono** [ldtteam/minecolonies#646]
### Minecolonies version

Future versions

### Requested behavior

- Wear the goggles and see all the MC waypoints from paths, light poles, invisible waypoints, etc.

### Current behaviour

- You cannot see where a waypoint is, and can inadvertently build over one or destroy it.

### Reasons for this suggestion

After placing several "invisible" waypoints, the three placeholders in a stack waypoint, I realized that I had no idea where they were afterwards. I wasn't even sure if I could place anything in their location without removing the waypoint. It would be nice to have some facility to see the waypoints either as columns of light or as differently colored squares on the ground.

The recipe could be very simple:

Stick space Stick
Pane Stick Pane
Leather Leather Leather

(It would also be nice if it gave 1 point of armor)

**Comment by xavierh** [comment]
What about to make the waypoints visible when holding the builder tools instead ?

**Comment by Raycoms** [comment]
I would say we should make a new waypoint block for that.

That block is invisible and untouchable and can be inside a block, but goes away if a block touches him.
And this block then only renders when wearing this goggles.

I think that would make this way easier

**Comment by Raycoms** [comment]
@kedamono you're up for some testing?

**Comment by kedamono** [comment]
Sure thing. I can set up a test profile and see if I can break things. :-)

**Comment by Raycoms** [comment]
Please contact me on discord so i can send you the link for it =)

2017-05-16 17:12 GMT-03:00 kedamono <notifications@github.com>:

**Comment by kedamono** [comment]
Will do.

**Comment by SulpherStaer** [comment]
This issue is closed - but as far as I know, it hasn't been implemented. How do I see waypoints?

**Comment by xavierh** [comment]
You can see them by using the builder tool and select a waypoint decoration
