### ISSUE TITLE
Client Joining Server Crash

### ISSUE THREAD

**Issue by Zilch00** [ldtteam/minecolonies#6460]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: minecolonies-0.13.480-BETA-universal
- Structurize Version: structurize-0.13.100-RELEASE-universal
- Related Mods and their Versions: OptiFine_1.16.4_HD_U_G6

## Expected behavior

Should be able to join the server without crashing
## Actual behavior

Whenever someone on client side has optifine installed, the client joins the server and then instantly crashes. Optifine works fine in Singleplayer, it just seems to be MP. Removing Optifine works, but was just wondering if there was a work around so that Optifine works since it would be nice to play with shaders.

## Steps to reproduce the issue

1. Install Minecolonies and Structurize onto 1.16.4 server
2. Install them both on Client side too with Optifine
3. Attempt to join the server

### Logs

- latest.log: https://gist.github.com/Zilch00/f35c31ad40a858392d1693d92a38b49a
- crashlog: https://gist.github.com/Zilch00/5c0915c0632b817b99980bc5f08f03cd

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Please report to Optifine.
