### ISSUE TITLE
Version concerns

### ISSUE THREAD

**Issue by TheOrionsun** [ldtteam/minecolonies#6463]
**This is not a game issue**....Just a question on versions. The new version release on Curseforge is 0.13.592-Alpha, however the changelog is version 0.13.595-Alpha(just updated 1/29). Also there is no Structurize version, (noted in Changelog), that the new version supports as has been posted in the past. I find that to be very helpful so I know what version of Structurize to update to....

Thank you for you time and the awesome mods!!

### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.13.592-Alpha (On Curseforge)
- Structurize Version: 0.13.113-Alpha (Last know version working with MineColonies)

### Notes or related things

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Something seems wrong with the buildsystem

**Comment by Raycoms** [comment]
Can't find the problematic file, can you link it for me?

**Comment by TheOrionsun** [comment]
Looks good this morning...

Thank you!
