### ISSUE TITLE
Fisher not...magnetic? enough?

### ISSUE THREAD

**Issue by Talyda** [ldtteam/minecolonies#6464]
- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

- Minecraft Version: 1.16.5
- MineColonies Version: one ending in .592
- Structurize Version: .113
- Related Mods and their Versions:

## Expected behavior
Fisher "sucked up" fish they caught

## Actual behavior
The fisher is working MUCH better now with the fixes, but I noticed last night that every now and then when I walked past their hut (I was keeping  an eye on them to see if the fixes fixed them) I would end up with fish in my inventory. So this morning I have been watching him fish. Occasionally he sends the line out, does all the fishing things, then when he catches a fish, it and the XP orb both just don't get sucked in to him. They're left floating around in odd places

## Steps to reproduce the issue

Use the fisher.
It doesn't happen on every cast.

### Notes
TBH not sure if it's really a bug - or just an oddity, but since changes had just been made, thought it was worth mentioning =)

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
![image](https://user-images.githubusercontent.com/17323101/106343372-ecd73080-62f4-11eb-999c-e2b92c9c3dd6.png)
It actually happened while I was typing that out - you can see two light blue dots just below and to the right of centre of the image, that is a puffer fish and a cod that he hasn't sucked up - they've both landed on the ground 2 - 3 blocks behind him

**Comment by someaddons** [comment]
ye he is a bit derpy, though as long as he gets most it is fine citizens are not supposed 100% functional robots afterall
