### ISSUE TITLE
level 3 university (wooden) requires grass

### ISSUE THREAD

**Issue by gabecupino** [ldtteam/minecolonies#6466]
Builder won't continue upgrading wooden university to level 3 until they have 38 grass. Tried manually adding dirt blocks to the worker's inventory, but that didn't work.

**Comment by ravenbuilder934** [comment]
Level 3 is advanced enough that it's probably intentional; use silk touch. Also, fill out the template next time.

**Comment by gabecupino** [comment]
I can't use silk touch on grass, it breaks into seeds even when using silk touch. Can you send a link to the template please?

**Comment by ravenbuilder934** [comment]
Oh, the builder needs grass itself, not grass blocks? Use shears to break it then
And the template should've shown up when you clicked on New Issue; how'd you get here?

**Comment by gabecupino** [comment]
Thanks, using the sheers allowed me to gather the grass.

I tried to click on new issue while not logged in. It redirected me to login. After logging in, I was given a blank text box to provide details about my issue.

**Comment by ravenbuilder934** [comment]
Hmm
Probably a github bug though, nothing we can do
