### ISSUE TITLE
Pirate Ship raid spawning under water

### ISSUE THREAD

**Issue by KKomrade** [ldtteam/minecolonies#6468]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.13.596-ALPHA
- Structurize Version: 0.13.113-ALPHA
- Related Mods and their Versions: 

## Expected behavior
Pirate Ship spawns on surface

## Actual behavior
Pirate ship raid spawns at bottom of ocean

## Steps to reproduce the issue
1. Wait for a raid
2. Pirates of the Carribean minecolonies edition

### Notes
![image](https://user-images.githubusercontent.com/74999353/106371824-4441c480-6326-11eb-97d7-54bc7cd250b7.png)

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
@ravenbuilder934 I guess now the ships on the schematic server are missign the ground level tag?

**Comment by ravenbuilder934** [comment]
@Raycoms do I need to have the tag on each ground level block? or only one?

**Comment by Raycoms** [comment]
only groundlevel block per schematic, how it was in the beginning as well.
