### ISSUE TITLE
Workers tp to unsafe positions

### ISSUE THREAD

**Issue by Thomasdavid097** [ldtteam/minecolonies#647]
### Minecolonies version
one on the server rn, 0.6.6
version X.X.XXXX or curse X.X.XX
server curse.
### Expected behavior
farmer,(might be all workers not really tested...) tp underground in under positions... 

(just think about this as dirt..: https://puu.sh/ugjsQ/f4057c67fb.png )
- XXX

### Actual behaviour
^
- YYY

### Steps to reproduce the problem
eh......... make it so he doesn't get randomly put in a unsure hole where he ends up getting killed.
1. XYZ
2. ZYX
3. ...
4. Profit

**Comment by marvin-bitterlich** [comment]
this is really stretching the template. Please fill it out or clean it up

**Comment by Raycoms** [comment]
The "tp if stuck" doesn't tp them to a save position they just tp to the
next possible which might be underground or mid air depending on the search
of the pathfinding.

2017-02-23 10:59 GMT-03:00 Thomasdavid097 <notifications@github.com>:
