### ISSUE TITLE
Baker can't stock cake batter

### ISSUE THREAD

**Issue by uecasm** [ldtteam/minecolonies#6470]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: 0.13.596-ALPHA-universal
- Structurize Version: 0.13.113-ALPHA-universal

## Expected behavior

After upgrading a Baker to level 2, they gain the recipe for cake and cake batter.  I would like to be able to keep some minimum stock of one or both of these items.

## Actual behavior

The option to keep these as minimum stock is missing from the hut's third page.  It is still possible to request them from the postbox, however.

## Steps to reproduce the issue

1. Make a level 2 baker.
2. Look at their recipe list, see that they now know how to make cake batter and cakes.
3. Look at their minimum stock list, see that they cannot be told to stock either cake batter or cakes.

### Logs

Not relevant here.

### Notes

When I asked on Discord, I was told that not showing Cake might be intentional (since colonists can't eat cake anyway?), but that not showing Cake Batter probably is not.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
@Mekle001 any idea?

**Comment by Mekle001** [comment]
Very odd. I'll take a look.

**Comment by Mekle001** [comment]
Ok, the reason this is happening is that the prestock list is only populated with items that can be eaten, or that when run through a furnace can be eaten.

That means neither cake or the batter will show up. I'm going to add another clause for the primary output of recipes.
