### ISSUE TITLE
former archer in training going to bed at archery ground

### ISSUE THREAD

**Issue by Moobien** [ldtteam/minecolonies#6471]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.13.596-ALPHA-universal
- Structurize Version: structurize-0.13.113-ALPHA-universal
- Related Mods and their Versions:

## Expected behavior

Citizen with changed job sleep in a house.
## Actual behavior

So I had a citizen levelling up in the archery hut, and then decided to use them as a courier. so I hired them directly from the courier hut. Was flying around and noticed the courier had decided they would go to bed at the archery ground instead of a house.

## Steps to reproduce the issue

1: put citizen in archery training ground
2) hire that citizen directly to another building.

1. 
2. 
3. 

### Logs

- latest.log: https://gist.github.com/Moobien/ff496091966ea2efb344e3ba34f84f49
- crashlog: 

### Notes

https://imgur.com/a/FQPYLDb - lvl 1 fortress archery training ground.
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Does this still happen? There were changes related to it
