### ISSUE TITLE
Cannot create colony

### ISSUE THREAD

**Issue by A-SaltyTaco** [ldtteam/minecolonies#6475]
I have tried making a colony, I put the townhall down and tried to make a colony. It said I need a supply camp/ship. To get a supply camp/ship It needs to be in a colony. This is in multiplayer 1.16.4 BTW. It works in singleplayer 1.16.4.

**Comment by Justen-N** [comment]
Please follow the issue template.

**Comment by Raycoms** [comment]
You don't need a colony to get a supplycamp/ship btw.

**Comment by Raycoms** [comment]
You just craft and place it.
