### ISSUE TITLE
Mod conflict with Areas?

### ISSUE THREAD

**Issue by Moleculor** [ldtteam/minecolonies#6480]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: v596
- Structurize Version: v113
- Related Mods and their Versions: Areas v1.1

The Medieval Dark Oak warehouse comes with a sign out front telling you an option for where to place a courier hut. 

I used the build tool to place a courier hut block in the exact same block position as the sign out front.

In multiplayer, I was disconnected. When reproducing it in singleplayer (which is what the attached logs are from), I crashed. 

Logs suggest a conflict between Areas and Minecolonies, so I'm reporting it to both. 

### Logs

https://gist.github.com/Moleculor/b30b0b76ba70bb92c09167a01c76fa27

### Related

https://github.com/ricksouth/serilum-mc-mods/issues/403

## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
double checked, unless the areas dev can convince me otherwise, it seems like they're trying to access the sign after the building replaced it already.

**Comment by Raycoms** [comment]
(Will reopen if they can convince me that the fault is with us here)
