### ISSUE TITLE
Pirate ship spawned under water with no pirates 

### ISSUE THREAD

**Issue by Sleeclow** [ldtteam/minecolonies#6483]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.13.596-ALPHA-Universal
- Structurize Version: 0.13.113-Alpha-Universal

## Problem description
 The colony got attacked by a pirate ship. but the ship spawned underwater/underground, with no spawners on it or pirates at all

### Notes or related things

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Duplicate, PR with fix pending
