### ISSUE TITLE
Upgrading to Dark Oak Town Hall 5 Frozen

### ISSUE THREAD

**Issue by Geoffrotism** [ldtteam/minecolonies#6484]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: latest
- MineColonies Version: minecolonies-0.13.589-ALPHA
- Structurize Version: structurize-0.13.113-ALPHA-universal
- Related Mods and their Versions: 1.16.4

## Expected behavior
TownHall 5 finishes getting built

## Actual behavior
Most of the upgrade happens, but gets stuck at 90% with the builder standing on the townhall main block and doing nothing (he needed 2 armor stands and 2 full sets of gold armor and 2 full sets of leather armor). These were given to him and he is still just standing there.

Some more weirdness, is that when the worker goes to sleep the required items list is asking for more stuff. But during the day the item list is showing as needing nothing else.

![image](https://user-images.githubusercontent.com/5430964/106771001-8744b600-660c-11eb-8bc7-f135f6e546ac.png)
![image](https://user-images.githubusercontent.com/5430964/106771157-acd1bf80-660c-11eb-9092-a1e435468d75.png)
![image](https://user-images.githubusercontent.com/5430964/106771223-bce99f00-660c-11eb-8997-fd16c68a8406.png)
![image](https://user-images.githubusercontent.com/5430964/106771281-cbd05180-660c-11eb-84f1-6a154bdf7ae0.png)

## Steps to reproduce the issue
Make dark oak town hall 4
try to upgrade to town hall 5

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Geoffrotism** [comment]
Ah ok, giving him the sunflowers and item frame allowed him to finish. So the bug should really be that the builder is not requesting those during the day/the builders hut does not request those items during the day (only at night).

**Comment by shhStealth** [comment]
Thank you very much for this! I was having the exact same issue and this finally helped.

**Comment by Raycoms** [comment]
Fix pushed through
