### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by ergoplato** [ldtteam/minecolonies#6486]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.13.598-ALPHA
- Structurize Version: 0.13.127-ALPHA

## Problem description

Latest version of MineColonies does not accept latest version of Structurize (it requires 0.13.113). Since it is a hard dependency, it should really check if you have a required version or better.

### Notes or related things

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
> Since it is a hard dependency, it should really check if you have a required version or better.

No, we can't really do that. Sometimes (as happened with the recent versions of Structurize) a Structurize update breaks MineColonies, and we need to manually fix MineColonies to accept it. This way, it just errors instead of crashes.

**Comment by someaddons** [comment]
not an issue, minecolonies tells you exactly the structurize version it does work with
