### ISSUE TITLE
[1.11-0.6.2919] can't place supply ship after colony delete

### ISSUE THREAD

**Issue by kreezxil** [ldtteam/minecolonies#649]
### Minecolonies version

1.11-0.6.2919

### Expected behavior

- use /mc colony delete ID
- be able to place a new supply ship

### Actual behaviour

- use /mc colony delete ID
- craft supply ship
- try to place it
- get told you have already placed it

### Steps to reproduce the problem

see behavior

**Comment by Raycoms** [comment]
Not a bug. Supplyships contain a lot of free materials. Every player can
only place one supplyship. If you want to place another you have to reset
the achievement.
If you want to move your colony, mine your building blocks before deleting
it.

2017-02-24 12:57 GMT-03:00 kreezxil <notifications@github.com>:

**Comment by kreezxil** [comment]
I would think that /mc colony delete ID is or should be an op command, in which case it is to be used at the op or staff's discretion. Therefore when a person of sufficient power uses it, the colony it is being used on, should allow the previous owner to place another supply ship. It makes no sense to have this command and not have that other stuff.

**Comment by Raycoms** [comment]
you can unlock /mc colony delete in the config for not admins as well I
think.
The problem is that people will spam their supplyships and gain unfair
advantages (a lot of wool, gold blocks etc)
There are a lot of achievement mods which allow you to remove the according
achievement.

2017-02-24 14:01 GMT-03:00 kreezxil <notifications@github.com>:

**Comment by sandalle** [comment]
Still an issue in 1.15.2-0.10.716. If you're OP, you aren't usually restricted in resources as you can just cheat stuff in anyways. Even running this command:
`/advancement revoke <user> from minecolonies:minecolonies/root` (deleted 47 advancements from that user) did not allow a user to be able to re-create a colony after it was deleted with the command:
`/minecolonies colony delete 1 true delete buildings`. I then tried cheating in a **Town Hall**, but placing it using the Build GUI doesn't work, but placing it directly did, though I got none of the starting buildings.

**Comment by Raycoms** [comment]
there is a recipe for the townhall too with buildtool middle and top and rest planks
