### ISSUE TITLE
Restaurant medival oak alternative level 1 does not have a floor

### ISSUE THREAD

**Issue by Sindorman** [ldtteam/minecolonies#6492]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.565-ALPHA-universal
- Structurize Version: 0.13.105-ALPHA-universal
- Related Mods and their Versions: I am not sure if the mod pack I am using has related mods. Link to the modpack in the notes.

## Expected behavior
Restaurant MedivalOakAlternative level 1 to have flooring or use the existing ground.

## Actual behavior
Restaurant MedivalOakAlternative level 1 had barely any floors. The builder just removes the whole floor layer and places few grass blocks. Watch the screenshot:
![2021-02-04_11 36 42](https://user-images.githubusercontent.com/25555314/106946564-1cfc4600-66de-11eb-9476-9d02486069eb.png)

## Steps to reproduce the issue

1. Start Building MedivalOakAlternative restaurant(cook) level 1
2. Watch builder remove the ground floor in the whole area
3. Watch builder finish the structure with no floor level except for few grass blocks

### Logs

- latest.log: 
- crashlog: 

### Notes
I am using Life in village 2 [modpack](https://www.curseforge.com/minecraft/modpacks/life-in-the-village-2)

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
#5006

**Comment by Sindorman** [comment]
update: Level 2 fixes the inside floor, but the outside is still missing some
