### ISSUE TITLE
Builder not placing armor stands/armor

### ISSUE THREAD

**Issue by KKomrade** [ldtteam/minecolonies#6493]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.13.602
- Structurize Version: 0.13.113
- Related Mods and their Versions:

## Expected behavior
In the preview the structure shows and requires armor stands and armor.

## Actual behavior
The builder places everything except for the armor stands and armor pieces.

![2021-02-04_12 51 49](https://user-images.githubusercontent.com/74999353/106948193-a0bb3000-66e8-11eb-8684-b8eabebed0ca.png)

## Steps to reproduce the issue
1. Request upgrade to level 5 Fortress Guard tower.
2. Give builder materials
3. Watch as the builder does not place armor stands.

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by RealTrueDeviL** [comment]
Well, I don't know how to 'thumbs up' don't see the option..

However, got the same issue, in All The Mods 6 v1.5.1, (596 Alpha) trying to upgrade the University to lvl 4, and builders just stand there doing nothing, because they are not placing armour stands & armour..

**Comment by silicon11** [comment]
I also have the issue with the builder not playing armor stands and armor. My builder is standing doing nothing when he is trying to do the last parts of the asian barracks 5. Once I placed the armor stands the builder was able to finish the structure albeit without the armor on the stands. I am running version minecolonies-0.13.589-ALPHA-universal.jar

**Comment by AVFD** [comment]
I also have the same issue, but to builder is trying to upgrade University to 3 (wooden schematic).

**Comment by Raycoms** [comment]
Fixed with newest
