### ISSUE TITLE
Increase Min Spawn Distance

### ISSUE THREAD

**Issue by Geoffrotism** [ldtteam/minecolonies#6494]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

Minecraft Version: latest
MineColonies Version: minecolonies-0.13.589-ALPHA
Structurize Version: structurize-0.13.113-ALPHA-universal
Related Mods and their Versions: 1.16.4

## Expected behavior
Code comments are incorrect for distance calculations: 

https://github.com/ldtteam/minecolonies/blob/0a4e2749bd888ad88f3f307985c929942dd5e18b/src/main/java/com/minecolonies/coremod/colony/managers/RaidManager.java#L514-L526

I would ask that either the comments be made to match distance changes made in #5726

Alternatively, I'd like to bump the min distance back up to 35 since distance is calculated in a circle centered at the buildings special interaction block (meaning that large structures like the true dwarven mine can have spawns basically inside it.)

in the screenshot below, you can see the mine block through the opening. The cobble stone I placed is located 17x17 blocks away sqrt[(17^2)+(17^2)] = 25. so for a lvl 1 mine, a spawn could happen just 2 squares away which seems way too close for me. 🤷‍♂️ 

![image](https://user-images.githubusercontent.com/5430964/106970096-328f6100-671a-11eb-88e2-9350b9834d8b.png)

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
fixed
