### ISSUE TITLE
Builders won’t build due to apparent line of sight issue

### ISSUE THREAD

**Issue by DarkIlluminatus** [ldtteam/minecolonies#6496]
- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

- Minecraft Version: 1.16.5
- MineColonies Version: 0.13.602-ALPHA
- Structurize Version: 0.13.113-ALPHA (not the latest, but requires by the latest nine colonies)

## Problem description

I have an issue with the way I use this mod. I like to put my initial builders (the first four citizens that spawn) at the four corners of the town hall’s claim area, this causes them to stop working if I’m not constantly circling (and even if I am) and nothing gets built, they keep moving from their build site to their hut and back again. Could you please include a sort of chunkloader to ensure that the workers continue working when I am not in the area? I play in single player.

### Notes or related things
All covered in problem description.

**Comment by Raycoms** [comment]
a) You can turn on chunk loading in the config file
b) Optifine also causes this problem when you use their lazy chunkloading setting.
