### ISSUE TITLE
Planter plants mid-air

### ISSUE THREAD

**Issue by meffie96** [ldtteam/minecolonies#6497]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.562
- Structurize Version:  0.13.105
- Related Mods and their Versions: Life in the village 2 Modpack

## Expected behavior

Planter plants sugar cane next to the pond (medival oak, lvl 1 + 2, maybe also on higher levels).

## Actual behavior

The planter instead goes to the opposite side of the building (we have no building there yet) and tries to plant the sugar cane in mid-air. What does not work of course. 

## Steps to reproduce the issue

1.  Build a medival oak planter and hire someone to work there.
2.  Tell him to plant sugar cane and give some to him.
3.  He will go outside and plant it in mid-air.

### Logs

- latest.log: 
- crashlog: 

### Notes

If necessary, i will make a video and / or upload the log file.
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Should be fixed in a newer version.

**Comment by meffie96** [comment]
Thank you! :)
PS: The mod is really fun to play.
