### ISSUE TITLE
[1.11-0.6.2919] can't place supply ship near large body of water

### ISSUE THREAD

**Issue by kreezxil** [ldtteam/minecolonies#650]
### Minecolonies version

[1.11-0.6.2919]

### Expected behavior

- place supply ship

### Actual behaviour

- the game repeatedly tells me that I have to find a large body of water

### what I discovered

the ship apparently is set in specific orientation, so that while you the player are look at a large body of water that can hold the ship, the mod code has the ship in a specific orientation which makes it think that ship is going to run ashore if placed.

The solution is to build a pier out into the water and place the ship, the ship will then generate to the left or the right of the pier instead of perpendicular in front of you as expected.

**Comment by Raycoms** [comment]
Every direction should work. But the code searches in all 4 directions for
a body of 32*20 in a distance of 3-5 from the placement point.
Which might create problems if the shore is a bit curved.

2017-02-24 14:05 GMT-03:00 kreezxil <notifications@github.com>:
