### ISSUE TITLE
colonists do not use restaurant. Colony reports hunger as constant issue

### ISSUE THREAD

**Issue by Sindorman** [ldtteam/minecolonies#6500]
### Prerequisites

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.565-ALPHA-universal
- Structurize Version: 0.13.105-ALPHA-universal
- Related Mods and their Versions: I am not sure if the mod pack I am using has related mods. Link to the modpack in the notes.

## Expected behavior
Colonists use restaurant and not be hungry.

## Actual behavior
Not sure what causes it. But my restaurant has enough food and has worker there working. Yet I personally never seen anyone go to it, and when I check colony stats in the town hall or ask villagers about stats they all indicate Hunger as red all the time.

Screenshot of resteraunt chest
![2021-02-05_09 05 37](https://user-images.githubusercontent.com/25555314/107065325-80937b80-6791-11eb-94a9-f7073eefa1ab.png)

Screenshot of the cook's colony stats indicating hunger as red
![2021-02-05_09 05 45](https://user-images.githubusercontent.com/25555314/107065330-81c4a880-6791-11eb-9a3e-803dd63aee06.png)

## Steps to reproduce the issue

1. Have a restaurant with food
2. Watch colony report hunger as an issue

### Notes
I have checked if this is a duplicate. I have seen this has been an issue before and not sure if it was fixed yet. I am pretty sure my version is after the fix has been made for hunger issues. 

I also wonder if this could be related to me using restaurant medivaloakalternative which seems to have a broken scheme. But the Cook is able to get inside, and so is deliveryman, even with broken floors, so colonists should be able too?

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
You're over 30 versions behind, and iirc the hunger (in the town hall) issue was fixed *after* your version. Please update.

Colonists also only go to the restaurant when they're starving, but then they take some extra food.
