### ISSUE TITLE
My AI has run into an issue!

### ISSUE THREAD

**Issue by valveo** [ldtteam/minecolonies#6504]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16
- MineColonies Version: minecolonies-0.13.601-ALPHA-universal
- Structurize Version: structurize-0.13.113-ALPHA-universal
- Related Mods and their Versions: 

## Actual behavior
Player on my server (direwolf20 mod pack) reported me error: 
" Kieran V. Kennedy: My AI has run into an issue! Please locate the latest .log file (or contact the server owner if playing on a server) and send it to the MineColonies authors with this message."

### Logs

- latest.log: https://gist.github.com/valveo/dd48318bf2dcdd47bcdd042b1be1c2c6

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
I'll close this because the same problem as the deliveryman/courier issue where there is an issue of this already.

**Comment by ravenbuilder934** [comment]
(#5672)
