### ISSUE TITLE
crash server minecart

### ISSUE THREAD

**Issue by laboriens** [ldtteam/minecolonies#6506]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 
mohib 1.16.5-345 ( forgeVersion, 36.0.13)

- MineColonies Version:
minecolonies 0.13.602  (minecolonies-0.13.602-ALPHA-universal.jar)

- Structurize Version:
- structurize-0.13.113-ALPHA-universal.jar  (because we can't put another version than it because minecolonies refuse the versions above it)
- 
- Related Mods and their Versions:

## Steps to reproduce the issue

to place rails and that the colonies have the rail research (server side (solo no crash and it works))

1. 
2. 
3. 

### Logs

- latest.log:  https://textup.fr/527076P6
- crashlog:  https://textup.fr/527072a2

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

crash server cause minecart

log crash

https://textup.fr/527072a2

**Comment by ravenbuilder934** [comment]
Fill out the template please

**Comment by laboriens** [comment]
> Fill out the template please
done

**Comment by laboriens** [comment]
> Fill out the template please

done

**Comment by laboriens** [comment]
I try with server forge-1.16.5-36.0.15.jar to see if it comes from mohist.

**Comment by laboriens** [comment]
I'm going to contact mohist and give them the link of this problem because just with the forged server I have no error or crash so it comes from mohist.

**Comment by Raycoms** [comment]
I double checked it, really not our fault.
