### ISSUE TITLE
Version incorrect after updating both mod and structurize 

### ISSUE THREAD

**Issue by Jigsaw0213** [ldtteam/minecolonies#6507]
[crash-2021-02-07_02.03.01-fml.txt](https://github.com/ldtteam/minecolonies/files/5938578/crash-2021-02-07_02.03.01-fml.txt)

**Comment by Jigsaw0213** [comment]
not sure if that is intended

**Comment by Raycoms** [comment]
1) Please fill out the full template the next time
2) Yes intended, each minecolonies version asks for a specific structurize version

**Comment by laboriens** [comment]
you are obliged to have structurize with version 0.13.113-ALPHA the versions above minecolonies refuse them

**Comment by ravenbuilder934** [comment]
We do have it. On Curseforge, go to the Files tab, and then View All

**Comment by Jigsaw0213** [comment]
ok yea was just making sure its intention, seems funny to update the mods but still use the older core, must be for good reason though, thanks guys for the quick response
