### ISSUE TITLE
Bug with Bake/Baker does not work

### ISSUE THREAD

**Issue by Snaggl3t00th420** [ldtteam/minecolonies#6508]
I play on the minecolonies-0.13.480-BETA-universal.jar with structurize 0.13.100 on 1.16.4 forge version 35.1.4 
The baker does not owrk but i tried every help from the wiki step by step to debug him

### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.6.4
- MineColonies Version: minecolonies-0.13.480-BETA-universal.jar
- Structurize Version: structurize 0.13.100
- Related Mods and their Versions:Forge 35.1.4 Simple Ores 2 16.4 2.4.3.10 guardvilliagers1.1.8 valhelisa structures 16.0.05 simplecorelib 1.16.4-2.0.4.3

## Expected behavior
baker bakes breed i guess

## Actual behavior
 does nothing but also leaves his workplace loaded colony backup an restartet request system but still nothing tried to hire different persons choose different fuel tried to hire some one different oder restart the worker everything from the wiki

## Steps to reproduce the issue

1. build baker in medival oak /alternativ/wood every time nothing happend
2. nothing 
3. 

### Logs

- latest.log: https://gist.github.com/Skeletonlp/759e6201dadcc01e764db6a05de26d8b
- crashlog: have non

### Notes
in other colonies of the server doesnet work the fisher man or the saw mill to

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MatthiasMann** [comment]
You are on a very old version - latest at this time is 602-alpha.

**Comment by Snaggl3t00th420** [comment]
could you send an link for an download
because on curseforge i it the newest from 29 november
what it the differnce between alpha beta anfd release

**Comment by Snaggl3t00th420** [comment]
i updatet to the latest version still dosnt work

**Comment by ravenbuilder934** [comment]
In MineColonies, there is *no* difference between alpha/beta/release
Also, for the baker to work, someone has to be requesting bread/etc. Try requesting some from the postbox
