### ISSUE TITLE
Immediate building tool crash

### ISSUE THREAD

**Issue by oleblancpellerin** [ldtteam/minecolonies#651]
### Minecolonies version

version 0.6.2849

### Expected behavior

- When I right click on the ground with the building tool, and click decorations and then walls, it should change category.

### Actual behaviour

- Minecraft crashes immediatly.

### Steps to reproduce the problem

1. Right click on the ground with the building tool
2. Click on "decorations"
3. Click on "walls"
4. Crash

[crash-2017-02-24_14.45.56-client.txt](https://github.com/Minecolonies/minecolonies/files/800347/crash-2017-02-24_14.45.56-client.txt)

**Comment by Raycoms** [comment]
This coremod overwrites functions we need for rendering:

at
ValkyrienWarfareBase.PhysicsManagement.DimensionPhysObjectManager.getObjectManagingPos(DimensionPhysObjectManager.java:89)
at
ValkyrienWarfareBase.CoreMod.CallRunner.onGetDistanceSq(CallRunner.java:309)
at
net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:122)

That's probably also related to another similar issue we have with that mod.

2017-02-24 16:58 GMT-03:00 djeezuss <notifications@github.com>:
