### ISSUE TITLE
Maven repository for 1.16?

### ISSUE THREAD

**Issue by uecasm** [ldtteam/minecolonies#6511]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.13.602-ALPHA
- Structurize Version: 0.13.113-ALPHA

## Problem description

The maven repository linked in #4343 only contains builds for 1.15 (and older?); there are no builds for 1.16 there.

For example, 0.13.603-ALPHA is present, but 0.13.602-ALPHA and 0.13.610-ALPHA are not.

### Notes or related things

Are these being uploaded somewhere else or is there an error in the build process?

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Nightenom** [comment]
Try this, the base would be <https://ldtteam.jfrog.io/artifactory/mods-maven>
<https://ldtteam.jfrog.io/artifactory/mods-maven/com/minecolonies/minecolonies/0.13.603-ALPHA/>
edit: it only contains our mods since Nov/2020, Orion probably changed something in wrong way I guess

**Comment by uecasm** [comment]
That's the one I linked to.  It does have recent builds (from last week, even), but only the 1.15 builds, no 1.16 builds.

**Comment by Nightenom** [comment]
> That's the one I linked to. It does have recent builds (from last week, even), but only the 1.15 builds, no 1.16 builds.
> For example, 0.13.603-ALPHA is present, but 0.13.602-ALPHA and 0.13.610-ALPHA are not.

Do you see the second link? it contains 0.13.603-ALPHA..
also it contains this <https://ldtteam.jfrog.io/artifactory/mods-maven/com/minecolonies/minecolonies/0.13.595-ALPHA/> etc

**Comment by uecasm** [comment]
I am aware.  Did you notice that 603 is in fact a 1.15-only build?  (This would be more obvious if you had a better naming convention, but it is what it is.)

**Comment by Nightenom** [comment]
> I am aware. Did you notice that 603 is in fact a 1.15-only build?

Oh, sorry, you confused me, so do our numbers...

**Comment by Nightenom** [comment]
@OrionDevelopment the artifactory builds are missing artifacts (probably since your latest build.gradle rewrite) <https://ldtteam.jfrog.io/ui/builds/LetSDevTogether_Minecolonies_Alpha_Release/0.13.610-ALPHA/1612749783622/published>
And also we have some weird error from ForgeGradle <https://buildsystem.ldtteam.com/viewLog.html?buildId=67666&buildTypeId=LetSDevTogether_Minecolonies_Alpha_Release&tab=buildLog&filter=all&state=434%2C442%2C450%2C100%2C423&_focus=136#_state=434,442,450,100,423>
