### ISSUE TITLE
Archers & Knights in training do not go to bed or train

### ISSUE THREAD

**Issue by joolicious** [ldtteam/minecolonies#6512]
### Prerequisites 

- [ x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 610 Alpha
- Structurize Version: 113 Alpha
- Related Mods and their Versions: ATM6 1.5.1

## Expected behavior

Archers and Knights in training train during the day and go to their beds within the Combat Academy and Archery Academy at night.

## Steps to reproduce the issue

1. Build Archery and Combat Academy
2. Assign Knights and Archers in training
3. Knights and Archers in training wont train or sleep

### Logs

- latest.log: https://gist.github.com/joolicious/7131bce8f0a97eaa17cf94a914afe704
- crashlog: N/A

### Notes
N/A

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Moobien** [comment]
I have seen my archer in training shooting at his target, but I can confirm they don't go to bed. 
https://cdn.discordapp.com/attachments/741531816422539384/808462832332308540/2021-02-09_09.21.56.jpg

**Comment by Sandriell** [comment]
I can add to this to say that (on 610) I have no issues with my archers training, but my knights will not train if I hire more than one at a time- then they will just stand around the hut block forever.

Can confirm that neither knights or archers will use the beds when sleeping.
