### ISSUE TITLE
Smelter smelting disabled smeltables

### ISSUE THREAD

**Issue by Moobien** [ldtteam/minecolonies#6513]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 609
- Structurize Version: 113
- Related Mods and their Versions:

## Expected behavior

Smelter doesn't put coal into furnace when it is disallowed

## Actual behavior

smelter puts coal into cooking slot and turns it into Extreme Reactors Graphite, coal smelting is turned off in the huts gui.

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

https://cdn.discordapp.com/attachments/741531816422539384/808451020127731772/2021-02-09_06.12.23.jpg
https://cdn.discordapp.com/attachments/741531816422539384/808451021847396392/2021-02-09_06.12.28.jpg
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Moobien** [comment]
correction using 610

**Comment by Raycoms** [comment]
How does the smelter get the coal? Are you giving it to him?

**Comment by Moobien** [comment]
it was allowed for fuel so was requesting coal for fuel and was filling both slots on his furnace

**Comment by Moobien** [comment]
but was set to off as smeltable
