### ISSUE TITLE
planter demanding plantables that are set to not be planted

### ISSUE THREAD

**Issue by Moobien** [ldtteam/minecolonies#6514]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 609
- Structurize Version: 113
- Related Mods and their Versions:

## Expected behavior

planter only asking for items it is allowed to plant.
## Actual behavior

my planter is set to not plant bamboo, worker demanded bamboo and then doesn't plant it once supplied.

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

https://cdn.discordapp.com/attachments/741531816422539384/808454201767231518/2021-02-09_08.47.28.jpg
https://cdn.discordapp.com/attachments/741531816422539384/808454203503542322/2021-02-09_08.47.31.jpg
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Moobien** [comment]
correction. using version 610

**Comment by Raycoms** [comment]
The planter has two modes depending on the research. Are you sure you got bamboo disabled?

**Comment by Raycoms** [comment]
When you research the dual mode, the displayed option becomes the "disabled" one.

**Comment by ravenbuilder934** [comment]
yup the screenshot has "NOT planting:"
unless that's the issue actually and it should be saying "Planting:"

**Comment by Raycoms** [comment]
@ShadowProtocol maybe it was inverted?

**Comment by Moobien** [comment]
plant 2 had been researched so the not planting was correct. he never planted the bamboo, just kept it in his inventory

**Comment by Raycoms** [comment]
And after canceling the request he re-requests it again?

**Comment by Moobien** [comment]
I didn't try. let me load up that world
 I took the bamboo from him that I gave him and he hasn't asked for more

**Comment by Raycoms** [comment]
Like, after switching in the UI, it might take a little bit until he doesn't request it anymore (30s or so) and existing requests won't be cancelled.

**Comment by Moobien** [comment]
there was no further request at all

**Comment by Raycoms** [comment]
Should be solved now
