### ISSUE TITLE
Recipes being deleted from crafters (Failure to remove recipe)

### ISSUE THREAD

**Issue by ItsmeCurly** [ldtteam/minecolonies#6515]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: 0.13.566-ALPHA-universal
- Structurize Version: 0.13.104-ALPHA-universal
- Related Mods and their Versions:

## Expected behavior

Recipes save correctly and can be appended to/deleted from crafters.

## Actual behavior

Creating recipes in a crafter (sawmill in this case) and then deleting them causes the recipes to all disappear from the crafter. This has happened with as much as 50 recipes in my testing, and typically is caused when clearing 1-3 recipes from the list of recipes.

## Steps to reproduce the issue

1.  Create recipes (I did 5 recipes of various planks).
2.  Delete one or two recipes from the list.
3.  All recipes disappear from the list.

### Logs

- latest.log:  https://gist.github.com/ItsmeCurly/8c2ec72a3132d20e932b718e8a519f7c
- crashlog: 

### Notes

On lines 6603-6605 of the latest.log it references [minecolonies/]: Failure to remove recipe, please tell the mod authors about this, which then prompts the recipes all being deleted.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
This was already fixed, update (you're about 40 versions behind)
