### ISSUE TITLE
All Raid Mobs Wont Spawn

### ISSUE THREAD

**Issue by iMilui** [ldtteam/minecolonies#6517]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.13.602
- Structurize Version: 0.13.113
- Related Mods and their Versions:

## Expected behavior
 Barbarians should spawn when using a barbarian spawn egg in creative mode. Raiders should spawn when using the raid colony command. 

## Actual behavior
 Raids do not spawn, and no raid mobs spawn from spawn eggs e.g. barbarians, pharaohs, amazons, pirates etc

## Steps to reproduce the issue

1.  Creative mode
2.  Attempt to spawn in barbarian using spawn egg

### Notes
 In a creative world, I have attempted to spawn each raid mob using a spawn egg, the mob flashes and disappears almost instantly. Game difficulty is set to normal, I have also tried on easy and hard mode. /gamerule domobspawning is set to true. I have also created a colony and added 6 citizens to get the message saying that barbarians have noticed the colony, I then used the command to begin a raid, but one never shows up.  I have checked the config and barbarian raids should be spawning. 

(I apologise if I'm missing something really obvious)

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
The spawn egg thing is intentional, they can only spawn as part of raids
The command thing is weird tho, are you maybe on Peaceful mode?

**Comment by iMilui** [comment]
Ok, that explains the spawn eggs. I have tried easy, normal and hard mode.

**Comment by Raycoms** [comment]
Do you have a big enough colony to receive a raid?

**Comment by iMilui** [comment]
How many citizens is required? I had 6 citizens and received the message in chat notifying that barbarians have noticed the colony.

**Comment by Raycoms** [comment]
That might be just not enough. There is not a hard limit.

**Comment by iMilui** [comment]
Okay, I tried starting a raid with 20 citizens and it worked! Thanks for the help, I'm sorry if this was a little dumb.
