### ISSUE TITLE
Проблемы с стражами в може minecolonis

### ISSUE THREAD

**Issue by NegativCain** [ldtteam/minecolonies#6520]
вопрос люди вот я добавил друга в колонию и дал ранг офицера, но его атакуют стражи что делать ?
question people here I added a friend to the colony and gave the rank of an officer, but he is attacked by the guards what to do ?

**Comment by Raycoms** [comment]
Please fill in the full template. For support we also have a discord. There is a setting in the permissions called "attack guard" you turn this off. @ravenbuilder934 can we have an extra wiki entry for this?

**Comment by ravenbuilder934** [comment]
where should i add it? the town hall page (section abt the permission GUI)?

**Comment by Raycoms** [comment]
Yes, permission GUi page
