### ISSUE TITLE
Hell colonies Lava and magma block problems

### ISSUE THREAD

**Issue by oddrobbia** [ldtteam/minecolonies#6522]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version:minecolonies-0.13.602-ALPHA
- Structurize Version:structurize-0.13.113-ALPHA
- Related Mods and their Versions:

## Expected behavior
the colonist and the raid enemies need to evade lava instead of walking into it and also walking on a magma block
## Actual behavior
The colonist after they spawn walking around the colony territory and walking into lava but the buildings are few block higher then the lava is placed but still they walking in the lava and also when i order a builder to build they remove the blocks under themselfs and fall into the lava and also when the build order is done they walk into the middle of the building order where its placed and if there is a hole and the buttom filled with lava they walking into the lava and die

## Steps to reproduce the issue

just make a hell colony and you will notice soon

1. place a building on lava the builder will walk into the lava 
2.  if any of the citizens are walking near lava they will walking into the lava
3.  they die and loseing all the resurces from them

### Logs

- latest.log: 
- crashlog: 

### Notes
need something to do with them to notice there is lava or magma block and not go there even if its ordered to build need to evade the lava the builders not need to be go to the middle to build any buildings

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Fixed in the latest alpha
