### ISSUE TITLE
minecolonies.api.compatibility.CompatibilityManager.isCompost

### ISSUE THREAD

**Issue by Thoddius** [ldtteam/minecolonies#6523]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: minecolonies-0.13.610-ALPHA-universal.jar
- Structurize Version: structurize-0.13.113-ALPHA-universal.jar
- Related Mods and their Versions: OptiFine_1.16.4_HD_U_G6_MOD.jar

## Expected behavior

World loading normally after adding Optifine

## Actual behavior

After adding Optifine, when loading into a pre-existing world, on my dedicated server, I get a quick glimpse of the world and then my client does a "saving game" message and the client crashes with the crash report attached.
This has happened on my system as well as a secondary system with the same mods and configs but with slightly different hardware.
After the first crash I reloaded MC and was able to successfully load into a pre-existing SP world without incident. I then tried connecting to my server and was able to load in and played for several hours without incident. This was the case on the second PC as well.
My son, on the second PC, tried connecting later after restarting MC and the client crashed. I tried logging in as well and also crashed. Each crash had the same error with "minecolonies.api.compatibility.CompatibilityManager.isCompost"
I tried installing OptiForge-MC1.16.4-0.4.6.jar to see if that might help, but it did not, nor did I expect it to.

## Steps to reproduce the issue

1.  Create a new world on dedicated server with several MineColonies structures. I chose the Asian style.
2.  Add OptiFine_1.16.4_HD_U_G6_MOD.jar to the mods folder and load into pre-existing server world
3.  Client crash immediately after loading into world.

### Logs

- latest.log:  https://gist.github.com/Thoddius/5fab4e1772ba3c1a4e34039e00f7b3f1 (contains both files)
- crashlog:  https://gist.github.com/Thoddius/5fab4e1772ba3c1a4e34039e00f7b3f1 (contains both files)

### Notes

The SP world I loaded into did NOT have any MineColonies structures present. I do not know if this will cause the crash on a SP world or not. My concern is being able to connect to our dedicated server.
I will be checking on this issue tomorrow. I will try to do more troubleshooting in the afternoon, if you do not have a resolution, and get back to you if I have any new information to add.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Optifine bugs, fixed in 1.16.5, will apparently be fixed in the next 1.16.4 release
