### ISSUE TITLE
"My AI has run into an issue" message from a courier

### ISSUE THREAD

**Issue by War-Weasel** [ldtteam/minecolonies#6524]
Hey Idtteam, 
I am not sure where to send this so I hope this is the right place. If not, please let me know where/how you would prefer is sent/submitted. When this occurred I was in a creative world messing around looking at buildings and playing with colony layouts.
![2021-02-11_10 38 13](https://user-images.githubusercontent.com/36110519/107659966-c0f16e80-6c55-11eb-85af-f3d61de7abd9.png)
[latest.log](https://github.com/ldtteam/minecolonies/files/5966523/latest.log)

**Comment by ravenbuilder934** [comment]
1. please fill out the template
2. what version of minecolonies are you using?

**Comment by Raycoms** [comment]
Yeah the courier one is known and an issue for it still open.

**Comment by ravenbuilder934** [comment]
(https://github.com/ldtteam/minecolonies/issues/5672)
