### ISSUE TITLE
Builder Wand problem

### ISSUE THREAD

**Issue by Noobshtain** [ldtteam/minecolonies#6525]
Hi, I have a problem with builder Wand. I want to use it and everything is great, but I can't see how building will look, no blueprints, just nothing, only GUI to rotate building that I can't see. Any ideas to solve that problem?

**Comment by ravenbuilder934** [comment]
1. Please fill out the template
2. Optifine or the vanilla setting Fabulous Graphics can cause this, try removing/disabling those
