### ISSUE TITLE
Builder's hut does not acknowledge chainmail armor deliveries for Medieval Oak Barracks Level 3 and 4

### ISSUE THREAD

**Issue by darthvader45** [ldtteam/minecolonies#6527]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: 0.13.610-ALPHA
- Structurize Version: 0.13.113-ALPHA
- Related Mods and their Versions:

## Expected behavior

When chainmail armor is crafted and delivered, the 0/2 is incremented upwards to show it is there.
## Steps to reproduce the issue

1.  Build barracks up to level 3 with all necessary supplies needed for lv 4
2.  Start lv 4 build, and wait for all necessary supplies to be crafted and delivered
3.   See that the armor quantity in the builder's hut supply list and on the resource scroll (if linked) stay at 0/2 instead of showing a full 2/2 when the supplies arrive.

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Should be fixed now

**Comment by darthvader45** [comment]
Thanks.  It was kinda just a UI bug ig, as the armor is still placed.  It is fixed now, and I love it.  So much less to go nuts over, and my OCD thanks you.
