### ISSUE TITLE
1.10.2 | 0.6.2879 Workers not gaining any xp on at level 3

### ISSUE THREAD

**Issue by ghost** [ldtteam/minecolonies#653]
My Lumberjack and Miner are not getting any from level 3 and onward. I've tried everything to fix this, I fired a worker and rehired it but to no avail.

**Comment by Raycoms** [comment]
What is their worker and home hut level?

2017-02-24 19:11 GMT-03:00 H4Xx0R-PC <notifications@github.com>:

**Comment by ghost** [comment]
The two worker huts are both level 2. According to the wiki https://wiki.minecolonies.com/wiki/2/workers-info the maximum level for a level 2 worker hut should be 8.

**Comment by Raycoms** [comment]
and his citizen hut?

2017-02-24 19:17 GMT-03:00 H4Xx0R-PC <notifications@github.com>:

**Comment by ghost** [comment]
I don't have any citizen huts atm (I don't need any yet).

**Comment by Raycoms** [comment]
If the worker has no citizen hut his max should be around 3.
It doesn't say that on the wiki ?

**Comment by ghost** [comment]
Thanks for your help! You should mention it on the wiki though:)

Edit: I am retarded, I forgot everyone can edit a wiki lol.
