### ISSUE TITLE
config data only 2 options

### ISSUE THREAD

**Issue by agentsixtynine** [ldtteam/minecolonies#6533]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4-forge-35.1.4
- MineColonies Version:minecolonies-0.13.437-RELEASE-universal
- Structurize Version:structurize-0.13.96-ALPHA-universal

## Problem description
 I can only access two options in my config file. However I need to toggle the mob griefing option in my colony in order for the Create mod deployer arm to place saplings as otherwhise they won't be plated.

### Notes or related things
 <img width="376" alt="Unbenannt" src="https://user-images.githubusercontent.com/78607706/107854719-298b4780-6e1e-11eb-840f-d3389faafe8c.PNG">

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
See the config file page on the wiki - there are two different config files in 1.16
