### ISSUE TITLE
Waypoints not rendering in Build Tool

### ISSUE THREAD

**Issue by ItsmeCurly** [ldtteam/minecolonies#6536]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4/1.16.5 (Tested on both)
- MineColonies Version: minecolonies-0.13.610-ALPHA-universal
- Structurize Version: structurize-0.13.113-ALPHA-universal
- Related Mods and their Versions:

## Expected behavior

Waypoints are rendered when choosing Decorations->Infrastructure->Waypoint

## Actual behavior

Waypoints are not shown.

![image](https://user-images.githubusercontent.com/31974406/107862065-2a20df80-6e18-11eb-91ee-386f7f210ac1.png)

(After placing four waypoints in the view of the player and after the builder has built all of them)

## Steps to reproduce the issue

1. Have builder build Decorations->Infrastructure->Waypoint.
2. Choose Decorations->Infrastructure->Waypoint under Build Tool.
3. Waypoints are not rendered.

### Logs

- latest.log: Nothing shown of relevance.
- crashlog: N/A

### Notes
Graphics tested: FAST/FANCY, No Optifine.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Usually if they're not rendered, they're not there. Are you sure they are there? Did you place them above a solid block (the waypoint standing directly on the block)?

**Comment by ItsmeCurly** [comment]
They're definitely there, my citizens go completely out of their way to reach them. In my case, I built an underground metro with some various waypoints along it to have them prioritize it, and in some cases, my citizens will stand AFK above the waypoint doing nothing the entire day until I manually dig them a hole to the waypoint. I built every waypoint as shown in the image using the builder.

**Comment by Raycoms** [comment]
fix to structurize pushed, will take a little bit though until it will start appearing again.
