### ISSUE TITLE
Miner stop working after change mining level.

### ISSUE THREAD

**Issue by AVFD** [ldtteam/minecolonies#6537]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.13.610-ALPHA-universal
- Structurize Version: structurize-0.13.113-ALPHA-universal
- Related Mods and their Versions: no other mods.

## Expected behavior

Miner keep mining and find their own path in their current level setted. 

## Actual behavior

After playing for hours the miner stopped mining when I change the mining level. He went to another level (above or below) or even to another Hut and kept into a corner doing nothing.
I tried to reset the NPC, fire him and re-hiring him but he still stuck in this behaviour.
The problem was gone when I restart my Minecraft.

After restarting the game the miner get back to work.
![image](https://user-images.githubusercontent.com/18308993/107861992-5a707a00-6e28-11eb-9018-2dbb60612cbf.png)
The lost miner in another Hut.
![image](https://user-images.githubusercontent.com/18308993/107862267-65c4a500-6e2a-11eb-885b-964edae5a142.png)

## Steps to reproduce the issue

1. Get a miner lvl 4 (but another guy said with him this happened in lvl 3).
2. Keep playing for a long time (more than one or two hours).
3. Sometimes check where your miner are working. (do recall and then follow him)

### Logs

- latest.log:  (when this happen again I will upload the log)
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
When this happens they usually can't find a way to the next position. Did you check in the mine if there are blocked paths?

**Comment by Moobien** [comment]
the issue I had was more that when I change what levelo they are mining at that this happens (Draxx)

**Comment by AVFD** [comment]
Confirmed, the miner get lost when change the mining level.
