### ISSUE TITLE
Clicking Build Options on Barracks 0 causes crash

### ISSUE THREAD

**Issue by chrysillis** [ldtteam/minecolonies#6538]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.13.610-ALPHA
- Structurize Version: 0.13.113-ALPHA
- Related Mods and their Versions: Valhelsia 3 - 3.1.8a modpack

## Expected behavior

Open the build options so I can see the resources needed, change the style, and select a builder, then click build.

## Actual behavior

The game crashes immediately. Minecraft launcher gives the following error afterwards:

The game crashed whilst ticking screen
Error: java.lang.IndexOutOfBoundsException: Index: -1
Exit Code: -1

![screenshot](https://user-images.githubusercontent.com/20598834/107863326-5e8c9f80-6e08-11eb-9ef3-392cce4756e7.jpg)

## Steps to reproduce the issue

1. Click Build Options on level 0 Barracks.
2. Game crashes.

### Logs

- latest.log: https://gist.github.com/DarkSylph/b250ffe1071aa1882091e797140a93a4
- crashlog: https://gist.github.com/DarkSylph/afa266fa9bb6c9a5525fb3ec8543fca1

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Is this a 100% reproduce?

**Comment by chrysillis** [comment]
No. I rebooted the server and it allowed me to click on build options successfully. However, no matter how many times I rebooted my client it caused the same crash.

**Comment by Raycoms** [comment]
Is there a way to reproduce this then? Sth specific you did? Which style did you choose?

**Comment by Inomutso** [comment]
have the same behavior, since minecolonies-0.13.618-ALPHA-universal.jar
not sure, if that happened also on the Alpha Release (minecolonies-0.13.613-ALPHA-universal.jar) before, don´t think so

have minecolonies-0.13.618-ALPHA-universal.jar, structurize-0.13.133-ALPHA-universal.jar, forge-1.16.4-35.1.4-installer.jar

even trying to open a PostBox to order a request, crashes the game 

[16Feb2021 14:54:57.278] [Render thread/FATAL] [net.minecraft.client.Minecraft/]: Reported exception thrown!
net.minecraft.crash.ReportedException: Ticking screen
	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:434) ~[?:?]
	

do you want to have my logs on this ?

regards

**Comment by Inomutso** [comment]
it is not crashing anymore with minecolonies-0.13.620-ALPHA-universal.jar

i cannot use structurize-0.13.135-ALPHA-universal.jar together with minecolonies-0.13.620-ALPHA-universal.jar

getting an error in the MC Launcher on startup, told me to use structurize-0.13.134-ALPHA-universal.jar
  
have fun
