### ISSUE TITLE
Allowed Recipe Window Not Visible in Bakery Menu

### ISSUE THREAD

**Issue by Nerdnub** [ldtteam/minecolonies#6539]
The second window of the Bakery menu is now Choose Fuel, with no option to choose what recipes the Bakery creates. This prevents the Bakery from doing any work as all recipes default to disabled until enabled.

**Comment by uecasm** [comment]
Did you look at the third page?

**Comment by ravenbuilder934** [comment]
The baker works by request now. Either request sth from the postbox, have another worker request sth, or set a minimum stock at the warehouse or on the 3rd page of the bakery gui
