### ISSUE TITLE
Guards/Couriers stopping for waypoints.

### ISSUE THREAD

**Issue by Moobien** [ldtteam/minecolonies#6543]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 610
- Structurize Version: 113
- Related Mods and their Versions:

## Expected behavior

Expecting colonists to pass through waypoints

## Actual behavior

Guards and couriers (that I have seen so far) stop for roughly 4 seconds at EVERY way point between them and their destination. this is especially unhelpful when you have activated your rally banner and you watch 16 guards stop at every waypoint between them and you.

## Steps to reproduce the issue

1. build a nice colony
2. build lots of roads that have waypoints
3. trigger your rally banner and wait

### Logs

- latest.log: https://gist.github.com/Moobien/4b36882f7b5ae807e1dcdc55dcc4845d
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
This sounds weird. Does this happen on a new world too, or only on that particular world?

**Comment by Moobien** [comment]
want me to test on a new world or another existing world i havent touched in a while

**Comment by Raycoms** [comment]
New world would be best

**Comment by Moobien** [comment]
in case you missed discord. confirmed happening in a new world
