### ISSUE TITLE
Knights ask for shields and start using them before university research

### ISSUE THREAD

**Issue by asoshinsky** [ldtteam/minecolonies#6544]
Knight asked me to give them shields even at guard tower level 1. As soon as I give them shields they start walking with them. I suppose this is not intentional because there is a research in the university that allows guards to use shields. 

Style is medieval spruce.
minecolonies-0.13.603-ALPHA-universal
structurize-0.13.109-ALPHA-universal

**Comment by Moobien** [comment]
I am not sure if they are actually using them or if they are just rendering on them because they have them in their inventory, but they shouldn't be requesting them before the research though.

**Comment by asoshinsky** [comment]
Some definitely asked for shield and they were present in the To-do list. After giving shield to them they were walking around with the shield but I never seen them using it.

**Comment by ravenbuilder934** [comment]
I've noticed this too, but they never used them afaik

**Comment by Raycoms** [comment]
@gattsuru was this sovled in your PR?

**Comment by Raycoms** [comment]
Or @someaddons

**Comment by someaddons** [comment]
was sth I delayed till the research stuff is through
