### ISSUE TITLE
Racks turn invisible when placed in L shape

### ISSUE THREAD

**Issue by crouchingmoose** [ldtteam/minecolonies#6546]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.13.610-ALPHA
- Structurize Version: 0.13.113
- Related Mods and their Versions:

## Expected behavior
New Racks should not connect to already connected racks and should remain visible.

## Actual behavior
3 Racks placed in an L shape both attempt to connect to the middle rack. When items are placed in the outer 2 racks, the middle rack will visually update to connect to it and the other outer rack will turn invisible.

## Steps to reproduce the issue
1. Place 3 racks in a connected L shape.
2. Place items in the first outer rack, This rack will connect to the middle corner rack. Other outer rack turns invisible
3. Place items in the invisible other outer rack from step 2. This rack will reappear and connect to the middle, First outer rack will turn invisible

### Logs
N/A

### Notes

---

**Comment by Raycoms** [comment]
Do you have a screenshot or so, I can't reproduce this?

**Comment by ravenbuilder934** [comment]
I think it only happens when they're placed by the builder

**Comment by Moobien** [comment]
it doesn't happen when the building is built in its original orientation, but once you rotate it it does the weird glitch, and as Raven said, usually only happens when a builer places them.
