### ISSUE TITLE
Builder does not place bell in lv 4 med oak library

### ISSUE THREAD

**Issue by darthvader45** [ldtteam/minecolonies#6549]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: 0.13.610
- Structurize Version: 0.13.113
- Related Mods and their Versions:

## Expected behavior

Builder places a bell in the last few steps of the building process.
## Actual behavior

The bell is not placed, despite the schematic including one, thus it looks weird.

## Steps to reproduce the issue

1.  build library
2.  upgrade to level 4
3.  bell is not placed.

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Does this work in the newest?

**Comment by darthvader45** [comment]
Haven't had a new library built to check.

**Comment by ravenbuilder934** [comment]
Can anyone else reproduce this on the newest?
