### ISSUE TITLE
Barracks - TrueDwarven Schematic preview wrong

### ISSUE THREAD

**Issue by smmmadden** [ldtteam/minecolonies#6555]
### Prerequisites 

- [ x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 36.0.22
- MineColonies Version: 0.13.615-ALPHA
- Structurize Version: 0.13.113-ALPHA
- Related Mods and their Versions:

## Expected behavior

I Expected the preview of the Barracks (or any others) to show what the completed build would look like to decide if it was what I wanted.
## Actual behavior

Screenshots describe the issue.  The completed structure versus the preview of level 5 when I placed it on the ground.

![image](https://user-images.githubusercontent.com/10309346/108015101-6baeb780-6fdd-11eb-812c-1a60fdc91d43.png)
Preview before building it.
![image](https://user-images.githubusercontent.com/10309346/108015121-79643d00-6fdd-11eb-9925-930ecf6ed14e.png)

## Steps to reproduce the issue
Upgraded today to latest build and this doesn't render completely.  Was working previously but not sure which build since I've been keeping current with the releases.

1.  Place a barracks on the ground
2.  Preview True Dwarven Level 5
3.  It should show the correct built schematic of the barracks

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
That is correct actually. The barracks is only this. The barracks towers are a seperate thing that are not rendered

**Comment by smmmadden** [comment]
Sorry, but if there is no way to visualize it, how can someone choose it?  We were able to see the full build before when it was done in another colony.  Is there any other way to see the schematic in-game before it is placed?  These types of builds take many, many hours to do, so it would just waste a lot of time if the finished product isn't what was expected and only to have to destroy it and choose another. :-(   

Kind of related to this style build, having multiple builders work on "Fortress" style builds (or other very large buildings) would be a plus! :-)
