### ISSUE TITLE
UI Scaling Issue

### ISSUE THREAD

**Issue by ItsmeCurly** [ldtteam/minecolonies#6556]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: minecolonies-0.13.618-ALPHA-universal
- Structurize Version: structurize-0.13.133-ALPHA-universal
- Related Mods and their Versions:

## Expected behavior

UI Scales properly.

## Actual behavior

UI truncates and is larger than before. Lots of elements are cut off.

![image](https://user-images.githubusercontent.com/31974406/108015719-d7ddeb00-6fde-11eb-9171-816eedd9fa55.png)
![image](https://user-images.githubusercontent.com/31974406/108015753-efb56f00-6fde-11eb-999c-032a101f8d9b.png)

Happens with all GUI scales. 
No Optifine.

## Steps to reproduce the issue

1. GUI just doesn't scale properly.

### Logs

- latest.log: N/A
- crashlog: N/A

### Notes

Jumped from MC: .613 / Struct: .113 to MC: .618 / Struct: .133 and the issue started occurring.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Nightenom** [comment]
Lots of elements are cut off: that's issue of someone using small element bounding boxes, we need all screenshot of this happening to fix that
UI is larger than before: we used weird mix of fixed and vanilla gui scaling before, we now properly scale with vanilla gui scale setting according to size of gui, larger gui may have smaller scale than the setting to properly fit in the monitor
