### ISSUE TITLE
Crash when looking at citizen stats in Town Hall block

### ISSUE THREAD

**Issue by ItsmeCurly** [ldtteam/minecolonies#6557]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: minecolonies-0.13.618-ALPHA-universal
- Structurize Version: structurize-0.13.133-ALPHA-universal
- Related Mods and their Versions:

## Expected behavior

Town hall shows citizen stats

## Actual behavior

Crash

## Steps to reproduce the issue

1. Open town hall block
2. Click citizen tab
3. Click on random citizen to view stats
4. Crash

### Logs

- latest.log + crashlog: https://gist.github.com/ItsmeCurly/adcc9e4c1b403e4d46eb30d35dcce431

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
Same here with same versions of the mods, but in 1.16.5  - can provide a log if you need, but assume it is the same as above =)

**Comment by Moobien** [comment]
I got a crash when accessing a colonists ui directly to fulfil builder requests. 

https://gist.github.com/Moobien/da5db0517ffb3d56f6f6654659601f02

**Comment by Nightenom** [comment]
@Moobien please fill in new issues, your crash is weird and I'm unable to reproduce, need more info

**Comment by Nightenom** [comment]
> @Moobien please fill in new issues, your crash is weird and I'm unable to reproduce, need more info

@Moobien found potential reason after internal discussion, fix incoming soon
