### ISSUE TITLE
Doesn't accept correct version of Structurize

### ISSUE THREAD

**Issue by Thoddius** [ldtteam/minecolonies#6559]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: minecolonies-0.13.619-ALPHA-universal
- Structurize Version: 0.13.133-ALPHA
- Related Mods and their Versions: N/A

## Expected behavior

Load modpack

## Actual behavior

Both my client and server have the same error. Takes less than 30 seconds during load process.
Crash with : [main/FATAL] [minecraft/Main]: Failed to start the minecraft server
16.02 04:18:10 [Server] INFO net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
16.02 04:18:10 [Server] INFO Mod minecolonies requires structurize 0.13.133-ALPHA
16.02 04:18:10 [Server] INFO Currently, structurize is 0.13.113-ALPHA

## Steps to reproduce the issue

1.  Update to minecolonies-0.13.619-ALPHA-universal
2.  Start MC
3.  Crash

### Logs

- latest.log:  https://gist.github.com/Thoddius/a0d3ca77d640e93205469c9c440c1493
- crashlog:  https://gist.github.com/Thoddius/a0d3ca77d640e93205469c9c440c1493

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
You have 113 installed and it wants 133 now.  The numbers are similar but they are not the same.

**Comment by Thoddius** [comment]
Dyslexia strikes again. Curseforge loader doesn't have 133 listed yet.
Thanks.
