### ISSUE TITLE
Healer died but he is still listed in the town hall

### ISSUE THREAD

**Issue by wafebreaker** [ldtteam/minecolonies#6562]
### Prerequisites 

- [] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.13.610-ALPHA-universal.jar
- Structurize Version: structurize-0.13.113-ALPHA-universal.jar
- Related Mods and their Versions: ATM 6 Modpack

## Expected behavior

The healer dies and the slot in the town hall becomes free.

## Actual behavior
The healer has died but there is still 1/1 healer in the town hall. There are also only 16 out of 17 residents and I still can't hire anyone and no children are born.

[Imgur Images](https://imgur.com/a/8HqSz4y)

## Steps to reproduce the issue
I dont really know

### Logs

- latest.log: [Log](https://gist.github.com/wafebreaker/a8047a0903795a00f73397b3560cca78)

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Can you try this out on the newest?

**Comment by wafebreaker** [comment]
Unfortunately no, because I have absolutely no idea how that happened.

**Comment by Raycoms** [comment]
I mean, can you update to the latest and check if the UI and stuff is fixed.

**Comment by Raycoms** [comment]
Ping

**Comment by wafebreaker** [comment]
Couldnt play the last few days but it is Not easy for me to Update the mod because its on a full mp Server. But if you think it may ne fixed with updating you can close this. Sorry
