### ISSUE TITLE
GUI Issues

### ISSUE THREAD

**Issue by Sandriell** [ldtteam/minecolonies#6566]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: minecolonies-0.13.620-ALPHA-universal
- Structurize Version: structurize-0.13.134-ALPHA-universal

## Expected behavior

Text clearly displayed

## Actual behavior

No text displayed or cut off. All the issues I have observed.

2nd page of Miner Hut GUI, nodes are cutoff when (presumably) reaching triple digits.

![node](https://user-images.githubusercontent.com/10704907/108153318-edb7e280-70a8-11eb-84cd-baa90dc50536.png)

The text is missing on the bottoms on the Citizen Hut (same for the tavern)

![house](https://user-images.githubusercontent.com/10704907/108153893-0c6aa900-70aa-11eb-8cf9-f2ddd6e26272.png)

3rd page of Guard/Barracks Tower, mob names are cut off.

![moblist](https://user-images.githubusercontent.com/10704907/108153952-1b515b80-70aa-11eb-9ce8-d08bc1262663.png)

2nd page of Deliveryman hut

![delivery](https://user-images.githubusercontent.com/10704907/108154330-adf1fa80-70aa-11eb-9913-2870e607ee0e.png)

Townhall, Citizens page: XP bar is missing and their name disappears when selected.

![citizen](https://user-images.githubusercontent.com/10704907/108155851-98320480-70ad-11eb-9f6d-c4c6452a27d0.png)

Farms Hut, 2nd page is missing Field info such as assigned name and location. 3rd page is cut off about requesting compost.

![fields](https://user-images.githubusercontent.com/10704907/108156261-4b9af900-70ae-11eb-9b04-ea0bfba86dda.png)
![compost](https://user-images.githubusercontent.com/10704907/108156264-4d64bc80-70ae-11eb-97f7-3b271dc9dd6e.png)

## Steps to reproduce the issue

View the GUIs

### Logs

N/A

### Notes

Maybe leave this open as a master issue for all GUI bugs?

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by SirSmuggler** [comment]
I've seen it in the university as well, many techs now read "Requires X atleast level" but the number for level is gone so you have to guess :)

**Comment by SirSmuggler** [comment]
Seems to be the same as issue #6563

**Comment by Titanium237458** [comment]
I noticed the same thing happens in the materials screen when building or updating a building in .626 when more than 99 of one block are needed.
Wanted to upgrade my warehouse to Level 5, the screen said it only needed 11 Quartz Stairs and Slabs, but the builder requested 110 and 112 respectively.
![2021-02-18_17 27 52](https://user-images.githubusercontent.com/8401588/108389193-b7e13e00-720f-11eb-90ab-9f6c5c8c6988.png)
![2021-02-18_17 27 57](https://user-images.githubusercontent.com/8401588/108389417-ef4fea80-720f-11eb-8fb0-faaea67b7eff.png)
![2021-02-18_17 27 37](https://user-images.githubusercontent.com/8401588/108389198-b9ab0180-720f-11eb-9d0a-831341b159b3.png)

**Comment by ravenbuilder934** [comment]
> I noticed the same thing happens in the materials screen when building or updating a building in .626 when more than 99 of one block are needed.
> Wanted to upgrade my warehouse to Level 5, the screen said it only needed 11 Quartz Stairs and Slabs, but the builder requested 110 and 112 respectively.
> ![2021-02-18_17 27 52](https://user-images.githubusercontent.com/8401588/108389193-b7e13e00-720f-11eb-90ab-9f6c5c8c6988.png)
> ![2021-02-18_17 27 57](https://user-images.githubusercontent.com/8401588/108389417-ef4fea80-720f-11eb-8fb0-faaea67b7eff.png)
> ![2021-02-18_17 27 37](https://user-images.githubusercontent.com/8401588/108389198-b9ab0180-720f-11eb-9d0a-831341b159b3.png)

New issue please, this one's already closed
