### ISSUE TITLE
Guard Scepter is crashing my game upon loading into hosted server

### ISSUE THREAD

**Issue by RedAdams11** [ldtteam/minecolonies#6568]
### Prerequisites 

- [ x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.16.5
- MineColonies Version:0.13.620
- Structurize Version:

## Problem description
I leveled up the Guard Tower to level 2 (birch decor) but upon getting the Guard Scepter and right clicking a grass block 2-4 blocks from the guard tower, my game crashed and when trying to load back into the server (hosted through Mcprohosting) the game crashes. 

### Notes or related things
This is happening in Direwolf20's newest modpack for context

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
We do need the crash log

**Comment by RedAdams11** [comment]
[crash-2021-02-17_12.07.24-client.txt](https://github.com/ldtteam/minecolonies/files/5997380/crash-2021-02-17_12.07.24-client.txt)

**Comment by Raycoms** [comment]
@ravenbuilder934 did you remove the guard patroll banner schematic?

**Comment by ravenbuilder934** [comment]
I said *very specifically* in my last schem PR that I did :P 
and you're the one who merged it iirc

**Comment by ravenbuilder934** [comment]
anyway this is fixed now

**Comment by Raycoms** [comment]
Meh, I'll have to start reading those schematic PR messages then =P

**Comment by ravenbuilder934** [comment]
yes, you do 😁 
I'll write an extra-long one next time
