### ISSUE TITLE
Townhall citizen record bug

### ISSUE THREAD

**Issue by Cherubi09** [ldtteam/minecolonies#6569]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.16
- MineColonies Version:minecolonies-0.13.622-ALPHA-universal.jar
- Structurize Version:structurize-0.13.135-ALPHA-universal.jar
- Related Mods and their Versions:

## Expected behavior

To see colonists names in townhall menu. 
And see colonists' skill levels
## Actual behavior

When trying to get a builder i noticed they was not automatically claiming the job. After checking the townhall block i saw that the colonists were spawning but not showing in the citizens list. As well as looking at their menus their skills were not showing up either.

I do not sorry. 
## Steps to reproduce the issue
All i did was place the townhall started the colony. 
 

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Can you a) try the newest alpha and
b) Show us your latest.log?

**Comment by Cherubi09** [comment]
It is the newest alpha on curseforge. And the game never crashed

**Comment by Raycoms** [comment]
There is still a latest.log

**Comment by Cherubi09** [comment]
I looked in server files i see no latest.log

**Comment by Raycoms** [comment]
there should be a logs folder, with a latest.log

**Comment by Cherubi09** [comment]
unless you mean in the roaming folder 
[latest.log](https://github.com/ldtteam/minecolonies/files/5998038/latest.log)

**Comment by Raycoms** [comment]
Can you try without optifine?

**Comment by Cherubi09** [comment]
no not really cuz frames become too low

**Comment by Nightenom** [comment]
Reinstall forge, redownload structurize/minecolonies

**Comment by Raycoms** [comment]
is this on a dedicated server, or single player?

**Comment by Cherubi09** [comment]
> is this on a dedicated server, or single player?

Dedi server

**Comment by Raycoms** [comment]
Why is optifine installed on the server? You only need this on the client

**Comment by Cherubi09** [comment]
> Why is optifine installed on the server? You only need this on the client

It isnt in server thats thru my logs from roaming folder. There isnt a latest. Log on server

**Comment by Cherubi09** [comment]
Im juat gonna try an older version see if it works

**Comment by Raycoms** [comment]
Is this working in the newest alpha now?

**Comment by Raycoms** [comment]
fixed in latest
