### ISSUE TITLE
Suggestion: Weekends and Holidays

### ISSUE THREAD

**Issue by kedamono** [ldtteam/minecolonies#657]
### Minecolonies version

Future Versions

### Requested behavior

- Colonists labor for 5 days, and then take 2 off and wear their "civilian garb". Every so often, there ill be a holiday and the colonist expect cake for the holiday. The exception are the Guards. Only half of them, rounded down, take the weekend off. This can affect their "happiness" levels, and making a colonist work on the weekend or a holiday can lower their happiness. 

### Current behaviour

- Colonists work 7 days a week, guards work 24/7.

### Reasons for Suggestion

Basically, something to add to the experience of Minecolonies. Having the colonists take a weekend off, might be infuriating to the player, but it helps with their happiness levels. The guards need to take time off, so letting a couple have a weekend off should keep their happiness levels up. You can make someone work using the builders tool by right clicking them. That puts them back into their worker skin and back to work. It does lower their happiness level when you do this. 

Holidays can match traditional ones, or could be made up, like October 7th, St. Notches Day.

**Comment by Wissi** [comment]
I think there are other ways to have for "happiness" system level up that won't make the Player "infuriated". 

Once you have a well established colony/Town of maybe 10 or more Citizens then it might work well, but for a starter Colony/Player it won't be a nice experience.

It is a great idea IF it gets implemented after a certain colony size (of maybe more than 10).

Of course IMO.

**Comment by Raycoms** [comment]
I agree that guards should work less but the holidays and weekends would
only make players mad =D

2017-02-25 17:42 GMT-03:00 Wissi <notifications@github.com>:

**Comment by kedamono** [comment]
I agree, it could be an optional setting. Once you hit 10+ population, the weekends and holidays kick in. And, once every 365 minecraft days, there is founders day. Where the first four colonists have the day off and really do expect cake. :-)

**Comment by kedamono** [comment]
Hmm, that would also mean you'd need to make a calendar to keep track of the days. And since it would be based on the minecraft internal calendar, using the command _/time set 0_ would reset the calendar.

**Comment by marchermans** [comment]
It would be something that could be easily integrated into the new request system. So it would not be that hard.

**Comment by Raycoms** [comment]
Bt a lot of work for something optional most people won't like

2017-02-25 18:27 GMT-03:00 Orion <notifications@github.com>:

**Comment by WORMSS** [comment]
@kedamono What happens on Founders day if the original 4 colonists are dead?
Maybe it should be all colonists?

**Comment by kedamono** [comment]
Well, if they are dead, yeah, cake for everyone!

**Comment by Raycoms** [comment]
I think for now I will close this, improbable we will make this in feasible time.
And most players probably won't be psyched about that.
