### ISSUE TITLE
Number of needed materials is displayed wrong in building GUI

### ISSUE THREAD

**Issue by Titanium237458** [ldtteam/minecolonies#6571]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.13.627-ALPHA-universal
- Structurize Version: 0.13.135-ALPHA-universal
- Related Mods and their Versions: -

## Expected behavior

Number of needed blocks is displayed correctly and matches the number of items in the resource scroll
## Actual behavior

If a block is needed more than 99 times the last digit in the build screen is cut off.
Screenshots make it clearer. The upgrade GUI shows 11 Quartz Stairs and Quartz Slabs are needed,
but after the builder starts that build request, the resource scroll shows that 110 Quartz Stairs and 112 Quartz Slabs are needed.

![2021-02-18_17 27 52](https://user-images.githubusercontent.com/8401588/108394174-bbc38f00-7214-11eb-97c9-1a7f17a3b7bf.png)
![2021-02-18_17 27 57](https://user-images.githubusercontent.com/8401588/108394177-bc5c2580-7214-11eb-852a-4923fa262603.png)
![2021-02-18_17 27 37](https://user-images.githubusercontent.com/8401588/108394166-ba926200-7214-11eb-92e0-79fae9f9688d.png)

## Steps to reproduce the issue

1. Make a build request that uses more than 99 of a certain block (for example Mesa Warehouse Level 5)
2. Notice how the promised number of needed Quartz Stairs and Slabs doesn't match the actual number.

### Logs

- latest.log: -
- crashlog: -

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
fixed
