### ISSUE TITLE
Block icons in clipboard are very dark

### ISSUE THREAD

**Issue by darthvader45** [ldtteam/minecolonies#6573]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.13.627-ALPHA
- Structurize Version: 0.13.135-ALPHA
- Related Mods and their Versions:

## Expected behavior

Icons looking normal.
## Actual behavior

Icons for blocks are quite dark, often hard to see what blocks they are, only know from the text.

![2021-02-18_15 41 08](https://user-images.githubusercontent.com/2816420/108418829-c0317d00-71ff-11eb-8ade-64aeb0e4327d.png)
## Steps to reproduce the issue

1.  Get a clipboard and bind it to the town hall.
2.  Open it to view requests
3.  Icons for blocks look darker than normal.

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Nightenom** [comment]
#6565
