### ISSUE TITLE
Recipe UI closes after each add instead of remaining open until done

### ISSUE THREAD

**Issue by smmmadden** [ldtteam/minecolonies#6577]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 36.0.42
- MineColonies Version: 0.13.622
- Structurize Version: 0.13.135
- Related Mods and their Versions:

## Expected behavior

Recipe UI should remain open while each recipe gets added as it has in the past.  Having to right-click on the block, click on Add Recipe, click Done and then repeat the same steps is just way too time consuming/frustrating.  Some huts have 10's of recipes to manually add in and this just prolongs the agony of doing so taking away from the fun part of the builds.
## Actual behavior

Something changed recently and now it closes after clicking Done every time.

## Steps to reproduce the issue

I upgraded to 0.13.622 and we added a number of huts/buildings and then we started adding recipes only to find out it now takes much longer to do so.  I was on the Blacksmith adding its recipes and the list is pretty long.
1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

Given we are making multiple colonies on our servers, what would be more helpful than manually adding recipes over and over for the same buildings either multiple times in one colony or many colonies, is to have a command or server file setting that can support "require recipe" or "not require recipe" that we can use.  Could extend this further by specifying the colony ID associated with the setting.
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Nightenom** [comment]
Need to check this <https://github.com/ldtteam/minecolonies/commit/a7c1e7cdac4479809938feba43fa97c33261d7d6#diff-0a98e61c3c7cea5c6d6286f0adc218085f59d5e735a18467a09e75ad6891946a>
