### ISSUE TITLE
Miner doesn't mine shaft down

### ISSUE THREAD

**Issue by Samvanbogaert17** [ldtteam/minecolonies#6579]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**
Issue exists but couldn't find a valid solution

### Context 

What I have tried to resolve:

recall miner
restart miner
repair building
remove the entire building/shaft with cobble and rebuild the mine

All of the above but in a different location in my world

Mine level 1
Worker level 5

Worker inventory: see attachment

minecraft 1.16.5 (All the Mods 6)
minecolonies 0.13.620-ALPHA -> upgraded from 0.13.596-ALPHA

although I noticed the issue also presented itself on numerous other versions that were RELEASE and not alpha and also on a different modpack

Am I missing something?

Anyway, thanks for the great mod, lad(s). truly one of the best mods out there

miner inventory
![miner inventory](https://user-images.githubusercontent.com/34511667/108525800-c7748b80-72d0-11eb-832d-eb83cd7600de.jpg)

### Logs

- latest.log: 

## Steps to reproduce the issue / details

Build the miner I guess lol.

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Inomutso** [comment]
I have seen this in one of my Colonies years ago with MC 1.12.2
here it was my fault, cause in started the Colony on a "Flat World"
but I think you must have checked that already

for me my 2 Miners have no Problems like this at the moment in
minecraft 1.16.4 with minecolonies 0.13.620-ALPHA

**Comment by Raycoms** [comment]
Did you try giving the miner better tools than wooden tools already?

**Comment by Raycoms** [comment]
Did the miner stop out of the blue, or did the mine never mine down at all?

**Comment by Samvanbogaert17** [comment]
My world is a regular Biomes O' Plenty world

I did try and give him stone and iron tools, but that didn't help
After completing the miner building, the miner mines down a couple of layers and then just stops, but it always seems to be the same depth the miner mines and decides to stop

**Comment by MatthiasMann** [comment]
The depth of the mine depends on the level of the hut - so a level 1 mine won't go down very deep - I typically upgrade the mine to level 3 first before I hire a miner.

**Comment by Raycoms** [comment]
Same issue as https://github.com/ldtteam/minecolonies/issues/6537 then

**Comment by Samvanbogaert17** [comment]
Not sure how it is the same issue or how I can resolve my issue.
he's just standing there... menacingly :p

Mine:
![mine](https://user-images.githubusercontent.com/34511667/108606500-aab48280-73ba-11eb-94e3-8050f5607cf9.jpg)


Mine top:
![mine top](https://user-images.githubusercontent.com/34511667/108606504-ae480980-73ba-11eb-884f-b63e83b76a65.jpg)

**Comment by pastelflames** [comment]
Mine keeps doing the same thing. It keeps walking back and forth from her hut and mine. I tried breaking the top block and replacing it and the ladder. She would break the torches when I did. The mine is level 2. I am going to try and go up to level 3 but I have to upgrade my builder.

**Comment by Raycoms** [comment]
Can you tell me if this is now working better?

**Comment by Samvanbogaert17** [comment]
I got the newest version of minecolonies (and All The Mods 6)
but the miner on my world, still doesn't want to create nodes it seems

I deconstructed the mine and pasted a new mine of level 3 in the same spot (I covered the previous mining shaft/empty spaces with stone)

The miner started to mine down again but stopped again after 6 levels and is now afk-ing again

**Comment by ravenbuilder934** [comment]
What if you build a mine in a different spot?
