### ISSUE TITLE
Improved behavior: Smarter Lumberjacks/janes [$15]

### ISSUE THREAD

**Issue by kedamono** [ldtteam/minecolonies#658]
### Minecolonies version

version 0.6.2879

### Expected behavior

- Lumberjacks/janes do not stand directly on top of a sapling while cutting down a tree.

### Actual behaviour

- Lumberjacks/janes routinely stand on top of a sapling while they harvest another tree. Then the sapling grows and kills the lumberjack/jane.

### Steps to reproduce the problem

1. Put down one sapling in the lumberjack's area.
2. Bonemeal it to full size.
3. Plant three more saplings next to the tree to make a square.
4. Wait for the lumberjack to harvest the grown tree.
5. Sapling under lumberjack grows and kills him.

**Comment by Raycoms** [comment]
I had asked myself how to handle this.
We could mark saplings as not passable but that would make lumberjacks not  pass the saplings anymore which might be dump because they could get stuck with 8 saplings around them.

The other option would be making it similar to the stuck method. 
If more than 2 seconds over a sapling -> run away from place and try to approach the target from a different place.
What do you think @Kostronor ?

**Comment by marvin-bitterlich** [comment]
Why not exclude saplings as safe stand, but still have them be passable? The LJ is always looking for a place to stand, we just have to make this explicit.

**Comment by Raycoms** [comment]
The Lj searches for a place to stand? Thought only builder does that. I
will take a look at that.

2017-03-01 13:44 GMT-03:00 Marvin Hofmann <notifications@github.com>:

**Comment by Raycoms** [comment]
private AIState chopTree()
{
    final BlockPos location = job.tree.getLocation();
    if (walkToBlock(location))
    {
        checkIfStuckOnLeaves(location);
        return getState();
    }

    if (!job.tree.hasLogs())
    {
        if (hasNotDelayed(WAIT_BEFORE_SAPLING))
        {
            return getState();
        }
        plantSapling();
        this.getOwnBuilding().getColony().incrementStatistic("trees");
        return LUMBERJACK_GATHERING;
    }

    //take first log from queue
    final BlockPos log = job.tree.peekNextLog();
    if (!mineBlock(log))
    {
        return getState();
    }
    job.tree.pollNextLog();
    return getState();
}

No save stand here.


2017-03-01 14:27 GMT-03:00 Ray Neiheiser <ray.neiheiser@gmail.com>:

**Comment by marvin-bitterlich** [comment]
Yeah because you implicitly set it to null in walkToBlock

**Comment by Raycoms** [comment]
Yeah because we have no calculation.
But I think the mineBlock does calculate a save stand anyway we can
manipulate to not accept saplings

Am Mittwoch, 1. März 2017 schrieb Marvin Hofmann :

**Comment by Raycoms** [comment]
Just checked we're not calculating any better position.
Will have to create a "saveStand" check for the lumberjack then.

2017-03-01 15:30 GMT-03:00 Ray Neiheiser <ray.neiheiser@gmail.com>:

**Comment by kedamono** [comment]
I tested the new build in a very woody biome. I planted saplings everywhere before hiring a lumberjack. 

She would initially stay one block away from a sapling, but after clearing away leaves, she then stood on the sapling. However, she would walk away about every 8 to 10 seconds, and then walk right back on to the sapling. For one tree, she found a safe location to work from, so if there is a clear area with no saplings, that's where she will go. 

As a test to see what she would do around a jungle tree, I planted and bonemealed a 2x2 sapling group to grow a giant jungle tree. Then I planted more jungle saplings all around it. What she did was climb up into the tree and to cut it down from the top.

Screenshots of Hayley in action:
![2017-03-02_14 31 48](https://cloud.githubusercontent.com/assets/23420636/23531298/ab519c60-ff5a-11e6-85b8-a6a24756c49f.png)
![2017-03-02_14 32 18](https://cloud.githubusercontent.com/assets/23420636/23531302/ab6db882-ff5a-11e6-9f58-6462c9955d27.png)
![2017-03-02_14 33 14](https://cloud.githubusercontent.com/assets/23420636/23531300/ab6be4e4-ff5a-11e6-9ea9-fe6be346e093.png)
![2017-03-02_14 33 28](https://cloud.githubusercontent.com/assets/23420636/23531303/ab6f143e-ff5a-11e6-9a65-2b800c91ff91.png)
![2017-03-02_14 33 33](https://cloud.githubusercontent.com/assets/23420636/23531301/ab6c1b08-ff5a-11e6-9616-980341479043.png)
![2017-03-02_14 33 54](https://cloud.githubusercontent.com/assets/23420636/23531304/ab70c978-ff5a-11e6-996f-d99f838ee335.png)
![2017-03-02_14 34 33](https://cloud.githubusercontent.com/assets/23420636/23531299/ab69f5f8-ff5a-11e6-8912-5266bd03e15a.png)
![2017-03-02_14 34 41](https://cloud.githubusercontent.com/assets/23420636/23531305/ab800f6e-ff5a-11e6-8fbd-cd3822eb6b8a.png)
![2017-03-02_14 34 57](https://cloud.githubusercontent.com/assets/23420636/23531308/ab8a8da4-ff5a-11e6-887a-2b92dd9eeafd.png)
![2017-03-02_14 35 20](https://cloud.githubusercontent.com/assets/23420636/23531307/ab8929d2-ff5a-11e6-8e4d-5e1fb9da4a66.png)
![2017-03-02_14 37 22](https://cloud.githubusercontent.com/assets/23420636/23531309/ab8b654e-ff5a-11e6-8548-a1865ac80742.png)
![2017-03-02_14 40 11](https://cloud.githubusercontent.com/assets/23420636/23531306/ab8912b2-ff5a-11e6-972d-d93146059c48.png)
![2017-03-02_14 40 28](https://cloud.githubusercontent.com/assets/23420636/23531310/ab8b9c26-ff5a-11e6-8067-12697f015b80.png)
![2017-03-02_14 42 39](https://cloud.githubusercontent.com/assets/23420636/23531311/ab956eea-ff5a-11e6-80cc-320fe185d3e4.png)
![2017-03-02_14 51 51](https://cloud.githubusercontent.com/assets/23420636/23531313/ab9f48f2-ff5a-11e6-8b1c-e9416779b448.png)
![2017-03-02_14 52 40](https://cloud.githubusercontent.com/assets/23420636/23531312/ab9ece68-ff5a-11e6-849a-e6da2adb85ee.png)

**Comment by Raycoms** [comment]
Will work a bit  more on it today

2017-03-02 20:13 GMT-03:00 kedamono <notifications@github.com>:

**Comment by kedamono** [comment]
Better behavior with build 1.10.2-0.6.3016, the lumberjack will walk back and forth if the spot that they want to use has a sapling on it. But, they will continue this behavior until the sapling turns into a tree or another sapling grows and blocks the area with leaves. 

However, the LJ will stand on a sapling while breaking leaves on a tree. They will stand on the sapling for 8 to 10 seconds, go back to the hut, then stand back on it to break more leaves. Once enough leaves are broken, they will either go into the loop of walking back and forth, or if there is a way on top of the tree from a neighboring tree, they will climb up on the tree and cut it down from the top. 

In my test, my LJ climbed a tree and cut the tree directly beneath. Eventually the leaves decayed and she fell down and was surrounded by logs and leaves. A sapling grew and blocked her from getting out and she never left the tree after 7 minutes of waiting. I finally broke her out and removed the tree she was climbing up. So instead, she cut a couple of logs and climbed up and began cutting the tree down from inside the tree.

**Comment by Raycoms** [comment]
hmm very strange. Will take a longer look at it.

2017-03-05 19:22 GMT-03:00 kedamono <notifications@github.com>:

**Comment by kedamono** [comment]
Well, this time with build 1.10.2-0.6.3045 I succeeded in getting the achievement "I am Groot!", but in this case, it was due to such an artificial situation that I think this build is one of the better ones. 

In most cases the LJ stayed away from the saplings, though I did catch her standing on them twice while breaking leaves. 

The Groot 'chieve was gotten due to me literally covering a 16x16 area in saplings with some gaps. It formed a maze of trees and saplings, and clear spots that the LJ navigated and found the clear spot to work from. When she died, she had tried to get to the safe spot from a different direction and got herself caught in a dead end. Then the saplings grew and she subsequently had the sapling underneath her grow and suffocate her. 

The new LJ found the safe route in to the block of trees and stayed safe while she cut down the trees. So, I give this a 4.5 out of 5 for keeping the LJ safe. It's not perfect, but if it was perfect, you'd never get the Groot 'chieve.

**Comment by Raycoms** [comment]
Okay seems nice. I'll push it like this then.

Avoid that 100% will be impossible. Only if we make them invincible against
the trees, but where will be the fun =D
She will always have to walk above saplings sometimes but the chance to die
that way is relatively low.

Thanks for testing =)

2017-03-05 22:51 GMT-03:00 kedamono <notifications@github.com>:
