### ISSUE TITLE
Townhall outside build colony

### ISSUE THREAD

**Issue by firestorm2039** [ldtteam/minecolonies#6583]
### Prerequisites 

- [X ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: forge 1.16.4
- MineColonies Version: 1.16.4
- Structurize Version:1.16.4

## Problem description

i placed supply camp on flat land (took me a while to fit this out), which then built itself, i made a town hall as i didnt know 1 appears in supply camp, so now i have 2 lol.
anyway i go to place the town hall on flat land, use build tool and all is fine, then i click green tick and it says it is outside the colony?
i have this next to the supply camp, (not so the build goes in to the camp though), i cant place anything else until i build the town hall.
could you tell me what i am doing wrong?

### Notes or related things

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
```
Minecraft Version: forge 1.16.4
MineColonies Version: 1.16.4
Structurize Version:1.16.4
```


We need the exact version

**Comment by firestorm2039** [comment]
> ```
> Minecraft Version: forge 1.16.4
> MineColonies Version: 1.16.4
> Structurize Version:1.16.4
> ```
> 
> We need the exact version

i thought that was the version?? were do i find this?

**Comment by ravenbuilder934** [comment]
The mod's file name

**Comment by firestorm2039** [comment]
> The mod's file name

minecolonies-0.13.571-ALPHA-universal
structurize-0.13.104-ALPHA-universal
forge-1.16.4-35.1.37-installer
i assume you mean forge version? as minecraft itself automatically updates doesn't it?? (sorry i am not great with computers lol)

**Comment by ravenbuilder934** [comment]
Yup that's it! It's over 50 versions out of date though (for minecolonies), can you try updating?

**Comment by firestorm2039** [comment]
> Yup that's it! It's over 50 versions out of date though (for minecolonies), can you try updating?

i will try, i thought i clicked on latest 1.16.4 version a few week ago lol.

**Comment by ravenbuilder934** [comment]
We update *fast* 😄

**Comment by firestorm2039** [comment]
> Yup that's it! It's over 50 versions out of date though (for minecolonies), can you try updating?

it says 0.13.571 is the latest for 1.16.4
there is lots for 1.16.5, but my forge wont work with that version will it unless i get forged 1.16.5? but most of my mods are not upgraded to 1.16.5 yet :(

**Comment by ravenbuilder934** [comment]
Yup, all 1.16.5 versions work with 1.16.4

**Comment by firestorm2039** [comment]
> Yup, all 1.16.5 versions work with 1.16.4

oh ok, i will download the latest 1.16.5 now

**Comment by firestorm2039** [comment]
> Yup, all 1.16.5 versions work with 1.16.4

would i need to also download structurize 1.16.5 and would that work with forge 1.16.4??

**Comment by ravenbuilder934** [comment]
should, yeah

**Comment by firestorm2039** [comment]
> should, yeah

i assume i have to
![Untitled](https://user-images.githubusercontent.com/75093996/108564935-cefd5a00-72fb-11eb-9c0e-f1d6a2c5e42e.png)

**Comment by uecasm** [comment]
You do need to get the exact version of Structurize that it specifies, not the latest one.

**Comment by firestorm2039** [comment]
> You do need to get the exact version of Structurize that it specifies, not the latest one.

ok thank you

**Comment by firestorm2039** [comment]
> should, yeah
i still get the same message :( updated structurize to 0.13.135 and minecolonies to 0.13.630
![Untitled](https://user-images.githubusercontent.com/75093996/108565844-4a134000-72fd-11eb-8ec7-8a1c54c80a41.png)

**Comment by ravenbuilder934** [comment]
can you try `/mc colony list` and tell us what's there?

**Comment by firestorm2039** [comment]
> can you try `/mc colony list` and tell us what's there?

says page 0 of 1
< Prev and Next >

**Comment by ravenbuilder934** [comment]
so there are no colonies already, hmm
are you using the build tool to place it? If you are try without it, if you aren't try with it

**Comment by uecasm** [comment]
Usually the best thing to do is to place down the town hall block by hand, right click it and create a colony, then break the block again and place it with the build tool to get the exact style and placement that you want.

**Comment by firestorm2039** [comment]
> so there are no colonies already, hmm
> are you using the build tool to place it? If you are try without it, if you aren't try with it

yeah it says use build tool, or place anyway, when i click place anyway, it just places the item, not a building, but then when i go to place builders hut, it says i need a town hall

**Comment by uecasm** [comment]
You have to place the town hall block, actually create the colony at the town hall GUI, then place the builder's hut, then actually build the builders hut, then finally you can build the town hall.  In exactly that order.  (Well, technically you can delay actually building the town hall as long as you like, but you might as well do it then.)

**Comment by firestorm2039** [comment]
> You have to place the town hall block, actually create the colony at the town hall GUI, then place the builder's hut, then actually build the builders hut, then finally you can build the town hall. In exactly that order. (Well, technically you can delay actually building the town hall as long as you like, but you might as well do it then.)

thank you, that seems to have worked, its got like a fencing around it now that i can walk through, much bigger that the build tool said it was lol.
same with builders hut, it has created 1 person so far. i will try and understand the rest lol

**Comment by Talyda** [comment]
Always make sure to create the building block for the building you want to build, and choose it in the left hand drop down arrow when you want to place it - don't let the left hand drop down say "decorations" it should say whatever building you are trying to make =)


> Usually the best thing to do is to place down the town hall block by hand, right click it and create a colony, then break the block again and place it with the build tool to get the exact style and placement that you want.

This is not the advice that I have ever seen anyone in the mod give, unless there is a problem. Build tool for all buildings except the supply buildings =)

**Comment by ravenbuilder934** [comment]
Well, if it's working now, this can be closed

**Comment by uecasm** [comment]
> This is not the advice that I have ever seen anyone in the mod give, unless there is a problem. Build tool for all buildings except the supply buildings =)

Just for the initial town hall placement.  Once in a while it gets confused when you try to use the build tool to place it and you don't yet have a colony.  Once the colony is set up, then build tool all the way after that.
