### ISSUE TITLE
Latest build throwing exceptions

### ISSUE THREAD

**Issue by smmmadden** [ldtteam/minecolonies#6586]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 36.0.42
- MineColonies Version: 0.13.633
- Structurize Version: 0.13.135
- Related Mods and their Versions:

## Expected behavior

Not throw any exceptions interacting with huts or citizens
## Actual behavior

Having the builder upgrade his hut seems to be throwing out exceptions when providing resources via Fulfill.

There shouldn't be any exceptions/errors in logs interacting with huts or citizens.  Also found several other citizens just frozen in place and not moving or interactable.
## Steps to reproduce the issue

Just had builder start upgrading and provided resources via "Fulfill" in creative mode.  First click of Fulfill seemed to be fine, but after that, each throw an exception.
1. 
2. 
3. 

### Logs

https://pastebin.com/LnuZrwnM

- latest.log: 
- crashlog: 

### Notes

The first login, took me to the builders hut and the builder was in a shaking state (frozen in place).  Trying to interact failed, so I left and came back in and it was okay again (possible path issue?) but it did cause exceptions due to speed for some reason.  I wasn't flying either.  The latest.log link is provided.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by smmmadden** [comment]
Just confirmed it still exists using the latest builds of MineColonies-0.13.634-ALPHA and Structurize-0.13.138-ALPHA.  Seems to be a recursive loop in the packets (at first glance of exception).

**Comment by Raycoms** [comment]
I'll check it out tomorrow then

**Comment by Raycoms** [comment]
Most of this seems combat academy related

**Comment by smmmadden** [comment]
Hi @Raycoms - still seeing exceptions thrown in logs after updating to 0.13.639 and 0.13.139 (Structurize).  Posted latest log in pastebin [here](https://pastebin.com/4bfLPufH).  The warnings at the bottom are coming from the Couriers running around picking up supplies.  The enchanter (Louisa C. Gooder) also throws warnings for fetching packets.
If you need a separate bug, do let me know but they all seemed to have started in build 0.13.633 so hopefully that helps. 
-Steve

**Comment by Raycoms** [comment]
yes, for those we already have a seperate open issue.
