### ISSUE TITLE
SP should use its own config file

### ISSUE THREAD

**Issue by xavierh** [ldtteam/minecolonies#659]
### Minecolonies version

Tested with 1.11.2

### Expected behavior

- SP game which should use its on configuration as in ~/.minecraft/saves/<Game name>/config/minecolonies.cfg if the configuration file exist otherwise it should use ~/.minecraft/config/minecolonies.cfg

### Actual behaviour

- All the SP game use the same configuration file location ~/.minecraft/config/minecolonies.cfg

I use SP when testing. some of my world use instant mining, others use infinite resources, ect... So I can test different part of the mod

**Comment by AndrewTru** [comment]
the thing here is that the more file paths the mod makes the more the computer has to think in order to run them. I get your idea but this seems more a '[request] move some settings to world dependent', @Kostronor What is your take on the matter?

**Comment by xavierh** [comment]
What we are doing for schematic now is MUCH worst.

Did not look to much into it but I suspect the config is loaded only once anyway.

The purpose of this idea is to be able to test specific part of the mod without to have modify the config all the time

**Comment by AndrewTru** [comment]
I am backing you on the idea, this may help out the mod in a good way.
@Kostronor What do you think?

**Comment by xavierh** [comment]
@AndrewTru feel free to implement any of the issue you like and submit a pr.
I doubt this particular one is going to be controversial. ;-)

**Comment by AndrewTru** [comment]
I will keep that in mind, right now the mods skin system is my current request.

**Comment by xavierh** [comment]
It's not the easiest on to start with

**Comment by marvin-bitterlich** [comment]
@AndrewTru Extra config file is a nice thing to have and the overhead is not noticeable

**Comment by marchermans** [comment]
@xavierh @Kostronor @AndrewTru The overhead for the additional file is not worth the note. However the overhead of syncing the config between server and client is a pain.

**Comment by AndrewTru** [comment]
@OrionDevelopment 
You aren't sending the file to and from the computer, Minecraft uses a fake server for SSP activity and from what I can tell you just have to make a small block of code that tell the server the dif from 
W1-config.txt and W2-config.txt, the idea being that some of the mod settings that can be changed in game/in world are saved in a (World name)-config.txt. I understand the idea, I myself have messed with reading and writing files when I had mobile applications at school.

Sadly my current computer will not be able to support the needed IDE and technically I am only advising with the team and not a full member.

**Comment by marchermans** [comment]
@AndrewTru Not to be rude, but i have been developing MC Mods for over 5 Years now (That is nearly a quarter of my life), i now how it works, and no it is not that simple. Forge does not allow you direct access to your config file. They are talking about introducing this kind of behaviour by default.

But for now we would need to code the logic our selfs, which is harder then you think.

**Comment by AndrewTru** [comment]
@OrionDevelopment 
My bad, did not think about that.
So yes, this request is so far : One, talks about another request and Two, is not doable at this time.
so minor issue.

**Comment by xavierh** [comment]
Orion,  why did you close this?

**Comment by Raycoms** [comment]
To make this we would have to write our own "config" system completely.
I wrote in slack to close it because its not worth the work.
We can consider reopening it as soon as forge supports this kind of operations.

**Comment by xavierh** [comment]
You don't need an IDE :)

**Comment by xavierh** [comment]
Got it
