### ISSUE TITLE
Townhall outside colony. and cannot be build

### ISSUE THREAD

**Issue by alexvermaning0** [ldtteam/minecolonies#6593]
### Prerequisites 

- [ ?] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version. (where can i download the alpha builds.)
- [ X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ ?] I made sure that **this issue is not a duplicate of any existing issue.** (can't find it atleast.)

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.13.602-ALPHA-universal
- Structurize Version: structurize-0.13.113-ALPHA-universal
- Related Mods and their Versions: ? DireWolf20 1.16 pack

## Expected behavior

able to place the town hall and play minecolonies
## Actual behavior

if i place the town hall i get the message "The build order for  at x: , z: is outside of the colony and cannot be built!"

## Steps to reproduce the issue
place a supply camp.
place town hall and fail.

1.  place supply camp
2.  place town hall and fail.
### Logs
[latest.log](https://github.com/ldtteam/minecolonies/files/6017809/latest.log)

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
you can get the alphas here: https://www.curseforge.com/minecraft/mc-mods/minecolonies/files/all

also, are you using the build tool to place it? If so, can you send a screenshot of the build tool GUI before you click Confirm?

**Comment by alexvermaning0** [comment]
i just updated with the latest alpha and it works now.
afterwards i tryed the old one again and no issues still so. i don't really know what happend to fix it.
as i tried before posting this a restart and reopening world.
anyways thanks for the link to the builds.
