### ISSUE TITLE
Citizens Won't use Rails

### ISSUE THREAD

**Issue by hobnob11** [ldtteam/minecolonies#6598]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: 0.13.639
- Structurize Version: 0.13.139
- Related Mods and their Versions: Direwolf20-1.16 Pack, latest version (with manually updated MC)

## Expected behavior

Citizens would use the rails to get to where they want to go.

## Actual behavior

The npc's are following the rails, but walking, occasionally one person will use the rails correctly but most will walk
It happens on both flat rails and this "staircase", I have tested extensively with trying to use booster rails to help, but the issue happened with no boosters as well. 

https://gfycat.com/felinereasonableintermediateegret
## Steps to reproduce the issue

1. build an underground village, with the houses etc underground, place a few structures like forester and miner above ground.
2. build a staircase between the two levels, and then place rails on it
3. with the rails research at the university, observe that the majority of citizens refuse to use the rail. 

### Logs

- latest.log: https://gist.github.com/hobnob11/11bf73b128630824a1db51e9ea96e558
- crashlog: N/A

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Have you completed the Rails research?

**Comment by hobnob11** [comment]
Yes
![image](https://user-images.githubusercontent.com/2287055/108857909-7cfe5200-75e3-11eb-90c5-ed5a37c03158.png)

**Comment by someaddons** [comment]
works for me just fine, try updating to the newest

**Comment by hobnob11** [comment]
Just updated to 663 (struct 143) and it appears to be about the same, one or two npc's will use the rails but most wont, going either up or down. https://www.youtube.com/watch?v=09lRg4-Xbp8

**Comment by Raycoms** [comment]
And does this also happen with just one citizen? I saw that one of them was able to do it nicely.

**Comment by hobnob11** [comment]
It appears to be random which citizen will by chance use the rails correctly. in the video you see one of the lumberjacks using it correctly but i've just now watched him walk up the stairs, and i've also seen a guard use the rails correctly, once. 

it kind of looks like the first citizen in the "group" to get to the rails manages it, but the rest of the citizens fail and start climbing

**Comment by Raycoms** [comment]
Can you show me the start of the rails?

**Comment by Raycoms** [comment]
Bug found (forge bug)
