### ISSUE TITLE
ask for permission to create a fabric api port of the mod

### ISSUE THREAD

**Issue by pheonixfirewingz** [ldtteam/minecolonies#6599]
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

- Minecraft Version: 21w7a
- MineColonies Version: would have own version
- Structurize Version: would have own version

**Comment by ravenbuilder934** [comment]
To be clear, you want to port MineColonies to fabric?

**Comment by pheonixfirewingz** [comment]
yes

**Comment by pheonixfirewingz** [comment]
it will stay under the same license and I would add you as authors as it is a port of the codebase

**Comment by Raycoms** [comment]
In general you can do whatever our license allows you to do. However, we cannot offer support for that. and we cannot offer ongoing support after a fabric port. Similarly, only the default citizen texture sets can be used in such a port and the name "Minecolonies" cannot be used for publication on curse.
