### ISSUE TITLE
Builder stuck at 50%

### ISSUE THREAD

**Issue by V3RSBurst** [ldtteam/minecolonies#6603]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16
- MineColonies Version: 1.16

### Logs

- latest.log: 

## Steps to reproduce the issue / details
Building the spruce sawmill, and the builder has 0 building requests. Progress says 50%, but as soon as they go to the sawmill they just stand on top of the building block. 

Just reporting the AI issue. 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
This is most likely not a bug, can you join our discord to discuss there? https://discord.minecolonies.com
