### ISSUE TITLE
Apiarist ignores true drops of Resourceful Bees

### ISSUE THREAD

**Issue by truenachtara** [ldtteam/minecolonies#6607]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.13.643-ALPHA
- Structurize Version: 0.13.139-ALPHA
- Related Mods and their Versions: resourcefulbees-1.16.5-0.5.9_3b

## Expected behavior

Apiarist obeys the items produced by ResourcefulBees

## Actual behavior

Apiarist only checks if the hive is ready to harvest and collects three vanilla honeycombs.

![image](https://user-images.githubusercontent.com/16340367/109101579-9a6b1300-76ec-11eb-8ae8-835f643d8a07.png)
![image](https://user-images.githubusercontent.com/16340367/109101590-a060f400-76ec-11eb-96e3-5c55c2aaba99.png)
![image](https://user-images.githubusercontent.com/16340367/109102111-bde28d80-76ed-11eb-94fb-c0056ce47775.png)

## Steps to reproduce the issue

1: Install Resourceful Bees, launch and close to generate config folders.
2: Put the following JSON into /config/resourcefulbees/bees and save it as `creative.json`: https://pastebin.com/PwJTpJpQ
3: Save the following two images into /config/resourcefulbees/resources/assets/resourcefulbees/textures/entity  and save as `creative.png` and `creative_angry.png` respectively: 
![creative](https://user-images.githubusercontent.com/16340367/109101900-4280dc00-76ed-11eb-953e-9135885e45b7.png)
![creative_angry](https://user-images.githubusercontent.com/16340367/109101904-43b20900-76ed-11eb-8d53-f99c25b2c598.png)
4: Set up the apiarist to farm a Resourceful Bees beehive (any tier). The creative bee has extremely fast production and produces a non-vanilla-comb item (apples, instead). Wait for him to collect the items from the hive.
5: The apiarist will collect 3 vanilla honeycombs rather than the custom items.

### Logs

- latest.log:  https://gist.github.com/truenachtara/d07e445588a31efa64947f3ec79356bd
- crashlog:  No crashlog

### Notes

None extra

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
https://github.com/ldtteam/minecolonies-features/issues/135
