### ISSUE TITLE
Miner builds a mine hole in the air

### ISSUE THREAD

**Issue by realm174** [ldtteam/minecolonies#661]
### Minecolonies version

version 1.10.2-0.6.2941 or curse X.X.XX

### Expected behavior

- Miner mines, or fixes his mining area

### Actual behaviour

- Miner built a structure in the air

### Steps to reproduce the problem

Not sure if it is reproducible, but my miner was taking blocks away from its original structure for no apparent reason. Tried recalling to his block, recalling to townhall, he still went back to doing that. Fired him, re-hired, same behavior. Fired him, hired someone else, he just stood in place. I figured it might be because original structure was damaged, so I did a "repair", and provided the materials he's been asking for. This is the result (he's not completely done yet) attached.
![2017-02-27_07 26 38](https://cloud.githubusercontent.com/assets/7480440/23365230/7f9279c0-fcbf-11e6-9a39-181d7719bdcd.png)

**Comment by Raycoms** [comment]
Never seen that. It seems like the ladder position got damaged and then
afterwards even the complete building position =O

2017-02-27 11:37 GMT-03:00 realm174 <notifications@github.com>:

**Comment by realm174** [comment]
Well, the first block the original miner took out was that plank above ground level where the first ladder is attached to., so yes, that would have been a damaged area...

**Comment by Raycoms** [comment]
Are you able to reproduce that?


2017-02-27 11:59 GMT-03:00 realm174 <notifications@github.com>:

**Comment by realm174** [comment]
I've tried a few different things, but was not able to reproduce that behavior yet. I thought it might have been due to the lumberjack planting trees too close, but that doesn't seem to result in that behavior.

**Comment by marvin-bitterlich** [comment]
closing for now
