### ISSUE TITLE
Archers in Training do not Train or use Their Beds

### ISSUE THREAD

**Issue by rjezak** [ldtteam/minecolonies#6613]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16
- MineColonies Version: 0.13.643-ALPHA
- Structurize Version:0. 13.139
- Related Mods and their Versions:

## Expected behavior

Archers in training would normally train at their archery range, requesting and using bows to fire during the day. They'd level up in the process. At night they would then go to the beds in the range to sleep.

## Actual behavior

Currently archers in training do nothing but wander aimlessly around their hut block, sometimes flying through the air in the process. At night they do the same, showing that they are trying to sleep but making no attempts at pathing towards the beds and just clustering around the hut block. 

## Steps to reproduce the issue

1. Build an archery range, in my case a Medieval Oak of any level
2. Assign citizens to train and supply them with bows
3. They'll refuse to train or sleep

### Logs

- latest.log: https://gist.github.com/rjezak/1f1b23e7eeb2b8788339b6320924506d
- crashlog: NA

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
We'll need more info, which building level and which style are you using?

**Comment by rjezak** [comment]
Medieval Oak (Not alternate) as I said, archers wouldn't train at any level though the building is currently level 5.

**Comment by Raycoms** [comment]
Are there target blocks in the schematic?

**Comment by rjezak** [comment]
There are not, which I found strange as I recalled that being updated previously. Currently just the older style of hay blocks with buttons on them.

**Comment by rjezak** [comment]
Did just a bit more digging on it, replacing the hay blocks in the building after it's been built doesn't seem to affect things. Additionally, when I try to sleep in one of the beds at night, it says the bed is occupied but not the usual Minecolonies tile.bed.occupied chat message, rather one like the Vanilla messages regarding beds.

**Comment by Raycoms** [comment]
yeah it must be in the schematic. Are there blocks over the bed, like signs or so?

**Comment by rjezak** [comment]
Makes sense. And there is a torch over one of the beds, nothing over the other four however.

**Comment by ravenbuilder934** [comment]
Does this still happen in the latest version? (Try triggering a repair on the archery as well)

**Comment by rjezak** [comment]
Unfortunately I lost the colony where I had the original issue. Updated the mod without making a backup some months back and the colony was deleted. 

Testing it on a new world however, it seems to function perfectly. The schematics have been replaced with target blocks and they train properly.
