### ISSUE TITLE
Stonesmelter AI error

### ISSUE THREAD

**Issue by boomyuri** [ldtteam/minecolonies#6616]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.13.642-ALPHA-universal

### Logs

- latest.log: https://gist.github.com/boomyuri/57ee8eed92135f1b58465342a76c11f7

## Steps to reproduce the issue / details

Just reporting the AI issue. 

### Notes
Just added a few mob mods concerning their enchanting and all but I doubt this caused the problem as only my Stonesmelter is the one having the AI error.

Send help :(

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
There seems to be an invalid recipe with no input, but existing output in the hut. Remove that recipe and teach a new one to fix it.

**Comment by Raycoms** [comment]
Please re-open if that doesn't fix it.
