### ISSUE TITLE
ma cytoyen a disparue et ne revient pas quand je fait rappeler le cytoyen

### ISSUE THREAD

**Issue by Yanncm** [ldtteam/minecolonies#6617]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- MineColonies Version:

### Logs

- latest.log: 

## Steps to reproduce the issue / details

Just reporting the AI issue. 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Will need logs and fille din template
