### ISSUE TITLE
Builder hit an AI issue

### ISSUE THREAD

**Issue by EliotWL** [ldtteam/minecolonies#6620]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.13.629-ALPHA-universal

### Logs

- latest.log: https://gist.github.com/EliotWL/89b710e7212837862de6def6b416e247

## Steps to reproduce the issue / details

Just reporting the AI issue like the builder told me to.

### Notes

 Was building the Combat Academy.  Am playing on peaceful in creative on a super flat world, in case that matters.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Please update, you're over 10 versions behind and there have been several fixes lately
