### ISSUE TITLE
Builder hit AI issue

### ISSUE THREAD

**Issue by EliotWL** [ldtteam/minecolonies#6621]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.13.643-ALPHA-universal

### Logs

- latest.log: https://gist.github.com/EliotWL/81fc233a58648ec07fa24637e78ca948

## Steps to reproduce the issue / details

Just reporting the AI issue as the builder told me, post update. 

### Notes

Previously reported this at #6620.  Was told to update.  Updated, canceled the build request, reset the build request to a different builder.  Same AI issue came up.
  Same info as last time, super flat world, peaceful and creative.  Builder has all needed materials. Attempting to build the combat academy.  Have already built barracks and researched the required research in the university.  Nordic style combat academy.
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Log doesn't contain any builder exception. Builder doesn't always work on superflat world (they can't break blocks below y = 5), did yout ry to make the world thicker?

**Comment by EliotWL** [comment]
Figure out the issue.  The boundaries of the build were below bedrock...

**Comment by uecasm** [comment]
It's a good idea to use the Overworld superflat preset instead of the default one, so that the ground thickness is the same as normal.  Means that the miner works normally as well.
