### ISSUE TITLE
Delivery AI NullPointerException

### ISSUE THREAD

**Issue by Nubsi-DE** [ldtteam/minecolonies#6622]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5-forge-36.0.14
- MineColonies Version: 0.13.602-ALPHA

### Logs

- latest.log: https://gist.github.com/Nubsi-DE/0f90ae711af795e131ac2653eef24aa7

## Steps to reproduce the issue / details

Just reporting the AI issue. 

### Notes

I just saw a Gear above my Delivery Girl while she was working. She told me to report this issue.
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Duplicate issue
