### ISSUE TITLE
Asian Buildings Not Upgradeable

### ISSUE THREAD

**Issue by mrfunbeard** [ldtteam/minecolonies#6630]
### Prerequisites 

- [ x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.3
- MineColonies Version: unknown (the one included in valhelsia modpack, hopefully current)
- Structurize Version: unknown (the one included in valhelsia modpack, hopefully current)
- Related Mods and their Versions: valhelsia 2.3.1

## Expected behavior
i would expect to be able to upgrade asain player houses and decorations

## Actual behavior
upon attempting to upgrade asian decorations it tells me the decoration is unupgradeable or at max level. I am unable to upgrade anything past level 1

## Steps to reproduce the issue

1. build level 1 asian decoration
2. try and upgrade it
3. it tells you you are unable

### Logs

- latest.log: 
- crashlog: 

### Notes
i apologize i dont hav more information than that given

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
If you're still on 1.16.3 your mcol and struct versions are likely very out of date. There have been lots of schem fixes lately, so updating should fix it
