### ISSUE TITLE
Game Crashes when interacting with builder npc.

### ISSUE THREAD

**Issue by bgHunterr** [ldtteam/minecolonies#6631]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.13.659-ALPHA-universal
- Structurize Version: structurize-0.13.139-ALPHA-universal
- Related Mods and their Versions: -

## Expected behavior
Not to crash when trying to fulfill citizens needs.
## Actual behavior
As soon as I open builder's inventory or needs game crashes.

## Steps to reproduce the issue

1. Start the game and join server
2. Interact with builder and after 5 seconds
3. Game crashes

### Logs

- latest.log: https://gist.github.com/bgHunterr/0619df1a947dc03e6956c17f079df106
- crashlog: https://gist.github.com/bgHunterr/5aed4ed1b2705814262bf893575a6430

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Some tool mod is returning a bad value. Remove mods to narrow it down, then report to them

**Comment by bgHunterr** [comment]
Thanks for the quick reply!
