### ISSUE TITLE
Builder wanders around aimlessly while building Towncenter

### ISSUE THREAD

**Issue by SanderKnauff** [ldtteam/minecolonies#6632]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: 0.13.659-ALPHA
- Structurize Version: 0.13.139-ALPHA

## Problem description
My builder seems to wander around aimlessly while building a medieval oak towncenter. It often tries to go on the roof or on top of surrounding trees and seems to pathfind to "some" place in the air. I cannot figure out what it could be.

I've restarted the building process multiple times with different builders as well.

The builder has the required tools and is not requesting any new resources. 
### Notes or related things
A builder hut is present and the builder has build a tavern without issue. It does not seem to be able to finish the Towncenter.
This server runs Direwolf20 1.16 1.2.0 pack with manually updated Structurize and Minecolonies.

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
was this medieval oak alternative?

**Comment by SanderKnauff** [comment]
> was this medieval oak alternative?

Yes, I forgot to properly mention that.

I tried to debug it with the pathfinding debug tool, but that did not seem to work on the server. Although while tested locally, I don't think that would've given me any valuable information as it just shows where they're walking to and not what their current target block is. 
Perhaps a way of displaying the NPC's current target might help find out what the issue was, although the server owner has already forced the building into existence so I'm currently not facing the problem

**Comment by ravenbuilder934** [comment]
yes, the medieval alts are kinda bugged atm. A different style should work (but too late now anyway)

**Comment by Raycoms** [comment]
Nah there is a pathing bug I'm tracking down.
