### ISSUE TITLE
Versorgungcamp Falsch plaziert, dann komplett per Hand abgebaut und kann kein neues Stellen.

### ISSUE THREAD

**Issue by XDennisXD** [ldtteam/minecolonies#6637]
Ich habe auf einen Server ein Versorgungscamp gebaut und musste es nochmal abreißen weil es nicht so plaziert war wie es eigentlich sollte. Jetzt habe ich das Problem das dass Spiel jetzt sagt das ich schon ein platziert habe, ich es aber komplett abgebaut habe. Ich kann auch nix anderes Bauen lassen. Was soll ich jetzt machen damit es wieder geht. Spiele auf der 1.16

**Comment by Asherslab** [comment]
english please. while this community does have members who speak german we provide support in english.

**Comment by Raycoms** [comment]
Please visit us on discord for this, this is not a bug, it's a gameplay thing
