### ISSUE TITLE
I can't use the stable version

### ISSUE THREAD

**Issue by LionZXY** [ldtteam/minecolonies#6641]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.13.663
- Structurize Version: 0.13.143

## Problem description
Now I'm trying to use this mod and I notice that the latest alpha has a lot of bugs. Both already confirmed, as well as unreported. I tried to use the latest release version, but it does not work for known reasons. (https://github.com/ldtteam/Structurize/issues/287)
I am tired. Infinitely tired of the instability and dampness of alpha builds. This is fine for the alpha version, but you don't have a release version. Absolutely all of the mod's artifacts are broken and very difficult to use.
Perhaps it's time to code-freeze for the current build and create a release?

### Notes or related things
- Last release update (Nov 9, 2020): https://www.curseforge.com/minecraft/mc-mods/minecolonies/files/3106617

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
There is a beta.

**Comment by LionZXY** [comment]
Do I understand correctly that you do not have any open bugs for beta? Are you sure you understand the concept of stable release?

**Comment by Raycoms** [comment]
Are you sure you understand the concept of work in progress and open source FREE content?

**Comment by Raycoms** [comment]
And yes, you're blocked, and don't come back, uninstall our mod, we don't want toxic people that don't appreciate our work in our community. Thanks bye.
