### ISSUE TITLE
Builder can't upgrade barracks to lvl 3

### ISSUE THREAD

**Issue by Powerminer11** [ldtteam/minecolonies#6646]
- [x ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [ x] I made sure that **this issue is not a duplicate of any existing issue.**

Version: 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.13.6.60-BETA

The issue and how to reproduce it:
The builder is upgrading the barracks to lvl 3 caledonia style. Towards the end of the project he has 7 brown carpets, 5 spruce buttons, and 49 lanterns left to place. He has the brown carpets in his inventory, but the lanterns are back in his hut. All he does is walk around the building doing nothing. I have tried to cancel the build and start again. I have tried to switch to another builder but the problem persists. He just can't finish the building. It has been like this for hours, so I don't think this is supposed to happen.

Reproduce the issue by upgrading the barracks from lvl 2 to lvl 3 with the caledonia style

Log:
https://paste.ubuntu.com/p/FtgtM6CN5K/

**Comment by ravenbuilder934** [comment]
Can you try updating? 660 beta is a bit out of date

**Comment by Raycoms** [comment]
We'll be pushing a new beta out soon with a fix, so far, the newest alpha solves this problem

**Comment by Powerminer11** [comment]
Where can I find this? I thought I had the latest version. I downloaded the most recent file from this link https://www.curseforge.com/minecraft/mc-mods/minecolonies/files

**Comment by Talyda** [comment]
Scroll down that page and look for the "view all" link =)
*edits* actually, you can just add the word "all" to the link you used =)
https://www.curseforge.com/minecraft/mc-mods/minecolonies/files/all

**Comment by Powerminer11** [comment]
Thanks!

**Comment by Powerminer11** [comment]
Update: With latest alpha the builder is stuck in the animation of placing spruce fences without actually placing them, and without having any fences in his inventory. (barracks lvl 3 caledonia)

**Comment by Raycoms** [comment]
Are they requesting them?

**Comment by Powerminer11** [comment]
No, they are not requesting anything

**Comment by Powerminer11** [comment]
Just updated to alpha 669, And the issue is solved. There is however another problem, I'll make a new thread about it
