### ISSUE TITLE
Friends cant build buildings 

### ISSUE THREAD

**Issue by DrakeniWolf** [ldtteam/minecolonies#6651]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version:
- Structurize Version:
- Related Mods and their Versions: Life in a vilage 2

## Expected behavior

= I would have more fun couse my friend started the town hall, but i cant build unless i make my town hall.
## Actual behavior

= I am a builder and wanted to make houses while my friend does the tehnical stuff in a mod pack so what happened is that i still cant build unless i make my own town hall but than it woudnt count in the other one.

## Steps to reproduce the issue

1.  One build town hall and invites the other in there party
2.  the other tries to build anything not related to a decor or a town hall
3.  cant do anything.

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
You should read the wiki, especially the parts about the town hall permissions and protection system.  If you have further questions, join the Discord and ask there rather than jumping straight to creating issues.

**Comment by DrakeniWolf** [comment]
Im pretty sure you need to learn how to read its not the permissions its the acuall building im an officer of a friends clan thing and i cant build any of his stuff only a new collonie lol

**Comment by Nightenom** [comment]
Update your versions to latest alpha, also in 1.16 this works perfectly, not sure about 1.15

**Comment by DrakeniWolf** [comment]
But its a modpack the other mods wont work than in 1.16

**Comment by Nightenom** [comment]
you can still update to latest 1.15 tho

**Comment by Raycoms** [comment]
Even though you're an officer, there are still fine grained permissions, your friend has to make sure that building management is also turned on there.
