### ISSUE TITLE
Research-related log spam

### ISSUE THREAD

**Issue by Inomutso** [ldtteam/minecolonies#6656]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: forge-1.16.4-35.1.4-installer.jar
- MineColonies Version: minecolonies-0.13.670-ALPHA-universal.jar
- Structurize Version: structurize-0.13.146-ALPHA-universal.jar
- Related Mods and their Versions:
 1.741.346 furniture-7.0.0-pre19-1.16.3.jar
 8.109.657 ImmersiveEngineering-1.16.4-4.1.1-128.jar
 663.601 mcw-doors-1.0.1fix-mc1.16.4.jar
 4.309.452 worldedit-forge-mc1.16.3-7.2.2-dist.jar

## Steps to reproduce the issue

1. start the colonie
2. 
3. 

Hi there

a few releases ago, you have changed something with the research System
since then, I see a huge amount of entries in my latest.log and debug.log
this is slowing down the performance within the colonie
my colonie was already full researched, but with the change, I had to do all the research again, they were all lost

Could you please have a look into my log´s, maybe you can see something about the reasons.

Today I started the colonie at [04Mär2021 10:31:10.570] and stopped at [04Mär2021 12:56:24.796]
the latest.log is right now  "04.03.2021  12:56   420.150.146 latest.log" big.

sorry i could not use gist for the logs, gist is crashing with that logfile size

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
I don't see where you attached the logs?

**Comment by gattsuru** [comment]
If Gist isn't accepting the full logs, copying a few snippets including the specific error messages would be helpful, as would describing your situation.  Are you connecting to a remote server, playing single-player, running "Open to Lan mode"?

There's a PR to reduce a few extraneous logs in review, but they're relatively small things and shouldn't be enough to bloat a file that amount or cause significant slowdown.

**Comment by Inomutso** [comment]
I saw a zip File uploading here, but I cannot see it either

playing this in a single Player World, playing local 

I started the colonie just for 2 Minutes and you can find the debug.log here

https://gist.github.com/Inomutso/726109c975db6fd5f2ac4173ef2daa62

**Comment by gattsuru** [comment]
Huh.  I'm not sure what's causing that; it's acting like the save contains a lot of completed researches that aren't being loaded, but the research ids are all properly formed, and the data loader is at least registering the correct count of researches.  And the research ids match a proper migration from the previous string-based format.  Adding those four mods doesn't trigger the same behavior on multimc instance on a Windows machine.

Does this occur on new worlds (such as a creative world, where research will complete nearly-instantly), as well, if you close and reopen the world?  EDIT: can you upload the `.minecraft/saves/<worldname>/data/capabilities.dat` from your normal current world, the one that's showing the problem?

**Comment by Inomutso** [comment]
I have given up this colonie for now, I think I cannot fix this anyhow, maybe you can, but this is not very important for me anymore

I have started a new colonie now, playing on 1.16.5, but I can see Issues here too

[05Mär2021 10:50:41.741] [Server thread/FATAL] [net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Server
java.lang.NullPointerException: null
or
[05Mär2021 10:29:02.786] [Render thread/WARN] [net.minecraft.loot.LootTableManager/]: Found validation problem in {minecraft:chests/village/village_plains_house}.pools[1].entries[0]: Unknown loot table called null
[05Mär2021 10:29:02.786] [Render thread/WARN] [net.minecraft.loot.LootTableManager/]: Found validation problem in {minecraft:blocks/acacia_button}.pools[1].entries[0]: Unknown loot table called null
[05Mär2021 10:29:02.786] [Render thread/WARN] [net.minecraft.loot.LootTableManager/]: Found validation problem in {minecraft:blocks/soul_campfire}.pools[1].entries[0]: Unknown loot table called null

this is also in a single Player World, just have the town hall, a university and 4 citizens up

anyway, I uploaded the capabilities.dat from the 1.16.4 colonie as requested

hope you can see something there, you can also have the whole colonie, if that would help

(I had to change the extension from capabilities.dat to capabilities.txt, else no upload here)

[capabilities.txt](https://github.com/ldtteam/minecolonies/files/6090536/capabilities.txt)

**Comment by gattsuru** [comment]
There's a fix for the log spam and inconsistent progress in review.  It should solve your issues with your previous world.

The LootTableManager spam is an irritating vanilla thing, and has no impact.  The ThreadTask one may be meaningful or not, depending on context, but if there are no visible bugs, I'd not worry about them.

**Comment by Inomutso** [comment]
thx

**Comment by ravenbuilder934** [comment]
The fix isn't in the mod yet; it's still in review
