### ISSUE TITLE
Pig farm npc has an AI issue

### ISSUE THREAD

**Issue by ruestJS** [ldtteam/minecolonies#6663]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16
- MineColonies Version: 0.13.643-ALPHA
- Modpack : Valhelsia 3 v3.1.9

### Logs

- latest.log: 

## Steps to reproduce the issue / details

Just reporting the AI issue. 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
where is the log?

**Comment by ruestJS** [comment]
https://gist.github.com/Davoskaa/e1d6fc4e71a1bdc83d817c3bbe03bf71 (think i just wrote it up in the wrong place in the file)

**Comment by ravenbuilder934** [comment]
Can you try updating? we're in the 670s now

**Comment by ruestJS** [comment]
Imma try, i'm using a modpack (valhelsia 3 latest version) so i hope it doesn't affect everything :o

**Comment by ravenbuilder934** [comment]
Should be fine, as long as you're not on a server and you update Structurize too

**Comment by ruestJS** [comment]
Oh, i'm actually on a server and everyone's using the same modpack so it might be a bit annoying since they'd have to update it manually in their folder

**Comment by ravenbuilder934** [comment]
True
Also, keep it PG please (no swearing)

**Comment by ruestJS** [comment]
Oh my bad, edited the comment, didn't meant to!

**Comment by ruestJS** [comment]
Update: The sheep dude also has the same problem now, he asked me for a wooden axe, i pressed "i will work on it" and it bugged (My ai has run into an issue! please locate.......)

**Comment by Raycoms** [comment]
Please report here: https://github.com/stal111/Forbidden-Arcanus/issues

Their mod throws an exception when our citizens kill an entity.
