### ISSUE TITLE
structure issues (maybe solved but the question stills)

### ISSUE THREAD

**Issue by MrV0DkAa** [ldtteam/minecolonies#6664]
Hello, I started to play the ATM6 Modpack and I found your mod (that I loved)

I started to understand your mod, how it works but some buildings seams like bugged in some sites... I tryed to reapair and the error/bugs still the same 

I'm playing 0.13.610-ALPHA version, not the early but is that a version problem??

And if it is, I already have Townhall lvl3, builder's lvl5, farm's, university, hospital, library, miner etc etc etc and I don't want to lose all of that data that I already did. If I upgrade will i lost that buildings and quest and all of that stuff? Or is a method to update without losing anything? 

Thanks for your time, really apreciate that!

**Comment by MrV0DkAa** [comment]
I'm playing in a local server with a friend of mine (IDK if that makes any difrence or not)

**Comment by Raycoms** [comment]
Please fill in the entire template. Updating doesn't lose you anything, so please update and open a new Issue if the problem persists and with the full template.
