### ISSUE TITLE
Warehouse bugged

### ISSUE THREAD

**Issue by GoodPasi** [ldtteam/minecolonies#6665]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version:
- Structurize Version:
- Related Mods and their Versions: Valhelsia 3 Modpack

## Expected behavior

removed warehouse wont get regcognized by the game

## Actual behavior

game still thinks the warehouse i broke is there it wont let me build a new one the courier will walk there and try to interact with it as normal but its gone

## Steps to reproduce the issue

1. place warehouse
2. remove it
3. bam bugged invisible unaccessible warehouse

### Logs

i play on a server with friends if they are badly required i can see to get them

- latest.log: 
- crashlog: 

### Notes

the old warehouse already didnt rly work properly thats why i removed it the request system and courier seems to work fine but he only stood still next to the warehouse block and emptied his inventory into it infinitly doing nothing else 

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Did restarting the server fix it? Did you try mining it?

**Comment by ravenbuilder934** [comment]
@GoodPasi

**Comment by Raycoms** [comment]
closed after 2 weeks no response and no way to reproduce it
