### ISSUE TITLE
Display bug of NPC skill points

### ISSUE THREAD

**Issue by Micoumi** [ldtteam/minecolonies#6666]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.645-RELEASE-universal

### Logs

- latest.log: 

## Steps to reproduce the issue / details

hello sorry if my english is not good, i am french.
Here we have started a server in 1.15.2, everything is perfect except for one thing: we do not see the skill points of our NPCs and we therefore do not know how to disperse them.
We thought that it came from the resource pack but ultimately not because we remove it, then we thought of optifine but no, it is not that too.
I don't know if this is a problem or not because usually we play in 1.12.2 but we saw the skill points of the NPCs but the no so did you know how to solve this?

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Sorry, 1.15 isn't getting updated any more so this won't get fixed.
