### ISSUE TITLE
Town Hall Crashes Upon Opening

### ISSUE THREAD

**Issue by BirdsShade** [ldtteam/minecolonies#6669]
### Prerequisites 

- [ x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.3-forge-34.1.42
- MineColonies Version: 0.13.675
- Structurize Version: 0.13.148
- Related Mods and their Versions:

## Expected behavior

 The town hall upon being placed and having been confirmed that I would like to start a new colony should open to allow me to access the regular town hall menu.
## Actual behavior

 With the structurize tool I manipulated the preview to where I would like, after three different worlds it does not appear that the amount of manipulation factors into the crash. Upon placing it where I would like, I clicked the town hall block and clicked confirm for creating a new colony. I then clicked the town hall block again and the screen froze. It was about five seconds across all three attempts in which Minecraft was completely frozen. I then got pushed out to the Minecraft menu with the message, 'NoSuchMethod'.

## Steps to reproduce the issue

1.  Grab a structurize tool and a town hall, when placing the town hall, confirm you would like to move it with the build tool first.
2.  Manipulate the town hall with the build tool, then place it. Once placed, confirm you would like to start a colony, then click on the town hall again.
3.  This should crash Minecraft.

### Logs

- latest.log: 
- crashlog:  Bird's ShadowToday at 5:28 PM
https://pastebin.com/WU8aCpzw

### Notes

 I do play with Biomes'O'Plenty. However, this does not seem to affect the issue, as I tried this in the Mountains biome, a Plains biome, and a Marshy biome.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
Possibly something 1.16.3-specific?  You could try updating to 1.16.4 or 1.16.5 to see if it goes away.

**Comment by Nightenom** [comment]
Reinstall forge, check if mc version is a problem (as noted above), if that doesn't help send us full latest.log (you should do that when posting as the template ask for it)

**Comment by Raycoms** [comment]
No answer in 6 days, update must've fixed it.
