### ISSUE TITLE
Building style changed after update

### ISSUE THREAD

**Issue by Uwanami** [ldtteam/minecolonies#6670]
### Prerequisites 

- [x] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- Structurize Version: 0.13.148-ALPHA-universal

## Problem description

After updating Minecolonies to newest version (0.13.675-ALPHA-universal) style in the build menu of my alternative asian buildings changed to acacia. 

### Notes or related things

I notice that my builder complained he didn't sleep for few days so at night I checked and I noticed all citizens from my lvl 5 alt. asian house are gathered in from of house build block instead of going to bed. I tried to repaired the house (changing the style in menu back to alt. asian from acacia) but nothing happens. Same problem with alt. asian guard tower (lvl3)
![2021-03-05_22 08 53](https://user-images.githubusercontent.com/65950099/110191725-a8dbcc00-7e5c-11eb-9654-ebf03378225f.png)

---
![2021-03-06_08 22 29](https://user-images.githubusercontent.com/65950099/110191852-4c2ce100-7e5d-11eb-9642-4e9a8bd8f159.png)
![2021-03-06_08 22 15](https://user-images.githubusercontent.com/65950099/110191853-4df6a480-7e5d-11eb-80e8-ce367eb54cb6.png)

## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
What did you update from and to?

**Comment by ravenbuilder934** [comment]
I think the issue was that there was a misspelled `asianalterantive` folder and `asianalternative`, and you placed the first (which was deleted in the update).

**Comment by Uwanami** [comment]
Thanks for the quick answer.
I'm not sure which version exactly is was before (I updated to latest beta in end ). Is there a way to fix it without deconstructing buildings by hand? I tried to set builder to deconstruct but request wasn't created.

**Comment by Raycoms** [comment]
If you setup a valid builder deconstruct should work fine.

**Comment by uecasm** [comment]
If selecting a specific builder to deconstruct doesn't help, as a last resort (if single player or OP) you should be able to go into creative mode, then break the hut block, then paste a replacement building of the appropriate style and level over the top using the right-hand blue button in the build tool.

**Comment by Raycoms** [comment]
Please reopen if you still got issues with deconstruction in the latest
