### ISSUE TITLE
WindowGuardControl cause a large lag

### ISSUE THREAD

**Issue by Windmill-City** [ldtteam/minecolonies#6672]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.16.5
- MineColonies Version:0.13.675-ALPHA
- Structurize Version:0.13.148-ALPHA

## Expected behavior

no lag
## Actual behavior

mouse move slowly

## Steps to reproduce the issue

1. Sneak and use Guard Tool
2. the GUI is opened
3. move the mouse

### Logs

- latest.log: https://gist.github.com/Windmill-City/2f4f879d2c188236a538d9e9f52d1897

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
could you make a client side spark or similar profiler report?

**Comment by Windmill-City** [comment]
![QQ截图20210307120419](https://user-images.githubusercontent.com/14292823/110228586-46a6c800-7f3d-11eb-9cf9-06d3a5ff9dfd.png)

**Comment by Windmill-City** [comment]
onUpdate take most of time

**Comment by Windmill-City** [comment]
![2021-03-07_12 06 14](https://user-images.githubusercontent.com/14292823/110228632-94233500-7f3d-11eb-93a1-d3f3ef0fef11.png)

**Comment by Raycoms** [comment]
Can I get the full profile report, because I want to know what in onUpdate causes it exactly

**Comment by Windmill-City** [comment]
i use jvisualvm, can just profile method level

**Comment by Raycoms** [comment]
Can you export the profile?

**Comment by Windmill-City** [comment]
[WindowGuardControl.zip](https://github.com/ldtteam/minecolonies/files/6097028/WindowGuardControl.zip)
