### ISSUE TITLE
MineColonies Miner AI error

### ISSUE THREAD

**Issue by Rozerov66** [ldtteam/minecolonies#6673]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: Minecraft 1.16.5
- MineColonies Version: 0.13.673-ALPHA

### Logs

- latest.log: https://gist.github.com/Rozerov66/245216233b0eca552e46f04cb58bf98f#file-latest-log 

## Steps to reproduce the issue / details

Just reporting the AI issue. 

### Notes
 I left my laptop open with Minecraft on pause. Before I went to sleep there didn't seem to be a problem. After I woke up there was an error. I wish I could give more context.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
That's fixed in the latest.
