### ISSUE TITLE
Suggestion: implament the "campsite" option  [$5]

### ISSUE THREAD

**Issue by Kellochli** [ldtteam/minecolonies#668]
### Minecolonies version
future version
### Suggestion
as mentioned in the Discord chat, implament an option for making the "supply ship" a "campsite" instead of a ship.
#BlameWissi

**Comment by Wissi** [comment]
LOL.... #BlamePMardle  he posted the concept and initial design in the Patreon section of the Forum.

It is a GREAT idea, much easier to place a "Land Based Supply Camp" anywhere (just clear a bit of land) than trying to find an adequate stretch of water. 

Many have been asking for this option in game and with the 3-D rendering before placement (which should be a MUST for the Supply Ship as well) it should be much easier.

Quote: "So we are adding a land based version of the Supply Ship.. the Supply Camp..
 This will likely be an either or.,. you can have a ship or a camp not both, but perhaps we will add a config file option for people to choose whether this is the case"

**Comment by Raycoms** [comment]
We could vary the recipe but only accept the placement of one of both.

2017-03-03 13:22 GMT-03:00 Wissi <notifications@github.com>:

**Comment by Wissi** [comment]
Yep that is what was initially proposed by Pmardle:

Quote: "So we are adding a land based version of the Supply Ship.. the Supply Camp..
 This will likely be an either or... you can have a ship **or** a camp **not both**, but perhaps we will add a config file option for people to choose whether this is the case".

Not sure if the final design of the Camp is done or the code, the forum thread in the Patreon section has no more info.

**Comment by pmardle** [comment]
Camp was designed and scanned before.. still have it if you need a re-scan

**Comment by Wissi** [comment]
Well since the recipe is done and also the schematic, it can be implemented soon? 
So as to calm down all the ppl in the server that want it.. xD

**Comment by Wissi** [comment]
Uuummm...... Doable?
Since the World border has been widened (on official server), more player will be able to connect. Can it be included?

**Comment by marchermans** [comment]
I might take a look at this if the schematic is in the repo

**Comment by Wissi** [comment]
Pmardle has the schematics (according to him it should be in the repo) if not he says (3 posts before this one) he can provide it if needed.  
Thanx.

**Comment by Raycoms** [comment]
yeah but its only as .schematic in the repo and not as .nbt like we need.

2017-03-23 15:50 GMT-03:00 Wissi <notifications@github.com>:

**Comment by pmardle** [comment]
I NBT'ed it for someone a week or two ago..

**Comment by pmardle** [comment]
Went to Opmis on March 11th :P

Try the attached..  For some reason when downloading from Slack, it changes
the extension to .gz  I manually changed it back to .nbt.. hope it still
works.

**Comment by Wissi** [comment]
Sssooo... any update on this? 
Ppl keep asking in game and in Forum as well. 
Maybe even as a decoration for the people that already have a ship placed as well?
