### ISSUE TITLE
Support for Resourceful bees mod 

### ISSUE THREAD

**Issue by avidgamer5918** [ldtteam/minecolonies#6686]
### Prerequisites 

- [ x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.16.5
- MineColonies Version:0.13.670
- Structurize Version:0.13.146

## Problem description
Hello, I was wondering if you can add support for the Resourceful Bees mod. Currently, the beekeeper will detect the hive but will only get regular vanilla combs from a resourceful bee's hive, not the comb it's supposed to be like gold for instance. If you could add support for this that would be awesome
Thank you for your time
-Avid Gamer

### Notes or related things

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
ldtteam/minecolonies-features/issues/135

**Comment by ravenbuilder934** [comment]
This is actually in progress btw
