### ISSUE TITLE
Walking bug

### ISSUE THREAD

**Issue by rexrapter1234** [ldtteam/minecolonies#669]
### Minecolonies version

version 1.10.2 or curse 0.6.6

### Expected behavior

Colonus can walk around walls. When a Colonus comes to a wall of any type. they move to a different direction from the Wall or MineCart and then just carry on walking.

- XXX

### Actual behaviour

Colonus can not walk around walls. They just run in to them and just jump up and down or just stand there, waiting for the wall to be broken by the player.

- YYY

### Steps to reproduce the problem

To reproduce wall bug you will need to place down a town hall, Builder's hut and any other type of building from the mod. I am using a level 4 Bullder's hut. Build a path way from the builder's hut to the other building. When you build the path way remember to make the path have right and left paths, so the the path is not in a straight line from the Builder's hut to the building or this bug wont work. Also place a wall around the builder's hut and have this wall joined on to the path walls. The path walls should have two walls on each side of the path. Then just ask the builder to build the building and just watch as he runs into the nearest wall in the path.

1. XYZ
2. ZYX
3. ...
4. Profit

http://i243.photobucket.com/albums/ff156/rexrapter1234/wall-bug_zpsaiwdwonb.png
__________________________________________________

The walking bug also applies to Minecarts on rails too.

**Comment by marvin-bitterlich** [comment]
closing, mc locomotion
