### ISSUE TITLE
Error starting server NBT DATA

### ISSUE THREAD

**Issue by nevth** [ldtteam/minecolonies#6694]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.13.680-ALPHA
- Structurize Version: 0.13.148-ALPHA

## Problem description

After restart the server says "Error laoding NBT DATA" in the logs, if i download the world file and reinstall the server it works again
[crash-2021-03-08_18.54.42-server.txt](https://github.com/ldtteam/minecolonies/files/6103325/crash-2021-03-08_18.54.42-server.txt)

### Notes or related things

Even trying the most recent version did not change it

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Can you try the newest version? Are you on linux? Can you show us your world/minecolonies folder content?

**Comment by nevth** [comment]
tried new version (minecolonies-0.13.686-ALPHA) same problem.

The server is running on linux.


![Page 2](https://user-images.githubusercontent.com/80281524/110365374-3f6ae180-8045-11eb-9d2f-9877be5b16ea.PNG)
![Page 1](https://user-images.githubusercontent.com/80281524/110365383-4265d200-8045-11eb-8cc1-6347526ae2e4.PNG)

**Comment by nevth** [comment]
here is the debug file too
[Uploading debug.log…]()

**Comment by nevth** [comment]
.
[debug.log](https://github.com/ldtteam/minecolonies/files/6103538/debug.log)

**Comment by nevth** [comment]
So as I have updated to 0.13.690-ALPHA. It still shows the same error code? Should I delete the minecolonies folder? Or how can I fix my server. 

Thanks for your understanding and I appreciate your help.

**Comment by Raycoms** [comment]
Delete the .deleted file there

**Comment by nevth** [comment]
Still get it:
[debug.log](https://github.com/ldtteam/minecolonies/files/6109066/debug.log)

**Comment by nevth** [comment]
do you have another suggestion? :)

**Comment by someaddons** [comment]
is that world from an older minecraft version?

**Comment by nevth** [comment]
no it was made one week ago on 1.16.5

**Comment by someaddons** [comment]
could try deleting the colonies.dat as that one got errors on loading

**Comment by nevth** [comment]
that will delete the whole colonie am I right, is there a way to get it back after deleting?

**Comment by someaddons** [comment]
no that deletes the colony list, it should be able to still load the colonyX dat. Also you should have some zip backups where its in anyways

**Comment by nevth** [comment]
ok, thanks I will try

is there a link to donate ? :)

**Comment by Raycoms** [comment]
https://www.patreon.com/Minecolonies
