### ISSUE TITLE
Can't unlock fletcher

### ISSUE THREAD

**Issue by hfcotino** [ldtteam/minecolonies#6697]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 1.3
- Structurize Version: 0.13.139
- Related Mods and their Versions:

## Expected behavior
I would expect to be able to unlock Fletcher with Sawmill at Level 3 and 16 String in inventory

## Actual behavior
I can't unlock Fletcher even though I have Sawmill Level 3 and 16 String in inventory

## Steps to reproduce the issue
Build Sawmill to level 3 and try to unlock Fletcher at University

1. Build Sawmill to level 3
2. Try to unlock Fletcher at University with 16 String in inventory
3. Fletcher doesn't unlock

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
What level is your University? It needs to be at least level 2.

**Comment by ravenbuilder934** [comment]
Also that's not a minecolonies version

**Comment by hfcotino** [comment]
Ah that explains it. University is at level 1. Too bad the wiki doesn't
mention that. Thanks for the quick response!

**Comment by hfcotino** [comment]
Aw yeah sorry, its the modpack version

**Comment by ravenbuilder934** [comment]
It actually does mention it: (research system page)
![image](https://user-images.githubusercontent.com/63612548/110379204-23067f00-801c-11eb-9cbc-6e673d036abc.png)

**Comment by hfcotino** [comment]
Ahh i must've missed that, thanks for letting me know.
What I also couldn't find: How to produce String?

**Comment by ravenbuilder934** [comment]
Guards killing spiders mainly

**Comment by hfcotino** [comment]
Hey there, I'm stuck with sifters hut, hope u can help. When I open the
huts interface I'm supposed to be able to choose a block like dirt or sand.
But there's nothing to choose from. Do you know how I might fix this?
Thanks and regards..

**Comment by ravenbuilder934** [comment]
our Discord is for support: https://discord.minecolonies.com

**Comment by hfcotino** [comment]
Thanks 👍
