### ISSUE TITLE
client closes during raid

### ISSUE THREAD

**Issue by MrChickenWingz** [ldtteam/minecolonies#6698]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: minecolonies-minecolonies-0.13.645-RELEASE-universal
- Structurize Version: structurize-0.13.109-ALPHA-universal

## Problem description

Client starts closing on its own.
I ended up waiting about 10 minutes and upon logging in it says 
> Victory you have successfully defended against the intruders!

so I assume the raid caused this issue

### Notes or related things

Client Logs:
https://paste.ee/p/3Toaf

Server Logs:
https://paste.ee/p/Mxdo7

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by someaddons** [comment]
its some UI mod crashing: ` net.tslat.aoa3.client.gui.hud.BossBarRenderer.renderBossBar(BossBarRenderer.java:36)`

**Comment by Tslat** [comment]
Yeah this is on me - I didn't expect any other mod to be using this specific setup, but uh.. here we are lol

It'll be fixed in the next aoa version

**Comment by someaddons** [comment]
nice
