### ISSUE TITLE
D-men stop working with first warehouse

### ISSUE THREAD

**Issue by lebanni** [ldtteam/minecolonies#6704]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.13.690-ALPHA-universal.jar
- Structurize Version:structurize-0.13.148-ALPHA-universal.jar
- Related Mods and their Versions:

## Expected behavior

Delivery men work with all warehouses.

## Actual behavior

 I build a second warehouse (I enabled it in the config file). I have 2 delivery men. They both stopped working with the first warehouse. There is no tasks in their respectives buildings. They just stand at the second warehouse block and sometimes check the nearby guard tower.

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- https://gist.github.com/lebanni/15aff92f3602b55a91421443011896d4
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Couriers work at the closest warehouse and at that only. It's a restriction that is intentional in the current system.
Changing that would be a feature request  (in the feature request repo) rather than a bug report.
