### ISSUE TITLE
Builder stops working for no reason

### ISSUE THREAD

**Issue by masonbesmer** [ldtteam/minecolonies#6705]
### Prerequisites 

- [kinda] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.13.658-ALPHA

### Logs

- latest.log: https://gist.github.com/shotbyapony/a61deba60c463d195d62375cceb22594

## Steps to reproduce the issue / details

Just reporting the AI issue.

### Notes
[video of issue](https://www.youtube.com/watch?v=FGa6C9zdQ1I)

Builder wanders in circles for entire day, sleeps, then continues the next day
Lasts over several restarts, only a new issue since last night.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
fixed in latest
