### ISSUE TITLE
Warehouse Deleting Items

### ISSUE THREAD

**Issue by ghost** [ldtteam/minecolonies#6707]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.13.686-ALPHA-universal.jar
- Structurize Version: structurize-0.13.148-ALPHA-universal.jar
- Related Mods and their Versions: None

## Expected behavior
Items show in racks in the warehouse

## Actual behavior
When I put some items into the Birch Warehouse 3 to be exact and sort it, sometimes my items go into a rack that doesn't exist and I can't acquire them anymore.

## Steps to reproduce the issue
1. Build Birch Warehouse and get to level 3
2. Put items in there, enough for it to maybe have extra racks used
3. Press sort and try and search for certain items

Logs:
I don't know to upload logs without it showing anything private.

### Notes
This has only happened to me when using birch warehouse so far

**Comment by ravenbuilder934** [comment]
Did you check the hut block inventory?

**Comment by ghost** [comment]
> Did you check the hut block inventory?

I checked the inventory and it was there, I searched the racks and there was nothing and when I clicked the ? to search for it, it wouldn't click and kept that screen open.

**Comment by Raycoms** [comment]
Sure it's not somewhere in a connected courier hut or so closeby?

**Comment by ghost** [comment]
I checked everywhere, builder hut in case as well and nothing

**Comment by Raycoms** [comment]
Are there any errors in your log when sorting the warehouse?

**Comment by ghost** [comment]
I just sorted it a few times in a row to test it out and there was no error message

**Comment by Raycoms** [comment]
If you create a new world, just with minecolonies and dependencies, can you reproduce this easily?

**Comment by ghost** [comment]
I went into a new world and made the stuff and I couldn't do it to easily, I can try and record a video real fast to show you what is fully going on if that will help at all.

**Comment by Raycoms** [comment]
I had heard of this already but I never could reproduce it actually. Is that on a heavily modded world?

**Comment by ghost** [comment]
Besides the 2 for minecolonies, its Voxelmap, Citidel and Mana and Artifice so not that heavily modded

**Comment by Raycoms** [comment]
Oh, can you send me the world then?

**Comment by ghost** [comment]
I play on my friends server and he's got work then he will probs go to sleep afterwards so it may be like 16 hours or so before I can get the world, Ima just hope he doesn't add anymore mods before he sends it because he was already planning on adding a bit more quality of life stuff.

**Comment by Raycoms** [comment]
QoL mods don't matter, as long as there is not a lot of worldgen stuff it's fine. I just need the world not the mods folder

**Comment by ghost** [comment]
Well it will still be a bit of time till that, all I know would be for worldgen coming is better caves and repurposed structures.

**Comment by ghost** [comment]
I got my friends info to get the world download and I did a bit of investigating and figured out a solution to this
This is how I at least got it to work
1: Fire all delivery people for the assigned warehouse and made sure their inventories were empty
2: Restart the server
3: Rehire all the people
4: Resorted everything
Afterwards my missing items were shown again.

**Comment by Raycoms** [comment]
That is super weird, firing and rehiring should not have any effect at all on this

**Comment by Raycoms** [comment]
Might it've been only the restart?

**Comment by ghost** [comment]
I restarted before and nothing happened that's why I fired them and it worked so I really don't know at this point.

**Comment by Raycoms** [comment]
Still waiting for the broken world =D

**Comment by ravenbuilder934** [comment]
O_o they deleted their account

**Comment by Raycoms** [comment]
Closed then.
