### ISSUE TITLE
Visual Bug - switching recipe order in recipe list causes  visual error

### ISSUE THREAD

**Issue by xXAnoHitoXx** [ldtteam/minecolonies#6709]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.13.690-ALPHA
- Structurize Version: 0.13.148-ALPHA
- Related Mods and their Versions: none

## Expected behavior

moving recipe up or down the recipe list should move the entire recipe without changing the content
of the recipe

## Actual behavior

changing the order of the recipes sometimes causes a bug when two recipe swap places, 
the ingredients and outputs of the two gets mixed up. This happen more frequently the more
recipes are in the list, and especially more for certain recipe than others. 

In my case the spruce fences takes over the other recipe more than any other ones

![2021-03-09_18 42 49](https://user-images.githubusercontent.com/23743678/110557777-a3f67100-8117-11eb-8a1c-02cc93c92112.png)

## Steps to reproduce the issue

1. fill up a saw mill with recipes of 3+ types of wood, fences, stairs, fence gates etc
2. optional - execute the glitch to break the max number of recipe allowed
3. start moving different recipes up and down to reorder them
4. occasionally this bug happens

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Seba244c** [comment]
![image](https://user-images.githubusercontent.com/23051740/110682917-c81b8600-81db-11eb-827d-47c75dcf1eb1.png)
I can't seem to find a pattern with this error. It seems to be 100% random.

**Comment by Sandriell** [comment]
The bug can also happen if you simply scroll too fast through the list.
