### ISSUE TITLE
Build Preview cuts off amounts over two digits

### ISSUE THREAD

**Issue by truenachtara** [ldtteam/minecolonies#6710]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.13.693-ALPHA
- Structurize Version: 0.13.148-ALPHA
- Related Mods and their Versions:

## Expected behavior

I expect the build preview page to show an accurate count of all the items required to build a structure.

## Actual behavior

The build preview page is mostly accurate, but any numbers over two digits have additional digits cut off.

See stairs count: 
![image](https://user-images.githubusercontent.com/16340367/110562811-d1d7b780-810f-11eb-989f-dac1e3e56d8e.png)
![image](https://user-images.githubusercontent.com/16340367/110562962-1f542480-8110-11eb-81a6-90014c4ac02d.png)
![image](https://user-images.githubusercontent.com/16340367/110563045-43b00100-8110-11eb-9e0f-faf632a106e8.png)

## Steps to reproduce the issue

It's easiest to see this with the Level 1 Asian builder's hut, as demonstrated in the screenshots. This build requires 143 stairs, not 14.

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by truenachtara** [comment]
Less important: Long item names are also cut off after a few words. Check the timbers:
![image](https://user-images.githubusercontent.com/16340367/110726319-cd2e0480-81de-11eb-8c80-576cd3298fb7.png)
![image](https://user-images.githubusercontent.com/16340367/110726346-d7e89980-81de-11eb-868f-27134d851bdb.png)
![image](https://user-images.githubusercontent.com/16340367/110726358-dcad4d80-81de-11eb-91c0-173b39a09023.png)

**Comment by ravenbuilder934** [comment]
Yea, this isn't too hard of a fix. I've just been waiting until I have time to work on it, which is hopefully now :P
