### ISSUE TITLE
Forester not Working

### ISSUE THREAD

**Issue by Rowtag** [ldtteam/minecolonies#6711]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: Forge 1.16.5-36.0.45
- MineColonies Version: minecolonies-0.13.693-ALPHA-universal
- Structurize Version :structurize-0.13.148-ALPHA-universal
- Related Mods and their Versions: a lot (Using Direwolf 1.16 V 1.7)

## Expected behavior

Forester should start his work and cut the Trees in the defined area

## Actual behavior

The forester doesn't do anything, no requests, no actions taken.

## Steps to reproduce the issue

1. Build a forester
2. use the Build tool, mark an area and wait
3. Replant on, Restriction On. He's doing nothing.

### Logs

- latest.log: https://gist.github.com/Rowtag/98d206486a56c710249336969704d636
- crashlog: not available

### Notes
Checked also the last Beta where it doesn't work.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Nightenom** [comment]
Already being fixed #6678

**Comment by Raycoms** [comment]
Duplicate issue also

**Comment by Rowtag** [comment]
> Already being fixed #6678

Sorry didn't notice that one, my bad! Thanks

**Comment by SonicDRJ-1559** [comment]
I am having this same issue in a new release of Minecolonies.

Version: minecolonies-1.19.2-1.0.1351-RELEASE.jar

Issue is replicated the same as mentioned in the original post.

Is there a way to circumvent this? Or would I have to rebuild the Forester?

**Comment by MotionlessTrain** [comment]
Please open new issues instead of reacting on closed issues of more than a year old.

Also make sure to use the latest alpha version (which at the time of writing is roughly 60 versions newer than the latest release version)
