### ISSUE TITLE
Logfile warnings at startup still exist

### ISSUE THREAD

**Issue by smmmadden** [ldtteam/minecolonies#6712]
### Prerequisites 
Been hoping for a while now that all the warnings during node startup would be addressed, but they are still present.  It isn't clear if anything can be done since it warns about the **ID it expected by received (possible forge issue?)**.

- [ x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 36.0.45
- MineColonies Version: 0.13.693-ALPHA
- Structurize Version: 0.13.148-ALPHA
- Related Mods and their Versions:

## Expected behavior

Server startup should be free of warnings/exceptions as a rule so it would be great to eliminate the 1,000+ lines that get written.  I expect INFO lines, but that would be all.
## Actual behavior

Logs are very noisy at startup pointing to validation issues for all the MineColonies blocks/items.  No noticable in-game difference, just a noisy logfile.

## Steps to reproduce the issue

1.  start clean server
2.  watch the console/latest.log file
3.  see all the warnings

### Logs
https://pastebin.com/794qp6WX  Latest.log file

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Not directly related to us, this just means that block ids changed, due to some update or similar reasons so forge spams this log. 
There is nothing we can do here.
