### ISSUE TITLE
Nether Colonies do not have unique Colony IDs

### ISSUE THREAD

**Issue by smmmadden** [ldtteam/minecolonies#6717]
### Prerequisites 
Go into creative mode
Get to the Nether
Fly to top of Nether Ceiling
Break bedrock to get on top
Build out colony and name it

- [ x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 36.0.45
- MineColonies Version: 0.13.693-ALPHA
- Structurize Version: 0.13.148-ALPHA
- Related Mods and their Versions:

## Expected behavior

All new colonies should have unique ID regardless of their location, especially if they are not in the Overworld
## Actual behavior

We built out our colony and completed all the builds we wanted.  We are now moving over to The_End world and going to build a colony there.  In order to abandon the current colony, I have to use the ID.  However, there are TWO Colony 1's.

![image](https://user-images.githubusercontent.com/10309346/110728312-d02ef200-81ea-11eb-8a71-35664d75afb4.png)
Also noticed that leaving the colony shows "Leaving Farspell" instead of "Leaving Erie Village".
## Steps to reproduce the issue

Here is a view of the completed colony that we need to abandon before going to the next world.
![image](https://user-images.githubusercontent.com/10309346/110728405-053b4480-81eb-11eb-84bb-db8c958b92a1.png)

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

What also would be very helpful in the list of colonies is who the Owner is and if the colony is abandoned or not.
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Yes this is so far intended behaviour. You execute the command in the dimension you're in, so it deletes the colond id x in your dimension.
