### ISSUE TITLE
Wrong Traits

### ISSUE THREAD

**Issue by psxlover** [ldtteam/minecolonies#672]
### Minecolonies version

Curse 0.6.6

### Expected behavior

I expected the traits to be the same when viewing the worker menu (right click on worker) and when trying to hire one.

### Actual behaviour

The intelligence value I see when trying to hire a delivery man is different than the values on the worker. Not sure if this happens with any other job/trait.

![image](https://cloud.githubusercontent.com/assets/1429524/23579844/914b85a6-00fe-11e7-8054-deb27b5146a6.png)

![image](https://cloud.githubusercontent.com/assets/1429524/23579847/a0f48aa2-00fe-11e7-97a4-ec675f4de252.png)

**Comment by pmardle** [comment]
Good Spot

**Comment by psxlover** [comment]
https://github.com/Minecolonies/minecolonies/blob/39fefca350e69fb7ce3b1c19231a85ced289ed24/src/main/java/com/minecolonies/coremod/client/gui/WindowHireWorker.java#L178

should be citizen.getIntelligence() instead of citizen.getStrength()

Also for the sake of consistency the order of the traits should be the same on the workers and on the hire gui.

**Comment by Raycoms** [comment]
fixed in next update.

2017-03-06 11:41 GMT-03:00 Alex Pap <notifications@github.com>:
