### ISSUE TITLE
State sorting in gui is wrong

### ISSUE THREAD

**Issue by Nightenom** [ldtteam/minecolonies#6720]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: latest
- Structurize Version: irrelevant
- Related Mods and their Versions:

## Expected behavior
Result of <https://github.com/ldtteam/minecolonies/pull/6692> is wrong, they are sorted at the end
![image](https://user-images.githubusercontent.com/17338378/110783547-e4b1cf80-8268-11eb-916b-96618c3a605e.png)

## Actual behavior
On should be at the top

## Steps to reproduce the issue

1. lumberjack wood type list

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Nightenom** [comment]
@RyTechro

**Comment by RyTechro** [comment]
This is because this list is inverted, wil write a fix today

**Comment by RyTechro** [comment]
After writing the fix and reviewing the result I would like to argue that this is intentional behavior. For instance on the third page of the cook, all food items are enabled and I would like to quickly view the few that I've disabled.

I agree that for the lumberjack this isn't the desired behavior. But that would require a new variation where initially all items are checked but it does sort like an non-inverted list

**Comment by Nightenom** [comment]
We have exclusion and allowed filter afaik, so you need to distinguish between them, probably @Raycoms or someone else can say more

**Comment by Raycoms** [comment]
There is an !inverted var on the client side that could be used for this.

**Comment by RyTechro** [comment]
There is, and in the proposed fix I do use that.

```
if(!o1Allowed && o2Allowed){
    if (isInverted)
        return -1;
    return  1;
}else if(o1Allowed && !o2Allowed){
    if (isInverted)
        return 1;
    return -1;
}else{
    return 0;
}
```

But in the following three screenshots you can see the cases I'm talking about. In my opinion the lumberjack and cook fuel are correct in the screenshots but the cook food is wrong.

Cook fuel:
![Schermafbeelding 2021-03-11 om 15 13 47](https://user-images.githubusercontent.com/8685947/110800985-0e74f180-827d-11eb-8115-836670cab74f.png)

Cook food:
![Schermafbeelding 2021-03-11 om 15 19 13](https://user-images.githubusercontent.com/8685947/110801090-29dffc80-827d-11eb-9d70-dbee0ba9a9fa.png)

Lumberjack:
![Schermafbeelding 2021-03-11 om 15 14 27](https://user-images.githubusercontent.com/8685947/110801135-32383780-827d-11eb-81c3-dfa5127ef210.png)

**Comment by Raycoms** [comment]
I think this is fine, a perfect solution doesn't exist yet. Try to do a isInverted ? 1 : -1 btw, inline looks nicer in this case

**Comment by RyTechro** [comment]
Alright, will open a PR as is.
