### ISSUE TITLE
Courier started complaining of AI issues after I deconstructed warehouse

### ISSUE THREAD

**Issue by Lielac** [ldtteam/minecolonies#6725]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: Minecraft 1.15.2, forge-31.2.45
- MineColonies Version: minecolonies-0.13.533-ALPHA-universal
- Modpack: Life in the Village 2, on the Curseforge launcher

### Logs

- latest.log: https://gist.github.com/Lielac/aba31137b57e325ddf5b91cd2c44284b

## Steps to reproduce the issue / details

I realized I'd built my warehouse backwards, so I deconstructed it and rebuilt it facing the right way. My courier started complaining of AI issues when I placed the warehouse block back down, or maybe right after I picked it up after the deconstruction was done. They seem to be working just fine anyway, though.

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
533 is over a hundred versions out of date (latest for 1.15 is 645). However, even if it's still broken on 645, 1.15 isn't being updated any more
