### ISSUE TITLE
Colonies 1.16.5 crashing on load

### ISSUE THREAD

**Issue by bkysemperfi** [ldtteam/minecolonies#6728]
### Prerequisites 

- [x] I am running the latest minecolonies-0.14.3-ALPHA-universal.jar version of MineColonies and Structurize structurize-0.13.100-RELEASE-universal.jar for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 1.16.5
- Structurize Version: 1.16.4
- Related Mods and their Versions:

## Expected behavior
Minecraft would load

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Crashlog?

**Comment by ravenbuilder934** [comment]
Also, try updating to 0.13.148 alpha of structurize

**Comment by bkysemperfi** [comment]
Actually that was the fix to update the structurize file.  Had to downgrade my curseforge to 1.16.4 and then it errored asking for the newer structurize file.  When loading in curseforge 1.16.5 it wouldn't give that error to reference.  All fixed thanks!

**Comment by ravenbuilder934** [comment]
Ye, forge did a derp - instead of showing that error screen it crashes. Downgrading forge should also fix it
