### ISSUE TITLE
knights wont stop attacking friends

### ISSUE THREAD

**Issue by Dommskiez** [ldtteam/minecolonies#6730]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- MineColonies Version:
- Structurize Version:
- Related Mods and their Versions:

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
This is not a bug.  You've turned on the "Attack Guards" permission for them.  Turn it off.

And in future, it would be better if you asked on the Discord for help to confirm whether something is actually a bug or not first.  Especially if you don't even fill in the template properly.

**Comment by Dommskiez** [comment]
oh shoot sorry I'm new to this sort of thing is there anyway to delete the report?
