### ISSUE TITLE
Builder Stuck on Spruce Fence

### ISSUE THREAD

**Issue by mrcavallo1973** [ldtteam/minecolonies#6731]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.13.667-ALPHA-universal

### Logs

- latest.log: 

## Steps to reproduce the issue / details

i am attempting to build the caledonia buildings - but everytime the builder needs to place fences - so far ive only noticed on spruce - the builder just stands there constantly placing the fence even tho it is there. when i hit the builder they walk around then come back to same spot and keeps placing the fence. if i break the post it immediately appears. 

i have tried to fire, hire a new builder, change the location of building - but everytime it comes tot he fence the builder just will no longer progress.

i am using a fairly lightweight modpack - slightly vanilla.

Just reporting the AI issue. 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Update to the latest
