### ISSUE TITLE
Which build should be used?

### ISSUE THREAD

**Issue by smmmadden** [ldtteam/minecolonies#6733]
### Prerequisites 
I just checked the site and see two builds done the same day.  There is nothing in the Description (About Mod) that tells users which one should be used and both have completely different change log details which will add to confusion.
![image](https://user-images.githubusercontent.com/10309346/110972525-1343af00-832a-11eb-8d6b-05edea23a1be.png)

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- MineColonies Version:
- Structurize Version:

### Notes or related things

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
One of them (0.14.3) has a higher number, so logically that one is more recent and what should be used.

**Comment by Raycoms** [comment]
Both builds are fine. 0.14.3 has a bunch of newer stuff though.
