### ISSUE TITLE
Repeating FATAL Errors in logs

### ISSUE THREAD

**Issue by smmmadden** [ldtteam/minecolonies#6735]
### Prerequisites 

- [ x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [ x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 36.0.55
- MineColonies Version: 0.14.9-ALPHA

### Logs

https://pastebin.com/sciVF5mb

- latest.log: 

## Steps to reproduce the issue / details
Just logging in causes the errors and interacting with builders.

Just reporting the AI issue. 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Please do a request-system reset. Problem the same as https://github.com/ldtteam/minecolonies/issues/5672

**Comment by smmmadden** [comment]
Sorry @Raycoms - but the system-resest-all does not address this issue.  I just got one for university research and then for the farmer.  Suggestions?  Does the server have to be restarted after doing the reset?  How is this different than restarting the server after upgrading to this build?  Just curious.  Thanks! -Steve
[latest.log](https://pastebin.com/3JYUabpP)

**Comment by Raycoms** [comment]
At the university? There are no requests there, this is weird.

**Comment by smmmadden** [comment]
There was one request to do Civilian Research and it looks like it finished about the same time as the error.  I'm still testing the build out and will advise if there are other huts/civilians throwing the fatal errors.  If it makes any difference, this colony we are building is in The_End.

**Comment by smmmadden** [comment]
Three out of three times, fulfilling Builders Request for supplies resulted in FATAL exceptions.  Not hut specific as it happened for University 4, Mine 1 and then Citizen 3.  So its more likely to be in the same code.

**Comment by smmmadden** [comment]
@Raycoms - don't see a re-open option for the bug.  It is still an issue.

**Comment by Raycoms** [comment]
it's the same issue as the one I pointed out. it's a request system issue which happens when there are orphaned requests at a building and a fulfillment or similar happens. It's doesn't depend on a specific AI. We're still tracking this down.
