### ISSUE TITLE
Required Structurize version is unavailable.

### ISSUE THREAD

**Issue by quixote966** [ldtteam/minecolonies#6738]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: 0.13.437-RELEASE
- Structurize Version: 0.13.100-RELEASE
- Related Mods and their Versions:

## Expected behavior

Minecolonies mod loads successfully.

## Actual behavior

Error loading mod

Failure message: Mod minecolonies requires structurize 0.13.96-ALPHA
		Currently, structurize is 0.13.100-RELEASE
	Mod Version: 0.13.437-RELEASE

## Steps to reproduce the issue

1. Install the specific mod versions.
2. Launch Minecraft.

1. 
2. 
3. 

### Logs

https://gist.github.com/quixote966/d8f607f91706ecfdbd619b7334d9c3e0  <-- both files, sorry -->

### Notes

Attempted to find specified required version of Structurize on curseforge, but was unable to find it.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Go to the Files tab, then click View All. Also as an FYI, we recommend using the alphas or the betas instead of the releases (they aren't any less stable)

**Comment by uecasm** [comment]
Don't use releases.

Get the latest ALPHA from here: https://www.curseforge.com/minecraft/mc-mods/minecolonies/files/all
When you click on the link to the actual file (not just the download button) it will specify a specific version of Structurize.  Go here and get exactly that version, not any other: https://www.curseforge.com/minecraft/mc-mods/structurize/files/all
