### ISSUE TITLE
Construction Tape wrong with custom hut

### ISSUE THREAD

**Issue by xavierh** [ldtteam/minecolonies#674]
### Minecolonies version

version git version/1.11 (modified)

### Expected behavior

- Construction tape when putting down the hut's chest should be the same as when starting building it

### Actual behaviour

- A second tape is set up,the first one is not remove

I suspect when putting the chest down using the Build Tool, the default citizen hut size is use to put the first construction tape

![2017-03-05_16 25 56](https://cloud.githubusercontent.com/assets/2778556/23589265/a6a2d030-01c1-11e7-9354-3b4d043d03a2.png)
![2017-03-05_16 26 08](https://cloud.githubusercontent.com/assets/2778556/23589264/a6a21488-01c1-11e7-80fa-731c10c870f8.png)
![2017-03-05_16 29 29](https://cloud.githubusercontent.com/assets/2778556/23589266/a6a30a14-01c1-11e7-95b5-a038b9344827.png)
![2017-03-05_16 29 47](https://cloud.githubusercontent.com/assets/2778556/23589267/a6a5189a-01c1-11e7-978e-3598d478f672.png)

Would be nice is someone could try on a different version, my branch have been heavily modified in this area

**Comment by Raycoms** [comment]
Yeah could you test that in the port 1.11 branch?
I did some heavy fixes with that.

2017-03-05 13:36 GMT-03:00 xavierh <notifications@github.com>:

**Comment by xavierh** [comment]
Will do it sometime next week, leave it to me

**Comment by xavierh** [comment]
I did not actually test with version/1.11 but I doubt it would work either.

The Construction Tape is place in Colony.addNewBuilding

Before setting the style in BuildToolPlaceMessage.handleHut. The "wooden" default style is used to place the Tape instead.

**Comment by xavierh** [comment]
Similar problem when building the fisherman's hut

**Comment by Raycoms** [comment]
okay @nojo121 your constructiontape isn't considering the style.

**Comment by xavierh** [comment]
@Raycoms Not sure why it does that for the Fisherman hut as we only have one style. (noticed it yesterday when testing your branch)

**Comment by Raycoms** [comment]
Strange thing...

2017-03-13 10:39 GMT-03:00 xavierh <notifications@github.com>:

**Comment by Raycoms** [comment]
Fixed that already
