### ISSUE TITLE
Interaction with LumberJack triggers AI issue

### ISSUE THREAD

**Issue by PsyCrow1976** [ldtteam/minecolonies#6740]
### Prerequisites
- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context Minecraft version you're playing, please.--> 
- Minecraft Version: 1.16.5 - Forge 36.0.42
- MineColonies Version: minecolonies-0.14.3-ALPHA-universal.jar

### Logs
- latest.log: https://gist.github.com/PsyCrow1976/11a1e2049ba6bfd664384642cb8c6190

## Steps to reproduce the issue / details
Just reporting the AI issue.

**Comment by Raycoms** [comment]
fixed in next update
