### ISSUE TITLE
Builder Required Resources % is incorrect

### ISSUE THREAD

**Issue by smmmadden** [ldtteam/minecolonies#6743]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 36.0.55
- MineColonies Version: 0.14.9-ALPHA
- Structurize Version: 0.13.148-ALPHA
- Related Mods and their Versions:

## Expected behavior

Required Resources in the Builders Hut should reflect an integer value of 1% to 100%.
## Actual behavior

![image](https://user-images.githubusercontent.com/10309346/111099135-3aad9e00-851b-11eb-859a-982a52a5f379.png)
How it determined a negative 1,729% is beyond me but clearly incorrect.

## Steps to reproduce the issue

1.   Start a build (in my case Mechanic)
2.   Check the builders hut page 2
3.  See what % is listed - 1% to 100% should be the range.

### Logs

- latest.log: 
- crashlog: 

### Notes

It isn't on any specific hut being built, I'm not seeing any of them showing an actual percentage completed.
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by gattsuru** [comment]
_Should_ be a fix in https://github.com/ldtteam/minecolonies/pull/6726 , hasn't been merged in yet

**Comment by Raycoms** [comment]
Just merged
