### ISSUE TITLE
Citizens taking any edible foods from the restaurant

### ISSUE THREAD

**Issue by warning-djkajslh** [ldtteam/minecolonies#6746]
### Prerequisites 

- [] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- MineColonies Version: BETA 0.13.660
- Structurize Version:
- Related Mods and their Versions: rats-7.1.1-1.16.5

## Expected behavior
Citizens will take any edible foods from the restaurant block

## Actual behavior
Here's how it went:
I put in cheese from rats into the restaurant block as they are easy to make and I can always feed my citizens with it. But this time, they do not touch the stuff, I tried putting in vanilla cooked fishes, and that works, but not the cheese.

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes
May have something to do with this
https://www.reddit.com/r/Minecolonies/comments/m5dc0p/my_colonists_want_better_food/

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
We've recently changed things, how is the saturation value of cheese?

**Comment by warning-djkajslh** [comment]
https://rats-mod.fandom.com/wiki/Cheese_(Item)

**Comment by Raycoms** [comment]
Yep, it's "cheap" food, so citizens on highe rlevel reject it and start wanting better food like baked potatoes or bread
