### ISSUE TITLE
Differnt Intelligene display in Citiezens HUD & Hire HUD

### ISSUE THREAD

**Issue by Liguma** [ldtteam/minecolonies#675]
### Minecolonies version

Minecolonies Testserver 

The Citiezens HUD and the Hire HUD have different Inteligence

![2017-03-07_05 11 00](https://cloud.githubusercontent.com/assets/24432099/23641688/1df2834e-02f6-11e7-9f7a-ae44e0a8ab8b.png)
![2017-03-07_05 12 50](https://cloud.githubusercontent.com/assets/24432099/23641689/1e19f1d6-02f6-11e7-8c87-59ca8ff150ad.png)

**Comment by Raycoms** [comment]
That will be fixed with the next version.
2017-03-07 1:24 GMT-03:00 Gunvaldfar <notifications@github.com>:
