### ISSUE TITLE
my villagers don't eat or cook anything

### ISSUE THREAD

**Issue by nightfoxstarfox** [ldtteam/minecolonies#6751]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.16.4
- MineColonies Version:minecolonies-0.14.21-ALPHA-universal
- Structurize Version:structurize-0.13.148-ALPHA-universal
- Related Mods and their Versions:

probrem:
Try to give as much detail as possible here to help us properly understand the issue. -->
1 the cook always asks for food stocks infinitely and does nothing more than that and all my villagers are starving because the conziheiro doesn’t cook the food he just keeps asking me to add more food, he also said he doesn’t have a stock of food! I've tried to put food straight from his inventory to see if he does anything he just stands there, waiting for 64 more meals

2 all the foods I chose on the menu are 64, I wanted to put a certain amount of food,

## Steps to reproduce the issue

#possible explanation how it happened#

1map made in minecraft 1.12.2
2updated to 1.16.4
3there I managed to make the restaurant at 1.16.4

take my save, to investigate
???

mod list
BiomesOPlenty-1.16.4-13.0.0.432-universal
FastLeafDecay-v25
minecolonies-0.14.21-ALPHA-universal
OptiFine_1.16.4_HD_U_G7
structurize-0.13.148-ALPHA-universal

![rsrea](https://user-images.githubusercontent.com/80798837/111401264-b89eb000-86a7-11eb-997c-63800496319b.png)

**Comment by Raycoms** [comment]
What kind of food do they have in their hut?

**Comment by nightfoxstarfox** [comment]
> What kind of food do they have in their hut?

so far only fish, but I got into the creative after noticing that my villagers weren’t eating or cooking so I tried other foods and it didn’t work very well.

 prints
![FEWAEFWAWEF](https://user-images.githubusercontent.com/80798837/111461932-9420f300-86fc-11eb-947d-0b59b7387058.png)
![weaew](https://user-images.githubusercontent.com/80798837/111461684-473d1c80-86fc-11eb-93fd-d9b789c8ab0a.png)

**Comment by Raycoms** [comment]
they do need cooked fish

**Comment by nightfoxstarfox** [comment]
> they do need cooked fish

they don't cook?
I tried other foods, but only the watermelons worked!

**Comment by Raycoms** [comment]
Is everything on the food page turned on?

**Comment by nightfoxstarfox** [comment]
i think i discovered the problem

the restaurant employees don't cook and keep asking for stock infinitely, but afterwards he fed him, he went back to normal and started to work, is that a bug? if the cook is hungry, will i have to manually feed them? he can't cook hungry for later, to eat later?

![FEWAEFWAWEF](https://user-images.githubusercontent.com/80798837/111464292-55d90300-86ff-11eb-81d0-9c66aceba911.png)

**Comment by Raycoms** [comment]
Ohhh, if the cook is hungry and there is no food in the hut. You have to provide it, yes.

**Comment by nightfoxstarfox** [comment]
> Ohhh, if the cook is hungry and there is no food in the hut. You have to provide it, yes.

but there was food in the hut!

**Comment by Raycoms** [comment]
No, fish is not food, it has to be cooked.

**Comment by nightfoxstarfox** [comment]
so, after I manually fed them out of nowhere he started cooking the raw fish that was stored in the restaurant

**Comment by Raycoms** [comment]
Yep, after fed the cook works

**Comment by nightfoxstarfox** [comment]
so if he is hungry does everyone die of hunger?

**Comment by Raycoms** [comment]
Yes, but it happens very rarely, only when the building runs out of food, the cook goes hungry and then raw food gets delivered. That's why you have to check here and there by the restaurant.
