### ISSUE TITLE
Structurize mod isn't working the the minecolonies mod.

### ISSUE THREAD

**Issue by ghost** [ldtteam/minecolonies#6752]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.13.437
- Structurize Version: 0.13.156-ALPHA

## Problem description

![image](https://user-images.githubusercontent.com/80817338/111440993-ed4a5000-8717-11eb-8739-140f42818a2d.png)

### Notes or related things

I'm not sure what to do because I've searched up everywhere how to fix it but I haven't seen anyone who has encountered into this problem.
---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Titanium237458** [comment]
You downloaded the structurize api file, not the structurize mod file. [This](https://www.curseforge.com/minecraft/mc-mods/structurize/files/3226770) is the one you want, and make sure to download structurize-0.13.148-ALPHA-universal.jar
