### ISSUE TITLE
Builder won't accept banner for building

### ISSUE THREAD

**Issue by MonKind** [ldtteam/minecolonies#6753]
### Prerequisites 

- [ x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: 0.14.21 ALPHA

### Logs

- latest.log:  https://gist.github.com/MonKind/193151e47adff200fc6f45326fa47cf7

## Steps to reproduce the issue / details

 I wanted to build a university medieval spruce level 1, but my builder won't accept any banner. They are requesting 2 white banner but i can't give them to them on the second page of the builders hut. If i put them in their inventory they just put the banners in the builders hut inventory.

Just reporting the AI issue. 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Medieval university normal, or alt? And are they asking for white banner or for white colony banner?

**Comment by Nightenom** [comment]
`[17Mär2021 11:44:44.217] [pool-3-thread-1/INFO] [STDERR/]: [optifine.OptiFineTransformer:getOptiFineResourcePatched:414]: java.io.IOException: MD5 not matching, name: srg/net/minecraft/util/Direction$Plane.class, saved: cc770f196671e1a20942844855caf434, patched: 4bd03a442d2f47f2ee600f2ce0361c0e`

Try without optifine

**Comment by MonKind** [comment]
> 
> 
> Medieval university normal, or alt? And are they asking for white banner or for white colony banner?

the normal one. They are asking for a colony banner and the request image is a white banner

**Comment by MonKind** [comment]
> 
> 
> `[17Mär2021 11:44:44.217] [pool-3-thread-1/INFO] [STDERR/]: [optifine.OptiFineTransformer:getOptiFineResourcePatched:414]: java.io.IOException: MD5 not matching, name: srg/net/minecraft/util/Direction$Plane.class, saved: cc770f196671e1a20942844855caf434, patched: 4bd03a442d2f47f2ee600f2ce0361c0e`
> 
> Try without optifine

I'm playing on a server with my sister. She isn't using optifine and has the same issue

**Comment by Raycoms** [comment]
Do you have optifine on the server side?

**Comment by MonKind** [comment]
No.
I tried it without optifine, but it is still the same

> 
> 
> Do you have optifine on the server side?

**Comment by MonKind** [comment]
Is there a difference between a normal banner and a colony banner? how do i create a colony banner?

**Comment by Talyda** [comment]
Are they fresh made white banners? Never been placed anywhere?

**Comment by MonKind** [comment]
> 
> 
> Are they fresh made white banners? Never been placed anywhere?

yes, they are

**Comment by Raycoms** [comment]
Do you have any mod installed that adjusts banners? Can you give us the nbt value of your banners? (Turn on the item debug mode)

**Comment by MonKind** [comment]
> 
> 
> Do you have any mod installed that adjusts banners? Can you give us the nbt value of your banners? (Turn on the item debug mode)

I just have the structurize mod and the minecolonies mod on forge.
I know how to turn on debug mode for a new world, but how do i get the nbt value?
And i don't know how to turn on the item debug mo

**Comment by Raycoms** [comment]
f3+h

**Comment by MonKind** [comment]
Thanks!
When i have it in inventory: minecraft:white_banner
Is this the right information?

**Comment by Raycoms** [comment]
hm, so no extra nbt values, weird

**Comment by MonKind** [comment]
do you know if there is a difference between a normal banner and a colony banner?

**Comment by Raycoms** [comment]
![image](https://user-images.githubusercontent.com/6438347/111626298-b9d5f700-87e5-11eb-8212-121a9a2f7a3c.png)

Yes there is, this is the recipe (it's cheaper than normal bannerS)

**Comment by MonKind** [comment]
do you know if there is a difference between a normal banner and a colony banner?
