### ISSUE TITLE
Forester not fulfilling requested stripped logs

### ISSUE THREAD

**Issue by PomPoko-lab** [ldtteam/minecolonies#6754]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.20
- Structurize Version:
- Related Mods and their Versions:

## Expected behavior

Forester strips logs upon requests created.

## Actual behavior

Requests idle until player manually submits requested stripped logs.

## Steps to reproduce the issue

1.  Request stripped logs of any kind.
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

Worked perfectly fine a couple of weeks back. Unable to specify version. Apologies. 
Builder requested for stripped oak logs.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by lebanni** [comment]
I have the same issue but with Oak Wood.

**Comment by Moobien** [comment]
add to this, mayor may not be related but farmers aren't carving pumpkins either

**Comment by lebanni** [comment]
This may be not related either, but my farmer (lvl 3 building) crafts the requested hay bale, but it stays in the rack. I checked d-men and none has the pickup scheduled.

**Comment by Mekle001** [comment]
Is the request for stripped logs showing on the clipboard, and not getting handled by the forester?

**Comment by PomPoko-lab** [comment]
Yes, that's correct. The forester just continues to cut logs like normal without stripping them. I have to manually strip all my logs at the moment.

**Comment by Mekle001** [comment]
have you found and cancelled the request at the source? I had this happen a few minutes ago, I went to the builder, cancelled the request, and it worked as expected when it rerequested.

**Comment by Moobien** [comment]
If a rs reset doesnt fix it then cancelling the request wont help, and i have done several rs resets with no success

**Comment by PomPoko-lab** [comment]
Yep, canceling a request doesn't help. Just another request to the player to strip oak logs. 

![image](https://user-images.githubusercontent.com/80806516/111888200-59db7e00-89a8-11eb-99d3-08baae273a1a.png)

> If a rs reset doesnt fix it then cancelling the request wont help, and i have done several rs resets with no success

Agreed here as well. I've done a couple of request system resets to try to troubleshoot this myself.

**Comment by Mekle001** [comment]
Ok, we've identified the problem. And I understand why it appeared to work for me.
