### ISSUE TITLE
Sifter AI issue fulfilling request - broken

### ISSUE THREAD

**Issue by smmmadden** [ldtteam/minecolonies#6759]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 36.1.0
- MineColonies Version: 0.14.21-ALPHA
- Structurize Version: 0.13.148-ALPHA
- Related Mods and their Versions:

## Expected behavior

expected sifter AI to work - but multiple attempts all fail
## Actual behavior

![image](https://user-images.githubusercontent.com/10309346/111559548-265de100-8767-11eb-9bdc-6c0d848b6e39.png)
![image](https://user-images.githubusercontent.com/10309346/111559563-2eb61c00-8767-11eb-85f1-f4e24402e349.png)
Checking the Sifter inventory shows that he has more than enough sand to work with
![image](https://user-images.githubusercontent.com/10309346/111559819-9c624800-8767-11eb-8879-bd405db856b1.png)

## Steps to reproduce the issue

If it makes any difference, the Sifter Hut is at Level 2 currently.  I'm attempting to go to Level 3 and try again.  Will update issue once done.  Update: leveling up had no effect on the Sifter AI.
1. 
2. 
3. 

### Logs

https://pastebin.com/Vnt5AF2s
- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
As a workaround, give the worker a "mesh"

**Comment by smmmadden** [comment]
That worked @Raycoms - thanks for the quick response! :-)

**Comment by Mekle001** [comment]
You probably want to add the Mesh to the prestock like you have the sand, since the recipes changed. I'll also add something for the sifter to ask for a mesh if there is none.

**Comment by smmmadden** [comment]
should users also think of meshes as leveling up, where Diamond Mesh is the highest and Sifter doesn't need the Iron, Flint or String Mesh?
There isn't anything yet on the Wiki for the Sifter for users to know.  I'm sure that's in the pipeline tbd.

**Comment by ravenbuilder934** [comment]
Ye, leveling up. Will be added to the wiki soon:tm:

**Comment by smmmadden** [comment]
Not sure if this is related but I just opened the Inventory of the Sifter hut and each of the blocks including the meshes I added all got removed (cell by cell) until everything got removed.  Odd behavior and unexpected.
