### ISSUE TITLE
No background for the second tab of the composter

### ISSUE THREAD

**Issue by RyTechro** [ldtteam/minecolonies#6760]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0..14.24
- Structurize Version: 0.13.148
- Related Mods and their Versions:

## Expected behavior

A background on the second screen of the composter

## Actual behavior

The second screen of the composter has no background

![Schermafbeelding 2021-03-18 om 12 11 41](https://user-images.githubusercontent.com/8685947/111618714-0240e500-87e5-11eb-838e-2defa577ca74.png)

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Just fixed
