### ISSUE TITLE
roads/cave 3storybasicalley is defined wrong.

### ISSUE THREAD

**Issue by CXWRTH** [ldtteam/minecolonies#6765]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.12
- Structurize Version: 0.13.148
- Related Mods and their Versions: ATM6 Pi2

## Expected behavior
Road defined matches dimensions of other cave roads.

## Actual behavior
Road dimensions are much too tall, apparently including bedrock and 30+ blocks of air below bedrock.
https://i.imgur.com/frdOfyA.jpg

## Steps to reproduce the issue

Try and build a Decoration roads/cave 3storybasicalley

### Logs

N/A

### Notes
I was making things interesting by making a cave extension that would bump into "ancientdwarf" structures... and discovered this road while going through cave assets.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
#5006
