### ISSUE TITLE
0.14.28 crashes at server boot

### ISSUE THREAD

**Issue by SteadEXE** [ldtteam/minecolonies#6766]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.28
- Structurize Version: 0.13.148

## Problem description

When the server boot up, it crashes without any further informations.
There is the stacktrace: https://pastebin.com/UsV5qddf

### Notes or related things

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
What is your java version?

**Comment by SteadEXE** [comment]
1.8.0_281

**Comment by PomPoko-lab** [comment]
Downgraded to 0.14.27 after confirming this issue. 0.14.27 crashes on boot as well. 0.14.24 starts up fine.

**Comment by Raycoms** [comment]
Is this smp or ssp?

**Comment by PomPoko-lab** [comment]
SMP.

**Comment by Raycoms** [comment]
fix pushed
