### ISSUE TITLE
Builders incapable of finishing some of the buildings

### ISSUE THREAD

**Issue by DingoDong0** [ldtteam/minecolonies#6771]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: 0.13.660-BETA
- Structurize Version: 0.13.139-ALPHA
- Related Mods and their Versions: 

## Expected behavior
 I expected the builders (who were given all their required building supplies/tools to complete the builds and move onto new buildings. 

## Actual behavior
 What currently ends up happening is that the builders get to a certain point in a build and then break. I have tried building the medieval birch town hall and even the normal birch town hall on multiple occasions, but the builders give up before the last few blocks and for some reason want to climb to the roof of the building. I'm unsure as to why this is happening and I've even tried placing the blocks for them when they get stuck. My town hall currently has no other blocks that need to be placed and is currently just constantly under construction. The same issue happened when I was trying to upgrade my birch house to level 2 and the builder had issues trying to place the item frame.

 https://imgur.com/a/hZ5FC9s    https://imgur.com/a/rU1a8Qo

## Steps to reproduce the issue

 As far as I'm aware I just did what I've normally done for past versions of minecolonies. I started by just placing the town hall and building the builders hut and completing the builders hut first. I then started the town hall build and fulfilled the builder's requests from the top down. Then I just watched the builder do his job until he stopped when he had to place the ladders for the town hall or the item frame in the birch house level 2 scenario. The builder would then just walk around in circles and climb to the top of the building if possible. 

1.  Start the town hall build and then build a builders hut next to it
2.  Begin the town hall build and fulfill the builder's requests from the top town
3.  Observe and prepare for the builder to just stop at certain steps of the build

### Logs

- latest.log: 
- crashlog: 

### Notes

Even placing the block for the builder didn't fix the issue so I'm really confused on exactly what to do. Possibly implement a new function that checks if the blocks are already placed and finishes the building.
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Update, you're over 60 versions out of date
