### ISSUE TITLE
MinimumStockModuleView - Server Crashes on Startup

### ISSUE THREAD

**Issue by nekhs** [ldtteam/minecolonies#6773]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.33-ALPHA
- Structurize Version: 0.13.148-ALPHA
- Related Mods and their Versions:

## Expected behavior
Server launches.

## Actual behavior
Server crashes.

This line in particular seems relevant: 

Caused by 0: java.lang.BootstrapMethodError: java.lang.IllegalAccessError: no such constructor: com.minecolonies.coremod.colony.buildings.moduleviews.MinimumStockModuleView.<init>()void/newInvokeSpecial

## Steps to reproduce the issue

Attempt to launch server using latest version of Minecolonies.

### Logs

- latest.log: 
- crashlog: https://gist.github.com/nekhs/4393ba8f17796ad6ecc1b34ecd6e12ba

### Notes
I do see that it gets to about the registering registries bit for BYG and then gives up, but given that the error report says Minecolonies - and Minecolonies is the only thing I changed - it seems likely that Minecolonies is the thing that broke it.

I wasn't going to update so soon but I was really hopeful to get the enchanter issue #6767 fixed for my server. Even if I'm the only one on it with an enchanter at present, haha.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
minecolonies-0.14.28-ALPHA-universal.jar     is what you're using....

**Comment by nekhs** [comment]
Oops. I'd tried multiple versions but anything after .28 was throwing the same crash.
