### ISSUE TITLE
Lumberjack not producing apples

### ISSUE THREAD

**Issue by EliotWL** [ldtteam/minecolonies#6775]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: currently 0.14.28 but problem has persisted for the last few weeks at least (and had it confirmed that this hasn't been fixed in the handful of releases since yesterday when I updated)
- Structurize Version: 0.13.148
- Related Mods and their Versions:

## Expected behavior

The lumberjack occasionally produce apples at the same rate as if a player cuts down a tree of the same type.

## Actual behavior

Lumberjack never produces apples (or very very very few if any as I haven't seen one yet but I could have missed one or two)

## Steps to reproduce the issue
1.Have a lumberjack cutting down oak trees.  
2.Also cut down oak trees yourself.  
3.See how many apples you get compared to the lumberjack

### Logs

- latest.log: 
- crashlog: 

### Notes

where the conversation about the issue on the discord happened https://discord.com/channels/139070364159311872/741531816422539384/822531116782845992

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Actually, the lumberjack just eats them regularly. That's fine. So they need food from the cook less regularly.

**Comment by EliotWL** [comment]
> Actually, the lumberjack just eats them regularly. That's fine. So they need food from the cook less regularly.

That's somewhat frustrating when my cook is set to make golden apples and can never get regular apples it seems >.<  Oh well

**Comment by Raycoms** [comment]
At higher levels of the lumberjack the lumberjack will not eat raw apples anymore.

**Comment by EliotWL** [comment]
> At higher levels of the lumberjack the lumberjack will not eat raw apples anymore.

My lumberjack that's having the issue's hut is level 5, and their house hut is also level 5.  And it doesn't seem to matter how long they've been a lumberjack for either.
