### ISSUE TITLE
Polished Blackstone Pressure Plate recipe

### ISSUE THREAD

**Issue by EliotWL** [ldtteam/minecolonies#6777]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.34
- Structurize Version: .148
- Related Mods and their Versions:

## Expected behavior

The mechanic to be able to learn all pressure plate recipes

## Actual behavior

The Polished Blackstone pressure plate recipe can be learned by the stone mason, and instead of the mechanic

## Steps to reproduce the issue

1.I'm hoping this is self explanatory

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
@ravenbuilder934 can you double check a) chicken menstruation and b) wart blocks for the composter too?

**Comment by ravenbuilder934** [comment]
hehehehehehehe, sure
