### ISSUE TITLE
Mirror issue

### ISSUE THREAD

**Issue by psxlover** [ldtteam/minecolonies#678]
### Minecolonies version

Curse 0.6.7

### Behavior

- Using the mirror button on a hut, and then changing the hut level moves the hut to a different location

### Steps to reproduce the problem

1. Use the "Building Tool" with a "Citizen's Hut"
2. Press the mirror button
3. Change the level of the building

**Comment by Raycoms** [comment]
Will take a look at it

2017-03-07 9:36 GMT-03:00 Alex Pap <notifications@github.com>:
