### ISSUE TITLE
Builders all dieing where they should not be

### ISSUE THREAD

**Issue by smmmadden** [ldtteam/minecolonies#6780]
### Prerequisites 
Hospital Level 3 being upgraded to Level 4
- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 36.1.0
- MineColonies Version: 0.14.21-ALPHA
- Structurize Version: 0.13.148-ALPHA
- Related Mods and their Versions:

## Expected behavior

Three builders died as soon as they began building level 4 of the hospital.  They all died from drowning which shouldn't be possible as there are no openings to the towers with the water in them.
## Actual behavior

Notice the position is inside the water tower with the kelp and exact same location of death (-2041 69 -743)
![image](https://user-images.githubusercontent.com/10309346/111857431-cc485180-8907-11eb-85e2-f95d61a11368.png)
![image](https://user-images.githubusercontent.com/10309346/111857435-d1a59c00-8907-11eb-8db8-26c9c0de8b0c.png)
![image](https://user-images.githubusercontent.com/10309346/111857440-d8341380-8907-11eb-9e35-f1734991c79e.png)

This is where I ended up when trying to TP to the death spot.  I'm .50 blocks difference in both directions - but when I move, I end up in the water even though appearance shows I'm not in the water.
![image](https://user-images.githubusercontent.com/10309346/111857527-850e9080-8908-11eb-9ffa-872782cc4c1c.png)
Oddly enough, the position I'm in, I can step backwards and be on the roof OR if I step forward first, I'm in the water which shouldn't be possible.  The Hospital building type is "Birch".
## Steps to reproduce the issue

1. 
2. 
3. 

### Logs
If you need logs or something else, do let me know.  Thanks!  And the fun continues. :-)
-Steve

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Can you try this with the latest alpha too?

**Comment by smmmadden** [comment]
Haven't seen the issue come back since upgrading to 0.14.37 so we may be good.

**Comment by Raycoms** [comment]
We recently did some adjustments so that might've solved that. Please reopen if it happens again with a higher version.

**Comment by smmmadden** [comment]
Hi @Raycoms - looks like this still isn't fixed.  I lost 5 builders tonight trying to finish the hospital and they all somehow get trapped in the towers with the water in them and drown.  The current level is 3 and trying to get to 4 doesn't happen.
![image](https://user-images.githubusercontent.com/10309346/169676266-e392ce29-0fc1-4411-92f9-6a7ee77ff20b.png)

I'm now running with:
Forge: 40.1.20
MineColonies: 1.0.753-ALPHA
Multi-Piston: 1.2.7-ALPHA
Structurize: 1.0.399-RELEASE
Domum Ornamentum: 1.0.50-ALPHA
