### ISSUE TITLE
Unable to open miner GUI

### ISSUE THREAD

**Issue by MeikelLP** [ldtteam/minecolonies#6783]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.** May be related to #5100

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.34-ALPHA
- Structurize Version: 0.13.148-ALPHA
- Related Mods and their Versions:

## Actual behavior

Crashes every time (reproducable)

## Steps to reproduce the issue

1. 
2. 
3. 
Unknown

### Logs

- latest.log: https://gist.github.com/MeikelLP/fc1850f237f37e64b9d7ae9b64a4e921
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Can't find the exception in this log

**Comment by MeikelLP** [comment]
oh the log got truncated
let me fix that

**Comment by MeikelLP** [comment]
So github was limiting my log to ~4k lines but it had 75k. I included only the last lines

**Comment by vroni92** [comment]
I can't reproduce this. Can you send me a copy of your world?

**Comment by MeikelLP** [comment]
Will send you a link via discord. It's about 1.6GB

**Comment by vroni92** [comment]
That'd be great. You can find me in the MC discord Vroni#3924

**Comment by MeikelLP** [comment]
I tried to setup my world with the latest development code

but I am not getting my error.

I noticed the dev code uses forge 36.0.39 but my modpack is using 36.0.42
I am also unable to reproduce this issue in my world with an older modpack version (including an older mcol version)

**Comment by Raycoms** [comment]
With the dev code + forge 36.0.42, does it happen?

**Comment by MeikelLP** [comment]
I will need help with that. I am not a Java dev so I am too stupid to increase the forge version

**Comment by Raycoms** [comment]
there is a build.properties file, just increment it there

**Comment by MeikelLP** [comment]
Nope doesn't happen on .42

I will now try with the other mods installed

**Comment by MeikelLP** [comment]
So what I found out that it is not related to the forge version.
However, opening the world multiple times with only minecolonies installed (so ~190 mods missing) kinda purged my world.
It is now working with this purged state. However this is not acceptable as basically 90% of my items are gone.

I'll continue to investigate on that. Maybe it's related to my inventory.

Edit:
No its not related to my inventory.

**Comment by MeikelLP** [comment]
I was able to make it reproducable for @vroni92 with a minimal setup

**Comment by MeikelLP** [comment]
So we found out that this is some kind of race condition.

This happens if you are early in your game session and click the miner.
If you wait long enough this won't happen.

**Comment by uecasm** [comment]
It's normal for the colony to take a few seconds to fully load after the world itself is loaded and interactable.  If you're near a citizen you can see them change job outfits and if you right-click a hut during this time you usually get the 'this hut is missing its building" error in chat.  Usually things don't actually crash though.

**Comment by MeikelLP** [comment]
Yeah the guards in mines is a very new feature :)

**Comment by Raycoms** [comment]
I guess it's just in the moment before the colony view is over, but the building view is already over
