### ISSUE TITLE
Build Tool Substitution Block Rendering

### ISSUE THREAD

**Issue by pmardle** [ldtteam/minecolonies#679]
Can we please amend the building rendering system to render Substitution blocks as they will be built in game.. i.e. Solid Substitution Blocks appear as the block they will be when built (dirt, Sand, Grass etc.) and the non solid block as either the existing block in that location, or air etc.

Thanks,

**Comment by Raycoms** [comment]
You can test it here:
https://www.dropbox.com/sh/9cnqcjl0nan57cy/AABxuUuDgBzWlkWJAnkfnGrBa/branch/fix/%23644-%23679?dl=0&preview=minecolonies-universal-1.10.2-0.6.3062.jar

2017-03-07 20:24 GMT-03:00 Marvin Hofmann <notifications@github.com>:
