### ISSUE TITLE
Strong visitors

### ISSUE THREAD

**Issue by warning-djkajslh** [ldtteam/minecolonies#6790]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- MineColonies Version:
- Structurize Version:
- Related Mods and their Versions:

## Expected behavior
When attacked, visitors should flee to somewhere safe.

## Actual behavior
When a mob accidentally hit a visitor, as they aren't be target by mobs, the visitors and their cohort will retaliate back, dealing 10 HP WITH ONE PUNCH!!!!!!? result in a massive war between mobs vs visitors.

## Steps to reproduce the issue
 Get a strong mob that goes after everything(Zoglin, Mutant Beasts....) and have one of them attack a visitor and watch.

### Logs

- latest.log: 
- crashlog: 

### Notes
Can there be a config for whether can visitors be targeted by mobs? Real test to see if your colony is truly safe.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by someaddons** [comment]
intended to be strong
