### ISSUE TITLE
Glassblower Hut cannot be build

### ISSUE THREAD

**Issue by Inomutso** [ldtteam/minecolonies#6799]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: forge-1.16.5-36.1.0
- MineColonies Version: minecolonies-0.14.47-ALPHA-universal
- Structurize Version: structurize-0.13.148-ALPHA-universal
- Related Mods and their Versions:
  mcw-doors-1.0.1fix-mc1.16.4.jar
  furniture-7.0.0-pre19-1.16.3.jar
  worldedit-forge-mc1.16.3-7.2.2-dist.jar
  structurize-0.13.148-ALPHA-universal.jar
  ImmersiveEngineering-1.16.5-4.2.2-132.jar
  pamhc2foodcore-1.16.3-1.0.2.jar
  jei-1.16.4-7.6.1.72.jar

## Expected behavior
Glassblower Hut 

## Actual behavior
 Glassblower Hut can be placed, but building it is not possible

## Steps to reproduce the issue

Hi Team

I have built a new Colonie with MC 1.16.5 now, because of these Problems i had in #6656.
Now I tried to build my last Worker Hut, that is the Glassblower.
The Colonie Management is telling me, that I have to build a University or do a research, to give one of my workers the order to build this hut.
When I look in the University in research, I cannot find anything about the Glassblower there.
I have seen this research in my 1.16.4 Colonie, but right now, nothing is there.
I have build all the other Workers Hut's and everything is leveled up to 5.
The Colonie Wiki is showing an older Description, where the Glassblower research should be found in Technology -> Hot! -> Those Lungs!
But in my University GUI it is not there, so I am not able to build this Hut.
Did I miss anything, or is it Wissis fault ?

Thanks for checking that

Inomutso

1.  Place the Hut with the tool
2.  try to make a build order for this Hut
3.  error message: you have to build a University ...... 

### Logs

- latest.log: 
- crashlog: 

### Notes

@Ray @Someaddons
I could not find any issues on my System, that could be the reason for #6792.
With the update to minecolonies-0.14.47-ALPHA-universal, all these Ticking Problems were gone.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by gattsuru** [comment]
Should still be present.  You do have to scroll down pretty far, but on Technology: 
![image](https://user-images.githubusercontent.com/39036909/112002700-8e5d5000-8af6-11eb-847f-4f6927759208.png)

**Comment by Inomutso** [comment]
yes you were right, it was a Problem with my GUI in the University
"normal" scrolling did not show it, made the GUI a bit smaller and then pushed down the GUI, did show it
thx für helping me with that
