### ISSUE TITLE
Crafting warehouse conflit [$5]

### ISSUE THREAD

**Issue by RedAlex** [ldtteam/minecolonies#680]
### Minecolonies version minecolonies-universal-1.11-0.6.2919

Minecraft version 1.11.2

Forge Version 13.20.0.2252

### Expected behavior

- Crafting warehouse cube with Wood and chest in middle

### Actual behaviour

- With the recipe to create Warehouse are the same of Cabinet (Mod MrCrayfish's Furniture)

**Comment by Wissi** [comment]
Well, that's unavoidable and is NOT a mod issue. It's a "conflict" of recipes which is very common. Issue should be closed IMO, nothing to do here?

**Comment by Raycoms** [comment]
I think we can in the future try to find a way to offer unique recipes. A
way would be to make the recipes include the build tool but give the build
tool back to the player after crafting.

2017-03-07 15:03 GMT-03:00 Wissi <notifications@github.com>:

**Comment by kedamono** [comment]
There is a mod for disambiguating recipes, it's appropriately called, _[NoMoreRecipeConflict](https://mods.curse.com/mc-mods/minecraft/238123-stimmedcow-nomorerecipeconflict)_.

**Comment by Wissi** [comment]
Well if there is a system to create recipes with a bounty I'm guessing it will include ALL recipes?

**Comment by pmardle** [comment]
Any appetite for making our own crafting bench block for our mod and making colony chests only craftable in that? - Can be supplied as part of the supply chest.

**Comment by Raycoms** [comment]
We could just include the build tool into every recipe and but make the
build tool return.

2017-03-16 10:47 GMT-03:00 pmardle <notifications@github.com>:

**Comment by marchermans** [comment]
You could would be simple enough
Should i take a look at later tonight?

**Comment by Raycoms** [comment]
Yeah. I think that would be quite simple and guarantee compatibility. Just
have to refine the build tool recipe a bit, because it is quite bad with
compatibility as well. If people lose it, they can't craft anymore.

2017-03-16 13:11 GMT-03:00 Orion <notifications@github.com>:

**Comment by cheongchan** [comment]
Just make the build tool the only thing that requires common materials. I guess there will be only one potential for conflict there. 

However, it might not be simple.
Since some recipes take up 9 slots, adding one more required item would change many of these.

Also if the npcs will be able to craft both mod items and vanilla items at some point, they must also have this build tool too or some special condition must be set for the crafting table or npc.

**Comment by marchermans** [comment]
Yeah i already dug into it.
It is fairly simple to change. However i am still looking into it.

I have exams right now, if somebody else wants to take a look he is more then welcome.

**Comment by pmardle** [comment]
Ok, suggest it replaces the top centre plank in each case then.

**Comment by pmardle** [comment]
Just one question.. how do you craft the build tool :)

**Comment by Havvy** [comment]
How about the crafting recipes be a vertical stack of [Builder's Wand] [Unique Item] [Chest] where the unique item is something related to the hut?

**Comment by WORMSS** [comment]
+1

**Comment by Wissi** [comment]
kk.. anyone made progress with it? So I can add/replace all the WIKI recipes as soon as it's avail.

I agree all the recipes as they are, are fine just add the building tool in the top center block.

If there is a material there substitute it w/building tool, if empty just add building tool.

Building tool always returns to player's Inventory after crafting.

Crafting recipe is 2 sticks and 1 cobble, simple.
[https://wiki.minecolonies.com/wiki/1/recipes](url)

**Comment by xavierh** [comment]
No need to return the build tool as it is cheap to make

**Comment by WORMSS** [comment]
I would be pretty annoyed to have to keep remaking it for every building. 
It changes from needing a shovel to make a building, to you need a shovel embedded into every building.
The same way you need a bucket of milk to make a cake, but the bucket itself is not apart of the cake.
I know the analogy is not perfect, but hopefully close enough.

**Comment by xavierh** [comment]
build tool is cheap, don't know how to return an item, so the recipe will consume it
