### ISSUE TITLE
Builder block breaking speed consistent regardless of settings/upgrades.

### ISSUE THREAD

**Issue by CXWRTH** [ldtteam/minecolonies#6801]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 1.14.48
- Structurize Version: 0.13.148
- Related Mods and their Versions: ATM6

## Expected behavior
Builder is mining at a consistent speed even after 4 "block breaking speed" upgrades in the University.
In comparison the Miner is mining at what appears to be twice the speed now.

We've made a number of configuration changes to try and speed the builder up:
restrictbuilderunderground = false
blockminingdelaymodifier = 25

## Actual behavior
The builder is very slow at clearing underground. This wasn't that big a deal with cave schematics, but has become a significant hurdle with truedwarven schematics.

## Steps to reproduce the issue

1. Assign a builder to clear underground by placing a schematic underground.
2. Assign a miner.
3. Upgrade the university "Citizen Block Breaking Speed" upgrades. Comp

Observe significant difference in block breaking speed.

### Logs

N/A

### Notes
This is making it very hard to do a truedwarven build. It's taking IRL days to do a standard build 4x4 chunk build (e.g. builder)

## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Can disable "builder builds slower underground" or so btw

**Comment by CXWRTH** [comment]
As it says in the post... we set:

	#Should the Builder be slower when working underground? [Default: true]
	restrictbuilderunderground = false

**Comment by ravenbuilder934** [comment]
ravenderps++

**Comment by gattsuru** [comment]
Do you have PVP mode enabled?  As far as I can tell, that's the only thing that should prevent it from being applied.  Which is still probably a bug, but would help narrow it down.

**Comment by Raycoms** [comment]
I double checked this too, the only possibility should be the pvp mode enabled, but that would also slow down the miner.
I also tested this and increasing the builder skills resulted in a strong increase in speed as well. I can't see a reason why the miner would be faster but the builder is not, besides skill differences.

**Comment by Raycoms** [comment]
Stale issue -> closed
