### ISSUE TITLE
My villager (courier) reported an AI error

### ISSUE THREAD

**Issue by elementalia6** [ldtteam/minecolonies#6808]
### Prerequisites 

- [x] I am running the latest **beta** version of MineColonies for my Minecraft version.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: 0.13.480 BETA

### Logs

- latest.log:  https://gist.github.com/elementalia6/857e89ec827fdefd616590ae2b8443b2

## Steps to reproduce the issue / details

Create 4 level 2 acacia style courier buildings and a level 3 acacia style warehouse. Pause and restart each courier, after which 2 couriers must be fired. It was after these actions that one of the couriers reported the AI ​​problem.
Also, before that, couriers refused to work and just stood in the warehouse when they had active orders.

Just reporting the AI issue. 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by elementalia6** [comment]
Sorry, this is my first time on GItHub, I didn't immediately find the exact same topic :(

**Comment by ravenbuilder934** [comment]
480 beta is over 200 versions out of date, update
