### ISSUE TITLE
Town protection and mod TreeChopper

### ISSUE THREAD

**Issue by RedAlex** [ldtteam/minecolonies#681]
### Minecolonies version minecolonies-universal-1.11-0.6.2919
TreeChopper-1.11-1.1.1a

Minecraft  1.11.2

Forge 13.20.0.2252
### Expected behavior

- Cut tree in a town without right in. Nothing do.

### Actual behaviour

- Cut tree in a town without right in. With the mod Treechopper. The base of the tree don't disapear but all other part of the tree are cut and drop on floor.

**Comment by Raycoms** [comment]
https://github.com/DuchLord/TreeChopper/issues/40

Reported to them.

2017-03-07 11:53 GMT-03:00 RedAlex <notifications@github.com>:

**Comment by Wissi** [comment]
The LJ is coded to chop the tree down from **top to bottom** and the "tree chopper" mod requires the tree to be "hit" in the **bottom log** to then drop the rest of the logs **above** it. 
So there will be issues as to what the "tree chopper" mod will do when you hit the "Top" of the tree and expect the rest of the tree logs **below** to "fall off"

I really don't understand the concept: "•Cut tree in a town without right in. Nothing do."
I guess it's a google translate thing, so not very clear if you mean that you have set it to have to "right click" to bypass the mod and do nothing?

**Comment by Raycoms** [comment]
What he wants to say is that griefers can come into his town and use the
treeChopper mod to cut down the trees in his town.

2017-03-07 15:00 GMT-03:00 Wissi <notifications@github.com>:

**Comment by marvin-bitterlich** [comment]
closing as acknowledged by the mod author
