### ISSUE TITLE
Unable to remove recipe

### ISSUE THREAD

**Issue by uglyduck2k4** [ldtteam/minecolonies#6812]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.14.53-ALPHA
- Structurize Version: structurize-0.13.148-ALPHA
- Related Mods and their Versions:

## Expected behavior
With the Glass Blower and the Mechanic Hut, want to remove learned recipes that were given by default; Lantern from Mechanic, and Redsand to Glass.

## Actual behavior
Open the GUI for each of these huts to the List of Recipes. Scroll down and click Remove. I Will go back to the hut and the recipes are still there.

## Steps to reproduce the issue

1. Right Click on Hut
2. Click on "List of Recipes"
3. Scroll down to the unwanted recipe
4. Clicked Removed
5. Went back to it later, the recipe still there.

### Logs

- latest.log: none
- crashlog: none

### Notes
I would use these recipes if I had the materials, but they take priority over other "duplicate" recipes that are also given from the start. IE Sand to Glass or Nuggets around Torch.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Yeah, default recipes cannot be removed (or better they readd themselves), what you can do is change the order of recipes

**Comment by uglyduck2k4** [comment]
Thank you very much. Which is Priority? From Top to Bottom or Bottom to Top?

**Comment by Raycoms** [comment]
top
