### ISSUE TITLE
Builder completion -6383% complete on resource scroll.

### ISSUE THREAD

**Issue by CXWRTH** [ldtteam/minecolonies#6813]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.48-ALPHA
- Structurize Version: 0.13.48-ALPHA

## Problem description
Builder is reporting a completion percentage that does not seem possible on the resource scroll.

This was a dark oak citizen4 to citizen5 upgrade.

https://i.imgur.com/zUINZNK.png

The builder is working properly though and progressing through the upgrade. I originally saw the percentage as something like -7500% but didn't get a screen capture until he was already at -6300%.

### Notes or related things
I haven't been able to reproduce this.

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Try updating

**Comment by gattsuru** [comment]
Odd.  There was a fix on this matter in 0.14.18 or so.  ~~Can you confirm the version number?~~

We ended up going harder on [the AI side than the display](https://github.com/ldtteam/minecolonies/pull/6726), so it's certainly possible something snuck through, just odd to see it, and especially in that case; it's fairly close to one of my tests.

 EDIT: nevermind, we've talked last couple days about you having a more recent version.  I'll see about trying a replication, but may just push the caps again.

**Comment by EpicCraft1997** [comment]
I also got this when I was upgrading my plantation to tier 2, it said -422%

**Comment by Raycoms** [comment]
@CXWRTH do you know a way to reproduce this?

**Comment by darkninjas789** [comment]
Some times my builders will show a negative progress percentage. It seems to happen most when upgrading an exsiting hut and is sometimes fixed by resetting the request system.
