### ISSUE TITLE
Recipes and minium stock don't work after a few time 

### ISSUE THREAD

**Issue by artur1700** [ldtteam/minecolonies#6814]
Version: minecolonies-1.16.5-0.13.670 Alpha
FTB Direwolf20 Modpack for 1.16.5

After teaching a worker a recipe like smelting cobble to stone or set a minium stock like bread for restaurant, baker etc. they fullfill it for a while but after some time they just stop to maintain the stock and the worker stop working like never learn any recipe. If i set the same minimum stock again or teach the recipe again they start working.
City has about 70 people and i already resettet the RS System and restartet the Server.

**Comment by ravenbuilder934** [comment]
670 is about 90 versions out of date
