### ISSUE TITLE
Plantation worker only plants on sugar cane spots

### ISSUE THREAD

**Issue by Titanium237458** [ldtteam/minecolonies#6815]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.58-ALPHA
- Structurize Version: 0.13.148-ALPHA
- Related Mods and their Versions: No mod issue

## Expected behavior

Setting the plantation to plant cactus or bamboo causes the worker to plant those in the corresponding spots (cactus on sand above cobblestone without water, bamboo on sand above stone bricks).

## Actual behavior

The planter only plants cactus and bamboo on the spots that should be reserved for sugar cane. In some schematics those spots are put next to each other, which causes the planter to go into a loop when set to plant cactus, since previously placed cacti will break when new cactus is added. This continues until the planter has no cactus left to plant.

![2021-03-25_13 10 45](https://user-images.githubusercontent.com/8401588/112476023-befcee00-8d71-11eb-86da-453f512690ea.png)
![2021-03-25_13 25 05](https://user-images.githubusercontent.com/8401588/112476035-c15f4800-8d71-11eb-8b4e-a1ee520e7814.png)
![2021-03-25_13 40 09](https://user-images.githubusercontent.com/8401588/112476042-c3290b80-8d71-11eb-8ffd-5f2be6bf56e4.png)

## Steps to reproduce the issue

1. Make a colony in a testworld
2. Research the plantation (and not the upgrade "Double Trouble")
3. Build a plantation that plants cactus or bamboo

### Logs

- latest.log: https://gist.github.com/Titanium237458/3251fc861a878eb7740869a750d63c9b (As far as I saw, maybe lines 94, 128 and 169 are of interest)
- crashlog: No crash

### Notes

It's important to note that the plantation seems to work fine after researching "Double Trouble".
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Does this happen for all styles of plantation?

**Comment by Titanium237458** [comment]
So far I tried nordic, sandstone and acacia and it happened with those at least. I can test all styles, but it might take a bit.

**Comment by Raycoms** [comment]
The restriction nowadays is tag based and not "place based" anymore. So it shouldn't check for cobble sand etc anymore but instead for building tags

**Comment by Titanium237458** [comment]
> 
> 
> Does this happen for all styles of plantation?

Yes, just tested all styles, all had the same issues.

**Comment by Titanium237458** [comment]
Or rather I should say they have the same behaviour. It's not an issue per se for most of the schematics, but in particular the nordic, cave and truedwarven styles don't space out the postions or tags for sugarcane, which causes the planting loop with cactus, which is an issue
