### ISSUE TITLE
Dwarven Town Hall

### ISSUE THREAD

**Issue by uglyduck2k4** [ldtteam/minecolonies#6817]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.14.58-ALPHA
- Structurize Version: structurize-0.13.148-ALPHA
- Related Mods and their Versions:

## Expected behavior
Put down a Town Hall. Start the Colony, and wait for the first Citizen to appear. 

## Actual behavior
Put down a Town Hall. Started the Colony and no Citizen appeared after 10 minutes.

## Steps to reproduce the issue
1. Created Several new worlds
2. Place down the Town Hall
3. Waited
4.  No Citizens

### Logs

- latest.log: None
- crashlog: None
- 
### Notes
Wanted to try to build an unground Town, even tried to spawn on top of the Overworld.  No Citizen would ever come. Had to force spawn them in. 

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Did you change any town hall settings or config settings?

**Comment by uglyduck2k4** [comment]
Normally when placing the town hall, I will set everything to manual and turn off kids. I also was able to duplicate this when I just went into a new world, threw it down, and waited.

**Comment by ravenbuilder934** [comment]
Turning off kids also turns off initial citizens, so it could be that. The second duplication is odd though

**Comment by uglyduck2k4** [comment]
I will go over it and try to replicate it again then hit you back up

**Comment by uglyduck2k4** [comment]
I went back through my VOD, and appears i keep clicking kids off instinctively since those little buggers annoy me ;)  So the issue is resolved
