### ISSUE TITLE
Bug in the server console

### ISSUE THREAD

**Issue by Taknax** [ldtteam/minecolonies#6819]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context Exact MineColonies and Structurize versions (e.g. 0.9.126-ALPHA or 0.9.2-RELEASE) *and* the Minecraft version you're playing, please.

- Minecraft Version: 1.12.2
- MineColonies Version: 0.11.841-ALPHA
- Structurize Version: - 
- Related Mods and their Versions:

## Expected behavior
clean server console

## Actual behavior
What actually happens when this feature is used in its current state?
My server console spam an error

"[Server] Server thread/WARN [minecolonies]: Missing world capability with colony manager!"

## Steps to reproduce the issue

1. Open config
2. Open minecolonies.cfg
3. enableDebugLogging?

### Logs

- latest.log: 
- crashlog: 

### Notes
Is it because i enabled "enableDebugLogging."?

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
1.12 is not supported any more
