### ISSUE TITLE
Restaurant UI - add stock incorrect

### ISSUE THREAD

**Issue by smmmadden** [ldtteam/minecolonies#6820]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 36.1.2
- MineColonies Version: 0.14.53-ALPHA
- Structurize Version: 0.13.148-ALPHA
- Related Mods and their Versions:

## Expected behavior

Each hut "Add Stock" UI should be based on the function of the building and not pull in every item the game has.  The restaurant UI shows items that are not applicable and doesn't work properly.  Take the screen shots below.
## Actual behavior

![image](https://user-images.githubusercontent.com/10309346/112706662-1be4cb00-8e7c-11eb-8dbd-22a6d554067a.png)
![image](https://user-images.githubusercontent.com/10309346/112706668-21daac00-8e7c-11eb-8057-c96154bee3b4.png)
![image](https://user-images.githubusercontent.com/10309346/112706671-2606c980-8e7c-11eb-9106-021ee188b640.png)

To add food I have to now search for everything instead of previously, I could just select and click OK.  The filter is not properly filtering out the items as well.  I typed in raw and Raw and all I see is Raw Pumpkin Pie, but clearly there are raw foods. :-)

## Steps to reproduce the issue

1.   Add Restaurant
2.  level up to 5
3.  click on second tab (left) to Add minimum stock.

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.
EDIT:  Just for kicks, I filtered on "hut" and look what I see.  Don't think this is the desired behavior.
![image](https://user-images.githubusercontent.com/10309346/112706744-bcd38600-8e7c-11eb-8d55-48d6d1dba0eb.png)

**Comment by Raycoms** [comment]
For now this is intended behaviour. This allows you for example to stock things like cooking utensils or fuel as well up to a minimum stock in the building.

**Comment by smmmadden** [comment]
That's all well and good, but it is making it too difficult to locate anything in the list.  "Filter" or search for something does not show what the user is looking for as seen in the screen shots.  I get the piece about utensils (whenever they get added), but why can't I see all the food categories first (for the restaurant) and locate items by names (e.g. raw, cooked, food, etc.)?

**Comment by Raycoms** [comment]
The matching issue is solved in my current PR
