### ISSUE TITLE
Can't upgrade some of my pre-update buildings

### ISSUE THREAD

**Issue by viniisnap** [ldtteam/minecolonies#6824]
On some of the buildings I have had built back on 1.16.4 v1.9, I now upgraded my server to 1.16.5 v1,7 and have noticed for some of my Asian buildings (AsianAlt citizen1 and AsianAlt guardtower2) I cannot upgrade them, as instead of the upgrade button, it just says "Wrong Style!" and even when I cycle to the correct style, nothing happens. I can't deconstruct or repair the buildings with this issue as well.

**Comment by ravenbuilder934** [comment]
yeah this is because there was a typo in the style name (`asianalterantive` instead of `asianalternative` iirc) which was fixed. Breaking the hut block and rebuilding should fix it, and shouldn't happen again
