### ISSUE TITLE
crash on removing disease from config

### ISSUE THREAD

**Issue by masmc05** [ldtteam/minecolonies#6828]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version:minecolonies-0.14.61-BETA-universal (also tested on minecolonies-0.14.58-ALPHA-universal)
- Structurize Version:minecolonies-0.14.61-BETA-universal
- Related Mods and their Versions: 

## Expected behavior

just normal world load
## Actual behavior

I removed a disease from config because I wasn't rich enough to give 20 golden apples to citizens to cure them, afther that, minecraft crashed on every try to load world

## Steps to reproduce the issue

1. wait until someone have a disease
2. remove that disease from config
3. restart the game
4. try to load the world

### Logs

- latest.log: 
[2021-03-28-3.log](https://github.com/ldtteam/minecolonies/files/6217208/2021-03-28-3.log)
[2021-03-28-1.log](https://github.com/ldtteam/minecolonies/files/6217209/2021-03-28-1.log)
[2021-03-28-2.log](https://github.com/ldtteam/minecolonies/files/6217210/2021-03-28-2.log)
- crashlog: 
[crash-2021-03-28_14.01.05-server.txt](https://github.com/ldtteam/minecolonies/files/6217199/crash-2021-03-28_14.01.05-server.txt)
[crash-2021-03-28_14.06.25-server.txt](https://github.com/ldtteam/minecolonies/files/6217200/crash-2021-03-28_14.06.25-server.txt)
[crash-2021-03-28_14.13.53-server.txt](https://github.com/ldtteam/minecolonies/files/6217201/crash-2021-03-28_14.13.53-server.txt)

### Notes

readded the disease in config and world is loading as usual 
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by gattsuru** [comment]
Fix in review under https://github.com/ldtteam/minecolonies/pull/6798 .  I just got distracted by client/server problems.

**Comment by Raycoms** [comment]
Duplicate
