### ISSUE TITLE
forge and bakery and quarrys  not building or working at all   

### ISSUE THREAD

**Issue by deathishere420** [ldtteam/minecolonies#683]
### Minecolonies version

version minecolonies-universal-1.11-0.6.3027

### Expected behavior

- well when you place the forge or bakery or quarry it should put the constrution tape around the size of the building it is building or in the queue

### Actual behaviour

- well when you place the forge or the bakery or quarry it dont do any thing 
![2017-03-07_17 36 16](https://cloud.githubusercontent.com/assets/10132950/23683900/27f6a206-0361-11e7-8590-d10895f02484.png)

### Steps to reproduce the problem

1. make and then place the forge or bakery or quarry
2. ZYX
3. ...
4. Profit

**Comment by Raycoms** [comment]
Not yet implemented
