### ISSUE TITLE
Build Tool and Guard Scepter crash

### ISSUE THREAD

**Issue by egeis** [ldtteam/minecolonies#6831]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context
- Minecraft Version: 1.16.5
- MineColonies Version: 0.13.684-BETA
- Structurize Version: 0.13.148-ALPHA
- Related Mods and their Versions: See crash log.

## Expected behavior
Not crashing with a null pointer exception.

## Actual behavior
Scrolling to the Build Tool or Guard Scepter causes a client crash.

## Steps to reproduce the issue
I am having difficulty narrowing down the exact steps.  On Building placement I always select "Level 5".

1. Use the build tool to place a guard tower.
2. Place Structure (checkbox).
3. Switch to Guard Scepter and Activate.

"Saving" - Forge / Java Crash.
Attempting to Reconnect causes "Joining" -> "Saving" (crash)

I resolved the issue by teleporting my player to another player and having them kill me during loading.  
Once I was able to reconnect without crashing

1. Scroll to Build Tool - Crashes again.

After repeating the steps of being killed during loading.

1. Hotkey number select builders tool, no crash. 
2. Use Build Tool.
3. Press (X).
4. Go to another slots.
5. Scroll back - Causes crash.

### Logs
- crashlog: https://gist.github.com/egeis/ac2c5dd361c8bcd71aead813883d7ee4

### Notes
Life in the Village 2 - Modpack

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Should be fixed in newest.
