### ISSUE TITLE
AI is broken

### ISSUE THREAD

**Issue by mc76855** [ldtteam/minecolonies#6834]
[latest.log](https://github.com/ldtteam/minecolonies/files/6224774/latest.log)
![Base Profile Screenshot 2021 03 29 - 17 37 55 05](https://user-images.githubusercontent.com/35856387/112904788-79189080-90b7-11eb-9fdf-4a4b47272f9d.png)

**Comment by Raycoms** [comment]
Same exception, but on a different worker, but the same worker #5672
