### ISSUE TITLE
Problem with Construct GUI

### ISSUE THREAD

**Issue by Kanulol** [ldtteam/minecolonies#6837]
Hi! i have a issue/problem  with the Mine Colonies GUI, can't Turn, move, change model, etc....anyone can help me? This Minecraft are 1.16.4 version

https://youtu.be/EjSbS0vmlV4

Have these mods:

Carryon, Ceramics, Citadel, Coalstone, CookingForBlockheads, Create-mc, CreativeCore, Creeperconfetti, CrockPot, Curios-Forge, Cyclic, Decorative-Blocks, Druidcraft, Dungeon-plus, Durabilityviewer, DynamicSurroundings, Easy_Villagers, FallingTree, FarmersDelight, VoxelMap, GargageBins, Gravestone, Iceandfire, invtweaks, ironchest, Jei, Mantle, "Mcw-Bridges, Doors, roofs, Windows" Minecolonies, Morevanillalib, Mysticalworld, Obfuscate, Optifine, OuterEnd, "Pamhc2crops, Foodcore, foodextended, trees" Patchouli, Placebo, ratlantis, Rats, Reap, Refinedpipes, scalingHealth, Silentlib, Simplybackpacks, StorageDrawers, Strawgolem, structuregel, structurize, Alpha, supplementaries, The Abyss, torchmaster, torohealth, TravelersBackpack, upgrade Aquatic, valhelsia structures, vanillahammers, veichlemod, waterstrainer, Waystones.

**Comment by Raycoms** [comment]
Please fill in the entire template

**Comment by Raycoms** [comment]
Closed until template is filled in.
