### ISSUE TITLE
Crusher worker prefer using materials from their inventory rather than inside their hut 

### ISSUE THREAD

**Issue by warning-djkajslh** [ldtteam/minecolonies#6838]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- MineColonies Version:
- Structurize Version:
- Related Mods and their Versions:

## Expected behavior
I tried to make an auto item delivery systen that deliver cobblestone from my mine straight to my crusher. I expected to see then take out the stuff from inside their hut to work.

## Actual behavior
The workers ask for the items despite it is present right there in the huts inventory, that mean I have to now have some sort of method to drop the item and have the worker to pick up, and thats a no.

## Steps to reproduce the issue

1. Build crusher hut and hire worker
2. Set the worker to crush 999 cobblestone and save
3. put the items inside the hut
4. The worker will ask for the items
5. Now put the item inside the worker manually.

### Logs

- latest.log: 
- crashlog: 

### Notes
Not sire if this problem alsp present for any other workers, have only tested with crusher and report.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by warning-djkajslh** [comment]
Update: The crusher seems to work normally after I relog, taking stuff out of their hut, then I decide to play with the sawmill, and when I just hired the worker, they glitched the same way, I have to personally put stuff into their hands for them to craft. Havent relog onto the world yet, still playing around with crashes.

**Comment by Raycoms** [comment]
Providing things to their hut in means of 'not through the courier' doesn't work. Does it work when the courier delivers the items on demand?

**Comment by warning-djkajslh** [comment]
Don't know tbh, but when I relogged the crusher was fixed and was working with stuff that I put in

**Comment by warning-djkajslh** [comment]
Trying the latest alpha, issue still exist

**Comment by Mekle001** [comment]
Does the crusher work when there is a request for the materials from the postbox?

**Comment by warning-djkajslh** [comment]
Sorry for the late reply, but no, the issue persist even if there is a request

**Comment by Raycoms** [comment]
Got reworked
