### ISSUE TITLE
Builder AI issue

### ISSUE THREAD

**Issue by Moobien** [ldtteam/minecolonies#6842]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 14.70
- Structurize Version: 13.148
- Related Mods and their Versions: n/a

## Actual behavior

AI Crash after building Fortress Alternative Mystical Site Lvl2 (schems attached)

## Steps to reproduce the issue

1.  Build Lvl 1 Fortress Alternative Mystical site - ok!
2.  Build Lvl 2 Fortress Alternative Mystical site
3.  Builder AI issue.

### Logs

- latest.log:  https://gist.github.com/Moobien/40f04e30e5a85b9cc5bbc0e407ce7c5f
[fortressalternative2.zip](https://github.com/ldtteam/minecolonies/files/6240205/fortressalternative2.zip)

- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ToMe25** [comment]
This should be fixed pretty soon, until then a workaround is to have no numbers in the style name.
Just write "_two" instead of "2" and it should work fine.
