### ISSUE TITLE
Fisherman do not fish at any level

### ISSUE THREAD

**Issue by smmmadden** [ldtteam/minecolonies#6844]
### Prerequisites 
Add fisherman hut
- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 36.1.3
- MineColonies Version: 0.14.70-ALPHA
- Structurize Version: 0.13.148-ALPHA
- Related Mods and their Versions:

## Expected behavior

Fisherman actually fish in the water given them

## Actual behavior

Fisherman complains the water isn't large enough (7x7) even though it was 7x7.  Also complains that the water has to be as tall as the house too.  Really?  Not sure why that matters, when its the depth/width of the water that apparently matters.

![image](https://user-images.githubusercontent.com/10309346/113235981-00116880-9272-11eb-9bd1-b024772c2c87.png)

Measurements: 13W x 3D X 7L.  We added to the default 6L (front to back) 1 block to make it 7.  This was broken in 0.14.67-ALPHA as well.
## Steps to reproduce the issue
Should be able to just build a fishermans hut and see what gets built for the Asian Style hut.   Most buildings in this Colony are Asian structures (something different than our normal). :-)

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Yes, this is not 7x7, it has to be continous 7x7, and by on the same y level it means, water must be at hut y level -1 .

**Comment by smmmadden** [comment]
why did you close it?  It's still a bug in that the building was not built correctly for it to function properly from Level 1 thru 5 so its a non-functional build.  We only added the extra row when the default build did not work.

**Comment by Raycoms** [comment]
That'd be a schematic error, but no, the buildings are not supposed to provide all the necessary water, like th elumberjack schematics don't provide trees, the fisherman schematics are made to be built close to water.

**Comment by smmmadden** [comment]
that would be good if there is water nearby.  Not all colonies are built near or anywhere close to water (Nether, End, other dimensions, Desert, etc.).The Lumberjack has a tool to select the area where to get wood from.  There isn't a tool available for the Fisherman or guidance in how deep, wide or high it should be since every building varies.  Users would have to guess the how to fix it so it works properly.  We haven't seen this in the previous 9 colonies built using different styles of huts.
Thanks! -Steve

**Comment by Raycoms** [comment]
Some styles indeed provide sufficient water, but this is up to the style author. The player does get the description for the fisherman to have 7x7 water. You could mine away a bit of space and place water there to fill it up.
