### ISSUE TITLE
Pirate ship error on changing world folder

### ISSUE THREAD

**Issue by masmc05** [ldtteam/minecolonies#6845]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version:minecolonies-0.14.70-ALPHA-universal
- Structurize Version:structurize-0.13.148-ALPHA-universal
- Related Mods and their Versions: - 

## Expected behavior

When it writes in chat that the ship sailed away, the ship really should ship away
## Actual behavior

it writes in chat that it ships away, but it doesn't ship away

## Steps to reproduce the issue

1. Create a world and get a raid with a pirate ship
2. move world to another instance that is in another folder (like from profile to other that curse launcher make) 
3. afther finish defeating the raid, the ship doesn't sail away, even afther saying in chat that it did

### Logs

- latest.log: [2021-03-31-1.log](https://github.com/ldtteam/minecolonies/files/6241543/2021-03-31-1.log)
[latest.log](https://github.com/ldtteam/minecolonies/files/6241545/latest.log)
[latest.log](https://github.com/ldtteam/minecolonies/files/6241556/latest.log)

- crashlog: 

### Notes

Firstly, it was in a world that i manually made a backup because I updated many mods and added some new, and I was afraid of compatibility, all was fine so I didn't need that world, I joined that world and defeaded a raid that was running, which was defeaded in main world, and got that error
I made some test, best for this situation, i think, is that I made a world with only minecolonies and structurize (Initially it was the same a earlier state of the same world mentioned before, but forge deleted succesfully all unncesesary), started a pirate raid with ships, then saved, I loaded a copy with the same mods in same folder, the raid ended without errors, loaded other copy with same mods in other folder, it ended with that error

If the schematics mentioned in logs is saved outside the world folder, i think this is the problem, because I finished the same raid twice, it trowed this error,and in simulation it trowed errors beacuse the schematic remained in previous folder, this error may make problems on backups load 

[used world, with a raid saved](https://drive.google.com/file/d/1lBo1V14V-mYkhVa-j1WX_fa4L79yOQOe/view?usp=sharing)

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Ships create a world backup of the place they spawned in. This is stored afaik in minecolonies/structbackup those have to be copied together with the world.

**Comment by masmc05** [comment]
So you say that broken backups mentioned in this issue is a normal price? ok,ok....

**Comment by Raycoms** [comment]
No, backups aren't broken, you just have to backup additional metadata too

**Comment by masmc05** [comment]
that by default isn't done by any backup mod, and what isn't mentioned anywhere, so the only way to know this, is having that bug and serching on bugs on github, right?
