### ISSUE TITLE
Citizens ignoring pillagers and dying to them

### ISSUE THREAD

**Issue by Lariag** [ldtteam/minecolonies#6859]
### Prerequisites 

- [ x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [ x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.80

### Logs

- latest.log: 

## Steps to reproduce the issue / details

I have a colony of 45 citizens now, but this has been happening from the begining.
Pillagers spawn, often in the middle of the colony, and the citizens keep walking to their jobs or stay idle in the street if they are unemployed, just ignoring the pillagers, until they got shot and die. Guards identify the pillagers as hostile if happen to walk nearby and eventually kill them.

To reproduce:
Create a colony and play the game. It will happen at some point.

Tried to use the command "gamerule disableRaids true" and drink milk, but they keep coming and being ignored.

### Notes

---

Created the village with minecolonies alpha 0.13.645 (something like that, a bit before version 0.14 came).

## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
https://github.com/ldtteam/minecolonies-features/issues/351
