### ISSUE TITLE
Town Protection system NOT protecting doors.

### ISSUE THREAD

**Issue by Wissi** [ldtteam/minecolonies#686]
The Towns protection system will allow anyone to open/interact with doors of any type. (trap doors, levers, buttons, etc.)

The "Keys" plugin used to take care of that aspect as well as the chest protection. Then on new server the "Latch" plugin, but now BOTH are non-existent server side and Town protection system does NOT protect doors, trapdoors, levers, buttons, etc.

Will it be implemented in the Town protection system or can we get the "Keys" or "Latch" plugins back at least meanwhile?

**Comment by Raycoms** [comment]
There is no real event for the door open, lever switched and button clicked
which makes that detection quite ugly. Is it really necessary? Since your
chests and everything are protected well?

2017-03-10 0:20 GMT-03:00 Wissi <notifications@github.com>:

**Comment by Wissi** [comment]
Players complaining that other players can walk around their Towns, opening doors, accessing areas they would like to keep private. Using buttons and levers for redstone devices and making a mess, leaving them on, emptying their containers, creating excess materials, etc. etc. etc.

Specially because the "Nether Portal Fix" mod does NOT work with sponge due to that Sponge handles the Portals differently and overrides the mod. So other players come back from Nether and most reappear in a different Town.

In general causes a lot of issues that people complain a lot about in game.

**Comment by marchermans** [comment]
We could handle the playerinteract event for the protection?

**Comment by Raycoms** [comment]
Yeah but we would have to check for lever, button, door and everything
which involves redstone manually.

2017-03-10 14:26 GMT-03:00 Orion <notifications@github.com>:

**Comment by marchermans** [comment]
You could use a list in the config file and check the registry name

**Comment by Wissi** [comment]
A list of item or item ID's? 
It's only a few blocks; doors, buttons, trap doors, and levers. (All variants)

Maybe they can be read from the config file (and any other modded block can be added there as well) with an enable/disable option(?).

**Comment by marchermans** [comment]
It would be a list like this: Modid:blockname

So for the minecraft door it would be: Minecraft:door

**Comment by Wissi** [comment]
kk So if it's doable it would be the same concept for issue #667 

And get two birds with same coder?
