### ISSUE TITLE
Minecolonies crashing Aternos server 

### ISSUE THREAD

**Issue by froggygg** [ldtteam/minecolonies#6860]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context structurize 0.13.148 ALPHA universal, minecolonies 0.14.77 BETA universal

- Minecraft Version: Forge 1.16.5
- MineColonies Version:minecolonies 0.14.77 BETA universal
- Structurize Version:structurize 0.13.148 ALPHA universal

## Problem description
I hosted a server thorught Aternos with these versions of the mod, the server crashed on startup. When i showed the log to the support of Atternos they said its Minecolonies causing this, i even tried older version. Help please i really want to play with my friends, and we also have other mods on the server but theres no issues, in singleplayer everything works. Please help me if you can. Thanks

### Notes or related things
Here is the log btw - https://mclo.gs/c9YvwZI

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
That shouldn't be in the beta, but in the alpha. But the latest alpha should also fix that. I just a bit ago pushed a hotfix.
