### ISSUE TITLE
Followup to the Aternos server crashing because of MineColonies

### ISSUE THREAD

**Issue by froggygg** [ldtteam/minecolonies#6861]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:Forge 1.16.5
- MineColonies Version:minecolonies-0.14.79-ALPHA-universal
- Structurize Version:structurize-0.13.148-ALPHA-universal

## Problem description
So i installed the latest versions of the mods i saw, the Alpha versions as i was told earlier and it still crashes. I asked about it again on the Aternos help they just said its this mod causing it and i should try other version.  In singleplayer it works perfectly.

### Notes or related things
 Here is the crash log - 
https://mclo.gs/uuFDgY7

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
https://www.curseforge.com/minecraft/mc-mods/minecolonies/files/3262045

Starting this version its fixed. Idk why you can only see 79, but we already released several ones after that.

**Comment by froggygg** [comment]
ok ill try it tommor and ill let you know if it works, thanks
