### ISSUE TITLE
Rendering issue - problem happened after update

### ISSUE THREAD

**Issue by Aduis1210** [ldtteam/minecolonies#6863]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.14.83-ALPHA-universal
- Structurize Version: structurize-0.13.160-ALPHA-universal

## Expected behaviour
Able to render chunks

## Actual behaviour
Issues rendering chunks after teleporting

## Steps to reproduce the issue
Update to latest MC and Structurize 

### Logs

- latest.log: https://gist.github.com/Aduis1210/70795ab17db5d69216ba7d8f7a4beeb7

### Notes
No Hard crash - rendering issues

![2021-04-05_10 01 02](https://user-images.githubusercontent.com/56609195/113557763-73123a80-95f6-11eb-8de9-a00f51c9e814.png)

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Aduis1210** [comment]
some chunk load when getting close others don't

**Comment by Aduis1210** [comment]
also to mention. unable to join server after bug occurs. fixes after server reboot

**Comment by Aduis1210** [comment]
@Raycoms any ideas dude?

**Comment by Aduis1210** [comment]
trying latest alpha

**Comment by someaddons** [comment]
minecolonies doesnt do anything at all to chunk loading nor chunk rendering, I'd check into your visual mods instead

**Comment by Aduis1210** [comment]
it seems to be fixed since the latest alpha so

**Comment by Aduis1210** [comment]
thanks for closing for me Raven. appreciate it
