### ISSUE TITLE
Server crash while placing townhall

### ISSUE THREAD

**Issue by devmasu** [ldtteam/minecolonies#6867]
- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ x ] I made sure that **this issue is not a duplicate of any existing issue.**

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.61-BETA
- Structurize Version: 0.13.148-ALPHA

## Expected behavior

My friend want to place his townhall and start his journey.

## Actual behavior

I have my own colony, created without problem.
My friend just placed his townhall with the wand, click to accept the location etc...
And boom, server crash each time. 

I already updated a couple of times the mod but the problem is still here.

## Steps to reproduce the issue

1. Place the supply camp
2. Place the townhall with the wand
3. Accept the location etc

### Logs

- crashlog: https://gist.github.com/devmasu/53cd7a557b4decc6dd7a2c0a72fe83e5

### Notes
We tried a couple of times and the server crash each time. 
I don't understand why I managed to create my colony and my friend can't.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Can you try updating to the latest alpha?

**Comment by devmasu** [comment]
No problem, I'm doing it and I'll put the result here !

**Comment by Raycoms** [comment]
How big did you put the initial colony range in the config?

**Comment by devmasu** [comment]
The initial colony size is still default, 4

**Comment by someaddons** [comment]
its probably a very high min dist between colonies

**Comment by devmasu** [comment]
Actually 60

**Comment by someaddons** [comment]
ye try lowering that, it loads and checks all chunks in that 60x60 area

**Comment by Raycoms** [comment]
Which your server can't hold.

**Comment by devmasu** [comment]
Just tried it with my friend, that was the problem!
Thx for the help!
