### ISSUE TITLE
Warehouse requests aren't recognized by the Sawmill

### ISSUE THREAD

**Issue by HappyAchilles** [ldtteam/minecolonies#6868]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 1.5.5 ATM6
- Structurize Version:
- Related Mods and their Versions:

## Expected behavior

The Warehouse has a minimum of 3 stacks of darkoak Fences set. So now it only has 2 so it requests one. Sawmill should have the task in the GUI and after recieving the materials craft the fences.
## Actual behavior

The Sawmill has 0 Task on the GUI even tough the Warehouse has the request for 64 dark oak fences. I recalled worker. restarted him. Nothing changed it. I even gave him more materials still nothing. Obviously I made the necessary Crafting recipe. 

## Steps to reproduce the issue

1.  Dont really know just found a colony and build Warehouse and a Sawmill and then set a minimum of Dark Oak fences in the Warehouse
2.  ...
3. Sawmill does nothing

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
the task only shows up when the worker has all the needed materials, can you double-check?

**Comment by HappyAchilles** [comment]
> shows

I will starting Minecraft now

**Comment by Raycoms** [comment]
yes, tasks only show up when the worker is ready to work on it. So if the task list doesn't show it, the worker can't work on it either. Giving the worker doesn't solve it, if for example a delivery is scheduled for the necessary items. The crafter will wait for fulfillment.

**Comment by HappyAchilles** [comment]
Did it still nothing

![2021-04-05_22 21 05](https://user-images.githubusercontent.com/81992953/113622696-9e7c4000-965d-11eb-8237-f8280de082b8.png)
![2021-04-05_22 21 12](https://user-images.githubusercontent.com/81992953/113622697-9f14d680-965d-11eb-9f77-474652e68241.png)
![2021-04-05_22 21 18](https://user-images.githubusercontent.com/81992953/113622702-9fad6d00-965d-11eb-83f5-df1a426960f0.png)
![2021-04-05_22 21 02](https://user-images.githubusercontent.com/81992953/113622705-a0460380-965d-11eb-9ecb-63ff2cb27031.png)

**Comment by Raycoms** [comment]
If there is a courier, coming to deliver sth, the worker will wait for that. Since those are the ones fulfilling the request.

**Comment by Raycoms** [comment]
Are you sure there is no courier with a delivery task to there?

**Comment by HappyAchilles** [comment]
> 
> 
> Are you sure there is no courier with a delivery task to there?

Pretty Sure because the task has been up for like 1 hour

**Comment by HappyAchilles** [comment]
Does there need to be a Builder that needs the Fences for the Sawmill to start working? Because right now there is just a request from the Warehouse because it has less that i put as minimum

**Comment by HappyAchilles** [comment]
> 
> 
> Does there need to be a Builder that needs the Fences for the Sawmill to start working? Because right now there is just a request from the Warehouse because it has less that i put as minimum

I now think that that is the problem. I think the sawmill doesn't recognize the request of the Warehouse to fill its stock up as a task. Because i just had a request from a builder that needed dark oak trap doors the Warehouse didn't have them so I teached the recipe to the sawmill and it instantlly crafted them.

**Comment by ravenbuilder934** [comment]
? it not recognizing warehouse requests is still a bug

**Comment by Mekle001** [comment]
Can you cancel the warehouse request, and does it come back?

**Comment by Raycoms** [comment]
Double cecked this, works fine. this is probably because the task was stuck because it was launched at a moment it was assigned to the player already
