### ISSUE TITLE
[Compatibility] [$5] Harvest Festival

### ISSUE THREAD

**Issue by DcNdrew** [ldtteam/minecolonies#687]
Harvest festival is another townbuilding mod, but it's more. It disables vanilla crops, so seeds what farmers plants, won't grow. HF crops are also different, because they use 9 soil for one click, they only grows at 6:00 am, and need to be watered, irrigating doesn't work.
Minecolonies' farmer acceps HF crops, but when he/she plants it, the crop became a "NULL seed" without texture. And it's only one crop.
By the way, this last thing doesn't need to be changed, because you can get your seeds only by buying from the store, so if you want an automatic farming with Minecolonies, you have to use much more money.

**Comment by marvin-bitterlich** [comment]
This seems like a thing we need a fake player for. And in that respect a Harvest Festival worker for these special crops. Because planting in 3x3 messes up all the normal farmer calculations.

**Comment by DcNdrew** [comment]
It can be cheaper in work if the farmer found a HF seed in the scarecrow, he doesn't want to do anything, except harvest when crops are ready.
Anyways, if you want to make better tools, you have to use them. You should hoe the field, place sprinklers, plant the seeds and that's it. The farmer will collect them. It's enough.

**Comment by Raycoms** [comment]
Is there anything we can do to recognize HF seeds in the code? (Besides
importing the mod) ?
Like do they have a special name or similar?
@Kostronor might we get the mod prefix of the "item" to use it?

2017-04-05 9:17 GMT-03:00 DcNdrew <notifications@github.com>:

**Comment by DcNdrew** [comment]
Seeds name is harvesfestival:crops_seed, and the type of them should be in NBT tag. I'll find out.

**Comment by DcNdrew** [comment]
Yup, NBTExplorer says:
id: harvesfestival:crops_seed
tag: 1 entry
    Crop: harvestfestival:cabbage

**Comment by marchermans** [comment]
You can just check the item for its registry name.

**Comment by Raycoms** [comment]
Will be added to a new joint mod compat issue.
