### ISSUE TITLE
Citizens seem to see stairs as air all of a sudden

### ISSUE THREAD

**Issue by Talyda** [ldtteam/minecolonies#6873]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.16.4
- MineColonies Version: 0.14..84
- Structurize Version: 0.13.160
- Related Mods and their Versions:

## Expected behaviour

for them to walk around stairs, or on them

## Actual behaviour

Citizens come to a spot where there is a stair on top of a block in front of them, and stand there constantly trying to jump up on to the block

## Steps to reproduce the issue

1. Put a stair on top of a block in the way of a citizen
![bouncy](https://user-images.githubusercontent.com/17323101/113700422-fbd3c800-9715-11eb-9bed-0f9e52ee2daa.JPG)

2. wait for them to get to it
3. watch them bounce!

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Wait, did you put the stair there while they were already walking into that direction, or long before?

**Comment by Talyda** [comment]
There was one there already when I noticed he behaviour, I removed that stair, and she jumped on top of the block and went on her way. I exited the game and updated minecol and struct, then put a stair there again while she was still in her builders hut, pretty sure she was not on her way, and she did the same thing. I mean, I can test it again to be sure, but I have an appointment, so won't be able to for a few/several hours

Main reason it actually even clocked in my brain that that was what they were doing was because yesterday this person here said it as well:
https://discord.com/channels/139070364159311872/741531022872674314/828743370599956570
And I blithely told them "it might seem that way, but nah, they see them as blocks" - then I got in my game and had to eat my words =P

**Comment by Talyda** [comment]
Updated the game again (mcol .90, struct .162) put the stair back, but she was already on her way to the same spot (she did get stuck there again) so I recalled her to the builders hut, and fired her, but as she was already on her way to the build site, she got to the same spot again and started bouncing there again, so I recalled her to the tavern and slept the night, then rehired her and she took a different route to the build site, because of course she did =P
But the very first time it happened it DEFINITELY was a stair that had been there a long time, cos it was one of those dirt stairs that are dotting the landscape from whatever mod does that in the monsters and mineshafts pack

**Comment by Talyda** [comment]
I haven't been able to reproduce this again. But I know the first time it happened it was very definitely a stair that was already there before the building was ever placed, because I hadn't moved any of the dirt stairs until this happened.
So not sure if I should close this until I see it happen again?

**Comment by Raycoms** [comment]
I'll try to reproduce this later today

**Comment by Raycoms** [comment]
Yeah I double checked this. This might be a problem only if the stair is placed after path creation.
