### ISSUE TITLE
Apiary "My AI has run into an issue"

### ISSUE THREAD

**Issue by HappyAchilles** [ldtteam/minecolonies#6876]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- MineColonies Version:

### Logs
I dont know what logs or where to find them I play on my own server. If somebody can tell me where to find them I will update with the logs

- latest.log: 

## Steps to reproduce the issue / details
Not reproduced I dont know

Just reporting the AI issue. 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
in the server files, go to `logs/latest.log`

**Comment by Raycoms** [comment]
please fill in the template too

**Comment by HappyAchilles** [comment]
Actually it works now after i restartet it so thx anyway
