### ISSUE TITLE
Farmers cannot harvest melons or pumpkins that grow outside of the range of the field

### ISSUE THREAD

**Issue by warning-djkajslh** [ldtteam/minecolonies#6879]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- MineColonies Version:
- Structurize Version:
- Related Mods and their Versions:

## Expected behavior
Farmers should harvest every melon or pumpkin even if they grow outside of the field

## Actual behavior
Stems that produces blocks outside of the radius is ignored by the farmer, albeit this can be fixed by player's intervention of placing strings on the plot's border

## Steps to reproduce the issue

1. Start a simple melon/pumpkin farm and wait until the farmer finish tilting the plot
2. Watch as the crops grow, sometimes they will grow outside of the harvestable area. Ex: Some stem will produce blocks, if the field's radius is 5 then the produced blocks at 6 is ignored.

### Logs

- latest.log: 
- crashlog: 

### Notes
Here's a simple image that demonstrate my point
![Screenshot (17)](https://user-images.githubusercontent.com/79503341/113888303-6bb48200-97ec-11eb-8482-ab84a8f5dc8c.png)

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
No, that is intentional. Their max range is the field range.
