### ISSUE TITLE
I keep crashing to desktop when opening "Build Options".

### ISSUE THREAD

**Issue by fpayne27** [ldtteam/minecolonies#6880]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 
- Structurize Version:
- Related Mods and their Versions: Life in the Village 2 1.16.5

## Expected behavior
 Being able to open Build options without crashing to desktop

## Actual behavior
 My entire game crashes when I click build options on any build gui

## Steps to reproduce the issue

 Go to any build gui and click build options

1.  Go to/craft any build gui
2.  Place block after crafting and right click block to open
3.  Click on "Build Options"

### Logs

 

- latest.log:  "The game crashed whilst ticking screen" "Error: java.;ang.IndexOutOfBoundsException:
- crashlog:  

### Notes
 I also cannot place any building with the building tool except a big well. I don't get any option to change what to build.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
full log please

**Comment by fpayne27** [comment]
![Uploading 91682AE4-2307-451A-BF3D-5942901ECE90.jpeg…]()

**Comment by fpayne27** [comment]
![7B58D887-9901-463D-BE5B-52D6FFA75C5A](https://user-images.githubusercontent.com/82127210/113953953-ef6b7000-97e6-11eb-9522-2fce274e307d.jpeg)

**Comment by ravenbuilder934** [comment]
that is not the log.

**Comment by ravenbuilder934** [comment]
the log is in `minecraftfolderhere/logs/latest.log`

**Comment by fpayne27** [comment]
[2021-04-07-6.log.gz](https://github.com/ldtteam/minecolonies/files/6275402/2021-04-07-6.log.gz)

**Comment by ravenbuilder934** [comment]
that is not the latest.log. (also, please put it in a pastebin/etc)

**Comment by fpayne27** [comment]
How do I do that?

**Comment by fpayne27** [comment]
[latest.log](https://github.com/ldtteam/minecolonies/files/6275412/latest.log)

**Comment by Raycoms** [comment]
This crash report is not the same as the one above right? Because that one is completely unrelated to us.

**Comment by fpayne27** [comment]
I have no idea to be honest. I have no clue what I'm doing I just know I have an issue with my build option

**Comment by ravenbuilder934** [comment]
well this log doesn't look like it has *anything* to do with minecolonies. are you sure you got the right one? right folder, right time/etc?

**Comment by Raycoms** [comment]
I did notice that. Now do you have a crash reports folder? maybe?

**Comment by fpayne27** [comment]
I'm using a modpack called Life in the Village 2, and everything was working fine until today when I tried building and the crash happened. Does this mean I need to file a report with Life in the Village then?

**Comment by fpayne27** [comment]
I figured the issue was with Minecolonies since that portion of the mod was what I was using at the time.

**Comment by Raycoms** [comment]
We still need the right crash log, the one you showed us showed an error on startup that has nothing to do with us.

**Comment by fpayne27** [comment]
I don't know where to find that then

**Comment by Raycoms** [comment]
We can't really help you at all without the crash log

**Comment by fpayne27** [comment]
[crash-2021-04-07_20.47.33-client.txt](https://github.com/ldtteam/minecolonies/files/6275551/crash-2021-04-07_20.47.33-client.txt)

Is this it?

**Comment by Raycoms** [comment]
:partying_face:

**Comment by fpayne27** [comment]
I really appreciate the help. Obviously I have absolutely no idea what I'm doing haha
