### ISSUE TITLE
Multiple lumberjacks chopping the same trees

### ISSUE THREAD

**Issue by warning-djkajslh** [ldtteam/minecolonies#6884]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- MineColonies Version:
- Structurize Version:
- Related Mods and their Versions:

## Expected behavior
Lumberjacks that are in a close proximity won't chop a same tree

## Actual behavior
Sometimes if the huts are close they will both targeted the same trees.

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
That is to a certain sense intended, lumberjacks work independently and including additional information would just blow the complexity and performance impact up.

Thus, it's an additional management task the player has, to put thought into the placement of lumberjacks to not put them too close to eachother.
