### ISSUE TITLE
Blocks missing in monsters and mineshafts modpack

### ISSUE THREAD

**Issue by Talyda** [ldtteam/minecolonies#6888]
- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 
- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.93
- Structurize Version:0.13.163
- Related Mods and their Versions: updated forge to 36.1.4

## Expected behavior
Blocks to be there

## Actual behavior
Blocks disappear

I don't know if this is a minecolonies problem, but that is where we were trying to sort it out - starting around here on the discord:
https://discord.com/channels/139070364159311872/741531816422539384/829867688557150248

Updating to the newest minecol and struct in this pack makes blocks disappear. The main one I tested was Caledonia level 5 house. Tested it in a pack that i have set up for making schematics, and it is fine, so assuming there s a conflict with one of the other mods in the pack 

Including the latest/log from right as I pasted the building in

Can provide the list of mods if anyone can tell me how to get that easier than copy/pasting each individual one from the curse page =P

kpop addict (on discord) mentioned
> it was always framed blocks with cobble and another wood or brick blocks from struc
> that were missing 

Also from them:
> i used 14.77 with struc 13.148 and it works all fine

## Steps to reproduce the issue

1. Am hoping Ray is still playing mineshafts and monsters, then he can check LOL
2. You can see it in the preview 
3. blocks missing

### Logs
- latest.log: https://gist.github.com/Talyda/3aaf327edb168d664d68c7b63fd6bbdd

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
...why did half of that disappear?
ALL the things are disappearing today!
Damn it! 
Well, then. My derp =P I left in "<!-- What actually happens when this feature is used in its current state?" and it made the rest not show up =P

**Comment by Talyda** [comment]
I have more information.
So, the pack is made in 1.16.4, and up until yesterday I had been playing it in 1.16.4 - but then Ray said about structurize needing the latest version of forge so I upgraded the pack to 1.16.5 (forge 36.1.4)

Today while I am playing, I am about to place a new house, and I happen to be using the Caledonia style, so previewing it at level 5, and there was no missing blocks! I thought maybe it had magically fixed itself somehow? So I made a new creative world, and nope! Those same blocks are missing.

The only difference as far as I can tell, is in my regular playing game, that world was made in 1.16.4, and when I started it up, it gave me the warning about the world being made in a different version and so on - clicked "I know what I'm doing" (they don't need to know I am lying =P) and started game up all as normal.  The saves I have been using to test the missing blocks were created post-update - so with the game already in 1.16.5.

I did double check by going into my other save that was made in 1.16.4, and the blocks show in that one too - so it's only happening in games created after I updated to 1.16.5

**Comment by Raycoms** [comment]
Can you test sth for me. Please try to convert it to 1.16.4 first and then
start it and then after that update to 1.16.5

**Comment by Talyda** [comment]
Convert it back to 1.16.4? Or start a new instance with 1.16.4?

**Comment by Raycoms** [comment]
it should've made a 1.16.4 backup I believe

**Comment by Talyda** [comment]
If it did I have no idea where! Sorry!

**Comment by Raycoms** [comment]
Check in the world folder for a zip

**Comment by Talyda** [comment]
Oh! You want me to load the minecolonies file (like colonies-2021-04-06_20.26.19) from when I had it in 1.16.4?
But load it up in the instance as I have it now in 1.16.5?
I think I am confused what you want me to do =P
(also feel free to DM me on discord if you want - it might be faster - Shindria in case you forgot =P)

**Comment by Raycoms** [comment]
okay:

This is a funny forge bug. You first have to update to 1.16.5 (without updating minecolonies) and then update MineColonies seperately.

**Comment by Talyda** [comment]
I'm not sure if mentioning it here helps - people that were doing a brand new install of the official minecolonies mod pack are also having this happen - gattsuru was looking at it a little yesterday on the discord
https://discord.com/channels/139070364159311872/741531022872674314/830906358500425778
And one of the people that was having it happen with a fresh install here:
https://discord.com/channels/139070364159311872/724810039281451028/830726524754722856

**Comment by Raycoms** [comment]
Yes, 1.16.4 doesn't work. It has to be 1.16.5+

**Comment by WTheDumbass** [comment]
I made a fresh download of the official minecolonies modpack on cursed forge two days ago and got this problem. I really dont understand what is sopposed to fix it? Is it making a world in 1.16,4 and then uppdating to 1.16.5 and playing on the older world? i've looked both here and on the discord and i havent seen anyone mention anything that would be the direct solution or the true problem to/of the bug. i have the latest required updates for minecolonies, Structurize and minecraft, never played on the older versions on this pack yet still have the bug. I don't mean to be rude but i need to know if this is just something thats gonna be fixed later with an update or something or if its something that i have to fix myself.
![image](https://user-images.githubusercontent.com/67751427/114546599-a2abed00-9c5d-11eb-8f5e-12da59735529.png)
(minecolonies won't run with structurize 164 so using 163)

**Comment by Raycoms** [comment]
Fresh download of the pack of an old world, right?

**Comment by WTheDumbass** [comment]
Its fully new, no old worlds, no nothing.

**Comment by Raycoms** [comment]
Completely new world, on the newest version and you're missing blocks??

**Comment by WTheDumbass** [comment]
Yes i have two worlds, both made on the new version, both have missing blocks.

![image](https://user-images.githubusercontent.com/67751427/114548854-9aa17c80-9c60-11eb-8af5-0b64e397e6f3.png)
The worlds.

![2021-04-12_20 27 42](https://user-images.githubusercontent.com/67751427/114549157-f53ad880-9c60-11eb-8e0e-7299fe4046d7.png)
![2021-04-12_20 28 23](https://user-images.githubusercontent.com/67751427/114549176-fc61e680-9c60-11eb-9918-7ff051529589.png)
![2021-04-12_20 35 33](https://user-images.githubusercontent.com/67751427/114549204-04ba2180-9c61-11eb-9c37-1809412a867c.png)
![2021-04-12_20 37 17](https://user-images.githubusercontent.com/67751427/114549209-0683e500-9c61-11eb-83cf-69f8c1ff1fa2.png)
some images of the missing blocks in the top world but the other one had missing blocks as well.

**Comment by Raycoms** [comment]
can you try the latest forge version?

**Comment by WTheDumbass** [comment]
Yes, i tried it just now and the bug still persists.

**Comment by Raycoms** [comment]
okay @ravenbuilder934 we need a rescan of basically all schematics on the schem server =P

**Comment by ravenbuilder934** [comment]
*twitches* I JUST did that! Fiinne

**Comment by TrashGypsie** [comment]
Sweet! tbh I thought I was just being stupid so gave up, lol. Can't wait to use the mod again.

**Comment by MazeusXenon** [comment]
I am running my own server and our own pack, but we are using version 0.14.101-alpha and the "homes" are still missing blocks with every level of build for the Caledonia schematics.

Or has this been fixed with a very recent update? Or should this be a new issue?

**Comment by VeareTheGreat** [comment]
Second what MazeusXenon is saying. Same issue, but on my own "pack". 
All blocks related to the Structurize Cobblestone variants don't generate, not in preview, not as a request for a builder and they don't spawn in when using a camp-spawning item (Asian to be precise)

Structurize is on 0.13.136-ALPHA-universal
Minecolonies is on 0.14.101-ALPHA-universal

**Comment by ravenbuilder934** [comment]
about half of the schems were fixed in 102 alpha, the rest should be fixed soon
