### ISSUE TITLE
No blocks in some areas

### ISSUE THREAD

**Issue by TrashGypsie** [ldtteam/minecolonies#6889]
### Prerequisites 

- [X ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ X ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.14.93-ALPHA-universal
- Structurize Version: structurize-0.13.163-ALPHA-universal
- Related Mods and their Versions: N/A

## Expected behavior
 Blocks being placed on walls with windows

## Actual behavior
 There are no blocks in caldonia/birch majoraty buildings

![2021-04-08_20 45 23](https://user-images.githubusercontent.com/76763441/114117364-26f02000-98ac-11eb-81e0-d0d3a9ff71fc.png)

## Steps to reproduce the issue

1.  Try to place a civilian house in caledonia style
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

Just wanted to say I really like the mod and point out this issue
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
#6888 likely
