### ISSUE TITLE
item icons are missing 

### ISSUE THREAD

**Issue by grtdrake** [ldtteam/minecolonies#6893]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.16
- MineColonies Version:0.13.670
- Structurize Version:0.13.146
- Related Mods and their Versions:

## Expected behavior

item icons should be present in menus and list 

## Actual behavior

I don't see item icons in the visitor hire button, it just says "hire for". Also item icons are missing from the material lists in the building hut and the requirements to begin research in the university. 

## Steps to reproduce the issue

no idea
1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

i am running the Direwolf20 1.16 mod pack version 1.7.0
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Reduce gui scale to <= 6. Duplicate issue. Fix in the works
