### ISSUE TITLE
Builders getting stuck trying to climb builds

### ISSUE THREAD

**Issue by smmmadden** [ldtteam/minecolonies#6895]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 36.1.4
- MineColonies Version: 0.14.92-ALPHA
- Structurize Version: 0.13.163-ALPHA
- Related Mods and their Versions:

## Expected behavior

Builders shouldn't get stuck climbing structures if there is no block to step on.  They TP everywhere else, so they could either build from the ground or TP to the block they need to continue.
## Actual behavior

Two structures so far that I see repeated jumping up/down and have to break one or more blocks to help them along.
University Level1 and Level2 so far in the corners shown.  I have to break the Smooth Sandstone Block and Stair.
Mechanics Hut - have picture of one bouncing up/down due to no free block to step on.

![image](https://user-images.githubusercontent.com/10309346/114256277-3f346d80-9986-11eb-9004-8896102aff25.png)
![image](https://user-images.githubusercontent.com/10309346/114256299-6428e080-9986-11eb-8fa6-ddd97d1d6f1c.png)
Another example of breaking the block to let him climb and then he gets stuck under the stair until I hit him to get him out of that spot.
![image](https://user-images.githubusercontent.com/10309346/114256388-efa27180-9986-11eb-8713-ec161be788fc.png)

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

Appears to be happening more since many of the structures have changed leaving blind spots where builders get stuck.  Also with the University, as all 4 sides are built the same, that's 8 corners and 8 upside down stairs the builder is stuck in. 
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
How long do they get stuck jumping there?

**Comment by smmmadden** [comment]
they'd stay there and non-stop jumping if I let them.  We've waited several minutes and nothing happens.  Just hitting them with nothing in our hands moves them, but they end up back to where they were.  Only breaking the blocks to where they are going is all that frees them.

**Comment by Raycoms** [comment]
Weird, I'd expect them to adjust after 30 seconds

**Comment by smmmadden** [comment]
I would too, but if they leave one spot (University), they would go over the other side.  Frustrating to no end as we break blocks for them to climb up and finish the build only to have to repeat it on the opposite sides and give them a nudge in the right direction.

**Comment by Raycoms** [comment]
Currently building a university on tmy test world of this style, will see if I can reproduc ethis.

**Comment by uecasm** [comment]
FortressAlternate hospital, level 2 upgrade to 3 I think it was, also had a similar issue (in an older build).  The builder would climb onto the roof and want to go further up, but couldn't until I broke a block for them.  They'd even go away at the end of the day and then return to the exact same spot.  Meanwhile after finishing the fortress house level 3 upgrade the builder went out to the balcony and just spun in place infinitely on the fence around it.  Even after breaking the fence for them, they seemed to want to jump down from the balcony instead of using the stairs inside (but they wouldn't actually jump since it was too far, so they stayed there across multiple days, frozen in place).  Even after hitting them they'd run away inside the house, then come back out to the same spot on the balcony.

**Comment by smmmadden** [comment]
I've seen very similar behavior as well.  I have to hit them with an open hand or recall them to their hut and sometimes have to fire/rehire them to reset them.  It isn't too often and not something easily reproducible.

**Comment by GrumpyPirate** [comment]
Can confirm I’ve had the same happen recently with the Caledonia barracks lv3 -> 4. There are multiple spots near the roof tiles where the builder would get stuck repeatedly, attempting to jump up a more than 1-block height. I had to baby him through the last few layers.
