### ISSUE TITLE
Swineherd's hut GUI missing second page.

### ISSUE THREAD

**Issue by warning-djkajslh** [ldtteam/minecolonies#6898]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- MineColonies Version:
- Structurize Version:
- Related Mods and their Versions:

## Expected behavior
There should be a second page for the swineherd's hut like any other animal herders

## Actual behavior
there is none.

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Nope, on purpose there is none

**Comment by ravenbuilder934** [comment]
(Since there's nothing they can collect if they aren't breeding. For the shepherd, as an example, they can still collect wool from shearing.)
