### ISSUE TITLE
Sifter and Crusher worker tend to keep stuff in their inventory instead of dumping them in the hut for pick up

### ISSUE THREAD

**Issue by warning-djkajslh** [ldtteam/minecolonies#6899]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- MineColonies Version:
- Structurize Version:
- Related Mods and their Versions:

## Expected behavior
Sifter and crusher would occasionally dump their inventory into their respective huts

## Actual behavior
They keep on stockpile their inventory, seriously, my crusher inventory is almost filled with stacks of gravel.
Maybe will post picture later.

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by warning-djkajslh** [comment]
Even with the sifters, the crusher don't seem to want to put gravels into the hut block for delivery. Yeah they stack up quite an inventory full if you don't do anything about it.

**Comment by Raycoms** [comment]
Afaik, improved
