### ISSUE TITLE
Guards swap good gears for low tier gears

### ISSUE THREAD

**Issue by warning-djkajslh** [ldtteam/minecolonies#6905]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- MineColonies Version:
- Structurize Version:
- Related Mods and their Versions:

## Expected behavior
Guards detect armies and weapons correctly and wouldn't prefer chainmail over Enchanted diamonds.

## Actual behavior

Guards prefer chainmail over diamonds

## Steps to reproduce the issue

My guards picked up some armors from killing zombies and equip them over the enchanted diamond armors I made for them.

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by someaddons** [comment]
guards use the best armor that they are able to use, check https://wiki.minecolonies.ldtteam.com/source/systems/worker
They need a certain building levle to use high level armor with enchants

**Comment by warning-djkajslh** [comment]
The thing is my guard tower is at 5, they **swap** the enchanted diamond armors for some chainmail that they picked up after killing mobs.
Chainmail is definitely not the best armor.

**Comment by warning-djkajslh** [comment]
Please reopen this issue

**Comment by warning-djkajslh** [comment]
For correction: The guards structure was at L5, and it happened, they swapped out the enchanted diamond that they were using and replace it with the raiders armors, it can't be the levels of the guards, as I put literally top tiers armors and they were usable. 
Maybe the modded armors weren't register as lower tiers? Should they compare the armors before swapping?
They got the armor after a raid.

**Comment by Raycoms** [comment]
Which modded armor?

**Comment by Raycoms** [comment]
Maybe we're not adding enchantments to the calc @someaddons ?
