### ISSUE TITLE
Guards in the barrack tower pick up multiple armor when fighting

### ISSUE THREAD

**Issue by warning-djkajslh** [ldtteam/minecolonies#6906]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- MineColonies Version:
- Structurize Version:
- Related Mods and their Versions:

## Expected behavior
Guards will only pick up one piece of armor, weapon or shield so that other guards can come and take it

## Actual behavior

They take multiple pieces, sometimes an entire set, leaving other guards with nothing.

## Steps to reproduce the issue

Was playing with Barrack towers in creative, and after I dragged and copy armors and weapons so that I don't need to equip each of them manually, and the result is that despite the extra armors, a guard was still left with nothing to wear.
Just have them carry enough, the excesses why be stored for later use.

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by someaddons** [comment]
they take just 1 of each piece as intended
