### ISSUE TITLE
Carpenter AI Error

### ISSUE THREAD

**Issue by Feramors** [ldtteam/minecolonies#6908]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.94-ALPHA
- Structurize Version: 0.13.163-ALPHA

### Logs

- latest.log: https://gist.github.com/Feramors/c2ab918c9ee7a11b453fad517099ea53

## Steps to reproduce the issue / details

Unsure what originally started errors. It was originally the blacksmith and the carpenter(sawmill in error log). At some point it was also my two builders, and now it's back to just the carpenter. Builders are also not building anything - they're just sitting there. 

Just reporting the AI issue. 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
did you directly update from 1.16.4 to 1.16.5 with this world?

**Comment by Feramors** [comment]
No, it’s been 1.16.5 the entire time, I do believe. 

Not sure if it’s related or whatnot, but it appears that all of the recipes for each of the jobs have been changed - it displays the resulting craft but not the required items. So the first column will be blank, where it would normally show the recipe for the item, but it would still show the resulting item. If that makes any sense. I do t have access to my PC right now, but it appears that me simply removing and re-adding those recipes resolves the issue. 

It certainly doesn’t explain why the recipes were removed in the first place, but it certainly is a fix.

**Comment by Raycoms** [comment]
We had some bugs and fixes related to the recipes, so that might be a leftover. Maybe @Mekle001 we should have a smaller validator on recipe load to check if it has an empty input?

**Comment by Raycoms** [comment]
fixed
