### ISSUE TITLE
Random server crashes "CitizenData.generateName"

### ISSUE THREAD

**Issue by Mario359** [ldtteam/minecolonies#6911]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.77-BETA
- Structurize Version: 0.13.148-ALPHA
- Related Mods and their Versions:

## Issue

The server randomly crashes with thousands of lines "at com.minecolonies.coremod.colony.CitizenData.generateName(CitizenData.java:470) ~[minecolonies:0.14.77-BETA] {re:classloading}"
This happened recently, a little after I made the Fletcher learn about carpet craft

### Logs

- latest.log: https://gist.github.com/Mario359/6767f319ecfc4b6e0e07d4a9ed3dccd1
- crashlog: https://gist.github.com/Mario359/b0c417649f59de36935cb859714529b0

**Comment by gattsuru** [comment]
Can you upload the names portion (`maleFirstNames` and `femaleFirstNames`) of your config file?  It _looks_ like it's trying to randomly generate a name and failed after at least 1k attempts, with each attempt finding a previous colonist with the same name.  That's something we should be handling closer, but the default names options have more names than the highest maximum colonist settings; even with birthday attacks and every colonist having the same last name, it should have found a free name well before then.

**Comment by Mario359** [comment]
I think it's due to the accents in the names, I had NPCs named Rémi (who appeared though) that I then removed from the mod configuration, I restarted the server and since then no more crash

**Comment by Raycoms** [comment]
I double checked this, this is only possible if you don't have enough naming variations and thus you'd have more citizens than possible combinations. This is intended behaviour. That's why there are many variants and not only 2-3.
