### ISSUE TITLE
(Server Issue) Migrated World to New Server. Can No Longer Interact With Colony as Officer.

### ISSUE THREAD

**Issue by DizzyDJW** [ldtteam/minecolonies#6913]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.13.670 ALPHA
- Structurize Version: 0.13.146 ALPHA
- Related Mods and their Versions:

## Expected behavior

After migrating world, I should still have access to interact with Colony.

## Actual behavior

Had to alter modpack. Reuploaded new modpack with minor changes to Builder Mine and Build Speed. Migrated over Backup World and could no longer access backpacks, break blocks, interact with colonists, etc...

## Steps to reproduce the issue

1. Have someone create Colony.
2. Be officer of said colony.
3. Reupload modpack.
4. Migrate over old world containing said colony.
5. See issue.

### Logs

- latest.log: [Latest Log](https://gist.github.com/DizzyDJW/05def395821c1aae4caa2b985e11dbb7)
- crashlog: N/A

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by quietust** [comment]
I suspect this issue is going to be closed because you claimed to be running the latest alpha (0.14.96-ALPHA as of the time you submitted the issue) while you're actually running a version from over a month ago (0.13.670-ALPHA, presumably from Direwolf20's 1.16 modpack).

**Comment by Raycoms** [comment]
By chance did you upgrade the version of MineColonies and then downgrade or similar on the way?

**Comment by DizzyDJW** [comment]
> By chance did you upgrade the version of MineColonies and then downgrade or similar on the way?

Yes actually I just realized that it must have been I copied the Direwolf20s modpack rather than the one I updated. Also I did figure it out you have to remove then readd yourself as OP on the server in question. Fix it will close now
