### ISSUE TITLE
University

### ISSUE THREAD

**Issue by Maximusaurum** [ldtteam/minecolonies#6914]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 
- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.95-BETA
- Structurize Version: 0.13.163-ALPHA
- Related Mods and their Versions: 

## Expected behavior
The University GUI should open

## Actual behavior
After I placed the university block with the build tool (truedwarven style) and try to right-click it to open its GUI (and build it), the game just crashes

## Steps to reproduce the issue
1.  Build a Townhall with the Build Tool
2.  Build a University with the Build Tool
3. Try to open the University GUI by right-clicking

### Logs
- latest.log: https://gist.github.com/Maximusaurum/026034b5d386ca57876960ed1fb2951c
- crashlog: https://gist.github.com/Maximusaurum/ef95d9d1db6350f35302a4bfc11357cb

### Notes
I tried out the issue with different Minecolonies versions because I played on Version 0.14.40 initially. Also tried different Forge Versions and removing Optifine. Changing the Building Style of the University (Acacia eg) does not change anything. 
Side note: Structurize Version 0.13.165 does not work, because Minecolonies says it requires 0.13.163. 

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by gattsuru** [comment]
Is this a public modpack, and if so, what's the name?  Can you see if the issue persists with [FancyMenu](https://www.curseforge.com/minecraft/mc-mods/fancymenu/files/3238517) and [Konkrete](https://www.curseforge.com/minecraft/mc-mods/konkrete/files/3239521) updated?

**Comment by Maximusaurum** [comment]
Its a private modpack for some friends and me. Taking FancyMenu and Konkrete out does not change anything, still crashes. 
New Crash report without konkrete & fancymenu: https://gist.github.com/Maximusaurum/7e70cc26300ba9d56a41f155461a4e01

**Comment by Maximusaurum** [comment]
Small Note: A friend of mine tried to click it on our server and for him it worked completely normal, no crash there. So it seems to be a problem with my PC I guess

**Comment by Raycoms** [comment]
Could you try re-downloading the jar?

**Comment by Maximusaurum** [comment]
I already tried that out, didn't change anything
But we found out what caused the crash. I used a texture pack from an old version and my friend didn't. When I take the texture pack out, the game does not crash anymore. So the problem was somewhere there. 
Still thanks for the help!

**Comment by Raycoms** [comment]
ohhh, that texturepack probably overrides the UI file, what kind of pack is this? where did you get it from?

**Comment by Maximusaurum** [comment]
Don't know, but playing without it fixes my issue

**Comment by gattsuru** [comment]
That's bizarre; it shouldn't really be able to remove any of the files Blockout is references.  Do you have the name of the texturepack?

**Comment by Raycoms** [comment]
You can override the xml file with a texturepack so that it misses an element
