### ISSUE TITLE
Nobody move

### ISSUE THREAD

**Issue by Hugo-rndj** [ldtteam/minecolonies#6918]
all the people of the colony no longer move at all no more action. This happened after I touched the updaterate.

What should I do ?

**Comment by gattsuru** [comment]
1) Fill out the template.
2) Put the updaterate back to its default value (1).  There is _very_ little reason to put it very high outside of debugging environments, and numbers above 5 are very likely to be frustrating.

**Comment by Hugo-rndj** [comment]
what do you mean by "fill out the template", excuse me i am not english. I wanted to increase because the builders don't build if I don't start next to them.

**Comment by Raycoms** [comment]
Reset the updaterate to the default. Your problem is with optifine and not the minecolonies config.

**Comment by Hugo-rndj** [comment]
Ah thank you that clears up this problem I must find where to fix it. And I have another problem but do I have to create another tread?
