### ISSUE TITLE
Need help with Town help

### ISSUE THREAD

**Issue by Hugo-rndj** [ldtteam/minecolonies#6919]
So I have another problem which I have not found the solution to. I unfortunately broke my town hall block and I put one back quickly, it's okay all my buildings were saved but while my town hall was level 4, there it shows me level 0 while I have the whole building built. What should I do if I want to raise it to level 5?

**Comment by gattsuru** [comment]
Building levels are stored in the building block; if the block is broken, the data is lost.  You can : 

* rebuilding from level zero, or
* use a build wand in creative mode to paste the completed building into place

**Comment by Hugo-rndj** [comment]
thank for the tips i will try !
