### ISSUE TITLE
No images for items/blocks in recipies or build options

### ISSUE THREAD

**Issue by Nawabu** [ldtteam/minecolonies#6920]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16
- MineColonies Version:  0.14.97-ALPHA
- Structurize Version: 0.13.163-ALPHA
- DireWolf20 1.16 Modpack Version 1.8.0

## Expected behavior
Seeing the images of blocks/items in the "List of Recipes" and "Build Options"

## Actual behavior

I am able to add recipies to buildings and they also seem to work. But I can not see the actual recipies (they are there, but show no block or item).

<img width="934" alt="example1" src="https://user-images.githubusercontent.com/8913490/114624247-b5034680-9cb0-11eb-9ea0-838c1989cdc4.PNG">

The same thing happens when clicking on "Build Options". Here the issue is a bit less anoying, as the name of the items is also written.

<img width="1541" alt="example2" src="https://user-images.githubusercontent.com/8913490/114624348-d6643280-9cb0-11eb-8715-aa68cf213e2d.PNG">

## Steps to reproduce the issue

1. Add A Recipe to a building
2. Click on "List of Recipies"
3. Or Click on "Build Options"

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Did you try reducing your gui scale to <= 6?

**Comment by Nawabu** [comment]
Thanks, that actually solved it. Now I just have to get used to it :-) I have a 4k Display and a GUI scale of 6 is a bit small for my taste.

**Comment by Nawabu** [comment]
Just as a further hint: In the university I can only see the tooltips for research with a scale <= 5 and I can only start a research with a scale <= 4
