### ISSUE TITLE
Deliveryman AI issue 0.14.94

### ISSUE THREAD

**Issue by laurad2423** [ldtteam/minecolonies#6922]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5 
- MineColonies Version: minecolonies-0.14.94-ALPHA-universal

### Logs

- latest.log: https://gist.github.com/laurad2423/6f4033339fe9e86f8668fd2c3f0c1293

## Steps to reproduce the issue / details

Just reporting the AI issue. 

### Notes

Playing on Valhelsia 3 modpack with a few extra mods
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Thanks for the report. Closing because of duplicate

**Comment by ravenbuilder934** [comment]
(#5672)
