### ISSUE TITLE
Server Crash on Version 1.9 March 31st update

### ISSUE THREAD

**Issue by Scarfo76** [ldtteam/minecolonies#6923]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
          - i have tested on the latest version 2.1 that is available and was this issue, andreverted back to 1.9 and still seem to have the same errors
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.16.5
- MineColonies Version: minecolonies-0.14.70-ALPHA-universal
- Structurize Version: structurize-0.13.148-ALPHA-universal
- Related Mods and their Versions:
All mods available in the v1.9 Download for Client and Server, On my latest tests, i have disabled Horseandstill, as well as Better caves and byg

Client side i have disabled Both Durability mods and Neat.

## Expected behavior

Expect the server not to crash? idk :p
## Actual behavior

Server randomly crashes with "server closed"
The server seems to randomly Crash, Random intervals. i have been mining in a cave, Feeding my pigs, or providing supplies to builders, and have seen it crash. 

![image](https://user-images.githubusercontent.com/82480081/114633862-338ec280-9c76-11eb-8853-8c2764e14574.png)

## Steps to reproduce the issue

1.  Place down camp / town hall, builder hut, 
2. Provide some materials to builder and go explore
3.  random crash, Server comes up fine, buy may crash again. 

### Logs

<script src="https://gist.github.com/Scarfo76/f058828bfa70817d5a16e8baef9d420c.js"></script>- latest.log: 
Dont See Crash Log :/ - crashlog: 

### Notes

I am Aware that One of the Better Tools, The Tripple Hammer, Causes a crash on Right Clicking the grass blocks, This was not performed during the latest crash.
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
> I am Aware that One of the Better Tools, The Tripple Hammer, Causes a crash on Right Clicking the grass blocks, This was not performed during the latest crash.

I just fixed this btw. Also, this is for mod issues, not modpack issues

**Comment by Scarfo76** [comment]
Thank you, i thought i was under the mod pack. will repost there regarding the mod pack issue.
