### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Scarfo76** [ldtteam/minecolonies#6924]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
      - i have tested on the latest version 2.1 that is available and was this issue, and reverted back to 1.9 and still seem to have the same errors
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

Minecraft Version:1.16.5
MineColonies Version: minecolonies-0.14.70-ALPHA-universal
Structurize Version: structurize-0.13.148-ALPHA-universal
Related Mods and their Versions:
All mods available in the v1.9 Download for Client and Server, On my latest tests, i have disabled Horseandstill, as well as Better caves and byg
Client side i have disabled Both Durability mods and Neat.

## Expected behavior

Expect the server not to crash? idk :p
## Actual behavior

Server randomly crashes with "server closed"
The server seems to randomly Crash, Random intervals. i have been mining in a cave, Feeding my pigs, or providing supplies to builders, and have seen it crash.

![image](https://user-images.githubusercontent.com/82480081/114635527-c3823b80-9c79-11eb-9162-97c011dea330.png)
## Steps to reproduce the issue

1. Place down camp / town hall, builder hut,
2. Provide some materials to builder and go explore
3. random crash, Server comes up fine, buy may crash again.

### Logs

<script src="https://gist.github.com/Scarfo76/f058828bfa70817d5a16e8baef9d420c.js"></script> - latest.log: 
- crashlog: 

### Notes

Sorry if this is in the wrong section, I went to Cursefurge, MineColonies Official modpack And Selected Issue and Was brought here, If this is still the wrong location for this mod pack, to be supported. Are you able to provide me with that Link? i am sorry :/
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
I don't know why this is linked from the curseforge page _wissi_, but it's only for minecolonies (the mod) support. This looks like a PVI crash, so https://github.com/ldtteam/PerViamInvenire/issues

**Comment by Scarfo76** [comment]
Thank you Raven! Sorry again!

**Comment by ravenbuilder934** [comment]
np :D
