### ISSUE TITLE
Smelter's ore request system still contain those that was turn off.

### ISSUE THREAD

**Issue by warning-djkajslh** [ldtteam/minecolonies#6925]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- MineColonies Version:
- Structurize Version:
- Related Mods and their Versions:

## Expected behavior
If you disabled an ore, it shouldn't be delivered to the smeltery at all

## Actual behavior
The courier delivered the ores anyway, and it just sitting inside of the smelter. 
In my case it is lapis, redstone and coal ores.

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
okay I double checked this, this is not the case, only if you had an old pending request that was still running. New requests are then done correctly.
