### ISSUE TITLE
Need to stop breaking schemas and force rebuilds

### ISSUE THREAD

**Issue by smmmadden** [ldtteam/minecolonies#6926]
### Prerequisites 
Update #6916 (0.14-100-ALPHA) - update states nearly all buildings have to be deconstructed/rebuilt.  This will never happen when we have almost a dozen colonies now.  I wanted to say something in the last round, but you really need to maintain backward compatibility or provide an option to correct them in each colony.  No one in their right mind that spent hours/days/weeks building a colony wants to have to deconstruct and rebuild the entire colony again.  That's just bad anyway you slice it.
- [ x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 36.1.4
- MineColonies Version: 0.14.100-ALPHA
- Structurize Version: 0.13.163
- Related Mods and their Versions:

## Expected behavior

If structures get updated, add the fix into the "Repair" option for all buildings.  This I thought was the intent behind schema changes to make it plausible to fix colony schematic issues.
## Actual behavior

Deconstructing and reconstructing small buildings may be easy, but as one that spends every night building and playing on our server, this will simply never happen.  Many structures are so big that it takes days to complete ONE level alone.  So starting over is really asking too much of the users.  I'd rather regen the area and build a new colony if that were the case (as a very last resort).  When making breaking changes like these, try to consider the players perspective in what is being asked.  As a multiplayer server host/owner and developer for several decades, it is just too much to tell our users to do.  It's good enough reason for them to just leave the server especially with how many thousands of MC Servers they can go to or use other mods instead.  We shouldn't be giving them reasons to leave.

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Schematics are provided by the community and not handled nor greatly regulated by us. This is either #5006 or talking the the respective channnels on discrd witht he respective creators

**Comment by smmmadden** [comment]
Thanks Ray for the quick reply.  Seems like a great opportunity to setup some guidelines the community should follow when contributing changes like these that can impact server owners and their players if not implemented in the most desired way. :-)

**Comment by Asherslab** [comment]
The point was more that we don't want to enforce any sort of guidelines like that. the PR was accepted knowing full well the implications of what it would do

**Comment by gattsuru** [comment]
For clarity, the issue only covers the `alternativemedievalspruce` and `alternativemedievalbirch` styles, and only the fifteen listed building types for those two building styles. 

Some buildings can probably be safely Repaired or even just left be until the next Upgrade.  Deconstruct/Reconstruct plays it safest, but it's probably an abundance of caution for cases where the anchor block (for building, the hut block) is in the same relative position in the upgrade schematic, and where the boundaries of the schematic are the same.  Unfortunately, some pieces like the barracks and barrackstowers required more invasive changes that are difficult to handle automatically and elegantly.

"Deconstruct/Reconstruct" here also means to use the Build Options->Deconstruct and Build Options->Pick Up, which allow the placement of the hut block using the build tool to get to its previous level in a single step, ie a level 3 bakery can be deconstructed, moved, and then reconstructed without needing to be built to level 1 or 2.  This does still take time and resources (and, unfortunately, may clip other buildings that then need a quick Repair in turn), but it's not _as_ bad as it sounds, even for those heavily effected.

If users have these buildings at level 5, or no longer plan to upgrade them, they can leave them in current form without issue (though they won't get the new and improved designs).  

As a last resort, the Build Wand can be used in creative mode to automatically and (<10s) instantly replace a building with its newer variant.  This takes little time for very large colonies, and we understand that not all servers can trust all users with creative mode even temporarily (or dedicate a trusted user for long enough to do this in a large enough server), but it is an option, if not one mentioned in the PR.
