### ISSUE TITLE
AI Error Courier 

### ISSUE THREAD

**Issue by ImHelyx** [ldtteam/minecolonies#6927]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.16.5/forge-36.0.46
- MineColonies Version:0.13.684-BETA-universal

### Logs

- latest.log: https://gist.github.com/ImHelyx/18849a9f506bc202075801e5481dffa1

## Steps to reproduce the issue / details

Wasn't keeping much of an eye on my Courier, was paying attention to my Builder (I find it satisfying to watch the whole structure go up)
Some things I can note, which may or may not be related:
- Any request my Builder made, I fulfilled myself - but only by adding the items to their inventory. Not by clicking the fulfill button. I would instead cancel the request. My Builder then stood still a while, and would need to be reset or would need to sleep the night.
- Builder was very lazy, and would need me to be near them to be woken up and to start their schedule. (Am I crazy? Or is that a silly hilarious mechanic?
- Courier Hut lvl 1; Builders Hut lvl 2

Just reporting the AI issue. 

### Notes
All submitted above
![2021-04-13_23 41 59](https://user-images.githubusercontent.com/82489214/114653230-95225180-9cb5-11eb-8252-0f4f109f86d4.png)

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
duplicate issue. We're aware of it yes, still trying to find ways to reproduce this.
