### ISSUE TITLE
Builder Mining Snow Block does not Update Dirt/Gras Block below it.

### ISSUE THREAD

**Issue by ppvolto** [ldtteam/minecolonies#6928]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5-forge-36.0.46
- MineColonies Version: >= 0.14.97-ALPHA
- Structurize Version: 0.13.136-ALPHA
- Related Mods and their Versions: None

## Expected behavior

Builder "Mines" a Snow Block on top of a Snowy Dirt/Grass Block and changes the snowy=true to snowy=false

## Actual behavior

Builder "Mines" a Snow Block on top of a Snowy Dirt/Grass Block don't changes the snowy state to false

![grafik](https://user-images.githubusercontent.com/720216/114786429-5e643e00-9d7e-11eb-858f-2f827e020c0b.png)

### Notes

Resolved with a Test rewrite of 
Rewriting the triggerMinedBlock Funtion for the EntityAIStructireBuilder and AbstractEntityAIInteract to:

AbstractEntityAIInteract
``` java
protected void triggerMinedBlock(@NotNull final BlockPos blockToMine, @NotNull final BlockState blockState)
{
      
}
```

AbstractEntityAIInteract
``` java
@Override
protected void triggerMinedBlock(@NotNull final BlockPos blockToMine, @NotNull final BlockState curBlockState)
{
    super.triggerMinedBlock(blockToMine, curBlockState);
    if (curBlockState.getBlock() instanceof SnowBlock) {
        BlockPos snowyBlockPos = blockToMine.down();
        BlockState snowyState = world.getBlockState(blockToMine.down());
        if (snowyState.hasProperty(SnowyDirtBlock.SNOWY)) {
            world.setBlockState(snowyBlockPos, snowyState.with(SnowyDirtBlock.SNOWY, Boolean.valueOf(false)), 2);
        }
    }
}
```
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
If you resolved it, a PR would be welcome :D

**Comment by ppvolto** [comment]
I am not a Good Coder and what edge cases there are for that Part of the Code that's why i have added a "working" snipped for the Devs :smile:
