### ISSUE TITLE
Cook Cooking/Distributing Foods Not in Hut's Food List

### ISSUE THREAD

**Issue by desagas** [ldtteam/minecolonies#6929]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5.36.1.2
- MineColonies Version: minecolonies-0.14.100-ALPHA-universal.jar
- Structurize Version: structurize-0.13.163-ALPHA-universal.jar (Latest not compatible with Latest MineColonies)
- Related Mods and their Versions: ATM6 1.5.10b

## Expected behavior

Cook distributes only the food items on the list of food in the hut, and only makes said food items and requested items in recipe list (using fruit salad from harvest craft for compost, for example).

## Actual behavior

Cook makes requested foods, like fruit salad, but made 1300 when min stock is set to 4 stacks (256), which I understand is min stock, so maybe intended, but the cook is baking and distributing baked potatoes when they are not selected in the food list. Actually, the cook has done this with mutton, requesting it and cooking it even though the food list was not set to distribute cooked mutton. I have not tested this with other foods, but, it seems to be baked (furnace) foods only that this happens with. Seemingly the recipes for furnace food override or take priority over the huts food list.

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

My colony is at 41/51 colonists, the town hall is at 4, the restaurant is at 4.

I thought perhaps it was related to a full warehouse, and the couriers moving stock out to the buildings, but, even with an empty warehouse, this happens.

The colonists were requesting better food, even though both baked potato and cooked mutton have less overall saturation, so, I am not sure it is related.

This would not be a problem, except the healer needs potatoes to cure the flu.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by GrumpyPirate** [comment]
We're having the same issue on v0.14.97 - in particular, we're having an issue where the cook/assistant endlessly make Cooked Carrots (from Mystical World), despite them being 'Off' in the served foods settings.

We've set the Cook up to serve crafted 2x2 foods that have raw carrots as an ingredient, but nothing involving cooked carrots.

**Comment by desagas** [comment]
This is not solved. The cook in 123-Alpha just distributed foods not in the list. This time, they were not vanilla and they were not in the list of foods to distribute.

**Comment by uecasm** [comment]
@desagas You're going to need to be more specific than that.  What food from what mod?  Was it already in the restaurant before you upgraded?  Have you tried removing it from the restaurant and seeing if it gets put back?

**Comment by desagas** [comment]
Sorry, Pam's Harvest Craft Chili Dog, Requires bread from baker, bbq sauce (the only condiment that the cook can cook because its edible), chili, hotdog and ground pork, and a few tools. The cook gave my chicken farmer the bbq sauce, and some of the vegetables used in the recipes. They are three deep in recipes to make the chili dog.

I did rest the cook and the assistant, remove both the recipes and put them back in, and also turned on and then off again the items for the recipe. I am going to check back. in a bit, and let you know if it was just behind, perhaps part of a previous request.

For your question, yes, I did remove it and it was put back, as it is part of the recipe for a higher teired food.

**Comment by desagas** [comment]
after a game restart, she is still distributing the crafting ingredients that are not selected to be dostribuited, and the colonists are eating them ... the chili, the hot dogs, and the bbq sauce. I will play around a bit more and see if I can find a fix or a reason.

Does the colonists level affect what food they are given, and does that take priority over the distribution list?

What is more strange, is she is distributing the chili and the hot dogs that are on her request list for a higher recipe.

**Comment by GrumpyPirate** [comment]
I'd like to back @desagas' claim, my cook is now handing out the constituent ingredients of the foods listed in their 'to serve' list over the actual recipes themselves. In particular, they're now handing out Cabbage (from [Farmer's Delight](https://www.curseforge.com/minecraft/mc-mods/farmers-delight)), which is part of a Stuffed Potato 2x2 recipe from, I believe (I can't recall atm), the same mod. I'm currently at work so unable to test restarting the worker/removing the recipe etc., though IMO this shouldn't really be necessary after a mod update.

The ingredients' hunger/saturation values are understandably lower than the full recipe, so this is odd.

EDIT - I should mention that the version we're using is [0.14.115-ALPHA](https://github.com/ldtteam/minecolonies/releases/tag/0.14.115-ALPHA), which I believe is the version specifically containing cook changes.

**Comment by desagas** [comment]
Yeah, I have both leve 40 workers and level 13 workers both receiving both high saturation and hunger foods, and lower ones.
