### ISSUE TITLE
Explosion protection after 100 blocks

### ISSUE THREAD

**Issue by Disastros** [ldtteam/minecolonies#693]
### Minecolonies version

version 0.6.2991

### Expected behavior

- The explosion proctection work anywhere in the colony

### Actual behaviour

- The explosion stop at 100 blocks, even after expanding the colony max range

### Steps to reproduce the problem

1. Change the colony max range in .config
2. Explode anything past 100 blocks

**Comment by xavierh** [comment]
Using git branch version/1.11.
I extended the TH range to 200. TNT do not explode if closer than 200. 
The problem seems to be fixed. (not tested in 1.10)

**Comment by xavierh** [comment]
Tested on git branch develop, same result
