### ISSUE TITLE
Builder won't build guardtowers anymore

### ISSUE THREAD

**Issue by lebanni** [ldtteam/minecolonies#6934]
### Prerequisites 

- [x] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- Structurize Version: 0.13.163
- MineColonies Version (if related bug): 0.14.100
- Related Mods and their Versions:

## Expected behavior

Builders build guardtowers.

## Actual behavior

Builder stand at the corner of the building area and does nothing.

## Steps to reproduce the issue

1.  Order the building of a guardtower.
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

I don't know if it's related but the building block is 167 blocks from the town center. I set the claim limit to 50 chunks.
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
Did they say that they were starting to build it in the chat?  Did the chat say anything when you clicked Build Building in the first place?

There is a max range for auto-claiming of work orders, beyond that you need to manually select a builder to do the build/upgrade before clicking the Build/Upgrade button.

**Comment by lebanni** [comment]
I did select the builder and I had the messages saying the construction was ordered et the one that says the builder start the construction.
Other buildings can be built/upgraded without issues.

**Comment by ravenbuilder934** [comment]
Is it only a certain style of guard tower, or all tower styles?
