### ISSUE TITLE
Worker won't build PirateShip Decoration

### ISSUE THREAD

**Issue by HappyAchilles** [ldtteam/minecolonies#6935]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- MineColonies Version:
- Structurize Version:
- Related Mods and their Versions:

## Expected behavior

The Worker builds the pirateship decoration
## Actual behavior

The worker walks to the buildsite then waits 1 second and turns around and goes back to his hut. There he checks some racks then goes back to the build site and repeats the same thing over and over again. He also isn't requesting anything. Or taking anything when going back to the hut from the racks

## Steps to reproduce the issue

1.  Give order to build Pirate ship
2.  hire a stupid worker
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.
The buildsite
![2021-04-16_13 48 44](https://user-images.githubusercontent.com/81992953/115020174-7e991780-9eba-11eb-89a0-d9bc81d5d037.png)
His inventory
![2021-04-16_13 50 31](https://user-images.githubusercontent.com/81992953/115020331-be5fff00-9eba-11eb-9716-5d0dadd1094f.png)

**Comment by fr3akb0y** [comment]
I dont remember exactly but I think I had that once too and fixed it by building a bridge around the building so the worker can go everywhere he wants without needing to go into the water.

**Comment by HappyAchilles** [comment]
> 
> 
> I dont remember exactly but I think I had that once too and fixed it by building a bridge around the building so the worker can go everywhere he wants without needing to go into the water.

Still just walked  straight into the water and then instantly turned around
![2021-04-16_14 12 54](https://user-images.githubusercontent.com/81992953/115022610-e7ce5a00-9ebd-11eb-9b86-60c1b7297d59.png)

**Comment by fr3akb0y** [comment]
I would build to where he is trying to go maybe he just doesnt have enough range for where he tries to build. My building was probably smaller so he could reach. But then again that is what helped me dunno if this is the same issue here :P

**Comment by HappyAchilles** [comment]
> 
> 
> I would build to where he is trying to go maybe he just doesnt have enough range for where he tries to build. My building was probably smaller so he could reach. But then again that is what helped me dunno if this is the same issue here :P
So now he didn't go into the water but stopped in the middle of the birch walkway at the top and then turned around??
![2021-04-16_14 19 18](https://user-images.githubusercontent.com/81992953/115023209-c1f58500-9ebe-11eb-9db8-bb2f2e7fe19b.png)

**Comment by ravenbuilder934** [comment]
versions?

**Comment by HappyAchilles** [comment]
> 
> 
> versions?

All the Mods 6 1.5.5 Minecraft version 1.16.5

**Comment by ravenbuilder934** [comment]
exact minecolonies version please

**Comment by HappyAchilles** [comment]
Dont know where can i check that

**Comment by ravenbuilder934** [comment]
in the `mods` folder or in the mods menu

**Comment by HappyAchilles** [comment]
0.14.21-Alpha

**Comment by ravenbuilder934** [comment]
that's 80 versions out of date, can you update?

**Comment by HappyAchilles** [comment]
Not really its in the modpack like that

**Comment by ravenbuilder934** [comment]
you can still update as long as you're not on a server

**Comment by HappyAchilles** [comment]
I can try to swap the files but how do i not loose any existing colonies?

**Comment by ravenbuilder934** [comment]
Nothing should break when updating, we try to make sure of that

**Comment by HappyAchilles** [comment]
Im on a server but im the admin we are only playing with 2 other people
so i have access to the files

**Comment by HappyAchilles** [comment]
I swapped the minecolonies jar  files on the server but then after restarting it crashed:
16.04 18:26:01 [Server] INFO net.minecraftforge.fml.ModLoadingException: Mod minecolonies requires structurize 0.13.163-ALPHA
16.04 18:26:01 [Server] INFO Currently, structurize is 0.13.148-ALPHA

**Comment by HappyAchilles** [comment]
Is there a way to get around that?
or are you not able to update it like that

**Comment by ravenbuilder934** [comment]
You also need to update structurize to 0.13.163 alpha

**Comment by HappyAchilles** [comment]
ah okay wait

**Comment by HappyAchilles** [comment]
So new Version is 0.14.95 Beta,
Stil the Same problem the Builder walkes up to the constructionsite and then turns around to return to his hut without doing anything

**Comment by Raycoms** [comment]
I got some fixes piling up in regards to this, can you do a quick check and remove everytthing from the builders inv and put it in their hut?

**Comment by HappyAchilles** [comment]
I completly stopped the construction now and restartet it for now it seems to work

**Comment by HappyAchilles** [comment]
nvm so he build the first layer and now we are back to the same problem and then I removed all the items in his inventory and then he took them back walked to the constructionsite had a red sign on his head for a quarter of a second and turned around

**Comment by HappyAchilles** [comment]
Still same pattern it looks like when he arrives at the ship he thinks that something is missing and then when he comes back to his hut its not missing anymore and so on

**Comment by HappyAchilles** [comment]
He even removes item in his inventory 
everything thats not in this photo gets removed
![2021-04-16_20 22 54](https://user-images.githubusercontent.com/81992953/115068260-50cfc500-9ef2-11eb-9bbc-042a1515c077.png)

**Comment by HappyAchilles** [comment]
I now started a norsemanship: SAME problem. The builder builds the first layer and then he goes back in the cycle always walking between the construction site and his hut

**Comment by Raycoms** [comment]
Might be a water problem then.

**Comment by HappyAchilles** [comment]
Don't think so as you can see in the image I built little bridges and the worker walked from the cobblestone bridge on the right all the way to the left (The gold block) then he turned around went to the builders hut checked all the racks and then came back to the ship and same thing again
![2021-04-17_01 33 57](https://user-images.githubusercontent.com/81992953/115094285-4aa30e00-9f1d-11eb-9090-deb39c5adcb7.png)

**Comment by Raycoms** [comment]
Uhhh, I'm sure they're trying to fill up the chests.

**Comment by HappyAchilles** [comment]
so should i fill them manually and if so with what?

**Comment by HappyAchilles** [comment]
Wait but there are no chests right now
there not even placed

**Comment by Raycoms** [comment]
they might be gathering the stuff to fill one

**Comment by HappyAchilles** [comment]
But they don't take any more items from the builders hut they just walk there and come back

**Comment by Raycoms** [comment]
yes, because it might be too much to fit into the inv or so.

**Comment by HappyAchilles** [comment]
Could be because the builder actually has a chest in their inventory. Any idea how to solve this?

**Comment by Raycoms** [comment]
render the schematic on top and check what would be next to place, try to place the chests at the places in it

**Comment by HappyAchilles** [comment]
Is there a command to speed up or even unlock research in the university because there is the one reasearch that makes the inventories bigger right?

**Comment by ravenbuilder934** [comment]
Research is instacompleted in creative mode
