### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by egeis** [ldtteam/minecolonies#6936]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context
- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.95-BETA
- Structurize Version: 0.13.163-ALPHA
- Related Mods and their Versions: See crash log.

## Expected behavior
Not crashing with a null pointer exception.

## Actual behavior
Opening up the Smelter building UI causes a Crash to Desktop

## Steps to reproduce the issue
Opening up the Smelter building UI I see the worker screen requesting Smeltable Ore but when I close the request it crashed.

### Logs
- crashlog: https://gist.github.com/egeis/684fe39497a88b1c92946d0b81b41e21

### Notes
Life in the Village 2 - Modpack

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by egeis** [comment]
I cannot control whether this pack is updated to the latest version or not, besides I reviewed the files that throw the error and they have not been updated since march 11th, and the current version was released after that release.

**Comment by Raycoms** [comment]
By chance do you have apostheosis installed?

**Comment by egeis** [comment]
Yes, its installed, i did not see any issues with it when I reviewed the issues tracker with the two mods.

**Comment by Raycoms** [comment]
Okay, there is a bug in the compat of Apostheosis and Farmers Delight that break a forge event and stop loading client side data. Unfortunately, it's impossible for us to fix this. The next release of Apostheosis fixes it, but might take a while (which is why our issue regarding this was closed).

Apparently "FastWorkbench" fixes this problem as a workaround.
