### ISSUE TITLE
ai issue

### ISSUE THREAD

**Issue by vetinte11** [ldtteam/minecolonies#6938]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: v 3.1 release on the curseforge/owerwolf minecoliones official modpack
 
### Logs

https://gist.github.com/vetinte11/05d7b7c8ef1b004dd6e2f638ab98c07c

- latest.log: 

## Steps to reproduce the issue / details

Just reporting the AI issue. 

### Notes

it was my miner that this happened too
I am running the modpack
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
1.15 is not being updated anymore
