### ISSUE TITLE
No spawner on pirate ships + colony dying when Minecolonies updated

### ISSUE THREAD

**Issue by Worfale** [ldtteam/minecolonies#6939]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: Minecraft 1.16.4
- MineColonies Version: minecolonies-0.13.586-ALPHA-universal
- Structurize Version: structurize-0.13.113-ALPHA-universal

## Problem description
 
I noticed that pirate ships were appearing without any pirate spawner, making them useless since they would simply disappear after a couple of days without any actual raid happening. After awhile, I decided to try to find a solution to this problem and thought about updating the version of minecolonies/structurize. I typed /mc backup for safety, updated the mods and then when I opened my world again, my colony was "dead". The buildings were there but all villagers were gone. 
I tried typing various commands such as /mc colonies list or mc colony info or /mc colony info <[player: online player] | [colony: colony id]> but they all behaved as if there never was a colony in the first place. 
/mc colony loadAllColoniesFromBackup doesn't make anything happen either.

Why does my colony break when I update the mod? Am I missing any step?

### Notes or related things

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
The spawners were fixed in an update yeah. What version did you try to update to?

**Comment by Worfale** [comment]
Alright! 
I tried migrating to MC 0.13.437 release / structurize-0.13.96-ALPHA-universal

**Comment by Raycoms** [comment]
Wait, so you downgraded, you didn't upgrade. Yes you can't just downgrade your version. That's not supported, especially not so many versions.

**Comment by Worfale** [comment]
You are right, I downgraded to make sure I play with releases and not alpha versions. I also realized 0.13.437 is for 1.16.5 and not 1.16.4.
Following your comment, I installed MC 0.14.97-ALPHA and ST 0.13.163-ALPHA on top of the backup of my world before it "died". Everything seems to work now, even the pirate ships.

Thank you!
