### ISSUE TITLE
Crusher unable to turn bones into bonemeal

### ISSUE THREAD

**Issue by Dyonovan** [ldtteam/minecolonies#6940]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: 0.14.100-ALPHA
- Structurize Version: 0.13.163-ALPHA
- Related Mods and their Versions: Forge-35.1.37

## Expected behavior

The ability to add recipe to crusher to turn Bones into Bonemeal

## Actual behavior

There is no option to teach crusher new recipes and there is no default recipe programmed in as other recipes are.

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
https://github.com/ldtteam/minecolonies-features/issues/363
