### ISSUE TITLE
Teeny Aesthetic Issue Related to Digging Snow

### ISSUE THREAD

**Issue by potatochan721** [ldtteam/minecolonies#6944]
When builders dig snow away to place a building they leave the snow textured grass block behind underneath. This is a very minor thing but the grey grass is a little startling when you first notice it. I'm going to guess this has to do with the way blocks are being broken by the mod since the civs obviously aren't actually digging, more like running a set of set block commands from what I've seen in gameplay. So the grass under the snow doesn't update its texture when the snow is removed.

![2021-04-16_22 30 23](https://user-images.githubusercontent.com/31110953/115099498-3dc5f080-9f04-11eb-9207-7346b68c462f.png)

This screenshot was taken while playing the 1.16 Direwolf20 Pack from the FTB launcher on 4/16/2021. 

 Since I've put this village in the snow my work around has been to clear the snow away before the builders get around to the plot and if I miss a spot I can go back and replace it with normal grass. This is purely an aesthetic issue. 
 
 I apologize if I'm repeating someone else.

**Comment by Raycoms** [comment]
duplicate https://github.com/ldtteam/minecolonies/issues/6928
