### ISSUE TITLE
The builder will not build even if you give him what he needs, he will just walk around, also it says we need racks for it to build him home, but it says it can only be build at the saw mill, witch can only be built by the builder witch he doesn’t do anything thing and you need the builder at level 1 to build anything eles please fix. 

### ISSUE THREAD

**Issue by TheCaneslife25** [ldtteam/minecolonies#6948]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 
1.12.2
- Minecraft Version:
- MineColonies Version:
- Structurize Version:
- Related Mods and their Versions:

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

The builder will not build even if you give him what he needs, he will just walk around, also it says we need racks for it to build him home, but it says it can only be build at the saw mill, witch can only be built by the builder witch he doesn’t do anything thing and you need the builder at level 1 to build anything eles please fix. 
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
1.12 is not further supported

**Comment by baraks300** [comment]
If you are still looking for a workaround for 1.12.2, downgrading to minecolonies-1.12.2-0.11.811-BETA-universal should help. I remembered using it in a Project Ozone 3 world and had no issues with the builders. downside is losing out on some of the  additions that come along with later builds.

**Comment by TheCaneslife25** [comment]
Ya I’ve tried that it still doesn’t work for me if you could can you sent me the link to the that works.
