### ISSUE TITLE
Whats the best Food to give to workers.

### ISSUE THREAD

**Issue by HappyAchilles** [ldtteam/minecolonies#6949]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 
All the Mods 6
- Minecraft Version:1.16.5
- MineColonies Version:
- Structurize Version:

## Problem description

More of a general question: My worker is complaining he wants better food but bread or steak are not enough what does he want or is there anything fairly easy to do? Its strange because the wiki says that they at most want food with 2.5 shanks but then bread/steak would be enough right.
### Notes or related things

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
For support, discord please
