### ISSUE TITLE
Need mycelium for enchanter upgrade, seed with no mushroom field

### ISSUE THREAD

**Issue by omgimtara** [ldtteam/minecolonies#6952]
### Prerequisites 

- [X] I am running the latest *ALPHA* version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.77-BETA-universal
- Structurize Version: ?

## Problem description
An upgrade of the Enchanter's Building requires Mycelium. My world seed does not seem to have a mushroom field. I cannot find one. Mycelium on netherrack from the nether does not spread to dirt in the overworld.
How are we supposed to finish this upgrade without mycelium? There should be a way to craft this if it is needed for an upgrade.

### Notes or related things
I've spent weeks on my fortress colony only to be thwarted by a seed with no Mycelium. :(

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
afaik all seeds have mushroom fields, I suggest using [nature's compass](https://www.curseforge.com/minecraft/mc-mods/natures-compass) to find one. Even if mycelium is rare, it's allowed in higher building levels, as long as it's not impossible to get

**Comment by omgimtara** [comment]
Hello! Thank you for that. I used the nature's compass and was able to find
mycelium.

I was interested in starting a new world using the "large biomes" type. I
found my perfect seed, and used nature's compass to make sure the biomes
containing the resources I need are available. However, in my large biomes
seed, according to nature's compass, there is no Mushroom biome. I am
hesitant to start a colony here which is tragic because I had been
searching for a seed with Valhesia houses in an Amaranth Field and FINALLY
found one, but there is no Mushroom biome!

So my question is, if there is no mushroom biome, is it possible that some
of the higher building levels require mycelium to be built?
Or, is there a type of building that doesn't require mycelium for any of
its buildings? For instance, the Fortress composter requires mycelium to
get to level 3, and you need to get to level 3 to build the florist. I
would not be opposed to trying a different building type like birch or dark
oak or something.

Thanks!

**Comment by ravenbuilder934** [comment]
Probably some styles don't require mycelium. I don't remember which ones though
Nature's compass only checks within a 20k block region iirc, and with large biomes...it's going to be hard to find.

**Comment by omgimtara** [comment]
Alrighty. That’s good to know. I’ll make a default world with the same seed
and use natures compass to find the mushroom fields, and go back to my
large biome world and see if it is there if I travel far enough.
If not, I’ll try a different building style.

**Comment by Nightenom** [comment]
3rd party program <https://www.chunkbase.com/apps/biome-finder>, also has a large biome option

**Comment by omgimtara** [comment]
Thanks everyone! I was able to locate the mushroom biome location in the
default seed, which I was able to use to locate it in my large seed.

Best,
Tara
