### ISSUE TITLE
Structurize fails to load properly and crashes server before it can start

### ISSUE THREAD

**Issue by Ramen-Nood1ez** [ldtteam/minecolonies#6954]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: 0.14.97-ALPHA
- Structurize Version: 0.13.163
- Related Mods and their Versions:

## Expected behavior

I would expect that the server wouldn't crash on startup
## Actual behavior

Server starts up and then when it starts to load up Structurize, it crashes.

## Steps to reproduce the issue

1. Install the Direwolf20 Modpack (version 1.8.0-1.9.0) on a linux server
2. Run the server
3. Then it crashes after it starts to startup

### Logs

- latest.log: https://gist.github.com/Ramen-Nood1ez/a91f4ec88dd575e6cd5e8b3c1f4e4e8f 
- crashlog: https://gist.github.com/Ramen-Nood1ez/729152119e0abec2ece45c1bf3327597 

### Notes

My server is running the Direwolf20 1.16.4 modpack
The server doesn't crash when the modpack is version 1.7.0 or less.
The structurize version was 0.13.146-ALPHA when the modpack was version 1.7.0
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
use java 8 or update minecolonies and structurize to the latest
