### ISSUE TITLE
Forester stuck on leaves when using Passable Foliage mod

### ISSUE THREAD

**Issue by ftzi** [ldtteam/minecolonies#6955]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.105-ALPHA-universal
- Structurize Version: 0.13.163-ALPHA-universal
- Related Mods and their Versions: PassableFoliage-1.16.5-2.2.1

## Expected behavior
Forester should be able to walk inside leaves when using Passable Foliage, or break them.

## Actual behavior
I have to from time to time go break the leaves that are on the same position of the forester, else he will just stay stuck there. Rarely he will teleport back to the hut. I don't know if this bug still happens when not using the Passable Foliage mod, but anyway, it shouldn't happen, as any NPC/player can pass through the leaves when using this mod. The pathfinding should ignore leaves if using Passable Foliage / check they aren't physical blocks

## Steps to reproduce the issue

1. Have a Forester Hut
2. Plant lots of saplings
3. Eventually the forester will get stuck inside leaves and won't just walk away or break them (even if having hoes)
4. Break the leaves occupying the same blocks as him, and he will continue his duties

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Feature request. https://github.com/ldtteam/minecolonies-features/issues
