### ISSUE TITLE
Cow herder still ask for a bucket if milking is turned off

### ISSUE THREAD

**Issue by warning-djkajslh** [ldtteam/minecolonies#6956]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- MineColonies Version:
- Structurize Version:
- Related Mods and their Versions:

## Expected behavior
He wont ask for a bucket if milking is turned off

## Actual behavior

Until the request of one bucket is filled, then he will continue to other activities

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
did you just turn the milking off?

**Comment by warning-djkajslh** [comment]
Yes, do I have to restart?

**Comment by ravenbuilder934** [comment]
okay, so then the issue is that requests for buckets don't get cleared when milking is disabled

**Comment by Raycoms** [comment]
that's fine, that was never the intention either. That would be a feature request then

**Comment by warning-djkajslh** [comment]
Why? I would expect turning the worker will not request the items immediately after the option is turned off, but here you have to restart the game for them to do so, and it is fine? And that this is a feature request?

**Comment by Raycoms** [comment]
They requested it already before you cancelled it, that was the point above, you don't have to restart.
