### ISSUE TITLE
People complaining about low quality foods in their inventory 

### ISSUE THREAD

**Issue by warning-djkajslh** [ldtteam/minecolonies#6957]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- MineColonies Version:
- Structurize Version:
- Related Mods and their Versions:

## Expected behavior

People complain about bad foods too much, even if they produce them, or they pick some up:
- Farmer, herders and fishers complain about raw crops and meats that they produced, and deny to eat that, meaning most of my workers will yell to my ear about foods
- Guards complains everytime they pick up some rotten flesh from killing zombies
Also, there are some instances where there are better foods already in their inventory, but they only focus on the bad stuff, then upset about it. There can be breads present in the inventory and the citizen wouldn't touch it

I forgot to take pictures sorry

## Steps to reproduce the issue

Could be replicate by giving a mixture of bad and good foods to the citizen. Otherwise just watch them, as they work this problem will occur

### Logs

- latest.log: 
- crashlog: 

### Notes

Really just want things to be changed into the old ways so that I can start dumping stacks of cheese in the restaurant again. Please have an option for it.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Version?

**Comment by warning-djkajslh** [comment]
The latest alpha on the curse
0.14.108

**Comment by HoeenCoder** [comment]
Confirming this was also occurring with `0.14.101-ALPHA`. I just updated to the latest version (`0.14.108-ALPHA`) and am still having the issue. I am running minecolonies on a private server with only one other mod for context (world edit 7.2.4).

**Comment by pete-koning** [comment]
Having same issue on 0.14.107-Beta. (I think you told us to use the most current beta instead of the alpha). 

Not every colonist complains but some do, including the cook. No matter what raw foods I bring her she always wants more food and better quality food.

**Comment by desagas** [comment]
> Version?

Also happening in Alpha 110. Fisherman will complain about raw foods, and farmer and cook / assistant about poor foods.

**Comment by desagas** [comment]
This is happening with the fisherman still in 123-alpha. It could be that it is because he is getting modded fish, from Aquaculture, to be specific, in ATM6 1.6.2.

**Comment by Aduis1210** [comment]
yeah same happens with me as well. - If you raise your cook to level three you can hire an assistance who can do recipes - this means you can turn the fish into fillets ect

**Comment by desagas** [comment]
Also adding: chicken farmer is still complaining as well.

**Comment by kihgy** [comment]
Can you reopen this, I see lumberjacks are also complain when they have apples, confirmed in minecolonies-0.14.129-ALPHA-universal

**Comment by ravenbuilder934** [comment]
129 isn't the latest, try updating

**Comment by kihgy** [comment]
Updated to the latest of Minecolonies, still occuring
Please make it so they will start eating anything again

**Comment by Raycoms** [comment]
We won't make it so that they don't eat anything. But we'll reduce the threshold of complaints so that they only complain when they are really very hungry

**Comment by warning-djkajslh** [comment]
Lol foods is that much of a pain to code, tbh I agree with kihgy, just revert the mechanic again, so we can feed citizens with whatever foods, and avoid them complaining ever again and so I can start dumping stacks of cheese into the restaurant.

**Comment by warning-djkajslh** [comment]
Also inst it when you are hungry you will be less pickly about foods, if they get too hungry they would just eat anything. Just make them dtop complain, if you are a bad mayor then the citizens will display it via their happiness stats.

**Comment by Raycoms** [comment]
There is no bug atm here, they just complain too early about it, that's all. And this mechanic is exactly such that you don't dump stacks of cheese, people don't survive off of stacks of cheese....

**Comment by warning-djkajslh** [comment]
If you are just going to delay the complain then that wouldn't really solve anything, as there are still complains about other modded foods and even vanilla stuff like apples from lumberjack, eventually they will complain anyway and this issue will be bring out again, just make them eat literally anything edible, like stacks of cheese.

**Comment by Raycoms** [comment]
They are SUPPOSED to complain if they don't have SUITABLE food in their inventory and they are hungry, ffs that is the reason this mechanic exists, so that you give them suitable food.

**Comment by warning-djkajslh** [comment]
We don't particular want citizens to eat those either, they need to understand that, and shouting out to our face about them acquiring bad foods from their work won't help either, as there are better foods in the restaurant.

**Comment by desagas** [comment]
134-Alpha, all good gathering colonists are complaining about raw and inefficient foods. This includes Shepard, chicken pig cow and rabbit ranchers, fishermen, lumberjacks, farmers, and all guards who happen upon zombie flesh or spider eyes. That being said, they are no longer complaining about it like they used to when they have both good food and bad foods together in their inventory.

Also, if they are complaining about it before even attempting to get more food from the cook, and that is lowing their happiness, which a mayor would have literally zero control over, it is a bug, otherwise, if the mayor has a chance to get better food to them before they lower their happiness, be it through the restaurant, allowed time for colonists to get the food, then it is not a bug, as literally nothing happens to your colony as a result.

**Comment by MatthiasMann** [comment]
Would it make sense that they somehow remember which items they picked up as part of their work and which they got from the restaurant and only try to eat what they got from the restaurant?

**Comment by marchermans** [comment]
Well yes and no.

This is kind of an issue with how inventories work.
Sadly there is no way for us to directly check if they picked the "food"-item during work or to actually eat it.

So any worker who produces food will try to feed himself first. And as such eat unprocessed, low quality, food.
In my eyes this is fine, however we need to figure out a way to make these kind of items a fallback.

Not sure how though. Food is only processed at the restaurant, so we would need to check if the restaurant has food available @Raycoms?
Like OnSearchForFood -> Check Restaurant -> If food available go there -> Fallback to own inventory search?

**Comment by MatthiasMann** [comment]
Maybe let them only eat at the restaurant - eg go there, get food (remember which food item it was), sit down and eat?
(of course this only applies when you have a restaurant - and they should also eat food given by the player while at the restaurant in case there was a shortage).

**Comment by someaddons** [comment]
could just not complain and treat non-edible stuff as non-food and just dumb it

**Comment by uecasm** [comment]
It would likely be a major pain in the butt, but it should be theoretically possible to give them some dedicated food slots that can only be filled by the cook (or the player), and where they search first for food before falling back to general inventory.

**Comment by warning-djkajslh** [comment]
Good riddance Minecolonies
