### ISSUE TITLE
Guards in barrack tower pick up multiple items of the same type in the hut's inventory

### ISSUE THREAD

**Issue by warning-djkajslh** [ldtteam/minecolonies#6958]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- MineColonies Version:
- Structurize Version:
- Related Mods and their Versions:

## Expected behavior

If you add in 5 armor sets plus 5 swords and shields, then each guards will only take 1 item each and left one for others

## Actual behavior

Not all guards pick only one, some will take multiples, and the other guards can fill the missing item request then he will not pick up anything else.

## Steps to reproduce the issue

1. Get sword, shield and a set of armor
2. build l5 barrack tower and hire workers.
3. Drag the items in the hut inventory so that there will be 5 of each
4. Observe.

### Logs

- latest.log: 
- crashlog: 

### Notes

I am aware of the same issue of my that got closed, yet I am still experiencing this one as I playing on the latest alpha and tried to drag and copy items in the barrack tower GUI for each guards to be completely armored and armed.
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
I tested this with my latest changes and can't reproduce it.
