### ISSUE TITLE
the baker is not recognized by my colony as an employee.

### ISSUE THREAD

**Issue by ghost** [ldtteam/minecolonies#6959]
### Prerequisites 

- [ok ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [ok ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.12.2
- MineColonies Version: minecolonies-1.12.2-0.11.841-ALPHA-universal

### Logs

- latest.log: 

## Steps to reproduce the issue / details

I don't know how to make this issues on your game because I was doing a normal game when I noticed that.

Just reporting the AI issue. 

### Notes

I have a baker he is well employed because it is marked on the interface and he has the outfit but when we go to the town hall it marks baker: 0 so when I order bread on the letter box it mark me can be solved by player so how I could fix it
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
1.12 is not supported
