### ISSUE TITLE
stuck on door

### ISSUE THREAD

**Issue by cheongchan** [ldtteam/minecolonies#696]
### Minecolonies version

version 1.11.2 playing mine colonies 1.11-0.6.2919
Forge 1.11.2-13.20.0.2255

### Expected behavior

- Delivery men going through doors okay

### Actual behaviour

- You see the three stooges effect where 2 deliverymen or some other npc attempt to go through door at same time and block each other. They just end up opening and closing door while stuck together. 

Solution?
Not sure if this got resolved already in later but, maybe there should be some sort of timeout where the npc gets the recall triggered so they dont get stuck.

**Comment by Raycoms** [comment]
Closed in favor of new issue soon.
