### ISSUE TITLE
Ai issue with deliveryman and stash

### ISSUE THREAD

**Issue by MikeDonaghy** [ldtteam/minecolonies#6961]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: Minecraft 1.16.5
- MineColonies Version: minecolonies-0.14.97-ALPHA-

### Logs

https://gist.github.com/MikeDonaghy/769b3613ed745927ad0634556d308040

- latest.log: 

## Steps to reproduce the issue / details

I was using the stash to put items into my warehouse I had to break and replace to get them to collect the resources not sure if this caused the issue or not I know it was the stash cause I looked a the log file

Just reporting the AI issue. 

### Notes

I am running the most recent version of the direwolf20 1.16 pack
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
#6326 duplicate

**Comment by Raycoms** [comment]
Sorry, I meant this: #5672

**Comment by MikeDonaghy** [comment]
thanks
