### ISSUE TITLE
the hubs r not there

### ISSUE THREAD

**Issue by yolokleine** [ldtteam/minecolonies#6962]
hello,
i have a big issue with the hubs. if i klick on them the menu dont open and in the chat come a message "this block is missing respective building try restart or laoding back up". what should i do next? i tried to restart it. i dont know if i have an back up.
sorry for the bad english im from Germany 
Thx

### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- MineColonies Version:
- Structurize Version:
- Related Mods and their Versions:

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
We need more info, what version are you on? What was the last version it was working on? Did you do a version downgrade?

**Comment by Raycoms** [comment]
closed until info is provided and template is properly filled in.
