### ISSUE TITLE
AI issue with deliveryman

### ISSUE THREAD

**Issue by MikeDonaghy** [ldtteam/minecolonies#6963]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: Minecraft 1.16.5
- MineColonies Version: minecolonies-0.14.97-ALPHA-

### Logs

- latest.log: https://gist.github.com/MikeDonaghy/769b3613ed745927ad0634556d308040 

## Steps to reproduce the issue / details

 was using the stash and got the issue from the deliveryman that was supposed to do the pickup

Just reporting the AI issue. 

### Notes

I am running the most recent version of the direwolf20 1.16 pack
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
#5672
