### ISSUE TITLE
Can't assign any worker

### ISSUE THREAD

**Issue by nevth** [ldtteam/minecolonies#6965]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version:  minecolonies-0.14.110-ALPHA-universal
- Structurize Version:       structurize-0.13.166-ALPHA-universal

## Expected behavior

I would like to assign workers.

## Actual behavior

I look into my Townhall and see six unemployed people, but I can't assign them to a workplace. Also "Automatic" won't do anything.

## Steps to reproduce the issue

1. Set worker assignment to manual
2. Try assigning
3. Empty screen
### Logs

![signal-2021-04-20-220949_002](https://user-images.githubusercontent.com/80281524/115458870-9e1ba180-a226-11eb-9478-82870ea81d33.jpeg)
![signal-2021-04-20-220949_001](https://user-images.githubusercontent.com/80281524/115458873-9f4cce80-a226-11eb-8aa4-7cdcd4cbdbbe.jpeg)

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Can you send a screenshot of your town hall settings tab?

**Comment by nevth** [comment]
![Uploading 2021-04-20_22.28.01.png…]()

**Comment by nevth** [comment]
![2021-04-20_22 28 01](https://user-images.githubusercontent.com/80281524/115460006-06b74e00-a228-11eb-8701-865039100635.png)

**Comment by ravenbuilder934** [comment]
odd. Do the unemployeds actually exist? Can you recall them?

**Comment by nevth** [comment]
yes, they can come into the townhall

**Comment by nevth** [comment]
ok, after restart they got jobs. strange
