### ISSUE TITLE
AI problem

### ISSUE THREAD

**Issue by Gimligs** [ldtteam/minecolonies#6968]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.14.107-BETA-universal

### Logs

- latest.log: https://gist.github.com/Gimligs/8c03265adbba2aafd0411562adc90d09

## Steps to reproduce the issue / details

Just reporting the AI issue. 

### Notes
![aierror](https://user-images.githubusercontent.com/70501979/115496652-6b939800-a26a-11eb-9ed0-469a68f4ecbf.PNG)

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Fixed in latest alpha
