### ISSUE TITLE
Colonists slow down to a crawl if I'm a chunk or two away

### ISSUE THREAD

**Issue by TheFafalStudios** [ldtteam/minecolonies#6972]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.107
- Structurize Version: 0.13.148
- Related Mods and their Versions:

## Expected behavior

When I walk a chunk or two away from a villager, they keep working
## Actual behavior

When I walk a chunk or two away, everyone slows down to a crawl 

https://youtu.be/IxbPLVA86-M
## Steps to reproduce the issue
run a mohist server with minecolonies, as this does not persist in singleplayer

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Optifine issue, disable lazy chunkloading

**Comment by TheFafalStudios** [comment]
it's not an optifine issue, as this does not happen on the client, only on the server

**Comment by Raycoms** [comment]
It's not a minecolonies issue either. Some mod causes this. Do you have optifine installed on the server in the mod folder?

**Comment by daantipov** [comment]
We run a mohist server with this modpack ([https://www.curseforge.com/minecraft/modpacks/life-in-the-village-2](url)) and also experience same issue.
