### ISSUE TITLE
Caledonia Level 5 Mystical Site Not Cleaning Up Through Upgrades

### ISSUE THREAD

**Issue by desagas** [ldtteam/minecolonies#6974]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5.36.1.2
- MineColonies Version: 110-ALPHA
- Structurize Version: 166-ALPHA
- Related Mods and their Versions: ATM6-1.6.1

## Expected behavior

Old blocks will be removed when upgrading that should not be part of upgraded version.

## Actual behavior

The mystical site from Caledonia does not remove old blocks, so, things like concrete powder piles are left behind, as are cobble items, quarts stairs, pillars, etc.

I forgot to catch a screenshot before deconstructing to repair from scratch. Sorry.

## Steps to reproduce the issue
Build level 1 Mystical Site from Caledonia, and upgrade each step to Level 5.

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
I double checked this, this is a #5006 issue.
