### ISSUE TITLE
Builder AI issue

### ISSUE THREAD

**Issue by Aduis1210** [ldtteam/minecolonies#6975]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- MineColonies Version:

### Logs

- latest.log: https://paste.ee/p/4Alpa

## Steps to reproduce the issue / details

Let the builder build - error appears

Just reporting the AI issue.  https://paste.ee/p/4Alpa

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Aduis1210** [comment]
Builder is wandering back and fourth between racks and the builders hut aimlessly

**Comment by Aduis1210** [comment]
She's still working so that's a bonus

**Comment by relsqui** [comment]
Not sure why this is closed, but I have a similar-looking error from my builder. MineColonies 0.14.112-ALPHA, Structurize 0.13.166-ALPHA, Forge 36.1.0, Minecraft 1.16.5. Log attached.
[latest.log](https://github.com/ldtteam/minecolonies/files/6362564/latest.log)

**Comment by Raycoms** [comment]
This is closed because it was fixed in 113 :joy:

**Comment by relsqui** [comment]
Oh great, I look forward to being able to update my pack at some point then. (CF says I'm up to date, even after updating Forge versions 🤷 but that's not your problem, heh.)
