### ISSUE TITLE
Medieval Spruce Builder (the one shaped like an "L") Level 2 materials

### ISSUE THREAD

**Issue by Desastermon** [ldtteam/minecolonies#6978]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.13.437-RELEASE
- Structurize Version: structurize-0.13.100-RELEASE
- Related Mods and their Versions:

## Expected behavior

Builder should have correct ressources required for the build

## Actual behavior

Builder requires 2 purpur blocks for builder level 2, which aren't used, but required to finish building

## Steps to reproduce the issue

1. Build medieval spruce builder's hut
2. Upgrade builder's hut to level 2
3. see required materials

### Logs

- latest.log: 
- crashlog: 

### Notes

I'm not sure which version of the spruce builder's hut it is. It is the one shaped like an "L" and has the ressources in the basement.
I don't know if this issue applies to other builders of that type, but I know that purpur blocks normally wouldn't be used for level 2 buildings (and they don't get placed either)

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
You're close to, maybe even over, 300 versions out of date - try updating and see if it's been fixed =)

**Comment by Desastermon** [comment]
> 
> 
> You're close to, maybe even over, 300 versions out of date - try updating and see if it's been fixed =)

Really? I downloaded the version from curseforge. I will check, if a newer version will fix the problem, thank you!

**Comment by ravenbuilder934** [comment]
issue reports on versions this old (we recommend the alphas) are invalid
