### ISSUE TITLE
Game crashed when interacting with NPCs. 

### ISSUE THREAD

**Issue by ealtrik6** [ldtteam/minecolonies#6979]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5 forge 36.1.4
- MineColonies Version: minecolonies-0.14.114-ALPHA-universal.jar
- Structurize Version: structurize-0.13.166-ALPHA-universal.jar
- Related Mods and their Versions:
Listed in LOGS below 
## Expected behavior

To open the gui and be able to interact with the mod. 
## Actual behavior

Logs below 

## Steps to reproduce the issue

unknown
1.  Interact with NPC
2.  The game crashes
3. 

### Logs

The game crashed whilst ticking screen
Error: java.lang.NullPointerException: Ticking screen
Exit Code: -1

https://gist.github.com/ealtrik6/2fc8fed12e0543bdd6e74d674d29bb9b

- latest.log: 
- crashlog: 

https://gist.github.com/ealtrik6/2fc8fed12e0543bdd6e74d674d29bb9b

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
some tool mod is returning a null value, not our fault. Remove tool mods until you find which one and report to them

**Comment by ealtrik6** [comment]
at com.minecolonies.api.colony.requestsystem.requestable.Tool$$Lambda$16443/754267150.apply(Unknown Source) ~[?:?] {}
Does this not imply that mine colonies is pulling said tool?

**Comment by ravenbuilder934** [comment]
it is. But the tool mod can't return a null value (this doesn't happen with vanilla tools)

**Comment by Raycoms** [comment]
This doesn't happen with any properly coded tool.

**Comment by ealtrik6** [comment]
Okay. Well just for reference it seems to only happen with the builder NPC. That's why I thought it could be minecolonies. I will look into it. Thanks.

**Comment by ealtrik6** [comment]
The problem is related to a mod called Colds: Easy Paxel (FORGE).
I will notify them.
