### ISSUE TITLE
[Suggestions] Increase delivery boy stack capacity 

### ISSUE THREAD

**Issue by cheongchan** [ldtteam/minecolonies#698]
### Minecolonies version
1.11- 0.6.3113
Minecraft version 1.11.2

### Expected behavior

- Delivery boy supposed to move stuff somewhat efficiently around town

### Actual behaviour

- Delivery boy goes into huts that have nothing in it and theoretically the stuff the miner, lumberjack and even builder produces greatly exceeds the capacity which fills up their inventory. (even at low levels)

### Suggestions 

1. Unless the citizen hut or deliveryman hut will have stuff in it don't let them go into these places during the day. (I dont think they use it for storage although it might be nice if they do before warehouse is contructed.) [help reduce the number of useless trips]

2. Increase the number of stacks the delivery man can hold at each level. (Dont want them to sit around but dont want them to be useless also so this number may need to be experimented with)

3. When builder or someone needs something, they should send the request immediately and the delivery boy assigned should try to meet them after getting the stuff without both going to the hut. (reduce time loss walking back and forth.)

**Comment by Raycoms** [comment]
1: Will make sense soon, when we add that the citizens need food and he
passes there to deliver food and empty their chests.
2: I think the current rate is quite okay. Deliveryman level 1 is for when
your colony is really just starting, lumberjack and miner shouldn't produce
that much yet.
3: Yeah he will just finish he current delivery/gathering job and directly
will make the delivery.
But someone is already working on improving that point already as well.

2017-03-12 23:25 GMT-03:00 Cheong <notifications@github.com>:
