### ISSUE TITLE
AI issue report

### ISSUE THREAD

**Issue by R3dB3ard90** [ldtteam/minecolonies#6981]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16
- MineColonies Version: 0.14.97-ALPHA-Universal

### Logs

- latest.log: https://gist.github.com/R3dB3ard90/5d0061c0724aec9fdaabc502cfceb1b3

## Steps to reproduce the issue / details

     Trying to upgrade builders hut to level 4. no other notable issues around builder

### Notes
![Screenshot 2021-04-23 123838](https://user-images.githubusercontent.com/83093044/115923403-0b038700-a433-11eb-888c-f1170dd0131e.jpg)

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
fixed in latest 113
