### ISSUE TITLE
Courier AI Issue

### ISSUE THREAD

**Issue by Aduis1210** [ldtteam/minecolonies#6982]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.115 - Alpha

### Logs
- latest.log: https://paste.ee/p/aOnNk

## Steps to reproduce the issue / details

Courier went to cook
Error shown :(

Just reporting the AI issue. 
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Aduis1210** [comment]
Courier is completely frozen - tried restart - non responsive.
Fire and rehire - fixes the issue

**Comment by Raycoms** [comment]
Yes, we're aware of that one, and have an open issue for this already. Can't reproduce it yet though. So If you have a minimum reproducable example, that'd be great

**Comment by Aduis1210** [comment]
Found when the error appears - When the courier makes a delivery to the Cook.

**Comment by Aduis1210** [comment]
> Yes, we're aware of that one, and have an open issue for this already. Can't reproduce it yet though. So If you have a minimum reproducable example, that'd be great

@Raycoms i believe the error relates to when the courier delivers to the cook.
Potential mod conflict?

**Comment by Aduis1210** [comment]
ive noticed twice when the error appears when watching the courier deliver to the cook.

**Comment by vroni92** [comment]
It's upon pickup, not delivery, I think. Managed to reproduce it and going to fix it.
