### ISSUE TITLE
Deliver stop work

### ISSUE THREAD

**Issue by RedAlex** [ldtteam/minecolonies#6983]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5(MineColonies Official mod pack But last alpha MineColonies)
- MineColonies Version: minecolonies-0.14.115-ALPHA-universal

### Logs

- latest.log: https://pastebin.com/8Kjh54Tz

## Steps to reproduce the issue / details

I found the deliver stuck in cook2wood building and he are in build to be a cook3wood

Just reporting the AI issue. 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
duplicate, known, thanks for the report.
