### ISSUE TITLE
Rabbit Herder AI issue

### ISSUE THREAD

**Issue by laurad2423** [ldtteam/minecolonies#6986]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.14.113-ALPHA-universal

### Logs

- latest.log: https://gist.github.com/laurad2423/0d40b3525ba5ef9dd0c4a2cf55b76fc5

## Steps to reproduce the issue / details

 No

Just reporting the AI issue. 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Hmm, this is the same one as #5672 we really have to find out what is causing this
