### ISSUE TITLE
Barrack level 3 tower level 8 guards not wearing iron armors

### ISSUE THREAD

**Issue by LordHellscream** [ldtteam/minecolonies#6988]
### Prerequisites 

- [ x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.14.114-ALPHA-universal.jar
- Structurize Version: 0.13.166-ALPHA
- Related Mods and their Versions:

## Expected behavior
Info:
Asian style Barrack Level 3, 
the specific barrack tower is also at level 3. (there are 2 other barrack towers at level 2, no guards were hired in those)
2 Guards (knights) both showing as Worker level 8. 
Iron armor sets (non-enchanted) and shields are available in storage, recipe are also available on request at Blacksmith (level 3)
Expecting them to wear iron armor/shield

## Steps to reproduce the issue

1. Asian style Barrack level 3, 1 tower at level 3, 2 other towers at level 2 
2. Hire 2 guard, level 8 preferrablly
3. give them iron armor to see if they wear it

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
What armor are they wearing instead (if any)?

**Comment by LordHellscream** [comment]
I havent seen this issue in the last couple of updates, closing for now

**Comment by NachoLibre998** [comment]
I am also having this issue wont put on any armor at all

**Comment by MotionlessTrain** [comment]
As this is a very old issue, you are more likely to have run into a new issue. Could you please open a new issue instead?
