### ISSUE TITLE
Vanilla Fuel Not Showing In Restaurant

### ISSUE THREAD

**Issue by BlackWarrior2004** [ldtteam/minecolonies#6989]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.16.5
- MineColonies Version:minecolonies-0.14.115-ALPHA-universal
- Structurize Version:structurize-0.13.166-ALPHA-universal
- Related Mods and their Versions:betteranimalsplus-1.16.4-10.1.0

## Expected behavior

The restaurant to accept any fuel source from vanilla like coal.(other mods not sure)
## Actual behavior

The restaurant does not allow any vanilla fuel source to choose from. It 

## Steps to reproduce the issue

1. Install Better Animals Plus Mod(https://www.curseforge.com/minecraft/mc-mods/betteranimalsplus)
2. Go to restaurant to select fuel
3. Then no vanilla fuel is there

### Logs

- latest.log: https://gist.github.com/BlackWarrior2004/bdde97436869818fd7e39cc4226f5d6a
- crashlog: 

### Notes

Pls help anyone this happens after I update the minecolonies from 0.14.110-ALPHA-universal(previously it was working)
And I play this at Aternos server. And I am the owner of the server
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by BlackWarrior2004** [comment]
I also forgot to mention that when ever the Cook is requesting food from warehouse, the courier man ai corrupts and it tells to give the log and inform u guyz

**Comment by Raycoms** [comment]
This throws an exception:
[24Apr2021 14:02:07.944] [Worker-Main-4/ERROR] [net.minecraft.item.crafting.RecipeManager/]: Parsing error loading recipe pamhc2foodextended:peachesandcreamoatmealitem

Which crashes the loading code, please report to them.

**Comment by BlackWarrior2004** [comment]
> This throws an exception:
> [24Apr2021 14:02:07.944] [Worker-Main-4/ERROR] [net.minecraft.item.crafting.RecipeManager/]: Parsing error loading recipe pamhc2foodextended:peachesandcreamoatmealitem
> 
> Which crashes the loading code, please report to them.

Hey! Just wanted to know that whether Pam`s Harvest 2 and Better Animals Plus are compatible or not with Minecolonies. Pls tell

**Comment by uecasm** [comment]
If they fix their bugs, they should be.  Until then, they're not compatible with anything.
