### ISSUE TITLE
[Feature] Townhall Leveling

### ISSUE THREAD

**Issue by cheongchan** [ldtteam/minecolonies#699]
### Minecolonies version

version 0.6.3113

### Expected behavior

- Townhall upgrades should enable something useful

### Actual behaviour

- I build townhall level 1 and dont touch it. (this even uses lots of resources so i delay building it)

Suggestions:
1. Maybe with increase of level there is an increase in effective radius around the townhall you can build? And/Or allow construction of new huts as town grows) Or even cap max population.

2. Reduce the level 1 townhall size/resource usage. 

3? Get rid of townhall completely until more complicated gameplay is implemented and have a smaller marker/market place designate town center?

**Comment by marchermans** [comment]
The future request system will introduce usefullness into the Townhall, from level 1 and upwarts on

**Comment by rscott6666** [comment]
Is there a document of the roadmap for minecolonies?  That i can see?

**Comment by Raycoms** [comment]
@pmardle I think it would be nice to have that =D

**Comment by Raycoms** [comment]
We have some writeups on the forums in the patreons section and some in basecamp.

**Comment by pmardle** [comment]
Nothing that ties everything together.. we have a lot of random info on future stuff dotted about..

Guess it makes sense to combine it all into one "master" vision or something..

Where/how is best to present this though.. I don't think it should be a totally public document, but perhaps something the Patreons can view would be nice.

**Comment by Raycoms** [comment]
I think the master version should be on basecamp.
With like branches pointing out what comes after what and what the
priorities of the things are.
You could make a base version and we could discuss the details or changes
on slack.
Changes/Additions.

2017-03-13 14:53 GMT-03:00 pmardle <notifications@github.com>:

**Comment by cheongchan** [comment]
Before adding the too much complexity it might be better to get in enough features to make it a viable beta. Getting the npcs to craft I feel is very important. Let interactions with multiple colonies be an expansion after the town works well and the mod relatively bug free

**Comment by Raycoms** [comment]
That's the plan. Atm we're fixing up things, improving what is there and
working on the crafting system.

2017-03-13 15:22 GMT-03:00 Cheong Chan <notifications@github.com>:

**Comment by cheongchan** [comment]
I would like to help but I suck at programming (out of practice.) I only started playing Minecraft less than a month ago. Can you point me to some tutorials for tools to create blocks/building model that mine colonies could use? Or how the process works?

**Comment by Raycoms** [comment]
Actually everyone who knows java can participate.
Minecraft is just a "library".
You could search bugs or crashes etc and search in the code where things are happening and add to that.

**Comment by xavierh** [comment]
What about changing the builder's hut and Fisherman hut item, they look really out of place

**Comment by Raycoms** [comment]
The problem are the other items. The plan is to have all the items to be
"special" but our modeler guy went MIA.

2017-03-16 15:35 GMT-03:00 xavierh <notifications@github.com>:

**Comment by WORMSS** [comment]
I like the idea of town hall being the Cap in population.
So it being placed spawns the original 4, but until the building itself is finished, you cannot get a 5th (or higher).
I don't know what would be sane numbers for each level though.
