### ISSUE TITLE
Guards get stuck in fortress barracks and all get sick and can't find their way to a doctor.

### ISSUE THREAD

**Issue by laurad2423** [ldtteam/minecolonies#6991]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.16.5
- MineColonies Version:.14.115
- Structurize Version:13.166
- Related Mods and their Versions:

## Expected behavior

I would expect the guards to make their way to the healer when they are sick

## Actual behavior

They instead bunch up and all huddle together around the ladder to get out and stay stuck there indefinitely
Image to show: https://discord.com/channels/139070364159311872/741531816422539384/835584974668693574

https://discord.com/channels/139070364159311872/741531816422539384/835584974668693574
## Steps to reproduce the issue

1.  I don't know how to reproduce it, it's happen 2 times to me today since I upgraded to the 115 version.
2. 
3. 

### Logs

- latest.log: 
- https://gist.github.com/laurad2423/926cb7e1847d5065b1fdc11d37643bb0
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by laurad2423** [comment]
I figured out a workaround. I broke the wall where they were gathering and they figured out how to climb up on their own again

**Comment by pete-koning** [comment]
i had exactly the same issue. The guards all infected each other and then bunched up and couldn't figure a path to the healer. I left them huddled up and while I was making my way to check on the healer in the hospital they passed me, one after another and got healed on their own. 

I know this doesn't help you any, but it did seem to self-resolve.

**Comment by Raycoms** [comment]
okay I checked this and it's a #5006, I told aravan already
