### ISSUE TITLE
Using creative to paste in a structure causes minecraft to crash

### ISSUE THREAD

**Issue by dupontct** [ldtteam/minecolonies#6992]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.14.117-ALPHA-universal
- Structurize Version: structurize-0.13.166-ALPHA-universal
- Related Mods and their Versions:

## Expected behavior
When I use the creative paste option when placing a the decorations/fortress->kelpfarm that the structure is placed in full and not crash minecraft.

## Actual behavior

When I use the creative paste option using the decorations decoration/fortress->kelpfarm the minecraft crashes.  When I reenter the world the kelp farm is only partially placed.  This also happens with the double kelp farm but less of the total structure is there when reentering the world.

Interestingly a smaller structure like the decoration bigwell will paste in just fine.

Here is a picture of the incomplete placement of the double kelp farm after returning from the crash.

![2021-04-24_13 29 12](https://user-images.githubusercontent.com/29468/115969202-71ef7180-a501-11eb-87a0-facc1f9a007f.png)

So far I have tested decorations decorations/fortress->kelpfarm, decorations/fortress->kelpfarmcombo, decorations/fortress->kelpfarmdual, and decorations/fortress->kelpsmoked and pasting them causes the crash.

## Steps to reproduce the issue

1. Enter the creative game mode.
2. right click on the ground using the build tool.
3. select the Decorations->decorations/fortress->kelpfarm structure
4. Press the paste button in the build tool GUI
5. Minecraft crashes

### Logs

- latest.log and crashlog: https://gist.github.com/dupontct/2ed38b825ec42fbeb77cdaa9cda54b09

### Notes

I did some checking and the last version of Minecolonies where you can paste in the decorations/fortress->kelpfarm is 0.14.110-ALPHA.  From 0.14.112-ALPHA onward it will crash when attempting to paste in the structure.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by anakhasilver** [comment]
Can confirm, this happens with specific structures. Some will work, but like. Barracks? Specific citizen houes? Guard towers?
