### ISSUE TITLE
No Tavern building available

### ISSUE THREAD

**Issue by KnightCa** [ldtteam/minecolonies#6993]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.12.2
- MineColonies Version: minecolonies-1.12.2-0.11.841-ALPHA-universal
- Structurize Version: structurize-1.12.2-0.10.277-RELEASE
- Related Mods and their Versions: None

## Expected behavior
I expect the Tavern to be a building to create from the Wiki recipe (https://wiki.minecolonies.ldtteam.com/source/buildings/tavern) or the Tavern building to be available in Creative.

## Actual behavior
I can't seem to find the Tavern block in-game or be able to craft it.

## Steps to reproduce the issue
1. Go to a crafting table and try to make the Tavern with the recipe from the wiki. No luck.
2. Turn on creative and try to find the Tavern block in the menus by searching for Tavern. No luck.

### Logs
No logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
1.12 is not supported. All doc is for 1.16+
