### ISSUE TITLE
Colonists go to the restaurant but freeze instead of being fed

### ISSUE THREAD

**Issue by al-par** [ldtteam/minecolonies#6995]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.14.114-ALPHA-universal
- Structurize Version: structurize-0.13.166-ALPHA-universal
- Related Mods and their Versions: Valhesia 3 3.3.0

## Expected behavior

Citizens should go to the restaurant and get fed by the cook, then return to their tasks.

## Actual behavior

Citizens go to the restaurant and completely freeze. The cook does not feed them anything. Manually feeding citizens by placing food in their inventory does not fix the issue. Affected citizens will just stand in the restaurant near the restaurant block, completely frozen. Sometimes, affected citizens cannot be interacted with at all.
![image](https://user-images.githubusercontent.com/47093296/115991570-238cb200-a597-11eb-9fcc-35340cc83ce0.png)

## Steps to reproduce the issue

1.  Build a restaurant.
2.  Hire a cook and provide them with food and fuel (and cooking recipes).
3.  Wait for citizens to get hungry and go to the restaurant.
4. Observe citizens not getting fed and freezing.
5. ~~Profit~~   Loss
### Logs

- latest.log:  https://gist.github.com/JonTronsLongJon/90c69a1e3d703b035aa7391e0d9b39a5

### Notes

This issue is present in multiplayer, but I have not tested it in singleplayer.

Reloading the affected citizens using commands does not fix them. Reloading the cook does not fix them. Moving the restaurant does not fix the issue. Building a new restaurant does not fix the issue. The issue is present for all levels of restaurants, and has been tested with multiple different building styles. This issue is present with multiple cooks, and is not caused by cooks being hungry, and is present regardless of if the cook has food to distribute or not.

The only way I have been able to fix the affected citizens is by firing the citizens after having added food to their inventory. Once they have eaten, they can be rehired and will resume their tasks. This is manageable with smaller colonies, but becomes a constant struggle with more citizens.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by vroni92** [comment]
Please try updating, there's just been a fix to the cook, maybe this fixes it. If not, please report back.

**Comment by al-par** [comment]
Incredible. I updated about 45 minutes before the fix :p. Thank you, the issue is resolved.
