### ISSUE TITLE
Knights-in-training do not go to sleep, and visually retain their gear after being hired elsewhere

### ISSUE THREAD

**Issue by GrumpyPirate** [ldtteam/minecolonies#6996]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.115-ALPHA
- Structurize Version: 0.13.166-ALPHA
- Related Mods and their Versions:

## Expected behavior

- Knights--in-training getting assigned beds in the Combat Academy, and going to sleep like regular citizens in the building beds
- After training in the Combat Academy, subsequently being hired for other jobs (Builder, Courier etc.) would remove/reset their equipped gear, particularly their shield
- After training at the Combat Academy and being hired elsewhere, citizens would automatically be assigned spare slots in regular housing

## Actual behavior

**Example of knights-in-training not sleeping**
![2021-04-25_13 22 20](https://user-images.githubusercontent.com/6855824/115993620-85670f00-a5cb-11eb-8f95-71469166838f.png)

**Example of a couple of ex-Knights-turned-Librarians retaining their Shields visually, and returning to the Combat Academy as their 'home'**
![2021-04-25_13 42 56](https://user-images.githubusercontent.com/6855824/115994040-518ce900-a5cd-11eb-8bc8-03953f87f23f.png)

## Steps to reproduce the issue

1. Build a Combat Academy
2. Hire some workers there
3. Wait until night, when all other workers head to their beds
4. Observe how Knights huddle around the building block and do not sleep in their respective beds
5. Reassign those workers to other jobs, e.g. Builder
6. Notice that they retain their shields

### Logs

- latest.log: https://gist.github.com/GrumpyPirate/9fb2e33feca27af9be6dceac36c78f04

### Notes
I believe the not-sleeping issue was actually fixed a few versions ago, with our assigned Knights successfully going to bed using the beds inside the corresponding Academy/Archery buildings, but seems to have been reverted at some point in a recent version and is once again prevalent in 0.14.115-ALPHA affecting the Combat Academy. The closed issue was https://github.com/ldtteam/minecolonies/issues/6512.

We recently unlocked the worker work hours+ research so all our workers work until around 20:30 now, and were wondering if this might have something to do with it.

I should also note that the Archery and hired Archers _don't_ suffer from the insomnia issue.

We're playing through the mod as part of the Valhelsia 3 modpack, whose maintainers do a good job of keeping MineColonies (and Structurize) up-to-date.

I'd also like to mention that we understand the mod is a complex beast, and while we've had a few issues, we're having a wonderful time with MineColonies and have gotten rather attached to our city. We've ended up mostly ignoring 95% of our modpack. 😂 

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Can you show us the beds in the academy?

**Comment by GrumpyPirate** [comment]
Absolutely - here:
![2021-04-25_14 48 21](https://user-images.githubusercontent.com/6855824/115995979-6bcac500-a5d5-11eb-8a2b-5366e725461a.png)

It's the Caledonia building.

**Comment by GrumpyPirate** [comment]
An update on this - I've just ordered a builder to deconstruct and reconstruct the building altogether, and have rehired a worker, and it appears to have fixed the sleeping issue.

**Comment by ravenbuilder934** [comment]
Sleeping issue seems to have been fixed then, and the librarians returning to the academy is #6471
