### ISSUE TITLE
[Suggestion] Biome dependent architecture

### ISSUE THREAD

**Issue by cheongchan** [ldtteam/minecolonies#700]
### Minecolonies version

1.11-0.6.3113

### Expected behavior

- Build buildings out of most abundant resources locally

### Actual behaviour

- build everything out of oak and then other materials (potentially not found in same biome). Makes gameplay/leveling harder unless you end up in the right place at the beginning.

Solution:
Make buildings all out of the same wood (biome dependent on where center of town established) regardless of the level. Although in desert and mesa biome it may be better to allow buildings to be made of clay or sandstone. (no lumberjack but some other job stonemasons?)

I think this would be a really neat thing to have that would expand the geographies the colony can be established in and variation in buildings.

- In the far future maybe create biome dependent products/huts to make colonies trade with each other to get critical goods (for leveling up possibly)?

-- far far future integrate with traincraft or some other mod with vehicles to connect town/cities.

I know the intent is for motivate people to travel but without a list of what I need for the upgrades it becomes a huge chore to go and get saplings and then establish a forest of the required trees next to the town. (That also feels very unnatural)

This is probably gonna be left open for a while. Focus on making the town a closed system by adding the necessary jobs first i think.

**Comment by Raycoms** [comment]
Actually for this we depend on our colony.
You want a biome depending building like sandstone in the dessert or dark oak in the forest?
Create a schematic style pack and upload it to the forums. We will test it and might add it.
You will then be able to choose the biome depending buildings from the building menue.
