### ISSUE TITLE
Fortress alt university 

### ISSUE THREAD

**Issue by Rolo318** [ldtteam/minecolonies#7005]
Seems the fortress alt university upgrades are out of order. Lvl 1 shows correctly but then lvl 2 shows as lvl 5 and lvl 3 shows as lvl 4 and so on.

**Comment by Xowie89** [comment]
Level 5 should be the big observatory but it doesn't even show up anymore unless the final build was changed

**Comment by ravenbuilder934** [comment]
I would tell you to post on #5006, but a fix is already in review (#6999)
