### ISSUE TITLE
Screenshot of Caledonia

### ISSUE THREAD

**Issue by desagas** [ldtteam/minecolonies#7007]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5.36.1.2
- MineColonies Version: minecolonies-0.14.123-ALPHA-universal.jar
- Structurize Version: 166 ALPHA

## Problem description

I don't know where else to post this for you, as there is no discussion here on on curse. I have a screenshot of the Caledonia setup, if you want to use it wherever for whatever, like curse or whatever.

https://imgur.com/gallery/CKP7xIu

![2021-04-25_19 07 19](https://user-images.githubusercontent.com/8404632/116017558-2de19700-a5fd-11eb-8fa2-bcb605be7c96.png)

### Notes or related things

Sorry for wasting an issue number.

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
On our discord would probably be the best place :joy:
