### ISSUE TITLE
Dark Oak University lvl 5 upgrade - wrong building rotation

### ISSUE THREAD

**Issue by al-par** [ldtteam/minecolonies#7008]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.14.118-BETA-universal
- Structurize Version: structurize-0.13.166-ALPHA-universal
- Related Mods and their Versions: Valhesia 3 3.3.0

## Expected behavior

Builder should build the Dark Oak University lvl 5 upgrade on the same footprint as the lvl 4 university.

## Actual behavior

The builder builds the lvl 5 upgrade, but does not preserve the rotation of the university. In this case, the university was rotate 180 degrees.

![image](https://user-images.githubusercontent.com/47093296/116019413-27114f00-a612-11eb-9b33-2dd5c0fc7a58.png)

## Steps to reproduce the issue

1. Have a level 4 Dark Oak University.
2. Create a build order for the lvl 5 upgrade for the Dark Oak University.
3. Assign a builder to the build order.
4. Watch them build the university with the wrong rotation.

### Logs

- latest.log:  https://gist.github.com/JonTronsLongJon/5f24e0fb4a23e71bc89f846eae6512ba
- crashlog: 

### Notes

Cancelling and re-creating the build order leads to the same issue. I have not restarted the server yet to see if this fixes the issue (I assume it will), but I have noticed many other issues with buildings in general with the new update. Previews sometimes do not preserve rotation, and I've had an issue with the dark oak stonecutter where  the block could not detect the building (restart fixed the issue). Most issues seem to be fixable with a restart, but this gets very tiresome for players on my server.

-P.S.: thanks for fixing the restaurant bug!

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
#5006
