### ISSUE TITLE
[Suggestion] Garrison/Villager Capabilities

### ISSUE THREAD

**Issue by cheongchan** [ldtteam/minecolonies#701]
### Expected behavior

- As towns get bigger maybe enable a building that allows increasing fighters would be good. (i kinda want to play on harder levels and see how they fight off enemies)

### Actual behaviour

- No garrison only guardsman and 1 per tower.

Solution
-create new hut to enable recruiting more people to fight.
-also it would be cool if villagers had basic defense capabilities/increasing work schedules. (or some kind of evolution that allows more of the day to be used for work rather than npc going in at sundown)

- far future (maybe a block [or hut ; )] that spawns NPC barbarian hordes (like in Civilization) that attack as the town grows to keep it challenging)

**Comment by Raycoms** [comment]
Definitively planned.

**Comment by Raycoms** [comment]
That has been implemented now already =D
