### ISSUE TITLE
AI Log 1.16.5

### ISSUE THREAD

**Issue by triffman33** [ldtteam/minecolonies#7011]
- [ ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.14.117-ALPHA-universal.jar

### Logs

- latest.log: 
https://pastebin.com/1Xfj6PAp - around line 2117
## Steps to reproduce the issue / details

Just reporting the AI issue. 

### Notes

![image](https://user-images.githubusercontent.com/31788797/116084147-5f0da600-a695-11eb-9481-4ab4c28d6533.png)

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Fixed in latest
