### ISSUE TITLE
Restaurant Not Accepting Fuel

### ISSUE THREAD

**Issue by BlackWarrior2004** [ldtteam/minecolonies#7013]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.16.5
- MineColonies Version:0.14.123-ALPHA-universal
- Structurize Version:0.13.166
- Related Mods and their Versions:

## Expected behavior

The Restaurant to accept vanilla fuel sources in their gui.
## Actual behavior

The restaurant does not show any vanilla fuel source. It only shows other mod`s fuel sources if they have any. I have removed the mods which had those fuel soures then the fuel list in the gui is blank.

![list](https://user-images.githubusercontent.com/83131147/116100856-f2ad9980-a6ca-11eb-9abb-ec6fa22a061b.png)
My mods list
## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

I asked for it at Discord at mod discussion part. One of them told me to install and try FastWorkBench. I tried it but it did not work out. Pls help I m new to this mod.
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Can you test with just minecolonies and structurize?

**Comment by BlackWarrior2004** [comment]
> Can you test with just minecolonies and structurize?

OK

**Comment by BlackWarrior2004** [comment]
> Can you test with just minecolonies and structurize?

I tested it and the fuel list shows up!

**Comment by ravenbuilder934** [comment]
okay great! I'll close this then since it's not our fault. You can remove mods one-by-one to determine which one is causing this
