### ISSUE TITLE
Delivery Man - Log 

### ISSUE THREAD

**Issue by Eugen3006** [ldtteam/minecolonies#7015]
- [ x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

- Minecraft Version:1.16.5
- MineColonies Version:minecolonies-0.14.118-BETA-universal

### Logs
- latest.log: [latest.log](https://github.com/ldtteam/minecolonies/files/6378761/latest.log)

Just reporting the AI issue. 

### Notes
The Delivery Man Stay in this moment on the Kitchen ( restaurant )

---

**Comment by Eugen3006** [comment]
Sry My English ist bad xD

**Comment by Eugen3006** [comment]
Restart help the Delivery go to works

**Comment by ravenbuilder934** [comment]
Update to the latest alpha, several AI issues were fixed

**Comment by Eugen3006** [comment]
oh ok i dont see this . sry
