### ISSUE TITLE
Builder is building wrong version of decorations

### ISSUE THREAD

**Issue by Twilight798** [ldtteam/minecolonies#7016]
### Prerequisites 

- [ I am running minecolonies-0.14.40-BETA-universal.jar] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [ I have made sure there are no similar inquiries of this issue. ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.14.40-BETA-universal.jar

### Logs

- latest.log:  I don't how to to use the https://gist.github.com so I will just add it. 

## Steps to reproduce the issue / details

 have builder of any level try to build an asian fancy gate version 2 that uses the red concrete. It instead only built the fancy gate version 1 that uses oak wood.

Just reporting the AI issue. 

### Notes
It instead only built the fancy gate version 1 that uses oak wood.
It also happens when I try to use the builder to create any other versions of the decorations like the asian bridges. It seems to auto select the version 1 instead of any of the other versions. I am using other mods by the way. It is only the towns and kingdoms mod for 1.16.5 from the technic platform.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
Are they upgradeable decorations?
They build the same way as other buildings, build level 1, then upgrade to level 2

**Comment by ravenbuilder934** [comment]
Yeah, this is intentional. You need to find the decoration controller block to upgrade 'em
