### ISSUE TITLE
Hard Crash: TickingTransition Exception

### ISSUE THREAD

**Issue by desagas** [ldtteam/minecolonies#7019]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5.36.1.2
- MineColonies Version: 128-alpha
- Structurize Version: 167-alpha
- Related Mods and their Versions: ATM6 1.6.2

## Actual behavior

Minutes after my carpenter reduced his need for oak planks to craft oak 2x2 drawers, my game crashed. The attached latest.log is cut to only the end, as the error before the crash repeated a few hundred times, with the exact same @id, until it fully crashed, resulting in a server shut down.

## Steps to reproduce the issue

1.  Unknown
2.  My carpenter was working on oak drawers 2x2, and my cook and her assistant we working on ChiliDogs and and all the ingredients to make them from Pams, using BBQ Sauce. Otherwise, I am unaware of what else was happening, as I was building elsewhere.
3.  Unknown

### Logs

- latest.log:  https://gist.github.com/desagas/acd6943bfff4441d5e97d51c6765d5b5
- crashlog:  https://gist.github.com/desagas/7001a56fb7086746a06679d9d9a9a853

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Did you recently remove a mod, or did a mod recently remove an item or so?

**Comment by desagas** [comment]
In the scheme of recent, I updated ATM6 two days prior, but, I had logged around 24 hours (hardcore) since updating without any errors. The only thing I updated was minecolonies 2 hours prior. I did run around and double check that each hut had their respective recipes correct, incase any changes happened. Also, once restarting the pack, I did not get that crash in the 10 hours of game play since. However, the carpenter no any other hut has improved their recipes for any modded items, if its related, so, ill keep an eye out.

**Comment by desagas** [comment]
It happened again, I am unsure if the log is different. As for adding or removing anything, no, and I had been playing for 6 plus house since updating to 133-alpha, no other mods were changed or added. 

CrashLog: https://gist.github.com/desagas/06917da78f3ca38eed9d1ad39f3a6803

The cook was the only one doing anything outside of vanilla this time.

**Comment by desagas** [comment]
Possibly Related: if the smelter were to take something out of the furnaces in his hut that I was smelting, would this cause such a crash, if they were not part of his recipes? During the nights I cook glass in there as they are the most accessible.

**Comment by Raycoms** [comment]
fixed
