### ISSUE TITLE
Bakers have missing baking particles

### ISSUE THREAD

**Issue by chandler05** [ldtteam/minecolonies#7025]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.131-ALPHA
- Structurize Version: 0.13.167-ALPHA
- Related Mods and their Versions:

## Expected behavior

Particles show up correctly while the baker bakes
## Actual behavior

The baker uses wheat on the bakery, but missing particles show up

## Steps to reproduce the issue

1.  Have a baker start baking
2.  Watch the particles
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Do you have a screenshot or video? Anything related in the logs?

**Comment by chandler05** [comment]
Oh wait a second, I know what causes this
I'll do a PR in a sec
