### ISSUE TITLE
AI cause server crash

### ISSUE THREAD

**Issue by lordfriend** [ldtteam/minecolonies#7028]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.118-BETA

### Logs

- latest.log: 
- https://gist.github.com/lordfriend/c9b02e63b576dad441d545c89cd1eac0
- Crash log
https://gist.github.com/lordfriend/485e4deb020145f420f27ed4c51c1934

## Steps to reproduce the issue / details

Transient Issue.

Just reporting the AI issue. 

### Notes

I just update the mod from the 0.14.107-BETA-universal. I played in the game for several in-game days. then when I walking to the warehouse, the server suddenly crashed. But I guess there is nothing to do with my action. if you need mod pack or server world save. I will provide it later.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Not Minecolonies
