### ISSUE TITLE
server crash - The given output type is not a output of a factory

### ISSUE THREAD

**Issue by piesio98** [ldtteam/minecolonies#7030]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5 forge 36.1.4
- MineColonies Version: 0.14.133-ALPHA
- Structurize Version: 0.13.169-ALPHA

## Problem description

while not doing anything, by me or friend (just standing at colony), server occasionally (2-3 times a day) crashes, because of 
"Exception in server tick loop"
and
"Condition check for transition com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickingTransition@55810b03 threw an exception: java.lang.IllegalArgumentException: The given output type is not a output of a factory"

### Notes or related things

Crash-log nad server log:
https://gist.github.com/piesio98/9c70839b929e968852ae29171e49a0b3

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
fixed
