### ISSUE TITLE
Builder Requests for blocks/items not working properly

### ISSUE THREAD

**Issue by smmmadden** [ldtteam/minecolonies#7033]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 36.1.12
- MineColonies Version: 0.14.134-ALPHA
- Structurize Version: 0.13.169-ALPHA
- Related Mods and their Versions:

## Expected behavior

Builder requests should ask for all blocks that they can fit in their inventory the first time. 
## Actual behavior

Not sure when the mechanics changes (maybe in the 120's), but builders have a ?and gear over their heads and prompt for a non-standard UI popup.  Then after 5-30 seconds of thinking or walking back and forth in the hut, the turn and ask for more blocks/items.  Not ideal as I'm expecting to provide the items and walk away, but am forced to wait it out hoping they can get what they need up front.

Sequence of screens:
![image](https://user-images.githubusercontent.com/10309346/116499368-051a0580-a87a-11eb-83d8-32db799912e5.png)
![image](https://user-images.githubusercontent.com/10309346/116499383-0d724080-a87a-11eb-91ac-548585acd89e.png)
![image](https://user-images.githubusercontent.com/10309346/116499396-1400b800-a87a-11eb-8401-ae08c6f90b8b.png)
![image](https://user-images.githubusercontent.com/10309346/116499412-1b27c600-a87a-11eb-95eb-3748bf90667b.png)
![image](https://user-images.githubusercontent.com/10309346/116499425-20851080-a87a-11eb-8789-711339534a2a.png)
The last one varies from 1 additional item or a full page of them.

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
The full list is in the building on page 2?

**Comment by Raycoms** [comment]
Those requests you're seeing are still in the process of being processed by the request system (if they can be fulfilled or not) so they don't directly enter all at once. You give them a little bit of time and you'll see all of them together. Else, you can just fulfill the general item needs on the hut page 2.
