### ISSUE TITLE
Crash java.lang.IllegalArgumentException: The given output type is not a output of a factory

### ISSUE THREAD

**Issue by MeikelLP** [ldtteam/minecolonies#7034]
### Prerequisites

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.133-ALPHA
- Structurize Version: 0.13.167-ALPHA
- Related Mods and their Versions: https://github.com/ValhelsiaTeam/Valhelsia/releases/tag/3.3.0

## Expected behavior
* Do not crash

## Actual behavior
* It crashes

## Steps to reproduce the issue

_Unknown_

### Logs

- latest.log: https://gist.github.com/MeikelLP/5e0df12f7e1f0a80f56fc8e1daba13fc
- crashlog: https://gist.github.com/MeikelLP/58bb3fc680a2279ca96f1a91788329c9

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Fixed in latest
