### ISSUE TITLE
courtmier ai error

### ISSUE THREAD

**Issue by Numari99** [ldtteam/minecolonies#7035]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 
[latest.log](https://github.com/ldtteam/minecolonies/files/6398452/latest.log)

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.118-BETA-universal.jar

### Logs

- latest.log: 

## Steps to reproduce the issue / details

Just reporting the AI issue. 

### Notes
[>](url)

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
fixed in latest
