### ISSUE TITLE
Beekeeper eating honey bottle also eats the bottle itself.

### ISSUE THREAD

**Issue by bcmpinc** [ldtteam/minecolonies#7038]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.14.97-ALPHA-universal.jar
- Structurize Version: structurize-0.13.163-ALPHA-universal.jar
- Related Mods and their Versions: FTB Direwolf20 1.16 modpack version 1.9.0

## Expected behavior
When the colonist eats a honey bottle, an empty bottle will be left in their inventory.

## Actual behavior
When the colonist eats a honey bottle it eats both the honey and the bottle.

## Steps to reproduce the issue

1. Give a colonist some honey bottles (and only that).
2. Wait till they get hungry and eat the honey bottle.
3. Check their inventory to see whether a bottle was left behind.

### Logs

- latest.log: 
- crashlog: 

### Notes
I noticed this issue on a beekeeper (as they eat the honey they harvest). 

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Can you try updating?

**Comment by bcmpinc** [comment]
Tested it with the latest version. This one has the same issue.
MineColonies Version: minecolonies-0.14.134-ALPHA-universal
Structurize Version: structurize-0.13.169-ALPHA-universal

**Comment by Jinotad** [comment]
Just watched this happen with the BeeKeeper on Cave Colonies.  Beekeeper started eating the honey bottles, and didn't get the bottles back.

No bottle returning when honey is consumed.
Bee Keeper shouldn't be allowed to eat the honey.  The entire point is that they should be collecting honey for the colony. Eating it significantly slows down the collection.

minecolonies-1.20.1-1.1.517-BETA.jar
