### ISSUE TITLE
Clicking "Place Anyways" Removes Stored Hut Level.

### ISSUE THREAD

**Issue by desagas** [ldtteam/minecolonies#7039]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5.36.1.2
- MineColonies Version: minecolonies-0.14.134-ALPHA-universal.jar
- Structurize Version: 169-Alpha
- Related Mods and their Versions: ATM6 1.6.2

## Expected behavior

When placing a deconstructed hut back into the world, it would keep its hut level.

## Actual behavior

When clicking to place deconstructed hut back into world, without the wand, the hut loses its level. The pop up tells you that you might want to use the tool so you can reposition it, but it does not tell you that it will lose its level.

This happened with the farm hut, I am not sure if it happens with any other hut.

## Steps to reproduce the issue

1.  Deconstruct level 5 hut.
2.  Right click to place hut, click on "place anyways."
3.  Look in GUI to see hut level lost.

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Why aren't you using the wand?

**Comment by desagas** [comment]
At first, I had four farms, and I knew that each one was going to be placed at the exact place I had planned (modular), so, it would save a step each time I placed them. This was the primary purpose. (The image below shows three Caledonia farms directly across from a Caledonia Alternative farm).

Then, secondly,

I was trying to get the level 5 (picked up) hut block to recognize the racks without building the entire building, which I now know the huts will not do, even if they are in the right location, without being completed by a builder. Yet, when a builder or myself deconstructs a building, the hut block still recognizes and scans the location of the original racks (if not picked up), which means that you can deconstruct or tear down yourself, a building, and build an entire new structure around it, and still use the provided racks if they are still in the same location.

The nordic farmers hut has 28 racks for storage, while the Caledonia only has 3, and the Caledonia alternative has 4. I adore the Caledonia Alternative farm, but love the storage of the nordic, so, I was going to move 4 additional farmer huts into the Alternative field structures (1 farmer/hut per original field, as I have accelerated crop growth in the area), and then place the racks outside the fields, in the same locations as the nordic storage. This would allow each hut to still have 3 or four racks.

You can see the images below, the first shows how the hut would be placed, but, I don't want to build the entire nordic building, and then the second image shows what each Alternative field structure would look like with the new storage from the Nordic.

Long and complex story, but, I found a way around it. I have to build each nordic buildings, and then tear them down, leaving the hut in place, and then rebuild by hand the old field structures. There is no way around it that I know of.

![2021-04-29_14 13 55](https://user-images.githubusercontent.com/8404632/116613699-3f28ed00-a8f6-11eb-82b2-28b70ce67779.png)
![2021-04-29_14 14 28](https://user-images.githubusercontent.com/8404632/116613719-44863780-a8f6-11eb-85fd-68645f015025.png)

**Comment by Raycoms** [comment]
The thing is, if you place it without the buildtool, we don't know which style you want to place. But we can adjust it so it uses the level at least so you can "pick it back up" then again

**Comment by desagas** [comment]
And that is what I expected to happen, absolutely. Or, at least an extended message that says "level will be lost," or something like that. Not too big or a deal, as I learned my lesson fast.
