### ISSUE TITLE
Colony members fight to see who can go thru the door first

### ISSUE THREAD

**Issue by rexrapter1234** [ldtteam/minecolonies#704]
### Minecolonies version

version 1.10.2 or curse X.X.XX

### Expected behavior

Colony members take it in turn to go throw a door.

- XXX

### Actual behaviour

Colony members fight to see who can go thru the door first and just end up opening and closing the door again, again and so on .....

- YYY

### Steps to reproduce the problem

This bug had when two or more Colony members use the same house to sleep and then when day come, they both tray to leave the house at the same time. add a back door to the buildings if they need them.

1. XYZ
2. ZYX
3. ...
4. Profit

http://i243.photobucket.com/albums/ff156/rexrapter1234/2017-03-12_15.35.16_zpssyltofj8.jpg

**Comment by cheongchan** [comment]
Merge with #696 as maybe a general issue with pathfinding through doors? It is different version so root cause could be different, but I suspect probably the same.

**Comment by Raycoms** [comment]
yeah same issue. But its actually a minecraft pathfinding issue. Already saw zombies, sheeps, villagers doing this.
But yeah its a duplicate.
