### ISSUE TITLE
Structurize Version Problem

### ISSUE THREAD

**Issue by AquaFer1** [ldtteam/minecolonies#7041]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context  I am playing on 1.16.5 Forge i am using Minecolonies 0.13.437-Release and i am trying to use Structurize  0.13.96-ALPHA but every time i try to play it says i need a newer version of alpha, but when i change it to a newer version of alpha it says i need 0.13.96.

- Minecraft Version:
- MineColonies Version:
- Structurize Version:
- Related Mods and their Versions:

## Expected behavior
 It letting me past the loading screen to the main menu

## Actual behavior
 It loads up minecraft but it gives me a error message saying a error has occured during loading

## Steps to reproduce the issue

1.  Update it so it can be used on the newest version of ALPHA

### Logs

- latest.log:  
- crashlog:  https://gist.github.com/AquaFer1/97b92d5459e113d80ca78e95453d7f86

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
use the latest alphas of both minecolonies and structurize
