### ISSUE TITLE
Config option "generatesupplyloot" does nothing

### ISSUE THREAD

**Issue by Archi9** [ldtteam/minecolonies#7043]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5 Forge 36.1.4
- MineColonies Version: minecolonies-0.14.134-ALPHA-universal
- Structurize Version: structurize-0.13.169-ALPHA-universal
- Related Mods and their Versions: none

## Expected behavior

When set serverconfig "generatesupplyloot" to false, i expect "Supply chest - free" isn't in dungeon loot.

## Actual behavior

Config option does nothing - supply chest and ships spawn in any vanilla dungeon loot.

## Steps to reproduce the issue

1. Set config option generatesupplyloot to false
2. Open some dungeon loot chest

## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by someaddons** [comment]
the config option does work, it requires a game restart and ofc doesnt not affect already generated chests/loot

**Comment by Archi9** [comment]
Restart game many times and always create new world (and ofc use defalutconfig folder for configuration). Checked without any other mods too - i always have supply chest in dungeon loot.

**Comment by someaddons** [comment]
you're right seems the config has some loading problem

**Comment by someaddons** [comment]
@Nightenom could you take a look at this? due to the change to server configs the config value is not present on the loottable event yet.

**Comment by Nightenom** [comment]
If I get this right the problem is that server config file isn't present before world creation - thus values affecting worldgen can't be set and first chunks are generated using defaults? Looks like forge design fault to me - the solution could be adding screen between create world menu and chunk generating where user would be allowed to edit the files and then proceed with world generation

**Comment by uecasm** [comment]
The server config file itself is not present before world creation (it can't be, the world directory doesn't exist yet), but there is a "default" server config that gets copied in.  Typically this is populated by modpacks, but the player can do it too.

I haven't checked the precise timing, but try putting the `minecolonies-server.toml` file into the `defaultconfigs` folder (directly under the instance folder, like the client configs).

(Some docs say the folder should be `defaultconfig` but the default does seem to be `defaultconfigs`, although it can be overridden in fml.toml.)

**Comment by Nightenom** [comment]
According to forge code, it should happen during config file creation <https://github.com/MinecraftForge/MinecraftForge/blob/c0e74bc8a8ae68ec07c30e86fc11284a18135bec/src/main/java/net/minecraftforge/fml/config/ConfigFileTypeHandler.java#L51>

**Comment by someaddons** [comment]
ye the loottable load event is happening before the server config is loaded, and thats why the setting has no effect at all

**Comment by uecasm** [comment]
Might need to be moved back to common config then.  Common and client config are loaded significantly before server config, at least on SP.  Not sure about MP.

**Comment by someaddons** [comment]
ye common config would work
