### ISSUE TITLE
Incompatablility between Just Enough Resources and Minecolonies

### ISSUE THREAD

**Issue by BlackWarrior2004** [ldtteam/minecolonies#7044]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.16.5
- MineColonies Version:0.14.134-ALPHA-universal
- Structurize Version:0.13.169-ALPHA-universal
- Related Mods and their Versions:Just Enough Resources- 1.16.4-0.12.0.113

## Expected behavior

The restaurant to show the list of fuels.
## Actual behavior

The fuel list is empty

List Of Mods(i updated the JER, minecolonies and structurize mods. OLD screen shot)
![mods](https://user-images.githubusercontent.com/83131147/116677953-69e27680-a9c6-11eb-8d51-18c7281ea131.png)

## Steps to reproduce the issue

1. Install JER
2. Build Restaurant
3. Fuel list is empty

### Logs

- latest.log: 
- crashlog: 

### Notes

I asked about it in discord and got instructed to report here. Btw I dont need that mod(JER).
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Latest log is needed
