### ISSUE TITLE
Resource scroll deliveries do not update

### ISSUE THREAD

**Issue by Thodor12** [ldtteam/minecolonies#7046]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.14.134-ALPHA-universal.jar
- Structurize Version: structurize-0.13.169-ALPHA-universal.jar
- Related Mods and their Versions:

## Expected behavior
When a delivery is completed, the text with the delivery should disappear.

## Actual behavior
When a delivery is completed, the row in the resource scroll is correctly updated showing the new item count, however the text for the latest delivery does not go away unless you re-open the resource scroll

Before and after delivery screenshots: [https://imgur.com/a/YNN0QG3](https://imgur.com/a/YNN0QG3)

## Steps to reproduce the issue
1. Queue up any building for construction
2. Wait for the deliverymen to move the resources to the builder whilst keeping your resource scroll open

### Logs
- latest.log:
- crashlog:

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by chandler05** [comment]
Can confirm, working on a fix right now.
