### ISSUE TITLE
Builder not building/requesting

### ISSUE THREAD

**Issue by Logicless36** [ldtteam/minecolonies#7050]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context  0.14.107 BETA

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.107

### Logs

- latest.log:  https://gist.github.com/Logicless36/f4dac7c33eea76275380a57fa8294860

### Notes

Builder won't build TH1 for medieval spruce alternative. Not requesting anything, isn't hungry, has been sleeping, it plenty happy. I finished the build on my own and then broke a single block to see if that fixed it, nope. Hired a new builder, nope. cannot get it to finish

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Please update to the latest alpha
