### ISSUE TITLE
Mod requires Structurize 0.13.96-ALPHA and doesn't work on newer versions, but forge fails to load the required version.

### ISSUE THREAD

**Issue by AlfieLeFluffy** [ldtteam/minecolonies#7052]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.13.473-release
- Structurize Version: 0.13.169 Aplha and tested 0.13.96 Aplha

## Problem description

When I run Minecraft the Minecolonies mod says it requires Structurize 0.13.96 Alpha, even when I'm running a higher version (0.13.169 Alpha) and when I tried to install the required version of Structurize (0.13.96), it says the version is too old to run it and tells me to update to a higher one, which doesn't work and says it needs the 0.13.96 version.

### Notes or related things

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MatthiasMann** [comment]
Update - current Minecolonies is 0.14.134 with Structurize 0.13.169
