### ISSUE TITLE
The builder can place vines for free when building a schematic

### ISSUE THREAD

**Issue by kedamono** [ldtteam/minecolonies#7054]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.134-ALPHA
- Structurize Version: 0.13.169-ALPHA

## Problem description
While the builder will place grass blocks, path blocks, and leaf blocks for free, they do not place vines for free. Vines should be added to the list of blocks that the builder places for free, or the other blocks must be removed from the free list. Be consistent with how things work!

### Notes or related things

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Well, the builder doesn't place free paths or grass blocks, the builder consumed dirt for them. The only thing that is free are leaf blocks. Leave blocks in minecraft are fairly useless while vines are harder to get and especially ncessary for mossy blocks which is why it's especially gated.
