### ISSUE TITLE
Unable to Research "More Scrolls" at the University

### ISSUE THREAD

**Issue by Tzasame** [ldtteam/minecolonies#7056]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.134-ALPHA
- Structurize Version: 0.13.169-ALPHA
- Related Mods and their Versions: Added Minecolonies and structurize onto the latest version of ATM6 - To The Sky

## Expected behavior
Being able to research "More Scrolls"

## Actual behavior
Research remains locked although preconditions are met, there is a free research slot, and the required items are in my player inventory.

https://imgur.com/njBjxIT

## Steps to reproduce the issue

Build a Nordic village on a platform in the overworld. Population is currently 59/60 and University is fully staffed level 4.

1. 
2. 
3. 

### Logs

No crashes

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Can you update and try again? Something related to this was changed

**Comment by Tzasame** [comment]
Whatever changed appears to have fixed it. Well done. :)

**Comment by ravenbuilder934** [comment]
great!
