### ISSUE TITLE
Builders And Building 1.12

### ISSUE THREAD

**Issue by ghost** [ldtteam/minecolonies#7059]
### Prerequisites

- I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
-  I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- I made sure that this issue is not a duplicate of any existing issue.

### Context 

- Minecraft Version:
- MineColonies Version:
- Structurize Version:
- Related Mods and their Versions:

## Expected behavior
-Builders will build properly

## Actual behavior
-Builders Just Break Blocks Untill Bedrock If You Build Other Buildings But It will Build Town Hall Properly

**Comment by marchermans** [comment]
1.12 is not supported.
