### ISSUE TITLE
Miner stops working if no cobble in inventory

### ISSUE THREAD

**Issue by cheongchan** [ldtteam/minecolonies#706]
### Minecolonies version

version 0.6.3113 

### Expected behavior

- Miner to ask for cobblestone or get it from hut inventory and continue working.

### Actual behaviour

- Sort of stops working and stands by hut box with cobble. No notification of anything he requires. If manually put cobble into his inventory, he will start working again. There is cobblestone in the hut inventory when he stands there.

If he needs blocks to fill in his mine he should be able to use any stone i feel or even dirt if available.

Not sure conditions surrounding this from occurring.

**Comment by Raycoms** [comment]
yeah I also noticed that, which is strange, he should request it and take
it out of the chest...

2017-03-13 22:19 GMT-03:00 Cheong Chan <notifications@github.com>:

**Comment by cheongchan** [comment]
There are other rocks in the chest so i think an improvement should be the miner is able to use anything like dorite or granite to fill in places he mined ore. Perhaps cobble is the last thing he should attempt to use. This should alleviate some problems since cobble is a common construction material.

I realized for some reason he really wants the walls of the mine to be cobble so he replaced a bunch of it. I dont know what was there before or what triggered him to replace it. I did not see that much ore that would correspond to the amount of cobble.

Currently, It has also lead to the dumb situation that there is a general cobble shortage in the village. The miner becomes a sink for cobble.  Once you give him the cobble, he immediately fills something in and will continue back to work.

Can we somehow mark debugging this a priority? The miner is sort of important for the colony to function.

**Comment by Raycoms** [comment]
If he happens to find a cave or similar he has to protect himself. Usually
the cobble ends up to be the most common material and easy to produce

Am Dienstag, 14. März 2017 schrieb Cheong Chan :

**Comment by cheongchan** [comment]
I realized that this maybe a issue in the previous 0.6.2xxx version i was playing also. What would happen was the miner stopped working. I got annoyed and killed him or tried to restart minecraft to get him moving. I ended moving the mine 4 times until the miner had a 'good place' to mine.

To supply the cobble i spent all the spare time during gameplay mining out a quarry. 

After watching a youtube video on an earlier version of minecolones and learning about this cobble requirement, I tried giving the miner cobble and it does fix him. 

You may want to add this to the documentation about the miner behavior or a player has to be very lucky to find that video and make the connection.

**Comment by Raycoms** [comment]
Yeah he should request that. Will fix that ASAP

Am Dienstag, 14. März 2017 schrieb Cheong Chan :

**Comment by WORMSS** [comment]
I was caught out by this, I tried upgrading this hut, I tried giving him better tools, I tried mining some stuff for him, (incase there was some weird ores behind the wall), I tried resetting him, firing him, rehiring him.

**Comment by Raycoms** [comment]
Closed in favor of new issue soon.
