### ISSUE TITLE
Swineherd's Hut schematic issue

### ISSUE THREAD

**Issue by piesio98** [ldtteam/minecolonies#7061]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.134
- Structurize Version: 0.13.169

## Problem description

There is a schematic issue with "swineherd's hut" on style "MedievalDarkOak", all levels. When i try to confirm the build, item disappears from inventory, "error" sound is played and console error "BuildTool: building is null!".

![image](https://user-images.githubusercontent.com/6825486/116940565-6bce6300-ac6e-11eb-8922-14f9f308dd31.png)

![image](https://user-images.githubusercontent.com/6825486/116939586-ded6da00-ac6c-11eb-97cc-fbf1374c46bb.png)
![image](https://user-images.githubusercontent.com/6825486/116939597-e1393400-ac6c-11eb-9d41-9ba22b33729c.png)

Fine with other schematics
![image](https://user-images.githubusercontent.com/6825486/116939567-d7afcc00-ac6c-11eb-9fb9-1033421fef53.png)

### Notes or related things

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
#5006

**Comment by ravenbuilder934** [comment]
also, try updating
