### ISSUE TITLE
"Delivery person: "My AI has run into an issue"

### ISSUE THREAD

**Issue by pete-koning** [ldtteam/minecolonies#7062]
- [ X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [X ] I made sure that **this issue is not a duplicate of any existing issue.**

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.147-ALPHA

### Logs

- latest.log here:

    https://gist.github.com/pete-koning/518bfe99948a092ca8b618f60e571ffd

   (Look for:  "Pausing Entity Layla L. Pericherla")

### Notes

I've had this before and resolved it by firing the Delivery person, and hiring a new one. It seemed to work. This just reoccured tonight. I have two delivery persons and just started a third one but it was the second one that blew up both times. 
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
duplicate
