### ISSUE TITLE
Builder Issues: Not clearing out areas when creating a building/upgrading

### ISSUE THREAD

**Issue by LaminatedSamurai** [ldtteam/minecolonies#7063]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.16
- MineColonies Version:0.14.97
- Structurize Version:0.13.163
- Related Mods and their Versions: Direwolf20 1.16 (1.8.0 build) on FTB launcher

## Expected behavior
Upgrading or creating buildings should follow the actual blueprint shown with ghost blocks, replacing blocks where needed and clearing out empty space within the building for open spaces.

## Actual behavior
While upgrading or creating a building in the 'Fortress' style, builders are replacing blocks, but not clearing out empty space within the blueprint. Upgrading from Town Hall 2 to Town hall 3 does not remove Dark Oak building in the center, nor the Dark Oak trees. Tavern 2 and 3 does not clear out basement area or initial tents and wagon.

![2021-05-04_15 38 07](https://user-images.githubusercontent.com/83670164/117060708-39187f00-acef-11eb-807c-f77e2a95a2f5.png)

## Steps to reproduce the issue

1. 3 builders in suggested spots.
2. Creative mode to increase stats to 99 for quicker building and breaking, and fulfillment of resource needs.

### Logs

Server hosted by Serverminer.com, not sure how to get logs.

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Can you try updating? You're about 50 versions behind (ask your server host how)

**Comment by Raycoms** [comment]
Either it is a placeholder problem so it's #5006 or it is a patience issue, because those should get cleared in the last step before finishing the building it will do the clearing.
