### ISSUE TITLE
Mod minecolonies requires structurize 0.12.169-ALPHA. Currently, structurize is 0.13.170-ALPHA

### ISSUE THREAD

**Issue by Isfirs** [ldtteam/minecolonies#7065]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.147-ALPHA
- Structurize Version: 0.13.170-ALPHA
- Related Mods and their Versions:

## Expected behavior
Both mods updated through CurseForge app.

## Actual behavior
Minecolonies will not load due to a dependency "mismatch". Structurize is actually newer than required and only by a patch version.

## Steps to reproduce the issue

1. Install Minecolonies through CurseForge App. 
2. Start game

### Logs

If you think they are required for this issue, I will upload them on request. 

### Notes
No notes.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
So install the one that it wants then.

**Comment by Isfirs** [comment]
Update the version check....

**Comment by uecasm** [comment]
Each version of Minecolonies wants a very specific version of Structurize.  It tells you which one in the changelog when you go to download it, or failing that in the screen you mentioned above.  This does get updated periodically but not immediately.  You can't just go install random versions and expect them to work together.

**Comment by ravenbuilder934** [comment]
it is bumped manually because structurize sometimes has breaking changes, and no one got around to it in the past couple days. I've made a pull request to bump it (#7064) which should be merged soon:tm:. In the meantime, I suggest checking the changelog for the required version before updating.

To be completely clear, **this is not an issue** and is working as intended.
