### ISSUE TITLE
AI run into an issue

### ISSUE THREAD

**Issue by MisfitMouse** [ldtteam/minecolonies#7067]
### Context 

- Minecraft Version: latest
- MineColonies Version:0.14.115-ALPHA
- Structurize Version: not sure what this is
- Related Mods and their Versions: ALLthemods6

## Expected behavior

Not get errors
## Actual behavior
The Courier keeps popping up a message see below
![error](https://user-images.githubusercontent.com/83172801/117185764-2e6df080-ada8-11eb-811a-7b68ead38b21.png)

<!-- What should we do to make this issue show up in our own game?
     All I have done is build the warehouse and the hut. She ran fine but today started with error

I hope I did this right, not done this before.

[latest.log](https://github.com/ldtteam/minecolonies/files/6429179/latest.log)

[](https://imgur.com/RBcMsaF)

**Comment by MisfitMouse** [comment]
[latest.log](https://github.com/ldtteam/minecolonies/files/6429190/latest.log)

**Comment by ravenbuilder934** [comment]
Update, this was already fixed

**Comment by MisfitMouse** [comment]
If fixed how do i get that fix?

**Comment by ravenbuilder934** [comment]
You need to update your mod version
