### ISSUE TITLE
Missing blocks in mineshaft

### ISSUE THREAD

**Issue by lebanni** [ldtteam/minecolonies#7071]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.148
- Structurize Version: 0.13.171
- Related Mods and their Versions:

## Expected behavior

Torches not floating in the air.

## Actual behavior

Torches floating in the air.

https://youtu.be/hBegWqiFNLQ

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

Building is MediavalOak Mine level 1.
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
fixed

**Comment by lebanni** [comment]
v 0.14.154 : issue is back.
