### ISSUE TITLE
I am getting the 'incompatible fml modded server error message' how do i fix this?

### ISSUE THREAD

**Issue by FatihHekim0glu** [ldtteam/minecolonies#7078]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.16.5
- MineColonies Version:2.3
- Structurize Version:idk
- Related Mods and their Versions:none

## Expected behavior
Want to play this modpack with my friends on serverminer server

## Actual behavior
Gives this error incompatible fml modded server error message

![Ekran Alıntısı](https://user-images.githubusercontent.com/48997934/117546607-ebc04880-b033-11eb-9c62-f813107f0f4a.PNG)

## Steps to reproduce the issue

1. Open a server and download the mod pack
2. Then open modpack via cursedforge get to the multiplayer
3. Cant joın server cuz of the 
![image](https://user-images.githubusercontent.com/48997934/117546660-2cb85d00-b034-11eb-8134-402637c79c60.png)

### Logs

- latest.log: 
[latest.log](https://github.com/ldtteam/minecolonies/files/6446275/latest.log)

- crashlog: İt is no crash non related

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Does it just say that, or can you actually not connect?

**Comment by FatihHekim0glu** [comment]
no i cant connect

**Comment by ravenbuilder934** [comment]
latest.log is needed then

**Comment by FatihHekim0glu** [comment]
[latest.log](https://github.com/ldtteam/minecolonies/files/6446201/latest.log)

**Comment by ravenbuilder934** [comment]
you have both fabric and forge mods (this is an issue), but don't seem to have minecolonies. Closing as this isn't related to mcol

**Comment by FatihHekim0glu** [comment]
oh god thx man im such an idiot sory for your time

**Comment by ravenbuilder934** [comment]
it's okay!

**Comment by FatihHekim0glu** [comment]
ok... so it seems im dumb af and my dumbass send u the normal minecraft latest.log so here is the right one 
[latest.log](https://github.com/ldtteam/minecolonies/files/6446272/latest.log)

**Comment by ravenbuilder934** [comment]
`[20:27:58] [Netty Client IO #0/INFO]: Client has mods that are missing on server: [per-viam-invenire, betteradvancements]`
Those mods need to be added to the server or removed from the client

**Comment by FatihHekim0glu** [comment]
thx man finnaly its done thx for your time best support ever
