### ISSUE TITLE
Recall with mirrored buildings not working

### ISSUE THREAD

**Issue by cheongchan** [ldtteam/minecolonies#708]
### Minecolonies version

version 0.6.3113 

### Expected behavior

- Recall function to work (with deliveryman hut in this case)

### Actual behaviour

- Worker cannot be recalled in mirrored building "error message: Please make more space around location"

### Steps to reproduce the problem

1. mirror front of deliveryman hut facing its front so doors on the right side
2. recall delivery man

Probably due to some hard coded location relative to hut chest to move worker. Maybe best to disable mirroring building until a more adaptive recall is enabled? or enable a more adaptive recall

**Comment by Raycoms** [comment]
The recall actually searches a location around the chest. But we can give
it more space. Should be way simpler than disabling mirroring =D

2017-03-15 4:09 GMT-03:00 Cheong Chan <notifications@github.com>:

**Comment by marvin-bitterlich** [comment]
@Raycoms is this fixed?

**Comment by Raycoms** [comment]
No idea, no one complained for a while

2017-05-10 7:10 GMT-03:00 Marvin Hofmann <notifications@github.com>:

**Comment by marvin-bitterlich** [comment]
then closing for now
