### ISSUE TITLE
Tower Guards (not barrack guards) refuse to recognize plate armor even though they will wear them

### ISSUE THREAD

**Issue by LordHellscream** [ldtteam/minecolonies#7080]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.151-ALPHA
- Structurize Version: 0.13.171-ALPHA
- Related Mods and their Versions:

## Expected behavior
1. Researched Plate armor
2. Blacksmith can make plate armor
3. have 4 set of plate armor in stock
4. Guard tower levels are all level 4 (both barrack towers and guard towers)
5. all guards are at least worker level 10 (they are very good stats)
6. all guards are knights

Expected outcome: 
1. all guards will recognize plate armor in stock and wear them
2. when given plate armor directly, they will stop complaining about not having armors

## Actual behavior
1. barrack guards all recognize plate armor normally, and get them from warehouse and wear them
2. regular tower guards keep complaining no armor and won't take plate armor from storage
3. when given plate armor directly drop into their inventory, they will eventually wear them, but they still keep complaining not having armor --> means they will switch if there are other armors in ware house.

## Steps to reproduce the issue

1. have guard towers to level 4, and have a guard with sufficient level (whatever it is), have plate armor research and have plate armor in warehouse. 
2. see if they will wear them

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
I double checked and tested this. This is not an issue in the newest version.
