### ISSUE TITLE
Crash when right clicking builder while they build the builder's hut structure 

### ISSUE THREAD

**Issue by TripConeHead** [ldtteam/minecolonies#7081]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.14.154-ALPHA-universal.jar
- Structurize Version: structurize-0.13.171-ALPHA-universal.jar
- Related Mods and their Versions: 

## Expected behavior
Builder's GUI

## Actual behavior
Upon interacting with the builder after instructing them to build the builder's hut structure, the game will freeze and then crash.

## Steps to reproduce the issue

1. Create colony like you normally would
2. Place builder's hut block
3. Begin the structure by hiring a colonist to become a builder
4. interact with builder
5. game crashes

### Logs

- latest.log: https://gist.github.com/TripConeHead/9f1f69686cd26095b864482d5a947edb
- crashlog: https://gist.github.com/TripConeHead/9237156b65d8e6833baeeb91c15b4105
### Notes
Tried multiple times in different worlds with different colonies, same results every time.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
There is a mod adding invalid tools to your game that crash because they null things that can't be null.
