### ISSUE TITLE
Deliveryman AI had a problem, requested I submit latest.log to authors.

### ISSUE THREAD

**Issue by TheKLC** [ldtteam/minecolonies#7084]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5 (1.16.5-forge-36.1.4)
- MineColonies Version: 0.14.97-ALPHA

### Logs

- latest.log: https://gist.github.com/TheKLC/4a35a8943b0f8425623bb529b3c43179

## Steps to reproduce the issue / details

Just reporting the AI issue. 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Thanks, known problem. Duplicate issue
