### ISSUE TITLE
Frequent crashing due to Exception in server tick loop

### ISSUE THREAD

**Issue by vVwd** [ldtteam/minecolonies#7085]
- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

Latest version of MineColonies official (v2.3), CurseForge launcher.

Hi there,

Exception in server tick loop

Not sure if you can reproduce my bug, still thought it was worth reporting. Basic problem is just random crashing of the game. Looked if it was Graphic card related (outdated drivers, all that stuff) due to playing on a laptop with 2 graphic cards, and could not really find an issue since all is current. Also checked RAM setting, 8 GB used on 32GB RAM. Don't think it is either on of the above things, but what do I know...

If it is not a bug, I hope someone can tell me how to fix this issue. I know this is not the place for it, I would appreciate it.

Hope I've done the file uploading correctly.

[crash-2021-05-04_07.58.56-server.txt](https://github.com/ldtteam/minecolonies/files/6448325/crash-2021-05-04_07.58.56-server.txt)
[2021-05-09-7.log.gz](https://github.com/ldtteam/minecolonies/files/6448334/2021-05-09-7.log.gz)

Thanks for the support! Appreciated...

**Comment by Raycoms** [comment]
Fixed in latest version. Will be updating the pack soon.
