### ISSUE TITLE
Self Reporting AI Issue

### ISSUE THREAD

**Issue by FatihHekim0glu** [ldtteam/minecolonies#7087]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.16.5
- MineColonies Version:2.3

### Logs

- latest.log: 
[latest (2).log](https://github.com/ldtteam/minecolonies/files/6450491/latest.2.log)

## Steps to reproduce the issue / details

No i dont think it has 

Just reporting the AI issue. 

### Notes

![Ekran Alıntısıaaaa](https://user-images.githubusercontent.com/48997934/117627128-8332b200-b180-11eb-973e-96fa3ef702a6.PNG)

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Thanks. Known. Duplicate
