### ISSUE TITLE
Ai Issue - problem not found

### ISSUE THREAD

**Issue by DangerDr** [ldtteam/minecolonies#7103]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [ x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

1.16.5- Minecraft Version:
minecolonies-0.14.162-ALPHA-universal.jar - MineColonies Version:

### Logs

- latest.log:  https://gist.github.com/DangerDr/5ada939438e699aa4ad57e43ef331aa9

## Steps to reproduce the issue / details

Just reporting the AI issue. 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Which worker is this?

**Comment by DangerDr** [comment]
Rabbit seems to be the only one so far
