### ISSUE TITLE
Courier AI Bug

### ISSUE THREAD

**Issue by JChen677** [ldtteam/minecolonies#7107]
I got a message from my courier which said that they're AI has run into some issue and I should send the latest.log file to the devs. I first noticed the issue after upgrading my Warehouse to level 2, however my other courier has run into no such issues.

[latest.log](https://github.com/ldtteam/minecolonies/files/6488771/latest.log)

**Comment by Raycoms** [comment]
Known issue, please fill in the entire template the next time.
