### ISSUE TITLE
Undertaker raise exception and stop working while the graveyard was fullfilled.

### ISSUE THREAD

**Issue by ty359** [ldtteam/minecolonies#7108]
### Prerequisites 

- [y ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [y ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.154-ALPHA

### Logs

- latest.log: https://gist.github.com/ty359/a05cb93d0d8447a2083b56563c11f961

## Steps to reproduce the issue / details

Fullfilling the graveyard, then the undertaker stop working, and show the error message.

Just reporting the AI issue. 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
fixed in latest
