### ISSUE TITLE
console spam

### ISSUE THREAD

**Issue by fullshadowcat** [ldtteam/minecolonies#7109]
- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.14.162-ALPHA-universal

### Logs

https://gist.github.com/fullshadow/e7089b941801aa441e4a517d35757a09#file-gistfile1-txt

**Comment by Raycoms** [comment]
Did you do anything weird with your colony? Load it from a backup or so? There is a courier that is assigned to a courier hut, but doesn't have the job, this should be impossible.

**Comment by fullshadowcat** [comment]
No colony from the backup did not load, just at a certain point an AI error appeared over the chef in restaurant. Periodically the courier drowns in the pond. A new courier is automatically assigned by the colony. After I suspended the activity of the chefs in the restaurant and restarted the server, the spamming in the console stopped.

**Comment by fullshadowcat** [comment]
Nope that wasn't the problem, after a while it started again

**Comment by Raycoms** [comment]
Can you fire and re-hire all couriers?

**Comment by Raycoms** [comment]
Maybe fire re-hire that chef too
