### ISSUE TITLE
Can't load due to pathfinding issue ( i think )

### ISSUE THREAD

**Issue by Nandorian88** [ldtteam/minecolonies#7110]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.162
- Structurize Version: 0.13.171

### Logs

- latest.log:  https://gist.github.com/Nandorian88/047f7355ab3d49a761f94eabecbf8d56

## Steps to reproduce the issue / details

I've manually updated minecolonie (and structurize) to the latest version on the direwolf modpack, and I could just play fine. But now i can't load my world, after reading the crashlog it seems that it comes from one of the minecolonie's entity. I also tried to load a backup, just after I upgraded the mod, but it did the same error "ticking entinty".
The guy "Azariah N. Geste" is my enchanter, and in his hut is level 3 spacewars style, if it can help.
Just reporting the AI issue. 

### Notes

Any chance i can get my world to load again ?
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
We believe some other mod is injecting goals into MineColonies entities here

**Comment by Nandorian88** [comment]
I have ftbchunks loading chunks, i actually forgot to mention it

**Comment by Raycoms** [comment]
That shouldn't cause it, must be some kind of entity behaviour change mod or so.

**Comment by someaddons** [comment]
could you add performant and enable its ``debugOptionsEnabled`` config feature? then we could see which mod causes the issue in your latest.log, and it'll probably stop crashing for you

**Comment by Nandorian88** [comment]
Well I'll need a hand on this one. Where do i find that log again ? Previous one was just a copy paste of the crash report automatically generated..

**Comment by someaddons** [comment]
Quote from our helpful bot commands:
`You can generally find these logs in your game or server directory under the logs folder. The file latest.log is most likely required.
Once you've found this file please post it on a paste site. As a team we recommend https://gist.github.com/.`

**Comment by Nandorian88** [comment]
[latest.log](https://github.com/ldtteam/minecolonies/files/6489821/latest.log)
Here we go, then !

**Comment by Nandorian88** [comment]
https://gist.github.com/Nandorian88/03071b58551432225b211ef6d8a28d11
There we go

**Comment by someaddons** [comment]
oh I probably should've explained what I meant better, before posting the log install this mod: https://www.curseforge.com/minecraft/mc-mods/performant start once, then go into the config called ``performant-common.toml`` and there you turn the setting `debugOptionsEnabled ` to true. Afterwards play like before when you got the error and after a few min you turn it off and then send us the latest.log here through gist

**Comment by Nandorian88** [comment]
Ok so, after reloading my save with performant, it actually worked... Can i still manually generate some kind of log of what is working now, and what wasn't before?

**Comment by ravenbuilder934** [comment]
Logs are generated each time, even if it doesn't crash

**Comment by someaddons** [comment]
ye instead of a crash your latest.log should now have logged a warning, if you toggled the config option I mentioned before. So uploading that latest.log should be helpful to us to find the cuplrit

**Comment by Nandorian88** [comment]
Hope it will answer some questions
https://gist.github.com/Nandorian88/ac2be3cee4784186254f3126c128940e

**Comment by someaddons** [comment]
hm no doesnt contain the error xD
