### ISSUE TITLE
Miner fails catastrophically if existing shaft is damaged.

### ISSUE THREAD

**Issue by Electrofried** [ldtteam/minecolonies#7115]
### Prerequisites 

- [ x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version:  0.14.162
- Structurize Version:  0.13.171
- Related Mods and their Versions: n/a

## Expected behavior

Miner should rebuild the shaft down if 'repair' is requested or if it becomes damaged.

## Actual behavior

Say if lava happens to spill out in the mineshaft, and say that said mineshaft is made from wood, then the entire thing burns, the main 'shaft' is still there and the miner will attempt to scale the ladder but due to lack of platforms on each level they will fall, or simply get stuck in a pathing loop.

## Steps to reproduce the issue

1.  make a miner that uses wood on the main shaft for platforms
2.  set fire to the mine shaft
3.  watch as the miner has a conniption.

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
There is already an issue for that, either here or in the feature repo.
