### ISSUE TITLE
Server is crashing, while trying to start

### ISSUE THREAD

**Issue by Deviz17** [ldtteam/minecolonies#7119]
**Minecolonies version**
- Version: forge 1.16.5 36.1.0
- MineColonies Version: minecolonies-0.14.163-BETA
- Structurize Version: structurize-0.13.171-ALPHA

**Expected behavior:**
the world don't start

**Actual behaviour:**
Server is crashing, while trying to start

_Message error:_
Entity Type: minecolonies:citizen (com.minecolonies.coremod.entity.citizen.EntityCitizen)
Entity ID: 234
Entity Name: Demetrius R. Churmond
Entity's Exact location: 402.09, 68.00, 260.50
Entity's Block location: World: (402,68,260), Chunk: (at 2,4,4 in 25,16; contains blocks 400,0,256 to 415,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Entity's Momentum: 0.00, -0.08, 0.00
Entity's Passengers: []
Entity's Vehicle:  ~~ERROR~~ NullPointerException: null

[crash-2021-05-19_00.31.32-server.zip](https://github.com/ldtteam/minecolonies/files/6504801/crash-2021-05-19_00.31.32-server.zip)

thank you very much

**Comment by Raycoms** [comment]
Similar to another issue, there is another mod, inserting goals into our entities causing this crash. Mods can't do this just.

**Comment by Deviz17** [comment]
[crash-2021-05-19_19.39.58-server.zip](https://github.com/ldtteam/minecolonies/files/6510714/crash-2021-05-19_19.39.58-server.zip)

[2021-05-19-7.log.gz](https://github.com/ldtteam/minecolonies/files/6510723/2021-05-19-7.log.gz)


i removed all mods except minecolonies and structurize
equal crash; maybe wiping out all the settlers?

**Comment by Raycoms** [comment]
Same as #7121

**Comment by Raycoms** [comment]
Those two crash logs you sent me, still have a bunch of mods

**Comment by Deviz17** [comment]
I will create a new world, but he hoped to have been useful for future problems, thanks
