### ISSUE TITLE
Automatic View Update [$5]

### ISSUE THREAD

**Issue by Raycoms** [ldtteam/minecolonies#712]
We need a way to automatically update the views from the windows.
At the moment the windows have old instances of the views and they only update after they've been opened again.
There should be a way to do this on the fly.
This way we wouldn't have to update the local views manually.

**Comment by xavierh** [comment]
Ideally a view should only be send to the player when the gui is open.

Atm all the view are send whenever they change. For instance, the Builder hut view can change very frequently since I changed the resource tab. The view is sent all the time regardless of the player being in the gui or not

**Comment by Raycoms** [comment]
Yeah that would save us a lot of traffic as well.

2017-03-16 15:23 GMT-03:00 xavierh <notifications@github.com>:

**Comment by Wissi** [comment]
@Raycoms Should this be closed now?
