### ISSUE TITLE
Crash on login

### ISSUE THREAD

**Issue by lordfriend** [ldtteam/minecolonies#7126]
### Prerequisites 

- [] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.162-alpha
- Structurize Version: 0.13.171-alpha
- Related Mods and their Versions:

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: https://gist.github.com/lordfriend/7f64669e716102a0c1978c89ff8eeb3d
- crashlog:  https://gist.github.com/lordfriend/97fd4c531b13a76d0b0319f67eb57baf

### Notes
Server is running in Docker container and just started. when I joined in, the server crashed. restart server not solve the issue.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Fix just merged
