### ISSUE TITLE
Large Pirate Ship has no Loot

### ISSUE THREAD

**Issue by Maachiavelli** [ldtteam/minecolonies#7127]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.14.166-ALPHA-universal
- Structurize Version: structurize-0.13.173-ALPHA-universal
- Related Mods and their Versions:

### Expected behavior
Small Invading Pirate Ship has Loot in Chests
Large Invading Pirate Ship has Loot in Chests

### Actual behavior
Small Invading Pirate Ship has Loot in Chests
Large Invading Pirate Ship _DOES NOT_ have Loot in Chests

**Comment by Raycoms** [comment]
#5006 ships have to start using racks instead of chests for loot
