### ISSUE TITLE
Crash after improving hut recipe

### ISSUE THREAD

**Issue by Rolnaro** [ldtteam/minecolonies#7128]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.14.131-ALPHA-universal
- Structurize Version: structurize-0.13.167-ALPHA-universal
- Related Mods and their Versions: modpack Minecolonies official 1.16.5 - v2.3

## Expected behavior

The game to continu with reduced recipe cost after a recipe is improved.

## Actual behavior

The game crashes after a lot of exception errors with [Server thread/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID ...
and actions.js:2659 ps stderr: AL lib: (EE) alc_cleanup: 1 device not closed

## Steps to reproduce the issue

1. Installed the game with GDLauncher on a different drive and directory then C:<default>
2. Play the game and wait for a recipe to improve
3. Game crashes and game exits

### Logs

- latest.log: 
- crashlog: 
https://gist.github.com/Rolnaro/bc29cfb6e74e66dada4b17739e16d6ed#file-debug-1-log
https://gist.github.com/Rolnaro/bc29cfb6e74e66dada4b17739e16d6ed#file-latest-log

### Notes

Maybe not related but updating to newer Minecolonies version doesn't work and have to reinstall the game.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
You're quite some versions behind, can you try the newest?

**Comment by Rolnaro** [comment]
Updated to Minecolonies Official 1.16.5 v2.5
Loaded world and instantly crashed

Updated Forge Modloader to 36.1.18
Loaded world and instantly crashed

Disabled per-viam (as seen in some older bug report) now world loaded.

Will response when there is a new recipe improvement and what happens then.

**Comment by Raycoms** [comment]
Okay, this should be solved then (fixes for the bug you reported were merged earlier)
