### ISSUE TITLE
Description: Rendering Block Entity (Graveyard Asian version)

### ISSUE THREAD

**Issue by vVwd** [ldtteam/minecolonies#7129]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

- Minecraft Version: latest
- MineColonies Version: latest
- Structurize Version: latest

## Expected behavior
Placement of Asian version of the graveyard

## Actual behavior
Placement causes crash

## Steps to reproduce the issue

Try placement with wand at level 5

Other issue: Grave keeper not placing graves of those who died when using the Asian graveyard. Did manage to place one, crash happened after the latest update.  Graves are not placed / stay nameless in the yard. Not sure if the dead are in the menu list to get buried, definitely not marked as in a grave. Grave keeper also not picking up stuff from graves.

[crash-2021-05-21_10.30.19-client.txt](https://github.com/ldtteam/minecolonies/files/6521236/crash-2021-05-21_10.30.19-client.txt)

[colonies-2021-05-21_10.30.14.zip](https://github.com/ldtteam/minecolonies/files/6521250/colonies-2021-05-21_10.30.14.zip)

**Comment by ravenbuilder934** [comment]
Can you please put the crashlog in a https://gist.github.com?
