### ISSUE TITLE
Library redstone bug

### ISSUE THREAD

**Issue by HypnoPants** [ldtteam/minecolonies#713]
Library redstone off slightly in the 1.11.2 version, it just needs and extra repeater and it will work fine.

**Comment by Raycoms** [comment]
What?

**Comment by Raycoms** [comment]
Can you write that in the thread on the forums?

Its a player made decoration.

**Comment by HypnoPants** [comment]
Oh I see, sure.

I had clicked on Bug Reporting in the public forum and it sent me here :P

**Comment by xavierh** [comment]
@Raycoms the decorations is shipped in the jar, regardless if this is a user creation, it should be fixed.
@HypnoPants Could you provide a new scan with the fix ?

**Comment by kedamono** [comment]
Updated the .nbt file and fixed the light issues. 
[Town_Library.nbt.zip](https://github.com/Minecolonies/minecolonies/files/869282/Town_Library.nbt.zip)

**Comment by HypnoPants** [comment]
@xavierh I was gonna say... I have no idea how to provide a scan, I would if I knew how! :)

**Comment by xavierh** [comment]
That was quick. Thank you. Will do a pr later on today. Will add your
markets while I am here.
