### ISSUE TITLE
Owning field not considered because not loaded error for scarecrow blocks

### ISSUE THREAD

**Issue by Bashkaaaa** [ldtteam/minecolonies#7131]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context

- Minecraft Version: Forge 36.1.23 (Minecraft 1.16.5)
- MineColonies Version: minecolonies-0.14.163-BETA-universal.jar
- Structurize Version: structurize-0.13.171-ALPHA-universal.jar

## Problem description
Console throws an error [minecolonies/]: Owning field not considered because not loaded: BlockPos{x=9131, y=65, z=-10912}. This error is displayed over and over for multiple fields in many colonies.

### Notes or related things
- We are not running the latest alpha, because it would be difficult to keep up with updating the modpack and keep clients up -to-date for up to a 100 active players with daily updates, however we always try to update the pack the same day when a new beta comes out
- All coordinates point to field designators (scarecrows)
- Errors won't stop until the owner or officer of the colony removes the scarecrow and replaces the blocks in which the scarecrow was with a solid blocks (like dirt)- removing the scarecrow by itself doesn't stop the console spam
- Console spam will come back if they put the scarecrow back
- Server tick rate consistantly lowers, until it crashes- depending on number of people online, between every few hours to every 20 minutes with 20+ players online.

![image](https://user-images.githubusercontent.com/84290349/119136573-1f41a080-ba40-11eb-9832-15235cd726b9.png)

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Do you have optifine installed on the server or so? Something that forces chunks to unload?

**Comment by Bashkaaaa** [comment]
Hey. I tripple checked (just in case I copied it to the server by accident) no, there is no optifine. Full mod list: https://www.curseforge.com/minecraft/modpacks/ttw-community-server-pack/relations/dependencies, datapacks:
![image](https://user-images.githubusercontent.com/84290349/119167469-30020e80-ba60-11eb-979e-8b196ea556d4.png)
(The dimension detector was added after the issues with field errors started, which was after the update to 0.14.163-BETA
