### ISSUE TITLE
Description: Ticking entity causing crash on login

### ISSUE THREAD

**Issue by vVwd** [ldtteam/minecolonies#7134]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: current
- MineColonies Version: current
- Structurize Version: current

## Expected behavior

Being able to login

## Actual behavior

Game crash on login due to ticking entity

## Steps to reproduce the issue

Can provide save file if needed.

### Logs

- latest.log: 

[latest.log](https://github.com/ldtteam/minecolonies/files/6525971/latest.log)

- crashlog: 

[crash-2021-05-22_08.32.30-server.txt](https://github.com/ldtteam/minecolonies/files/6525965/crash-2021-05-22_08.32.30-server.txt)

**Comment by dhouck** [comment]
What is the actual version number when you say "current"?  This should have been fixed in 0.14.169-alpha yesterday, and if not this issue will probably last for a few days and there'll be more updates since then.

**Comment by vVwd** [comment]
Let me check, sec.

**Comment by vVwd** [comment]
Minecolonies Official 1.16.5 v2.5 (release) - (current)

Minecolonies      (to ver 0.14.166-ALPHA)
Structurize            (to ver 0.13.173-ALPHA)

**Comment by dhouck** [comment]
Can you update to the latest version (0.14.173-alpha) and see if that fixes it?

If not, a friend had some success with NBT editing; if you're comfortable with that, you can try removing Felicity T. Barnes from both `<world>/data/capabilities.dat` and `<world>/region/r.9.4.mca` as a workaround, but this will get rid of that colonist from your world so isn't ideal.

**Comment by vVwd** [comment]
There is no other version available on the CurseForge launcher. Can I pull it from here?

**Comment by dhouck** [comment]
You can get it from the CurseForge website at https://www.curseforge.com/minecraft/mc-mods/minecolonies/files/all (or really at the main https://www.curseforge.com/minecraft/mc-mods/minecolonies/ page on the sidebar), but if you still have trouble with that you'll need to wait for someone else to help.  I'm not a dev or an official support person, just the guy who noticed your issue first and had seen similar ones, and I don't use the CurseForge launcher so can't really help with trouble there.

**Comment by vVwd** [comment]
Fixed. Updated to .173

Bug can be closed.

Thanks for the help, dhouck. Appreciated...
