### ISSUE TITLE
Barbarian camp spawn in middle of claim

### ISSUE THREAD

**Issue by ghost** [ldtteam/minecolonies#7136]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.134
- Structurize Version: 0.13.169

## Problem description

I got raided by barbarians to the "south/west" and went to search only to find a handful to the south and west (~1/3).  I came back to my base to find the remaining ones taking a dip in the lake in the middle of my claim around their submerged campfires which is to the north and west of my town hall.
### Notes or related things
![image](https://user-images.githubusercontent.com/38839287/119240356-9e080d80-bb14-11eb-8088-f01bc2b71e0c.png)

The random destruction of barracks flooring is quite weird as well, there was no way that the ones to the south could be considered "stuck" except for being unable to path past the iron door.  Is/are there certain blocks that raiders will not destroy?  Failing that can a config be set to disable their destructive behavior(except for perhaps ignoring gate blocks)?

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Yeah, that's intended

**Comment by ghost** [comment]
To be clear, barbarians spawning inside the middle of your town _is_ intended?

**Comment by ravenbuilder934** [comment]
Yep. They should spawn at least 20 blocks from hut blocks and farther from guard/barracks towers

**Comment by ghost** [comment]
ah, alrighty then, my colonists don't get to enjoy a scenic lake view.
Out of curiosity, what is the raid direction based off of then? because it cannot be the town hall in this case.
