### ISSUE TITLE
Builder is not finishing medievaldarkoakalternative townhall

### ISSUE THREAD

**Issue by komiza24** [ldtteam/minecolonies#7137]
### Prerequisites 

- [ x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context   

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.14.173-ALPHA-universal.jar
- Structurize Version: structurize-0.13.173-ALPHA-universal.jar
- Related Mods and their Versions:  jei-1.16.5-7.7.0.98.jar, OptiFine_1.16.5_HD_U_G8.jar, replaymod-1.16.4-forge-1.0.0-beta.jar

## Expected behavior

I would expect that the builder has no open request for Pickup and finishing the townhall when go got all items given he need for it.

## Actual behavior

First at all the builder is not requesting the needed items but in the hut under required resources they are listed, 
if i put them in there he is not finishing the build as usual. 
Another point is that the builder has an request in the clipboard wich says Pickup. 
The builder is stuck at placing the last 9 torches and the campfire. 

## Steps to reproduce the issue

1. 
Create a new town, build the builder hut. 
2. 
After that's done, try to build the medievaldarkoakalternative. 
3. 
He won't be able to finish the building cause he isn't able to place the last 9 torches and the campfire. 

### Logs

- latest.log: 
- crashlog: 

### Notes

I tryed to do the same in a testworld, doesnt worked aswell. I have read to try to build the courier's hut and warehouse before. 
After i did that the request for the pickup at the clipboard has stopped.
I can start the build of the medievaldarkoakalternativ but there are no items requried anymore. 
The campfire aswell as the torches got placed down but he is still not finishing the build. 
After an little while he just start to break down parts of the townhall and replace them aigen. 
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
The last step in this building takes a long while, he will remove all unnecessary blocks, place air and do a lot of rescanning, it's a very big schematic and this takes some time. It's the longest step quite often.

**Comment by komiza24** [comment]
I have sitten here for abaout 2 hours. But okay, i till try to afk and leaf him working without 
to disturb him. Maybe u're right. Thank u anyways if it will not work i will just write below here. Aswell if it's working after some time so u know whats going on.

**Comment by Raycoms** [comment]
The specific townhall your building is well known for people reporting because it really takes ages to build. There are builds that take 1-2h total, but there are some like this townhall that really are just enormous =D

**Comment by komiza24** [comment]
Haha okay thank u for your help bro :)  have a nice day !
