### ISSUE TITLE
Colony protection request/issue

### ISSUE THREAD

**Issue by Divineaspect** [ldtteam/minecolonies#714]
0.6.3125

Please add a configurable range to the colony protection.

Colony protection is preventing other people from fighting monsters within it's range on a server

**Comment by Raycoms** [comment]
The newest version should fix that. Players will be able to fight monsters
even inside colonies. (Defend themselves)

2017-03-19 2:35 GMT-03:00 DivineAspect <notifications@github.com>:

**Comment by Wissi** [comment]
The Town Protection area is set in the Config file  (.../minecraft/config/minecolonies.conf ) you can make it a larger or smaller area.

The latest version ( as Raycoms says) now has s configurable option in the Townhall GUI (permissions tab - page 2 [top right of pg.]) where you can configure a lot of options individually per "rank". 

For more info:  https://wiki.minecolonies.com/
