### ISSUE TITLE
Guard trainees not all sleeping at night.

### ISSUE THREAD

**Issue by vVwd** [ldtteam/minecolonies#7141]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.173 Alpha

### Logs

- latest.log: 

[latest.log](https://github.com/ldtteam/minecolonies/files/6527712/latest.log)

## Steps to reproduce the issue / details

Tiny issue with Archery and Combat Academy, Asian version. 

At higher tier of both buildings only 1 trainee goes sleeping, the others stand downstairs not sleeping. And sometimes non of them go to bed.

Affects the overall score of your colony.

Not game breaking, its just a thing. Just reporting the AI issue.

![2021-05-23_10 00 08](https://user-images.githubusercontent.com/7923896/119252668-cc85f700-bbad-11eb-9b83-0c1e17240dd0.png)
![2021-05-23_10 00 23](https://user-images.githubusercontent.com/7923896/119252674-d27bd800-bbad-11eb-8bcd-d493a774af86.png)

**Comment by Raycoms** [comment]
#5006
