### ISSUE TITLE
Forester not working the way he expected

### ISSUE THREAD

**Issue by Jiriki79** [ldtteam/minecolonies#7144]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context: I'm currently playing on my server with the Valhelsia 3 (v3.3.1) modpack and when i try to set up a restricted area for forester he just stands by idle even when he has request from builder

- Minecraft Version:1.16.5
- MineColonies Version: minecolonies-0.14.134-ALPHA-universal

### Logs

- latest.log: https://gist.github.com/Jiriki79/432a85d24929af6e8b1f6e1d474ff30c

## Steps to reproduce the issue / details

<have a level 1 foresters hut and go to set restriction right behind his house and they just stand near the workbench. make sure to set restriction to "on" on the second page >

Just reporting the AI issue.

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
This was already fixed, update

**Comment by Jiriki79** [comment]
will it break my current colonie on the server to just update minecolonies

**Comment by ravenbuilder934** [comment]
It shouldn't, no

**Comment by Jiriki79** [comment]
does forester require a task from builder to work or will they just start working on their own

**Comment by Jiriki79** [comment]
also my builder keeps requesting resources even though all are in their racks

**Comment by ravenbuilder934** [comment]
> does forester require a task from builder to work or will they just start working on their own

they'll work on their own

> also my builder keeps requesting resources even though all are in their racks

please join our [discord](https://discord.minecolonies.com) for support
