### ISSUE TITLE
Can't see all of the citizens' stats when hiring.

### ISSUE THREAD

**Issue by The-Kenyon** [ldtteam/minecolonies#7146]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.171-alpha
- Structurize Version: 0.13.173-aplha
- Related Mods and their Versions: Minecolonies specific

## Expected behavior
  When hiring citizens for a job, I should be able to see the applicable stats.  For example:  I am at a guard tower trying to decide which citizens I would like to assign as knights, but I can not see their adaptability stat.

## Actual behavior
 I am at a guard tower trying to decide which citizens would be best suited as Knights, but some of the citizens' Adaptability stats are not displayed.
![20210523_230750](https://user-images.githubusercontent.com/84695056/119293159-d0526180-bc1f-11eb-984a-dd7b1600c1a7.jpg)

## Steps to reproduce the issue

1. <acquire some citizens
2. <open GUI at barracks tower
3. <note that some of the citizens' adaptability scores are not visible

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Stoovey** [comment]
@The-Kenyon 

1) You aren't running the latest alpha version of the game.
2) I'm unable to reproduce this and I'm running minecolonies-0.14.181-ALPHA-universal.jar
![image](https://user-images.githubusercontent.com/19435071/119868509-055bfe00-bf17-11eb-9cf1-7a20e7f8e3c8.png)

3) I also changed my graphic settings in game (the different resolutions), and the screen/GUI sized correctly.
Try updating to the latest version available [here](https://www.curseforge.com/minecraft/mc-mods/minecolonies/files/all)

4) I've also changed my GUI Scale from 1-4-Auto and still unable to reproduce this issue.

Once upgraded, let us know the results.
