### ISSUE TITLE
Colonists get stuck in the town hall's doors

### ISSUE THREAD

**Issue by jonabrv1965** [ldtteam/minecolonies#715]
### Minecolonies version

minecolonies-universal-1.10.2-0.6.3125

### Expected behavior

- The colonist open both doors in the town hall and get to their jobs.

### Actual behaviour

- This happens in the morning when the colonist go out to do their jobs, not always the same colonist. It seems that they open just one of the double doors and try to get out and push each other and none go out...You've to go and open the second door manually..

### Steps to reproduce the problem

1. XYZ
2. ZYX
3. ...
4. Profit

**Comment by Raycoms** [comment]
has been reported already. Working on it.
