### ISSUE TITLE
Builder gui has third empty page

### ISSUE THREAD

**Issue by ToMe25** [ldtteam/minecolonies#7152]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: eec25aa
- Structurize Version: 0.13.174-ALPHA
- Related Mods and their Versions:

## Expected behavior

I would expect the builder to only have as many pages in the main tab as are actually used.
In this case that would be two.
The builders hut is style caledonia and level 2.

## Actual behavior

For some reason that I do not know the builder has a third main page with nothing on int.
I assume this is because in the past this is where the build orders were listed, but they were moved to the settings tab?
![2021-05-26_13 56 13](https://user-images.githubusercontent.com/38815969/119656211-bcc71680-be2a-11eb-9c02-1c30719e902f.png)

## Steps to reproduce the issue

1. Build a builders hut(Tested with styles caledonia and acacie, and levels 1 and 2)
2. Open its gui
3. See three main pages instead of two.

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
If you switch to manual mode in the settings, you will see workorders on the last page. this will become a propper module with description in the future. But it's not a bug.

**Comment by ToMe25** [comment]
Oh, I assumed they would still show up under the button.
Also the work orders do not show up there, even in manual mode, I just tested this.
Or do they just show up when the builder isn't working on anything?

**Comment by Raycoms** [comment]
It's a settings only page, so they don't show up there, they will get their own list page in the near future. I'm not 100% sure how it works atm with the manual mode list. I will rework this and have it always display the list of workorders that are currently assigned to the builder and allow cancellation. And then in manual mode it will show all + assignment
