### ISSUE TITLE
No kill commands to remove Phantoms

### ISSUE THREAD

**Issue by Stoovey** [ldtteam/minecolonies#7156]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.14.181-ALPHA-universal.jar
- Structurize Version: structurize-0.13.174-ALPHA.jar

## Problem description

There are no "easy to use" kill commands to remove Phantoms when playing at night.

This gets annoying when trying to complete tasks during the night, or when you are idling for whatever reason.

### Notes or related things

I've already developed the code for this.

## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
1) https://github.com/ldtteam/minecolonies-features/issues, this isn't a bug
2) if you've made the code you're welcome to make a PR

**Comment by UnityRacy** [comment]
why not /gamerule
