### ISSUE TITLE
Builder keeps asking for a Item Frame when upgrading town hall to tier 3

### ISSUE THREAD

**Issue by jonabrv1965** [ldtteam/minecolonies#716]
### Minecolonies version

minecolonies-universal-1.10.2-0.6.3125

### Expected behavior

- he should use the supplied item frame

### Actual behaviour

- Once I put the item frame inside the builder's inventory, it (the item frame) disappear and the builder request an item frame again... and again...

### Steps to reproduce the problem

1. XYZ
2. ZYX
3. ...
4. Profit

**Comment by Raycoms** [comment]
Yeah he requests item frame by item frame.
He needs quite a bunch for townhall 3.
