### ISSUE TITLE
Crash on load world with latest version of MineColonies and Tinkers

### ISSUE THREAD

**Issue by Electrofried** [ldtteam/minecolonies#7165]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.14.186-ALPHA
- Structurize Version: structurize-0.13.174-ALPHA
- Related Mods and their Versions: TConstruct-1.16.5-3.0.4.171

## Expected behavior

The game not crash when loading a world with tinkers and minecolonies
 
## Actual behavior

Game crashes with both mods, rolling back to past version of tinkers resolves the issue.

## Steps to reproduce the issue

1. Install minecolonies and tinkers latest versions
2. load an existing world
3. game crashes
### Logs

- latest.log: https://gist.github.com/Electrofried/63366ce0630bce006b2bfc17f4550971 
- crashlog: included above

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Fixed
