### ISSUE TITLE
Bakery not requesting fuel

### ISSUE THREAD

**Issue by ToMe25** [ldtteam/minecolonies#7175]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 48b7927
- Structurize Version: 0.13.174-ALPHA
- Related Mods and their Versions:

## Expected behavior

I expected the Bakery to request fuel to bake bread.

## Actual behavior

The baker just bakes the bread with their bare hands I guess.

## Steps to reproduce the issue

1. Build a Bakery
2. Hire someone in it
3. Enable some fuels(In my case charcoal and Oak Planks)
4. Make your Bakery produce bread
5. Wait for the bread to finish without the baker having any fuel

### Logs

- latest.log: https://pastebin.com/UQ52VRrc
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by dhouck** [comment]
I also see this for the dyer wanting green dye.  My guess is that the automatically-known recipes aren't coded in a way to need fuel for some reason; the stone smelter still needs fuel.

**Comment by Raycoms** [comment]
Was solved afaik
