### ISSUE TITLE
Tinker compatibility server crash on login

### ISSUE THREAD

**Issue by patgoull** [ldtteam/minecolonies#7176]
### Prerequisites

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version:  0.14.189-BETA
- Structurize Version: 0.13.174-ALPHA
- Related Mods and their Versions: TConstruct-1.16.5-3.0.3.144

## Expected behavior
Server doesn't crash when logging

## Actual behavior
The server crash on login. The last working version for us is minecolonies-0.14.181-ALPHA-universal.

## Steps to reproduce the issue

Not sure. It seems that one knight at some point had a tinker sword equiped. A miner also used a pickaxe. I tried to removed all tinker tools from the colony (including wharehouse) and the crash still happens. 

### Logs

- latest.log: https://gist.github.com/patgoull/14ec89fa046967c981b698941f8857bb
- debug.log: https://gist.github.com/patgoull/d2c5c6efe8db36f41b45a14aad781bde

## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by vroni92** [comment]
Update Tinker's, they have changed some stuff on their end, our compat now only works with the newer version.

**Comment by patgoull** [comment]
I didn't notice the new tinker versions. I feel kinda bad. Thanks for the quick response.
