### ISSUE TITLE
builderinfiniteresources: worker stop working

### ISSUE THREAD

**Issue by Waxime64** [ldtteam/minecolonies#7187]
### Prerequisites 

- [ X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: mohist-1.16.5-618-server.jar
- MineColonies Version:minecolonies-0.14.197-ALPHA-universal.jar
- Structurize Version:structurize-0.13.175-ALPHA-universal.jar
- Related Mods and their Versions:

## Expected behavior
When my builder start to build a new Structure with builderinfiniteresources=true in creative. I expect all my builder build non stop without any question: Ressource/Tool/Food ....

## Actual behavior
When my builder start to build a new Structure with builderinfiniteresources=true in creative. They didn't start. I have to change the value builderinfiniteresources=false for my builder start and after rechange to builderinfiniteresources=true and after that no problem

## Steps to reproduce the issue

1. Change the value builderinfiniteresources = true
2. Create a new colonies in creative
3. Start to build
4. ...... Builder wait in working mode without question
5. Change value to builderinfiniteresources = false
6. Wait 30 secondes
7. Builder start to work
8. Change the value to builderinfiniteresources = true
9. Builder build without question

**Comment by Raycoms** [comment]
Yeah this setting is not supported anymore and will be removed in the future. In creative there is no need for a builder, just paste buildings right away or just fulfill the necessary res.

**Comment by Waxime64** [comment]
But in my case, I want to use my builder for build my Spawn. I not really want to play minecolonies this time, only use it and create some live. And after I switch to survival and desactivate this feature for playing really.

**Comment by Raycoms** [comment]
Just paste the things then with the build tool directly.

**Comment by Waxime64** [comment]
But in this case, my city isn't really live. Yes I have the building present, but without NPC

**Comment by Raycoms** [comment]
the right paste button will place the building correctly with citizens into it. The left doesn't. With a colony np

**Comment by Waxime64** [comment]
Oh thanks
Last time I try this option my main building block isn't work. Now everything fine
