### ISSUE TITLE
Game crashes after giving tools to lumberjack. (using Dynamic trees)

### ISSUE THREAD

**Issue by AkGamerRo** [ldtteam/minecolonies#7188]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.14.197-ALPHA-universal

### Logs

- latest.log: https://gist.github.com/AkGamerRo/a2a932bdb26b9d8370bcf0753fbf36da (included both crash report and latest log)

## Steps to reproduce the issue / details

1.Found colony
2.Build forester (either with builder in survival or wand in creative) (near dynamic trees)
3.Hire Lumberjack
4.Give tools to worker
5.Game crashes.
Just reporting the issue. 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by vroni92** [comment]
I'll be working on this tomorrow. For now you can downgrade DynamicTrees, Beta8 was working.

**Comment by AkGamerRo** [comment]
All DynamicTrees versions that i used(BETA10, BETA12 and after your suggestion BETA8) yield the same result for me, however i found that DynamicTrees tree seeds(acorns and such) were not present in the sapling replanting tab.
