### ISSUE TITLE
Knights have no aggression radius/Make guards smarter [$5]

### ISSUE THREAD

**Issue by generilisk** [ldtteam/minecolonies#719]
### Minecolonies version

version 0.6.2991

### Expected behavior

- Knights seek and attack enemies

### Actual behaviour

- Knights walk their patrol route. If they are actively touching an enemy, they will attack it, but make zero effort to move toward the enemy.

### Steps to reproduce the problem

1. Assign a guard to "knight."
2. Be sad

**Comment by marvin-bitterlich** [comment]
@Raycoms wasn't there a pr for this?
