### ISSUE TITLE
Medieval Oak Tavern Level 3 is broken, prevent upgrades

### ISSUE THREAD

**Issue by cheshyrp** [ldtteam/minecolonies#7194]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.198-ALPHA-universal
- Structurize Version: 0.13.175-ALPHA-universal
- Related Mods and their Versions: Mineshafts & Monsters modpack, v1.3.2

## Expected behavior
The level 3 medieval oak tavern should be completed successfully, allowing upgrades to level 4 and 5.

## Actual behavior
The builder places two illegal item frames outside of the tavern, floating in mid-air. As this isn't valid placement, they immediately break, causing the tavern to require repairs. It's impossible to repair it however, as this schematic isn't valid.

[Before](https://i.imgur.com/rdVBfCa.jpg)
[After](https://i.imgur.com/ky8xweN.jpg)

## Steps to reproduce the issue

1. Build a level 2 Medial Oak Tavern
2. Upgrade to level 3
3. Watch as the item frame outside the front door breaks

### Logs

Not applicable

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
#5006 @carlansor

**Comment by cheshyrp** [comment]
Why was this closed? #5006 is far to cryptic to provide any information to me. The fact is this tavern is broken, whether you believe me or not.

**Comment by carlansor** [comment]
this was already fixed, will rescan again anyways

**Comment by baden27** [comment]
Just dropping by to note that this is still a bug - after more than a year.
Minecraft Version: 1.18.2
MineColonies Version: minecolonies-1.18.2-1.0.636-BETA
Structurize Version: structurize-1.18.2-1.0.379-BETA
Related Mods and their Versions: Modpack: All the Mods 7-0.3.18
