### ISSUE TITLE
Ticking entity involving dynamic trees

### ISSUE THREAD

**Issue by lebanni** [ldtteam/minecolonies#7196]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.14.200-ALPHA-universal.jar
- Structurize Version: structurize-0.13.175-ALPHA-universal.jar
- Related Mods and their Versions:
DynamicTrees-1.16.5-0.10.0-Beta14.jar
DynamicTreesPlus-1.16.5-0.1.0-Beta8.jar
DynamicTreesAtum-1.16.5-1.1.0.jar
DynamicTreesTerraForged-1.16.5-1.0.0.jar

## Expected behavior

The server doesn't crash.

## Actual behavior

The server crashes when the client connects

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log:  https://gist.github.com/lebanni/0906ea5005b7c9f5e9eff5a811418eaa
- crashlog:  https://gist.github.com/lebanni/4a3f75813c0344cb4294c83b4c2791fd

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
downgrade to beta8 for now. They changed the API, so we have to update that soon. Another issue is open already for that
