### ISSUE TITLE
Glassblowers Hut Creative placement not working

### ISSUE THREAD

**Issue by VampireTechnologyLord** [ldtteam/minecolonies#7199]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.14.204-ALPHA-universal.jar
- Structurize Version: structurize-0.13.175-ALPHA-universal.jar
- Related Mods and their Versions: none

## Expected behavior

Instant placement of the glassblowers hut

## Actual behavior

The glassblowers hut block is placed, but it creates the construction tape and the building itself doesn't get's constructed. If you right click on the hutblock it says: `This block is missing is respective building. Try restarting or loading a backup`. (Both don't work)

## Steps to reproduce the issue

1. Get the glassblowers hutblock
2. Preview any level ingame and click `Instantly Places the strcucture in the world, as if constructed by a builder`

### Logs

- latest.log:  https://gist.github.com/VampireTechnologyLord/e7dbfdf022e0f7ce429cf86215fee810
- crashlog:  none

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by VampireTechnologyLord** [comment]
btw.: it works for all the other huts ive tried in that session just fine...

**Comment by dhouck** [comment]
Doesn't work for forester for me: https://gist.github.com/dhouck/1cab24ef9668ad4016f3e525f2724643

**Comment by VampireTechnologyLord** [comment]
it also won't work with placing the hutblock normally (with buildtool and then the checkmark) OR instantly placing (without buildtool)

**Comment by dhouck** [comment]
If I had to guess I'd say this is caused by https://github.com/ldtteam/minecolonies/commit/402b2ba61848297c80514b4a6ddd66f34cdeb944 since it did work on the item list module.  I'll actually check that later when I'm more available.

**Comment by dhouck** [comment]
Yep; works in 201-BETA but not 202-ALPHA

**Comment by dhouck** [comment]
Also affects smeltery.

**Comment by Raycoms** [comment]
fix pushed
