### ISSUE TITLE
Crash on opening 

### ISSUE THREAD

**Issue by VampireTechnologyLord** [ldtteam/minecolonies#7200]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.14.204-ALPHA-universal.jar
- Structurize Version: structurize-0.13.175-ALPHA-universal.jar
- Related Mods and their Versions: none

## Expected behavior

Open settings-page at builders hutblock

## Actual behavior

Crash of the game when trying to open settings tab. All other tabs of the builder and the setting tabs of other huts are working properly. After clicking the settings-tab, the game freezes and then crashes with error code -1 and an `ticking screen` error.

## Steps to reproduce the issue

1.  Build Builders hut
2.  Open Menu
3.  Go to settings page

### Logs

- latest.log:  https://gist.github.com/VampireTechnologyLord/e7dbfdf022e0f7ce429cf86215fee810
- crashlog:  https://gist.github.com/VampireTechnologyLord/988d0ab5620409c64bb2862d3296f376

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by dhouck** [comment]
It looks like it's failing to find something from the Rats mod.  Did you recently update that?

**Comment by VampireTechnologyLord** [comment]
i've tried updating it, but it still don't works... 😭

**Comment by Raycoms** [comment]
hotfix pushed

**Comment by dhouck** [comment]
Still seeing this on 205-alpha.  All the other tabs work.

https://gist.github.com/dhouck/ee0ff161a9fb98c08a4fdfefc23d3689

**Comment by dhouck** [comment]
So are two other people in Discord; one of their logs:
https://pastebin.com/vxSZRwc9

**Comment by Raycoms** [comment]
Another hotfix pushed
