### ISSUE TITLE
Undertaker AI Issue

### ISSUE THREAD

**Issue by InfernoNeko** [ldtteam/minecolonies#7201]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.16.5
- MineColonies Version: [0.14.155-BETA]

### Logs

- latest.log: 
![error](https://user-images.githubusercontent.com/85462910/120943105-defa4780-c6fa-11eb-9f46-52d62b5e3b49.JPG)
[2021-05-18-1.log.gz](https://github.com/ldtteam/minecolonies/files/6605109/2021-05-18-1.log.gz)

## Steps to reproduce the issue / details

Just reporting the AI issue. 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
can you upload this log to pastebin or gist? And, I couldn't find the exception in this log.

**Comment by Raycoms** [comment]
I need another log, else I can't do anything.

**Comment by Raycoms** [comment]
Just saw 155 beta, this was fixed already
