### ISSUE TITLE
Pathfinding: blocks which are under water have too low pathing cost, which makes NPCs get stuck while they are trying to cross a body of water

### ISSUE THREAD

**Issue by Bashkaaaa** [ldtteam/minecolonies#7207]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1,16,5
- MineColonies Version: minecolonies-0.14.206-ALPHA-universal.jar
- Structurize Version: structurize-0.13.175-ALPHA-universal.jar
- Related Mods and their Versions: Modpack: https://www.curseforge.com/minecraft/modpacks/ttw-community-server-pack/relations/dependencies

## Expected behavior
Colonists should avoid water while pathfinding since they can't swim too well. 

## Actual behavior
When citizens have to path to a location on the other side of a body of water, they will choose to walk to the bottom of the lake, rater than walk around it. This gets them stuck in the middle of it. I'm only guessing here, but I am assuming that they have an oxygen meter and when walking on the bottom of the lake depletes their oxygen, they pop to the surface and get stuck, because they lose the previously selected path. The only way to to get them out of there is to recall them in their hut. 

![image](https://user-images.githubusercontent.com/84290349/121101390-0be25380-c7fc-11eb-92ae-1221258ee9eb.png)
![image](https://user-images.githubusercontent.com/84290349/121101956-22d57580-c7fd-11eb-8acf-7a70aebb2831.png)

## Steps to reproduce the issue

It's really hard for me to give very precise STR here, the only way to actually test it would be to verify the pathing cost for blocks under water and manipulate this value to be able to observer AI behavior. I don't have the skills and knowledge to do this.

### Logs

N/A

### Notes
We are not using the latest version, because the mod updates sometimes several times a day and it would be problematic to update the modpack every time a new version comes out. I know that there were few more alpha releases since the one we are using was published and we will be updating again tomorrow, but I checked the patch notes and none of them mentioned any changed to AI pathfinding, so this issue is more likely still valid. That saying, I will verify it again after the next update.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
can you send us this world?

**Comment by someaddons** [comment]
`/mc colony export 1`  <- replace 1 with the actual id, can find it with /mc whereami  this way you get some nice cut-down zip to send

**Comment by Bashkaaaa** [comment]
@someaddons oh my, thank you! the whole world is 80GB and it would be really hard to send it over. I made the export zip
[colony40Export.zip](https://github.com/ldtteam/minecolonies/files/6619963/colony40Export.zip)

FYI: since I reported this issue, I added some more grass paths around, which made this happen less often, but it still happens

**Comment by someaddons** [comment]
should be fixed with rays update today
