### ISSUE TITLE
Ticking Entity Crash with MineColonies and Dynamic Trees after using suggested fix

### ISSUE THREAD

**Issue by AndrewEllen** [ldtteam/minecolonies#7208]
### Prerequisites 

- [x]  I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.209-ALPHA
- Structurize Version: 0.13.177-ALPHA
- Related Mods and their Versions: DynamicTrees-1.16.5-0.10.0-Beta14 and DynamicTrees-1.16.5-0.10.0-Beta8

## Expected behavior

No crash would happen

## Actual behavior

The game crashes from a ticking entity, it appears that the lumbar jack doesn't know how to handle saplings in dynamic trees from the crash.

## Steps to reproduce the issue

1. Build a forester hut
2. wait
3. crash

### Logs

- latest.log: N/A
- crashlog: https://gist.github.com/AndrewEllen/429b9c046bf856c817a69f1c1931013d

### Notes

I found an issue that is pretty much the exact same issue I have from a few days ago however the issue was closed and it said to use version BETA 8 to fix it. This hasn't fixed it and it's broken on both versions it looks like. I don't know where to go from here other than to submit another bug report.

**Comment by Raycoms** [comment]
Please search for recent issues before posting. Roll back to beta8, and await new dynamic tree release

**Comment by AndrewEllen** [comment]
> Please search for recent issues before posting. Roll back to beta8, and await new dynamic tree release

I did role back to beta 8. The issue isn't fixed
