### ISSUE TITLE
Citizens Freeze, stutter and move choppily beyond 16 blocks

### ISSUE THREAD

**Issue by j3553a** [ldtteam/minecolonies#721]
### Minecolonies version

version 0.6.3125

### Expected behavior

- Citizens to function within loaded chunks on a forge server

### Actual behaviour

- Citizens freeze at about 16 blocks from a player. They will stutter and move extremely slowly beyond that mark. I have to basically be holding their hand and watching them to get them to do anything

### Steps to reproduce the problem

1. Be on a forge minecraft server
2. Make a colony
3. Watch as citizens freeze beyond 16 blocks
4. Profit

**Comment by Raycoms** [comment]
are you using sponge?


2017-03-20 21:29 GMT-03:00 jessejohn01 <notifications@github.com>:

**Comment by Raycoms** [comment]
You have to configure that in sponge. Not our fault.

**Comment by gd71** [comment]
for the posterity
disable sponge entity-activation-range for minecolonies if you want citizens to continue their life when players are at far distance
```
            minecolonies {
                defaults {}
                # Set to false if you want mod to ignore entity activation rules and always tick.
                enabled=false
                entities {}
            }
```

**Comment by j3553a** [comment]
Thank you guys. I didn't realize it was a sponge issue. The solution worked.
