### ISSUE TITLE
Cant hire new citizens even thought barracks has room for guards

### ISSUE THREAD

**Issue by starfall18** [ldtteam/minecolonies#7210]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.16.5
- MineColonies Version:0.14.182-ALPHA-universal
- Structurize Version:0.13.174-ALPHA-universal
- Related Mods and their Versions: ATM6 modpack version 1.6.7

## Expected behavior

 I should be able to hire additional guards even if the houses are full but guard posts arent, as they sleep in the guard towers.

## Actual behavior

 I cant hire more citizens if they are all employed elsewhere and housing has reached its current housing limit (can build more houses and upgrade them though) even though barracks has room for more soldiers. Firing a citizen from another job that takes up housing space will make me able to hire the fired citizen as a guard and then recruit another citizen to fill up the empty housing slot. If the guards are set to auto hire, they will hire new guards as i recruit the new citizens. However, as soon as i hire citizen to work where i had fire one earlier from, the cap is reached and i cant hire more guards, with a popup again stating that i dont have enough housing.

-
## Steps to reproduce the issue

1. build a tavern, and a house, and a builder, and other working areas till the housing limit is reached for working citizens (like lvl 1 tavern + lvl 2 house = 6 working spaces that arent guard towers or barracks towers)
2. Then build barracks, and turn children being born off. After barracks is finished and you have built a couple of barrack towers for new knights, try recruiting new citizens from the tavern.
3. The citizens in the tavern cant join with a popup in chat saying that you dont have enough housing for additional citizens even though there is room in the barracks.

### Logs

- latest.log: 
- crashlog: 

### Notes

You can still hire guards when you fire a citizen from his job to have an unemployed citizen to be employed at the barracks, which then allows you to hire another citizen at the tavern. But why do i have to fire citizens from their jobs that they have been working at so i could hire more guards and then fire the guard that was hired from the first unemplyed citizen to be rehired back at his old job. This shuffling seems rather annoying and im sure that it is a bug and not working as intended.
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
This is not a bug.  When you recruit someone from the tavern, they start out as an unemployed citizen and thus require a normal bed space -- they cannot use any space in the barracks because they're not a guard.

If you hire one of your existing citizens (who already have a regular bed) as a barracks guard then that will free up a house/tavern bed space and this will allow you to recruit someone (and you can then assign them to the barracks afterwards if there's another free space there, allowing you to recruit someone else).
