### ISSUE TITLE
Barracks Placeholder causes x-ray

### ISSUE THREAD

**Issue by dhouck** [ldtteam/minecolonies#7211]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.210-Alpha
- Structurize Version: 0.13.177-Alpha
- Related Mods and their Versions:

## Expected behavior

When previewing a structure that includes a barracks placeholder, or when such a structure is actually placed in the world (eg. by creative mode paste outside colony borders), you can see the blocks behind the barracks tower placeholder

## Actual behavior

![image](https://user-images.githubusercontent.com/524925/121134366-ec95f700-c7f8-11eb-82a0-a2a0a3fc4cfa.png)

## Steps to reproduce the issue

1. Grab a barracks hut block
2. Preferably away from any colony, preview a barracks that includes barracks towers inside (eg. Fortress, Medieval Birch Alternative)
   a. Optionally, if not in a colony border, use the creative mode paste (clipboard) button to place the barracks.  Outside a colony the placeholder will not turn into a regular barracks hut block.  Probably applies to the other creative mode copy button (two papers) always, but didn't test this
3. See behind the block, possibly into the ground depending on what's behind the block

### Logs

Visual issue, no logs

### Notes

Found while debugging https://github.com/ldtteam/minecolonies/issues/5006#issuecomment-856323324

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Yes, this is not a survival block and not obtainable in survival, it's builders only.
