### ISSUE TITLE
JEI plugin conflicts with the Integrated Dynamics's facede

### ISSUE THREAD

**Issue by wasdspace** [ldtteam/minecolonies#7214]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.210-alpha
- Structurize Version: 0.13.177-alpha
- Related Mods and their Versions: IntegratedDynamics-1.16.5-1.8.4

## Expected behavior

The log file does not have any errors.
## Actual behavior

The Integrated Dynamics's facede seems to conflict with minecolonies' JEI plugin, the log file shows too many messages indicating the existence of errors.

## Steps to reproduce the issue

1. Running game with minecolonies and integrated dynamics.
2. No exceptions during loading of the game.
3. When entering the world, it will take a minute to two minutes longer than before, and the log file will start to swell.

### Logs

- latest.log: It's too big.
- crashlog: Too big.

### Notes

Maybe the Integrated Dynamics's facade should be blacklisted. Sorry for the machine translation.
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Upload the log please as a gist then.

**Comment by wasdspace** [comment]
[latest.log](https://github.com/ldtteam/minecolonies/files/6616070/latest.log) It starts at about 12,000 lines or so.
There is no crash file, I made a mistake, sorry.

**Comment by uecasm** [comment]
That's mostly other mods defining broken recipes that we then try to interpret.  But I'll look into it and see if we can ignore that sort of thing.
