### ISSUE TITLE
TC compat issue (?): vanilla fuel types not visible in fuel selection UI

### ISSUE THREAD

**Issue by Bashkaaaa** [ldtteam/minecolonies#7217]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.14.210-ALPHA-universal.jar
- Structurize Version: structurize-0.13.177-ALPHA-universal.jar
- Related Mods and their Versions:  TC: TConstruct-1.16.5-3.0.4.171.jar (latest), Modpack: https://www.curseforge.com/minecraft/modpacks/ttw-community-server-pack

## Expected behavior
Player should be able to select any fuel source available in their game for furnaces.

## Actual behavior
When accessing fuel selection UI, the only available options are molten blaze and various tinkers wood blocks. Vanilla fuel sources are missing from the UI

![image](https://user-images.githubusercontent.com/84290349/121223904-4db8db80-c888-11eb-9608-d256d9b5b99d.png)
![image](https://user-images.githubusercontent.com/84290349/121223947-5ad5ca80-c888-11eb-975d-dc252cf868db.png)

## Steps to reproduce the issue

N/A

### Logs

N/A

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Can you send us your startup log?

**Comment by Bashkaaaa** [comment]
Sure!
https://gist.github.com/Bashkaaaa/1660625b473332de6d09681823389b98

**Comment by Raycoms** [comment]
@gattsuru or @uecasm any idea?

**Comment by Bashkaaaa** [comment]
Heyo! Sorry for bothering, it seems to have been a client-side glitch which happened on my a few other clients on my server. it worked just fine for other players, so we rebooted the server and the clients and it's all good now.
