### ISSUE TITLE
Builder Refuses to Build with Farmland

### ISSUE THREAD

**Issue by WenXin20** [ldtteam/minecolonies#722]
### Minecolonies version

version 0.6.3125-1.10.2

### Expected Behavior

- To build the custom decoration with the farmland included.
- He should place dirt, then create the dry farmland instead of trying to place wet farmland and freezing from that.

### Actual Behavior

- Builder freezes after detecting wet farmland and refuses to build anything.

### Steps to reproduce the problem

1. Create a custom decoration that has wet farmland in it.
2. Request the builder to build it
3. Builder Freezes

### Latest.log

[Gist](https://gist.github.com/WenXin20/b715b466835404cf8d5fa13d24fba443)
This is what is spammed in the log.

**Comment by WenXin20** [comment]
I've also noticed that the same seems to happen with the grass path, fire, and the purple nether portal blocks.

**Comment by marvin-bitterlich** [comment]
@Raycoms any news?

**Comment by Raycoms** [comment]
fixed
