### ISSUE TITLE
Instant Build

### ISSUE THREAD

**Issue by CTH999** [ldtteam/minecolonies#7220]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: minecolonies-0.14.213-ALPHA-universal
- Structurize Version: structurize-0.13.177-ALPHA-universal

## Problem description
I looked, no instant-build feature.

### Notes or related things
So, versions ago (Not sure how long, I just now got it working on 1.16.4, java didin't want to work. Anyways...), there was a feature to make the builder build without needing recourses. Now, being my lazy self, that sounded perfect, so I always made that "true". Well, that option is gone!

So, this is kind of a feature request. Could you add that in? And mb a "Doesn't require food" option (Which also makes the bakery useless?), and maybe make these two things a game-rule, not a config? Thanks!
---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Feature requests go here https://github.com/ldtteam/minecolonies-features/issues, and you can instapaste buildings in creative mode without even needing a builder

**Comment by CTH999** [comment]
> Feature requests go here https://github.com/ldtteam/minecolonies-features/issues, and you can instapaste buildings in creative mode without even needing a builder

lemme guess, that insta-paste is why you removed that config? Well, that solves that issue!
