### ISSUE TITLE
Cook cannot be build 0.14.204-ALPHA

### ISSUE THREAD

**Issue by gotoxy** [ldtteam/minecolonies#7221]
When placing a cook with the build tool or by itself and right click it, i get that error: 

This block is missing its respective building, try restarting or loading a backup!

I see the cook item on the floor but i still have it in my inventory. If I destroy the block, i get lots of error on my server and one line say: 

[20:33:52] [Server thread/INFO] [minecolonies/]: Colony 1 - removed AbstractBuilding BlockPos{x=984, y=63, z=-129} of type cook

And the cook item is removed from the ground. so its duplicate itself. 

MineCololines: 0.14.204-ALPHA
Structurize 0.13.175-ALPHA

From AlltheMods6 on curseforge

**Comment by Raycoms** [comment]
Can you please send us th elog?

**Comment by gotoxy** [comment]
i got an other reply on discord telling me that 204 had that issue and is was solve in 215. So i updated it and it works as it should.

Sorry, im using all the mods 6 and saddly, the new release wasnt update to date at all.

Ill keep in mind to check last version next time i post a bug.
