### ISSUE TITLE
JEI not displaying custom datapack outputs from sifter hut correctly.

### ISSUE THREAD

**Issue by Electrofried** [ldtteam/minecolonies#7223]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.215-ALPHA
- Structurize Version: 0.13.177-ALPHA
- Related Mods and their Versions:

## Expected behavior

Sifter hut should display output of custom recipes added via datapack correctly.

## Actual behavior

Sifter is not displaying the outputs of custom datapack recipes/loot tables in the JEI section for the sifter hut.
The outputs are registered as looking up the "recipe" by pressing "r" to look up recipes  for the output will bring up the sifter hut in JEI and show the input block and mesh correctly. However it will fail to display the outputs in the section below as seen in the image. 

![sifter fail display](https://user-images.githubusercontent.com/27886155/121305460-f165c280-c940-11eb-88aa-b9759fd8202a.png)

## Steps to reproduce the issue

1.  Download the modpack [ModColonies from curseforge](https://www.curseforge.com/minecraft/modpacks/modcolonies) would be the simplest way to test this.
2. look up the recipe for the item "Iron Ore Chunk" and flip over to the sifter hut in JEI
3.  No outputs are displayed.

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
Where in the modpack are you adding custom sifter recipes?

**Comment by Electrofried** [comment]
using openloader to load the datapack, you will find them in the .\openloader\data\modcolonies\data\modcolonies folder

**Comment by uecasm** [comment]
Ah, I think I know what this is.  Unfortunately the method currently being used to load loot tables for the JEI integration is not compatible with external datapacks on servers.  (It's not completely unsolvable, but it's Complicated™ due to some Minecraft internals.)

~~It should work in single player, and~~ you can workaround it by writing a minimal jar mod and putting your datapack inside that instead.
