### ISSUE TITLE
{ 1.16.5 } Unable to get past a Header error on client reconnect to a server 

### ISSUE THREAD

**Issue by ACrazyD** [ldtteam/minecolonies#7229]
### Prerequisites 

- [X ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5 
- MineColonies Version:  0.14.215 ALPHA
- Structurize Version: 0.13.177 ALPHA
- Related Mods and their Versions: (Theres a lot, we have done the testing already)

abnormals_core-1.16.5-3.1.1.jar
abnormals_delight-1.16.5-1.1.1.jar
additional_lights-1.16.4-2.1.3.jar
AdLods-1.16.4-4.1.5.1-build.0118.jar
AkashicTome-1.4-16.jar
alexsmobs-1.10.1.jar
allurement-1.16.5-1.2.0.jar
AppleSkin-mc1.16.2-forge-1.0.14.jar
appliedenergistics2-8.3.1.jar
Aquaculture-1.16.5-2.1.19.jar
architectury-1.17.20-forge.jar
Artifacts-1.16.5-2.8.4.jar
atmospheric-1.16.5-3.1.0.jar
autooredictconv-1.16.4-16.1.10.jar
AutoRegLib-1.6-49.jar
autumnity-1.16.5-2.1.1.jar
Babel-1.0.5.jar
BackTools-1.16.5-10.1.0.jar
BetterCaves-Forge-1.16.4-1.1.2.jar
BetterMineshafts-Forge-1.16.4-2.0.3.jar
BetterStrongholds-1.16.4-1.1.jar
BiomesOPlenty-1.16.5-13.1.0.471-universal.jar
Bookshelf-1.16.5-10.1.11.jar
Botania-1.16.5-416.jar
BotaniaAdditionsMC1.16.4-1.0.4.jar
botanicalmachinery-1.16.4-0.4.1.jar
byg-1.2.9.jar
carryon-1.16.5-1.15.5.15.jar
cc-tweaked-1.16.4-1.96.0.jar
charm-forge-1.16.5-2.3.2.jar
chiselsandbits-0.3.4-RELEASE.jar
chunkloaders-1.1.7-mc1.16.5.jar
citadel-1.6.3.jar
cloth-config-4.11.26-forge.jar
CodeChickenLib-1.16.4-3.5.1.408-universal.jar
cofh_core-1.16.4-1.2.1.jar
collective-1.16.5-2.26.jar
comforts-forge-1.16.5-4.0.0.4.jar
commands_plus_1.0.jar
constructionwand-1.16.5-2.2.jar
Controlling-7.0.0.22.jar
CookingForBlockheads_1.16.5-9.3.2.jar
CraftingTweaks_1.16.5-12.2.1.jar
CraftTweaker-1.16.5-7.1.0.313.jar
create-mc1.16.5_v0.3.1c.jar
create-stuff-additions1.16.5_v1.0.3.jar
create_addon_v1.jar
createaddition-1.16.5-20210517a.jar
CreativeCore_v2.2.0_mc1.16.5.jar
CTM-MC1.16.1-1.1.2.6.jar
Cucumber-1.16.4-4.1.9.jar
cuneiform-1.16.3-1.2.5.jar
curios-forge-1.16.5-4.0.5.2.jar
curiousjetpacks-1.4c-1.16.5.jar
decorative_blocks-1.16.4-1.7.2.jar
enchantedbookredesign-3.3-1.16.4.jar
EnchantmentDescriptions-1.16.5-7.0.8.jar
endergetic-1.16.4-3.0.0.jar
EnderStorage-1.16.4-2.7.1.166-universal.jar
ensorcellation-1.16.4-1.2.0.jar
environmental-1.16.5-1.0.0.jar
expandedstorage-3.0.5+1.16.3.jar
extremeSoundMuffler-3.12_Forge-1.16.5.jar
fairylights-4.0.5-1.16.5.jar
FarmersDelight-1.16.5-0.4.3.jar
FastLeafDecay-v25.jar
findme-1.16.3-2.2.0.0.jar
ForgeEndertech-1.16.4-7.1.0.0-build.0075.jar
ForgivingVoid_1.16.5-5.2.1.jar
ftb-gui-library-1605.2.1.41-forge.jar
ftb-library-forge-1605.3.1-build.10.jar
ftb-ultimine-forge-1605.2.2-build.4.jar
gates-1.7.1.jar
gravestone-1.16.5-1.0.4.jar
guardvillagers-1.16.5.1.2.4.jar
Hats-1.16.5-10.3.0.jar
horse_colors-1.16.5-1.6.0.2.jar
horse_tack-3.0-1.16.3release.jar
iChunUtil-1.16.5-10.4.0.jar
ImmersiveEngineering-1.16.5-5.0.0-135.jar
ImmersivePetroleum-1.16.5-3.3.0-4.jar
immersiveposts-1.16.5-4.1.0.jar
industrial-foregoing-1.16.5-3.2.13-4.jar
invtweaks-1.16.4-1.0.1.jar
IronJetpacks-1.16.4-4.2.0.jar
item-filters-1605.2.4-build.30-forge.jar
ItemPhysic_v1.4.18_mc1.16.5.jar
jei-1.16.5-7.7.0.100.jar
jeiintegration_1.16.5-7.0.1.15.jar
JEITweaker-1.16.5-1.0.1.27.jar
JEPB-1.0.0.jar
journeymap-1.16.5-5.7.1.jar
JustEnoughResources-1.16.5-0.12.1.114.jar
kotlinforforge-1.12.1-obf.jar
LibX-1.16.3-1.0.76.jar
light-overlay-5.8.0.jar
little_critters-0.0.1.jar
mcw-doors-1.0.3-mc1.16.5.jar
mcw-fences-1.0.0-mc1.16.5.jar
mcw-furniture-2.0.1-mc1.16.5.jar
mcw-paintings-1.0.1-mc1.16.5.jar
mcw-roofs-2.0.1-mc1.16.5-4.jar
mcw-trapdoors-1.0.2-mc1.16.5.jar
mcw-windows-1.0.3-mc1.16.5.jar
mdecore-1.16.4-16.1.0.jar
mgui-1.16.5-3.2.0.jar
minecolonies-0.14.215-ALPHA-universal.jar
moreminecarts-1.3.8.jar
morevillagers-FORGE-1.16.5-1.5.1.jar
Morpheus-1.16.5-4.2.70.jar
MouseTweaks-2.14-mc1.16.2.jar
MythicBotany-1.16.4-1.3.15.jar
NaturesCompass-1.16.5-1.9.0.jar
occultism-1.16.5-1.2.2.jar
pamhc2crops-1.16.3-1.0.2.jar
pamhc2foodcore-1.16.3-1.0.2.jar
pamhc2foodextended-1.16.3-1.0.2.jar
pamhc2trees-1.16.3-1.0.1.jar
Patchouli-1.16.4-51.jar
performant-1.16.2-5-3.66m.jar
personality-1.16.5-1.0.2.jar
Placebo-1.16.4-4.5.0.jar
Psi 1.16-94.jar
psipherals-1.4.0.jar
Quark-r2.4-312.jar
QuarkOddities-1.16.3.jar
refinedpipes-0.5.jar
savageandravage-1.16.5-3.1.0.jar
SimpleDiscordRichPresence-1.16.4-1.3.5.jar
smallships-1.16.5-1.8.5.jar
SolarFluxReborn-1.16.3-16.2.5.jar
sophisticatedbackpacks-1.16.4-2.5.0.271.jar
stoneholm-1.2.2.jar
StorageDrawers-1.16.3-8.2.2.jar
structure_gel-1.16.5-1.7.7.jar
structurize-0.13.177-ALPHA-universal.jar
supermartijn642configlib-1.0.6-mc1.16.jar
supermartijn642corelib-1.0.5-mc1.16.5.jar
swingthroughgrass-1.16.4-1.5.3.jar
tellme-forge-1.16.4-0.9.1.jar
terraincognita-1.16.3-1.6.4.2.jar
tetra-1.16.5-3.11.1.jar
tetranomicon-1.2.jar
tetrapak-0.2.1.jar
the-conjurer-1.16.4-1.0.13.jar
The_Undergarden-1.16.5-0.5.1.jar
theoneprobe-1.16-3.1.4.jar
thermal_cultivation-1.16.4-1.2.0.jar
thermal_expansion-1.16.4-1.2.0.jar
thermal_foundation-1.16.4-1.2.0.jar
thermal_innovation-1.16.4-1.2.0.jar
thermal_locomotion-1.16.4-1.2.0.jar
titanium-1.16.5-3.2.8.3-9.jar
torchmaster-2.3.7.jar
TrackAPI-1.16.4-forge-1.2.1.jar
trashcans-1.0.10-mc1.16.5.jar
Undergarden-Tetra Patch-1.2.1.jar
UniversalModCore-1.16.4-forge-1.0.1.jar
upgrade_aquatic-1.16.5-3.1.0.jar
valhelsia_core-16.0.9.jar
valhelsia_structures-1.16.5-0.1.2.jar
villagernames_1.16.5-2.9.jar
villagertools-1.16.5-1.0.0.jar
Waystones_1.16.5-7.6.2.jar
YungsApi-1.16.4-Forge-6.jar
YungsExtras-Forge-1.16.4-1.0.jar

## Expected behavior

To beable to play past one login

## Actual behavior

The first time the user logs into the server there is no issue, but as soon as that user logs out and attempts to log in the error shows up kicking the player with a msg
" io.netty.handler.codec.decoderexception java.util.zip.dataformatexception incorrect header check "

## Steps to reproduce the issue

1.  run the same mods
2.  log into a server log out then attempt to log back in
3. 

### Logs

- latest.log:  (Server Side) - https://gist.github.com/AcrazyD/76bb5c643afc5e4cd8b383a5312f5cfc
- latest.log:  (Client Side, to big for gist - dropbox link is direct download) - https://www.dropbox.com/s/mu0dxi7n3wp6xc8/latest.log?dl=1
- crashlog:  (None, the server nor client fully crashes)

### Notes

We have tested every mod and the error occurs when running this mod, tho we are not 100% sure it this mods fault - we have been testing many versions and many mod configs trying to get it to work for the last 4 days.
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Can you try this mod: https://www.curseforge.com/minecraft/mc-mods/connectivity ?

**Comment by ACrazyD** [comment]
I can leave a zip for a curseforge install with the mods listed above

**Comment by Raycoms** [comment]
I mean, can you try to install the connnectivity mod and see if it solves it.

**Comment by ACrazyD** [comment]
Ya i was typing that and pressed enter as I saw the msg - it has been tested, and it looks to be promising - tho why that mod is not stated as one to be used is past me

**Comment by someaddons** [comment]
because its not a minecolonies issue, but technical general limitations you might hit depending on how much stuff the mods add in sum together
