### ISSUE TITLE
Builder suddenly stopped working

### ISSUE THREAD

**Issue by JijaSuu** [ldtteam/minecolonies#7230]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.155-BETA

### Logs

- latest.log: https://gist.github.com/JijaSuu/8e7f947a014da42d6c56e8c2a60b0c5f 

## Steps to reproduce the issue / details

Just reporting the AI issue. 

### Notes

I tried to build a tavern1, but when 80% was done, my builder just stopped building anything. Hiring another builder didn't help, they all have the same issue
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
That's over 50 versions out of date and there were several builder fixes since then, please update
