### ISSUE TITLE
Colonists AI not factoring flowing lava in their pathfinding

### ISSUE THREAD

**Issue by ClementJ18** [ldtteam/minecolonies#7236]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.14.198-ALPHA-universal.jar
- Structurize Version: structurize-0.13.175-ALPHA-universal.jar
- Related Mods and their Versions:

## Expected behavior
Colonists pathfind to their target around the flowing lava

## Actual behavior

When pathfinding to a target which has flowing lava in its way the AI does not seem to take the lava in account, I've lost 3 colonists so far, each time they died from onFire not too far from the lava wall, one even died straight in the ditch. The colonists that died were
* A builder who was trying to go from their hut to the building site
* Two archers who were, I assume, patrolling
![The lava wall](https://cdn.discordapp.com/attachments/321803083141087233/852984286000709662/unknown.png)
![Colonist grave in the ditch](https://cdn.discordapp.com/attachments/741531022872674314/852982698158194688/unknown.png)

## Steps to reproduce the issue

1. Create a builder hut
2. Create a build request
3. Place the lava wall as a direct obstacle between the two

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
I did a full checkup on this. Workers indeed do not path into lava, but they might path too close and get parts of their body on fire and die or similarly, get pushed by another citizen into lava that is walking closebye. To avoid anyone dieing from lava you'll have to make sure there are no open flows.
