### ISSUE TITLE
[1.16.5] Barracks Tower Shows no resources and crash if build is clicked

### ISSUE THREAD

**Issue by DarkGuardsman** [ldtteam/minecolonies#7237]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.14.169-ALPHA
- Structurize Version: structurize-0.13.173-ALPHA
- Related Mods and their Versions: Running direwolf20 1.16.5 v1.10.1, crash includes list of mods and versions

## Expected behavior

Opened Barracks Tower -> Selected builder -> Click Build Building Button -> Start Building

## Actual behavior

Opened Barracks Tower -> Selected builder -> Click Build Building Button -> Crashed

![image](https://user-images.githubusercontent.com/1477330/121762243-bb703c00-cb02-11eb-9679-e8ea58fa1b38.png)

## Steps to reproduce the issue

1. Upgrade barracks to level 2
2. Go to build barracks building
3. Open UI
4. Click build options
5. Notice list is empty of resources but ignore as half asleep
6. Select builder
7. Build Building to confirm

### Logs

- latest.log: https://gist.github.com/DarkGuardsman/91e9ffaac63a43f8c7c4afc7c09a0762
- crashlog: https://pastebin.com/j74r3Ku8x

### Notes

Crash is likely a result of the building specifying no resources to build. Building core was placed by a level 2 stone barracks and server was restarted shortly after upgrade finished. Restart doesn't seem to solve the problem.

Noticed all buildings have the same problem of losing build option data.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Update, you're about 50 versions out of date
