### ISSUE TITLE
Enchanter stops showing up as employed in enchanter hut and can not open worker GUI

### ISSUE THREAD

**Issue by Electrofried** [ldtteam/minecolonies#7238]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: forge-1.16.5-36.1.31
- MineColonies Version:  minecolonies-0.14.217-ALPHA
- Structurize Version: structurize-0.13.177-ALPHA
- Related Mods and their Versions: n/a

## Expected behavior

The enchanter should display as employed in the hut gui and allow players to open GUI.

## Actual behavior

Enchanter does not show in the hut GUI as employed and when right clicked the worker GUI does not open.

![unknown (2)](https://user-images.githubusercontent.com/27886155/121773827-fbe2bf00-cbc1-11eb-9443-0e96863d1149.png)

checking them with  the citizen info shows this:

![unknown (3)](https://user-images.githubusercontent.com/27886155/121773842-0e5cf880-cbc2-11eb-9ed4-2995312eb0da.png)

The town hall likewise does not show them.

![townhall](https://user-images.githubusercontent.com/27886155/121773864-2896d680-cbc2-11eb-9800-36d81e38eaf7.png)

If you kill them, then the issue is 'resolved' in that you can hire a new worker. But otherwise they simply continue to stand around the hut, go to sleep, eat, etc. They still respond to requests and perform crafting tasks. 

## Steps to reproduce the issue

1.  Look, I honestly have no idea. It has happened to a couple of players on my server right now and I can find no common link. Separate colonies, not performing the same tasks. This only started to happen after the update from 14.215 to 14.217. But I update the pack (ModColonies) / server near daily so I can not be 100% sure it is specific to this version and we did not notice it last version though I have had no reports before now.
2. Server restart does not resolve the issue, multiple clients have confirmed same behavior.  
3. 

### Logs

- latest.log:     [Server latest and debug logs](https://gist.github.com/Electrofried/33488b1c54ec28f30127a94d1866e74a)
- crashlog:  [Client latest and debug logs, good luck, the workers seem to be having some sort of rendering issue spamming console since the latest update that I should probably post a separate issue about. ](https://gist.github.com/Electrofried/d42e5af0d899bca420ca3cea5f34b566)

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Always the enchanter?

**Comment by Raycoms** [comment]
Leaving the colony for 10 minutes does not fix it or a server restart? This looks like one of these client/server desynch issues that are only fixed with a relog.

**Comment by Electrofried** [comment]
Not seen  or reported with any other huts so far. Tried server restart with no luck. I can try get them to leave the area for 10 mins and report back. 
To confirm, I can log in, with a totally separate client to the person reporting the issue, and experience the same behavior. 
I have an instance of the issue right now and can take a server snapshot if that would help, though the world is about 30GB in size....

**Comment by someaddons** [comment]
can you send us the colony/world in question? /mc colony export 1   (replace 1 with actual id) produces a slim export of the colony and world

**Comment by Electrofried** [comment]
I was talking to Ray in discord, this is linked to the other issue ( #7239 ) that I posted

Here is the requested export. 
[colony7Export.zip](https://github.com/ldtteam/minecolonies/files/6642430/colony7Export.zip)

**Comment by Raycoms** [comment]
I'll close this as this is due to #7239, and I'll happily get the world =D
