### ISSUE TITLE
Dark Oak Medieval House at Low Level citizen doesn't sleep

### ISSUE THREAD

**Issue by ncottrill** [ldtteam/minecolonies#7242]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version. (v410)
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:  1.16.5
- MineColonies Version:  0.14.210-alpha
- Structurize Version:  0.13.177-alpha
- Related Mods and their Versions:  

## Expected behavior

Level 2 medieval dark oak house has 2 beds - upstairs and on left hand side of the house, away from the house block. I would expect assigned NPCs to sleep - 1 in the bed upstairs and 1 in the bed in the left hand side of the house.

## Actual behavior

One assigned NPC sleeps in the bed upstairs. The other assigned NPC stands by the house block and does not sleep. He does not find the bed that is in the left side of the house.

I have attached a screenshot of the house and the unsleeping NPC.

## Steps to reproduce the issue

1.  Build a medieval dark oak house (not the alternate one, the regular one)
2.  Make it level 2. Assign 2 NPCs
3.  One sleeps upstairs at night in a bed. The other assigned NPC stands by the house block and does not sleep
![darkoak](https://user-images.githubusercontent.com/14022160/121791582-97673600-cba8-11eb-850c-639f7dee70cf.png)

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MatthiasMann** [comment]
I'm seeing the same behavior on level 4 medieval dark oak house on Minecolonies 0.14.219 - seems that the last arriving citizen can't find their bed and stands besides the hut block.

**Comment by Raycoms** [comment]
Is there maybe something hanging over the bed? something that might obstruct it? then it'd be #5006 which it most likely is

**Comment by MatthiasMann** [comment]
In the main house (the side with the hut block in it) on the top floor there is a upside down stair above the head end of the bed:
![2021-06-13_10 41 39](https://user-images.githubusercontent.com/6777029/121800758-f920b200-cc33-11eb-90a9-00f0c27355da.png)

**Comment by MatthiasMann** [comment]
Removing these stairs fixed the issue
