### ISSUE TITLE
Miner keeps ores in inventory rather than stashing them

### ISSUE THREAD

**Issue by AWolters-ru** [ldtteam/minecolonies#7245]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.220-ALPHA
- Structurize Version: 0.13.177-ALPHA
- Related Mods and their Versions: None that would mess with the miner AI

## Expected behavior
I would expect the miner to put the ores from their inventory into the racks in the mine so the can be picked up by the couriers.

## Actual behavior
The miner keeps the ores in their inventory, so they cannot be picked up and the smelter has nothing to work with, so the whole industry chain stops dead.
![Miner inventory](https://user-images.githubusercontent.com/21329625/121804106-0e520c80-cc45-11eb-9bef-a82d2940c9b0.png)

## Steps to reproduce the issue

1. Build a mine (in my case, Level 5)
2. Let the miner mine to bedrock
3. Let them collect a few ores
4. See them not stashing the ores away.

### Logs

- latest.log: Nothing shows up in logs about this
- crashlog: N/A

### Notes
The world is a redstone ready superflat world, so I added sandstone to the `minecolonies:orechanceblocks` tag and upped the chance to 35, it may be that the miner is confused because they do not find any ore. (Maybe the inventory check is only ran if they found anything?)

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by AWolters-ru** [comment]
This is also still a problem in 0.14.221-BETA, no change there.

**Comment by Raycoms** [comment]
The miner doesn't dump all the time, the miner will dump regularly so ores might stay back for a little bit.
