### ISSUE TITLE
i cant't load into my world

### ISSUE THREAD

**Issue by chaosnick44** [ldtteam/minecolonies#7247]
i have structureize and minecolonies installed. im joining my world but its loading and loading(1.16.5) (and 1.16.4 files work for 1.16.5)

**Comment by chaosnick44** [comment]
*waiting for 20m

**Comment by someaddons** [comment]
we only accept reports with properly filled out template

**Comment by chaosnick44** [comment]
? What do i say, its just not loading. i cant get my world

**Comment by grundyboy34** [comment]
I've noticed minecolonies makes a local or server world that normally loads in about 2 seconds instead take around 15 seconds longer to load, and this is on a an ssd with a 4Ghz processor, so I can imagine it's awful on worse hardware.

**Comment by dhouck** [comment]
There’s a template you should have seen when filing this issue which asks for extra information.  Not all of it will be relevant but most will, and without that nobody will be able to help.
