### ISSUE TITLE
Playerhousing wooden 3

### ISSUE THREAD

**Issue by chris5022** [ldtteam/minecolonies#7249]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:`1.16.5
- MineColonies Version:0.14.221-BETA
- Structurize Version:0.13.177-ALPHA

## Problem description

Playerhousing wooden level 3:
the sticky pistons that control the gates on both sides. you have 2 pistons staked on top of 2 pistons. the top 2 need to be removed in order to make the buttons raise and lower the gate
### Notes or related things

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
#5006
