### ISSUE TITLE
Builder stopped building completely 

### ISSUE THREAD

**Issue by notkhev** [ldtteam/minecolonies#7250]
**Prerequisites**
[x ] I am running the 12.2.2 version of MineColonies and Structurize for my Minecraft version.
[ x] I checked the MineColonies/Structurize wiki and made sure my issue is not covered there.
[x ] I made sure that this issue is not a duplicate of any existing issue.

**Context**
Minecraft Version: 1.12.2
MineColonies Version: 12.2.2-0.11.811-BETA
Structurize Version: 12.2.2-0.10.277

**Expected behavior**
When I place down a structure for my Builder to build (mine for this example) , they would add it to the build tasks and start building. 

**Actual behavior**
Builder does nothing. 

**Notes**
This happens in the console : “WorkOrderBuild at location BlockPos{} is using schematics/Nordic/Miner1 instead of schematics/Nordic/Miner1. “ and also “Colony at place BlockPos{} is null! 0” Not sure what else the issue would be other than a mod bug. Was working completely find and then randomly started messing up.

**Comment by ravenbuilder934** [comment]
1.12 is not supported or updated
