### ISSUE TITLE
oakwallsegment upgrade issue

### ISSUE THREAD

**Issue by AlmightyAnubis** [ldtteam/minecolonies#7251]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.178-ALPHA-universal
- Structurize Version: 0.13.173-ALPHA-universal
- Related Mods and their Versions: official MineColonies Modpack

## Expected behavior
 oakwallsegment  to be upgradable to tier 3

## Actual behavior
The tier 2 schematic has an error in the Decoration controller. The s for schematics is missing:
schematic/walls/oak/oakwallsegment
has to be
schematic**s**/walls/oak/oakwallsegment

## Steps to reproduce the issue

1. Place tier 1 oakwallsegment
2. Upgrade it with the builder
3. It is not further upgradeble

**Comment by Raycoms** [comment]
#5006 please for schematic issues
