### ISSUE TITLE
Family members not assigned right after birth of child

### ISSUE THREAD

**Issue by Thodor12** [ldtteam/minecolonies#7254]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.14.221-BETA-universal
- Structurize Version: structurize-0.13.177-ALPHA-universal
- Related Mods and their Versions: n/a

## Expected behavior
My child should have both a father and mother set, and so both parents must also have a child set.

## Actual behavior
Firstly the child only has a mother set, the father is unknown.
Secondly the mother is showing no partner, only that she had a child.

## Steps to reproduce the issue
1. Start your colony and get your housing count to 5
2. Wait for a child to be born and check their family statistics

I'm not sure if the jobs could pose the issue, in case it does make sure someone is a guard.
If still not the case make sure it's specifically the male that becomes a guard.
In case it becomes very specific, I've got my first male working as a builder, one female as a cook and the other as a miner.

### Logs
- latest.log: https://gist.github.com/Thodor12/f0fb80b71bd1df262bd410dc6d08e54a
- crashlog: n/a

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
That's correct, Not everyone has a partner, and as such, not always are all the parents known. This means it's a single mother raising the child.
