### ISSUE TITLE
The game crash with the last alpha

### ISSUE THREAD

**Issue by harmalom** [ldtteam/minecolonies#7261]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- 1.16.5
- MineColonies Version:
- minecolonies-0.14.223-ALPHA-universal
- Structurize Version:
- structurize-0.13.177-ALPHA-universal

## Problem description

 after updating to the latest alpha, the game freezes after a few seconds of playing the game
### Notes or related things

apparently checking the crash-reports, immersive engineering is also involved in this bug, but I'm not sure, every time I enter my map after walking for a moment or interacting with something in the colony the game freezes, all entities except me, that if I can move freely but the rest no longer responds and does not load the rest of the map, so I have to saw it.

:attached is the crash report
https://pastebin.com/NfTsbd5r
---
## Viewers
* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments. 
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Can you report this to FastSuite?

https://www.curseforge.com/minecraft/mc-mods/fastsuite

We just tick this furnace, this should definitely not stall the game.
