### ISSUE TITLE
Instantly crash when right click on Guard

### ISSUE THREAD

**Issue by Xosooo** [ldtteam/minecolonies#7267]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version:0.14.223
- Structurize Version: 0.13.177 
- Related Mods and their Versions:

## Expected behavior

Speaking to the Guard and handing over required items
## Actual behavior

Right clicking on the guard with the red icon above him instantly crash me

## Steps to reproduce the issue

1.  Building guard tower
2.  Hiring a guard and right clicking after they need an item to function
3.  instantly crashes

### Logs

- latest.log: 
- crashlog: 
- https://gist.githubusercontent.com/Xosooo/4c22d5457ac2503764055eab6faf8f2a/raw/c2947c68f3e445a548eb5027a015aeba97e8ab75/gistfile1.txt

### Notes

I'm able to just put the needed item in the guard hut inventory and able to right click him again without crashing

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
This is a known compatibility issue with Tinkers Construct.  Downgrade Tinkers to 193 or older, or wait for #7259 to be merged.

**Comment by RangerArden** [comment]
Tinkers only exists in 197, 194 and then 171 so your advice does not super work. In addition, downgrading to 171 does not fix the issue.

**Comment by ravenbuilder934** [comment]
#7259 was merged, so the latest version of minecolonies should now work
