### ISSUE TITLE
[Suggestion] Assign Builder at build request

### ISSUE THREAD

**Issue by Megistus** [ldtteam/minecolonies#727]
Pretty simply, when using the build scepter, a GUI opens up and allows assigning a specific builder for that job, if having more than one builder. Gets a bit frustrating when a builder picks up a job from way over on the other side of the colony. That, or have an algorithm that has the builder start with the closest job and work their way out ... I suppose.

**Comment by xavierh** [comment]
One week and no comment?
I think it is a very good idea. At first I thought it might be difficult to implement but thinking baxk it might not be.
At the moment, builder take the first work order available. If we add to the work order the uuid of the builder, builder could take the first work order with their uuid, if none found, they could take the first work order without a builder uuid.

Additionally when right clicking on a builder with the building wand, it could select this builder to do the build we are about to order.

Thoughts?

**Comment by Raycoms** [comment]
Sorry we're quite busy. Developing here and in real live.
Yeah we plan on a smarter build queue.

I think 2 changes should be included:
1: Button in townhall to trigger manual build assignment.
This way when you click build in a building it will give you a list of
builders you can assign (might be free for work or not, but the gui will
indicate that)

and

2:
In automatic mode it should first be checked for the closest builder if he
is free and then for the rest.

2017-04-01 11:42 GMT-03:00 xavierh <notifications@github.com>:
