### ISSUE TITLE
If contact with NPCs, game crashes.

### ISSUE THREAD

**Issue by mentlesoul** [ldtteam/minecolonies#7272]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.16.5
- MineColonies Version:0.14.215-ALPHA
- Structurize Version:0.13.177-ALPHA
- Related Mods and their Versions:

## Actual behavior
· If I right-click NPCs or minecoloy's building blocks, the game will crash in my server. But when in a new archive, it does not happen.

## Steps to reproduce the issue
[]

1. 
2. 
3. 

### Logs

- latest.log: https://github.com/mentlesoul/mentlesoul.github.io/blob/master/latest.log
- crashlog: https://github.com/mentlesoul/mentlesoul.github.io/blob/master/crash-2021-06-21_13.49.03-client.txt

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by vroni92** [comment]
This looks like some sort of data corruption. Could you make a colony export and share it with me? You can do the export with /mc colony export <colonyId> (replace <colonyId> with the ID of your colony, you can find it through /mc whoami or /mc colony list). Either share it here or message me on discord with it (Vroni#3924)

**Comment by mentlesoul** [comment]
[colonies-2021-06-20_21.59.51.zip](https://github.com/ldtteam/minecolonies/files/6685046/colonies-2021-06-20_21.59.51.zip)
is this? I can not directly export, it has an error. I give you the backup, my colony id is 1.

**Comment by vroni92** [comment]
If you could provide a zip of the save, that would be great.

**Comment by mentlesoul** [comment]
The language of my whole game package is Chinese. You may difficult to use. So I will provide the mods package and save package several minutes later.  It is a save for server, so you may use my id to play or just login in my server?

**Comment by vroni92** [comment]
I just need a zip of the world save (I don't know where it is exactly on a server).

**Comment by mentlesoul** [comment]
You can download the world save from my server, use this link:
        [http://cuberserver.imwork.net:8081/externalLinksController/downloadFileByKey/save%26%26config%26reports.zip?dkey=2f3cf863-1c2c-4cc4-b3d4-08ef93133e81](url)
And my id is "mentle_soul"
One player in my server found that his colony has no problem, but if click NPCs & working block of buildings of my colony, his game also crashed.
If you can not test the problem from just save, you can tell me and try to solve in my server.

**Comment by vroni92** [comment]
Thanks. Something weird was going on there. Did you add and remove a rank in the past?

**Comment by mentlesoul** [comment]
I remember I just used [raid-all] and [spawn new citizens] once respectively. No other command, and just develop the colony in survival mode.

**Comment by vroni92** [comment]
That's not what I meant. In the town hall, where you can also add players and change their permissions, did you add a rank there?

**Comment by mentlesoul** [comment]
Oh,yes. I wrongly add a rank, and do not know how to delete.

**Comment by vroni92** [comment]
Did something happen when you did this? Because somehow the rank was null, which lead to the behaviour you experienced. Loading your world with the fix that currently is in review should repair it.

**Comment by mentlesoul** [comment]
You mean no rank' id is 5 but in permission map, it build a permission of rank5?
![image](https://user-images.githubusercontent.com/61239889/122785776-3cd78380-d2e6-11eb-8a10-8d2a04ff6460.png)
I deleted that null permission, but crash still exist
[colony1.dat.txt](https://github.com/ldtteam/minecolonies/files/6687733/colony1.dat.txt)
Before use this file, delete .txt at the end of name.
the file path is: [  world\minecolonies\minecraft\overworld  ]

and I got an error text just now
[error text.txt](https://github.com/ldtteam/minecolonies/files/6687783/error.text.txt)

Or we can chat on discord, that maybe more efficiency, my id is mentle_soul

**Comment by Bashkaaaa** [comment]
Hey! I have the exact same issue on my server with one of our players' colony. I can provide additional logs and colony export if needed.

**Comment by ravenbuilder934** [comment]
^ Logs would be nice to make sure it actually *is* the same issue, not all crashes have the same cause

**Comment by Bashkaaaa** [comment]
https://gist.github.com/Bashkaaaa/fcd7f6b5b3e104a85203f7cb2e379b29 this is a snippet from the server log
https://gist.github.com/Bashkaaaa/7a3c561225ab2af9865d4182a5086aec client crash log. My client crashed when I interacted with an NPC. I am a colony officer, Colony owner crashes too with the same error.

**Comment by mentlesoul** [comment]
> https://gist.github.com/Bashkaaaa/fcd7f6b5b3e104a85203f7cb2e379b29 this is a snippet from the server log
> https://gist.github.com/Bashkaaaa/7a3c561225ab2af9865d4182a5086aec client crash log. My client crashed when I interacted with an NPC. I am a colony officer, Colony owner crashes too with the same error.

But actually, just that colony has problem right? Other colonies has no problem.
