### ISSUE TITLE
AI Problem

### ISSUE THREAD

**Issue by bblaze1001** [ldtteam/minecolonies#7275]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.221-BETA

### Logs

https://gist.github.com/bblaze1001/57e3f4e869d8e51a35d20838915ca584

- latest.log: 

## Steps to reproduce the issue / details

This showed up on the last steps of building playerhousing oak3. After asking me for red roses.

Just reporting the AI issue. 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Log doesn't contain the exception unfortunately.
