### ISSUE TITLE
Courierhut adds Delivery of:32 (NULL item, not even shown) Warehouse -> (NPCname) Priority: 13

### ISSUE THREAD

**Issue by BorednBoring** [ldtteam/minecolonies#7276]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.16.5 
- MineColonies Version:0.14.288 ALPHA
- Structurize Version:0.13.177 ALPHA
- Related Mods and their Versions: MineColonies Official modpack v2.8 by H3lay

## Expected behavior

Courier will be doing their job.

## Actual behavior

Courier runs back and forth between the courierhut and the warehouse.

![image](https://user-images.githubusercontent.com/84329771/122869917-8617e980-d35f-11eb-8a56-b96e054397ab.png)

## Steps to reproduce the issue
**_I didn't test a new game, however this is what I did before the courier broke_**

**I have a new colony.** 
Started off with Builder -> Forester -> Miner -> Courier -> Warehouse
I am not sure when the courier broke(I had just created the warehouse), but I had thrown 40+ slots of items on the ground for the courier to store in the brand new warehouse.
I realised the courier was broken as he ran back and forth from the courierhut and the warehouse.
I then check the Courierhut and Courierhut showed "Delivery of:32           Warehouse -> NPCname Priority: 13
Next, I opened the inventory of the courier which showed 32 cobblestone slabs. 
What I did to try and fix the issue: I have removed the 32 cobblestone slabs and had tried to fire the worker, rebuild the huts and used the /mc colony requestsystem-reset 1 command to no avail.

### Logs

Latest.log: https://gist.github.com/BorednBoring/2b107a5b41818d949fa8c0589a5f4580
No crash happened.

### Notes

I was on the default v2.8 of the MineColonies modpack. I was informed on Discord Bugs-116 to update the Mods: MineColonies and Structurize which is shown on the top, but it didn't fix the issue.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Who is Forest T Clavell? the courier himself? Do you have a weird air minimum stock setup anywhere?

**Comment by BorednBoring** [comment]
Nope, Forest T Clavell is the Miner who is requesting for 32 Cobblestone slabs.
It's all default with no minimum setup etc.

The courier broke(running back and forth even with a proper request) after this happened which could be fixed by swapping jobs with another citizen and swapping the job back. (Fix was only done after I had resolved the cobblestone slab request personnally)

**Comment by Raycoms** [comment]
It seems like for some reason this cobble slab request got messed up badly into an air request for some reason, hmmm. Are you able to reproduce this somehow?

**Comment by BorednBoring** [comment]
Nope, after I had fixed the issue, I threw a bunch of items(Pretty much everything I had thrown in the beginning before the issue) at my courier, and it didn't break the AI. Not sure what caused it.

**Comment by Raycoms** [comment]
Ohhh wait, by chance do you have any recipes that look weird? I think there is a chance that some item got removed from your world, but is still in some recipe.

**Comment by Raycoms** [comment]
Should be solved
