### ISSUE TITLE
I think the Undertaker is broken. No idea what is causing it.

### ISSUE THREAD

**Issue by Santereva** [ldtteam/minecolonies#7281]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.16.5
- MineColonies Version:0.14.155-BETA

### Logs

- latest.log: https://github.com/Santereva/issue 

## Steps to reproduce the issue / details

(Prior info: It's on a server, using the modpack "Life in a village 2" as the source)
Just reporting the AI issue.
Unsure what happened, he just sits there in his own home and brings up the message.
I'm new to Git hub, so contact me if there is an issue.
(You can use Santereva101@gmail.com if it's needed)

 

### Notes

He was working just fine earlier, but when I booted up the server and noticed that there is a citizen complaining, that was when I found the error. His work place is about 20 block or so away. He has a shovel, last death was the day before he attained his job.
I have gone into spectator to look for graves yet there were none. The message was made roughly 2 hours ago as of writing now and the log presented.
I do not know what other info or something of note I need to give.
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
You linked the wrong log

**Comment by Santereva** [comment]
> You linked the wrong log

I have uploaded an updated log made by the server (since there is no other log file I could find) and a latest Debug file along with it.
These are logs generated by the server with only me in it and attempted to do some more exploring in the matter.

**Comment by Raycoms** [comment]
Where did you upload this?

**Comment by Santereva** [comment]
> Where did you upload this?

On the same link i posted, you can see them with the names.

**Comment by Santereva** [comment]
They would appear as "LatestUpdated" and "Debug".

**Comment by Raycoms** [comment]
No, there is nothing at that link I have access to.

**Comment by Santereva** [comment]
I will just post it here on my comment then. unsure if it's working.
[debug.log](https://github.com/ldtteam/minecolonies/files/6695969/debug.log)
[latest.log](https://github.com/ldtteam/minecolonies/files/6695970/latest.log)

**Comment by Raycoms** [comment]
Has been fixed in the latest version

**Comment by Santereva** [comment]
> Has been fixed in the latest version

Am I able to assume that this means there is a new version update of the mod?

**Comment by Raycoms** [comment]
50

**Comment by Santereva** [comment]
50?

**Comment by Raycoms** [comment]
You're over 50 versions behind =P

**Comment by Santereva** [comment]
I might have to contact the mod pack author about this XD.

**Comment by Santereva** [comment]
> You're over 50 versions behind =P

If you don't mind me bothering you again, mind explaining this? I downloaded the release version of Minecolonies and Structurize.
![image](https://user-images.githubusercontent.com/86306235/122968606-a063be80-d383-11eb-9ee3-fe2caf6cec4e.png)

**Comment by ravenbuilder934** [comment]
Download the alpha versions

**Comment by Raycoms** [comment]
Or the latest beta, the release is even more outdated, new release is coming out soon.

**Comment by Raycoms** [comment]
It will tell you which structurize version to download alongside with it.

**Comment by Santereva** [comment]
> It will tell you which structurize version to download alongside with it.

I tried looking for version 0.13.96-Alpha and I can't find it. I decided to just download the latest alpha version and is asking for minecraft to be 1.15?

**Comment by Santereva** [comment]
Still asking for the 96 version

**Comment by ravenbuilder934** [comment]
You downloaded this file? https://www.curseforge.com/minecraft/mc-mods/minecolonies/files/3360973

**Comment by Santereva** [comment]
No, I have downloaded this one https://www.curseforge.com/minecraft/mc-mods/minecolonies/files/3106617

**Comment by Santereva** [comment]
Im trying out downloading the Beta version as we speak to see if it works.

**Comment by Santereva** [comment]
No dice, still asking for this magical "0.13.96" that doesn't exist on the curse forge file downloads.
Will renaming the file as 0.13.96 work or will my stupidity break everything?
![image](https://user-images.githubusercontent.com/86306235/122970106-6398c700-d385-11eb-957d-15ab2ad8e08f.png)

**Comment by ravenbuilder934** [comment]
Yeaaahh don't rename it. What file did you get this time? With those messages I doubt it's the latest beta

**Comment by ravenbuilder934** [comment]
Did you remove the release file?

**Comment by Santereva** [comment]
Currently, my minecraft is running :
minecolonies-0.13.437-RELEASE-universal
structurize-0.13.30-BETA
I'm really confused now.

**Comment by Santereva** [comment]
I have attempted to run structurize-0.13.100-RELEASE-universal
but is still asking for the magical number 96

**Comment by ravenbuilder934** [comment]
Download and install https://www.curseforge.com/minecraft/mc-mods/minecolonies/files/3358290 and https://www.curseforge.com/minecraft/mc-mods/structurize/files/3341854. Remove all other minecolonies and structurize files. then it should work

**Comment by Santereva** [comment]
Ok thank you, the game and the server is back up and working as normal again. The Ai is also fixed. I can't thank you enough with your patience.

One thing I will ask though, will the Undertaker's model be updated? (has a hole at the back of the head)

**Comment by ravenbuilder934** [comment]
great :smile: @Imrielle model?

**Comment by Santereva** [comment]
> great 😄 @Imrielle model?

If it's the top hat and tux, then yes.

**Comment by Santereva** [comment]
Sorta looks like a disformed Micheal Jackson.

**Comment by Imrielle** [comment]
> 
> 
> great 😄 @Imrielle model?

This would be OddRobbia or Carlansor, I haven't made any of the citizen models, or touched the newer citizen models textures. :P

**Comment by Santereva** [comment]
> > great 😄 @Imrielle model?
> 
> This would be OddRobbia or Carlansor, I haven't made any of the citizen models, or touched the newer citizen models textures. :P

Well tell them from me: "You guys are doing a good job".
