### ISSUE TITLE
AI Issue

### ISSUE THREAD

**Issue by Flami21** [ldtteam/minecolonies#7282]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [ x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.221-BETA

### Logs

- latest.log: https://gist.github.com/Flami21/d29fb525c0979ec3b2d4a7c14fb9287d 

## Steps to reproduce the issue / details

The builders (two of them) had this problem while buildinn the last tier of Oak house for playerhousing
Just reporting the AI issue. 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Can you please report this to: AdvancedCrafterLootFunction ?

**Comment by Raycoms** [comment]
at edivad.extrastorage.loottable.AdvancedCrafterLootFunction

Extrastorage I meant

**Comment by bblaze1001** [comment]
may I know how to do that? I'm new here c:

**Comment by Raycoms** [comment]
Here: https://github.com/Edivad99/ExtraStorage
