### ISSUE TITLE
Cannot open Minecraft after developing colony

### ISSUE THREAD

**Issue by supercronchy** [ldtteam/minecolonies#7286]
### Prerequisites 

- [ x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.231-ALPHA
- Structurize Version:-0.13.177-ALPHA
- Related Mods and their Versions: No other mods :(

## Expected behavior

After some gameplay, game opens to main menu after hitting "Play" button.

## Actual behavior

After some gameplay, game loads mods, attempts to generate main menu, then crashes.

## Steps to reproduce the issue
1. Develop your colony enough to get some level 3 buildings and a message that raids will be increasing in size, then exit the game. 
2. Attempt to reload the modded version of Minecraft.
3. Game crash.

1. 
2. 
3. 

### Logs

- latest.log:  no log, game doesn't start
- crashlog:  https://gist.github.com/supercronchy/33460cf484c939b05492fff5715f9df6

### Notes

I did initially have other mods loaded, but eliminated them when I could no longer access my game. The other mods didn't really interact with anything in Minecolonies besides some Pam's Harvestcraft 1.16 mods and Tinker's, but the issue did not happen on multiple occasions after the mods interacted, so I don't think its that.
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Try deleting the file `forge-client.toml`; it doesn't look like this has much to do with minecolonies.

**Comment by Raycoms** [comment]
Yeah, nothing to do with MineColonies, this is a forge/config issue

**Comment by supercronchy** [comment]
> Try deleting the file `forge-client.toml`; it doesn't look like this has much to do with minecolonies.

Immediately worked. I was convinced that was just forge, the modloader. Facepalm.

I am curious how that's getting in there and stopping the game from loading. That's never happened on other custom packs I've made. Thanks for your help, anyhow.
