### ISSUE TITLE
MC won't start because unlisted version is required for the newest build.

### ISSUE THREAD

**Issue by becamesus** [ldtteam/minecolonies#7287]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.231 Alpha
- Structurize Version: 0.13.191 Alpha

## Problem description
When I try to launch the game, it doesn't work. Minecraft tells me that I need the version of Structurize to be 0.13.177. However, I haven't been able to locate any version like that.

### Notes or related things
I'm using ForgeOptifine.
![изображение_2021-06-23_121618](https://user-images.githubusercontent.com/86349097/123070852-ce491180-d41c-11eb-9bb7-196fc5ad3074.png)

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
You should ask support questions on discord rather than going straight to github.
And the file is there, just click on All Files.  Curseforge's UX is terrible.
