### ISSUE TITLE
one of the mods saying its not up todate

### ISSUE THREAD

**Issue by jessk2323** [ldtteam/minecolonies#7288]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x
![Capture](https://user-images.githubusercontent.com/86370348/123131701-cda38180-d402-11eb-8b89-8f7b88f217de.PNG)
![Capture](https://user-images.githubusercontent.com/86370348/123131722-d431f900-d402-11eb-98bb-8bac7e2be932.PNG)
[latest.log](https://github.com/ldtteam/minecolonies/files/6703397/latest.log)
[latest.log](https://github.com/ldtteam/minecolonies/files/6703399/latest.log)
 ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- MineColonies Version:
- Structurize Version:

### Notes or related things

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.
![Capture](https://user-images.githubusercontent.com/86370348/123131896-faf02f80-d402-11eb-892a-09c73d8b4658.PNG)
[latest.log](https://github.com/ldtteam/minecolonies/files/6703403/latest.log)

**Comment by jessk2323** [comment]
sorry the multiple pictures this my first time using this!

**Comment by ravenbuilder934** [comment]
What does this have to do with the minecolonies mod?

**Comment by jessk2323** [comment]
> What does this have to do with the minecolonies mod?
i installed YOUR mod pack through curse forge and get THIS ERROR

**Comment by ravenbuilder934** [comment]
Okay, but this github is *just* for the mod itself. report it on our [discord](https://discord.minecolonies.com)
