### ISSUE TITLE
Permission nodes for all /mc commands.

### ISSUE THREAD

**Issue by Wissi** [ldtteam/minecolonies#729]
No specific nodes exist for the Minecolonies commands to be set server side in permission systems.

For example: 
minecolonies.command.*    (wildcard) will allow ALL /mc perms

But no specific node for each command.
/mc rtp            (needs a node) for example:   minecolonies.command.rtp
/mc colonies list      it could be:    minecolonies.command.colonies.list

Atm no variants work only the wildcard, but is not recommended because it gives ALL /mc commands and some should only be Admin/OP.

**Comment by Raycoms** [comment]
normally all our commands should have their own way to detect if the player
has the right to execute it.
The problems seems to be that nucleus gives the player op to execute which
we detect and then allow.

2017-03-24 14:38 GMT-03:00 Wissi <notifications@github.com>:

**Comment by marvin-bitterlich** [comment]
We need permission nodes on our commands to use the permission system if it is supported

**Comment by Wissi** [comment]
I guess it's two separate settings:
Config file side for SMP play in LAN ?

But definitely nodes required for server side permission systems.

**Comment by Raycoms** [comment]
@Kostronor might that resolve our problem?

```
 return FMLCommonHandler.instance().getMinecraftServerInstance().getPlayerList()
                    .canSendCommands(((EntityPlayer) sender).getGameProfile());

 public boolean canSendCommands(GameProfile profile)
    {
        return this.ops.hasEntry(profile) || this.mcServer.isSinglePlayer() && this.mcServer.worlds[0].getWorldInfo().areCommandsAllowed() && this.mcServer.getServerOwner().equalsIgnoreCase(profile.getName()) || this.commandsAllowedForAll;
    }
```

**Comment by Raycoms** [comment]
I think that resolved it
