### ISSUE TITLE
Colonists not sleeping

### ISSUE THREAD

**Issue by anakhasilver** [ldtteam/minecolonies#7291]
### Prerequisites 

- [ x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.233-ALPHA
- Structurize Version: 0.13.191-ALPHA

## Problem description

At night, my colonists all gather at their huts to sleep and then... Don't sleep, then complain they haven't slept in days. This is an entirely new save with this mod. Medieval dark oak alternative and medieval dark oak have problems. Birch does not.
### Notes or related things

I have manual housing on and have kids off, otherwise this is pure default settings outside of the rain-work setting.

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Are there blocks somehow above the beds that block them from sleeping potentially?

**Comment by anakhasilver** [comment]
No. I have changed nothing in the builds. I can use the beds just fine, no damage, and path to them just fine. But they're just... Not going to them. These are level five huts, too.

Like to be clear, they don't even go upstairs. They hover at the hut block like the beds don't exist. I can try a builder repair?

**Comment by Raycoms** [comment]
Yeah, maybe the schematics already have the beds somehow obstructed. Can you show screenshots of some of the beds?

**Comment by anakhasilver** [comment]
https://imgur.com/a/KxI3cQx

Imgur album so I can save people's mobile data. All the beds I could find in the two styles.

**Comment by Raycoms** [comment]
Does this apply to all of them, or do some of them sleep?

**Comment by anakhasilver** [comment]
Every medieval dark oak/dark oak alternative has this problem. I think one of them slept like. Once. And then never again. I've moved them out to different houses, I've removed them from houses for a night, I moved them back in, saved and restarted... The birch house is having 0 problems.

EDIT: Can confirm. Repairing does nothing.
