### ISSUE TITLE
Already built colony no longer allows access to huts or people and crashes client to desktop after a second player builds their own colony without issues

### ISSUE THREAD

**Issue by Visceralfulton** [ldtteam/minecolonies#7295]
- [ No] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ Yes] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [YES ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 
- MineColonies Version: minecolonies-0.14.221-BETA-universal
- Structurize Version: structurize-0.13.177-ALPHA-universal
- Related Mods and their Versions: ALL THE MODS 6 Pack plus:
ImmersiveRailroading-1.16.4-forge-1.8.0.1.jar
SpartanWeaponry-1.16.4-2.1.0-beta-4.jar
ProjectE-1.16.5-PE1.0.1B.jar
guncus-1.16.4-2.0.jar
UniversalModCore-1.16.4-forge-1.0.1.jar
gunswithoutroses-1.16.5-1.0.9.jar
TrackAPI-1.16.4-forge-1.2.1.jar
vehicle-mod-0.45.2-1.16.3.jar
cgm-1.0.1-1.16.3.jar
Space-Bosstools-1.16.5-5.3.jar
obfuscate-0.6.2-1.16.3.jar

## Expected behavior

To allow more than one player to be able to access more than one colony without the game crashing or denying players access to other colonies 

## Actual behavior

What i have noticed now after doing some testing is that I can access my friends colony that he given me officer permissions for and can help him build that up but when i go to my own colony and try to access any hut or the town hall it instantly crashes my game now and i have to reboot minecraft to be able to rejoin my server

## Steps to reproduce the issue
Anytime after a second player builds a new town hall and gives the first player officer permissions the first players already built colony denies them access to any building or villager and immediately crashes their client 

### Logs

- latest.log: 
- crashlog:

**Comment by Visceralfulton** [comment]
https://pastebin.com/mGAtcfsN Latest Log

**Comment by Visceralfulton** [comment]
https://pastebin.com/bz2zJbxd Crash Log

**Comment by Raycoms** [comment]
Are you in LAN mode?

**Comment by Visceralfulton** [comment]
Negative, its a public server that i have been running with a server box in my home and port forwarded to. I have a buddy in Alabama that is able to connect to it via my public IP

**Comment by Visceralfulton** [comment]
If need be i can record a video of what exactly happens in my interaction with the server, when i interact with the 2 colonies, and when it crashes me out if that also helps

**Comment by Raycoms** [comment]
This is strange, this works perfectly fine on all our servers.

**Comment by Raycoms** [comment]
@vroni92 is that among the fixes you recently pushed?

**Comment by Visceralfulton** [comment]
I can definitely show you what happens with a recorded video

**Comment by Raycoms** [comment]
Can you try the latest alpha?

**Comment by Visceralfulton** [comment]
I have tried and after i install both the Alpha of minecolonies and Structurize my server will refuse to boot and crashes out, i can attempt to install both again

**Comment by Raycoms** [comment]
Ohh, I guess you have java 11+, right?

**Comment by Visceralfulton** [comment]
java SE development  kit 16.0.1

**Comment by Visceralfulton** [comment]
I have recorded a video of what happens. Is there some place i can publish it so you can view it?

**Comment by Visceralfulton** [comment]
actually i may be able to share it via dropbox

**Comment by Visceralfulton** [comment]
https://www.dropbox.com/s/03dt7jvbgb5m8e4/Base%20Profile%202021.06.24%20-%2019.09.10.01.mp4?dl=0

**Comment by Raycoms** [comment]
Can you try the newest structurize/minecolonies combo? Should be working now for highe rjava versions

**Comment by Visceralfulton** [comment]
I can certainly try, which verisons of both do i need to find

**Comment by Raycoms** [comment]
194 structurize 236 minecolonies

**Comment by Visceralfulton** [comment]
roger that, ill let you know my findings in about 10 minutes

**Comment by Visceralfulton** [comment]
got a crash report serverside before it could finish

**Comment by Raycoms** [comment]
What's the crash? I had some people test the latest and it should work for newer java versions.

**Comment by Visceralfulton** [comment]
one moment

**Comment by Raycoms** [comment]
(You might have to update forge if your forge version is quite behind)

**Comment by Visceralfulton** [comment]
https://pastebin.com/tEiCVqun

**Comment by Raycoms** [comment]
Gotta update Tinkers to newest too

**Comment by Visceralfulton** [comment]
okay so what do i need to go and download to what specific versions?

**Comment by Raycoms** [comment]
Just the newest tinkers, they pushed breaking changes recently

**Comment by Visceralfulton** [comment]
Tinker's Construct 3.0.4.197 for 1.16.5 This version?

**Comment by Visceralfulton** [comment]
What about Mantle as well?

**Comment by Raycoms** [comment]
```
tc_version=3.0.4.197
mantle_version=1.6.108
```

**Comment by Visceralfulton** [comment]
i didnt see a mantle_version=1.6.108 only the 109. Also the server didnt crash this time on bootup so lemme see what happens when i boot in

**Comment by Visceralfulton** [comment]
HOLY SHIT IT WORKS! :D But there is this thing that does keep appearing in my CMD 
[21:31:05] [Server thread/WARN] [structurize/]: Could not find iterator for value: using default instead!

**Comment by Raycoms** [comment]
Np, that will appear a few times until it's settled

**Comment by Visceralfulton** [comment]
Thank you very much sir! i really appreciate the help you have given me, i am so glad that I don't have to restart my server all over again.

**Comment by Visceralfulton** [comment]
i am not sure what happened but now i cannot seem to start my server at all now. and the logs dont seem to provide much in terms of information

**Comment by Visceralfulton** [comment]
NEVERMIND FIXED IT
