### ISSUE TITLE
[1.16] Can't upgrade 4th tower to level 4 in barracks

### ISSUE THREAD

**Issue by DarkGuardsman** [ldtteam/minecolonies#7297]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.233-ALPHA-universal
- Structurize Version: 0.13.191-ALPHA
- Related Mods and their Versions: 

## Expected behavior

Ability to upgrade the tower to level 4

## Actual behavior

Attempt to upgrade the tower and get told to upgrade the barracks. The barracks is already level 4 and 3 of the other towers are at matching level

![image](https://user-images.githubusercontent.com/1477330/123353930-98954d00-d530-11eb-8d7f-21e23159168e.png)
![image](https://user-images.githubusercontent.com/1477330/123353939-9df29780-d530-11eb-98b4-f5b2b1146d77.png)
![image](https://user-images.githubusercontent.com/1477330/123353945-a5b23c00-d530-11eb-8566-a2aacfa0b8b4.png)
![image](https://user-images.githubusercontent.com/1477330/123353966-ae0a7700-d530-11eb-93d3-fb196cddf8da.png)

## Steps to reproduce the issue

1. Upgrade barracks to level 4
2. Upgrade towers to level 4
3. Hit a tower that refuses to upgrade

### Logs

- latest.log: https://gist.github.com/DarkGuardsman/f8214fbe1db4b103934db0330cb2e990
- crashlog: 

### Notes

We just jumped 50+ versions but this error persisted before/after the update. 

Placing and rebuilding doesn't seem to solve the issue.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Can you try a repair on the barracks main building?

**Comment by Raycoms** [comment]
Should be solved, if not the above step should solve it.
