### ISSUE TITLE
[1.16] Crashed while opening mystical site build options UI

### ISSUE THREAD

**Issue by DarkGuardsman** [ldtteam/minecolonies#7298]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- MineColonies Version:
- Structurize Version:
- Related Mods and their Versions:

## Expected behavior

Open Build options in mystical site

## Actual behavior

Crashed while opening build options

## Steps to reproduce the issue

1. Open UI
2. Click Build options
3. Crash

### Logs

- latest.log: 
- crashlog: https://gist.github.com/DarkGuardsman/6c312120fdd7105371e8ea96a8b78c20

### Notes

Creative build the site shortly before. Saw it show two messages for claimed chunks.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Which mystical site, which level?

**Comment by kedamono** [comment]
I had the same problem upgrading the Caledonia style Mystical Site from Level 2 to Level 3. That mystical site was upgraded to level 2 about a month ago, if that matters. 

My crash log: https://gist.github.com/kedamono/3de8ce31c4076b739391b029cbc9a265

**Comment by DarkGuardsman** [comment]
Level 4 if I recall right
