### ISSUE TITLE
Citizens do not start working in the morning.

### ISSUE THREAD

**Issue by werewolfspb1987** [ldtteam/minecolonies#7299]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.224-BETA

### Logs

- latest.log: 

## Steps to reproduce the issue / details

Just reporting the AI issue. 

### Notes

Citizens do not start working in the morning if they are further than 2 chunks from the player. It is necessary to approach them or call them to the town hall.
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.
![2021-06-25_13 44 55](https://user-images.githubusercontent.com/69458421/123414584-be683380-d5bc-11eb-9ef2-c1f10f169b80.png)

**Comment by someaddons** [comment]
that is some other mod's doing, not minecolonies

**Comment by werewolfspb1987** [comment]
![Mods](https://user-images.githubusercontent.com/69458421/123421375-6b46ae80-d5c5-11eb-9f21-f5a1cbd6d196.png)

**Comment by Raycoms** [comment]
There is an optifine problem that makes citizens not wake up if you're not standing right next to the hut. There are some config values around that you have to adjust.

**Comment by Duorhs** [comment]
> There is an optifine problem that makes citizens not wake up if you're not standing right next to the hut. There are some config values around that you have to adjust.

I got the same issue. After looking up some issues now I know this is a Optifine issue, but since you said we can adjust some config to fix it, can you please give more details?

**Comment by uecasm** [comment]
Turn off the "smooth world" setting.

**Comment by Duorhs** [comment]
> Turn off the "smooth world" setting.

Thanks very much! After doing some research now I know that "smooth world" is related to "chunk loading" not "world texture/block loading".  It seems that this setting stops chunks from loading if they are far away, which reduces lag but become a problem.
