### ISSUE TITLE
Minecolonies: Builders tape not removed after completion and sometimes appears one block farther out than expected

### ISSUE THREAD

**Issue by kedamono** [ldtteam/minecolonies#7302]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.235-ALPHA
- Structurize Version: 0.13.192-ALPHA
- Related Mods and their Versions: n/a

## Expected behavior

When the builder completes upgrading a building the builders tape is removed. Also, the builders tape should appear one block outside of the building's boundary.

## Actual behavior

When the builder has completed constructing a building, the building tape is not removed. Also, the builder's tape appears one block further away from the building's boundary than expected. The image shows the placement of the builder's tape around the Caledonia Style Mechanic hut and is one block larger than expected. The tape should be placed adjacent to the cobblestone border. 

![2021-06-25_10 26 19](https://user-images.githubusercontent.com/23420636/123478106-d5eeee80-d5b3-11eb-9830-f90c534fd7e8.jpg)

## Steps to reproduce the issue

1. Have the builder upgrade an existing hut.
2. The Builders tape appears 1 block farther out than expected from the building's border.
3. When the builder completes, the builder's tape remains in place.

### Logs

- latest.log: https://gist.github.com/kedamono/b50abd9631604519c302d2df2fd2e95c
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by someaddons** [comment]
can't reproduce it with new buildings

**Comment by kedamono** [comment]
Yes, that's why I said upgrading a hut. Brand new huts work as expected. But go from level 1 to 2 and you'll get the issue.

**Comment by someaddons** [comment]
no I did upgrade to test, pasted a level 1 and upgraded it

**Comment by kedamono** [comment]
Well, I had it happen 5 times this morning as I was working on my colony. Every one was an upgrade of an existing building that was built the traditional way.

**Comment by uecasm** [comment]
I think the point is that there could have been a bug in the L1 schematics at the time you originally built them, that was since fixed (and is no longer present in current versions).  So your existing L1 buildings will upgrade funny, but if you built a new one and upgraded it today then it should work as expected.

You could probably "fix" any other existing L1 buildings affected by deconstructing, picking up, replacing, and repairing/upgrading.

**Comment by someaddons** [comment]
its probably some buildings upgraded from an old version ye

**Comment by kedamono** [comment]
Well, one of the buildings is a custom Citizen hut I created. That was about a month ago. It could be that. I'll try a new building with the current version of Minecolonies and see how it fares.

**Comment by Nooska** [comment]
To chime in, I have it happening too, on fortress schematics (mentioned in the discord), on all upgrades done on buildings in 14.236 with 13.194 (edited to correct typo of 192) - all buildings were initially built in versions prior, for structurize (which I think handles it) it was 177 previously, and buildings ordere dupgraded then (but sitll not done) did not have the issue.
Original builds are quite a ways back though.

**Comment by Nooska** [comment]
And after a bit of experimenting after coming across this issue, I'll confirm that in my world this bug only affects huts built prior to 13.194 (typo in the last one). The huts built after upgrading do not have the extra space to the construction tape. (I don't have any huts that I've built prior, upgraded and can upgrade again yet, as I'm only at level 3)

**Comment by uecasm** [comment]
Just had this happen in one of my worlds too.  This was a relatively recent build, but it probably was initially built with Mcol 228/Structurize 177 and then upgraded on MCol 237/Structurize 195.  The tape wasn't removed at the end of the build, and it was one block too far out on at least one side.

Another building upgrade I started after the mod upgrade (initially built way back in 0.13) does have the tape snugly fitted around the building (so may be unaffected), but the build hasn't finished yet.  I'll report back once it has.  Possibly rotation is a factor?

**Comment by uecasm** [comment]
The other one isn't built yet (it's the university, so it's a huge build) but in the meantime I started another upgrade of a building that definitely hasn't been touched since 0.13.  The tape appeared one block too far out on all four sides.

In case it helps, partial NBT from the hut block => `pos: { x: -314, y: 64, z: 37 }, corner1: { x: 1125, y: 44, z: 789 }, corner2: { x: 1125, y: 44, z: 789 }` (birch guardtower L2=>L3) and the tape was placed from -307,64,31 to -319,64,43.
