### ISSUE TITLE
Using forester's zoning tool is awkward when following the in-game instructions

### ISSUE THREAD

**Issue by Bashkaaaa** [ldtteam/minecolonies#7304]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.14.230-ALPHA-universal.jar
- Structurize Version: structurize-0.13.177-ALPHA-universal.jar
- Related Mods and their Versions: modpack https://www.curseforge.com/minecraft/modpacks/ttw-community-server-pack/relations/dependencies

## Expected behavior
Player should be able to follow the instructions given in-game when using the zoning tool to restrict forester's working area in an easy and intuitive way.

## Actual behavior
When player is following the given instructions (left click first to set the first position, right click to set the second position) they are having really hard time, because the left click to set the first position has to be ultra short- much shorter than your average click, otherwise the game sees it as double-click and completes the process without setting the second position. However the tool works just fine, if we use the right-click for the first position and left click for the second position. The area is registered correctly and forester will start working in the area. 
This is ok if someone knows about it, but if they don't, this leads to a lot of frustration. 
Unfortunately just changing the wording will not work, because if you read the chat messages in the second screenshot, you will see that when I used the reverse-click method, after using the left-click for the second position, I still got the message for the first position.

![image](https://user-images.githubusercontent.com/84290349/123509491-1ca51d00-d676-11eb-807b-de273598af4f.png)
![image](https://user-images.githubusercontent.com/84290349/123509509-3a728200-d676-11eb-9b27-b1e6f5739bc3.png)

## Steps to reproduce the issue

1. Open the forester's GUI on the zoning tool page and read the instructions
2. Grab the tool and proceed to the desired work area
3. Following the instructions, left click on the ground with the tool to select the first corner- you will notice that you click super fast, the tool will disappear like if you've clicked twice
4. Repeat steps 1-2
5. Ignore the instructions and the chat messages and right-click on the ground with the tool to select the first corner
6. Left click on the ground with the tool to select the second corner- you will notice that the confirmation message is displayed and the area is selected correctly.

### Logs

N/A

### Notes
We are not using the latest alpha, because updating the modpack every time there is a new version would be very cumbersome. We try to update the pack once a week.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by aelfwyne** [comment]
This is still an issue. I found this issue because I was trying to figure out why the selection tool was simply "disappearing" on the first click. Turns out it is thinking a normal press is a double click. No other application I have has a problem with detecting double clicks on my mouse. But sure enough, I intentionally did a VERY fast click and it didn't disappear. It's still incorrectly detecting double clicks.

**Comment by pwaksman973** [comment]
Today it still a pain, when you click it perform several action, its basically impossible to do 1 single left click to complete the area selection.

You grab the tool, right click on a block, works just fine, then try to left click on another block. It will almost always print like 2 to 4 messages for your left click, leaving the selection area invalid again, so efectively you can't define a working area now a days :( 

minecolonies-1.1.705-1.21.1-snapshot
