### ISSUE TITLE
Published maven artificats depend on mapped versions

### ISSUE THREAD

**Issue by maxanier** [ldtteam/minecolonies#7305]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.228-ALPHA
- Structurize Version: 0.13.177-ALPHA

## Problem description

The `.pom` file upload to your maven specifies `_mapped_snapshot_xxxx` dependencies which cannot be resolved when depending on that artifact (at least if using a different mapping version).
https://ldtteam.jfrog.io/artifactory/mods-maven/com/minecolonies/minecolonies/0.14.228-ALPHA/minecolonies-0.14.228-ALPHA.pom

This is sort of an issue with ForgeGradle, which apparently won't be fixed: https://github.com/MinecraftForge/ForgeGradle/issues/584

However, there are two workarounds mentioned in the respective issue.
One includes filtering those versions: https://github.com/MinecraftModDevelopment/Gradle-Collection/blob/eba777ee097440f8eac2d7fd81907c65ce66d9de/minecraft/maven_nomcp.gradle#L30-L44

Similar to the already implemented filtering for `.deobf` versions in minecolonies `build.gradle`.

### Notes or related things

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
solved
