### ISSUE TITLE
Hello, my friend's game keeps crashing.

### ISSUE THREAD

**Issue by ritgamer8** [ldtteam/minecolonies#7306]
My friend always gets this error "Error- java.lang.NullPointerException: Unexpected error"
This is his crashlog. I have tried updating the server but it doesn't seem to do anything. We have also tried changing the versions of the mod. Yet no success. Any help would be great! Thanks, and I look forwarding to hearing from you guys soon ^-^ 
[message.txt](https://github.com/ldtteam/minecolonies/files/6720143/message.txt)

**Comment by Raycoms** [comment]
Please fill out the template
