### ISSUE TITLE
Crsh when right clicking the fisherman hut's inventory

### ISSUE THREAD

**Issue by jonabrv1965** [ldtteam/minecolonies#731]
### Minecolonies version

version X.X.XXXX or curse X.X.XX

### Expected behavior

- XXX

### Actual behaviour

With the latest version (minecolonies-universal-1.10.2-0.6.3228) I'm getting a crash when right click the fisherman hut's inventory, the other stations inventories works fine (builder, farmer and lumberjack)

### Steps to reproduce the problem

1. XYZ
2. ZYX
3. ...
4. Profit

**Comment by jonabrv1965** [comment]
[crash-2017-03-11_13.50.14-server.txt](https://github.com/Minecolonies/minecolonies/files/869206/crash-2017-03-11_13.50.14-server.txt)

**Comment by marchermans** [comment]
Please report this also to the mod author of the ultimate unicorns mod. This does not seem related to minecolonies i would think. @Kostronor @Raycoms are we spawing any entities when we click on that block?

**Comment by Raycoms** [comment]
No I guess one of the coremods or that unicorn mod seem to overwrite
methods we use.

2017-03-24 18:37 GMT-03:00 Orion <notifications@github.com>:

**Comment by marchermans** [comment]
This could also just be a random coincidence.
@jonabrv1965 Does it happen al the time. Or just once? Can you renter your world?
@Raycoms What methods do we use when opening that UI that would cause a **Minecraft** villager to spawn? We have our own entities. So.......

**Comment by Raycoms** [comment]
Nothing should be causing an entity to spawn. But maybe a obfuscated method
has been changed so that it kinda translates to that spawning method?

2017-03-24 18:40 GMT-03:00 Orion <notifications@github.com>:

**Comment by marchermans** [comment]
We are not even in the call stack. So from where should we be calling that obfuscated method?
And it is impossible to override obfuscated methods. Even so it is not our fault and really nothing we can do about it.

**Comment by Raycoms** [comment]
Yeah I think this isn't our fault. Seems to be a coremod changing something
about the messages which are called on openGUI

2017-03-24 18:44 GMT-03:00 Orion <notifications@github.com>:

**Comment by marchermans** [comment]
We just got another one with that #733 seems to be the same without log though.
