### ISSUE TITLE
Cook gets swamped by citizens, cant get to their station.

### ISSUE THREAD

**Issue by starfall18** [ldtteam/minecolonies#7312]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.16.5
- MineColonies Version:0.14.231-ALPHA-universal
- Structurize Version:0.13.177-ALPHA-universal
- Related Mods and their Versions: ATM6 modpack v 1.6.11

## Expected behavior
Cooks and assistant cooks making food at their designated work area. Citizens walking in, receiving food from the cook and then consuming it. Multiple restaurants should draw citizens nearest to them to share the workload.

## Actual behavior
When cooks go to sleep and try to return in the morning they find a mass of soldiers and other citizens there waiting for food unable to get to their cooking area. They get stuck behind other citizens and cant cook or make food. Recalling doesnt seem to help much cause they get pushed aside again by all the citizens wanting to occupy that one space in front of the cook block.
Also several restaurants dont work cause they all seem to go to the cook that was built last.
Might be an AI issue as well but im unsure, anyways, here is a pic i took.

![image](https://user-images.githubusercontent.com/8801600/123528113-6842df80-d6e5-11eb-8e6b-054d1c4a36ca.png)

## Steps to reproduce the issue

1. Build a large city with working food chains and production chains etc.
2. Make sure you have at least one working level 3-5 restaurant with food and wait for the night or just dont hire any cooks untill villagers start to show up demanding food.
3. Hire a Cook and assistant cook and wait for the morning. The cooks will try to come to work and start distributing food but are unable to get to their stations due to the increasing numbers of clientele blocking them. They dont seem to go home for rest either while cooks do. 

### Logs

- latest.log: https://gist.github.com/starfall18/1d6622ef6a5be8b22d46eb5a84cac542
- crashlog: 

### Notes
The assistant cooks constantly seem to also have issues about getting to their workplace altogether. 

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Not sure if there is sth good we can do for this. Citizens go to the closest restaurant, so if you put them both in different corners of the colony you should get approx half of the load only.

**Comment by starfall18** [comment]
thats the funny thing... they are both on either side of the colony.
maybe you can make the citizens assable like a few blocks away from the cooks station to wait for their meal.
kinda like in a normal restaurant. People dont run into the kitchen and look over the cooks shoulder either, they wait behind the counter. In minecraft however they run into the cooking area and... well, how are you supposed to work if you are cramped by the clients as if you were on a bus at top hours XD

**Comment by starfall18** [comment]
thank you for dealing with this. Lets hope the improvements work :)
