### ISSUE TITLE
Soggyguns issue with minecolonies 

### ISSUE THREAD

**Issue by shikyojojo** [ldtteam/minecolonies#7316]
Says soggyguns wont work for minecolonies v2.9 because it was designed for older forge, when I go to load the game.

**Comment by Raycoms** [comment]
Not modpack support.

**Comment by shikyojojo** [comment]
then why on the curse forge modpack minecolonies official has it?

**Comment by shikyojojo** [comment]
> Not modpack support.
then why on the curse forge modpack minecolonies official has it?

**Comment by Raycoms** [comment]
It's for bug reports in relation to our mod, not to the modpacks.

**Comment by shikyojojo** [comment]
ah ok thankyou

**Comment by shikyojojo** [comment]
i do have a bug but not sure if its a different mod or your mod. the bug is the farmer wont plant sunflower seeds. he just walks around the farm after you give him the seeds, after you put them in the scarecrow. He will ask for the seeds but wont plant them.

**Comment by Raycoms** [comment]
That is lacking mod compatibility. There is a special place for those
requests
