### ISSUE TITLE
Pasting barracks towers in creative mode crashes the game

### ISSUE THREAD

**Issue by Thodor12** [ldtteam/minecolonies#7322]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.14.243-ALPHA-universal.jar
- Structurize Version: structurize-0.13.195-ALPHA-universal.jar
- Related Mods and their Versions: n/a

## Expected behavior
When I paste in the barracks towers through creative I expect the game not to crash

## Actual behavior
The game crashes when pasting in the building

## Steps to reproduce the issue
1. Paste in a barracks tower

### Logs
- latest.log: https://gist.github.com/Thodor12/2a877ec7d7a518d59ae42cdb3aed56b0
- crashlog: https://gist.github.com/Thodor12/37fe8b45a2c054abee137d3c8e732ad7

### Notes
n/a

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Don't paste barrackstowers
