### ISSUE TITLE
Looping Citizen Stuck

### ISSUE THREAD

**Issue by Uyarrr** [ldtteam/minecolonies#7326]
### Prerequisites 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.241
- Structurize Version: 0.13.195
- Related Mods and their Versions:

## Expected behavior
Citizens continue to their path instead of looping in same location over and over again.

## Actual behavior
While their hunger is low but not fully hungry , like in image below. They start looping around and they stay stuck forever until you give them food. I don't have restaurant yet. Interesting part is at night, they properly go and sleep. However next day, stuck again and in same spot. 
Edit: Same results for miner, looping miner climbing ladder.
![image](https://user-images.githubusercontent.com/63975845/123689936-7c5d1d00-d85c-11eb-801f-03a02e4f718b.png)
![image](https://user-images.githubusercontent.com/63975845/123690501-1fae3200-d85d-11eb-9201-26d02ec7670c.png)

If you feed them they start working back.

**Comment by Talyda** [comment]
Just adding to this, there's been several people on discord in the past week or two that have had the same thing happen - if I tell them to give them food it immediately fixes things. Have only noticed people mentioning it happening with the courier specifically too!

Oh, I had it happen on the adventure server too, but as that wasn't on the latest I didn't report it - and after I fed them that once, they were back to working as normal from then on, and only stopping for hunger when they were actually hungry.

**Comment by Uyarrr** [comment]
I've edited it, I got same results for miner, he looped forever , climbed up and down on ladder until I gave him food. I don't think it's only for courier.
