### ISSUE TITLE
Builder Shulker issues

### ISSUE THREAD

**Issue by Aduis1210** [ldtteam/minecolonies#7327]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.223-ALPHA-universal
- Structurize Version:0.13.177-ALPHA-universal
- Related Mods and their Versions: Adventure Pack by Pix

## Expected behavior
Builder able to place Shulker boxes as required by templates 

## Actual behavior

As discussed on Stream - 28/06/2021 - Issue with builder placing shulker boxes that have been opened by the player.
NBT data issue

1. Place template with shulker box as part of template - (level 5 Cave farmer)
2. give builder a opened shulker box as required by template
3. Builder has issues with the item fulfilling the resource requirements

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Bashkaaaa** [comment]
Another shulker NBT related behavior: if by accident you leave a shulker box (with some stuff inside and/or named) within the building border while a builder is upgrading, they will break the box , but no pick it up. Instead they will have an empty, unnamed box of the same colour.

Not sure if this is a bug, or just lack of implementation.

**Comment by Aduis1210** [comment]
@Raycoms HI Ray, have you had a chance to look at this yet?

**Comment by Raycoms** [comment]
Yes it's a "vanilla is meh problem". We will look into adding a way to craft opened shulkerboxes to empty shulker boxes. That's all we can do.

**Comment by nikit-nl** [comment]
Is there any update on this issue ?
I'm running on version minecolonies-1.16.5-1.0.527-ALPHA
Trying to update the courier to level 5 (Nordic) and asking for shulkerbox
The builder is taking out the shulkerbox but not using it and then asking again for it.
When i check the building with the building tool i cant seem to find the location where it needs to be so i can place it myself.

**Comment by PlanetBlonde** [comment]
I've placed the block myself -- (Cave Farm Level 5) still not working. Super frustrated, but open to suggestions.

**Comment by drcrazy** [comment]
Still a thing in 1.18 :(

**Comment by MotionlessTrain** [comment]
> Still a thing in 1.18 :(

What schematic are you trying to build? And what minecolonies version are you using?
Most of the shulker boxes have been removed from schematics by now because of this bug

**Comment by drcrazy** [comment]
I'm trying to build Warped-themed University Level 5.
Minecolonies version is minecolonies-1.18.2-1.0.872-BETA.

I've tried to edit assets\minecolonies\schematics\warped\university5.blueprint but that haven't helped. Is there some cache or data saved to world save?

**Comment by MotionlessTrain** [comment]
There is no schematic data saved in the world.
If you override the schematic, you may need to cancel and restart the build for it to take effect (the builder remembers their requests from last time)

**Comment by drcrazy** [comment]
Thank you for confirmation. It was an issue on my side. Shulker box mentioned both in palette and block entities. I've initially changed only in block entities. Change in palette helped to fix shulker box issue.

**Comment by Raycoms** [comment]
This should be solved now
