### ISSUE TITLE
Fisherman's hut crash minecraft

### ISSUE THREAD

**Issue by rexrapter1234** [ldtteam/minecolonies#733]
### Minecolonies version

version 0.6.7 or curse X.X.XX

### Expected behavior

Player can click on Fisherman's hut and the game do not crash

- XXX

### Actual behaviour

Minecraft crash playing on the server when trying to click on the fisherman's hut.

- YYY

### Steps to reproduce the problem

Make level 1 Fishmaner's hut ans than try to upgrade it to level 2 and it should crash the game when click on.

1. XYZ
2. ZYX
3. ...
4. Profit

**Comment by marchermans** [comment]
Please post a log.

**Comment by Raycoms** [comment]
[crash-2017-03-24_15.54.15-client.txt](https://github.com/Minecolonies/minecolonies/files/869338/crash-2017-03-24_15.54.15-client.txt)
