### ISSUE TITLE
Issue with accepting travelers into colony, Citizens not loading

### ISSUE THREAD

**Issue by NoobzUltra29** [ldtteam/minecolonies#7330]
**Minecolonies Version:**
Latest as of writing, ver. for 1.16.5

**Forge version**
ver. 36.1.0

**Expected Behavior**
Travelers show up at colony tavern, and are recruited in exchange for resources, becoming citizens in colony and being assigned to homes and jobs.

**Actual Behavior**
As usual, travelers show up the colony tavern, and allow me to recruit them in exchange resources. however, after clicking the button to recruit, the traveler simply disappears. checking the citizen list with /mc citizens list 1 1 shows that they are indeed part of the colony, showing their names in the list, but show no coordinates for current location, and their names do not show up in colony management, hiring/firing workers, or in housing, and said colonists are nowhere to be found. This has occurred for every colonist that is NOT an initial citizen.

**Attempted**

- Using any commands like /mc citizens teleport, /mc citizens walk, /mc citizens kill, etc, simply returns "Citizen Entity Not Loaded!"

-Restarted the game multiple times, nothing happens.

-Used the keybind F3 + T top reload textures and resource packs. Nothing happens.

-Reset the minecolonies server config file for world save, nothing happens. 

-Clicked citizen recall button on various different buildings, as well as the Worker Where-Are-You scroll. All initial citizens responded as normal. but the travelers I have accepted into the colony are still nowhere to be found.

**World Type**
A Modded Singleplayer world, with mods such as Comfortable Nether, BYG, Etc. Edited config file to allow colonies to be set in other dimensions, so this colony is set up in the nether, I have done this multiple times before in other worlds without issue.

Here are some screenshots of the given colony, just in case someone might be able to spot an issue with it:
![2021-06-29_13 04 07](https://user-images.githubusercontent.com/86681803/123846156-a0f7da00-d8da-11eb-9b6f-8a8abaf2615c.png)
![2021-06-29_13 04 19](https://user-images.githubusercontent.com/86681803/123846160-a2c19d80-d8da-11eb-8bb7-5e877b8a985b.png)

**Comment by Raycoms** [comment]
Do you have the full cost, or always only the 1 item?

**Comment by Raycoms** [comment]
Might be related with the item count displaying being wrong, so you're not actually hiring them. Because hired citizens should keep standing in front of you.

**Comment by Raycoms** [comment]
I did a bunch of tests, can you verify?

**Comment by NoobzUltra29** [comment]
This was a creative mode colony, and the travellers were hired in Creative mode, so I'm not sure how costs to recruit
travellers are handled in Creative, but it's always worked exactly how you
described it, the citizens continue to stand in front of me, but in this
specific instance, whenever I click the button, the message "-Insert name
here- has decided to stay in your colony!", but said individual just ceases
to exist in all areas except for the /mc citizens list command. Their names
and ID show up in the list, but no coordinates. It's like they were never
there to begin with.

**Comment by NoobzUltra29** [comment]
Alright, so I tried the same thing in Survival mode. Same result, they just cease to exist. After that, I tried starting a new colony, and found that citizens I spawned in with /mc citizens spawnNew worked just fine. Afterwards, something happened with a mod conflict and now the world won't load, so I'm going to need to start fresh. I'll continue to test things as I go.

**Comment by Raycoms** [comment]
Strange, I tried to reproduce it and couldn't at all, maybe any mod in
there causing it?

**Comment by NoobzUltra29** [comment]
I'll have to remove all the mods and re-add them one by one, and then go through the same tests, which might take a while, but I'll see what I can do.

**Comment by Raycoms** [comment]
Reopen if can reproduce with just MineColonies
