### ISSUE TITLE
Badly Compressed packet upon rejoining server

### ISSUE THREAD

**Issue by ronmusto2** [ldtteam/minecolonies#7331]
### Prerequisites 

- [ y] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [y ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [y ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.16.5
- MineColonies Version:0.14.238
- Structurize Version:0.13.195
- Related Mods and their Versions:None

## Expected behavior

I am able to join server
## Actual behavior

When I initially add minecolonies and structurize to my server I am able to join and use the mod fine. But when I leave the server and try to join a second time I am locked out. It gives me this error. Internal exception: io.netty,handler.codec.DecoderException: Badly Compressed packet size of 2642069 is larger than protocol maximum of 2097152. 

## Steps to reproduce the issue

1.  Add Minecolonies and structurize to server
2.  Join server, leave, then rejoin again 
3.  Get bad compression error

### Logs

- latest.log: 
- crashlog: 

### Notes

I have other mods on this server I'm not sure if there are any known incompatibilities. 
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
General forge/minecraft problem, https://www.curseforge.com/minecraft/mc-mods/connectivity should fix it.
