### ISSUE TITLE
Gradle JEI Issue

### ISSUE THREAD

**Issue by SirEndii** [ldtteam/minecolonies#7336]
- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5 - Forge 36.1.32
- MineColonies Version: 0.14.251-ALPHA
- Structurize Version: 0.13.195-ALPHA

## Problem description

I have some issues with gradle and some dependencies.
When I update JEI(from 1.16.4:7.6.1.71 to 1.16.5:7.7.0.106) Gradle can't resolve any dependency anymore. This JEI version does exist.
I want to update some other dependencies too, so I need a newer JEI version.

In the log is always the line, so I thought it's an issue with MineColonies.
```
Required by:
    project : > com.minecolonies:minecolonies:0.14.251-ALPHA
```

### Notes or related things

Logs: https://gist.github.com/Seniorendi/3bfbdda6549ab329d3fe2bf6dc34799b

I try to use mine colonies in my own mod as dependency
---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by SirEndii** [comment]
Fixed with Tarina via Discord

**Comment by SirEndii** [comment]
Nah, not fixed.
I could use the api file, but I need two classes which are not in the api package
1. `com.minecolonies.coremod.colony.buildings.AbstractBuildingStructureBuilder`
2. `com.minecolonies.coremod.colony.buildings.utils.BuildingBuilderResource`

**Comment by Raycoms** [comment]
@uecasm any idea on this?

**Comment by SirEndii** [comment]
I already took a look at his code, he uses literally the same way. *I took a little inspiration from him*

And I have no problem with the code, I have problems with gradle, jei and that minecolonies prevents me from using newer JEI versions

**Comment by SirEndii** [comment]
And this is the way how I add minecolonies
```gradle
    compileOnly fg.deobf("com.minecolonies:minecolonies:${minecolonies_version}:universal")
    compileOnly fg.deobf("com.ldtteam:structurize:${structurize_version}:universal")
```

**Comment by uecasm** [comment]
By "a little inspiration" it looks like you actually mean "entirely copying the code".  And I shouldn't have to point out that you're not allowed to take code from a GPL mod and put it into an Apache licensed mod; the licenses are not compatible in that direction.

**Comment by SirEndii** [comment]
I agree with you, I will change that.
But I did not just use copy and paste. For some things, there isn't really another way(Only for a really few things). I want to learn from others. I'm not just a lazy copy and paste person 
I know you don't care. But I hope you can forgive me. I will try to change everything

**Comment by Raycoms** [comment]
As it works fine for others, I mark this as a support issue and not as an actual issue.

**Comment by SirEndii** [comment]
> As it works fine for others, I mark this as a support issue and not as an actual issue.

So others can use the latest JEI version in their dev environment? This is the only Issue I have. I also created a new Java project in Intellij. Same issue
