### ISSUE TITLE
Required Structurize isn't forward compatible

### ISSUE THREAD

**Issue by AngleWyrm10** [ldtteam/minecolonies#7339]
### Prerequisites 

- [x] PROBLEM HERE Doesn't accept latest version of Structurize
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.238-BETA-universal
- Structurize Version:  0.13.197-ALPHA

## Expected behavior
Game starts normally

## Actual behavior
![structurize](https://user-images.githubusercontent.com/55937426/124047499-32de1080-d9c9-11eb-999a-b4fe1820ca18.png)

### Logs

- [latest.log](https://paste.ee/p/i86Pr)

**Comment by AngleWyrm10** [comment]
Linked dependency does contain the requested version on the alpha files page, but the latest ALPHA versions of Structurize are not accepted by latest Minecolonies version.

It appears to be behaving as if there's an = requirement on version number rather than a >= version number

**Comment by AngleWyrm10** [comment]
Since there is a specific and spelled-out demand for using the "latest ALPHA version" in the bug reports, I'm reopening this for your consideration.

**Comment by ravenbuilder934** [comment]
This is intentional, as sometimes the latest version of Structurize has breaking changes. Usually however the latest versions of both match (in fact I think the latest version of mcol, released a few hours ago, currently matches)

**Comment by AngleWyrm10** [comment]
So then is it accurate to say "Latest minecolony version and it's associated Structurize library"?

**Comment by ravenbuilder934** [comment]
Say that where? Wdym?

**Comment by AngleWyrm10** [comment]
This line in bug reports
- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.

**Comment by ravenbuilder934** [comment]
Yeah, that'd be accurate
