### ISSUE TITLE
Cook: Have all foods off by default or allow an all on/off toggle

### ISSUE THREAD

**Issue by Bidgam** [ldtteam/minecolonies#7340]
Due to mods providing hundreds of food options, it's tedious to turn them all off if you want the cook to bake or provide only a handful.

Please allow an option to turn all on/off en mass to allow for a small selection to be turned back.

Thanks!

**Comment by ravenbuilder934** [comment]
https://github.com/ldtteam/minecolonies-features/issues/

**Comment by Bidgam** [comment]
Oops, sorry, thanks
