### ISSUE TITLE
Minecraft crashes loading SP saved game world

### ISSUE THREAD

**Issue by kedamono** [ldtteam/minecolonies#7342]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.14.256-ALPHA-universal
- Structurize Version: structurize-0.13.197-ALPHA-universal
- Related Mods and their Versions: Forge-36.1.32

## Expected behavior

I load my saved SP game world and have it load properly.

## Actual behavior

The saved SP world starts the loading process as expected, then I get a brief view of the HUD and an brief view of sky and then the screen goes black for about 4-5 seconds, then the launcher shows an Exit Code: 0 error on the main screen.

Checking the crash logs, the error seems to indicate that there's an issue with the Mystical Site

## Steps to reproduce the issue

1. Create a SP world using a version of Minecolonies, at least 15 versions back.
2. Start a colony and as one of the buildings, build a Mystical site. To properly repro, you'll have to research this.
3. Upgrade to the .256 version of Minecolonies.
4. Start Minecraft and then try to open world.
5. World tries to load and crashes the game.

### Logs

- latest.log: https://gist.github.com/kedamono/826e10b3c37e0cdc9bbd01bf4587cd16
- crashlog: https://gist.github.com/kedamono/b7646763516b10b6c2bacd5f32bcbaf5

### Notes

I created a new world with the same custom modpack and it loaded just fine. Didn't try to start a colony, but otherwise the world was working just fine. 

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by someaddons** [comment]
which mystical site does your colony have?

**Comment by kedamono** [comment]
Sorry, it was the 2nd level Caledonia Mystical Site.

**Comment by le415** [comment]
me too.  I don't know the solution.

**Comment by le415** [comment]
> 죄송합니다. 2 층 칼레도니아 신비로운 장소였습니다.

Did it work out? If you solved it, how did you solve the problem?

**Comment by le415** [comment]
> 당신의 식민지에는 어떤 신비로운 장소가 있습니까?
Even if you turn it to the previous version, there will be a conflict if you click on the tomb and mysterious building settings.
