### ISSUE TITLE
crashed the game when i interactuated with the town hall

### ISSUE THREAD

**Issue by marcoxx12** [ldtteam/minecolonies#7346]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.224-BETA-universal
- Structurize Version: 0.13.177-ALPHA-universal
- Related Mods and their Versions: none

## Expected behavior
 interact with the town hall

## Actual behavior
when i interacted to the town hall, crashed the game 

## Steps to reproduce the issue

1. i place the town hall
2. i right click
3.  the game crashed

### Logs

- latest.log:  https://gist.github.com/marcoxx12/f1bca3be9a324591d245d11ae2b3cdcb
- crashlog: 

### Notes
 only crashd when i play in a server, in single player dont crashed the game

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.
[error.txt](https://github.com/ldtteam/minecolonies/files/6756650/error.txt)

**Comment by ravenbuilder934** [comment]
Please fill out the template
