### ISSUE TITLE
Deliveryman AI issue, attempting to handle a nonexisting request

### ISSUE THREAD

**Issue by Thodor12** [ldtteam/minecolonies#7347]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.14.259-ALPHA-universal.jar

### Logs

- latest.log: https://gist.github.com/Thodor12/bc267215d6fe6a41e470b1ba9a6d5b9a

## Steps to reproduce the issue / details
Unsure, seems to be a generic issue in the request system. "java.lang.IllegalArgumentException: The given token is not registered as a request to this manager"

### Notes
I did see a bunch of unfamiliar requests popping up in the clipboard, something was requesting wheat and glass bottles but I couldn't find any building that actually wanted those. This does match what the error message said.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
After some further investigation it seems the bakery added or changed the recipe for bread, it now takes glass bottles (filled with water) and wheat, I didn't think this was the case before or the tier 3 research of "Know the end" changed it.
Now I'm unsure whether or not this one was actually the problematic request, is it possible to include some additional information about what request it was attempting to process so that in case this error occurs again I can make a more complete repro.
If this isn't possible because it says the given token is not linked to a request, maybe consider not throwing an exception in this circumstance, it could still be logged but it wouldn't have to turn into an AI failure, if the request isn't present you could also just let it ignore the call and continue.

**Comment by uecasm** [comment]
It's not the research, the recipe changes when you upgrade the bakery to L3.

**Comment by Raycoms** [comment]
I'll pull this together with #7276 as both of them quite probably got the same origin.
