### ISSUE TITLE
Blacksmith not using best available material when crafting tools for colonists

### ISSUE THREAD

**Issue by Oraxian** [ldtteam/minecolonies#7350]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.259-ALPHA
- Structurize Version: 0.13.197-ALPHA
- Related Mods and their Versions:

## Expected behavior
When a colonist requests a new tool from the the blacksmith, it should use the best material the colonist can use.  In my setup, this should be iron tools.

## Actual behavior
The blacksmith is only crafting stone tool recipes.  He knows all wood, stone and iron recipes, and there are plenty of all materials in the warehouse.  The blacksmith hut and requesting colony huts are all level 4.  The colonists will use iron and even diamond tools normally if the player supplies them.  This behavior is the same for all tools - axe, pick, etc.

## Steps to reproduce the issue

* Make sure enough materials for iron tools are in warehouse.  Also make sure there are no tools in warehouse.
* Remove tool from any colonist to force them to request a new tool from blacksmith.
* Only stone tools are created.

### Logs

https://gist.github.com/Oraxian/8368f971ca417efb91aba63c3a1aa897

### Notes
In the recipe list, the up and down arrows do not work, so the list order cannot be changed.  I'm not sure if this related, but thought I should mention it.  In my blacksmith recipe list, the order (from top to bottom) is iron - stone - wood.  I didn't this order mattered, but I could be wrong.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
They prefer making the recipes at the top of their list whenever possible.  That's why there are arrows to reorder them.

**Comment by Raycoms** [comment]
As uecasm said, some players might want to have iron/diamond tools only crafted when its really required. So people reorder them as they see fit.

**Comment by Oraxian** [comment]
There still 2 problems here:

1. Iron tools are already at the top of my list.  The blacksmith is only crafting stone, which is farther down the list.  So based on what uecasm said, iron should be crafted.
2. The client is not letting me use the arrows to reorder the list.  This behavior is the same in all huts - I can't reorder any recipies.

Unless I'm missing something, this is not working right.

**Comment by Oraxian** [comment]
> 2. The client is not letting me use the arrows to reorder the list.  This behavior is the same in all huts - I can't reorder any recipies.
> 

Please see issue #7351 for more details
