### ISSUE TITLE
True-Dwarven-Mine Level 1 bug/issue. Mine is at y:64 but asks for better mine to start digging

### ISSUE THREAD

**Issue by Nyinxie** [ldtteam/minecolonies#7353]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.14.259-ALPHA-universal.jar
- Structurize Version: structurize-0.13.197-ALPHA-universal.jar
- Related Mods and their Versions:

## Expected behavior

Build a 'Truedwarvenmine' mine at 64 height and have the miner work

## Actual behavior

Miner tells me to upgrade their hut to dig deeper, even though we're at Y: 64.

[https://cdn.discordapp.com/attachments/741531022872674314/861086204304424960/unknown.png](url)
[https://cdn.discordapp.com/attachments/741531022872674314/861086380025053184/unknown.png](url)
## Steps to reproduce the issue

1. 
Build Level 1 'truedwarvenmine'
assign miner
2. 
bring them to you or right click them for dialog
3. 
miner tells you to upgrade their roofless cave mine so that they can do their dwarven diggy diggy hole
### Logs

- latest.log: https://gist.github.com/Nyinxie/0eafe8a97e97a12012c3363b1ce97f7d
- crashlog: N/A

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Can you send us the world? There is a minecolonies colony export command that sends us only the chunks relevant for the colony

**Comment by Nyinxie** [comment]
It's server-side and a part of a whole modpack. you want access to the
modpack + server OP?

**Comment by Raycoms** [comment]
The export command we have in the mod just extracts the necessary regions, so it should be fine.

**Comment by Raycoms** [comment]
I can't reproduce this, either you got a mod that changes the world heights or sth else is going on. I need an export or a reproduce for this.

**Comment by Raycoms** [comment]
Reopen if can reproduce
