### ISSUE TITLE
Minecolonies 0.14.266 (latest) for 1.16.5 wants Structurize 198, won't accept 199 (latest)

### ISSUE THREAD

**Issue by archonsd** [ldtteam/minecolonies#7360]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:                               1.16.5
- MineColonies Version:                        0.14.268
- Structurize Version:                             0.13.199 (latest)
- Related Mods and their Versions:

## Expected behavior

Server starts.

## Actual behavior

SMP servers fails to start, specifically saying latest Minecolonies (268) requires Structurize 198, when the latest Structurize is 199.

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

[minecraft/Main]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
Mod §eminecolonies§r requires §6structurize§r §o0.13.198-ALPHA§r
§7Currently, §6structurize§r§7 is §o0.13.199-ALPHA

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by archonsd** [comment]
Issue is still present with Minecolonies 268, same dependence on Structurize 198 and unwillingness to accept latest Structurize. (199)

**Comment by archonsd** [comment]
SSP client is able to start and create a world with Minecolonies 266 and Structurize 199, so it might be an SMP-only issue.

**Comment by uecasm** [comment]
If you have a read of the changelog at <https://www.curseforge.com/minecraft/mc-mods/minecolonies/files/3376790> it specifies a specific Structurize version.  That version and that version alone is what is supported -- not earlier, not later.  This is by design.

Hopefully, you are mistaken in your last comment, for if it did let you start with mismatched versions, **that** would be a bug.
