### ISSUE TITLE
Fletcher not crafting the string mesh when requested by the Sifter

### ISSUE THREAD

**Issue by kedamono** [ldtteam/minecolonies#7369]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.14.268-ALPHA-universal
- Structurize Version: structurize-0.13.198-ALPHA-universal
- Related Mods and their Versions: Forge - 36.1.32

## Expected behavior

When the Sifter requests a string mesh, the Fletcher would craft one in response.

## Actual behavior

When the Sifter uses up a string mesh, instead of requesting the Fletcher to craft the string mesh, they instead display the cogwheel icon over their head. When I check them, they are requesting the string mesh, listing the parts for it, but the Fletcher is not crafting it. 

I'm using the Level 1 Sifter and Level 3 Fletcher in the Caledonian style.

## Steps to reproduce the issue

1. Take away the mesh being used by the Sifter.
2. They immediately issue a request for a new one.
3. The player interaction icon appears above their head.

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
This is somewhat intended, because they're actually requesting "any mesh" and it's up to you which one you want them to use -- just that before level 3 the only option that they can actually use is the string mesh.

The intended method of operation is for you to set a minimum stock for whichever mesh you want them to use in the sifter hut, at which point it will make them automatically whenever they're used up.  Or you can request one manually at the postbox and give it to them yourself if you want them to only use it sometimes.

**Comment by Raycoms** [comment]
Hmm, I forgot about this, doesn't the interaction tell the player to setup meshes as min stock?

**Comment by kedamono** [comment]
I will double check. The min stock is set at the Sifters or the Fletcher?

**Comment by Raycoms** [comment]
Sifter

**Comment by kedamono** [comment]
That seemed to work, but the message I got from the Sifter is not all that clear as to what to do. 
![2021-07-07_08 15 30](https://user-images.githubusercontent.com/23420636/124785939-25aaaf80-defc-11eb-945a-aaf39471e48f.png)
It could be worded better. Just saying to make sure that they have a string mesh to sift with doesn't mean "set minimum stocks to include at least one string mesh." It can be interpreted as to mean "make me a mesh" which, of course, is not possible. 

A better wording could be: "Please make sure that I have at least one string mesh in stock at all times." It still keeps the wording in a roleplaying sense, but it uses the keyword "stock" that should help the player remember that minimum stocks exist.
