### ISSUE TITLE
Cook is asking player for crafting task instead of the baker

### ISSUE THREAD

**Issue by Benlog** [ldtteam/minecolonies#7372]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.14.268-ALPHA
- Structurize Version:structurize-0.13.198-ALPHA
- Related Mods and their Versions: None

## Expected behavior

The cook should forward the bread crafting task to the baker.

## Actual behavior

The cook is asking for bread crafting task to the player as we can see in the clipboard.

![2021-07-07_16 54 10](https://user-images.githubusercontent.com/10711229/124814693-9f778300-df66-11eb-999c-eb741c1f2983.png)

## Steps to reproduce the issue

1. Wait for the cook to ask the player for bread.
2. See the crafting task in the clipboard
### Logs

- latest.log: https://gist.github.com/Benlog/ff79a8a50ef1bb672621c1cd05ecd28a
- crashlog:  None

### Notes

Does crafting task supposed to be in the clipboard, should it not be bring ingredient task?

The baker is working fine (posting bost task works fine) but the bread task is not shown in the baker task list.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Strange, I can't reproduce this, can you send me your colony export?

**Comment by Benlog** [comment]
> Strange, I can't reproduce this, can you send me your colony export?

You want the save? Where I forward it?

**Comment by Raycoms** [comment]
There is a /mc colony export command, you can pm me on discord the export (pm me)

**Comment by jzisser9** [comment]
I'm still experiencing this issue. Running Minecraft 1.16.5, Minecolonies 0.14.293-ALPHA. I've tried all steps in the troubleshooting page on the wiki.

I noticed that the only way I can get my baker to fulfill my bread request is to fire both cooks at my restaurant. At that point, requests trickle down to the baker, almost making it seem like the restaurant has priority.

I've also attempted creating a new single-player creative world and placing down a cook and baker in my colony, then seeing where bread requests go, and in that case they go to the baker like they should. Is it possible my colony got corrupted somehow? What should I do from here?

**Comment by leagris** [comment]
Still having issue in `minecolonies-0.14.310-ALPHA-universal.jar`
Baker is perfectly fine and all ingredients are available:
![2021-07-25_03 16 59](https://user-images.githubusercontent.com/1111474/126884697-871dfcce-d57d-4210-99ec-67a60cbd9cc9.png)

**Comment by Moobien** [comment]
The issue stems from when Raven added some additional Pam's support if that helps Ray

**Comment by Raycoms** [comment]
Nah, not related

**Comment by Moobien** [comment]
I found a workaround for this. seems you can teach the restaraunt to cook bread dough

**Comment by Raycoms** [comment]
I can't reproduce this. At all, I need a way to reproduce this in a new world.

**Comment by Moobien** [comment]
You want a world save where its happening?

**Comment by Raycoms** [comment]
Works

**Comment by Benlog** [comment]
The colonie extract I gave you does not work?

**Comment by Moobien** [comment]
> The colonie extract I gave you does not work?

Gave him mine

**Comment by Raycoms** [comment]
@Benlog using food mods like pams?

**Comment by Moobien** [comment]
Yes. My world was tested both with mods and without and the issue only happened when mods were enabled

**Comment by Benlog** [comment]
> @Benlog using food mods like pams?

I don't think so, I just have a potion mod that add some edible items.

**Comment by EverettSummer** [comment]
I'm experiencing this issue (from 352 to now)
I'm requesting the bread and cookie, instead of the baker receive the request, the cook instead receive the request but they don't know how to make it so the clipboard just shows a recipe request for the bread. the baker doesn't work.

Is this possible caused by Lycanitemobs? I have seen it adds some food items. because I don't have Pams, the only thing I changed recently is I added Lycanitemobs and upgraded minecolonies.

I also have an issue with cook request food that I have already turned off.

**Comment by Moobien** [comment]
the current workaround is to teach the food smelting recipe to the restaraunt, or fire your assistant cook

**Comment by EverettSummer** [comment]
@Moobien I have taught the cook the bread recipe. It seems working.
Another issue is that the cook sometimes does not request high-quality food cause the restaurant to shut down. I have turned off Apple and rotten flesh in the restaurant. but sometimes, they keep resupplying those two types of food, but it actually can be feed to citizens. and even my warehouse has two stacks of raw beef. the restaurant is crowded with hungry citizens because the cook has no cooked food.
