### ISSUE TITLE
Crash when right click in fisherman´s hut inventory (sorry, in my past ticket I  attached an old crash log)

### ISSUE THREAD

**Issue by jonabrv1965** [ldtteam/minecolonies#738]
### Minecolonies version

version X.X.XXXX or curse X.X.XX

Crash when right click in fishermans hut inventory.

I apologize for the confusion. I had the unicorns mod but uninstalled several weeks ago (because of lack of support with one crash bug)

Here is the correct log, as you can see, there is no mention of any unicorn :-) as a matter of fact, I had the previous version of colonies together with unicorn and this worked fine.

[crash-2017-03-24_15.58.46-client.txt](https://github.com/Minecolonies/minecolonies/files/870009/crash-2017-03-24_15.58.46-client.txt)

As a workaround I'm extracting the contents of the fisherman hut via EnderIO Itemconduit which seems to works fine.

- XXX

### Actual behaviour

- YYY

### Steps to reproduce the problem

1. XYZ
2. ZYX
3. ...
4. Profit

**Comment by Raycoms** [comment]
did you try the newest version of curse?

2017-03-25 9:51 GMT-03:00 jonabrv1965 <notifications@github.com>:

**Comment by jonabrv1965** [comment]
Hi Ray, thank you for your promptly answer. Once again I apologize for my mistake with the crash log :-(

Oops, I just realize that you upload a new version few hours ago!! good work! and thank you very much, seem solved now!

Keep your effort! is a very nice mod with unlimited potential!
