### ISSUE TITLE
Enchanter can't harvest exp from workers

### ISSUE THREAD

**Issue by Mewcenary** [ldtteam/minecolonies#7384]
### Prerequisites 

- [Y ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [Y ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [Y ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: **1.16.5**
- MineColonies Version:  **minecolonies-0.14.279-ALPHA-universal**
- Structurize Version:  **structurize-0.13.199-ALPHA-universal**

## Problem description

**My enchanter can't harvest exp from workers, she keeps asking me to configure them and I have no idea where to do that, I've looked at the wiki and nothing is in there that explains it.**

### Notes or related things

(give the ability to marry a colonist and have a family of your own to help run the colony. lol )
---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Page 2 of the building

**Comment by Mewcenary** [comment]
Thank you, sorry I was being blind lol.
