### ISSUE TITLE
Level 1 Miner gets "Rock Bottom" advancement and won't new shafts

### ISSUE THREAD

**Issue by Graepix** [ldtteam/minecolonies#7386]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- MineColonies Version: Alpha 0.14.279
- Structurize Version: 0.13.198

## Expected behavior
A newly hired miner does not achieve the "Rock Bottom" advancement and begins digging the shaft lower.

## Actual behavior
After the completion of the miner's hut, I hired the miner and immediately received the rock bottom advancement.

The Unconstructed lower level/Cave Entrance
![2021-07-10_17 54 55](https://user-images.githubusercontent.com/33644848/125179497-80722e80-e1bc-11eb-93bd-c0c42f8ee4e9.png)

Relevant Advancement
![2021-07-10_17 55 29](https://user-images.githubusercontent.com/33644848/125179512-9bdd3980-e1bc-11eb-8bf7-9c1016ebbd06.png)

Mine Levels
![2021-07-10_17 55 10](https://user-images.githubusercontent.com/33644848/125179517-b0213680-e1bc-11eb-95f2-f9748f5f038b.png)

Miner's Stats
![2021-07-10_17 56 24](https://user-images.githubusercontent.com/33644848/125179523-badbcb80-e1bc-11eb-9b8f-100f824d6280.png)

## Steps to reproduce the issue

1. Create a colony
2. Find a location with a cave close to the surface.
3. Place the Miner's hut on top of the cave (Use the medieval oak style mine)
4. Construct the Mine at Y=64
5. Hire a Miner
6. If all goes wrong, you should get the bug

### Logs
Latest Log: https://github.com/Graepix/minecolonies-logs/blob/main/2021-07-10-1.log.tar
No crash occurred

### Notes
My miner's strength is 13 and his stamina is 15. Also I have not built any guard towers yet and my miner sleeps in the tavern which is 130 blocks away. I'm also playing on peaceful. 
My colony has a constructed Tavern lv 1, Woodcutter (MOalt) lv 1, Courier (MOalt) lv 1, Warehouse (MOalt)  lv 1, Builder (MOalt) lv 2, Farmer (MO) lv 1, Restaurant (MOalt) lv 1, and two houses (1 MO)(1MOalt) lv 1. It also has placed schematics for the townhall (MO), the library (MO), and the university MO). MO= Medieval Oak, MOalt = Medieval Oak Alternative

I relogged into the world to check the Y level the block was built at, all sound was missing and the miner briefly split into two entities the Miner and a regular citizen with a technical information name. Here's the log for that: https://github.com/Graepix/minecolonies-logs/blob/main/latest.log

I constructed my mine on top of a cave, and during construction, my builder kept teleporting into the cave and path finding her way out.

I'm playing with a custom modpack, the only mods I have that affect the world generation are Serene Seasons (version: 1.16.5-4.0.1.119) and Farmer's Delight version (1.16.5-0.4.5). Serene Seasons seems to have no affect on my other colonists, but it does change the temperature and grass color of a biome. My miner was constructed in late autumn. 
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Graepix** [comment]
I realized I hadn't tried restarting the game, that seems to have fixed it. I couldn't click on my miner, but firing him and rehiring fixed that.

**Comment by Raycoms** [comment]
I tried reproducing it but really couldn't
