### ISSUE TITLE
None of my Citizens are Building Anything

### ISSUE THREAD

**Issue by Derpercoaster** [ldtteam/minecolonies#7387]
Minecraft Version: 1.16.5
MineColonies Version: Latest version
Structurize Version: Latest version
Related Mods and their Versions: ?

Expected behavior: At least one citizen will become a builder after I place the builders hut.

 Actual behavior: Nothing happens

 Steps to reproduce the issue:
1. Place a supply camp or ship
2. Place town hall. A fence will appear around it's area
3. Wait for citizens to all arrive
4. Place builder's hut block. a 3x3 fence will appear around it, and it vanishes
5. Nothing seems to happen after this

**Comment by Oraxian** [comment]
After placing a building's hut block, you have to select it, then select "build options" and then "build building."  Do the builder hut first.

**Comment by Raycoms** [comment]
As stated above
