### ISSUE TITLE
Courier unable to bring items to warehouse.

### ISSUE THREAD

**Issue by Fjythethird** [ldtteam/minecolonies#7393]
### Prerequisites 

- [x] I am running the latest alpha version of MineColonies for my Minecraft version.
- [x] I made sure that this issue is not a duplicate of any existing issue.

### Context 

- Minecraft Version: 1.16.5
- Forge Version: 36.1.31
- MineColonies Version: 0.14.287-ALPHA
- Structurize Version: 0.13.200-BETA

### Logs

- https://gist.github.com/Fjythethird/74c408a6f6434706dd9b1c75b2bb045b

## Steps to reproduce the issue / details

Recreating the problem:
- Build Town Hall Structure
- Build Courier Structure
- Build Warehouse Structure
- Build resource gathering structure, eg. Farmer, Miner, etc Structure
- Fill center block of resource gathering structure, eg. Farmer, Miner, etc.

Expected Behavior:
- Courier will visit structures and bring excess materials back to the warehouse

Actual Behavior:
- Courier Sits in the warehouse and does nothing

### Notes

Other notes:
- Running on a server, not single player
- When you "Request Pickup Now" at a structure, the chat says, "Unable to comply, pickup already in progress!"
- When you "Request Pickup Now" at the courier structure, the courier behaves as expected and grabs resources from the courier block and brings them to the warehouse
- The Courier is able to deliver resources as requested
- Attempted both with a structure style (for all buildings possible) that contained a rack and one that didn't, neither worked

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
There were some past bugs that caused issues with requests getting stuck. Please do /mc colony requestsystem-reset colonyid to solve the problem.
