### ISSUE TITLE
can't seem to hire worker after a custom hut is built by a builder

### ISSUE THREAD

**Issue by rakostep** [ldtteam/minecolonies#7399]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.16.5
- MineColonies Version: minecolonies-0.14.288-ALPHA-universal
- Structurize Version: 0.13.200-BETA
- Related Mods and their Versions:

## Expected behavior

-Expected to have the hut block to be able to hire workers when it's constructed by the builder.

## Actual behavior

-can't hire worker and says "you must construct this hut before you can hire a worker" message even though the custom hut was already built.

## Steps to reproduce the issue

1. make custom hut (from placing the hut block on the custom hut structure) and scan it, save and copy the blueprint to the schematics folder.
2. Build the said custom hut via builder (with the hut block in inventory) 
3. after construction is finished, try to hire a worker.

### Logs

- latest.log: 
- crashlog: 

### Notes

-I can still hire workers on the custom structure but it can only be done in creative with the "instantly place structure like it was built by a builder" 

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
What does the building Ui say? Which level is it?

**Comment by Raycoms** [comment]
Did you make the building block the anchorblock of the schematic?

**Comment by rakostep** [comment]
The building UI actually works normally, with the building type and style are working as intended and the builder does build it completely. Also yes I made the building block (I assume the hut block?) as the anchorblock of the schematic.

**Comment by Asherslab** [comment]
send the .blueprint files you used here please

**Comment by rakostep** [comment]
Not sure how to upload the .blueprint file in github but I put it in a zip folder and uploaded it here.

[guardtower custom.zip](https://github.com/ldtteam/minecolonies/files/6813893/guardtower.custom.zip)

**Comment by rakostep** [comment]
Hi again, I'd like to add on that after constructing a custom hut, the fireworks don't go out, not sure if that helps out.

**Comment by Raycoms** [comment]
I believe it is because you scanned it in as "guardtower1 militia" and then renamed it instead of scanning it as "guardtower1" to begin with.

**Comment by rakostep** [comment]
ooh I see now, thank you for that, I'll try and scan it with a proper name then. Thank you very much.
