### ISSUE TITLE
Farmer Issue.

### ISSUE THREAD

**Issue by ItzBlazeMc** [ldtteam/minecolonies#7402]
### Prerequisites 

- [x] I am running minecolonies version 1.15.2 on minecraft 1.15.2 forge plus optifine.
- [x] This issue is probably a duplicate issue. But please do check it.

### Context 

- Minecraft Version: 1.15.2 forge plus optifine.
- MineColonies Version: 0.13.645-RELEASE-universal

### Logs

- latest.log: 

## Steps to reproduce the issue / details

1 - Launch minecolonies 1.15.2 with forge and optifine and hire a farmer.
2 - Build all necessary fields and such making sure that the farmer has no complaints. And the farmer doesnt have a house. -->

### Notes

Farmer has all neccessary items such as hoes and axes. Also seeds. A field is also set up. However the farmer doesnt harvest nor plant. The farmer does go to sleep and walk around. But fails to harvest and such. I am using wheat as crops and i fail to see what may be the issue. Please assist me if you can it shall be much appreciated!
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ItzBlazeMc** [comment]
Very confused as to what is the issue. Please reply as soon as possible ldtteam

**Comment by Raycoms** [comment]
Please visit our discord for support at discord.minecolonies.com.
