### ISSUE TITLE
structurize for 1.15.2

### ISSUE THREAD

**Issue by SLCPfaelzer** [ldtteam/minecolonies#7406]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2 (Coquest Reforged)
- MineColonies Version: minecolonies-0.13.645-RELEASE-universal
- Structurize Version: structurize-0.13.31-RELEASE
- Related Mods and their Versions:

## Actual behavior

https://gyazo.com/e0937655ee14bcfa0e0d9ddd548c6916

I can not find an appropriate version to resolve this.

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
https://www.curseforge.com/minecraft/mc-mods/structurize/files/all?page=4

Also please join discord for support questions. This is not really a "bug"
