### ISSUE TITLE
Builder places only bottom half of field block

### ISSUE THREAD

**Issue by WenXin20** [ldtteam/minecolonies#7407]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft v1.16.5
- MineColonies v0.14.290-alpha
- Structurize v0.13.200-beta

## Expected behavior
- Builder should place both the bottom and top halves of the scarecrow (field block).

## Actual behavior

- The builder only places the bottom half when building the medieval spruce farm.
- This means the top half of the scarecrow cannot be right-clicked to access the gui.
- Breaking and replacing the scarecrow properly places the top and bottom halves.

## Steps to reproduce the issue

1.  Build the farm
2.  Try to right-click the top half of the scarecrow
3.  Break, replace, and repeat step two.

### Logs

- latest.log: 
- crashlog: 

### Notes

- Nothing else to mention.
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Double checked #5006 schematics with old fields. Will report to the authors.
