### ISSUE TITLE
Workers using furnace waste fuel a lot

### ISSUE THREAD

**Issue by xiaobbl** [ldtteam/minecolonies#7410]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.16.5
- MineColonies Version:0.14.292 alpha
- Structurize Version:0.13.200 beta
- Related Mods and their Versions:

## Actual behavior
Workers waste fuel,thats because they seem to judge the end by the time the current fuel runs out instead of the time when product completes.
For example,my dyer makes green dye using coal.But unless the current coal runs out,he wont go getting the green dye and start the next task.If I use lava,fuel-wasting goes worse.
Similar issue is captured on stonesmelter.

## Steps to reproduce the issue

1. Let a simple task using furnace and high-quality fuel begin
2. Add a similar task.
3. watch for furnace's GUI

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Intended behavior.
