### ISSUE TITLE
Sandstone Schematic issues

### ISSUE THREAD

**Issue by visionarry** [ldtteam/minecolonies#7414]
version 289 minecolonies
not covered on wiki
not a duplicate issue
-----------------------------------------
1.16.3
minecoloines version 289
structurize 200
other mods involved none
------------------------------------------
expected= racks in builders huts and buildings not rotating when being upgraded
-----------------------------------------
instead= **Sandstone build** smeltery rotates between lvl 2 and 3 when upgraded (hut block rotates causing whole building to be torn down and rebuilt at the appropriate lvl) and zero racks in builders hut from lvl 1 through 4. 
------------------------------------------

Hello, 
     i've been building the sandstone colony and i've noticed that the builders hut from lvls 1 through lvl 4 use chests instead of racks. been playing with it this way for about a dozen versions of the game as i like to update frequently. i've also noticed that the smeltery building has a 90 degree rotation between lvl 2 and 3. 
![2021-07-17_17 11 39](https://user-images.githubusercontent.com/62813292/126049496-51c86ccb-c564-4ab3-915a-bdc489271b93.png)

**Comment by Raycoms** [comment]
#5006
