### ISSUE TITLE
Crash when trying to access minimum stock page in the library 

### ISSUE THREAD

**Issue by abadger** [ldtteam/minecolonies#7416]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.14.293-ALPHA-universal.jar
- Structurize Version: structurize-0.13.200-BETA-universal.jar
- Related Mods and their Versions: This started out as a direwolf2-1.16-1.10.1 pack.  I've upgraded minecolonies, structurize, rats-7.2.0-1.16.5.jar, and mana-and-artifice-1.4.0.7.jar.  Updated tinkers construct and mantle (TConstruct-1.16.5-3.0.4.197.jar, Mantle-1.16.5-1.6.97.jar) because they were dependencies of one of those.  Added ImmersiveRailroading-1.16.4-forge-1.8.0.1.jar, TrackAPI-1.16.4-forge-1.2.1.jar, UniversalModCore-1.16.4-forge-1.0.1.jar, and Notes-1.16.5-1.2.3.jar

## Expected behavior
Able to add items to the minimum stock in the library

## Actual behavior

Freeze followed by a crash.

## Steps to reproduce the issue

1. Level 4 Asian Library with no minimum stock currently set
2. Open the GUI.  Click on the minimum stock tab
3. Click on the Add button
4. minecraft becomes unresponsive and eventually crashes.

### Logs

- latest.log: https://gist.github.com/abadger/c615e8b018329ae1c25a8bf9c224cf2e#file-latest-log
- crashlog: https://gist.github.com/abadger/c615e8b018329ae1c25a8bf9c224cf2e#file-crash-2021-07-17_21-46-47-client-txt

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
This looks like a bug in Tetra.  Try updating it to 3.12.0 or later.

**Comment by abadger** [comment]
Confirmed.  Upgrading to tetra-3.14.1 fixes the crash.  Thanks!
