### ISSUE TITLE
Guards won't eat

### ISSUE THREAD

**Issue by MotionlessTrain** [ldtteam/minecolonies#7418]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.300-ALPHA
- Structurize Version: 0.14.200-BETA
- Related Mods and their Versions: N/A

## Expected behavior
If guards are hungry, they eat either the food in their inventory or go to the restaurant to get food

## Actual behavior
There is a guard with no saturation left, having the slowness particles around him, still patrolling the colony.
In his inventory are 6 cooked fish, and to be sure it was not a "this food is not good enough" issue, I gave him one steak.
But he refuses to eat any of them and keeps patrolling.
His "hungry" happiness modifier is red, indicating he is not happy about his current situation.

## Steps to reproduce the issue

1. Have a few guards
2. Let them work for a while
3. They won't eat.

### Logs

I could not find anything in the logs saying something about the guard, but just in case, here is the log

- latest.log: https://gist.github.com/MotionlessTrain/2a20aa18abda39ea2b4ac52da63e2835
- crashlog: 

### Notes
On discord, someone else (Thodor) was facing the same issue. All of his guards have no saturation left.
He also noticed a guard going to patrol at the restaurant, eating something, but not getting any saturation out of it.

It also seems that this problems only happens to guards. I caught both my baker and stone smelter at the restaurant after getting food there.
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
There is some "can I eat now" check in the AI that might be overreporting "nope" for guards.

**Comment by i72jilej** [comment]
I've noticed that the guards will eat if they have food in their inventories when reloading the game (if you gave them the food manually, they won't visit the restaurant). I think however that the bug persist afterwards and will not go to the restaurant when they get hungry again.
Is not a fix, but it can help until fixed.

**Comment by Inomutso** [comment]
I have the same here with MineColonies Version: 0.14.303-ALPHA
It is there, since some changes/Hotfixes with the barracks has been done
