### ISSUE TITLE
Miner does not work, keep asking for a pickaxe minimum diamond but maximum stone (!) see image...

### ISSUE THREAD

**Issue by jonabrv1965** [ldtteam/minecolonies#742]
### Minecolonies version

version minecolonies-universal-1.10.2-0.6.3277

### Expected behavior

- XXX

### Actual behaviour

- YYY

### Steps to reproduce the problem

![capture](https://cloud.githubusercontent.com/assets/13445986/24338486/60005da4-126b-11e7-884d-18d260a20538.JPG)

I supplied him with stone, iron and diamond pickaxes not to avail....

**Comment by Raycoms** [comment]
That means that you need to upgrade his hut.
He probably found obsidian or any other ore he needs a diamond pickaxe for.
But his hut level is still level 1.
