### ISSUE TITLE
AI issue builder

### ISSUE THREAD

**Issue by camilooses** [ldtteam/minecolonies#7422]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.14.280-BETA-universal.jar

### Logs

- latest.log:  https://gist.github.com/camilooses/0c4eb3c6d7f4316d8774782fb7c5ec84

## Steps to reproduce the issue / details

 send the builder to build the tavern, and he said tha have a bug with AI

Just reporting the AI issue. 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Are you building this on a superflatworld by chance?

**Comment by camilooses** [comment]
Yes

**Comment by Raycoms** [comment]
You placed your building outside of the world height. you have to place it higher. If you use superflat make sure there is at least a 20 dirt layer. Either way, I'm writing a fix to not throw an exception, but this will still continue a problem for you.
