### ISSUE TITLE
Cannot Place Supply Lines

### ISSUE THREAD

**Issue by Artyom-Strelok** [ldtteam/minecolonies#7423]
Regardless of game mode or server no one is able to place down a supply line. Using the Mineshafts and Monsters modpack. I searched the forms but there are 5,000 post so it is not easy to see if this was posted before but it was not among the open ones.

We tried on 4 different servers and with 4 different people. Solo games don't work either,

**Comment by Raycoms** [comment]
The supplycamp/supplyship you mean? What did you try? What is the error message? I will close this because we have a template for people to fill in for a reason. The information you provided is too little to solve anything.

**Comment by Raycoms** [comment]
discord.minecolonies.com has our support discord, you might want to check there.
