### ISSUE TITLE
Colonist chat gui can be opened while right-clicking in other inventories

### ISSUE THREAD

**Issue by WenXin20** [ldtteam/minecolonies#7424]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft v1.16.5
- MineColonies v0.14.303-alpha
- Structurize v0.13.200-beta

## Expected behavior
- Only access colonist chat gui when not in another inventory

## Actual behavior

- If the cursor is looking at a colonist, the chat gui can be opened while in the player inventory and right-clicking.

## Steps to reproduce the issue

1.  Point cursor at a colonist.
2.  Press `E` to open the player inventory.
3.  Right-click anywhere in the inventory.
4.  Colonist chat gui opens.

### Logs

- latest.log: 
- crashlog: 

### Notes

- Nothing else to mention.
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Okay I tested this, I can't reproduce this. I would've had a fix for if it was reproducible, but I believe another mod interferes here and since it's not a gamebreaking bug, they should fix their issues.

**Comment by WenXin20** [comment]
Here's a video of it. I've realized it only happens when standing 3 or more blocks away from the colonist. But yeah, if it's not reproducible, probably not worth pursuing. 


https://user-images.githubusercontent.com/12000593/126363631-11ad2c4d-ad48-4194-a26d-9861c56ee200.mp4
