### ISSUE TITLE
Nearby barracks towers do not make citizens feel safe

### ISSUE THREAD

**Issue by abadger** [ldtteam/minecolonies#7428]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.14.293-ALPHA-universal.jar
- Structurize Version: structurize-0.13.200-BETA-universal.jar
- Related Mods and their Versions:

## Expected behavior
citizens whose workplace is near a barracks tower would feel protected.

## Actual behavior

citizens complain that there is no guard or barracks towers near their workplace.

## Steps to reproduce the issue

1. have an asian barracks with barracks towers adjacent to a black smith/combat academy/archery
2. See that the citizens employed at the lack smith, combat academy, and archery complain that there is no guard or barracks tower near their workplace.

### Logs

- latest.log: 
- crashlog: 

### Notes

I first noticed this while playing minecolonies-0.14.293-ALPHA-universal.jar (the changelog for that version and several previous versions note changes to the barracks and barracks towers).

I'll download minecolonies-0.14.305-ALPHA-universal.jar to make sure this hasn't been fixed but I did not see any changelog entries that seemed relevant.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by abadger** [comment]
I have confirmed that upgrading to 0.14.305-ALPHA does not fix this problem.

**Comment by uecasm** [comment]
This is related to the order in which things are built.  Upgrade or repair the not-guard-tower building and they'll notice the guard tower at that point.

(Think of it like a neighbourhood watch list posted on the wall of the building -- the builder is the one who updates the list, and the citizens get nervous if their list is empty.)

**Comment by abadger** [comment]
I'll test that out tonight.  However, I will note that all of these buildings (blacksmith, archery, builder, combat academy) have been upgraded or built more recently than the barracks towers.  Was these buildings "forgetting" that they are built near a barracks towers a one-time bug or is it going to be an ongoing issue every time I stop my world?

**Comment by abadger** [comment]
My builder just finished a repair job on the archery.  The archers-in-training still report that there are no guard towers nearby despite being kitty-corner from one.  So I think this bug is different than simply being about which order things are built in.

**Comment by Inomutso** [comment]
I have the same here with MineColonies Version: 0.14.310-ALPHA
This Issue is in the colony, for a long time already
