### ISSUE TITLE
The interface is too small

### ISSUE THREAD

**Issue by Circling007** [ldtteam/minecolonies#7434]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.16.5
- MineColonies Version:0.14.308-ALPHA
- Structurize Version:0.13.200-BETA

## Problem description

The interface is too small
### Notes or related things

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
..*What* interface?

**Comment by uecasm** [comment]
It would help if you included a screenshot showing what you mean.  But also note that you can resize the Minecraft window and/or change the GUI Scale setting to fix most such issues.

**Comment by Raycoms** [comment]
Closed until further detail is given.
