### ISSUE TITLE
Decoration Controller NOT storing path

### ISSUE THREAD

**Issue by Moobien** [ldtteam/minecolonies#7436]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 14.237 (schem server) / 14.306
- Structurize Version: 13.195 (schem server) / 13.200
- Related Mods and their Versions:

## Expected behavior

you input the path and file name in the decoration controller and it saves it.
## Actual behavior

it does not save the information

## Steps to reproduce the issue

1.  make a deco, add a deco controller
2.  add path information and level in correct boxes
3.  NOTHING happens beyond it saving file name

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Moobien** [comment]
seems to store the path, until you scan the schematic at which point it scans without the path and the 'path' field changes to the schem name only.

**Comment by someaddons** [comment]
fixed
