### ISSUE TITLE
Shepherd AI issue

### ISSUE THREAD

**Issue by 1Litre** [ldtteam/minecolonies#7437]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.16.5
- MineColonies Version:0.14.310

### Logs

- latest.log: 
- 
https://gist.github.com/1Litre/4143a4a46c61fd2a0624f01a2e85a508

## Steps to reproduce the issue / details

The shepherd requested to report the issue.
The shepherd does not produce anything.

Just reporting the AI issue. 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
```
	at love.marblegate.flowingagony.eventhandler.CapabilityEventHandler.lambda$AbnormalJoyCapEvent$1(CapabilityEventHandler.java:38) ~[flowingagony:1.16.5-beta-0.4.3]
```

This mod can't handle fakeplayers killing.
