### ISSUE TITLE
Crash to desktop on adding minimum quantities in Builder hut

### ISSUE THREAD

**Issue by Nihilhalla** [ldtteam/minecolonies#7438]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.294-BETA
- Structurize Version: 0.13.200
- Related Mods and their Versions: CodeChickenLib-1.16.5-4.0.2.429-Universal, ProjectRed-1.16.5-4.10.0-beta-46-core, ProjectRed-1.16.5-4.10.0-beta-46-integration, ProjectRed-1.16.5-4.10.0-beta-46-transmission {A bunch of others but these ones appears to be the conflict judging by the crash report)

## Expected behavior
A menu screen should show up allowing me to fiddle with the settings

## Actual behavior
A crash to desktop occurs with the below crash report

## Steps to reproduce the issue

1. Install the aforementioned mods (CodeChickenLib, Project Red Core, Project Red Integration and Project Red Transmission)
2. Do all steps necessary to have a level 1 Builder's hut
3. Click the add button in the minimum stock tab

### Logs

- latest.log: https://gist.github.com/Rainemakerx/799fb261975faa77a46a47fbf62d2d2f
- crashlog: https://gist.github.com/Rainemakerx/0533556aa22fa544b030073c30ca1c27

### Notes
I believe the issue is isolated to project red, but there may be other mods affected by this kind of crash, if I encounter further issues I'll try to point them out, if for no other reason than to increase awareness so that they can be solved for other users.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Nihilhalla** [comment]
I've updated to the latest version of both Minecolonies and Structurize for the purpose of seeing if the issue was fixed without having been mentioned in a patch note. 
EDIT: Structurize version is 13.202 because Minecolonies 14.310 won't launch with 13.203
EDIT2: Crash is still present even with latest possible Minecolonies and Structurize. Suspect it's an issue with ProjectRed in general but advice on how to fix, or if a fix is possible, would be welcome.

**Comment by Raycoms** [comment]
```
at codechicken.microblock.ItemMicroBlock$.getFactory(ItemMicroBlock.scala:113) ~[?:1.16.5-3.0.2.119] {re:classloading}
	at codechicken.microblock.ItemMicroBlock.func_200295_i(ItemMicroBlock.scala:25) ~[?:1.16.5-3.0.2.119] {re:classloading}
	
```

Can you check with them as well? This seems to be crashing on their side. They don't like changing itemStacks on the client side

**Comment by Nihilhalla** [comment]
Submitted a bug report on the Project Red Issue Tracker on GIT

**Comment by Raycoms** [comment]
https://github.com/TheCBProject/CBMultipart/issues/95

part of this
