### ISSUE TITLE
Magnetic Fisherman

### ISSUE THREAD

**Issue by Moobien** [ldtteam/minecolonies#7440]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 310
- Structurize Version: 202
- Related Mods and their Versions:

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

Mainly a suggestion here. was watching my fisherman doing his thing and noticed that an average of 3/5 fish fly over the fisherman when hooked, screenshot shows where the fish landed. my suggestion is to increase the magnet strength on fisherman to try to mitigate this. 

https://imgur.com/fkEsYv1
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Moobien** [comment]
in the 5 minutes it took me to type up the issue and edit the screenshot, I ended up with 19 fish in my inventory, fisherman had 5 in his, from the airborne fish.

**Comment by someaddons** [comment]
fixed, fisher is now much better at this
