### ISSUE TITLE
Planter not correct plant cactuses 

### ISSUE THREAD

**Issue by tanaliko** [ldtteam/minecolonies#7441]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.310
- Structurize Version: 0.13.202 
- Related Mods and their Versions:

appleskin-forge-mc1.16.x-2.1.0.jar
AutoRegLib-1.6-49.jar
Bookshelf-1.16.5-10.1.12.jar
caelus-forge-1.16.5-2.1.3.0.jar
carryon-1.16.5-1.15.5.15.jar
CraftingTweaks_1.16.5-12.2.1.jar
crashutilities-3.11.1.jar
curios-forge-1.16.5-4.0.5.2.jar
curiouselytra-forge-1.16.5-4.0.2.3.jar
Cyclic-1.16.5-1.3.3.jar
DynamicTrees-1.16.5-0.10.0-Beta19.jar
findme-1.16.3-2.2.0.0.jar
gravestone-1.16.5-1.0.6.jar
hole_filler_mod_1.2.4.1-mc_1.16.x-forge.jar
Hwyla-Mod-1.16.3.jar
invtweaks-1.16.4-1.0.1.jar
jei-1.16.5-7.7.1.2.jar
jeiintegration_1.16.5-7.0.1.15.jar
journeymap-1.16.5-5.7.3.jar
JustEnoughResources-1.16.5-0.12.1.121.jar
Mantle-1.16.5-1.6.115.jar
minecolonies-0.14.310-ALPHA-universal.jar
moreoverlays-1.18.15-mc1.16.5.jar
MouseTweaks-2.14-mc1.16.2.jar
NaturesCompass-1.16.5-1.9.1-forge.jar
Neat+1.7-27.jar
OreExcavation-1.8.157.jar
Quark-r2.4-316.jar
SimpleStorageNetwork-1.16.5-1.4.0.jar
storageracks-1.4.jar
structurize-0.13.202-ALPHA-universal.jar
TConstruct-1.16.5-3.1.0.231.jar
tl_skin_cape_forge_1.16.5-1.17.jar
WailaHarvestability-mc1.16.x-forge-1.1.15.jar

## Expected behavior
Planter plants and harvest cactuses 

## Actual behavior
Cactus planted together and destroyed

## Steps to reproduce the issue

make medieval plantation, upgrade to 4 level (as i remember issue reproduced on level 3) , set to produce cactus, give cactus item to worker. see that worker try to plant two cactuses next to each other

https://imgur.com/a/QOFi0bH

### Logs

- latest.log: https://gist.github.com/tanaliko/06b3fc1b712264420e22039b6bed3321

**Comment by Raycoms** [comment]
Was this during upgrade?

**Comment by tanaliko** [comment]
No. No actual building upgrade. I try to repair building, but problem exists during repair and after repair

**Comment by tanaliko** [comment]
Seems to be fixed after discover "Double Trouble" at University
