### ISSUE TITLE
Game crashes when player tries to use Pharaoh Scepter

### ISSUE THREAD

**Issue by sweg4552** [ldtteam/minecolonies#7443]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.310-ALPHA
- Structurize Version: 0.13.202-ALPHA
- Related Mods and their Versions:

## Expected behavior

Pharaoh Scepter shoots fire arrow as it used to

## Actual behavior

Game crashes when releasing the arrow

## Steps to reproduce the issue

1.  Fire up minecraft
2.  Try to shoot with pharaoh scepter
3.  Game crashes

### Logs

- latest.log:  https://gist.github.com/giggity404/5571f98a87725a0764211484c2c81c67
- crashlog:  https://gist.github.com/giggity404/b3bd60797452597bc1399bce452e1063

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
fix pushed
