### ISSUE TITLE
Builder can't finish the town hall

### ISSUE THREAD

**Issue by Sensray** [ldtteam/minecolonies#7447]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.314 ALPHA

### Logs

- latest.log: https://gist.github.com/Sensray/0f1fc7aa2d746518b779206681b07faa.js

## Steps to reproduce the issue / details

No idea how to reproduce the issue. I've tried to get the builder to build the town hall 4 times. 3 times with the Medieval Dark oak alternative, 1 time with the Medieval Oak alternative. For the medieval dark oak town hall, every time the builder gets to the part where he needs to put down the torches and campfire he stops and stands at either the side of the incomplete hall (same spot every time) or in the builder's hut. The attempt with the medieval oak alternative is the same as the other 3 attempts except the carpets and oak signs are not placed as well. The builder will always have the last item he was using before the torches (typically stairs or fence) in his hands even though the item is not in his inventory. The builder has no issues finishing other buildings such as the builder's hut, houses, and a watch tower. 

Strangely as I was typing this, I watched him chop a door down from the outside of the building. I gave him back the door as he did not try to go inside and get it. He is still standing at the side of the building, holding the door. All of what he needs to finish the hall is in his inventory and he's just standing there.

### Notes

I have played this world on LAN but all attempts to build the town hall were not on LAN
I also have 270+ mods (mod incompatibility maybe?)
I have attempted to fix the glitch by: 
*giving him the item he is holding
*beating him to trigger a flee response
*killing him
*replacing the builder
*feeding the builder
*canceling the work order
*emptying some of his inventory into the builder hut
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Sensray** [comment]
Update: The builder managed to place the door but is still standing in the same place. He will occasionally wander off only to return to either the builder's hut or his favorite standing spot. I also forgot to mention I started the town on 0.14.311 BETA and updated to 0.14.313 ALPHA and finally 0.14.314 ALPHA with the hope that the problem would be fixed.

**Comment by Raycoms** [comment]
This is lacking some info, building level? to which level? rotated? mirrored?

**Comment by Raycoms** [comment]
How long did you wait?

**Comment by Sensray** [comment]
Building level 1, rotated to face the north, not mirrored. A few hours for the first 2 tries, 30 mins for the 3rd, 1 hour for the 4th. I ended up switching to creative to manually place the town hall.

**Comment by Raycoms** [comment]
It's because those medieval alternative townhall are enormous, and they actually will mostly likely take a few real world hours to complete. There is a ton of area to scan, and we don't scan thousands of blocks at a time because else you'll get serious lag.

**Comment by Sensray** [comment]
Oh sorry, I meant to say that time was after the builder finished the initial building. Each building took around ~40mins and he had no trouble building it. The builder stops when it's time to place the torches and the building is never complete.

**Comment by Raycoms** [comment]
Yes, the last step takes quite long, because of the air scans. I'll try it on a day off myself quickly.
