### ISSUE TITLE
AI getting stuck in building (Medieval Spruce Courier lv4+)

### ISSUE THREAD

**Issue by Aleksejus1** [ldtteam/minecolonies#7448]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.314-ALPHA

### Logs

- latest.log: https://gist.github.com/Aleksejus1/ebe1149ec794dfb1a1da4a2434ac4f41

## Steps to reproduce the issue / details

Build level 4 medieval spruce (not alternative) courier house and have the builder attempt to build level 5.
What will happen is that the builder will enter into one part of the building and get stuck unable to leave. So far I've seen the same happen to my guard.

### Notes

Here's an image of where they're getting stuck, it's a space between two trapdoors on both sides, somehow they enter there, and then get stuck with only recall as the option to get them out
![image](https://user-images.githubusercontent.com/12628681/127274288-9c71b445-9004-46c1-bc50-e0e614c6e088.png)

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
That's okay. Builders will most likely get stuck in some buildings. They will unstuck themselves after some time.

**Comment by Raycoms** [comment]
There is literally nothing we can do about this.

**Comment by Aleksejus1** [comment]
> That's okay. Builders will most likely get stuck in some buildings. They will unstuck themselves after some time.

Do other professions do the same? I didn't wait for my archer to get out, but would he after a while?

**Comment by Raycoms** [comment]
Yes
