### ISSUE TITLE
Archer Guard not gaining any Damage from Agility before 50

### ISSUE THREAD

**Issue by MantelKun** [ldtteam/minecolonies#7457]
### Prerequisites 

- [no] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [yes] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [yes] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.310 Alpha universal
- Structurize Version: 0.13.202 Alpha universal
- Related Mods and their Versions: All The Mods 6 modpack

## Expected behavior

Archer Guard dealing at least 5 Attack Damage at 20 Agility (If he would deal 1 Damage [0.5 Hearts] at 0-4 Agility)

## Actual behavior

The Archer damage does not increase whatsoever in the levels at or below 20. It doesnt matter what bow he is using (Tested Vanilla bow and Dragon Bone Bow from ice and fire)

https://youtu.be/aVZNTPGiJM4 

## Steps to reproduce the issue

1.  Use a Guard
2.  Assign it as Archer
3.  Its damage doesnt Increase probably before reaching 50 Agility

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
It's not a linear increase at all.
