### ISSUE TITLE
Builder constructs and then deconstructs the roof of the University continuously

### ISSUE THREAD

**Issue by SandWitch016** [ldtteam/minecolonies#7459]
### Prerequisites 

- [no] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [yes] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [yes] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 1.13.645-RELEASE-universal
- Structurize Version: 0.13.109-ALPHA-universal
- Related Mods and their Versions: -

## Expected behavior
 The builder places down the stoneshingle slabs and finishes the building.

## Actual behavior
 The builder places down all the stoneshingles, then immediately deconstructs them, then places them down again, and keeps repeating this loop over and over again.

## Steps to reproduce the issue

1.  Build a Medieval Oak University.
2.  Have the builder complete the building up until they reach the part where they need to place down the stoneshingle slabs.
3.  The builder will get himself stuck in a loop of building and deconstructing the stoneshingle slabs.

### Logs

- latest.log:  https://gist.github.com/SandWitch016/862bf97704afd1ffc46b0ff3d568f526
- crashlog: 

### Notes
 If I cancel the build request then request it again, all the items needed to finish the build (torches, poppy, dandelion, grass) will be replaced by 8 dirt blocks and 3 gravel blocks.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Unfortunately we're not offering any mayor fixes reworks for 1.15.2 anymore, as that is a very old version. You can visit our discord for extended support on what you can do to fix this at discord.minecolonies.com

**Comment by SandWitch016** [comment]
Oh, that's ok. I'll try updating my version of minecolonies to see if that changes anything. Thanks anyway!
