### ISSUE TITLE
"Free Block" interaction not working really well. Create a tool to add them to the gui. [$5 awarded]

### ISSUE THREAD

**Issue by Wissi** [ldtteam/minecolonies#746]
The "free block" in the pg 3 Permissions tab in TH GUI.

When the position of a block is set there, the block should be open to interaction for "anyone" (whether, hostile, neutral, friend, etc).

Does not work. When position of a Diamond chest is set, NO one can access it. and a 0 0 0 free block is always present, when it is erased and GUI is reopened it will still appear.

**Comment by Raycoms** [comment]
yes 0 0 0 will stay. The position of the block must be quite exact I tried
it a few times and failed. But after a few attemps I got it right. Other
players got it right as well. I tested it with them on the server

2017-03-28 0:33 GMT-03:00 Wissi <notifications@github.com>:

**Comment by kedamono** [comment]
Perhaps we should have a "free block" wand, that way you can just right click the item to add it?

**Comment by Wissi** [comment]
>Perhaps we should have a "free block" wand, that way you can just right click the item to add it?

That was my initial "fool proof" suggestion, sssoo I second the idea   xP

@Raycoms can it be do-able?
