### ISSUE TITLE
Villagers slide on backs instead of walk

### ISSUE THREAD

**Issue by RainbowAfro** [ldtteam/minecolonies#7461]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5 forge 36.2.1
- MineColonies Version: 0.14.317-ALPHA-universal
- Structurize Version: 0.13.205-ALPHA-universal

## Problem description

Villagers seem to walk as usual, but sideways. Only affects some villagers, such as my miner, cook, and fisher. Others seem to function as normal, whereas the affected villagers slide across the ground on their backs. I am unsure of how to reproduce the issue on different worlds, but it happens upon every load of the world the issue seems prevalent on. 

### Notes or related things

I have a video of the issue here, of my cook: 

https://user-images.githubusercontent.com/88349780/127928152-f09a15da-1d34-4c10-96bc-1b5bcbe7bc24.mp4

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
This happens because you're using Optifine.  Turn off the "Smooth World" setting in its options.

**Comment by RainbowAfro** [comment]
I've turned off "Smooth World." Same thing happens.

**Comment by RainbowAfro** [comment]
> This happens because you're using Optifine. Turn off the "Smooth World" setting in its options.

I've turned off "Smooth World." Same thing happens. I have even COMPLETELY removed optifine from my mods folder and it remains the same.

**Comment by ravenbuilder934** [comment]
Have you tried punching and/or recalling them?

**Comment by Raycoms** [comment]
How do you reproduce this?

**Comment by RainbowAfro** [comment]
> Have you tried punching and/or recalling them?

Yes! Thank you, this seems to be the issue. After a good decking they seem to be working as normal- looks like the game thought they were still in bed. Didn't know punching was such an effective solution.

**Comment by uecasm** [comment]
When you turn off the setting or remove optifine, any affected citizens will remain affected until the next minecraft day, or until you recall/punch them.
