### ISSUE TITLE
Currier IA broken after a while

### ISSUE THREAD

**Issue by AVFD** [ldtteam/minecolonies#7462]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.14.314-ALPHA-universal
- Structurize Version: structurize-0.13.205-ALPHA-universal

### Logs

- latest.log:  https://gist.github.com/AVFD/fb16d790550229390dbc7621382d16ec

Line 718 (where is the problem I think).

## Steps to reproduce the issue / details

1. Play for a long time, like 3 or 4 hours.
2. I have a Wooden Warehouse lvl 4, and I came to check some stuff when I saw one of my Curries with the message.
![image](https://user-images.githubusercontent.com/18308993/128111033-404b6135-ae8c-4125-a7dc-b292cf5f4ed3.png)
3. I paused and restarted the worker, but didn't work.
### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Was fixed in 315/316 with some chance of old corrupt requests that need to be cleaned up with /mc colony requestsystem-reset-all
