### ISSUE TITLE
Guards that set on patrol with manual positions still keep the building visiting behavior in automatic mode

### ISSUE THREAD

**Issue by warning-djkajslh** [ldtteam/minecolonies#7463]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- MineColonies Version:
- Structurize Version:
- Related Mods and their Versions:

## Expected behavior

Guards will go to designated position points and ignore building's blocks.

## Actual behavior

If there is any building nearby, they will decide to step out of the line and go chill inside the building

## Steps to reproduce the issue

1. Set patrol mode to manual
2. Assign some points near a building
3. Watch.

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
This is due to the waypoint systems, guards will visit nearby waypoints close to the route.
