### ISSUE TITLE
How to change the owner of a colony in world files

### ISSUE THREAD

**Issue by JackNyckless** [ldtteam/minecolonies#7465]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.310-ALPHA
- Structurize Version: 0.13.202-ALPHA

## Problem description

We have played with friends online in the world. But for some reason, one of them had to change their account (nickname). Because of this, he lost access to his colony. Tried to change Owner_ID and Owner in saves/"world"/minecolonies/minecraft/overworld/colony1,2,3.dat, but it didn't work. Please tell me what needs to be changed in the world files to change the owner of the colony?

### Notes or related things

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
don't change it in the dat, use the /mc colony setowner command, for more support discord.minecolonies.com
