### ISSUE TITLE
Citizen stuck at restaurant with food in inventory

### ISSUE THREAD

**Issue by leagris** [ldtteam/minecolonies#7466]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

This issue is **not a duplicate, but a follow-up on related: https://github.com/ldtteam/minecolonies/issues/7442**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.14.321-ALPHA
- Structurize Version: structurize-0.13.205-ALPHA
- Related Mods and their Versions: Forge 36.2.2

## Expected behavior

Citizen shall not get stuck at restaurant.

## Actual behavior

After a couple hours up-time, citizen get stuck at restaurant having eaten food, but not going to bed despite overdue bedtime.

https://imgur.com/a/rMyrJ2l

**Stuck at restaurant, with overdue sleep:**

![Stuck at restaurant, with overdue sleep](https://i.imgur.com/8myLA2n.png)

**Has valid edible vanilla cooked food:**

![Has valid edible vanilla cooked food](https://i.imgur.com/GciWLEO.png)

## Steps to reproduce the issue

1. Build a restaurant
2. Get many Citizens like 50 (helps reproducing the bug with higher chance)
3. Wait a couple hours and see citizen at restaurant past bedtime, not returning to bed, eventually complaining he needs sleep, with inventory containing some food.
4. Restart game
5. Citizen unstuck, go to bed without eating food.

### Notes
Follow-up on related issue: https://github.com/ldtteam/minecolonies/issues/7442

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by AVFD** [comment]
In my case, the citizens stuck in the same spot (chair).
![image](https://user-images.githubusercontent.com/18308993/128430859-b7a06139-0580-4324-9fc1-3c77516f2b85.png)

The cooker give food but the citizens don't ate till I make the citizens walk a little.

For a while I notice my citizens are only accepting bread to eat, but the cook isn't ordering food from baker.

**Comment by leagris** [comment]
With a large colony (town size and above). Multiple citizens are stuck at restaurant each night despite restarting the game each minecraft day.

**Having to restart the game every Minecraft day to unstuck citizens from the restaurant is a real burden that is wiping all sense of game-play**

Please make it possible to disable the need for food and the restaurant until this bug is fixed.

**Comment by MotionlessTrain** [comment]
I'm afraid the issue moved. I had a courier standing next to her courier hut, stating she was hungry. She did not accept the bread I gave her, and did not go to bed at night. Recalling her to her hut block did nothing. Only when I teleported her to the restaurant, she started walking to one of the chairs. After the cook gave her food, she ate it and went on with her job

**Comment by tecnobrat** [comment]
I can confirm that what MotionlessTrain mentioned is happening for me as well on 0.14.323-ALPHA which should have had #7475 in it.

**Comment by MotionlessTrain** [comment]
It is fixed (again) in 0.14.324-ALPHA

**Comment by leagris** [comment]
Thank you @Raycoms, it is really fixed this time.
