### ISSUE TITLE
Minecolonies NPC's walks extremely wrong when outside of chunk. MULTIPLAYER.

### ISSUE THREAD

**Issue by yaoxiaosa** [ldtteam/minecolonies#7469]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.16.5
- MineColonies Version:minecolonies-0.14.280-BETA-universal

### Logs

- latest.log: no log

## Steps to reproduce the issue / details

First installation module
Second, a distance beyond the working citizen
Third, citizens began to twitch

### Notes
I found a lot of solutions to the relationship sponge in the issue. Unfortunately, I use spigot. I can't learn from it. I hope I can get a solution
---
## Viewers
thanks
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Then configure MineColonies entities to have a larger entity activation range with spigot
