### ISSUE TITLE
[Request] Alternate Blocks For Crafting Tables

### ISSUE THREAD

**Issue by Darkosto** [ldtteam/minecolonies#747]
### Minecolonies version
1.10.2-0.6.3277 on Curse

The Builder's hut level 2 needs Crafting Tables for correct construction, and my modpack does not use vanilla tables. I absolutely love MineColonies and think it works really well for the pack idea. Is it possible to allow an alternate crafting table to be used in its place so users can upgrade their colonies?

Thank you very much for your consideration!
Darkosto

**Comment by Raycoms** [comment]
hmm you can rescan the builder hut with your custom table and put it in the
jar of your modpack. That'd work =)

2017-03-28 14:37 GMT-03:00 Darkosto <notifications@github.com>:

**Comment by Darkosto** [comment]
Will Curse allow altered jar files in public modpacks?

**Comment by Raycoms** [comment]
Should be no problem.

2017-03-28 14:42 GMT-03:00 Darkosto <notifications@github.com>:

**Comment by Darkosto** [comment]
Alright, thank you!

**Comment by xavierh** [comment]
@Raycoms I wonder If I should add an option to NOT use the schematic from the jar?

**Comment by Raycoms** [comment]
@xavierh like an option to only enable style from folder and not from jar?

2017-03-30 10:41 GMT-03:00 xavierh <notifications@github.com>:

**Comment by xavierh** [comment]
@Raycoms that's right, if a server only want to use it own huts because they want a specific  theme to it, it would be better to disable schematic  from the jar and only use the folders one.
In my branch the only way is to override all schematics

**Comment by Raycoms** [comment]
Sure I think that would make sense.

2017-03-30 12:16 GMT-03:00 xavierh <notifications@github.com>:

**Comment by Raycoms** [comment]
Soon to come feature.
