### ISSUE TITLE
Minecolonies NPC's walks extremely wrong when outside of chunk

### ISSUE THREAD

**Issue by yaoxiaosa** [ldtteam/minecolonies#7470]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.16.5
- MineColonies Version:minecolonies-0.14.280-BETA-universal

### Logs

- latest.log: no log

## Steps to reproduce the issue / details

First installation module
Second, a distance beyond the working citizen
Third, citizens began to twitch

### Notes
I found a lot of solutions to the relationship sponge in the issue. Unfortunately, I use spigot. I can't learn from it. I hope I can get a solution

---
## Viewers
thanks

**Comment by Raycoms** [comment]
Just making a new issue won't solve it. There is nothing we can do on our side. You gotta configure spigots entity activation range and talk with their staff, not us.
