### ISSUE TITLE
Builder leaves blocks with invalid / not-updated block-state

### ISSUE THREAD

**Issue by leagris** [ldtteam/minecolonies#7474]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.321-ALPHA
- Structurize Version: 0.13.205-ALPHA
- Related Mods and their Versions: Forge 36.2.2

## Expected behavior
Builder shall update the block-state of blocks it places

## Actual behavior
After placement, some blocks are left with invalid block-states:
- Glass panes, iron bars not connected to their neighbour block.
- Walls on top of roof invisible because in an invalid state
- Shingle slabs ending straight at air because their block-state does not reflect there is no connection to air.

**Walls becomes visible if placing a blocks near them to force a block-state update**.
![Invisible walls](https://i.imgur.com/UbFrITq.png)

**Iron Bars not connected left because block-state not updated**
![not-connected iron bars](https://i.imgur.com/E0Hutg8.png)

## Steps to reproduce the issue

1. Let builder build a Medieval Dark Oak Blacksmith Hut
2. See no wall poles on top of roof
3. Climb atop of roof and place blocks.
4. See hidden poles made of wall blocks now visible because they have updated their block-state.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
can you confirm if those blocks are connected correctly in the schematics?

**Comment by leagris** [comment]
Block is not updated, and without update connection state will not update.
When two stages of a schematic have same block but with different state, like here, the state is not updated when building the next stage.

**Comment by leagris** [comment]
Issue still valid.
