### ISSUE TITLE
Builder not building

### ISSUE THREAD

**Issue by TerraStella** [ldtteam/minecolonies#7476]
### Prerequisites 

- [y ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [ y] I made sure that **this issue is not a duplicate of any existing issue.**

### Context  0.14.316 beta

- Minecraft Version: 1,16,5
- MineColonies Version: 1.16.5

### Logs

 dont know how

- latest.log: 

## Steps to reproduce the issue / details

trying to get the builder to build the town hall, medieval dark oak alternative level 1. (I also updated my structurize as well). I am in the extreme hills biome

Just reporting the AI issue. 

### Notes
The builder will not place torches. So I placed them for him in the right places. Now the town hall says I need no other blocks to finish the build but the builder still wont say its finished. So I took out a block, canceled and restarted the build, again (I have done this several times as well) and they went and finished it by putting the block back and STILL wont recognize the building is finished. The builder just stands around in or around the hut not doing anything while the builders tab still says they're working. When I upgraded their hut to level 2, they did that build quickly with no issues placing torches. It seems like the issue is the town hall. I made sure they were fed, they arent sick, they do not ask for any supplies because the building is done. I have tried killing the builder, I tried firing and rehiring SEVERAL times including hiring different ones. I tried restarting them several times. I have given them MANY days in game to finish scanning and several days later they are still standing around saying they are working on the building. I tried restarting the game multiple times as well. I do have mods but none of them effect torches and the minecolonies has no other issues to speak of and doesnt appear to be conflicting with anything else. I have tried to research this issue A LOT and no answers were given. I cant really progress if I cant update this town hall as its town perimeter, at its basic point, is incredibly small and limiting unless I am able to update the town hall

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
I've put fixes for the newest beta surrounding this issue. Please update.
