### ISSUE TITLE
Mystical Site Crashes The Game When Trying To Open Build Menu

### ISSUE THREAD

**Issue by sarkubocael** [ldtteam/minecolonies#7477]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.65.5
- MineColonies Version: 0.14.325-Beta-universal
- Structurize Version: 0.13.207-Alpha-universal
- Related Mods and their Versions: 

## Expected behavior

Game not crashing when i click build button on mystical shrine to upgrade it to level 2

## Actual behavior

I have a mystical shrine built to level one no issues, but when i open its GUI and click build option where it should open the window to repair, build or deconstruct, list of materials and builder picking it actually crashes the game.

## Steps to reproduce the issue

Build mystical shrine then try to upgrade it to level 2.

1.  Build shrine level 1
2.  try to upgrade it to level 2 by upening its GUI and clicking build button
3.  Crashes the game

### Logs

- latest.log: 
- https://gist.github.com/sarkubocael/d5a35cd96ab38e90399ee03ba96160f1
- crashlog: 
-https://gist.github.com/sarkubocael/f2c126944ef7fd6c8d343375515a83ed

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Which mystical site, which level?

**Comment by sarkubocael** [comment]
Stone Version of the Mystical Site forgot to mention that, but as it says its just fresh built level 1, when i try to upgrade it to level two it crashes.

**Comment by uecasm** [comment]
Not related to the crash, but you have a massive amount of recipe errors in those logs from other mods.  You and/or the pack author should probably look into that.

I believe this specific error was fixed in mcol 279, but you might still be affected if you originally built the site prior to that.  Try breaking the hut block and then replace it and repair the building; that should fix it.

**Comment by sarkubocael** [comment]
ok il try to do that, recipes are managed by another mod, so far i havent had issues.

**Comment by sarkubocael** [comment]
New version/updated game changed the model, after breaking the block the mystical site works. thank you.
