### ISSUE TITLE
My citizen just told me to report an AI issue despite not appearing to have one on the surface

### ISSUE THREAD

**Issue by SandWitch016** [ldtteam/minecolonies#7478]
### Prerequisites 

- [no] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [yes] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15,2
- MineColonies Version: minecolonies-0.13.645-RELEASE-universal

### Logs

- latest.log:  https://gist.github.com/SandWitch016/e4d9dca7a97320d1a5271fb873f2dd5c

## Steps to reproduce the issue / details

 

Just reporting the AI issue. 

### Notes
 She seems to work just fine, I don't get why she's complaining. Could this be a false alarm?

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Yeah this is a bug that is still present in 1.15 but was fixed in 1.16 already.

**Comment by SandWitch016** [comment]
Alright, thanks!
