### ISSUE TITLE
Complete wipe of recipes by "double deleting" the same recipe

### ISSUE THREAD

**Issue by Teldrik** [ldtteam/minecolonies#7479]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.327-BETA
- Structurize Version: 0.13.208-ALPHA
- Related Mods and their Versions: Modpack: Life in the Village 2 version 1.24. Minecolonies and Structurize have been manually kept up to date.

## Expected behavior
Able to delete without accidentally wiping the hut block's entire list of recipes.

## Actual behavior
Easy accidental wipe of full recipe list if you are deleting recipes too quickly.

## Steps to reproduce the issue

1: Have hut block with recipes (builder, carpenter, blacksmith etc.)
2: Have multiple recipes within the said block.
3: When clicking on the delete button for a recipe, click on it multiple times in rapid succession before the UI has time to update that the recipe has been deleted.
4: Weep.

### Logs

- latest.log: https://gist.github.com/Teldrik/000fa82787870e66ea05b4d161e1d2a3
- crashlog: N/A

### Notes
---
First encountered when playing on version 0.14.321. Updated to version 0.14.327 and the recipe wipe can still be done.
Forcing it to occur causes this line to appear in the log: [Server thread/WARN]: Failure to remove recipe, please tell the mod authors about this
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by EverettSummer** [comment]
I am using 368 version, the issue is still there. the recipes are all added in the old versions. but yesterday when I accidentally double click the remove button, all recipes got removed.
