### ISSUE TITLE
Farmer and Forester interfaces lack a "Minimum Stock" tab

### ISSUE THREAD

**Issue by SomewhatDamaged** [ldtteam/minecolonies#7483]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.328
- Structurize Version: 0.13.208
- Related Mods and their Versions: Forge 36.2.0

## Expected behavior
Like all the other worker buildings, there should be a Minimum Stock tab on Forester and Farmer buildings.

## Actual behavior
There is no Minimum Stock tab on the Farmer or Forester building interface

## Steps to reproduce the issue

1. Place farmer/forester
2. Open farmer/forester interface
3. There is no Minimum Stock tab on the interface

### Logs
No logs needed.

### Notes
The main reason for this would be to be able to keep tools on hand and ready to go should the worker run out.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
We have left them out on purpose atm as we were not sure how they will behave in terms of interference with crafting. I think it makes sense to add them to those workers atm to see how they behave with it tbh.
