### ISSUE TITLE
The courier does not work

### ISSUE THREAD

**Issue by TimLiz** [ldtteam/minecolonies#7487]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.14.328-ALPHA-universal.jar
- Structurize Version: structurize-0.13.208-ALPHA-universal
- Related Mods and their Versions: Valhelsia 3-3.4.1

## Expected behavior

The courier must pick up unnecessary items
The courier must deliver the items

## Actual behavior

The courier is just standing in the warehouse.
If the colonists order items, it is visible in their panel, but it is not visible in the courier block, and the courier is just standing in the warehouse

https://wmpics.pics/di-F9QR.png
https://wmpics.pics/di-0QDX.png
https://wmpics.pics/di-OHX5.png
## Steps to reproduce the issue

I don't know, I just built it and it doesn't work

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by TimLiz** [comment]
log
https://gist.githubusercontent.com/TimLiz/bc4680986f3e913afb9faa6e1f5b9740/raw/feb2a0250cc684be44c207eb870e9586e1236f34/gistfile1.txt

**Comment by Raycoms** [comment]
Yeah, there was a past issue with that, keeping them stuck, you have to run /mc colony requestsystem-reset 1 (if 1 is your colony id) /mc whereami to know your colony id.

**Comment by jojo2357** [comment]
I had the same issue but im playing on a server that nobody really goes on and when i run `/mc colony requestsystem-reset 1` it says "This command is disabled in the config" and when i run `/mc colony requestsystem-reset-all` it says "Must be OP to use this command". Is there a workaround here for me or am i stuck with a bum for a courier? I do not have access to any of the config files or anything since it is not my server and the server owner isnt around either.

**Comment by Raycoms** [comment]
When I get some time soon, I'll do some more fixes around these things and will push a force-reset in, for all colonies like yours.

**Comment by jojo2357** [comment]
Ok sounds good! Just bummed that i am stuck with no courier since i am the courier as of now.
