### ISSUE TITLE
Minecolonies Universal 1.11-0.6.3282

### ISSUE THREAD

**Issue by DriznaVv** [ldtteam/minecolonies#749]
### Minecolonies version

version Universal 1.11.3282 or curse X.X.XX

### Expected behavior

- Placing a forge, bakery, or Quarry and works
- Deliveryman delivers items with no issues

### Actual behaviour

- Can't place these three with a builders wand, and when placed by hand block breaks game. The block won't build, and when you break it, it's still there invisibly glitched. If you place another block it reappears. This also causes parts of buildings already built to glitch invisibly as well. The glitching is so powerful tnt won't blow it up.

- Deliveryman works for a small while, then when the game has been running for quite a long time, AI breaks, and then he starts to fill up with crazy things, and delivers them to everyone instead of what's being ordered. I reset the time to keep people working cause I want to see the town in full in creative. So not sure if it's the resetting of time, or it's just a leak. Requires an entire shut down of the game to reset these parameters.

- Also when I try to config the game the button is greyed.

- Also under permissions in the town hall, there's a button with no description, but toggle active. If clicked it kills the game fully. No error, just crashes out back to desktop.

- Also pathing is weird. I have ample room between buildings for the people to move through, and they will move through warehouse, or around all other buildings to get to the destination. The builder especially does this, and sometimes will stand a mile away while working on a building. So building is being built, but builder is no where to be seen.

### Steps to reproduce the problem

1. XYZ
2. ZYX
3. ...
4. Profit

**Comment by DriznaVv** [comment]
By the way forgot to mention it's under forge that I am using this with other mods.

**Comment by DriznaVv** [comment]
Another issue I have seen. When you upgrade the houses, it's beautiful looking, but with more than one person in there hilariousness insues. The AI is programmed to use only one of the two doors, and I've seen them both trying to leave, so when one opens the door, the other closes it causing them to be stuck in the building with no way out. Possible solution. Alternate back doors, or maybe somehow have them be able to use both doors to leave?

**Comment by DriznaVv** [comment]
Also would it be a possibility to have a manual of some sort to explain things, and what the benefits are to upgrading different buildings? I know the homes will hold more people, and the builder can upgrade to it's current level. However, the mines, the sawmill, townhall, deliveryman, etc. I don't know what benefits are to upgrading these buildings. Since the people level up, any chance of having a stats change happen every certain amount of levels? Since the starting people are usually low in different stats. What about being able to improve them either a school, or in the building they are working at.

Also would it be possible to say have more than one person working in a building? Most companies in real life have more than one person working usually. Thanks. :) You are probably gonna get annoyed with me in here. :)

**Comment by xavierh** [comment]
One issue = one bug please.
Some of the bugs you describe already have a issue.

Also quarry forge and bakery are not
 implemented yet

**Comment by DriznaVv** [comment]
Oh my apologies then. I got super excited. :P

**Comment by DriznaVv** [comment]
I apologize for this, but do you have a link for general bug reporting, and suggestions? That way I can bookmark it, and know where to go.

**Comment by xavierh** [comment]
@DriznaVv no need to apologise btw.
A link for general bug reporting ? Not sure that I understand the question. Could you expand it ?

**Comment by Raycoms** [comment]
Can you open a new issue for still existing problems?
