### ISSUE TITLE
the builder does not accept the clock

### ISSUE THREAD

**Issue by TimLiz** [ldtteam/minecolonies#7490]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.14.328-ALPHA-universal
- Structurize Version: structurize-0.13.208-ALPHA-universal
- Related Mods and their Versions: Valhesia 3

## Expected behavior

The builder takes the clock and puts it in a frame
## Actual behavior

The builder does not accept the watch, it remains in his inventory, and he does not use it

## Steps to reproduce the issue

Start the construction of a building in which the builder will use the clock

### Logs

- latest.log: https://gist.githubusercontent.com/TimLiz/1ed1d5c454c70fec31bde4d825eb522f/raw/6396a58d3ecbf5772482271d4298d90b6749865a/log

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Well known quark compatibility issue. Disable quark clock changes in config.
