### ISSUE TITLE
Carpenter abilities are scalling off incorrect skills

### ISSUE THREAD

**Issue by starmun-0010** [ldtteam/minecolonies#7494]
- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered here.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context
From the wiki:
![image](https://user-images.githubusercontent.com/5557278/129453301-a013b54e-89c6-4a58-b0e6-6c18d2a8fedf.png)

Which makes Dexterity to be primary skill and Knowledge secondary. But from the [code](https://github.com/ldtteam/minecolonies/blob/a73d1241693d4c4aa178451a9ef86e1dfae99c5a/src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingSawmill.java#L87) in BuildingSawmill it is exatly the opposite.

```
    public Skill getPrimarySkill()
    {
        return Skill.Knowledge;
    }
    public Skill getSecondarySkill()
    {
        return Skill.Dexterity;
    }
```

- Minecraft Version: 1.16.5
- MineColonies Version: 0.15.328-ALPHA
- Structurize Version: 0.13.208-ALPHA
- Related Mods and their Versions:

## Expected behavior
Primary skill should return Dexterity and secondary should return Knowledge.

## Actual behavior
The methods return incorrect skill values.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
this is actually an issue with the wiki not the mod, open an issue here https://github.com/ldtteam/MinecoloniesWiki/issues
