### ISSUE TITLE
Bug serveur 

### ISSUE THREAD

**Issue by Rinkimedoenzoc** [ldtteam/minecolonies#7496]
Bonjour messieurs je envoie se mail car avec des amis nous voudrions jouer à minecolonies sur un hébergeur OuiHeberg mais le mod me demande d’activer les placements des colonies dans d’autres dimensions. Le fichier est bien activer mais le message qui dit d’activer le fichier reste. Comment je peux le résoudre. Merci de votre réponse. ( langue:française)

**Comment by Raycoms** [comment]
Please fill in the entire template and make an attempt to translate what you did to english, even if you use google translate.

**Comment by Rinkimedoenzoc** [comment]
Hello gentlemen, I'm emailing friends, we would like to play minecolonies on a OuiHeberg host but the mod is asking me to enable colony placements in other dimensions. The file is activated, but the message that says to activate the file remains. How can I solve the whole thing. Thank you for your reply.

**Comment by ravenbuilder934** [comment]
Please fill out the template and make sure you're on the latest version of minecolonies
