### ISSUE TITLE
Builder won't place torches or finish building

### ISSUE THREAD

**Issue by bubblebearneedshelp** [ldtteam/minecolonies#7504]
Basically the builders will build something nearly to completion without any issues but then run around in circles once they have to start placing torches. They have all necessary materials and aren't requesting anything. I've tried firing and rehiring them, recalling them, letting them eat until their full, fully restarting them, hiring new builders, cancelling and restarting all build requests, punching them, I even placed blocks to let them go on the roof that they were spinning under, they climbed the stairs and started pacing back and forth before going back down. I've tried everything that I've found online and nothing has fixed them. pls help I am so tired

**Comment by Raycoms** [comment]
There is a template, please fill it in.
