### ISSUE TITLE
NPE when opening the requests GUI of unemployed citizen

### ISSUE THREAD

**Issue by leagris** [ldtteam/minecolonies#7505]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.14.336-ALPHA
- Structurize Version: structurize-0.13.208-ALPHA
- Related Mods and their Versions: Forge 36.2.2

## Expected behavior
No crash

## Actual behavior

NPE crash opening the Requests of unemployed citizen

## Steps to reproduce the issue

1. Have unemployed citizen
2. Open unemployed citizen GUI and click on the Open requests tab
3. Instant NPE crash

### Logs

- latest.log: https://gist.github.com/leagris/7862998e6f64a0d45d3b04c665bce36f#file-latest-log
- crashlog: https://gist.github.com/leagris/7862998e6f64a0d45d3b04c665bce36f#file-crash-2021-08-17_01-56-26-client-txt

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Fixed

**Comment by leagris** [comment]
Was fast dude!
