### ISSUE TITLE
Builder doing nothing

### ISSUE THREAD

**Issue by PricelessMile0** [ldtteam/minecolonies#7507]
The builder is standing in front of the builder's workbench doing nothing, whilst in the middle of a build request. The build request is stuck on step 0/5 without progressing further. Recalling the worker doesn't fix this, however firing and re-hiring the builder does fix it, displaying 'I've started work on [building]', but when the builder goes to sleep and the back to the builder's hut to carrying on with the work it gets stuck on step 0/5 again with no progress on the build request.

**Comment by Raycoms** [comment]
Please fill in the entire template.
