### ISSUE TITLE
Client Crash when trying to add Minimum Stock for a building

### ISSUE THREAD

**Issue by Gizmo0320** [ldtteam/minecolonies#7508]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5-36.2.0
- MineColonies Version: 0.14.339-ALPHA
- Structurize Version: 0.13.208-ALPHA
- Related Mods and their Versions:

## Expected behavior

To be able to add Minimum Stock for buildings 

## Actual behavior

When trying to add an item to the Minimum Stock list the game crashes. It only crashes client side not server.

## Steps to reproduce the issue

Try adding minimum stock 

### Logs

- latest.log: https://gist.github.com/Gizmo0320/077e2a8e4b9d25ae3b901fcc9a6b40fc
- crashlog: https://gist.github.com/Gizmo0320/65c694fdde37e78943b031fc1f63b1e2

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
Are you using ~~a custom style that includes~~ Chisels & Bits microblocks?  Because that's what appears to be the cause of your crash.

You also have a lot of other mods that are spamming the logs with errors, most notably Citadel.

**Comment by Raycoms** [comment]
Is a problem on the side of: https://github.com/Chicken-Bones/ForgeMultipart, this bug was reported there already

**Comment by TheCommensuratePup** [comment]
@Raycoms I am also experiencing this & I didn't pull in ForgeMultipart nor microblocks. I am completely unable to access any minimum stock for any worker.

Also not important to my scenario, but the repo you mention above hasn't had any check ins in over 6 years nor bugs reported in several months not sure what bug report would be involved in this.

**Comment by ravenbuilder934** [comment]
I think ray means https://github.com/TheCBProject/CBMultipart/issues/95

**Comment by TheCommensuratePup** [comment]
Interesting, that's an array out of bounds exception, I'm not getting that, the issue I'm seeing is an init error:

	

> at com.minecolonies.coremod.client.gui.WindowSelectRes.<init>(WindowSelectRes.java:94) ~[minecolonies:0.14.345-ALPHA] {re:classloading}
> 	at com.minecolonies.coremod.client.gui.modules.MinimumStockModuleWindow.addStock(MinimumStockModuleWindow.java:98) ~[minecolonies:0.14.345-ALPHA] {re:classloading}
> 	at com.minecolonies.coremod.client.gui.AbstractWindowSkeleton.lambda$registerButton$2(AbstractWindowSkeleton.java:96) ~[minecolonies:0.14.345-ALPHA] {re:classloading}
> 	at com.minecolonies.coremod.client.gui.AbstractWindowSkeleton.onButtonClicked(AbstractWindowSkeleton.java:122) ~[minecolonies:0.14.345-ALPHA] {re:classloading}
> 	at com.ldtteam.blockout.controls.Button.handleClick(Button.java:104) ~[structurize:0.13.210-ALPHA] {re:classloading}
> 	at com.ldtteam.blockout.Pane.click(Pane.java:553) ~[structurize:0.13.210-ALPHA] {re:classloading}
> 	at com.ldtteam.blockout.views.View.mouseEventProcessor(View.java:394) ~[structurize:0.13.210-ALPHA] {re:classloading}
> 	at com.ldtteam.blockout.views.View.mouseClickableEventHandler(View.java:347) ~[structurize:0.13.210-ALPHA] {re:classloading}
> 	at com.ldtteam.blockout.views.View.click(View.java:217) ~[structurize:0.13.210-ALPHA] {re:classloading}
> 	at com.ldtteam.blockout.BOScreen.func_231044_a_(BOScreen.java:196) ~[structurize:0.13.210-ALPHA] {re:classloading}
> 	at net.minecraft.client.MouseHelper.func_198033_b(MouseHelper.java:87) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}

**Comment by MotionlessTrain** [comment]
Update. This has been fixed in later versions
