### ISSUE TITLE
beekeeper not breeding bees

### ISSUE THREAD

**Issue by leagris** [ldtteam/minecolonies#7512]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.14.337-ALPHA
- Structurize Version: structurize-0.13.208-ALPHA

## Expected behavior
Beekeeper's hut setting to breed bee, beekeeper should request flowers and mate breed bees (seeing hearts and baby bees

## Steps to reproduce the issue

1. Get a beekeeper hut and beekeeper worker, assign area with beehives or the beehives from the hut building
2. Fill beehives with bees.
3. Wait a few Minecraft days, and see bee population decaying

### Notes

Even providing the beekeeper with flowers, he does not breed or mate bees.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Did you enable flowers in the apiary?

**Comment by leagris** [comment]
Yes I did enable flowers and even set minimal stock, but bees decaying anyway I never see newly breed baby bees

**Comment by Raycoms** [comment]
Might be not enough florists or other reasons for decay. Can you watch the beekeeper carefully if they never actually breed? Maybe there is just too much work for them and you have to get another one.

**Comment by Raycoms** [comment]
Double checked. This works fine, you might not have enough florists just.
