### ISSUE TITLE
About the colony's authority

### ISSUE THREAD

**Issue by JVhuaA** [ldtteam/minecolonies#7513]
- Minecraft Version:1.16.5
- MineColonies Version:minecolonies-0.14.327-BETA-universal

Here is the situation, after I set my other ID as officer in the server
It is not possible to open chests in the colony and will be attacked by guards.
In addition, all professions have several duplicate requests for equipment they already have, such as the diamond sword.

**Comment by Raycoms** [comment]
We need more info, is this LAN mode?

**Comment by JVhuaA** [comment]
> 我们需要更多信息，这是局域网模式吗？

It's Internet, but it's still being tested, and the target player was not online (via City Hall) when granting permissions in previous tests. Probably granting permissions when the object does not exist is not effective.

**Comment by Raycoms** [comment]
Did you maybe remove the other permissions in the permission settings?

**Comment by JVhuaA** [comment]
I gave my friend officer permission without changing permission settings. But using my friend's account to open chests will be attacked by guards.

**Comment by Raycoms** [comment]
So you turned on the "attack guards" permission on.

**Comment by JVhuaA** [comment]
It's not very clear if it's a permission-on problem. But after giving the officer permission, you still can't open the boxes in the colony. But using /mc colony addofficer 1 @a command, it's fine (although the owner also becomes an officer).
