### ISSUE TITLE
feature better 2-pass, silk-touch recycle deconstruction

### ISSUE THREAD

**Issue by leagris** [ldtteam/minecolonies#7515]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.14.340-ALPHA
- Structurize Version: structurize-0.13.208-ALPHA

## Problem description

1. When deconstructing, the builder loose blocks that cannot float in air (lanterns, torches, ladders…).
2. Glass is broken, grass, long grass is lost.

This cause material loss.

![2021-08-19_19 54 27](https://user-images.githubusercontent.com/1111474/130120943-208d2901-df3a-4050-a1d7-d91a3dff73f5.png)

### Notes or related things

1. To prevent falling blocks as items, the builder could deconstruct in two passes the inverse of the building passes.
2. Block that do not drop themselves could be harvested with proper tool like shearing or silk-touched. 
    This could be an university technology research for recycling, at various levels.

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by someaddons** [comment]
thats normal, deconstruction was never intended to be a fully loss-less process
