### ISSUE TITLE
Problem with Structurize version

### ISSUE THREAD

**Issue by TheEvilEye05** [ldtteam/minecolonies#7516]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context  

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.13.437-RELEASE-universal
- Structurize Version: structurize-0.13.100-RELEASE-universal

## Problem description
When i try to run minecraft with this mod, it says I need the 0.13.96 version of structurize
![image](https://user-images.githubusercontent.com/84248306/130147884-2b29df46-6b8e-4753-b14d-840a23d09a0f.png)
And when I try using that version, it says this:
![image](https://user-images.githubusercontent.com/84248306/130148289-1d8986a6-e108-4456-9a88-580687dfa68c.png)

### Notes or related things

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Not an issue, use the latest alpha of minecolonies

**Comment by TheEvilEye05** [comment]
I tried that, and well it's true. Thank you and I'm sorry.
