### ISSUE TITLE
[1.16.5] Builder gets stuck when upgrading Asian-style house from T1-2

### ISSUE THREAD

**Issue by GamertechAU** [ldtteam/minecolonies#7517]
### Prerequisites

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.340-ALPHA
- Structurize Version: 0.13.208-ALPHA
- Related Mods and their Versions:

## Expected behavior
Builder successfully completes construction without manual aid.

## Actual behavior
The builder completes the addition to the rear of the house with them inside creating a sealed room with no way in/out, causing them to get stuck until the player breaks the wall or recalls them.

They wont remove the original wall until they complete the roof and areas at the front they can't get to.

Reproduced 2/2. Upgrading houses to T3 & 4 have no issues.

## Steps to reproduce the issue

1. Complete a tier 1 house using the Asian style
2. Request an upgrade to tier 2 and allow it to progress
3. Once the builder completes the walls for the rear expansion, they become stuck in the new room and cannot progress
4. Freeing the builder allows them to complete as normal

### Logs

N/A - Construction order issue

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
That is actually okay. We added different build modes unlockable via research where some won't result in this. They might get stuck, but they will eventually teleport out.
