### ISSUE TITLE
Client crashes when opening postbox

### ISSUE THREAD

**Issue by Dryelo** [ldtteam/minecolonies#7518]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- Forge Version 36.1.16
- MineColonies Version: minecolonies-0.14.338-BETA-universal
- Structurize Version: structurize-0.13.208-ALPHA-universal
- Related Mods and their Versions: Enigmatica 6 pack with a couple of manually added mods

## Expected behavior

Postbox GUI appears

## Actual behavior

Minecraft client crashes

## Steps to reproduce the issue

1.  Place postbox in colony
2.  right-click postbox
3.  postbox GUI appears

### Logs

- latest.log: 
- crashlog: 
- https://gist.github.com/Dryelo/7e276ab805ffb6e15316f4cf94192366

### Notes

 edit: Am I using github gist correctly?
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
It's actually not us crashing but one of the other mods. We're just rendering it. You'll have to try out to find out which of the mods causes this and then report it to them.

**Comment by someaddons** [comment]
likely one of those: placebo astralsorcery tetra dankstorage losttrinkets itemfilters quark

**Comment by MotionlessTrain** [comment]
I’ve seen an error like this before where tetra was the problem. It gives no guarantee for this issue, but you could try updating tetra and see if that fixes it

**Comment by Dryelo** [comment]
Thanks for the help. I'll try removing the mentioned mods one by one and/or updating them.

**Comment by Dryelo** [comment]
it was Tetra... again  :(
Thanks for pointing me in the right direction!

**Comment by MotionlessTrain** [comment]
You're welcome!
