### ISSUE TITLE
Opening postbox after update crash the game

### ISSUE THREAD

**Issue by AVFD** [ldtteam/minecolonies#7521]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.14.343-ALPHA-universal
- Structurize Version: structurize-0.13.210-ALPHA-universal
- Related Mods and their Versions: jei-1.16.5-7.7.1.116

## Expected behavior

Open my postbox and order some stuff.

## Actual behavior

After update my mod to the lastest version, when I try to use my postbox the game crash.

## Steps to reproduce the issue

1. Have a previous version of minecolonies installed
2. Update to the lastest version
3. Try to open your postbox (the postbox should contain any itens)
4. W8 until the game crash and open a log.

### Logs

- latest.log: 
- crashlog: https://gist.github.com/AVFD/4c84cc865e5b6005747dd2d6b29ff00d

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
Downgrade to 342 for the moment, this appears to only exist in 343.

**Comment by starmun-0010** [comment]
Still crashing with 346
[crash-2021-08-24_22.27.04-client.txt](https://github.com/ldtteam/minecolonies/files/7041016/crash-2021-08-24_22.27.04-client.txt)

**Comment by MotionlessTrain** [comment]
This is an issue with forge multipart, on their side. A microblock cannot be rendered properly. It is already on their github tracker (https://github.com/Chicken-Bones/ForgeMultipart)
