### ISSUE TITLE
Miner stopped digging and gives an error.

### ISSUE THREAD

**Issue by SteelTarkus** [ldtteam/minecolonies#7523]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.343-ALPHA

### Logs

- latest.log:  https://gist.github.com/SteelTarkus/b6a0df6737dccbf9e0a9850e0158b4ca#file-gistfile1-txt

## Steps to reproduce the issue / details

Hi all, I have a problem with my miner. She stopped digging her mines. I built level 3 mine in nordic style and after I updated my minecolonies from 0.14.340-ALPHA version to 0.14.343-ALPHA she stopped working. Now she descends into the mine, goes to one of her shafts and stands with message which says to send a latestlog file. She asigned to y:11 and made 32 nodes.I started my colony on version 0.14.327-BETA then updated the mod every 4-5 days and this error never appeared until today.  In the log the error starting at Line 209. 

### Notes

If I roll back to 0.14.340-ALPHA version, she work normal and digs new nodes.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
fixed
