### ISSUE TITLE
Miner getting AI error after a while and then stuck on it

### ISSUE THREAD

**Issue by AVFD** [ldtteam/minecolonies#7524]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.14.344-ALPHA-universal

### Logs

- latest.log: https://gist.github.com/AVFD/85b6a5b3ce1258a5e3f6f4106e457d96

## Steps to reproduce the issue / details

I really don't know if this is the correct steps to reproduce, but this is what I did.

1. Build a miner with medievaloakalternative style.
2. Upgrade the miner hut to lvl 2.
3. Let the Miner work for a while (40+ nodes).
4. Upgrade the miner to lvl 3.

### Notes
I noticed other things such, the miner sometime put floating torches like this the next img:
![image](https://user-images.githubusercontent.com/18308993/130429791-cf5dfcb3-06a4-453d-a425-732b05211d4a.png)

And the other thing, the miner started to prepare to continue digging down but stopped (probably because of the AI error), see the next img:
![image](https://user-images.githubusercontent.com/18308993/130430266-62f90da6-3a97-4420-ac0a-8b683492a768.png)

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
fixed
