### ISSUE TITLE
Miner AI issue

### ISSUE THREAD

**Issue by justin9900** [ldtteam/minecolonies#7526]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.16.5
- MineColonies Version:minecolonies-0.14.343-ALPHA-universal

### Logs

- latest.log: https://gist.github.com/justin9900/ff64b83b425e7d2557f65a7f67634b8c

## Steps to reproduce the issue / details

Miner goes down into the mine gets to the spot where he would mine next then gets the ai error and just stands there menacingly and its only happening on this version of minecolonies/structurized, The previous versions i was using in this world were minecolonies 0.14.327 beta universal and structurized 0.13.208 alpha
![miner](https://user-images.githubusercontent.com/33006371/130481698-df9e55b5-fdab-44cf-ab58-fad7f296c53a.png)

Just reporting the AI issue. 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
already fixed in the newest
