### ISSUE TITLE
Blacksmith doesn't "see" the warehouse stock

### ISSUE THREAD

**Issue by MotionlessTrain** [ldtteam/minecolonies#7529]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.345-Alpha
- Structurize Version: 0.13.210-Alpha
- Related Mods and their Versions:

## Expected behavior

When the player requests a diamond axe via the post box, the blacksmith would request three diamonds and two sticks from the warehouse in order to craft said axe

## Actual behavior

When I requested the diamond axe, the request for diamonds ended up in the clipboard rather than as a delivery request.
The carpenter was asked to make the two sticks, while there are 1000 sticks in the warehouse.

I tried resetting the request system and restarting minecraft, and both didn't help.

Some screenshots: 

The warehouse stock:
![Schermafbeelding 2021-08-24 om 00 20 59](https://user-images.githubusercontent.com/6672741/130526847-dcf228d0-dd00-4df7-9bca-7bb5cf1bb31a.png)
![Schermafbeelding 2021-08-24 om 00 21 29](https://user-images.githubusercontent.com/6672741/130526882-e08a6be4-1dd7-46f2-9e6b-527f6b864a8f.png)

Crafting recipe at the blacksmith:
![Schermafbeelding 2021-08-24 om 00 24 06](https://user-images.githubusercontent.com/6672741/130527097-34305e52-f308-47d2-b80b-6d75cb881021.png)

Postbox gui:
![Schermafbeelding 2021-08-24 om 00 26 17](https://user-images.githubusercontent.com/6672741/130527342-379568e0-59b5-425c-aa6e-7723b1896818.png)
![Schermafbeelding 2021-08-24 om 00 26 44](https://user-images.githubusercontent.com/6672741/130527383-aaf903ca-bf68-42df-9f39-7c46b0dc3203.png)

Clipboard:
![Schermafbeelding 2021-08-24 om 00 28 48](https://user-images.githubusercontent.com/6672741/130527563-982b7f33-5102-42b3-a3f5-39c1f4ae68c7.png)

## Steps to reproduce the issue

1. Teach the blacksmith the diamond axe recipe
2. Make sure there are enough diamonds and sticks at the warehouse
3. Request a diamond axe at the post box
4. (In my case) watch it request the diamonds and sticks from anywhere but the warehouse
### Logs

The logs don't show request system requests.

- latest.log: 
- crashlog: 

### Notes

On discord, it looks like someone had a similar issue with a builder's hut. One of the builder's huts got all of the materials they needed, while the other one was requesting items to the player that are in the warehouse. Cancelling does requests didn't help.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Can you reproduce this? Can you send export the colony?

**Comment by MotionlessTrain** [comment]
I can reproduce this in my colony.
My colony export:
[colony1Export.zip](https://github.com/ldtteam/minecolonies/files/7035292/colony1Export.zip)

**Comment by Raycoms** [comment]
I loaded this up, and it worked fine for me. Is this on a server? Should I try this in smp?

**Comment by MotionlessTrain** [comment]
It is a singleplayer world

**Comment by Raycoms** [comment]
I could reproduce it without my recent changes, so they seem to fix this =P

**Comment by MotionlessTrain** [comment]
Good to know. Some sort of predictive patching: writing a solution for a problem you didn't know existed 😄
