### ISSUE TITLE
Crashing Server with Minecolonies Permission interacting with "Actually additions"

### ISSUE THREAD

**Issue by djpanda** [ldtteam/minecolonies#753]
### Minecolonies version

minecolonies-universal-1.11-0.6.3282.jar

### ActuallyAdditions version

ActuallyAdditions-1.11.2-r106.jar

### Expected behavior

- no problems with other mods 

### Actual behaviour

- there seems to be problems at the permissions and other mods using fakeplayerevents
### Steps to reproduce the problem

1. build a minecolonie 
2. place a longrangebraker from actually additions at the protected area and let him do his work

Log attached ->  https://pastebin.com/DgEFkL7j
Issue posting @ Acctualy Additions GIT -> https://github.com/Ellpeck/ActuallyAdditions/issues/729

**Comment by Raycoms** [comment]
Will be fixed in the next version =)
Please see it seems like the longrangebraker from actually additions
doesn't seem to use your UUID to break things. Therefore he isn't allowed
to do anything in your colony.

2017-04-01 18:38 GMT-03:00 djpanda <notifications@github.com>:

**Comment by djpanda** [comment]
Yes thats what i was thinking too and thats why i was sending the issue cause it has to be covert in code or the other way i was thinking of maybe it works as a workaround to add the fakeplayer to the userlist of the Townhall but therefor i had to know the name Actually Additions are using and that i didnt

**Comment by Raycoms** [comment]
We actually handle them if the other mod implements it correctly.
If the fakePlayer has the same UUID as his placer (which is the way
fakePlayers should be implemented) he will be allowed to work inside your
colony.)
But still, if it hasn't been implemented accordingly it shouldn't crash on
our side. I just created the fix. It should be up by Monday or even
tomorrow.

2017-04-01 19:03 GMT-03:00 djpanda <notifications@github.com>:

**Comment by djpanda** [comment]
Verson with fix for 1.11.2 already released ?

**Comment by Raycoms** [comment]
Oh for 1.11.2

Will have to see. Having a lot of stuff for real live to do.
I can get you the jar in the next days. The official release on curse will
need a while.

2017-04-03 11:30 GMT-03:00 djpanda <notifications@github.com>:

**Comment by djpanda** [comment]
would be great

**Comment by Raycoms** [comment]
You can try this here out:
https://www.dropbox.com/sh/9cnqcjl0nan57cy/AAD-tL30w8ZhRKKuCd7X2G2Za/branch/port-to-1.11?dl=0&preview=minecolonies-universal-1.11-0.6.3334.jar

But it has not been tested yet.

It has all the latest 1.10 changes, including the sandstone builds.

2017-04-03 11:41 GMT-03:00 djpanda <notifications@github.com>:

**Comment by djpanda** [comment]
OK with this version the Actually Additions Breaker no longer crash the sever but didnt work for real. Embers Automatic Breaker still crashes the server.
And the ones from Cyclic and Random Thinks try to break but cant break any block (tested on cobblestone, Netherquarz)

**Comment by Raycoms** [comment]
Okay can you send me the log of the crash?

2017-04-08 8:47 GMT-03:00 djpanda <notifications@github.com>:

**Comment by djpanda** [comment]
Thats the Crash with Embers Breaker -> https://pastebin.com/B7a79s9N
And as i sayed the breakers from Actually Additions can be placed without crash but no longer functional. The others are  working and try to break blocks as the texture looks like but cant realy remove the block.

**Comment by Raycoms** [comment]
I think that crash you can report to the embers breaker mod. Can't find
anything related to us in the log.
We coded our anti griefing regarding to forge.
Meaning:
If a block breaker received the UUID of the player (and is marked as
fakePlayer) it will be able to break blocks. Else -> not

2017-04-08 10:11 GMT-03:00 djpanda <notifications@github.com>:

**Comment by djpanda** [comment]
RFTools Builderblock with Quarry Card can be placed but not able to remove any Block inside the colonyboarders
