### ISSUE TITLE
Ordering food from postbox doesn't work

### ISSUE THREAD

**Issue by AVFD** [ldtteam/minecolonies#7530]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.14.345-ALPHA-universal
- Structurize Version: structurize-0.13.210-ALPHA-universal
- Related Mods and their Versions: jei-1.16.5-7.7.1.116

## Expected behavior

Ordering cooked food through postbox, w8 the Cook to make the food and the courrier delivery it.

## Actual behavior
Order some cooked food and w8 until ever, the food never comes. Checking the Cook and I saw that was no tasks. 

First Image, showing the cooked food ordered:
![image](https://user-images.githubusercontent.com/18308993/130538763-3328e79c-73ca-498f-995d-cad1f6b4fe1a.png)

Second image, showing that are no task from Cook:
![image](https://user-images.githubusercontent.com/18308993/130538821-7fadc0bb-8418-4369-a62d-a89ae89e327f.png)

Third image, showing there are the requested food ON:
![image](https://user-images.githubusercontent.com/18308993/130538887-4e7c7591-4705-454c-8138-9695ede64368.png)

Fourth image, showing that are a lot of potatoes on the warehouse.
![image](https://user-images.githubusercontent.com/18308993/130539191-aec53c57-2100-48a1-8039-b4f61a6c37ed.png)

## Steps to reproduce the issue

1. Build a restaurant lvl 2 (medievaloakalternative style).
2. Order some cooked food (using postbox).
3. W8 for a long time.

### Logs

- latest.log: 
- crashlog: 

### Notes

I tried with another cooked foods and still having the same issue.

Ordering some raw food works (but it came from warehouse directly).
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Do you have an assistant cook?

**Comment by AVFD** [comment]
Nop, my restaurant is only lvl 2.

**Comment by Raycoms** [comment]
Okay, that is the issue, only the assistant provides for postbox requests.

**Comment by AVFD** [comment]
Thanks!!!
