### ISSUE TITLE
deconstructed and replaced mine hut missing mineshaft levels

### ISSUE THREAD

**Issue by leagris** [ldtteam/minecolonies#7535]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.347-ALPHA
- Structurize Version: 0.13.210-ALPHA
- Related Mods and their Versions: Forge 36.2.2

## Expected behavior
Deconstructed and replaced mine hut item shall contain enough information to rebuild the mining levels and mineshaft, and possibly remember nodes.

All in all, a deconstructed replaced mine hut shall be fully fonctional.

## Actual behavior

The miner cannot work and complains his hut need be upgraded even if hut is at mark V.

## Steps to reproduce the issue

1. Build mine, and upgrade it
2. Let miner build down mineshaft levels
3. deconstruct, and replace mine hut
4. hire builder and see he cannot work because mine has no mineshaft levels.

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
The problem with this is that if you move the shaft even slightly then the stored values won't work.  And usually the point of deconstructing is to move the building.  Even if you're only changing style and putting it back in the "same spot", different styles have the mineshaft in different locations and starting at different depths, so it's very hard to avoid accidentally moving it.

There is, however, already a "repair mineshaft" button that you can use; and if that doesn't help then as you were told on Discord you can often get them to recover (i.e. restart from scratch) by removing all but the top three ladders in the shaft.

**Comment by Raycoms** [comment]
Yep, this is actually correct. We can't support this.
