### ISSUE TITLE
Miner AI NPE crash

### ISSUE THREAD

**Issue by leagris** [ldtteam/minecolonies#7537]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.349-ALPHA
- Structurize Version: 0.13.210-ALPHA
- Related Mods and their Versions: Forge 36.2.2

## Expected behavior
Miner AI not crashing

## Actual behavior

Miner AI crashed after digging brand new mineshaft, reaching mineshaft level 3 with mine level 1 in stone style

![2021-08-26_13 57 02](https://user-images.githubusercontent.com/1111474/130959216-22eda1fe-057d-4f72-85dc-029e23144e86.png)

## Steps to reproduce the issue

1. Build new mine in stone style and leave it at mark I
2. Let miner construct mineshaft
3. After a while reaching level3 and continuing a bit below, miner AI NPE crash

### Logs

- latest.log: https://gist.github.com/leagris/38af2a35a0940b7af0702a19dbe868d3
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
fix pushed
