### ISSUE TITLE
Knights not leveling up / gaining xp from fighting.

### ISSUE THREAD

**Issue by Gaviell** [ldtteam/minecolonies#7538]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.350 ALPHA
- Structurize Version: 0.13.210 APHA
- Related Mods and their Versions: Forge 36.2.2

## Expected behavior
Knight's stamina and adaptability stats gradually increasing while being assigned to a Guard Tower / Barracks Tower and participating in combat.

## Actual behavior
Knight's stats stay the same no matter the tower/barracks level, intelligence level, attacks or kills they get.

## Steps to reproduce the issue

1. Build a guard or barracks tower to level 5
2. Hire a guard and give them a high intelligence stat (and probably some OP armor).
3. Have them fight lots of monsters or raids and check their stats afterwards.

### Logs

- latest.log: 
- crashlog: 

### Notes
Right-clicking a guard to bring up their info tab shows their status as "fighting" (the little picture) even while they are idle, guarding or patrolling.
Guards stats still increase over time if they are in a combat academy.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Gaviell** [comment]
Was able to get a guard to level up their adaptability by removing their armor and giving them a ton of stamina and letting them fight (which was agonizingly slow even with 99 intelligence). It seems that their level ups may be based on the damage they take, or may not be based on combat at all, I'm not sure, wiki doesn't explain it. All I know is that recently my knights leveling has slowed way down. Maybe a design choice by the devs to get people to use the combat academy.

**Comment by someaddons** [comment]
I want to recheck this, some stuff recently changed in the vincinity
