### ISSUE TITLE
👍 Block placing bug when fulfilling requests. 

### ISSUE THREAD

**Issue by tudoran2007** [ldtteam/minecolonies#7547]
### Prerequisites 

- [n] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [y] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [y] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.14.311-BETA-universal
- Structurize Version: structurize-0.13.202-ALPHA-universal
- Related Mods and their Versions: https://imgur.com/a/V9D7LTc

## Expected behavior

When completing a citizens entire request the respective citizen resumes work on whatever he was doing that required that resource.

## Actual behavior

Regardless of the citizens state (stopped working or not), this error (https://mclo.gs/90xPEFW) appears in console and from there on, block placing and breaking only gets registered on the client.
I should add that the server has been running for 17 days, so i have no idea as to what caused it to act up now...

## Steps to reproduce the issue

1.  Complete all of a citizens requests
2.  try to break/place blocks
3.  If you try to get into a hole that you dug, you are stopped, like something is there and when placing blocks and getting on top of them you get kicked for flying.

### Logs

 

- latest.log:  https://gist.github.com/tudoran2007/fca2c5c6e8b390d15a7f533b98b77f5a
- crashlog:  ----------

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Did you already try updating to the latest?

**Comment by tudoran2007** [comment]
lemme try

**Comment by tudoran2007** [comment]
how do i know what structurize version is the good one?

**Comment by Raycoms** [comment]
The curse changelog tells you

**Comment by tudoran2007** [comment]
ok

**Comment by tudoran2007** [comment]
i installed the latest version, i a going to repeat my steps and see if the problem repeats

**Comment by tudoran2007** [comment]
it seems to be working... ill open another issue if i discover any other problems :)

**Comment by tudoran2007** [comment]
i got another problem
now when i try to place a building this happens: https://mclo.gs/yEPus7F

**Comment by Raycoms** [comment]
that happens if you place it outside of a valid colony.

**Comment by tudoran2007** [comment]
welp i am inside of my colony :l

**Comment by tudoran2007** [comment]
if you want ill give you the modpack and ip, and then add you to the colony to see for yourself

**Comment by Raycoms** [comment]
Are you by chance in a LAN world?

**Comment by tudoran2007** [comment]
nope

**Comment by Raycoms** [comment]
Did you try restarting?

**Comment by tudoran2007** [comment]
yes... it always seems to fix it, but another error comes right up :(
imma do it right now just to be sure tho

**Comment by tudoran2007** [comment]
...
i confused
now placing buildings DOES work... but the block updating issue is back
help?

**Comment by Raycoms** [comment]
I'm pretty sure that sth else is causing this issue and that it is not MineColonies as this doesn't happen in any of our worlds. And the exception you showed is sth that doesn't cause any active harm.

**Comment by tudoran2007** [comment]
it makes the game unplayable... and i talked about this to magma and they said its the mod, also every error that causes this has the word minecolonies in it :l

**Comment by Raycoms** [comment]
Well, error != the cause of your problem. Something is stalling your world. That is not MineColonies doing it. And then when you interact on the client side, this causes minecolonies exceptions. The error you see is the result of the problem, not the cause of it.

**Comment by tudoran2007** [comment]
hmm... fair enough... but knowing your mod, what do you think causes that specific error
CPU? RAM? lag in general? lack of compatibility? etc etc

**Comment by Raycoms** [comment]
Ohh you're using Magma not forge itself. Then it's definitely on their side. They're just blaming some exception we throw in the log. But probably they are having issues with chunk capabilities.
