### ISSUE TITLE
The Ia of the miner stucks

### ISSUE THREAD

**Issue by xGodKx** [ldtteam/minecolonies#7550]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.348-ALPHA-universal

### Logs

https://gist.github.com/xGodKx/4e335151cf50120e6e142c15b769a30f

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
Update minecolonies. This is fixed already in later versions
