### ISSUE TITLE
Repeated Miner AI crash

### ISSUE THREAD

**Issue by taggianto** [ldtteam/minecolonies#7552]
I keep getting an AI error for the miner, asking me to post the latest.log file.

I've tried relocating the mine, trying a different mine type, firing and rehiring, hiring someone completely new, and it still keeps popping up. I've attached the log file as requested. Please let me know if you need more information!

[latest.log](https://github.com/ldtteam/minecolonies/files/7082165/latest.log)

**Comment by Talyda** [comment]
Please fill in the template when you are reporting a bug. And make sure you are on the latest version of the mod =)

**Comment by taggianto** [comment]
seems to be fixed with new version!
