### ISSUE TITLE
Cook: Not requesting food / ingrediants

### ISSUE THREAD

**Issue by Jinotad** [ldtteam/minecolonies#7559]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.356-ALPHA-universal
- Structurize Version: 0.13.210-ALPHA-universal
- Related Mods and their Versions: Adventure Server 3.8

## Expected behavior
Cook requesting food / ingredients to maintain a food supply.

## Actual behavior
The cook is failing to request food or ingredients. No or long delay between requesting new food after a delivery.

I have fired / rehired the cook and assistant once, and the cook immediately started requesting food.  After some time has passed, the cook stops making requests for food.

https://user-images.githubusercontent.com/85356635/132077124-ba4a9314-57be-424a-b051-4a2c9c922b41.mp4

https://user-images.githubusercontent.com/85356635/132077261-6ecec1db-53e5-4614-8a94-af0c538178a8.mp4

![2021-09-03_20 07 25](https://user-images.githubusercontent.com/85356635/132077304-53f462a7-582b-4922-b30d-ffaaa8e4cddb.png)

## Steps to reproduce the issue

Wait and watch the cooks. No or long delay between requesting new food after delivery.

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
How much food is in the restaurant?

**Comment by Jinotad** [comment]
When things were working properly, it had around 50-60% of its double rack.  Then after a time, perhaps 1 or 2 stacks of food. Primarily seemed to maintain a supply of a stack of baked potatoes.  Eventually none.

In the video's the cook had 7 cooked fish, and 38 fried eggs. (Food remaining from manually bringing 96 raw eggs and I'm not sure how many fish, because the restaurant was empty.)

**Comment by Raycoms** [comment]
Bug already tracked down =)
