### ISSUE TITLE
Simple Park Missing Cobblestone Walls in Builder's Tool

### ISSUE THREAD

**Issue by Havvy** [ldtteam/minecolonies#756]
### Minecolonies version

version 0.6.3329 for MC 1.10.2

### Expected behavior

- Simple park should show cobblestone walls in builders tool.

### Actual behaviour

- Floating torches because the cobblestone walls don't render.

### Steps to reproduce the problem

1. Open builder's tool
2. Show the Simple Park
3. Look at floating torches
4. Profit

**Comment by Raycoms** [comment]
We use minecraft structure rendering for that. That's not our fault.

2017-04-03 18:12 GMT-03:00 Ryan Scheel <notifications@github.com>:

**Comment by Havvy** [comment]
What's "Minecraft Structure Rendering"?

**Comment by xavierh** [comment]
Is that in the build tool preview ?

**Comment by Raycoms** [comment]
Yes it is

2017-04-04 9:54 GMT+00:00 xavierh <notifications@github.com>:

**Comment by xavierh** [comment]
Btw you won't be able to build it. It does require stone bricks monster eggs 😕
