### ISSUE TITLE
Builder Randomly Teleports To surface When Building Colony In The Sky

### ISSUE THREAD

**Issue by snakemasterepic** [ldtteam/minecolonies#7560]
### Prerequisites 

- [ x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version:0.14.361-ALPHA
- Structurize Version:0.13.210-ALPHA
- Related Mods and their Versions:

## Expected behavior

Builder remains up in the sky with the colony (s)he is building unless (s)he falls off.

## Actual behavior

The builder teleports down to the surface of the world while the colony is in the sky.  The builder was carefully followed, and did not accidentally fall.

## Steps to reproduce the issue

1. Start building a colony in the sky (around y=161).
2. Make sure the colony is walled off to minimize the probability of accidental falling.
3. Create a build order for a sky colony.  It generally works best if the build order has a large horizontal footprint.
4. Observe the builder, and after a while, (s)he will teleport to the surface.  I even tried covering the surface below with lava, and the builder teleported down and died.  The builder is most likely to teleport while scanning a bunch of air blocks.

### Logs

- latest.log:  N/A
- crashlog:  N/A

### Notes

- I have also observed workers falling, and they don't die despite falling from y= ~160 to y=~65.
- Sometimes, the builder will try to go to the surface even when it makes no sense for the block(s) the builder is trying to place.  I believe this is related.
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
https://buildsystem.ldtteam.com/guestAuth/repository/download/LetSDevTogether_Minecolonies_Branches_Build/94094:id/build/libs/minecolonies-0.14.1002-PERSONAL-universal.jar

Can you test if its better with this?

**Comment by Raycoms** [comment]
Solved
