### ISSUE TITLE
Builder Breaks And Replaces Walls & Fences Unnecessarily

### ISSUE THREAD

**Issue by snakemasterepic** [ldtteam/minecolonies#7561]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version:0.14.361-ALPHA
- Structurize Version:0.13.210-ALPHA
- Related Mods and their Versions:

## Expected behavior

Builder leaves existing walls and fences intact if they are used in the final structure.
## Actual behavior

The builder breaks the fences/walls and re-adds them back in.  This issue occurs even when they retain the same blockstate.

## Steps to reproduce the issue

1. Create a schematic with walls/fences.
2. Prepare space to build the schematic.
3. Place walls/fences in the build area in the same relative positions that they will appear in the schematic.
4. Place the build request.
5. Wait for the builder to start clearing the area.

### Logs

- latest.log: N/A
- crashlog: N/A

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
I double checked this and scanned in walls and fences, and it only happens if they somehow change their state and then yes. In the case of a state change we remove the walls/fences and re-add them back in.

**Comment by MotionlessTrain** [comment]
What I think happened is that one of the walls or fences at the end of the line had the wrong state (or one of the walls not yet connecting vertically or so). The builder removed that one because of the wrong block state. Consequently, the neighbouring fences/walls got the wrong block state etc.

**Comment by Raycoms** [comment]
That is possible yes, it can trickle down. But that's okay. The few times it happens, the builder doesn't have to be 100% efficient. They already build extremely fast.

**Comment by MotionlessTrain** [comment]
I agree that this works as intentional.
I just tried to find an explanation of them removing multiple fences, even when they have the correct block state already
