### ISSUE TITLE
Citizens cannot get out of their seats after fed

### ISSUE THREAD

**Issue by EverettSummer** [ldtteam/minecolonies#7563]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.361-ALPHA
- Structurize Version: 0.13.210-ALPHA
- Related Mods and their Versions: 

## Expected behavior

All citizens should be able to move out of the seat in the restaurant.

## Actual behavior

Some citizens got stuck in their seat. those chairs are usually in a corner.

## Steps to reproduce the issue

Currently, Cook has a bug requesting raw materials. so the restaurant is constantly crowded with people. so people will have a chance to sit everywhere in the restaurant.
It's recommended to use Medieval Dark Oak style. because I'm using this style. but I don't think it's a schematics issue.
1.  make restaurant lack of material 
2.  waiting for enough citizens fill the restaurant
3.  to see if some citizens cannot get out of their seats.

### Logs

- latest.log: 
- crashlog: 

### Notes

![2021-09-04_11 29 33](https://user-images.githubusercontent.com/55684557/132079688-989d9bca-4712-493f-a78d-5108060993ff.png)

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by AVFD** [comment]
I think in this case is an style issue... I had some stuck citizens and I broke the blocks above them... and it's worked for me. Try it.
