### ISSUE TITLE
Auto Backup of Colonies Overload...

### ISSUE THREAD

**Issue by Zoidey** [ldtteam/minecolonies#7564]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.321-ALPHA
- Structurize Version: 0.13.205-alpha
- Related Mods and their Versions: All the Mods 6 - ATM6 - 1.16.5 Modpack version 1.7.7

## Expected behaviour
Not seeing like 1,000+ backups a day

## Actual behaviour
Not sure if this is a bug or a glitch etc but I've noticed my world size increase dramatically due to mass MineColonies automated backups, over the course of a day or so I can quite easily have like 1000+ backups. The backups are only tiny in filesize but when you have like 100 to 1000+ they certainly add up.

Screenshot from my FTP client so you can see what I mean: https://i.imgur.com/Qg5gjQF.png

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: N/A
- crashlog: N/A

### Notes
I know that the All The Mods 6 Modpack that I'm using isn't the latest and I don't think even the latest version has an updated version of the mod. What I'm considering trying is manually update just the MineColonies on both the server and client but I wanted to find out a bit more first and see what others might suggest first.

Also, I think with it consonantly backing up multiple times every minute for several minutes it could using up more server memory than it really should be.

I think this is about as much information I can provide that I can think of at the moment but if more is needed let me know.
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by someaddons** [comment]
backups are made each shutdown normally, please add your latest.log file so we can see more

**Comment by Zoidey** [comment]
Alright here is the latest log, I hope it is of some help: https://gist.github.com/Zoidey/0e9fb4d5f7e2f2b17a2db9453ac5891b

Since you mention "backups are made each shutdown normally" With my server scheduled to auto restarting every two hours be causing issues with the backups? I'm guessing when the server crashes it wouldn't affect the backup as it's not exactly a normal shutdown.

**Comment by someaddons** [comment]
its so many backups because its making one on each dimension unloading

**Comment by Zoidey** [comment]
Interesting, I never thought about the other dimensions, etc would be a way to like either restrict what dimensions minecolonies access (for example limit it to just the overworld) and/ or have an option to clean up the excess backups?

**Comment by Raycoms** [comment]
There is a pending PR for it yes.
