### ISSUE TITLE
Citizens put their food in the huts that waste food

### ISSUE THREAD

**Issue by EverettSummer** [ldtteam/minecolonies#7565]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.361-ALPHA
- Structurize Version: 0.13.210-ALPHA
- Related Mods and their Versions: 

## Expected behavior

Citizens should always carry their food instead of unloading to huts with other items they picked.

## Actual behavior

Citizens always unload their food to huts.

<img width="447" alt="javaw_2021-09-04-161153-88" src="https://user-images.githubusercontent.com/55684557/132086244-a9653876-56f5-4792-a059-117aabca437d.png">

## Steps to reproduce the issue

1.  let the cook give citizens who are any type of worker some cooked food.
2.  throw something on the ground like eggs. this will increase the chance of unloading items.
3.  check their hut to see if there is cooked food in the hut.

### Logs

- latest.log: 
- crashlog: 

### Notes

This behavior causes additional pick-up requests. reduce the logistics efficiency. waste food because the assistant cook will never request cooked food from the warehouse.
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
This is intended, citizens will also first check for food in their hut before going to the restaurant.

**Comment by EverettSummer** [comment]
@Raycoms , even the put back in their hut is intended, the cooked food will eventually picked up by couriers and ended up in the warehouse is still a issue. currently, assistant cook will never use cooked food from warehouse, they always request raw food to produce cooked food. the citizens will also not able to use the cooked food in the warehouse.

I have set my restaurant **pick up priority** to never. so I guess the cooked food in the warehouse can only be from the worker's hunt.

**Comment by Raycoms** [comment]
There is a thing where a hungry courier gets food and dumps it in the warehouse (As that is their working hut)
