### ISSUE TITLE
ServerHangWatchdog detected that a single server tick took 180.00 seconds

### ISSUE THREAD

**Issue by MeikelLP** [ldtteam/minecolonies#7568]
### Prerequisites

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.356-ALPHA
- Structurize Version: 0.13.210-ALPHA
- Related Mods and their Versions:

## Expected behavior
No nullpointer

## Actual behavior
I'm trying to move my warehouse and started to move items from the warehouse to separate chests.
When I break a rack and take the items, so of the workers run into AI issues.
I play in single player. Also after some minutes the game (server?) freezes and no interaction is possible. All entities are frozen. Like when u have disconnect on a MP session.

## Steps to reproduce the issue

1. Have about 5 couriers.
2. Destroy some racks in the warehouse.
3. Wait for AI errors.

### Logs

- latest.log: https://gist.github.com/MeikelLP/58f063afe093d52ee77ed9683c34217c
- crashlog: https://gist.github.com/MeikelLP/8969c40a41ca8285cf0042f909ac5588

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Can you test out this here:

```
https://buildsystem.ldtteam.com/guestAuth/repository/download/LetSDevTogether_Minecolonies_Branches_Build/94064:id/build/libs/minecolonies-0.14.995-PERSONAL-universal.jar
```

If that still happens with it.

**Comment by MeikelLP** [comment]
Nope. Still happens. What log do you need? latest or crash?

**Comment by Raycoms** [comment]
crash

**Comment by MeikelLP** [comment]
https://gist.github.com/MeikelLP/380d958bd4693b7e7dd4c84a8409bb11

**Comment by Raycoms** [comment]
Can you try this one now too?
https://buildsystem.ldtteam.com/guestAuth/repository/download/LetSDevTogether_Minecolonies_Branches_Build/94090:id/build/libs/minecolonies-0.14.1001-PERSONAL-universal.jar

**Comment by MeikelLP** [comment]
lgtm
