### ISSUE TITLE
No Way to Cancel Decoration Builds

### ISSUE THREAD

**Issue by Havvy** [ldtteam/minecolonies#757]
### Minecolonies version

version 0.6.3329 for MC 1.10.2

### Expected behavior

- Some UI for canceling decoration builds (e.g. the simple park)

I'd expect the UI for doing this to either be in page 2 of the Builder UI or in the builder's UI itself.

### Actual behaviour

- Builder has to actually build the entire thing.

**Comment by Raycoms** [comment]
You can cancel the build in the townhalls workOrder tab?

2017-04-03 18:14 GMT-03:00 Ryan Scheel <notifications@github.com>:

**Comment by Havvy** [comment]
Ah, cool. Then changing this to an enhancement request to have UI also in one of those two places.

**Comment by Raycoms** [comment]
But that's what we have the townhall for gui for.
We already have a lot of things in gui 1 and 2. And all normal houses can be canceled in their own gui.
I feel like this is not necessary to have 2 guis for that.
