### ISSUE TITLE
Minecolonies prerequisite structurize version: typo?

### ISSUE THREAD

**Issue by Hequinoxe** [ldtteam/minecolonies#7576]
### Prerequisites 

- [ X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version:0.14.366-ALPHA
- Structurize Version: 0.13.219-ALPHA
- Related Mods and their Versions: Forge 36.2.0

## Expected behavior
 Be able to log into my world while Minecolonies & structurize are installed

## Actual behavior
 Cannot login, error message from forge says Minecolonies requires structurize 0.13.210 and that I have structurize 0.13.219    According to changelog I need to have 0.13.219 installed.

## Steps to reproduce the issue

1.  Install most recent structurize and minecolonies
2.  Try to log into a world (personnal)
3.  Get the error message

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
Wait, the ingame error says you need 210 but the changelog says you need 219? Am I reading this right?

**Comment by MotionlessTrain** [comment]
Are you 100% sure you loaded 0.14.366-Alpha? I just upgraded to it and minecraft tells me exactly the opposite message, asking me to install structurize 0.13.219-Alpha

**Comment by Hequinoxe** [comment]
> 
> 
> Wait, the ingame error says you need 210 but the changelog says you need 219? Am I reading this right?

Yes that was what I had... However I realized where the issue was. I used to manage my mods manually and recently I changed to curseforge. When I was asked to update minecolonies & structurize I did so. I had the issue I wrote above and I thought my updates were correct, however when I just reopened it I saw I was on a beta version (I think 364, but I did not look correctly) and a more recent version was available (366). I'm pretty sure I changed the option from restricting to beta to allow any update a few days ago. Anyway, once I updated, I was able to login. I can't say for sure if it was me being idiot and not seeing the arrow for update or a glitch from curseforge, but I suspect (also read hope) it's the latter. moving forward I will check manually the mods before opening a ticket. 

Truly sorry for the trouble.
Thanks for your help.

**Comment by Hequinoxe** [comment]
> 
> 
> Are you 100% sure you loaded 0.14.366-Alpha? I just upgraded to it and minecraft tells me exactly the opposite message, asking me to install structurize 0.13.219-Alpha

You are right. I had the wrong version. As you can read above.
