### ISSUE TITLE
Builder Mode - Inward Circular height 4, skips a corner block

### ISSUE THREAD

**Issue by Jinotad** [ldtteam/minecolonies#7580]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.356-ALPHA-universal
- Structurize Version: 0.13.210-ALPHA-universal
- Related Mods and their Versions: Adventure Server 3.8

## Expected behavior
Properly placing all the blocks.

## Actual behavior
I don't know if it is all the circular modes, or if it is just the height 4 version; but it seems like the builder always skips placing the bottom most North West block of the build.

Failed to replace the dirt block with cobblestone when rebuilding a lvl 5 guard tower after picking it up and moving it.
![2021-08-27_16 48 44](https://user-images.githubusercontent.com/85356635/132141409-a883afe1-62d6-4af0-ae4a-cfee736ec43e.png)

Not placing the block when constructing a new lvl 1 guard tower
![2021-08-28_16 01 23](https://user-images.githubusercontent.com/85356635/132141442-4f027c6f-7101-4d2c-80d0-60ef3693fbc6.png)

Built two Statue decorations, on either side of my road using the Mirror option.  Both missing their NW block.
![2021-09-05_17 10 15](https://user-images.githubusercontent.com/85356635/132141548-d0176c66-867b-44b9-9784-4a7a7085d6c0.png)

## Steps to reproduce the issue

1. Unlock the builder mode options.
2. Set the builder to inwardcircleheight4
3. Have builder construct a schematic
4. 
5.  Rebuild a moved structure.

### Notes
If the builder is building, they will clear the block space. If the builder is rebuilding a moved structure, they will leave that spot as is. (Won't clear that spot or place the proper block in that spot.)

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Was fixed
