### ISSUE TITLE
[BUG]architect patrols the building hut meaninglessly

### ISSUE THREAD

**Issue by binglingyao** [ldtteam/minecolonies#7584]
### Prerequisites 

- [ X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version:minecolonies-0.14.368-ALPHA-universal
- Structurize Version:structurize-0.13.219-ALPHA-universal
- Related Mods and their Versions:

## Expected behavior

   Builders no longer aimlessly wander or patrol from point A to point B in [Block Hut Builder] and [Builder-Medievalbirchalternative basement] 

## Actual behavior

The architect will meaninglessly patrol the Block Hut Builder and its basement on the way to building other buildings, doing nothing meaningful in the process, I checked the architect's backpack and the warehouse of the building hut, nothing changed, just meaningless patrols there and back.
Occasionally there will be some errors in the background.

"Could not find iterator for value: using default instead!" *3

This is an error reported when the debug mode is not enabled
![QQ截图20210909085847](https://user-images.githubusercontent.com/60381869/132604973-5b6b20f5-c71e-432f-9c97-d8e4a757372a.png)
This is what the building actually looks like
![QQ图片20210909091934](https://user-images.githubusercontent.com/60381869/132606403-22a4262e-23d3-471a-ab5c-9522f256e799.png)

## Steps to reproduce the issue

 
I don't know if it will happen again, maybe it's just me?  I was just playing around and I found it.  

1. 
2. 
3. 

### Logs

- latest.log: 
- <script src="https://gist.github.com/binglingyao/bd09a60b8721aec189651502e5072da4.js"></script>
- crashlog: 

### Notes

We know that pausing and restarting after meaningless loitering will keep it going for a while, sometimes by 1 square, sometimes until the end of the construction project. The same goes for finding more materials in the architect's backpack in the process. They work for a while and then return to meaningless patrols.

addition:

Occasionally NPC models will appear, showing names of existing NPCS with the same name. These NPCS are non-collision entities, will be models that are not scheduled to work, and will disappear after re-entering the save.
What is known is that the presence of such invalid NPC models will cause the AI of valid NPCS with the same name to stall somewhat
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
This is actually fine, the builder does some rounds between the different inventories in their hut before going off to work for a bit. The error is unrelated and will be removed in the near future.
