### ISSUE TITLE
Courier AI ran into an issue.

### ISSUE THREAD

**Issue by EverettSummer** [ldtteam/minecolonies#7585]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.368-ALPHA

### Logs

https://gist.github.com/EverettSummer/c0cd9b19df8f97deed7fb1a8e45759ef
- latest.log: 

## Steps to reproduce the issue / details

Just reporting the AI issue. 

### Notes

The courier standing near the warehouse block.
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by EverettSummer** [comment]
![2021-09-09_18 26 47](https://user-images.githubusercontent.com/55684557/132661373-00e09b47-8d46-4f3d-af5e-6891de28ee97.png)

**Comment by Raycoms** [comment]
This one seems to happen when a private crafting request exists at a crafter, but the crafter was fired/died.

**Comment by Raycoms** [comment]
Should be solved
