### ISSUE TITLE
Courier not emptying miner's chest

### ISSUE THREAD

**Issue by Rosomah** [ldtteam/minecolonies#7586]
Hello.

- I am running the 0.14.353 version of MineColonies and 0.13.210 Structurize for 1.16.5 version.
- I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- I made sure that this issue is not a duplicate of any existing issue.

## Expected behavior
The courier should take resources (like ores, or full stacks of cobblestone or other materials) from the miner's chest.

## Actual behavior
The courier only delivers materials or tools to the worker (like a pickaxe or other materials for building shafts), but doesn't take anything from the chest. It's working fine with other workers, for example, as soon as the forester deposits logs into his chest, the courier picks them up.
The courier also is not busy doing any other thing, he's just standing in the warehouse, waiting to make a delivery.
Also, trying to "request pickup" at the miner's chest returns the "unable to comply, another delivery in progress" or something like that.

Hope you can help.
Best regards,
Rosomah

**Comment by Raycoms** [comment]
Yeah, it's a known problem caused by a past bug. Did you try the requestsystem-reset?

**Comment by Rosomah** [comment]
Great, thank you, that worked!

Closing issue.
