### ISSUE TITLE
bug bannière pour hôtel de ville de niveau 4

### ISSUE THREAD

**Issue by bryan20020807** [ldtteam/minecolonies#7587]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.12.2
- MineColonies Version: 1.12.2
- Structurize Version:
- Related Mods and their Versions:

## Expected behavior
 qu'il passe au block suivants.

## Actual behavior
 c'est la block bannière noir (personnalisée avec des colorants ) qu'il ne veut pas récupérer.

## Steps to reproduce the issue

1.  tout est dur les image il y a juste a build l'hdv de niveau 4
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

![2021-09-10_15 55 52](https://user-images.githubusercontent.com/90461591/132865027-feaf855e-d354-4ec5-9efe-1c8fc01aa63d.png)
![2021-09-10_15 56 04](https://user-images.githubusercontent.com/90461591/132865034-e387fe19-2776-4256-8fcc-615d0de121e5.png)
![2021-09-10_15 56 15](https://user-images.githubusercontent.com/90461591/132865035-6ab2a96e-6bb7-4d09-b5fa-85e173af9649.png)

**Comment by Raycoms** [comment]
No support for 1.12

**Comment by bryan20020807** [comment]
oui mais à cause de ça impossible de finir les builds.
