### ISSUE TITLE
Is the barracks tower bugged or supposed to be this way?

### ISSUE THREAD

**Issue by KitsuTheFloof** [ldtteam/minecolonies#7589]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version. ✔
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there. ✔
- [x] I made sure that **this issue is not a duplicate of any existing issue.** ❕ (This issue was posted in 2019)

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-1.0.0-RELEASE
- Structurize Version: structurize-0.13.219-ALPHA-
- Related Mods and their Versions:

## Expected behavior

I expect to be able to place a barracks tower. Whether it's inside the barracks OR if it's on the outside where it's on a side or next to a corner.

## Actual behavior

What occurs is the message saying **Please upgrade the barracks first** sometimes it will allow me to build the barracks tower without tat message showing up. I cannot figure out how I worked around it and some people say try repairing but that doesn't work always and I'm not sure if that even worked or if t

## Steps to reproduce the issue

1.  Get a barracks tower
2.  Place a barracks tower. Place it on the side of the wall, on a Corner, or Inside the Bar
3.  Either it will say **Please upgrade the barracks first** or it will start the building process.

### Logs

- latest.log:  https://gist.github.com/KitsuTheFloof/cd618ab2d392b0e147ce1d3f35720b49
- crashlog: 

### Notes

I would like to add I'm not sure how to exactly work around it and sometimes repairing can be a work around but in my experience it only can work if the barracks tower is literally inside the barracks and even if you do that there's no gurantee it will work. I was able to start the building process for a barracks tower that I placed inside the barracks (wasn't able to build it at first). Then I decided to test it and I picked the barracks tower up and placed it in the EXACT same spot and I wasn't able to work around it this time.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
You can't place barrackstowers. They'r epart of the barracks. That's why they don't have a crafting request. The builder places them.

**Comment by KitsuTheFloof** [comment]
I was told the towers come with the schametics? If that's the case how come I don't see the barracks tower. And how come I can't assign workers to the towers.

**Comment by Raycoms** [comment]
Build the barracks. It will place towers. click build on the towers, that the builder placed. then you can assign.

**Comment by KitsuTheFloof** [comment]
> Build the barracks. It will place towers. click build on the towers, that the builder placed. then you can assign.

Thanks it seems he placed a barracks tower after I clicked repair but didn't do that the first 2 or 3 times.
