### ISSUE TITLE
Wrong translation

### ISSUE THREAD

**Issue by HaroldCHANG-afk** [ldtteam/minecolonies#7597]
### Prerequisites 

- [√] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [√] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [√] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.16.5
- MineColonies Version:1.0.0-RELEASE-
- Structurize Version:Not important

## Problem description

The Chinese translation of 'Sacred Scroll of Regeneration' is wrong and may cause a misunderstanding.
The following is the translation from the lang file:
"item.minecolonies.scroll_buff": "重生卷轴",
"item.minecolonies.scroll_buff.tip": "至少在大多数情况下，可以对你周围的市民进行重生...",

"可以对你周围的市民进行重生..." actually means that I could bring the dead citizens back to life, while the true meaning should be 'apply a regeneration buff to nearby citizens'. So "重生卷轴" is better to be replaced by "再生卷轴". The effect description should be "至少在大多数情况下，可以让你周围的市民恢复生命..."

### Notes or related things

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
the translations are community-made, you can suggest a change here https://crowdin.com/project/minecolonies
