### ISSUE TITLE
A specific player cannot connect to my server 

### ISSUE THREAD

**Issue by DecVrc** [ldtteam/minecolonies#7599]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 1.0.2 alpha
- Structurize Version: 0.13.230 - alpha
- Related Mods and their Versions:

Client mods

Ars Nouveau
baileyholl2
ars_nouveau-1.16.5-1.23.7.jar

CraftTweaker
Jaredlll08
CraftTweaker-1.16.5-7.1.2.423.jar

Ev's Alcohol
DetectiveSky612
evsalcohol3.jar

Farsighted Mobs (Forge)
Sindarin27
farsightedmobs-1.0.jar

Flywheel
jozufozu
flywheel-1.16-0.2.3.jar

FTB Chunks (Forge)
FTB
ftb-chunks-forge-1605.3.1-build.48.jar

FTB Ranks (Forge)
FTB
ftb-ranks-1605.1.4-build.9-forge.jar

FTB Teams (Forge)
FTB
ftb-teams-forge-1605.2.2-build.30.jar

KubeJS (Forge)
LatvianModder
kubejs-forge-1605.3.15-build.110.jar

MythicBotany
noeppinoeppi
MythicBotany-1.16.5-1.4.10.jar

Patchouli
Vazkii
Patchouli-1.16.4-53.1.jar

Rhino
LatvianModder
rhino-forge-1605.1.3-build.54.jar

Structurize
H3lay
structurize-0.13.219-ALPHA-universal.jar

Abnormals Core
TeamAbnormals
abnormals_core-1.16.5-3.3.0.jar

Absent by Design
Lothrazar
absentbydesign-1.16.5-1.5.0.jar

AI Improvements
QueenOfMissiles
AI-Improvements-1.16.2-0.3.0.jar

AIOT Botania
MelanX
aiotbotania-1.16.5-1.8.1.jar

Akashic Tome
Vazkii
AkashicTome-1.4-16.jar

Alex's Mobs
alex_khaan
alexsmobs-1.12.0.jar

AmbientSounds 4
CreativeMD
AmbientSounds_v3.1.9_mc1.16.5.jar

Apotheosis
Shadows_of_Fire
Apotheosis-1.16.5-4.8.0.jar

AppleSkin
squeek502
appleskin-forge-mc1.16.x-2.1.0.jar

Applied Energistics 2
AlgorithmX2
appliedenergistics2-8.4.1.jar

Architectury API (Forge)
shedaniel
architectury-1.22.32-forge.jar

Artifacts
ochotonida
Artifacts-1.16.5-2.10.0.jar

Astral Sorcery
HellFirePvP
astralsorcery-1.16-1.16.5-1.13.12.jar

AutoRegLib
Vazkii
AutoRegLib-1.6-49.jar

Autumnity
TeamAbnormals
autumnity-1.16.5-2.1.1.jar

Back Tools
ohaiiChun
BackTools-1.16.5-10.1.0.jar

Bad Wither No Cookie - Reloaded
Kreezxil
bwncr-1.16.5-3.10.16.jar

Bamboo Blocks
TeamAbnormals
bamboo_blocks-1.16.5-3.0.0.jar

Better Badlands
Gkoliver
Better-Badlands-1.16.5-2.0.3.jar

Better Biome Blend
FionaTheMortal
betterbiomeblend-1.16.4-1.2.9-forge.jar

Better Burning
DarkhaxDev
BetterBurning-1.16.5-6.0.6.jar

Better Title Screen
Girafi
BetterTitleScreen-1.16.4-1.10.2.jar

BetterEnd (Forge)
Beethoven92
betterendforge-1.16.5-1.6.1.jar

BetterF3
cominixo
BetterF3-1.1.3-forge-1.16.5.jar

Biomes O' Plenty
Forstride
BiomesOPlenty-1.16.5-13.1.0.482-universal.jar

Blood Magic
WayofTime
BloodMagic-1.16.4-3.1.3-18.jar

Bookshelf
DarkhaxDev
Bookshelf-Forge-1.16.5-10.2.27.jar

Botania
Vazkii
Botania-1.16.5-419.jar

Building Gadgets
Direwolf20
buildinggadgets-1.16.5-3.8.0.jar

Caelus API (Forge)
TheIllusiveC4
caelus-forge-1.16.5-2.1.3.1.jar

Carry On
Tschipp
carryon-1.16.5-1.15.5.15.jar

Cat Jammies
Buuz135
catjammies-1.1.0.jar

Chisel
tterrag1098
Chisel-MC1.16.5-2.0.1-alpha.4.jar

Chocolate Fix
AlcatrazEscapee
chocolate-1.3.0-1.16.4.jar

Citadel
alex_khaan
citadel-1.8.1-1.16.5.jar

Clumps
Jaredlll08
Clumps-6.0.0.25.jar

CodeChicken Lib 1.8.+
covers1624
CodeChickenLib-1.16.5-4.0.3.434-universal.jar

Collective
Serilum
collective-1.16.5-2.64.jar

Configurable Extra Mob Drops
Serilum
configurableextramobdrops_1.16.5-1.6.jar

ConnectedTexturesMod
tterrag1098
CTM-MC1.16.1-1.1.2.6.jar

Connectivity
someaddon
connectivity-2.3-1.16.5.jar

Controlling
Jaredlll08
Controlling-7.0.0.24.jar

Corail Tombstone
Corail_31
tombstone-1.16.5-6.5.2.jar

Cosmetic Armor Reworked
LainMI
CosmeticArmorReworked-1.16.5-v4.jar

Create
simibubi
create-mc1.16.5_v0.3.2d.jar

Create Crafts & Additions
MRHminer
createaddition-1.16.5-20210911a.jar

CreativeCore
CreativeMD
CreativeCore_v2.2.1_mc1.16.5.jar

Cucumber Library
BlakeBr0
Cucumber-1.16.4-4.1.10.jar

Curios API (Forge)
TheIllusiveC4
curios-forge-1.16.5-4.0.5.3.jar

Curious Armor Stands
ochotonida
Curious Armor Stands-1.16.5-2.1.2.jar

Curious Elytra (Forge)
TheIllusiveC4
curiouselytra-forge-1.16.5-4.0.2.3.jar

Curious Shulker Boxes (Forge)
TheIllusiveC4
curiousshulkerboxes-forge-1.16.5-4.0.1.0.jar

Customizable Elytra
Hidoni
customizableelytra-1.16.4-1.5.7.jar

Cyclic
Lothrazar
Cyclic-1.16.5-1.4.0.jar

Decorative Blocks
stohun
decorative_blocks-1.16.4-1.7.2.jar

Decorative Blocks modded compat
Evo_934
decorative_blocks_abnormals-1.2.jar

Discord Integration Forge
ErdbeerbaerLP
dcintegration-forge-2.3.2-1.16.jar

DrawerFPS
someaddon
drawerfps-2.1.jar

Drawers Tooltip
Snownee_
DrawersTooltip-1.16.2-2.1.0.jar

Druidcraft
VulpTheHorseDog
Druidcraft-1.16.5-0.4.53.jar

Dungeons Mobs
the_infamous_1
dungeons_mobs-1.16.5-1.0.10.jar

Dusk
someaddon
dusk-1.4.jar

Dynamic Surroundings
OreCruncher
DynamicSurroundings-1.16.4-4.0.4.2.jar

Dynamic View
someaddon
dynviewdist-2.0.jar

Eidolon
elucent_
eidolon-0.2.7.jar

Enchanted Book Redesign
tfarecnim
enchantedbookredesign-3.3-1.16.4.jar

Enchantment Descriptions
DarkhaxDev
EnchantmentDescriptions-1.16.5-7.0.12.jar

Ender Storage 1.8.+
covers1624
EnderStorage-1.16.5-2.8.0.168-universal.jar

Engineer's Decor
wilechaote
engineersdecor-1.16.4-1.1.14.jar

Environmental
TeamAbnormals
environmental-1.16.5-1.1.0.jar

Environmental Core
ValkyrieofNight
envirocore-1.16.5-3.0.9.1.jar

Environmental Tech
ValkyrieofNight
envirotech-1.16.5-3.0.9.4.jar

ExpandAbility
florensie
expandability-2.0.1-forge.jar

Extra Disks
MelanX
extradisks-1.16.4-1.5.1.jar

ExtraStorage
3divad99
ExtraStorage-1.16.5-1.5.0.jar

Extreme Reactors
ZeroNoRyouki
ExtremeReactors2-1.16.5-2.0.27.jar

Farsight
someaddon
farsight-1.6.jar

Fast Leaf Decay
olafskiii
FastLeafDecay-v25.jar

FerriteCore (Forge)
malte0811
ferritecore-2.0.7-forge.jar

Flux Networks
sonar_sonic
FluxNetworks-1.16.5-6.1.7.12.jar

Forbidden and Arcanus
cesar_zorak
forbidden_arcanus-16.2.0-beta-4.jar

FTB Backups (Forge)
FTB
ftb-backups-2.1.1.6.jar

FTB Essentials (Forge)
FTB
ftb-essentials-1605.1.4-build.20.jar

FTB Library (Forge)
FTB
ftb-library-forge-1605.3.3-build.71.jar

GeckoLib
ThanosGecko
geckolib-forge-1.16.5-3.0.46.jar

Goblin Traders
MrCrayfish
goblintraders-1.6.0-1.16.3.jar

Hats
ohaiiChun
Hats-1.16.5-10.3.1.jar

Ice and Fire: Dragons
alex_khaan
iceandfire-2.1.9-1.16.5.jar

iChunUtil
ohaiiChun
iChunUtil-1.16.5-10.4.1.jar

Industrial Foregoing
Buuz135
industrial-foregoing-1.16.5-3.2.14.6-14.jar

Iron Chests
ProgWML6
ironchest-1.16.5-11.2.13.jar

Jade 🔍
Snownee_
Jade-1.16.4-2.7.4.jar

JEI Integration
SnowShock35
jeiintegration_1.16.5-7.0.1.15.jar

JEITweaker
Jaredlll08
JEITweaker-1.16.5-1.0.1.34.jar

JourneyMap
techbrew
journeymap-1.16.5-5.7.3.jar

Just Enough Items (JEI)
mezz
jei-1.16.5-7.7.1.121.jar

Just Enough Resources (JER)
way2muchnoise
JustEnoughResources-1.16.5-0.12.1.128.jar

KleeSlabs
BlayTheNinth
KleeSlabs_1.16.5-9.2.1.jar

KubeJS Blood Magic
LatvianModder
kubejs-blood-magic-1605.1.1-build.3.jar

KubeJS Create
LatvianModder
kubejs-create-1605.1.2-build.7.jar

KubeJS Mekanism
LatvianModder
kubejs-mekanism-1605.1.2-build.2.jar

LibX
noeppinoeppi
LibX-1.16.3-1.0.76.jar

Macaw's Bridges
sketch_macaw
mcw-bridges-1.0.6-mc1.16.5.jar

Macaw's Doors
sketch_macaw
mcw-doors-1.0.3-mc1.16.5.jar

Macaw's Fences and Walls
sketch_macaw
mcw-fences-1.0.0-mc1.16.5.jar

Macaw's Roofs
sketch_macaw
mcw-roofs-2.0.1-mc1.16.5-4.jar

Macaw's Windows
sketch_macaw
mcw-windows-2.0.0-mc1.16.5.jar

Magical Psi: Redux
TheIllusiveC4
magipsi-1.16.5-2.0.0.1.jar

Mana and Artifice
AWildCanadianEh
mana-and-artifice-1.4.0.8.jar

Mantle
mDiyo
Mantle-1.16.5-1.6.123.jar

Mekanism
bradyaidanc
Mekanism-1.16.5-10.0.21.448.jar

Mekanism Additions
bradyaidanc
MekanismAdditions-1.16.5-10.0.21.448.jar

Mekanism Generators
bradyaidanc
MekanismGenerators-1.16.5-10.0.21.448.jar

Mekanism Tools
bradyaidanc
MekanismTools-1.16.5-10.0.21.448.jar

MineColonies
H3lay
minecolonies-1.0.0-RELEASE-universal.jar

Mouse Tweaks
YaLTeR
MouseTweaks-2.14-mc1.16.2.jar

Mowzie's Mobs
bobmowzie
mowziesmobs-1.5.19.jar

Music Maker Mod
xerca0
xercamusic-1.16.5-1.4.jar

Mystical Agradditions
BlakeBr0
MysticalAgradditions-1.16.5-4.2.1.jar

Mystical Agriculture
BlakeBr0
MysticalAgriculture-1.16.5-4.2.2.jar

Mystical Customization
BlakeBr0
MysticalCustomization-1.16.4-2.1.5.jar

Mystical World
Noobanidus
mysticalworld-1.16.5-0.3.3.19.jar

Nature's Compass
Chaosyr
NaturesCompass-1.16.5-1.9.1-forge.jar

NetherPortalFix
BlayTheNinth
NetherPortalFix_1.16.3-7.2.1.jar

ObserverLib
HellFirePvP
observerlib-1.16.5-1.5.3.jar

Overloaded Armor Bar
tfarecnim
overloadedarmorbar-5.1.0.jar

Paintings ++
AbsolemJackdaw
paintings-1.16.4-7.0.0.1.jar

Performant
someaddon
performant-1.16.2-5-3.72m.jar

Placebo
Shadows_of_Fire
Placebo-1.16.5-4.6.0.jar

Polymorph (Forge)
TheIllusiveC4
polymorph-forge-1.16.5-0.25.jar

Psi
Vazkii
Psi 1.16-95.jar

Quark
Vazkii
Quark-r2.4-316.jar

Rats
alex_khaan
rats-7.2.0-1.16.5.jar

ReAuth
TechnicianLP
ReAuth-1.16-Forge-3.9.3.jar

Refined Storage
raoulvdberge
refinedstorage-1.9.15.jar

Refined Storage Addons
raoulvdberge
refinedstorageaddons-0.7.3.jar

Refined Storage: Requestify
Buuz135
rsrequestify-1.16.5-2.1.3.jar

Savage & Ravage
TeamAbnormals
savageandravage-1.16.5-3.1.0.jar

Selene Lib
MehVahdJukaar
selene-1.16.5-1.7.jar

Serene Seasons
TheAdubbz
SereneSeasons-1.16.5-4.0.1.121-universal.jar

Shutup Experimental Settings!
Corgi_Taco
shutupexperimentalsettings-1.0.3.jar

Simple Discord RPC [Forge/Fabric]
hypherionsa
simple-rpc-1.16.5-2.3.1.jar

Storage Drawers
Texelsaur
StorageDrawers-1.16.3-8.3.0.jar

Storage Drawers crash fix
HaydnV
StorageDrawers-1.16.3-8.2.2-fixed.jar

Supplementaries
MehVahdJukaar
supplementaries-1.16.5-0.16.1.jar

SwingThroughGrass
exidex
swingthroughgrass-1.16.4-1.5.3.jar

The Endergetic Expansion
TeamAbnormals
endergetic-1.16.4-3.0.0.jar

The Outer End
BlueDuckYT
OuterEnd-0.2.14.jar

Tinkers Construct
mDiyo
TConstruct-1.16.5-3.1.2.265.jar

Titanium
Buuz135
titanium-1.16.5-3.2.8.5-20.jar

Tome of Blood
ToxicMintTea
tomeofblood-1.16.5-1.2.jar

Torch Slabs Mod
EndlesNights
torchslabmod-1.16.4_v1.6.19.jar

Upgrade Aquatic
TeamAbnormals
upgrade_aquatic-1.16.5-3.1.0.jar

Valhelsia Core
ValhelsiaTeam
valhelsia_core-16.0.10.jar

Valhelsia Structures
ValhelsiaTeam
valhelsia_structures-1.16.5-0.1.5.jar

ValkyrieLib
ValkyrieofNight
valkyrielib-1.16.5-3.0.9.2.jar

Vampirism - Become a vampire!
maxanier
Vampirism-1.16.5-1.8.1.jar

Vampirism Integrations
maxanier
VampirismIntegrations-1.16.5-1.6.0-beta.1.jar

Vending Tile
tfarecnim
vending-2.1-1.16.4.jar

Waila Harvestability
squeek502
WailaHarvestability-mc1.16.x-forge-1.1.15.jar

Waystones
BlayTheNinth
Waystones_1.16.5-7.6.3.jar

When Dungeons Arise - Forge!
Aureljz
DungeonsArise-1.16.5-2.1.47-release.jar

Windowlogging
mc_Grimmauld
windowlogging-mc1.16.3_v0.0.4.jar

Woot
Ipsis
woot-1.16.5-1.0.8.0.jar

YUNG's API (Forge)
YUNGNICKYOUNG
YungsApi-1.16.4-Forge-12.jar

YUNG's Better Caves (Forge)
YUNGNICKYOUNG
BetterCaves-Forge-1.16.4-1.1.2.jar

YUNG's Better Dungeons (Forge)
YUNGNICKYOUNG
BetterDungeons-1.16.4-1.2.jar

YUNG's Better Mineshafts (Forge)
YUNGNICKYOUNG
BetterMineshafts-Forge-1.16.4-2.0.4.jar

YUNG's Better Strongholds (Forge)
YUNGNICKYOUNG
BetterStrongholds-1.16.4-1.2.1.jar

ZeroCore 2
ZeroNoRyouki
ZeroCore2-1.16.5-2.1.3.jar

## Expected behavior
 The player to be able to connect to the server

## Actual behavior
 The specific player connects then a internal error happens and he is then diconected

## Steps to reproduce the issue

 
    1. Create a minecoloney on a server 
    2. Set any players permissions to co-owner
    3. said player with permission of co-owner will not be able to log in again after they disconnect until co-owner role is removed

### Logs

- latest.log:  https://gist.github.com/DecVrc/54dfa1c7bf51fe53c5df898614f87cc8
- crashlog:  No Crash Happens
- client log: https://gist.github.com/DecVrc/2ed5a99ab8a0de22771d66aa00f68d9e

### Notes
 
We reinstalled the pack via curse forge (the pack is running an older version of minecolonies but I updated both client and server to the newest version to test for the issue which it  still occoered.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
It looks like there's a corrupted Rank in a colony near where they're trying to log in.

**Comment by DecVrc** [comment]
> It looks like there's a corrupted Rank in a colony near where they're trying to log in.

I will check it tomorrow when he's available

**Comment by DecVrc** [comment]
> It looks like there's a corrupted Rank in a colony near where they're trying to log in.

Done some testing around and Figured out the issue if you make any person a co- owner in any colony in multiplayer or at least on my server they will have that error

**Comment by uecasm** [comment]
What do you mean by co-owner?  A colony can only have one owner.  Do you just mean giving them the Officer rank?

**Comment by DecVrc** [comment]
> What do you mean by co-owner? A colony can only have one owner. Do you just mean giving them the Officer rank?

I see so on the server it generates a role called co-owner and I'm not sure what causes this but when in single player it doesn't generate this role. 
so I guess this leads to my next question is there a way to change the progenerated default roles on the server and remove that role from pre existing colonies

**Comment by Raycoms** [comment]
I guess the co-owner role was potentially added manually?

**Comment by DecVrc** [comment]
> I guess the co-owner role was potentially added manually?

not sure i just had a new player make a colony and it didn't create the role
so at this point I need to just remove the role from pre existing colonies

**Comment by DecVrc** [comment]
is there any way to do that from the colonies.dat files  in the world folder?

**Comment by Raycoms** [comment]
Solved
