### ISSUE TITLE
Builder only grabbing one itemstack at a time from batch

### ISSUE THREAD

**Issue by KKomrade** [ldtteam/minecolonies#7600]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version:
- Structurize Version:

## Problem description
   A while back, there were some changes to the builder that prevented them from grabbing blocks in the batch from any rack without moving at all. Because the builder would search racks and grab one item stack at a time, this was fine with the old system, but with the new system, it has become problematic for any Builder's Huts where the racks are not immediately next to the builder's hut.

   Why is this a problem? Let's say your builder gets a batch with 20 different items, and in the medieval styles, the racks are underground, so they spend 10 seconds grabbing each item stack and returning to the hut. That's over 3 minutes per batch spent walking back and forth between the hut block and the racks. My suggestion to remedy this problem is to either A) Revert the changes that made the builder have to walk to racks, or B) Make the builder grab all of the items in the batch at once without returning to the hut block for each different block.

   Hopefully this all made sense, and I love Carlansor's amazing medieval designs as well as some of the other elaborate builder's huts, and I hope I can use them in the future without worrying about the efficiency of my builders. 

### Notes or related things

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by carl010010** [comment]
Can confirm that this adds significant amount of time to how long it takes for a builder to build.
 
 Edit: Just for completeness sake, I'm using the dark oak alternative
