### ISSUE TITLE
Can't change dynamic trees radius in the forester's setting

### ISSUE THREAD

**Issue by lebanni** [ldtteam/minecolonies#7601]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-1.0.2-ALPHA-universal.jar
- Structurize Version: structurize-0.13.230-ALPHA-universal.jar
- Related Mods and their Versions:

## Expected behavior

Change Dynamic Trees Radius in the forester's hut GUI.

## Actual behavior

On the settings tab, you can't remove the "5" number. All you can do is add any numbers after it.
I tried to change the value in the config file, with no effect.

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
That is the case for all settings fields with numbers (e.g. at the composter as well). First type the number you want to set it to after the current number (e.g. “57”), then go back to the 5 and delete it

**Comment by Raycoms** [comment]
Yeah that's the way it's currently implemented.

**Comment by lebanni** [comment]
Thanks.
