### ISSUE TITLE
Citizen cannot interact or do any actions

### ISSUE THREAD

**Issue by faustojc** [ldtteam/minecolonies#7602]
### Prerequisites

- [ ] I am running the latest 1.0.0-RELEASE version of MineColonies for my Minecraft version.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context

- Minecraft Version: 1.16.5
- MineColonies Version: 1.0.0-RELEASE

### Logs

- latest.log: https://gist.github.com/faustojc/5dab81b96d8cd42682a8acb4e96d72fd

## Steps to reproduce the issue / details
- Just reporting the AI issue. My citizen cannot be interact and doesn't do anything. Basically, nothing like a display with name on it.

### Notes
- The citizen is just a display like no AI 

## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

![Untitled](https://user-images.githubusercontent.com/61080389/133871282-b9777764-03ae-450d-b61f-5d2c2a9c6c93.png)

**Comment by Raycoms** [comment]
Does reloading the chunk/area fix it? This might be a vanilla duplicate

**Comment by faustojc** [comment]
Yes it does and by exiting and starting the world, but it still happens sometimes that's why I file a bug report.

**Comment by Raycoms** [comment]
Yeah, that's okay. It's a vanilla thing we can't do a lot of things against.
