### ISSUE TITLE
AbstractPathJob does not respect block shape

### ISSUE THREAD

**Issue by baileyholl** [ldtteam/minecolonies#7603]
When checking for passability of a particular block, a check is made for if the material blocks motion, but is missing a check on the ability for the actual blockstate to collide, or its shape. This causes entities to attempt to jump over or on top of blocks that they could easily walk over.

The primary line is here:
https://github.com/ldtteam/minecolonies/blob/d20939d9dfa8f9994d1791992d6741fb9932a19e/src/main/java/com/minecolonies/coremod/entity/pathfinding/pathjobs/AbstractPathJob.java#L1325

The final else condition where the voxel shape is checked is never made for blocks who have a material that blocks motion such as stone but are actually pathable.

The fix for my case was making an additional check on that line to ensure that both the material blocks motion AND the blockstate itself blocks motion by using another voxel shape check.

Going from:  
```java
if (block.getMaterial().blocksMotion())
```
to  
```java
if (block.getMaterial().blocksMotion() && !(shape.isEmpty() || shape.max(Direction.Axis.Y) <= 0.1))
```

**Comment by ravenbuilder934** [comment]
If you've fixed it, you're welcome to open a PR!

**Comment by Raycoms** [comment]
I asked them to open it.

**Comment by ravenbuilder934** [comment]
Whoops, didn't actually mean to close it at all, just leave a comment
