### ISSUE TITLE
Crash with NullPointerException because of Guard Scepter

### ISSUE THREAD

**Issue by tobischiebel** [ldtteam/minecolonies#7604]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.340-ALPHA 
- Structurize Version: 0.13.208-ALPHA

## Problem description

Repeatedly experiencing crashes of the Valhelsia 3 Modpack due to a Nullpointer Exception. The log states it occurs at at `com.minecolonies.coremod.event.ClientEventHandler.handleRenderScepterGuard(ClientEventHandler.java:522) ~[?:0.14.340-ALPHA] {re:classloading,pl:runtimedistcleaner:A}`. I am not entirely sure and can't check, as I am unable to join my world, but I think I might have it equipped in my active slot (was moving it from a chest into my inventory).

Here is my crash log:
[crash-2021-09-19_23.41.49-client.txt](https://github.com/ldtteam/minecolonies/files/7192985/crash-2021-09-19_23.41.49-client.txt)

### Notes or related things

Quick question... how can I ever join my world again as the item which seems to cause the problem stays in my inventory?

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
Answer to the quick question:

Open your playerdata file with nbt explorer, and delete the offending item (the guard tool), there is a list off inventory items in the playerdata file, and you only needs to delete that one thing.

**Comment by Raycoms** [comment]
Hotfix pushed

**Comment by tobischiebel** [comment]
Follow up: I moved the Guard Scepter to a different slot, which resolved the issue and I could join the world again. Thank you :)
