### ISSUE TITLE
Minimum stock feature in restaurant building causing a game crash

### ISSUE THREAD

**Issue by AbdulmajeedAlOmari** [ldtteam/minecolonies#7606]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 1.0.6-ALPHA
- Structurize Version: 0.13.230-ALPHA
- Related Mods and their Versions: Modpack used (All The Mods 6 version 1.18.3)

## Expected behavior

Assign minimum stock for restaurant building

## Actual behavior

Crashes the game and shows "Saving World" when you click the Add button in minimum stock page

![image](https://user-images.githubusercontent.com/33428565/134012471-09f62ed2-f497-4678-8769-a47839b53aed.png)
![image](https://user-images.githubusercontent.com/33428565/134012815-f5e9bbcc-e373-407b-8f36-8860675432e8.png)

## Steps to reproduce the issue

1. Open restaurant building block
2. Click on minimum stock
3. Click on add button
4. Game shows "Saving World" for a brief moment and then it crashes

### Logs

- latest.log: [latest.log](https://gist.github.com/AbdulmajeedAlOmari/54456f36bfce3fa70f508abc15aec55b) 
- crashlog: [crashlog](https://gist.github.com/AbdulmajeedAlOmari/54456f36bfce3fa70f508abc15aec55b) 

### Notes

I tested the minimum stock feature in restaurant building only, I'm not sure if this applies to other buildings as well.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by AbdulmajeedAlOmari** [comment]
This seems a like a duplicated issue as there was a report in this issue https://github.com/ldtteam/minecolonies/issues/7508 but in the thread, it mentions that it was fixed in a later version but we're still facing this issue.

**Comment by Raycoms** [comment]
This is an incompatibility with: codechicken.microblock.ItemMicroBlock
We did adjust our code in this regard to only query the creative tabbed items. If this is still a problem, they will have to fix this on their side as far as my understanding of this goes.

**Comment by AbdulmajeedAlOmari** [comment]
I see, thank you @Raycoms, I will try to reach them out regarding this issue.

**Comment by MotionlessTrain** [comment]
Update forge multipart. They fixed the issue already

**Comment by AbdulmajeedAlOmari** [comment]
> Update forge multipart. They fixed the issue already

Hey @MotionlessTrain, what do you mean by forge multipart? The forge JAR file in this link https://files.minecraftforge.net/net/minecraftforge/forge/index_1.16.5.html ?

**Comment by AbdulmajeedAlOmari** [comment]
Oh, I think I found what you meant @MotionlessTrain:
https://www.curseforge.com/minecraft/mc-mods/cb-multipart

Thanks!

**Comment by MotionlessTrain** [comment]
Yeah, I meant that one. Sorry for the confusion.

You're welcome!
