### ISSUE TITLE
Crash upon using the build tool with jar schematics disabled

### ISSUE THREAD

**Issue by IchHabeHunger54** [ldtteam/minecolonies#7607]
- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context

- Minecraft Version: 1.16.5
- MineColonies Version: 1.0.7-ALPHA
- Structurize Version: 0.13.230-ALPHA
- Related Mods and their Versions: N/A

## Expected behavior
I am making my modpack, and I want to remove some styles and buildings. Long story short, I extracted the schematics from the jar into an OpenLoader resource pack, removed the Warped style and a few hut buildings (sifter, stonesmeltery and some others) and set Structurize's Ignore Jar Schematics config option to true.

Now when I want to use the build tool, I want it to work as usual.

## Actual behavior
Game freezes and eventually crashes. See logs below.

I already tried to debug this on Discord, but people couldn't help me there either.

## Steps to reproduce the issue

1. Extract the schematics of both Structurize and Minecolonies into a resourcepack and load that resourcepack (I assume OpenLoader is unrelated).
2. Disable Jar Schematics in the Structurize config.
3. (unsure if this actually affects anything) Remove the Warped (or any other) style from the schematics.
4. Launch your game and try to use a build tool on the floor.
5. Tada!

### Logs

- debug.log: https://gist.github.com/IchHabeHunger54/fb745b78cb4c7a76e6586698d9bfd2c6
Edit: No, this is not the entire debug.log, I needed to crop it at the top, otherwise Gist would yell at me for trying to upload a 30 MB file.

### Notes
Is inside a modpack with 80-90 other mods inside, so it could theoretically be an incompatibility with some other mod, though I highly doubt that.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
One last thing to debug: Can you try putting a schematic inside of the structurize/schematics folder of the minecraft folder?

**Comment by IchHabeHunger54** [comment]
Tried that, didn't change the outcome.

**Comment by uecasm** [comment]
Resource pack schematics are not supported.  The schematics do need to either be in a mod jar or directly in the structurize/schematics folder.  The crash occurs because some required schematics are missing.

**Comment by Raycoms** [comment]
No problem anymore in latest I believe
