### ISSUE TITLE
[1.16.5] Builders will not move to next task until night has happened 

### ISSUE THREAD

**Issue by b52src** [ldtteam/minecolonies#7608]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.16.5
- MineColonies Version:1.0.7 Alpha, also had issue with 1.0.0 this is why this is updated to the latest alpha build 
- Structurize Version:0.13.230 Alpha
- Related Mods and their Versions: Modpack: Life In the Village 2 1.2.6

## Expected behavior
Builders move on to the next task after completing their build or upgrade within the same day.

## Actual behavior

When builder completes their build or upgrade they go back to their hut and their stat changes to load structure trying to move on to the next task but the builder will not start their next task until night has happened. so small builds such as roads or smaller buildings complete but builder will not build the next thing until the next day, making small tasks like building roads take a long time.

## Steps to reproduce the issue

1. create new colony(I'm doing fortress theme) (note for troubleshooting infinite builder resources and builder speed is ramped up to delay of 3 and work in rain. also dev features are enabled to see builder state.)
2. try and upgrade or build 2 smaller builds such as the level 1 currier and miner in the same day 
3.  builder should be stuck in Structure_Load until a night cycle has happened. once night has happened it will finally move onto its next task.

### Logs

- latest.log:  https://gist.github.com/b52src/26e318f3c8e10f1647b2f9d7e1e650e5
- crashlog:  N/A no crash

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Volinock** [comment]
So I have the same exact issue. However if you pause then restart the worker while at their station they will immediately start working. Not a complete fix but its something until it gets a fix!

**Comment by MotionlessTrain** [comment]
Do you have the configuration setting "builderinfiniteresources" turned on? I know that could cause this bug.
If so, that builder's setting is buggy and not supported anymore.

**Comment by Volinock** [comment]
> Do you have the configuration setting "builderinfiniteresources" turned on? I know that could cause this bug. If so, that builder's setting is buggy and not supported anymore.

Yes, actually. That might be the issue then, unfortunately.

**Comment by MotionlessTrain** [comment]
In creative mode, you can fulfill requests from the builder without actually having the resources. That is the better way to achieve the same goal.
Alternatively, also in creative, you can paste buildings in using the build tool
