### ISSUE TITLE
Mine-Colonies official mod pack crashes entering world

### ISSUE THREAD

**Issue by krakenmorski** [ldtteam/minecolonies#7609]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: Curse-Forge Official Modpack "minecolonies-1.0.0-RELEASE-universal"
- Structurize Version: Curse-Forge Official Modpack "structurize-0.13.219-ALPHA-universal"
- Related Mods and their Versions: Curse-Forge Official Modpack 

## Expected behavior
I wanted to play my colonies Curse-Forge Official Modpack creative world.

## Actual behavior

I wanted to play my colonies Curse-Forge Official Modpack creative world.
The first time launching I had fun, I created a fun colony.
The next time launching, I created a new world having an idea of what colony I can build.
The next thing I joined, I should see the square loading screen.
But nothing was appearing. When I clicked the game, it froze.
Now it is the same every time I launch...

## Steps to reproduce the issue

Can you help me play my Minecraft mod pack? 😥
Btw I added world-edit but it doesn't change anything.
### Logs

[latest.log](https://github.com/ldtteam/minecolonies/files/7212463/latest.log)

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation

.

**Comment by Raycoms** [comment]
Something is wrong with the config file: net.minecraftforge.fml.config.ConfigFileTypeHandler$ConfigLoadingException: Failed loading config file D:\mincrafttwiter\Instances\MineColonies Official\config\waystones-server.toml of type SERVER for modid waystones

Delete it, and restart.

**Comment by Raycoms** [comment]
Also, this is the wrong place to ask for this.

**Comment by krakenmorski** [comment]
> Something is wrong with the config file: net.minecraftforge.fml.config.ConfigFileTypeHandler$ConfigLoadingException: Failed loading config file D:\mincrafttwiter\Instances\MineColonies Official\config\waystones-server.toml of type SERVER for modid waystones
> 
> Delete it and restart.

Thank you!!! Finally, I can have fun with this mod! well I haven't tested if it works tho yet
