### ISSUE TITLE
Dark oak and Lumber Jack

### ISSUE THREAD

**Issue by Thanaen** [ldtteam/minecolonies#761]
### Minecolonies version

version 0.7.3.2 or curse 7.1.6296.41462

### Expected behavior

- Cut down a dark oak, a plant back 4 saplings in square.

### Actual behaviour

- She plants only one sapling, which is useless :(

### Steps to reproduce the problem

1. Have a dark oak
2. Have a lumber jack
3. Oh
4. it fails

**Comment by Raycoms** [comment]
she only plants 1, are you sure? I coded it that she should plant all 4.
Did she wait for a time and didn't get enough saplings droppeD?

2017-04-04 14:14 GMT-03:00 Thanaen <notifications@github.com>:

**Comment by Wissi** [comment]
What version are you using (1.10.2 - 1.11.2) and what specific build? maybe not the latest?

**Comment by Raycoms** [comment]
1.10.2 the latest build he uses.

2017-04-04 14:51 GMT-03:00 Wissi <notifications@github.com>:

**Comment by Thanaen** [comment]
Using latest build!
I've seen plenty of lonely Dark oak that were planted on the village, where dark oaks were planted

**Comment by Raycoms** [comment]
hmm can you take a look while she is cutting and observe: Does she have
enough dark oak saplings, does she wait a time until saplings drop down?

2017-04-04 15:03 GMT-03:00 Thanaen <notifications@github.com>:

**Comment by SulpherStaer** [comment]
I have just observed the lumberjack, and ensured she had enough dark oak saplings in her inventory. After successfully chopping down a dark oak tree, she placed 4 saplings in a square, in the exact place of the tree she just chopped down.

I think this issue isn't so much about incorrectly planting, but planting a sapling of dark oak when she doesn't have enough. Perhaps a check that she has at least 4 before even attempting to plant a dark oak sapling, and else skipping replanting the dark oak.

**Comment by marvin-bitterlich** [comment]
closing this as it seems to behave correctly
