### ISSUE TITLE
Farmer in pack v1.26 not always replanting

### ISSUE THREAD

**Issue by ZippityDoodah** [ldtteam/minecolonies#7610]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [ x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 1.0.0-RELEASE

### Logs

https://gist.github.com/ZippityDoodah/27a901993f59cbf9750507a1f832ec3e

- latest.log: 

## Steps to reproduce the issue / details

Unsure if this issue is occurring in any other packs besides Life in the Village 2 (v1.26) but the Farmer is not always replanting after harvesting. The farmer has plenty of seeds, the ground is tilled (regardless if it's tilled dirt or other tilled block), and tried various tools from Stone Axe-Diamond Axe-Emerald Axe. It's as if the AI is not always properly reacting to the need for replanting a square within the confines of the Scarecrow's setup after breaking the plant (aka harvesting). This problem occurs regardless if chunk is loaded or not, as I can stand in the same chunk and the issue still occurs.

### Notes

Life in the Village 2 Modpack (v1.26)
Forge Version 1.16.5-36.2.4

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Justen-N** [comment]
Your log doesn't contain any useful information. What level is the farmer? How long are you waiting for them to replant? There is a delay for most tasks that depends on the citizens' level. Unless those spots never get replanted, I don't think this is a bug.

**Comment by Raycoms** [comment]
I'm not sure if I should close this or not. The farmer cycles through phases for different fields. They are not 100% efficient on purpose (else they'll eventually end up littering your storage). They harvest/till/replant in different phases. They will only start the next phase after the current is completely finished (which might sometimes implied harvesting the entire field and waiting for it to be fully grown).

**Comment by ZippityDoodah** [comment]
Level 5 Farm Hut, with only 3 fields... Wheat, Carrots, and Potatoes... The larger field is Wheat... If I ignore the farm for a day, practically every block where there should be wheat growing will be empty of anything growing, it isn't as bad with the carrots and potatoes, but they are smaller fields... Typically the farmer would always replant after breaking a crop (pre-update), but if I don't replant myself, eventually the fields become empty of plants at all... This issue did not begin until the modpack author updated their pack with the version of Minecolonies I mentioned above... Is it a possibility that the issue is one of needing the chunk to be loaded at all times in order for the farmer to function correctly? If that is the case, this will almost never be a possibility if the player goes out exploring and has to deal with the vastness of the Town as it becomes larger and larger...

**Comment by Raycoms** [comment]
Was Pams removed or so maybe? The harvest/replant only happens if pams is installed

**Comment by ZippityDoodah** [comment]
The pack has both Pam's HavestCraft 2 Crops and Pam's HavestCraft 2 Food Core... Does the mod look at what the warehouse contains as far as things like the crops it's farming and seeds it's harvesting and then do this on purpose in order to keep the warehouse from being overrun with the seeds and plants? I do notice that the Warehouse does have a tendency to receive a ton of Wheat Seeds from the farm... I been having to go remove them when I feel there is an overabundance... It was mentioned above that the farmer is not 100% efficient on purpose, is it perhaps going overboard with that function or is it smart enough to notice the warehouse surplus?
