### ISSUE TITLE
Custom rank only half exists, causing null reference

### ISSUE THREAD

**Issue by uecasm** [ldtteam/minecolonies#7612]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 1.0.0-RELEASE (and also latest dev build)
- Structurize Version: 0.13.219-ALPHA

## Expected behavior

Using world in uecasm/colony4cc#9, should be able to read player permissions.

## Actual behavior
NullPointerException in `Permissions.hasPermission` whenever Rank parameter is the "auto" rank.

In this particular colony, it appears that `ranks` contains the "auto" rank but `permissionMap` does not.

## Steps to reproduce the issue

I'm not certain what gets the colony into this state, but it can be observed already in this state in the colony export in the linked issue.

## Notes

In this state, trying to add any permission to the "auto" rank in the town hall GUI causes an NPE CTD.

Deleting the "auto" rank and creating it again appears to fix it (including after restarting the server), so perhaps it was some previous version that generated the damaged rank, and the remaining bug is just that it doesn't auto-repair it?

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by RedStoner** [comment]
Any questions about the colony export can be directed at me.
