### ISSUE TITLE
Builder cannot use Rally Banner.

### ISSUE THREAD

**Issue by RedStoner** [ldtteam/minecolonies#7613]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**  

### Context 
minecolonies-1.0.0-RELEASE-universal
structurize-0.13.219-ALPHA-universal

## Expected behavior

Builder builds schematic with rallying banner
## Actual behavior

builder requests rallying banner, but does not accept any of them i give. You have to manually place the banner.

## Steps to reproduce the issue

build barraks lvl 3 for dark oak. it will require a banner. Builder will never place it.

### Logs

on server... i have no access to these.

### Notes

Showing this issue as fixed in a prior issue report. This has not been fixed.
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by someaddons** [comment]
![image](https://user-images.githubusercontent.com/38401808/134821047-c6a5179c-83ff-4c27-87c1-48cc7f5b9114.png)

**Comment by RedStoner** [comment]
Question for the one who closed this the minute it opened..... How is someone thats on a server supposed to be able to update the server they dont own?????

**Comment by RedStoner** [comment]
@someaddons

**Comment by RedStoner** [comment]
Sorry for reporting a bug I found and trying to help improve your program some more. I have learned my mistake and will never report a bug here again. Thank you for the 'support'

**Comment by MotionlessTrain** [comment]
As an additional note: In the release version, this should work. I don't think anything changed with rallying banners in the 7 versions after the release version.
The fact that this does not work in some cases in the release is serious enough to keep this issue open, I would think

**Comment by uecasm** [comment]
> How is someone thats on a server supposed to be able to update the server they dont own?????

You can test it in single-player, or ask the server admin to report it.  Or discuss the issue on Discord first.

> The fact that this does not work in some cases in the release is serious enough to keep this issue open, I would think

The problem is that this particular report contains no information that can actually be actioned.  If you try doing that action, it works perfectly every time (as far as I am aware, and I have tested exactly that multiple times).  Nobody has yet discovered a reproducible means to break it.  And in general, it is not useful to make issues without logs; it's better to try to reproduce it and get logs, or discuss things on Discord first.

**Comment by RedStoner** [comment]
"You can test it in single-player, or ask the server admin to report it. Or discuss the issue on Discord first. "

If you had been on discord or even looked, you would see i was on there and trying to get support. And i did test in singleplayer. All that information is there. Was planning on putting it here, but it was instantly denied. The action of it being instantly denied simply because i did not test it on an experimental branch where none of that code was touched, and should have been fixed in the version i was working on, is the reason i put no further testing information on here. What is the point of adding more information if the post is just going to be instantly denied.

"The problem is that this particular report contains no information that can actually be actioned. "

That is not the reason this was closed, why not take a look at the first comment posted. And as for how to replicate, that is what i did. Would you like me to add in additional steps that have nothing to do with this just to make it look more actionable?
