### ISSUE TITLE
problem with building the medevildarkoakalternative town hall

### ISSUE THREAD

**Issue by GamerArvils** [ldtteam/minecolonies#7619]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.16.5
- MineColonies Version:1.0.0
- Structurize Version:0.13.219
- Related Mods and their Versions:what ever is in the minecolonies modpack

## Expected behavior

when building medevildarkoakalternative town hall it should finish
## Actual behavior

it shows it doesnt need anymore blocks it is step 0/6 but the building is finished

![2021-09-30_18 41 29](https://user-images.githubusercontent.com/91677259/135488694-e198036f-719b-458a-9663-84133cbd3991.png)

![2021-09-30_18 43 03](https://user-images.githubusercontent.com/91677259/135488711-2f0fe1cd-0368-4464-a664-7a65c527a38c.png)

## Steps to reproduce the issue

1. try to make a medevildarkoakalternative town hall in a coniferous clearing
2. asign a builder to buld it and give it all the materials
3. it finished but still has the construction tame thing around hom

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
It's an enormous building, have you waited for a while so that it can finish the scanning?

**Comment by GamerArvils** [comment]
i have had it like that for an hour

**Comment by KKomrade** [comment]
Something that helped me with the level 1 medieval alt TH is restarting game and then waiting some more. I do remember it taking a very long time.

**Comment by GamerArvils** [comment]
i have waited hours i am giving up and restarting but i will not close it yet incase i still have the problem

**Comment by Raycoms** [comment]
Should be solved, reopen if still an issue
