### ISSUE TITLE
minecolonies-1.0.8-ALPHA requiring Structurize Version: 0.13.230-ALPHA and is rejects all later versions

### ISSUE THREAD

**Issue by superdude808** [ldtteam/minecolonies#7622]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-1.0.8-ALPHA-universal
- Structurize Version: structurize-0.13.235-ALPHA-universal
- Related Mods and their Versions:

## Expected behavior
the game to load

## Actual behavior

![crash picture](https://user-images.githubusercontent.com/18659186/135749216-b45e6a54-bff1-43cf-938d-f7472ec9e6aa.png)

## Steps to reproduce the issue

load the game with the latest 1.16.5 versions of minecolonies and structurize together 

### Logs

[latest.log](https://github.com/ldtteam/minecolonies/files/7273116/latest.log)

[crash-2021-10-03_18.10.45-fml.txt](https://github.com/ldtteam/minecolonies/files/7273118/crash-2021-10-03_18.10.45-fml.txt)

### Notes

probably just a simple mistake of defining a singular required version of structurize instead of a range of versions or a minimum version requirement
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
Intended behaviour.
Later versions of structurize may have breaking changes, which minecolonies needs to adapt to. Hence only one version of structurize is allowed, one which guarantees to work.
