### ISSUE TITLE
Unable to install new 1.17 pack

### ISSUE THREAD

**Issue by RedStoner** [ldtteam/minecolonies#7623]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.17
- MineColonies Version: not sure cannot install pack
- Structurize Version: not sure cannot install pack

## Problem description

Trying to install the new pack via curse forge is giving an error on intallation. 
![image](https://user-images.githubusercontent.com/1278466/135771479-1269d889-7e92-4b32-bb78-817cbb9dc1c8.png)
Several users in discord are reporting the same issue.
### Notes or related things

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
This repository is only for issues with the mod itself, please stay on discord for the modpack

**Comment by RedStoner** [comment]
Except..... 
![image](https://user-images.githubusercontent.com/1278466/135771578-cc835889-84ee-4a16-8d31-40e87bf055de.png)
 Right on your page for this modpack it says to report issues here. 
@ravenbuilder934 Please reopen this, as this is where your pack documentation says to report issues.

**Comment by Raycoms** [comment]
Please report it on discord.

**Comment by RedStoner** [comment]
already is, many many people having this issue here in discord.

**Comment by RedStoner** [comment]
Found solution: 
Launching Curseforge in administrator mode before installing via the install link seems to have solved the issue.

Edit: This does not actually seem to be the fix. Pack forced the 1.16 version

**Comment by RedStoner** [comment]
Fix for this error without using GDLauncher:
-  Download the pack's zip file from curse forge's website
-  Open the zip with 7zip (Windows zip browser will not work here)
-  In the overrides folder, extract the global_data_packs folder to your desktop or a location you can find.
-  Delete the global_data_packs folder in the zip file
-  Use the curse launcher to create a new profile using this modified zip file
-  After installation completes, move the extracted global_data_packs folder into the newly installed pack (easily found using the "Open Folder" option on the packs profile page)
-  Profit

**Comment by RedStoner** [comment]
Datapacks can be distributed as a zip file. I have tested zipping all the data packs and this allows for a clean installation. This allows a bypass for the long path names.
