### ISSUE TITLE
The Brick Extras and Paper Walls will not Craft

### ISSUE THREAD

**Issue by 16Kitsune41** [ldtteam/minecolonies#7625]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.17.1
- MineColonies Version: minecolonies-1.17.1-1.0.23-ALPHA.jar
- Structurize Version: structurize-1.17.1-0.13.239-ALPHA.jar
- Related Mods and their Versions: 
BlockUI: blockui-1.17.1-0.0.26-ALPHA.jar
Domum Ornamentum: domum_ornamentum-1.17.1-1.0.9-ALPHA-universal.jar
Multi-Piston: multi-piston-1.17.1-1.2.1-ALPHA.jar

## Expected behavior

I would be able to craft the extra brick roofs and paper walls. Or find them in the creative menu.

## Actual behavior

There are no extra brick recipes or paper walls in Just Enough Items, even when you try to use the recipe for them, they don't craft, and they can't even be found in the creative menu.

## Steps to reproduce the issue

I don't know. I have reloaded the curseforge Minecraft world that I have over and over but it still hasn't worked. I even made a world without any other mods but the required ones, and it still didn't show.

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
1.17 is a little different and the wiki hasn't been updated yet.  Those blocks are now in Domum Ornamentum rather than Structurize, and instead of the regular crafting table you need to use the new Architects Cutter block to craft them, or use the new tabs in the various crafting huts.

**Comment by 16Kitsune41** [comment]
Ok thank you so much


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
