### ISSUE TITLE
Builder is converting blue brick extra shingles to blue cobblestone extra shingles

### ISSUE THREAD

**Issue by Nikademus** [ldtteam/minecolonies#7626]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.17
- MineColonies Version: minecolonies-1.17.1-1.0.23-ALPHA
- Structurize Version: structurize-1.17.1-0.13.239-ALPHA
- Related Mods and their Versions: domum_ornamentum-1.17.1-1.0.9-ALPHA-universal

## Expected behavior

Builder was upgrading Builder's hut (medieval spruce) from level 2 to 3.  Builder requested blue brick extra shingles (normal and corner ones), and also blue cobblestone extra shingles (both versions).  I gave him the requested amount of each.

## Actual behavior

At some point the builder combined them into the cobblestone versions of the blocks, as he had far too many of the cobblestone version and none of the brick version.   He would then request more brick versions from me.  Sometimes if I cancelled his request from the clipboard, he would place a cobblestone version instead, then go back to requesting the brick version.

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Nikademus** [comment]
Ok, when looking at the requirements before upgrading, you can see it's asking for 16 Blue Cobblestone Extra Shingles
 and 54 Blue Cobblestone Extra Shingles
![2021-10-04_18 48 34](https://user-images.githubusercontent.com/1380028/135935458-0a09e729-ffd8-44da-a6e8-caf1c3b6fadf.png)
![2021-10-04_18 48 39](https://user-images.githubusercontent.com/1380028/135935469-93cfc07e-eae9-4978-8a7d-8fbd3b511998.png)
.
Then, once the upgrade begins, you can see it splits the requirements:
![2021-10-04_18 49 44](https://user-images.githubusercontent.com/1380028/135935500-700ccfd8-cb89-424e-89f5-cbe8f3c2265b.png)

**Comment by Nikademus** [comment]
Once the builder got to the roof, he combined what I gave him
![2021-10-04_19 08 31](https://user-images.githubusercontent.com/1380028/135936590-2649a1db-c98a-48d9-b806-6643b11b5bb2.png)
![2021-10-04_19 10 29](https://user-images.githubusercontent.com/1380028/135936607-368672cc-622e-4149-99e0-775e6161ea59.png)

.

**Comment by Raycoms** [comment]
I did find the issue, will require some structurize changes I believe

**Comment by tecnobrat** [comment]
Is this the same issue as the carpenter making oak paper frames instead of spruce ones, or making cobblestone shingles when its supposed to be making mossy cobblestone ones? It appears to only make the recipe (of that type, shingle, frame, etc) that has the highest priority.

**Comment by Raycoms** [comment]
I believe so, I got some fixes ready to be released soon
