### ISSUE TITLE
Townhall banner UI crashes upon usage

### ISSUE THREAD

**Issue by Rikaeus** [ldtteam/minecolonies#7627]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.17.1
- MineColonies Version: 1.17.1-1.022-ALPHA
- Structurize Version: 1.17.1-0.13.239-ALPHA
- Related Mods and their Versions: the 1.17.1 minecolonies official modpack

## Expected behavior

Being able to go to the first page of the colony banner interface in town hall

## Actual behavior

It crashes the game the second you click the 1 in the colony banner interface

## Steps to reproduce the issue

1.  Open Townhall
2.  Go to the Settings Page
3.  Open the Minecolony Banner interface
4. Press the 1 Button on the interface

### Logs

- latest.log: 
- https://gist.github.com/Rikaeus/44f22760f0d2b92afc6a7bfddc1eb3ee
- crashlog:  https://gist.github.com/Rikaeus/0d07ca0b57088982b67b7fb85fe82c77

### Notes

---

## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Okay. I dug into this deeply, and this took me a while. The armor mod we're having adds broken banner patterns which cause undefined behavior on trying to render them. I reported it to that mod and I'm awaiting a fix or so.
