### ISSUE TITLE
Tavern and Raid Sounds not working

### ISSUE THREAD

**Issue by DSMister** [ldtteam/minecolonies#7629]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-1.0.8-ALPHA-universal.jar
- Structurize Version: structurize-0.13.230-ALPHA-universal.jar

## Problem description

During the night, I cannot hear the tavern music that normally should start playing after all my colonists are tucked in bed. Additionally, after I clear a raid, there is no victory jingle. All other sounds that I remember are in this mod are functional.

### Notes or related things

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by someaddons** [comment]
I've tested them and they are working. Note that the tavern does not play every night, only occasionally when there is visitors around in it. And the Raid ending sound you only hear while you're within the colonies claimed area
