### ISSUE TITLE
Request: LJ GUI Sapling Selector. [$5 awarded]

### ISSUE THREAD

**Issue by Wissi** [ldtteam/minecolonies#763]
I think that a pg. 2 in the LJ block GUI is needed. 
Where the player can select what type of tree(s) the LJ should work on. Leaving all other type of tree(s)/saplings alone.

Maybe an interface like Pg. 2 Permissions Tab in TH GUI? Where there is an ON/OFF for each permission.

With a list of trees/saplings (including other mod trees - like slime trees) where the player con "select" (turn ON/OFF) which type LJ will work on.

**Comment by AndrewTru** [comment]
I think this will help, the minecraft trees are not an issue but the modded ones seems to be a issue.
The thing here is that this sounds like an API pull request, and a lot of the mods add trees may not have a Trees API yet. I am backing the idea, just have to play the cards in just the right way.

**Comment by marvin-bitterlich** [comment]
With @OrionDevelopment request and api systems we schould be able to get that list

**Comment by AndrewTru** [comment]
let's just hope they are cool with it, this may work well with a system to select the type of wood that can be used for building the buildings, This is more for the rubber trees and other wood that may not be as pleasing to the eyes and depends on the user and the APIs we can get access to as well.

**Comment by Wissi** [comment]
I think this portion of the LJ is working fine now. This issue should be closed? Lumberjack has issues still, but "sapling Selector" done and working. Close issue?
