### ISSUE TITLE
Cannot research anything requiring house hut levels

### ISSUE THREAD

**Issue by Rikaeus** [ldtteam/minecolonies#7630]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.17.1
- MineColonies Version: 1.17.1-1.0.22-ALPHA
- Structurize Version: 1.17.1-0.13.239-ALPHA
- Related Mods and their Versions: Minecolonies Official 1.17 modpack

## Expected behavior

Being able to research things that need house levels as a pre-req.
## Actual behavior

Research is still red'ed out, and the description of the house hut block is instead block.minecolonies.blockhuthome(s)

![Minecolonies issue](https://user-images.githubusercontent.com/31223289/136270512-8d4f6ab5-ccdd-46c7-b578-67498dd9138f.png)
## Steps to reproduce the issue

1.  Open up University Research Interface
2.  Try to research something that needs house hut level
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
fixed
