### ISSUE TITLE
[1.17.1] Unable to install official minecolonies modpack

### ISSUE THREAD

**Issue by Hallite** [ldtteam/minecolonies#7633]
### Prerequisites 

- [ ] I am running the latest **beta** version of MineColonies and Structurize for my Minecraft version. 
(I can't check as it doesn't install so not sure it applies)
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.17.1
- MineColonies Version: file name just says mc1.17.zip
- Structurize Version: unknown (can't check)

## Problem description

When I try to install the pack from the curseforge app it doesn't fully install then cancels giving me a "could not find a part of the path" error
### Notes or related things

XTrying to download mc 1.16.5 minecolonies V3.4 does work but trying to update from that to mc 1.17.1 for minecolonies gets stuck at 33% then cancels and puts me back at the mc 1.16.5 minecolonies V3.4.
Sorry if this isn't worded well or if I am missing/adding things i don't need to as this is my first time using github for anything. 
(I'm not sure why this is in bold I didn't make it bold it just is) 
---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation
![Screenshot 2021-10-07 090217](https://user-images.githubusercontent.com/70004184/136424114-686f76ee-b6c4-4d92-9093-f3d8d5789198.png)

**Comment by Raycoms** [comment]
Please report this a) On discord, this github is for the mod not the modpack b) Report it to curselauncher as this is a bug on their side and c) On discord people can tell you ways on how to deal with this.

**Comment by Hallite** [comment]
> 
> 
> Please report this a) On discord, this github is for the mod not the modpack

I just realized this isn't specifically for the mod that's why i changed the title though you already got that covered thanks for the quick reply

**Comment by RedStoner** [comment]
See my reply on original report for a fix - https://github.com/ldtteam/minecolonies/issues/7623#issuecomment-938115068
