### ISSUE TITLE
Help The game crashed whilst unexpected error Error

### ISSUE THREAD

**Issue by lluviamagenta** [ldtteam/minecolonies#7636]
I have uninstalled both both minecraft and cured forge, and I keep crashing as soon as I enter the server. The error is on my side since the owner of the server and other players can log in without an issue.  

attached is the log of the crash
[New Text Document.txt](https://github.com/ldtteam/PerViamInvenire/files/6327594/New.Text.Document.txt)

 Any help is appreciated!

**Comment by ravenbuilder934** [comment]
Please update to the latest alpha, you're several months out of date (based on when the issue was created) and it's likely this has been fixed by now
