### ISSUE TITLE
the game crash when recall a Courier and at the same time the Courier is far away from his hut

### ISSUE THREAD

**Issue by gaiteli** [ldtteam/minecolonies#7637]
when I recall a Courier and at the same time the Courier is far away from his hut, the game crash. I don't know exactly the distance needed to make this possible. This is not by chance, because I have tried it for three times.

I wish the coder could repair this fatal bug as soon as possible, very thanks! 
I like this mod very much. Wish a better MineColonies! Wish a better Minecraft!!!

**version: 1.16.5-1.0.0-RELEASE**

[错误报告-2021-10-9_20.54.45.zip](https://github.com/ldtteam/minecolonies/files/7315645/-2021-10-9_20.54.45.zip)

**Comment by Raycoms** [comment]
Please fill in the template and upload the log as a gist.
