### ISSUE TITLE
Courier AI ran into a problem

### ISSUE THREAD

**Issue by EmmiPigen** [ldtteam/minecolonies#7638]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.645

### Logs

- latest.log: https://gist.github.com/EmmiPigen/fb25478b15d4e8b3bde44ffd933cef76

## Steps to reproduce the issue / details

 
I don't know exactly what caused the issue. but the last things i did was create a build request for a house, and use the the stash and postbox

Just reporting the AI issue. 

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Fixed in 1.16.5 - 1.15 is out of support already. Sorry
