### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Froeschli1** [ldtteam/minecolonies#7641]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- MineColonies Version:

### Logs

- latest.log: 

## Steps to reproduce the issue / details

Just reporting the AI issue. 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

Here is the link : https://gist.github.com/Froeschli1/cd1dd8e609bf21e85f18ba8d7673a694

**Comment by Raycoms** [comment]
Please fill in the entire template, else we won't be able to situate it accordingly.
