### ISSUE TITLE
AI Issue

### ISSUE THREAD

**Issue by Froeschli1** [ldtteam/minecolonies#7642]
### Prerequisites 

- [no ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [ yes] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 1.17.1

Minecraft version : 1.17.1
- MineColonies Version:minecolonies-1.17.1-1.0.27-ALPHA.jar

### Logs

- latest.log: 

## Steps to reproduce the issue / details

 No , but the AI noticed the Issue

Just reporting the AI issue. 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Froeschli1** [comment]
Oof i forgot to add the latest.log , but here is the link https://gist.github.com/Froeschli1/9a6bfb46949489824af01b972d31e3cc

**Comment by Raycoms** [comment]
Which worker, and what are they doing atm?

**Comment by Froeschli1** [comment]
Builder , i gave the builder the request to build a building (i dont know anymore which it was) and then accidently deleted the building

**Comment by Froeschli1** [comment]
seems like rejoining fixes the issue.
