### ISSUE TITLE
Guard's taunting mobs research doesn't always work.

### ISSUE THREAD

**Issue by warning-djkajslh** [ldtteam/minecolonies#7644]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- MineColonies Version:
- Structurize Version:
- Related Mods and their Versions:

## Expected behavior

The mob will priority the guards above all else.

## Steps to reproduce the issue

1. Unlock the research
2. Have a horde of zombies targeting you
3. Wait for your guards to come
4. Now watch as the horde keep on hitting you

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Taunt means that on hit of the guard, the mob will target the guard, and not just all mobs around.
