### ISSUE TITLE
Hair on citizen is floating

### ISSUE THREAD

**Issue by tecnobrat** [ldtteam/minecolonies#7645]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.17.1
- MineColonies Version: minecolonies-1.17.1-1.0.30-ALPHA
- Structurize Version: structurize-1.17.1-0.13.243-ALPHA
- Related Mods and their Versions: domum_ornamentum-1.17.1-1.0.10-ALPHA-universal

## Expected behavior

The hair would be attached to the model, not floating.

## Actual behavior

The hair model is floating.

## Steps to reproduce the issue

1. Unfortunately I found the citizen like this -- I have no idea how to reproduce it.

### Logs

- latest.log: 
- crashlog: 

### Notes

I am *NOT* using optifine

![2021-10-10_09 28 04](https://user-images.githubusercontent.com/145406/136707364-03255bd6-66cc-455c-8adc-68e5c32b2c02.png)
![2021-10-10_09 28 13](https://user-images.githubusercontent.com/145406/136707366-42935a0f-b6c7-441a-a4aa-a9328d8f211e.png)
![2021-10-10_09 31 03](https://user-images.githubusercontent.com/145406/136707367-070ab05d-f381-4c10-b0a5-5357bf4bee64.png)
![2021-10-10_09 31 09](https://user-images.githubusercontent.com/145406/136707368-30cde78e-d49e-48f4-a567-7f3a2995ebe8.png)

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
do you have optifine installed?

**Comment by uecasm** [comment]
They said not.  And I can confirm that this happens to me as well, only in 1.17.  And with no additional mods (just JEI and the dependencies).  Doesn't affect all colonists, just some of them.
