### ISSUE TITLE
Guards don't immediately pick up armor from their tower

### ISSUE THREAD

**Issue by warning-djkajslh** [ldtteam/minecolonies#7647]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- MineColonies Version:
- Structurize Version:
- Related Mods and their Versions:

## Expected behavior
 The poorly equipped guard will want to head to their tower to get the armor as fast as they can to armor themselves.

## Actual behavior

They take their sweet time, seriously, for them to do that you will have to manually call them to their tower and sometimes give them the armor yourself.

## Steps to reproduce the issue

1. Have an armorless guard
2. Wait for him to strays far away then put some armor pieces in the tower's inventory
3. See how long it will take for them to notice and return there to get the armor.
### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
on purpose
