### ISSUE TITLE
Citizens cramped in the restaurants

### ISSUE THREAD

**Issue by warning-djkajslh** [ldtteam/minecolonies#7648]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- MineColonies Version:
- Structurize Version:
- Related Mods and their Versions:

## Expected behavior

Everytime a citizen is hungry and visit the restaurant, they would check to see if there are any available "sit" there are, and proceed to sit down waiting.
If there is a citizen leaves their sit, another citizen will notice that and take the sit.

## Actual behavior

Literally none of them sit at all, even when there are numerous sits available (Observed in Nordic, Wooden and Stone styles), at times I would see the restaurant's kitchen became a mosh pit as people waiting for foods from the cook, never in my gameplay have I actually see any of them sit down.

## Steps to reproduce the issue

1. Open up a L5 restaurant, preferrably Nordic as there are sits there.
2. Have hungry citizens come flooding the restaurant
3. Wait for one of them to sit down.

### Logs

- latest.log: 
- crashlog: 

### Notes

If you aren't manage to replicate this and it worked fine for you, then please post a few pics of citizens using their sits in the restaurant, I am also wanting to see it.
Here is a demonstrating video, you can see that beside not taking the sit, the citizens also clogged up the restaurant, making it impossible to even access the structure block, proving that not only the standing issue need to be fixed, but the crowding issue also.
https://youtu.be/ms276vMMGGo?t=532 

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
Please fill in the versions.  I know that this does work as expected in some versions.

**Comment by warning-djkajslh** [comment]
I was playing on 1.16.5 with minecolonies-1.0.8-ALPHA-universal.jar, not really on 1.17 as there are not an abundant of mods as of now.

**Comment by Raycoms** [comment]
Only styles that are tagged they sit #5006

**Comment by warning-djkajslh** [comment]
> Only styles that are tagged they sit #5006

So it seems, what styles is it that ultilize this mechanic? Can I create my own custom restaurant schematic that contain it's "sit"?

**Comment by warning-djkajslh** [comment]
Should I make another thread because some structures doesn't use this mechanic, in the wooden style there are clearly stairs for sitting yet no actual sitting can be found.

**Comment by MotionlessTrain** [comment]
As Raycoms already mentioned, those issues should be added to the schematic issues thread (#5006)
