### ISSUE TITLE
Citizens don't feel like moving to their racks to get the items

### ISSUE THREAD

**Issue by warning-djkajslh** [ldtteam/minecolonies#7649]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- MineColonies Version:
- Structurize Version:
- Related Mods and their Versions:

## Expected behavior

Everytime a citizen want to take out an item which is on their rack, they would move to access the rack to get/deposit the item.

## Actual behavior

They would just get it from the main structure block, a normal behavior in the warehouse, where couriers would all gather around the warehouse but not the racks.

## Steps to reproduce the issue

1. Open a L5 warehouse in a colony
2. Observe the 10 couriers

### Logs

- latest.log: 
- crashlog: 

### Notes

In this issue I only cover taking items out, but I would like to mention that it is the same for deposting items, I know that the item(s) get automatically put in one of the racks, but the citizens doesn't show me which rack did they deposited is quite confusing, plus it breaks the immersion.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Please make this a feature request
