### ISSUE TITLE
Whiter/creeper does not explode near town hall (120 aprox blocks radius)

### ISSUE THREAD

**Issue by jonabrv1965** [ldtteam/minecolonies#765]
### Minecolonies version

version minecolonies-universal-1.10.2-0.6.3317

### Expected behavior

- XXX

### Actual behaviour

- YYY

### Steps to reproduce the problem

I'm trying to create a nether star farm in the bowels of my base, and realize that the wither, once spawn make all the flashing thing before explode, but it does not explode at all... Same happen with creepers...

Additionally I detected that the autoplacer and autobreaker blocks from actually additions mod does not work either.

Trying to find out what happened I concluded that nearby the town hall this is happening. If I move away from it about 120 blocks (radius), everything works as expected (the blocks and the explosions)

1. XYZ
2. ZYX
3. ...
4. Profit

**Comment by Raycoms** [comment]
You are playing on a server? Which server? You have disable anti griefing
to allow explosions and auto block breakers.

2017-04-05 14:24 GMT-03:00 jonabrv1965 <notifications@github.com>:

**Comment by jonabrv1965** [comment]
Ah forgot to mention, debugging this I removed the minecolonies mod and load the world, and in the very same spot where this happened does not happen any longer... But I love my colony and need them... so as a workaround I move my wither farm away from my base meanwhile...

**Comment by xavierh** [comment]
You can disable this in the minecolonies configuration file

**Comment by jonabrv1965** [comment]
Oh I see. I'll disable this in the config. THX!!

**Comment by jonabrv1965** [comment]
Ah, Singleplayer, my own laptop :-)
