### ISSUE TITLE
Architecture block crafting, faill, sawmill

### ISSUE THREAD

**Issue by Wetz1990** [ldtteam/minecolonies#7651]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.17.1
- MineColonies Version: minecolonies-1.17.1-1.2.1-ALPHA
- Structurize Version: structurize-1.17.1-0.13.243-ALPHA
- Related Mods and their Versions: domum_ornamentum-1.17.1-1.0.10-ALPHA-universal

## Expected behavior
Crafter being able to craft the DOM blocks.

## Actual behavior
This is only related to the sawmill.
The builder is requesting the "Framed oak plank". The request is being send to the sawmill. The request shows up in the sawmills task list. The task disapears after a few seconds of being displayed, before reappearing.

## Steps to reproduce the issue

     1. Sawmill level 3,
     2. Builder level 4.
     3. Builder trying to build the Frontier University level 4.
     4. Teach the sawmill the neede recipies.
     5. and wait for the request to not be fulfilled.
     6. I experienced the same thing when building the builder level 4.

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Fixed in upcoming
