### ISSUE TITLE
Guards not responding to other guards being attacked.

### ISSUE THREAD

**Issue by Wetz1990** [ldtteam/minecolonies#7652]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.17.1
- MineColonies Version: minecolonies-1.17.1-1.2.1-ALPHA
- Structurize Version: structurize-1.17.1-0.13.243-ALPHA
- Related Mods and their Versions: domum_ornamentum-1.17.1-1.0.10-ALPHA-universal

## Expected behavior
When a guard engages in combat with a mob (barbarian), the guard would call for help from other nearby guards.
Just like when a citizen is being attacked by a mob, guards come running. This does not happen when a guard takes damage. Other guards will leave him be till they randomly get close enough to detect the mob themself.

## Actual behavior
Guard enganges mob. He takes damage.
He is left fending for himself.

## Steps to reproduce the issue
1. Build two or more guard towers
2. have one guard fight a mob
3. see him not getting any help
4. spawn a citizen
5. have it be attacked by mob
6. see citizen get help

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
What is the distance of the two guards?

**Comment by Wetz1990** [comment]
As far as I have observed, any and all distances.
It is only when the "other" guard detect the mob themselves they will engage.
Have seen some walk past within 10 blocks not helping another guard.

**Comment by Wetz1990** [comment]
![2021-10-11_21 22 07](https://user-images.githubusercontent.com/33292786/136861254-4f4e50cf-a8d6-475c-a8eb-ad80dfef37fc.png)
stupid potion effect. But in this picture you can see a guard going to the left, when a bunch of other guards are engagne in battle straigh ahead.
