### ISSUE TITLE
Stonemason can't craft "Brick extra"

### ISSUE THREAD

**Issue by Wetz1990** [ldtteam/minecolonies#7654]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- MineColonies Version: minecolonies-1.17.1-1.2.1-ALPHA
- Structurize Version: structurize-1.17.1-0.13.243-ALPHA
- Related Mods and their Versions: domum_ornamentum-1.17.1-1.0.10-ALPHA-universal

## Expected behavior
The stonemason should be able to craft the "brick extra. 
He is able to craft all the other pure stone variant blocks, and the dyer can craft the colored versions.

## Actual behavior
When trying to teach the stonemason the "brick extra" recipie the can not learn it. JEI does not suggest any MC crafter who can learn it.
![image](https://user-images.githubusercontent.com/33292786/136760494-4b47807a-de69-4757-8a1e-9ddb49f83b45.png)
![image](https://user-images.githubusercontent.com/33292786/136760577-a14adb67-fd69-4a28-bbd5-a7efc6e6291e.png)

## Steps to reproduce the issue
1. Try to teach stonemason "brick extra" recipie.

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by tecnobrat** [comment]
Same appears to happen for Paper Extra with the Plantation.
