### ISSUE TITLE
Forester does not work properly with nether trees

### ISSUE THREAD

**Issue by Wetz1990** [ldtteam/minecolonies#7657]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- MineColonies Version: minecolonies-1.17.1-1.2.1-ALPHA
- Structurize Version: structurize-1.17.1-0.13.243-ALPHA
- Related Mods and their Versions: domum_ornamentum-1.17.1-1.0.10-ALPHA-universal

## Expected behavior
Forrester will chop down Warped trees, and replant fungi.

## Actual behavior
They do not. Mostly.
I had one instance where a forrester took down a warped tree, destroyed a few of the "leaves", and then went back to his hut without replanting.
But mostly the two forrester I have just stand and "look for tree" even tho there are two warped trees within range.

![2021-10-12_00 13 55](https://user-images.githubusercontent.com/33292786/136862114-f5d9c1b2-b763-4375-974e-d1b7337cdcc3.png)

## Steps to reproduce the issue

1. Be in overworld
2. Plant assortment of trees
3. include warped fungi in the mix.
4. Bonemeal the fungi to make it grow.
5. watch how the forester will, 95% of the time not chop down the tree.

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Number of questions: 
a) Do those warped tree have the leaves connected to the top most stem?
b) Did the forester have the necessary shrooms for replanting?

**Comment by Wetz1990** [comment]
a) yes
b) yes
![2021-10-12_00 36 52](https://user-images.githubusercontent.com/33292786/136863399-000aa0fe-cc6c-4de8-aed4-af04ccdf8a2d.png)
The forrester decided to remove all the "leaves" and leave the logs

**Comment by Wetz1990** [comment]
The warped fungus does also not appear on the "samplings" list 
I assume this is why he deposited all the fungus in the rack when he returned form o dump his inventory.

![2021-10-12_00 38 15](https://user-images.githubusercontent.com/33292786/136863464-afbd988e-befe-4dd8-a329-2d37a9b5b191.png)

**Comment by Wetz1990** [comment]
He returned and took down the logs after a while.
But no replanting.

**Comment by Wetz1990** [comment]
Somwhow it started working.
He replanted this time, so the cycle is complete.
However, he may not replant if the ground he is about to plant on is not a warped nylium block, and just a normal netherrack block.
