### ISSUE TITLE
[Suggestion] 'Dump Chest' inside Warehouse / Chest to ship Items to the Warehouse

### ISSUE THREAD

**Issue by SulpherStaer** [ldtteam/minecolonies#766]
### Minecolonies version

version 1.11-0.6.3282

### Expected behavior

- Be able to, as a player, place items inside the warehouse and have the npc's sort them in the chests according to their sorting system. It is too confusing as a player to know what they want to put where.
Or have a large chest available for the delivery people to sort things into the warehouse.

### Actual behaviour

- Put things in a chest, and look at the unsorted mess. And cause a mess-up in the NPC sorting system.

### Steps to reproduce the problem

1. Build a colony
2. Build a warehouse and delivery person
3. Observe messy 'sorting' system when players put items into the chests in the warehouse.

**Comment by Raycoms** [comment]
You can place them in the chest of the deliveryman or in the citizen huts.
They will pick it eventually up and sort it.
