### ISSUE TITLE
forester not finding trees that are in a lower y coordinate than the hut

### ISSUE THREAD

**Issue by Hallite** [ldtteam/minecolonies#7661]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.17.1
- MineColonies Version: minecolonies-1.17.1-1.0.42-ALPHA.jar
- Structurize Version: structurize-1.17.1-0.13.253-ALPHA.jar
- Related Mods and their Versions: 

## Expected behavior

find and mines trees within his range regardless of y level
## Actual behavior

he sits at hut block with trees one y level lower than the hut saying he cant find trees, planting a tree at hut y level near by sets him into action and he nabs it

![2021-10-12_13 54 44](https://user-images.githubusercontent.com/70004184/137029898-0563410d-875c-48bb-8f13-4148db6b0407.png)
## Steps to reproduce the issue

1.  place forester hut one y level above trees y level
2.  i had some trees at the same y level he went to first not sure if its a factor but they where there
3.  he got the trees at his y level then instead of getting the other trees he just sat at the hut and said he couldnt find any

### Logs

- latest.log: 
[latest.log](https://gist.github.com/Hallite/623f94149a1c8e1818a9a6df247c53db)

- crashlog:  no crash log

### Notes

planting treas yourself on the same y level as the hut puts him to work but he continues to ignore lower y level ones after finishing
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
fixed
