### ISSUE TITLE
crash when clicking build options

### ISSUE THREAD

**Issue by aleph-infinity** [ldtteam/minecolonies#7662]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 1.0.8 alpha
- Structurize Version: 0.13.230 alpha
- Related Mods and their Versions:

## Expected behavior

see the build options menu

## Actual behavior

game crashes out: The game crashed whilst mouseclicked event handler
Error: java.lang.NullPointerException: mouseClicked event handler
Exit Code: -1

## Steps to reproduce the issue

1.  place building
2.  click build options
3.  game crashes

### Logs

- latest.log: https://gist.github.com/aleph-infinity/4aa19e9a7ac8c5c69dd7607c6d60a8ed
- crashlog: https://gist.github.com/aleph-infinity/a06055fa4b56d1ff56cf5403e5cbf9b9

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
reopen if still an issue. Shouldn't be an issue anymore

**Comment by SpaceCandy** [comment]
It is still an issue..

[crash-2022-01-24_22.20.41-client.txt](https://github.com/ldtteam/minecolonies/files/7928984/crash-2022-01-24_22.20.41-client.txt)

**Comment by uecasm** [comment]
You're running minecolonies-1.18.1-1.0.278-RELEASE.  Update to the latest alpha instead.
