### ISSUE TITLE
Visitors will not accept enchanted books when they request them

### ISSUE THREAD

**Issue by ncottrill** [ldtteam/minecolonies#7667]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.17.1 
- MineColonies Version: minecolonies-1.17.1-1.0.42-ALPHA
- Structurize Version: structurize-1.17.1-0.13.253-ALPHA
- Related Mods and their Versions: 

## Expected behavior
 I would expect that the visitors would accept enchanted books. I have the correct number of books in my player inventory. I click the bottom button requesting x number of enchanted books, but visitor does not accept. 

## Actual behavior

The visitors walk away without accepting enchanted books when I click on the button that should accept the books.

## Steps to reproduce the issue

1.  Have requested enchanted books in inventory
2.  Go up to visitor and click bottom button
3.  Nothing. The visitor does not accept the book and walks away.

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Fix pushed
