### ISSUE TITLE
Courier Issue

### ISSUE THREAD

**Issue by Mtank023** [ldtteam/minecolonies#7668]
Tried to write this in the forms but you banned the form as spam, not really spam when I am trying to get help....

Built a dwarven area so we have the main floor and a subfloor about 40 blocks down. We built a stairway to connect the two, and the issue is the courier just stands over the miner as opposed to using the stairway. Tried adding waypoints on the stairs, but they don't use it still. Any help on what I 
am doing wrong?
![Courier](https://user-images.githubusercontent.com/89362890/137508571-06509fd0-9f7c-4519-b79c-ed912cb8eb04.png)

**Comment by Raycoms** [comment]
Please fill in the complete template and give us a colony export.
