### ISSUE TITLE
Courier Issue

### ISSUE THREAD

**Issue by Mtank023** [ldtteam/minecolonies#7669]
### Prerequisites 

- [ X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-1.0.53-ALPHA-universal.jar

### Logs

- latest.log:  
- https://gist.github.com/Mtank023/0011c38354298b13ed4c9e26f71ecfe4

## Steps to reproduce the issue / details

Have a large mountain, and create a warehouse on top of the mountain. Go around the mountain and shear it so there are 4 block drops so the courier won't try to jump down. Build a stairway down to the main level, 40 blocks deep, and then build a miner. Valley next to the mountain that is also 40 blocks deep, build a forestry area. Build tunnels that connect the mine to the stairway and another tunnel that leads outside the mountain for a house, guard tower, and about 50 -60 blocks south is the forestry building. This is where both my couriers will no longer work. One will stand over the mine on the main level, and the other will run to the edge of the mountain and just stare at the forestry area. 

The stairway is L shape all the way down, so multiple small three-block levels that lead to other stairways. six in total. I've placed waypoints down the stairway, they will go down two sets of stairs, and then go back up. 

The overall stairway is nine by nine wide. 

Just reporting the AI issue. 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Can we get a colony export?

**Comment by Mtank023** [comment]
How do I give you that? Mean a copy of the world?

**Comment by Raycoms** [comment]
./mc colony export

**Comment by Mtank023** [comment]
Keeps giving me a unknown or incomplete command, see below for error
...ony export <--[HERE]

**Comment by Raycoms** [comment]
(needs the colony id after that)

**Comment by Mtank023** [comment]
Where shall I attach it? I keep trying to attach it to this message but it is giving a message of is not included in the list.

**Comment by Raycoms** [comment]
drive or so

**Comment by Mtank023** [comment]
Where? Can't attach it to this form, and can't use the https://gist.github.com/Mtank023/0011c38354298b13ed4c9e26f71ecfe4 either.

**Comment by Mtank023** [comment]
Closed by mistake.

**Comment by Raycoms** [comment]
just post the drive link of the download here

**Comment by Mtank023** [comment]
https://drive.google.com/file/d/1-kYyZ5mhxEeafvyQa0uyGd1Pk2X6ZVB3/view?usp=sharing

Not sure where else to put it, so here you.

**Comment by KKomrade** [comment]
I used to have this issue a while ago, and what seemed to happen is that if the Courier has to travel down a considerable Y amount, they will just stand on the X/Z position of the hut block and do nothing, seemingly incapable of pathing. Hope this helps at all.

**Comment by Raycoms** [comment]
Sorry for the delay, I can't open the world in dev because it has too many mods/special datapacks in it. Would you be able to reproduce this otherwise, maybe in a fresh world with only minecolonies?

**Comment by Raycoms** [comment]
Stale issue
