### ISSUE TITLE
Deliverymen need to learn to count.

### ISSUE THREAD

**Issue by SulpherStaer** [ldtteam/minecolonies#767]
### Minecolonies version

version 1.11-0.6.3282

### Expected behavior

- A builder requests 3 beds. There are 16 available in the warehouse. A deliverymen takes 3 beds out of the warehouse, and delivers it to the builders hut.

### Actual behaviour

- A builder requests 3 beds. There are 16 available in the warehouse. A deliveryman takes the whole stack out of the warehouse, and delivers it to the builder, who then claims the whole stack for himself. A secondary builder requesting beds, will shout it out, because there are none more available in the warehouse, having me chase around to see where the beds went.

### Steps to reproduce the problem

1. Build a colony.
2. Build a warehouse and delivery person.
3. Build a secondary builder.
4. Construct two buildings with a specific traceable item, such as beds, or polished material, and have only up to 1 stack available of the materials, but in surplus of the required amount.
5. Notice that the first builder that requests said material, gets the entire stack of material, instead of only the X amount he requested.

**Comment by SulpherStaer** [comment]
... nevermind. It only happens when you gave yourself a stack of items that normally doesn't stack, and put that inside the warehouse. I was a dumb.

**Comment by Raycoms** [comment]
Yeah atm he just takes a stack of any item.
This will be improved in the future
