### ISSUE TITLE
Archer and Knight in training doesn't use the bed in their schematic

### ISSUE THREAD

**Issue by warning-djkajslh** [ldtteam/minecolonies#7670]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- MineColonies Version:
- Structurize Version:
- Related Mods and their Versions:

## Expected behavior

Guards in training facility will sleep in the bed at night

## Actual behavior

The don't and just go stand at the structure block at night.

## Steps to reproduce the issue

1. Open up a training schematic
2. Hire some guards, provide what is needed and wait till night time.
3. Observe

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
Could you fill in the version information?

Try using the “repair” option on the academies. After that, they should recognise their bed again

**Comment by warning-djkajslh** [comment]
Worked
