### ISSUE TITLE
Miner not using max world depth

### ISSUE THREAD

**Issue by Wetz1990** [ldtteam/minecolonies#7671]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.17.1
- MineColonies Version: minecolonies-1.17.1-1.2.1-ALPHA
- Structurize Version: structurize-1.17.1-0.13.243-ALPHA
- Related Mods and their Versions: domum_ornamentum-1.17.1-1.0.10-ALPHA-universal

## Expected behavior
Miner would dig a shaft till they hit bedrock (below zero now)

## Actual behavior
With the world generating below zero now, they stop at the old world limits around Y5-6, and will not go deeper.

## Steps to reproduce the issue

1. Have world generate with 1.18 world generation
2. Build a miner and level the miner up to/past level 3
3. Watch them not dig below Y0

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
fixed
