### ISSUE TITLE
Higher Learning cannot be researched

### ISSUE THREAD

**Issue by krjencik** [ldtteam/minecolonies#7676]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.17.1
- MineColonies Version: 1.0.56
- Structurize Version: 0.13.253
- Related Mods and their Versions:

## Expected behavior

being able to start this research
## Actual behavior

it says in red "requires com.minecolonies.coremod.gui.workerhuts.citizen(s)"

![2021-10-16_20 28 17](https://user-images.githubusercontent.com/92643141/137598407-3fd8fd65-da99-44a7-a376-13006c3ec9d4.png)
## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

i already have 4 houses lvl 2 and 2 lvl 1 + one is currently under construction
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by krjencik** [comment]
my first issue

**Comment by Mr-Robby** [comment]
I have the same issue, but I've built 5 houses and all of them 3 lvl

**Comment by Raycoms** [comment]
fix pushed
