### ISSUE TITLE
Ticking entity/pathfinding crash

### ISSUE THREAD

**Issue by Moobien** [ldtteam/minecolonies#7679]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.17.1
- MineColonies Version: 1.0.56
- Structurize Version: 0.13.256
- Related Mods and their Versions: 

## Actual behavior

updated to 56 and started getting this crash, rolled back to 55 and the game played as before with no issue. @MotionlessTrain suspects ladder fix.

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: https://gist.github.com/Moobien/b0756b2de8c966c0d532a5a8f5ed9cb7
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
sokved
