### ISSUE TITLE
Deliveryman doesn't leave fences for miner

### ISSUE THREAD

**Issue by SulpherStaer** [ldtteam/minecolonies#768]
### Minecolonies version

version 1.11-0.6.3282

### Expected behavior

- The miner requests enough oak fence for either 1 mine support beam (4), or enough for 1 depth level balistrade. (16)

alternate

- The miner requests 1 full stack of oak fence, in the same way he requires 1 full stack of cobble, 1 full stack of oak planks, and 1 full stack of torches after the initial shaft is completed, and he begins branching.
- The deliverymen leave behind 1 full stack of oak fences, in the same way they leave 1 full stack of cobble, torches, and planks.

### Actual behaviour

- The miner asks "I need 1 Oak Fence" every few moments when he isn't given a stack of them.
- Deliverymen do not leave behind oak fences in the miner chest, and only supply them on request.

### Steps to reproduce the problem

1. Build a colony
2. Build a mine
3. Build a warehouse & deliveryman
3. Have 1 oak fence in the warehouse, as requested.
4. See the miner asking for more oak fence not a moment later once he has received his initial request.

**Comment by Wissi** [comment]
Well it's pretty hard to determine how much he will be needing since he requires a lot of them all the time. So changing the number of fences he's asking for to 4/8/16/32/64 wouldn't help much anyways. It would only make him ask less frequently.

The best option (when he has done building the horizontal shaft) is to always give him a stack of fences, a stack of torches, a stack of planks and make sure he has at least a stack of cobble as well. An extra pick and shovel (if they are vanilla ones) IMO.

**Comment by SulpherStaer** [comment]
The fences sadly aren't in his standard kit the delivery people put in his chest (at level 5), where 1 full stack of torches, 1 full stack of cobblestone, and 1 full stack of oak planks is.

I'll alter my bug report, taking in your comment to account.

**Comment by Wissi** [comment]
So the Deliveryman (level 5) will only give him 1 fence when he asks for 1 fence, etc?
If so, then that is a bug that needs to be fixed to ensure that the Miner always asks for 1 stack when he needs any of these materials.

**Comment by Raycoms** [comment]
No the deliveryman will give one stack.

2017-04-07 13:19 GMT-03:00 Wissi <notifications@github.com>:

**Comment by SulpherStaer** [comment]
No. Delivery man will give 1 stack. I mean to say that the delivery men, at level 5, pre-allocate the miner resources. Instead of pulling everything out of the chest, they give 1 stack of oak planks, 1 stack of torches, and leave or give 1 stack of cobblestone. I think 1 stack of fences should be added to that.

**Comment by Raycoms** [comment]
he doesn't leave fences?

Can you then rename the issue to "Deliveryman doesn't leave fences" I will
fix that soon then.

2017-04-07 13:21 GMT-03:00 sylcai <notifications@github.com>:

**Comment by Wissi** [comment]
Yes, there is an Issue currently addressed to this exact thing: issue #642

**Comment by Wissi** [comment]
No Rays, D-man will remove "everything" from workers chests, even tools  that the worker leaves there.

**Comment by Raycoms** [comment]
Yeah but #642 is something we'll really need time for. Fixing that he needs
to leave fences there is a 1 line fix.

2017-04-07 13:23 GMT-03:00 Wissi <notifications@github.com>:

**Comment by Raycoms** [comment]
He removes everything from any worker atm?
He is supposed to leave a certain amount of items there as defined in code.

2017-04-07 13:24 GMT-03:00 Wissi <notifications@github.com>:

**Comment by Raycoms** [comment]
Besides builder. He will take everything the builder isn't currently
needing for the current building.

2017-04-07 13:25 GMT-03:00 Ray Neiheiser <ray.neiheiser@gmail.com>:

**Comment by SulpherStaer** [comment]
I do not know. I did not test to see if delivery men remove tools as well. I do not think so, as my miner has not complained about picks or other tools. Only fences. Maybe its my fault, as I don't have many in the warehouse.

**Comment by Wissi** [comment]
I fired the D-man a while ago due to that issue and chest issues at warehouse. Was waiting for a general D-man fix w/all workers to hire another one. Too annoying to have to run around doing it myself and then have D-man take things anyways...   

And then having a really hard time finding anything in the warehouse..   xD

**Comment by SulpherStaer** [comment]
I have 6 deliverymen, all at level 5. No more waiting. Deliverymen can only carry very little stacks. at level 1, 1, 2 at level 2, 4 at level 3, 8 at level 4, and a full inventory at level 5.

So, level 5 deliveryman are WAY better, and extremely efficient.

**Comment by marvin-bitterlich** [comment]
Is this still relevant?

**Comment by SulpherStaer** [comment]
I am not sure. I can't test it, because the 1.11 client isn't updated.

**Comment by marvin-bitterlich** [comment]
closing for now
