### ISSUE TITLE
Citizens still go to sleep even without a bed in their house

### ISSUE THREAD

**Issue by warning-djkajslh** [ldtteam/minecolonies#7686]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-1.0.66-ALPHA-universal.jar
- Structurize Version:Structurize Version: 0.13.252-ALPHA
- Related Mods and their Versions:Ice and fire 2.1.9

## Expected behavior

They would complain about there is no bed for them to lay down and refuse to go to sleep. They will go to the house block, but would stand there and complain.

## Actual behavior

Citizens just stand and sleep around the house block.

## Steps to reproduce the issue

1. spawn a L5 house in Creative, have citizens move in
2. Destroy the bed
3. set it to night and observe.

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
They only complain if they've been unable to sleep for three consecutive days.  So try running longer in this state and see if they complain then.

**Comment by warning-djkajslh** [comment]
No they don't complain even after 3 days

**Comment by Raycoms** [comment]
That's intended actually.

**Comment by warning-djkajslh** [comment]
Oh...
