### ISSUE TITLE
Shrodinger's Bottom Door

### ISSUE THREAD

**Issue by Moobien** [ldtteam/minecolonies#7688]
DO: domum_ornamentum-1.17.1-1.0.10-ALPHA-universal

When upgrading a Frontier lvl 1 house to lvl 2 the bottom half of the wool door becomes both there and not there at the same time. 

https://imgur.com/XlLBJSl

When the top half is closed it obviously blocks the player, but when it is open the player cannot pass as though they are hitting an invisible barrier. I have also seen a child run straight through that space on their way to bed (with the top half closed. 

To reproduce build or place a lvl 1 frontier house. 
Then have a builder upgrade the house to lvl 2. https://imgur.com/KrE8LH6 in the screenshot you can see the bottom half of the door has been placed.

after the top half of the door is placed the bottom half disappears. https://imgur.com/YKjNrlC

https://imgur.com/XlLBJSl

Placing a block in the bottom space places the block but breaks the whole door. https://imgur.com/TJU3ubf

**Comment by marchermans** [comment]
This is not a do issue.
The builder is just planning then in the wrong order would be my guess... It works flawlessly when the player places them

**Comment by Moobien** [comment]
It seems to disappear once the top half is placed. But whether the door is open or closed the player cannot pass but colonists can

**Comment by ravenbuilder934** [comment]
fixed
