### ISSUE TITLE
Deliverymen should be able to pick-up orders too

### ISSUE THREAD

**Issue by SulpherStaer** [ldtteam/minecolonies#769]
### Minecolonies version

version 1.11-0.6.3282

### Expected behavior

- There is a request for raw material such as logs, the lumberjack has logs available. A delivery person should bring these logs to the warehouse, or directly at the order.

### Actual behaviour

- An order is repeated, despite materials available. (not in the warehouse)

### Steps to reproduce the problem

1. Build a colony.
2. Have a builder, a warehouse and deliveryman, and a lumberjack
3. Ensure the warehouse is empty, and the lumberjack has started logging.
4. Have a builder build something that requires logs.
5. See the deliveryman doing nothing, as no materials are available inside the warehouse, despite being available in the colony.

**Comment by Raycoms** [comment]
Already been working on. there is an issue just for this.
