### ISSUE TITLE
Builder not accepting Clock and Comapass

### ISSUE THREAD

**Issue by marcin212** [ldtteam/minecolonies#7690]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version:  minecolonies-1.0.57-ALPHA-universal
- Structurize Version: structurize-0.13.252-ALPHA-universal
- Related Mods and their Versions: Quark-r2.4-319

## Expected behavior

- Builder's Hut accept clock and compass

## Actual behavior

- Builder requests Clock and Compass and request can't be fulfilled (no button)

![screen1](https://img.bymarcin.com/2021-10-18_17-59-24_m6v266MSwjEArkua.png)

## Steps to reproduce the issue

1. Place Mechanic's Hut (cave style)
2. Build Building
3. The builder cannot complete the construction because he does not recognize the clock and compass 

### Notes

I think it can be related to Quark, because both items contains tags from Quark

- ![screen-clock](https://img.bymarcin.com/2021-10-18_18-00-10_C6NCrYWUj5SjUlzS.png)
- ![screen-compas](https://img.bymarcin.com/2021-10-18_18-00-27_LJ0MPE2BeW7dNOjW.png)

Related issues #4699 that relates to https://github.com/ldtteam/minecolonies-features/issues/135 where is marked as done.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Yes, quark adds nbt to those items and makes them "different" you can fix that by turning this off in the quark config.
