### ISSUE TITLE
Archers friendly fire

### ISSUE THREAD

**Issue by warning-djkajslh** [ldtteam/minecolonies#7692]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- MineColonies Version:
- Structurize Version:
- Related Mods and their Versions:

## Expected behavior

Arrows from archers will not damage the player, knights/other citizens, passive mobs such as golems and animals(especially tamed mobs (i.e:dragons)).

## Actual behavior

The don't have friendly fire and ended up hurting the wrong target while leaving the true threat unharmed.

## Steps to reproduce the issue

1. Get some archers to follow you
2. Observe

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
That is also fine, may happen, there are cases where it respects, and cases we don't want to threat.

**Comment by isaac-prog** [comment]
not sure why is it so hard to just implement this feature.  its super annoying.
