### ISSUE TITLE
I do not have access to all the builds of my colony because I am no longer the mayor since I went to server

### ISSUE THREAD

**Issue by Hmidouch95** [ldtteam/minecolonies#7693]
### Prerequisites 

- [ x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.12.2
- MineColonies Version:1.12.2
- Structurize Version:1.12.2
- Related Mods and their Versions:1.12.2

## Expected behavior
- play on my server

## Actual behavior
-I do not have access to all the builds of my colony because I am no longer the mayor since I went to server 

## Steps to reproduce the issue

- upload your save on a server with the colony 

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ravenbuilder934** [comment]
1.12 is not supported
