### ISSUE TITLE
Miner stuck and does nothing

### ISSUE THREAD

**Issue by Yarik124421** [ldtteam/minecolonies#7694]
### Prerequisites 
- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 
- Minecraft Version: 1.17.1
- MineColonies Version: 1.0.69-ALPHA

### Logs

- latest.log: https://gist.github.com/Yarik124421/ec24a10fef0b0d90791327cfe68550fe

## Steps to reproduce the issue / details

What I tried:

1. Fire the miner and hire him again
2. Summon a worker to the hut
3. Break down the wall where he stands
4. Break down all the walls lmao
5. Push him into the cave (it helped a little, he dug 5 blocks and came back)

### Notes
The miner in my colony refuses to work. He asks for nothing, just stands stuck

<details>
  <summary>Screens: </summary>
  
![image](https://user-images.githubusercontent.com/42224678/137981715-6654d0b6-1c3c-44e8-a457-d74f6873b469.png)
![image](https://user-images.githubusercontent.com/42224678/137981730-9ca5ed24-8298-4090-962a-3f8094e8223d.png)
![image](https://user-images.githubusercontent.com/42224678/137981750-3a213a59-44d5-4811-bbaf-286b798cc052.png)
![image](https://user-images.githubusercontent.com/42224678/137981768-fc094726-de30-4154-808b-426bfb95bc7c.png)

</details>

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Yarik124421** [comment]
The solution turned out to be to dig up all the obsidian next to it, after which the miner start work, However, this looks like a bug

**Comment by Raycoms** [comment]
Is there a way to reproduce this?

**Comment by Justen-N** [comment]
Probably put obsidian blocks around an existing shaft and see if he'll stop
digging. Intuition says some logic may have broken and he isn't sending a
request for a better pickaxe, or that request isn't going to the player for
some reason.

**Comment by Yarik124421** [comment]
> Is there a way to reproduce this?

I made a backup of the colony, but did not backup the world, I will try to reproduce it and I can send a copy of the world if I succeed in repeating

And he also had a diamond pickaxe and so, he could break obsidian, but he did not.

**Comment by Yarik124421** [comment]
It looks like I have a copy of the world when it was still hanging

**Comment by Raycoms** [comment]
Found ways to improve in latest
