### ISSUE TITLE
Citizens all sit in the same sit in the restaurant

### ISSUE THREAD

**Issue by warning-djkajslh** [ldtteam/minecolonies#7698]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- MineColonies Version:
- Structurize Version:
- Related Mods and their Versions:

## Expected behavior

They wouldn't anymore, if there is no available then they should stand up.

## Actual behavior

They stockpile on each other's sit
https://cdn.discordapp.com/attachments/741531816422539384/900602908641488946/2021-10-21_11.18.49.png

## Steps to reproduce the issue

1. have a lot of starving citizen
2. open a restaurant
3. watch them flood over.

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Happens, no bug, feature request please
