### ISSUE TITLE
[Feature] Knowledge System for autocrafting

### ISSUE THREAD

**Issue by Isfirs** [ldtteam/minecolonies#77]
As discussed with @Kostronor 
## New Hut

The librarien. 
## New achievement
- Aquire knowledge (build librarien to lv 1)
- A true master of wisdom (maxed out librarien)
## New game & colony mechanic
- In terms of auto crafting, every citizen has a list of default capabilities(based on profession).
- These are limited to very basic items, aka wood tools, turn logs to planks, torches. Tier 1, a few tier 2 craftings.
- Tiered crafting system. Depending on the levels of craftings, the item is classified into a tier.
- To gain more craftings, knowledge must be aquired. This is the job of of the librarien. The activity involved comes later, making a diagram.
- Leveling the hut & the librarien itself unlocks new capabilities to the librarien, the citizens and the crafting system
# Knowledge persistence
## Creating
- The librarien has a (hut GUI or a new block specialised for it) system to generate craftings.
- This involved "guessing" the recipe.
  - You have tabs representing each crafting grid( 2x2, 3x3, mods can add new one)
  - Putting things into the crafting grid provided checks for the outcome.
  - This will be validated to the item tier, the librarien level (& maybe the hut level, but used definitly somewhere else).
## Persisting
- Each (working) citizen has a some knowledge (lets say its a book)
- Giving a citizen a knowledge page(=a crafting information) lets him store it into his own storage(=in his book)
- This slots can increase by:
  - Leveling the citizen
  - Leveling the worker hut
  - leveling the librarien hut
  - Leveling the citizens hut (where they live in) 
- Each citizen class has a base number of slots(a blacksmith will craft more then a lumberjack)
## Tiered crafting
- The number of layers to craft an item equals the tier
- Needs to be defined more.

**Comment by pmardle** [comment]
I like the general idea..

I would suggest the Librarian actually uses the Town Hall as their home/workspace..  gives a reason to level the TH up too then :)

Not sure I 100% understand the mechanism for creating/learning new recipes for your citizens.  You basically teach the librarian by crafting the item once it it's GUI?

I would rather see this as a time based system,. where say the Librarian is "studying" at the TH Library, and every now and then "Your Librarian has learnt a new recipe" - which is passed to the relevant workers.  There should also be some mechanism of boosting the librarians speed - Perhaps giving him a jar of ale gives him a 50% speed boost for a while (example :P) - or something like this..  Just having to teach the worker all the recipes just seems like a lot of work for the player for nothing.

**Comment by pmardle** [comment]
Perhaps actually the Librarian's learning speed is also influenced by the number of bookcases located nearby (Like the Enchantment Table but with a bigger range.)

**Comment by Isfirs** [comment]
I want to point out that the actual crafting system needs to consider alot of use cases:

- Vanilla Crafting (2x2 and 3x3)
- Smelting (aka different input slots & materials and a result)
- Advanced crafting

### Advanced Crafting
This comes from enabling mod support. Systems such as thermal expansion have systems allowing a complex system of crafting (1 input, multiple out puts, multiple inputs, multiple outputs)

### Possible solution
Considering tools that already exist, we could take a look at `Steve's Factorymanager`. He did a great job of enabling crafting for at least **EVERY** type of crafting possible. 

### Conclusion
That will lead to a lot of designing. We will come to some kind of `programming` for the crafting, but it would be a system enabling a lot of features from design, such as mod support and complex craftings. A tool may help `programming` the crafting instructions.

**Comment by Raycoms** [comment]
We should only consider vanilla crafting. If a building contains specific
items the player should give them to the builder.

2016-09-13 6:30 GMT-03:00 Isfirs <notifications@github.com>:

**Comment by forReason** [comment]
I definitely could also see it go into a whole other direction:
Researching.

You can build the standard buildings like builders hut, sawmill etc. but you have to unlock the upgrades by researching. The workers can create very basic (wood) tools automaticly. 

You can then for example research advanced professions such as Carpenter, Mason or blacksmith which can provide the Workers with the required advanced materials.

**Comment by DanNetwalker** [comment]
Ok, what if the game mechanic where:

- A library is built, a librarian is spawn
- Player has to give items to the librarian for him/her to study, and paper, ink and feathers as work tools
- Every now and then the librarian makes a "knoledge scroll" that shows how an item is made
- When a worker needs to build a certain item, if the player or a messenger gives the scroll to the worker, that worker learns to make that item. Only that worker in particular
- Should certains special workers can make tools for others (blacksmith?). A good player should priorize giving the scrolls to this workers. Messenger workers will just give the scroll to the first worker asking for a block that doesn't know the item recipe.
- Should a worker know the recipe, the messenger could give the materials instead of the item if there's no item availlable, IF AND ONLY IF the worker station has a crafting table

That way players can let the librarian do his/her job and the system will kind of work, but a micro managing player could priorize and give the habilities to a high level builder before a low level one, a certain wood cutter, etc.

**Comment by AndrewTru** [comment]
@forReason @DanNetwalker 
I see where the two of you are going with this, But what if you did some off both.
Just here me out, the game will 'give' you the basic ones (Wood tools, farming wheat, some basic food items, and so on) When you first get started the librarian is spawned the max size of the colony is moved to 5 from 4 that way you get the same 4 workers to start with.
the rest of it the knowledge scroll and the work tools are provided to account for it.
most of it will just be everything you need to make a 'self-safishent' colony.
you still micro manage it as mayor but the AI is sub controlled by the TH that way the player can pick what is done by the computer and what they do by hand (extends the automatic jobs setting)
again this is just my two cents on the matter.

**Comment by WORMSS** [comment]
You could make the 2x2 as a basic, and 3x3 as you go up the levels?? I am not sure if that would be for the crafter to do or the researcher? Or are you making it so Crafter makes items, Forger/Blacksmith makes tools?

**Comment by AndrewTru** [comment]
@WORMSS 
If we do it that way it limits the auto crafting support the colony can provide till you get to that point.
If we make it so everyone has the same 2x2 crafting when out and about but a 3x3 when at the building in question. The builder is the odd one out due to a 'better crafting' research that promotes the 2x2 with the idea of taking a crafting table to and from the job site but I see your point.

**Comment by th3wyatt** [comment]
Maybe the library is used to store crafting recipes that are player created and a workshop to do the actual crafting?  You get a limited number of slots and get more as you level the library(maybe also install upgrades for storage, book racks?).  The workshop levels will allow more a more simultaneous crafting operations as it levels.  You could also install upgrades to tune if you want more speed or fluid crafting.  I would think that would be better than just having full on access to everything.  You would need to "teach it" what to craft.

**Comment by hron84** [comment]
Independently from the Librarian, I would like to see a Blacksmith. Also, Blacksmith should spawn with knowing wooden tools already (if it is craftable), if not, look for a first equivalent craftable tool. This partially can be similar how Dooglamo's Carpenter works, feed it with logs and it can craft tools (plank -> stick -> tool, maybe some strings for a fishing rod). Any other tool levels can be gained from leveling his/her hut AND learning from librarian.

Alternatively, it can learn vanilla (and only vanilla) tool recipes by leveling its hut and learn special tool recipes from librarian (like emerald or obsidian tools that lasts longer, paxels for builder so he/she can break kinda any block that the tool can break). 

Blacksmith can make smeltery, lumberjack and miner more purpose

**Comment by Raycoms** [comment]
Yes blacksmith is planned

**Comment by Wissi** [comment]
@Raycoms I think this should be closed now?
As all this has been implemented now?
If not, then re-open with a comment of why it still needs to be open?

**Comment by Raycoms** [comment]
That's auto recipe discovery

**Comment by Raycoms** [comment]
Closed in favor of joint issue.
