### ISSUE TITLE
NullPointerException:Unexpected error from handleRenderScepterGuard

### ISSUE THREAD

**Issue by HakureiHikaze** [ldtteam/minecolonies#7703]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

--  I am running the latest **release** version of MineColonies and the latest **alpha** version of Structurize for my Minecraft version.

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 1.0.0-RELEASE
- Structurize Version: 0.13.219-ALPHA
- Related Mods and their Versions: OptiFine(1.16.5_HD_U_G8)*The stack trace doesn't mention any other ralated mods, except this.

## Expected behavior

I don't know what will happen when I switch to the Guard Scepter from Build Scepter.

## Actual behavior

The game threw NPE:Unexpected error and crashed for 4 times.
1st:   The first crash, didn't notice what causes the crash.
2nd:  Tried to connect to the server, then client crashed.
3rd:  I connected to the server, and instantly teleported myself to another place then died. Client ran prefectly, but when I 
        switched to the ScepterGold, the client crashed in the same way.
4th:   I changed my character-dat-file, modified  "SelectedItemSlot" from 6(ScepterGold) to 0(other item), then joined the server 
        and moved  ScepterGold to my inventory. But this time when I switched from Slot6(Nothing) to Slot7(ScepterGuard), the 
        client crashed in the same way.

## Steps to reproduce the issue

1. 
2. I scheduled many buildings using ScepterGold. 
3. I have tried to use the Guard Scepter to set guards' path, but made no effects(one of possible causes ).
4. Related action is retold in ##Actual behavior.

### Logs

- latest.log: https://gist.github.com/HakureiHikaze/5543c1cffda4e936db3572a8a4cf938a
- crashlog: 
- 4 in 1: https://gist.github.com/HakureiHikaze/c8808a5456364c5ca0531400f40504cb

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
Update minecolonies. This bug has been fixed in 1.0.5-Alpha and later versions

**Comment by HakureiHikaze** [comment]
Okay, thanks.
