### ISSUE TITLE
children will not be born and i cannot recruit new citizens from tavern but i have more then enough houses

### ISSUE THREAD

**Issue by TheHouseDownBoots** [ldtteam/minecolonies#7704]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.603 ALPHA

### Logs
[2021-03-05-1.log.gz](https://github.com/ldtteam/minecolonies/files/7402433/2021-03-05-1.log.gz)

- latest.log: 

## Steps to reproduce the issue / details

Just reporting the AI issue. 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
I'm sorry, we're not offering any 1.15.2 support anymore.
