### ISSUE TITLE
Guards don't actually patrol the shaft entirety in patrol mine mode

### ISSUE THREAD

**Issue by warning-djkajslh** [ldtteam/minecolonies#7707]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-1.0.68-BETA-universal
- Structurize Version: structurize-0.13.252-ALPHA-universal
- Related Mods and their Versions:

## Expected behavior

Guards will properly patrol the mineshaft, maybe even have them stick close the miner.

## Actual behavior

The guards just patrol the mine schematic, on the surface, leaving the miner to go down on his own, eventually get killed down there.

## Steps to reproduce the issue

1. Assign some guards to patrol in the mine
2. Observe

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
They only patrol the nodes, not the shaft itself

**Comment by Raycoms** [comment]
They only start patrolling down there when the miner goes horizontal
