### ISSUE TITLE
Postbox request interrupted after sometimes

### ISSUE THREAD

**Issue by warning-djkajslh** [ldtteam/minecolonies#7708]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- MineColonies Version:
- Structurize Version:
- Related Mods and their Versions:

## Expected behavior

The request will still remain

## Actual behavior

The request vanished even if the order has not been met

## Steps to reproduce the issue

1. Build a L5 warehouse
2. deposit A LOT of something
3. Request all of the items from the postbox
4. Leave it on for a while, wait for night fall, leaving and entering the game...

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Yes, this is possible, if sth in the request chain fails, the request gets cancelled.

**Comment by warning-djkajslh** [comment]
So does this mean the issue is not going to get fixed?
