### ISSUE TITLE
Citizen ran outside of the houses to escape monsters

### ISSUE THREAD

**Issue by warning-djkajslh** [ldtteam/minecolonies#7709]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- MineColonies Version:
- Structurize Version:
- Related Mods and their Versions:

## Expected behavior

Citizens will try to stick to buildings when fleeing

## Actual behavior

They went far away from any houses, into the "wilderness" (technically they are still inside the colony but because my colony have only consist a few houses so it is relatively smaller than the actual border), they went into the danger zone without knowing and ended up getting killed, even if there are about 10+ guards in my colony.
Sometimes they would flee through the town and got lost outside.

Here's as citizens that fleed outside
![2021-10-24_08 01 55](https://user-images.githubusercontent.com/79503341/138579321-ce214dca-7e44-43e5-a4ea-fe71e02c3918.png)

## Steps to reproduce the issue

1. Just enable night owl II in a crowded colony and see I guess.

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
This should be a feature request. Not a bug. Feature requests are somewhere else
