### ISSUE TITLE
Simple park requires monster egg

### ISSUE THREAD

**Issue by Nugoo** [ldtteam/minecolonies#771]
### Minecolonies version

version 0.7.3.2

### Expected behavior
Simple park does not require monster egg

### Actual behaviour

Simple park requires 4 cobblestone monster eggs

### Steps to reproduce the problem

1. Start a colony
2. Build a builder's hut
3. Use the building tool to place a Simple Park blueprint
4. Check the required resources at the builder's hut

**Comment by xavierh** [comment]
Thus is a known issue. I will update the schematic soon.
