### ISSUE TITLE
Builder AI issue

### ISSUE THREAD

**Issue by TinedCircle1744** [ldtteam/minecolonies#7711]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: v3.4

### Logs

- latest.log: 

## Steps to reproduce the issue / details

Just reporting the AI issue. 

### Notes

Only 1 builder seems to have this issue. 
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the co
[latest.log](https://github.com/ldtteam/minecolonies/files/7405864/latest.log)

##Comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
MineColonies version? 3.4 is no MineColonies version

**Comment by TinedCircle1744** [comment]
Sorry,

 

On the main screen of CurseForge that is the number it showed.

 

Here are all the numbers I could find – if none of these are the one you are looking for could you please tell me how to find it please? Also, the issue went away after I upgraded the builder to the 3rd or 4th level.

 

Forge: 36.2.4

MC 1.16.5

MCP 20210115.111550

 

Thank you.

**Comment by Raycoms** [comment]
You have to open the mods list, and there search for minecolonies

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by TinedCircle1744** [comment]
Ok, thank you. So easy ha ha

 

MineColonies   1.0.0-RELEASE

**Comment by Raycoms** [comment]
Should be fixed in the latest then
