### ISSUE TITLE
Unable to place builder hut even 6 blocks away from a town hall

### ISSUE THREAD

**Issue by sixtiethemu** [ldtteam/minecolonies#7715]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:Mc Eternal 1.12
- MineColonies Version: minecolonies-1.12.2-0.11.811-BETA-universal
- Structurize Version:
- Related Mods and their Versions:

## Expected behavior
 Able to place builder hut in a radius of a town hall

## Actual behavior
 I right click the builder hut 6 blocks away from the town hall and it still says "You need to be closer to your town hall" in chat

## Steps to reproduce the issue

1.  Place the town hall blueprint Make sure there is building tape around the area
2.  Attempt to build the builder hut in any radius 
3.  a message in chat saying "You need to be close to your town hall" will appear 

### Logs

- latest.log:  https://gist.github.com/sixtiethemu/34d6ae8d23c0915feded275d0c59c999
- crashlog: 

### Notes
 My .latest log had to much text to put it all in a gist so i put the log up to placing the town hall untill making this bug report, I am in a multiplayer  server

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
There is no support any more for 1.12, although you can still read past messages in Discord to see if they help you.
