### ISSUE TITLE
Baker craft bread doughs into breads instead of cooking them

### ISSUE THREAD

**Issue by warning-djkajslh** [ldtteam/minecolonies#7716]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- MineColonies Version:
- Structurize Version:
- Related Mods and their Versions:

## Expected behavior

The baker will put the dough into furnaces and cook them into breads

## Actual behavior

The baker hand crafted the dough into breads.
As you can see, the baker is crafting the breads
![2021-10-25_17 35 49](https://user-images.githubusercontent.com/79503341/138681709-1a7c9b26-cd89-41a0-8009-0ebcaa927ced.png)
![2021-10-25_17 35 47](https://user-images.githubusercontent.com/79503341/138681722-3b8dec13-d1b5-4f40-97c6-a4ae45bdea6c.png)
![2021-10-25_17 35 48](https://user-images.githubusercontent.com/79503341/138681725-ac99c415-08f8-40c8-adb0-c8abc52366c6.png)

## Steps to reproduce the issue

1. Build a L5 restaurant
2. Request some breads

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
That was solved
