### ISSUE TITLE
Frorester replants Dark Oak sapling wrongly

### ISSUE THREAD

**Issue by HakureiHikaze** [ldtteam/minecolonies#7719]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: **1.16.5**
- MineColonies Version: **1.0.68-BETA**
- Structurize Version: **structurize-0.13.252-ALPHA**
- Related Mods and their Versions: Not related, I guess.

## Expected behavior

Foresters should replant **4** Dark Oak saplings after they fell the tree.

## Actual behavior

They **sometimes** replant **3 or less** saplings after they fell Dark Oak trees.

![image](https://i.ibb.co/bdT48Hr/Forester-Bug.jpg)

## Steps to reproduce the issue

1. Plant Dark Oak trees in Forester's area.
2. Forester fells the tree.
3. Forester **sometimes** replants **3 or less** Dark Oak saplings.

### Logs

- latest.log: Not crashed.
- crashlog: Not crashed.

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
This is somewhat expected behaviour when they run out of saplings mid-replant.  They will also continue to chop down more trees and then not replant anything (until they get more saplings) after this.

**Comment by HakureiHikaze** [comment]
OK, thanks.
