### ISSUE TITLE
Fishermans Boat pathing

### ISSUE THREAD

**Issue by SulpherStaer** [ldtteam/minecolonies#772]
### Minecolonies version

version version 1.11-0.6.3282

### Expected behavior

- NPC's correctly find a path around the fisherman's boat

### Actual behaviour

- Infrequently the fisherman's boat causes the fisherman, and the deliverymen that visit to get stuck.

### Steps to reproduce the problem

1. Build a colony
2. Build a fisherman at the very edge of the colony
3. Build a warehouse and several deliverymen
4. Wait for pathing to screw up around the fisherman's boat - (I was at colony center and only noticed afterwards)

**Comment by Raycoms** [comment]
I am sure we have an issue for that here already.
Working on it
