### ISSUE TITLE
Fatal error in server console

### ISSUE THREAD

**Issue by ghost** [ldtteam/minecolonies#7720]
### Prerequisites

- [ ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 1.0.0-release
- Structurize Version: 0.13.219-alpha

### Logs

- latest.log: https://pastebin.com/7Nn3uEKn

## Steps to reproduce the issue / details

Im sorry i dont know what triggered this error

Just reporting the AI issue. 

### Notes

The "fatal" error just appeared in my server console not sure what caused it thought you might want it

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Thanks for reporting this. This is "normal". It's when the client sends multiple messages to fulfill a request.
