### ISSUE TITLE
Some modded hostile mobs aren't detected in the guard's target list

### ISSUE THREAD

**Issue by warning-djkajslh** [ldtteam/minecolonies#7721]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- MineColonies Version: minecolonies-1.0.85-ALPHA-universal.jar
- Structurize Version:
- Related Mods and their Versions:

## Expected behavior

The game will register these as a hostile mob and put them on the target list for guards

## Actual behavior

Guards treat them as neutral mob
They do not appear on the target list
Example is some mobs from Ice and Fire mod, such as the dread mobs

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
There is a config way for this.
