### ISSUE TITLE
You may occasionally get visitors boots if you kill them

### ISSUE THREAD

**Issue by warning-djkajslh** [ldtteam/minecolonies#7725]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- MineColonies Version:
- Structurize Version:
- Related Mods and their Versions:

## Expected behavior

VIsitors will ALWAYS drop their boots upon death

## Actual behavior

They rarely drop them.

## Steps to reproduce the issue

1. Build a tavern
2. Kill any visitors that spawn

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by someaddons** [comment]
intended, not a bug
