### ISSUE TITLE
Builder not excepting banners

### ISSUE THREAD

**Issue by Legorfyr** [ldtteam/minecolonies#7728]
### Prerequisites 

- [ x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.17.1 with Forge Version 37.0.90
- MineColonies Version: minecolonies-1.17.1-1.0.86-ALPHA
- Structurize Version: structurize-1.17.1-0.13.253-ALPHA
- Related Mods and their Versions: domum_ornamentum-1.17.1-1.0.13-ALPHA-universal
                                                      blockui-1.17.1-0.0.29-ALPHA
                                                      multi-piston-1.17.1-1.2.1-ALPHA
## Expected behavior
 Builder accepting the crafted banners

## Actual behavior

I'm using medieval birch and its alternative in my colony, but this issue happens with both. Builder wants banners without nbt data, I can only craft ones with nbt data.

https://ibb.co/wr1hksM
https://ibb.co/3vQRm28
https://ibb.co/nm4QYjC

## Steps to reproduce the issue

1.  Build for instance medieval birch alternative courier lvl 4, which needs 1 orange banner.
2.  the material list will not update.
3.  Buildings can't be upgraded. My university is stuck at lvl 2 because of this and can't build the school etc.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
That's strange, I'm fairly certain that it is working fine on our 1.17 server. i wonder if you got any mod messing with the banner crafting.

**Comment by Legorfyr** [comment]
I found out which mod it was, multi beds. So after removing it everything works :)

**Comment by Raycoms** [comment]
Awesome, thanks for figuring this out!
