### ISSUE TITLE
Citizens will not attend their working hut block if there is nothing to do there

### ISSUE THREAD

**Issue by warning-djkajslh** [ldtteam/minecolonies#7729]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- MineColonies Version:
- Structurize Version:
- Related Mods and their Versions:

## Expected behavior

Citizens should always come and stand around their worksite during working hours

## Actual behavior

Unless there are things to be done there, such as crafting or building request, the citizen would just stand still around their bed...

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
This is, currently, on purpose
