### ISSUE TITLE
You can genocide visitors without any major conciquences

### ISSUE THREAD

**Issue by warning-djkajslh** [ldtteam/minecolonies#7731]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- MineColonies Version:
- Structurize Version:
- Related Mods and their Versions:

## Expected behavior

The amount of visitors will eventually be zero for a while, or even forever.

## Actual behavior

Even if they said that my tavern has been rumored as extremely dangerous, they would keep coming back to this literal dangerous place and get butchered by me.
No drawback to not just even put them on the target list if your military is strong enough, to farm diamond boots in large quantity.

## Steps to reproduce the issue

1. Get a strong axe that 1-2 shot visitors
2. Build a L5 tavern
3. Kill every visitors that spawn, over and over like the animals they are.

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Please. This is bugs not feature requests
