### ISSUE TITLE
courier keeps picking up inventories even though it's set to NEVER

### ISSUE THREAD

**Issue by linn001** [ldtteam/minecolonies#7736]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- MineColonies Version:
- Structurize Version:
- Related Mods and their Versions:

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Please fill in the template, also. Was it full?

**Comment by linn001** [comment]
No.

He just kept on taking all of the stuff it’s so annoying cuz my builder
will just stop and go back and forth and build absolutely nothing.

tis 2 nov. 2021 kl. 01:16 skrev Raycoms ***@***.***>:

**Comment by Raycoms** [comment]
Template was still not filled in - stale issue - can't reproduce (only when builder inventory gets too full)
