### ISSUE TITLE
Buildings Burning Down

### ISSUE THREAD

**Issue by Josiahisnerd** [ldtteam/minecolonies#7738]
My Dark Oak Houses (Tier 2) and my Dark Oak University keep burning down, I cannot figure out why either, will report back here if I can find out, but if you know I would love to find out.

**Comment by Justen-N** [comment]
As I posted in your discussion topic, Discord is the best place for this type of support. Also, If you create an issue in the future, please fill out the template

**Comment by Josiahisnerd** [comment]
Dang you are fast
