### ISSUE TITLE
Server crashed and refuses to restart after placing tile entity.

### ISSUE THREAD

**Issue by Deylendor** [ldtteam/minecolonies#774]
Was sent here from the "Refined Storage" github.
https://github.com/raoulvdberge/refinedstorage/issues/1135
After placing a cake with their mod the server crashed and refused to start ( ticking tile entity ).

quote from their man [raoulvdberge]::
**"**This is a problem with com.minecolonies, please report the bug to them. You could also try updating Forge if you're not on the latest version yet, as I heard this bug is prevented with newer Forge versions.**"**

I made the server playable by temporary setting
B:removeErroringTileEntities=false to true in the forge.cfg file.

I'm linking you my logs so you can determine for yourself if your mod really was the cause for our sever crash.

**latest.log**
https://pastebin.com/q5F8xyef

**fml-server-latest.log**
https://gist.github.com/Deylendor/66ebff1742ee2acc33463de6ae4b7500

**Comment by Raycoms** [comment]
Did you try using the newest minecolonies version of curse?
And is it 1.10 or 1.11?

2017-04-06 21:15 GMT-03:00 Deylendor <notifications@github.com>:

**Comment by Deylendor** [comment]
my apologies.. versions! of course.



Minecraft: 1.11.2
Forge: 1.11.2 - 13.20.0.2265
Minecolonies : Minecolonies 1.11.2 permissions v3 - File :: minecolonies-universal-1.11-0.6.3282.jar

It seems to be the latest version on Curse, yes.

**Comment by Raycoms** [comment]
can you try this one here it should fix the bug you were experiencing.

https://www.dropbox.com/sh/9cnqcjl0nan57cy/AAC99g-CJiTZjQiXMuLKkDgja/branch/version/1.11?dl=0&preview=minecolonies-universal-1.11-0.6.3360.jar



2017-04-06 21:22 GMT-03:00 Deylendor <notifications@github.com>:

**Comment by Deylendor** [comment]
Will do ASAP.

**Comment by Deylendor** [comment]
It fixed the issue completely. 
Gotta lose my cool and say it..  badass support.

**Comment by Raycoms** [comment]
Great to hear. Will upload that version in the next days to curse.
