### ISSUE TITLE
minecolonies-server got corrupted after abrupt exit

### ISSUE THREAD

**Issue by fviol** [ldtteam/minecolonies#7742]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

- Minecraft Version: 1.17.1
- MineColonies Version: minecolonies-1.17.1-1.0.95-ALPHA
- Structurize Version: structurize-1.17.1-0.13.253-ALPHA

## Problem description
My local game session has unexpectedly closed because of force pc reboot. After that, I couldn't enter my world with an endless "reading word files". It turned out that files in serverconfig folder are corrupted: instead of colony information, there's a bunch of NULs.
I managed to restore all of my buildings and inventory but my colony settings and colony itself are gone.
Please, if there any way to restore everything, including citizens and settings, inform me. 
Thank you!

### Notes or related things
Backup commands are not helping.
Structurize TOML is also corrupted.

![photo_2021-11-04_19-47-33](https://user-images.githubusercontent.com/93731633/140393152-9f63c7ab-7ca7-41ea-a9a9-1caa0b7a7558.jpg)

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by someaddons** [comment]
not sure what corrupted the files, but its not related to minecolonies coding, its a library thats used for handling configs. If they are corrupted simply delete them and they'll regenerate

**Comment by fviol** [comment]
> not sure what corrupted the files, but its not related to minecolonies coding, its a library thats used for handling configs. If they are corrupted simply delete them and they'll regenerate

But I lost all the colonies. Citizens don't have names anymore and buildings are just blocks with no workers chained to them.
Mb there are any backup files where I can get the latest copy of the stable colony?

**Comment by Raycoms** [comment]
Yes there is, in the world/minecolonies folder there are backups of the colony data

**Comment by fviol** [comment]
> Yes there is, in the world/minecolonies folder there are backups of the colony data

How to apply them so all the citizens could get back and attached to their buildings? Because now they're just straying around with no names, and buildings are empty.
