### ISSUE TITLE
Cactus Jack's actual dialogues are missing

### ISSUE THREAD

**Issue by pantsguyapp** [ldtteam/minecolonies#7752]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- MineColonies Version:
- Structurize Version:
- Related Mods and their Versions:

## Actual behavior

Missing dialogues for hiring as well

![2021-11-08_17 39 27](https://user-images.githubusercontent.com/92203672/140730977-4106fa2d-b847-4e41-bdca-f7fb13303ed1.png)
![2021-11-08_17 39 37](https://user-images.githubusercontent.com/92203672/140730986-6d042ad5-189b-49bb-a20f-823bb44ee717.png)

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Fixed, next time please fill in the full template. We can't guess the version you're on =P
