### ISSUE TITLE
Gravedigger reports it has an AI issue 

### ISSUE THREAD

**Issue by WebDragon** [ldtteam/minecolonies#7754]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-1.0.111-ALPHA-universal, structurize-0.13.252-ALPHA-universal
- latest Direwolf20 pack for mc 1.16.5 but bumped the two aforementioned mods to their current release above to see if the problem had been resolved in a more current version of minecolonies but it persists in spite of the updates. 

### Logs

- latest.log: https://gist.github.com/WebDragon/4e36989dc1f2fe287df4f9748d1c608d

## Steps to reproduce the issue / details

Problem occurred possibly after upgrading their hut (Stone type) to either tier 3 or tier 4 (it was at tier 4 before I noticed the villager wasn't coming around to work but was instead malingering around their bed). I also have a Jungle mystical site immediately adjacent to the graveyard, also at tier 4.

Just reporting the AI issue. 

### Notes

I may try a teardown and rebuild if you think that would be a good idea. 

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
It seems something placed a fast furnace at the grave position?

**Comment by WebDragon** [comment]
I tried breaking that grave (it was in fact a gravestone and the only one that had been placed so far by my gravedigger, around lvl 1 of the hut) to see if it would clear the AI but it did not. the block's absence from the world doesn't seem to have affected whatever is bugging the AI 

It looked to me that a 'fast furnace' was trying to be cast as a gravestone? if I'm reading things right? like utilize one block as another block for decoration with a different skin? (not sure how that all works TBH)

**Comment by MotionlessTrain** [comment]
The gravedigger assumed on the position of the grave, there would be a grave, with the data of the grave (like inventory, information about the citizen just died there, etc.).
But It looks like that the block on the position where the grave is/should be was a fast furnace instead, or at least had the data of a fast furnace.
"Casting" in this case is viewing the object with all the data, and interpreting it as a gravestone in this case. (Which obviously isn't possible if it is a fast furnace)

**Comment by WebDragon** [comment]
so considering I broke the block (and it went away and didn't drop anything) why is the AI still bugnuts about it? should I try placing another block in its place? or just tear down and rebuild the graveyard from tier 1 again?

**Comment by WebDragon** [comment]
[Gist of Latest.log](https://gist.github.com/WebDragon/3135cb648b43b595d62c8066bf8b5970)

Problem persists in latest  minecolonies-1.0.118-ALPHA-universal inspite of complete teardown and rebuild of entire graveyard, including breaking the build-tool block and starting the graveyard over from scratch, AND placing and breaking blocks all around above and beneath the location of what had been the only grave ever placed by the gravedigger.

The instant I hire the citizen and recall them to the location so I could watch them, within 15 seconds their AI once again encounters the problem.
