### ISSUE TITLE
Jungle Theme Issues/Pathing Issues

### ISSUE THREAD

**Issue by ZippityDoodah** [ldtteam/minecolonies#7755]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.339-ALPHA
- Structurize Version: 0.13.208-ALPHA

## Problem description

Currently playing the FTB Direwolf20 Pack v1.11.0 (Beta) - Been playing with the Minecolonies Mod for a little over a month, primarily using the Jungle Theme for most buildings with a few Dark Oak buildings mixed in here and there. The issues I've noticed relate primarily to Pathing issues and a few Structure Issues with some of the buildings. #1 - Because the Vines grow between upgrades, each time a building gets upgraded, the more vines involved with the prior Tier tends to cause upgrades to take 2 to 3 times or more longer to upgrade/repair then any other building theme. This is primarily due to the builders having to remove all the vine growth in order to put them back to the length as appropriate to the new/current tier dictated in the build. This leads into issue #2 - the Builders (as well as Guards and other townsfolks) tend to want to path up vines to the top of the very tall jungle trees when moving about, or when the builder is performing their upgrades/repairs. Sometimes this leads to their deaths from fall damage, or sometimes they get stuck in the tree (this is usually the builders) either because the vine was cut by a builder or they get caught in a pathing loop within the vine layout/structure. Another issue regarding pathing is issue #3 - When building walls (specifically the decorative walls) around the perimeter of the town, there is a tendency for some townsfolk (beyond the guards) to go out of their way, by quite a long distance) to move towards the walls regardless of distance, when heading to where they need to go. This has happened several times where I will find an Archery Trainee on the polar opposite side of town from their home and workplace, pathing along the wall (or sometimes on top of the leaves - such as with Dark Oak Decoration Walls) almost in a random fashion (sometimes this leads to their death as they fall off the leaves or jump off ledges). I have no roads or paths leading to any of the walls, and yet I find non-guards running along the walls for whatever reasons. Another issue regarding the Jungle Theme are some of the buildings not functioning correctly or functioning in a way as to cause issues. An example is the Jungle Themed Tavern (Tier 3), where I've had a minimum of 5 visitor deaths, 2 from climbing up vines and falling off the trees, and 3 from wall suffocation because too many visitors are crammed into such a tight space causing some to be pushed into the walls or get stuck on the stair blocks while sitting. Only way to fix the issue with falling was to remove all vines leading up to the tree tops, but the suffocation of getting stuck in a wall is not really fixable as it is not always the same structure points where this occurs. Another building that has an issue within the Jungle Theme is the Swineherder building, where the pigs are able to climb up on the tables and cauldron and because the 1 block high stone wall is just at the corner of cauldron and table top, they can walk right out onto the wall and escape. Only solution was to extend the Jungle Fence one block in both directions along the top of the Stone Wall to disallow the pigs a path to get onto the stone wall, so you may want to adjust that building for later releases. Another building with issues is the Jungle Rabbit Farm, where the Rabbits are constantly escaping through the double set of doors leading into and out of the holding pen. Either because the worker/guards leave the door/s open, or because the rabbits get pushed out when a town member leaves the pen. My only solution that worked was to replace the door into the pen with a 3 block high wall and use ladders on either side for the worker to get in and out of the pen (this involved knocking out some clay roof pieces as well. I also saw that some rabbits were glitching into the Paper Wall near the door, so i replaced it with Jungle Planks. Overall, the Jungle Rabbit building is a bad design, as rabbits are in constant jumping motion trying to get out of the small space they are trapped in. When I made the wall/ladders only 2 blocks high, sometimes they were able to still escape. So that building may need some rework.

### Notes or related things

I believe the only possible solutions for the vine issues is to either remove townsfolks/visitors ability to climb vines, remove the vines from the builds entirely, add vines that are incapable of growing and use those instead of normal vines in the builds, and or remove vines as a viable path usage for builders and other townsfolks. As to the Wall issue, I can understand the guards pathing out to the walls, as they auto path pretty much everywhere within the town boundaries, but the other townsfolks, like Couriers, Builders, and so forth should not be going so far out of their way just to use a wall path to get to their destination, especially when a more direct path is more viable. When my courier died falling off a Dark Oak Wall because it was walking on top of the leaves 9+ chunks away from any other building or pickup/drop-off point, it was unreasonable why it should have ever gone out of it's way to leave the path I made between buildings already, to go to the ground where I have no paths created, head many chunks out of it's way to a decoration wall, climb a vine to get on top of the leaves, then fall off when nothing was out there that would give it a need to go there in the first place. So obviously there are some pathing issues that still needing to be worked out.

Overall, I love the mod, but I will probably never go with the Jungle Theme again, because it just has too many pathing issues and because upgrading/repairing is so tedious with the builders taking such a huge amount more time to do their jobs because of vine growth and pathing up/down the vines. When I did the Asian theme in Life in the Village 2, I never had those types of issues with upgrading/repairing. Never built walls then, so I never experienced the pathing issues I've run into this playthrough regarding the decoration walls.

Thank you for your continued work on this mod.

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Hi, thanks for the long an detailed report. The builder climbing around is certainly intended. But the jungle style has been reworked seriously in 1.17.1 to improve it significantly. Unfortunately, these schematics will not be backported to 1.17 most likely.
