### ISSUE TITLE
Endermen killing villagers

### ISSUE THREAD

**Issue by PerfectNinja** [ldtteam/minecolonies#7759]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 1.0.116-ALPHA
- Structurize Version: 0.13.252-ALPHA
- Related Mods and their Versions:

## Expected behavior
Colonists and Endermen ignore eachother

## Actual behavior
Forester died of "mob". I went to check and found an enderman fighting a knight. Per recommendation in discord, I turned off enderman as a hostile mob for every guard. A few in-game days later, several of my colonists died of "mob" in succession (less than 2 minutes apart). When I got to the death coordinates of the last one, I found a knight fighting an enderman. Something is still causing endermen to attack my colonist, and my guards can't keep the colonists safe.

## Steps to reproduce the issue

1. Make colony
2. ???
3. Profit

## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Definitely not a MineColonies issue, something else must be causing them to attack. I.e. another mod.

**Comment by MotionlessTrain** [comment]
Should be fixed in 1.0.120
