### ISSUE TITLE
Right click not working.

### ISSUE THREAD

**Issue by operative2259** [ldtteam/minecolonies#776]
### Minecolonies version

version1.10.2-0.6.2404

### Expected behavior

Be able to right click on npc and buildings

### Actual behaviour

Game has been running well with builder, miner, and fisher built and running.  Now unable to right click on NPC or the box that the building is based.

### Steps to reproduce the problem

1.  Build Builder  / miner / fisher / builder2 / miner2
2.  Play several hours.
3.  Mod elements stop responding.
4.  Other mods working fine.
5. Restart does not solve the issue.

**Comment by Raycoms** [comment]
okay some questions: /mc colony info   -> returns what?
/mc colony refresh -> solves the problem?

2017-04-07 10:47 GMT-03:00 operative2259 <notifications@github.com>:

**Comment by operative2259** [comment]
Id:1 Name: operative's Colony
Mayor: operative2259
Citizens: 4/4
Cooridinates: x=388 y=66 z=177


/mc colony refresh only returns 

/minecolonies colony
<kill|respawn|info|delete|addofficer|citizenInfo>

My fisherman is still working.  ASked for a fishing pole.  I could not give to him directly but threw one at his feet and he took it and started working again.

**Comment by Raycoms** [comment]
okay then try /mc colony refresh 1

2017-04-07 10:55 GMT-03:00 operative2259 <notifications@github.com>:

**Comment by operative2259** [comment]
/mc colony refresh 1 only returns the same error message.

/minecolonies colony
<kill|respawn|info|delete|addofficer|citizenInfo>

**Comment by Raycoms** [comment]
Please download the newest version and try it again:

https://minecraft.curseforge.com/projects/minecolonies/files

2017-04-07 11:03 GMT-03:00 operative2259 <notifications@github.com>:

**Comment by operative2259** [comment]
I have upgraded and still am not able to right click any building or NPC.   I also tried the refresh command. 

I went back to some older backups and all is good.   I broke and moved the town hall block and that seemed to kill it.  I thought that I had been able to do that before.   

All is good now.   THanks for the assistance.

**Comment by Raycoms** [comment]
The newest version should allow you to move the townhall block.

2017-04-07 13:15 GMT-03:00 operative2259 <notifications@github.com>:
