### ISSUE TITLE
Crash with Optifine shaders sometimes when rendering accesing GUI with blocks

### ISSUE THREAD

**Issue by Shibva** [ldtteam/minecolonies#7760]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 36.2.8 [ver 1.16.5]
- MineColonies Version: minecolonies-1.0.68-BETA-universal.jar
- Structurize Version: structurize-0.13.252-ALPHA-universal.jar
- Related Mods and their Versions: Optifine G7, (see crashlong provided for other mods present)

## Expected behavior

when I click on a minecolony block, it opens the GUI
## Actual behavior

Sometimes when clicking it, the thing will freeze and the game will crash

## Steps to reproduce the issue

Not exacaly what is a guranteed triggure for this, the only thing that seems to be prevailant is going though dimentions, player death, and interactions with any minecolonly block, the Crashlong might help shed some light

### Logs

- latest.log: will provide if neededed, it will be large though
- crashlog: https://gist.github.com/SteamDoge9000/593f903f32129fc6e99a53674578c71d

### Notes

this bug happens randomly, ususaly I belive after I go back to the overworld after I die though death in another dimention, this is usualy not an issue but for some reason it sometimes happens when atempting to access the main GUI (via click interaction)
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Fixed in newest

**Comment by Shibva** [comment]
Issue has returned

https://gist.github.com/SteamDoge9000/111f3e637509cc262ca8e3eb25387675

Verison Present: minecolonies-1.0.124-ALPHA-universal.jar

**Comment by Shibva** [comment]
issue also exist in inecolonies-1.0.128-ALPHA-universal.jar
