### ISSUE TITLE
Guards getting stuck on floating carpet

### ISSUE THREAD

**Issue by darealGameknight14** [ldtteam/minecolonies#7766]
### Prerequisites 

- [x] I am running the latest **release** version of MineColonies for my Minecraft version.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 1.0.0-RELEASE

### Logs

- latest.log: https://gist.github.com/darealGameknight14/771a33b6595babf2a9557dafa9a193b8 

## Steps to reproduce the issue / details

The problem appears to be a combination of AI pathing and the sandstone house3 schematic. I am unsure of what the schematic is actually called. This mostly occurs during guard patrols, but also from random citizens. When travelling upstairs, the guard appears to break due to the minecolonies:floating_green_carpet block. It somehow arrives on top of the block (as of yet I have not seen how this occurs, just the results) and becomes unable to continue its path until someone either removes the block or pushes the guard off. It will continue to spin in place until this happens. 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by someaddons** [comment]
use the latest alpha and report again if still an issue
