### ISSUE TITLE
Pirate ship generated inside colony boundary.

### ISSUE THREAD

**Issue by lordfriend** [ldtteam/minecolonies#7769]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 1.0.91-ALPHA
- Structurize Version: 0.13.252-ALHPA
- Related Mods and their Versions:

## Expected behavior

In the previous version, both pirate ship and barbarian camp are generated correctly outside the boundary.

## Actual behavior

In current version ,when the owner not at any chunks near or inside the colony (like not online or in other colonies) but the colony are not yet unloaded. when a raid started at that time, some raid camp or pirate ship can be generated inside the colony. 

![2021-11-14_22 47 29](https://user-images.githubusercontent.com/1235614/141684259-3fb71d2e-14f0-4a87-b578-99eec599e308.png)

## Steps to reproduce the issue

1.  Set force lord all chunks (chunk load strictness =1) when any officer or own are inside colony.
2.  Leave colony, not over 10 mins.
3.  spawn a raid using command

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
That is intended and was never different. Guard towers are protective buildings with a min range against pirate ships.

**Comment by lordfriend** [comment]
But there is a level 3 guard tower just beside the pirate ship
