### ISSUE TITLE
[1.16.5] Colonist do not load out of bed when player is greater than aprox 48 blocks away from their bed

### ISSUE THREAD

**Issue by Shibva** [ldtteam/minecolonies#7774]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5 36.2.8
- MineColonies Version: minecolonies-1.0.128-ALPHA-universal.jar
- Structurize Version: structurize-0.13.252-ALPHA-universal.jar
- Related Mods and their Versions: will list if needed

## Expected behavior

Id expect for the colonlist to get out of bed while within the colony to head to their jobs
## Actual behavior

they do not load after they go to sleep and requires the player to be within 48 blocks of their bed location for them to "wake up"

## Steps to reproduce the issue

this should be self explanatory, but the best way to test this is to have their home at one side of the colony (a large one) and their work station on the other and fathest point and then wait for them to come to work in the day 
### Logs

- latest.log: 
- crashlog: 

### Notes

pressing the "recall worker" will force them to their workstation and they try to go back to bed but will then recognize that its day. this fixes the issue in one instance, but must be repeated and can get anoying

stepping wtihin aproximatly 50 blocks from their home when its day will wake them up. Chicken Chunks spot loader has been used but seems to have no effect and requires a player presence

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Shibva** [comment]
this aproximation was done thanks to the abacus from the quark mod to help make the block distance calculations

**Comment by uecasm** [comment]
This is an optifine "feature".  Either remove it or disable its "Smooth World" option.

**Comment by Shibva** [comment]
oh, thanks

might not be a bad idea to include a configable warning to let the user know if they have optfine present (going into the config to disable it is an option)
