### ISSUE TITLE
No fuel available in the fuel list of stonesmelter and the stonesmelter cannot use fuel

### ISSUE THREAD

**Issue by EverettSummer** [ldtteam/minecolonies#7775]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 1.0.128-ALHPA
- Structurize Version: 0.14.252-ALPHA
- Related Mods and their Versions:

## Expected behavior

In the previous version , the fuel list has all available fuel to select
## Actual behavior

The list is empty, the stonesmelter cannot work.

<img width="685" alt="javaw_2021-11-17-003931-262" src="https://user-images.githubusercontent.com/55684557/142017033-fa6013d6-a698-4d16-b2e3-90e151af08e4.png">

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Please give us the startup log

**Comment by EverettSummer** [comment]
https://gist.github.com/EverettSummer/9e395c3098eb2de027672fd66bc467bb

**Comment by EverettSummer** [comment]
Btw, Not only the stonesmelter, other workers also has the issue. like the Composter

**Comment by uecasm** [comment]
You do have a bunch of recipe errors during startup, but it looks like it did detect the fuel list properly, so it's probably some kind of client sync issue.  Which modpack is this?  Does it work as expected in single player?

**Comment by EverettSummer** [comment]
I am using my custom modpack. I just upgraded from 1.0.9, since it requires forge 36.2.4+, so I upgraded forge to the latest 36.2.9 and JEI to the latest version. I start the world for almost one year. so this is the first time I encounter the issue. but I guess the issue has been around since 1.0.9

**Comment by EverettSummer** [comment]
Other mod upgrades I can recall is Lycanites mobs.

**Comment by uecasm** [comment]
1.0.9 of what?  Of minecolonies itself?  That's a fairly hefty jump from 1.0.9 to 1.0.128.

Anyway, the thing is that with just minecolonies 1.0.128 (and structurize/jei) this does work as expected, which suggests that it's one of your other mods that is causing problems.  Anything you can do to try to narrow down what is triggering the problem (e.g. multiplayer only, or both? try different versions of minecolonies? try a binary search removing other mods until you find the one which seems to cause problems?) would be helpful, because at the moment we can't reproduce any problems.  It might be a bug in minecolonies, or a bug in the other mod, but until we can reproduce it and track it down it's hard to do anything about it.

**Comment by EverettSummer** [comment]
OK, Thanks for the advice

**Comment by uecasm** [comment]
Can you upload your client logs as well please?  Since you appear to be playing on a server.

**Comment by EverettSummer** [comment]
OK. I just downloaded the world and play it in single-player, the recipe can be displayed in single-player.

**Comment by EverettSummer** [comment]
Here is the client log:
https://gist.github.com/EverettSummer/ed8615dbefd2ae34d3a4c39cb95999c0

**Comment by uecasm** [comment]
Ok, thanks!  That gives me a good hint.

**Comment by uecasm** [comment]
I think I've worked out what's causing this, and it should hopefully be in a new build soon.  In the meantime you should be able to work around it by connecting single-player first and then (without quitting Minecraft) reconnecting to your server.

**Comment by EverettSummer** [comment]
Thank you for the quick response!
