### ISSUE TITLE
Forester chop down logs that are on cobblestones.

### ISSUE THREAD

**Issue by pantsguyapp** [ldtteam/minecolonies#7778]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.17
- MineColonies Version: minecolonies-1.17.1-1.0.127-ALPHA
- Structurize Version: structurize-1.17.1-0.13.253-ALPHA
- Related Mods and their Versions:

## Expected behavior

The npc won't try to chop down the logs that are above cobbles.

## Actual behavior

To prevent the npc from chopping down my whole base, I put down a cobblestone perimeter around the border to mark the "fake trees"
![2021-11-17_12 02 29](https://user-images.githubusercontent.com/92203672/142138176-265398f6-9766-4e56-b144-f106f2f50615.png)
![2021-11-17_12 02 43](https://user-images.githubusercontent.com/92203672/142138197-e2008a7c-c1ba-4bee-8839-23f46699897e.png)
But as you can see, the forester still try to chop them down and doesn't care about the cobblestones at all.
![2021-11-17_12 02 10](https://user-images.githubusercontent.com/92203672/142138323-c82cf44b-4499-468d-8275-12642812a471.png)
![2021-11-17_12 02 11](https://user-images.githubusercontent.com/92203672/142138330-ed56042d-2728-4ccc-a071-ae3928bb86de.png)
![2021-11-17_12 02 14](https://user-images.githubusercontent.com/92203672/142138335-7a68b8dc-21af-4894-a97c-c360034ab564.png)

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by pantsguyapp** [comment]
Still present in minecolonies-1.16.5-1.0.434-BETA for 1.16.5
Chopping tree w/cobble under
![2022-02-15_13 44 27](https://user-images.githubusercontent.com/92203672/154008354-74112e09-16e3-40ea-9893-76755fc66522.png)
Replaced the trunk w/wood block, will tryng to chop
![2022-02-15_13 45 41](https://user-images.githubusercontent.com/92203672/154008443-a892cf78-48c6-445e-a8ed-33ab0f7121fd.png)
![2022-02-15_13 45 43](https://user-images.githubusercontent.com/92203672/154008461-4250ba4c-5eef-4b7b-a762-d6aaf064fcab.png)
This is with zoning mode on and a dedicated chopping zone registered. While darkwood tree is configured to not be chopped in the sapling list.

**Comment by MotionlessTrain** [comment]
Have you tried to fire and rehire the forester after setting the zone and enabling zoning mode and changing the sapling settings?

**Comment by Raycoms** [comment]
1.17 is out of support. Can't reproduce in 1.18
