### ISSUE TITLE
Level 5 builder requests tools of maximum grade of .

### ISSUE THREAD

**Issue by SulpherStaer** [ldtteam/minecolonies#778]
### Minecolonies version

version 1.11-0.6.3282

### Expected behavior

- The builder requests the maximum available tool. (Diamond), or tells you you can get a supported mod that gives him other tools that he can now use.

### Actual behaviour

- The builder requests a tool of maximum grade of . (As you can see, he doesn't say what grade)

### Steps to reproduce the problem

1. Build a colony
2. Build and level the worker to level 5
3. Have its tool run out, and have none available in a warehouse.
4. Observe strange request.
![2017-04-07_18 37 39](https://cloud.githubusercontent.com/assets/5037244/24810201/cfccdaea-1bc1-11e7-82a4-46b14fcad67d.png)

**Comment by Wissi** [comment]
Yeah, when he reaches the max level of tool to use, he will only say that. 

I guess it's a matter of adding (like you suggest) ...maximum grade of "diamond" or better.  
That would be more understandable than just: ...grade of .

Simple 1 line of code Ray?  xD

**Comment by marvin-bitterlich** [comment]
fix is merged :)
