### ISSUE TITLE
Postbox and Stash take a relatively long time to break

### ISSUE THREAD

**Issue by pantsguyapp** [ldtteam/minecolonies#7781]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

Minecraft Version: 1.17
MineColonies Version: minecolonies-1.17.1-1.0.127-ALPHA
Structurize Version: structurize-1.17.1-0.13.253-ALPHA
Related Mods and their Versions:

## Expected behavior

Unlike normal huts, they break as fast as a chest would.

## Actual behavior

Both blocks break extreme slow, meaning it will be very frustrating when using them as portable connection to the warehouse.
Furthermore, the Stash doesn't even has a registered tool to break.
Racks break quite slow too, they should be faster.

## Steps to reproduce the issue

1. Place and break those blocks in survival, if you have TOP you can check the Stash's breaking tool.

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by pantsguyapp** [comment]
Also, guards are visiting these blocks as if they were regular working huts.

**Comment by pantsguyapp** [comment]
Still, haven't got resolved

**Comment by pantsguyapp** [comment]
the breaking one, guards no longer visit the boxes

**Comment by Raycoms** [comment]
Even with the right tool? axe?
