### ISSUE TITLE
AI Issue, knight request house

### ISSUE THREAD

**Issue by EverettSummer** [ldtteam/minecolonies#7782]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 1.0.148-ALHPA

### Logs

- latest.log: 
https://gist.github.com/EverettSummer/9ea35325849477ba0972d0066f192d34
## Steps to reproduce the issue / details

Just reporting the AI issue. 

### Notes

my friends said their mechanic was also not working.
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Can you do an /mc colony export for me?

**Comment by EverettSummer** [comment]
Here is one of the colonies.
[colony2Export.zip](https://github.com/ldtteam/minecolonies/files/7564006/colony2Export.zip)

**Comment by Raycoms** [comment]
Fix pushed
