### ISSUE TITLE
Fletcher cycle request bug

### ISSUE THREAD

**Issue by lordfriend** [ldtteam/minecolonies#7788]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 1.0.147-ALPHA
- Structurize Version: 0.13.252-ALPHA
- Related Mods and their Versions:

## Expected behavior

Fletcher requests wool when wool is insufficient. They should request the player to fulfill the request.
## Actual behavior

But instead of request player to give white wool. they look at the recipe list, first, the cycle is wool -> string -> wool -> string -> wool ....
after remove the string -> wool recipe, they instead request wool -> gray wool -> wool -> gray wool -> wool ->gray wool -> wool ....

Please check the video
https://www.youtube.com/watch?v=8MN7ymvIzXM

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
How many fletchers did you have?

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by lordfriend** [comment]
Just confirm with my friend,he has 1 fletcher (but 3 fletcher's hut)

**Comment by EverettSummer** [comment]
Latest update:
1 fletcher's hut and 1 fletcher now. still have the issue.
the farmer also have a cyclic recipe requests. This is because he added two recipes that convert things forth and back. like hay -> wheat and wheat -> hay. I have already ask him to remove one of the recipe to avoid the issue.

But I would suggest the code should able to detect an circle within a graph. there are some algorithm that can detect that in directed graph.

**Comment by Raycoms** [comment]
We do have cycle detection, that's the weird thing.

**Comment by Raycoms** [comment]
Fix pushed
