### ISSUE TITLE
Builder level 5 still request wood or gold pickaxe

### ISSUE THREAD

**Issue by SulpherStaer** [ldtteam/minecolonies#779]
### Minecolonies version

version 1.11-0.6.3282

### Expected behavior

- The builder at level 5 requests the maximum available tool of any kind when he needs one.

### Actual behaviour

- The builder requests a pickaxe of maximum grade of Wood or Gold grade and at maximum grade.
- Deliverymen still deliver diamond (or next highest available), and the builder will accept this.

### Steps to reproduce the problem

1. Build a colony
2. Build and level the worker to level 5
3. Have its pickaxe run out, and have none available in a warehouse.
4. Observe strange and slightly confusing request.
![2017-04-07_19 06 49](https://cloud.githubusercontent.com/assets/5037244/24811302/c68329cc-1bc5-11e7-9c45-1550168996f0.png)

**Comment by Raycoms** [comment]
its at least wood or Gold. Same issue as previous he doesn't print correctly the grade he wants.

**Comment by SulpherStaer** [comment]
So will it be fixed? As the message is very confusing. Is there still an open ticket for this issue?

**Comment by Raycoms** [comment]
will be fixed altogether with the previous and similar bug

2017-04-07 14:14 GMT-03:00 sylcai <notifications@github.com>:
