### ISSUE TITLE
Mirroring function in the build tool causes perma-crash in game

### ISSUE THREAD

**Issue by pantsguyapp** [ldtteam/minecolonies#7791]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.17
- MineColonies Version: minecolonies-1.17.1-1.0.148-ALPHA
- Structurize Version: structurize-1.17.1-0.13.253-ALPHA
- Related Mods and their Versions:

## Expected behavior

I can use the build tool without any crashes

## Actual behavior

Upon right-clicking to open the build tool GUI, the game immediately crashed, I tried using the build tool again but everytime it crashes.
I have been playing with the build tool and everything worked fine in the same version, and this time it crashed.
I am playing without Optifine

[crash-2021-11-21_21.45.05-client.txt](https://github.com/ldtteam/minecolonies/files/7576458/crash-2021-11-21_21.45.05-client.txt)

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Solved
