### ISSUE TITLE
requerid structurize 0.13.252

### ISSUE THREAD

**Issue by NRBLACKRED** [ldtteam/minecolonies#7792]
### Prerequisites 

- [ x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.16.5
- MineColonies Version:minecolonies-1.0.154-ALPHA-universal
- Structurize Version:structurize-0.13.200-BETA-universal
- Related Mods and their Versions:1.12.2

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
It's a fixed version of structurize that works for a specific minecolonies verison, yes

**Comment by NRBLACKRED** [comment]
So how could I do if for now the most current is the 200, but the 252 is
requiring me

**Comment by Raycoms** [comment]
https://www.curseforge.com/minecraft/mc-mods/structurize/files/3488829

**Comment by NRBLACKRED** [comment]
Got it, thanks!
