### ISSUE TITLE
Builders requesting golden tools

### ISSUE THREAD

**Issue by KhanMaytok** [ldtteam/minecolonies#7797]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 1.0.147-ALPHA-universal
- Structurize Version: 0.13.252-ALPHA-universal

## Problem description

The builder requests tools made of gold. Golden tools have limited durability. Is there any way to allow them to use diamond tools?

### Notes or related things

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
The workers request a range of tools depending on the hut level. More detail on this on the wiki.
