### ISSUE TITLE
Fancy park wrongly requires sunflowers

### ISSUE THREAD

**Issue by SulpherStaer** [ldtteam/minecolonies#780]
### Minecolonies version

version 1.11-0.6.3282

### Expected behaviour

- The Fancy park uses rosebushes as decoration. Therefor it shouldn't request sunflowers, to then later replace them with sunflowers.

### Actual behaviour

- The Fancy park requests sunflowers, because of a wrong detection on double high rosebushes. The builder does not even place the sunflowers correctly, leaving dropped sunflowers on the ground

### Steps to reproduce the problem

1. Build a Fancy park to completion whist observing the build.

**Comment by Raycoms** [comment]
should be solved
