### ISSUE TITLE
Instant Kill Uno Reverse Card

### ISSUE THREAD

**Issue by PlatinumGM** [ldtteam/minecolonies#7801]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.17.1
- MineColonies Version: Latest
- Structurize Version: Latest
- Related Mods and their Versions: Vampirism: Latest. Silent's Gear: Latest

## Expected behavior

The barbarian/mummy dies instantly

## Actual behavior

The barbarian/mummy dies instantly, but I die instantly as well. Does have an extended area of effect, as it can happen with even a bow at medium distance. Seems to be some sort of after death thorns effect that is based on how much damage was dealt with the weapon, which in the case of ridiculous damage and instant kill weapons, will instantly kill the player as well, even when they have 3 and a half bars of health. For reference, both the bow and the sword that was used from Silent's gear are capable of enough damage to instantly kill the ender dragon, and Vampirism has a perk that if you take will deal instant death to creatures with less than 25% of their health.

## Steps to reproduce the issue

1. With the vampirism mod installed, use "/vampirism level vampirism:vampire 13" and advance down the left skill tree until you have the "Finisher" perk.
2. Get any vampirism sword meant for vampires (Heartseeker/heartstriker)
3. Spawn a colony raid
4. Attack the barbarians/mummies until you find one that produces the thorns-like effect
5. Die instantly
6. Click Respawn

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
I think this falls into "it's not a bug its a feature" category. We consider instant kill weapons as "cheating".

**Comment by someaddons** [comment]
barbs do get a thorns like effect to offset too strong modded attacks and then partially reflect that damage, this is indeed intentional.

**Comment by Hoff2567** [comment]
Damn that's dumb. Good way to get people to disable barbarians.

**Comment by Raycoms** [comment]
If you want to play in peaceful or easy mode, you can still do that. Hard mode is hard mode.

**Comment by Raycoms** [comment]
Not cheating in OP weapons to bypass all difficulty

**Comment by Hoff2567** [comment]
It has nothing to do with cheating in weapons when you play in a modded environment in which weapons regularly deal over 30 damage. It's an awful feature and directly has prejudice against a mixed modded environment. It will do nothing but teach people to entirely disable this feature of your mod or stop using it completely in modpacks or even standalone. It's a punishment for playing with more than just your mod not a feature to stop 'cheating'. 

Why are you even so concerned about how people play it anyway?

**Comment by Raycoms** [comment]
Like I said, if you want to play in easy-mode, play in easy-mode, in easy mode you can one-hit them all you want. But don't play in hard mode and add a mod that adds OP weapons and armor. That's just easy-by-proxy.

**Comment by Hoff2567** [comment]
Whatever I'll just let this part of your mod fall into obscurity like it used to be. Silly to be worrying how people play with it instead of working on the content of it. Ah well.

**Comment by Raycoms** [comment]
Yeah, we're clearly not working on the content of this mod. Silly us worrying about details and not getting anything done.

**Comment by Raycoms** [comment]
Don't wanna deal with raids, turn them off in the config.

**Comment by Hoff2567** [comment]
No need just remove the mod from modpacks. A-OK.

**Comment by PlatinumGM** [comment]
In almost all cases (And certainly all of the ones I'm thinking of) the "OP" items are locked behind a set path of progression. With the unobtanium and vibranium alloy, you have to at least gotten to the end, killed the ender dragon, and looted thousands of chests, for a chance for one piece. You can also extremely rarely mine a single ore block that takes excavating hundreds of islands to find that single piece of unobtanium, which only spawns one block of ore per vein. Not only that, if I want to use any of that in SIlent Gear, I have to farm nether bananas, pray to RNGesus that it's golden, make a chorus fruit farm, smelt an entire netherite barrel worth of chorus fruit to make popped chorus fruit, and craft all of it into glittering dust. Then, once I have the dust, I have to sit there for hours upon hours, rerolling my 3 pieces of unobtanium-vibranium alloy ingots, because it takes on average about 12 stacks of glittering dust, the highest tier of grading catalyst, to reroll the grade to (MAX), because there is no way that I'm going to use anything less than perfect materials when it's taken me all week to make a single bow. Not to mention the absurdity of trying to roll (MAX) on every other material that I put into the bow, because the sunk cost fallacy is setting in, and this much effort for a single bow had better produce some extraordinary results. Lo and behold, it was worth it. Until a barbarian raid came in at a raid size of 25 barbarians, and I die to them at least six times, making me have to turn keepinventory to true just so I can keep fighting the bullshit and at least attempt to save my citizens. I also had to build an iron farm and a pumpkin farm just so I could spawn a stack of iron golems (4 stacks of iron blocks, 1 stack of jack-o-lanterns ) so that I could reasonably protect my city from an absurd amount of barbarians, an insane amount of vampire hunters who won't stop attacking my village inside of my city because I used a totem to extend my work area so I didn't constantly burn in the sunlight, and don't even get me started on the vampire barons and regular mobs, which by the way have beefed up stats. And because I've killed so many barons, their average level that they spawn as is about 3.5, because just this week they've all been level 5, and I can swear one of the level 5 barons killed another and became level 6. There is no way that my guards can ever kill a level 3 baron, let alone a level 5 baron. And I have no hope for them even if they have the most absurd gear that I could possibly think up with Silent Gear. As for "Just turn off raids" I don't want to. I want to experience raids, which as far as I'm aware is the only way to get ancient tomes without spawning them in myself. Not only that, It's fun to go around like super man, a god in a city made out of paper, and try and take pot shots at the barbarians and hope that I'm skilled enough to not instantly kill my builder or a courier. But now I can't deal with them, because I die more than the barbarians do, and there's no way to justify my little super hero role because my only way of defeating them puts my citizens in danger, and will kill me anyway. It's not a challenge, it's a punishment for wanting to have a playstyle of minecraft where I can slog my way through hours of gameplay and every inch I take i am rewarded with making the previous steps a little bit easier, and preparing me for the challenges ahead. And by the time I beat the end dragon, I'm so powerful that I can do what I want and explore all of the mods in their fullest. If Botania was 1.17.1, I would be doing Gaia boss battles, because that has a damage limit, and will give me another challenge. I could also go to the deep dark and fight off the constant horde of wardens as I try to get those rare materials to make my armor good enough to tank the 20 damage that a warden does, just to make it a fair fight.

**Comment by PlatinumGM** [comment]
At the very least, make it an option in the config file for the raids to instantly kill you, instead of trying to police another player's minecraft experience

**Comment by Hoff2567** [comment]
You won't get a reasonable response from people who think anything above vanilla values is """cheating""", extra content be damned.

**Comment by PlatinumGM** [comment]
If I don't try to get a reasonable response, then who will? certainly none of the developers. Even though I have been kicked in the dick for 22 years by life, I still try to hold onto some sort of hope that people can change. I am addicted to having hope, which is why something as simple as mentioning politics is enough to make me depressed for the rest of the day. But I have to cling to any hope that I can, just to find more reasons to keep going.

**Comment by marchermans** [comment]
> In almost all cases (And certainly all of the ones I'm thinking of) the "OP" items are locked behind a set path of progression. With the unobtanium and vibranium alloy, you have to at least gotten to the end, killed the ender dragon, and looted thousands of chests, for a chance for one piece. You can also extremely rarely mine a single ore block that takes excavating hundreds of islands to find that single piece of unobtanium, which only spawns one block of ore per vein. Not only that, if I want to use any of that in SIlent Gear, I have to farm nether bananas, pray to RNGesus that it's golden, make a chorus fruit farm, smelt an entire netherite barrel worth of chorus fruit to make popped chorus fruit, and craft all of it into glittering dust. Then, once I have the dust, I have to sit there for hours upon hours, rerolling my 3 pieces of unobtanium-vibranium alloy ingots, because it takes on average about 12 stacks of glittering dust, the highest tier of grading catalyst, to reroll the grade to (MAX), because there is no way that I'm going to use anything less than perfect materials when it's taken me all week to make a single bow. Not to mention the absurdity of trying to roll (MAX) on every other material that I put into the bow, because the sunk cost fallacy is setting in, and this much effort for a single bow had better produce some extraordinary results. Lo and behold, it was worth it. Until a barbarian raid came in at a raid size of 25 barbarians, and I die to them at least six times, making me have to turn keepinventory to true just so I can keep fighting the bullshit and at least attempt to save my citizens. I also had to build an iron farm and a pumpkin farm just so I could spawn a stack of iron golems (4 stacks of iron blocks, 1 stack of jack-o-lanterns ) so that I could reasonably protect my city from an absurd amount of barbarians, an insane amount of vampire hunters who won't stop attacking my village inside of my city because I used a totem to extend my work area so I didn't constantly burn in the sunlight, and don't even get me started on the vampire barons and regular mobs, which by the way have beefed up stats. And because I've killed so many barons, their average level that they spawn as is about 3.5, because just this week they've all been level 5, and I can swear one of the level 5 barons killed another and became level 6. There is no way that my guards can ever kill a level 3 baron, let alone a level 5 baron. And I have no hope for them even if they have the most absurd gear that I could possibly think up with Silent Gear. As for "Just turn off raids" I don't want to. I want to experience raids, which as far as I'm aware is the only way to get ancient tomes without spawning them in myself. Not only that, It's fun to go around like super man, a god in a city made out of paper, and try and take pot shots at the barbarians and hope that I'm skilled enough to not instantly kill my builder or a courier. But now I can't deal with them, because I die more than the barbarians do, and there's no way to justify my little super hero role because my only way of defeating them puts my citizens in danger, and will kill me anyway. It's not a challenge, it's a punishment for wanting to have a playstyle of minecraft where I can slog my way through hours of gameplay and every inch I take i am rewarded with making the previous steps a little bit easier, and preparing me for the challenges ahead. And by the time I beat the end dragon, I'm so powerful that I can do what I want and explore all of the mods in their fullest. If Botania was 1.17.1, I would be doing Gaia boss battles, because that has a damage limit, and will give me another challenge. I could also go to the deep dark and fight off the constant horde of wardens as I try to get those rare materials to make my armor good enough to tank the 20 damage that a warden does, just to make it a fair fight.

This argument is skewed.
You argue that because you went through all the trouble to get the OP item in the first place, you are allowed to negate all the gameplay mechanics of other mods, because you have collected item X, is just wrong. It might work for that one particular mod, but not in a modpack.
How do you think mod author Y would feel if we just gave you that OP item directly after a couple of raids? (Equivalent time spent I would say, so say like 3 to 4 raids). You can bet your ass he will figure out a way to nerf us.
This is fairly simple: We want you to engage with the raiders, figure out creative solutions around them, and not use one hit wonders to solve your issues. The raiders are an integral part of our mod, and we explicitly do not want you to circumvent them by going to another mod that adds damage numbers against which we can not scale properly. We want you to build castles and pick terrain that suits your needs to defend the colony. That is what we envisioned for our mod when it comes to dealing with raiders. And we stand by that, we have ampel evidence that this brings the best gameplay and brings players the most joy.

Hope to have cleared up why we added this nerf to OP items, 

Greets,
Orion

**Comment by PlatinumGM** [comment]
Then you have a fundamental misunderstanding of games. I do not want to stay in pallet town catching only rattatas and pidgey for the whole game. I want to go to the next challenge, find a gardevoir, beat all of the gyms, catch all of the legendary pokemon, take on the elite 4, beat up the champion, and fill out the pokedex. you have implemented a mechanic that punishes game progression, just because you made an assumption that you're the Pinnacle of what minecraft strength should be. You've even nerfed netherite, an actual material from the base game. You are at best vermilion city in my game, and somehow youngster Joey has 6 level 1 rattatas with endeavor and a focus sash. A level 100 mewtwo, especially if you want to make it perfect, with perfect IVs, EVs, nature, and moveset, takes a lot longer than a silly minecraft bow that I ACCIDENTALLY discovered did a million damage. I didn't even purposely make the bow because it did a bunch of damage, I made it because unobtanium-vibranium alloy has indestructible, which, by the way, I could already do with the perpetual enchantment mod and a nether star, so don't even get me started. In my game, there are much more powerful enemies than the ender dragon, let alone some barbarian with the bullshit ability to instantly kill me for no valid reason.

**Comment by marchermans** [comment]
> for the whole game. I want to go to the next challenge, find a gardevoir, beat all of the gyms, catch all of the legendary pokemon, take on the elite 4, beat up the champion, and fill out the pokedex. you have implemented a mechanic that punishes game progression, just because you made an assumption that you're the Pinnacle of what minecraft strength should be. You've even nerfed netherite, an actual material from the base game. You are at best vermilion city in my game, and somehow youngster Joey has 6 level 1 rattatas with endeavor and a focus sash. A level 100 mewtwo, especially if you want to make it perfect, with perfect IVs, EVs, nature, and moveset, takes a lot longer than a silly minecraft bow that I ACCIDENTALLY discovered did a million damage. I didn't even purposely make the bow because it did a bunch of damage, I made it because unobtanium-vibranium alloy has indestructible, which, by the way, I could already do with the perpetual enchantment mod and a nether star, so don't even get me started. In my game, there are much more powerful enemies than the ender dragon, let alone some barbarian with the bullshit ability to instantly kill me for no valid reason.

The problem is that we can not scale for everything, and we have had so many complains from servers that one player does what you are saying and others don't. And that does not lead to good game play.

Now your argument that you want to rush through the gameplay is fine: Disable raids...... You don't loose anything if you want to play the way you do, well maybe ancient tomes, but those are not really relevant if you have raids disabled anyway. Maybe we should figure out a way to get it when it is disabled in the first place, but that is not related to this feature, and as such outside of scope of this topic.

Again you play your pokemon however you like, up to the degree that the developers of that game allow you to. I don't completely disagree with you that this particular aspect of the raids could be done better, but as of now, nobody has proposed a system that works in both scenarios. Especially on the long term.

Greets,

Orion

**Comment by MotionlessTrain** [comment]
> I don't completely disagree with you that this particular aspect of the raids could be done better, but as of now, nobody has proposed a system that works in both scenarios. Especially on the long term.

There are ways to limit the maximum amount of damage dealt to a mob, so that even overpowered weapons take several hits to kill it.
I believe the wither has that, as well as Botania’s Guardian of Gaia.
Maybe that is a better solution?

**Comment by marchermans** [comment]
> There are ways to limit the maximum amount of damage dealt to a mob, so that even overpowered weapons take several hits to kill it.
> I believe the wither has that, as well as Botania’s Guardian of Gaia.
> Maybe that is a better solution?

This is already implemented: The magical shield you reference to, however this only comes into play if deal more then 150% of the max HP of a barbarian at the moment. We added the thorns, because it is triggered on the player even if he uses a sword like The Sword of the Cosmos, which simply does not do any damage, but kills the entity.

**Comment by Hoff2567** [comment]
> How do you think mod author Y would feel if we just gave you that OP item directly after a couple of raids? (Equivalent time spent I would say, so say like 3 to 4 raids). You can bet your ass he will figure out a way to nerf us.

This is such an exceptionally poor take and horribly prideful. I'm quite sure any sane dev, that isn't up their own ass that their mod has to be played explicitly in the only way they see it being played, will not care if people play their mod that way.

> That is what we envisioned for our mod when it comes to dealing with raiders. And we stand by that, we have ampel evidence that this brings the best gameplay and brings players the most joy.

And here's the crux of the problem: you think there's only one 'correct' way to play the mod. It's so beyond foolish to gatekeep your own mod and will eventually destroy it. Have fun getting copied and falling away into oblivion similar to gregtech when people made tech reborn because he was so set on forcing people to play only the way he felt was right.

The best gameplay and bringing joy to players is entirely subjective. You guys should probably step outside of your echo chamber to see that other people enjoy things differently.

**Comment by Raycoms** [comment]
Bye. For this level of toxicity there is no space here.

**Comment by PlatinumGM** [comment]
I don't feel like you're getting the point. When I started the colony, I was a fledgling vampire who only just got his heartseeker sword. The raids were manageable, and I didn't exactly kill everything in one hit. But then I leveled up my vampire abilities and got a perk that allowed me to finish off non vampire mobs that had less than 25% of their health. Suddenly, without any explanation, I would die after my third hit on the barbarian, where my perk kicked in and finished him off. My progression was being punished. Earning that perk now hurt me more than it helped. All progress from that point onward would be punished by the barbarians. And as for "No good solution has been presented" I already gave you the perfect solution. Make this feature something that can be disabled. All those server owners who are complaining about "OP" items can just turn the feature on, and everyone else can turn it off. I would like to still have the occasional raid, but not if it instantly kills me every couple of barbarians. If it were a toggleable feature, I could still have raids, while also not having my level of progression punished.

**Comment by MotionlessTrain** [comment]
Another solution that could work is to train guards and mostly let them deal with the raids. You could aid them if things go south, but let them do the most work. They don't have the same problem.

**Comment by PlatinumGM** [comment]
The guards can't handle 30 barbarians, because I don't know how to train them. they die, and get replaced, and they start all over from gold armor. They also can't deal with the vampire hunters who raid the village in my colony, and even if they can, they don't kill any of them fast enough to prevent a colonist from dying

**Comment by MotionlessTrain** [comment]
1. Use a combat academy and/or archery to let them train. They skill up without getting hurt by mobs
2. Upgrade their guard towers. Only level 1 guard towers would ask for gold or leather armour. The armour they can wear is better for higher level towers.
3. I think you could handle those vampire hunters mostly yourself. That is in line with Orion's statement about the mod being balanced against itself. If you can do critical hits again non-vampires by Vampirism, those vampire hunters should be coded in such a way that those critical hits should actually work and not give negative effects on yourself.

**Comment by PlatinumGM** [comment]
Most of the time those vampire hunters happen at the same time as a barbarian raid, and there's no way for my guards to deal with them both. and I have my insane bow at this point, so my only method of helping my guards is with one of my two instant kill weapons. and even if the guards could take care of both of them by themselves, I still can't stop myself from trying to help. It's an OCD thing.

**Comment by pwaksman973** [comment]
Oh, so when the message pops "[Name] Was killed trying to kill barbarian archer", that is the system detecting the weapon you use is considered too strong?

I was wondering why the heck I was getting insta kill with full diamond set. Got it, best not use those weapons then 😂🤣.

Playing mod packs with so many options and strong boss and weapons, that it probably go in a scale that minecolonies is not expecting to. Well at least I know why the heck I'm dying hahahah gonna use a normal sword with some enchantments for raids

**Comment by Raycoms** [comment]
Tbf, a weapon that deals a lot more damage than a player can tank reeks of bad game design =D

-------- Original Message --------

**Comment by Thodor12** [comment]
As an alternative, if we detect an OP weapon, instead of reflecting the damage, could we not simply just cap the incoming damage to a set maximum? Or potentially even divide it by a multiplier depending on how high the damage is?

I.e. you can deal up to 20 damage at max, because this would be a full standard healthbar.
Above that, say you have 30 damage, you just tone it back down to 20, so it's still a great weapon, but nothing that exceeds our expectations in regards to our own difficulty scaling?

I could imagine, besides the inconvience, there are also certain unwanted cases where this is really harmful. Let's say someone was playing hardcore, and even if they are aware of this happening. They get in a groupfight and accidently hit a guard with their weapon -> game over, world gone

**Comment by pwaksman973** [comment]
Those were intended for bosses with hundreds to thosand life points and armor. 

I would suggest a more clear message.

"[Name] was killed trying to kill [npc] (Consider using a weapon more align with Vanila damage)", as it is people do get confuse about what the heck is going on.

I would agree on the cap, or at least a config, so people can do whatever they judge is "fun".

I personally didn't intended to use a op weapon, I was just not aware it was considered op, specially because it doesn't insta kill any npc, only me 🤣🤣

**Comment by turret001** [comment]
Implementing a way to toggle this off would be cool.
The progress I made in my save has turned into a punishment. I like seeing raids, I like seeing my colonists/guards fighting with the raiders but I'm not able to participate in those fights anymore just because of this.

**Comment by Thodor12** [comment]
Then don't give them OP weapons, and actually play the fight fairly.

**Comment by Raycoms** [comment]
It's not about giving someone OP weapons, it's about using one hit kill weapons on raiders while the weapons deal more damage than the armor of the wielder can handle.
