### ISSUE TITLE
Deepslate ores aren't being smelted

### ISSUE THREAD

**Issue by pantsguyapp** [ldtteam/minecolonies#7803]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.17
- MineColonies Version:
- Structurize Version:
- Related Mods and their Versions:

## Expected behavior

The deepslate versions of normal ores will be handled by the smelter

## Actual behavior

the ores aren't being recognized as smeltable

Normal ores have the Smelter tab while the deepslate ones aren't

![2021-11-24_17 35 46](https://user-images.githubusercontent.com/92203672/143250703-66d67c9a-83b1-4912-b735-7b99e50afe21.png)
![2021-11-24_17 35 51](https://user-images.githubusercontent.com/92203672/143250714-b8a7dcd1-7bee-4e6c-81cf-e93387b3609e.png)

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Known forge bug. There is a pending PR at forge for this.
