### ISSUE TITLE
Following guards don't attack the thing that the player hit when it is not on the list or is disabled.

### ISSUE THREAD

**Issue by pantsguyapp** [ldtteam/minecolonies#7806]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- MineColonies Version:
- Structurize Version:
- Related Mods and their Versions:

## Expected behavior

The guards will go after the mob even if it is not included, similar to wolves

## Actual behavior

If that mob isn't on the list, they won't attack

## Steps to reproduce the issue

1. Have some following guards
2. Punch like a cow or some animals
3. Observe
### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
That is intended behaviour, you could make a feature request for this at most.
