### ISSUE TITLE
[Suggestion] Congregation Point

### ISSUE THREAD

**Issue by SulpherStaer** [ldtteam/minecolonies#781]
### Minecolonies version

version 1.11-0.6.3282

### Expected behaviour

- Villagers without a job hang around, gather, and socialise at parks or other objects that are counted as Decorations or Parks.
- Alternatively, introduce a congregation point under waypoints, so that Points of Interest can be set by the player.

### Actual behaviour

- Villagers wander around, but there doesn't appear to be any particular pathing or objective to their wandering behaviour.

### Steps to reproduce the problem

There is no problem, so there is nothing to reproduce.

**Comment by cltnschlosser** [comment]
We can use `EntityCreature#setHomePosAndDistance(BlockPos pos, int distance)` to set the center point and distance from it. And the current wandering AI will respect that.

**Comment by Raycoms** [comment]
It would be quite interesting to have them stay around decorations the player placed for example (like parks etc) for that a congregation block the player might place would fit well so citizens try to path around a bit between those.

**Comment by SulpherStaer** [comment]
Is this still an idea, or are there way to many bug-fixes / big implements that are happening, that don't allow for this (perhaps complex) minor feature?

**Comment by Nightenom** [comment]
@sylcai I have never read this issue tbh, but can you close it if you feel satisfied with the idea in #3394?

**Comment by SulpherStaer** [comment]
https://github.com/ldtteam/minecolonies/issues/3394
