### ISSUE TITLE
Taven guest requiring Enchanted Books do not get recruited

### ISSUE THREAD

**Issue by ZenithMage** [ldtteam/minecolonies#7813]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 1.0.176-ALPHA-universal
- Structurize Version: 0.13.252-ALPHA-universal

## Problem description
My tavern spawned in a guest who I wanted to recruit and he required 14 Enchanted Books for the deal to be done. However, when I got all 14 books and I tried to turn it in to him, the window just returns to his stat screen and there is no message that he decided to stay in the colony or why he was not recruited. I purposely removed one enchanted book from my inventory and the message that I didn't have enough resources for him worked fine. I even tried swapping out an aqua affinity book that I had to a level one book (which I thought was the issue, even if I did not cause problems before) but nothing worked

### Notes or related things

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ZenithMage** [comment]
Update: Seems it is not a one-off issue in my colony. I had a few more guests that required enchanted books and all had the same issue as the first one.

**Comment by Raycoms** [comment]
Fix pushed
