### ISSUE TITLE
Guard towers can't restore state

### ISSUE THREAD

**Issue by MotionlessTrain** [ldtteam/minecolonies#7814]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 1.0.182-alpha
- Structurize Version: 1.0.252-alpha
- Related Mods and their Versions: none

## Expected behavior

The guard towers should load as expected and function properly

## Actual behavior

When clicking on any guard tower or barracks tower, it tells that the block is missing its building.
Restoring a backup doesn't change that.

## Steps to reproduce the issue

1. Load a world in 1.0.176 with guard towers and barracks towers
2. Build a guard tower or barracks tower
3. Update to 1.0.182
4. Try to access  the guard tower's gui

### Logs

- latest.log: https://gist.github.com/MotionlessTrain/78cc3febfee1aa0aa91c4778a4e29569

### Notes
I noticed it when my rallying banner wished me good luck rallying no guards. The interface showed illegal towers, so I removed them and wanted to re-add the guard towers. But the barracks tower I wanted to add turned out to be missing its building.

The log shows that deserialising the NBT went wrong. I think something changed during versions so that old NBT is not compatible with the new one.
The problems seems to be with just guard towers, as I was able to access an apiary's gui without problem

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
Was also reported on a 1.17 version as well, after updating versions to 1.0.181-alpha

**Comment by Raycoms** [comment]
Fix pushed
