### ISSUE TITLE
Can't fire or hire citizens from library

### ISSUE THREAD

**Issue by MotionlessTrain** [ldtteam/minecolonies#7815]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 1.0.191-alpha
- Structurize Version: 0.13.252-alpha
- Related Mods and their Versions: none

## Expected behavior
I can hire a cook directly from a library in the "manage worker" window

## Actual behavior
After hiring, it shows it hired a "Student: <name of citizen>" instead of "Cook: <name>".
After closing the world and reopening, the citizen turned out not to be hired as well.

![2021-11-28_22 59 22](https://user-images.githubusercontent.com/6672741/143788343-71355a12-9915-491d-849f-5be3374dbce5.png)

I tried to manually fire the same student from the library, and hire them while they were unemployed, but that didn't work either.
Looking in the log, both threw a NPE in the HireFireMessage.

## Steps to reproduce the issue

1. Hire someone at the library (if possible)
2. Try to hire them somewhere else
3. Try to fire them instead.

### Logs

After multiple relogs, trying to reproduce the issue, I managed to get the two crashes relatively close together.
(Just separated by a lot of Journeymap errors...)
At the very bottom of the log.
The error seems to be exactly the same, except for the line number in the line it throws (90 vs 94).

- latest.log: https://gist.github.com/MotionlessTrain/29769b722b5083fd9214b6c2f0af0b2a

### Notes
The firing seems to be a problem at multiple buildings. I wasn't able to fire my sifter either.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
This is also not working on 1.17 with version 1.0.192-alpha, judging from discord

**Comment by TheMerced** [comment]
latest.log including the issue on 1.17 / 1.0.192:

[https://gist.github.com/TheMerced/9a6d464f24c024a40cf0299e68ed963e](https://gist.github.com/TheMerced/9a6d464f24c024a40cf0299e68ed963e)

**Comment by MotionlessTrain** [comment]
Could it be not all assignment modules in the worker buildings are `instanceof IAssignsJob`? Cause that seems what the error is indicating.
According to commit [059cd10](https://github.com/ldtteam/minecolonies/pull/7812/commits/059cd10ea7c620edfaf645b56684ec2c8dcdc628) where the IAssignsJob interface was introduced, only the courier assignment module is implementing it.

**Comment by Raycoms** [comment]
Hope the latest commit fixes it
