### ISSUE TITLE
lumber jacks keep getting stuck   repeating action and dont do their job

### ISSUE THREAD

**Issue by hunnybunny21** [ldtteam/minecolonies#782]
minecolonies-universal-1.11-0.6.3282

lumber jacks keep getting stuck   repeating action and dont do their job
for example jumping up and down off a chest and never breaking the pattern unless you recall
but then end up stuck some where else

also an issue from previous version too
lumber jacks get stuck in farm where there is two gates to get into cow pen
they can open both to get in but are only able to open one to leave and just gget stuck 

i notice because trees grow big and no one is getting rid of them
and i followed them and saw they got stuck some where

**Comment by SulpherStaer** [comment]
It's a pathing issue. Other villagers have exactly the same issue.

**Comment by marvin-bitterlich** [comment]
closing as mc locomotion

**Comment by Kostronor** [comment]
closing as mc locomotion
