### ISSUE TITLE
Guard health change incorrectly

### ISSUE THREAD

**Issue by Night-Govery** [ldtteam/minecolonies#7821]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-1.0.193-ALPHA-universal
- Structurize Version: structurize-0.13.252-ALPHA-universal
- Related Mods and their Versions: none

When I set up the guard tower and chose someone to became an guard or ranger, his health changes correctly as the setting "guardhealthmult = xxx" , but when I quit the game and login the game again, their health reduce to the default health(not 20 health, it is 20 + their "strength" attribute I guess).
Actually, I don't know wether the health add up is correct at the first time, becase I set "guardhealthmult = 1.0" and the guard health add too much as I excepted.
The first time they become an guard(knight or ranger)
 
![image](https://user-images.githubusercontent.com/61444002/143972918-4b083563-3818-4f2b-85c2-d473011e9802.png)

I quit the game and login the game again
 
![image](https://user-images.githubusercontent.com/61444002/143972937-fd44277d-d9d8-4635-919d-8949622298e5.png)

## Steps to reproduce the issue

1.  Put the GuardTower down
2.  chose an npc to become a guard and see his health
3.  quit the game and login again, and see his health

### Logs

- latest.log:  
- https://gist.github.com/Night-Govery/0632af91500cadfa5e93768acd33228f
- crashlog:  
- no crash

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Tooney99** [comment]
i tested it myself for the past 3 weeks.. same thing, changed the health guard multiplier from 1.0 to 1.5, hire/rehire the guard, his health increased, left and rejoined the world, his hearths were back at default but, the config file changes (in this case the 1.5 increase from the default 1.0) remained, but not applied in game on the guard after the savequit. Only minecolonies-1.0.193-ALPHA and structurize-0.13.252-ALPHA alongside with Forge-36.2.19 were used in my final attempt of recreating it.

**Comment by Tooney99** [comment]
P.S: If you made the changes in the configs and re/hired the guard, after some game time his health will be changed to normal in game automatically with no need for savequiting the game.
