### ISSUE TITLE
bug warehouse and deliveryman

### ISSUE THREAD

**Issue by laboriens** [ldtteam/minecolonies#7826]
forge 1.16.5 36.2.19
minecolonies 1.0.193-ALPHA
structurize 0.13.252-ALPHA

1. 
server multiplayer
  town hall: all in manual;
assign the deliveryman to a warehouse.

2. 
restart the server

3. 
the deliveryman is no longer assigned to any warehouse and the warehouse does not have an assigned deliveryman

**Comment by Raycoms** [comment]
Fixed in the newest
