### ISSUE TITLE
Crash on divideByZero from MineColonies

### ISSUE THREAD

**Issue by Chewypuppielover** [ldtteam/minecolonies#7828]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-1.0.156-BETA-universal
- Structurize Version: structurize-0.13.252-ALPHA-universal
- Modpack: Life in the Village 2 1.28a + Occultism-1.16.5-1.21.0, Create-mc1.16.5_v0.3.2g, and lootr-1.16.5-0.0.9.28

## Problem description
After Completing a medieval dark oak tavern on server, I started to get really bad lag spikes until my game crashed.

### Notes or related things
This is the logs from my server just before the crash and the only reason I suspect that minecolonies was the issue:
[server log snippet](https://pastebin.com/VeQUiV6B)
I also should note that I'm making the Colony on the Ocean and got one colonist almost immediately, but since then no more have come. (I have had time to complete 3 buildings in that time span). When I completed the tavern, visitors came, but I still only have one resident.
Sorry if this isn't MineColonies issue

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by schafhierte204** [comment]
please manually update to the latest alpha 
also dont use one time downloads here.
log snippet: [https://gist.github.com/schafhierte204/799521c379ff27e6a3aa595d833cb6d6](https://gist.github.com/schafhierte204/799521c379ff27e6a3aa595d833cb6d6)
