### ISSUE TITLE
Click remove recipes for several times cause all recipes removed!

### ISSUE THREAD

**Issue by lordfriend** [ldtteam/minecolonies#7829]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 1.0.176-ALPHA
- Structurize Version: 0.13.252-ALPHA
- Related Mods and their Versions: Forge 36.2.9, 

## Expected behavior

No matter how many times I click the remove button, the recipes not clicked should not be removed.
## Actual behavior

When I remove 5 ~ 6 recipes in the sawmill. all 100+ recipes got removed!

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

not many useful and related logs. I stop the server immediately and going to rollback the save. Just paste here.
- latest.log: 
```
minecraft-settlers_1  | [15:46:15] [Server thread/INFO] [FTB Utilities Backups/]: Server Backup started!
minecraft-settlers_1  | [15:46:15] [Server thread/INFO] [minecraft/DedicatedServer]: Server Backup started!
minecraft-settlers_1  | [15:46:15] [Thread-2774/INFO] [FTB Utilities Backups/]: Deleting old backup: 2021-11-29-16-35-11.zip
minecraft-settlers_1  | [15:46:15] [Netty Epoll Server IO #12/ERROR] [minecraft/ArgumentTypes]: Could not serialize com.blamejared.crafttweaker.impl.commands.CTCommands$CTItemArgument@11ce430e (class com.blamejared.crafttweaker.impl.commands.CTCommands$CTItemArgument) - will not be sent to client!
minecraft-settlers_1  | [15:46:15] [Thread-2774/INFO] [FTB Utilities Backups/]: Backing up 713 files...
minecraft-settlers_1  | [15:46:15] [Thread-2774/INFO] [FTB Utilities Backups/]: Compressing 713 files...
minecraft-settlers_1  | [15:46:16] [Thread-2773/INFO] [co.ly.LycanitesMobs/]: [LycanitesMobs] [Info] [] Online familiars loaded successfully for d69c9beb-b017-4ff1-a227-18da8ba351bc.
minecraft-settlers_1  | [15:46:50] [Thread-2774/INFO] [FTB Utilities Backups/]: Done compressing in 00:35 seconds (1.0GB)!
minecraft-settlers_1  | [15:46:50] [Thread-2774/INFO] [FTB Utilities Backups/]: Created /minecraft/backups/2021-12-02-15-46-15.zip from /minecraft/world
minecraft-settlers_1  | [15:46:50] [Thread-2774/INFO] [minecraft/DedicatedServer]: Server backup done in 00:35! (1.0GB | 20.0GB)
minecraft-settlers_1  | [15:50:47] [Server thread/WARN] [minecolonies/]: Failure to remove recipe, please tell the mod authors about this
```
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
If it bothers you so much then fix it instead of ranting about this to so rudly.

**Comment by someaddons** [comment]
no appreciation for people creating mods in their freetime for your enjoyment eh?

**Comment by lordfriend** [comment]
Sorry for the emotional and offensive words. You guys are making great mods. I just have a bit frustrated.

**Comment by Raycoms** [comment]
At least in the version now it's impossible to click fast enough unintended ones.
