### ISSUE TITLE
Builder stop's working even with Chunkloader

### ISSUE THREAD

**Issue by technobrain5000** [ldtteam/minecolonies#7830]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- Forge Version: 36.2.0
- MineColonies Version: 1.0.0 Release
- Structurize Version: 0.13.219 Alpha

## Problem description

I don't really know if it's an issue or intended that way but my builder stops working immediatly after getting out of sight, even tough i installed a Chunk Loader there. I don't know why this is happening. Are the Colonists getting unloaded cause they're entities?

Thanks in advance.

### Notes or related things

Is it possible to solve this problem? Maybe even by myself?

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
It's called entity activation distance. There are certain mods/plugins which influence it.
