### ISSUE TITLE
Crash when clicking recipe menu in Forester's Hut 

### ISSUE THREAD

**Issue by Aboody1423** [ldtteam/minecolonies#7832]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.17.1
- MineColonies Version: 1.17.1-1.0.195-ALPHA
- Structurize Version:1.17.1-0.13.264-ALPHA
- Related Mods and their Versions:
- multi-piston-1.17.1-1.2.1-ALPHA
- domum_ornamentum-1.17.1-1.0.19-ALPHA-universal
- blockui-1.17.1-0.0.31-ALPHA

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log:(https://gist.github.com/Aboody1423/8f96c8ce478c6c92653464bc2cb1ae97)
- crashlog:(https://gist.github.com/Aboody1423/f0766a82525bdcf69e1ca91ecce98f1e)

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
Could you fill in the template please?

**Comment by Aboody1423** [comment]
Here you go

**Comment by Raycoms** [comment]
Can you reproduce this?

**Comment by Raycoms** [comment]
stale issue
