### ISSUE TITLE
Courier AI issue

### ISSUE THREAD

**Issue by lordfriend** [ldtteam/minecolonies#7835]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 1.0.200-ALPHA

### Logs

- latest.log: 
https://gist.github.com/lordfriend/5b676486e42b7985f7cfcde8ed0e2e22
## Steps to reproduce the issue / details
I am not sure what can cause the issue. but the situation is I'm rebuilding a lot of places in the colony, moving large chunk of blocks, and reshaping the terrains (with my tools). I tried to restart the courier, but I just saw she ran into AI issue again (the same courier). So just paste the log here.

Currently fire the courier and rehire her can solve the issue.

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by TyBraniff** [comment]
https://gist.github.com/TyBraniff/e1eff33e587942704f77df5af0e4d9ab
