### ISSUE TITLE
builder job

### ISSUE THREAD

**Issue by laboriens** [ldtteam/minecolonies#7836]
forge 1.16.5 36.2.19
minecolonies 1.0.200
structurize 0.13.252

when the builder's job requires a compass/clock and we craft then have mine in our inventory, the compass/clock adds an NBT which means that the builder's job no longer recognizes the item

**Comment by Raycoms** [comment]
That is actually a mod compatibility issue with quark. You want to turn off the clock/compass feature in quark.

**Comment by laboriens** [comment]
yes
