### ISSUE TITLE
addOfficer not working

### ISSUE THREAD

**Issue by kilian3309** [ldtteam/minecolonies#785]
[fml-server-latest.zip](https://github.com/Minecolonies/minecolonies/files/908219/fml-server-latest.zip)
version 1.10.2-0.6.3329 (last)

Expected behavior

- An op can add a player to another colony (and make it officer) by the command /mc colony addOfficer <ID> <Player>

Actual behavior

- Correct output in chat but hasn't any effect on permission

Steps to reproduce the problem

1. Setup a server with minecolonies
2. Tell a friend to make a colony 
3. Try /mc colony addOfficer <Friend's Colony ID>

**Comment by xavierh** [comment]
Could you attached your log file too it?

**Comment by kilian3309** [comment]
Yep. To get this log I try to put myself officer to the colony ID 4 and i try to break some block. I haven't the permission to break it. But i can't see (in the log) when i (try) to break them.

[fml-server-latest.zip](https://github.com/Minecolonies/minecolonies/files/908218/fml-server-latest.zip)

**Comment by Raycoms** [comment]
Officer isn't getting added to the list?

**Comment by Wissi** [comment]
Are you using any "Permission" system in the Server side? 
Are you actually /OP or require special permission node on server?

**Comment by kilian3309** [comment]
Yes and no I use permission system (PermissionEX with spongeForge) but I also test without any other plugin or mod, that change nothing.

I've also test another thing and I found the problem: When you're already in the list (as friend or other), you cannot became an officer using this command ! That's why I haven't reply to you Raycoms. The problem is a little different that I was thinking but is it a bug or is it a non-implemented feature ?

**Comment by Raycoms** [comment]
Okay then its a known "bug" aka not implemented feature.
We're working on that already
