### ISSUE TITLE
Latest update crashing on launch

### ISSUE THREAD

**Issue by Estyria** [ldtteam/minecolonies#7850]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.17.1
- MineColonies Version: 1.17.1-1.0.227
- Structurize Version: 1.17.1-0.13.279

## Problem description

Minecraft fails to launch on latest version of Minecolonies. Immediate crash with crash log.

### Notes or related things

I haven't been able to launch either of the newest versions but will focus on this latest one because I want the fix for the farmer. Attempting to attach crash log now. Apologies if I don't get this right, I haven't used github before.
https://gist.github.com/Estyria/71e8999ff34663b4948f45c5b9fb5d0e

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Thanks for reporting this, digging into it a bit.

**Comment by Raycoms** [comment]
Should've been solved for a while
