### ISSUE TITLE
[1.16.5 and up feature request] Colinization, Expand your Colony!

### ISSUE THREAD

**Issue by Shibva** [ldtteam/minecolonies#7851]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

This mod is gread and its nice to see its still a WIP, but heres a thought, what if you want to expand your colonly to more ares, thats where this idea comes in, if you manage to prefrom enough research, you could create new colonies that are connected to yours wtihout the need of having to start over again. 

### Notes or related things

This can allow for cross-dmentional colinies to be established for you mighty colonly! certain enchantmets can be made from doing research that grants special things

End Research will allow for a collony outpost to be setup in the end (Great for mods that expand the end to a great amount) But how will they get there if you want your colonies to transevere between one another? 

shipments, trans dimentonal methods

by completeing certain research that extends and stems off unlocking the secrets to the end, a possable means for transport can be made between dimetnons, wtih upgrades such as linking storage huts in diffrent colony outpost you made to it, and even further down the line produce the means to even eliminat the needs of couriers!, thsese would be end-game developments on the reserch side and while costly to make, its also costly to research as a large amount of ellusive items woudl be needed, by unlocking the secrets of the end, your colonly could benefit even more so

Dimentional based combat upgrades: Endermen are a threat to the towns folk, but what if there was a reacersh notice that can protect citizens from eraging the ender-mennace and guards wwtih mage like abilites to not only foritfy the dimentonal threats but to also ward themself of any of it (such as preventing enderman form useing their frustrating teleport attacikn tatics if a guard attacks them)

sorry for all the spelling errors, I love this mod and I wish to see more things that increse the aspect of colinization in the form of dimentonal adventure to come, it could aos come into play wtih new ideas such as guards that are warlocks or witches
---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Wrong repository for feature requests =)
