### ISSUE TITLE
[1.16.5 version request] Bump up the version for structuralize for newer version to be used wtih minecolonies 

### ISSUE THREAD

**Issue by Shibva** [ldtteam/minecolonies#7852]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: currently irrelivant
- Structurize Version: at what its set to work on curreny

## Problem description

its been some time now but a newer veersion of structurlize that has been made to work with this mod has been out for some time, only problem is that if you update this version that minecolonies will prevent the game from runings, specifiying you dont have the right instance

sollution: bump up the version to run on the newer instances of Structurlize! mod, if their are any issues that may be involded with doing this, please respond to this request, because if their is Im curious to what might the reasons may be

### Notes or related things

none, really
---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
We know.
