### ISSUE TITLE
1.16.5 version is broken on Curseforge

### ISSUE THREAD

**Issue by ModernGamingWorld** [ldtteam/minecolonies#7855]
every time you update 1.16.5 version via the Curseforge Launcher is Installing BlockUi-1.17.1, Domum 1.17.1, and Multi Piston 1.18, This should not be happening as this is a 1.16.5 version of Minecolonies, not anything newer 

Herres Proof that the 1.16.5 version is broken on curse forge, It's showing your Forcing a Required Dependency of 1.17 and 1.18 mods on the 1.16 builds

https://i.imgur.com/C4EUZ6u.png

**Comment by Raycoms** [comment]
adjusted

**Comment by choombdev** [comment]
Just downloaded the latest vresion (1.16.5-1.0.296-BETA) and the same issue persists, just letting you know!
