### ISSUE TITLE
bug de compatibilité

### ISSUE THREAD

**Issue by Zoryoto** [ldtteam/minecolonies#7856]
bonjour j'ai un plus tôt gros problème.

quand je sélectionne les modes (de la 1.17.1) pour mon monde sa me dit que il ne sont pas compatible et que il sont compatible pour une autre version .
donc j'essayer avec une autre version et sa me dit que il sont compatible avec une version plus récente

**Comment by Raycoms** [comment]
a) Fill in the template
b) we don't speak french, please at least try using google translate.
