### ISSUE TITLE
Clipboard is being spammed with irrelevant requests

### ISSUE THREAD

**Issue by chantrykomori** [ldtteam/minecolonies#7861]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-1.16.5-1.0.311-BETA.jar
- Structurize Version: structurize-0.13.252-ALPHA-universal.jar
- Related Mods and their Versions:

## Expected behavior
The clipboard shows which requests need to be fulfilled by the player, and not other colony requests that do not require the player's input (such as sawmill/stonemason products).

## Actual behavior
The clipboard shows every single step in a crafting recipe. For example, if the forester needs an iron axe, it will display in the clipboard that the forester needs an axe, which will be crafted by the blacksmith once they receive 3 iron ingots (not in the warehouse, should be the only thing actually requested) and two sticks (crafted by the sawmill) and two wood planks (also by the sawmill) and one wood log (also requested by the sawmill), Of the five requests shown on the clipboard, only one request is actually relevant/fulfillable by the player - the iron ingots. This makes the clipboard useless, because you have to scroll through pages and pages of irrelevant information.

![Screenshot_753](https://user-images.githubusercontent.com/16926135/146639954-f45b71eb-eeec-4b35-ba4e-3138012ed610.png)
![Screenshot_754](https://user-images.githubusercontent.com/16926135/146639956-b6b44ea3-f73c-4985-86c2-6f605034b78f.png)
![Screenshot_755](https://user-images.githubusercontent.com/16926135/146639957-fe56d324-2285-48b8-a34e-ea4622c48bb1.png)

## Steps to reproduce the issue

1. Assign a clipboard to a town hall
2. Give crafting huts multiple recipes
3. Look at the clipboard

### Logs

- latest.log: https://gist.github.com/chantrykomori/ef77998612f89a7f88eab9c4b65956ff

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
This is correct, it shows the full tree, if one of the ingredients is missing.
I.e. the system lacks nether quartz and cobblestone.

**Comment by chantrykomori** [comment]
> This is correct, it shows the full tree, if one of the ingredients is missing. I.e. the system lacks nether quartz and cobblestone.

If this is the intended behavior, how are you supposed to see at a glance what you need to send to the warehouse?

**Comment by Raycoms** [comment]
To be honest, that is the point. Any. You can either give quartz and cobblestone, or actually diorite.
