### ISSUE TITLE
cook not working

### ISSUE THREAD

**Issue by David041706** [ldtteam/minecolonies#7862]
Hi,
My cook isn't working. He asks me to choose fuel for him but I don't see any green arrows or anything to choose the fuel. Please, help me, I can't play without my cook. Here are some photos.

![Minecraft_ 1 17 1 - Multiplayer (3rd-party Server) 2021-12-18 11_12_52](https://user-images.githubusercontent.com/96345613/146647888-ec1d1af8-9743-45d6-aa39-db2d5d76ef91.png)
![Minecraft_ 1 17 1 - Multiplayer (3rd-party Server) 2021-12-18 11_12_57](https://user-images.githubusercontent.com/96345613/146647889-f2f5b3a2-40d5-4c4b-ba2b-5c82a02b552c.png)

**Comment by David041706** [comment]
By the way, It's level 1.

**Comment by someaddons** [comment]
reopen a new issue and fill out the template please

**Comment by David041706** [comment]
what do you mean by template?

**Comment by someaddons** [comment]
the template you see when clicking new bug report
