### ISSUE TITLE
can't choose the fuel for my cook (1.17.1)

### ISSUE THREAD

**Issue by David041706** [ldtteam/minecolonies#7863]
### Prerequisites 

- [ x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.17.1
- MineColonies Version:minecolonies-1.17.1-1.0.255-ALPHA
- Structurize Version:structurize-1.17.1-0.13.279-ALPHA
- Related Mods and their Versions:balm-1.8.0+0  blockui-1.17.1-0.0.31-ALPHA  cc-tweaked-1.17.1-1.99.1 Colony4ComputerCraft-1.17.1-2.1.1  domum_ornamentum-1.17.1-1.0.9-ALPHA-universal  endremastered-forge-1.17.1-R4.1.2   jei-1.17.1-8.3.0.39  multi-piston-1.17.1-1.2.1-ALPHA  OptiFine_1.17.1_HD_U_H1  waystones-8.2.0+0  Xaeros_Minimap_21.22.3_Forge_1.17.1

## Expected behavior
 : I'd want to be able to choose the kind of fuel my cook is going to use.

## Actual behavior
: I can't choose the kind of fuel. Some forums say there should be a green arrow  to go to choose the fuel but I dont see any.

![Minecraft_ 1 17 1 - Multiplayer (3rd-party Server) 2021-12-18 11_12_52](https://user-images.githubusercontent.com/96345613/146648307-a7f3006a-a89c-41fc-9323-865790106627.png)
![Minecraft_ 1 17 1 - Multiplayer (3rd-party Server) 2021-12-18 11_12_57](https://user-images.githubusercontent.com/96345613/146648310-6fcabb19-c9b4-4905-a6a7-bc72dfde73e6.png)
![Minecraft_ 1 17 1 - Multiplayer (3rd-party Server) 2021-12-18 11_35_03](https://user-images.githubusercontent.com/96345613/146648660-eab29cc2-44ba-4f5d-82d3-7807406d8e1c.png)
![Minecraft_ 1 17 1 - Multiplayer (3rd-party Server) 2021-12-18 11_35_23](https://user-images.githubusercontent.com/96345613/146648661-07fa30e0-fdc8-4917-9fe1-136ae91e86e4.png)

## Steps to reproduce the issue

1. : build a cook level 1 
2.  click on the cook block
3.  try to find the area to choose the kind of fuel ( I don't think you'll find it)

### Logs

- latest.log: : I cant find it. My server is on aternos. Tell me where to find it and I will give it to you.
- crashlog: : I cant find it. My server is on aternos.  Tell me where to find it and I will give it to you.

### Notes
: I tried to level it up but didn't change anything.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
@uecasm any idea what is up now?

**Comment by David041706** [comment]
nvm, I just restarted my game and it fixed it. Thanks again.

**Comment by uecasm** [comment]
> @uecasm any idea what is up now?

Not sure.  It's been reported by a few people on a few versions but I can't reproduce it in dev (even on a server).  The common threads are playing on a server, and that opening an SP world before connecting to the server fixes it (and likely so does disconnecting and reconnecting).  So it is _probably_ something funky with the order of events firing causing the CompatibilityManager sync to client to fail, possibly disturbed by some other mod, but it's hard to debug without more info or a reliable reproduction method.
