### ISSUE TITLE
Using Hut Crafting Tables = MASSIVE material duplication

### ISSUE THREAD

**Issue by ArkavianX** [ldtteam/minecolonies#7867]
### Prerequisites 

- [ x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:  1.16.5 ATM 6 Pack
- MineColonies Version:  ATM 6 Pack 
- Structurize Version:  ATM 6 Pack
- Related Mods and their Versions: ATM 6 Pack Latest

## Expected behavior
Build a tool 

## Actual behavior
Massive Duplication

## Steps to reproduce the issue
1. Go to a hut that has a crafting table,
2. Build a batch of vanilla tools. If more tools than your inventory can handle the remaining unused materials will bug out with insane numbers.  

- latest.log: 
- crashlog: 

### Notes
Was trying to restock the builders tool assortment, maxed out my own inventory on tools and now I have a million sticks

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Not sure I understand this fully. It's in a vanilla crafting table inside a MineColonies building?

**Comment by ArkavianX** [comment]
Yes, Builders hut

**Comment by Raycoms** [comment]
But a vanilla crafting table? This doesn't happen with normal vanilla tables?

Or do you mean the teaching interface?

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by ArkavianX** [comment]
1. When I go to the vanilla crafting table in the builders hut with other stuff in my inventory. 
2. I try to restock the builder on tools, exceed my inventory with some parts still on the crafting table. 
3. The part count in the crafting table shoots up to 5+ digit quantities.
4. If you leave the table, you get massive pile mess of parts, if one the colonists pick it up they get an item with Dank null amount of items.

**Comment by Raycoms** [comment]
Doesn't this also happen in any other crafting table in the world?

**Comment by ArkavianX** [comment]
Ok, I think this bug is a conflict with the Dank Storage mod, a similar bug happens with T.Con crafting table as it tries to connect to the Dank Storage dock and didnt have to craft anything. 

At the time I had a L5 Dank Null in my inventory

**Comment by Raycoms** [comment]
That's that probably. It tries to access nearby inventories and creates a mess. Can you report that to them please and link it to this?

**Comment by Random832** [comment]
Out of curiosity, were you in survival or creative mode when you tested this? When testing with Tinkers Construct I got a client inventory desync that could manifest in creative mode as an apparent dupe glitch.

**Comment by ArkavianX** [comment]
Was in survival
