### ISSUE TITLE
Farmer destroys farmland on harvest

### ISSUE THREAD

**Issue by SulpherStaer** [ldtteam/minecolonies#787]
### Minecolonies version

version 1.11-0.6.3360

### Expected behavior

- When harvesting fully grown crops, the farmer leaves behind tilled earth, or replants crops when he has enough seeds available right away. (The same way default minecraft villagers do)
The reason for this is, when a MineColony Village is built ontop of a Minecraft Village, both types of farmer, minecolony, and default, can both use the fields to harvest and plant crops, leading to a bigger village, and greater immersion.

### Actual behaviour

- When harvesting crops, (and not always waiting for them to be fully grown), the farmer leaves behind dirt. He also harvests said crop with a hoe. So... if he's not using it, why does he have it equipped during harvest?

### Steps to reproduce the problem

1. Build a colony.
2. Build a farm, and upgrade to level 5
3. Build 5 normal fields
4. Observe farmer behaviour.

**Comment by Raycoms** [comment]
Already reported somewhere.

**Comment by SulpherStaer** [comment]
I looked for farmer. Please give the report number before closing.

**Comment by SulpherStaer** [comment]
Ok, so I found the tickets, #301 #722 and #631 

But it seems that it doesn't reply about the farmland / tilled earth not being replaced. Only that it first harvests, and then replants.

I am talking about specifically the farmland remaining tilled, instead of being destroyed and turned into dirt.
