### ISSUE TITLE
Crash when using cardboard boxes from mekanism on servers (1.16)

### ISSUE THREAD

**Issue by mzuletal** [ldtteam/minecolonies#7873]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 1.0.311-BETA
- Structurize Version: 0.13.252-ALPHA-universal
- Related Mods and their Versions: Mekanism-1.16.5-10.1.0.455

## Expected behavior
Using cardboard box on any mob spawner and being replaced the spawner with the cardboard box

## Actual behavior
When attempting to use a cardbaord box on a mob spawner, game instantly crashes

## Steps to reproduce the issue

1. Right click a mob spawner with a cardboard box

### Logs

- crashlog: https://gist.github.com/mzuletal/24a1d3fca437950a033cea4f5c55892d

### Notes
This started happening after updating to mekanism v10.1 that adds a blockbreak event when using a cardboard box in any block.

---

**Comment by MotionlessTrain** [comment]
Was that spawner inside of a colony by chance?

**Comment by mzuletal** [comment]
Nope
