### ISSUE TITLE
Feature Request. Move/Relocate/Style change any Building.

### ISSUE THREAD

**Issue by Wissi** [ldtteam/minecolonies#788]
I see that a couple great features would be for the player to have the option to "move" a building from one place to another. That is a needed option for the mod, since Towns grow and sometimes planning requires relocation of buildings without losing their level or starting over.

Perhaps have an option in the Hut GUI for "move/relocate" building.
Then have an option in the "Building Wand" for the "Move/relocate".
Once player "commits", the builder will tear down/remove the building and start the build process in the new location with the current level that the building had.

Also a Button to be able to change the "Style" of the building at the current level.
If already "Wooden" and level 3 - Player decides to have the "Stone/Cobble/Sandstone" or other future style instead. Builder would tear down and replace the Wooden style and rebuild (at same level 3) with desired style change.

**Comment by xavierh** [comment]
@wissi  moving, change location and changing style will probably very easy to implement. Cleaning the old area could be left to the player to do ?

**Comment by Wissi** [comment]
@xavierh Sure, the player could "clean up" the old area to his liking.
Or the builder could fill in the floor w/native material: dirt, sand, etc. as to leave a flat surface leveled with the surrounding area?

**Comment by Raycoms** [comment]
he should then fill everything under the chest with floor material and
above with air?

The only moving would be easy code, the problem is the clearing of the
previous area.
We would've to create a whole job for that one.

2017-04-10 13:55 GMT-03:00 Wissi <notifications@github.com>:

**Comment by xavierh** [comment]
The way I see it, it should be easy for the player to scan an "air" area and ask his builder to "build" it. 
Sound like unnecessary dev's work where time can be spend better somewhere else.

**Comment by Raycoms** [comment]
I agree.

2017-04-10 14:45 GMT-03:00 xavierh <notifications@github.com>:

**Comment by Wissi** [comment]
sssoooo... a quick, easy, fast do-able request? ;-)

**Comment by Wissi** [comment]
The removal process in itself isn't much of an issue (player side) if anything is left there or needs attention from player... no big deal. 
As long as a building can be "removed" and the status is saved to be able to be built again somewhere else as the level it was or different material/style as well, that is what will make any player happy. IMO
sssoo.. easy, fast, do-able request?    ;-)

**Comment by WORMSS** [comment]
I would expect there to be holes in the ground if a builder moves the building. 
At the moment, if ask the builder to build something, he digs holes in the ground and fills will cobble (Foundations).
If I ask him to move the house.. 
I would expect him to remove the current house blocks (from top to bottom),, Place them in his inventory/builders hut inventory and then what would be left is the holes where the foundations used to be.

And then use all the blocks from his inventories to re-build the house in the new location.

Yes, there could start to be inventory issues, and that should be an "expected consequence" of trying to move the building.

I like the idea of having to right click the building's block with the builders wand to bring up the gui to move the house.

**Comment by ghost** [comment]
Rotating buildings would be neat, too.

**Comment by JackOfSpade** [comment]
Was this ever implemented or no?

**Comment by Raycoms** [comment]
yes
