### ISSUE TITLE
Cannot place anything but well after server restart

### ISSUE THREAD

**Issue by bvierra** [ldtteam/minecolonies#7881]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.18.1
- MineColonies Version: minecolonies-1.18.1-1.0.278-RELEASE
- Structurize Version: structurize-1.18.1-1.0.319-BETA

## Problem description
Multiple issues appeared after a server restart:

- No colony owners could place any buildings other than the well under decorations. We attempted to change ownership via the /mc commands to a different player and then back (neither could ever place anything else), restore all colonies from backup, verified that the required items were in inventory, as well as replacing the builders tool.

- A player without a colony could not place the starting block (either ship or land version) with a CTD upon trying. [Server Log](https://gist.github.com/bvierra/5787cb15269dd50fba0b43f712f2690f) [CTD Client Log](https://gist.github.com/bvierra/438b083f0affb7d4dafb66ff7cb24062)

Shutting down the server, deleting the toml config files for both structurize and for minecraft colonies on the server and then restarting the server (letting them be recreated) fixed the issue. The only diff was for the minecolonies-server.toml is in the following [unified diff](https://gist.github.com/bvierra/8798495f05dc0b9452649f4f87c5f5c6).

### Notes or related things
Please advise if there is anything else I can provide.

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Could you give me the server startup log from that time? I believe sth broke during startup that didn't initiate the structurize loading.

The dif seems small, but sometimes forge configs got weird whitespace issues.

**Comment by bvierra** [comment]
So sorry, I forget server log had IP/UUID's in it and I had removed it for that reason. I have re uploaded it [here](https://gist.github.com/bvierra/5787cb15269dd50fba0b43f712f2690f) and have fixed link in bug report - This version has UUID's and IP's replaced with <redacted> if for some reason you need a log without these redactions I will be happy to send to you so it is not public.

**Comment by bvierra** [comment]
> The dif seems small, but sometimes forge configs got weird whitespace issues.

Correct, the diff was from our version of the config that did not work and then the new config created after deleting it (we only had a few small changes)
