### ISSUE TITLE
Updating to Alpha 1.0.322 (MC 1.17.1) crashes miner block.

### ISSUE THREAD

**Issue by Knaxia** [ldtteam/minecolonies#7883]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.17.1 (Forge 37.1.1)
- MineColonies Version: minecolonies-1.17.1-1.0.322-ALPHA (updating from minecolonies-1.17.1-1.0.312-BETA)
- Structurize Version: structurize-1.17.1-1.0.311-BETA
- Related Mods and their Versions: [None that I can think of]

## Expected behavior
No crash?

## Actual behavior
I just upgraded my server to 322 Alpha and as I launched the server, it threw me an exception for my mine block and that it cannot be recovered. I tried to load a backup of my world but it always does the same. Restarting the server doesn't solve it, trying to interact with the mine block just keeps saying to restart or load a backup.

I do have daily backups so I reverted back to 312-BETA and works fine that way, but that means I cannot update and fear for future updates. My mine is already large and level 3 and I'm not sure if trying to rebuild the mine on top of it will create any additional issue.

## Steps to reproduce the issue

1. Load or make a colony in 1.17.1 with 312-BETA
2. Have a mine
3. Update to 322-ALPHA
4. Start the server and check logs

### Logs

- latest.log: [latest.log](https://github.com/ldtteam/minecolonies/files/7796678/latest.log)
- crashlog: No crash, server keeps running

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Meh 323 wasn't published. Pushing a new build out right now
