### ISSUE TITLE
Quarry etc.

### ISSUE THREAD

**Issue by pmardle** [ldtteam/minecolonies#789]
Can we please delete the Quarry and other non implemented buildings out of the mod for now..  The number of times I get told/asked "The quarry doesn't work, please help me" or similar is becoming ridiculous.  I know we have stated "please dont use them for now"etc. but people just dont read/listen to that :)

This includes from the Creative menu etc.

Adding them back in later is a very minor task. 

Thanks,

**Comment by xavierh** [comment]
I thought they were only available when enabling the development option?

**Comment by IchigoGames** [comment]
that and the Quarry can crash the server its on

**Comment by pmardle** [comment]
Well people are using them, and asking me why they arent working..

Can we just nuke it for now.. :)

**Comment by neadlak** [comment]
I also noticed some buildings with no recipes - so I don't spawn them using op/creative and JEI.

My vote: Hide it behind developer mode; if people are enabling dev mode and don't understand what do... that's on them.

**Comment by marvin-bitterlich** [comment]
@xavierh can you check if this still needs restriction?

**Comment by xavierh** [comment]
Will do it later today or tomorrow
