### ISSUE TITLE
Rendering Issue - crash

### ISSUE THREAD

**Issue by JavelinD** [ldtteam/minecolonies#7895]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.18.1
- MineColonies Version: 1.0.328-ALPHA
- Structurize Version: 1.0.319-BETA
- Related Mods and their Versions: ATM 7 Modpack versions 0.2.15 - 0.2.19

## Expected behavior
not crashing to desktop on loading into a running colony

## Steps to reproduce the issue

Simply loading into the world or moving into the chunks where the issue occurs

1. 
2. 
3. 

### Logs

- latest.log: https://gist.github.com/JavelinD/78e12360954fd842b69f47d968e6f533
- crashlog: https://gist.github.com/JavelinD/41c2f5bd559ee7f1e95baa2b02f5fbe4

### Notes

Sorry for the lack of details here I don't really know what to write about a instant crash to desktop

In the colony that my friends and I have built up we're using mainly Medieval Oak and Asian themes with one or two normal Dark Oak or Nordic themed buildings mixed in. Most are levels 1 through 3.

Hopefully this helps in some way. Absolutely love Mine Colonies <3

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
It seems like there is a banner pattern which is crashing when it gets rendered.

**Comment by MotionlessTrain** [comment]
Someone else playing ATM7 who had the same problem seemed to solve it by disabling Alex's Mobs. So it could actually be a problem on their side.

**Comment by JavelinD** [comment]
good to know i'll give that a shot and report back

**Comment by JavelinD** [comment]
After disabling Alex's Mobs and checking around town for a bit I looked at the town hall banner editor and noticed it looked like there were fewer options. went back into atm7 0.2.13 and doubled checked there. There were more options with Alex's Mobs enabled. but selecting any of those options as a banner would crash the game.

**Comment by MotionlessTrain** [comment]
Then the banner patterns they add are not made properly and crash when used in a banner.
It seems like it is already reported to Alex's mobs:
https://github.com/Alex-the-666/AlexsMobs/issues/780

**Comment by Raycoms** [comment]
Okay, will close here then. the problem is at alex's mobs.
