### ISSUE TITLE
Blacksmith doesn't proceed with requests from other citizen from the colony

### ISSUE THREAD

**Issue by Tellurnirn** [ldtteam/minecolonies#7899]
Minecolonies

Version: Minecolonies-1.18.1-1.0.278 on Server

Expected behavior

    When workers request a tool, the blacksmith should start make the tool. We also placed postboxes and stash ones, in order to place request or let citizen do it too, as we read it was a possible solution amongst fixed issues threads on here: https://github.com/ldtteam/minecolonies/issues/3534
  

Actual behaviour

    The blacksmith does nothing even though she has all the needed recipes and the material in her shop. It is only possible to type words in a box on the post boxes menu, it does not lead anywhere and nothing changes in the display doing so.

Addendum:

Don't know if it is related: but the list of items, to be selected in the minimum stock page after the player clicks on ADD, does not display anything but air in all the buildings. Hence nothing can be added to the list.

Thanks in advance

**Comment by Raycoms** [comment]
Any startup logs?

**Comment by Tellurnirn** [comment]
Is there anything that should be deleted from the logs so what I share here can't be used to access the server/mess with it?

**Comment by Raycoms** [comment]
Not that I am aware of.

**Comment by Tellurnirn** [comment]
Ok actually, the issue evolved. Somehow restarting the server every single time the display fails to show recipes works.
It's really time consuming but does the job.

So now the new problem is about the miner's hut block that simply can't find the framed cobblestone or the frame spruce plank items for the player to add to the minimal stock list. Typing their name in the search gives no results even though the miner says they can't work any further if they don't get these blocks. Blocks which totally exist as they're easy to find in creative mode...

Any ideas how to fix this?
