### ISSUE TITLE
Implement the baker [$10 awarded]

### ISSUE THREAD

**Issue by nojo121** [ldtteam/minecolonies#790]
We should implement the baker.
He's very useful :)

**Comment by pmardle** [comment]
GUess I need to get his buildings built then :P

**Comment by nojo121** [comment]
@pmardle already done :)

**Comment by marvin-bitterlich** [comment]
LGTM @nojo121 😉

**Comment by nojo121** [comment]
@Kostronor nice 👍

**Comment by pmardle** [comment]
Buildings for all 3 Styles (Wooden, Stone and Desert?)

**Comment by nojo121** [comment]
@pmardle  yep ^^

**Comment by pmardle** [comment]
Cool.. Let me know when it's ready for release and i'll do a video :)

**Comment by kedamono** [comment]
If you need an alternate wood bakery hut, here's one. :-)
[Alt_Bakery_Wood.zip](https://github.com/Minecolonies/minecolonies/files/910936/Alt_Bakery_Wood.zip)

**Comment by Wissi** [comment]
Is there a Sandstone version for it? To complement the already Sandstone pack?

**Comment by kedamono** [comment]
I haven't made one, and it would have to be in keeping with the Sandstone design aesthetics. I could come up with one, I will have to figure a good look for it first.

**Comment by kedamono** [comment]
As requested, here's a sandstone alternate version.
[Alt_Bakery_Sand.zip](https://github.com/Minecolonies/minecolonies/files/911637/Alt_Bakery_Sand.zip)

**Comment by nojo121** [comment]
when the building competition is over, I'll implement the baker :)

**Comment by kedamono** [comment]
Pictures of these builds are in the forums. If you want to put them in the contest world, you may want to use another plot, my plot is getting full.

**Comment by Raycoms** [comment]
I did that already
