### ISSUE TITLE
Having both the smeltery and stone smeltery in your inventory when placing the smeltery places a malfunctioning stone smeltery

### ISSUE THREAD

**Issue by WrinLangford** [ldtteam/minecolonies#7900]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.18.1
- MineColonies Version: 1.0.328-ALPHA
- Structurize Version: 1.0.319-BETA
- Related Mods and their Versions:

## Expected behavior
When placing a smeltery with multiple buildings in your inventory, a smeltery is placed

## Actual behavior
When attempting to place a smeltery with both a smeltery and a stone smeltery in your inventory, it shows the smeltery blueprint, but when placed converts the stone smeltery item to a smeltery. However, the construction tape size is set as a stone smeltery, and previewing the building by placing another building nearby will show a stone smeltery. After seeing this preview, interacting with the building will give an error about the building not being saved, and asking the user to restart.

## Steps to reproduce the issue

1. Create a building tool, stone smeltery and smeltery.
2. Using the building tool, attempt to place the smeltery. Tested using Acacia, Asian and Fortress.
3. Place the smeltery as normal.
4. Attempt to place another building nearby, the preview of the previous building shows the stone smeltery
5. Cancel the placement of second building
6. Attempt to interact with the original smeltery, see error.

### Logs

I'm unable to attach logs as I'm playing on a multiplayer server

### Notes
Shindria was able to replicate.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
>  it shows the smeltery blueprint, but when placed converts the stone smeltery item to a smeltery.

Just double checking that - when I place the smeltery, it shows the preview of the smeltery, but when I hit the check mark, it ~~converts the smeltery block into the stone smeltery block, and~~ removes the stone smeltery block from my inventory

Stone smeltery places fine with both in inventory, just the regular smeltery messes up.

*edits* nope, sorry, when I hit the check mark the smeltery blocks stays there visually, but the builders tape changes to the stone smeltery building, and the stone smeltery block disappears from my inventory

**Comment by Raycoms** [comment]
solved
