### ISSUE TITLE
Colony flag banner not show flag when placed by builders

### ISSUE THREAD

**Issue by EverettSummer** [ldtteam/minecolonies#7901]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 1.16.5-1.0.327-ALPHA
- Structurize Version: 0.13.252-ALPHA
- Related Mods and their Versions:

## Expected behavior

Colony Flag Banner placed by builder should be able to show colony flag even in user defined shematics 

## Actual behavior

I made a fancy wall from the official one replace the banner with colony flag banner in SP creative mode then upload it to server's structurize/schematics/walls/
When I let my builder build it the flag is still white.

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

I remember this bug has been fixed before.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Couldn't reproduce in the latest at least
