### ISSUE TITLE
Build order outside of colony for town hall placement

### ISSUE THREAD

**Issue by YzXupoo** [ldtteam/minecolonies#7902]
I am just doing the second step after the supplycamp of putting the town hall down using the wand and the game just says, "The build order for at x: , z: is outside of the colony and this cannot be built."

**Comment by Raycoms** [comment]
please fill in the whole info. Also do you have another colony already?

**Comment by YzXupoo** [comment]
I left all the info it gave me. But I figured out what the issue was. It
was defaulting to place a water fountain instead of the townhall. I had to
just switch it from decorations to townhall. I apologize for being so dumb
about it.
