### ISSUE TITLE
The server always crashes

### ISSUE THREAD

**Issue by TVince0** [ldtteam/minecolonies#7903]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.10.2
- MineColonies Version: 0.9.7587
- Structurize Version: -

## Problem description
When i'm running a server it always crashes and i have got no clue why, only that is related to minecolonies.

### Notes or related things

I'm running the Sprout - Explore for More modpack

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Unfortunately we do not support 1.10.2 anymore. You will have to find a workaround yourself for this.
