### ISSUE TITLE
Cannot fulfill Builder gravel request - Lvl2 Builder Hut upgrade

### ISSUE THREAD

**Issue by JRA28** [ldtteam/minecolonies#7908]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.18.1
- MineColonies Version: 1.18.1-1.0.328-ALPHA

### Logs

- Is there a way I can upload/ share this privately - It contains my name within the file structures which I do not want publically available. 

## Steps to reproduce the issue / details

While trying to upgrade the 'medieval oak alternative' Builder Hut to Level 2, the builder requests 6 gravel blocks.
Despite adding 6 blocks to both the Builder's inventory, the Builder Hut inventory and also placing 6 gravel blocks down randomly (in the hope that the builder would break and pick up), the request can't be fulfilled. Regardless of any combination of these, the request was not fulfilled and I never once got the fulfil button to click on the clipboard or builder's GUI.

I created another builder hut item and used the build wand to place the 'invisible' preview of the Level 2 structure and I could not see any gravel blocks. Is the builder falsely requesting the gravel?

Cancelling the Builder's request does not allow them to progress, instead they re-enter the hut and re-request.

### Notes

The issue remains after restarting the program.

I am using All The Mods 7 0.2.13 mod pack (with several additional mods installed) with the issue persisting on Forge 39.0.9 and 39.0.10.

Thank you in advance!
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
I double checked on this. The gravel is placed in the basement of the hut. It works quite fine for me, so I'm a bit confused

**Comment by Raycoms** [comment]
Stale
