### ISSUE TITLE
Minecolonies cannot be used with data generators

### ISSUE THREAD

**Issue by SirEndii** [ldtteam/minecolonies#7909]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.18.1
- MineColonies Version: 1.18.1-1.0.328-ALPHA
- Structurize Version: 1.18.1-1.0.319-BETA
- Related Mods and their Versions:

## Expected behavior
I should be able to run `runData` without issues from minecolonies.

## Actual behavior

The mod does not work with data generators. I don't use the API version as I need classes from the actual mod.

## Steps to reproduce the issue

1. Use minecolonies as dependency 
2. Use `genData`, you'll not be able to run it successful.

### Logs

runtime-log: https://gist.github.com/Seniorendi/d6b4e89ed96b1499cb9c684084191bde

### Notes

Nope
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
will be solved in one of the upcoming PRs, yes.

**Comment by SirEndii** [comment]
Thank you

**Comment by Raycoms** [comment]
afaik this has been solved
