### ISSUE TITLE
New Citizen Huts

### ISSUE THREAD

**Issue by pmardle** [ldtteam/minecolonies#791]
Player made content for all wood types..

http://www.minecolonies.com/publicforum/m/18051739/viewthread/29972406-alternative-wooden-huts/page/1/post/last

Haven't checked the .rar file or individual schematics submitted..

**Comment by xavierh** [comment]
Done more than citizen now. If we wait a little more we might get full sets? 😊

**Comment by carlansor** [comment]
maybe xD i need help modifiying miners hut, any idea where i can find info about it?

**Comment by xavierh** [comment]
@Raycoms @pmardle as minecolonies support additional huts schematics from a folder, should we have a repository for them?

Adding new huts styles in the jar is time consuming as we need to:

- Test them to check that the scan are done properly
- Make sure there difficulties are balanced
- release them for 1.10 and 1.11

I suggest we should only add **full sets** when:
- they have been tested for a while (on the official server?)
- They are well balanced
- it's a full set

Thoughts?

@carlansor this is a good question. Ray, do you know how it does work for the miner ? How does it know where to dig ?

**Comment by Raycoms** [comment]
The miner does search a ladder which goes 1 into the ground and has cobble
on the back.
And Yes I think a repository for styles would be great.

2017-05-02 5:27 GMT-03:00 xavierh <notifications@github.com>:

**Comment by marvin-bitterlich** [comment]
closing this for now
