### ISSUE TITLE
Cowhand cannot make milk bucket even with the milking turned on

### ISSUE THREAD

**Issue by EverettSummer** [ldtteam/minecolonies#7910]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 1.16.5-1.0.327-ALPHA
- Structurize Version: 0.13.252-ALPHA
- Related Mods and their Versions:

## Expected behavior

Cowhand should produce milk bucket based on the request, just as previous version. they will request bucket.

## Actual behavior

The baker will request the player to fulfill the milk bucket.

## Steps to reproduce the issue

1.  Turn on milking in cowhand's hut
2.  request bread
3.  you will see baker request milk bucket from player

### Logs

- latest.log: 
- crashlog: 

### Notes

<img width="427" alt="javaw_2022-01-06-234214-360" src="https://user-images.githubusercontent.com/55684557/148401934-14ea6dbd-a45b-49a9-b9dc-d613928dd272.png">

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
The cowhand is not a crafter, but a producer. If you hand them empty buckets, they will fill them and ask the courier to pick those up. But they won't do that if the baker (or anyone else) asks for milk buckets. That is similar to how they produce leather and raw beef. Those aren't produced on request either.

**Comment by EverettSummer** [comment]
@MotionlessTrain Thanks for reply, So this is a new change that they no longer behave like they did before. I will try set a minimal stock in their hut to see if this can be resolved automatically!

**Comment by Raycoms** [comment]
Min stock would be in the warehouse then

**Comment by MotionlessTrain** [comment]
> Min stock would be in the warehouse then

I think a minimum stock of empty buckets at the Cowhand would work better, as milk buckets can't get requested by the system

**Comment by EverettSummer** [comment]
It seems the baker will not return the empty bucket after crafting bread.

**Comment by uecasm** [comment]
> @MotionlessTrain Thanks for reply, So this is a new change that they no longer behave like they did before. I will try set a minimal stock in their hut to see if this can be resolved automatically!

It's not a new change.  They have never crafted milk buckets on request, as MotionlessTrain said.

As for the baker returning the empty buckets, they should -- but they might be landing in an unexpected rack or other inventory, so you might be overlooking them.  You can verify this in JEI -- it should show the empty buckets as an additional output of the cake batter recipe.  I _think_ these are also shown in the recipe in the hut as well, but I'm less sure about that.

There's an outside chance, if your colony has been upgraded from some _really_ old versions of Minecolonies, that the recipe itself is outdated and didn't get upgraded automatically.  You can try to fix this by removing the recipe from the baker; the latest version will be re-added automatically after a minute or so.

**Comment by EverettSummer** [comment]
Close since it's not a bug
