### ISSUE TITLE
Rendering issue causing world to be borked

### ISSUE THREAD

**Issue by LordRelentless** [ldtteam/minecolonies#7920]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [ x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.18.1
- MineColonies Version: 1.0.278-Release

### Logs

- latest.log: https://gist.github.com/LordRelentless/8d8855c03e0adad70387c1376db9f482#file-kjm-render-error-crash
## Steps to reproduce the issue / details

No idea what caused this but I can't even get into my game world.

### Notes

Reported this to the FeyWilds modpack team.
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
```
	at mod.tesslandia.ancientdebrisfinder.item.AncientDebrisFinderItem$1.m_142187_(AncientDebrisFinderItem.java:112) ~[ancientdebrisfinder-1.18.1-0.1.0.jar%2360!:1.18.1-0.1.0] {re:classloading}

```

Report to this mod.
