### ISSUE TITLE
Issue with inwardcircleheight4 builds

### ISSUE THREAD

**Issue by AzSteel** [ldtteam/minecolonies#7924]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: v 1.0.309 Release
- Structurize Version: 0.13.252-ALPHA
- Related Mods and their Versions:

## Expected behavior

When Using inwardcirleheight4 build procedure, all block would be placed as in the schematic

## Actual behavior

When placiing a schematic on inwardcircleheight4, the bottommost block on one corner is not checked or placed.  Any dirt needed to place that block is removed, however.

What the schematic should be:
https://i.imgur.com/7Mfdodh.png
What the builder placed:
https://i.imgur.com/1mINuGK.png

## Steps to reproduce the issue

1. Set a schematic (I've only noticed it with decorations, like roads or fields) with builder in inwardcircleheight4
2. Builder requests material, missing the bottom corner square (in above image, only asked for 5 glowstone, when the schematic requires six)
3. Builder builds schematic, leaving out the one block.

### Logs

- latest.log: https://gist.github.com/AzSteel/55670671dabcf9d73dc205f03967852e
- crashlog: No crash involved
### Notes
![2022-01-09_13 16 44](https://user-images.githubusercontent.com/97412132/148702917-c732afa1-3c72-4525-ac7a-315e716b48c4.png)
![2022-01-09_13 21 12](https://user-images.githubusercontent.com/97412132/148702920-f86bde36-8474-4878-8df3-5c9c17ddbf04.png)

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
duplicate: https://github.com/ldtteam/minecolonies/issues/7580
