### ISSUE TITLE
Citizens behave like jobless when updating to 1.16.5-1.0.345-ALPHA from 1.16.5-1.0.327-ALPHA

### ISSUE THREAD

**Issue by BlackWarrior2004** [ldtteam/minecolonies#7927]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-1.16.5-1.0.327-ALPHA to 1.16.5-1.0.345-ALPHA(upgrade)
- Structurize Version: structurize-0.13.252-ALPHA-universal
- Related Mods and their Versions:

## Expected behavior

The citizens to do their job normally
## Actual behavior

1. The citizens have the default skin(jobless skin) regardless their job
2. They are assigned to their job sites(we can see their name in the respective job sites and can recall them), but don`t do any work, just roam around like jobless citizen

![2022-01-10_22 48 48](https://user-images.githubusercontent.com/83131147/148831113-7d1c5d2a-9adf-4a2c-ba27-6a233e11fdc3.png)
![2022-01-10_22 51 27](https://user-images.githubusercontent.com/83131147/148831151-9f46938b-e984-4152-9980-9b91e0211939.png)
![2022-01-10_22 51 58](https://user-images.githubusercontent.com/83131147/148831174-dd176947-c153-4564-af8f-accb910add8b.png)
![2022-01-10_22 52 10](https://user-images.githubusercontent.com/83131147/148831179-0397051e-e4c4-4634-a739-d70c316450f0.png)
## Steps to reproduce the issue

1.  Create a colony with minecolonies-1.16.5-1.0.327-ALPHA installed
2.  Update the version to minecolonies-1.16.5-1.0.345-ALPHA
3.  Then it will happen

### Logs

- latest.log: https://mclo.gs/F4otDbz
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Solved
