### ISSUE TITLE
Duplication of building base item

### ISSUE THREAD

**Issue by Trethope** [ldtteam/minecolonies#7928]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.18.1
- MineColonies Version:  minecolonies-1.18.1-1.0.347-ALPHA
- Structurize Version: structurize-1.18.1-1.0.319-BETA
- Related Mods and their Versions: N/A

## Expected behavior

When placing building item should be used from inventory.

## Actual behavior

Item is not used but is still placed in world effectively duplicating item. 

https://user-images.githubusercontent.com/42754232/148945502-ee2a2eb6-6b5b-442c-bcd9-c91a13715f20.mp4

## Steps to reproduce the issue

1. Place a building e.g. guard tower using tool as normal. 
2. Use pick up button under build options to obtain item.
3. Place building again and item is not used but is placed.

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
Fwiw, the fix has not been pushed to 1.18 yet. So this issue is not solved yet in that version.
