### ISSUE TITLE
Using build tool the buildings turns invisible

### ISSUE THREAD

**Issue by Toktok123** [ldtteam/minecolonies#7930]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.18.1
- MineColonies Version: 1.0.347-ALPHA
- Structurize Version: 1.0.319-BETA
- Related Mods and their Versions: Optifine: U_H4

## Expected behavior

The blueprints working as they used to do, so I can see them bright. I am using SEUS shaders, but the only thing that has changed is the update to the newest Minecolonies. I know this has been a "bug" earlier, but didn't expect it to come back.

## Actual behavior

The blueprints or schematics are invisible, can only see beds and signs.

## Steps to reproduce the issue

1. Install the official Minecolonies modpack
2. Add optifine and SEUS shaders.
3. Try building something with the build tool, and you won't see anything.

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Nightenom** [comment]
Known thing - optifine is not supported in 1.18 yet (1.17 will never get it), reach discord for more info
