### ISSUE TITLE
My colony removed itself.

### ISSUE THREAD

**Issue by Qee0** [ldtteam/minecolonies#7932]
I just removed minecolony mod in mods folder for a sec and joined my colony world by mistake and i just putted the mod back and joined colony world again. My colony just removed when i try place a townhall it says there a colony near but there no colony. How can i revert to last saves or can i recorver the old colony.. i wasted 3 4 days for it.. Thanks..

**Comment by Raycoms** [comment]
Please ask in our discord for support discord.minecolonies.com
