### ISSUE TITLE
noSuchFieldError: DIRT on forge 39.0.18 | 1.18.1 latest Alpha

### ISSUE THREAD

**Issue by ghost** [ldtteam/minecolonies#7933]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.18.1
- MineColonies Version: minecolonies-1.18.1-1.0.347-ALPHA
- Structurize Version: structurize-1.18.1-1.0.320-ALPHA
- Related Mods and their Versions:
- BlockUI: blockui-1.18-0.0.34-ALPHA
- Domum Ornamentum: domum_ornamentum-1.18-1.0.32-ALPHA-universal
- Multi-Piston: multi-piston-1.18-1.2.2-ALPHA

## Expected behavior
When using the instant place feature (no placeholder blocks), the building would be placed instead of resulting in a noSuchFieldError: DIRT crash.

## Actual behavior
The v39.0.18 release of Forge 1.18.1 made changes to their tags, which included the removal of the tag forge:dirt. While trying to instantly place down a hut using the instant place (no placeholder blocks) feature, a noSuchFieldError: DIRT crash occurs, most likely from the usage of the removed forge:dirt tag. From my knowledge, this also occurs even while not cheating in buildings and having a builder do their job according to a user who brought this crash to light while using a modpack I moderate for.

## Steps to reproduce the issue
1. Obtain build tool and a builders hut in creative.
2. Use the instant place (no placeholder blocks) feature to place a level one acacia builder hut.
3. Watch a noSuchFieldError: DIRT crash occur.

### Logs
- latest.log: https://gist.github.com/switchnlade/dad67aad1100dfc215ba44cd93d43b1c
- crashlog: https://gist.github.com/switchnlade/609c07b333f889db43bdadb9b54c6362

### Notes
Link to the removal of forge:dirt tag commit: https://github.com/MinecraftForge/MinecraftForge/pull/7891/commits/38c91607ecdac1e43c88db7790a0a00e49a6d60f
This occurs only on 39.0.18, while using 39.0.17 or earlier, it works as intended.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
This is not a bug in MineColonies, it's a bug in Nature's Compass.  Either remove that or update both it and Forge.

**Comment by ghost** [comment]
Nature's compass is not in the mod list. Please check again.

**Comment by uecasm** [comment]
Actually wait, sorry, jumped the gun there.  It's still not a bug in Minecolonies, it's a bug in Structurize related to the Forge change.  Please post it there instead.

**Comment by ghost** [comment]
Sounds good, thanks for guiding to the correct spot to post it!
