### ISSUE TITLE
 Couriers do not bring back the finished item

### ISSUE THREAD

**Issue by Kolibry-Zero** [ldtteam/minecolonies#7934]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.16.5
- MineColonies Version:1.0.309

### Logs

- latest.log: https://gist.github.com/Kolibry-Zero/a623a2b3830757def7d393d7a9422386

## Steps to reproduce the issue / details

To reproduce the issue:
1. have a crafter
2. worker start a request
3. deliveryman bring the material to the crafter
4. crafter makes it
5. couriers doesnt bring it back 

After the crafter makes an item couriers doesnt pick it up, tried everything canceld the request used the reset request command, and if the crafter inventory is full they still dont pick up items from them. 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
Firstly, 309 is not the latest alpha.  Perhaps you should try updating and see if you can reproduce it with a more precise set of steps.

Secondly, this does work; I explicitly tested it myself just a couple days ago.  You may have to wait a while for it to be picked up, especially if your couriers are already quite busy.  The task to pick up the item is queued, so if your couriers already have a long list of things to do then it may take them a while to get to it.  You can check their task lists in the courier hut gui.

If you reset the request system, that also cancels all the pickup requests; then they won't pick it up again until you make a manual request or the crafter's storage gets quite a bit more full.

**Comment by Kolibry-Zero** [comment]
Thanks for the answer, I play with a modpack and if I download the latest version it crashes due compatibility. The other thing is my couriers are not busy they has nothing on the task list

**Comment by uecasm** [comment]
If you ask on Discord people can probably help you get past the update crash.
