### ISSUE TITLE
Citizen cap not rasing

### ISSUE THREAD

**Issue by DarVillous** [ldtteam/minecolonies#794]
### Minecolonies version

version minecolonies-universal-1.10.2-0.6.3387 (v0.7.3.3 )

### Expected behavior

Building a citizens hut should increase the max citizens from 4

### Actual behavior

- The max citizens remains at 4

### Steps to reproduce the problem

1. Start a new world, creative or survival SSP or SMP.
2. Place supply ship
3. place town hall
  * check the info and confirm a max of 4
4. place a builder
5. build the builder
6. place the citizen hut
7. build the citizen hut
8. check the info and confirm a max of ...dang it.

in one world I've built 2 citizen huts, town hall, delivery man and raised them to level 2,builder. I've build a level 5 warehaouse and builders hut,  a level 1 sawmill, and a level 4 miner.  I have a second level 1 builders hut, a farm and Fishing hut all needing someone to work them.

My normal mod (with forge 12.18.3.2254) pack has a lot of mods so I made a new pack with the following mods
-JEI
-journey map
-Minecolonies
-forge 12,18,3,2281
The same behavior was encountered.

**Comment by xavierh** [comment]
This is the normal behaviour, you get 4 homeless citizens when placing the town hall but they will still need their Citizen hut at one point. 
To get 5 citizens you need 5 citizen huts level 1 or 1 citizen hut level 5.

**Comment by Raycoms** [comment]
The problem is that you need one buildingLevel each citizen.
And, in order to get new citizen, all 4 existing citizen require a house
already.
Therefore, you need 4 levels of citizen huts + 1  to get a new citizen.

2017-04-10 10:59 GMT-03:00 Dar Villous <notifications@github.com>:

**Comment by DarVillous** [comment]
DOH, thank you.  I must have missed that in the wiki

**Comment by xavierh** [comment]
You are not the first one to report this issue. I guess we need to make it
more obvious somehow
