### ISSUE TITLE
CTD when placing supply camp with all latest versions

### ISSUE THREAD

**Issue by misteractimel** [ldtteam/minecolonies#7940]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version. (no ALPHA versions)
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 
- Minecraft Version: 1.18.1
- MineColonies Version: 1.18.1-1.0.336-BETA
- Structurize Version: 1.18.1-1.0.319-BETA
- Related Mods and their Versions: OptiFine HD U H4 (tried with and without)

## Expected behavior
I'd expect a supply camp to get placed. 

## Actual behavior
Game crashed to desktop, the supply camp is consumed and if attempting to place again after the crash the game says there is one already placed. 

## Steps to reproduce the issue

1. Craft supply camp.
2. Place supply camp in completely cleared area. 
3. Crash to desktop. 

### Logs

- latest.log: https://gist.github.com/misteractimel/e76efe15b0373843cf8f5c3cd430032d
- crashlog: https://gist.github.com/misteractimel/e03d42c30325b333526bbcd927153dd1

### Notes
If attempting to place the supply camp with optifine on, OpenGL gives 1282 error, and the outline of the building is a huge orange thing in the sky. Only the bed and banner are visible where the actual placement area is. 

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
https://github.com/ldtteam/minecolonies/issues/7938
