### ISSUE TITLE
Crash to desktop when opening "Build Option"

### ISSUE THREAD

**Issue by Overtekk** [ldtteam/minecolonies#7941]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.18.1
- MineColonies Version: minecolonies-1.18.1-1.0.278-RELEASE
- Structurize Version: structurize-1.18.1-1.0.319-BETA
- Related Mods and their Versions:

## Expected behavior
 I should be able to open Build Option

## Actual behavior
The game crash to desktop

## Steps to reproduce the issue

1. Make a construction
2.  Open "Build Option"
3. 

### Logs

- latest.log: https://gist.github.com/Overtekk/7a5bdbff4416bac9c7b68d74d24e8e37
- crashlog: https://gist.github.com/Overtekk/a8de4041681c34ce021fc9252c5ab9bc

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
#7938
