### ISSUE TITLE
Other people wandering around the colony and in the tavern display a face with a green “+” at the bottom left and it says I can recruit them at a price. I have 8+ level 5 houses in my colony, and 3 are empty, yet the wandering people display a message saying that there is not enough room for any more colonists in your colony!

### ISSUE THREAD

**Issue by NicksCraft2007** [ldtteam/minecolonies#7943]
I am running Forge 1.18.1 39.0.22 and MineColonies 1.18.1 1.0.351 ALPHA, BlockUI 1.18x 0.0.34, Domum Ornamentum 1.18x 1.0.35 Alpha, MultiPiston 1.18x 1.2.2 Alpha, and Structurize 1.18.1 1.0.323 Alpha. I don’t actually know if this is an issue on my side, or if it’s a mod issue.

**Comment by Raycoms** [comment]
"latest" is not a version. Please fill in the entire template
