### ISSUE TITLE
Other people wandering around the colony and in the tavern display a face with a green “+” at the bottom left and it says I can recruit them at a price. I have 8+ level 5 houses in my colony, and 3 are empty, yet the wandering people display a message saying that there is not enough room for any more colonists in your colony!

### ISSUE THREAD

**Issue by NicksCraft2007** [ldtteam/minecolonies#7946]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: Forge 1.18.1 39.0.22
- MineColonies Version: 1.18.1-1.0.351-ALPHA
- Structurize Version: 1.18.1-1.0.323-ALPHA
- Related Mods and their Versions: blockui-1.18-0.0.34-ALPHA
domum_ornamentum-1.18-1.0.35-ALPHA-universal
multi-piston-1.18-1.2.2-ALPHA

## Expected behavior
All citizens should automatically be added to a house nearest to their job. Other citizens should still be added to a partially or completely empty house whether or not they have a job.

## Actual behavior
Some houses are completely empty, even though there are far more houses than citizens. The citizens that are wandering around, mainly those who are displaying a face icon above their heads, display a message in chat saying that there is not enough room for them in your colony!

## Steps to reproduce the issue

1. Build a few more houses than there are citizens.
2. Most houses will be filled, but others will remain mostly empty.
3. One or more houses is/are partially or completely empty, when the amount of citizens is still less than the count of houses.

### Logs

- latest.log: 
- crashlog: 

### Notes
I have a theory that this could be because of the fact the each house has exactly 4 blocks between them(I'm building a small, somewhat cramped town.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
Could it be you are on 25 citizens and need to do the "Outpost" research to be able to get more citizens?

> All citizens should automatically be added to a house nearest to their job. Other citizens should still be added to a partially or completely empty house whether or not they have a job.
On automatic mode, they don't get assigned to the house nearest to their job, but to a random house. This is also true for unemployed citizens.

**Comment by Raycoms** [comment]
distance between houses doesn't matter btw

**Comment by NicksCraft2007** [comment]
That may be the case. I am very new to this mod, and I just started a series on it. I will check the University to see if I have unlocked that and or if I have the requirements to continue that research.

**Comment by NicksCraft2007** [comment]
Thanks for your help, I will try this.

**Comment by NicksCraft2007** [comment]
What is the max amount of citizens I can have?

**Comment by uecasm** [comment]
The ultimate max limit is set in the config file, though there are various limits at different levels of research.  If you're wanting to ask questions about how things work, joining the Discord is strongly recommended.
