### ISSUE TITLE
Kind of an inappropriate sounding name if you pronounce it a specific way, I would say. Maybe change or remove it? “Jazmin C. Cockayne"

### ISSUE THREAD

**Issue by NicksCraft2007** [ldtteam/minecolonies#7947]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- MineColonies Version:
- Structurize Version:

## Problem description

![2022-01-15_21 48 41](https://user-images.githubusercontent.com/72476728/149645557-acd3d674-0bd7-43e2-bf8e-4740466de7dd.png)

### Notes or related things

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn’t clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
I assume you're referring to the surname.  This surname has a [long and storied past](https://www.houseofnames.com/cockayne-family-crest) and it seems silly to me to censor names like that.

**Comment by NicksCraft2007** [comment]
I understand. Sometimes I overthink about things like this. Also, I just realized that I can remove the names I don’t like in the config file.
