### ISSUE TITLE
cannot find any clear how the food/hunger multiplier works

### ISSUE THREAD

**Issue by Snowmanbiggz** [ldtteam/minecolonies#7949]
### Prerequisites 

- [ x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [  ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.18.1
- MineColonies Version:1.18.1-1.0.351-ALPHA
- Structurize Version:structurize-1.18.1-1.0.323-ALPHA

## Problem description
no clear description of hunger multiplier

### Notes or related things
most if not all other configs say "percentage increase or decrease" or "decreasing this value decreases, increasing increases, etc"
looking for clear guidance on which direction to go for huger multiplier if i want colonists to eat less often or slow their rate of becoming hungry. Secondly, how is the multiplier meant to function? Does it reduce the amount of food needed to restore hunger? Reduce the amount of time before needing to eat again? Both? and conversely increases respectively? its the one config I havent seen any confirmed clear information on.

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
It's not an issue, ask on discord for support.
