### ISSUE TITLE
After deleting courier's hut block build tool and town hall GUI stopped working

### ISSUE THREAD

**Issue by Hecute** [ldtteam/minecolonies#7950]
### Prerequisites 

- [ x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.18.1
- MineColonies Version: 1.18.1-1.0.278
- Structurize Version: 1.18.1-1.0.324-ALPHA
- Related Mods and their Versions: 
![obraz_2022-01-16_174444](https://user-images.githubusercontent.com/92364733/149669281-eb64c159-c6a1-4ac4-8bfe-bb6d2da5bed5.png)

## Expected behavior
Using build tool I should see plans of building and I should see town hall and other building's GUI

## Actual behavior
I can open build tool mode and I see build tool's GUI but I can't see plans of the building. Also, I don't see building's GUI 

## Steps to reproduce the issue

1. Just delete courier's hut block with axe
2. Try to put courier's hut block again using build tool mode
3. Build plans doesn't show up

### Logs

- latest.log: 
- crashlog: 

### Notes

While looking for solution on your git forum I've learned that I can just pick up building block in "Build option". So don't worry, I'll never destroy building block with mine axe again (not only becouse it takes a looot of time)
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Using fabulous mode or optifine?

**Comment by Hecute** [comment]
> Using fabulous mode or optifine?

I think that I changed video settings to fabulous mode today, so maybe you are right. Let me check
Edit: Oh my gosh, You are right. Thank you so much!

**Comment by Raycoms** [comment]
Np =D
