### ISSUE TITLE
Ai has run into an issue, send to MineColonies authors

### ISSUE THREAD

**Issue by Henrik1234567** [ldtteam/minecolonies#7951]
This message came up on my miners, one the first day, and 3 the next day.
It started happening after one miner died, built more mining huts, but they had the same problem
[2022-01-16-1.log](https://github.com/ldtteam/minecolonies/files/7882641/2022-01-16-1.log)
[latest.log](https://github.com/ldtteam/minecolonies/files/7882642/latest.log)

**Comment by Henrik1234567** [comment]
Playing All the mods 6, version 1.8.17

**Comment by Raycoms** [comment]
a) I think you uploades some image you didn't want to =P
b) Yeah, there was an intermediary version that broke miners (blame me). So people that did update to that version before getting the fix have a broken miner and will have to place a new one =(
