### ISSUE TITLE
crash issue

### ISSUE THREAD

**Issue by nekotamer** [ldtteam/minecolonies#7955]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.18.1
- MineColonies Version: minecolonies-1.18.1-1.0.354-ALPHA.jar
- Structurize Version:  1.18.1-1.0.319-BETA
- Related Mods and their Versions:

## Expected behavior
 int the town hall i click the build options to go to the  builder menu. 

## Actual behavior
 when I click on the build tab in the town hall my game crashes every time. and give me error DIRT

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog:  https://gist.github.com/nekotamer/d09b9bbd26d41110832dc18ca779d7cc#file-c-users-miles-curseforge-minecraft-instances-all-the-mods-7-atm7-1-18-1-crash-reports-crash-2022-01-18_10-18-04-client-txt

### Notes
 I am using the mod in the mod pack (all the mods7)

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Duplicate, downgrade forge for now. Update is underway today.

**Comment by Talyda** [comment]
Also using the wrong version of structurize for that version of minecolonies, which also may have been part of the problem
