### ISSUE TITLE
crash upon using the scan tool over a large empty area

### ISSUE THREAD

**Issue by pantsguyapp** [ldtteam/minecolonies#7958]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: minecolonies-1.18.1-1.0.351-ALPHA
- MineColonies Version:
- Structurize Version: structurize-1.18.1-1.0.321-ALPHA
- Related Mods and their Versions:

## Actual behavior

As soon as I right clicked, my game crashed

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 
- 
[crash-2022-01-18_20.00.02-client.txt](https://github.com/ldtteam/minecolonies/files/7893397/crash-2022-01-18_20.00.02-client.txt)
[crash-2022-01-19_08.23.30-client.txt](https://github.com/ldtteam/minecolonies/files/7893398/crash-2022-01-19_08.23.30-client.txt)

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Can you try 355?

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by pantsguyapp** [comment]
sorry for late rep but the issue is solved thanks
