### ISSUE TITLE
Housing/Recruiting Issue

### ISSUE THREAD

**Issue by Moobien** [ldtteam/minecolonies#7959]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.18.1
- MineColonies Version: 355
- Structurize Version: 321
- Donkey Origami Version: 39
- BlockUI: 34
- MultiPiston: 2

## Expected behavior

Upgraded a house which adds an additional colonist slot for either a child to be born or visitor to be hired
## Actual behavior

House upgrades fine but sometimes doesn't update the colony even after 30 minutes. I changed the housing mode to manual and did some reshuffling of housing and was able to hire a visitor, even though when on automatic the mod said I had no free housing.

## Steps to reproduce the issue

1. build/upgrade a house (with colony housing set to automatic and children off)
2. attempt to hire a visitor, if successful repeat step 1 until fails
3.  Get told no free housing even though you have an empty house slot

### Logs

- latest.log: https://gist.github.com/Moobien/c6b9754dabfe48c1adc0b8cc1f902fbe 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Moobien** [comment]
EDIT: This happened to another player today using mcol v1.16.5-1.0.309-release

**Comment by Raycoms** [comment]
Can you try the newest?

**Comment by Talyda** [comment]
This has been happening for ages Ray, not always, so not able to reproduce it =P  I know it's not newest, but yesterday with someone in version .355 had it happen too (not sure if you changed anything to do with it since then)
Fix is to either fire and rehire a guard, switch housing to manual/auto, log out and in again, or repair the freshly made house, and sometimes sleep - any of those MIGHT work
