### ISSUE TITLE
I broke the miner

### ISSUE THREAD

**Issue by DriznaVv** [ldtteam/minecolonies#796]
### Minecolonies version

version 0.6.3282 or curse X.X.XX

### Expected behavior

- Miner was being stuck on the top of the mine shaft ladder. Figured breaking the block would open up the pathing for the miner to get down.

### Actual behaviour

- Miner started to build the mine shafts up instead of down. Even repaired the building, and got the top block replaced. Miner still kept trying to build up, instead of down.

### Steps to reproduce the problem

1. Build, and upgrade a miner hut to level 2
2. Break the top block of the mine shaft ladder
3. ...
4. Profit

**Comment by Raycoms** [comment]
Yeah the miner orientates himself at the ladders.
Break a ladder and he will give you hell.
its important that always the 4 first ladders stay intact. Else he will get problems recognizing things
