### ISSUE TITLE
A child was born and both his parents were the same guy and he was siblings with himself

### ISSUE THREAD

**Issue by Aldiket** [ldtteam/minecolonies#7964]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

1.18.1 - Minecraft Version:
1.0.355-ALPHA - MineColonies Version:
1.0.326-ALPHA - Structurize Version:
- Related Mods and their Versions:

## Actual behavior

When I open the newborn's family GUI I expect it to have both parents and since he was my first child he shouldn't be his own sibling.

![Child bug](https://user-images.githubusercontent.com/5954887/150438677-c8c5eab0-e051-439a-9ed6-ca36d0c7d6b9.PNG)

## Steps to reproduce the issue

If it's a GUI issue then fix the GUI.

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
Just a note to add I saw someone else with this yesterday too - I don't remember single parent families having the same parent listed as both mother and father
Do not recall if they had the kid listed as their own sibling though =)

**Comment by Talyda** [comment]
Just checked, the one from yesterday was the same
https://discord.com/channels/139070364159311872/244066364573089793/933583693514162199

**Comment by Raycoms** [comment]
No, it's supposed to just display one. Apparently it's not doing an equals check.
