### ISSUE TITLE
Server Crashed because of... "DIRT"?

### ISSUE THREAD

**Issue by YassaaaTU** [ldtteam/minecolonies#7965]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.18.1
- MineColonies Version: minecolonies-1.18.1-1.0.278-RELEASE.jar
- Structurize Version: structurize-1.18.1-1.0.319-BETA.jar

## Problem description

I don't know what happened but the server crashes because of Minecolonies. Or it says it does in the [crash-2022-01-21_01.38.13-server.txt](https://github.com/ldtteam/minecolonies/files/7909687/crash-2022-01-21_01.38.13-server.txt)

### Notes or related things

It is a big modpack. 150+
Forge version: 39.0.18
---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
Update, that's been fixed =)

**Comment by YassaaaTU** [comment]
Oh okay thank you! But I'm running the "Stable" version of the mod should I really update to Alpha?

**Comment by Talyda** [comment]
Yeah, 99% of the time you want the latest alpha for minecolonies =)
Make sure you read the changelog, and get the exact version of structurize that it mentions - and the versions of the other dependencies too

**Comment by YassaaaTU** [comment]
Ok got it thank you! I will update and check back here for result

**Comment by YassaaaTU** [comment]
Thank you it's working now without problems! :)
