### ISSUE TITLE
Minecolony Colonists don't appear on JourneyMap

### ISSUE THREAD

**Issue by KnightCa** [ldtteam/minecolonies#7966]
Minecolonies version
version 1.16.5 / 1.0.352-BETA

JourneyMap version
version 1.16.5 / 5.8.0beta10

Expected behavior
JourneyMap should display colonists, pets, or villagers, it does not matter.

Actual behavior
All colonies seems empty on the map.

**Comment by Raycoms** [comment]
Can we get client logs?

**Comment by MotionlessTrain** [comment]
Have you made sure you turned all sorts of entities on on the map?

**Comment by mysticdrew** [comment]
This is a journeymap bug, will be fixed in beta11. Honestly, this has been an issue for a while, not sure how it has not been reported. 
This has nothing to do with minecolonies.

**Comment by KnightCa** [comment]
This problem was not present in the version just before this one:

Minecolonies version
version 1.16.5 /  1.0.311-BETA

JourneyMap version
version 1.16.5 / 1.16.5-5.8.0beta4

**Comment by KnightCa** [comment]
Here is a screenshot of both the Local Fullscreen Map settings (you can see that all entities are selected).
![Map Settings](https://user-images.githubusercontent.com/51968609/150653043-882198c1-2239-4368-a519-38433698c6ae.jpg)

I did notice that in the Server Admin Global Properties, that Animal/Villager/Hostile entity Radar is turned off. Would this have a impact on the Full Screen Map?
![Server Admin JourneyMap](https://user-images.githubusercontent.com/51968609/150653091-a5b137ee-0915-417a-8fe8-7c15c7150145.jpg)

**Comment by mysticdrew** [comment]
Like I said this will be fixed in beta11 when it is released. This issue can be closed since it is not a minecolonies issue.

**Comment by mysticdrew** [comment]
> Here is a screenshot of both the Local Fullscreen Map settings (you can see that all entities are selected). ![Map Settings](https://user-images.githubusercontent.com/51968609/150653043-882198c1-2239-4368-a519-38433698c6ae.jpg)
> 
> I did notice that in the Server Admin Global Properties, that Animal/Villager/Hostile entity Radar is turned off. Would this have a impact on the Full Screen Map? ![Server Admin JourneyMap](https://user-images.githubusercontent.com/51968609/150653091-a5b137ee-0915-417a-8fe8-7c15c7150145.jpg)

Your server has them disabled, but there was also a bug with them not displaying anyways. Which is fixed in our internal builds.

**Comment by KnightCa** [comment]
Thank you for being on top of this @mysticdrew. Much appreciated.
