### ISSUE TITLE
Connection impossible because "guardTowerView" is null instant Crash

### ISSUE THREAD

**Issue by Tibseydon** [ldtteam/minecolonies#7967]
### Prerequisites 

- [ ] I am running the latest **1.18.1-1.0.354-ALPHA** version of MineColonies and Structurize for my Minecraft version.
- [ ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.18.1
- MineColonies Version: 1.0.354-ALPHA
- Structurize Version: 1.0.326-ALPHA
- Related Mods and their Versions: modpack ATM 7

## Expected behavior

Connection to the server, not crashing while loading the map

## Actual behavior

When I want to connect to the server, I can't see a thing because i crash while i'm connecting

## Steps to reproduce the issue

1.  I played last night without any problem, the problem occured this morning on the new connexion. Yersteday I built 2 or 3 Guards tower for my colonies. The error is guardTowerView is null so I supposed guards Towers  are the problem, try to build some on a server (they all are lvl 1)
2. I logged out yersteday, everything was good. 
3. I logged in this morning, i played 30s (loading time I guess) then i crashed and never logged in again (as shown on the video)

### Logs

- latest.log:  
- 
- crashlog:  https://gist.github.com/Tibseydon/ed243a21461cb91a2b7eb78e0823237f#file-crash-2022-01-21_10-25-46-client

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.
[MineconoliesCrash.zip](https://github.com/ldtteam/minecolonies/files/7912026/MineconoliesCrash.zip)
[latest.log](https://github.com/ldtteam/minecolonies/files/7912074/latest.log)

**Comment by Tibseydon** [comment]
Update, with an other account, i teleported my bug account while his connection in an other colony, He crashed. But when he reload and relog on this colony, he didnt crash. I teleported back in the colony and destroy the guard tower to be sure and he didnt crashed
before destruction, he didnt crash as well, maybe destruct tower guards was not necesseray

**Comment by Raycoms** [comment]
Do you have the server log as well?

**Comment by Tibseydon** [comment]
[latest.log](https://github.com/ldtteam/minecolonies/files/7913086/latest.log)

**Comment by Raycoms** [comment]
Fix pushed
