### ISSUE TITLE
Farmer trying to find field dirt crashes game

### ISSUE THREAD

**Issue by BasicallyWiz** [ldtteam/minecolonies#7969]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.18.1
- MineColonies Version: 1.0.356-ALPHA

### Logs

- latest.log: https://gist.github.com/BasicallyWiz/fb3b1a8b9e6badbc0cac2f297d338be1 

## Steps to reproduce the issue / details

Just reporting the AI issue. 

1. Build Farmer hut, hire farmer, and build plot near farm hut
2. Expect game crash

### Notes

- Farm hut is birch, and is a few blocks away from an ocean, but I doubt that would affect anything.
- Using external apps like Amulet to remove the plot from the level data fixes the crashing, until another plot is placed.
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
You still have 1.0.278 installed (probably by error; Curseforge doesn’t always remove old versions of mods as of lately). Make sure you delete any older versions of mods in the mods folder.

**Comment by BasicallyWiz** [comment]
> You still have 1.0.278 installed (probably by error; Curseforge doesn’t always remove old versions of mods as of lately). Make sure you delete any older versions of mods in the mods folder.

You were totally right! It also affected other mods.
![image](https://user-images.githubusercontent.com/48531736/150635460-dc9f2e75-24db-4fb2-a6b7-9710e6df0efd.png)
