### ISSUE TITLE
Domum Ornamentum is listed as mandatory dependency in mods.toml, causes crash after removal.

### ISSUE THREAD

**Issue by Jessman5** [ldtteam/minecolonies#7970]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.18.1
- MineColonies Version: minecolonies-1.18.1-1.0.355-ALPHA
- Structurize Version: structurize-1.18.1-1.0.326-ALPHA
- Related Mods and their Versions: domum_ornamentum-1.18.1-1.0.39-ALPHA-universal

## Expected behavior

I expect that when I remove a mod that's not related to minecolonies, that this mod is not mentioned as mandatory in minecolonies META-INF/mods.toml file like this:
```
[[dependencies.minecolonies]]
    modId="domum_ornamentum"
    mandatory=false
    versionRange="[1.18.1-1.0.31-ALPHA, )"
    ordering="AFTER"
    side="BOTH"
```
and that I can resume playing the game without the deleted mod.

## Actual behavior

Instead of loading the game without the actually not required mod, console gives me this:
```
 [main/ERROR] Missing mandatory dependencies: domum_ornamentum
 ..
  [Render thread/FATAL] Error during pre-loading phase
  [Render thread/WARN] Removed resource pack mod_resources from options because it doesn't seem to exist anymore
  [Render thread/ERROR] Cowardly refusing to send event net.minecraftforge.client.event.sound.SoundLoadEvent to a broken mod state
```
the META-INF/mods.toml file still states that domum_ornamentum would be mandatory. Changes to the file can't be saved. This is the only mention of the deleted mod, the mod itself had no config files.

## Steps to reproduce the issue

1. load minecolonies and domum_ornamentum
2. delete domum_ornamentum
3. game is crashing because minecolonies still wants the deleted mod.

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
The mod is mandatory and you cannot remove it.  What makes you think otherwise?  It's listed as a required dependency everywhere.

**Comment by Jessman5** [comment]
It's first NOT listed on curseforge as dependency, and second it was not required to install when I installed it via ATLauncher.
I installed that one myself and wanted to delete it again.
So you should rather update the description of your mod and fix the installation.

**Comment by uecasm** [comment]
It's listed as a required dependency for the 1.17 and 1.18 versions of the mod (see: https://www.curseforge.com/minecraft/mc-mods/minecolonies/files/3616095).  It is not a dependency for the 1.16 versions of the mod.

If ATLauncher did not download it as a dependency, then you should report that as a bug to them.

**Comment by someaddons** [comment]
Yelling at the creators of a mod, which do it unpaid in their freetime for you, maybe look into a mirror someday.

**Comment by Jessman5** [comment]
> It's listed as a required dependency for the 1.17 and 1.18 versions of the mod (see: https://www.curseforge.com/minecraft/mc-mods/minecolonies/files/3616095). It is not a dependency for the 1.16 versions of the mod.
> 
> If ATLauncher did not download it as a dependency, then you should report that as a bug to them.

then maybe update it here too https://www.curseforge.com/minecraft/mc-mods/minecolonies/relations/dependencies

**Comment by Jessman5** [comment]
> Yelling at the creators of a mod, which do it unpaid in their freetime for you, maybe look into a mirror someday.

No need to be a shithead, dude! No need for harassment! Bugreport is bugreport. If you can't handle this, then stop doing it, look yourself in the mirror and start questioning yourself what you can do better in your freetime.

**Comment by uecasm** [comment]
> then maybe update it here too https://www.curseforge.com/minecraft/mc-mods/minecolonies/relations/dependencies

That is the page for dependencies of all versions of the mod.  As I already explained, it is not a dependency for all versions of the mod, so it is not appropriate to list it there.  Currently the 1.16 version is still the "main"/stable version and that does not depend on it.

> No need to be a shithead, dude! No need for harassment! Bugreport is bugreport. If you can't handle this, then stop doing, look yourself in the mirror and start questioning yourself what you can do better in your freetime.

I suggest you take your own advice; you clearly need it more than we do.
