### ISSUE TITLE
Freeze on 2nd Supply Camp placement

### ISSUE THREAD

**Issue by Halibear** [ldtteam/minecolonies#7973]
### Prerequisites 

[x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
[x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
[x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context
- Minecraft Version: forge-1.18.1-39.0.58
- MineColonies Version: minecolonies-1.18.1-1.0.356-ALPHA
- Structurize Version: structurize-1.18.1-1.0.326-ALPHA
- Related Mods and their Versions:

## Expected behavior
Place 2nd supply camp found in chest by spawner box

## Actual behavior
Game freezes, after the 1st time game needs to be force shutdown through task manager

## Steps to reproduce the issue
1. Create Colony (I have been playing long enough to have built every building to level 5)
2. Find Supply Camp (chest) in chest by skeleton spawner box
3. Take back to colony and attempt to place OR Go far away from colony and try to place

### Logs
- latest.log: same as below
- crashlog: (https://gist.github.com/Halibear/31bcb9f733d88dd5f6c465f17bc13841)

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
The log seems entirely unrelated, are you sure you uploaded the right one?

**Comment by Halibear** [comment]
Sorry, was really sick when I was trying to put that together. I was able to reproduce the full crash again today, same steps as above no changes. 

https://gist.github.com/Halibear/93d59d0fe4eecd332a3d322b3b8d0973

Also.. I get this back at the Minecraft launcher:

The game crashed whilst unexpected error
Error: java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 0
Exit Code: -1

Sorry to keep adding here, but just in case it's relevant, I am right clicking with the supply camp in my hand on a grass block. I did try to use the build tool but it doesn't recognize the supply camp in my inventory (which I assumed was the expected result).

**Comment by Raycoms** [comment]
Can't reproduce this at all. Can you reproduce this with latest minecol+struct?

**Comment by Halibear** [comment]
Just updated to:

minecolonies-1.18.1-1.0.364-ALPHA
structurize-1.18.1-1.0.335-ALPHA
forge: 1.18.1 - 39.0.59

and yes, right click grass block within colony (I think where I am it would run into other buildings/not enough open space) but it freezes after the right click.

**Comment by Raycoms** [comment]
Any other mod you're running, do you override any schematics or styles?

**Comment by Halibear** [comment]
Well I feel less than qualified to answer, but I will do my best. Schematics wise I think structurize is the only one with buildings after world gen, but I am using Repurposed Structures & Shrine Structures which produce cool buildings during world gen. (If you think these might be the conflict, can you give me the right way to explain to the other creators so I can have them take a peak?)

https://www.curseforge.com/minecraft/mc-mods/repurposed-structures
https://www.curseforge.com/minecraft/mc-mods/shrines-structures

On the styles question, I'm not sure what this might be. I have 85 mods running and a few data packs on the world. I appreciate the help with trying to identify what is causing the issue.

**Comment by Halibear** [comment]
I started removing mods one at a time trying to locate a conflict. I removed them one at a time not putting any back on in the following order, but still get the freeze:

1: Shrines
2: Repurposed structures
3 & 4: (both are prereqs for repurposed structures) feature_nbt_deadlock_be_gone & No null processors
5 & 6: Quark & Quark Oddities

I know there is no way for you to know all the mods that are out there, but if you have any more check for "mods that do this" ideas, please let me know and I can try to remove those.

**Comment by Raycoms** [comment]
Generally asking. As you're saying this is only a problem on the second camp. a) Does this also happen with the ships and b) Does it also happen on the first camp (i.e. in a new world with the same setup).

**Comment by Halibear** [comment]
New world, 1st Camp, freeze and crash, only basic mods:

https://gist.github.com/Halibear/e3c2a1696bf8d6defb33a864aee6d6eb

blockui-1.18-0.0.42-ALPHA
domum_ornamentum-1.18.1-1.0.39-ALPHA-universal
minecolonies-1.18.1-1.0.364-ALPHA
multi-piston-1.18-1.2.2-ALPHA
structurize-1.18.1-1.0.335-ALPHA

Steps to reproduce:

1 - Create New world, Cheats on, Survival
2 - /gamemode creative
3 - go to inventory, search supply camp, grab supply camp, add to inventory
4 - /gamemode survival
5 - traveled to an "open" space, lots of different levels and grass but no trees, so I could see if it tried to place
6 - right click on grass block with supply camp in hand
Freezes, saving world screen, crash with log

**Comment by Raycoms** [comment]
Can I have the startup log of this? I.e. latest.log of the startup

**Comment by uecasm** [comment]
That kind of error usually happens if the Structurize config option has been set to disable built-in schematics and you haven't added any external ones to replace them.

We've had a couple reports on Discord of this somehow becoming set due to a corruption in the config file or something.  Try hunting down and deleting your `structurize-server.toml` config files (check both `defaultconfigs` and the `serverconfig` folder inside your world/save).

Perhaps save a copy first so that you can paste their contents here if it does fix the issue -- that might help us discover how it happens.

**Comment by Halibear** [comment]
I deleted the structurize .toml file in the save folder path, there wasn't one the the regular config folder. Ran the game no change. Deleted the minecolonies .toml file in the regular config folder and the structurize .toml in the server config folder. Ran the game, all the same world, no change. If there should be a structurize config then it's missing.

**Comment by Talyda** [comment]
Did you get the latest.log for Ray?

Fwiw I tested this in a fresh install with the exact same versions and steps and it was fine

**Comment by Raycoms** [comment]
What OS are you on?

**Comment by limmyhop** [comment]
Hello,
having the exact same issue, updated to the latest versions across the board today, happens when i right click, everyone is having the issue on my server

here's my log

[crash-2022-01-25_00.16.52-client.txt](https://github.com/ldtteam/minecolonies/files/7929711/crash-2022-01-25_00.16.52-client.txt)

hope this helps

**Comment by Raycoms** [comment]
I need your server startup log

**Comment by limmyhop** [comment]
[latest.log](https://github.com/ldtteam/minecolonies/files/7929748/latest.log)
thats the server log upto me joining, placing and crashing
it appears to be only client side as the server does not crash

**Comment by Talyda** [comment]
> What OS are you on?

Win 10 (if that was for me!)

**Comment by uecasm** [comment]
> that should be it, it appears to be only client side as the server does not crash

Perhaps, but we still need to see the log.

**Comment by Raycoms** [comment]
> [latest.log](https://github.com/ldtteam/minecolonies/files/7929748/latest.log) thats the server log upto me joining, placing and crashing it appears to be only client side as the server does not crash

Can I get a client startup + login log too?

**Comment by limmyhop** [comment]
Client
[latest.log](https://github.com/ldtteam/minecolonies/files/7929757/latest.log)

Server
[latest.log](https://github.com/ldtteam/minecolonies/files/7929761/latest.log)

hope thats all

**Comment by Raycoms** [comment]
@limmyhop did you try to regen the structurize client and serverconfig?

**Comment by limmyhop** [comment]
I deleted the structurize.toml in the server config but that didn't solve anything, I couldn't find one on client side

**Comment by Talyda** [comment]
Oh, I tested in SP (in case that matters)

**Comment by Raycoms** [comment]
a) Does this only happen with the supplycamp or also with the ship?
b) Does placing a hut with the buildtool work?

**Comment by limmyhop** [comment]
I have tested with supply camp, someone else on the server had the same results with the ship
Building using the build tool works fine, even the supply camp
reinstalling the client hasn't worked

**Comment by Raycoms** [comment]
Can you try, downgrading blockui to version 0.0.40?

**Comment by limmyhop** [comment]
yep that's the issue, now its fine

**Comment by Raycoms** [comment]
okay great, so we have a workaround for now. And Indeed with 42 I was able to reproduce it.

**Comment by limmyhop** [comment]
thanks for the help!

**Comment by Halibear** [comment]
me too! thank you so much!

**Comment by Raycoms** [comment]
Now I pushed a version with a fix.
