### ISSUE TITLE
Can't place mine colony camp or ship?

### ISSUE THREAD

**Issue by RebelGuy12345** [ldtteam/minecolonies#7974]
![Capture](https://user-images.githubusercontent.com/63030267/150656618-caf68103-196e-40ed-9d7e-41e1ecd30e5f.PNG)

It won't let me place the minecolony camp or ship because it says that I'm outside of the colony and thus can't be built but I just started the world and haven't made a colony yet. I have tried this on 3 separate worlds to try and get it to work. Picture is included to show what it says. Thank you in advance!

**Comment by MotionlessTrain** [comment]
Right click the supply camp directly on the ground and don’t use the build tool yet.

Furthermore, could you please fill in the template next time?

**Comment by RebelGuy12345** [comment]
Thank you so much!! Sorry in regards to the template. In the future I shall use the template provided. Again thank you in advance!
