### ISSUE TITLE
CTD when using Journey Map integration

### ISSUE THREAD

**Issue by Dryelo** [ldtteam/minecolonies#7975]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

I am playing the Enigmatica 6 pack on a dedicated server with some manually added mods.
My FTBChunks claims are basically my colony borders. 

- Minecraft Version: 1.16.5
- Forge Version: 36.2.20
- MineColonies Version: 1.16.5-1.0.352-BETA
- Structurize Version: 0.13.252-ALPHA-universal
- Related Mods and their Versions:
- JourneyMap Version: 1.16.5-5.7.3
- ftbChunks Version: 1605.3.2-build.83

## Expected behavior
JourneyMap shows colony borders

## Actual behavior
Game crashes to desktop as soon as I move. Turning around is okay but moving crashes the game.
As soon as I set the JouneyMap options to false in the Minecolonies config file, the game no longer crashes.

## Steps to reproduce the issue

1. updated Minecolonies from v1.0.205-BETA-universal to v1.16.5-1.0.352-BETA on server and client
2. rejoin the game
3. move around

### Logs

- latest.log: 
- crashlog: [https://gist.github.com/Dryelo/39f506fb92a2b7fa67ccc207c9342e1e](url)

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
Your JourneyMap is outdated.  You need to update to at least 5.8.0beta5, but the latest beta10 is recommended.

It's *supposed* to tell you that when you start Minecraft, but there have been reports that the minimum version checking is not always behaving as expected.

**Comment by uecasm** [comment]
Note that when you click into the specific file on Curseforge (in this case [here](https://www.curseforge.com/minecraft/mc-mods/minecolonies/files/3608226)) the changelog tells you the versions of other mods that are expected.  Structurize is an exact-version-only dependency while the others are that-version-or-later, although on occasion a later version of some mod will also introduce an incompatibility.

Also note that some of the launchers appear to have had problems recently where they weren't removing the old versions of mods being updated, so you'd end up with two or more copies of the same mod and hilarity would ensue.  So it might pay to double-check the actual contents of your mod folder to confirm.

**Comment by Dryelo** [comment]
okay, it even says so in the changelog - optional dependencies.
And I noticed Curseforge doesn't remove the old files.

Sorry for the trouble and thank you for the support! 👍
