### ISSUE TITLE
Minecolonies Ticking Check Crash the issue: the quarry block.

### ISSUE THREAD

**Issue by IchigoGames** [ldtteam/minecolonies#798]
### Minecolonies version

minecolonies-universal-1.11-0.6.3282

### Expected behavior

Not Crashing

### Actual behaviour

Minecolonies Ticking Check Crash the issue: its the quarry block.

### Steps to reproduce the problem

1. place the minecolonies quarry block
2. let it run
3. and it Crash server.

https://pastebin.com/6nptBUg0 the crash report

**Comment by Raycoms** [comment]
Yeah please don't use it. Its not obtainable ingame (outside of creative tab)

**Comment by IchigoGames** [comment]
um what no it is i crafted it
