### ISSUE TITLE
Citizen duplicating, said duplicates are frozen and seem not to ever disappear

### ISSUE THREAD

**Issue by Tellurnirn** [ldtteam/minecolonies#7981]
- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context

- Minecraft Version: 1.18.1
- MineColonies Version: 1.0.278 Release (Forge)

## Steps to reproduce the issue / details

Play long enough till you witness citizens duplicating themselves around the colony.

Their duplicates are frozen and don't seem to ever disappear even after the said citizen dies.
Their inventory and all features on their personal page are all availabe and functional.

I write duplicate here but there are as much as 2 clones of some villagers so far.
They all eventually display a notification above their head stating they couldn't sleep in three days.

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Known problem. (You could find that with the issue search feature). It's a vanilla problem with entity handling. Regular server restarts solve it.
