### ISSUE TITLE
[1.6.15] SkyColonies Ultimate Pack treeplamter now growing all trees

### ISSUE THREAD

**Issue by drago87** [ldtteam/minecolonies#7986]
### Prerequisites 

- [ x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 1.0.358-ALPHA
- Structurize Version: 0.13.252-ALPHA-universal
- Related Mods and their Versions: SkyColonies Ultimate Pack

## Expected behavior

All trees would grow on decorations/skylands treeplantera

## Actual behavior

When planting Acacia Sapling on the decorations/skylands treeplantera (i assume b,c,d and e)
the tree will not grow the same is true for a 4x4 jungle sappling

## Steps to reproduce the issue

1. have the citicen build decorations/skylands treeplantera
2. Plant a Acacia Sapling or a 4x4 of Jungle Saplings
3. Use bonemeal or run/repetedly sneak around the saplings
3. Bonemeal effect is happening but the trees wont grow

### Logs

- latest.log: https://gist.github.com/drago87/2c2e73fc6f2dd5d9dbaa984f0a00ffe3
- crashlog: no crash

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
This is for minecolonies bug reports, not for modpack bug reports. For those please go to our discord.
