### ISSUE TITLE
crash on multiplayer server

### ISSUE THREAD

**Issue by ZeSunshine** [ldtteam/minecolonies#7987]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.18
- MineColonies Version: minecolonies-1.18.1-1.0.364-ALPHA.jar
- Structurize Version:structurize-1.18.1-1.0.335-ALPHA.jar
- Related Mods and their Versions:

## Expected behavior
 I would be able to build the town hall and or create a colony

## Actual behavior

when I try building the town hall using the build tool it tells me I dont have the hut block in my inventory even if I do. If I place the block directly on the ground without using the build tool, I crash instantly when I try creating the colony and can never join the server again

https://justpaste.it/8wbx6

## Steps to reproduce the issue

on a server
1. place town hall block on the ground, since the build tool wont allow me to build it 
2. create colonie

### Logs

- latest.log: 
- crashlog: [](https://justpaste.it/8wbx6)

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Will merge the two PRs with the fixes right away
