### ISSUE TITLE
Guards clipping through floor

### ISSUE THREAD

**Issue by sbuller** [ldtteam/minecolonies#7989]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 1.16.5-1.0.348-ALPHA
- Structurize Version: 0.13.252-ALPHA
- Related Mods and their Versions: SkyColonies Ultimate v2.2

## Actual behavior

I'm experiencing guards clipping through the floor.

I've built a 'hive' style base. The hive is built in the void with no supporting blocks. I repeatedly lose guards to the void within a day or two of letting them loose. Initially I fenced the base in, and hunted holes in the base, but the deaths continued. I followed up on the coordinates from a death message and found it rather centrally located, with no holes through the bottom of the base. I have not had issues with other citizens.

I speculate that what must be occurring is that the guard is falling asleep on or in the vicinity of a slab or stair with nothing beneath it, and the vertical position isn't properly calculated when the guard wakes up, leading to the guard clipping through the floor. Unfortunately I have not directly observed the phenomenon, so this remains speculation.

What *is* clear is that the guards are somehow clipping through the floor.

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Bunzinator** [comment]
I am experiencing the same issue, in SkyColonies Ultimate 2.2. (minecolonies-1.16.5-1.0.348-ALPHA) Guards who fall asleep on a slab with nothing below it, fall out of the world when they wake up.
