### ISSUE TITLE
Minecolonies on 1.18.1 (All The Mods 7 v0.2.35) using Asian theme erroring with Mineshaft Blueprints

### ISSUE THREAD

**Issue by figori** [ldtteam/minecolonies#7995]
The following message keeps getting spammed on the server as the Miner is attempting to build the mine:

[Server thread/WARN]: File jar resolve FAILED for: schematics/asian/miner/minermainshaft.blueprint

Minecolonies v:minecolonies-1.18.1-1.0.368-ALPHA

**Comment by uecasm** [comment]
That message just means that the asian style does not have a custom mineshaft schematic, and so it will use the default style instead.  It is not an error and can safely be ignored.

In the future, please discuss issues on Discord first, and fill in the template if you do submit an issue on GitHub.
