### ISSUE TITLE
Colonists skins are bugged

### ISSUE THREAD

**Issue by IcarusRoM** [ldtteam/minecolonies#7999]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: Minecraft 1.18.
- MineColonies Version: minecolonies 1.18.1-1.0.374-ALPHA

### Logs

- latest.log:  https://gist.github.com/IcarusRoM/1a0d538e855c7a77ebf4129e0ad91ac7#file-gistfile1-txt

## Steps to reproduce the issue / details

 Noticable is that the AI that has the player model bug is mostly unemployed. I also picked the caledonia style, if that helps.

Just reporting the AI issue. 

### Notes

![Bugged ColonistSkins](https://user-images.githubusercontent.com/98590943/151542871-535f225e-3d99-469e-a04c-4cd87378a7c8.png)

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
From earlier conversations, it seems to be the unemployed aristocrat male  skin that is looking weird

**Comment by Raycoms** [comment]
fixed
