### ISSUE TITLE
MineColonies Colonist Health Status don't display right with high-res GUI

### ISSUE THREAD

**Issue by thakyZ** [ldtteam/minecolonies#8007]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: `1.18.1`
- MineColonies Version: `1.0.376-ALPHA`
- Structurize Version: `1.0.340-ALPHA`
- Related Mods and their Versions:
  - All the Mods 7: `3.2.3`
  - Open Computers 2: `0.0.8`
  - Markdown Manual: `1.1.0`
  - Sedna: `1.0.10`

## Expected behavior
The icons on a colonist's GUI should display properly no matter the resolution, just like it does on the player's health bar.

## Actual behavior

When using a texture pack that uses a `icons.png` file that is at least double the resolution of the vanilla texture (>256px) it displays all wonky and doesn't show up right.

![image](https://user-images.githubusercontent.com/950594/151686680-cf70b915-097a-4795-ba0f-8854a6ddca4b.png)

## Steps to reproduce the issue

1. Download a texture pack with a higher resolution GUI.
2. Enable texture pack
3. View a colonist's status GUI

### Logs

- latest.log:  https://gist.github.com/thakyZ/c188e71a8e7d4a69df0a5cfbf27527a9
- crashlog:  N/A

### Notes

With the texture pack with a higher resolution, I used New Default+ but I am not sure if it would happen on others, however I don't see why it wouldn't happen.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Moobien** [comment]
are you using a resource pack?

**Comment by Raycoms** [comment]
yes, that's the point of the report

**Comment by Raycoms** [comment]
@Nightenom any idea?

**Comment by drakray** [comment]
got the same thing with Faithfulx32
Removing the resourcePack fixes the bug

**Comment by thakyZ** [comment]
> are you using a resource pack?

I was using a resource pack, sorry I said texture pack original and I meant resource pack.
