### ISSUE TITLE
[1.10.2-0.6.3395] The Builder can't craft blocks

### ISSUE THREAD

**Issue by ghost** [ldtteam/minecolonies#801]
### Minecolonies version

version 0.6.3395 on Minecraft 1.10.2

### Expected behavior

- The Builder can craft blocks by himself (like shown in the presentation video on YouTube)

### Actual behaviour

- He doesn't, he can continue to build only if he gets the crafted block

### Steps to reproduce the problem

1. Create a colony
2. Place a builder's hut
3. Give him a shovel, some cobble, some wood log and some dirt
4. He'll stop himself on the wooden fence or on the wood planks, and he'll keep asking for one of them
(I only tested the mod in creative)

### Notes

I am also using other mods, such as:
 - Food Expansion
 - Just Enough Items
 - Mantle
 - Tinkers' Construct
 - Realistic Terrain Generation
 - Placeable Items

So I tried without these mods, but I still get the bug.

**Comment by Raycoms** [comment]
Working on this.
Not a bug.
Will have a future crafter worker.
