### ISSUE TITLE
Crash when create a colony

### ISSUE THREAD

**Issue by DrSigma4164** [ldtteam/minecolonies#8010]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.16.5
- MineColonies Version:1.0.365-ALPHA
- Structurize Version:1.0.339-ALPHA
- Related Mods and their Versions: journeymap-1.16.5-5.7.3

## Actual behavior
I'm playing with a friend and he decided to start your mod put the town hall block and when he clicked to create a new colony it crashed and later me. Now I can't go into the world because it makes me beautiful. The crash log mentioned your mod as well as the Journey Map mod. And one more. It starts to beautify me after I start walking, that is, if I go into the world and will stand I do not crash.

## Steps to reproduce the issue
1. Place Townhall hut block
2. Click on button "Create a new colony"
3. Crash
### Logs
- latest.log: https://gist.github.com/39ed181be3153e6d9f6e4aa38737c1da.git
- crashlog when friend click on button "create a new colony": https://gist.github.com/df698af9c091c60600f7bb78ce00b3f1.git
- crashlog when I tried to enter the world : https://gist.github.com/bb3bde4c61f2e94d6894d69ba14a7dc5.git

**Comment by MotionlessTrain** [comment]
Upgrade Journeymap to the latest beta (5.8.0-beta…). Minecraft should have warned you while starting up the world, but didn’t for some reason.
