### ISSUE TITLE
Mine does not show the Layer selection anymore

### ISSUE THREAD

**Issue by Galotar** [ldtteam/minecolonies#8014]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.18.1
- MineColonies Version: 1.18.1-1.0.383
- Structurize Version: Structurize: 1.18.1-1.0.340-ALPHA
- Related Mods and their Versions:
      Multi-Piston: 1.18-1.2.2-ALPHA
      BlockUI: 1.18-0.0.42-ALPHA
      Domum Ornamentum: 1.18.1-1.0.39-ALPHA

## Expected behavior

The layer selection where the Miner have to mine.

## Actual behavior

The tab for the layerselection do not show up.

![image](https://user-images.githubusercontent.com/17314295/151885186-001da189-2c3e-495a-8776-ff5960a1d415.png)

## Steps to reproduce the issue

1.  Right click on the Mine
2.  See no Layer-Tab ... :)
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
fix pushed

**Comment by Talyda** [comment]
Ray, did this get fixed in 1.18 as well? It seems only 1.16 got the fix =)

**Comment by MotionlessTrain** [comment]
This did get fixed in 1.18, however the version with the fix in it failed to build.
There is no fixed version released yet unfortunately.

Edit: Version 1.0.386 is now released fixing issue in 1.18
