### ISSUE TITLE
Version incorrect, Wants an older version, auto installed wrong dependency. 

### ISSUE THREAD

**Issue by ghost** [ldtteam/minecolonies#8015]
### Prerequisites 

- [ x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5, Forge 36.2.20
- MineColonies Version: minecolonies-1.16.5-1.0.309-RELEASE.jar
- Structurize Version: structurize-0.13.252-ALPHA-universal.jar

## Problem description

I just installed Minecolonies latest from curseforge app, installing it to my custom profile.
![minecolonies](https://user-images.githubusercontent.com/28419558/151904173-454dff15-41ed-4e6c-945f-5dbe8b29d872.PNG)
This is the error i got, trying again with the version the error requested
### Notes or related things

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
sure you don't have the mod twice in the folder?

**Comment by ghost** [comment]
Yes I'm sure.

**Comment by Raycoms** [comment]
Can you screenshot your mods folder so we can see the other deps?

**Comment by Raycoms** [comment]
+ Log please

**Comment by ghost** [comment]
to be clear, I messed up that initial post, This was using structurize-1.16.5-1.0.339-ALPHA.jar
[crash-2022-01-31_20.12.54-fml.txt](https://github.com/ldtteam/minecolonies/files/7975480/crash-2022-01-31_20.12.54-fml.txt)

**Comment by Raycoms** [comment]
Ahh, did you try the alpha it mentions to install?

**Comment by Raycoms** [comment]
Anyway, I'd also encourage you to update to a newer beta version.

**Comment by ghost** [comment]
I installed minecolonies through curseforge, it auto installed structurize, and like the error says minecolonies wants the older version, I would like to have the latest version installed, but it is not happy about it.

**Comment by ghost** [comment]
It launches without errors with the version it requested, I found it odd it wont accept a newer one.

**Comment by Talyda** [comment]
Minecolonies is always built to a specific version of structurize.
You're also outdated on minecolonies, which is what Ray meant when he said he would encourage you to update to a newer beta

**Comment by ghost** [comment]
Wow, okay i see that now, This is what curse installed by default
