### ISSUE TITLE
Builder not taking wheat extra shingles

### ISSUE THREAD

**Issue by Ampaex** [ldtteam/minecolonies#8016]
- [ x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.18.1
- MineColonies Version: 1.18.1-1.0.386-ALPHA
- Structurize Version: 1.18.1-1.0.340-ALPHA
- Related Mods and their Versions:
- domum_ornamentum-1.18.1-1.0.39-ALPHA-universal.
- multi-piston-1.18-1.2.2-ALPHA.
- blockui-1.18.1-0.0.43-ALPHA.
- jei-1.18.1-9.1.2.61.
- journeymap-1.18.1-5.8.0beta11.

## Expected behavior
Being able to fulfill the request or not keep asking for it.

## Actual behavior
The builder is asking for wheat extra shingles. He already has in his inventory and in the building inventory. If I take the block and try to fulfill his request the block is not recognised as a correct block.

![2022-02-01_13 02 19](https://user-images.githubusercontent.com/9005862/151967656-84e2c3c3-8450-4083-9ca4-e90ede92c5ed.png)
![2022-02-01_13 03 22](https://user-images.githubusercontent.com/9005862/151967673-e3f3ca39-6ed6-4640-967a-544b586af426.png)
![2022-02-01_13 02 00](https://user-images.githubusercontent.com/9005862/151967735-48295065-561f-48d2-9c96-286b0765e9a5.png)

## Steps to reproduce the issue

1. Try to build a cowboy hut lvl 1.
2. Then will be a moment(near the end, it's the top roof of the building) in which the builder will ask you for wheat extra shingles.
3. Cannot fulfill his request.
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Wrong wheat extra shingle. Double wheat extra cobble with oak base.
