### ISSUE TITLE
Crafters don't seem to always stand by their hut and ready to craft

### ISSUE THREAD

**Issue by pantsguyapp** [ldtteam/minecolonies#8018]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-1.16.5-1.0.381-ALPHA
- Structurize Version: structurize-1.16.5-1.0.339-ALPHA
- Related Mods and their Versions:

## Expected behavior

The crafters always come to stand next to their hut

## Actual behavior

They stay in their home
Test with blacksmith

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
That's normal - if they don't have anything to do they can wander around =) They aren't chained to their workstations! ;)

**Comment by pantsguyapp** [comment]
that seems unfair when compared to other labouring workers who have to spend the entire day on the field, and here we have the crafters who are unable to follow the simple task of just stand around in their workplace. Furthermore, the wandering mechanic make it so that the crafters is seen as terribly irresponsible, realistically you would only wander away from your position if you have other things to do, not spending the entire day in the nearby park only run back when there are tasks available, and as a result, affect the entire line and the overall productivity of the colony.

**Comment by Talyda** [comment]
I really think you are overthinking things =P

**Comment by pantsguyapp** [comment]
why close?

**Comment by Raycoms** [comment]
It is intended behaviour

**Comment by pantsguyapp** [comment]
> It is intended behaviour

Sad...
