### ISSUE TITLE
Quarry worker isn't requesting pickaxe when needed

### ISSUE THREAD

**Issue by Talyda** [ldtteam/minecolonies#8020]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.18.1
- MineColonies Version:  1.0.387
- Structurize Version: 1.0.341
- Related Mods and their Versions:
Multi-Piston: 1.2.2
BlockUI: 0.0.43
Domum Ornamentum: 1.0.39

## Expected behavior
Quarry worker requests pickaxe

## Actual behavior
Quarryer stands at the mine hut block, making the block place animation over and over, but not actually doing anything

## Steps to reproduce the issue

I can't reliably replicate it. 
Had it happen on the small quarry first off, and didn't realise what was happening.
Gave him a pick and off he went. Realised what was happening, so I took pick away from him, but this time he did request it =P
Miner in the medium quarry has worn out his pick, and found him standing at his mine hut block doing as above. No request in the clipboard, or on his GUI. There were picks in the warehouse, and idle couriers.
Waited a bit to see if he would go off, but nada. Gave him a pick and he went off to work right away.

### Logs

If they will help I can try and grab one next time it happens

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
I've had this game open in the background all day today, and the first miner is doing it again - at the mine hut block, making placing animations, no requests showing anywhere, but they need a pickaxe

this is when I do /mc citizen info - he's definitely not mining, though doing the animation, there is nothing going in or out of his inventory
![image](https://user-images.githubusercontent.com/17323101/152295728-51bc59e8-bb94-4b41-8193-6fffccb89af3.png)


This is immediately after I give him the pick (while he is on his way back to start quarrying again)
![image](https://user-images.githubusercontent.com/17323101/152295992-507ab6d2-58e2-4f0c-b865-c4cac232ede3.png)

**Comment by Talyda** [comment]
Oh, and peculiarer and peculiarer - once I gave him the pick and that changed to "NEEDS_ITEM", the courier brought him one from the warehouse.
At least I assume it was right then the courier took it, cos they weren't there before.

Same exact thing just happened with the other quarry worker, courier just brought them a pickaxe after I gave them one with all that above stuff being the same (except this time the quarryer needed to empty their inventory as well)

**Comment by Talyda** [comment]
Don't know if this is related, but now he is just sitting at the top of the quarry with "Load_structure" as their current activity. Not sure what else to try to get them working

**Comment by Raycoms** [comment]
fix pushed

**Comment by Talyda** [comment]
I've updated to that fixed version, fired and rehired the worker, but he is still standing at the top of the quarry, doing nothing, with "load structure" as his current activity, so I guess that was not related =P I left the game running for a couple hours last night with him doing the same.
Gonna start a fresh game and see if I can get them going any further.
Small quarry was no hassles, finished two of those, but the medium quarry he is just standing there

**Comment by Raycoms** [comment]
Does the quarry, by chance, leave the world height limits? (like in a superflat world?)

**Comment by Talyda** [comment]
Nope, made it on a regular world
Starts at y69, and is down to y56

**Comment by Talyda** [comment]
Would a world export help you?

**Comment by Raycoms** [comment]
Maybe, ye

**Comment by Talyda** [comment]
[colony1Export.zip](https://github.com/ldtteam/minecolonies/files/7998235/colony1Export.zip)
There you go =)
Meanwhile I will start on another world, and see if it happens there too 

Mod list if you need it?
![image](https://user-images.githubusercontent.com/17323101/152429217-edce167b-5dc8-423b-903b-3da07f9ef859.png)

**Comment by Talyda** [comment]
Started a new world, and have had one stuck for about an hour now for the same reason, on a medium quarry again - has only dug out about 2 Y levels. Small quarry is still motoring away, and nearly finished
This time I used that superflat "overworld" preset - so it's all flat, but still very deep - started at y-1 and has been stuck at y-3 (world goes down to -64)

**Comment by Raycoms** [comment]
Was for tool reasons again?

**Comment by Talyda** [comment]
No, just the "load structure"

**Comment by Talyda** [comment]
She DID also get sick, but I htink she was stuck in "load structure" so she didn't go off to get healed until I fired her - waiting for that to happen now, before I try restarting her to see if she starts working

**Comment by Raycoms** [comment]
So I guess the resource cost calc is increasing infinitely in the miner hut display?

**Comment by Talyda** [comment]
I didn't know to look there - will do so once she is back and healed

**Comment by Talyda** [comment]
On a one minute sample - it does appear that way! (Obviously I will keep watching =D) And make sure she is still stuck there

**Comment by MotionlessTrain** [comment]
> So I guess the resource cost calc is increasing infinitely in the miner hut display?

I saw someone mentioning that the quarrier was asking for 446 framed cobblestone to make the small quarry right after hiring.
I haven't done the calculations, but it does sound a bit much.

**Comment by Raycoms** [comment]
and you are on the latest.

> > So I guess the resource cost calc is increasing infinitely in the miner hut display?
> 
> I saw someone mentioning that the quarrier was asking for 446 framed cobblestone to make the small quarry right after hiring. I haven't done the calculations, but it does sound a bit much.

I fixed that recently. It should now ask a stack at a time afaik. But partial fulfillment is a thing. 446 is the total amount.

@Talyda You are on the absolute latest, right?

**Comment by Talyda** [comment]
Ok, it did stop after a bit more than a minute - then she moved to a spot inside the quarry, and it is counting up again - will keep watching to see if that changes

**Comment by Talyda** [comment]
The one you put the fix in this morning - ending in.90 I think?

**Comment by Talyda** [comment]
Yeah, .390

**Comment by Talyda** [comment]
![image](https://user-images.githubusercontent.com/17323101/152445920-37120346-fdf4-40de-a21d-cad2d2b55704.png)
It got up to about 1700 of this block required, then reset and started listing all the resources required.
I tried to do the /mc citizens info when the number or resources reset 9not sure if I was fast enough) but it still said "load structure"

**Comment by Talyda** [comment]
1755 of that block, then resets and starts counting again. She doesn't physically move at all as far as I can tell, just standing there with a creative DO block in her hand

**Comment by Talyda** [comment]
Just went back in to the first game save and it is doing the same thing  (different amounts, cos that one dug further, but same behaviour)

**Comment by Raycoms** [comment]
I got a lead. It's weird

**Comment by Talyda** [comment]
Well, if you think it's weird, I had bugger all chance of trying to troubleshoot it =D

**Comment by Raycoms** [comment]
I loaded your world, and it tries to place some cobblestone in a place where a normal placeholder is apparently.

**Comment by Raycoms** [comment]
but the resource list disagrees, obviously. So it recalculates just to come to the same result

**Comment by Talyda** [comment]
Yeah, I never ever would have figured that one out =D  Never would have even known where to start LOL!

**Comment by Raycoms** [comment]
Found it!

**Comment by Talyda** [comment]
Oh yay! =D
I really did want to test the quarry thoroughly!

**Comment by Raycoms** [comment]
Good find!
