### ISSUE TITLE
Hiring overwrite resets after a restart/reload

### ISSUE THREAD

**Issue by BrainInBlack** [ldtteam/minecolonies#8021]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 1.0.391-ALPHA
- Structurize Version: 1.0.339-ALPHA
- Related Mods and their Versions: N/A

## Expected behavior

Buildings to "remember" which hiring mode they are on, regardless of the overall colony setting.

## Actual behavior

Each restart I have to change the hiring settings to the desired mode again, from Colony default. In my case I have to set the Pupil hiring setting back to Automatic every time I start up the game.

## Steps to reproduce the issue

1. Change the hiring mode to something different than the colony default
2. Reload the save game
3. Profit?

### Logs

N/A

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Fix pushed, please tell me if it works

**Comment by BrainInBlack** [comment]
Will do, as soon the new version is available

**Comment by BrainInBlack** [comment]
Yerp, the fix is working. Though the game/server crashed after at first. Fixed it via a version rollback, loading the save and letting everything revert to default, i.e. let the initial issue happen, and then update to the new version.

[Client and Server Crashlogs](https://gist.github.com/BrainInBlack/0925c09bfe0de3f60a9cac3d2bf4b76a)
