### ISSUE TITLE
Game crashes when clicking the "Build Options" Button

### ISSUE THREAD

**Issue by derZCKR** [ldtteam/minecolonies#8022]
When I play on multiplayer and try to open the "Build Options"-Screen, my game crashes and gives the error down below.  It would be great if either this issue gets resolved or there is a workaround.
[crash-2022-02-04_21.11.27-client.txt](https://github.com/ldtteam/minecolonies/files/8005987/crash-2022-02-04_21.11.27-client.txt)

**Comment by MotionlessTrain** [comment]
Update to the latest alpha. This issue has been fixed already.

Also, could you please fill in the template?
