### ISSUE TITLE
Quarry requests for craftable items don't land at the respective professions

### ISSUE THREAD

**Issue by BrainInBlack** [ldtteam/minecolonies#8023]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 1.0.393-ALPHA
- Structurize Version: 1.0.339-ALPHA
- Related Mods and their Versions: N/A

## Expected behavior

Quarry request to be going to the respective professions, instead of the player.

## Actual behavior

All requests for craftable items land directly at the player instead of the respective professions. There are plenty of raw resources for the request to be fulfilled by the respective profession.

## Steps to reproduce the issue

N/A

### Logs

N/A

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by BrainInBlack** [comment]
This was a food supply issue, not a bug

**Comment by BrainInBlack** [comment]
Looks like the food was not the issue.

**Comment by Talyda** [comment]
Adding that I tested it in my test world in 1.18 cos I thought I remembered that happening yesterday, and it is - for me I tested with the DO blocks. Quarry worker needs them to continue, and I have a sawmill with the recipes saved, materials to make them in the warehouse, but the request is showing "resolver player" on the clipboard
(oh, version ending in 94)
I was too focused on the other bug yesterday, and thought i had just done something wrong teaching the recipe and ignored it =P

**Comment by Raycoms** [comment]
fix pushed
