### ISSUE TITLE
Builder returning to completed projects to construct the next in queue

### ISSUE THREAD

**Issue by Aduis1210** [ldtteam/minecolonies#8024]
- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

- Minecraft Version: 1.18
- MineColonies Version: minecolonies-1.18.1-1.0.394-ALPHA
- Structurize Version: structurize-1.18.1-1.0.341-ALPHA
- Related Mods and their Versions: MC official pack.

## Expected behavior
Builder to path to current project and construct as normal

## Actual behavior
Builder returns to previous project to build the next project

![2022-02-04_20 35 41](https://user-images.githubusercontent.com/56609195/152599787-87395810-b660-4511-9640-cecfc4bb7025.png)
![2022-02-04_20 35 56](https://user-images.githubusercontent.com/56609195/152599795-3d37529b-f6c2-48ca-a7a3-1ce35957e1ee.png)

## Steps to reproduce the issue

1. Ask builder to build.
2. let them complete a project
3. watch as they move back to the completed project to build the next project.

### Logs

No errors

### Notes
Happy to provide world

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Aduis1210** [comment]
Also noticed they aren't pathing back to the builders hut when they require materials they don't have in inventory or in Hut

**Comment by BrainInBlack** [comment]
Can confirm this behavior under 1.16.5 with version 1.0.393-ALPHA

**Comment by Raycoms** [comment]
The pathing back I found too, the other one I'm still trying to reproduce

**Comment by Raycoms** [comment]
Any easy way to reproduce this?

**Comment by Aduis1210** [comment]
doing some testing on latest minecolonies-1.18.1-1.0.397-ALPHA

**Comment by Moobien** [comment]
confirmed in 416 for 1.18.1

**Comment by Raycoms** [comment]
fixed
