### ISSUE TITLE
Crash related with Farmer

### ISSUE THREAD

**Issue by Ret44** [ldtteam/minecolonies#8025]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.18.1
- MineColonies Version: 1.0.278-RELEASE
- Structurize Version: 1.0.36-ALPHA
- Related Mods and their Versions: N/A

## Expected behavior
After several hours on our custom mod pack server, we planned to create a first farmer hut and assign two fields at same time to that hut.

## Actual behavior
After one of the players set upgrade to the Farmers Hut, and then assigned new fields, server crashed as soon as daytime started, dropping "java.lang.NoSuchFieldError: DIRT" exception in the logs. From now on, everytime server is restarted, after any connection attempt, server crashes immediately dropping the same exception.

## Steps to reproduce the issue

1. Setup field, and assign them to Farmers hut.
2. Wait for daytime, so farmer could start his work.

### Logs

- latest.log: (https://gist.github.com/Ret44/2ed6ad6dc2ed296eb44d3a8249033759)
- crashlog: N/A

### Notes
Tried updating mod to 1.0.394-ALPHA but this version crashes both client and the server on startup. 

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
This is the DIRT error, which just means that you need to update to the latest alpha (or downgrade Forge, but updating is easier).

Read the changelog on the curseforge site to find the correct version of Structurize to go with it, and make sure that you only have one copy of each mod in your mods folder -- the CurseForge client has recently had some bugs where it was not deleting old versions when updating, and the user-friendly "you're using the wrong Structurize version" was not shown.

**Comment by Ret44** [comment]
Just to be clear: What exactly I should upgrade to the latest alpha? MineColonies, Structurize, any other dependency or Forge?

If you meant MineColonies, as I pointed out on Notes latest alpha crashes the client at startup with 
"Error: java.lang.NullPointerException: Registry Object not present: findme:particle" 
crashlog: https://gist.github.com/Ret44/4cf6a957578b9729d2a6cac770514a9a

Structrize was also updated to the version mentioned in file changelog.

**Comment by uecasm** [comment]
> What exactly I should upgrade to the latest alpha? MineColonies, Structurize, any other dependency or Forge?

Yes.  (Update minecolonies to latest alpha.  Update structurize to the exact version that wants.  Also update BlockUI and other dependencies of minecolonies to the latest versions of those, alpha or otherwise.)

> If you meant MineColonies, as I pointed out on Notes latest alpha crashes the client at startup with
"Error: java.lang.NullPointerException: Registry Object not present: findme:particle"
crashlog: https://gist.github.com/Ret44/4cf6a957578b9729d2a6cac770514a9a

You just said that there was a crash before, you didn't say what -- and as mentioned above if you're not changing anything else then mismatched versions are the most likely cause of crashes.

Having said that, that particular crash does not appear to be related to minecolonies in any way.

**Comment by Ret44** [comment]
Updating journeyMap to the lastest version fixed client crash. Updated JEI to the latest version as well just to be sure, and then I've  reuploaded modpack with updated mods to the server - it started without problems, and DIRT error is gone. Thanks for the help!
