### ISSUE TITLE
Ancient tomes not dropping from raids

### ISSUE THREAD

**Issue by Estyria** [ldtteam/minecolonies#8026]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.18.1
- MineColonies Version: 1.18.1-1.0.394-ALPHA
- Structurize Version: 1.18.1-1.0.341-ALPHA

## Problem description
I have been playing a 1.18.1 world for a couple hundred in game days at this point (weeks in real life) and have only gotten one ancient tome from a raid waaaay back when I first started this save. If that. It's been long enough now I'm wondering if I just creatived it in. I've had probably more than twenty raids with no drops. In fact I don't think they've dropped armor or weapons either, but those are harder to track.

### Notes or related things

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by someaddons** [comment]
They drop weapons and tomes as intended for me, which raider entities did you face?

**Comment by Estyria** [comment]
Amazons, norsemen, and vikings.

**Comment by Estyria** [comment]
And regular barbarians I think

**Comment by someaddons** [comment]
regular barbarians/amazons work fine, but norsemen are actually missing loot

**Comment by Estyria** [comment]
I'm in a taiga, fairly landlocked, so the norsemen are the bulk of the raiders that I face. I had a barbarian raid this morning that dropped a single iron axe.
