### ISSUE TITLE
Villages duplicates

### ISSUE THREAD

**Issue by Scampi-ml** [ldtteam/minecolonies#8036]
### Prerequisites 

- [X ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 
![image](https://user-images.githubusercontent.com/1528455/152658876-0bf9cd6a-0ad4-4159-bce1-89a3a09eed3a.png)
Villages have duped themself s at the workbench, and the one "original" is working somewhere else

- Minecraft Version: 1.18.1
- MineColonies Version: minecolonies-1.18.1-1.0.378-ALPHA.jar
- Structurize Version: structurize-1.18.1-1.0.340-ALPHA.jar
- Related Mods and their Versions: None

## Expected behavior
They do not dupe themselfs

## Actual behavior
single villages

## Steps to reproduce the issue
I have no idea how it happens

### Logs
Nothing in the logs

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
As I said on the other issue, this is a vanilla bug, not a minecolonies bug. Restarting the game again should fix them.

**Comment by Scampi-ml** [comment]
Is there something we (or you) can do to prevent this from even happening?

Thx

**Comment by MotionlessTrain** [comment]
Not really. The team already tried to mitigate it, but they can’t prevent it completely
