### ISSUE TITLE
Workers stay at town hall

### ISSUE THREAD

**Issue by Greydman24** [ldtteam/minecolonies#8037]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.18.1
- MineColonies Version: 1.0.402
- Structurize Version: 1.0.341
- Related Mods and their Versions: multi piston- version 1.2.2
- domum_ornamentum verion 1.0.39

## Expected behavior

   i would expect that workers go to their work stations and work

## Actual behavior

 workers will go to their work station and then turn around and go to the town hall and gather around where the enderdragon head would be for a lv.5 town hall. no other things that would affect their work (like weather, time, raids) are present. and the status of the workers is "working". i have allready tried things in the wiki, like re calling them,and pausing them.

## Steps to reproduce the issue

you start playing the game as normal. make builders huts, houses, farms, ect. eventually, they will all just go to the town hall and stand there with the status "working".

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Is there a way to reproduce this? Does it stop on restart?

**Comment by Greydman24** [comment]
it dose not stop on restart, as soon as workers resive their materials, they go to the town hall.

**Comment by Raycoms** [comment]
Can you try the latest alpha/beta?

**Comment by MystiaTech** [comment]
So, after some further testing myself on the 1.16.5 latest version of 401 until something newer comes out, it looks like if you cancel all pre-existing work orders if you recently updated to 401 or newer, the builders get stuck.

**Comment by MotionlessTrain** [comment]
> Can you try the latest alpha/beta?

Unfortunately, 401 and 402 are the latest versions available at the moment. None of the later versions managed to build correctly, so there is not fixed version available at the moment.

**Comment by Raycoms** [comment]
I just made sure a new one is built, please test that one.
