### ISSUE TITLE
[1.16.5] Builders/Citizens not doing work/stalling at the townhall

### ISSUE THREAD

**Issue by MystiaTech** [ldtteam/minecolonies#8038]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 1.16.5-1.0.401-ALPHA
- Structurize Version: 1.16.5-1.0.339-ALPHA
- Related Mods and their Versions:
 Journeymap-1.16.5-5.8.0beta12
 JMI-1.16.5-0.8.45

## Expected behavior

Builders build the project they are given resources for and return to the next project
## Actual behavior

Builder is given all items for project, then heads to the top of the townhall and stands there. Status shows they are working but nothing is done. Fired them and let the colony re-hire as appropriate. replacement builders are doing the same thing even the farmer and knight that the original builders had changed their jobs to were doing the same thing and they had everything. I even rebooted the server and restarted the workers schedule

![2022-02-06_11 20 46](https://user-images.githubusercontent.com/2319526/152690503-5c1fcd9c-f851-43c2-8bdb-17bee0fc696a.png)
![2022-02-06_11 21 00](https://user-images.githubusercontent.com/2319526/152690504-8dc12c59-b1a5-4876-98a0-443301a493eb.png)
![2022-02-06_11 21 37](https://user-images.githubusercontent.com/2319526/152690505-31a78a56-782c-4a2a-9824-827e08277353.png)

## Steps to reproduce the issue

1.  Assign a builder any upgrade/build
2.  Supply them with all the resources
3.  Watch them stop at the townhall and not work.

### Logs

- latest.log: https://gist.github.com/Advtech92/e0d94ba3ab4e4289b39c7ecd1c6925a0
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
duplicate https://github.com/ldtteam/minecolonies/issues/8037, please try to reproduce with latest
