### ISSUE TITLE
Tick overload

### ISSUE THREAD

**Issue by Nick777777712** [ldtteam/minecolonies#8040]
### Prerequisites 

- [ yes] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [yes ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ yes] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.18.1
- MineColonies Version:1.18.1
- Structurize Version:1.18.1
- Related Mods and their Versions:1.18.1

## Expected behavior
Not crash everytime i start the game

## Actual behavior
 I load a world and in less than a minute the game stops and I get a crash report with ticking entity
Error. The report menches alot about minecolonie entitys

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

<script src="https://gist.github.com/Nick777777712/f252ed713098e5e15e39474b3618f936.js"></script>

- latest.log: 
- crashlog: 

### Notes

Please let me know If i can do anything. another email you can reach me at is 1vangemertni@hdsb.ca
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
This is the DIRT incompatibility; just update to the latest alpha and compatible dependency versions.

Also, you picked something weird when generating the gist link.  It shouldn't be a js file.

**Comment by Nick777777712** [comment]
Update to the latest versions on minecolonies?

**Comment by Nick777777712** [comment]
yes
