### ISSUE TITLE
My Game Crashed In Build Options

### ISSUE THREAD

**Issue by DaftTheMonkeMan** [ldtteam/minecolonies#8042]
- Minecraft Version:1.18.1
- MineColonies Version: minecolonies-1.18.1-1.0.278-RELEASE.jar
- Structurize Version: structurize-1.18.1-1.0.341-ALPHA.jar
- Related Mods and their Versions:

## Expected behavior
To Build Buildings

## Actual behavior
when i go to the build buildings in build options its crashes

## Steps to reproduce the issue

1. place build hut
2. open build options
3. click build buildings
4. crash

### Logs

- crashlog: (https://gist.github.com/DaftTheMonkeMan/b7d0528dc96d655f3aedd085e647812c)

**Comment by uecasm** [comment]
Forge broke a thing.  Update to the latest alpha and the matching dependencies.  Make sure you don't have older duplicates installed (curseforge hasn't been removing old versions recently).
