### ISSUE TITLE
Field issues

### ISSUE THREAD

**Issue by pantsguyapp** [ldtteam/minecolonies#8043]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- MineColonies Version:
- Structurize Version:
- Related Mods and their Versions:

## Expected behavior

Farmers cannot use the pumpkin field recipe
The pumpkin field model has the carved texture for pumpkin and they are crafted from a normal pumpkin.

## Actual behavior

They will be able to.
Also the pumpkin recipe include a normal pumpkin instead of a carved one.

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Intended
