### ISSUE TITLE
Translation strings are getting "untranslated"

### ISSUE THREAD

**Issue by Ampaex** [ldtteam/minecolonies#8048]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- MineColonies Version:
- Structurize Version:

## Problem description

These strings are getting "untranslated"(appears untranslated after a couple days) very frequently, the "new" string seems the same. This happened like 6 times, with all the strings that can be seen in the capture.
![image](https://user-images.githubusercontent.com/9005862/153045626-b6e0d93d-41ad-41a3-8a06-9e69c73f8f97.png)
I don't know if this is intentional but I think it shouldn't happen. It's a little bit annoying because crowdin is constantly spamming my email saying that there is new strings to be translated but always are the same.

### Notes or related things

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
There have been some translation id changes recently, where a string was renamed (most commonly just changed from mixed-case to all-lowercase, due to new Minecraft id requirements).  That's possibly what you're seeing there.
