### ISSUE TITLE
it does not work or detect structurize

### ISSUE THREAD

**Issue by stefanobarbon** [ldtteam/minecolonies#8049]
- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

- Minecraft Version:1.16.5
- MineColonies Version:1.16.5-1.0.425-ALPHA
- Structurize Version:1.16.5-1.0.343-RELEASE

i used the version it said but does not detect it
![imagen](https://user-images.githubusercontent.com/62155792/153084687-70c68a14-f327-411d-97f7-b0e54f1e7900.png)

![imagen](https://user-images.githubusercontent.com/62155792/153084557-b128072a-074d-4073-8df0-59cf8f5c0f48.png)

**Comment by Talyda** [comment]
You should fill the template out properly BTW
~~The error message at the top is formatted oddly, you have the wrong structurize.
Go here 
https://www.curseforge.com/minecraft/mc-mods/minecolonies/files/3641457
read the changelog, it tells you which versions you need there~~

~~You don't seem to have the other needed dependencies either~~ (oh, ignore that, this is 1.16.5 - my bad!)

**Comment by stefanobarbon** [comment]
brUh

**Comment by MotionlessTrain** [comment]
> The error message at the top is formatted oddly, you have the wrong structurize. Go here https://www.curseforge.com/minecraft/mc-mods/minecolonies/files/3641457 read the changelog, it tells you which versions you need there

It might be me, but it seems like the changelog tells you to use 1.0.343-Release, which is the installed version

> You don't seem to have the other needed dependencies either

This is an 1.16 version, so Structurize is the only required dependency
