### ISSUE TITLE
1.10 gets updated, but 1.11 does not

### ISSUE THREAD

**Issue by SulpherStaer** [ldtteam/minecolonies#805]
### Minecolonies version

version 1.11

### Expected behavior

- When an update is published on curseforge, 1.10 and 1.11 both get updated

### Actual behaviour

- Only 1.10 was updated 17 hours ago, 1.11 still is 6 days behind.

### Steps to reproduce the problem

1. Observe the curseforge project of minecolonies.

**Comment by xavierh** [comment]
Update do not happen magically and require work and time.
