### ISSUE TITLE
1.5.2 release 

### ISSUE THREAD

**Issue by nagol2003** [ldtteam/minecolonies#8050]
### Prerequisites 

- [ ] I can’t seem to find the mod download for Minecraft version 1.5.2. Any help?

**Comment by Raycoms** [comment]
Neither can I.

**Comment by nagol2003** [comment]
> Neither can I.

Fair, but could you tell me if it at least a exists? Was it even made on this version?

**Comment by Raycoms** [comment]
It was made for that version. But it's unlikely to find it.
