### ISSUE TITLE
Mercenaries are better than guards when it comes to killing things

### ISSUE THREAD

**Issue by pantsguyapp** [ldtteam/minecolonies#8057]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- MineColonies Version:
- Structurize Version:
- Related Mods and their Versions:

## Expected behavior

Guards will be superior to Mercenaries in protecting duty.

## Actual behavior

Mercenary can attack mobs from further away than guards, meaning they are less likely to get hit by a mob, while guards will have to walked into the mob and risking being hit, guards hitting range needs to be extended.
Mercenary detects mobs faster, whereas guards can walk pass an enemy without even noticing, I tested this by spawning in a zombie next to the guards and a mercenary, and the mercenary went for the mob while the guards are still clueless.

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by pantsguyapp** [comment]
Right now, an Iron Golem, the dumb golem that was mean to be an idiotic protector, is better at detecting nearby threats than 20 of your barrack tower guards.

**Comment by Raycoms** [comment]
The dumb golem also takes 100x as much computational resources.
