### ISSUE TITLE
All recipes got erased when I deleted one recipe while its lagging.

### ISSUE THREAD

**Issue by pantsguyapp** [ldtteam/minecolonies#8058]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- MineColonies Version:
- Structurize Version:
- Related Mods and their Versions:

## Expected behavior

One click = one recipe deleted

## Actual behavior

I tried to erase the iron stuff recipes in my blacksmith's hut, and while I was mass deleting stuff a lag happen and when its over every recipes got deleted, and I had to teach all the recipes to the blacksmith again

## Steps to reproduce the issue

Not sure if you need a lag to happen, basically just teach lots of recipes then try to delete some by rapidly clicking and see if the bug happened.

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
It deletes one recipe per click, if you click 10x it deletes 10 recipes. If there is lag, it counts the 10 impatient clicks

**Comment by pantsguyapp** [comment]
But the thing is that the recipe amount I had was way over the numbers of click and one lag erased all. After the lag all the recipes, even the custom ones was gone, basically a blank GUI, I exited out and reenter and there was only the custom recipes.
