### ISSUE TITLE
[1.16.5] Citizens struggle to go up stairs.

### ISSUE THREAD

**Issue by Sandriell** [ldtteam/minecolonies#8062]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5 (Dedicated Server)
- MineColonies Version: minecolonies-1.16.5-1.0.432-ALPHA
- Structurize Version: structurize-1.16.5-1.0.343-RELEASE
- Related Mods and their Versions: https://gist.github.com/Sandriell/0688b4e8e61c46e1bd44c36ad9ff6fc0

## Expected behavior

Smoothly walking up stairs.

## Actual behavior

When climbing stairs citizens struggle to go up them and will jump and spin around with every step slowing them down considerably.   Only occurs on stairs, not when just jumping up blocks, and no issues going down.

## Steps to reproduce the issue

1.  Have Stairs
2.  Watch them struggle
3.  Profit?

### Logs

- latest.log: N/A
- crashlog: N/A

### Notes

If more information is needed, let me know, but not sure what else to provide as there is no logs or anything associated with an issue like this. Just hoping it is easily something the devs can see happening.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
Just adding to this, we've seen an increase of people reporting it over approximately the last two weeks, so not sure if anything changed in it recently

**Comment by Raycoms** [comment]
Does this only happen when you place them, or even long placed stairs?

**Comment by Sandriell** [comment]
Happens all the time with all stairs, no matter how recently or long ago they were placed.

It's definitely not like the issue you get with just placed blocks and the pathfinding hasn't updated.

**Comment by Talyda** [comment]
I don't know if it would have anything to do with it Ray, but in the same time frame, we have had a lot more reports of colonists drowning too - though nobody has made a report for it yet as far as I know (like I said, no idea if it is related)

**Comment by iloveShaders** [comment]
Same on 1.18.1 but singleplayer, not sure when it started to happen because I always update to newest version.
The good example is Builder Hut tier 2 with medieval birch style.
Builder just walks back and forth trying to get out from the cellar, he tries to make a turn too early on the last step a he just slides back to bottom and up again for like 6~ times.
Then he finally continues working after a few seconds and continues walking as he should ?
And same for the guards when they got into builders hut cellar. Then it is a party on the stairs along with the Builder.
