### ISSUE TITLE
Problems with miners digging mines

### ISSUE THREAD

**Issue by KuroPeach** [ldtteam/minecolonies#8063]
**Prerequisites**
[x ] I am running the latest alpha version of MineColonies and Structurize for my Minecraft version.
[x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
[x ] I made sure that this issue is not a duplicate of any existing issue.

**Context**
Minecraft Version: 1.16.5 (Dedicated Server)
MineColonies Version: minecolonies-1.16.5-1.0.430-ALPHA
Structurize Version: structurize-1.16.5-1.0.342-RELEASE
Related Mods and their Versions: 

**Expected behavior**
normal construction mine 

**Actual behavior**
When building a mine floor, miners dig up cobblestone and replace it with netherrack

**Steps to reproduce the issue**
When miners build a mine

**Logs**
latest.log: N/A
crashlog: N/A

**Notes**
I used a warped-style building in the main world. At this time, when the miner places the ladder, the block behind it will be placed into cobblestone, and this style of mine branch ladder is behind the nether rock, so there is a problem.

Cobblestone is used by default when placing ladders even though I set the replacement to netherrack.

Excuse my bad english, this is translated using google, hope you can understand.

![20220213181217](https://user-images.githubusercontent.com/19620848/153748437-b89d985a-f7c9-4d5f-a802-5bf11e714b29.png)
![20220213181446](https://user-images.githubusercontent.com/19620848/153748539-cf767526-efd3-4510-a29d-dcf33231029d.png)

**Comment by MotionlessTrain** [comment]
Could you please fill in the entire template please?

**Comment by uecasm** [comment]
Was this a custom style or a built-in one?  Having cobblestone behind the main shaft ladder in the miner is mandatory, due to the way that things work internally.

**Comment by KuroPeach** [comment]
In this case, just only manually modify the blueprint, change the ladder attachment in the blueprint to cobblestone?

**Comment by Raycoms** [comment]
The warped mine is actually only supposed to work in the nether at the moment. It uses netherrack and material everywhere. It also relies on a different block behind the ladder yes. If you want to adjust that you can make a feature request on the feature request repo.
