### ISSUE TITLE
Increase RAM usage

### ISSUE THREAD

**Issue by DrSigma4164** [ldtteam/minecolonies#8064]
### Prerequisites 

- [ x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 1.0.434-BETA
- Structurize Version: 1.0.343-RELEASE

## Actual behavior
I run minecraft with the following parameters: "-Xms6G -Xmx12G -XX: + UseConcMarkSweepGC", where I actually indicate that I use a garbage collector. During the game, my memory usage is 7-8 GB, and this compiler works great and the usage jumps to only 300-400 MB. But after some actions, I do not quite understand after which but for some reason I think that after the backup, it seems that this parameter: "-XX: + UseConcMarkSweepGC" is turned off because memory usage jumps from 8 to 12 GB, and I no longer have RAM memory so I start to freeze and I need to re-enter the game. This happens when I am in my friend's city, where I actually live. I have tried many different mods for backups, for example: FTB Backups, OpenBackup, and this problem always occurs after the second backup. Below I attached the latest.log and debug.log, they were saved after I hung and could not even turn off minecraft normally and had to stop the process through the task manager.

## Steps to reproduce the issue

1. Run minecraft with the following parameters: "-Xms6G -Xmx12G -XX: + UseConcMarkSweepGC"
2. Wait for second backup
3. Live as memory usage increases

### Logs

- latest.log: https://gist.github.com/9ba35ae40dc6352251db1b3e41d82485.git
- debug.log: https://gist.github.com/0e1a5b99db1d272b99173976abbcdb10.git (I inserted only the second half of the file because it is too large)

**Comment by Raycoms** [comment]
I'm not sure how this is related to MineColonies and not potentially just a general support question for the discord.

**Comment by DrSigma4164** [comment]
Now I went to the city and my memory usage rose from 7 GB to 12.5 GB. What could be the problem is the conflict? Is this some kind of structure from our fashion so threatening? I attach a log file. At the end of the file, this moment is captured
https://gist.github.com/e7f9dd97e965fc54f24290febf53a8a7.git

**Comment by uecasm** [comment]
Try upgrading Journeymap.  There's some known memory issues in beta12-14 that beta15 fixes.

**Comment by DrSigma4164** [comment]
It didn't help. When I leave the colony I do not lag, but when I approach the opposite. Also, I don't know if it means anything, but when I press ESC the lags on the graph decrease as shown in the screenshot (in the purple frame it is when I press ESC)

debug.log - https://gist.github.com/90f1f2bf4e5b98a505a1d4ca42698a0f.git
latest.log - https://gist.github.com/51acc3d7d9652075854ac8d4e38e5770.git
![image](https://user-images.githubusercontent.com/93322905/153896096-24cd4d50-bda7-4349-a78e-7b6c8f4dd807.png)

**Comment by Raycoms** [comment]
There could be many things in the colony, aside of our colonists that could cause that lag for you. Would need at least a client side spark report

**Comment by DrSigma4164** [comment]
And how to make this spark report?

**Comment by DrSigma4164** [comment]
I think I understand what you're talking about. Also tried to make a profile, link below.
https://spark.lucko.me/KAznq9nCj1

**Comment by Raycoms** [comment]
Lycanite mobs seems to take an enormous chunk here.

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

------- Original Message -------

**Comment by DrSigma4164** [comment]
I have already written to the developers will be waiting for answers. However, I deleted this mod two days ago, but the lags and memory load were still there, although maybe this JourneyMap on the beta version behaved like that ..... I don't know ...

**Comment by DrSigma4164** [comment]
Now I have left the city, and my friend is now standing in the middle of the city and "communicating with the residents" and he and I do not like. What could this mean?

**Comment by DrSigma4164** [comment]
I turned off Lycanite's mods, but still when I come to town lags. I bought 16 GB of RAM and it fills up to 16 GB after a certain time, preferably 10 seconds when I'm in town
https://spark.lucko.me/zx1ZI9Nzas

**Comment by Raycoms** [comment]
never give java 16gb, give it at most 8gb, java will always fill up to the max

**Comment by DrSigma4164** [comment]
When I removed the Journey Map mod, the lags stopped. And I allocated 16 GB because if it was less I could not even move, but enough 10 according to experiments

**Comment by uecasm** [comment]
If you're still having problems with JM beta15, then report it to their GH -- they're very interested in hearing about any memory issues remaining in that version (it's a known issue in beta12-beta14).

**Comment by DrSigma4164** [comment]
I have already reported and we are solving this problem. Thanks
