### ISSUE TITLE
Pirate ship spawned inside of colony borders

### ISSUE THREAD

**Issue by SerranoPancake** [ldtteam/minecolonies#8065]
### Prerequisites 

- [X ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.18.1
- MineColonies Version: minecolonies-1.18.1-1.0.430-ALPHA
- Structurize Version: structurize-1.18.1-1.0.342-RELEASE

## Problem description
Pirate ship spawned inside of colony borders destroying my enchanter's tower

### Notes or related things

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.
![image](https://user-images.githubusercontent.com/20136617/153778603-95e6629c-6ba3-404b-b619-43512ef72623.png)

**Comment by Raycoms** [comment]
Not a bug. The minimum distance is based on guard towers. So you'd want more guard towers alongside the river
