### ISSUE TITLE
Citizens run away a small distance when a monster attacks them, then stand still

### ISSUE THREAD

**Issue by pantsguyapp** [ldtteam/minecolonies#8066]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- MineColonies Version:
- Structurize Version:
- Related Mods and their Versions:

## Expected behavior

The citizen awares that there is a monster nearby and proceed to run into somewhere safe.

## Actual behavior

The citizen firstly run away, then quickly stop, stand still, got hit, repeat until they got killed.
Sometimes this happened to citizens that strayed too far from the colony, basically they just accept that they're going to die.

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Sandriell** [comment]
I have always disliked this and it is the reason I personally keep mob damage turned off. As it stands now, a cow tries harder to get away from being killed than a minecolonies citizen does.

A few ideas I had is they should ideally run towards the nearest guard, run into the nearest building (closing the door behind them of course), or run home.

**Comment by Raycoms** [comment]
if citizens can run away "faster for forever" than the mob can walk, they will never die and there is no danger element anymore unless maybe it's a skeleton. This is intentional. They run away fast enough to hope there is a guard closeby. If you got enough guards this should mostly be fine. Once citizens reach a health limit and you got a hospital, they try to get there.

**Comment by pantsguyapp** [comment]
I got a hospital and they don't care about going to it.
"there is no danger element anymore unless maybe it's a skeleton." The whole world at night is dangerous if left unlitted, guards are inefficient and will come to only one threat while ignoring others, you can have lots of guards but if there are multiple citizens being under attacked then it is simply not going to cut it.
"if citizens can run away "faster for forever" than the mob can walk" surely they can, but it would make it so that they last more to call for guards, definately better than just stand there like an idiot, just give back their awareness to the monster and have them run far from them.
