### ISSUE TITLE
Unnamed Graves can't generate over water/lava

### ISSUE THREAD

**Issue by pantsguyapp** [ldtteam/minecolonies#8069]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- MineColonies Version:
- Structurize Version:
- Related Mods and their Versions:

## Expected behavior

The grave replaces the flowing block and generate

## Actual behavior

It doesn't, meaning that citizens inventory is potentially lost.
Tested with my citizen death trap:
We have a grave plus a citizen dying
![2022-02-15_09 19 39](https://user-images.githubusercontent.com/92203672/153980815-40b8b3f0-404d-4307-9390-5f100520ce19.png)
The citizen died but nothing spawned.
![2022-02-15_09 19 49](https://user-images.githubusercontent.com/92203672/153980868-b63d13ae-12a3-4973-bcb8-571e2791259f.png)
One more time.
![2022-02-15_09 20 15](https://user-images.githubusercontent.com/92203672/153980899-edc0a399-b856-439b-9508-1aa87100f647.png)
Nothing happened
![2022-02-15_09 20 22](https://user-images.githubusercontent.com/92203672/153980927-41b4bcb2-c9c1-4c4c-b56c-3901248d00d8.png)

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
duplicate
