### ISSUE TITLE
Mechanic and Blacksmith taking extra unnecessary steps to make iron ingots

### ISSUE THREAD

**Issue by pantsguyapp** [ldtteam/minecolonies#8070]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- MineColonies Version:
- Structurize Version:
- Related Mods and their Versions:

## Expected behavior

The storage block recipe shouldn't be used that much.
The courier delivers the ingots straight to the blacksmith for easy crafting

## Actual behavior

The courier delivers the iron ingots to the mechanic to be crafted into blocks, then deliver the ingots to the blacksmith.
![2022-02-15_09 06 22](https://user-images.githubusercontent.com/92203672/153981492-2d9ffd80-014c-42d3-a22b-65b71be5f683.png)
Thats the whole crafting tree, below are other separated recipes.

## Steps to reproduce the issue

1. Teach the mechanic iron block recipe
2. Teach blacksmith iron blocks into ingots.
3. Minimum stock something that requires iron ingots such as shields.

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
Having both recipes confuses the crafters indeed, and therefore it is not recommended to have both of them taught to the crafters.
Previously, it could have generated an infinite loop of crafting requests, now it at least stops after a few circular requests, which only gives a slight inconvenience

**Comment by pantsguyapp** [comment]
but I want to have both in case I WANT my mechanic to craft storage blocks of ingots, and I think everyone would want the same thing, they should address this and fix this instead of telling people not to teach some specific recipes.

**Comment by OrionDevelopment** [comment]
This is effectively not possible, we have talked about this in length before.
As of now it is simply performance wise not possible to simulate different crafting trees with the way entities behave and the performance cost that is associated with it.

Sorry.
