### ISSUE TITLE
Stash and postbox flags

### ISSUE THREAD

**Issue by SivartMcDorf** [ldtteam/minecolonies#8074]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.18.1
- MineColonies Version:
- Structurize Version:

## Problem description

No way to tell if box has been emptied or filled
### Notes or related things

Suggest a flag or color on box that for a stash if you put items in the flag turns red, if some items are taken it is yellow, if all are taken it is green, the opposite for the postbox for deliveries.
---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
There is a separate github for feature requests: https://github.com/ldtteam/minecolonies-features/issues
