### ISSUE TITLE
Unclaimed chunk in middle of colony that erases Town Hall and other buildings.

### ISSUE THREAD

**Issue by ghost** [ldtteam/minecolonies#8075]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context  

- Minecraft Version: 1.18.1
- MineColonies Version: minecolonies-1.18.1-1.0.437-ALPHA
- Structurize Version: structurize-1.18.1-1.0.346-ALPHA
- Related Mods and their Versions:

## Expected behavior
 No unclaimed land or erased buildings, able to upgrade without issue. 

## Actual behavior
 Upon starting the world up, the two buildings got erased from the colony and the land became unclaimed. 

 
![2022-02-15_21 16 26](https://user-images.githubusercontent.com/99777159/154183728-7679d289-72b5-4fcc-8555-ee537b7ad99d.png)

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes
 The Town Hall block within the 2 unclaimed chunks is still there, however I'm unable to upgrade the building

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
Someone has had this same problem in 1.16 on discord, you can see their post here:
https://discord.com/channels/139070364159311872/741531022872674314/941996367801356319

Also as I mentioned in that conversation, I have had a semi-similar (kinda =P) problem in my last two worlds at the 0,0 chunk - but I am still able to build in that chunk and it is still part of my colony when I /mc wherami - it just isually looks unclaimed
![image](https://user-images.githubusercontent.com/17323101/154191249-3d947cd6-d55d-4c91-b004-2ca0334f14ea.png)
Probably not at all related, but mentioning it in case!

**Comment by uecasm** [comment]
There is probably something in that chunk that crashed it and caused it to regenerate.

You can try manually reclaiming the chunk with `/mc colony claim 1 0 true` while standing inside the chunk (replace `1` with your actual colony id if different -- see `/mc whoami`).

If you can't run commands for some reason, then try building/repairing a building in a neighbouring chunk.

If it happens again, check logs to see if anything weird happened in that chunk.

**Comment by Raycoms** [comment]
Yeah, it's sth that can happen when Minecraft crashes and loses data. What @uecasm said will solve it.
