### ISSUE TITLE
Permissions update

### ISSUE THREAD

**Issue by Liloa** [ldtteam/minecolonies#808]
### Minecolonies version

I apologize for bad formatting, an Invasion collaborator sent me here and I am unfamiliar with GitHub

version 1.10.2 or curse X.X.XX

### Expected behavior

- Able to work in colony as normal

### Actual behaviour

- When I updated to a new version of the Invasion modpack by darkosto, I now do not have permission to do anything. I started using the minecolonies supply chest so that the ship would arrive and that I could use the bed and such from the supply ship. After this I made a townhall but I left it as is after this. Then there was an update in the modpack and all of a sudden I lost my permission and I made my base underground of the area that I happened to place townhall and supply chest. Darkosto suggested that I try to take out the mod and put it back in. Upon taking it out, I can do as I pleased and play like usual. But in the modpack there is a minecolonies questline. So I updated the pack again and put in my worldsave. Upon logging in I am once again having a permissions issue when I am using the same account that placed all blocks in the world in the first place.

### Steps to reproduce the problem

1. XYZ
2. ZYX
3. ...
4. Profit

**Comment by Raycoms** [comment]
did you try /mc colonies list (to find out your colony id)
and then /mc colony refresh id

2017-04-15 6:37 GMT-03:00 Liloa <notifications@github.com>:

**Comment by Liloa** [comment]
Thank you, problem seems to be fixed!

**Comment by Liloa** [comment]
I lied, it hasnt been fixed, I tried the suggestions

**Comment by Raycoms** [comment]
you tried using an older minecolonies.dat? from the backups?

2017-04-17 2:46 GMT-03:00 Liloa <notifications@github.com>:

**Comment by marvin-bitterlich** [comment]
closing this for now
