### ISSUE TITLE
Quarry miner bug?

### ISSUE THREAD

**Issue by willawe1** [ldtteam/minecolonies#8080]
The quarry miner seems to rebuild the medium quarry one block to the side after the builder has already built it. I have already tried firing and rehiring, repairing the building, restarting the individual and entire colony, and he still just proceeds to rebuild it, check on the required dependences and they are all at the correct version.

Minecolonies version: 1.18.1-1.0.441 ALPHA
Structurize version: 1.18.1-1.0.346 Alpha
![2022-02-20_00 55 52](https://user-images.githubusercontent.com/100061856/154830844-2c209907-9408-46ae-a8d4-e6fa40546a3e.png)
![2022-02-20_01 02 29](https://user-images.githubusercontent.com/100061856/154830845-e13028f2-d6fe-4605-b9fb-18bdf84a4ba1.png)
![2022-02-20_01 02 45](https://user-images.githubusercontent.com/100061856/154830846-ccb15db6-e0ad-4f68-b23a-d16f317f7e6e.png)
![2022-02-20_01 02 50](https://user-images.githubusercontent.com/100061856/154830848-3bdbe2f4-63f2-46bd-93da-33db83bc6183.png)

**Comment by LexiLeeRanson** [comment]
From what I can tell this is intended to create a stair case effect. If you check the ladder in the hut it should create a shaft directly down.

**Comment by Talyda** [comment]
Oh, actually I think this issue can be closed @willawe1 to be sure? You did test that a second time and it built properly didn't you?
