### ISSUE TITLE
Villager listed twice as parent to child villager

### ISSUE THREAD

**Issue by ketchakat13** [ldtteam/minecolonies#8082]
### Prerequisites 

- [x] I am running the latest 1.18.1-1.0.441-ALPHA version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 1.18.1-1.0.441-ALPHA

- Minecraft Version: 1.18.1-1.0.441-ALPHA
- MineColonies Version: 1.18.1-1.0.441-ALPHA
- Structurize Version: 1.18.1-1.0.346-ALPHA
- Related Mods and their Versions:

## Expected behavior
 Two different villagers listed as parents of child villager.

## Actual behavior
 Single villager listed as both mother and father of child villager.

![2022-02-17_20 39 38](https://user-images.githubusercontent.com/87506601/154862780-c5679bf9-9bf7-4a4c-b3ff-a7ee4f67e721.png)

## Steps to reproduce the issue

1. 1 villager in a house
2. have an available bed in your colony
3.  adult villager has child villager without a second adult villager in the house.

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
Note: It is possible for a child to only have one parent (they "adopted" this child), but I don't think that parent should be listed twice in the interface

**Comment by uecasm** [comment]
Were you previously running an older version of MineColonies?  This was a known bug in a previous version but it has (AFAIK) been fixed now.  But I don't think the fix will correct your existing citizens.

**Comment by Raycoms** [comment]
Forgot to port it. merged now
