### ISSUE TITLE
Wrong version of domum ornamental required

### ISSUE THREAD

**Issue by hotluck** [ldtteam/minecolonies#8083]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.18.1
- MineColonies Version: 428-RELEASE and 442-BETA
- Structurize Version: n/a
- Related Mods and their Versions: domum-ornamental

## Expected behavior

Minecraft would run

## Actual behavior

Both versions are asking for version 39 of domum-ornamental yet the latest version seems to be 31 (at least on curseforge)!

## Steps to reproduce the issue

Run Minecraft with either of those versions and the latest version of domum from curseforge
1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

Someone has added a comment on curseforge against domum ornamental about amending the minecolonies jar file - mods.toml file in the meta-inf folder to show 31 instead of 39 but not everyone can open jar files (myself included).
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
https://www.curseforge.com/minecraft/mc-mods/domum-ornamentum/files/all
Topmost one in the list (at moment of writing)

You probably needed to click the "View all" button which is somewhere on the files page on curseforge
