### ISSUE TITLE
Riders drops

### ISSUE THREAD

**Issue by Oscukitty** [ldtteam/minecolonies#8085]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- MineColonies Version:
- Structurize Version:
- Related Mods and their Versions:

## Expected behavior

Normal drops
## Actual behavior

Riders drop to much loot, like absurd amount of it , i killed one and filled 3 doble chest just from his loot, how can i solve these problem?

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
Please fill in the template.  But also, "riders" aren't a mob added by Minecolonies; did you mean something else or is this a modpack issue?  (Please direct modpack issues to the authors of the respective mods, unless you're certain that it's something specific to the modpack configuration itself, in which case use the modpack channel on Discord to report it instead.)
