### ISSUE TITLE
absurds amounts of drops

### ISSUE THREAD

**Issue by Oscukitty** [ldtteam/minecolonies#8086]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.18.1
- MineColonies Version:1.0.428
- Structurize Version:1.0.342
- Related Mods and their Versions:

## Expected behavior

Normal drops from barbarians
## Actual behavior

extreme amounts of drops when killed

![Películas y TV 21_02_2022 05_51_04 p  m](https://user-images.githubusercontent.com/50629408/155039629-ca76f4cf-c24b-4bae-9d8d-074a5d42825d.png)

## Steps to reproduce the issue

1. kill a barbarian
2. 
3.  extremes amounts of loot

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
That's another mod causing this, which alters mob drops. Not us.

**Comment by Oscukitty** [comment]
> 

there is no mod instaled that alters mobs loottables on death

**Comment by Raycoms** [comment]
Modlist?

**Comment by Oscukitty** [comment]
![mods 21_02_2022 05_58_39 p  m](https://user-images.githubusercontent.com/50629408/155040199-4984429a-30fb-4764-a5f2-8952339f4009.png)
![mods 21_02_2022 05_58_42 p  m](https://user-images.githubusercontent.com/50629408/155040203-308459b0-0120-4882-8b96-76416357da4a.png)

**Comment by Oscukitty** [comment]
> Modlist?

those

**Comment by Raycoms** [comment]
What kind of level of looting do you have on your weapon?

**Comment by Oscukitty** [comment]
> What kind of level of looting do you have on your weapon?

is not even the wepon even beare handed dropps these amounts of it

looting 3
