### ISSUE TITLE
[BUG] Ai issue aafter giving pickaxe latest.log Post

### ISSUE THREAD

**Issue by JacobFrodermann** [ldtteam/minecolonies#8093]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.0.428(occured) Update 1.0.451-> still

### Structurize Version

1.0.342(occured) Update 1.0.346

### Related Mods and their Versions

Forge 39.0.79
Block UI 0.0.43
Donum Orantmentum: 1.0.39-Apla
Optifine HD_H_U4

### Reproduction Steps

Builder(Lvl 1) builds tavern (needs to mine many blocks beacuse of a hill
I quit
I comeback
Builder needs Pickaxe
I give Builder damaged woodpick
Builder tells me to post log and does nothing
I update Mincolonies and Strukturize
Nothing changes

### Logs

https://pastebin.com/4rHeRvvg

### Anything else?

My Builder **told me to post it**, I wanted to help at the development of this great Mod

It took a Lot of time to create this report so pls pay attention too it, and if this is the wrong platform/way to post it pls specify the was to post it in the Message from the AI

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Can you reproduce this somehow?

**Comment by JacobFrodermann** [comment]
tried it two times with a stone shovel just took the builder a minuit to continue buidling
