### ISSUE TITLE
[BUG] After some time minecolonies produce a serialize error for cpw inventory sort causing netty.io disconnect

### ISSUE THREAD

**Issue by dandud100** [ldtteam/minecolonies#8096]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

minecolonies-1.18.1-1.0.448-ALPHA

### Structurize Version

structurize-1.18.1-1.0.346-ALPHA

### Related Mods and their Versions

Forge: 39.0.85
Inventory Sorter by cpw: [inventorysorter-1.18-19.0.0.jar](https://www.curseforge.com/minecraft/mc-mods/inventory-sorter/files/3543137)

(Modpack ATM7) Opened Issue here with some references and quick fix: https://github.com/AllTheMods/ATM-7/issues/526

### Current Behavior

https://github.com/AllTheMods/ATM-7/issues/526

### Expected Behavior

Joining normally

### Reproduction Steps

Can produce this only for my account when copying the bugged files back: [minecolonies bugged.zip](https://github.com/ldtteam/minecolonies/files/8148318/minecolonies.bugged.zip)

(I created the colonie. IGN: Pokemoon)

### Logs

https://github.com/cpw/inventorysorter/issues/112

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
None of the logs give any indication. The files shouldn't affect anything at all, they're mostly backups.
Can you please: Add the files back and then send us a server startup log until login attempt?

**Comment by dandud100** [comment]
[2022-02-27-2.log](https://github.com/ldtteam/minecolonies/files/8148709/2022-02-27-2.log)

**Comment by Raycoms** [comment]
And this only happens when you add back those files?

**Comment by dandud100** [comment]
> And this only happens when you add back those files?

yes, and after some time (and a server stop) the working files get corrupted again so i cant join and have to replace them again.

For example these are working files:
[colonies-2022-02-27_12.45.47.zip](https://github.com/ldtteam/minecolonies/files/8148729/colonies-2022-02-27_12.45.47.zip)

**Comment by Raycoms** [comment]
Shouldn't happen anymore
