### ISSUE TITLE
Sawmill Custom recipe - No input, teach, crash

### ISSUE THREAD

**Issue by IPromiseImFamous** [ldtteam/minecolonies#8098]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.18.1-7

### Structurize Version

1.18.1-1.0.342

### Current Behavior

Teach sawmill a custom recipe without any inputs, crashes client

### Expected Behavior

nothing

### Reproduction Steps

1. Open sawmill hut
2.  Custom recipe
3. Teach without inputs

### Logs

https://gist.github.com/IPromiseImFamous/775fc1a49923c7a713bd9814c185e6f8

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
That is correct. No input is free, they do no free stuff.

**Comment by MotionlessTrain** [comment]
But should minecraft crash if you leave all spots empty?

**Comment by MotionlessTrain** [comment]
I can understand that nothing happens when you click "teach", or that there is an error message in chat saying "Please select the ingredients!" or something like that. But I would not expect minecraft to crash. That is why I sent them to github

**Comment by Raycoms** [comment]
Ahh, this is not a custom recipe, this is attempting to teach a normal recipe? (Custom recipes are datapack recipes with minecolonies support)

**Comment by MotionlessTrain** [comment]
This is an architect's cutter recipe, which uses the "custom recipes" tab iirc

**Comment by Raycoms** [comment]
fix pushed
