### ISSUE TITLE
[BUG] Quarrier destroys blocks they placed in quarry

### ISSUE THREAD

**Issue by LexiLeeRanson** [ldtteam/minecolonies#8099]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.18.1-1.0.457

### Structurize Version

1.18.1-1.0.436

### Related Mods and their Versions

Domum Ornametum 1.18.1-1.0.39-ALPHA
Forge 39.0.85
BlockUI 1.18.1-0.0.43

### Current Behavior

Quarrier destroys blocks they placed

### Expected Behavior

THe quarrier places the blocks then continues to mine down

### Reproduction Steps

1. Place quarry
2. Assign miner
3. wait for them to mine down

### Logs

https://gist.github.com/LexiLeeRanson/bf1020753469692d2e956a102dd922b7

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Should be solved
