### ISSUE TITLE
[Feature] Market & Trading

### ISSUE THREAD

**Issue by Isfirs** [ldtteam/minecolonies#81]
### Minecolonies version

Future release
### Planned Features
- Having a probably expanding hut that is allowed to have `MarketStands` in its range.
- The `MarketHut` does nothing rather than provide space where `Market Stands` are allowed to be placed in.
- The `Market Stand` provided 2 use cases:
  - The owner is allowed to put stuff to `sell` into it and apply 1 or more items + amount to it.
  - The non-owner sees a list of `wanted` items and the `giving` items (Should be defined more to give a clear relation of what is wanted and what is needed)
  - Placing `wanted` items in results in showing a list of `giving` items. A bit comparable to the Villagers trading system.
### Addition notes

This system can be used as a basis to define the #5 `Anti-Grief` more. I would definitly focus on this system to have a more overlook of what our `Anti-Grief` will need.

**Comment by pmardle** [comment]
Ok my take on this is...

There is 1 market per colony, Upgradeable as per other buildings.

Upon building it has 1 worker assigned who is the "Master Trader" Worker  (Primary = Charisma, Secondary = Intelligence).. he doesn't actually trade himself, but wanders around the market making sure everything is ok.. :) - this is in effect the tax on trading as his food needs etc will be an ongoing cost to the player for having trading facilities, whether people trade or not.

At each level 2 NPC traders will spawn in the market (think re-textured Testificates)

Each NPC trader can hold one trade per 10 levels of the Master Trader (giving reason to level him up) 

Trades appear similarly to the Testificates trades, however the trade is set by the owning player (officer) of the colony, by having a GUI trade input screen (in the NPC) where you have a slot for the desired item,  a slot for the required item, and two sliders (1-64) for each item to set quantities.

This sets the trade in the NPC trader.

These traders (10 at max Market Level) walk around WITHIN THE CONFINES OF THE MARKET BUILDING and anyone Neutral or above to the colony can interact and trade with them in exactly the same way they would a village testificate. (Thus most of the code we need is already written) - A max level Market with a Max level Trader Worker will therefore have 10 NPC traders with 5 trades each - 50 possible trades :)

Now for the cool part.

For each NPC trader you have in your own Colony, you can spawn an exact copy of that trader in ONE other Colony you are Friendly to (or Higher), by visiting the other Colonies market place and opening the market GUI and hitting a "Spawn my trader" button, upon which a list of your possible 10 traders are there for you to select from.  Each of your 10 traders can only be spawned once, and you can only spawn 1 trader per other Colony, (so you can have 10 remote traders across 10 different colonies).

At any time an officer or above of a colony, can open the GUI of another persons trader and hit a "send back to owner" button to dismiss them from their colony.

These duplicates will share(mirror) the inventory of the "home" version of it.  if someone places a trader with the remote vendor, the goods received are added to the Market Chest in the HOME Colony, and Goods given are Taken from the inventory of the HOME version of itself.

The Home versions should I think not have their own inventories either, and all outgoing and incoming goods are done directly from the Home Market Chest.  I also think these traders (especially the remote ones) should be invulnerable.

Each Market can only accept a maximum of 2 remote traders per Level, so a max 10 in total giving a possible max 20 traders in any one location..

How awesome would this be :)

**Comment by marchermans** [comment]
#638 Should make this a possible.
The building would needed to be designed, but that should be possible.

**Comment by Raycoms** [comment]
Closed in favor of a joint issue
