### ISSUE TITLE
[BUG] Warehouse Builder Break

### ISSUE THREAD

**Issue by ItzBlazeMc** [ldtteam/minecolonies#8101]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

minecolonies-1.18.1-1.0.428-RELEASE

### Structurize Version

structurize-1.18.1-1.0.342-RELEASE

### Related Mods and their Versions

Forge = 1.18
Domum Ornamentum = domum_ornamentum-1.18.1-1.0.39-ALPHA-universal
BlockUI = blockui-1.18-0.0.34-ALPHA
Multipiston = multi-piston-1.18-1.2.2-ALPHA

### Current Behavior

I prepared a warehouse for my village as any would do. After a short while found a good place and got the construction underway (Yes i did the build building and all necessary steps to start a building. The building went all well, The overall building was done.
But in the interior when the builder placed racks, For some reason whenever my builder placed the racks next to each other, One of them would lose their textures and using f3 they turn into a variant of racks which is called "air" in minecolonies (the variant name might not be accurate). Afterwards the builder instead of placing torches to finish the build, Begins to break down the racks along with a bit of the floor. The builder after breaking a specific portion of the floor along with all the racks within the warehouse replaces the blocks + racks after destroying them. This "loop" repeats over and over again and the builder remains stuck here. Best i could do was cancel the build and focus on other builds, But if fixed i will be really thankful!

### Expected Behavior

The builder after completing the placement of racks, Places the torches and finishes the build to carry on with other tasks.

### Reproduction Steps

1 - Install the version of the mods of minecolonies mentioned above
2 - Construct the warehouse and watch as the builder completes the building exterior
3 - Wait and see until the builder goes inside for the interior to place racks
4 - This is at least what i did and it reproduced the issue, The behaviour should be that the builder gets stuck in a loop of breaking the racks and the floor and replacing them.

### Logs

No log is needed so far as i am aware, A simple fix or mod bug is all that's causing this.

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Can you try the latest alpha?

**Comment by ItzBlazeMc** [comment]
Same problem either way

**Comment by MotionlessTrain** [comment]
What style warehouse are you trying to build?

**Comment by ItzBlazeMc** [comment]
Medieval Spruce

**Comment by ItzBlazeMc** [comment]
Any idea how this is happening?

**Comment by Raycoms** [comment]
Which level to which level build/upgrade?

**Comment by ItzBlazeMc** [comment]
Its the first level,

**Comment by Raycoms** [comment]
Rotation, mirror?

**Comment by ItzBlazeMc** [comment]
Uh i have 0 clue what you mean by that-

**Comment by Raycoms** [comment]
When you placed the building did you rotate or mirror it?

**Comment by ItzBlazeMc** [comment]
I did rotate it to face towards the road i made, Yes

**Comment by Raycoms** [comment]
do you know by how much? 90, 180?

**Comment by ItzBlazeMc** [comment]
180

**Comment by ItzBlazeMc** [comment]
Am gonna call this a night for now, Leave questions here for me to answer if you have any. I will answer tommorow

**Comment by Talyda** [comment]
Fwiw I tested both med spruce and med spruce alt and both built and finished fine =)  Might be worth deconstructing and trying to build it again?
(minecol .463)

**Comment by Raycoms** [comment]
Couldn't reproduce it either

**Comment by ItzBlazeMc** [comment]
> Fwiw I tested both med spruce and med spruce alt and both built and finished fine =) Might be worth deconstructing and trying to build it again? (minecol .463)

Problem Being i did exactly that, I cancelled the construction and dismantled it (as the building wasnt completed i had to do it manually since there was no deconstruct option) So i destroyed the building and carried on, And the issue repeated

**Comment by ItzBlazeMc** [comment]
I had a couple mods along with this to form a modpack but even after removing all (including optifine and magnesium etc), Still carried on. Maybe some info such as the rotation is false, Il run a couple tests to see if i can try to reproduce it

**Comment by ItzBlazeMc** [comment]
Wait a minute, Is the file upload size on github limited? If not why not i just send you the world itself for troubleshooting-

**Comment by uecasm** [comment]
There's actually a command for that.  `/mc colony export <id>` will create a minimal copy of your world containing just the colony.

However, the problem is that the dev environment doesn't have any other mods installed, and it's not really possible to use a modpack.  So before you do that, it's best to try to reproduce it in a minimal SP world that only has minecolonies and dependencies, not any other mods.

**Comment by ItzBlazeMc** [comment]
> There's actually a command for that. `/mc colony export <id>` will create a minimal copy of your world containing just the colony.
> 
> However, the problem is that the dev environment doesn't have any other mods installed, and it's not really possible to use a modpack. So before you do that, it's best to try to reproduce it in a minimal SP world that only has minecolonies and dependencies, not any other mods.
To be fully fair its not even a modpack, And it doesnt have any mods that would affect the game in any way as stated above removing them and running Minecolonies still constitutes the same issue. Nevertheless il use the command and export the world to you all for troubleshooting, Hope this works!

**Comment by ItzBlazeMc** [comment]
[colony1Export.zip](https://github.com/ldtteam/minecolonies/files/8167293/colony1Export.zip)
e

Above is my minecolonies world, For reference here is a list of mods i used in it 
1 - Xaeros Minimap
2 - Jei
3 - Magnesium (aka sodium for forge)

The minecraft version is 1.18, Minecolonies and dependacies are at their latest versions.
Hope this gives insights as to how this is happening!

**Comment by Talyda** [comment]
Have you tried in a new world with the same mods?
Because at least two of us have tried to reproduce it and can't - so the problem isn't with the mod, it's with your world or your mod combination

**Comment by ItzBlazeMc** [comment]
The mod combination is what i have tested with and without the problem persists, As for the world i have already sent a copy of it to see if the issue persists for the other devs too. If it did not occur for any of you at all, Then honestly i am lost as to how this works, Only thing i can do is keep rebuilding it until it works somehow

**Comment by ItzBlazeMc** [comment]
Well if you cant find a solution for this, Then i suppose we have to call this matter a close as, I dont know about you but rather i am out of ideas to test any further-

**Comment by Raycoms** [comment]
Two small questions:
a) Can you upload a video of the builders behaviour (unlisted to youtube or so)
b) How long did you wait for the completion step?

**Comment by ItzBlazeMc** [comment]
The point (a) is not gonna work for me, since well as much as i dont want to admit it my pc will be unable to run obs along with mc 1.18, As for point (b) Answer is 15minutes

**Comment by Raycoms** [comment]
The last scan etc step might take in some cases a bit more than that. In my test I think it took around 20 minutes after the solid step was finished.

**Comment by ItzBlazeMc** [comment]
Hmm a feasible idea indeed, Aight then il deconstruct it and then leave it to rebuild for around a hour or less (depending if its done or not il keep checking) After its done il share the results if any

**Comment by ItzBlazeMc** [comment]
Alright finally dealt with it, Found the problem as well as managed to fix the warehouse.

The problem wasnt that i was not waiting rather i think it was the racks, Not all the time but sometimes when my builder places racks together to join them one of the racks would turn into a variant called "blockrackair". The solution is just to manually break the racks that are invisible and place them back where they belong, At least my problem got fixed so we can finally call this a close. Thanks Raycoms + talyda + uecoms + motionlesstrain for the support~
