### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by thaurane** [ldtteam/minecolonies#8102]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.0.455

### Structurize Version

This is the issue.

### Related Mods and their Versions

1. forge: 39.0.5
2. Blockui 0.0.43
3. domum 1.0.39

When trying to launch minecolonies 1.0.455 forge demands structurize version 1.0.346. However this version does not exist within curseforge https://www.curseforge.com/minecraft/mc-mods/structurize/files and https://www.curseforge.com/minecraft/mc-mods/structurize/files/3666521

https://i.imgur.com/DyjYDNz.png

### Current Behavior

Refuses to launch without the proper structurize version 1.0.346 which doesn't exist. Version 1.0.347 is not accepted by forge.

### Expected Behavior

Game should launch

### Reproduction Steps

Try to use the mod properly with a fresh install of Minecolonies and its dependencies.

### Logs

NA

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
click "view all"

**Comment by thaurane** [comment]
Ok, I found it. However this .346 version needs to be among list of either of those directories to be easily found because of the strict requirement.

**Comment by uecasm** [comment]
We don't have any control over which versions Curseforge chooses to show by default.
