### ISSUE TITLE
[BUG] the Russian font very often does not fit

### ISSUE THREAD

**Issue by TimLiz** [ldtteam/minecolonies#8105]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [ ] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.16

### MineColonies Version

1.0.438

### Structurize Version

1.0.343

### Current Behavior

![2022-03-02_17 49 35](https://user-images.githubusercontent.com/88791919/156385317-f024e6f7-b85c-4efa-baa2-f1b06adb643f.png)

### Expected Behavior

Does not fit all the information

### Reproduction Steps

1. Set translate to russian
2. Build barracks lvl 3
3. Start raid
4. Issue

### Logs

Should i do it?

### Anything else?

I can send more screenshots with the wrong text

**Comment by Raycoms** [comment]
Gotta adjust the russian translation on translate.minecolonies.com then to make it fit. Not a code problem. We can't make infinite size for every language.
