### ISSUE TITLE
[BUG] <crash server 1.16.5 magma>

### ISSUE THREAD

**Issue by HOFEV** [ldtteam/minecolonies#8106]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.16

### MineColonies Version

1.0.465-ALPHA

### Structurize Version

1.0.465-ALPHA

### Related Mods and their Versions

forge-1.16.5-36.2.19-c7f6ff3-STABLE

### Reproduction Steps

1. Starting the server
2. Crash

### Logs

https://gist.github.com/HOFEV/63da5aede112c8d080b30b66303815b6

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
Failure message: Mod minecolonies requires forge 36.2.20 or above
		Currently, forge is 36.2.19-c7f6ff3-STABLE

**Comment by someaddons** [comment]
we also only support using forge, not magma.
