### ISSUE TITLE
[BUG] Stone Smelter Will Not Produce Charcoal

### ISSUE THREAD

**Issue by Lakuta** [ldtteam/minecolonies#8109]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.16

### MineColonies Version

1.16.5-1.0.309

### Structurize Version

0.13.252

### Current Behavior

Several other buildings, including the warehouse are requesting charcoal. I have taught the worker how to smelt the logs into charcoal and provided the coal and set the fuel type as coal, and the coal is in the furnaces, but the worker does not touch the logs

### Expected Behavior

Given that they are a smelter and they are allowed to learn the log smelting recipie, i'd have thought that they would be capable of smelting the logs. So far, they have shown no interest to do so.

### Reproduction Steps

1. Set up level 5 stone smeltery
2. Teach worker how to smelt Acacia Log into Charcoal
3. Set fuel type as Coal
4. Provide Coal and Acacia Logs
5. Have other buildings requesting Charcoal
6. Worker will not produce charcoal

### Logs

N/A

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
they need a non charcoal fuel to do so.

**Comment by Lakuta** [comment]
The Fuel Type used is Coal, not Charcoal

**Comment by Lakuta** [comment]
> they need a non charcoal fuel to do so.

The Fuel Type is Coal, not Charcoal

**Comment by MotionlessTrain** [comment]
Could you check the "open request" tab of the workers that request the charcoal? That gives a status of the request at the moment (whether the couriers are planning to bringing logs over, or the stone smelter has the smelting request in the queue, etc.)

**Comment by Raycoms** [comment]
stale
