### ISSUE TITLE
[BUG] collect comb and honey

### ISSUE THREAD

**Issue by SivartMcDorf** [ldtteam/minecolonies#8110]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

463

### Structurize Version

346

### Current Behavior

Have not researched comb and honey in university but the option is already availible

### Expected Behavior

should have to research it before it appears

### Reproduction Steps

build bee keepers hut and option is available I didn't notice it until level 4 but research has not been done

### Logs

n/a

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
The research doesn't seem to do anything at all. I searched for the places where the effect which is given by the research was used, but I can't find anything outside of the constant definition and datagen:
```
$ grep -R BEEKEEP_2 .     
Binary file ./build/classes/java/api/com/minecolonies/api/research/util/ResearchConstants.class matches
Binary file ./build/classes/java/main/com/minecolonies/coremod/generation/defaults/DefaultResearchProvider.class matches
./src/api/java/com/minecolonies/api/research/util/ResearchConstants.java:    public static final ResourceLocation BEEKEEP_2         = new ResourceLocation(Constants.MOD_ID, "effects/beekeep2unlock");
./src/main/java/com/minecolonies/coremod/generation/defaults/DefaultResearchProvider.java:        effects.add(new ResearchEffect(BEEKEEP_2).setTranslatedName("Beekeepers Can Harvest Both Honey Bottles and Combs at Once"));
./src/main/java/com/minecolonies/coremod/generation/defaults/DefaultResearchProvider.java:          .addEffect(BEEKEEP_2, 1)
```
