### ISSUE TITLE
[BUG] Knight and Archer not keeping their hire state

### ISSUE THREAD

**Issue by WastelandStag** [ldtteam/minecolonies#8113]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.18.1-1.0.468

### Structurize Version

1.18.1-1.0.347

### Current Behavior

Since the druid update, the hiring state (automatic, default, manual) Is reset for the guard tower based on what the druid is set to.
Meaning that when you log back in, if a druid is set to manual, all other jobs in the tower will be set to manual, etc.

### Expected Behavior

Store each job state independantly

### Reproduction Steps

Change the job states to different ones,
Restart game.
Job states change to match druid.

### Logs

Reported off phone, sorry

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
I can also reproduce it with the restaurant (I changed the assistant cook to automatic, and after relogging the cook was set to automatic as well).
I think this never worked properly since the assignment rework (as the nbt seems to assume there is only one button to have stored data for)
(That was on 1.16.5 1.0.469 by the way)
