### ISSUE TITLE
[BUG] Forester Hut-Selection Tool-Restricted area Grammar Issue

### ISSUE THREAD

**Issue by IPromiseImFamous** [ldtteam/minecolonies#8115]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.18.1-9

### Structurize Version

1.18.1-1.0.347-ALPHA

### Current Behavior

Forester area restriction tool

"First position set. Click the same position to finish.
Second position set. Click the same position to finish.
Forester restricted area set: ... ... ... ...
Second position set. Click the same position to finish."
![unknown](https://user-images.githubusercontent.com/15721685/156937849-123745a3-3916-41e8-9e3a-1c275a1daf14.png)

### Expected Behavior

"Tool obtained, right-click the first corner then left-click the opposite corner to define restricted work area.
First position set. Left-click the opposite corner to define worked area.
Second position set. Work area restricted.
Forester restricted area set: (x: xxx to xxx, z: xxx to xxx, area: xxxx blocks) The max size is xxxx blocks."

### Reproduction Steps

1. Obtain forester tool.
2. Set area

### Logs

n/a

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Not sure I understand to what you'd like it changed, and where the grammar issue is.

**Comment by IPromiseImFamous** [comment]
> Not sure I understand to what you'd like it changed, and where the grammar issue is.

Expected behavior has correct grammar or at least it makes more sense to me. Maybe I'm using the tool wrong.

Clicking the same position with the tool is not how you actually use the tool as far as I understand.. as left clicking the opposite corner makes the tool disappear and you get the definition message

**Comment by Raycoms** [comment]
For me, left click, then right click the same position twice was how it worked.

**Comment by MotionlessTrain** [comment]
I agree that the sentence "Click on the same position to finish" is strange at the first position message

**Comment by IPromiseImFamous** [comment]
> For me, left click, then right click the same position twice was how it worked.

Really??? I right click one time on the first corner then left click the opposite corner one time... Im so confused

**Comment by MotionlessTrain** [comment]
As I explained on the other issue, the order between the first and the second position is not relevant

**Comment by uecasm** [comment]
The trick is that when you right click, it only "clicks" once.  When you left click, it "clicks" more than once if you hold the left button down too long (because minecraft "breaking" mechanics).

As such, the easiest way to use it is to right-click first, then left click-and-hold, at which point it will double-left-click and vanish itself.  But it is possible to single-left-click if you're fast enough, and then you can do it in either order.
