### ISSUE TITLE
[BUG] Forester Hut-Selection Tool-Restricted area-No Area Selected

### ISSUE THREAD

**Issue by IPromiseImFamous** [ldtteam/minecolonies#8116]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.18.1-9

### Structurize Version

1.18.1-1.0.347-ALPHA

### Current Behavior

Left clicking the selection tool without first selecting an initial position with a right click produces this response:

"Second position set. Click the same position to finish.
Second position set. Click the same position to finish."

<img width="673" alt="Screen Shot 2022-03-06 at 12 01 12 PM" src="https://user-images.githubusercontent.com/15721685/156938096-c10061ec-0f4b-4716-8db8-5d53cdad855c.png">

### Expected Behavior

"Please start by right-clicking the first corner."

### Reproduction Steps

1. Obtain tool
2. left click without first selecting a corner with a right click

### Logs

n/a

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
It is possible to reverse the first position and the second position. As long as you right clicked one of the position and left clicked the opposite one (or in reverse), it will work.
Left-clicking a position seems to trigger a double left click sometimes, hence it triggers the "second position" message (so that if it double clicks, the tool disappears and the area is set correctly).

**Comment by IPromiseImFamous** [comment]
> It is possible to reverse the first position and the second position. As long as you right clicked one of the position and left clicked the opposite one (or in reverse), it will work.
> Left-clicking a position seems to trigger a double left click sometimes, hence it triggers the "second position" message (so that if it double clicks, the tool disappears and the area is set correctly).

Seems to happen 100% of the time just tested it 10 times...

**Comment by IPromiseImFamous** [comment]
Sorry, just needed to turn zoning mode on.
