### ISSUE TITLE
[BUG] Smeltery converts ores into resource by hands and not via smelting

### ISSUE THREAD

**Issue by pantsguyapp** [ldtteam/minecolonies#8117]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

minecolonies-1.18.1-1.0.468-ALPHA

### Structurize Version

structurize-1.18.1-1.0.347-ALPHA

### Current Behavior

Smeltery rubs the ores and it become the resources, unless said ore have raw versions.

### Expected Behavior

They will use the furnaces and apply the Fortune effect with take out the resouces.

### Reproduction Steps

I tested with some diamond ores.
![2022-03-08_11 50 47](https://user-images.githubusercontent.com/92203672/157171160-20dff6e8-de69-46d8-9279-64bb983e5b18.png)
![2022-03-08_11 50 51](https://user-images.githubusercontent.com/92203672/157171164-f06b51cd-1c64-443a-b4d7-4b2680780376.png)

### Logs

https://gist.github.com/pantsguyapp/839634055c6a2d156ff0e06d865d4132

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
They use fortune when they convert it to the raw items - like that diamond block became two diamonds instead of 1
They apply fortune at that point, not when smelting it

**Comment by pantsguyapp** [comment]
My point is that by doing so they have made the furnace become obsolete, for ores that don't have a raw version that is.

**Comment by uecasm** [comment]
But some ores do have a raw version, and they still use the furnace.  Unless you'd want the smelter to just output the raw ore, and then you'd have to teach the stone smelter how to make ingots, which makes less sense.

**Comment by Raycoms** [comment]
Especially iron, copper and gold are still smelted.
