### ISSUE TITLE
[BUG] [1.16.5] OpenGL API ERROR: 1281 With Minecolonies 1.0.475 And Newer

### ISSUE THREAD

**Issue by Sandriell** [ldtteam/minecolonies#8118]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.16

### MineColonies Version

1.16.5-1.0.475-ALPHA and newer

### Structurize Version

structurize-1.16.5-1.0.343-RELEASE

### Related Mods and their Versions

https://gist.github.com/Sandriell/b5e93fe6822f3fc2fd8670f3f35dbfa8

### Current Behavior

To preface this is undoubtedly Optifine related, so not sure how easy to fix, or what your policy is on Optifine.

Had updated to the latest Minecolonies 1.16.5-1.0.480-ALPHA and started getting spammed with OpenGL errors at an incredibly fast rate, quickly generating massive log files. At first I attributed it to being an issue with Optifine and the latest forge version since Minecolonies 1.16.5-1.0.480-ALPHA required a forge upgrade. So I downgraded to 1.16.5-1.0.475-ALPHA and back to the forge version I was previously using (36.2.23) but the errors were still happening. Finally, downgrading to 1.16.5-1.0.474-ALPHA has stopped the errors- so it seems to be something that changed on Minecolonies' side. Something related to the Nether Miner update?

### Expected Behavior

No errors.

### Reproduction Steps

Upgrade minecolonies to 1.0.475 or 1.0.480.
Have optifine.
Profit?

### Logs

https://gist.github.com/Sandriell/40b2f00c3d2dbc8c9394d409e31ec6a3

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
@OrionDevelopment or @Nightenom any idea.

475 added:           .forEach(hut -> RenderTypeLookup.setRenderLayer(hut, renderType -> renderType.equals(RenderType.cutout()) || renderType.equals(RenderType.solid()) || renderType.equals(RenderType.translucent())));


translucent to huts because the nether hut block has this.

**Comment by Nightenom** [comment]
Definitely optifine issue

**Comment by Sandriell** [comment]
Just to say this is still occurring with the latest version (minecolonies-1.16.5-1.0.507-BETA). And I do believe the errors are caused by the hut blocks specifically, though it is inconsistent.

I was testing with the school hut block and a level 0 or level 1 school causes openGl errors, no matter how it was placed.. normally or creatively (either paste option)- goes away soon as I destroy the school hut block. If I creatively paste a higher level (2+) school, I briefly get a flash of openGL errors but then they stop. However this does not seem to be consistent across all huts. Regardless though, it is definitely caused by the hut blocks themselves.

**Comment by Sandriell** [comment]
Was debugging issues with another mod and it was suggested to disable Optifine's "Render Regions" feature. Figured I would go ahead and try out the latest Minecolonies (1.16.5-1.0.564) and see if just maybe this helped with it as well, and to my delight it did. The OpenGL errors have now stopped with that feature turned off.
