### ISSUE TITLE
BUG ===File jar resolve FAILED for: schematics/asian/miner/minermainshaft.blueprint

### ISSUE THREAD

**Issue by cutter4ever** [ldtteam/minecolonies#8124]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.18.1-1.0.448-ALPHA

### Structurize Version

structurize-1.18.1-1.0.346-ALPHA

### Related Mods and their Versions

1. forge 39.0.88
2. domum_ornamentum-1.18.1-1.0.39-ALPHA

### Logs

https://gist.github.com/cutter4ever/27d3a3450271636ce653d49151b956d0

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.
![2022-03-09_23 16 03](https://user-images.githubusercontent.com/10689780/157591428-94216fb2-020e-4bb4-9afb-dbc08192dc7c.png)

**Comment by MotionlessTrain** [comment]
The message "file resolved failed for schematics/asian/miner/minermainshaft.blueprint" doesn't have to do anything about the AI log, it just means that Asian uses the default schematics instead.

It seems like the miner wants to mine on a level that doesn't exist

**Comment by cutter4ever** [comment]
Sorry about the title for the bug. I'm not good at this stuff. But I'm getting all kinds of errors since the miner has had problems. Schematic error out of bounds errors. etc. The log file should have all of them. Tks.
