### ISSUE TITLE
[BUG] Shire Style Cook does not upgrade to Level 2 in 1.18.1 Minecolonies

### ISSUE THREAD

**Issue by kedamono** [ldtteam/minecolonies#8127]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

minecolonies-1.18.1-1.0.479-ALPHA

### Structurize Version

structurize-1.18.1-1.0.347-ALPHA

### Related Mods and their Versions

Forge - 39.0.59
blockui-1.18.2-0.0.47-ALPHA
domum_ornamentum-1.18.1-1.0.39-ALPHA-universal

### Current Behavior

I upgrade the Cook from Level 1 to Level 2. The builder proceeds and builds the level 2 version of the cook hut. But when I check the UI, it shows it as Level 1.

### Expected Behavior

The Cook hut upgrades to Level 2 from Level 1

### Reproduction Steps

(Note, convert the Shire Style Cook to 1.18.1 using the appropriate commands.)

1. Using the Build tool, with the Cook Hut block in your colony and select Shire for the style.
2. Have the builder build the level 1 cook hut for Shire.
3. Upgrade the Cook hut to Level 2.
4. When finished check the UI for the Cook hut.

Result: The building is still level 1.

### Logs

https://gist.github.com/kedamono/567d012d766cf9e13746dc2ae76ac21f

### Anything else?

If you repair the building, the Builder will turn it back to Level 1. 

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.
![2022-03-10_13 17 57](https://user-images.githubusercontent.com/23420636/157758891-4e5f4e2c-f0de-4f24-a35c-2c92c0733c87.jpeg)
![2022-03-10_13 12 25](https://user-images.githubusercontent.com/23420636/157758475-e9901525-0341-4301-acd5-9811a5883ebd.jpeg)

**Comment by Raycoms** [comment]
Does the builder call it finished?

**Comment by Raycoms** [comment]
They either are still on it, or it was scanned incorrectly. Then it's not a MineColonies issue. I'll close this in favor of #5006 for now.

**Comment by kedamono** [comment]
The builder completes the build, but there's no fireworks, but as you see in the screenshot, they say they finished Cook 2 and but it stays Cook 1.

I did double check to make sure that there is a Cook2.blueprint for Shire, and it's a different file size. If I were to place in "build mode" and save it out as "cook2" would that fix the problem?

**Comment by Raycoms** [comment]
They probably scanned it in as cook1 and renamed to cook2 or so. So that the tileEntity thinks it's cook1. @someaddons

**Comment by MotionlessTrain** [comment]
If I recall correctly, every time I heard about this issue, it was a scan error (or renamed file) or something like that. I would suggest rescanning the build.

**Comment by Talyda** [comment]
This probably isn't helpful, but I am pretty sure I saw someone report that happening on the patreon server a couple weeks ago too.
Gonna see if I can find it.
*some time later*
https://discord.com/channels/472875599422291968/473575384445878273/945136911821963266
Found it! Similar problem I think?
I do think there was more though

**Comment by kedamono** [comment]
Pasting it in build mode on my personal flat world and then rescanning it and saving it as "cook2" solved the problem. Also this time I got fireworks when I did it. so now I have to check my other buildings to see if they are really level 2 or not.

Thanks!
