### ISSUE TITLE
[BUG] Passive Mob Spawns out of control in Abandoned Colonies 1.18.2

### ISSUE THREAD

**Issue by revdave33** [ldtteam/minecolonies#8128]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.18.2-1.0.478-ALPHA

### Structurize Version

1.18.2-1.0.349-ALPHA

### Related Mods and their Versions

Forge 40.0.12

### Current Behavior

I find an abandoned colony and start exploring the colony trying to decide if I want to settle here or at least to see what resources are available. Within minutes, there are a lot of cows, sheep, and cats. They keep spawning. Even if I execute a kill @e[type=!player] command, they start spawning again within seconds. If I am within the bounds of the abandoned colony it doesn't take long to be too many passive mobs.

### Expected Behavior

At first I thought having some sheep, cows, and even cats in an abandoned colony was nice, but only a few is needed. 

### Reproduction Steps

Create a new world in 1.18.2.
Locate an abandoned colony.
Spend time in the colony, the mobs will spawn

### Logs

If you want logs, fine, but the only I saw in reading through them was my execution of the kill command.

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Fix pushed
