### ISSUE TITLE
Medieval Birch Guard Tower Issue

### ISSUE THREAD

**Issue by Hybrid1Wolf** [ldtteam/minecolonies#8129]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.18.1-1.0.448-ALPHA.jar

### Structurize Version

1.18.1-1.0.448-ALPHA.jar

### Related Mods and their Versions

Curse Forge
All The Mods 7

### Current Behavior

Unable to reactivate abanadoned guard tower in Medieval Birch Mine Colony, states that block is missing respective building and that I should restart or load backup.

### Expected Behavior

I expected to reactivate the guardd tower the same way I have the other buildings

### Reproduction Steps

Load MC Version 18
Locate Medival Birch abandoned Colony
Activate Town Hall
Once up and running, attempt to reactivate guard towers, all of them should come up with the above message

### Logs

Not available

**Comment by Talyda** [comment]
Just to add, there's been three other people I think report same thing for same building =)
