### ISSUE TITLE
MY AI has run into an issue please locate the latest.log and send it to the minecolonies authors

### ISSUE THREAD

**Issue by thomasaeddy** [ldtteam/minecolonies#8132]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.18.1-1.0.428-RELEASE

### Structurize Version

1.18.1-1.0.428-RELEASE

### Related Mods and their Versions

1. Forge Version: 39.0.59

### Logs

https://pastebin.com/QQNStQwN

### Anything else?

Just submitting this because the game AI instructed to do so.

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
This is not the latest version. Should be fixed in latest. If not fixed, than the miner data got corrupted in earlier and needs to be replaced.
