### ISSUE TITLE
Long schematic names don't rendre entirely in the work order

### ISSUE THREAD

**Issue by mcmanustfj** [ldtteam/minecolonies#8133]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

#8112 

### Structurize Version

.347

### Related Mods and their Versions

x

### Current Behavior

![image](https://user-images.githubusercontent.com/10820772/157935930-fcc66e90-0d62-437b-9a8a-b15cf83b1d27.png)
Long schematic names get cut off in the work order view in the TH

### Expected Behavior

"deliveryman2"

### Reproduction Steps

make a lumberjack or deliveryman schematic 

### Logs

x

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
Could you please add your Minecolonies and Structurize versions?

**Comment by mcmanustfj** [comment]
It's structurize version 0.347, and it's MineColonies built from source as of #8112

**Comment by Thodor12** [comment]
Note that even in this new system I provided here this is still an issue, it's a limitation of the `AbstractTextElement`.
This class provides wrapping options to make text render on newlines if possible but there's no overflow options to it,
when text is too long to fit it's wrapped by the first whitespace and the rest is simply not shown.
The PR for the new work order "fixes" this by adding a tooltip to it but a long term solution would be to make the `AbstractTextElement` capable of text overflow.
