### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by thomasaeddy** [ldtteam/minecolonies#8134]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.18.1-1.0.468-ALPHA

### Structurize Version

1.18.1-1.0.468-ALPHA

### Related Mods and their Versions

1. Forge Version 0.193.1.8 (Feb 27, 2022

### Logs

https://pastebin.com/sKiHbbtE

### Anything else?

I previously reported the miner AI stated to copy the log and send it back to the minecolonies author.  It was reported back to me to update to the newest mine colony and if the error occurred again to report it.  I have updated and the miner AI reported an error again.  Log pasted in pastebin.com

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
I believe your miner buildings data got corrupted, did you try fire/re-hrie, or even deconstruct, pickup, place somewhere else and construct again?

**Comment by Raycoms** [comment]
Also, what is your miners building level?

**Comment by MotionlessTrain** [comment]
Minecolonies 1.0.468 doesn't have the fix in it. Could you please try on the newest version (1.0.494)?

**Comment by thomasaeddy** [comment]
I do not know why I got the message.  The miner's seem to be behaving
properly (they are mining).  I just posted the log because the MOD had a
message to do so.  I was not looking for a solution.

Thomas Eddy

**Comment by thomasaeddy** [comment]
Currently they are level 3.  Just started level 4.  These are three mines
next to each other.  I built them so I had enough employment for each
member of the colony.  Not too concern if they do not mine (but they are).
I have one level 5 mine some distance away.

Thomas Eddy

**Comment by thomasaeddy** [comment]
Curse Forge only has MineColonies Official 1.18.1-9.zip posted 3/4/2022
This is the one I have updated to and had the issue with.

Thomas Eddy

**Comment by Talyda** [comment]
You need to update the mod within the modpack =)

**Comment by thomasaeddy** [comment]
How do I do that?  I have only used Forge as my access to the MOD.

Thomas Eddy

**Comment by MotionlessTrain** [comment]
If you mean curseforge, click on the three dots, go to profile options, and check "allow content management for this profile". Then you can click on the mod, and select the newer version on the "versions" tab

**Comment by Raycoms** [comment]
I'll close that as can't reproduce especially as the miner seems to be working outside of here and there a hickup.
