### ISSUE TITLE
[BUG] Clicking the crafting tab on a hut that has at least a recipe saved crashed the game

### ISSUE THREAD

**Issue by cloudgal42** [ldtteam/minecolonies#8143]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.16

### MineColonies Version

1.16.5-1.0.495-ALPHA

### Structurize Version

1.16.5-1.0.343-RELEASE

### Related Mods and their Versions

Forge version: 36.2.30
Java version: 1.8.0_202, Oracle Corporation

### Current Behavior

After teaching a hut any valid recipe, the crafting recipe tab is inaccessible, since clicking on the tab crashes the game.

### Expected Behavior

Clicking the crafting tab should show the list of learned recipes, and a button to teach a hut another one.

### Reproduction Steps

1. Create a colony
2. Place any hut that accepts custom recipes (e.g. builder)
3. Teach them any valid recipe (e.g. a torch)
4. Save the recipe, then interact with the hut block again
5. Click the crafting tab
6. Profit

### Logs

crash log: https://gist.github.com/cloudgal42/1d0bc4658ca4f081d5d2ad024810c3f7

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
hotfix pushed
