### ISSUE TITLE
[BUG] Plantation's Double Trouble growable selection error.

### ISSUE THREAD

**Issue by pantsguyapp** [ldtteam/minecolonies#8145]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

minecolonies-1.18.1-1.0.494-ALPHA

### Structurize Version

structurize-1.18.1-1.0.352-ALPHA

### Related Mods and their Versions

no

### Current Behavior

Rapid clicking the planting option will show up as if you haven't unlocked the Double Trouble research, but that is just a visual bug and still pattern to the double crops option.

### Expected Behavior

Plantation will no longer have single crop selection after the research is unlocked

### Reproduction Steps

1. Unlock DOuble Trouble
2. built a L5 plantation
3. Go into the crop selection menu and rapid click the option.

### Logs

https://gist.github.com/pantsguyapp/839634055c6a2d156ff0e06d865d4132

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Way too hard to reproduce and only really a problem when you're trying to break it in the first place
