### ISSUE TITLE
[BUG] Server crashes(Netherworker)

### ISSUE THREAD

**Issue by TimLiz** [ldtteam/minecolonies#8147]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [x] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.16

### MineColonies Version

1.16.5-1.0.503

### Structurize Version

1.16.5-1.0.354

### Related Mods and their Versions

Check log

### Current Behavior

Server crashes by minecolonies netherworker

### Expected Behavior

The server does not crash

### Reproduction Steps

...

### Logs

https://pastebin.com/raw/iJhSQjrk

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Need some more info:
Forge version?
Running sth like paper or similar?
Performance mods?

**Comment by TimLiz** [comment]
> Need some more info: Forge version? Running sth like paper or similar? Performance mods?

Forge: latest(36.2.30)
Running on forge
Perfomace mods: dinamic view, ferrite core

**Comment by TimLiz** [comment]
I think noone needs it, so i will close it.

**Comment by MotionlessTrain** [comment]
This crash bug has been fixed anyway, so it could have been closed quite some time ago
