### ISSUE TITLE
[BUG] Crash Supply Camp

### ISSUE THREAD

**Issue by MrHimera** [ldtteam/minecolonies#8148]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.16

### MineColonies Version

1.0.505-ALPHA

### Structurize Version

1.0.354-ALPHA

### Current Behavior

Game crashes when I try to place a Supply Camp.

### Expected Behavior

The Supply Camp must be established on the ground.

### Reproduction Steps

Put the Supply Camp on the ground.

### Logs

https://pastebin.com/Rex2GBMt

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by DaemonUmbra** [comment]
Should "Have you purchased the game?" be added to the issue template?

**Comment by Raycoms** [comment]
Is this one of those "hacky custom launchers" ?

**Comment by DaemonUmbra** [comment]
TLauncher, it's plain ol' piracy

**Comment by Raycoms** [comment]
Ah yeah, and afaik it even causes issues with some colony stuff
