### ISSUE TITLE
[BUG] Game won't launch on most recent versions with up-to-date forge

### ISSUE THREAD

**Issue by Arronicus** [ldtteam/minecolonies#8155]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.0.504-BETA

### Structurize Version

1.0.353-ALPHA

### Related Mods and their Versions

1. FORGE 40.0.18
2. Minecraft 1.18.2
3. Domum 1.0.41-ALPHA
4. JEI 9.5.2.135
5. Multi-Piston 1.2.3-ALPHA
6. UI Library Mod 0.0.47-ALPHA (this is the name it shows in MultiMC but is one of the minecolony dependencies

### Current Behavior

Attempting to launch the most recent version (beta 1.0.504) gives error messages and fails to load on forge 40.0.18, but launches successfully (with warnings) on 40.0.13. 

Attempting to launch the Alpha version (1.0.498) with the listed dependencies generates an error message that it requires structurize to be 1.0.352-alpha, but when running this version of sturcturize, multi-piston says that it requires structurize 1.0.349-alpha or higher. 

### Expected Behavior

I guess just the game to launch

### Reproduction Steps

Install the most recent Beta or Alpha minecolonies version with MultiMC, using the most up-to-date forge version (40.0.18)

### Logs

https://pastebin.com/0KRUv3cD

### Anything else?

This is the other relevant logfile
https://pastebin.com/Fdb7e046

please note these both have a 1 day expiry

**Comment by Moobien** [comment]
Shin says to post here even though its not a minecolonies issue. had mod loading errors on forge .18 but loads fine on .17

**Comment by MotionlessTrain** [comment]
It looks like Forge rewrote a registry in that forge version indeed, which breaks something in minecolonies

**Comment by Moobien** [comment]
> It looks like Forge rewrote a registry in that forge version indeed, which breaks something in minecolonies

Not just minecolonies, Train look in #general-chit-chat on the discord at my crash logs.

**Comment by suckmepeen** [comment]
having same issue. any fixes yet?

**Comment by MotionlessTrain** [comment]
Other than downgrading forge to 40.0.17, no

**Comment by marchermans** [comment]
Yes this is known and a hard binary break in forge.
We will eventually update the 1.18.2 release to get it fixed.

**Comment by MotionlessTrain** [comment]
In fact, the latest alpha for 1.18.2, version 1.0.521 at time of writing, is already updated to forge 40.0.19, so this issue can be closed

**Comment by Moobien** [comment]
> In fact, the latest alpha for 1.18.2, version 1.0.521 at time of writing, is already updated to forge 40.0.19, so this issue can be closed

That version has the hut block crash though doesn't it?

**Comment by MotionlessTrain** [comment]
Yes, but that is a different issue
