### ISSUE TITLE
[BUG] warehouse stock update losts after replacing the racks

### ISSUE THREAD

**Issue by xiaobbl** [ldtteam/minecolonies#8163]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.16

### MineColonies Version

1.0.507-BETA

### Structurize Version

1.0.355-ALPHA

### Current Behavior

If you have a warehouse stock update then you break the rack and replace it,it will become as small as that hasn't updated

### Expected Behavior

.

### Reproduction Steps

1.break the rack in updated warehouse
2.place it again
3.open its GUI to see

### Logs

none

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
Don't break and replace racks in warehouses. They may not be recognised by the couriers if you do so. If you (accidentally) break racks, repair the warehouse and let a builder place them back, for the warehouse to register them again

**Comment by xiaobbl** [comment]
> Don't break and replace racks in warehouses. They may not be recognised by the couriers if you do so. If you (accidentally) break racks, repair the warehouse and let a builder place them back, for the warehouse to register them again

but i have just tried to repair it but didn't work...

**Comment by xiaobbl** [comment]
> Don't break and replace racks in warehouses. They may not be recognised by the couriers if you do so. If you (accidentally) break racks, repair the warehouse and let a builder place them back, for the warehouse to register them again

do i need to replace the rack before i repair it or i have to make the builder to place it?
