### ISSUE TITLE
[BUG] Lindie's recruitment's cost is not properly showing

### ISSUE THREAD

**Issue by MotionlessTrain** [ldtteam/minecolonies#8167]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.16

### MineColonies Version

1.0.522-ALPHA

### Structurize Version

1.0.358-ALPHA

### Current Behavior

Lindie doesn't show the recruitment cost. I happen to know it should be something like 169 rotten flash, but that is not showing.
I tried all gui scales to see if it is a scale problem.

![Schermafbeelding 2022-03-21 om 00 31 52](https://user-images.githubusercontent.com/6672741/159190752-5e828f7c-03d4-4610-ac35-ca27bda09070.png)

### Expected Behavior

Her recruitment cost would be visible

### Reproduction Steps

1. Wait until Lindie spawns
2. Interact with Lindie

### Logs

Doesn't seem to log anything about visitors

### Anything else?

I can remember this was reported earlier as bug, and I thought I remembered it was fixed as well. But unfortunately, that doesn't seem to be the case.
Asana Yuuki seems to be working well, but I have seen a similar issue on one "regular" visitor as well.
Unfortunately I can't tell what she should have been asking.
Visitors asking for diamonds, sunflowers and redstone work fine.

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
fix properly ported
