### ISSUE TITLE
[BUG] Game crashes when attempting to place supply camp

### ISSUE THREAD

**Issue by SpaceBoyHmm** [ldtteam/minecolonies#8169]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.16

### MineColonies Version

1.0.523-ALPHA

### Structurize Version

1.0.358-ALPHA

### Related Mods and their Versions

1. Forge Version: 36.2.31 (newest, as of yesterday at least)
2. I recieved a mod pack from a friend, with the main focus being this mod-but I decided to add a couple more mods, for performance, and QOL. They are here:
- Magnesium (unofficial forge port of Sodium)
- BetterF3
- FPS-Monitor

### Current Behavior

When attempting to place a supply camp, the schematic preview shows up as normal (after updating structurize and minecolonies, from what they were when I downloaded the pack). However, when trying to place the schematic (or when trying to cancel it, but not when hitting ESC to walk around the preview) the game freezes for about 5 seconds, goes to a loading screen and saves the world, and then crashes. I have attempted making a flat area for the schematic (excluding the grass blocks as the floor) and that didn't work, and then I got rid of the floor grass blocks to leave no obstruction, which still crashed my game.

### Expected Behavior

After clearing a flat plain, the schematic for the supply camp should place correctly.

### Reproduction Steps

1. Place the supply camp schematic preview.
2. Attempt to click the check mark or X button, either of which will crash the game.

### Logs

https://gist.github.com/SpaceBoyHmm/08f6d77c92da157e11031675f61b0a55

### Anything else?

Nothing else to note. I've tried everything, looked at old bug reports (closed), and updating mod versions got me farther but didn't solve the problem.

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
Update - just been fixed about an hour ago
