### ISSUE TITLE
Game Crashes Whenever I Try To Use Build Tool

### ISSUE THREAD

**Issue by tj5382** [ldtteam/minecolonies#8177]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.16

### MineColonies Version

minecolonies-0.13.614-ALPHA-universal

### Structurize Version

structurize-0.13.109-ALPHA-universal

### Related Mods and their Versions

forge-1.15.2-31.2.33
My version is actually 1.15.2 however there is no option for that. The Issue I'm having: Whenever I try to use the build tool my game will freeze for a couple of seconds then crash. I've tried a few things already because I initially thought it was incompatible versions. I've used minecolonies-0.13.614-ALPHA-universal and structurize-0.13.109-ALPHA-universal together, minecolonies-0.13.645-RELEASE-universal and structurize-0.13.109-ALPHA-universal and both didn't work. If I go to any earlier versions of structurize my game won't run and I'll be told I need structurize-0.13.109-ALPHA-universal for that version of minecolonies. This whole problem arose when I was updating to a newer release. Before I updated, I was using minecolonies-0.13.436-RELEASE-universal and structurize-0.13.94-ALPHA-universal which actually worked. I even reverted back to this version and now it doesn't work which really puzzles me. I can still run everything else fine by using the option to place anyway when putting a structure block down in every try but the build tool is very convenient. The only other information I'll add is I did mess with the config file for minecolonies but didn't change anything too crazy. Maybe I screwed something up or something but I can't seem to figure it out and I've tried looking online for answers everywhere but I can't find anything for this specifically.  By the way, thank you guys for everything you do. This is an amazing mod and I really look forward to what I have planned utilizing this mod.

### Logs

---- Minecraft Crash Report ---- // You're mean.  Time: 3/24/22 12:10 AM Description: Unexpected error  java.lang.NullPointerException: Unexpected error 	at net.minecraft.client.renderer.RenderState.lambda$static$34(RenderState.java:181) ~[?:?] {re:classloading,xf:OptiFine:default} 	at net.minecraft.client.renderer.RenderState$$Lambda$4720/1534773730.run(Unknown Source) ~[?:?] {} 	at net.minecraft.client.renderer.RenderState.func_228547_a_(RenderState.java:197) ~[?:?] {re:classloading,xf:OptiFine:default} 	at net.optifine.render.RenderStateManager$$Lambda$10451/395249765.accept(Unknown Source) ~[?:?] {} 	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:408) ~[guava-21.0.jar:?] {} 	at net.optifine.render.RenderStateManager.setupRenderStates(RenderStateManager.java:30) ~[?:?] {re:classloading} 	at net.minecraft.client.renderer.RenderType$Type.lambda$new$0(RenderType.java:857) ~[?:?] {re:classloading,xf:OptiFine:default} 	at net.minecraft.client.renderer.RenderType$Type$$Lambda$4751/247446217.run(Unknown Source) ~[?:?] {} 	at net.minecraft.client.renderer.RenderState.func_228547_a_(RenderState.java:197) ~[?:?] {re:classloading,xf:OptiFine:default} 	at net.minecraft.client.renderer.RenderType.func_228631_a_(RenderType.java:464) ~[?:?] {re:classloading,xf:OptiFine:default} 	at net.minecraft.client.renderer.IRenderTypeBuffer$Impl.func_228462_a_(IRenderTypeBuffer.java:148) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default} 	at net.minecraft.client.renderer.IRenderTypeBuffer$Impl.getBuffer(IRenderTypeBuffer.java:77) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default} 	at com.ldtteam.structurize.event.ClientEventSubscriber.lambda$renderWorldLastEvent$0(ClientEventSubscriber.java:54) ~[?:0.13.109-ALPHA] {re:classloading} 	at com.ldtteam.structurize.event.ClientEventSubscriber$$Lambda$13463/681356970.get(Unknown Source) ~[?:?] {} 	at com.ldtteam.structurize.event.ClientEventSubscriber.renderWorldLastEvent(ClientEventSubscriber.java:72) ~[?:0.13.109-ALPHA] {re:classloading} 	at net.minecraftforge.eventbus.ASMEventHandler_239_ClientEventSubscriber_renderWorldLastEvent_RenderWorldLastEvent.invoke(.dynamic) ~[?:?] {} 	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.2.0-service.jar:?] {} 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?] {} 	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:185) ~[?:?] {re:classloading} 	at sun.reflect.GeneratedMethodAccessor57.invoke(Unknown Source) ~[?:?] {} 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {} 	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {} 	at net.optifine.reflect.Reflector.callVoid(Reflector.java:736) ~[?:?] {re:classloading} 	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:1016) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_gamerenderer_resetprojectionmatrix,xf:fml:xaerominimap:xaero_gamerenderer_renderworld,xf:OptiFine:default} 	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:689) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_gamerenderer_resetprojectionmatrix,xf:fml:xaerominimap:xaero_gamerenderer_renderworld,xf:OptiFine:default} 	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:924) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A} 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:553) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A} 	at net.minecraft.client.main.Main.main(SourceFile:204) [?:?] {re:classloading} 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {} 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {} 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {} 	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {} 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.15.2-31.2.33.jar:31.2] {} 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$435/537524656.call(Unknown Source) [forge-1.15.2-31.2.33.jar:31.2] {} 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.2.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.2.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.2.jar:?] {} 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.2.jar:?] {} 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.2.jar:?] {}   A detailed walkthrough of the error, its code path and all known details is as follows: ---------------------------------------------------------------------------------------  -- Head -- Thread: Render thread Stacktrace: 	at net.minecraft.client.renderer.RenderState.lambda$static$34(RenderState.java:181) 	at net.minecraft.client.renderer.RenderState$$Lambda$4720/1534773730.run(Unknown Source) 	at net.minecraft.client.renderer.RenderState.func_228547_a_(RenderState.java:197) 	at net.optifine.render.RenderStateManager$$Lambda$10451/395249765.accept(Unknown Source) 	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:408) 	at net.optifine.render.RenderStateManager.setupRenderStates(RenderStateManager.java:30) 	at net.minecraft.client.renderer.RenderType$Type.lambda$new$0(RenderType.java:857) 	at net.minecraft.client.renderer.RenderType$Type$$Lambda$4751/247446217.run(Unknown Source) 	at net.minecraft.client.renderer.RenderState.func_228547_a_(RenderState.java:197) 	at net.minecraft.client.renderer.RenderType.func_228631_a_(RenderType.java:464) 	at net.minecraft.client.renderer.IRenderTypeBuffer$Impl.func_228462_a_(IRenderTypeBuffer.java:148) 	at net.minecraft.client.renderer.IRenderTypeBuffer$Impl.getBuffer(IRenderTypeBuffer.java:77) 	at com.ldtteam.structurize.event.ClientEventSubscriber.lambda$renderWorldLastEvent$0(ClientEventSubscriber.java:54) 	at com.ldtteam.structurize.event.ClientEventSubscriber$$Lambda$13463/681356970.get(Unknown Source) 	at com.ldtteam.structurize.event.ClientEventSubscriber.renderWorldLastEvent(ClientEventSubscriber.java:72) 	at net.minecraftforge.eventbus.ASMEventHandler_239_ClientEventSubscriber_renderWorldLastEvent_RenderWorldLastEvent.invoke(.dynamic) 	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) 	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:185) 	at sun.reflect.GeneratedMethodAccessor57.invoke(Unknown Source) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.lang.reflect.Method.invoke(Method.java:497) 	at net.optifine.reflect.Reflector.callVoid(Reflector.java:736) 	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:1016)  -- Affected level -- Details: 	All players: 1 total; [ClientPlayerEntity['TheTimMen'/234, l='MpServer', x=-58.06, y=4.00, z=-154.81]] 	Chunk stats: Client Chunk Cache: 4761, 3969 	Level dimension: DimensionType{minecraft:overworld} 	Level name: MpServer 	Level seed: -7098584389651451922 	Level generator: ID 01 - flat, ver 0. Features enabled: false 	Level generator options: {} 	Level spawn location: World: (-32,4,-144), Chunk: (at 0,0,0 in -2,-9; contains blocks -32,0,-144 to -17,255,-129), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1) 	Level time: 6569 game time, 6569 day time 	Known server brands:  	Level was modded: false 	Level storage version: 0x00000 - Unknown? 	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false) 	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false 	Server brand: forge 	Server type: Integrated singleplayer server Stacktrace: 	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:611) 	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1763) 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:572) 	at net.minecraft.client.main.Main.main(SourceFile:204) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.lang.reflect.Method.invoke(Method.java:497) 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$435/537524656.call(Unknown Source) 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)  -- System Details -- Details: 	Minecraft Version: 1.15.2 	Minecraft Version ID: 1.15.2 	Operating System: Windows 10 (amd64) version 10.0 	Java Version: 1.8.0_51, Oracle Corporation 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation 	Memory: 2301617832 bytes (2194 MB) / 8589934592 bytes (8192 MB) up to 8589934592 bytes (8192 MB) 	CPUs: 16 	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M 	ModLauncher: 5.1.2+70+master.2845bb9 	ModLauncher launch target: fmlclient 	ModLauncher naming: srg 	ModLauncher services:  		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE  		/forge-1.15.2-31.2.33.jar object_holder_definalize PLUGINSERVICE  		/forge-1.15.2-31.2.33.jar runtime_enum_extender PLUGINSERVICE  		/accesstransformers-2.1.3-shadowed.jar accesstransformer PLUGINSERVICE  		/forge-1.15.2-31.2.33.jar capability_inject_definalize PLUGINSERVICE  		/forge-1.15.2-31.2.33.jar runtimedistcleaner PLUGINSERVICE  		/OptiFine_1.15.2_HD_U_G6.jar OptiFine TRANSFORMATIONSERVICE  		/forge-1.15.2-31.2.33.jar fml TRANSFORMATIONSERVICE  	FML: 31.2 	Forge: net.minecraftforge:31.2.33 	FML Language Providers:  		javafml@31.2 		minecraft@1 	Mod List:  		forge-1.15.2-31.2.33-client.jar Minecraft {minecraft@1.15.2 DONE} 		useful_backpacks-1.15.2-1.10.3.77.jar Useful Backpacks {usefulbackpacks@1.10.3.77 DONE} 		ToolBelt-1.15.2-1.14.2.jar Tool Belt {toolbelt@1.14.2 DONE} 		animalnet-v1.15.2+Forge+b1.jar AnimalNet {animalnet@v1.15.2 Forge b1 DONE} 		valkyrielib-1.15.2-3.0.2.1.jar ValkyrieLib {valkyrielib@1.15.2-3.0.2.1 DONE} 		forge-1.15.2-geckolib-2.0.0.jar Geckolib {geckolib@2.0.0 DONE} 		jei-1.15.2-6.0.3.15.jar Just Enough Items {jei@6.0.3.15 DONE} 		Abnormals-Core-1.15.2-1.0.6.jar Abnormals Core {abnormals_core@1.0.6 DONE} 		astikorcarts-1.15.2-1.0.4.jar AstikorCarts {astikorcarts@1.0.4 DONE} 		vanillaboom-1.15.2-1.6.5.1-universal.jar Vanilla Boom {vanillaboom@1.6.5.1 DONE} 		CannabisCraft1.15.2v4.1.5.jar CannabisCraft {cannabiscraft@4.1.5 DONE} 		paintings-1.15.2-7.0.0.0.jar Paintings ++ {paintings@1.14.4-6.0.1.5 DONE} 		curios-FORGE-1.15.2-2.0.2.7.jar Curios API {curios@FORGE-1.15.2-2.0.2.7 DONE} 		SpartanShields-1.15.2-2.1.0.jar Spartan Shields {spartanshields@2.1.0 DONE} 		Patchouli-1.15.2-1.2-35.jar Patchouli {patchouli@1.15.2-1.2-35 DONE} 		create-mc1.15.2_v0.3e.jar Create {create@mc1.15.2_v0.3e DONE} 		Xaeros_Minimap_21.2.0_Forge_1.15.2.jar Xaero's Minimap {xaerominimap@21.2.0 DONE} 		collective-1.15.2-1.56.jar Collective {collective@1.56 DONE} 		XaerosWorldMap_1.11.11_Forge_1.15.2.jar Xaero's World Map {xaeroworldmap@1.11.11 DONE} 		SereneSeasons-1.15.2-3.0.0.75-universal.jar Serene Seasons {sereneseasons@1.15.2-3.0.0.75 DONE} 		enderchests-1.15-1.6.6.jar EnderChests {enderchests@1.6.6 DONE} 		decorative_blocks-1.15.2-1.7.jar Decorative Blocks {decorative_blocks@1.7 DONE} 		NomadicTents-1.15.2-11.0.0-beta.jar Nomadic Tents {nomadictents@11.0.0-beta DONE} 		structurize-0.13.109-ALPHA-universal.jar Structurize {structurize@0.13.109-ALPHA DONE} 		worldedit-forge-mc1.15.2-7.1.0.jar WorldEdit {worldedit@7.1.0;48cc31c DONE} 		u_team_core-1.15.2-3.0.2.169.jar U Team Core {uteamcore@3.0.2.169 DONE} 		minecolonies-0.13.614-ALPHA-universal.jar MineColonies {minecolonies@0.13.614-ALPHA DONE} 		SpartanWeaponry-1.15.2-2.0.0-beta-1.jar Spartan Weaponry {spartanweaponry@2.0.0 beta 1 DONE} 		mapperbase-1.15.2-1.1.1.0.jar Mapper Base {mapperbase@1.15.2-1.1.1.0 DONE} 		embellishcraft-1.15.2-2.2.1.0.jar EmbellishCraft {embellishcraft@1.15.2-2.2.1.0 DONE} 		additional_lights-1.15.2-2.0.2.jar Additional Lights {additional_lights@2.0.2 DONE} 		sworddisplay-1.15.2-1.5.1.jar Sword Displays {sworddisplay@1.15.2-1.5.1 DONE} 		platos-FORGE-1.15-1.4.4.jar Plato's Transporters {platos@1.4.4 DONE} 		Hwyla-forge-1.10.8-B72_1.15.2.jar Waila {waila@version DONE} 		SnowRealMagic-1.15.2-1.7.5.jar Snow! Real Magic! {snowrealmagic@1.7.5 DONE} 		Kiwi-1.15.2-2.8.5.jar Kiwi {kiwi@2.8.5 DONE} 		ars_nouveau-1.15.2-1.3.0.jar Ars Nouveau {ars_nouveau@1.3.0 DONE} 		lotr-1.15-renewed-2.13.jar The Lord of the Rings Mod {lotr@Renewed-2.13 DONE} 		Swamp-Expansion-1.15.2-1.7.3.jar Swamp Expansion {swampexpansion@NONE DONE} 		forge-1.15.2-31.2.33-universal.jar Forge {forge@31.2.33 DONE} 		simplechunkloaders-1.15.2-1.0.2.0.jar Simple Chunk Loaders {simplechunkloaders@NONE DONE} 		shetiphiancore-1.15-3.7.4.jar ShetiPhian-Core {shetiphiancore@3.7.4 DONE} 		grindstonesharpertools_1.15-1.4.jar Grindstone Sharper Tools {grindstonesharpertools@1.4 DONE} 		FastLeafDecay-v22.1.jar FastLeafDecay {fastleafdecay@v22.1 DONE} 		thutcore-1.15.2-7.3.0.jar Thut Core {thutcore@7.3.0 DONE, thutcrafts@7.3.0 DONE} 		thuttech-1.15.2-8.4.0.b.jar Thut Elevators {thuttech@8.4.0 DONE} 	Kiwi Modules:  		kiwi:contributors 		kiwi:data 		snowrealmagic:snowrealmagic 	Patchouli open book context: n/a 	Launched Version: 1.15.2-forge-31.2.33 	Backend library: LWJGL version 3.2.2 build 10 	Backend API: NVIDIA GeForce RTX 3070/PCIe/SSE2 GL version 4.6.0 NVIDIA 496.49, NVIDIA Corporation 	GL Caps: Using framebuffer using OpenGL 3.0 	Using VBOs: Yes 	Is Modded: Definitely; Client brand changed to 'forge' 	Type: Client (map_client.txt) 	Resource Packs: vanilla, file/Excalibur_V1.15.zip, mod_resources 	Current Language: English (US) 	CPU: 16x 11th Gen Intel(R) Core(TM) i9-11900KF @ 3.50GHz 	OptiFine Version: OptiFine_1.15.2_HD_U_G6 	OptiFine Build: 20210124-205244 	Render Distance Chunks: 32 	Mipmaps: 4 	Anisotropic Filtering: 1 	Antialiasing: 0 	Multitexture: false 	Shaders: null 	OpenGlVersion: 4.6.0 NVIDIA 496.49 	OpenGlRenderer: NVIDIA GeForce RTX 3070/PCIe/SSE2 	OpenGlVendor: NVIDIA Corporation 	CpuCount: 16

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
1.15.2 is not supported and does not work with optifine.
