### ISSUE TITLE
[BUG] <neitherminer ai>

### ISSUE THREAD

**Issue by shenzhencz** [ldtteam/minecolonies#8185]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.0.510-ALPHA

### Structurize Version

1.0.353-ALPHA

### Related Mods and their Versions

1.40.0.17
2.0.0.47-ALPHA
3.1.0.41-ALPHA

### Current Behavior

the ai has some problem:
![2022-03-26_10 36 23](https://user-images.githubusercontent.com/102397830/160221623-c93e3f9e-5c23-4731-bddd-40de5bcffec7.png)

### Expected Behavior

the worker cannot work because he says his ai has problems

### Reproduction Steps

1.build neithermine with acacia style
2.call a neitherminer to work

### Logs

https://gist.github.com/shenzhencz/f910f51a4f3ae1b9ba568661259b1315

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
You could try updating the mods - there was a problem with that style, not sure if that was the same problem, but updating might fix it =)

**Comment by MotionlessTrain** [comment]
Not yet unfortunately. A pull request with the fixes is pending

**Comment by Raycoms** [comment]
The fixes are only necessary to avoid the exception, technically if the tags are set this should not happen.

**Comment by MotionlessTrain** [comment]
I mean the updated schematics with the fixed tags are in an pending PR at the moment

**Comment by Raycoms** [comment]
ahhh
