### ISSUE TITLE
Netherworker Citizen Model after firing

### ISSUE THREAD

**Issue by SerranoPancake** [ldtteam/minecolonies#8194]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.0.553-ALPHA

### Structurize Version

1.0.369-ALPHA

### Related Mods and their Versions

Forge 39.1.2
Domum 1.0.49-ALPHA
blockui 0.0.47-ALPHA

### Current Behavior

When firing NetherMiner the model of the citizen is missing parts.
![image](https://user-images.githubusercontent.com/20136617/160489719-32c7f743-5161-4373-80f5-ee20dd75b1f1.png)

### Expected Behavior

Model of citizen should revert to original

### Reproduction Steps

1. Hire Netherminer.
2. Fire Netherminer

### Logs

https://gist.github.com/SerranoPancake/8e5b8fde44b79e087262dc73265fc191

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Can't reproduce this, which texture style are you using?

**Comment by SerranoPancake** [comment]
Not sure what you mean by “texture style.” If you mean the hut, it is wooden. No texture packs are being used.

**Comment by Raycoms** [comment]
In the townhall no seperate texture set is selected for the citizens either, right? What citizen hut level does the worker have?

**Comment by SerranoPancake** [comment]
I don't even see that option in the town hall. It was at level 4 when this was happening. I haven't tried it since upgrading to level 5

**Comment by Raycoms** [comment]
worker hut or citizen hut?

**Comment by SerranoPancake** [comment]
Worker hut was 4 (now 5) Citizen hut is 5

**Comment by MotionlessTrain** [comment]
Also happening with unemployed citizens living in a level 4 house (but not level 3 house), as reported in #8234

**Comment by fairlyoddfaery** [comment]
This may be the same bug. Using Nordic skins. Citizen is male living in a level 4 house and employed. When deconstructing and picking up the hut building that the citizen is working at the skin gets messed up. Has happened 3 times for me so far. Only with male citizens. Don't know if anyone else has been able to reproduce it.

**Comment by SerranoPancake** [comment]
Can confirm, this issue is still happening. Had a child living in a level 4 citizen hut. When they grew up the texture for the skin glitched out. Changing skin textures in TH did not fix it.
![image](https://user-images.githubusercontent.com/20136617/166467056-bd25c1ac-2124-40e6-a569-95bd754619d5.png)

**Comment by Raycoms** [comment]
fixed
