### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by GD-00** [ldtteam/minecolonies#8196]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.18.2

### Structurize Version

1.18.2

### Related Mods and their Versions

1.18.2

### Current Behavior

Cannot craft sandstone colonies as they require cactus planks, and cactus planks are not craftable unless you have the "sawmill" which cannot be crafted out of sandstone because it too requires cactus planks, cactus planks may only be crafted at the sawmill so this is a flaw please fix so I may build a sandstone colony.

### Expected Behavior

NA

### Reproduction Steps

Allow cactus planks to be crafted in inventory and crafting table

### Logs

not sure

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
You don't need a sawmill, just make it in a crafting table - check JEI. 
5 cactus in an "x" shape (unless it drastically changed between 1.18.1 and 1.18.2 =P)

**Comment by MotionlessTrain** [comment]
And use the architect's cutter for the slabs, stairs and trapdoors
The latter of those may require green cactus extra as well, which is the same recipe as cactus extra/cactus planks, but with green dye in the middle instead
