### ISSUE TITLE
Addon: AE2 Citizen and work

### ISSUE THREAD

**Issue by Isfirs** [ldtteam/minecolonies#820]
In depth description will come later.

**Comment by AndrewTru** [comment]
@Isfirs , the thing here is that this seems to be more a 'pull request' for another mods API
I get the idea but at the same time the if('Mod name' == true) block will help it know when to start the API that is if one is made for it. I am thinking about how to lower its impact on the memory and CPU of the computer, why fire up and API if we don't need it for that pack/install.

**Comment by marvin-bitterlich** [comment]
@AndrewTru this is a worker we are planning that will enable when AE2 is detected

If you want to help the team, please consider applying: http://www.minecolonies.com/recruitment

**Comment by Raycoms** [comment]
I will close this here, it's something so far in the future. We shouldn't clutter this around here.
