### ISSUE TITLE
[BUG] Children will not grow up after many hours IRL

### ISSUE THREAD

**Issue by tomny-dev** [ldtteam/minecolonies#8204]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.18.2-1.0.552-ALPHA

### Structurize Version

1.18.2-1.0.370-ALPHA

### Related Mods and their Versions

1. Forge version: 1.18.2-40.0.32
2. Modpack: https://www.curseforge.com/minecraft/modpacks/medieval-minecraft-new (3/28/2022 version)

### Current Behavior

Initially, we were using the mod pack Medieval Minecraft [FORGE] v2 [MineColonies version 1.18.2-1.0.504-BETA] and had no issues, but after upgrading to Medieval Minecraft [FORGE] v3 [MineColonies version 1.18.2-1.0.552-ALPHA],
we are now having issues with children not growing up in both single-player and multiplayer.
Children will not grow up at all even after many hours IRL. 
Reverting back to Medieval Minecraft [FORGE] v2 [MineColonies version 1.18.2-1.0.504-BETA] allowed children to grow up fine, but I wanted to call this out because the latest version of the mod pack we use is causing issues.

### Expected Behavior

Children should grow up after a few in-game days.

### Reproduction Steps

1. Download the mod pack ([HERE](https://www.curseforge.com/minecraft/modpacks/medieval-minecraft-new))
2. Set up a Colony with children
3. Wait a few in-game days
4. Children will not grow up

### Logs

N/A

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
Just adding to this, there's been at least two other people today that have reported problems of the same thing, someone with the same version as in this report, another with minecolonies-1.18.1-1.0.553-ALPHA.jar

**Comment by tomny-dev** [comment]
@Raycoms Thanks for the quick fix. Can you also please release a 1.18.2 version build?

**Comment by Raycoms** [comment]
on its way
