### ISSUE TITLE
Spruce trees not dropping Spruce Sapplings HC

### ISSUE THREAD

**Issue by Daemanis** [ldtteam/minecolonies#8205]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.18.1-10

### Structurize Version

1.18.1-10

### Related Mods and their Versions

Forge Version: 39.0.59

### Current Behavior

Spruce trees have Oak leaves on them so they do not drop Spruce Sapplings instead they drop Oak sapplings meaning that farming them for the Caledonia builds is impossible

### Expected Behavior

Spruce trees to drop Spruce Sapplings

### Reproduction Steps

Find a Spruce tree, Chop it down, Drops Oak sapplings

### Logs

N/A.com.au

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
Minecolonies doesn't change the leaves on trees

**Comment by Daemanis** [comment]
I have no other mods installed so it has to be something in the modpack

**Comment by Talyda** [comment]
What mod pack?
This github is for the minecolonies mod, not a modpack =)  If you are having trouble with another mod then you need to contact them - Minecolonies doesn't change the behaviour of trees

**Comment by Daemanis** [comment]
It's the mine colonies official modpack and it linked here
