### ISSUE TITLE
[BUG] Stone mason does not want to craft Chiseled Nether Brick 

### ISSUE THREAD

**Issue by AlmightyAnubis** [ldtteam/minecolonies#8213]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

minecolonies-1.18.1-1.0.511-BETA

### Structurize Version

structurize-1.18.1-1.0.352-ALPHA

### Current Behavior

Stone mason does not accept recipe

### Expected Behavior

Stone mason does accept recipe

### Reproduction Steps

1. Teach Chiseled Nether Brick recipe to stone mason
2. Recive "Unable to store" -Recipe Message

### Logs

https://gist.github.com/AlmightyAnubis/16ec28cd76962b8093d0c0f47c36ec6c

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
Could you please try again with the latest alpha? (1.0.562)
A lot of blocks which were missing from the stone mason have been added in between those versions.

**Comment by AlmightyAnubis** [comment]
tested with minecolonies-1.18.1-1.0.566-ALPHA.jar but it doesn't allow the recipe
