### ISSUE TITLE
[BUG] Minecolonies vrs 562 breaks builders hut and graphics glitch in warehouse

### ISSUE THREAD

**Issue by SivartMcDorf** [ldtteam/minecolonies#8214]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

562

### Structurize Version

369

### Related Mods and their Versions

1. forge 39.1.2
2. Do .49
3. BLui  .47

### Current Behavior

When upgrading to 562 from 553 all builder hut blocks on server broke, and there is now a graphic glitch see convo from discord

The New update broke all builders blocks but kids are growing again
warehouse has a bit of a glitch too visual in racks
UnlikelyRaycoms — Today at 1:56 PM
thats nothing new
Mcdorf — Today at 2:07 PM
i never had it before this update where the inside of the rack is a bunch of purple boxes
Mcdorf — Today at 2:17 PM
the builders blocks though i have had to replace about 40 of them on the server so far though they are all broke
NotRaycoms — Today at 2:18 PM
!logs Could you provide the server's latest.log?
Assistant
BOT
 — Today at 2:18 PM
Unexpected error occurred dispatching command. Please report this to your bot admin.
NotRaycoms — Today at 2:19 PM
!logs Maybe you should do that as well, Assistant
Assistant
BOT
 — Today at 2:19 PM
To properly diagnose your issue we need access to your logs please. 
You can generally find these logs in your game or server directory under the logs folder. The file latest.log is most likely required.
Once you've found this file please post it on a paste site. As a team we recommend https://gist.github.com/.
Mcdorf — Today at 2:19 PM
https://gist.github.com/SivartMcDorf/ece89678ff488e9598bfe69bef228110
Gist
[Colony Builders Server Log](https://gist.github.com/SivartMcDorf/ece89678ff488e9598bfe69bef228110)[](https://github.githubassets.com/images/modules/gists/gist-og-image.png)[](https://cdn.discordapp.com/attachments/915411448342118441/959519542147682334/unknown.png)[](https://cdn.discordapp.com/attachments/915411448342118441/959519659672088637/unknown.png)
Colony Builders Server Log. GitHub Gist: instantly share code, notes, and snippets.
Colony Builders Server Log
you don't need to use the tricks on me i know what they say
NotRaycoms — Today at 2:20 PM
Just force of habit
Mcdorf — Today at 2:20 PM
understand
I replaced 12 or so for me, another 20 or so for another player and a few others for newer platyers
NotRaycoms — Today at 2:26 PM
Annoyingly, the latest.log doesn't say why they broke down
Mcdorf — Today at 2:27 PM
they all broke when i moved to the new update to fix the kids
NotRaycoms — Today at 2:27 PM
I hoped on some error that indicated what exactly caused it
Mcdorf — Today at 2:28 PM
only builders huts and the graphic glitch for warehouse
Image
Image
that i have found so far
NotRaycoms — Today at 2:30 PM
They didn't change anything regarding racks 🤔
I'm now starting to think that the mod didn't get downloaded properly or something like that
What version did you update from?
Mcdorf — Today at 2:30 PM
553
i'm rebooting to see if that clears it
but the builder hut is a server wide issue
NotRaycoms — Today at 2:33 PM
Not just the builder's hut. I have seen errors regarding the combat academy and school, and it looks like all requests from the request system gave errors, as I think the corresponding building(s) broke down as well
Mcdorf — Today at 2:33 PM
i will check those in a moment
NotRaycoms — Today at 2:34 PM
You may be able to restore a few/all of those buildings with /mc colony loadbackup <colonyid> by the way
Mcdorf — Today at 2:35 PM
tried that first
graphic glitch still there
NotRaycoms — Today at 2:36 PM
Did you perhaps restart the server down after upgrading and before you tried to load the backup?
Mcdorf — Today at 2:37 PM
yes
school, academy, and all seem fine
NotRaycoms — Today at 2:39 PM
Then I think you may have tried to load a backup from after the buildings broke. You can try deleting the colony.dat and minecraft folder in world/minecolonies, and unzip the zip from just before you upgraded. Those should have the data of the restored buildings, so you should be able to load those in
And if that gives an error, than that may clear up the cause of the buildings breaking down
Mcdorf — Today at 2:42 PM
not sure what you mean there
think i figured it out (what you said that is) 
ok reloaded from 6am backup still broken
https://gist.github.com/SivartMcDorf/389aadb572907c384648584215959e3c
Gist
[Colony Builders Logs](https://gist.github.com/SivartMcDorf/389aadb572907c384648584215959e3c)[](https://github.githubassets.com/images/modules/gists/gist-og-image.png)
Colony Builders Logs. GitHub Gist: instantly share code, notes, and snippets.
Colony Builders Logs
here is my logs if that helps maybe https://gist.github.com/SivartMcDorf/572d88a4edece7ef77c341994b9842cc
Gist
[Sivarts Logs](https://gist.github.com/SivartMcDorf/572d88a4edece7ef77c341994b9842cc)[](https://github.githubassets.com/images/modules/gists/gist-og-image.png)
Sivarts Logs. GitHub Gist: instantly share code, notes, and snippets.
Sivarts Logs
NotRaycoms — Today at 2:57 PM
After reading the first log, it seems it silently fails again unfortunately.
Though I see a lot of other errors of other mods, e.g. waila failing to load, advanced backpacks seems to have config issues, copperequipment seems to be missing, and a lot of missing ids from connectedclass, cookingforblockheads, glassential, elevatorid and refinedstorage.
I don't think these would cause broken buildings though
Mcdorf — Today at 2:58 PM
those have been there all along i removed those mods before the server opened
not sure how to clean that up
NotRaycoms — Today at 2:59 PM
Those should be harmless indeed. The 1.18 schematic server also gives errors that in can't find the timber frames and shingles etc. from structurize anymore. The world was ported from 1.16 using very careful techniques
Mcdorf — Today at 2:59 PM
it was not a ported world
NotRaycoms — Today at 2:59 PM
I can see something about the missing texture at least: Failed to load texture: minecolonies:textures/gui/gui144.png
NotRaycoms — Today at 3:00 PM
No, just the same types of errors, as mods are missing or blocks in mods are missing. Those errors are harmless
Mcdorf — Today at 3:01 PM
if that is the builder block GUI that could be the issue
NotRaycoms — Today at 3:02 PM
The first gui you opened just after you joined the server
I can't find the texture either (on github).
Mcdorf — Today at 3:03 PM
that would be the builder hut
NotRaycoms — Today at 3:08 PM
Could you make github issues for the missing textures and the broken buildings? Hopefully the devs have more of an idea what is happening here than I do

### Expected Behavior

update works

### Reproduction Steps

upgrade, play, and it is broken 

### Logs

https://discord.com/channels/139070364159311872/915411448342118441/959525566531403807

### Anything else?

personal logs here
https://discord.com/channels/139070364159311872/915411448342118441/959526786448900126

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
fix pushed
