### ISSUE TITLE
[BUG] Buildings may be built partially outside of colony borders

### ISSUE THREAD

**Issue by Arronicus** [ldtteam/minecolonies#8218]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.0.565

### Structurize Version

1.0.370

### Related Mods and their Versions

all for 1.18.2:
domum 1.0.41
JEI 9.5.2.135
minecolonies 1.0.565
multipiston 1.2.3
structurize 1.0.370
ui library mod 0.0.47

### Current Behavior

If I place a structure hut block within the colony borders, but part of the building (including the actual structure of the building) extends outside of the colony borders, the builder will accept the request and still build the building. I'm not sure on the exact circumstances as there's some finnicky-ness to it, I haven't tested many buildings, but the forester's hut absolutely works. 

### Expected Behavior

Apparently you're not supposed to be able to extend buildings at all beyond the colony border? I wasn't aware of this as I thought this bug was normal behaviour.

### Reproduction Steps

Place a hut block with the build tool such that the hut block is within the colony borders AND within range of a builder, but part of the building extends outside the border

Confirm the build that generates the build order

If it doesn't work, adjust it a little further in the colony, or try a different block

### Logs

nul

### Anything else?

Will try to upload images in a bit showing what I mean

**Comment by uecasm** [comment]
Are you playing in creative mode?  Some of the rules, such as this, are relaxed in creative, especially if you're pasting rather than having the builder build it normally.

**Comment by Arronicus** [comment]
Nope, this is in survival mode, placing and building in survival

**Comment by someaddons** [comment]
unable to reproduce this

**Comment by MotionlessTrain** [comment]
I found a screenshot from when they posted the issue on discord, if that is of any help. They were able to place the forester's hut here, half outside of the colony (hut block is just in the colony)


![forester's hut](https://media.discordapp.net/attachments/915411380268580864/960673124720971807/unknown.png)

**Comment by Raycoms** [comment]
Okay. That's the "ugly paste" that works always, no colony required.

**Comment by Raycoms** [comment]
What doesn't work is place + builder builds it. Creative placing always works

**Comment by MotionlessTrain** [comment]
This was in survival though, as they previously mentioned. They placed it with the green tick

**Comment by MotionlessTrain** [comment]
The screenshot was the preview in the build tool, just before they placed it. On discord, there was a second screenshot of just the hut block placed there

**Comment by Raycoms** [comment]
Placing might work, on clicking building there should be a warning then.

**Comment by Arronicus** [comment]
Hi, sorry, I practically never log in to github so I'm not used to following issues here, Discord is the easy way to reach me. I'll attempt it again tonight, but just some points to confirm:

The block is placed in survival mode

At least some portion of the structure itself is outside of the colony boundary

The builder successfully constructs the building

**Comment by Arronicus** [comment]
On the most recent version, I tried several different huts, and am only able to extend builds outside of the colony it would seem where the level 1 build portion of the build does not actually alter the terrain that is external to the claim, as you can see in these screenshots (blue wool is fully outside the boundaries of the village, red wool is fully inside the boundaries of the village. :

![image](https://user-images.githubusercontent.com/46831073/163670280-20036185-f609-4e41-bc44-7aab105fe47f.png)

![image](https://user-images.githubusercontent.com/46831073/163670298-29601999-31b7-4ec2-b966-7c98da602e82.png)

![image](https://user-images.githubusercontent.com/46831073/163670307-3369ab6b-4ce1-404d-ac0f-038cdf94eb1b.png)

So to be clear, the actual footprint of the build extends outside the colony, but no part of the building (at level 1 anyway) is able to extend outside the colony. In previous versions I was able to get some parts of the buildings themselves to extend outside the colony, but that part seems to no longer be the case. 

Here's the relevant versions if you're curious 

![image](https://user-images.githubusercontent.com/46831073/163670385-9592dbe9-c3a1-49d4-904a-e2428d030d91.png)
