### ISSUE TITLE
[BUG] Abandoned Colony World Generation Options Missing

### ISSUE THREAD

**Issue by Zerris** [ldtteam/minecolonies#8220]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.18.2-1.0557-Alpha

### Structurize Version

structurize-1.18.2-1.0.370-ALPHA

### Current Behavior

Currently the options for disabling or even adjusting world generation in regards to Abandoned Colonies is completely missing from the minecolonies-server.toml file. 

### Expected Behavior

I expected to find the option to disable the world generation for abandoned colonies in the server config file, could not find any section for this.

### Reproduction Steps

Create a new world then check the server file that is generated.

### Logs

https://pastebin.com/7F7DfpMu

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
Now that someone opened an issue and reminded me - there was a couple other reports of this in 1.18.2, and I just checked the config in the instance i made to test something the other day, and the "disableemptycolonies" line is definitely missing

**Comment by Raycoms** [comment]
That is now fully data driven according to the 1.18.2 changes.

**Comment by Talyda** [comment]
What does that mean"? When people want to turn it off, how do they do so?

**Comment by Raycoms** [comment]
https://github.com/ldtteam/minecolonies/blob/version/1.18.2/src/main/resources/data/minecolonies/worldgen/structure_set/empty_colony.json

datapack this here with 

"structures": [ ]

**Comment by Talyda** [comment]
Ah! Thanks!

**Comment by EnderDJ98** [comment]
Sooooo....

Anyone got the it in data pack form?

I tried to make it but fail.

**Comment by jkkiller101** [comment]
So im trying to do the same thing here in 1.18.2 and cant figure out how to make the datapack as the setting is missing in the config folder. Any help is appreciated

**Comment by MotionlessTrain** [comment]
There is a datapack pinned on our discord server, in the #support-118 channel
(You can find our discord server on https://discord.minecolonies.com)

**Comment by jkkiller101** [comment]
Thank you so much!
