### ISSUE TITLE
[BUG] O construtor fica pedindo uma tesoura de poda, que não tem no mod e a no mine não funciona. Versão: 1.16.5

### ISSUE THREAD

**Issue by gabuoi** [ldtteam/minecolonies#8223]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.16

### MineColonies Version

1.16.5

### Structurize Version

1.16.5

### Related Mods and their Versions

 1.16.5

### Current Behavior

1.16.5

### Expected Behavior

1.16.5

### Reproduction Steps

1.16.5

### Logs

1.16.5

### Anything else?

1.16.5

**Comment by Raycoms** [comment]
Please english issues.
