### ISSUE TITLE
[BUG] Stone Mason does not save Custom Recipes using colored Terracotta blocks

### ISSUE THREAD

**Issue by revdave33** [ldtteam/minecolonies#8224]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.18.2-1.0.568-BETA

### Structurize Version

1.18.2-1.0.370-ALPHA

### Current Behavior

I go to the Custom Recipe tab on the Stonemason hut to enter a recipe using a colored Terracotta block (for example to make White Terracotta Wall as requested for a Lost City construction). When I click on the teach button it says that it cannot save either because there are no spaces left or it isn't appropriate for that worker. 
It is only the 3rd recipe I've taught it. The plain Terracotta block is accepted as a valid recipe.

### Expected Behavior

The recipe would be learned successfully.

### Reproduction Steps

1. Go to Stonemason hut
2. choose Custom Recipe tab
3. under first input choose any colored Terracotta block
4. choose Teach

### Logs

If you want logs let me know.

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
I double checked this after they mentioned it on discord (in 1.0.566) and is happening on that version too - regular terracotta is fine, any coloured it won't accept

**Comment by MotionlessTrain** [comment]
Does the dyer have a custom recipe tab? If so, they may be the appropriate crafter (or maybe the mechanic) instead of the stone mason

**Comment by Talyda** [comment]
I'll check after dinner, but you would think the stonemason would accept coloured terracotta - it simply doesn't accept it

*edits* didn't realise I still had game open - mechanic does accept it.
But that seems like a very wrong choice

**Comment by Raycoms** [comment]
The dyer is the right job for this.

**Comment by Raycoms** [comment]
Misunderstood, yes, this should go to the stonemason
