### ISSUE TITLE
[BUG] <Farmer crash>

### ISSUE THREAD

**Issue by crazydud24** [ldtteam/minecolonies#8229]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.0.577

### Structurize Version

1.0.369

### Reproduction Steps

I completed a lv1 farmers hut at the edge of my village. I assigned an jobless colonist and this crash happened. it now crashes every time I load the world

### Logs

https://pastebin.com/01LrtJDC 

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
I guess the sloped fields feature has been tested with an old version of forge, from before the changes to the DIRT field.
It seems like it references to this field again, yielding the same type of errors as before

**Comment by MotionlessTrain** [comment]
#8230 has additional information. (That issue got opened by accident, it seems)

**Comment by Raycoms** [comment]
fix pushed

**Comment by MotionlessTrain** [comment]
For some reason, version 1.0.579 containing the fix is not available on curseforge. Is it possible to upload/release that version again, or to rebuild it?
