### ISSUE TITLE
Colonists going to unmanned restraunts

### ISSUE THREAD

**Issue by Moobien** [ldtteam/minecolonies#8233]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.18.2-1.0.583

### Structurize Version

1.18.2-1.0.370

### Related Mods and their Versions

N/A

### Current Behavior

Had an abandoned colony spawn with 4 restraunts. hired a cook to one, and colonists go to wait to be fed at whatever restraunt is closest to them, INCLUDING ones with no worker.

### Expected Behavior

Colonists only go to restraunts that have a hired worker.

### Reproduction Steps

Find a Colony with more than 1 restraunt.
Hire a cook.
Wait to see where hungry colonists go to eat.

### Logs

n/a

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
That's correct behaviour, they will eventually serve themselves if no worker is available
