### ISSUE TITLE
[BUG] <Messed up texture for medieval unempleyed in lvl 4 housing>

### ISSUE THREAD

**Issue by DragonKitten** [ldtteam/minecolonies#8234]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.18.1-1.0.567-BETA

### Structurize Version

structurize-1.18.1-1.0.369-ALPHA

### Current Behavior

Am running a colony with the medieval citizen style, and after starting to upgrade my housing to lvl 4 i noticed that one of my people have a messed up texture
![image](https://user-images.githubusercontent.com/12358942/162394251-502229e1-4321-4cf6-8669-eef3edb029fa.png)

### Expected Behavior

normal texture display

### Reproduction Steps

1. have unemployed citizen
2. set citizen style to medieval
3. assign them to lvl 4 house

### Logs

N/A

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
Sorry, I should have checked before I sent you to github. It turns out it was already posted in #8194
