### ISSUE TITLE
My miner is asking for a tool that doesnt exist......

### ISSUE THREAD

**Issue by Nachtus01** [ldtteam/minecolonies#824]
### Minecolonies version

version R1.0.2 

### Expected behavior

- Miner should ask for a pick axe of a minimum of stone quality to a maximum of diamond quality.

### Actual behavior

- Miner asks for a pick axe of a minimum of diamond quality to a maximum of stone quality. Results in not being any pick axe that satisfies his need.

### Steps to reproduce the problem

Not sure how to reproduce the issue. My miners hut is lvl 0, so the best tools he should be asking for is stone, if I understand the mechanics correctly. Anyways, I am guessing that this would be a scripting behavior issue not a config file issue, but i looked for something in the configs anyways, but didn't find anything.

**Comment by marvin-bitterlich** [comment]
we fixed that bug already :)

**Comment by Nachtus01** [comment]
"Kostronor commented an hour ago

we fixed that bug already :)"

I am not sure what that is supposed to mean. Are you saying its my imagination? If I go to sleep, in the morning my miner will be all better? Because as of right now, I have a miner in my colony that apparently didn't get the memo that you "fixed him". And you have provided no information directing me to what I should do, (if its something on my end that need be done), nor have you provided me with any links or whatever that direct me to any patch notes showing how/what to do etc. So now what? I have tried to look up anything related to this, but I'm guessing that since you fixed it, you also closed it, and the search options that I am given on github, seem to only allow me to search open items, and anything open or closed directly related to my own posts.

**Comment by marvin-bitterlich** [comment]
I am just saying there already exists an issue stating exactly that. And there exists a fix with a pr and I think I remember correctly that pr is already merged and a new version will be on curse the next days

**Comment by marvin-bitterlich** [comment]
#778 #817 for reference

**Comment by Nachtus01** [comment]
Oh, ok, thanks. Sorry, I am new to the whole github thing, and so much of the jargon also is new, but, whats a PR? And I did see #817. Didn't think it would be considered the same issue as his builder is maxed out and has no higher tier of tool to ask for, whereas mine is actually asking for a tool that doesn't exit.

**Comment by marvin-bitterlich** [comment]
The thing is:
Your miner found a block from a mod that requires a higher mining level then diamond. And our old code has an overflow problem. So mining level 5 and greater would go around to becoming stone again. So we capped it with "greater then diamond" for now.

So yeah this fixes your bug too :)

And sorry to be a bit rough. We get many bugs that are duplicates of existing ones and we have to go through our over 100 open bugs each day to close them ;)

**Comment by marvin-bitterlich** [comment]
It may be that after the fix you have a second bug. Just post a new issue if that is the case :)
