### ISSUE TITLE
[BUG] Courrier not delivering ressources to builder / not doing pickups

### ISSUE THREAD

**Issue by Ramodo** [ldtteam/minecolonies#8245]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

minecolonies-1.18.2-1.0.585-BETA

### Structurize Version

structurize-1.18.2-1.0.370-ALPHA

### Related Mods and their Versions

Forge 40.0.44
blockui-1.18.2-0.0.47-ALPHA
domum_ornamentum-1.18.2-1.0.48-ALPHA-universal
multi-piston-1.18.2-1.2.3-ALPHA

### Current Behavior

Courriers are unable to deliver results of craft to builders and are unable to perform pickups of several huts (blacksmith, stonesmelter and stonemason). They are able to deliver resources from the wharehouse to the huts but not to pickup the finished goods. They are able to do pickups of other huts (it works for builders) but not of the huts listed above.

![image](https://user-images.githubusercontent.com/33554609/162644118-e3650b64-0023-41a1-abe6-55320896f568.png)

### Expected Behavior

Courrier should be able to deliver the resources and to perform the pickups

### Reproduction Steps

1. Builder request resources
2. Stonemason / Stonesmelter / Blacksmith perform craft
3. Courrier doesn't deliver resources from those huts

1. Request pickup of a hut
2. No message appears in the chat
3. Request pickup again
4. "unable to comply, a pickup is already in progress"
5. No courrier comes for a pickup

### Logs

https://pastebin.com/gH2eb8zs

### Anything else?

Paste is latest.log of the 1.18.1 version (I play on the modpack) but I tested the issue in the lastest version of minecolonies and it happened as well

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
can you try a /mc colony request-system-reset command? it seems you got some corrupted RS data around.

**Comment by Ramodo** [comment]
Just tried it, it didn't solve the issue

**Comment by Ramodo** [comment]
Update : Just before that bug appeared, I had built a second wharehouse but didn't assign any courriers to it
When I removed the hut block of this wharehouse, It solved the issue
