### ISSUE TITLE
[BUG] HUD elements rendering under structurize blocks

### ISSUE THREAD

**Issue by hivehum** [ldtteam/minecolonies#8246]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.18.1-1.0.589

### Structurize Version

1.18.1-1.0.378

### Related Mods and their Versions

running All the Mods 7-0.2.45 with the addition of [Apathetic Mobs Reborn (Forge)](https://www.curseforge.com/minecraft/mc-mods/apathetic-mobs-reborn-forge) and the specified versions of minecolonies + structurize

### Current Behavior

the colonist HUD element (specifically the orange message box; i have not yet observed this with the other icons) is rendering under structurize blocks. here is a short video demonstration: https://cdn.discordapp.com/attachments/915411448342118441/962944810723983400/2022-04-11_01-17-06.mp4

### Expected Behavior

colonist icons should render over all blocks

### Reproduction Steps

1. position a colonist with a message near a structurize block
2. look at them at an angle so the structurize block is over the icon

### Logs

https://gist.github.com/hivehum/e8c805fd419ee39acac269fc156ed2f2

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Nightenom** [comment]
Known thing, fix is low priority now
