### ISSUE TITLE
[FEATURE REQUEST] remove F3 info on nearness of colonies

### ISSUE THREAD

**Issue by Zygus42** [ldtteam/minecolonies#825]
minecolonies-universal-1.10.2-0.6.112
Could you please make the F3 info on nearness of colonies an optional setting in the config ?  It's not something we're ever interested in, and it's using up some processing power, however small, every scrap of which we're badly in need of.

**Comment by marchermans** [comment]
The question is why are you looking at the F3, If you want to spare you calculation power looking at the f3 is bad in general as it does some extra calculations. On top of that it is a debug screen, there is generally nothing you would really need in there.

That sad however we could only activate it in the debug mode. @Raycoms @Kostronor ?

**Comment by marvin-bitterlich** [comment]
Many people rely on this extra info (like they rely on coordinates in F3) and until we have a replacement gui I am against removing it.

**Comment by Zygus42** [comment]
Using F3 to test what sort of strain assorted mods are causing in my new server/modpack build.

I guess my concern is that the calculations are being done even when F3 is not on.  If this is not the case, then it's not a problem.

**Comment by Raycoms** [comment]
no only happen if trigerred and only on clientside

2017-04-19 23:36 GMT-03:00 Zygus42 <notifications@github.com>:
