### ISSUE TITLE
[BUG] Colony name does not show for other players on server

### ISSUE THREAD

**Issue by Nikademus** [ldtteam/minecolonies#8254]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.18.2-1.0.568-BETA

### Structurize Version

1.18.2-1.0.370-ALPHA

### Current Behavior

When a player enters someone else's colony, the name is not shown to the player.

What the colony owner sees:

![Untitled](https://user-images.githubusercontent.com/1380028/163288910-766d25fa-412f-40a7-9ea9-31310a98f411.png)

What the other player sees:
![unknown1](https://user-images.githubusercontent.com/1380028/163288957-777a1c71-0428-4009-8f09-030d19a0f076.png)

### Expected Behavior

Players should see the name of the colony.

### Reproduction Steps

1. Rename colony in town hall
2. Have another player enter the town border

### Logs

https://gist.github.com/Nikademus/c930d4249f85c2682241a80d0ae7789f

**Comment by Raycoms** [comment]
I think this was fixed by @Thodor12 in his PR
