### ISSUE TITLE
[BUG] Colony safe area prevents deployers from the create mod to work properly

### ISSUE THREAD

**Issue by yuvalyly** [ldtteam/minecolonies#8255]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.16

### MineColonies Version

1.16.5-1.0.613-ALPHA

### Structurize Version

1.16.5-1.0.380-BETA

### Related Mods and their Versions

Create - create-mc1.16.5_v0.3.2g

### Current Behavior

The deployer block from the create mod is for some reason considered a player by the mod and thus is limited by the colony safe zone, because it is defaulted to neutral. It can be fixed by changing the neutral permissions, but then any random player who comes by can do those things as well, because he/she is also neutral by default.
The video is to big for the file size limit so I uploaded it to youtube as unlisted: https://www.youtube.com/watch?v=Nm8qKqgN67c

### Expected Behavior

The deployer is suppose to mimic player actions, mostly used to place blocks automatically, and should be able to do so without special permission from the colony owner, considering that only players with permission to place blocks would be able to place the deployer in the first place.

### Reproduction Steps

1. Start a colony.
2. Place a deployer inside the colony's safe zone.
3. Connect the deployer to any power source from the create mod.
4. Right-click the front face of the deployer (the side with the hand) with any placable block to give the block to the deployer.
5. Then the deployer should attempt to place that block 2 blocks in front of itself.

### Logs

https://gist.github.com/yuvalyly/3feb020e877464e73f4c895746f2fc50

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Two details:
a) Please report this to the create mod. They did not setup the fakeplayers correctly.
b) We have a workaround to allow (after a level 1 townhall) see permission events and add the create fakeplayers in the townhall UI.
