### ISSUE TITLE
[BUG] 1.18.2 Assigned Tasks tab missing from Courier's Hut

### ISSUE THREAD

**Issue by revdave33** [ldtteam/minecolonies#8256]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.18.2-1.0.612-ALPHA

### Structurize Version

1.18.2-1.0.379-ALPHA

### Related Mods and their Versions

Forge: 40.0.46

### Current Behavior

Open up the Courier Hut GUI and there is not Assigned Tasks tab to check for the delivery/pickup queue

### Expected Behavior

A tab to see what a particular Courier has on their list of tasks. (Usually looking for where the Stash pickup is in the list)

### Reproduction Steps

1. Click on the Courier Hut to open its GUI.

### Logs

None Needed.

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
fix pushed
