### ISSUE TITLE
[BUG] Planter AI Issue

### ISSUE THREAD

**Issue by MotionlessTrain** [ldtteam/minecolonies#8257]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.16

### MineColonies Version

1.0.613

### Structurize Version

1.0.380

### Reproduction Steps

1. Have a level 3 plantation
2. Complete the Double Trouble research
3. Have the planter plant sugercane and cactus

### Logs

https://gist.github.com/a47db17ad9e59c7c38a29cf478896de5

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
Which plantation schematic did you use?
This is caused because `plantation.getAllSoilPositions()` returns no results, so it's possible there's no sand positions tagged

**Comment by MotionlessTrain** [comment]
Fortress

The sugarcane and cactus are planted on their respective spots, it seems like, so I guess the tags are present.
But I'll double check just in case

**Comment by MotionlessTrain** [comment]
Yes. The tags `sugar`, `cactus` and `bamboo` are all applied 12 times, which seems correct

**Comment by Thodor12** [comment]
I cannot get this issue replicated on Fortress, I've found some other small issues which I'll fix and add a safety protection so this error cannot happen, but I do not know the root cause

**Comment by MotionlessTrain** [comment]
It doesn't seem to get triggered everytime, but only sometimes.
I noticed the issue, was about to open an issue on github, but decided to update minecolonies first (it was a few versions outdated). After that I didn't notice it anymore, until I opened the game today, and the planter had the issue again.

**Comment by Thodor12** [comment]
I'll add a protection around the random so that it requires at least 1 planting position, at least if it does randomly decide to return 0 working positions at least it won't outright crash the AI
