### ISSUE TITLE
[BUG] Right Click interaction issue

### ISSUE THREAD

**Issue by SinFlame** [ldtteam/minecolonies#8261]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.0.612-ALPHA

### Structurize Version

1.0.379-BETA

### Current Behavior

Right clicking a colonist will crash the client.(But not the server)

### Expected Behavior

Should bring up a GUI.

### Reproduction Steps

1) Right click on Colonist

### Logs

https://gist.github.com/SinFlame/d36dcb6e8419be5b2a91c9419c6da50d

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
Just adding a note - I had them downgrade to version ending in .594 (before the right click interactions were introduced) and they can use right click normally on tha version

**Comment by SinFlame** [comment]
Add on note - Affects visitors too, not only colonists.

**Comment by SinFlame** [comment]
Updated note - Going on to single player first and then to multiplayer(server) fixes this issue

**Comment by SinFlame** [comment]
#8262 has fixed this issue. Tested and works properly now. Thanks!
