### ISSUE TITLE
[BUG] Schematics dont show after placement

### ISSUE THREAD

**Issue by lukaszbanas** [ldtteam/minecolonies#8264]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.16

### MineColonies Version

1.16.5-1.0.507-BETA

### Structurize Version

1.16.5-1.0.355-ALPHA

### Related Mods and their Versions

modpack Life in the village 2 https://www.curseforge.com/minecraft/modpacks/life-in-the-village-2

### Current Behavior

after placing starting camp in multiplayer, only half of blocks are shown up. Other ones are invisible, and cannot walk through them. After relog, they are shown correctly. Same things goes to building - tape around building sites are not shown, sometimes building block (the one with building options) is also invisible.
This issue don`t appear in single player.

### Expected Behavior

blocks should be visible

### Reproduction Steps

start a pack on a server and play

### Logs

https://pastebin.com/2SVbJVSc

### Anything else?

on single player, it works corectly. No optifine. 

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
This can happen if you have a lot of mods installed. The connection between server and client gets overloaded when the supply camp (or build tool) places the blocks. Relogging, going far away or going to another dimension all help.

There are also mods that improve the connection between client and server, and mitigate this. E.g. [connectivity](https://www.curseforge.com/minecraft/mc-mods/connectivity)

**Comment by Raycoms** [comment]
Yeah, this should not be a MineColonies issue. We just happen to place a lot of blocks.
