### ISSUE TITLE
[BUG] No audio from Jukebox

### ISSUE THREAD

**Issue by Nikademus** [ldtteam/minecolonies#8268]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

minecolonies-1.18.2-1.0.632-ALPHA

### Structurize Version

structurize-1.18.2-1.0.379-BETA

### Related Mods and their Versions

Forge 40.0.24
blockui-1.18.2-0.0.47-ALPHA
domum_ornamentum-1.18.2-1.0.48-ALPHA-universal
multi-piston-1.18.2-1.2.3-ALPHA

### Current Behavior

Place a music disc into a jukebox, you get the "now playing" message, but hear no music.

### Expected Behavior

Music should play

### Reproduction Steps

1. Place a jukebox
2. Insert a music disc

### Logs

https://gist.github.com/Nikademus/33c4fca2336fa817263b676ad4cc6eaf

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Why is this a minecolonies issue?

**Comment by MotionlessTrain** [comment]
After some testing of Nikademus and Shindria, it seems to be a forge issue indeed
