### ISSUE TITLE
[BUG] Baker isn't baking

### ISSUE THREAD

**Issue by xstarlotte** [ldtteam/minecolonies#8270]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.18.2-1.0.625-ALPHA

### Structurize Version

1.18.2-1.0.379-BETA

### Related Mods and their Versions

1. 40.0.44
2.1.18.2-16.0.0.107
3. 1.18.2-1.0.48-ALPHA

### Current Behavior

The baker will not craft dough or bake bread.
I have tried requesting a stack of bread from the cook and the warehouse, tried together and separately. I have also tried requesting bread dough to the cook. I have given the baker over 6 stacks of wheat, a large amount of water bottles, stacks of coal which are also in his furnaces, his inventory is empty, there is wheat and coal in his racks upstairs, I have requesting tried with and without an assistant cook.
The bakery is level 5, the cook is level 5 (all my buildings are level 5).
I have tried firing and rehiring, restarting the baker, restarting the game, I have had this issue since 1.16 (I always have this mod in my modpacks) and throughout different worlds both soloplayer and multiplayer.
The baker lives right next to his house, he is happy, he isn't hungry, he doesn't request anything.
Coal is turned on in the fuel tab.
There is a guard tower right next to it.
There is also more wheat and water bottles available in the warehouse.
Moobien from the discord tried replicating the error, and he found that after making 62 bread dough, after requesting 64, the baker just stopped. He had enough resources to make more but he just didn't. Both bakers are just walking around slowly doing nothing.

### Expected Behavior

The baker creates dough and bakes it into bread when it is requested.

### Reproduction Steps

Just request bread from the baker, to your cook or warehouse. Give him all the things he needs. Try with a level 5 medievalbirch (or medievalbirchalternative I cant remember which) baker and cook.

### Logs

There is nothing in the logs to relate to this issue

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Moobien** [comment]
Can confirm this is happening in 1.18.2 also. Requested 1 stack of bread. Baker made 62/64 bread dough, stored it in the racks and then went wandering outside

**Comment by xstarlotte** [comment]
https://pastebin.com/5sXPFkWH - LOGS

**Comment by Raycoms** [comment]
Can you tell me if the baker got enough space for all the water bottles in the hut inventory?

**Comment by Moobien** [comment]
> Can you tell me if the baker got enough space for all the water bottles in the hut inventory?

Mine didnt need water bottles and had empty racks to begin with. A couple of real world days and mcol updates later it 'appears' to be working ok

**Comment by Raycoms** [comment]
Can't reproduce this with the available resources at the warehouse and space at the crafter. Got 16 up to 65 well fulfilled.
