### ISSUE TITLE
[BUG] Missing mod compat between Raider's Bane and EnchantmentDescriptions mod

### ISSUE THREAD

**Issue by mc-kaishixiaxue** [ldtteam/minecolonies#8274]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.0.644-alpha

### Structurize Version

1.0.389-release

### Related Mods and their Versions

EnchantmentDescriptions: 10.0.3
Bookshelf: 13.0.12

### Current Behavior

Show `enchantment.minecolonies.raider_damage_enchant.desc` on tooltip when installed EnchantmentDescriptions mod.

### Expected Behavior

`enchantment.minecolonies.raider_damage_enchant.desc` should have own description text.

### Reproduction Steps

1. Get a Raider's Bane enchanted book in creative mode inventory;
2. Look up its tooltip.

### Logs

https://gist.github.com/mc-kaishixiaxue/b1400953fd2dea6aa20494efdea0531b

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by baz1l** [comment]
Hey, just making sure but is this what you see?
![image](https://user-images.githubusercontent.com/40123555/163844343-734308f1-e52c-40d2-a39e-bff43a7f4c4f.png)
Vanilla enchantment books also don't have a unique tooltip either. They're just called `minecraft:enchanted:book`, just like Raider's Bane so I don't think this is a bug.

**Comment by Raycoms** [comment]
It's more of a "missing mod compat" I believe
