### ISSUE TITLE
[BUG] Speech bubble icons render even with HUD off

### ISSUE THREAD

**Issue by 0DeltaWaves** [ldtteam/minecolonies#8276]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.18.1-1.0.649

### Structurize Version

1.18.1-1.0.387

### Related Mods and their Versions

forge 39.1.0
blockui 0.0.45
donum ornamentum 1.0.49

### Current Behavior

![2022-04-18_18 50 48](https://user-images.githubusercontent.com/82335536/163895314-45ea4d48-2386-4a79-9b92-87650ed678f4.png)
Speech bubbles render even when F1 is pressed

### Expected Behavior

No UI elements should render when the HUD is turned off, as it interferes with screenshots

### Reproduction Steps

1) Have at least one worker with a speech bubble icon
2) Press F1

### Logs

don't believe that's necessary

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Imo, it's not an UI element and is fine to render in this situation.

**Comment by 0DeltaWaves** [comment]
> Imo, it's not an UI element and is fine to render in this situation.

I disagree. UI or not, things like that interfere with screenshots. Colonist names also have the same issue, while in the vanilla game, player names turn off appropriately when the HUD is turned off

**Comment by marchermans** [comment]
@0DeltaWaves Is correct here, since Mojang hides the nameplate, that should be the ruleset to follow. We should not render any additional information besides the model if the screenshot mode is enabled.
