### ISSUE TITLE
Town Hall does not show building names

### ISSUE THREAD

**Issue by smmmadden** [ldtteam/minecolonies#8289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.18.2-1.0.654-ALPHA

### Structurize Version

1.18.2-1.0.389-RELEASE

### Related Mods and their Versions

Forge Version: 40.0.1
Multi-piston 1.18.2-1.2.3-ALPHA
Domum_ornamentum 1.18.2-1.0.50-ALPHA
BlockUI 1.18.2-0.0.47-ALPHA

### Current Behavior

![image](https://user-images.githubusercontent.com/10309346/164877714-d7b3551c-a998-4b94-83d7-575c73e2db08.png)

### Expected Behavior

Should show building names, not code snippets

### Reproduction Steps

Go to town hall after sending builders to build stuff and check the display above

### Logs

https://pastebin.com/ududqtYy

### Anything else?

switch between creative and survival modes, but mostly creative 

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
@Thodor12

**Comment by Thodor12** [comment]
Might already be fixed by #8287 but I'd have to double check

**Comment by Thodor12** [comment]
Fixed in the above mentioned PR

**Comment by smmmadden** [comment]
Thanks, will keep an eye on it to see which build it gets made to
