### ISSUE TITLE
[1.11.2] Crash on start.

### ISSUE THREAD

**Issue by Sejoslaw** [ldtteam/minecolonies#829]
### Minecolonies version

version minecolonies-universal-1.11-0.6.3360

### Expected behavior

- Start game normally.

### Actual behaviour

- Crash on start.

### Steps to reproduce the problem

1. Start MC.

[Crash Report](https://pastebin.com/4dBKDiKs)

**Comment by xavierh** [comment]
Could you try the latest build ?

**Comment by Sejoslaw** [comment]
Version used:  minecolonies-universal-1.11.2-0.7.811.jar

Just checked and it crashed in different place.
[Crash Report](https://pastebin.com/Cn2SkMrz)
It seems to crash on: `com.minecolonies.coremod.event.FMLEventHandler.onClientTick(FMLEventHandler.java:39)` 
with error `java.lang.NoClassDefFoundError: com/minecolonies/coremod/colony/ColonyManager`
with last forge debug line:
`[13:21:58] [Client thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.TickEvent$ClientTickEvent@1b25a7a1:`

Also it broke before the game fully loaded.

**Comment by Raycoms** [comment]
Still happening with the newest version?

**Comment by Sejoslaw** [comment]
It still crash in the same way - [Crash Report](https://pastebin.com/Aq7XDc68) - `java.lang.NoClassDefFoundError: com/minecolonies/coremod/colony/ColonyManager
	at com.minecolonies.coremod.event.FMLEventHandler.onClientTick(FMLEventHandler.java:39) ~[FMLEventHandler.class:?]`
I'm using Forge 2259. Could that be a problem ?

**Comment by marvin-bitterlich** [comment]
@OrionDevelopment any issues with the build system?

**Comment by cltnschlosser** [comment]
Either the build you have is bad, or this is a forge issue. Assuming forge has a custom classloader that is acting strangely.

**Comment by cltnschlosser** [comment]
@Sejoslaw Looks like we are building for forge version 13.20.0.2228, which is the latest recommended build. Maybe try using that?

**Comment by Sejoslaw** [comment]
Using:
Forge - 13.20.0.2228
Minecolonies - minecolonies-universal-1.11.2-0.8.1450   (latest)
[Crash](https://pastebin.com/3e1F0cG9)
It is still crashing in `java.lang.NoClassDefFoundError: com/minecolonies/coremod/colony/ColonyManager`
With last on stacktrace `at com.minecolonies.coremod.event.FMLEventHandler.onClientTick(FMLEventHandler.java:39) ~[FMLEventHandler.class:?]`
What's more is that it couldn't load any sound. For instance: `[12:51:09] [Client thread/WARN]: File minecolonies:sounds/mob/deliveryman/female/time2go2sleep2.ogg does not exist, cannot add it to event minecolonies:mob.deliveryman.female.offtobed`

**Comment by cltnschlosser** [comment]
Sound thing is unrelated, there is a PR to fix that now.

**Comment by cltnschlosser** [comment]
I'm unable to reproduce this, I've even ran it inside the VanillaMagic dev environment as it looks like thats what you're doing. This is really strange, it looks like its unable to find the Colony or ColonyManager classes. I'd try updating to latest java version. Mine is newer than yours, so its possible there was a ClassLoader issue in the version you have.
