### ISSUE TITLE
Unable to teach stonemason recipe using DeepSlate Bricks

### ISSUE THREAD

**Issue by SerranoPancake** [ldtteam/minecolonies#8298]
DO version 1.0.50-Alpha
Minecolonies 1.0.662-Alpha

Attempting to teach StoneMason in Minecolonies a custom recipe for DeepSlate Brick Panel as requested by builder gives "Unable to store recipe" message. Architect cutter recipes using DeepSlate bricks combined with another material work fine.
![image](https://user-images.githubusercontent.com/20136617/165421174-01fcef89-70a2-4918-b4a9-c0e6e9f168f7.png)

**Comment by LadyShatana** [comment]
I use these a lot! Please please pleaaaaaaase fix! <3 !!!

**Comment by uecasm** [comment]
I'm not entirely sure why, but deepslate bricks are considered a Mechanic recipe, not a Stonemason one.

This should be more obvious once #8282 is merged, as this adds JEI support to figure out which crafter will accept which material.

**Comment by uecasm** [comment]
Looks like the "why" is just that the mechanic handles anything not handled by any of the other crafters.  Possibly some of these things ought to be moved.

**Comment by Raycoms** [comment]
can you adjust deepslate to the stonemason @uecasm ?

**Comment by uecasm** [comment]
Yeah, was planning to do a full pass on the domum materials from the spreadsheet after #8282 merges, to avoid conflicts.  Or I guess I could add it to that if you don't mind re-reviewing it?

**Comment by LadyShatana** [comment]
lol I never in a million years would have thought to look at the mechanic for this!
