### ISSUE TITLE
Can't Research LAN

### ISSUE THREAD

**Issue by Josbud1** [ldtteam/minecolonies#8301]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

minecolonies-1.18.2-1.0.662-ALPHA.jar

### Structurize Version

structurize-1.18.2-1.0.389-RELEASE.jar

### Current Behavior

Well in a LAN game only the host can research

### Expected Behavior

Being able to research

### Reproduction Steps

Host a LAN world and have a friend try to research in their colony

### Logs

not sure

### Anything else?

* Add a thumbs-up to the bug repor
![research](https://user-images.githubusercontent.com/93408749/165832598-be3cbe12-dde7-40a4-9bee-9dcb5c1cde87.PNG)
t if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
LAN mode is at the current moment not yet supported. Please host a local server

**Comment by MotionlessTrain** [comment]
@OrionDevelopment told me to ask them to open an issue here

**Comment by marchermans** [comment]
I did.
If this is really the problem, I would consider it a problem worth solving, since it would mean that there is generally something wrong with the research UI.

Practically speaking the integrated server should not behave different from the dedicated one (yes I know there are differences, does not mean that their logic is not 99% identical)

**Comment by Seba244c** [comment]
Can confirm this is a problem, but hosting a local server fixed it for me.

**Comment by DrSigma4164** [comment]
On version 1.16.5-1.0.878-BETA, the same problem. Only the server host can choose research, also this window is shown every time like the screenshot below for non-host players.
![photo_2022-07-14_22-09-55](https://user-images.githubusercontent.com/93322905/179064163-51d14368-3ccb-4099-b9e6-a459fe246ea6.jpg)

**Comment by marchermans** [comment]
This is a known bug in 1.16.5 there is nothing we can do to fix it since it is in forge

**Comment by YummyCoin5155** [comment]
i have this exact same problem it really needs to get fixed because me and my friend wants to keep upgrading our things and we cant without being able to research stuff within the university and such

**Comment by Talyda** [comment]
> i have this exact same problem it really needs to get fixed because me and my friend wants to keep upgrading our things and we cant without being able to research stuff within the university and such

You can fix it by making an actual server =) We can't help you with LAN
