### ISSUE TITLE
[BUG] Smeltery has an empty recipe tab

### ISSUE THREAD

**Issue by Nikademus** [ldtteam/minecolonies#8303]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.18.2-1.0.659-ALPHA

### Structurize Version

1.18.2-1.0.389-RELEASE

### Current Behavior

The smeltery has a Custom Recipes tab (second tab) that is blank.  Nothing is listed and you can't add recipes.
![smelt2](https://user-images.githubusercontent.com/1380028/165998583-9f193b7c-a03b-444d-b96e-8e57752389b9.png)

### Expected Behavior

Typically you can disable or teach recipes when this page is displayed.

### Reproduction Steps

Open Smeltery GUI
Select second tab, Custom Recipes

### Logs

no log needed

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
This is actually intentional. The recipes will display once unlocked.

**Comment by MotionlessTrain** [comment]
What kind of recipes does the smelter do?
I didn't think they were a crafter (Hence I sent them here)

**Comment by Raycoms** [comment]
They handle the breaking or ore to scraps nowadays.
