### ISSUE TITLE
[BUG] Recipe Loops in Dyer with Colored Wool

### ISSUE THREAD

**Issue by anonymous563** [ldtteam/minecolonies#8306]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

minecolonies-1.18.1-1.0.667-ALPHA

### Structurize Version

structurize-1.18.1-1.0.387-RELEASE

### Related Mods and their Versions

1. Forge 39.0.5
2. DO 1.18.1-1.0.49-ALPHA
3. Multi-Piston 1.18-1.2.2-ALPHA
4. BlockUI 1.18.2-0.0.47-ALPHA
5. Copper Equipment
6. Fast leaf decay, JEI, Journeymap, some FPS-increasers that Sam wrote, Enchantment Descriptions, Medieval Music, The One Probe, Time Control, Vanilla+ Tools (all from the 1.18.1 modpack)

### Current Behavior

When my colonists request a colored wool, the dyer will make requests that loop from e.g. yellow wool --> white wool + yellow dye --> black wool wool + white dye --> white wool + black dye.
The dyer knows the recipe for yellow wool and yellow dye, but does not have any other recipes related to wool or dyes.
The "recipes" request steps all come from the dyer.
https://discord.com/channels/139070364159311872/915411448342118441/969806648359125022

![image](https://user-images.githubusercontent.com/34487065/166089765-cdeb9a4b-ef6a-44f8-b67f-abd217b77a67.png)
![image](https://user-images.githubusercontent.com/34487065/166089770-9ad5f070-fa15-4153-896d-32b73dd6b10e.png)
![image](https://user-images.githubusercontent.com/34487065/166089776-20de6729-f7e3-4d2c-be02-d08abbd14d63.png)
![image](https://user-images.githubusercontent.com/34487065/166089778-3f2652e9-8950-4d42-9f78-a5957d560e17.png)

### Expected Behavior

I expect the dyer to request white wool and for that to be the end of the request chain since they shouldn't know recipes to make white wool.

### Reproduction Steps

1. Make new colony (creative mode).
2. Creatively paste in a dyer (at level 5). Assign a colonist to work as the dyer.
3. Teach dyer recipe for yellow wool and yellow dye from dandelion.
4. Place a postbox somewhere. Request 10 yellow wool at the postbox.

### Logs

pastebin.com/WillIncludeLater

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
do you have white wool available?

**Comment by anonymous563** [comment]
The steps to reproduce might not be right. Here are some screenshots from my actual game. I had put a min stock of white wool in the warehouse.

![image](https://user-images.githubusercontent.com/34487065/166107044-a71ec088-5099-456c-b3d8-2af0997d513c.png)
![image](https://user-images.githubusercontent.com/34487065/166107062-8e850abc-24f4-4f0c-95f7-e1ba9d4b603d.png)

Or maybe I'm derping and misreading something.

**Comment by Raycoms** [comment]
If resources are not available, it is possible that it loops up to one time, but not further and will then be stuck at that position.

If resources are available it should not loop.

**Comment by anonymous563** [comment]
Part of a request for black wool for banners made by a colonist:
![image](https://user-images.githubusercontent.com/34487065/166107141-e83c31b5-e8c1-4466-9334-68d9a23322e3.png)
![image](https://user-images.githubusercontent.com/34487065/166107148-484741ab-0d22-429e-9376-f909096bf19c.png)

I can't reliably reproduce this, but it only seems to happen with the dyer, but it takes so long to find this situation that I'm not sure what steps are required.

Why does it loop in the first place?

**Comment by Raycoms** [comment]
Well, you want black wool, you don't have black wool so it tries to craft black wool with the help of white wool, but you don't have white wool, so it tries to color a different wool white first, etc.

**Comment by Raycoms** [comment]
There is no way to solve this without simulating the entire tree, for now this is intended behaviour.

**Comment by uecasm** [comment]
It would be nice if the "create white wool" recipe disabled itself if there was not sufficient coloured wool to immediately satisfy the request (such that it then can't loop back to trying to create more coloured wool).  I believe (from glancing at it) that it does already check the warehouse when evaluating that recipe to choose which colour to turn white, so this shouldn't be super complicated.

**Comment by uecasm** [comment]
Hmm.  I had a bit of a go at this and it's a little trickier than first thought.  It would be doable if `getFirstRecipe` were passed the target count, but that isn't currently the case.  And implementing the check only in `getFirstFulfillableRecipe` does not appear to be sufficient to stop it attempting to use the "wrong" recipe.  I'm not really sure why both of these need to exist.
