### ISSUE TITLE
[BUG] <title>Couriers stop working 

### ISSUE THREAD

**Issue by ghost** [ldtteam/minecolonies#8308]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.16

### MineColonies Version

664

### Structurize Version

392

### Related Mods and their Versions

Forge Version: 36.2.34

### Current Behavior

 Since a few days (irl) i have the problem that my couriers stop working every now and than. They just stay in their assigned warehouse until they go to bed. All the common fixes (punching them, restarting, even recruiting an other person) didnt work. I have no problems with any other job. The bug hast started to appear in the previous release version i think
Resetting the request system helps for only a couple of minutes, then they go back idling in the warehouse

### Expected Behavior

To not idle and do their job 

### Reproduction Steps

it just happens after a few minutes for me nothing out of the regular 

### Logs

https://gist.github.com/MockingSniper/13e1f5b723b13cef96a22055eef4f035

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
do you have multiple warehouses or so?

**Comment by ghost** [comment]
Yes 2 warehouses and 3 curriers 
All of them stop working after a short time. Resetting only helps for a few minutes

**Comment by Raycoms** [comment]
I'll look into it.
