### ISSUE TITLE
Refined storage texture overlapping on corner under construction block

### ISSUE THREAD

**Issue by ProjectGR** [ldtteam/minecolonies#831]
### Minecolonies version

version 1.11-0.6.3360

### Expected behavior

- Corner tape texture being normal

### Actual behaviour

- Corner tape texture being overlapped by refined storage

### Steps to reproduce the problem

1. Have both mods installed on 1.11.2 
2. Profit

![2017-04-19_20 57 17](https://cloud.githubusercontent.com/assets/16193803/25194664/d6a1f978-2543-11e7-822c-b341c6029eb0.png)

I also suspect the same mod could be conflicting with minecolonies and it might be the reason why the warehouse is crashing the game as reported at #758

**Comment by marchermans** [comment]
Are we using a TileEntitySpecialRenderer?

**Comment by Raycoms** [comment]
No I think we're using normal jsons for this here.

2017-04-19 15:43 GMT-03:00 Marc Hermans <notifications@github.com>:

**Comment by marvin-bitterlich** [comment]
@nojo121

**Comment by Asherslab** [comment]
New Construction tape fixed this [closed]
