### ISSUE TITLE
[BUG] Sawmill takes Dyers job

### ISSUE THREAD

**Issue by Unerhalla** [ldtteam/minecolonies#8312]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.16

### MineColonies Version

1.0.664

### Structurize Version

1.0.392

### Current Behavior

Sawmill is able to produce coloured shingles, it should be only the job of the dyer.

Also ingame recipe says that coloured Terracotta can be crafted by Stonemason (unable to teach it), wich is correctly not possible.  

### Expected Behavior

Colourizing should only be done by Dyer. 

### Reproduction Steps

Teach the reipe to the Sawmill/Carpenter

### Logs

-

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
That's intended atm. There is an overlap there
