### ISSUE TITLE
Getting snapshot of warehouse Stock crashes game

### ISSUE THREAD

**Issue by SerranoPancake** [ldtteam/minecolonies#8313]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.0.670-ALPHA

### Structurize Version

1.0.389-RELEASE

### Related Mods and their Versions

1. Forge Version: 40.1.0
2. Domum Version: 1.0.50-ALPHA
3. BlockUI Version: 0.0.47-ALPHA

### Current Behavior

When shift + right clicking on the warehouse with resource scroll to get snapshot of inventory, game crashes

### Expected Behavior

When shift + right clicking on the warehouse with resource scroll to get snapshot of inventory, resource scroll shows available inventory of items requested.

### Reproduction Steps

1. Create resource scroll.
2. Assign scroll to builder.
3. Assign work order to builder.
4. Wait for needed resources to show on scroll.
5. Shift + right click warehouse hut block

### Logs

https://gist.github.com/SerranoPancake/5c432411756546194d3c6a9a7d90122c

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
Can you list what resources the builders hut needs? By the looks it's errored on the fact that the builder is requesting the same item twice.

**Comment by SerranoPancake** [comment]
He's building the Cavern MegaHall Apiary. Requesting 8 Poppy, 21 Framed Brown Staind Glass, and 2 Brown Stained Glass Door.
![image](https://user-images.githubusercontent.com/20136617/166121618-8a09f7cf-7dc5-4d29-b37e-ab5d75fa9141.png)

**Comment by SerranoPancake** [comment]
Here is the list from the resource scroll.
![image](https://user-images.githubusercontent.com/20136617/166121783-b2607047-5b59-41f1-97b2-f91c3b1f9d3c.png)

**Comment by SerranoPancake** [comment]
It does appear to be only for this work order. I am still able to get a snapshot using other builders' resource scrolls.

**Comment by Thodor12** [comment]
Turns out it's related to blocks that utilize an identical item but have extended NBT data, mainly applies to blocks from DO, working on a fix
