### ISSUE TITLE
[BUG] Multiple problems with Pathing System

### ISSUE THREAD

**Issue by HexatomicRing** [ldtteam/minecolonies#8315]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.0.662

### Structurize Version

1.0.389

### Related Mods and their Versions

1. Forge version: 40.0.44
2. Block UI version: 0.0.47
3. Domum Ornamentum version: 1.0.50

### Current Behavior

I played this mod for some weeks. It is very fantastic ,but I encountered some problems with pathing system in succession.

The first one is that citizens and raiders cannot avoid doors when pathing. That is to say, maybe there is another way to get to destination just a few blocks farther, but citizens and raiders will still try the shortest way, spending a lot of time opening or breaking the door. Doors might need to add a cost to pathing system.

The second one is citizens and raiders cannot recognize and evade campfires. Citizens often get hurt when entering tavern, and raiders may even die while preparing, just for standing on a campfire. Campfires shoulb be regarded as fire and lava.

The third, trapdoors are possibly regarded as passable blocks, but they can block path under some states.(shown as below) To deal with this, the state and direction of the trap door should be taken into account.
![2022-04-30_23 05 00](https://user-images.githubusercontent.com/54496918/166134529-cfbea320-550b-4ca0-8eaa-e64c8af382a9.png)

The forth one, when multiple citizens or raiders trapped in a hole which is 2 blocks deep, they cannot get out by placing ladders or blocks.

Last one, ranged raiders often hurt themselves, especially amazon raiders, who usually die from friends' injuries. Maybe they should check whether there is friendly entities on the raycast, or just take no damage from friendly entities.

An additional request: If it's possible to set a Rallying Banner into defend mode that guards will stay around the point, not be too far away.
 

### Expected Behavior

-

### Reproduction Steps

-

### Logs

-

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
In 1.18 a new decorative-only kind of trapdoor has been added, but it will take time for styles to switch to using them.

**Comment by Raycoms** [comment]
Doors and holes are on purpose. Same for friendly fire for raiders for now. Trapdoors and campfires I'll look into again
