### ISSUE TITLE
[BUG] residents split and created illusions when he works

### ISSUE THREAD

**Issue by Fantasycho** [ldtteam/minecolonies#8316]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.0.635-BETA

### Structurize Version

1.0.378-BETA

### Related Mods and their Versions

1.Forge: 39.1.2
2.BlockUI: 0.0.47-ALPHA
3.domum_ornamentum: 1.0.39-ALPHA-universal

### Current Behavior

![image](https://user-images.githubusercontent.com/49608407/166137716-d55d3d8e-1f41-4565-8441-bc10752dd530.png)
Resident always split when he works. And when I don't play with my friends, it wont be happened.

### Expected Behavior

No illusions would appear at all.

### Reproduction Steps

Play with friends by using LAN, Singleplayer game wont be able to reveal the bugs.

### Logs

https://gist.github.com/Fantasycho/3ebb48ca4d3ab73e63b2a396c7335ccc

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
This is a vanilla bug. Restarting the world should solve it

**Comment by Fantasycho** [comment]
> This is a vanilla bug. Restarting the world should solve it

Hope it can be solved at future version, it's so complicated to restart the game frequently when playing LAN game. Reconnection would waste lots of time.

**Comment by MotionlessTrain** [comment]
That is up to Mojang, to solve that in an upcoming minecraft version
