### ISSUE TITLE
[BUG] Researches can not consume tools that have removed enchantments

### ISSUE THREAD

**Issue by HexatomicRing** [ldtteam/minecolonies#8317]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.0.662

### Structurize Version

1.0.379

### Related Mods and their Versions

    Forge version: 40.0.44
    Block UI version: 0.0.47
    Domum Ornamentum version: 1.0.50

### Current Behavior

I have met the requirement of research Builder Modes (all the requirements turned to blue), and there's only one research in progress in my lv.3 university, but I cannot research it. I have two diamond axes in my inventory, both with full durability, bought from villagers and removed its enchantment on a grind stone. But the research is still locked, nor could I press it.
However, after I enter the command /give hexatomic_ring minecraft:diamond_axe , I can research it.
![2022-05-01_16 26 00](https://user-images.githubusercontent.com/54496918/166138278-39a4e0e2-3bc1-464b-9b5f-1682cfbc88f9.png)

### Expected Behavior

-

### Reproduction Steps

-

### Logs

-

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
That means the tool has some special NBT still which doesn';t make it recognizable. There is nothing we can do at this time.
