### ISSUE TITLE
Hut gui issue[BUG] <title>

### ISSUE THREAD

**Issue by Pelkenator** [ldtteam/minecolonies#8319]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.18.2

### Structurize Version

1.18.2

### Current Behavior

when i click on a hut to add a crafting recipe or anything it doesn't give me a list of items. the item has to be in my inventory. some of the huts don't work at all like the composter hut.

### Expected Behavior

Usually the huts gives you a list of items from JEI or something but it only shows air.

### Reproduction Steps

no idea whats causing the issue 

### Logs

.

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Pelkenator** [comment]
![image](https://user-images.githubusercontent.com/96737577/166167074-1074e0fd-2708-494b-a04e-6cec76fddc65.png)

**Comment by MotionlessTrain** [comment]
Please fill in the mod versions, not the minecraft versions (There are hundreds of versions released for just 1.18.2)

Try to go into singleplayer first, then join the server again

**Comment by Pelkenator** [comment]
single player multiplayer fixes thanks
