### ISSUE TITLE
Workers are too picky about tools

### ISSUE THREAD

**Issue by PenguinMan98** [ldtteam/minecolonies#832]
### Minecolonies version

version 1.11-0.6.3360

### Expected behavior

- When a worker asks for a shovel, they should ask for a shovel of _minimum_ strength wood or gold and accept any shovel that meets or exceeds their need.

### Actual behaviour

- Workers ask for a shovel that is a _maximum_ grade of wood or gold.  If you give them stone or iron shovels, then they walk to the build site with it, stop, then return complaining that they don't have the right tool.

**Comment by marvin-bitterlich** [comment]
That is a feature, level up your buildings to use better tools.

**Comment by PenguinMan98** [comment]
Reeeely.  OK then. Thanks!  Please consider putting a note to this effect somewhere. I'm sure I'm not the only player that might be confused by this.

Maybe have the builder return with the stone shovel and instead of saying 'I need a wood shovel' he can say 'I don't have enough experience to use this shovel. Please give me a wooden one.'

**Comment by sandalle** [comment]
This is still an issue. Finally found https://www.reddit.com/r/Minecolonies/comments/dxhu6e/help_starting_minecolonies/ and this ticket, then gave my worker a _wooden_ shovel, even though the text (_twice_!) said that anything from wood to gold would suffice, and he started building the Builder's Hut. In-game text should at least tell us what we need and not be misleading. I had given them stone tools to start.

https://wiki.minecolonies.ldtteam.com/source/misc/troubleshooting mentions
> Do they have tools of the correct [level](https://wiki.minecolonies.ldtteam.com/source/systems/worker)?

With the level section for tools says this:
> 0 | Wood or Gold + 0 enchantments

Which is more clear than the in-game text which says this:
> Tool of class: Shovel with minimal level: Wood or Gold and with maximal level: Wood or Gold

Stone is between wood and gold so meets both the "minimum" and "maximum" requirements as stated. Perhaps the in-game text could be made to match the wiki text? Or more clear that those aren't minimum and maximum levels, but rather the _only_ levels allowed.

**Comment by uecasm** [comment]
Stone is not between wood and gold.  And if you look at the details of the request in-game, it will flash between all the acceptable items (so that you can see that it is not showing stone tools).

**Comment by Nekkowe** [comment]
Oh god, that was INTENTIONAL? Why is every part of this mod engineered to be as tedious as possible? Even with all the wood in the world, builders can't make their own stairs and fences, foresters and miners can't make their own wodden tools in a pinch, you can't even give them anything more durable and that's supposed to be a **feature!?**

**Comment by uecasm** [comment]
Please don't necropost on 6 year old closed issues.  If you want to discuss things, the Discord server is a good place to do so.

**Comment by Nekkowe** [comment]
> Please don't necropost on 6 year old closed issues.   

That's fair, I'm sorry.

> If you want to discuss things, the Discord server is a good place to do so.  

I was invested enough to give this mod a couple hours' worth of trying it out, despite its completely horrific starting experience, because I was really hoping for it to be good. The concept is really nice! But I'm _**definitely**_ not invested enough to come hang out in your little club treehouse.
