### ISSUE TITLE
[BUG] The Minium Stock has bugs with some items

### ISSUE THREAD

**Issue by HexatomicRing** [ldtteam/minecolonies#8320]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.0.673

### Structurize Version

1.0.389

### Related Mods and their Versions

Forge 40.1.0
multi-piston-1.18.2-1.2.3-ALPHA
blockui-1.18.2-0.0.47-ALPHA
domum_ornamentum-1.18.2-1.0.41-ALPHA-universal

### Current Behavior

As you can see, I just added a minium stock of Oak Wood, Stripped Oak Wood and Stripped Oak Log of quantity from 64 to 256 to my warehouse. Then my forester started to craft all my Oak Logs into these items.
The minium stock works correctly for other items.
![2022-05-02_12 18 19](https://user-images.githubusercontent.com/54496918/166184306-f9441409-d8b5-48f8-8751-7d4f3a1c7f6e.png)
![2022-05-02_12 18 32](https://user-images.githubusercontent.com/54496918/166184371-66ae2f6f-ba3e-407c-a2ff-1429aa5b9013.png)
![2022-05-02_12 18 43](https://user-images.githubusercontent.com/54496918/166184379-8b360780-4f56-46f0-8128-0ad986f6825a.png)

### Expected Behavior

-

### Reproduction Steps

-

### Logs

-

**Comment by Raycoms** [comment]
Minimum stock is in stacks, you set it to 64 stacks of stripped oak xD
