### ISSUE TITLE
[BUG] Florist hut ignoring need for a tool for ferns/tall grass

### ISSUE THREAD

**Issue by Arronicus** [ldtteam/minecolonies#8322]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.18.2-1.0.673

### Structurize Version

1.18.2-1.0.389

### Related Mods and their Versions

Torchmaster 18.1.0
JEI 9.5.2.135
Flywheel 1.18-0.6.2 (Create dependency)
Immersive Engineering 1.18.2-8.0.1-147
patchouli 1.18.2-67
Multi-Piston 1.18.2-1.2.3
Domum 1.18.2-1.0.41
Ui Library 1.18.2-0.0.47
Little Contraptions 1.18.2.0-beta.2
Gauges & Switches 1.2.16-b1
Little Logistics 1.2.3
Create 0.4.1

### Current Behavior

When attempting to harvest ferns and tall ferns, the florist now just punches the fern with bare hands, or random inventory items (including seeds), breaking the fern without harvesting the result.

### Expected Behavior

Requesting shears, then using them to harvest the fern

### Reproduction Steps

Have a florist grow ferns and attempt to harvest them

### Logs

null

### Anything else?

If logs are actually helpful for this, let me know which ones and I'll get them uploaded here

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
I fixed this

**Comment by Talyda** [comment]
I think something went wrong with the build maybe then Ray?
They are on the latest one available

**Comment by Raycoms** [comment]
Hadn't pushed the 1.18.2 port yet.
