### ISSUE TITLE
Issue: Archer request a bow, but the UI does not have the bow icon

### ISSUE THREAD

**Issue by kedamono** [ldtteam/minecolonies#8325]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.18.1-1.0.675-ALPHA

### Structurize Version

1.18.1-1.0.387-RELEASE

### Related Mods and their Versions

Forge: 39.0.59
Donum Ornamentum: 1.18.1-1.0.49-ALPHA
BlockUI: 1.18.2-0.0.47-ALPHA

### Current Behavior

The Archer is requesting a bow, and the Request UI does not have the bow icon.
The Archer has a bow in their inventory, and the Fletcher has the bow recipe in their recipe list.

I tried removing the existing bow from the Archer's inventory, close the inventory, and then put back the bow into their inventory, but that did not resolve the issue.

### Expected Behavior

The bow request has the correct item icon and the request is fulfilled by the Fletcher.

### Reproduction Steps

1. Install Minecolonies 1.18.1-1.0.675-ALPHA.
2. Make sure you have a guard job of type Archer.
3. Give the Archer a bow.
4. The Archer asks for a bow, but the request does not have the correct item icon
![2022-05-02_09 19 44](https://user-images.githubusercontent.com/23420636/166331679-7d499e24-5049-44ef-9b61-f94a4a59e0ec.jpeg)
![2022-05-02_09 19 53](https://user-images.githubusercontent.com/23420636/166331697-0f48c027-a033-4f47-8256-5323425eded5.jpeg)
![2022-05-02_09 19 57](https://user-images.githubusercontent.com/23420636/166331708-7eb19721-a357-44f2-8a6a-395167464da7.jpeg)

.

### Logs

https://gist.github.com/kedamono/1b853262ff90c10fbb4e30b3a5d01364

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
Just adding to this someone else reported it yesterday here:
https://discord.com/channels/139070364159311872/915411448342118441/970634065675956297
But due to some blahblah or another, they couldn't be bothered reporting it on github =P But same minecol version

**Comment by Sandriell** [comment]
Experiencing this issue on 1.16.5-1.0.688 as well. The request is visually broken as shown above and the archer refuses to accept any bows.
