### ISSUE TITLE
new mod update breaks most buildings

### ISSUE THREAD

**Issue by adam110902** [ldtteam/minecolonies#8329]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.16

### MineColonies Version

minecolonies-1.16.5-1.0.682-ALPHA

### Structurize Version

1.0.392-RELEASE

### Current Behavior

when updating minecolonies to any version between 1.0.677 and 1.0.682 most buildings break, when i interact witha broken building it gives a "the block is missing it's respective building" message
any new building placed is broken
restarting doesn't help
reverting to older version fixes everything

### Expected Behavior

everything works normally after updating with improvements  caused by new version

### Reproduction Steps

1:have a village on minecolonies 1.0.664
2:update to one of broken versions
3: now some of the  placed buildings are broken, along with any buildings placed after update

### Logs

https://gist.github.com/adam110902/bb92aefaa37bef5aa0ef6fb84836301d

### Anything else?

https://gist.github.com/adam110902/0605e6c3f7fbcef3625add78d1dae09a
log for the same save on the working version after reverting

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
hotfix pushed
