### ISSUE TITLE
Colony forgot its owner during upgrade

### ISSUE THREAD

**Issue by PenguinMan98** [ldtteam/minecolonies#833]
### Minecolonies version

version 1.11-0.6.3360

This is more of a support request.  We upgraded our server from Colonial Expansion 1.9 to 2.0. When we did this, our mine colonies forgot who their owners were.  I'm surrounded by my stuff but I can't control it or even go inside anymore.  Is it possible to correct this without restarting the server or without abandoning my colony and starting a new one?

**Comment by Raycoms** [comment]
okay did you try /mc colony refresh yourColonyId

2017-04-19 17:20 GMT-03:00 Joe <notifications@github.com>:

**Comment by PenguinMan98** [comment]
If my colony were named 'The Rookery', then how would I find its 'yourColonyId' ?

**Comment by Raycoms** [comment]
do /mc colonies list    to find it in the list.

2017-04-19 17:44 GMT-03:00 Joe <notifications@github.com>:

**Comment by cympaul90** [comment]
I am the one running the server that this problem is occurring on and the refresh command did not work. I found the colony ID with the list command, ID=1, and ran the update command but it could not complete it.
https://cdn.discordapp.com/attachments/190636923369422848/304481081040699394/unknown.png
https://cdn.discordapp.com/attachments/190636923369422848/304480964719935489/unknown.png

**Comment by Raycoms** [comment]
run it ingame in the chat

2017-04-20 2:06 GMT-03:00 Paul <notifications@github.com>:

**Comment by halacon** [comment]
To fix this issue (or at least work around it) we have found that if you log into the server, then turn the server off, boot it back up, then log back in, it should fix the problem.  This happens to us every time I update my server to the new version of FTB Beyond.  You have to do this to every player that owns a colony so it's a boon if, once you get the server up and running have everyone that owns a colony log in at the same time.  As with you, the commands weren't working.  If THAT doesn't help, (we had a guy this didn't fix) what I did was replace the new minecolonies.dat file with the one from the old server.  It forces it to remake a new .dat file and that seemed to work.

**Comment by marvin-bitterlich** [comment]
closing for now
