### ISSUE TITLE
four-sided shingles not appearing in architect's cutter

### ISSUE THREAD

**Issue by jmtrichey** [ldtteam/minecolonies#8331]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

All The Mods 7

### Structurize Version

All The Mods 7

### Current Behavior

Trying to craft a specific part in architect's cutter and the part doesn't show up regardless of items used or configuration.
![Capture](https://user-images.githubusercontent.com/81836336/166605969-264ceca5-a93a-4029-bfb3-40e859bf4cc7.PNG)
![Capture2](https://user-images.githubusercontent.com/81836336/166605970-161f6f2e-424b-4342-b01e-01e397eefc89.PNG)

### Expected Behavior

I expected to be able to find the resulting item I needed

### Reproduction Steps

1. Put any configuration of materials into Architect's cutter
2. search for the steepled shingles (they are just called <name of material> extra shingles)

### Logs

I don't have access to log files in the server I'm playing on

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Moobien** [comment]
shingle slabs are a 3 input item, not a 2 input item.

**Comment by jmtrichey** [comment]
That would explain it, thanks so much
