### ISSUE TITLE
[1.16.5] [Server Crash] Opening any Hut Block Inventory Causes Crash

### ISSUE THREAD

**Issue by Sandriell** [ldtteam/minecolonies#8332]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.16

### MineColonies Version

1.16.5-1.0.688

### Structurize Version

1.16.5-1.0.392-RELEASE

### Related Mods and their Versions

https://gist.github.com/Sandriell/b5e93fe6822f3fc2fd8670f3f35dbfa8

### Current Behavior

Attempting to open the hut block inventory of any hut (tested with Sifter and Sawmill), either through the UI or by shift-right-click on it results in my dedicated server crashing.

### Expected Behavior

Inventory opens and doesn't crash.

### Reproduction Steps

Simply attempt to open the hut block inventory.

### Logs

https://gist.github.com/Sandriell/4aa276dfdbadc6c5c558bc449efa55c2

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
fix pushed
