### ISSUE TITLE
JEI 9.7 upwards not working with MineColonies

### ISSUE THREAD

**Issue by Nyuraa** [ldtteam/minecolonies#8333]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.0.689-ALPHA

### Structurize Version

1.0.389-RELEASE

### Related Mods and their Versions

Forge Version 40.1.10
JEI Version 9.7.0.194 down to 9.7.180

### Current Behavior

The Tabs for the Hut in which Recipes are available doesn´t show up and the +Button function doesn´t appear when using JEI in the add Recipe function.

### Expected Behavior

JEI should show Tabs for the Hut Recipes
+Button should show up in the Add Recipe function

### Reproduction Steps

1. Open up JEI
2. Choose any Recipe a Hut should be able to work.
3. Example Spruce Planks - Spruce Stairs
4. No Tab for the Sawmill available
5. When in the Add Recipe funtion of the Hut opening the Recipe
6. No +Button available

### Logs

https://gist.github.com/Nyuraa/97283e16fb9ecd5aa7cd2450fee579ee

### Anything else?

Cropped version of the log with an Minecolonies related Error: https://gist.github.com/Nyuraa/f7806f94142f315ea4a82bcd4f45c43c

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
Adding to this, cos I did some testing - I'm using forge 40.0.32, JEI 9.7.0.194, blockui 0.0.47, DO 1.0.50, multipiston 1.2.3 same minecol and structurize as above and seeing same as above

Adding my latest.log as well in case it helps
https://gist.github.com/Talyda/b332bd82dd98f71884330aaee0af7e3c

**Comment by uecasm** [comment]
This is not actually related to JEI version at all, it's just a bug that only appears in MineColonies 1.18.2 due to some differences between that and 1.18.1.

Downgrading temporarily to MineColonies 1.18.2-1.0.673-ALPHA should work around it until this fix is merged.
