### ISSUE TITLE
Quarries

### ISSUE THREAD

**Issue by Rodgarson** [ldtteam/minecolonies#8336]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.0.673

### Structurize Version

1.0.389-RELEASE 

### Related Mods and their Versions

ATM7 0.3.19

### Current Behavior

Quarry worker breaks framed cobblestone framework when digging out medium quarry, thus leaving no framework and floating torches; or worker repeatedly breaks and replaces outer framed cobble and does nothing else.

### Expected Behavior

Expected to build a quarry.

### Reproduction Steps

Set up mine then quarry before hiring quarrier and assigning to quarry.

### Logs

Today

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Which style, screenshots?

**Comment by Rodgarson** [comment]
> 
![2022-05-05_20 11 05](https://user-images.githubusercontent.com/104944842/167050870-4e6441af-0261-41f2-a334-c37c63e5f8ca.png)
Wooden style, and this is after repairing

**Comment by Raycoms** [comment]
Oh, I just noticed how old your version is, this is long fixed
