### ISSUE TITLE
FakePlayer cannot interact with the environment within Colony borders

### ISSUE THREAD

**Issue by Rhodizzle** [ldtteam/minecolonies#834]
I've read about this issue on several other sites but searching through the issues backlog here on Github did not result in an issue that was similar. We're using MineColonies in a modified version of FTB Beyond for 1.10.2.

### Minecolonies version

version 0.6.69

### Expected behavior

- When machines and devices that implement FakePlayer from Forge (examples: EnderIO Farming Station or Mechanical User from ExtraUtilities2 are placed within the boundaries of the Colony, they are able to interact with the environment.

### Actual behaviour

- These devices are unable to interact with the environment as normal. Moving them outside of the colony boundary allows them to work as normal.

### Steps to reproduce the problem

1. Build a Colony
2. Attempt to implement a FakePlayer block such as those mentioned above within the Colony border.
3. ...
4. (lack of) Profit

**Comment by Raycoms** [comment]
I am sure we already have 2-3 issues of this around here.
They implement fakePlayer but they don't give it the playerUUID like forge intends them to do so.
Had a discussion with lex about that already.

**Comment by shammon5** [comment]
I'm likewise having this problem. Was a workaround eventually added?

**Comment by marchermans** [comment]
It is technically possible to add fake player users as members of your colony.

**Comment by shammon5** [comment]
Hi, thanks for the reply! How would i go about adding a fake player in order to be able to interact with these mods? Sorry, I'm a complete noob, haha. :P

**Comment by marchermans** [comment]
@Raycoms Was it something like [<fakeplayername>] as username?
@shammon5 Their is an option in the townhall to see all interactions made by any player also fake players. That gives you the fakeplayer name you can use to add to the Memberlist and then modify its permissions. Contact our discord for more information in the #help channel.

**Comment by Raycoms** [comment]
After townhall level 1 you can see an event log of all not permitted events, you can add the fakeplayers from there.

**Comment by shammon5** [comment]
Ah, ok thank you! :)
