### ISSUE TITLE
Bugs about Nether Miner

### ISSUE THREAD

**Issue by shenzhencz** [ldtteam/minecolonies#8340]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.0.510-ALPHA

### Structurize Version

1.0.353-ALPHA

### Related Mods and their Versions

1.40.1.0
2.0.0.47-alpha
2,1.0.50-alpha

### Current Behavior

1,When the nether miner get into nether,I can't find him in overworld or nether
2,When he died in nether,I can't find his grave,and under taker do nothing,the coordinate the game shown is the townhall

### Expected Behavior

1,able to find the nether miners
2,able to summon graves when they died

### Reproduction Steps

1,make a person to be a nether miner
2,when he get into nether ,the bug 1 happened
3,when he died ,the second bug happened

### Logs

Because of the network,I can't upload the log file

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by shenzhencz** [comment]
by the way,the nether miner must be dead in nether,i don't know if it is one of the bugs

**Comment by MotionlessTrain** [comment]
This is both intended. They cannot actually go into the nether, so they hide somewhere in the building. As the undertaker cannot (and doesn't want to) go in to the nether either, no grave should be produced when they die

**Comment by Thodor12** [comment]
Also FYI don't tick the checkboxes because you think they're mandatory or something, 510 is not the latest alpha at the time of the issue. Thanks!

**Comment by Raycoms** [comment]
Both intended
