### ISSUE TITLE
Builder cannot use Shears when not given directly

### ISSUE THREAD

**Issue by Nyuraa** [ldtteam/minecolonies#8343]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.0.699-ALPHA

### Structurize Version

1.0.389-RELEASE.jar

### Related Mods and their Versions

1. Forge 40.1.15
2. DO 1.0.50-ALPHA
3. multi-piston 1.2.3-ALPHA
4. blockui 0.0.47-ALPHA
5. jei 9.7.0.194

### Current Behavior

1-Builder request Shears
2-takes Shears from Hut Inventory
3-puts Shears back into Hut Inventory
4-goes to Construction Site
5-cannot break Grass
6-goes back to Hut
starts over at 2

can be circumvented then given Shears directly when on its way to Construction Site, then he breaks the Grass as intended.

### Expected Behavior

takes Shears
keeps it
breaks Grass

### Reproduction Steps

1. Give Builder Build Request in which he has to break Grass Blocks
2. Fulfill the Shears Request
3. then Bug happens

### Logs

https://gist.github.com/Nyuraa/94fdcd7cec0fb6a2bc2174b0052dd29e

### Anything else?

Tested on a Test Instance with only Mods mentioned above

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
fix pushed
