### ISSUE TITLE
Builder requests invisible shears than building his own lvl0 hut

### ISSUE THREAD

**Issue by Nyuraa** [ldtteam/minecolonies#8348]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.0.711-ALPHA

### Structurize Version

1.0.389-RELEASE

### Current Behavior

The Builder requests a invisible Shear when his building is lvl0
when given to another builder with a lvl1 hut it works correctly

### Expected Behavior

Builder requests correct Shears

### Reproduction Steps

1. place a new builders hut
2. let the builder of this hut build it
3. he will request an invisible shear

### Logs

https://gist.github.com/Nyuraa/6b5cb7ec73a5c40a8ad53544987009d2

### Anything else?

![2022-05-06_21 42 48](https://user-images.githubusercontent.com/104888046/167208373-aa006e63-31d5-4c72-b393-52d8226de5a5.png)
![2022-05-06_21 43 53](https://user-images.githubusercontent.com/104888046/167208382-cedb86ab-edeb-4312-b0ae-8739769e5660.png)

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ArkenorOakshadow** [comment]
This shears bug also appears to be affecting miners, when they come up against something like Quark's Cave Roots.
