### ISSUE TITLE
Scarecrow (field) doesn't work

### ISSUE THREAD

**Issue by PenguinMan98** [ldtteam/minecolonies#835]
### Minecolonies version

version 1.11-0.6.3360

### Expected behavior

- I built the farmer hut. He announces that he needs fields before he can do anything. I craft the field (scarecrow) and place it somewhere. He should get to work.  If I mis-place the field, I should be able to move it.

### Actual behaviour

- I create the field (scarecrow) and place it.  The farmer does nothing and continues asking for a field.  When I try to pick up the scarecrow and move it, it is unbreakable.  Placing 4 scarecrows had no effect and they are all unbreakable.

**Comment by marvin-bitterlich** [comment]
can you check if this is the same as #838

**Comment by PenguinMan98** [comment]
The server I found the issue on is no longer being hosted. I'll see if I can reproduce it in single player if you don't mind waiting.

**Comment by Raycoms** [comment]
Sure, go for it.

2017-04-24 14:20 GMT-03:00 Joe <notifications@github.com>:

**Comment by xavierh** [comment]
Any news about this ?

**Comment by Wissi** [comment]
I guess it was an isolated permissions config "Server Issue". No response since 14 days ago. Issue should be closed?
