### ISSUE TITLE
Miner requests Shears, but will not use them, resulting in endless loop.

### ISSUE THREAD

**Issue by ArkenorOakshadow** [ldtteam/minecolonies#8356]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.16

### MineColonies Version

1.0.716-ALPHA

### Structurize Version

1.0.392-RELEASE

### Related Mods and their Versions

Forge 36.2.34

Cave Roots from Quark, though I suspect any similar vegetation will get the same response.

### Current Behavior

When faced with Cave Roots, from the Quark mod, and presumably vines or anything similar, the miner requests shears, picks them up, puts them down, goes back into the mine to where she wants to dig, and then heads back out to pick up and put down the shears again.

Removing the cave roots fixes her until she comes across another.

### Expected Behavior

I expect her to hit the vines with her axe. Or keep hold of the shears long enough to use them.

### Reproduction Steps

I would expect that placing cave roots where your miner is going to dig will stop them in their tracks. If you're not using Quark then vines will probably suffice.

### Logs

https://gist.githubusercontent.com/ArkenorOakshadow/dc07a2ebb5f26577df3faf971682bd29/raw/39ff776ec10f778dd1acff5cd9b90f36f2e52d03/gistfile1.txt

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
This is also reproducible with cobwebs, I noticed. That gave an issue when my miner ran into an abandoned mineshaft
