### ISSUE TITLE
Plantation worker hangs on manufacturing items that depend on plantation output.

### ISSUE THREAD

**Issue by sgallaty** [ldtteam/minecolonies#8358]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.16

### MineColonies Version

minecolonies-1.16.5-1.0.709-ALPHA

### Structurize Version

structurize-1.16.5-1.0.392-RELEASE

### Related Mods and their Versions

There are no mod interactions for this issue.

### Current Behavior

Plantation worker stops and waits for paper to make books.

### Expected Behavior

Plantation worker continues to gather sugarcane and makes paper when there is no paper available.

### Reproduction Steps

Run plantation.
Have a demand for books (warehouse will suffice)
Remove sugarcane from inventories.

### Logs

No log information material to this issue.

### Anything else?

raycoms told me to post this issue after I discussed it with him.

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by sgallaty** [comment]
You can verify that it is the pending book or paper manufactury that is holding up the hut by canceling the book demand and observing the hut worker going back to harvesting sugarcane.

**Comment by marchermans** [comment]
This is a complicated one to solve.

At this moment the request system does not consider resources that the worker produces as available to him for crafting (for obvious complexity reasons). 

To support that we would need to create request types for each production worker and implement that accordingly in the API, similar to how the DMan handles delivery requests internally. Additionally, this would need to be a low priority option, to prevent it from blocking the queue.

That said it is not impossible to do, but at least very time consuming to implement. @Raycoms What do you think?

**Comment by MotionlessTrain** [comment]
The planter has an additional complexity, as they require sugarcane for themselves as well, for replanting purposes.
This is not always going right: I noticed they sometimes use their own stock for crafting purposes as well, and have trouble replanting the sugarcane afterwards

**Comment by Thodor12** [comment]
You could try having a different plantation that does not farm sugar cane himself craft the books and paper, seeing as you need multiple plantations anyway to suffice all of the possible resources.

**Comment by marchermans** [comment]
> The planter has an additional complexity, as they require sugarcane for themselves as well, for replanting purposes. This is not always going right: I noticed they sometimes use their own stock for crafting purposes as well, and have trouble replanting the sugarcane afterwards

This is indeed logical, as I said, the RS does not care that it is a crafter worker: Has it the supplies? Then no subsequent request is made... That is because it just does not know. It is internally capable of handling it but it would not matter since it just does not know that those are stock to keep.

**Comment by marchermans** [comment]
> You could try having a different plantation that does not farm sugar cane himself craft the books and paper, seeing as you need multiple plantations anyway to suffice all of the possible resources.

Would not really solve it. The RS uses shortest distance approximation, so the own worker is always closer then any other.

**Comment by Raycoms** [comment]
At the very least I want the plantation worker to be able to continue doing their "main job" as long as they don't have any actual crafting to do. Waiting for resources should have them free to do stuff too. Afaik the forester works this way too.

**Comment by ArkenorOakshadow** [comment]
Perhaps it might be simpler to give papermaking to a different worker. The carpenter perhaps.

**Comment by sgallaty** [comment]
Give books and paper making to the library - a la monastic bookmaking.

**Comment by Thodor12** [comment]
Giving it to a different worker won't solve the issue of the AI standing still for crafting requests, for the carpenter this isn't a big issue since he's a sole crafting job, however by default carpenter recipes mandate 75% wood products present in the craft, sugar cane does not fall under this, so that would require an exemption of some sort.

Additionally the library falls in the exact same category as the plantation. It'd become a crafting job with a side effect, also currently "workers" in the library are students training on their skills, not really librarians, so that'd probably require a better fitting job to be made first.

Leaving it with the plantation is the best course of action, but just changing up the entity AI so it matches the forester.
