### ISSUE TITLE
Builder doesnt build the sawmill

### ISSUE THREAD

**Issue by PenguinMan98** [ldtteam/minecolonies#836]
### Minecolonies version

version 1.11-0.6.3360

### Expected behavior

- Build the sawmill!

### Actual behaviour

- I place the building and create a build order for it and the builder asks for materials. I provide the materials. The builder happily skips off into the woods, finds a nice spot overlooking the build site, then stops there and does nothing.  Pressing recall just resets the guy and he returns to the same spot.

**Comment by SulpherStaer** [comment]
sawmill, or lumberjack?

sawmill is not yet implemented

**Comment by marvin-bitterlich** [comment]
Sawmill it the building for the lumberjack.

@PenguinMan98 can you give us a acreenshot of him at his spot? There may be pathing issues we can see.

**Comment by PenguinMan98** [comment]
I don't think that server is currently being hosted. I could try to recreate the issue in single player if you don't mind waiting.

**Comment by Raycoms** [comment]
That would be useful.

2017-04-24 14:18 GMT-03:00 Joe <notifications@github.com>:

**Comment by PenguinMan98** [comment]
So far I have not been able to reproduce this.  The issue seems to be specific to the map.  I have a copy of the server map if you think that might be useful.

**Comment by Raycoms** [comment]
Please reopen if able to reproduce
