### ISSUE TITLE
Netherminer crashes Server

### ISSUE THREAD

**Issue by DerpGorg** [ldtteam/minecolonies#8362]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [ ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.16

### MineColonies Version

1.0.527-ALPHA

### Structurize Version

1.0.527-ALPHA

### Current Behavior

As soon as the Netherminer picks all required tools and starts his job the server crashes. 

### Expected Behavior

Netherminer enters the nether withouth crashing the server

### Reproduction Steps

1. Build a Netherminer
2. Provide him with the Items needed
3. Wait for him to start his job

### Logs

https://gist.github.com/DerpGorg/44e2bec367d2cb8d374cdf4c244242bb

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
Could you try with the latest version? (Version 1.0.716 at time of writing)

**Comment by Raycoms** [comment]
The log doesn't show the crash from what I could see?
