### ISSUE TITLE
Colony name instead of player name when entering colony

### ISSUE THREAD

**Issue by Nikademus** [ldtteam/minecolonies#8363]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

minecolonies-1.18.2-1.0.715-ALPHA

### Structurize Version

1.18.2-1.0.389-RELEASE

### Current Behavior

When a player enters someone else's colony, the message the colony owner gets says "colony name has now entered colony".

![unknown](https://user-images.githubusercontent.com/1380028/167745329-b8fad8cf-8bb9-44cb-8217-310060a095f4.png)

### Expected Behavior

Should say "player name has now entered colony"

### Reproduction Steps

1. On a Multiplayer server, have another player visit your town.

### Logs

https://gist.github.com/Nikademus/cfd57b452ca93f5b808f128d4425b9b6

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
This has already been fixed in #8349, but that has not yet been merged to 1.18.

The merge to 1.18 is tracked by #8359.

**Comment by uecasm** [comment]
This should now be fixed as of 1.18.1-1.0.724-ALPHA and 1.18.2-1.0.725-ALPHA (or above).
