### ISSUE TITLE
Couriers not obeying priorities or priorities are reversed

### ISSUE THREAD

**Issue by Jjmboni** [ldtteam/minecolonies#8364]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.18.1-1.0.721-ALPHA

### Structurize Version

1.18.1-1.0.387-RELEASE

### Related Mods and their Versions

Forge Version: 39.1.2
blockui-1.18.1-0.0.45-ALPHA
domum_ornamentum-1.18.1-1.0.39-ALPHA-universal

### Current Behavior

It appears the Couriers are sorting their tasks by priority SMALLER numbers first.  My courier has a Priority 14 task to pickup from the stash.  I just watched four other tasks get inserted ABOVE that task.
Pickup from Shepherd 
Priority 7

Delivery of 64 [Compost] Warehouse -> farmer: Poppy B. Garrary
Priority 13

Delivery of 2 [Oak Slab] Warehouse -> builder: Harlee C.
Priority 13

It's making the stash pickups take days because other tasks constantly get inserted in front of it.

### Expected Behavior

Priorities should be sorted highest first.  

### Reproduction Steps

1.  You may need a colony with lots of buildings.
2.  Place an item in the stash.  That gets assigned to a courier.
3.  Go to the courier's workplace and observe tasks.  The stash is the highest priority but you should see lower priority tasks get inserted above it.
4. It may take several days for the courier to get to the stash

### Logs

https://pastebin.com/WcJQPEDD

### Anything else?

I don't believe this occurred in version minecolonies-1.18.1-1.0.508-ALPHA.  It was only until I upgraded to this latest alpha that I began noticing the inordinate amount of time couriers took to get to the stash.

My colony has 66 citizens, 7 couriers for one lvl4 warehouse and 4 builders.  I expect it to take a while to get items from the stash, but not several ingame days.

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by someaddons** [comment]
This is actually not a bug. Couriers are calculating various factors into the ordering of requests, from distance to similar requests, trying to alternate with closeby pickups and to the given priority of the requests. Which allows them to run a much more optimized course than just those plain priorities are dictating. What we probably should change here is the representation to the player, either hide the numbers or display the internal scores.

**Comment by MotionlessTrain** [comment]
I think displaying the internal score would be very useful. The pickup priorities are confusing enough already (a lot of people seem to think they determine the delivery priority as well, which has a higher priority), and trying to explain those priorities, while the couriers don't seem to use them as much as they seem to ought to, is counterproductive. Those scores would at least explain the order better
And it gives players a valuable insight why that courier doesn't want to go to the stash

**Comment by Raycoms** [comment]
Deliveries != Pickups. Deliveries are FIFO + they are distributed to couriers depending on various factors. Pickups are the only ones that got priorities. If you adjust a priority of a building, it will change the pickup prior not the delivery prio.

**Comment by Jjmboni** [comment]
This is really good information, thank you.  I agree seeing the internal score would be more helpful.

**Comment by nacklebert** [comment]
if may also be helpful to change how priorities are shown from a number - which infers an absolute order - to a "category/tag" which could be "Whenever/Average/High/Urgent/Critical" or similar. This would be a good rule of thumb anytime there values being combined into weighted outcomes (dont show the values, abstract them)
