### ISSUE TITLE
Relocating Colony

### ISSUE THREAD

**Issue by Rory-Lambert** [ldtteam/minecolonies#837]
Please can anyone advise if it is possible to allow a player to have a second colony, or to relocate their first colony. I do not mind losing any citizens/progress on the old colony. I have allowed infinite supply chests in the configs, but I cannot place a second townhall, even after destroying the first. I can't seem to find an admin command to wipe out a player's colony either

**Comment by xavierh** [comment]
I will assume that you are playing in SP or that you have permissions for it.

You can show the list of colonies and their id using commands:
`/mc colonies list`

Use the id to delete the colony with:
`/mc colony delete 1`

Where **1** is your colony id
