### ISSUE TITLE
Mines through ceiling and through walls and teleports to unreachable places

### ISSUE THREAD

**Issue by leagris** [ldtteam/minecolonies#8375]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.0.730-ALPHA

### Structurize Version

1.0.399-RELEASE

### Related Mods and their Versions

1. Forge: 40.1.20
2. BlockUI: 0.0.47-ALPHA
3. Domum Ornatum: 1.0.50-ALPHA-universal

### Current Behavior

Miner can move to unrelated level or even teleport into unreachable caverns to mine at a level.

Building through ceiling or ground, or walls. Teleporting to unreachable places.

### Expected Behavior

Miner should only be allowed to mine at the level he is standing into. Only allowed to emergency teleport out if leaving the mine (go to mine hut, go to restaurant, go to bed, go to hospital...), but should never teleport to the place to mine.

Corollary, miner shall not mine a place if it is not directly reachable from the node/mineshaft he is standing while mining.

### Reproduction Steps

Have a mine with lots of nodes built at level 2, then have miner work now at level 1.

### Logs

nothing/irrelevant

### Anything else?

This misbehavior of the miner has some negative consequences:

- Miner mines unreachable places.
- Miner teleports to unlit monster riddled caverns.
- Miner standing at wrong level cannot get help from mine guards who patrols at the right level the miner shall be at.

![Mines level 1 while standing at level 2](https://i.imgur.com/WE4dQFQ.jpg)

![Mines 1 level above and forward](https://i.imgur.com/zXugAY3.jpg)

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
As an additional note, it seems that they continued building the next node but on the new selected level, after a new level got selected.
It is intended that they use the other tunnels to get close to the place they are mining, but it seems unintended that they are mining there in the first place

**Comment by Raycoms** [comment]
The issue is a bit confusing. If the miner can't reach a place the regular way, they might try to get close through other means, which is intended.

From what I'm understanding is that even though they could theoretically reach it, they still mine on another level sometimes?

**Comment by MotionlessTrain** [comment]
From the message on discord, I understood that a new level got selected, and the next node was placed as if it would be adjacent to a previous one on the previous level, instead of next to the shaft

**Comment by leagris** [comment]
The next node was built in the middle of nowhere without reachable path, so the miner moved to the level below and started digging through ceiling.

Also, while digging the mineshaft. One of my miner decided to teleport into nearby cavern that was unreachable and unlit. Then was killed there alone without even possibility to get help. I found out when he died with the highlight of his grave.
