### ISSUE TITLE
Nether miner always idle

### ISSUE THREAD

**Issue by supershooter116** [ldtteam/minecolonies#8378]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

minecolonies-1.18.2-1.0.737-RELEASE

### Structurize Version

structurize-1.18.2-1.0.399-RELEASE

### Related Mods and their Versions

1. forge-1.18.2-40.1.0
2. multi-piston-1.18.2-1.2.7-ALPHA
3. blockui-1.18.2-0.0.47-ALPHA
4. domum_ornamentum-1.18.2-1.0.41-ALPHA-universal
5. OptiFine_1.18.2_HD_U_H7

### Current Behavior

![image](https://user-images.githubusercontent.com/79056473/168585842-dd9670ab-b516-480a-b7d3-7e67633c34cf.png)
Currently my nether miner is always idle end will not enter the portal to collect resources.
He is in perfect condition to work and his GUI says he is working, but he wont enter the portal or collect resources.
I even went in to creative to give him all the items he needs, but he wont work.
This problem started after I had build my nether miner for the first time and then my first nether miner died while in the nether and now the second miner wont work
If further information is needed please let me know.

### Expected Behavior

After a nether miner has died either in the nether or overworld the new miner should continue working and go in the portal to collect resources.

### Reproduction Steps

1. research and build the nether mine (wooden)
2. give the miner all the items he needs
3. let the first miner then die in the nether while collecting resources
4. assign a new miner and see if this one will go in the portal to the nether.

### Logs

https://gist.github.com/supershooter116/b82fc089434270c84a9b665fa85fc03f#file-gistfile1-txt

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
There is a cooldown on going to the nether? How many ingame days did you wait?

**Comment by supershooter116** [comment]
I don't quit understand that sentence. Are you asking if  there is a cooldown for the nether miner or are you saying that there is a cool down for the nether miner?
cause if there is a cooldown for the nether miner then of course he would not work since we had day and night cycle turned off.
I also could not find anything on the minecolonies wiki and in the minecolonies discord.

**Comment by MotionlessTrain** [comment]
Ah, that may explain things. Minecolonies doesn't work properly as daylight cycle is turned off. The mod relies on it for a few things

**Comment by Raycoms** [comment]
Yes, there is a cooldown, and day/night cycles off explains it then =D Will need to add that info to the wiki @anonymous563

**Comment by anonymous563** [comment]
[Sleep system](https://wiki.minecolonies.ldtteam.com/source/systems/sleep)
That info is actually already on the wiki, just not on the nether miner page specifically since that wasn't known until now. I've updated the sleep page with that info.
