### ISSUE TITLE
Stonemason cannot learn DO recipe with only Sandstone Input

### ISSUE THREAD

**Issue by Nyuraa** [ldtteam/minecolonies#8379]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.0.747-ALPHA

### Structurize Version

1.18.2-1.0.399-RELEASE

### Related Mods and their Versions

1. Forge Version 40.1.20
2. blockui-1.18.2-0.0.47-ALPHA
3. domum_ornamentum-1.18.2-1.0.50-ALPHA-universal
4. multi-piston-1.18.2-1.2.7-ALPHA
5. jei-1.18.2-9.7.0.195

### Current Behavior

Stonemason cannot learn The DomumOrnamentum Recipe with only Sandstone as Input.

![2022-05-17_08 09 20](https://user-images.githubusercontent.com/104888046/168741253-003efdba-ee99-421e-b196-43b088ea0d68.png)

### Expected Behavior

Stonemason should be able to learn Sandstone DO recipes,
because he´s also responsible for normal sandstone recipes (Sandstone Stairs, Slabs, etc.)

### Reproduction Steps

1. Open Stonemason Hut
2. Open Custom Recipe Tab
3. "Teach Recipe"
4. Select Sandstone as Input 1
5. Try to save Recipe

### Logs

https://gist.github.com/Nyuraa/b3a028863c93fadc4bc1c53f1f26e9b7

### Anything else?

Reproducable in a Testworld with only JEI and Minecolonies Dependencies

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
This is already fixed in 1.18.1 but it looks like it hasn't been ported yet.
