### ISSUE TITLE
Nonfunctional Tinkers Compat

### ISSUE THREAD

**Issue by Moobien** [ldtteam/minecolonies#8382]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

753

### Structurize Version

399

### Related Mods and their Versions

Forge 40.1.19
Tinkers: 1.18.2-3.5.0.17

### Current Behavior

Workers don't recognise valid (level appropriate) tools as valid.

### Expected Behavior

Workers accept the appropriate tools.

### Reproduction Steps

1: Make a Tinkers tool, Axe for an example. Iron axe head, wood tool rod, copper binding
2: have a lvl 2 forester asking for an axe
3: give the tinkers axe you made to the forester
4: watch them still ask for an axe.

### Logs

https://gist.github.com/Moobien/c4d10dc85aaaffbaac828e424d726378

### Anything else?

https://cdn.discordapp.com/attachments/915411380268580864/976135012598550579/unknown.png
https://cdn.discordapp.com/attachments/915411380268580864/976135384176140298/unknown.png

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
did you try even lower grade?

**Comment by Moobien** [comment]
Someone on discord said that they wouldnt accept stone tinkers tools

**Comment by MotionlessTrain** [comment]
> Someone on discord said that they wouldnt accept stone tinkers tools

They were using Tetra, not Tinker's Construct. That was a separate question altogether

**Comment by Moobien** [comment]
> > Someone on discord said that they wouldnt accept stone tinkers tools
> 
> They were using Tetra, not Tinker's Construct. That was a separate question altogether

at any rate, I just tried it myself with a stone headed axe. refused to accept it was an axe

**Comment by Raycoms** [comment]
I'll close this, as this is not nun functional, but simply non existant in 1.18.2 as at the moment we added it to 1.18.1 1.18.2 tinkers didn't exist yet.
