### ISSUE TITLE
Send latest.log modpack Live in the vilage 2

### ISSUE THREAD

**Issue by FaustMont** [ldtteam/minecolonies#8384]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.16

### MineColonies Version

minecolonies-1.16.5-1.0.634-BETA.jar

### Structurize Version

structurize-1.16.5-1.0.380-BETA.jar

### Related Mods and their Versions

Charm cows cause an error

### Reproduction Steps

I drove him into the corral cows from the mod Charm 

### Logs

https://gist.github.com/FaustMont/908b8064ae897a601d72ff165e800e35

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
I believe it's an issue with the Charm mod

**Comment by FaustMont** [comment]
Thanks for the feedback, then we will bring him normal cows in the game
С уважением,
*Алейников Вячеслав*


ср, 18 мая 2022 г. в 01:23, Raycoms ***@***.***>:

**Comment by Raycoms** [comment]
=) Np

**Comment by FaustMont** [comment]
By the way, the problem is still there, but I noticed that this version squatter also faces the problem of AI, reload through the main unit does not help, but to lay off and take back, gives a temporary job, and again in the error ns, although ovtsi and cows already  standard, all unit functions are included, such as reproduction, feeding, milking and to paint, there are options, why it can happen?

**Comment by MotionlessTrain** [comment]
The cows give a problem when the game tries to store them: An error is thrown, which in turn confuses the Cowhand's AI.

I'm not sure whether travelers_index has anything to do with Charm, but that mod seems the one giving the error when the cow's data is stored

**Comment by ArkenorOakshadow** [comment]
Probably the "Random animal textures" feature doing something odd with the NBT, making Travellers Index choke.
