### ISSUE TITLE
missing Localization 

### ISSUE THREAD

**Issue by manmaed** [ldtteam/minecolonies#8385]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [ ] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.0.754-ALPHA

### Structurize Version

1.0.399-RELEASE

### Related Mods and their Versions

BlockUI: 0.0.47-ALPHA
Multi-piston: 1.2.7-ALPHA
Domum Ornamentum: 1.0.399-RELEASE

Forge: 40.1.20

### Current Behavior

No Localization for npcs job label desc
 ![](https://ss1.manmaed.net/1652826709.png)

### Expected Behavior

for there to be Localization 

### Reproduction Steps

1. make coloney
2. build a buider or other hut if have builds
3. open npcs GUI
4. open there job tab

### Logs

N/A

### Anything else?

Nope

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
@Thodor12
