### ISSUE TITLE
builder destroying items inside chests

### ISSUE THREAD

**Issue by TheAncientCrafter** [ldtteam/minecolonies#8393]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.18.1

### MineColonies Version

1.0.735  release

### Structurize Version

1.0.401 release

### Related Mods and their Versions

non of the mods i have have download button at forge(assuming last versions)

### Current Behavior

builder destroyed everything on the chest  while upgrading

### Expected Behavior

should not destroy the items on chest

### Reproduction Steps

propably put chest where builder gonna build  

### Logs

N/A

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
fix pushed to structurize, will take a bit to take effect
