### ISSUE TITLE
Uneven distribution of Tasks between delivery man/courier

### ISSUE THREAD

**Issue by AlmightyAnubis** [ldtteam/minecolonies#8394]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

minecolonies-1.18.1-1.0.735-RELEASE.jar

### Structurize Version

 structurize-1.18.1-1.0.401-RELEASE.jar

### Current Behavior

My level 5 couriers dont take any tasks while my lower level couriers do all the jobs. This why, the task list of the level 5 couriers is empty, while when I ask for items from the stash the item delivery is in places over 100, what is very slow. I don't really know, what causes this issue, but maybe the check for the number of items to deliver and see, that a lower tier delivery man would be better, because the would run nearly empty (1 of 36 slots (University Upgrade for more Inv space) is worst capacity utilization then 1 of 3 or 5)

### Expected Behavior

A more even distribution of the workload between the works. I don't know, how the current system works, but maybe it can be adjusted so that the delivery man with the lowest number of tasks get the new tasks. This would cause the task to be more even distributed but can cause inefficiency depending on local distribution (2 delivery man get pickup tasks next to each other, that one could easy handle). Maybe a handling in step sizes would be a solution to. So, tasks get floor divided by 10 for example and if the number is equal (both hat 0-9, 10-19  etc. tasks), they distribution will depend on distance and efficiency but when it is not equal, the delivery man with the lower number of tasks will get the tasks. This could prevent this kind of very uneven distribution.

### Reproduction Steps

1. Build town to level 5
2. research the 9 more slots for citizens
3. upgrade most delivery man to level 5
4. Even resetting the request system does not cause equal distribution between delivery man

### Logs

-

### Anything else?

I found a similar issue, but this was closed some versions before, so it might be a new or a renewed issue.

![2022-05-22_13 09 10](https://user-images.githubusercontent.com/62308030/169692254-0f8c7ace-eb3b-495a-a515-0d2adda35852.png)
![2022-05-22_13 08 32](https://user-images.githubusercontent.com/62308030/169692255-de56c88b-5b2f-43bf-b475-1fe42c4629ce.png)

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
do you have multiple warehouses?

**Comment by AlmightyAnubis** [comment]
yes, 2. But the level 5 and the lower level, which take all the tasks work at one

**Comment by AlmightyAnubis** [comment]
I had no issues util now. My be caused by upgrading delivery man to level 5. I don't have any other idea

**Comment by AlmightyAnubis** [comment]
Never mind. It was an issue with my food system. Cook only keeped carrots for some reason what my level 5 workes didnt like... So the got stuck there...

**Comment by Raycoms** [comment]
I was just wanting to ask if the other courier was somehow stuck =D

**Comment by AlmightyAnubis** [comment]
Should I reopen for the restaurant issue? Or make a new one? I have more then enough raw beef for steak, rabbit etc. but the restaurant only stocked on carrots what my level 5 citizens dont want to eat.
Or is the normal solution to disable such foods or minimum stock the better ones?

**Comment by Raycoms** [comment]
What restaurant level is it?

**Comment by AlmightyAnubis** [comment]
Level 4

**Comment by Raycoms** [comment]
Let me quickly look at it.

**Comment by Raycoms** [comment]
I added some fixes for that

**Comment by AlmightyAnubis** [comment]
Thanks, very nice
Could you have a quick loot at this: #8345 
Should be done is some seconds, if you have this time left
