### ISSUE TITLE
Multithread AI

### ISSUE THREAD

**Issue by reggaemuffin** [ldtteam/minecolonies#84]
Plan to migrate all AI code to a multi-threaded system with targets/goals.

This means that all code running in the server thread will be split up into small easily maintainable chunks.

We also have to make more error checks and so it will solve many problems we currently experience with workers shut down/ fired while performing a critical task.

With a multi-threaded system we can migrate the path-finding to it and clean up some of  that messy code. Also we can introduce sub-goals that will help a lot with path-finding as we can somewhat enforce a certain path over others.

Overall we will increase stability as the coder has to think more in terms of actions and less in terms of 50 global variables with 100 edge cases.

**Comment by Wissi** [comment]
@reggaemuffin Still working on this?
Is it still a thing?
Do we close this now?
