### ISSUE TITLE
Supply Camp as Decoration Can't be built.

### ISSUE THREAD

**Issue by Wissi** [ldtteam/minecolonies#840]
When trying to build the Supply Camp as a decoration Builder will just stand there and do nothing.
Builder has all the materials in the list (pg. 2 GUI), and even the space required is cleared and clean.
Fire/Hire will reset him to go back and stare at the spot eternally. 
Several Minecraft days and fire/hire again.. same thing.

**Comment by xavierh** [comment]
Is it because of the fire? @raycoms

**Comment by Raycoms** [comment]
It is, I'll fix that next week

2017-04-23 8:48 GMT-03:00 xavierh <notifications@github.com>:
