### ISSUE TITLE
Research tree requirements lists "totaling levels" for buildings that can only be built once

### ISSUE THREAD

**Issue by Thodor12** [ldtteam/minecolonies#8402]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.0.765-ALPHA.jar

### Structurize Version

1.0.399-RELEASE.jar

### Current Behavior

When you hover over a research it shows the building requirements, for buildings like a town hall (which can only be built once) the below message is unnecessary since the building can only be built once.

![Image](https://cdn.discordapp.com/attachments/956880930608410704/979385937400328292/2022-05-26_16_09_48-Minecraft__1.18.2_-_Singleplayer.png)

### Expected Behavior

The research tree should respect limits to certain buildings and change the requirement messages accordingly.
At the time of writing this only applies to:
- Town hall
- Tavern

### Reproduction Steps

1. Build a university
2. Open any research tree
3. Look for a research which has a town hall or tavern as requirement (ex. "Combat > Boiled Leather")

### Logs

N/A

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
At the research-tree level, it is actually checking for what it claims, so the tooltip is correct.

When someone defines a research, they can choose to set a different limit property if they want to limit on "a single building being at least level N" instead of that.  Currently this is only used for the sifter unlocks, not the "classic" research.

So this isn't really a bug.  You could perhaps argue that the single-allowed buildings ought to use that other property instead, but that might be more fragile if in the future it was decided to allow multiple taverns, for example.

**Comment by Thodor12** [comment]
Instead of defining the building limit requirement on a per research basis, woudn't it be more beneficial to have a proper limiter defined in the AbstractBuilding itself, that way the research can make use of that (if not explicitly defined in the research itself).
It would at least be used on the townhalls to always force 1 of them (and for now taverns aswell).

That could then also be used to improve the build tool logic so there's no special cases in constructing certain buildings like the way this is currently handled, it would just become a generic way.

**Comment by MotionlessTrain** [comment]
The way it is now is more flexible. There may be research in the future that requires a level 3 house, not house(s) totalling 3 levels. If this would be defined in the AbstractBuilding, that flexibility is gone.

**Comment by Thodor12** [comment]
> The way it is now is more flexible. There may be research in the future that requires a level 3 house, not house(s) totalling 3 levels. If this would be defined in the AbstractBuilding, that flexibility is gone.

I did state `(if not explicitly defined in the research itself)`. I'm not saying remove the option, but make it also take into consideration the overall building limit.

**Comment by Raycoms** [comment]
This is actually fine. Maybe the text is not that great
