### ISSUE TITLE
supply camp items in chests with supply loot set to false in config

### ISSUE THREAD

**Issue by MacChuck** [ldtteam/minecolonies#8403]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.18.2-1.0.754-ALPHA

### Structurize Version

1.18.2-1.0.399-RELEASE

### Related Mods and their Versions

FTB Pack, direwolf 20 1.12, pack version 1.2.0

### Current Behavior

"SupplyCamp Chest - free" is spawning in dungeon treasure chests even with the following config setting applied. This is on a fresh world with the configuration file in place before the chunks were generated.

world/serverconfig/minecolonies-server.toml
generatesupplyloot = false

### Expected Behavior

Supply camp items shouldn't be appearing in dungeon loot

### Reproduction Steps

Change generatesupplyloot from true to false in the server config file.
Explore new chunks until a new dungeon is found.
Check loot.

### Logs

which log?

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
You would need to put that setting in a copy of the minecolonies server config in the "defaultconfigs" folder before you create a new world.
Otherwise, when you set that option to false, it will only apply to dungeon chests in unexplored terrain.

That said, I thought this config option was supposed to be moved to the common config a while ago

**Comment by MacChuck** [comment]
Now that you mention it, I think I did put it in defaultconfigs before world creation. Either way I know the file was in place before this terrain was generated, as I found it 20,000 blocks from spawn where nobody had been yet.

I don’t remember seeing that option in another file, where is the common one at?

**Comment by MotionlessTrain** [comment]
It doesn't appear to be in the common config in 1.18.2. That did change in 1.16.5.
I have the feeling that that change never got ported to 1.18.2

**Comment by Raycoms** [comment]
fix ported
