### ISSUE TITLE
Children moving into manual set home

### ISSUE THREAD

**Issue by Josbud1** [ldtteam/minecolonies#8407]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

 minecolonies-1.18.2-1.0.765-ALPHA.jar

### Structurize Version

 structurize-1.18.2-1.0.399-RELEASE.jar

### Current Behavior

I have a house set on manual mode because it's for a workplace far from my town center. I've upgraded the house to get the bonus for the worker but children keep moving into the open beds. Not sure if it does it with adults too.

### Expected Behavior

If set to manual mode I expect empty beds in a house to permanently stay empty unless I assign someone

### Reproduction Steps

Reach your max pop with children and one will move into the manual mode house.

### Logs

<script src="https://gist.github.com/Josbud1/99fd5ffbe9ee61cb5577b5d0c6d447b6.js"></script>

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
To make it easier to open the log (if it is at all necessary)
https://gist.github.com/Josbud1/99fd5ffbe9ee61cb5577b5d0c6d447b6

**Comment by Raycoms** [comment]
That's intentional, if two people in that house decide to have a kid, the kid will take that open bed.

**Comment by Josbud1** [comment]
I had already mentioned in the discord to you that if there is an empty slot a child will move in, Not be born in.  this even happens in house that have a max of 2 civs with 1 living there, cant make a baby with 1 person. I can unassign the child from the house and a new one will swap places with a the child, it seems to me children just ignore the assignment state of the house

**Comment by Talyda** [comment]
Single parent families are a thing that exist - in game as well as in life =)  You can have same sex couples, even orphaned children if there is no parents in the house.
Children will be born into empty spaces, if you don't want them to, you can turn off "kids will be born" in the town hall

**Comment by Josbud1** [comment]
That feels wrong. The house should keep the beds empty if you don’t want people in them. I can’t just turn off birth cause I need the constant stream of children but they tank my morale when they decide to move into my outposts 300 blocks away from the nearest school.

**Comment by uecasm** [comment]
Then only use L1 houses at your outposts (or however many people you want to have there).  Or consider constructing schools and other facilities (restaurants, etc) out there too -- that will also use up some housing slots.

**Comment by Josbud1** [comment]
Worker level is limited by the level of their house. So If I want good workers I have to upgrade their house. Building a school at all these places is excessive. I'm not trying to make several popup gold rush towns. Plus there would be the issue of children in the main town trying to work at the far away outpost's school and being mad at the distance circling back to square one.

**Comment by Josbud1** [comment]
I still think this is bugged and doesn't work intuitively, but seems that point is not getting across. Should I just make a suggestion post instead since this isn't getting anywhere?
