### ISSUE TITLE
Mine levels messed up

### ISSUE THREAD

**Issue by Josbud1** [ldtteam/minecolonies#8408]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

 minecolonies-1.18.2-1.0.765-ALPHA.jar

### Structurize Version

 structurize-1.18.2-1.0.399-RELEASE.jar

### Current Behavior

https://vimeo.com/714797036

It's best shown in the video but my mine levels go 1,2,3,4,5,6,4,5,-1,7

I believe what caused this was I had a power outage well playing the game and a lot of mine colonies stuff was rolled back. Any building in construction leveled down one and forgot they had an upgrade request. That was a pain but I just had to reupgraded them. Guards dematured back into babies still wearing their armor and when they grew up stayed a pupil on the jei map but I think those ones died so no problem there.

None of the actual blocks got rolled back, just the data or something for minecolonies rolled back.

My theory is the last level my miner made before the rollback was 6 but it rolled back to when they were on level 4. So they continued building the shaft from the bottom starting with level 4 but the previous 4,5,6 where just forgotten.

![image](https://user-images.githubusercontent.com/93408749/170840361-2c72e0f7-c59b-49ed-9f80-76fd63951d1a.png)

As you can see each consecutive level goes down by 4 blocks on the y-axis, however at level 3 it jumps 15 blocks down. The original 4-6 are just forgotten all together and the new level 6 is displayed as -1 on the sign.

I've tried repairing and upgrading the mine aswell as trying to repair the levels from the hut block with no success 

### Expected Behavior

to count all the levels that were built.

### Reproduction Steps

Play the game
unplug/turn of pc maybe alt f4 the game well a miner is making a shaft.

### Logs

not sure

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by GangstaPichu** [comment]
I've had this same issue, but on a server with a modpack also I'm not sure what might've cause it. I don't recall if it was after an effecting crash I had in the area (due to another mod) or what. All I know is that mine stopped on 11 and it was -1 like yours. I decided to try and fix it by destroying it and placing it back down. That seemed to make it worse as there's now no options to mine any of the levels. The miner isn't detecting the mine at all. Just sits there all day doing nothing. Doesn't even request anything like tools. I've counted it as a lost cause and I'm gonna try and build a whole new one somewhere. Keep the broken one, just never use it. 

Also, that's the only issue I have. Just the miner. Nothing else happened.

Modpack: Valhesia Volatile (For reference)

**Comment by Josbud1** [comment]
My miner is continuing on like normal. The only problem is he doesn't acknowledge those other levels exist. The main problem I have is it sucks having a nearly perfect shaft then a few messed levels. Guess I could manually build them

**Comment by GangstaPichu** [comment]
> My miner is continuing on like normal. The only problem is he doesn't acknowledge those other levels exist. The main problem I have is it sucks having a nearly perfect shaft then a few messed levels. Guess I could manually build them

Yeah, mine was doing that too. Wouldn't go to any other level even if I ordered them too. Weirdly as well they started building pieces of mineshaft in place that wasn't even reachable. They'd teleport around too I noticed sometimes. It was definitely weird. 

At least yours still works. I wish mine did.

**Comment by Raycoms** [comment]
same as https://github.com/ldtteam/minecolonies/issues/7753
