### ISSUE TITLE
ai has run into an issue upgrading barracks tower

### ISSUE THREAD

**Issue by superdude808** [ldtteam/minecolonies#8412]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

minecolonies-1.18.1-1.0.777-ALPHA

### Structurize Version

structurize-1.18.1-1.0.401-RELEASE

### Related Mods and their Versions

forge 39.1.2.
domum_ornamentum-1.18.1-1.0.49-ALPHA-universal
multi-piston-1.18.1-1.2.9-ALPHA
blockui-1.18.2-0.0.47-ALPHA

### Logs

https://gist.github.com/superdude808/ed50125956873077625c86d0626cabca

### Anything else?

https://imgur.com/a/GjtZ6dB

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by dmdinnc** [comment]
Some notes i've found with this bug while repeatedly upgrading my jungle barracks:
- Came up on each upgrade of the barracks
- Happened after completion, triggering the build complete messages 3 times (the chunk radius claimed and the builder completed messages)
- When you go to the barracks after they break, the building is stuck on a repair that was not requested, and after cancelling the repair there's nothing to repair.

**Comment by Raycoms** [comment]
hotfix pushed
