### ISSUE TITLE
Game Crashes on Rightclicking with Builders Tool

### ISSUE THREAD

**Issue by Ferisia** [ldtteam/minecolonies#8413]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.0.778-ALPHA.jar

### Structurize Version

1.0.399-RELEASE

### Related Mods and their Versions

Forge 40.1.19
Block UI 1.18.2-0.0.47-ALPHA.jar
Domum Ornamentum 1.0.50-ALPHA-universal.jar

### Current Behavior

The game crashes when you try to right click with a Builders Tool in a already built colony

### Expected Behavior

The game not to crash.

### Reproduction Steps

1. Load game
2. Build a colony
3. Right click with Builders Tool

### Logs

https://pastebin.com/GQTRk2aN

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Nightenom** [comment]
Will get fixed with ldtteam/Structurize#506
