### ISSUE TITLE
1.18.2 Crash when using Build tool

### ISSUE THREAD

**Issue by Saereth** [ldtteam/minecolonies#8418]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

minecolonies-1.18.2-1.0.784-ALPHA

### Structurize Version

structurize-1.18.2-1.0.399-RELEASE

### Related Mods and their Versions

Forge version 40.1.31

### Current Behavior

if I try to use the build tool for most structures it crashes

### Expected Behavior

In would expect it not to crash

### Reproduction Steps

Put down a restaurant or most other huts, shift right click with build wand, game crashes

### Logs

https://bytebin.lucko.me/geFb0GSbEw

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Saereth** [comment]
Saw there was an updated so I updated to 
structurize-1.18.2-1.0.411-ALPHA
minecolonies-1.18.2-1.0.792-ALPHA
blockui-1.18.2-0.0.48-ALPHA

I did notice it doesnt happen with all structures, but it definitely happens with the tavern, and a few others but I dont remember which ones specifically
Problem persists under these. If I can be of any more assistance let me know, thanks!

**Comment by Raycoms** [comment]
did you disable jar schematics?

**Comment by Saereth** [comment]
Yes, I have the warped schematics extracted into the structurize folder, should I refresh those from the new build?

**Comment by Raycoms** [comment]
Atm this causes crashes as you've been experiencing. We already got an issue for that too. Will be fixed "soonish".
