### ISSUE TITLE
Production recipes not working.

### ISSUE THREAD

**Issue by Rimuru-Tempest-IMP** [ldtteam/minecolonies#8420]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.16

### MineColonies Version

1.0.801-ALPHA

### Structurize Version

1.0.392-RELEASE

### Related Mods and their Versions

Forge Version: 36.2.35

### Current Behavior

Production recipes not working.
When builder requests specific Recipes like any Timber frame or stairs or stone item
both the Sawmill or the Stonemason dont make them.
When checking the request from builder the list below showing the recipe and that it is requested from sawmill or stonemason is missing.

After spending a whole day trying to solve it and been talking with Locomotive about possible causes nothing seems to solve it.
(believe this started after updating to 1.0.788-ALPHA and now in 1.0.801-Alpha it is still the case.)
dont remember having it in 1.0.782-ALPHA)

### Expected Behavior

That the recipes would be created as they have been teached to the production workers:Sawmill and Stonemason in this case.

### Reproduction Steps

Have builder construct a building that requires timber frames....
when requesting for timber frames sawmill will not make them even while builder is asking for it and the resources needed are in the warehouse but delivery is not even conducted to the sawmill.

### Logs

<script src="https://gist.github.com/Shadow-Wing-NLD/748338bd439af2699ff37fa5f5972336.js"></script>

### Anything else?

Check Discord Chat in Support 1.16 to see everything checked with Locomotive on possible causes or fixes.

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
https://gist.github.com/Shadow-Wing-NLD/748338bd439af2699ff37fa5f5972336 for easier access to the log

**Comment by MotionlessTrain** [comment]
We did trying to reteach recipes, cancel requests, etc.

**Comment by Raycoms** [comment]
Is this still a problem?

**Comment by Rimuru-Tempest-IMP** [comment]
Have not checked as been too busy to play MC recently due to work
