### ISSUE TITLE
A.I is damaged

### ISSUE THREAD

**Issue by EmrysMerlin04** [ldtteam/minecolonies#8421]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.0.737-RELEASE

### Structurize Version

1.0.399-RELEASE

### Logs

<script src="https://gist.github.com/EmrysMerlin04/b4bf57d84a89aa1e10bcce2056dc98ce.js"></script>

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
It seems like the dynamic tree compatibility hasn't been enabled again in 1.18, so foresters can't harvest dynamic trees at the moment in 1.18.2
