### ISSUE TITLE
Builder's getting stuck at "load_structure" needing fill material

### ISSUE THREAD

**Issue by Talyda** [ldtteam/minecolonies#8422]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.18.2-1.0.792

### Structurize Version

1.18.2-1.0.411

### Related Mods and their Versions

Minecolonies exploration edition v1.2 on the patreon server

### Current Behavior

I haven't got to a point in my game yet to build, so haven't experienced this myself yet, but putting this here cos I saw it happen to Greypelt on the exploration server yesterday, and Wetz posted it here today:
https://discord.com/channels/472875599422291968/486940969737125922/983825366772756540

Builders are getting stuck, with no signs of needing items at all. When doing /mc citizen info they show 
![image](https://user-images.githubusercontent.com/17323101/172489162-afeebaa2-ae01-4d44-838c-527dc5dec1d0.png)

No requests anywhere from them. Giving them their "fill item" gets them going again.

### Expected Behavior

Builders request fill item if they need it

### Reproduction Steps

 I don't know if it's consistent - reporting it for Wetz

### Logs

there is no log, but I can't submit the report without something in here, so now i ramble =P

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by talkingdragon** [comment]
Same.
On new patron server.
The builder wont let me chnage fill type.
Day before it let me after i chnaged to cobble then to lush (dirt type in biome im in)
now I cant chnage type and builder dosea request wich dosnt indicate what exactly he needs
Eventually I thought he may be bugged, so i filled in the lsuh dirt he needed to do him self, and that was what got him stuck
Seems he is unable to fill him self.

talk1994

**Comment by Wetz1990** [comment]
The builder does also not want to take the "fillblock" from his hutblock, it has to be delivered directly to his inventory.
And it may already be written, but he does not request any fillblocks, he just waits for them.
This is on the Patreon server, running the explore pack.

**Comment by MotionlessTrain** [comment]
This seems to be affecting miners too

**Comment by Raycoms** [comment]
fixed
