### ISSUE TITLE
[1.18.2] initialColonySize not working as intended, limit at 5 instead of 15?

### ISSUE THREAD

**Issue by drakray** [ldtteam/minecolonies#8423]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.0.798-ALPHA

### Structurize Version

1.0.411-ALPHA

### Related Mods and their Versions

Forge 40.1.47
journeymap-1.18.2-5.8.5(mini-map show claim chunk, but holding the build tool show same chunks)
domum-ornamentum-1.18.2-1.0.50-alpha
blockui-1.18.2-0.0.48-alpha
many others but there shouldn't be any interaction

### Current Behavior

initialColonySize is default at 4, which allow a 9x9 claim area
Setting initialColonySize to 15(max value) allow a 11x11 claim, instead of 31x31
Tested in a superflat world for a Fortress build

### Expected Behavior

Setting initialColonySize should provide correct claim area

### Reproduction Steps

Set initialColonySize=15 in defaultConfigs/minecolonies-server.toml
Start a superflat world
Make or /give a supply camp
Start colony
Look at 11x11 claim area

### Logs

https://gist.github.com/drakray/2d5f049f615c7a1ce415e50e95d2e2b0

### Anything else?

Referred here from Discord/support-1.18 by MotionlessTrain#0397, who manage to reproduce

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
As a note: The initialColonySize=15 has been checked and/or set in the serverconfig of the superflat world as well.

I don't think I said I reproduced the issue

**Comment by drakray** [comment]
Sorry I misinterpreted that :O

**Comment by uecasm** [comment]
Try increasing your render range before creating the colony.  I don't think it can claim unloaded chunks.

**Comment by drakray** [comment]
I was using a render of 16 and simulation of 12
I tried with render and simulation of 32, same result, 11x11 initial chunk claim

I also tried to just put a building outside of the visible claim, and got the "must upgrade" message, so it's not only a visual thing

**Comment by drakray** [comment]
Setting initialColonySize=13 claim an 11x11 too

**Comment by MotionlessTrain** [comment]
Possibly related to #8503?

**Comment by Raycoms** [comment]
Afaik not, this one is actually a code problem
