### ISSUE TITLE
Carpenter / Sawmill results in loud colony wide "saw" sound when crafting

### ISSUE THREAD

**Issue by shalazan** [ldtteam/minecolonies#8427]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.0.784-ALPHA (Also present in 1.0.798-ALPHA)

### Structurize Version

1.18.2-1.0.399-RELEASE

### Related Mods and their Versions

blockui-1.18.2-0.0.47-ALPHA
domum_ornamentum-1.18.2-1.0.50-ALPHA-universal
Forge Version 40.1.31

### Current Behavior

Whenever the carpenter at the sawmill crafts an item there is a "saw"/ cutting noise that plays at full volume anywhere in the colony

### Expected Behavior

The saw noise should play only locally to the sawmill and fade with distance

### Reproduction Steps

1. Have a sawmill (Mine is a level 1 Caledonia)
2. Teach them a recipe
3. Have them craft something
4. Listen for loud noise

### Logs

https://gist.github.com/shalazan/cb854940d9753483f155213e629384c7

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by shalazan** [comment]
This also appears to affect the woodcutter, It may be anyone crafting

**Comment by someaddons** [comment]
probably sounds being stereo not mono

**Comment by drakray** [comment]
Also, the sound seems controlled by "Friendly Creature", not "Blocks" (as I think it's the sawmill block that should do the sound?)
Still present in mc808/st411

**Comment by Catpoint789** [comment]
As of the new update (minecolonies-1.18.1-1.0.891-RELEASE/structurize-1.18.1-1.0.408-ALPHA) I am still experiencing this bug.

**Comment by Raycoms** [comment]
@someaddons did we forget porting it or so?

**Comment by someaddons** [comment]
probably, but we dont update 18.1 anyways

**Comment by uecasm** [comment]
I've been updating 1.18.1 with my changes, and they've been getting merged.  I don't think we've officially retired it yet...

**Comment by MotionlessTrain** [comment]
Raycoms asked me to stop making schematic PRs for 1.18.1, though

**Comment by Raycoms** [comment]
yeah, too many branches to handle.
