### ISSUE TITLE
Simple Quarry not being built properly by the quarrier

### ISSUE THREAD

**Issue by Letsdrajl** [ldtteam/minecolonies#8428]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [ ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.0.792-ALPHA

### Structurize Version

1.0.411-ALPHA

### Related Mods and their Versions

1. Forge Version: 40.1.47
2. Block UI Version: 0.0.48-ALPHA
3. Domum Ornamentum Version: 1.0.50-ALPHA
4. Direwolf20 1.18.2 Modpack Version: 1.4.1

### Current Behavior

Quarrier destroying blocks of the quarry
![2022-06-08_22 52 52](https://user-images.githubusercontent.com/70962271/172719695-797d6ac8-548a-4e0e-909c-44a27747a7ef.png)
Building a row of framed cobble and then destroying it
![2022-06-08_22 58 44](https://user-images.githubusercontent.com/70962271/172722184-06f2fff0-0573-4bed-8323-cc5dbf21226d.png)
Building another row 90° shifted
![2022-06-08_22 59 45](https://user-images.githubusercontent.com/70962271/172722280-6d13b048-2371-4df7-b4f3-248bc728ce1b.png)
![2022-06-08_23 00 20](https://user-images.githubusercontent.com/70962271/172722312-420ac627-7da4-4739-842d-d902bc2ac611.png)
Building down one layer with removing all placed blocks
![2022-06-08_23 02 21](https://user-images.githubusercontent.com/70962271/172722321-ba7eeef6-ae6d-4fd7-a240-c335058e9460.png)
![2022-06-08_23 03 18](https://user-images.githubusercontent.com/70962271/172722334-2e449b43-6ed3-4f12-a398-5475d6460c6b.png)

### Expected Behavior

A quarry being normally built, so it could be used

### Reproduction Steps

1. Build a simple quarry
2. Assign a quarrier
3. Supply resources
4. See the carnage begin

### Logs

https://gist.github.com/Letsdrajl/5cf356a6112d27b55c3f09c1115357bb

### Anything else?

I'm playing on the Modpack Direwolf20 1.18.2 with friends. The modpack is at the latest version and i had issues with the quarry before. I hoped it would be resolved with an update of the modpack since I read something about it in the issues.

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Hi, can you try reproducing this with the latest?

**Comment by Letsdrajl** [comment]
Ok, it seems to be fixed there, thanks. Then I just need to wait for the modpack to update.

Just wasn't sure if it was fixed since I didn't find any issues with this problem for my current Version.

**Comment by Raycoms** [comment]
Awesome!
