### ISSUE TITLE
Builder placement bug on official exploration server

### ISSUE THREAD

**Issue by talkingdragon** [ldtteam/minecolonies#8429]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

minecolonies-1.18.2-1.0.792-ALPHA.jar

### Structurize Version

structurize-1.18.2-1.0.411-ALPHA.jar

### Current Behavior

When builder needs to place in the solid placeholder, he dosent, and just sits there, no error messages or request

### Expected Behavior

he should place the default builder fill in, multiple types have been given to him

### Reproduction Steps

1. Set builder to any job requiring a placeholder fill in
2. watch him not place it
3. if you place it for him, he will work on the next block

### Logs

none?

### Anything else?

I have a theory, I have tried several fill in dirt types and i believe it has not got to do with that
when i set him to fill in a entire area with multiple dirt types in that biome, he had no problems placing the dirt areas
But in some of the patches he actually requested lush dirt and even peat
these are dirt type replacements for the biome I am in
I believe the builder is getting told to not place the standard dirt, but to place the biome equivalent
and then somewhere in the place code it is crashing
maybe the code is trying to force placing dirt, but he actually is being told by the game to place the lush
if u want to come test it, im talk1994 in the server
i can easily show u

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Saereth** [comment]
I'm having an issue with this as well in Inferno, I've manually verified there are no bedrock blocks in the schematic by spawning it in with the builders tool and then using the scan tool to check all blocks, as well as via NBTexplorer, no bedrock listed at all yet the builder still requesting bedrock. This is on the nether roof with the warped schematic

![image](https://user-images.githubusercontent.com/9200909/190012262-f2b7fbc9-5e5e-45d6-991c-72c74d5fc917.png)

**Comment by Raycoms** [comment]
Have you tried manually setting a block in the builder settings?

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by Raycoms** [comment]
That is @Saereth

**Comment by Raycoms** [comment]
I pushed a fix, but it might take a bit to reach 1.18.2.

**Comment by Saereth** [comment]
@Raycoms I tried to switch the block from dirt to netherack after you mention it and it wouldnt let me change it XD 
im currently on minecolonies-1.18.2-1.0.1026-ALPHA but I see there is an update so I'll update today and check
