### ISSUE TITLE
Exploration edition pack always generates same single player world

### ISSUE THREAD

**Issue by Talyda** [ldtteam/minecolonies#8430]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

minecolonies-1.18.2-1.0.792-ALPHA

### Structurize Version

structurize-1.18.2-1.0.411-ALPHA

### Current Behavior

Any time you open a single player world, it generates the exact same world

Remove the "biomesizepack" from the global pack\required data folder, and it generates a new seed each time

### Expected Behavior

New worlds generate with different seeds

### Reproduction Steps

Create new world, see same map.
Remove folder
create new world, see different map

### Logs

no logs

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
I will close this here, as this is not related to MineColonies, but to our packs. But I will check about it. Did this not happen in the other pack?

**Comment by Talyda** [comment]
I put it here cos when I went to the modpack page, this is where it took me for "issues"
No idea if it happened with the other packs, I just know with this one, remove that folder and you get new worlds each time, and can also do a superflat .
Couldn't do a superflat in one of the other packs, though I can't remember which (adventure maybe?)

**Comment by Raycoms** [comment]
I already fixed it locally, next pack update will have a fix

Sent from ProtonMail mobile

-------- Original Message --------
