### ISSUE TITLE
Minecolonies Log Report

### ISSUE THREAD

**Issue by HashedIce** [ldtteam/minecolonies#8431]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.0.777-ALPHA

### Structurize Version

1.0.401-RELEASE

### Related Mods and their Versions

Forge Version: 39.1.2

### Reproduction Steps

I dont really know what happen

### Logs

https://pastebin.com/Q4kixU2s

### Anything else?

no

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.
* So i should leave it blank?

**Comment by MotionlessTrain** [comment]
Update minecolonies. This has been fixed already
