### ISSUE TITLE
Worker chest bug

### ISSUE THREAD

**Issue by mmaster3101** [ldtteam/minecolonies#8432]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.18.2-1.0.792-ALPHA

### Structurize Version

1.18.2-1.0.411-ALPHA

### Current Behavior

Workers put materials in chests and then request said resource again.
-example: apiary request 1 bottle i give a stack of 64 apiary puts 63 in chest uses 1 then requests 1 bottle again
this issue happens with multiple buildings like miner bakery apiary and maybe others i havent noticed yet

### Expected Behavior

using materials they put in chests

### Reproduction Steps

give materials 
watch as it gets put in chest
and wait for the request for material to return

### Logs

no

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
Chests are purely decorative.  Workers ignore their contents and couriers should not be putting items into them.  Unless you actually meant racks?

**Comment by mmaster3101** [comment]
yeah thats what i meant and the workers put the stuff in the rack and then act like they forgot it exists
________________________________
Van: Gavin Lambert ***@***.***>
Verzonden: zaterdag 11 juni 2022 00:27
Aan: ldtteam/minecolonies ***@***.***>
CC: mmaster3101 ***@***.***>; Author ***@***.***>
Onderwerp: Re: [ldtteam/minecolonies] Worker chest bug (Issue #8432)


Chests are purely decorative. Workers ignore their contents and couriers should not be putting items into them. Unless you actually meant racks?

**Comment by Raycoms** [comment]
We would have to know exactly for which workers and which resources, the problem is most likely that after dumping 63, they want the full 64 again and don't accept partial

**Comment by Raycoms** [comment]
stale
