### ISSUE TITLE
Any minecolony specific blocks float above building schematic

### ISSUE THREAD

**Issue by CherryStar1011** [ldtteam/minecolonies#8440]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.0.428-RELEASE

### Structurize Version

1.0.342-RELEASE

### Related Mods and their Versions

1. Forge 1.18.1
2. Optifine 1.18.1 H6
3. Block UI 1.18.1 0.043-ALPHA
4. Domun Ornamentum 1.18.1 1.0.39-ALPHA
5. Multi-Piston 1.18.1 1.2.2-ALPHA

### Current Behavior

Any time I try and place a Minecolonies colony block (EX. Lumberjack, University, School etc,) any of the special Minecolony blocks do not appear beside the others when being placed (EX. Roof tiles, Any Framed block) and requires to look up into the sky and Tetris your way through to figuring out what the final product will look like.

### Expected Behavior

All blocks, Vanilla Minecraft blocks and any new blocks added, should be shown beside each other and able to discern the final product showing all framed blocks, all roof blocks, glass blocks, etc, close by.

### Reproduction Steps

1. Get any Minecolonies block that requires building
2. Place a builders hut (As example, so far works with almost any Minecolonies source block requiring workers to build it), use build tool to build and choose medieval dark oak for best results
3. Set level to 5 for best visibility of issue
4. Look above placed structure
5. Blocks are floating estimated 2 to 15 blocks above highest point of build

### Logs

https://gist.github.com/CherryStar1011/74a208cf7f5386a2ff4047e61f1f5afc

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
You are almost 400 versions outdated. Please update to the newest alpha. These optifine bugs have been fixed quite some time ago already.

**Comment by CherryStar1011** [comment]
Alright, is there any way to move my current Minecolonies file to newest alpha without messing a chunk of things up or do I just have to recreate my current file?

**Comment by MotionlessTrain** [comment]
You can just replace the jar files of minecolonies and its dependencies with the newer versions in the mods folder. Look at the changelog of the minecolonies version on curseforge to find out what versions you need of the dependencies.

Your world should still work after upgrading

**Comment by CherryStar1011** [comment]
Will it continue to work with 1.18.1?

**Comment by MotionlessTrain** [comment]
Yes. As long as you keep using 1.18.1 versions, there shouldn't be an issue, since you are playing 1.18.1 already

**Comment by CherryStar1011** [comment]
Alright, thank you for your time, I'll close this now!

**Comment by MotionlessTrain** [comment]
No problem!
