### ISSUE TITLE
Minecolonies Official - Adventure - Create Your Colony - v1.10 - Builder Error latest.log

### ISSUE THREAD

**Issue by Lightshardz** [ldtteam/minecolonies#8442]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.18.1-1.0.777-ALPHA

### Structurize Version

1.18.1-1.0.401-RELEASE

### Related Mods and their Versions

1. Minecolonies Official - Adventure - Create your Colony v1.10 (current)
2. Forge Version - 39.1.2
3. Additional Client Mod - More Overlays Updated - moreoverlays-1.20.5-mc1.18.1

### Logs

https://pastebin.com/BY1WrUyN

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
Update minecolonies. This has been fixed already

You can just replace the mod file inside of the mods folder

**Comment by Lightshardz** [comment]
@MotionlessTrain Thank you very much! We are following the Minecolonies Official versions through Curseforge, so either we will wait for that to be officially updated or I will get with the server clients and see if they want to try to manually handle updating the server and clients to be non-compliant with the official modpack.
