### ISSUE TITLE
the problem with the icon above the residents

### ISSUE THREAD

**Issue by eqorfox** [ldtteam/minecolonies#8450]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.0.737-RELEASE

### Structurize Version

1.0.737-RELEASE

### Current Behavior

the icon above the residents stretches to the full scree
![2022-06-17_11 09 04](https://user-images.githubusercontent.com/40038300/174256723-8f2d7b92-8185-446f-9770-1c4bf1db83d6.png)
![2022-06-17_11 09 07](https://user-images.githubusercontent.com/40038300/174256731-1090c4a5-4857-4fc2-8ca9-19c9aec913a9.png)
![2022-06-17_11 09 09](https://user-images.githubusercontent.com/40038300/174256732-ae9bb363-c81b-4178-97cd-c81a2c84169e.png)
n

### Expected Behavior

the icon shouldn't stretch like that

### Reproduction Steps

residents were initially with such a problem

### Logs

https://gist.github.com/eqorfox/d0dad12beaa3bd77fe4c4e2ec16ba92c

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
It's not a minecolonies issue, one of your other mods causes it.  Probably oculus
Or rubidium (think that was the name)
