### ISSUE TITLE
JEI says the stonemason can craft stone tools

### ISSUE THREAD

**Issue by SeeTwoDev** [ldtteam/minecolonies#8453]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

minecolonies-1.18.2-1.0.806-ALPHA

### Structurize Version

structurize-1.18.2-1.0.411-ALPHA

### Related Mods and their Versions

jei-1.18.2-9.7.0.195

### Current Behavior

JEI Lists that the stonemason can craft stone tools (which might make sense since its stone based...) , while it can't.

### Expected Behavior

JEI should not show the stonemason at all

### Reproduction Steps

Check the recipes for stone tools.

### Logs

---

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
This works as expected after #8439 is merged.
