### ISSUE TITLE
[1.18] crash using builder tool

### ISSUE THREAD

**Issue by Saereth** [ldtteam/minecolonies#8454]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

minecolonies-1.18.2-1.0.824-ALPHA

### Structurize Version

structurize-1.18.2-1.0.411-ALPHA

### Related Mods and their Versions

Forge Version: 40.1.41

### Current Behavior

Using the structurize tool is crashing with certain buildings under these conditions:
Jar schematics disabled, warp folder extracted and placed in the correct location. 

### Expected Behavior

I would expect the menu to pull back up to be able to click build after positioning

### Reproduction Steps

Place a baker hut (this happens with a few other buildings as well) tell it to use the build tool
align the structure how you like, but back out of the build menu/back off
right-click on the baker block again to bring the menu back up... crash

University immediately crashes if you try to use the build tool at all, never even gets to the preview
(Separate crash log for university specifically, similar error though, https://www.toptal.com/developers/hastebin/hagepayoyi.properties )

### Logs

https://www.toptal.com/developers/hastebin/ezugamuxub.yaml

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Did you disable jar schematics?

**Comment by Saereth** [comment]
Yep, jar schematics disabled with the warp folder extracted from the minecolonies jar and moved to structurize/schematics/warped as per the wiki instructions to enforce warped theme (Will be adding some more custom nether themed options later)

**Comment by Raycoms** [comment]
Currently got another new theme coming up for the nether (wicked). This is a known issue with disabling jar schematics, I'll see if I can find a workaround for now.

**Comment by Raycoms** [comment]
Can you, just for tests sake, try to name the "Warped" folder to "wooden" and see if it still causes this issue? I feel it's because of the default style setup we got internally.

**Comment by Saereth** [comment]
No luck unfortunately, same error with it named wooden

**Comment by Saereth** [comment]
Just an update on this, brought some testers on to try the pack and of course they all immediately crashed with the build tool trying to place their town halls despite us not having an issue discord. I made a new world and tried again and yeah it does it everytime with the town hall block. New log just in case anything is different... I did update minecolonies so we're on the latest again as of this posting. 

[crash-2022-06-23_16.55.58-client.txt](https://github.com/ldtteam/minecolonies/files/8970944/crash-2022-06-23_16.55.58-client.txt)

**Comment by MotionlessTrain** [comment]
Could you try to put one (decoration) blueprint in the schematics folder? That is the place where the default well, and the "dig" and "fill" schematics are. Just in case the build tool expects a schematic there to select by default

**Comment by Saereth** [comment]
![image](https://user-images.githubusercontent.com/9200909/175404561-fbb81a3e-649f-4686-bd9d-f8a3d69adaf5.png)
I think you nailed it! Its working now!

**Comment by Raycoms** [comment]
Awesome, that's a great workaround!

**Comment by Raycoms** [comment]
(I'm reworking all of this at the moment anyway, so that this won't be necessary anymore anyway)

**Comment by Raycoms** [comment]
This is solved in 1.19 now will soon be merged into 1.18 too
