### ISSUE TITLE
[1.18] Raids do not seem to be working

### ISSUE THREAD

**Issue by Saereth** [ldtteam/minecolonies#8455]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

minecolonies-1.18.2-1.0.824-ALPHA

### Structurize Version

structurize-1.18.2-1.0.411-ALPHA

### Related Mods and their Versions

41.0.41

### Current Behavior

Raids do not seem to be working. I noticed after some time a raid never happened so I even used to command to make one happen and no enemies ever spawn. This is with set allow to spawn air set to true, on the roof of the nether in case that has any bearing. 

### Expected Behavior

I would expect raids to occur 

### Reproduction Steps

create a colony on the nether roof, attempt to use the command to start a raid, it warns you that the raid is happening and then no enemies ever spawn. I am definitely not in peaceful and other hostile mobs are spawning around.

### Logs

N/A

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
Raiders can't spawn on top of the nether

This gave issues otherwise with colonies which were just below the nether roof. Raiders spawned on top of the nether and couldn't ever reach the colony

**Comment by Raycoms** [comment]
They should spawn normally if the colony is inside the nether area and not on the top of it.

**Comment by Saereth** [comment]
Yeah in this pack you can get above/below the nether roof fairly easily, mobs as well so it wouldnt be a problem here persay but I understand the issue under normal circumstances. Would you entertain the idea of a config option if I were to submit a PR for it? (off by default obviously)

**Comment by Raycoms** [comment]
Wouldn't be a problem for me @someaddons what do you think?

**Comment by someaddons** [comment]
Its kinda messy, the world height checks are within block position searching code, not raid-related code. Not sure if thats really worth it for a spawn place we want to prevent xD
