### ISSUE TITLE
Last.log

### ISSUE THREAD

**Issue by ElectricPanda14** [ldtteam/minecolonies#8462]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.18.1

### Structurize Version

1.18.1

### Logs

https://gist.github.com/ElectricPanda14/0cefe3a9d2a02d310e7637012c1a726a

### Anything else?

this is my nether miners having this issue. i have 4

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
You're over 300 version numbers out of date - update and you will probably find they are fixed
