### ISSUE TITLE
Some DO custon recipies not craftable by crafter

### ISSUE THREAD

**Issue by Wetz1990** [ldtteam/minecolonies#8464]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.0.806-ALPHA

### Structurize Version

1.0.411-ALPHA

### Related Mods and their Versions

Official Minecolonies Exploration Edition

### Current Behavior

There are several blocks from DO that no crafter can craft.
This is DO blocks that only have 1 crafting ingredience.

Examples i have encountered so far:
1: The dirt stair from DO that requier just 1 dirt block. No crafter can learn this.
2: The Wheat extra slab/stair, this requiers 1 wheat extra block, but no crafter can learn this.
3: The Block of gold trapdoor, Requiers 1 gold block, but no crafter than learn this,

### Expected Behavior

That some crafter can learn these in their custon recipies.

### Reproduction Steps

Try to give crafter 1 dirt, wheat extra or gold block as the only material in the custon recipies.

### Logs

https://gist.github.com/Wetz1990/4a7ddd93b2ca0f4e4bc3269fed85fff9

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
did you try the mechanic?

**Comment by Wetz1990** [comment]
yes i did, he cant do it.

**Comment by Raycoms** [comment]
oh, strange

**Comment by Wetz1990** [comment]
![image](https://user-images.githubusercontent.com/33292786/174771318-69789f5a-34d7-4f62-9a33-9ced606f7a46.png)
![image](https://user-images.githubusercontent.com/33292786/174771352-16054884-c6da-4dee-9ed0-20bc675e5ac1.png)
