### ISSUE TITLE
The server crashed when the player attacked mercenaries

### ISSUE THREAD

**Issue by mcmso** [ldtteam/minecolonies#8470]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [ ] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.16

### MineColonies Version

structurize-1.16.5-1.0.392-RELEASE.jar

### Structurize Version

minecolonies-1.16.5-1.0.830-BETA.jar

### Current Behavior

Attacking a mercenary will crash the server

### Expected Behavior

I want to be able to fix him

### Reproduction Steps

Attacking a mercenary will crash the server

### Logs

https://paste.ubuntu.com/p/TyzDSDSd4C/

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by AnthonyNGarcia** [comment]
Was not able to reproduce this issue on 1.16.5 (or a later version, for that matter). Can you clarify what weapon you used to attack the mercenary? And please list out all the mods in case there is some mod incompatibility that may have caused this crash?
