### ISSUE TITLE
[1.18.2] Builder crashes minecraft server.

### ISSUE THREAD

**Issue by VKirbyatev** [ldtteam/minecolonies#8475]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.0.737-RELEASE

### Structurize Version

1.0.399-RELEASE

### Related Mods and their Versions

1. Forge: 40.1.52
2. BlockUI: 0.0.47-ALPHA
3. Domum Ornamentum: 1.0.50-ALPHA-universal
4. Multipiston: 2-1.2.13-ALPHA

OTHER:
1. openjdk 18-ea 2022-03-22
2. Platform: Ubuntu 22.04 LTS

### Current Behavior

When I start server and join game, I got "BUILDERS_NAME started work on BUILDING" message and then server crashes.

I gave to builder a scissors, and he removed all grass totally fine.
But after I gave him wood shovel, he probably tried to remove dirt, and server crashed.

I tried to take shovel from him, but server crashes instantly, when I got connected.

### Expected Behavior

I expected that he will remove dirt, and my server won't crash.

### Reproduction Steps

1. Generate world with 4222124689661003 seed.
2. Start build builder's hut near +- -88.74, 69.00, 42.50 coordinates.
3. Give builder scissors, then shovel.
4. Wait before it crashes.

### Logs

https://pastebin.com/s4rUWNr7

### Anything else?

1. Server start command 
`nice -10 java -server -Xmx4096M -Xms2048M @user_jvm_args.txt @libraries/net/minecraftforge/forge/1.18.2-40.1.52/unix_args.txt --world ../worlds/WORLD_NAME --nogui "$@"`

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by someaddons** [comment]
you're not running the latest alpha, make a new report if you can reproduce it on that

**Comment by Raycoms** [comment]
Can you try the latest alpha / beta?

Sent from Proton Mail mobile

-------- Original Message --------
