### ISSUE TITLE
no translation

### ISSUE THREAD

**Issue by TimLiz** [ldtteam/minecolonies#8482]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.16

### MineColonies Version

1.16.5-1.0.858-BETA

### Structurize Version

1.16.5-1.0.392-RELEASE

### Current Behavior

![Снимок](https://user-images.githubusercontent.com/88791919/175964156-fcfc18fe-8c0c-42bf-961e-1d639e3fa302.PNG)

There is no translation

### Expected Behavior

![Снимок](https://user-images.githubusercontent.com/88791919/175964156-fcfc18fe-8c0c-42bf-961e-1d639e3fa302.PNG)

There is no translation

### Reproduction Steps

1. Start building house

### Logs

Server or client log?

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
You can add missing translations yourself at https://crowdin.com/project/minecolonies
