### ISSUE TITLE
Shape tool not working

### ISSUE THREAD

**Issue by furret-sleuth** [ldtteam/minecolonies#8485]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.16

### MineColonies Version

1.0.858-BETA

### Structurize Version

1.0.392-RELEASE

### Current Behavior

The shape tool fails to build structures/clean land with the chat message "Could not build CUBE: schematic missing!"
The chat message is on the line 5231 of the latest.log

### Expected Behavior

The shape tool should create a build request for the builder and they sould start working on the shape.

### Reproduction Steps

Use a shape tool to create a cube with air as fill blocks, click the green tick, choose a builder and click "build". The build request does not create with an error message.

### Logs

https://gist.github.com/furret-sleuth/6d8342299a2a211d3bc3c4bf8d902364

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Should be fixed now
