### ISSUE TITLE
Option "Request fertilizer" Off does not work

### ISSUE THREAD

**Issue by uhloin** [ldtteam/minecolonies#8494]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.0.872-BETA

### Structurize Version

1.0.411-ALPHA

### Current Behavior

2 farmers requests fertilizer when option "Request fertilizer" in their both Farms is in state "Off"

### Expected Behavior

Stop requests for fertilizer

### Reproduction Steps

Build 2 farms and 2 farmers, turn off option

### Logs

-

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
did you cancel the open requests after turning it off?

**Comment by uhloin** [comment]
Only when I discover clipboard. Make additional item just to say "cancel" is nonsense. If request received from dialog then accept/cancel should be via the same dialog. But the dialog has only weird choices "I will work on it", "Please remind...", "That has to do...", "Skip..." - all 4 sounds like "may be", "may be", "may be" and "may be".

**Comment by MotionlessTrain** [comment]
"That has to do for now" is the cancel button

**Comment by uhloin** [comment]
Please do not write "Cancel", otherwise someone might guess what author of GUI meant to say and someone might understand what he doing. GUI must be original and mysterious.

**Comment by MotionlessTrain** [comment]
The GUI tries to simulate a conversation. "Cancel" is not really an answer to a conversation.

Besides, the text "Cancel" has the issue that it is not clear what it cancels, just that screen or the entire request?

(There is another cancel button by the way, which may be a bit more clear: If you go to the open requests tab of the user, the second tab from the top, there is a cancel button there as well on the request)

**Comment by uhloin** [comment]
If simulate conversation then
"Please remind..." - is OK
"Give me more details..." - is OK
"I will work on it" and "Skip chit-chat" - are bad because do the same as "Please remind" (?)
"That has to do..." - is VERY bad, it sounds simultaneously like order (do itself immediately!) accept, reject, or accept with sarcasm and real reject. When citizen asks for cure carrot or potato this has not sense at all.
Should be: "Don't ask again".

**Comment by uecasm** [comment]
"Remind me later" = go away for now, but tell me again later
"Give me more details" = show me details right now
"I will work on it" = OK (acknowledge but don't delay or show details)
"That has to do" = Cancel (i.e. "you will have to make do with what you already have")

**Comment by Raycoms** [comment]
Anyway, there is an actual cancel inside the "more detail" and the request list of the farmer.

**Comment by uhloin** [comment]
Thank you all for explanation!
