### ISSUE TITLE
Guard tower of Level 4 has 2 beds but does not allow to hire 2nd guard

### ISSUE THREAD

**Issue by uhloin** [ldtteam/minecolonies#8495]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

minecolonies-1.18.2-1.0.872-BETA.jar

### Structurize Version

structurize-1.18.2-1.0.411-ALPHA.jar

### Current Behavior

subj

### Expected Behavior

home in tower as many guards as beds

### Reproduction Steps

subj

### Logs

-

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
That is intended. Guard towers can only have one guard at max.

Beds in guard towers are decorational only, the amount of beds in a guard or barracks tower has nothing to do with the amount of guards in the tower

**Comment by Thodor12** [comment]
What MotionlessTrain said, the amount of beds doesn't dictate the guard amount, closing this issue

**Comment by uhloin** [comment]
Oh, got it. Guard has 2 beds and sleep on his ass on the grass... because both beds are just decorations as intended.
