### ISSUE TITLE
Eternal Steak from Artifacts gets voided when fed to Citizens

### ISSUE THREAD

**Issue by StrangerSon71** [ldtteam/minecolonies#8502]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.0.872

### Structurize Version

1.0.411

### Related Mods and their Versions

Artifacts 1.4.0

### Current Behavior

When you right click on a Citizen with the Eternal Steak from Artifacts, it gets fed to said Citizen and permanently lost.

### Expected Behavior

Either A: Just opening the Citizen's inventory and not interacting with the Steak, or B: Feeding the Citizen without consuming the Steak.

### Reproduction Steps

1. Right click on a Citizen with an Eternal Steak or Everlasting Beef

### Logs

Exceeded the pastebin limit, probably not relevant anyway.

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
This is expected.  Don't do that.

**Comment by StrangerSon71** [comment]
I did it accidentally. Twice.

**Comment by marchermans** [comment]
THere is not really something we can do here.
Our citizens are no players so player specific logic for those items jsut does not apply, it is a limitation to the food system on mojangs end.

Closing since this is not fixable.

**Comment by StrangerSon71** [comment]
So there's no way to just block the feeding action for that particular item? So when you right click on a Citizen with one it isn't lost and the Citizen isn't fed?

**Comment by marchermans** [comment]
No sorry there is no proper way to detect that, outside of just black listing it.
We might be able to look into this in the future, by using some form of tagging system, but that is currently not yet possible.

**Comment by StrangerSon71** [comment]
"just black listing it" is what I'm asking for.

**Comment by Raycoms** [comment]
We'd be open to accept PRs to make a tag blacklist for interaction items. But in general it's a "mod compat request"

**Comment by Sandriell** [comment]
Personally I wish the entire right click item interaction could be turned off. I have never once intentionally given them something using that method.

**Comment by Thodor12** [comment]
We don't have to disable an entire feature because it causes 1 problem with a random mod which we do not have any tie-ins to

**Comment by StrangerSon71** [comment]
No, but a config would be nice. I've accidentally given them regular food to, and never done it on purpose. It's a good thing I never had gapples in my hotbar while dealing with citizens.
