### ISSUE TITLE
changes in config file do not effect the game

### ISSUE THREAD

**Issue by Retsamikit** [ldtteam/minecolonies#8503]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.18.2-1.0.877

### Structurize Version

1.18.2-1.0.411-ALPHA

### Current Behavior

changes in config like workersalwaysworkinrain = true do not effect the game. the workers still pause with rain. 
[serverconfig\minecolonies-server.toml]

### Expected Behavior

I expect that changes in config effect the game, like in versions before.. :-)

### Reproduction Steps

edit config, save
start minecraft.. 
start game
go to builder
set rain
watch him going away

### Logs

config: https://justpaste.it/53219

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
When you edit the config, do you shut down the server, wait for it to be down, edit, and start up?

**Comment by MotionlessTrain** [comment]
They're not the only one with this issue by the way. I have seen quite a few people saying that the builderbuildblockdelay and the blockminingdelaymodifier didn't seem to work, and they were shutting down the server and edited afterwards (we asked that to them).
That, the issue I mentioned and this issue together seem like there is something wrong with the config loading

**Comment by Raycoms** [comment]
The delay stuff doesn't have that huge of an influence as the levels still make a big part of the speed.

**Comment by Retsamikit** [comment]
I do not play on a server, I forgot. None of the modifications in config do work. Yes, I edit the config shutting down the game.
If I would, setting changes will go lost, I know that. I play MC for two years now, its only first install with this minecaft version.
All changes in my "old" versions do work fine. (1.12.2)

**Comment by dhouck** [comment]
A few days ago I turned on working in rain (it’s an underground colony; I can’t even *tell* it’s raining and it feels thematically off for them to stop because of weather), with the server down, and it didn’t work.  But then I cancelled some of what the builders were doing and they started again.  I think it might somehow be saving the worker state and not restoring it.
