### ISSUE TITLE
Armor stand's with armor that has custom NBT are not accepted for buildings

### ISSUE THREAD

**Issue by Saereth** [ldtteam/minecolonies#8506]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

.18.2-1.0.879-ALPHA

### Structurize Version

1.19-1.0.417-ALPHA

### Related Mods and their Versions

Forge 40.1.54

### Current Behavior

We recently added the mod Spoorn Armor Attributes to the pack and it automatically generates bonus stats/nbt data on armor when crafted, so the builder is not recognizing the armor since adding that mod. If you craft the armor and hit fulfill on the request fast enough (the stats generate on tick in the inventory) the builder will accept it but then as soon as the stats generate they wont use it/see it as valid and go back to requesting it. This currently makes it impossible to complete someof the buildings that require the armor stand with armors.

I have opened an issue with the mod author as well to request a blacklist
https://github.com/spoorn/SpoornArmorAttributes/issues/6

### Expected Behavior

The builder should accept the item regardless of nbt data and complete the structure

### Reproduction Steps

install Spoorn Armor attribute mod, make iron armor and try to give it to a builder to complete a town hall (warped tier 3) or any building that requires the armor+armorstand

### Logs

No crash logs for this

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
That is the same problem as with shulker boxes. It's hard. There are items that fully change based on nbt (potions, books, etc) such that giving the worker wrong items (i.e. wrong nbt) could allow abusing this to cheat in enchantments or in a cheaty way strip enchantments, or in a cheaty way fulfill a request with the wrong item (i.e. the builder needs potion x, but gets just potion y)

**Comment by MotionlessTrain** [comment]
Maybe the same workaround works as the similar nbt issue with clocks when Quark is installed: Quark changes the clock and compass item when it hits your inventory, so if you drop it out of the crafting table on the ground in front of the builder, the builder can pick it up without it having a chance to get modified by Quark
(The easier workaround is to have teach the clock or compass recipe to the mechanic, or in this case the armour recipe to the blacksmith or fletcher, if you have those)

**Comment by Saereth** [comment]
yeah I tried having the colonist craft the armor but it changes in the builder's inventory as well not just a player inventory so that particular work around was no good. I do see the complication though with this issue for sure.

**Comment by Raycoms** [comment]
Will connect this to https://github.com/ldtteam/minecolonies-features/issues/135
