### ISSUE TITLE
Config file not opening properly. Or incomplete data?

### ISSUE THREAD

**Issue by docduke1** [ldtteam/minecolonies#8508]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.18.1-1.0891-Release

### Structurize Version

1.18.1-1.0.408-Alpha

### Related Mods and their Versions

- Forge 1.18.1-39.1.0 
- Blockui 1.18.2-0.0.48-Alpha
- Docum_orn 1.18.1-1.0.39-Alpha
- Multi-Piston- 1.18.1-1.2.9-Alpha
- jei- 1.18.1-9.4.1.172
- journeymap 1.18.1-5.8.1
- morevillagers-FORGE-1.18.1-3.1.2
- worldedit-mod-7.2.9

### Current Behavior

When attempting to modify config settings, (to decrease or turn-off empty colonies spawn rate/range) the config files in AppData\Roaming\.minecraft\config only seem to be opening incomplete files. 

Both Client and Common configs have 10 lines or less. 

Have attempted to delete all mods, configs, and fresh install; while also trying different versions of minecolonies plus all required mods many times. 

Attempted alternative forge verisons with applicable mods.

Have Configs been replaced or mainly disabled in these versions?
![common](https://user-images.githubusercontent.com/64733103/179616508-049eb996-dd84-42d3-a1f5-5c6e07350c9d.png)
![client](https://user-images.githubusercontent.com/64733103/179616551-169c44e2-cb8a-4f64-a303-c26b396b8ccd.png)

### Expected Behavior

Previous versions were at least able to modify configs. Hoping to do it in this version. At least to get rid of colonies spawning so close. 

### Reproduction Steps

honestly unsure. happens everytime and any version. 

### Logs

[15:17:53] [modloading-worker-0/WARN]: Configuration file C:\Users\...\AppData\Roaming\.minecraft\config\minecolonies-client.toml is not correct. Correcting [15:17:53] [modloading-worker-0/WARN]: Incorrect key gameplay was corrected from null to its default, SimpleCommentedConfig:{}.

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
That's normal.  Most of the configuration is in the serverconfigs in your save directory.

If you have support questions like this, it's best to ask in the Discord first.

**Comment by docduke1** [comment]
Copy that
