### ISSUE TITLE
Workers replace vanilla tools with those from other mods!

### ISSUE THREAD

**Issue by GonzaloGamenara** [ldtteam/minecolonies#8510]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

minecolonies-1.18.2-1.0.889-RELEASE

### Structurize Version

structurize-1.18.2-1.0.411-ALPHA

### Related Mods and their Versions

[Mods.txt](https://github.com/ldtteam/minecolonies/files/9164105/Mods.txt)

### Current Behavior

Workers ask for very hard to get tools from other mods ("Ventium Shears") and do not accept vanilla tools like vanilla scissors or vanilla shovels

### Expected Behavior

Workers must accept the tools by TAG, that is, any shovel or scissors...

### Reproduction Steps

Install the mods I own and try to build the builder's shack

### Logs

https://gist.github.com/BlackJellyBeans/443c249f0e43e92645703001a1274e6c

### Footer

:

**Comment by Talyda** [comment]
If you check this page on the wiki:
https://wiki.minecolonies.ldtteam.com/source/systems/worker
it has a chart for what levels of tools the workers will use.
They ask for a variety of tools, vanilla and modded, for whatever level of tool they can use. They will use vanilla ones, just put them in their inventory. If you click the three little lines to the bottom left of the request window, it will show you what they are asking for (minimal and maximum levels)
If you need support, discord is a much better place to check before making a bug report =)
