### ISSUE TITLE
Error with lumber jack and dynamic trees

### ISSUE THREAD

**Issue by JustinDLlacuna** [ldtteam/minecolonies#8511]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

minecolonies-1.18.2-1.0.889-RELEASE

### Structurize Version

structurize-1.18.2-1.0.411-ALPHA

### Related Mods and their Versions

1. Dynamic Trees: DynamicTrees-1.18.2-0.11.0-Alpha2

### Current Behavior

When lumber jack is given a DynamicTrees sappling, an error occurs. 

Unrelated to the error: the lumberjack cuts DynamicTrees trees from the top, and not the bottom.

### Expected Behavior

Lumberjack should cut DynamicTrees tree from the bottom, and then plant a DynamicTrees sappling.

### Reproduction Steps

1. Give Lumberjack a DynamicTrees sappling.
2. Error occurs.

As for tree cutting behavior, I am unsure how to reproduce.

### Logs

https://pastebin.com/DXcmdpi3

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
There is no dynamic tree compat as of 1.18.2 yet. Yes

**Comment by Moobien** [comment]
> There is no dynamic tree compat as of 1.18.2 yet. Yes

then why do the Dynamic trees options show up in the forester ui if there is no compat for it?

**Comment by Raycoms** [comment]
Because they register those properly.

**Comment by Moobien** [comment]
> Because they register those properly.

Better add the compat then :p

**Comment by Raycoms** [comment]
> > Because they register those properly.
> 
> Better add the compat then :p

Go ahead then

**Comment by Mungoid** [comment]
@JustinDLlacuna  

Luckily DynamicTrees has a recipe to create vanilla saplings (Bucket of dirt and a seed). So what you can do instead is get rid of all dynamic trees within a radius of the LJ hut and plant some saplings instead. Also go into LJ settings and only allow planting of the specific saplings you want grown, and disable every DynamicTree seed. 

This seems to work for me and you dont have to mess with starting a new world or disabling any mods.
