### ISSUE TITLE
Latest MineColonies version crashes on start (Minecolonies failes to load correctly)

### ISSUE THREAD

**Issue by semillakan6** [ldtteam/minecolonies#8512]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

minecolonies-1.18.2-1.0.889-RELEASE.jar 

### Structurize Version

structurize-1.18.2-1.0.411-ALPHA

### Related Mods and their Versions

1. Forge Version 40.1.68
2. BloackUI blockui-1.18.2-0.0.55-ALPHA
3. MultiPiston multi-piston-1.18.2-1.2.13-ALPHA+(1)
4. Domun domum_ornamentum-1.18.2-1.0.55-ALPHA-universal

### Reproduction Steps

Try to start the game

### Logs

https://pastebin.com/LcrbN8Xx

### Footer

One of the things that could be causing it, can be that multi-piston has a (1) on the file name and somehow that messes with it

**Comment by Talyda** [comment]
Try downgrading forge to .62 (I think it is 62 that works!)

**Comment by Raycoms** [comment]
Not MineColonies,it's a problem with farmers delight:
Exception message: org.spongepowered.asm.mixin.throwables.ClassMetadataNotFoundException: vectorwing.farmersdelight.common.registry.ModRecipeTypes

**Comment by Talyda** [comment]
For my own education (cos I am still trying to learn these things) how does farmers delight stop minecolonies from loading correctly?

And sorry @semillakan6 for my bad advise!

**Comment by semillakan6** [comment]
Welp it was Farmer's Delight I had an older version this is embarrasing I had been staring at the crash logs for 3 hours please someone delete this and sorry for wasting time

**Comment by MotionlessTrain** [comment]
> For my own education (cos I am still trying to learn these things) how does farmers delight stop minecolonies from loading correctly?

It looks like Farmer's delight added a mixin to modify minecraft (and apparently minecolonies) code.
When minecolonies was being loaded, the mixin was applied, and crashed minecraft
