### ISSUE TITLE
Barracks building claim not taken into account for hasGuardBuildingNear

### ISSUE THREAD

**Issue by Aalandriel** [ldtteam/minecolonies#8514]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

minecolonies-1.18.2-1.0.824-ALPHA.jar

### Structurize Version

structurize-1.18.2-1.0.411-ALPHA.jar

### Related Mods and their Versions

N/A

### Current Behavior

In PR [#7338](https://github.com/ldtteam/minecolonies/pull/7338) the special check for the barracks building in relation to the hasGuardBuildingNear check was removed. This results in the claim radius of the Barracks **tower** being used to calculate the guarded area, instead of the Barracks' claim radius.

### Expected Behavior

hasGuardBuildingNear should used the claim radius of the Barracks.

### Reproduction Steps

Build barracks away from the influence of guard towers.
Build houses and work places 1-2 chunks away from a guard tower but within the claim range of the Barracks
Expected outcome: 
Citizens are happy with the security of their homes and work places

Actual outcome
Citizens are only happy with the security if building are in the same chunk as a Barracks tower.

### Logs

n/a

### Anything else?

Discord discussion:
From: https://discord.com/channels/472875599422291968/486940969737125922/1000069995004440606
Till: https://discord.com/channels/472875599422291968/486940969737125922/1000365028123349052 

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
To add to this, barracks towers have a claim radius of 0 chunks, so they don't really make anyone happy at all (since most of the claim is in the barracks anyway)

**Comment by Moobien** [comment]
Barracks doesn't contribute to colonists feeling safe from memory

**Comment by Aalandriel** [comment]
Not since the PR mentioned in the description. Before that it did count.

**Comment by Moobien** [comment]
> Not since the PR mentioned in the description. Before that it did count.

Ahhh

**Comment by Raycoms** [comment]
fixed
