### ISSUE TITLE
1.18.2 Build tool not showing preview for buildings

### ISSUE THREAD

**Issue by luispereira223** [ldtteam/minecolonies#8515]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.0.889-RELEASE

### Structurize Version

minecolonies-1.18.2-1.0.889-RELEASE.jar

### Related Mods and their Versions

Forge Version : 40.1.67

### Current Behavior

Building tool does not show a preview of building.

### Expected Behavior

To show the preview of the building

### Reproduction Steps

1. get the fisher huts block
2. use build tool and change to fishers block
3. right click a block to place building

### Logs

https://pastebin.com/R2EArBFv

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
There are multiple reasons why previews may be invisible:
- Sometimes when you switch worlds and the build tool was still open, the build tool would show the preview at the same coordinate as it was in the other world. Hitting the "X" and bringing up the preview again solves that
- Fabulous graphics can mess with the schematic previews. We recommend using fast or fancy graphics instead
- The mod "tempad-forge" seems to give problems with the preview as well. Try again without that mod.

Also, the log you sent is not a minecraft log, but a log from the minecraft launcher you use, which seems to be cracked by the looks of it

**Comment by Songbird0** [comment]
Hi all!

Sorry for upping this topic but I think it's important.

> Fabulous graphics can mess with the schematic previews. We recommend using fast or fancy graphics instead

I fixed the same problem with MineColonies 1.0.978-RELEASE, so this solution works for Minecraft 1.16.5 too. Thank you so much!
