### ISSUE TITLE
Female Shepherd missing one Leg and one Arm just on Nordic Style

### ISSUE THREAD

**Issue by SeteshSub** [ldtteam/minecolonies#8516]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.18.2-1.0.889-RELEASE

### Structurize Version

1.18.2-1.0.411-ALPHA

### Related Mods and their Versions

1. Forge: 40.1.27
2. BlockUI: 1.18.2-0.0.55-ALPHA
3. 1.18.2-1.0.50-ALPHA

### Current Behavior

The Female Sheperd missing one Leg and one Arm on Nordic Style of Citizens
![2022-07-23_14 50 25](https://user-images.githubusercontent.com/109860478/180607237-b7c5ee60-3440-4051-80a4-0cc6d41beda7.png)
.

### Expected Behavior

I dont know what happend?^^

### Reproduction Steps

Just use Nordic Style of Citizens and a Female Sheperd (i tried a Male Sheperd, he has both).

### Logs

https://gist.github.com/SeteshSub/c588138eccbdc03e03d9ea9434c75b7b

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
fixed
