### ISSUE TITLE
Inventory (hut/block inventory, using the button marked "Inventory") isn't seen in their overall hut inventory.

### ISSUE THREAD

**Issue by crysallis** [ldtteam/minecolonies#8521]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

minecolonies-1.18.2-1.0.893-ALPHA

### Structurize Version

structurize-1.18.2-1.0.411-ALPHA

### Related Mods and their Versions

Launching pack All the Mods 7 - ATM7 - 1.18.2 0.4.22 for Minecraft 1.18.2
[25/07/2022 19:45:36 PM] Logging into Minecraft!
[25/07/2022 19:45:36 PM] Access Token has expired. Attempting to refresh it.
[25/07/2022 19:45:36 PM] Oauth token expired. Attempting to refresh
[25/07/2022 19:45:37 PM] xsts auth expired. Attempting to get new auth
[25/07/2022 19:45:39 PM] Loader: Forge 40.1.60

### Current Behavior

When I add an item that has been requested, viewable on the clipboard, to the Inventory button of the hut block... they do not see the item until I use the sort command.  

### Expected Behavior

The inventory buttons inventory should be included in the overall block inventory

### Reproduction Steps

See current behavior

### Logs

https://gist.github.com/crysallis/5e0ffeb15797a3887643eb49b6cccba9

### Anything else?

I have a video example of this here
https://imgur.com/a/mOyiyv0

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
It also looks like other buildings are affected: I saw another report on discord lately where the farmed carved a pumpkin on request for a builder and put it in their hut block (by lack of racks in that building). The courier failed to recognised the pumpkin, which let to other requests for pumpkins, etc. They had that problem with other crafters too.

**Comment by Talyda** [comment]
Adding to this, I was testing this yesterday (was going to continue today, but I won't now) and found the same thing. I had the sawmill making stairs etc. She was making them all fine, and sending them out straight away. I plopped some extras into her hut block as a test, left the builder making stuff and requested some in the post box, but the stuff in her hutblock inventory never got used, she just kept making more, and those stayed there.
Was gonna test if it happened in her racks today to, but won't bother now that there is more reports of it.
Also was testing in 1.18.1, (version 1.18.1-1.0.891) cos that is where first reports of it were happening

**Comment by Raycoms** [comment]
The crafters don't fulfill based on their own inventory. If you want the courier deliver already made ones, only warehouse will cause delivery

**Comment by crysallis** [comment]
> The crafters don't fulfill based on their own inventory. If you want the courier deliver already made ones, only warehouse will cause delivery

Maybe it's just a wording difference... as they do in fact fulfill from their own inventory.  If they have a request and you put blocks in their inventory they will see that and process the request.  What, I'm guessing you mean by your statement is they do not include blocks they already have as completed when deciding on how to process a request.  If they have 6 based on the recipe and only needed 4, those 2 are basically lost unless a pick up is done.  That, in and of itself, seems like a bug

**Comment by Raycoms** [comment]
Sent from Proton Mail mobile

-------- Original Message --------
