### ISSUE TITLE
Minecolonies ask for 1.18.1 - 1.0.408 and then when i add it, it ask for 1.18.2 - 1.0.349. How do i fix this?

### ISSUE THREAD

**Issue by BobaFettTea9** [ldtteam/minecolonies#8522]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.18.1-1.0.891-RELEASE

### Structurize Version

1.18.1-1.0.408-ALPHA

### Logs

https://pastebin.com/zyWJet0K

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
You are mixing 1.18.1 and 1.18.2 versions:
You are using 1.18.2 forge and multipiston, and 1.18.1 versions of minecolonies and structurize.
Those versions aren't compatible with each other, make sure you use 1.18.2 versions of all mods

**Comment by BobaFettTea9** [comment]
Oh man, i feel dumb. Thank you so much
