### ISSUE TITLE
Miner says AI has experienced an issue and to report it

### ISSUE THREAD

**Issue by thebloggingchef** [ldtteam/minecolonies#8528]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.
I am also running the latest (possible) versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [x] I checked the MineColonies/Structurize [Wiki](https://wiki.minecolonies.ldtteam.com/) or I asked on [discord](https://discord.minecolonies.com/). Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.0.898

### Structurize Version

1.0.411

### Related Mods and their Versions

1. Forge Version 40.1.68
2. Domum Ornamentum 1.0.50
3. BlockUI 0.0.48

### Current Behavior

My miner displays the message that its AI has experienced an issue and to report it to the developers. The miner stand by her workstation and does nothing.

### Expected Behavior

The miner to mine.

### Reproduction Steps

I do not know, it just happened.

### Logs

https://gist.github.com/thebloggingchef/806639a827e7e5d20167b8c0f80c0b92

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
I looked into this now, this can only happen when state gets corrupted in a crash.

**Comment by Raycoms** [comment]
Ill close this, I added a safeguard for this now
