### ISSUE TITLE
[BUG] <title> barracks upgrade problems

### ISSUE THREAD

**Issue by uhloin** [ldtteam/minecolonies#8531]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

minecolonies-1.18.2-1.0.904-ALPHA.jar 

### Structurize Version

structurize-1.18.2-1.0.411-ALPHA.jar 

### Related Mods and their Versions

forge-1.18.2-40.1.51-installer.jar 
blockui-1.18.2-0.0.58-ALPHA.jar 
domum_ornamentum-1.18.2-1.0.55-ALPHA-universal.jar 

### Current Behavior

-

### Expected Behavior

-

### Reproduction Steps

Upgrade barracks (core) from lvl 4 -> 5. Requires diamond helm (etc). Buy enchanted helm (or other armor) from vanilla villager armorer, remove enchantment with Grindstone. Try use deenchanted item for build -> failed.

Upgrade barracks (tower) from lvl 3 ->4. Pair of glass panes at second floor stays inaccurate (window 2x2 is not flat).

### Logs

-

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
For the second it's #5006 for the first it's a vanilla thing that leaves nbt behind, so we can't really process it unfortunately.
