### ISSUE TITLE
[BUG] Citizens of the same gender can create babies.

### ISSUE THREAD

**Issue by pantsguyapp** [ldtteam/minecolonies#8547]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.16

### MineColonies Version

minecolonies-1.16.5-1.0.920-ALPHA

### Structurize Version

structurize-1.16.5-1.0.418-ALPHA

### Current Behavior

Even in an all male colony, babies were still being produced

### Expected Behavior

They shouldn't be, as all the colonists are male

### Reproduction Steps

1. Build some houses.
2. Recruit only male visitors
3. Wait sometimes for a baby to be born

### Logs

https://gist.github.com/pantsguyapp/839634055c6a2d156ff0e06d865d4132

### Anything else?

The child:
![2022-08-07_13 31 48](https://user-images.githubusercontent.com/92203672/183278564-3d374157-4309-4437-96ac-8de731fb74b4.png)
![2022-08-07_13 34 28](https://user-images.githubusercontent.com/92203672/183278554-eb78620e-27fc-4137-9e9e-7dae3df1d8f3.png)
The parents and the child:
![2022-08-07_13 34 21](https://user-images.githubusercontent.com/92203672/183278570-1424db69-8491-4de9-9cb5-ee74439a3151.png)

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
Yes, that is how it works

**Comment by Raycoms** [comment]
Someone had a baby with one of the female visitors around and the gay couples adopted them.

Sent from Proton Mail mobile

-------- Original Message --------
