### ISSUE TITLE
[BUG] WorldGen Minecolonies Issues

### ISSUE THREAD

**Issue by Electrocutor** [ldtteam/minecolonies#8549]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.0.919-ALPHA

### Structurize Version

1.0.424-ALPHA

### Current Behavior

WorldGen allows Minecolonies abandoned colonies to spawn in the same location as existing NPC villages. If this happens, the existing village house blocks are replaced by the minecolonies building blocks wherever they intersect.

Also, the random block replacement causes things like uprooted flowers or frames/torches/etc falling off walls.

### Expected Behavior

Minecolonies abandoned colonies will not spawn directly near an existing NPC village to avoid overwriting it.

Abandoned colonies block random replacement will check for any dependent entities or blocks and not replace them with a block that does not allow those dependents.

*I realize that reporting a bug while having other mods installed is not ideal, but the likelihood of having an NPC village and Minecolonies abandoned colony randomly overlap is extremely small, so I felt I should at least make you aware of the issue.

### Reproduction Steps

1. Generate a new world where a Mincolonies abandoned colony happens to generate in the same location as an existing NPC village.

### Logs

https://gist.github.com/Electrocutor/ae71afc8597d1e085c63ed4156ecd3e6

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
The overlap of structure is something normal in vanilla worldgen, that is not something we can do against.
