### ISSUE TITLE
[BUG] <Fisher's AI broke>

### ISSUE THREAD

**Issue by bielabomba** [ldtteam/minecolonies#8551]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.18.2-1.0.919-ALPHA.

### Structurize Version

dunno

### Related Mods and their Versions

not sure am using the Direwolf 20 1.18 (Version 1.9) modpack

### Reproduction Steps

My Game lagged and crashed wilst in the nether and when i restarted and returned back to the overwolrd  i wanted to see my colony and for some reason the fisher would over trow his small place to fish even tho he has a lake right next to him so i tried expanding his small pond but he would reel in the fish.

### Logs

cant seem to upload them both sites crashed wilst trying to 

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
I don't really understand your report at all

**Comment by bielabomba** [comment]
ah well i suck at english and am kinda new to minecolonies but for unknow reasons the fisher's AI is just broken dunno what i should try i tried to repair his hut fire and hire him but still it doesnt work

**Comment by AuGold** [comment]
I'm experiencing the same bug on Direwolf 20 1.19. I dug into the latest.log as requested and found that something regarding the mod BloodMagic-1.18.2-3.2.4-39 is causing the error. 
Pastebin of the latest.log error: https://pastebin.com/JdWV6sS8

**Comment by AuGold** [comment]
I have discovered the solution: BloodMagic's update in Direwolf 20 1.19 broke fishing. BloodMagic already put out an update as of 4 hours ago fixing this issue, as seen here: https://www.curseforge.com/minecraft/mc-mods/blood-magic/files/3926937

**Comment by bielabomba** [comment]
Oh i knew something with one of the mods was up thank you
