### ISSUE TITLE
[BUG] smelter unable to recognize modded raw ores.

### ISSUE THREAD

**Issue by mike7998** [ldtteam/minecolonies#8552]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.0.919

### Structurize Version

1.0.424

### Current Behavior

Smelter and request system not recognizing modded raw ores. Recognizes the block versions of those ores

### Expected Behavior

Smelter should recognize all raw ores including modded

### Reproduction Steps

install any mod that adds metal ores (thermal expansion, mekanism, etc). Put raw ores in smeltery hut block.

### Logs

https://gist.github.com/mike7998/d56aaecec814cdc4a2c8525efefe995a

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
There is no standard Minecraft or Forge tag for raw ores, so the modpack author needs to add them to a MineColonies tag in a datapack for compatibility.
