### ISSUE TITLE
This block is missing its respective building

### ISSUE THREAD

**Issue by krjencik** [ldtteam/minecolonies#8553]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19.2

### MineColonies Version

1.19.1 - 1.0.921

### Structurize Version

1.19.1 - 1.0.423

### Related Mods and their Versions

Forge 43.0.7
Block UI 1.19 - 0.0.59
Domum ornamentum 1.19 - 1.0.58

### Current Behavior

I loaded a world - i have built builders hut. I cant access it: this block is missing its respective building, try restarting or loading a backup. I restarted the world. Nothing.

### Expected Behavior

be able to access the hut

### Reproduction Steps

Honestly I dont know. I just entered a world I had...

### Logs

https://gist.github.com/krjencik/f2311b2a578c0b327cdb62f3cc1eb509

### Anything else?

It turns out i also lost my colony

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by tyler489** [comment]
I had this happen immediately after dying to blood magic self sacrifice (soul to weak)  in minecolonies 1.18.2-1.0.1050-alpha
Structualizer 1.18.2-1.0.424
Domum Ornamentum 1.18.2-1.0.55-alpha

**Comment by MotionlessTrain** [comment]
> I had this happen immediately after dying to blood magic self sacrifice (soul to weak) in minecolonies 1.18.2-1.0.1050-alpha
> Structualizer 1.18.2-1.0.424
> Domum Ornamentum 1.18.2-1.0.55-alpha

"This block is missing its respective building" doesn't say much, except that something is wrong. If you want us to look at the issue, we would need your logs from the moment that happened

**Comment by uecasm** [comment]
This message is not entirely unusual for up to a minute or so after you load your world -- it means things haven't fully synched yet, just wait a bit longer and it should eventually work.

If you're still seeing it more than a couple minutes after your world loads, then that building might be corrupted and you may need to break and replace it (but don't do that before waiting!).

If it happens on all buildings, and you definitely waited, then it means your colony is probably corrupted, and unless you have a recent world backup you may be out of luck.  (There are some colony data backups that can be restored via command, but I'm not sure how well that works.)

If you can repeatably do a specific thing to make that start happening (other than reloading your world), then that may be a bug and we'd like to see your logs when it happens.
