### ISSUE TITLE
 Builder won´t start/finish building Fortress Townhall

### ISSUE THREAD

**Issue by gamingbeserkan** [ldtteam/minecolonies#8554]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.19.1-1.0.921-ALPHA.jar

### Structurize Version

1.19.1-1.0.423-ALPHA.jar

### Related Mods and their Versions

forge- 41.1.0
BlockUI- 1.19-0.0.59-ALPHA.jar
Domum Ornamentum- 1.19-1.0.59-ALPHA-universal.jar

### Current Behavior

So my builder wont finish or often not even start building the fortress townhall they build other things normally and this was also a problem in 1.18.1 for me.
The builder just does the placing animation/sound either from their hut without moving or at the building site but nothing is placed they have all the resources and the flat space.

### Expected Behavior

the townhall being built :/

### Reproduction Steps

build your temporary/perma builders hut and try building the fortress townhall next they might start but never finish. build a house for the builder to see if that changes anything. (no)

### Logs

5/8/22

### Anything else?

Github only let me choose 1.18 as minecraft version but it happened in 1.19 but also in 1.18.1.

**Comment by Talyda** [comment]
Give them a couple of hours, the final steps of the fortress town hall can take a really long time

If you are on discord, go into the bot commands channel and type in !slowbuilder that should give you some more inofrmation

**Comment by gamingbeserkan** [comment]
> Give them a couple of hours, the final steps of the fortress town hall can take a really long time
> 
> If you are on discord, go into the bot commands channel and type in !slowbuilder that should give you some more inofrmation

it is lvl 1 and its only torches that are left *IF* they even start building it in the first place :/

**Comment by Talyda** [comment]
Yeah, give them some time =)  Doesn't matter what level it is, the space it takes up is the same at all levels

**Comment by gamingbeserkan** [comment]
> Yeah, give them some time =) Doesn't matter what level it is, the space it takes up is the same at all levels

i´ll try that sometime tomorrow
