### ISSUE TITLE
Smeltery worker broken AI, exception thrown

### ISSUE THREAD

**Issue by HBullock3** [ldtteam/minecolonies#8555]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.0.919

### Structurize Version

1.0.424

### Related Mods and their Versions

Playing on DireWolf20 1.18.2 pack version 1.9.0

### Reproduction Steps

Smeltery is medieval spruce lvl 1

### Logs

https://gist.github.com/HBullock3/19797ab90affdbe31fc52e379e2aafb9

### Anything else?

Worker will intermittently work but eventually gets stuck saying AI is broken

**Comment by uecasm** [comment]
There are a **lot** of errors in there, which you should probably report to the modpack.

But that specific AI error seems to be a problem with Blood Magic doing something weird to the loot tables.  Check for an upgrade for that specific mod, or report it to them.
