### ISSUE TITLE
[BUG] Graphical incompatibility with Oculus

### ISSUE THREAD

**Issue by Aeris1One** [ldtteam/minecolonies#8561]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.0.919-ALPHA

### Structurize Version

1.0.424

### Related Mods and their Versions

1. Forge : 40.1.73
2. BlockUI : 0.0.58-ALPHA
3. DO : 1.0.55-ALPHA
4. Rubidium : 0.5.3a
5. Oculus : 1.2.5a

### Current Behavior

https://i.imgur.com/I5iKRBO.jpg
https://i.imgur.com/ifXn2fX.jpg

With Oculus installed, icons over the heads of citizens are glitched.

### Expected Behavior

Chatboxes should render correctly

### Reproduction Steps

1. Install Rubidium (Sodium Forge port) only
2. It works well
3. Install Oculus (Iris Forge port) too
4. Chatboxes are glitchy

### Logs

Absolutely no logs, nothing related the Minecolonies at least

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
Oculus changes forge's and vanilla's rendering code, causing this to happen.

This is rather a bug in oculus than in minecolonies

**Comment by Raycoms** [comment]
Please report to oculus. Not a minecolonies bug.

Please someone close it, I'm on my phone

Sent from Proton Mail mobile

-------- Original Message --------
