### ISSUE TITLE
residence unrepairable and beds not used.

### ISSUE THREAD

**Issue by Roses4664** [ldtteam/minecolonies#8562]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

minecolonies-1.19.1-1.0.921-ALPHA

### Structurize Version

structurize-1.19.1-1.0.423-ALPHA

### Related Mods and their Versions

forge-1.19.2-43.0.11-installer
blockui-1.19-0.0.60-ALPHA
domum_ornamentum-1.19-1.0.59-ALPHA-universal
multi-piston-1.19-1.2.16-ALPHA

### Current Behavior

unable to repair residence of some builds, colonists won't use the beds in any build, medieval birch changes its name to "oak" once built.
medieval birch alternative residence can be repaired, but the campfire blocks have to broke so the colonists don't die from standing next to the metal bars blocking it.
I deleted minecolonies and structurize, reloaded them, then rebooted my laptop. It didn't help.
 I'm wondering if the issue is caused by forge. 
![2022-08-14_11 18 56](https://user-images.githubusercontent.com/85271827/184557042-0da14e59-9744-44d2-8d2d-bc58dc3bb4ce.png)
![2022-08-14_11 19 24](https://user-images.githubusercontent.com/85271827/184557049-c574b480-f7af-4e76-8c85-e0ee4cf852f5.png)
![2022-08-14_11 47 06](https://user-images.githubusercontent.com/85271827/184557052-05e9b23c-50d6-48c6-88aa-6f6d8fe7a9bc.png)

### Expected Behavior

I expect the MODs to work as they always have.

### Reproduction Steps

Using the versions above, start a medieval birch colony, build a residence to level 5 and attempt to repair it. the repair button should be missing. 

### Logs

I am unable to make this work. 

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
I shortly looked at the "unrepairable" problem, and it looks to be a schematic issue with several medieval houses.
They have "Medieval Oak" set in the style property of the nbt.

The beds not being used seems to be a bigger issue, which I managed to reproduce in 1.19.2

**Comment by Roses4664** [comment]
I found the issue just now in "birch" builds. it can't be repaired either.

**Comment by MotionlessTrain** [comment]
~~That looks to be a bug in the datagen: The "style" property in the nbt of the hut block is "Birch" in 1.19.2, instead of "birch", making the house unbuildable in 1.19.2
(The only difference between both schematic files is that I ran the datagen to convert the birch style to 1.19 after the last rescan)~~
Edit: I managed to find the style property in 1.18.2 as well, but it only seems to give problems in 1.19.2, or very recent versions, it seems like (some of the files with the wrong "style" property haven't been changed in the past year)
