### ISSUE TITLE
[BUG] Jungle Schematics vs AI Pathing problems return

### ISSUE THREAD

**Issue by Chinthor** [ldtteam/minecolonies#8564]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.18.2-1.0.919-ALPHA

### Structurize Version

1.18.2-1.0.424-ALPHA

### Related Mods and their Versions

1.18.2-forge-40.1.69
blockui-1.18.2-0.0.58-ALPHA
domum_ornamentum-1.18.2-1.0.55-ALPHA-universal
DireWolf20 Pack MC1.18 - Pack v1.9.1

### Current Behavior

Colonists of all types are dying from fall damage while pathing needlessly over and around Jungle style buildings and vines. Most dangerous building is University. Upgrading from v2 to v3 never completed due to endless pathing loops up, over, and around the structure. Repeated falls nearly killed first builder. Upgrade canceled to allow builder to heal. Tried to resume the upgrade, builder began looping again. Made no progress for 45min, then died of fall damage. Second builder began looping the same. Used creative to force replace the v2 university with a v3. Requested a v4 upgrade, currently in progress. My miner and an unemployed citizen who both have no reason to be there tried to path through and died. They are climbing a vine and attempting to dismount onto a rooftop. 

Highlighted in picture. They keep climbing Tree 1, trying to get to Shingle 3, while traversing Vine 2. Vine 2 is not long enough and the colonist is not speedy enough for this. Might as well be empty space. Worse, they still use this path if they want to stop building and leave the area. Like when they are sick/dying and heading for the Hospital. Repeat loop until dead. More worse, other colonists are trying to path through this plot and finding pockets like this to get stuck in. Yes, the red text in the chat is 3 deaths inside of 10 min.

Seems this is a repeat of closed issue #7755. The schematic could be improved to not be so deadly to colonists, maybe by removing some vine strands, keeping them farther from ledges they might try to path to. Conversely, these issues with pathing AI were thought fixed in v 1.16 when #7755 was closed. Might need tweaking again in the current version.

![image](https://user-images.githubusercontent.com/8145428/184961995-7bd56b91-a400-41f8-993d-609804474891.png)

### Expected Behavior

Might be better if all colonists pathing gave heavier preference to paths, gravel, planks, stairs, and stone bricks. De-prioritize vines. Might also need to restrict what counts as a valid path. Example: "Valid path includes vine block, but only if the spaces above and below = vine or solid block AND the space 2 blocks up and 2 blocks down are also. Maybe require 3 up and 3 down.

### Reproduction Steps

1. Build Jungle University v2 or v3 via builder or creative mode.
2. Build and staff other facilities near by.
3. Allow time for vines to grow
4. Request an upgrade to v3 or v4
5. Upgrade will stall around 80-90% due to infinite loop pathing
6. Builder doing the upgrade as well as other colonists will die due to looped pathing + vine climbing + falling.

### Logs

https://gist.github.com/Chinthor/de7a89862fdf00097953752a4dc33f68#file-latest-log

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
Did you ever complete the "Aaaioooiooo" research? (The one that lets citizens climb vines)

**Comment by Chinthor** [comment]
Yes. While they seemed to use vines just fine before, I completed the research anyway. At the time of the issues, I had completed all available research except those requiring The End or an enchanter.  Hadn't gotten around to building one.
*edit* completed all research available to the level of university. Had all Lv2 research (minus enchanter branch)completed long before the upgrade to Lv3 got stuck. Same for the next upgrade, minus things that require purpur blocks, chorus fruit, or the enchanter tower.

**Comment by Raycoms** [comment]
I wouldn't call that an issue. That's why we made it a research. Climbing vines can be dangerous.

**Comment by Chinthor** [comment]
Ok. Noted, and perhaps lesson learned. Is there a way to un-learn vine climbing? Either in game or via a file edit? Would like to test the difference without restarting the whole colony.

**Comment by Raycoms** [comment]
@uecasm I think we need a way to allow specific research to unlearn, maybe a json toggle. For rails and vines
