### ISSUE TITLE
[BUG] Carpenter is loud 

### ISSUE THREAD

**Issue by Sinnedue** [ldtteam/minecolonies#8566]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

minecolonies-1.19.1-1.0.921-ALPHA

### Structurize Version

structurize-1.19.1-1.0.423-ALPHA

### Related Mods and their Versions

1. domum_ornamentum-1.19-1.0.59-ALPHA-universal
2. blockui-1.19-0.0.59-ALPHA
3. multi-piston-1.19-1.2.16-ALPHA
4. forge 1.19 - 41.1.0

### Current Behavior

Whenever the carpenter at the sawmill crafts an item there is a "saw"/ cutting noise that plays at full volume anywhere in the colony

### Expected Behavior

The saw noise should play only locally to the sawmill and fade with distance

### Reproduction Steps

1. Have a sawmill (Mine is a level 1 Caledonia)
2. Teach them a recipe
3. Have them craft something
4. Listen for loud noise

### Logs

https://pastebin.com/0gH4f76x

### Anything else?

Minecraft 1.19
Similar to [this](https://github.com/ldtteam/minecolonies/issues/8427)

**Comment by Shintori99** [comment]
Quite an annoying bug, but I guess they aren't fixing this since it's not game-breaking and has an easy work-around.

**Comment by Sinnedue** [comment]
> 

What's the workaround?

**Comment by Shintori99** [comment]
The one that's mentioned in your link - turning Friendly Creatures volume down, but I like hearing all the worker sounds so I hope they fix this.

**Comment by TheRTGGaming** [comment]
Sorry to break the sound barrier. but... the issue is back in 1.19.2. the sound from the sawmill audio is being heard from large distances.

**Comment by Raycoms** [comment]
fix pushed
