### ISSUE TITLE
[BUG] Rack outline does not appear through walls when searching inventory of a building

### ISSUE THREAD

**Issue by DarthLeahcim** [ldtteam/minecolonies#8571]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.19.1-1.0.921-ALPHA

### Structurize Version

1.19.1-1.1.423-ALPHA

### Related Mods and their Versions

Forge: 43.1.1
BlockUI: 1.19-0.0.60-ALPHA
Domum: 1.19-1.0.59-ALPHA
Multi-Piston: 1.19-1.2.16-ALPHA

### Current Behavior

When hitting the ? next to the item in the inventory of the main building block (the chest) the outline shows up around the correct rack but does not show through walls. Neither red no green outlines do this

### Expected Behavior

According to Moobien on the Discord, it should show through walls by default

### Reproduction Steps

Start a colony
Place a building
Place an item in a rack(s)
Search for the item
Search for the rack(s)

### Logs

https://gist.github.com/DarthLeahcim/a44eaaf6810f0ad20a161c49aabf11b9

### Anything else?

First noticed on MineColonies v1.19.1-1.0.927-ALPHA with Forge v42.0.9 but could've been an issue before this.
The log may be a bit messy from me accidentally skipping a step or two when quickly creating a town in Creative

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Using any client side performance or shader mods?

**Comment by DarthLeahcim** [comment]
Sadly no. Hopefully one day Rubidium and Structurize work together. 

I removed all other mods as well as my Shenandoah GC launch arguments with no luck. I also just created a brand new Modpack instance on 1.19.2 (I'm currently using 1.19.1 with Forge v42.0.9 for my main Modpack) and it still doesn't show through blocks. 

I also noticed the outline behaves strangely with respect to the rack itself:
![image](https://user-images.githubusercontent.com/2687067/185804804-40556169-521a-45d8-bd43-3112914156fe.png)
![image](https://user-images.githubusercontent.com/2687067/185804839-f0ef98f1-a8cb-437e-b246-45688318c98b.png)

**Comment by DarthLeahcim** [comment]
The building block also affects it:
![image](https://user-images.githubusercontent.com/2687067/185804900-fb79466d-869a-475f-8137-c1db2fae2aad.png)

**Comment by DarthLeahcim** [comment]
Some interesting discoveries. 
A similar thing happens when looking at the outline of a building block when it's being previewed. It's also blocked by racks but can be seen through solid blocks and is slightly darker when seen through a transparent block:
![image](https://user-images.githubusercontent.com/2687067/185808448-364d248c-54b8-4391-9034-27e151c24a4d.png)
![image](https://user-images.githubusercontent.com/2687067/185808465-9be8ac31-10fe-4e4f-9834-2e7bafc40ba8.png)

It is also blocked by banners:
![image](https://user-images.githubusercontent.com/2687067/185808533-83cabb07-48d8-4a07-88f4-6aa993f82773.png)


The rack search outline behaves in the same manner if you are in build preview mode or have the build tool out:
(no tool)
![image](https://user-images.githubusercontent.com/2687067/185808663-b35761da-b831-4fa1-84f6-33c7d0fb3ccb.png)

(with tool)
![image](https://user-images.githubusercontent.com/2687067/185808686-7575f163-c5ac-4a23-845a-e4068c9bdbe2.png)

Edit: The amount in container number also behaves the same as the outline

**Comment by Nightenom** [comment]
Side effect of our incompatibility with recent forge client updates

**Comment by Sandriell** [comment]
Incidentally I am on 1.16 and have never had this work (showing through blocks) either. I know 1.16 is EOL, but I mention it cause it might mean it is a deeper issue than simply a recent change in forge.

**Comment by MotionlessTrain** [comment]
I'm 99% sure it worked in at least one 1.16.5 version
