### ISSUE TITLE
[BUG] <Builder gave me an error on completion and noticed the decoration ui was useless>

### ISSUE THREAD

**Issue by Dylbert93** [ldtteam/minecolonies#8577]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.19.1-1.0.968-ALPHA

### Structurize Version

1.19.1-1.0.434-ALPHA

### Related Mods and their Versions

1. Forge - 43.1.2
2. Block UI - 1.19-0.0.60-ALPHA
3. Domum Ornamentum - 1.19-0.0.60-ALPHA
4. Multi-Piston - 1.19-1.2.16-ALPHA
5. Biomes O' Plenty - 1.19.2-17.1.1.150
6. Corpse - 1.19.2-1.0.0
7. Jade - 1.19.1-forge-8.0.1
8. Journey Map - 1.19.1-5.9.0beta2-forge
9. JEI - 1.19.2-forge-11.2.0.256
10. Terra Blender - 1.19.2-2.0.1.125
11. When Dungeons Arise - 1.19-2.1.51-beta
12. William Wythers' Overhauled Overworld - 3.1.7+1.19.2

### Reproduction Steps

Caladonia Style
Decorations
Nether Portal
Build with Builder

### Logs

https://gist.github.com/Dylbert93/48dbf027edfc95b8be67fcea9288ad37

### Anything else?

https://cdn.discordapp.com/attachments/1003402487417548801/1011693930963808376/2022-08-24_03.49.37.png

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
fixed
