### ISSUE TITLE
[BUG]  Builders Building Road Instead of Railroad

### ISSUE THREAD

**Issue by auddie2015** [ldtteam/minecolonies#8578]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.18.2-1.0.969-ALPHA

### Structurize Version

1.18.2-1.0.424-ALPHA

### Related Mods and their Versions

Forge: 1.18.2-forge-40.1.73
BlockUI: 1.18.2-0.0.58-ALPHA
Domum: 1.18.2-1.0.50-ALPHA-universal

### Current Behavior

Laying decorations rail/fortress longrailroad2 and trail2

Builder requests blocks for and builds decorations road/fortress longpath1 and tjunction1

The proper schematic is shown while placing the road sections for each one.

When construction starts and finishes, the proper schematic is displayed in chat. 

### Expected Behavior

The builder builds the schematic I place.

### Reproduction Steps

Place either of the railroad schematics. I have not checked if this does it with all of them.

### Logs

https://gist.github.com/auddie2015/aec1b2bb6cf03127f2c45d21d89cc66f

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
That is intended. Like all buildings, upgradable decorations always start at level 1.
There is a decoration controller at one of the posts halfway the road which you can use to upgrade it to level 2 (and 3 eventually)

**Comment by auddie2015** [comment]
HAHAHA! Awesome! I looked specifically for roads in the wiki not even thinking that they _are_ in fact decorations. The mod is very different between 1.12 and 1.18. I have to say the 1.18 has blown me away so far. Thanks!
