### ISSUE TITLE
[BUG] Several citizens have a work distance of "-5410 blocks" in the Tavern

### ISSUE THREAD

**Issue by aaronhowser1** [ldtteam/minecolonies#8582]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

minecolonies-1.18.2-1.0.969-ALPHA

### Structurize Version

structurize-1.18.2-1.0.424-ALPHA

### Current Behavior

![image](https://user-images.githubusercontent.com/15698722/186746188-eccaaeea-6aa8-4edb-b803-ab2e7ad2d85e.png)

Recalling these citizens at the Town Hall does not work, either

### Expected Behavior

For it to show where they work

### Reproduction Steps

No idea

### Logs

https://gist.github.com/5f6aa003923a9ab420631a8c11a19289

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Sent from Proton Mail mobile

-------- Original Message --------

**Comment by Raycoms** [comment]
related to the mod killing our citizens
