### ISSUE TITLE
[BUG] The question mark button in the buildings UI doesn't work

### ISSUE THREAD

**Issue by Albe0774** [ldtteam/minecolonies#8583]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.19.2-1.0.982-ALPHA

### Structurize Version

1.19.2-1.0.437-ALPHA

### Current Behavior

When i click the  question mark button it just shows some text. Looks like the file name of the file that should have been loaded.
Example, this is a level 1 gaurd tower:

![image](https://user-images.githubusercontent.com/112131164/186779467-b6556cd2-7141-4ce6-9d34-f6d762e85291.png)

### Expected Behavior

I expect to get a messege telling what the building is all about :D

### Reproduction Steps

I just open the game and click the qustion mark button in the building UI.

### Logs

https://pastebin.com/zEqnh7wL

### Anything else?

I think either im missing a file or something else went wrong trying to read a file.

**Comment by Raycoms** [comment]
fix pushed
