### ISSUE TITLE
[BUG] Guards AI Error

### ISSUE THREAD

**Issue by Cheonza** [ldtteam/minecolonies#8589]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

minecolonies-1.19.2-1.0.982-ALPHA.jar

### Structurize Version

structurize-1.19.2-1.0.437-ALPHA.jar

### Related Mods and their Versions

1) multi-piston-1.19-1.2.16-ALPHA
2) domum_ornamentum-1.19-1.0.59-ALPHA-universal
3) blockui-1.19-0.0.60-ALPHA

### Reproduction Steps

1) I place the Guard Tower
2) I have the Guard Tower constructed
3) Colonist/Guard asks for their desired items
4) After a minute or so the Colonist/Guard informs me there is a problem with their AI and to send the log to the Author.

### Logs

https://gist.github.com/Cheonza/3dc1d727df5df455c1d7b65b2e1c557b

### Anything else?

Guards are NOT attacking mobs as they should, be even when fully geared.

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Please report to: stepsword.mahoutsukai

**Comment by Cheonza** [comment]
Will do

**Comment by stepsword** [comment]
pretty sure i fixed this on latest mahou already (log has 2 versions behind)
