### ISSUE TITLE
[BUG] Builder AI issue when completing decoration build

### ISSUE THREAD

**Issue by nrohrlach4** [ldtteam/minecolonies#8590]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.19.2-1.0.982-ALPHA

### Structurize Version

1.19.2-1.0.437-ALPHA

### Related Mods and their Versions

forge-1.19.2-43.1.1
blockui-1.19-0.0.60-ALPHA
domum_ornamentum-1.19-1.0.59-ALPHA-universal
structurize-1.19.2-1.0.437-ALPHA
multi-piston-1.19-1.2.16-ALPHA
appleskin-forge-mc1.19-2.4.2
appliedenergistics2-12.1.2-beta
configured-1.5.8-1.19
elevatorid-1.19-1.8.7
FastLeafDecay-30
InventoryProfilesNext-forge-1.19-1.6.5
jei-1.19.2-forge-11.2.0.256
journeymap-1.19.1-5.9.0beta2-forge
kotlinforforge-3.7.1-obf
moreoverlays-1.21.3-mc1.19
reap-1.19.2-1.0.0
sit-1.19-1.3.3
StorageDrawers-1.19-11.1.2
theoneprobe-1.19-6.2.1
ZeroCore2-1.19-2.1.25

### Reproduction Steps

Medieval Spruce style
Caledonia Alt Roads
Will occur with any road decoration in this combo
finished building message will repeat in chat every few seconds
construction tape does not disappear
must remove work order in Town Hall Hut block to stop repeating message

### Logs

https://gist.github.com/nrohrlach4/d7ec58e81ddfd5007698ab3ea6f01a13

### Anything else?

![2022-08-27_21 14 50](https://user-images.githubusercontent.com/112162934/187028779-84a36b06-9927-439c-8fdb-29d43bbc7427.png)

![2022-08-27_21 14 56](https://user-images.githubusercontent.com/112162934/187028782-012eeefc-3293-496e-bc3f-240ea1eaf8d4.png)

![2022-08-27_21 15 12](https://user-images.githubusercontent.com/112162934/187029064-9c00bb77-5ae9-4034-903a-1a3a0b749ccf.png)

**Comment by Raycoms** [comment]
fix pushed
