### ISSUE TITLE
[BUG] Advancements related to huts/build tool are not working

### ISSUE THREAD

**Issue by Shintori99** [ldtteam/minecolonies#8591]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

minecolonies-1.19.2-1.0.982-ALPHA

### Structurize Version

structurize-1.19.2-1.0.437-ALPHA

### Related Mods and their Versions

forge-1.19.2-43.1.1
blockui-1.19-0.0.60-ALPHA
domum_ornamentum-1.19-1.0.59-ALPHA-universal
multi-piston-1.19-1.2.16-ALPHA

### Current Behavior

Advancements that involves the player using the build tool to place down a hut block (e.g. Start Your Colony, The Builder Begins, most advancements in Production and Militia tab, etc.) is not working.
Advancements which are not involved with build tool works fine (e.g. Minecolonies, Check Out The Guide, Another Mouth to Feed, Last Resort, etc.)

### Expected Behavior

Advancements are granted once the requirements have been met.

### Reproduction Steps

1. Place down the town hall block using build tool
2. Check if the advancement "Start Your Colony" was granted
3. Place down the builder's hut using build tool
4. Check if the advancment "The Builder Begins" was granted
5. Continue the process for all of the other advancements which involves/starts with placing down a hut block using build tool

### Logs

https://gist.github.com/Shintori99/950448e93c3929af1439e7998475b442

### Anything else?

In the log, you'll see I only reproduced "Start Your Colony" and "The Builder Begins" bug as a point of proof, but this is also true for other build tool-related advancements, based on the experience I had with my other modded survival world with only Minecolonies + dependencies installed.

**Comment by Raycoms** [comment]
fix pushed
