### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by Mistmage** [ldtteam/minecolonies#8599]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [x] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.0.989-BETA

### Structurize Version

1.0.424-ALPHA

### Related Mods and their Versions

Forge 40.1.70
blockui-1.18.2-0.0.58-ALPHA
domum_ornamentum-1.18.2-1.0.50-ALPHA-universal
multi-piston-1.18.2-1.2.15-ALPHA

FpsReducer2-forge-1.18.2-2.0 (identified by Not enough crushes)

### Current Behavior

I didn’t see citizen's preview for: level 1 to 5 for spruce medieval, 1 to 5 for birch, but see smoke from invisible campfires and level 1 to 4 oak medieval (level five is okay, I can even place it), but see all medieval dark oak and (theoretical) all others.

After asking on Discord I try to paste the building in, (birch, level four), and it crashed immediately.
Later I tried for oak level two and oak level five and five was okay and two have crush. 

It also works the same way if you want to place it to be 

When they see crush, they send me there, on github 
> 

### Expected Behavior

Be able to see preview and, don't have crushes.

### Reproduction Steps

I don't really know, you have a crush.

Past any building which preview you don't see, having some conflicting mod installed… I think.

### Logs

https://gist.github.com/Mistmage/8eb8046dbfd39e4326206f740dc87980

### Anything else?

![2022-08-30 02-46-22 Minecraft  1 18 2](https://user-images.githubusercontent.com/42159697/187317939-65913886-aca4-4b05-87cb-13c6cdc48497.png)

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
Do you also have a latest.log from the time of the crash?

**Comment by Mistmage** [comment]
> 

Yes, but full log is 61 257 kb and it too much for gist. But I insert a part of it lower than crush. That part is repeated 12000 times 

Oops... now it looks like it 2369011 kb... so i can't even open it…

**Comment by Raycoms** [comment]
Did you try it without fps reducer?

**Comment by Mistmage** [comment]
> Did you try it without fps reducer?

No.
But i test it on minecolonies-1.18.2-1.0.984-ALPHA and all is okay

And i see that in changelog: Fix several medieval schematics seeming to have trouble upgrading due to an invalid style property

**Comment by MotionlessTrain** [comment]
I was wondering whether I managed to break something, and I hoped the latest.log would help finding where the problem is

**Comment by Mistmage** [comment]
> I was wondering whether I managed to break something, and I hoped the latest.log would help finding where the problem is

And fragment about GZIP is not enough?

I mean, what are you searching for?

**Comment by MotionlessTrain** [comment]
Edit: A latest.log on discord seems to reveal that the blueprints are not in gzip format, so something must have gone wrong saving them. I apologise for it. For now, I recommend downgrading to the latest alpha version before this beta version.
I'll fix it as soon as possible

**Comment by Mistmage** [comment]
> 

Already did it 😉


also – no worries, you're making wonderful mod, and bugs are okay, i am little surprised because that one looks as big as elephant, but maybe it only looks like that.
