### ISSUE TITLE
Crash: Ticking Entity

### ISSUE THREAD

**Issue by Merithor** [ldtteam/minecolonies#8600]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.0.966 RELEASE

### Structurize Version

1.0.424 ALPHA

### Related Mods and their Versions

Mod Pack: ATM 7 , latest patch.
Was being raided by Barbarians, the only thing thats changed was my villagers armor since the last raid, could be an enchant or a bow from the Twilight Forest (as per some of the changes I want to make my Guards stronger).

### Current Behavior

Crashing on a Ticking Entity, something incompatible with Minecolonies. One of the new pieces of armor or weapons I have given my guards.

### Expected Behavior

Not to crash.

### Reproduction Steps

Have a raid, give Guards armor dropped from Apotheosis Boss mobs (End Dimension dropping), this includes Twilight Forest Bows.

### Logs

https://pastebin.com/mzMN72qM

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
You'll need to report this to Forbidden Arcanus -- they appear to be assuming that only players will be using their weapons.
