### ISSUE TITLE
[BUG] Builder AI Error

### ISSUE THREAD

**Issue by Cheonza** [ldtteam/minecolonies#8602]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

minecolonies-1.19.2-1.0.982-ALPHA

### Structurize Version

structurize-1.19.2-1.0.437-ALPHA

### Related Mods and their Versions

1) blockui-1.19-0.0.60-ALPHA
2) domum_ornamentum-1.19-1.0.59-ALPHA-universal
3) multi-piston-1.19-1.2.16-ALPHA

### Reproduction Steps

All you really need to do is have the builder do a decoration build.
Upon Completion the Builder starts to say that he's finished the construction multiple times and doesn't get rid of the construction tape around the decoration that was recently finished, and also states there is an error with their AI; send logs to minecolonies authority.

### Logs

https://gist.github.com/Cheonza/d47b8a5a4616990f56cf6e12b5446052

### Anything else?

The bug is really just messages the builders send in chat after finishing a decoration build. You could make it stop by firing them and rehiring them, or just canceling the build that's already finished. Just wanted to send logs in case anything else needs fixing.

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
A bug related to this was solved recently. Could you try with the newest alpha?
