### ISSUE TITLE
[BUG] Barracks towers get build in incorrect rotation

### ISSUE THREAD

**Issue by MotionlessTrain** [ldtteam/minecolonies#8605]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.0.991-Alpha (or rather the equivalent commit to that)

### Structurize Version

1.0.437-Alpha

### Related Mods and their Versions

The other mods that get loaded in the dev environment

### Current Behavior

Barracks towers seem to get built in one orientation, rather than following the orientation of the parent building.
I built the Caledonia barracks in two different orientations, and the barracks tower faced the same direction in both of them.

### Expected Behavior

The orientation of the barracks tower depends on the orientation of the barracks

### Reproduction Steps

1. Build a barracks (I used the caledonia barracks in my test, as that was originally reported on discord)
2. Let a builder build the barracks tower.
3. In three of the four orientations, the barracks tower is facing in the wrong direction (in case of caledonia, the door should be facing the fenced area, in order to be correct)

### Logs

https://gist.github.com/d85e353e69f179355049a8327105b2c5

### Anything else?

I think this may be related to #7866. Though in this case, it seems to be affecting child buildings using the (old) regular names.

Mirror mode was off.

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
Yeah, this is the same problem I've been poking Ray about for another schematic.

Currently the workaround is to (a) create a `hutname0.blueprint` scan for the child huts containing only the hut block/placeholders (ideally with the same dimensions as the real child schem, but a 1x1x1 should work too, it just might produce confusing tape -- also note that the level 0 hut must be rotated the same way as the level 1-5 huts as of scan time) and (b) _after_ moving it to the correct pack and path, "constructed" paste this into the correct spot and rotation in the parent schematic, then rescan the parent.  (Disclaimer: I haven't actually tested this, but it fits with the facts.)

However it is intended that things work without having to do this, so it will hopefully be fixed Soon™.

**Comment by MotionlessTrain** [comment]
That would indeed be quite annoying to do so for every barracks.

However, what I also found out was that auto-upgrading barrack towers break too, when you try to repair them.
Currently, the only barracks which has that to my knowledge is an updated version of the caledonian barracks (most other auto-upgrading barracks towers use a 1x1x1 schematic, so this wouldn't be noticed at all).
I'm not sure if there is any difference between an auto-upgrading barracks tower and one built from a level 0 blueprint

**Comment by Raycoms** [comment]
fixed
