### ISSUE TITLE
Bug in desert oasis.

### ISSUE THREAD

**Issue by Roses4664** [ldtteam/minecolonies#8612]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

minecolonies-1.19.2-1.0.998-ALPHA

### Structurize Version

structurize-1.19.2-1.0.441-ALPHA

### Related Mods and their Versions

FORGE 43.1.1
multi-piston-1.19-1.2.16-ALPHA
blockui-1.19-0.0.61-ALPHA
structurize-1.19.2-1.0.441-ALPHA
domum_ornamentum-1.19-1.0.60-ALPHA-universal

### Current Behavior

Desert oasis; builder is rebuilding rather repairing the townhall, coming out of the left side of the townhall.
The miner "can't mine because the mine is missing the proper indication." I thought this was because I needed to finish the research, (Although I'm playing in creative), then I thought I needed to place the mineshaft, I also tried rebuilding a new mine. none of these worked.
 The nether miner is killed "every time" by lava immediately upon entering the nether. I fixed this by removing the lava within 3 blocks of the portal at the mine.

 
![2022-09-02_20 39 53](https://user-images.githubusercontent.com/85271827/188251843-b5fc8ab6-d7a5-4fe0-80e0-7b6536a4e5d3.png)
![2022-09-02_20 40 06](https://user-images.githubusercontent.com/85271827/188251848-d22e66f1-3611-47e3-90fd-185baf4efdca.png)
![2022-09-02_20 40 28](https://user-images.githubusercontent.com/85271827/188251851-899e79a1-97d3-41f7-9a78-2e78997e682b.png)
![2022-09-02_21 20 02](https://user-images.githubusercontent.com/85271827/188252186-3b06b36b-8d10-4bc5-afac-6445233b1fe3.png)

### Expected Behavior

I expect the builder and miners to behave as they always have. 

### Reproduction Steps

Build the town hall to level 5 in creative, turning it any other direction then the preview. once the builder is available request a repair to the town hall. 
Hire a miner and right click the miner to see the message.
Hire a nether miner, provide it with its supplies and watch the message pop up that it died by lava.

### Logs

I am unable to make this work. 

### Anything else?

I haven't found anything else yet, but I'll let you know.

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
#5006 and @MotionlessTrain

**Comment by Roses4664** [comment]
The issue with the miner is still not resolved, he still won't mine because something is missing, I downloaded the update and rebuilt the mine all the way to 5.

**Comment by MotionlessTrain** [comment]
Could you try to repair it again, and then go into creative mod and get yourself a tag tool? If so, could you shift+right click with the tag tool on the hut block of the mine, and open its interface and make a screenshot?

**Comment by Roses4664** [comment]
No need, it seems to be working properly now.
 I got tired of the issues and deleted the world and was going to start over tomorrow until I got your message.


Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Roses4664** [comment]
Thank you

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
