### ISSUE TITLE
[BUG] <Crafting loop on whwool>

### ISSUE THREAD

**Issue by Mistmage** [ldtteam/minecolonies#8625]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

minecolonies-1.18.2-1.0.1001-ALPHA

### Structurize Version

structurize-1.18.2-1.0.424-ALPHA

### Current Behavior

i have mod on flax (Supplementaries) Fletcher study recipe of making wool out of strings and vanilla strings to wool recipe.

![2022-09-05 20-44-17 Minecraft  1 18 2 - Singleplayer](https://user-images.githubusercontent.com/42159697/188497878-ffd476bc-844f-4a5e-866e-8bb3431f049d.png)

It worked great until i built a dyer's hut. After these when in warehouse was not wool instead of making a white wool out if strings, they prefer make it out of gray wool (bleaching recipe). Where they want to get gray wool? They make it of white wool! (white wool + gray dye, recipe) and where they want to get white wool? Right! Out of gray one.

If you remove gray recipe, they would use orange.

![2022-09-05 20-45-54 Minecraft  1 18 2 - Singleplayer](https://user-images.githubusercontent.com/42159697/188498558-30973ede-7867-4e4e-9a40-da931a5fe55b.png)

### Expected Behavior

Instead of loop if there are no wool – go and make it from strings.

### Reproduction Steps

1 Built a Fletcher, dyer, courier, and warehouse. (Asian if it can matter)
2 Study a string to wool, gray dye and white wool to gray wool, red wool same as gray, and red banner (Fletcher recipe from red wool)
3 Put strings and red dye in warehouse. Request a red banner.
4 see that they want.

### Logs

https://gist.github.com/Mistmage/5e03a8e1b290032f61aea2df39fac434

### Anything else?

Debag.log

https://gist.github.com/Mistmage/aa3d3229d81cf4f4993e15408e147d28

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
There is unfortunately no way to avoid this.

**Comment by Mistmage** [comment]
is it possible to add the ability to turn off the bleach recipe via config?

> There is unfortunately no way to avoid this.

**Comment by Raycoms** [comment]
I'm not 100% sure, can you check if there is a way to disable a recipe in the list of recipes?

**Comment by MotionlessTrain** [comment]
The bleaching recipe doesn't show up in the recipe list, so it has no button to disable it

**Comment by Raycoms** [comment]
okay, then we need a setting trigger for this. I'm talking with @Mekle001 about it
