### ISSUE TITLE
Pirate Encounter Destroying Player Build Structures

### ISSUE THREAD

**Issue by jnutty3** [ldtteam/minecolonies#8626]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.16.5-1.0.978=Release.jar

### Structurize Version

1.16.5-1.0.418-ALPHA.jar

### Related Mods and their Versions

Forge 36.2.34
Minecraft version 1.16.5
![2022-09-05_15 24 27](https://user-images.githubusercontent.com/104437171/188506008-b691139f-abc0-4b20-b9bf-5fb43c1b81f0.png)
![2022-09-05_15 24 45](https://user-images.githubusercontent.com/104437171/188506009-c55ad2cc-052e-4ca1-971d-e914c159f41c.png)
![2022-09-05_15 25 05](https://user-images.githubusercontent.com/104437171/188506011-f4904525-3fea-4899-a709-846c6216dd6b.png)
![2022-09-05_15 25 28](https://user-images.githubusercontent.com/104437171/188506015-5a488ebc-5af9-4b61-9a0a-10c51527dd01.png)

### Current Behavior

Pirate Encounter Destroying Part of Player created structure. 
![2022-09-05_15 25 28](https://user-images.githubusercontent.com/104437171/188505546-5a993c5b-bf93-4f68-b601-0576814d6746.png)
![2022-09-05_15 25 05](https://user-images.githubusercontent.com/104437171/188505556-4c812c66-35a7-45c9-b3c9-753bfd4acf54.png)
![2022-09-05_15 24 45](https://user-images.githubusercontent.com/104437171/188505559-179c1f28-ae9a-4587-97ac-a16b3d0b4017.png)
![2022-09-05_15 24 27](https://user-images.githubusercontent.com/104437171/188505564-f0ba5341-a9c5-4821-b777-6a793b03857f.png)

### Expected Behavior

To show up in water, but outside of player created structure. Before encounter starts it should check for a player created item and avoid it. 

### Reproduction Steps

Build Large Structure that is part on land and over water. 

### Logs

https://pastebin.com/hF5sVj8m

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
They restore the building when they leave again.
And it is impossible to determine what is player built, and what was made by the world generation (Did someone terraform here to make this island, and or did they dig a lake here?)

**Comment by Raycoms** [comment]
same as #7798
