### ISSUE TITLE
[BUG] Courier getting stuck on pickup

### ISSUE THREAD

**Issue by BradleyPratt** [ldtteam/minecolonies#8628]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.0.1004

### Structurize Version

1.0.443

### Related Mods and their Versions

Forge Version: 43.1.3
BlockUI Version: 0.0.61
Domum Ornamentum: 1.0.60

### Current Behavior

Couriers idle permanently at pickup location (Doing a request system reset fixes the issue temporarily)

### Expected Behavior

Couriers shouldn't idle permanently at pickup location

### Reproduction Steps
Has also happened to me in other use cases, but using this as an example

1. Forester (Dark Oak Alternative 1 or 2) cuts down trees and places them in Forester's Hut Storage.
2. Forester creates item pick up request
3. Courier will take whatever items the forester has placed
4. Courier returns to empty storage again and idles there permanently

### Logs

https://gist.github.com/BradleyPratt/b0f26a3eb2c472f7c1c7b8f79193bf99

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
fixed
