### ISSUE TITLE
[BUG] Can Dupe Minecolony Field block with Ars Exchange Spell

### ISSUE THREAD

**Issue by Saereth** [ldtteam/minecolonies#8630]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

minecolonies-1.18.2-1.0.1001-ALPHA

### Structurize Version

structurize-1.18.2-1.0.424-ALPHA

### Related Mods and their Versions

Forge 40.1.73
Ars: ars_nouveau-1.18.2-2.7.7

### Current Behavior

Place the field(scarecrow).
Cast exchange on the bottom block of the Scarecrow. Bottom block is replaced with whatever block you had ready.
The top of the scarecrow is still there but not visible, you can see the selection box, though.
Mine that top selection box to receive a 2nd Scarecrow.

Tried with a couple other 2-high items from vanilla, it doesn't work on them.

### Expected Behavior

For the block to not be duped

### Reproduction Steps

Place the field(scarecrow).
Cast exchange on the bottom block of the Scarecrow. Bottom block is replaced with whatever block you had ready.
The top of the scarecrow is still there but not visible, you can see the selection box, though.
Mine that top selection box to receive a 2nd Scarecrow.

### Logs

https://pastebin.com/ZAbU5iQF

### Anything else?

Also opened an issue with the ars dev since im not sure who's side the issue is on

https://github.com/baileyholl/Ars-Nouveau/issues/685

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Checked with Ars dev, they told me that they have to fix it on their side
