### ISSUE TITLE
[BUG] Wrong direction for attackers

### ISSUE THREAD

**Issue by uhloin** [ldtteam/minecolonies#8634]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.19.2-1.0.1010

### Structurize Version

1.19.2-2.6.1

### Current Behavior

"Mysterior warriors have been spotted
South/East of ... Colony!"

### Expected Behavior

South/West
Looks like west/east was swapped by mistake in this message.

### Reproduction Steps

-

### Logs

-

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Sometimes they go around the colony if they find a better task. Double checked this.

**Comment by uhloin** [comment]
No, I saw where they spawned because xaero's map mod. After first twice attacks direction becomes correct. I'll write with screenshot if bug will appear again.
