### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by wuggyfoot** [ldtteam/minecolonies#8638]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

minecolonies-1.19.2-1.0.1016-ALPHA

### Structurize Version

structurize-1.19.2-1.0.443-ALPHA

### Current Behavior

There is no dependency for Domum Ornamentum on the curseforge page.

### Expected Behavior

I expected there to be a list of dependences and to not have to find out in the console log. I just think it would be advantageous to update the dependencies page on curseforge. I am aware this is all in alpha but still.

### Reproduction Steps

Go to minecolonies curseforge page. Click dependencies tab. Be confused.

### Logs

https://www.curseforge.com/minecraft/mc-mods/minecolonies/relations/dependencies

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
that's on cf now. I verified and we got it there.

**Comment by MotionlessTrain** [comment]
The 1.18.2 and 1.19.2 files have the dependencies listed on the bottom of the curseforge page. It looks like Curseforge still thinks it is a 1.16.5 mod (probably because the last "release" version is for 1.16.5), and lists the 1.16.5 dependencies on that page instead. We can't do anything about that
