### ISSUE TITLE
[BUG] <JEI Recipes are bloated with the Integrated Dynamics Facade+MineColonies>

### ISSUE THREAD

**Issue by Snorlax1337** [ldtteam/minecolonies#8639]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

minecolonies-1.18.2-1.0.919-ALPHA

### Structurize Version

structurize-1.18.2-1.0.424-ALPHA

### Related Mods and their Versions

IntegratedDynamics-1.18.2-1.11.8

### Current Behavior

My Issue is that the JEI Recipes get overloaded by the "Facade - None" block specifically in the MineColonies Sections like the Assistant Cook, Farmer, Fletcher, Glassblower, and so on.
You can take ANY block and the combination of ID and MC will cause a completly overloaded JEI in the recipe area.

### Expected Behavior

Please find a way to de-bloat my JEI so i dont have to scroll through unneccesary pages of recipes.

### Reproduction Steps

1. Open JEI
2. Check Recipe Options for any block
3. Find random things like a Planter trying to work with a diamond block
![JustWhy](https://user-images.githubusercontent.com/110115789/189314189-2c03eb88-9347-47ef-ba30-b6bcdcc99878.png)

### Logs

https://gist.github.com/Snorlax1337/cab0aecb17b8712db7258828e0e85772

### Anything else?

I have talked to MotionlessTrain on the MineColonis Discordserver and another person on the ID Discord server and they suggest i should open up a ticket to solve my issue.

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
To explain why I sent Snorlax to GitHub:
I'm not entirely sure whose side this is on (do we interpret their recipe in the wrong way, or did they implement it wrongly?)
In the latter case, they would like to speak one of the devs to solve it on their side

**Comment by uecasm** [comment]
`!datapack`

Press F3+H to enable advanced tooltips, which will show you the internal id of that facade item (it's likely just the one item id for all facades).

Make a datapack that adds it to the `*_ingredient_excluded` and/or `*_product_excluded` tag for each of the crafters where they show up (depending on whether they show up as inputs or outputs).
(Note that this won't just hide them from JEI, it will also prevent the crafter from learning that recipe.)

**Comment by Raycoms** [comment]
What are the tags of the facade block?

-------- Original Message --------

**Comment by Snorlax1337** [comment]
Picture as attachment.Is that all you need?Am 11.10.22, 11:03 schrieb Raycoms ***@***.***>:

   What are the tags of the facade block?
   
   -------- Original Message --------

**Comment by MotionlessTrain** [comment]
I don't think GitHub liked that picture.

Besides, this should be fixed already. It seems Github had some issues with comments via mail the other day, and those were added to issues too late

**Comment by uecasm** [comment]
Well, it's fixed in 1.19 at least.  It hasn't been backported to 1.18 yet.

**Comment by frquadrat** [comment]
hey, @uecasm
thanks for the info.
You don't happen to know the commit(s) or keywords to look for in order to (possibly!) enable me make a pull request for a backport?

thanks
