### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by Talyda** [ldtteam/minecolonies#8640]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

minecolonies-1.19.2-1.0.1012-ALPHA

### Structurize Version

structurize-1.19.2-1.0.443-ALPHA

### Related Mods and their Versions

blockui-1.19-0.0.61-ALPHA
domum_ornamentum-1.19-1.0.59-ALPHA-universal
multi-piston-1.19-1.2.16-ALPHA

ColonyVenture modpack/patreon server

### Current Behavior

Trying to start a build for a blueprint I made in creative SP on the server (A modified version of one of the megahalls) and as soon as I hit the check mark, I crash back to menu

In single player it is bringing up the regular UI, but it takes almost exactly 5 minutes from the time I click the check mark, to the time the UI shows up - but once it loads that once, I can bring it up immediately again until I restart the game

### Expected Behavior

No crashies

### Reproduction Steps

Scan thing
try to place thing

### Logs

https://gist.github.com/Talyda/3588f57659f435c59d4b9f2d4e5c6f26

### Anything else?

crash log:
https://gist.github.com/Talyda/e822e7d8ed6aeb9656967dc76e51a41c

**Comment by Talyda** [comment]
Is there a way to reopen this?  Or will y'all see it if I comment on it?

Or is a link to discord good enough?
https://discord.com/channels/472875599422291968/486940969737125922/1019022848297275433

*edits* Aha! You will see it =D

**Comment by Raycoms** [comment]
server log: https://gist.github.com/Raycoms/99da44ba5d8677adeedaf7e1e880708b
