### ISSUE TITLE
[BUG] Accessing LegacyRandomSource from multiple threads

### ISSUE THREAD

**Issue by niekschoemaker** [ldtteam/minecolonies#8641]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.0.1010-ALPHA

### Structurize Version

1.0.443-ALPHA

### Related Mods and their Versions

1. Forge Version 43.1.1
2. Stackrefill 2.3
Other mods don't seem to be relevant since they aren't referenced in the stack trace

### Reproduction Steps

This happened randomly, but happens when the citizen is idle, so randomly walking around, which is obvious from the stack trace.

I think the RandomSource has to be changed for a different version, so something like the thread safe variant of it.

### Logs

https://gist.github.com/niekschoemaker/3f807f0a0c08afd95199c1737ceca0b2

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
fixed
