### ISSUE TITLE
citizen icon rendering[BUG] <title>

### ISSUE THREAD

**Issue by lax556** [ldtteam/minecolonies#8642]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.19.2-1.0.1020 ALPHA

### Structurize Version

1.19.2-1.0.443-ALPHA

### Related Mods and their Versions

Forge: 43.1.15
multi piston: 1.12-1.2.16-ALPHA
domum: 1.10-1.0.59-ALPHA
oculus: 1.2.8
rubidium 0.6.2

### Current Behavior

Render Issue for citizen icons when using Oculus. This issue looks to be resolved in 1.18 via the PR: #8588 . Wondering if this can be ported to 1.19.2 [https://github.com/ldtteam/minecolonies/pull/8588](url)

### Expected Behavior

icons should not have rendering issues. 

### Reproduction Steps

happens when oculus/ rubidium is installed.

### Logs

N/A

### Anything else?

Thanks for keeping this mod up to date and everything you guys do!

**Comment by Raycoms** [comment]
done
