### ISSUE TITLE
Various dark oak problems

### ISSUE THREAD

**Issue by Rec0gnice** [ldtteam/minecolonies#8647]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.18.2-1.0.1029

### Structurize Version

1.18.2-1.0.424

### Current Behavior

When trying to build the _decorations:dark_oak:big_well{2,3}_ it will automatically fall back to the _big_well1_ as soon as  a builder picks up the request.

Also many _medieval_dark_oak_ buildings use Shingles with different support materials. For example dark oak planks on the sides and regular oak planks for the roof.

### Expected Behavior

1. It gets the building I selected with the build tool
2. The wood type is depending on the building theme and does not interchange

### Reproduction Steps

1. Build the mentioned wells
2. Build a medieval dark oak alternative builders hut level 3 for example

### Logs

N/A

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
The wells are an upgradeable decoration if they have numbers on the end, so yes, the builder will build level 1.
And the shingles thing is a left over from when the buildings were converted to the new system, you just have to use oak for now.

**Comment by Raycoms** [comment]
#5006 for schematic issues
