### ISSUE TITLE
[BUG] < Minecolonies 1.16.5-builder Ai has run into an issue>

### ISSUE THREAD

**Issue by SuiTheBabygirl** [ldtteam/minecolonies#8648]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.16.5-1.0.978-RELEASE

### Structurize Version

1.16.5-1.0.418-ALPHA

### Logs

https://gist.github.com/SuiTheBabygirl/a02558145ef1a9f5f32b72b52eadd62d

### Anything else?

!!Please read!! My minecraft version is 1.16.5 but there was no such option so I had to pick 1.18. instead.

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.
![IMG_6722](https://user-images.githubusercontent.com/92274270/189625950-438676fc-8cea-4333-8dc7-03a16a505253.jpg)

**Comment by Raycoms** [comment]
It's because 1.16 does not receive support anymore. Anyway, it might be because your superflat world is too low. The builder is trying to dig/place into the void. Also, your log is empty.

**Comment by SuiTheBabygirl** [comment]
> It's because 1.16 does not receive support anymore. Anyway, it might be because your superflat world is too low. The builder is trying to dig/place into the void. Also, your log is empty.

oh sorry i used the wrong log, i tried putting the right one now and it just crashed the site. Also i don't have superflat world i have biomes o plenty so that's not the issue

**Comment by SuiTheBabygirl** [comment]
well thank you for the help

**Comment by Raycoms** [comment]
Sorry, we can't provide support for old Minecraft versions forever.
