### ISSUE TITLE
[BUG] Multiple players not seeing the build menu with the build tool 

### ISSUE THREAD

**Issue by Roachamus** [ldtteam/minecolonies#8650]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

minecolonies-1.19.2-1.0.1032-ALPHA

### Structurize Version

structurize-1.19.2-1.0.443-ALPHA

### Related Mods and their Versions

Forge Version 43.1.3
blockui-1.19-0.0.61-ALPHA

### Current Behavior

No UI when using build tool

### Expected Behavior

I expect a UI to pop up when I use a build tool

### Reproduction Steps

Use build tool
No ui happens
Multiple people on my server have this issue 

### Logs

https://gist.github.com/Roachamus/ebfefb72f89c9529219e5d54595774d3

### Anything else?

Screenshot of the issue

https://user-images.githubusercontent.com/113257318/189806017-ee73682d-f452-4187-a153-76f80371a548.png

**Comment by Raycoms** [comment]
How many people on fabulous mode?

**Comment by Nightenom** [comment]
You have too much memory allocated for mc. 10 GB is really big overkill. You probably have corrupted files or sth like that, many files are reported as missing in your logs. The error is
```
[00:04:52] [Structurize IO Worker #0/ERROR]: Structurize IO Thread errored! 
java.lang.NoClassDefFoundError: org/codehaus/plexus/util/FileUtils
	at com.ldtteam.structurize.storage.ClientStructurePackLoader.lambda$onStructurePackTransfer$3(ClientStructurePackLoader.java:253) ~[structurize-1.19.2-1.0.443-ALPHA.jar%23228!/:1.19.2-1.0.443-ALPHA]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: org.codehaus.plexus.util.FileUtils
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.4.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.4.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 4 more
```
Which is either our ci fault or again corrupted file

**Comment by Roachamus** [comment]
It does not work on 4gb of ram and a fresh install for all users of server. Tries with 4 gb 5 gb 6 gb +

**Comment by Raycoms** [comment]
Which minecraft launcher are you using?

**Comment by Roachamus** [comment]
All users are using curseforge.

**Comment by Talyda** [comment]
The stuff that happened yesterday and how you go it to work might help as extra info Roach

**Comment by Roachamus** [comment]
We got it to work for one of our users by swapping to an account it worked on on her PC and it worked after that. Today its happening to other users on the server who do not have the ability to swap accounts.

**Comment by Raycoms** [comment]
and you're not on fabulous?

**Comment by Roachamus** [comment]
No users are on fabulous.

**Comment by Raycoms** [comment]
can you try updating forge/java ?

**Comment by Roachamus** [comment]
Manually update forge from 43.1.3? 

Java is on 17.0.4.1.

**Comment by Talyda** [comment]
Yesterday you said it was account specific - you tested the same (broken) account on different PC's - was it the same installation of curseforge/modpack? Like you just changed users in curseforge, but it all ran from the exact same place as the one that was working? (I don't know if that is important, but more information is always good =P)

**Comment by Raycoms** [comment]
It can't be account specific, it must be computer specific. This is a missing library that should be on there afaik.

**Comment by Roachamus** [comment]
> Yesterday you said it was account specific - you tested the same (broken) account on different PC's - was it the same installation of curseforge/modpack? Like you just changed users in curseforge, but it all ran from the exact same place as the one that was working? (I don't know if that is important, but more information is always good =P)

The broken account is broken on 3 different PCs except for one no matter what PC that log in on. 
 
 All PCs are using the latest curseforge pack. 
 All PCs are using the latest version of Java

**Comment by Roachamus** [comment]
Issue has been resolved for all players by swapping accounts with the player that have a working GUI. I have no idea why this fix is working.

**Comment by Raycoms** [comment]
So, logging in with a different account solves it?

**Comment by Roachamus** [comment]
An account that has a working UI seems to resolve it.

**Comment by Raycoms** [comment]
I'm not sure I understand.
Do you mean people are exchanging passwords and are logging in with the account fo another person, and with that it works, but not with their own. And after relogging it then works with their own too?

**Comment by Roachamus** [comment]
Correct currently played with a close group of friends and since it worked for one person we tried it with others and it worked.

**Comment by Raycoms** [comment]
can you try to tell people to switch to a different pack?

**Comment by Raycoms** [comment]
Is this in LAN mode?

**Comment by Roachamus** [comment]
This on a hosted server. Not LAN mode. The issue persists with different versions of 1.19.2 pack

**Comment by Terramup** [comment]
Have you tried having the users first start/load a single player game and then exit the world and start the multi-player.  For some reason that fixed the issue for me.

**Comment by Raycoms** [comment]
Solved
