### ISSUE TITLE
[BUG] Failed pathfinding + too far to mine

### ISSUE THREAD

**Issue by leagris** [ldtteam/minecolonies#8652]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.0.1012-ALPHA

### Structurize Version

1.0.443-ALPHA

### Related Mods and their Versions

blockui-1.19-0.0.61-ALPHA
domum_ornamentum-1.19-1.0.59-ALPHA-universal

### Current Behavior

Builder on the right is blocked forever not finding a path and not able to reach close enough to successfully shovel gravel.

There is a ravine in-between the gravel and the place he is standing at.

Builder reached the closest its path-finding algorithm could solve but not close enough to successfully be able to shovel/mine.
There was no close enough platform to teleport at either, so the result was the builder completely stuck unable to mine and unable to move close enough.

![2022-09-14_00 23 52](https://user-images.githubusercontent.com/1111474/190025546-5715d898-449c-42c7-aebd-d04e3b664ac8.png)

### Expected Behavior

There need to be a way a builder/miner to place blocks to cross a ravine or have an exemption of maximum distance if there is no way to reach the place to mine at. Being stuck is not a suitable situation.

### Reproduction Steps

1. Assign build task to builder at the other side of a ravine
2. Ensure there is no platform close to the build location
3. See builder stuck unable to mine, unable to teleport, unable to dig or build its way close enough.

### Logs

Irrelevant logs

### Anything else?

![image](https://user-images.githubusercontent.com/1111474/190026459-58c37df7-aefd-46fe-acd6-59d9b1551428.png)

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
I've only found one other report of this, but I'm certain I saw at least one more (might have been on patreon server?
https://discord.com/channels/139070364159311872/1003402487417548801/1018647344603988099
this is the other person I could find anyways

**Comment by Raycoms** [comment]
Honestly, I think stuck is alright, BUT they should communicate about it "I can't reach position x". If the player gives them an impossible task they can also build a quick tunnel/bridge
