### ISSUE TITLE
[BUG] Build tool previews going wonky

### ISSUE THREAD

**Issue by Revv1e** [ldtteam/minecolonies#8653]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.19.2-1.0.1032-ALPHA

### Structurize Version

1.19.2-1.0.443-ALPHA

### Current Behavior

When previewing other levels of a hut or decos with levels, if you rotate the level 1 preview, the previously clicked on levels will end up rotating in the wrong orientation. Also happens when you mirror the preview.

### Expected Behavior

When previewing other levels of a hut or decos with levels, the rotations and position/mirroring should remain consistent.

### Reproduction Steps

1. Grab a hut or a deco with levels.
2. Cycle through the other levels' previews.
3. Go back to the level 1 preview.
4. Rotate/Mirror the level 1 preview.
5. Click back on the other levels' previews.
6. Notice that they are now wonky and not aligned.

This does not happen if you keep your level 1 preview the same rotation, or if you rotate the level 1 preview first and then view the other levels' previews.

### Logs

https://pastebin.com/YCEr3as9

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
Just adding that I had noticed this happening several times, but was never able to work out how to reproduce it!

**Comment by Raycoms** [comment]
Fix pushed to structurize, will bump minecolonies soon
