### ISSUE TITLE
[BUG] <Warehouse from abbandoned villages doesn't act like double chest>

### ISSUE THREAD

**Issue by AVFD** [ldtteam/minecolonies#8655]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.19.2-1.0.1028

### Structurize Version

1.19.2-1.0.443

### Related Mods and their Versions

1. Forge: 1.19.2-43.1.25
2. Domum: 1.19-1.0.59
3. multi-piston: 1.19-1.2.16

### Current Behavior

Open or breaking a double Rack from a abbandoned warehouse doesn't give 2 Racks.

### Expected Behavior

Open or breaking a double Rack acts like one Rack. Only drop one Rack and when opened the UI is from one Rack too.

### Reproduction Steps

1. initialize a new world.
2. find a abbandoned village (in my caso was spruce).
3. find an abbandoned warehouse and break or open the racks after breaking the warehouse block.
4. get one rack UI when opened or one rack item when broken.

### Logs

https://pastebin.com/ebZ7VDJx

### Anything else?

The following images are from my test.

![founded rack](https://user-images.githubusercontent.com/18308993/190657209-f81af524-2e49-4a41-a42d-154b4282307b.png)

![breaking rack](https://user-images.githubusercontent.com/18308993/190657306-1e237abe-56c8-4991-bfee-5dedfa39f430.png)

![dropped rack](https://user-images.githubusercontent.com/18308993/190657386-eb33192a-98a6-4837-89cb-0168be58620a.png)

![picked rack](https://user-images.githubusercontent.com/18308993/190657422-474184a0-51db-4677-aa87-21359f574cca.png)

**Comment by MotionlessTrain** [comment]
Could you check whether there is still an invisible rack left at the spot next to where you broke it?

**Comment by Raycoms** [comment]
And can we check if this is a borked rack already in the scheme?

**Comment by AVFD** [comment]
I will check both..

**Comment by AVFD** [comment]
I have found some interesting things...

Next image show the actual pre-view of the building
![shcematic](https://user-images.githubusercontent.com/18308993/190682820-f08e5dac-48ca-44b1-b61c-edb43f2115af.png)

After put some itens in rack close it and open again, teh UI updated.
![att-UI](https://user-images.githubusercontent.com/18308993/190683012-a2a0db3f-229b-4b27-8cdf-4c5e57d6d708.png)

Another thing, breaking the left rack cause it to make a visual bug.
![visualBug](https://user-images.githubusercontent.com/18308993/190684206-7a1efcad-a842-43b0-bccf-2e45dfd44607.png)

I can make another tests if u want guys :)

**Comment by Raycoms** [comment]
This will also be fixed with the new rack changes
