### ISSUE TITLE
shingles glitch between upgrade levels

### ISSUE THREAD

**Issue by MetriCfan** [ldtteam/minecolonies#8669]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

server colony ventures 1.19.2

### Structurize Version

server colony ventures 1.19.2

### Related Mods and their Versions

server colony ventures 1.19.2

### Current Behavior

I am building with the Urban Acacia pack. I've noticed a few glitches with shingle types being supplied as one colour and being affixed as a different colour or the next level upgrade colour is being placed at an earlier upgrade level thus making it free.
When upgrading the Tavern to level 3 it ended up as purple cobblestone shingles which were never requested or supplied. (a form of red shingles can't remember exactly was supplied)
When upgrading the Town hall from 3 to 4 it affixed the level 5 upgrade shingle instead (blue shingles), more blue shingles were needed for the level 5 upgrade.
Level 5 Composter Hut finished up at level 5 with brown shingles that were never requested or supplied.
I have precise evidence of what happened when upgrading the Fishers Hut as I monitored the process from start to finish:
I have followed the process and can tell you exactly what has happened... up to level 3 all ok (brick extra shingles requested and affixed)
when upgrading to level 4 no shingles are requested or supplied but the builder changes them to the blue brick extra shingles,  the upgrade to level 5 was immediate with nothing needed... made my job easier not having to supply those blue shingles

### Expected Behavior

NA

### Reproduction Steps

NA

### Logs

NA

### Anything else?

NA

**Comment by Raycoms** [comment]
Fixed
