### ISSUE TITLE
[BUG] Custom crafts are not being reported as complete 

### ISSUE THREAD

**Issue by Saereth** [ldtteam/minecolonies#8671]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

minecolonies-1.18.2-1.0.1040-BETA

### Structurize Version

structurize-1.18.2-1.0.424-ALPHA

### Related Mods and their Versions

1. Forge 41.0.80

### Current Behavior

When given special recipes such as having the alchemist craft a custom item or having the blacksmith make a custom ingot when you request it from the post box they seem to craft it then put it on the shelf and the minecolonies seems to forget about it. It still shows as waiting to be fulfilled and given the materials the crafter will keep making them indefinitely. Only by searching all the surrounding racks to find it and then canceling the order does it stop. 

### Expected Behavior

I would expect the item to be marked completed after they craft it and for a courier to deliver it to the postbox

### Reproduction Steps

make a custom recipe for a crafter and teach it to them, give them the materials to make it then go order one from the post box

### Logs

https://gist.github.com/Saereth/693f85d93ccaf28e9750d583630a0af4

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
This has also been reported with books at the planter. So it seems not only custom recipes are affected
