### ISSUE TITLE
[BUG] Colony breaks creates blaze burners

### ISSUE THREAD

**Issue by Rosenblack** [ldtteam/minecolonies#8673]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.0.1044

### Structurize Version

1.0.424

### Related Mods and their Versions

Create 0.5.0.d

### Current Behavior

Before making a townhall and beginning a colony, blaze burners work fine, the moment a colony is made, you cant input anything into them, only manual right clicking works which breaks automation

### Expected Behavior

fuel consumed on blaze burner with deployer, hopper, just any item transport method, vanilla or not while having a running colony

### Reproduction Steps

1. start colony
2. use hopper/deployer on blaze burner with fuel

### Logs

https://gist.github.com/Rosenblack/9ef5471bda889c8a38f321e4e1923636

### Anything else?

doesnt seem to show anything in the log, acts like its meant to be that way

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Did you check with discord support on this? This can be solved in numerous ways, disabling anti grief for it, disabling it entirely, disabling it for the blockPos etc

**Comment by Raycoms** [comment]
closed, stale
