### ISSUE TITLE
[BUG] In-game JEI Information Menu on the Smelter falsely lists silk ore blocks as being Doubleable & Triplable.

### ISSUE THREAD

**Issue by JakeThatDog** [ldtteam/minecolonies#8679]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.0.1046-ALPHA

### Structurize Version

1.0.466-ALPHA

### Related Mods and their Versions

JEI Version 11.3.0.262

### Current Behavior

Raw Iron, Gold, and Copper ore chunks are all listed in the Just Enough Items information menu as being doublable or triplable per level of the smeltery.

### Expected Behavior

They should not be listed as such, since raw ores are excempt from the doubling rule, since they are not silked ore.

### Reproduction Steps

1. Open Just Enough Items on the most recent version of Minecolonies Official Modpack 
2. search "raw" in JAI to locate the raw ores, then right click them, and look in the "Smeltery" tab.

### Logs

https://paste.ee/p/60PgF

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
The description is for the crafter/building as a whole, not the specific recipe.  The raw items show up in the smelter's list because they do process them.  As they're not ores, the "doubles or triples ores" text does not apply to them.

Having said that, the text is a little outdated and probably should be updated for the new 1.18 mechanics.

**Comment by Raycoms** [comment]
Should probably say sth more specific like "Smelts this and breaks this into raw ores and applies fortune on it"
