### ISSUE TITLE
[BUG] Server config file keeps being rewritten

### ISSUE THREAD

**Issue by Saereth** [ldtteam/minecolonies#8680]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.0.1050-alpha

### Structurize Version

1.0.424-alpha

### Current Behavior

The server config file keeps rewriting itself every update. This wasnt happening a few minor versions ago. It keeps stripping all custom name settings and a few other settings that were changed such as supply camp loot etc. I've looked through the last set of half a dozen changelogs to see any reference to this but didnt see anything

### Expected Behavior

I would expect my custom naming settings to be preserved or an error thrown as to why they were rewritten 

### Reproduction Steps

Add in custom names in the config then start the server

![image](https://user-images.githubusercontent.com/9200909/193092878-13a65c3f-8732-4f0e-97f1-4e673ce4ac78.png)

### Logs

https://gist.github.com/Saereth/a385a28382e38749605fac0d3fb246af

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
The names actually did get all stripped out into datapacks in a recent update.

**Comment by Saereth** [comment]
ok that makes sense, doesnt seem like the wiki is updated yet, where can I find these?

**Comment by MotionlessTrain** [comment]
You would need to override [this](https://github.com/ldtteam/minecolonies/blob/version/main/src/main/resources/data/minecolonies/citizennames/default.json) datapack file
