### ISSUE TITLE
[BUG] Restaurant AI reported an issue

### ISSUE THREAD

**Issue by husk7777** [ldtteam/minecolonies#8681]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.0.1044-ALPHA

### Structurize Version

1.0.424-ALPHA

### Related Mods and their Versions

Forge 40.1.80
DO 1.0.55 -Alpha

### Logs

https://gist.github.com/husk7777/063a691448f8e0af25f2b16786058ac0

### Anything else?

pretty sure the error in question starts at line 6497 in the gist, but I submitted the whole log anyway. the name of the colonist is on line 6545

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
shouldve been fixed
