### ISSUE TITLE
Bakery not working[BUG] <title>

### ISSUE THREAD

**Issue by 1523dayo** [ldtteam/minecolonies#8687]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.19.2-1.0.1049-BETA

### Structurize Version

1.19.2-1.0.446-ALPHA

### Current Behavior

The baker wanders around the bakery and doesn't work.

### Expected Behavior

use the wheat to make dough and then use the fuel to make bread.

### Reproduction Steps

level 1 baker,level 1 restaurant
1 stacks of wheat in baker's inventory
1 stack of coal in baker's inventory

### Logs

Sorry, I don't know what the log is.

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
The baker does not automatically make anything.  You need to request bread or another item either via the postbox or via a minimum stock at the warehouse or restaurant.

**Comment by 1523dayo** [comment]
How did you request it?

**Comment by 1523dayo** [comment]
?

**Comment by MotionlessTrain** [comment]
Either with a postbox or with a minimum stock at the warehouse or restaurant

**Comment by 1523dayo** [comment]
In the warehouse, there are 5 stacks of wheat and 7 or more stacks of logs set as fuel.

**Comment by MotionlessTrain** [comment]
For support, please go to our [discord](https://discord.minecolonies.com)

The amount of stacks of wheat in the warehouse don't matter, if there is no request anywhere.
For that, you need to request bread yourself by postbox or set a minimum stock request of (1 stack of) bread at e.g. the warehouse or restaurant

**Comment by 1523dayo** [comment]
I wrote to Discord but didn't get a response, so I'll ask here.
The bakery keeps circling around the bakery even though I requested a minimum of 1 stack of bread in the warehouse.
