### ISSUE TITLE
[BUG] Breaking postbox destroys the items

### ISSUE THREAD

**Issue by Saereth** [ldtteam/minecolonies#8690]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

minecolonies-1.18.2-1.0.1050-ALPHA

### Structurize Version

structurize-1.18.2-1.0.424-ALPHA

### Current Behavior

Breaking a postbox that has items waiting to be picked up in it deletes the items.

### Expected Behavior

I would expect the items to go into my invetory or fall on the ground

### Reproduction Steps

place a post box, order items, once they're in the post box mine the post box with an axe, pickup the post box off the ground and replace it, items are gone from its inventory and never dropped on the ground

### Logs

https://gist.github.com/Saereth/748ec59073109fb6199f8bd4cbf22d64

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Is this still happening?

**Comment by Saereth** [comment]
just confirmed this does still happen. Upon breaking the post box it doesnt drop any of its inventory nor does it retain it if you place it back down. We've currently updated to minecolonies-1.18.2-1.0.1086-ALPHA and it's still happening on this version.

**Comment by Raycoms** [comment]
Sent from Proton Mail mobile

-------- Original Message --------

**Comment by Raycoms** [comment]
What do you use to break it?

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by Saereth** [comment]
TOP says axe so I used a diamond axe. It does return the post box to me though so I'm assuming it correctly broke

**Comment by Raycoms** [comment]
Does this also happen when you just: Place postbox, fill items, destroy?

**Comment by Saereth** [comment]
Yes

**Comment by Raycoms** [comment]
Did you by chance disable colony protection in the config?

**Comment by Raycoms** [comment]
and does this happen in your own colony?

**Comment by Saereth** [comment]
yes in my colony, havent tried doing it in someone else's colony
