### ISSUE TITLE
[BUG] Baker consumes an extra Cocoa Bean to craft Cookie Doughs

### ISSUE THREAD

**Issue by mc-kaishixiaxue** [ldtteam/minecolonies#8697]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.0.1050-alpha

### Structurize Version

1.0.424-alpha

### Current Behavior

After looking up the Cookie Dough's recipe and Cookie's vanilla recipe in JEI, I found the Baker crafts Cookie Doughs need 2 wheats and 2 cocoa beas, instead of 2 wheats and 1 cocoa bean. The former consumes one more cocoa bean than the latter.
I don't know if it's a quantity error.

### Expected Behavior

Right recipe: 2 wheats + 1 cocoa bean = 8 cookie doughs, the ingredients are same as vanilla.

### Reproduction Steps

1. Look up the Cookie Dough's recipe in JEI;
2. Then look up the vanilla Cookie's recipe.

### Logs

https://pastebin.com/5i1h5cQv

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Not a bug
