### ISSUE TITLE
[BUG] the waypoint can not be removed

### ISSUE THREAD

**Issue by Unokoneko** [ldtteam/minecolonies#8700]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

minecolonies-1.18.2-1.0.966-RELEASE

### Structurize Version

structurize-1.18.2-1.0.424-ALPHA

### Related Mods and their Versions

1.Forge version : 40.1.80
2.blockui-1.18.2-0.0.62-ALPHA
3.domum_ornamentum-1.18.2-1.0.50-ALPHA-universal
4.multi-piston-1.18.2-1.2.15-ALPHA

### Current Behavior

the citizens are keep jumping when they passing the trapdoor which as ornaments on huts, so I try to built a waypoint by using building tool, but on a second thought, I wish to remove it. No matter what I did, including the issues were reported earlier, placing a solid block, dig it out, the waypoint just can not be remove. And the citizens keep standing on it for a while everytime they passing by, it's a nightmare. what should I do?
please help me T.T
![QQ截图20221009100554](https://user-images.githubusercontent.com/115382832/194734755-16ad5330-9c3b-4109-9e96-54a004dd4321.png)
![QQ截图20221009101936](https://user-images.githubusercontent.com/115382832/194734758-b4b499df-021d-4e48-b8b9-553272f9fc48.png)

### Expected Behavior

just remove the waypoint..?

### Reproduction Steps

just remove the waypoint..?

### Logs

no logs

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
How long did you put a solid block into it and waited?

**Comment by Unokoneko** [comment]
10 mins in each different ways, I've read the issues which were reported by other people, so I tried them all.

**Comment by Raycoms** [comment]
do you have a lot of waypoints?

**Comment by Unokoneko** [comment]
No, I just built two to see how it works.
