### ISSUE TITLE
[BUG] Error in assigning buildings

### ISSUE THREAD

**Issue by Revv1e** [ldtteam/minecolonies#8701]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [ ] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

minecolonies-1.19.2-1.0.1060-ALPHA

### Structurize Version

structurize-1.19.2-1.0.452-ALPHA

### Current Behavior

When using the build tool to assign a deco build to a specific builder, it doesn't get assigned, have been having to go to the hut itself and manually give them the order to build. Only happens with decos.

### Expected Behavior

The builder should getting assigned when selected in the menu for the build tool.

### Reproduction Steps

1. Using the build tool, select a deco.
2. Assign to a specific worker.
3. Press the checkmark.
4. Go to the builder's hut and see that they are not assigned.
5. Be sad.

### Logs

https://gist.github.com/Revv1e/20ba3bc04530ea0344e1afcccf4ddbc5

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
solved at least now
