### ISSUE TITLE
[BUG] Serverconfig keeps resetting with Custom Names

### ISSUE THREAD

**Issue by Dubslash** [ldtteam/minecolonies#8704]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.0.1048-BETA

### Structurize Version

1.0.424-ALPHA

### Related Mods and their Versions

Forge Version: 40.1.73

Mods:
absentbydesign 1.6.2
AdvancementPlaques 1.4.5.1
AI-Improvements 0.5.0
alexsmobs-1.18.6
AmbientSounds_FORGE_v5.0.16
appleskin-forge 2.4.1
architectury-4.9.84-forge
AutoRegLib-1.7-53
badpackets-forge-0.1.2
balm-3.2.0+0
blockui 0.0.62-ALPHA
Bookshelf-Forge 13.2.50
carryon 1.17.0.8
chat_heads-0.6.1
citadel-1.11.3
ClearDespawn-forge 1.1.7
cloth-config-6.4.90-forge
Clumps-forge 8.0.0+15
collective 5.0
configured-2.0.0
Controlling-forge 9.0+22
cookingforblockheads-forge 12.0.2
CraftTweaker-forge 9.1.193
create 0.5.0.e
CreativeCore_FORGE_v2.6.15
creeperoverhaul 1.3.0-forge
defaultoptions-forge 14.1.1
domum_ornamentum 1.0.50-ALPHA-universal
eatinganimation 2.1.1
fancymenu_forge_2.12.2-1
FarmersDelight 1.2.0
farsight 1.9
farsightedmobs-forge-1.1
feature_nbt_deadlock_be_gone_forge-2.0.0
ferritecore-4.2.1-forge
flywheel-forge 0.6.5
FpsReducer2-forge 2.0
GameMenuModOption Forge-1.14.1
geckolib-forge 3.0.40
Iceberg forge-1.0.48
Incendium_v5.0.4
inventorysorter 19.0.0
jei 9.7.1.255
JEITweaker 3.0.0.9
JustEnoughResources 0.14.1.171
konkrete_forge_1.5.1
kotlinforforge-3.7.1-obf
lazydfu-1.0
loadmyresources_1.0.1
lootr 0.2.21.58
Mantle 1.9.27
minecolonies 1.0.1048-BETA
MouseTweaks-forge 2.21
multi-piston 1.2.15-ALPHA
MyServerIsCompatible 1.0
no_null_processors_forge-2.0.2
Oh_The_Biomes_You'll_Go-forge 1.4.4
polymorph-forge 0.45
Quark-3.2-358
repurposed_structures_forge-5.1.14
ServerTabInfo 1.3.5
simplylight 1.4.5-build.43
spark-1.9.11-forge
stackrefill 3.0
StorageDrawers 10.2.1
structurize 1.0.424-ALPHA
TerraBlender-forge 1.2.0.126
The_Graveyard_1.9.2
The_Undergarden 0.7.1
TreeChop 0.15.7
waystones-forge 10.1.0
worldedit-mod-7.2.10
WorldPreGenerator 3.0.1
wthit-forge-4.13.3
Xaeros_Minimap_22.15.1
XaerosWorldMap_1.28.0
YungsApi Forge-2.0.8
YungsBetterStrongholds Forge-2.1.1

### Current Behavior

1. Server starts with Custom Names in minecolonies-server.toml
2. Detects a change in file and replaces with a default file

[11Oct2022 16:13:48.313] [Server thread/DEBUG] [net.minecraftforge.fml.config.ConfigFileTypeHandler/CONFIG]: Loaded TOML config file ./world/serverconfig/minecolonies-server.toml
[11Oct2022 16:13:48.313] [Server thread/DEBUG] [net.minecraftforge.fml.config.ConfigFileTypeHandler/CONFIG]: Watching TOML config file ./world/serverconfig/minecolonies-server.toml for changes
[11Oct2022 16:13:48.314] [Server thread/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: **Configuration file ./world/serverconfig/minecolonies-server.toml is not correct. Correcting**
[11Oct2022 16:13:48.315] [Server thread/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Incorrect key names was corrected from SimpleCommentedConfig:{usemiddleinitial=false, useeasternnameorder=false, malefirstnames=[...], femalefirstnames=[...], lastnames=[...]} **to its default, null.** 
[11Oct2022 16:13:48.316] [Thread-0/DEBUG] [net.minecraftforge.fml.config.ConfigFileTypeHandler/CONFIG]: **Config file minecolonies-server.toml changed, sending notifies**

### Expected Behavior

Server starts without resetting the minecolonies-server.toml

### Reproduction Steps

1. Download Custom Names Template
2. Open minecolonies-server.toml
3. Add Custom Names Template before everything
4. Save
5. Start the Server

### Logs

https://gist.github.com/Dubslash/bdffb6e0ee8742372c16426c8a64cff8

### Anything else?

(I hope its not Forge or some "default file" being compared)

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
Those work via datapacks now

**Comment by MotionlessTrain** [comment]
More information about that in #8680 (for which this is a duplicate)

**Comment by Dubslash** [comment]
Oh ok, thank you!
And sorry, i should remove the filter is:open next time...
