### ISSUE TITLE
[colonies not placeable in other dimensions] <minecraft 1.15.2>

### ISSUE THREAD

**Issue by Levenoss** [ldtteam/minecolonies#8709]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

latest

### Structurize Version

0.13.109-APLPHA

### Current Behavior

Even after setting allowotherdimcolonies = true it still wont work for me im currently in a modded dimension called the mirror dimension the forge version is 31.2.57 and the game version is 1.15.2 not 1.18 and its a server too 

### Expected Behavior

change false to true and have it actually be true

### Reproduction Steps

1.use the mirror dimension and try to place anything related to mine colonies like a supply camp and it wont work

### Logs

there's nothing to put the game didn't crash 

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
1.15.2 is not supported anymore. Things have changed since then, and bugs related to placing colonies in dimensions have probably been solved since then
