### ISSUE TITLE
Desert Oasis Mechanic Hut level 5 requires a creative version of the firework rocket

### ISSUE THREAD

**Issue by MetriCfan** [ldtteam/minecolonies#8710]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

colony ventures server 1.8

### Structurize Version

colony ventures server 1.8

### Related Mods and their Versions

colony ventures server 1.8

### Current Behavior

NA

### Expected Behavior

the title says it all
cannot obtain the required item in survival
Desert Oasis Mechanic Hut level 5 requires a creative version of the firework rocket

### Reproduction Steps

NA

### Logs

NA

### Anything else?

NA

**Comment by MotionlessTrain** [comment]
#5006 for schematic issues
