### ISSUE TITLE
[BUG] There is no crafter who can create build tool

### ISSUE THREAD

**Issue by uhloin** [ldtteam/minecolonies#8717]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.0.1071

### Structurize Version

1.0.452

### Related Mods and their Versions

Minecraft 1.19.2, forge

### Current Behavior

Carpenter, stonemason, blacksmith, fletcher cannot craft "build tool" item.

### Expected Behavior

Carpenter and stonemason should allow receipt for build tool for example for racks.

### Reproduction Steps

-

### Logs

-

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
The only person that needs a build tool is you =) Carpenter doesn't need one to make racks =)

**Comment by uhloin** [comment]
Thank you!
