### ISSUE TITLE
Hut Blocks destroyed

### ISSUE THREAD

**Issue by Inomutso** [ldtteam/minecolonies#8718]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

minecolonies-1.19.2-1.0.1073-BETA

### Structurize Version

structurize-1.19.2-1.0.452-ALPHA

### Related Mods and their Versions

forge-1.19.2-43.1.1
blockui-1.19-0.0.64-ALPHA
domum_ornamentum-1.19-1.0.59-ALPHA-universal
multi-piston-1.19-1.2.16-ALPHA
jei-1.19.1-forge-11.2.0.241
worldedit-mod-7.2.11

### Current Behavior

Hi guys

Today I made an update from minecolonies-1.19.2-1.0.1070-ALPHA to minecolonies-1.19.2-1.0.1073-BETA.

After starting the installation, there were no residents and no more Hut blocks, all empty.
Other blocks from my paths and in the houses were also missing.

We had that years ago, I think under 1.16...

Will bring back my backup and re-enable minecolonies-1.19.2-1.0.1070-ALPHA

The system has not written a Debug.log (!)

The current colony is a single player world, no modpack used

latest.log from today is here

s://gist.github.com/Inomutso/291d315f671c03f8559d558d9fc144c5

### Expected Behavior

should be my colonie again, with all my citizens

### Reproduction Steps

do a full backup
update to minecolonies-1.19.2-1.0.1073-BETA
start the colony

### Logs

https://gist.github.com/Inomutso/291d315f671c03f8559d558d9fc144c5

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
It looks like you started up vanilla minecraft by accident, not forge

**Comment by Inomutso** [comment]
uh, sorry for that, saw it now too, you're right
started the Minecraft full version without Forge in the launcher
my son was visiting...

can be closed, everything ok after the update
