### ISSUE TITLE
Builders dont swap grass block with coarse dirt when building

### ISSUE THREAD

**Issue by carlansor** [ldtteam/minecolonies#872]
### Minecolonies version

version minecolonies-universal-1.11-0.6.3360

### Expected behavior

- Builder should place coarse dirt where there are grass blocks

### Actual behaviour

- Builder doesn't place coarse dirt where there is a grass block on the spot, leaving the grass block but requering still the coarse dirt block.

### Steps to reproduce the problem

1. Place a building with coarse dirt with grass blocks on the same spots
2. Wait for the builder to ask for materials
3. Builder builds the building but leaves grass blocks on coarse spots

**Comment by Raycoms** [comment]
Fixed already, will be fixed in the next update
