### ISSUE TITLE
[BUG] Forester Struggles to Replant Dark Oak

### ISSUE THREAD

**Issue by PvtPuddles** [ldtteam/minecolonies#8721]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.0.1073-BETA

### Structurize Version

1.0.457-ALPHA

### Related Mods and their Versions

Forge 43.1.1

### Current Behavior

The forester does not always successfully replant dark oak trees.

Because the trees require 4 saplings, the forester does not always have them (either the tree didn't drop enough, or more likely they despawned/were picked up by someone else while the forester was chopping)

### Expected Behavior

If the forester does not have enough saplings to replant a tree, they should request some or pick them up from their hut.  Alternatively, they could be able to produce saplings from thin air in order to replant trees (simpler, makes jungle tree farming more reliable).

(Bonus, this will allow them to request nether mushrooms, so should lead to those trees being farmable as well with a little extra work)

### Reproduction Steps

1. Have a forester chop down a dark oak tree but not get enough saplings
2. The forester will plant the 1-3 remaining saplings, but be unable to complete the pattern to grow a new tree.

### Logs

No relevant logging

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
A new setting got added, "Break Leaves", which should improve the sapling yield for dark oak (make sure to turn shears off!)
