### ISSUE TITLE
Wheat Extra Shingles not recoginised

### ISSUE THREAD

**Issue by CorykriegNZ92** [ldtteam/minecolonies#8724]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

ColonyVenture-1.9.zip

### Structurize Version

 structurize-1.19.2-1.0.457-ALPHA.jar

### Current Behavior

Wheat Extra shingles are not recognized by builder when placed in builder inventory after they have been requested for the tier 1 Medieval Oak restaurant. Have also tried standard wheat shingle which also doesn't work. 
![error1](https://user-images.githubusercontent.com/116445748/197344982-0ee20b0c-7df6-4004-8f86-916bc9bb491a.png)
![error2](https://user-images.githubusercontent.com/116445748/197344985-00d96591-21f2-43db-ab94-4816e2d31d64.png)

### Expected Behavior

The item recognised by the builder when placed into their inventory or the builders hut

### Reproduction Steps

Start a normal survival game. Have a builder start work on the Medieval Oak Restaurant then try to place Wheat Extra Shingles in an observed inventory for the builder to recognize 

### Logs

https://aka.ms/snapshotbugs?ref=game

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
Read the tooltip of the item the builder requests carefully. They probably don't want single slabs supported by wheat extra

**Comment by CorykriegNZ92** [comment]
Discovered the issue was using all wheat extra in the architects cutter where planks should have been used instead. Is this method perhaps a little over specific? I found it difficult to understand this was what it meant or needed as the only indication for it is visual. 
![fix1](https://user-images.githubusercontent.com/116445748/197368836-6a7c468f-dd51-4875-9f79-ce78d1f34968.png)
