### ISSUE TITLE
[BUG] Game crahses when i open Domum Ornamentum tab on creative mod and when i search it on JEI

### ISSUE THREAD

**Issue by hllous** [ldtteam/minecolonies#8725]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

minecolonies-1.19.2-1.0.1073-BETA

### Structurize Version

structurize-1.19.2-1.0.458-ALPHA

### Related Mods and their Versions

domum_ornamentum-1.19-1.0.58-ALPHA-universal
jei-1.19.2-forge-11.3.0.271

### Current Behavior

Basically, my game runs until i find something related with domum ornamentum mod.
![image](https://user-images.githubusercontent.com/116463450/197361968-8d78e509-2269-43dc-853c-16b3956ca5a7.png)

### Expected Behavior

The expected behavior would be that when i look up in jei something from the domum ornamentum mod, the game does not crash.

### Reproduction Steps

1. Open Minecraft
2. Create a New World
3. Gamemode creative and go to the domum ornamentum tab
4. Crash

### Logs

https://gist.github.com/hllous/a30948a50c6eea6311f13cb0f580ad43

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
Don't use optifine if you have it

**Comment by hllous** [comment]
> Don't use optifine if you have it

oh, that was it hahahaha. Thanks!
and bye bye optifine

**Comment by KhalidVG** [comment]
> 

I have the same issue but is there any way to fix it without removing optifine ?

**Comment by MotionlessTrain** [comment]
Until optifine fixes their compatibility with forge, no
