### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by LetsMCLP** [ldtteam/minecolonies#8728]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

minecolonies-1.18.2-1.0.1048-BETA

### Structurize Version

1.18.2

### Related Mods and their Versions

Forge: forge-1.18.2-40.1.80-installer.jar

### Logs

https://pastebin.com/jUqLUqxA

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
The server lagged to death

**Comment by Raycoms** [comment]
Wasn't us, was very slow mojang chunk access
