### ISSUE TITLE
Suggestion: Player's house and new building chest

### ISSUE THREAD

**Issue by DcNdrew** [ldtteam/minecolonies#873]
I think there should be a house - build by builders of course - where the player can live, and you can connect to the deliveries of the town.

I thought two ways. First: add an option to the civil house, to disable its using as a colonist's house, so it won't add to the max population, but it can be upgraded as well, and you can use it for yourself.

The second way is a new building, the "player's house", "major's house", "crafter's house", or something else. It can be the same as the civil houses, but as a new type of house, it can be different too.

Either way there will be the building chest what can be maintained by deliverymen, so you won't have to run along the town if you want to send your wares to the colonists. Tools, raw material and so.

And there should be an option in the building chest, called wishlist (or what the workers use already), where you can set what kind of materials do you want and if it's available, deliverymen will bring them.

I think these are based on existing solutions, so it shouldn't be complicated to add.

The other thing:
I suggest to change the block of the building chest. It should be more accurate in placement and facing. So you won't have to test where would be the buildings faced and where will be the chest.
For example when you place townhall, it will be two blocks higher than the base of the building; so if you place it just like the others, the stairs at the entrance will be digged into the ground. Not to mention while the townhall's front door will be in the way where you are facing, some other buildings entrance will be just behind you. This isn't the best way. And of course these chests aren't seem to be part of the building.

This is why I suggest a new block, something like what I suggested here:
http://www.minecolonies.com/publicforum/m/18051739/viewthread/30077190-new-building-chest

**Comment by Raycoms** [comment]
You can upload decorations and let them be a player house.

If you want to drop of things you can drop it off in any chest, dman chest, citizen hut etc.


The rotation depends on how things are scanned in.

And we hope that people use the build tool which will actually help you to adjust every building.
Besides that there is little we can do to improve this.
