### ISSUE TITLE
[BUG] Builder dont accept items

### ISSUE THREAD

**Issue by MarobsKoco** [ldtteam/minecolonies#8733]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.0.1080

### Structurize Version

1.0.424

### Related Mods and their Versions

1. Forge: 1.18.2 - 40.1.84
2. BlockUI: 1.18.2 - 0.0.62 Alpha
3. Domum Ornamentum: 1.18.2 - 1.0.55 Alpha
4. 

### Current Behavior

Builder Upgrading Wooden Mechanic from lever 1 to level 2: needs clock and compass, made and givin, but wont accept them. put also in warehous, but wont get requested. stays on: player need to solve

### Expected Behavior

Builder should just accept the normale compass and clock from minecraft but wont

### Reproduction Steps

build colonie, try wooden mechanic
upgrade wooden machanic to level 2,
builder ask for clock and commpass and wont accept

### Logs

http:\\nolog

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
You probably have quark installed; that does weird things to clocks and compasses.  You need to give them a clock or compass that has never been in your own inventory -- Either teach a mechanic how to craft it, use some other auto-crafting mechanism that doesn't require you to carry the item, or craft-n-drop without ever holding it yourself.
Alternatively, turn off the "compasses work everywhere" setting in the quark config and then also make a new clock or compass

**Comment by MarobsKoco** [comment]
Thnx, i didnt know that quark would do that. so i solved it with the auto crafting from refinedstorage, nice that the head block of the warehouse can see all the storage, putted an extern storage on it :D
