### ISSUE TITLE
[BUG] Construction Tapes turn into other blocks

### ISSUE THREAD

**Issue by MKr4zy** [ldtteam/minecolonies#8734]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.0.1080

### Structurize Version

1.0.424

### Related Mods and their Versions

1. Forge: 40.1.84
2. BlockUI: 0.0.62
3. Dormum Ornamentum: 1.0.50

### Current Behavior

![image](https://user-images.githubusercontent.com/33859570/198854010-2e192a42-485c-4463-8a74-f741cc9953e7.png)
When placing Blocks, they turn into other Blocks. Upon right-clicking them, they turn into the right block.
If I place another block for example another construction tape, they both "break" again.

### Expected Behavior

Don't turn into other blocks

### Reproduction Steps

Place multiple Construction Tapes next to each other.

### Logs

https://gist.github.com/MKr4zy/7514528cff9918fad07cb84924e70be6

### Anything else?

Server Log:
https://gist.github.com/MKr4zy/e0ee4609ffcb1e95c7dfa998e7f4fe54

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
I'll close this here as this is 1000% not a minecolonies issue but some other mod causing it, please try removing other mods to see which mod is causing this and then report it to them.
