### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by Devils-Cat** [ldtteam/minecolonies#8735]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.8

### Structurize Version

1.8

### Related Mods and their Versions

this is a modpack in tlauncher(first page of all)

### Reproduction Steps

i just play last 3 weeks and bug was start without any reasons

### Logs

file:///C:/Users/lqwerpl/AppData/Roaming/.minecraft/logs/latest.log

### Anything else?

my courier don't see any things in storage, don't deliver from builders(but deliver another villagers) and i can't change another courier because the button 'see unemployed' not pressed(but on another objects all is good)
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
We don't support tlauncher at all, as it is a cracked client. Please use the official launcher instead, or the curseforge launcher
