### ISSUE TITLE
[Question] How do I put a scanned decoration on a server?

### ISSUE THREAD

**Issue by belathus** [ldtteam/minecolonies#874]
### Minecolonies version
version 2-0.6.112

Just curious. I tried putting it is ./minecraft/minecolonies/decoration/, but that does not appear to have worked. I did see that I supposedly could put it in the world folder, but this is going to be for a modpack, and I'd like to have these decorations available to other worlds. (I admit, I didn't test that part out.)

**Comment by Raycoms** [comment]
Are you on 1.11 or on 1.10?

2017-04-27 21:23 GMT-03:00 Andrew Sage <notifications@github.com>:

**Comment by belathus** [comment]
1.10.

**Comment by Raycoms** [comment]
For now you have to put it in the jar you send to your players.
But in a 1.11 version we'll release soon it will be way easier.
The 1.10 will need a bit to receive the update.

2017-04-27 21:28 GMT-03:00 Andrew Sage <notifications@github.com>:

**Comment by belathus** [comment]
Gotcha. And bummer.

**Comment by Raycoms** [comment]
But I think in at most 2 weeks that feature will be out for 1.10 as well.

2017-04-27 21:44 GMT-03:00 Andrew Sage <notifications@github.com>:

**Comment by belathus** [comment]
Good to hear. I look forward to it, then.

**Comment by xavierh** [comment]
It has been ported to 1.10 but did not had time to test yet. 2 weeks sound about right!
