### ISSUE TITLE
[BUG] <Glitched Skin>

### ISSUE THREAD

**Issue by Dylbert93** [ldtteam/minecolonies#8741]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.0.1088-ALPHA

### Structurize Version

1.0.459-ALPHA

### Related Mods and their Versions

The Official Modpack v1.12

### Current Behavior

My nether miners skin stopped working, Im using the Medeval Patron skins. It worked in 1.11 of the pack
The Colonist is Female. would have to test male.
I got Flying_Kitty2 to look at the Colonist on her end and it was bugged aswell

### Expected Behavior

A skin

### Reproduction Steps

My Colony is Fort Clover on the 1.19 server so you can just log in and look at it

### Logs

https://gist.github.com/Dylbert93/179a6a5bf2f348274631f5ed5316b2bd

### Anything else?

![2022-11-01_06 21 13](https://user-images.githubusercontent.com/111447206/199097596-f2cc38a3-8ee4-4746-ac43-f68ba6bd3dc5.png)

![2022-11-01_06 21 17](https://user-images.githubusercontent.com/111447206/199097614-802fc387-4629-49f7-936f-a32290aa415d.png)

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
fixed
