### ISSUE TITLE
Home sweet home advancement does not work

### ISSUE THREAD

**Issue by uhloin** [ldtteam/minecolonies#8742]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

minecolonies-1.19.2-1.0.1088-ALPHA.jar

### Structurize Version

structurize-1.19.2-1.0.452-ALPHA.jar

### Related Mods and their Versions

forge-1.19.2-43.1.47-installer.jar 

### Current Behavior

Advancement "Home sweet home" does not work.
Details.
In my colony I built some houses some time ago and 2 days ago found I have no this advancement. I thought I need at least one level 5 home. I build it but did not get advancement message. 

It was on the version 1082 because I do not like halloween citizens. Just for case I upgraded to latest version 1088 and restart minecraft but did not get advancement message. 

Another bug: halloween is gone but those ugly citizens are still there so I am going to rollback to 1082.

### Expected Behavior

-

### Reproduction Steps

-

### Logs

-

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uhloin** [comment]
After update 1082 ALPHA-> 1097 BETA achiement does not fixed.  I tried some reset with "repair" + "cancel repair" for residence but without effect.

Also I have no first 2 achievements "MineColonies" and "Start Your Colony". I've started it without "supply camp", but just crafted build tool and place Town Hall.

**Comment by Raycoms** [comment]
This is fixed in latest upcoming alpha, not current beta

**Comment by Raycoms** [comment]
Also, It might not be always possible to get the achievements with old ones missing.

**Comment by uhloin** [comment]
Thank you for explanation. 
Could you say approximate time when zombie-halloween skins will be removed?

**Comment by Raycoms** [comment]
Were removed with the same alpha =D

**Comment by uhloin** [comment]
I'am happy! :)

Here Builder asked to say you about pain in his brains. See attachment.
[bug.txt](https://github.com/ldtteam/minecolonies/files/9946583/bug.txt)

**Comment by Raycoms** [comment]
fix pushed, next time new issue please =D
