### ISSUE TITLE
[BUG] <Advancements related to huts/build tool are not working>

### ISSUE THREAD

**Issue by 8coachm** [ldtteam/minecolonies#8747]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.0.1088-ALPHA

### Structurize Version

1.0.459-ALPHA

### Current Behavior

Advancements that involves the player using the build tool to place down a hut block (e.g. Start Your Colony, The Builder Begins, most advancements in Production and Militia tab, etc.) is not working.
Advancements which are not involved with build tool works fine (e.g. Minecolonies, Check Out The Guide, Another Mouth to Feed, Last Resort, etc.)

This was listed as fixed [here](https://github.com/ldtteam/minecolonies/issues/8591) back in August, but it seems the problem is back

### Expected Behavior

Advancements are granted once the requirements have been met

### Reproduction Steps

1. Place down the town hall block using build tool
2. Check if the advancement "Start Your Colony" was granted

1. Place down the builder's hut using build tool
2. Check if the advancement "The Builder Begins" was granted

### Logs

N/A

**Comment by MotionlessTrain** [comment]
The "start a colony" advancement should be given when you actually start a colony.
The "builder begins" should be given when the builder actually starts building.
Most of the other building advancement are given when the building is built, not when the hut block is placed
