### ISSUE TITLE
[BUG] There are times when you get stuck in the GUI while providing items

### ISSUE THREAD

**Issue by gjmhmm8** [ldtteam/minecolonies#8749]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

minecolonies-1.18.2-1.0.1048-BETA

### Structurize Version

structurize-1.18.2-1.0.424-ALPHA

### Current Behavior

A concise description of what you're experiencing. Please provide screenshots and videos if possible.

### Expected Behavior

close the gui

### Reproduction Steps

open the builder house's gui ,provision of items, sonetimes it will get stuck in the GUI

### Logs

None

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
how does this happen and how does "getting stuck" look like?

**Comment by Raycoms** [comment]
No response
