### ISSUE TITLE
Deliveryman to Farmer

### ISSUE THREAD

**Issue by wilsondgonzales** [ldtteam/minecolonies#875]
### Minecolonies version

1.11.2 updated

### Expected behavior

- Deliveryman gets seeds from warehouse to deliver to the farmer

### Actual behaviour

- seeds get ignored

### Steps to reproduce the problem

1. build farm, delivery hut, warehouse, field
2. prep the field to accept seed, farmer requests for seeds
3. .seeds don't get delivered
4. Profit

**Comment by marvin-bitterlich** [comment]
How long have you waited? Are there other things the deliveryman is busy with?

**Comment by wilsondgonzales** [comment]
I had 2 delivery men and watched them in the air do 3 circuits from warehouse to every structure (including farmer) and then back to warehouse. I have dev features on so i can see on their tags when they go from gathering to dumping

**Comment by wilsondgonzales** [comment]
deliveryman seems to also ignore the farmer's request for carrots and melon seeds. they deliver tools no problem though

**Comment by neadlak** [comment]
I've just gotten farmer and warehouse online. I will go take away his seeds and put them in warehouse and observe behavior.

**Comment by neadlak** [comment]
I do see this in 0.7.4.2.1, with Harvestcraft disabled. Took all seeds from farmer, put them in warehouse. Farmer calls for seeds, Deliveryman has at least 1 real hour to respond (he is only covering 3 buildings) and does not make a delivery.

My farmer was requesting seeds for wheat with >4 stacks in the warehouse.
