### ISSUE TITLE
Multiplayer LAN server university research tab not working for owner, only for the host.

### ISSUE THREAD

**Issue by 40mboudreaux** [ldtteam/minecolonies#8751]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.0.1048 beta

### Structurize Version

1.0.424 alpha

### Current Behavior

I am playing on a LAN server with my daughter as the host.  I made a minecolony and have both my daughter and my wife as officers in the colony. I built the spruce university but I am unable to tell my colonists what to research. My daughter is the only one on the world that can access the research tab and tell them what to research no other players can do it no matter what rank they are in the colony.  I have tried destroying the university and building another one, firing and hiring new researchers, repairing the university and removing other players from my colony so I am the only one controlling it.  The first image is my daughter the host opening the research tab. The second image is what I see. 
![2022-11-04_08 44 49](https://user-images.githubusercontent.com/66912768/200000981-09f27c55-184e-4c8e-b566-591937ed54f0.png)
![2022-11-04_08 44 26](https://user-images.githubusercontent.com/66912768/200003150-d4f64999-1aec-4f35-b401-c0757f16aef2.png)

### Expected Behavior

I expect to be able to see the research tab in my own colony no matter if I am the host or just a player on a multiplayer server.

### Reproduction Steps

start a LAN server
Someone other than the host make a colony
Build a spruce university
See if you can access the research tab in your university.
make the host an officer of your colony
see if they can access the research tab in your univerity

### Logs

<script src="https://gist.github.com/40mboudreaux/415d0273f2de18a46e186788195547c5.js"></script>

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
duplicate: https://github.com/ldtteam/minecolonies/issues/8301

LAN mode is very wonky with modded Minecraft in general. we always advice people to run a local server.
