### ISSUE TITLE
[BUG] Disease curing

### ISSUE THREAD

**Issue by Teddy-Kun** [ldtteam/minecolonies#8752]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.0.1094-ALPHA

### Structurize Version

1.0.459-ALPHA

### Related Mods and their Versions

1. Forge: 43.1.47
2. BlockUI: 0.0.64-ALPHA
3. Donum Ornamentum: 1.0.64-ALPHA

### Current Behavior

After a colonist contracts a disease he prompts you to give him certain items to cure him/her.
These items do not cure said colonist instead only a golden apple does so.

### Expected Behavior

Either the items given to said colonist cure him, or the prompt needs to be changed.

### Reproduction Steps

1.  Get a sick colonist
2. Give prompted items (in my case I noticed it with carrot+potato, I also had one that required a golden apple+honey and that of course worked)
3. after a few seconds or when inspecting the inventory of the colonist you will get your items back and they will stay ill

### Logs

https://gist.github.com/Teddy-Kun/da67a62adf34cd35327360cd2d29ba40

### Anything else?

Note: The log is a server log from a bigger modpack. It is therefore pretty big, so to make it a bit easier, I briefly looked at the code and the Golden Apple seems to be hard coded as the cure item for any illness (file: src/main/java/com/minecolonies/coremod/entity/citizen/EntityCitizen.java | line: 461).

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
You can either right click on them with a golden apple (that is the code you found), or open their inventory and put the cure items there. Note that if you right click on them with the carrot and/or potato, there is a risk that you are feeding them instead.

Also note that if they are hungry as well, they could see the carrot as food, and eat that instead of start healing
