### ISSUE TITLE
[BUG] Builder ran into an issue

### ISSUE THREAD

**Issue by EmmiPigen** [ldtteam/minecolonies#8757]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.19.2-1.0.1106

### Structurize Version

1.19.2-1.0.459

### Related Mods and their Versions

Forge: 43.1.47
BlockUI: 1.19-0.0.64
Domun: 1.19-1.0.73
Muti-Piston: 1.19.2-1.2.19

### Reproduction Steps

Let builder work on a building

### Logs

https://gist.github.com/EmmiPigen/4338fb765a241310f0e11dad7c475542

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
The version of this log is 1.0.1102 not the latest 1106 where this is fixed
