### ISSUE TITLE
Building tool upgrade glitch

### ISSUE THREAD

**Issue by SivartMcDorf** [ldtteam/minecolonies#8764]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.19.2-1.0.1094-alpha

### Structurize Version

1.19.2-1.0.459-alpha

### Current Behavior

When you start building a building, then later cancel the build after it has started.  When you go back to select build/upgrade it jumps to the next level.  

I have 3 guard towers partially built at level 2 with level 3 tops.  I also have a level 1 warehouse with 3 blocks laid that I can now upgrade to level 2.

### Expected Behavior

self explanatory self-explanatory

### Reproduction Steps

see current behavior

### Logs

n/a 

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Which schematics exactly? I couldn't reproduce this

**Comment by SivartMcDorf** [comment]
I have had it happen and posted several pictures in the chat to many guard towers and several upgradable decos (Fortress BTW)

https://discord.com/channels/139070364159311872/915411448342118441/1040710125096288276

**Comment by Raycoms** [comment]
Do you have any good way to reproduce it yet?

**Comment by Raycoms** [comment]
So what happens here is probably that somehow world data is lost on a crash or similar situations. Our data is kept and the build progress is erased. Thats the only way I can see this happen. Please re-open once you got a reproducable way
