### ISSUE TITLE
[BUG] Huts with super long names don't show level

### ISSUE THREAD

**Issue by anonymous563** [ldtteam/minecolonies#8778]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.19.2-1.0.1122-ALPHA

### Structurize Version

1.19.2-1.0.460-ALPHA

### Current Behavior

The alchemist hut's name does not show its level, though other buildings with short-ish names do. 
As per MT's comment, if the name is "Alchemist's Tower," then the full name of the building still isn't showing. In either case, buildings with names that are too long don't look quite right.

![image](https://user-images.githubusercontent.com/34487065/202983275-ee5795a5-fce7-4384-b108-fc38733ded30.png)

### Expected Behavior

It should show the level of the building to the right of the name, or at least the full building name.

### Reproduction Steps

1. Start a new colony.
2. Paste in an alchemist hut in creative mode (or build one normally).
3. Right-click the hut block and look at its title.

### Logs

N/A

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
Isn't the full name "Alchemist's tower"? In that case, the issue is that the name is too long

**Comment by anonymous563** [comment]
Updated!
