### ISSUE TITLE
[BUG] Datapack elements not working properly for new research/branch

### ISSUE THREAD

**Issue by Shadizar** [ldtteam/minecolonies#8780]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.0.1122-ALPHA

### Structurize Version

1.0.460-ALPHA

### Related Mods and their Versions

Forge 43.1.52
Blockui 0.0.64-ALPHA
DO 1.0.75-ALPHA

### Current Behavior

In game observe University UI after the indicated repro steps.

1/Despite having the lowest sort order, the new item is at the bottom. (the others are in order of ascending sort order from top to bottom).
2/branch-name is not properly used, instead it shows as "Arsnouveau" in the UI.
3/subtitle is not taking effect; mousing over branches does not show any mouseover text.

### Expected Behavior

1/New research item to be top of sort order.
2/branch-name properly used, showing as "Ars Nouveau" in the UI.
3/subtitle causing mousing over branches to show proper mouseover text.

### Reproduction Steps

Create a research branch.
{
  "branch-name": "Ars Nouveau",
  "subtitle": "Used by Archwood Collective (and potentially others)",
  "base-time": 1.0,
  "sortOrder": 25
}

Start Minecraft and see section Current Behavior

### Logs

https://gist.github.com/Shadizar/04f74dbbe5c336e893ffa8bbafd45b7c

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Shadizar** [comment]
![image](https://user-images.githubusercontent.com/94550408/203224815-d40d3786-9c9b-4517-a995-5bf999a25f59.png)

**Comment by Raycoms** [comment]
https://imgur.com/cfirag4.png

Tried with exactly this and it worked fine for me.

**Comment by Shadizar** [comment]
I'll check again shortly, it was not working for me yesterday still, I think.  Will confirm

**Comment by Shadizar** [comment]
I don't understand... it is still not working for me in 1207 alpha


![image](https://user-images.githubusercontent.com/94550408/215280216-b0652a63-b120-4683-bc4b-74cce058f882.png)


archwoodcollectivedatapack\data\archwoodcollective\researches\arsnouveau.json : 
{
  "branch-name": "Ars Nouveau",
  "subtitle": "Used by Archwood Collective (and potentially others)",
  "base-time": 1.0,
  "sortOrder": 25
}

My name in UI still shows as Arsnouveau ; and still has no tooltip, and is still at the bottom

**Comment by Raycoms** [comment]
@uecasm any idea? I tried some local datapacks and they worked out perfectly

**Comment by Shadizar** [comment]
I also have \archwoodcollectivedatapack\data\archwoodcollective\researches\arsnouveau\arscraftingrecipes.json
I assume it's  out of  scope of the bug listed but including it for reference

{
  "branch": "minecolonies:arsnouveau",
  "name": "Ars Crafting Recipes",
  "researchLevel": 1,
  "subtitle": "Unlocks automatically-learned Ars Nouveau crafting recipes. Really only exists to keep from cluttering your recipes if you are not doing an Ars Nouveau style.",
  "icon": "ars_nouveau:relay",
  "requirements": [
    {
      "item": "ars_nouveau:source_gem",
      "quantity": 4
    }
  ]
}

![image](https://user-images.githubusercontent.com/94550408/215281880-a196855d-c9dc-4073-bc1c-cf48a98fb4ed.png)

**Comment by Shadizar** [comment]
Let me know if there is anything I can do to help

**Comment by Shadizar** [comment]
Per item in questions 1.19 ⁠questions-1․19⁠ https://discord.com/channels/139070364159311872/1003402520846139533/1129111326426402947
I still think https://github.com/ldtteam/minecolonies/issues/8780 is still occurring.
It still happens for me on all instances I create.
Any idea why some folks are still not seeing things correctly for this research from my datapack? ( https://github.com/Shadizar/archwoodcollectivedatapack ) 
I think this is still a legit bug, can it be reopened?
