### ISSUE TITLE
[BUG] <Raiders loot bug?>

### ISSUE THREAD

**Issue by CubeTwo** [ldtteam/minecolonies#8785]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.19.2-1.0.1124-ALPHA

### Structurize Version

1.19.2-1.0.460-ALPHA

### Related Mods and their Versions

1.forge 43.1.52
2.minecolonies-1.19.2-1.0.1124-ALPHA
3.domum_ornamentum-1.19-1.0.75-ALPHA-universal
4.structurize-1.19.2-1.0.460-ALPHA
5.multi-piston-1.19.2-1.2.19-ALPHA
6.blockui-1.19-0.0.64-ALPHA
7.Apotheosis-1.19.2-6.0.1
8.Nameless Trinkets-1.19.2-1.6.9

### Current Behavior

dont know on which side is this but Apotheosis dev? redirected( #https://github.com/Shadows-of-Fire/Apotheosis/issues/725#issue-1463297175) to your mod.
 if you have all items with + 5-8 luck and sword with looting 3, you kill raiders from "MineColonies" thay drop like 10-15 items, if you have crown from "Nameless Trinkets" +50% all stats or +120% all stats thay drops like 50 -70 items from 1 mob
screenshots: https://imgur.com/a/YAjIUtA

### Expected Behavior

mob drops just few items, not 50-70 items

### Reproduction Steps

get items with +6-8 luck from Apotheosis,
get sword with looting 3 or higher and kill raiders, and you get like 4-15 items from 1 raider 
if you get trinket +50 or +120% all stats from Nameless Trinkets, raiders drops like 50-70 items

### Logs

https://gist.github.com/CubeTwo/82c48f3cf9fede9b0bd6854ce978e193

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
´´´
{
  "pools": [
    {
      "name": "minecolonies:barbarian",
      "rolls": 1,
      "bonus_rolls": 1,
      "entries": [
        {
          "type": "empty",
          "weight": 80
        },
        {
          "type": "item",
          "weight": 1,
          "name": "minecraft:diamond_axe"
        },
        {
          "type": "item",
          "weight": 2,
          "name": "minecraft:golden_axe"
        },
        {
          "type": "item",
          "weight": 5,
          "name": "minecraft:iron_axe"
        },
        {
          "type": "item",
          "weight": 6,
          "name": "minecraft:stone_axe"
        },
        {
          "type": "item",
          "weight": 3,
          "name": "minecolonies:ancienttome"
        }
      ]
    }
  ]
}

´´´

This is just a normal loot table, I guess Apotheosis gives extra rolls even though we mention only one here. I dont think this is a bug on our side.

**Comment by Diversion98** [comment]
@Raycoms 

can you look at this please?
https://github.com/Shadows-of-Fire/Apotheosis/issues/725

**Comment by Raycoms** [comment]
Our loottable is normal, there is nothing on our side

**Comment by uecasm** [comment]
bonus_rolls = 1 means that 1 extra item is generated per point of luck on the killing guard/player.  Floating point values are allowed (and used in other places, such as sifting loot).

Most vanilla mobs seem to have bonus_rolls = 0.  (Actually, I couldn't find any vanilla loot tables that have a non-zero bonus value at all.)  There isn't a lot of info around about player luck, except that it typically ranges from -1 to 1 in vanilla AFAIK -- luck potions are hard to come by (actually impossible, without mods or cheating) and don't change the value much.  So it is probably still a bug/OP in apotheosis if it allows significantly higher luck values.

Not sure if this is a regression, but as far as I can tell guards don't pass on any luck value for their kills, so they never get bonus rolls anyway.  And vanilla luck usually only affects fishing, not other loot.  So perhaps we could just reduce this to 0 on our end?  Then the luck effect is irrelevant.

**Comment by Diversion98** [comment]
> Our loottable is normal, there is nothing on our side

well there is nothing on apoth's side as i gave myself 100 luck through "/attribute" and still got hundreds of weapons from the barbarians. (this was just for testing purposes)
I'll just alter the loottables in my modpack then to not drop any weapons

**Comment by Raycoms** [comment]
Nothing should give these insane amounts of luck imo

**Comment by Diversion98** [comment]
> Nothing should give these insane amounts of luck imo

no true, but it is possible to get 30+ luck easily in modded environments
event with botania alone getting to 100+luck is easy to do
