### ISSUE TITLE
[BUG] Attempting to travel through Iron Gates with certain items in your hand or off-hand causes the gate to close when you are 1-2 blocks away.

### ISSUE THREAD

**Issue by Pewmaymen** [ldtteam/minecolonies#8788]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.19.2-1.0.1124-ALPHA

### Structurize Version

1.19.2-1.0.460-ALPHA

### Related Mods and their Versions

1. Forge Version: 43.1.47
2. BlockUI Version: 1.19-0.0.64-ALPHA
3. Domum Ornamentum: 1.19-1.0.75-ALPHA
4. Multi-Piston Version: 1.19.2-1.2.19-ALPHA

### Current Behavior

When you approach a Minecolonies Iron Gate that is closed with certain items in your primary or off hand and right click on it, it opens as expected.  However, as you get within 1-2 blocks of the open Iron Gate, the gate spontaneously closes and you are blocked.  Attempting to open the gate while within 1-2 blocks causes the gate to flash, make the gate opening sound and close immediately.  If you time it just right and approach while sprinting, you can "make it" through the gate before it closes all the way.
Items in hand include the following but this is by no means an exhaustive list:
Vanilla Torches
Vanilla Redstone Torches
MineColonies Stash boxes

Items tested that do not cause issues, whether in the primary or off hand, are:
Tools such as picks and shovels regardless of material to make them
Weapons regardless of material
Placeable blocks such as cobblestone, stone, and dirt (not all blocks were tested, just a sampling)
Soul Torches (these strangely do NOT cause the issue).
Vanilla lanterns
Food items, cooked or otherwise, including Steak/beef, Pork/pork chops, rabbit/cooked rabbit, etc.  Not all were tested.

This occurs whether the colony is owned by the person affected or not.  I have not tested Minecolonies wooden gates.
This occurs in a superflat world with creative mode on so it is really easy to recreate.

### Expected Behavior

Iron Gates that are open as you approach them stay open unless closed by an action of a player or a citizen, allowing the player to pass through.

### Reproduction Steps

1. Create a structure with a minecolonies Iron gate.
2. Hold a torch or redstone torch in your primary hand.
3. Approach the gate and right click as soon as you can access the hitbox.
4. Continue to walk towards the gate.  
5. Notice that as you get within 1-2 blocks, the gate closes, preventing you from passing through.
6. Repeat with the item in the off-hand and note the behavior is the same.
7. Repeat with the item in your inventory but not in hand and note that the behavior does not occur.

### Logs

https://gist.github.com/Pewmaymen/8cad447431a6a48f7a625246b13497db

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
I can't reproduce this in single-player with only MineColonies and dependencies.  Does this only happen on server, or with another specific mod installed?

**Comment by Pewmaymen** [comment]
I am not sure if other mods would be an issue.  I have others installed.  I can recreate this on survival and creative single player with regular and superflat worlds (I noted this in my update).  There was another person who reported the issue with stashes causing the same issue.

**Comment by uecasm** [comment]
Can you please try to reproduce it in an instance with only mcol and dependents installed too?  If it works fine there, then you can do a bisection search by gradually adding and removing mods from your original instance until you've found which one triggers it.  (If you need more info on how to do that, you can ask on the Discord.)

**Comment by Pewmaymen** [comment]
I can't recreate with just the four minecolonies mods (minecolonies and it's three dependencies).  It will take time for me to do a bisection run.  I will try to get to it and will update when I find the mismatch.

**Comment by someaddons** [comment]
its probably some mod or effect, triggering redstone signals around you

**Comment by Pewmaymen** [comment]
I figured out the mod.  It is AtomicStrykerGrumpy's Dynamic Lights.  When you said it was something sending redstone signals and I combined that with the fact it only happened with torches and redstone torches, I realized it was most likely something that affected lighting in some way.  That was the most obvious mod I could think of. 
I guess the only thing that is odd is that other things affected by redstone like doors (wooden, iron, etc), trapdoors, pressure plates, etc are not affected.  Is there something different about the gates from Minecolonies that causes them to be affected?  Is there some redstone sensitivity? Or is it the way they work with the hitbox in the center that triggers the door open/close mechanism (that seems likely to me)?

**Comment by uecasm** [comment]
Looking at how that mod works, it appears to turn air blocks near the player into invisible light blocks.  The gate tends to have a _lot_ more air blocks adjacent to it than doors or trapdoors.  But you probably could get those (or other redstone-operated devices) to misbehave too if you manage to get its light block into exactly the "wrong" spot.

In any case, the bug is that for some inexplicable reason they've made those invisible light blocks emit a full-strength redstone signal as well, and you should report that as a bug to them.  And/or just stop using that mod.
