### ISSUE TITLE
[BUG] Nether Mine Missing Building Scematic

### ISSUE THREAD

**Issue by pro-game-coder** [ldtteam/minecolonies#8794]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.0.1129-ALPHA

### Structurize Version

1.0.460-ALPHA

### Related Mods and their Versions

1. forge

### Current Behavior

For some reason I cant build the Nether Mine, even when I place down the block itself, when I right clicked the block it said that it was missing the Respected Building.

### Expected Behavior

it was supposed to build, although i was using Creative at the time.

### Reproduction Steps

1. ! don't know how this happened or how to reproduce it.
2. .
3. .

### Logs

https://gist.github.com/pro-game-coder/c639c73de13246f6eef23af8b80daf73

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
Use the build tool to place it down.
Indeed not all styles have a nether miner, as not all style designers have had time yet to make one. You can just build one from another style

**Comment by pro-game-coder** [comment]
> Use the build tool to place it down. Indeed not all styles have a nether miner, as not all style designers have had time yet to make one. You can just build one from another style

oh thank you for the info
