### ISSUE TITLE
[BUG] Missing text / description for Level 2 Civilian Technology, 'Ambition' row

### ISSUE THREAD

**Issue by yusifsaladin** [ldtteam/minecolonies#8798]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.18.2-1.0.1123-ALPHA

### Structurize Version

1.18.2-1.0.424-ALPHA

### Related Mods and their Versions

Running Forge 40.1.85, on modded server/client,

### Current Behavior

In Civilian techs, the description of the 2nd level of the 'Ambition' row has bugged out slightly?  

The name displays as "com.minecolonies.research.civilian.air.name", with it's description as "com.minecolonies.research.effects.air.description" (requirements 1 heart of the sea)

No other in game issues noted, hopefully just a minor display issue.

### Expected Behavior

Normal name / description

(according to very helpful person on discord, I believe this is a new tech relating to time citizens can be underwater?)

### Reproduction Steps

Open research tree, go to 'Civilian', check description of level 2 Ambition.

### Logs

n/a

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments
![2022-12-03_09 11 44](https://user-images.githubusercontent.com/50356671/205402852-17bcee2c-ccb3-4559-b775-107241f0ddad.png)
.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
fixed
