### ISSUE TITLE
[Wrong Translation] Error in Brazilian-Portuguese translation (pt_br)

### ISSUE THREAD

**Issue by FITFC** [ldtteam/minecolonies#8800]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.19.2-1.0.1129-ALPHA

### Structurize Version

1.19.2-1.0.462-ALPHA

### Current Behavior

The description is wrong calling it "tesoura de poda" and the correct one is just "tesoura"
Crowdin: https://crowdin.com/translate/minecolonies/42/en-ptbr?filter=basic&value=0#5482

ref: https://minecraft.fandom.com/pt/wiki/Tesoura

I opened a warning about the translation and no one had fixed it yet, so I resorted to github

### Expected Behavior

~~

### Reproduction Steps

~~

### Logs

~~

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
translate.minecolonies.com please for translations
