### ISSUE TITLE
[BUG] missing respective building when on my private server

### ISSUE THREAD

**Issue by Chazzie** [ldtteam/minecolonies#8806]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.0.1132-ALPHA

### Structurize Version

1.0.467-BETA

### Related Mods and their Versions

1. Forge Version: 1.19.2 - 43.1.65
2. Multi-Piston: 1.19.2-1.2.21-ALPHA
3. Blocks-UI: 1.19-0.0.64-ALPHA
4. Domum Ornamentum: 1.19-1.0.75-ALPHA

### Current Behavior

so when placing down new buildings on my private server i can't even interact with them due to this:
missing the respective building, try restarting or loading an backup.
and due to that i can't build them
when i try to restore buildings that were in the village already before i settled there it works
i tried waiting for an few minutes but sadly this message still pops up

### Expected Behavior

that i could interact with the new placed buildings to build them

### Reproduction Steps

1. make an server on an server host (i used PebbleHost Budget plan)
2. try to find an abandoned town and settle there using its town hall
3. place down for example an forester hut but not repair one (but could be something else as well due to none of them works)
4. interact with it
5. try to wait an few minutes to 1 hour and it still shows the same message

### Logs

https://pastebin.com/FXJWkXcw

### Anything else?

in singleplayer it works fine just not multiplayer

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
How did you place down that forester's hut?

**Comment by Chazzie** [comment]
just by right clicking the ground with it

**Comment by MotionlessTrain** [comment]
Use a build tool to place it. That will also show a preview, which helps making sure it doesn't collide with other buildings, and that it isn't placed too high or too low

**Comment by Chazzie** [comment]
ok i will try that and come back to you

**Comment by Chazzie** [comment]
> Use a build tool to place it. That will also show a preview, which helps making sure it doesn't collide with other buildings, and that it isn't placed too high or too low

apparantly that worked to fix my issue. need to remember myself to use the build tool from now on
