### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by bbrk53** [ldtteam/minecolonies#8807]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1,12,2

### Structurize Version

1.12.2

### Related Mods and their Versions

forge 1.12.2*

### Reproduction Steps

*i download the mod *
*i download the other mod
*i open minecraft mod verson 1.12.2 
*i join a world 
*a message pops up and i click it away
*it pops up again and again every 2 seconds in 1.12.2

### Logs

minecraft 1.12.2

### Anything else?

plz fix the mod for minecraft 1.12.2* it is a error pop up

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
1.12.2 is not supported anymore
