### ISSUE TITLE
Lost Mesa City - Recipe counts 1/2 what it should be

### ISSUE THREAD

**Issue by smmmadden** [ldtteam/minecolonies#8809]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

minecolonies-1.19.2-1.0.1132-BETA

### Structurize Version

1.0.467-BETA

### Related Mods and their Versions

Forge: 43.1.65
BlockUI: 0.0.64-ALPHA
Domum Ornamemtum: 1.0.75-ALPHA
MultiPiston: 1.2.21-ALPHA
MineColonies: 1.0.1132-BETA
Structurize: 1.0.467-BETA

### Current Behavior

went to craft the recipes for the Builder Huts, but the max shown at level 5 for Lost City Mesa are all set to 48 when it should be 96 like other packs.
![image](https://user-images.githubusercontent.com/10309346/206615434-688738a6-4d8f-45bc-80d2-aa993f949324.png)
![image](https://user-images.githubusercontent.com/10309346/206615479-752e8a4b-b738-4ed7-9c13-431c48e5ef05.png)

### Expected Behavior

![image](https://user-images.githubusercontent.com/10309346/206616208-2590e7d4-8654-4edc-826b-bc89bc8c2a04.png)
![image](https://user-images.githubusercontent.com/10309346/206616221-8fdf79ac-fe9a-4fab-bd9c-ab1fab747add.png)

### Reproduction Steps

just need to build a Lost City Mesa builders hut (I have 4 and all are the same 48 max)

### Logs

N/A

### Anything else?

nothing else

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by smmmadden** [comment]
Just checked my wife's build and Urban Birch is worse at 32 max recipes

**Comment by uecasm** [comment]
The number of max recipes is completely unrelated to the style.  It does change based on the level of the building and based on which research has been done.

**Comment by MotionlessTrain** [comment]
What is the name of that builder's hut? (Can be found on the top of the main tab of the builder's hut)

**Comment by uecasm** [comment]
FWIW, assuming they're all level 5 builders, 32 recipes max is normal if you have not done any research.  48 max means you've done two of the recipe-count researches, and 96 max means you've done all of them.

Usually that's way more recipes than you'll ever need; I think I only ever teach my builders about 5 recipes in total; the rest it's better to give to regular crafters.

**Comment by smmmadden** [comment]
Confirmed - I realized that while the builders hut was at level 5, there was a missed research done in the University (also level 5) and once that got completed, the recipes jumped to 96 as expected.  Sorry for false alarm, my bad. :-(
