### ISSUE TITLE
Inconsistent Crafter assignment.

### ISSUE THREAD

**Issue by Moobien** [ldtteam/minecolonies#8810]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1135

### Structurize Version

468

### Related Mods and their Versions

n/a

### Current Behavior

There is inconsistencies among certain craftable items.  The wiki states the following for pressure plates.

"The Carpenter is a part of your colony’s production line. The Carpenter can learn 3x3 recipes made of at least 75% wood that do not include ingots, stone, redstone (or produce a redstone signal), or string. "

Pressure plates, being an item that emits redstone, is a mechanic item.  Buttons on the other hand are craftable by sawmill/stonemason.  This is inconsistent with other comparable items.

### Expected Behavior

Suggestion: move buttons to mechanic where they will be consistent with pressure plates or move pressure plates from mechanic to their respective material crafter.

### Reproduction Steps

n/a

### Logs

n/a

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
Buttons are almost never actually used as redstone signal generators in colonies.  Pressure plates are (for pens/doors).

**Comment by Moobien** [comment]
Yes but the inconsistency is still there and should be addressed.

And used for table tops too.

**Comment by uecasm** [comment]
The above is a reason why it makes sense as is, which counts as addressing it.  But I didn't close it so you can wait to see what Ray thinks too if you like.

**Comment by Moobien** [comment]
Its still causing confusion in the support channels, thats all.

**Comment by McKitten** [comment]
I do believe that just because something is colony specific, does not give it the right to be uniquely placed.
Two other things to consider 
1) On scale the use of pressure plates for redstone is also minimal compared to how many table tops are produced.
2) The level at which the plates are requested is much lower than a mechanic's availability.

I counter propose removing the no-redstone requirement for all items which contain wood. If there is a recipe limit than move rack's out of the carpenter ;)

**Comment by MotionlessTrain** [comment]
I don't think *all* redstone items containing wood should be teachable to the carpenter. The note block makes sense it would be a mechanic item, since it actually contains redstone

**Comment by McKitten** [comment]
> I don't think _all_ redstone items containing wood should be teachable to the carpenter. The note block makes sense it would be a mechanic item, since it actually contains redstone

sounds fair.

**Comment by Moobien** [comment]
> I don't think _all_ redstone items containing wood should be teachable to the carpenter. The note block makes sense it would be a mechanic item, since it actually contains redstone

yeah. thats why I think pressure plates should be moved to sawmill/stonemason or buttons moved to mechanic, that will make it all more consistent.

**Comment by Raycoms** [comment]
I'd probably move the buttons to the mechanic then. Both can be made by the builder anyway too
