### ISSUE TITLE
[Wrong Translation] Error in Brazilian-Portuguese translation (pt_br)

### ISSUE THREAD

**Issue by FITFC** [ldtteam/minecolonies#8814]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.19.2-1.0.1129-ALPHA

### Structurize Version

1.19.2-1.0.462-ALPHA

### Current Behavior

The description is wrong calling it "tesoura de poda" and the correct one is just "tesoura"
https://translate.minecolonies.com/translate/minecolonies/42/en-ptbr?filter=basic&value=0#5482

The description is wrong calling it "Demoluir" and the correct one is just "Demolir" (Demoluir does not exist in Portuguese)
https://translate.minecolonies.com/translate/minecolonies/42/en-ptbr?filter=basic&value=0#q=Demoluir
Ref: https://www.dicio.com.br/demolir/

The description is wrong calling it "Chamar os cidadãos" and the correct one is just "Chamar cidadãos" (It's cutting the button because it has too many characters, the old translation supports the correct amount of characters)
https://translate.minecolonies.com/translate/minecolonies/42/en-ptbr?filter=advanced&value=12&verbal_expression_scope=translations&comments=have_comments&sort_method=3#4912

Capitalization correction
https://translate.minecolonies.com/translate/minecolonies/42/en-ptbr?filter=advanced&value=12&verbal_expression_scope=translations&comments=have_comments&sort_method=3#4486

Fixes for female NPCs to be represented in dialogs
https://translate.minecolonies.com/translate/minecolonies/42/en-ptbr?filter=advanced&value=12&verbal_expression_scope=translations&comments=have_comments&sort_method=3#4842

Context is wrong for this dialog
https://translate.minecolonies.com/translate/minecolonies/42/en-ptbr?filter=advanced&value=12&verbal_expression_scope=translations&comments=have_comments&sort_method=3#5770

"morreu no" is wrong, the correct is "morreu em" because it is a position not a cause
https://translate.minecolonies.com/translate/minecolonies/42/en-ptbr?filter=advanced&value=12&verbal_expression_scope=translations&comments=have_comments&sort_method=3#4560

The current translation is too big and keeps cutting, that solves it.
https://translate.minecolonies.com/translate/minecolonies/42/en-ptbr?filter=advanced&value=12&verbal_expression_scope=translations&comments=have_comments&sort_method=3#5204

"Recursos requeridos" is better than "Recursos Solicitado" for dialog context
https://translate.minecolonies.com/translate/minecolonies/42/en-ptbr?filter=advanced&value=12&verbal_expression_scope=translations&comments=have_comments&sort_method=3#5032

The translation is more pleasant to read in the way I suggested
https://translate.minecolonies.com/translate/minecolonies/42/en-ptbr?filter=advanced&value=12&verbal_expression_scope=translations&comments=have_comments&sort_method=3#6652

"Recrutar para" this context is wrong, the dialog that uses this is when talking to the npc's in the tavern, and the way it is suggests that it is for work and not an exchange, between "give me item X" to hire.
https://translate.minecolonies.com/translate/minecolonies/42/en-ptbr?filter=advanced&value=12&verbal_expression_scope=translations&comments=have_comments&sort_method=3#7220

Too large text is clipping, the suggestion I sent is better and it fits the button perfectly.
https://translate.minecolonies.com/translate/minecolonies/42/en-ptbr?filter=advanced&value=12&verbal_expression_scope=translations&comments=have_comments&sort_method=3#6318

If possible, I become a translation reviewer, as I am always checking how the game button looks and the contexts in which they are.

Unfortunately the translation that is approved contains serious errors and were not even checked as they were on the mod buttons.

### Expected Behavior

~~

### Reproduction Steps

~~

### Logs

~~

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Please only adjust on crowdin, not on here
