### ISSUE TITLE
[BUG] Unable to upgrade Shire TavernRestaurant beyond level3

### ISSUE THREAD

**Issue by leagris** [ldtteam/minecolonies#8815]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.19.2-1.0.1135-ALPHA

### Structurize Version

1.19.2-1.0.467-BETA

### Current Behavior

Tavern is at max level 3
but TavernRestaurant refuses to upgrade to level4

The build menu only proposes repair.

### Expected Behavior

Should be upgradable up to level 4, then 5.

### Reproduction Steps

- Place and upgrade to max Shire style tavern alt containing the `tavernrestaurant` sub-structure.
- Upgrade restaurant and find it refuses to upgrade beyond level 3.

### Logs

irrelevant

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Spumantii** [comment]
Never mind, I need more coffee

**Comment by Spumantii** [comment]
![image](https://user-images.githubusercontent.com/114318715/208578630-51dee5d9-eca5-4856-8570-bf4fb0721f63.png)

Child dorm schematic

![image](https://user-images.githubusercontent.com/114318715/208578762-dda1fa0e-e0af-4202-a95b-05d22444c339.png)

Child dorm at lvl 5 (end stone creeper panel)

**Comment by Spumantii** [comment]
![image](https://user-images.githubusercontent.com/114318715/208579372-5f160544-c41a-42f0-a4df-63e4209cf18a.png)
Here's the parent, we're upgrading to lvl 2, normal build items shown
![image](https://user-images.githubusercontent.com/114318715/208581317-e759079a-74d8-4f3b-b134-6b89c0f1a1d8.png)
Building lvl 2 of parent, showing children mid build, all respective huts found

![image](https://user-images.githubusercontent.com/114318715/208583029-0f5e4156-40a0-4d90-bcd3-475c9f7df13a.png)
After finishing lvl 2 of the parent, the child gets upgrade option

**Comment by Spumantii** [comment]
![image](https://user-images.githubusercontent.com/114318715/208583388-43998c82-7362-4dcf-862e-0106ed909bed.png)
Upgraded the child room to 2, now it loses the upgrade option again, until the parent is upgraded again.  Somehow, upgrading multiple children at the same time as the parent can cause the parent to take on the build list from the child, trying to reproduce

**Comment by Spumantii** [comment]
![Uploading image.png…]()
On holiday server

**Comment by MotionlessTrain** [comment]
> Similar behavior in Byzantine Insulaes. Children can't be asked to upgrade beyond the level of the parent- though the schematics are found

It is intended that a child building cannot be upgraded beyond the level of the parent building.
The only exception to that rule is when the parent building is at its maximum level (E.g. the tavern at level 3), and the child building has more levels than the parent.
That is that is happening on the holiday server, and something that isn't completely working (which is the reason this issue exists)

**Comment by krjencik** [comment]
same issue : minecolonies-1.19.2-1.0.1198-ALPHA

**Comment by rmlgray** [comment]
This issue is still present in 1.20.1, just had it. Or atleast a version of it. My entire tavern cannot go past Tavern 3 due to this bug.

**Comment by Nik-Was** [comment]
> My entire tavern cannot go past Tavern 3 due to this bug.

Not a bug, taverns only have 3 levels.

**Comment by MotionlessTrain** [comment]
The original bug was about the included restaurant in the Shire tavern, not about the tavern itself

**Comment by rmlgray** [comment]
> > My entire tavern cannot go past Tavern 3 due to this bug.
> 
> Not a bug, taverns only have 3 levels.

Oh shoot, I thought everything went to level 5, is there any other ones like that?

**Comment by MotionlessTrain** [comment]
The quarry only has one level. Other than those two, all buildings have 5 levels
