### ISSUE TITLE
[BUG] Crusher and Sifter block don't have proper translation key assigned

### ISSUE THREAD

**Issue by Kardane** [ldtteam/minecolonies#8816]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.0.1137-ALPHA

### Structurize Version

1.0.468-ALPHA

### Current Behavior

Following  translation key is not used currently :
"block.minecolonies.blockhutsifter"
"block.minecolonies.blockhutsifter.name"
"block.minecolonies.blockhutcrusher"
"block.minecolonies.blockhutcrusher.name"

Instead, these translation key is being used right now:
"com.minecolonies.job.sifter"
"com.minecolonies.job.crusher"

### Expected Behavior

Crusher and Sifter block uses right translation key

### Reproduction Steps

Install latest minecolonies's mod
change language to korean (한국어), or other languages.
look name of crusher or sifter hut block.

### Logs

nope

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Those two language keys:
"com.minecolonies.job.sifter"
"com.minecolonies.job.crusher"

Should also be available on crowdin, so the only thing that is missing is the translators there, translating those too


translate.minecolonies.com if you want to help out with this.

**Comment by Kardane** [comment]
well.. 
![image](https://user-images.githubusercontent.com/64183602/207053763-5d7a92da-5f85-4e32-a653-77e4f3f4bf56.png)
It doesn't have any of these...

**Comment by MotionlessTrain** [comment]
The translation keys of all of them exist within minecolonies (about twice the size of that list there).
Either that is a very old list, or you need to add those manually
