### ISSUE TITLE
[BUG] Sick villagers gather at a replaced hospital building block before the hospital is rebuilt

### ISSUE THREAD

**Issue by Preladon** [ldtteam/minecolonies#8822]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.19.2-1.0.1129-ALPHA

### Structurize Version

1.19.2-1.0.460-ALPHA

### Related Mods and their Versions

No mod changes to default pack downloaded from CurseForge via ATLauncher

### Current Behavior

Built a hospital in my colony, then disassembled it to move it. When placing the block down and organising a rebuild, sick guards immediately gathered at the block, despite the hospital not being (re)built at this stage

### Expected Behavior

I didn't expect the site to count as a hospital until the build was complete

### Reproduction Steps

1. Build a hospital, recruit a doctor, have it operational
2. Deconstruct the building, retain the building block
3. Replace the building block
4. Watch citizens (maybe just guards?) gather at the building block waiting to be healed. Interaction text shows "Waiting for a cure" or similar.

### Logs

n/a

### Anything else?

I don't know if it matters, but I removed the two 'higher impact' sicknesses from the config file prior to this bug occurring, so any colonists are only suffering influenza (potato/carrot cure).

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Preladon** [comment]
<img width="1207" alt="image" src="https://user-images.githubusercontent.com/10695651/208237199-b048715e-8313-4e64-be72-4f4ca2c7cca2.png">

**Comment by Raycoms** [comment]
Seems fine to me tbh. Anyway they wouldn't work, they come there to be cured.
