### ISSUE TITLE
[BUG] migration to 1147-ALPHA breaks decoration controllers

### ISSUE THREAD

**Issue by ZRunner** [ldtteam/minecolonies#8826]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.0.1147-ALPHA

### Structurize Version

1.2.21-ALPHA

### Related Mods and their Versions

1. Forge 41.1.57
2. BlockUI 0.0.64-ALPHA

### Current Behavior

Migrating my world from Minecolonies `1.0.1143-ALPHA` (Structurize `1.0.471-BETA`) to the latest Minecolonies/Structurize versions broke the already-placed decoration controllers, preventing me from upgrading or repairing them. Their names got also replaced by ".blueprint", which makes me think they somehow forgot who they were.

Newly-placed decorations (without updating the schematics pack) does not have this issue.

PS: I got this bug with the "underwater" extension pack and haven't tested with the builtin packs.

### Expected Behavior

Migrating from a new version should not break previously placed decorations and still allows player to repair or upgrade them.

### Reproduction Steps

1. With Minecolonies 1.0.1143 and Structurize 1.0.471, create a new world
2. Place a town hall and some decoration (both using the "constructed" and "schematic paste" buttons lead to the same issue)
3. Close the game, update your mods to Minecolonies 1.0.1147 and Structurize 1.0.472, reopen the game
4. Open your world and click on a decoration controller

### Logs

https://pastebin.com/48gqPbNX

### Anything else?

What I see after updating my mods:
![2022-12-18_17 43 30](https://user-images.githubusercontent.com/30912430/208323201-8f605bd9-40ca-4656-99aa-9797dfdc84c0.png)

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
It looks like all decorations from all styles are broken. This got reproduced with Urban Birch

**Comment by Raycoms** [comment]
I'll look at this when I arrive at home, I got an idea what the problem is and how we can solve it
