### ISSUE TITLE
[BUG] Upgrade Enchanters Tower (Steampunk) fails, "couldn't find structure" error in log

### ISSUE THREAD

**Issue by aelfwyne** [ldtteam/minecolonies#8828]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.19.2-1.0.1148-ALPHA

### Structurize Version

structurize-1.19.2-1.0.472-BETA

### Related Mods and their Versions

Forge 43.2.0
Blockui 1.19-0.0.64-ALPHA
1.19-1.0.76-ALPHA-universal

### Current Behavior

Enchanters Tower (Steampunk) is currently at level 1. When I click to upgrade to level 2, it shows ingredients required as normal and no issue. It queues the upgrade. Eventually a builder accepts the job. At this time, the build request simply disappears from the queue and nothing is built for the upgrade. It's as if I never requested it. 

I checked the logfile and it gives the following error: 
[17:02:15] [Server thread/WARN] [minecolonies/]: Couldn't find structure with name: mystic\enchanter2.blueprint in: Steampunk. Aborting loading procedure
[17:02:15] [Server thread/ERROR] [minecolonies/]: Worker (1:11) ERROR - Starting and missing work order(0)

### Expected Behavior

Expected behavior is to upgrade the building.

### Reproduction Steps

Build level 1 Steampunk enchanter tower.
Upgrade 2 level 2.
It fails silently when the builder accepts the job, and issues the "couldn't find" error in the logs.

### Logs

https://pastebin.com/Sr5HhEE3

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
#5006
