### ISSUE TITLE
[BUG] courier reports impossible problem

### ISSUE THREAD

**Issue by adam110902** [ldtteam/minecolonies#8832]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.0.1142-ALPHA

### Structurize Version

1.0.424-ALPHA

### Related Mods and their Versions

the "minecolonies exploration edition" pack

### Current Behavior

couriers work as normal but keep reporting "i can't deliver because reed a. ardall has afull chest"
reed is dead

### Expected Behavior

couriers work as normal and report existing issues

### Reproduction Steps

i am not sure, 
reed was a crusher, at first the issue semed normal but it continued after he was first fired than killed

### Logs

https://gist.github.com/adam110902/ab565dbf1f6f6b9f533b616f3bc3a129

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Does the old Hut of the crusher still have a full inv?

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by adam110902** [comment]
> Does the old Hut of the crusher still have a full inv? Sent from Proton Mail mobile

no ,it works properly
