### ISSUE TITLE
[BUG] Builder AI break on completion of player house Deco

### ISSUE THREAD

**Issue by taiyoko** [ldtteam/minecolonies#8833]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.19.2-1.0.1148-ALPHA

### Structurize Version

1.19.2-1.0.472-BETA

### Related Mods and their Versions

Forge Version: 43.1.55
Domum Ornamentum Version: 1.19-1.0.76-ALPHA

Modpack: All The Mods 8 pack version: 1.0.6b (with manual updating of Minecolonies and related mods due to previous issues from outdated versions)

### Current Behavior

Builder reported the decoration building "asian_a" (the pagoda-style player house) as being completed multiple times, then when I went to see why he wasn't starting his next queue item, he gave me the "AI is broken, please submit logs" message.

### Expected Behavior

After announcing the building completion, he continues to his next build in the queue.

### Reproduction Steps

1. Begin build of player house
2. Add additional buildings to queue
3. Check with builder when the house is complete.

### Logs

https://mclo.gs/6mUxs5o

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
Did you update minecolonies after the builder started building the player house?

**Comment by taiyoko** [comment]
No, I updated it beforehand, since he seemed possibly be having troubles deconstructing my level 1 town hall so I could reposition it and when I'd asked on the discord, got told to update.

**Comment by Pewmaymen** [comment]
Seeing the same issue on the latest build (1165).  See the GIST at https://gist.github.com/Pewmaymen/2d7763199ed1ef3f59a6bfbd5e0560a0 for the stack trace.  It is throwing a null pointer exception in the state machine.  For me it was the PAgoda Fountain and when I canceled the build in the town hall, the builder moved on to other builds but the decoration control now doesn't have any buttons to interact including upgrade or repair.

**Comment by Dryelo** [comment]
I have the same issue with the Caledonia arches (both double and single).
I also play the ATM8 pack but with an older version: 1.19.2-1.0.1135-ALPHA
As I am not the server admin, I can't update the mod(s).
Would it help you if I upload my logs anyway?

**Comment by MotionlessTrain** [comment]
It won't. Caledonia has been reworked, so this is likely not an issue anymore in recent versions

**Comment by Raycoms** [comment]
same issue> https://github.com/ldtteam/minecolonies/issues/8705
