### ISSUE TITLE
[BUG] Can't place buildings. Previews don't show up or even the gren left/right up/down arrows.

### ISSUE THREAD

**Issue by servireettueri** [ldtteam/minecolonies#8836]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.19.2-1.0.1152-BETA

### Structurize Version

1.19.2-1.0.472

### Related Mods and their Versions

Forge version: not sure where to find this, but it up to date.
BlockUI: 1.19-0.0.64-ALPHA
Multipiston: 1.19.2-1.2.21-ALPHA
Domum Ornamentum: 1.19-1.0.76-ALPHA

I'm not using ANY shaders, which is what all search results tell you to disable.

### Current Behavior

![image](https://user-images.githubusercontent.com/76633423/209477489-aacd054f-d315-49c8-b1ff-459fce2b8adc.png)

Can't place it or see anything.

### Expected Behavior

I SHOULD see a preview of the building.

### Reproduction Steps

Try to place any building and click "use build tool" while having the build tool in your inventory.

### Logs

There is no crash

### Anything else?

![image](https://user-images.githubusercontent.com/76633423/209477584-3fcdd1ac-b225-48cf-af98-75847f461c59.png)

All mods currently installed.

**Comment by Raycoms** [comment]
Are you using fabulous?

**Comment by servireettueri** [comment]
> Are you using fabulous?

nope

**Comment by MotionlessTrain** [comment]
Did you click on any of those buttons, to get to the actual schematics?
(E.g the town hall is available under "fundamentals", the 5th button from the left)

**Comment by servireettueri** [comment]
> 



> Did you click on any of those buttons, to get to the actual schematics? (E.g the town hall is available under "fundamentals", the 5th button from the left)

that would do it. Thanks!
