### ISSUE TITLE
[BUG] AI Issue: Send log report to Author

### ISSUE THREAD

**Issue by TheePandaDev** [ldtteam/minecolonies#8837]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

minecolonies-1.18.2-1.0.966-RELEASE.jar

### Structurize Version

structurize-1.18.2-1.0.424-ALPHA.jar

### Logs

https://gist.github.com/TheePandaDev/e46f37aef2376c874a50f95cbe305738

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
Can you reupload or send the proper link to your gist, what you sent is not usable at all

Edit: Fixed the link for you

**Comment by Raycoms** [comment]
Issue with dynamic tree compat, I believe things changed

**Comment by uecasm** [comment]
There was a fix to Dynamic Trees compat for newer DT in 1114-ALPHA+, so probably just needs to update.

**Comment by Raycoms** [comment]
kk, so Ill close this, please update us if still an issue
