### ISSUE TITLE
file.log issue with colonists

### ISSUE THREAD

**Issue by skiderz458** [ldtteam/minecolonies#8838]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

minecolonies-1.19.2-1.0.1129-ALPHA.jar

### Structurize Version

structurize-1.19.2-1.0.460-ALPHA.jar

### Related Mods and their Versions

Naturalist
Starfish_Studios
naturalist-forge-2.1.1-1.19.2.jar

Neat
Vazkii
Neat-1.19-32.jar

Savage Ender Dragon[Forge/Fabric]
someaddon
dragonfight-1.19.2-2.4.jar

Scaling Health
SilentChaos512
ScalingHealth-1.19.2-7.0.0+6.jar

Server Performance - Smooth Chunk Save[Forge/Fabric]
someaddon
smoothchunk-1.19.1-2.0.jar

Shield mechanics
someaddon
shieldmechanics-1.19.2-3.5.jar

Spice of Life: Carrot Edition
lordcazsius
SoL-Carrot-1.19.2-1.14.0.jar

Spoorn Weapon Attributes [Fabric/Forge]
spoorn
spoornweaponattributes-4.0.9-1.19-forge.jar

Storage Racks
H3lay
storageracks-1.19.2-1.1.4.jar

TrashSlot
BlayTheNinth
trashslot-forge-1.19-12.0.0.jar

### Reproduction Steps

apply fixes and email to confirm to allow us to know when the problem has been fixed

### Logs

atest.log](https://github.com/ldtteam/minecolonies/files/10304391/latest.log)

### Anything else?

[debug.log](https://github.com/ldtteam/minecolonies/files/10304396/debug.log)
[debug-1.log.gz](https://github.com/ldtteam/minecolonies/files/10304397/debug-1.log.gz)
[debug-2.log.gz](https://github.com/ldtteam/minecolonies/files/10304398/debug-2.log.gz)
[debug-3.log.gz](https://github.com/ldtteam/minecolonies/files/10304399/debug-3.log.gz)
[latest.log](https://github.com/ldtteam/minecolonies/files/10304400/latest.log)
[2022-11-04-1.log.gz](https://github.com/ldtteam/minecolonies/files/10304401/2022-11-04-1.log.gz)
[2022-11-04-2.log.gz](https://github.com/ldtteam/minecolonies/files/10304402/2022-11-04-2.log.gz)
[2022-11-04-3.log.gz](https://github.com/ldtteam/minecolonies/files/10304403/2022-11-04-3.log.gz)
[2022-11-04-4.log.gz](https://github.com/ldtteam/minecolonies/files/10304404/2022-11-04-4.log.gz)

attached further files to allow you to backdate and potentially fix early recurring visible problems

**Comment by Talyda** [comment]
What's the actual problem?  I can't see minecolonies mentioned at all in your latest.log.
And have you tried the latest version to see if it is already fixed?

**Comment by Raycoms** [comment]
you are using a 1.18 structurize in 1.19
