### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by Eefeec** [ldtteam/minecolonies#8845]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.0.1127

### Structurize Version

1.0.1127

### Related Mods and their Versions

Force 43.1.65
Domum 1.0.58

### Current Behavior

![Снимок экрана (4)](https://user-images.githubusercontent.com/121577736/209862643-001207f8-4dec-4ff0-82e4-6d34f86e688b.png)

### Expected Behavior

Продолжение процесса

### Reproduction Steps

Запросил постройку парка у строителя,после завершения ИИ выдал ошибку

### Logs

https://gist.github.com/Eefeec/6e5ea70d8f531ce05f68dbf73dc47f59

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Eefeec** [comment]
Как решить проблему?

**Comment by Nightenom** [comment]
Hi, i understand your language but i'm not able to type in. just leave it here, someone else will look into it.

(note for team: it's just ai log report)

**Comment by Eefeec** [comment]
Спасибо. Жду ответ.

**Comment by Raycoms** [comment]
same as https://github.com/ldtteam/minecolonies/issues/8833
