### ISSUE TITLE
[BUG] 1.19.2 Builder AI Error latest.log

### ISSUE THREAD

**Issue by McKitten** [ldtteam/minecolonies#8846]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.192.2-1.0.1149-Alpha

### Structurize Version

1.19.2-1.0.472-Beta

### Related Mods and their Versions

1. Forge 43.1.55
2. blockui-1.19-0.0.64-ALPHA
3. domum_ornamentum-1.19-1.0.76-ALPHA-universal

### Reproduction Steps

1. Went to nether, came home, started having memory issues so i logged off and slept for a little,
2. Reloaded client, logged in and noticed no start message from 1 of the builders, hunted him down and found the AI error report request.
3. Seems the problems started last session but were not noticed until more (tho barely) awake.

### Logs

https://gist.github.com/McKitten/0bb765c06ef0c1a7b5703e5dabb067a7

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by McKitten** [comment]
After rebooting the server and reconnecting the issue was not present until I dropped the connection and joined again.
Then the same error showed up in console output. Have updated to the BETA to test if it is still present, and it is,

**Comment by Raycoms** [comment]
Can you run the request system reset command? It seems like the request log got corrupted somehow.

**Comment by McKitten** [comment]
If it happens again I will, Cancelling the job didn't work but the fire/rehire did so it is back working again.
Yet to pick up that or any house job again tho so might be a matter of time.
