### ISSUE TITLE
[BUG] Text balloons hovering over citizens render behind the cloud layer

### ISSUE THREAD

**Issue by Thodor12** [ldtteam/minecolonies#8849]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.19.2-1.0.1152

### Structurize Version

1.19.2-1.0.472

### Related Mods and their Versions

1. Forge: 43.2.0
2. BlockUI: 1.19-0.0.64
3. Domum Ormamentum: 1.19-1.0.76
4. Multi-Piston: 1.19.2-1.2.21

### Current Behavior

On the image below you can see that the text balloon hovering above the citizen is rendered partially below the cloud layer.
GUI like this should be rendered at the top-most layer, similar to the name of the citizen.

![2022-12-29 11_46_15-Greenshot](https://user-images.githubusercontent.com/14359461/209940918-85527f7a-7b9b-4a97-ad88-489b625cef0f.png)

### Expected Behavior

The text baloon should render above the cloud layers.

### Reproduction Steps

1. Get any citizen using a text baloon/cogwheel above their heads
2. Look at the sky where there are clouds in between

### Logs

N/A

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Nightenom** [comment]
Can some with shader mods test its working properly with them? Thanks
[latest 1.19.3 jar from PR build](https://buildsystem.ldtteam.com/repository/download/LetSDevTogether_Minecolonies_PullRequests_2_BuildAndTest/126227:id/build/libs/minecolonies-1.19.3-1.0.2530-PR.jar)
@Thodor12
