### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by AlexFawl** [ldtteam/minecolonies#8853]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

minecolonies-1.19.2-1.0.1152-BETA

### Structurize Version

structurize-1.19.2-1.0.472-BETA

### Related Mods and their Versions

1.19.2-forge-43.2.0

domum_ornamentum-1.19-1.0.76-ALPHA-universal

multipiston-1.19.2-1.2.21-ALPHA

blockui-1.19-0.0.64-ALPHA

### Logs

https://pastebin.com/LnQCkcbE

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
Downgrade forge to 43.1.  Specifically 43.1.57, if you're planning to use Oculus as well.
