### ISSUE TITLE
[BUG] <title>maybe about optifine?

### ISSUE THREAD

**Issue by 2974226620** [ldtteam/minecolonies#8854]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

minecolonies-1.19.2-1.0.1152-BETA

### Structurize Version

 structurize-1.19.2-1.0.472-BETA

### Related Mods and their Versions

forge v:43.2.2
optifine h9
[crash-2022-12-30_20.31.13-client.txt](https://github.com/ldtteam/minecolonies/files/10324700/crash-2022-12-30_20.31.13-client.txt)

### Current Behavior

when use jei ,in minecolonies page,that crash,I tried nei,same  crash in page.
but i replace optifine l1 _pre 3 or pre 4, Seem to become normal ,but he made me give up some shaders,And some [Domum Ornamentum],[minecolonies] items are transparent on the JEI page.

### Expected Behavior

it cant use in new jei and h9 optifine,Maybe you can look for details in the three logs

### Reproduction Steps

use 1.19.2 s jei,optifine h9
[debug.log](https://github.com/ldtteam/minecolonies/files/10324761/debug.log)
[latest.log](https://github.com/ldtteam/minecolonies/files/10324763/latest.log)

### Logs

Useless for more details than logs

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
>Remove optifine, install rubidium and oculus, fixed

**Comment by uecasm** [comment]
You also need to ensure you're running Forge 43.1.57 or older.

**Comment by 2974226620** [comment]
> > Remove optifine, install rubidium and oculus, fixed

thanks,i use the new optifine _pre,that not crash ,Although this has some effect on my shaders

**Comment by 2974226620** [comment]
> Reference in new issu

Thank you, I chose to ditch my shaders, making all mods run smoothly

**Comment by Raycoms** [comment]
Sent from Proton Mail mobile

-------- Original Message --------
