### ISSUE TITLE
[BUG] 1.19.2 Not compatible with Numismatic Overhaul: Reforged

### ISSUE THREAD

**Issue by agentwolf88** [ldtteam/minecolonies#8860]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

minecolonies-1.19.2-1.0.1163-BETA

### Structurize Version

structurize-1.19.2-1.0.472-BETA

### Related Mods and their Versions

Forge - 43.1.57
BlockUI - blockui-1.19-0.0.64-ALPHA
Domum Ornamentum - domum_ornamentum-1.19-1.0.76-ALPHA-universal
Numismatic Overhaul: Reforged - numismaticoverhaul-1.19.2-1.0.2

### Current Behavior

After i place a Builders Hut i cant open the GUI of this.

### Expected Behavior

GUI of Builders Hut does not work

### Reproduction Steps

Install Forge 43.1.57, install BlockUI, install domom ornamentum, install numismatic Overhaul reforge, install minecolonies.
Build a townhall, create a new colonie, build a builders hut, rightclick on this. Its not work.

### Logs

https://pastebin.com/vbbQXQnv
https://pastebin.com/tmZRUkkm

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Nothing in logs

**Comment by agentwolf88** [comment]
When i right click on a builders hut, this is in log.

[15:54:28] [Render thread/ERROR] [minecolonies/]: java.lang.ClassCastException: class net.minecraft.world.item.AirItem cannot be cast to class net.minecraft.world.item.BlockItem (net.minecraft.world.item.AirItem and net.minecraft.world.item.BlockItem are in module minecraft@1.19.2 of loader 'TRANSFORMER' @7fb66650)

**Comment by Raycoms** [comment]
Please give me the full log of this occuring

**Comment by agentwolf88** [comment]
Which files you need?

[latest.log](https://github.com/ldtteam/minecolonies/files/10338424/latest.log)
[debug.log](https://github.com/ldtteam/minecolonies/files/10338425/debug.log)

**Comment by Raycoms** [comment]
the file that has this full error

**Comment by agentwolf88** [comment]
The 2 files i have posted are the full logs i think. From the beginning to shut down the game.

**Comment by agentwolf88** [comment]
Is there a chance to fix it?

**Comment by Raycoms** [comment]
Please report it to the mod in question and link this here

**Comment by agentwolf88** [comment]
I do this, but he cant fix this in his mod.

**Comment by uecasm** [comment]
Yes, he totally can.  I had a quick look at this and it's definitely the fault of one or more of their mixins.  Specifically, when we create an `ItemStack(DIRT, 1)` and pass it from server to client, it arrives as an `ItemStack(DIRT, 0)` because they're messing with the count field in some inconsistent way.  This is likely breaking quite a lot of other mods as well.

**Comment by Raycoms** [comment]
Oh god, then I'll even close it. Please link this issue to them in their github and tell them to make sure their code doesn't kill other mods.
