### ISSUE TITLE
[BUG] <Nether creates Crash>

### ISSUE THREAD

**Issue by Bot62323** [ldtteam/minecolonies#8864]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

43.1.47

### Structurize Version

1.19.2-1.0.472-BETA

### Current Behavior

When i Start the World it crashed immediatly. 

### Expected Behavior

Join thw World and play 

### Reproduction Steps

I was in The Nether in the Crystal Biome. Out of Nowhere it creashed and is not playable anymore :(.

### Logs

05.01.2023

### Anything else?

Got a Link from the Crash: 
https://bytebin.lucko.me/CooinKwV70

**Comment by MotionlessTrain** [comment]
This is not a crash from minecolonies, but from magistuarmory.
You may need to ask support there
