### ISSUE TITLE
[BUG] Forester going out of Restricted area.

### ISSUE THREAD

**Issue by vvezina** [ldtteam/minecolonies#8869]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.0.1149-ALPHA

### Structurize Version

1.0.1149-ALPHA

### Related Mods and their Versions

Minecolonies ColonyVenture 1.16 (official 1.19 modpack)

### Current Behavior

There is an issue with the foresters "restricted zone". If there is no tree to cut in the restricted area he will go outside that zone.

### Expected Behavior

The  foresters should never leave the "restricted zone". He should wait for the trees to grow back.

### Reproduction Steps

1- Set restricted area.
2- Wait for the trees to be depleted.
3- Watch him ruins your beautiful decorative trees :P.

### Logs

No Logs.

### Anything else?

Suggestion: It could be an actual feature is people do not want to have downtime on their production... You could add an option to activate it. " If there is no trees in the restricted ares - Goes outside the restricted zone"

Thanks! Love the mod!

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Shadizar** [comment]
can confirm this occurs also on 1165 alpha.
Also, if the forester is set to zone mode and no zone is set I would expect them to not cut trees (and they do still cut trees).
(this is a common use case for  me where I want to put woodcutting on hold or where a given forester is meant to only do log stripping)

**Comment by Shadizar** [comment]
From my discord comments also below
1165 alpha....
I set the forester to zoning mode. Set his zone to 1x2 block area with ni wood or leaves (I only want him for log stripping). The guy can't stop wandering around cutting down trees...even after fire and rehire
I wish there was a control in their ui like plantation or apiary 
Cut trees +strip, or strip only 🙂
I also wonder if ther is any possibility for sawmill to strip....in many playthroughs forester takes forever to get to the strip orders, leaving builders cooling their heels waiting

**Comment by MotionlessTrain** [comment]
> Also, if the forester is set to zone mode and no zone is set I would expect them to not cut trees (and they do still cut trees).

Iirc in that case, the setting doesn't actually get saved, as there is no point having zoning mode in without having a zone

**Comment by Shadizar** [comment]
There is a point actually, as stated: I want a way for them to never chop trees, and only strip logs for me

**Comment by Raycoms** [comment]
Weird, for me they walk to the zone and just stand there and do nothing.

**Comment by uecasm** [comment]
They might still hunt down and chop one last tree after you set the zone area + setting, but should then stop after that.  Firing and rehiring should reset that too (such that they wouldn't), but I'm not entirely sure.

**Comment by Raycoms** [comment]
Yes, that is expected. They also started stripping a few seconds later for me then.

**Comment by Talyda** [comment]
The original poster had it happen more than once (I think they said it happened twice in 20 hours or so - but then it happened more times, and they were able to work out it was happening each time when there was no trees in the zone)

**Comment by Raycoms** [comment]
Are they constantly running around cutting trees or does it happen here and there randomly?

**Comment by vvezina** [comment]
He usually chop trees in the restricted area for a long time (hours) before he goes out of the zone.

Also, when hes out of the restricted area, he's always going to the same other area/trees (that's how i spot him). I dont know if that can help but he usually have time to replant 2-3 trees in that spot (outside restricted zone) before i notice and those are the trees that he goes to...

Also like Talyda said, it happened to me a lot of time now. Around 5 times in the past week.

Thanks!

**Comment by Shadizar** [comment]
Mine wandered near their hut chopping trees (including outside his 1x2 box I zoned...the ui did say 2 blocks )
Fired rehired and he went right back to chopping

**Comment by Raycoms** [comment]
fix pushed
