### ISSUE TITLE
[BUG] Mirrored Building Upgraded in Incorrect Orientation

### ISSUE THREAD

**Issue by Darmandir** [ldtteam/minecolonies#8872]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.18.2-1.0.1159

### Structurize Version

1.18.2-1.0.424

### Related Mods and their Versions

1. Forge: 40.1.92
2. BlockUI: 1.18.2-0.0.62
3. Domum Ornamentum: 1.18.2-1.0.55

### Current Behavior

Builder upgrades flipped building in an incorrect orientation

### Expected Behavior

Builder retains correct orientation of mirrored building when upgraded

### Reproduction Steps

1. Build building
2. Continue playing as normal
3. Upgrade building
4. Building is built incorrectly

### Logs

https://gist.github.com/Darmandir/a2e4dd94de0ecfa9989a640ff1b23bbd

### Anything else?

A while back, I built a builder's hut in a flipped orientation. Today, I began work on upgrading the builder's hut, until I realized the builder had began to intersect it with a nearby house. I have added/removed mods in this time, but nothing that interacted with structurize or anything.

As you can see, the construction tape is all correct, but the actual structure preview and builder's apparent orientation is incorrect.
![2023-01-06_15 31 50](https://user-images.githubusercontent.com/45914359/211106367-ed8a5a86-34aa-4f57-af1f-30e3371642c0.png)
![2023-01-06_15 39 54](https://user-images.githubusercontent.com/45914359/211106375-c8a3709e-c037-43a2-95ab-1400612a4f53.png)

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Is there a way to reproduce this?

**Comment by Talyda** [comment]
Maybe the same thing as the thing I reported a while ago?
https://github.com/ldtteam/minecolonies/issues/8719
I wasn't able to replicate the builder building it wrong each time was my problem. But the facing east/west vs north/south was replicable

**Comment by Raycoms** [comment]
Yes, might be #8719

I'll close it in favor of this for now
