### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by Hedkracka** [ldtteam/minecolonies#8882]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.0.1149.Alpha

### Structurize Version

1.0472.beta

### Current Behavior

This is related to the chicken handler,
I have noticed that when leaving the pen they still have seeds in their hands, causing the chickens to follow them out of the pen.

### Expected Behavior

i would suggest that the handler should have an empty hand when moving thru the fence system (airlock)

### Reproduction Steps

i have a tier 1 chicken pen, watch when the handler is leaving the pen after a feeding.

### Logs

no crash no log

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
Them having seeds in their hand doesn't cause chickens to follow them. That is just the case for players

**Comment by Hedkracka** [comment]
no, that is not the case, i have watched from distance the handler leave the pens with seeds in hands and chickens follow them out.

**Comment by krjencik** [comment]
where to put this: it happens chickens and other animals tend to leave their pens, huts. I think its because the citizens are slow in opening/closing fence gates (and doors).

im currently playing minecolonies-1.19.2-1.0.1198-ALPHA

**Comment by Raycoms** [comment]
Above was fixed btw
