### ISSUE TITLE
[BUG] Crash on clicking the little questionmark. Also hi!

### ISSUE THREAD

**Issue by webtomek** [ldtteam/minecolonies#8883]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.19.2-1.0.1183-ALPHA

### Structurize Version

1.19.2-1.0.472-BETA

### Related Mods and their Versions

forge 43.2.3
blockui-1.19-0.0.64-ALPHA
domum_ornamentum-1.19-1.0.59-ALPHA-universal

... also getting the crash in 1.0.1177-BETA.
in 1.0.1183-ALPHA it does crash but doesn't give crash logs, just freezes.

### Reproduction Steps

1. build a farm
2. open the like... the main block thingy
3. press the little red questionmark on the bottom left corner

### Logs

https://pastebin.com/FRsNvz4C

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
on it

**Comment by Raycoms** [comment]
hotfix pushed
