### ISSUE TITLE
[BUG] [1.16.5] Game crashing when using the build tool to place buildings

### ISSUE THREAD

**Issue by TheFlamSonic** [ldtteam/minecolonies#8886]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.16.5-1.0.978-RELEASE

### Structurize Version

1.16.5-1.0.418-ALPHA

### Related Mods and their Versions

Forge version : 1.16.5-36.2.39
Mine Mine No Mi version : 1.16.5 - 0.9.1

### Current Behavior

When using the build tool to place a building, the game crashes right after right clicking with the build tool. If it doesn't crash now, it will crash when selecting a level 5 wooden house.

### Expected Behavior

Expected the game not to crash and placing buildings normally.

### Reproduction Steps

1.Install the latest Minecolonies 1.16.5 version with structurize
2.Install the Mine Mine No Mi mod
3.Use the build tool with a house
4.Select a level 5 wooden house
5.The game crashes

### Logs

https://pastebin.com/dnQd7edm

### Anything else?

I can't place certains buildings because the game crashes instantly when selecting them with the build tool.

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
It's interesting that you state MC version of 1.18, yet your jar version is 1.16.5.
If you are playing on 1.16.5 then we do not provide any help, else correct your mod version and re-open the issue.

**Comment by TheFlamSonic** [comment]
I couldn't choose 1.16.5 when creating the issue, there was only 1.18 and 1.19. And yes, I'm playing on 1.16.5

**Comment by Thodor12** [comment]
That selection is there for a reason, we do not support 1.16.5 anymore, so if you're not playing either of those version, you aren't allowed to make issues on those anymore.

**Comment by TheFlamSonic** [comment]
Oh ok, thank you for the quick replies.
