### ISSUE TITLE
[BUG] <NPC convulsion>

### ISSUE THREAD

**Issue by Qiushixunzhu** [ldtteam/minecolonies#8896]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

minecolonies-1.19.2-1.0.1185-ALPHA

### Structurize Version

structurize-1.19.2-1.0.476-ALPHA

### Current Behavior

https://user-images.githubusercontent.com/122713277/212523616-7fbc9fe8-4bb0-4a58-8ba6-306e8d9efa95.mp4

### Expected Behavior

NPC convulsion

### Reproduction Steps

It happened suddenly
[latest.log](https://github.com/ldtteam/minecolonies/files/10419489/latest.log)

### Logs

https://gist.github.com/Qiushixunzhu/6893cbf76e7d0527ae1271d2e434d0d0

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Does this happen often or regularly? Does this happen without optifine as well? Any other mods that could be influencing this too?

**Comment by skadlig** [comment]
It has happened to me as well using this modpack:
https://www.curseforge.com/minecraft/modpacks/ccm-1-19-2
That modpack doesn't use optifine.

**Comment by budgej** [comment]
"Convulsing" NPC's cannot be interacted with or recalled.  However, unloading the colony (by player log-off, for example) sometimes resolves it.

**Comment by budgej** [comment]
After more than a week of play, I have yet to see this repeated in 1248.

**Comment by Raycoms** [comment]
Its most likely related to minecraft losing track of entities sometimes randomly and duplicating them which causes these glitches. If you restart every 12h or so it basically never occurs. Ill close this for now then
