### ISSUE TITLE
Hut Survival Recipes Not Functional

### ISSUE THREAD

**Issue by geldonyetich** [ldtteam/minecolonies#890]
### Minecolonies version

minecolonies-universal-1.10.2-0.6.571 through 0.6.588 as shown in Twitch/Curse client.

### Expected behavior

* Surround a door with wood planks, the builder hut becomes buildable.
* Click on any kind of hut in the Not Enough Items interface, a recipe should come up.

### Actual behaviour

Crafting with or without NEI help does not seem to produce a builder hut.
None of the recipes for the other huts will show up when I click on them with NEI.

### Steps to reproduce the problem

1. Update to minecolonies-universal-1.10.2-0.6.571or later.
2. Try to craft a hut in survival mode, like notch intended.
3. ???
4. Profit!

**Comment by Raycoms** [comment]
Hey there, please roll back to Minecolonies v0.7.4.2
<https://minecraft.curseforge.com/projects/minecolonies/files/2407417> for
now. We're currently experimenting with a new build system which
automatically uploads to curse.
Will remove the buggy versions.

2017-04-28 18:02 GMT-03:00 geldonyetich <notifications@github.com>:

**Comment by geldonyetich** [comment]
Ah, I see!  Will do.

**Comment by geldonyetich** [comment]
Looks like Minecolonies v0.7.5 released version sent to the Curse launcher also has this issue. 

Reverting back to 0.7.4.2 for now.  But excited for the cool new food-requiring version!

**Comment by Raycoms** [comment]
The v0.7.5 doesn't allow you to craft huts?

I will take a look at this a bit later.

2017-04-29 19:35 GMT-03:00 geldonyetich <notifications@github.com>:

**Comment by Raycoms** [comment]
Found the bug, fixed it. Will upload the fix today or tomorrow

2017-04-29 19:36 GMT-03:00 Ray Neiheiser <ray.neiheiser@gmail.com>:

**Comment by geldonyetich** [comment]
Confirmed working in 0.7.5.1.  Thanks much for the quick fix!
