### ISSUE TITLE
[BUG] <title> Builder starts demoing building before finishing

### ISSUE THREAD

**Issue by detsuo04** [ldtteam/minecolonies#8902]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.0.1177-BETA

### Structurize Version

1.0.1177-BETA

### Related Mods and their Versions

atm 8 modpack

### Current Behavior

Builder will build a structure to 100% then start breaking all blocks made with the architect cutter.  The builder will then place them again and complete the building.

If the game crashes some times all the core blocks will become detached from their buildings.  to fix this the block must be mined and replaced with the build tool.  then the builder will break only blocks made with the architect cutter before replacing them and completing the structure.

### Expected Behavior

Builder should finish the building without deconstructing blocks he already placed.

### Reproduction Steps

have a builder build any structure that uses blocks made with the architect cutter.

### Logs

https://gist.github.com/detsuo04/42b479d495e68535109d0024862782e5

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
That's normal, especially if you have crashed mid build. You may find they replace fences and doors too - anything with a  blockstate that can change between schematic and being placed

**Comment by Raycoms** [comment]
Is similar to the other DO issue, improvement incoming, slight takedown of non compatible blockstates will still happen though
