### ISSUE TITLE
[BUG] <Game crash when click on build option>

### ISSUE THREAD

**Issue by SIKAdeerX** [ldtteam/minecolonies#8903]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.19.2-1.0.1198-ALPHA

### Structurize Version

1.19.2-1.0.441-ALPHA

### Related Mods and their Versions

1. Forge version: 42.0.9
2. BlockUI version: 1.19-0.0.64-ALPHA
3. Domum_ornamentum version: 1.19-1.0.60-ALPHA-universal

### Current Behavior

Game keep crash when I trying to open the build option for both town hall or builder hut. Problem not solved after I break the hut and replaced it.

### Expected Behavior

Game not crash when clicking on build option.

### Reproduction Steps

1. Place builder hut
2. Click builder option
3. Game crash

### Logs

https://pastebin.com/mknUsDHk

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
You likely will have to upgrade your forge version, try a forge 43 version and see if the issue persists.

**Comment by Talyda** [comment]
Try without optifine - optifine doesn't play nice on 1.19

**Comment by SIKAdeerX** [comment]
Thanks for the help from all of you! Problem solved.
First I try to remove the optifine with 1.19.1 version of minecraft, the issue is still there.
Then I update the minecraft to 1.19.2 and removed optifine, issue is gone.
