### ISSUE TITLE
[BUG] Decorations disturb builder

### ISSUE THREAD

**Issue by BakermanLP** [ldtteam/minecolonies#8906]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.0.1193

### Structurize Version

1.0.472

### Related Mods and their Versions

1. Forge version 43.2.2
2. blockui-1.19-0.0.64-ALPHA.jar
3. domum_ornamentum-1.19-1.0.76-ALPHA-universal.jar

### Reproduction Steps

1. Placement Decoration Well 

### Logs

https://gist.github.com/BakermanLP/d4cf5e8e97b3a620e21be7b6342aae09

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
same as https://github.com/ldtteam/minecolonies/issues/8705
