### ISSUE TITLE
latest.log

### ISSUE THREAD

**Issue by Curio88** [ldtteam/minecolonies#8908]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.0.1163-BETA

### Structurize Version

1.0.471-ALPHA

### Related Mods and their Versions

![изображение_2023-01-21_211918171](https://user-images.githubusercontent.com/123264739/213881327-b51d2dfc-34b9-426a-987f-aed308a58516.png)

### Logs

<script src="https://gist.github.com/Curio88/bf33cbf4a430ac47511b39254738e28d.js"></script>

### Anything else?

Мой ИИ написал мне прям в игре что у него проблема, и он не работает!

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Can you try a request system reset?

**Comment by Curio88** [comment]
Что я должен сделать?

сб, 21 янв. 2023 г., 21:25 Raycoms ***@***.***>:

**Comment by Raycoms** [comment]
Fixed by RS reset. Else same as https://github.com/ldtteam/minecolonies/issues/8740
