### ISSUE TITLE
[BUG] First level warehouse has a glitched double rack when built.

### ISSUE THREAD

**Issue by Sovietsupporter69** [ldtteam/minecolonies#8911]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.19.2-1.0.1135-ALPHA

### Structurize Version

1.19.2-1.0.467-BETA

### Related Mods and their Versions

1. In Direwolf 1.19 modpack version 1.0.4
(ask if you need anything specific as I'm willing to help)

### Current Behavior

3 racks are placed together and form 2 overlapping double racks.
![image](https://user-images.githubusercontent.com/84580170/214909614-0a59f83a-4616-4fca-8445-e39dff02bf8f.png)

### Expected Behavior

A single rack and a double rack.
![image](https://user-images.githubusercontent.com/84580170/214909909-50080416-e77c-4fca-ac72-fab40b2a7528.png)

### Reproduction Steps

1.chose the warehouse 1 though the structiurize menu
2.change the style to shire
3.let the npc build the house and it should be bugged (might be directional so I'm facing south here)

### Logs

https://gist.github.com/Sovietsupporter69/e5c279fb0d91289c988599733b22c921

### Anything else?

Isn't much of a problem for me so its more of just a good thing to fix in the future.

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
fixed
