### ISSUE TITLE
Related mods

### ISSUE THREAD

**Issue by 21Sumter** [ldtteam/minecolonies#8913]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.19.2-1.0.1207-ALPHA

### Structurize Version

1.19.2-1.0.472-BETA

### Related Mods and their Versions

1. 1.19.2 Laster
2. blockui-1.19-0.0.64-ALPHA
3. in the latest versions of the mod requests the installation of DOMUM_ORNAMENTUM on version 1.19, this mod is only on version 1.18 and below

### Current Behavior

-

### Expected Behavior

-

### Reproduction Steps

-

### Logs

-

### Anything else?

-

**Comment by Raycoms** [comment]
Click view all

**Comment by 21Sumter** [comment]
I deeply apologize, I found domum on 1.19, it was not listed on the main page of all versions of the mod, but on the main one was
https://imgur.com/a/7GEPBij
