### ISSUE TITLE
Townhall Blueprint Style not saving

### ISSUE THREAD

**Issue by dhgameryt** [ldtteam/minecolonies#8918]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

minecolonies-1.19.2-1.0.1207-ALPHA.jar

### Structurize Version

structurize-1.19.2-1.0.476-ALPHA.jar

### Related Mods and their Versions

forge 43.2.3

### Current Behavior

I built a town hall with the pagoda style, now I want to change the default style of my colony to medieval oak, but when selecting this style, closing and opening the town hall menu returns it to pagoda

### Expected Behavior

I want to be able to change the default style

### Reproduction Steps

place a town hall with pagoda style and try to change the default style to medieval oak

### Logs

https://gist.github.com/dhgameryt/30d5dd27fa83d7f2fc50991312f40413

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Can you give me additional info?

- Does this always happen?
- Is this on a server or in singleplayer?

**Comment by dhgameryt** [comment]
> 

Yes it always happen, and its in singleplayer

**Comment by Raycoms** [comment]
Do you have any other colonies in the world?

**Comment by dhgameryt** [comment]
> Do you have any other colonies in the world?

i only have 1 colony in that world

**Comment by Raycoms** [comment]
I cant reproduce this at all in any way. Did you try just with minecolonies + deps if it also happens, I fear some mod interference.

**Comment by dhgameryt** [comment]
I think that if it is a problem of my colony/world, I will close this issue
