### ISSUE TITLE
[BUG] "build options" for cavern university lvl2 crashes minecraft

### ISSUE THREAD

**Issue by MrMcMiller** [ldtteam/minecolonies#8927]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.0.1226-BETA

### Structurize Version

1.0.480-ALPHA

### Related Mods and their Versions

Forge: 43.2.4
BlockUI: 0.0.67-ALPHA
DomumOrnamentum: 1.0.76-ALPHA-universal
Multi-piston: 1.2.25-ALPHA

### Current Behavior

Using cavern style, university lvl2 (non-megahall variant) crashes minecraft when clicking on "build options"

### Expected Behavior

no crash

### Reproduction Steps

1. Have a colony with university lvl2 (cavern style, non-megahall variant)
2. Click on "build options"
3. Minecraft crashes

### Logs

https://gist.github.com/MrMcMiller/3ef83cc36d33929f0337276d73586bcf

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by budgej** [comment]
Can confirm same issue with Flower shop, same mod versions.

**Comment by Raycoms** [comment]
hotfix pushed

**Comment by MrPlant1** [comment]
Bug also present with underwater style town hall in version minecolonies-1.19.2-1.0.1234-ALPHA. Happens when placing the townhall block down with the build tool. Besides this, if the block happens to be placed, it doesn't create a colony. My latest log when encountering this bug: 

https://gist.github.com/MrPlant1/ca56e45137480611c67ffca7be52d322

**Comment by budgej** [comment]
Bug remains in 1227.
https://github.com/ldtteam/minecolonies/issues/8938

**Comment by Raycoms** [comment]
Tried with the same building in 1224 and couldnt reproduce it. Can you try with the newest, make sure you dont have multiple jars in the folder AND send us the new log when it crashes?

**Comment by anonymous563** [comment]
https://pastebin.com/16W5znzd
Minecraft crashes for me when I try to creative-paste a level 5 alt fortress university over a level 3 alt fortress university.
minecolonies-1.19.2-1.0.1247-BETA
structurize-1.19.2-1.0.480-ALPHA

**Comment by budgej** [comment]
After testing on 1248 for more than a week, I have not seen this crash.
