### ISSUE TITLE
[BUG] Can't order the build of the nether mine

### ISSUE THREAD

**Issue by ShadowoftheRedFox** [ldtteam/minecolonies#8928]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.19.2-1.0.1226-BETA

### Structurize Version

1.19.2-1.0.480-ALPHA

### Current Behavior

Once you placed the nether mine block, click build options, and you crash there.

### Expected Behavior

Once you click the build options, the normal build options menu should open with the correct style and everything. 

### Reproduction Steps

1. Place the nether mine block.
2. Open the block menu.
3. Click on build options.

### Logs

https://bytebin.lucko.me/sKYTX0BaSc

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
hotfix pushed
