### ISSUE TITLE
[BUG] <Server will spam an error for about 20 minutes before shutting down>

### ISSUE THREAD

**Issue by yokonzo** [ldtteam/minecolonies#8939]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

 1.18.2-1.0.1228

### Structurize Version

1.18.2-1.0.424

### Related Mods and their Versions

1. Forge Version: 40.2.0
2. BlockUi Version: 1.18.2-0.0.55
3. Domum Ornamentum Version: 1.18.2-1.0.77

### Current Behavior

MineColonies will run normally as a server, during this time i am creative mode building a town and using worldedit, after about 20 minutes of runtime the server will kick out all players without error, Upon Looking at log, it has been flooded with about 820kb of text, repeating an error that seems to be referencing the sleep handler 

### Expected Behavior

Normal Gameplay without crash

### Reproduction Steps

Run Server, wait for a bit and error starts spamming

### Logs

https://gist.github.com/yokonzo/421c0510b5a4440da129bcb79c8a3217

### Anything else?

I asked about this on the discord and they suggested making a bug report, please let me know if you need any more info from me

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
This log doesn't have any crash or flooding of text

**Comment by Talyda** [comment]
To help them out - this was the log (seems they put wrong one in the report):
https://gist.github.com/yokonzo/d216ef4ddcc91773f34008a77240d02d

**Comment by yokonzo** [comment]
> 

My bad, yes this is the correct log

**Comment by Raycoms** [comment]
You do have a broken bed somewhere. Like, half of the bed is correct, the other half is broken.

**Comment by yokonzo** [comment]
Interesting, I'll take a look around and see if i can fix it. interestingly, i've recently gone around in creative remaking the whole city into the "Jungle" varient, using the "build as if made by builders" button, along with worldedit. Its possible this is what caused the beds to be messed up in the first place but thats just speculation

**Comment by Raycoms** [comment]
should be fixed
