### ISSUE TITLE
[BUG] <No Stlye Showing up>

### ISSUE THREAD

**Issue by thgknightyyy** [ldtteam/minecolonies#8941]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.19.2-1.0.1234-ALPHA

### Structurize Version

structurize-1.19.2-1.0.480-ALPHA

### Related Mods and their Versions

Added minecolonies to TNP Limitless 6 mod pack.

### Current Behavior

I used a supply to make a steampunk style. After reading the book on taking 15+ hours per level i decided to not go that route.

i deleted the building but now when ever i press the style button everything is blank.

I cant place anything i cant see any styles i cant do anything with minecolonies anymore.

### Expected Behavior

I expected the screen to show the different styles so i can pick what i want and then build?

### Reproduction Steps

1) build supply steampunk style
2) saw 15+ hour builds deleted supply
3) tried to build new supply no styles show and wont show anything
4) tried building a townhall and everything else nothing

### Logs

https://pastebin.com/b3BEvthy

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
So, you dropped of the steampunk style in the bluepritns folder, saw the requirements and removed the style from the blueprints folder again?

**Comment by Raycoms** [comment]
Stale
