### ISSUE TITLE
[BUG] Technically Industrial, mine colonies, right clicking town hall crashes my game

### ISSUE THREAD

**Issue by Elfyylad** [ldtteam/minecolonies#8950]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.19.2

### Structurize Version

1.19.2-1.0.1226-BETA

### Related Mods and their Versions

All the mods in curse forge technically industrial modpack. When game crashes it tells me no other mods are involved though

### Reproduction Steps

Start mine colonies with the camp, get town hall and build wand out of the starter chest, go to build the town hall through your build wand, once its placed, right click the town hall. This is where my game crashes

### Logs

https://pastebin.com/m8fYEtPi

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
Update minecolonies to at least 1.0.1248. This has been fixed already
