### ISSUE TITLE
Game Crashing upon Pirate ship Leaving.

### ISSUE THREAD

**Issue by NovaProgression** [ldtteam/minecolonies#8953]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

minecolonies-1.19.2-1.0.1200-BETA

### Structurize Version

structurize-1.19.2-1.0.472-BETA

### Related Mods and their Versions

1. Forge Version: 43.2.3

(modpack is All The Mods 8 but i dont think its relevant due to the specific issue in question.)

### Current Behavior

- a pirate invasion started. 
- Pirates were slain and spawner was broken.
- the pirate invasion ended and the ship despawned
-  i tried to exit game and crashed. 
- the world saved so there is no more pirate ship, but the raid is still in progress.
-  when i log back in it tries to end the invasion again but cant remove the pirate ship and the game crashes.
-  i can only load up for about 30 seconds before it crashes again.

Error code:     java.lang.NullPointerException: Cannot invoke "com.ldtteam.structurize.blueprints.v1.Blueprint.getSizeX()" because the return value of "com.ldtteam.structurize.placement.structure.IStructureHandler.getBluePrint()" is null 

### Expected Behavior

- Upon clearing the pirate invasion remove pirate ship as normal
- If  the return value of "com.ldtteam.structurize.placement.structure.IStructureHandler.getBluePrint()" is null end the event and move on because its already gone so who cares.

### Reproduction Steps

1. Minecolonies.
2. begin pirate invasion
3. clear pirate invasion
4. immediately after pirate ship departs save and close
5. crash halfway through
6. reload and continue crashing

### Logs

https://pastebin.com/7BM6dYsi

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
It seems like the crash during leave corrupted the state. Ill add a safeguard to this.

**Comment by Raycoms** [comment]
fixed
