### ISSUE TITLE
[BUG] Plantation 0 available soil positions - Urban Birch

### ISSUE THREAD

**Issue by budgej** [ldtteam/minecolonies#8955]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19.2

### MineColonies Version

1248

### Structurize Version

1.0.480

### Related Mods and their Versions

Forge 1.19.2 43.2.4

### Current Behavior

Planter stands idle with level 1 Urban Birch plantation, spams log twice per second with the following message.
"Planter building returned 0 available soil positions, schematic is plantation, please report this to the developer!"

### Expected Behavior

Planter plants cactus and harvests it.

### Reproduction Steps

Build level 1 plantation and hire a worker, assign cactus.

### Logs

https://pastebin.com/aMWpcwxm

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by budgej** [comment]
Level 2 urban birch plantation works as intended, no log spam, planter plants cactus.

**Comment by Raycoms** [comment]
Please report to #5006
