### ISSUE TITLE
[BUG] Pickaxes Not Working? (1.19.3)

### ISSUE THREAD

**Issue by bdgrim** [ldtteam/minecolonies#8956]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19.3

### MineColonies Version

1.19.3-1.0.1243-alpha

### Structurize Version

1.19.3-1.0.482-alpha

### Related Mods and their Versions

1. forge version: 44.1.0
2. block ui version: 1,19.3-0.0.70-alpha
3. domum_ornamentum version: 1.19.3-1.0.81-alpha

### Current Behavior

sorry github would only let me select between minecraft versions 1.18 and 1.16 - **BUT my issue is 1.19.3**

i created an entirely fresh curseforge profile with ONLY MineColonies installed and its related dependencies, and im getting a weird glitch where every pickaxe is as slow as a wooden one, and even if you mine blocks to completion, nothing drops from them.

### Expected Behavior

i expect.. pickaxes.. to work? :(

### Reproduction Steps

1. create a new curseforge profile
2. install the latest version of minecolonies (curseforge should automatically grab the dependencies)
3. start a new world
4. craft/spawn a pickaxe of any type and try to mine some stone, cobble, etc

### Logs

https://gist.github.com/bdgrim/42b1c1448ce343bad56e9009da2c9588#file-gistfile1-txt

### Anything else?

I asked the bugs-1_19 discord chat for help and Shindria sent me to post this github, so.

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
How come you state MC version of 1.16?

**Comment by bdgrim** [comment]
https://i.gyazo.com/d4b384d2eefd828b95832ccbab655018.mp4
github wouldnt let me select anything else ?

**Comment by Talyda** [comment]
Githubs gone weird, and you can only choose 1.16 and 1.18

> How come you state MC version of 1.16?

**Comment by Thodor12** [comment]
I told Ray to update the issue templates, anyway.

**Comment by Thodor12** [comment]
Revert to Domum Ornamentum 1.19.3-1.0.78.
This is still problematic in the latest Domum version.

**Comment by Raycoms** [comment]
Pushed a fix to DO
