### ISSUE TITLE
Epic Knights: Shields, Armor and Weapons

### ISSUE THREAD

**Issue by LeDiable22** [ldtteam/minecolonies#8957]
https://logpaste.com/4RSwHyc4

**Comment by someaddons** [comment]
bug of the Epic Knights: Shields, Armor and Weapons mod, next time fill the form properly with putting the log into a paste site.

**Comment by LeDiable22** [comment]
Sorry if i didn't full fill correctly the report i am french and i didn't
understand a little part of it

Le lun. 20 févr. 2023 à 13:52, someaddons ***@***.***> a
écrit :

**Comment by Raycoms** [comment]
Report this to: Epic Knights: Shields, Armor and Weapons

**Comment by LeDiable22** [comment]
Thanks.
