### ISSUE TITLE
[BUG] Compatibility bug with ForceCraft/Custom Vanilla Crafting

### ISSUE THREAD

**Issue by Saereth** [ldtteam/minecolonies#8961]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19.2

### MineColonies Version

minecolonies-1.19.2-1.0.1258-ALPHA

### Structurize Version

structurize-1.19.2-1.0.480-ALPHA

### Related Mods and their Versions

Forge 43.2.3
blockui-1.19-0.0.69-ALPHA
forcecraft-1.19.2-3.2.4

### Current Behavior

ForceCraft ads a custom vanilla crafting recipe that takes the force rod+book (which stores xp) and crafts their upgrade cores while consuming some of the XP. This recipe works normally but when minecolonies is added to the pack the recipe functionality breaks. 

This can be produced with an absolutely minimum modlist of only forcecraft and minecolonies.

### Expected Behavior

For the recipe to work

### Reproduction Steps

Create a fresh 1.19.2 instance with forge 43.2.3
Add minecolonies + dependencies
Add forcecraft 
jei-1.19.2-forge-11.6.0.1011

Recipe will be broken with this minimal mod set

### Logs

https://gist.github.com/Saereth/30a0d61ab7315d18f788995cd8cc18f0

### Anything else?

There is an issue up on ForceCraft's github as well here regarding this
https://github.com/Mrbysco/ForceCraft/issues/68

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
I couldn't reproduce this when JEI is left out, could you change your description to state that JEI is not optional for this bug to occur?

**Comment by Saereth** [comment]
> I couldn't reproduce this when JEI is left out, could you change your description to state that JEI is not optional for this bug to occur?

Good catch, ammended and put the version of jei I was using as well

**Comment by uecasm** [comment]
That log has a whole bunch of stuff about "EmendatusEnigmatica" generating a data pack and Minecraft failing to load tags from that pack.

Since that doesn't appear to be a dependency of either mod, either that's the wrong log or you haven't tried it in a clean instance.

**Comment by Raycoms** [comment]
We were able to reproduce it in a clean instance with minecol + deps + the mod in question + jei
