### ISSUE TITLE
Unable to join server with mine colonies. 

### ISSUE THREAD

**Issue by Stronyy** [ldtteam/minecolonies#8963]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.16.5-1.0.978-release

### Structurize Version

1.16.5-1.0.418-Alpha

### Current Behavior

"internal exception io.netty.handler.codec.decoderexception java.io.ioexception: payload may not be larger than 1048576 bytes" 

### Expected Behavior

For it to allow me to join the game and play the modpack with minecolonies. 

### Reproduction Steps

Add minecolonies and structurize mod to Ragnamod VI modpack client and server. Then Attempted to join server. 

### Logs

23.02 04:11:08 [Server] Netty Epoll Server IO #5/INFO [co.li.co.ConfigSyncManager/]: Skipping config sync, No mods have registered a syncable config. 23.02 04:11:08 [Server] User Authenticator #2/INFO UUID of player zChil is 3485e4bd-1b32-4fcc-9ed7-9f258e36e0b1 23.02 04:11:09 [Disconnect] User com.mojang.authlib.GameProfile@569516f7[id=3485e4bd-1b32-4fcc-9ed7-9f258e36e0b1,name=zChil,properties={textures=[com.mojang.authlib.properties.Property@550cd596]},legacy=false] (/72.184.79.144:64870) has disconnected, reason: Disconnected

### Anything else?

 I often add minecolonies to many other modpacks and it works without issues. I tried to add minecolonies to a modpack I'm currently playing. When I added everything, the modpack works and allows me to join singleplayer worlds and play without issues. When I try to join my multiplayer server it doesn't let me join and gives me a "internal exception io.netty.handler.codec.decoderexception java.io.ioexception: payload may not be larger than 1048576 bytes" error message. I have tried scanning the modpack for mods that may conflict with minecolonies as well as looked on forums. The only solution I have found was to run the  /mc colony requestsystem-reset-all command, but I cannot even log in to run the command. When I try to run the command from console it does not recognize the command.

**Comment by Talyda** [comment]
1.16.5 is no longer supported sorry - that's why you can't choose it in the version list

**Comment by Stronyy** [comment]
So 1.16.5 no longer works ?

**Comment by Talyda** [comment]
That's not what I said.  Support is no longer provided for it

**Comment by Stronyy** [comment]
Is there anywhere else that provides support with minecolonies?

**Comment by Talyda** [comment]
Not that I know of!
