### ISSUE TITLE
[BUG] Clicking on barracks Build Options crashes the game

### ISSUE THREAD

**Issue by DruidLox13** [ldtteam/minecolonies#8966]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19.2

### MineColonies Version

1.0.1226-BETA

### Structurize Version

1.0.472-BETA

### Related Mods and their Versions

1. Forge 43.2.4

### Current Behavior

When I click on build options for the barracks, my game crashes, see the screenshot attached.

![Screenshot (53)](https://user-images.githubusercontent.com/126285098/221271487-06d3568d-4275-4e14-8f42-29d9f934c3e9.png)

### Expected Behavior

I expected it to pull up the build options and allow me to assign a builder, etc.

### Reproduction Steps

1. Create a colony that is Medieval Oak
2. Place a barracks block with the build tool
3. Right click on the block to bring up the main menu
4. Click on Build Options

### Logs

https://gist.github.com/DruidLox13/3e5ecd12319ff57ee258b9cdaaa43413

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
Update minecolonies. This has been fixed already
