### ISSUE TITLE
[BUG] Rotating costume style packs crashes an ATM 8 server

### ISSUE THREAD

**Issue by Dyerzombie** [ldtteam/minecolonies#8967]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19.2

### MineColonies Version

1.19.2-1.0.1262-ALPHA

### Structurize Version

1.19.2-1.0.480-ALPHA

### Current Behavior

When I would attempt to place a structure I made with the build tool and then rotate the building the server would crash.

### Expected Behavior

I expected to turn the structure 180 degrees to have the door facing me and for the building to be placed for construction

### Reproduction Steps

1. Download the ATM 8 server zip folder
2. Copy your costume style pack
3. Use the building tool to rotate the structure 180 degrees
4. Click the green check mark

### Logs

https://pastebin.com/Y5x5UWCv

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Let me guess, the name had upper case letters and server/client different os, windows-linux?

**Comment by Raycoms** [comment]
or windows-mac

**Comment by Dyerzombie** [comment]
No, all lowercase but the system running the server is windows 10 and the system I’m playing on is windows 11From,DyerzombieOn Mar 2, 2023, at 11:17, Raycoms ***@***.***> wrote:﻿
or windows-mac

**Comment by Raycoms** [comment]
hmm, dif windows versions dont matter
