### ISSUE TITLE
I can't order a building above level 2

### ISSUE THREAD

**Issue by JPZamps** [ldtteam/minecolonies#8969]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19.2

### MineColonies Version

1.19.2-1.0.1247-BETA

### Structurize Version

1.19.2-1.0.472-BETA

### Current Behavior

I have a small town and until then nothing had gone wrong, but when I went to build barracks and ordered with the build tool that it be built level 3 it was built level 1, and then I realized that every construction I tried to do with the build tool it does not go beyond level 2, I click to build I select the building level as 2-3 and I see that the building has appeared and when I click ok and I see what is asked for it is being built at level 1, I tried to upgrade but it ends up being just a level 1 build with upgrade 3 which is not what was asked

### Expected Behavior

What was supposed to be happening was the building leaving with level 3 and being able to be upgrade up to level 3-4, thus making a building level 3 upgrade 3

### Reproduction Steps

1. I clicked with the build tool
2. I selected the building
3. I selected the style
4. I selected level 3 for the building
5. I clicked ok (V)

### Logs

https://pastebin.com/DHNSDw2F

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
This is normal.  Buildings are always built at level 1 to start with; you then upgrade them using the GUI for the building itself.

The build tool only shows you the additional levels so that you can preview how they look and decide if it's the right building and location for you.

In the future, we recommend asking on the Discord if you have questions about how things work.

**Comment by JPZamps** [comment]
So what happened was another bug, because I simply can't upgrade the barracks anymore and it's in a very primitive state of wood and none of the upgrades showed that
