### ISSUE TITLE
[BUG] Builder don't want to build anymore

### ISSUE THREAD

**Issue by Marsshiii** [ldtteam/minecolonies#8970]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19.2

### MineColonies Version

1.19.2

### Structurize Version

2.7.1

### Related Mods and their Versions

ATM8

### Current Behavior

At first I have a bug with the University, where my builder doesn't want to put the colony flag
But now, I've got 2 bluider hut and non of them are built anymore (cause I try to break one and put it back) and my 2 builders doesn't want to build anything anymore
Also I've got the build request but it says 0 blocks needed which is false
![image_2023-02-25_085408389](https://user-images.githubusercontent.com/126317289/221345795-4398f6f8-55ba-4447-8338-5f7cbb0bf989.png)
![image_2023-02-25_085421372](https://user-images.githubusercontent.com/126317289/221345801-27a6a6e1-a281-48ac-a209-41b16e8d8e79.png)

And now my colonie are getting disease and I can do anything about it because I can't build anything

### Expected Behavior

I just want to fixe my builder

### Reproduction Steps

I don't know I want an answers :((

### Logs

https://gist.github.com/Marsshiii/aa72d4fe58cb8f8743500d182334b841#file-gistfile1-txt

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
How long did you wait for your builder without interfering. In some styles, the final scan to make sure everything in order sometimes takes quite some time. The log has nothing useful on it.
