### ISSUE TITLE
[BUG] Improper Version

### ISSUE THREAD

**Issue by Pheared-Phantom** [ldtteam/minecolonies#8971]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.19.2

### Structurize Version

1.19.2

### Related Mods and their Versions

The problem is that I can not play on 1.19 due to the fact that the dependencies are on different versions than what is available for minecolonies

### Current Behavior

The problem is that I can not play on 1.19 due to the fact that the dependencies are on different versions than what is available for minecolonies

### Expected Behavior

Minecolonies to be updated to 1.19.3 so it is playable on 1.19

### Reproduction Steps

1
2
3

### Logs

1

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
It's available on 1.19.3 already, you need to click the "view all" button on curseforge's website where the file list is

**Comment by Pheared-Phantom** [comment]
> It's available on 1.19.3 already, you need to click the "view all" button on curseforge's website where the file list is

I did, but i only see 1.19.2 available...

**Comment by Pheared-Phantom** [comment]
> It's available on 1.19.3 already, you need to click the "view all" button on curseforge's website where the file list is

My mistake, it was sorted improperly. Thank you
