### ISSUE TITLE
[BUG] Sorting erased all the items in the warehouse

### ISSUE THREAD

**Issue by Falk20** [ldtteam/minecolonies#8973]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.19.3-1.0.1243-ALPHA

### Structurize Version

1.19.3-1.0.482-ALPHA

### Related Mods and their Versions

1. alexsmobs-1.22.0
2. Aquaculture-1.19.3-2.4.11
3. blockui-1.19.3-0.0.68-ALPHA
4. carryon-forge-1.19.3-2.0.5.17
5. citadel-2.2.3-1.19.3
6. Clumps-forge-1.19.3-9.0.0+16
7. corpse-1.19.3-1.0.2
8. domum_ornamentum-1.19.3-1.0.79-ALPHA-universal
9. EasierSleeping-1.19.3-2.1.2
10. ecologics-forge-1.19.3-2.1.12
11. FallingTree-1.19.3-3.11.2
12. ferritecore-5.1.0-forge
13. geckolib-forge-1.19.3-4.0.3
14. ironchest-1.19.3-14.3.2
15. jei-1.19.3-forge-12.1.1.13
16. multipiston-1.19.3-1.2.26-ALPHA
17. queencats-1.0.3-1.19.3-Forge
18. twilightforest-1.19.3-4.2.1528-universal
19. u_team_core-1.19.3-4.5.1.238
20. useful_backpacks-1.19.3-1.14.2.108

### Reproduction Steps

1. Build a second-level warehouse
2. Fill the warehouse pallets with various items
3. Improve the warehouse to the third level
4. Click the "sort" button in the warehouse control panel
5. ???
6. All items disappear

I couldn't reproduce it again

### Logs

https://gist.githubusercontent.com/Falk20/3800a3c2895ed11ecae3a57b16904b24/raw/91078f7bd4e5f323a1b1c793a024441db6ddd5bf/Log

### Anything else?

I found a similar complaint in the discord, but I didn't see the issue in the github. https://discord.com/channels/139070364159311872/1003402487417548801/1073965064052281385

**Comment by Raycoms** [comment]
Warehouse style?

**Comment by Falk20** [comment]
Nordic

**Comment by chloeseitz27** [comment]
I also had this happen in the Minecolonies original style https://gist.github.com/chloehassall27/ee90e3ac78af3e5a6ba4c5c0a094dbe8
The mods we have in common are: 
- blockui-1.19.3-0.0.68-ALPHA I have 1.19.3-0.0.70-ALPHA)
- Clumps-forge-1.19.3-9.0.0+16
- domum_ornamentum-1.19.3-1.0.79-ALPHA-universal (I have 1.19.3-1.0.84-ALPHA)
- ferritecore-5.1.0-forge
- ironchest-1.19.3-14.3.2
- jei-1.19.3-forge-12.1.1.13 (I have 12.3.0.18)
- multipiston-1.19.3-1.2.26-ALPHA (I have 1.2.22)
- twilightforest-1.19.3-4.2.1528-universal (I have 4.2.1549)
