### ISSUE TITLE
[BUG] AI issue with a builder

### ISSUE THREAD

**Issue by anonymous563** [ldtteam/minecolonies#8977]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

minecolonies-1.19.2-1.0.1262-ALPHA

### Structurize Version

structurize-1.19.2-1.0.480-ALPHA

### Related Mods and their Versions

domum_ornamentum-1.19-1.0.76-ALPHA-universal

### Reproduction Steps

No idea! Train said just to report it here.
Restarting Minecraft and restarting the worker didn't do anything to fix this.

### Logs

https://gist.github.com/anonymous563/dd0b1239c40fd8d611e5d4c3cf9545e6

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
Can you check their requests list to maybe see what they are attempting to craft?
Supposedly the recipe he is looking to craft has no output item.

**Comment by anonymous563** [comment]
Unfortunately not anymore. I creative fulfilled the requests to see if that would fix it, but I don't think it did.
