### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by Sand-Tiger** [ldtteam/minecolonies#8980]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

0.14.343-ALPHA-universal.jar

### Structurize Version

0.13.210-ALPHA-universal.jar

### Related Mods and their Versions

Advancement Plaques [Forge]
Grend_G
AdvancementPlaques-1.16.5-1.3.1.jar

Aquaculture 2
Shadowclaimer
Aquaculture-1.16.5-2.1.20.jar

Architectury API (Fabric/Forge)
shedaniel
architectury-1.20.29-forge.jar

Bedspreads (Forge)
TheIllusiveC4
bedspreads-forge-1.16.5-5.1.0.2.jar

BetterEnd (Forge)
Beethoven92
betterendforge-1.16.4-1.6.0.jar

Blood Magic
WayofTime
BloodMagic-1.16.4-3.1.1-16.jar

Blueprint
TeamAbnormals
abnormals_core-1.16.5-3.2.0.jar

Citadel
sbom_xela
citadel-1.7.3-1.16.5.jar

Clumps
Jaredlll08
Clumps-6.0.0.25.jar

Collective
Serilum
collective-1.16.5-2.58.jar

Comforts (Fabric/Forge/Quilt)
TheIllusiveC4
comforts-forge-1.16.5-4.0.1.2.jar

Cosmetic Armor Reworked
LainMI
CosmeticArmorReworked-1.16.5-v4.jar

Craftable Horse Armour & Saddle [CHA&S]
EwyBoy
CraftableHorseArmour-1.16.5-1.6.jar

Curios API (Forge)
TheIllusiveC4
curios-forge-1.16.5-4.0.5.2.jar

DisenchantingForge
chirptheboy
Disenchanting-forge-1.16.5-1.7.1.jar

Dynamic Surroundings
OreCruncher
DynamicSurroundings-1.16.4-4.0.4.2.jar

Dynamic Trees
ferreusveritas
DynamicTrees-1.16.5-0.10.0-Beta24.jar

Enhanced Celestials - Blood, Blue, & Harvest (Super) Moons
Corgi_Taco
enhancedcelestials-2.0.5-1.16.5.jar

FTB Library (Forge)
FTB
ftb-library-forge-1605.3.2-build.64.jar

FTB Quests (Forge)
FTB
ftb-quests-forge-1605.3.3-build.49.jar

FTB Teams (Forge)
FTB
ftb-teams-forge-1605.2.1-build.20.jar

Goblin Traders
MrCrayfish
goblintraders-1.6.0-1.16.3.jar

Ice and Fire: Dragons
sbom_xela
iceandfire-2.1.8-1.16.5.jar

Illagers+
LiteWolf101
illagers_plus-1.16.4v1.5.jar

Iron Chests
ProgWML6
ironchest-1.16.5-11.2.13.jar

Iron Furnaces [FORGE]
XenoMustache
ironfurnaces-1.16.5-2.7.3.jar

Just Enough Items (JEI)
mezz
jei-1.16.5-7.7.1.118.jar

Kotlin for Forge
thedarkcolour
kotlinforforge-1.14.0-obf.jar

Mantle
mDiyo
Mantle-1.16.5-1.6.115.jar

Medieval Craft (Structures)
franciscofunari
MedievalCraft-1.16.5-1.15.10.jar

MineColonies
H3lay
minecolonies-0.14.343-ALPHA-universal.jar

More Villagers
SameDifferent
morevillagers-FORGE-1.16.5-1.5.4.jar

Mowzie's Mobs
bobmowzie
mowziesmobs-1.5.19.jar

Oh The Biomes You'll Go
AOCAWOL
byg-1.3.1.jar

Placebo
Shadows_of_Fire
Placebo-1.16.4-4.5.0.jar

Serene Seasons
TheAdubbz
SereneSeasons-1.16.5-4.0.1.121-universal.jar

Structurize
H3lay
structurize-0.13.210-ALPHA-universal.jar

The Twilight Forest
Benimatic
twilightforest-1.16.5-4.0.546-universal.jar

Tinkers Construct
mDiyo
TConstruct-1.16.5-3.1.1.252.jar

Tree Harvester
Serilum
treeharvester_1.16.5-2.9.jar

Undead Army!
pixelgeist666
undeadarmy-2-1.jar

Valhelsia Core
ValhelsiaTeam
valhelsia_core-16.0.10.jar

Valhelsia Structures
ValhelsiaTeam
valhelsia_structures-1.16.5-0.1.5.jar

Bountiful (Forge)
Ejektaflex
Bountiful-1.16.4-3.3.1.jar

Dragon Drops Elytra
Serilum
dragondropselytra_1.16.5-1.4.jar

Eidolon
elucent_
eidolon-0.2.7.jar

GuardsCraft
sgtmattbaker
guardscraft-1.16.5-1.1.1.jar

Horse Statistics
nero_surfing
horsestatsmod-MC1.16.x-1.4.2.jar

Hwyla
TehNut
Hwyla-forge-1.10.11-B78_1.16.2.jar

Ice and Fire: Dragonseeker
syrikalis
dragonseeker-1.1.jar

Item Filters
LatvianModder
item-filters-forge-1605.2.5-build.9.jar

Nature's Compass
Chaosyr
NaturesCompass-1.16.5-1.9.1-forge.jar

Netherite Horse Armor Mod
j0s3ph_k
netheritehorsearmor-1.7.jar

No Villager Death Messages
MutantGumdrop
novillagerdm-1.0.1.jar

One Player Sleeping
JayJay1989BE
oneplayersleeping-1.16.4-0.0.5.jar

Skeleton Horse Spawn
Serilum
skeletonhorsespawn_1.16.5-1.9.jar

Spartan Shields
ObliviousSpartan
SpartanShields-1.16.5-2.1.2.jar

The Outer End
BlueDuckYT
OuterEnd-0.2.14.jar

ToroHealth Damage Indicators
ToroCraft
torohealth-1.16.4-forge-4.jar

Two Players One Horse
Beethoven92
twoplayersonehorse-1.16.4-2.0.2.jar

VoxelMap
MamiyaOtaru
forgemod_VoxelMap-1.10.12_for_1.16.5.jar

Waila Harvestability
squeek502
WailaHarvestability-mc1.16.x-forge-1.1.15.jar

YUNG's Better Caves (Forge)
YUNGNICKYOUNG
BetterCaves-Forge-1.16.4-1.1.2.jar

YUNG's Better Mineshafts (Forge)
YUNGNICKYOUNG
BetterMineshafts-Forge-1.16.4-2.0.4.jar

Zombie Horse Spawn
Serilum
zombiehorsespawn_1.16.5-3.0.jar

### Reproduction Steps

Make a miner and have them start the mining process. the miner block was placed at about y=60 and it would not make nodes after digging down to y=50 where the GUI says the it should be making them. Miner is at lever 2 now but it was doing this at level 1 as well.

### Logs

<script src="https://gist.github.com/Sand-Tiger/b2d356f02528a1887351fa37cb67c9c8.js"></script>

### Anything else?

This is in the modpack Game of Ice and Fire through Curse forge by Canadioryan and the miner is the villager that is making this error message.

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Sorry, 1.16.5 is EOL

**Comment by Sand-Tiger** [comment]
I'm not sure what EOL means, but the Minecraft version that launches is 1.16.5. there was not an option whe filling out this form.

**Comment by Raycoms** [comment]
EOL, we do not support this version anymore. Please upgrade to 1.18+

**Comment by BraveCaperCat2** [comment]
(Probably) Not his modpack.

**Comment by Raycoms** [comment]
Yeah, would have to pick a newer modpack then to receive support

**Comment by BraveCaperCat2** [comment]
Also, just for you to note, the UI in the 1.18.2 and later versions is completely different compared to 1.16.5 and was very hard to understand on a computer with <30 FPS (compared to the computer i normally use with >120 FPS)
