### ISSUE TITLE
[BUG]Description missing for "Knowledge of the Depth" research

### ISSUE THREAD

**Issue by corvusv** [ldtteam/minecolonies#8981]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19.2

### MineColonies Version

minecolonies-1.19.2-1.0.1200-BETA

### Structurize Version

structurize-1.19.2-1.0.479-ALPHA

### Current Behavior

Missing description for what "Knowledge of the Depth" does at the university. Information ava

### Expected Behavior

Expected to see "[Crusher Huts] can convert deepslate into tuff and tuff into cobblestone"

### Reproduction Steps

Check technology research

### Logs

https://gist.github.com/corvusv/4da67790e8b901332e1b478edafc4b92

### Anything else?

![image](https://user-images.githubusercontent.com/108915030/221970570-e98234c5-0413-419a-ba38-a48bfb27e7e6.png)

**Comment by MotionlessTrain** [comment]
Could you check on the newest alpha? You are roughly 60 versions outdated
