### ISSUE TITLE
[BUG] Guard is shifty. 

### ISSUE THREAD

**Issue by drkanbs** [ldtteam/minecolonies#8982]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.18.2-1.0.1197-ALPHA

### Structurize Version

1.18.2-1.0.424-ALPHA

### Current Behavior

I was assigning a minion to another building and I turn around to goto a builder house and there's a guard frozen, uh skipping in place unable to be recalled or moved.  
![Screenshot (80)](https://user-images.githubusercontent.com/22972588/221983931-3c57956b-e12a-4021-8b93-d2bd2a17d2ed.png)

### Expected Behavior

Just patrolling the area. 

### Reproduction Steps

I don't think there's a way to reproduce this.  It just sorta happened. 

### Logs

https://gist.github.com/drkanbs/16b8e655c53eecf1aa3f416b766ee01c

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by drkanbs** [comment]
forgot, it's apart of the Inferno Modpack

**Comment by Thodor12** [comment]
Considering you're in a heavily modded pack and you have no reproduction, all I can say is just try and restart it.

**Comment by Raycoms** [comment]
does world reload solve it?
