### ISSUE TITLE
Farmers no eat

### ISSUE THREAD

**Issue by XxAmber21xx** [ldtteam/minecolonies#8984]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19.2

### MineColonies Version

1.19.2-1.0.1265-ALPHA

### Structurize Version

1.19.2-1.0.480

### Current Behavior

When my farmers go to the restaurant they complain that they have raw food for example carrots, wheat, beef etc.. but the chef doesn’t go and feed them any cooked meats. Have had many farmer colonist die due to starving to death.

### Expected Behavior

Expected the chef to go and feed the farmers more cooked food and he/she doesn’t. Tried restarting jobs and still having the same issue.

### Reproduction Steps

1. Have farmer be hungry.
2. Watch go to restaurant.
3. Wait for the chef to go and feed them.(but they don’t )
4. manually put food in to stop them starving.

### Logs

https://pastebin.com/frRdTevE

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Im very confused by this report. First, there is no starving to death element in Minecolonies, so I dont get how that would happen. Second, I tried to reproduce this and it didnt happen. Can you tell us exactly what they had in their inventory, and what the cook had available, what level the housing/worker huts/restaurant was?

**Comment by anonymous563** [comment]
My guess is that the farmer scans their inventory for food, see that they have raw potatoes first, and then refuse to eat the raw potatoes because their standards are higher.

**Comment by Raycoms** [comment]
No, I tested that

**Comment by Raycoms** [comment]
Did some small adjustments
