### ISSUE TITLE
[Graphic problem] <The problem with multiplayer and experimental settings>

### ISSUE THREAD

**Issue by Skeleton4ek** [ldtteam/minecolonies#8989]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19.2

### MineColonies Version

1.0.1163-BETA

### Structurize Version

1.0.471-ALPHA

### Related Mods and their Versions

1.domum_ornamentum-1.19-1.0.76-ALPHA-universal
2.blockui-1.19-0.0.64-ALPHA
3.forge 43.2.3

### Current Behavior

For players who join my world, they don't see some graphical parameters in buildings.
While the problem has been encountered in the improvements of the university, a button is not available in all houses to teach how to make a subject, there is no choice of a subject for frying from a cook and a melting pot.

### Expected Behavior

I thought if I recreate the world, but still, the players don't see the graphic buttons, nothing changes

### Reproduction Steps

Well, I got it this way, I guess:
1. I created a world with the assembly of different mods, played with the player for one day and came out, everything was fine without complaints.
2. I entered the world, but there was a warning about experimental settings, I confirmed and entered the world with the player. After that, his buttons disappeared
He repeated everything the same in his world in the same order everything was repeated

### Logs

https://gist.github.com/Skeleton4ek/9bf80b384edfb8fa90cd60096139787b

### Anything else?

![image](https://user-images.githubusercontent.com/87833642/222965743-42189cf6-5a85-45b5-931d-f69e3504ccad.png)

**Comment by MotionlessTrain** [comment]
Are you using LAN mode?

**Comment by Nightenom** [comment]
Hi,
first thing is to download mods from legitimate sources (e.g. curseforge) - search your log for "stopmodreposts.org", there are two mods downloaded from suspicious sites.
second thing - try running without optifine, if you want shaders then please use different shader mods (eg. oculus)

~lan mode should no longer be a problem afaik~

**Comment by MotionlessTrain** [comment]
> lan mode should no longer be a problem afaik

It still is

**Comment by Raycoms** [comment]
No answers, probably lan mode,
