### ISSUE TITLE
[BUG] Texture glitch when updating from 1.18.2-1.0.1251 to 1.18.2-1.0.1271

### ISSUE THREAD

**Issue by Lion010101** [ldtteam/minecolonies#8990]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

minecolonies-1.18.2-1.0.1271-ALPHA.jar

### Structurize Version

structurize-1.18.2-1.0.424-ALPHA.jar

### Related Mods and their Versions

1. Forge - 40.2.1

2. blockui-1.18.2-0.0.71-ALPHA.jar

3. domum_ornamentum-1.18.2-1.0.50-ALPHA-universal.jar

4. betterwithminecolonies-1.16.5++-1.18.19.jar

![Minecolonies bug](https://user-images.githubusercontent.com/118841064/222970853-d0100d6d-db98-47eb-8981-314af7962d3e.png)

### Current Behavior

textures for the Builders hut,Mechanics Hut,Warehouse,Townhall,Mine,Library,Enchanters Tower and University glitched during the update from minecolonies-1.18.2-1.0.1251-ALPHA.jar to minecolonies-1.18.2-1.0.1271-ALPHA.jar

### Expected Behavior

for the worker block to have a texture after updating

### Reproduction Steps

update from minecolonies-1.18.2-1.0.1251-ALPHA.jar to minecolonies-1.18.2-1.0.1271-ALPHA.jar

### Logs

the latest.log is way to long and provides no information about it.

### Anything else?

that is everything let me know if it helps solve the issue :3

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Fix pushed
