### ISSUE TITLE
[BUG] Food screen in restaurant crashes to desktop

### ISSUE THREAD

**Issue by TaeoG** [ldtteam/minecolonies#8994]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19.2

### MineColonies Version

1.0.1247-BETA

### Structurize Version

1.0.476-ALPHA

### Related Mods and their Versions

1. Forge :  43.2.4
2. BlockUI : 0.0.64-ALPHA
3. Domum Ornamentum :  1.0.75-ALPHA
4. Biomancy 2: 2.0.48.0

### Current Behavior

Opening the food tab in the restaurant interface crashes the game

### Expected Behavior

Obviously not that

### Reproduction Steps

1. Place a restaurant in your village
2. Access the restaurant block
3. Try to open the food tab (the one that looks like a carrot)

### Logs

https://pastebin.com/RWQVkgrK

### Anything else?

Given the contents of the crash report, it seems the BlockUI interface code doesn't handle atypical tooltip implementations or something like that

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Nightenom** [comment]
Please update Biomancy to latest version

**Comment by TaeoG** [comment]
Awesome, hopefully Biomancy dev releases the newer version soon
