### ISSUE TITLE
[BUG] Builder Stop Working

### ISSUE THREAD

**Issue by Ashuntoi** [ldtteam/minecolonies#8996]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19.2

### MineColonies Version

minecolonies-1.19.2-1.0.1273-ALPHA

### Structurize Version

structurize-1.19.2-1.0.483-ALPHA

### Related Mods and their Versions

forgeVersion, 43.2.6
blockui-1.19-0.0.69-ALPHA
domum_ornamentum-1.19-1.0.83-ALPHA-universal
veinmining-forge-1.1.0+1.19.2

### Current Behavior

The builder stop working and tell me to report why.

![Capture d’écran 2023-03-09 005254](https://user-images.githubusercontent.com/34601480/223879533-25891f7f-5c51-4f6a-a683-470ddf998459.png)

### Expected Behavior

Build my guard tower.

### Reproduction Steps

Just go near the builder with a Vein Mining pickaxe.

### Logs

https://pastebin.com/WaU6yLVi

**Comment by ThomMcLean** [comment]
I have run into the same problem and request to post latest.log

I noticed this bug report includes veinmining. We recently added that mod, so if there is any correlation, I'll post my log file here as well.
[latest.log](https://github.com/ldtteam/minecolonies/files/10926870/latest.log)

**Comment by MotionlessTrain** [comment]
It looks like veinminer assumes that just players are using the tool. As the builder is not a player, that assumption doesn't work and veinminer crashes, which causes the builder's AI to fail

Could you report this to them?

**Comment by Raycoms** [comment]
Def on them
