### ISSUE TITLE
[BUG] WAREHOUSE SORT BUTTON NOT SORTING

### ISSUE THREAD

**Issue by AliAhmed0411** [ldtteam/minecolonies#8998]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19.3

### MineColonies Version

1.0.1275

### Structurize Version

1.0.484

### Related Mods and their Versions

1. Forge - 44.1.21
2. blockui - 0.0.70
3. domum ornamentum - 1.0.86
4. multipiston - 1.2.22

### Current Behavior

When I use the sort button in the warehouse, nothing happens to my stock - however the racks lose the appearance of having items. When I open the rack and add/remove an item, the appearance appears again, but there is no sorting of the stock

### Expected Behavior

My items in the warehouse sort into stacks

### Reproduction Steps

1. Use the sort button

### Logs

https://pastebin.com/qP33DbEq

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
does restarting fix this?

**Comment by AliAhmed0411** [comment]
> does restarting fix this?

no the same thing happens - i haven’t been able to sort my warehouse since i started playing. Before the last update for minecolonies all of my stock just got deleted but now after updating the stock stays exactly the same but the racks appear empty from outside

**Comment by AliAhmed0411** [comment]
https://pastebin.com/KhXb9mb4 log with new update - bug is still there. Can I get this issue reopened?
