### ISSUE TITLE
Can't join on my server

### ISSUE THREAD

**Issue by hereticlegion** [ldtteam/minecolonies#9006]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

minecolonies-1.18.2-1.0.1285-ALPHA

### Structurize Version

structurize-1.18.2-1.0.424-ALPHA

### Related Mods and their Versions

Forge 40.2.0
blockui-1.18.2-0.0.71-ALPHA
domum_ornamentum-1.18.2-1.0.77-ALPHA-universal
multi-piston-1.18.2-1.2.15-ALPHA

### Current Behavior

I can't connect to my own (running server)
ERROR net.minecraftforge.fml.javafmlmod.FMLModContainer - Exception caught during firing event: Cannot invoke "org.apache.logging.log4j.core.LoggerContext.updateLoggers()" because the return value of "org.apache.logging.log4j.core.config.Configuration.getLoggerContext()" is null

### Expected Behavior

Server and Client files are up to date, in sync and the server in running, expected to join without problems

### Reproduction Steps

I'm running an altered version of the Life in the village 3 MOdpack

### Logs

https://gist.github.com/hereticlegion/42d1e63829884a39673ab24db16a2dfd

### Anything else?

EDIT: insert gist link

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
gist.github.com can also be used to paste logs, and makes it much more readable

**Comment by Raycoms** [comment]
You are in an environment where log4j seems to be not installed properly. Please try to update forge, java, etc.
