### ISSUE TITLE
[BUG] CompatibilityManager#discoverAllItems is being called on server side

### ISSUE THREAD

**Issue by caelwarner** [ldtteam/minecolonies#9008]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19.3

### MineColonies Version

1.0.1275-ALPHA

### Structurize Version

1.0.484-ALPHA

### Related Mods and their Versions

1. Forge Version: 44.1.21
2. Create Version: 1.19.3 0.5.0j

### Current Behavior

`CompatibilityManager#discoverAllItems` is getting called on the server side by `DataPackSyncEventHandler$ServerEvents#loadRecipes` which causes crashes when other mods run client side only code to build their creative mode tabs. The specific incompatibility is with Create.

### Expected Behavior

`CompatibilityManager#discoverAllItems` not be called on the server side.

### Reproduction Steps

1. Install Create & MineColonies
2. Run server

### Logs

https://gist.github.com/Ackar77/9121a3c738ff8e658bc40d2a7c07f35a

### Anything else?

The issue on Create's repo Creators-Of-Create/Create#4545

**Comment by uecasm** [comment]
This is completely intentional, and ideally Create should fix it on their side.  There shouldn't be any particular reason why this method can't be called on server side.  (Albeit it's true that it is only called on client side in vanilla.)

Having said that, we could possibly add in something to work around broken code in other mods.

**Comment by Raycoms** [comment]
This is the only way to get some data, please report to create

**Comment by caelwarner** [comment]
Alright, I will look into fixing it on Create's side. I originally thought this might be unintentional based off of the comment on `CompatibilityManager#discoverAllItems` https://github.com/ldtteam/minecolonies/blob/b05287d2e3511d6279ed882b9b2cfa68d911c392/src/api/java/com/minecolonies/api/compatibility/CompatibilityManager.java#L607-L610

**Comment by Raycoms** [comment]
Oh, Thats an old comment, it used to be client side only some time back. We should remove that too.
Nowadays we do it both sides so both sides have the same knowledge.

**Comment by uecasm** [comment]
The comment has been removed in the patch above already. 😁
