### ISSUE TITLE
[BUG] Raiders break doors and place ladders, even when config says otherwise

### ISSUE THREAD

**Issue by anonymous563** [ldtteam/minecolonies#9012]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19.2

### MineColonies Version

minecolonies-1.19.2-1.0.1287-ALPHA

### Structurize Version

structurize-1.19.2-1.0.485-ALPHA

### Current Behavior

When the config says
`shouldraiderbreakdoors = false`
and a raid occurs, the raiders replace doors with ladders, effectively breaking down doors.

Possibly related, raiders still place ladders even though 
`dobarbariansbreakthroughwalls = false`

### Expected Behavior

Setting the config to `shouldraiderbreakdoors = false` should make raiders not break down doors.
Setting the config to `dobarbariansbreakthroughwalls = false` should make raiders not break walls, place ladders, or bridge over gaps.

### Reproduction Steps

1. Put down a house. Have a citizen live in it.
2. Have a raid happen. Don't kill any raiders.
3. Eventually, they should replace the door with ladders and/or just break down the door.

### Logs

N/A

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
there is no config for ladders, but there is for breaking doors

**Comment by anonymous563** [comment]
the description for it says
`#Whether or not raiders can break, scale, and bridge obstacles. [Default: true]`
so i thought the "scale" part referred to ladders. either way, placing ladders shouldn't break down doors though imo

**Comment by Raycoms** [comment]
Good point, will adjust that in my pr then too
