### ISSUE TITLE
[BUG] Composter request list hard to read

### ISSUE THREAD

**Issue by anonymous563** [ldtteam/minecolonies#9017]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19.2

### MineColonies Version

minecolonies-1.19.2-1.0.1296-ALPHA

### Structurize Version

structurize-1.19.2-1.0.487-ALPHA

### Current Behavior

The composter's request list is hard to read. It's not clear which items are being delivered. This is on the worker, not the hut block.

![image](https://user-images.githubusercontent.com/34487065/226156468-d1700086-1ea5-47b3-9591-4f3289e29477.png)

### Expected Behavior

It should mirror the new courier hut task list!

### Reproduction Steps

1. Have a composter, warehouse, and couriers.
2. Have compostable items in the warehouse.
3. Wait for composter to request items.
4. Look at composter's open requests.

### Logs

N/A

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
You can click on the three-lines button to see more details of the request.
