### ISSUE TITLE
[BUG] Extreme Spam Related To Sleep Pathing Being Null After Updating Past ``minecolonies-1.19.2-1.0.1295-ALPHA.jar`` 

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [ldtteam/minecolonies#9020]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19.2

### MineColonies Version

minecolonies-1.19.2-1.0.1296-ALPHA.jar - minecolonies-1.19.2-1.0.1304-ALPHA.jar

### Structurize Version

 structurize-1.19.2-1.0.490-ALPHA.jar

### Related Mods and their Versions

Nothing else is at fault. Just don't blame the modpack because it works after downgrading back to minecolonies-1.19.2-1.0.1295-ALPHA.jar

### Current Behavior

After updating log spam related to sleep being null has occurred to the tune of bloating file to 2MB

### Expected Behavior

All sleep nodes and logs should work as intended.

### Reproduction Steps

Install this modpack https://www.curseforge.com/minecraft/modpacks/fiction-friction-pixelmon/files/4444534 (Modpack not at fault)

Update the Minecolonies ``minecolonies-1.19.2-1.0.1295-ALPHA.jar+Dependencies`` to any version ``minecolonies-1.19.2-1.0.1296-ALPHA.jar, minecolonies-1.19.2-1.0.1302-ALPHA.jar, minecolonies-1.19.2-1.0.1304-ALPHA.jar``

You need an old world that was running ``minecolonies-1.19.2-1.0.1295-ALPHA.jar+Dependencies`` to replicate environment. (Preferably with significant work done)

Run as dedicated server.

### Logs

https://gist.github.com/P3rf3ctXZer0/94d8a0fd066f304deef01f8997519363

### Anything else?

Do not ask me to tear apart modpack because it is not the modpacks fault. Something happened between ``minecolonies-1.19.2-1.0.12962-ALPHA.jar+Dependancies`` and ``minecolonies-1.19.2-1.0.1304-ALPHA.jar+Dependancies``

**Comment by P3rf3ctXZer0** [comment]
Okay so the bug starts at and between these two versions ``minecolonies-1.19.2-1.0.1296-ALPHA.jar - minecolonies-1.19.2-1.0.1304-ALPHA.jar`` all have the same bug.

**Comment by P3rf3ctXZer0** [comment]
So of course its no longer happening ... I hate minecraft. (Hopefully the log helps yall devs shed some light.) My world was about 4 weeks old.

**Comment by MotionlessTrain** [comment]
It looks like that when `findBedAndTryToSleep()` times out (when no bed can be found in the housing, for some reason), `usedBed` stays `null`. Which gives issues with the check in `sleep()`, which assumes there is a bed, and lets the citizen walk close to it

**Comment by Raycoms** [comment]
fix pushed
