### ISSUE TITLE
[BUG] minecolonies.requestsystem constant spam in debug.log

### ISSUE THREAD

**Issue by emanuele246gi** [ldtteam/minecolonies#9021]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

minecolonies-1.18.2-1.0.1305-ALPHA

### Structurize Version

structurize-1.18.2-1.0.424-ALPHA

### Current Behavior

In my survival world, Minecolonies keeps spamming in the debug.log the messages that you can see in the link below. This issue only happens in this world and even with the "enabledebuglogging" config set to false

### Expected Behavior

To not spam with enabledebuglogging = false

### Reproduction Steps

-

### Logs

https://gist.github.com/emanuele246gi/978e91985d09c06d7de3c3df113fc1ec

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
You probably got one of the log4j debug flags set to true, that overrides anything.

**Comment by MotionlessTrain** [comment]
I could reproduce it. I haven't messed with any config at all

**Comment by Raycoms** [comment]
How did you reproduce it?

**Comment by MotionlessTrain** [comment]
I looked in the debug log of my own play world. I haven't messed with any configs at all, and double checked that enabledebuglog was set to false

**Comment by Raycoms** [comment]
Ahh, the debug.log file not the latest.log file. Is this a problem somehow?

**Comment by MotionlessTrain** [comment]
The config option seems to indicate it turns off those request system messages in the debug.log, so either the comment is confusing, or something is broken.

I don't think it is a huge problem, unless the disk has storage issues, and the size of the debug.log could be a problem

**Comment by Raycoms** [comment]
The problem is basically that the config is loaded too late for this to take effect. So we cannot config lock this anymore afaik. @marchermans can we do anything about this, or should we drop the config value? Move it to common config?

**Comment by emanuele246gi** [comment]
Would it risk to affect performance even a bit?

**Comment by marchermans** [comment]
Yes, the logging is pretty heavy on larger colonies, which is why it is disabled by default.

**Comment by emanuele246gi** [comment]
So that may explain some things, thanks
