### ISSUE TITLE
[BUG] I have the newest version of structurize, but when I try to start TLauncher, it says that structurize is missing.

### ISSUE THREAD

**Issue by SkullGamer507** [ldtteam/minecolonies#9032]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.0.1305-ALPHA

### Structurize Version

1.0.448-ALPHA

### Related Mods and their Versions

 [1.18.2-forge]-Epic-Knights-7.11.jar
 alexsdelight-1.18.2-1.3.3.jar
 alexsmobs-1.18.6.jar
 appleskin-forge-mc1.18.2-2.4.1.jar
 architectury-4.11.89-forge.jar
 balm-3.2.6.jar
 BiomesOPlenty-1.18.2-16.0.0.134.jar
 blockui-1.18.2-0.0.71-ALPHA.jar
 Blood-Smeltery-1.18.2-1.1.5a.jar
 BloodMagic-1.18.2-3.2.6-41.jar
 Ceramics-1.18.2-1.7.1.jar
 cfm-7.0.0-pre35-1.18.2.jar
 champions-forge-1.18.2-2.1.6.3.jar
 chococraft-1.18.2-0.5.2.jar
 citadel-1.11.3-1.18.2.jar
 cleancut-mc1.18.2-4.0-forge.jar
 cloth-config-6.4.90-forge.jar
 CNB-1.18.2-1.5.1.jar
 create-1.18.2-0.5.0.i.jar
 DoggyTalents-1.18.2-2.5.11.jar
 domum_ornamentum-1.18.2-1.0.77-ALPHA-universal.jar
 DynamicTrees-1.18.2-0.11.0-Beta8.jar
 DynamicTreesBOP-1.18.2-3.0.0-Beta3.jar
 ecologics-forge-1.18.2-1.7.11.jar
 Enhanced_Celestials-forge-1.18.2-2.0.7.jar
 FarmersDelight-1.18.2-1.2.0.jar
 flywheel-forge-1.18.2-0.6.8.a.jar
 geckolib-forge-1.18-3.0.57.jar
 iceandfire-2.1.12-1.18.2-beta.jar
 immersive_armors-1.5.4+1.18.2-forge.jar
 invhud.forge.1.18.2-3.4.10.jar
 ironchest-1.18.2-13.2.11.jar
 ironfurnaces-1.18.2-3.3.3.jar
 Jade-1.18.2-forge-5.2.6.jar
 JadeAddons-1.18.2-forge-2.4.1.jar
 jei-1.18.2-forge-10.2.1.1004.jar
 journeymap-1.18.2-5.9.4-forge.jar
 Mantle-1.18.2-1.9.43.jar
 minecolonies-1.18.2-1.0.1305-ALPHA.jar
 minecraft-comes-alive-7.4.8+1.18.2-universal.jar
 mowziesmobs-1.5.32.jar
 multi-piston-1.18.2-1.2.15-ALPHA.jar
 NaturesCompass-1.18.2-1.9.7-forge.jar
 OptiFine-1.18.2_HD_U_H9_pre1.jar
 Patchouli-1.18.2-71.1.jar
 playerex-3.4.2.jar
 projectvibrantjourneys-1.18.2-4.1.1.jar
 reap-1.18.2-1.0.0.jar
 rottencreatures-forge-1.18.2-1.0.0.jar
 smallships-1.18.2-2.0.0-Alpha-0.4.jar
 structurize-1.18.2-1.0.448-ALPHA.jar
 TConstruct-1.18.2-3.6.3.111.jar
 TerraBlender-forge-1.18.2-1.2.0.126.jar
 tl_skin_cape_forge_1.18_1.18.2-1.25.jar
 tombstone-7.6.2-1.18.2.jar
 ToughAsNails-1.18.2-7.0.0.73.jar
 TravelersBackpack-1.18.2-7.1.28.jar
 waystones-forge-1.18.2-10.2.0.jar
 woodenshears-1.18.2-1.2.1.2.jar
 YungsApi-1.18.2-Forge-2.2.9.jar
 YungsBetterDesertTemples-1.18.2-Forge-1.3.1.jar
 YungsBetterDungeons-1.18.2-Forge-2.1.0.jar
 YungsBetterMineshafts-1.18.2-Forge-2.2.jar
 YungsBetterNetherFortresses-1.18.2-Forge-1.0.0.jar
 YungsBetterOceanMonuments-1.18.2-Forge-1.0.3.jar
 YungsBetterStrongholds-1.18.2-Forge-2.1.1.jar
 YungsBetterWitchHuts-1.18.2-Forge-1.0.1.jar
 YungsBridges-1.18.2-Forge-2.1.0.jar
 YungsExtras-1.18.2-Forge-2.1.0.jar
 zmedievalmusic-1.18.2-1.4.jar
OptiFine and Forge (Last version available for 1.18.2)

### Reproduction Steps

- Select 1.18.2 ForgeOptiFine option for TLauncher.
- Place all mods on the "mods" folder.
- Start the game.
- Wait for a screen that says that structurize is missing.

### Logs

I'm confused about this step.

### Anything else?

Does it has to do with me playing on TLauncher?

**Comment by MotionlessTrain** [comment]
Don't use TLauncher. There is zero tolerance towards cracked launchers

**Comment by SkullGamer507** [comment]
Ok (I want to delete this now)
