### ISSUE TITLE
[BUG] Unable to select Citizen Style - options blanked

### ISSUE THREAD

**Issue by Knaxia** [ldtteam/minecolonies#9034]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19.3

### MineColonies Version

minecolonies-1.19.4-1.0.1321-ALPHA

### Structurize Version

structurize-1.19.4-1.0.489-ALPHA

### Related Mods and their Versions

1. forge-1.19.4-45.0.31
2. blockui-1.19.4-0.0.73-ALPHA
3. domum_ornamentum-1.19.4-1.0.88-ALPHA-universal
4. journeymap-1.19.4-5.9.4beta2-forge
5. multipiston-1.19.3-1.2.26-ALPHA
6. worldedit-mod-7.2.14

### Current Behavior

As a Patreon, both Citizen Style and Naming Convention options are open. I remember in the past having no issue selecting the Citizen Style (1.17 and 1.18). Right now, both in 1.19.3 and in 1.19.4, the options are available, but only the Naming Convention has something in it , and has a list I can pick from. Citizen style is blank, and if I click it, nothing happens. It seems that a menu appears because if I press Escape, nothing happens, as if that invisible menu closes, then pressing Escape again closes the town hall interface.

I made sure all my account linking were correct in, even unlinked and redid the minecraft one, but same thing again. If there was a problem there, the Naming Convension would also be greyed out.

### Expected Behavior

Being able to pick a Citizen Style.

### Reproduction Steps

1. Create Colony
2. Access Town hall block
3. Go in Settings, check Pick Citizen Style (Must be Donor).

### Logs

No logs.

### Anything else?

![2023-03-29_21 53 22](https://user-images.githubusercontent.com/73440864/228707797-aad3670b-6ded-4468-96ec-c19e39d809f9.png)

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Can you send us the log from a moment you open it?

-------- Original Message --------

**Comment by Knaxia** [comment]
I updated to .1322 that was uploaded earlier today (which fixed my other issue you closed, thanks a bunch!)

I started the game in single player, loaded my test 1.19.4 colony, opened the townhall book, went to settings, it went from dark gray grayed to available, Citizen style was still empty, Naming convention was available with the list showing up and options selectable, I closed the game after.

Here are both latest and debug logs:
[latest.log](https://github.com/ldtteam/minecolonies/files/11113662/latest.log)
[debug.log](https://github.com/ldtteam/minecolonies/files/11113665/debug.log)

**Comment by Raycoms** [comment]
fix pushed
