### ISSUE TITLE
[BUG] <The block is missing its respective building, try restarting or loading a backup>

### ISSUE THREAD

**Issue by MidnightRoseLight666** [ldtteam/minecolonies#9050]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19.3

### MineColonies Version

minecolonies-1.19.4-1.0.1334-ALPHA

### Structurize Version

structurize-1.19.4-1.0.489-ALPHA

### Related Mods and their Versions

![Screenshot 2023-04-05 134631](https://user-images.githubusercontent.com/129987358/230161826-6ec64f7b-e0be-40a0-8588-9c12bc4a0e09.png)

### Current Behavior

![the issue](https://user-images.githubusercontent.com/129987358/230162014-765eb723-3c6b-419d-8a1e-25473f65ce24.png)

I have used the town hall to start the colony, but then i go to make the builders hut...but i get that message

### Expected Behavior

I expected to be able to...make the colony?

### Reproduction Steps

I'd recommend having a starters guide in the mod, as well as another guide to bug fixes that would be within the game.

### Logs

not sure where the log is...

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Did you place the builders hut otuside of the colony borders? or did it crash after placement or did you shut down the server oddly?

**Comment by MotionlessTrain** [comment]
> I'd recommend having a starters guide in the mod, as well as another guide to bug fixes that would be within the game.

We have a starter guide on the wiki:
https://wiki.minecolonies.ldtteam.com/source/tutorials/getting-started

**Comment by MidnightRoseLight666** [comment]
> Did you place the builders hut otuside of the colony borders? or did it crash after placement or did you shut down the server oddly?

It didn't crash, and I didn't shut the server down odd i don't think? I used the normal way to leave a server 'esc' then 'leave server' to the server list screen. And I don't believe it was out of bounds? I wasn't that far from the town hall block.

**Comment by Raycoms** [comment]
try to mine and place it down again.

**Comment by MotionlessTrain** [comment]
Did you use the build tool to place down the building?

**Comment by Raycoms** [comment]
We would also need a log from the time of the first placement.

**Comment by MidnightRoseLight666** [comment]
I did try to use the build tool, but when using the build tool, nothing was appearing. It was just blank. All I could do was close it out.

**Comment by MidnightRoseLight666** [comment]
[2023-04-05-3.log.gz](https://github.com/ldtteam/minecolonies/files/11170511/2023-04-05-3.log.gz)
[2023-04-05-4.log.gz](https://github.com/ldtteam/minecolonies/files/11170512/2023-04-05-4.log.gz)
[latest.log](https://github.com/ldtteam/minecolonies/files/11170519/latest.log)

found the logs

**Comment by MotionlessTrain** [comment]
> I did try to use the build tool, but when using the build tool, nothing was appearing. It was just blank. All I could do was close it out.

You should be seeing a lot of icons at the bottom. If you click the middle one (called "fundamentals"), you should see a lot of buttons with one of them being the builder's hut

**Comment by Raycoms** [comment]
The issue is the custom style hut blueprint is missing
