### ISSUE TITLE
"Steps" for building make no sense

### ISSUE THREAD

**Issue by smmmadden** [ldtteam/minecolonies#9051]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19.2

### MineColonies Version

1.0.1331-ALPHA

### Structurize Version

1.0.472-BETA

### Related Mods and their Versions

Forge: 43.2.8
BlockUI: 0.0.64-ALPHA
Domum Ornamentum: 1.0.76-ALPHA

### Current Behavior

New build (for Level 1)
![image](https://user-images.githubusercontent.com/10309346/230256606-2247cc80-2238-4f56-9ad7-39a42de7799f.png)
Provided materials (for Level 1)
![image](https://user-images.githubusercontent.com/10309346/230256705-ecb8be06-5377-45d8-b542-272f1275b68c.png)

### Expected Behavior

If the Steps are supposed to reflect which level build is being done, then this has never worked (since I've been playing going back to 1.16.x).  I would expect that out of the 5 levels, level 1 should show Step 1/5, level 2 should show 2/5, etc.  The second screenshot is odd because it shows Step 0/6 for a 5 level build so I have no idea what this is for if not for levels.

Currently, Steps in the dialogs add zero value so either it should reflect which level is being done or remove altogether.

### Reproduction Steps

Place a building down
Go to builders hut
Review the required resources tab
Note the "Step 0/5" does not show what it should for numbers.

FYI: In case it matters, I'm building in Creative mode - rarely if ever now use Survival mode.

### Logs

https://pastebin.com/YZbTB5GY

### Anything else?

Unrelated but similar is the University Research UI never show the actual timer working.  It always shows zeros when asking to research a topic.  I would expect the count down to begin at that point but I never (literally) have seen this work. :-(

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
The steps aren't for levels, they are for the step, or stage, the builder AI is on at the time.
If you're in creative I wouldn't expect the research timer to show up either, as research is almost instant in creative, and doesn't take the times that it does in survival

**Comment by smmmadden** [comment]
even then it doesn't make sense.  I went from 0/5, then 0/6 and reopening UI it was back to 0/5 so even that didn't help much.  Just seems very inconsistent and doesn't tell me what level the building is at which to me, adds more value than what the builder stage is on.  For the research, it can be pretty quick when you get to level 3, 4 & 5, but the first two levels of research it does take a good 15-20 seconds each.

**Comment by Raycoms** [comment]
Steps are the builing steps. Something like clear, build, deco, remove water, etc
