### ISSUE TITLE
Citizen UI edit stats should not cover UI

### ISSUE THREAD

**Issue by smmmadden** [ldtteam/minecolonies#9052]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19.2

### MineColonies Version

1.0.1331-ALPHA

### Structurize Version

1.0.472-BETA

### Related Mods and their Versions

Forge: 43.2.8
BlockUI: 0.0.64-ALPHA
Domum Ornamentum: 1.0.76-ALPHA

### Current Behavior

![image](https://user-images.githubusercontent.com/10309346/230258533-73423a6f-3683-4cb9-872e-ef4f38665d31.png)

### Expected Behavior

remove the two images on the right and then move the + - buttons to the right of each text and have it always available next to each skill.  From a UX perspective, its a bad design to cover text up with other text when there is plenty of room to the right.  I've been designing UI's for applications for decades and this one always bothered me that I have to get my mouse just right to make it visible and then repeat it for every row.  From a usability perspective, always having the buttons there makes it much faster and simpler to click and edit.
All the skills could easily be added as well by removing the fancy squiggle under the name and remove the scrolling.

### Reproduction Steps

Open the citizen UI and try to edit the skills

### Logs

https://pastebin.com/YZbTB5GY

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
Where would you put those two images then?
The "+" and +-" buttons only appear in creative, so removing parts of the UI that are needed, to move something that isn't doesn't really make sense =)

**Comment by smmmadden** [comment]
good point - if in creative mode then they can go on the right side of the skills
One thing we are always doing is updating the skills as sometimes the skills just don't make much sense like a 1 for intelligence and teens or 20's  for everything else.

**Comment by Raycoms** [comment]
It's purely a debug tool though. So its not meant to be used for normal operation.
