### ISSUE TITLE
curarry is a mess

### ISSUE THREAD

**Issue by noone4242** [ldtteam/minecolonies#9053]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19.2

### MineColonies Version

1.19.2-1.0.1320-alpha

### Structurize Version

1.19.2-1.0.491-alpha

### Current Behavior

the quarry got stuck,  he dug down 5 levels and is now just breaking and replacing his pillar blocks.

![2023-04-06_10 05 22](https://user-images.githubusercontent.com/129317325/230405345-48e495a9-eeba-42a7-a2b5-da492d82d357.png)

### Expected Behavior

diggy diggy, and decluttering the build would be nice,  theres no reason for that many pilars or lanters.

### Reproduction Steps

no idea

### Logs

https://gist.github.com/noone4242/05ba5763156643661a8c56d849c101a1

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
Possible duplication of #8488 (which I asked to add the bug to)

I have the feeling that both issues are caused to DO blocks which have a different block state than the quarrier expects (due to block updates, or something like that)

**Comment by GroeneKnuppel** [comment]
i got the same problem aswell
my quarrier is just replacing it own framed cobble blocks without even making 1 layer

**Comment by Raycoms** [comment]
Duplicate
