### ISSUE TITLE
[BUG] <title> Guard AI issue

### ISSUE THREAD

**Issue by R1singPhoenix** [ldtteam/minecolonies#9054]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.19.4-1.0.1338-ALPHA

### Structurize Version

1.19.4-1.0.489-ALPHA

### Related Mods and their Versions

Forge: 1.19.4-45.0.39
Blockui: 1.19.4-0.0.73-ALPHA
Domum-ornamentum: 1.19.4-1.0.88 ALPHA
Multipiston 1.19.3-1.2.26 ALPHA

### Reproduction Steps

I was just running the game and whenever I added guards it came up with this message I've tried updating to the latest minecolonies and restarting minecraft.  I don't know if this is the same problem with archers or druids because I only have knights right now

### Logs

<script src="https://gist.github.com/R1singPhoenix/e1c380c314382fe39055f1cb03b425c0.js"></script>

### Anything else?

![IMG_0734](https://user-images.githubusercontent.com/130073607/230436367-6095556d-a0e9-4702-ae7d-37fd069e1d0a.jpg)

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Log doesnt contain the issue.

**Comment by Raycoms** [comment]
Stale, might have been fixed by one of our fixes
