### ISSUE TITLE
[BUG] Restaurant cannot choose fuel/food 

### ISSUE THREAD

**Issue by Ruane001** [ldtteam/minecolonies#9056]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19.3

### MineColonies Version

1.19.4-1.0.1342

### Structurize Version

1.19.4-1.0.489

### Related Mods and their Versions

Forge 45.0.29
blockuiu 1.19.4-0.0.73
Domum Ornamentum domum_ornamentum-1.19.4-1.0.88
Multi-Piston 1.19.3-1.2.26

### Current Behavior

On the Fuel and food tabs there is only the black square to type.  there is no list of items that can be chosen for use. ex. charcoal
Can't enter a fuel type so cook will constantly just ask for me to choose fuel. Even if given raw food and fuel, or cooked food they will not do anything.  will not feed people.

### Expected Behavior

Be able to select fuel types/food types.  Should fix the cook just standing there doing nothing

### Reproduction Steps

build restaurant
hire cook
check fuel tab
check food tab

### Logs

https://gist.github.com/Ruane001/c9dd4f9e43f1586e518eabdb8030d89d

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comme
![2023-04-06_14 50 22](https://user-images.githubusercontent.com/130080999/230480453-1869adcd-c8fe-455e-9b8f-eff72eebd596.png)
![2023-04-06_14 50 27](https://user-images.githubusercontent.com/130080999/230480457-1a8ad71f-eaef-47ad-9d84-eb6bb569ef58.png)
![2023-04-06_14 50 50](https://user-images.githubusercontent.com/130080999/230480459-47f764a1-71e1-4418-9a2e-7b813968d277.png)
nt if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Does restarting fix it?

**Comment by MotionlessTrain** [comment]
Are you perhaps playing on a LAN world?

**Comment by Knaxia** [comment]
I'd just like to add that I have also this issue with the same mod versions. 

I'm running with a personal dedicated server and the same happens if disconnected for a while. If I log in and it's empty, I have to disconnect and reconnect and it's fixed, until the next day that I reconnect, the same issue happens.

**Comment by Ruane001** [comment]
yes I'm running a dedicated server on my computer. thanks knaxi.  took a few times but the list finial showed up. Guess a bit of luck needed when reconnecting for it.

**Comment by Talyda** [comment]
Try logging in to a single player game before you log into the server (just a simple log in/log out) cos it sounds like an old bug that was fixed in 1.18/1.19.2 and that was the easiest temporary solution! No guarantees, but it does sound like the same thing!

**Comment by Raycoms** [comment]
Similar problem yes, because the way minecraft allows doing it in 1.19.4 is flimsy
