### ISSUE TITLE
[BUG] Smelter broken - only breaks 1 ore block then complains, in loop.

### ISSUE THREAD

**Issue by Knaxia** [ldtteam/minecolonies#9057]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19.3

### MineColonies Version

minecolonies-1.19.4-1.0.1342-ALPHA

### Structurize Version

structurize-1.19.4-1.0.489-ALPHA

### Related Mods and their Versions

1. forge-1.19.4-45.0.42
2. blockui-1.19.4-0.0.73-ALPHA
3. domum_ornamentum-1.19.4-1.0.88-ALPHA-universal
4. jei-1.19.4-forge-13.1.0.2
5. journeymap-1.19.4-5.9.5-forge
6. multipiston-1.19.3-1.2.26-ALPHA

### Current Behavior

-Smelter will break 1 ore block, then complain it has no ores, so will take the single raw ore it made and goes to smelt it. Once it's made an ingot, it will grab it, store it, call for pickup, then repeat.

If you turn off the raw ore smelting, to make him break down all the ores first this will happen:

-Smelter breaks down 1 ore block, then complains it needs ores, then stops complaining, complains again, stops, breaks one ore block, then complains... repeat forever.

-The inventory is full of ore blocks to break
-All ores are turned on in the smelter panel

### Expected Behavior

-Smelter will break down all the ores blocks
-Smelter will then take the raw ores and go smelt them in batch

### Reproduction Steps

1. Make smelter
2. Hire smelter
3. set fuel and give them some
4. Place stacks of ore block (not raw ores)
5. (Optional) Disable all the raw ore smelting in the smelter panel for 2nd behavior.

### Logs

[latest.log](https://github.com/ldtteam/minecolonies/files/11175901/latest.log)

### Anything else?

https://www.youtube.com/watch?v=2DAMFYtLeLQ

Here's a quick video of the behavior after raw ores have been turned off to only make him break the ore blocks first.

When I did a colony in 1.19.3, the smelter acted normally and not like this, it would break all the ores, then smelt the stacks after.

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Knaxia** [comment]
Update : It seems like it only affects Iron Ore block? I waited for him to finish the iron, and when he switched to copper, he no longer complains and seems to act normal.

**Comment by Knaxia** [comment]
I'd like to add it does the same to Lapis Lazuli Ore. did update to the Minecolonies 1344  but same issue still present.

Seems like I also often need to cancel his request for ores, even if there are many in the warehouse, for him to request it correctly from the courier.

**Comment by Sjduckrescuer** [comment]
I am having the same issue on an older version. MineColonies version 1.18.2-1.0.1337-ALPHA, in the modpack FTB Inferno. FTB inferno is on version 1.7.0

**Comment by Knaxia** [comment]
I just went to test in a new single player colony in creative, with all updated mods and nothing else, in case the issue was with the server / my world / my colony. Sadly it still does it, but seems to affect any ores, not just iron or lapis.

Using all pre-built buildings. Made town hall (1), starting colony, made builder (1), tavern (1), mine (3), university (1), house (5) did the research, made the smeltery (3), hired a worked ,raised their stats in the 30s, set fuel (charcoal), gave them 32 of each : iron ore block, gold ore block, coal ore block.

Same thing, they wait a little, break one ore, complain that they don't have ores, then stop, wait, break one, repeat.

Forge 1.19.4 - 45.0.43
blockui-1.19.4-0.0.73-ALPHA
domum_ornamentum-1.19.4-1.0.88-ALPHA-universal
jei-1.19.4-forge-13.1.0.2
journeymap-1.19.4-5.9.5-forge
minecolonies-1.19.4-1.0.1369-ALPHA
multipiston-1.19.3-1.2.26-ALPHA
structurize-1.19.4-1.0.489-ALPHA

Single player log to this point:
[latest.log](https://github.com/ldtteam/minecolonies/files/11290820/latest.log)
