### ISSUE TITLE
Infinite Server Crash - 1.10.2 + Sponge

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [ldtteam/minecolonies#906]
### Minecolonies version

https://minecraft.curseforge.com/projects/minecolonies/files/2414093

### Expected behavior
Should work

### Actual behaviour

https://gist.github.com/P3rf3ctXZer0/11c1908a40cc3af02e73c1144979f7de

### Steps to reproduce the problem

Don't know just reporting it I am a bit busy.

**Comment by Raycoms** [comment]
@xavier it seems to be the same problem here.


2017-04-30 17:18 GMT-03:00 P3rf3ct_Zer0 <notifications@github.com>:

**Comment by Auriel1** [comment]
Yep, not only server and not only 1.10

**Comment by Raycoms** [comment]
Yeah because we and that mod access the same folders which throws some
errors. Will fix it soon. No worries =)

2017-04-30 18:31 GMT-03:00 Auriel1 <notifications@github.com>:

**Comment by xavierh** [comment]
Fixed
