### ISSUE TITLE
[BUG] Inventory button has no text

### ISSUE THREAD

**Issue by kezmodius** [ldtteam/minecolonies#9066]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19.2

### MineColonies Version

1.0.1316-ALPHA

### Structurize Version

1.0.491-ALPHA

### Current Behavior

Huts' Inventory buttons no longer have text.
Ray asked on stream for someone to add the issue to github so he'd remember to fix it.
I looked to see if it was here but I did not see it.

### Expected Behavior

Inventory buttons used to have text

### Reproduction Steps

Look at hut inventory button
Look for the word "inventory"
It's gone

### Logs

Don't have one

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
Are you using a resource pack?

**Comment by Raycoms** [comment]
Cant reproduce, I believe some resource pack replaces the vanilla inventory text
