### ISSUE TITLE
Mechanic's Hut - Urban Birch - Perpetual Music??

### ISSUE THREAD

**Issue by smmmadden** [ldtteam/minecolonies#9069]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19.2

### MineColonies Version

1.0.1331-ALPHA

### Structurize Version

1.0.472-BETA

### Related Mods and their Versions

Forge: 43.2.8
BlockUI: 0.0.64-ALPHA
Domum Ornamentum: 1.0.76-ALPHA

### Current Behavior

Urban Birch - Mechanic's Hut has perpetual music.  Step on the plate and the music (notes) go on forever and never stop even after leaving the area or game.  The redstone is setup in a closed circuit and even replacing the pressure plate with lever or button it doesn't stop the notes from sounding off.  You have to break the redstone connection to stop it.
![image](https://user-images.githubusercontent.com/10309346/231332476-a1e1e311-c3e0-4583-b2d1-6eb9313982d2.png)
![image](https://user-images.githubusercontent.com/10309346/231332496-0b7801c9-bf7c-4d24-8ea9-a0d099954135.png)

### Expected Behavior

If the notes stay, put it on a timer so that it plays xx seconds and then stops until the next time the pressure plate is stepped on.
Or move the pressure plate to allow the music to play once then stop on depressure of plate.
![image](https://user-images.githubusercontent.com/10309346/231333266-327f66ad-71e9-4e04-b873-c1f9f66de1d1.png)

### Reproduction Steps

Get to level 5 and step on the plate.  Music will never stop

### Logs

https://pastebin.com/YZbTB5GY

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Is a #5006 but will be reworked soontm
