### ISSUE TITLE
[BUG] Missing translation interface for mod's quest text

### ISSUE THREAD

**Issue by mc-kaishixiaxue** [ldtteam/minecolonies#9080]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19.2

### MineColonies Version

1.0.1371-ALPHA

### Structurize Version

1.0.491-ALPHA

### Current Behavior

1.0.1371-ALPHA version adds some quests, but I can't translate them on Crowdin, because Crowdin doesn't have them.
I can only override them if I want to translate. There's no second way. Once the mod updated the newer version, I have to override them again, that's too inconvenience.

### Expected Behavior

I hope quest texts can be translated to other language on Crowdin. 

### Reproduction Steps

1. Open `minecolonies.jar` by 7z;
2. Open `data\minecolonies\quests` folders, I found some json files;
3. These texts are all English.

### Logs

Not crash

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Our current policy is that they are datapacks that can be translated "externally" and users can then download the translated datapacks. I think that is the easiest solution to this problem.
