### ISSUE TITLE
[BUG] Colonist My AI has run into an issue!

### ISSUE THREAD

**Issue by ghost** [ldtteam/minecolonies#9083]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.19.2-1.0.1371-ALPHA

### Structurize Version

1.19.2-1.0.491-ALPHA

### Related Mods and their Versions

1. Forge Version 43.2.0
2. Domum Ornamentum 1.19-1.0.83-ALPHA
3. Multi-Piston 1.19.2-1.2.25-ALPHA
4. Other Mods
![Other Mods](https://user-images.githubusercontent.com/131329041/233253204-fe8e3a89-63b2-48e1-af5f-f9d93adba66c.png)

### Reproduction Steps

1. Absolutely nothing
2. Let time pass
3. Drink water
4. "My My AI has run into an issue!"

### Logs

https://gist.github.com/Aivcyon/088990a3e522df15d7f406561b9658f8

### Anything else?

![2023-04-19_22 55 30](https://user-images.githubusercontent.com/131329041/233254402-04a2f5b8-3b6b-4519-88df-3f4825f72039.png)
![2023-04-19_22 56 05](https://user-images.githubusercontent.com/131329041/233254407-1d999f53-165e-4daf-988c-4adb19b1af3a.png)
Both my courier & forester are experiencing this however they both do there job fine.

**Comment by MotionlessTrain** [comment]
Canary seems to give this issue

**Comment by Raycoms** [comment]
What is canary and why does it interfere with our racks?

**Comment by MotionlessTrain** [comment]
Canary is a general-purpose optimization mod and unofficial fork of the Fabric mod Lithium for Minecraft Forge, according to its Curseforge page

**Comment by Raycoms** [comment]
Ahk. Closed, report to Canary.
