### ISSUE TITLE
[BUG] Console spam

### ISSUE THREAD

**Issue by kezmodius** [ldtteam/minecolonies#9084]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.0.1371-ALPHA

### Structurize Version

1.0.491-ALPHA

### Related Mods and their Versions

Forge - 43.2.8
blockui-1.19-0.0.64-ALPHA
multipiston-1.19.2-1.2.21-ALPHA

Console for my server is spamming Minecolonies issues. I was not on the server at the time, so cannot say what players were doing. 
When I did log on and spend time in my colony the spam was not happening in the console.

### Reproduction Steps

I don't know why or how it happened but it happened for hours, mostly when one player was on.

### Logs

https://gist.github.com/kezmodius/91e2f91610a1d4a7180c6dc96854c8a5

### Anything else?

This is the first time this has happened. I updated the server yesterday.

**Comment by kezmodius** [comment]
I forgot to add you need to look at the whole file as it is large and the Minecolonies errors were happening at the end of the file.

**Comment by Raycoms** [comment]
hotfix pushed
