### ISSUE TITLE
[BUG] Raiders spawning inside colony farm

### ISSUE THREAD

**Issue by Konclan** [ldtteam/minecolonies#9094]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19.2

### MineColonies Version

1.0.1351

### Structurize Version

1.0.472

### Current Behavior

Raiders are currently spawning inside my farm plots instantly killing my farmers before they can even run away,
![2023-04-23_22 15 20](https://user-images.githubusercontent.com/16567080/233893720-5e80d6fb-5ec0-407a-bcb6-22a71e822f43.png)
![2023-04-23_22 15 23](https://user-images.githubusercontent.com/16567080/233893722-57c34e00-8e21-4369-9ad9-efc2bb623893.png)
![2023-04-23_22 28 40](https://user-images.githubusercontent.com/16567080/233893769-42f47d4d-8b8a-4f69-9843-7c24e1383b76.png)

### Expected Behavior

Raiders should not be able to spawn in farms

### Reproduction Steps

Build a big colony I guess idk

### Logs

https://pastebin.com/b7kjfPQf

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Not actually a bug, whats protects you are guardtowers. Place a guardtower in that corner and youll be fine.
