### ISSUE TITLE
[BUG] 1.19.2 Quest Bugs

### ISSUE THREAD

**Issue by freevortex** [ldtteam/minecolonies#9095]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19.2

### MineColonies Version

1.19.2-1.0.1378-ALPHA

### Structurize Version

1.19.2-1.0.491-ALPHA

### Related Mods and their Versions

1. Forge Version 43.2.8
2. BlockUI Version 0.0.69-ALPHA
3. Domum Ornamentum Version 1.0.83-ALPHA

### Current Behavior

When I complete a quest from a guard (e.g., hand them an apple), instead of completing the quest, it then tells me "I'm still waiting for you to mine %s dirt!". Additionally, I have a quest from a guard to kill 10 skeletons, but when I talk to him, he says "I'm still waiting for you to kill %s skeletons!"

When I complete a quest from a non-guard, I get the message "You have successfully completed the quest:translation={key='QUESTNAME', args=[]}

git issue requested by motionlesstrain via discord

### Expected Behavior

No issues with quests

### Reproduction Steps

1. Have the aforementioned versions of each mod
2. Try to complete a quest

### Logs

https://pastebin.com/w0nG8v2R

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Not a bug, this is a tempalte quest that shouldnt show up. It has a bunch of unrelated objectives. I fixed this recently but when it once got triggered in a world it would stay around.
