### ISSUE TITLE
[BUG] Repeated Resolver & Request Retrieving

### ISSUE THREAD

**Issue by OnioTheSeal** [ldtteam/minecolonies#9097]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19.2

### MineColonies Version

1.0.1378-ALPHA

### Structurize Version

1.0.491-ALPHA

### Related Mods and their Versions

Forge Version: 43.2.1

### Current Behavior

Minecolonies is seemingly attempting to perform many actions in a single millisecond repeatedly causing the server to continually increase time per tick as it times out.

### Expected Behavior

Minecolonies resolves its requests once and less frequently.

### Reproduction Steps

Unknown cause.
Of note, the issue does not start until a player enters an area with minecolonies colonists, even when the areas are previously force-chunkloaded by the server (using FTBChunks). Leaving the area does not cause the problem to cease.
Restarting the server does prevent the error until someone triggers it again.

### Logs

https://gist.github.com/OnioTheSeal/0dd4cf15363b6570f3916d9b70394bda

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by kezmodius** [comment]
I have the same issue. My debug log is over 100mb for 17 minutes. I crashed my gist trying to load it so I have grabbed a sample for you to look at here. Can give you access to more if need be.
https://gist.github.com/kezmodius/5a90e457692085ddd9e84fe5d073a083

**Comment by OnioTheSeal** [comment]
Currently I am running a command block every so often to perform the /mc colony requestsystem-reset-all command, which has helped to keep the lag from crashing the server so far, but does not fix the issue at hand.

**Comment by Raycoms** [comment]
Can we have a spark report instead of this? The log is okay.

**Comment by OnioTheSeal** [comment]
Updated the server to the latest Alpha to try and fix this error, however the error persists.
Installed Spark and will be attempting to get a better log for this issue as it is not yet completed.

**Comment by Raycoms** [comment]
Make sure debug logging is not turned on int he config

**Comment by Raycoms** [comment]
in the common config.

**Comment by OnioTheSeal** [comment]
Had debug logging on when figuring out the issue earlier- oops!
Now that it is off, the issue seems to be fixed.

**Comment by Raycoms** [comment]
debug logging can take considerable performance.

**Comment by OnioTheSeal** [comment]
Yeah. Originally it was set to false, though, but now the config works as intended.
