### ISSUE TITLE
colonists moving around on their backs and game freezing when using rally banner

### ISSUE THREAD

**Issue by Roses4664** [ldtteam/minecolonies#9098]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19.4

### MineColonies Version

1.19.4- 1.0.1360-ALPHA

### Structurize Version

1.19.4-1.0.489-ALPHA

### Related Mods and their Versions

forge-1.19.4-45.0.49-
blockui-1.19.4-0.0.73-ALPHA
domum_ornamentum-1.19.4-1.0.88-ALPHA
multipiston-1.19.3-1.2.26-ALPHA

### Current Behavior

Colonists moving around on their backs.
When using the rally banner, once the guards have arrived and I attempt to move among them the game freezes.
Once a guard has been hired, it only requests the weapon, everything else is requested much later.
![2023-04-24_17 09 33](https://user-images.githubusercontent.com/85271827/234129625-1ebf37df-e828-46ac-8a3e-cf2eb67f4ce2.png)
![2023-04-24_17 09 34](https://user-images.githubusercontent.com/85271827/234129648-c93b6382-b2b3-43f1-9702-932300088a30.png)

### Expected Behavior

I expect colonists to walk upright, the game not to freeze for any reason, and when using creative i expect to be able to equip the gaurds.

### Reproduction Steps

The colonist's on their backs is totally random.
use the banner to rally the guards, once they arrive attempt to move around among them clicking on them to equip them with armor.
 Hire a guard, click on the guard, wait, fulfil weapon, The druid won't request anything at all for quite some time, the guards won't request armor or shields for a long time either.
 When I say quite some time, I mean like 10 minutes. 
[debug-1.log.gz](https://github.com/ldtteam/minecolonies/files/11315115/debug-1.log.gz)

### Logs

not smart enough to do this

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
I am a bit confused, is the colonists on their backs related to the rallying banner?

The other things are correct. Guards are supposed to be equipped long before rallying them.

**Comment by Roses4664** [comment]
The rally has nothing to do with them being on their backs, it's a separate issue. My apologies for confusing you.
 I Rallied them so I could equip them since i was unable to once they were hired initially (im playing in creative mode).
 I decided since i couldn't equip them until later, i would just get the hiring done and rally them all later to equip them all at once.




Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Raycoms** [comment]
Just drop off the gears at their stations

**Comment by Roses4664** [comment]
Rallying them and them moving among them and clicking on tuem on causes the game to freeze. The only remedy then is to shut down the game with task killer.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Raycoms** [comment]
Did you try giving it more RAM? 2gb is a bit little

**Comment by Roses4664** [comment]
We changed it to 8 since 2 is ridiculous little for a 1T comp. Im not sure why it's telling its only 2. I have an IT I'll ask him tomorrow.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by uecasm** [comment]
Colonists moving around while lying down was in previous versions a fairly common sign of using Optifine or another mod that messed with entity activation.  So remove those.

**Comment by MotionlessTrain** [comment]
I have it seen once as well. They were sick citizens, which were in bed while I logged off and logged back on. It looked like they were thinking they were still sleeping, despite being out of bed and moving around near their house and worker hut
(I'm not using any performance mods at all, or anything with regard to entity activation)

Once they were cured, they stood up again and started working as usual

**Comment by Roses4664** [comment]
I don't have optifine or performance mods.
 Rebooting doesn't get colonists off their backs, they're not sick either, Or the ones I've seen weren't, they could have been at start up of the game.
  I can recognize my comp could be the issue with freezing and will work on it when I get home.
 Thank you all for your help with this issue.
 I apologize for the confusion.



Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
