### ISSUE TITLE
Unable to progress in 'Builder's Quest'

### ISSUE THREAD

**Issue by KiritoProjects** [ldtteam/minecolonies#9100]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19.2

### MineColonies Version

1.19.2-1.0.1377-BETA

### Structurize Version

1.19.2-1.0.491-ALPHA

### Related Mods and their Versions

Forge Version: forge-1.19.2-43.1.47
BlockUI Version: 1.19-0.0.64-ALPHA
Domum Ornamentum Version: 1.19-1.0.76-ALPHA-universal

### Current Behavior

Builder gives a quest Asking for Builder's Goggles, I created one and wen't back to the Builder to give it to them.
The Builder keeps repeating that they are looking for Goggles even though i have some in my inventory.
I clicked on the "I don't have any of it!" button since it was stuck in a repeating loop of asking for said Goggles.
After a while they started to ask for said Goggles again where i tried to give the ones made previously with no progress.
I made another pair of said Goggles thinking that would solve this issue, But seems i was darn unlucky.

### Expected Behavior

Quest completed when either having said goggles in your inventory or placed in theirs.

### Reproduction Steps

Wait for the quest marker to appear above the builders head.
Go to the builder and see if they are asking for "Builder's Goggles".
Create said Goggles and talk to the builder.

### Logs

N/A doesn't say anything in the log/console about that

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by LeonScholta** [comment]
Same here

**Comment by Thodor12** [comment]
I tried this myself yesterday and it worked fine, have you equipped the goggles yourself by any chance prior to handing them in?
If at all, try updating to a newer version.

**Comment by Raycoms** [comment]
Are they slightly damaged?

**Comment by LeonScholta** [comment]
No, I tested 2 and both had max durability (Official Minecolonies Modpack v1.18)

**Comment by MotionlessTrain** [comment]
Then it is likely another mod adding NBT data to it (I know Spoorn has done so in the past)
You may need to do any of the following things:
- Teach the corresponding crafter the builder's goggles
- Use some other crafting mechanic that doesn't require you to carry the item, or
- Craft and drop the item close enough to the builder, without ever holding it yourself

**Comment by uecasm** [comment]
I don't think those workarounds will work, since the quest wants the item in the player's inventory.  You'd have to disable whatever mod or setting is adding data.
