### ISSUE TITLE
[BUG] Incorrect visibility of priority display in Builder's hut [Ru]

### ISSUE THREAD

**Issue by McOway** [ldtteam/minecolonies#9104]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19.2

### MineColonies Version

1.19.2-1.0.1341-ALPHA

### Structurize Version

structurize-1.19.2-1.0.472-beta

### Related Mods and their Versions

I think you can find this Bug on all working versions of Mine Colonies 1.19.2 ¯\_(ツ)_/¯

### Current Behavior

When translating the mod into Russian in the builder's hut, the priority display for the courier disappears

### Expected Behavior

Please, make the interface in the builder's hut visible in Russian translation! ヾ(•ω•`)o

### Reproduction Steps

1. On English version you can see everithing correct
2. Just enter the game with Russian language
3. Have Bug with priority display, enjoy :) (not funny)

### Logs

. _ .

### Anything else?

![2023-04-25_23 37 31](https://user-images.githubusercontent.com/131817328/234401322-2bf6703e-10d7-40c6-a88a-87438d8078c8.png)
(Special thanks for working on the mod, it has changed a lot! (last year for sure) With love from Russia!)

**Comment by Raycoms** [comment]
Thats a problem with the russian translation at translate.minecolonies.com you can fix that there as well
