### ISSUE TITLE
[BUG] Project Expansion and Minecolonies Food-related Crash to Desktop

### ISSUE THREAD

**Issue by CopperBoltwire** [ldtteam/minecolonies#9108]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19.2

### MineColonies Version

1.0.1382a

### Structurize Version

1.0.491a

### Related Mods and their Versions

1. Project E (Not at fault, needed by Project Expansion)
    ProjectE-1.19.2-PE1.0.1B
2. Project Expansion (Culprit / Trigger)
    ProjectExpansion-1.19.2-1.0.8

### Current Behavior

Upon loading or creating a new SP world, it crashes back to Desktop.

If a world already exists, it takes me to the world select menu just fine, from there, I can do above.

Game works fine in 1356, but not in 1361+

### Expected Behavior

Play the game as normal; being able to load my worlds or create new worlds.

Game works fine in 1356, but not in 1361+

### Reproduction Steps

Quick & easy:
Create empty 1.19.2 modpack with Forge 43.2.8 (via ATLauncher - Not that launcher matters...)
(You can make a new pack with the "Vanilla packs" menu.)
Now go to Instances and select "Add mods" or via "Edit mods", then "Browse".
Add Project E and Project Expansion.
Add MineColonies v1.0.1361 or greater.
Start instance and watch as it crashes.
Update/replace/reinstall (via edit mods) MineColonies to v1.0.56 and it works just fine.
What ever you guys did in 1361, now breaks the game.

Tests was done with every available version from 1351 to 1382, crashes start at 1361

### Logs

https://pastebin.com/ttZPCHtX

### Anything else?

Here is the Crash log: https://pastebin.com/xyQSiCDP
I added the mod "Ding" mod just to help me know when the darn thing loads, even with this few mods, the game takes ages to load.
It was not that important to add to the list above. ( think...)

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by CopperBoltwire** [comment]
Reminder: the problem starts at v1361, not just the latest version.
All versions was tested since 1351.
Here is the suspected item that might be the culprit for the crashing, from Project Expansion: https://imgur.com/a/rNvaNeA

**Comment by MotionlessTrain** [comment]
The issue seems to be right around here in ItemStackUtils (which was a change when quests got introduced):

https://github.com/ldtteam/minecolonies/blob/6633aa5fce4e4379710fca94dccb9229e5734028/src/api/java/com/minecolonies/api/util/ItemStackUtils.java#L87-L91

One of the `getFoodProperties` method calls never got changed to include the arguments

**Comment by CopperBoltwire** [comment]
So it might just be a very simple fix?
A typo?

**Comment by Raycoms** [comment]
just needs two more properties to be added

**Comment by CopperBoltwire** [comment]
Woohoo, quick fix incoming - Looking forward to the next patch :D

**Comment by Raycoms** [comment]
hotfixed
