### ISSUE TITLE
[BUG] Missing texture - Gotta love the black/purple placeholder texture, makes blck text unreadable

### ISSUE THREAD

**Issue by CopperBoltwire** [ldtteam/minecolonies#9112]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19.2

### MineColonies Version

1.0.1390a

### Structurize Version

1.0.491a

### Current Behavior

A texture is missing - 
![2023-04-29_02 11 04](https://user-images.githubusercontent.com/39056633/235273223-31fc9326-a431-4492-8822-3c4d454f4747.png)
This missing texture shows when trying to manually place a build-block like, say, the builder's Hut.
It also shows (Or rather, it's missing) when asking to see more details on some places that shows similar screen.

### Expected Behavior

That it used the texture required for that pop-up menu thing.
Sorry, i don't even know what one would call that window...

I assume it's just a typo somewhere...

### Reproduction Steps

Try to manually place (with 1390a) any of the buildings... I don't know what to call the menu, so i can't explain it better.
Try manually placing the Builder's Hut.

### Logs

https://pastebin.com/CMzYbNCd

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Shadizar** [comment]
+1...same minecolonies and dependencies...updated and get this ui now also. I think mine was talking to my forester about missing tools? Could be wrong about that part though

**Comment by CopperBoltwire** [comment]
YEah, when ever you try to get more info on what a profession person requests, like, lets say they want a shovel, and you click on the more information button, you get similar menu with missing texture x.x
