### ISSUE TITLE
[BUG] Farmer eats empty bottles when making mud

### ISSUE THREAD

**Issue by Shadizar** [ldtteam/minecolonies#9119]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19.2

### MineColonies Version

1.0.1390-ALPHA

### Structurize Version

1.0.491-ALPHA

### Current Behavior

When I supply X water bottles to the farmer to craft X mud blocks, they consume all but 2 bottles fully (returning 2 empty bottles and no others). I checked the hut inventory and racks of the farm, the personal inventory of the farmer and all couriers, and the inventory of the warehouse. I also requested bottles at a postbox, and the clipboard showed Player as supplier for them (I used about 1/2 X as the requested quantity)

### Expected Behavior

Return X empty bottles.

### Reproduction Steps

Start a build that requires X mud blocks, with 0 mud blocks in the colony inventories (and 0 empty bottles/water bottles for testing purposes.
Teach the farmer the mud recipe (1 dirt/1 water bottle)
Place the X water bottles in the farmer inventory
When crafting is completed, search the colony thoroughly for empty water bottles

### Logs

N/A

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
It looks like the mud recipe has been implemented the same way as the level 3+ bread recipe for the baker:
The amount of glass bottles returned is based on the skill of the farmer (or baker, in case of the bread), it seems like.
They have a very low chance to return a glass bottle at low stats, and almost guaranteed at very high stats

**Comment by Shadizar** [comment]
seems quite harsh...and odd given that player return is 100%
Why would anyone then want the farmer to make mud? Glass is a big hassle compared to just doing it yourself.
My return was ~ 10% of the bottles coming back (L1 or 2 farmer)

**Comment by Raycoms** [comment]
I guess that is fine then. Its okay to have a trade-off to automation. Especially as higher level workers will properly compensate then.

**Comment by uecasm** [comment]
The fisher will produce free water bottles.  Slightly less as they level up, but by that time you've probably set up a glassmaker (and the farmer will be less careless).
