### ISSUE TITLE
[BUG] Config file option to shut up the colonists doesn't work

### ISSUE THREAD

**Issue by Shadizar** [ldtteam/minecolonies#9121]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19.2

### MineColonies Version

1.0.1390-ALPHA

### Structurize Version

1.0.491-ALPHA

### Current Behavior

Colonists talk

### Expected Behavior

Colonists to not talk

### Reproduction Steps

Open client config file (<instancefolder>\config\minecolonies-client.toml) when client is not running

edit segment as follows 
	#minecolonies.config.enablecitizenvoices.comment [Default: true]
	enablecitizenvoices = false

Save and exit and start playing on server.

### Logs

N/A

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Odd, I just tested this and it worked fine. Just didnt work when changing it mid run.

**Comment by Shadizar** [comment]
I can update to today's alpha and retry, I guess...they are still chattering away 

It is a client only setting, I assume, from the file name/location, correct?

**Comment by Raycoms** [comment]
yes

**Comment by Shadizar** [comment]
I believe that it might now be the case that they don't idle-chatter,
 But they still talk when right-clicked (which seems a bug since the config is to disable voices not 'disable idle voices'?

**Comment by Shadizar** [comment]
Nope
I still hear some "good day to you" when they walk near me when they're going to their homes at night etc.
Forge 43.2.8
minecolonies-1.19.2-1.0.1405-ALPHA.jar

**Comment by Raycoms** [comment]
Okay, I double checked this even in smp, in a pack with only minecolonies and only on the server.
Something else must be interfering causing this or its on an old forge.

**Comment by Shadizar** [comment]
Not sure how anything else could interfere with this, should be entirely minecolonies internal logic? And I have 43.2.8, IIRC only 43.2.10 is as far as it goes in 1.19.2

**Comment by Raycoms** [comment]
Im not sure either. But I tested it in a normal world environment and smp just with minecolonies + dependencies and it worked 100%

**Comment by Shadizar** [comment]
Did you change the value also on the server side? I did not try that because of two reasons (1, I assume it should only be needed client side only since it is a client config file per the name, and 2, other players might want the voices)

**Comment by Raycoms** [comment]
No, didnt change anything

**Comment by Shadizar** [comment]
still happens for me in the existing world (server)
creating a new singleplayer they're silent

I'm wondering if maybe the change won't take effect in existing playthroughs only new colonies? Or maybe only new colonists? Just a thought, maybe they don't 'refresh'. 
I saw another person mention it on the discord hence adding a comment as a note
