### ISSUE TITLE
[BUG] Resturant AI issue

### ISSUE THREAD

**Issue by CopperBoltwire** [ldtteam/minecolonies#9123]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19.2

### MineColonies Version

1.0.1392a

### Structurize Version

1.0.491a

### Current Behavior

![2023-05-06_00 18 35](https://user-images.githubusercontent.com/39056633/236578029-90d14706-ba98-4063-937a-c24857794174.png)
Was told to do so, so here ya go... 

### Expected Behavior

Saw he was complaining, came to see what was his issue...
Apparently i gotta share the issue and latest.log, so here ya go... 

### Reproduction Steps

Sorry, but i don't actually, i know it's not helpful... hope the "Latest.log" can help...

### Logs

https://pastebin.com/uNqCF9v1

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
fix pushed
