### ISSUE TITLE
[BUG] Crash when joining server or on server startup

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [ldtteam/minecolonies#9131]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19.2

### MineColonies Version

 minecolonies-1.19.2-1.0.1405-ALPHA.jar

### Structurize Version

 structurize-1.19.2-1.0.491-ALPHA.jar

### Related Mods and their Versions

https://legacy.curseforge.com/minecraft/modpacks/fiction-friction-pixelmon/files/4527780

### Current Behavior

When users try and join my modpack now a strange issue started occurring where there is a ticking entity issue with Minecolonies ... I actually have no idea what I am reporting I was told it was important though.

### Expected Behavior

No crash

### Reproduction Steps

Unsure

### Logs

https://pastebin.com/3ZpdRRyq

### Anything else?

I was informed by Shindria and Motionless it was a good idea to report this ... I think the bug has something to do with skins loading and apotheosis but I am honestly unsure.

### Additional Information
* Falling back to ``minecolonies-1.19.2-1.0.1392-ALPHA.jar`` seems to fix it. However it re-introduces multiple bugs relating to rendering ... maybe something is catching on render thread in future versions?

**Comment by Raycoms** [comment]
Could I get the latest log?

**Comment by P3rf3ctXZer0** [comment]
I deleted that work space. Ask me later and I might set it back up.

* Newest Client Crash Log https://gist.github.com/P3rf3ctXZer0/bc5de6d0c91735971e2ca877986f984d
* Newest Client Debug Log https://gist.github.com/P3rf3ctXZer0/9460384a572840dd15ac9b0c01297c04
* Newest Client Latest Log https://gist.github.com/P3rf3ctXZer0/68daa46972065d668d88e328d06a666e
* Bonus Server Log https://gist.github.com/P3rf3ctXZer0/c319a28b80fae574d599e9642d777beb

This was caused by a connected issue surprisingly
https://github.com/embeddedt/ModernFix/issues/84#event-9191324254

**Comment by P3rf3ctXZer0** [comment]
Strange crash issue.
https://gist.github.com/P3rf3ctXZer0/9466a45894ba9e2bf48ffcc41569a646

**Comment by Raycoms** [comment]
Please make a new issue with the latest log etc as well then. Somehow your colonies failed to load properly. So something before that mustve prevented them from ticking.
