### ISSUE TITLE
[BUG] Huts are changing Settings on their own (for sure, forester and farmer)

### ISSUE THREAD

**Issue by Shadizar** [ldtteam/minecolonies#9132]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19.2

### MineColonies Version

1.0.1405-ALPHA

### Structurize Version

1.0.491-ALPHA

### Current Behavior

I had my farmer set to request fertilizer:off, and my forester to zoning mode:on (with zone set and working for many days IRL time), and shears:off

I found my forester changed their settings to zoning mode:off and shears:on (and therefore started messing up all sorts of trees I did not want them changing), and farm changed to fertilizer:on

As a note, my builders did keep Hilbert and did not revert to default.

### Expected Behavior

Settings must not change unless I do the changing.

### Reproduction Steps

farmer set to request fertilizer:off

forester to zoning mode:on (with zone set and working for many days IRL time), and shears:off

Updated to the alpha 1.0.1405-ALPHA from 1.0.1392-ALPHA

Restarting workers does not help. Restarting server and client does not help.

### Logs

https://gist.github.com/Shadizar/d6f72f21f8cb5a1431bf73f97e775cce

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Did you restart the server inbetween or have a crash?

**Comment by Shadizar** [comment]
There was no crashing. Obv. had to restart the server when I updated the mod, but then I spotted the bad settings, and fixed them and watched them a bit (stayed same it seemed while playing.)
But then overnight my server had a scheduled restart so maybe server restart borks it, unsure

**Comment by Raycoms** [comment]
Server restart may sometimes bork it if the restart is quite close (within like 10 minutes or so depending on lag)

**Comment by Shadizar** [comment]
no, server restart was hours after changing the settings
and, it wasn't happening with server restarts in 1.0.1392-ALPHA

**Comment by Raycoms** [comment]
Odd, is this still happening?

**Comment by Raycoms** [comment]
Like, can you reproduce this consistently?

**Comment by Shadizar** [comment]
Yep
Just rebooted server to test it for you, and settings are again borked (after having been fine for hours)

**Comment by Shadizar** [comment]
confirmed fixed on latest alpha; thanks so much, I can unleash the forester again :D
