### ISSUE TITLE
[BUG] <building tool Glitches my vision>

### ISSUE THREAD

**Issue by xRediFox** [ldtteam/minecolonies#9138]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19.4

### MineColonies Version

minecolonies-1.19.4-1.0.1411-ALPHA.jar

### Structurize Version

structurize-1.19.4-1.0.489-ALPHA.jar

### Related Mods and their Versions

1 forge 1.19.4 (45.0.59)
2 BlockUI blockui-1.19.4-0.0.73-ALPHA.jar
3 Domum Ornamentum domum_ornamentum-1.19.4-1.0.88-ALPHA-universal.jar
4 Stylecolonies  1.0.2
5 multipiston-1.19.3-1.2.26-ALPHA.jar

### Current Behavior

Every single time i want to build something by using the build tool it glitches my vision so that i see from 2 different angles at once and it doesn't dissapear till i completly turn off minecraft 

### Expected Behavior

i expect to not be forced to restart my game everytime i want to build something from the mod

### Reproduction Steps

1. craft Build Tool
2. Use Build tool
3. Build whatever 

### Logs

https://gist.github.com/xRediFox/3a71eab8aeaa5974850e1e930f013f01

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.
![Screenshot_6](https://github.com/ldtteam/minecolonies/assets/133499805/51f62481-4e69-4882-94cb-8c0121c83e5c)

**Comment by Talyda** [comment]
Optifine. Try without.

**Comment by RailedGaming** [comment]
I had this same issue, However I found that the issue for me had to do with my shaders pack, Optifine is still installed and working fine with everything.
