### ISSUE TITLE
[Question] builderinfiniteresources = true

### ISSUE THREAD

**Issue by KORorc** [ldtteam/minecolonies#9139]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19.2

### MineColonies Version

1.0.1413-ALPHA

### Structurize Version

1.0.491-ALPHA

### Related Mods and their Versions

forge 43.2.0

### Current Behavior

I use a Google translator because I can't speak English... sorry...
i like singleplayer. One day, i found
https://github.com/ldtteam/minecolonies/issues/4267

but

\serverconfig\minecolonies-server.toml
(builderinfiniteresources =true/false) does not exist

where are the options..
Is it a missing option?

### Expected Behavior

builderinfiniteresources = true

Builder creates a building without resources

### Reproduction Steps

1.create a new world
2.Go to the config folder \serverconfig\
3.Can't find option

### Logs

I don't know programming, so I don't know logs....

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
It no longer exists. Was a debug option, which was actually very buggy =P

**Comment by KORorc** [comment]
답변 감사합니다 
Thank you for answer
