### ISSUE TITLE
[BUG] Forester hut zone

### ISSUE THREAD

**Issue by DomitillePottier** [ldtteam/minecolonies#9147]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19.2

### MineColonies Version

minecolonies-1.19.2-1.0.1420-ALPHA

### Structurize Version

structurize-1.19.2-1.0.491-ALPHA

### Current Behavior

I'm trying to change my forester's zone with the forest tool. However, each time I select a new zone (select 2 corners with left and right click), nothing happens and my forest hut keep be associated with the previous zone.

This is the chat when I use the forest tool (one click on corner A, one on corner B)
![image](https://github.com/ldtteam/minecolonies/assets/55233473/0906cbed-b17d-4ed0-b9a6-ef524594f9b9)

I also tried to change the mode of the forester to automatic and then return to zoning mode, but it doesn't change anything.

The visual zone appear during the selection, but if I request a new tool then the visual zone is on the old zone. My forester keep work in the old zone.

### Expected Behavior

Set a new zone for the forester hut by using the forest tool

### Reproduction Steps

1. Have a forester hut with a defined zone.
2. Set a new zone with the forest tool.

### Logs

https://gist.github.com/DomitillePottier/a1e09eea46a3cc95b560de476303697f

### Anything else?

I don't try in solo or by constructing a new forester hut. 
I'm on Littleton theme.

**Comment by BlackWarrior2004** [comment]
Same kind of thing happening to me, my colony is new, so I didn`t have a previous zone, so the zoning mode option automatically turns to "off", even if I use the zoning tool and turn zoning mode to on

**Comment by uecasm** [comment]
Ok, confirmed.  This works fine in singleplayer but is broken in multiplayer.  Looking at it now.
