### ISSUE TITLE
[BUG] Soldiers dont get cured in hospital

### ISSUE THREAD

**Issue by Simanova86** [ldtteam/minecolonies#9148]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19.2

### MineColonies Version

1.0.1410-ALPHA

### Structurize Version

1.0.491-ALPHA

### Related Mods and their Versions

Direwolf Pack v1.11.0

### Current Behavior

Soldiers dont get cured from any disease
doest matter is soldier if stationed in barracks or guard tower

fire the soldier and the npc gets cured properly

### Expected Behavior

Every colonist should be cured by hospital?

### Reproduction Steps

1. Check game and mod version
2. Assign a soldier to barracks or guard tower
3. Wait until he/she is sick (any disease)
4. Soldier wont get cured

### Logs

https://gist.github.com/Simanova86/81a9cc0526151f6e35beecd2229abd6a

### Anything else?

Bug was maybe introduced in the last weeks.
I also checked that the hospital is reachable, has "medicine" and it is daytime of course.

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Do you mean, they dont go to the hospital, or do you mean, they dont get cured at the hospital when they go?

**Comment by Simanova86** [comment]
> Do you mean, they dont go to the hospital, or do you mean, they dont get cured at the hospital when they go?

In my case, they dont go to the hospital. 

in all cases the guards are starving and got bubbles around them.
in some cases i disturbed their sleep, while awake.

![grafik](https://github.com/ldtteam/minecolonies/assets/126411918/7efcbf54-e430-493d-867c-54f8071034db)
![grafik](https://github.com/ldtteam/minecolonies/assets/126411918/2e4d2ad4-f296-43ff-b639-4e7262f22e63)
![grafik](https://github.com/ldtteam/minecolonies/assets/126411918/faaa4710-6a07-4005-893d-d5b606fc2faf)
![grafik](https://github.com/ldtteam/minecolonies/assets/126411918/8a4f46ae-e5e3-4857-acc0-588947e27bda)

**Comment by Raycoms** [comment]
I assigned someaddons to this because his AI readjustments will solve this
