### ISSUE TITLE
[BUG] Shepherd stop shearing 

### ISSUE THREAD

**Issue by iubx** [ldtteam/minecolonies#9151]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.19.2-1.0.1410-ALPHA

### Structurize Version

1.19.2-1.0.491-ALPHA

### Related Mods and their Versions

Blockui: 1.19-0.0.69-ALPHA
Domum_ornamentum: 1.19-1.0.83-ALPHA-universal

### Current Behavior

My shepherd would eventually stop shearing wool. Restarting my worker or changing the shearing option to off then on again wont fix it. I have to hire a new worker to have shearing work again. 

### Expected Behavior

The shepherd should always shear wool

### Reproduction Steps

One thing i've noticed is that through all the sheperds i've hired, they would stop shearing once they reach Focus 13 and up.

### Logs

https://gist.github.com/iubx/1325af24b786ef25a2e4d823f47e0761

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by iubx** [comment]
My friend (server owned) did some tests. So whenever the bug happen, if we turn off breeding and feeding, the shepherd will restart shearing. We turn back the breeding, it will stop.
We hired a new shepherd, boost the focus to 13 and it would work properly, so we dont think it's related to that stat.
We rehired prior shepherds (those that stopped shearing) and yet again, we were able to force the shearing my disabling breeding and feeding, but once we turn back the breeding, they would stop shearing

**Comment by Simanova86** [comment]
from my experience the shepherd shear only when breeding and feeding is disabled. 
with breeding an feeding on, sheeps getting killed drop meat only.

**Comment by uecasm** [comment]
It is currently intended that the shepherd does shearing last amongst all their other priorities.  This doesn't mean you need to turn the others off, but they will feed, breed, and kill all that they can before they start looking for sheep to shear.

There were some recent changes (specifically, 1426+) that should help with this, by reducing cases where they can try to breed more frequently than they should (and sometimes forget to do it entirely), which should give them more time to do other things.

As for drops, killed sheep have exactly the same chance to drop wool as in vanilla.
