### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by xan1mple** [ldtteam/minecolonies#9153]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.0.1400-BETA

### Structurize Version

1.0.424-ALPHA

### Related Mods and their Versions

forge:40.2.1
blockui:0.0.62-ALPHA
Domum:1.0.77-ALPHA
running on Magma hybrid server

### Current Behavior

[1.18.2 Magma Server] Server stops with error message: Encountered an unexpected exception

As this file shows,a domum block maybe was placed somewhere,but it was seen as a minecraft chest block entity,causes the game crashed.Is this problem literally CAN'T BE FIX ? I really need to use Magma server.
[crash-2023-05-25_18.06.13-server.txt](https://github.com/ldtteam/minecolonies/files/11563907/crash-2023-05-25_18.06.13-server.txt)
Not every Domum block has this problem,the error only occur in some particular blocks that I don't know.The exact location of the error Domum block isn't reported in the crashlogs , so it can't be deleted by some tool like MCEdit.

### Expected Behavior

the block should be placed correctly,then nothing will occur,thats the right way of placing a block

### Reproduction Steps

first,u need to run the server on Magma. When the builders place a particular Domum block,the Domum block will be seen as a Minecraft vanilla chest block entity,then the game will crash.This may only happen in a hybird server like this Magma or Sponge&forge server.

### Logs

https://gist.github.com/xan1mple/6b118787de5e7473e3ed3b3dd81fd96e

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Not minecolonies. Keep it to DO
