### ISSUE TITLE
Builder stuck in a loop trying to build the deliveryman's hut

### ISSUE THREAD

**Issue by PenguinMan98** [ldtteam/minecolonies#916]
### Minecolonies version

version 1.11-0.6.3360

### Expected behavior

- Build the thing

### Actual behaviour

- Builder wanders in a circuit.

### Steps to reproduce the problem

1. Place the deliveryman hut and start construction.
https://www.screencast.com/t/W9XS6mKiQh6D

**Comment by PenguinMan98** [comment]
I recalled her and she snapped out of it and finished the hut.

**Comment by Raycoms** [comment]
Perfect, great to hear
