### ISSUE TITLE
[BUG] <Mending Tools/Armor are unbreakable with colonist>

### ISSUE THREAD

**Issue by BlatantGuitar55** [ldtteam/minecolonies#9163]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19.2

### MineColonies Version

minecolonies-1.19.2-1.0.1433-ALPHA.jar

### Structurize Version

structurize-1.19.2-1.0.492-ALPHA.jar

### Current Behavior

Any tool with mending is unbreakable when in the hands of a colonist has been this way since 1.15

### Expected Behavior

expected them to break when being used after each update to the mod, but it never happened

### Reproduction Steps

step 1: give any tool/armor mending, but start with golden for a baseline
step 2: give enchanted tool to a worker (Forester, builder, miner, ECT)
Step 3: have them do their job and you will never need to give them a new tool again

### Logs

N/A

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
Why is this a bug according to you? The whole idea about mending is to get repairable tools when you they earn experience by working.

**Comment by Raycoms** [comment]
Yes, they gather xp while working which heals up the mending tool. But afaik it reduces the xp they gain a little bit
