### ISSUE TITLE
[BUG] Domum Ornamentum blocks aren't being delivered/used

### ISSUE THREAD

**Issue by bootzin** [ldtteam/minecolonies#9169]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19.2

### MineColonies Version

1.19.2-1.0.1433-ALPHA

### Structurize Version

1.19.2-1.0.492-ALPHA

### Related Mods and their Versions

Forge: 43.2.8
Block UI: 1.19-0.0.69-ALPHA
Domum Ornamentum: 1.19-1.0.83-ALPHA-universal

### Current Behavior

Domum Ornamentum items have suddenly stopped being delivered by couriers from the warehouse. Worked fine until yesterday. Today I updated to the latest minecolonies version and it stopped working. Rolling back did not solve the issue. Every other item works normally

![image](https://github.com/ldtteam/minecolonies/assets/23266003/76fae498-e70a-460b-bc71-56e4b5d2312e)
![image](https://github.com/ldtteam/minecolonies/assets/23266003/eac1b112-f5bb-48b5-af78-52bc7f969316)

Any Domum Ornamentum block has this issue. The requested item is the exact same as the item in the warehouse.
Another example:
![image](https://github.com/ldtteam/minecolonies/assets/23266003/55252a28-4cc7-4195-96d6-dda30589014f)
![image](https://github.com/ldtteam/minecolonies/assets/23266003/a9c97087-e6da-4a5f-ad0c-1a54307dd5dc)
![image](https://github.com/ldtteam/minecolonies/assets/23266003/3bbffa9d-c1c5-4604-95a0-66f6d4c3dbfe)

Going in creative and fulfilling the request doesn't work either. The builder accepts the item, goes to the construction site, but as soon as they get there, they show a red cog symbol above their head and request the item again, even if it's still in their own inventory or in their huts.

I have about 4 builders with the same issue, for a plethora of different items. This worked fine until yesterday, I have built multiple level 5 buildings, and a level 3 barracks, all in steampunk style.

Resetting the request system for mine and for all colonies didn't work either, nor did cancelling the request a few times.

### Expected Behavior

I would expect the couriers to be able to deliver DO items, and the builders to be able to use them

### Reproduction Steps

This is a bit hard, since it was working fine and the issue appeared suddenly, but here is somewhat what happened to me:

Use version 1.19.2-1.0.1431-ALPHA of minecolonies. Build a few buildings, including a builder's hut and a warehouse. I would suggest having both at level 5 and in the steampunk style (available in planetminecraft)
Have builders request a Domum Ornamentum item that is present in the warehouse.
Before that request is fulfilled, save and quit, update minecolonies to 1.19.2-1.0.1433-ALPHA and log back in.
When the builders resume their work orders, the couriers should be unable to fulfill their DO requests. Other requests should work normally.

### Logs

https://gist.github.com/bootzin/a11bc8c333b89ded5272d35ee1dd09c2

### Anything else?

There's one last thing. The log I attached was from when I started having problems. However, a previous log had the following error in it:
`Failed to build baked materially textured model for: com.ldtteam.domumornamentum.client.model.data.MaterialTextureData@5751c823`

Maybe it's related? That log is sadly too big however, even for a gist, but here is a part of it which might be relevant: [gist](https://gist.github.com/bootzin/eeb3d292c75aa62d73d13eda2ad7c26f)

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
I haven't been able to reproduce this in an instance containing only MineColonies and its dependencies.  Can you give this a try yourself?  Perhaps then try adding other mods from your current pack in groups until the problem resurfaces?

**Comment by Raycoms** [comment]
Stale
