### ISSUE TITLE
[BUG] Chunks Not Loading - SittingEntity Error

### ISSUE THREAD

**Issue by w4ngel** [ldtteam/minecolonies#9171]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19.2

### MineColonies Version

1.19.2-1.0.1433

### Structurize Version

1.19.2-1.0.1491

### Related Mods and their Versions

1. Forge version: 1.19.2 43.2.0
2. BlockUI 1.19-0.0.64
3. Domum Ornamentum 1.19 1.0.76

### Current Behavior

Certain players are getting chunks in colonies unloaded. When they go near these chunks they get their player data invalidated and they can't join. It only happens within colonies, and this error appears every time. 

The colonies have been built using creative with pre-constructed at all levels.

It is also happening in smaller colonies with only a few buildings spread out. The chunks seem to have no pattern with some parts of the colony loading and others not at all.every time

### Expected Behavior

The chunks should load.

### Reproduction Steps

We have not managed to replicate this, it happens to random players. It can also happen to players that have already loaded those chunks. 

This occurred with version 1316 to the latest alpha (1433). 

When we removed mods like Canary, or small ships. It seems to have fixed the issue only for it come back after a while.

### Logs

https://pastebin.com/Eg6rUwe3

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
There is another mod creating issues with our sitting entities. Please enable mixin logging: -Dmixin.debug=true
to get more info

**Comment by w4ngel** [comment]
> There is another mod creating issues with our sitting entities. Please enable mixin logging: -Dmixin.debug=true
> to get more info

We’ve done that and will continue monitoring. We think it was incompatibility with the small ships mod. We’re keeping an eye on it and will update if it happens again.
