### ISSUE TITLE
[BUG] Raids not Spawning at All

### ISSUE THREAD

**Issue by DSMister** [ldtteam/minecolonies#9179]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

minecolonies-1.19.2-1.0.1442-ALPHA.jar

### Structurize Version

structurize-1.19.2-1.0.491-ALPHA.jar

### Related Mods and their Versions

1. Forge version: 43.2.10
2. BlockUI version: blockui-1.19-0.0.64-ALPHA.jar
3. Domum Ornamentum: domum_ornamentum-1.19-1.0.76-ALPHA-universal.jar

### Current Behavior

Raids are not spawning at all. No barbarians, no Amazons, no mummies, no pirates, etc. 60 in-game days and not a single raid has happened. When someone tried to force raid all, an error message was thrown back instead.

### Expected Behavior

Raids should happen within the average allocated time (in our case, average is 16 nights with a minimum of 7 nights). 

### Reproduction Steps

This just happens every time a raid attempts to spawn, but to see it quickly, you can do the following:

1. Attempt /mc raid-All tonight barbarian_raid
2. Wait for the night
3. Check logs for error message

### Logs

https://gist.github.com/DSMister/5276d05f1c252ed08345de4b7b63dc85

### Anything else?

https://gist.github.com/DSMister/3b1d9cb049f25a5f373e811f12fdd5ad

This is the specific error message that I get. It's plastered all over the latest logs, but just in case you want to find it quickly.

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Estyria** [comment]
As a side note, I've seen several reports on discord from the last two days or so of people not seeing raids in .1442. Not an isolated event is what I'm leaning toward.

**Comment by Raycoms** [comment]
hotfixes pushed
