### ISSUE TITLE
Mystic Place

### ISSUE THREAD

**Issue by Evalun1** [ldtteam/minecolonies#9184]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.18

### MineColonies Version

1.19.4

### Structurize Version

1.19.4

### Current Behavior

Good day. there is a problem with the mystical site in version 1.19.4. the construction set is available but there is no selectable building in the mystic tab

### Expected Behavior

a mystic place 

### Reproduction Steps

?

### Logs

?

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
Not all styles have all buildings
If you can't find the building you are trying to build in the style you are using, hold the hut block in your hand and right click the air.
That will bring up a list of all the styles that have that building, and which section of the build tool they are in.
