### ISSUE TITLE
[BUG] Cook isn't cooking when fuel and raw meat input into restaurant block

### ISSUE THREAD

**Issue by gmwarlord** [ldtteam/minecolonies#9185]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

1.19.2-1.0.1391-BETA

### Structurize Version

1.19.2-1.0.491-AL

### Related Mods and their Versions

1. Forge 43.2.11

### Current Behavior

Cook isn't cooking when fuel and raw meat input into restaurant block
but is when input into a rack.

### Expected Behavior

Cook cooking when fuel and raw meat input into restaurant block and rack

### Reproduction Steps

build have empty inv on restaurant

set fuel type and recipe

add fuel and raw meat to restaurant block

[cook will walk up to the restaurant block, then go and sitdown] 

### Logs

?

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
You are roughly 60 versions out of date. Could you try to update first?

**Comment by samohtGTO** [comment]
is it a recipe for cook or assistant cook, bc at lvl 3 you have assistant cook which unlocks a lot more recipies if im right
