### ISSUE TITLE
[BUG] Builder Significantly slower after June 11 Alpha drop for 19.2

### ISSUE THREAD

**Issue by kcddagger** [ldtteam/minecolonies#9188]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

1.19.2-1.0.1460-ALPHA

### Structurize Version

1.19.2-1.0.492-ALPHA

### Related Mods and their Versions

1. Forge Version: 43.2.4
2. BlockUI Version: 1.19-0.0.69-ALPHA
3. Domum Ornamentum Version: 1.19-1.0.83-Alpha-universal
4. 101 other Mods installed that I had stripped out to make sure weren't causing issues prior to speaking up.

### Current Behavior

Prior to the update the tier 4 builder was zooming along placing blocks at a fast clip and could complete small buildings like the Level 1 Urban Birch residence in about half a (game) day. Now it takes the builder about a (game) day+ to complete the same build.

### Expected Behavior

I have the research, and have builders leveling up, I expect them to get faster at building things and placing blocks, not slower.

### Reproduction Steps

I am not sure what it would take to make sure this issue shows up in your own game.  I'm at a tier 4 city, expanding to some new buildings and leveling them up to level 4 before I move on to tier 5.  The builders slowing down (all three of them!) has slowed down progress significantly and I'm on a personal instance with enough RAM, Video, and Processor power to dedicate to the game so that should not be an issue.

### Logs

https://gist.github.com/kcddagger/2d22a61230695cd2c304bad824d2d57d

### Anything else?

JmWarrior on Discord is also having this issue and dropped his latest log in this GIST  https://gist.github.com/jmWarrior13583/03ad80493529f8d9488b91c127b66242

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
fixed
