### ISSUE TITLE
[BUG] Colonist needs to wait a few seconds before interacting with door

### ISSUE THREAD

**Issue by mc-kaishixiaxue** [ldtteam/minecolonies#9190]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

1.19.2-1.0.1464-ALPHA

### Structurize Version

1.19.2-1.0.491-ALPHA

### Current Behavior

Colonist needs to wait a few seconds before interacting with door, it may cause animals to take advantage of this time to escape from the fence.

### Expected Behavior

Hope to shorten the waiting time, like the vanilla villager.

### Reproduction Steps

1. Let the colonist stand in front of the door;
2. He'll stand there for a few seconds, then open the door;
3. A few seconds later, the door is closed.

### Logs

Uploading is failed

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by revdave33** [comment]
I, too, have wondered about this. A shorter pause would be great.

**Comment by Raycoms** [comment]
Normal, everything else would be much laggier
