### ISSUE TITLE
[BUG] Guards sometimes take off the armors they wear

### ISSUE THREAD

**Issue by mc-kaishixiaxue** [ldtteam/minecolonies#9191]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

1.19.2-1.0.1464-ALPHA

### Structurize Version

1.19.2-1.0.491-ALPHA

### Current Behavior

Guards sometimes take off the armors they wear, then they won't put it back on.
Besides that, when hiring a guard, he doesn't request armors, unless toggling the mode to follow.
Strangely, toggling the mode to following, they wear armors again, or the request is back to normal.

### Expected Behavior

Guards will not take off their armors automatically.

### Reproduction Steps

1. Build a guard tower and hire a guard;
2. Visit the guard's request GUI, nothing;
3. Visit the guard tower's GUI, then toggling the mode to follow;
4. The guard requests the armors;
5. After giving him items, toggling the mode to patrol mode, then waiting for a little long time. I found he took off his armors. This behavior does not necessarily happen when.

### Logs

Uploading is failed

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
It takes a while until the guard starts with the requesting
