### ISSUE TITLE
[BUG] My IA has run into an issue! [...]

### ISSUE THREAD

**Issue by Theomio** [ldtteam/minecolonies#9206]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.19.2-1.0.1391-BETA

### Structurize Version

1.19.2-1.0.491-ALPHA

### Related Mods and their Versions

All the Mods 8-1.0.19b

### Reproduction Steps

1. Have a colony
2. Colony works relatively fine
3. Have multiple coursiers
4. Have 1 then 2 coursiers bug while in the warehouse showing the bellow screened message

### Logs

https://gist.github.com/Theomio/a7a1be1026ce68ff4561a44bb0f84fbd

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.
![Capture11](https://github.com/ldtteam/minecolonies/assets/60735862/f6d360b4-61cc-44f8-a6d0-98d43a0a3a88)

**Comment by MotionlessTrain** [comment]
You are more than 100 versions outdated. Could you please try on the newest version?

**Comment by Theomio** [comment]
Apparently firing the bugged workers and hiring them again solved the issue.
