### ISSUE TITLE
[BUG] Can not reassign a request that has children (fixes itself) 1.15

### ISSUE THREAD

**Issue by zipacna** [ldtteam/minecolonies#9207]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

universal (1.15.2 did not have it yet?)

### Structurize Version

0.13.109-ALPHA (extracted from 1.15.2 jar mods.toml)

### Related Mods and their Versions

1. Forge Version (extracted): 31.2.8
2. Modpack: Craft To Exile Dissonance

### Reproduction Steps

I am aware that this is on a older Minecraft/MineColonies version (and had to misslabel it as 1.18). But as I did not find any matches on your issue tracker or discord for the phrase 'Can not reassign a request that has children'. I figured I at least document it.

1. Start to rebuild half the colony (2 builders on it)
2. Let the courier juggle the requests
3. Courier continues! But complains to report the AI issue.

### Logs

https://gist.github.com/zipacna/bdc713e7ed0d4b0ab903a786492f3ea5

### Anything else?

![image](https://github.com/ldtteam/minecolonies/assets/4885295/e7ffa2f3-a439-48f8-b924-31abf7e88082)

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Estyria** [comment]
Sorry, you’re playing a version of the mod that’s no longer supported. You could try searching archived help channels on the discord, but that is all we can suggest. That or update to a supported version like 1.19.2
