### ISSUE TITLE
[BUG] <My AI has run to an issue >

### ISSUE THREAD

**Issue by LeBaronTurquoise** [ldtteam/minecolonies#9208]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.18

### MineColonies Version

1.19.2-1.0.1365-BETA

### Structurize Version

1.19.2-1.0.472-BETA

### Related Mods and their Versions

[1.19.2]+SecurityCraft+v1.9.4.jar
blockui-1.19-0.0.64-ALPHA.jar
cfm-7.0.0-pre35-1.19.2.jar
create-1.19.2-0.5.0.f.jar
domum_ornamentum-1.19-1.0.76-ALPHA-universal.jar
immersive-portals-2.3.5-mc1.19.2-forge.jar
jei-1.19.2-forge-11.6.0.1015.jar
minecolonies-1.19.2-1.0.1365-BETA.jar
multipiston-1.19.2-1.2.21-ALPHA.jar
paradise-lost-2.1.0-beta+1.19.2.jar
StorageDrawers-1.19-11.1.2.jar
structurize-1.19.2-1.0.472-BETA.jar
Terralith_1.19.3_v2.3.7b.jar
tombstone-8.1.7-1.19.2.jar
VanillaTweaks-forge-1.19.2-1.5.65.jar

### Current Behavior

The builder says : 
"My AI has run into a issue! Please locate the latest.log (or contact the server owner if playing on a server) and send it to the minecolonies authors with this message."

So i'm sending you the message and the log here ! Thanks guy.

### Expected Behavior

Mmmh, i expected my builder to build. 
I had the same problem with the miner, but i changed the worker and it was good. It doesn't work with the builder.

### Reproduction Steps

The worker's ai run into an issue

### Logs

https://pastebin.com/vu3jJa2K

### Anything else?

:
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Log unfortuantely lacking the exception, we would need the serverlog for this
