### ISSUE TITLE
can no longer place the Supplycamp chest

### ISSUE THREAD

**Issue by Auriel1** [ldtteam/minecolonies#921]
### Minecolonies version

version      minecolonies-universal-1.10.2-0.7.780.jar
same with minecolonies-universal-1.10.2-0.7.776.jar 

### Expected behavior

- can place the Supplycamp chest

### Actual behaviour

- can't place the Supplycamp chest

### Steps to reproduce the problem

1. Try to place the Supplycamp chest
2. Wait that it takes place
3. Nothing happen, nor even a message in the chat
4. For the supplyship chest, either there is a warn that it runs out of space, or it takes place well
5. Profit (if you are near an ocean) ...

But I can place the Supplycamp chest with the builder wand, it's juste that nothing when clicking on ground with the item in hand..

**Comment by Auriel1** [comment]
After check it is impossible to put Supplycamp chest, yesterday I saw the ghost of the structure, but even by validating the construction do not begin, and nothing takes place.

Sorry for the wrong info

**Comment by xavierh** [comment]
Fixed, will be in in the next release
