### ISSUE TITLE
[BUG] <Crash on showing blueprint>

### ISSUE THREAD

**Issue by Acar77** [ldtteam/minecolonies#9213]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

1.19.2-1.0.1505-ALPHA

### Structurize Version

1.19.2-1.0.491-ALPHA

### Related Mods and their Versions

1. Forge Version: 43.2.14
2. BlockUI Version: 1.19-0.0.69-ALPHA
3. domum_ornamentum-1.19-1.0.76-ALPHA-universal

### Current Behavior

Game plays fine but the moment a blueprint is loaded to render in world, the game saves then crashes with an Exit Code -1. Attached is the crash report.
[crash-2023-06-25_13.24.37-client.txt](https://github.com/ldtteam/minecolonies/files/11860756/crash-2023-06-25_13.24.37-client.txt)

### Expected Behavior

Blueprints should be able to load and be moved without crashing

### Reproduction Steps

1. use the build tool or building item
2. load up the blueprint
3. wait for game to crash a few seconds after loading

### Logs

https://gist.github.com/Acar77/25dbffc994d1c911a997db590e8230ec

### Anything else?

Same issues apply even on diferent Minecolonies versions

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Estyria** [comment]
Are you using optifine?

**Comment by Nightenom** [comment]
Workaround fix in structurize-[1.0.493-ALPHA](https://github.com/ldtteam/Structurize/releases/tag/1.0.493-ALPHA)

**Comment by Talyda** [comment]
> Workaround fix in structurize-[1.0.493-ALPHA](https://github.com/ldtteam/Structurize/releases/tag/1.0.493-ALPHA)

Will this be ported back to 1.19.2?

**Comment by Nightenom** [comment]
@Raycoms

**Comment by Raycoms** [comment]
structurize-1.19.2-1.0.492-ALPHA.jar hbas it

**Comment by Talyda** [comment]
Oh, then I was wrong about person that had what I thought was same crash log =P Will get them to create an issue!
