### ISSUE TITLE
Crash when trying to place a certain building in this case a restaurant

### ISSUE THREAD

**Issue by UnluckyGodKing1** [ldtteam/minecolonies#9218]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

minecolonies-1.19.2-1.0.1511-ALPHA.jar

### Structurize Version

structurize-1.19.2-1.0.492-ALPHA.jar

### Current Behavior

So im in the starting stages of making my colony which is using the Medieval oak blueprints, I am trying to place a restaurant which has the same style and when im in that process of placing it, I press on the arrow buttons to shift it around but then the world crashes.

### Expected Behavior

Simply just being able to place down the restaurant without issue/crash

### Reproduction Steps

Use build tool/Restraint block to start the process of placing it down
Picking the style which for me is Medieval Oak
Then selecting the building
Once i can see the building i try to shift it around using arrow buttons that are displayed
Then i freeze and crash

### Logs

https://gist.github.com/UnluckyGodKing1/5d93785b71ebaa513b1d94a2761d72b2

### Anything else?

I am using the medieval MC modpack (MMC3) v16 and i have updated both the structurize and the minecolonies mods which is the only thing i have changed in the pack/

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Fixed already
