### ISSUE TITLE
Town Hall Upgrade bug?

### ISSUE THREAD

**Issue by NephandusMage** [ldtteam/minecolonies#922]
### Minecolonies version

version 1.10.2 or curse X.X.XX

### Expected behavior

Town Hall Level 3 - Builder keeps asking for 1 Item Frame - If I give it one, it disappears and Builder keeps asking for one.

### Actual behaviour

Town Hall Level 3 - Builder keeps asking for 1 Item Frame - If I give it one, it disappears and Builder keeps asking for one.

### Steps to reproduce the problem

1. keep giving 1 Item Frame
2. Fired and rehired another builder
3. Stopped and restarted upgrade
4. Profit

**Comment by NephandusMage** [comment]
I did not see an Item Frame in the list of needed resources

**Comment by Raycoms** [comment]
Yeah, that's because item frames are entities and not blocks.
Still in the current version it should show item frames in the list and he might even tell you the full amount.
They don't appear, he places them from his worker chest.

**Comment by jasonsaffle13** [comment]
I just had this exact thing happen to me with minecolonies-universal-1.10.2-0.8.1429 this morning.
