### ISSUE TITLE
Silents tools advisory

### ISSUE THREAD

**Issue by Moobien** [ldtteam/minecolonies#9220]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.18

### MineColonies Version

n/a

### Structurize Version

n/a

### Related Mods and their Versions

n/a

### Current Behavior

Sorry Ray for the vague bug report. I am only doing this as the person reported it didn't want to.

https://discord.com/channels/139070364159311872/724810019928801290/1123539630906671215

Apparently workers can use silents tools at any level regardless of hut level.

unconfirmed on versions etc.

### Expected Behavior

n/a

### Reproduction Steps

n/a

### Logs

n/a

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
So, they dont properly implement the stuff. I dont think there is anything we can do there aside of mod-compat requests
