### ISSUE TITLE
[BUG] Farmers "Forgetting" Field Assignments

### ISSUE THREAD

**Issue by kcddagger** [ldtteam/minecolonies#9222]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

1.19.2-1.0.1511-ALPHA

### Structurize Version

1.19.-1.0.492-ALPHA

### Related Mods and their Versions

1. Forge: 43.2.4
2. BlockUI: 1.19-0.0.69-ALPHA
3. Domum Ornamentum: 1.19-1.0.83-ALPHA-universal
4. +101 other mods that are currently up to date.

### Current Behavior

When I was working with my farmers (I have 5 Lvl 5 Farmers each have 5 fields) I noticed that most or all were all either missing fields or had "forgotten" fields that were theirs (Screenshots 1 & 2).
![1](https://github.com/ldtteam/minecolonies/assets/38692576/5a86cf12-0ec0-42d1-a9c6-bf673c0e1565)
![2](https://github.com/ldtteam/minecolonies/assets/38692576/be4ba0c9-48b4-42c8-8312-5cac5321b5c1)

To see if a restart of the game would remedy this; 
1. I closed out the game (Single player instance)
2. Exited to desktop
3. Closed my launcher (ATLauncher)
4. Waited 5 minutes and then restarted my launcher
5. Checked for updates
6. Restarted the game

Coming back into the game, at random 2-5 Farmers will have "forgotten" their fields.  I put it in quotes, because the fields were still assigned to the farm and farmer, but the name was listed as <unused> even though the field was assigned (Screenshots 3-7).
![3](https://github.com/ldtteam/minecolonies/assets/38692576/e59620d7-1d58-41b9-9b88-ae99bd0e2fdc)
![4](https://github.com/ldtteam/minecolonies/assets/38692576/19f1f54a-10cf-4f03-b072-b58fa52b7c0b)
![5](https://github.com/ldtteam/minecolonies/assets/38692576/cc209827-1577-4b21-b7f1-f4e89b729cfa)
![6](https://github.com/ldtteam/minecolonies/assets/38692576/8c1f7277-6d8b-4504-9029-a1e3282cb3ba)
![7](https://github.com/ldtteam/minecolonies/assets/38692576/01590acc-fb87-4183-b378-77f24189733e)

I went to each farmer, unassigned each field and reassigned it to that farmer again and that seemed to correct the <unused> issue. (Something I had thought might have been caused by one or more deaths of previous farmers during raids)

Less than 15 minutes later I went to each farmer again and checked their fields and found the original issue back again. (Screenshots 8-12).
![8](https://github.com/ldtteam/minecolonies/assets/38692576/aa2e12ff-2c35-4971-8a32-902d8dc2b958)
![9](https://github.com/ldtteam/minecolonies/assets/38692576/3ebe2771-b576-4d93-8b3c-98fa27e0d9fd)
![10](https://github.com/ldtteam/minecolonies/assets/38692576/99fc9100-216a-4c02-95ba-3ad965812b9d)
![11](https://github.com/ldtteam/minecolonies/assets/38692576/91c9f12d-b0bd-49c8-9c40-3535d7324e55)
![12](https://github.com/ldtteam/minecolonies/assets/38692576/fd8bcd31-859b-4e73-b1f5-194995b54720)

I have done this several times now across the last week so I can't pin down the time when this started. Only that I've been doing this to see if I can reproduce this reliably before reporting this here to see if there is something I'm missing.

### Expected Behavior

I should not be seeing farmers losing or forgetting fields.

### Reproduction Steps

Reproduction steps should be doable from the current behavior section.  If more information is needed I can be contacted in Discord or here in Github

### Logs

https://gist.github.com/kcddagger/7de07eec881c3688c1b628829c81a699

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
Farmers rely on the scarecrow tile entity to be loaded, this can become problematic if the farm fields are further away and not loaded, that could potentially cause this problem.
Soon, #9025 will push through which will move the fields to be stored as part of the colony buildings manager, which will completely mitigate this issue.
