### ISSUE TITLE
[BUG] Game crashes when trying to access the "Tasks:" tab of the Foresters hut

### ISSUE THREAD

**Issue by Lucina28** [ldtteam/minecolonies#9223]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

1.0.1511-ALPHA

### Structurize Version

1.0.492-ALPHA

### Related Mods and their Versions

Official Minecolonies Modpack 2.1 with all mods updated
GUI Scale (screenscale-1.19.2-2.4.jar) deactivated as it causes memory leak when combined with ars nouveau.

### Current Behavior

Game crashes when trying to access the "Tasks:" tab of the foresters hut.

### Expected Behavior

Game shows the "Tasks" tab of the foresters hut with the task to convert around 199 Oak Log to Stripped Oak Log issued by builders hut.

### Reproduction Steps

1. Load the world
2. When loaded in, wait a few seconds for the game to recognize the foresters hut as part of the colony
3. Access the Foresters hut GUI (right in front of the player)
4. Click the "Tasks:" tab
5. Game Crashes

### Logs

https://gist.github.com/Lucina28/38e8c7d80ff4c0e872428080bf7a3c76

### Anything else?

Allocated RAM:
8192MB also tried it with 16384MB
I'm launching the game via the CurseForge App

Here's a link to my world if needed:
https://drive.google.com/drive/u/0/folders/1GZx_ycc4AbqaXDookR7AxaPPQ1rdEURN

I don't know much about logs, but on the exceptions it says that something about mekanism or immersive engineering.
This world was never created or loaded on a modpack with the mentioned mods. maybe this is more about the place where it says that it's expecting to find a string.

**Comment by Lucina28** [comment]
Okay, the game no longer crashes after I supplied the warehouse with my own Oak Logs, since before my colony didn't have enough on its own yet.
![2023-06-29_00 48 37](https://github.com/ldtteam/minecolonies/assets/87932640/e9cc8123-d8ee-4e8d-967f-9e98305b7afa)

**Comment by Raycoms** [comment]
Can you include the crash report as well?

**Comment by Lucina28** [comment]
> Can you include the crash report as well?

where can I find this?

**Comment by Raycoms** [comment]
There should be a crash report folder

**Comment by Lucina28** [comment]
It seems that when trying to recreate the crash, it doesn't create a crash report. the game just freezes and doesn't respond. But I found a crash report in a different instance which I originally encountered this crash and is based on on the Minecolonies official modpack, just some mod adjustments/addons.

https://gist.github.com/Lucina28/bc49dfaa0da3054776249104f36e2eab

**Comment by Raycoms** [comment]
Can you try updating to the latest forge?

**Comment by Lucina28** [comment]
I've done that (43.2.13 -> 43.2.14)
The crash still persists.

**Comment by Raycoms** [comment]
Odd, the crash report doesnt mention us at all. Can you try without rubidium and oculus once?

**Comment by Raycoms** [comment]
hotfix pushed

**Comment by Raycoms** [comment]
Thanks for the world =D

**Comment by Lucina28** [comment]
did you manage to find out what the issue was?

I hope I could help :)
I really like your mod

**Comment by Raycoms** [comment]
Yes, it did

**Comment by Lucina28** [comment]
Okay!

I'm currently playing the pagoda pack and noticed that the builder places some blocks that they don't have in their inventory and also don't request. like Brown Brick Extra Shingles on Builders hut and Mine lvl 4 to 5 and Magenta Brick Extra Shingles on Tavern lvl 2 to 3, probably more but I haven't played as much yet. Don't know if that's intended (also some of the shingles are rotated the wrong way when the builders hut was placed inverted). Didn't wanna start an extra thread, just letting you know in case you didn't.

**Comment by MotionlessTrain** [comment]
That was fixed in structurize already iirc, so you probably need to update that.
Please do start a new issue for other issues. Otherwise it would get hard to keep track which issues have been resolved already and which haven't

**Comment by Lucina28** [comment]
alrighty
