### ISSUE TITLE
[BUG] Crafters stop working with items in their inventory

### ISSUE THREAD

**Issue by AlMasque** [ldtteam/minecolonies#9224]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

1.19.2-1.0.1511-ALPHA

### Structurize Version

1.19.2-1.0.492-ALPHA

### Current Behavior

When given a builder request, if crafters have items in their inventory (food items, saplings, apples), they become unable to process this request unless the items are manually removed from their inventories.

### Expected Behavior

Workers should process requests upon receiving them without having to manually remove items.

### Reproduction Steps

1. Request a build upgrade or construction
2. Monitor workers
3. Pay attention to those who recently went to the restaurant/picked up items along the way.

### Logs

https://gist.github.com/AlMasque/5c5411ce7209361e789b465806278c9d.js"></script><script src="https://gist.github.com/AlMasque/5c5411ce7209361e789b465806278c9d.js

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by SchemingWeasels** [comment]
Reproduced on 1.19.2-1.0.1524-ALPHA, Multiplayer.

Forester has a task to strip 9Oak 8Acacia and the hut has all 17 logs on a rack. If I try to put it into the forester's inventory, he immediately dumps it into the hut rack. 

I tried passing him full stacks of each log, but the courier comes and picks up the excess, leaving 8 and 9 logs respectively on the rack.

I removed everything from his inventory (except for his tool) as mentioned by OP, and he immediately got to work.
