### ISSUE TITLE
[BUG] class ovh.corail.tombstone.entity.GraveGuardian tried to access private field for com.minecolonies.coremod.colony.crafting.RecipeAnalyzer.createAnimals

### ISSUE THREAD

**Issue by sandalle** [ldtteam/minecolonies#9229]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.2

### MineColonies Version

1.20.1-1.0.1539-ALPHA

### Structurize Version

1.20-1.0.510-ALPHA

### Related Mods and their Versions

1. Forge 1.20.1-47.0.35
2. Structurize: 1.20-1.0.510-ALPHA
3. MineColonies: 1.20.1-1.0.1539-ALPHA
4. Corail Tombstone: 8.5.0-1.20

### Current Behavior

A mob from MineColonies tries to spawn/load/or die and causes a crash.

### Expected Behavior

Should not be crashing. Not sure if the field needs to be public or Corail Tombstone needs a fix.

### Reproduction Steps

1. Create a new world
2. Crashes while world is generating

### Logs

https://pastebin.com/m44ZE2d8

### Anything else?

Corail Tombstone bug for this same issue opened at https://github.com/Corail31/tombstone_lite/issues/160 .

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Yeah, that is on corail side and not ours. He actually takes the entity list for compat and uses a subfield that is not ours.
