### ISSUE TITLE
[BUG] Builder doesn't list, request but uses extra shingles in the pagoda pack & some shingles are rotated the wrong way when inverting the building

### ISSUE THREAD

**Issue by Lucina28** [ldtteam/minecolonies#9230]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

minecolonies-1.19.2-1.0.1541-ALPHA.jar

### Structurize Version

structurize-1.19.2-1.0.492-ALPHA.jar

### Related Mods and their Versions

minecolonies-1.19.2-1.0.1541-ALPHA.jar

structurize-1.19.2-1.0.492-ALPHA.jar

domum_ornamentum-1.19-1.0.102-ALPHA-universal.jar

forge - 43.2.14

Minecolonies Official Modpack 2.1 (not modified except updated the relevant mods to the latest alpha)

### Current Behavior

1. In the Pagoda pack, the Builder doesn't request extra shingles when upgrading buildings to the last level.

![2023-07-03_18 06 00](https://github.com/ldtteam/minecolonies/assets/87932640/9d62f740-30dc-4688-983a-5da30c2e7622)
Example 1:  Builders Hut lvl 4 -> 5

![2023-07-03_18 06 04](https://github.com/ldtteam/minecolonies/assets/87932640/a647542c-aca8-4746-a405-34061ad8a76d)
Builder doesn't have Brown Brick Extra Shingles in their inventory but builds with them.

![2023-07-03_18 17 55](https://github.com/ldtteam/minecolonies/assets/87932640/6762b88e-41ef-42a3-bf2f-99a2bf98cdcd)
Example 2 Tavern lvl 2 -> 3

![2023-07-03_18 18 06](https://github.com/ldtteam/minecolonies/assets/87932640/e0e7ba30-90e1-485a-bdc0-01258f6fabfe)
Again, builder doesn't have any of the Extra Shingles they are using

This has happened with every building I've been upgrading to the last level yet.

2. some of the Extra Shingles are rotated the wrong way when the building was inverted when placing it.

![2023-07-03_18 00 32](https://github.com/ldtteam/minecolonies/assets/87932640/92743d47-0226-43f4-9a73-5dab2c986c1c)
I have only experienced this on the builders hut since it's the only one I placed as inverted yet.

![2023-07-03_17 55 56](https://github.com/ldtteam/minecolonies/assets/87932640/7c0f8d43-d2b1-4950-83ce-12f0cf501f83)
Other angle

Also the mine has some written arrows on signs that point to the right entrance from lvl 3 on. if inverted the signs point in the wrong direction.

### Expected Behavior

1. The Builder requests the correct Extra Shingles and doesn't continue building until provided.

2. The Extra shingles on the corner rotate to the right angle when the building is upgraded on Inverted buildings and the signs point in the right direction when the mine is inverted.

### Reproduction Steps

1. create new world in creative
2. select the pagoda pack, place townhall and create colony
3. place builders hut inverted on lvl 4 and tavern on lvl 2 already constructed
4. assign a builder to the builders hut and upgrade it as well as the tavern.
5. provide the materials (important here: they don't request or list the extra shingles)
6. watch the builder place the extra shingles out of thin air in the final steps of the upgrades as well as the wrongly rotated corner pieces. (notice that some corner pieces are already wrongly rotated on the preview of the building!)
7. place a mine minimum lvl 3 inverted and see the signs on the other entrance

### Logs

https://gist.github.com/Lucina28/f964ca1bd1029802c89fb6aabbee746f

### Anything else?

I tested and recreated the issues on the Official Minecolonies Modpack. I don't know if they exist on a raw instance with only Minecolonies and all its dependencies but I'd assume they do. If testing on the Modpack, deactivate GUI Scale to prevent current the Memory leak when combined with Ars Nouveau.

**Comment by Lucina28** [comment]
update:

with the new version "structurize-1.19.2-1.0.591-BETA.jar" for 1.19 the builder requests the blocks now and has them in their inventory when building, but doesn't use them. the extra shingles now appear in a different "magical way" than before. They are placed in the builders racks afterwards.

**Comment by Raycoms** [comment]
fixed now
