### ISSUE TITLE
[BUG] <title> Deleted colony not actually deleted

### ISSUE THREAD

**Issue by norfaremc** [ldtteam/minecolonies#9231]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

minecolonies-1.19.2-1.0.1351-RELEASE.jar

### Structurize Version

structurize-1.19.2-1.0.491-ALPHA.jar

### Related Mods and their Versions

Forge version 43.2.14

### Current Behavior

Really strange issue. We loaded up the world and, despite never making a colony at all, a colony was made in a 1x1 chunk radius. Couldn't get rid of it. 

Deleted the mod, the colony stayed on the JourneyMap (Fullscreened and Mini-Map). We added the mod back in and it says the colony exists but... doesn't. It says Unknown pos. I went to the block it says the building was placed and it's super far away from the claim. Doesn't make sense.

I tried to combat this by making another colony and naming it Little Spruce. I then deleted said colony. Colony deleted, but this chunk stayed behind!
This image shows the colony ID, Building POS: unknown
![image](https://github.com/ldtteam/minecolonies/assets/133526827/cc250818-dc60-4ccb-a817-47f9f938dfad)

This image shows the colony claim and the block position that it says the building is at. My blue player marker is the location in which it says there's a building.
![image](https://github.com/ldtteam/minecolonies/assets/133526827/dea19d06-e22a-4712-b7b4-92cbebb21a07)

### Expected Behavior

Uh.... not have a colony we never made that is bugged even with or without the mod installed on the server.

### Reproduction Steps

- Added the minecolonies mod. A ghost colony showed up, uninvited.
- Removed minecolonies mod, ghost colony stayed
- readded minecolonies
- created a new colony, found out they were connected
- deleted my colony, even removed buildings, it did not delete this colony
- issue is not just Journey-Map related, it's still registering as a colony but with an unknown location
- recreated the colony with a blank name, now it says emikei's colony (my minecraft username), so I know for a fact it really is connected to my account
- I went into spectator mode and looked EVERYWHERE. There's not a single piece of minecolonies-related blocks anywhere near this entire area.

### Logs

Unrelated-No logs!

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
This looks like journeymap leftover data. When you hit /mc whereami in this chunk, do you get anything?

**Comment by norfaremc** [comment]
I initially thought it was a JourneyMap bug. But if you look at the first pic, you'll see that the colony in fact is real, but it's a ghost colony. This implies (I think?) that this bug also involves the minecolony mod itself as it's showing up still in the command, it just says the location is unknown.
It says no close colony when I do /mc whereami
When I do /mc colony claimInfo, this is what I get:
![image](https://github.com/ldtteam/minecolonies/assets/133526827/a5b10d2a-8dc3-4152-b348-af3c703dd47e)

**Comment by Raycoms** [comment]
Its because we store the colony id in a capability in the chunk. If something happens, or the world cant do cleanup properly. That chunk data might stay behind. When you create a new colony with the same id. It will understand this chunk as part of itself then.

**Comment by norfaremc** [comment]
Is there anything I can do to remove this then? It's an eyesore in our spawn.

**Comment by Raycoms** [comment]
The mc colony claim command, you can unclaim with it as well

**Comment by norfaremc** [comment]
We tried that, it doesn't work.

**Comment by Raycoms** [comment]
/mc colony claim <colony id> 3 false

where colony id is the id of the colony there. Which might be just 0 or 1

**Comment by norfaremc** [comment]
"Colony with ID 1 could not be found in this dimension!"
The colony's ID is 1

**Comment by Raycoms** [comment]
okay, create a colony somewhere else as you had done. Do the unclaim. then delete the colony again.

**Comment by norfaremc** [comment]
AMAZING! YOU FIXED IT, LOVE YOU!

**Comment by Raycoms** [comment]
yay =)
