### ISSUE TITLE
[BUG] Minecolonie 1.20.1 crash on generated chest loot

### ISSUE THREAD

**Issue by yanikara** [ldtteam/minecolonies#9236]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player (not tested)
- [X] Multi Player

### Minecraft Version

1.2

### MineColonies Version

1.0.1540-ALPHA

### Structurize Version

1.0.516-ALPHA

### Related Mods and their Versions
0. forge:47.0.49

1. server-1.20.1-20230612.114412-srg.jar
2. voicechat-forge-1.20.1-2.4.13.jar
3. TerraBlender-forge-1.20.1-3.0.0.165.jar
4. BiomesOPlenty-1.20.1-18.0.0.592.jar
5. jei-1.20.1-forge-15.2.0.22.jar
6. domum_ornamentum-1.20-1.0.103-ALPHA-universal.jar
7. sophisticatedcore-1.20.1-0.5.77.347.jar
8. rubidium-0.6.5.jar
9. curios-forge-5.2.0-beta.3+1.20.1.jar
10. flywheel-forge-1.20-0.6.9-4.jar
11. create-1.20.1-0.5.1.d.jar
12. blockui-1.20-0.0.84-ALPHA.jar
13. Xaeros_Minimap_23.5.0_Forge_1.20.jar
14. waystones-forge-1.20-14.0.0.jar
16. XaerosWorldMap_1.30.6_Forge_1.20.jar
17. citadel-2.4.2-1.20.1.jar
18. alexsmobs-1.22.5.jar
19. NaturesCompass-1.20.1-1.11.1-forge.jar
20. structurize-1.20-1.0.516-ALPHA.jar
21. multipiston-1.20-1.2.29-ALPHA.jar
22. sophisticatedbackpacks-1.20.1-3.18.54.870.jar
23. minecolonies-1.20.1-1.0.1540-ALPHA.jar
24. pmmo-1.20.1-1.0.1.jar
25. balm-forge-1.20-7.0.4.jar
26. forge-1.20.1-47.0.49-universal.jar
27. appleskin-forge-mc1.20.1-2.5.0.jar
28. corpse-1.20.1-1.0.3.jar
29. DungeonsArise-1.20.1-2.1.56.1-beta.jar

### Current Behavior

The server crashes at every chest opening generated in the world such as those in the wrecks or in the Pillagers' towers.__

### Expected Behavior

Open a chest without it crashing, from what I saw in the logs it's about loot table.

### Reproduction Steps

1. Found a structure with a chest (Can be vanilla)
2. Open the treasure chest.

### Logs

https://gist.github.com/yanikara/3e9369b4fe76da405925f1071708df95

### Anything else?

Thank you for this great mod and good continuation

**Comment by MotionlessTrain** [comment]
This at least seems to be happening in forge 47.0.50, based on other reports of the same crash

**Comment by Raycoms** [comment]
Did you upgrade this world from 1.19 to 1.20?

**Comment by Raycoms** [comment]
fixed

**Comment by yanikara** [comment]
Thank you for this fix, and no, is new world
