### ISSUE TITLE
[BUG] Server Crashes when Shift Clicking in crafting

### ISSUE THREAD

**Issue by Marix20** [ldtteam/minecolonies#9237]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.2

### MineColonies Version

1.20.1-1.1.2-ALPHA

### Structurize Version

1.20-1.0.516-ALPHA

### Related Mods and their Versions

1.20.1-forge-47.0.35
blockui-1.20-0.0.84-ALPHA
domum_ornamentum-1.20-1.0.104-ALPHA-universal
multipiston-1.20-1.2.30-ALPHA

### Current Behavior

Server crashes when in Crafting Table and shift+clicking on items.

### Expected Behavior

Shift+click on items work as normal.

### Reproduction Steps

Shift+click items into crafting table
Shift+click crafted items into inventory

### Logs

https://gist.github.com/Marix20/559ac0c1d8e37a7c5fc0f69e9ec406df

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
The log does not contain any mention of a crash

**Comment by Raycoms** [comment]
and I cannot reproduce it with only minecolonies

**Comment by Raycoms** [comment]
Closed until log is provided
