### ISSUE TITLE
[BUG]  Dedicated server crash when player opens a loot chest.

### ISSUE THREAD

**Issue by ProsperCraft** [ldtteam/minecolonies#9238]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.18

### MineColonies Version

minecolonies-1.20.1-1.0.1540-ALPHA

### Structurize Version

structurize-1.20-1.0.516-ALPHA

### Related Mods and their Versions

Forge - forge-1.20.1-47.1.0-
Blockui- blockui-1.20-0.0.84-ALPHA
DO- -domum_ornamentum-1.20-1.0.104-ALPHA-universal

### Current Behavior

Server crashes, I suspect we are using the deprecated way of adding loot to chests-

I had this issue with another mod and they updated to fix it.

They said forge had this note - @Deprecated //Use other method or manually call ForgeHooks.modifyLoot

### Expected Behavior

No crash

### Reproduction Steps

Install- open a chest- may only crash in dedicated server, not tried single player.

### Logs

https://gist.github.com/ProsperCraft/f7bd80688f55603c81eafec799bc4eec

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
Update mate, it was fixed in the version after that one =)

**Comment by ProsperCraft** [comment]
Issue was that curseforge this version is marked as release, the other versions are marked as alpha so my client didn't see them, thank you.
