### ISSUE TITLE
[BUG] Random crash when opening a loot chest

### ISSUE THREAD

**Issue by janisl** [ldtteam/minecolonies#9239]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.2

### MineColonies Version

1.20.1-1.0.1540-ALPHA

### Structurize Version

1.20-1.0.516-ALPHA

### Current Behavior

The game sometimes crashes when opening a loot chest in a village.

### Expected Behavior

Game does not crash.

### Reproduction Steps

1. Have a modpack that does not disable vanilla villages
2. Find a village
3. Open all loot chests

### Logs

https://gist.github.com/janisl/161ac4de73a1b1ee704a9e7951245bef

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
Update the mod, it was fixed in the next version
