### ISSUE TITLE
Miner level 5 stone version requires monster egg

### ISSUE THREAD

**Issue by Anakardian** [ldtteam/minecolonies#924]
### Minecolonies version

version 0.7.4.2.1 or curse 0.8.3

### Expected behavior

- Miner building should only require normal blocks

### Actual behaviour

- Building requires stone brick monster eggs

### Steps to reproduce the problem

1. Upgrade miner to level 5
2. check material list for builder

**Comment by Raycoms** [comment]
@pmardle

**Comment by marvin-bitterlich** [comment]
@pmardle any news? @Anakardian still an issue?

**Comment by pmardle** [comment]
Will sort it this weekend if still an issue

**Comment by Anakardian** [comment]
Just tried the update again. monster stone bricks are still listed as a requirement.

This is being tested on the official server.
