### ISSUE TITLE
Work Orders Not Appearing 1.18.1

### ISSUE THREAD

**Issue by RebmaV** [ldtteam/minecolonies#9245]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.18.1-1.0.975-RELEASE.jar

### Structurize Version

structurize-1.18.1-1.0.419-ALPHA.jar

### Reproduction Steps

I tried to look at the Work Orders at the Townhall, the game froze and then crashed. 
I have tried restarting the game, repairing the profile and restarting but the TownHall work orders and all building lists for the builders.

### Logs

https://pastebin.com/5LPAnGvM

### Anything else?

![No Work Orders](https://github.com/ldtteam/minecolonies/assets/63925799/45fa1b1c-baeb-491c-9e7b-77368738fb63)

**Comment by Raycoms** [comment]
Update to latest beta at least, super old version 1.18.1
