### ISSUE TITLE
Crash 10 secs after loading world..

### ISSUE THREAD

**Issue by jonabrv1965** [ldtteam/minecolonies#925]
### Minecolonies version

version minecolonies-universal-1.10.2-0.6.592.jar and minecolonies-universal-1.10.2-0.7.780.jar
MC 1.10.2, Java 1.8.0_131 (64)

### Expected behavior

- does not crash

### Actual behaviour

- crash....

### Steps to reproduce the problem
Please see the attached crash reports. the first is with .592 version and the second with .780

[crash-2017-05-02_16.53.30-server.txt](https://github.com/Minecolonies/minecolonies/files/972110/crash-2017-05-02_16.53.30-server.txt)

[crash-2017-05-02_17.02.01-server.txt](https://github.com/Minecolonies/minecolonies/files/972112/crash-2017-05-02_17.02.01-server.txt)
 
MC starts ok, and load the world, but after the load (10 secs aprox.) the game crash...

**Comment by jonabrv1965** [comment]
Uhm...I forgot to mention that rolling back to version minecolonies-universal-1.10.2-0.6.112, this very same world loads and works fine...

**Comment by marvin-bitterlich** [comment]
fixed
