### ISSUE TITLE
[BUG] 1.20.1 crash when colonists going to sleep

### ISSUE THREAD

**Issue by hron84** [ldtteam/minecolonies#9254]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.2

### MineColonies Version

1.1.22-BETA

### Structurize Version

1.0.584-BETA

### Related Mods and their Versions

1. Forge Version: 47.1.28
2. Blockui Version: 0.0.84-ALPHA
3. Domum Ornamentum version: 1.0.104-ALPHA

### Current Behavior

I assigned a housing to my colonists they started to approach their beds in a Tavern and suddenly, a crash

### Expected Behavior

Do not crash

### Reproduction Steps

1. Set colony to manual housing assing
2. Build a tavern
3. Assign a housing at night
4. See colonist approaching their bed
5. Crash

### Logs

https://gist.github.com/hron84/be1f2c0586710637ec7b5baf56a6944b

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
Downgrade forge to 47.1.3

**Comment by hron84** [comment]
I'll check it tonight, thanks.
