### ISSUE TITLE
Crashing Client when workers lie down

### ISSUE THREAD

**Issue by drKenderRendel** [ldtteam/minecolonies#9257]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.2

### MineColonies Version

1.1.28-RELEASE

### Structurize Version

1.0.584-BETA

### Related Mods and their Versions

Forge version: 47.1.33
BlockUI version: 0.0.84-ALPHA
Domum Ornamentum version: 1.0.106-BETA
[crash-2023-07-19_21.48.13-client.txt](https://github.com/ldtteam/minecolonies/files/12099641/crash-2023-07-19_21.48.13-client.txt)

### Reproduction Steps

Wait until a worker gets sick or is nighttime

### Logs

https://gist.github.com/drKenderRendel/b5b5c2072b6e9380e75398e46f1e9eba

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
Downgrade forge to 47.1.3
