### ISSUE TITLE
Query rather than issue - Colony Starter Kit

### ISSUE THREAD

**Issue by nekatu** [ldtteam/minecolonies#926]
Guys,

Setting up a server with Kreezxil's Colonial Expansion mod pack and I'd like to start all new players off with a kit with all the resources they'll need to get going.

What ID would I use for a give command to allocate a "SupplyCamp Chest" or "Supply Chest" to each user?

**Comment by Raycoms** [comment]
its minecolonies:supplyChestDeployer
