### ISSUE TITLE
[BUG] Default naming convention gone after changing name datapack

### ISSUE THREAD

**Issue by FluffiKiki** [ldtteam/minecolonies#9261]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

1.1.10-ALPHA

### Structurize Version

1.0.491-ALPHA

### Related Mods and their Versions

Forge version: 43.2.0

### Current Behavior

![image](https://github.com/ldtteam/minecolonies/assets/42556991/49ff1336-47ff-47c2-af02-6259f0364de2)
Where "default" should be, it is gone and you can only select other languages. New visitors and babies will also not spawn. This all occured after switching one citizen name datapack for another. 

### Expected Behavior

Upon switching them, I expected the game to using the new names. Old ones will be circulated out. 

### Reproduction Steps

1. Put different name datapack in.
2. Put another name datapack in.
3. Default naming removed, visitors and new citizens will not spawn. 

### Logs

https://paste.ee/p/OGG4U

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Can you post the datapack together?

**Comment by FluffiKiki** [comment]
Original:
[foodNamesDatapack.zip](https://github.com/ldtteam/minecolonies/files/12117559/foodNamesDatapack.zip)
Replaced with:
[foodPlantNamesDatapack.zip](https://github.com/ldtteam/minecolonies/files/12117562/foodPlantNamesDatapack.zip)

**Comment by FluffiKiki** [comment]
Discovered problem was in the datapack itself, not the game. Please close if no longer needed

**Comment by Raycoms** [comment]
Yeah, I guessed so, the datapack probably broke datapack loading which made the mod ones not load properly.

**Comment by uecasm** [comment]
More likely it just had the same name so it replaced the existing one.  That's expected behaviour 😁

**Comment by MotionlessTrain** [comment]
It actually looked like a syntax error in the json, from the log that was posted on discord earlier
