### ISSUE TITLE
[BUG] Ticking Entity Crash when sleeping

### ISSUE THREAD

**Issue by Anlambdy** [ldtteam/minecolonies#9262]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

1.20.1-1.1.28 RELEASE

### Structurize Version

1.20-1.0.584-BETA

### Related Mods and their Versions

1. Forge version: 47.1.33
2. Domum Ornamentum-1.20-1.0.104 ALPHA
3. Block UI Version 1.20-0.0.84-ALPHA

### Current Behavior

Whenever any colonist tries to sleep, they crash the game. it is a ticking entity error and occurs with whatever colonist gets to their bed first. 

### Expected Behavior

They should sleep and not crash the game when they interact with a bed

### Reproduction Steps

1.start the game normally
2. follow the tutorial
3. get the tavern built
4. on the first nigh it should happen.

### Logs

https://gist.github.com/Anlambdy/7d30ce517f4b8297058d8a88e8cb6eec.js

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
Downgrade forge to 47.1.3 (not .30)
