### ISSUE TITLE
[BUG] <title> Video/render problem before place the townhall

### ISSUE THREAD

**Issue by gatitoespacial** [ldtteam/minecolonies#9263]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

1.19.2-1.0.1351-RELEASE

### Structurize Version

1.19.2-1.0.491-ALPHA

### Related Mods and their Versions

Forge version: 1.19.2-43.2.21

### Current Behavior

https://github.com/ldtteam/minecolonies/assets/140284969/712a61ef-e749-4958-84ac-a4dbc945fbdb

I just wanted to place the townhall and then the video just look cut it

### Expected Behavior

Place de townhall and continuing playin

### Reproduction Steps

I dont know if its just a bug or just me, i dindt fin anyone else with the same problem

### Logs

-

### Anything else?

I tried to use another versions of the same mod but it doesnt work

**Comment by Talyda** [comment]
Using optifine? If so, don't. Oculus and Rubidium will work for your shaders =)
(also you are on a very old version of the mod, update that too =P)

**Comment by gatitoespacial** [comment]
It Worked! Thank you so much, I appreciate it
I downloaded a recent version btw, thank u :)
