### ISSUE TITLE
[BUG] Crash to Desktop - NoSuchMethodError - getEntitySizeForge called from EntityCitizen

### ISSUE THREAD

**Issue by joshuagore** [ldtteam/minecolonies#9264]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.2

### MineColonies Version

1.20.1-1.1.28-RELEASE

### Structurize Version

1.20-1.0.54-BETA

### Related Mods and their Versions

1. Forge: 1.20.1-47.1.28
2. BlockUI: 1.20-0.0.84-ALPHA

Minecraft Colonies 1.7 Modpack

### Current Behavior

I'm getting a crash to desktop when I'm near my colony.

Seems to be an error being thrown in the log.

`java.lang.NoSuchMethodError: 'net.minecraftforge.event.entity.EntityEvent$Size net.minecraftforge.event.ForgeEventFactory.getEntitySizeForge(net.minecraft.world.entity.Entity, net.minecraft.world.entity.Pose, net.minecraft.world.entity.EntityDimensions, float)'
	at com.minecolonies.coremod.entity.citizen.EntityCitizen.m_6210_(EntityCitizen.java:2099) ~[minecolonies-1.20.1-1.1.28-RELEASE.jar%23499!/:1.20.1-1.1.28-RELEASE]`

### Expected Behavior

There wouldn't be a crash to desktop.

### Reproduction Steps

Not sure if it's when I'm near a specific mob or what.

Overall, my colony was starting out well. Built a Builder's Hut, Townhall, Restaurant, 1st Residence, and was starting construction on a 2nd Residence. The Style I selected for this colony was Medieval Dark Oak, all buildings were alternate 1.

This is with the Minecolonies Dimensional Adventure Modpack.

### Logs

https://gist.github.com/joshuagore/4a0ea264e6b33e4a35a143c78897ce70 https://gist.github.com/joshuagore/a68919e464e7ca39c49056de6fa48cf8

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
Downgrade forge to 47.1.3

**Comment by joshuagore** [comment]
This pack has other dependencies which need newer Forge. Is there a plan to fix this?

**Comment by Thodor12** [comment]
No, Forge completely broke due to unrelated issues past that version.
Any mod that requires that version has to downgrade their mandatory Forge version because that version is completely broken.
