### ISSUE TITLE
[BUG] <Ticking Entity>

### ISSUE THREAD

**Issue by MacGod1969** [ldtteam/minecolonies#9268]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.2

### MineColonies Version

minecolonies-1.20.1-1.1.28-RELEASE

### Structurize Version

1.20-1.0.585-BETA

### Related Mods and their Versions

Citadel (by sbom_xela)
ShetiPhianCore (by ShetiPhian)
Cloth Config API (Fabric/Forge) (by shedaniel)
GeckoLib (by Gecko)
Simple Crop Harvester (by the_harbinger69)
Ender IO (by crazypants_mc_the_second)
MoreVanillaTools (by MelanX)
Corpse (by henkelmax)
Curios API (Forge) (by TheIllusiveC4)
Jade 🔍 (by Snownee_)
Tree Harvester (by Serilum)
Iron Furnaces [FORGE] (by XenoMustache)
Balm (Forge Edition) (by BlayTheNinth)
Seed Drop (by EwyBoy)
Caelus API (Forge) (by TheIllusiveC4)
FTB Backups 2 (by FTB)
Sophisticated Core (by P3pp3rF1y)
Alex's Mobs (by sbom_xela)
Puzzles Lib [Forge & Fabric] (by Fuzs)
Waystones (by BlayTheNinth)
CreativeCore (by CreativeMD)
Comforts (Fabric/Forge/Quilt) (by TheIllusiveC4)
Powah! (Rearchitected) (by thetechnici4n)
Refined Storage (by raoulvdberge)
MineColonies (by Raycoms)
Collective (by Serilum)
ForgeEndertech (by EnderLanky)
FTB Teams (Forge) (by FTB)
Advanced Finders (by EnderLanky)
Energized Power (by JDDev0)
No Auto Jump (by Jacky)
NetherPortalFix (by BlayTheNinth)
Supplementaries (by MehVahdJukaar)
Architectury API (Fabric/Forge) (by shedaniel)
Spice of Life: Carrot Edition (by lordcazsius)
Mouse Tweaks (by YaLTeR)
Farmer's Delight (by vectorwing)
Refined Storage Addons (by raoulvdberge)
BlockUI (by Raycoms)
Transmog (by Hidoni)
Xaero's Minimap & World Map - Waystones Compatibility [Forge] (by precisemodpacker)
Searchables (by Jaredlll08)
FTB Essentials (Forge) (by FTB)
McJtyLib (by McJty)
LibX (by noeppinoeppi)
TrimsEffects (by lupiiin_)
Simply Swords [Fabric & Forge] (by sweenuss)
Clumps (by Jaredlll08)
Charm of Undying (Fabric/Forge/Quilt) (by TheIllusiveC4)
Echo Chest [Forge & Fabric] (by Fuzs)
Structurize (by Raycoms)
AppleSkin (by squeek502)
PolyLib (by Official_CreeperHost)
Xaero's Minimap (by xaero96)
Stylecolonies (by Raycoms)
Resourceful Lib (by ThatGravyBoat)
FTB Chunks (Forge) (by FTB)
Dungeons and Taverns (by Nova_Wostra)
SmartBrainLib (Forge/Fabric/Quilt) (by Scimiguy)
FTB Library (Forge) (by FTB)
Supplementaries Squared (by plantspookable)
Lootr (Forge) (by Noobanidus)
Sophisticated Storage (by P3pp3rF1y)
Bookshelf (by DarkhaxDev)
Create (by simibubi)
Leap (by ModdingLegacy)
Domum Ornamentum (by OrionOnline)
Sophisticated Backpacks (by P3pp3rF1y)
Multi-Piston (by Raycoms)
Handcrafted (by kekie6)
Storage Racks (by Raycoms)
Lenient Creepers (by bl4ckscor3)
Iron Chests (by ProgWML6)
EnderChests (by ShetiPhian)
Simply Tools (by MelanX)
Kotlin for Forge (by thedarkcolour)
Xaero's World Map (by xaero96)
Scuba Gear (by ModdingLegacy)
Enchantment Descriptions (by DarkhaxDev)
Moonlight Lib (by MehVahdJukaar)
Controlling (by Jaredlll08)
Trade Cycling (by henkelmax)
Craftable Saddles (by alexdaum1)
Elytra Slot (Fabric/Forge/Quilt) (by TheIllusiveC4)
Just Enough Items (JEI) (by mezz)
Dash (by ModdingLegacy)

### Current Behavior

While working inside the Colony will get an entity ticking fault and it reboots the server.

### Expected Behavior

the server should not fault and reboot.

### Reproduction Steps

1. use the list of mods above and generate a dedicated server. 
2. Start building a colony. 
3. After building the 2nd builder hut, start building tavern, residence, mine, and town hall.
4. should start getting the ticking entity within 20 minutes from the time the builders start constructing any of these buildings and asks for tools or building materials. It also occurs when the sun goes down and the colonists go to bed.

### Logs

<script src="https://gist.github.com/MacGod1969/8bd3249456b8aed0baf6021565a80da0.js"></script>

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
Downgrade forge to 47.1.3

**Comment by MacGod1969** [comment]
I am running Forge 47.1.3

Sent from Yahoo Mail on Android 
 
  On Tue, Jul 25, 2023 at 5:50 PM, ***@***.***> wrote:   


Downgrade forge to 47.1.3

**Comment by Talyda** [comment]
Log says you are using fmlloader-1.20.1-47.1.30.jar
You need 47.1.3, not 47.1.30
