### ISSUE TITLE
Mine Signs not updating in 1.20 [BUG] <title>

### ISSUE THREAD

**Issue by LadyKathleen** [ldtteam/minecolonies#9269]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.2

### MineColonies Version

minecolonies-1.20.1-1.1.28-RELEASE.jar

### Structurize Version

structurize-1.20-1.0.585-BETA.jar

### Current Behavior

All Signs only say level_placeholder when being built.

https://discord.com/channels/139070364159311872/724810039281451028/1133789565325422663

Picture how the sign is not updating.

### Expected Behavior

expect the sign to give the level.

### Reproduction Steps

normal build a mine

### Logs

https://gist.github.com/LadyKathleen/7065c6f2eb7ecc36ba2673956e572fe8

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Moobien** [comment]
this COULD be related to how signs in 1.20.1 are double sided AND editable
