### ISSUE TITLE
[BUG] Pirate raid ship spawns on solid ground

### ISSUE THREAD

**Issue by gr2ws** [ldtteam/minecolonies#9270]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.2

### MineColonies Version

1.18-ALPHA

### Structurize Version

1.0.583-BETA

### Current Behavior

A pirate raid occurred in my colony even though my colony is in a Meadow Biome surrounded by Birch Forest. There are no large bodies of water. The ship spawned on a mound of podzol I use for growing big Spruce trees, if that matters. 

![2023-07-27_00 42 25](https://github.com/ldtteam/minecolonies/assets/96656463/805ffed5-81e2-4158-a623-3949b0af657a)

### Expected Behavior

I've only had barbarian raid types. According to the wiki, pirates need a large body of water, which is not present anywhere near where they spawned.

### Reproduction Steps

I have no concrete steps in reproducing the issue since it happened unexpectedly. However, I do have a large body of water North my colony that would possibly allow pirates to spawn, but they spawned in the South. Maybe the check for the large body of water did happen, but they were placed in the wrong location. 

### Logs

https://pastebin.com/3bwbUYyB

### Anything else?

I am NOT running the latest alpha version of Minecolonies. I ticked the box to submit it since I did not find anything mentioning this specific issue in any of the changelogs for the version after my own.  I have also checked open and closed issues and did not see anything mentioning this. 

I've also experienced a Nord raid a while ago despite the wiki saying that they only spawn in Taiga biomes, so that might be worth checking out. It happened a while ago and I do not have proof since I thought it was normal.

**Comment by Raycoms** [comment]
Do you by chance have the sky raid setting enabled in the config?

**Comment by gr2ws** [comment]
No I do not.

https://pastebin.com/M3dPqGuM
