### ISSUE TITLE
[BUG] Doctor acting useless, not curing people

### ISSUE THREAD

**Issue by Shadizar** [ldtteam/minecolonies#9272]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

1.19.2-1.1.36-BETA

### Structurize Version

1.19.2-1.0.591-BETA

### Related Mods and their Versions

ColonyVenture 2.5 on patreon server

### Current Behavior

Doctor doesn't cure patients and just runs around randomly; reported by at least 4 players on patreon server

### Expected Behavior

Doctor to cure patients

### Reproduction Steps

1. Have a doctor, with relevant cure items in rack in hospital.
2. Have patient that needs curing.

### Logs

Patreon server; not available

### Anything else?

I can cure the people by giving them the cure.
Firing/rehiring doctor or pause/unpause (with or without restart) has no impact.
Persisted after server reboot.

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Shadizar** [comment]
Supplementary data.
* Diseases I've had to cure by hand: mostly flu, some of the poppy/kelp/dandelion and one goldapple/honey
* djvirus in discord asserts they are attracted to guard patrol points. I do have some manually assigned guard cycles so it is possible but I've not confirmed in my colony.
* The racks have the cure items. Couriers bring them just fine.
* The doctor can reach the racks and I have seen them do so. The doctor has been found to have cure items in their inventory (unused). 
* The doctor is not themselves sick or hungry.
* Firing/rehiring does not fix. Nor do pause/unpause, nor pause/reset.
* Problem has persisted after server reboot.
* Doctor has "blight" (purple flames) with some buffs including speed. I don't think other folks' affected doctors have had it.
* Pretty sure hospital is lvl 3 right now. Not in game at the moment.
* Patients do come and lay down in beds. When manually supplied cure items they get cured and go about their business.
* Masks research has been done and vaccines one in progress.

**Comment by Raycoms** [comment]
the latest fixes seem to have fixed this too
