### ISSUE TITLE
[BUG] <title>Builder doesn't finish upgrade of townhall to level 2

### ISSUE THREAD

**Issue by Clov-er** [ldtteam/minecolonies#9278]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [X] Multi Player

### Minecraft Version

1.18

### MineColonies Version

1.20.1-1.1.28

### Structurize Version

1.20.1

### Related Mods and their Versions

Forge Modpack 'MineColonies Dimensional Adventure': 1.20.1 - 1.8

### Current Behavior

I have ordered 5 separate builders to complete an upgrade of a Steampunk Theme town hall (I'm not sure if the Steampunk theme is in the regular version of the mod) several times. 2 of the builders have died, 2 have been replaced, fired and rehired, paused, and reset dozens of times, and 1 has come from a separate builder's hut. I have attempted to get these builders to complete the build for at least 14 non-consecutive hours. Every time they begin the order, they walk around their builder's hut, appear to be gathering items from their racks, leave the building empty-handed and with nothing new in their inventories, and proceed to swing their hand emptily at the building at various points. If left to their own devices they will continue swinging their hand at the building until they eventually walk their way through the building, sit at the top, and do nothing. They have every resource they need to try and complete the build, no open requests for more items, and half a dozen tools they could use to terraform the building or its surroundings if needed. They will respond if I order them to build other buildings, or if I order them to deconstruct or repair the existing level 1 town hall. I am just at the end of my rope and have half a dozen other buildings already completed, along with the work that all my friends have put into this world. I don't want to have to restart, and I'm worried that my friends will lose interest if I do restart the village/world.

### Expected Behavior

The builder would complete an upgrade order for the town hall, bringing it from level 1 to level 2.

### Reproduction Steps

1. Build a Level 1 Steampunk Theme Town Hall while using the 'Minecolonies Dimensional Adventure' Modpack on Cursed forge.
2. Build and upgrade the Steampunk Builder's Hut to Level 2.
3. Order one of the builders to upgrade the Steampunk Theme Town Hall to Level 2.
4. Watch and begin to openly weep after 14 hours of fruitless effort. 

### Logs

I do not know where to find the logs

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.
* This is my first time using this site and I'm not sure if this is where I should be posting my issue, so if there is somewhere else I should post it please let me know.

**Comment by MotionlessTrain** [comment]
In the final steps of building a building (usually when placing torches and similar items), the builder will seem to stand still and not work. However, they are most likely performing calculations/checks to ensure that every block is placed correctly. This may take a while, especially the larger buildings, so be patient.
Firing and re-hiring a builder risks forcing the builder to start all of these calculations over again, so just leave them for a while

**Comment by Clov-er** [comment]
I saw that comment posted on other builds, but in those issues, it seemed like the builder had already placed down everything, or at least all items that weren't torches and items of that nature. Here the builder is still refusing to place down simple full-block items. And, even if they were still doing the final calculations, I fail to see how it could possibly take that builder 7+ hours uninterrupted to complete that calculation. If it is that simple then I am all for it, but is it at all possible there could be another issue here?

**Comment by aAndrew3030** [comment]
They get stuck in a endless loop. I am experiencing this issue with numerous building upgrades, and builders. If you watch the item screen in the builders hut, you can see the items switching all around, like there is a but in the request system. Cancelling the upgrades, removing everything from the builders inventory, and retrying the upgrade SOMETIMES get them unstuck. 

https://github.com/AllTheMods/ATM-9/issues/166

**Comment by aAndrew3030** [comment]
This seems to be the same issue as #9255

**Comment by Clov-er** [comment]
So if I'm reading both of those articles right, does that mean the only solution is to uninstall AE2?

**Comment by MotionlessTrain** [comment]
If they get stuck in an endless loop, I'm afraid so (until this issue gets fixed on either side)

**Comment by Clov-er** [comment]
How long do bugs like these typically take to resolve, just as a rough estimate? Like are we talking weeks, months, or years here?

**Comment by MotionlessTrain** [comment]
Depends on how difficult the bug is to track down, and the availability of the Minecolonies devs and/or AE2 devs (i.e. it is hard to say how long it will take)

**Comment by Clov-er** [comment]
Could a problem be that the mod pack uses a more unstable version of AE2, and a solution could be using a less unstable version instead of outright removing it?

**Comment by aAndrew3030** [comment]
The best way to figure that out is to try different versions of AE2 and see if it fixes the issue for you! AE2 has a version released yesterday, but I have not tested it yet to see if it fixes this bug

**Comment by aAndrew3030** [comment]
Scratch that, the new AE2 version seems to be for Neoforge
