### ISSUE TITLE
broken schematics

### ISSUE THREAD

**Issue by H3roDude** [ldtteam/minecolonies#928]
@xavierh when im making scannings from a building (like lumberjack) and upload it to the server it the building didnt get shown with the builder tool and when i press ok it only paste a sawmill chest with no interaction (you cant right klick it, like a ghost town block)
it also didnt worked with decorations i uploadet on the server

**Comment by H3roDude** [comment]
it also didnt worked with decorations i uploadet on the server

**Comment by xavierh** [comment]
Could you provide the log and the schematic in question ?

**Comment by xavierh** [comment]
> it also didnt worked with decorations i uploadet on the server

Could you reproduce this too, and send me the log for the client and the server ?

**Comment by H3roDude** [comment]
the log? i dont think its making text in the consol
i just marked the building uploadet it and restarted the server

**Comment by xavierh** [comment]
I need the log from the client and server. I can not do anything about it without them.

**Comment by xavierh** [comment]
btw does it show properly just after you scanned in the builder tool ?

**Comment by H3roDude** [comment]
the building? now it shows nothink 
is there a extra log where thinks like placed townhall wrote?

**Comment by xavierh** [comment]
You can find the client log in the Minecraft's directory under logs\fms-client-latest.log
For the server side it is logs\fms-server-latest.log

Could you send me both of them, just after you replicate the bug ?

**Comment by H3roDude** [comment]
Sie its My fault i diddnt noticed that tja wasnt on the newest Version from minecolonies its workin Fine on the la test version

**Comment by xavierh** [comment]
ok good to know
