### ISSUE TITLE
Housing Issues [BUG] <title>

### ISSUE THREAD

**Issue by LadyKathleen** [ldtteam/minecolonies#9280]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

minecolonies-1.20.1-1.1.28-RELEASE.jar

### Structurize Version

structurize-1.20-1.0.590-BETA.jar

### Current Behavior

I can confirm this issue.   If you start out with no houses available If you build a worker hut and then build a guardtower  then you hire someone and they take the worker hut, they do not have a place to live and will only gather at the townhall until you build them a house.
It falsely thinks that the guardtower is a home so you can hire someone.   But yet the catch 22 is if it did not then you would not be able to hire for the guardtower either.
He should have had a home before I could hire him..

Also a note: once he took the other job.. I can not hire a guard for the guardtower now until I finish the house.

Not sure how you would fix this or even if you can for both possible ways people play but I wanted to alert you to the behavior.

### Expected Behavior

Forced to build a house or if guardtower is open fill that job first.

### Reproduction Steps

Said Above

### Logs

https://gist.github.com/LadyKathleen/402006ad4779b13c40f6f07092da77fd

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by someaddons** [comment]
That is actually intended behaviour to allow hiring for guardtowers we allow hiring +1 when there is an open guard position, even if the citizen may not be used as a guard.
