### ISSUE TITLE
[BUG] Stonemason wont accept just stone in his "Custom Recipes"

### ISSUE THREAD

**Issue by Sven3399** [ldtteam/minecolonies#9282]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.20.1-1.1.28.-RELEASE

### Structurize Version

1.20-1.0.584-BETA

### Related Mods and their Versions

1. Forge version: 47.1.3
2. All the mods 9 Version: 0.0.45

### Current Behavior

Stonemason wont accept just stone in his "Custom Recipes"
As in the architects cutters recipe for for example: Stone Panels.  

He has the space.

### Expected Behavior

Stonemason will accept just stone in his "Custom Recipes"

### Reproduction Steps

In my case its Cavern Stonemason lvl 2.
![image](https://github.com/ldtteam/minecolonies/assets/139875314/8ab3acc8-ccc2-469f-85fc-993bec89d839)
Press "Teach" and the error on the bottom left shows up.
He has accepted other recipes before and after this.
![image](https://github.com/ldtteam/minecolonies/assets/139875314/97a62d69-b6af-4557-92e1-50656f925e87)
![image](https://github.com/ldtteam/minecolonies/assets/139875314/8f082661-4dd4-4e76-8a7f-914e7e7b791a)

I am Running All the mods 9 0.0.45.
I know AE2, which is installed, caused an issue before, so maybe thats it.

### Logs

https://pastebin.com/0vp7z7Wy

**Comment by Mekle001** [comment]
This is because the recent builds of that pack include GregTech, which turns Stone into a storage block for stone dust. All storage blocks automatically move to the Mechanic.

**Comment by Raycoms** [comment]
We could add a few classic blocks where this happens to the stonemason (stone, stonebricks, cobble) that they accept no matter what? @Mekle001

**Comment by Mekle001** [comment]
Yeah, I'm looking at this.
