### ISSUE TITLE
[BUG] Schematic cause a crash

### ISSUE THREAD

**Issue by 5UP3RTH30B4G** [ldtteam/minecolonies#9286]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [X] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

minecolonies-1.20.1-1.1.28-RELEASE

### Structurize Version

1.20-1.0.590-BETA

### Related Mods and their Versions

domum_ornamentum-1.20-1.0.110-RELEASE-universal
minecraftforge:47.1.43
blockui-1.20-0.0.84-ALPHA

### Current Behavior

The game crash on rendering a structure

### Expected Behavior

schematic work normaly 

### Reproduction Steps

1. right clic to place a structure
2. don't work
3. so retry 
4. crash
[crash-2023-08-02_14.47.21-client.txt](https://github.com/ldtteam/minecolonies/files/12240248/crash-2023-08-02_14.47.21-client.txt)

### Logs

https://pastebin.com/DSZRrDeA

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Moobien** [comment]
have you tried updating to the most recent version of the mod? do you have optifine or ribidium extras installed?

**Comment by Talyda** [comment]
Isn't sodium fabric?

**Comment by Moobien** [comment]
> Isn't sodium fabric?

Rubidum is a port of sodium so its likely some internal names are the same

**Comment by Raycoms** [comment]
So, you are trying to select a supplyship with a custom style of yours, right?

**Comment by Raycoms** [comment]
Added a fix for the crash

**Comment by 5UP3RTH30B4G** [comment]
> So, you are trying to select a supplyship with a custom style of yours, right?

No that the default one
