### ISSUE TITLE
[BUG] Schemetics wont turn or mirror unless changing the lvl of the schematic

### ISSUE THREAD

**Issue by JustADuder** [ldtteam/minecolonies#9287]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [ ] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

minecolonies-1.19.2-1.1.27-RELEASE.jar

### Structurize Version

structurize-1.19.2-1.0.594-RELEASE.jar

### Related Mods and their Versions

1. Forge: 43.2.19
2. domum_ornamentum-1.19-1.0.107-RELEASE-universal.jar
3. blockui-1.19-0.0.69-ALPHA.jar
4. multipiston-1.19.2-1.2.21-ALPHA.jar

### Logs

https://gist.github.com/JustADuder/ef29b21afd857ce243382634a50a022b

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Moobien** [comment]
I was able to replicate this in a clean instance. OP posted a video on discord showing the behaviour. https://discord.com/channels/139070364159311872/1003402520846139533/1136309570847912096

**Comment by someaddons** [comment]
might be related to https://github.com/ldtteam/Structurize/pull/594

**Comment by agentduckys** [comment]
I had the same issue, i updated structurize today so i assumed it was that so i just reverted to my backup before the update, and i have no issues now and i can rotate again.

**Comment by DragonMotion** [comment]
The latest stable version of "structurize-1.19.2-1.0.594- RELEASE " causes problems. All buildings don't rotate.
Return to the old stable version of "structurize-1.19.2-1.0.592- RELEASE" solves the problem with the rotation of buildings.

**Comment by Raycoms** [comment]
Please test the latest and tell us it if solved it for you
