### ISSUE TITLE
[BUG] Colonists are not properly using trapdoors to go up and down ladders

### ISSUE THREAD

**Issue by Jinotad** [ldtteam/minecolonies#9291]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [X] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

minecolonies-1.19.2-1.1.46-BETA.jar

### Structurize Version

structurize-1.19.2-1.0.591-BETA.jar

### Current Behavior

If a trap door is at the top of ladders, colonists will not open trap doors to go up/down the ladders.  Instead they will act as though there is no valid path, and given enough time will warp.  If the trap door is opened by a player, the colonists will immediately utilize the path just fine.

### Expected Behavior

Colonists should know to open and close the trapdoor to go up and down ladders during pathing.

### Reproduction Steps

Make a path for a colonist, where they need to go up or down a ladder with a trapdoor on top of the ladder.
Wait for them to need to use that path, check that they won't go up/down.
Open trap door, and see that they will now go up/down the ladder.

### Logs

None

### Anything else?

In the video, you can see the chicken herder trying to find a way down to the chickens, but is unable to reach them until I manually opened the trap door.

https://github.com/ldtteam/minecolonies/assets/85356635/ed344284-94a9-4a23-b75c-0db8adbcb898

**Comment by Raycoms** [comment]
-
