### ISSUE TITLE
[BUG] Field GUI hovertexts overlap buttons

### ISSUE THREAD

**Issue by qwltech** [ldtteam/minecolonies#9295]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

1.1.55-BETA

### Structurize Version

1.0.603-RELEASE

### Related Mods and their Versions

appleskin-forge-mc1.19-2.4.2.jar
balm-forge-1.19.2-4.5.7.jar
blockui-1.19-0.0.69-ALPHA.jar
Botania-1.19.2-440-FORGE.jar
comforts-forge-6.0.5+1.19.2.jar
Compressium-2.1.1-build.8+mc1.19.jar
corail_woodcutter-1.19.2-2.5.2.jar
corpse-1.19.2-1.0.0.jar
craftingtweaks-forge-1.19.2-15.1.8.jar
curios-forge-1.19.2-5.1.4.1.jar
domum_ornamentum-1.19-1.0.121-BETA-universal.jar
entityculling-forge-1.6.1-mc1.19.2.jar
FarmersDelight-1.19.2-1.2.3.jar
Jade-1.19.1-forge-8.8.1.jar
jei-1.19.2-forge-11.6.0.1015.jar
journeymap-1.19.2-5.9.7-forge.jar
JustEnoughResources-1.19.2-1.2.2.200.jar
minecolonies-1.19.2-1.1.55-BETA.jar
MouseTweaks-forge-mc1.19-2.23.jar
multipiston-1.19.2-1.2.25-ALPHA.jar
Patchouli-1.19.2-77.jar
radium-0.8.2.jar
radon-0.8.2.jar
rubidium-0.6.2b.jar
silent-lib-1.19.2-7.0.3.jar
sophisticatedbackpacks-1.19.2-3.18.55.889.jar
sophisticatedcore-1.19.2-0.5.83.394.jar
storageracks-1.19.2-1.1.4.jar
structurize-1.19.2-1.0.603-RELEASE.jar
trashslot-forge-1.19-12.0.2.jar
TreeChop-1.19.2-forge-0.17.8a.jar

### Current Behavior

In the new GUI for the farmer's field, the tooltip hovers over the number I am trying to adjust. I cannot see the number and I have to predict how many times to click.

### Expected Behavior

The tooltip should be positioned so it does not cover the number.

### Reproduction Steps

Open a farmer's field and try to set it up.

### Logs

https://gist.github.com/qwltech/4d3d1ff52377c1e90bf1966b845d8a93

### Anything else?

![Screenshot from 2023-08-06 21-43-31](https://github.com/ldtteam/minecolonies/assets/16530112/c171341d-1c61-453b-8ba8-9ececb102494)

**Comment by kezmodius** [comment]
This issue has had it's title changed incorrectly

**Comment by Thodor12** [comment]
Thanks kez!

**Comment by Thodor12** [comment]
This is actually fixed in more recent blockUI versions.
![2023-12-04 11_37_59-Minecraft_ 1 19 2 - Singleplayer](https://github.com/ldtteam/minecolonies/assets/14359461/3988e489-ea63-44e2-b4e9-cb708e80fcef)
