### ISSUE TITLE
Server - Failure to load world wierd crash.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [ldtteam/minecolonies#930]
### Minecolonies version

minecolonies-universal-1.10.2-0.7.799.jar

### Expected behavior

Could update from https://minecraft.curseforge.com/projects/minecolonies/files/2415244

### Actual behaviour

https://gist.github.com/P3rf3ctXZer0/0230f3e28ca4f42887bf6b0843e31790

### Steps to reproduce the problem

1. Update Minecollonies as seen above
2. Make a world using the world older minecollonies 
3. Profit.

**Comment by P3rf3ctXZer0** [comment]
@Kostronor mind responding?

**Comment by Raycoms** [comment]
Does this happen repeatedly?
Or only happened once?
Did you change anything else, are you using any other mods?

**Comment by P3rf3ctXZer0** [comment]
Repeatedly

**Comment by Raycoms** [comment]
Should be fixed with the newest alpha on curse.

**Comment by cltnschlosser** [comment]
@P3rf3ctXZer0 Are you still having this issue with the newest alpha that @Raycoms is talking about?

**Comment by P3rf3ctXZer0** [comment]
I left the minecraft scene sorry to disappoint.
