### ISSUE TITLE
[Bug] Farmer lost field assignments after plantation update

### ISSUE THREAD

**Issue by anastasia590** [ldtteam/minecolonies#9301]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

1.1.58 beta

### Structurize Version

1.0.609

### Current Behavior

farmer did not have any fields,  I had to break them and replace them in order to assign them.  These fields were previously being farmed.  This happened I believe when the GUI changed and plantations got fields

### Expected Behavior

that the fields would have been automatically recognized as they had been (the plantation continued doing it's thing with no problems) 

### Reproduction Steps

use the old version of minecolonies before the plantation field update
build a farm and get the farmer some fields, 
update minecolonies 
check the farm

### Logs

I don't know how to get those right now 

### Anything else?

it's fixed now that I broke and put back down the fields but wanted you to know about it 

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
I had built something in the code to fix this, but since I couldn't guarantee fields were being loaded (due to them being tile entities), it didn't always work.

Seeing as this is a one time fault requiring re-placing the fields, do you think this is a big issue?

**Comment by Raycoms** [comment]
Losing assignment is not a huge problem, requiring removing and readding is a problem. There should be some UI way to solve that.

**Comment by anastasia590** [comment]
not a big deal but after troubleshooting in discord I was asked to still post a github.   Maybe just an announcement that if that happened to break and replace fields.  it's not going to affect new colonies moving forward but as people update the "why is my farmer not farming" questions may get annoying.

**Comment by Thodor12** [comment]
Unfortunately there is not much I can do to this issue. When tile entities load the colony may or may not exist yet, which means I cannot register the farm field, which was required for migration to properly happen.

If you break the field, it will re-register itself to the colony.

However I added some code that upon opening of the GUI will also attempt to register it again if it does not exist, it still isn't a fix all solution but at least it doesn't require replacing them.
