### ISSUE TITLE
[BUG] Extra claimed colony chunk about 3 chunks away from main colony.

### ISSUE THREAD

**Issue by Kaylinofhr** [ldtteam/minecolonies#9304]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

minecolonies-1.19.2-1.1.70-BETA.jar

### Structurize Version

structurize-1.19.2-1.0.611-RELEASE.jar

### Related Mods and their Versions

Forge Version: 43.2.10
domum_ornamentum-1.19-1.0.125-BETA-universal.jar
blockui-1.19-0.0.69-ALPHA.jar
stylecolonies-1.0.3.jar
multipiston-1.19.2-1.2.21-ALPHA.jar
journeymap-1.19.2-5.9.7-forge.jar
JadeColonies-1.19.2-1.0.1.jar
This is a personal custom modpack.  I don't see any other mods that would deal with the colony.  If you need a complete mod list, please let me know.

### Current Behavior

Link from Discord: [https://discord.com/channels/139070364159311872/1003402520846139533/1140094457702789171](url)

I was told to report this issue.  There's an image attached to the link of UltraAlphaAngel's post on the issue that shows it clearly.  Information from the conversation that may help: The whereami command says: "You're inside colony Kaylin's Colony with ID 1.  The colony center is approx. 169.0 blocks away."  Cavern style colony.  Created yesterday (Aug. 11, 2023). The world and colony were created on minecolonies-1.19.2-1.1.58-BETA.jar.  I updated to today's update and still see the extra claimed chunk.

### Expected Behavior

All colony claimed chunks connected together.

### Reproduction Steps

Create world
Establish Cavern style colony
See extra claimed chunk about 3 chunks away.

### Logs

https://gist.github.com/Kaylinofhr/fcbb316bfcd997569592ceb3f66c117e

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by UltraAlphaAngel** [comment]
I've got the same thing that happened.

**Comment by Raycoms** [comment]
Was there ever an attempt of a different colony in the same world?

**Comment by UltraAlphaAngel** [comment]
Not with me it is the only one I made

**Comment by MotionlessTrain** [comment]
From what I noticed, the extra chunk seems to be the chunk containing block 0, 0, 0
I haven't checked when it claims it, but I think it is either after starting up a world or claiming a building (last time I noticed it happening, a building was just finished a couple minutes after joining the world)

**Comment by someaddons** [comment]
did the game crash anytime after colony creation?
Could you use the claimInfo command and show us the output?

**Comment by MotionlessTrain** [comment]
> did the game crash anytime after colony creation?

I have had this happen without the game crashing.
I have tried multiple times to unclaim that chunk, and it showed up back later as being claimed, by journeymap, the build tool, and /mc whereami
Unfortunately, I haven't payed enough attention, whether that happened after starting up the game or having a building claim chunks
(I'm not in game right now, so I can't run the claimInfo command)

**Comment by Kaylinofhr** [comment]
It's happened everytime I've started a new world on the same seed. (3690981369606832557) It's from one of Lady Shatana's videos.  I've  never noticed any crashes or bad things from the extra chunk.  Mine is actually 6 chunks away.  I misremembered.  It is the chunk containing 0,0.

**Comment by Kaylinofhr** [comment]
I don't seem to have a claiminfo or mc claiminfo command.  Do you have the exact command I need to type?

**Comment by UltraAlphaAngel** [comment]
mc colony claiminfo

**Comment by Kaylinofhr** [comment]
![2023-08-13_02 19 52](https://github.com/ldtteam/minecolonies/assets/69356635/bafbe5b8-fd2e-41f6-90cb-489dd8007816)

**Comment by someaddons** [comment]
oh very interesting, apparently all buildings applied a claim to 0 0

**Comment by kalutro** [comment]
I am having this same issue. The rogue claim is the chunk at position (0,0) and it also is claiming all of my buildings. When I building a new building, it automatically gets claimed by this rogue claim. I noticed this claim as soon as I built my colony. My colony was initially just a lone town hall that I claimed.

**Comment by someaddons** [comment]
fixed
