### ISSUE TITLE
[BUG] Mod updates broke my citizens

### ISSUE THREAD

**Issue by LadyShatana** [ldtteam/minecolonies#9308]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

1.19.2-1.1.87-BETA

### Structurize Version

1.19.2-1.0.629-RELEASE

### Related Mods and their Versions

Forge 43.2.0

### Current Behavior

Updated to Version 1.19.2-1.1.82-BETA which broke all my colony ownerships on my server. Used commands to reassign proper owners but colonists didn't look right and were not responding as expected.

As per MTrain updated to NEW beta 1.19.2-1.1.87 which did not do anything to ownership but all colonists and visitors are non selectable, cannot even "smack" them

### Expected Behavior

Being able to interact with citizens would be cool

### Reproduction Steps

Update mod.
Try to talk to citizens
Fail
Try to smack them
Fail
Cry
#blameSam 

### Logs

https://gist.github.com/LadyShatana/dd1b6b9fa13ac7536453594bb36bf3f3

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
Just to add one detail which was mentioned on discord, but I don't see on the bug report: After updating to 1.1.87, the ownerships were restored using the command

**Comment by LadyShatana** [comment]
I have reset with commands: requests, citizens. Fired and rehired. Smacked. Recalled. Re-did colony ownership command. Citizens seem to be like ghosts

**Comment by someaddons** [comment]
restarted the game/server?

**Comment by LadyShatana** [comment]
Yes, 2 restarts on both ends :)

**Comment by Raycoms** [comment]
Can you give us some colony info extract?

**Comment by LadyShatana** [comment]
Would it help to give you access directly to my server and files?

**Comment by someaddons** [comment]
^ye logging in would probably be helpful (with op for commands)

**Comment by Raycoms** [comment]
fixed in newest
