### ISSUE TITLE
[BUG] Clipboard wont open in the end

### ISSUE THREAD

**Issue by Tristenm1019** [ldtteam/minecolonies#9311]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.1.56

### Structurize Version

1.0.607

### Related Mods and their Versions

ATM9 pack - Forge 1.20.1-47.1.3

### Current Behavior

clipboard will not open, even after binding it at the town hall, in the End

![image](https://github.com/ldtteam/minecolonies/assets/123491278/9fdd8ceb-3089-4530-9972-ea2ed3d023ca)

### Expected Behavior

Expected the clipboard to open

### Reproduction Steps

1. Make a colony in the End
2. Bind the clipboard to the townhall
3. right click with the clipboard in your hand

### Logs

https://gist.github.com/Tristenm1019/df30212c56c618ecf2656b1221103e8b

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by someaddons** [comment]
can't reproduce it

**Comment by Raycoms** [comment]
I believe that was the buggy version we had.
