### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by UnstableMistake** [ldtteam/minecolonies#9318]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.20.1-1.1.97

### Structurize Version

1.20.1-1.0.627

### Related Mods and their Versions

Forge 47.1.3
Block ui 1.20-0.0.83
Domum 1.20-1.0.126

### Current Behavior

Unable to put any kind of block into the architects cutter to craft the domum ornamentum blocks

### Expected Behavior

Being able tp craft the block through use of the architects cutter

### Reproduction Steps

1 Place architects cutter 
2 try to place block in the ui for cutter 
3 doesnt accept blocks

### Logs

K

### Anything else?

Not really much else to say just wont allow me the use of the architects cutter

**Comment by MotionlessTrain** [comment]
Are you using Epic Paladins by chance?

**Comment by UnstableMistake** [comment]
Yes i am would that be the cause

**Comment by MotionlessTrain** [comment]
It would, yeah

**Comment by UnstableMistake** [comment]
Okay i will remove that mod from my list thank you wouldnt have thought those would interact
