### ISSUE TITLE
Feedback for the food system

### ISSUE THREAD

**Issue by rexrapter1234** [ldtteam/minecolonies#932]
Feedback for the food system.

I've found out that when I give workers food, they end up eating some of it and when they go back to their blocks, they put the rest in their block and the delivery man comes a long and takes it. 

After some time all of the workers have no food, so they stop working as they have no food left. Also the delivery man is not delivering food. so I end up having to give out more food to the workers and than it just repeats and on and on ......

My city has lots of food, so I never run out of it. It just not been delivered to the workers and then they do have it. It just gets taken a way from them.

All of my buildings are level 5.

**Comment by Raycoms** [comment]
The deliveryman actually should deliver the food to the citizen huts of the workers.
If you put food in their citizen huts they will take out exactly enough and the deliveryman won't take it away.

**Comment by rexrapter1234** [comment]
Oh okay. I been put it in the work chests / blocks. Question how can I tell what citizen huts my workers live in ? I have lots of citizen huts.

Thank you the info is very useful.

**Comment by Raycoms** [comment]
Look at their huts at night.
We'll add something smarter soon

**Comment by rexrapter1234** [comment]
ok thx

**Comment by Raycoms** [comment]
Is this still a problem?

**Comment by jennyl** [comment]
@Raycoms Hi. I have this problem too. The delivery man was not bringing food to the citizens. I had steak sitting in the warehouse. Using the universal jar version (0.7.848).

**Comment by Raycoms** [comment]
Can you use the newest beta and check if it still happens?

Am Samstag, 20. Mai 2017 schrieb Jen :

**Comment by jennyl** [comment]
Hi, lol. I deleted my message because I realized I make my character sleep immediately at night so this is probably preventing the citizens from requesting food from the delivery man. I wanted to try again before commenting on this again.

On a side note, is there a list of food that the citizens accept? They didn't like my blackberry juice from Pam's Harvestcraft but I know they like steak and pork chops. 

And are there any change logs available for each version release? I'm not currently using the Curse client but if there are immense bug fixes I will definitely reconsider.

Loving your mod so far!

**Comment by Raycoms** [comment]
On curse we publish the change logs of each version, the moment we tested
them.
They accept everything which is ItemFood.


Am Samstag, 20. Mai 2017 schrieb Jen :

**Comment by zekermarco** [comment]
This is still happening to me in the latest version of the Minecolonies Testpack (0.8.9).
The workers DO eat from their citizens chests, but the Dman doesn't deliver any food to empty citizens chests even when the citizens hunger bars are low.

**Comment by scottosx** [comment]
I have this problem too. I keep giving citizens food and the dman takes it away. That would be fine but they don't (have 3) deliver it back in a timely fashion, at least during building phases. I have yet to see any of my citizens eat from their home chests.

The dman should always leave at least 1 stack of the highest value food in citizens inventory.
