### ISSUE TITLE
[BUG] Colony missing

### ISSUE THREAD

**Issue by ThePebblemancer** [ldtteam/minecolonies#9329]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.20.1-1.1.110-BETA

### Structurize Version

1.20.1-1.0.631-BETA

### Related Mods and their Versions

1. Forge: 47.1.44
2. Domum Ornamentum: 1.20-1.0.126-BETA-universal
3. BlockUI: 1.20.1-0.0.87-ALPHA
4. TownTalk: 1.20.1-1.0.0

### Current Behavior

All colonists and colonies disappeared when entering the world.

### Expected Behavior

All colonists and colonies continue to exist after entering the world.

### Reproduction Steps

1. Update all Minecolonies-related mods (specifically Minecolonies 1.20.1-1.1.28-RELEASE to 1.20.1-1.1.110-BETA and Structurize 1.20-1.0.606-RELEASE to 1.20.1-1.0.631-BETA) and download TownTalk
2. Enter world

### Logs

https://gist.github.com/ThePebblemancer/6608aebac4f2d05450329b57f81308b7

### Anything else?

MotionlessTrain askem me to open this bug report

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
fixed
