### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by MishaninaT** [ldtteam/minecolonies#9333]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [ ] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.1.28-RELEASE

### Structurize Version

1.0.584-BETA

### Related Mods and their Versions

1.Forge

### Current Behavior

No WORK

### Expected Behavior

WORK

### Reproduction Steps

No work with mod create

### Logs

https://gist.github.com/MishaninaT/ba6f37e16665227d47960a3e3215db92.js

**Comment by Moobien** [comment]
Plugin loaders are not supported ie Mohist which is what you are using.

**Comment by Raycoms** [comment]
and you are vastly outdated
