### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by Yuri348** [ldtteam/minecolonies#9336]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

minecolonies-1.20.1-1.1.113-BETA.jar

### Structurize Version

structurize-1.20.1-1.0.631-BETA.jar

### Related Mods and their Versions

Forge - 47.1.40
Domum Ornamentum - 1.0.126 - BETA
BlockUI - 0.0.87 - ALPHA

### Current Behavior

It stays on the world loading screen, but does not enter

### Expected Behavior

Enter the world

### Reproduction Steps

Bug happens when I enter a world where I had already started a colony.

### Logs

https://gist.github.com/Yuri348/fa71513abf9e027a5c8d187e23d4b761

### Anything else?

This only happens when I enter a world where I started my colony, and after I leave the game and come back, the bug happens.

**Comment by MotionlessTrain** [comment]
It looks like the sophisticated core config is corrupt

**Comment by Yuri348** [comment]
I removed Sophisticated Core and dependent mods, but it didn't work...

**Comment by Raycoms** [comment]
New log?

**Comment by Raycoms** [comment]
Please come to our discord for support.
