### ISSUE TITLE
[BUG] Cant Upgrade Town Hall 

### ISSUE THREAD

**Issue by HectorCesar** [ldtteam/minecolonies#9339]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.1.56-Beta

### Structurize Version

1.0.607-Beta

### Related Mods and their Versions

1:47.1.3

### Current Behavior

Found an Village and now i want to Upgrade my Town Hall to lvl 3 but it only Shows me the Town Hall Block. The Builders Hut is at lvl 5.

### Expected Behavior

Should Upgrade from 2->3

### Reproduction Steps

I dont know 

### Logs

I dont have a log Right now 

### Anything else?

![image](https://github.com/ldtteam/minecolonies/assets/143325694/12b85afc-56b2-469b-826d-85d9ed4bd36a)

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
Could you try updating to the latest beta? Afaik this is fixed already
