### ISSUE TITLE
[BUG] Description for the plantation nether research doesn't mention vines

### ISSUE THREAD

**Issue by IchHabeHunger54** [ldtteam/minecolonies#9340]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

1.1.96-BETA

### Structurize Version

1.0.629-RELEASE

### Related Mods and their Versions

N/A

### Current Behavior

![image](https://github.com/ldtteam/minecolonies/assets/52419336/1f8dbdea-a62b-419c-b389-c05c630db8e8)
The research description for the "Gargamel" research (the one that unlocks nether plants for the plantation) is missing the Weeping /Twisting Vines part.

### Expected Behavior

For it to say something like "Crimson Fungi, Warped Fungi, Weeping Vines and Twisting Vines" (might as well fix the weird capitalization in there)

### Reproduction Steps

1. Place down a University and see for yourself (lol)

### Logs

N/A

### Anything else?

N/A

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by anonymous563** [comment]
I think this belongs on the mod's main github, not the wiki. However, the research system page also needs to be updated with the new research.

**Comment by Raycoms** [comment]
@Thodor12 ?
