### ISSUE TITLE
[BUG] Achitect's Cutter does not take item inputs.

### ISSUE THREAD

**Issue by PiratBootyPirat** [ldtteam/minecolonies#9341]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.20.1-1.1.117-RELEASE

### Structurize Version

1.20.1-1.0.631-BETA

### Related Mods and their Versions

1. Forge Version: 47.1.3
2. BlockUI Version: 1.20-0.0.84-ALPHA
3. Domum Ornamentum Version: 1.20-1.0.126-BETA

### Current Behavior

The Architect's Cutter will not allow any blocks to be placed in it's inventory slots, leaving decorative blocks uncraftable.

### Expected Behavior

It should allow for items to be put in the inventory slots to allow for crafting. 

### Reproduction Steps

1. Place an Architect's cutter
2. Try to use it

### Logs

N/A

### Anything else?

Interestingly I was just playing a slightly different modpack with Domum Ornamentum in which the Architect's cutter did work. I tried using the same version of DO, but it did not fix the issue. Not sure what to make of the situation.

**Comment by Talyda** [comment]
Do you have Epic Paladins installed?
Try disabling that, see if it works

**Comment by PiratBootyPirat** [comment]
I did have Epic Paladins installed, and disabling it fixed the issue. Thanks for the help!
