### ISSUE TITLE
[BUG] After update to 1.20.1-1.1.118-BETA the colony is (not) owned by me any more and no hut is accessible

### ISSUE THREAD

**Issue by Florianer** [ldtteam/minecolonies#9344]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.20.1-1.1.118-BETA

### Structurize Version

1.20.1-1.0.631-BETA.jar

### Current Behavior

Not sure, I think I upgraded from minecolonies-1.20.1-1.1.101-BETA.jar to minecolonies-1.20.1-1.1.118-BETA.jar

/minecolonies whoami
You are Florianer. Your colony is Sea City with ID 1 at position x: -72 y: 52 z: 109

/minecolonies whereami
You're inside colony Sea City with ID 1. The colony center is approx 6.0 blocks away.

Clicking on any existing building hut results in: "This block is missing its respective building, try restarting or loading a backup!"

Clicking on the town hall:
You are inside Sea City owned by Florianer

You own an existing colony at BlockPos{x=-72, a=52, z=109}.

There is an existing colony you own, delete it before creating a new one.

<Delete own colony> (active button)

<Create new colony> (disabled button)

In the server console I get since I started the server with the updated mods constantly this null ptr exception:

```
[00:12:17] [Server thread/WARN] [minecolonies/]: Condition check for state ACTIVE threw an exception:
java.lang.NullPointerException: Cannot invoke "net.minecraft.network.FriendlyByteBuf.resetReaderIndex()" because "this.visitorBuf" is null
        at com.minecolonies.coremod.network.messages.client.colony.ColonyVisitorViewDataMessage.toBytes(ColonyVisitorViewDataMessage.java:93) ~[minecolonies-1.20.1-1.1.118-BETA.jar%23243!/:1.20.1-1.1.118-BETA] {re:classloading}

```

### Expected Behavior

After the update, the colony should still be owned by me and also the hut should work and the town hall should not tell me to delete an existing colony at the very same location.

### Reproduction Steps

1. Have a server running 1.20.1-1.1.101-BETA.jar
2. create a colony
3. stop the server
4. upgrade to minecolonies-1.20.1-1.1.118-BETA.jar
5. start the server
6. log in
7. see the null pointer exception in the server console and the colony not working

### Logs

https://gist.github.com/Florianer/9f7e61bf638c08563eee85709167b631

### Anything else?

not related, but also found in latest.log:
`[29Aug.2023 00:24:14.492] [Worker-Main-7/ERROR] [net.minecraft.server.packs.resources.SimpleJsonResourceReloadListener/]: Couldn't parse data file minecolonies:recipes/misc/blockhutplantationfield from minecolonies:advancements/recipes/misc/blockhutplantationfield.json
com.google.gson.JsonParseException: java.io.EOFException: End of input at line 1 column 1 path $
`

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Florianer** [comment]
Downgraded the server and the client simply to minecolonies-1.20.1-1.1.117-RELEASE.jar without the need of a backup fixed the behavior.

**Comment by kezmodius** [comment]
Same for me but I am in single player
https://gist.github.com/kezmodius/b9651c390b4c87ffb5462e936ab7b0d8

**Comment by Thodor12** [comment]
Broken after #9315 @someaddons can you look at this?

**Comment by someaddons** [comment]
fixed
