### ISSUE TITLE
1.11.2-0.7.811 localization completely borked

### ISSUE THREAD

**Issue by Konlii** [ldtteam/minecolonies#935]
### Minecolonies version

version 0.7.811

### Expected behavior

- Expected text to be localized.

### Actual behaviour

- All text in the mod shows unlocalized name, prepended with "MISSING:" modid.

### Steps to reproduce the problem

1. Do literally anything that shows text from the mod.
![2017-05-04_13 50 56](https://cloud.githubusercontent.com/assets/11935163/25719945/c0804a30-30d0-11e7-99b8-8f55483630f2.png)

**Comment by Raycoms** [comment]
what language are you playing on?

2017-05-04 15:53 GMT-03:00 Konlii <notifications@github.com>:

**Comment by Konlii** [comment]
en_US

**Comment by marchermans** [comment]
Why is it missing this file again...........
I had to clean the gradle Cache and everytime i do this, the got damn en_US.lang dissappears.
At least that is what i think caused it. I will dig into it tomorrow, i am on my way to bed,

**Comment by Terpo** [comment]
Open the minecolonies.jar with 7zip, extract en_US.lang. Rename the file to en_us.lang. Drag and drop it back in. After a restart / F3+T the localization should be fine.

**Comment by marchermans** [comment]
Oh is it just named wrong....
Weird. Why would the buildsystem name it wrong when i clean its caches but not when i rerun the same build again after the cache cleanup....

**Comment by marvin-bitterlich** [comment]
@Raycoms had that problem.

**Comment by marchermans** [comment]
It seems that sombody renamed the file wrong in git. And it is tracking it wrongly on windows systems.

**Comment by marvin-bitterlich** [comment]
then we need to delete it in one comit and add in a second one

**Comment by Raycoms** [comment]
Should be fixed
