### ISSUE TITLE
[BUG] Mobs spawning inside building bounding box

### ISSUE THREAD

**Issue by kezmodius** [ldtteam/minecolonies#9357]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.1.141

### Structurize Version

1.0.631

### Current Behavior

I've been told that mobs cant spawn inside any building bounding box from level 1 but they are. Lighting is low but shouldn't they be stopped from spawning anyway? I know they will spawn in decos, but this is a proper hut build.
![2023-09-05_11 43 50](https://github.com/ldtteam/minecolonies/assets/120763436/f225146d-063d-470d-8a86-d7861da0aa9c)

### Expected Behavior

Mobs not to spawn inside building bounding box. They are not wandering in from elsewhere as I am underwater and they can't.

### Reproduction Steps

Low light. Mobs spawn inside build.

### Logs

https://gist.github.com/kezmodius/a39b125e9e0b9e1174ded62e28261efc

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Jinotad** [comment]
minecolonies-1.20.1-1.1.195-BETA

Desert style, Barracks.  Leveling the barracks from 2-3.  

Walking by the construction, I could hear spiders. Builder finishes the upgrade, so I dug my way into the barracks (one level 1 barracks tower. No other towers built) and find 2 spiders inside the basement of the barracks.

I can only assume that they managed to spawn in during the digout process of the basement, as you can see that there are glowstones in the floor.  Which must have been covered up for the spiders to have spawned inside.

![2023-10-04_18 47 56](https://github.com/ldtteam/minecolonies/assets/85356635/1c2f6856-c3dc-4ed7-a47d-06d9d9ca558b)

**Comment by Jinotad** [comment]
minecolonies-1.20.1-1.1.247-BETA.jar

Just had the under taker killed inside their hut. There are passageways and ladders as a part of the "tomb" in the Desert Graveyard with no lighting. I'm assuming the undertaker was trying to use them to path a way to deliver the gravestone of a builder that recently died.

![2023-10-21_07 57 22](https://github.com/ldtteam/minecolonies/assets/85356635/2d2d3a88-19c2-4f6b-8823-2631d38f494f)
![2023-10-21_07 58 17](https://github.com/ldtteam/minecolonies/assets/85356635/e78173e8-7d06-400f-ac83-7e80354cb9a1)

**Comment by Jinotad** [comment]
Way to recreate this bug. (

Create a super flat world with dirt all the way up to Y68. Set difficulty to hard, no daylight cycle with sun at daytime.
Create a town hall, claim the town, place Desert Graveyard lvl 3 into world at ground level.

Move far enough away for mobs to spawn inside the graveyard. Change to spectator mode, and look inside.

![2023-10-21_08 23 24](https://github.com/ldtteam/minecolonies/assets/85356635/c0a0cefe-37a1-4c99-babd-d557b9ceb00d)
![2023-10-21_08 27 46](https://github.com/ldtteam/minecolonies/assets/85356635/af6cc116-059c-49d9-bb32-774f08e1154c)

**Comment by Raycoms** [comment]
fixed
