### ISSUE TITLE
[BUG] Forester stops cutting down tree when encountering productive bees nest

### ISSUE THREAD

**Issue by NoMoreStars** [ldtteam/minecolonies#9358]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.1.134-BETA

### Structurize Version

1.0.631-BETA

### Related Mods and their Versions

Productive Bees-1.20.1-12.1.9

### Current Behavior

When attempting to cut down trees grown in the world or naturally generating with a log bee nest from the Productive Bees mod, the Lumberjack stops cutting down the tree and places down a sapling, behaving as if it had finished cutting down the tree.

### Expected Behavior

Lumberjack should cut down the whole tree, the nest included, before placing down a sapling and moving on to the next tree.

### Reproduction Steps

Install Productive Bees mod as well as it's dependencies
Grow saplings in the world, some generating with Bee Nests
Assign a zone to the Lumberjack

### Logs

https://mclo.gs/vpwSNmb

### Anything else?

This bug was encountered while playing the All The Mods 9 mod pack version 0.0.63
A bug report has been sent to the ATM team as well.
Should I also submit a report to the authors of Productive Bees?

**Comment by Raycoms** [comment]
Hmm, the log doesnt tell us anything about forester related issues. Are you sure that this log reflects a time where the forester got stuck?

**Comment by mikevmark** [comment]
> Hmm, the log doesnt tell us anything about forester related issues. Are you sure that this log reflects a time where the forester got stuck?

The Forester doesn't get stuck. He sees the tree, chops the bottom block, but when the Productive Bees nests spawns on the 2nd block up so the tree doesn't 'chop'. He even plants a sapling directly under the Productive Bees Nest. 

Modpack: ATM9 V. 9.0.2.24

**Comment by Raycoms** [comment]
Ahhhh, so the nest is part of the tree trunk

**Comment by mikevmark** [comment]
> Ahhhh, so the nest is part of the tree trunk

Precisely. Now I believe in ATM9 I'm interacting with 2 bugs, yours that the Forester cant harvest trees with the nests, and a productive bees bug where, every single tree that grows from a planted sapling (Spruce is the only one I tired) is generating a nest. The combination of these 2 bugs means the forester has 0% effectiveness for me right now. I set the Spruce Nest spawn rate in productive Bees to 0.0 to work around this issue so now the Forester is working as intended but I can't have Nests of the wood type the Forester would harvest.

**Comment by TheGamekiller** [comment]
> > Ahhhh, so the nest is part of the tree trunk
> 
> Precisely. Now I believe in ATM9 I'm interacting with 2 bugs, yours that the Forester cant harvest trees with the nests, and a productive bees bug where, every single tree that grows from a planted sapling (Spruce is the only one I tired) is generating a nest. The combination of these 2 bugs means the forester has 0% effectiveness for me right now. I set the Spruce Nest spawn rate in productive Bees to 0.0 to work around this issue so now the Forester is working as intended but I can't have Nests of the wood type the Forester would harvest.

I'm having the exact same issue but setting the spawn rate to 0 isn't consistent, it worked after a reboot and then after another it stopped working again. My forester is basically useless and there's a stupid amount of nests and bees...

**Comment by superzero10** [comment]
Found a workaround  in `productivebees.jar` by changing  `data/productivebees/worldgen/configured_feature/acacia_wood_nest.json`
and putting sponge has target bloc

Worked like a charm ! no more nest !

**Comment by Lillemats90** [comment]
having the same issue, though its not really caused by the Minecolonies mod, but it would be great if the forester could recognize the nests as something he or she should remove.

**Comment by Akjosch** [comment]
I'm not playing the pack, so I can't check easily, but did you try adding the nest blocks to `data/minecolonies/tags/blocks/tree.json` via a datapack? You'd have to check in game (via F3, on the right-hand side while looking at the nest) what the IDs are, but they should be something like `"productivebees:oak_wood_nest"`, `"productivebees:spruce_wood_nest"` and so on.

**Comment by Lillemats90** [comment]
i have not tested this yet, but im sure that would be a solution that would be great, then they would harvest them.

**Comment by Devilswarchild** [comment]
> I'm not playing the pack, so I can't check easily, but did you try adding the nest blocks to `data/minecolonies/tags/blocks/tree.json` via a datapack? You'd have to check in game (via F3, on the right-hand side while looking at the nest) what the IDs are, but they should be something like `"productivebees:oak_wood_nest"`, `"productivebees:spruce_wood_nest"` and so on.

im attempting this and the datapack literally has the file path up to tree.json and for whatever reaosn im having difficulties getting the game to load it....

managed to load it and idk if I did something wrong but the forester continues to just ignore the nests

**Comment by puggan** [comment]
same, and searching REI for `$minecolonies:tree` shows the nests.

minecolonies 1.20.2-1.2.647-beta in Technotoens 1.0.10.
guess i just disables productives bees as I don;t use them.
