### ISSUE TITLE
Colonist voices still on even with config set to false

### ISSUE THREAD

**Issue by Raspberrycommie1** [ldtteam/minecolonies#9361]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

1.1.150-BETA

### Structurize Version

1.0.630-RELEASE

### Related Mods and their Versions

1. Forge 43.2.23
2. Domum Ornamentum 1.0.130-BETA

### Current Behavior

After updating to the current version of the mod, colonist voices have turned themselves back on. I've tried relogging and restarting minecraft with no effect. The config file still has colonist voices set to false.

### Expected Behavior

There should have been no voices due to the config being set to false.

### Reproduction Steps

1. Change colonist voices in the config in the /config folder to false
2. Talk to a colonist

Or
1. Update from 1.1.10-ALPHA to current
2. Talk to a colonist

I don't know which one it was but this is what I did

### Logs

https://gist.github.com/Raspberrycommie1/ac2d9247217db099721ae4b0159e48bc

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by KaraSuumei** [comment]
Minecolonies version 1.20.1-1.1.195-BETA

Config setting still does not work.  Set to false, and I still hear colonist voices.

**Comment by Talyda** [comment]
> Config setting still does not work. Set to false, and I still hear colonist voices.

Just to double check, do you actually have the voice pack mod installed? Towntalk?

**Comment by Thodor12** [comment]
I double checked with Towntalk installed as well, it doesn't matter, when I try either of them with the config off, I get no voices (tested with the exact same version as described there, outside of dev env)

**Comment by Akashugo** [comment]
2025 and the button to turn off the voices at the configuration keeps being a decoration. because does nothing at all...

**Comment by Talyda** [comment]
2025 and people still come in complaining vaguely without giving any details...

**Comment by Thodor12** [comment]
This is due to other sound altering mods, we can't do anything about this, please stop complaining

**Comment by Akashugo** [comment]
Thodor12, i have only Minecolonies and required mods at the mod folder, and still happen.
Talyda i don't need give any detail when is the same error/bug that was described up.

But yeah fine don't worry. The usual toxic mod dev interaction after all.
And i had this bug literally from years ago since colonists have voices, earlier than this post first msg date earlier than Minecolonies split onto different mods like Domum, and Town Talk, but i didn't even knew where to ask for help.
np, i will not ask anymore, worthless ask for any help as i see.

**Comment by Talyda** [comment]
> But yeah fine don't worry. The usual toxic mod dev interaction after all.

You were the one that came in with an attitude, I just served back exactly what you gave.

If you want help, ask for it, with details of what version, what other mods, and without a shitty attitude. But if you want to just play victim, yeah, don't ask any more.

**Comment by Thodor12** [comment]
This bug was fixed, I confirmed it myself, so unless you are using an ancient version of Minecolonies which doesn't have the fix, I don't know what you want me to do.

You're not providing a mod version, MC version.

I've locked the post at this time, if you want help create a new issue.
