### ISSUE TITLE
[BUG] Construct buildings in Creative is not registered unless a builder repair it

### ISSUE THREAD

**Issue by pantsguyapp** [ldtteam/minecolonies#9367]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

minecolonies-1.19.2-1.1.150-BETA

### Structurize Version

structurize-1.19.2-1.0.630-RELEASE

### Current Behavior

When I construct a level 5 building in Creative, the building is then constructed but at level 1, not level 5, you can see it as there will be construction tapes around the building, I tried to have the builder repair but when I construct level 5 builder, the same issue happen, and I have to have the builder repair the builder's hut first, then repair the other building. The same goes for other buildings I built, to be registered as a level 5 you need a builder to repair it.
As you can see, the building itself is at level 5, but the guard still request level 1 materials.
![2023-09-10_11 08 24](https://github.com/ldtteam/minecolonies/assets/92203672/8acec732-dcb9-45df-b992-63cfac90b11b)
![2023-09-10_11 08 14](https://github.com/ldtteam/minecolonies/assets/92203672/46a7e4e4-8c85-4da5-af9a-e92de63d4a3a)
![2023-09-10_11 08 17](https://github.com/ldtteam/minecolonies/assets/92203672/61797e92-1dd2-4e0c-a3ba-7e126e8da56d)

### Expected Behavior

Level 5 buildings can be placed willy nilly in Creative, without having to go through all the survival steps.

### Reproduction Steps

Provided above.

### Logs

https://www.kretzlumber.com/wp-content/uploads/2022/01/Red-Oak-big-diameter-1.jpg

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Just paste the building at level 5 directly? Or paste at level 4 to do the last upgrade step?

**Comment by pantsguyapp** [comment]
Paste level 5 directly

**Comment by Raycoms** [comment]
"minimal level wood or gold" doesnt say, maximum level wood or gold

**Comment by pantsguyapp** [comment]
But still, the guard refuses to use the diamond sword I placed in the inventory until I repaired the building.
