### ISSUE TITLE
Racks not connecting when builder places them down

### ISSUE THREAD

**Issue by RenRants** [ldtteam/minecolonies#9368]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.20.1-1.1.137

### Structurize Version

1.20.1-1.0.631-BETA

### Related Mods and their Versions

1. Forge Version: 47.1.3
2. BlockUI Version: 1.20-0.0.84-APLHA
3. Domum Ornamentum Version: 1.20-1.0.110
![2023-09-10_12 05 46](https://github.com/ldtteam/minecolonies/assets/143908552/761a10a7-402b-4bd7-bb6f-287fdc6ae8ce)

### Current Behavior

Racks and Chests not connecting and turning into double racks when builder places them down.

I am using the Nordic build style.

### Expected Behavior

Racks should connect into double racks

### Reproduction Steps

1. Have the builder build any building that should create a double rack (I.E. Warehouse)

### Logs

https://pastebin.com/4JRMNsTR

**Comment by Raycoms** [comment]
That was intended by the designer

**Comment by Sandriell** [comment]
Wasn't like that in 1.16.5 for the Nordic style.

I have had the same issue using the Medieval Spruce style with the racks not connecting in 1.19.2.

**Comment by MotionlessTrain** [comment]
There were some changes to how racks connect, which unfortunately corrupted a lot of racks in existing blueprints (looking invisible, rotated in the wrong direction, glitching through other blocks). I found a way to mass fix the glitching racks, with the caveat that some of the glitched racks are now single.
 This was the best I could get it without fixing thousands of schematics manually. It is up tot the style designer to change/correct those single racks again if they so wish
