### ISSUE TITLE
[BUG] Vine Lassoo against Minecolonies Mob = Crash

### ISSUE THREAD

**Issue by DoctorMage** [ldtteam/minecolonies#9369]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [X] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

minecolonies-1.19.2-1.1.151-BETA.jar

### Structurize Version

structurize-1.19.2-1.0.630-RELEASE.jar

### Related Mods and their Versions

Forge:43.2.23
multipiston-1.19.2-1.2.21-ALPHA.jar
domum_ornamentum-1.19-1.0.107-RELEASE-universal.jar
citadel-2.1.4-1.19.jar
blockui-1.19-0.0.69-ALPHA.jar
alexsmobs-1.21.1.jar

### Current Behavior

Using a lasso on a minecolonies mob will cause a ticking entity crash

### Expected Behavior

Lasso acts as lead on mob

### Reproduction Steps

1. Equip vine lasso.
2. Wind it up.
3. Have it land on minecolonies mob

### Logs

https://gist.github.com/DoctorMage/0fad43d34a7b3169c0790a06fa9f47f8

### Anything else?

was told to report it here https://github.com/AlexModGuy/AlexsMobs/issues/1791

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Is there a tag to opt out of this? Because ye, dont lasso citizens

**Comment by Nightenom** [comment]
My 2 cents: I would say it their bug as you should not (ideally?) call Entity#moveTo on client side? especially when doing serverside logic. But we should not crash cuz of it anyway

**Comment by uecasm** [comment]
I don't think there's any inherent reason not to call `Entity#moveTo` on client side.  It's non-authoritative (server position will "win" on resync) but calling it on both sides is more efficient / less latency, particularly for teleportation-style movement.

Calling `PathNavigation#moveTo` on client side is weirder, though, and probably shouldn't be happening.  The related vanilla reference is `#tickLeash`, which is only called server side.

So yes, this looks like mostly their bug.
