### ISSUE TITLE
stonemason and sawmill never building anything

### ISSUE THREAD

**Issue by jadebullfrog** [ldtteam/minecolonies#9374]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [X] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.20.1-1.1.13

### Structurize Version

1.20.1-1.0.631

### Related Mods and their Versions

forge 47.1.1

![Screenshot 2023-09-13 213058](https://github.com/ldtteam/minecolonies/assets/144971789/b6010129-9b76-4039-835a-a2001ad79895)

![Screenshot 2023-09-13 213115](https://github.com/ldtteam/minecolonies/assets/144971789/3cf1f3e5-c585-414d-aca7-66db3d90e85a)

![Screenshot 2023-09-13 213123](https://github.com/ldtteam/minecolonies/assets/144971789/8e279e65-deb6-47f2-a7d2-85b0cf26f0a5)

![Screenshot 2023-09-13 213204](https://github.com/ldtteam/minecolonies/assets/144971789/a743bcab-1e34-40e9-84a4-31f537903486)

![Screenshot 2023-09-13 213209](https://github.com/ldtteam/minecolonies/assets/144971789/00c4630b-a2f2-41d4-8f4e-bbc0c3d49499)

![Screenshot 2023-09-13 213135](https://github.com/ldtteam/minecolonies/assets/144971789/c8d9bbb7-425c-476f-a56c-6df9cd99ae03)

![Screenshot 2023-09-13 213158](https://github.com/ldtteam/minecolonies/assets/144971789/539dedc6-c3c0-4cbc-9bc3-4c94fabf7aa7)

![Screenshot 2023-09-13 213129](https://github.com/ldtteam/minecolonies/assets/144971789/7f247670-f00b-42e9-999f-9d0159071f05)

### Current Behavior

my builder will request something to be crafted from the sawmill or stonemason and they never do anything. i have the materials in the warehouse and people to bring it to them. I've seen others complain about it for about 3 years now. 

### Expected Behavior

for my sawmill and stonemason to request the blocks they need to craft. but they don't request anything. i teached them how to make stuff but they still don't do anything.

### Reproduction Steps

just develop ur town normally and set the sawmill and stonemason the way it should

### Logs

https://gist.github.com/jadebullfrog/0a4acc8ccea7b8dd83e6b7c19a7a1dde

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
Is the builder actually currently requesting the items, or are they just appearing on the required resources list? Check on the builder (person) their requests tab.
And did you teach the stonemason/sawmill after the requests were made? In that case, cancel their request and have them re-request the items. Also make sure that you are requesting exactly the right items, hover your mouse over the request, and the items you taught, and make sure that way.
Easier to help troubleshoot on discord BTW

**Comment by jadebullfrog** [comment]
yah her request tab is always empty occasionally shes is able to request items from the warehouse but sometimes she wouldn't request them even though i know there's that item in the warehouse. I've never seen her requesting anything from the sawmill or stonemason though. ill be in the discord my name is JADEDBULLFROG

**Comment by Raycoms** [comment]
Are there requests assigned to the player in the clipboard then?

**Comment by jadebullfrog** [comment]
my name is jadedbullfrog in the discord

**Comment by jadebullfrog** [comment]
nope nothing on the clipboard about them

**Comment by jadebullfrog** [comment]
im not sure if im the few people experiencing this but here's a reddit of other people experiencing this too https://www.reddit.com/r/Minecolonies/comments/lijs8y/sawmill_not_getting_crafting_requests/

**Comment by Talyda** [comment]
That was 2 years ago.

Please go ask the question on discord, then we can ask you other things to try and troubleshoot
https://discord.minecolonies.com

**Comment by Raycoms** [comment]
If nothing shows up on the clipboard, this means your builder is not requesting anything at all. They dont request everything at once, but only items once they are getting close to needing them, in the order they will need them. (Thats more efficient actually). The UI in the building shows them already ahead of time (all at once). So you are fulfilling things before they can ever reach the sawmill or stonemason
