### ISSUE TITLE
[BUG] Minecraft either locks or crashes immediately after world load

### ISSUE THREAD

**Issue by vincentreynolds** [ldtteam/minecolonies#9376]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

1.1.151-BETA

### Structurize Version

1.0.630-RELEASE

### Related Mods and their Versions

1. Forge version: 43.2.23 (also tried 43.1.47)
2. BlockUI version: 0.0.69-ALPHA
3. Domum Ornamentum version: 1.0.130-BETA
4. MultiPiston version: 1.2.25-ALPHA

### Current Behavior

Loaded a save that has consistently worked before. Immediately after loading, Minecraft locks—no cursor movement, no sound. After a period of time, it either crashes or must be Force Quit. Tried with Forge, but no mods, and it did not crash. Added only minecolonies, structurize, domumornamentum, blockui, and multipiston, and the crash reappears.

### Expected Behavior

I expect it not to crash.

### Reproduction Steps

1. Load the specific save. (It is obviously something in this save that is triggering the error.)

This description seems inadequate, but the error requires no user interaction beyond loading the save. The save is a bit over 1GB zipped, but I can supply it if it would help the diagnostic process.

### Logs

https://gist.github.com/vincentreynolds/ef5751c33b1075b848d1bc208ba192a2

### Anything else?

The "latest.log" file is also available at: [latest.log](https://gist.github.com/vincentreynolds/fd73571dae3c2b39cbfbc1bad0f0d712)

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by someaddons** [comment]
would be nice if you could upload the save somewhere, it'd be helpful to track the source of this :)

**Comment by vincentreynolds** [comment]
Agreed. Just uploaded the save folder to OneDrive. Link is: https://1drv.ms/u/s!AtZaEtT_5SDBkgGpft9WqXp_Ivl_?e=cLm3FC

**Comment by someaddons** [comment]
I made a fix for the AI error in your log, at least for me your world does not lock up on load in dev(though may be fixed by the AI thing I changed, not 100%)
