### ISSUE TITLE
[BUG] Exit game when trying to add min stock to the Restaurant

### ISSUE THREAD

**Issue by JeanLuisJimenez** [ldtteam/minecolonies#9379]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

minecolonies-1.20.1-1.1.159-BETA

### Structurize Version

structurize-1.20.1-1.0.631-BETA

### Related Mods and their Versions

Domun Ornamental: 1.0.129 BETA
Forge: 47.1.3
Block UI: 0.0.84 ALPHA

### Current Behavior

On the Restaurant block UI > Min Stock tab, if you click the add button the game will break and exit.

### Expected Behavior

On the Restaurant block UI > Min Stock tab, if you click the add button it should open the option to search for the item you want to add for min storage.

### Reproduction Steps

1. Set a Restaurant Block.
2. Right-click on it.
3. Go to the Min Stock tab.
4. Click the add button.

### Logs

https://gist.github.com/JeanLuisJimenez/e04b78e0349f5c5546151504f9a9abce

### Anything else?

![Screenshot 2023-09-16 at 11 54 51 PM](https://github.com/ldtteam/minecolonies/assets/45690922/5414f9db-b4e0-4e09-b2f4-dc0528c9cd5c)

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by JeanLuisJimenez** [comment]
Also does happen in the latest RELEASE version (1.1.137), and there are no ALPHA versions of this mod at TLauncher

**Comment by Talyda** [comment]
Do you own minecraft? Tlauncher is a really bad launcher to use

**Comment by Raycoms** [comment]
Problem on side of: 	at untamedwilds.util.EntityDataHolder.getName(EntityDataHolder.java:87) ~[untamedwilds-4.0.0.jar%23208!/:4.0.0]
