### ISSUE TITLE
[BUG] NPCs voices still enabled even after disabling in config

### ISSUE THREAD

**Issue by SkylordManga** [ldtteam/minecolonies#9382]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [X] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

1.1.116

### Structurize Version

1.0.630

### Related Mods and their Versions

Forge: 43.2.21

Domum Ornamentum: 1.0.107

### Current Behavior

Edited the client config to disable citizen voices, but after saving the file and relaunching the game, the citizens still would speak when clicking on them. 

### Expected Behavior

No voices

### Reproduction Steps

currently running the LunaPixelStudios Medieval MC for Forge 1.19.2. Only edits to the pack that I've done is remove ToughAsNails. 

The mod's(minecolonies) configs have only been edited in the client settings to diable voices.

### Logs

[latest.log](https://github.com/ldtteam/minecolonies/files/12644198/latest.log)

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.
[latest.log](https://github.com/ldtteam/minecolonies/files/12644198/latest.log)

**Comment by Raycoms** [comment]
duplicate
