### ISSUE TITLE
Language X translation missing

### ISSUE THREAD

**Issue by ghost** [ldtteam/minecolonies#939]
![123](https://cloud.githubusercontent.com/assets/24831406/25743655/15431246-319e-11e7-803d-8fa7cc74a0ce.PNG)
using forge 2294, minecolonies-universal-1.11.2-0.7.811

**Comment by marvin-bitterlich** [comment]
What language are you using?

**Comment by ghost** [comment]
![232](https://cloud.githubusercontent.com/assets/24831406/25743835/1e599dd6-319f-11e7-8670-1ab97917cd84.PNG)
didn't touch anything in options, i just updated minecolonies mod.

**Comment by ghost** [comment]
i'm using an argument which is this:
![23](https://cloud.githubusercontent.com/assets/24831406/25744130/e739a894-31a0-11e7-82f3-0194b73f4775.PNG)
can it effect it?
btw, if i don't use this, most of the mods or apps that runs with java won't work.

**Comment by marchermans** [comment]
It seems that because I cleared gradles Caches, it does not add the Standard en_US.lang file to the jar
And i have no idea why :(

**Comment by marchermans** [comment]
Ones a build is ran it will add it again though.

**Comment by ghost** [comment]
then what should i do? i tried reinstalling my modpack 5 times, and tried deleting configs, even restarting my pc, etc.

**Comment by ghost** [comment]
oh, let me try the latest build.

**Comment by ghost** [comment]
okay, build 832 works fine.

**Comment by ghost** [comment]
uhm, but now; another bug: no citizen spawn

**Comment by ghost** [comment]
waiting for 5 mins but still no citizens, i think it's more than 5 mins

**Comment by ghost** [comment]
omg, they just spawned after about 15 mins

**Comment by marchermans** [comment]
:P Yeah it is funny with that file. It does not delete it when clean was not run ......

**Comment by ghost** [comment]
aaaaand just another bug, my builder wanted an axe from me, (wood or gold) and i gave him a wooden axe but he still wants.

**Comment by marchermans** [comment]
Yeah there are some Problems with inventories, right now. We are on it to fix them. But that one is new. Where did you gave it to him?

**Comment by ghost** [comment]
what u mean with where ?i gave it in my townhall

**Comment by marchermans** [comment]
Townhall will not work.
You will need to either give it to him directly, by opening up his UI and clicking the inventory button.
Or put it in his Building chest. The townhall is not being checked on purpose.

**Comment by ghost** [comment]
what? i already placed the wooden axe in his inventory, but i did it in townhall. so i must do it out of townhall? please fix this :( it's not sensible

**Comment by ghost** [comment]
oh, sorry. i gave the axe to the wrong citizen. it works. but i did it in builder's hut.

**Comment by ghost** [comment]
and i want to ask a question, why the builder is far away from the build? he looks like a crazy :D he's just hitting the air but something is happening in build area. why doesn't he come to the build area?

**Comment by xavierh** [comment]
It is to prevent him to suffocate when building
