### ISSUE TITLE
[BUG] Issue with Death Messages

### ISSUE THREAD

**Issue by Sandriell** [ldtteam/minecolonies#9402]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

1.19.2-1.1.162-BETA

### Structurize Version

1.19.2-1.0.630-RELEASE

### Current Behavior

Death messages are showing up like:

"death.attack.death.attack.entity.minecolonies.shieldmaiden! Their death position is -811 72 -2081."

Was a Knight that died to a Shield Maiden.

### Expected Behavior

Readable messages

### Reproduction Steps

1. Have citizen.
2. Murder!

### Logs

N/A

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
This may be specific to the amazons. They may be missing death messages (other message may look fine)
