### ISSUE TITLE
Unable to access builder's inventory

### ISSUE THREAD

**Issue by Spleenczar** [ldtteam/minecolonies#942]
### Minecolonies version

version X.X.XXXX or curse X.X.XX

### Expected behavior

- Opening the builder's inventory

### Actual behaviour

- Nothing happens when clicking the "Inventory" button

### Steps to reproduce the problem

1. Make a new colony
2. Make a builder's hut
3. Hire a builder
4. Try and access their inventory

I have not tried this with other colonists because I have just started using the mod and it's all I have - Not sure if this problem applies to other worker types. The builder can still take resources from the hut though.

**Comment by Raycoms** [comment]
Can you deliver us more information?
Multi or single-player?
Are you using other mods?
Can you send us your log files?

**Comment by marvin-bitterlich** [comment]
closing for now as missing infos
