### ISSUE TITLE
[BUG] Crashing upon attempting to place townhall block

### ISSUE THREAD

**Issue by TheGecks** [ldtteam/minecolonies#9420]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.1.192-beta

### Structurize Version

1.0.648-beta

### Related Mods and their Versions

1. Forge Version: 47.2.1
2. Domum: 1.0.133-beta.
3. Blockui: 0.0.94-alpha

### Current Behavior

Server crashing when attempting to place the townhall block. I use the build tool and can preview the build but when I click the checkmark it crashes (attempted with both the desert oasis and the urban savannah styles)

### Expected Behavior

The townhall block places and can be interacted with

### Reproduction Steps

1. Use the build tool to place the townhall block
2. Preview the build and adjust placement
3. Click the checkmark to place the townhall block

### Logs

https://gist.github.com/TheGecks/b1e4785b40521896eac8d9e9f1fcf65f

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
I cannot reproduce this crash on newer versions, please tell ATM they would have to update Minecolonies
