### ISSUE TITLE
[BUG] [1.19.2] Fireworks At Building Completion Can Break Things

### ISSUE THREAD

**Issue by Sandriell** [ldtteam/minecolonies#9427]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

1.19.2-1.1.194-BETA

### Structurize Version

1.19.2-1.0.649-BETA

### Related Mods and their Versions

Forge: 43.2.21

### Current Behavior

When a building completes that is in a confined space, the fireworks can cause some blocks to break. In a custom build of mine they are destroying the armor stand, which doesn't even drop when destroyed- making the situation more annoying.

### Expected Behavior

Fireworks not to break blocks.

Perhaps, if possible, they should be a visual-only effect rather than using real fireworks?

Otherwise a way to disable the fireworks would be nice.

### Reproduction Steps

1. Build a building (in my case it is a small custom guard tower made to go in a much larger build).
2. When completed the fireworks go off, destroying the armor stand that is part of the build.

### Logs

N/A

### Anything else?

Screenshot of the custom guard tower:
![2023-10-02_23 42 32](https://github.com/ldtteam/minecolonies/assets/10704907/2681a311-bafc-41dc-b2de-e06c5c581600)

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
Note: fireworks cannot break blocks. It can however damage entities, which is why the armour stand broke (armour stands and item frames are entities)

I have seen one time before that someone shared that their builder died because the firework (which wasn't reported as bug, just as something funny that happened)
