### ISSUE TITLE
[BUG/Compatibility Issue] Minecolonies/Alex's Mobs lasso problem. Was Told to report it here from the Discord.

### ISSUE THREAD

**Issue by Silversky13** [ldtteam/minecolonies#9429]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.1.195

### Structurize Version

1.0.648

### Related Mods and their Versions

1. Forge 47.1.1
2. blockui 0.0.84
3. domum 1.0.110
4. Alex's Mobs 1.22.6
5. Citadel (Alex's Library) 2.4.4-1.20.1

### Current Behavior

If you combine Minecolonies with Alex's Mobs and use a Vine Lasso from Alex's Mobs on a colonist it will crash the game instantly and corrupt all data for the world.

I was told to report this here by a mod on the discord because there is a discrepancy on which side this is on. 
3 weeks ago this report was generated on the minecolonies github for the same issue https://github.com/ldtteam/minecolonies/issues/9369

He/she was referred to Alex's Mobs to have it fixed on their end. However, Alex claims that it is actually on Minecolonies side and closed that bug report without fixing it as seen here. https://github.com/AlexModGuy/AlexsMobs/issues/1791

It might require some amount of communication between the mod teams for both mods to resolve it. 
I have attached a log of the crash as well if that helps. 

any help on it would be greatly appreciated.

### Expected Behavior

I don't think the lasso should even work on colonists at all to be fair, but I can see someone trying it regardless because they can. Both mods are very popular so I'm sure this will be a recurring issue. Honestly, if the lasso could just be made to not interact with the colonists at all or the colonists made to ignore the lasso somehow it would probably fix the problem completely.

### Reproduction Steps

1. Get Lasso and right click to use it.
2. Target colonist and throw lasso.
3. Game crashes and world data is corrupted from ticking entity error.

### Logs

https://gist.github.com/Silversky13/e8e1da4623dca4306d1f6727c55d7621

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
Do note that one of our developers has already commented in that thread stating it's an issue on their end, not ours.

**Comment by MotionlessTrain** [comment]
@Thodor12 I asked them to report in on github (actually as a comment of #9369), to mention than Alex's devs apparently think it is on Minecolonies' side, so that there could hopefully be communication between the dev teams of both mods to sort out whose issue it actually is. Having both mentioning that it is an issue on the other's side, so that it never gets solved doesn't help at all

**Comment by Thodor12** [comment]
It's a duplicate of #9369 anyway
