### ISSUE TITLE
[BUG] [1.19.2] Packet Error with Forester/Lumberjack Scepter

### ISSUE THREAD

**Issue by Sandriell** [ldtteam/minecolonies#9432]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

1.19.2-1.1.194-BETA

### Structurize Version

1.19.2-1.0.649-BETA

### Related Mods and their Versions

Forge: 43.2.21

### Current Behavior

Get the following errors on the server when using the Forester/Lumberjack Scepter to define a zone.

https://gist.github.com/Sandriell/a99954b2164d35becef3a5e04ba7cdf0

Despite the errors though, it does appear to be working.

### Expected Behavior

No errors

### Reproduction Steps

Use the Scepter to define a zone for the Forester to work in.

### Logs

https://gist.github.com/Sandriell/a99954b2164d35becef3a5e04ba7cdf0

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
If that error happens it means that while the box might be visibly updating, it's not being saved properly on the server, so it won't actually work.  You can verify this by throwing away your scepter and getting another one and seeing if it shows the box you tried to set or not.

If the error does stop happening then it should never happen again for that particular forester building, though.  Failing that, a fix is on the way.
