### ISSUE TITLE
[BUG] NPCs are not spawning.

### ISSUE THREAD

**Issue by rafasrns** [ldtteam/minecolonies#9436]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

minecolonies-1.19.2-1.1.170-RELEASE.jar

### Structurize Version

structurize-1.19.2-1.0.650-RELEASE.jar

### Current Behavior

NPCs are not spawning in villages or with eggs. When spawned with eggs they appear and disappear at the same time.

### Expected Behavior

NPCs should spawn normally around the world and with egg spawns.

### Reproduction Steps

1. Create a world.
2. Pick an egg from any mob of Mine Colonies Mod.
3. Try to spawn it.

### Logs

https://gist.github.com/rafasrns/ad071a493cce8957780577c84fe22040

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
There are no citizens in abandoned colonies, if that is what you mean.
That is currently intended.
Also which spawn egg do you mean? Citizens don't have a spawn egg, just raiders (which cannot be spawned outside of a raid)

**Comment by rafasrns** [comment]
> There are no citizens in abandoned colonies, if that is what you mean. That is currently intended. Also which spawn egg do you mean? Citizens don't have a spawn egg, just raiders (which cannot be spawned outside of a raid)

I found an unabandoned colony (it didnt have cobwebs), and even so there were no NPCs, but if Im really wrong, please tell me what is the command to locate an inhabited colony

**Comment by MotionlessTrain** [comment]
There are no world generated colonies with citizens, as of yet. The only world generated structures Minecolonies adds are abandoned colonies

**Comment by rafasrns** [comment]
> There are no world generated colonies with citizens, as of yet. The only world generated structures Minecolonies adds are abandoned colonies

Oh sorry and thx, I was sure the mod added NPCs around the world. I'll delete the post.
