### ISSUE TITLE
Fisherman blocks Lure when trying to fish.

### ISSUE THREAD

**Issue by BinarySavage** [ldtteam/minecolonies#944]
### Minecolonies version

Minecolonies version 1.10.2-0.7.776
Modpack verion 0.8.3

### Expected behavior

- Lure to ignore fisherman collision when casting

### Actual behaviour

- Lure collides with fisherman and is cast into fisherman's body.

### Steps to reproduce the problem

1. Build Fisherman Hut
2. Assign Villager
3. Provide with fishing rod
4. Wait for Fisherman to approach water and attempt to cast.

First noticed it on SMP server a verified that it also occurred on SSP.
![fishermanlurestuck](https://cloud.githubusercontent.com/assets/17791959/25767825/cda6e9da-31ca-11e7-86a9-1e4dfe280217.png)

**Comment by Raycoms** [comment]
Found bug, removed. Will be fixed in next version.

**Comment by marvin-bitterlich** [comment]
fixed
