### ISSUE TITLE
[BUG] [1.19.2][rubidium] Latest versions broke rendering during structure placement preview

### ISSUE THREAD

**Issue by vgrynch** [ldtteam/minecolonies#9441]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [X] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

1.19.2-1.1.197-BETA

### Structurize Version

1.19.2-1.0.652-BETA

### Related Mods and their Versions

rubidium-mc1.19.2-0.6.2c (or a few previous for 1.19.2, also embeddium has the same behavior)

blockui-1.19-0.0.69-ALPHA
domum_ornamentum-1.19-1.0.135-BETA-universal
minecolonies-1.19.2-1.1.197-BETA
structurize-1.19.2-1.0.652-BETA

### Current Behavior

When entering the structure preview mode, textures of non-block items (grass, railways, flowers, etc.) are displayed incorrectly. Reproduces clearly with only 5 mods listed above. When removing rubidium, everything is good. With Oculus, it is corrupted too according to other reports (I did not try it myself).
No errors in the logs.
This did not happen when I tried a similar mods pack about 6 months ago. This also reproduces in minecolonies-1.19.2-1.1.184-BETA, did not try other versions, but it's quick and easy to try out and reproduce on a clean install with just 5 mods.

There is an open issue for rubidium as well: https://github.com/Asek3/Rubidium/issues/521

### Expected Behavior

Non-block stuff rendered correctly with rubidium.

### Reproduction Steps

1. Create a new Forge profile with these mods:
rubidium-mc1.19.2-0.6.2c
blockui-1.19-0.0.69-ALPHA
domum_ornamentum-1.19-1.0.135-BETA-universal
minecolonies-1.19.2-1.1.197-BETA
structurize-1.19.2-1.0.652-BETA
2. Create a new world and try to place some structure
3. Observe rendering issues as on the screenshot during the structure placement preview.

### Logs

No errors in logs

### Anything else?

![image](https://github.com/ldtteam/minecolonies/assets/46818018/8bdd5dd5-c17f-4d05-94e8-9fde31652b91)

**Comment by Talyda** [comment]
It's not just on the latest versions, It's something to do with rubidium, and not all people experience it. 
Not minecolonies related judging from the multiple reports, and the fact that removing rubidium solves it

**Comment by vgrynch** [comment]
Too many people are using Rubidium to simply ignore this. 
Rubidium is a graphical engine mod used really widely. 
Your mod is very complex. I doubt Rubidium devs would fix this quickly by themselves without knowing Minecolonies sources. You can try and cooperate with them on this - they are quite open to this, I saw a few mods were fixed by them instead of fixing Rubidium.

**Comment by Raycoms** [comment]
It worked fine for a couple of versions of Rubidium, they changed sth on their side, they most likely would have to fix.

**Comment by Thodor12** [comment]
Also do note that we do not build our mod around Rubidium, we have to do certain things to make those preview work.
If Rubidium doesn't like that then that is not our fault, we can't go without this preview system. Considering that we don't officially support Rubidium, and the fact that it's only a graphical issue, this is a wontfix.

If mod compatability problems cause literal crashes to desktop then we look at them.
