### ISSUE TITLE
[BUG] Alchemist things (Ray told me to!)

### ISSUE THREAD

**Issue by Talyda** [ldtteam/minecolonies#9455]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

minecolonies-1.20.1-1.1.195-BETA

### Structurize Version

structurize-1.20.1-1.0.648-BETA

### Current Behavior

Alchemist seems to not collect mistletoe fast enough

### Expected Behavior

Alchemist would have enough

### Reproduction Steps

Have alchemist

### Logs

https://gist.github.com/Talyda/46950cbdc27d8bae33838f3494da3c93

### Anything else?

Don't ask me for logs! Server is kicked me for being afk now cos I needed to put a log or it wouldn't let me make the issue =P

**Comment by Raycoms** [comment]
I wanna check if there are some things preventing the alchemist from collecting in general.

**Comment by kezmodius** [comment]
I suspect our alchemist is not working correctly at all. I requested potions and they have never arrived (real time over a week). I taught him all the recipes. He had all the ingredients. I gave him blaze powder. I put the blaze powder in his brew stands. Still did not receive potions.
![2023-10-12_19 20 36](https://github.com/ldtteam/minecolonies/assets/120763436/b71a938b-0e59-4eeb-a3f9-cad07b1afce7)
![2023-10-12_19 20 22](https://github.com/ldtteam/minecolonies/assets/120763436/6bc2c35d-e22e-47eb-b4c0-5dc03b354326)

Plus, apart from the collecting, he does not seem to be working on one request at a time. 20 druids request potions at once. He seems to be waiting for all the ingredients for 20 requests before doing one request. It clogs up the courier system too.
![2023-10-12_19 10 07](https://github.com/ldtteam/minecolonies/assets/120763436/45456a3f-691e-4ac3-92f5-6432dcd3e3db)
![2023-10-12_19 10 32](https://github.com/ldtteam/minecolonies/assets/120763436/b57eb754-d17b-459f-bebf-4e3da8fc5f64)
![2023-10-12_19 10 43](https://github.com/ldtteam/minecolonies/assets/120763436/5a53c432-bee1-4f1d-b1f1-dd8e5c83ba72)
o.

**Comment by zendarsf** [comment]
one thing i noticed in my word i am using fortress style but the Alchemist hut puts dark oak leaves down. jei says mistletoe needs oak leaves. i changed the dark oak leaves to oak leaves and he started collecting mistletoe.

**Comment by Jinotad** [comment]
Minecolonies 1.20.1-1.1.661-snapshot-universal

Was testing the Alchemist using a lvl 1 Nordic, and a lvl 5 Nordic. After waiting 1 hour, both only produced 2 mistletoe.  I suppose that may be due to their stats. level one had all 1's, and the level five had all 3's  But it still feels really low, if they are not at least getting one mistletoe a day. Especially considering how fast a druid can throw potions.

**Comment by Jinotad** [comment]
Did some more testing with a lvl 5 alchemist who has 50 in all stats. They started with 64 netherwart and a shears.

At about 2 hours.  They had 6 mistletoe, 62 netherwart in their hut, and 5 planted on soul sand. At about 3 hours they only had 10 mistletoe. 

So I'd say its safe to assume that it's on a set income, and not based on worker's stats at all.

**Comment by Raycoms** [comment]
fixed
