### ISSUE TITLE
Warehouses griefed by staff member/s on Server

### ISSUE THREAD

**Issue by rexrapter1234** [ldtteam/minecolonies#946]
I joined the server to today just to founded out that 3 out of 6 of my Warehouses have been griefed by staff member/s. They are complaining about lag on the server and have decided to fix the lag by destroying players hard work. It took me over 2 weeks to build my Warehouses which took me a long time to build. As a Player I like helping will the bugs, when I find them, but it's going to make it very hard to play on the server and test if I have to rebuild my buildings each time one or more staff members decides to fix the lag on the server by griefing player's towns. I'll probably have to rebuild the my griefed Warehouses now ;(.

**Comment by Raycoms** [comment]
Hey there rexrapter,

Luckily I didn't see all 6 or I would've destroyed 5 of them.
On our wiki it says there is supposed to be 1 Warehouse each player.

6 warehouses need the resources of the whole server.
So basically 90% of the cpu and memory just go to your colony.

Please be considerade and see that its kinda selfish to require 6 warehouses for your little colony.
That's way more than 1 player needs.

Your colony brought down the server to its knees and I had to destroy 3 of the warehouses.
Please remove 2 more.

In one of the upcoming updates I will restrict it completely to 1 warehouse each colony on the server.
I thought people would follow the guidelines but if it doesn't work I'll have to do this.

**Comment by rexrapter1234** [comment]
1. No I haven't read the wiki, as I've played this mod back in 1.7.7 Minecraft beta. I'll change it to one.

2. These not posted to use 90% of cpu of the server, there only buildings. why would they be set to use high cpu ? That is very weird.

3. Well I not trying to use 90% of the server's resources. I think one warehouse is to small that is why I made more of them.

4. Okay will do. Can I add chests and trap chests to one of my warehouses ? Will the delivery man use them ?

**Comment by Raycoms** [comment]
Because the warehouse has to do the calculation which items the deliveryman
can deliver.
So 6 warehouses calculating if they can deliver food to the citizen

2017-05-06 11:00 GMT-03:00 rexrapter1234 <notifications@github.com>:

**Comment by rexrapter1234** [comment]
Ok that makes sense.

If I add more chests (chests and trap chests) in the warehouse and by digging down and making the building taller, would the delivery man use the new chests ?

**Comment by marchermans** [comment]
No, only chests placed by builders are regocnized.

**Comment by rexrapter1234** [comment]
oh ok

**Comment by marvin-bitterlich** [comment]
@rexrapter1234 I am closing this for now. Please open up separate issues for other problems.

We had initially planned and said that only one warehouse per colony was allowed (because of heavy CPU usage) and will now enforce this n the mod.

We are sorry you lost some work but we had to deactivate your warehouses as they used up too much server resources. With a game as complex as minecraft this is really easy to do. And players have to be careful how they design their things to not strain the server too much.
