### ISSUE TITLE
[BUG] Raids don't respect the minimumnumberofnightsbetweenraids option

### ISSUE THREAD

**Issue by MotionlessTrain** [ldtteam/minecolonies#9465]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

1.1.230

### Structurize Version

1.0.652

### Related Mods and their Versions

Forge 43.2.0
BlockUI 0.0.92
DO 1.0.137

### Current Behavior

Two days after a raid starts, the next raid starts.
In one case for me, it almost looked like a raid got aborted, so that the next raid could start 2 minutes later (and the citizens had three days free of work)
I another case, after a few pirates slaughtered 5 of my guards, I had basically one day to clean up the graves, loot the pirate ship, hire visitors to fill back the empty guard spots, and give them the materials needed to actually be able to work

### Expected Behavior

After a raid ends, the next raid starts in on average `averagenumberofnightsbetweenraids` days, and at least `minimumnumberofnightsbetweenraids` days.

### Reproduction Steps

1. Have a colony which is developed enough to get raided automatically
2. Let raids spawn naturally
3. After getting rid of the raid, wait a couple of days for the next raid

### Logs

https://gist.github.com/MotionlessTrain/0c15aed77a6fc9e3f20356a8dd91a0a2

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by OlofTheBald** [comment]
I've had to completely turn off raids for now (in `serverconfig/minecolonies-server.toml`) because of this issue:

`dobarbariansspawn = false`

**Comment by Raycoms** [comment]
fixed

**Comment by MotionlessTrain** [comment]
If you mean that it got fixed by https://github.com/ldtteam/minecolonies/commit/9474d7d74c99646fb628f342b9ea8f3126e7df63, then I'm not sure how that would work
From a discord report, it seems that 1.1.232 still has the issue (though I haven't had the time yet to verify that)

**Comment by Raycoms** [comment]
That bug stopped the "night processing" for a lot of colonies, which can cause repetitive raids

**Comment by MotionlessTrain** [comment]
I still have the same issue on 1.1.232 as well

**Comment by someaddons** [comment]
post the new latest.log then

**Comment by MotionlessTrain** [comment]
https://gist.github.com/MotionlessTrain/5f59a28968661cffb843f1c585e4c0bb

**Comment by MotionlessTrain** [comment]
I tried to restart the game as well, just in hope that would help (^ that log is from before the restart), but that doesn't seem to help

**Comment by someaddons** [comment]
was helpful to confirm that the other bug is fixed^^

**Comment by MotionlessTrain** [comment]
I actually didn't know about that other bug.
I did read the first log a little bit, but apparently not enough to see that that error 😄
Glad to help with that as well!
