### ISSUE TITLE
Raids will not spawn

### ISSUE THREAD

**Issue by sh09700** [ldtteam/minecolonies#9469]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [X] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

minecolonies-1.19.2-1.1.235-BETA

### Structurize Version

structurize-1.19.2-1.0.649-BETA

### Related Mods and their Versions

I play on direwolf 20 1.19 1.12.0 but i manually added minecolonies-1.19.2-1.1.235-BETA and structurize-1.19.2-1.0.649-BETA to try to fix the issue.

### Current Behavior

Raids are not spawning, the NPC's are not spawning either (barbarian, pirate etc.) Tried with spawn eggs. Tried looking on the internet to solve the issue. The difficulty is hard.

### Expected Behavior

Expected raids

### Reproduction Steps

Try to spawn raider NPC's.

### Logs

https://pastebin.com/PWqL9zjt

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
They dont spawn with spawn eggs. Did you try the mc colony raid command?

**Comment by sh09700** [comment]
Yes i did it did not work earlier but i tried it now and it magically worked, i am not sure if the raids will spawn naturally tho..

**Comment by sh09700** [comment]
i tried changing the difficulty to normal maybe that did it

**Comment by Raycoms** [comment]
Were you on easy before? They dont spawn on easy

**Comment by sh09700** [comment]
no

**Comment by sh09700** [comment]
was on hard. according to the server config

**Comment by sh09700** [comment]
server.properties*

**Comment by sh09700** [comment]
is hard=hardcore?

**Comment by sh09700** [comment]
it seems i can only get the raids to happen on normal difficulty!

**Comment by sh09700** [comment]
thes erver properties files revert back to easy if i try to put them on hard

**Comment by MotionlessTrain** [comment]
Did the raid command work on hard as well?

**Comment by sh09700** [comment]
It lets me do the command but no raid appears

**Comment by Raycoms** [comment]
Shut down the server. Then change the properties to hard. Then start up. Then check difficulty.

**Comment by sh09700** [comment]
I followed your instructions
It now works!
I will update you on wether the raids will spawn naturally now!

**Comment by sh09700** [comment]
![raid tim](https://github.com/ldtteam/minecolonies/assets/123329855/ba93bf90-9211-4ef7-8206-e62f57ebccce)

**Comment by sh09700** [comment]
must be a good sign

**Comment by sh09700** [comment]
![Capture](https://github.com/ldtteam/minecolonies/assets/123329855/8484bbcb-b09b-499c-9430-aeb3ddba2f0c)

**Comment by sh09700** [comment]
![Capture](https://github.com/ldtteam/minecolonies/assets/123329855/3647a30b-fc32-499f-9929-2d305bb1db27)

**Comment by sh09700** [comment]
sucssess! Thanks for the help guys! tho it was a silly problem i appreciate it!
