### ISSUE TITLE
[BUG] Mercy Ends to Raids still say "Victory"

### ISSUE THREAD

**Issue by anonymous563** [ldtteam/minecolonies#9472]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

Ray: "Almost the newest"

### Structurize Version

Ray: "Almost the newest"

### Current Behavior

When a raid kills enough citizens or guards, the raid automatically ends. The ending message says "Victory, the colony was successfully defended!"

Note: I only saw this in the stream. I didn't personally experience this.

### Expected Behavior

It should say some message that the colony was defeated and the raiders pillaged enough or something. Ask Thodor.

### Reproduction Steps

Do the raid.
Let everyone die.
Read chat.

### Logs

N/A

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
fixed
