### ISSUE TITLE
[BUG] Builders starting fires during upgrade

### ISSUE THREAD

**Issue by SoaGMC** [ldtteam/minecolonies#9476]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [X] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

1.18.2-1.1.149-RELEASE

### Structurize Version

1.18.2-1.0.424-ALPHA

### Related Mods and their Versions

Forge 40.2.10
blockui-1.18.2-0.0.71-ALPHA

### Current Behavior

Upgrading buildings leads to them catching fire.
Observed with Caledonia series townhall, barracks, barracks tower, guard tower, library, house and warehouse (so far.)

### Expected Behavior

Builders to follow safe practices before any more NPCs die.

### Reproduction Steps

1. Upgrade building to the point lanterns are used instead of torches.
2. Upgrade again.

### Logs

Did not save log at the times.

### Anything else?

Problem seems to occur when builder replaces a block that has a lantern attached to it causing the lantern to fall to the floor and break.
2 possible solutions:
A) Step 1 of each upgrade = remove all lanterns (possibly place temporary torches) and re-add lanterns as final step.
B) Remove lanterns from all but final tier of each building.

**Comment by Estyria** [comment]
Supplementaries does this. When lanterns drop they break. If you have supplementaries installed you’ll want to change it in their config.

**Comment by Sandriell** [comment]
Considering the popularity of Supplementaries, and that this is a feature on by default, it would be nice if this was supported.

Similar to how there is a final deco pass when building, there should be an initial type of pass when upgrading. Likely there are other cases out there where this could be useful as well. In fact, it could help with even default Minecraft behavior to properly collect blocks than cannot support themselves and just fall to the floor, likely not to be collected- such as buttons, item frames, paintings, etc.

**Comment by Thodor12** [comment]
> Considering the popularity of Supplementaries, and that this is a feature on by default, it would be nice if this was supported.
> 
> Similar to how there is a final deco pass when building, there should be an initial type of pass when upgrading. Likely there are other cases out there where this could be useful as well. In fact, it could help with even default Minecraft behavior to properly collect blocks than cannot support themselves and just fall to the floor, likely not to be collected- such as buttons, item frames, paintings, etc.

But then what? Do you want him to spend extra work removing deco blocks beforehand in the off-chance that supplementaries is installed and that lanterns may or may not fall?

You'd be introducing more steps to a build, where people are already complaining over and over that they think it's too long, and you want to make it longer in general, for such a minor thing?

**Comment by Raycoms** [comment]
You can turn this feature off in the config btw to avoid builds catching fire. This is a very intrusive feature, its not on us to be compatible with intrusive features of other mods.

**Comment by Sandriell** [comment]
As I said though, it would help in more cases than just with Supplementaries, including in vanilla Minecraft behavior.
