### ISSUE TITLE
[BUG] Adding Architect's Cutter recipes in a Hut causes crash

### ISSUE THREAD

**Issue by LoAndEvolve** [ldtteam/minecolonies#9477]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.20.11.1.240-RELEASE

### Structurize Version

1.20.1-1.0.653-BETA

### Related Mods and their Versions

1. Forge version 47.1.3
2. BlockUI 1.20.1-0.0.94-ALPHA
3. Domum Ornamentum 1.20-1.0.138-BETA-universal

Using All the Mods 9, 1.20.1-0.2.5

### Current Behavior

When inputting an Architects Cutter recipe in a hut, the game closes to desktop and the recipe has not been added once joining back in the server.

### Expected Behavior

The recipe gets added and doesn't crash the game.

### Reproduction Steps

Open any hut menu where you can input an architect cutter recipe, click the menu button, find an open request by the builder and click Select, the game will close.

### Logs

https://pastebin.com/ZLK1Dqma

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by cammy1o** [comment]
I also have this bug.

**Comment by uecasm** [comment]
Upgrade to DO 1.0.139.

**Comment by cammy1o** [comment]
> Upgrade to DO 1.0.139.

It's already on the latest version of Domum Ornamentum and block UI and Minecolonies. And it still crashes. Even when you remove the recipe in the hut then select, the game will still crash without adding the recipe.

**Comment by LoAndEvolve** [comment]
Yus, i updated to latest of Domum and still get this crash.

**Comment by Thodor12** [comment]
See the linked pull request, update Minecolonies

**Comment by LoAndEvolve** [comment]
ahh sorry about that, just saw it
