### ISSUE TITLE
[BUG] Mouse pointer is forcibly moved to the center of the screen after quitting scrollable

### ISSUE THREAD

**Issue by mc-kaishixiaxue** [ldtteam/minecolonies#9478]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

1.19.2-1.0.1464-ALPHA

### Structurize Version

1.19.2-1.0.491-ALPHA

### Current Behavior

Mouse pointer is forcibly moved to the center of the screen after quitting the research tree GUI.
In addition to quitting the GUI, starting, undoing, and canceling a research will all do this.

### Expected Behavior

Mouse pointer shoudn't be forcibly moved to the center of the screen.

### Reproduction Steps

1. Right click the university to visit its GUI;
2. Click reserch button to visit research tree GUI;
3. Click "X" button to quit research tree GUI;

### Logs

Log uploading failed

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Nightenom** [comment]
@Raycoms just dont call close unnecessarily like there: <https://github.com/ldtteam/minecolonies/blob/version/main/src/main/java/com/minecolonies/coremod/client/gui/WindowResearchTree.java#L270-L274>
open will automatically close if needed

**Comment by Nightenom** [comment]
Closed via https://github.com/ldtteam/minecolonies/pull/9750/commits/10f19c2dbf8f0aaa1d08bd4ae696a6494add1378
