### ISSUE TITLE
[BUG] Cook not handing out food at all in 1.12.2

### ISSUE THREAD

**Issue by KiillerKiiller** [ldtteam/minecolonies#9479]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

0.11.841-BETA

### Structurize Version

1.12.2

### Current Behavior

![image](https://github.com/ldtteam/minecolonies/assets/148286740/509bb92e-afbb-40ea-824f-a17cfe868d2b)

There seems to be no way to select which food they are allowed to eat like in the wiki

### Expected Behavior

I want the people to come to the restaurant and feeds themselves, not eat rotten flesh they find or starve

### Reproduction Steps

Download the mod in version 1.12.2 in cursed forge, and play and they will not feed themselves

### Logs

10/17/2023

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by someaddons** [comment]
1.12 is not updated anymore

**Comment by KiillerKiiller** [comment]
Is there a way around this bug or am I stuck manually feeding them?
