### ISSUE TITLE
[BUG] [1.20] Decoration Controllers are Broken by Water

### ISSUE THREAD

**Issue by Reveter** [ldtteam/minecolonies#9482]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [X] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.20.1-1.1.240-RELEASE

### Structurize Version

1.20.1-1.0.653-BETA

### Related Mods and their Versions

1. Forge 47.1.3

### Current Behavior

Decoration controllers are destroyed by flowing water.

### Expected Behavior

Decoration controllers not to be destroyed by flowing water.

### Reproduction Steps

1. Place decoration controller
2. Place water bucket next to it
3. Decoration controller breaks

### Logs

https://gist.github.com/Reveter/df863c838cfe5c5642ab2c37a73bed9a

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MarcusUA** [comment]
So that what broke them.
I now have multiple irreparable gates.
