### ISSUE TITLE
[BUG] java.lang.NoSuchMethodError: 'void com.ldtteam.blockui.Loader.createFromXMLFile(net.minecraft.resources.ResourceLocation, com.ldtteam.blockui.views.View)

### ISSUE THREAD

**Issue by litjohn50** [ldtteam/minecolonies#9487]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [X] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.20.1-1.1.240-RELEASE.jar

### Structurize Version

1.20.1-1.0.653-BETA.jar

### Related Mods and their Versions

1. Forge: 47.1.3
2. Domum: 1.20-1.0.139-BETA-universal

### Current Behavior

Clicking "Settings" page on the builders hut crashes the client.

### Expected Behavior

Work as intended

### Reproduction Steps

Refer to Current Behavior

### Logs

https://bytebin.lucko.me/qZfS5OINIq

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
This has been resolved in the latest BlockUI version. You need to update that mod
