### ISSUE TITLE
[BUG] barrack tower is reported to miss its perspective building

### ISSUE THREAD

**Issue by MarcusUA** [ldtteam/minecolonies#9489]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

1.1.240-RELEASE

### Structurize Version

1.0.653-BETA

### Related Mods and their Versions

1. Forge 47.1.3
2. All the Mods 9 0.2.6

### Reproduction Steps

1. Lvl 5 barrack tower is reported to miss its perspective building.
2. Couriers receive red icon on top of them and message me about their AI being broken and ask to report it.  

### Logs

https://gist.github.com/MarcusUA/e054a3fc3c1dbbe6aab339bd46bb1711

### Anything else?

I haven't tried running latest Alpha, as in my case MineColonies comes with All the Mods 9 mod-pack.
As per suggestion on discord I mined tower block with an axe and ordered a repair for barracks (not yet finished) to try to rebuild the tower.  

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Either fixed or #5006
