### ISSUE TITLE
[BUG] Linking resource scroll crashes game when player is in different colony

### ISSUE THREAD

**Issue by midikeyboard** [ldtteam/minecolonies#9496]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

1.1.151 BETA

### Structurize Version

1.0.630

### Current Behavior

Game crashes completely 100% of the time when attempting to check other colonies resources.

### Expected Behavior

Atleast an error message or exception being handled.
would be cool if it would be possible to link with either friendly or Officers roles

### Reproduction Steps

Colony owner of colony B tries to link his builder's resource scroll to Colony A's warehouse. 

### Logs

https://github.com/ldtteam/minecolonies/files/13047806/crash-2023-10-19_21.50.54-client.txt

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Estyria** [comment]
Just a note: Thodor asked for this bug report to be posted.

**Comment by Thodor12** [comment]
Just as another clarification, this feature is not supported, but a message is put in place telling you it's not allowed, as opposed to crashing.
