### ISSUE TITLE
[BUG] CTD when trying to teach recipe into Sawmill from colony requests

### ISSUE THREAD

**Issue by Mincera22** [ldtteam/minecolonies#9497]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.20.1-1.1.240

### Structurize Version

1.20.1-1.0.653

### Current Behavior

When i try to teach a recipe into the sawmill it crashes to desktop.
I'm playing on the ATM9 modpack, latest release

### Expected Behavior

Do the teaching?

### Reproduction Steps

1. Click Teach Recipe
2. Click on requests
3. Click on any open requests
4. Crash to desktop
![image](https://github.com/ldtteam/minecolonies/assets/148474794/ea9e81ba-d6cd-4aa0-b24b-dbada9531925)

### Logs

https://pastebin.com/zaeXyPnQ

### Anything else?

Let me know if you need anything else

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
Can you try updating minecolonies and all the dependencies and see if it is fixed?

**Comment by Mincera22** [comment]
Update to the realease, alpha or beta version?
i have:
structurize-1.20.1-1.0.653-BETA
multipiston-1.20-1.2.31-ALPHA
domum_ornamentum-1.20-1.0.139-BETA-universal
blockui-1.20.1-0.0.94-ALPHA
minecolonies-1.20.1-1.1.240-RELEASE

**Comment by Talyda** [comment]
Whatever is latest, whether alpha, beta or release

**Comment by Talyda** [comment]
Oh, actually, it's been reported on the newest versions too
https://github.com/ldtteam/minecolonies/issues/9492
