### ISSUE TITLE
Loosing Items

### ISSUE THREAD

**Issue by JavaVampire** [ldtteam/minecolonies#950]
### Minecolonies version

1.11.2 - 0.7.811 (Same thing happens with 1.11.2 - 0.7.830 & 1.11.2 - 0.7.832)

### Expected behavior

a) Lumberjack deposits wood into building (chest) and wood is available for collection.
b) Deliveryman collects items and places them in the warehouse.

### Actual behaviour

a) Lumberjack deposits wood into building (chest) and wood disappears.
b) Deliveryman collects items and the items never appear in the warehouse (or anywhere else).

### Steps to reproduce the problem

1. Tried with all available versions of the mod, problem still remains.
2. Removed all other mods I am running and problem still remains.
3. Checked the config files to see if anything was relevant to the issue, nothing found.
4. Demolished the warehouse and had it rebuilt, problem still remains.

Note:  I understand that the 1.11.2 version is not the most stable yet.  I love the mod and hope to be playing it for a long time to come.  Thanks for a great mod!

**Comment by Raycoms** [comment]
Will be fixed in the next version.

**Comment by marchermans** [comment]
I could have sworn that this worked in my PR.....
Am i that blind......

**Comment by marvin-bitterlich** [comment]
@OrionDevelopment remember that the 811 build is not the newest. Have you tracked what build contains your patch?

**Comment by wilsondgonzales** [comment]
@JavaVampire update to at least 0.7.930
