### ISSUE TITLE
[BUG] <minecolonies 1.19.2 requires blockui from 1.20.1>

### ISSUE THREAD

**Issue by sasankyou** [ldtteam/minecolonies#9504]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

minecolonies-1.19.2-1.1.255-BETA

### Structurize Version

structurize-1.19.2-1.0.651-RELEASE.jar

### Related Mods and their Versions

forge: 43.3.2
blockui-1.19-0.0.69-ALPHA.jar

### Current Behavior

![minecolonies - block ui problem](https://github.com/ldtteam/minecolonies/assets/148558126/ec8c9788-a79a-493c-94b3-4eff7c207453)
I am playing on minecraft version 1.19.2 and minecolonies 1.19.2 version demands block ui version thats for minecraft version 1.20.1

### Expected Behavior

that it worked, sorry I am completely new >_<

### Reproduction Steps

Use curseforge app
create profile with 1.19.2 version
install minecolonies, domum ornamentum, block ui
start game on that profile
game window will change to show mentioned error

### Logs

https://gist.github.com/sasankyou/200375b48e5eb27f622e017501cdce53

### Anything else?

feel free to contact me if you need more, and ty very much :)

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
marked newer ones as release to auto select them
