### ISSUE TITLE
[BUG] <Colony deletion after each server restart>

### ISSUE THREAD

**Issue by coconuq** [ldtteam/minecolonies#9506]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

minecolonies-1.16.5-1.0.978-RELEASE

### Structurize Version

structurize-1.16.5-1.0.418-ALPHA

### Related Mods and their Versions

Minecraft - 1.16.5
Forge - 36.2.34

### Current Behavior

After **each** server restart colony deletes itself.
Citizens disappear (logs says: "EntityCitizen 'UUID' unable to find Colony")
/minecolonies colony list - is empty
/minecolonies colony backupAllColonies - do nothing
also each hut says "this block is missing its respective building"

### Expected Behavior

Colony does not delete itself

### Reproduction Steps

start server
make colony (any buildings, single townhall is enough)
restart server
colony deleted

### Logs

https://gist.github.com/coconuq/8ff34e05990e81efe57d837189474f51

### Anything else?

use "EntityCitizen" to find in log - this happens after player joins the server

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
at com.oitsjustjose.geolosys.common.world.capability.Deposit.DepositCapability.deSerializeBlockPos(DepositCapability.java:159) ~[geolosys:6.0.2]


Seems geolosys kills all capability data on load because of an issue on their side. Please report to them.
