### ISSUE TITLE
[BUG] Says not enough space when I have enough space

### ISSUE THREAD

**Issue by truenorth15** [ldtteam/minecolonies#9512]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

1.19.2

### Structurize Version

1.19.2

### Current Behavior

I wanted to get someone into my colony, they need enchanted books, so I got them and when I tried to invite them to my colony it says it doesn't have space. I had already killed my builder to get this person so I was confused. I went into town hall info and it says I have 3/5 people, so I try again and it doesn't work. I even kill my only child to try and get this person to join and it still says I don't have space. I checked my residency and have it on manual and made sure no one is in it. My tavern has three out of four and is also on manual. I don't know what to do. 

### Expected Behavior

It should be letting me get her into my colony please help.

### Reproduction Steps

1. I have no idea what is happening
2. I did feed her food to stop her from leaving
3. one of the enchanted books are from a different mod but i assume this has nothing to do with my issue because it is saying i dont have space in colony not that i dont have enough resources

### Logs

i dont know what tis is

### Anything else?

i have restarted my game multiple times :(

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Celant** [comment]
Looks like this is still a bug, any ideas?

**Comment by Estyria** [comment]
Old bug at that time that was in fact fixed, I believe. Usually the answer is wait five minutes. Make sure that the option for children to be born is turned off in the townhall while you wait. You should not have to wait longer than a couple of minutes.

**Comment by Raycoms** [comment]
old indeed
