### ISSUE TITLE
[BUG] Forge Server Times out

### ISSUE THREAD

**Issue by bkoee** [ldtteam/minecolonies#9513]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.1.265-BETA

### Structurize Version

1.0.655-BETA

### Related Mods and their Versions

1. Forge 47.2.1
2. blockui-1.20.1-0.0.94-ALPHA
3. domum_ornamentum-1.20-1.0.139-BETA-universal
4. multipiston-1.20-1.2.31-ALPHA
5. structurize-1.20.1-1.0.655-BETA
6. balm-forge-1.20.1-7.1.4
7. create-1.20.1-0.5.1.e
8. curios-forge-5.3.5+1.20.1
9. sophisticatedbackpacks-1.20.1-3.18.59.909
10. sophisticatedcore-1.20.1-0.5.89.425
11. waystones-forge-1.20-14.0.2

### Current Behavior

The server hangs or goes unresponsive after the "[Server thread/WARN] [minecolonies/]: Writing Recipe Manager: 12 recipes!" message in the console. Results in server timeout message for me and server has to be stopped. This happens randomly 5-15 minutes after server starts but always ends with that same message in console.

### Expected Behavior

The server is able to be run without timing out and needing to restart.

### Reproduction Steps

1. Local forge server install
2. have 4-5 colonists
3. build builders hut, foresters hut, town hall, guard tower, residence and farm.

### Logs

https://gist.github.com/bkoee/eac992e32968d1ddd898a5e9575d782b

### Anything else?

I have removed minecolonies and dependencies and the issue is not present. I see other people are playing it on 1.20.1, I refuse to play minecraft without your awesome mod lol

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Which launcher are you using?

**Comment by bkoee** [comment]
> Which launcher are you using?

Was using standard launcher then tried using multimc, both have the same issue

**Comment by bkoee** [comment]
Update: only appears to be happening on the forge server. Been playing single player with no issues

**Comment by Raycoms** [comment]
Can you try with the newest? Because this works fine on our servers. And what kind of server is this?

**Comment by bkoee** [comment]
This is on a local forge server running on my win 11 home pc. I'll try with newest and I'll also try this same version on a new server installation. I'm starting to think there was an interaction that corrupted something to do with recipe manager and when it tries to use it that's when the server fails. I'll let you know the results after work today.

**Comment by someaddons** [comment]
if its still broken: uploading the world somewhere(e.g. google drive) could be usefuk

**Comment by bkoee** [comment]
Ok, uploading server folder to google drive now. Where should I send the link? Idk if this thread is private and I'm not sure I'll remove my IP from everything. BTW old server and new mod versions still doesnt work, same error. New server installation and new mod versions is working atm. Saw "[minecolonies/]: Writing Recipe Manager: 0 recipes!" in console and no crash but havent setup colony yet.

**Comment by someaddons** [comment]
could just pm me or ray on discord^^

**Comment by bkoee** [comment]
dm'd ray the link

**Comment by bkoee** [comment]
Just happened to me in singleplayer as well. Crashed after recipe manager line in the console. Vanilla launcher
[latest.log](https://github.com/ldtteam/minecolonies/files/13183805/latest.log)
[debug.log](https://github.com/ldtteam/minecolonies/files/13183808/debug.log)

**Comment by Raycoms** [comment]
solved

**Comment by shps18ppt** [comment]
May I please have the solution? Same issue here, and I want to try it out.
