### ISSUE TITLE
[BUG] Permissions not Sticking

### ISSUE THREAD

**Issue by litjohn50** [ldtteam/minecolonies#9516]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [X] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

minecolonies-1.20.1-1.1.265-BETA.jar

### Structurize Version

structurize-1.20.1-1.0.659-BETA.jar

### Related Mods and their Versions

1. Forge: 47.1.3
2. blockui-1.20.1-0.0.98-ALPHA.jar
3. stylecolonies-1.1.jar

### Current Behavior

When viewing the video mentioned below. I try to set a custom rank to a colony manager setting. This is so I don't get warned each time they enter my colony. I have tried this on non custom ranks. And they also don't stick. If I leave the townhall or change page or anything. It will revert to their default setting.

### Expected Behavior

For Colony Manager Permission to stick.

### Reproduction Steps

https://cdn.discordapp.com/attachments/431629480881160213/1166202127471890532/Base_Profile_2023.10.23_-_21.29.59.29.DVR.mp4?ex=6549a15e&is=65372c5e&hm=7d7a60d568a29da4c80d8ad642564b629ed4a1814e60eb36b83e7d035f5fb693&

### Logs

n/a

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
is this still a problem?

**Comment by Raycoms** [comment]
Closed stale, cant reproduce.
