### ISSUE TITLE
[BUG] Baker acts like their working but does nothing

### ISSUE THREAD

**Issue by DragonLord3688** [ldtteam/minecolonies#9519]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

1.12.2

### Structurize Version

1.12.2

### Related Mods and their Versions

Tekxit 3.14 (Pi)

### Current Behavior

Baker is supplied with a stack of wheat, and the bread recipe is turned on, I taught them the recipe for wheat flour using 1 wheat, as the recipe for vanilla bread (3 wheat across) does NOT work in this iteration/modpack. The baker acts like they are working (slaps the bakery mill) but does nothing and produces nothing, but the wheat is being used

### Expected Behavior

wheat flour should be produced in the bakery or bread

### Reproduction Steps

Removed the recipe
readded the recipe
tried the vanilla recipe
fired the worker and rehired
restarted the server
fed the worker

### Logs

https://pastebin.com/donthavealog

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
1.12 is no longer supported or updated

**Comment by DragonLord3688** [comment]
> 1.12 is no longer supported or updated

Can I manually update the mod ? What are the dependencies of the most recent version? I'd like to see if i can update this mod alone without breaking my other mods by needing to update their dependencies.

**Comment by Talyda** [comment]
Your 1.12 world won't work in 1.20, You can't just update the mods

**Comment by DragonLord3688** [comment]
> Your 1.12 world won't work in 1.20, You can't just update the mods

Thank you for the prompt reply. I appreciate the feedback.
