### ISSUE TITLE
[BUG] Concrete mixer looping because of panel

### ISSUE THREAD

**Issue by Jinotad** [ldtteam/minecolonies#9520]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

minecolonies-1.20.1-1.1.265-BETA.jar

### Structurize Version

structurize-1.20.1-1.0.648-BETA.jar

### Related Mods and their Versions

Raid King-1.9

### Current Behavior

Desert Concrete mixer lvl 2

The hut looks to be in an infinite loop.  Picks up powder, puts powder back, pick up, put back.  I have tried firing, rehiring, canceling request. Switching workers between the concrete mixer and crusher made no change in the concrete hut's worker's behavior.

After testing, it looks like the panel added at level 2 was interfering with the AI for the concrete mixer.

Video of the worker looping:

https://github.com/ldtteam/minecolonies/assets/85356635/5032e139-da16-4748-9a0c-7f370199ae5d

Hut's lvl 2 layout
![2023-10-25_05 29 58](https://github.com/ldtteam/minecolonies/assets/85356635/fb05ea93-b085-4983-b2b7-646327327f8a)

![2023-10-25_05 30 06](https://github.com/ldtteam/minecolonies/assets/85356635/d4656bcd-b57d-4ca5-af04-085738bcb21f)

Lvl 1's layout
![2023-10-25_05 31 18](https://github.com/ldtteam/minecolonies/assets/85356635/f276a74d-e649-42df-b001-35054be6f2b2)

As soon as I broke the panel that was added in lvl 2, the worker started working properly again.
![2023-10-25_17 02 47](https://github.com/ldtteam/minecolonies/assets/85356635/2e8a32f7-0728-4561-ac39-f45e778beefe)
![2023-10-25_17 02 59](https://github.com/ldtteam/minecolonies/assets/85356635/095cb631-7832-4b9e-a9c7-c448aa5d6a56)

### Expected Behavior

(Ray said to make the report.)

I would expect with the panel blocking off the last of the water flow, the worker would start to use the last flow available to make the concrete.

### Reproduction Steps

Place down the lvl 2 desert concrete mixer, and put in a request for concrete.

### Logs

None

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by sidara21** [comment]
Can confirm on same version and same theme (desert).

**Comment by Raycoms** [comment]
fixed
