### ISSUE TITLE
Turning blueprint mode on stops town hall being able to be placed

### ISSUE THREAD

**Issue by Talyda** [ldtteam/minecolonies#9521]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

minecolonies-1.20.1-1.1.269-BETA

### Structurize Version

structurize-1.20.1-1.0.659-BETA

### Related Mods and their Versions

Tried on forge 47.1.3 and 47.2.1
blockui-1.20.1-0.0.98-ALPHA
domum_ornamentum-1.20-1.0.144-BETA-universal
multipiston-1.20-1.2.31-ALPHA

### Current Behavior

Change `blueprintbuildmode` to `true` and when trying to place a townhall down in normal way, there is just an error beep
Moobien said this isn't intended so reporting it.
Zer0Necrosis on discord found out what was causing it, and said it happened on server as well as SP (I only tested SP)

### Expected Behavior

Be able to place town hall to start a colony

### Reproduction Steps

Change config
Try to start a colony

### Logs

https://gist.github.com/Talyda/44ca7fa1288b1642c2580a778d49f286

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
You're not supposed to start colonies in blueprintbuildmode worlds.  Make a different world.

**Comment by Raycoms** [comment]
Yeah, blueprintbuildmode is for schematic worlds, not for regular play worlds.

**Comment by Moobien** [comment]
guessing I read it wrong. I thought Zero had said that they were able to start the mod with blueprint mode enabled and was unable to start it with blueprint mode disabled.

That was what I was saying needed to be reported
