### ISSUE TITLE
[BUG] Alchemist takes all blocks/items as ingredient for dynamictrees:dendro_potion

### ISSUE THREAD

**Issue by Nycto97** [ldtteam/minecolonies#9522]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [X] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

1.1.266-BETA

### Structurize Version

1.0.661-RELEASE

### Related Mods and their Versions

1. Dynamic Trees Version: 1.1.0-BETA10

### Current Behavior

Every block/item I right-click in JEI list, has a recipe for the Alchemist, more specifically for the item `dynamictrees:dendro_potion` (atleast in JEI, don't know if the recipe actually works, not tested)

Right-clicked on Diamond Block and navigated to Alchemist tab:
![image](https://github.com/ldtteam/minecolonies/assets/83367226/b301d860-1c7c-4ff2-a54d-4ae906e53524)

Left-clicked on the potion (`dynamictrees:dendro_potion`), showing 27K recipes:
![image](https://github.com/ldtteam/minecolonies/assets/83367226/a46216f1-fc9e-4769-a0d7-4f155c2ef27d)

### Expected Behavior

To not have 27K+recipes generated for `dynamictrees:dendro_potion`. (this is with all my mods enabled)

I ran the game with only the following mods:
![image](https://github.com/ldtteam/minecolonies/assets/83367226/ead3d328-4504-4e41-85e7-1d91808b08cf)

resulting in:
![image](https://github.com/ldtteam/minecolonies/assets/83367226/fd7a22e0-46a3-47e1-bc1f-23f249daad7d)

### Reproduction Steps

1. Have MineColonies + required dependencies + Dynamic Trees + JEI installed
2. Launch client
3. Join a world (singleplayer or multiplayer)
4. Open JEI GUI
5. Right-click (or hover and 'U) any item
6. Go to Alchemist tab
7. Left-click the `dynamictrees:dendro_potion`
8. Go to Alchemist tab
9. See all the pages with recipes

### Logs

https://pastebin.com/v3u3K0N6

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
From screenshots posted on discord, the corresponding brewing stand recipe just has one alternative: just using awkward potions (and charcoal as ingredient)

**Comment by uecasm** [comment]
This is most definitely a bug in Dynamic Trees.  If you actually try putting charcoal into all of the slots (or charcoal in the top slot and any other item at all in the bottom slots) in a brewing stand, it will indeed produce the DT potion.  MineColonies is just telling it like it is, and DT's JEI plugin is lying to you. 😀 

When reporting the bug to them, you can tell them that `DendroBrewingRecipe.isInput` is accepting all items, because they're not doing the comparison they probably intended.
