### ISSUE TITLE
[BUG] Workers will not return to unemployed when fired

### ISSUE THREAD

**Issue by KaisarDragon** [ldtteam/minecolonies#9525]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.1.270

### Structurize Version

1.0.656

### Current Behavior

Firing someone from a hut does not return them to unemployed. They remain their current job, but you can still hire a new person. This person is also stuck in the job. Multiple workers will work in the same hut. You cannot hire a worker for a different hut. While the new hut claims they work there, their title remains from their old job and they will continue to do their old job.

### Expected Behavior

Workers should return to unemployed when fired.

### Reproduction Steps

Fire a worker in a hut
Hire a different worker
Fire that new worker
Wonder what went wrong

### Logs

https://pastebin.com/hFHG0FpL

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by someaddons** [comment]
can you upload your clients latest.log? can't seem to reproduce this
edit: was able to reproduce with just enchanter it seems, builder didnt have the issue

**Comment by MotionlessTrain** [comment]
This seems to be solved, according to the discussion on [discord](https://discord.com/channels/139070364159311872/1003402487417548801/1167198114910830613)

**Comment by qwltech** [comment]
Hello, still experiencing this on minecolonies-1.19.2-1.1.307

forge 43.3.2

appleskin-forge-mc1.19-2.4.2.jar
AttributeFix-Forge-1.19.2-17.2.7.jar
balm-forge-1.19.2-4.6.0.jar
BetterAdvancements-1.19.2-0.3.0.148.jar
blockui-1.19.2-1.0.118-BETA.jar
bobby-1.19.2_v5.0.1.jar
Bookshelf-Forge-1.19.2-16.3.20.jar
Botania-1.19.2-440-FORGE.jar
Clumps-forge-1.19.2-9.0.0+14.jar
comforts-forge-6.0.6+1.19.2.jar
Compressium-2.1.1-build.8+mc1.19.jar
Controlling-forge-1.19.2-10.0+7.jar
corail_woodcutter-1.19.2-2.5.2.jar
corpse-1.19.2-1.0.0.jar
craftingtweaks-forge-1.19.2-15.1.8.jar
curios-forge-1.19.2-5.1.4.2.jar
domum_ornamentum-1.19-1.0.146-BETA-universal.jar
EnchantmentDescriptions-Forge-1.19.2-13.0.16.jar
ExplorersCompass-1.19.2-1.3.0-forge.jar
FarmersDelight-1.19.2-1.2.3.jar
Jade-1.19.1-forge-8.9.1.jar
jei-1.19.2-forge-11.6.0.1018.jar
journeymap-1.19.2-5.9.7-forge.jar
JustEnoughResources-1.19.2-1.2.2.236.jar
LibX-1.19.2-4.2.8.jar
MaxHealthFix-Forge-1.19.2-8.0.2.jar
Mekanism-1.19.2-10.3.9.13.jar
MekanismGenerators-1.19.2-10.3.9.13.jar
MekanismTools-1.19.2-10.3.9.13.jar
minecolonies-1.19.2-1.1.307-BETA.jar
MouseTweaks-forge-mc1.19-2.23.jar
multipiston-1.19.2-1.2.25-ALPHA.jar
MythicBotany-1.19.2-3.0.2.jar
NaturesCompass-1.19.2-1.10.0-forge.jar
netherportalfix-forge-1.19-10.0.1.jar
Patchouli-1.19.2-77.jar
radium-0.8.2.jar
radon-0.8.2.jar
rubidium-mc1.19.2-0.6.2c.jar
SandBox-1.19.2-1.0.1.jar
sophisticatedbackpacks-1.19.2-3.18.63.934.jar
sophisticatedcore-1.19.2-0.5.98.459.jar
sophisticatedstorage-1.19.2-0.8.47.625.jar
structurize-1.19.2-1.0.661-RELEASE.jar
Terralith_1.19.3_v2.3.12.jar
timecontrol-1.19.2-1.1.3.1.jar
towntalk-1.19.2-1.0.0.jar
trashslot-forge-1.19.2-12.1.0.jar
TreeChop-1.19.2-forge-0.17.8a.jar
waystones-forge-1.19.2-11.4.1.jar

**Comment by qwltech** [comment]
More info: after firing the worker, the worker is basically corrupted and will just stand still at the warehouse (courier in this instance). When hiring the worker again in their original post (e.g. reinstate the unhappy courier with higher pay) he suddenly works correctly again. But I want him as an archer.
