### ISSUE TITLE
[BUG] 1.20.1 Client Crashing When Hiring Worker

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [ldtteam/minecolonies#9526]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

minecolonies-1.20.1-1.1.271-BETA.jar

### Structurize Version

structurize-1.20.1-1.0.656-BETA.jar

### Related Mods and their Versions

None

### Current Behavior

https://gist.github.com/P3rf3ctXZer0/928cf8a3c75c9b1eb6eae38f29820994

### Expected Behavior

No crash

### Reproduction Steps

Not sure

### Logs

https://gist.github.com/P3rf3ctXZer0/928cf8a3c75c9b1eb6eae38f29820994

### Anything else?

Told to report by MotionlessTrain

**Comment by MotionlessTrain** [comment]
This has at least been reported for a builder's hut, and I believe a farm as well

**Comment by Raycoms** [comment]
This is caused by a citizen keeping the hut even though the hut gets removed. And then other code breaks because get building on getWorkBuilding is null.
