### ISSUE TITLE
[BUG] Request list not updating after teaching DO blocks to crafter

### ISSUE THREAD

**Issue by Jinotad** [ldtteam/minecolonies#9528]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

minecolonies-1.20.1-1.1.269-BETA.jar

### Structurize Version

structurize-1.20.1-1.0.659-BETA.jar

### Current Behavior

A DO block is requested, it appears on the clipboard because no one can craft it yet. You go to a crafter and teach them the DO block recipe, but the request never leaves the clipboard. Resulting in you having to cancel the request, so the block is eventually re-requested.

Just taught the stonemason this recipe, but it still showing on the clipboard.
![2023-10-27_05 31 14](https://github.com/ldtteam/minecolonies/assets/85356635/90830b33-c437-4cd9-97cc-34b297c57194)
![2023-10-27_05 31 22](https://github.com/ldtteam/minecolonies/assets/85356635/ef2cd89e-f919-43a4-a4dd-d3adab5290ed)

### Expected Behavior

Just like all the regular recipes, once you teach it, it automatically gets refreshed on the request list so it no longer appears on the clipboard. No longer needing to cancel it.

### Reproduction Steps

Request a fancy block copper door, made from block of copper and nether brick. Request appear on clipboard. 

Teach recipe to stone mason. Look at clipboard again.

### Logs

None

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Moobien** [comment]
normal behaviour. due to the large number of DO recipes being taught at once. cancel the requests and all will be good.

**Comment by uecasm** [comment]
> normal behaviour

_points at PR_ not for much longer...
