### ISSUE TITLE
[BUG] [MC1.19.2] Zooming in Minecolonies Research Tree View crashes Client with NPE

### ISSUE THREAD

**Issue by Braastos** [ldtteam/minecolonies#9531]
Mods:
Domum Ornamentum 1.19-1.0.146-BETA
MineColonies 1.19.2-1.1.275-BETA
Multi-Piston 1.19.2-1.2.25-ALPHA
Structurize 1.19.2-1.0.661-RELEASE
BlockUI 1.19.2-0.0.100-ALPHA

Current Behavior:
When Opening any Research Tree in the University (not Tier 5) and the zooming out, the client crashes with a NullPointerException.
Crash happens at different Zoom Levels depending on Univerity Tier. Lower Tier = earlier crash

Expected Behavior:
Zooming out and no crash happening

Reproduction Steps:
1. Have University not a max level
2. Open any Research Tree
3. Zoom out

Logs:
https://gist.github.com/Braastos/b9358c173ddceab4d24cc92bf267ef8c

Anything else?
Crash does not happen with BlockUI 1.19.2-0.0.100-ALPHA or on MC 1.20

**Comment by Braastos** [comment]
Crash does not directly related to zoom.
My game crashed when i moved the view over to the Tier locked research area.
Seems to be related to this locked Area. Which would explain why its not hapening with Tier 5 Universitys

**Comment by MotionlessTrain** [comment]
According to the report on discord, this only happened on BlockUI 0.0.100, and not on 0.0.99 (which is why I said to open the issue on BlockUI's github, as I thought it had to do with the fix for the glitching shadows)

**Comment by Nightenom** [comment]
definitely mcol issue - in research tree ui:
probably bug source - children cant be modified like this, if add(0,...) is really needed then full addChild method must be replicated, especially the setwindow part:
https://github.com/ldtteam/minecolonies/blob/version/main/src/main/java/com/minecolonies/coremod/client/gui/WindowResearchTree.java#L379
super wierd - should either have "i" as index or be outside for cycle?
https://github.com/ldtteam/minecolonies/blob/version/main/src/main/java/com/minecolonies/coremod/client/gui/WindowResearchTree.java#L816

**Comment by MotionlessTrain** [comment]
> Crash does not directly related to zoom. My game crashed when i moved the view over to the Tier locked research area. Seems to be related to this locked Area. Which would explain why its not hapening with Tier 5 Universitys

I didn't get the crash when the locked area was visible, but when I hovered over one of the level 4+ researches (in a level 3 university)

**Comment by Braastos** [comment]
> > Crash does not directly related to zoom. My game crashed when i moved the view over to the Tier locked research area. Seems to be related to this locked Area. Which would explain why its not hapening with Tier 5 Universitys
> 
> I didn't get the crash when the locked area was visible, but when I hovered over one of the level 4+ researches (in a level 3 university)

My Game crashes when hovering over the darkend area, i dont need to hover over any research. (Yes i explicitly only moved the cursor into the darkened area and not over any of the locked researches)
But i did not notice this while figuring out what is happening, because of the default mouse position, the moment you zoom out with an Level 1 University you are instantly over the locked Area

**Comment by 420science** [comment]
> According to the report on discord, this only happened on BlockUI 0.0.100, and not on 0.0.99 (which is why I said to open the issue on BlockUI's github, as I thought it had to do with the fix for the glitching shadows)

My game crashed to but the above quote is right, i installed BlockUI 0.0.99 and the issue is gone, works with latest version of minecolonies 1.19.2-1.1.275-BETA

**Comment by Bjorndoesgaming** [comment]
The Town Map in the Town Hall block also crashes in the latest version of BlockUI. blockui-1.19.2-0.0.100-ALPHA <--- This one,
Downgrading to the .99 version fixes this problem.

**Comment by Braastos** [comment]
@Bjorndoesgaming could you provide more information, like, what exactly did you do, so the crash is reproducable.
I could not reproduce the crash with the Town Map.

But it got me thinking which other Screens trigger this bug....
~~At the moment i only found that in the Town Hall, pressing the Hire Mercenarys Button also causes a crash.~~ <- other Error, will investigate...

**Comment by Braastos** [comment]
Seems to be fixed with updates in BlockUI and MineColonies.
From my point of view could be closed.
