### ISSUE TITLE
[BUG] Server Crash Loop with Alchemist.

### ISSUE THREAD

**Issue by Sandriell** [ldtteam/minecolonies#9533]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

1.19.2-1.1.266-BETA

### Structurize Version

1.19.2-1.0.649-BETA

### Related Mods and their Versions

Forge: 43.2.21
BluckUI: 1.19.2-0.0.99-ALPHA
DO: 1.19-1.0.146-BETA-universal

### Current Behavior

After requesting (through the post box) 9 potions (taught recipe for night vision) from the alchemist the sever crashed and is now stuck in a crash loop. Server crashes again soon as attempting to login- presumably because the Alchemist resumes trying to use the Brewing Stand once loaded.

### Expected Behavior

No crashes and some potions.

### Reproduction Steps

Simply requested Night Vision 8:00 from the brewing stand. I believe from watching the request process, the crash occurred when the Alchemist attempted the first step, making the Awkward Potions.

### Logs

https://gist.github.com/Sandriell/f7bb7be8f512f26908f018ec305d3d48

### Anything else?

Additional crash log:
https://gist.github.com/Sandriell/81ad1ed7f9926a1e53a96e5100f3b158

Not running the latest version, but only 1 version behind and that version had no changes that had anything to do with the alchemist as far as I can tell.

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Doesnt seem minecolonies fault from what I can see, some mod alters brewing stands in your pack and that crashes on tileentity load. Might have to find out which mod of them does that

**Comment by Sandriell** [comment]
The mod BiggerStacks was the issue, it allows modifying stack sizes. I was changing the stack size of potions to 16 and I am guessing the Minecolonies alchemist was trying to force more than 1 item into the brewing stand, possibly?

**Comment by Raycoms** [comment]
They did the vanilla setup of the brewing stand and then the brewing stand was crashing alone without our interference. You can probably reproduce this without minecol by setting up a brewing stand with content, log off, install mod, log on.
