### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by Murdersands** [ldtteam/minecolonies#9539]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

1.20.2

### Structurize Version

1.19.2

### Related Mods and their Versions

포지가 오류인가요?

### Reproduction Steps

릴리스 +플레이 이가 오류

### Logs

https://www.curseforge.com/minecraft/modpacks/minecolonies-official

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Please make issues in english
