### ISSUE TITLE
[BUG] Client crashes when trying to select open recipe request in saw mill

### ISSUE THREAD

**Issue by mribrgr** [ldtteam/minecolonies#9543]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [X] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.20.1-1.1.240-RELEASE

### Structurize Version

ATM9 0.2.10 (but was a problem at least since ATM9 0.1.5)

### Current Behavior

The game crashed whilst mousepressed event for bo screen
Error: java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2

<img width="643" alt="image" src="https://github.com/ldtteam/minecolonies/assets/46381092/981e6607-a240-4ec2-a1cd-c9442b962daa">

In the server log there are no more information given.

### Expected Behavior

No crashing

### Reproduction Steps

1. go to saw mill
2. click to the request page
3. click "select"

### Logs

[01:32:33] [Server thread/INFO] [minecraft/ServerGamePacketListenerImpl]: CubeChars lost connection: Disconnected [01:32:33] [Server thread/INFO] [minecraft/MinecraftServer]: CubeChars left the game

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
Update minecolonies. This has been fixed already
