### ISSUE TITLE
[BUG] Crash in Twon Hall Block, when pressing Map or Hire Mercenaries

### ISSUE THREAD

**Issue by Braastos** [ldtteam/minecolonies#9544]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

1.19.2-1.1.292-BETA

### Structurize Version

1.19.2-1.0.661-RELEASE

### Related Mods and their Versions

Forge 43.3.2
BlockUI 1.19.2-0.0.102-ALPHA
Multi-Piston 1.19.2-1.2.25-ALPHA
DO 1.19-1.0.146-BETA

### Current Behavior

When pressing the "Open Town map" or "Hire Mercenaries" Button in the Town Hall, the game crashes with a RuntimeException, File not found Error.

### Expected Behavior

Opening Map or Mercenaries

### Reproduction Steps

1. Open Town Hall
2. Press Town Map or Hire Mercenaries Button
3. Crahs

### Logs

https://gist.github.com/Braastos/9f96d84e0f63a6ab747c380cae80bde4

### Anything else?

It seems it cant find some Entity Icons. Could be related to the Citizen Corruption mentioned in the latest Announcment on Discord...

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
fix pushed
