### ISSUE TITLE
[BUG] [1.19.2] Never Ending Spooky Season (Nether style still enabled)

### ISSUE THREAD

**Issue by Sandriell** [ldtteam/minecolonies#9549]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

1.19.2-1.1.297-BETA

### Structurize Version

1.19.2-1.0.649-BETA

### Related Mods and their Versions

Forge: 43.2.21

### Current Behavior

It is November 5th and the Halloween event is still going on- the nether style is still enabled.

I have restarted the server and the client multiple times. My citizens are all still undead and the style specified in the Townhall is "nether".

I am not a Patron, so I cannot change it.

I am not a java dev, but looking at the code, it seems like if the date is in the range 29-2 it sets the style to nether... but does nothing to change the style outside of the date range- just sets the style to whatever it already is. 

### Expected Behavior

The Halloween event to end on November 3rd as coded.

### Reproduction Steps

Have Colony.
Halloween Event started on Oct 29.
Possibly not be a patron?
Wait till Nov 3rd (or the 5th as the case may be)

### Logs

N/A

### Anything else?

Based on a discussion in Discord, possible this issue only exists for non-patrons, and why it wasn't caught by any of the devs/team.

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Hmm thats, odd, this worked fine for me. Were you a patreon at the time or so?

**Comment by Sandriell** [comment]
Sadly, have never been a patron.

**Comment by MotionlessTrain** [comment]
Would it matter whether you looked at the options tab in the town hall during the time it was enabled?
That it perhaps saved the nether style as default style when you did (and it would restore to the previous set style when you didn't go to the tab during the spooky season)?

Edit: It did revert back for me correctly as well, but I don't believe I have looked at that tab in the past week

**Comment by Raycoms** [comment]
Ahh, that is possible. I might have to add a "reset to default" button there then

**Comment by Sandriell** [comment]
Would not apply to me, but someone who was previously a patron and had a custom style picked, they could potentially lose that custom style if their only option was to "reset to default".

Edit to add: I can also confirm that I did open the Townhall during the event, because I changed the Housing Assignment to Automatic.

**Comment by Desoroxxx** [comment]
Same issue for me, I had looked at the tab during the event, since I did not understand why everybody looked like that
