### ISSUE TITLE
Ressources diseappears

### ISSUE THREAD

**Issue by Arthebas** [ldtteam/minecolonies#955]
### Minecolonies version

version 1.11.2-0.7.832 

### Expected behavior

- Each NPC who gather ressources deposit in his storage (farmer, miner, builder, sawmill, etc ... )

### Actual behaviour

- When a NPC deposit ressources, they disappears 

### Steps to reproduce the problem

1. Minecraft 1.11.2
2. Forge 1.11.2-13.20.0.2282
3. Server host by Verygames
4. Some mods like Tinkers Construct
 I've test other minecolonies versions, delete config files, nothing works :/

PS: your mod is really great, so much fun a big thanks to you :)

**Comment by Raycoms** [comment]
Have you tried the alpha versions on curse?

2017-05-08 22:13 GMT-03:00 Arthebas <notifications@github.com>:

**Comment by Arthebas** [comment]
Hello Raycoms, yes I've tried the minecolonies-universal-1.11.2-0.7.887.jar
Don't know if problem was solved cause I can't access NPC inventory.

I try again

**Comment by Arthebas** [comment]
Omg, it works \o/
This time no inventory bug or text bug and NPC stock items.
So much thanks for your help \o/
