### ISSUE TITLE
[BUG] 1.20.1/+ When Destroying Spawners on Pirate Ships the Raid Should End According to Set Number of Days In Config

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [ldtteam/minecolonies#9551]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [X] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

minecolonies-1.20.1-1.1.303-BETA.jar

### Structurize Version

 structurize-1.20.1-1.0.659-BETA.jar

### Current Behavior

Even though I have set in config for the pirate ship to be set to disappear in 24 hours they remain. I was told its because I am destroying spawners. Ironically why should this matter? At any rate if it does matter it should be fixed became it makes your town do nothing for 3 days.

### Expected Behavior

Regardless to how a player removes threats your town should go back to its business. if Actual pilgrims took this stance they would have died. I feel like days present should only apply to living threats and once they are dealt with this should return to normal with no delay at all. I play with dangerous mobs in pack and I enjoy a challenge but I do not enjoy when colonists commit suicide and do nothing. Or a threat arrives and they do nothing. This honestly seems very; very stupid. 

### Reproduction Steps

Set Config to 1 day
Get raided by pirates and then go burn down or destroy ships.

### Logs

NA

### Anything else?

Again as stated I play with leveling mobs and monsters and the raids add extra spice and is meant to be forced to deal with; I even have it set to be max difficulty and spawn rate - what I don't want to do is be punished for successfully defending my colony or colonies. Thanks for your time.

**Comment by Raycoms** [comment]
fixed
