### ISSUE TITLE
[BUG] Heavy Lag Spike when opening Postbox in ATM9-0.2.12

### ISSUE THREAD

**Issue by privatemeta** [ldtteam/minecolonies#9552]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

minecolonies-1.20.1-1.1.294-BETA

### Structurize Version

structurize-1.20.1-1.0.659-BETA

### Related Mods and their Versions

- Forge 47.1.3
- minecolonies-1.20.1-1.1.294-BETA
- structurize-1.20.1-1.0.659-BETA
- blockui-1.20.1-1.0.115-BETA
- domum_ornamentum-1.20-1.0.147-BETA-universal

all other mods can be seen in the spark report

### Current Behavior

As soon as the postbox ui is openend, the game freezes for 45-60 seconds.
After the freeze, the game seems to catch up on all actions paused during UI open

### Expected Behavior

fast load time, maybe a few seconds, hopefully less until the 

### Reproduction Steps

1. Install All The Mods 9 Version 0.2.12 (at the current time)
2. Open MineColonies Postbox
3. Lag appears

### Logs

https://spark.lucko.me/RJnQrsz6ow

### Anything else?

The issue was tested with a single player instance. The spark report was done with "/sparkclient", so it seems to be a client side issue, even though it was a singe player instance.
The issue did not happen with ATM9-0.1.12, the version I used previously, which includeded the following versions:

- minecolonies-1.20.1-1.1.195-BETA
- blockui-1.20.1-0.0.94-ALPHA
- domum_ornamentum-1.20-1.0.133-BETA-universal
- structurize-1.20.1-1.0.648-BETA

I did not install a later version of Minecolonies as the used version came with the played modpack

---

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Estyria** [comment]
As a note, this is not an isolated incident. I believe we're up to 3 separate reports on the discord.

**Comment by Sandriell** [comment]
I was planning to report this issue as well on 1.19.2, but I was gonna do a little testing first. I suspected it was related to a BlockUI change sometime between 102 and 117

**Comment by qwltech** [comment]
This is probably not limited to ATM9. I'm experiencing this on a custom pack. The spike only lasts a fraction of a second.

appleskin-forge-mc1.19-2.4.2.jar
AttributeFix-Forge-1.19.2-17.2.7.jar
balm-forge-1.19.2-4.6.0.jar
BetterAdvancements-1.19.2-0.3.0.148.jar
blockui-1.19.2-1.0.118-BETA.jar
bobby-1.19.2_v5.0.1.jar
Bookshelf-Forge-1.19.2-16.3.20.jar
Botania-1.19.2-440-FORGE.jar
Clumps-forge-1.19.2-9.0.0+14.jar
comforts-forge-6.0.6+1.19.2.jar
Compressium-2.1.1-build.8+mc1.19.jar
Controlling-forge-1.19.2-10.0+7.jar
corail_woodcutter-1.19.2-2.5.2.jar
corpse-1.19.2-1.0.0.jar
craftingtweaks-forge-1.19.2-15.1.8.jar
curios-forge-1.19.2-5.1.4.2.jar
domum_ornamentum-1.19-1.0.146-BETA-universal.jar
EnchantmentDescriptions-Forge-1.19.2-13.0.16.jar
ExplorersCompass-1.19.2-1.3.0-forge.jar
FarmersDelight-1.19.2-1.2.3.jar
Jade-1.19.1-forge-8.9.1.jar
jei-1.19.2-forge-11.6.0.1018.jar
journeymap-1.19.2-5.9.7-forge.jar
JustEnoughResources-1.19.2-1.2.2.236.jar
LibX-1.19.2-4.2.8.jar
MaxHealthFix-Forge-1.19.2-8.0.2.jar
Mekanism-1.19.2-10.3.9.13.jar
MekanismGenerators-1.19.2-10.3.9.13.jar
MekanismTools-1.19.2-10.3.9.13.jar
minecolonies-1.19.2-1.1.307-BETA.jar
MouseTweaks-forge-mc1.19-2.23.jar
multipiston-1.19.2-1.2.25-ALPHA.jar
MythicBotany-1.19.2-3.0.2.jar
NaturesCompass-1.19.2-1.10.0-forge.jar
netherportalfix-forge-1.19-10.0.1.jar
Patchouli-1.19.2-77.jar
radium-0.8.2.jar
radon-0.8.2.jar
rubidium-mc1.19.2-0.6.2c.jar
SandBox-1.19.2-1.0.1.jar
sophisticatedbackpacks-1.19.2-3.18.63.934.jar
sophisticatedcore-1.19.2-0.5.98.459.jar
sophisticatedstorage-1.19.2-0.8.47.625.jar
structurize-1.19.2-1.0.661-RELEASE.jar
Terralith_1.19.3_v2.3.12.jar
timecontrol-1.19.2-1.1.3.1.jar
towntalk-1.19.2-1.0.0.jar
trashslot-forge-1.19.2-12.1.0.jar
TreeChop-1.19.2-forge-0.17.8a.jar
waystones-forge-1.19.2-11.4.1.jar

**Comment by Estyria** [comment]
I believe they are working on a fix for this.

**Comment by Talyda** [comment]
Been fixed =) A fraction of a second is hardly a lag spike! The lag spike was 20 seconds or so =)
