### ISSUE TITLE
[BUG] Guards requesting wrong tier of armor compared to tower level

### ISSUE THREAD

**Issue by darthvader45** [ldtteam/minecolonies#9554]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.1.303-BETA

### Structurize Version

1.0.659-BETA

### Related Mods and their Versions

1. Forge 47.2.1
2. BlockUI 1.0.115-BETA
3. Domum Ornamentum 1.0.147-BETA

### Current Behavior

Guards are requesting armor consistent with a level 1 tower, despite their tower being level 2.

### Expected Behavior

They should request armor with a max tier equivalent to their tower level (i.e. for level 3 they should request anywhere from leather to iron).

### Reproduction Steps

1. Level a guard tower to level two and make sure a guard is hired.
2. Wait until they request armor and weapon.
3. Notice it's lower than they would normally request (check request clipboard)

### Logs

N/A

### Anything else?

![image](https://github.com/ldtteam/minecolonies/assets/2816420/a081bf83-df4e-4944-9f22-5afba71646cd)

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Is this maybe an old request from before the upgrade?

**Comment by darthvader45** [comment]
I cancelled the request and it reappeared.  No matter how many times I cancel the request, they make new ones.

Also, I gave them leather armor before the upgrade, and after it was done I swapped the leather for chainmail.

**Comment by MotionlessTrain** [comment]
From the request detail, it looks like leather and gold are not the same material tier (anymore). I'm wonder how that is possible

**Comment by darthvader45** [comment]
Yeah, they give exactly the same protection, with the only difference being durability.

**Comment by MotionlessTrain** [comment]
^ And enchantability (gold tools and armour generally get better enchantments than wooden and leather tools and armour), but both duration and enchantability shouldn't matter for material tier

**Comment by darthvader45** [comment]
Yeah, and that.  Hopefully this can be remedied in a future update.

**Comment by Zethamnos** [comment]
To piggy back off this since I did not make it last night. 
I was having issues with fulfilling the armor requests with lv 4 guard towers.  
They were rejecting armor they liked before the update (I have since reverted my server).
I tried changing/reducing enchants they took before, and while they would wear the iron armor or it would fulfil their request (the actual fulfill option, also tried directly putting into inventory and armor slots), they would keep requesting new armor. 
Silent gear crimson steel armor was still taken despite being fully enchanted and with no issues. 

I think it is incredibly annoying that even before this update and especially now, if they say I can fulfill a request in their tabs, it does not always actually fulfill. The deal breaker for keeping the update for me was that they would wear the armor I fulfilled for them, then request for more armor. My health bar mod even shows they were benefiting from the armor value.

**Comment by Raycoms** [comment]
This seems to be related to some other mod in the pack changing vanilla armor properties.

**Comment by Zethamnos** [comment]
> This seems to be related to some other mod in the pack changing vanilla armor properties.

Silent gear can convert vanilla armor to it's own gear, but I had not done so. The only other differences are some enchantments or entirely new armor sets. I was using vanilla iron armor + protection. Maybe I missed a mod changing something or there is a mod messing with the code but I do not have that expertise to know.

**Comment by janisl** [comment]
I just updated to latest (1.20.1-1.1.327-BETA) and I started to get this as well. For me it seams if I cancel it it doesn't come back.

**Comment by janisl** [comment]
I did a test. I hired a guard (tier 3), after a while I have in clipboard requests for lower tier armor, but the guard has iron armor.

**Comment by Alathreon** [comment]
I have a similar problem in the current latest version in 1.19.2, they are level 3 tower, have equiped on themself full iron armor, but are requesting leather to chainmail armor.

**Comment by LairdMatthex** [comment]
Is anyone else still having this bug? My guards are all in level 2 buildings, and (seemingly) randomly request lower tier gear as previous comments have detailed. 

Raycoms mentioned another mod possibly changing vanilla armour properties; does anyone have an idea which one?

**Comment by MotionlessTrain** [comment]
From what was noticed on the patreon server, it looks like this only happens after the game has been running for a while, and is hard to debug what exactly is happening because of that

**Comment by Raycoms** [comment]
This should not happen at all anymore now.
