### ISSUE TITLE
[BUG] <Decoration controler not working>

### ISSUE THREAD

**Issue by Drowkas** [ldtteam/minecolonies#9556]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

minecolonies-1.20.1-1.1.303-BETA

### Structurize Version

structurize-1.20.1-1.0.659-BETA

### Related Mods and their Versions

1. forge version: 47.2.0
2. Block UI : blockui-1.20.1-1.0.119-BETA
3. Domum Ornamentum: 
domum_ornamentum-1.20-1.0.147-BETA-universal
Multi-Piston: 
multipiston-1.20-1.2.31-ALPHA
TownTalk: towntalk-1.20.1-1.0.0

### Current Behavior

I right click on the decoration controler and nothing pops up
![image](https://github.com/ldtteam/minecolonies/assets/150283777/5d665bd7-cae2-4de5-b15d-c00af064624d)

### Expected Behavior

When I right click on the decoration controller it should pop up with something like this:
![image](https://github.com/ldtteam/minecolonies/assets/150283777/e33db18f-d6bc-494d-a390-73c8b9c1cff3)

### Reproduction Steps

1. I construct the housing in the original minecolonies pack located in decoration/housing
2. Then I right click on the decoration controlor and i don't get de GUI

### Logs

https://gist.github.com/Drowkas/b748308b003551e1dcf932ff84062f13

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
The interface of the expected behaviour is the old 1.18 interface. It has been changed to the other one
Apparently the wall decoration cannot be found in that folder in the style it was built in, that is why the buttons are missing
What style is that wall of?

Also this should have been reported in #5006

**Comment by Drowkas** [comment]
I tried diferent styles, but the one in the picture is medival oak

**Comment by MotionlessTrain** [comment]
Could you try Minecolonies Original -> walls -> oak -> oakwallsegment1?
Just to check whether you happened to find ones with broken decoration controllers, or to find out whether something else is the issue (I know the decoration controller of the Minecolonies Original wall should work correctly)

**Comment by Drowkas** [comment]
Same problem 
![image](https://github.com/ldtteam/minecolonies/assets/150283777/ecbca608-525e-4823-aa4b-f1cfb6ca05c5)

**Comment by MotionlessTrain** [comment]
Just in case: How did the decoration get placed?

Did a builder build it, or did you use schematic paste? or constructed paste?

**Comment by Drowkas** [comment]
constructed paste

**Comment by MotionlessTrain** [comment]
Are you pasting it inside of a colony?

**Comment by Drowkas** [comment]
No, im gonna try that, im using a creative world to test it becouse it happend on a survival world the first time

**Comment by Drowkas** [comment]
That works, I feal stupid now xD, thanks for you help!
