### ISSUE TITLE
[BUG] <Game crashes when a TownHall is placed with Build Tool>

### ISSUE THREAD

**Issue by OraclePearl** [ldtteam/minecolonies#9557]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.1.240

### Structurize Version

1.0.662

### Current Behavior

Minecraft crashes whenever I attempt to place a TownHall with the wand.
I was able to preview before placing it down, but as soon as i click on the tick, it crashes.

### Expected Behavior

Placing down the TownHall with a wand will actually place it down.

### Reproduction Steps

1. Ensure Town Hall and Built Tool is in inventory.
2. Aim the tool at a flat ground.
3. Preview to ensure the Town Hall is on the flat ground.
4. Click on the Green icon to accept.

### Logs

https://gist.github.com/OraclePearl/36a4f45a80f57e08382c7fb543b546ff

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
Duplicate of https://github.com/ldtteam/Structurize/issues/628
You may need to downgrade Structurize one version for now, and upgrade minecolonies as well

**Comment by OraclePearl** [comment]
> Duplicate of [ldtteam/Structurize#628](https://github.com/ldtteam/Structurize/issues/628) You may need to downgrade Structurize one version for now, and upgrade minecolonies as well

It works if i play the mod by itself but since its in a modpack, there is a rendering overlay crash. Is there a solution for that?

**Comment by Nightenom** [comment]
Try latest mcol, should be fixed, if it says to send us log then please do so, so we can investigate it

**Comment by OraclePearl** [comment]
> Try latest mcol, should be fixed, if it says to send us log then please do so, so we can investigate it

It fixes the issues, my current versions are structurize-1.20.1-1.0.659-BETA + minecolonies-1.20.1-1.1.240-RELEASE.
