### ISSUE TITLE
[BUG] Courier AI gets bugged when trying to access the warehouse

### ISSUE THREAD

**Issue by xlightningstar** [ldtteam/minecolonies#9558]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

1.1.304

### Structurize Version

1.0.661

### Current Behavior

Courier AI often bugs out when they try to access the warehouse
![image](https://github.com/ldtteam/minecolonies/assets/97979893/e71de0ab-961b-4808-8707-b941c885d847)

### Expected Behavior

Couriers working as usual

### Reproduction Steps

1. Create a colony with a warehouse and courier hut
2. Use the couriers to deposit items into the warehouse or deliver items from the warehouse

*This is the best I can do because it seems to happen randomly as far as I'm aware. Log files may indicate as to when this could happen but I have no clue what they mean.

### Logs

https://gist.github.com/xlightningstar/6c822688d02dbe471a5352e13acd60c5

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Did you unassign a courier from a warehouse mid job or so?

**Comment by xlightningstar** [comment]
> Did you unassign a courier from a warehouse mid job or so?

No, however I did move the warehouse before that, and after moving it, for about an hour or 2 all the couriers kept doing that until I restarted the server. Also happened later when I moved a courier hut. It's probably to do with moving the blocks for the buildings. I realised all this after posting the report

**Comment by Raycoms** [comment]
okay, that makes sense, I will look into it.
