### ISSUE TITLE
[BUG] Incorrect display of the building location select screen.(on Mac)

### ISSUE THREAD

**Issue by clarusthecow** [ldtteam/minecolonies#9560]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

1.19.2-1.1.306-BETA

### Structurize Version

1.19.2-1.0.661-RELEASE

### Related Mods and their Versions

1. 43.2.13
2. blockui-1.19.2-1.0.118-BETA
3. domum_ornamentum-1.19-1.0.146-BETA-universal

### Current Behavior

When I right-click the structurize stick or try to place an structure with structurize the menu displays incorrectly.
Here is the screenshot:
<img width="1440" alt="Снимок экрана 2023-11-10 в 18 07 16" src="https://github.com/ldtteam/minecolonies/assets/150455346/7d6e7ffe-e8ab-4c9c-b390-91bf163d161c">

### Expected Behavior

The menu should display in the normal size.

### Reproduction Steps

1. Open Official MineColonies Modpack on GDLauncher(on Mac)
2. Join a new world
3. Right-click the structurize stick

### Logs

https://gist.github.com/3442904/7bd57e45a5f8f52745d15147f57ef26f

### Anything else?

I tried to change interface size, but it didn't help.

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Has something to do either with an interaction with the screenscale mod or sodium etc. This is not on our side.
