### ISSUE TITLE
[BUG] Server crashed

### ISSUE THREAD

**Issue by NOTdenNes** [ldtteam/minecolonies#9561]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.2

### MineColonies Version

1.20.1-1.1.303

### Structurize Version

1.20.1-1.0.662

### Related Mods and their Versions

1. Forge Version: 47.2.4
2. Block UI Version: 1.20.1-1.0.119
3. Domum Ormamentum Version: 1.20-1.0.147

### Logs

https://gist.github.com/NOTdenNes/2de8f3f0e31afa110a5648d7392fc42e

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
This is already fixed, but Curseforge seems to be slow at the moment (version 1.1.308 is not released yet, it seems like)

**Comment by DanyloMeranov** [comment]
This is very ... odd, but git has change with spelling. Does it helps with for new structurize?

**Comment by DerTyp7** [comment]
I have the exact same issue server crashes all the time, when a builder accepts a new job.
My log looks pretty much the same: https://gist.github.com/DerTyp7/c3775dcd046d3992d73cb633d18492b0

**Comment by MotionlessTrain** [comment]
Until that version finally gets released, you could downgrade structurize one version
