### ISSUE TITLE
[BUG] Plantations their initial 3 fields are not created

### ISSUE THREAD

**Issue by Fenixphlame** [ldtteam/minecolonies#9565]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.20.1-1.1.308-BETA

### Structurize Version

1.20.1-1.0.662-BETA

### Related Mods and their Versions

ATM9 modpack

### Current Behavior

Plantations from packs with Integrated Fields do not assign fields to workers
Bug discovered using Medieval Dark Oak pack plantation, and minecolonies pack plantation field
discord tech support tested other packs and found issues in Steampunk/minecolonies/colonial packs plantations as well.

### Expected Behavior

both external and integrated plantation fields should assign to workers in the Plantation block menu.

### Reproduction Steps

build Dark oak Plantation
build Minecolonies Plantation Field nearby
check plantation block menu for assigned fields

### Logs

https://gist.github.com/Fenixphlame/0207395cd86c3522ba51c347b43688c7

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
In no circumstance do fields auto assign them to the plantation if they are children of the plantation itself, the only auto assignment is if the toggle in the fields menu is set to auto

**Comment by Talyda** [comment]
The problem is that the ones that are built in to the buildings (not using the plantation field block) are not working. (The issue didn't describe that bit quite clearly)
@Moobien  tested it with the steampunk/colonial/minecolonies original as well
(I'll find the posts and link them cos plantation flat out confuses me =P)

**Comment by Talyda** [comment]
[Here's most recent part of the discussion if that helps](https://discord.com/channels/139070364159311872/1125094832143077456/1173444410835480657)
You have to read down a fair few posts I think

**Comment by MotionlessTrain** [comment]
Has the plantation been pasted in, or built by the builder?

**Comment by Thodor12** [comment]
The issue is already known @MotionlessTrain, it's something to do with 1.20.1 and I believe Mirality was already looking into it.

**Comment by uecasm** [comment]
I started looking at it, posted my findings, and hoped you'd finish it off 😁

**Comment by Thodor12** [comment]
Guess I missed the hint, I'll look into it

**Comment by Moobien** [comment]
I my testing I pasted. The player had built theirs.

**Comment by Fenixphlame** [comment]
Update the next day, plantation started working perfectly fine after researching the jungle crops plantation upgrade in the university. all three default integrated fields, and the newly built cocoa field all appeared in the menu, and things are working as intended,
