### ISSUE TITLE
[BUG] Colony won't fill archer or guard slots

### ISSUE THREAD

**Issue by purpletiger6862** [ldtteam/minecolonies#9578]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

1.1.275-beta

### Structurize Version

1.0.660

### Current Behavior

I have unemployed colonists (5 in the screenshot, now 9). I have 0 archers or soldiers. The druid role is filled though, it seems to the the only 'guard' role that actually auto-hires. When I built the stone smeltery, that job was filled immediately also. 
![2023-11-18_13 00 05](https://github.com/ldtteam/minecolonies/assets/149257941/7690e652-3216-4387-ab10-53ed9bc5a61b)
![2023-11-18_13 00 09](https://github.com/ldtteam/minecolonies/assets/149257941/22da74eb-1218-4d21-81a9-5628884a7137)
![2023-11-18_14 26 02](https://github.com/ldtteam/minecolonies/assets/149257941/726dd192-2467-4ed8-b68b-01a790d5ba82)

### Expected Behavior

For all guard types to auto-hire new citizens when guards die or new towers are built, not just druids.

### Reproduction Steps

1. Have unemployed citizens
2. Build guard towers or have guards die.
3. Druids are the only guard type that will refill

### Logs

https://gist.github.com/purpletiger6862/924b696b2339f078a69d14eb7d2490f9.js

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Can you show the guard tower hiring settings and the colony hirind mode settings?

**Comment by purpletiger6862** [comment]
> Can you show the guard tower hiring settings and the colony hirind mode settings?

Colony hiring is set to automatic, and the guard towers have 'hire trainees' on
