### ISSUE TITLE
[BUG] World crashes when pasteing schematics that contain hut blocks

### ISSUE THREAD

**Issue by AkGamerRo** [ldtteam/minecolonies#9579]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

minecolonies-1.19.2-1.1.315-BETA

### Structurize Version

structurize-1.19.2-1.0.661-RELEASE

### Related Mods and their Versions

1. Forge 43.3.5
2. blockui-1.19.2-1.0.122-BETA
3. multipiston-1.19.2-1.2.25-ALPHA
4. domum_ornamentum-1.19-1.0.146-BETA-universal

### Current Behavior

Single player world crashes and sends the player to multi player menu when a request to paste a schematic that contains a hut block(Hospital) outside the area of any colony using the schematic paste option.

### Expected Behavior

Paste schematic in world.

### Reproduction Steps

1. have a schematic containing hut block
2. use build tool to enter preview mode
3. click confirm then schematic paste
4. single player world crash

### Logs

https://gist.github.com/AkGamerRo/e6c2f27c495544da8a8bd36b622318d0

### Anything else?

Image from world entered after crash:
![image](https://github.com/ldtteam/minecolonies/assets/46200199/2a48baa3-31ed-4739-b67b-10f32c69d7a8)

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
fixed in latest
