### ISSUE TITLE
Delivery Warehouse

### ISSUE THREAD

**Issue by Akkaross** [ldtteam/minecolonies#958]
### Minecolonies version

version 1.11.2-0.7.917 and before with .887 on a Verygames multiplayer server .

### Expected behavior

- Delivery-man collects all items from the gatherers (miner, sawmill ...) and stock them to the warehouse.

### Actual behaviour

- Delivery-man collects all items as intended, and going to the warehouse. Then items disapear from his inventory but don't go to the chests nor in the inventory of warehouse.

### Steps to reproduce the problem

1. Build a townhall. Then a builder, sawmill, miner ...
2. Build a warehouse and a deliveryman.
3. Hire a deliveryman.
4. Wait and watch deliveryman eating all your ressources. ;o)

**Comment by wilsondgonzales** [comment]
@Akkaross this problem has been fixed. update to at least 7.930
