### ISSUE TITLE
[BUG] neutral monsters attack colonists

### ISSUE THREAD

**Issue by SonicTheHedgehog58987276** [ldtteam/minecolonies#9580]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.20.1-1.1.240-release

### Structurize Version

doesn't have to do with structurize

### Current Behavior

neutral monsters except endermen attack citizens example, spiders attack citizens at daytime while neutral to players

### Expected Behavior

neutral mobs be nice to citizen until one provokes them

### Reproduction Steps

1. supply camp or ship placement
2. place townhall and create colony
3. spawn spider at daytime after first colonist arrives

### Logs

no need

### Anything else?

* i am affected
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by SonicTheHedgehog58987276** [comment]
music to describe how terrible the issue seems: https://www.youtube.com/watch?v=CunvBXTAt9E&list=OLAK5uy_k4Mj5z3DDi994D3vlOzF8FoamaswdzG30

**Comment by Raycoms** [comment]
While, spiders and endermen see players as threats, they see citizens as easy targets to pick off. Thats why they go after them in broad daylight! Quick, build out the barracks to neutralize the threat!

**Comment by SonicTheHedgehog58987276** [comment]
or defend colonists yourself?

**Comment by Raycoms** [comment]
to arms!

**Comment by SonicTheHedgehog58987276** [comment]
so does "to arms!" mean you can defend them yourself?

**Comment by Raycoms** [comment]
indeed

**Comment by SonicTheHedgehog58987276** [comment]
did you listen to repulsive in the dark yet?

**Comment by Raycoms** [comment]
https://media.tenor.com/SOey404oLmsAAAAM/schitts-creek-david-rose.gif

**Comment by SonicTheHedgehog58987276** [comment]
i play in creative mode often

**Comment by SonicTheHedgehog58987276** [comment]
so i can bust those mobs!

**Comment by SonicTheHedgehog58987276** [comment]
...And Build More Quickly For More Fun!

**Comment by SonicTheHedgehog58987276** [comment]
Any Mob That Kills My Citizens Are Gonna Have A Bad Time. https://www.google.com/imgres?imgurl=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fen%2Fthumb%2F0%2F01%2FSans_undertale.jpg%2F220px-Sans_undertale.jpg&tbnid=ZRGW4D2KgdROrM&vet=12ahUKEwjd1se1uNCCAxWewMkDHYf2BzUQMygAegQIARB1..i&imgrefurl=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FSans_(Undertale)&docid=g1nwMOpvzWNVZM&w=220&h=294&q=sans&client=firefox-b-1-d&ved=2ahUKEwjd1se1uNCCAxWewMkDHYf2BzUQMygAegQIARB1ve A Bad Time.

**Comment by SonicTheHedgehog58987276** [comment]
any mobs that kill my citizens are gonna have a bad time.                                                       ![sans](https://github.com/ldtteam/minecolonies/assets/115895321/f05a75e2-9f2b-4096-9bee-77b267bb754d)
