### ISSUE TITLE
[BUG] [1.19.2] New Townhall UI Alignment and Button Placement issues.

### ISSUE THREAD

**Issue by Sandriell** [ldtteam/minecolonies#9582]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

1.19.2-1.1.322-BETA

### Structurize Version

1.19.2-1.0.661-RELEASE

### Related Mods and their Versions

Forge: 43.2.21

### Current Behavior

On the Actions page of the new Townhall UI, some of the text elements are overflowing underneath their counterpart buttons. Additionally, the newly added citizen style texture reset button completely covers up the style selection button.

Interestingly enough when looking at the pull request for this, I noticed some of my UI text labels are different than the ones shown in those screenshots. "Hiring Mode" versus "Worker Hiring Mode" for example. Was an updated language file mistakenly excluded?

![2023-11-19_12 47 55](https://github.com/ldtteam/minecolonies/assets/10704907/c5b5c3c5-3fe8-45c9-b80f-b8bd00939a9a)

### Expected Behavior

No overlapping elements.

### Reproduction Steps

Just.. look at it?

### Logs

N/A

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Sandriell** [comment]
Turns out the resource pack Unity Dark (https://legacy.curseforge.com/minecraft/texture-packs/unity-dark-edition) is shipping with its own copy of the en_us.json for Minecolonies.

**Comment by Raycoms** [comment]
the reset button only covers it for none patreons if you dont have the default chosen.

**Comment by Sandriell** [comment]
Didn't mean to close this, as the reset button is still overlapping the citizen style button.. but maybe that is intentionally for non-patrons?

**Comment by Sandriell** [comment]
Oh, well than no issues at all! lol

**Comment by Sandriell** [comment]
Reported this issue to Unity Dark https://github.com/Unity-Resource-Pack/Unity-Dark/issues/119
