### ISSUE TITLE
[BUG] when you feed citizens food in bowls they eat the bowl

### ISSUE THREAD

**Issue by SonicTheHedgehog58987276** [ldtteam/minecolonies#9585]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.20.1-1.1.240-release

### Structurize Version

not related to structurize

### Current Behavior

the bowl disappears after bowl food is eaten

### Expected Behavior

the bowl is emptied

### Reproduction Steps

1. feed citizen bowl food (example: mushroom stew)

### Logs

https://gist.github.com/SonicTheHedgehog58987276/45e7a2d63c8b2e908237489024d47eca

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments. i am affected
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by cheesehead5835853853** [comment]
SonicTheHedgehog, YOU'RE CRINGE!!!

**Comment by cheesehead5835853853** [comment]
(sonic the hedgehog is my old account)
