### ISSUE TITLE
[BUG] Supply camp/ship error highlights remain after placement

### ISSUE THREAD

**Issue by kezmodius** [ldtteam/minecolonies#9586]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [X] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

321.beta

### Structurize Version

??

### Related Mods and their Versions

Unknown. Uncertain if it is 1.19.2 and 1.20.1, or either/or.

### Current Behavior

This is a just a heads up report for dev team
Many reports on main discord regarding highlights remaining after placing supply camps / ships. Started immediately after version .321 was released.
My advice has been to restart Minecraft and this has worked to remove them. Relog alone does not remove them.

### Expected Behavior

Highlights to disappear after placement

### Reproduction Steps

Place supply camp or ship
Observe highlights do not go away.

### Logs

Discord reports below

### Anything else?

Screenshots included on these discord reports below.
https://discord.com/channels/139070364159311872/1003402487417548801/1175996369018830951
https://discord.com/channels/139070364159311872/1125094832143077456/1176692042814988308
https://discord.com/channels/139070364159311872/1003402487417548801/1176307330191728680
https://discord.com/channels/139070364159311872/1003402520846139533/1176458553935003658
https://discord.com/channels/139070364159311872/1003402487417548801/1175876932739543100

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Cybercube21** [comment]
Also happens to me on 1.20.1-1.1.321-BETA
