### ISSUE TITLE
[BUG] Teaching recipes to crafters does not fully work to update clipboards etc.

### ISSUE THREAD

**Issue by Shadizar** [ldtteam/minecolonies#9587]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.20.1-1.1.321-BETA

### Structurize Version

1.20.1-1.0.662-BETA

### Related Mods and their Versions

forge 47.2.0
blockui-1.20.1-1.0.125-BETA.jar
domum_ornamentum-1.20-1.0.147-BETA-universal.jar
multipiston-1.20-1.2.31-ALPHA.jar

### Current Behavior

teaching a recipe often doesn't make the 'ding' and doesn't remove the 'need' from the clipboard. The recipe is in fact taught
Happens for normal recipes and DO, at all crafters including like builder; canceling from clipboard, they figure it out
I'd estimate it happens 40% of the time or so; the rest of the time the normal ding occurs and the clipboard immediately updates

### Expected Behavior

Ding
immediate clipboard updates (for normal recipes at least)

### Reproduction Steps

Open crafter UI 
Use JEI to search and teach a recipe (for example some stone or wood slab)
Click Learn

### Logs

https://gist.github.com/Shadizar/3a4215d3b90083f92f966926f495d5f2

### Anything else?

Multiple persons reported in 1.20 discord (at least 2 others IIRC)

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Braastos** [comment]
Having the same issue in minecraft 1.19.2 (big modpack) so its not 1.20 only issue
Minecolonies 1.19.2-1.1.323-BETA
Structurize 1.19.2-1.0.661-RELEASE
forge 43.2.14
Block UI 1.19.2-1.0.127-BETA
Multi-Piston 1.19.2-1.2.25-ALPHA
Domum Ornamentum 1.19-1.0.146-BETA

**Comment by Sandriell** [comment]
Can also confirm that on 1.19.2, both requests are not properly getting updated and there is no feedback for new recipes added. You click add, and while the recipe is indeed getting added, visually/audibly nothing happens to confirm it.

**Comment by janisl** [comment]
I just updated to latest and it started to happen to me as well. It's 1.20.1.

**Comment by Raycoms** [comment]
Fix pending

**Comment by janisl** [comment]
Still broken for DO recipes.

**Comment by Sandriell** [comment]
Just came to add the same, issues still existing when adding DO recipes.

minecolonies-1.19.2-1.1.332-BETA

**Comment by Raycoms** [comment]
fix pushed for DO too
