### ISSUE TITLE
[BUG] Citizen Glitching

### ISSUE THREAD

**Issue by SonicTheHedgehog58987276** [ldtteam/minecolonies#9589]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.20.1-1.1.240-release

### Structurize Version

probably not related to structurize

### Current Behavior

shaking while flashing red

### Expected Behavior

normal citizens

### Reproduction Steps

happens randomly

### Logs

https://gist.github.com/SonicTheHedgehog58987276/6aaecc8e54f603d8aa120fb4ae272e78

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments. i am affected
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by SonicTheHedgehog58987276** [comment]
Image Of Glitching While I Do Archery:
![2023-11-22_16 02 19](https://github.com/ldtteam/minecolonies/assets/115895321/07310b14-4ae6-4af1-9e0e-b34deba6f7cb)

**Comment by Thodor12** [comment]
There is nothing in Minecolonies that does this, I can tell from that image this is some sort of modpack as there are things going on that are not vanilla.

In the future, please stop making reports like this and ask on Discord first whether this is even a bug to begin with, my guess is that this is an Optifine/Rubidium issue and has nothing to do with Minecolonies.

**Comment by SonicTheHedgehog58987276** [comment]
it is not a modpack

**Comment by SonicTheHedgehog58987276** [comment]
it is my mod folder

**Comment by SonicTheHedgehog58987276** [comment]
it is not optifine either, optifine wont work

**Comment by Thodor12** [comment]
You have several items on your hotbar which are not vanilla nor Minecolonies, which means other mods are involved.
You also provided a partial latest.log, so we cannot do anything with that.

**Comment by SonicTheHedgehog58987276** [comment]
yes, still this is not a modpack, it is a forge mod loader folder

**Comment by SonicTheHedgehog58987276** [comment]
btw, after a builder died, i got upset and bsod my pc (days ago in real life, not mc time}

**Comment by Thodor12** [comment]
That doesn't matter, other mods are other mods.

Also please stop unnecessarily commenting on these issues, otherwise I'm going to lock this issue once again.

**Comment by SonicTheHedgehog58987276** [comment]
how can i talk to you then?

**Comment by Thodor12** [comment]
If you want this resolved I suggest you go to [discord](https://discord.minecolonies.com) and go to the support channels, Github issues are not the correct place for this kind of discussion.

**Comment by SonicTheHedgehog58987276** [comment]
do you know what bsod means?
