### ISSUE TITLE
Spawnable spots in warehouse

### ISSUE THREAD

**Issue by Anakardian** [ldtteam/minecolonies#959]
### Minecolonies version

version 0.8.4  or curse 0.7.4.2.1

### Expected behavior

When upgrading warehouse there should be no spawnable areas after the builder is finished.

### Actual behaviour

The top floor has several spawnable spots in the area away from the ladder
As a minimum this occurs on the final upgrade and maybe earlier levels as well.

### Steps to reproduce the problem

1. Build warehouse
2. upgrade warehouse
3. after each upgrade, check for spawnable spots
4. run away from creepers in the warehouse?

**Comment by Anakardian** [comment]
Raycoms asked me to tag it with @pmardle

**Comment by Raycoms** [comment]
@pmardle

**Comment by Raycoms** [comment]
Should be fixed in the newest alpha
