### ISSUE TITLE
[BUG] Farm Request dint work

### ISSUE THREAD

**Issue by Roc25** [ldtteam/minecolonies#9593]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.20.1-1.1.321-BETA

### Structurize Version

1.20.1-1.0.662

### Current Behavior

Cowhand requests wheat and in this request the player is indicated as the resolver, although in colony is a working farm with wheat. But for planter it works normal, requests for sugar cane are displayed correctly and resolved by the planter
![image](https://github.com/ldtteam/minecolonies/assets/88423841/4dc7b8e0-8816-4ad4-9bf5-f901d66ded32)
![image](https://github.com/ldtteam/minecolonies/assets/88423841/b7b4c66b-6e83-468a-9c5f-b87e668c5730)

### Expected Behavior

Farmer must accept request for wheat

### Reproduction Steps

Build wheat farm and request wheat

### Logs

-

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
Farm's don't grow wheat to request =)

**Comment by Roc25** [comment]
I figured it out, if possible I would like to ask that it look like with a planter
