### ISSUE TITLE
[BUG] Guards not hiring trainees

### ISSUE THREAD

**Issue by janisl** [ldtteam/minecolonies#9595]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.20.1-1.1.328-BETA

### Structurize Version

1.20.1-1.0.662-BETA

### Current Behavior

Guard towers don't hire from combat academy or archery.

### Expected Behavior

Giards are hired.

### Reproduction Steps

1. Set colony to manual hiring
2. Build combat academy/archery and set to automatic hiring
3. Set guard tower to automatic

### Logs

https://gist.github.com/janisl/2173a6fd0684a3bfd0b0b3853b6df8cd

### Anything else?

The issue only started after I built combat academy and archery.

Also after I hired all trainees other guard towers could directly hire available citizens.

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Is "hire trainees" turned on in the guard tower?

**Comment by janisl** [comment]
Yes, it is. And if there are trainees guards are not hired at all. Only when there are no more trainees it automatically hires.

**Comment by Raycoms** [comment]
fixed
