### ISSUE TITLE
[BUG] Archer reported AI failure.

### ISSUE THREAD

**Issue by DragonMotion** [ldtteam/minecolonies#9597]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

1.1.329- BETA

### Structurize Version

1.0.661-RELEASE

### Related Mods and their Versions

Forge 1.19.2 - 43.3.5
Divine RPG

### Current Behavior

Archer reported AI failure when used Inferno Bow from DivineRPG mod. A lot of errors at the end of the log.

### Expected Behavior

Work without errors

### Reproduction Steps

Give the archers the Inferno Bow from the DivineRPG mod. Wait for errors.

### Logs

https://gist.github.com/DragonMotion/c4c3dfc441b11e731bcd5ad159105018

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
fixed
