### ISSUE TITLE
[BUG] Food Duplication Bug

### ISSUE THREAD

**Issue by Zygus42** [ldtteam/minecolonies#9598]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

minecolonies-1.20.1-1.1.328-BETA

### Structurize Version

minecolonies-structurize-1.20.1-1.0.662-BETA

### Related Mods and their Versions

forge-1.20.1-47.2.1-installer
minecolonies-blockui-1.20.1-1.0.124-BETA
minecolonies-domum_ornamentum-1.20-1.0.147-BETA-universal
minecolonies-multipiston-1.20-1.2.31-ALPHA
minecolonies-stylecolonies-1.2

### Current Behavior

Recently updated from minecolonies-1.20.1-1.1.287-BETA to minecolonies-1.20.1-1.1.328-BETA.  Since then, whenever a colonist eats any kind of food item, it duplicates the stack of food they're eating from for every time they eat from that stack.  We are getting stacks of 3,000-4,000 of a cooked food item in our warehouses over the period of a single minecraft day (although we are running longer days).

### Expected Behavior

Eat without duplicating food.

### Reproduction Steps

Watch a colonist eat.

### Logs

https://pastebin.com/QAhR73SU

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Zygus42** [comment]
Worth noting that you also lose an entire stack of food if you right-click on a colonist with it, where in the past it would only use 1 item.

**Comment by Raycoms** [comment]
hotfix pushed for both
