### ISSUE TITLE
[BUG] [1.19.2] Students in the Library are Hoarding Food!

### ISSUE THREAD

**Issue by Sandriell** [ldtteam/minecolonies#9600]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

1.19.2-1.1.332-BETA

### Structurize Version

1.19.2-1.0.661-RELEASE

### Related Mods and their Versions

Forge: 43.2.21

### Current Behavior

I just happened to notice that all of my students in the library are carrying around multiple stacks of food. I removed a bit over 90 _stacks_ of food off the 8 students I had in the library.

Near as I can tell, they are the only ones with this issue. I looked at many other citizens and they are all carrying around the normal amount of food, like 5 or less.

It is not food I have given them either (as in right clicking on them with it) because it is not the same food I carry around to eat myself.

### Expected Behavior

Not hoarding food!

### Reproduction Steps

Sadly not sure here. I do not know when or how they accumulated so much food, or if they are duplicating it somehow. Also not sure why is is just students in the library.

I will continue to observe ands see if I can spot when it happens.

### Logs

N/A

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
That was the food duplication bug we had. Its fixed int he latest

**Comment by Talyda** [comment]
Isn't .332 the latest Ray? That one says hotfix in the changelog. 
Someone else said in .332 as well they are still taking a stack of food when clicked on (or did the fixed one not get released yet?)

**Comment by Raycoms** [comment]
Yeah, but if you had food duplicate pre 332 and then you visit your library students in 332, they will have a lot of food.

**Comment by Talyda** [comment]
Ah, kk.
Just someone said earlier today they were still taking a stack when they clicked on them, so thought maybe it hadn't gone out yet (I don't think they made an issue for it)

**Comment by Sandriell** [comment]
Ok, good deal.
