### ISSUE TITLE
[BUG] [1.19.2] Barracks Guards do not go to the Hospital

### ISSUE THREAD

**Issue by Sandriell** [ldtteam/minecolonies#9601]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

1.19.2-1.1.336-BETA

### Structurize Version

1.19.2-1.0.661-RELEASE

### Related Mods and their Versions

Forge: 43.2.21

### Current Behavior

When guards in the barracks get sick they will not go to the hospital, though they do seem to try to. Instead they will just pace back and forth from the barracks to about 1/3 of the way to the hospital.

If I speak to them just before the turn around, they will continue a little further towards the hospital and then I have to speak to them again, to make them go a little further-er. Sometimes I can get them all the way there doing this dance, but half the time after arriving at the hospital finally they will hang around a bit and then just leave without getting cured.

Sometimes the doctor will try and chase them down too.

I am also unable to cure the manually. I have given them the cure items, but they do not use them, and just keep doing the pacing.

Possibly related, they are set to patrol, and since they patrol as a group, it almost seems like they are fighting their desire to stay with their group versus going to the hospital. Would explain why this issue does not seem to effect normal guards at all.

### Expected Behavior

For them to properly go to the hospital and to stay there until cured.

### Reproduction Steps

Have a Hospital and Barracks a decent distance apart.
Guards in barracks get sick.

### Logs

N/A

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by evan1026** [comment]
Not sure if this helps, but I'm also seeing this on 1.20.1 and I've noticed that the group will eventually make its way to the hospital, but it seems like it's only once the entire party is infected. Then the doctor will cure them and they will go about their business. In the meantime though they've already gone around and spread the sickness throughout the town on their patrols

**Comment by Raycoms** [comment]
should be fixed/improved
