### ISSUE TITLE
[BUG] The coordinates of the settler's death are not displayed.

### ISSUE THREAD

**Issue by DragonMotion** [ldtteam/minecolonies#9608]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

1.19.2-1.1.339-BETA

### Structurize Version

1.19.2-1.0.661-RELEASE

### Current Behavior

The coordinates of death are not displayed when the Russian language is used.

### Expected Behavior

Displaying the coordinates of the settler's death when the Russian language is used.

### Reproduction Steps

1. Set the Russian language.
2. Kill the settler using the chat command.
3. The coordinates will not be displayed.
![2023-12-05_235952](https://github.com/ldtteam/minecolonies/assets/18142911/8a01e610-650f-491f-966e-d5cf1a4cc390)

### Logs

none

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
That needs to be fix by a translator on translate.minecolonies.com then
