### ISSUE TITLE
Chickens escaping 

### ISSUE THREAD

**Issue by smmmadden** [ldtteam/minecolonies#9614]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.1.344-BETA

### Structurize Version

1.0.662-BETA

### Related Mods and their Versions

Forge: 47.2.17
BlockUI: 1.0.128-BETA
Domum Ornamentum 1.0.147-BETA

### Current Behavior

Chickens are escaping faster than the farmer can keep them inside
Doors are taking too long to close behind the farmer

### Expected Behavior

Chickens should not be able to escape at all

### Reproduction Steps

Just watch the farmer and chickens leaving the coup.  Screen shots show the doors and type of build.
![2023-12-10_22 48 37](https://github.com/ldtteam/minecolonies/assets/10309346/95250197-8b30-4ee1-9ffb-bc1d81edf18c)
![2023-12-10_22 49 25](https://github.com/ldtteam/minecolonies/assets/10309346/6fe9ae51-6a7d-44ce-a5f5-0f42b74453b6)

### Logs

not applicable

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by smmmadden** [comment]
same issue with the Rabbits - I put in extra gates to keep them in but even then they get out. :-(
![2023-12-10_23 00 41](https://github.com/ldtteam/minecolonies/assets/10309346/011ea667-0749-4d07-8884-7eebbfe470ef)

**Comment by samohtGTO** [comment]
1.19.4 has the same issue with chicken and cows this is bc of the cows and chickens walking thru the fence gates when opened by the worker.

**Comment by Moobien** [comment]
not a bug.

**Comment by smmmadden** [comment]
I disagree, there are other styles where this is not an issue and chickens, cows, pigs and sheep do not escape.  If the pens are too confined they will more likely escape especially when the gates/doors take too long to close.  The farmer should not let so many of each be present as it should be breeding and controlling the population to reduce the risk of them getting out as well. :-)

**Comment by Thodor12** [comment]
This is just as much of an issue on every single building, on top of that there is a separate thread for schematic issues, do not make separate issues for this.

**Comment by Moobien** [comment]
> I disagree, there are other styles where this is not an issue and chickens, cows, pigs and sheep do not escape. If the pens are too confined they will more likely escape especially when the gates/doors take too long to close. The farmer should not let so many of each be present as it should be breeding and controlling the population to reduce the risk of them getting out as well. :-)

still not a mod bug.

**Comment by smmmadden** [comment]
very disappointing

**Comment by Sandriell** [comment]
I would argue the mod "bug" is both, that they are slow to close the doors/gates behind them, and sometimes, though rarely, they do not close them at all.
