### ISSUE TITLE
[BUG] Crash - ClassCastException EntityCitizen to Player - Multi Player

### ISSUE THREAD

**Issue by JimWalkerii** [ldtteam/minecolonies#9615]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

1.1.349-BETA

### Structurize Version

1.0.661

### Related Mods and their Versions

Forge-3.2.2
1.0.129
Basically taken the Direwolf 20 1.19.2 packet and updated Minecolonies and relative mods

### Current Behavior

It's a random crash, usually with pirates active. I can fly over to the colony in question and it doesn't crash. 
Then fight/clear the pirates and then the person can log in.
It is only 1 of the 6 players causing this issue. 
Reading the other git-issues., likely the pathing issues,

### Expected Behavior

Need to resolve the crashing issue. :)

### Reproduction Steps

Full log attached, if you need map files let me know.

### Logs

https://gist.github.com/JimWalkerii/5dbaebe175cad1cae184e58400b4205a

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
Report to https://github.com/dragoni7/Silent-Compat, they appear to be assuming that citizens are players.
