### ISSUE TITLE
Patrol Mine No Longer an Option

### ISSUE THREAD

**Issue by Moobien** [ldtteam/minecolonies#9616]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.1.354

### Structurize Version

n/a

### Related Mods and their Versions

n/a

### Current Behavior

updated to 354 from 350 and noticed a guard following me. turns out it was the guard I had set to patrol the mine.  Went to check at their hut and they were set to follow and patrol mine was no longer an option. only guard, follow and patrol.

### Expected Behavior

err well I expect to have the ability to have guards patrolling the mine

### Reproduction Steps

1: hire guard
2: try to assign guard to mine....

### Logs

b/a

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
fixed
