### ISSUE TITLE
[BUG] Builder/Farmer AI Error and Stops Doing Their Jobs

### ISSUE THREAD

**Issue by SCBionicle** [ldtteam/minecolonies#9619]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.2

### MineColonies Version

minecolonies-1.20.1-1.1.354-BETA

### Structurize Version

structurize-1.20.1-1.0.664-BETA

### Related Mods and their Versions

Forge: 47.2.0
Block UI: blockui-1.20.1-1.0.128-BETA
Domum Ornamentum: domum_ornamentum-1.20-1.0.147-BETA-universal

### Logs

https://gist.github.com/SCBionicle/c14d72d1c162037da4300e153f7612fe
https://gist.github.com/SCBionicle/5bb337f6c0c3a21e1a694909010c9ea5

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by SCBionicle** [comment]
Farmer instance log: https://gist.github.com/SCBionicle/5bb337f6c0c3a21e1a694909010c9ea5

**Comment by Thodor12** [comment]
Should be already fixed in the newest version, please reopen if not

**Comment by SCBionicle** [comment]
It is newest version, problem reoccurred on the latest: minecolonies-1.20.1-1.1.355-BETA

**Comment by SCBionicle** [comment]
Please see this gist, it was on the newest: https://gist.github.com/SCBionicle/5bb337f6c0c3a21e1a694909010c9ea5

**Comment by SCBionicle** [comment]
When will this be released to CF? I'm eager to deploy this to my server.

**Comment by Raycoms** [comment]
356 with it should be out
