### ISSUE TITLE
Button confusion.

### ISSUE THREAD

**Issue by fallenhunter1** [ldtteam/minecolonies#962]
### Expected behavior
Full name of button(stone), or Button(wood)

### Actual behavior
Just asks for Button. Confusing at least, not game breaking, but a hassle.

### Steps to reproduce the problem
Any building requiring buttons, just ask to build/upgrade one.

**Comment by Raycoms** [comment]
I'd say in this case Minecraft is a dick because they named both exactly
the same, we would have to create an extra logging case only for this.
@Kostronor

2017-05-09 16:44 GMT-03:00 fallenhunter1 <notifications@github.com>:

**Comment by xavierh** [comment]
We should add the item icon on the resources needed tab
