### ISSUE TITLE
[BUG] <My game crashes when I open the world>

### ISSUE THREAD

**Issue by spacememories** [ldtteam/minecolonies#9623]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.2

### MineColonies Version

1.2

### Structurize Version

1.20.1

### Reproduction Steps

1. Open minecraft game through the curse forge MineColonie mod 
2. open world 
3. game crashes

### Logs

https://gist.github.com/spacememories/4839fd041355ced43542b3ca2198bc89

### Anything else?

exit code: 6

**Comment by someaddons** [comment]
looks like a terrablender issue with macos, unrelated to minecolonies unless you can reproduce it with just minecolonies
