### ISSUE TITLE
[BUG] Zombies can break the gate like vanilla wooden door

### ISSUE THREAD

**Issue by mc-kaishixiaxue** [ldtteam/minecolonies#9626]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.20.1-1.1.359-BETA

### Structurize Version

1.20.1-1.0.662-BETA

### Current Behavior

Minecolonies' gates can defend the raiders' breaking, but they can't defend many zombies in hard difficulty. The gates' usage defeats its original purpose.

### Expected Behavior

Zombies can't break gates, or breaking them needs longer time.

### Reproduction Steps

1. Set the difficulty to `Hard`;
2. Use `/summon minecraft:zombie ~ ~1 ~ {CanBreakDoors:1b}` to summon a zombie who can break the wooden door;
3. Put some Minecolonies' gates;
4. Let this zombie try to break these gates.

### Logs

No log

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
Not a bug, the gates do not prevent raiders from breaking them, your raiders are not at the minimum requirement yet for them to break gates (or they just plain haven't tried it yet).

**Comment by Raycoms** [comment]
The gated should take a bit longer than a vanilla door, but a horde can still break it.

**Comment by Raycoms** [comment]
There is research to extend the break time.
