### ISSUE TITLE
[BUG] registry trying to load before mod is loaded

### ISSUE THREAD

**Issue by Swantsy** [ldtteam/minecolonies#9628]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [ ] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [x] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [X] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.20.1-1.1.344-BETA

### Structurize Version

1.20.1-1.0.662-BETA

### Related Mods and their Versions

ATM 9 version 0.2.28

### Current Behavior

Full game crash upon completing one of the quests 

### Expected Behavior

no game crashing

### Reproduction Steps

Finish one of the quests in the quest book. Somtetimes it takes 2 quests.

### Logs

https://api.paste.ee/p/1YOxP

### Anything else?

[iron431](https://github.com/iron431) commented [7 minutes ago](https://github.com/iron431/all-the-wizard-armor/issues/4#issuecomment-1859217280)
at com.minecolonies.api.compatibility.CompatibilityManager.discoverAllItems(CompatibilityManager.java:633) ~[minecolonies-1.20.1-1.1.344-BETA.jar%23754!/:1.20.1-1.1.344-BETA] {re:classloading}

This looks like an issue with minecolonies attempting to load our registry before our mod has loaded. You should also report this to them. I would have to look into this further to see if there's anything I can do on my end

**Comment by Raycoms** [comment]
That is FTB quests. Ours is jsut a warning, the actual crash is unrelated to us.
