### ISSUE TITLE
[1.11.2 MC 0.7.930] Colonists spawn with all 1 for attributes

### ISSUE THREAD

**Issue by wilsondgonzales** [ldtteam/minecolonies#963]
I've killed a bunch to get colonists with the right attributes for a job but now have a bunch of em with 1s across all attributes. if it was intended that they level up as they go, great. I also can't provide a log as it's not really an error that shows up on the log

also is there anywhere to read up on mc commands? if a colonist did die, i would look to respawn them but if the colony reaches max size, would it then be impossible?

**Comment by Raycoms** [comment]
What is your colony happiness?

2017-05-09 17:21 GMT-03:00 Wilson Gonzales <notifications@github.com>:

**Comment by wilsondgonzales** [comment]
@Raycoms happiness is 5

**Comment by wilsondgonzales** [comment]
i noticed that my colony happiness went down to 1. Could me slaughtering the colonists be the cause?

**Comment by Raycoms** [comment]
Yes definitively. Killing citizen sets happiness to 1

2017-05-11 3:40 GMT-03:00 Wilson Gonzales <notifications@github.com>:

**Comment by Raycoms** [comment]
They spawned all on all stats 1 even with happiness 5?
I'll have to take a look at that one =D
