### ISSUE TITLE
[BUG] [1.19.2] Invalid Player Data - Cannot Login to Dedicated Server

### ISSUE THREAD

**Issue by Sandriell** [ldtteam/minecolonies#9631]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

1.19.2-1.1.370

### Structurize Version

1.19.2-1.0.665-BETA

### Related Mods and their Versions

Forge: 43.3.5

### Current Behavior

Getting an error "Invalid Player Data" when attempting to login to a dedicated server. Also noticed, during server start that Minecolonies updated from backup several times during start up.

Error seems related to the request system?

Included log is from dedicated server, from startup till the login error. Nothing meaningful on the client side, but can include that if requested.

### Expected Behavior

Able to login normally, and not restoring from backup.

### Reproduction Steps

Assume just updating and trying to login to a dedicated server will do it.

### Logs

https://gist.github.com/Sandriell/4f0c6eb68532f75a75832534a8f28795

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by PhweeDev** [comment]
Same issue here. Tried joining my friend, kept getting disconnected, their log said my playerdata was invalid.

**Comment by ghost** [comment]
same issue after updating minecolonies from 350 to 369 on mc 1.20.1. Update to 361 works well

**Comment by Sandriell** [comment]
Can confirm, working again on latest (371) version!
