### ISSUE TITLE
[BUG] Forester keeps picking up logs and doing nothing when they don't have enough logs for a stripping request

### ISSUE THREAD

**Issue by RadCppkiller** [ldtteam/minecolonies#9639]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.1.152-BETA

### Structurize Version

1.0.631-BETA

### Related Mods and their Versions

Domum ornamentum 1.0.129-BETA
block UI 0.0.94-ALPHA

### Current Behavior

When the forester receives a stripped log request, if they don't have enough logs to complete the entire request, they will pick up as many logs as possible from the rack(s), bring it to their hut block, do nothing with it and place it back on the rack. They will repeat this loop seemingly forever. Manually giving them enough logs to complete the request fully will make them start crafting.

### Expected Behavior

The forester receives the request and either crafts the required amount of stripped logs if enough are in storage or cuts wood until that is the case

### Reproduction Steps

1. Have a request for stripped logs (This happened with the miner requesting stripped logs for a mineshaft)
2. Make sure there aren't enough logs to immediately complete that request in full
3. Observe the actions of the forester

### Logs

https://gist.github.com/RadCppkiller/3f26e7c04d908e3d8dc2c950ae868139

**Comment by SailorEffinMoon** [comment]
Yep, same here

**Comment by Nik-Was** [comment]
Can confirm I experienced the same thing, and the same with plantations and farms too (but on 1.19, haven't tested on 1.20)
