### ISSUE TITLE
[BUG] Builders using tools to break blocks that do not require tools

### ISSUE THREAD

**Issue by Nik-Was** [ldtteam/minecolonies#9645]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.20.1-1.1.375-BETA

### Structurize Version

1.20.1-1.0.664-BETA

### Current Behavior

When clearing out the area for a building, if the current block does not require a tool to be broken (grass with "Use shears" turned off, flowers, etc.), builders will proceed to break that block using whichever tool they used to break the previous block.
If the tool is removed from that slot, they will proceed to break the grass with an empty hand. If the tool in that slot is replaced by another item, they will proceed to break the grass with that item.

### Expected Behavior

Builders switch to an empty hand when clearing out blocks that do not have a required tool.

### Reproduction Steps

1. Place a building that, in order to be constructed by a builder, will require some grass (or flowers etc.) to be cleared out
2. Ensure there is at least one solid block the builder will need to remove before removing grass
3. Turn off "Use shears" in a builder's hut and order that builder to construct the building, giving them appropriate tools for breaking the solid block(s)

### Logs

https://gist.github.com/Nik-Was/61981593157e47986f40e3a8e91fa164

### Anything else?

I have been noticing this for years at this point as far as I remember, over multiple Minecraft versions, so just assumed it was intended, but Estyria in the discord server said it probably isn't, so I'm making this report here.
I think it might have started happening after a tool requirement for grass was added and then removed again, but not completely sure.

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Does the tool lose durability in the meanwhile?

**Comment by Nik-Was** [comment]
Yes, of course. Otherwise I wouldn't consider it a bug, sorry it wasn't obvious.

**Comment by Nik-Was** [comment]
Another thing I noticed while testing this - also not sure if intentional or not:
They don't harvest tall grass. With "use shears" turned on they still treat tall grass as not needing a tool, and if they break some normal grass with shears and then go to break the tall grass with them, it still is destroyed, not picked up as grass.
