### ISSUE TITLE
[BUG] Disabling a mob as "Hostile" at a guard tower/barracks tower doesn't seem to stick.

### ISSUE THREAD

**Issue by rexwreckage** [ldtteam/minecolonies#9654]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.18

### MineColonies Version

1.20.1-1.1.375-BETA

### Structurize Version

1.20.1-1.0.670-BETA

### Related Mods and their Versions

EvilCraft 1.2.35

### Current Behavior

Backstory: Our guards go absolutely buckwild whenever any sort of combat or danger appears or anything dies, shooting at each other/nothing at all, and throwing potions and stuff.  It's funny but colonists do get hurt sometimes.

I was told on the discord that this is likely because (as I use ATM9) I have EvilCraft installed.  EvilCraft spawns "Vengeance Spirits" when something dies, which apparently guards can aggro on, causing this.

I was told further that the fix for this is to go to guard towers and disable Vengeance Spirits from the list of Hostiles in its UI.  I do that, then walk away from the guard tower for 10 seconds, I walk back and "Vengeance Spirits" is again labeled "On" when I just changed it to "Off."

All guard towers are doing this.  This survives restarts of the server.

### Expected Behavior

I'd expect that telling guard towers that Vengeance Spirits are not in the "Hostiles" list would stick.

### Reproduction Steps

1. Go to a guard tower, open the Hostiles UI
2. Disable Vengeance Spirits from the list, change their entry to "Off" and walk away
3. Go back later and it's "On" again without you doing anything

### Logs

https://pastebin.com/RfkF5RLR

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Probably even better to datapack disable them entirely. But yeah the non sticky thing sounds odd.
