### ISSUE TITLE
[Feature] Waypoints for players

### ISSUE THREAD

**Issue by xavierh** [ldtteam/minecolonies#966]
This is **not** about the way-points use by the citizen for pathfinding!

Add a way point system a bit like journeyMap but for minecolonies.

Way-points could be pointing to Huts, Colony centre, citizens and will be created automatically.

We should be able to see a way-point when:
- Outside the colony to indicate the colony centre;
- Citizen when requesting something (only when player is inside the colony)
- Huts when something need to me looked at (for instance when the chest is full)

Use different icons depending of the way-point:
- For the colony as owner
- For the colony as officer
- For hut
- For citizen

Additionally the player could set his own way points by defining:
- its position 
- label
- icon
- colour
- min range i.e. only display if we are further than the minimum range.
- max range i.e. only display if we are closer than the maximum range.

**Comment by ghost** [comment]
Out of curiosity, why not just use JourneyMap or one of the other systems that add waypoints? Is there a intent that MineColonies be played without other mods?

**Comment by Raycoms** [comment]
It would be possible to solve this via an integration with journeymap, but then we would depend on journeymap to show them and players who don't have journeymap wouldn't enjoy this.

**Comment by ghost** [comment]
Oh, I get it. It's not about the waypoints, it's about integration with the Minecolonies activity. You could use another mod and add a waypoint for the colony, but it won't show you where colonists are or where the border is or where other colonies are on a MP server.

**Comment by Raycoms** [comment]
Closed in favor of joint issue.
