### ISSUE TITLE
Deliveryman/Warehouse bug v0.8.930

### ISSUE THREAD

**Issue by Akkaross** [ldtteam/minecolonies#967]
### Minecolonies version

version 1.11.2-0.8.930 on a Verygames multiplayer server .

### Expected behavior

   - Delivery-man collects all items from the gatherers (miner, sawmill ...) and stock them to the warehouse.

### Actual behaviour

   - Delivery-man collects all items as intended, and going to the warehouse. Then items disapear from his inventory but don't go to the chests nor in the inventory of warehouse.

### Steps to reproduce the problem

 1.   Build a townhall. Then a builder, sawmill, miner ...
 2.   Build a warehouse and a deliveryman (level 1 and 2 tested)
 3.   Hire a deliveryman.
 4.   Wait and watch deliveryman eating all your ressources.

(Thanks for all your work, very appreciated)

**Comment by marvin-bitterlich** [comment]
@OrionDevelopment does that version contain your fixes?

**Comment by Akkaross** [comment]
Normally yes, but the bug is still there.

**Comment by marvin-bitterlich** [comment]
@Akkaross have you tested the latest alpha builds?

**Comment by Akkaross** [comment]
v0.7.946 tested. Always the same problem.

**Comment by marchermans** [comment]
This seems to be a particular issue with 1.11
I gotta dig into this, i will have time for this in the Weekend.

**Comment by Akkaross** [comment]
Thanks. I'm here for more feedback if you need.

**Comment by wilsondgonzales** [comment]
It's weird how I've verified that there are **no problems** with 

- Deliveryman handling items requested from the warehouse to the worker
- Deliveryman taking items from worker chests and bringing it to the warehouse
- Deliveryman delivering food
- Workers dropping their items to their respective worker chests

these were working for me on 8.930 and now even with .946

**Comment by marchermans** [comment]
Their is a Problem with the dropoff method when he Drops Overflow into the warehouse.....
That is at least what we could verify.

**Comment by xavierh** [comment]
Tested on a fresh  SP world, the d-man workd fine.
Tested on my server, my 2 d-man are stuck next to the main warehouse chest.
I think they wre in the PREPARE_DELIVERY state. Could not debug yesterday as I could not build :(

**Comment by marvin-bitterlich** [comment]
merged the fix

**Comment by Akkaross** [comment]
Hello here, sorry for not giving any news sooner. It was a long time to do some tests on my side. I completely destroyed the Dman and the warehouse and recrafting their placement blocks. I also had to destroy a small mountain in order to be able to warehouse further, thinking that this could be what triggered the bug. Alas no change.
There are some others mods on this server, maybe there is a problem with one ? 

- BloodMagic-1.11-2.1.10-79
- Chameleon-1.11-3.0.2
- ElevatorMod-1.11.2-1.3.0
- Guide-API-1.11.2-2.1.1-52
- jei_1.11.2-4.3.4.273
- journeymap-1.11.2-5.4.6
- Mantle-1.11.2-1.2.0.26
- minecolonies-universal-1.11.2-0.7.946
- NoMoreRecipeConflict-0.8(1.11)
- OptiFine_1.11.2_HD_U_B7
- platforms-1.11.0-1.3.3
- Reliquary-1.11.2-1.3.3.635
- RoguelikeDungeons-1.11.2-1.6.6
- shetiphiancore-1.11.0-3.4.4
- SpawnCommands-2.2.3-mc1.8.9-forge
- StorageDrawers-1.11.2-4.2.4
- TConstruct-1.11.2-2.7.0.9
- WearableBackpacks-1.11.2-2.3.0

**Comment by xavierh** [comment]
A fix have been merge, please test the latest version (when available)

**Comment by Akkaross** [comment]
Thanks, I would keep you informed as soon as our admin will have updated the server.

**Comment by Akkaross** [comment]
It's working as intented ! Many thanks !! :D
