### ISSUE TITLE
[BUG] Builders don't retain existing hut level when building "universitylibrary" placement helper

### ISSUE THREAD

**Issue by linol-shadowcat** [ldtteam/minecolonies#9672]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.20.1-1.1.395-BETA

### Structurize Version

1.20.1-1.0.670-BETA

### Related Mods and their Versions

1. Forge Version: 47.2.16
2. N/A
3. Domum Ornamentum Version: 1.20-1.0.150-BETA

### Current Behavior

When using the medieval universitylibrary helper blueprint, the builder will always place a level 1 university and/or library hut blocks, even if you give them a pre-leveled hut block.

### Expected Behavior

The hut blocks that the builder places should retain any existing nbt data, including hut level.

### Reproduction Steps

1. Level a university and/or library building beyond level 1.
2. Have a builder deconstruct the building leaving just the leveled hut blocks.
3. Pick up the pre-leveled hut blocks.
4. Place a universitylibrary decoration blueprint down for any medieval theme.
5. Give the assigned builder the pre-leveled hut blocks.
6. When the builder places the hut blocks, the levels are lost. 

### Logs

https://gist.github.com/linol-shadowcat/c8a3ca01fa651b4f45b93df36ae8a097

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
The level of child buildings is coded into the blueprint (as part of the name/building alternative). It is not possible for builders to ignore that part of the name, and use a different level

That said, I wouldn't expect the builder to accept a pre-levelled hut block in such cases (and rather ask for a new one)

**Comment by TheNumenorean** [comment]
I ran into this too, level 0 library and university hut blocks got converted to level 1. (not complaining...)

**Comment by Raycoms** [comment]
#5006
