### ISSUE TITLE
World Generation Colonies disable optioon is missing

### ISSUE THREAD

**Issue by Snaggl3t00th420** [ldtteam/minecolonies#9677]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [X] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

minecolonies-1.20.1-1.1.395-BETA.jar

### Structurize Version

structurize-1.20.1-1.0.675-BETA.jar

### Current Behavior

the Option to disable the World Generation Colonies in (Your Minecraft folder)/saves/(your world's name)/serverconfigs/minecolonies-server.toml is missing 

### Expected Behavior

option to disable random spawning of colonies

### Reproduction Steps

add option 

### Logs

no logs config bug

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
What option, there's never been an option because worldgen is sourced from datapacks, it's not dynamically toggleable through a config.

**Comment by Snaggl3t00th420** [comment]
This is writtenm in the Wiki:
As you explore the world, you’ll notice that there are some colonies abandoned by the former residents. Moving into one of these abandoned colonies is a way to quickstart your own colony!
(Note: This feature is only available in 1.18+. Vanilla villages will still spawn as normal. If you wish to turn off this feature, you can do so in the [configuration options](https://wiki.minecolonies.ldtteam.com/source/misc/configfile) for your world.)

**Comment by Thodor12** [comment]
I don't know who wrote that but that is wrong, there's a guide on how to disable worldgen colonies on Discord.

**Comment by Raycoms** [comment]
It's an old config option, this is now all datapack.
