### ISSUE TITLE
After updating minecolonies builder not upgrading anymore

### ISSUE THREAD

**Issue by Eviiable** [ldtteam/minecolonies#968]
### Minecolonies version

version minecolonies-universal-1.10.2-0.4.1870 to minecolonies-universal-1.10.2-0.8.929

Minecraft version 1.10.2

### Expected behavior

Clicking on a building, pushing upgrade button -> builder will upgrade building from for example lvl 1 to 2 

### Actual behaviour

Pushing the upgrade button somehow won't work. no response at all. Before it worked fine. Now there is not even a chat response. I still can fire / hire workers. 
I actually dont know what happens with new buildings I build. 

### Steps to reproduce the problem

1. Refreshed the colony
2. deleted the colony
3. fired the worker hired a new one

Thx in advance :-)

UPDATE:

I built a new building. I can upgrade the new building without a problem but I still can't upgrade the old buildings. Even though with a fresh new builders hut... still not working

**Comment by marvin-bitterlich** [comment]
Does the building show up as a build request in the town hall?

**Comment by Eviiable** [comment]
Nope.

**Comment by Raycoms** [comment]
Can you send us the log?

2017-05-10 12:47 GMT-03:00 Eviiable <notifications@github.com>:

**Comment by Eviiable** [comment]
I actually would... if I could :) If u meant the latest log file  in the logs folder... I can't send it to you because it says the file is too big. its 32 mb :) ... How can I send it to you? (thx for the help btw...) :'-)

**Comment by xavierh** [comment]
Delete it your log file. And try to do the upgrade again. Your log will be much smaller

**Comment by Eviiable** [comment]
[latest_log.txt](https://github.com/Minecolonies/minecolonies/files/990873/latest_log.txt)

**Comment by xavierh** [comment]
@raycoms I suspected it was my fault. Spot on!
Trying to upgrade to schematics/default/Citizen5 which does not exist. I did not know that default was a style. Should I do a patch to change default to wooden?

**Comment by Raycoms** [comment]
Didn't have the time to take a look at that.

Yes the first style we had was "default" but that has been a while, we
changed it to "wooden" since.

**Comment by xavierh** [comment]
@Eviiable Extract this file into minecolonies\schematics in your minecraft folder or world's folder.
[default.zip](https://github.com/Minecolonies/minecolonies/files/991122/default.zip)

more info: https://wiki.minecolonies.com/wiki/22/schematics#schematicfolder

**Comment by Eviiable** [comment]
It worked! Thank you so much :-))) I'm actually the happiest person on earth atm *haha* Thank you thank you thank you :))
