### ISSUE TITLE
[BUG] <title> No raids spawning

### ISSUE THREAD

**Issue by Havicer** [ldtteam/minecolonies#9683]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

1.19.2-1.0.1442-ALPHA

### Structurize Version

1.19.2-1.0.491-ALPHA

### Current Behavior

I can’t seem to get any raids or spawn then with commands. I’ve tried toggling raid spawn in config and setting min between nights to 1 to see if it would do anything and it’s not. Is there a way to reset or fix this?

### Expected Behavior

I expect to be raided.

### Reproduction Steps

I did toggle to keep daylight on which may of caused the issue. Can it be fixed?

### Logs

No log for this

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
Try turning daylight cycle back to normal. They spawn at night usually

**Comment by Havicer** [comment]
Sorry I did do that a while ago. Also set spawn min to one night

**Comment by Havicer** [comment]
I’ve tried repairing files and a lot of other things

**Comment by Raycoms** [comment]
Are you maybe playing in peaceful mode? And how big is your colony?

**Comment by kezmodius** [comment]
1.19.2-1.0.1442-ALPHA is a very old version. You could try updating.
