### ISSUE TITLE
[BUG] Composter does not make compost - Fortress Style

### ISSUE THREAD

**Issue by LordCorellon** [ldtteam/minecolonies#9685]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [X] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.20.1-1.1.397-BETA

### Structurize Version

1.20.1-1.0.662-BETA

### Related Mods and their Versions

ATM9

### Current Behavior

When the composter is built a couple issues occur in which it prevents the composter from actually functioning and creating compost.

Issue 1: Composter does not generate requests for items that have been set to compostable resulting in stock not being delivered to the composter

Issue 2:  Composter will not retrieve items from the racks or main block (Compost block) inventory resulting in the composter not having items to compost, instead the composter will walk to the rack/inventory appear to to grab an item (Hand changes but stock does not reduce and worker inventory does not fill) and then cycle back and forth between walking to the composter and the rack pretending to insert items which do not fill the composter

Issue 3: Only slot 1 of the worker inventory is functional - When you manually place items in the composter worker inventory the composter will work function correctly so long as slot 1 (Top Left slot) is full, they will take whatever compostable item is in that slot and insert it into the composter until full/exhausted and then harvest the resulting compost, however if any other slot of the inventory is fill (Including every slot but slot 1) no work will be performed, only slot 1 results in functional work

### Expected Behavior

Issue 1:  Expected that a minimum Qty. can be set on the building to generate delivery orders for composting, or at the minimum delivery tasks are generated to replenish supplies of items marked as compostable

Issue 2:  Expected that items can be retrieved from Racks and/or main inventory for utilization in composting in a similar fashion to all other buildings.

Issue 3: Expected that the entire inventory of the worker will be checked and utilized while deciding if stock exists for fulfilling job.

### Reproduction Steps

1. Construct composter
2.  Set Wheat Seeds, Potatoes, Carrots, Etc as compostable
3. Wait for delivery to occur (Failed)
4. Place wheat seeds, potatoes, etc on building rack or main inventory
5. Wait for worker to retrieve (Failed)
6. Place Wheat seeds, potatoes, etc in worker inventory upper right slot
7. Wait for worker to compost items (failed)
8. Move Wheat seeds, potatoes, etc from upper right to upper left slot (first slot)
9. Wait for worker to compost (Success)

### Logs

Can not retrieve from server currently, will do at next restart

### Anything else?

This seems to affect the fortress style primarily as other users using a different style do not seem to be affected (By issues 1 and 2 at least) Issue 3 seems to be common among all styles.

When debugging is enabled the worker does appear to cycle through steps but primarily stays in the "Decide" phase.   Worker does not hang on the "Waiting on resources" that would indicate they are missing items, but instead goes through the actions (and as far as I can tell the steps) of "working" by retrieving stock, assessing if a valid composter is available, walking it it, placing the item in it and then exiting the logic.   However because it appears to fail at the "retrieving stock" the rest of the actions are ghost actions producing no result since they have nothing to deposit.

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Works now at least
