### ISSUE TITLE
[BUG] dobarbariansbreakthroughwalls = false being ignored

### ISSUE THREAD

**Issue by LordCorellon** [ldtteam/minecolonies#9686]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.20.1-1.1.397-BETA

### Structurize Version

1.20.1-1.0.662-BETA

### Related Mods and their Versions

ATM9

### Current Behavior

Server is configured with dobarbariansbreakthroughwalls = false

Based on the description of the TOML (#Whether or not raiders can break through obstacles [Default: true]) it would be expected that barbarians will not break obstacles (Blocks) to reach the village and follow the path finding to find a valid route/entry.

shouldraiderbreakdoors is configured as true so barbarians can break through doors to reach the target.

Behaviour encountered is that no observable instances of walls being broken have occurred, the barbarians will still break "ceiling" blocks to reach the target, this has been observed with the path finding leading the barbarians into an underground cave system (Rather then across the the same z level (level village) to a door or gap in the wall (Fortress style)) and then the barbarians constructing ladders and destroying the block above them to gain entry (Sometimes from as many as 32 blocks lower in Z)

### Expected Behavior

Expected that dobarbariansbreakthroughwalls = false prevents the removal of blocks above and below in addition to the sides.  A valid path does exist for entry so this is not a case of "All else fails" but instead is a result of pathfinding determining that a cave system 32 blocks under the village is a "shorter" route then "Gate at the front of the village".

### Reproduction Steps

1. Build a colony over a cave system,
2. Isolate the colony with a wall around it except for in the "Front" (IE: North side)
3. Wait for the raid to occur in the "Back" (IE: South Side)
4. It will occasionally be observed that they will enter the cave rather then walk around the village wall
5. Wait for barbarians to start building upwards 

### Logs

Do not have from when the issue occurred last, will upload once observed again

### Anything else?

This is not always observable due to it (I suspect) being related to path finding and the decisions made based on layout, raid direction, path taken, etc however in some instances the result is in the raid going "down" rather the "across" and entering a cave system or waterway and making their way "under" the village and then building upwards.

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
Which config in which folder did you change?

If you just changed the one in defaultconfigs, that one will only affect new worlds, not the current one. Make sure to edit the server config in `<server>/<world>/serverconfigs`

**Comment by LordCorellon** [comment]
I can confirm it's the server/world/serverconfigs file. 

Other changes are accepted and have taken effect (such as when enabling or disabling debug) and it does prevent breaking blocks on the same z level but not those above (haven't had a situation to test blocks below)

**Comment by Thodor12** [comment]
You say they're going up, breaking blocks this way, are they actually breaking blocks or placing ladders on those blocks?

**Comment by LordCorellon** [comment]
Breaking blocks then placing ladders where the broken block was.

For example I have a large cavern a couple blocks under where the village was situated as well as a mineshaft worldgen feature,  the first occurrence was when a hole appeared in the floor of my town hall and barbarian stragglers (ran away as I was fighting the main horde) entered the village.  I chalked that up to me mistakenly mining a block by mistake (but it was under a gate so I was doubtful) but since then there have been other occurrences where the floor of buildings have been mined out and barbarians have gotten in, all have occurred after a raid and did not exist prior to the raid (I am compulsive about looking for missing blocks now) and have observed it occurring twice where after watching the barbarians fall into a hole and observing the minimap of where they are see a block disappear and a ladder appear before a barbarian comes out of the hole

**Comment by Raycoms** [comment]
It's the ladder placement that breaks it. ye

**Comment by Thodor12** [comment]
Yeah I figured as much, although literal block breaking is not allowed for them, they are still allowed to ladder up.
However there's no placement restrictions on ladders, they can use them to dig up through the floor, place them against a surface, or anything.

The concept this tends to avoid is when barbarians are at your colony walls, they will not dig horizontally through a wall, however if they accidently manage to place a ladder and create a hole within a structure, they will capitalize on that and continue going through a structure.

**Comment by Raycoms** [comment]
we do get the blockstate for some checks though, so we can use this also to check on the config

**Comment by LordCorellon** [comment]
If it's intentional then I understand, but would ask if a separate config option would be possible?  I play with my younger son and while I don't mind the challenge (as I suspect most do) he's still struggled with the complexity of planning which is why I had tried to restrict it to just doors and entry points.

Thanks for looking into it

**Comment by Raycoms** [comment]
we will adjust it to take this into account
