### ISSUE TITLE
[BUG] 1.20.1 version. Map not loading or anything else just normal survival. Structures and Buildings only in creative menu

### ISSUE THREAD

**Issue by Cowman28forlife** [ldtteam/minecolonies#9689]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

1.1.379-BETA

### Structurize Version

1.0.675-BETA

### Related Mods and their Versions

1. Forge version 47.2.19
2. Block UI version 1.20.1-1.0.128-BETA
3. Domum Ornamentun version 1.20-1.0.151-BETA
4. Multi-Piston version 1.20-1.2.31-ALPHA

### Current Behavior

when the world loads, it looks like standard Minecraft when no mods. I did not see a start command to start the mod either. I loaded up a creative world to see if that would change anything. All I found were the items the mod added like structures

### Expected Behavior

I was expecting the map to load and to be able to see what i had to do to progress in the game

### Reproduction Steps

1. Download forge
2. Install forge to java launcher
3. download mods load forge version
4. add mods with the "Open Mods Folder" button]
5. quit the game
6. relaunch it
7. create a new world

### Logs

https://gist.github.com/Cowman28forlife/92b8624cd9ab8d25548cb75c41e58fb9

**Comment by kezmodius** [comment]
Are you expecting a tutorial? A colony at spawn? Minecolonies pretty much starts by punching trees like normal minecraft. 
https://wiki.minecolonies.com/source/tutorials/getting-started

**Comment by Raycoms** [comment]
It's not an adventure map. Minecraft doesn't give you a "here is a way to the enderdragon" start either.

**Comment by Cowman28forlife** [comment]
I’m not asking for an “adventure map”. All the start up I saw of people starting to play, they had the map in the top corner without reference to any other mod like journey map. As well as how some the images from curseforge have the minimap without reference.

**Comment by Raycoms** [comment]
We don't add our own minimap. For that you need journeymap or similar

**Comment by Cowman28forlife** [comment]
Thanks
