### ISSUE TITLE
[BUG] <title>Crash and now my warehouse block is not working

### ISSUE THREAD

**Issue by Catmosphere** [ldtteam/minecolonies#9694]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.20.1-1.1.38\95-BETA

### Structurize Version

1.20.1-1.0.674-BETA

### Related Mods and their Versions

1. Forge 47.2.1.9
2. BlockUI  - not present
3. Domum Ornamentum 1.20-1.0.150-BETA
4. 

### Current Behavior

warehouse block is no longer working after crash. i went to open the block right clicking with builders hut scroll in my hand

### Expected Behavior

Warehouse block is meant to work?

### Reproduction Steps

Inspect builders scroll, waystone into the warehouse hut, inspect inventory, attempt to open warehouse block with hand with scroll in it, client crash. 

Did not affect other 2 people on the server. I am the only one doing the mc mod. I am the only active colony although I started then stopped another one I found elsewhere.

### Logs

https://gist.github.com/Catmosphere/2868abf9c79ddebd1c695a33a84bedf6

### Anything else?

crash log
https://gist.github.com/Catmosphere/f18b9f5ddcb691daf94d0fcad04364a6

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
We got an open PR to fix the crash. Weird that it corrupted the warehouse. But after it is corrupted only thing you can do is mine it and repair it or ask an admin to paste the same one over the existing one after removing the hutblock.

**Comment by Moobien** [comment]
> We got an open PR to fix the crash. Weird that it corrupted the warehouse. But after it is corrupted only thing you can do is mine it and repair it or ask an admin to paste the same one over the existing one after removing the hutblock.

We suggested the admin repaste (after emptying the racks)

**Comment by Catmosphere** [comment]
I'm playing on a server with friends so the admin is like 'huh?'  Can you please give a lot more detail on "ask an admin to paste the same one over the existing one after removing the hutblock."

**Comment by Raycoms** [comment]
admin goes to your warehouse, you add admin to colony as officer. Admin removes warehouse block. Admin right clicks build tool and on the top left selects the same style as you. Admin selects the warehouse in the categories (you tell the admin the style, in which folder the warehouse is, and which level, or alternative it is). Admin positions the building to be the same as yours right now. Admin clicks the confirmation button. Then admin gets three choices and picks "constructed".
