### ISSUE TITLE
[BUG] <title> guards attack players who do not own the colony no matter the player's rank

### ISSUE THREAD

**Issue by dragon-g33k** [ldtteam/minecolonies#9703]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.1.321

### Structurize Version

1.0.662

### Related Mods and their Versions

forge ver 47.2.5
domum ver 1.0.147
blockui ver 1.0.125

### Current Behavior

the guards attack colony offficers

### Expected Behavior

the guards should not attack non aggressive players, especially after killing them with forgivedeadplayers active

### Reproduction Steps

go into multiplayer, have another player create a colony, have them build a guard tower, go to guard.

### Logs

why is it required? it happend on five different sessions

### Anything else?

👍

**Comment by Raycoms** [comment]
This only happens if the person that created the colony set the "attackguards" perm in the permission settings in the townhall
