### ISSUE TITLE
[BUG] unable to repair auto upgrading nested buildings with functional blocks 

### ISSUE THREAD

**Issue by anastasia590** [ldtteam/minecolonies#9708]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.20.1.1.425

### Structurize Version

1.20.1.0.675

### Related Mods and their Versions

Style colonies 1.3

### Current Behavior

The Steampunk hospital nested restaurant does not function due to builder not recognizing the furnaces,  but cannot be repaired either as it should be able to be repaired. 
The farmhouse in the farm has the same issue,  the people stand by hut block to "sleep" and are unhappy they cannot sleep
there is no repair button for this either.  
there is a repair button in the nested school which does not auto level but does have functional blocks,  barracks towers have a repair button as does the baker (not autoleveling) it seems that all the other nested buildings do have repair buttons (and work fine)  
  note I am aware that auto-leveling nested buildings with functional blocks doesn't work and shouldn't work,  I know those furnaces "belong" to the hospital and the beds "belong" to the farm,  the issue is not that they don't work but that the reapair button isn't there. 

### Expected Behavior

I expected that as an autoleveling nested building with functional blocks that this would not work without "repair" but I did expect a repair button.   Having built a style with an insane amount of nested buildings myself,   I did attempt autoleveling nested buildings with functional blocks, and those did not work,  but were repairable,  and then they worked.    This was in v19 when I designed funtional fantasy.   I ended up making those buildings not auto-level due to my own experience in my survival test so I can't test this problem outside of steampunk. 
    neither of these has a repair button,  only a pick up button but then says you cannot pick up this building.   you also cannot deconstruct them 

### Reproduction Steps

build steampunk hospital to level four. 
hire cook in the nested restaurant
watch them complain you need to repair their hut, 
try and repair it. 
swear,  
log out and log back in,  try again
break restaurant hut block and repair hospital instead,  
see nothing is fixed except your builder spent hours trimming down the bamboo outside,  
swear 
give up and break hut block to keep couriers from starving 

build farm to level 5  
assign farmer to live there 
watch him sleep standing up
try and repair farmhouse 
swear when there is no button or laugh at me if there is 
 I don't know if other styles are affected,  I do not know if others have autoleveling nested buildings with functional blocks so I cannot test it.  

### Logs

https://gist.github.com/Ramtough2011/a61af2d6703eef6d771f96cb6a3ab9f0

### Anything else?

I can confirm troubleshooting with other builders and both should be repairable.  
screen shots to show that school (which functions fine as it should but doesn't auto-level ) is repairable but not the farmhouse - I had to remove the restaurant hut block to prevent hungry people getting stuck there as the cook would not feed people without furnaces,  they were just too upset I guess.   Also the barracks tower which does auto level (but isn't malfunctioning as it has no functional blocks) is also repairable. 

 problem has been going on for many MC versions and at least the last two stylecolonies versions 
![2024-01-13_21 01 14](https://github.com/ldtteam/minecolonies/assets/121142637/6ad0fd18-514f-4d62-95c8-28a395d097c7)

 
![2024-01-13_20 47 04](https://github.com/ldtteam/minecolonies/assets/121142637/5a89b1be-e37d-4fc3-8ef0-8627bc29dca5)
![2024-01-13_20 49 17](https://github.com/ldtteam/minecolonies/assets/121142637/d299bf5d-2da4-4b32-8d91-18207a491853)

**Comment by uecasm** [comment]
This is expected behaviour.  For auto-leveling children, the blocks are actually placed when building the parent -- they're ignored at that point since they're not important to the parent.  The child is not actually ever "built" so it does not register any of the blocks, and so they do not function.

This is why the schematics tutorial advises to not use auto-levelling when the child has functional blocks.  There's a few cases where it can work (when the child building searches for blocks later, not purely at construction time), but the majority will not.

**Comment by MotionlessTrain** [comment]
A "repair" button would be expected for those types of child buildings, wouldn't it?

**Comment by uecasm** [comment]
Yes, the repair button should show -- but if it doesn't, that's a schematic bug and not a mod bug.  Suggests that they were scanned with the wrong path (for the child in the parent) so that it can't find the schematic (which is why it would display Pick Up instead of Repair).

Typically auto-levelled children are just single blocks so the repair wouldn't do much anyway, but it's still a sign of something wrong if it's missing.

**Comment by anastasia590** [comment]
I tried pasting and scanning the farm in a sp creative world -- - clicking "view resources" crashed that world several times 
[]([](https://gist.github.com/anastasia590/ee952489b6209d7b73bbb622d1a53515))  this is the crash log for that. 
I went back in and pasted the level 5 farm,  and then scanned the farmhouse,  and it scans fine,  it is scanning as the level 4 farmhouse as expected,  not as a single block as it would if this had not been properly pasted.  
   then I was able to scan the farm,  the farm scans correctly with the correct anchor,  the and I can't figure out how this could possibly not have a repair button, the report is only for the lack of a repair button -- I know why the buildings don't work - I don't care if I have to repair them - it's faster than building them from level 0 -

**Comment by Raycoms** [comment]
I believe this has been solved
