### ISSUE TITLE
[BUG] A Token of Appreciation: Quest giver doesn't have follow-up dialogue giving the name of the recipient/participant in the quest

### ISSUE THREAD

**Issue by darthvader45** [ldtteam/minecolonies#9709]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.1.427-BETA

### Structurize Version

1.0.662-BETA

### Current Behavior

The quest giver doesn't let me talk to them while the quest is active to give information on who I should visit to complete the quest.

### Expected Behavior

The quest giver should have repeatable dialogue giving the recipient's name until the quest is done.

### Reproduction Steps

1. Get quest from citizen.
2. Try to find citizen to give the gift to.
3. Return to quest giver.
4. No dialogue telling you who to deliver to.

### Logs

N/A

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Yeah, the system can't handle this at the moment. You can use the questlog to track the next person to get in contact with.

**Comment by darthvader45** [comment]
Weird, cause the questlog also tracks the giver, not the next person.

**Comment by Raycoms** [comment]
Huh, odd.

**Comment by Flabort** [comment]
I had to talk with every colonist in my colony to figure this out myself. Eventually I found it was my baker, but yeah. Quest book only showed quest giver, not redeem point.

However, that was a couple of versions ago AFIAK, because some of the huts have changed their UI since I did this quest.

**Comment by Thodor12** [comment]
Finishing off is always a talk to person X stage, it should still state that as part of the current quest objective in the quest log, maybe not the track button but it will show the name of the intended person.

**Comment by Raycoms** [comment]
The track button should show the "next current objective owner"

**Comment by Raycoms** [comment]
Quest log now allow tracking this better
