### ISSUE TITLE
[BUG] <title> Server crashes when destroying a monster spawner and killing a pirate on a pirate ship

### ISSUE THREAD

**Issue by axlmly** [ldtteam/minecolonies#9716]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19.2

### MineColonies Version

1.19.2-1.1.433-BETA

### Structurize Version

1.19.2-1.0.679-RELEASE

### Related Mods and their Versions

Silent Compat (silentcompat), Version: 1.3.4
Apotheosis (apotheosis), Version: 6.4.1
blockui,version: 1.0.129-BETA
domum_ornamentum,version:1.0.146-BETA-universal

### Reproduction Steps

Translation: In multiplayer, I was in a pirate raid and after entering a pirate ship to destroy the monster spawner, the server was lost and I couldn't get in by restarting the server.

### Logs

https://gist.githubusercontent.com/axlmly/c6a470d0d4bb04cf9c5ab0d67d373ab4/raw/f689c004fa9b824579411abf6007763b1f195fa7/gistfile1.txt

### Anything else?

[debug.log](https://github.com/ldtteam/minecolonies/files/13953538/debug.log)

**Comment by Raycoms** [comment]
Can you try if this also happens without:

Silent Compat
Apotheosis (apotheosis)
And or Quark

One of these three mods cause a crash as they assume a player and not another entity with their mixins/events/

**Comment by axlmly** [comment]
> Can you try if this also happens without:
> 
> Silent Compat
> Apotheosis (apotheosis)
> And or Quark
> 
> One of these three mods cause a crash as they assume a player and not another entity with their mixins/events/

Thank you, after troubleshooting the mod I've found out that it was Silent Compat that was causing the problem, and after removing the mod the server is working fine!
