### ISSUE TITLE
Settings for colony announcements is not in game or on the configs

### ISSUE THREAD

**Issue by Mystara0001** [ldtteam/minecolonies#9717]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.1.434-BETA

### Structurize Version

1.0.680-BETA

### Related Mods and their Versions

1. Forge Version: 47.2.20

### Current Behavior

Children are born - No announcement
Children grow up - No Announcement
Jobs complete - No announcement

Unable to find a setting in game or in the client/server/common config for announcements 

### Expected Behavior

Announcements should be available for all events and broadcast while within that colony.

### Reproduction Steps

Let colony have kids
Let the kids grow up
Finish a build job

Expect announcement.

### Logs

N/A

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Grow up is only for the first 10 citizens atm. Have kids is currently derped and is pending a PR.
