### ISSUE TITLE
[Game Crash] <Game crashes when Shift+ Right click on worker's hut with resource scroll (it says there's no worker's building on the log)>

### ISSUE THREAD

**Issue by LLORTX** [ldtteam/minecolonies#9723]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.20.1-1.1.417-BETA

### Structurize Version

1.20.1-1.0.675-BETA

### Related Mods and their Versions

1. Forge: 47.2.0
2. Terra Blender: 3.0.1.2
3. Biomes O' Plenty: 18.0.0.598
4. Nether's Exoticism: 1.2.7
5. The Aether: 1.20.1-1.0.0-neoforge
6. Just Enough Items: 15.2.0.27
7. Domum Ornamentum: 1.20-1.0.151-BETA
8. Spark: 1.10.58
9. Curios API: 5.4.7+1.20.1
10. Flywheel: 0.6.10-7
11. Create: 0.5.1.f
12. UI Library Mod: 1.20.1-1.0.128-BETA
13. Soot's Sandwichcraft: 1.2.3
14. Citadel: 2.4.9
15. Alex's Caves: 1.0.9
16. Traveler's Backpack: 9.1.12
17. YUNG's API: 1.20-Forge-4.0.2
18. MixinExtras: 0.2.0-beta.9
19. Structurize: 1.20.1-1.0.675-BETA
20. Multi-Piston: 1.20-1.2.31-ALPHA
21. Cumulus: 1.20.1-1.0.0-neoforge
22. Minecolonies: 1.20.1-1.1.417-BETA
23. Starlight: 1.1.2+forge.1cda73c
24. Architectury: 9.1.12
25. Furnish: 26
26. Create: Steam 'n' Rails: 1.5.3+forge-mc1.20.1
27. YUNG's Better End Island: 1.20-Forge-2.0.4
28. Nitrogen: 1.20.1-1.0.1-neoforge
29. Dragon Mounts: Legacy: 1.1.5.b3
30. CosmeticArmorReworked: 1.20.1-v1a
31. The Twilight Forest: 4.3.1893
32. Dynamic Trees: 1.20.1-1.3.0-BETA1
33. Structurize GEL API: 2.16.0
34. The Farlanders: 1.4.1

### Current Behavior

I just finnished building the Worker's Hut when the worker in question tells me about the Resource Scroll. I go craft it. I give it to the worker and then it dissapears. The worker tells me to Shift + Right click on the worker's hut to activate it. When i do, the game crashes.

VIDEO OF CRASH:
https://github.com/ldtteam/minecolonies/assets/156937346/5bccfd0f-08d0-4d01-ad81-74be64e50d24

### Expected Behavior

I Shift and Right click on the hut's table with the scroll and i mark it as finnished.

### Reproduction Steps

1. Talk to worker about resource scroll
2. Give scroll to worker
3. Scroll Dissapears from own inventory and isn't in worker's inventory
4. With a different resource scroll, shift + right click on worker's hut table
5. Game crashes

### Logs

https://gist.github.com/LLORTX/032efae1ee2f3a141d04c0cda6a2dbbb

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

[crash-2024-01-17_18.46.23-client.txt](https://github.com/ldtteam/minecolonies/files/13966849/crash-2024-01-17_18.46.23-client.txt)

**Comment by LLORTX** [comment]
This bug was reported in the Discord server too (By myself)

**Comment by LLORTX** [comment]
Update: It crashes on ANY building for some reason :)

**Comment by Raycoms** [comment]
Fixed in newest
