### ISSUE TITLE
[BUG] Issues with Citizens claiming to be unable to dump their inventory.. when their workstation's (or hutblock's) storage is EMPTY.

### ISSUE THREAD

**Issue by xandercreates** [ldtteam/minecolonies#9729]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

MineColonies 1.20.1-1.1.430-RELEASE

### Structurize Version

Structurize 1.20.1-1.0.662-BETA

### Related Mods and their Versions

1. Forge 42.2.17
2. BlockUI 1.20.1-1.0.128-BETA
3. Donum Ornamentum 1.20-1.0.151-BETA

### Current Behavior

It's easier for me to show whats happening with a short video, here is an clip showing the Cook not realizing that he could dump his inventory.

[Video](https://cdn.discordapp.com/attachments/1125094832143077456/1198202386393596017/Base_Profile_2024.01.20_-_04.45.34.23.mp4?ex=65be0bee&is=65ab96ee&hm=e2152fdba08cacc3266702ece8e2b99f1d67b72cd7fbd51af0f75e7946fbd41d&)
If you somehow cannot view the video, In a nutshell, I would just go about the days building up a colony, and soon after I would see the NPCs start to complain about not having inventory space when they clearly have space.

### Expected Behavior

The expected behavior is for them to use their workstation's inventory.

### Reproduction Steps

1. Make a Colony
2. Expand Said Colony
3. Check any employed Citizen (Except Builders, never had issues with them), namely Cooks, Guards, Foresters.. etc.

### Logs

No logs, No Relevant Errors were found

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Please add a comment if you have any further information or would like to show your own instances of this bug happening!

**Comment by Raycoms** [comment]
can you post some screenshots?

**Comment by Talyda** [comment]
Adding on here - there's been an increased amount of people reporting this on discord over the past few days (I think). Workers saying they need space to be able to empty their inventory, but their hutblocks are completely empty

**Comment by Talyda** [comment]
https://discord.com/channels/139070364159311872/1125094832143077456/1197978633608904765
Another report from this morning

**Comment by xandercreates** [comment]
> can you post some screenshots?
![2024-01-20_05 19 42](https://github.com/ldtteam/minecolonies/assets/69139978/66e72b42-f711-448b-b694-3822ebaaaae1)
![2024-01-20_05 19 47](https://github.com/ldtteam/minecolonies/assets/69139978/eb6a026c-c172-476e-b5a9-8a9fbb5755f6)

Here, but.. I'm surprised you asked for screenshots. I did link a video after all

**Comment by Talyda** [comment]
Not everyone can look at videos, or want to open them (and that's my fault, I meant to tell you to put screenshots instead of videos)

**Comment by xandercreates** [comment]
Has anyone gotten the same issue in singleplayer by any chance?

**Comment by Talyda** [comment]
https://discord.com/channels/139070364159311872/1003402487417548801/1198399877768564798
Another person had it happen here. it seems like a restart of the game, once they get this error fixes it and they dump their inventory in the hutblock.
So it's still buggy, but there is at least a temporary fix

**Comment by Raycoms** [comment]
solved
