### ISSUE TITLE
[BUG] Courier get stuck inside my warehouse

### ISSUE THREAD

**Issue by denderpro** [ldtteam/minecolonies#9733]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.20.1-1.1.441

### Structurize Version

1.20.1-1.0.680

### Related Mods and their Versions

forge version: 47.2.0
blockui-1.20.1-1.0.128-BETA
domum_ornamentum-1.20-1.0.151-BETA
structurize-1.20.1-1.0.680-BETA
stylecolonies-1.2.3
towntalk-1.20.1-1.0.1

### Current Behavior

My couriers get stuck inside my underwaterstyle warehouse. they seem to not be able to climb the ladders. I tried replacing the ladders, recalling and restarting the couriers also wouldnt help, i even tried out vines without any success. i tested it in a new world, the courier would work normally when i requestet an item from the first floor, when i did it for something on the top floor he would just stand still infront of the ladder.

### Expected Behavior

Courier getting me items from all the floors in my warehouse, just like in previous minecolonies versions

### Reproduction Steps

1. create underwater style colony and built warehouse lvl 5
2. build 1 courier
3. place item of ur choice in rack at second floor
4. place a postbox inside ur warehouse and request said item
5. watch ur courier fail at his job

### Logs

https://gist.github.com/denderpro/591793b2dce74ce10ee6280a9a6cfa21

### Anything else?

this bug was definetly not there on version 1.20.1-1.1.439 i just tested it. probably something with the pathfinding changes patch 1.440 brought? although there are no magma blocks etc inside my warehouse. thanks for this lovely mod btw !!!!

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
fix already pushed out

**Comment by denderpro** [comment]
ok bug got fixed with version 1.1.446 while i was still writing the bug report lol.
u guys are legends thank you so much
