### ISSUE TITLE
[BUG] Can't assign builder anymore

### ISSUE THREAD

**Issue by lebanni** [ldtteam/minecolonies#9739]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.1.449-BETA

### Structurize Version

1.0.686-BETA

### Related Mods and their Versions

Forge 47.2.20
blockui-1.20.1-1.0.134-BETA
domum_ornamentum-1.20-1.0.151-BETA

### Current Behavior

I have two builder with resource scroll assigned to their respective hut block. Since version 1.1.449, I can't select them in the drop down menu in the build options button. The resource scrolls say "no builder". I still can order build or upgrade, and the first available builder build the building. 

### Expected Behavior

Assign builder to build building.

### Reproduction Steps

Update to 1.1.449. Trying to assign a builder.

### Logs

https://gist.github.com/lebanni/4c120b5c56c5f6407dcef062ffea6254

### Anything else?

![2024-01-25_14 11 01](https://github.com/ldtteam/minecolonies/assets/2799575/7709ca6c-5f61-4bc6-83d0-82632551f3f4)

![2024-01-25_14 11 18](https://github.com/ldtteam/minecolonies/assets/2799575/2f8d54f1-99bb-4742-a21c-ca69aa5729ad)

![2024-01-25_14 11 36](https://github.com/ldtteam/minecolonies/assets/2799575/031dfeeb-aaec-4de2-b0df-8333170963b4)

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
hotfix pushed
