### ISSUE TITLE
[BUG] Client crash when attempting to join server.

### ISSUE THREAD

**Issue by Just-A-Shawn** [ldtteam/minecolonies#9743]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

1.1.433-BETA

### Structurize Version

1.0.684-BETA

### Related Mods and their Versions

1. Forge: 43.3.7
2. BlockUI: 1.0.136-BETA
3. Domum Ornamentum: 1.0.146-BETA

### Current Behavior

Client crashes when attempting to join a server established town.
Client encounters no errors attempting to join same world from single player.

### Expected Behavior

Joining the server without the shutdown of the client.

### Reproduction Steps

N/A, Crash is exlusive to joining a server with largely established town. I am willing to share both the modpack and the world for testing if you wish for exact reproduction of crash.

### Logs

https://mclo.gs/WGMN1Qt, https://mclo.gs/8lAeQrj

### Anything else?

I have only experienced this crash joining a server with a town already set up, creating a new world hasn't made me crash as of posting.

**Comment by someaddons** [comment]
Can you try without modern fix? Something seems to be affecting models

**Comment by Just-A-Shawn** [comment]
Removing modernfix fixes the crashes.
The mod supports changing all of it's settings through config files, I will attempt to isolate which setting is causing the issue and informing Modernfix's devs about the incompatibility.
