### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by GyouZK** [ldtteam/minecolonies#9745]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

minecolonies-1.20.1-1.1.430-RELEASE

### Structurize Version

structurize-1.20.1-1.0.686-BETA

### Related Mods and their Versions

Forge - 47.2.18
domum_ornamentum-1.20-1.0.151-BETA-universal
multipiston-1.20-1.2.31-ALPHA
towntalk-1.20.1-1.0.1

### Current Behavior

Crash when loading the modpack.

![Screenshot_2](https://github.com/ldtteam/minecolonies/assets/157899204/af6f9c7b-15be-411e-abe7-9bb4cc0e9ae5)

### Expected Behavior

Loading complete and ending up on the Minecraft Home screen.

### Reproduction Steps

Launch the modpack through the launcher, Launch it on the minecraft launcher, crashes and get the error.

### Logs

https://gist.github.com/GyouZK/b5df6c79c41c754aab07a2b8bc2cb25c

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Idk what forge broke for this to fail, but we can remvoe this code path anyway

**Comment by GyouZK** [comment]
Sorry to bother but what should i do to fix the issue on my own now?

**Comment by Thodor12** [comment]
For one, you should not use any Forge version past 47.1.3, so try downgrading Forge for now.
A fix has been made for it though, but that has to be merged first and a new Minecolonies version released.

**Comment by someaddons** [comment]
try forge version 47.1.3

**Comment by GyouZK** [comment]
I tried and sadly it doesn't work, i do get the same error whatever the version of forge i'm using..

**Comment by Thodor12** [comment]
Then you will have to wait for the linked pull request to get merged and a new Minecolonies version to be released
