### ISSUE TITLE
[BUG] Lvl 3 guards requiring up to chain armor while wearing full iron set

### ISSUE THREAD

**Issue by Kosmic138** [ldtteam/minecolonies#9747]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

minecolonies-1.19.2-1.1.433-BETA

### Structurize Version

structurize-1.19.2-1.0.683-RELEASE

### Related Mods and their Versions

Forge - 43.2.0, domum_ornamentum-1.19-1.0.146-BETA-universal, blockui-1.19.2-1.0.129-BETA, style is Byzantine, guard towers are auto-built by object Insulae, which is a house and contains auto-build guard towers.

### Current Behavior

Lvl 3 guards requiring minimal leather maximal chain armor, even they wear full iron set of armor with full durability, no enchants 

### Expected Behavior

Lvl 3 guards not requiring lower tier armor while wearing suitable armor already.

### Reproduction Steps

Have plenty of guards lvl 3 (bug is not consistently appearing on one guard), equip them with full iron armor set. Plenty of requests for lower tier armor should pop up in the Clipboard.

### Logs

https://gist.github.com/Kosmic138/18f324d56281a2384ea67131530d1437

### Anything else?

![image](https://github.com/ldtteam/minecolonies/assets/2978351/96551238-071e-4513-ac25-45a4327427b5)
![image](https://github.com/ldtteam/minecolonies/assets/2978351/80886191-f98b-4578-8342-34f38484ab48)
![image](https://github.com/ldtteam/minecolonies/assets/2978351/879880e2-7ce1-45c4-8a13-32eccd905e90)

**Comment by Raycoms** [comment]
duplicate
