### ISSUE TITLE
[BUG] Model Conflict

### ISSUE THREAD

**Issue by hjhhhc** [ldtteam/minecolonies#9755]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.1.460-BETA

### Structurize Version

1.0.686 beta

### Related Mods and their Versions

forge：47.2.20
blockui：1.20.1-1.0.139-BETA
Domum Ornamentum：1.20-1.0.154-BETA

### Current Behavior

![QQ图片20240130011109](https://github.com/ldtteam/minecolonies/assets/158079751/632148c6-b9e2-42fe-a0ed-6fb6ccc04d93)

![QQ图片20240130001645](https://github.com/ldtteam/minecolonies/assets/158079751/2aaad988-6152-41c6-87d5-64cd17a8ebcd)
Model conflicts, not limited to the original version

### Expected Behavior

Can you give the guard a skin without a hat?

### Reproduction Steps

Give a helmet

### Logs

I won't

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Same as: https://github.com/ldtteam/minecolonies/issues/9740#issuecomment-1915175099

**Comment by hjhhhc** [comment]
[minecraft-exported-logs-2024-01-30T01-33-14.log](https://github.com/ldtteam/minecolonies/files/14087695/minecraft-exported-logs-2024-01-30T01-33-14.log)
