### ISSUE TITLE
[BUG] New model bug

### ISSUE THREAD

**Issue by hjhhhc** [ldtteam/minecolonies#9758]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.1.461-BETA

### Structurize Version

1.0.686 beta

### Related Mods and their Versions

forge:47.2.20

### Current Behavior

![2024-01-30_09 53 18](https://github.com/ldtteam/minecolonies/assets/158079751/ddac347b-52cb-4714-92b7-d0d03028a66d)
![2024-01-30_09 53 29](https://github.com/ldtteam/minecolonies/assets/158079751/9dab859c-b803-487f-baa1-07678260918e)
Female character's chest and hair styling

### Expected Behavior

Fix model issues

### Reproduction Steps

Wear a helmet and armor

### Logs

.

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Not a bug. This is fine.
