### ISSUE TITLE
[BUG] <Issue adding minimum stock to the warehouse>

### ISSUE THREAD

**Issue by Krovski6** [ldtteam/minecolonies#9761]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [ ] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [x] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

1.20.1-1.1.461-BETA.jar

### Structurize Version

1.20.1-1.0.686-BETA.jar

### Related Mods and their Versions

1. forge version 47.2.19
2. blockui-1.20.1-1.0.139-BETA.jar
3. domum_ornamentum-1.20-1.0.154-BETA-universal.jar

### Current Behavior

After adding a minimum stock to the warehouse, the warehouse block provided an error message about needed to restart the pack or load a back up.  After the error came up, the clipboard indicated that the warehouse block no longer existed, since all the requests from the colony came up as not having a solution (swine herder wanted carrots, cowhand wanted wheat, etc, things that are normally not on the clipboard because the requests are handled by the couriers).  This happened while my warehouse was being upgraded form level 3 to 4 with the steampunk style.

### Expected Behavior

I guess I expected the warehouse to add my minimum stock request and then send the requests to the lumberjack and sawmill to maintain the minimum stock

### Reproduction Steps

I'm not entirely sure how to reproduce it, but even after loading backups or restarting my game completely, every time I requested the minimum stock I would get the same error message.

### Logs

https://gist.github.com/Krovski6/9bc867115545327e77721dd2e6be5e82

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Haekel** [comment]
This happened to me as well, in this version and a couple weeks ago (though that was the first time I tried to use minimum stock in the warehouse, so the problem might be even older). I'm running the most up to date version of ATM 9, which has 1.12.1-1.1.461-BETA of Minecolonies included.

I managed to get maybe 3 or 4 items into the minimum stock before it disconnected from the warehouse (stones, stone bricks, spruce plants, cracked stone bricks, if that matters). Minimum stock entries did not show up immediately after adding them, but after the next reload of the window. Warehouse did send out work orders to smelter and sawmill before it disconnected.

Running on singleplayer as well. Contrary to the above post, my warehouse was already fully upgraded to level 5 for a while.

Reproduction suggestion: request several stacks of several blocks, wait. As far as I can tell, it only took a couple minutes to break.

Log:
https://gist.github.com/Haekel/a7239716ba044abe30b23cd24ba738f1

Recent crashlog, but crash was most likely not related to the bug (Backpack imprinted on compacting drawer). Adding it anyway in case it helps in any way.
https://gist.github.com/Haekel/571d9faaf5ba4867e8594fc15a27dca6

**Comment by uecasm** [comment]
For now, remove the FindMe mod -- if you happen to press its hotkey (which is easy because it's numpad 0 or 1 or something like that by default) then it will delete any nearby buildings, because Reasons™.

This is a known issue that will hopefully be fixed soon.

Unfortunately unless you have a recent backup then you'll probably need to go into creative and re-paste the warehouse to recover it.
