### ISSUE TITLE
[BUG] <title>Architects recognize Cactus Extra Block.

### ISSUE THREAD

**Issue by ghost** [ldtteam/minecolonies#9776]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.20.1-1.1.464-RELEASE

### Structurize Version

1.20.1-1.0.674-BETA

### Current Behavior

When upgrading a composter hut from 2 to 3, the cactus Extra block was not recognized, so the construction stopped.
Even when I gave him the block circled in the first picture, he did not start building.
![2024-02-11_14 53 00](https://github.com/ldtteam/minecolonies/assets/159679718/072a350f-9ee2-4249-95f8-290ea57599af)
![2024-02-11_14 51 03](https://github.com/ldtteam/minecolonies/assets/159679718/1b4537f8-9
![2024-02-11_14 50 44](https://github.com/ldtteam/minecolonies/assets/159679718/20049d11-9469-42cf-a87f-e394025b0a0d)
518-4f88-b7e1-0a38c644bd5d)
![2024-02-11_14 50 52](https://github.com/ldtteam/minecolonies/assets/159679718/c5a3d1b3-df4a-4453-92ff-dec25e9ac98e)

### Expected Behavior

I don't know.

### Reproduction Steps

1.Build a composter shed level 2.
2.Attempt to upgrade from level 2 to level 3.

### Logs

https://gist.github.com/MinecoloniesLOVE/d60bd3c1cbb7721e8836dd409efc4dbc

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
Hover your mouse over the requested item, like you have in the second image, so that this 
![image](https://github.com/ldtteam/minecolonies/assets/17323101/0ee35332-0ee6-473c-afa3-597b77e9be63) pops up.
Make sure that what you make says the exact same thing.  Might be a panel for example, and you made a trapdoor
