### ISSUE TITLE
[BUG] <AI>

### ISSUE THREAD

**Issue by SupfireDragon** [ldtteam/minecolonies#9781]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

1.0.978-RELEASE

### Structurize Version

1.0.454-ALPHA

### Related Mods and their Versions

1.16.5 
forge 36.2.4.1

### Current Behavior

He's a cattle farmer. I started the game wrong this morning

### Expected Behavior

His behavior seems to be all right, but he just reports mistakes

### Reproduction Steps

I don't know

### Logs

https://gist.github.com/SupfireDragon/09edfa66bfa4947a112f219dd1d4f091

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
This bug is definitely not on our side. Someone adjusted the mojang advancement code for butchering and doesn't accept a non player most likely.

**Comment by Raycoms** [comment]
Can you check if you have any advancement mod or mod with advancements around butchering?

**Comment by Talyda** [comment]
Also playing on an ancient unsupported version ;)
