### ISSUE TITLE
[BUG] Guard's enchanted armor doesn't work

### ISSUE THREAD

**Issue by ddaodan** [ldtteam/minecolonies#9788]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.20.1-1.1.477

### Structurize Version

1.20.1-1.0.693

### Related Mods and their Versions

NeoForge 47.1.99

### Current Behavior

Armor enchantments don't take enchant when the guard takes damage (e.g. "thorns", the monster doesn't take damage)

### Expected Behavior

consistent with players

### Reproduction Steps

1. Hire a guard
2. Dress him in enchanted and unenchanted armor, respectively.

### Logs

No log

### Anything else?

This seems to be an issue after one of the updates in the last 2-3 months
I recorded a video for this, I can provide it if needed

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ddaodan** [comment]
The problem still exists, but only for enchantments added by mods
"Thorns" works after testing
@Raycoms

**Comment by Moobien** [comment]
to my understanding this is normal. MOST enchantments are meant for player only and only work for players.

**Comment by ddaodan** [comment]
> to my understanding this is normal. MOST enchantments are meant for player only and only work for players.


My friend tested that this problem started with version 303, which means that the update to version 303 broke it
