### ISSUE TITLE
Colonist stats still all 1s

### ISSUE THREAD

**Issue by wilsondgonzales** [ldtteam/minecolonies#979]
@Raycoms 

using 7.985 
colony happiness is at 1
colonists still spawn with all 1s for attributes

**Comment by nekatu** [comment]
Finding the same thing; seems to be fine for the initial 4 citizens, but any after that appear to be all 1s on their stats

**Comment by nekatu** [comment]
Just updated to 1.11.2-0.8.1010- still getting new colonists with all 1s for stats

**Comment by Raycoms** [comment]
Yeah that's probably because your happyness is at 1 already?

2017-05-13 20:09 GMT-03:00 nekatu <notifications@github.com>:

**Comment by nekatu** [comment]
It is- so old colonists have to be happy for new colonists to have good stats?

**Comment by Raycoms** [comment]
exactly

2017-05-13 21:41 GMT-03:00 nekatu <notifications@github.com>:

**Comment by Raycoms** [comment]
Let's say it that way "Happy citizen which feel secure and are well
saturated" have "intelligent childs"

2017-05-13 21:59 GMT-03:00 Ray Neiheiser <ray.neiheiser@gmail.com>:

**Comment by nekatu** [comment]
cool, makes sense- so aside from food, what else do we need to do to make them happy?

I have a level 5 townhall, level 5 houses, 2 level 5 guard houses, 1 level 5 warehouse, 1 level 5 deliveryman, all level 5 worker huts. desert biome so no rain and limited mobs.

**Comment by Raycoms** [comment]
You need as many guard huts as worker huts at the same levels

2017-05-13 22:15 GMT-03:00 nekatu <notifications@github.com>:

**Comment by nekatu** [comment]
Do the guard huts need workers too for that to work?

**Comment by Raycoms** [comment]
Yes


2017-05-13 22:23 GMT-03:00 nekatu <notifications@github.com>:

**Comment by nekatu** [comment]
hmm... that's going to take some rethinking on city planning then, just for the sheer amount of space that all those towers are going to take up, never mind the resources to build them. I'll see how it goes though- if nothing else the guards will ensure that there are NO mobs in the area... ;-)

**Comment by Raycoms** [comment]
With the latest update the happiness should be quite okay even with 1/2 or
3/4 if at least saturation and housing is well

2017-05-13 22:27 GMT-03:00 nekatu <notifications@github.com>:

**Comment by Akkaross** [comment]
Hmmm ... So, when a colonist dies, happiness falls to 1. A new colon arrives moments later. With happiness at 1, also his stats. I misunderstood something? We must stop the respawn of colonists the time that happiness goes back up? If yes, how ? ^_^ ' (using 0.8.1010 btw)

**Comment by Raycoms** [comment]
If a colonist dies it decreases by 1 (to 9 for example)
If you kill a citizen it goes to 1.

2017-05-14 11:31 GMT-03:00 Akkaross <notifications@github.com>:

**Comment by Akkaross** [comment]
Ow nice ! That changes everything ! *grab some gravel*

**Comment by wilsondgonzales** [comment]
if guard towers = worker huts with happiness at 1 then
does it automatically go back up?

**Comment by Raycoms** [comment]
Yes

2017-05-14 17:49 GMT-03:00 Wilson Gonzales <notifications@github.com>:
