### ISSUE TITLE
[BUG] Invisible preview supply camp / ship

### ISSUE THREAD

**Issue by PlovieJ** [ldtteam/minecolonies#9791]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.1.479-BETA

### Structurize Version

1.0.696-RELEASE

### Related Mods and their Versions

1. Forge 47.2.20
2. Embeddium 0.3.4 for shaders

### Current Behavior

New world. Crafted supply ship. Placed said ship. Exited because I could not see any preview (hadn't chosen a style yet, fairly new to this mod and didn't know that was required). Tried to get back into the UI by placing the supply ship again. Nothing happens. No preview, no way to get back into the UI, can't place another supply ship. Tried dropping the ship, placing it in inventory, going into creative.

Then tried to see if the same happens with supply camp. Same things apply, but because I got into the supply camp UI, I was then able to try again with the supply ship. Managed to select a style before exiting the UI and then the preview showed up.

### Expected Behavior

1. any kind of "default" supply ship / camp
2. This enables people to get back into the UI
3. The above OR when placing another supply X of the type that we just tried to place, for another UI to pop-up as if placing one for the first time.

### Reproduction Steps

1. make new world as you can apparently only place 1 supply camp/ship per world?
2. try to place either, but immediately exit the UI when it prompts before picking a style or whatever
3. try to place whatever type of supply thingy again. Doesn't work for me. Either for a new prompt or trying to get back into the UI of the previous placement (there is no preview so...)

### Logs

https://pastebin.com/e72SNfc8

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
It seems a custom style you have:

1.20 Check\blueprints\zervanic\decorations\supplies\supplyship.blueprint

is messing with the system?

**Comment by PlovieJ** [comment]
First time using Minecolonies. I don't think I've installed any datapacks or custom Minecolonies.
Only datapack I have is to not spawn abandoned minecolonies. Definitely haven't been making my own stuff.

**Comment by Talyda** [comment]
> It seems a custom style you have:

FWIW cos I've seen this a couple times now, it seems like the UI is defaulting to the player folder maybe? And that is messing things up?
this isn't the first report of it on discord at least =)

**Comment by PlovieJ** [comment]
> > It seems a custom style you have:
> 
> FWIW cos I've seen this a couple times now, it seems like the UI is defaulting to the player folder maybe? And that is messing things up? this isn't the first report of it on discord at least =)

Yeah I commented this in the Discord and was asked to create an issue here as someone mentioned this indeed wasn't their first notice of this bug.
