### ISSUE TITLE
[BUG] Builders AI issue

### ISSUE THREAD

**Issue by g0urra** [ldtteam/minecolonies#9793]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.20.1

### MineColonies Version

1.1.479-BETA

### Structurize Version

1.0.697-BETA

### Related Mods and their Versions

1. Forge Version: 47.2.20
2. BlockUI version: 1.0.139-BETA
3. Domum Ornamenum version: 1.0.157-BETA

### Logs

https://mclo.gs/aY2TZCj

### Anything else?

Several of my builders seem to run into issues mid-building, causing them to stop building at all. Restarting them does not help, nor does restarting the game. Prior to updating to the latest version, one of them showed strange behavior, such as trying to place the same piece over and over. One of the things they might get stuck on is placing torches.

**Comment by Water-Cat1** [comment]
This appears to be happening when they reach the "remove old blocks" step when upgrading a building. Happens with a main building and with decorations that get upgraded.

**Comment by Raycoms** [comment]
With which buildings did you run into this issue?

**Comment by Water-Cat1** [comment]
I have so far encountered it with the restaurant, enchanting tower, glass corridor segment, and mine. Underwater theme pack. Buildings from level 3 to level 4, and the corridor segment from 2 to 3, as that is just what my colony is upgrading to currently.

The builders are placing blocks fine to build the next level, but then get the error when they are removing the old blocks of the previous level. This includes vanilla blocks. The buildings of this level don't have torches either (OP mentioned in original post).

**Comment by g0urra** [comment]
Adding to this, firing the builder and hiring a brand new citizen does not help https://mclo.gs/3g6LkzF

**Comment by g0urra** [comment]
> This appears to be happening when they reach the "remove old blocks" step when upgrading a building. Happens with a main building and with decorations that get upgraded.

What's strange is that a 4th builder I have (my latest one) does not run into this issue.

**Comment by g0urra** [comment]
> With which buildings did you run into this issue?

Any building that's in the process of upgrading, it can even be just a road (Colonial style).

**Comment by g0urra** [comment]
Similar to the mentioned issue earlier, I am also playing on ATM 0.2.51
@Water-Cat1 Do you also play this pack?

**Comment by Raycoms** [comment]
upgrading, so it's not the initial building, right?

**Comment by g0urra** [comment]
After forcing them to not do any upgrades, there seem to be no problem with the initial building. They do however seem to keep complaining about their AI having problems.

**Comment by tecnobrat** [comment]
I am still encountering this issue. It happens when upgrading to the later stages of the `oakwall` variants, but only when they are removing the old blocks of the previous level as stated previously.

Minecraft Version
1.20.1

MineColonies Version
1.1.482-BETA

Structurize Version
1.0.700-RELEASE

Related Mods and their Versions
Forge Version: 47.2.17
BlockUI version: 1.0.139-BETA
Domum Ornamenum version: 1.0.159-BETA

Error from log: https://gist.github.com/tecnobrat/6f99cb83e3aa98e3581c4fdda6050f1e

**Comment by impromptuu** [comment]
just adding another log. Multiple builders building multiple styles from Shire and Cliffs running into AI errors and pausing while upgrading.

minecolonies-1.20.1-1.1.484-BETA
structurize-1.20.1-1.0.701-BETA

[https://gist.github.com/impromptuu/0774f1bb731df1da1acd0f27d491bef8](https://gist.github.com/impromptuu/0774f1bb731df1da1acd0f27d491bef8)
