### ISSUE TITLE
[BUG] Server crashes due to Scoreboards

### ISSUE THREAD

**Issue by SoStokedMyDude** [ldtteam/minecolonies#9795]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [X] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

1.12.2

### Structurize Version

1.12.2-2.0

### Current Behavior

Server crashes when loading

### Expected Behavior

Server loads

### Reproduction Steps

When i updated from the 1.9.9.8 version to 2.0 the issue occured

### Logs

https://gist.github.com/SoStokedMyDude/7f1f1133ec45fa41130433467fe575d5

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
1.12 is no longer supported
