### ISSUE TITLE
[BUG] #9788 not fix

### ISSUE THREAD

**Issue by ddaodan** [ldtteam/minecolonies#9803]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [X] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.20.1-1.1.482

### Structurize Version

1.20.1-1.0.693

### Current Behavior

#9788 
The problem still exists, but only for enchantments added by mods
"Thorns" works after testing
My friend tested that this problem started with version 303, which means that the update to version 303 broke it

### Expected Behavior

Same as before version 303

### Reproduction Steps

same to #9788

### Logs

no

### Anything else?

Curse of Bones from Corail Tombstone
works in version 301
![-6c12a45cfc958396](https://github.com/ldtteam/minecolonies/assets/40017293/97ab95b0-64c9-48cb-8fa7-54ac2aa54788)

This problem prevents my guards from being able to withstand the raid

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by ddaodan** [comment]
So what can I do besides rolling back the version?

**Comment by Raycoms** [comment]
Can you try the latest?

**Comment by ddaodan** [comment]
> Can you try the latest?

No, I have been staying on version 301 because it is the last version without this issues.

**Comment by Raycoms** [comment]
The latest might fix this now too
