### ISSUE TITLE
[BUG] Issues running a colony into the nether

### ISSUE THREAD

**Issue by MissLopiah1** [ldtteam/minecolonies#9804]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

minecolonies-1.20.1-1.1.464-RELEASE

### Structurize Version

structurize-1.20.1-1.0.700-RELEASE

### Related Mods and their Versions

1. forge 47.2.0 2. domum_ornamentum-1.20-1.0.151-BETA-universal 3. multipiston-1.20-1.2.31-ALPHA 4. architectury-9.2.14-forge 5. blockui-1.20.1-0.0.101-ALPHA 6. towntalk-1.20.1-1.0.1

### Current Behavior

Colony isnt saving when logging out in the nether colonists reset to their debug name and debug model when clicking on the town hall it then states that theres a colony with the ID #1 but when trying to claim it it states the colony isnt in this dimension
![debug](https://github.com/ldtteam/minecolonies/assets/161590204/0a3f8aa8-f93d-4db4-b15f-d6bc321324e2)
![image](https://github.com/ldtteam/minecolonies/assets/161590204/08c65d7c-7505-47eb-afff-ff200ab1f547)

### Expected Behavior

for me to run a colony in the nether

### Reproduction Steps

1. go into the nether
2. teleport around 5000 blocks away
3. create a colony 
4. Log out of world
5. Log back in

### Logs

https://gist.github.com/MissLopiah1/3f39b35f10ce44b16ec6c673bb362b24

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
Could you provide the entire log? This only seems to be the end of it
