### ISSUE TITLE
[BUG] Forester Tree Detection

### ISSUE THREAD

**Issue by Moobien** [ldtteam/minecolonies#9805]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [X] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.1.483

### Structurize Version

1.0.699

### Related Mods and their Versions

n/a

### Current Behavior

Forester cannot detect all trees inside the assigned zone. more specifically the ones 25 blocks above the forester.

### Expected Behavior

Expected: forester able to detect all trees within the assigned zone.

### Reproduction Steps

1: start a colony.
2: place aquatica/agriculture/fields/atrium_d3 or higher
3: plant 1 or 2 trees on bottom deck and bonemeal. go up the top and do the same.
4: place aquatica/fundamantals/forester and hire a  forester.
5: set a zone that covers both the upper and lower sections
6: observe

### Logs

n/a

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

![2024-02-29_03 08 34](https://github.com/ldtteam/minecolonies/assets/17806806/466effd9-88b0-4503-a577-c332f662aaa4)
![2024-02-29_03 10 01](https://github.com/ldtteam/minecolonies/assets/17806806/41107417-aae9-458a-9014-c7bb580beaf6)
![image](https://github.com/ldtteam/minecolonies/assets/17806806/35724511-5c1e-47d8-ad9c-885f439ae291)

This isn't exclusive to the aquatica atrium d. this also happens for the steampunk forestry tower. Forester harvests the trees on the lower deck with no issues but cannot detect the ones on the upper deck. Have tested this previously in a clean test world using the steampunk forestry tower.

**Comment by Raycoms** [comment]
Duplicate?
