### ISSUE TITLE
[BUG] <can’t put planks into acatect cutter

### ISSUE THREAD

**Issue by comrade-lucius** [ldtteam/minecolonies#9810]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.1.484-beta.jar

### Structurize Version

1.0.699-beta.jar

### Current Behavior

I can no longer place planks in the cutter making it impossible to use the mod

### Expected Behavior

To place it in and craft

### Reproduction Steps

1.open the architects cutter 2.try to place a plank

### Logs

What???

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
Do you have Epic Paladins installed? That breaks the cutter

**Comment by Talyda** [comment]
Also, logs are in your logs folder in your instance

**Comment by comrade-lucius** [comment]
No

**Comment by comrade-lucius** [comment]
Could there be another issue

**Comment by comrade-lucius** [comment]
I have simply swords installed

**Comment by Talyda** [comment]
Then add your logs so people can look at them =)

**Comment by comrade-lucius** [comment]
How

**Comment by comrade-lucius** [comment]
Like how do I edit it

**Comment by comrade-lucius** [comment]
or post logs

**Comment by Talyda** [comment]
(copying this from discord - BTW discord is a better place to try and get help initially!)
To properly diagnose your issue we need access to your logs please. 
You can generally find these logs in your game or server directory under the logs folder. The file latest.log is most likely required.
Once you've found this file please post it on a paste site. As a team we recommend https://gist.github.com/

You go to https://gist.github.com/
You sign up or in
There should be a button to make a gist somewhere. If not, go to https://gist.github.com/ again
Drag the file on the big text area
Click "Create secret gist"
Copy the url out of the address bar and paste it in here
