### ISSUE TITLE
[BUG] Research is not progresing

### ISSUE THREAD

**Issue by Ashan040** [ldtteam/minecolonies#9811]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.1.470

### Structurize Version

1.0.691

### Current Behavior

Even though the items have been placed, the scientist is not developing the technology
![Zrzut ekranu 2024-02-29 163002](https://github.com/ldtteam/minecolonies/assets/161731122/2e9c9487-4701-4913-960a-6df73e1f75db) I play on my own server

### Expected Behavior

.

### Reproduction Steps

I don't know

### Logs

I do not know how

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
The timer doesn't actively tick down, but the research bar has literally moved, you can see the progressbar having advanced slightly.
