### ISSUE TITLE
[BUG] After playing for a while, soldiers and couriers may have convulsions

### ISSUE THREAD

**Issue by lja1317990** [ldtteam/minecolonies#9819]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.1.493-RELEASE

### Structurize Version

1.0.699-BETA

### Related Mods and their Versions

Forge 47.2.0
Domum_ornamentum 1.0.160-BETA 
Block-ui 1.0.139-BETA
Multi-piston 1.2.32-Aplha
Towntalk 1.0.1

### Current Behavior

https://github.com/ldtteam/minecolonies/assets/162317074/3fe22106-2acc-42d8-976e-f98ab3566d52

### Expected Behavior

My colony has a large population of about 100 people, and after playing for a period of time, soldiers and couriers may encounter such bugs

### Reproduction Steps

I uninstalled optimizations such as embeddium and oculus, as well as entity mods, but they did not solve this problem

### Logs

It didn't crash my game

**Comment by Raycoms** [comment]
Is that on a server? How often do you restart?

**Comment by lja1317990** [comment]
> Is that on a server? How often do you restart?
This is a single player. In version 1.20.1, I only loaded the simulated colony mod and ice and fire mod, which also caused this problem

**Comment by lja1317990** [comment]
> Is that on a server? How often do you restart?

However, it does take more than 10 minutes of gameplay to appear, and there was no such problem at first

**Comment by lja1317990** [comment]
https://github.com/ldtteam/minecolonies/assets/162317074/fba3db6f-d585-4391-b536-a78f3432a958

@

**Comment by aAndrew3030** [comment]
I am experiencing the same issue and also tried disabling all performance mods. I did notice that the citizens continue to work even while glitching and continue to do tasks normally. It appears to be only a rendering issue? Currently at 150 citizens it starts with at least a couple after starting the game and continues to get worse until I restart

If it helps, a debug.log
[debug-2.log.gz](https://github.com/ldtteam/minecolonies/files/14531512/debug-2.log.gz)

**Comment by lja1317990** [comment]
> I am experiencing the same issue and also tried disabling all performance mods. I did notice that the citizens continue to work even while glitching and continue to do tasks normally. It appears to be only a rendering issue? Currently at 150 citizens it starts with at least a couple after starting the game and continues to get worse until I restart
> 
> If it helps, a debug.log [debug-2.log.gz](https://github.com/ldtteam/minecolonies/files/14531512/debug-2.log.gz)

It is worth noting that I did not have this issue in the archive of version 1.18.2

**Comment by Talyda** [comment]
FWIW I have this happening right now on the patreon server, and I only logged in 10 minutes ago

Logged out and  in again, and seems to be ok again

**Comment by aAndrew3030** [comment]
> FWIW I have this happening right now on the patreon server, and I only logged in 10 minutes ago
> 
> Logged out and in again, and seems to be ok again

Your using the default pack? (nothing client side added). If it is a mod conflict, this greatly narrows down the number of mods!

**Comment by Talyda** [comment]
Cavecolonies modpack, with some client side mods

**Comment by aAndrew3030** [comment]
> Cavecolonies modpack, with some client side mods

Have you tried with the added client side mods disabled? If that fixes the issue for you, please share a list of the added mods so we can also test with them disabled in our packs. That would greatly help narrow down the mod causing the conflict

**Comment by aAndrew3030** [comment]
Or it it is easier, just share a list of the mods you added so we can test it.

**Comment by Talyda** [comment]
It hasn't happened again, so can't test it.

And TBH I can't recall exactly what I added!
If these weren't already in the pack, this is probably what I added
Neat 1.20.35
mousetweaks 1.20-2.25
light overlay 8.0.0
JER 1.20.1-5.9-18
inventory profiles next 1.20-1.10.9
crafting tweaks 1.20-18.2.2
appleskin 1.20.1-2.5.1
(plus any dependencies I guess!)

**Comment by Talyda** [comment]
Oh, and I disabled BHMenu

**Comment by Raycoms** [comment]
Those are usually the "duplicate stuck ones" when they are like this in airl.

**Comment by Sandriell** [comment]
I get this all the time if I leave the area and then come back before the colony unloads. Like when I use a waystone to go to a friend's colony and then go back to my colony within 10 minutes (the time a colony stays loaded).

If I stay away for longer than 10 minutes, I don't see the issue.

This is on 1.19.2. [[Mod List](https://gist.github.com/Sandriell/765f5ba6b2853df86c6aba9be807576e)]

**Comment by lja1317990** [comment]
> Or it it is easier, just share a list of the mods you added so we can test it.


It's not a mod conflict, I have tested it

**Comment by someaddons** [comment]
fixed
