### ISSUE TITLE
Modded Server Crash Minecolonies / by zero

### ISSUE THREAD

**Issue by pieeep123** [ldtteam/minecolonies#982]
### Minecolonies version

version ?.?.???? or curse 0.8.974 (1.11.2)

### Expected behavior

- Tried building a new colony on my new server everything fine.

### Actual behaviour

- Server crash. Sometimes immediately after giving a build order for the town hall, sometimes later at seemingly random points in time.
- I'm actually really unexperienced in programming, but I think it is trying to divide by zero somewhere, maybe it's something to do with the happiness value of the colony?

### How to solve the issue

- Well it didn't work in the version before this one, but maybe in an older one?
- Otherwise, I am lost.

[crash-2017-05-12_16.14.57-server.txt](https://github.com/Minecolonies/minecolonies/files/997133/crash-2017-05-12_16.14.57-server.txt)

**Comment by Raycoms** [comment]
Uhh, I actually forgot to add that to 1.11.2. I fixed that in 1.10.2
already.

2017-05-12 12:21 GMT-03:00 pieeep123 <notifications@github.com>:

**Comment by Raycoms** [comment]
Yeah we're dividing through 0.
That crash happens when it gets night and there are 0 citizen in a colony.

2017-05-12 12:24 GMT-03:00 Ray Neiheiser <ray.neiheiser@gmail.com>:

**Comment by pieeep123** [comment]
Ahh thank you that response was quick :D
So I assume I merely have to watch out for an empty colony at night and then upgrade the mod version as soon as a new update is released

**Comment by Raycoms** [comment]
Exactly =D

2017-05-12 12:44 GMT-03:00 pieeep123 <notifications@github.com>:
