### ISSUE TITLE
[BUG] UI does not scale past 4

### ISSUE THREAD

**Issue by awesomepuppy404** [ldtteam/minecolonies#9821]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [x] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [X] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.20.1-1.1.494-BETA

### Structurize Version

1.20.1-1.0.697-BETA

### Current Behavior

Minecolonies GUI stops scaling past minecraft GUI scale setting of 4 

### Expected Behavior

GUI should continue scaling up at larger GUI scale options

### Reproduction Steps

1. Use a screen with a resolution of at least 1600x1200
2. Set GUI scale to 4 and open a MineColonies menu
3. Set GUI scale to 5 and open another MineColonies menu
4. MineColonies GUI has not continued to scale along with the rest of the game

### Logs

[Log](https://paste.ee/p/nnlEG)

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Nightenom** [comment]
Our GUIs have different size compared to all vanilla GUIs, its possible that GUIs you have tried are in one dimension bigger than "allowed" vanilla maximum, which results in higher gui_scale not applying as expected (the GUI would simple overflow out of your monitor), if you have latest blockui (1.0.149-BETA) you may press left ctrl+shift+alt to see debug info for our GUIs which also shows `Scaling: [scaling mode] (vanilla: [gui_scale in your settings] our: [gui_scale of rendered GUI])`

**Comment by awesomepuppy404** [comment]
Please elaborate on what you mean here? There is no “allowed” vanilla maximum… max gui_scale setting is calculated based on display resolution.

**Comment by awesomepuppy404** [comment]
The vanilla max gui_scale is calculated based on the formula `max(1, min(floor(width / 320), floor(height / 240)))`

**Comment by Nightenom** [comment]
I meant maximum GUI size which you can see in the formula: 320 x 240 px, some of our GUIs are large in one or both dimensions therefore will result in smaller gui_scale than in your settings

**Comment by awesomepuppy404** [comment]
My screen is 2880 x 1800. The area that MineColonies takes up is minuscule — I have to strain my eyes to even try and read the text. Why should the MineColonies UI stop scaling at 4 when the vanilla UI does not? This is unrelated to your UI being large in any one dimension. It should continue scaling up as is intended vanilla behavior (to make it usable on large screens).

**Comment by Nightenom** [comment]
Name the gui(s) you have problem with - it's quite common someone forgot to give it proper size, otherwise in our code there is no such limitation you're talking about - we take gui_scale from vanilla settings, and do min of "max possible scale of current gui" and "vanilla settings"

**Comment by awesomepuppy404** [comment]
Resource scroll, town hall, builders hut, interactions with colonists, residences, etc. — I haven’t come across a MineColonies GUI not affected by this issue.

**Comment by awesomepuppy404** [comment]
I can get screenshots later.

**Comment by Raycoms** [comment]
I have a strong feeling that another mod is messing with this. I got high res screens and it scales perfectly fine for me.

**Comment by JerryWeii-27** [comment]
Hey, I know that this is a few months old but is there a solution? For me,  it is vanilla: 5 our: 2, but how do I change that?
