### ISSUE TITLE
[1.20.1] [BUG] Packet error: java.lang.NullPointerException: Cannot invoke "com.minecolonies.api.colony.IColony.getName()"

### ISSUE THREAD

**Issue by Sandriell** [ldtteam/minecolonies#9828]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

minecolonies-1.20.1-1.1.501-BETA

### Structurize Version

structurize-1.20.1-1.0.701-BETA

### Related Mods and their Versions

Forge: 47.2.17
Mod List: https://gist.github.com/Sandriell/50674f01415bbff167ec9f974b20311c

### Current Behavior

Found an abandoned colony. When clicking on the townhall black it is generating the following packet error:

https://gist.github.com/Sandriell/06c5ea069fe43fe68baa37998d6c47e2

This may be happening on a placed townhall as well, but did not test that. This is a brand new world.

### Expected Behavior

No error, open the Townhall GUI

### Reproduction Steps

Start world.
Fine abandoned colony (or start one perhaps, did not test that)
Right click on townhall block.

### Logs

https://gist.github.com/Sandriell/06c5ea069fe43fe68baa37998d6c47e2

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
fix pushed
