### ISSUE TITLE
[BUG] Crash when trying to open the map

### ISSUE THREAD

**Issue by IchHabeHunger54** [ldtteam/minecolonies#9830]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.20.1-1.1.494-BETA

### Structurize Version

1.20.1-1.0.701-BETA

### Related Mods and their Versions

NeoForge 1.20.1-47.1.79
~25 other mods that should not be relevant, mostly Minecolonies dependencies and some simple mods like JEI, Mouse Tweaks, Embeddium, etc. Please ask in the issue if you need the list.

### Current Behavior

The game crashes when trying to open the map in the town hall.

### Expected Behavior

No crash, and a normal map GUI.

### Reproduction Steps

1. Drop off a map in the Town Hall inventory.
2. Open the Town Hall menu again, click the Map button.
3. Crash.

### Logs

https://gist.github.com/IchHabeHunger54/d0cea815d3749ad9f4b53684e7604202

### Anything else?

Semi-related: I also noticed that the text saying "please drop a map off in the inventory" changes its color when hovered. Nothing major, but a tad bit annoying.

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
Was fixed yesterday IHH =)

https://github.com/ldtteam/minecolonies/issues/9822

**Comment by IchHabeHunger54** [comment]
Ah, didn't think far enough to check the closed issues. My bad!
