### ISSUE TITLE
[BUG] Trying to place supply camp is crashing game (not server)

### ISSUE THREAD

**Issue by FIegaIkCz** [ldtteam/minecolonies#9839]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [x] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.20.1-1.1.502 BETA

### Structurize Version

1.20.1-10.703 BETA

### Related Mods and their Versions

Forge 47.2.0
Domum 1.20-1.0.166 BETA
blockui 1.20.1-1.0.151 BETA
Byzantine-1.20.1-11.1
stylecolonies-1.3.2

### Current Behavior

take supply camp item
right click on ground
game crashes (tested on server, server is okay)

### Expected Behavior

when r-click on ground, gui for palcing shows up

### Reproduction Steps

take supply camp (from loot chest in my case)
(i was in byzantine style colony) right click on ground to place it
game crashed

### Logs

https://justpaste.it/bwk5j

### Anything else?

i think why that happened.
i tried to place down supply camp (from loot chest, but dont think that matters)
when i already had a TownHall (Byzantine style) and it crashed my game. 
I think its bcs Byzantine doesnt actually have supply camp , only ship.

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Can you also give us your latest.log?

**Comment by FIegaIkCz** [comment]
I tried, but 10k lines just lagged the site. But sure. Im starting game and
i will try to reproduce in singleplayer aswell

Dne čt 14. 3. 2024 9:18 uživatel Raycoms ***@***.***> napsal:

**Comment by Raycoms** [comment]
gist.github.com

**Comment by FIegaIkCz** [comment]
https://gist.github.com/FIegaIkCz/77354a2bc14e6d70ff3626540b973f60

**Comment by FIegaIkCz** [comment]
btw, couldnt reproduce it on singleplayer and now i didnt even reprodice it on server.. but i crashed 2 times yesterday when i sent it on discord

**Comment by nanonestor** [comment]
Here is a crash report from someone getting supply camp placement crashes.

It's using version 1.20.1-1.1.507-BETA - I looked at the commits done since that version and does not look like anything changed since this version is relevant?

[Crash Report - paste.gg website paste](https://paste.gg/p/anonymous/2af92baf329e40f4b6104c7f11056528)


[crash-2024-03-17_19.25.54-client.txt - file](https://github.com/ldtteam/minecolonies/files/14631735/crash-2024-03-17_19.25.54-client.txt)
