### ISSUE TITLE
[BUG] Builder: My AI ran into an issue

### ISSUE THREAD

**Issue by HendrikJ79** [ldtteam/minecolonies#9842]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.20.1

### MineColonies Version

1.20.1-1.1.507-beta

### Structurize Version

1.20.1-1.0.708-beta

### Related Mods and their Versions

Forge Version: 47.2.21
BlockUI Version:  1.20.1-1.0.151-beta
Domum Ornamentum: 1.20.1-1.0.166-beta

### Reproduction Steps

Placed the Jungle Treehouse supply camp in the world, on the signed place dropped the town hall block, when building over the excisting supply camp it ran in to an problem.
Solved this by removing the racks and restarting my server.

### Logs

https://gist.github.com/HendrikJ79/942f2de0a533e984eec179be249ff571

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by HendrikJ79** [comment]
This is going to be annoying, don't know what to do as the citizens keeps saying "My AI ran into an issue"
Updated al the mods to the latest versions.
Log: https://gist.github.com/HendrikJ79/75414605ecf114612c5114c808dd4160

**Comment by Raycoms** [comment]
fixed already update domum and minecol
