### ISSUE TITLE
[BUG] Resource request for Mine has extra 0 (needs 1 item, requests 10)

### ISSUE THREAD

**Issue by MossyJossy** [ldtteam/minecolonies#9843]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

1.1.473-BETA

### Structurize Version

1.1.473-BETA

### Related Mods and their Versions

1. Valhesia 5-5.3.0
2. blockui-1.19.2-1.0.140-BETA
3. domum_ornamentum-1.19-1.0.146-BETA

### Current Behavior

When the Mine is requesting items using the request system, it is populating on the clipboard and in other worker tasks as having an added 0 to the amount of items needed. 
Example: Mine requires 31 Oak Fence, as seen in mine building block Required Resources Tab, but in the Clipboard it shows as requiring 310 Oak Fence. This issue also effects the task request system for other workers/building blocks, such as the forester to make 40 stripped oak instead of 4, clogging up their workload.
The same happens for all current items required by the mine, and does not happen for any other building request system.

### Expected Behavior

Request system should show the correct number of required resources for the Mine.

### Reproduction Steps

1. Run Valhesia 5 (5.3.0) from forge
2. Have mine working to build new level
3. Check clipboard for error

### Logs

https://gist.githubusercontent.com/MossyJossy/1a162a783bb51f678175b2461cb6f2ab/raw/a8f471ad69717a3d83ec1c644915fce5716ea767/latest.log

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
That is intended. They ask for more than they need, so that they need to ask less often
They are by the way happy with just the amount needed
(the requests should show something like "6 - 60 oak fences", which means they happily take 60 fences if those are available, but they at least need 6 to continue working)
The crafters try to make the full amount if possible, also because it is more efficient than having ten separate requests over time

**Comment by MossyJossy** [comment]
> That is intended. They ask for more than they need, so that they need to ask less often They are by the way happy with just the amount needed (the requests should show something like "6 - 60 oak fences", which means they happily take 60 fences if those are available, but they at least need 6 to continue working) The crafters try to make the full amount if possible, also because it is more efficient than having ten separate requests over time

Is there a way to turn this off or change it in the config so they request the minimum? It just doesn't seem to work smoothly for me at the start of a town when resources are still low.

**Comment by Raycoms** [comment]
I adjusted it to x4, x10 was a bit of an overkill

**Comment by MossyJossy** [comment]
> I adjusted it to x4, x10 was a bit of an overkill

Thank you so much! If there's any chance this could be done for a minecraft version 1.19.2 that would also be incredible but I can understand if not a priority, I just won't be able to use it for what I am playing at the moment.
