### ISSUE TITLE
[BUG] Crash when trying to place second supply ship

### ISSUE THREAD

**Issue by TheNumenorean** [ldtteam/minecolonies#9849]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.20.1-1.1.510

### Structurize Version

1.20.1-1.0.708

### Current Behavior

Game client crashes when right-clicking with a supply ship in hand.

### Expected Behavior

no crash.

### Reproduction Steps

1. Place supply ship
2. Create colony
3. Try to place a second supply ship.

### Logs

https://gist.github.com/TheNumenorean/2ca4cca3aea111ca0f9d1dad3240ff8a

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by TheNumenorean** [comment]
Actually duped by #9839, but leaving this here for the second data point.

**Comment by Raycoms** [comment]
will close in favor of https://github.com/ldtteam/minecolonies/issues/9839
