### ISSUE TITLE
Request: Reduce the number of guard towers required for Happiness

### ISSUE THREAD

**Issue by Amadeus99** [ldtteam/minecolonies#985]
### Minecolonies version

Curse 0.8.1009

### Expected behavior

Not to need almost half your population as Guards.

### Actual behaviour

With this update, housing has some affect on happiness.  I believe at most, averageHousing would be equal to 5 which is only as valuable as one level 5 Guard Tower.  Saturation looks like it would max out to be as valuable as one level 5 Guard Tower, as well.  So, best case you could have two less Guard Towers and break even.  This is all assuming you max out all building levels.   If you have 10 level 5 houses, you would be able to have 26 citizens assigned to max level work buildings and would have to have 24 citizens as Guards.  And that would only allow you to break even on Happiness IF you got the best value for Saturation every day.  So, more than likely you would have to have 25 Guards.  It just seems a bit much to me to have to have half your population as Guards in order to keep your colony happy.

If needing half your population as Guards was intended, then please just close this ticket.  If not, maybe do something as simple as doubling the worth of Guard Tower levels which would drop the number of Guard Towers needed to one third the colony population.  Or triple the worth of Guard Tower levels to reduce needed Guard Towers to one quarter the population.
Thanks.

**Comment by nekatu** [comment]
I have to agree with this, as per #979; this requirement for 1 guard tower per worker hut seems excessive. 

A better system might be 1 guard tower per citizen house instead, that way you have a 1 tower to 5 citizen ratio, which seems fair to me. Especially given that all citizens are in the houses (or the hall) at night, which is generally the time they would by most scared and in need of protection.

You could even have it so that the higher level towers support 2 guards (as per the number of beds) which means you should need half the number of towers currently required anyway.

**Comment by Raycoms** [comment]
The thing is you won't need all guard towers for full happiness.
I will have breakfast and explain it here

2017-05-14 7:00 GMT-03:00 nekatu <notifications@github.com>:

**Comment by Raycoms** [comment]
Okay let's say all your citizen live in level 5 houses.
That means your overall happiness +1 per night.
If they're all well saturated + 0.5 - +1 per night.

Let's say you have 10 workers and 5 guards.
That's -1 per night.




And 5 guards for 10 workers is nothing, even more considering if we add in
the future a system where pirates and babarians attack depending on your
development of the city.

2017-05-14 9:21 GMT-03:00 Ray Neiheiser <ray.neiheiser@gmail.com>:

**Comment by Amadeus99** [comment]
So, based on your example, 15 citizens.  3 level 5 houses would make averageHousing = 5.  Happiness increases by 5 * HAPPINESS_FACTOR which is 0.1 which means happiness increases by 0.5.

I am assuming saturation maxes out at 10.  Maximum averageSaturation would be 10.  WELL_SATURATED_LIMIT = 5.  That means maximum increase to happiness would be (averageSaturation - WELL_SATURATED_LIMIT) * HAPPINESS_FACTOR = (10 - 5) * 0.1 = 0.5.

10 workers working in level 5 buildings: requiredGuardLevels += 50.  5 guards in level 5 towers: requiredGuardLevels -= 25.  requiredGuardLevels = 25.  Happiness decreases by 25 * HAPPINESS_FACTOR = 2.5.

Overall happiness decreases by 1.5.

Changing to 9 workers and 6 guards would be a decrease in happiness by 0.5.  And changing to 8 workers and 7 guards would be an increase to happiness by 0.5.  So, back to nearly half the population as guards.

Where am I going wrong with the calculations?

**Comment by Raycoms** [comment]
Ah I thought the happiness factor was 0.2 for the others. Read wrongly in
my own code =P.

Hmm I will see about that and make the security thingy an average as well
so it won't influence that hard.

2017-05-14 16:39 GMT-03:00 Amadeus99 <notifications@github.com>:

**Comment by SulpherStaer** [comment]
How many workers do you all add in your colony? You don't need that many. One or two is more than enough! Unless you feel they are building WAY to slow?...

**Comment by Amadeus99** [comment]
I'm guessing you mean specifically builders which we have 2.  Overall for workers, we have 2 builders, 2 delivermen, 2 miners, 1 farmer, and 1 lumberjack.

**Comment by Amadeus99** [comment]
I just looked at the changes to how happiness is modified based on guard tower levels.  Please correct me if I'm wrong, but:

1. Now you lose happiness if you have more guard tower levels than worker building levels if you have at least twice as many guard tower levels as worker building levels.
2. You can have no guard towers and you will have no loss in happiness.
3. You can no longer gain happiness from having any amount of guard towers.

**Comment by Raycoms** [comment]
Wow good catch, I think something went wrong there when I merged the
branchs it should be workers/guards and not the other way around...

2017-05-16 9:27 GMT-03:00 Amadeus99 <notifications@github.com>:

**Comment by Raycoms** [comment]
That should be fixed already.
