### ISSUE TITLE
[BUG] <Scaffolding pathing broken>

### ISSUE THREAD

**Issue by Tuganace** [ldtteam/minecolonies#9851]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [X] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.1.512-BETA

### Structurize Version

1.0.712-BETA

### Current Behavior

Citizens will just stand/ignore scaffolding path, no matter if it's underground pathing or made as a bridge.

### Expected Behavior

To be able to path via scaffolding, (in this case for animal pens)

### Reproduction Steps

Try and do the animal scaffolding guide that is usually posted on the official discord.

### Logs

https://gist.github.com/Tuganace/dc91ae0da6e0f7b3443dadf5fc7bba84

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
It's part of the vines research now. Will need to be updated on the wiki, and probably the vines research desc

**Comment by Talyda** [comment]
ohhh!
Well! That kinda sucks. But at least now we know!
(sorry, shoulda explained why I think it sucks =P) I always avoid the vine research, cos the citizens are total derps on vines. Scaffolding used to just work.

**Comment by uecasm** [comment]
Petition to change it back ☑️ 
Or at least to make it a separate research.

**Comment by MotionlessTrain** [comment]
Scaffolding can be very useful in e.g. the Jungle Treehouse style, where the vines research is not recommended (due to the pathfinding haywire with all vines in the style)

**Comment by Raycoms** [comment]
I'd be totally fine with it being a separate research

**Comment by Talyda** [comment]
Why does it have to be a research? It used to just work.
I mean, yeah, a separate one would be better, but GAH! More research!

**Comment by Moobien** [comment]
> It's part of the vines research now. Will need to be updated on the wiki, and probably the vines research desc
what if I dont want them climbing vines but need them using scaffolds...

**Comment by Moobien** [comment]
> ohhh! Well! That kinda sucks. But at least now we know! (sorry, shoulda explained why I think it sucks =P) I always avoid the vine research, cos the citizens are total derps on vines. Scaffolding used to just work.

its now forcing players to use a research they probably werent doing as it wasn't needed for their colony. this is a BAD idea for any colony that uses vines decoratively.

**Comment by Moobien** [comment]
what if I have vines all over the place but dont want them using them but have buildings that use scaffolds?

**Comment by Shadizar** [comment]
All my pens use scaffolding from. Level 1 as the sole entry 

I don't know if other styles may also

Can this please be reverted?  Scaffolding is key also to vertical colonies and I have used it extensively on most playthroughs

**Comment by Shadizar** [comment]
And we can't tag player placed as tag tool is creative only 

It's unclear why this is a thing....

**Comment by MotionlessTrain** [comment]
> All my pens use scaffolding from. Level 1 as the sole entry
> 
> I don't know if other styles may also
> 
> Can this please be reverted? Scaffolding is key also to vertical colonies and I have used it extensively on most playthroughs

That is what the linked PR is doing

**Comment by MotionlessTrain** [comment]
> And we can't tag player placed as tag tool is creative only
> 
> It's unclear why this is a thing....

It would be a block tag (datapack tag) rather than a tag tool tag

**Comment by Shadizar** [comment]
Ok
Sorry, got very confused
