### ISSUE TITLE
[BUG] Build tool broke because of "missing building name"

### ISSUE THREAD

**Issue by cocoa005** [ldtteam/minecolonies#9854]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.20.1

### MineColonies Version

1.1.512-BETA

### Structurize Version

1.0.708-RELEASE

### Reproduction Steps

1. Right-click the ground with build tool
2. Expect the build tool GUI to show, but instead be greeted by just the green checkmark and red x, and nothing more.

### Logs

https://mclo.gs/94woD93

### Anything else?

I was directly instructed to open this issue by staff member Mirality in the donor's Discord, who stated:

> it looks like they were trying to build a tavern, or a parent that contains a tavern, but it was missing its building name so the build tool broke.
> which definitely means something needs to be rescanned, but also is probably a bug to make the build tool a bit more robust.  can you put that on github please?

https://discord.com/channels/472875599422291968/486940969737125922/1219554176518848542 

I apologize if I opened this issue incorrectly at all, this is my second time ever doing this lol. I'm not very familiar with GitHub.

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
May I know which pack/schematic you attempted to place down?

**Comment by cocoa005** [comment]
> May I know which pack/schematic you attempted to place down?

Hi. This issue is happening to one of the users on my server (doesn't have GitHub), so I'm going to give you their response to your question:

> Dark Dust style
> 
> I was trying to place a tavern

> But in general it didn't let me see any different style packs when using the build tool, or any previews of builds

> If you click the styles panel on the upper left when using the build tool, t would just show a blank screen with cancel or a search bar. And typing in the search bar shows nothing
