### ISSUE TITLE
[BUG] Water clearing doesn't account for flowing water in schematics.

### ISSUE THREAD

**Issue by Moobien** [ldtteam/minecolonies#9861]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [X] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.1.515-BETA

### Structurize Version

1.0.712-BETA

### Related Mods and their Versions

n/a

### Current Behavior

when a schematic has flowing water in a schematic the clearing doesn't take into account flowing water and simply leaves source blocks.

### Expected Behavior

water is cleared/flowing water treated as air blocks for the purpose of clearing.

### Reproduction Steps

build Aquatica/miilitary/lure1
compare constructed against the preview.

### Logs

n/a

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.
![2024-03-22_21 16 45](https://github.com/ldtteam/minecolonies/assets/17806806/2034ba0b-e377-4126-a8d4-feb40081c72a)
after constructiion/water clearing

![2024-03-22_21 19 44](https://github.com/ldtteam/minecolonies/assets/17806806/d5f696a9-d899-480a-a659-f6483bc9eb45)
how the schematic says the water should be.

**Comment by Raycoms** [comment]
Honestly, I have to mark this as "not-planned". This is one of these edge cases we won't support.

**Comment by Moobien** [comment]
you realise it could happen to every concrete mixer right?

**Comment by Moobien** [comment]
gonna test

**Comment by Raycoms** [comment]
In the extreme edge cases, yes.

**Comment by Moobien** [comment]
in all cases where water might already exist actually. and expecting/demanding players NEVER place their concrete mixers near water is a bit of a lofty dream Ray, will never happen. people place where they want to place
