### ISSUE TITLE
[BUG] Builder AI 

### ISSUE THREAD

**Issue by Erwancdorcha** [ldtteam/minecolonies#9864]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.20.1

### MineColonies Version

1.1.521-BETA

### Structurize Version

1.0.708-RELEASE

### Related Mods and their Versions

1. alexsdelight-1.5 
2. alexsmobs-1.22.8 
3. amendments-1.20-1.1.11
4. appleskin-forge-mc1.20.1-2.5.1
5. berries_and_cherries-1.0.9-hotfix
6. Better_Dogs_X_Doggy_Talents_Next_v1.2.1 [1.20-1.20.1]
7. BetterCompatibilityChecker-forge-4.0.8+mc1.20.1
8. blockui-1.20.1-1.0.151-BETA
9. Butchersdelight beta 1.20.1 2.0.9f
10. Butchersdelight Foods beta 1.20.1 1.0.2
11. citadel-2.5.4-1.20.1
12. corail_recycler-5.9.1-1.20.1
13. corail_woodcutter-1.20.1-3.0.4
14. corn_delight-1.0.3-1.20.1
15. cratedelight-1.0.7-1.20.1-forge
16. curios-forge-5.7.2+1.20.1
17. DoggyTalentsNext-1.20.1-1.18.10
18. Domum_ornamentum-1.20.1-1.0.181-BETA-universal
19. embeddium-0.3.9+mc1.20.1
20. endersdelight-1.20.1-1.0.3
21. entity_model_features_forge_1.20.1-1.3
22. entity_texture_features_forge_1.20.1-5.2.3
23. entityculling-forge-1.6.2-mc1.20.1
24. FarmersDelight-1.20.1-1.2.4
25. farmersutils-1.0.5-1.20.1
26. iceandfire-2.1.13-1.20.1-beta-4
27. ItemsDisplayedForge-v1.2.2-1.20.1
28. Jade-1.20.1-forge-11.7.1
29. JadeColonies-1.20.1-1.4.2
30. jei-1.20.1-forge-15.3.0.4
31. journeymap-1.20.1-5.9.18p1-forge
32. JustEnoughResources-1.20.1-1.4.0.247
33. moonlight-1.20-2.11.9-forge
34. MouseTweaks-forge-mc1.20-2.25
35. multipiston-1.20-1.2.43-RELEASE
36. mysterious_mountain_lib-1.4.4-1.20.1
37. nethersdelight-1.20.1-4.0
38. oceansdelight-1.0.2-1.20
39. oculus-mc1.20.1-1.6.15a
40. pmmo-1.20.1-1.2.20
41. pmmo_farmers_compat-1.20.1-1.0.4
42. portablemobs-1.2.0-forge-mc1.20
43. seasonhud-forge-1.20.1-1.7.16
44. SereneSeasons-1.20.1-9.0.0.46
45. sophisticatedbackpacks-1.20.1-3.20.3.1034
46. sophisticatedcore-1.20.1-0.6.12.589
47. storageracks-1.20.1-1.7
48. supermartijn642corelib-1.1.17-forge-mc1.20.1
49. supplementaries-1.20-2.8.6
50. tombstone-1.20.1-8.6.5
51. towntalk-1.20.1-1.0.1
52. vintagedelight-0.0.11
53. worldedit-mod-7.2.15

### Logs

<script src="https://gist.github.com/Erwancdorcha/be791499dec5ad65142065b768654fdf.js"></script>

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
already fixed in newer version
