### ISSUE TITLE
Version 1.1.521 bricked AI Pathing

### ISSUE THREAD

**Issue by Tuganace** [ldtteam/minecolonies#9866]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [X] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.20.1-1.1.521-BETA

### Structurize Version

1.20.1-1.0.712-BETA

### Current Behavior

Updated from minecolonies-1.20.1-1.1.515-BETA to 1.20.1-1.1.521-BETA, and the server we play on crashes at random from minecolony entity pathing errors, and every citizen in the city is walking 1-2 meters, stops, walks another 1-2 meters and continues like their pathing is lagging/bottlenecking.

### Expected Behavior

to do anything els but the current behavior

### Reproduction Steps

update from the version I did, get a colony size of 39 people maybe.

### Logs

https://gist.github.com/Tuganace/14c9b12fb36d7c36ad4461a72f9c7de0

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by someaddons** [comment]
fixed in 523-BETA
