### ISSUE TITLE
Problème avec l'IA

### ISSUE THREAD

**Issue by Loflane** [ldtteam/minecolonies#9867]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.20.1

### MineColonies Version

1.1.521-BETA

### Structurize Version

1.0.718-BETA

### Related Mods and their Versions

Domum Ornamentum (1.20.1-1.0.181-BETA) 
Forge (47.2.21)

### Reproduction Steps

Mon IA a rencontré un problème ! Veuillez localiser le fichier latest.log et l'envoyer aux auteurs de MineColonies avec ce message.
![20240324_183508](https://github.com/ldtteam/minecolonies/assets/164783851/b2925ffe-bda7-4bb3-8696-268c4c13a6ba)

### Logs

https://gist.github.com/Loflane/7f9dd06c64cfe2a514ab933a951ec80e#file-gistfile1-txt

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
fixed
