### ISSUE TITLE
[BUG] Builders Stuck in BUILDING_STEP State and Unable to Finish Builds

### ISSUE THREAD

**Issue by YumatanGames** [ldtteam/minecolonies#9868]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.20.1-1.1.525-BETA

### Structurize Version

1.20.1-1.0.718-BETA

### Related Mods and their Versions

Domum Ornamentum: 1.20.1-1.0.181-BETA
Forge Version: 47.2.21

### Current Behavior

Several users have reported builders becoming stuck in a BUILDING_STEP state, causing them to loop in their actions and be unable to complete tasks such as building or upgrading structures. This issue appears to happen randomly and affects different types of buildings. Various attempted fixes include recalling workers, firing and rehiring, clearing inventories, and canceling and reissuing build requests, none of which have permanently resolved the problem.

### Expected Behavior

Builders should complete their assigned tasks without getting stuck in a loop, successfully build and upgrade structures, and react appropriately to recalls and other commands.

### Reproduction Steps

The specific steps to reproduce the bug are unclear, but it began occurring after updating the following mods:

MineColonies to version 1.1.525-BETA
Domum Ornamentum to version 1.0.181-BETA
Structurize to version 1.0.718-BETA

### Logs

https://pastebin.com/h9Na7Cnw

### Anything else?

YouTube video showcasing the issue: https://youtu.be/XSVLuhM83yU

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
It has been found out that downgrading to 1.1.515 helps with this, so this broke somewhere in those versions

**Comment by Knaxia** [comment]
Same issue here. My only solution was to manually push my builder inside the building and trap them in and they would finish, but it's annoying to do each time.

It seems on upgrades, it happens the moment they're done placing their blocks, and they're on the stage of clearing out old blocks. I just had the same issue on university and restaurant rank 1 to 2 in Caledonian Style.

As said above, trapping them inside solves the issue, at least for the building, but it's hard to constantly push them in a good spot.

**Comment by alfonsan** [comment]
Same issue in 2 of my worlds, one is single player, it's not a multiplayer only thing.

In the video the worker is shown performing actions with the hoe, and that might be missleading. In my servers, the worker is just walking back and forth in a loop, his inventory doesn't change, the build doesn't change, its not an invisible underground thing, neither a loooong range thing, he is stuck in that pathing loop.

**Comment by Knaxia** [comment]
So far so good on my side now. 

Running on 1.20.1-1.1.530 since the start of the evening and haven't had any issues with multiple builds and upgrades.
