### ISSUE TITLE
[BUG] banned user reported issue.

### ISSUE THREAD

**Issue by Moobien** [ldtteam/minecolonies#9870]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [X] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

n/a

### Structurize Version

n/a

### Related Mods and their Versions

n/a

### Current Behavior

a user, who has since been banned from discord reported that they were able to have functional buildings built out of their scans folder.

### Expected Behavior

functional buildings should not be functional if built from the scans folder.

### Reproduction Steps

they CLAIMED that they just had the required functional blocks, scanned them and then had a builder build them.

### Logs

n/a

### Anything else?

user got argumentative and was banned before more information could be obtained.

**Comment by Moobien** [comment]
their 'friend' joined and posted this. https://discord.com/channels/139070364159311872/1003402520846139533/1222030148262559785

**Comment by Talyda** [comment]
Honestly, we were trying to get more information out of them when they started cussing me out cos I asked them not to cuss =P
It *sounded* like what they were doing was an unintended bug - but it was so hard to get anything out of them. tried with their friend that joined after they were banned too, but didn't really get anywhere with them either. But I think they were just scanning in hutblocks and necessary blocks, and using them as buildings directly out of their scans folder

**Comment by Thodor12** [comment]
Not a bug

**Comment by Moobien** [comment]
> Not a bug

given that Ray had said that styles have to be in a style pack and functional buildings cant be built from a scans folder when he did the rework how can this not be a bug? for MONTHS now we have been telling players that functional buildings need to be in a style pack based on what I just listed it means we have been giving incorrect information. functional buildings should NOT be usable when built from a scans folder.

**Comment by Moobien** [comment]
I would like @Raycoms to comment on this.

**Comment by Thodor12** [comment]
The local scans directory *is* a style pack technically. In single-player any client schematic is automatically a server schematic, which makes them usable.

**Comment by Raycoms** [comment]
This is fine in singleplayer. This is not possible on a server. Yes

**Comment by Moobien** [comment]
> The local scans directory _is_ a style pack technically. In single-player any client schematic is automatically a server schematic, which makes them usable.

yes but when Ray redid the build tool he explicitly stated that functional buildings will not be functional if built from the scans folder. and the impression I got was that it was working on a server.

**Comment by Thodor12** [comment]
> This is fine in singleplayer. This is not possible on a server. Yes

Assuming structurize has allowplayerschematics on, which is true by default

**Comment by Raycoms** [comment]
> > This is fine in singleplayer. This is not possible on a server. Yes
> 
> Assuming structurize has allowplayerschematics on, which is true by default

Independent of the setting. You can't build functional buildings on a server from your personal folder without uploading them on a server.

**Comment by Moobien** [comment]
but we have been telling people since the rework that they have to be in a valid style pack in order to be used and cannot be used from the scans folder, based on what Ray had initially told us.

**Comment by Raycoms** [comment]
> but we have been telling people since the rework that they have to be in a valid style pack in order to be used and cannot be used from the scans folder, based on what Ray had initially told us.

That's the correct setup. But on the singleplayer the other thing theoretically also works

**Comment by Moobien** [comment]
ok so we have been giving incorrect information for months.

**Comment by Raycoms** [comment]
> ok so we have been giving incorrect information for months.

No, just because this isn't a bug in singleplayer, doesn't mean that we shouldn't tell people to make a proper pack and not build it from the scan folder.

**Comment by Moobien** [comment]
> > ok so we have been giving incorrect information for months.
> 
> No, just because this isn't a bug in singleplayer, doesn't mean that we shouldn't tell people to make a proper pack and not build it from the scan folder.

yes but we were being insulted and called liars because we were stating what we knew, and turns out we were wrong.

**Comment by Raycoms** [comment]
The answer remains. Make a proper pack for regular play. Anything else won't be supported. Any other setting is way too adhoc

**Comment by Moobien** [comment]
and we still get called liars for saying to do this.

**Comment by Raycoms** [comment]
Well, then let a mod deal with this and kick them if necessary.

**Comment by Moobien** [comment]
that is what shindria had to do...twice.
