### ISSUE TITLE
[BUG] My AI has run into an issue! Please locathe the lates log and send it to the MineColonies authors

### ISSUE THREAD

**Issue by ELThorbo** [ldtteam/minecolonies#9875]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.20.1

### MineColonies Version

WinterColonies-1.8

### Structurize Version

WinterColonies-1.8

### Logs

https://pastebin.com/vYjy7Qp0

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Please update the mod, will roll out modpack update "soonish"

**Comment by Cklarkus** [comment]
> Please update the mod, will roll out modpack update "soonish"

What is the stable version now after 629?
