### ISSUE TITLE
[BUG] Forester's Hut Block Disappears Instead of Moving to Inventory on Pick Up

### ISSUE THREAD

**Issue by YumatanGames** [ldtteam/minecolonies#9876]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.20.1-1.1.530-BETA

### Structurize Version

1.20.1-1.0.718-BETA

### Related Mods and their Versions

1. Forge Version: 1.20.1-47.2.21
2. Domum Ornamentum Version: 1.20.1-1.0.184-BETA
3. BlockUI Version: 1.20.1-1.0.151-BETA

### Current Behavior

After using the deconstruct option on the Forester's Hut and then selecting the "pick up" option to relocate it, the hut block did not appear in my inventory and instead disappeared. Items from the hut's inventory were dropped at the location. The server log indicates the hut block was removed, which seems to imply it was deleted by the game:
`[28.03 08:03:02] [Server] [Server thread/INFO] [minecolonies/]: Colony 1 - removed AbstractBuilding BlockPos{x=457, y=68, z=-590} of type forester`

### Expected Behavior

The Forester's Hut block should have been transferred to my inventory upon using the "pick up" button, allowing for the relocation of the hut and preservation of its level.

### Reproduction Steps

These was the steps I've took and how the issue happened to me:

1. Direct the builder to deconstruct the Forester's Hut and wait for them to finish the process.
2. Click the "pick up" button to move the building.
3. Hut block does not appear in the player's inventory and instead disappears.

### Logs

https://pastebin.com/micdanxR

### Anything else?

During the time of the issue, the assigned Forester was present but not actively working. The Forester picked up the items dropped from the hut's inventory after the block disappeared. I checked to ensure that the hut block was not mistakenly moved to the Forester's or the Builder's inventory. I even checked the Warehouse and Builder's Hut Inventory to see if it wasn't there by any chance.
 

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Did a checkup on this and I could not reproduce this. Even if player inventory is full. I believe some other mod must interfere and alter the player inventory in a weird fashion then. Might've ended up in a backup or curios or whatever slot.
