### ISSUE TITLE
[BUG] Quest issue: Cookies for the kids

### ISSUE THREAD

**Issue by kezmodius** [ldtteam/minecolonies#9883]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

minecolonies-1.20.1-1.1.533-BETA

### Structurize Version

structurize-1.20.1-1.0.718-BETA

### Related Mods and their Versions

On Cavecolonies server

### Current Behavior

Quest issue: if the child grows up before you complete the cookie quest you can't track them and the name no longer shows and the baker has no more interaction so they won't tell you the name again. I did find them and the quest was completable.
I had hired them (the grown child) before I saw the baker had a quest. 

### Expected Behavior

Since the quest is still completable I would hope to still know which citizen wants cookies and still be able to track them.

### Reproduction Steps

Trigger quest by having a child. Child grows up while quest is available.

### Logs

Don't have one

### Anything else?

It may work better as a quest to have the cookies be for a present? Because then it doesn't matter if they are child or adult. 
![2024-04-02_12 42 48](https://github.com/ldtteam/minecolonies/assets/120763436/f37394b9-56aa-44db-bbe8-8d62bbce63f8)

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
should be solved
