### ISSUE TITLE
[BUG] Visitors have stopped wandering

### ISSUE THREAD

**Issue by kezmodius** [ldtteam/minecolonies#9884]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [X] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

minecolonies-1.20.1-1.1.534-BETA

### Structurize Version

structurize-1.20.1-1.0.718-BETA

### Related Mods and their Versions

Forge 47.2.0
BlockUI - blockui-1.20.1-1.0.151-BETA.jar
Domum Ornamentum - domum_ornamentum-1.20.1-1.0.184-BETA-universal.jar
Jade 🔍- Jade-1.20.1-forge-11.8.0.jar
JadeColonies - JadeColonies-1.20.1-1.4.2.jar
JourneyMap - journeymap-1.20.1-5.9.20-forge.jar
Just Enough Items (JEI) - jei-1.20.1-forge-15.3.0.4.jar
MineColonies - minecolonies-1.20.1-1.1.534-BETA.jar
Multi-Piston - multipiston-1.20-1.2.43-RELEASE.jar
Structurize - structurize-1.20.1-1.0.718-BETA.jar
Stylecolonies - stylecolonies-1.3.2.jar
TownTalk - towntalk-1.20.1-1.0.1.jar

### Current Behavior

Visitors are standing still for a long time. They will move a few steps if you bump them or if they bump each other but then they stand still again.

### Expected Behavior

Visitors to wander about, like they used to before.

### Reproduction Steps

On Cavecolonies it started after the last update. On SP I tested with the modpack above. Settled an abandoned colony and pasted in a level 3 tavern. Visitors that spawned in would o it almost immediately.

### Logs

https://gist.github.com/kezmodius/dffe0c8a0487986d7c87ec088962695d

### Anything else?

Also happening on Cavecolonies server and I've reported it here: https://discord.com/channels/472875599422291968/486940969737125922/1224269977595543622

On observing the visitors they still move from different seated positions. I think that when they are standing dead still is the 'wandering' phase of their animation but it's not working as it used to. 

Other reports:
https://discord.com/channels/139070364159311872/1125094832143077456/1224624297201500221
https://discord.com/channels/139070364159311872/1125094832143077456/1224380469118767115
https://discord.com/channels/139070364159311872/1125094832143077456/1223674456128487464

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by someaddons** [comment]
fixed
