### ISSUE TITLE
[BUG] Fishers ignore glass and try to fish through them

### ISSUE THREAD

**Issue by Wallbreaker93** [ldtteam/minecolonies#9890]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.1.534-BETA

### Structurize Version

1.0.718-BETA

### Current Behavior

Fisher runs into wall of glass blocks and tries to fish throgh them
![Bild_2024-04-04_170106240](https://github.com/ldtteam/minecolonies/assets/129981249/29952e1c-fef2-4fa4-a96d-359223367496)

### Expected Behavior

Fisher should fish in water next to them

### Reproduction Steps

1. Create Colony using Underwater Theme
2. Build Fisher
3. Assign Fisher
4. Fisher will try to fish through glass

### Logs

none needed

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by batuhanbjkbatuhan** [comment]
_Construction blueprints remain and do not go away. How do I reset the construction tool?_

**Comment by MotionlessTrain** [comment]
> __Construction plans remaining and are not losting. How do I reset the construction tool?__

Please don't use a completely unrelated issue for this. You can open the interface of the build tool by right clicking and press the "X" button, as described on the [wiki](https://minecolonies.com/wiki/items/build_tool)

**Comment by batuhanbjkbatuhan** [comment]
> > **İnşaat planları ortada kaldı ve kaybolmuyor. İnşaat aletini nasıl sıfırlarım?**
> 
> Lütfen bunun için tamamen kalmasız bir konuyu kullanmayın. Oluşturma aracının tarifesini [wiki'de](https://minecolonies.com/wiki/items/build_tool) açıklandığı gibi sağ açma "X" düğmesine tıklayarak açabilirsiniz.[](https://minecolonies.com/wiki/items/build_tool)


I'm not saying that
I mean it stays when I press "x"

**Comment by batuhanbjkbatuhan** [comment]
When I press the x key it remains as a ghost image

**Comment by MotionlessTrain** [comment]
Please give more information on [discord](https://discord.minecolonies.com) or rather open an issue on [structurize's issue tracker](https://github.com/ldtteam/Structurize/issues). The issue about fishers trying to fish through glass is not related to build tool previews at all
