### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by kusyukin** [ldtteam/minecolonies#9905]

**Comment by Raycoms** [comment]
The miner will always dig down until bedrock (depending on the building level) before digging sideways. You can alter the depth setting to make them stay on the same level for longer.

**Comment by arenacreatoru** [comment]
The first mine has dug to level 16 and does not dig below, because there is a huge cave below.  He breaks the cobblestone blocks every time and puts them back up. The level -1 is set in the settings

**Comment by arenacreatoru** [comment]
That's it, it worked out! Thank you very much. Please leave some clarifications in the game somewhere so that fewer people will face a similar problem!!!
