### ISSUE TITLE
[Incompatibility] 1.20.1 Neo 47.1.104 Minecolonies UUID completely taken over by Duplicate Entity UUID Fix 

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [ldtteam/minecolonies#9909]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.20.1-1.1.550 Beta

### Structurize Version

structurize-1.20.1-1.0.725-BETA.jar

### Related Mods and their Versions

deuf-1.20.1-1.3.jar

### Current Behavior

After warping back to colony on server UUID suddenly started to constantly reassign Minecolonist

### Expected Behavior

That warping back does not reassign ids. Causing recall and to fail and villagers to stand in place.

### Reproduction Steps

Have a server; play on it have DEUF; eventually it breaks.

### Logs

https://mclo.gs/FOdZYuP

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.
Asked by Mirality to make a report.
![Discord_7wzZzShowm 1](https://github.com/ldtteam/minecolonies/assets/10351221/5032b916-9384-4d0e-83c8-b4486b9e8f2f)

**Comment by someaddons** [comment]
should be reported to the duplicate fix mod:

Instead of skipping entities with the same uuid's it assigns a new ID and keeps both entities, effectively duplicating a variety of entities, not just ours (which sometimes use the uuid to prevent a duplicate entity on chunkload, as we also manually respawn them)
https://github.com/CAS-ual-TY/DuplicateEntityUUIDFix/blob/1.20.1/src/main/java/de/cas_ual_ty/deuf/DEUF.java

**Comment by Knaxia** [comment]
Mine had nothing to do with incompatibility, I don't use Neoforge nor that DEUF addon which I never heard about, so I'm unsure why mine was closed/merged with this one.

**Comment by someaddons** [comment]
fixed^^
