### ISSUE TITLE
Citizens not working in unloaded chunks

### ISSUE THREAD

**Issue by ghost** [ldtteam/minecolonies#991]
### Minecolonies version

version 0.7.848 (minecraft 1.10.2)

### Expected behavior

- Wherever you are in the world, your citizens will still be loaded so that they can accomplish their tasks.

### Actual behaviour

- Chunks, where citizens are, are not loaded. This causes work to be delayed until you get inside their range of work.

**Comment by Wissi** [comment]
Well it's not actually an Issue. If it's meant to be a "feature request" then please add it to the title.

**Comment by marchermans** [comment]
This is actually not possible.
Towns can get very large. Which would mean that we would need to load very high amount of chunks and if the Citizen wanders off into a unloaded chunk he would just stop.

This is just how MC works. Nothing we can do about it.

**Comment by ghost** [comment]
That's why you add config options. Besides, I have a mod installed that loads chunks in a selected radius. The mod itself is buggy, but it loads over 100 chunks and doesn't lag my minecraft. Meanwhile, if I set my render distance to 8, I get very laggy. If each citizen loaded the one chunk they were in, this would not create much lag (and make my minecraft a bit smoother in my case). Your computer might have a better graphics card than RAM, which is why you did not think it was possible. For others it's the other way around, making this mod much more functionable and enjoyable. Before you close this thread again I'd like to either have another developer look at this or for you to reconsider based on my experience with chunk loading.

**Comment by ghost** [comment]
@OrionDevelopment @Kostronor

**Comment by Raycoms** [comment]
Just increase the amount of chunks loaded around you so while you're in the
colony citizens will stay loaded.

2017-05-15 12:19 GMT-03:00 ert67dy7 <notifications@github.com>:

**Comment by ghost** [comment]
"...it loads over 100 chunks and doesn't lag my minecraft. Meanwhile, if I set my render distance to 8, I get very laggy". Rendering chunk data is different than rendering chunk graphics (and much laggier). @Raycoms

**Comment by ghost** [comment]
And by the way the other (buggy) mod I'm using the load the chunks is called chickenchunks. It is meant for servers but still works on single player.

**Comment by Raycoms** [comment]
just set world spawn to your colony, it should stay automatically loaded


2017-05-15 12:46 GMT-03:00 ert67dy7 <notifications@github.com>:

**Comment by ghost** [comment]
Do you know how large that loading radius is? @Raycoms

**Comment by Raycoms** [comment]
https://www.google.com.br/search?q=minecraft+spawn+chunk+size&oq=minecraft+spawn+chun+sie&aqs=chrome.1.69i57j0j69i64.13656j0j7&sourceid=chrome&ie=UTF-8

2017-05-15 12:51 GMT-03:00 ert67dy7 <notifications@github.com>:
