### ISSUE TITLE
[BUG] Fisher "water not found" message still says 7x7

### ISSUE THREAD

**Issue by MiriamAlter** [ldtteam/minecolonies#9910]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.20.1-1.1.530-BETA

### Structurize Version

1.20.1-1.0.708-RELEASE

### Related Mods and their Versions

MineColonies Dimensional Adventure modpack

### Current Behavior

If a fisher colonist does not have a suitable water source near them, their alert message says they need a 7x7 water source in order to do their job properly.
![image](https://github.com/ldtteam/minecolonies/assets/46386049/a0b30e5a-3ed3-4efc-8d9c-5053f26a94ef)

### Expected Behavior

The alert message should say they need a 6x5 water source.

### Reproduction Steps

1. Build a fisher hut
2. Remove any nearby water sources, including those in the hut zone
3. Hire a fisher
4. Wait for the alert message

### Logs

https://gist.github.com/MiriamAlter/eff9f9a9344932bce6901d57e3a97cee

### Anything else?

Requested by Moobien

**Comment by Raycoms** [comment]
That's actually intentional, while it accepts less, it works better with more
