### ISSUE TITLE
[BUG] Colonists become stuck in Create seats.

### ISSUE THREAD

**Issue by kezmodius** [ldtteam/minecolonies#9916]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

minecolonies-1.20.1-1.1.550-BETA

### Structurize Version

structurize-1.20.1-1.0.718-BETA

### Related Mods and their Versions

Forge 47.2.20

### Current Behavior

Colonists (within the Fairytale style) are getting stuck in the Create seats and will remain there bobbing up and down until recalled.
I observed the builder, after placing the seats, kept getting trapped on them. I watched her and the trapping occurred when she simply walked over the seat. She did drop down onto it from the countertop and got stuck then too.

### Expected Behavior

That they can get out of the seats when they 'choose'. Or can walk over them without getting stuck.

### Reproduction Steps

(My experience) Build Level One Tavern - Fairytale style - with a builder.
When the builder walks over the seat they get stuck/trapped on the seat.

### Logs

https://gist.github.com/kezmodius/f80356015cf549edeb00b6f350c4712c

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by kezmodius** [comment]
Oops. Hit enter too soon sorry.
Server log: https://gist.github.com/kezmodius/aa440d251e148790463b0426253128ad
Above log was client.

Also reported by others on discord:
https://discord.com/channels/139070364159311872/1125094832143077456/1228489618064801884
https://discord.com/channels/139070364159311872/724810039281451028/1228536599910809710 (video)

**Comment by NalyKalZul** [comment]
also playing a 1.20.1 pack from a friend, also involved minecolony and the dreaded create seats.
i have to baby sit a builder over several ingame days just to stop them from being permanently trapped during builds.

the minecolony guards go into the restaurant but never get out.

create seating, should not be this powerful.

so we found one npc behavior fix,
but it required us to use the easy villager mod, to fill all seats with dummy villagers.
![2024-04-29_00 55 25](https://github.com/ldtteam/minecolonies/assets/12812081/2b4f7f00-e6f3-4bfc-96e5-88d22b00838a)

**Comment by Bizzmuth** [comment]
so after some testing i found that you can remove the stools and the citizens will just sit in mid air/on the ground.
![image](https://github.com/ldtteam/minecolonies/assets/90510166/ef718e01-b99a-49c6-968f-380742ad4465)

i then replaced the seats with stools from "Quark" which they sat on happily.
![image](https://github.com/ldtteam/minecolonies/assets/90510166/639dfa87-5cac-45b8-9e8b-0cb0c1b8e1f6)

You can replace the stools as soon as the builder has placed them and moved on from the looks of it. this will help with the builder not getting stuck during building phase
