### ISSUE TITLE
[BUG] Colonists Happiness does not return to normal after a Death or Injury. Colony quest participation also always in the red.

### ISSUE THREAD

**Issue by Knaxia** [ldtteam/minecolonies#9921]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

minecolonies-1.20.1-1.1.550-BETA

### Structurize Version

structurize-1.20.1-1.0.725-BETA

### Related Mods and their Versions

1.20.1-forge-47.2.23

blockui-1.20.1-1.0.151-BETA.jar
domum_ornamentum-1.20.1-1.0.184-BETA-universal.jar
jei-1.20.1-forge-15.3.0.4
journeymap-1.20.1-5.9.20-forge.jar
multipiston-1.20-1.2.43-RELEASE

### Current Behavior

If a colonist had an injury, or if someone has died, their meter in their happiness will forever remain in the red and will never return to normal, even after weeks of in-game days. This also affect the global colony happiness, which will also remain in the red. Citizen who have never been injured in the past, or were born after the last death, will not be affected until it happens again.

As per mentioned in the wiki:
-All citizens become slightly less happy for the next day when injured.
-Each time a citizen (other than a Guard) dies, other citizens will mourn the next day and be less happy for the next three days.

This has been going on since the start of my colony a while ago. My last citizen death was very early this week, when I reported the undertaker bug 5 days ago. Plenty of time has passed since that death as I've been playing 2-3 hours each evening since then, people still are in the red for death. 

Same with injuries. All my people who once got injured mostly due to the pathing issues earlier on, are still in the red, even people who have been sitting inside a building for weeks, such as researchers, students, teacher and such. my whole colony is on near flat land, no major holes or gap to fall, all their houses are close, the place is lit up and no mobs near by. I've even followed some NPCs a few days around, and they still complain they got injured.

Quest participation is also always red. I've completed all the quests each time I saw them, my quest logs shows 2/2 on both zombies (3 and 10) quests, I've only ever got 1 hungry courier quest (shows 1/10). I know the 2nd number is the max amount of those quests you can complete as when I did the first zombie quest, it showed 1/2 ,then 2/2 the second time.

So in overall, the overall happiness is fine, except that those 3 are always red, no matter what, for the colony.

### Expected Behavior

-Injured colonists happiness slowly returns to normal in the days after the event
-Colonists happiness slowly returns to normal after 3 days of another colonist's death (non-guard)
-Quest completion happiness actually reflects the amount of completed quests.

### Reproduction Steps

-Have someone die, or injure one of your colonist
-Wait for many (3+) days, 
-Check their happiness, it will be stuck in the red for their respective category.

### Logs

No logs related

### Anything else?

![2024-04-14_11 11 58](https://github.com/ldtteam/minecolonies/assets/73440864/f488b2e8-2e74-46cd-92ae-b42767be17c4)

![2024-04-14_11 13 00](https://github.com/ldtteam/minecolonies/assets/73440864/2ffff96d-84db-4a1d-a04e-946abf2e0f7c)

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
solved

**Comment by Nchard** [comment]
I am still having this issue on 1.20.1-1.1.647
