### ISSUE TITLE
[BUG] <pirate and drowned pirate raiders not spawning when trying to spawn them in with commands or spawning in as barbarians>

### ISSUE THREAD

**Issue by AltoCLumobius** [ldtteam/minecolonies#9922]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.20.1-1.1.561-BETA

### Structurize Version

1.20.1-1.0.725-BETA

### Related Mods and their Versions

1. 47.2.0
2. blockui-1.20.1-1.0.151-BETA
3. domum_ornamentum-1.20.1-1.0.184-BETA-universal
4. structurize-1.20.1-1.0.725-BETA

### Current Behavior

When trying to trigger a pirate raid or a drowned pirate raid, they either don't spawn in or spawn in as barbarians.
I'm also fairly sure my colony is near a large body of water.

### Expected Behavior

Pirates

I expected them to spawn in.

Drowned Pirates

I expected them to spawn in.

### Reproduction Steps

Pirates

Type in "/minecolonies colony raid now [ID] pirate_raid"

Drowned Pirates

Type in "/minecolonies colony raid now [ID] drowned_ pirate_raid

### Logs

Don't know how to do that. Sorry. :(

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
If it can't find a suitable location it falls back to barbarians
