### ISSUE TITLE
[BUG] Undertaker doesn't go to Mystical Site or do any other visits if they have nothing to do.

### ISSUE THREAD

**Issue by Knaxia** [ldtteam/minecolonies#9929]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [X] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

minecolonies-1.20.1-1.1.563-RELEASE

### Structurize Version

structurize-1.20.1-1.0.730-BETA

### Related Mods and their Versions

forge-1.20.1-47.2.30
blockui-1.20.1-1.0.155-BETA
jei-1.20.1-forge-15.3.0.4
journeymap-1.20.1-5.9.20-forge

### Current Behavior

When the undertaker isn't currently on a job, so idle at the graveyard, they will not visit the Mystical Site or other citizen to raise their mana stats. They will just wander around like any other idle workers.

### Expected Behavior

They should go to the Mystical site and do their visits when not working on a dead citizen grave, raising their mana stat.

### Reproduction Steps

-Have both a graveyard and Mystical site built and an active undertaker. (Any level)
-check the initial stats of your undertaker and then wait and see, the undertaker will just wander around their graveyard all day and their stats won't move.

### Logs

None Required

### Anything else?

Someone asked about it on discord yesterday, which made me realize my undertaker was doing the same thing. I do recall them behaving differently in a previous minecolonies gameplay (in 1.19) and they did go around and visit the Mystical site. I'm currently playing on a dedicated server, but with a discussion also including Moobien, I went to test in a single player world, in creative, to see if the issue was still present.

I made a full level 5 test colony, including : town hall, tavern, 2 houses, graveyard, Mystical site, restaurant, warehouse + courier, guard, university. I hired the undertaker and set all of their stats to 1, except intelligence to 40 to see if it would change.
-Tested without any researches at first : Still idle wander
-Did most of the graveyard researches except the totem of undying one : Same thing
-Fire / rehire / pause / restart  : Same thing
Each time I waited a few in game days, just watching them, they never went away except to go sleep or get food, their stats are still the same as when hired.

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
There was never a feature that made them level extra skills based on mystical site visits in the colony. Mystical sites extisting results in a few undertaker boni, but there is no code to wander there.

**Comment by MotionlessTrain** [comment]
That must be a myth, then. Not sure where that came from, but I believe it was common belief that they went there

**Comment by Knaxia** [comment]
The wiki clearly stated that they do. The cached / wayback archive (since wiki is down) does show:

"If no citizens have died recently, the Undertaker will visit the , the , and citizens' homes. Doing so will increase their Mana level."

That is not what they are doing at all right now, and I do remember seeing my undertaker back in 1.19.4 colony do it.

**Comment by Raycoms** [comment]
The AI code hasn't change in ages for the undertaker, so it's probably a myth that someone even ended up writing to the wiki xD They might've seen them doing the casual wandering which can lead to the mystical site.

**Comment by MotionlessTrain** [comment]
I guess #blame-raven for adding that to the wiki, when the graveyard pages were added 😄

**Comment by Knaxia** [comment]
I guess I was also crazy because I read that. I swear I already saw them around the Mystical site in the past...

I still have my 1.19.4 server saved, along with my 1.19.4 client and mods so I went to check and yea.. undertake just wanders around. 

Sorry for the false report!

**Comment by MotionlessTrain** [comment]
> Mystical sites extisting results in a few undertaker boni

In an attempt to collect the wiki, what types of bonuses do they get specifically?

**Comment by Raycoms** [comment]
higher resurrection chance
