### ISSUE TITLE
[BUG] <Builders AI ran into a problem>

### ISSUE THREAD

**Issue by Chill907Gaming** [ldtteam/minecolonies#9931]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [ ] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.20.1

### MineColonies Version

minecolonies-1.20.1-1.1.481-BETA.jar

### Structurize Version

structurize-1.20.1-1.0.699-BETA.jar

### Related Mods and their Versions

I am running version "6.1.0 Release" of the Valhelsia 6 mod-pack. If you'd like you can check [the Valhelsia 6](https://github.com/ValhelsiaTeam/Valhelsia-6) list for all versions of each mod, but I'm just reporting this in case someone sees an obvious flaw. I'm very thankful for the Minecolonies team. I will also let the Valhelsia staff know about the bug so they can update to the latest version of Minecolonies. :)

### Reproduction Steps

This issue happened suddenly and without explanation. The only cause I can see is increasing my minimum simulation distance using DynView. I changed the simulation distance over a week ago and the bug didn't happen until maybe yesterday or the day before. DynView changes the simulation distance dynamically based on server performance, and I never noticed this bug before I 
 increased the minimum simulation distance, so that's why I say it _might_ be the cause.

### Logs

https://gist.github.com/Chill907Gaming/3f80f2b4a883c0b9bbbb88039d2243b1

### Anything else?

Thank you for your hard work on the Minecolonies mod. It's one of my favorites. If you need me to do further testing I can, but like I said earlier I'm not the mod-pack creator so I will need to let the Valhelsia 6 mod-pack staff know about the bug and have them update the Minecolonies mod and their mod-pack so that all the players on my server run the same version.

I **could** check to see if updating the mod fixes the bug, but I'd have to make a duplicate of my MC server which is a huge hassle at the moment. I hope that you can find the cause from my attached logs.

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
Because you are on such an outdated version of the mod, you're probably going to find that it has already been fixed in the many versions since then =)

**Comment by Raycoms** [comment]
Please reopen if it persists on the newest

**Comment by Chill907Gaming** [comment]
I think I've solved the issue and found the cause of the bug. 

I switched my builders' "Construction Strategy" to "Inward Circle Height 2" and that appears to cause them to bug out. Switching them back to "Default" and cancelling their build-in-progress fixed it.
