### ISSUE TITLE
[BUG] Crash with Aether on develop environment.

### ISSUE THREAD

**Issue by gisellevonbingen** [ldtteam/minecolonies#9943]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19.2

### MineColonies Version

1.19.2-1.1.516-BETA

### Structurize Version

1.19.2-1.0.689-RELEASE

### Related Mods and their Versions

The Aether - 1.19.2-1.4.2-forge
https://www.curseforge.com/minecraft/mc-mods/aether/files/5302176

### Reproduction Steps

== Steps ==
1. Add Minecolonies and Aether dependencies at gradle like below settings.
2. Execute forge_client task to Run Minecraft.
3. Try create a new world.

== Settings ==
build.gradle
```Groovy
repositories {
	maven {
		name "MineColonies"
		url "https://ldtteam.jfrog.io/ldtteam/modding"
	}
	maven {
		name "CurseForge"
		url "https://www.cursemaven.com"
	}
}

dependencies {
	implementation fg.deobf("com.ldtteam:minecolonies:${minecolonies_version}")
	implementation fg.deobf("com.ldtteam:structurize:${structurize_version}")
	implementation fg.deobf("com.ldtteam:multipiston:${multipiston_version}")
	implementation fg.deobf("com.ldtteam:domum_ornamentum:${domumornamentum_version}:universal")
	implementation fg.deobf("com.ldtteam:blockui:${blockui_version}")
	implementation fg.deobf("curse.maven:aether-255308:${aether_file}")
}
```
gradle.properties
```Groovy
minecolonies_version=1.19.2-1.1.516-BETA
structurize_version=1.19.2-1.0.689-RELEASE
multipiston_version=1.19.2-1.2.25-ALPHA
domumornamentum_version=1.19-1.0.146-BETA
blockui_version=1.19.2-1.0.140-BETA
aether_file=5296999
```

### Logs

https://gist.github.com/gisellevonbingen/e963deb6aef5cbf24f9d4ec5f7959bbd

### Anything else?

As log showen, it because tried read config value before config system initialized.
Please see Aether's code what occurred Crash.
https://github.com/The-Aether-Team/The-Aether/blob/1.19.2-develop/src/main/java/com/aetherteam/aether/item/food/GummySwetItem.java#L86

Looking more further into the logs, can know it came from  Forge Config system.
![image](https://github.com/ldtteam/minecolonies/assets/44163945/e145adb4-575a-4a69-9632-e9c220bbcc01)
That check is not called in production environment. (only on Dev.)

There are any solution?

**Comment by Raycoms** [comment]
Nothing we can really do from our side here.

**Comment by gisellevonbingen** [comment]
ok i understand.
