### ISSUE TITLE
cook incessantly cooking mushrooms and unable to turn off as food 

### ISSUE THREAD

**Issue by anastasia590** [ldtteam/minecolonies#9944]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.20.1..1.1.567-beta-jar

### Structurize Version

1.20.1.1.0.731

### Related Mods and their Versions

vanilla plus cookbook 2.2.2
I am on cavecolonies server using the cavecolonies modpack 

### Current Behavior

![2024-05-08_07 31 39](https://github.com/ldtteam/minecolonies/assets/121142637/16e18f51-496b-444d-87b6-9c390fc2ff6b)
![2024-05-08_07 31 52](https://github.com/ldtteam/minecolonies/assets/121142637/a7ed9c69-7497-4154-8800-53a796cb9ed6)
![2024-05-08_07 31 59](https://github.com/ldtteam/minecolonies/assets/121142637/953bb711-df2e-4802-8c86-47d07dd8a5af)
the cook is cooking all the mushrooms, wasting fuel and preventing using mushrooms in recipes,  this has been going on since the restaurant was level 1 - that the cooked mushrooms are not on the list of foods to disable,  the restaurant is currently level 4 and most citizens will not eat cooked mushrooms which only satisfy one shank of hunger, so he's wasting fuel and tying up couriers delivering then sending it back to the warehouse after a while 

  While discussing this on discord  and getting screen shots he cooked up 22 mushrooms 
   I have noticed in the past also that several ingredients in pams recipes randomly seem to not be on the list of things you can disable,  that is pams roasted mushrooms , roasted garlic,   etc 
    

### Expected Behavior

I would expect the cook to have left the mushrooms alone because the assitant cook needed them for rabbit stew
I would expect to be able to turn off cooked mushroom in the food tab  so he would stop cooking them
I would expect a level 4 restaurant not to cook up low quality food but I do have 1 or 2 citizens in a new house that "might" eat it 
I wish I could expect him to only cook what I tell him to cook in the smelting recipes tab but that is not how it's supposed to work

### Reproduction Steps

come over to my restaurant and look 
Or put some mushrooms in your restaurant and see what happens 
set min stock of mushroom stew and see if your assistant cook is fast enough to make it 

### Logs

it's the cavecolonies server 

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
I was testing as I was reading the discord conversation, the cooked mushroom *do* appear at level 1 restaurant, and you can turn them off then, but once you get to a higher level restaurant, they are no longer on the list to be able to disable them.  So maybe the auto smelt recipes need to be disabled automatically once the restaurant is high enough level that they no longer will serve them?

*edits* Fresh level 5 restaurant, without having turned them off at level 1, and yeah, they are just cooking all the mushrooms, and no option to turn them off

To just test more things I then taught the assistant cook the cooked mushroom recipe, and requested some at post box, which she then cooked and had delivered.



Incidentally as part of testing it, (and I want to keep this separate to above!) I taught them rabbit stew, and nothing else, and the assistant cook filled all 5 furnaces with coal, but only cooked rabbit. Once the stack of rabbit was cooked, she started cooking potatoes in the same one furnace. Once the potatoes were cooked she used the same one furnace to cook the one mushroom I requested at the post box (I requested 1 first, then requested 15). Once the fuel ran out/expired from cooking the one, she then put the 15 in to cook. That seems very wasteful and not very good time management!  Minecolonies original style restaurant if that matters

**Comment by uecasm** [comment]
> So maybe the auto smelt recipes need to be disabled automatically once the restaurant is high enough level that they no longer will serve them?

Yep, that's the idea.  They're also _supposed_ to not cook anything that's required by an active recipe, but it sounds like that's not working as intended either.  Might be a timing issue.

**Comment by xElandriax** [comment]
This is also happening with popcorn - croptopia (corn), and raisins - croptopia (grapes) on a level 5 restaurant, IE they do not appear in the food list to disable them being produced/smelted by the cook who is still cooking them, despite not being eaten by the residents.
