### ISSUE TITLE
[feature request] new config options for villagers

### ISSUE THREAD

**Issue by Zygus42** [ldtteam/minecolonies#996]
v1.10.2

We would love to see options in the config to allow minecolonist villagers to:
(a) work in the rain
(b) work in the snow
(c) work during the night

This came to a head on our server as we were using Harvest Festival which adds seasons, and so we had long periods of rain + snow.  Personally I though it was very reasonable and even realistic, but had so many complaints, that I thought I'd ask here.

**Comment by Zygus42** [comment]
A friend suggested that this could be an upgrade option, to give them a building that allows them to work in rain, or else give them some kind of item, like a raincoat or old-timey oilskins.

**Comment by Raycoms** [comment]
currently all workers with level 5 huts work during the rain

2017-05-15 12:17 GMT-03:00 Zygus42 <notifications@github.com>:

**Comment by Zygus42** [comment]
Didn't know that, and that's cool, but in our current situation if the Builder doesn't work during rain + snow, would take a heck of a long time to get to lvl 5 huts.

**Comment by Asherslab** [comment]
I just made a PR for working during the rain (without having the working being level 5) i'll see what i can do about the night-time, but i'd highly suggest not having workers out at night (referring to upcoming update, in a few days)
