### ISSUE TITLE
[BUG] Crash when trying to set minimum stock when used with UntamedWilds

### ISSUE THREAD

**Issue by Robynstar** [ldtteam/minecolonies#9963]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.1.581-BETA

### Structurize Version

1.0.733-RELEASE

### Related Mods and their Versions

Forge Version 47.2.0
UntamedWilds [untamedwilds-1.20.1-4.0.4.jar](https://www.curseforge.com/minecraft/mc-mods/untamedwilds/files/4779746)

### Current Behavior

When using MineColonies with UntamedWilds if you try to set Minimum Stock in any building the game immediately crashes/closes.

### Expected Behavior

For it to let me set a minimum stock without crashing?

### Reproduction Steps

1. Install both MineColonies and Untamed Wilds
2. Build any building with the Minimum Stock tab
3. Click Add in the Minimum stock tab
4. Watch game close

### Logs

https://pastebin.com/Xd2qqGcU

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Report to untamed wilds
