### ISSUE TITLE
My AI has run into a problem .....

### ISSUE THREAD

**Issue by anastasia590** [ldtteam/minecolonies#9965]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.20.1

### MineColonies Version

1.1.583

### Structurize Version

1.0.733

### Reproduction Steps

click on my builder chloe barefoot to see why she won't build anything 

### Logs

https://gist.github.com/Ramtough2011/671e842df78c92f1f616b1d080cc61d8

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.
![9AB2E498-989B-499A-A014-FC71A3E0D16C](https://github.com/ldtteam/minecolonies/assets/121142637/475af159-b2ca-430d-956b-4b8a774ee9f6)

**Comment by anastasia590** [comment]
![2024-05-26_20 15 27](https://github.com/ldtteam/minecolonies/assets/121142637/ffae32fa-703c-46c2-ab24-2b451dcd1ae0)
clearly that was the wrong image attached the first time

**Comment by Raycoms** [comment]
Can you fire and then re-hire?

**Comment by Raycoms** [comment]
solved
