### ISSUE TITLE
[BUG] toms storage terminal dont work if cables are  involved

### ISSUE THREAD

**Issue by dhgameryt** [ldtteam/minecolonies#9968]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

minecolonies-1.20.1-1.1.585-BETA

### Structurize Version

structurize-1.20.1-1.0.733-RELEASE

### Related Mods and their Versions

1. toms_storage-1.20-1.6.6

### Current Behavior

terminal dont work when i use cables, only work if i place the terminal touching the townhall block or the connector, if i use cables and cables connectors terminal dont work (the mod work with other inventories, like chest, or racks, this only happen with the townhall block), refined storage works well

### Expected Behavior

that the terminal work with cables involved

### Reproduction Steps

place the inventory connetor touching townhall block, next place a cable, next place a cable connector and a terminal

### Logs

https://gist.github.com/dhgameryt/63ebe5af8d3e5df5ce43660805cc1fad

**Comment by someaddons** [comment]
please report this to toms storage mod instead
