### ISSUE TITLE
Crash on Start

### ISSUE THREAD

**Issue by Dabdad2** [ldtteam/minecolonies#9973]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.20.1

### MineColonies Version

1.1.530-BETA

### Structurize Version

1.1.708-RELEASE

### Logs

https://gist.github.com/Dabdad2/4099cd445bff348aa710c25502aa6579#file-latest-log

### Anything else?

I try and boot up the game and it imminently crashes, it doesn't even start loading, it's always straight back to the launcher, it's like it's being interfered or something, or like it can't finish the config files, I don't know what's happening

**Comment by Thodor12** [comment]
Insufficient log, this has nothing to do with Minecolonies.
