### ISSUE TITLE
[BUG] Shire style Warehouse, visitors keep suffocating themselves by sitting on a specific block.

### ISSUE THREAD

**Issue by AlkalinePineapples** [ldtteam/minecolonies#9977]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

minecolonies-1.20.1-1.1.581-BETA

### Structurize Version

structurize-1.20.1-1.0.733-RELEASE

### Related Mods and their Versions

1. Dorum Ornamentum Version: domum_ornamentum-1.20.1-1.0.184-BETA-universal

### Current Behavior

![2024-06-06_17 55 51](https://github.com/ldtteam/minecolonies/assets/138986467/b80f8f31-1808-4cac-a3bf-a23999085913)

Visitors keep sitting on this specific block in the warehouse, and suffocate inside the rack. I have removed the top rack to prevent them from dying, but this becomes a problem when I am upgarding the warehouse. The builder has to put the rack back, and the visitors will take the opportunity to ruin my colony's reputation.

![2024-06-06_18 01 33](https://github.com/ldtteam/minecolonies/assets/138986467/b89c84ba-bfbb-4190-acd3-2fbc845cabdc)

Even if I remove the plank block they usually sit on, they'll just sit on the block below it instead.

![2024-06-06_18 15 24](https://github.com/ldtteam/minecolonies/assets/138986467/85684ae6-5c8f-4ac5-b831-6d6163400981)

### Expected Behavior

Visitors should not sit on any block that isn't a stair block inside the Tavern.

### Reproduction Steps

1. Build a Tavern in the Shire style
2. Build a Warehouse in the Shire style

### Logs

https://pastebin.com/5BJN3iqn

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
please report in #5006 and @kedamono
