### ISSUE TITLE
I cannot move or look around when in build mode

### ISSUE THREAD

**Issue by Pyro-Rat** [ldtteam/minecolonies#9982]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.20.1

### Structurize Version

1.20.1

### Current Behavior

I cannot look around when in build modey camera locks and I can't move either

### Expected Behavior

Me being able to look around so I can actually place things

### Reproduction Steps

1. Build something
2. Camera locks

### Logs

N/A

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
esc, move around, right click to re-enter
