### ISSUE TITLE
[BUG] Stonemason unable to learn recipe

### ISSUE THREAD

**Issue by ProgFroz** [ldtteam/minecolonies#9985]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

minecolonies-1.20.1-1.1.563-RELEASE

### Structurize Version

structurize-1.20.1-1.0.733-RELEASE

### Current Behavior

The stone mason is somehow unable to learn the recipe for tools.

I tried the following:

- Stone Axe - Did not work
- Stone Pickaxe - Did not work
- Stone Bricks - Worked
- Sturdy Stone - Worked

It seems that is entirely related to tools.

### Expected Behavior

The stone mason should be able to learn recipes regarding tools.

### Reproduction Steps

1. Build Stone mason
2. Try to learn them the recipe for a stone tool

### Logs

https://pastebin.com/nqWQii8r

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
The blacksmith makes stone tools

It may be stated wrong in JEI
