### ISSUE TITLE
[BUG] independant pasted barracks towers functional

### ISSUE THREAD

**Issue by Moobien** [ldtteam/minecolonies#9987]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.1.591

### Structurize Version

1.0.736

### Current Behavior

cereative pasting an independant barracks tower allows hiring of guards

### Expected Behavior

expecting the tower to complain about not having a barracks

### Reproduction Steps

paste in any barracks tower
hire guards

### Logs

n/a

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Creative pasting bypasses any security checks. Tis fine
