### ISSUE TITLE
Architects cutter doesnt work with oak planks

### ISSUE THREAD

**Issue by Ihatemakingpasswords** [ldtteam/minecolonies#9988]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.20.1+1

### Structurize Version

1.20.1

### Related Mods and their Versions

using the current atm9 mod pack

### Current Behavior

trying to put oak planks in architects cutter. can not also red box in bottom slot 
![image_2024-06-13_225203299](https://github.com/ldtteam/minecolonies/assets/172201203/978e4515-a75f-4289-b642-56356aa4f10b)

### Expected Behavior

planks should go in and make framed cobblestone or other items 

### Reproduction Steps

make architects cutter put oak planks in cutter

### Logs

idk how

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
Did you just post on discord for this? I answered you there, it isn't a bug

**Comment by Ihatemakingpasswords** [comment]
yeah you did thank you!
