### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by ZEUS-102** [ldtteam/minecolonies#9993]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [ ] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [ ] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.20.1

### MineColonies Version

minecolonies-1.20.1-1.1.586-BETA.jar

### Structurize Version

structurize-1.20.1-1.0.736-BETA.jar

### Related Mods and their Versions

If I understood correctly what should be written then:MineColonies_Compatibility-1.20.1-2.12.jar , MineColonies_Tweaks-1.20.1-2.21.jar

### Reproduction Steps

I right-click on the archer I hired using the first level barracks tower, after which he tells me that he has a problem with the AI ​​and I need to send the latest.log to the authors of the mod along with this message

### Logs

<script src="https://gist.github.com/ZEUS-102/7768a38760a34c7f1702fed7f06ea6b8.js"></script>

### Anything else?

[latest.log](https://github.com/user-attachments/files/15904316/latest.log)
![image](https://github.com/ldtteam/minecolonies/assets/173296205/5e8fa2bc-bfa0-4e7d-a3c6-5e8a662d4663)
and if it helps, I'm playing on a build from curseforge called industrial village IV-1.20-1.5.zip

**Comment by Thodor12** [comment]
We do not support any usage of Minecolonies_Tweaks as they modify things using mixins. If you're running into any bugs, go ask them.
