### ISSUE TITLE
[BUG] Colonists keep not swimming to surface

### ISSUE THREAD

**Issue by AprilDerg** [ldtteam/minecolonies#9999]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.1.593-BETA

### Structurize Version

1.0.736-BETA

### Related Mods and their Versions

Industrial Village modpack - IV-1.20-1.5
Forge - 47.2.14

### Current Behavior

At some occasions, a colonist might path across water, and for some reason would not bob up and stay above water, causing them to drown. This usually happens to a builder that tries to go through canals, and walks across the bottom of the (4 block deep) water, but part of my colony extends to the other side of a river, with a college being on the other side, and i have had multiple workers for that building try to path across the water and die in the middle of the river. In the attached screenshot, I have placed a yellow wool on the exact coordinates given by the colonist death message, with nothing else changed.
![2024-06-22_10 31 40](https://github.com/ldtteam/minecolonies/assets/42842686/0b209cf0-82b7-43f4-a5d0-141dce33321b)

### Expected Behavior

The colonists should bob up on top of the water if there is enough space for them to do so, as stated in the wiki. As seen in the screenshot from the current behavior, they should also path across the wooden bridge, as going across the water is by far a much longer route to the houses.

### Reproduction Steps

1. Build a colony on one side of a river deep enough to drown in
2. build a building on the other side of the river (not an outpost, as they have patrolling workers)
3.(optional) build a bridge across the two sides
4. assign a worker to the building on the other side of the river
5. wait multiple in-game days until the issue occurs
Additional: seed of the world in which the issue occurs (bonus chest:0; generate features:1): -2111105504851395317 (in case this river is special somehow)

### Logs

https://gist.github.com/AprilDerg/c42fb11a99df86b4b4e26b185f3742ec

### Anything else?

The modpack I am using is Industrial Revolution and is publicly available on curseforge
This issue does not occur every time, but often enough to be a problem
Possibly an issue with elevation
only vanilla blocks used in bridge

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by AprilDerg** [comment]
Small update: apparently patrolling guards can drown too

**Comment by Raycoms** [comment]
Do they all drown at the same location?

**Comment by AprilDerg** [comment]
No, they are all in different places, whether it be in the river i mentioned or a small constructed canal. I have seen them drown in multiple depths, as well, even just below the surface.

**Comment by kezmodius** [comment]
Server was on 1.1.586. So many drowning deaths. Many Guards, Many Fishers and Builder. From the little I observed they are either pathfinding to a spot they cannot get up onto land and bob there until death, or they stay where they fell in the water and not pathfind to an accessible shore, instead trying to get back up a two block high wall. Shindria asked someone else to add their experience so I thought I'd add mine.

**Comment by Talyda** [comment]
Yeah, there's definitely been an increase in the amount of people reporting drowning citizens of all kinds in the past week or so

**Comment by Raycoms** [comment]
Any good way to reproduce this?

**Comment by kezmodius** [comment]
The server is updating tomorrow so I can do some checks on whatever version they update to.
Try using the Fairytale fisher.

**Comment by AprilDerg** [comment]
Had another case of drowning, hadn't had then in a while since i installed some waypoints to help people path, but patrolling guards still drown i guess. (Again marked in yellow wool)

![2024-07-02_21 49 08](https://github.com/ldtteam/minecolonies/assets/42842686/e4da5ba2-d409-4892-a062-06757c688748)

**Comment by AprilDerg** [comment]
Wanted to add two things: 
1. the yellow wool is not only at the x and z of where they drowned, but at the y as well, according to the death message.
2. I saw this bug in action a bit back, and the citizen refuses to bob. Even if the area around where they are is clear, they do not bob at all and just sit at the bottom of the water. Before i thought the slabs from the fisher were causing the problem since that project alone took like 3 builders to finish, but now they're just drowning wherever.

**Comment by fulmoonless** [comment]
In certain situations, the Pathing System will generate a path along underwater blocks, causing Colonists to drown.
I think this is why we occasionally find Colonists drowned at the bottom of rivers.
[video](https://youtu.be/oco37hkT-Wg)

**Comment by AprilDerg** [comment]
Yeah, I saw that firsthand, although without the path debugging. What I find strange though is why it would happen in an open space. If there are some ceiling related challenges that would make sense, but a clear open path across an uncovered body of water feels strange to me.

**Comment by fulmoonless** [comment]
That's not the point. As long as they are submerged while crossing the river, they will choose a path that causes them to drown.
[video](https://youtu.be/cBawO2dVo7Q)

**Comment by fulmoonless** [comment]
I think it's because the pathing system tries to avoid water routes, but it only considers which blocks the citizen's feet walk on. So, when a citizen encounters a block in the water, the pathing system immediately generates a path along the blocks without considering that this will cause them to suffocate.

[video](https://youtu.be/cBawO2dVo7Q)

**Comment by AprilDerg** [comment]
That seems like quite the oversight.

**Comment by Raycoms** [comment]
Ohh you're all using the industrial village modpack. Yes, there are some hacky broken tweak mods in there that butcher core mechanics because they got no clue what they are doing which is causing this behaviour.

**Comment by AprilDerg** [comment]
Do you by chance know which mod it might be from that modpack? The only one that is labeled as minecolonies tweak mod is MineColonies_Tweaks-1.20.1-2.21, but i checked that mod out at the start and it didn't mention anything about pathing changes or anything even remotely related do that, so I'm not sure which mod to remove.

**Comment by MotionlessTrain** [comment]
That is one of the two mods Raycoms means. The other one is Compatibility for Minecolonies
Those mods change Minecolonies in ways we cannot give support anymore

**Comment by fulmoonless** [comment]
Wait, I should have mentioned this here, sorry. In my test above, I only downloaded Minecolonies (and its dependencies), and I also encountered the same issue with the guards in the official Minecolonies modpack. I believe it's not just an issue with those two mods.
(Sorry, it's my first time using GitHub. I thought I couldn't comment after marking it as complete.)
